### ISSUE TITLE
Docker on server instead of OS ?

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode-remote-release#10009]
The installation for this extension asks for one to install docker for their Operating system; is it possible to use docker on a server instead of installing the one for their Operating System ?

**Comment by chrmarti** [comment]
Yes, you can use Remote SSH or Tunnels to connect to a server which then has Docker installed. See https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host for details. HTH!
