### ISSUE TITLE
.gitconfig not copied into devcontainer

### ISSUE THREAD

**Issue by branic** [microsoft/vscode-remote-release#10022]
My `.gitconfig` file is not being automatically copied into the devcontainer. I have a `.gitconfig` file in my home directory and I have the Dev Containers "Copy Git Config" setting enabled. However, my `.gitconfig` file is not being copied into the container. When I look at the container logs I do not ever see it being tested for like it does with the `known_hosts` and `gpg`  configurations which are both being copied into the container.

I am using Podman as my conatiner engine so I included that in the steps to reproduce, but I can't see how podman would make any difference.

- VSCode Version: 1.90.2
- Local OS Version: Fedora 40
- Remote OS Version: registry.access.redhat.com/ubi9/python-312:1
- Remote Extension/Connection Type: Containers
- Dev Containers Version: v0.369.0

- Logs: 
[devcontainer_logs_no_gitconfig.txt](https://github.com/user-attachments/files/16073201/devcontainer_logs_no_gitconfig.txt)

Steps to Reproduce:

1. Install podman
2. Configure Dev Containers extension to use podman
3. In a new directory create a `.devcontainer` folder
4. In the `.devcontainer` folder create a devcontainer configuration using this 
[devcontainer.json](https://github.com/user-attachments/files/16073237/devcontainer.json) file and a simple Dockerfile:

```Dockerfile
FROM registry.access.redhat.com/ubi9/python-312:1

RUN echo "Installing Poetry" \
  && curl -sSL https://install.python-poetry.org | python3 - \
  && poetry config virtualenvs.in-project true \
  && poetry config virtualenvs.create false

RUN mkdir /opt/app-root/src/workspace/
```

5. Rebuild and reopen in the container

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
Is your local config at `~/.gitconfig`? Maybe VS Code does not have permission to read it?

**Comment by branic** [comment]
The permissions are such that VS Code should be able to read it
```
$ ls -al ~/.gitconfig
-rw-rw-r--. 1 bevans bevans 970 Jun 11 11:45 /home/bevans/.gitconfig
```

Using git outside of the devcontainer works as expected.

**Comment by branic** [comment]
I upgraded to 1.91 today and rebuilt the devcontainer and my .gitconfig was copied into the container as expected. I'll close this issue as it seems to be working now.
