### ISSUE TITLE
Dev Container: `${containerEnv:VAR_NAME}` not properly expanded in `devcontainer.json` in `customizations.vscode.settings`

### ISSUE THREAD

**Issue by georglauterbach** [microsoft/vscode-remote-release#10033]
- VSCode Version: 1.90.0 89de5a8d4d6205e5b11647eb6a74844ca23d2573 x64
- Local OS Version: Ubuntu 22.04.4 LTS (Linux 6.5.0-41-generic #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux)
- Remote OS Version: Ubuntu 22.04.4 LTS (Linux 6.5.0-41-generic #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux)
- Remote Extension/Connection Type: Dev Container over Remote-SSH (verified that the issue also occurs when connecting via RDP without Remote-SSH)
- Logs: N/A

Steps to Reproduce:

1. Write a `devcontainer.json` file with the following content:
   ```jsonc
   {
     // some config, and then
     "containerEnv": {
       "BUILD_OUTPUT_DIR": "${containerWorkspaceFolder}/../build-${containerWorkspaceFolderBasename}"
     },
     // some more config, and then
     "customizations": {
       "vscode": {
         "settings": {
           "sonarlint.pathToCompileCommands": "${containerEnv:BUILD_OUTPUT_DIR}/compile_commands.json",
           "cmake.buildDirectory": "${containerEnv:BUILD_OUTPUT_DIR}",
           "clangd.arguments": [
             "--compile-commands-dir=${containerEnv:BUILD_OUTPUT_DIR}"
           ]
         }
       }
     }
   }
   ```
3. This worked until today, but I am not seeing the following error, for example when configuring with CMake:
   ```ini
   [main] Configuring project: <PROJECT NAME>
   [rollbar] Unhandled exception: Failed writing to file ${containerEnv:BUILD_OUTPUT_DIR}/.cmake/api/v1/query/client-vscode/query.json Error: EACCES: permission denied, mkdir '${containerEnv:BUILD_OUTPUT_DIR}' {}
   [driver] Failed to configure project
   ```
   And I see similar behavior with Clangd, which tells me that the path to my `compile_commands.json` does not exist. Somehow, **it looks like `${containerEnv:BUILD_OUTPUT_DIR}`  is not expanded anymore**...

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: N/A (you need the Dev Container extension)

**Comment by chrmarti** [comment]
Confirmed. This works in the previous stable release 0.369.0 of the Dev Containers extension. You can install that (`F1` > `Extensions: Install Specific Version of Extension...`) until we have this fixed. Thanks.

**Comment by eleanorjboyd** [comment]
Hi @georglauterbach! Are you able to verify if this fix works? You can do so by getting the latest pre-release version of the dev containers extension. We want to make sure we get this bug verified, and the fix is correct, before we release this to stable. Thanks!

**Comment by rzhao271** [comment]
The remote settings.json still does not have the variables expanded.

**Comment by chrmarti** [comment]
Good catch, this didn't make it into a new Dev Containers CLI release yet. Moving to August, thanks.
