### ISSUE TITLE
ssh-remote set custom ssh port is not work

### ISSUE THREAD

**Issue by fanwz** [microsoft/vscode-remote-release#1004]
- VSCode Version:1.36.1
- Local OS Version:Win 10
- Remote OS Version:Centos 7
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.set ssh config like this 
```
Host mycs@localhost
    HostName 127.0.0.1
    User mycs
    Port 5522
    IdentityFile ~/.ssh/id_rsa
```

2.then select connect to this host.

3.and the vs code log show:

> remote-ssh@0.44.2
win32 x64
SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a226c6f63616c686f7374222c2275736572223a226d796373227d", attempt 1
SSH Resolver called for host: mycs@localhost
Setting up SSH remote "localhost"
Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_7.1p1, OpenSSL 1.0.2e 3 Dec 2015
Running script with connection command: "ssh"  -o ClearAllForwardings=true    "mycs@localhost" bash
Install and start server if needed
> 
> ssh: connect to host localhost port 22: Connection refused

why the ssh-remote still use port 22?

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Is this still an issue? `@` may not be allowed in the Host name...
