### ISSUE TITLE
It is not possible to disable the automatic addition of connections to REMOTE PLATFORM

### ISSUE THREAD

**Issue by rsorokaa** [microsoft/vscode-remote-release#10048]
It is not possible to disable the automatic addition of connections to REMOTE PLATFORM, which means that REMOTE_COMMANDS cannot be executed with REMOTE.SSH. What would be the solution?

**Comment by joshspicer** [comment]
Thank you for taking the time to open an issue.  Could you please share your logs (`> Remote-SSH: Show Log` in the command palette) after reproducing the issue?

I think you're referring to the text on the remote command setting, which states Remote Platform must be unset. Could you confirm the Local Server setting is also set appropriately? We will be able to both see this from the Remote - SSH logs.

![Image](https://github.com/user-attachments/assets/8160a15a-fd26-4427-80db-fb6fbd3cdb05)
