### ISSUE TITLE
[Remote-SSH Bug]: After one of the latest releases, it doesnt respect remote.SSH.serverPickPortsFromRange

### ISSUE THREAD

**Issue by rgulden** [microsoft/vscode-remote-release#10043]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### Version

`vscode-portable  1.91.0 ` -- installed via Scoop on windows.

### Expected Behavior

Expected is VSCode remote server will start on one of the ports from the range

### Steps To Reproduce

Attempt to connect to a remote machine and set your server pick port range.

Example settings as below:
```json
{
    "remote.SSH.serverPickPortsFromRange": {
        "my_hostname": "60000-60001"
    },
    "remote.SSH.remotePlatform": {
        "my_hostname": "linux"
    },
    "remote.SSH.enableDynamicForwarding": false
}
```

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[16:43:28.747] > Starting VS Code CLI... "/home/jupyter/.vscode-server/code-ea1445cc7016315d0f572
> 8f8e8b12a45dc0a7286" command-shell --cli-data-dir "/home/jupyter/.vscode-server/
> cli" --on-port --on-host=127.0.0.1 --parent-process-id 2832 &> "/home/jupyter/.v
> scode-server/.cli.ea1445cc7016315d0f5728f8e8b12a45dc0a7286.log" < /dev/null   
```

</p>
</details>

### Anything else?

As you can see from the log, it is not giving a port to `--on-port` even when the following config is passed `[16:43:27.009] "remote.SSH.serverPickPortsFromRange": {"my_hostname":{"start":60000,"end":60001}}`

Error message if cant use port `[11:56:51.530] > channel 3: open failed: administratively prohibited: open failed` on remote machine.

In the following issue a similar problem happened with `OnHost`, I would think the fix is similar. https://github.com/microsoft/vscode-remote-release/issues/9963

**Comment by austinbspencer** [comment]
I'm experiencing the same issue

**Comment by rgulden** [comment]
@roblourens @connor4312 - Is there anyway you could quickly look into this. I believe its a quick fix based off of the linked issue. Thanks!

**Comment by roblourens** [comment]
Looks like this isn't respected for execServer mode, you can disable `useExecServer` if you need it

**Comment by joshspicer** [comment]
@rgulden There's a little bit of info in this wiki - https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting#remotesshuseexecserver---exec-server-mode.  Having this setting enabled utilizes the VS Code CLI

**Comment by connor4312** [comment]
This'll be fixed in the prerelease of Remote - SSH on VS Code Insiders next week
