### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by Drong0305** [microsoft/vscode-remote-release#10055]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Steps To Reproduce

1.in any environment
2.click the left button  of ssh
![image](https://github.com/user-attachments/assets/c4e6dac0-be04-4336-ba41-dcd30f0b9d8b)
3.then just nothing come out
![image](https://github.com/user-attachments/assets/7b710555-0c5c-41e5-962d-339a62e333f8)

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
[10:40:53.959] Log Level: 2
[10:40:54.045] VS Code version: 1.91.1
[10:40:54.045] Remote-SSH version: remote-ssh@0.113.2024070816
[10:40:54.045] win32 x64
[10:41:01.832] Picking SSH host
[10:41:12.965] Picking SSH host
[10:41:47.189] Picking SSH host
[10:48:32.236] Picking SSH host
[10:49:30.110] Picking SSH host
[10:50:21.833] Picking SSH host
[10:58:32.014] Picking SSH host
[10:58:49.815] Picking SSH host
```

</p>
</details>

### Anything else?

I edited the ssh config file recently.

**Comment by joshspicer** [comment]
We fixed an issue earlier this year that has the same repro steps as you: https://github.com/microsoft/vscode-remote-release/issues/10341

If the issue is fixed - great. If not, could you share the extension host logs (like was done in the attached issue). That's probably where any error would be. Thanks!
