### ISSUE TITLE
Debug mode doesnt works

### ISSUE THREAD

**Issue by sensensation** [microsoft/vscode-remote-release#10057]
Type: <b>Bug</b>

Finishin running tests message appeare always during debug mode. It cant event start

Extension version: 0.327.0
VS Code version: Code 1.84.2 (Universal) (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin arm64 23.1.0
Modes:
Remote OS version: Linux x64 6.6.26-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|32.00GB (1.79GB free)|
|Process Argv|--crash-reporter-id 8a3940e0-3931-4f3e-89ef-aeefac9547fd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container orders-app (orders_app) @ desktop-linux|
|OS|Linux x64 6.6.26-linuxkit|
|CPUs|unknown (10 x 0)|
|Memory (System)|30.31GB (23.45GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
legacy_priority:31082724
refactorc:31093864
pythonrstrctxt:31093869
0c838689:31092287

```

</details>

**Comment by bamurtaugh** [comment]
Hi there, thanks for the issue. Could you please provide some more details:
- What steps have you taken? This would be a great help so that we can try to reproduce the issue
- What is the message you're seeing?
- What can't start?
- Which remote extension(s) are you using?
