### ISSUE TITLE
SSH Always asks for a Password ? 

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode-remote-release#10053]
I'm asking this question in relation to [this](https://github.com/microsoft/vscode-remote-release/issues/2728); I too cannot get SSH to stop asking for a password ?

**Comment by joshspicer** [comment]
Thank you for taking the time to open an issue. Please share your logs (`> Remote-SSH: Show Log` in the command palette) after reproducing the issue so we can better understand the specific issue you're facing.
