### ISSUE TITLE
how to close the notice by doing Nothing :   You are connected to an OS version that is unsupported by Visual Studio Code.

### ISSUE THREAD

**Issue by abetday** [microsoft/vscode-remote-release#10056]
🚨 The issue tracker is not for questions 🚨
![image](https://github.com/user-attachments/assets/31ea35ff-da22-4ba8-bb1a-006bb6ecaea1)

If you have a question about VS Code, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code and about
VS Code Remote on https://stackoverflow.com/questions/tagged/vscode-remote.

**Comment by bamurtaugh** [comment]
Hi there, thanks for the issue. I believe you'll see the notice until you move to an OS version that is supported by VS Code.

cc @isidorn in case I'm missing anything.
