### ISSUE TITLE
Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.)

### ISSUE THREAD

**Issue by warmkid** [microsoft/vscode-remote-release#1006]
[createInstance] extensionManagementService depends on storageService which is NOT registered.

**Comment by B3zo0** [comment]
I see this as well. I can not start vscode insiders from wsl.

Version: 1.37.0-insider (user setup)
Commit: 81ed55af79f01e9e64c3438558d2c2233e382a5a
Date: 2019-07-22T07:16:47.743Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
- Local OS Version: Win 10.0.18362
- Remote OS Version: WSL version: 4.4.0-18362-Microsoft Ubuntu
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. try to open vscode from wsl


Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by M1XZG** [comment]
> I see this as well. I can not start vscode insiders from wsl.
> 
> Version: 1.37.0-insider (user setup)
> Commit: 81ed55af79f01e9e64c3438558d2c2233e382a5a
> Date: 2019-07-22T07:16:47.743Z
> Electron: 4.2.5
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.18362
> 
> * Local OS Version: Win 10.0.18362
> * Remote OS Version: WSL version: 4.4.0-18362-Microsoft Ubuntu
> * Remote Extension/Connection Type: WSL
> 
> Steps to Reproduce:
> 
> 1. try to open vscode from wsl
> 
> Does this issue occur when you try this locally?: Yes
> Does this issue occur when you try this locally and all extensions are disabled?: Yes

I'm having exactly the same issue, this seems to have started last week after this version of Code was pushed out .. before this update everything was working well.

**Comment by yazinsai** [comment]
+1 Same error here using insiders on WSL v1

**Comment by SriRamanujam** [comment]
Version: 1.37.0-insider (user setup)
Commit: 81ed55af79f01e9e64c3438558d2c2233e382a5a
Date: 2019-07-22T07:16:47.743Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Seeing the same issue here when launching Code via interop in WSL. It sets up the remote environment without issue when I launch Code via Windows and open the workspace/folder directly.

**Comment by masojus** [comment]
In `<VS Code install location>\bin\code-insiders` it looks like `WSL_EXT_WLOC=[createInstance] extensionManagementService depends on storageService which is NOT registered.` which seems odd. In case it helps, here is the output running `code-insiders .` from WSL with `set -x` at that top of that script:

```

+ COMMIT=81ed55af79f01e9e64c3438558d2c2233e382a5a
+ APP_NAME=code-insiders
+ QUALITY=insider
+ NAME=Code - Insiders
+ DATAFOLDER=.vscode-insiders
+ realpath /mnt/c/Users/<USERNAME>/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders
+ dirname /mnt/c/Users/<USERNAME>/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders
+ dirname /mnt/c/Users/<USERNAME>/AppData/Local/Programs/Microsoft VS Code Insiders/bin
+ VSCODE_PATH=/mnt/c/Users/<USERNAME>/AppData/Local/Programs/Microsoft VS Code Insiders
+ ELECTRON=/mnt/c/Users/<USERNAME>/AppData/Local/Programs/Microsoft VS Code Insiders/Code - Insiders.exe
+ grep -qi Microsoft /proc/version
+ [ Legacy ]
+ WSL_BUILD=18362
+ [ 18362 -ge 17063 ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:
+ wslpath -m /mnt/c/Users/<USERNAME>/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/cli.js
+ CLI=C:/Users/<USERNAME>/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/<USERNAME>/AppData/Local/Programs/Microsoft VS Code Insiders/Code - Insiders.exe C:/Users/<USERNAME>/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/cli.js --locate-extension ms-vscode-remote.remote-wsl
+ WSL_EXT_WLOC=[createInstance] extensionManagementService depends on storageService which is NOT registered.
c:\Users\<USERNAME>\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.39.0
+ [ -n [createInstance] extensionManagementService depends on storageService which is NOT registered.
 ]\Users\<USERNAME>\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.39.0
+ wslpath -u [createInstance] extensionManagementService depends on storageService which is NOT registered.
c:\Users\<USERNAME>\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.39.0
+ WSL_CODE=[createInstance] extensionManagementService depends on storageService which is NOT registered.
c:/Users/<USERNAME>/.vscode-insiders/extensions/ms-vscode-remote.remote-wsl-0.39.0/scripts/wslCode.sh
+ [createInstance] extensionManagementService depends on storageService which is NOT registered.
c:/Users/<USERNAME>/.vscode-insiders/extensions/ms-vscode-remote.remote-wsl-0.39.0/scripts/wslCode.sh 81ed55af79f01e9e64c3438558d2c2233e382a5a insider /mnt/c/Users/<USERNAME>/AppData/Local/Programs/Microsoft VS Code Insiders/Code - Insiders.exe code-insiders .vscode-insiders .
/mnt/c/Users/<USERNAME>/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders: 39: /mnt/c/Users/<USERNAME>/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders: [createInstance] extensionManagementService depends on storageService which is NOT registered.
c:/Users/<USERNAME>/.vscode-insiders/extensions/ms-vscode-remote.remote-wsl-0.39.0/scripts/wslCode.sh: not found
+ exit 127
```

**Comment by masojus** [comment]
For what it's worth, when I run `code-insiders --locate-extension ms-vscode-remote.remote-wsl` from a Windows CMD prompt, this is the output: ```[createInstance] extensionManagementService depends on storageService which is NOT registered.
c:\Users\tweek\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.39.0```
...so that first line of error output is likely the cause.

**Comment by masojus** [comment]
Yeah, I changed line 35 in `<VS Code install location>\bin\code-insiders` to only grab the last line of output: `WSL_EXT_WLOC=$(ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --locate-extension $WSL_EXT_ID | tail -1)` and things **appear** to be working normally now.

**Comment by aeschli** [comment]
dup of #1012
