### ISSUE TITLE
Remote commands not posible in remote.ssh VS

### ISSUE THREAD

**Issue by rsorokaa** [microsoft/vscode-remote-release#10066]
Type: <b>Bug</b>

Its not posible send remote_command. For my example i log with user1 in my remote_machine, and try log with other user2, but the remote command not executed in remote.ssh extension in VS.

Extension version: 0.113.2024070816
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 4.18.0-305.el8.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1365U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.64GB (4.00GB free)|
|Process Argv|--crash-reporter-id 9d9cab6e-7763-45ea-9c2f-eeb1242fe2da|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: aviserverco4|
|OS|Linux x64 4.18.0-305.el8.x86_64|
|CPUs|Intel Xeon Processor (Skylake, IBRS, no TSX) (32 x 0)|
|Memory (System)|15.45GB (11.41GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
legacy_priority:31094926
pythonrstrctxtcf:31093870

```

</details>

**Comment by joshspicer** [comment]
Thank you for taking the time to open an issue.  Could you please share your logs (`> Remote-SSH: Show Log` in the command palette) after reproducing the issue?
