### ISSUE TITLE
can't run python file, says extension not installed but it is

### ISSUE THREAD

**Issue by rbavery** [microsoft/vscode-remote-release#10064]
Type: <b>Bug</b>

I'm running Vscode on a Mac M1, remote sshing into an Ubuntu desktop, and then remoting into the dev container running on my desktop. I can't start jupyter notebooks or run python files after updating vscode on my desktop. I get an error saying the extension is not found and a prompt to install the extension but it is already installed.

Extension version: 0.327.0
VS Code version: Code 1.84.2 (Universal) (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin arm64 23.4.0
Modes:
Connection to 'ssh-remote+10.0.0.156' could not be established
Remote OS version: Linux x64 6.5.0-41-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id 812585f6-38c7-486f-9c05-ad075248e4d2|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+10.0.0.156' could not be established

|Item|Value|
|---|---|
|Remote|Container gpu-wherobots-inference-gpu (gpu-wherobots-inference-gpu-1) @ 10.0.0.156|
|OS|Linux x64 6.5.0-41-generic|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4294)|
|Memory (System)|31.26GB (24.93GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31094925
pythonrstrctxtcf:31093870

```

</details>

**Comment by chrmarti** [comment]
Please update to the latest version of VS Code (1.91.1) and Dev Containers (0.375.1) and retry.

**Comment by rbavery** [comment]
this was resolved not by updating (I think I was on the latest version) but by starting my container with a different custom user that was set up in the base image.
