### ISSUE TITLE
fileWatcher CPU 100%

### ISSUE THREAD

**Issue by olegKusov** [microsoft/vscode-remote-release#10060]
- VSCode Version:  1.91.1 
- Local OS Version: 14.1.1 
- Remote OS Version: DO NOT using remote

- Logs:

Steps to Reproduce:

1. im using SVN repository.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

If I disable Remote - SSH extensions (Remote - SSH, Remote - SSH: editing configuration files, Remote Explorer) the problem do not exists.

**Comment by connor4312** [comment]
I think changes in https://github.com/microsoft/vscode-remote-ssh/compare/remote-ssh.0.110.1...remote-ssh.0.112.0#diff-748f338a0405f0c0c6306e0670469d1e6ed71fa5daed485a87aabcbab82541a2 might have introduced some kind of pathological case.

@olegKusov if possible, could you share your SSH config file(s) so we can get a repro? Feel free to redact IP's etc.

**Comment by joshspicer** [comment]
Please feel free to re-open if you are still able to reproduce and are able to provide updated logs for us to try to reproduce the issue. Thanks
