### ISSUE TITLE
Can't connect to Host with ":" in name

### ISSUE THREAD

**Issue by yaxin-cn** [microsoft/vscode-remote-release#1007]
- VSCode Version: 1.36.1
- Local OS Version: 10.0.18362 暂缺 Build 18362
- Remote OS Version: Ubuntu 18.04.2 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

When I use Remote-SSH to connect my ubuntu developer server, it give me an alert: 

![image](https://user-images.githubusercontent.com/2509813/61621167-f49c2a80-aca4-11e9-8ec3-6dd4a98dbe2b.png)

and the detail output is:

```
remote-ssh@0.44.2
win32 x64
SSH Resolver called for "ssh-remote+devbox:", attempt 1
SSH Resolver called for host: devbox:
Setting up SSH remote "devbox:"
Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
Running script with connection command: "ssh"  -o ClearAllForwardings=true    "devbox:" bash
Install and start server if needed
> 
> ]0;C:\Windows\SYSTEM32\cmd.exe
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 文件名、目录名或卷标语法不正确。
> 
"install" terminal command done
Received install output: 文件名、目录名或卷标语法不正确。
Failed to parse remote port from server output: 文件名、目录名或卷标语法不正确。

------
```

I clear my vscode config file, and it still give me an error.

**Comment by roblourens** [comment]
Why is there a colon in your remote name, `devbox:`? How did you set up ssh?

**Comment by yaxin-cn** [comment]
> Why is there a colon in your remote name, `devbox:`? How did you set up ssh?

yes, and I can ssh to it under cmd ssh directly.

![image](https://user-images.githubusercontent.com/2509813/61757614-e3156880-adf3-11e9-941d-1a1ca3a19df7.png)
![image](https://user-images.githubusercontent.com/2509813/61757681-34bdf300-adf4-11e9-94a0-33dafaea1b09.png)

**Comment by roblourens** [comment]
I can repro this, it seems cmd.exe has some issue with combining a quoted ":" in an argument, with the pipe operator. Confusing, I guess for now you could rename your host to not have a :

**Comment by yaxin-cn** [comment]
oh, I'm sorry. I forget that the ssh config Host alias do not require ":" at the end. After remove the ":", I got the correct result.
