### ISSUE TITLE
remote protocol links support tunnel

### ISSUE THREAD

**Issue by unship** [microsoft/vscode-remote-release#10077]
current vscode support following remote protocol links, which can be used in project manager extension to dirrect open project in remote machine.
```
vscode://vscode-remote/wsl+CONTAINER_NAME/path/to/file
vscode://vscode-remote/ssh-remote+[USER@]HOST[:PORT]/path/to/file:ROW:COL
```

So I need this link to support tunnel, the syntax for this can be `vscode://vscode-remote/tunnel+machinename/path/to/file:ROW:COL`

**Comment by connor4312** [comment]
This works now with --openExtenernal in the remote CLI

**Comment by GHF** [comment]
@connor4312 Can you please provide the URL format necessary to open a file on a remote tunnel, and/or a link to the documentation for the feature? The author's suggested format `vscode://vscode-remote/tunnel+machinename/path/to/file` pointed me towards trying:

```sh
code --open-url 'vscode://vscode-remote/tunnel+desktop/home/xo/.gitconfig'
```

where my remote tunnel server is named `desktop` and the file I'm trying to open is `~/.gitconfig`. I get this dialog:

<img width="260" alt="Image" src="https://github.com/user-attachments/assets/2ac88182-1a81-49c8-bd63-b184cf42e9ad" />

This URL seems to have been modified on the way into Code. If I click "Yes," then I see this:

![Image](https://github.com/user-attachments/assets/698eca4b-e70b-4579-b84b-4b7a0db8ead4)

Based on the color scheme, this seems like Code trying to connect to a remote tunnel named `vscode-remote` and I'm not entirely sure what local workspace it's on or what workspace it _would_ try to open on the remote (assuming it had correctly connected to `desktop`).

Additionally, I've tried `code --openExtenernal <url>`, `code --openExternal <url>`, `code --open-external <url>`, each of which resulted in the warning `Warning: 'openExtenernal' is not in the list of known options, but still passed to Electron/Chromium.` (or similar).

**Comment by connor4312** [comment]
If you just want to open via the CLI, you can use the format `code-insiders --remote tunnel+<name here> <path here>`





`

**Comment by GHF** [comment]
> If you just want to open via the CLI

No, I want to use the system URL handler for the `vscode:` protocol, per the original issue. I used the CLI to test out the functionality and because you closed the issue mentioning a CLI change. If the remote protocol links _don't_ support tunnels, please reopen this issue.

**Comment by connor4312** [comment]
The format in https://github.com/microsoft/vscode-remote-release/issues/10077#issuecomment-2537477168 works. As the notifications says though in the screenshot, it requires the remote tunnels extension to use.
