### ISSUE TITLE
I can't download the various python extensions

### ISSUE THREAD

**Issue by MargaretDefang** [microsoft/vscode-remote-release#10076]
Type: <b>Performance Issue</b>

I can't download the various python extensions. I have been getting "ERROR WHILE FETCHING EXTENSIONS. XHR FAILED"

Extension version: 0.4.3
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2492)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.78GB (0.59GB free)|
|Process Argv|--crash-reporter-id bf79b9b2-c4f9-4062-84cd-7c7185e50a9b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   108	  4124	code main
    0	   118	  1084	   gpu-process
    0	    91	  3752	   window
    2	   154	  4676	extensionHost [1]
    0	   100	  5188	     "C:\Users\USER\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=4676
    1	   103	  4820	window [2] (Issue Reporter)
    0	   112	  8288	shared-process
    0	    87	  8308	ptyHost
    0	    68	  1560	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     6	 11332	     conpty-agent
    1	    41	  8524	   utility-network-service
    0	    83	  8972	fileWatcher [1]
    0	    28	  9164	   crashpad-handler
    0	   220	  9524	window [1] (Extension: Python Language Basics - react-app - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: Python Language Basics - react-app - Visual Studio Code)
|    Folder (react-app): 21 files
|      File types: json(4) tsx(3) svg(2) css(2) ts(2) cjs(1) gitignore(1)
|                  html(1) md(1)
|      Conf files: package.json(1) tsconfig.json(1);
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31094925

```

</details>

**Comment by bamurtaugh** [comment]
Thanks for letting us know. Could you please provide some more details:
- Which remote extension(s) are you using?
- Which Python extension(s) are you trying to install, and how?
- Do other extensions install correctly?
