### ISSUE TITLE
rg heavy disk I/O searching for package.json in a large project

### ISSUE THREAD

**Issue by John-Ao** [microsoft/vscode-remote-release#10086]
- VSCode Version: 1.91.1
- Local OS Version: Ubuntu 22.04
- Remote OS Version: local docker conatiner running ubuntu 20.04
- Remote Extension/Connection Type: Containers

When I start VS Code and attach to the running container, an `rg` process starts wtih the following command:
```
/home/[xxx]/.vscode-server/bin/[xxx]/node_modules/@vscode/ripgrep/bin/rg --files --hidden --case-sensitive --no-require-git -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/Thumbs.db -g !**/.classpath -g !**/.factorypath -g !**/.project -g !**/.settings -g !**/node_modules/** --no-ignore --follow --no-config --no-ignore-global
```
Since it is a large project with many files, this command immediately leads to a high disk I/O load and significantly slows down the OS.

I found the [closed issue 9738](https://github.com/microsoft/vscode-remote-release/issues/9738) with similar problem where the cause is that the dev conatiner extension uses rg to search for `devcontainer.json`. I also had this "dev container" problem earlier and it was solved by updating this extension to `v0.375.1`. But I don't know what causes the "package.json" problem.

**Comment by chrmarti** [comment]
It must be a different extension causing this. Could you run `F1` > `Help: Start Extension Bisect` to find which?

**Comment by John-Ao** [comment]
> It must be a different extension causing this. Could you run `F1` > `Help: Start Extension Bisect` to find which?

I find that it is because of the `vscode-icons-team.vscode-icons` extension. Thank you!
