### ISSUE TITLE
devcontainers: "ENOENT: no such file or directory" when trying to build Laravel Sail container

### ISSUE THREAD

**Issue by parapente** [microsoft/vscode-remote-release#10085]
- VSCode Version: 1.91.1
- Local OS Version: Ubuntu Linux 24.04
- Remote Extension/Connection Type: Containers

Steps to Reproduce:

1. ```curl -s "https://laravel.build/example-app?with=mariadb,mailpit&devcontainer" | bash```
2. cd example-app && code .
3. Try to reopen in container

There is no problem when trying either ```./vendor/bin/sail up``` or using the devcontainers/cli and running ```devcontainer build --workspace-folder .```

```bash
% devcontainer --version
0.57.0
```

[remoteContainers-2024-07-20T16-47-32.155Z.log](https://github.com/user-attachments/files/16321771/remoteContainers-2024-07-20T16-47-32.155Z.log)

The problem seems to be with the relative path of the context property in ```docker-compose.yml```. It doesn't use the project root path but the path from the extension. This used to work correctly in previous versions of vscode and the remote extension. I tested it in vscode-insiders and it still doesn't work. I also tested both with docker-compose and docker with builderx and got the same error message.

**Comment by parapente** [comment]
Some more notes:

I tested vscode 1.90, even with a clean profile (removed ~/.vscode and ~/.config/Code), but it still doesn't work. I also tried the previous versions of the remote extension from this year but they give the same error message.

What works:
If I use the cli devcontainer command ```devcontainer up --workspace-folder .``` and then try to reconnect from vscode to the container, it works just fine.

**Comment by chrmarti** [comment]
Could you update to a more recent Docker Compose? The log shows:
```
[2024-07-20T16:47:33.693Z] Stop (73 ms): Run: docker compose version --short
[2024-07-20T16:47:33.693Z] Docker Compose version: v2.0.1
```

**Comment by parapente** [comment]
I tested it with the latest docker-ce version and it wouldn't work. I'll retest and upload the new log.

**Comment by parapente** [comment]
Log with docker-ce
[remoteContainers-2024-07-22T12-36-21.496Z.log](https://github.com/user-attachments/files/16333192/remoteContainers-2024-07-22T12-36-21.496Z.log)

**Comment by chrmarti** [comment]
The new log still shows the old version: `Docker Compose version: v2.0.1`. You might need to update a separate package.

**Comment by parapente** [comment]
@chrmarti you are correct. I had an old version of the docker compose plugin installed in ```~/.docker/cli-plugins``` which was taking precedence on any new install and I didn't even remember installing. Thank you for your help.
