### ISSUE TITLE
[Remote-SSH Bug]: Make it so VSCode doesn't eat 100% of VPS CPU 

### ISSUE THREAD

**Issue by verybigelephants** [microsoft/vscode-remote-release#10098]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

Once in every while, a new employee with VSCode comes in, connects to our remote VPS with it and then this happens:

![image](https://github.com/user-attachments/assets/f5b9563a-ef67-492a-9829-8cca6d5eb36b)

When lookint at htop there's some vscode script eating all the cpu. 

I didn't believe them so i went to do a fresh vscode install with remote ssh extension, connected to our VPS and there it was, server was crashing.

Now, i understand vscode probably crawls the server to see the directory structure, but can't this behavior be not enabled by default? This is a truly invasive feature that can crash machines. There should be a button and big warning before indexing the whole machine telling users that this can crash the remote servers.

### Expected Behavior

Not crash remote vps

### Steps To Reproduce

1 connect to a remote vps
2 crash server with 100% cpu usage

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

### Anything else?

I have searched for other similar issues like this, and tried tips like disabling "follow symlinks" but it doesn't really help.

**Comment by roblourens** [comment]
> Now, i understand vscode probably crawls the server to see the directory structure

VS Code doesn't do this. Most likely there's some extension doing a lot of work when a workspace is opened. Could be a builtin extension like the js/ts extension, or another one that is installed on the remote. This wiki page might help: https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting#performance-issues

**Comment by verybigelephants** [comment]
I understand, thank you for the reply

I have managed to see that it's caused by devsense.phptools
