### ISSUE TITLE
Skip creation of `./.github/dependabot.yml` by default

### ISSUE THREAD

**Issue by ndlarsen** [microsoft/vscode-remote-release#10095]
Currently when creating a dev container, a `./.github/dependabot.yml` is added. Looking through the extension's settings I have found no obvious way to prevent this. I suggest this is configurable and disabled by default.

**Comment by chrmarti** [comment]
This is added by the templates. I wonder if we should have a setting to skip all files in `.github`.

**Comment by chrmarti** [comment]
Or we could add it as an option in the UI when adding the configuration.

**Comment by ndlarsen** [comment]
> Or we could add it as an option in the UI when adding the configuration.

Having an option in the GUI drop down when creating a new dev container could probably be nice as it might be situational when the config is needed.

**Comment by joshspicer** [comment]
Related to https://github.com/devcontainers/features/issues/916

**Comment by joshspicer** [comment]
Will keep this open until we publish a pre-release of the dev containers extension (set to release by the end of this milestone 😄 )

**Comment by joshspicer** [comment]
Support for Templates that declare `optionalPaths` has shipped in the Dev Containers extension pre-release `v0.382.0`.

I've re-published all the Templates in [the devcontainers/templates repo](https://github.com/devcontainers/templates) to declare `.github` as optional.

https://github.com/user-attachments/assets/22d79a21-cf43-4e64-841e-08c102713a6d

Please give the feature a try and let us know how it feels.
