### ISSUE TITLE
Setting a version on a devcontainer feature breaks feature option intellisense

### ISSUE THREAD

**Issue by Clockwork-Muse** [microsoft/vscode-remote-release#10090]
Version: 
- VSCode Version: 1.91.1 (user setup)
  - Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
  - Date: 2024-07-09T22:06:49.809Z
  - Electron: 29.4.0
  - ElectronBuildId: 9728852
  - Chromium: 122.0.6261.156
  - Node.js: 20.9.0
  - V8: 12.2.281.27-electron.0
- Local OS Version: Windows_NT x64 10.0.22631
- Remote OS Version: Ubuntu 22.04
- Remote Extension/Connection Type: Containers/WSL/Server

When adding a feature to a devcontainer, intellisense for feature options does not appear if a version (or even just the colon separator) is specified.
Without feature version: 
![image](https://github.com/user-attachments/assets/403b3fbe-6103-46d4-a30a-5c7629b1eb68)
With feature version:
![image](https://github.com/user-attachments/assets/522b6bc2-e2f3-407b-9564-fdbd0f894e3e)

- Logs:

Steps to Reproduce:

 1. With the following devcontainer:
```json
{
	"name": "Alpine",
	"image": "mcr.microsoft.com/devcontainers/base:alpine-3.20",
	"features": {
		"ghcr.io/devcontainers/features/azure-cli:1.2.5": {

		}
	}
}
```
 2. Place the cursor between the two open brackets for the azure-cli feature and hit `Ctrl+Space`.
 3. Observe that intellisense returns a set of "unrelated" text, not the options for the feature.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
This fix is available in Dev Containers 0.381.0-pre-release.

**Comment by rzhao271** [comment]
On 0.382.0 pre-release, I get "No code actions available" no matter whether or not I have a version set.

**Comment by chrmarti** [comment]
The issue was that there were no specific IntelliSense suggestions (only the unspecific word collection). There are no code actions at the moment.

To verify please check if you get IntelliSense with suggestions that match the feature's options, e.g.:
![Image](https://github.com/user-attachments/assets/e68e85a2-0a7a-4fb6-95ca-29c3f8ab543f)
