### ISSUE TITLE
Remote containers: Support of changing folder mount path without Docker Compose

### ISSUE THREAD

**Issue by asyncx** [microsoft/vscode-remote-release#101]
It would be useful if the `workspaceFolder` setting in `devcontainer.json` worked for changing the folder mount path without using Docker Compose. This would make it easier to integrate with existing container setups.

**Comment by vnijs** [comment]
Looks like this would also address the following 2 questions on SO:

https://stackoverflow.com/questions/55970168/how-to-change-default-volume-mount
https://stackoverflow.com/questions/56158307/mounting-local-directory-to-home-directory-in-container

**Comment by Chuxel** [comment]
FYI - Most of the discussion related to this is happening in #171 which expands the scope beyond this slightly but would necessitate this kind of change. `workspaceFolder` is still needed to allow you to pick a different folder inside the container or volume mount where the project exists.  We're discussing a new property for this kind of thing among others.

**Comment by chrmarti** [comment]
`workspaceFolder` won't change the mount point, it will only change which folder VS Code opens on. We will add another option to control the mount point and options.
