### ISSUE TITLE
[Remote-SSH Bug]: Remote SSH connection fails after VSCode update to 1.91.0/1.91.1

### ISSUE THREAD

**Issue by bhavyavm** [microsoft/vscode-remote-release#10103]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Bug Description
I am experiencing issues connecting to a remote SSH server after updating VSCode to version 1.91.0 and 1.91.1. Prior to this update, the connection was working fine. Here are the details of my setup and the error message I am encountering:

**Local Environment:**
- **Operating System:** macOS 14.5
- **VSCode Version:** 1.91.1 (universal)

**Remote Environment:**
- **Operating System:** Linux RHEL 8.9

### Expected Behavior
It was working fine till the VSCode update 1.91.0 release. After that, it stopped connecting to the host and we tried with release 1.91.1 and found the same error.

### Steps To Reproduce
1. Local OS version: macOS 14.5
2. VSCode version: 1.91.1 (universal)
3. Attempt to connect to remote SSH to the ADS on Linux RHEL 8.9

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
>     ACME_SUBLIST_PATH=/nfs/acmecontrol/usrlu/sanos/sublist
>     WR_X86_XEON_GCC_LIB_DIR=/auto/andpkg/rep_cache//wr-x86-xeon/5.0/toolchain/x86_64-wrlinuxsdk-linux/usr/toolchain/lib/gcc/i686-wrs-linux-gnu/4.6.3
>     ATC_BASE_U=/auto/andpkg/rep_cache/
>     ATC_BASE_L=/auto/andatcd
>     ATC_BASE_I=/auto/dcos-sw-hard/base-dcos-sw/andatc/independent
>     ATC_BASE_D=/auto/andatcd-hard
>     ATC_BASE_B=/auto/andatc/independent
>     _=/auto/andatcd/coreutils/8.17/bin/printenv
> Removing old logfile at /nobackup/pkr2/.vscode-server/.cli.dc96b837cf6bb4af9cd736aa3af08cf8279f7685.log
> Spawned remote CLI: 3994452
[17:35:46.190] > GPL Ghostscript 9.27: Unrecoverable error, exit code 1
[17:35:46.206] > Exec server process not found
> Listening on 127.0.0.1:36475
.....
 
[17:35:46.369] Failed to parse remote port from server output
[17:35:46.370] Exec server for ssh-remote+xxx-xx-xx failed: Error
[17:35:46.370] Error opening exec server for ssh-remote+xxx-xx-xx: Error
```

</p>
</details>

**Comment by peterwaller-arm** [comment]
I've just experienced this as well and root caused it to being out of disk space where `~/.vscode-server` is stored on the target I was connecting to. There was no obvious hint in the vscode logs that this was the case, I saw something very similar to what was reported above.

Experienced it on vscode 1.89.1, mac host, linux remote; remote extension version v0.112.0.

**Comment by roblourens** [comment]
Could you share the full log? Does disabling `useExecServer` fix it?
