### ISSUE TITLE
Ctrl+F find functionality in the Remote Explorer no longer works.

### ISSUE THREAD

**Issue by georgitrifonov** [microsoft/vscode-remote-release#10105]
Type: <b>Bug</b>

After updating to the latest version of Visual Studio Code, the Ctrl+F find functionality in the Remote Explorer no longer works. This issue started immediately after the update.

Steps to Reproduce

	1.	Open Visual Studio Code.
	2.	Select Remote Explorer.
	3.	Press Ctrl+F to search for SSH sessions or folders within the Remote Explorer.

Expected Behavior

Pressing Ctrl+F should open the find input box, allowing me to search for SSH sessions or folders within the Remote Explorer.

Extension version: 0.4.3
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:46.768Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|32.00GB (0.59GB free)|
|Process Argv|--crash-reporter-id 5a884c43-72a5-4104-ba64-58b8a88693f0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactorc:31101458
ccplti:31103428
pythonrstrctxt:31103193
wkspc-onlycs-c:31102393

```

</details>

**Comment by georgitrifonov** [comment]
Hi, I found that everything works normally in version 1.88 (March 2024), but since version 1.89 (April 2024), the ctrl+f functionality in Remote Explorer has stopped working.

**Comment by roblourens** [comment]
The keybinding chanaged, it's now ctrl+alt+f
