### ISSUE TITLE
Option to ignore default features in devcontainer recovery container

### ISSUE THREAD

**Issue by evilhamsterman** [microsoft/vscode-remote-release#10115]
When a devcontainer fails to build VSCode will offer to let you open it in a recovery container to try and fix the devcontainer.json. It will still install the default features that are set in the devcontainers extensions settings, however sometimes the issue is with a one of the default features, or the feature relies on something like `apt-get` but the recovery container is based on Alpine so that command is not available. To get into the recovery container then you have to open a new window, because you can't access settings in the broken window, and remove or comment out the problem feature. Fix the issue then reenable the problem feature.

Kind of like safe mode for Windows, the recovery container should not load anymore than is necessary to open the editor. Or at least have that as an option.

**Comment by joshspicer** [comment]
Related to https://github.com/devcontainers/features/issues/916

**Comment by joshspicer** [comment]
Repro steps:

- Add a Feature to defaultFeatures setting that will fail to install on alpine, eg:
```json
  "dev.containers.defaultFeatures": {
    "ghcr.io/devcontainers/features/docker-in-docker:2": {}
  }
```
- Select a GitHub repo that has a broken configuration (to force recovery mode), eg: https://github.com/codspace/broken-project
- Create a new dev container by cloning to volume with `Dev Containers: Clone Repository in Container Volume` and select the GitHub Repo
- Select `Edit devcontainer.json in Recovery Container`
- Note that the recovery container fails to create, logs confirm:
```
Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/base:0-alpine-3.20
...
...
0.092 ./install.sh: line 192: dpkg: command not found
0.092 ERROR: Feature "Docker (Docker-in-Docker)" (ghcr.io/devcontainers/features/docker-in-docker) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/docker-in-docker for help troubleshooting this error.
------
```

Removing the `defaultFeatures` setting and retrying the steps above successfully opens to a recovery container

**Comment by joshspicer** [comment]
Thanks for the report! This should be fixed in the next pre-release of the extension (i'll keep this issue around until we publish that)

**Comment by joshspicer** [comment]
This change has shipped in pre-release `v0.382.0`.  Please let us know if the change helps!

**Comment by rzhao271** [comment]
In the recovery container, I see --additional-features passed in the logs, but those logs seem to reflect the failed container build attempt. The recovery container loads properly.

**Comment by evilhamsterman** [comment]
Sorry it took a bit to get back to it. I verified it with the v0.383.0 release. Including a default feature that uses apt to install a package no longer breaks the recovery container

**Comment by joshspicer** [comment]
Appreciate you giving it a go, thanks!
