### ISSUE TITLE
storageService which is NOT registered

### ISSUE THREAD

**Issue by xietao1233** [microsoft/vscode-remote-release#1012]
/mnt/d/Program Files (x86)/Microsoft VS Code Insiders/bin/code-insiders: 37: /mnt/d/Program Files (x86)/Microsoft VS Code Insiders/bin/code-insiders: [createInstance] extensionManagementService depends on storageService which is NOT registered.
c:/Users/taoism/.vscode-insiders/extensions/ms-vscode-remote.remote-wsl-0.39.0/scripts/wslCode.sh: not found

**Comment by Tyriar** [comment]
Verified via code review
