### ISSUE TITLE
The remote ssh pannel is stuck by some private url request every time of opening

### ISSUE THREAD

**Issue by walkerlala** [microsoft/vscode-remote-release#10138]
Type: <b>Bug</b>

When never opening the "remote ssh" pannel (on the left hand side), it seems that it is stuck on processing something. On some occasion I noticed that it seems to be requesting some private URL (without a hostname) until timeout or success, which seems like a black door issue hijected by the vscode dev team.

I don't understand. Openning the "remote ssh" panel should only read some configuration. Why on earth does it have to read from some remote private URL.

Extension version: 0.112.0
VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 6.5.0-44-generic
Remote OS version: Linux x64 6.5.0-44-generic
Remote OS version: Linux x64 6.5.0-44-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.79GB (1.96GB free)|
|Process Argv|--crash-reporter-id c0b9e04f-1509-4546-8fe1-1451bf1bd2df|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: bigbox_lan|
|OS|Linux x64 6.5.0-44-generic|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor (32 x 400)|
|Memory (System)|125.01GB (116.80GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: bigbox_lan|
|OS|Linux x64 6.5.0-44-generic|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor (32 x 400)|
|Memory (System)|125.01GB (116.80GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: bigbox_lan|
|OS|Linux x64 6.5.0-44-generic|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor (32 x 400)|
|Memory (System)|125.01GB (116.80GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
ccplc:31103425
pythonrstrctxtcf:31103194
1iic9185:31097392

```

</details>

**Comment by bamurtaugh** [comment]
Thanks for opening. When you experience this next, could you share a screenshot of what you're seeing? I haven't observed this behavior and would love to take a closer look.

**Comment by walkerlala** [comment]
> Thanks for opening. When you experience this next, could you share a screenshot of what you're seeing? I haven't observed this behavior and would love to take a closer look.

OK I would send screenshot here next time I experience this.

**Comment by bamurtaugh** [comment]
Please let us know if you're still encountering this. Thank you!
