### ISSUE TITLE
SSH not connecting. Potential nodejs issue

### ISSUE THREAD

**Issue by dalurness** [microsoft/vscode-remote-release#1013]
![96F40886-1ACD-45AF-86A1-250A8D236FFF](https://user-images.githubusercontent.com/43400680/61773293-9741cf80-adb1-11e9-868c-704dfb148981.jpeg)

- VSCode Version: 1.36.1
- Local OS Version: Microsoft Windows [Version 10.0.17134.885]
- Remote OS Version: Ubuntu 18.04.2 LTS
- Remote Extension/Connection Type: Remote - SSH

Steps to Reproduce:

1. I am simply attempting to Log in to my server remotely through VSCode, but there is an error that I cannot seem to find anywhere.
2. I am able to connect just fine via terminal, but when it fails during VSCode connection.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

*** I know that my host does not allow nodejs on the server, and I think this may be causing the problem. If so, I need to know how to bypass that download onto the server during setup.

```
ERROR:

> Starting server...
> 
> Waiting for server log...
> 
> Waiting for server log...
> 
> Waiting for server log...
> 
> Waiting for server log...
> 
> Waiting for server log...
> 
> Waiting for server log...
> 
> Waiting for server log...
> 
> Waiting for server log...
> 
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
> Server did not start successfully. Full server log >>>
> 
> 
> #
> # Fatal error in , line 0
> # Check failed: SetPermissions(protect_start, protect_size, PageAllocator::kReadExecute).
> #
> #
> #
> #FailureMessage Object: 0x3e8c4f87cc0/home/jimsam1/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/server.sh: line 12: 26
> 277 Illegal instruction     (core dumped) "$ROOT/node" ${INSPECT:-} "$ROOT/out/vs/server/main.js" "$@"
> <<< End of server log
> 
"install" terminal command done
Received install output: <<< End of server log
Failed to parse remote port from server output: <<< End of server log
```

Thanks in advance!!!

**Comment by roblourens** [comment]
We include our own copy of node but it is failing to start and seems to be some permissions error. So your host does not allow node to run? Can you explain some more about that?

**Comment by dalurness** [comment]
@roblourens the picture I just edited on there is all I can find on it. When you click on the security link, it just takes you to the site of the company they use for security. It doesn’t actually give you any information about the setup. There’s no way to exclude the download of node when just making the ssh connection?

**Comment by roblourens** [comment]
Ok, sounds like vscode remote will not work on those boxes then.
