### ISSUE TITLE
Missing Git Extension

### ISSUE THREAD

**Issue by koderzi** [microsoft/vscode-remote-release#10144]
Type: <b>Bug</b>

Git extension is missing when starting dev container. All extension that need git extension to run failed to start.

Extension version: 0.380.0
VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.74GB (16.65GB free)|
|Process Argv|--crash-reporter-id 27f6d4dc-e162-4026-9d67-f8ef17833575|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: wp-dev @ desktop-linux|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900HX (32 x 0)|
|Memory (System)|15.49GB (13.72GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
ccplt:31103426
pythonrstrctxt:31103193
wkspc-onlycs-c:31111717

```

</details>

**Comment by geropl** [comment]
I think I'm seeing the same:
 - Local OS is Linux Mint 21.3 (Ubuntu, kernel: `5.15.0-117`)
 - Remote OS: Ubuntu, kernel `6.1.91`
 - only seeing this with VSCode `1.92.0`
   - downgrading to `1.91.1` fixes it! :heavy_check_mark: 
 - all extensions contributed by the client are reported as "not installed" (?), cmp. screenshot:
   -  ![image](https://github.com/user-attachments/assets/6f279471-13c3-4c02-9870-f39efd4151f9)
 - workaround:
   - click "Install" for every extension
   - "Reload Window"

**Comment by sandy081** [comment]
> Git extension is missing when starting dev container.

Can you please open extensions view and look for the Git Extension by typing `@builtin git` and let us know what you see?
