### ISSUE TITLE
Exectuable 'git' not found on PATH

### ISSUE THREAD

**Issue by nhphu** [microsoft/vscode-remote-release#10140]
"I got this error trying to push to my GitHub repository. The local repository is in the WSL2 filesystem. Git is installed in both WSL2 and Containers. dev.containers.executeInWSL is enabled. Sometimes the push succeeds, but other times it fails, I have to retry many time. The error is always printed.
I don't have git installed in my local OS (Windows) but I don't think it is needed.

- VSCode Version: 1.92
- Local OS Version: Windows 11 23H2
- Remote OS Version: WSL2 Ubuntu
- Remote Extension/Connection Type: Containers (mcr.microsoft.com/devcontainers/go:1-1.22-bookworm)

- Logs:

`[515520 ms] Container server: {
  message: "Exectuable 'git' not found on PATH 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\Cloudflare\\Cloudflare WARP\\;C:\\Program Files\\Git\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Users\\Phu\\AppData\\Local\\Microsoft\\WindowsApps'.",
  name: 'Error',
  stack: "Error: Exectuable 'git' not found on PATH 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\Cloudflare\\Cloudflare WARP\\;C:\\Program Files\\Git\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Users\\Phu\\AppData\\Local\\Microsoft\\WindowsApps'.\n" +
    '\tat So (c:\\Users\\Phu\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.380.0\\dist\\extension\\extension.js:81:741)\n' +
    '\tat async c:\\Users\\Phu\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.380.0\\dist\\extension\\extension.js:126:1625\n' +
    '\tat async se (c:\\Users\\Phu\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.380.0\\dist\\extension\\extension.js:125:494)\n' +
    '\tat async dY (c:\\Users\\Phu\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.380.0\\dist\\extension\\extension.js:66:1186)\n' +
    '\tat async mY (c:\\Users\\Phu\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.380.0\\dist\\extension\\extension.js:66:1059)\n' +
    '\tat async Object.rpc (c:\\Users\\Phu\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.380.0\\dist\\extension\\extension.js:97:781)'
}
[515579 ms] Container server: {
  message: "Exectuable 'git' not found on PATH 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\Cloudflare\\Cloudflare WARP\\;C:\\Program Files\\Git\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Users\\Phu\\AppData\\Local\\Microsoft\\WindowsApps'.",
  name: 'Error',
  stack: "Error: Exectuable 'git' not found on PATH 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\Cloudflare\\Cloudflare WARP\\;C:\\Program Files\\Git\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Users\\Phu\\AppData\\Local\\Microsoft\\WindowsApps'.\n" +
    '\tat So (c:\\Users\\Phu\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.380.0\\dist\\extension\\extension.js:81:741)\n' +
    '\tat async c:\\Users\\Phu\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.380.0\\dist\\extension\\extension.js:126:1625\n' +
    '\tat async se (c:\\Users\\Phu\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.380.0\\dist\\extension\\extension.js:125:494)\n' +
    '\tat async dY (c:\\Users\\Phu\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.380.0\\dist\\extension\\extension.js:66:1186)\n' +
    '\tat async mY (c:\\Users\\Phu\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.380.0\\dist\\extension\\extension.js:66:1059)\n' +
    '\tat async Object.rpc (c:\\Users\\Phu\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.380.0\\dist\\extension\\extension.js:97:781)'
}
`

Steps to Reproduce:

1.  Push to github repository while inside dev container (using the built-in VS Code source control)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by bamurtaugh** [comment]
cc @lszomoru as well

**Comment by chrmarti** [comment]
It looks like the `PATH` in your container has Windows paths. Could you share your configuration?

**Comment by nhphu** [comment]
devcontainer.json
```
{
	"dockerComposeFile": [
		"../../docker-compose.yml"
	],
	"service": "webhook",
	"workspaceFolder": "/workspace/webhook"
}
```
docker-compose.yml
```
services:
  webhook:
    container_name: webhook.tradingsend
    restart: unless-stopped
    build: ./webhook
    secrets:
      - nats_seed
    
secrets:
  nats_seed:
    environment: NATS_SEED
```
Dockerfile
```
FROM mcr.microsoft.com/devcontainers/go:1.22-bookworm AS dev
FROM dev AS build
WORKDIR /app
COPY go.mod go.sum *.go ./
RUN CGO_ENABLED=0 GOOS=linux go build
FROM alpine:3.20 AS prod
WORKDIR /app
COPY --from=build /app/webhook ./
EXPOSE 8801
ENTRYPOINT ["./webhook"]

```

**Comment by chrmarti** [comment]
Misread the log, we can just improve handling of `git` not being available locally. Thanks.
