### ISSUE TITLE
Allow per workspace configuration of remote.SSH.configFile parameter as well as all other settings

### ISSUE THREAD

**Issue by samzuercher** [microsoft/vscode-remote-release#10150]
As already requested in 2022 https://github.com/microsoft/vscode-remote-release/issues/7772 i like to see if we can get more upvotes this time.

In general: i think software-development moved from global settings to workspace-settings, so it should be possible to override every setting in the workspace not just the SSH.configFile.

I think this is also important from a security standpoint: only give access to the needed SSH-connection's on a workspace.

**Comment by samzuercher** [comment]
@dantefromhell:matrix.org @ExequielAD

**Comment by roblourens** [comment]
Not really possible because in a Remote-SSH scenario, the workspace is on the remote. And you need the ssh config file _before_ you connect to the remote 😄

**Comment by samzuercher** [comment]
@roblourens ehm.. no. you clearly did not understand anything. Did you read the description? This item was already a candidate for the backlog once https://github.com/microsoft/vscode-remote-release/issues/7772. But with your infinite wisdom you discovered it is not possible within 2 seconds? good luck then..
