### ISSUE TITLE
after deleting scripts the vscode remote-wsl not work

### ISSUE THREAD

**Issue by DigitalFountainBase** [microsoft/vscode-remote-release#10155]
I have deleted all the scripts in the path ".vscode\extensions\ms-vscode-remote.remote-wsl-0.88.2\scripts" then vscode cannot open the ubuntu.
where can i found the scripts?

**Comment by aeschli** [comment]
I would uninstall the extension and install it again. Maybe close VS Code after the uninstall and then manually delete `.vscode\extensions\ms-vscode-remote.remote-wsl-0.88.2` to be sure it is not going to be cached.

**Comment by aeschli** [comment]
Closing the issue.
