### ISSUE TITLE
[Remote-SSH Bug]: no /bin/bash

### ISSUE THREAD

**Issue by ohhmm** [microsoft/vscode-remote-release#10151]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

use sh instead of bash as the most compatible

### Steps To Reproduce

Make sure that target has no bash, just sh

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
/bin/bash not found
```

</p>
</details>

**Comment by roblourens** [comment]
We use a few bash-isms, I would like to simplify it, there's an issue for this somewhere
