### ISSUE TITLE
[Remote-SSH Bug]: Installation its incompatible with VSCODE Version

### ISSUE THREAD

**Issue by uNbAs** [microsoft/vscode-remote-release#10164]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (different error message)

### ->

Problem in install vsix extension.

Procedure, go to the marketplace, download extension and install manually from vscode

### Expected Behavior

Install its not possible with last version of vscode

### Steps To Reproduce

Envirronment: Windows 11
VSCODE Version: 1.92.1
Remote-SSH: Last Version published = ms-vscode-remote.remote-ssh-0.114.2024081215

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
workbench.desktop.main.js:820 Error: Error: Unable to install extension 'ms-vscode-remote.remote-ssh' as it is not compatible with VS Code '1.92.1'.
    at Object.run (workbench.desktop.main.js:2724:57560)
    at async Object.run (workbench.desktop.main.js:2724:57075)
    at async L.u (workbench.desktop.main.js:264:20729)
    at async L.run (workbench.desktop.main.js:264:20653)
c @ workbench.desktop.main.js:820
(anonymous) @ workbench.desktop.main.js:820
B @ workbench.desktop.main.js:93
C @ workbench.desktop.main.js:93
fire @ workbench.desktop.main.js:93
addNotification @ workbench.desktop.main.js:820
error @ workbench.desktop.main.js:1941
(anonymous) @ workbench.desktop.main.js:1959
B @ workbench.desktop.main.js:93
C @ workbench.desktop.main.js:93
fire @ workbench.desktop.main.js:93
run @ workbench.desktop.main.js:264
await in run (async)
onClick @ workbench.desktop.main.js:264
(anonymous) @ workbench.desktop.main.js:264
setTimeout (async)
M.setTimeout @ workbench.desktop.main.js:1918
(anonymous) @ workbench.desktop.main.js:264
workbench.desktop.main.js:660   ERR Unable to install extension 'ms-vscode-remote.remote-ssh' as it is not compatible with VS Code '1.92.1'.: Error: Unable to install extension 'ms-vscode-remote.remote-ssh' as it is not compatible with VS Code '1.92.1'.
    at z.install (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:105:113767)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5
```

</p>
</details>

**Comment by joshspicer** [comment]
Could you please provide the full logs so that we can better understand the issue you're seeing? More info here: https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting#troubleshooting-steps

**Comment by roblourens** [comment]
It looks like the marketplace is only showing you pre-release versions of the extension, which require VS Code Insiders right now. If you can't download through vscode you can hack the download URL to get the right version, eg https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-ssh/0.113.1/vspackage is the latest stable

**Comment by uNbAs** [comment]
Thank you very much.

It seems then that the problem was in the interface that connects the chair and the keyboard, I was not able to find the published stable version, so I could install it manually :(

Thank you very much!
