### ISSUE TITLE
[Remote-SSH Bug]: Failure to remote connect to Debian 12

### ISSUE THREAD

**Issue by leonbrag** [microsoft/vscode-remote-release#10160]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

Cannot connect to Debian 12 over SSH

### Steps To Reproduce

1. install latest VS code
2. install latest remote SSH tools
3. Connect to Debian 12
4. Supply password, observe log below and cannot connect

I have tried to use Remote SSD command to remove server, after that it worked once. But then it stopped working again.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
leonbrag@hpdebian's password:
4560f56ed71e: running
Found existing installation at /home/leonbrag/.vscode-server...
Starting VS Code CLI... "/home/leonbrag/.vscode-server/code-eaa41d57266683296de7d118f574d0c2652e1fc4" command-shell --cli-data-dir "/home/leonbrag/.vscode-server/cli" --on-port --on-host=127.0.0.1 --parent-process-id 5622 &> "/home/leonbrag/.vscode-server/.cli.eaa41d57266683296de7d118f574d0c2652e1fc4.log" < /dev/null
printenv:
    SHELL=/bin/bash
    PWD=/home/leonbrag
    LOGNAME=leonbrag
    XDG_SESSION_TYPE=tty
    MOTD_SHOWN=pam
    HOME=/home/leonbrag
    LANG=en_US.UTF-8
    VSCODE_AGENT_FOLDER=/home/leonbrag/.vscode-server
    SSH_CONNECTION=192.168.4.204 56038 192.168.4.33 22
    XDG_SESSION_CLASS=user
    USER=leonbrag
    SHLVL=1
    XDG_SESSION_ID=15
    XDG_RUNTIME_DIR=/run/user/1000
    SSH_CLIENT=192.168.4.204 56038 22
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
    DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
    _=/usr/bin/printenv
Removing old logfile at /home/leonbrag/.vscode-server/.cli.eaa41d57266683296de7d118f574d0c2652e1fc4.log
Spawned remote CLI: 5641
Waiting for server log...
4560f56ed71e: start
SSH_AUTH_SOCK====
DISPLAY====
listeningOn==127.0.0.1:33547==
osReleaseId==debian==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
serverStartTime==67==
execServerToken==7b2885e8-d73f-4673-bc0d-10d7e7a582d3==
4560f56ed71e: end
```

</p>
</details>

**Comment by signag** [comment]
Since a few weeks. I have a similar issue with remote development on Raspberry Pi systems.     
When trying to open a remote session, VSCode shows a message that the server is being set up.     
The session is not opened, even after waiting a long time.

Sometimes, a session is opened after many tries.

Trying the prerelease version and playing with ```remote.SSH.useLocalServer``` did not work.

I went back to a version from some time ago (v0.111.2024040515).
This worked.

**Comment by joshspicer** [comment]
Glad to here you were able to work around the issue.

We unfortunately don't have too much info to work off of here.  What was the error you were trying to share with me in the log?  That snippet of log looks OK to me.


If you're still able to reproduce, please include your entire SSH log next time so I can understand the issue you're facing better. Thanks!
