### ISSUE TITLE
[Remote-SSH Bug]: Dev Container installation can't complete

### ISSUE THREAD

**Issue by avishco** [microsoft/vscode-remote-release#10175]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Expect devcontainer to finish installation properly

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by bamurtaugh** [comment]
Thanks for opening. Could you please share some repro steps so that we can take a closer look?

**Comment by avishco** [comment]
Looks like the problem was caused due to low connectivity, although it was hard to diagnose on realtime due to insufficient logging. Now back on stable internet connection the extension works flawlessly.

**Comment by joshspicer** [comment]
Was the dev container already created when you tried to connect?  In almost all cases you'll need a stable internet connection to create your container.  I suspect that was the case here.  If you're able to reproduce the issue, please feel free to re-open and i'm happy to take a closer look.
