### ISSUE TITLE
Dev Container gives git "dubious ownership" error message

### ISSUE THREAD

**Issue by richb-hanover** [microsoft/vscode-remote-release#10179]
- VSCode Version: 1.92.2
- Local OS Version: Darwin x64 21.6.0
- Remote OS Version:
- Remote Extension/Connection Type: Containers/WSL/Server

- Logs:

Steps to Reproduce:

I have a Dev Container whose [Dockerfile has this form](https://github.com/PRQL/prql/blob/main/.devcontainer/base-image/Dockerfile):

```
...
USER vscode

... install a bunch of cargo/rust stuff ...

USER root
...
```

Using current versions of Docker Desktop on both macOS and Windows, I see this error:

```
ERROR Failed to read Git log: fatal: detected dubious ownership in repository at '/workspaces/prql'
To add an exception for this directory, call:

        git config --global --add safe.directory /workspaces/prql
```

I first noticed this a while ago - maybe two-three months, but I'm not sure. 

**My questions:**

1. Is this behavior expected? (That is, will a Dev Container with two USERs always trigger this error message?)

2. Is the proper fix running the `git config ... --add safe.directory...` command?

3. Is there any reason this command couldn't be placed in the `postCreateCommand` section of _devcontainer.json_?

NB: 

* I did see #8656, but that referred only to Windows. This report concerns both macOS and Windows...
* I googled around and found several third-party sites (such as [Avoiding Dubious Ownership in Dev Containers](https://www.kenmuse.com/blog/avoiding-dubious-ownership-in-dev-containers/)) that made this sound like a reasonable fix. Is there an official Microsoft/Docker page that gives this advice that I could link to? 

Many thanks.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/8656.
