### ISSUE TITLE
Unable to connect to one patricular remote host

### ISSUE THREAD

**Issue by prsharonmathew** [microsoft/vscode-remote-release#10176]
Type: <b>Bug</b>

Hi, I have connected to the remote host fritz earlier using vs code connect to remote host feature. But now Im unable to connect to fritz. Even after typing in the correct password its just showing running. However i was able to connect to other hosts.

Extension version: 0.113.1
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Connection to 'ssh-remote+fritz' could not be established
Connection to 'ssh-remote+fritz' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.65GB (1.85GB free)|
|Process Argv|--crash-reporter-id 1de2ab4d-af66-4f5d-bd6f-dc0477b4d569|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+fritz' could not be established

Connection to 'ssh-remote+fritz' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
nativeloc1:31118318
wkspc-ranged-t:31118572

```

</details>

**Comment by joshspicer** [comment]
From the information you've shared the most likely explanation is that there is an issue with the fritz host. Did you try directly SSH'ing to it outside of VS Code.

Please take a look at our [troubleshooting guide](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting). 

If you're still able to reproduce, please feel free to reopen with your logs attached so I can take a deeper look
