### ISSUE TITLE
devcontainer: confusing SCM view when git is not installed

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode-remote-release#10188]
Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

Steps to Reproduce:

1. Start a dev container without git.
2. VS Code is going to propose how to install Git in SCM view, but for your local machine, not remote container.

![Screenshot 2024-08-26 at 11 38 13](https://github.com/user-attachments/assets/92ba2d29-d702-4987-b766-123f8085ae04)

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by bamurtaugh** [comment]
cc @lszomoru since I wonder if this would live more in the SCM view logic rather than the Dev Containers extension (and SCM view would look different if it detects it's in a remote environment)

**Comment by lszomoru** [comment]
@digitarald, I suspect that we should not be showing the "install" welcome view when connected to a remote.

**Comment by rzhao271** [comment]
Hit this just now while sanity testing.

Remote: Alpine
Local: Windows

**Comment by lszomoru** [comment]
Pushing a fix to show a generic git installation welcome view when connected to a remote.
