### ISSUE TITLE
keyboxd support not working for me

### ISSUE THREAD

**Issue by red8888** [microsoft/vscode-remote-release#10184]
This was supposed to be fixed: https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_92.md

The docs were never updated btw: https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials#_using-gpg-241

```
Version: 1.92.0 (Universal)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z (3 wks ago)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.4.0
```

When I try to commit inside a dev container I get the same error:
```
error: gpg failed to sign the data:
gpg: skipped "me, me <me@me.com>": No secret key
[GNUPG:] INV_SGNR 9 me, me <me@me.com>
[GNUPG:] FAILURE sign 17
gpg: signing failed: No secret key

fatal: failed to write commit object
```

This is my gpg version inside the container:
```
gpg --version
gpg (GnuPG) 2.2.27
libgcrypt 1.8.8
Copyright (C) 2021 Free Software Foundation, Inc.
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /root/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

I built my image off of: `mcr.microsoft.com/devcontainers/python:3.12-bullseye`

Is there something else I have to do?

**Comment by chrmarti** [comment]
If you created the devcontainer before the last update, you probably have to rebuild it to make it work.

If rebuilding doesn't help, please append the Dev Containers log from when you rebuild the container. (`F1` > `Dev Containers: Show Container Log`)
