### ISSUE TITLE
Getin-cnpj

### ISSUE THREAD

**Issue by marciotech-dev** [microsoft/vscode-remote-release#10195]
- VSCode Version:
- Local OS Version:
- Remote OS Version:
- Remote Extension/Connection Type: Containers/WSL/Server

- Logs:

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by bamurtaugh** [comment]
Seems like this might've been opened by accident. If you do have more details for an issue, please just let us know. Thanks!
