### ISSUE TITLE
Should all quick picks say "templates" instead of "definitions"?

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#10193]
Testing #226686

Now that we refer to these configurations as "templates" instead of "definitions," should we replace any mention of "definition" in the quick picks?

![Image](https://github.com/user-attachments/assets/573c5907-9556-42a9-8560-1e7175898c48)

**Comment by rzhao271** [comment]
Looks like the fix isn't in yet.

**Comment by chrmarti** [comment]
@rzhao271 Thanks for the reminder! Kicking off a build for 0.383.0-pre-release, should be available within an hour.
