### ISSUE TITLE
Should `Add configuration to workspace` be first option?

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#10194]
Testing #226686

Is there a reason (i.e. specific user feature request / feedback) we made user data folder the first / default option when adding dev container config files?

![Image](https://github.com/user-attachments/assets/b7be4520-c79b-48b7-a84d-d0f890196f87)

At least in my muscle memory, I always want to add the config to the workspace, and I feel like that's also the core flow we document and discuss with users.

**Comment by chrmarti** [comment]
We can swap it early next milestone, so we have some time to test the muscle memory effect (ourselves and by the pre-release users).
