### ISSUE TITLE
Detect the error case where `scp` cannot copy to remote because remote doesn't have `scp` installed

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode-remote-release#10200]
As [discussed here](https://stackoverflow.com/a/20242139), to use `scp` it needs to be installed on both sides.  Today the ssh extension will not be able to identity this fatal case, likely producing a cryptic error like:

```
[17:11:53.801] > bash: line 1: scp: command not found
> lost connection
```

More context:  https://github.com/microsoft/vscode/issues/226759#issuecomment-2319270904

**Comment by chrmarti** [comment]
Not sure if this could be applied here, but Dev Containers uses an existing shell to send the server over. It only requires `dd` and `tar` on the remote side.
https://github.com/microsoft/vscode-remote-containers/blob/7457cd00ff79e5bcf1ef50c8028fd44edab60a2e/src/common/injectHeadless.ts#L1065

**Comment by joshspicer** [comment]
Interesting, i'm not able to repro with a test Ubuntu 24 remote that has scp removed.  This behavior must only exist in some cases of SSH

**Comment by joshspicer** [comment]
I can't repro this anymore (both with the aforementioned dev container repro or a real VM).  Perhaps I was actually hitting a bug/inconsistency in fedora at the time? Not sure - please do comment if you can reproduce today.
