### ISSUE TITLE
Dev Containers CLI: RPC pipe not configured. on git commands from other tools

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode-remote-release#10222]
Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

Steps to Reproduce:

1. Create a devcontainer with SSH support, connect it via Dev Containers.
2. After that connect to it using another editor, i.e. zed or IntelliJ.
3. Run some git command like `git fetch`.

It would be nice that Dev Containers modify the config in such way that it does not get noisy while using other tools.

**Comment by chrmarti** [comment]
@akosyakov Can you confirm that this is fixed? (We are currently verifying the fixes of the milestone.)

**Comment by akosyakov** [comment]
yes, it works for me
