### ISSUE TITLE
Feature Request: vscode.dev to work with Chromium's Secure Shell extension

### ISSUE THREAD

**Issue by jarrodcolburn** [microsoft/vscode-remote-release#10227]
Problem:
vscode.dev does not work with code extension [Remote - SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh). 

Reason:
vsocde.dev runs in the browser which has many limitations preventing ssh.

Purpose solution:
Make vscode.dev's Remote - SSG extension ssh calls compatible with Chromium's [Secure Shell extension](https://chromewebstore.google.com/detail/secure-shell/iodihamcpbpeioajjeobimgagajmlibd) or fork Chromium extension and add functionality.

Pros:
Chromium's Secure Shell extension is able to ssh and port forward. 

Cons:
It would require user to install a browser extension.

Notes: 
* Chromium's Secure Shell extension already understands [`ssh`](https://chromium.googlesource.com/apps/libapps/+/master/nassh/doc/uri.md) urls, such as 
`ssh://user[;option=value]@host[:port][@proxyhost[:proxyport]]` 
which may make adding functionality in Code's Remote - SSH extension easier.
* Does Chromium's Secure Shell extension use a proxy, or deprecated NaCl?

**Comment by bamurtaugh** [comment]
Thanks for opening! As there are limitations preventing SSH connections as you mention, we recommend using the Remote-Tunnels extension: https://code.visualstudio.com/docs/remote/tunnels.

Please let us know if you have any questions about or requests for Remote-Tunnels!
