### ISSUE TITLE
SSH: `curl` is not detected

### ISSUE THREAD

**Issue by harryhmtse** [microsoft/vscode-remote-release#10238]
- VSCode Version:  Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
- Local OS Version: macOS 14.6.1
- Remote OS Version: openSUSE Tumbleweed 20240904
- Remote Extension/Connection Type: Server

- Logs: 

Steps to Reproduce:

1. Update to VSCode 1.93.0
2. Connect to Remote System over SSH

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

When VSCode 1.93.0 attempt sto connect to a Remote SSH System,  the connection fails with Error: Downloading VS Code Server failed - please install either curl or wget on the remote.

The installation script appears to be misdetecting the presence of curl verified.  

Verified that curl is present via 
```
command -v curl
/usr/bin/curl
```

If the logic of the script is run interactively, and the code CLI binary is moved into it's expected location, VSCode successfully connects to the remote system. 

 ```
curl --location https://update.code.visualstudio.com/commit:4849ca9bdf9666755eb463db297b69e5385090e3/cli-alpine-x64/stable --output /tmp/vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz
tar -xf /tmp/vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz
chown 1000:1000 code-4849ca9bdf9666755eb463db297b69e5385090e3
chmod g+w code-4849ca9bdf9666755eb463db297b69e5385090e3
cp /tmp/code ~/.vscode-server/code-4849ca9bdf9666755eb463db297b69e5385090e3
```

**Comment by harryhmtse** [comment]
[remote.log](https://github.com/user-attachments/files/16918721/remote.log)

Issue appears to be in line 378 of the log, where
```
if [ $error_code -ne 0 ]
```

**Comment by joshspicer** [comment]
Thank you for taking the time to provide feedback.

I've generated a new pre-release build of the extension (`v0.115.2024090921 (pre-release)`) with a fix. If you're able to test, please let me know if it helps.

**Comment by joshspicer** [comment]
Version `v0.114.2` has been released with the fix.  Please share any related logs if the issue persists
