### ISSUE TITLE
Dev container volume mountpoint inconsistency

### ISSUE THREAD

**Issue by icyvapor** [microsoft/vscode-remote-release#10232]
Hello, 

Got a very confusing problem: I was trying to access workspace files in a dev container. Found that the volume mountpoint reported by Docker is not correct. See the attached screenshots.

I created the dev container by building from a base image, and I didn't explicitly set any mount point.
I'm on Win11, docker Desktop is integrated with WSL2.

What I *actually* want to do is, to replicate my dev container from desktop to my laptop. I did docker-save to create tar file, then docker-load on my laptop, the dev container seems to be spinning up fine. But my source files under 'workspaces' are in a volume. 

Any help is greatly appreciated!

![dev_container_volume_loc1](https://github.com/user-attachments/assets/9aab54c5-a9e2-4489-a8b7-ab602dcbe401)
![dev_container_volume_loc2](https://github.com/user-attachments/assets/676c572a-a00f-4ed3-8d34-a6f283daf43b)

**Comment by chrmarti** [comment]
`docker save` and `docker load` seem to work on images. How did you go from the container to the image and then back?

**Comment by icyvapor** [comment]
You are right, my confusion. I copied the image over to the new machine, and load it into Docker Desktop, then run it manually. 

My more general question is what's the recommended way to replicate a dev container on another machine?

**Comment by chrmarti** [comment]
I would check in the `devcontainer.json` (and `Dockerfile` if using one) to share the container setup.

@joyceerhl Can `Continue On` be used to move pending changes between dev containers on different machines?

**Comment by icyvapor** [comment]
Right, copying over the `devcontainer.json` and rebuild the container worked for me.
Thanks for your help!
