### ISSUE TITLE
DevContainers: Unable to open any options, error "ERR stream is closed"

### ISSUE THREAD

**Issue by jorlan259** [microsoft/vscode-remote-release#10236]
![devcontainer](https://github.com/user-attachments/assets/f74fd690-87a1-46ce-916a-e5b80949b188)

I'm encountering an issue where I'm unable to open any options within DevContainers in VS Code. Regardless of the option I select, it fails to load and I receive the following error in the VS Code console:

ERR stream is closed: Error: stream is closed
at h (c:\VScode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:161:210901)

**Comment by chrmarti** [comment]
What are your VS Code and Dev Containers extension versions? Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)
