### ISSUE TITLE
Using the SSH plugin with a locally built vscode

### ISSUE THREAD

**Issue by nojaf** [microsoft/vscode-remote-release#10235]
Hello,

I'm investigating microsoft/vscode#210792 by installing the VSIX from https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh in my locally built version of VSCode. My goal is to establish a remote connection and debug the `PtyService` to identify the issue.

Steps to reproduce:

1. Clone and build https://github.com/microsoft/vscode/
2. Start the debug task and launch the locally built VSCode
3. Download the VSIX from https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh
4. Install it via the command in the local VSCode frontend
5. Connect via the SSH command

I keep encountering the error: `Connection error: Unauthorized client refused` when attempting this locally. This issue does not occur with the vanilla product or the insiders' version—only with the locally built VSCode. I've checked the remote server, and there are no SSH problems, and the vscode-server process starts as expected. Despite this, I consistently hit the "Unauthorized client refused" error in Developer tools.

I'm looking for someone familiar with VSCode internals and the remote extension to help troubleshoot this. Should this approach work, or are there limitations I'm unaware of?

Tagging some people who might offer insights: @roblourens, @joshspicer, @kieferrm.

Thanks in advance!

**Comment by bamurtaugh** [comment]
Hi there, thanks for your issue. Remote-SSH is only expected to work in the official builds of VS Code Stable and Insiders as you've identified. There's more information on their connection restrictions here: https://code.visualstudio.com/docs/remote/faq#_license-and-privacy.
