### ISSUE TITLE
Remote-SSH cannot uncompress the compressed server deployment, which was transfered by VSCode client

### ISSUE THREAD

**Issue by zhang-stephen** [microsoft/vscode-remote-release#10252]
- VSCode Version: 1.93.0
- Local OS Version: Windows 11 Enterprize 22H2
- Remote OS Version: CentOS 7.9
- Remote Extension/Connection Type: Remote-SSH/Linux Server

- Logs:
```
48f4982d6f37: running
Script executing under PID: 28232
Installing to '/host/workdir'/.vscode-server...
48f4982d6f37%%1%%
Downloading with wget
wget is from busybox: no
Program 'wget' appears to support flag '--no-config'
Download complete
48f4982d6f37%%2%%
tar --version: tar (GNU tar) 1.35
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
mv: cannot move 'code' to "'/host/workdir'/.vscode-server/code-4849ca9bdf9666755eb463db297b69e5385090e3": No such file or directory
ERROR: '/host/workdir'/.vscode-server/code-4849ca9bdf9666755eb463db297b69e5385090e3 don't exist
Trigger local server download
48f4982d6f37:trigger_server_download
artifact==cli-alpine-x64==
destFolder=='/host/workdir'/.vscode-server==
destFolder2==/vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz==
48f4982d6f37:trigger_server_download_end
Waiting for client to transfer server archive...
Waiting for '/host/workdir'/.vscode-server/vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz.done and vscode-server.tar.gz to exist
 main: line 337: /host/workdir/.vscode-server/code-4849ca9bdf9666755eb463db297b69e5385090e3: No such file or directory
```

Steps to Reproduce:

1. update vscode to 1.93.0, then reconnect to the remote server
2. due to the network limitation, the vscode server update would fallback to be downloaded by vscode client(windows) and be transferred to the remote.
3. then you will see the error log shows above.
4. I have checked the installation of vscode on remote server, the compressed file cannot be uncompressed, but I could uncompress it manually.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by zhang-stephen** [comment]
Workaround: the Remote-SSH pre-release works well.

**Comment by joshspicer** [comment]
Thanks for opening. @zhang-stephen is correct that the pre-release should have this patched. 

Closing in favor of https://github.com/microsoft/vscode-remote-release/issues/10230
