### ISSUE TITLE
Request to Reopen Issue #8673: Support for Shared Home Directories Across Different Architectures

### ISSUE THREAD

**Issue by bcaddy** [microsoft/vscode-remote-release#10269]
I'm having the same problem that was highlighted in Issue #8673, namely that I'm working on a system that has nodes with different architectures that share a home directory and I cannot connect to both architectures at once with vscode-remote; more details are in Issues #8673. My suspicion is that this will become more common as computing becomes more heterogeneous. What is the proper way to reopen an issue for consideration?

**Comment by joshspicer** [comment]
Re-opened, I also left a workaround suggestion. Thanks!
