### ISSUE TITLE
remote ssh server needs .wgetrc for proxy configuration.

### ISSUE THREAD

**Issue by dxunix** [microsoft/vscode-remote-release#10263]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.93.0
- OS Version: windows 10

Steps to Reproduce:

1. Remote SSH to AWS EC2 (linux 2023)
2. we have proxy for access internet from the ec2
3. the proxy is stored in .wgetrc
4. the installation hangs during the downloading vscode. the message shows “wget appears to support “—no-config”, thus the config .wgetrc on remote is not used, hence downloading hangs.

Please remove this option or make it is an option on local so i dont run into this issue.

**Comment by joshspicer** [comment]
Thanks for the details. There is a VS Code setting that when enabled will respect the remote's `.wgetrc` (or `.curlrc`) configurations. 

![Image](https://github.com/user-attachments/assets/67183549-6e3d-449f-8d23-a3e8f80e83a9)

Please let me know if this helps!

**Comment by rjra100** [comment]
Is it just me that thinks that ignoring the curl/wget config files is a very strange default? By all means provide an *option* to ignore them (presumably there was a use-case for that), but if I put a .wgetrc file in my home directory, it's because I expected wget to use it!

**Comment by joshspicer** [comment]
Thanks for the feedback. There's been a decent amount of bug reports in the past that were "fixed" by ignoring these configuration files.  Perhaps a solution where re-attempt with config (or vice versa) after a failure could be a good middle ground? Happy to rework this if folks have other ideas - please let me know.
