### ISSUE TITLE
VSCode server fails in Alpine:3.10 with Docker version 18.09.8

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#1026]
Ubuntu 18.04.2 LTS
Docker version 18.09.8

Running the remote server in alpine:3.10 (latest) crashed with a segfault.

Not sure if this is the problem, but the node that we ship with is built against alpine:3.9

**Comment by chrmarti** [comment]
Works for me with the latest Docker (2.1.0.1). Could you retry with that?

**Comment by chrmarti** [comment]
@aeschli Could you check if there is a newer version of image: `docker pull alpine:3.10`?

**Comment by chrmarti** [comment]
Checked with Ubuntu 18.04 and 18.10 with the latest docker-ce, but could not reproduce.

**Comment by chrmarti** [comment]
Most likely an upstream issue, filed https://gitlab.alpinelinux.org/alpine/aports/issues/10767.

**Comment by chrmarti** [comment]
The workaround is to automatically remove spdlog from the node_modules folder. There are some follow-up errors to that module missing and there is no log file for the remote extension host.

**Comment by alexr00** [comment]
Verified that I can now connect to an Alpine 3.10 container. I see the missing spdlog errors, but connection is successful.

**Comment by chrmarti** [comment]
@Chuxel FYI, with Alpine 3.10 there will be a warning in the Dev Container terminal about this issue. Not sure if this needs to be mentioned in the documentation.

**Comment by Chuxel** [comment]
@chrmarti Added to known issues that refers here since you get a "cannot find module" error that, while isolated to our own logging, looks scary. 

I'd been thinking about possibly adding an Alpine dev container into the vscode-dev-containers repo since things like setting up a non-root user are slightly different on Alpine, but we should hold off on that until we at least make the error a bit less alarming (if not get a real fix).

**Comment by chrmarti** [comment]
Following-up with the musl mailing-list: https://www.openwall.com/lists/musl/2019/09/06/1

**Comment by chrmarti** [comment]
The update to Node.js 12.4.0 fixes this. The latest VS Code Insiders comes with that in its server build for Alpine. I have removed the workaround in the extension. /fyi @Chuxel
