### ISSUE TITLE
wsl changelog not kept up to date

### ISSUE THREAD

**Issue by melutovich** [microsoft/vscode-remote-release#10260]
The WSL changelog is not kept up to date

https://marketplace.visualstudio.com/items/ms-vscode-remote.remote-wsl/changelog

Last mentions 0.78.0 and before that 0.39.6

And the current version is 0.88.3 with no indication what changed

**Comment by bamurtaugh** [comment]
Thanks for opening an issue! We'd recommend using the link [See here for the latest release notes.](https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes) in the Changelog, as it points to all of the latest changes from each month.

If we hear additional confusion over this, we can revisit the approach here (i.e. maybe removing the 2 entries in that first changelog link you shared so that folks know just to click on the second link).

**Comment by melutovich** [comment]
@bamurtaugh

In the link you gave the latest mentioning of WSL is in https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_89.md.  However I don't understand how that version number is related to WSL version that indicates it is v0.88.3 

So that link release note version number file v1_89 (latest file v1_93) seems very confusing, I would have expected each ...v1_89...v1_93 to list all the products and what their current version number is and indicate if within each there was a change.

So I don't think the "[See here for the latest release notes](https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes)" is good enough.  You except someone to search through each file and then try to guess which WSL version maps to the file name?

**Comment by aeschli** [comment]
Yes, sorry, we don't want to maintained the `changelog` file in addition to the remote release notes.

I change it to only keep the link

**Comment by melutovich** [comment]
@aeschli
I believe you should also remove the two entries of 0.78.0 and 0.39.6

@bamurtaugh
Should I open a separate issue on the remote-release-notes such as:
So that link release note version number file v1_89 (latest file v1_93) seems very confusing, I would have expected each ...v1_89...v1_93 to list all the extensions and what their current version number is and indicate within each if there was a change.
(For example the WSL extension currently says it is version v0.88.4)
