### ISSUE TITLE
Adopt remoteName

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#1029]
the context key remoteAuthority is used to enable and disable commands for the remote indicator.

- `remoteAuthority` is now deprecated and replaced with `remoteName` (matching vscode.d.ts)
- new context key `remoteConnectionState` with values 'initializing' | 'disconnected' | 'connected'

- remoteName is empty in a local window 
- in remote window it is set to the remoteName e.g. `wsl`, `ssh`  (part before the `+`)
- the remote indicator menu now also shows actions when disconnected.
Use the `remoteConnectionState` key to control when a command should show.

**Comment by aeschli** [comment]
See as example: https://github.com/microsoft/vscode-remote-containers/commit/58611cd0291ae8e28ac5b2edcfbb403804254522

**Comment by roblourens** [comment]
It seems when the resolver fails and the status bar says "Disconnected from ..." then  `remoteConnectionState` is "initializing", is that right?

**Comment by aeschli** [comment]
It should be 'disconnected'
