### ISSUE TITLE
Pipe MOTD to activated terminal

### ISSUE THREAD

**Issue by dghw** [microsoft/vscode-remote-release#10295]
Linux server administrators can use the /etc/motd to show messages to users upon SSH login. VS Code by default doesn't show the login terminal, but even if it is shown the MOTD is not printed correctly, I'm not sure why. 

Example of login window using ssh over Windows terminal:

```
Logged on to server. Please don't break anything.

Last login: DATE from ADDRESS
USER@SERVER:~$
```

I think it would be useful it the /etc/motd message was shown correctly in the login shell, and if the login shell is not shown (as is the default setting), piped to the non-login shell that is automatically opened by VS Code.

**Comment by oopstls** [comment]
I have the same request to display the server information for my classmates
