### ISSUE TITLE
[Remote-SSH Bug]: .gitconfig not copied to remote machine

### ISSUE THREAD

**Issue by stefanrybacki** [microsoft/vscode-remote-release#10290]
VSCode Version: 1.93.1
Local OS: Windows 11
Remote OS: Ubuntu 24.04

.gitconfig exists in local user folder on Windows side, but will not be copied to remote machine, leading to errors regarding not set `user.name` and `user.email` configuration when trying to commit something.

**Comment by joshspicer** [comment]
Are you using the Remote SSH extension or dev containers extension? The Remote-SSH extension doesn't copy anything (like gitconfig) over from the local machine to the remote machine. 

The Dev Containers extension performs limited syncing steps between the host and container.  If this is what you're asking about, please provide your logs and ideally a minimal dev container configuration that we can use to repro on our side.  Thanks!

**Comment by stefanrybacki** [comment]
I am using plain remote SSH. So it seems I am under the wrong impression that .gitconfig was supposed to be copied over. I think I read it somewhere though. May it as it be, if it is not supposed to copy I guess this issue can be closed. Thanks for looking into this.

**Comment by joshspicer** [comment]
Yes, we have [this feature for containers](https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials#:~:text=Sharing%20Git%20credentials%20with%20your%20container).  You may also be interested in the `ForwardAgent` feature of SSH (that this extension supports).
