### ISSUE TITLE
How can I have a shared shell profile without having to mount in any files?

### ISSUE THREAD

**Issue by red8888** [microsoft/vscode-remote-release#10297]
I want to have a shell profile applied with my global user config but I don't want to have to edit all my devcontainer configs to mount in a shell profile from my host nor do I want to add a shell profile script to all of my project directories.

Is there a way to define a shell profile inside vscode and have it get used for all terminals regardless of if they are dev containers or not? 

For example I can do this (this actually doesn't work because of some zsh bug or something) to set shell config for all terminals without having to edit any dev container configs:

```
    "terminal.integrated.defaultProfile.linux": "zsh",
    "terminal.integrated.profiles.linux": {
        "zsh": {
            // causes zsh bug: invalid module name `zsh/zle'
            "args": ["-o", "vi"]
        }
    },
```

Is there a way to store my shell profile script _inside_ of my vscode settings? I have lots of projects and I don't want to have to configure bind mounts for every single devcontainer.json.

**Comment by chrmarti** [comment]
You could configure a dotfiles repository in the user settings that has the script.
![Image](https://github.com/user-attachments/assets/2e9037b5-9886-4f12-8a82-3e12c9f3cec2)
