### ISSUE TITLE
 devcontainer clone repo,  how to set clone branch

### ISSUE THREAD

**Issue by xiangpingjiang** [microsoft/vscode-remote-release#10298]
devcontainer clone repo,  how to set clone branch

**Comment by bamurtaugh** [comment]
They there, have you checked out our docs and getting started tutorial for Dev Containers?

- https://code.visualstudio.com/docs/devcontainers/tutorial
- https://code.visualstudio.com/docs/devcontainers/containers

If so, were you still having issues? Sharing more about the steps you've tried and what has/hasn't worked would be very helpful!

**Comment by xiangpingjiang** [comment]
@bamurtaugh 
<img width="480" alt="image" src="https://github.com/user-attachments/assets/207ea4e8-49b3-4c4b-a810-63fca5eb4e84">

I tried clone In volume, it would clone my repo defaut the master branch. But my  master branch did'nt have a .devcontainer file. I'd like to know how to set the branch

**Comment by chrmarti** [comment]
`F1` > `Dev Containers: Clone Repository in Container Volume...` has branch picker for GitHub repositories. (Only when you go through the GitHub repository picker.)

**Comment by chrmarti** [comment]
More general request tracked as: https://github.com/microsoft/vscode-remote-release/issues/4296

**Comment by xiangpingjiang** [comment]
@chrmarti 
When my  repo is not in github, is there a  branch picker?

**Comment by chrmarti** [comment]
No, not at the moment. https://github.com/microsoft/vscode-remote-release/issues/4296 is tracking that request.
