### ISSUE TITLE
remote-ssh: How to install the builtin extension Git on remote ssh server?

### ISSUE THREAD

**Issue by playsand** [microsoft/vscode-remote-release#10306]
![image](https://github.com/user-attachments/assets/8acfec74-277a-4065-9823-8c7ef28b3e89)
```
Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

**Comment by bamurtaugh** [comment]
Thanks for sharing this. Are you connected to your remote machine when you see this?

As a built-in extension, the Git extension should "just work" on your remote, no special install or setup required. Here's an example of how it looks when I'm connected to a remote:

![Image](https://github.com/user-attachments/assets/8ec9b7ad-d3c9-41c2-aedd-ed7bd61096ce)

**Comment by playsand** [comment]
Thank your reply. I'm sure I'm connected to the remote machine. Here is my screenshot.
![image](https://github.com/user-attachments/assets/35b6edd2-dc86-4b3e-b7dd-5f0b193a76d1)
![image](https://github.com/user-attachments/assets/4b5e1636-7747-432c-a7c8-5731dfacb124)

**Comment by playsand** [comment]
Thanks again for your reply. I just solved the problem by deleting the .vscode-server folder on the remote machine and reconnecting to it.  This issue might have been caused by the fact that I recently switched computers, with the CPU changing from Intel to an M3 processor.
