### ISSUE TITLE
Remote Tunnel Keeps Reporting Errors

### ISSUE THREAD

**Issue by Indekkusu545** [microsoft/vscode-remote-release#10312]
- VSCode Version: 1.93.1
- Local OS Version: Windows 11 24H2
- Remote OS Version: ---
- Remote Extension/Connection Type: Tunnel

- Logs: Tunnel service returned status code: 502 Bad Gateway。This may be caused by the extension committing `remote-explorer.refresh` .

Steps to Reproduce:

1. Install `Remote Development` Ext Pack.
2. Sign in a github account.
3. Click Remote Explorer side bar.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

I do not have any tunnel in my github account. However, every time I open the Remote Explorer for remote SSH developing, the tunnel will reporting errors. Is there a way to disable Remote Tunnel while using Remote SSH and Remote Explorer?

**Comment by derekbekoe** [comment]
@Indekkusu545 For the `502 Bad Gateway` error can you share logs (with sensitive info redacted)?
Of interest would be the timestamp and response headers.

**Comment by bamurtaugh** [comment]
If you're still experiencing this, please let us know. Thank you!
