### ISSUE TITLE
[Remote-SSH Bug]: reading and writing files very slow

### ISSUE THREAD

**Issue by jdb8** [microsoft/vscode-remote-release#10317]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

* saving a file should not hang with "Writing into file..." on remote servers via the SSH extension
* opening a file in the remote repository should complete in a reasonable amount of time without a long loading bar

### Steps To Reproduce

Since I'm working on a large internal monorepo, it's difficult to provide a full reproduction. I'm mainly hoping to get a sense of which logs might be worth digging into, or which settings are worth toggling based on hypotheses anyone else might have here.

My RW repro is essentially:

* open large monorepo in remote ssh
* open a file
* make a change and save the file
* repeat on various files until vscode gets "stuck" for a while with the right-hand-side popup showing "Writing into file..."
* after a while (>1 minute, or more) the file does eventually save

For the RO "slow to open file" case, it's as simple as using intellisense to navigate to another file, or opening up the file explorer, and then the file taking >1 minute to load.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[18:40:02.004] Remote server is listening on port 44345
[18:40:02.004] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":44345},"osReleaseId":"ubuntu","arch":"x86_64","tmpDir":"/run/user/3098","platform":"linux","execServerToken":"111a111a-11aa-1111-a1aa-111111a11111"},"serverStartTime":71,"installUnpackCode":""}
[18:40:02.005] Starting forwarding server. local port 50806 -> socksPort 50802 -> remotePort 44345
[18:40:02.005] Forwarding server listening on port 50806
[18:40:02.006] Waiting for ssh tunnel to be ready
[18:40:02.007] [Forwarding server port 50806] Got connection 0
[18:40:02.007] Tunneled port 44345 to local port 50806
[18:40:02.007] Resolved "ssh-remote+devbox" to "port 50806"
[18:40:02.007] Resolving exec server at port 50806
[18:40:02.008] [Forwarding server port 50806] Got connection 1
[18:40:02.054] Exec server for ssh-remote+devbox created and cached
[18:40:02.059] Opening exec server for ssh-remote+devbox
[18:40:02.064] Verified and reusing cached exec server for ssh-remote+devbox
```

</p>
</details>

### Anything else?

It should be noted that I've been using vscode's remote ssh functionality since it was released, and for the most part have not experienced much instability of any kind until fairly recently (a couple of months or so). It's unclear if something has regressed in some layer of my stack or if the codebase I'm working on has reached some kind of tipping point in terms of size, but it's very strange.

----

Something I tried, which helped with prior instability that I don't remember the details of, was toggling `"remote.SSH.useExecServer": false`. 

However as can be seen in the remote ssh log above, I still see `Resolving exec server`, `Exec server for ssh-remote+devbox created and cached`, `Verified and reusing cached exec server for ssh-remote+devbox` - is this a bug with the logs, or is my exec server setting not working?

---

Overall with this report I'm mainly hoping to get a lead on what this _could_ be. So far the only thing I can think of is some kind of remote host IO issue, since this seems to affect both reading and writing inconsistently/intermittently.  Any insight or links to other issues that I couldn't find would be appreciated!

Let me know if there is additional data that would help narrow down which piece of the puzzle is failing here.

**Comment by zerbobo** [comment]
+1, never occured one or two months ago. so are recent updates do something with this matter?

**Comment by sammcj** [comment]
I came to log a bug for this also, even on very powerful machines on the same network vscode seems to have started lagging up when trying to save files on the remote machine.

**Comment by joshspicer** [comment]
Would you folks be able to share [performance profiles](https://github.com/Microsoft/vscode/wiki/Performance-Issues) when the problem repros.  This may give us more info to work with.  Let me know if you have any questions on this wiki link
