### ISSUE TITLE
[Remote-SSH Bug]: VS Code remote server frozen at 100% CPU usage

### ISSUE THREAD

**Issue by pelmers-db** [microsoft/vscode-remote-release#10314]
- VSCode Version: 1.93.1
- Local OS Version: macos 14.6.1 (23G93)
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Server, remote ssh

- Logs: working on gathering

Steps to Reproduce:
It is unclear how exactly this happens, but multiple people on my team have run into an issue with VS Code server becoming unresponsive. It might be triggered by saving typescript files in a large project.

1. work for a while on typescript
2. save a file
3. vs code server is completely frozen

Symptom:
all actions in the vs code client editor become spinners. It doesn't say it's disconnected, but everything appears to last forever. 

Has this been reported before? Could it be something pathological coming from the TS LSP that's bringing down the server? What logs should I collect?

```
# process:
38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/server-main.js --start-server --server-data-dir .vscode-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all --connection-token-file .vscode-server/.38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.token

# top:
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
    4212 me  20   0 1700600 483192  44976 R 101.0   0.4  15:08.02 node
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by joshspicer** [comment]
Thanks for opening an issue.  Do you mind capturing some [performance metrics](https://github.com/Microsoft/vscode/wiki/Performance-Issues) and sharing the results.  This will help us better understand what we need to improve.

**Comment by joeygit** [comment]
I believe I'm having this same issue. I thought it was when I was saving/editing remote files. But it seems to only spike (both CPU and eventually memory as well) when I am running remote commands in the terminal. It sometimes errors out and I get a prompt saying "Disconnected. Attempting to Reconnect." Then I have to reload the session. A message also sometimes pops up saying "Remote Extension host terminated unexpectedly X times within the last 5 minutes."

[CPU-20241003T011902.294Z.cpuprofile.txt](https://github.com/user-attachments/files/17237876/CPU-20241003T011902.294Z.cpuprofile.txt)
[CPU-20241003T011946.818Z.cpuprofile.txt](https://github.com/user-attachments/files/17237878/CPU-20241003T011946.818Z.cpuprofile.txt)

![Capture](https://github.com/user-attachments/assets/91b591e1-1981-4f1a-a284-74ce40721fa0)

![image](https://github.com/user-attachments/assets/5c773440-480b-4b27-a2e6-192d7c77b73b)

**Comment by joeygit** [comment]
I believe its related to the HashiCorp Terraform extension. I had that extension disabled previously, and was still experiencing the issue. But then I rebooted the remote server, and could not reproduce the problem. As soon as I enabled the terraform extension the CPU and Memory shot up. Below is a screenshot of htop, it's hard to tell exactly what process is using the CPU and memory but these were the top ones when the server was still responding:
![image](https://github.com/user-attachments/assets/a0600ee1-1d37-4731-b425-83475d73d98d)

For now, I'll keep that extension disabled but it is handy so hoping for a fix. Let me know if I can send over any other logs or info. I can reproduce the problem easily.

**Comment by joeygit** [comment]
I was wrong. It doesn't seem to be the terraform extension. It was fine for a while but it started happening again. These two processes below are the ones using all the cpu. The top one is using all the memory. Once it runs out of memory or doesn't respond the sessions dies and restarts. Seem to be related to ripgrep and a DNS process.
![image](https://github.com/user-attachments/assets/f403d97d-5cf8-460d-acea-41c36b49f278)

**Comment by pelmers-db** [comment]
@joshspicer wait I don't see any instructions on profiling the remote process. https://github.com/Microsoft/vscode/wiki/Performance-Issues

here it's the remote server that's frozen at 100% cpu, what info can I give?

**Comment by joshspicer** [comment]
Oh apologies @pelmers-db, i think this wiki will be more helpful: https://github.com/microsoft/vscode-remote-release/wiki/Profiling-Remote-Processes
