### ISSUE TITLE
remote-ssh stuck at “waiting for server log”

### ISSUE THREAD

**Issue by yyl19** [microsoft/vscode-remote-release#10310]
Visual Studio Code
版本: 1.70.2 (user setup)提交:e4503b30fc78200f846c62cf8091b76ff5547662日期: 2022-08-16T05:35:13.448Z(2 年前)Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8:10.0.139.17-electron.0
OS: Windows NT x64 10.0.22631

remote:
Linux paraai-n32-h-01-ccs-master-2 4.19.90-24.4.v2101.ky10.aarch64 #1 SMP Mon May 24 14:45:37 CST 2021 aarch64 aarch64 aarch64 GNU/Linux

logs:
e52db3cf6450: running
Acquiring lock on /home/bingxing2/home/scx7kz4/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/vscode-remote-lock.scx7kz4.e4503b30fc78200f846c62cf8091b76ff5547662
Found existing installation at /home/bingxing2/home/scx7kz4/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662...
Checking /home/bingxing2/home/scx7kz4/.vscode-server/.e4503b30fc78200f846c62cf8091b76ff5547662.log and /home/bingxing2/home/scx7kz4/.vscode-server/.e4503b30fc78200f846c62cf8091b76ff5547662.pid for a running server
Looking for server with pid: 638908
Starting server with command... /home/bingxing2/home/scx7kz4/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all   &> "/home/bingxing2/home/scx7kz4/.vscode-server/.e4503b30fc78200f846c62cf8091b76ff5547662.log" < /dev/null
printenv:
    SHELL=/bin/bash
    PWD=/home/bingxing2/home/scx7kz4
    LOGNAME=scx7kz4
    MODULESHOME=/home/bingxing2/apps/tools/modules
    MOTD_SHOWN=pam
    HOME=/home/bingxing2/home/scx7kz4
    LANG=en_US.UTF-8
    VSCODE_AGENT_FOLDER=/home/bingxing2/home/scx7kz4/.vscode-server
    SSH_CONNECTION=36.103.203.3 8080 172.16.4.3 22
    USER=scx7kz4
    LOADEDMODULES=
    SHLVL=0
    SSH_CLIENT=36.103.203.3 8080 22
    ZIPINFO=-O GBK
    __MODULES_LMINIT=module use --append /home/bingxing2/apps/tools/modules/modulefiles
    UNZIP=-O GBK
    XDG_DATA_DIRS=/home/bingxing2/home/scx7kz4/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
    PATH=/home/bingxing2/home/scx7kz4/.local/bin:/home/bingxing2/home/scx7kz4/bin:/home/bingxing2/apps/tools/modules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
    MODULEPATH=/home/bingxing2/apps/modules:/home/bingxing2/apps/tools/modules/modulefiles
    MODULES_CMD=/home/bingxing2/apps/tools/modules/libexec/modulecmd.tcl
    BASH_FUNC_ml%%=() {  module ml "$@"
    }
    BASH_FUNC_module%%=() {  local _mlredir=0;
     if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
     if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
     _mlredir=0;
     else
     if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
     _mlredir=1;
     fi;
     fi;
     fi;
     case " $@ " in
     *' --no-redirect '*)
     _mlredir=0
     ;;
     *' --redirect '*)
     _mlredir=1
     ;;
     esac;
     if [ $_mlredir -eq 0 ]; then
     _module_raw "$@";
     else
     _module_raw "$@" 2>&1;
     fi
    }
    BASH_FUNC__module_raw%%=() {  eval "$(/usr/bin/tclsh '/home/bingxing2/apps/tools/modules/libexec/modulecmd.tcl' bash "$@")";
     _mlstatus=$?;
     return $_mlstatus
    }
    _=/usr/bin/printenv
Removing old logfile at /home/bingxing2/home/scx7kz4/.vscode-server/.e4503b30fc78200f846c62cf8091b76ff5547662.log
Spawned remote server: 644157
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...

**Comment by joshspicer** [comment]
This appears like the VS Code remote server is having an issue spawning.  Could you share the contents of any lgos files in the `.vscode-server` directory after launching. 

You may also manually try spawning the VS Code server that is downloaded into `vscode-server`.  It may provide a helpful error message and then crash (which would explain this loop you're in).

![Image](https://github.com/user-attachments/assets/ed17d7c4-5993-4cc0-a4cf-74f0a993dc51)


Perhaps there are some permission issues or something like AppArmor (total guesses) preventing the server from starting?
