### ISSUE TITLE
Dev Containers on Remote Host should use host wget/curl where available to download required binaries

### ISSUE THREAD

**Issue by PythonCoderAS** [microsoft/vscode-remote-release#10329]
Type: <b>Feature Request</b>

As of right now, Dev Containers will download data to the host VSCode instance and then upload it to the Remote Host's container. However, in the case where the host has a slow upload, this means that uploading the data can take a minute+, which makes it very difficult to use Dev Containers on a remote host.

Extension version: 0.387.0
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin x64 23.5.0
Modes:
Remote OS version: Linux x64 6.10.11-orbstack-00280-g1304bd068592
Connection to 'Container alpine (zen_yonath) @ f708bde446fe' could not be established

**Comment by chrmarti** [comment]
Tracking as https://github.com/microsoft/vscode-remote-release/issues/9414
