### ISSUE TITLE
Cannot open dev containers on M1 Mac

### ISSUE THREAD

**Issue by mikekistler** [microsoft/vscode-remote-release#10321]
Type: <b>Bug</b>

On my M1 MacBook Pro I try to open a dev container in VSCode and get this pop-up.

<img width="269" alt="Docker version 17 12 0 or" src="https://github.com/user-attachments/assets/72d75973-22e7-421f-aa1e-066298c9aec7">

If I go through the installation process I get Docker Desktop version 4.34.2:

<img width="508" alt="Software updates" src="https://github.com/user-attachments/assets/27fb32df-ebf2-440a-a41a-59104e4ceab0">

Then I try again to open a dev container and it gives the same pop-up again, requiring 17.12.0 or later.

Environment:
- MacOS version: Sonoma 14.6.1
- VSCode: Version: 1.93.1
- Dev Containers Extension: v0.384.0

Extension version: 0.384.0
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|. --crash-reporter-id 42fde34e-84f4-477f-b6aa-39b0a990b899|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
cf971741:31144450
fje88620:31121564
iacca1:31144502

```

</details>

**Comment by unfixa1** [comment]
The problem of not being able to open the development container on the M1 Mac may be related to the Docker version or configuration.
It is recommended that you use tools such as [servbay](servbay.com) to check the development environment and redeploy it, which is more compatible than docker on mac.

**Comment by chrmarti** [comment]
Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)

**Comment by mikekistler** [comment]
Here's the dev container log. It looks like the problem is that Docker is not on my path?
[log.txt](https://github.com/user-attachments/files/17162242/log.txt)

**Comment by mikekistler** [comment]
Seems that this is known problem:

https://stackoverflow.com/questions/64009138/docker-command-not-found-when-running-on-mac

**Comment by mikekistler** [comment]
I resolved this problem by adding the Docker bin directory to my path (in .zshrc):

```sh
# Add Docker Desktop for Mac (docker)
export PATH="$PATH:/Applications/Docker.app/Contents/Resources/bin/"
```

**Comment by bamurtaugh** [comment]
Thanks for the discussion! Since it looks like this issue is resolved with the above path setting, going to close this issue, but please let us know if you have any further questions/issues.
