### ISSUE TITLE
Launching server using command node.exe failed.

### ISSUE THREAD

**Issue by konosubakonoakua** [microsoft/vscode-remote-release#10327]
- VSCode Version: 1.93.1
- Local OS Version: win11 23h2
- Remote OS Version: ubuntu 22
- Remote Extension/Connection Type: Server

- Logs:
    ```bash
    2024-09-27 16:06:58.881 [info] (Client) Pylance async client (2024.9.2) started with python extension (2024.14.1)
    2024-09-27 16:06:58.891 [info] [Error - 4:06:58 PM] Pylance client: couldn't create connection to server.
    2024-09-27 16:06:58.891 [info] Launching server using command node.exe failed. Error: spawn node.exe ENOENT
Steps to Reproduce:

1. Connect to ubuntu sersver
2. open python file
3. see the error

Workaround:
```bash
# I have ~/.local/bin in $PATH
ln -s $(which node) ~/.local/bin/node.exe
```

**Comment by joshspicer** [comment]
I believe this is a configuration issue on either your local machine or remote machine, which you seem to solve by installing/placing `node` on your path?  These [docs](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#provide-your-own-nodejs-executable-to-run-pylance-with) suggest that Pylance should pick up a bundled node executable from VS Code, but from your logs it appears like that setting may have been changed to instead look on the path (per your workaround).

I would suggest engaging with the pylance folks as it seems to either be some assumptions made by that extension, or perhaps configuration on your end that is no longer using their defaults
