### ISSUE TITLE
Latest code-insider update broke Remote-SSH (Checking server status with wget)

### ISSUE THREAD

**Issue by OmriSama** [microsoft/vscode-remote-release#1032]
Code-insider details:
- Version: 1.37.0-insider (user setup)
- Commit: d4b3a7a22fe01ce6af85f9c59943ad54d6f6f205
- Date: 2019-07-25T16:23:12.371Z
- Electron: 4.2.7
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Windows_NT x64 10.0.17763

The latest version of `code-insiders` caused Remote SSH to stop working. The process pretty much gets stuck at this stage:
![image](https://user-images.githubusercontent.com/10534779/61898246-bfbeec00-aecd-11e9-95b2-f65cffae540b.png)

Meanwhile, current `code` stable works perfectly fine:
![image](https://user-images.githubusercontent.com/10534779/61898288-d5341600-aecd-11e9-8ee8-e0abb1783bd8.png)

**Comment by Britvich** [comment]
Likewise with me

**Comment by roblourens** [comment]
Will merge this to https://github.com/microsoft/vscode/issues/77951, sorry.
