### ISSUE TITLE
Cannot connect to SSH Host after Restart to Update

### ISSUE THREAD

**Issue by cmeans** [microsoft/vscode-remote-release#1033]
- VSCode Version: 1.37.0-insider
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:

1. Click Restart to Update
2. After restart, VS starts fine, but stuck with notification in lower right indicating:
Setting up SSH Host vagrant_vm (details) Initializiing VS Code Server.

Terminal Window shows:

[snip]...
Starting server...
Waiting for server log...

Does this issue occur when all extensions are disabled?: N/A
Without Remote-Connections this tool is useless to me.

**Comment by roblourens** [comment]
You can also click "details" to get the terminal then kill the terminal manually (garbage can icon)

**Comment by Tyriar** [comment]
Found the problem https://github.com/xtermjs/xterm.js/pull/2348

**Comment by Tyriar** [comment]
Sorry about the hassle everyone, this will be fixed in the next Insiders build which should drop about 7 hours from now. In the meantime you can jump on the nightly SSH build to unblock yourself.
