### ISSUE TITLE
"Rebuild Container" command is not available when attaching to running docker container

### ISSUE THREAD

**Issue by alita-moore** [microsoft/vscode-remote-release#10330]
- VSCode Version: 1.93.1
- Local OS Version: 14.6.1 (23G93)
- Remote OS Version: ubuntu 23.10
- Remote Extension/Connection Type: Containers

- Logs:

Steps to Reproduce:

1. Attach vscode to a running docker container
2. Notice that there is not a command to rebuild
![Screenshot 2024-09-27 at 1 26 21 PM](https://github.com/user-attachments/assets/3eb9151b-d9f9-4dc2-ae98-7661975f2e46)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by alita-moore** [comment]
note that I started the devcontainer by running the devcontainers cli from the terminal to start the container

**Comment by chrmarti** [comment]
"Attach" doesn't use the devcontainer.json. You could use Reopen Folder in Container, that would use the devcontainer.json and also use the existing container.
