### ISSUE TITLE
Stuck on Opening Remote...

### ISSUE THREAD

**Issue by CLAUDINLEO** [microsoft/vscode-remote-release#10340]
Type: <b>Bug</b>

After installing GitPod and running a remote workspace through visual studio code, attempting a different connection, in my case to a remote machine, gets stuck in "Opening remote..."

Extension version: 0.114.3
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Linux x64 6.8.0-40-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 432)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 3, 2|
|Memory (System)|15.26GB (5.84GB free)|
|Process Argv|--crash-reporter-id e57ff7dd-79bd-4fd2-a721-71024e9d9c2b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
cf971741:31144450
autoexpandse:31146404
5fd0e150:31146321

```

</details>

**Comment by joshspicer** [comment]
Thanks for taking the time to report an issue.  I'm not too familiar with Gitpod and how you'd like to integrate with VS Code - could you elaborate more on the remote environment you're connecting to?  Are you attempting to use the Remote - SSH extension? If so, please provide the log output from the extension so we can better understand if you're hitting a bug in that extension.

**Comment by CLAUDINLEO** [comment]
Hello Josh,

Thank you for addressing my problem. It seems to me that the bug I encountered appeared when I installed the GitPod extension. This introduced a new element in my .ssh/config file which also stores the credentials necessary  to attempt a connection to this remote environment. The conflict came not because I was unable to establish a connection with the remote machine, which I was, but because VSCode got stuck in "Opening Remote..." everytime I wanted to select a directory in which to work at (with Open Folder). I found out that, by removing these lines introduced by GitPod, I was able to use the Remote - SSH extension normally.

These are the lines added to the config file after GitPod extension installation (which I removed):

"remote.SSH.defaultExtensions": [
       "gitpod.gitpod-remote-ssh"
   ]

When running a connection with these lines, the log output seems normal:

***@***.***) Password:
cdcc21605fe6: running
Script executing under PID: 39796
Found existing installation at /home/rcli/idib057549/.vscode-server...
Starting VS Code CLI...
printenv:
    LC_PAPER=es_ES.UTF-8
    LESSKEY=/etc/lesskey.bin
    MANPATH=/apps/modules/LMOD/7.7/lmod/lmod/share/man:/usr/local/man:/usr/share/man:/opt/man
    NNTPSERVER=news
    LC_ADDRESS=es_ES.UTF-8
    XDG_SESSION_ID=328121
    LC_MONETARY=es_ES.UTF-8
    HOSTNAME=sllogin1
    XKEYSYMDB=/usr/X11R6/lib/X11/XKeysymDB
    SHELL=/bin/bash
    HOST=sllogin1
    HISTSIZE=1000
    MAKEFLAGS=--max-load 6
    PROFILEREAD=true
    SSH_CLIENT=92.178.86.201 44222 22
    MODULEPATH_ROOT=/apps/modules/LMOD/7.7/modulefiles
    TMPDIR=/scratch/tmp
    LC_NUMERIC=es_ES.UTF-8
    MORE=-sl
    LMOD_PKG=/apps/modules/LMOD/7.7/lmod/lmod
    LMOD_VERSION=7.7
    MODULES_BASE=/apps/modules
    USER=idib057549
    LC_TELEPHONE=es_ES.UTF-8
    LMOD_sys=Linux
    XNLSPATH=/usr/share/X11/nls
    HOSTTYPE=x86_64
    QEMU_AUDIO_DRV=pa
    FROM_HEADER=
    PAGER=less
    CSHEDIT=emacs
    XDG_CONFIG_DIRS=/etc/xdg
    MINICOM=-c on
    LIBGL_DEBUG=quiet
    PATH=/home/rcli/idib057549/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/lpp/mmfs/bin
    MAIL=/var/mail/idib057549
    CPU=x86_64
    SSH_SENDS_LOCALE=yes
    LC_IDENTIFICATION=es_ES.UTF-8
    LMOD_SETTARG_CMD=:
    PWD=/slgpfs/home/rcli/idib057549
    INPUTRC=/home/rcli/idib057549/.inputrc
    LANG=en_US.UTF-8
    MODULEPATH=/apps/modules/modulefiles/applications:/apps/modules/modulefiles/compilers:/apps/modules/modulefiles/environment:/apps/modules/modulefiles/libraries:/apps/modules/modulefiles/tools
    PYTHONSTARTUP=/etc/pythonstart
    LC_MEASUREMENT=es_ES.UTF-8
    LMOD_CMD=/apps/modules/LMOD/7.7/lmod/lmod/libexec/lmod
    AUDIODRIVER=pulseaudio
    GPG_TTY=not a tty
    HOME=/home/rcli/idib057549
    SHLVL=2
    QT_SYSTEM_DIR=/usr/share/desktop-data
    OSTYPE=linux
    LESS_ADVANCED_PREPROCESSOR=no
    BSC_MACHINE=starlife
    SDL_AUDIODRIVER=pulse
    ALSA_CONFIG_PATH=/etc/alsa-pulse.conf
    XCURSOR_THEME=DMZ
    WINDOWMANAGER=/usr/bin/icewm-session
    BASH_ENV=/apps/modules/LMOD/7.7/lmod/lmod/init/bash
    LOGNAME=idib057549
    MACHTYPE=x86_64-suse-linux
    LESS=-M -I -R
    ***@***.***,UTF-8,ISO-8859-15,CP1252
    CVS_RSH=ssh
    SSH_CONNECTION=92.178.86.201 44222 84.88.52.21 22
    XDG_DATA_DIRS=/usr/share
    MODULESHOME=/apps/modules/LMOD/7.7/lmod/lmod
    LESSOPEN=lessopen.sh %s
    LMOD_FULL_SETTARG_SUPPORT=no
    XDG_RUNTIME_DIR=/run/user/16099
    LMOD_DIR=/apps/modules/LMOD/7.7/lmod/lmod/libexec
    LC_TIME=es_ES.UTF-8
    LESSCLOSE=lessclose.sh %s %s
    HISTTIMEFORMAT=%h/%d - %H:%M:%S
    G_BROKEN_FILENAMES=1
    LC_NAME=es_ES.UTF-8
    COLORTERM=1
    BASH_FUNC_module%%=() {  source /apps/modules/module_wrapper.sh $*
    }
    BASH_FUNC_ml%%=() {  eval $($LMOD_DIR/ml_cmd "$@")
    }
    _=/usr/bin/printenv
Removing old logfile at /home/rcli/idib057549/.vscode-server/.cli.38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.log
Spawned remote CLI: 39857
Waiting for server log...
cdcc21605fe6: start
listeningOn==127.0.0.1:42203==
osReleaseId==sles==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/16099==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
serverStartTime==72==
execServerToken==7cbc1e84-bdfd-4577-a132-b579930ad31c==
platformDownloadPath==cli-alpine-x64==
cdcc21605fe6: end

I hope this information is of any help and might lead to a future solution to this bug.

Kind regards,

Leo
________________________________
De: Josh Spicer ***@***.***>
Enviado: miércoles, 2 de octubre de 2024 0:18
Para: microsoft/vscode-remote-release ***@***.***>
Cc: CLAUDIN, LEONARDO (FCRB) ***@***.***>; Author ***@***.***>
Asunto: Re: [microsoft/vscode-remote-release] Stuck on Opening Remote... (Issue #10340)


Thanks for taking the time to report an issue. I'm not too familiar with Gitpod and how you'd like to integrate with VS Code - could you elaborate more on the remote environment you're connecting to? Are you attempting to use the Remote - SSH extension? If so, please provide the log output from the extension so we can better understand if you're hitting a bug in that extension.
