### ISSUE TITLE
Please reopen 6829

### ISSUE THREAD

**Issue by tucked** [microsoft/vscode-remote-release#10346]
https://github.com/microsoft/vscode-remote-release/issues/6829

**Comment by GongT** [comment]
Yes, suddenly disconnect when multiple unsaved file is super annoying. But the connection is stateful, it seems super hard to recover this state, especially when 3rd party extensions installed.

I only need a way to fast save all files into somewhere (local machine is ok!), and recover (even just open them and let me merge by hand) after reconnect.

**Comment by tucked** [comment]
For me, the biggest downside is losing my shell sessions.

**Comment by joshspicer** [comment]
I've re-opened 6829 so the conversation can continue there - thanks
