### ISSUE TITLE
C# DevKit crashes on attempted install in dotnet:9.0 dev container

### ISSUE THREAD

**Issue by mikekistler** [microsoft/vscode-remote-release#10342]
Type: <b>Bug</b>

I created a new dev containter with this image:

"image": "mcr.microsoft.com/devcontainers/dotnet:9.0"

Then I attempted to install the C# DevKit VSCode extension in the dev container and the install crashes with this error message:

ENOENT: no such file or directory, mkdir '/home/vscode/.vscode-server/extensions/.c422a818-7c7b-4987-ad9c-d4b67ff4020f', ENOENT: no such file or directory, mkdir '/home/vscode/.vscode-server/extensions/.4ac55ddb-4c4a-41c5-a232-7d037ccf3119'

BTW ... I picked Dev Containers as the extension in the form only because I was not able to enter C# DevKit ... probably because it isn't installed -- which is the problem I'm reporting.

Extension version: 0.384.0
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 24.0.0
Modes:
Remote OS version: Linux arm64 6.10.4-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.15GB free)|
|Process Argv|. -g specification/oracle/resource-manager/Oracle.Database/preview/2024-08-01-preview/openapi.json --crash-reporter-id 419d896f-7e85-4c21-8845-5a77abdaec9d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: C# (.NET) @ desktop-linux|
|OS|Linux arm64 6.10.4-linuxkit|
|CPUs|unknown (10 x 0)|
|Memory (System)|7.66GB (6.75GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
cf971741:31144450
defaultse:31146405
iacca1:31150322
notype1:31150297
cc771715:31146322

```

</details>

**Comment by mikekistler** [comment]
This may have started happening just after I updated my system to MacOS 15 (Sequoia).

**Comment by mikekistler** [comment]
Just tried this again and got some additional info:
> mkdir: cannot create directory ‘/home/vscode/.config/vscode-dev-containers’: No space left on device

**Comment by chrmarti** [comment]
`No space left on device` suggests that this is an issue with your Docker installation.
