### ISSUE TITLE
Q: Using VSCode DevContainers in offline environment

### ISSUE THREAD

**Issue by hinogi** [microsoft/vscode-remote-release#10356]
So using docker in offline scenarios is annoying enough but devcontainers seem to be even worse.
Is there any guide that explains how to use docker devcontainer with only the containers available on the docker host and no internet connection?
One thing I already found out, if you kill the try to use `wget` on the remote host the fallback is to install from the current machine which let you use devcontainer cli.
As soon as you try to inspect a volume with a devcontainer it defaults to an alpine image which might or might not be around. Which will fail if not around but will not terminate.
Also, if I connect to a remote docker host via ssh and then try to use devcontainers without internet connection even with an image that is already there it hangs in Resolving Remote even in an empty folder `git rev-parse --show-cdup` which also does not terminate and will run forever.

So from every angle it seems that an internet connection must be available but is that really necessary?
```[tasklist]
### Tasks
```

**Comment by joshspicer** [comment]
I've had personal success in the past building the dev container in the past (leaving it open on my laptop) and _then_ going offline (in this case, on a plane).  I don't believe the extension is regularly tested in an offline scenario, nor do we have specific documentation on that scenario

**Comment by hinogi** [comment]
It would be also good to know how to start one yourself like docker/devcontainer cli wise. It is a bit opaque what is happening when you hit `inspect volume in devcontainer` or `checkout repo in container volume` or `reopen folder in container`. I can do the manual work when I know what has to be done.
Having the typescript node image around is not enough since that only starts node when fired up.

**Comment by hinogi** [comment]
I will try that but I guess that doesn't also provide the additional vscode server capability to the container?

**Comment by hinogi** [comment]
sadly there is still [#8564](https://github.com/microsoft/vscode-remote-release/issues/8564) which prevents me to try it in an offline environement

**Comment by chrmarti** [comment]
@hinogi You can install the dev container CLI on your ssh server with `npm install -g @devcontainers/cli`.

**Comment by hinogi** [comment]
> [@hinogi](https://github.com/hinogi) You can install the dev container CLI on your ssh server with `npm install -g @devcontainers/cli`.

the ssh server has no internet access
