### ISSUE TITLE
Remote development "Retry as Sudo"

### ISSUE THREAD

**Issue by HendrikJan** [microsoft/vscode-remote-release#1035]
I would like ```Retry as Sudo``` in remote development in the same way as it works in local development.

In local development, when you have insufficient permissions, a message pops up:

    Failed to save 'filename': Insufficient permissions. Select 'Retry as Sudo' to retry as superuser.

Currently in remote development you get the message:

    Failed to save 'filename': Unable to write file (NoPermissions...

And you have no way to save the file.

**Comment by roblourens** [comment]
Is that the whole error message? If you check the devtools console (Help > Toggle Developer Tools) are there any other errors?
