### ISSUE TITLE
[Dev Containers] `try a example` button at left dev container pannel open the example in local instead of remote when in remote window

### ISSUE THREAD

**Issue by NewUserHa** [microsoft/vscode-remote-release#10352]
`try a example` button at left dev container pannel open the example in local instead of remote when in remote window

- VSCode Version: 1.94
- Local OS Version: win10 1803
- Remote OS Version: centos7
- Remote Extension/Connection Type: Containers

- Logs:

Steps to Reproduce:
1. connect to a host
2. in the new window, click the `try a example` button then select a random one, say python

Does this issue occur when you try this locally?: 
Does this issue occur when you try this locally and all extensions are disabled?:

**Comment by bamurtaugh** [comment]
Thanks for filing. Could you please include a screenshot or recording of what you're seeing?
