### ISSUE TITLE
After opening a folder required to enter password twice, again

### ISSUE THREAD

**Issue by EmbeddedBacon** [microsoft/vscode-remote-release#1036]
Hello,

  For the remote host I connect we use password, looking to setup public key but requires IT support.  So, each time VS Code connects it requires entering the password, twice!  This is fine, but whenever I need to update an extension that requires a restart I need to enter my password, twice, again.  Also, if I open a folder I have to go through the process of entering my password twice.  It appears that VS Code closes that window and is reopening it again, why?  Is there a way to limit the number of times I need to enter my password?  Can VS Code save the password somewhere, encrypted, and use the stored password? 

  If I can get IT to help support public key authentication I hope using Putty's pageant to lower the burden of entering passwords.

Regards,
Mark

**Comment by roblourens** [comment]
Working on improving this experience https://github.com/microsoft/vscode-remote-release/issues/642

**Comment by EmbeddedBacon** [comment]
Thanks, subscribe to parent to watch this.  I have to say other than the passwords the new features work beautifully and I use it was my main development flow since VS Code July update came out
