### ISSUE TITLE
[Remote-SSH Bug]: Unable to install vscode server on host without internet connection

### ISSUE THREAD

**Issue by dibalavs** [microsoft/vscode-remote-release#10373]
### Is there an existing issue for this bug?

- [x] I have searched the existing issues

### Required Troubleshooting Steps

- [x] I have followed these troubleshooting steps
- [x] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

Hello,
I just update my vscode instance to 1.94.1 And got a problem during connection to remote host.

I have 2 computers
1 - Laptop with internet access and LAN access
2 - Remote pc with access to LAN but without access to the internet.

Both computers are availabe over LAN.

When I  try to connect from Laptop to remote PC, vscode is trying to download server from the internet without any success, so I unable to use my workspaces.  I always see permanent notification "Downloading VS Code Server..."

I have read about tunnels. I tried to enable tunnel (Remote tunnles: Turn on tunnel access...)  . but without success. tunnel Tries to 
 ask my Microsoft account (Why???)

### Expected Behavior

vscode install server over existing ssh connection from laptop.

See screenshot

![Image](https://github.com/user-attachments/assets/8524177a-b1bc-461b-9e5f-70cfad51fb9a)

It looks like kind of chicken and egg problem.

To set up tunnel, I need vscode server installed,
But to install server, I need working tunnel.

### Steps To Reproduce

1) Connect to remote pc without internet access
2) Happy debugging ;)

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
Remote tunnel service:

2024-10-09 10:21:55.370 [info] No other tunnel running
2024-10-09 10:22:22.578 [info] No authentication session available, not starting tunnel
2024-10-09 10:23:08.735 [info] No authentication session available, not starting tunnel
2024-10-09 10:23:45.842 [info] No authentication session available, not starting tunnel
2024-10-09 10:24:22.381 [info] No authentication session available, not starting tunnel
2024-10-09 10:35:52.025 [info] No authentication session available, not starting tunnel
2024-10-09 10:36:16.861 [info] No authentication session available, not starting tunnel
```

[remote_ssh.log](https://github.com/user-attachments/files/17304440/remote_ssh.log)

</p>
</details>

### Anything else?

Remote - SSH v0.115.0

Version: 1.94.1 (user setup)
Commit: e10f2369d0d9614a452462f2e01cdc4aa9486296
Date: 2024-10-05T05:44:32.189Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by JammyJellyfish** [comment]
I have the same Issue, I have a PC with a proxied connection.
The setting "Remote.SSH: Local Server Download" is set to "Always". 

After the update to 1.94.1, It gets stuck at "Downloading VS Code Server...".
In the Output I get some "Failed to download" and a "Forbidden-message" of my proxies, even though vs code should not use the internet connection on the remote PC.

Unfortunately I can't use VS-code at all if I'm not able to use this Extension.

**Comment by nzomi** [comment]
I've encountered the same issue where I can't download the code server after updating VS Code. The previous version worked fine, and I've tried multiple solutions, but none have been effective.

**Comment by joshspicer** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/10344
