### ISSUE TITLE
Remote-SSH doesn't work with KillUserProcesses=yes in systemd

### ISSUE THREAD

**Issue by chaserhkj** [microsoft/vscode-remote-release#1037]
- VSCode Version:
    - Version: 1.36.1 (system setup)
    - Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
    - Date: 2019-07-08T22:59:35.033Z
    - Electron: 4.2.5
    - Chrome: 69.0.3497.128
    - Node.js: 10.11.0
    - V8: 6.9.427.31-electron.0
    - OS: Windows_NT x64 10.0.18362
- Local OS Version: Windows 10 Pro 1903
- Remote OS Version: Arch Linux x86_64
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Setup Arch Linux ssh access with proper public key authentication
2. Try to connect to Arch Linux host from local VS Code installation
3. Client would stuck on "Opening remote"

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Outputs panel contents:

```
remote-ssh@0.44.2
win32 x64
SSH Resolver called for "ssh-remote+desktop", attempt 1
SSH Resolver called for host: desktop
Setting up SSH remote "desktop"
Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
Running script with connection command: "ssh"  -o ClearAllForwardings=true    "desktop" bash
Install and start server if needed
> 
> ]0;C:\WINDOWS\SYSTEM32\cmd.exe
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> Running remote connection script
> 
> Migrating .vscode-remote to /home/hkj/.vscode-server...
> Installing to /home/hkj/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191
> 529...
> Downloading with wget
> 
> Download complete
> 
> SHELL=/bin/zsh
> PWD=/home/hkj
> LOGNAME=hkj
> XDG_SESSION_TYPE=tty
> HOME=/home/hkj
> VSCODE_AGENT_FOLDER=/home/hkj/.vscode-server
> SSH_CONNECTION=192.168.233.2 55834 192.168.233.1 22
> XDG_SESSION_CLASS=user
> USER=hkj
> SHLVL=1
> XDG_SESSION_ID=130
> XDG_RUNTIME_DIR=/run/user/1000
> SSH_CLIENT=192.168.233.2 55834 22
> PATH=/usr/local/sbin:/usr/local/bin:/usr/bin
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
> MAIL=/var/spool/mail/hkj
> _JAVA_OPTIONS=-Dawt.useSystemAAFontSettings=on
> OLDPWD=/home/hkj/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529
> 
> _=/usr/bin/printenv
> 
> 
> Starting server...
> 
> Waiting for server log...
> 
> 
>  
> 
> *
> 
> * Reminder: You may only use this software with Visual Studio family products,  
> 
> 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> 
> *
> 
> 
> 
> 7336e726-fb17-43f6-bd02-d3057af8953f==40649==35617==
> 
> 
"install" terminal command done
Received install output: 7336e726-fb17-43f6-bd02-d3057af8953f==40649==35617==
Server is listening on port 40649
Running script with connection command: "ssh" -L 127.0.0.1:40649:127.0.0.1:40649     "desktop" bash
Spawning tunnel with: type "C:\Users\admin\AppData\Local\Temp\vscode-linux-multi-line-command-desktop-638921980.sh" | "ssh" -L 127.0.0.1:40649:127.0.0.1:40649     "desktop" bash
> 
> ]0;C:\WINDOWS\SYSTEM32\cmd.exe
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> Connected to SSH Host - Please do not close this terminal
> 
Spawned SSH tunnel between local port 40649 and remote port 40649
Waiting for ssh tunnel to be ready
Tunneling remote port 40649 to local port 40649
Resolved "ssh-remote+desktop" to "127.0.0.1:40649"
------




> channel 2: open failed: connect failed: Connection refused
> 
> channel 3: open failed: connect failed: Connection refused
> channel 4: open failed: connect failed: Connection refused
> 
```

I debugged this a little on my own and have a few conclusions:

1. SSH setup seems to be fine, I could ssh to server by ssh command without any problems. TCP forwarding works well too.
2. On server I setup a script to poll node processes to see whats going on there, only to find that the vscode server exits on itself in less than two seconds when launched, and so the client is left hanging there. sshd logs on server suggests that as well:
    ```
    Jul 26 03:43:47 hkj-desktop sshd[9540]: Accepted publickey for hkj from 192.168.233.2 port 56902 ssh2: RSA SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    Jul 26 03:43:47 hkj-desktop sshd[9540]: pam_unix(sshd:session): session opened for user hkj by (uid=0)
    Jul 26 03:43:48 hkj-desktop sshd[9540]: pam_unix(sshd:session): session closed for user hkj
    ```

    The session for vscode-server exited immediately after it opened.
3. However, manually running the vscode server on remote works fine. I ran it by `~/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/server.sh --port=0` and it seems to be listening there without any problem. It only fails on ssh from vscode client
4. This only happens on my Arch Linux desktop, if connecting to my Ubuntu VPS, it would just work fine.

Is there anyway I could get more detailed logs from the server side? It might help a lot in pinpointing the actual problem.

**Comment by roblourens** [comment]
Can you check the server log at `~/.vscode-server/. 2213894ea0415ee8c85c5eea0d0ff81ecc191529.log`?

**Comment by chaserhkj** [comment]
I cleared the old `.vscode-server` folder last time to try a complete new run and did not collect that log. I shot a new run with triggering the exact same bug just with different port numbers and the log messages read below:

```
*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


IP Address: 192.168.0.1
IP Address: 10.117.127.251
IP Address: 192.168.233.1
IP Address: 172.17.0.1
webview server listening on 38559
Extension host agent listening on 33619
```

Can't see any errors, but would the multiple (virtual) network interfaces and ip addresses on my workstation be an issue?

**Comment by roblourens** [comment]
I'm not concerned about that or about the ssh session exiting, we expect it to launch the server then terminate. Is the server still running? What is the output of `ps ax | grep 2213894ea0415ee8c85c5eea0d0ff81ecc191529`?

**Comment by chaserhkj** [comment]
`ps ax | grep 2213894ea0415ee8c85c5eea0d0ff81ecc191529` won't output any other process other than the grep process.

But the fact that the ssh session is expected to launch the server then terminate actually rings a bell to me. I looked up further on this issue, and I think I found what's happening there.

This is related to systemd's handling of user processes on my workstation, particularly with systemd-logind configuration at `/etc/systemd/logind.conf`, where `KillUserProcesses=yes`

Basically systemd manages sshd sessions in a different way then the traditional Unix way where sshd session processes are children processes of the sshd master process. In systemd every sshd session would be considered as a normal user session scope, not distinctive from other user logged in sessions. And `KillUserProcesses` config field in `/etc/systemd/logind.conf` manages where a user logs out of a session, whether all remaining processes in that session would be killed.

So the problem to my issue is that with `KillUserProcesses=yes`, systemd would kill everything in a ssh session once that ssh session terminates (this was discussed on [debian bug tracker](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825394) as well), killing the vscode server. The traditional double-fork method of spawning a daemon in Unix won't work, since this kill happens with cgroup in systemd. After setting `KillUserProcesses=no`, vscode remote could work successfully, this is the same situation with my VPS as well.

However, doing that `KillUserProcesses=no` has another problem with vscode remote. since in vscode port forwarding ssh session is kept with `sleep infinity`, this means that with `KillUserProcesses=no`, these sleep processes would not be killed even after vscode disconnects. This could potentially leave a lot of zombie processes on the server, if the user connects and disconnects for multiple times.

Generally, I think there're two possible optional solutions to this problem:

1. To set `KillUserProcesses=yes` on server side, but spawn vscode-server using `systemd-run`, this would start vscode-server as an anonymous systemd service, which is no longer managed by the systemd session scopes and would not be killed later. I currently am using this workaround, by changing the start line in `~/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/server.sh` to 
```
systemd-run --user -P "$ROOT/node" ${INSPECT:-} "$ROOT/out/vs/server/main.js" "$@"
```
2. To set `KillUserProcesses=no` on server side, but do not spawn `sleep infinity` processes on server when creating ssh tunnel. There's a `-N` flag in OpenSSH client that instructs the client not to create a shell session and hang the client once the connection is established. This should be a much more cleaner method to keep the tunnel on then spawning that `sleep`

Anyway, I think some documentation with `KillUserProcesses` configurations would definitely be very helpful, since a lot of linux systems are default using systemd nowadays and I suppose someone else sooner or later would come across this same problem ...

**Comment by roblourens** [comment]
For another workaround, you could try installing the nightly version of the ssh extension (uninstall the stable version first) then set `"remote.SSH.useDynamicForwarding": true`. In this mode, we only start one ssh process and the ssh session that starts the server stays alive. 

However, reconnection would not work (when you lose the internet connection and the ssh process goes down) and if you connect window A, then window B to the same host, then close window A, then the server would go down and kill window B

**Comment by roblourens** [comment]
Maybe we can detect when this systemd option is set and use `systemd-run`. But that will take some investigation on my end.

**Comment by aanderse** [comment]
> However, doing that KillUserProcesses=no has another problem with vscode remote. since in vscode port forwarding ssh session is kept with sleep infinity, this means that with KillUserProcesses=no, these sleep processes would not be killed even after vscode disconnects. This could potentially leave a lot of zombie processes on the server, if the user connects and disconnects for multiple times.

I have ran into this issue as well. Thanks for the explanation @chaserhkj, and thanks for potential solutions @roblourens. Looking forward to seeing how this evolves.

**Comment by jclay** [comment]
@chaserhkj I'm so happy you pointed this out. You allowed me to track down this issue that has been preventing me from using the Remote-SSH extension to connect to my home desktop.

For those using KDE Neon, the `KillUserProcess` is enabled, even though it shows up in `/etc/systemd/logind.conf`.

It is enabled in `/usr/lib/systemd/logind.conf.d/40_kde_neon_allyourprocessarebelongtous.conf` (Some context on [why it was enabled here](https://bugs.kde.org/show_bug.cgi?id=363851).)

Disabling it can be done by creating a new file with a higher prefix such as: `/usr/lib/systemd/logind.conf.d/50_kde_neon_keep_processes_alive.conf`. It should contain the following:

```
[Login]
KillUserProcesses=No
```

A reboot afterwards solves the issue and allows connecting from VSCode.
