### ISSUE TITLE
Please implement soft start (quick resume)

### ISSUE THREAD

**Issue by marcoiosif** [microsoft/vscode-remote-release#10387]
Hello.

I've been using devcontainers for a couple of months, and I don't understand why it's necessary to install everything again (reinstalling the devcontainers container, starting the Docker Compose services again) when reopening the folder. If devcontainer is already running, everything is there in the memory.

It would be a good idea to have a quick start option if it has been recently closed and then reopened.

Thanks

**Comment by joshspicer** [comment]
If the dev container is already running the extension should just re-attach itself.  If you're not seeing that, please provide us your logs or repro steps so we can take a look. Thanks!
