### ISSUE TITLE
How to open an local terminal when using Remote - SSH

### ISSUE THREAD

**Issue by xiaopao2014** [microsoft/vscode-remote-release#10380]
Type: <b>Feature Request</b>

hi guys,
             i am an android system developer, using Remote -SSH to connect ubuntu server.
            Mostly i need to do 3 things : 
            a. open remote folder using vscode remote -ssh , edit code
            b.using remote bash to build the image 
            c. push the image file to local device using local bash
         
            The question is: i could'nt find any way to open a local terminal when in Remote-ssh mode

Extension version: 0.113.1
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.6.0
Modes:
Remote OS version: Linux x64 5.15.0-105-generic

**Comment by joshspicer** [comment]
For (c), perhaps you could try using [`scp`](https://www.freecodecamp.org/news/scp-linux-command-example-how-to-ssh-file-transfer-from-remote-to-local/) to copy your files from the remote machine back to your local machine.

**Comment by xiaopao2014** [comment]
um . yes scp maybe works. In most condiction , we need to open an local terminal to run some command.
I think if we to do all things in on window , it would be excellent!  For now, what confusing me is there is no way to start an local terminl window when in Remove-ssh mode


![Device topo](https://github.com/user-attachments/assets/8ec7a949-6ee7-4760-8d73-f196f4472aa9)
![Terminal menu](https://github.com/user-attachments/assets/5c24473e-3993-4fff-8e22-802fe3d71aa8)

**Comment by joshspicer** [comment]
Thanks for the diagram.  I'd suggest opening a second VS Code window (not connected to your remote machine) to access a local terminal.  Conceptually, I think it's helpful to think of your first VS Code window as though you were typing directly on the remote workstation. Using a tool like `scp` you can copy items between the two machines.
