### ISSUE TITLE
My remote ssh servers are not loading

### ISSUE THREAD

**Issue by Shiba-Kar** [microsoft/vscode-remote-release#10402]
Type: <b>Bug</b>

1. Tap the left pannel remote ssh icon.
2. Keeps loading but no remote servers showing up.

Extension version: 0.115.0
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id f2e5dca3-8acf-4e5a-8e23-bee9ce9328cf|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca2:31156134
notype1:31157159
5fd0e150:31155592
dwcopilot:31164048
icondisabled:31158250

```

</details>

**Comment by exaland** [comment]
Same issue

 ![Image](https://github.com/user-attachments/assets/6d5789f1-3599-41da-9edd-d9703800242e)

The list is Empty

**Comment by joshspicer** [comment]
For Remote SSH, this list is powered by your local machine's SSH configuration files (on macOS/linux, `~/.ssh/config`).  Does that file exist on your machine?

What do you see if you run this command?  

![Image](https://github.com/user-attachments/assets/64d560db-ad8e-46cc-86a6-53fd7a336b6d)

I see: 

![Image](https://github.com/user-attachments/assets/541700ed-6c0b-4ff6-ba66-727f1786eab4)


You can also override this path with a setting, is that overwritten?

![Image](https://github.com/user-attachments/assets/62fd1336-0a27-4399-8a40-f75294785b46)

**Comment by exaland** [comment]
Bug fixed thanks
