### ISSUE TITLE
I can not see dev containet in botomm lef corner

### ISSUE THREAD

**Issue by vvidov** [microsoft/vscode-remote-release#10401]
![Image](https://github.com/user-attachments/assets/a3cebaf1-6d53-42a2-aca8-32443209702b)

Does this occur consistently? Yes
Repro steps:

1. If I try reopen in Container
2.
Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=d:\dev\think-cell,target=/workspaces/think-cell,consistency=cached --mount type=volume,src=vscode,dst=/vscode --mount type=bind,src=\\wsl.localhost\Ubuntu\mnt\wslg\runtime-dir\wayland-0,dst=/tmp/vscode-wayland-5dd21eb8-8eb0-48cd-9dae-a6f11ca04074.sock -l devcontainer.local_folder=d:\dev\think-cell -l devcontainer.config_file=d:\dev\think-cell\.devcontainer\devcontainer.json --entrypoint /bin/sh -l devcontainer.metadata=[{"postCreateCommand":"g++ --version","customizations":{"vscode":{"extensions":["ms-vscode.cpptools"],"settings":{"terminal.integrated.shell.linux":"/bin/bash"}}}}] gcc:13.2 -c echo Container started
[2024-10-21T12:15:18.971Z] docker: Error response from daemon: can't access specified distro mount service:
 stat /run/guest-services/distro-services/ubuntu.sock: no such file or directory

Version: 1.29.3
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.94.2
Language: en

**Comment by chrmarti** [comment]
This appears to be an issue with Docker Desktop for Windows:
```
[2024-10-21T12:15:18.971Z] docker: Error response from daemon: can't access specified distro mount service:
stat /run/guest-services/distro-services/ubuntu.sock: no such file or directory
```
Maybe try restarting your machine or reinstalling Docker Desktop.

**Comment by vvidov** [comment]
it works now, but I do not know, what I have done:)
until next time
