### ISSUE TITLE
Unable to establish connection to host in VSCode - Insiders

### ISSUE THREAD

**Issue by juliussimonelli** [microsoft/vscode-remote-release#1040]
I had been using the same method to create an SSH connection between my docker container on AWS and VSCode using Remote - SSH (nightly) and it was working and recently it stopped working. I create a port forwarding ssh to a docker instance inside EC2 with something like this ssh -L 2201:localhost:2222 user@host -N -i ~/.ssh/id_rsa -v. user@host is an AWS instance running a docker container and I publish port 2222 when I create it the docker container, but I have to map port 2201 on the host to port 2222 in the container. Then I connect to it using a config file that looks like:

Host *
     User root
     Port 2201
     IdentityFile ~/id_rsa
     
Then in VSCode I go to "Remote-SSH: Connect to Host" and enter localhost.

This procedure is working on the stable build of VSCode, but is no longer working on the nightly of VSCode Insiders. I get a message saying "Could not establish connection to "localhost"."

Here's the output from Remote - SSH:
 > Checking server status on port 46451 with wget
> 9982ad08-f1d7-4da6-97be-4258b1a567a0==46451==36301=="centos"==
[15:13:35.669] Received install output: 
9982ad08-f1d7-4da6-97be-4258b1a567a0==46451==36301=="centos"==
[15:13:35.669] Failed to parse remote port from server output: 
9982ad08-f1d7-4da6-97be-4258b1a567a0==46451==36301=="centos"==
[15:13:35.670] 
[15:13:35.670] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"UnparsableOutput"},"measures":{"resolveAttempts":1,"retries":1}}
[15:13:35.670] ------

System information:

CPUs | Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: enabledoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | 2, 2, 2
Memory (System) | 16.00GB (0.22GB free)
Process Argv |  
Screen Reader | no
VM | 0%

**Comment by roblourens** [comment]
See microsoft/vscode-remote-release#1039 - fix is on the way
