### ISSUE TITLE
Too many server processes at once

### ISSUE THREAD

**Issue by jdonovan** [microsoft/vscode-remote-release#10408]
My website is hosted on [Hostinger](https://www.hostinger.com/), which, in addition to CPU and memory constraints, also limits the number of simultaneous (or nearly simultaneous) processes that I can run on the host.  Currently that number is 120 processes.  Lately when I use VS Code's Remote SSH extension to connect, it immediately exceeds my process quota, leading to errors and connection issues across my whole website, even though CPU and RAM usage are nearly flatline.

When I run `ps -aux` on the server, I certainly don't see 120 processes, so I assume the processes that Hostinger is counting are short-lived forks or shell commands that terminate in milliseconds.  Nevertheless, spinning up so many processes at once is a dealbreaker given the quota.

This didn't used to happen when I used the Remote SSH extension.  There has to be a way to rework the implementation to use a small handful of long-running processes rather than a barrage of quick ones.  Are there any plans on the horizon to do that, or do I need to abandon the Remote SSH extension entirely?

**Comment by joshspicer** [comment]
Interesting, i've never heard of such a constraint.  

Have you tried the [troubleshooting steps](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting)?  Specifically disabling `useExecServer` mode.  That is "newer" (not that new) so maybe your previous experience with the extension was in that mode. 

"Exec server" mode uses a bootstrap program before starting the server, so I think it would have a slightly higher absolute process count compared to with the feature disabled.

**Comment by jdonovan** [comment]
> Have you tried the [troubleshooting steps](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting)? Specifically disabling `useExecServer` mode. That is "newer" (not that new) so maybe your previous experience with the extension was in that mode.
> 
> "Exec server" mode uses a bootstrap program before starting the server, so I think it would have a slightly higher absolute process count compared to with the feature disabled.

That seems to help.  Here is a plot of the concurrent processes, from Hostinger's control panel.  The peak on the left is before I disabled `useExecServer` mode; the peak on the right is after disabling it.  Now connecting using Remote SSH uses merely _half_ of my quota.  That still seems high, but at least it isn't crashing my web server anymore.

![Image](https://github.com/user-attachments/assets/71ee9719-eb76-4204-a5f6-8c5ce890b2ff)

**Comment by matteoFeduzi** [comment]
Hi @jdonovan, I have the same problem as you. I also use Hostinger and I think exactly the same plan as yours.

Is there any additional even more efficient solution to reduce the running processes?

Thank you very much.

**Comment by userofit123** [comment]
I have been dealing with this for years and have found no solution. While I wish this wasn't an issue, I do wish there were others that have a solution for this or that would vote for this so that the issue could be fixed.

**Comment by YujieH3** [comment]
I'm using computing cluster that also has this issue. Hope it gets reopened.
