### ISSUE TITLE
Command failed: docker cp 25c240aa33624928e14022a384c814e890ccec62d6a5986b95d416e367d1c077:/etc/passwd -

### ISSUE THREAD

**Issue by jonfen** [microsoft/vscode-remote-release#1041]
This is not an issue with `code-insiders`, but it is an issue with `code`.

Distributor ID:	_Ubuntu_
Description:	_Ubuntu 18.04.2 LTS_
Release:	_18.04_
Codename:	_bionic_
Docker version _19.03.0, build aeac949_
Code:
  _1.36.1
  2213894ea0415ee8c85c5eea0d0ff81ecc191529
  x64_

The following error happens when [vscode attempts to open the .devcontainer](https://github.com/microsoft/vscode-remote-try-python#setting-up-the-development-container)

> Error response from daemon: error processing tar file: docker-tar: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_readline_unlocked version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
> : exit status 127
> 
> Command failed: docker cp 25c240aa33624928e14022a384c814e890ccec62d6a5986b95d416e367d1c077:/etc/passwd -

$ ldd /lib/x86_64-linux-gnu/libnss_files.so.2
	linux-vdso.so.1 (0x00007ffd87d3e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0ae07b3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0ae0db6000)

$ ldd /lib/x86_64-linux-gnu/libc.so.6
	/lib64/ld-linux-x86-64.so.2 (0x00007f64e18ef000)
	linux-vdso.so.1 (0x00007ffc80bf7000)

**Comment by Chuxel** [comment]
@jonfen I am seeing that error come up in relation to the latest version of Docker independant of VS Code.  e.g. https://github.com/docker-library/golang/issues/292

I have a Ubuntu Budgie 18.04 machine with Docker 18.09.7 on it that is working without issue. You might want to back down to the stable channel install of Docker while some of this gets ironed out on the Docker side.

**Comment by aeschli** [comment]
It's a problem with Docker 19.03. https://github.com/moby/moby/issues/39449

**Comment by DaniloNC** [comment]
I was having the same problem on a Linux Mint 19.1 machine where I installed the docket using the https://get.docker.com

In my case, even though the Linux mint 19.1 is based on ubuntu 18.04, the apt repository was configured to use debian buster.

My /etc/apt/source.list.d/docker.list file before was
```
deb [arch=amd64] https://download.docker.com/linux/debian buster stable
```

I fix the issue on my computer by uninstalling docker-ce, docker-ce-cli, containerd.io; fixing the docker.list manually, reinstalling docker-ce and reboot the machine:

```
sudo apt-get remove docker-ce docker-ce-cli containerd.io
echo 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable' | sudo tee /etc/apt/sources.list.d/docker.list
sudo apt-get install docker-ce
sudo reboot
```

Not sure if this is the same problem to people having this issue.

**Comment by Chuxel** [comment]
@DaniloNC That appears to be the convenience script which will install edge bits instead of stable bits.  The Debian stable channel gives you 18.09.7.

> Docker provides convenience scripts at get.docker.com and test.docker.com for installing edge and testing versions of Docker Engine - Community into development environments quickly and non-interactively ..  Using these scripts is not recommended for production environments, and you should understand the potential risks before you use them

These steps will install stable: https://docs.docker.com/install/linux/docker-ce/debian/#install-using-the-repository

Typically edge works fine, but you can think about it like VS Code Insiders - which is why they don't recommend using it in production.

Type `docker --version` to see if you're on a later build.

**Comment by bocian85** [comment]
Unfortunately I am having the same problem on 18.09.7 from debian stretch

`# cat /etc/debian_version`
>9.9  

`# uname -a`
>Linux compute-atm01 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux

`# cat docker-repo.list`  

>deb [arch=amd64] https://download.docker.com/linux/debian stretch stable

`# docker --version` 

>Docker version 18.09.7, build 2d0083d

`# docker cp test_docker:/var/www/html/wp-config-sample.php ./wp-config.php`

>Error response from daemon: error processing tar file: docker-tar: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_readline_unlocked, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
>: exit status 127

`# dpkg -l | grep libc6`

>ii  libc6:amd64                          2.24-11+deb9u4                     amd64        GNU C Library: Shared libraries
ii  libc6-dev:amd64                      2.24-11+deb9u4                     amd64        GNU C Library: Development Libraries and Header Files
ii  libc6-i386                           2.24-11+deb9u4                     amd64        GNU C Library: 32-bit shared libraries for AMD64

**Comment by Chuxel** [comment]
This appears to have been an issue that occurred in a small window of Docker versions.  We are not seeing it repro currently - please update Docker and let us know if you are still seeing this problem.

//cc: @chrmarti
