### ISSUE TITLE
How to connect X11 display to devcontainer

### ISSUE THREAD

**Issue by JackCaster** [microsoft/vscode-remote-release#10414]
How do you recommend to enable X11 forwarding between the host and the docker container? Online there are many, many suggestions but none has been successful so far, unfortunately. I believe it would be beneficial to many if there were an official guide on how to go about it.

Currently, I can get the display working via Remote-SSH (between my host and remote compute). Once I am connected to the remote compute, I also need to start a Dev container. Then, the display won't work. 

I tried:
- adding the `"initializeCommand": "xhost +"` to `.devcontainer.json`
- tried all of these suggestions: https://stackoverflow.com/questions/60733288/devcontainer-how-to-make-x-display-work-mount-graphics-inside-docker-in-visual

It seems to me, that there is not a standard and consistent way of enabling X11 in the devcontainer. 

Would you be able to help?

- VSCode Version: 1.94.2
- Local OS Version: Ubuntu 22.04.5 LTS
- Remote OS Version: Ubuntu 22.04.5 LTS
- Remote Extension/Connection Type: SSH and Containers

**Comment by chrmarti** [comment]
The Dev Containers extension attempt to forward X11 automatically. Can you try without any X11 additions to the devcontainers.json? If that doesn't work please append the log (`F1` > `Dev Containers: Show Container Log`).
