### ISSUE TITLE
Cannot connect to a host machine

### ISSUE THREAD

**Issue by bobo-91** [microsoft/vscode-remote-release#10433]
Type: <b>Performance Issue</b>

I have a remote machine that I can ssh into using command prompt. But using VS Code remote-ssh plugin, it is either really unstable or even fails to connect. 

Extension version: 0.115.0
VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

**Comment by joshspicer** [comment]
Thanks for taking the time to open an issue. We will need more information to understand your issue.  Please see https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting#performance-issues
