### ISSUE TITLE
[Remote-SSH Bug]: vscode server processes didn't closed after client closed.

### ISSUE THREAD

**Issue by pointertobios** [microsoft/vscode-remote-release#10448]
### Is there an existing issue for this bug?

- [x] I have searched the existing issues

### Required Troubleshooting Steps

- [x] I have followed these troubleshooting steps
- [x] I have tried both values of the `remote.SSH.useLocalServer` setting [(more info here)](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting#troubleshooting-steps)

### Connect Locally

It connects successfully

### Expected Behavior

server processes exit after client close

### Steps To Reproduce

1. Environment:
    - Server: Debian12
    - Client:Windows11
2. Start a ssh remote vscode window.
3. Close it.
4. Link the server using ssh in the terminal.
5. Check process.You will find many vscode related processes.
![Image](https://github.com/user-attachments/assets/d71bffb0-69b0-4ab0-8088-d9357af79170)

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```

```

</p>
</details>

**Comment by joshspicer** [comment]
These processes will terminate after some time of no connection.  Keeping the connection around for a limited amount of time provides a better experience if, say, you have an unstable internet connection.
