### ISSUE TITLE
localhost URL in dev container translated to 127.0.0.1 when opened in host system

### ISSUE THREAD

**Issue by mikekistler** [microsoft/vscode-remote-release#10442]
Type: <b>Bug</b>

When clicking on a link that contains localhost in the terminal within a dev container (e.g. https://localhost:5001), the browser opens in the host system with 127.0.0.1 instead.

CORS policies treat 127.0.0.1 as a different host from localhost, so if the page that is opened makes calls back into the container (e.g. SwaggerUI), those calls will fail if CORS is not configured (which is common).

This seems very close to the problem reported in 

https://github.com/microsoft/vscode-remote-release/issues/2711

But that was closed over four years ago as fixed so either there has been a regression or it fixed a different problem.

Extension version: 0.390.0
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Darwin arm64 24.1.0
Modes:
Connection to 'dev-container+7b22686f737450617468223a222f55736572732f6d696b656b6973746c65722f50726f6a656374732f6d696b656b6973746c65722f6173706e65742d6f70656e6170692d6578616d706c6573222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f6d696b656b6973746c65722f50726f6a656374732f6d696b656b6973746c65722f6173706e65742d6f70656e6170692d6578616d706c65732f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f6d696b656b6973746c65722f50726f6a656374732f6d696b656b6973746c65722f6173706e65742d6f70656e6170692d6578616d706c65732f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f6d696b656b6973746c65722f50726f6a656374732f6d696b656b6973746c65722f6173706e65742d6f70656e6170692d6578616d706c65732f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d' could not be established
Remote OS version: Linux arm64 6.10.4-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 419d896f-7e85-4c21-8845-5a77abdaec9d|
|Screen Reader|no|
|VM|0%|

Connection to 'dev-container+7b22686f737450617468223a222f55736572732f6d696b656b6973746c65722f50726f6a656374732f6d696b656b6973746c65722f6173706e65742d6f70656e6170692d6578616d706c6573222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f6d696b656b6973746c65722f50726f6a656374732f6d696b656b6973746c65722f6173706e65742d6f70656e6170692d6578616d706c65732f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f6d696b656b6973746c65722f50726f6a656374732f6d696b656b6973746c65722f6173706e65742d6f70656e6170692d6578616d706c65732f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f6d696b656b6973746c65722f50726f6a656374732f6d696b656b6973746c65722f6173706e65742d6f70656e6170692d6578616d706c65732f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d' could not be established

|Item|Value|
|---|---|
|Remote|Dev Container: C# (.NET) @ desktop-linux|
|OS|Linux arm64 6.10.4-linuxkit|
|CPUs|unknown (10 x 0)|
|Memory (System)|7.66GB (2.21GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by alexr00** [comment]
I'm not able to reproduce this issue. Do you have any `forwardPorts` in your devcontainer.json?
