### ISSUE TITLE
Cannot find any Dev Containers .

### ISSUE THREAD

**Issue by liangzelang** [microsoft/vscode-remote-release#10447]
Type: <b>Bug</b>

I can find my running containers in Terminal when using 'docker ps -a' , but vscode `ctrl + shift + P` option ` Attach to running container` , there is no available containers to choose.

Extension version: 0.309.0
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 5850U with Radeon Graphics      (16 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|14.83GB (2.20GB free)|
|Process Argv|--crash-reporter-id 5f35523d-3a3b-4b24-aa28-a3597feb5b72|
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|SSH: 172.24.136.223|
|OS|Linux x64 5.15.0-72-generic|
|CPUs|Intel(R) Xeon(R) Platinum 8468V (180 x 2400)|
|Memory (System)|2891.95GB (2769.93GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
nativeloc2:31134642
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by chrmarti** [comment]
This command only shows the running containers. Maybe the containers are stopped?

Please also update to the latest VS Code (1.95) and Dev Containers (0.388.0) versions to get the latest fixes.

**Comment by liangzelang** [comment]
Thanks for your reply. I have found the reason why no Dev containers can be found. There are various Dev containers on the server. Before VSCode attaches to a Dev container, it tries to find all the running Dev containers using docker ps -q. Then, it retrieves information about these containers with docker inspect --type container xx yy zz. If there is a container that is abnormal and cannot read information, the process will hang, and this will cause the list of available Dev containers to be empty.

**Comment by chrmarti** [comment]
Thanks, closing for now as this does not seem to be a common scenario.
