### ISSUE TITLE
Unable to install Dev Containers extension while connected to remote with dev tunnel

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-remote-release#10469]
- VSCode Version: 1.96.0-insider
- Local OS Version: Chrome browser
- Remote OS Version: CBL-Mariner/Linux 2.0.20240829
- Remote Extension/Connection Type: Server

- Logs:

Steps to Reproduce:

1. Connect to a remote machine using dev tunnels
2. Try to install the Dev Containers extension

Met with error: ![Image](https://github.com/user-attachments/assets/118e2262-32da-454b-9b04-4e4a8b366f7c)

I am connected to a remote that should support installing this extension, why can't it be installed?

Does this issue occur when you try this locally?: No. When I connect to the remote using desktop vscode I'm able to install the extension. It seems to work fine. So maybe just an issue where vscode web doesn't allow installing it to the remote.
Does this issue occur when you try this locally and all extensions are disabled?: n/a

**Comment by connor4312** [comment]
Dev container needs to be a web extension for this. That's something that's been a backlog item for a while.

**Comment by alexweininger** [comment]
Dang, I thought because it was connected to a remote host that it could be installed as a node extension on the host.

**Comment by connor4312** [comment]
It can't, because in that case it's the extension _doing_ the resolving of the remote (it just calls the remote tunnels extension too) so that has to exist on the web side

**Comment by chrmarti** [comment]
We are tracking as https://github.com/microsoft/vscode-remote-release/issues/9059.
