### ISSUE TITLE
Adding port visibility column when running vscode within WSL 2

### ISSUE THREAD

**Issue by Mumbawa** [microsoft/vscode-remote-release#10478]
We know that in the PORTS tab in vs code there is a column named "visibility"
![Image](https://github.com/user-attachments/assets/e9348397-83b0-40ef-8049-a59a12409368)

Would it be possible to have this column present when running vs code within WSL 2?

 As you can see, this column is not present in this case:

![Image](https://github.com/user-attachments/assets/3156881b-c3c4-4a8c-bdef-135eb2c05c93)

**Comment by alexr00** [comment]
The visibility column is only shown in places where the visibility can be changed. Witha WSL remote, the visibility can't be changed.
