### ISSUE TITLE
[Remote-SSH Bug]: Local server download fails on proxy

### ISSUE THREAD

**Issue by bitagoras** [microsoft/vscode-remote-release#10474]
### Is there an existing issue for this bug?

- [x] I have searched the existing issues

### Required Troubleshooting Steps

- [x] I have followed these troubleshooting steps
- [x] I have tried both values of the `remote.SSH.useLocalServer` setting [(more info here)](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting#troubleshooting-steps)

### Connect Locally

It connects successfully

### Error description

Since vscode version 1.94.0 the local remote server download fails in case of a proxy and has to be done manually. In our company our local vscode runs in Windows behind a proxy and we connect remotely to Linux servers. The local vscode is able to download and update any extension without the need of specifying the proxy settings, which are provided automatically by the Chromium kernel of vscode. In the past this worked also for the local remote server download. But since October 2024 the update of the remote vscode server always fails.

### Steps To Reproduce

The setting for the server download is: `"remote.SSH.localServerDownload": "always"`

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

`... [server] Error installing server: error requesting https://update.code.visualstudio.com/commit:e8653663e8840adaf45af01eab5c627a5af81807/server-linux-legacy-x64/stable: 407 <html><head><title> ...`

After `<html><head><title>` follows the page from the Proxy that says "Credentials are missing".

</p>
</details>

### Anything else?

Old versions of remote-ssh do not solve the issue. Therefore it is not obvious to me if this issue ticket is correctly placed at vscode-remote extension or if it is an issue of vscode.

**Comment by bitagoras** [comment]
#10344 might give a workaround for this issue.

**Comment by bitagoras** [comment]
I finally solved the issue by setting:
`"remote.SSH.useExecServer": false`

I also use the default setting for `"remote.SSH.useLocalServer": true` and also unset the option for `"http.proxy"`

The option useExecServer says: "Uses the a new bootstrapping mode when connecting to a server. Can be toggled off in the event of connection issues.". It is unclear to me why this is connected to the server download. But I will close the ticket now.

**Comment by joshspicer** [comment]
Thanks for following up and sharing your workaround.

Does your work use a NTLM proxy?  We're tracking better support for this specific case in https://github.com/microsoft/vscode-remote-release/issues/10521
