### ISSUE TITLE
Too many safe declarations in .gitconfig

### ISSUE THREAD

**Issue by arterrey** [microsoft/vscode-remote-release#10484]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94.2
- OS Version: macOS 15 -> Remote SSH to Debian 11  -> Remote Container (Docker 27.0.3) to python:3.12-alpine

Steps to Reproduce:

I don't know how to reproduce, but inside my remote remote container I have a `.gitconfig` that looks like

`/root/.gitconfig`:

```
[user]
        name = ***
        email = ***
[filter "lfs"]
        clean = git-lfs clean -- %f
        smudge = git-lfs smudge -- %f
        process = git-lfs filter-process
        required = true
[credential]
        helper = ***

[pull]
        rebase = true
[safe]
        directory = /main
        directory = /main
        directory = /main
        directory = /main
        directory = /main
        directory = /main
        directory = /main
        directory = /main
        directory = /main
...
[snip about 16,000 lines]
...
        directory = /main
        directory = /main
        directory = /main
        directory = /main
```

The expected output is to just have one `directory = /main` lines instead of 16k.

```
~ # grep 'directory = /main' .gitconfig | wc
  16103   48309  305957
```

**Comment by chrmarti** [comment]
@arterrey I guess you have the `.gitconfig` mounted from the host machine?

**Comment by alexr00** [comment]
What's the best way to verify this?

**Comment by chrmarti** [comment]
To verify use a configuration that mounts the local gitconfig (use USERPROFILE instead of HOME on Windows):
```json
{
	"image": "mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm",
	"mounts": [
		"source=${localEnv:HOME}/.gitconfig,target=/home/node/.gitconfig,type=bind"
	]
}
```
Reopen the folder with this configuration in the Dev Container, make the workspace folder in the container owned by root (`sudo chown root:root .`) and initialize a Git repo.
- Verify that `git status` reports dubious ownership on the folder.
- Then run `Dev Containers: Rebuild Container` twice and verify that the .gitconfig gets only a single safe directory entry for the workspace folder.

**Comment by alexr00** [comment]
I don't get any `safe` entries.

**Comment by chrmarti** [comment]
Git fails to write to the `~/.gitconfig` on macOS for me. Not an issue with the fix. 🤔 

Please instead verify with:
```json
{
	"image": "mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm",
	"mounts": [
		"source=tmphome,target=/home/node,type=volume"
	]
}
```

This will also preserve the `~/.gitconfig` across rebuilds.

**Comment by alexr00** [comment]
Ok, here's how I verified:
- Opened a folder with that mount config in a container
- Opened `/home/node/.gitconfig` and added a comment
- Rebuilt the container
- Verified that the comment was still there.
