### ISSUE TITLE
`vscode://vscode-remote/ssh-remote+` to open a new VSCode window

### ISSUE THREAD

**Issue by Andrei-Aksionov** [microsoft/vscode-remote-release#10493]
Hey there 👋 

I'm generating a link in a form of 
```sh
vscode://vscode-remote/ssh-remote+<SSH_HOST>
```

that I provide to a user, so by clicking on it an SSH connection to the running server is created.

The problem is that it opens a connection in the current window. 

**The desired behavior is to open a new window and open a connection there.**

I tried to modify the link:
```sh
1. vscode://vscode-remote/ssh-remote+<SSH_HOST>?openInNewWindow=true
2. vscode://vscode-remote/ssh-remote+<SSH_HOST>?newWindow=true
```

but that didn't help.

-----

Is it supported at all?
Or it needs to be added?

Thanks

**Comment by joshspicer** [comment]
I'm not familiar with the history here, but perhaps this is a regression from https://github.com/microsoft/vscode/issues/191902

**Comment by Andrei-Aksionov** [comment]
Hello @joshspicer 
Yes, this worked like a charm! 😊 
Thanks a lot 👍
