### ISSUE TITLE
Can't ask questions on SO

### ISSUE THREAD

**Issue by evertiro** [Microsoft/vscode-remote-release#105]
You say to ask questions on SO and tag them with visual-studio-code-remote, but that tag doesn't exist and I can't create tags...

As such, I'm going to ask the question here and will happily move it to SO if the tag is added there and nobody has an answer... once connected to a remote, how do you disconnect?

🚨 The issue tracker is not for questions 🚨

If you have a question about VS Code, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code and about
VS Code Remote on https://stackoverflow.com/questions/tagged/visual-studio-code-remote.

**Comment by mjbvz** [comment]
Use the `vscode-remote-tag` until we can create a synonym for it
