### ISSUE TITLE
[Remote-SSH Bug]: windows update broke addon

### ISSUE THREAD

**Issue by epgfm** [microsoft/vscode-remote-release#10515]
### Is there an existing issue for this bug?

- [x] I have searched the existing issues

### Required Troubleshooting Steps

- [x] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting [(more info here)](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting#troubleshooting-steps)

### Connect Locally

It connects successfully

### Expected Behavior

After windows update, VSCode connects to a remote (Ubuntu VM running locally) successfully

### Steps To Reproduce

Update Windows
Attempt to connect to a remote

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

### Anything else?

This is more of an FYI. Posting this as it might help others (will update with logs later)
I lost a lot of time at work today getting Remote explorer to work again on a colleague's W11 workstation.
The root cause of the problem was an update to the newest W11 version.
During the update, windows apparently reset an user environment variable (TEMP) to a default value of C:\WINDOWS\TEMP.
This caused an obscure connection issue with a message of "Connection denied"
After creating a "tmp" directory in the home directory of my colleague and setting the user env variable TEMP to that directory, the extension worked again.

**Comment by joshspicer** [comment]
Thanks for taking the time to open an issue.  Could you please share your logs (`> Remote-SSH: Show Log` in the command palette) after reproducing the issue?
