### ISSUE TITLE
dev containers being mounted with hashes instead of names, leading into 'workspace not found' errors.

### ISSUE THREAD

**Issue by Molier** [microsoft/vscode-remote-release#10514]
# [Dev Containers] Workspace mounted with hash instead of folder name in WSL2

## Environment
- VS Code: 1.95.3 (stable) and 1.96.0-insider
- Dev Containers Extension: 0.391.0
- OS: Windows 10.0.22635.4515
- WSL: Version 2.3.24.0, Kernel 5.15.153.1-2
- Docker Desktop: 4.36.0 (175267)
- Docker Engine: 27.3.1
- Remote Type: Dev Containers

## Description
When opening a folder in a devcontainer, the workspace is sometimes mounted with a hash instead of the proper folder name. For example:
```/workspaces/0110a523bdc23904cd5568a7d6fc183dfe16c64ca76142a30185b6a070dedffe```
instead of
```/workspaces/project-name```

The issue appears to be triggered particularly after adding a post-install script and rebuilding the container. The first build works correctly, but subsequent builds result in the hash-based workspace path.

## Steps to Reproduce
1. Create a new folder with a `.devcontainer/devcontainer.json`:
```json
{
    "name": "Python 3-test",
    "image": "mcr.microsoft.com/devcontainers/python:1.1.9-3.11-bookworm",
    "postCreateCommand": "zsh -l .devcontainer/post-install.sh",
    "remoteUser": "root",
    "customizations": {
        "vscode": {
            "extensions": [
                "ms-python.python",
                "ms-toolsai.jupyter",
                "ms-azuretools.vscode-azurefunctions",
                "mhutchie.git-graph",
                "charliermarsh.ruff",
                "ms-python.vscode-pylance",
                "esbenp.prettier-vscode"
            ],
            "settings": {
                "python.pythonPath": "/usr/local/bin/python",
                "terminal.integrated.profiles.linux": {
                    "zsh": {
                        "path": "/usr/bin/zsh"
                    }
                },
                "terminal.integrated.defaultProfile.linux": "zsh"
            }
        }
    }
}
```
2. Add .devcontainer/post-install.sh:

```sh
source $NVM_DIR/nvm.sh
nvm install 23
npm i -g azure-functions-core-tools@4 --unsafe-perm true
pipx install poetry && poetry install
pipx install pre-commit
pipx install deptry
pre-commit install
sed -i '/^ZSH_THEME/c\ZSH_THEME="agnoster"' ~/.zshrc
```
Open folder in container first time - works correctly
Make a change to devcontainer config or post-install script
Rebuild container
Workspace is now mounted with a hash instead of proper name

Expected Behavior
The workspace should consistently mount as /workspaces/project-name regardless of rebuilds or configuration changes.
Actual Behavior
After rebuilding, the workspace is mounted as /workspaces/<hash> and the VS Code UI shows multiple workspace entries with various hashes.
Additional Context

<details>
<summary>Container Inspection</summary>

```json
{
    "Mounts": [
        {
            "Type": "bind",
            "Source": "/mnt/wsl/docker-desktop-bind-mounts/Ubuntu/0110a523bdc23904cd5568a7d6fc183dfe16c64ca76142a30185b6a070dedffe",
            "Destination": "/workspaces/0110a523bdc23904cd5568a7d6fc183dfe16c64ca76142a30185b6a070dedffe",
            "Mode": "",
            "RW": true,
            "Propagation": "rprivate"
        }
    ]
}
```

</details>

![Image](https://github.com/user-attachments/assets/36668312-d891-4a98-bfaf-1aa543311c47)

WSL Configuration
```ini
[boot]
systemd=true
```
### I've tried:

Removing containers and rebuilding from scratch
Using both VS Code stable and insiders
Verifying Docker Desktop WSL integration is enabled

The issue persists across VS Code restarts and container rebuilds.

# Additional Technical Details
[remoteContainers-2024-11-28T14-02-16.196Z.log](https://github.com/user-attachments/files/17949400/remoteContainers-2024-11-28T14-02-16.196Z.log)

## Log Analysis

1. The bind mount configuration shows that Docker Desktop is creating mounts with hashed paths:
```shell
Source: /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/<hash>
Target: /workspaces/<hash>
```

2. The failure sequence appears to be:
* Initial container creation works
* Post-install script fails (exit code 127)
* Subsequent mounts use hashed directories instead of proper workspace names

3.Error pattern shows spaces in paths may be contributing:
```shell
source=/mnt/c/Users/oscar/Downloads/test run,target=/workspaces/test run
```
### Observed Behavior in Logs

Docker Desktop is accumulating multiple bind mount directories in /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/
The post-install script failure may be triggering a fallback mounting behavior
Container inspection shows proper labels but incorrect mount paths

Additional Environment Details

WSL Distribution: Ubuntu
Docker Engine: 27.3.1
containerd: 1.7.21
runc: 1.1.13

##### finally my 2 cents...:
possibly: 
* Docker Desktop's bind mount handling with WSL2 getting confused by multiple rebuilds
* A race condition between the bind mount setup and the post-install script execution
* Path handling issues with spaces or special characters

**Comment by Molier** [comment]
## Additional Finding
Investigating `/mnt/wsl/docker-desktop-bind-mounts/Ubuntu/` reveals multiple hash-named directories accumulating:
```shell
➜  Ubuntu ls /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/
0110a523bdc23904cd5568a7d6fc183dfe16c64ca76142a30185b6a070dedffe
0f27eebe173f247f4788a4ed7190a18a0a37c592e1946cd7d79b737fb4a5f321
[... multiple other hash directories ...]

**Comment by Molier** [comment]
# 2 logs, first time works, second time the path is wrong.

## first boot: working log:

[remoteContainers-2024-11-28T15-15-21.045Z.log](https://github.com/user-attachments/files/17950010/remoteContainers-2024-11-28T15-15-21.045Z.log)
## second boot: not working anymore:
[remoteContainers-2024-11-28T15-29-37.114Z.log](https://github.com/user-attachments/files/17950032/remoteContainers-2024-11-28T15-29-37.114Z.log)

# analysis of the logs: 

The key difference between the working (log 2) and non-working (log 1) Dev Container setup lies in how the workspace folder is mounted inside the container:

Log 2 (Working):
  
`
[2024-11-28T15:15:22.000Z] Start: Run: docker run ... --mount type=bind,source=/mnt/c/Users/oscar/Nextcloud/work/OpenEnergyID,target=/workspaces/OpenEnergyID ...
`
    
The source is the correct WSL path to your project, and the target mounts it directly as /workspaces/OpenEnergyID. This is the expected behavior.

Log 1 (Not Working):

`[2024-11-28T15:29:39.025Z] Start: Run: docker run ... --mount type=bind,source=/mnt/wsl/docker-desktop-bind-mounts/Ubuntu/19069a979c0cb89ef07026d4294e38fa110acd773f80e2db7057190ee238b508,target=/workspaces/19069a979c0cb89ef07026d4294e38fa110acd773f80e2db7057190ee238b508 ...
`

The source points to a hashed directory within Docker Desktop's bind mount area (/mnt/wsl/docker-desktop-bind-mounts/.../<hash>). This hashed directory should be an intermediary, transparently linking to your actual project directory. However, it appears this link is broken or misconfigured, leading to the observed issues. The target also mirrors this hashed directory name inside the container, which is incorrect.


so the second boot the devcontainer tries to incorrectly open the hashed workspace?

**Comment by Molier** [comment]
yes exactly, but I'm doing nothing different, just pressing reopen in container or rebuild container. What's causing that behaviour? something in my config? 

Is it intended to do that and am I doing something wrong? Or is it caused by something and it's a bug?

**Comment by chrmarti** [comment]
This seems to be some combination of Docker's mount points and wslpath's behavior. I don't see anything you could do to affect this. I will add a check for this case and try to correct it by putting the path under `/mnt/<driveletter>` together.

**Comment by Molier** [comment]
it seems to happen a lot more with the insiders edition I feel like, but its quite hit or miss.

What can i now do to follow the progress? what does the milestone + closed mean?

> This seems to be some combination of Docker's mount points and wslpath's behavior. I don't see anything you could do to affect this. I will add a check for this case and try to correct it by putting the path under `/mnt/<driveletter>` together.

**Comment by Molier** [comment]
Or perhaps some way to use [devcontainer cli](https://code.visualstudio.com/docs/devcontainers/devcontainer-cli)? to build/reopen the devcontainer correctly?

**Comment by Molier** [comment]
it also always makes a new container, every rebuild, which does not feel like normal behavior at all.

 ![Image](https://github.com/user-attachments/assets/cf528b8e-61ef-4e5b-9ac8-74322662005a)

**Comment by chrmarti** [comment]
@Molier Could you give Dev Containers 0.392.0-pre-release a try and let me know if that fixes it? Thanks.

**Comment by rzhao271** [comment]
Dev Containers still doesn't seem to work on my Windows machine. Letting someone else verify this issue.
![Downloading VS Code Server fails](https://github.com/user-attachments/assets/627206fe-a880-4967-98c6-d371414305e4)

**Comment by mfeeney-rsos** [comment]
I can confirm I'm getting the same issue. 

Using the following devcontainer.json:

```
{
  "name": "staboard-gql-container",
  "image": "mcr.microsoft.com/devcontainers/typescript-node:1-16-bookworm",
  "workspaceFolder": "/workspaces/staboard-gql",
  "mounts": [
    "source=${localWorkspaceFolder},target=/workspaces/staboard-gql,type=bind"
  ],    
  "customizations": {
    "vscode": {
      "extensions": ["dbaeumer.vscode-eslint", "eamodio.gitlens", "esbenp.prettier-vscode"],
      "settings": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.formatOnPaste": true,
        "editor.formatOnSave": true
      }
    }
  }
}
```

Building and opening the first time gives the following log and and docker containers:
[DevContainer1.log](https://github.com/user-attachments/files/18030336/DevContainer1.log)
![Image](https://github.com/user-attachments/assets/62dd97ec-9639-4f6d-9f02-76eb549e8f45)

Closing the window and immediately re-opening results in the following:
[DevContainer2.log](https://github.com/user-attachments/files/18030362/DevContainer2.log)
![Image](https://github.com/user-attachments/assets/db6d08f2-8aff-4384-8d92-67e16aa456b8)

**Comment by chrmarti** [comment]
@mfeeney-rsos Could you give Dev Containers 0.392.0-pre-release a try and let me know if that fixes it? Thanks.

**Comment by mfeeney-rsos** [comment]
> [@mfeeney-rsos](https://github.com/mfeeney-rsos) Could you give Dev Containers 0.392.0-pre-release a try and let me know if that fixes it? Thanks.

Looks like it crashes out before creating the container with the pre-release. Attached the log file.

[DevContainer3.log](https://github.com/user-attachments/files/18042013/DevContainer3.log)

**Comment by rzhao271** [comment]
The issue LGTM now. I'll leave it to Christof to confirm whether the crash log is related to this issue or belongs in a new one.

**Comment by chrmarti** [comment]
@mfeeney-rsos This sounds like you might be mounting your `/workspaces/staboard-gql` folder manually when it is already mounted automatically:
```
docker: Error response from daemon: Duplicate mount point: /workspaces/staboard-gql.
```

**Comment by mfeeney-rsos** [comment]
@chrmarti That definitely had something to do with it. I removed the following two lines from devcontainer.json:

```
"workspaceFolder": "/workspaces/staboard-gql",
"mounts": ["source=${localWorkspaceFolder},target=/workspaces/staboard-gql,type=bind"],
```

Now I'm running v0.393.0 (pre-release) and it appears to be working correctly with the following config file:

```
{
  "name": "staboard-gql-container",
  "image": "mcr.microsoft.com/devcontainers/typescript-node:1-16-bookworm",
  "postCreateCommand": "bash -i -c 'npm install --legacy-peer-deps'",
  "customizations": {
    "vscode": {
      "extensions": ["dbaeumer.vscode-eslint", "eamodio.gitlens", "esbenp.prettier-vscode"],
      "settings": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.formatOnPaste": true,
        "editor.formatOnSave": true
      }
    }
  }
}
```

I can also confirm that it's also not creating new containers every time.
