### ISSUE TITLE
Allow user to enter passphrase for configured ssh key

### ISSUE THREAD

**Issue by wmujawar** [microsoft/vscode-remote-release#10511]
Type: <b>Feature Request</b>

Show a dialog or some option for user to enter the SSH key passphrase when connecting to remove machine via SSH

Extension version: 0.115.1
VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 24.1.0
Modes:

**Comment by joshspicer** [comment]
Are you instead seeing the password prompt where you expect to see the passphrase prompt?


There is support for entering a passphrase for an SSH key:

![Image](https://github.com/user-attachments/assets/8b917072-4d44-48f6-9c81-2ac46aeb5161)

I did notice, however, if I removed my key from my ssh-agent (ssh-add -d <key-name>) and the configuration _didn't_ state an `IdentityFile`, then SSH would default to prompting for password.  This behavior was the same both within VS Code and directly on the terminal.

I suggest either (1) adding your key with `ssh-add` to a local auth agent or (2) in your host's configuration ensure you're stating which key you want to use:

```
Host myHost
    HostName 1.2.3.4
    User josh
    IdentityFile ~/.ssh/my-key # <----
``` 

When I did (2) I was able to see the passphrase prompt and connect successfully from VS Code. 

Feel free to reopen with some more detailed steps, and i'll be happy to dig in further!
