### ISSUE TITLE
Opening remote SSH directories in one step by entering a host:path address

### ISSUE THREAD

**Issue by slikts** [microsoft/vscode-remote-release#1051]
There should be a way to open remote SSH directories just by entering a remote path; for example, having a "Remote-SSH: Open path" command that opens a prompt, and the prompt would take a path in the SSH `host:path` format.

Currently connecting to a remote SSH directory takes too many clicks and also waiting for the connection in-between, so working remotely over SSH is much less convenient than just being able to run `code .` in remote WSL.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/585
