### ISSUE TITLE
[Remote-SSH Bug]:

### ISSUE THREAD

**Issue by beo0001** [microsoft/vscode-remote-release#10516]
### Is there an existing issue for this bug?

- [x] I have searched the existing issues

### Required Troubleshooting Steps

- [x] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting [(more info here)](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting#troubleshooting-steps)

### Connect Locally

It connects successfully

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by sijial430** [comment]
I have the same issue. log attached below[remote_ssh_failed.log](https://github.com/user-attachments/files/17967460/remote_ssh_failed.log)

**Comment by joshspicer** [comment]
If you'd like to report an issue please fill out the body of the issue and then feel free to re-open
