### ISSUE TITLE
Using a small panel width causes Explorer and editor groups to never load

### ISSUE THREAD

**Issue by kylrth** [microsoft/vscode-remote-release#1052]
I always toggle my panel position to the right when using a large display. When the panel width is not large enough to display the "Connected to SSH Host - Please do not close this terminal" on one line, upon reloading the workspace the Explorer and editor groups continually display a loading bar without completing.

Someone else please confirm this, because the behavior is kind of surprising.

- VSCode Version: Version: 1.37.0-insider (user setup)
- Commit: 3802a986823977ec472fc993854e1a753037fc8f
- Date: 2019-07-29T05:30:35.768Z
- Local OS: Windows_NT x64 6.3.9600 (Windows 8)
- Remote OS Version: CentOS Linux Release 7.4.1708
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to the remote directory.
2. Use `View: Toggle Panel Position` to move the panel to the right.
3. Resize the panel so that part of the "Connected to SSH Host" message is cut off.
4. `Developer: Reload Window`
5. Observe that the SSH tunnel displays the success message, but the Explorer and editor groups never display their contents.
6. Resize the panel so the entire SSH tunnel message fits.
7. `Developer: Reload Window`
8. Observe that the views successfully display their contents.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: I deleted `.vscode-server-insiders` on the remote machine and found the same result.

**Comment by roblourens** [comment]
This is new but you should only see this if you have `"remote.SSH.showLoginTerminal": true` set. Do you? That setting should no longer be necessary and it should work if you remove it.

**Comment by kylrth** [comment]
That is true. Removing that setting fixes this.

**Comment by roblourens** [comment]
Ok, thanks for trying it. Sorry for the break but I'm just going to kill that setting soon and won't do anything else for this.
