### ISSUE TITLE
CS50 setup not working in code space

### ISSUE THREAD

**Issue by tashveekhare** [microsoft/vscode-remote-release#10531]
Does this occur consistently? Yes
Repro steps:

1. opening the code space
2.getting a popup:
This codespace is currently running in recovery mode due to a configuration error. Please review the creation logs, update your dev container configuration as needed, and run the "Rebuild Container" command to rectify.

Version: 1.29.3
OS: linux
OS Release: 6.5.0-1025-azure
Product: Visual Studio Code
Product Version: 1.95.3
Language: en

**Comment by joshspicer** [comment]
For issues specifically with Codespaces you'll unfortunately need to contact GitHub support directly. If you are a CS 50 student, i'd suggest contacting your professor (who can contact GitHub support on your behalf)

Have you made any changes to the files in your `.devcontainer` folder? If so, revert those back to the original contents and "rebuild".  When contacting your professors or support, you'll also want to include your [creation log](https://docs.github.com/en/codespaces/troubleshooting/github-codespaces-logs?tool=webui#creation-logs).  If you post that here, I may be able to spot a simple fix (but please do engage with your professor).

**Comment by bamurtaugh** [comment]
Closing since as Josh shared, this is an issue on the Codespaces side.

If there's anything VS Code Remote specific you'd like help with, please let us know! Thank you!

**Comment by LEdges333** [comment]
For those who encounter this problem, read the cs50 manual section https://cs50.readthedocs.io/cs50.dev/#codespaces-run-into-recovery-mode In short, you need to create a new codespace
