### ISSUE TITLE
[Remote-SSH Bug]: Remote Terminal Node Processes are not killed on exiting VS Code

### ISSUE THREAD

**Issue by yNakidori** [microsoft/vscode-remote-release#10538]
### Is there an existing issue for this bug?

- [x] I have searched the existing issues

### Required Troubleshooting Steps

- [x] I have followed these troubleshooting steps
- [x] I have tried both values of the `remote.SSH.useLocalServer` setting [(more info here)](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting#troubleshooting-steps)

### Connect Locally

It connects successfully

### ->

All Node procces keeps runnig even after exiting VS Code, already checked a lot of solutions but none of them worked - Node v23.3.0

### Expected Behavior

Is expected to VS Code kills the procces runnig after closing the program

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
> vite

Port 5173 is in use, trying another one...
Port 5174 is in use, trying another one...

  VITE v5.2.10  ready in 135 ms

  ➜  Local:   http://localhost:5175/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
```

</p>
</details>

**Comment by joshspicer** [comment]
These are projects you're starting yourself in the terminal on remote machine, correct? If you SSH directly (outside of VS Code) and then close the connection, does the same thing happen?

I wouldn't expect the behavior of the VS Code extension to be doing anything in particular to user-started processes. I'm seeing some discussion online about `vite` not being particularly easy to terminate (eg: https://github.com/vitejs/vite/discussions/12419), perhaps there's something helpful there?
