### ISSUE TITLE
Test: empty remote window shows explorer and terminal

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#1053]
Tests https://github.com/microsoft/vscode-remote-release/issues/954

- [x] ssh @weinand
- [x] wsl @deepak1556
- [x] containers @weinand

Complexity: 2

- when an empty remote window is opened (no folder, no workspace file) and the startup editor is not the welcome page, then we show the (empty) projects view and the terminal.

- change the startup editor to something else than the welcome page (setting `workbench.startupEditor`)
- open a new WSL window, attach to a container or open an ssh connection
- verify that the projects view shows, has a 'open' button and a good label
- verify that the terminal shows

**Comment by weinand** [comment]
When attaching to a container, the terminal shows up fine.
