### ISSUE TITLE
The SSH servers im connected to per project are randomly incorrect.

### ISSUE THREAD

**Issue by harryeffinpotter** [microsoft/vscode-remote-release#10537]
Type: <b>Bug</b>

For instance when I am connected to my host called NIF2, and I am in a project folder called pydrive, when looking at my recently closed connections it for some reason shows pydrive on workapi, and when I know i have mgmt_api on workapi, it shows it on NIF2, it is just randomly mixing up project and directory/project name.

Extension version: 0.87.0
Windsurf version: Windsurf 1.94.0 (d33d40f6cd3a4d7e451b22e94359230a4aa8c161, 2024-11-27T21:27:37.168Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 6.11.9-arch1-1
Remote OS version: Linux x64 6.11.9-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor             (32 x 4500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.14GB (31.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: NIF2|
|OS|Linux x64 6.11.9-arch1-1|
|CPUs|Intel(R) Xeon(R) E-2286G CPU @ 4.00GHz (12 x 0)|
|Memory (System)|21.53GB (9.89GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: workapi|
|OS|Linux x64 6.11.9-arch1-1|
|CPUs|AMD EPYC 7551P 32-Core Processor (8 x 0)|
|Memory (System)|30.57GB (24.57GB free)|
|VM|0%|
</details>

**Comment by joshspicer** [comment]
What extension are you reporting an issue for?  Are you referring to the Remote Explorer (in the sidebar)?  

I am seeing in your report references to Windsurf, which unfortunately is incompatible with VS Code's remote family of extensions.  Please try again with VS Code and let us know if that helps
