### ISSUE TITLE
Named devcontainer connects to another running container

### ISSUE THREAD

**Issue by g4brielvs** [microsoft/vscode-remote-release#10546]
When using Remote Explorer in VS Code to connect to a named devcontainer, the connection sometimes attaches to a different, unrelated running container instead of the one defined in the corresponding devcontainer.json file.

### Steps to Reproduce

1.	Create two distinct devcontainer configurations: devcontainer1.json and devcontainer2.json.
2.	Launch VS Code and ensure both containers are running.
3.	Use Remote Explorer (Dev Containers) to attach to one of the containers.
4. Observe that the connection may attach to the wrong container (a different running container).

### Expected Behavior
Each named devcontainer configuration (devcontainer1.json and devcontainer2.json) should connect to its respective running container without confusion.

### Actual Behavior
VS Code sometimes connects to a different, unintended container, leading to workflow interruptions.

### Additional information

- VSCode Version: 1.95.3
- Local OS Version: Windows 11 Enterprise 23H2
- Remote OS Version: RHEL 8.10
- Remote Extension/Connection Type: Containers

**Comment by chrmarti** [comment]
Could you share the devcontainer.json files and the folder structure they are in? Are you using an "Attach" or a "Connect" action in the Remote Explorer?
