### ISSUE TITLE
vscode remote spawn a huge amount of node process (upate to 1800 above) ?

### ISSUE THREAD

**Issue by coreyzzp** [microsoft/vscode-remote-release#10547]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:   1.94.0 (Universal)  d78a74bcdfad14d5d3b1b782f87255d802b57511
- OS Version:  macos 10.15.7 

Steps to Reproduce:

1.  use vscode remote for a few hours
2. 

```bash
#  ps aux | grep -i  node

...
root     4193488  0.0  0.0 1037840 48120 ?       Sl   12月07   0:00 /root/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813-legacy/node /tmp/vscode-remote-containers-server-d025a5db-a72f-4fc2-a6dc-a5f56939bd99.js
root     4193638  0.0  0.0 1038096 48068 ?       Sl   12月07   0:00 /root/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813-legacy/node /tmp/vscode-remote-containers-server-ff5e1dd7-6b37-4693-b621-4f31e2fa6012.js
....

#  ps aux | grep -i  node | wc -l
1816
```

**Comment by Kai-Denzel-Jane** [comment]
I have this same issue my Server with 24GB of RAM just slowly fills up and eventually crashes

Dev Container Log:

`[415 ms] Dev Containers 0.394.0 over Remote - SSH 0.116.0 in VS Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c).
[414 ms] Start: Loading environment from ExecServer
[464 ms] Host OS: linux 6.8.0-1017-oracle
[464 ms] Host CWD: /home/kai/Discord
[464 ms] Start: Run: /bin/sh 
[623 ms] Start: Run in host: echo ~
[674 ms] /home/kai
[674 ms] 
[675 ms] Start: Run in host: id -un
[727 ms] kai
[728 ms] 
[728 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'kai' || grep -E '^kai|^[^:]*:[^:]*:kai:' /etc/passwd || true)
[817 ms] userEnvProbe: loginInteractiveShell (default)
[817 ms] userEnvProbe: not found in cache
[817 ms] userEnvProbe shell: /usr/bin/zsh
[1498 ms] userEnvProbe PATHs:
Probe:     '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
Container: None
[1848 ms] Initializing configuration support...
[1848 ms] Internal initialization of dev container support package...
`

**Comment by Kai-Denzel-Jane** [comment]
> Could you append more of the log? This excerpt doesn't capture what is going on.

I can try I'm not sure how long I will need ro have it open to start logging more

**Comment by Kai-Denzel-Jane** [comment]
Hmm heres bashtop after the session being open for only like 4 minutes

![Image](https://github.com/user-attachments/assets/e6f82033-ac2a-4bbf-89e2-ad7c914e53b8)

**Comment by Kai-Denzel-Jane** [comment]
And it just keeps going up in memory usage
 and the Dev Container Log doesn't update past what I've sent

**Comment by chrmarti** [comment]
Could you check if you also see this in Dev Containers 0.390.0-pre-release and 0.391.0-pre-release?

**Comment by Kai-Denzel-Jane** [comment]
> Could you check if you also see this in Dev Containers 0.390.0-pre-release and 0.391.0-pre-release?

Ok I've tried pre-release 0.390.0 and I noticed that I don't have that many node processes running like anywhere near 1800 only like 9 or 7 at a time hover i still have this high memory usage thing so maybe my issue is unrelated?

**Comment by chrmarti** [comment]
@Kai-Denzel-Jane Could you share your devcontainer.json?

**Comment by Kai-Denzel-Jane** [comment]
> @Kai-Denzel-Jane Could you share your devcontainer.json?

Unfortunately I currently don't have access to my computer but I should be able to get back to you on this by this time tomorrow if not earlier.

**Comment by chrmarti** [comment]
@Kai-Denzel-Jane Sorry, I was mislead by the original issue being about Dev Containers. Maybe you are using Remote-Tunnels or Remote-SSH? Could you open a new issue for that?
