### ISSUE TITLE
Test: VSCode running on Alpine WSL

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#1054]
Tests https://github.com/microsoft/vscode-remote-release/issues/954

- [x] wsl @weinand
- [x] wsl @sandy081

Complexity: 3

The VSCode server now also runs on Alpine WSL

Requires WSL on Windows 10, May 2019 Update

- Install Alpine WSL from the Windows Store
- `Remote-WSL: New Window using Distro` and select Alpine
- On the first launch there will an error telling you to install a required library (`libstdc++`). Follow the instructions to install the library
- Next start all should go well

**Comment by weinand** [comment]
Works great!
BTW, to install node.js and npm on Alpine use `apk add --update nodejs npm`
