### ISSUE TITLE
"Connect in New Window" for on one running container

### ISSUE THREAD

**Issue by roachsinai** [microsoft/vscode-remote-release#10559]
There has been two closed related issue about this: #1737 #4470 

But now for me it still swith to the first window.

Is this feature supported? Thanks!

**Comment by chrmarti** [comment]
It is a bit hidden: First use a single window to attach to the container and open one and then the other folder. Now you can open a second window on the first folder from the Remote Explorer:
<img width="438" alt="Image" src="https://github.com/user-attachments/assets/d76e695e-3f79-4d32-baf1-7d2e73682545" />

**Comment by roachsinai** [comment]
Thanks!
