### ISSUE TITLE
Test SSH agent forwarding

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1055]
Testing #16

Complexity: 5

- [x] Windows @sbatten
- [x] Linux @joaomoreno 
- [x] Mac @octref

This feature lets your SSH remote access keys stored in the local SSH agent. There are a few ways that you could test this but here is a simple one that I've been using.

If you don't have a VM handy you can use [this one](https://github.com/microsoft/vscode-internalbacklog/issues/700)

First to make sure your SSH agent is set up correctly on your local machine
- In a local vscode window terminal:
- `ssh-add -l` - should list one or more keys. Add your keys using `ssh-add` if needed.

If this doesn't work, see https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent.

General troubleshooting tip, the ssh agent's socket is found using the `$SSH_AUTH_SOCK` environment variable. If you have trouble, check whether it is set to a file that exists in the local and the remote environments. And include this info with any bugs you file.

Test initial connection:

- Install the _nightly_ SSH extension and uninstall the stable one
- Have SSH auth for github configured for your account
- Have a VM that does not have its own ssh key for github
  - You can verify that this is the case by sshing into the VM and running `ssh -T git@github.com`, you should get "Permission denied"
- In your ssh config, add `ForwardAgent yes` to your config for this VM
- Set `"remote.SSH.enableAgentForwarding": true` in vscode
- Connect to this VM through vscode
- In a terminal, run `ssh -T git@github.com`, now you should get "Hi <username>! ..."

Test reconnection:

- **(optional)** Add this to your remote .bashrc ```alias rs='SSH_AUTH_SOCK=`cat $SSH_AUTH_SOCK_LOCATION`'``` and start a new session
- Trigger reconnection
- Once reconnected, running this test again in _previously existing_ terminals _should fail_, but if you create a new terminal, it should work in that terminal
- In a terminal that went through reconnection, if you configured the alias, run `rs`. After this, the ssh agent should be accessible from the terminal. If you didn't configure the alias, run ```SSH_AUTH_SOCK=`cat $SSH_AUTH_SOCK_LOCATION` ```. The point of this is to update SSH_AUTH_SOCK to the new tunnel that was established during reconnection.

Note - the reconnection user experience is not great right now since the user must often manually update the SSH_AUTH_SOCK variable in existing terminals. But we will be able to do a better job when we use dynamic port forwarding. That is also just an experiment this month.

**Comment by weinand** [comment]
@roblourens `ssh-add -l` does not list any keys (because linux is not my normal environment and I'm using a more-or-less clean Parallels ubuntu VM).

What keys should I add by using `ssh-add`?

**Comment by sbatten** [comment]
not working in windows for me

$`SSH_AUTH_SOCK` on remote
![image](https://user-images.githubusercontent.com/6561887/62153989-a39ac080-b2ba-11e9-9909-8d412605b253.png)

key in ssh-agent:
![image](https://user-images.githubusercontent.com/6561887/62154053-cc22ba80-b2ba-11e9-878a-952bbb5a22b8.png)

setting enabled:
![image](https://user-images.githubusercontent.com/6561887/62154080-dcd33080-b2ba-11e9-8d60-5844b176f8f7.png)

ssh config
```
Host az-vm-vscode-4
   HostName az-vm-vscode-4.westus2.cloudapp.azure.com
   User sbatten
   IdentityFile C:\Users\stbatt\.ssh\id_rsa
   ForwardAgent yes
   Port 22
	 LocalForward 5901 localhost:5901
```

**Comment by octref** [comment]
> Once reconnected, running this test again in previously existing terminals should fail,

After reconnection, I'm still able to connect to git@github.com
My `$SSH_AUTH_SOCK` is properly set on remote. And with `ssh-add -l` I see the same output as my local ssh fingerprints.

**Comment by roblourens** [comment]
@weinand You will have to add an ssh key that is authorized for github. If you don't want to do that you can also test that you can access some other machine using that key, or even just test that it's returned by `ssh-add -l` and don't add it anywhere.

@sbatten was that after reconnection? And does it work from a local vscode window?

@octref sometimes when reconnection happens, the old connection doesn't die, and in that case, it will automatically work after reconnection. That just means you got lucky.

**Comment by weinand** [comment]
After discussion in the Standup we have moved the linux assignment to @joaomoreno because he has actually the problem that was fixed through this work.

**Comment by joaomoreno** [comment]
The first set of steps worked great.

But now I don't understand what you mean by _test reconnection_. I have paused the VM I'm connected to, saw the connection dropping, resumed the VM, resumed the connection and everything still works... is that it? I guess not since I can still run `ssh -T git@github.com` on the same terminal and it works.

I also don't understand what this means or why I would do it... so I haven't done it since reconnection just worked:

> Add this to your remote .bashrc alias rs='SSH_AUTH_SOCK=`cat $SSH_AUTH_SOCK_LOCATION`' and start a new session

**Comment by roblourens** [comment]
It sounds like you saw the same thing that @octref did

> sometimes when reconnection happens, the old connection doesn't die, and in that case, it will automatically work after reconnection. That just means you got lucky.

**Comment by sbatten** [comment]
@roblourens I tested reconnection and now all SSH commands hang in any terminal, other commands work without issue

**Comment by roblourens** [comment]
We found that reconnection actually doesn't work right after all and it will be fixed in tomorrow's insiders 😬
