### ISSUE TITLE
Proposed API is only available when running out of dev or with the following command line switch

### ISSUE THREAD

**Issue by kpolley** [microsoft/vscode-remote-release#1056]
Issue Type: <b>Bug</b>

Unable to use remote SSH feature on any of my machines. When I click on the Remote-SSH icon on the left-side panel I receive the error: 

_[ms-vscode-remote.remote-ssh-explorer]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-vscode-remote.remote-ssh-explorer_

When I run code via `code --enable-proposed-api ms-vscode-remote.remote-ssh-explorer` I am able to see the list of available machines, but when attempting to connect I receive the error: 

_Failed to connect to the remote extension host server (Error: Connection error: Version mismatch, client refused.)_. 

(Not sure if the mismatch error is related to the first error message, but these are the two issues I've faced)

Extension version: 0.44.2
VS Code version: Code - OSS 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-22T07:38:21.043Z)
OS version: Linux x64 5.2.2-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.67GB (4.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
You are using Code-OSS, the remote extensions are only supported with the official build of vscode.
