### ISSUE TITLE
Copilot not working in Remote windows

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#10578]
_This is a duplicate issue to https://github.com/microsoft/vscode-copilot-release/issues/3375 for information purposes only._

When using Copilot in with DevContainer, SSH, or WSL you will encounter that the Copilot Chat window is stuck in the setup state. The recording below shows the error state as well as a temporary workaround.

The error state is that the Chat window displays a button to suggests to you to "Use Copilot" or "Use Copilot for Free". When clicking the button, supposedly nothing happens.

The workaround:
1) Go to the extension management view
2) Disable the Copilot Chat extension **on the remote**
3) Reload the window
4) In the extension management view, enable the Copilot Chat extension **on the remote**

The workaround is necessary for each remote window. 

We're working on a fix.

![Image](https://github.com/user-attachments/assets/55d45a17-e6fa-4f41-9532-62e535caaa7b)

This issues was first reported as https://github.com/microsoft/vscode-copilot-release/issues/3366.

**Comment by kieferrm** [comment]
A fix will be release in the next official Insiders build, followed by a recovery build for Stable.

**Comment by joyceerhl** [comment]
This should be fixed in the 1.96.2 release.
