### ISSUE TITLE
Test dynamic port forwarding

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1057]
Testing #642

Complexity: 3

- [x] Linux @deepak1556
- [x] Mac @isidorn
- [x] Windows @Tyriar

Dynamic port forwarding lets us set up a port tunnel over an existing SSH connection rather than having to set up a new SSH process for each forwarded port. This means that you only have to type your password once in a new window.

If you don't have a VM with password auth, you can use [this one](https://github.com/microsoft/vscode-internalbacklog/issues/700)

- Install the _nightly_ SSH extension and uninstall the stable one
- Set `"remote.SSH.enableDynamicForwarding": true`
- Connect to your VM
- The password prompt should appear and only appear once
- Test the "Forward port from active host" command - you should be able to forward another port from the host and the password prompt should not appear
- Test that reconnection works. You should have to enter your password once during reconnection.

Include the full log from the Remote-SSH output channel with any issue you file.

**Comment by Tyriar** [comment]
Very cool 🙂

**Comment by deepak1556** [comment]
Was finding that multiple labels forwarding the same port weren't working as expected, but seems like it was fixed with today's update. Really cool feature overall 👍
