### ISSUE TITLE
No PTY requested

### ISSUE THREAD

**Issue by caijq4ever** [microsoft/vscode-remote-release#1058]
Issue Type: <b>Bug</b>

It can connect to local virtual machine, cannot connect to jump server.
ssh config:
```
Host Virtual
    HostName 192.168.52.129
    User xxx
    IdentityFile ~/.ssh/id_rsa
Host Jumpserver
    HostName 10.20.18.30
    Port 5520
    User xxx
    IdentityFile ~/.ssh/jumpserver
```

VSC output:
```
remote-ssh@0.44.2
win32 x64
SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a224a756d70736572766572227d", attempt 1
SSH Resolver called for host: Jumpserver
Setting up SSH remote "Jumpserver"
Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4
Running script with connection command: "ssh"  -o ClearAllForwardings=true    "Jumpserver" bash
Install and start server if needed
> 
> No PTY requested.
> 
"install" terminal command done
Received install output: No PTY requested.
Failed to parse remote port from server output: No PTY requested.
```

Extension version: 0.44.2
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134
Fetching remote diagnostics for 'SSH' failed.
Fetching remote diagnostics for 'SSH' failed.

**Comment by roblourens** [comment]
What happens if you run `ssh Jumpserver bash` in a terminal?

**Comment by caijq4ever** [comment]
![image](https://user-images.githubusercontent.com/5621857/62339497-c9200800-b50e-11e9-99ba-27ae61e8fdfc.png)

**Comment by roblourens** [comment]
You will have to set up the ProxyCommand or ProxyJump options in your ssh config file so that a command like `ssh host bash` works. https://code.visualstudio.com/docs/remote/troubleshooting#_troubleshooting-hanging-or-failing-connections
