### ISSUE TITLE
Unclear wording when recommending ws

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-remote-release#1059]
re https://github.com/microsoft/vscode-internalbacklog/issues/699

I think the wording here is weird and doesn't do a good job at selling the extension. How about "Install the 'Remote WSL' extension for a better develop experience of Window Subsystem..."

<img width="495" alt="Screenshot 2019-07-30 at 10 53 53" src="https://user-images.githubusercontent.com/1794099/62116781-0db36580-b2bb-11e9-9f32-984b6f655e34.png">

**Comment by gregvanl** [comment]
I don't mind the current text and like that it explains why the extension is recommended.
The extension name should be 'Remote - WSL'.
