### ISSUE TITLE
Improve discoverability of 'Install Local Extension...'

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#1066]
Testing #1049

Currently the action is provided in the '...' menu of the extensions viewlet (which is an advanced location) and in the Command Palette. It isn't well discoverable in both locations.

One idea would be to show a link 'Install Local Extensions' as the first item in the list of locally installed extensions

![image](https://user-images.githubusercontent.com/172399/62134867-89280d80-b2e1-11e9-8aa5-b2211a66374d.png)

**Comment by sbatten** [comment]
or an action on the Local - Installed title bar like in Debug viewlet:
![image](https://user-images.githubusercontent.com/6561887/62155026-cd54e700-b2bc-11e9-876a-0ecd47e3e4f7.png)

**Comment by Chuxel** [comment]
@sandy081 @egamma I know this is tagged as a feature request, but right now the feature is pretty hidden unless you look at docs - Remote isn't even in the command name (so typing "Remote" doesn't show it). #1068 proposed some potentially lower impact versions of this - I don't think we can call some level of this backlog given how hard it is to find if you don't know its there.  Should we perhaps re-open #1068 for low impact changes and backlog this?

**Comment by sandy081** [comment]
@Chuxel 

> but right now the feature is pretty hidden unless you look at docs.

I do not think so as this is available in extensions view secondary actions in addition to command pallete

![image](https://user-images.githubusercontent.com/10746682/61752470-13d1af80-adac-11e9-8cdd-9023e95747fc.png)

> Remote in the command name (so typing "Remote" in the command palette doesn't show it)

How about moving the command from `Extensions` category to `Remote`.

**Comment by Chuxel** [comment]
@sandy081

> How about moving the command from Extensions category to Remote ?

Yeah that makes sense - it was one of the suggestions in the other bug.  The other one was then to add it to the scoped command palette (clicking on the status bar item in the lower left) like we did with Close Remote Connection.

**Comment by egamma** [comment]
>I do not think so as this is available in extensions view secondary actions in addition to command pallete

Honestly, the '...' menu in the extensions viewlet is advanced and doesn't really help with regard to discoverability.

**Comment by sandy081** [comment]
Changed the category to `remote`. I am not in favour of moving to remote window connection actions as this action is specific to extensions and remote window connection actions are global and resolver specific actions.

`...` menu actions contain secondary actions, if we want this to be prominent then we can move this to primary actions in the title area of the viewlet or in the title area of the view.

<img width="549" alt="Screenshot 2019-08-01 at 10 24 10" src="https://user-images.githubusercontent.com/10746682/62266628-a0344000-b446-11e9-99ff-d12179647d98.png">

<img width="442" alt="Screenshot 2019-08-01 at 10 28 31" src="https://user-images.githubusercontent.com/10746682/62266758-31a3b200-b447-11e9-88fc-573d87989b1b.png">

I would go with the action on the view title (above).

@misolori Please provide an icon for this action.

Let me know if we want this to be done for July or August?

**Comment by Chuxel** [comment]
@sandy081 To be clear, I'm not suggesting we move, but rather add.  The scoped command palette is intended to show all available commands specific to the remote context.  It's not about the remote extensions, it's about the context the current window is in. This is why common cross-extension features line "Close Connection" are also present in the menu.  From a UX perspective, it's intended to increase awareness of remote features and provide a one-stop-shop for common remote commands.

With this in mind, I understand that from an implementation perspective that this command is related to extensions, but from a user perspective, allowing people to see all remote context commands is quite useful.

**Comment by sandy081** [comment]
As a user is not it more natural to go to extensions view to install extensions either in local or in remote? If so this action fits better in extensions view and showing it in the remote context menu might be redundant IMO. I also think having this action in remote context menu makes it overloaded and it will become a command pallette for all remote actions.

**Comment by Chuxel** [comment]
> I also think having this action in remote context menu makes it overloaded and it will become a command pallette for all remote actions.

@sandy081 Indeed, that is what it is - it's literally a "scoped command palette".  The only ones we wouldn't put here are those we don't think most people will want or need. There's just a couple not present.  As I mentioned, this is not an "or" thing in my view, it's an and.

**Comment by misolori** [comment]
If we do decide to use an icon here, I think re-using the same icon makes sense.

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/62978123-cf708700-be20-11e9-8627-d27667b2fb0d.png)
