### ISSUE TITLE
Polish `Extensions: Install Local extensions on` command

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-remote-release#1067]
Testing #1049

Should this command be `Extensions: Install Local extensions on WSL: Ubuntu...` instead, with an ellipsis?

---

The completion of the command has strange phrasing:

![image](https://user-images.githubusercontent.com/22350/62133621-5e3cba00-b2df-11e9-88ab-728e8a0673b1.png)

Should it rather be:

> Successfully installed 2 extensions in WSL: Ubuntu. Reload the window to activate them.

**Comment by sandy081** [comment]
Changed the completion message to following. 

![image](https://user-images.githubusercontent.com/10746682/62320217-4884eb80-b4bd-11e9-91c9-370565be1d2f.png)

**Comment by joaomoreno** [comment]
@sandy081 There's a typo in the button, just noticed now!
