### ISSUE TITLE
Install Local Extensions command should appear in the quick action menu

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#1068]
Testing #1049 

To aid discoverability, I'd suggest that the "Install Local Extensions" command should appear in the quick action menu when you click on the status bar item in the lower left.  I didn't know the exact command name, so this was the first thing I did when looking for it.  We did the same thing with "Close Remote Connection".

I'd also suggest we may want to have a category of "Remote" instead of extensions since typing "Remote" in the command palette does not show the command... which is another reason I didn't find it at first.

![image](https://user-images.githubusercontent.com/312252/62136444-fb283480-b298-11e9-999d-169c7b5ed586.png)

**Comment by egamma** [comment]
See also #1066
