### ISSUE TITLE
"Remote Containers: Reopen Folder in Container" should annotate which project a Dockerfile / docker-compose.yml file is from in a workspace

### ISSUE THREAD

**Issue by jonfen** [microsoft/vscode-remote-release#1071]
Given a workspace with several projects/repos, each containing a "Dockerfile", opening a single Dockerfile the tab shows like: 

![image](https://user-images.githubusercontent.com/56961/62139875-447f8080-b2a7-11e9-9b28-87671f0361a0.png)

When opening up a file with the same name from a different project in the workspace, the tabs annotate the project it is from:

![image](https://user-images.githubusercontent.com/56961/62139773-231e9480-b2a7-11e9-875a-df05604054e3.png)

This annotation should happen when using "Remote Containers: Reopen Folder in Container" as well, this is the current behavior:

![image](https://user-images.githubusercontent.com/56961/62139999-755fb580-b2a7-11e9-9817-44027b19d121.png)

**Comment by alexr00** [comment]
I'm seeing the "Reopen in Container" command not do anything when I run it in a workspace with multiple dockerfiles.
Steps:
Clone the vscode-dev-containers repo.
Open the azure-ansible folder
Add Folder to workspace -> azure-functions-node-lts
Add Folder to Workspace -> swift-4
Reopen in Container

Nothing seems to happen.

**Comment by chrmarti** [comment]
Moving that to a new issue. Thanks.

**Comment by alexr00** [comment]
What are the steps for verifying this?

**Comment by alexr00** [comment]
I did that and I was able to connect to the container, but my folders aren't there:
![image](https://user-images.githubusercontent.com/38270282/66198596-0898db00-e69d-11e9-9d5a-8cc6ede7883e.png)
Expected?

**Comment by chrmarti** [comment]
@alexr00 Not expected, could you open a new issue for that?

The change here is to qualify the Dockerfile and docker-compose.yml filenames with the workspace folder name in the QuickPick you get when you first 'reopen in container'. I wasn't precise in my steps above. The qualification only shows when there is more than one workspace folder.

**Comment by alexr00** [comment]
Qualification works great.
