### ISSUE TITLE
Provide more devcontainer.json guidance when reusing an existing Docker Compose / Dockerfile

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#1076]
Currently reusing an existing Dockerfile results in a very minimal devcontainer.json with no real guidance on what to do next:

```text
{
    // See https://aka.ms/vscode-remote/devcontainer.json for format details.
    "dockerFile": "Dockerfile",
    "extensions": []
}
```

Docker Compose is similar.  When you pick a pre-defined dev container definition, we provide quite a bit more context setting for common scenarios and use cases customers may face.

For example:

```text
{
	// See https://aka.ms/vscode-remote/devcontainer.json for format details.
	"name": "Existing Dockerfile",

	"dockerFile": "Dockerfile",

	// Uncomment the next line if you want to publish any ports.
	// "appPort": [],

	// The optional 'runArgs' property can be used to specify additional runtime arguments.
	"runArgs": [
		// Uncomment the next line if you will be using a ptrace-based debugger like C++, Go, and Rust.
		// "--cap-add=SYS_PTRACE", "--security-opt", "seccomp=unconfined"

		// The "-u" flag allows you to use a non-root user if available. See https://aka.ms/vscode-remote/containers/non-root-user.
		// "-u", "1000"
	],
	
	// Uncomment the next line if you want to add in default container specific settings.json values
	// "settings":  { "workbench.colorTheme": "Quiet Light" },

	// Uncomment the next line to run commands after the container is created - for example installing git.
	// "postCreateCommand": "apt-get update && apt-get install -y git",

	// Add the IDs of any extensions you want installed in the array below.
	"extensions": []
}
```

Ideally we'd just reuse these two dev container definitions:
1. Existing Dockerfile
2. Existing Docker Compose

This will requite some reworking of how the extension generates the JSON (currently it creates an object which drops the comments), so there's a bit more to it than just updating content.

**Comment by chrmarti** [comment]
@Chuxel I have started using your definitions for existing Dockerfiles / docker-compose.ymls and update the paths and the service name in the devcontainer.json accordingly.

What's missing is I also need to update the service name in the development docker-compose.yml that you include. But before getting all the details right I first want to check with you, do you agree with the approach?

**Comment by Chuxel** [comment]
@chrmarti Yep, that makes sense.  Also makes it easy for people to contribute to it if they don't like our defaults.

I can also take another look and double check that we have good defaults in the definition.

**Comment by chrmarti** [comment]
@Chuxel Editing the YAML without losing any formatting is tricky. I now parse the second docker-compose.yml, look up the first service's name and then run a regular expression replacing that name in the entire YAML text. That will work fine as long as that name is sufficiently distinct and does not contain regex special characters. Hope that's robust enough.
