### ISSUE TITLE
Reconnect modal blocks inputting password on reconnection

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-remote-release#1079]
#1057

![image](https://user-images.githubusercontent.com/2193314/62175108-348c8e80-b2f1-11e9-8958-ffde1ddc34f1.png)

**Comment by roblourens** [comment]
I can't repro it and I don't even know why there would be a command prompt there. Can you include the log or the contents of the terminal?

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/1072
