### ISSUE TITLE
127.0.0.1:port should be mapped as well as localhost:port in WebView

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode-remote-release#108]
- 1.34.0-insider (1.34.0-insider) 473af338e1bd9ad4d9853933da1cd9d5d9e07dc9
- macOS High Sierra 10.13.6（17G6030）
- Remote Development 0.12.0

With [Remote - SSH](https://code.visualstudio.com/docs/remote/ssh) scenario,  `127.0.0.1:port` in WebView is not mapped. It should be mapped as well as `localhost:port`.

I want to avoid using `localhost` because it might be misconfigured by users editing `/etc/hosts`.

**Comment by DanTup** [comment]
Not only can it be reconfigured, but sometimes a process will bind to `localhost` as 127.0.0.1 and then sometimes a connecting process will get `::1` (IPv6), and the connection fails. Not supporting this blocks several Dart/Flutter tools that all use IP addresses to avoid this :(

**Comment by DanTup** [comment]
@mjbvz does this fix cover openExternal too? The commit looks like webviews, but my issue that was closed as a dupe is for `openExternal` (I'm opening my own browser, there are no webviews):

https://github.com/microsoft/vscode/issues/74105

**Comment by jrieken** [comment]
verified via review

**Comment by DanTup** [comment]
Tested this with my extension in Insiders, and it worked - my page spawned with openExternal() that used 127.0.0.1 was mapped successfully. Thanks!
