### ISSUE TITLE
Command Open Folder in Container missing in Insiders build

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-remote-release#1083]
- VSCode Version:  1.37.0-insider
- Commit: d5900c642b359fe7a9eb1e3f9e2d0977f6e0905c
- Remote Extension/Connection Type: Docker

When testing https://github.com/microsoft/vscode-remote-release/issues/1049

**Stable:**

<img width="1027" alt="Screen Shot 2019-07-31 at 2 28 34 PM" src="https://user-images.githubusercontent.com/964386/62250018-acfe5880-b3a0-11e9-9d4e-2846878d0e27.png">

**Insiders:**

<img width="1187" alt="Screen Shot 2019-07-31 at 2 37 48 PM" src="https://user-images.githubusercontent.com/964386/62250056-cef7db00-b3a0-11e9-96bf-355fa4c88a45.png">

**Comment by Chuxel** [comment]
Still repros on:

Version: 1.37.0-insider (user setup)
Commit: 5e08ee01b7daee99cdda2456f19d77e715fb8762
Date: 2019-08-05T21:18:05.921Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

This happens in a new window - so this is an important one to fix.

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode-remote-release/issues/1074.

Make sure you have the latest version of remote containers installed.
