### ISSUE TITLE
Ability to launch .devcontainer project from command line

### ISSUE THREAD

**Issue by bmweller** [microsoft/vscode-remote-release#1084]
As designed VSCode launches a project containing a .devcontainer it starts in local mode promoting to reopen in a container.

"Folder contains a dev container configuration file. Reopen folder to develop in a container ([learn more](https://aka.ms/vscode-remote/docker))."

I would like to have an option added to the command line to allow the dev container to be opened by default for example:

 code-insider . --dev-container or
 code-insider . --mode=dev-container
when this extension is enabled.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/585
