### ISSUE TITLE
Sometimes the vscode  server process doesn't close on remote end

### ISSUE THREAD

**Issue by goldenarrow381** [microsoft/vscode-remote-release#1086]
Sometimes the 'vscode-server' process doesn't close on remote end after vscode is closed on client side. And the process goes zombie, preventing vscode from logging in again. I have to manually kill the process to login from vscode again.

**Comment by roblourens** [comment]
The server process shouldn't end immediately. If vscode shuts down cleanly and the remote extension host goes down, then the server should go down 10 minutes later. But this

> preventing vscode from logging in again

is unexpected. Can you explain more about what you are seeing? The Remote-SSH output channel log from the failed attempt to connect would be helpful.

**Comment by liujshi** [comment]
same problem 
remote ssh could not establish connection to
when kill this process, connection can be established

**Comment by roblourens** [comment]
Still need more info
