### ISSUE TITLE
Conflict with WSL extension connection and Github Desktop

### ISSUE THREAD

**Issue by TulioAbreu** [microsoft/vscode-remote-release#1088]
Issue Type: <b>Bug</b>

1. Use WSL extension.
2. Use Github Desktop for Windows.
3. Make some changes in project files.
4. Try to commit the changes

When you try to commit changes while connected to WSL instance in VSCode you can't make a commit in Github Desktop, it appears the error:

"fatal: Could not write new index file."

When i close the VSCode or stop the connection with WSL I can make commits normally

Extension version: 0.38.10
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2197)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.90GB (1.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2197)|
|Memory (System)|5.90GB (1.46GB free)|
|VM|0%|
</details>

**Comment by Plasmoxy** [comment]
Has this been resolved yet? I have the same issue.

**Comment by aeschli** [comment]
I asume the git repo is located in a folder that is both visible from WSL and Windows (e.g. /mnt/c/..)

Running Windows and Linux Git on the same folder is not unproblematic. I'd recommend you to use an unshared folder (e.g. /home/you/..).

The locking issue that you are seeing is a known WSL1 issue: Switching to polling should fix the issue:
https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace
I gave this a quick try and didn't see the locking issue.
