### ISSUE TITLE
Install Remote WSL fail with mv - permission denied

### ISSUE THREAD

**Issue by ntcong** [microsoft/vscode-remote-release#109]
- VSCode Version: 1.34.0-insidier
- OS Version: WSL Ubuntu 18.04.2

Steps to Reproduce:

1. Install Remote - WSL
2. WSL - New Window
```
[2019-05-04 03:23:02.480] mv: cannot move '/home/<>/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9-1556940174' to '/home/<>/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9': Permission denied
```

I think it's related to https://github.com/Microsoft/WSL/issues/1529, I got Permission denied when mv folder but not when I cp-ed it.

I changed the script `ms-vscode-remote.remote-wsl-0.32.0\scripts\wslDownload.sh` from mv to cp -r and it works
```
	for i in 1 2 3 4 5; do
		cp -r "$VSCODE_REMOTE_BIN/$TMP_NAME" "$VSCODE_REMOTE_BIN/$COMMIT" && break || sleep 2;
		rm -rf "$VSCODE_REMOTE_BIN/$TMP_NAME"
	done
```

**Comment by aeschli** [comment]
The mv works for me (and others), so I wonder what could have caused this.
What version of windows is it?
Are there any watchers running on the home folder on the linux side or do you have a windows file explorer open on the home folder?
Did you delete the install by hand and reinstalled it, but still have processes running on the old install?

**Comment by ntcong** [comment]
It's a long-running issue so I'm not sure it would be good if we discuss it here. I'm running latest Windows 10 with latest updates, Ubuntu 18.04.2. `mv` command will not good even when I create a completely new folder, no watchers or explorer open (it's a folder under / so Windows can't access).

modifying `wslDownload.sh` is enough to get the remote agent installed. The only minor issue when installing an extension (which also uses mv) which I also fix by change rename -> copy in `out/vs/agent/remoteExtensionHostAgent.js`

**Comment by aeschli** [comment]
I added a cp in case mv failes after 5 tries.
