### ISSUE TITLE
Soft link cannot be seen in explorer

### ISSUE THREAD

**Issue by derekxia1988** [microsoft/vscode-remote-release#1090]
Issue Type: <b>Bug</b>

As the title...

Extension version: 0.38.10
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18950
Remote OS version: Linux x64 4.19.57-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (2.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-16.04|
|OS|Linux x64 4.19.57-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3192)|
|Memory (System)|14.57GB (0.67GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment]
Can you confirm that you have created a soft link in the remote machine and then this link is not rendered in the explorer?

Does the same scenario work locally?

**Comment by derekxia1988** [comment]
![image](https://user-images.githubusercontent.com/28382254/62405892-f2579b80-b5d5-11e9-99b7-59ff9fb8aea1.png)
As the screen shot shows, the soft link cannot be seen in the explorer side bar.Because my local OS is Windows10,so I havenot test for in linux like ubuntu desktop.

**Comment by derekxia1988** [comment]
> Can you confirm that you have created a soft link in the remote machine and then this link is not rendered in the explorer?
> 
> Does the same scenario work locally?

forget to get you noticed
