### ISSUE TITLE
Remote - Containers fails to build an image if an "_" is in the local folder name

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#1093]
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.18.0-25-generic

Also seen on Windows.

If you have a folder with an "_" in it, the dev container will fail to build with an invalid tag error.  We should filter these out of the tag name.

Repro:
1. Create a folder called "_test"
2. Run **Open Folder in Container...** and select any pre-configured definition (I used Debian)
3. Let VS Code try to open the folder

Expected: Folder opens
Actual: Image build fails due to "invalid reference format" due to the use of the folder name with the "_" in the tag added to the container.

Full log showing problem:
```
Setting up container for folder: /home/clantz/Repos/_microsoft
Run: docker build -f /home/clantz/Repos/_microsoft/.devcontainer/Dockerfile -t vsc-_microsoft-c157c1e94218b42decde65402efda214 /home/clantz/Repos/_microsoft/.devcontainer
invalid argument "vsc-_microsoft-c157c1e94218b42decde65402efda214" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
Failed: Building an image from the Dockerfile.
Command failed: docker build -f /home/clantz/Repos/_microsoft/.devcontainer/Dockerfile -t vsc-_microsoft-c157c1e94218b42decde65402efda214 /home/clantz/Repos/_microsoft/.devcontainer
```

**Comment by leshow** [comment]
I've just run into this also
