### ISSUE TITLE
Remote - Containers : No HTML or RAZOR Intellisense in .cshtml file for Dotnet MVC project

### ISSUE THREAD

**Issue by HoTKreeZy** [microsoft/vscode-remote-release#1096]
- VSCode Version: 1.36.1
- Local OS Version: macOs Mojave v10.14.6
- Remote OS Version: Linux debian 9
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Create a folder on my local machine that will contains my project
2. Open this folder inside vs code
3. Use the remote extension : 
    - Add Development Configuration file : `C# (.NET Core Latest)`( mcr.microsoft.com/dotnet/core/sdk:latest )
    - Reopen folder in container
4. Create project inside the container : dotnet new mvc
5. Open any CS file and wait for Omnisharp installation
6. Open any CSHTML file and try to write some html but got no intellisense for both html or razor syntax

Does this issue occur when you try this locally?: Didn't try locally
Does this issue occur when you try this locally and all extensions are disabled?: Didn't try locally

I created a public repo with the full project to run in a remote container with the extension  : https://github.com/HoTKreeZy/TryAspCore

**Comment by egamma** [comment]
@HoTKreeZy can you please report the issue against https://github.com/OmniSharp/omnisharp-vscode/issues
