### ISSUE TITLE
command 'remote-containers.openFolder' not found

### ISSUE THREAD

**Issue by cleversonahum** [microsoft/vscode-remote-release#1097]
I have installed the extension 'Remote - Containers', when I try to run the command 'Open folder in Container' it replies with the error `command 'remote-containers.openFolder' not found`. I have tried to reinstall and clean the packages from `.vscode/extensions` and install again without success.

Extension version: 0.66.0
VS Code version: Code - OSS 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-22T07:38:21.043Z)
OS version: Linux x64 5.2.5-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.67GB (4.16GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by cleversonahum** [comment]
Using the Toggle Developer Tools console, I found the following error:
```
Activating extension 'ms-vscode-remote.remote-containers' failed: [ms-vscode-remote.remote-containers]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-vscode-remote.remote-containers.
```

**Comment by egamma** [comment]
>VS Code version: **Code - OSS 1.36.1** (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-

It looks like you try to use the remote extensions with the OSS version of VS Code? Can you reproduce the behaviour when you use the published VS Code stable version.

**Comment by jrobsonchase** [comment]
Looks like this is an issue with Arch's OSS build.

[Arch bug report](https://bugs.archlinux.org/task/63374)

**Comment by cleversonahum** [comment]
It worked using VS Code @egamma . It is a bug with the OSS code as @jrobsonchase said. Thx
