### ISSUE TITLE
 I want to log with ssh-remote

### ISSUE THREAD

**Issue by soma-yoshida** [microsoft/vscode-remote-release#1099]
I would like to develop using ssh-remote, but
I have to log the terminal.
I configured the shell to work after logging in with the script command added to Force command of / etc / ssh / sshd_config to log the terminal.
Installation of ssh-remote code-server fails.
I want to get the terminal log when I connect to the server with ssh-remote. Is there any better way?

**Comment by roblourens** [comment]
> I have to log the terminal.

Sorry I don't understand what you mean by this. Can you explain some more?

**Comment by soma-yoshida** [comment]
What I want to do is to run the login script when accessing vm with remote-ssh from vscode.
I want to execute the script command in the login script.

**Comment by roblourens** [comment]
Oh ok, https://github.com/microsoft/vscode-remote-release/issues/141

**Comment by soma-yoshida** [comment]
Excuse me.
Instead of reflecting the environment, we want to execute the command.
I received that this is not the answer, is it wrong?

**Comment by soma-yoshida** [comment]
Excuse me.
Instead of reflecting the environment, we want to execute the command.
I received that this is not the answer, is it wrong?
