### ISSUE TITLE
Extension packs are not installed on correct location

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-release#11]
- Open a remote window
- Look for an extension pack that has workspace extensions. Eg: PHP Extension Pack
🐛 It shows a button install locally
Expected to show Install on remote

![image](https://user-images.githubusercontent.com/10746682/57077503-828ef780-6cec-11e9-89fb-8c6d2b2458cd.png)

🐛 Clicking on Install, installs PHP extensions locally.
Expected to install remotely

**Comment by sandy081** [comment]
An extension pack is an extension that comprises of multiple other extensions. Included extension can be any extension (pack or ui or workspace). So it means an extension pack can be

- Workspace pack that comprises of all Workspace extensions
- UI pack that comprises of all UI extensions
- Hybrid pack that comprises of Workspace and UI extensions

When an extension pack is installed, included extensions should be installed at the appropriate location. Following is my proposal:

An extension pack is considered as workspace extension kind unless specified by the extension. 

A workspace extension pack is installed on the remote and if it includes any UI extensions, then they will be installed locally. When a workspace extension pack comprises UI extensions, then user will be notified that installing such a pack also installs some extensions locally.

A UI extension pack is always installed locally and there will be no special treatment.

**Comment by sandy081** [comment]
@alexandrudima FYI

**Comment by alexandrudima** [comment]
@sandy081 I think this makes sense, but I am concerned about our `isUIExtension` implementation. The definition you propose would make `isUIExtension` no longer work on a single `package.json`. i.e. by looking at the `package.json` of an extension pack it would no longer be possible to determine where it should execute...

**Comment by sandy081** [comment]
> An extension pack is considered as workspace extension kind unless specified by the extension.

@alexandrudima Its `isUIExtension` that determines above. So it still holds the logic to determine whether an extension is ui extension or not.
