### ISSUE TITLE
able to connect to the server with command prompt but confirming takes forever to connect on VSCode

### ISSUE THREAD

**Issue by tingli-shen** [microsoft/vscode-remote-release#110]
- VSCode Version: 1.34.0-insider (user setup)
- Local OS Version: Windows 10, 1803
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

I can connect to my server with ssh on command prompt but confirming takes forever to connect on VSCode. I guess it's because VSCode does not have my password of the server to connect to the server. How do I set it up at the config file of VSCode?
<img width="478" alt="Captsure" src="https://user-images.githubusercontent.com/9148912/57173407-7fcff780-6dfd-11e9-8cbe-852d98a4ac91.PNG">

**Comment by GenkunAbe** [comment]
add `"remote.SSH.showLoginTerminal": true` to `settings.json`.

see: [Enabling alternate SSH authentication methods](https://code.visualstudio.com/docs/remote/troubleshooting#_enabling-alternate-ssh-authentication-methods)

**Comment by tingli-shen** [comment]
> add `"remote.SSH.showLoginTerminal": true` to `settings.json`.
> 
> see: [Enabling alternate SSH authentication methods](https://code.visualstudio.com/docs/remote/troubleshooting#_enabling-alternate-ssh-authentication-methods)

Thank you very much! It worked
