### ISSUE TITLE
Keeps losing connection to the sever

### ISSUE THREAD

**Issue by SteveALee** [microsoft/vscode-remote-release#1100]
Issue Type: <b>Bug</b>

Every few minutes I get a message saying it is trying to re connect. I have to close the connection and start code again. Very frustrating especially as cant save work. I'm just editing a mark down file and not even saving. So the code remote sever can't be doing much!

Can see no errors or log.

Extension version: 0.38.10
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18950
Remote OS version: Linux x64 4.19.57-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.57-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2207)|
|Memory (System)|14.58GB (13.68GB free)|
|VM|0%|
</details>

**Comment by SteveALee** [comment]
I removed Spell Right extension which was not working anyway and the problem has gone away.

Am leaving this open for your attention but please do close.

**Comment by roblourens** [comment]
This is https://github.com/bartosz-antosik/vscode-spellright/issues/279
