### ISSUE TITLE
Git panel missing operator icons

### ISSUE THREAD

**Issue by SteveALee** [microsoft/vscode-remote-release#1102]
Issue Type: <b>Bug</b>

While the menus work fine when viewing the git panel the icons are missing (eg stage, commit). I made sure to set name and email on git in UBuntu. Is more needed?

Extension version: 0.38.10
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18950
Remote OS version: Linux x64 4.19.57-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.57-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2207)|
|Memory (System)|14.58GB (13.77GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/687
