### ISSUE TITLE
Save All doesn't work

### ISSUE THREAD

**Issue by SteveALee** [microsoft/vscode-remote-release#1103]
Issue Type: <b>Bug</b>

Alt+F,A does not save files. Alt+F,S does work however.

Extension version: 0.38.10
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18950
Remote OS version: Linux x64 4.19.57-microsoft-standard

**Comment by roblourens** [comment]
Are you saying that the keyboard shortcut doesn't work, or the command itself doesn't work? What if you click the menu item?

**Comment by SteveALee** [comment]
I did not try the command - will do.
It's not actually a shortcut but the menut item mnemonic that is failing to do anything

**Comment by SteveALee** [comment]
Ah got it - The new menu item 'Close Remote Connection' has the same mnemonic so it clashes. It will work if you hit enter after l.

But that's a pain - can a non clashing mnemonic be chosen?

**Comment by sbatten** [comment]
updated to use m in remote
