### ISSUE TITLE
allow install and config vscode-server manually

### ISSUE THREAD

**Issue by youyongsong** [microsoft/vscode-remote-release#1105]
I hope vscode could release vscode-server as an application to major registries(like npm, apt), and allow us use vscode-server cli to install extensions and config settings, then allow us set vscode-server url in vscode editor.
This will give us more flexibility, and we can maintain vscode extensions and settings in Dockerfile.

**Comment by roblourens** [comment]
You can set extensions to be installed in the devcontainer.json - https://code.visualstudio.com/docs/remote/containers#_creating-a-devcontainerjson-file

You can also already install extensions through the CLI. I don't think that what you ask for makes anything simpler.

**Comment by youyongsong** [comment]
@roblourens hello, but I think there are some problems can't be solved with `devcontainer.json`:
* the environment setup by `devcontainer.json` is not persistence，each time the container is destroyed all environment need to be setup again. I think if we could setup the environment in a Dockerfile may be a better choice.
* We have some basic extensions(like git) are common to all projects, copy and sync the common basic extensions across all projects' `devcontainer.json` feels not good. I expect I can install and configure all that common extensions in a base docker image, and use that image as the base image for all projects.

**Comment by roblourens** [comment]
The extensions in devcontainer.json should be installed automatically each time the container is built. 

If you want to use an extension in every container, you can also use `remote.containers.defaultExtensions`

**Comment by youyongsong** [comment]
Thanks for suggestion, I'll try that.
