### ISSUE TITLE
Add user setting to set the remote host as having no internet connection

### ISSUE THREAD

**Issue by Helloimbob** [microsoft/vscode-remote-release#1106]
It would be useful to be able to explicitly tell the remote extension that the remote host has no internet connection. 
This would make installing extensions via the client (and with the new installing server via client) quicker and easier, since we won't have to wait for the original request on the remote host to timeout (5 mins) before using the client to download and transfer to the remote host.

**Comment by sandy081** [comment]
Introduced a setting `remote.downloadExtensionsLocally` when enabled, extensions are downloaded locally and installed on remote.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/10746682/68219611-917d9c00-ffe6-11e9-9611-c61ddfd606ce.png">

**Comment by sandy081** [comment]
To verify:

- Enable log level to trace
- Open window log in output panel
- If above setting is enabled, Verify that installing extensions in remote are downloaded locally by checking the logs. Otherwise extensions are downloaded in remote.
