### ISSUE TITLE
File duplication command does not work on SSH

### ISSUE THREAD

**Issue by DjalelBBZ** [microsoft/vscode-remote-release#1107]
Issue Type: <b>Bug</b>

Open the palette with cmd+shift+p
Enter "File: duplicate"
Press Enter. 

The file is not duplicated. 

Extension version: 0.44.2
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.15.0-48-generic

**Comment by roblourens** [comment]
I think this command must come from an extension. Please file an issue on the extension.
