### ISSUE TITLE
Poor error message when trying to open a terminal in a non-existent directory

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode-remote-release#1109]
This is a follow-up to #1073

- VSCode Version: 1.37.0-inside  36e08fed41272d1ff0d73d9b3a540b0a052ecef4
- Local OS Version: macOS 10.14.4
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.  Create a workspace on the remote machine that contains a directory that doesn't exist.
2. Open the workspace using the remote SSH extension.
3. Try to open a terminal.
4. You'll get an error message: `The terminal process terminated with exit code: -3` which is not very helpful.

*Does this issue occur when you try this locally?:* No, you get the somewhat more helpful error message `The terminal shell CWD "/path/to/nonexistent/directory" does not exist`

Really I think you should still be able to open a terminal even if one of the workspace directories doesn't exist, but in the mean time a decent error message would be good.

**Comment by roblourens** [comment]
This is what I see, when I open a terminal on that directory

![image](https://user-images.githubusercontent.com/323878/62810602-4a4d4100-bab3-11e9-9a36-767c830bc34c.png)

**Comment by Timmmm** [comment]
No. That's what I see too in a non-remote workspace. Are you using a remote workspace? I'll try again to confirm on Monday.

**Comment by roblourens** [comment]
Yeah this is also a remote workspace.

**Comment by Timmmm** [comment]
Ok that's weird. Well, feel free to close this if you like, though `[object Object]` is clearly not right either!

**Comment by Tyriar** [comment]
@Timmmm I'll hopefully fix both soon 😃

**Comment by Tyriar** [comment]
Fixed in https://github.com/microsoft/vscode/commit/0b4c4dc892cc52a9a1b42d41579299d6a4ddbe92

To verify make sure an invalid value for `terminal.integrated.cwd` gives a good error message both locally and in remote.

**Comment by royz4u** [comment]
Looks like I ran into this problem as well.
[https://www.screencast.com/t/qBxIqqwi3R](url)

**Comment by Tyriar** [comment]
@royz4u looks like you probably set the setting wrong.
