### ISSUE TITLE
Recovery on connection lost

### ISSUE THREAD

**Issue by david50407** [Microsoft/vscode-remote-release#111]
What will happened if the connection lost on remoting SSH? Can I get back to the lastest state when the network connection is back (like mosh does, it captures requests and sends again when network is back)? Or I have to reconnect/reopen the workspace and do the changes again?

**Comment by kieferrm** [comment]
The client tries to reconnect for 3 hours before we give up. Note, we can only reconnect if we find the exact same instance of the VS Code Server, the client was connect to before. If we don't the reconnect fails. I.e. reboot of servers etc. don't allow for reconnect.
