### ISSUE TITLE
too much memory for remote-ssh vscode

### ISSUE THREAD

**Issue by skayres** [microsoft/vscode-remote-release#1110]
- VSCode Version: 1.36.1
- OS Version: windows 10 x64

Steps to Reproduce:

1. Create remote-ssh connection to a host
2. After a couple of hours see memory consumption by vscode on the host

Does this issue occur when all extensions are disabled?: Yes/No
No. The root of cause is extension 'remote-ssh'

**Comment by roblourens** [comment]
Please give more details. Which processes do you see using memory? Are you running remote extensions?

**Comment by ArrowComputingTech** [comment]
Same here. Using Remote-SSH to connect.
My VPS crashed a couple times because it ran out of memory while connected with VSCode. It's never crashed before in 2 years of use, and typically stays around 50-60% use on 1GB.
![snip](https://user-images.githubusercontent.com/44952894/62715422-15af8b80-b9c6-11e9-9fdb-f8ad86bd9ea4.PNG)

**Comment by ArrowComputingTech** [comment]
@skayres Were you using more than 1 instance of VSCode? I think mine might be crashing when I connect to it from more than one machine.

**Comment by roblourens** [comment]
Does your VM have only 1gb of RAM? This will probably not be enough to use vscode. But I think your screenshot does not really show a major issue. Keep in mind those rows are threads, not processes.

**Comment by ArrowComputingTech** [comment]
Yes, it only has 1GB. That's the remote end of the SSH connection. I haven't been able to consistently use VSCode to connect to this server because it crashes the server. Looks like I should upgrade...

https://code.visualstudio.com/docs/supporting/requirements

Thanks @roblourens

**Comment by entr0cks** [comment]
Not really simple SFTP - sadly. In my case, not very usable with small specialized (aka in use) instances - see multiple process started on remote each min 50MB in size. With other connections up, out of memory - instance locked...
