### ISSUE TITLE
File watch polling interval not honered

### ISSUE THREAD

**Issue by CreatedBySeb** [microsoft/vscode-remote-release#1113]
Issue Type: <b>Bug</b>

If a program is compiled using the WSL terminal using g++ (`g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`) and removed using `rm` in the WSL terminal, it will become undeleteable from WSL, in the Windows Explorer or using Command Prompt, until Visual Studio Code is reloaded. For instance, given a source file `simple.cpp`:

```c++
int main() {
    return 0;
}
```

and the command `g++ simple.cpp -o simple`, the command `rm simple` will appear to work initially, but will cause simple to show up unreadable with `ls -l`. The only solution is to reload or exit Visual Studio Code, which can slow down work dramatically if you forget not to delete files in the terminal. Deleting files in the VS Code explorer will cause them to disappear from the explorer, but the issue will persist. The only way to avoid the issue entirely is to delete files from Windows Explorer, without attempting to write over them by running `g++ simple.cpp -o simple` again.

Extension version: 0.38.10
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (8.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3201)|
|Memory (System)|15.70GB (8.44GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment]
@CreatedBySeb can you try whether switching to the polling file watcher solves the problem?
Pls see https://github.com/microsoft/vscode-docs/blob/master/remote-release-notes/v1_36.md#use-polling-for-file-watching-in-wsl

**Comment by CreatedBySeb** [comment]
Enabling polling solved the issue, in that files can now be successfully deleted/renamed/overwritten/etc., but the pollingInterval setting does not seem to be respected, I have it set to 500 just to test how it works, but it doesn't seem to be updating the file browser at all. I've waited at least a minute. Refreshing manually makes the files show up. Interestingly, opening settings.json seems to force an update, but opening other files doesn't appear to have the same effect (for example, the source file).

**Comment by aeschli** [comment]
If you leave the polling interval at the default, does it work?

**Comment by CreatedBySeb** [comment]
No, I've tried a range of values including the default 5 seconds, from sub 1 second to 15 seconds (just to see if it would work).

**Comment by aeschli** [comment]
Can you run the command `Set Log Level` and set the level to `verbose'? Then Open the Output view, go t the 'Remote Server' tab to see the event sent by the file watcher.

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/63340963-75078700-c348-11e9-9099-0f2370a3f14e.png)

**Comment by CreatedBySeb** [comment]
@aeschli I couldn't find a `verbose` option in `Set Log Level`, so I set it to `trace` to try and get the same output. Most of the time I don't get any output from File Watcher, but with a different project I got some output when I edited the source file:

```
[2019-08-21 17:23:08.075] [remoteagent] [trace] [File Watcher (chokidar)] [CHANGED] /mnt/d/.../quadruple-x.cpp
[2019-08-21 17:23:08.142] [remoteagent] [trace] [File Watcher (chokidar)]  >> normalized  [CHANGED] /mnt/d/.../quadruple-x.cpp
```

But I don't seem to get any output when I use g++ or rm. (I tried refreshing the tree to get the file to show up, and then rm'ing it, but it doesn't yield any output either.)

**Comment by aeschli** [comment]
Maybe related to the filewatcher exclusion patterns?
The defaults are
```
	"files.watcherExclude": {
		"**/.git/objects/**": true,
		"**/.git/subtree-cache/**": true,
		"**/node_modules/**": true
	},
```

**Comment by CreatedBySeb** [comment]
@aeschli Sorry, I've been away, I don't know why it would be related, as my file tree looks like:
```
simple/ (workspace root)
 - simple.cpp
 - simple
```
Is there an alternative value you would like me to try?
