### ISSUE TITLE
"code ." in Ubuntu terminal does nothing

### ISSUE THREAD

**Issue by SteveALee** [microsoft/vscode-remote-release#1114]
Issue Type: <b>Bug</b>

when i run 'code .' in my project directory on ubuntu nothing happens. The cwd is ~/project. I have to run code and open a window in the distro

Extension version: 0.38.10
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18950
Remote OS version: Linux x64 4.19.57-microsoft-standard
Remote OS version: Linux x64 4.19.57-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.57-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2207)|
|Memory (System)|14.58GB (13.55GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.57-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2207)|
|Memory (System)|14.58GB (13.55GB free)|
|VM|0%|
</details>

**Comment by 8thHalfHour** [comment]
Same. I just came here to report it. I get the following:

```
$ code .

Command 'code' not found, did you mean:

  command 'cobe' from deb python-cobe (2.1.2-1)
  command 'node' from deb nodejs (10.15.2~dfsg-1)
  command 'cdde' from deb cdde (0.3.1-1build1)
  command 'cde' from deb cde (0.1+git9-g551e54d-1.1)
  command 'tcode' from deb emboss (6.6.0+dfsg-7)
  command 'ode' from deb plotutils (2.6-10)

Try: sudo apt install <deb name>
```

I have tried uninstalling VSCode Insiders and reinstalled, without change.

**Comment by roblourens** [comment]
From an integrated terminal in vscode right? You should have `~/.vscode-server/bin/hash/bin` on your path. Is it possible that you have a bashrc or similar script removing it from the path?

**Comment by SteveALee** [comment]
> From an integrated terminal in vscode right? 

Ah, is that a requirement? I'm sure the article I read was taking about a standalone wsl shell. When i try it there does nothiby, not even return to prompt and ctrl c doesnt work. SO far I've had to open a new window in code and close the launching window which is messy.

**Comment by roblourens** [comment]
Yeah so if you run `code .` in an integrated terminal __in a Remote WSL window__ then it will be able to open that folder in another WSL session. Otherwise it is just invoking normal code.exe on your path.

**Comment by ksawerykarwacki** [comment]
I have the same issue even though this one is closed. I'm working on latest fast ring build with ubuntu on wsl2 and latest stable version of VSCode. Is this an issue within code/remote or there is some problem with wsl itself?
