### ISSUE TITLE
"runArgs" not work

### ISSUE THREAD

**Issue by wcchh** [microsoft/vscode-remote-release#1117]
- VSCode Version: 1.36.1
- Local OS Version: Linux x64 4.4.0-62-generic (Linux mint 18.1 64-bits)
- Remote OS Version: nikolaik/python-nodejs:python3.7-nodejs10
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. set "runArgs": ["--network", "d_net", "-e", "NODE_ENV=development"] in "devcontainer.json"
2. (disconnect) open folder in container ... to restart
3. settings not applied
4. try set "runArgs": [
		"--volume=${env:HOME}${env:USERPROFILE}/.ssh:/root/local-home"
	]
5. (disconnect) open folder in container ... to restart
6. settings not applied

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by Chuxel** [comment]
@wcchh Did you use the **Rebuild Container** command?  If not, the settings will not take effect. We need to implement #758 so that you're automatically prompted in scenarios like this since you are not alone.

**Comment by wcchh** [comment]
@Chuxel Thanks a lot! Rebuild Container command is work! 
I thought it didn't need to rebuild container since it's a [docker run] parameter.
Anyway, thanks for the help.
