### ISSUE TITLE
Why remote-ssh need Enter the password twice by password method??

### ISSUE THREAD

**Issue by hset911** [microsoft/vscode-remote-release#1118]
always need Enter the password twice,too troublesome.
Could configure the user name and password in the configuration file?
let it be automation?

**Comment by roblourens** [comment]
Working on this! You can set `"remote.SSH.enableDynamicForwarding": true` to try out a new mode where you will only have to enter your password once.

**Comment by aaronfulkerson** [comment]
> Working on this! You can set `"remote.SSH.enableDynamicForwarding": true` to try out a new mode where you will only have to enter your password once.

Having a problem with this setting where it doesn't really do anything until I click on "details" in the connection popup where it'll give me some information in a terminal window named "install".

**Comment by roblourens** [comment]
Please open a new issue and include the log from the Remote-SSH output channel
