### ISSUE TITLE
Config files don't work properly when defined in workspace settings

### ISSUE THREAD

**Issue by utkutombul** [microsoft/vscode-remote-release#1119]
- VSCode Version: 1.36.1
- Local OS Version: Windows_NT x64 10.0.18362
- Remote OS Version: Ubuntu 18.04.2 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Define a custom configuration file via "settings.json" in a workspace (not user settings, not global settings, must be a workspace "settings.json") with "remote.SSH.configFile" setting.
2. Put your settings in. Somehow it only reads "Host" and skips everything else including "User, HostName, IdentityFile".

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Can you explain what it means by "skips"? We just run `ssh <host>` and let ssh read your config file.

**Comment by utkutombul** [comment]
Weird. It started working today, despite my previous tries on the day I created this. Closed.
