### ISSUE TITLE
Fortran syntax error checking is not working in Remote ssh

### ISSUE THREAD

**Issue by Subratappt** [microsoft/vscode-remote-release#1121]
- VSCode Version: 1.36.1
- Local OS Version: macOS 10.13.6
- Remote OS Version: CentOS Linux release 7.6.1810 (Core)
- Remote Extension/Connection Type: SSH/Docker/WSL

I am using **Modern Fortran** extension in VS code which provides the syntax highlighting and error checking. It is working fine locally but syntax error checking is not working in Remote Development. I have installed the extension in both the local machine and remote server. Both the machines have `gfortran` installed, and I have provided the `gfortran` path in the `settings.json`.

Does this issue occur when you try this locally?: No

**Comment by roblourens** [comment]
Please file this issue on the extension's repo
