### ISSUE TITLE
Get prompted for the ssh pwd 5+ times to set up a connection to a cloud foundry app

### ISSUE THREAD

**Issue by IObert** [microsoft/vscode-remote-release#1122]
- VSCode Version: 1.36.1  2213894ea0415ee8c85c5eea0d0ff81ecc191529 x64
- Local OS Version: macOS 10.14.6 (18G84)
- Remote OS Version: NA / https://github.com/cloudfoundry/nodejs-buildpack
- Remote Extension/Connection Type: SSH/Docker/WSL SSH

I would like to connect to a running cloud foundry application. As CF doesn't expose SSH passwords, I can only retrieve one-time passwords from the local cli. I would understand if the plugin would prompt me 2-3 times bc the password expired, but I get prompted 5-8 times just to set up the initial connection.
I think the underlying problem is, that there are too many SSH sessions in parallel open or they get cut off to fast. Normal SSH connections (without the plugin) work perfectly fine.

 I know this isn't the main use-case of this plugin, but it would be interesting to know if you plan to reduce the number of parallel sessions.

Steps to Reproduce:

I wrote a blog [post](https://blogs.sap.com/2019/08/02/cloudfoundryfun-7-connect-vs-code-to-deployed-cloud-applications/) about this, please have a look there if you'd like to reproduce it

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
I would expect 2 times. Please share the log from the Remote-SSH output channel. Also see if `"remote.SSH.enableDynamicForwarding": true` helps, that should reduce it from 2 to 1 pw auth.

**Comment by IObert** [comment]
Thanks for the explanation. I think you're right that I get prompted twice, but this happens a couple of times.
The first time (1st +2nd prompt) when I try to set up the connection. Log:
```
remote-ssh@0.45.2
darwin x64
SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a224346424c4f42227d", attempt 1
SSH Resolver called for host: CFBLOB
Setting up SSH remote "CFBLOB"
Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_7.9p1, LibreSSL 2.7.3
Running script with connection command: "ssh"  -o ClearAllForwardings=true -o ConnectTimeout=15   "CFBLOB" bash
Install and start server if needed
> cf:9dae73ff-4991-4a55-8c57-070@ssh.cf.eu10.hana.ondemand.com's password: 
"install" wrote data to terminal: "**********"
> 
> Running remote connection script
> Found existing installation at /home/vcap/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529...
> Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Checking server status with wget
> 6bb1d75b-92b4-43d5-a60f-796917f017fe==44679==41717==
"install" terminal command done
Received install output: 6bb1d75b-92b4-43d5-a60f-796917f017fe==44679==41717==
Server is listening on port 44679
Running script with connection command: "ssh" -L 127.0.0.1:44679:127.0.0.1:44679  -o ConnectTimeout=15   "CFBLOB" bash
Spawning tunnel with: "ssh" -L 127.0.0.1:44679:127.0.0.1:44679  -o ConnectTimeout=15   "CFBLOB" bash << 'EOSSH'
echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity
EOSSH
> cf:9dae73ff-4991-4a55-8c57-070@ssh.cf.eu10.hana.ondemand.com's password: 
"SSH Tunnel" wrote data to terminal: "**********"
> 
> Connected to SSH Host - Please do not close this terminal
Spawned SSH tunnel between local port 44679 and remote port 44679
Waiting for ssh tunnel to be ready
Tunneling remote port 44679 to local port 44679
Resolved "ssh-remote+7b22686f73744e616d65223a224346424c4f42227d" to "127.0.0.1:44679"
------
```

And a second time (3rd +4th prompt), when I try to open a folder:
```
remote-ssh@0.45.2
darwin x64
SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a224346424c4f42227d", attempt 1
SSH Resolver called for host: CFBLOB
Setting up SSH remote "CFBLOB"
Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_7.9p1, LibreSSL 2.7.3
Running script with connection command: "ssh"  -o ClearAllForwardings=true -o ConnectTimeout=15   "CFBLOB" bash
Install and start server if needed
> cf:9dae73ff-4991-4a55-8c57-070@ssh.cf.eu10.hana.ondemand.com's password: 
"install" wrote data to terminal: "**********"
> 
> Running remote connection script
> Found existing installation at /home/vcap/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529...
> Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Checking server status with wget
> 4623d4f9-a4e0-4e7a-8650-5662cca4f1d4==44679==41717==
"install" terminal command done
Received install output: 4623d4f9-a4e0-4e7a-8650-5662cca4f1d4==44679==41717==
Server is listening on port 44679
Running script with connection command: "ssh" -L 127.0.0.1:44679:127.0.0.1:44679  -o ConnectTimeout=15   "CFBLOB" bash
Spawning tunnel with: "ssh" -L 127.0.0.1:44679:127.0.0.1:44679  -o ConnectTimeout=15   "CFBLOB" bash << 'EOSSH'
echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity
EOSSH
> cf:9dae73ff-4991-4a55-8c57-070@ssh.cf.eu10.hana.ondemand.com's password: 
"SSH Tunnel" wrote data to terminal: "**********"
> 
> Connected to SSH Host - Please do not close this terminal
Spawned SSH tunnel between local port 44679 and remote port 44679
Waiting for ssh tunnel to be ready
Tunneling remote port 44679 to local port 44679
Resolved "ssh-remote+7b22686f73744e616d65223a224346424c4f42227d" to "127.0.0.1:44679"
------
```

I'm sure if got prompted for another two times last week after I edited some files, but I wasn't able to reproduce this today.

PS: I added `"remote.SSH.enableDynamicForwarding": true` to the settings.json, but I'm still prompted twice in a row and the editor marks the config as invalid. I am used the latest version `0.45.2`

<img width="582" alt="Screen Shot 2019-08-12 at 11 26 22" src="https://user-images.githubusercontent.com/1873245/62856867-583ed400-bcf6-11e9-833f-7d36a053b745.png">

**Comment by roblourens** [comment]
> And a second time (3rd +4th prompt), when I try to open a folder:

Oh ok, that makes sense.

The latest is 0.45.4, check for updates on that extension.

**Comment by IObert** [comment]
Thanks, I updated the extension and it works now! 
Just to confirm, the second prompt is intended (at least for onetime passwords)?

**Comment by roblourens** [comment]
Yes, when you open the new window (by opening a folder) it should prompt again.
