### ISSUE TITLE
several file watchers fail after a while using containers

### ISSUE THREAD

**Issue by rhyek** [microsoft/vscode-remote-release#1126]
- VSCode Version: 1.36.1
- Local OS Version: Windows 10 Pro Version	10.0.18362 Build 18362
- Remote OS Version: `FROM ubuntu:latest`
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. have a monorepo project with 1) node + koa using `ts-node-dev` and 2) `create-react-app` app
2. start each with their corresponding dev scripts in watch mode (they both run in the same docker container)
3. start editing source files and saving them
4. after a while one or a combination or even all of the following will happen:
    - ts-node-dev will not detect changes in source files
    - create-react-app will not detect changes in in source files
    - visual studio code's git integration will not detect changes in the repo's tracked files
    - when importing modules (typescript), visual studio code will not autocomplete paths for new files

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: -

I have had to switch to configuring each project to use polling to detect file changes which is not ideal and this doesn't solve the issue with git and module import autocomplete.

I have tried Remote - WSL for a while and didn't notice any of these issues. I have not tested that setup for a prolonged time, however.

Edit: Tested using the latest insiders build and noticed the same issue.

Edit: Just tested 1.37.0 and the problem is there as well.

**Comment by rhyek** [comment]
Also, if ts-node-dev or create-react-app eventually fail, i can restart them without restarting the container and they will again work for a while.

**Comment by aeschli** [comment]
Anything in the logs? (View > Output)
To see in detail what the file watcher detects, you can turn on trace mode (Run command `Developer: Set Log Level...` and pick `Trace` ).You can then see the File Watcher logging in the `Log (Remote Server)` tab.

**Comment by aeschli** [comment]
similar issue: #870

**Comment by aeschli** [comment]
@rhyek Are you on WSL1 or WSL2?

**Comment by rhyek** [comment]
@aeschli I am not using either. I'm using containers. I haven't had the problems lately. I believe it might be because I increased the available RAM to docker containers on my Windows host.

I still see the behavior with Git integration kind of frequently, but it is not so troublesome since I can just hit the refresh button on the Git panel.

My dev processes will still stop responding to file changes like mentioned in the initial description of this issue when resuming the Windows host computers from sleep.

**Comment by chrmarti** [comment]
@rhyek Please try: https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc

**Comment by rhyek** [comment]
@chrmarti hey, thanks. I just checked that setting and the current limit was already set to maximum. My docker image extends `ubuntu:latest`, so maybe that's it.

I think I might close this issue, because the problems I mentioned haven't really creeped up lately (aside from the waking from sleep one which I don't really care about). Although, there is still one remaining problem I have which I thought was just a Typescript language service bug (and therefore hadn't mentioned it), but turns out it's not:

Every time I add a new TS module, import auto-completion does not work when I try to import anything into it from the rest of the project and when I import anything it itself exports in any other file. I have to manually type out the imports including module path. I figured I could restart the TS language service and now autocompletion works!

So I was doing this the whole time thinking it was a general issue, but when I tried working on the project on my Macbook Pro the issue is non-existent there!

On my Windows maching Docker Desktop is updated to the latest version and everything. This is not something that happens after some amount of time. It is just always like this.

**Comment by rhyek** [comment]
I'm not sure what info would be necessary for that one. I just ran a test on Windows creating a new project using the "node:latest + typescript" and create 2 files trying to import stuff between them and all worked perfectly.

I'm guessing my issue stems from the project being a monorepo. Like I said, everything works perfectly on the Macbook.

**Comment by rhyek** [comment]
I'll see if I have time this week to make a sample repo trying to replicate the issue and I'll link it here.

**Comment by rhyek** [comment]
Sorry, haven't been using remote containers for a while, so can't check at this moment. I remember increasing docker containers' memory capacity helped quite a bit, but never managed to see any relevant logs to be sure that was the root cause.
