### ISSUE TITLE
SSH using Host setting from Config File

### ISSUE THREAD

**Issue by dsadosky** [microsoft/vscode-remote-release#1129]
Issue Type: <b>Bug</b>

In earlier verions, up until this week it seems, I was able to configure my ssh config file like:
Host my-test-system
    HostName 10.1.0.51
    User my-test-user

The Host field was free form text that I could use to easlity identify the system in the Remote-SSH connection pain.  It would then take the values of Hostname and User to establish the ssh connection.  Recently, it started using the value of the "Host" field to establish a connection which is not a valid hostname or IP address but a lable to id systems within the Connections pain.  Now the only way I can establish a connection is to put the ip or valid hostname in the Host field.  Unfortuately this is also the label that shows up in the Connections pain making it hard to differntiate between systems.

[12:51:35.975] remote-ssh@0.45.4
[12:51:35.975] darwin x64
[12:51:35.976] SSH Resolver called for "ssh-remote+my-test-system", attempt 1
[12:51:35.976] SSH Resolver called for host: my-test-system
[12:51:35.976] Setting up SSH remote "my-test-system"
[12:51:35.984] Using commit id "5e08ee01b7daee99cdda2456f19d77e715fb8762" and quality "insider" for server
[12:51:35.986] Testing ssh with ssh -V
[12:51:36.005] ssh exited with code: 0
[12:51:36.005] Got stderr from ssh: OpenSSH_7.9p1, LibreSSL 2.7.3
[12:51:36.005] Running script with connection command: ssh -o ClearAllForwardings=true -o ConnectTimeout=15 my-test-system bash
[12:51:36.005] Install and start server if needed
[12:51:36.569] > Password: 
[12:51:36.569] Got some output, clearing connection timeout
[12:51:40.961] "install" terminal command canceled
[12:51:40.961] Install terminal quit with output: 
[12:51:40.961] Received install output: 
[12:51:40.962] Failed to parse remote port from server output: 
[12:51:40.962] 
[12:51:40.962] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"UnparsableOutput"},"measures":{"resolveAttempts":1,"retries":1}}
[12:51:40.962] ------

Extension version: 0.45.4
VS Code version: Code - Insiders 1.37.0-insider (5e08ee01b7daee99cdda2456f19d77e715fb8762, 2019-08-05T21:16:01.319Z)
OS version: Darwin x64 18.6.0
Fetching remote diagnostics for 'SSH' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|10%|

Fetching remote diagnostics for 'SSH' failed.
</details>

**Comment by roblourens** [comment]
We simply run `ssh <host>` which tells ssh to look up the details in your ssh config file. Can you explain some more about what you are seeing? The log shows that it should have showed you a password prompt.

**Comment by dsadosky** [comment]
Figured out the problem…My actual settings for Host included a open and closed parenthesis () which the the SSH command didn’t like

Host test-(10.1.1.x)
HostName 10.1.1.x
User test_user


Please close

Regards,

David Sadosky
Technical Account Manager
gen-E
e:  david.sadosky@gen-e.com<mailto:david.sadosky@gen-e.com>
m: 832-545-6453
a:  2301 Blake Street, Suite 250
     Denver, CO 80205
w:  www.gen-e.com<http://www.gen-e.com/>

[cid:4CE6F5EE-9B83-436A-8029-0BF68E6D54BD]
 [cid:9F397E8E-B839-4A2A-ACA1-311BD0B2CA2A]  <http://www.gen-e.com> [cid:7956D518-D89D-4AB4-973F-3880BC30CDA0] <https://twitter.com/genE_Info>  <https://twitter.com/genE_Info> [cid:04F005A7-BA38-4FB0-A15B-FD2F7D08336C]
<https://www.linkedin.com/company/4867970/>
<https://www.linkedin.com/company/4867970/>

On Aug 9, 2019, at 5:39 PM, Rob Lourens <notifications@github.com<mailto:notifications@github.com>> wrote:


We simply run ssh <host> which tells ssh to look up the details in your ssh config file. Can you explain some more about what you are seeing? The log shows that it should have showed you a password prompt.

**Comment by roblourens** [comment]
OpenSSH handles it fine as long as it gets past the shell, so I think I just need to quote the hostname in this case. Thanks for pointing that out.

**Comment by roblourens** [comment]
Already fixed normally but need to fix when using `"remote.SSH.useLocalServer": true`.

Verification steps, enable that setting and verify that you can connect to a host with parens in the name, like

```
Host test-(10.1.1.x)
    HostName 123.123.123.123
```
