### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by urakymzhan** [microsoft/vscode-remote-release#1131]
- Issue Type: `Bug`
- Extension Name: `remote-ssh-explorer`
- Extension Version: `0.45.2`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.35.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by roblourens** [comment]
> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️
