### ISSUE TITLE
Query strings double-encoded in webviews in VS Code Remote - Breaks extensions

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#1132]
Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:22:37.660Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

This broke the SQL Server extension and likely others.  Currently it appears that the query string passed through an iframe with a port mapping in the WebView API ends up getting uri encoded (other calls may as well).  For example, if a localhost webserver expects:

```
/webview?test=true
```

…it gets this instead:
```
/webview?test%3Dtrue
```

Repro:
1. Download this project and open it in VS Code stable: [webview3.zip](https://github.com/microsoft/vscode-remote-release/files/3487854/webview3.zip)
2. Reopen Folder in Container
3. `yarn install`
4. F5
5. Run **WebView Example: WebView Demo**

**Expected:** Webview appears with the text `/webview?test=true` before an image.
**Actual:** `/webview?test%3Dtrue` appears instead.

//cc: @kieferrm @mjbvz 

@chrisdias - FYI given extension testing going on.

**Comment by roblourens** [comment]
This is broken even not in remote

**Comment by Chuxel** [comment]
@roblourens Ah interesting - MSSQL uses the same port internally and externally which much avoid the issue. (The customer reported it working locally, so I focused on the remote scenario.)

**Comment by roblourens** [comment]
From https://github.com/microsoft/vscode/blob/4dfac135d0e635ddcf61ba61ee9aea23091bcecf/src/vs/workbench/contrib/webview/common/portMapping.ts#L57

We now always uri-encode the query part, after https://github.com/microsoft/vscode/commit/69146d090e1785fe122526a4d74467ece743f38a

**Comment by jrieken** [comment]
@mjbvz The problem is that our `URI#toString` is mostly dumb and only guarantees that `toString` and `parse` don't loose information. When serialising uris for interopt then some care must be taken. The common trick is to use `uri.toString(true)` which means don't encode and then pass that into `encodeURI`, like here: https://github.com/microsoft/vscode/blob/5d22d7f74c36ef606347f647def0bad73b4877bc/src/vs/editor/browser/services/openerService.ts#L58

**Comment by mjbvz** [comment]
Will investigate to see if we want to add this to July recovery. Fix seems relatively scoped
