### ISSUE TITLE
Remote Containers: file permission change causes git to show all files as modified

### ISSUE THREAD

**Issue by djensen47** [microsoft/vscode-remote-release#1134]
- VSCode Version: 1.37.0
- Local OS Version: Windows 10.0.18362
- Remote OS Version: Debian 9.5
- Remote Extension/Connection Type: Docker
- Docker version: Docker Desktop Community 2.0.0.3 and 2.1.0.1

Steps to Reproduce:

1. Clone a repository on Windows
2. Open Folder in container
3. Open the source control

Expected Result:
No files modified

Actual Result:
All files are modified.

A `git diff <filename>` results in this:
```
diff --git a/<filename> b/<filename>
old mode 100644
new mode 100755
```
---
aside: I'm super surprised this hasn't come up yet because my understanding is that volume mounts are basically SMB which has these funky permission issues. Hopefully my understanding is wrong.

**Comment by djensen47** [comment]
I found a workaround, one that's really not ideal.

In the container run this in the git dir
`$ git config core.fileMode false`

**Comment by egamma** [comment]
pls see https://code.visualstudio.com/docs/remote/troubleshooting#_resolving-git-line-ending-issues-in-containers-resulting-in-many-modified-files for the recommended approach.

**Comment by djensen47** [comment]
Thank you but please re-open because this is **not** a file ending issue. I checked and doubled checked file endings. I used the `file` command as well as looking at the status bar in VS Code.

Also, my issue was fairly explicit about this being a file mode and/or permission changing issue. This is actually not the first time that Windows VS Code has changed file permissions in my repos but this bug is specifically for containers.

Also, you can clearly see the work around had nothing to do with file endings. It's a file mode issue.

**Comment by djensen47** [comment]
@egamma I updated the steps to reproduce. Step 1 is in fact the suggestion you made. It was the first thing I tried to fix the issue.
