### ISSUE TITLE
Add setting to specify commands to execute on connection

### ISSUE THREAD

**Issue by ArcanoxDragon** [microsoft/vscode-remote-release#1139]
So far I've very much been enjoying the Remote SSH extension, and have found it to be a huge productivity booster while working on remote servers...there's just one thing missing that would make it even better.

I discovered I can set my `VISUAL` variable to `code -w` so commands like `crontab -e` and `visudo` open the file being edited in an actual VSCode editor tab. This is extremely useful and I was pleasantly surprised when I tried it the first time and learned how well it works. However, it's a bit of a pain to have to manually set this every time I open the workspace. I can't put it in my `.bash_profile` because if I connect via another client, all of a sudden my editor doesn't work because it's trying to use `code -w` without being connected through VSCode.

I would like a way to specify, via VSCode settings, a list of remote commands to run after connecting to the remote host. This could be at the global, workspace, or "remote" level. This would allow me to put something like `"remote.SSH.connectCommands": [ "export VISUAL=\"code -w\"" ]` in my workspace settings and have it automatically set the variable _only_ when connecting via VSCode. I couldn't find any other way of accomplishing this with the functionality included in "Remote: SSH" currently.

**Comment by antst** [comment]
I also would love to have this functionality.
Typical case is that on remote system with Lmod (or environmental modules) there are some modules needs to be loaded for particular workspace (for example to get environment for compiler etc), and it would be very nice to have option to configure commands to execute on connect, to automatically do it.

**Comment by giddyhup** [comment]
You might find a solution here: https://github.com/microsoft/vscode-remote-release/issues/1722#issuecomment-611200194 (using the terminal.integrated.shellArgs.linux setting).

**Comment by tanhakabir** [comment]
Thank you for this request! I see on https://github.com/microsoft/vscode-remote-release/issues/4474 others have requested something similar. I'm going to close this issue and track progress on this feature on https://github.com/microsoft/vscode-remote-release/issues/4474.
