### ISSUE TITLE
ForwardAgent in SSH Config is ignored

### ISSUE THREAD

**Issue by twolodzko** [microsoft/vscode-remote-release#1145]
- VSCode Version: 1.37.0
- Local OS Version: Ubuntu 18.04
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Configure the .ssh/config on the local machine

```
Host remote
   HostName xxx.xxx.xxx.xxx
   User username
   ForwardAgent yes
```
2. Configure GitHub/BitBucket etc. to accept the SSH key from the local machine.
2. Connect to remote machine using VS Code Remote.
3. Try using Git integration either one integrated in VS Code, or from the build-in terminal; neither of them works as the Agent is not forwarded. To use git I need to use external terminal, with another connection (it uses same .ssh/config, no extra parameters) to use git.

**Comment by roblourens** [comment]
For now you just need to set `remote.SSH.enableAgentForwarding`
