### ISSUE TITLE
Support $HOME environment variable in "remote.SSH.configFile"

### ISSUE THREAD

**Issue by rcdailey** [microsoft/vscode-remote-release#1146]
- VSCode Version: 1.37
- Local OS Version: Windows 10
- Remote OS Version: N/A
- Remote Extension/Connection Type: SSH

On my machine, I have a `HOME` environment variable set which points to my linux home directory (this is mostly for Git Bash):

```
HOME=C:\Development\Home
```

I want the SSH Remote extension to use this path to find my `~/.ssh/config` file, which does exist. However, it doesn't offer that in the list (it treats `~` as `C:\users\myname`). I tried to set the setting like so:

```
"remote.SSH.configFile": "${env:HOME}/.ssh/config"
```

Which should resolve to `C:\Development\Home\.ssh\config`, but it doesn't seem to recognize it. I think maybe environment variable support is lacking in this specific setting. I get this error:

```
ENOENT: no such file or directory, mkdir 'C:\Program Files\Microsoft VS Code\${env:HOME}'
```

How can I get the Remote SSH extension to recognize and use my `.ssh/config` in a cross-platform way? I sync my `HOME` directory as well as my VS Code settings across my work machines. I have my `HOME` path set differently on each machine. So it's important to be able to configure this extension to find my hosts, keys, and other configuration consistently across these platforms.

**Comment by roblourens** [comment]
We use node's `os.homedir()` which uses the USERPROFILE variable. Sounds like you have a different sort of setup but it's a fair request. https://nodejs.org/api/os.html#os_os_homedir

**Comment by roblourens** [comment]
The sshfs extension doesn't use ssh.exe at all and has made some different design decisions which make sense for their case, but not ours.

**Comment by rcdailey** [comment]
Why was this marked "out of scope"? On 8/15/2019 you said:

> it's a fair request

**Comment by 2Torr** [comment]
I also think that supporting $HOME environment variable in "remote.SSH.configFile" is a great idea!
Or ${env:<var>} or even ${command:<cmdname>} to run arbitrary tasks.

I'm setting up a multi-user build environment on a remote Windows VM, and having this feature would really help simplify per user configuration.
Would it be possible to please re-open this request?
Thanks!

**Comment by akarasulu** [comment]
I just notice that environment variables in the ssh config file are not honored. At least with ssh-config file env variables, we could have gotten around this problem using openssh v8.4 and above.

**Comment by glass-ships** [comment]
+1 to consider re-opening. 
Semi-related to https://github.com/microsoft/vscode/issues/2809
Would be nice to set:
`"remote.SSH.configFile": "${env:userHome}/.ssh/config",`
or similar, and have it search `%USERPROFILE%` on Windows or `/home/username` on Unix platforms.
