### ISSUE TITLE
Open/Reopen folder in a container from a Docker Hub image

### ISSUE THREAD

**Issue by brunoborges** [Microsoft/vscode-remote-release#115]
From the VS Code Extension, allow user to type in the name of an image available in Docker Hub.

Right now, the list is predefined.

**Comment by alvarlagerlof** [comment]
I hope that you know that you can picka a ubuntu or debian image, then edit the docker file yourself to install the right packages.

**Comment by brunoborges** [comment]
I do know, but I think allowing the developer to type in a specific image available in a remote Docker repository is more natural.

**Comment by Chuxel** [comment]
@brunoborges You're welcome to use any image you want, but many will not have the needed dev tools.  See here if you don't want to use a Dockerfile: https://code.visualstudio.com/docs/remote/containers#_using-an-existing-container-image

**Comment by egamma** [comment]
Closing, this is supported in the devcontainer.json file as pointed out in the previous comment.
