### ISSUE TITLE
Python extension was crashed unexpectly when using the remote ssh

### ISSUE THREAD

**Issue by luanft** [microsoft/vscode-remote-release#1150]
Issue Type: <b>Bug</b>

The ms-python extension was stopped working after connected to remote server a few minutes

Extension version: 0.45.4
VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.15063
Remote OS version: Linux x64 3.10.0-862.14.4.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.43GB (2.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vndc-adm01|
|OS|Linux x64 3.10.0-862.14.4.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz (16 x 3200)|
|Memory (System)|62.64GB (41.83GB free)|
|VM|0%|
</details>

**Comment by luanft** [comment]
![image](https://user-images.githubusercontent.com/11657076/62910483-42431900-bdb3-11e9-8973-43a83f196c24.png)
Here is my screenshoot. I opened a python file, but ms-python can not run.
It's okay if I use the VNC for working

**Comment by WSLUser** [comment]
This is the case even with running python on local machine. If the Remote extension is installed, it crashes the extension host or at least prevents python and Intellicode from working.

**Comment by egamma** [comment]
Please report the issue against the python extension

**Comment by luanft** [comment]
@egamma I don't think it is the issue of python extension. Because I can VNC to the server and work with the VScode there. It's no crashed.
 
The mspython extension is still working for a few minutes but crashed after that.
