### ISSUE TITLE
Unable to start debugging (C/C++)

### ISSUE THREAD

**Issue by colonyevan** [microsoft/vscode-remote-release#1151]
- VSCode Version: 1.37
- OS Version: Windows 10 - 1903 with WSL
- Extensions (Up-to-date): Remote - WSL, C/C++, C++ Intellisense, GitLens, Live Server, Prettier - Code Formatter. I disabled all extensions but C/C++ and remote - WSL to ensure the issue persisted
- Ensured all WSL apps are up-to-date with a sudu apt-get update && sudo apt-get upgrade

Steps to Reproduce:

Start any project, add some easy code, and compile (I compile from the command line with g++).
Begin debugging with the launch.json from https://code.visualstudio.com/docs/cpp/config-wsl.
There will then be a pop-up like the one below:

![image](https://user-images.githubusercontent.com/15172814/62913531-1a6f9900-bd52-11e9-8618-c4e4a16c366f.png)

Before the recent VSCode update I was at least getting further than this in the debugging process (before the update whenever I interacted with the user via cout/cin the debug session would hang)

Below is my launch.json

![image](https://user-images.githubusercontent.com/15172814/62913540-22c7d400-bd52-11e9-8dbd-7f999493fb50.png)

One important note is that I have two drives on my machine and my project is on a different drive than my operating system and WSL.

**Comment by egamma** [comment]
@weinand has anything changed on our side? Otherwise pls move the issue to the C++ extension.

**Comment by weinand** [comment]
@colonyevan This issue could be related to https://github.com/microsoft/vscode/issues/78898.
A fix is already available in Insiders.
Could you try whether the problem still exists in Insiders?

**Comment by cruzeflute** [comment]
> @colonyevan This issue could be related to [microsoft/vscode#78898](https://github.com/microsoft/vscode/issues/78898).
> A fix is already available in Insiders.
> Could you try whether the problem still exists in Insiders?

Are you sure?
I uninstall vscode,install vscode insider.And the problem still exists in Insiders.

**Comment by weinand** [comment]
@colonyevan no, I wasn't not sure. That's why I used the word "could" ;-)

**Comment by weinand** [comment]
@colonyevan please file the issue against the C++ extension: https://github.com/microsoft/vscode-cpptools/issues

**Comment by colonyevan** [comment]
Sorry, I have not had access to the internet for the past couple of days. I'll go file it there, thanks for the help!
