### ISSUE TITLE
Can't type Korean alphabet(Hangul) on Terminal

### ISSUE THREAD

**Issue by ryush00** [microsoft/vscode-remote-release#1156]
- VSCode Version: 1.36.1 (user setup)
- Local OS Version: Windows_NT x64 10.0.18362
2213894ea0415ee8c85c5eea0d0ff81ecc191529
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0

- Remote OS Version: Ubuntu 16.04.2 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Type any Hangul. To type "이것은 한글입니다." Change to Korean(2sets) input and press
`dlrjtdms gksrmfdlqslek.`
2. It couldn't be typed.

This should be 
![Honeycam 2019-08-14 00-26-31](https://user-images.githubusercontent.com/4997174/62954933-2b400d80-be2b-11e9-9967-927c1346f294.gif)

But on Terminal Tab, it was
![Honeycam 2019-08-14 00-27-46](https://user-images.githubusercontent.com/4997174/62955026-57f42500-be2b-11e9-8c7a-8ce792aafc36.gif)

 When press Enter, it only recognize `.`.
![image](https://user-images.githubusercontent.com/4997174/62955111-7e19c500-be2b-11e9-9408-a6dcac3a5af9.png)

**Comment by Tyriar** [comment]
I can't reproduce this, it's working fine for me on Windows 10 -> Ubuntu 18.04 using Korean Microsoft IME. @ryush00 what IME are you using?

**Comment by Tyriar** [comment]
Also please update to v1.37.1

**Comment by ryush00** [comment]
I tried to reproduce bug there's no more bug... weird.. lol

So I'll close the issue. Thank you
