### ISSUE TITLE
ssh config file not read by extension

### ISSUE THREAD

**Issue by fabge** [microsoft/vscode-remote-release#1159]
* VSCode Version: 1.37.0
* Local OS Version: 10.15 Beta (MacOS Catalina)
* Remote OS Version: Ubuntu 18.04 (LTS) x64
* Remote Extension/Connection Type: SSH

When I ssh in the macOS terminal with `ssh -i deployer_key deployer@167.xxx.xxx.xxx` it works smoothly.
Trying to use the Remote SSH extension in VSCode I can't make it work.

I added following to the config file in ~/.ssh/ but VSCode can't seem to read the file. It doesn't show up in the sidebar and the connection permission is denied.

```
Host ssh-with-identity-file
    User deployer
    HostName 167.xxx.xxx.xxx
    IdentityFile ~/.ssh/deployer_key
```

What am I missing or doing wrong?

**Comment by roblourens** [comment]
Most likely vscode is not looking at that configuration file. If you run "Remote-SSH: Open Configuration File", do you see that file? You can either move your config to one of those files or set the path to a custom one through a setting.
