### ISSUE TITLE
Version freezing for vscode-server

### ISSUE THREAD

**Issue by N-McA** [microsoft/vscode-remote-release#1162]
In order to determine what code will run on a remote machine, it would be very helpful to freeze the version of vscode-server / fix the set of available binaries and prevent automatic downloading and installation.  

This would make it much easier to make a case for use on corporate networks, where arbitrary automatic updates will likely be frowned upon, and private corporate repositories are used for security purposes / IT likes to keep a handle on what people can install.

Is this on the roadmap? It seems like it should be possible primarily by removing features.

**Comment by N-McA** [comment]
Alternatively, this could be phrased as "Does vscode-server respect  {"update.mode": "none"} settings?

**Comment by egamma** [comment]
>"Does vscode-server respect {"update.mode": "none"} settings?
No

The remote extensions ensure that the VS Code Server version matches the version of the VS Code desktop version. 

To lock down the version of the VS Code Server you have to lock down the version of VS Code that connects to the server.

**Comment by N-McA** [comment]
Ah - that sounds like a fine solution to me. Is this noted anywhere in the official documentation?

**Comment by chrmarti** [comment]
Closing as this is already possible.
