### ISSUE TITLE
Server installment fails on untarring (unrecognized option, old tar version)

### ISSUE THREAD

**Issue by maciejmatczak** [microsoft/vscode-remote-release#1163]
Issue Type: <b>Bug</b>

Hello,
I have specific hosts. Default tar binary is really old and does not support argument used by instalator:
```
[13:11:25.829] > Download complete
> tar: unrecognized option '--strip-components'
```

I do have an access to other binaries, but I do not know if the flow currently supports any way modify the environment it is launched in. I tried to alias tar on my user with my rc files, but no luck.

Any help appreciated,

Maciej

Extension version: 0.45.5
VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
The environment wil be whatever you get when you run `ssh <host> 'echo $PATH'`. I think your `.bashrc` will be executed but not a `.profile`.

How old is your version of tar? Did you get it from some common linux distro or is this an unusual setup? Or can you share its manpage?

**Comment by maciejmatczak** [comment]
Hi @roblourens,
Hmm... ` ssh host 'tar --version' ` gives me 1.28 which should work with --strip-components. Should be fine. Does remote ssh enforce some specific shell, like bash especially?

Default tar is 1.13.25 from 2001.

**Comment by roblourens** [comment]
Yeah we are running a script in bash. I am going to look at this though, https://github.com/microsoft/vscode-remote-release/issues/1196
