### ISSUE TITLE
not connecting since windows update

### ISSUE THREAD

**Issue by rafipiccolo** [microsoft/vscode-remote-release#1164]
Used to work smothly, but then i did a windows update.
Now when i connect to a ssh server i get a cmd window saying (i never had it poping when it used to work) :
Runnin remote connection script
Acquiring lock...
found existing installation ...
found runing server
checking server status on port 40955 with wget

On the vscode output i get : "failed to parse remote port from server output".
ps: on the other computer with same config but update not done it still works.
ps: i tried to reinstall vscode. same error

**Comment by rafipiccolo** [comment]
maybe related to #1137

**Comment by roblourens** [comment]
Sounds the same as https://github.com/microsoft/vscode-remote-release/issues/1152
