### ISSUE TITLE
Reconnecting creates additional terminal panels "install" and "SSH Tunnel"

### ISSUE THREAD

**Issue by kylrth** [microsoft/vscode-remote-release#1166]
- VS Code version: 1.38.0-insider (user setup)
- Commit: microsoft/vscode@ba69d8dcccaebbfaa94906503728eb7c3e45b9c1
- Date: 2019-08-14T07:18:43.039Z
- OS: Windows_NT x64 6.3.9600 (Windows 8)
- Remote OS: CentOS Linux Release 7.4.1708
- Remote SSH version: 0.45.5
- Remote Extension/Connection Type: SSH

When I lock my computer with a remote SSH connection open, upon unlocking my computer VS Code attempts to reconnect to the remote computer. Often, once it does this, new terminal panels appear in the list of terminals. They're named "install" and "SSH Tunnel". Each time I lock and unlock again, the number of terminals increases. Reloading the window gets rid of the extra terminals.

Steps to Reproduce:

1. Connect to the remote workspace.
2. Lock the computer.
3. Unlock the computer.
4. Observe the new panels. If they don't appear, try again.

**Comment by roblourens** [comment]
You likely have `"remote.SSH.showLoginTerminal": true` set. That isn't needed for anything anymore and you can remove it. Let me know if that is not the case.

**Comment by kylrth** [comment]
I do not have that option set. This happens more often when I've been away from the computer for a while.

**Comment by roblourens** [comment]
And I assume you aren't clicking the "details" link while connecting, which would also cause them to show up. Hm...

Setting `"remote.SSH.enableDynamicForwarding": true` might help this. Also, this may already be fixed in the nightly version of the extension.

**Comment by kylrth** [comment]
I'll add `"remote.SSH.enableDynamicForwarding": true` and let you know if it happens again.
