### ISSUE TITLE
Prefix shell commands executed e.g. during run/debug with a space so they don't go to the shell history

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/vscode-remote-release#1168]
When I run/debug a file, VS code executes a command like this in the shell:

```
cd /home/adrian/dev/code-test/pkg2 ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /home/adrian/dev/code-test/.venv/bin/python /home/adrian/.vscode-server-insiders/extensions/ms-python.python-2019.8.30787/pythonFiles/ptvsd_launcher.py --default --nodebug --client --host localhost --port 42347 /home/adrian/dev/code-test/pkg2/test2.py 
```

However, this clutters my shell history with what can only be described as noise. Most shells\* provide a setting so commands starting with a space are not added to the history, so it would be nice if vscode prefixed anything it executes in a shell with a single space (maybe configurable in case someone wants to disable it)

---

\*Both [bash](https://unix.stackexchange.com/a/115922/2505) and [zsh](https://unix.stackexchange.com/a/6104/2505) (other shells probably too) provide this feature; probably other shells do this as well.

Some other tools that run shell commands (tmuxp for example) already make use of this.

**Comment by ThiefMaster** [comment]
@egamma What kind of "more info" is needed?

**Comment by egamma** [comment]
@ThiefMaster I did not save my comment, sorry.

Is your feature request specific to VS Code Remote or does it also apply to local development? I assume it is.

**Comment by ThiefMaster** [comment]
I never used vscode locally on Linux (since I don't use it as a Desktop OS), so I don't know if it also runs commands in a shell (instead of just running them via `exec()` etc.). But if it does run commands the same way locally then yes, it applies to local development at well.

**Comment by egamma** [comment]
The output you show above comes from an extension, so please file the issue against the corresponding extension.
