### ISSUE TITLE
Clean up message about IP address mismatch in remote known_hosts file

### ISSUE THREAD

**Issue by sjetha** [microsoft/vscode-remote-release#1170]
- VSCode Version: 1.37
- Local OS Version: Windows 10 (1903)
- Remote OS Version: Ubuntu 18.04.2
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
Complete steps are unknown, but the below will likely reproduce the issue
1. Create private and public keys for the local machine.
2. Add the public key to the remote machine.
3. Change the IP address of the local machine.
4. Attempt to connect to the remote machine using VS Code's Remote SSH tool.
5. Observe the exception found in the screenshot.

![image](https://user-images.githubusercontent.com/1066864/63105662-7eef4b80-bf3e-11e9-9be1-c7fa89a8e9aa.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
I can't reproduce this, and have fixed some issues with terminal escape codes showing up in the meantime. If you still see this, please include the log from the Remote-SSH output channel.
