### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by gcormier** [microsoft/vscode-remote-release#1172]
https://code.visualstudio.com/docs/remote/troubleshooting

## 1. Reusing a key generated in PuTTYGen
This doesn't work. Exported the key from puttygen as instructed, windows SSH reports:
` > Load key "C:\\Users\\xxx\\private.key": invalid format`

## 2. Improving your security with a dedicated key
On Windows 10:
````
C:\> ssh-keygen -t rsa -b 4096 -f %USERPROFILE%\.ssh\id_rsa-remote-ssh
unknown key type rsa
````

**Comment by Chuxel** [comment]
@gcormier Are you using the OpenSSH client for Windows 10 or something else? It's likely that these two errors are related and are tied to your SSH client version - potentially being out of date.

If you open a command prompt and type "where ssh" what does it tell you?

For example: `C:\Windows\System32\OpenSSH\ssh.exe`

**Comment by gcormier** [comment]
OpenSSH on Windows 10.

````
C:\Users\cormierg>where ssh
C:\Windows\System32\OpenSSH\ssh.exe
````

**Comment by gcormier** [comment]
![image](https://user-images.githubusercontent.com/8388983/63122906-cba24900-bf75-11e9-97ca-a874809d2030.png)

**Comment by Chuxel** [comment]
@gcormier That looks like one of the beta versions - old versions did not support RSA. See https://github.com/PowerShell/Win32-OpenSSH/issues/1001 Support for RSA was added sometime in 2018.

For comparison:

![image](https://user-images.githubusercontent.com/312252/63123141-34c99280-bf5d-11e9-9eac-e9f726934529.png)

**Comment by gcormier** [comment]
It's what Windows installed when adding the feature on 1709.

Not related to code so I will close and look into how I can update SSH.
