### ISSUE TITLE
Cannot Load VSIX from WSL

### ISSUE THREAD

**Issue by cookthebook** [microsoft/vscode-remote-release#1173]
Issue Type: <b>Bug</b>

While attached to a WSL session, try to install an extension from VSIX, navigate to the folder in your WSL, and select the VSIX file. VS Code will be unable to find the file.

Extension version: 0.39.2
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3400)|
|Memory (System)|15.93GB (8.81GB free)|
|VM|67%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3400)|
|Memory (System)|15.93GB (8.81GB free)|
|VM|67%|
</details>

**Comment by navarog** [comment]
Same thing... trying to install ms-vscode-remote.remote-wsl-0.39.3.vsix

But i get: Unable to install extension 'ms-vscode-remote.remote-wsl' as it is not compatible with VS Code '1.37.1'.

**Comment by vinser52** [comment]
Seems I have similar issue #1218

**Comment by sandy081** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/1027

**Comment by sandy081** [comment]
#1218 is not related
