### ISSUE TITLE
Can't connect ssh server

### ISSUE THREAD

**Issue by duyixian1234** [microsoft/vscode-remote-release#1174]
Issue Type: <b>Bug</b>

After upgrade VS Code today, when I use remote-ssh to connect my ubuntu server it keep

```
Setting up SSH Host duyixian.ubuntu.dev: Connect to VS Code Server
```

with 30+ times retry

and finally report a error with 

```
TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"ExhaustedRetries"},"measures":{"resolveAttempts":1}}
```

I *fix* it by run `rm -rf  ~/.vode-server` 

Extension version: 0.45.5
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.15.0-55-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.62GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: duyixian.ubuntu.dev|
|OS|Linux x64 4.15.0-55-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz (8 x 1999)|
|Memory (System)|31.41GB (23.52GB free)|
|VM|0%|
</details>

**Comment by Gu0Yu** [comment]
Yes! I got this

**Comment by roblourens** [comment]
@duyixian1234 If you see this again, please include the full log. Sorry you had trouble but I don't know what the problem was.

@Gu0Yu please open your own issue with some more details about what is happening. Seems the server download failed but I don't have more info.
