### ISSUE TITLE
Show progress bar when downloading / DnD via SSH

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode-remote-release#1176]
Downloading bigger files via SSH doesn't give any feedback. There should be a percentage progress bar somewhere.

**Comment by isidorn** [comment]
This is a fair feature request.
However currently we do not get the percentage progress back from the file service.
The best we can do is show the infinite spinner in the exlporer. And than this looks somewhat like this request https://github.com/microsoft/vscode/issues/73996
