### ISSUE TITLE
"Download" should download to temporary location first

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode-remote-release#1177]
It seems like DnD downloads to temporary location first and copies over but the "Download" command in the context menu saves to the final location immediately, which may be a problem for bigger files as people may try to open the file too early.

**Comment by isidorn** [comment]
I was not aware that dropping and "Download" gets content through a different location.
This is up to the file system implementation.

As for the Download first putting a file in a temporary location we will keep this open as a feature request.
