### ISSUE TITLE
WSL: Git extension disabled but SCM git working

### ISSUE THREAD

**Issue by vpereira01** [microsoft/vscode-remote-release#1178]
- VSCode Version: 1.37.1 (user setup)
- Local OS Version: Windows_NT x64 10.0.18362
- Remote OS Version: Debian GNU/Linux 9.9 (stretch)
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Open a git folder/repo in Windows  
2. Reopen folder in WSL 
3. Got an error saying that Atlassian.atlascode extension is disable because git extension is not loaded
4. Check @builtin extensions and git is disabled
5. Check source control and it shows git is active (git operations also work)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Seems related to #896 but in this case the git operations works. Maybe gitlens provides SCM features.

**Comment by sandy081** [comment]
Can you please run following command 

`F1 -> Developer: Show Running Extensions` 

and see if `git` extension is running or not?

**Comment by vpereira01** [comment]
The git builtin extensions now seems to be active... maybe I had some temporary issue.

I search again now I have found an open issue on the vscode extension for the real problem https://bitbucket.org/atlassianlabs/atlascode/issues/112/cannot-activate-the-atlassian-for-vscode

Closing this issue since the original problem seem to have disappear.
