### ISSUE TITLE
Add support for Docker Toolbox on Windows 7

### ISSUE THREAD

**Issue by Flyffies** [microsoft/vscode-remote-release#1179]
- VSCode Version: 1.13.1
- Local OS Version:
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Use docker toolbox on windows 7

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes (Because it is not related to any extentions, but to docker)

My windows 7 is unable to run dev containers using Docker Toolbox.
The Problem is a trivial one, docker does not recognise the paths to mount correctly.

Docker just can't handle the additional : in the path.
I copied the command and replaced the "c:\Users\..." with "\c\Users\..." and it worked.

![image](https://user-images.githubusercontent.com/6882791/63157161-97cb3000-c016-11e9-9165-d1ecca51b1d3.png)

A setting or something to format the paths in the later format would be great.

**Comment by egamma** [comment]
Docker toolbox is currently not supported, sorry.

**Comment by Flyffies** [comment]
Well, it would not need to be fully supported. Just an option to force a working path syntax would be enought.

**Comment by bamurtaugh** [comment]
Hey there, thanks for opening this issue. Support for Docker Toolbox is being tracked in https://github.com/microsoft/vscode-remote-release/issues/95, so closing this issue as a duplicate. If you have any other questions or feedback, please feel free to let us know. Thank you!
