### ISSUE TITLE
WSL: Add multi distro support

### ISSUE THREAD

**Issue by sulume** [microsoft/vscode-remote-release#118]
Issue Type: <b>Bug</b>

I have two WSL Apps installed via MS Store.  The command "Remote-WSL: New Window" always opens window with one of them without prompting which to use.

Thank you for all the efforts on the remote feature. I can't wait for this to be stable.

Extension version: 0.32.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.4.0-17134-Microsoft

**Comment by AngellusMortis** [comment]
It is probably openning your default instance. In PowerShell/CMD you can run `wslconfig /l` to see all of your installed WSL instances and which is the default. 

```
PS C:\> wslconfig /l
Windows Subsystem for Linux Distributions:
Arch (Default)
Ubuntu
kali-linux
```

You can then use `wslconfig /s <name>` to set a specific instance as default. For example, you can use `wslconfig /s Ubuntu` to set that instance as default.

I do agree, this would be a nice new feature to have.

**Comment by sulume** [comment]
Thank you for your advise. That worked. I could switch over to the other instance.

I see there's a global setting for the WSL default and this feature simply relies on it, so this is not really a bug. However I can touch only one instance at a time even with multiple windows, which is not very useful in practice. This issue would be a feature request.

**Comment by aeschli** [comment]
Yes, that's known, Multi distro support will be added in a future release.
