### ISSUE TITLE
Custom reconnect timeout

### ISSUE THREAD

**Issue by kdkavanagh** [microsoft/vscode-remote-release#1185]
From reading the other issues, it seems there is a timeout setting under the hood where VS Code will stop attempting to reconnect and instead ask you to reload the window.  My use case is that I leave work w/ my laptop for the day and come back in the morning, and see the prompt to reload the window.  This isn't a big deal for the file editor itself, but cause all terminal sessions and, in my case, a python interpreter to be lost.  This results in a long processes to reestablish what I had set up.

It would be great if the user could specify what that hard timeout is, or otherwise disable it such that VS Code always attempts to 'cleanly' reconnect until the user manually reloads the window

**Comment by roblourens** [comment]
I recommend using tmux for this. Then your terminals will survive losing internet, any amount of time, etc.

**Comment by kdkavanagh** [comment]
That does solve the issue for terminals, but not for extensions like vscode-python which create interactive windows.

Minimally, would be great to see this parameter be configurable - The remote extension does seem to work nicely after a disconnect/laptop sleep, so long as it's within the time window

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/3096
