### ISSUE TITLE
Keeps disconnecting and reconnecting 

### ISSUE THREAD

**Issue by kevinlu1211** [microsoft/vscode-remote-release#1186]
Issue Type: <b>Bug</b>

Logs from output
```
"install" terminal command done
Received install output: 4072fc8b-0a54-431e-bb1d-e43fe8f4d611==36305==
Server is listening on port 36305
Spawning tunnel with: ssh -t  "home" -L localhost:61958:localhost:36305 "echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity"
Spawned SSH tunnel between local port 61958 and remote port 36305
Waiting for ssh tunnel to be ready
Tunneling remote port 36305 to local port 61958
Resolving "ssh-remote+home" to "localhost:61958", attempt: 20
```

Extension version: 0.42.2
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: home|
|OS|Linux x64 4.15.0-43-generic|
|CPUs|Intel(R) Core(TM) i9-9940X CPU @ 3.30GHz (28 x 1200)|
|Memory (System)|125.61GB (8.52GB free)|
|VM|0%|
</details>

Also, don't know if this is relevant, but the Memory System for my server is wrong here is a `htop` screenshot:

![Screen Shot 2019-08-17 at 9 47 50 AM](https://user-images.githubusercontent.com/12663823/63203642-2fdb1f00-c0d4-11e9-8709-5a0a7fc0e567.png)

Also, even though it says attempting to reconnect in 5 seconds, I can dismiss the window, and even if I'm in a debug session the variables still persist, it is just annoying that I have to keep dismissing the window

**Comment by midacts** [comment]
I think this is the same thing I am running into.

Using this extension to connect into local containers keeps disconnecting.
If i reconnect it inevitably disconnects.

**Comment by roblourens** [comment]
You are using an old version of VS Code and the extension, can you try upgrading to the latest of each?
