### ISSUE TITLE
Reconnect after disconnect for save files

### ISSUE THREAD

**Issue by fakhamatia** [microsoft/vscode-remote-release#1187]
I change files and not save them, SSH disconnect and stuck in reconnecting and not reconnect again, files are open and not saved, how can I reconnect to save files? I don't see any button for reconnecting trying.

I open ssh in a new window and connected, but the first window not reconnect.

I click close SSH and show a message for saving files, "save all" did nothing.

- VSCode Version: 1.37.1
- Local OS Version: Ubuntu 18.04
- Remote OS Version: Xubuntu 18.04
- Remote Extension/Connection Type: SSH

**Comment by roblourens** [comment]
Sorry for the late response. Is this still an issue? If you can't reconnect please share the log from the Remote-SSH output channel.
