### ISSUE TITLE
Bad Owner or Permissions on %USERPROFILE%\.ssh\config file on Windows 10

### ISSUE THREAD

**Issue by bunnyvishal6** [microsoft/vscode-remote-release#119]
- VSCode Version: 1.34.0 insiders(user setup)
- Local OS Version:  Windows 10 1809
- Remote OS Version: Ubuntu 18.04 lts
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
When I try to connect this is the error 
Can't connect to VM-IP: unreachable or not Linux x86_64 (Bad owner or permissions on C:\\Users\\Bunny/.ssh/config). But vm is ubuntu 18.04 and x86_64. 

Here are my file permissions

![vscode-remote-1](https://user-images.githubusercontent.com/13260838/57178489-5f9c4900-6e8e-11e9-9c9c-c1b59b4c82d9.jpg)

![vscode-remote-2](https://user-images.githubusercontent.com/13260838/57178490-63c86680-6e8e-11e9-8898-acc24a4dc8e9.jpg)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bunnyvishal6** [comment]
According to this doc, the ./ssh/config file only user should have access to it.
![image](https://user-images.githubusercontent.com/13260838/57180217-2e2e7800-6ea4-11e9-815a-0f8ff36e9cd3.png),

Which is a contradiction to this doc
![image](https://user-images.githubusercontent.com/13260838/57180272-89606a80-6ea4-11e9-942b-1044abd7c29d.png)


--------------------------------------------------------------------------------------------------------
 So by removing all other permission entries from above list I can successfully run ssh from powershell or cmd but, cannot connect from vscode.

**Comment by murilogiatti** [comment]
![image](https://user-images.githubusercontent.com/38364583/57181352-d1fa3280-6e68-11e9-8aa8-0836f60cf95d.png)

It is working for me like this.
Just my user...

**Comment by bunnyvishal6** [comment]
@murilogiatti  .This is still not working for me

![image](https://user-images.githubusercontent.com/13260838/57181736-009dfa80-6eb5-11e9-8e11-4dd5ff4f12e5.png)

**Comment by murilogiatti** [comment]
![image](https://user-images.githubusercontent.com/38364583/57182276-a92b6a80-6e73-11e9-8e7b-99b86d790f86.png)

it is in the key file permissions, both private and public...

**Comment by bunnyvishal6** [comment]
@murilogiatti can I contact you in private?

**Comment by Chuxel** [comment]
@bunnyvishal6 Yeah, the permissions in the document are exactly how things are set up on my machine.  I suspect something else may be going on here.

**Comment by bunnyvishal6** [comment]
@Chuxel Vscode remote dev doc says we need to give full control to user, Administrator and system. But doing so I cannot connect ssh from cmd or powershell, it gives Bad owner or permissions error. And also cannot connect via vscode same error. But by removing all Principals from /.ssh/config file permissions list, I can connect via cmd or pwershell with a normal ssh command. As Win32-openssh config file should not have anyother people to access otherthan owner.

**Comment by Chuxel** [comment]
@bunnyvishal6 Windows unfortunately has lots of variations of the SSH clients that may be in your path.

If you're using the official Windows 10 OpenSSH install, there is a utility you can use to set permissions. https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/openssh/FixUserFilePermissions.ps1

Here's a snippet you can cut-and-paste in an administrator's powershell window to run it.

```powershell
Install-Module -Force OpenSSHUtils -Scope AllUsers
Repair-UserSshConfigPermission ~/.ssh/config
Get-ChildItem ~\.ssh\* -Include "id_rsa","id_dsa" -ErrorAction SilentlyContinue | % {
    Repair-UserKeyPermission -FilePath $_.FullName @psBoundParameters
}
```

If you still get an error, it's possible you're using a older or different version of the tools than

**Comment by bunnyvishal6** [comment]
@Chuxel, Did you get your setup working with this? I recently re installed win10. And the openSsh is the default one that comes with installation. And after installing above module, it says opensshutils.psm1 scripts are disabled. Is there a way to update openSsh client?

**Comment by Chuxel** [comment]
@bunnyvishal6 Don't install from the GitHub repo since that could be causing your problems - those are going to be development builds.  Use the version that ships with Windows 10.  It is known to work.  

You do not need to download the script.  Just run the following from an **administrator** power shell window.

```powershell
Install-Module -Force OpenSSHUtils -Scope AllUsers
Repair-UserSshConfigPermission ~/.ssh/config
Get-ChildItem ~\.ssh\* -Include "id_rsa","id_dsa" -ErrorAction SilentlyContinue | % {
    Repair-UserKeyPermission -FilePath $_.FullName @psBoundParameters
}
```

If you get an error, please post it - no way to know what is going wrong otherwise.

**Comment by bunnyvishal6** [comment]
I'm getting this error  when i try to run above commands in elevated powershell
![image](https://user-images.githubusercontent.com/13260838/57215233-e295de80-7009-11e9-9fe2-c229770a3c03.png)

**Comment by Chuxel** [comment]
@bunnyvishal6 Run:
```
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
```

...or if you want this to only apply to the current window...
```
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
```

**Comment by bunnyvishal6** [comment]
@Chuxel  Thanks a lot. It worked.

**Comment by Chuxel** [comment]
@bunnyvishal6 Great! Updated the docs to recommend this script.  Re: //build - Yeah we announced at PyCon last week but it's going to show up in a number of spots over the week!
