### ISSUE TITLE
Persistent Remote Plugins

### ISSUE THREAD

**Issue by smadgerano** [microsoft/vscode-remote-release#1190]
Not sure if this is possible, but it would be great to have some for of remote persistent plugin cache. I'm running VSCode and WSL on a very very low powered machine and have around 50 plugins for various things. Each time I load and connect I have to walk away for 15 minutes whilst everything loads up, and it does it for every connection, even changing folders on the remote host. Really frustrating.

**Comment by aeschli** [comment]
What does the WSL log show?

**Comment by smadgerano** [comment]
Thinking about this a bit more it might have something to do with the Setting Sync plugin I'm using. It's set to automatically run on startup and install anything that's missing.

I'm going to get in touch with the devs for Settings Sync, but still a little confused as the same "reloading" behaviour happens on both WSL and SSH remote connections, across all my machines and when changing folder.

Where would the logs you need be stored, locally in my VSCode folder or remotely on the WSL instance?

**Comment by aeschli** [comment]
The WSL log is shown when you invoke 'Remote WSL: Show Log' command. It's not persisted. It can tell you more about where the startup time was spent.
