### ISSUE TITLE
VSCode Remote SSH - Annoying terminal jump to long line

### ISSUE THREAD

**Issue by Manh-Toan** [microsoft/vscode-remote-release#1192]
When open new SSH project, I have to enter password 3 times; also recently, when entering password, the terminal automatically jump to a "long line" window, I have to select back to continue enter password.
![image](https://user-images.githubusercontent.com/54256000/63236347-93498600-c267-11e9-8251-a6ceb8bc99d7.png)

**Comment by egamma** [comment]
/needsMoreInfo

>jump to a "long line" window

can you elaborate what you mean by this? Can you illustrate using a screenshot

**Comment by Manh-Toan** [comment]
Dear @egamma ,
As you can see in the picture attached, there's the "long line" below "2. SSH Tunnel".
When I entered password 2nd times, the "2. SSH Tunnel" appeared then the "long line" appeared. I have to click on the drop box to select the "2. SSH Tunnel" a gain, to enter the last time pass-word.

Btw, I've tried the update of code-insider yesterday, this symptom not occurs anymore, and only 2 time enter pass-word needed.

I think I can resolve this issue.
Thanks
