### ISSUE TITLE
Find in Files with Workspaces and Remote-SSH

### ISSUE THREAD

**Issue by plantago** [microsoft/vscode-remote-release#1193]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Open a VSCode workspace file via the Remote-SSH
2. Activate Find in Files
3. Search for anything

Actual result:
Error message `spawn /home/USER-NAME/.vscode-server/bin/3652345724752746257435273/node_modules/vscode-ripgrep/bin/rg ENOENT`

Expected result:
A list of files where the string was found.

Note:
If a folder is opened via Remote-SSH then Find in Files works as expected.

Extension version: 0.45.5
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 5.0.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.51GB (9.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|44%|

|Item|Value|
|---|---|
|Remote|SSH: ubuntu-vm|
|OS|Linux x64 5.0.0-25-generic|
|CPUs|Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz (4 x 2712)|
|Memory (System)|7.76GB (3.35GB free)|
|VM|100%|
</details>

**Comment by roblourens** [comment]
Is it possible that one of the folders in your workspace doesn't exist?

**Comment by plantago** [comment]
Yes, you are right. There were 2 folders that did not exist.
Locally, missing folders do not lead to errors in `Find in Files`.

**Comment by roblourens** [comment]
There is an issue for this in the vscode repo
