### ISSUE TITLE
Access Denied 

### ISSUE THREAD

**Issue by rgillen** [microsoft/vscode-remote-release#1194]
VSCode Version: 1.37.1
Local OS Version: 18362.295
Remote OS Version: 4.4.0-18362-Microsoft Ubuntu
Remote Extension/Connection Type: WSL

**Steps to Reproduce:**

- Launch VS Code
- Open/Folder Workspace
- Open Terminal
- Run: `sudo su - <username>`
- Run (command pallet): `Reopen Folder in WSL`
- Attempt to add/edit a file/folder using the VS Code IDE

**Result:**
➜ Error: EACESS - Permission Denied

Upon Additional Investigation the Following was Discovered

- RUN (command pallet): `Remote-WSL: Show Log`

Starting server: /home/**<<< REDACTED >>>**/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/server.sh  --port=0 --fileWatcherPolling=5000

**<<< REDACTED >>>** = Default WSL Ubuntu User (NOT the User from: `sudo su - <username>`

Running the following command and then repeat the steps from above:

- RUN (Windows CMD): `ubuntu config --default-user <username>`
- Close/Reopen VSCode Folder/Workspace
- Open Terminal
- Run: `sudo su - <username>`
- Run (command pallet): `Reopen Folder in WSL`
- Attempt to add/edit a file/folder using the VS Code IDE

**Result:**
➜ It Works! This time there is no EACESS error

**Conclusions**

- Changing the 'Default' Ubuntu user every time I open a new project is cumbersome, many times I will have multiple VSCode projects open simultaneously; each client work-space uses its own WSL user (keeps ssh/aws access keys separate per client)

- If the Default WSL User had Write access to the File/Folder this issue would go away. This is the solution for #1008 - in my case this is not appropriate as the various WSL users rightfully do not share write access to the same directories.

- Remote WSL Extension calls the default distribution (Ubuntu in my case) directly, passing in a sub-command to start the WSL Server. This appears to be independent of the terminal initialization within VSCode. `wsl.exe` supports a `-u` flag to specficy the WSL user to execute the command with. I was able to resolve my issue by adding this flag when launching `wsl.exe` from `wslDaemon.js`. The <username> value is obtained from a custom setting I added, aptly named `remote.WSL.username`

**Comment by aeschli** [comment]
You are asking for multi user support: https://github.com/microsoft/vscode-remote-release/issues/286

For that we need to store the user in the remote URL as well.
