### ISSUE TITLE
Remote-ssh: Support confirming authenticity of remote host

### ISSUE THREAD

**Issue by robertlugg** [microsoft/vscode-remote-release#1195]
This request could be solved in a similar way to what apparently was done for microsoft/vscode#23855

When connecting to a host for the first time using Remote-ssh, the connection "fails".  This is because I've never connected this computer to that host.  The message is similar to:
```
[16:41:39.884] Running script with connection command: ssh -o ClearAllForwardings=true ltgrd-gpu1 bash
[16:41:39.885] Install and start server if needed
[16:41:40.038] > 
[16:41:40.038] Got some output, clearing connection timeout
[16:41:40.164] > The authenticity of host 'abc (1.2.3.4)' can't be established.
> ECDSA key fingerprint is SHA256:aWholeBuNcHofChaRacTERs.
> Are you sure you want to continue connecting (yes/no)?
[16:41:50.493] "install" terminal command canceled
[16:41:50.493] Install terminal quit with output: 
[16:41:50.493] Received install output: 
[16:41:50.493] Failed to parse remote port from server output: 
[16:41:50.493] 
[16:41:50.494] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"UnparsableOutput"},"measures":{"resolveAttempts":1,"retries":1}}
[16:41:50.494] ------
```
The there is an interactive prompt to confirm that I trust the remote host but the script just fails.  Instead, add some feature to allow me to say Yes or No.  microsoft/vscode#23855 seems to be what VSCode did for other connections.

**Comment by roblourens** [comment]
> The there is an interactive prompt to confirm that I trust the remote host but the script just fails. 

So you are seeing a box pop up with this message right? And you pick "yes" but it does not continue? Or are you saying that's what _should_ happen? This is supposed to be handled but unfortunately I don't log if it does...

**Comment by robertlugg** [comment]
It should popup but does not.  There is no chance to type 'yes'.

**Comment by roblourens** [comment]
This is confusing. I will have to add some logging around here. You should be able to work around it by connecting from a terminal first and accepting the host fingerprint.

**Comment by roblourens** [comment]
Added some logs that will be in tomorrow's nightly build if you would like to try it again and see where the dialog went.

**Comment by robertlugg** [comment]
It looks good.  Sorry for my long delay.  Confirmed that this works nicely on
```
Version: 1.39.0-insider (user setup)
Commit: b7a5b7cf39f569a570599530ffc855b454e37b06
Date: 2019-09-12T08:47:28.947Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134
```

**Comment by pauloyster** [comment]
It seems that the vanishing popup is back from the dead in the latest version:

Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by roblourens** [comment]
Really weird. Is there something else going on at the same time that might make the dialog hide, like another dialog popping up at the same time? Do you see it flash, any way you can record a video of it? All I know is that we show the quick pick and it apparently fires its `onDidHide` event immediately after.

**Comment by pauloyster** [comment]
Video here:
https://www.dropbox.com/s/ztnl1hkumpx5vdn/VSCode%20SSH.mp4

Note that it didn't capture the ['Close Remote' / 'More Actions...', 'Retry' ] message box on the screen (that pops up immediately when the yes/no vanishes from the upper edge of the screen.

**Comment by roblourens** [comment]
Oh, I see the issue...

**Comment by roblourens** [comment]
Please try this in tomorrow's nightly build (in about 11 hours)

**Comment by carmeli-tamir** [comment]
Similar effect after updating. When can I expect a version update?

> osboxes@127.0.0.1's password:
[04:41:04.386] Showing password prompt
[04:41:09.561] Password dialog canceled
[04:41:09.561] "install" terminal command canceled
[04:41:09.562] Resolver error: Connecting was canceled
[04:41:09.564] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"Canceled","askedPw":"1","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","gotUnrecognizedPrompt":"0","remoteInConfigFile":"1"},"measures":{"resolveAttempts":1,"retries":2}}
[04:41:09.566] ------

**Comment by roblourens** [comment]
Please open a new issue and include the whole log. In your case it looks possible that the password prompt was actually canceled (did you press esc while connecting?)

**Comment by pauloyster** [comment]
Looking good in current version, thanks!

Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
