### ISSUE TITLE
[Docker Compose] Apply overrideCommand with remote Docker Compose

### ISSUE THREAD

**Issue by jlost** [microsoft/vscode-remote-release#1200]
Hi, I noticed when using Docker Compose (specifying a `dockerComposeFile` in `.devcontainer.json`, the command in the specified `service` is not overridden. Would it make sense to do this? I find it confusing that `overrideCommand` is a valid option at the same level as `dockerComposeFile`, and yet it has no effect in certain circumstances. If the `overrideCommand` were truly only valid when a `dockerFile` were specified, maybe it should be nested into another level of options.

**Comment by jlost** [comment]
For clarity, here is my configuration. The `command` that is specified in the `app` service of `docker-compose.yml` is not overridden.

```
{
	"dockerComposeFile": "docker-compose.yml",
	"service": "app",
	"workspaceFolder": "/usr/src/app",
	"extensions": [],
	"overrideCommand": true
}
```

**Comment by chrmarti** [comment]
The docker-compose.yml can control the command that is run. We could look into using a docker-compose.yml fragment to override the command, but maybe we're better off leaving that up to the user in the Compose case, like we do with the mounting of the source folder.

**Comment by jlost** [comment]
Fair enough, and that is how I ended up doing it. It works well, I just thought it would be more convenient to do it directly in the settings, especially since users wouldn't have to look up the sleep command to copy-paste.
For reference, here is my fragment:
```
version: "3"

services:
  app:
    entrypoint: ""
    command: /bin/sh -c "while sleep 1000; do :; done"

```

**Comment by chrmarti** [comment]
Adding this. Note that the default will be false for backward compatibility.
