### ISSUE TITLE
Cannot Initialize VS Code Server on remote machine using the remote-SSH extenstion

### ISSUE THREAD

**Issue by deepakiim** [microsoft/vscode-remote-release#1202]
- VSCode Version:1.37.1
- Local OS Version:Ubuntu 18.04.3
- Remote OS Version:Ubuntu 18.04.1
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. When I connect to remote server using Vscode, it saying `Setting up SSH Host GPUMACHINE: Initializing VS Code Server`
When I check the log in the terminal, I see the below log and it get stuck at this point even after waiting for 1 hour. 

```
Running remote connection script
Acquiring lock on /home/ubuntu/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/vscode-remote-lock.f06011ac164ae4dc8e753a3fe7f9549844d15e35
Installing to /home/ubuntu/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35...
Downloading with wget

```
when I  login to the same machine using putty, I and try to wget a file from internet, it downloads the file from internet. So doesnt look like a internet access issue

**Comment by sali0** [comment]
Having the same issue with local OS being Windows 10.

**Comment by lucasexe** [comment]
Same error using: Windows 10 + CentOS 7

In my case, the download fails but the script continues without checking the downloaded file causing errors in next steps:

```
[15:57:01.159] remote-ssh@0.45.6
[15:57:01.159] win32 x64
[15:57:01.161] SSH Resolver called for "ssh-remote+vdi2-sj", attempt 1
[15:57:01.161] SSH Resolver called for host: vdi2-sj
[15:57:01.161] Setting up SSH remote "vdi2-sj"
[15:57:01.217] Using commit id "20dd80d91a76cbe80fb1d1979c3a9f02d94ba161" and quality "insider" for server
[15:57:01.222] Testing ssh with ssh -V
[15:57:01.559] ssh exited with code: 0
[15:57:01.559] Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[15:57:01.560] Running script with connection command: ssh -o ClearAllForwardings=true vdi2-sj bash
[15:57:01.565] Install and start server if needed
[15:57:02.019] > 
[15:57:02.019] Got some output, clearing connection timeout
[15:57:05.721] > Running remote connection script
> 
[15:57:05.812] > Acquiring lock on /home/lmartins/.vscode-server-insiders/bin/20dd80d91a76cbe80fb1d1979c3a9f02d94ba161/vscode-remote-lock.20dd80d91a76
> cbe80fb1d1979c3a9f02d94ba161
> Installing to /home/lmartins/.vscode-server-insiders/bin/20dd80d91a76cbe80fb1d1979c3a9f02d94ba161...
> Downloading with wget
> 
[15:57:07.783] > Download complete
> tar: unrecognized option '--strip-components'
> Try `tar --help' for more information.
> WARNING: tar exited with non-0 exit code
> WARNING: /home/lmartins/.vscode-server-insiders/bin/20dd80d91a76cbe80fb1d1979c3a9f02d94ba161/node doesn't exist. Download/untar may h
> ave failed.
> WARNING: /home/lmartins/.vscode-server-insiders/bin/20dd80d91a76cbe80fb1d1979c3a9f02d94ba161/server.sh doesn't exist. Download/untar
> may have failed.
> 
```

**Comment by RebornL** [comment]
Have you solved this problem?

**Comment by roblourens** [comment]
Is this still an issue? Do you have a proxy set up on the remote?

**Comment by deepakiim** [comment]
> Is this still an issue? Do you have a proxy set up on the remote?

No Proxy is not setup on the remote.

**Comment by roblourens** [comment]
Here is something you could try

- Install the nightly version of the extension (uninstall the stable version)
- Set `"remote.SSH.allowLocalServerDownload": true`

See if it works in that mode

**Comment by sali0** [comment]
Tried adding new nightly version with "remote.SSH.allowLocalServerDownload": true and still does not work. It is stuck at wget.

**Comment by roblourens** [comment]
Can you share the log too?

**Comment by sali0** [comment]
```
>[21:14:39.316] > wget download failed
> ...
> ...
> Trigger client server download
> VSCODE_ARCH==x64==
> ccd10a87-0c11-4028-a56b-e76089a84e68__trigger_vscode_server_download__
> Waiting for client to transfer server archive...
> Waiting for /home/users/.../.vscode-server/bin/3db7e09f3b61f915d03bbfa58e258
> d6eee843f35/vscode-scp-done.flag and vscode-server-linux-x64.tar.gz to exist
> 
>[21:14:39.316] Got request to download on client for x64
>[21:14:39.545] Failed to download VS Code Server: HTTP 403 - HostBrowserBlocked
>[21:14:39.545] ------

This is the error I got (had to cut out some parts). My last reply was wrong, it did get past wget, but it terminated with HTTP 403 - HostBrowserBlocked. I suspect this is an issue internally though with our own networks. I will try to get back with an update.

**Comment by roblourens** [comment]
No idea why you would get that error. Anything you can tell me about the network that you are downloading from would help. I assume that you were able to download vscode from the website fine on this network.

**Comment by sali0** [comment]
I think this is caused by being behind Invincea protection. This is something I'll have to speak with our system admins about. Thank you for your help, I hope to use this extension soon.

**Comment by roblourens** [comment]
Thanks, will close for now, please follow up if you learn anything that vscode can help with.

**Comment by sali0** [comment]
Is there any possibiilty of adding the option to install the VSCode remote extension server manually? The reason it isn't working here is because we have a firewall that only allows the web browser and select few other programs to connect to the internet. Getting permissions to allow anything else has been disallowed.

There are also completely offline labs that, with this feature, we could use the remote extension in.

**Comment by roblourens** [comment]
Try setting this: `"remote.SSH.allowLocalServerDownload": true`

**Comment by sali0** [comment]
This is the option I tried with my response from last week. It tells me > wget download failed and throws the error HostBrowserBlocked.

Like I said, I believe this is an issue with the firewall on my side. I was alluding to an option to setup the remote extension server manually, as in downloading the tar manually and setting it up on the server myself, rather than having the extension try to do so.

**Comment by roblourens** [comment]
Sorry, I missed that it is failing on the client too.

There is an issue tracking for allowing the user to download the server manually: https://github.com/microsoft/vscode-remote-release/issues/1242
