### ISSUE TITLE
Tasks fail in containers when alternate shell is used locally (due to that shell not being in container)

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#1203]
In short - terminal windows use the remote user's default shell.  Tasks use the local user's default shell. Both should use remote.

This may also happen on other platforms, but is most likely to occur on Linux - particularly given the popularity of alternate shells there. It may also happen with Remote - SSH, but the alternate shell is very likely to actually be there in that case (since zsh is in many default distros). As macOS transitions to zsh by default, it will start happening more there.

Repro:
1. Set up a Linux machine with `zsh` as your default shell (`chsh -s /bin/zsh`) - you may need to sign out and in again.
2. Clone and open the `javascript-node-lts` dev container definition from vscode-dev-containers **locally**
3. Pop open a new terminal - note you are in `zsh`
4.  Reopen Folder in Container
5. Open a new terminal - Note you are correctly in `bash` since this is the default for the remote user.
6. Press <kbd>F5</kbd>

**Expected:** `npm` pre-launch task succeeds
**Actual:** Task fails saying "The terminal shell path "/usr/bin/zsh" does not exist"

//cc: @chrmarti

**Comment by alexr00** [comment]
The problem happens here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/terminal/node/terminal.ts#L35
Since the platform is still Linux, and that code is run in the renderer we incorrectly get the local system shell, not the remote.

**Comment by alexr00** [comment]
It looks like this might be a tough bug. You should be able to work around it for now by setting 
`	"terminal.integrated.automationShell.linux": "/bin/bash"`

**Comment by chrmarti** [comment]
@Chuxel Should that be `"terminal.integrated.automationShell.linux"`? Do we want to distribute the workaround with the configuration? That will stay around after a fix went in.

**Comment by alexr00** [comment]
I fixed this for tasks, but @Tyriar this seems like it could still be a bug in terminal.

**Comment by Tyriar** [comment]
I don't think this is a problem in the terminal, when the linux.shell setting isn't set it then `null` will be passed over to the ext host which then evaluates it. This was fixed about 3 months ago for the terminal.

**Comment by Chuxel** [comment]
@alexr00 @Tyriar Yeah terminal seemed to be working, it was the tasks that were not.  I stuck with the property above purely to make it easier for customers to change both to a different shell if they installed it.

**Comment by alexr00** [comment]
@Tyriar, the issue is that the terminal instance service isn't passing over to the extension host for `getDefaultShellAndArgs`.

**Comment by Tyriar** [comment]
@alexr00 yep, that's only used in the local case. It's a little different to other parts because we're still supports processes on the renderer.
