### ISSUE TITLE
Dev containers are no longer shutting down when window is closed or another folder is opened

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#1205]
Version: 1.38.0-insider (user setup)
Commit: c8d44e24dd250d416475a10efe64e35c9e2c65b3
Date: 2019-08-19T12:53:53.607Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

I'm seeing dev containers stay running after the window is closed or you switch to a local folder. 
 I also see this in stable, so not sure when the problem hit - I just happen to be switching between containers that used the same port today and noticed it.

Repro:
1. Open a folder in a container
2. Reopen folder locally or just close the window

**Expected:** Running`docker ps` shows the dev container is shut down
**Actual:** The container is still running

//cc: @chrmarti

**Comment by bestickley** [comment]
I'm having this issue too

**Comment by chrmarti** [comment]
@Chuxel The code around this hasn't changed for a while, so this is likely a change in timings on your machine making it hit the timeout after which the extension host is terminated. One thing we can try is use `runCommandInDetachedProcess` like we do for Docker Compose - of course that wouldn't help if the extension host never gets to the point of shutting down our extension.

Have you by any chance installed extensions that take time to shutdown? I think the timeout before the extension host is terminated is a global one.

**Comment by Chuxel** [comment]
@chrmarti They stay running pretty much forever.  It's possible something changed with Docker since there was a major version update lately to the Docker engine that broke things.  (From 18.06 to 19.03)

I even see it with the basic vscode-remote-try-node repo.

**Comment by chrmarti** [comment]
@Chuxel Do you also see it with a Docker Compose setup?

**Comment by Chuxel** [comment]
@chrmarti Yep - This is on:

Version: 1.38.0-insider (user setup)
Commit: e77b008fb04222192a608906ff603bd72943d779
Date: 2019-08-30T10:15:17.547Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

and v 0.72 of the extension.

Docker is latest stable:
![image](https://user-images.githubusercontent.com/312252/64030753-0bcc0480-cafc-11e9-9d81-cb3fe67d2b5a.png)

**Comment by Chuxel** [comment]
@chrmarti Ah ha! One more thing.  I have multiple windows open.  I just noticed that if I start up **only** the compose container and close it shuts down.

What I've started doing is testing the new containers explorer so I have a separate window open with the explorer -- that may be why I didn't notice earlier.

**Comment by chrmarti** [comment]
Could you try with all extensions but Remote-Containers disabled?

**Comment by Chuxel** [comment]
After updating this morning to the latest insiders and v0.73 of the extension and it no longer appears to repro!

Closing for now - will reopen if it starts happening again in a specific scenario.

**Comment by chrmarti** [comment]
Tracked it down to the extension host being terminated 5 seconds into the shutdown phase to keep extensions from holding back the shutdown. Working on a fix.

**Comment by chrmarti** [comment]
Fixed for September and available in VS Code Insiders with 0.75.0 of the extension.
