### ISSUE TITLE
Remote Development on Raspberry Pi

### ISSUE THREAD

**Issue by akoenig** [microsoft/vscode-remote-release#1206]
I built the latest tag on Raspbian successfully. Due to the fact that the Marketplace is not available in the OSS version, I tried to install the Remote SSH extension manually. The installation works as expected.

Unfortunately, when executing `Remote-SSH: Connect to Host...` I get:

```sh
command 'opensshremotes.openEmptyWindow' not found
```

The Raspberry Pi 4 is powerful enough to render `vscode`, but have an even more powerful compute environment in the Cloud. Therefore, there is so much potential in this kind of use case.

So in fact, I have two questions:

- Any chance to run the `Remote SSH` extension within the `OSS version` of `vscode`?
- ... and if not: Is there any chance to get a RPi compatible version of the actual `vscode` distribution (with Marketplace and Remote Extension integration)?

That would be a dream :slightly_smiling_face:

**Comment by Chuxel** [comment]
@akoenig Breaking this up into two issues:

1. You can use VS Code Insiders to connect to a Raspberry PI running a 32-bit OS (e.g. Raspbian) using the Remote - SSH extension now (it's just not stable yet).  AARCH64 is planned as well. 

2. Full VS Code on RPi is tracked here so please up-vote if you are interested: https://github.com/microsoft/vscode/issues/6442

**Comment by egamma** [comment]
@Chuxel comment provides the answers, closing.

**Comment by akoenig** [comment]
@Chuxel Thanks for your response. Yes, I saw that connecting to a Raspberry Pi is possible. My use case refers more or less to the second point. I want to use the RPi 4 as a thin client connecting to a server in the cloud. I up-voted the referenced issue. Any chance to estimate an ETA for official RPi builds?

I mean, there is huge potential (especially in the education sector).

**Comment by Chuxel** [comment]
@akoenig We don't have a specific ETA for this, but given what you describe, you may be interested in [signing up for the private preview](https://aka.ms/vsfutures-signup) of the upcoming browser-based "Web Companion".  You can read more about what is planned at https://online.visualstudio.com
