### ISSUE TITLE
Install Local Extensions toolbar action does not prompt for the extensions to install

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#1213]
The 'Install Local Extensions' Command prompt the user for which locations should be installed.

The 'Install Local Extensions' shown in the toolbar installs all local extensions immediately without a prompt. There should be a prompt, since by default all the extensions that will be installed are not in view in the extensions viewlet, that is, you have to scroll to the bottom of the view.

![image](https://user-images.githubusercontent.com/172399/63339872-21943980-c346-11e9-985b-7001e66a29fb.png)

**Comment by sandy081** [comment]
Same action in recommendations also does the same -> Installs it without any prompt.

But I think it is better to show the selection picker here so that user can choose and install. Now the action in the toolbar also show the picker to select extensions to install.
