### ISSUE TITLE
Different webview server and extention host agent

### ISSUE THREAD

**Issue by dawidstezycki** [microsoft/vscode-remote-release#1214]
The problem is that when I try to run VSCode Remote on remote host it installs fine but when it comes to running server it throws this output:

```
> Starting server...
> 
[11:38:45.883] > Waiting for server log...
> 
[11:38:46.563] > Waiting for server log...
> 
[11:38:47.193] > Waiting for server log...
> 
[11:38:47.812] > Waiting for server log...
> 
[11:38:48.342] > Waiting for server log...
> 
[11:38:48.975] > Waiting for server log...
> 
[11:38:49.511] > 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
[11:38:49.688] > Server did not start successfully. Full server log >>>
> 
[11:38:49.727] > <<< End of server log
> 
[11:38:50.773] "install" terminal command done
[11:38:50.774] Install terminal quit with output: <<< End of server log
[11:38:50.774] Received install output: <<< End of server log
[11:38:50.774] Failed to parse remote port from server output: <<< End of server log
[11:38:50.774] 
[11:38:50.775] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"UnparsableOutput"},"measures":{"resolveAttempts":1,"retries":1}}
[11:38:50.775] ------
```

I looked in the log file in vim and that's the content:

```
* Visual Studio Code Server
* Reminder: You may only use this software with Visual Studio family products
* as described in the license https://aka.ms/vscode-remote/license
*
webview server listening on 36939
Extension host agent listening on 37934
```

It seems that the last two lines are the problem but I don't know enough about it to say for sure.

- VSCode Version: 1.37.1
- Local OS Version: Windows 10 Enterprise, Version: 1709, Build: 16299.1268
- Remote OS Version: Red Hat Enterprise Linux Server release 7.4 (Maipo)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to a remote host for the first time

**Comment by WSLUser** [comment]
> Local OS Version: Windows 10 Enterprise, Version: 1709, Build: 16299.1268

You might be better off enabling WSL and using the Remote-WSL extension. You could always ssh to the RHEL server from WSL.

**Comment by dawidstezycki** [comment]
What's the difference between ssh-ing from Windows and WSL? I want to use VSCode remote because I want to develop on the remote host with the right environment.

**Comment by WSLUser** [comment]
yes, I was suggesting WSL as an alternative to using ssh. The difference is with WSL, you install a distro locally from the Store (or get the offline appx from MS Docs). Basically it removes your need to develop "remotely". You can use sync using git if you need the source code on the RHEL server.

**Comment by dawidstezycki** [comment]
Well, I can't build it locally and I know how to sync the files. That's the exact thing that I want to avoid by using VSCode remote.

**Comment by WSLUser** [comment]
Here's the docs. You shouldn't need to do any syncing. I was just suggesting you could if you still wanted to. https://code.visualstudio.com/docs/remote/wsl

**Comment by dawidstezycki** [comment]
Thanks, but you don't answer my question and I have reasons to do it the way I want to, so please let me wait for the solution to my problem.

**Comment by dawidstezycki** [comment]
The problem seems to have resolved itself overnight. I have no idea why but for now I have to close it as it's not reproducible.
