### ISSUE TITLE
Group "Attach" actions closer together

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#1215]
In this case:

![image](https://user-images.githubusercontent.com/900690/63329609-8c3b7a00-c332-11e9-8025-06994c2f05af.png)

I suggest to have the "Attach" actions grouped together.

**Comment by egamma** [comment]
The corresponding group in the docker view would be `containers_1_general@2`

**Comment by egamma** [comment]
Fixed by https://github.com/microsoft/vscode-remote-containers/commit/ac48b24f3fea251c73b456e0c5af40a07b02dc43
