### ISSUE TITLE
Cannot login to GitHub

### ISSUE THREAD

**Issue by Quintuplin** [microsoft/vscode-remote-release#1216]
Issue Type: <b>Bug</b>

On clicking on the 'syncronize changes' icon, the 'ask for github login credentials' popup appears as expected. however, completing the login with password fails due to 2fa, and completing the login with an access token exits with no error message, but does not successfully complete the login process

Extension version: 0.39.2
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (10.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aeschli** [comment]
Is this on WSL?

I assume you mean git credential.

I just tried today with the oauth token as user name and that worked.

Another thing you can try is to configure to use the Windows credential manager also in WSL:
In a WSL shell type: 
```
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager.exe"
```

**Comment by Quintuplin** [comment]
ran the shell command, and it worked perfectly, immediately.

thank you!
