### ISSUE TITLE
Stuck on "Attempting to reconnect…" after waking from sleep

### ISSUE THREAD

**Issue by darknoon** [microsoft/vscode-remote-release#122]
I put my laptop to sleep last night after testing out Remote w/ SSH to a server on the local network `ml-dev-box`, and when I woke it up this morning VSCode is stuck on "Attempting to reconnect...". I'm not sure what debugging logs I should send you, but I can leave it in this state to debug.

- VSCode Version: Version 1.34.0-insider (1.34.0-insider)
- Local OS Version: macOS 10.14.4 (18E226)
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to remote, do some stuff
2. Close laptop, wait 8hours
3. Wake laptop

It doesn't really seem to be trying to reconnect, since I am able to ssh normally into the server in my normal Terminal.app.

<img width="1392" alt="Screen Shot 2019-05-04 at 11 59 38" src="https://user-images.githubusercontent.com/355540/57181609-1a632180-6e64-11e9-82d6-e4ac87a7fa5d.png">

**Comment by roblourens** [comment]
After 8 hours, reconnection should fail and prompt you to reload the window.

Can you paste the contents of the `Remote - SSH` output channel?

**Comment by darknoon** [comment]
@roblourens I will do that next time! I am sorry, I closed that window but I now know where the debug info is.

**Comment by roblourens** [comment]
And it's possible that log will be cleaned up, please also check the dev tools under (Help > Toggle developer tools)
