### ISSUE TITLE
Consider security implications of SSH agent forwarding

### ISSUE THREAD

**Issue by rgov** [microsoft/vscode-remote-release#1222]
#1158 describes enabling SSH agent forwarding by default.

There are security risks with agent forwarding. The remote server could ask the client's agent to authenticate to a third service without user intervention.

For instance, suppose an attacker compromises an EC2 instance on Amazon, and wants to pivot by modifying a source file on GitHub. The attacker waits for an unsuspecting developer to fire up VS Code and connect to the virtual machine to edit some file.

VS Code connects and silently enables agent forwarding. Now the attacker can talk directly to the developer's local agent, and asks it to authenticate to GitHub. The attacker sneakily pushes a commit that introduces a backdoor.

I'm not sure if there is a currently a way to get the `vscode://` URL handler to initiate a remote connection, but if there is (or it is later added), this could also be used as a way to force/convince a developer to connect to an attacker's server, where the developer's agent can be abused.

I hope that this risk is considered when implementing this feature. Agent forwarding is OK for a host that the user trusts has not been compromised. But I don't believe it should be enabled always.

**Comment by roblourens** [comment]
Thanks for pointing this out, but when I say "enable by default", I actually just mean enabling the code that makes it work __iff the user has already enabled it for the host by setting `ForwardAgent` in their SSH config__. We will never forward the agent by default unless the user has opted into it, for exactly the reasons you mention.
