### ISSUE TITLE
"handshake timeout" when reconnecting

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1224]
Sometimes when going through reconnection, I see an infinite "attempting to reconnect" and the EH has gone down. When this happens, in the devtools console I see `"handshake timeout"`.

I see https://github.com/microsoft/vscode/blob/e558dc6ea73a75bd69d7a0b485f0e7e4194c66bf/src/vs/platform/remote/common/remoteAgentConnection.ts#L123-L125

I think that when I open my laptop lid and MacOS is deciding whether or not it is connected to the internet, there is a period when I am connected long enough for the resolver to connect but then the connection is slow or goes away for a couple seconds, and the handshake times out when it could have succeeded. I think this is a weak point in reconnection and maybe this timeout should be longer, or maybe that error should kick us back into the reconnection loop.

**Comment by alexandrudima** [comment]
I could reproduce by adding an artificial delay in code

**Comment by roblourens** [comment]
Sorry I totally forgot about https://github.com/microsoft/vscode-remote-release/issues/1130

**Comment by roblourens** [comment]
I have not seen this recently
