### ISSUE TITLE
port not released and cannot kill the process

### ISSUE THREAD

**Issue by marchers** [microsoft/vscode-remote-release#1225]
HI, 

An error ocurred when I was debugging my dotnet code and the terminal stop ped the process. However, when I tried to execute `dotnet run` again, I was told that the port 5000 was being used. 
by using the command I could not kill the process

```
lsof -i:5000
kill pid
```

At last, I restarted my vs code and the issue was resolved.

---

CPUs | Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 7.82GB (1.62GB free)
Process Argv | --folder-uri vscode-remote://ssh-remote%2B{my ip}/home/tcma/code/cop
Screen Reader | no
VM | 0%

Remote | SSH: {my ip}
-- | --
OS | Linux x64 5.0.0-25-generic
CPUs | Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (4 x 1137)
Memory (System) | 15.57GB (1.06GB free)
VM | 0%

**Comment by roblourens** [comment]
This sounds like an issue either with your code, or with the C# debugger. Please file this on the C# debugger repo.
