### ISSUE TITLE
No SSH hosts have been configured yet

### ISSUE THREAD

**Issue by 1016990109** [microsoft/vscode-remote-release#1226]
- VSCode Version: 1.37.1
- Local OS Version: macOS 10.14.6
- Remote OS Version: 
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1. Configure a SSH host
2. set config:
```
Host AliServer
	HostName 1.1.1.1 # 填写远程服务器的IP或者Host
	User     username # 填写登陆远程服务器的用户的名字
```
3. save
4. refresh CONNECTIONS
5. no changes

![image](https://user-images.githubusercontent.com/7438952/63497892-5e536280-c4f7-11e9-853c-de6b68ef5a7b.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by roblourens** [comment]
Not sure what the problem is. Can you open the ssh config and find the log in the Remote-SSH output channel and share that here?

Also, do you see any errors in the devtools console? (Help > Toggle developer tools)

**Comment by 1016990109** [comment]
> Not sure what the problem is. Can you open the ssh config and find the log in the Remote-SSH output channel and share that here?
> 
> Also, do you see any errors in the devtools console? (Help > Toggle developer tools)

The ssh config:
```
Host AliServer
	HostName 9.154.15.52
	User     root
```
But I can't find any SSH hosts in the 'REMOTE-SSH' side bar, it shows 'No SSH hosts have been configured yet.Configure a SSH host'.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/7438952/63747795-8f0e1000-c8da-11e9-922f-4c54b652bfa4.png">

And I can't see any errors in the devtools console.

**Comment by 1016990109** [comment]
Thank you! It works now after using an absolute path. @roblourens

**Comment by roblourens** [comment]
Hm, the ~ should work, so is there something weird with your user directory? If you do 

```
cd ~
pwd
```

in a terminal, what do you see?

**Comment by 1016990109** [comment]
Yes, I can see "aigate_dev_config" in ~/.ssh directory. But when I use "~", I can't find any hosts in the side bar.

**Comment by roblourens** [comment]
If you have node installed on your computer, could you try running `node -p "require('os').homedir()"`?
