### ISSUE TITLE
"Attempting to reconnect..." never succeed in remote container

### ISSUE THREAD

**Issue by jeffreyyjp** [microsoft/vscode-remote-release#1227]
- VSCode Version:
1.36.0
- OS Version:
Mac OS 10.14.5
Steps to Reproduce:

1. restart docker using "docker restart containID"
2. So Visual Studio Code is trying to reconnnect the restarted container.

But in my using Code for these days, never succeed even once after restart my docker container.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
This is a limitation of the reconnect logic which is based on the remote state being present in RAM. Restarting the container looses that state. Closing as out-of-scope, thanks.
