### ISSUE TITLE
Can not connect to two containers in same project at same time, even using recommended method.

### ISSUE THREAD

**Issue by mxdmedia** [microsoft/vscode-remote-release#1233]
I have a project, with a set of Dockerfiles and a docker-compose file which is used for deployment as well as development.  The project launches a database server, django REST api server, and a node/angular client, each in their own containers (but all are defined in the docker-compose file).  The scaled down version of the project can be cloned here: https://github.com/mxdmedia/full-stack-demo .

What I am trying to do is be able to debug both the API server and the front end at the same time in VS Code.  To do so, I am trying to do something similar to the directions here: https://code.visualstudio.com/docs/remote/containers-advanced#_connecting-to-multiple-containers-at-once .

The issue I am seeing- if I open either the api server directory (`<project_root>/api-server/my-api`), or the client (`<project_root>/client/my-app`) with "Open directory in container", they work fine.  If I open one, then close it (which stops the containers), then open the other, it also works fine.  However, if I try to open either the server or the client, after the other is running, it fails.  In the latest stable version of VSCode, I get an error -3, and in the insiders version, I get no error, but my files don't show up in the file browser, and I get a message that the files cant be found.

Additionally, even when the python/api-server container does open, it doesn't seem to respect the workspace settings in my `.devcontainer` file.  I have set the mount point to be `<project-root> --> /workspaces`, then in .devcontainer, the workspaceFolder to be `/workspaces/api-server/my-api`, but when the file directory comes up in VS code, it is in the project root.  The node/client container properly shows only the `client/my-app` directory.

- VSCode Version: 1.38.0-insider and 1.37.1
- Local OS Version:  OS X 10.14.4
- Remote OS Version:  Docker Engine 19.03.1 (Docker Desktop 2.1.0.1)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:
1.  Clone my repo: https://github.com/mxdmedia/full-stack-demo
2. Open a new window in VS Code, then "Remote-Containers: Open folder in container.."
3. Select either the `<project-root>/client/my-app` directory, or `<project-root>/api-server/my-api` directory.
4. The container will build/run as it should.  After it is running, close the window.
5. Repeat 3, but select the other directory.
6. It will build/run as it should.
7. While the container from step 5 is still running, open a new window, then "Remote-Containers: Open folder in container.."
8. Select the directory you originally picked in step 3.
9. Boom!

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by mxdmedia** [comment]
Ok, I suspect I've figured out what is going on with the file directory.

In the main docker-compose file, everything is set up for simply running a dev server (for both the API and client), so I was mounting the necessary files to `/code` and executing a serve command.  The Workspaces directory is being set up in the `docker-compose.yml` file in the `.devcontainer` directories.  It looks like when the container is already running, it isn't re-launched using the extended `docker-compose.yml` files, and so that `/workspaces` was never being created.  Additionally, when attaching to the already running container, whatever serving command that it had at start, is already running, which messes some things up.  This is something that fixing #211 would help with.

I went ahead and added mounting `/workspaces` to the root `docker-compose.yml` which is a workaround.  However, I am not sure how I'd go about keeping the server from starting up.

That being said, no matter what I do, the python/api container still doesn't respect the `workspaceFolder` setting.

**Comment by Chuxel** [comment]
> It looks like when the container is already running, it isn't re-launched using the extended docker-compose.yml files

To be clear, you are extending the Docker Compose configuration as a whole - the list of Docker Compose files only affects what is done when the container is started. The reason this trick works at all is because it VS Code can connect to an already running to container.  Your primary compose file spins up two containers at once, and you can't change the configuration again once it is up. 

> That being said, no matter what I do, the python/api container still doesn't respect the workspaceFolder setting.

This is because the `/workspace` bind mount is specified in your extended compose files and only one is getting used to start up the containers (depending on which folder you start with).  There's two ways to both extend both and attach:

Option 1. Merge your extended compose configuration in  `api-server/my-api/.devcontainer/docker-compose.yml` and `client/my-app/.devcontainer/docker-compose.yml` in a single file referenced by both devcontainer.json files.

Option 2. Reference both extended files in both devcontainer.json files.

Either option will ensure both containers are started with the right config.

That said, #211 is a bug - this will shut it down when you close VS Code (assuming you haven't changed that behavior in your devcontainer.json). Running Rebuild Container should cause the new configuration to kick in.

**Comment by mxdmedia** [comment]
> This is because the /workspace bind mount is specified in your extended compose files and only one is getting used to start up the containers (depending on which folder you start with).

I'm not entirely sure that is what is going on.  If I only try to launch the python/server container (before any other container is running), it launches fine, and the `/workspaces` bind mount shows up.  However, in my `devcontainer.json` file I've specified `"workspaceFolder": "/workspaces/api-server/my-api"`.  This is the part that is being ignored, as VSCode opens to just `/workspaces` rather than my specified path.  And this behavior occurs regardless of which order I launch the containers.  I'll also note, the client `devcontainer.json` file also specifies a `workspaceFolder`, and that works properly.. VSCode sees the workplace root as `/workspaces/client/my-app` it is only the python container that doesnt.

**Comment by Chuxel** [comment]
>VSCode sees the workplace root as /workspaces/client/my-app it is only the python container that doesnt.

One scenario that can cause this to happen is if you're using the recently opened to re-connect to the container.  It will reuse the same path just like it would locally.  This allows you to open up multiple folders in the same container - the workspaceFolder is a default. (You can use File > Open to select a different folder in the exact same container.)

**Comment by mxdmedia** [comment]
BINGO!  That was it.  Thanks so much @Chuxel.

**Comment by Chuxel** [comment]
Great!  Closing the issue since it sounds like we have you unblocked!  Let us know if that turns out not to be the case.
