### ISSUE TITLE
please use #!/usr/bin/env bash instead of /bin/bash (which often doesn't exist!)

### ISSUE THREAD

**Issue by ghuntley** [microsoft/vscode-remote-release#124]
Issue Type: <b>Bug</b>

https://twitter.com/GeoffreyHuntley/status/1124538617865523200

![image](https://user-images.githubusercontent.com/127353/57174168-76866f80-6e7d-11e9-9242-fcf0e150e93b.png)

VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.17134
Fetching remote diagnostics for 'SSH' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (51.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|

Fetching remote diagnostics for 'SSH' failed.
</details>Extensions: none

**Comment by roblourens** [comment]
In a terminal, you will get whatever shell you have configured. We just run our install script using bash. I can change it to find `bash` on the PATH.

**Comment by benpye** [comment]
@roblourens Is there a reason for the dependency on bash, would it be better to just use sh?

**Comment by roblourens** [comment]
That's probably doable. Is bash not available on your system?

**Comment by Reanmachine** [comment]
@roblourens Would this change effectively fix #33 by making the commands run in bash shell when a seperate shell is configured as the default?

**Comment by roblourens** [comment]
We already run the install script in bash regardless of the configured shell. The problem with fish is the very short bootstrapping script that invokes bash with the larger install script.

**Comment by anaisbetts** [comment]
@roblaurens this doesn't seem to be the case for me, I'm always being dropped into a default bash prompt

**Comment by roblourens** [comment]
@tyriar Do users need to set the setting for their remote terminal or should it find the default shell?

@anaisbetts How do you set your default shell?

**Comment by Tyriar** [comment]
@roblourens the non-existing shell problem should be fixed by https://github.com/microsoft/vscode-remote-release/issues/38 as the default shell will be evaluated on the remote side (based on `$SHELL`).

**Comment by roblourens** [comment]
This is fixed in the new "nightly" build of the ssh extension, would appreciate people trying it to let me know if there's still an issue: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly (uninstall the stable version too)

Side note, had issues with `flock` when using just `sh`, keeping `bash` for now.
