### ISSUE TITLE
Test connecting to offline hosts

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1253]
Test #15 

- [x] Non-windows client @alexandrudima 
- [x] Windows @rebornix client

Complexity: 4

- Set `"remote.ssh.enableClientDownload": true`
- Configure a VM to be accessible from your client, but not able to access the internet (or our update site). This is easy with a Parallels VM. 
  - VM settings -> Hardware -> Network -> Set "Source" to "Host-Only Network"
  - Now the VM should have no internet access, but you should still be able to SSH from the VM host machine
- If you have connected to this VM before (with the same vscode build) then run the command "Kill VS Code Server"
- Connect to the VM with Remote-SSH as usual
- You should be able to connect with no problem

If you file an issue, include the "Remote - SSH" output channel output

**Comment by alexandrudima** [comment]
Why is this behind a setting? IMHO the option to upload the vscode-server should be presented in the error dialog.
