### ISSUE TITLE
Test connecting using local server to manage connection

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1255]
Test #96

- [ ] ~~Windows~~
- [x] MacOS @sandy081
- [x] Linux @jrieken

Complexity: 5

Install the nightly version of the extension (uninstall stable)

- Set `"remote.SSH.useLocalServer": true`
- Connect to an ssh host with password auth, e.g. https://github.com/microsoft/vscode-internalbacklog/issues/700
- Reload the window
- You should **not** have to enter your password again
- This works by starting a local server to manage the ssh connection. In the Remote-SSH output channel log you can see `Spawned 1234` when the server is started, and in an instance that connected to an already running server, you will see `Found running server - short-circuiting install`
- Try opening multiple windows, reloading, make sure it works as expected. It's easiest to use password auth so its obvious that something went wrong if you have to enter your password again.
- Close all windows - 3 minutes later, the server process should die.

**Comment by jrieken** [comment]
@roblourens The `useLocalService`-setting doesn't exists...

<img width="1030" alt="Screenshot 2019-08-27 at 11 15 39" src="https://user-images.githubusercontent.com/1794099/63758406-02545980-c8bc-11e9-83ac-631d8120f397.png">

**Comment by sandy081** [comment]
Blocked because of #1269

**Comment by jrieken** [comment]
Confusion... Isn't this item about testing that password prompts only show once? So, when I have a VM that doesn't require a password how do I know that things are in order?

**Comment by roblourens** [comment]
Not going to publicize it in release notes this month. There are some issues which you guys found, reconnection doesn't work as well as I thought, and windows is still currently a no-go. SSH on windows doesn't report the askpass prompt message. Meaning we can show a password prompt and complete the loop but we can't tell the user what we are asking for - password, key passphrase, 2fa key, etc.
