### ISSUE TITLE
Exact supported platform in extension and tutorial documentation

### ISSUE THREAD

**Issue by devegied** [Microsoft/vscode-remote-release#126]
While we waiting of other platforms than Linux x86_64 support please update [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh#installation) and [tutorial](https://code.visualstudio.com/docs/remote/ssh#_connect-to-a-remote-host) documentation to indicate exact supported platform (it looks that just "Linux" or "64 bit Linux based OS" is misleading).
Related: #114 #69 #60 #25 #24 #13

**Comment by roblourens** [comment]
Good point, will update docs.

**Comment by CoderOverflow** [comment]
unreachable or not Linux x86_64...
I meet the same question when trying to connect  the ubuntu_18.04 server version

I can create SSH connection by CMD.

**Comment by roblourens** [comment]
Please open a new issue with as many details as possible @CoderOverflow 

The docs will be fixed in the next update, closing
