### ISSUE TITLE
Test: ${localWorkspaceFolder} in devcontainer.json

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1260]
Test #442

- [x] Windows @alexr00
- [x] MacOS @alexandrudima
- [x] Linux @aeschli

Complexity: 2

Test that in the devcontainer.json `${localWorkspaceFolder}` is replaced with the local folder.

**Comment by alexandrudima** [comment]
@chrmarti Could you please link to steps?

**Comment by chrmarti** [comment]
- Open VS Code on an empty folder.
- `Add Development Container Configuration Files...` and pick some definition with a single container.
- Change devcontainer.json to include `${localWorkspaceFolder}`.
- Verify that is substituted correctly.

**Comment by alexandrudima** [comment]
I have tested it with `runArgs` and it worked!

![image](https://user-images.githubusercontent.com/5047891/63772413-56216b80-c8d9-11e9-8d24-0faee1e43035.png)

![image](https://user-images.githubusercontent.com/5047891/63772445-620d2d80-c8d9-11e9-9719-bfc1c7a4b2fa.png)

**Comment by alexr00** [comment]
Tested in runArgs and in settings

**Comment by aeschli** [comment]
Verified based on example in https://github.com/microsoft/vscode-remote-release/issues/442#issuecomment-523335859
