### ISSUE TITLE
VSC won't launch from  WSL2 in Win build 18947

### ISSUE THREAD

**Issue by kobenauf** [microsoft/vscode-remote-release#1263]
Issue Type: <b>Bug</b>

This morning I installed Windows build 18947, and since then, I am unable to launch VSC from a WSL 2 shell using `code .`, which used to work.

I notice if I edit the `code` launch script and remove ELECTRON_RUN_AS_NODE=1 from this line it sort of works:
WSL_EXT_WLOC=$(ELECTRON_RUN_AS_NODE=1 "$ELECTRON" ".\resources\app\out\cli.js" --locate-extension $WSL_EXT_ID)

However, it causes VSC to launch (rather than nothing happening) but VSC does not open the current folder.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18947

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (53.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
tslint|eg2|1.0.44
prettier-vscode|esb|1.9.0
nbpreviewer|jit|1.2.2
vscode-docker|ms-|0.7.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.6.24221
remote-wsl|ms-|0.38.10
cpptools|ms-|0.24.1
Go|ms-|0.11.4
powershell|ms-|2019.5.0
vscode-jest|Ort|3.0.2
vscode-yaml|red|0.4.1
rust|rus|0.6.1
debug|web|0.23.1

(1 theme extensions excluded)

</details>

**Comment by Rhahkeem** [comment]
For anyone experiencing this on the non-insiders build (like I am ), [this](https://github.com/microsoft/vscode-remote-release/issues/1263#issuecomment-515591124) is a valid workaround for now. Is there somewhere we can track this since this issue is closed?
