### ISSUE TITLE
Dev container file is not associated to a workspace

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-release#1265]
Testing https://github.com/microsoft/vscode-remote-release/issues/1258

- Open a workspace
- Create a dev container file using the command `Add Development Container Configuration Files..`
- Reload the workspace
🐛 No notification appears to reopen this workspace in container
- Run the command `Open Workspace in Container...`
🐛 Notification appears now

- Open a different workspace from the same root folder as the first workspace
- Run the command `Open Workspace in Container...`
🐛 Notification appears again

**Comment by chrmarti** [comment]
We now activate after startup which will bring up the notification. (Previously we activated if there is a devcontainer.json in the folders.)
