### ISSUE TITLE
Containers: "Add development Container Files" should not be available if there is a devcontainer.json

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-remote-release#1266]
Refs: https://github.com/microsoft/vscode-remote-release/issues/1259

1. Have a `.devcontainer` and a `devcontainer.json`
2. Trigger the "Add development Container Configuration Files...." command
3. You get a weird error that it is already setup

It would be much nicer that you have a proper context key depending if the `devcontainer.json` exists or not. And that the command is tied to that context key as a precondition.
Thus when the `devcontainer.json` exists the command would not be present in the command palete and also when I invoke the remote actions via the remote status bar entry.

![Screenshot 2019-08-27 at 12 10 45](https://user-images.githubusercontent.com/1926584/63762787-b60d1780-c8c3-11e9-9816-8cf08e493843.png)

**Comment by isidorn** [comment]
I dont understand how triggering a command which fails brings any value.
And yes, having a replacement command in its place makes perfect sense for me. Or if the same command can handle the case that the devcontainer.json exists.

**Comment by sandy081** [comment]
I agree, it makes sense to have this command when it already exists. I encountered this and had a same impression why the command exists if user is not supposed to run that.

**Comment by Chuxel** [comment]
As I mentioned above, my preference would be to allow you to replace the config rather than hide the command.  This allows you to reset or change your configuration as needed easily.

**Comment by chrmarti** [comment]
Folding into https://github.com/microsoft/vscode-remote-release/issues/841.
