### ISSUE TITLE
Containers: "refer to this file" wording could be more precise

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-remote-release#1267]
Refs: https://github.com/microsoft/vscode-remote-release/issues/1259

1. Have a dockerfile and trigger the "Add container config..." command
2. Notice how the `From 'Dockerfile'` has a general description

I suggest to update the description to actually have the name of the file to be more precise. There are too many files being created and 'this file' might be confusing.

Suggestion: `Refer to existing 'Dockerfile' in the container configuration`

![Screenshot 2019-08-27 at 12 12 35](https://user-images.githubusercontent.com/1926584/63762948-0ab09280-c8c4-11e9-8a65-8ed8b47df7d5.png)

**Comment by chrmarti** [comment]
Updating to:

![image](https://user-images.githubusercontent.com/9205389/63855025-be865080-c99e-11e9-812f-3eb3dc55228a.png)

**Comment by isidorn** [comment]
Great. Looks good.
I would only consider adding the word `exisiting` before the name. Though I am fine either way.

**Comment by chrmarti** [comment]
Going with 'the existing':
![image](https://user-images.githubusercontent.com/9205389/63914587-f4294900-ca33-11e9-97f6-8fcb8bf576e6.png)

Thanks!
