### ISSUE TITLE
Do not open container if workspace has paths which cannot be opened in container

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-release#1268]
Testing https://github.com/microsoft/vscode-remote-release/issues/1258

- Have a workspace file that has an absolute path
- Run command `Reopen in Container...`
- It opens the workspace in container but the workspace folder does not have contents.

If we cannot open a workspace with absolute paths in containers, we shall try avoiding them opening in container. For eg., if possible we can evaluate the workspace configuration file and prevent.

**Comment by chrmarti** [comment]
Discussed with @aeschli. We'll keep it simple for now and disallow the non-obvious cases. I'm therefore adding a check for absolute URIs. I'll open a feature request to track relaxing this check for cases where it might still work as suggested by @Chuxel .
