### ISSUE TITLE
User install of VSCode Insiders is not in the path - "code-insiders ." fails

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/vscode-remote-release#127]
Issue Type: <b>Bug</b>

What this means is that the requirement to "bootstrap" remote dev in WSL by running "code-insiders ." fails with "no command found". I have since uninstalled the "user" install and re-installed a "system" install which now works.

Extension version: 0.32.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3396)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (1.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|        Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3401)|
|Memory (System)|7.96GB (1.00GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment]
The Windows installer for both user and system install ask at the end if you want to add the VSCode to the PATH. We should mention in the doc that starting VSCode directly out of a WSL shell requires this. However, you can open a WSL window also from the command menu or the remote indicator. All should work without requiring VSCode on the path, otherwise it's a bug.

**Comment by Sangeppato** [comment]
In my case, I added VSCode to the PATH even with the User installation and in fact I was able to launch it from Powershell/WSL Bash just fine, it simply didn't launch a WSL remote session in the latter case.
Everything works as expected with a System installation

**Comment by aeschli** [comment]
@Sangeppato Can you give more details. What error did you see when the server was starting?

**Comment by andreialecu** [comment]
@Sangeppato I had the same issue, take a look at https://github.com/microsoft/vscode-remote-release/issues/170

**Comment by Sangeppato** [comment]
@aeschli Sorry, I've just done a clean install again and it looks like everything is working just fine..
Previusly I had the same issue @andreialecu  mentioned

**Comment by virgilwashere** [comment]
I submitted PR [#2638](/microsoft/vscode-docs/pull/2638) to update the `PATH` section of [#2635](/microsoft/vscode-docs/pull/2635).

**Comment by Chuxel** [comment]
Tips and tricks doc includes both the cmd.exe path and the VS Code Insiders path issues now.  Install instructions also specifically mention checking "Add to PATH" option and has a pointer to the tips and tricks spot in the quick start..
