### ISSUE TITLE
Wrong path when running 'Open Workspace in Container'

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-remote-release#1271]
re https://github.com/microsoft/vscode-remote-release/issues/1258

* open a devcontainer-workspace
* run the 'Open Workspace in Container' command
* :bug: the picker is pre-populated with a path from my (host) machine which doesn't exist in the current container

<img width="907" alt="Screenshot 2019-08-27 at 14 14 04" src="https://user-images.githubusercontent.com/1794099/63770314-30926300-c8d5-11e9-86df-43acac801551.png">

**Comment by chrmarti** [comment]
Regression from #1204. Reverting that.

@alexr00 Your observation of there being a need to override whether the picker opens remotely / locally was correct after all. Over to you.

**Comment by alexr00** [comment]
I've updated the file picker to respect the scheme of the default URI passed in. I did some testing and didn't find any cases where the URI had an unexpected scheme, but if someone gives the file picker a default URI with the wrong scheme the file picker will no longer try to correct it.
