### ISSUE TITLE
Containers in Explorer: Details view content is lost when another container is selected

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#1274]
Since the Details view is shown for the currently running container, the details view should not change when the selection changes.

In the example below

![image](https://user-images.githubusercontent.com/172399/63771786-1ad26d00-c8d8-11e9-8097-2cd244da3def.png)

The Details view is emptied when the selection in the Targets view becomes empty.

**Comment by alexr00** [comment]
Behavior is now the details view only shows the details of the currently connected container.
