### ISSUE TITLE
Remote Container Explorer: Attach state not updated across windows

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#1276]
In the following setup

![image](https://user-images.githubusercontent.com/172399/63776206-30986000-c8e1-11e9-8cbe-5d8e0a5e278a.png)

Attach to `friendly-hello`

A new window opens and the container got moved to the 'Attach Container' section

![image](https://user-images.githubusercontent.com/172399/63776330-79e8af80-c8e1-11e9-8c0b-97f97bed5028.png)

However in the window from which the attach got started the container still shows up in the 'Other Containers' section. It should show up in the 'Attach Container' section

![image](https://user-images.githubusercontent.com/172399/63776413-a7cdf400-c8e1-11e9-854f-7ad7f9441c5c.png)

**Comment by chrmarti** [comment]
For me it shows under Other Containers in the original and the new window:
![image](https://user-images.githubusercontent.com/9205389/64027705-8cf9ba80-cb41-11e9-8186-1cf36b61737e.png)

**Comment by alexr00** [comment]
Currently, a container can only move to the Attached Containers section when you have opened a folder in it. Until that point, we can't tell the difference. Did you open a folder yet?

(That said, I'm still not seeing the original window update)

**Comment by chrmarti** [comment]
You're right, that makes it move in the new window. I don't see the update in the original window.
