### ISSUE TITLE
Polish suggestions for 'Remote - SSH: Add New Host..`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#1279]
Testing https://github.com/microsoft/vscode-remote-release/issues/1256

- Use the `+` like in 'add branch' in the git viewlet
![image](https://user-images.githubusercontent.com/6461412/63783850-f6818b00-c8ed-11e9-8930-8ebab2e6a953.png)

- open the config file by default. Add user and host as well, not just the one line
![image](https://user-images.githubusercontent.com/6461412/63784372-dacab480-c8ee-11e9-9518-442cfeda2c5e.png)

That way I can also define a custom name. 
Would be cool it there a `Open` code lens that lets me connect from the editor. :-)

**Comment by roblourens** [comment]
Will add the `+`. Code lens is an interesting idea! You got the notification with the options to open the config file or connect, right?

Yeah regarding the Host, we could add a second step where they set a name for the remote.

**Comment by aeschli** [comment]
I though instead of adding another step, just open the config file and insert a snippet.

**Comment by roblourens** [comment]
I want it to work without requiring the user to edit or open the config file.

**Comment by Chuxel** [comment]
@roblourens I could also see a "+" on the explorer doing the same thing.  The main reason docs tell people to use the command rather than the viewlet to get going is because that's not there.

**Comment by roblourens** [comment]
Improvements:

- Use plus icon
- Add it to command palette
- Add plus button to remote explorer view
- Refresh remote explorer after adding a host
