### ISSUE TITLE
Cannot start a ssh session -- bash: /tmp/tmp.LG3at7s3x9/vscode-remote-install...: Permission denied

### ISSUE THREAD

**Issue by antogerva** [microsoft/vscode-remote-release#128]
I get the following issue when I attempt to connect via ssh on a remote server:
Issue Type: **Bug**
```
SSH Resolver called for "ssh-remote+myhost@somehost.com"
SSH Resolver called for host: myhost@somehost.com
Setting up SSH remote "myhost@somehost.com"
Using commit id "473af338e1bd9ad4d9853933da1cd9d5d9e07dc9" and quality "insider" for server
Install and start server if needed
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> Enter passphrase for key 'C:\Users\MyUser/.ssh/id_rsa':
> 
> 
> myuser@myhost@somehost.com's password:
> 
> 
> bash: cannot set terminal process group (-1): Inappropriate ioctl for device
> bash: no job control in this shell
> 
> bash: /tmp/tmp.LG3at7s3x9/vscode-remote-install.473af338e1bd9ad4d9853933da1cd9d5d9e07dc9.sh: Permission denied
> 
"install" terminal command done
Received install output: bash: /tmp/tmp.LG3at7s3x9/vscode-remote-install.473af338e1bd9ad4d9853933da1cd9d5d9e07dc9.sh: Permission denied
Failed to parse remote port from server output: bash: /tmp/tmp.LG3at7s3x9/vscode-remote-install.473af338e1bd9ad4d9853933da1cd9d5d9e07dc9.sh: Permission denied
```

Of course, I can connect to the ssh server with a regular ssh client.

VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.17134
Fetching remote diagnostics for 'SSH' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|

Fetching remote diagnostics for 'SSH' failed.
</details>Extensions: none

**Comment by gaohuazuo** [comment]
I hacked my ssh and recorded what this extension is attempting to do:

<pre><code>Using commit id "473af338e1bd9ad4d9853933da1cd9d5d9e07dc9" and quality "insider" for server
Install and start server if needed
> <b>/home/gaohuazuo/bin/ssh -T -o ConnectTimeout=15 xxx</b>
> ++ mktemp -d
> + INSTALL_SCRIPT=/tmp/tmp.8MAiSv5nix/vscode-remote-install.473af338e1bd9ad4d9853933da1cd9d5d9e07dc9.sh
> + cat
> + chmod +x /tmp/tmp.8MAiSv5nix/vscode-remote-install.473af338e1bd9ad4d9853933da1cd9d5d9e07dc9.sh
> <b>+ /bin/bash -ilc /tmp/tmp.8MAiSv5nix/vscode-remote-install.473af338e1bd9ad4d9853933da1cd9d5d9e07dc9.sh</b>
> bash: cannot set terminal process group (28196): Inappropriate ioctl for device
> bash: no job control in this shell
"install" terminal command done
Received install output: bash: no job control in this shell
Failed to parse remote port from server output: bash: no job control in this shell
</code></pre>

There clearly is something wrong: `ssh` with `-T`, then `bash` with `-i`.

**Comment by roblourens** [comment]
@antogerva is it possible that you have `/tmp` mounted with noexec, like https://github.com/Microsoft/vscode-remote-release/issues/17?

@gaohuazuo Not clear that you have the same issue, those warnings are not fatal. 

> However, my bash is configured to switch to zsh automatically and that was the case of the problem.

That may or may not be an issue. Can you explain some more about your issue, and if you aren't seeing a "permission denied" error, please open a new issue.

**Comment by antogerva** [comment]
@roblourens Well, let's see what I get with the [stat command](https://askubuntu.com/a/152003):
```
myuser@myhost [~]$ stat -c "%a %n" /tmp
1777 /tmp
myuser@myhost [~]$ stat -c "%a %n" $(mktemp -d)
700 /tmp/tmp.t2N5P4JT5j
myuser@myhost [~]$ mount | grep "/tmp"
/dev/root on /var/tmp type virtfs (defaults)
/dev/root on /tmp type virtfs (defaults)
```
Now if I had the following to my .bashrc
```
mkdir ~/tmp2
echo "export TMPDIR=~/tmp2" >> .bashrc
stat -c "%a %n" $(mktemp -d)
700 /home/myuser/tmp2/tmp.bqZfI5N7eb
```
That being said, this seem to help as I get an another error message, when I attempt to connect again:
```
...
Using commit id "473af338e1bd9ad4d9853933da1cd9d5d9e07dc9" and quality "insider" for server
Install and start server if needed
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> Enter passphrase for key 'C:\Users\MyUser/.ssh/id_rsa':
> 
> 
> bash: cannot set terminal process group (-1): Inappropriate ioctl for device
> bash: no job control in this shell
> 
> flock: 99: Bad file descriptor
> 
> Installation already in progress...
> d15f4ef9-85c3-4f43-bb01-62db05c8fbed##24##
> flock: 99: Bad file descriptor
> flock: 99: Bad file descriptor
> 
"install" terminal command done
Received install output: flock: 99: Bad file descriptor
Failed to parse remote port from server output: flock: 99: Bad file descriptor
```

**Comment by roblourens** [comment]
I wonder if `virtfs` doesn't support flock in the same way?

Can you try running this to test?

```
eval "exec 99>/tmp/testlock"
flock -xn 99
```

Should have no output, and not write "Bad file descriptor"

**Comment by underchemist** [comment]
@gaohuazuo could you describe how hacked your ssh to provide that debug information? I'm trying to investigate further with my own setup.

**Comment by antogerva** [comment]
@roblourens, I get no output as well.

**Comment by roblourens** [comment]
Then I'm confused because that's basically exactly what our script does.

**Comment by antogerva** [comment]
It seem I have [jail-shell](https://github.com/pymumu/jail-shell) running as well, so maybe this is the issue?

**Comment by gaohuazuo** [comment]
> @gaohuazuo could you describe how hacked your ssh to provide that debug information? I'm trying to investigate further with my own setup.

I basically created a script named `ssh` and put it in `PATH`:

```
#!/bin/bash -x
/usr/bin/ssh "$@" bash -x
```

**Comment by roblourens** [comment]
@antogerva That could be relevant? Can you try it without that running?
