### ISSUE TITLE
[Polish] Show mounts in details of container explorer

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#1280]
There are three scenarios where I believe seeing container mount points in the details would be useful:

1. Increasingly we are suggesting developers use multiple mount points for different scenarios like SSH keys, optimizing performance with volume mounts, or things like Kubernetes config. Getting these to pick up requires that the container be rebuilt, so seeing this can help hint to rebuild when adding one.

2. Similarly, seeing the source and destination path can help with debugging if a mount point does not appear correctly.

3. As I am reviewing PRs, I frequently have multiple containers with the same name. Seeing the source of the mount point for the source code helps me understand which container I am actually inside.  A related request would be to make the devcontainer.json path visibility in the details (it's actually stored as a label in the container)

**Comment by alexr00** [comment]
I added the devcontainer.json and when you click on it it opens the file.

For the mounds, I think the source is probably what we care about here so I added that. Would it be helpful to also include the mount destination?

![image](https://user-images.githubusercontent.com/38270282/64176399-ac545880-ce5d-11e9-9b6c-48d71fa1b2e4.png)
