### ISSUE TITLE
Support "show details" gesture for container explorer

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#1281]
I am often in a situation where as I review PRs, I have multiple dev containers with the same name, image, and other details but different source code paths and mount points.

I would love to be able to right click and select a "show details" menu item that would poulate the details view even when not connected (potentially with just a subset of information).  This would help me understand which container to delete particularly if combined with #1280.

I imagine others that would use VSCR for PRs would be in the same boat.

This may be more feature request size than polish size, so tagged it as such.

**Comment by alexr00** [comment]
I also want this. @rebornix FYI.

**Comment by alexr00** [comment]
@Chuxel next release (0.74.0 I assume) you'll see this in the context menu of containers.

**Comment by alexr00** [comment]
To verify, right click on any container in the explorer and Show Details.  Verify that this works while connected to a container and while not connected. It should always work, no matter the connection.
