### ISSUE TITLE
Cygwin SSH installation not being found

### ISSUE THREAD

**Issue by Kaos-Industries** [microsoft/vscode-remote-release#1283]
- VSCode Version: 1.37.1
- Local OS Version: Windows 7 x64
- Remote Extension/Connection Type: SSH

----

I have SSH access to a Siteground shared server set up and working without issues via Cywgin, which I've used for years and IMO is currently the best, most complete Unix-like shell experience on Windows 7. I'd like to be able to use Cygwin's SSH binary and config file to remote into my server with VS Code, which would allow me to edit my site without needing to mess around with installing extra, non-Cygwin binaries. Currently, all I get is a fatal error. 

----

Steps to Reproduce:

1. Have Remote-SSH installed

2. Set *Remote.SSH Config File* setting to path of Cygwin SSH config file, in either one of the following formats:

`~/.ssh/config`
`/home/Me/.ssh/config`
`C:\cygwin64\home\Hashim\.ssh\config`

3. Run **Remote SSH: Connect to Host**, enter user@hostname and press Enter. A new VS Code window opens, and after a few seconds a native-looking Windows error is thrown:

> An SSH installation couldn't be found

This issue occurs regardless of whether the integrated VS Code shell is CMD or [set to Cygwin](https://stackoverflow.com/a/51055130/1191147) via the:

`"terminal.integrated.shell.windows": "C:\\cygwin64\\bin\\bash.exe"` 

...setting. Doing `which ssh` when Cygwin is set to my integrated terminal gives me `/usr/bin/ssh`.

**Comment by roblourens** [comment]
Does it work if you set `remote.SSH.path` to `"C:\cygwin64\bin\ssh.exe"` or wherever you have cygwin installed

**Comment by Kaos-Industries** [comment]
Sorry for the late reply, I can confirm that this was the solution.  Thank you.

> 
> 
> Does it work if you set `remote.SSH.path` to `"C:\cygwin64\bin\ssh.exe"` or wherever you have cygwin installed?
