### ISSUE TITLE
[Polish] Add generated .devcontainer folder into workspace when using Open in... flow

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#1284]
Right now when you run the "Open Workspace in Container" command and there is no existing dev container in the location, the `.devcontainer` folder is automatically added to the file structure as expected, but this is not visible from the workspace unless the folder with the workspace in it is in the workspace.

A simple improvement would be to automatically add a `.devcontainer` folder as annother folder in the existing workspace.  Otherwise it is a bit hidden currently.

**Comment by chrmarti** [comment]
I like the idea. /cc @egamma @aeschli

**Comment by aeschli** [comment]
I'm not sure anymore that it's really necessary to see the devcontainer file in the remote explorer. For example the workspace-file is typically not part of the folders.
What's IMO is needed is an command that opens the devcontainer file in an editor. If the devcontainer file references a dockerfile it would be good if there are links to open these.

Also note that we currently don't have API to add a workspace folder.
