### ISSUE TITLE
Missing `Remote WSL: Reopen Folder in Windows` command with multiple distros

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-remote-release#1285]
Testing https://github.com/microsoft/vscode-remote-release/issues/1251

Steps to Reproduce:

1. Install some distros, on my machine (Ubuntu, Kali, Alpine)
2. Open `code-insiders` from default wsl shell
3. Verify that `Remote WSL: Reopen Folder in Windows` is present in this window
4. Run `Remote WSL: New Window using Distro...` and choose another distro
5. `Remote WSL: Reopen Folder in Windows` will not be present in this window.

**Comment by aeschli** [comment]
No it should always by present if the Window is a WSL window and you have a folder or workspace open.
Also, your Windows version has to be 1803 or newer but that seems to be the case in your example otherwise you couldn't do `Remote WSL: Reopen Folder in Windows`
