### ISSUE TITLE
Container action icons

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1289]
Testing microsoft/vscode-internalbacklog#772

![image](https://user-images.githubusercontent.com/323878/63815424-62adc000-c8e9-11e9-9b8e-145fbfc96591.png)

To me, the "Attach to Container" icon looks very similar to our "new folder" icon. I can't think of a better option though.

And the "Stop Container" icon doesn't really look like "stop", is the badge supposed to be a square? This might be similar to the "Stop search" icon that @misolori was iterating on.

**Comment by alexr00** [comment]
Stop has been removed to the context menu since it is more low level, so no more icon. 
I've fixed the Attach To Container action to open a new window every time, which I hope will help.

@rebornix for the Attach looking like new folder.

**Comment by Chuxel** [comment]
@misolori @alexr00 I am also having a hard time detecting the difference between the "running" and "stopped" icon on a 96-DPI monitor (1920x1080).  The difference is too subtle that small from a normal seating position - I'm having to lean in to see it.

![image](https://user-images.githubusercontent.com/312252/64560051-9c74c280-d2fc-11e9-8699-4ad1d342394e.png)

**Comment by misolori** [comment]
@Chuxel do you find that it's only the running/stopped icons or do you think all of those icons w/ small badges are harder to read as well?

**Comment by Chuxel** [comment]
@misolori Could be the size. If the shape is materially different, then is more noticible and color helps - e.g. a checkmark verses a box.  Of course color isn't always accessible.

![image](https://user-images.githubusercontent.com/312252/64563733-e82b6a00-d304-11e9-94da-f140e893c42d.png)

But the triangle and box are too close together and smudge particularly if its lost in a big list.  Its more of a problem in light theme which is where I saw it first:

![image](https://user-images.githubusercontent.com/312252/64563811-19a43580-d305-11e9-80b8-c70116263416.png)

I really have to stare to pick up that ubuntu-18.04-git is the play icon.

**Comment by alexr00** [comment]
@misolori +1 to not being able to tell the difference between stopped and running.

**Comment by misolori** [comment]
@Chuxel @alexr00 what if we made `Stopped` the empty circle and used the filled-in ones when they are running or active? We should also add a tooltip when you hover each icon to indicate what it is.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/35271042/64655544-770db480-d3e1-11e9-8866-af9be3c76889.png">

If we feel these aren't enough we could go a little more agressive and copy what the new Docker icons will be showing (we'd remove the `Machine` portion of the icon) though not sure how it would play with the SSH connections:

<img width="316" alt="image" src="https://user-images.githubusercontent.com/35271042/64655737-fb603780-d3e1-11e9-8a1e-df68bf3a4534.png">

**Comment by Chuxel** [comment]
@misolori Yeah that's different enough I should be able to see it. Mostly solid vs empty.  I suppose another option would be not have the dot at all if the container is not running (like SSH before you connect).  Or use the square stop shape instead of a dot if we want to still invoke the "audio button" aesthetic.

**Comment by alexr00** [comment]
We already have a tooltip that gives you the status when hovering over the text of the container, but the tree itself doesn't extend that to the icon. I'll look at fixing that: https://github.com/microsoft/vscode/issues/80694

Current tooltip:
![image](https://user-images.githubusercontent.com/38270282/64677658-475dbb80-d478-11e9-9e76-7e44ac1758db.png)

**Comment by alexr00** [comment]
It sounds like we should go back to how the icons where used before:

Closed dot for:
Running

Open dot for:
Created
Paused
Refresh (this usually only shows for a second any way)

No dot for:
Exited
Dead (Another unusual state)

**Comment by alexr00** [comment]
Updated the created state icon.

It looks like https://github.com/microsoft/vscode-remote-release/files/3606355/remote-icons-stopped.zip is the open dot icon. Could I get the new window icon from https://github.com/microsoft/vscode-remote-release/issues/1289#issuecomment-525878757 ?
