### ISSUE TITLE
Show progress bar while actions are running

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1291]
Testing microsoft/vscode-internalbacklog/issues/772

If possible, it would be great to have a progress notification while delete, stop, and start actions are running. Otherwise I click the button and don't really get feedback for a bit.

**Comment by chrmarti** [comment]
Seen the progress bar and sometimes the spinner in front of the container node, but now they don't show anymore. 🤔

**Comment by alexr00** [comment]
I can't reproduce this, so opening a new issue to investigate for October.
