### ISSUE TITLE
Upload to github from vscode

### ISSUE THREAD

**Issue by petroskey** [microsoft/vscode-remote-release#1294]
Hi, thank you always for your support.

I am trying to upload projects being developed in a docker container, edited with vscode remote-container, to my github repository.
The OS is Ubuntu18.04.

I am looking forward to hearing any suggestion.
Thank you in advance.

**Comment by chrmarti** [comment]
What does your devcontainer.json look like? If your source is a cloned git repository, you should be able to push changes to GitHub like you normally do, all you need is git installed in the container.

**Comment by petroskey** [comment]
Thank you for your reply, @chrmarti,
I am sorry, but how can I open devcontianer.json file? 
I have not installed git extension, since I have not found the correct one from a lot of git-related extensions.
I sort of understand your suggestion.
My project is not one cloned from a git repository, but has been developed only in the container.
So, should I create a git repository that fully copy this project, and then clone the repository in a new container? 
I am looking forward to hearing your reply.
Thank you for your help.

**Comment by chrmarti** [comment]
VS Code comes with support for Git built-in, you still need make sure the Git CLI is installed into your container. The way you do this depends on the Linux distribution your container is using. (If it is Debian/Ubuntu based, try: `apt-get update && apt-get install git`.)

If you started your project inside the container you can follow [this article](https://help.github.com/en/articles/adding-an-existing-project-to-github-using-the-command-line) on GitHub.

**Comment by petroskey** [comment]
Thank you @chrmarti for your kind reply.
I will try as you suggest!

**Comment by chrmarti** [comment]
Closing as question then. Thanks.
