### ISSUE TITLE
Docker-compose in remote-containers does not respect `workspaceFolder`

### ISSUE THREAD

**Issue by Rhahkeem** [microsoft/vscode-remote-release#1298]
Issue Type: <b>Bug</b>

Using the following `.devcontainer.json`

```
{
    "name": "Super Docker-Compose Workflow",
    "dockerComposeFile": "docker-compose.yaml",
    "service": "mysvc",
    "workspaceFolder": "/workarea",
    "extensions": [
        "ms-python.python",
    ],
    "settings": {
        "python.linting.flake8Enabled": true,
        "python.linting.pylintEnabled": true,
        "python.linting.mypyEnabled": true,
        "python.linting.pep8Enabled": false,
        "python.linting.enabled": true,
        "python.formatting.autopep8Path": "autopep8",
        "python.formatting.provider": "autopep8",
        "git.enabled": false
    },
}
```

When I bring up my container using the remote containers, I always land in `/` in the container. 

In my Dockerfile I also have 

`WORKDIR /workarea` and yet still end up in the root directory. 

If I switch to using the docker interface in the `.devcontainer.json` and keep the same parameter for `workspaceFolder` then it works with no problem. 

Extension version: 0.67.3
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.6.0
Fetching remote diagnostics for 'dev-container+2f55736572732f6a636861726c6572792f57696e646f77732f62626769746875622f6d79646665737663' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 6|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|Dockerfile|
|Screen Reader|no|
|VM|29%|

Fetching remote diagnostics for 'dev-container+2f55736572732f6a636861726c6572792f57696e646f77732f62626769746875622f6d79646665737663' timed out.
</details>

**Comment by chrmarti** [comment]
When you 'attach' to a container, we don't know there is a `.devcontainer.json` and drop you in `/` (or $HOME). We could change that to also look at the `WORKDIR` (which is in the container metadata).

**Comment by Rhahkeem** [comment]
In this case I used the extension to start up a container, but in this case I since i was using `docker-compose` maybe it was trying to attach to the container

**Comment by chrmarti** [comment]
When you do a `Reopen in Container`, it should read the `workspaceFolder` from the `devcontainer.json`.

**Comment by Rhahkeem** [comment]
I'll check it out and get back to you on it

**Comment by cecilphillip** [comment]
I'm having a similar issue as well. My `devcontainer.json` file looks like this
```json
{
    "name": "py3amqp",
    "context": "..",
    "workspaceFolder": "/app",
    "dockerFile": "Dockerfile",
    "extensions": [
        "ms-python.python"
    ],
    "forwardPorts": [
        5672
    ]
}
```
and my docker file looks like...
```Dockerfile
FROM python:3.8.1
WORKDIR /app
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
ENV PATH="~/.poetry/bin/:${PATH}"
```
When I open the project the first time, the container is built and my code is copied to `/workspace/foldername`.  However, vscode drops me in `/app`, that's not where the code is. The code is in the `/workspace/foldername` directory

**Comment by Rhahkeem** [comment]
@cecilphillip I believe it is because of 
```Dockerfile
WORKDIR /app
```

and 
```json
    "workspaceFolder": "/app",
```

that it drops you there. Try changing those to `/workspace/foldername` and see if it helps

**Comment by cecilphillip** [comment]
@Rhahkeem yes your right.
I found the `workspaceMount` setting and that solved my issue
```json
{
    "name": "py3amqp",
    "context": "..",
    "workspaceFolder": "/app",
    "workspaceMount": "source=${localWorkspaceFolder},target=/app,type=bind,consistency=cached",
    "dockerFile": "Dockerfile",
    "extensions": [
        "ms-python.python"
    ],
    "forwardPorts": [
        5672
    ]
}
```

**Comment by chrmarti** [comment]
@Rhahkeem Is this still an issue?
