### ISSUE TITLE
Allow use on `runArgs` in  docker-compose interface

### ISSUE THREAD

**Issue by Rhahkeem** [microsoft/vscode-remote-release#1299]
Issue Type: <b>Feature Request</b>

In the [docs](https://code.visualstudio.com/docs/remote/containers#_devcontainerjson-reference) for `.devcontainer.json` it shows that `runArgs` are an option when using a `Dockerfile` but not when using `docker-compose`. 

Can this option also be extended to the `docker-compose` interface as it would allow for an easier transition when switching between the two and a more unified interface

Extension version: 0.67.3
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.9.184-linuxkit

**Comment by chrmarti** [comment]
Most arguments to `docker run` are available as options in the `docker-compose.yml`, but not as `docker-compose` CLI arguments.

**Comment by Rhahkeem** [comment]
You can use them as arguments to `docker-compose run` which is what the extension runs if I understand correctly

**Comment by chrmarti** [comment]
We use `docker-compose up` to build and start all services. `docker-compose run` would have to be run for each service.

**Comment by Rhahkeem** [comment]
ahh

**Comment by Rhahkeem** [comment]
Potentially `docker-compose run` can be used for the main service and up for the rest?

**Comment by chrmarti** [comment]
Maybe what you want can be achieved by having multiple docker-compose.yml files? You can have a main one and then add to that with additional files. devcontainer.json allows you to specify multiple compose files (main one first).
