### ISSUE TITLE
Please add support for ARM (and Raspberry Pi)

### ISSUE THREAD

**Issue by gingters** [microsoft/vscode-remote-release#13]
It would be great if VSCode remote would also support connecting to Raspian on a Raspberry Pi.

On Twitter @egamma said, there's no AMD build (yet) for the VS Code server part yet. For Raspian this also needs to be a 32bit build, and not 64bit.

Raspberry Pi 2's all have ARMv6 or ARMv7 CPUs which are all 32bit only, and while Raspberry Pi 3's have an ARMv8 CPU that is 64bit capable, Raspbian is only available in 32bit builds.

**Comment by dschaefer** [comment]
+1 :)

**Comment by dschaefer** [comment]
Assuming a remote has node.js available. Wondering what native libraries would be needed.

**Comment by dschaefer** [comment]
So I was thinking more of running VS Code on my laptop and doing builds and debug on the Pi. Why couldn't we just use the Remote-SSH feature for that.

Also, coming from the C++ world where myself and the Eclipse CDT team are building a vscode extension based on clangd, I need to understand how that or any other language server plugs in. I assume we need that on the remote?

**Comment by egamma** [comment]
@dschaefer 

>So I was thinking more of running VS Code on my laptop and doing builds and debug on the Pi. Why couldn't we just use the Remote-SSH feature for that.

VS Code will provision the VS Code Server into your box and for this to work the VS Code Server has to run in your remote environement.

>Also, coming from the C++ world where myself and the Eclipse CDT team are building a vscode extension based on clangd, I need to understand how that or any other language server plugs in. I assume we need that on the remote?

The VS Code extension will work transparently in the remote setup. All you need to do is to install.

**Comment by dschaefer** [comment]
Here's me making assumptions. I thought this was an open extension. Is the protocol open at least so we could write our own servers?

@egamma would I need an ARM/Linux version of the language server for the Pi?

**Comment by egamma** [comment]
>I thought this was an open extension. Is the protocol open at least so we could write our own servers?

Sorry, we did not specify the extension host protocol. It is an area where we make frequent changes/optimisations and we cannot afford the costs of maintaining a specification same as we did for LSP. 

>@egamma would I need an ARM/Linux version of the language server for the Pi?

Yes you would need the language server running on the PI, but also the VS Code Server that hosts the extension that launches the language server.

**Comment by dschaefer** [comment]
Of course, the difference is, I can make the language server, clangd, run on the Pi (or on my QNX device) since it's fully open :).

**Comment by egamma** [comment]
>Of course, the difference is, I can make the language server, clangd, run on the Pi (or on my QNX device) since it's fully open :).

Understood.  However, we have to honest about the cost of an open specification for a domain like IDE extensions. We know this very well from the LSP spec. 

If your goal is to run a clangd language server remotely then you can also achieve this by remoting the LSP protocol (there node modules to do so, they talk through a web socket to an express server running on your device).

**Comment by dschaefer** [comment]
@egamma Frankly, my goal is to help enable Remote-SSH for embedded targets that have self hosted toolchains, like the Raspberry Pi, for whatever operating system it may be running. Looks like that will have to wait.

**Comment by selfup** [comment]
This would be an awesome achievement. Debugging GPIO stuff on a raspberrypi through VSCode would be _amazing_ :tada:

**Comment by ericblade** [comment]
As an embedded systems developer, this would be super cool.  My embedded systems all run node too :-)

**Comment by nataelj** [comment]
Not just GPIO stuff; ALL stuff on the Pi! This is actually clearly something in demand already as someone previously compiled a VS Code version _for_ the Pi (https://pimylifeup.com/raspberry-pi-visual-studio-code/). I've been using that until recently but, on switching to a smaller-profiled devices (which required lower memory) found it no longer worked. The solution discussed here would be the ideal solution for this situation!

**Comment by jmcpeek** [comment]
@dschaefer I ran into a similar issue/quandary and raised a more general issue/request, at least for Remote - SSH  (#257)

Slightly different than how Eclipse handles remote/embedded development support (at least the last time I tried - but I was never able to get it up and operational).

**Comment by dschaefer** [comment]
@jmcpeek Eclipse, or at least the Eclipse C/C++ IDE assumes a cross-development environment for remote/embedded where your compiler and debugger run locally.

This feature of vscode assumes you can compile and debug on the remote but not run vscode there, or at least not all of it. That's what makes this really interesting, especially for larger systems that run Linux or similar OS's that have hard to set up cross-development environments. And, again, the Raspberry Pi is the poster child for this :).

**Comment by duwke** [comment]
And beaglebone and odroid and ...

**Comment by pfeerick** [comment]
Having armhf builds will allow the water to be tested on more than a few SBCs like the rPi, Odroid, etc.

**Comment by dschaefer** [comment]
I think the biggest challenge if they don't open source this is also supporting armv7 and aarch64 versions as the cool cheap little boards at Friendly Elec, and even all the Odroid variants.

**Comment by magic-k** [comment]
Im throwing arm64 chromebooks into the ring. I would really love to use my arm64 chromebook for stuff like developing in arm64 containers.

**Comment by pfeerick** [comment]
@magic-k Just having an armhf build (at all!) should be enough to get started with that, as you can usually install armhf as a foreign architecture and run that on arm64 ;)

**Comment by gingters** [comment]
@pfeerick The Raspberry's are arm32 though. arm64 isn't enough, sadly, for that use case.
I am currently porting some 433 Mhz receiver code from C++ to C#, as well as a lib that runs I2C LCD displays.

My current workflow is edit on PC, build a self-contained deployable, SSH-deploy that the to Pi and run it there, and test. If something fails, it's all about adding log messages as remote-debugging isn't possible.

**Comment by pfeerick** [comment]
> The Raspberry's are arm32 though. arm64 isn't enough, sadly, for that use case.

Huh? armhf = hardware floating point instructions + 32-bit instruction set. If you are on an arm64 system, armhf may also be able to run, meaning an armhf build would be the most flexible.

**Comment by Norbinsh** [comment]
would love to see support for this - rpi 2 / (Linux armv7l )

**Comment by ptone** [comment]
While not as rich as the remote editor, this has been possible over just sftp (I used to use transmit on mac) and there is another extension that will do this without needing to install anything on the remote system, the extension:`kelvin.vscode-sshfs`

I know this isn't as good as the remote server protocol, but it at least is something

**Comment by duwke** [comment]
Good point. Gonna try it.

**Comment by joaosobreira** [comment]
> 
> 
> While not as rich as the remote editor, this has been possible over just sftp (I used to use transmit on mac) and there is another extension that will do this without needing to install anything on the remote system, the extension:`kelvin.vscode-sshfs`
> 
> I know this isn't as good as the remote server protocol, but it at least is something

Yeah, this is what I use. Problem is that most features don't work with it, such as debugging, linting and Intellisense. Remote-SSH seems like the perfect solution for me if it supported ARMv7.

**Comment by benelgiac** [comment]
Nobody mentioned NVIDIA TX1, TX2 platforms, so I will ! Would love to see arm64 support for this, it'd be really great. I know the platform is not even supported for Visual Studio but... you have plenty of spare time, right? :) Cheers

**Comment by fakhamatia** [comment]
I use [THIS](https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs) extension to ssh.
Its support armv7l as well .
But in this extension you cant use extensions on the server side.

**Comment by rikhuijzer** [comment]
> I use [THIS](https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs) extension to ssh.
> Its support armv7l as well .
> But in this extension you cant use extensions on the server side.

Same advise as @ptone

**Comment by joaomoreno** [comment]
Done! 🎉 

https://twitter.com/joaomoreno/status/1138379435839754240

**Comment by magic-k** [comment]
Any technical reason for not extending this to arm64? Don't want to be greedy, just curious.

**Comment by isaac2004** [comment]
I am getting an error when trying to connect to my pi

> Connected to SSH Host - Please do not close this terminal
> 
> "SSH Tunnel" terminal command canceled
> SSH tunnel command completed unexpectedly

Here is my ssh_config


```
Host pi
    HostName 192.168.0.101
    User pi
```

**Comment by joaomoreno** [comment]
> Any technical reason for not extending this to arm64? Don't want to be greedy, just curious.

No technical reason other than not having hardware to test it on right now.

**Comment by SuperSandro2000** [comment]
> > Any technical reason for not extending this to arm64? Don't want to be greedy, just curious.
> 
> No technical reason other than not having hardware to test it on right now.

If you have a Rpi 3b you can install ubuntu with arm64

**Comment by arhimondr** [comment]
@joaomoreno Still fails =\ Here's the log: https://gist.github.com/arhimondr/ab6ca4e7d6798231667fb0a59c1c15ac

Although there's a chance that i messed up with the nightly build (it still shows the version as remote-ssh@0.42.0: https://gist.github.com/arhimondr/ab6ca4e7d6798231667fb0a59c1c15ac#file-gistfile1-txt-L1). 

However it no longer fails with the `unreachable or not Linux x86_64` message, so it looks like the nightly version has been used.

**Comment by pfeerick** [comment]
@arhimondr You got an `Exec format error` near the end there when it failed... so it's loading the wrong binaries... oh, and try deleting the `/home/pi/.vscode-server` folder and letting it set up again... that's the 'stable' version of the server... you need the .vscode-server-insiders to be installed ;)

I had similar issues, but my problem now is the vscode-server(-insiders) is installed and running, but the ssh terminal won't connect. On a rPi 3.

**Comment by rachetfoot** [comment]
I have the same issue @pfeerick although it just hangs forever at that step. The log on the host/server doesn't seem to show any activity at all.

**Comment by pfeerick** [comment]
@rachetfoot Eureka! :D Set up public key authentication so you have passwordless login... and it will then all 'just work' ;) Better off that way in the long run as you don't want to have to enter passwords every time you re-open the connection...

i.e. https://www.ssh.com/ssh/copy-id#sec-Setting-up-public-key-authentication

**Comment by rachetfoot** [comment]
Thanks @pfeerick but I have that already. Oddly the first time I ran it it seemed to get farther before it failed, but now it hangs instead. I've tried closing the processes on the host, deleting the .vscode-server* folders and even rebooting, but I still hangs. I also have the keep terminal window open option enabled, but it still doesn't show me anything.

**Comment by pfeerick** [comment]
@rachetfoot :( I did pretty much the same... It installed perfectly the first time, then got stuck on the tunnel... and had to enter the password about four times once for login, once for the install, and then twice for the tunnel... which failed. I ended up realising I had both .vscode-server and .vscode-server-insiders... so nuked both, and killed the vscode-server processes (using htop)... then tried again... hit the tunnel issues again... then copied the ssh key and double checked it was working with the insiders terminal... and it worked for me. Fingers crossed you work out the magic sauce... the integration looks pretty good! ;) 
![Code_-_Insiders_ZCutVc55Fv](https://user-images.githubusercontent.com/5500713/59347174-4fae3980-8d57-11e9-9ac3-53d98f4b489f.png)

**Comment by rachetfoot** [comment]
I tried a couple more times (including deleting the vscode-server files and stopping the processes) and now it's working. The only other maybe relevant change I recall is enbabing PermitUserEnvironment in /etc/ssh/sshd_config.

**Comment by joaomoreno** [comment]
cc @roblourens

**Comment by roblourens** [comment]
Right now you must uninstall the stable version before using the nightly version, and I just released an update with a warning message to make this more obvious. And if you tried to connect with the stable version, you will need to delete the wrong platform bits that it installed so it will redownload the correct bits. You can do this with the "Uninstall VS Code Server" command. Sorry for the trouble.

**Comment by electronics-ElectroAD** [comment]
I can get it to work with the Raspberry Pi 3 but not with Zero W. VSCode outputs "Unsupported architecture: armv6l". Is it being worked on?

Using the nightly Remote SSH and VSCode as indicated in the blog posts.

**Comment by Misiu** [comment]
@joaomoreno any news about Raspberry Pi Zero W? As @electronics-ElectroAD wrote, this currently outputs unsupported architecture. Should we fill new issue for Pi Zero W or can it be addressed in this?

**Comment by MrAdam** [comment]
@roblourens, any idea when this can be used with the stable version of VS Code?

**Comment by jguiditta** [comment]
Are there plans to extend this support to other distros that run on the Pi, like fedora?

**Comment by noterms** [comment]
@joaomoreno i would appreciate some love for arm67 raspberry Pi Zero W that would be amazing! Keep up the good work.

**Comment by rosslannen** [comment]
> > Any technical reason for not extending this to arm64? Don't want to be greedy, just curious.
> 
> No technical reason other than not having hardware to test it on right now.

@joaomoreno We are using a yocto linux for arm64, and would like to know if there is any way we could build/test remote editing for this architecture?

**Comment by joaomoreno** [comment]
@rosslannen Not currently, no. Only armv7.
