### ISSUE TITLE
Firewall settings prevent connecting to WSL

### ISSUE THREAD

**Issue by costas90** [microsoft/vscode-remote-release#1304]
- VSCode Version: 1.37.1
- Local OS Version: Windows 10, version 1903
- Remote OS Version: 
- Remote Extension/Connection Type: WSL

This problem appeared today after updating Windows to version 1903. Also, when I disable the firewall from Avast Antivirus it works! 

But I dont know how to fix the issue because I want the firewall enabled at all times..

In the firewall logs, it seems that svchost.exe is related, but checking the application rules, all connections are allowed.

![Capture3](https://user-images.githubusercontent.com/18027867/63863390-d7026500-c9b6-11e9-9c64-053a8b026c05.PNG) 

What am I missing?

**Steps to Reproduce:**

1. Run 'code .' in Ubuntu Bash
2. New VS Code window opens but gives the error "Failed to connect to the remote extension host server (Error: connect ETIMEDOUT 127.0.0.1:51072)"

![Capture1](https://user-images.githubusercontent.com/18027867/63863155-6c512980-c9b6-11e9-8c57-5a13e2faecfd.PNG)

![Capture](https://user-images.githubusercontent.com/18027867/63863157-6c512980-c9b6-11e9-9ca0-180f2d4e4369.PNG)

**Comment by costas90** [comment]
I tried rolling back VS Code to 1.36.1 and I get similar errors.

Similar errors and it says it cannot connect to the extensions marketplace..

![Capture5](https://user-images.githubusercontent.com/18027867/63865636-973d7c80-c9ba-11e9-85af-5f2a764475b7.PNG)

In another thread people talk about removing the () from the hostname, but I am not sure where to locate this. Or is that not relevant to WSL?

https://github.com/microsoft/vscode-remote-release/issues/1137#issuecomment-520283108

**Comment by costas90** [comment]
I tried running this from the Insiders V. 1.38

In stable VS Code I cant get the log, but in Insiders I can,, here it is:

![Capture6](https://user-images.githubusercontent.com/18027867/63916070-4b351b00-ca40-11e9-82c4-cf092c42dca3.PNG)

**Comment by aeschli** [comment]
The server seems to be running as the log shows

When you open a browser on http://127.0.0.1:50902/version, does that work?
Can you also try the other IPs listed and http://localhost:50902/version?

**Comment by costas90** [comment]
I ended up rolling back the Windows version from 1903 to 1803 and now it works.

I did try visiting those URLs but did not work.

**Comment by mikeweltevrede** [comment]
I have the same issue but I am unable to roll back to a previous Windows version. Any solutions?

**Comment by mikeweltevrede** [comment]
Following https://github.com/microsoft/vscode-remote-release/issues/927#issuecomment-509262618, I noticed that it was indeed my antivirus software as well (AVG, for those wondering)

**Comment by costas90** [comment]
@mikeweltevrede you can roll back windows if no more than 10 days have past since the upgrade.

https://pureinfotech.com/uninstall-windows-10-1903-may-2019-update/

**Comment by costas90** [comment]
@mikeweltevrede did you manage to make this work with your antivirus?

My windows were auto-updated and I have this problem again..

**Comment by mikeweltevrede** [comment]
@costas90 it is working only if I turn off my virus control before starting VS Code, unfortunately

**Comment by calevans** [comment]
Anyone find a way around this that does not involve shutting down antivirus firewall?

**Comment by aeschli** [comment]
Closing as a WSL issue. Please file against https://github.com/microsoft/WSL/issues
