### ISSUE TITLE
Not sure whether container folder opening behavior is correct 

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1306]
Testing microsoft/vscode-internalbacklog#772

![image](https://user-images.githubusercontent.com/323878/63815671-63932180-c8ea-11e9-9d40-b00ddf159ef0.png)

I think this implies that if I have the setting as "default" and open a container from the viewlet, then it should open in the same window. But, it opens in a new window.

**Comment by alexr00** [comment]
The Attach to container action doesn't respect this setting, but the Open folder in container action should be respecting it and is handling default incorrectly.
