### ISSUE TITLE
[Polish] Containers Explorer - "Open" default folder rather than "Attach" to dev containers from top level

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#1307]
Given the flow we optimize for with remote containers is driving into a primary folder either explicitly set (`workspaceFolder`) or implied in `devcontainer.json`, I'm finding I wish I could just directly "open" from the top level for a given dev container:

![image](https://user-images.githubusercontent.com/312252/63892317-343ced00-c99c-11e9-8ef9-738183074661.png)

Right now you can "start" / connect to the container and get a blank window, but I'd expect to be able to open from here and have the default folder opened.  The dropdown would then show this location and others you may have opened.

It would be nice not to do the extra click for the common use case for this particular extension flow.  (SSH is a bit of a different deal in this regard since it's really an entire machine.)

This may have gotten covered with #1275, so apologies for the dupe if it did, but I didn't see it in today's build.

**Comment by alexr00** [comment]
If I understand correctly then that's pretty close to what the Attach to Container action (the new folder looking icon) does today.

If the container is a dev container, we open the dev container folder when you click the Attach to Container icon. 

If the container is just a container, then we only attach to it.

**Comment by Chuxel** [comment]
@alexr00 Yes, I don't want to attach when I have a devcontainer.json defined since I have already specified the path to open.  I just want to open the folder.

When there's no devcontainer.json, attach makes sense.

**Comment by alexr00** [comment]
@Chuxel then the Attach to Container icon is the one that runs the action you want. We're thinking about changing the icon so that it's a bit clearer!

**Comment by Chuxel** [comment]
@alexr00 Did this change since 0.71? Right now the attach icon does not do what I want - it attaches and drops me in a window without a folder opened.  I want to open the default folder.

What I get - Note the status bar says "attach" and there's no folder open:
![image](https://user-images.githubusercontent.com/312252/63949135-bfff5980-ca2e-11e9-9617-864c74d32ece.png)

What I want:
![image](https://user-images.githubusercontent.com/312252/63949230-eb824400-ca2e-11e9-8f44-d5233d8496a5.png)

**Comment by Chuxel** [comment]
@alexr00 Let me know if you still need more info - I can do a quick video instead if that's easier to understand.

**Comment by alexr00** [comment]
@Chuxel I see what you're saying. It did work the way you are describing, but now there's a bug.

**Comment by roblourens** [comment]
I am missing the top level icon now?

![image](https://user-images.githubusercontent.com/323878/66165054-be562200-e5e8-11e9-9692-b8c4200d2b07.png)

**Comment by alexr00** [comment]
Nothing more to verify here since Rob confirmed that there is no top level action on dev containers.
