### ISSUE TITLE
Remote explorer icon polish

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-remote-release#1308]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/35271042/63888645-4155de00-c994-11e9-9976-7912f505ee3c.png">

- Close actions should always be the last item in the list (it's our consistent pattern)
- Start icon should use the regular start icon instead of the debug start (it's less bold)
- States of VMs could be improved (adding starting/stopped/pending)

**Comment by rebornix** [comment]
> Close actions should always be the last item in the list (it's our consistent pattern)

@alexr00 we may want to add ordering for the inline actions in Container.

**Comment by misolori** [comment]
I've created these icons for the states of VMs, let me know if these are good and I can add them to the repo:

<img width="768" alt="image" src="https://user-images.githubusercontent.com/35271042/63897044-c3e89880-c9a8-11e9-9348-0029f8be3cde.png">

Since the circle badges are 8px, the icons inside may be a little hard to see on non-HDPI screens:

<img width="406" alt="image" src="https://user-images.githubusercontent.com/35271042/63897090-d95dc280-c9a8-11e9-9d9a-5638a8c82e24.png">

**Comment by alexr00** [comment]
Start and stop are removed to the context menu and order is fixed.

For the states, we have created, restarting, running, removing, paused, exited, or dead.

Badge-less icon -> dead status. Dead only happens when the container cannot be restarted again without intervention. I've never seen it. **This icon would only rarely be seen.**

Open circle badge -> created and paused. 

Play -> running.

Refresh arrows -> restarting

Stop square -> exited.

@misolori and @rebornix does that line up with your thinking?

**Comment by misolori** [comment]
Yes, this is exactly what i had in mind. For `Pause`, do you think the open circle would be enough or do you think having something like below would be better?

![image](https://user-images.githubusercontent.com/35271042/63960441-550c4d80-ca43-11e9-9512-1ddf13d53635.png)

**Comment by misolori** [comment]
@alexr00 here are the icons for the explorer (also included the forward ports and open in browser), the only new ones are refresh and stop. Added them here since i wasn't sure if you wanted them in the repo yet.

[remote-icons.zip](https://github.com/microsoft/vscode-remote-release/files/3557338/remote-icons.zip)

**Comment by alexr00** [comment]
I think it can't hurt to have a more specific pause. Thanks for the icons!

**Comment by alexr00** [comment]
@misolori I've updated the icons. Looks like there still isn't a play badge icon so I kept the solid circle badge for running.
