### ISSUE TITLE
Remove SSH extension's `which` dependency

### ISSUE THREAD

**Issue by cpusmith** [microsoft/vscode-remote-release#131]
Searched and no similar.

- VSCode Version:
Version: 1.34.0-insider (user setup)
Commit: 473af338e1bd9ad4d9853933da1cd9d5d9e07dc9
Date: 2019-05-01T00:22:05.899Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
- Local OS Version: 1809 Build 17763.437
- Remote OS Version: CentOS Linux release 7.6.1810 (Core)
- Remote Extension/Connection Type: SSH

Attempts to connect say that curl or wget are not installed when they are.

![image](https://user-images.githubusercontent.com/4100472/57185445-ac395180-6e99-11e9-80cd-34468ecde8ca.png)

or

Install and start server if needed
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> bash: no job control in this shell
> Installing...
> Neither wget nor curl is installed
> 9a3fdd2f-6dde-469c-a316-689f65bb2519##26##
> 
"install" terminal command done
Received install output: 9a3fdd2f-6dde-469c-a316-689f65bb2519##26##
Neither curl nor wget is installed - can't download the Server
Downloading VS Code Server failed - please install either curl or wget on the remote.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
We search for curl or wget by running `which curl` and `which wget` and checking the exit code. What do those commands return when running them on your remote?

**Comment by mklemarczyk** [comment]
When developer does not have rights to install that software it will be not possible to continue. Can you distribute the server package via developer workstation and deliver over ssh?

**Comment by cpusmith** [comment]
Wow, so "which" was not installed on server. Once installed it works now.

Thanks.

**Comment by roblourens** [comment]
We can remove the dependency on `which`. I was taking it for granted and didn't document it as a dependency...

**Comment by cpusmith** [comment]
No, it was my bad not having it installed and is an easy way to check for
installation dependencies.

**Comment by roblourens** [comment]
Out of curiosity, are you using a particular distro that doesn't include it, or did you remove it, or something else? Just wondering how common this might be.

**Comment by ryansully** [comment]
`which curl`/`which wget` can be substituted with `command -v curl >/dev/null`/`command -v wget >/dev/null`; `command` is builtin so should always be available.
