### ISSUE TITLE
Should non-interactive containers show up in explorer view ?

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-remote-release#1310]
When testing https://github.com/microsoft/vscode-internalbacklog/issues/772

1. docker build --tag=test <dockerfile>
2. docker run test (container created will be destroyed)
3. Explorer view shows a container target that is unusable

![Screenshot (9)](https://user-images.githubusercontent.com/964386/63898978-f5189700-c9af-11e9-83fb-04234260973e.png)

**Comment by alexr00** [comment]
`docker build --tag=test` doesn't for me. Is there an additional argument?
Is the container removed when it is destroyed? If not, a user could still start it and remove it.

**Comment by deepak1556** [comment]
>  Is there an additional argument?

Sorry about that, there should be an argument to a folder that has dockerfile.

```Dockerfile
From debian:9
```

`docker build --tag=test folder-that-has-dockerfile/`

> Is the container removed when it is destroyed? 

Yup it is removed, verified with `docker container ls`

**Comment by alexr00** [comment]
@deepak1556 after running those commands the container is still around, it's just exited:
```
PS C:\Users\alros\Documents\empty4> docker ps -a
CONTAINER ID        IMAGE                                                      COMMAND                  CREATED             STATUS                       PORTS               NAMES
06bfa5a569be        test                                                       "bash"                   32 seconds ago      Exited (0) 30 seconds ago                        pedantic_almeida 
```

**Comment by deepak1556** [comment]
> We need to show exited containers because dev containers created by us are automatically exited when we disconnect from them

👍
