### ISSUE TITLE
Setting up SSH notification/progress remains for ever

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-release#1314]
Testing https://github.com/microsoft/vscode-remote-release/issues/1255

- Set `"remote.SSH.useLocalServer": true`
- Connect to an ssh host with password auth, e.g. https://github.com/microsoft/vscode-internalbacklog/issues/700
- Enter wrong password 3 times

🐛 No error indication and `Setting up SSH` notification remains for ever.

From logs: `[06:43:31.833] > ssh child died, shutting down`

**Comment by roblourens** [comment]
Fixed
