### ISSUE TITLE
Details link in notification is not working

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-release#1315]
Testing https://github.com/microsoft/vscode-remote-release/issues/1255

- Set `"remote.SSH.useLocalServer": true`
- Connect to an ssh host with password auth, e.g. https://github.com/microsoft/vscode-internalbacklog/issues/700
- Connect to the provided box
- Password prompt appears
- Click on the `details` link in the notification

🐛 Nothing is shown. neither terminal nor output.

**Comment by roblourens** [comment]
Maybe it should show the output channel in this case, not sure.

**Comment by roblourens** [comment]
Fixed
