### ISSUE TITLE
C# extension fails to install correctly over Remote - SSH

### ISSUE THREAD

**Issue by CodedBeard** [microsoft/vscode-remote-release#1318]
Issue Type: <b>Bug</b>

Using the latest version of code insiders, I've been using Remote - SSH to connect to a raspberry pi running the latest version of raspbian. Whilst the Remote - SSH connection itself seems to work well, it is failing to correctly install omnisharp when installing the C# extension despite reporting it successful. I can see that the .vscode-server-insiders/extensions/ms-vscode.csharp-1.21.1 folder is created, however omnisharp is no where to be found.

The omnisharp log reports:
"Starting OmniSharp server at 8/29/2019, 11:17:58 AM
    Target: $HOME/src/picore-blazor/picore-blazor.sln

[ERROR] Error: spawn $HOME/.vscode-server-insiders/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/run ENOENT
"
I've tried removing/reinstalling the extension and it always ends up in the same broken state.

Extension version: 0.45.6
VS Code version: Code - Insiders 1.38.0-insider (bffbe2ea304a6a4cff23388703b0963f1dadec36, 2019-08-29T05:40:18.065Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux arm 4.19.66-v7+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3672)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (41.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: raspberrypi|
|OS|Linux arm 4.19.66-v7+|
|CPUs|ARMv7 Processor rev 4 (v7l) (4 x 1200)|
|Memory (System)|0.90GB (0.11GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Please file this on the omnisharp repo https://github.com/OmniSharp/omnisharp-vscode/issues
