### ISSUE TITLE
I can't remote on port 443

### ISSUE THREAD

**Issue by Suniron** [microsoft/vscode-remote-release#1320]
Hi,

I would like to connect my VScode Insiders on my proffesionnal laptop to my Raspberry 3B+ by the port 443 (needed to bypass the proxy).

I tried to etablish it with userName@raspberryadress:443 but i have this error popup:
" Could not etablish connection to "userName@raspberryadress:443". Could not resolve hostname".

Thanks to help me :-)

Sorry for my english 👎 *

**Comment by roblourens** [comment]
To use a different ssh port, you will have to set up an ssh config file and set the port option. https://code.visualstudio.com/docs/remote/ssh#_remembering-hosts-you-connect-to-frequently

**Comment by Suniron** [comment]
Thanks! 

configuration of ssh file:

Host <myservername>
    HostName <myserveraddress>
    User <muser>
    Port <myportnumber>
