### ISSUE TITLE
"Learn more" port forwarding link does not go to correct documentation

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-remote-release#1323]
The link https://aka.ms/vscode-remote/containers/ports resolves to https://code.visualstudio.com/docs/remote/containers#_forwarding-a-port, the title of this section appears to have changed so this should instead be https://code.visualstudio.com/docs/remote/containers#_forwarding-or-publishing-a-port

**Comment by Chuxel** [comment]
Ack! Thanks for catching it!  Fixed.
