### ISSUE TITLE
Issues with poor network connection

### ISSUE THREAD

**Issue by hensz** [microsoft/vscode-remote-release#1328]
Hi!

Since a couple of days I need to work with a poor network connection, so the VPN sometimes disconnects and needs to reconnect. The network outage is rather short, e.g. my ssh connection in the shell (I'm using tmux with resurrect plugin just in case) often keeps connected. However VS Code remote shows various issues after such a network loss:

Sometimes the dialog "Attempting to reconnect" is displayed, but reconnection seems to fail - the dialog stays open until I restart VS Code. I also cannot see anything regarding the connection in the Output window.

Most of the time, the workspace seems to have lost most of its information:
- Search only finds results in the currently open file
- Quick open only lists files that I have opened recently
- Go to definition doesn't work
- Remote plugins like MultiClip don't work ("command 'multiclip.copy' not found")

Also, in case of this problem, not all of the above issues occur. Just now I can't use MultiClip or search across files, but opening "new" files works without any problem.

What can I do to help you analyze and hopefully fix this problem? What diagnostics can I provide for further analysis?

Thanks,
Torsten

**Comment by roblourens** [comment]
When reconnection fails, do you see a Remote-SSH log in the output panel? Can you share that? If it doesn't appear please share the console log from devtools (Help > Toggle developer tools)

**Comment by hensz** [comment]
Hi!
The issue didn't occur again, most likely because our IT could fix my network issues.
Best regards,
Torsten
