### ISSUE TITLE
Always show 'Forwarded Ports' and add inline action 'Add'

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1330]
We now can make the dynamic port forwarding a lot easier to discover.

**Comment by alexr00** [comment]
Just waiting for the icons: https://github.com/microsoft/vscode-remote-release/issues/1301#issuecomment-525944078

**Comment by alexr00** [comment]
To verify, connect to a container that doesn't have any ports forwarded. Open the remote explorer and verify that the details view shows Forwarded Ports with and add option.

**Comment by sandy081** [comment]
If it is adding a forward port, is not '+' icon apts instead

<img width="360" alt="image" src="https://user-images.githubusercontent.com/10746682/66113534-3f9fbb80-e5cd-11e9-84c5-5a9e846506be.png">

**Comment by alexr00** [comment]
@misolori for icon details.

**Comment by misolori** [comment]
@sandy081 @alexr00 good point, I hadn't seen the context of where this was going to be used, `+` feels better. I'll create a separate issue.
