### ISSUE TITLE
Add sshd_config and ssh_config to contributes.languages.filenamepatterns

### ISSUE THREAD

**Issue by lmf-mx** [microsoft/vscode-remote-release#1334]
The package.json for the remote-ssh-edit extension has two patterns for contributes.languages
```
"filenamePatterns": [
					"**/.ssh/config",
					"/etc/ssh/ssh_config"
				],
				"filenames": [
					"ssh.config"
				],
```
The syntax highlighting is valuable when examining an ssh_config or sshd_config. Please consider adding `ssh_config` and `sshd_config` to contributes.languages.filenames.

**Comment by roblourens** [comment]
I think that `sshd_config` has other options that aren't covered by this extension. But I could add "ssh_config". Why does the `filenamePatterns` not cover your ssh_config?

**Comment by lmf-mx** [comment]
I was editing an sshd_config in Code for a SaltStack state and went looking for a highlighter. This was the option available.

The local file as part of a project is what doesn't fit the pattern.

**Comment by roblourens** [comment]
I think I need to add a new language type for this so we don't suggest misleading completions, so I will call this a feature request. But, you can use the `"files.associations"` setting to get the sshd_config files colorized for now.
