### ISSUE TITLE
stty: standard input: Invalid argument

### ISSUE THREAD

**Issue by futurehome** [Microsoft/vscode-remote-release#134]
When I tried to connect to a remote server which runs Redhat 6.9, after I input the password, it failed and vscode showed the log below. My account in the server uses tcsh. And I can ssh to this server in Powershell successfully.

> Confirming that Tahiti is a valid reachable host
> Running type "C:\Users\xx\AppData\Local\Temp\1\vscode-linux-multi-line-command-Tahiti.sh" | ssh  Tahiti to confirm the host platform
> > 
> > Pseudo-terminal will not be allocated because stdin is not a terminal.
> > 
> > xx@xx.xx.com's password:
> > 
> > 
> > Warning: no access to tty (Bad file descriptor).
> > Thus no job control in this shell.
> > 
> > **stty: standard input: Invalid argument**
> > 
> "uname" terminal command done
> Tahiti: unreachable or not Linux x86_64. (stty: standard input: Invalid argument)
> 

We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Extension version: 0.35.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kieferrm** [comment]
@futurehome for now pls make sure that the remote server's default shell is bash. We're working on fixing this.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode-remote-release/issues/19

**Comment by futurehome** [comment]
@kieferrm , thanks, hope to see it can work on csh soon.
