### ISSUE TITLE
Remote Containers: Add 'Rebuild Container' action to container context menu

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#1342]
![image](https://user-images.githubusercontent.com/172399/64101361-fcec8880-cd6d-11e9-9fc5-388e58c08984.png)

**Comment by alexr00** [comment]
To verify, connect to a container. Right click on the container that you are currently connected to and verify that there is a Rebuild Container option and that it works. Also verify that the the Rebuild options only exists on the container you are connected to.
