### ISSUE TITLE
Extensions specified in devcontainer.json not automatically installed

### ISSUE THREAD

**Issue by CoenraadS** [microsoft/vscode-remote-release#1343]
- VSCode Version: 1.37.1
- OS Version: Ubuntu 18

Steps to Reproduce:

1. Follow official python 3 dev container example
2. Note `ms-python.python` is specified in devcontainer.json
3. It is not listed as installed extension in the container, I have to install it manualy

**Comment by CoenraadS** [comment]
Ah you are correct, I thought it was rebuilding the container every time.

Quick follow up question I didn't see in the docs. I want to passthrough some environmental args from host to docker. e.g. `docker run --rm -e YOURAPP_ENV=development`

How can I set this up inside vscode? somewhere in the devcontainer.json?

**Comment by jbrandli** [comment]
This issue happens to me too. The java pack does not get installed

```
	"extensions": [
		"vscjava.vscode-java-pack",
		"redhat.java"
	]
```
```
CPUs | Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.88GB (1.25GB free)
Process Argv |  
Screen Reader | no
VM | 0%


```
```
Remote | Dev Container: Java 11
-- | --
OS | Linux x64 4.9.184-linuxkit
CPUs | Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (3 x 2402)
Memory (System) | 7.28GB (5.90GB free)
VM | 0%
```
