### ISSUE TITLE
Remote SSH Not Detecting Saved Hosts in ssh config files

### ISSUE THREAD

**Issue by hprateek43** [microsoft/vscode-remote-release#1347]
Issue Type: <b>Bug</b>

The hosts saved in ssh config file are not displayed in the connections tab

Extension version: 0.45.6
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Please give some more details. Do you have a custom ssh config file set up?

**Comment by hprateek43** [comment]
No I do not have a custom ssh file. I am using the standard ssh files with my hosts defined with specific users and key files. However VSCode does not detect the hosts that are present there. Do let me know if I should add some screenshots

**Comment by roblourens** [comment]
Yes screenshots would help, or tell me the location of those files and whether it shows up when you run the command "Open configuration file"
