### ISSUE TITLE
Container ports forwarding randomly

### ISSUE THREAD

**Issue by damccull** [microsoft/vscode-remote-release#1348]
- VSCode Version: 1.37.1
- Local OS Version: Win 10 1903
- Remote OS Version: Docker for Windows FROM mcr.microsoft.com/dotnet/core/sdk:3.0
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Set up devcontainer.json with:
```
"appPort": ["5000:5000"],
```
2. Set up launch.json for:
```
"serverReadyAction": {
    "action": "openExternally",
    "pattern": "^\\s*Now listening on:\\s+https?://\\S+:([0-9]+)",
    "uriFormat": "https://localhost:%s"            
},
```
3. Run a web app on this with the listening address set to 0.0.0.0:5000
4. Watch as the browser launches to 127.0.0.1:<randomport> instead of 0.0.0.0:5000.

No matter what I do, I can't make it launch the browser to the preferred port. It IS, however, at least listening on the preferred port as well.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
@mjbvz I guess this is using your forwarding implementation. If the extension had a way to tell the core about the forwarded ports, the core could use those ports instead of creating new forwarding ports.

**Comment by damccull** [comment]
I'm not sure that I have a forwarding implementation...I'm using this with the default configs generated by the extension and modifying the ports to match what I want. The random ports seem to be automatic somehow.

**Comment by Chuxel** [comment]
@chrmarti @mjbvz Yes, this is #1115. The current behavior is quite confusing.  In addition to not reusing the same port, we don't forward 0.0.0.0, which is a problem in the containers case.  If you use appPort, 127.0.0.1 will not resolve since it's published.

**Comment by damccull** [comment]
So is there a workaround for this, then, or should I just continue what I'm doing until some update incorporates a fix? Like I said, though the behavior is undesirable, it's not breaking. The manually set ports do still work, they just don't seem launch in the browser that way automatically, which is completely weird to me, and I end up having multiple ports mapped to the same back-end port: my manually set one, and the automatic one.

**Comment by damccull** [comment]
Ah, I read through the very nice issue you referenced. I'll close this one with reference to that one, since this is a duplicate.
