### ISSUE TITLE
Remote Containers: Guide users to create the first container when non exists

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#1349]
Currently the Remote explorer shows 

![image](https://user-images.githubusercontent.com/172399/64133722-ae280880-cdd8-11e9-963e-e4fbd65f9f69.png)
 

We should guide users to create the first container when none exists as is done by the SSH Explorer today:

![image](https://user-images.githubusercontent.com/172399/64133713-9a7ca200-cdd8-11e9-9dee-01d80b50635d.png)

**Comment by alexr00** [comment]
The ability to have a link in the tree view message is no longer supported, so both containers and SSH will need to use only a string.

**Comment by alexr00** [comment]
New guidance for docker running but no containers:
![image](https://user-images.githubusercontent.com/38270282/64624882-9a3d6180-d3eb-11e9-8835-5f98cd51fcaa.png)

**Comment by alexr00** [comment]
To verify, make sure you have docker running but no containers at all then open the Containers explorer. Verify that the commands shown are appropriate for your workbench state (folder/workspace or nothing) and that the commands work.
