### ISSUE TITLE
SVN extension doesn't work with Remote-SSH

### ISSUE THREAD

**Issue by FractalBoy** [microsoft/vscode-remote-release#135]
- VSCode Version: 1.34.0-insider
- Local OS Version: Windows 10
- Remote OS Version: CentOS 7
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install the Subversion extension
2. Try to use it (cd to a SVN directory)
3. "There is no data provider that can provide view data" and ""Cannot find module 'original-fs'" in the developer's console.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

![image](https://user-images.githubusercontent.com/2024233/57187132-3e4c5480-6eb0-11e9-979b-5cf3a237adac.png)

![image](https://user-images.githubusercontent.com/2024233/57187135-4d330700-6eb0-11e9-8f06-331c71fd9e87.png)

![image](https://user-images.githubusercontent.com/2024233/57187138-6cca2f80-6eb0-11e9-9d40-f186b6e325f9.png)

Note that git works fine and that the error in the developer's console does not show up locally.

I also opened this issue with the extension in case they need to make a change. https://github.com/JohnstonCode/svn-scm/issues/561

**Comment by Chuxel** [comment]
@FractalBoy Okay, looking at this, this may be due to this challenge with extensions that use native Node.js modules: https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-native-node.js-modules

Assuming that is accurate, the extension will need to make some changes to accommodate remote development unfortunately.

//cc: @rebornix

**Comment by Chuxel** [comment]
@rebornix @FractalBoy  Actually - I think in this particular case, this is a difference in how its accessing the "fs" node module... it's attempting to use original-fs to get at the underlying Node.js implementation's "fs" module.  So technically not the same as the link above, but a similar underlying issue... Electron node verses standard node in the remote case.

This was introduced with this change: https://github.com/JohnstonCode/svn-scm/pull/540

We'd looked at this extension before, but this update was published after we'd done the validation.

**Comment by Chuxel** [comment]
Closed via https://github.com/JohnstonCode/svn-scm/issues/561#issuecomment-491859214
