### ISSUE TITLE
Getting Cannot read property 'getExtension' of undefined

### ISSUE THREAD

**Issue by rinti** [microsoft/vscode-remote-release#1352]
Issue Type: <b>Bug</b>

I can't really show steps on how to reliably produce but I've reinstalled both Docker for Mac and VSCode and the only extensions I have are Remote Containers and Python. This works on my coworkers computers but not on mine.

The .devcontainer and .vscode I use are identical to those of this:
https://github.com/Frojd/Wagtail-Pipit/tree/develop/Company-Project

The steps I take:
1) code . in the folder
2) Reopen folder in Container
3) I go to debug pane
4) I press the play button
5) I get the "Cannot read property 'getExtension' of undefined"

I have tried both example python projects on my computer and they work fine.

Extension version: 0.67.3
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.9.184-linuxkit

**Comment by chrmarti** [comment]
Could you check the developer console for a stacktrace to this error message (Help > Toggle Developer Tools)?

**Comment by rinti** [comment]
I think this solved itself after the latest vscode version or the latest extension version because I'm not getting the error anymore. I'm getting another error that seems to be my own fault :) I'll reopen a new issue if it's not.
