### ISSUE TITLE
Local external terminal that connects to remote host

### ISSUE THREAD

**Issue by kcajf** [microsoft/vscode-remote-release#1354]
I was wondering if it would be possible to open a local terminal that automatically connects to the remote host via ssh (& perhaps autoconnecting to a tmux session?). Currently setting `"terminal.explorerKind": "external"` appears to have no effect when using Remote SSH.

**Comment by roblourens** [comment]
The integrated terminal will operate within the remote, and you can use the "Terminals Manager" extension to autoconnect to a tmux session. But I don't think we will launch an external terminal with an ssh command.

**Comment by kcajf** [comment]
Ignoring the ssh part: currently, `"terminal.explorerKind": "external"` doesn't seem to work when connected to a remote server. I would expect it to open a local external terminal.
