### ISSUE TITLE
<>: unreachable or not Linux x86_64. (debug1: Exit status 0)

### ISSUE THREAD

**Issue by umdstu** [microsoft/vscode-remote-release#1363]
Searched previous issues with similar error, some existed, but not exactly the same.

- VSCode Version: 1.37.1
- Local OS Version: Windows 10
- Remote OS Version: CentOS 7
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Attempt to connect to Remote SSH host
2. unreachable or not Linux x86_64. (debug1: Exit status 0)

This is different than similar issues because the OS *is* Linux x86_64. Running uname command on the remote host yield "Linux x86_64", so it's not an OS issue. Last few lines of the Output tab:

```
> debug2: channel 0: input drain -> closed
> 
> Linux x86_64
> debug3: received packet: type 98
```
...
```
> debug3: channel 0: status: The following connections are open:
>      #0 client-session (t4 r0 i3/0 o3/0 fd -1/-1 cc -1)
>
> debug3: send packet: type 1
> debug3: fd 0 is not O_NONBLOCK
> debug3: fd 1 is not O_NONBLOCK
> Transferred: sent 2496, received 3532 bytes, in 0.5 seconds
> Bytes per second: sent 5246.7, received 7424.4
> debu1: Exist status 0
>
"uname" terminal command done
x.x.x.x: unreachable or not Linux x86_64. (debug1: Exit status 0)
```

I am not seeing anything else in the logs that would yield this error.

Thanks

**Comment by roblourens** [comment]
Please include the full log. This looks like an old version of the extension.

**Comment by umdstu** [comment]
Thanks for the quick reply @roblourens - You were correct, it was an older version. Updated the extension and now it actually attempts to install the server code.

Much appreciated!
