### ISSUE TITLE
constant connection interruption

### ISSUE THREAD

**Issue by anandbhattad** [microsoft/vscode-remote-release#1364]
Recently, I have been facing a lot of connection issues and after less than a minute get "Attempting to reconnect..."

**Comment by chrmarti** [comment]
Is this with SSH or with Containers?

**Comment by anandbhattad** [comment]
SSH

**Comment by chrmarti** [comment]
Maybe related: #1365

Are there any errors in the console (Help > Toggle Developer Console)?

**Comment by anandbhattad** [comment]
Updating to VSCode 3 (Aug 2019 update) seems to solve the issue. Don't see any interruption so far!
