### ISSUE TITLE
VSCode crashes on opening Remote-WSL extension

### ISSUE THREAD

**Issue by alextokarewLM** [microsoft/vscode-remote-release#1368]
Issue Type: <b>Bug</b>

1. Launch WSL
2. Go to project source directory
3. Type `code .`

Or

1. Lauch VSCode
2. Press F1 and type: Remote-WSL: New Window

VSCode launches, but crashes on step 'Starting VSCode in WSL Ubuntu'. It shows a popup 'The window has crashed' with a message 'We are sorry for the inconvenience! You can reopen the window to continue where you left off'

Extension version: 0.39.5
VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.64GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aeschli** [comment]
Similar to https://github.com/Microsoft/vscode/issues/43062

Can you try `code .` on a different folder, maybe one without much content.
