### ISSUE TITLE
Code-insiders started from WSL doesn't return to console/ doesn't connect

### ISSUE THREAD

**Issue by Sieboldianus** [microsoft/vscode-remote-release#1369]
Intro:

* **I've reported this problem before here in [#780](https://github.com/microsoft/vscode-remote-release/issues/780), it was solved but since the update yesterday the bug seems back**
* I've searched and found 2 similar problems, but no solution reported there works for me and, even when following the guidance, my issue remains. See [46462](
https://github.com/Microsoft/vscode/issues/46462)
 and [44540](https://github.com/Microsoft/vscode/issues/44540)
* I've installed the latest code-insiders release
* VSCode Version: 1.39.0-insider (user setup)
* OS Version: Windows 10 with latest patches

Steps to Reproduce:

1. Install Code-Insiders
2. Open WSL
3. type code-insiders .
4. a: Code insiders opens up in Windows, does not connect to WSL
5. b: WSL shows log output from code-insiders, e.g.:
```bash
[main 2019-09-05T11:06:09.080Z] update#setState idle
[main 2019-09-05T11:06:39.081Z] update#setState checking for updates
[main 2019-09-05T11:06:39.106Z] update#setState idle
```
* same result when launching with code-insiders . --disable-extensions, launching with code . opens up regular vs code (doesn't leak, but also has no native WSL support). So, does this issue occur when all extensions are disabled? Yes!

My Path environment variables for `code` and `code-insiders`:
```bash
which code-insiders
/c/Users/[me]/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders
```

```bash
which code
/c/Program Files/Microsoft VS Code/bin/code
```

My WSL is based on the official Ubuntu 18.04, setup with [LxRunOffline](https://github.com/DDoSolitary/LxRunOffline)

* starting code-insiders with code-insiders . from WSL worked until the last week. So this issue didn't occur before the latest version of code-insiders.

**Comment by pcolmer** [comment]
I'm having the same problem. It does seem to have been caused by a newish release as I'm using this daily and I've only started seeing this today. It was fine yesterday.

**Comment by kaymach** [comment]
Same here. Happened right after most recent update.

**Comment by aeschli** [comment]
Sorry for that, I copy pasted a fix to the wrong line.
I pushed a fix. If you can't wait for the next insiders build on Monday, edit your `/c/Users/[me]/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders` as seen here
https://github.com/microsoft/vscode/commit/68c1123b33676df276f706e66caf2293a959155b

**Comment by Sieboldianus** [comment]
Yep, works again 👍
