### ISSUE TITLE
Settings precedence, shouldn't Remote take precedence over Workspace?

### ISSUE THREAD

**Issue by tdamsma** [microsoft/vscode-remote-release#1371]
Currently ( vscode 1.37.1; remote containers 0.67.3) the precedence of settings is 

`User` < `Remote [Dev Container]` < `Workspace`

The [documentation](https://code.visualstudio.com/docs/remote/containers#_devcontainerjson-reference) states 

> Container specific settings

> VS Code's local user settings are also reused when you are connected to a dev container. While this keeps your user experience consistent, you may want to vary some of these settings between your local machine and each container. [...] These will override any local settings you have in place whenever you connect to the container.

For my usecase,  am developing a python package. I refer local development, but also want to be able to develop in containers. An important difference is the configuration of the `python.pythonPath`. When developing locally I use virtual environments so this setting is different per project, and thus goes into the project settings. When I develop in the container the location of the python interpreter is different, so I have to adjust it. It would be nice to keep this configuration confined to the containers, but as I have mounted the project rot into the container I have also mounted the .vscode/settings.json file in the container, and those settings override my local settings. So every time I switch between local and remote development I need to change the Workspace settings. 

 I think it would make much more sense to change the precedence to 

`User` < `Workspace`< `Remote [Dev Container]` 

That way you can override both User and Workspace settings an a per project basis.

**Comment by sandy081** [comment]
A new scope has been introduced `machineOverridable` to honour machine settings in workspace. Please request python to use this scope.
