### ISSUE TITLE
Massive resource utilization on Raspberry Pi when doing Python development

### ISSUE THREAD

**Issue by EvgenyMuryshkin** [microsoft/vscode-remote-release#1375]
Issue Type: <b>Bug</b>

My raspberry pi 4 runs on 1.5Mhz and using 300% when remote connection is up from VSCode. Eventualy it overheats and shuts down. Once remote connection is closed, all goes low and works stable.

Running application inside terminal in VSCode
![image](https://user-images.githubusercontent.com/11254187/64410195-d8761080-d0cd-11e9-8da4-2b2d418c876a.png)

Running same application directly on device via VNC
![image](https://user-images.githubusercontent.com/11254187/64410014-74ebe300-d0cd-11e9-9a3f-cc40ce32b94a.png)
 

Extension version: 2019.9.6660
VS Code version: Code - Insiders 1.39.0-insider (9414b7e75bdbef887c76cb603e542db2b86b99b7, 2019-09-06T05:27:14.341Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by EvgenyMuryshkin** [comment]
UPD: with external fan, it does not overheat, but still hangs in about 10 minutes of idling event if nothing runs in terminals

**Comment by egamma** [comment]
/needsMoreInfo

What extensions do you have installed? What kind of project are you working on, e.g., python? When you run Help>Process Explorer which process shows high CPU/Memory consumption.

**Comment by EvgenyMuryshkin** [comment]
I am running python application, but it hangs even on idle without running anything, 
just boot pi, open connection and leave it, in about 10 minutes it is dead - process with name "rg" slowly stacks up memory 

![image](https://user-images.githubusercontent.com/11254187/64595666-c8c03a00-d3f5-11e9-9d20-1f6d1d0551ed.png)


From Process Explorer all good
![image](https://user-images.githubusercontent.com/11254187/64594287-10919200-d3f3-11e9-9a82-e97cfebf37e3.png)

If I look in pi itself and run top, I get this
![image](https://user-images.githubusercontent.com/11254187/64594386-40409a00-d3f3-11e9-913f-7a3b8db7520f.png)

If I close remote connection from VSCode, all goes back to normal
![image](https://user-images.githubusercontent.com/11254187/64594472-6f570b80-d3f3-11e9-885e-ee37e7b3e436.png)

**Comment by egamma** [comment]
@EvgenyMuryshkin since I cannot move the issue, can you please file the issue against the vscode-python extension
https://github.com/microsoft/vscode-python/issues/new/choose

I suggest to create an issue with a description that it links back to this issue, so that you do not have to copy all the comments.

**Comment by EvgenyMuryshkin** [comment]
Why? It has nothing to do with python.

**Comment by EvgenyMuryshkin** [comment]
I boot pi, connect VS remote and it hangs in about 10 minutes without doing anything.
