### ISSUE TITLE
Files created outside VS Code does not render in VS Code

### ISSUE THREAD

**Issue by MikkelHegn** [microsoft/vscode-remote-release#1376]
Issue Type: <b>Bug</b>

In the integrated terminal I create a new file the folder, which is connected remotely. The files does not show up in the Explorer in VS Code, until I close and re-open the remote folder.

Extension version: 0.39.5
VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18970
Remote OS version: Linux x64 4.19.59-microsoft-standard
Remote OS version: Linux x64 4.19.59-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (17.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.59-microsoft-standard|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3599)|
|Memory (System)|30.11GB (29.09GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.59-microsoft-standard|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3599)|
|Memory (System)|30.11GB (29.09GB free)|
|VM|0%|
</details>

**Comment by MikkelHegn** [comment]
Choosing to open the file using the File --> Open option, will render a refresh in the explorer

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode-remote-release/issues/1381
