### ISSUE TITLE
After sleeping the port forwarding is changed on the local side

### ISSUE THREAD

**Issue by SSmale** [microsoft/vscode-remote-release#1378]
- VSCode Version:
```
Version: 1.39.0-insider (user setup)
Commit: 7edc8f786e065edbc9540f1e19ebd9220b9e0cf9
Date: 2019-09-05T05:42:21.072Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134
```
- Local OS Version: Windows 10 Pro
- Remote OS Version: CentOS Linux release 7.5.1804 (Core)
- Remote Extension/Connection Type: SSH
- RemoteSSH version: 0.46.0

Steps to Reproduce:

1. open connection
2. set port forwarding (4200 then blank)
3. open port in browser ( all working)
4. let the PC go to sleep (like over lunch)
5. on checking the port forward in VSCode the port is now set locally as a random 50k port 
6. cant connect over :4200 

This is the first day that I have seen the issue after 3 ish months of using the extension.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by roblourens** [comment]
Fixed this
