### ISSUE TITLE
Cannot debug a Go program

### ISSUE THREAD

**Issue by cfiderer** [microsoft/vscode-remote-release#1379]
Issue Type: <b>Bug</b>

Debugging a simple HelloWorld.go program fails in remote WSL:
When starting to debug (with F5), I see that Delve gets started (pid 13615) in the background, the target gets compiled and started, too (pid 13706) - but the UI doesn't connect to Delve.

Extension version: 0.39.5
VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (13.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|Memory (System)|31.79GB (13.57GB free)|
|VM|0%|
</details>

ms-vscode.go 0.11.4 installed in WSL

Running processes (ps -ef):
```
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 14:28 ?        00:00:00 /init
root       246     1  0 14:34 tty2     00:00:00 /init
cfradm     247   246  0 14:34 tty2     00:00:00 -bash
cfradm     775     1  0 16:01 ?        00:00:09 [node] <defunct>
root     13234     1  0 16:45 tty1     00:00:00 /init
cfradm   13235 13234  0 16:45 tty1     00:00:00 sh -c "$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 3db7e09f3b61f915d03bbfa58e258d6eee843f35 stable .vscode-server 0
cfradm   13236 13235  0 16:45 tty1     00:00:00 sh /mnt/c/Users/d041725/.vscode/extensions/ms-vscode-remote.remote-wsl-0.39.5/scripts/wslServer.sh 3db7e09f3b61f915d03bbfa58e258d6eee843f35 stable .vscode-server 0
cfradm   13240 13236  0 16:45 tty1     00:00:00 sh /home/cfradm/.vscode-server/bin/3db7e09f3b61f915d03bbfa58e258d6eee843f35/server.sh  --port=0 --fileWatcherPolling=0
cfradm   13242 13240  0 16:45 tty1     00:00:07 /home/cfradm/.vscode-server/bin/3db7e09f3b61f915d03bbfa58e258d6eee843f35/node /home/cfradm/.vscode-server/bin/3db7e09f3b61f915d03bbfa58e258d6eee843f35/out/vs/server/main.js  --port=0 --fileWatcherPolling=0
cfradm   13257 13242  0 16:45 tty1     00:00:01 /home/cfradm/.vscode-server/bin/3db7e09f3b61f915d03bbfa58e258d6eee843f35/node /home/cfradm/.vscode-server/bin/3db7e09f3b61f915d03bbfa58e258d6eee843f35/out/bootstrap-fork --type=watcherService
cfradm   13299 13242  0 16:45 tty1     00:00:06 /home/cfradm/.vscode-server/bin/3db7e09f3b61f915d03bbfa58e258d6eee843f35/node /home/cfradm/.vscode-server/bin/3db7e09f3b61f915d03bbfa58e258d6eee843f35/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/home/cfradm/.vscode-server/bin/3db7e09f3b61f915d03bbfa58e258d6eee843f35/out/vs/server/uriTransformer.js
cfradm   13590 13299  0 16:49 tty1     00:00:00 /home/cfradm/.vscode-server/bin/3db7e09f3b61f915d03bbfa58e258d6eee843f35/node /home/cfradm/.vscode-server/bin/3db7e09f3b61f915d03bbfa58e258d6eee843f35/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=13299
cfradm   13608 13299  0 16:57 tty1     00:00:00 /home/cfradm/.vscode-server/bin/3db7e09f3b61f915d03bbfa58e258d6eee843f35/node /home/cfradm/.vscode-server/extensions/ms-vscode.go-0.11.4/out/src/debugAdapter/goDebug.js
cfradm   13615 13608  0 16:57 tty1     00:00:00 /mnt/c/Users/d041725/go/bin/dlv debug bugreport --headless=true --listen=127.0.0.1:3140 --api-version=2 --log=true
cfradm   13706 13615  0 16:57 tty1     00:00:00 /mnt/c/Users/d041725/go/src/bugreport/__debug_bin
cfradm   13708   247  0 17:01 tty2     00:00:00 ps -ef
cfradm   13709   247  0 17:01 tty2     00:00:00 less
```
Debug Console:
API server listening at: 127.0.0.1:3140
2019-09-06T16:57:49+02:00 info layer=debugger launching process with args: [/mnt/c/Users/d041725/go/src/bugreport/__debug_bin]

Sample program:
````
package main

import (
	"fmt"
)

func main() {
	fmt.Printf("Hello, World\n")
}
````

**Comment by egamma** [comment]
This is a known limitation of WSL https://code.visualstudio.com/docs/remote/wsl#_known-limitations that is addressed in WSL2.
