### ISSUE TITLE
[WSL 2] FileWatcher not working events not firing up

### ISSUE THREAD

**Issue by Flaires** [microsoft/vscode-remote-release#1381]
- Version: 1.38.0 (user setup)
- Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
- Date: 2019-09-03T21:49:13.459Z
- Electron: 4.2.10
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Windows_NT x64 10.0.18975
- Remote Extension/Connection Type: WSL (2)

Steps to Reproduce:

1. Open up the workspace in the WSL 2. Install `vector-of-bool.cmake-tools` (or any other extension doesn't matter, for this example I use this).

2. Create a SystemFileWatcher extension, lets take a simple one. Example: 

```ts
let myWatcher= vscode.workspace.createFileSystemWatcher('**/*.{c,cpp}');

myWatcher.onDidCreate(() => vscode.commands.executeCommand('cmake.configure'));
```

3. Locally the extension works perfect on the WSL site not. You can call any other method or function in the `onDidCreate()` event, but it doesn't fire up.

Does this issue occur when you try this locally?: No

Maybe related to #870

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode-remote-release/issues/870
