### ISSUE TITLE
Improve Attach to Running Container support

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#1383]
Today "Attach" has limited flexibility and starts from scratch with each attach / container.

Improve this by:
  - [x] Remembering the last `workspaceFolder`, installed extensions and dynamically forwarded ports for each image.
  - [x] Associate a devcontainer.json with the image of a container and allow the user to edit it.

**Comment by Chuxel** [comment]
The second item on this list is related to #633 (if not a dupe).  Also, FYI, #538 also requests the ability to specify an alternate user for the attach workflow which is a related request.

**Comment by chrmarti** [comment]
Also added a command to open any of the existing configurations.
