### ISSUE TITLE
Run Asp.NetCore App With SPA crash integrated console

### ISSUE THREAD

**Issue by xaraskas** [microsoft/vscode-remote-release#1384]
Issue Type: <b>Bug</b>

1. Get a Asp.NetCore App with Angular (with many packages).
   - @angular/cli 8.3.3
   - dotnet 2.2.401
2. Run command `dotnet run --urls https://localhost:44350`.
3. Waiting for npm to compile the single page app.
4. The integrated console crash (VS Code flash and no more output of the console)

The screenshot of the problem : 
![image](https://user-images.githubusercontent.com/3975143/64495913-76541180-d26d-11e9-9754-9c4e56912887.png)

Extension version: 0.39.5
VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (3.82GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2801)|
|Memory (System)|15.86GB (3.82GB free)|
|VM|0%|
</details>

**Comment by Tyriar** [comment]
@craigloewen-msft are you aware of an issue around dotnet in wsl1 (I'm assuming)?

**Comment by craigloewen-msft** [comment]
This isn't something I'm aware of. I wonder if it's related to the other Terminal closing issue: https://github.com/microsoft/vscode/issues/78886.

@xaraskas are you using the bash shell or the zsh shell when running this? Seems like bash from your screenshot.

**Comment by xaraskas** [comment]
@craigloewen-msft, hi use the default bash shell. But what append, it's when the spa start building, the output of the command in the terminal goes "blank" and the app stop working. When I run the same command in Windows everything works.

**Comment by Tyriar** [comment]
When this happens against can you try:

- ctrl++, ctrl+- to redraw the terminal
- Check devtools (help menu) console for errors
