### ISSUE TITLE
cannot open remote terminal

### ISSUE THREAD

**Issue by l1xiao** [microsoft/vscode-remote-release#1385]
Issue Type: <b>Bug</b>

>>>Opening a terminal on the remote host from VS Code is simple. Once connected, any terminal window you open in VS Code (Terminal > New Terminal) will automatically run on the remote host rather than locally.

I follow above to start a terminal, but the local terminal was lauched instead of remote

Extension version: 0.45.6
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 4.15.0-60-generic
Remote OS version: Linux x64 4.15.0-59-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3899)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.54GB (5.93GB free)|
|Process Argv|--new-window|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: r740|
|OS|Linux x64 4.15.0-59-generic|
|CPUs|Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (64 x 3367)|
|Memory (System)|125.37GB (63.87GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment]
/needsMoreInfo 

Please provide detailed steps for how to reproduce this behaviour.
