### ISSUE TITLE
How to use non 22 ssh port in visual studio code insiders remote developments?

### ISSUE THREAD

**Issue by hylepo** [microsoft/vscode-remote-release#139]
ssh login by authentication is working fine.

    C:\Users\${DEVELOPER_NAME}>ssh ${HOST_IP_ADDRESS} -l ${DEVELOPER_NAME} -p ${SSHD_PORT} -i D:\prefix\PuTTY\${OPENSSH_FORMAT_PRIVATE_KEY}
    Last login: Sun May  5 15:27:50 2019 from 10.40.171.44
    Welcome to ...
    [${DEVELOPER_NAME}@${HOST_AKA} ~]$

but sshd is running on 36000 not default 22 port, how can I tell that to vs code remote-ssh plugin

    Host ${DEVELOPER_NAME}@${HOST_IP_ADDRESS}
    HostName ${HOST_IP_ADDRESS}:${SSHD_PORT}
    User ${DEVELOPER_NAME}
    Port ${SSHD_PORT}
    IdentityFile D:\prefix\PuTTY\${OPENSSH_FORMAT_PRIVATE_KEY}

this way gives me

    Can't connect to ${DEVELOPER_NAME}@${HOST_IP_ADDRESS}: unreachable or not Linux x86_64 (ssh: connect to host ${HOST_IP_ADDRESS} port 22: Connection refused)

and

    ${DEVELOPER_NAME}@${HOST_IP_ADDRESS}:${SSHD_PORT}

in `Remote-SSH: Connect to Host...` gives me

    Can't connect to ${DEVELOPER_NAME}@${HOST_IP_ADDRESS}:${SSHD_PORT}: unreachable or not Linux x86_64 (ssh: Could not resolve hostname ${HOST_IP_ADDRESS}:${SSHD_PORT}: Name or service not known)

**Comment by sun11** [comment]
The `HostName` should not contain your port, `HostName ${HOST_IP_ADDRESS}` and `Port ${SSHD_PORT}` worked for me.

**Comment by hylepo** [comment]
> The `HostName` should not contain your port, `HostName ${HOST_IP_ADDRESS}` and `Port ${SSHD_PORT}` worked for me.

tried this first, not working

**Comment by hylepo** [comment]
It just ignores Port 36000 option, why would it do that....

**Comment by kieferrm** [comment]
@hylepo, pls confirm that the following works on your machines:

1) Your ssh config file contains the following entry that is not overwritten by any wildcard configurations:

```
Host <server>
    HostName <your server address>
    User <your user>
    Port 36000
```

2) In a terminal `ssh <server>` is successfully connecting to your server.

**Comment by hylepo** [comment]
> @hylepo, pls confirm that the following works on your machines:
> 
> 1. Your ssh config file contains the following entry that is not overwritten by any wildcard configurations:
> 
> ```
> Host <server>
>     HostName <your server address>
>     User <your user>
>     Port 36000
> ```
> 
> 1. In a terminal `ssh <server>` is successfully connecting to your server.

@kieferrm thanks for the reply. Just as I mentioned at the first, `ssh ${HOST_IP_ADDRESS} -l ${DEVELOPER_NAME} -p ${SSHD_PORT} -i D:\prefix\PuTTY\${OPENSSH_FORMAT_PRIVATE_KEY}` is successfully connected to the server, check it out below
![image](https://user-images.githubusercontent.com/4371599/57214560-f0089400-701c-11e9-9630-39cb42edd2b6.png)
![image](https://user-images.githubusercontent.com/4371599/57214628-28a86d80-701d-11e9-91fb-9170b450981a.png)
![image](https://user-images.githubusercontent.com/4371599/57214716-66a59180-701d-11e9-8b63-54a32cea4eaa.png)
![image](https://user-images.githubusercontent.com/4371599/57214703-5db4c000-701d-11e9-96cf-9841a6a63ce3.png)

**Comment by hylepo** [comment]
Manually changed `type "${i}" | ${h()} ${u(n)} ${r}` to `type "${i}" | ${h()} ${u(n)} ${r} -p 36000 -i D:\\prefix\\PuTTY\\pvt_key_openssh ` in extension code, then it connects

**Comment by hylepo** [comment]
then is wget internet file, but my server has no internet access.
manually downloaded from internet and uploaded to server
then it comes
Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /data/xianhuadu/workspace/vscode-server-linux-x64/node_modules/spdlog/build/Release/spdlog.node)

so it depends, advanced glibc, i have to upgrade glibc now, god plz help me

**Comment by roblourens** [comment]
The GLIBC error is tracked here: https://github.com/microsoft/vscode-remote-release/issues/103
