### ISSUE TITLE
Disabling automatic reconnectes

### ISSUE THREAD

**Issue by michaelardo** [microsoft/vscode-remote-release#1393]
First of all I would like to thank you for making a great piece of software that I and millions around the globe enjoy using!

As a way to hopefully make the extension even better, I would suggest you consider allowing users to disable the automatic reconnect feature in the settings of the extension.

A valid use-case would be for companies using 2FA for ssh logins( it's rare but we do exist).Our company uses one-time passwords for logins and in case of a network hiccup the extension uses that password over and over until the account gets locked out.

Would be a great and welcome edition to allow disabling the feature.

Thanks!

**Comment by roblourens** [comment]
The extension doesn't save the password and isn't using the password over and over. Can you give some more details? Like if you can reproduce this and share teh Remote-SSH log from the output panel that would be helpful.

**Comment by michaelardo** [comment]
I will make sure to save the Remote-SSH log when this happens again. 

In the meantime,I originally failed to say that my SSH config also utilizes a ProxyJump.
The full config looks something like:

Host my-machine
    Hostname 1.1.1.1
    ProxyJump user@server
    User root
I am not sure if that might cause multiple failed logins to occur

Thanks for looking into it!

**Comment by roblourens** [comment]
If you are using windows, note that there is this issue with ProxyJump and windows' OpenSSH: https://github.com/microsoft/vscode-remote-release/issues/18#issuecomment-507258777

But it sounds like you are able to connect at least so that's probably not related.

**Comment by michaelardo** [comment]
After taking a closer look at the authentication attempts  I saw that they were actually mostly performed at night and after inspecting the macOS event logs it appeared to wake up in order to check for updates e.t.c.

After disabling the PowerNap feature of the OS - the issue never occurred again.

Sadly, I didn't figure out what exact process was attempting to reconnect multiple times, but the only three places using the password were VS Code , Safari and Hyper. So it was one of those.Hope this might help someone with the same issue
