### ISSUE TITLE
Wrong sleep configuration when adding configuration files for alpine container

### ISSUE THREAD

**Issue by october21** [microsoft/vscode-remote-release#1394]
For example we have docker-compose.yml file with alpine based web container.

When we use `Remote-Containers: Add Development Container Configuration Files` from docker-compose and choose web container we have created `.devcontainer/docker-compose.yml` with following content in `command` key:

`# Overrides default command so things don't shut down after the process ends.
    command: sleep infinity`

But Alpine doesn't support `infinity` arg for sleep command and therefore our container failed to run with exit code 1.
Instead of this following content must be in `command` for same behavior as `infinity`:

`# Overrides default command so things don't shut down after the process ends.
    command: sleep 3600`

Steps to Reproduce:

1. Setup latest Alpine Linux with docker-compose.yml
1. Run `Remote-Containers: Add Development Container Configuration Files` and choose from docker-compose.yml

**Comment by Chuxel** [comment]
@october21 Good catch! Will update.
