### ISSUE TITLE
try-node example - bash: cannot set terminal process group (-1) error

### ISSUE THREAD

**Issue by razilevin** [microsoft/vscode-remote-release#1397]
- VSCode Version: Version: 1.39.0-insider
Commit: 55825e9ad2aa4b4b3f8b2290a54a517bc454a7a5
Date: 2019-09-10T05:23:19.252Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
- Local OS Version: Mac OS Mojave 10.14.6
- Remote OS Version: 
- Remote Extension/Connection Type: Docker (Docker Desktop For Mac)

Steps to Reproduce:

1. Clone https://github.com/Microsoft/vscode-remote-try-node
2. Launch In Remote Container

Notice in the log it that it complains about forking the remote monitor process.
[Log](https://gist.github.com/razilevin/4efc5fd95f0a1da55e81edd381782dfe)

**Comment by roblourens** [comment]
@chrmarti I haven't changed anything around that recently.

**Comment by Chuxel** [comment]
@razilevin This could be due to #1465 - Can you retry with the latest bits?

**Comment by Chuxel** [comment]
Likely no longer repros with latest insider bits since #1465 is fixed - please reopen if you see it again.
