### ISSUE TITLE
Remote fails if WSL executes TMUX by default

### ISSUE THREAD

**Issue by ryankmcintyre** [microsoft/vscode-remote-release#14]
- VSCode Version:  1.34.0-insider
- Local OS Version:  Windows 10, 18351.26
- Remote OS Version:  Ubuntu 18.04
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1.  Install tmux in WSL
2.  Add "exec tmux" to .bashrc and reload shell (may not have to do the reload since Code starts new session)
3.  Install remote extension, if not already installed
4.  Run "code-insiders ." in WSL

Code launches and tries to start up the remote connection, but fails with "open terminal failed: not a terminal" and "VS Code Server for WSL closed unexpectedly."

**Comment by jonaspetersorensen** [comment]
tmux works for me when I started it using just `tmux` and not `exec tmux` in my `.zshrc` file.
The downside is that the vscode terminal will then attach to an existing tmux session and stuff will look strange in my regular terminal.

My final solution was to use zsh tmux plugin with the following configuration
```
# zsh tmux settings
ZSH_TMUX_AUTOSTART="true"
# do not autoconnect to existing session, allows a new iTerm tab to open with a new tmux session
ZSH_TMUX_AUTOCONNECT="false"

# And add tmux as a plugin
plugins=(git zsh-dircolors-solarized tmux kubectl docker)
```
and now everything works ok.

**Comment by aeschli** [comment]
To use tmux in WSL, run `chsh -s $(which tmux) $USER`.
This sets tmux as your default shell.

**Comment by ryankmcintyre** [comment]
@aeschli I still want to use bash as my shell so changing my default to tmux won't work for me. I want tmux to start by default when I launch WSL so I have `exec tmux` or, as @jonaspetersorensen tried, just `tmux` in my .bashrc file. The former flat out won't work and causes the error originally logged in this issue, the latter doesn't throw an error but results in unwanted behavior between VSCode and the console.

I'm still searching for a good solution for bash.

**Comment by ryankmcintyre** [comment]
I have a bit of a workaround that is working well for me so far. I looked at the environment vars set when initiating a WSL connection from VSCode and found a few specific to VSCode. I chose to key off of TERM_PROGRAM, so in my .bashrc file I check for that and if it's set to "vscode", I use a tmux session called vscode. Otherwise, I use a default tmux session.

```
if command -v tmux &> /dev/null && [ -z "$TMUX" ] && [ "$TERM_PROGRAM" == "vscode" ]; then
    tmux attach -t vscode || tmux new -s vscode
elif command -v tmux &> /dev/null && [ -z "$TMUX" ]; then
    tmux attach -t default || tmux new -s default
fi
```
