### ISSUE TITLE
How to improve the architecture

### ISSUE THREAD

**Issue by lars18th** [microsoft/vscode-remote-release#140]
Hi,

After some days trying this _interesting_ project, I feel some improvements in the architecture are required to improve the compatibility and usability.

Here my suggestions:
- Dependencies: Instead of create a closed list of supported platforms as now, the use of static binaries can improve the compatibility. At time, the remote environment links to shared libraries, and this is the cause of a lot of problems. Please, consider to use _only_ **static** binaries.
- SSH forwarding: The current network model is very simple and prone to errors: stablish an initial SSH session and forward ports to interchange data between VSCode client and the remote service. However, this generates troubles in a multiplatform environment. For example, in Windows clients you lack the Master Control Session to multiplex connections. Similar problems appears when you use alternative ports and firewalls. So one improved solution can be this: Include in the server one static binary of `Dropbear`. Then after the initial connection using the host regular SSH server, the vs-server service will starts his dropbear server in a random port listening only in localhost, and stablish a tunnel over the initial connection to this dropbear. After that it creates a custom certificate only for use in this connections and share it over the initial session. So, the final result is that VSCode client and the VS-remote-service can connect over a "custom" SSH connection using Dropbear (and perhaps using too a custom SSH client). This will overcome all limitations and can support any architecture, as then all binaries are the same.
- Initial check: Instead of the custom approach to execute commands in the remote server as they are required, an initial _full_ check is required. Think in the `configure` tool as an example. It checks all dependencies _before_ compiling anything. And with this initial check is possible to ensure that if the host passes all checks, then all will run as expected.

I hope developers will like to consider these changes. Futhermore, if you have another suggestions, please share here your opinion.

Regards.

**Comment by kieferrm** [comment]
@lars18th what you're proposing has merits but also downsides. We tried to find a balance between minimal requirements on the remote server, no assumptions about the admin rights of a given user, and also maintenance costs on our side. For example, if I understand your second proposal correctly, then this is the same model `BigDig` follows but it assumes that a user has the right to open additional ports on a remote machine.

**Comment by lars18th** [comment]
Hi @kieferrm ,

I'm only discussing "ideas" to reduce troubles. For example, the idea of running a "full test" before doing anything I feel it's a must have. Futhermore, if this "test" be an independent downloadable script, then any user can use it to check if a "server" is compatible before installing anything. I'm sure this will reduce the number of issues. And similar for the static compilation.

Regards.

**Comment by bamurtaugh** [comment]
Thanks for the discussion here. As it's been some time since there has been activity in this issue, closing it out. Please feel free to let us know if you have any other questions or feedback!
