### ISSUE TITLE
Where to get the latest vscode-server

### ISSUE THREAD

**Issue by zsynacl** [microsoft/vscode-remote-release#1403]
due to some reason, extension "Remote-WSL" can not download vscode-server automatically from my network. I used to download vscode-server using the commit info  the extension gave when it failed to download the package.

```shell

[2019-08-19 03:46:26.082] Launching C:\Windows\System32\wsl.exe sh -c "\"\$(wslpath -u 'c:/Users/zsy/.vscode/extensions/ms-vscode-remote.remote-wsl-0.39.2/scripts/wslServer.sh')\" 'f06011ac164ae4dc8e753a3fe7f9549844d15e35' 'stable' '.vscode-server' '' 0  " in c:\Users\zsy\.vscode\extensions\ms-vscode-remote.remote-wsl-0.39.2
```

But this time the extension did not show any error but only wait there, so I can't download the latest package since I don't have the latest commit info.
![图片](https://user-images.githubusercontent.com/4392800/64753928-99294300-d557-11e9-951b-c8e3cc1bac5e.png)

So I am wondering if I could know where to get the latest commit so I can download the package manually.

**Comment by zsynacl** [comment]
I found a log file inside the extension folder
![图片](https://user-images.githubusercontent.com/4392800/64754128-7f3c3000-d558-11e9-8ddc-8f88881b61f8.png)
Seems I got the right url from the log

**Comment by aeschli** [comment]
The log now contains the download URL.
