### ISSUE TITLE
Release for older versions of VS Code?

### ISSUE THREAD

**Issue by KyleMylonakis** [microsoft/vscode-remote-release#1406]
Is there a download of this extension available which is compatible with VS Code 1.32.3?

When I install from the store I get the following error:

Unable to install because, the extension 'ms-vscode-remote.remote-ssh' compatible with current version '1.32.3' of VS Code is not found.

Thanks for your help!

**Comment by roblourens** [comment]
That's an old version of VS Code, please update.
