### ISSUE TITLE
Support for the Include directive in ssh config file

### ISSUE THREAD

**Issue by daveletourneau** [microsoft/vscode-remote-release#1408]
Having to work with near a hundred systems via SSH, I find it useful to split them into multiple files that are included in the main `.ssh/config`. Unfortunately, vscode-remote does not support this feature but it would be great and allow to group them (by their filename?) in the SSH targets panel. See http://man7.org/linux/man-pages/man5/ssh_config.5.html for the `Include` directive.

**Comment by roblourens** [comment]
Got https://github.com/microsoft/vscode-remote-release/issues/65 for this
