### ISSUE TITLE
First time running code in Debian WSL distro results in wget:not found

### ISSUE THREAD

**Issue by craigloewen-msft** [microsoft/vscode-remote-release#1410]
- VSCode Version: 1.38.0
- Local OS Version: -
- Remote OS Version: -
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Install the Debian package for WSL
2. Run `code .` to open folder in VSCode remote
3. Receive error that wget is not installed.
![image](https://user-images.githubusercontent.com/42221804/64826277-00a1bb80-d575-11e9-8f05-cb114b5a024c.png)

You can fix this error by installing wget, is there a way to make this simpler for first time WSL users, such as detecting if wget is not installed?

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by aeschli** [comment]
Detecting the missing wget and showing a better message in 0.39.7 (requires latest insider build)
