### ISSUE TITLE
Files on bind mounted Docker volume require ludicrous latency between editing and saving

### ISSUE THREAD

**Issue by ebednarz** [microsoft/vscode-remote-release#1414]
- VSCode Version: Insiders 1.39.0
- Local OS Version: Windows 10 Home 1909
- Remote OS Version: Alpine Linux (node:12-alpine)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Edit and save a file on a bind mounted volume
2. If latency between edit and save is less than about 3 seconds (!) , the failed to save / compare versions prompt is spawned

Does this issue occur when you try this locally?: does not apply
Does this issue occur when you try this locally and all extensions are disabled?: does not apply (can disable all but remote container extensions)

I haven't experienced that with Windows 10 1903, btw.

**Comment by egamma** [comment]
@ebednarz have tried to set the consistency to 'delegated' (https://github.com/microsoft/vscode-docs/blob/master/remote-release-notes/v1_38.md#mount-consistency), does this help?

**Comment by ebednarz** [comment]
@egamma I thought that was only for osxfs? I had the described symptoms twice, right now I can't reproduce it. Will try when it comes back.

**Comment by ebednarz** [comment]
After signing out and in again, editing and saving resumed to work flawlessly. This might actually be Docker Desktop for Windows not handling suspension very well for bind mounted volumes?

**Comment by chrmarti** [comment]
We have seen intermittent problems with bind mounts on Windows. Does this still happen or did it go away for now?

**Comment by ebednarz** [comment]
@chrmarti Unfortunately it's difficult and time consuming to create a reliable reproduction path. It happened four days in a row though. It seems that I can always reproduce it like this:

1) Manually hibernate machine with project open
2) Wake up the machine again
3) Symptoms of bug report are back

I manually enabled hibernation as a power option for this as I couldn't reproduce it with sleep, at least not after a short period. It is my impression though that the machine often hibernates by itself after a while. I've seen numerous complaints about that being unpredictable on Windows 10, but I've been using it for too short a period to say something about that myself.

**Comment by ebednarz** [comment]
For completeness: after recreating the symptoms of the bug report with hibernation I was able to fix them by

1) Restarting Docker Desktop
2) Reconnecting to the container with VSCode once the daemon is up

Unfortunately that's very time consuming. :(

**Comment by chrmarti** [comment]
You could also try using a Docker volume to check out your repository. That shows the best performance in our experience. See https://code.visualstudio.com/docs/remote/containers-advanced#_use-a-named-volume-for-your-entire-source-tree.

**Comment by ebednarz** [comment]
That would be more complicated for me, at least for Node.js containers. My standard version control structure for Node projects is

- config/
- source/

and in the developmeent container

- config/
- app/
    - source/
    - [symlinks to files in config]

where `config` and `source` are bind mounts.

That way I can edit `package.json` both on the host and in the container and `node_modules` is not exposed on the host at all. Performance of that strategy has been great for me ever since I came up with that on macOS (Docker osxfs is dog slow with a large amount of bind mounted files, and named volumes used to randomly unmount).

**Comment by chrmarti** [comment]
Since this appears to be an issue with the bind mount and not VS Code: Could you open an issue with Docker Desktop for Windows: https://github.com/docker/for-win/issues? Thanks!

**Comment by chrmarti** [comment]
We now support opening folders in WSL inside a container and you can also clone a repository into a Docker volume. Both should have improved file IO performance. Closing.
