### ISSUE TITLE
Reopen/Rebuild container causes "Error: (HTTP code 503) unexpected"

### ISSUE THREAD

**Issue by kidlj** [microsoft/vscode-remote-release#1416]
Output:

```
Setting up container for folder or workspace: /Users/mellon/Remote/beyondELB-test
Error: (HTTP code 503) unexpected -  
        at /Users/mellon/.vscode/extensions/ms-vscode-remote.remote-containers-0.74.0/dist/extension.js:1:254204
        at /Users/mellon/.vscode/extensions/ms-vscode-remote.remote-containers-0.74.0/dist/extension.js:1:254167
        at m.buildPayload (/Users/mellon/.vscode/extensions/ms-vscode-remote.remote-containers-0.74.0/dist/extension.js:1:254177)
        at IncomingMessage.<anonymous> (/Users/mellon/.vscode/extensions/ms-vscode-remote.remote-containers-0.74.0/dist/extension.js:1:253677)
        at IncomingMessage.emit (events.js:187:15)
        at endReadableNT (_stream_readable.js:1092:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
```
- VSCode Version:

```
$ code --version
1.38.1
b37e54c98e1a74ba89e03073e5a3761284e3ffb0
x64
```

- Local OS Version:
macOS 10.14.6 (18G87)

- Remote OS Version:

```
$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[centos@lijian-k8s-node1 ~]$ docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:26:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:28:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Remote Extension/Connection Type: SSH/Docker/WSL
Docker

Steps to Reproduce:

1. Build a remote container for first time, it works well.
2. Close remote connection.
3. Reopen/rebuild the remote container.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
Could you attach your devcontainer.json and Dockerfile?

**Comment by kidlj** [comment]
It seems not to be an issue of devcontainer.json or Dockerfile, since they work normally on my another remote Docker host, with Reopen/Rebuild all fine.

I guess may be it's a problem of the remote Docker host, since I have by force deleted some running containers/images of VSCode remote. I wonder if there is a way to fix this or get more debugging info printed? Thanks.

**Comment by chrmarti** [comment]
Does `docker pull alpine` work? This sounds like an issue with the daemon, maybe restart that or check if https://github.com/docker/hub-feedback/issues/1632 applies.

**Comment by kidlj** [comment]
It was caused by the `http.proxy` setting in devcontainer.json. I thought that this is a setting used by VSCode process/extensions in remote container *after* container creation, but it seems that it uses this proxy setting *on* container creation. I'm confused.

Here's how to reproduce:

1. build a remote container *without* `http.proxy` settings in devcontainer.json
2. after the container started, open the 'remote' settings tab, set `http.proxy` to a proxy. In my example: `http://10.20.9.10:8118`.
3. close the connection.
4. Reopen the container. 

It's the 'remote' proxy setting read from cache that fails, and you have to delete the cached settings from `~/Library/Application\ Support/Code/CachedConfigurations/user/dev-container+**`, and reconnect to the container, it should work.

**Comment by kidlj** [comment]
<img width="1680" alt="WX20190918-172847@2x" src="https://user-images.githubusercontent.com/300616/65136951-10207900-da3b-11e9-831f-723e481ef3f8.png">
