### ISSUE TITLE
Customizable build-args

### ISSUE THREAD

**Issue by matevarga** [Microsoft/vscode-remote-release#142]
Use case:
The specific use case I have is that I need to set env vars inside the container at startup (credentials).

Problem:
Right now this is not possible, because the 'runArgs' array in the devcontainer.json file doesn't allow variable substitution (e.g. `"-e","MY_CREDS=$MY_LOCAL_CREDS"` won't work as `$MY_LOCAL_CREDS` won't be substituted).

Requested feature:
support var substitution with runArgs

Thanks.

**Comment by egamma** [comment]
This supported with the syntax "before ${env:SOMETHING} after". It evaluates to the value of the environment variable SOMETHING between the literal strings before and after.

**Comment by matevarga** [comment]
Brilliant, thanks, that works.

This project is _huge_ for remote teams and/or BYOD companies, please continue the great work. :)

**Comment by egamma** [comment]
//fyi @chrmarti @Chuxel
