### ISSUE TITLE
Fail to connect to remote server

### ISSUE THREAD

**Issue by cl406215003** [microsoft/vscode-remote-release#1421]
版本: 1.39.0-insider (user setup)
提交: d157c2e941cae17acb79bf26a70bbfad732bdc83
日期: 2019-09-16T06:06:10.647Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
![image](https://user-images.githubusercontent.com/39961012/64955272-64e8b600-d8ba-11e9-8704-1ca4ecbb8630.png)

a few minuets ago ,i can connect to remote linux system,but when i installed the newest version and update,vscode insider has this error as the image. and vscode(not insider) is work normally .

**Comment by leomoty** [comment]
Same here:

```
Could not establish connection to "Dev". y.onDidWriteData is not a function.
```

```
Version: 1.39.0-insider (user setup)
Commit: d157c2e941cae17acb79bf26a70bbfad732bdc83
Date: 2019-09-16T06:06:10.647Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by jmoses-ds** [comment]
This is also #1419

**Comment by jmoses-ds** [comment]
and #1417

**Comment by Riconec** [comment]
VSCode updated itself and I am unable to use Remote-SSH now, exactly the same error. And overall stability of ssh connection with vscode remote is very bad... 
P.S. I am on RPi3 as remote server

**Comment by egamma** [comment]
duplicate #1417
