### ISSUE TITLE
Remote Explorer polish

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1426]
Related to https://github.com/microsoft/vscode-remote-release/issues/926

- Polish labels (no need to show "Targets")
- Expand the section for the currently used remote type, and collapse the other sections.

**Comment by roblourens** [comment]
Question for @sandy081 or @alexr00 

What I want to happen in the remote explorer:

- When I have an SSH workspace open, the 2 views from the SSH extension (and the help view) are initially expanded, and the others are collapsed
- Likewise for the Containers or WSL extensions
- In a local folder, all views are initially expanded

To do this we have to know somehow which remote authorities are associated with which contributed views. We could do this by figuring out which extension registered the current remote authority resolver, then figure out which remote views were also contributed by that extension, and expanding those views, but this is a hack. It won't work if the views are contributed by a different extension (currently like the remote-ssh-explorer extension although that will go away) and it won't work if the extension contributes more than one remote resolver (future?).

That might be an ok hack to try this out for a month, but I am thinking we could also just directly associate a view with a remote authority like

```json
"contributes": {
    "views": {
        "remote": [
            {
                "id": "sshHosts",
                "name": "Targets (SSH)",
                "when": "config.remote.SSH.enableHostsExplorer",
                "group": "targets@1",
                "remoteAuthority": "ssh-remote"
            },
```

Is this ok to do? I see where I would have to copy the property over to `ICustomViewDescriptor` or a sub interface of it here https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/browser/viewsExtensionPoint.ts#L419-L431

Then on `RemoteViewlet` in remote.ts, we would check this and set the initial expand state of each view when it's added to the panel.

But I don't know much about this area of code, how bad/hacky is that?

**Comment by sandy081** [comment]
Handling this in `RemoteViewlet` makes sense and `viewExtensionPoint` code is pretty clean.
Looks like you want to introduce a remote view specific properties. Is there a way for remote viewlet to get this information from other contribution points, say, remote ssh view might already provide this info that it handles `ssh-remote` authority in other contribution points?

**Comment by roblourens** [comment]
>  Is there a way for remote viewlet to get this information from other contribution points, say, remote ssh view might already provide this info that it handles ssh-remote authority in other contribution points?

I don't understand exactly what you are asking. But this info doesn't show up in any other contribution point as far as I'm aware.

Related question - there is no way for an extension to expand/collapse the view pane, right? Wondering whether it's possible for the extensions to implement this direct but it doesn't look like it.

**Comment by sandy081** [comment]
Yeah, collapsible state of the views cannot be controlled from extensions.

**Comment by roblourens** [comment]
Please review https://github.com/microsoft/vscode/commit/0719e0ae4285e76a0f6ef2c0b8698d86239f761e @sandy081
