### ISSUE TITLE
"Installing dev container" never ends

### ISSUE THREAD

**Issue by christianayala10** [microsoft/vscode-remote-release#1431]
I have a remote host with Centos 7 where docker 18.09 is running. When I try to "attach my VSC Insiders v1.39 to a remote container" my VSC installs the agent and so on correctly. Then when I try to locate my workdir by performing "open folder" my VSC tries to install the agent again. The dev container console shows "Setting up container ..." indefinitely.

I have downgraded Remote - Containers from 0.76.0 to 0.75.0 and works perfectly.

UPDATED (24/09/2019): The problem is still present in version 0.77.0

**Comment by chrmarti** [comment]
Tried to repro with 0.77.0. This works for me on Mac:
- `docker run -d centos:7 sleep infinity`
- Attach to new container.
- Open `/root` folder in container.

Are you saying the Docker daemon runs on CentOS? What kind of container are you using?

**Comment by chrmarti** [comment]
How did you configure Docker / Remote-Containers to connect to the remote CentOS? Is CentOS run with Windows' WSL?

**Comment by christianayala10** [comment]
No, CentOS is running by itself without a Windows subsytem. We have configure Remote-Containers by setting: DOCKER_CERT_PATH, DOCKER_HOST and DOCKER_TLS_VERIFY environment variables.

**Comment by chrmarti** [comment]
Could you check if there are any entries in the console? (Help > Toggle Developer Tools)

**Comment by christianayala10** [comment]
Here's my VSC's terminal otput:

- 0.75.0 [(output)](https://pastebin.com/8SRHwVLH)
- 0.77.0 [(output)](https://pastebin.com/ELunYZVH)

**Comment by chrmarti** [comment]
Could you also check the console in the dev tools (Help > Toggle Developer Tools)? That might have some more output.

**Comment by chrmarti** [comment]
Could you check if there is a `ms-vscode-remote.remote-containers` folder in `~/.config/Code\ -\ Insiders/User/globalStorage`? What permissions does it (or the `globalStorage` folder) have?

**Comment by christianayala10** [comment]
The path you have told me doesn't exists. I have found this other path `~/.vscode-server-insiders/data/User`. There:

     drwxr-xr-x. 4 root root 51 Sep 17 10:44 .
     drwxr-xr-x. 5 root root 62 Sep 16 08:38 ..
     drwxr-xr-x. 2 root root  6 Sep 16 08:38 globalStorage
     drwxr-xr-x. 3 root root 46 Sep 17 10:44 workspaceStorage

**Comment by chrmarti** [comment]
Sorry, please check on Windows 10 (cmd.exe syntax): `dir "%APPDATA%\Code - Insiders\User\globalStorage"`

**Comment by christianayala10** [comment]
26/09/2019  13:05    <DIR>          .
26/09/2019  13:05    <DIR>          ..
13/09/2019  11:21    <DIR>          ms-vscode-remote.remote-containers
26/09/2019  13:05           151.552 state.vscdb
26/09/2019  13:05           151.552 state.vscdb.backup

**Comment by chrmarti** [comment]
Any files in `ms-vscode-remote.remote-containers`?

Could you also retry with the latest version of the extension (0.78.0)?

**Comment by christianayala10** [comment]
```
ms-vscode-remote.remote-containers
13/09/2019  11:21    <DIR>          .
13/09/2019  11:21    <DIR>          ..
13/09/2019  11:21    <DIR>          imageConfigs
```
It doesn't work neither with the latest version 0.78.0

**Comment by chrmarti** [comment]
What's in the imageConfigs folder? Could you also check if the Dev Containers terminal stops at the same point as before?

**Comment by christianayala10** [comment]
imageConfigs folder is empty. Dev Containers terminal stops at the same point, it shows:
`Setting up container with 555305e71352f68ba1e238d86c4e388bf852e8707b64c754da9f6a33d706b882`

**Comment by chrmarti** [comment]
Could you retry with the latest version (0.79.0)? That includes another change that might affect this.

**Comment by christianayala10** [comment]
Solved!

**Comment by chrmarti** [comment]
Great, thanks!

**Comment by alexr00** [comment]
Verified by original issue filer.
