### ISSUE TITLE
Freeze when installing extension on remote container 

### ISSUE THREAD

**Issue by bilykigor** [microsoft/vscode-remote-release#1433]
- VSCode Version: 1.39.0
- Local OS Version: Win10
- Remote OS Version: Centos 6
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

Try attach vscode to remote container with
"remote.containers.defaultExtensions": [
        "ms-vscode.cpptools"
    ]

Got freeze on this step:

Installing extensions...
Installing extension 'ms-vscode.cpptools' v0.25.1...
Extension 'ms-vscode.cpptools' v0.25.1 was successfully installed.
Run: docker exec -w /root/.vscode-server-insiders/bin/211fa02efe8c041fd7baa8ec3dce199d5185aa44 -e VSCODE_AGENT_FOLDER=/root/.vscode-server-insiders b29406f2a72853aad3ce3f073e4f1679fc47690593cbda0be1cf3b79297937b2 /root/.vscode-server-insiders/bin/211fa02efe8c041fd7baa8ec3dce199d5185aa44/server.sh --list-extensions

Without ms-vscode.cpptools extension installed there is no problem. 
Problem appears when try install extension.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bilykigor** [comment]
The problem is in vscode-insiders.
Regular vscode works fine.

**Comment by chrmarti** [comment]
@bilykigor There have been fixes in this area, is this still an issue with the latest version?

**Comment by bilykigor** [comment]
for now case is fixed
