### ISSUE TITLE
The connection tries with windows username instead host conf file username

### ISSUE THREAD

**Issue by isra60** [microsoft/vscode-remote-release#1434]
Issue Type: <b>Bug</b>

I check that I can enter to my remote machine without password promt. 

Then I try to connect with remote-ssh and in the terminal I see that the username is using the windows name in the command to install...

Ths is my config file 

Host 10.50.84.90
  User ubuntu

As you can see the user is ubuntu...

So then when I try to connect to my machine which is a Jetson Tx2 with Ubuntu. 
The terminal shows.
israe@10.50.84.90's password:

Extension version: 0.46.1
VS Code version: Code - Insiders 1.39.0-insider (bdd1971f2cd9d08a8a90e02740f1850afe03da66, 2019-09-17T06:02:08.670Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by egamma** [comment]
/needsMoreInfo please provide more detailed steps and include logs.

**Comment by tombancroft** [comment]
Hi, I have the same problem.  Config for the server : 

Host hostname
  User another_user
  IdentityFile path_to_id_file
  HostName hostname
  LogLevel DEBUG

log : 

[14:49:22.005] Running script with connection command: "C:\Program Files\Git\usr\bin\ssh.exe" -D 63454 qxvsmtkafka001 bash

ie. it's not specifying the user.  If I run this at the comment line ; 

"C:\Program Files\Git\usr\bin\ssh.exe" -i path_to_id_file another_user@hostname

then it works.  It looks like it doesn't specify the user in the ssh ?

**Comment by tombancroft** [comment]
hi - using a custom ssh config for this seems to work - if i set this in preferences (ssh client) then the command line changes slightly : 

[15:15:21.195] Using SSH config file "c:\temp\customssh.config"
[15:15:21.195] Running script with connection command: "C:\Program Files\Git\usr\bin\ssh.exe" -D 64341 -F c:\temp\customssh.config hostname_new bash

it feels like it reads the custom config properly (and so picks up the User setting ) in a way it doesn't in the default. Does the default assume the logged in user ?

**Comment by roblourens** [comment]
Sorry for the slow response. if this is still an issue, please share the full log from the Remote-SSH output channel.
