### ISSUE TITLE
Failed to connect to the remote extension host server (Error: Connection error: Version mismatch, client refused.)

### ISSUE THREAD

**Issue by mesmat** [microsoft/vscode-remote-release#1436]
**Client-side VScode info:**
- Version: 1.39.0-insider (user setup)
- Commit: bdd1971f2cd9d08a8a90e02740f1850afe03da66
- Date: 2019-09-17T06:02:08.670Z
- Electron: 6.0.9
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Windows_NT x64 10.0.17763
- Remote SSH Extension: 0.46.1

- Remote OS Version: Amazon Linux 2018.03
- Remote Extension/Connection Type: SSH

**Steps to Reproduce:**

1. I have manually downloaded the vscode-server-insider commit id: bdd1971f2cd9d08a8a90e02740f1850afe03da66 using the link https://update.code.visualstudio.com/commit:bdd1971f2cd9d08a8a90e02740f1850afe03da66/server-linux-x64/insider
2. Moved the content of the extract vscode-server-linux-x64.tar.gz to ~/.vscode-server-insiders/bin/bdd1971f2cd9d08a8a90e02740f1850afe03da66

3- Tried to "Connect to Host.." and received the below output:

**Running remote connection script**
**Acquiring lock on /home/hadoop/.vscode-server-insiders/bin/bdd1971f2cd9d08a8a90e02740f1850afe03da66/vscode-remote-lock.bdd1971f2cd9d0
8a8a90e02740f1850afe03da66**
**Found existing installation at /home/hadoop/.vscode-server-insiders/bin/bdd1971f2cd9d08a8a90e02740f1850afe03da66...
Found running server...**

*
* **Reminder: You may only use this software with Visual Studio family products,**
* **as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)**
*

**Checking server status on port 36205 with wget**
**7a62783b-1994-4cc7-8189-92ebd506bc3b: start**
**sshAuthSock====**
**agentPort==36205==**
**webViewServerPort==35013==**
**osReleaseId==amzn==**
**arch==x86_64==**
**webUiAccessToken====**
**7a62783b-1994-4cc7-8189-92ebd506bc3b: end**

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
Please don't try to manually download and install the server, we don't officially support that workflow. The error implies that you ended up with mismatched client and server versions.
