### ISSUE TITLE
Environment variables are not synchronized

### ISSUE THREAD

**Issue by littleShy** [microsoft/vscode-remote-release#1437]
- VSCode Version: 1.38.1
- Local OS Version: win10 x64
- Remote OS Version: Linux server 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. open remote ssh in vscode
2. use some linux environment variable in vscode, I can get the correct value.
3. modify or add environment variable on linux server
3. use this evnironment variable in vscode settings and I cannot get its value.
4. reopen vscode or re connect remote ssh won't wrok, only works if I reboot my PC.

Does this issue occur when you try this locally?: Yes

**Comment by roblourens** [comment]
> modify or add environment variable on linux server

How are you doing this? If you are changing variables in a terminal, they will stay in that terminal. If you are changing your bashrc/profile, you will have to restart the remote server for those variables to end up in the remote vscode server. You can run the "Kill VS Code Server on Host..." command to do that.

**Comment by littleShy** [comment]
thanks，after i run  "Kill VS Code Server on Host..." command, everything wroks fine.
