### ISSUE TITLE
vscode-server don't shutdown on vscode exit with WSL

### ISSUE THREAD

**Issue by fxgsell** [microsoft/vscode-remote-release#1438]
The  vscode-server process keep running after the session is over, and each new session started spinup a new instance of the process, eventually it will fill the entire memory on the system if there is no frequent reboot. 

- VSCode Version: insider
- Local OS Version: Windows 10 (81980.1)
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Start VsCode
2. Initiate remote session
3. Close VsCode
4. Check in WSL the server is still running: `ps aux | grep vscode-server | wc -l`
5. Repeat from 1.  `ps aux | grep vscode-server | wc -l` will keep increasing with each repeat.

Does this issue occur when you try this locally?: Not applicable
Does this issue occur when you try this locally and all extensions are disabled?: Not applicable

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode-remote-release/issues/1244
