### ISSUE TITLE
Investigate automatic port forwarding based on console output

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-remote-release#1439]
Investigate how to generalise the port detection mechanism used in the "serverReady" feature.

**Comment by OmriSama** [comment]
Is it possible to have automatic port-forwarding by workspace? Meaning, whenever open a certain workspace it knows to start forwarding say, port 3000:3000?

**Comment by bamurtaugh** [comment]
I believe this has been addressed by https://github.com/microsoft/vscode-remote-release/issues/3836, so closing issue. If I'm misinterpreting the request, please just let me know, and I'm more than happy to reopen or discuss further. Thank you!
