### ISSUE TITLE
Cannot find ssh.exe path of "Git for Windows"

### ISSUE THREAD

**Issue by okmt** [microsoft/vscode-remote-release#144]
SSH connection does not work because the VS Code or the Remote-SSH extension can't find the correct ssh.exe path as follows:
> The terminal process command 'cmd.exe/c (type "C:\Users\ {USERNAME} \AppData\Local\Temp\vscode-linux-multi-line-command-{REMOTEHOST}.sh" | C:\Windows\Sysnative\OpenSSH\ssh.exe -F C:\Users\ {USERNAME} \ .ssh\config {REMOTEHOST}) & exit /b 0' failed to launch (exit code: 255)

and

> Can't connect to {REMOTEHOST}: unreachable or not Linux x86_64
> Source: Remote - SSH (Extension)

Note: I could use SSH by modifying the path of ssh.exe in the file "extension.js" manually.

- VSCode Version: 1.34.0-insider (user setup)
- Local OS Version: Windows 7 32bit
- Remote OS Version: Ubuntu 16.04 x64
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install "Git for Windows". Using the default setting, ssh.exe is installed in the "c:\Program Files\Git\usr\bin\ssh.exe"
2. Add "c:\Program Files\Git\usr\bin" to PATH
3. Install VS Code Insider and "Remote Development" extension
4. Configure .ssh/config
5. Try to connect a host written in .ssh/config

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by roblourens** [comment]
Tricky because ssh on the path may be a 64-bit binary and not valid to launch from a 32-bit process.

**Comment by garyng** [comment]
I was able to reproduce this. Windows 7 32 bit, with `git`'s `ssh` in `path`.

```
Version: 1.34.0-insider (user setup)
Commit: 473af338e1bd9ad4d9853933da1cd9d5d9e07dc9
Date: 2019-05-01T00:21:02.354Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT ia32 6.1.7601
```

Extension:
```
Name: Remote - SSH
Id: ms-vscode-remote.remote-ssh
Description: Open any folder on a remote machine using SSH and take advantage of VS Code's full feature set.
Version: 0.35.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh
```
