### ISSUE TITLE
Bracket Pair Colorizer2 extensions not working in remote

### ISSUE THREAD

**Issue by mmCodingjs** [microsoft/vscode-remote-release#1440]
Issue Type: <b>Bug</b>

Some extensions do not work in WSL. Like Bracket Pair Colorizes 2. When I'm using WSL to open some projects, the brackets still in white only

Extension version: 0.39.5
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz (4 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.87GB (4.07GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/mnt/c/Users/miigu/Documents/GitHub/offBot --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz (4 x 3700)|
|Memory (System)|11.87GB (4.07GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment]
/needsMoreInfo

>Like Bracket Pair Colorizes 2.

Bracket Pair Colorizer 2 is currently a workspace extension and needs to be installed into WSL in order to activate. Does it work once you do this?

What other extensions do not work?

**Comment by mmCodingjs** [comment]
> /needsMoreInfo
> 
> > Like Bracket Pair Colorizes 2.
> 
> Bracket Pair Colorizer 2 is currently a workspace extension and needs to be installed into WSL in order to activate. Does it work once you do this?
> 
> What other extensions do not work?

Yes, I've installed all my extensions into WSL, but the only extension I've noticed it wasnt working was `Bracket Pair Colorizer 2`.
The brackets still white even if I restart the VSCode.
If I opened with normal window, I mean, not using WSL, the extension works

**Comment by egamma** [comment]
Issue confirmed (same behaviour in Remote-Containers), this extension cannot run as a workspace extension since it tries to load the vscode-textmate module out of the asar file.

Tagging the extension as a UI extension does not work around the problem.

**Comment by egamma** [comment]
Added the extension to the list of UI extensions, for a workaround and more discussion please see
https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/issues/163#issuecomment-540609716
