### ISSUE TITLE
link file which the target not exist not show in explorer

### ISSUE THREAD

**Issue by CyrilTaylor** [microsoft/vscode-remote-release#1442]
Issue Type: <b>Bug</b>

link file which the target not exist not show in explorer, I think the link file should be shown in explorer with error mark

Extension version: 0.46.1
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.15.0-62-generic
Remote OS version: Linux x64 4.15.0-62-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (1.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|

|Item|Value|
|---|---|
|Remote|SSH: LocalServer|
|OS|Linux x64 4.15.0-62-generic|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (8 x 3192)|
|Memory (System)|7.77GB (0.17GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: LocalServer|
|OS|Linux x64 4.15.0-62-generic|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (8 x 3192)|
|Memory (System)|7.77GB (0.17GB free)|
|VM|100%|
</details>

**Comment by isidorn** [comment]
I have no clue what you are saying.
Can you please provide exact reproducable steps and potentialy a picture

**Comment by CyrilTaylor** [comment]
![image](https://user-images.githubusercontent.com/12631466/66742796-0f98c800-eeab-11e9-9743-809bce6eaa9e.png)
