### ISSUE TITLE
Does not work in code-insiders 

### ISSUE THREAD

**Issue by lab119-mai** [microsoft/vscode-remote-release#1444]
Issue Type: <b>Bug</b>

Steps to reproduce:
Try to connect over SSH
a. "Connect to Host in Current Window"
b. "Connect to Host in New Window"

Actual results:
a. and b. New window is opened, but "Remote - SSH" extension is not even shown in "Output" tabs.

There is nothing concerning "SSH Resolver" in logs and/or developer console logs; the only output is:
```
[10:53:15.405] remote-ssh@0.46.1
[10:53:15.405] win32 x64
```

With VS Code 1.38.1 (stable) Remote - SSH works as designed with the same configuration.
 
Extension version: 0.46.1
VS Code version: Code - Insiders 1.39.0-insider (575062278d181c075ea8dce345ab3d20a127309c, 2019-09-20T06:11:13.647Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Jeff010101** [comment]
It seems I met the same problem. Have you solved yet?

**Comment by roblourens** [comment]
Sorry, working on a fix.

**Comment by roblourens** [comment]
From https://github.com/Microsoft/vscode/commit/443ab8f33e08d6a001522608d9a03cd31831c9b1. There are two problems, it ignores the remoteAuthority parameter and renames `reuseWindow` to `reuse`.

**Comment by roblourens** [comment]
Unreleased the previous insiders build so you should get an update that fixes it.

**Comment by roblourens** [comment]
This is fixed in master but please check my work @bpasero

**Comment by bpasero** [comment]
@roblourens sorry for that, not sure how I could have missed that the `remoteAuthority` is being used via API :(

**Comment by bpasero** [comment]
@roblourens One thing that I am not a big fan of is how now we have a `IHostService#openEmptyWindow` with options that the web version will never support. I think that was my original intent of removing desktop only stuff from web facing services. 

I do not have a good answer though because this command is contributed for all extensions.
