### ISSUE TITLE
Breakpoints don't work in WSL because of uppercase letters in the path

### ISSUE THREAD

**Issue by ThePlenkov** [microsoft/vscode-remote-release#1447]
Hi! 

I noticed strange behavior. When I connect to my Ubuntu WSL i'm able to debug node.js app from inside. However node ignores my breakpoints.

I also noticed if I click the file name from console VS opens one more file next to already opened where breakpoints work.

I guess it happens because of capital letters in the path. Please see example:

![image](https://user-images.githubusercontent.com/6381507/65340363-55c17b00-dbce-11e9-822c-82ffc6805025.png)

**Comment by roblourens** [comment]
Can you show your launch config? It seems like we launch the app with an all lower case path, when it should have an uppercase letter.

You get the `/mnt/c/U...` path if you open a file from the explorer, right?

**Comment by ThePlenkov** [comment]
@roblourens Hi, actually I see that after version update the problem has gone.

That was my launch.json
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Debug Portal",
            "program": "${workspaceFolder}/flp/node_modules/@sap/site-entry/server.js",
            "cwd": "${workspaceFolder}/flp",
            "preLaunchTask": "makeEnv",
            "envFile": "${workspaceFolder}/.env/.env",
            "env": {
                "NODE_TLS_REJECT_UNAUTHORIZED": "0"
            }
        }
    ]
}
```

**Comment by ThePlenkov** [comment]
I'll close the issue and will reopen if it's there again. Thank you!
