### ISSUE TITLE
Allow specifying host for forwarding ports in remote explorer

### ISSUE THREAD

**Issue by vilic** [microsoft/vscode-remote-release#1448]
We are running remote workspace container with other services like mongo and redis. Usually we don't forward those ports, so I don't want to write them into SSH config file. However, currently we can only specify port in the remote explorer forwarded port.

**Comment by roblourens** [comment]
You are connecting to your remote with the Remote - SSH extension right? The `remote.SSH.defaultForwardedPorts` is probably what you are looking for. If not, please give more details.

**Comment by vilic** [comment]
@roblourens Hi, we are using "Remote - SSH" but it's not the case.

The remote workspace has access to services like MongoDB via host `mong`, Redis via host `redis` etc. And we want to dynamically forward local ports to those. E.g.:

```
LocalForward 127.0.0.1:27017 mongo:27017
```

We can configure it via SSH configuration, but we want to add it on demand because most of the time we don't need to.

**Comment by roblourens** [comment]
Oh I see, thanks

**Comment by roblourens** [comment]
This is now possible
