### ISSUE TITLE
Container Extension using 127.0.0.1 instead of localhost has unexpected results with WSL 2.0 & Docker

### ISSUE THREAD

**Issue by Drakota** [microsoft/vscode-remote-release#1449]
- VSCode Version: 1.39.0-insider
- Local OS Version: Windows Insiders 18985
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: Containers Extension with WSL

Steps to Reproduce:
1. Install WSL 2.0 following this [procedure](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install)
2. Install Docker Engine inside WSL and start the service
3. Follow this [procedure](https://github.com/LongLiveCHIEF/wsl2-docker-for-win) to expose WSL's docker instance to docker-cli on Windows
4. Make sure you're able to run Docker from Windows using the WSL's instance
![image](https://user-images.githubusercontent.com/22665836/65359218-dfbb1500-dbc9-11e9-95c4-94c9990f6ae2.png)
5. Clone the [vscode-remote-try-node](https://github.com/Microsoft/vscode-remote-try-node) repo
6. Open it with VSCode, press F1, type Reopen in container.
Get an error
![image](https://user-images.githubusercontent.com/22665836/65359428-6a9c0f80-dbca-11e9-84ea-7e7d29657d89.png)
I know for sure I can access the Docker daemon with localhost:2375, but it seems with the networking quirks of WSL 127.0.0.1 doesn't seems to map correctly to localhost as expected.

EDIT:
When I tried changing my Windows ENV variables with 127.0.0.1, I wasn't able to access the daemon. So this is clearly the issue. Is there a way to change which hostname the extension use to connect so I can point it to localhost instead of 127.0.0.1?
![image](https://user-images.githubusercontent.com/22665836/65359654-31b06a80-dbcb-11e9-92d0-6952bcf607d4.png)

Does this issue occur when you try this locally?: Yes

**Comment by Drakota** [comment]
Hi @aeschli, thanks for checking my issue.

The thing is that I don't want to connect to the WSL itself, I know I can use the Remote - WSL Extension to access files inside and do my development there, but I want to connect to a docker container that is running inside WSL. That's why I had to install docker-cli on Windows also.

**Comment by aeschli** [comment]
@Drakota No problem, thanks for reporting, we'll look into it!

**Comment by chrmarti** [comment]
@Drakota You could try setting the `DOCKER_HOST` environment variable. Or if you also have the Docker extension installed, try setting the Docker Host setting. /cc @Chuxel

**Comment by Drakota** [comment]
Hi! So I've tested it with the Docker Extension and here are my results.
Here's what I can access from Windows
![image](https://user-images.githubusercontent.com/22665836/65607151-0e464080-df7a-11e9-8f22-bb4549a038ef.png)
![image](https://user-images.githubusercontent.com/22665836/65607180-19996c00-df7a-11e9-976a-ad5e17fc856e.png)
![image](https://user-images.githubusercontent.com/22665836/65607247-3635a400-df7a-11e9-8b33-93472b786060.png)

If I set the DOCKER_HOST to localhost like this
![image](https://user-images.githubusercontent.com/22665836/65607345-60876180-df7a-11e9-86ce-6a403116fe90.png)
I get the same error as before
![image](https://user-images.githubusercontent.com/22665836/65607365-69783300-df7a-11e9-95d5-732210a44287.png)
So down the road it seems the extension assumes localhost and 127.0.0.1 are interchangeable and changes it.

If I set it to a IPv6 address like this 
![image](https://user-images.githubusercontent.com/22665836/65607446-93315a00-df7a-11e9-92f3-f30e4ad7c819.png)
VSCode does not complains that it can't connect to the daemon, but I get this.
IPv6 doesn't seems to be supported.
![image](https://user-images.githubusercontent.com/22665836/65607727-0044ef80-df7b-11e9-9ef1-25e7d6764314.png)

**Comment by chrmarti** [comment]
Your Docke daemon appears to be listening only on the IPv6 address, can you configure it to listen on both the v6 and v4 IP addresses?

**Comment by gustavovalverde** [comment]
The new VS code insiders fixed this for me: https://github.com/microsoft/vscode-remote-release/issues/1089#issuecomment-535645668 

We'll just have to wait for this to land stable

**Comment by Drakota** [comment]
Hi @gustavovalverde, it didn't fixed it for me unfortunetly. I'm not using the Docker Tech Preview also.

**Comment by chrmarti** [comment]
Upstream issue, filed: https://github.com/apocas/docker-modem/issues/105

**Comment by Drakota** [comment]
Great! Thank you @chrmarti

**Comment by armitagemderivitec** [comment]
I'm using the remote containers extension to develop on a linux docker image from Mac OS. I have two ASP Net applications in my launch.json with the "serverReadyAction" set to "openExternally". When the Chrome window opens on my Mac the URLs are formatted as https://127.0.0.1:44301 instead of https://localhost:44301. My authentication layer requires the url to be localhost and therefore my application won't start.

Is this related or shall I post a separate issue?

**Comment by chrmarti** [comment]
@armitagemderivitec Yes, that is a different issue. Please open a new issue for https://github.com/microsoft/vscode. Thanks.

**Comment by Alirezanet** [comment]
@armitagemderivitec
I have the same problem. did opened new issue? everything is redirecting to 127.0.0.1

**Comment by Chuxel** [comment]
@Alirezanet I believe this is https://github.com/microsoft/vscode-remote-release/issues/2711

**Comment by chrmarti** [comment]
Closing as we have moved off of Dockerode.

**Comment by PavelSosin-320** [comment]
@chrmarti Beware of localhost!!!!! IPV4 127.0.0.1 v!== IPV6 [::1] IPV4 client with IPV6 server [Docker IPV6 support](https://docs.docker.com/config/daemon/ipv6/). Only for IT professionals!
