### ISSUE TITLE
Failed to connect to the remote extension host server (Error: getaddrinfo ENOTFOUND localhost localhost:<port number>)

### ISSUE THREAD

**Issue by ProKil** [Microsoft/vscode-remote-release#145]
When I tried to connect to the host, it made some errors while connecting to the remote extension host server. 

The pop-up window says:

`Failed to connect to the remote extension host server (Error: getaddrinfo ENOTFOUND localhost localhost:<port number>)`

Full output of Remote-SSH:

```
SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a224c616233227d"
SSH Resolver called for host: Lab3
Setting up SSH remote "Lab3"
Using commit id "473af338e1bd9ad4d9853933da1cd9d5d9e07dc9" and quality "insider" for server
Install and start server if needed
> Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.19.0-25-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com/
> 
> 191 packages can be updated.
> 138 updates are security updates.
> 
> New release '16.04.6 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.
> 
> bash: cannot set terminal process group (30876): Inappropriate ioctl for device
> bash: no job control in this shell
> Found existing installation...
> Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> 8c747234-6d3d-4476-978b-46925f69ab0b==49074==
"install" terminal command done
Received install output: 8c747234-6d3d-4476-978b-46925f69ab0b==49074==
Server is listening on port 49074
Spawning tunnel with: ssh  Lab3 -L localhost:43960:localhost:49074 "echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity"
Spawned SSH tunnel between local port 43960 and remote port 49074
Waiting for ssh tunnel to be ready
Tunneling remote port 49074 to local port 43960
Resolving "ssh-remote+7b22686f73744e616d65223a224c616233227d" to "localhost:43960", attempt: 1
> Connected to SSH Host - Please do not close this terminal
```

Log (Window):

```
[2019-05-05 22:14:57.568] [renderer13] [error] getaddrinfo ENOTFOUND localhost localhost:43960: Error: getaddrinfo ENOTFOUND localhost localhost:43960
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
[2019-05-05 22:14:57.569] [renderer13] [error] Cannot read property 'extensions' of null: TypeError: Cannot read property 'extensions' of null
    at e.<anonymous> (file:///private/var/folders/6g/m3x943p50nbd4tlqw9rl04nw0000gn/T/AppTranslocation/048EE3CC-90D9-4B19-BD52-5E84CA8DFEDC/d/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3850:751)
    at Generator.next (<anonymous>)
    at r (file:///private/var/folders/6g/m3x943p50nbd4tlqw9rl04nw0000gn/T/AppTranslocation/048EE3CC-90D9-4B19-BD52-5E84CA8DFEDC/d/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:34:454)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-05-05 22:14:57.569] [renderer13] [error] getaddrinfo ENOTFOUND localhost localhost:43960: Error: getaddrinfo ENOTFOUND localhost localhost:43960
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
```

- VSCode Version: Version 1.34.0-insider (1.34.0-insider)
- Local OS Version: macOS Mojave 10.14.4
- Remote OS Version: Ubuntu 14.04.5 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. F1 -> Remote-SSH: Connect to Host...

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
From the log it seems the server installed and launched correctly and the tunnel is setup.

@ProKil please confirm that the terminal with the output `Please do not close this terminal` was still open.

**Comment by ProKil** [comment]
@kieferrm Yeah, the terminal was still open.

**Comment by alexandrudima** [comment]
@ProKil Can you please try in a terminal `ping localhost`. It is bizzare that `localhost` would result in `ENOTFOUND`.

@kieferrm @roblourens Would it be more general for the SSH extension to resolve with `127.0.0.1:port` then `localhost:port`. In theory, I believe it is possible to bind `localhost` to something else...

**Comment by ProKil** [comment]
@alexandrudima You mean type in SSH Tunnel Terminal? I tried and got no response. Output-Remote SSH just echoed back `ping localhost`. I also tried to start a new terminal in vscode, but it stalls while starting.

**Comment by alexandrudima** [comment]
@ProKil 

The SSH extension is trying to set up a tunnel, e.g.:

```
Spawning tunnel with: ssh  Lab3 -L localhost:43960:localhost:49074 "echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity"
```

Later the error you get is `Error: getaddrinfo ENOTFOUND localhost localhost:<port number>`

---

I thought perhaps the error means that `localhost` does not resolve to `127.0.0.1` in one of the machines. So, outside of VS Code:
* could you please open a local terminal on macOS and try `ping localhost`. Is `localhost` resolving to `127.0.0.1`?
* could you please connect via SSH (outside of VS Code) to the Ubuntu machine? Can you also try there `ping localhost`. Is `localhost` resolving to `127.0.0.1`?

**Comment by ProKil** [comment]
Great! I found `localhost` of my local machine is not bound to `127.0.0.1`. 

I put `127.0.0.1 localhost` in `/etc/hosts`, and it works. Thank you very much!

**Comment by egamma** [comment]
@Chuxel another candidate for a tips&tricks addition.

**Comment by roblourens** [comment]
Should the SSH extension use `127.0.0.1` instead of `localhost`?

**Comment by alexandrudima** [comment]
@roblourens Yes, please.

FYI @chrmarti @aeschli Please return `127.0.0.1` from your resolvers and not `localhost` since `localhost` can be rebound.
