### ISSUE TITLE
Remote-WSL server has umask set to 0000 

### ISSUE THREAD

**Issue by rbarrimond** [microsoft/vscode-remote-release#1451]
For some reason, the "instance" of Ubuntu launched by the `Remote-WSL` extension sets the umask to `0000` either ignoring or overriding the normal WSL settings which are `022`. When I create files or folders from the Explorer they have `0777` set and the ugly-to-read colors at the terminal result. 

My partial work around is to set the umask in my `.bashrc` file and do file operations at the command prompt but that's annoying and this should be fixed. Installing the Maven plugin for example had the `0777` settings om the `.m2` directory for example.

I tried

- Setting the umask with a code snippet in `/etc/profile.d/` hoping the Bourne shell running the vscode server would pick that up.
- Creating a fresh workspace.
- Using VS Code Insiders.

None worked.

- VSCode Version:
- Local OS Version:

> Version: 1.38.1 (user setup)
> Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
> Date: 2019-09-11T13:35:15.005Z
> Electron: 4.2.10
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.18362

- Remote OS Version: 
> Ubuntu 18.04 LTS
> Linux LNAR-5CG9204ZZ8 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Launch VS Code.
2. Open folder in Remote-WSL or open saved workspace file.
3. Open a terminal in VS Code.
4. Type `umask` at prompt.

Does this issue occur when you try this locally?: No

If I open the folder through the WSL integration share `\\wsl$` the umask is set to `022` which is exactly correct because WSL has the correct umask set. It's when the Remote-WSL extension creates an "instance" that the problems start.

Does this issue occur when you try this locally and all extensions are disabled?: No (but then there can be no issue with an extension that's not running LOL)

**Comment by aeschli** [comment]
Remote - WSL does not make any changes to `umask`. The Remote-WSL extension starts the server without running any profile scripts so what you see is the when files are created by VSCode VSCode is what's the default of the distro. 
I've observed that in the latest WSL versions the default for  `umask` seems to be `022`, while it's `000` in older ones. Not sure if it's really WSL dependent or just distro dependent.

The integrated terminal however runs the [shell startup files](https://medium.com/@rajsek/zsh-bash-startup-files-loading-order-bashrc-zshrc-etc-e30045652f2e) (/etc/profile, .bash_profile ...) so you can configure `umask` there. But it will only affect the files created from that terminal.

The plan is to add a profile for the server as well so things like `umask` can be configured.

**Comment by rbarrimond** [comment]
Hi @aeschli ! You are correct that mirrors my experience and investigation. Thanks for explaining and I hope this makes it into the next release!

**Comment by aeschli** [comment]
With the Remote-WSL (>= 0.39.7) you can now define a script: `~/vscode-server-insiders/server-env-setup` where you can set stuff like umask.

Note: The script has to be valid (Bourne) shell script. Don't just source your bash startup scripts.
