### ISSUE TITLE
wrong  workspace folder while using docker-compose file for open in container command

### ISSUE THREAD

**Issue by slavugan** [microsoft/vscode-remote-release#1454]
Issue Type: <b>Bug</b>

I have folder /projects and proj1, proj2, proj3 inside.  when I set to use docker-compose file for "reopen in container" command I see proj1, proj2, proj3 folders in left bar "workcspace" but I expect to see files from proj2 as this folder was opened in VS Code befor running "reopen in container". If I set to use dockerfile it's ok.
my docker-compose:
version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db

Extension version: 0.74.0
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 5.0.0-29-generic
Remote OS version: Linux x64 5.0.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 1767)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.69GB (1.03GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Existing Docker Compose (Extend)|
|OS|Linux x64 5.0.0-29-generic|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 1767)|
|Memory (System)|7.69GB (1.03GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
You can configure the folder using the `"workspaceFolder"` property in the devcontainer.json.

Does that resolve the issue for you?
