### ISSUE TITLE
Remote Container: Attach Keeps Disconnecting

### ISSUE THREAD

**Issue by ih84ds** [microsoft/vscode-remote-release#1456]
Issue Type: <b>Bug</b>

I am connecting to a container running in Docker for Mac, if that makes a difference. I am not doing anything Mac-specific. In fact, I am going out of my way to avoid it.

Steps to reproduce:
* Connect to running container
* Run some commands in the container, like `yarn install` or `yarn run dev`

Result: Remote gets disconnected at some seemingly random point (usually within a minute or two). Remote then attempts to reconnect unsuccessfully, forever.

Expected: no random disconnects

Notes about the container I'm connecting Remote to:
* Based on ubuntu:18.04
* Has several bind-mounted volumes attached. All are Linux-native (no osxfs paths).

Extension version: 0.74.0
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|8.00GB (0.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
What's in the 'Dev Containers' terminal at the time the disconnect occurs? Are there any errors in the console (Help > Toggle Developer Tools)?

**Comment by ih84ds** [comment]
No errors in the Dev Containers terminal.

I think the issue I'm having is possibly a Docker for Mac issue. When this happens, the CPU usage is pegged to the max, and all Docker commands become unresponsive. It does seem to be triggered by something in the Dev Container, though, as this issue doesn't occur when I'm running the same containers without Remote. Perhaps it is related to memory usage in the Dev Container?

**Comment by chrmarti** [comment]
Could you run `htop` or something to monitor the memory usage?

**Comment by ih84ds** [comment]
Yes, I've done some more experimenting, and it does seem like allocating more memory to the Docker machine makes it happy. I think the VS Code server was the straw that broke the camel's back.
