### ISSUE TITLE
Line endings not set correctly when opening from WSL

### ISSUE THREAD

**Issue by yevster** [microsoft/vscode-remote-release#1458]
Issue Type: <b>Bug</b>

I ran `code path.sh` from WSL to edit a path configuration file. Even though the extension knew I was editing a file on a Linux filesystem, the line endings were set to CRLF.

I typed in the following script:
```bash
export JAVA_HOME=/opt/zulu11.33.15-ca-jdk11.0.4-linux_x64
export MVN_HOME=/mnt/c/soft/apache-maven-3.6.0
export PATH="${JAVA_HOME}/bin:${MVN_HOME}/bin:$PATH"
```

And no matter what I did, the paths would come out wrong. If the line endings are saved as CRLF, then running `echo "${JAVA_HOME}/bin"` after running this script will always print `/bin/zulu11.33.15-ca-jdk11.0.4-linux_x64`.

It took me close to an hour to figure out what the issue was. In short: when editing a new file on WSL, always set the line endings to the correct default: LF.

Extension version: 0.39.5
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.72GB free)|
|Process Argv|--file-uri=vscode-remote://wsl+Ubuntu-18.04/home/yevster/path.sh --remote=wsl+Ubuntu-18.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|15.93GB (8.72GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment]
pls see https://code.visualstudio.com/docs/remote/troubleshooting#_resolving-git-line-ending-issues-in-containers-resulting-in-many-modified-files

**Comment by yevster** [comment]
@egamma, the file being edited may not be in Git (as it wasn't in this case), and it is therefore not reasonable to expect such a file to always be present. In such a case, the right thing to do would be to infer the correct line endings based on the target environment.
