### ISSUE TITLE
Error Connecting to Raspberry Pi

### ISSUE THREAD

**Issue by coatsy** [microsoft/vscode-remote-release#1459]
- VSCode Version: 1.39.0-insider
- Local OS Version: Windows 10.0.18985
- Remote OS Version: Raspberian (Debian) 10.0
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install Remote-SSH (nightly) v 2019.9.31312
1. Connect to remote host
1. Fail with error  
`Install terminal quit with output: bash: line 54: ldconfig: command not found`
1. Roll back to v 2019.9.28260
1. Connect to remote host
1. Connect sucessfully

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by wil19558** [comment]
I have the exact same issue. 
I was using the Insiders version of SSH-Remote for the Raspbian support, but have just read that the Non-Insider version now supports it.

I have switched to the release SSH-Remote and it works like a charm.

**Comment by tenkaisynapse** [comment]
Just started getting this same exact issue today, one two different computers, one is running windows and the other is OS X. I cannot switch to the release version because I need to use it with a raspberry pi. This has totally broken my dev environment

**Comment by tenkaisynapse** [comment]
How can someone roll back to 2019.9.28260?

**Comment by Pack3tL0ss** [comment]
Same issue here, on numerous (previously ) known-working RPIs.  exact same error as op.

**Comment by tenkaisynapse** [comment]
> How can someone roll back to 2019.9.28260?

I figured it out, if you right click on the extension in Vscode, you can select a previous version to use

**Comment by Pack3tL0ss** [comment]
Good Tip @tenkaisynapse I ended up using the stable version as @wil19558 suggested.  Either way there is an issue with the current nightly build, as least as it relates to the RPI.

btw in case it's useful (to the devs):  the user configured to login with vscode has access to ldconfig (it's location is in PATH and command is executable) when logging in with that user via SSH (outside vsc).

**Comment by tenkaisynapse** [comment]
> btw in case it's useful (to the devs): the user configured to login with vscode has access to ldconfig (it's location is in PATH and command is executable) when logging in with that user via SSH (outside vsc).

Agreed, when I log in via SSH, i have access to ldconfig as well.

**Comment by ojullien** [comment]
Same issue while trying to connect to a Debian.Buster. The script is looking for ldconfig but ldconfig can only be executed by root, not by a normal user

**Comment by joaomoreno** [comment]
I just hit this last night on my RPi 4 as well, I assumed it was a 4 issue, but it seems not.

**Comment by roblourens** [comment]
Sorry! So the raspberry pi has `ldconfig` available, you just need to be root? Is that the case for everyone or is the PATH wrong in the install script? I wouldn't expect to see `command not found` if you just need privileges.

**Comment by roblourens** [comment]
Pushed an improvement for this, not 100% sure whether it will fix it or not, please somebody let me know.

**Comment by ojullien** [comment]
The 2019.9.34260 version fixes my issue. Thx.

**Comment by joaomoreno** [comment]
Yup all good in today's Insiders @roblourens! Thanks!

**Comment by Pack3tL0ss** [comment]
Connected without issue here as well, Thanks! @roblourens
