### ISSUE TITLE
Status icon bg color mismatch

### ISSUE THREAD

**Issue by niccolomineo** [microsoft/vscode-remote-release#1461]
**Product and Version** [VS/VSCode]: 1.38.1
**OS Version** [macOS/Windows]: MacOS Mojave 10.14.6
**Target Platform or Language** [e.g. Node.js]: Any

The status icon features a different background color when VSCode starts up:
![Schermata 2019-09-19 alle 13 40 19](https://user-images.githubusercontent.com/5409469/65241173-3863b280-dae3-11e9-9f70-99c0031d154a.png)

**Comment by niccolomineo** [comment]
Hi, I posted a screenshot in the OP. You can see that by default your icon has a blue background color, which doesn't match the rest of the VSCode's statusbar color (purple). Your icon's background color should match VSCode's statusbar color depending on the statusbar state (i.e. when no workspace is open, it shows up as purple; when in debug mode, it shows up as yellow/orange).

**Comment by roblourens** [comment]
This button is actually a different color on purpose, to make it stand out. You can customize the color if you would prefer it to match.
