### ISSUE TITLE
BSoD while installing core-js@3

### ISSUE THREAD

**Issue by AbdusamadTurdiev** [microsoft/vscode-remote-release#1463]
- VSCode Version: 1.38.1 (user setup)
- Local OS Version: Windows 10 Pro 18362.356
- Remote OS Version: Ubuntu 18.04.3 LTS
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Restart computer
2. Clear cache/node_modules

Does this issue occur when you try this locally?: No

I'm running this in project's folder and get BSoD with this error

```npm install --save core-js@3```

![image](https://user-images.githubusercontent.com/33511684/65431522-1051b780-de33-11e9-9902-8894dd75b067.png)

**Comment by aeschli** [comment]
Can you complete the steps? How is VSCode involved here? Do you run `npm install --save core-js@3` in a WSL shell? Or in an integrated terminal in a WSL remote window? Do you get a blue screen in both cases?

My guess is that this is not related to the Remote - WSL extension but to WSL. In that case please file directly against https://github.com/microsoft/WSL/issues

**Comment by AbdusamadTurdiev** [comment]
> Can you complete the steps? How is VSCode involved here? Do you run `npm install --save core-js@3` in a WSL shell? Or in an integrated terminal in a WSL remote window? Do you get a blue screen in both cases?
> 
> My guess is that this is not related to the Remote - WSL extension but to WSL. In that case please file directly against https://github.com/microsoft/WSL/issues

I ran that in integrated terminal in a WSL remote window. I didn't test first case, but I got blue screen two times with first case

**Comment by aeschli** [comment]
Can you test if it also crashes in a WSL shell?

**Comment by AbdusamadTurdiev** [comment]
> Can you test if it also crashes in a WSL shell?

I've tested and it was successful in `/mnt/c/Users/Abdusamad` folder and in project's folder located in wsl `~/projects/pet/prisma-app` but in the last case it was very slow and pause was in executing `node scripts/postinstall`

**Comment by aeschli** [comment]
So no blue screen when you do it outside of VSCode.
The difference between the WSL shell and from inside VSCode could be the file watcher.
You can verify that theory by setting `"remote.WSL.fileWatcher.polling": true` in VSCode. 

Can you please file the issue against https://github.com/microsoft/WSL/issues? I can also do it, but then I get questions asks, but I'm not able to reproduce (I tried with the same version of Windows)

**Comment by AbdusamadTurdiev** [comment]
@aeschli not outside of VSCode but outside of WSL1 I guess. And I've already created an issue there https://github.com/microsoft/WSL/issues/4537

**Comment by aeschli** [comment]
Thanks a lot!
