### ISSUE TITLE
SSH extention Cannot reconnect. Please reload window.

### ISSUE THREAD

**Issue by koenkv** [microsoft/vscode-remote-release#1464]
- VSCode Version: 1.38.1
- OS Version: Windows 10

I try to connect to linux machine using the ssh extention
using a local tunnel and sshkey
the tunnel is working if I use a putty with the same key and tunnel the connection works

Steps to Reproduce:

1. my ssh config file:
Host config-2
    HostName 127.0.0.1
    Port 2223
    User XXXXXXX
    IdentityFile C:\Users\XXXXXXXXX\Documents\keys\XXXXXXX
2. connect to host in new window
3. get the error "Cannot reconnect. Please reload window."

Does this issue occur when all extensions are disabled?: No

**Comment by koenkv** [comment]
I dont get any output on my screen 
is there a way to get more debug information?

![image](https://user-images.githubusercontent.com/17100518/65489637-d5d83100-deab-11e9-873e-61269de1bd98.png)

**Comment by rinzlerFix** [comment]
I had the same issue. I had 2 visual instances running at the same time. If you have more than 1 window with visual code running try to close before the ssh connection.

**Comment by jiayiliu** [comment]
I fixed the problem by removing the `.vscode-server` folder on the server and connecting to the server again.

**Comment by koenkv** [comment]
That solved the problem Thx
