### ISSUE TITLE
SSH and then sudo into another user.

### ISSUE THREAD

**Issue by altesien** [microsoft/vscode-remote-release#1466]
is there a way that you can have the editor be bound not to the user that logged in, but the user that was sudo'd to.

ie.

Host somehost
    HostName somehost
    User urself
    IdentityFile C:\Users\user\.ssh\file
    RemoteCommand sudo su - newUser
    RequestTTY yes

**Comment by roblourens** [comment]
Not currently. Covered by https://github.com/microsoft/vscode-remote-release/issues/141 I think
