### ISSUE TITLE
Adopt 'remoteAuthority' in wsl and containers extensions

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1468]
I don't want to do it everywhere until it's survived a few days and I'm sure we're keeping it.

https://github.com/microsoft/vscode-remote-release/issues/1426

**Comment by roblourens** [comment]
FYI @alexr00 @aeschli

**Comment by roblourens** [comment]
Would be great if you can publish the wsl and containers extensions so we can selfhost with it!

**Comment by aeschli** [comment]
@roblourens  In the VSCode API we use the term `remoteName` instead of `remoteAuthority`. Can we fix that?

**Comment by roblourens** [comment]
Oh, yeah good point

**Comment by roblourens** [comment]
Fixed, also realized that containers has 2 remote authorities, so now remoteName is `string | string[]`
