### ISSUE TITLE
"Attached Container" text is too long with private registries

### ISSUE THREAD

**Issue by zifik** [microsoft/vscode-remote-release#1470]
When using a private registry with Docker it is required to have the registry URL as part of the image name. Combine that with port and namespaces and you have a very long name. In my case mine it is something like: gitlab.myserver.com:8443/group/team/project:1.2.3-alpha

The remote dev extension displays the full image name in the green block in the status bar and it very quickly crowds out other extensions that also require status bar real-estate: 
**>< Attached Container gitlab.myserver.com:8443/group/team/project:1.2.3-alpha (/serene_khorana) @ localhost23750**

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/2372529/65514690-cf49b980-deab-11e9-9854-3d21de163a40.png">

Just remove the image name from that green box and all will be well. The image name showing up in the tooltip is fine.

**Comment by chrmarti** [comment]
@aeschli Is this something the platform should handle better by automatically shortening with an ellipsis and a tooltip showing more?

**Comment by aeschli** [comment]
The text is coming from the Container extension:
https://github.com/microsoft/vscode-remote-containers/blob/b1d8d3f03c79af4e1c7b3f7ee3a6d5d03af30c57/src/attachContainerResolver.ts#L83
Better keep it compact. IMO the it's better if the extension does the shortening as it knows better what information is most relevant.

Adding a tooltip text is a good idea.

**Comment by alexr00** [comment]
Verified that the text is shorter, but the tooltip doesn't show the full text.
