### ISSUE TITLE
Better remote-containers portability (windows/mac/linux)

### ISSUE THREAD

**Issue by Kamori** [microsoft/vscode-remote-release#1471]
First, I want to say, this feature request is more a report on my experience with Remote Containers. I'm hoping it will spark a discussion how to make an environment more portable across OSes.

So I went through the process of setting up Remote Containers and mostly got it working well. However, I've hit a pretty epic hurdle that makes it not work for my personal workflow.

I jump from machine to machine a lot. Linux for Work, Mac for my on the go dev, and then Windows when i wanna sit at a desk at home.  My main goal for trying to use the Remote Container method was to be able to setup an environment that had all my required VSCode Extensions and language libraries (python-black, pytest, linter etc) and no bloat. As well as copy my settings.

For the most part I achieved that.

However, I had a few problems.
* Build times for project startup are pretty bad on my linux machine (just due to the load on the machine itself) when all I want to do is read code.
* Docker and how it manages file permissions is pretty sucky to deal with from one device to the next. In normal docker this isn't so bad, but having a bind mount is what makes it suck. I think I can get around this, but it only complicates the project more by introducing docker-compose.yml just for development, when there may be one present for the application itself.
===
Having said this I'm going to go back to my traditional method of ever project has a bit of startup cost.
* Make my project, install my dependencies (python-virtualenv + black,test,lint etc) that part I can pretty easily script around just to "init" the project and not suffer repeatably long startup times.
* Enable/disable certain extensions per workspace
* And then I'll just have to make sure my languages are installed on the box. For example having Go setup on my machines individually rather than having a container that is just good to go.... I may still make use of Docker for my dev experiences, but I won't make explicit use of vscode's devcontainers

**Comment by chrmarti** [comment]
Thanks for writing this down.

- Build times: Agree, filed #1498 to track.
- Permissions: Particularly on Linux, tracked with #1155. (Also: The latest release (needs VS Code Insiders) supports building a container from a GitHub repository which it clones into a Docker volume instead of using a bind mount.)

/cc @Chuxel

**Comment by Kamori** [comment]
I noticed the linked issues have been resolved and the spin up time has been improved. Not sure when I'll get around to it, but gonna try to re-adopt this workflow.

**Comment by Chuxel** [comment]
@Kamori There's also a number of pre-built images for config added via VS Code (or coming from the microsoft/vscode-dev-containers repo) release that should further speed things up. Let us know if there's a particular one you're finding slow as a change may already be in-flight. :smile:

**Comment by chrmarti** [comment]
Closing this issue as the linked issues should be dealing with it. Thanks.
