### ISSUE TITLE
How to login as user instead of as root when attaching remote container

### ISSUE THREAD

**Issue by ztlevi** [microsoft/vscode-remote-release#1477]
After I setup remote container and try to connect it via `Remote-Container: attach to running container`, it's always under root privilege. It cause a lot of problem when I came back to local machine. 

How to attach it not as root?

![image](https://user-images.githubusercontent.com/16655096/65567397-faafc100-df0a-11e9-854e-2d6900a40a6c.png)

**Comment by chrmarti** [comment]
Please see: https://code.visualstudio.com/docs/remote/containers-advanced#_adding-a-nonroot-user-to-your-dev-container

Does that help?

**Comment by ztlevi** [comment]
I believe devcontainer.json is something for local, right? Because it needs `dockerFile` path to be a valid devcontainer.json.

And when I do `Remote-Container: attach to running container` in vscode, I am trying to attach a remote container published by ssh forward port (`ssh -l`).

And it basically doesn't have any configuration options there for users to pick.

**Comment by chrmarti** [comment]
Got it. You can start the container with a different user (`docker run -u user ...`) and that user will then also be used by VS Code.

**Comment by ztlevi** [comment]
Great, thanks!
