### ISSUE TITLE
Connot establish connect with host  The terminal shell path "cmd.exe" does not exist

### ISSUE THREAD

**Issue by goodnighteveryone** [microsoft/vscode-remote-release#1479]
Issue Type: <b>Bug</b>

1：Ctrl+p，(remote-ssh: Connect current window to host)
2：this is the full log
![无标题](https://user-images.githubusercontent.com/49894559/65531250-0f508100-df2c-11e9-9c6b-e3316bc8a120.jpg)
![无标题2](https://user-images.githubusercontent.com/49894559/65531260-137c9e80-df2c-11e9-92b7-e39135c2bd8e.jpg)
![无标题3](https://user-images.githubusercontent.com/49894559/65531267-16778f00-df2c-11e9-8a7e-51ec5d1b4345.jpg)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
Local OS version: Windows_NT x64 10.0.17134
Remote OS version:Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-29-generic x86_64)
Remote Extension/Connection Types:SSH
I am a new beginner,I am sorry  that I cannot provide more detailed information.But you can tell me what I should do for you. 
Fetching remote diagnostics for 'SSH' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed.
</details>Extensions: none

**Comment by roblourens** [comment]
Thanks for the logs, this is a strange error. If you open a normal terminal and type `cmd.exe`, does it work or do you get a similar error?

**Comment by goodnighteveryone** [comment]
I am soory for replying now.
In Powershell,it says:"The command cmd.exe could not be found, but it does exist in the current location"
In cmd,it says:"'cmd.exe' is not an internal or external command, nor it is a executable program"

**Comment by roblourens** [comment]
Ok, there is definitely some problem with your PATH. @Tyriar how does the terminal find cmd.exe?

**Comment by goodnighteveryone** [comment]
thank you

**Comment by roblourens** [comment]
If system32 is not on your path, I don't see how windows even works. Can you tell me what `echo %PATH%` shows (Or in powershell, `echo $env:PATH`)

**Comment by goodnighteveryone** [comment]
my path in system variables is :"C:\Program Files\AdoptOpenJDK\jdk-8.0.222.10-hotspot\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;D:\Git\Git\cmd;D:\chocolatey\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\OpenSSH-Win64;C:\OpenSSH\bin;D:\visual studio code\Microsoft VS Code\bin;D:\Git\Git\usr\bin;C:\Users\86183\AppData\Local\Microsoft\WindowsApps;D:\Git\Git\mingw64\libexec\git-core;D:\Git\Git\bin;D:\Git\Git\cmd\git.exe;D:\visual studio code\Microsoft VS Code\bin;D:\Git\Git\usr\bin;"
I modified my path several months ago.
I use the app called everything find two cmd.exe ,one is in C:\Windows\System32,the other is in C:\Windows\SysWOW64

**Comment by goodnighteveryone** [comment]
I try to add the C:\Windows\System32\cmd.exe to path then restart my computer but no effect

**Comment by Tuxiaojing** [comment]
I get the same problem. Need help.

**Comment by Tuxiaojing** [comment]
![企业微信截图_15698085909072](https://user-images.githubusercontent.com/14515064/65844422-caf72380-e325-11e9-8802-7a0d45b65650.png)
![企业微信截图_15698086475163](https://user-images.githubusercontent.com/14515064/65844424-ccc0e700-e325-11e9-9b0f-393f55280d72.png)

**Comment by Tuxiaojing** [comment]
> I try to add the C:\Windows\System32\cmd.exe to path then restart my computer but no effect

QQ:526008411 can we contact？

**Comment by roblourens** [comment]
Both of you don't have `C:\Windows\System32` on your path, I don't understand why that is. But I will change this to not rely on the PATH.
