### ISSUE TITLE
targets ssh forgets opened remote directories

### ISSUE THREAD

**Issue by Spookhub** [microsoft/vscode-remote-release#1480]
Issue Type: <b>Bug</b>

connecting to a aws ec2 (.pem key) via remote explorer, then opening the filesystem directories,it maps the remote files. swapping to other plugins and returning it forgets the mapped files.
you have to reopen a new VSC to reload the system.

also targets containers doesn't work. 

Extension version: 0.46.1
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

**Comment by roblourens** [comment]
Please explain more about exactly what you do and what you are seeing.

> also targets containers doesn't work.

Please open a new issue for this with more details.
