### ISSUE TITLE
display <ffffffff><ffffffff><ffffffff> while typing chinese characters in zsh terminal.

### ISSUE THREAD

**Issue by yangkghjh** [microsoft/vscode-remote-release#1481]
- VSCode Version: 1.38.1
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 18.04.1 LTS 
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. open terminal
2. type chinese character, like `我`
3. shows `<ffffffff><ffffffff><ffffffff>`
4. if paste `我` in terminal, it will shows like `???`
5. if type or paste in bash, it wan't display anything

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by Tyriar** [comment]
Usually these are related to you `$LANG` variables. The upcoming version of VS Code has better detection and filling in of this to the valid UTF-8 value which you can try out in the [Insiders build](https://code.visualstudio.com/insiders).

/duplicate https://github.com/microsoft/vscode/issues/80072
