### ISSUE TITLE
File not showing up with same name but different case

### ISSUE THREAD

**Issue by zzh1996** [microsoft/vscode-remote-release#1482]
- VSCode Version: 1.38.1
- Local OS Version: Windows 10 1903
- Remote OS Version: Ubuntu 19.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open a remote folder.
2. On the remote machine, run `touch a` and `touch A` in the project folder.
3. Only the first one will show up in vscode file explorer. Same for one file and one folder, and two folders.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by foreignmeloman** [comment]
I can confirm this. Same version, same issue.

When I ls the files in terminal you can see 2 of them: **makefile** and **Makefile**, but in the tree only the **makefile** is visible.

![ssh_tree_bug](https://user-images.githubusercontent.com/11769352/65884992-dfc9ca80-e3aa-11e9-9055-0f34ca555304.png)

**Comment by isidorn** [comment]
I believe we always had this issue. Let me know if this was working in previous versions, and if yes please specify which.

Same name different case has issues across the workbench, not sure if this is explorer specific @bpasero fyi

**Comment by bpasero** [comment]
🤷‍♂️

**Comment by zzh1996** [comment]
I thought it is a very special case to have files with the same name but different case, but in fact it is not so rare.

If you have a folder called `Program` and a file called `program` inside it, and you want to move the file outside the folder in vscode, you will end up finding the file disappeared

**Comment by vicenteherrera** [comment]
I have same issue with folder name, where it is important.
Executing a composer install on a Laravel project, some libraries where originally registered with lowercase vendor name, and some other with uppercase.
Right now all the libraries in the uppercase vendor folder are invisible for us. It is not just one file missing, is a whole set of libraries.

Workaround is use the "add folder to workspace" menu option, and there you can see and correctly select the uppercase folder name to be added in the root of the workspace. At least that way we can see them.

**Comment by awarmfastbear** [comment]
Windows 10 now supports case sensitivity [1], I believe Visual Studio Code and Remote SSH should default to a case sensitive workspace whenever possible. I just got bit by this in a deployment. To make matters worse, I can't rename 'gamma' to 'Gamma' if the 'Gamma' folder already exists but is not shown inside of Visual Studio Code:
![2019-11-27 11_12_59-Hyper](https://user-images.githubusercontent.com/25071166/69753988-a80ca400-1109-11ea-95b0-238be3de79d8.png)

[1] https://devblogs.microsoft.com/commandline/per-directory-case-sensitivity-and-wsl/

**Comment by isidorn** [comment]
Should be fixed via https://github.com/microsoft/vscode/issues/48258
Please try out vscode insiders from tomorrow

**Comment by isidorn** [comment]
Does this work now as expected with vscode insiders?
Thanks!
