### ISSUE TITLE
VSCode git doesn't work with SSH key with passphrase when attached to container

### ISSUE THREAD

**Issue by alexsirbu** [microsoft/vscode-remote-release#1483]
VSCode Version: 1.38.1
Local OS Version: macOS Mojave 10.14.6
Remote OS Version: Ubuntu 14.04.6 LTS
Remote Extension/Connection Type: Docker/Attach to running container

When attaching to a container that has a ssh key with passphrase configured in ~/.ssh/, using git from VSCode fails when trying to pull/push from a configured repository where the key has access (`Permission denied (publickey)`). 

From command line, after starting git-agent and adding the key, git push/pull work.

Linked to https://github.com/microsoft/vscode/issues/13680. Is there any way to apply the workaround mentioned here (to start VSCode from a terminal that has the git-agent set up, with the ssh key added to it), that applies to remote containers?

**Comment by kevinfaguiar** [comment]
Any news on this?

**Comment by chrmarti** [comment]
No, a workaround has been crafted, but I haven't tried it yet: https://github.com/microsoft/vscode-remote-release/issues/106#issuecomment-524911632

**Comment by patrickquijano** [comment]
Do we have any updates on this?

**Comment by chrmarti** [comment]
We now forward the local ssh-agent into the container. So if you add your key to the local ssh-agent, it should work. Please post your log (`F1` > `Remote-Containers: Show Log`) if it doesn't.
