### ISSUE TITLE
Debugger doesn't stop at Breakpoints

### ISSUE THREAD

**Issue by paamonim** [microsoft/vscode-remote-release#1484]
Issue Type: <b>Bug</b>

I have rails 3.2.8, ruby 1.9.3, working with WSL.
Gems ruby-debug-ide and ruby-debug-base19x are installed.
Everything works fine, but the debugger doesn't stop. It ignores the breakpoints.

Extension version: 0.39.5
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|15.88GB (8.59GB free)|

|Remote|WSL: Ubuntu-16.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2201)|
|Memory (System)|15.88GB (8.59GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment]
Please file this against the Ruby extension that provides the debugger.
