### ISSUE TITLE
Remote should display images selected on the explorer

### ISSUE THREAD

**Issue by felipeportella** [microsoft/vscode-remote-release#1489]
Will be nice if remote extension could display remote images (like a PNG) when they are selected on the remote explorer, the same way VSCode display them when we select anyone local.

**Comment by chrmarti** [comment]
You can select an image in the Explorer just like when running locally. Could you attach a screenshot of when you clicked on an image? Which OS and VS Code version are you running?

**Comment by felipeportella** [comment]
Sorry, in that case could be a bug. I attached some screenshots and below my VSCode details:

Version: 1.39.0-insider
Commit: b0d714d2de2886060e0904bf0cc774e0d70667cd
Date: 2019-09-26T09:06:52.273Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-64-generic

I'm using Remote SSH extension version 0.46.1 with the respective Remote SSH Explorer.

![Screenshot from 2019-09-27 13-05-02](https://user-images.githubusercontent.com/946578/65768998-d0404c80-e132-11e9-9c0c-c4216f66c648.png)
![Screenshot from 2019-09-27 13-05-05](https://user-images.githubusercontent.com/946578/65768999-d0d8e300-e132-11e9-9e7e-d76408ee7102.png)

**Comment by mjbvz** [comment]
Can't repo going from MacOS client to ssh workspace

![Screen Shot 2019-09-27 at 11 24 32 AM](https://user-images.githubusercontent.com/12821956/65792841-71220e00-e119-11e9-841f-8c198ba7bc8b.png)


Will test on linux too...

**Comment by mjbvz** [comment]
Also can't repo with linux client going to same vm. @felipeportella  Can you please test this with the nightly ssh extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly

**Comment by felipeportella** [comment]
With the new nightly versions of VSCode and Remote Extension worked as expected:  

Version: 1.39.0-insider
Commit: e0762af258c0b20320ed03f3871a41967acc4421
Date: 2019-09-27T05:26:55.061Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-64-generic

Name: Remote - SSH: Editing Configuration Files (Nightly)
Id: ms-vscode-remote.remote-ssh-edit-nightly
Description: Edit SSH configuration files
Version: 2019.9.38738
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-edit-nightly

The new Remote removed the Explorer extension.

![Screenshot from 2019-09-30 11-07-36](https://user-images.githubusercontent.com/946578/65864679-9e1d2d80-e372-11e9-964b-82f1109d5e30.png)

We can close as no change needed ... 
Thanks!
