### ISSUE TITLE
Forward fails when using ProxyCommand

### ISSUE THREAD

**Issue by lars18th** [microsoft/vscode-remote-release#149]
- VSCode Version: 1.34.0-insider
- Local OS Version: Windows 10 1809
- Remote OS Version: Debian 9.9 Stretch
- Remote Extension/Connection Type: SSH with ProxyCommand

Steps to Reproduce:

1. Configure your `.shh/config` with `ProxyCommand` for your session.
2. Start the Remote-SSH session, but after when stablishing the connection over the tunnel you see "Openning Remote..." forever.

The main problem is because when creating the _TUNNELED_ connection, the SSH client still try to connect using the ProxyCommand. And obviously this will fail as you're connecting to "localhost".

So, please fix this problem or provide a workaround.
Regards.

**Comment by kieferrm** [comment]
@lars18th can you show what your config file looks like. I'm running the following (although from macOS) without problems:

```
Host jump-box
	HostName <jump box address>
	IdentityFile ~/.ssh/jump-box
	User <user>

Host target-box
	HostName <target box address>
	IdentityFile ~/.ssh/target-machine
	User <user>
	ProxyJump jump-box

Host target-box2
	HostName <same address as tagret-box>
	IdentityFile ~/.ssh/target-machine
	User <user>
	ProxyCommand ssh -q -W %h:%p jump-box
```

**Comment by lars18th** [comment]
Hi @kieferrm ,

Thank you for your comment. However I use ProxyCommand for SOCKS PROXY, and not for the JUMP functionality. Please, not merge JUMP with PROXY (socks or HTTP); they're different things.

Here is my `.ssh/config` in Windows 10:
```
Host my-server
    HostName 192.168.2.126
    User userme
    ProxyCommand c:\VSCODE\connect.exe -S 192.168.1.31:1080 %h %p
```

And the problem is that the Remote-SSH uses the ProxyCommand too with the _TUNNELED_ connection (aka `localhost:20843:localhost:48214`), and this is an error! To connect over the tunnel the proxy isn't needed and it fails (as it can't connect to `localhost:20843` because this address has sense in the local machine and not in the proxy device).

I hope it will be fixed soon.

**Comment by lars18th** [comment]
Hi,

I report another annoying problem when using ProxyCommand with a WINDOWS client:

- The SSH connection that stablishes the Forwarding tunnel, it opens a window for the proxy process, instead of doing it in the background. I feel the problem is because the spawn call opens the window. It will be desirable to not open this command window.

Regards.

**Comment by bamurtaugh** [comment]
Hey @lars18th, I see #230 was fixed, and I haven't seen any new traction in this issue recently. Are you still experiencing any problems? Otherwise, I'll go ahead and close this issue.

**Comment by lars18th** [comment]
> Hey @lars18th, I see #230 was fixed, and I haven't seen any new traction in this issue recently. Are you still experiencing any problems? Otherwise, I'll go ahead and close this issue.

Hi @bamurtaugh ,

I'll do some more deep tests.
Regards.
