### ISSUE TITLE
"No such container" error after removing container

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1491]
- `docker run -it --rm debian`
- Open Remote Explorer.
- Exit from container.
- "No such container" error message is shown (as notification or in console).

**Comment by chrmarti** [comment]
There is still an error in the console and as a notification with the above steps:

![image](https://user-images.githubusercontent.com/9205389/66142684-2ff09900-e606-11e9-9965-8be73e61f45c.png)

**Comment by alexr00** [comment]
I cannot repro, but I added an additional guard around where this was happening before.
