### ISSUE TITLE
Remote-Containers:Error Port not found

### ISSUE THREAD

**Issue by Monsterlin2018** [microsoft/vscode-remote-release#1497]
- VSCode Version:1.38.1
- Local OS Version: window 1809
- Remote OS Version: docker 18.06.0-ce centos7
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1、Starting from “Add Development Container Configuration Files”
2、F1 to run “Remote-Containers: Reopen Folder in Container”

---------------------------------------------------
Setting up container for folder or workspace: d:\WorkSpace\formicary\container-config\test05
Run: docker run -a STDOUT -a STDERR --mount src=/vscode/testvrtjm,dst=/workspace,type=bind -l vsch.quality=stable -l vsch.local.folder=d:\WorkSpace\formicary\container-config\test05 -l vsch.remote.devPort=0 --entrypoint /bin/sh test03:0.1 -c echo Container started ;  while sleep 1; do :; done
...
...

Run: docker exec -w /root/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0 -e SHELL=/bin/bash -e VSCODE_AGENT_FOLDER=/root/.vscode-server 1cb74f8fbc1dfdd122cafc3f19c93d82329834a38aa339dc34d0e9f65e4c0105 /root/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/server.sh --disable-user-env-probe --port 0
Error: Port not found
        at Object.t.launchVSCHeadless (c:\Users\MonsterLin\.vscode\extensions\ms-vscode-remote.remote-containers-0.74.0\dist\extension.js:1:96188)

**Comment by chrmarti** [comment]
Does this also happen with VS Code Insiders? Download: https://code.visualstudio.com/insiders/

**Comment by Monsterlin2018** [comment]
Thank you so much！
With VS Code Insiders（vesion1.39.0），this still hanppens。
-----------------
I refer to [this page](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host) for modification，No other redundant changes have been made.This is my configuration：
————————
seetings :
{
    "docker.host": "10.16.x.x:5000" //In a LAN
}

File: devcontainer.json
{
	"image": "test03:0.1",//dockerfile-->FROM openjdk:8-jdk 
	"workspaceFolder": "/vscode/testvrtjm",
	"workspaceMount": "src=/vscode/testvrtjm,dst=/workspace,type=bind",
	"name": "Java 8"
}
---------------------------

**Comment by chrmarti** [comment]
Could you attach the entire log from the Dev Container terminal?

**Comment by Monsterlin2018** [comment]
dev container terminal：
————
Setting up container for folder or workspace: d:\WorkSpace\formicary\container-config\test03
Run: docker run -a STDOUT -a STDERR --mount src=/vscode/testvrtjm,dst=/workspace,type=bind -l vsch.quality=stable -l vsch.local.folder=d:\WorkSpace\formicary\container-config\test03 -l vsch.remote.devPort=0 --entrypoint /bin/sh test03:0.1 -c echo Container started ;  while sleep 1; do :; done
Run: docker exec 71a0476452746ce4c670bd949ce68cfae5fd84d2c3df611a5129937914ca5fc1 /bin/sh -c (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
Run: docker cp 71a0476452746ce4c670bd949ce68cfae5fd84d2c3df611a5129937914ca5fc1:/etc/passwd -
Run: docker exec 71a0476452746ce4c670bd949ce68cfae5fd84d2c3df611a5129937914ca5fc1 test -d /root/.vscode-server
Run: docker exec 71a0476452746ce4c670bd949ce68cfae5fd84d2c3df611a5129937914ca5fc1 /bin/sh -c set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
Run: docker exec 71a0476452746ce4c670bd949ce68cfae5fd84d2c3df611a5129937914ca5fc1 /bin/sh -c set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.copyGitConfigMarker' ; } 2> /dev/null
Run: docker exec 71a0476452746ce4c670bd949ce68cfae5fd84d2c3df611a5129937914ca5fc1 test -e /root/.gitconfig
Run: docker exec 71a0476452746ce4c670bd949ce68cfae5fd84d2c3df611a5129937914ca5fc1 test -d /root/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Run: docker exec 71a0476452746ce4c670bd949ce68cfae5fd84d2c3df611a5129937914ca5fc1 test -d /root/.vscode-server/extensions
Run: docker exec -w /root/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0 -e VSCODE_AGENT_FOLDER=/root/.vscode-server 71a0476452746ce4c670bd949ce68cfae5fd84d2c3df611a5129937914ca5fc1 /root/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/server.sh --install-extension MS-CEINTL.vscode-language-pack-zh-hans
Run: docker exec 71a0476452746ce4c670bd949ce68cfae5fd84d2c3df611a5129937914ca5fc1 /bin/sh -c set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.postCreateCommandMarker' ; } 2> /dev/null
Run: docker exec 71a0476452746ce4c670bd949ce68cfae5fd84d2c3df611a5129937914ca5fc1 test -f /root/.vscode-server/.postCreateCommandMarker
Run: docker exec -w / -u 0 71a0476452746ce4c670bd949ce68cfae5fd84d2c3df611a5129937914ca5fc1 /bin/sh -c command -v git >/dev/null 2>&1 && git config --system credential.helper '!f() { command -v code >/dev/null 2>&1 && code --gitCredential $*; }; f' || true
Run: docker exec -w /root/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0 -e SHELL=/bin/bash -e VSCODE_AGENT_FOLDER=/root/.vscode-server 71a0476452746ce4c670bd949ce68cfae5fd84d2c3df611a5129937914ca5fc1 /root/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/server.sh --disable-user-env-probe --port 0
Error: Port not found
        at Object.t.launchVSCHeadless (c:\Users\MonsterLin\.vscode\extensions\ms-vscode-remote.remote-containers-0.74.0\dist\extension.js:1:96188)
————

**Comment by chrmarti** [comment]
Some output seems to be missing, could attach the Dockerfile?

**Comment by Monsterlin2018** [comment]
Attach Dockerfile，dev container terminal is：
```
Setting up container for folder or workspace: d:\WorkSpace\formicary\container-config\test08
Run: docker build -f d:\WorkSpace\formicary\container-config\test08\.devcontainer\Dockerfile -t vsc-test08-bc33683d8202b83d81113f19a919d510 d:\WorkSpace\formicary\container-config\test08\.devcontainer
Sending build context to Docker daemon  8.192kB
Step 1/9 : FROM openjdk:8-jdk
 ---> e8d00769c8a8
Step 2/9 : ARG USERNAME=vscode
 ---> Using cache
 ---> 47da94a57f0a
Step 3/9 : ARG USER_UID=1000
 ---> Using cache
 ---> 5aaea7bc9d98
Step 4/9 : ARG USER_GID=$USER_UID
 ---> Using cache
 ---> 8fca761ec3c8
Step 5/9 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> a82abd07c124
Step 6/9 : RUN apt-get update     && apt-get -y install --no-install-recommends apt-utils dialog 2>&1     && groupadd --gid $USER_GID $USERNAME     && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME     && apt-get install -y sudo     && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME    && chmod 0440 /etc/sudoers.d/$USERNAME     && apt-get -y install git iproute2 procps curl lsb-release
 ---> Using cache
 ---> 24aeea3b8e1c
Step 7/9 : RUN apt-get autoremove -y     && apt-get clean -y     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 541626c5d678
Step 8/9 : ENV DEBIAN_FRONTEND=
 ---> Using cache
 ---> dba17093854e
Step 9/9 : RUN if [ ! -d "/docker-java-home" ]; then ln -s "${JAVA_HOME}" /docker-java-home; fi
 ---> Using cache
 ---> 76b91e423f37
Successfully built 76b91e423f37
Successfully tagged vsc-test08-bc33683d8202b83d81113f19a919d510:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
Run: docker run -a STDOUT -a STDERR --mount src=/vscode/test08,dst=/workspace,type=bind -l vsch.quality=stable -l vsch.local.folder=d:\WorkSpace\formicary\container-config\test08 -l vsch.remote.devPort=0 --entrypoint /bin/sh vsc-test08-bc33683d8202b83d81113f19a919d510 -c echo Container started ;  while sleep 1; do :; done
Run: docker exec 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01 /bin/sh -c (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
Run: docker cp 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01:/etc/passwd -
Run: docker exec 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01 test -d /root/.vscode-server
Run: docker exec 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01 test -d /root/.vscode-remote
Run: docker exec 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01 /bin/sh -c cp -r '/root/.vscode-remote' '/root/.vscode-server'
Run: docker exec 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01 /bin/sh -c set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
Run: docker exec -w /root 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01 /bin/sh -c mkdir -p '/root/.vscode-server/data/Machine' && cat >'/root/.vscode-server/data/Machine/settings.json' <<json
                                                   {
                                                        "terminal.integrated.shell.linux": "/bin/bash",
                        "java.home": "/docker-java-home"
                                                        }
                                                         json
Run: docker exec 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01 /bin/sh -c set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.copyGitConfigMarker' ; } 2> /dev/null
Run: docker exec 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01 test -e /root/.gitconfig
Run: docker cp C:\Users\MonsterLin\.gitconfig 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01:/root/.gitconfig --follow-link
Run: docker exec -w /root -u root 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01 chown root:0 /root/.gitconfig
Run: docker exec 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01 test -d /root/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Run: docker exec 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01 test -d /root/.vscode-server/extensions
Run: docker exec -w /root/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0 -e VSCODE_AGENT_FOLDER=/root/.vscode-server 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01 /root/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/server.sh --install-extension MS-CEINTL.vscode-language-pack-zh-hans
Run: docker exec 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01 /bin/sh -c set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.postCreateCommandMarker' ; } 2> /dev/null
Run: docker exec 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01 test -f /root/.vscode-server/.postCreateCommandMarker
Run: docker exec -w / -u 0 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01 /bin/sh -c command -v git >/dev/null 2>&1 && git config --system credential.helper '!f() { command -v code >/dev/null 2>&1 && code --gitCredential $*; }; f' || true
Run: docker exec -w /root/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0 -e SHELL=/bin/bash -e VSCODE_AGENT_FOLDER=/root/.vscode-server 7619714473fc8c8ab41e55538b057766f04561e35383507dd648f29c3a420f01 /root/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/server.sh --disable-user-env-probe --port 0
Error: Port not found
        at Object.t.launchVSCHeadless (c:\Users\MonsterLin\.vscode\extensions\ms-vscode-remote.remote-containers-0.74.0\dist\extension.js:1:96188)
```

Maybe it will get better after I reinstall the OS. The attempt was frustrating in this time.

**Comment by Monsterlin2018** [comment]
原因找到了。
因为 在远端服务器上部署了Flannel网络，docker启动时附加在内部网络上，使得本地无法连接。
重新设置网络后，正常了
The reason is found.
Because the flannel network is deployed on the remote server, docker is attached to the internal network when it is started, which makes the local connection impossible.
After resetting the network, it's ok。

> 
> [root]# cat /usr/lib/systemd/system/docker.service 
> [Service]
> Type=notify
> EnvironmentFile=/run/flannel/subnet.env 
> #this is internal network
