### ISSUE TITLE
DevContainer takes long to connect to

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1498]
#1471

Some steps could be parallelized. Others could be folded together to avoid some of the overhead of docker exec (or: use a single docker exec to run shell commands).

**Comment by Chuxel** [comment]
We could also consider converting some of the base dev containers to base images that are updated regularly.  E.g. Debian + Git.  This is non-trivial both from a CI and attribution perspective, but likely is worth the effort for some of the most common dev containers.

**Comment by chrmarti** [comment]
Merging into #1823
