### ISSUE TITLE
Support Docker buildArgs

### ISSUE THREAD

**Issue by thernstig** [Microsoft/vscode-remote-release#150]
Currently the Remote Containers support the devcontainer.json `runArgs`. It would be great to amend it with a `buildArgs`. This would open up possibilities to stop at specific build stages with `--target`, or anything else one can imagine when building. `--build-arg` and `--pull` are two other great options that come to mind that one would want to use.

https://docs.docker.com/engine/reference/commandline/build/
https://docs.docker.com/develop/develop-images/multistage-build/#stop-at-a-specific-build-stage

**Comment by thernstig** [comment]
Another issue that could be closed if this is implemented is this one: https://github.com/Microsoft/vscode-remote-release/issues/46

**Comment by egamma** [comment]
Duplicate #46

**Comment by thernstig** [comment]
@egamma #46 specifically only mentions the --target build argument, whereas this issue mentions setting any build arg. So I did not consider it a duplicate when writing this, but as long as #46 is solved with a generic build arg then all good :)

**Comment by egamma** [comment]
@thernstig the issues are linked so this additional info will not get lost.
