### ISSUE TITLE
README is out of date.

### ISSUE THREAD

**Issue by Kai-Richardson** [microsoft/vscode-remote-release#1500]
https://github.com/microsoft/vscode-remote-release/blob/master/README.md

On line 49, the link to the Slack group is not working.

**Comment by roblourens** [comment]
Can you explain the issue some more? Seems ok to me.

**Comment by Kai-Richardson** [comment]
Interesting. When I go to click the link now, it works fine.
It was giving me a non-existent slack group error when I attempted to join previously.
Possibly it was an issue on slack's end, or the aka.ms link redirect was in error.

Closing issue, as not reproducible anymore.
