### ISSUE TITLE
Icon disappear when I use WSL remote

### ISSUE THREAD

**Issue by Lips7** [microsoft/vscode-remote-release#1502]
- VSCode Version: 1.39
- OS Version: windows insider 18990

Steps to Reproduce:

1. Extensions icons disappeard when I launch wsl remote, see the screenshots below.
![image](https://user-images.githubusercontent.com/51849534/65756404-9d548380-e147-11e9-8584-ab0f24f161ba.png)
![image](https://user-images.githubusercontent.com/51849534/65756562-e6a4d300-e147-11e9-918e-5f984149ea01.png)

**Comment by Lips7** [comment]
Seems like VSCode can not load the .svg file from wsl2 correctly.
![image](https://user-images.githubusercontent.com/51849534/65814587-4c5f9080-e216-11e9-8b94-1d05996372d4.png)

**Comment by aeschli** [comment]
@alexandrudima Probably has to do with the change to use `::1` in the resolver.

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode/commit/22caeb97a487fb87ef05a2d80fb61997d624a4e8
