### ISSUE TITLE
downloading docker image fails occasionally

### ISSUE THREAD

**Issue by xinyiz1226** [microsoft/vscode-remote-release#1507]
- VSCode Version: 1.38.1
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open a repo with devcontainer info in remote mode
2. occasionally it will report error saying "cannot resolve mcr.microsoft.com/v2"
3. retry works for me

do we have retry mechanism during image downloading?

**Comment by chrmarti** [comment]
Docker does the downloading. "Cannot resolve" appears to indicate that there is a problem with the DNS resolution, is the `v2` needed in the name?

**Comment by xinyiz1226** [comment]
should be OK. Please note it happens occasionally, and retry works for me. So I guess it is DNS availability issue in a short time. That's why I am asking if we have retry mechanism in VS Code. Otherwise I need to handle it by myself.

**Comment by chrmarti** [comment]
Closing then as we don't want to add retry logic for network infrastructure services. Thanks.
