### ISSUE TITLE
Would be nice to be able to sort per project into folders

### ISSUE THREAD

**Issue by freeyland** [microsoft/vscode-remote-release#1508]
In config file:
Host Projects/Thienpont/Staging-Prod-Emma
    User frederick
    HostName cs107.studioemma.com

In vscode you should have 2 folders: 
Projects
  Thienpont 
     conncection icon
  Other project
    conncection icon
Other master folder

**Comment by roblourens** [comment]
I don't quite follow what you are asking for. How are you suggesting that we sort folders?

**Comment by freeyland** [comment]
Would be nice that your projects can be sorted into folders if you have a lot of projects:
Projects
-- Thienpont project
-- -- conncection icon
-- Other project
-- --conncection icon
Other master folder
