### ISSUE TITLE
Cant open SSH config file or SSH connections

### ISSUE THREAD

**Issue by shrasool** [microsoft/vscode-remote-release#1509]
Issue Type: <b>Bug</b>

Receiving error: "Command 'Remote-SSH: Open Configuration File...' resulted in an error." upon selecting `>Remote-SSH: open configuration file` and selecting the default ~/Users/$USERNAME/.ssh/config file

Extension version: 0.45.6
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (7.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Are there any more details about the error in the developer tools? (Help > Toggle developer tools)

Does that file exist?

**Comment by shrasool** [comment]
[-1571132243649.log](https://github.com/microsoft/vscode-remote-release/files/3728466/-1571132243649.log)
I've generated this log file for the console error.

**Comment by roblourens** [comment]
Thanks, unfortunately that doesn't tell me exactly what the error is. Can you check the "Log (Extension Host)" output channel?
