### ISSUE TITLE
Test: Open a repository into a volume

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#1515]
Test #1395

- [x] Windows @alexr00 
- [x] MacOS @chrmarti 
- [x] Linux @joaomoreno    

Complexity: 3

Test the 'Remote-Containers: Open Repository in Container...' command.

This command supports to clone a repository that contains a `devcontainer.json` file into a docker volume. Use the Docker extension and its 'Volume' section to inspect the volume creation.

- verify that a container with the cloned respository contents is created
  - verify that the intermediate containers to clone and build the image are deleted at the end of the operation.
  - verify that this works with dockerfiles that use a non-root user id (e.g. https://github.com/microsoft/vscode-remote-try-node/blob/9bf39d354a1bf80d74799762e5b80310dde5dab7/.devcontainer/Dockerfile#L15). The files should be owned by this users.
- verify that 'reopen locally' is handled gracefully (since there is no bind mount the command is not available).
- verify that 'Open Recent...' works for such containers.
- verify that an existing volume, created from the same repository is reused.
- verify that such a container is rendered in the Remote Explorer: 
  - shows the source repository as an attribute in the Details section
  - shows the volume mount (and you can inspect the volume from the context menu) in the Details section.
- removing such a container from the explorer should prompt you to remove the corresponding volume.

Limitations:
- no support to clone private repositories
- docker-compose or multi-root setups are not supported.

**Comment by joaomoreno** [comment]
@egamma Pretty cool, everything works as advertised!

> verify that 'reopen locally' is handled gracefully (since there is no bind mount the command is not available).

What does this mean? When I run that action I get: _Reopen Locally' not possible in current context._

**Comment by egamma** [comment]
>>verify that 'reopen locally' is handled gracefully (since there is no bind mount the command is not available).

>What does this mean? When I run that action I get: Reopen Locally' not possible in current context.

@joaomoreno This is the current behaviour, but I agree with #1542 it is lame.
