### ISSUE TITLE
Test: Connect to remote Docker daemon

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1516]
Test #859

- [x] anyOS @joaomoreno 
- [ ] anyOS @dbaeumer 

Complexity: 3

NOTE: Creating the Docker Machine takes ~5 minutes.

Set up a remote Docker host using Docker Machine:
- Check if installed: https://docs.docker.com/machine/install-machine/
- Create in Try Out Subscription: `docker-machine create --driver azure --azure-subscription-id 22597fe7-6f99-41e2-a033-345a493ab393 --azure-location <westus2 or francecentral> --azure-resource-group <your-alias>-docker-machine --azure-size Standard_D2s_v3 <your-alias>-docker-machine`
- Show values for settings (don't eval the env variables): `docker-machine env <your-alias>-docker-machine`
- Docs on Azure driver: https://docs.docker.com/machine/drivers/azure/
- After testing / endgame week: `docker-machine rm <your-alias-docker-machine>`

Verify you can use `docker.host`, `docker.certPath` and `docker.tlsVerify` from the Docker extension to connect to a remote Docker daemon. Test:
- single container
- repository container
- Docker Compose and
- attach to existing container cases.
- Remote Explorer.

Note that the Docker extension will honor these settings in its viewlet which can be useful for checking what is going on.

**Comment by roblourens** [comment]
@chrmarti I get to this when trying to create the host.

![image](https://user-images.githubusercontent.com/323878/66002056-a8652780-e457-11e9-8bf9-0f5e5fb37ec0.png)

**Comment by roblourens** [comment]
I should have permission to do this and I shouldn't have to jit or anything like that...

**Comment by Chuxel** [comment]
FYI - https://github.com/microsoft/vscode-remote-release/issues/1550 I think is a bug related to these changes.

**Comment by chrmarti** [comment]
@roblourens Not sure, you have the same permissions as I for the Try Out Subscription.

**Comment by roblourens** [comment]
Rachel got the same result, can I just use one of your resource groups?

Also I'm not sure what those docker settings are supposed to be set to.

**Comment by chrmarti** [comment]
Unfortunately the configuration of a Docker Machine is highly unportable. (I once managed to export/import with a 3rd party tool.) `docker-machine env ...` would show the settings values.

Could you, as a last attempt, try a different subscription, like the development one: 9b16b0df-65b6-46d3-b9c9-e4fbc86b1fa7

**Comment by roblourens** [comment]
Same result

**Comment by Chuxel** [comment]
If you can't get this working using the Azure driver, you can use the generic SSH type to set up the Docker machine instead.  Just get a SSH host and run this (replacing values as appropriate):

```bash
docker-machine create --driver generic --generic-ip-address <your-ip-address-here> --generic-ssh-user <your-remote-user-here> <your-alias>-docker-machine
```
The key thing is the user you select needs to have [passwordless-sudo](https://serverfault.com/questions/160581/how-to-setup-passwordless-sudo-on-linux) configured.

It will set up the host on the remote machine automatically.

You then run 
```
docker-machine env <your-alias>-docker-machine
``` 
just like above to get the values.

This is how I actually set up my Docker Machines in my Azure DevTest Lab VMs.

**Comment by bowdenk7** [comment]
I had the same issue as Rob on two subscriptions I tried. It works fine with my personal Azure account though.

I then run into this error during create:

```
Error creating machine: Error in driver during machine creation:
compute.AvailabilitySetsClient#CreateOrUpdate: 
Failure responding to request: StatusCode=409 -- 
Original Error: autorest/azure: Service returned an error. 
Status=409 Code="SubscriptionNotRegistered" 
Message="Subscription is not registered."
```

**Comment by bowdenk7** [comment]
Deleting all the resources that were creating and running `docker machine rm wilkelly-docker-machine` and then re-generating everything resolved this error.

**Comment by roblourens** [comment]
I can't get that to work either @Chuxel, I get this error from `docker-machine create`:

```
Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "168.62.29.176:2376": dial tcp 168.62.29.176:2376: i/o timeout
```

It seems like docker is running on the remote at this point but 

```
$ docker-machine ls
NAME                    ACTIVE   DRIVER    STATE     URL   SWARM   DOCKER   ERRORS
roblou-docker-machine            generic   Timeout
```

I try regenerating the certs or running `docker-machine start` on that machine but I can't figure out how to get it to start or be created successfully on the first try.

I think I have passwordless sudo set up correctly

**Comment by dbaeumer** [comment]
I get the same a @roblourens 

![image](https://user-images.githubusercontent.com/1931590/66126558-0590e280-e5ea-11e9-9ea2-d3a052b94bcb.png)

**Comment by chrmarti** [comment]
@Chuxel Did you have this working with all 3 settings set? That would make 3 testers (including me) which would be enough I think. We shouldn't spend too much time here.

Sorry everyone who lost time looking into this. It looked so simple when I tried. :)

**Comment by bowdenk7** [comment]
I ended up getting this working with the 3 settings

**Comment by chrmarti** [comment]
Thanks @bowdenk7! Closing :)

**Comment by Chuxel** [comment]
I was also able to see it running - just didn't see the question this until now due to some randomization. 😊
