### ISSUE TITLE
targets do not show up properly

### ISSUE THREAD

**Issue by caleb15** [microsoft/vscode-remote-release#1517]
```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-29-generic snap
```

ext info:
```
Name: Remote - SSH
Id: ms-vscode-remote.remote-ssh
Description: Open any folder on a remote machine using SSH and take advantage of VS Code's full feature set.
Version: 0.46.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh
```

- VSCode Version: 1.38.1
- Local OS Version: ubuntu 18
- Remote OS Version: ubuntu 18
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. use a ssh config similar to following
2.only foo1 target shows up but the jumpbox should show up too. I also expected it to show *.env1 and when you click on it it would ask you which env instance to connect to (although that is somewhat of a feature request)

```
Host foo1
    User caleb
    Hostname %h
    IdentityFile ~/.ssh/ff_foo_rsa
    Port 253

Host jumpbox.env1.15five.com
    User caleb
    IdentityFile ~/.ssh/ff_env1_rsa
    Port 253

Host *.env1
    HostName %h
    User caleb
    IdentityFile ~/.ssh/ff_env1_rsa
    ProxyJump jumpbox.env1.15five.com
    Port 253
```

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by caleb15** [comment]
note that I can connect to instance.env1 and the jumpbox fine when I specify it through `ssh: connect to host` - this is just a problem with parsing the configuration file.

**Comment by roblourens** [comment]
Got https://github.com/microsoft/vscode-remote-release/issues/186 for this
