### ISSUE TITLE
WSL server user startup script

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#1518]
Tests #912 and #1451

- [x] Windows @roblourens
- [x] Windows @chrisdias

Complexity: 2

With the Remote-WSL (>= 0.39.7) users can now define a script: `~/.vscode-server-insiders/server-env-setup` that is run before the server is started and where users can initialize the environment.

Use cases:
- set `umask` (#1451)
- run `weasel-pageant` (#912)

Test the use cases above. Try what happens when the script is invalid or not a `sh` acript.

The script has to be valid (Bourne) shell script. Don't just source your bash startup scripts

**Comment by roblourens** [comment]
Why this instead of the "user env probe" `bash -ilc` thing that ssh and local vscode do?

**Comment by roblourens** [comment]
I see that the script is running but don't see it affecting my terminal environment, is it supposed to?

![image](https://user-images.githubusercontent.com/323878/66004036-86ba6f00-e45c-11e9-99c5-aef2aef3bb33.png)

**Comment by chrisdias** [comment]
ok, so I think I finally got it to work, but it took me like 30min.

- why doesn't the file have a `.sh` extension?
- I don't see any environment variables showing up in the terminal (as rob notes above)
- its super hard to find the output.  i was trying to find something in the Output pane, when I click on the prompt when first connecting nothing happens, then I found the ability to open the log from the command palette.

I will file issues, just taking notes here.

**Comment by aeschli** [comment]
> Why this instead of the "user env probe" bash -ilc thing that ssh and local vscode do?

The user env probe happens anyways (the code that you added when starting the ext host).
The problem is that this doesn't help users with umask or starting programms.

We used to run the server with `bash -ilc`, but was the cause of multiple issues:
- invalid startup scripts caused the server startup to fail. Users called tmux or ran another shell in their .bashrc. You can call it a user error but it worked for them when opening a terminal.
We're not really a shell and not interactive, so us using -li is not really proper either.
- I only want 'expert' users to config the startup script.

**Comment by roblourens** [comment]
Ok that makes sense and I will probably do the same for ssh at some point.

Is it supposed to be able to modify the environment though? That is a big usecase for me.
