### ISSUE TITLE
WSL2 connection now using `localhost`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#1519]
Test #859

- [x] Windows @gregvanl

Complexity: 2

The connection to a WSL2 VM now uses localhost instead of the VM IP (which is sometimes blocked by the Firewall).

Test that Remote -WSL can connect to a WSL2 distro. Test that icons of installed extensions are correctly shown.

Installing a WSL2 distro requires:
- Windows 10 Insider Preview Build, Fast Ring
- Machine must be able to run Hyper-V. Best use a Windows PC/Labtob. If you run Windows 10 in a VM, you need to enable nested virtualization (works for me in Parallels, but not VMWare)
-  Follow https://docs.microsoft.com/en-us/windows/wsl/wsl2-install

**Comment by aeschli** [comment]
@gregvanl I assume you don't have a WSL2 setup. Maybe @fiveisprime has one?

**Comment by gregvanl** [comment]
@aeschli Either Matt or a Windows writer I know has one. I also have a second laptop I could install Windows Insiders on.

**Comment by gregvanl** [comment]
@aeschli Found a Windows Insiders machine and was able to test. Looks good!
