### ISSUE TITLE
Stuck at "Attempt to reconnect"

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode-remote-release#152]
- VSCode Version: 1.34.0-insider
- Local OS Version: macOS 10.14.4
- Remote OS Version: Ubuntu 16.04.6
- Remote Extension/Connection Type: SSH

I used remote-ssh to successfully work with a remote cmake c++ project several hours ago. But now when I try to connect to remote server and open a project, it always goes to "attempting to reconnect" soon after the project file structure is fetched. 

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/4662568/57197321-7af37b00-6f98-11e9-9e27-03df8b1123f9.png">

The remote terminal does not initiate as shown below:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4662568/57197327-8e9ee180-6f98-11e9-9a1a-7bfc0e335416.png">

From the logging, I don't see any relevant information about why it always attempts to reconnect. I use a typical ssh in iTerm2 to connect to the same server and everything works perfectly but vscode remote-ssh does not work for me any more even when I "Reload Window" (as suggested in #122), completely close vscode, and even reboot.

**Comment by roblourens** [comment]
Can you share the logs from "Log (Window)" and "Remote - SSH"?

**Comment by renkun-ken** [comment]
Logs from "Log (Window)" is empty, and there's no "Remote - SSH" at all.

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/4662568/57202757-ae0b2e00-6fdb-11e9-9da3-7df22f5b54a8.png">

**Comment by renkun-ken** [comment]
The file list structure is fetched in Explorer, but when I click any file, an error occurs in Log (Window) as follows:

```
[2019-05-06 08:50:23.587] [renderer3] [error] connect ECONNREFUSED 127.0.0.1:7475: Error: connect ECONNREFUSED 127.0.0.1:7475
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
[2019-05-06 08:50:28.575] [renderer3] [error] connect ECONNREFUSED 127.0.0.1:7475: Error: connect ECONNREFUSED 127.0.0.1:7475
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
```

**Comment by roblourens** [comment]
Ok, can you open the developer tools (Help > Toggle Developer Tools) and show any logs that are there?

**Comment by renkun-ken** [comment]
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/4662568/57242641-a6dd3200-7066-11e9-8a03-2e5895abcb71.png">

**Comment by roblourens** [comment]
Can you explain how you got to this state? Was this when reconnecting after several hours or running "reload window" or something else?

**Comment by roblourens** [comment]
What "should" happen is that after more than 3 hours, reconnection should fail and show a dialog that with a  "reload window" button. And you should not get that error when connecting fresh.

**Comment by renkun-ken** [comment]
I installed the latest vscode-insider and the problem is gone.

**Comment by roblourens** [comment]
Ok, thanks for following up. Let me know if you see it again...

**Comment by michaeloc** [comment]
My problem very seems. After 10 minutes of processing, the connexion is lost and visual code tries to reconnect forever

**Comment by HinPeng** [comment]
My problem was very similar when connecting to wsl. The connection will lost very soon.
![Annotation 2019-06-11 155237](https://user-images.githubusercontent.com/25048735/59253708-62464700-8c61-11e9-9b2d-4e88e063267b.png)
