### ISSUE TITLE
Test warning popup for remotes that don't meet our prereqs

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1522]
Testing https://github.com/microsoft/vscode-remote-release/issues/1427

- [x] Linux @aeschli
- [ ] Some other linux @joaomoreno 

Complexity 2

- Connect to a remote that doesn't meet https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites, such as CentOS 6
- You should see a warning popup during connection, as in https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites but it won't block connection

**Comment by aeschli** [comment]
Tested with Alpine 3.10, Ubuntu 32bit
