### ISSUE TITLE
Test merging ssh explorer extension into main ssh extension

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1523]
Testing https://github.com/microsoft/vscode-remote-release/issues/1428

- [x] AnyOS @sandy081
- [x] AnyOS @bowdenk7

Complexity 2

- Install the 3 nightly ssh extensions
- Do something to activate ssh (connect to a remote, open the remote explorer, etc)
- You should see a popup prompting you to uninstall the ssh remote explorer
- You shouldn't see duplicate views in the remote explorer at any point
- Check that the ssh part of the remote explorer still works after uninstalling the ssh explorer extension

**Comment by sandy081** [comment]
Are there any plans to remove this extension as it is still available to install.

**Comment by roblourens** [comment]
Yeah I guess I should unpublish it too.

**Comment by sandy081** [comment]
Please be aware of older clients while unpublishing

**Comment by bowdenk7** [comment]
Very first time I did it I got this, though I can't repro this anymore.

![image](https://user-images.githubusercontent.com/820883/66087501-8d181c00-e52c-11e9-8b9b-e64e77d57d26.png)

Reloaded the window and got the prompt as expected, though it displays again after dismissing:
![2019-10-02_15-54-42 (1)](https://user-images.githubusercontent.com/820883/66087678-395a0280-e52d-11e9-9e86-317751728631.gif)

**Comment by roblourens** [comment]
@bowdenk7 that's a different prompt, you have to uninstall the stable remote extension if you are using the nightly version.

**Comment by bowdenk7** [comment]
I definitely read this wrong. I thought the three extensions were `remote SSH`, `SSH explorer`, and `remote SSH (nightly)`. My bad...
