### ISSUE TITLE
Test windows server support

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1524]
Testing https://github.com/microsoft/vscode-remote-release/issues/25

- [x] Linux @mjbvz client
- [x] Windows @sbatten client
- [x] Mac @bpasero client

Complexity 5

- Set `remote.SSH.remoteIsWindows`
- Install ssh nightly extension
- Connect to a windows remote such as https://github.com/microsoft/vscode-internalbacklog/issues/700
- Test typical vscode/remote functionality... paths are rendered correctly, remote and ui extensions work, terminal works, debug works
- After testing for awhile, check that we are not leaking powershell processes on the remote. Check in task manager or using `gps powershell` in powershell. There should not be an extremely large number of powershell processes.

**Comment by bpasero** [comment]
@roblourens a couple of issues:
* `remote.SSH.remoteIsWindows` does not seem like a valid extension key even after having the SSH nightly extension installed
* I was able to connect to the Windows box and do a bit of commands, but now it seems to be no longer accessible, can you check?

**Comment by bpasero** [comment]
I take it back, only IFF I configure `"remote.SSH.remoteIsWindows": true`, connection fails. I will continue testing without this setting.

**Comment by roblourens** [comment]
Yeah the resolver does the right thing but I get `Failed to connect to the remote extension host server (Error: Time limit reached)`

**Comment by roblourens** [comment]
Also don't test this without that setting, you're just connecting to WSL

**Comment by roblourens** [comment]
@alexandrudima this has always worked in the past, and now I can't connect at all. The server log only says

```


*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


IP Address: 10.0.20.5
Extension host agent listening on 63979


[16:05:55] Extension host agent started.
```

seems like something changed in the past few days.

**Comment by mjbvz** [comment]
I connected successfully on my first try from Linux but can't reliably reconnect and have not been able to open a folder. Here's the last part of the logs:

```
[11:21:13.178] Remote server is listening on port 63979
[11:21:13.178] Parsed server configuration: {"agentPort":63979,"osReleaseId":"windows","arch":"x64","sshAuthSock":""}
[11:21:13.179] Starting forwarding server. localPort 36357 -> socksPort 42779 -> remotePort 63979
[11:21:13.179] Forwarding server listening on 36357
[11:21:13.180] Waiting for ssh tunnel to be ready
[11:21:13.180] [Forwarding server 36357] Got connection 0
[11:21:13.181] Tunneled remote port 63979 to local port 36357
[11:21:13.181] Resolved "ssh-remote+robwin" to "127.0.0.1:36357"
[11:21:13.181] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"success","osReleaseId":"windows","arch":"x64","askedPw":"1","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0"},"measures":{"resolveAttempts":1,"retries":1}}
[11:21:13.182] ------




[11:21:13.192] [Forwarding server 36357] Got connection 1
[11:21:13.193] [Forwarding server 36357] Got connection 2
[11:21:13.384] > Install script is 7076, watching sshd parent 10900
```

**Comment by roblourens** [comment]
Oddly, this is working for me just fine now. When this happened, I think I saw the server responding to requests from the local machine but not over the ssh tunnel which would point to a problem with the extension, so I will keep investigating @alexandrudima. 

@bpasero If you had the useLocalServer setting enabled, please try with it disabled.

**Comment by roblourens** [comment]
FYI There are a couple issues reported here - https://github.com/microsoft/vscode-remote-release/issues/25#issuecomment-536923838

windows -> windows isn't working depending on the default shell, and issues with non-admin accounts.

**Comment by roblourens** [comment]
I think I found the issue and it should be fixed now. The "windows -> windows" issue I mentioned should be fixed too. Still need an admin account though.

**Comment by bersbersbers** [comment]
Version 2019.10.1265 is still giving me `''powershell' is not recognized as an internal or external command, operable program or batch file.`

**Comment by roblourens** [comment]
Sorry the nightly extension wasn't updated when I thought it was, I broke the devops pipeline when trying to delete the explorer extension, stand by...

**Comment by bersbersbers** [comment]
`remote-ssh-nightly@2019.10.2486` here:

> [22:16:58.367] Got some output, clearing connection timeout
> [22:16:58.377] > ))) was unexpected at this time.

The corresponding command is
`ssh -T -D 53998 remote "powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -Command \"$e=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String(\\"ZWNobyAx\\")))); powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -EncodedCommand $e\""`
(I replaced by Base64String by `ZWNobyAx` = `Hello 1`)

Pasting this into cmd.exe gives an error similar in spirit:

```
At line:1 char:124
+ ... ([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String(\ZWNobyA ...
+                                                                  ~
Missing ')' in method call.
At line:1 char:124
+ ... oding]::UTF8.GetString([Convert]::FromBase64String(\ZWNobyAx\)))); po ...
+                                                        ~~~~~~~~~~
Unexpected token '\ZWNobyAx\' in expression or statement.
At line:1 char:134
+ ... ding]::UTF8.GetString([Convert]::FromBase64String(\ZWNobyAx\)))); pow ...
+                                                                 ~
Unexpected token ')' in expression or statement.
At line:1 char:135
+ ... ing]::UTF8.GetString([Convert]::FromBase64String(\ZWNobyAx\)))); powe ...
+                                                                 ~
Unexpected token ')' in expression or statement.
At line:1 char:136
+ ... ng]::UTF8.GetString([Convert]::FromBase64String(\ZWNobyAx\)))); power ...
+                                                                 ~
Unexpected token ')' in expression or statement.
At line:1 char:137
+ ... g]::UTF8.GetString([Convert]::FromBase64String(\ZWNobyAx\)))); powers ...
+                                                                 ~
Unexpected token ')' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEndParenthesisInMethodCall
```

Simplifying that call a bit:

`ssh remote "powershell -Command \"$e=(\\"ZWNobyAx\\")\""`

gives a different error, but still an error:

```
\ZWNobyAx\ : The term '\ZWNobyAx\' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:5
+ $e=(\ZWNobyAx\)
+     ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\ZWNobyAx\:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

This works, however (at least in `cmd`, which is used on my local system):
`ssh remote "powershell -Command ""$e=(\\""ZWNobyAx\\"")"""`

**Comment by sbatten** [comment]
@roblourens I was testing this going through the basics after finally getting connected and after about 5 minutes of being connected I got disconnected. After that I could only maintain a connection for 5 seconds at a time.

**Comment by bpasero** [comment]
@roblourens I have to give up, doing more complex things like debugging I am constantly running into https://github.com/microsoft/vscode-remote-release/issues/1601. Maybe this is because I am sitting in CH and connection is slow. If you want more macOS coverage, please find someone in US.

**Comment by roblourens** [comment]
We saw the same in the US, it's definitely just not stable on windows.
