### ISSUE TITLE
Test: Simplified open remote from cli

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#1526]
Tests https://github.com/microsoft/vscode-remote-release/issues/585

- [x] anyOS @roblourens 
- [x] anyOS @sandy081  

Complexity: 2

There's a new syntax to open a remote window on a folder or code-workspace:
`code --remote ssh-remote+myubuntubox /home/x/projects/foo`
`code --remote wsl+Debian /home/x/projects/foo`

- test it for ssh and wsl
- test for folder and workspace
- test what happens when remote name is misspelled or the path does not exist.

**Comment by roblourens** [comment]
@aeschli is this documented anywhere?

**Comment by yamajik** [comment]
Any document？

**Comment by aeschli** [comment]
User docs, no, not yet. Will do.
