### ISSUE TITLE
Ruby Language Server Crashes in Remote SSH Environment

### ISSUE THREAD

**Issue by abrookins** [microsoft/vscode-remote-release#153]
- VSCode Version: 1.34.0-insider (user setup)
- Local OS Version: Windows 10 1809, build 17763.379
- Remote OS Version: Linux - RHEL, `uname -r`: 3.10.0-957.10.1.el7.x86_64
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

0. Install vscode-ruby extension in VS Code on Windows from the Extensions menu
1. Set up a Ruby project on a Linux (RHEL) server/VM
2. Connect to Linux server from within VS Code on Windows using "Remote-SSH: Connect to host..."
3. Open a Ruby file hosted on the remote server within VS Code on Windows in the window currently connected to the remote server

**Expected**
The file opens without any error messages. Language server features work.

**Actual**
An error appears in the "Output" pane at the bottom of the screen and language server features do not  work.

```
[Info  - 09:56:26] Initializing Ruby language server...
[Info  - 09:56:26] Rebuilding tree-sitter for local Electron version
[Info  - 09:56:26] Rebuild succeeded!
/home/andrew/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/node: symbol lookup error: /home/andrew/.vscode-remote/extensions/rebornix.ruby-0.22.3/server/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorE
[Error - 09:56:26] Connection to server got closed. Server will not be restarted
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by benjaminwood** [comment]
This also happens when "Developing inside a Container": https://code.visualstudio.com/docs/remote/containers

**Comment by Chuxel** [comment]
@rebornix Is this due to the Native module issue? 

https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-native-node.js-modules

**Comment by rebornix** [comment]
Yes it is. I'm waiting for reviews for tree-sitter-ruby.

**Comment by rebornix** [comment]
For the ruby ls crashing issue, I already sent out PR for both tree-sitter-ruby and vscode-ruby

* https://github.com/tree-sitter/tree-sitter-ruby/pull/106
* https://github.com/rubyide/vscode-ruby/pull/480

Will ping once we have them merged and released.

**Comment by wingrunr21** [comment]
Hi all,

I'll do the work in vscode-ruby this weekend to get the PR there merged and a release cut

**Comment by Chuxel** [comment]
@wingrunr21 @rebornix Looks like this is fixed correct? If so we can close.

**Comment by Chuxel** [comment]
Closing - looks like this was fixed a while ago.

**Comment by OmriSama** [comment]
Idk if this was really fixed, the `vscode-ruby` extension still doesn't work properly on Remote and it's been super frustrating.

**Comment by Chuxel** [comment]
@OmriSama The change referenced here was merged, but there may be a new issue. 
 I see https://github.com/rubyide/vscode-ruby/issues/533 was raised recently. I'd track progress there since it likely is an extension issue given the scenario.

//cc: @rebornix

**Comment by wingrunr21** [comment]
@OmriSama

The next release is bringing full support. I’m sorry you are frustrated, but the extension has never stated it had full support for remote. There are tracking issues and milestone 0.26.0 for the full support.

**Comment by OmriSama** [comment]
@wingrunr21 awesome! Looking forward to it
