### ISSUE TITLE
Provide the complete remote URI instead of separating scheme and path parts

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-release#1530]
Testing #1526

In cli, why don't we support remote URI instead of separating them.

`code --remote vscode-remote://ssh-remote+myubuntubox/home/x/projects/foo`

This aligns well with other cli args.

Also why do we need to `--remote` arg? Can we infer it from the scheme? In that case, this becomes similar to supporting file and folder uris using `--file` and `--folder`

`code --folder-uri vscode-remote://ssh-remote+myubuntubox/home/x/projects/foo`

**Comment by sandy081** [comment]
I see `code --folder-uri vscode-remote://ssh-remote+myubuntubox/home/x/projects/foo` already works not sure why we need another cli arg?

**Comment by aeschli** [comment]
Yes, it's an alternative to --folder-uri, without having to tell users about `vscode-remote://`

- we already had the `remote`, to be used for empty remote windows
- you can list any numbers of folders/workspaces, like you do in the normal cl
`code folder1 folder2 ...`

**Comment by sandy081** [comment]
We still have to tell users about remote authority which I don't find anywhere in our UI.

> you can list any numbers of folders/workspaces, like you do in the normal cli
`code folder1 folder2 ...`

We can do the same with the uris right?

**Comment by sandy081** [comment]
Also what does it mean when I pass `--remote` and `--folder-uri` both containing folders from same remote?

**Comment by roblourens** [comment]
I think this is good, I find it easier to type and parse. We just have to make sure the remote names are written down somewhere, in the docs or in the extension readmes. If `--remote` and `--folder-url` are both passed, just make sure one overrides the other, or it errors.

**Comment by aeschli** [comment]
no plans to implement
