### ISSUE TITLE
ssh: improve error message when bash is missing

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#1531]
Testing https://github.com/microsoft/vscode-remote-release/issues/1522

- Remote SSH nightly
- Alpine 3.10 in a VM

![image](https://user-images.githubusercontent.com/6461412/65952358-10a90e80-e442-11e9-9ef5-d289fe7384dd.png)

- no message in the log hinting that it could be releated to Alpine
- no button to just ignore the dialog and to look at rest of the log

**Comment by roblourens** [comment]
I was not thinking about this case but it's easy.

**Comment by chrmarti** [comment]
Verified. Should there be a `:` instead of a `.` in the error dialog?

![image](https://user-images.githubusercontent.com/9205389/73529145-76b89900-4416-11ea-8fb3-e3f1b6c7df62.png)

**Comment by roblourens** [comment]
I can't get the error message to look like that. Can you share the full log? And how did you try to connect, did you type `localhost:2222` in the host picker?

**Comment by chrmarti** [comment]
This was with:
```
Host localhost2222
    HostName localhost
    User root
    Port 2222
    IdentityFile ~/.ssh/id_rsa
```
in the SSH config.

**Comment by roblourens** [comment]
Oh, I thought there was a missing `:` between localhost and the port, but that's just the name of your remote. Yeah I'll change the `.` to a `:`
