### ISSUE TITLE
Get the warning to rebuild the container for existing containers

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#1533]
Testing #1514

Open an existing container that was created with an older version of the extension.
You get the warning below, but the Dockerfile has not changed. 

![image](https://user-images.githubusercontent.com/172399/65951911-439ed280-e441-11e9-90a0-837fd59e64d4.png)

**Comment by chrmarti** [comment]
Was the container created with 0.67.3 or earlier? (That's the latest stable version.) For that there should be no notification (this would be a bug).

There was some evolution during the milestone, so maybe the container was created with one of the 'insiders' versions?

**Comment by egamma** [comment]
>There was some evolution during the milestone, so maybe the container was created with one of the 'insiders' versions?

Yes this is likely the case. I cannot reproduce, closing.

**Comment by sandy081** [comment]
I also ran into same case (got the notification) and rebuild again did not show up anything.

**Comment by alexr00** [comment]
Verified by:
Starting on stable with containers version 0.74.0 (the max version for stable) 
Created dev container
Opened dev container in insiders
