### ISSUE TITLE
[wsl] Progress reporting seems broken

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-remote-release#1535]
re #1511

* installed ubuntu in wsl
* connected a window so that code server gets installed
* :bug: progress values keep appending new lines instead of re-use/updating a line

<img width="837" alt="Screenshot 2019-10-01 at 11 59 28" src="https://user-images.githubusercontent.com/1794099/65952890-20752280-e443-11e9-9592-c400dded6db6.png">

**Comment by aeschli** [comment]
Dup of https://github.com/microsoft/vscode-remote-release/issues/672

It's a debug view, typically hidden. Currently no plans to prettify.

**Comment by jrieken** [comment]
How about at least adding the missing `]`?
