### ISSUE TITLE
Error dialog while opening a wsl folder from cli with invalid remote is not helpful

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-release#1538]
Testing #1526

- From CLI open WSL folder with an invalid remote. 
- It shows following dialog

![image](https://user-images.githubusercontent.com/10746682/65954502-64b5f200-e446-11e9-9bd5-e9925d8dc65a.png)

In the terminal we log that the distribution is not available. Is not it possible to show that in the above dialog?

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/70315831-40bcb700-17cf-11ea-9504-2bd0acd96cb6.png)

**Comment by aeschli** [comment]
This git fixed. There's now a proper error message.
