### ISSUE TITLE
Failed to parse remote port from server output:

### ISSUE THREAD

**Issue by rholland** [Microsoft/vscode-remote-release#154]
Trying to connect to digitalocean.  Get following error message:

```
SSH Resolver called for "ssh-remote+ocean-rivet1"
SSH Resolver called for host: ocean-rivet1
Setting up SSH remote "ocean-rivet1"
Using commit id "473af338e1bd9ad4d9853933da1cd9d5d9e07dc9" and quality "insider" for server
Install and start server if needed
> root@165.22.250.134's password: 
"install" terminal command done
Received install output: root@165.22.250.134's password: 
Failed to parse remote port from server output: root@165.22.250.134's password: 
```

When I input the password it repeats asking for it.  What is causing the failure to parse?

adding a bit more detail:

After I input the password some text flashes in the terminal - too fast to read before it clears, a new vscode opens and I get the password prompt again in the terminal

**Comment by roblourens** [comment]
First try setting `remote.SSH.showLoginTerminal`, does that help?

More details: https://code.visualstudio.com/docs/remote/troubleshooting#_enabling-alternate-ssh-authentication-methods

**Comment by rholland** [comment]
I have that set - it prompts me for password, after I put in password
1. vscode closes
2. a new vscode instance opens
3. terminal has focus and it prompts for a password again
4. status bar says opening remote
5. tool tip says setting up SSH .... initializing server

**Comment by rholland** [comment]
On another run it left the old vscode open - here is the error message

`Confirming that ocean-rivet1 is a valid reachable host
Running ssh -T -o ConnectTimeout=15  ocean-rivet1 << 'EOSSH'
uname -sm
EOSSH to confirm the host platform
> root@165.22.250.134's password: 
> 
> Welcome to Ubuntu 18.10 (GNU/Linux 4.18.0-10-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   System information as of Sun May  5 23:40:32 UTC 2019
> 
>   System load:  0.0                Processes:           94
>   Usage of /:   15.7% of 24.06GB   Users logged in:     1
>   Memory usage: 24%                IP address for ens3: 165.22.250.134
>   Swap usage:   0%
> 
>   Get cloud support with Ubuntu Advantage Cloud Guest:
>     http://www.ubuntu.com/business/services/cloud
> 
> 0 packages can be updated.
> 0 updates are security updates.
> 
> New release '19.04' available.
> Run 'do-release-upgrade' to upgrade to it.
> 
> 
> mesg: ttyname failed: Inappropriate ioctl for device
> Linux x86_64
"uname" terminal command done`

**Comment by rholland** [comment]
More info:

When the new vscode is opened it names the terminal "install" in the drop down box.
In the original vs code the name of the terminal is bash and it is connected to the local terminal.  The output panes (read only) has the ans SSH label and the returned SSH information but it only gets through the uname command and then stops and starts a new vscode terminal which gets focus.

**Comment by rholland** [comment]
More info:

I kept entering the password in the terminal after it reset each time.  On the third time it connected.  Here are my questions:

1.  Why is a new instance of vscode opened when I enter the ssh password?
2.  Why do I need to enter the password three times before it connects? 
3.  When I open a remote folder, why do I need to enter the password again?

Thanks.

**Comment by roblourens** [comment]
1. By default we open a new window for the remote you are connecting to just to not disrupt your current window
2. We have to open multiple connections to set up the remote window, and we don't save your password. This is why we recommend using key-based auth - https://code.visualstudio.com/docs/remote/ssh#_getting-started or ControlMaster (if not on windows) https://code.visualstudio.com/docs/remote/troubleshooting#_enabling-alternate-ssh-authentication-methods
3. See 2. We don't want to save your password.

**Comment by roblourens** [comment]
I guess it's not clear, do you have a working window after entering your password 3 times?

**Comment by rholland** [comment]
Thanks for that.  Multi windows happen even if I select same window but you have now explained that is related to password.  Still experimenting.  The 3 entry success seems to happen sometimes but not always.  Will let you know statistics over the next couple of days.

**Comment by roblourens** [comment]
Please let me know how it goes, thanks. I will reopen the issue if there is more to address.
