### ISSUE TITLE
Connect to Host causes vscode to crash

### ISSUE THREAD

**Issue by sgrech** [microsoft/vscode-remote-release#1540]
Issue Type: <b>Bug</b>

Using Connect to Host fails, most of the time it crashes vscode but sometimes it gives out the message 'handshake failed' in ssh connection terminal. I can succesfully connect via ssh to the target machine using the ssh configuration file. WSL connection also seems to be impacted, removed the WSL plugin to ensure it wasn't affecting it but the issue still persists.

Extension version: 0.46.1
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (2.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Can you give some more details? What exactly do you see when it crashes? Can you share the log from the Remote-SSH output channel?
