### ISSUE TITLE
WSL Alpine not working on build 17134

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1543]
Issue Type: <b>Bug</b>

#1511 

It made Alpine the default and then failed:

![image](https://user-images.githubusercontent.com/9205389/65962440-f6c6f600-e458-11e9-9f2e-11f0ded6bb98.png)

Extension version: 0.39.8
VS Code version: Code - Insiders 1.39.0-insider (313ede61cbad8f9dc748907b3384e059ddddb79a, 2019-10-01T07:29:05.652Z)
OS version: Windows_NT x64 10.0.17134
Fetching remote diagnostics for 'WSL' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|8.00GB (2.82GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|44%|

Fetching remote diagnostics for 'WSL' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.
</details>

**Comment by aeschli** [comment]
It's caused by a bug in the Alpine distro on an older WSL. The probing shell script does not return a result.
It that case we now now longer assume it's x64, but make the check and the download on the WSL side.

**Comment by chrmarti** [comment]
Still looks similar:
![image](https://user-images.githubusercontent.com/9205389/67935664-a57e6380-fbca-11e9-970d-3b55f32c7741.png)

Anything I might be missing?

(Btw.: Didn't we have a decorator for the default distro? Is that expected to be gone?)

**Comment by aeschli** [comment]
To use Alpine on WSL on Windows 10 April 2018 (build 1803) you need to install `bash` to work.
I updated our documentation with https://github.com/microsoft/vscode-docs/pull/3208. 

Also, when starting up the Alpine distro it tells you that
```
==== MANUAL STEP ====
If you're on Windows 10 1803 17134, manually execute this/these command(s), NOW:
Or upgrade to the latest version of windows 10
/bin/chmod 755 /
/sbin/apk --no-cache add shadow
/bin/sed -i 's/^export PATH/#export PATH/' /etc/profile

Also you need to provide a /bin/bash executable to use bash.exe from Windows.
Either by symlinking any other shell to /bin/bash or by installing bash.
If you want to change the default user (after you created one), run:
Alpine.exe /config --default-user <username>
== // MANUAL STEP // ==
```
