### ISSUE TITLE
Checkmark missing in WSL Explorer

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1544]
Issue Type: <b>Bug</b>

#1511 

![image](https://user-images.githubusercontent.com/9205389/65963100-5bcf1b80-e45a-11e9-93d7-22a61dcfea86.png)

Extension version: 0.39.8
VS Code version: Code - Insiders 1.39.0-insider (313ede61cbad8f9dc748907b3384e059ddddb79a, 2019-10-01T07:29:05.652Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.4.0-17134-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|8.00GB (2.35GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|44%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17134-Microsoft|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|8.00GB (2.34GB free)|
|VM|44%|
</details>

**Comment by RMacfarlane** [comment]
Looks like a new version of the WSL extension hasn't been published yet, so can't verify yet

**Comment by chrmarti** [comment]
@aeschli Are you going to publish a new version for Remote-WSL for verification?

**Comment by aeschli** [comment]
Published ms-vscode-remote.remote-wsl@0.39.9
