### ISSUE TITLE
WSL Explorer: Recent folders move with default distro

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1546]
Issue Type: <b>Bug</b>

#1511

E.g., there is no 'devel' folder in the Debian distro:

![Oct-01-2019 14-53-34](https://user-images.githubusercontent.com/9205389/65963669-92596600-e45b-11e9-8444-29cf6b947732.gif)

Extension version: 0.39.8
VS Code version: Code - Insiders 1.39.0-insider (313ede61cbad8f9dc748907b3384e059ddddb79a, 2019-10-01T07:29:05.652Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.4.0-17134-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|8.00GB (2.31GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|44%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17134-Microsoft|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|8.00GB (2.31GB free)|
|VM|44%|
</details>

**Comment by alexr00** [comment]
I don't think we can fix this. @aeschli do we have enough info to fix this on older versions of windows where there is no multidistro?

**Comment by alexr00** [comment]
To make this a bit better we now sort and have the default distro on top and show a dialog when you change the default distro without multi-distro support.

![image](https://user-images.githubusercontent.com/38270282/66216625-1ca50280-e6c6-11e9-8563-2ab1f448995c.png)

**Comment by alexr00** [comment]
Also added the same language to this existing message:
![image](https://user-images.githubusercontent.com/38270282/66216912-9f2dc200-e6c6-11e9-8885-72f9a2f33aad.png)
