### ISSUE TITLE
shutdownAction: container not stopped by default

### ISSUE THREAD

**Issue by njbmartin** [microsoft/vscode-remote-release#1548]
- VSCode Version: 1.38.1
- Local OS Version: Mac OS X 10.14.6
- Remote OS Version: `node:lts`
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. initialise with preset `devcontainer` configuration for Node.
2. expose port `3000` via `appPort` option
3. launch `create-react-app` project in Dev Container
4. Close the VS Code window
5. container is still running with port in use

According to the docs `shutdownAction` defaults to `stopContainer`, so shouldn't be necessary in `devcontainer.json`, however adding `"shutdownAction": "stopContainer",` to the configuration now behaves as expected.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Could you check if this is still an issue with the latest VS Code (1.39.2) and Remote-Containers extension (0.81.0)?
