### ISSUE TITLE
Unclear association between workspace and devcontainer.json

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-remote-release#1549]
Testing https://github.com/microsoft/vscode-remote-release/issues/1514

1. Add multiple folders to a workspace, none of them having existing Dockerfiles or devocontainer.jsons, and save the workspace
2. Run the `Open workspace in container` command. As the file selection dialog appears, a notification is also shown saying that the workspace contains a devcontainer.json, which is not true
3. Ignore notification and select the workspace from the file dialog
4. No prompt is given to choose a predefined devcontainer, the window reloads, seemingly choosing the last image I had used with a different project

Once the workspace is open in the container, I'm not able to find any of the container configuration files - they're not visible anywhere in the file tree, not found with file search, and there's nothing in the code-workspace file besides the names of the folder. I've retried this process with two newly created, completely empty folders as the workspace with the same result.

Version: 1.39.0-insider (user setup)
Commit: 313ede61cbad8f9dc748907b3384e059ddddb79a
OS: Windows_NT ia32 10.0.18362
Containers extension version: 0.79.0

**Comment by chrmarti** [comment]
It uses the devcontainer.json in the same folder as your workspace file. Does that explain it?
