### ISSUE TITLE
Locked out of WSL when the setup script fails

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1555]
Testing https://github.com/microsoft/vscode-remote-release/issues/1518

- Have the setup script be some text that is not syntactically valid
- Open new WSL window
- Get error: `/mnt/c/Users/roblou/.vscode-insiders/extensions/ms-vscode-remote.remote-wsl-0.39.8/scripts/wslServer.sh: 1: /home/roblou/.vscode-server-insiders/server-env-setup: Syntax error: "&" unexpected (expecting ")")`
- and I don't connect to WSL, so that means I can't fix the script
- I have to open WSL in an external terminal. If I'm a new user I might not know how to do this, and I'm totally locked out of WSL until I do. 

I think ideally we would still connect when the setup script fails, but show an obvious warning.

**Comment by roblourens** [comment]
Also I just got that error once, if I try to connect later, I just see

```
[2019-10-01 22:06:00.576] Starting VS Code Server inside WSL (Ubuntu)
[2019-10-01 22:06:00.576] Extension version: 0.39.8, Windows build: 18362. Multi distro support: enabled. WSL path support: enabled
[2019-10-01 22:06:00.986] VS Code Server for WSL closed unexpectedly.
[2019-10-01 22:06:00.986] For help with startup problems, go to
[2019-10-01 22:06:00.986] https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips
```

which is less helpful

**Comment by aeschli** [comment]
The easiest way to get out of this is probably to open a WSL shell and rename the setup script.

The idea is that the setup script is an advanced feature, not really for newbies...

**Comment by aeschli** [comment]
Documented that this is an advanced feature and what to do when you locked yourself out:
https://code.visualstudio.com/docs/remote/wsl#_advanced-environment-setup-script
