### ISSUE TITLE
Confusing error when starting with --remote wsl+ a distro that doesn't exit

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1559]
Testing #1526

- Run `code-insiders --remote wsl+ubuntu2`
- There should be a nicer error message. With `--remote` people will probably be guessing at the format

![image](https://user-images.githubusercontent.com/323878/66006802-c8e7ae80-e464-11e9-9acf-128ef31fc9e8.png)

**Comment by aeschli** [comment]
dup of #1538
