### ISSUE TITLE
container not rebuilt when changing config files (2nd time)

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-remote-release#1562]
Testing #1514

- Scaffold out a simple express app using something like `npx express-generator myExpressApp` into a multi level folder structure. in my case I have all my folders in `~/src` so in this case I scaffolded the app into `~/src/myExpressApp`. This is important :).
- Using the Docker extension, add docker files to the workspace with `Docker: Add Docker Files to Workspace`
- Update the version in the `docker-compose.yml` to 3.0 (see #1560)
- Add remote-container configuration files with `Remote-Containers: Add Development Container Configuration Files...`
- Choose `From 'docker-compose.yml'`
- Change `..:workspace` in `.devcontainer/docker-compose.yml` to `.:workspace` (see #1561)
- Now reopen in a container with `Remote-Containers: Reopen in Container`
- Edit any `docker-compose.yml` file or the `.devcontainer.json`

Result: nothing happens, I was expecting a prompt to rebuild based on the test plan item.

**Comment by chrisdias** [comment]
oh wait, I get a prompt the next time I open the folder in a container.

**Comment by chrisdias** [comment]
Ok, it worked the first time. Subsequent changes to the config files don't show the prompt.

**Comment by chrmarti** [comment]
Fixed an issue with when the Dockerfile is not explicitly given (defaulting to `Dockerfile`).

Verification:
- Run the Docker extension's `Docker: Add Docker Files to Workspace...` in an empty folder.
- Run command `Remote-Containers: Reopen in Container` and pick the existing `docker-compose.yml`.
- Change Dockerfile.
- Reload window.
- Verify that you are notified about the change in the Dockerfile.

This is with `build: .` in the `docker-compose.yml`. Repeat with:
```yaml
build:
  context: .
```
Use `Remote-Containers: Rebuild Container` to reset the notification first before verifying to this case.

and an explicitly named Dockerfile (e.g., rename it):
```yaml
build:
  context: .
  dockerfile: Dockerfile-renamed
```
Again use `Remote-Containers: Rebuild Container` to reset the notification first before verifying to this case.
