### ISSUE TITLE
infinite loops in server-env-setup

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-remote-release#1564]
Testing #1518

An infinite loop makes it impossible to connect to WSL...

in `server-env-setup`:

``` bash
while :
do
        echo "Press [CTRL+C] to stop.."
        sleep 1
done
```

I can't press `CTRL+C` anywhere to stop this crazy train.

**Comment by aeschli** [comment]
It's an advanced feature, and we warn in the documentation that you need to know what you do...
