### ISSUE TITLE
rename server-env-setup to server-env-setup.sh?

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-remote-release#1565]
Testing #1518

why doesn't `server-env-setup` have a `.sh` extension?

**Comment by aeschli** [comment]
I'm not a Linux expert at all, but it seems not common to have a `.sh` suffix on for init files:
https://how-to.fandom.com/wiki/Guide_to_linux_configuration_files

@Chuxel Do you have a name suggestion?

**Comment by Chuxel** [comment]
@aeschli @chrisdias Both are common. This is basically like `cmd` files in the Windows world - there it responds to both with and without the extension. The difference is whether you want people to think about it like a command or a script. In the Linux world, if the command is sourced, it always is without `.sh`.

A good example of a scripts w/o the `.sh` in common use is `mvnw` for Maven and node module `bin` files.  In fact, some of these are actually executable node.js code without the `.js`.

I'd say it's fine as-is.

**Comment by aeschli** [comment]
Thanks @Chuxel . It is sourced, so no `.sh`.

**Comment by chrisdias** [comment]
why not support both, so if someone doesn't read the fine print of the docs and accidentally add `.sh` then we still pick it up and it works.
