### ISSUE TITLE
move server-env-setup to /etc?

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-remote-release#1567]
Testing #1518

Should `server-env-setup ` be `/etc/vscode-remote` or `/etc/vscode-insiders-remote`, or some variation in the `/etc` folder?

See: https://www.linux.com/tutorials/linux-directory-structure-explainedetc-folder/

**Comment by Chuxel** [comment]
I believe `/etc` would require root access to use.  Modern Linux provides a user specific locations user the home directory (`~`) for user specific config files (`~/.confg`) and install locations (`~/.local/share`) that can be overridden by XDG_ environment variables (`$XDG_CONFIG_HOME`, `$XDG_DATA_HOME`) if we want to move it out of `~/.vscode-server` .  `$XDG_DATA_HOME` is where the URI handler lives for Live Share.

**Comment by aeschli** [comment]
No changes planed
