### ISSUE TITLE
Where do I type in an IP address?

### ISSUE THREAD

**Issue by TheRook** [microsoft/vscode-remote-release#1568]
Issue Type: <b>Bug</b>

This addon is baffeling. I don't undersatnd how to connect to anything, have you ever used Putty?  Perhaps you could learn a thing or two about UX form Putty. 

Uninstall.

Extension version: 0.46.1
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details>

**Comment by roblourens** [comment]
Please see the docs here, it's easy once you know how to do it: https://code.visualstudio.com/docs/remote/ssh#_connect-to-a-remote-host
