### ISSUE TITLE
Repository Container: Offer to create devcontainer.json when it does not exist

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1570]
#1515

Using a repository that does not have a devcontainer.json ends with an error dialog. It would be great if we instead offered to create the devcontainer.json with the QuickPick sequence we already have. (E.g., use 'microsoft/python-sample-vscode-flask-tutorial').

**Comment by chrmarti** [comment]
Variations to this could be:
- Associate a local devcontainer.json instead of copying the definition into the project folder to avoid polluting the repository.
- Associate a local DevContainer definition that is readonly (and updates with updates to the Remote-Containers extension).

**Comment by egamma** [comment]
Support to add a dev container configuration when it doesn't exist has been added.

I've extracted the ideas from https://github.com/microsoft/vscode-remote-release/issues/1570#issuecomment-537408077 into a separate issue.

To verify:
- Run `Remote Containers: Open Repository in Container...`
- Enter a repository that does not have a dev container configuration, e.g. https://github.com/microsoft/vscode-npm-scripts.git

You will prompted with the dev container definitions quick pick.

**Comment by egamma** [comment]
To verify:
- Use 'Remote Containers: Open Repository in Container...' e.g. https://github.com/Microsoft/vscode-npm-scripts to clone a GitHub repository without a dev container configuration in a dev container
- You will be prompted to add a configuration
