### ISSUE TITLE
Repository Container: Support cloning into shared volume

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1571]
#1515

It can be useful to colocate repository clones to, e.g., copy files between them. Sharing a single volume also avoids creating too many volumes.

This could be implemented using a user setting or an additional step when creating a repository container.

**Comment by Chuxel** [comment]
@chrmarti @egamma This got done with 1.41, correct?

**Comment by chrmarti** [comment]
Correct, that was implemented with #1581.
