### ISSUE TITLE
pythonPath not respected in remote container

### ISSUE THREAD

**Issue by syagev** [microsoft/vscode-remote-release#1579]
- VSCode Version: 1.38.1
- Local OS Version:  Window 10 1903
- Remote OS Version:  Ubuntu 18.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:
1. Create a project with pipenv
2. In the folder `settings.json` point `pythonPath` to the python interpreter in the virtualenv (i.e. something like `C:\Users\username\.virtualenvs\SomeProject-09hncfd\bin\python.exe`
3. Create a custom Dockerfile based of Ubuntu 18.04 and build image (e.g. `my-image:latest`), in this image create a virtualenv based on the project's Pipfile using pipenv. Assume the virtualenv (in the image) is created at `/root/.local/share/virtualenvs/SomeProject-1298hf`
4. Setup remote like so:
```
"image": "my-image:latest",
"settings": {
  "terminal.integrated.shell.linux": "/bin/bash",
  "python.pythonPath": "/root/.local/share/virtualenvs/SomeProject-1298hf/bin/python",
  "python.linting.enabled": true,
  "python.linting.pylintEnabled": true,
  "python.linting.pylintPath": "/root/.local/share/virtualenvs/SomeProject-1298hf/bin/pylint"
},
```
5. Open VSCode remote, run the project.
6. An error message appears: "You need to select a Python interpreter ..."

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

In remote mode, VSCode doesn't seem to respect the `pythonPath` settings - it does not find the python in the virtualenv (although it's there). In the terminal the project can be run using either one of these commands:
1. `pipenv run myscript.py` from the project's folder, or
2.  `/root/.local/share/virtualenvs/SomeProject-1298hf/bin/python myscript.py`

However in the Python Interpreter Selection only the system's Python installs appear (/usr/bin/python3, /usr/local/bin/python3)

Possibly related:
https://github.com/microsoft/vscode-remote-release/issues/187
https://github.com/microsoft/vscode-remote-release/issues/141

**Comment by chrmarti** [comment]
Closing in favor of https://github.com/microsoft/vscode-python/issues/7813. Thanks.
