### ISSUE TITLE
RemoteCommand with SSH is ignored

### ISSUE THREAD

**Issue by MOZGIII** [microsoft/vscode-remote-release#158]
- VSCode Version: 1.34.0-insider (user setup), 473af338e1bd9ad4d9853933da1cd9d5d9e07dc9
- Local OS Version: Windows 10 1809
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. I set `RemoteCommand` to my custom shell I like to use for ssh connections at `.ssh/config`.
2. I connect to the remote host and default shell is used in the integrated terminal.

Does this issue occur when you try this locally?: Not applicable
Does this issue occur when you try this locally and all extensions are disabled?: Not applicable

**Comment by roblourens** [comment]
Sorry for the delayed response. To set your default shell, use the setting `"terminal.integrated.shell.linux": "/bin/bash"`. In fact, having RemoteCommand in your ssh config can break the ssh connection process so I'm surprised if you don't see it broken.

**Comment by MOZGIII** [comment]
How am I supposed to set it per server? Doesn’t sound like a viable solution to me.

**Comment by Chuxel** [comment]
@MOZGIII <kbd>F1</kbd> > **Preferences: Open Remote Settings** when connected to the SSH host.  Also available from the settings UI under the remote tab.

See https://code.visualstudio.com/docs/remote/ssh#_ssh-hostspecific-settings

**Comment by MOZGIII** [comment]
Cool, works for me

**Comment by tiago-af-silva** [comment]
I've experienced the same issue while trying to use `RemoteCommand` in my `~/.ssh/config` to switch users after connecting. Had something like this:

```
Host server1
  HostName hostname
  Port 123
  User user1
  RemoteCommand sudo su user2
  RequestTTY yes
```

Logs showed me the extension was adding `-o RemoteCommand=none` to the SSH command, no matter what command I would specify. The only way to make it work was to revert the _Remote - SSH (Nightly)_ extension back to version **2019.5.38340**.

- VSCode Version: 1.36.0-insider
- Local OS Version: macOS High Sierra 10.13.6
- Local OpenSSH Version: 8.0
- Remote OS Version: Ubuntu 16.04 x86_64
- Remote Extension/Connection Type: SSH

**Comment by roblourens** [comment]
Yes, this isn't supported. We just use ssh to forward a port from the server, and ssh doesn't allow you to use RemoteCommand while forwarding a port (and it wouldn't have the affect you expect anyway)
