### ISSUE TITLE
[Polish] Odd error message when full git URI pasted into input box for Open Repository in Container

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#1580]
Related to #1515 

Currently if I paste in a GitHub https URI like I do when cloing from the command line into the input box for Open Repository in Container, you get a confusing error message.

![image](https://user-images.githubusercontent.com/312252/66077898-d0b35b80-e515-11e9-9978-4d774efaf66d.png)

Repro:
1. Start VS Code, run Open Repository in Container
2. Paste in `https://github.com/Microsoft/vscode-dev-containers` into the input box

Expected: Clones
Actual: Errors given this is not the format it expects,  It looks like the logic to generate a container image name is failing which is causing an invalid argument error.

We could trap, but ideally we'd support full URIs if pasted in to support alternate Git repository types -- particularly if private repos (#1578) are also working.

```
Cloning Github repository:  into volume vsc--1a00b3d4c5c85a2e272bdd546a49c21a
Run: docker run --rm --mount src=vsc--1a00b3d4c5c85a2e272bdd546a49c21a,dst=,type=volume,volume-driver=local alpine/git clone https://github.com/Microsoft/vscode-dev-containers 
invalid argument "src=vsc--1a00b3d4c5c85a2e272bdd546a49c21a,dst=,type=volume,volume-driver=local" for "--mount" flag: target is required
See 'docker run --help'.
```

I assume the `--` in `vsc--1a00b3d4c5c85a2e272bdd546a49c21a` should be the repo name which is probably where the issue is.

Version: 1.39.0-insider (user setup)
Commit: 695ee74864ef93d10f5de0861cb66af190e76211
Date: 2019-10-02T08:56:48.092Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
Extension version: 0.79

//cc: @egamma

**Comment by egamma** [comment]
Didn't handle the case when the full URL doesn't have a `.git` suffix.
