### ISSUE TITLE
Support "Open folder in container..." like experience when attaching to a running container

### ISSUE THREAD

**Issue by akappen** [microsoft/vscode-remote-release#1582]
I am working with an existing in-house tooling that spins up dozens of containers and conditionally mounts local source code folders into them. It uses docker but extends it in ways that prevent me from using the `devcontainer.yml` file to orchestrate spinning up an equivalent environment.

I would like to be able to work with these already running containers in the same way as when you use the Remote Development tools to "Open folder in container...". When done this way terminals and tasks and launch configs and selected extensions run in the container, but editing and most importantly git interactions happen on the host machine.

It appears that attaching to a running container and opening a local folder in your workspace are mutually exclusive operations. Trying to open a local folder in a container attached vscode window instead opens it in a new unattached window.

I know this is an uncommon usage pattern and a nitpick in many ways. By attaching to the running container I can do 90% of what I want. The main drawback is that the git integration falls apart, since git is run in the container and it doesn't have my credentials or basic gitconfig like email and name.

**Comment by chrmarti** [comment]
The upcoming release will remember the last workspace folder, installed extensions and dynamically forwarded ports for containers with the same image and image tag. You could give that a try by using VS Code Insiders which also gets the newer Remote-Containers: https://code.visualstudio.com/insiders/

**Comment by chrmarti** [comment]
We register a Git credentials helper in the container when `git` is installed in the container. We should also copy the gitconfig into the container, but currently that is missing when attaching (an oversight).

The combination of both would make Git work in the container. Would that help?

**Comment by chrmarti** [comment]
I should add: You would still need to install Git in the container yourself.
