### ISSUE TITLE
Windows ssh remote: Cannot use `\` in explorer new file dialog to create directories

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-remote-release#1584]
Issue Type: <b>Bug</b>

From #1524

**Repo**
1. Connect from linux to windows over ssh
1. Using the `new file` action in the file explorer
1. Try entering a path such as `a\b\c.js` that should create a file `c.js` inside two directories

**Bug**
Directory not created. See the error:

![Screen Shot 2019-10-02 at 3 02 15 PM](https://user-images.githubusercontent.com/12821956/66085340-c305d200-e525-11e9-9a16-e53431b56cd4.png)

Extension version: 2019.10.2486
VS Code version: Code - Insiders 1.39.0-insider (695ee74864ef93d10f5de0861cb66af190e76211, 2019-10-02T08:56:32.907Z)
OS version: Linux x64 4.15.0-64-generic
Remote OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (2 x 2194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|6.31GB (1.11GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: robwin|
|OS|Windows_NT x64 10.0.18362|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (2 x 2394)|
|Memory (System)|7.00GB (2.49GB free)|
|VM|0%|
</details>

**Comment by isidorn** [comment]
Yeah. The `/` probably works.
However this was never supported and is a fair feature request. Issue is that even though we show `\` as a separator, that the services below and everything use `/`. So the new file action should transform all separators before passing them to the `fileService`.
Code pointer https://github.com/Microsoft/vscode/blob/6ff7bf27c9dc447cd95693debdc5b90910e804b5/src/vs/workbench/contrib/files/browser/fileActions.ts#L929

Let me know if you are passionate about this and I can do it next milestone.

**Comment by isidorn** [comment]
@mjbvz I would really appreciate if you could verify this using insders from tomorrow onward.

**Comment by JacksonKearl** [comment]
Unable to verify as I can't seem to get a Remote-SSH windows setup working.

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/97498828-19f8f900-192a-11eb-8bd0-c8f72a8e5114.png)
still seeing this. 

And maybe setting a record for longest time to `verification-needed`?
