### ISSUE TITLE
Forward slashes used in title bar for windows ssh remote

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-remote-release#1585]
Issue Type: <b>Bug</b>

From #1524

**Repo**
1. Connect from linux to windows over ssh
1. Set `"window.title": "${activeEditorLong}"`

**Bug**
In title bar, see the path is using forward slashes instead of a windows style path:

![Screen Shot 2019-10-02 at 3 45 50 PM](https://user-images.githubusercontent.com/12821956/66087269-bab09580-e52b-11e9-8b61-f9fe62671e1c.png)

Extension version: 2019.10.2486
VS Code version: Code - Insiders 1.39.0-insider (695ee74864ef93d10f5de0861cb66af190e76211, 2019-10-02T08:56:32.907Z)
OS version: Linux x64 4.15.0-64-generic
Remote OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (2 x 2194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|6.31GB (1.11GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: robwin|
|OS|Windows_NT x64 10.0.18362|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (2 x 2394)|
|Memory (System)|7.00GB (2.49GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Actually this might be mine.

**Comment by mjbvz** [comment]
Same formatting used in the `open editors` view too

**Comment by roblourens** [comment]
Fixed now
