### ISSUE TITLE
Backslashes path separators matching as expected used for quick open on windows ssh remote

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-remote-release#1586]
Issue Type: <b>Bug</b>

From #1524

**Repo**
1. Connect from linux to windows over ssh
1. Create a workspace with the following structure

    ```
    sub/
      index.js
    ```

1. Using quick open, type `sub\index`

**Bug**
You can see that the `sub` part is not actually being matched (it is not blue)

![Screen Shot 2019-10-02 at 3 50 13 PM](https://user-images.githubusercontent.com/12821956/66087436-580bc980-e52c-11e9-947a-eb846ec2d713.png)

This is different than on a normal windows machine:

![Screen Shot 2019-10-02 at 3 48 35 PM](https://user-images.githubusercontent.com/12821956/66087415-45919000-e52c-11e9-90ac-9b432bf7a3f9.png)

It works properly if you use `sub/index`

Extension version: 2019.10.2486
VS Code version: Code - Insiders 1.39.0-insider (695ee74864ef93d10f5de0861cb66af190e76211, 2019-10-02T08:56:32.907Z)
OS version: Linux x64 4.15.0-64-generic
Remote OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (2 x 2194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|6.31GB (1.11GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: robwin|
|OS|Windows_NT x64 10.0.18362|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (2 x 2394)|
|Memory (System)|7.00GB (2.49GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Seems to work now, minus https://github.com/microsoft/vscode/issues/108535
