### ISSUE TITLE
Attach to Remote Container not working when using Remote SSH

### ISSUE THREAD

**Issue by aidandj** [microsoft/vscode-remote-release#1590]
- VSCode Version: 1.38.1
- Local OS Version: OSX 10.12.6
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH/Docker

Steps to Reproduce:

1. Connect to Remote SSH host
2. Set "docker.host": "localhost:2375"
3. Open Docker Pane. See running containers
4. Right click on running container->Attach Visual Studio Code
5. Get Error: "Docker version 17.06.1 or later required"

Maybe I'm misreading the docs and this is not a supported use case. I do not have Docker on my local os (not enough room) so I was trying to use remote ssh to connect to a Linux VM I have running docker, then attach to that container. Is this possible?

It appears to be seeing all the containers correctly, but when it tries to attach it looks for my local docker instance (which I don't have)

![image](https://user-images.githubusercontent.com/1535239/66091021-be97e400-e53a-11e9-8440-6f8fc7864a50.png)

**Comment by aidandj** [comment]
I can attach a shell to it just fine, but cannot attach an instance of VS Code to it.

**Comment by aidandj** [comment]
This may be a problem with the docker extension, but I'm also having trouble getting the "Targets (Containers)" Populated also.

Maybe things just aren't forwarding correctly? Or I'm doing something unsupported.

**Comment by aidandj** [comment]
I'm getting closer. Running on a windows PC with docker installed (but not running). I was able to do the following.

In SSH config, set `LocalForward 23750 localhost:2375`
In the remote workspace settings.json I set "docker.host" : "localhost:23750"

By doing this I was able to see my "Targets (Containers)" populated.

And I was able to open an instance of VSCode in the remote container!

*But*, when I went to do the same thing on my Mac (docker not installed locally) I still get the error about docker missing.

Is this because the docker attach command relies on local docker commands?

If possible this should maybe be moved to the docker extension.

**Comment by aidandj** [comment]
Installed Docker on my Mac and now it works. Is this expected behavior? I was hoping to do everything remote.

**Comment by chrmarti** [comment]
The `docker` CLI is required. You could install Docker for Windows and then shutdown the Docker daemon if you don't need/want that. Stackoverflow has an answer for installing the CLI only, but I haven't tried that: https://stackoverflow.com/a/43594065/7857763

**Comment by aidandj** [comment]
Thank you.
