### ISSUE TITLE
Terminal shell path not found when pwsh configured

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#1593]
Testing #1524 

This might be expected but I've forgotten as it never came up for me before.

When connecting from Windows to Windows in SSH remote, launching a terminal fails with `The terminal shell path "C:\Program Files\PowerShell\6\pwsh.exe" does not exist` as I have pwsh on my local box.

**Comment by Tyriar** [comment]
This is expected, remote machine settings should override user settings to workaround.
