### ISSUE TITLE
Remote SSH Windows: paths have trailing backslash

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#1597]
Test: https://github.com/microsoft/vscode-remote-release/issues/1524

![image](https://user-images.githubusercontent.com/900690/66102002-1c671300-e5b1-11e9-9190-06cc78a71893.png)

I would not expect to see trailing backslash.

**Comment by roblourens** [comment]
I think this is correct, I see a trailing slash on mac: 
![image](https://user-images.githubusercontent.com/323878/66137324-c5157280-e5b1-11e9-8b6f-d261f57cc32c.png)

**Comment by bpasero** [comment]
Hm ok this is probably do distinguish files from folders @alexr00 ?

**Comment by bpasero** [comment]
I don't really understand why that is needed given the icons we have:

![image](https://user-images.githubusercontent.com/900690/66141836-ae4c3b80-e604-11e9-8990-26a11ebfdaba.png)

**Comment by roblourens** [comment]
You can have file icons turned off too

**Comment by bpasero** [comment]
Sure, but that is not our default. I would aim to do what OS dialogs tend to do and I have never seen trailing slash or backslash anywhere.

**Comment by bpasero** [comment]
Filed: https://github.com/microsoft/vscode/issues/81911
