### ISSUE TITLE
Remote SSH Windows: symbolic link appears twice

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#1598]
Test: #1524

![before](https://user-images.githubusercontent.com/900690/66102148-98615b00-e5b1-11e9-97ce-737fb8900ee8.gif)

**Comment by isidorn** [comment]
Code pointer https://github.com/Microsoft/vscode/blob/6ff7bf27c9dc447cd95693debdc5b90910e804b5/src/vs/workbench/contrib/files/browser/views/explorerDecorationsProvider.ts#L52

The symbolic link should never appear two times.
@jrieken I believe that the `provideDecorations` overwrites what was returned previosuly, so I do not have ideas who the decoration could be duplicated.

**Comment by jrieken** [comment]
Two providers by any chance?

**Comment by jrieken** [comment]
So, this registration never gets disposed: https://github.com/microsoft/vscode/blob/6ff7bf27c9dc447cd95693debdc5b90910e804b5/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L104. 

Assuming an explorer view gets recreated (?) that you have another provider

**Comment by isidorn** [comment]
Yeah, let me add it to the disposables. Good catch @jrieken 
And @roblourens can check if this reproduces with Friday's vscode insider.

However not sure if the view somehow gets recreated. Would be funky, and I would expect other things to potentially break.

**Comment by isidorn** [comment]
Optimistically closing this. Please reopen if you still see @roblourens @bpasero
