### ISSUE TITLE
Remote SSH Windows: paths are not well formatted

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#1599]
Test: #1524

Notice how the path in the hover looks not well formatted.

![before](https://user-images.githubusercontent.com/900690/66102167-a9aa6780-e5b1-11e9-8e44-844663a51e6f.gif)

**Comment by bpasero** [comment]
Actually this is just true for any path.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode-remote-release/issues/1583
