### ISSUE TITLE
Filesystem is not mounted

### ISSUE THREAD

**Issue by riponbanik** [microsoft/vscode-remote-release#160]
Issue Type: <b>Bug</b>

1. Follow the instruction to Open Folder in Remote Contrainer. 
2. Browse the location in container ~ls -al workspaces/vscode-remote-try-node - does not copy server.js file

drwxr-xr-x 3 root root   80 May  5 07:20 .
drwxr-xr-x 3 root root 4096 May  6 01:46 ..
drwxr-xr-x 2 root root   60 May  5 07:20 node_modules
-rw-r--r-- 1 root root   86 May  5 07:20 yarn.lock

Extension version: 0.48.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.16299
Remote OS version: Linux x64 4.9.125-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (10.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js Sample|
|OS|Linux x64 4.9.125-linuxkit|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (2 x 2463)|
|Memory (System)|3.84GB (0.23GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment]
>Browse the location in container ~ls -al workspaces/vscode-remote-try-node - does not copy server.js file

What do you mean by does not copy?

Are you sharing the drive as described here: https://code.visualstudio.com/docs/remote/containers#_installation

For more tips & tricks for docker on windows pls see: https://code.visualstudio.com/docs/remote/troubleshooting#_docker-desktop-for-windows-tips

**Comment by riponbanik** [comment]
@egamma The files in the local systems are not found in the remote location and thus not able to run server.js. 

yes the sharing is enabled and it works for my other containers.

**Comment by egamma** [comment]
@riponbanik 

>Browse the location in container ~ls -al workspaces/vscode-remote-try-node - does not copy server.js file

Are you saying that only `server.js` is missing in the explorer and when you run `ls` in a terminal in the container?

**Comment by riponbanik** [comment]
@egamma By ls I listed the files in remote to show that files are not being copied.

**Comment by chrmarti** [comment]
@riponbanik Does rebuilding the container help? What does `docker inspect <container id/name>` show as mount points?

**Comment by riponbanik** [comment]
@chrmarti  Thanks. I rebuilt today and it is able to mount now. But when I do curl http://localhost:3000 it gives an empty reply.
![image](https://user-images.githubusercontent.com/963681/57432705-eaf45080-7279-11e9-9505-fae29fce1bb6.png)

docker inspect shows the following -

"Mounts": [
            {
                "Type": "bind",
                "Source": "/host_mnt/c/Temp/vscode-remote-try-node",
                "Destination": "/workspaces/vscode-remote-try-node",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/host_mnt/c/Users/xxx/.gitconfig",
                "Destination": "/root/.gitconfig",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],

**Comment by chrmarti** [comment]
Have you configure the `"appPort"` in the devcontainer.json? Alternatively try `F1` > `Remote-Containers: Forward Port From Container` when the server is already listening on port 3000.

**Comment by riponbanik** [comment]
@chrmarti  YES using default and you can see it in the screen shot that I have attached in my previous comment.

**Comment by chrmarti** [comment]
That should work, given what your screenshot shows only Docker is involved with this. Are you sure there is something listening on port 3000 of the container?

**Comment by antoniusostermann** [comment]
If anyone else having the original problem with not mounted files: Double-check if your firewall is still allowing traffic on the described ports / if the shared device setting still works. You can do that easily by switching the shared device off and on again. 

Mine was enabled, but the rule I added to my firewall wasn't enabled anymore. Didn't get any error message in vscode, but after switching the shared device on and off again.

**Comment by chrmarti** [comment]
Thanks @antoniusostermann. @riponbanik Any idea what is causing the empty reply? Maybe a firewall issue too?

**Comment by riponbanik** [comment]
@chrmarti I use the http://localhost:3000 so there will be no firewall in between. I have found the issue, the app was not running inside the container, so I had to run it manually.

root@b8e875b37fad:/# cd workspaces/vscode-remote-try-node/
root@b8e875b37fad:/workspaces/vscode-remote-try-node# node server.js
Running on http://0.0.0.0:3000

Now I am getting reply -

![image](https://user-images.githubusercontent.com/963681/57739709-09ce6900-76f8-11e9-92af-1e1cb1aff851.png)

**Comment by chrmarti** [comment]
You might want to set `"overrideCommand": false` in the devcontainer.json, so it doesn't override what you have set with `CMD`. (`ENTRYPOINT` avoiding that is an oversight on our side, we will likely fix that.)
