### ISSUE TITLE
Remote SSH Windows: colorization takes ages

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#1600]
Test: #1524

When I open a TS file over this setp, I takes almost 10s until the TS file gets colorized. I do not understand that, isn't coloring provided from the client?

![before](https://user-images.githubusercontent.com/900690/66102362-6997b480-e5b2-11e9-893f-a35a899eaf54.gif)

**Comment by mjbvz** [comment]
@roblourens I don't think I'm the right owner. Assigning @alexandrudima to investigate since it is related to syntax highlighting

**Comment by alexandrudima** [comment]
Yes, the TS basic colorisation extension runs on the remote because it contributes json schemas. We have a duplicate for this somewhere...

**Comment by alexandrudima** [comment]
There it is --- https://github.com/microsoft/vscode/issues/73336

**Comment by bpasero** [comment]
Wow.

**Comment by alexandrudima** [comment]
I think we should build a "request" viewer for the websockets... The amount of stuff that travels through there can be a lot larger than all of our `.js` files combined ...
