### ISSUE TITLE
Remote SSH: error adding new host

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#1602]
SSH Nightly 2019.10.2817

- In the remote explorer click on the '+' above SSH Targets
- Enter an IP of a machine (e.g. 10.165.252.70)
- select /home/user/.ssh/config
- error dialog

/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2551 Error: Cannot read property 'after' of undefined
	at p.append (/home/aeschli/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2019.10.2817/out/extension.js:127)
	at Object.t.addSshHost (/home/aeschli/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2019.10.2817/out/extension.js:1)
onDidNotificationChange @ /usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2551

Content of my config file:
```
Host vmware-fedora
 User aeschli
 HostName 10.165.252.76
 ControlMaster auto
 ControlPath  ~/.ssh/sockets/%r@%h-%p
 ControlPersist  600
Host vmware-ubuntu
 User aeschli
 HostName 10.165.253.59
 ControlMaster auto
 ControlPath  ~/.ssh/sockets/%r@%h-%p
 ControlPersist  600
Host kyrian-fedora-vm

```

**Comment by aeschli** [comment]
Removing the last line of my config file fixes the issue.

**Comment by roblourens** [comment]
Filed https://github.com/cyjake/ssh-config/issues/24
