### ISSUE TITLE
"Reopen in Container" command not do anything

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1608]
I'm seeing the "Reopen in Container" command not do anything when I run it in a workspace with multiple dockerfiles.
Steps:
Clone the vscode-dev-containers repo.
Open the azure-ansible folder
Add Folder to workspace -> azure-functions-node-lts
Add Folder to Workspace -> swift-4
Reopen in Container

Nothing seems to happen.

_Originally posted by @alexr00 in https://github.com/microsoft/vscode-remote-release/issues/1071#issuecomment-538312941_

**Comment by chrmarti** [comment]
Reproduced when the workspace file is not saved yet.

**Comment by bhack** [comment]
I think that there is also some quite complex bug with the same "Reopen in Container" behavior adding another project folder in the workspace.

**Comment by bhack** [comment]
Also there is also a problem when the workspace is save outside the project folder. It search `dockerFile` in the wrong path.

**Comment by chrmarti** [comment]
We now ask the user to save the workspace file first.
