### ISSUE TITLE
Docker: port forwarding not showing up in picker

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#1609]
* open vscode in container
* pick Ubuntu 18 as base image
* run this script

```
require('http')
    .createServer((req, res) => {
        res.end('Hello!');
    })
    .listen(0);
```
* select to forward port

=> 🐛 port does not show up

I have used the `node` executable from the server to run the script.

**Comment by chrmarti** [comment]
Can reproduce with the Ubuntu 18.04 definition.

**Comment by chrmarti** [comment]
Fixed with the new implementation. Closing for verification.
