### ISSUE TITLE
Bash completion is not working

### ISSUE THREAD

**Issue by Frankie412** [microsoft/vscode-remote-release#1610]
Issue Type: <b>Bug</b>

I've created remote WSL window, and not able to make a Bash completion from terminal.

Before WSL plugin (in wsl console):

"git check"*press tab*- completes is as "git checkout"

After WSL plugin (in wsl console):

"git check"*press tab* - nothing happens

Extension version: 0.39.5
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.16299
Remote OS version: Linux x64 4.4.0-43-Microsoft

**Comment by Tyriar** [comment]
Using WSL debian I don't get auto-complete for git in conhost, did you install something to get it to work?

**Comment by Tyriar** [comment]
Actually it works in WSL ubuntu, both in conhost and in VS Code. This is likely an issue with how you configured your bash launch scripts where it's not getting hit. You'll need to do some investigation yourself as it's environment related.
