### ISSUE TITLE
Missing folders when Reopening in Container on a workspace with several folders

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#1612]
Found while verifying https://github.com/microsoft/vscode-remote-release/issues/1071

- Save the workspace file in a parent folder of all workspace folders.
- Have Dockerfile / docker-compose.yml files in the workspace folders' main folder (those in .devcontainer won't be picked up).
- Reopen folder in container from that. 

You end up in the container, but without the folders:
![image](https://user-images.githubusercontent.com/38270282/66198596-0898db00-e69d-11e9-9d5a-8cc6ede7883e.png)

There didn't appear to be any errors in the output.

**Comment by chrmarti** [comment]
@alexr00 Sorry for the delay, do you still have the workspace file? I see backslashes in the screenshot and am wondering where they come from.

**Comment by alexr00** [comment]
I don't know what I did to cause this before, and when I try to rerun "Reopen in container" it doesn't let me choose a different source for the configuration, it always re-use the first choice I made (which makes this difficult to try to repro).
