### ISSUE TITLE
Can't connect to host: unreachable or not Linux x86_64 (Linux i686)

### ISSUE THREAD

**Issue by shuishang** [microsoft/vscode-remote-release#162]
Issue Type: <b>Bug</b>

Can't connect to host: unreachable or not Linux x86_64 (Linux i686)

Extension version: 0.35.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|44%|
</details>

**Comment by egamma** [comment]
Please provide more information so that we can reproduce the problem. I assume you are using vscode-remote-ssh?

**Comment by edtamarin** [comment]
I have a similar issue.

I have installed the OpenSSH client, generated the keys and filled in the config file. If I initiate the SSH session from PowerShell, it goes through with no issues. If I rty to connect to host through Remote-SSH, I get the following error:

```
Can't connect to my_host: unreachable 
or not Linux x86_64 (operable program or batch file.)

The terminal process command 
'cmd.exe/c (type "C:\Users\myuser\AppData\Local\Temp\vscode-linux-multi-line-command-ddm.sh" | ssh my_host) &
exit /b 0' failed to launch (exit code: 255)
```

The host is running Ubuntu. What could be the cause of this?

Extension version: 0.35.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by psolyca** [comment]
I had the same problem from Windows to Ubuntu with OpenSSH installed.

Have you add ControlMaster to your ssh config ?
If yes, remove it and try.

**Comment by Clqsin45** [comment]
I had the same problem too, may caused by ssh agent? and I solved it as the following steps:
1. configure ssh (F1 -> connect to host -> configure ssh hosts)
```Host example-remote-linux-machine-with-identity-file 
    User your-user-name-on-host
    HostName another-host-fqdn-or-ip-goes-here
    IdentityFile ~/.ssh/id_rsa-remote-ssh
```
2. connect example-remote-linux-machine-with-identity-file
3. enter password of your private key
4. choose not use ssh agent when vs code ask  you to enable ssh agent.

enable SSH Agent may also work[(https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent](https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent)

To enable SSH Agent automatically on Windows, start PowerShell as an Administrator and run the following commands:
```
# Make sure you're running as an Administrator
Set-Service ssh-agent -StartupType Automatic
Start-Service ssh-agent
Get-Service ssh-agent

```

**Comment by edtamarin** [comment]
@Clqsin45 Enabling SSH Agent helped. What was happening is that I use an SSH key without a passphrase so I did not start the SSH Agent up (since in the docs it is only mentioned for a key+passphrase). Now I can connect to the remote host.
