### ISSUE TITLE
"Target (SSH)" Window Does Not Contain Most-Recently Connected Server

### ISSUE THREAD

**Issue by funkeyfreak** [microsoft/vscode-remote-release#1622]
Issue Type: <b>Bug</b>

### Expectations

1. Add a configuration in $HOME/.ssh/config to connect to a remote host (Win32 ssh).
```bash
Host *
  User git@github.com
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/a-private-key

Host My-Work-Computer
  User user@DOMAIN
  AddKeysToAgent yes
  UseKeyChain yes
  IdentityFile ~/.ssh/another-private-key
```
2. Connect to this host using CMD+P => ">REMOTE-SSH:Connect to Host..."
3. Select "My-Work-Computer" from the list of hosts
4. Connection is successful 🎉
5. Exit connection
6. Connection is visable in the targets frame in vscode

### REALITY

6. Connection is not visable in the targets frame in vscode
![image](https://user-images.githubusercontent.com/5327214/66291031-9c34fc00-e895-11e9-9d97-b26e190b364f.png)

Extension version: 0.46.1
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'ssh-remote+7b22686f73744e616d65223a224761646765742d4d53227d' timed out.
</details>

**Comment by roblourens** [comment]
This is because `My-Work-Computer` doesn't have a HostName. Is `My-Work-Computer` found through DNS? You can add `HostName My-Work-Computer` to make it show up.
