### ISSUE TITLE
Extension install fails - EACCES

### ISSUE THREAD

**Issue by mcaulifn** [microsoft/vscode-remote-release#1629]
Issue Type: <b>Bug</b>

Attempting to install the Lombok plugin in WSL. Getting `EACCES: permission denied` when the plugin install process attempts to move the folder from `.gabrielbb.vscode-lombok-0.9.9` -> `gabrielbb.vscode-lombok-0.9.9`

Extension version: 0.39.5
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

**Comment by sandy081** [comment]
@mcaulifn Are you able to reproduce this still? If so, can you please let me know

- Installing this extension in local VS Code works?
- Do you have any process (like Windows Defender) hooking on to the folder where extensions are installed?

**Comment by mcaulifn** [comment]
I was able to delete the .vscode folder completely to get by. I have not installed any new extensions recently.

- yes, installing locally worked
- it was all w/in WSL so I don't think Defender would be able to see that. I am suspecting the node process was the culprit but wasn't sure how to prove it

**Comment by sandy081** [comment]
Please check what processes are locking that folder? For some guidance look at this - https://unix.stackexchange.com/questions/85994/how-to-list-processes-locking-file
