### ISSUE TITLE
Attempting to reconnect ...

### ISSUE THREAD

**Issue by futurehome** [microsoft/vscode-remote-release#163]
I can connect to a remote server by remote-ssh, but when I try to open the folder on the remote server, vscode will show "Attempting to reconnect ... ", and only after maybe 10mins, I can connect to the server again.
The remote server runs Ubuntu 18.04 x86_64.

I found some errors in the log file under folder .vscode-remote in the server as below:
> EXTHOST: PROCESS EXITED
> 0
> null
> ==> Received a management connection
> ==> Received an extension host connection.
> ==> Using UI language: en
> ==> Received an extension host connection.
> ==> Using UI language: en
> { Error: write EPIPE
>     at WriteWrap.afterWrite [as oncomplete] (net.js:833:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
> Error: Unexpected SIGPIPE
>     at process.on (/root/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/out/bootstrap.js:5:192)
>     at process.emit (events.js:182:13)
> Error: Unexpected SIGPIPE
>     at process.on (/root/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/out/bootstrap.js:5:192)
>     at process.emit (events.js:182:13)
> EXTHOST: PROCESS EXITED
> 0
> null
> ==> Received an extension host connection.

We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Extension version: 0.35.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (9.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alimovz** [comment]
Almost identical issue here. Running Windows 7 with almost exact same hardware params as the OP. Connecting to a EC2 instance running Ubuntu 18 LST. Everything works great. Then at random times VS code puts up this message:
![reconnecting](https://user-images.githubusercontent.com/13075330/61023972-ebd05e00-a360-11e9-9af1-03c24c33a1f7.png)

What I know for certain is that the load on the remove box spikes through the roof and a separate putty SSH terminal logged into it becomes super slow to respond. And yet when I manage to run top or uptime, the load is over 20.

**Comment by trasherdk** [comment]
I'm seeing similar behavior.
Getting disconnected every 2 minutes, loosing the changes to the file I'm working on.

**Server** is a  Slackware64 14.2, 32GB RAM, 1000/1000 Mbit internet.
OpenSSH_7.4p1, OpenSSL 1.0.2s  28 May 2019
```
Linux 4.4.190 #1 SMP Wed Aug 28 12:53:50 CEST 2019 x86_64 Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz GenuineIntel GNU/Linux
```
```
$ ~/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/node -v   
v10.11.0
```

**Client** is Windows 8.1 x64, 16GB RAM. 300/100 Mbit fiber. 
OpenSSH_7.1p1, OpenSSL 1.0.2e 3 Dec 2015

**Log on server:**
```
==> Received a management connection
==> Received an extension host connection.
==> Using UI language: en
Got start params: { language: 'en',
  break: undefined,
  port: undefined,
  debugId: undefined }
==> Received a management connection
==> Received an extension host connection.
==> Using UI language: en
==> Received an extension host connection.
==> Using UI language: en
==> Received an extension host connection.
==> Using UI language: en
{ Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
Error: Unexpected SIGPIPE
    at process.on (/home/vbox/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/bootstrap.js:5:192)
    at process.emit (events.js:182:13)
Error: Unexpected SIGPIPE
    at process.on (/home/vbox/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/bootstrap.js:5:192)
    at process.emit (events.js:182:13)
{ Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
Error: Unexpected SIGPIPE
    at process.on (/home/vbox/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/bootstrap.js:5:192)
    at process.emit (events.js:182:13)
Error: Unexpected SIGPIPE
    at process.on (/home/vbox/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/bootstrap.js:5:192)
    at process.emit (events.js:182:13)
```

**Comment by anandbhattad** [comment]
Similar behavior and losing connection in less than a minute.

**Comment by roblourens** [comment]
Lots has changed since the last comments, sorry for not getting to this earlier. Please file new issues with the log if you are still having problems.
