### ISSUE TITLE
Please support s390 architecture

### ISSUE THREAD

**Issue by ArulDhandapani** [microsoft/vscode-remote-release#1630]
This remote development support extend to s390 architecture platform, where many development done by using legacy tools. This will be bring mainframe TEXT/CLI interface users to GUI modern development.

Below the extensions in extended support to this architecture help basic developments at begin.

- Remote Development 
  - Remote - SSH
  - Remote - SSH: Explorer

**Comment by roblourens** [comment]
Sorry but with no expertise or test system, this is not likely to happen.
