### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Rizary** [microsoft/vscode-remote-release#1632]
- VSCode Version: 1.39
- Local OS Version: Windows
- Remote OS Version: Linux
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Run linux on hyper-v
2. Connect vscode using ssh to the host.

The error is like the following picture:

![image](https://user-images.githubusercontent.com/7221768/66461132-8f392800-eaa2-11e9-9fb5-3a3f3d6106d0.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Notes: I work well prior to version 1.39.

**Comment by roblourens** [comment]
Where did that error come from?

**Comment by Rizary** [comment]
It comes from the linux VM.

**Comment by roblourens** [comment]
Yes but where do you see it? Which log file, screen etc

**Comment by alexandrudima** [comment]
Indeed, it looks like [`Module.__resolveLookupPaths`](https://github.com/nodejs/node/blob/64219741218aa87e259cf8257596073b8e747f0a/lib/internal/modules/cjs/loader.js#L462-L499) can return `null` sometimes...
