### ISSUE TITLE
WSL: Improve formatting on "recent workspaces" list

### ISSUE THREAD

**Issue by thoean** [microsoft/vscode-remote-release#1633]
The list of recent projects includes the full path, therefore cutting off the relevant part. A mouse-over reveals the underlying project, but it's slow and hard to use.

To make it specific:
* Windows Task bar -> right click on VS Code icon
* Reveals the recent workspaces
  * Those opened in WSL mode, show the full path
  * Those opened in standard mode, show the project name

I like the fact to distinguish between a WSL project and non-WSL project, but simply pre-fixing it with [WSL] would be fully satisfying.

![OUTLOOK_aQgVVapTMM](https://user-images.githubusercontent.com/7394947/66467232-66a23580-ea84-11e9-918e-4876f43be374.png)

**Comment by thoean** [comment]
Thank you @aeschli !

**Comment by sbatten** [comment]
@aeschli what is the new formatting supposed to look like?

**Comment by aeschli** [comment]
Just the file name or folder name + `[remote]`, if remote.

![image](https://user-images.githubusercontent.com/6461412/67930579-58958f80-fbc0-11e9-9fb1-7d340857069d.png)

**Comment by sbatten** [comment]
ah, working today
