### ISSUE TITLE
Remote-SSH : Helper does not traverse .ssh sub directories to show additional config entries

### ISSUE THREAD

**Issue by sharathm** [microsoft/vscode-remote-release#1638]
- VSCode Version: 1.38.1
- Local OS Version: Mac OS 10.15
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH/Docker/WSL
SSG
Steps to Reproduce:

In my local machine, I have several sub directories where ssh configs have been split for easy maintenance. 
Ex: 
```
.ssh/
├── dev-one/
│   ├── config
│   ├── server1.pem
│   ├── server2.pem
├── dev-two/
│   ├── config
│   └── server1.pem
└── config
```

In the root file `~/.ssh.config` I have included references to the other config files as

```
Include dev-one/config
Include dev-two/config
```

For example the file `dev-one/config` contains a entry

```
Host server652255
  Hostname 1xx.xxx.xxx.xx
  User  root
  IdentityFile ~/.ssh/id_rsa
```

**Steps to Reproduce**
1.  Press Cmd + Shift + P to bring up the Remote-SSH: Prompt
2. I am expecting to see the auto complete for `server652255` . Only entries in the root config file, that is the entries inside `~/.ssh/config` show up.

Does this issue occur when you try this locally?: No.
_From a regular terminal things work as expected and i can ssh into servers via their name_

Does this issue occur when you try this locally and all extensions are disabled?: No
_Not relevant, as the issue is with auto complete of possible SSH config options._

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/65
