### ISSUE TITLE
Install binaries outside roaming user profile on Windows

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode-remote-release#1639]
My roaming profile on a Windows 10 server fails to sync because my profile has gotten too big: A partial reason is the folder `C:\Users\bersbersbers\.vscode-server-insiders`, which holds binaries as well as extensions, all of which are quite big. I wonder if these files could be stored in `C:\Users\bersbersbers\AppData\Local` somewhere.

**Comment by roblourens** [comment]
Yeah, I think they should be kept there instead.
