### ISSUE TITLE
SSH tunnel command completed unexpectedly

### ISSUE THREAD

**Issue by xiaoqinxing** [microsoft/vscode-remote-release#164]
Log: Spawning tunnel with: ssh  10.85.4.199 -L localhost:36458:localhost:38447 "echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity"
Spawned SSH tunnel between local port 36458 and remote port 38447

Error: Bad forwarding specification 'localhost:36458:localhost:38447'

My view: command with "ssh  10.85.4.199 -L 36458:localhost:38447" is ok

**Comment by kieferrm** [comment]
@xiaoqinxing what OS are you on? What's the version of OpenSSH?

**Comment by xiaoqinxing** [comment]
Thank you for your reply.
My OS: win7
OpenSSH: 3.8.1p1
OpenSSL 0.9.7d 17 Mar 2004

**Comment by roblourens** [comment]
That appears to be a very old version of SSH. From where did you install it on windows? Can you update?
