### ISSUE TITLE
Allow pre-download/caching of the server installation package

### ISSUE THREAD

**Issue by phudson** [microsoft/vscode-remote-release#1640]
My scenario:
1. I have Internet access to start with
2. I connect to a VPN that has no internet access
3. I then need to SSH to another server that also has no internet access

So the remote installation fails. But then, so does the local one for scp'ing to the remote host

So I would like to be able to tell Vscode to download the server (and any other extensions I might want remotely) while I'm off the VPN, then when I am on the VPN it accesses those local copies if it can't download them locally.

**Comment by bhack** [comment]
It could partially overlap with https://github.com/microsoft/vscode-remote-release/issues/185 needs

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/1242
