### ISSUE TITLE
VSCode states that this plugin is not longer required

### ISSUE THREAD

**Issue by lanceofwhichwedream** [microsoft/vscode-remote-release#1642]
- VSCode Version: 1.39.0
- Local OS Version: Debian Unstable
- Remote OS Version: Ubuntu Xenial
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1. Open VsCode
2. NAvigate to any remote codebase using this extension
3. Notification will pop up stating Extension is no longer needed

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

VsCode provides a notification stating this extension is no longer needed however no documentation appears for vscode or this extension stating any news that this functionality has been introduced into the main VsCode codebase, please provide guidance on how to handle this notification.

**Comment by jaydiablo** [comment]
I think maybe this issue is related #1428?

I'm seeing the notice too, trying to find official docs/notes about it being included in core as well.

**Comment by jaydiablo** [comment]
FWIW, it's just prompting to remove the Explorer extension, as #1523 states. I uninstalled, and still have the `Remote - SSH` and `Remote - SSH: Editing Configuration Files` extensions installed (and all seems to work ok so far).

**Comment by roblourens** [comment]
Yeah, this is just to remove the Explorer extension which is now redundant. This is mentioned in the remote release notes here: https://github.com/microsoft/vscode-docs/blob/master/remote-release-notes/v1_39.md#eliminating-the-remote---ssh-explorer-extension

**Comment by QGB** [comment]
The "Remote-SSH: Explorer" extension is no longer needed. Would you like to uninstall
