### ISSUE TITLE
SSH: Got remote setup working, but can't access Extensions Marketplace to install new extensions

### ISSUE THREAD

**Issue by sergei3000** [microsoft/vscode-remote-release#165]
I have everything working in my VS Code Insiders. I see remote files, git directories are recognized correctly and so on.
But I can't install new extensions. When I try to search for them in the Extensions Marketplace, all I see in the results is:
"We cannot connect to the Extensions Marketplace at this time, please try again later."
I thought since I'd had everything working that meant I had all the connections needed. Or am I wrong and installing additional extensions require something more than what is needed for the initial installation?
https://marketplace.visualstudio.com seems to be available from curl.

- VSCode Version: Code - Insiders Version 1.34.0
- Local OS Version: macOS Mojave version 10.14.4
- Remote OS Version: Red Hat Enterprise Linux Server release 7.4 (Maipo)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Setup remote connection with VS Code Insiders
2. Search for an extension in Extensions Marketplace

**Comment by sandy081** [comment]
@sergei3000 Is it also not working in other windows where you have local folders opened?

**Comment by sergei3000** [comment]
@sandy081 from what I've found out in recent days it seems these problems appear because of some security limitations in my company. This can be closed.
