### ISSUE TITLE
Connect Remote Host through VPN Tunnel as provided in configuration

### ISSUE THREAD

**Issue by BR0008** [microsoft/vscode-remote-release#1650]
The configuration file may support addition of VPN parameters by which SSH Remote connection shall be triggered in a private VPN tunnel.

This should help solve for a lot enterprise adoption.  Today you need to connect your machine to VPN and then ssh to the box. Instead if the remote connection to the host server can be made inside a dedicated tunnel, it would be a cheese!

**Comment by roblourens** [comment]
Can you give an example of how this should work? If this is something that SSH can already do out of the box, sure, but I probably wouldn't implement something totally new for this.

**Comment by BR0008** [comment]
While SSH supports VPN at protocol level, the below could through some light into the topic at different perspectives.

- https://www.techrepublic.com/article/how-to-use-ssh-as-a-vpn-with-sshuttle/
- https://wiki.archlinux.org/index.php/VPN_over_SSH
- https://www.linuxjournal.com/content/ssh-tunneling-poor-techies-vpn

**Comment by roblourens** [comment]
This looks more like using SSH to emulate a VPN, which seems not relevant to what vscode is doing.

**Comment by BR0008** [comment]
Yes, if SSH could be used to emulate VPN then we could bring about something like below:
<img width="1389" alt="system" src="https://user-images.githubusercontent.com/44339359/67352335-55b9ef80-f56d-11e9-973c-db0c05e67d8d.png">

**Comment by roblourens** [comment]
Thanks for the diagrams but it doesn't help, your links describe using dynamic forwarding with SSH to set up a VPN tunnel to the whole remote machine. 

Maybe I am slow, but I'm not understanding what you are asking for, and it doesn't sound helpful for vscode, sorry.

**Comment by BR0008** [comment]
Thanks for the time. Will it be possible for me to submit a pull request?

**Comment by roblourens** [comment]
The code for this is not open source, sorry.
