### ISSUE TITLE
terminal does not change path to current dir after opening

### ISSUE THREAD

**Issue by codder414** [microsoft/vscode-remote-release#1651]
Hello ! I use VS Code Insiders, and after last update, i discovered one bug. I heavily use SSH Remote  extension in order to work with code via ssh. 
Here is info:
,
![image](https://user-images.githubusercontent.com/7738622/66644065-b588d000-ec28-11e9-8fec-e9fcbbd8da4f.png)

So right after connection, if you open terminal, it does not change path to project directory. So now, if i open the editor, it opens at home dir.

**Comment by Tyriar** [comment]
Probably caused by https://github.com/microsoft/vscode/commit/7f5a4a3f5bee5594ee31002d28a4d68c1a3bac78#diff-2cd0788646964b3c2ee8f5393da7e367

**Comment by Tyriar** [comment]
I reverted it, will need to be more careful when I apply that again.
