### ISSUE TITLE
Symlink Extensions that already exist on remote VSCode

### ISSUE THREAD

**Issue by allenc97** [microsoft/vscode-remote-release#1652]
Hi,

In my usage of the new Jupyter Notebook support in Azure, I realized that the SSH extension creates ~/.vscode-server folder to store its configurations. However, this causes the extension to be unable to use any existing extensions on the remote, which are regularly stored at ~/.vscode. Can we create a flag, that if enabled, symlinks the extension directory of ~/.vscode-server to use the extension directory of ~/.vscode?

Thanks
Allen

**Comment by roblourens** [comment]
You may have different sets of UI and remote extensions installed, so it's much easier for us to keep them separate. You can create a symlink like this if you want.
