### ISSUE TITLE
Opening a workspace file inside a container fails as of 0.81

### ISSUE THREAD

**Issue by rbaker5** [microsoft/vscode-remote-release#1653]
Error below appears after:
1. Attach to running container
2. Open a file .code-workspace.code-workspace inside a subdirectory of home folder inside container instance.
3. Container is linux based.

These steps worked before September 2019 update to VSCode.  I've tried extension version 0.80 and 0.81 so far.  Both failed.

```
Setting up container with ***
TypeError: Cannot read property 'uri' of undefined
        at t.resolve.n.window.withProgress (c:\Users\***\.vscode\extensions\ms-vscode-remote.remote-containers-0.81.0\dist\extension.js:45:44576)
```

**Comment by dfarley1** [comment]
Same issue here.  Just updated VSCode to 1.39.1 and the container extension is 0.81.0.  Both my host and container are Linux.  I tried deleting everything under `/home/dan/.vscode-server` in the container as well as `/home/danf/.vscode` on the host but no dice.

```
Setting up container with ***
TypeError: Cannot read property 'uri' of undefined
        at n.window.withProgress (/home/danf/.vscode/extensions/ms-vscode-remote.remote-containers-0.81.0/dist/extension.js:45:44576)
```

**Comment by rbaker5** [comment]
Reverting to 0.74 resolved this for me.

**Comment by roblourens** [comment]
Maybe someone else can look at this since @chrmarti is out, @alexr00?

**Comment by chrmarti** [comment]
Verification: Open a workspace file from the attached container's home folder.
