### ISSUE TITLE
When downloading the VSCode Remote binary - do not wait for 90s

### ISSUE THREAD

**Issue by sr229** [microsoft/vscode-remote-release#1655]
There are cases that downloading the vscode tarball will take some time especially where there are people with rather crappy connections. We shouldn't wait for 90s for VSCode to recieve a signal from vscode-remote if its just downloading the tarball for the server. Else, it should only wait for such signal if it detects it found a binary.

**Comment by aeschli** [comment]
Can you paste the WSL log here to see where it got stuck?
(Click on the link in the WSL progress dialog to see the log)

Note:
- The timer restarts when there is any output from the script (such as download or untar progress)
- If you are on a recent version of Windows/WSL (April 2018 Update and newer) we download the server on the Windows side, before even starting the server script.

**Comment by sr229** [comment]
@aeschli Can't reproduce currently since the server installed fine, but to reproduce, kindly throttle your network to 3G speeds and wait for approximately 90s.

**Comment by aeschli** [comment]
I found the problem. You were right. If the download happens on the host side we would not reset the timeout.

**Comment by aeschli** [comment]
To verify you need a very slow connection where the server download takes more than 90 sec.

**Comment by connor4312** [comment]
I was able to repro this running on the latest vscode and nightly remote extensions.

![image](https://user-images.githubusercontent.com/2230985/70269451-437bc580-1757-11ea-8fe8-7c950fe8e8fe.png)

**Comment by aeschli** [comment]
Pushed a fix for ms-vscode-remote.remote-wsl@0.41.5
