### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by MagixInTheAir** [microsoft/vscode-remote-release#1656]
Issue Type: <b>Bug</b>

high CPU usage from multiple VSCodeServer instances (NodeJS)

Extension version: 0.47.1
VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:30:33.955Z)
OS version: Linux x64 5.0.0-31-generic snap
Remote OS version: Linux x64 4.9.0-8-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|4, 4, 3|
|Memory (System)|19.29GB (5.98GB free)|
|Process Argv|--force-user-env --unity-launch|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ANNA-BACKEND|
|OS|Linux x64 4.9.0-8-amd64|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (4 x 2303)|
|Memory (System)|1.96GB (0.57GB free)|
|VM|100%|
</details>

**Comment by MagixInTheAir** [comment]
![Capture d’écran de 2019-10-13 00-27-37](https://user-images.githubusercontent.com/8146140/66704630-57570c80-ed50-11e9-985f-6a4646176049.png)
```
Vagrant@ANNA-BACKEND:~/ANNA-Backend$ ps aux | grep vscode
vagrant   1217  0.0  0.0   4288   760 ?        S    12:39   0:00 sh /home/vagrant/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown --port=0
vagrant   1225  0.1  2.9 990264 61096 ?        Sl   12:39   0:18 /home/vagrant/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/node /home/vagrant/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/main.js --host=127.0.0.1 --enable-remote-auto-shutdown --port=0
vagrant   1303  0.0  1.9 873216 39184 ?        Sl   12:39   0:02 /home/vagrant/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/node /home/vagrant/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/bootstrap-fork --type=watcherService
vagrant   1322  0.2  4.5 1281896 93752 ?       Sl   12:39   0:37 /home/vagrant/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/node /home/vagrant/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/home/vagrant/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/uriTransformer.js
vagrant   1337  0.0  3.7 602496 77092 ?        Sl   12:39   0:03 /home/vagrant/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/node /home/vagrant/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/node_modules/typescript/lib/tsserver.js --syntaxOnly --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /tmp/vscode-typescript1000/7460589a6dca9789dc09/tscancellation-af2f634cdbb9615d9b0b.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
vagrant   1343 93.4 11.7 794560 240636 ?       Sl   12:39 214:13 /home/vagrant/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/node /home/vagrant/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-typescript1000/7460589a6dca9789dc09/tscancellation-2c4d3676582793b69b7e.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
vagrant   1370  0.8  4.0 663860 82708 ?        Sl   12:39   1:58 /home/vagrant/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/node /home/vagrant/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /home/vagrant/.cache/typescript/3.6 --enableTelemetry --typesMapLocation /home/vagrant/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation
vagrant   2243  0.0  2.1 576076 44828 ?        Sl   14:52   0:02 /home/vagrant/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/node /home/vagrant/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=1322
vagrant  21253  0.0  0.0  12780   940 pts/1    S+   16:28   0:00 grep vscode
```

**Comment by MagixInTheAir** [comment]
This happens only with NodeJS v10

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by hunterlxt** [comment]
Same issue. Although I closed all windows of vscode, the multi related processes stay with high cpu usage.

**Comment by ifuyivara** [comment]
Any news on this? It is happening to us too :)

**Comment by intnick** [comment]
Me as well

**Comment by GoogleSkrome** [comment]
Me too :(

**Comment by KoenChiu** [comment]
same here.

**Comment by orangelynx** [comment]
Problem was gone for me after disabling docker extension in the remote workspace, removing .vscode-server directory and reconnecting.

**Comment by mjbvz** [comment]
Closing as OP never replied with information to investigate this (it seemed TS specific but could have been fixed by our TS updates)

If you are seeing a perf issue with VS code, follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. If it still seems VS Code itself is to blame, open a new issue
