### ISSUE TITLE
Support 'Reveal in Explorer' in WSL

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#1659]
WSL supports to open a WSL file/folder in the windows explorer from the command line. This feature could be used to support the 'Reveal in Explorer' command in the WSL setup.

**Comment by aeschli** [comment]
We would need to add a hook to the `Reveal in Explorer` command for the mapping of remote-url to drive.

**Comment by egamma** [comment]
The same hook could be used for a bind-mounted remote container to support this.

**Comment by nicobrinkkemper** [comment]
You can just write `explorer.exe .`

**Comment by burkeholland** [comment]
@egamma So you would be able to view a file in a container with Explorer/Finder? Did I read that right?

**Comment by leandro-manifesto** [comment]
If the folder is in a Windows drive acessed through WSL (`/mnt/c`, etc) it would be very welcome to have the 'Reveal in Explorer' option.
