### ISSUE TITLE
VSCode takes increasing memory when using cmake to build a project

### ISSUE THREAD

**Issue by hzcheng** [microsoft/vscode-remote-release#1667]
Open a large project (I use a C project) with VSCode remote container, build the project with cmake. The built files are in the _build_ directory in the project folder. During compilation, the memory used by the _node_ service on container is getting larger and larger. If I detach the VSCode remote container, and build the project from a shell, it won't happen.

**Comment by roblourens** [comment]
Can you tell exactly which process is using the memory? Assuing you are using the C++ extension, if you disable it, does it stil happen?

**Comment by hzcheng** [comment]
It is the cmake plugin's problem. If I use cmake plugin to config, then build, this problem can happen. I think this issue should be in cmake plugin workspace.

**Comment by roblourens** [comment]
Please file it on their repo - thank you
