### ISSUE TITLE
Remote SSH does not pick up ConnectTimeout from config file.

### ISSUE THREAD

**Issue by abhaysac** [microsoft/vscode-remote-release#1668]
Issue Type: <b>Bug</b>

Some times the SSH server is slow to respond, and 15 second timeout is not enough. I tried adding ConnectTimeout to SSH config so that we wait longer for connection to go through. But vscode seems to ignore the config option and use some default value.

Extension version: 0.47.1
VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.16299

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/462
