### ISSUE TITLE
VSCode Devcontainer falls over on Windows 10

### ISSUE THREAD

**Issue by lifeiscontent** [microsoft/vscode-remote-release#1670]
About every 15 to 20 minutes I get a "Reconnecting to Container" Alert. This is a real pain in the *** for development.

**Comment by lifeiscontent** [comment]
@chuxel how do I do that? The reason I’m using a dev container is because I’m not familiar developing on windows (where I’m using the dev container)

**Comment by Chuxel** [comment]
@lifeiscontent This is all in VS Code.  When you are connected and see it happening:
1. Go to View => Terminal
2. Select the "Dev Container" terminal from the dropdown 
3. Copy and paste the entire contents of the terminal into a reply.

Are you doing something in particular when it happens? For example something CPU or memory intensive?  If so, you may want to try to give Docker more of your local capacity - it's only 2CPU, 2GB RAM by default on Windows.  To do so:

1. Right-click on the Docker task bar item and select Settings.
2. Go to Advanced and you can increase the number of CPU or Memory Docker consumes from there.

**Comment by lifeiscontent** [comment]
@Chuxel its happening a lot less since I boosted my CPU/Ram settings.

as an initial action item for this, if you want, it might be helpful to detect if docker is being used and give a tip to add additional CPU/Memory.
