### ISSUE TITLE
[bug] Remote WSL (2): Unable to use extension offline after terminating WSL instance

### ISSUE THREAD

**Issue by radu-matei** [microsoft/vscode-remote-release#1674]
Version: 1.40.0-insider (user setup)
Commit: 3f6ed25939b8ef157a7a41e0dc43b517898d4005
Date: 2019-10-15T05:26:38.861Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18999

Every time after terminating the WSL instance, VS Code tries to download the VS Code Server, even if the latest version is already present locally. It results in the extension being unusable when offline:

```
$ pwd
/home/radu/.vscode-server-insiders/bin
$ rm -rf *                                                                                    
zsh: sure you want to delete all 31 files in /home/radu/.vscode-server-insiders/bin [yn]? y
$ code-insiders .
Updating VS Code Server to version 3d3202804b4644f58cfac014e39b77dd36a6d226
Removing previous installation...
Downloading: 100%
Unpacking: 100%

# terminate WSL 2 instance and reopen, disconnect from network
# wsl.exe --terminate <your-distro>

$ code-insiders .
Updating VS Code Server to version 3f6ed25939b8ef157a7a41e0dc43b517898d4005
Removing previous installation...
Downloading:     Failed
--2019-10-15 09:49:47--  https://update.code.visualstudio.com/commit:3f6ed25939b8ef157a7a41e0dc43b517898d4005/server-linux-x64/insider
Resolving update.code.visualstudio.com (update.code.visualstudio.com)... 
wget: unable to resolve host address ‘update.code.visualstudio.com’
ERROR: Failed to download https://update.code.visualstudio.com/commit:3f6ed25939b8ef157a7a41e0dc43b517898d4005/server-linux-x64/insider to /home/radu/.vscode-server-insiders/bin/3f6ed25939b8ef157a7a41e0dc43b517898d4005-1571158177.tar.gz 
```

**Comment by aeschli** [comment]
`3d3202804b4644f58cfac014e39b77dd36a6d226` and `3f6ed25939b8ef157a7a41e0dc43b517898d4005 are really two different version from last week. New insider builds come our every day and sometimes, if we detect a major issue, there are even more builds on the same day, which was the case 6 days ago.

But agreed, this is not ideal for working offline. We have issue https://github.com/microsoft/vscode-remote-release/issues/1399 to make sure that when updating the client bits we also download the server bits.
