### ISSUE TITLE
The disk where the file is located loses read-write permission

### ISSUE THREAD

**Issue by Mr-YangJun** [microsoft/vscode-remote-release#1677]
Issue Type: <b>Bug</b>

If the speed of modifying files is too fast in the state of setting auto save, the disk where the files are located will lose the read-write permission. Only restart WSL can recover. If the frequency of modifying files is too fast in the mode of manual save, this problem will also be caused.

Extension version: 0.39.9
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18980
Remote OS version: Linux x64 4.19.67-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.67-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 2993)|
|Memory (System)|6.71GB (6.37GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Can you give some more details about exactly what you are doing and exactly what the problem is?
