### ISSUE TITLE
remote pdf cannot be viewed 

### ISSUE THREAD

**Issue by razhangwei** [microsoft/vscode-remote-release#1679]
Hi, 

After upgrading to version 1.39 or above, I found that the pdf file on remote hosts cannot be viewed properly. To reproduce, simply 
1. connect to a remote host
2. open an arbiturary pdf file, and the pdf can't be viewed. 

The issue was nonexistent if I downgrade to version 1.38 (e.g., 1.38.1); neither does it appear if the pdf file is in local. 

------
Extension version: 0.47.1
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 19.0.0
Remote OS version: Linux x64 3.10.0-1062.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: nebula-9|
|OS|Linux x64 3.10.0-1062.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz (24 x 2393)|
|Memory (System)|125.74GB (3.93GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Please give more details about exactly what you try to do and what happens.

**Comment by razhangwei** [comment]
Sorry, it was my first time reporting bugs. I've updated my original post.

**Comment by roblourens** [comment]
Thanks. This sounds like an issue with whatever extension you are using to view pdf files. Please file an issue on that extension's repo.
