### ISSUE TITLE
Vscode completely bricked

### ISSUE THREAD

**Issue by nicobrinkkemper** [microsoft/vscode-remote-release#1680]
- VSCode Version: 1,39,2 (latest build) and insiders build
- Local OS Version: 18999 (Fast Windows Insiders)
- Remote OS Version: Ubuntu 18.04 WSL 2
- Remote Extension/Connection Type: WSL 2

Steps to Reproduce:

1. Added some bash code to ~/.profile to add a certain ssh key on startup (and start ssh-agent)
2. Use for sometime. Close, open, close, restart, etc
3. Vscode renders unusable. No UI will render, only the background colors of vscode will render and that's it.
Like this:
![image](https://user-images.githubusercontent.com/1597349/66938925-566cf600-f042-11e9-8ba0-25dc6cdb82b0.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

My rigorous fix was to:
- undo any recent changes to WSL. (in my case it was adding ssh-agent code to ~/.profile)
- close and reopen a couple of times OR remove extension directory

**Comment by roblourens** [comment]
What exactly did you make to `.profile` that seemed to trigger this?

**Comment by roblourens** [comment]
Sounds related to https://github.com/microsoft/vscode/issues/82607?

**Comment by nicobrinkkemper** [comment]
It was something along the lines of:
```
eval `ssh-agent`
ssh-add some-rsa
```
btw I'm not 100% that was the issue but main vscode client started working right after. I remember that the Insider client kept that bricked state until 1 (maybe 2?) restarts later. Anyway they work now.

**Comment by roblourens** [comment]
If you start seeing it again, please start vscode with `code --verbose` and let us know what the output is.
