### ISSUE TITLE
Go To Definition says "No Definition for"

### ISSUE THREAD

**Issue by vecbib** [microsoft/vscode-remote-release#1682]
VSCode Version: code_1.39.2-1571154070_amd64
Local OS Version: Ubuntu 16.04 LTS
Remote OS Version: CentOS Linux release 7.6.1810
Remote Extension/Connection Type: Remote - SSH 0.47.1
Another Extension : Python ms-python.python
Steps to Reproduce:

Connect to remote machine with SSH extension
Open remote folder (My folder contains a python project)
Click on a symbol/function/define
Press F12
Nothing happens.

I expect to be sent to the file and location of the definition of the selected symbol.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by egamma** [comment]
@vecbib please file the issue against the python extension.
