### ISSUE TITLE
Remote-SSH commands do not work with large workspace open

### ISSUE THREAD

**Issue by bkonicek-cs** [microsoft/vscode-remote-release#1689]
This appears to be similar to issue #1687 but on the local side.

- VSCode Version: 1.39.2
- Local OS Version: Windows 10 1803
- Remote OS Version: CentOS 7
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open a workspace with a very large number of folders/files
2. Click the Remote Development "Open a remote window" button in the bottom left of the window.
3. Select "Remote-SSH: Connect to host..." or "Remote-SSH: Open configuration file" - the command window will close but nothing will happen.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No - when all extensions except for Remote Development are disabled this issue does not occur. However, it also does not occur with all extensions ENABLED, if I first close my workspace.

**Comment by roblourens** [comment]
So you open a local window with lots of folders first? Shouldn't matter, unless the extension host process is blocked by some local extension.

Is there any output in the Remote-SSH output channel?

**Comment by bkonicek-cs** [comment]
Yeah - it's definitely strange. It will even work if I open a new window and call it from there, leaving the one with all the folders open in the background. I've just updated it to 0.47.2 and it's still happening.

In "Log (Window)" I'm seeing this error
`[2019-10-24 13:14:49.742] [renderer5] [error] An unknown error occurred. Please consult the log for more details.`

In "Log (Extension Host)" I see the following events. These are exactly the same as the events I see in empty Workspaces when the extension does prompt me to select an SSH host:
```
[2019-10-24 13:14:49.435] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-ssh {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-ssh","_lower":"ms-vscode-remote.remote-ssh"},"activationEvent":"onCommand:opensshremotes.openEmptyWindow"}
[2019-10-24 13:14:49.435] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/bkonicek/.vscode/extensions/ms-vscode-remote.remote-ssh-0.47.2/out/extension
```

In the "Remote - SSH" output channel I see 
```
[13:14:49.681] remote-ssh@0.47.2
[13:14:49.681] win32 x64
[13:14:49.706] Picking SSH host
```

**Comment by roblourens** [comment]
Thanks for figuring out that the Terraform extension is somehow involved! It sounds like that extension is blocking the extension host, could you file an issue on their repo?
