### ISSUE TITLE
SSH Extension - consumes 100% host server CPU

### ISSUE THREAD

**Issue by dextersi** [microsoft/vscode-remote-release#1690]
In the new version, there is an integrated SSH connection option, before it was an extension. But now when I connect to SSH, it consumes 100% of CPU remote Linux server. Now, this option is useless.

Can you give me some solution?

![image](https://user-images.githubusercontent.com/1510872/67101266-98707600-f1c1-11e9-9d93-0fcc454b3a11.png)

**Comment by dextersi** [comment]
/home/USER/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/node /home/USER/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/home/USER/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/out/vs/server/uriTransformer.js

**Comment by roblourens** [comment]
That is the extension host which is running extensions. Can you try starting with the `--disable-extensions` flag so we can verify that an extension is doing this?

**Comment by dextersi** [comment]
Sorry, I don't understand what you mean. If I disable all the extensions(Remote - SSH) then I can's connect to remote SSH server. ?

![image](https://user-images.githubusercontent.com/1510872/67362139-b562cb80-f56a-11e9-996c-0b00d0f2cb74.png)

**Comment by dextersi** [comment]
I disable all the extension except "Remote - SSH". Nothing better, still 100% on remote server.

![image](https://user-images.githubusercontent.com/1510872/67362566-96b10480-f56b-11e9-82d9-ba60060f6bd7.png)

**Comment by roblourens** [comment]
@jrieken is it possible to profile the remote EH?

**Comment by jrieken** [comment]
If you can debug it then you can profile it - simply attach dev tools for nodejs. Tho, I don't know how/if the remote EH runs in debug mode. @alexandrudima will know

**Comment by roblourens** [comment]
I mean, I can do it manually. It would be helpful if users can also click a button the same way we profile the local EH. I assume it's possible but it doesn't look like it's hooked up for the remote EH.

**Comment by jrieken** [comment]
No have to do it manually - due to security concerns we won't be able to expose that to the outside world like that

**Comment by roblourens** [comment]
I don't think we need to expose the debug port to the world (although that isn't really sound different than exposing the remote agent to the world) but maybe the remote agent could profile the remote EH, then the EH can transfer the profile to the frontend.

**Comment by ceyhunkerti** [comment]
Facing the same issue

Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-66-generic

**Comment by roblourens** [comment]
Are either of you opening a large folder with lots of files? I think this is just the same as https://github.com/microsoft/vscode-remote-release/issues/1687 and https://github.com/microsoft/vscode-remote-release/issues/1257

**Comment by ceyhunkerti** [comment]
no not a large dir. and cat see the relation to above two issues

**Comment by cesarlee** [comment]
I have the same issue.  VSCode remote-ssh is using all 8 cores at 100% on AWS Ubuntu server.  I tried removing the extension and re-installing, same problem.  Also tried the nightly build and same process.  

Besides disabling other extensions, etc., I can clearly pin this down on VSCode with:

ps -eo pcpu,pid,user,args | sort -k1 -r -n | head -10

10.8 16947 ubuntu   /home/ubuntu/.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729/node --max-old-space-size=3072 /home/ubuntu/.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-typescript1000/fe048e066991c9d0e5d4/tscancellation-0714935b774f42fc6806.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
 
Pretty much every line except in the prior command points to VS Code.  VS Code seems to be running a dozen or so processes which are taking up all available CPU's at 100%.

Also, when I close VS Code, everything goes away and CPU's go back down to zero.

**Comment by roblourens** [comment]
@cesarlee not the same issue, that is the tsserver process, you can open an issue on https://github.com/microsoft/vscode with the same info.

**Comment by libbkmz** [comment]
After upgrading to 1.42 I faced the same issues with 
/home/bkmz/.vscode-server/bin/ae08d5460b5a45169385ff3fd44208f431992451/node /home/bkmz/.vscode-server/bin/ae08d5460b5a45169385ff3fd44208f431992451/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/home/bkmz/.vscode-server/bin/ae08d5460b5a45169385ff3fd44208f431992451/out/vs/server/uriTransformer.js

If I disable all extensions, obviously this process is no longer exists. After installing only one extenion Remote - WSL my laptop is trying to heat the whole room.... Not a good way of using laptop on battery...
