### ISSUE TITLE
Permissions error attaching to running container with non-root default user

### ISSUE THREAD

**Issue by forrcaho** [microsoft/vscode-remote-release#1692]
Version: 1.40.0-insider
Commit: 5aec74ad3b55bb9463e717ec950e665288accd0f
Date: 2019-10-18T05:32:01.162Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

- Remote Extension/Connection Type: Docker

I have a docker container with a non-root default user. I didn't write the script to spin up this container, and it's sort of complex, but from the error message given and the workaround I found I think the key is simply that the default user is not root.

When I try to attach to my running container, I see these messages, ending in a permissions error:
```
Setting up container with ceb466c924fba5d76a0179831b0377e4994fb2d7a452855e8fd07d3ce093883c
Run: docker exec ceb466c924fba5d76a0179831b0377e4994fb2d7a452855e8fd07d3ce093883c /bin/sh -c (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
Run: docker cp ceb466c924fba5d76a0179831b0377e4994fb2d7a452855e8fd07d3ce093883c:/etc/passwd -
Run: docker exec ceb466c924fba5d76a0179831b0377e4994fb2d7a452855e8fd07d3ce093883c test -d /root/.vscode-server-insiders
Run: docker exec ceb466c924fba5d76a0179831b0377e4994fb2d7a452855e8fd07d3ce093883c test -d /root/.vscode-remote
Run: docker exec ceb466c924fba5d76a0179831b0377e4994fb2d7a452855e8fd07d3ce093883c test -d /root/.vscode-server-insiders/bin/5aec74ad3b55bb9463e717ec950e665288accd0f
Installing VS Code Server for commit 5aec74ad3b55bb9463e717ec950e665288accd0f
Run: docker exec ceb466c924fba5d76a0179831b0377e4994fb2d7a452855e8fd07d3ce093883c mkdir -p /root/.vscode-server-insiders/bin/5aec74ad3b55bb9463e717ec950e665288accd0f_1571431762786
mkdir: cannot create directory ‘/root’: Permission denied
Command failed: docker exec ceb466c924fba5d76a0179831b0377e4994fb2d7a452855e8fd07d3ce093883c mkdir -p /root/.vscode-server-insiders/bin/5aec74ad3b55bb9463e717ec950e665288accd0f_1571431762786
```

The default user's home directory is not `/root` (it's actually `/tmp`). The above commands are trying to write to `/root` as the default user which of course fails.

The workaround is to get a root shell into the container and chown `/root` to the default user. After that I can attach to the container successfully. That's obviously an ugly hack which I don't want to use.

I don't understand why vscode is not using the HOME env var to find the correct dir to write into.

Sorry if this is a duplicate; I found many similar issues, but none quite the same as mine.

**Comment by chrmarti** [comment]
What's the user's home dir in `/etc/passwd`? And what's the HOME environment variable's value in `docker inspect <container id>`?

**Comment by forrcaho** [comment]
User's home dir in `/etc/passwd` is `/home/zz` (user is `zz`). This dir exists but it's owned by root, which seems like a misconfiguration.

No HOME is set in the info dumped by `docker inspect`.

**Comment by chrmarti** [comment]
We read and parse `/etc/passwd`, could you attach its contents? And what do you get for `docker exec <container id> pwd`?

Does changing the ower of `/home/devuser` to `devuser` fix the issue?

**Comment by forrcaho** [comment]
I'm currently working on a "clean" docker instance that will reproduce the issue without revealing any of my organization's internal workings I'm dubious about sharing. This will probably take me a few days. If you want to close the ticket, I can open a new one when I have something clean to share.

**Comment by chrmarti** [comment]
Sounds good, thanks!
