### ISSUE TITLE
Strange behavior of replacing port number in URL  

### ISSUE THREAD

**Issue by antimora** [microsoft/vscode-remote-release#1693]
- VSCode Version: 1.39.2
- Local OS Version: Linux future 5.0.0-31-generic # 33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Remote OS Version: Linux 0bc5a37396a9 5.0.0-31-generic # 33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1. Launch vscode in remote container locally.
2. Run jupyter notebook --ip=0.0.0.0
3. Mouse over the URL and CTRL + Click to follow the link.

Problem: Instead of opening the URL with Jupyter's 8888 port, a random port is injected into URL. The browser correctly renders the page but when you open a notebook, the kernel icon goes into infinite spin. It took a while to figure out the wrong port was causing the issue. Initially I assumed, Jupyter itself was redirecting to a different port. However, when I copied and pasted the original URL, the behavior was normal. I traced a node process that was listening on that port and it appears code launches a proxy to redirect HTTP traffic. 

I think this auto-magic behavior of exposing ports should be made more explicitly and there should be a way to control it. 

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

```
[I 07:18:45.605 NotebookApp] The Jupyter Notebook is running at:
[I 07:18:45.605 NotebookApp] http://hostname:8888/?token=d5465baf3bb08350d4d463b7e7190d233d645e459c04edcf
[I 07:18:45.605 NotebookApp]  or http://127.0.0.1:8888/?token=d5465baf3bb08350d4d463b7e7190d233d645e459c04edcf
[I 07:18:45.605 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

**Comment by Marshal27** [comment]
I have a similar issue with Angular CLI projects and the hyper link opening on port 3001 instead of 3000... would be nice to control this behavior and or turn it off.

**Comment by Marshal27** [comment]
This appears to have been resolved (for me at least) on VS Code v1.53.0

**Comment by mjbvz** [comment]
@antimora Can you also please test using VS Code 1.53 to see if this has been fixed?

**Comment by antimora** [comment]
@mjbvz I don't have access to my desktop machine which has the correct setup. So I cannot confirm if this has been fixed. If others are telling this problem has been fixed, then you can close it. I can check later again. 

It would be nice to link to an actual code commit that fixes this issue.

**Comment by mjbvz** [comment]
Closing since others are reporting it as resolved

@antimora There is no commit because we never checked in code to specifically fix this issue. It is was fixed, it was likely incidentally fixed by another change
