### ISSUE TITLE
fail to switch uppercase/lowercase when renaming a file

### ISSUE THREAD

**Issue by NeeXxx** [microsoft/vscode-remote-release#1697]
- VSCode Version: 1.39.2
- Local OS Version: Windows10 18362.418
- Remote OS Version: Ubuntu 18.04.2 LTS
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. connect to WSL, and open a folder
2. rename a file, only switch one or more of its characters to uppercase/lowercase.(for example: `Node.py` to `node.py`; `plot.py` to `PLOT.py`)
3. the filename remains the same

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/12448
