### ISSUE TITLE
Specify remote alternative to /tmp

### ISSUE THREAD

**Issue by TheStoof** [microsoft/vscode-remote-release#17]
Some remote machines have /tmp mounted with **noexec**. Offering an alternative for the end-user to specify a directory such as their own home directory would allow end-users to use this feature w/o needing to remount /tmp

**Comment by seeken** [comment]
using TMPDIR env in .bashrc works

**Comment by TheStoof** [comment]
Confirmed. It is a temporary solution, but I think in most cases general users don’t need to use /tmp. Thanks!

**Comment by roblourens** [comment]
This is fixed in the new "nightly" build of the ssh extension, would appreciate people trying it to let me know if there's still an issue: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly (uninstall the stable version too)
