### ISSUE TITLE
[WSL]: `code .` better error when 'cmd.exe' is not on the path

### ISSUE THREAD

**Issue by andreialecu** [microsoft/vscode-remote-release#170]
Issue Type: <b>Bug</b>

Running:

`"/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders" .`

This is printed in the console before Code starts, it's a message that I'm not seeing in stable Code:

`/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders: line 29: cmd.exe: command not found`

Code Insiders will open, but the project will be opened from the Windows path (`X:\dir\dir`, instead of `/x/dir/dir`), without Remote-WSL.

This is likely to break various tooling and workflows relying on the command line.

VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.17763

**Comment by andreialecu** [comment]
Thanks for taking note of this.

From what I can see, the `cmd.exe` call is just used to run the sibling `code-insiders.cmd` in the same directory as the `code-insiders` bash script. The `.cmd` file doesn't look particularly complicated. 

Wouldn't it be better to just drop the `cmd.exe` call altogether and include the code from the `.cmd` natively in the main bash script?

I feel cmd.exe won't be on the PATH for a lot of people, and it seems like it could be fixed outright, rather than just reported to the user that he needs to take additional action.

**Comment by alexr00** [comment]
I removed /mnt/c/WINDOWS/system32 from my WSL path then:
```
$ code .
/mnt/c/Users/alros/.vscode/extensions/ms-vscode-remote.remote-wsl-0.36.0/scripts/wslCode.sh: line 12: wsl.exe: command not found
Visual Studio Code for WSL currently only supports the default distro. Use 'wslconfig.exe' to configure the default distro.
```
That message doesn't explain that the path is missing something.

**Comment by alexr00** [comment]
Now I'm getting an exception:
```
alros@ALROS-1:/mnt/c/Users/alros/Documents/empty1$ code-insiders .
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by aeschli** [comment]
fixed by https://github.com/microsoft/vscode/commit/49b51b32b2a9c32f34c00746c2013dbde86d1ef3

**Comment by weinand** [comment]
After removing `/mnt/c/WINDOWS/system32` from the WSL PATH, "code-insiders" starts up fine, but the following message shows up in the terminal: 
```
wsl.exe not found on PATH, unable to probe wheter this is the default distro
```
IMO the message is self-explanatory (but contains a typo).
