### ISSUE TITLE
[wsl] inherit environment from process where `code .` is executed

### ISSUE THREAD

**Issue by edburns** [microsoft/vscode-remote-release#1700]
I observe that environment variables that are sourced at the command
line between opening the WSL shell, and starting `code .` appear to not
be inherited, and therefore are not available when VS Code needs them.
For example, the Java extensions for VS Code need java and maven to be
in the path.

Stack: Windows 10, WSL, VS Code (insiders from 2019-10-15) with WSL and Java Extensions

Preconditions: verify that VS Code correctly connects to WSL by
observing the WSL: Ubuntu in the status bar.

Steps to reproduce.

1. Open an Ubuntu WSL shell and verify that the following environment
   variables are not set:
   
   ```
   export JAVA_HOME="${HOME}/edburns/Downloads/jdk-11.0.3"
   export ANT_HOME=${HOME}/edburns/Downloads/apache-ant-1.10.6
   export M2_HOME=${HOME}/edburns/Downloads/apache-maven-3.6.1
   ```

   verify PATH does not have JAVA_HOME, ANT_HOME, or M2_HOME in it.
   
2. Make a script containing the following, say `env-java11`

   ```
   export JAVA_HOME="${HOME}/edburns/Downloads/jdk-11.0.3"
   export ANT_HOME=${HOME}/edburns/Downloads/apache-ant-1.10.6
   export M2_HOME=${HOME}/edburns/Downloads/apache-maven-3.6.1
   export PATH=${M2_HOME}/bin:${ANT_HOME}/bin:${JAVA_HOME}/bin:${PATH}
   ```
3. Source the script in the Ubuntu WSL shell.

   ```
   . ./env-java11
   ```
   
4. Start VS Code `code .`

5. Open a bash shell in VS Code

6. Echo the variables and see they are not defined.

Workaround

If you source the environment variables directly from the `~/.bashrc`
you will find the variables are inherited correctly.

If you are internal to Microsoft, I have a video of the problem at 
https://msit.microsoftstream.com/video/cbe42ed7-e766-431f-abfc-2c5e818653e5

**Comment by aeschli** [comment]
Yes, that's how it currently is structured. `code .` starts VS Code on the Windows side which starts a new WSL process for the server.
You need to define your environment in your shell startup scripts, as you have observed.

**Comment by impguard** [comment]
Is there a workaround for this besides storing things in .bashrc? I'm ok with having to setup a visual studio specific bashrc (some launch file?)

Not sure if a workspace specific or language specific "launch script" is something visual studio can already do.

**Comment by aeschli** [comment]
You can try this: https://code.visualstudio.com/docs/remote/wsl#_advanced-environment-setup-script

**Comment by impguard** [comment]
Thanks for the suggestion. Unfortunately, seems like adding some env vars in this script doesn't get picked up. I don't have a good understanding on what the WSL server process is doing, but it doesn't seem like setting vars then propagates properly. VSCode still complains about not being to find things that it should find if it had the environment variables that I set before typing "code .".

Specifically, my gopath is setup with tools like goenv, which is dynamic to the folder. Unfortunately, VSCode can't see the GOPATH environment variable, so I have to manually point a workspace at that gopath for now.

**Comment by JP-sngy** [comment]
what you can do is modify the `~/.bashrc` file to export a new $PATH. Though the standard is to place your export scripts in the `~/.profile` file, this will not be picked up by the WSL remote module in VSCode so it has to be in `~/.bashrc`. You might be able to find a better alternative though...
For now this is how mine is set up. Chao

**Comment by vogler** [comment]
This is unfortunate since it breaks [opam's local switches](https://opam.ocaml.org/blog/opam-local-switches/) which set the environment depending on the current directory.
I can set tool-specific paths in the workspace settings, but then I can't commit settings since those paths depend on where you checkout the project.

**Comment by chrisjaquet** [comment]
Our workflow also uses a process where for a certain workspace (dev environment) we set up environment variables specific to that workspace (via a script), so having the ability to inherit the environment would be convenient, mainly because we use vscode via WSL to debug build issues and need to be able to run the build tools (which depend on the environment vars) to get the correct output.

We currently work around this by manually running the script in the vscode terminal and building only from there.

**Comment by spottedmahn** [comment]
Another workaround: [Share Environment Vars between WSL and Windows](https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/).  I added [a few USER ENV Variables in Windows](https://spottedmahn.wordpress.com/2020/01/15/fix-java-test-runner-not-seeing-wsl-environment-variables/) and then added them to the `WSLENV` variable in a : separated list.

_Note:_ I had to close all instances in VS Code instances before it picked up the env variables.

**Comment by spottedmahn** [comment]
Hi @aeschli - I got this alert via email:

>Closed #1700 via 3cb1826639519b40479df17efe5328c921b3ae42

but I don't see the link to the commit on GitHub 🤔

**Comment by aeschli** [comment]
The source code of the WSL extension is not public, that's why you don't get a link.

I will publish a new version of extension in the coming days for you try it out.

**Comment by spottedmahn** [comment]
>The source code of the WSL extension is not public, that's why you don't get a link.

Gotcha, thanks for clearing that up for me!
