### ISSUE TITLE
Windows 10 18980 ssh-keygen wrong directory

### ISSUE THREAD

**Issue by positivedefinite** [microsoft/vscode-remote-release#1702]
When trying to set up VSCode remote by following:
https://code.visualstudio.com/docs/remote/ssh
I generate a key through PowerShell.

![image](https://user-images.githubusercontent.com/22936927/67272071-197a8680-f4bc-11e9-934f-4a67dcf7343c.png)

However, the gey is generated in 
C:\Users\my_user 
rather than in C:\Users\my_user\.ssh as the PowerShell says

At least the docs should be updated

**Comment by roblourens** [comment]
Please file an issue here: https://github.com/PowerShell/Win32-OpenSSH/issues, I can't reproduce it
