### ISSUE TITLE
Using remote containers on ARMv64 (Jetson Nano) fails (wrongly installs vscode-server-linux-64)

### ISSUE THREAD

**Issue by hlacik** [microsoft/vscode-remote-release#1716]
- VSCode Version: 1.40.0-insider
- OS Version: Linux pop-os 5.3.0-19-generic (local host), Linux jetson 4.9.140-tegra (remote host, running containers)

Steps to Reproduce:

1. Create local devcontainer.json
{
	"image": "ubuntu",
	"workspaceFolder": "/pcrdev",
	"workspaceMount": "src=pcrdev,dst=/pcrdev,type=volume,volume-driver=local"
  }

2. Launch Remote-Containers Open Folder in Containers

3. Wait during Installing Dev Container, Copying VSCode Server to container

Wrong extension architecture is installed (x64 instead of ARMv64) 

4. Error Occures - Visual Studio Code - Insiders An Error ocurred setting up the container.

![Screenshot from 2019-10-23 17-13-16](https://user-images.githubusercontent.com/7456938/67407894-752a3a00-f5b8-11e9-8ffe-e483e3c745a1.png)

However when  using Just Remote SSH  Development, correct version of vscode-server is installed (ARMv64) so this bug is valid only for remote containers on ARMv64

**Comment by hlacik** [comment]
Excuse me but why is this a feature request and not a bug? For sure it is possible to do remote development (SSH) with VSCODE INSIDERS on arm64 architecture, therefore same version vscode remote development could be deployed inside container. Therefore its just a matter of install script during development container deployment.

**Comment by chrmarti** [comment]
Adding support for ARM64 in Insiders and ARM32 in general.

**Comment by chrmarti** [comment]
Verification using emulators:
```
docker run --rm --privileged hypriot/qemu-register
docker run -d arm32v7/ubuntu sleep infinity
docker run -d arm64v8/ubuntu sleep infinity
```

Then attach to the two containers with Remote-Containers.

**Comment by chrmarti** [comment]
ARM64 will be enabled in the next VS Code stable release too.

**Comment by hlacik** [comment]
using docker run -it --rm --gpus all arm64v8/ubuntu

then attaching vscode insider 1.41.0 to this container results in error :
[1138 ms] /root/.vscode-server-insiders/bin/7cf4cca47aa025a590fc939af54932042302be63/server.sh: 12: /root/.vscode-server-insiders/bin/7cf4cca47aa025a590fc939af54932042302be63/server.sh: /root/.vscode-server-insiders/bin/7cf4cca47aa025a590fc939af54932042302be63/node: Exec format error
[1212 ms] Command failed: docker exec -w /root/.vscode-server-insiders/bin/7cf4cca47aa025a590fc939af54932042302be63 -u root -e SHELL=/bin/bash -e VSCODE_AGENT_FOLDER=/root/.vscode-server-insiders bbd4deeea942f7e33682cb80b1a6e31b503c4f69b6c6e4726c39b7453a5a3fcb /root/.vscode-server-insiders/bin/7cf4cca47aa025a590fc939af54932042302be63/server.sh --disable-user-env-probe --port 0

**Comment by chrmarti** [comment]
@hlacik Please check you are running the latest version of the extension (currently 0.86.0).

Maybe you attached to the same container with an earlier version of the extension. If so, try deleting the `/root/.vscode-server-insiders` folder in the container (or use a new container) and attach again.

**Comment by hlacik** [comment]
> @hlacik Please check you are running the latest version of the extension (currently 0.86.0).
> 
> Maybe you attached to the same container with an earlier version of the extension. If so, try deleting the `/root/.vscode-server-insiders` folder in the container (or use a new container) and attach again.

Oh, so after TODAY insider update 1.41.0-1575351432 it finally works , your awesome guys, right on time, I have one week before project delivery (running on nvidia jetson nano) and I can finally remote debug inside containers running there.

**Comment by alexr00** [comment]
Looks like this is verified by the original issue filer!
