### ISSUE TITLE
Feature: .devcontainer for vscode repo 

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/vscode-remote-release#1717]
Lets create .devcontainer for this repo to speed up vscode development

we will bind mount from linux the xauthority and for mac we will use nut and the xserver for mac

- Todo: find a xserver for windows that we could maybe bind mount and use else use vnc

**Comment by bhack** [comment]
Have we a dep here over microsoft/vscode-remote-release#2067?

**Comment by bhack** [comment]
Check also https://github.com/mviereck/x11docker/wiki/x11docker-on-MS-Windows
https://github.com/mviereck/x11docker/

**Comment by egamma** [comment]
Closing - a devcontainer configuration has been added.
