### ISSUE TITLE
Saving file slow

### ISSUE THREAD

**Issue by JavaCS3** [microsoft/vscode-remote-release#172]
Issue Type: <b>Performance Issue</b>

Sometimes file saving is slow

Extension version: 0.35.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:21:48.884Z)
OS version: Darwin x64 16.7.0
Remote OS version: Linux x64 4.18.0-17-generic
Fetching remote diagnostics for 'ssh-remote+10.74.133.173' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.74.133.172|
|OS|Linux x64 4.18.0-17-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz (8 x 2800)|
|Memory (System)|15.64GB (1.28GB free)|
|VM|33%|

Fetching remote diagnostics for 'ssh-remote+10.74.133.173' timed out.
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   21	   115	  9726	code-insiders main
    6	   147	  9729	   gpu-process
    0	    66	  9827	   shared-process
    0	   410	 19202	   window (build.py — novum-os [SSH: 10.74.133.172])
    0	   131	 19219	     extensionHost
    0	     0	 77525	       ssh 10.74.133.172 -N -L localhost:30577:localhost:43141
    0	    49	 81448	     searchService
    0	   147	 24878	   window (Welcome — lab [SSH: 10.74.133.173])
    3	    82	 83903	   window (Issue Reporter)
    0	     0	 84400	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
Fetching remote diagnostics for 'SSH: 10.74.133.172' failed: Command failed: "/home/*****/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/out/vs/base/node/cpuUsage.sh" 91842

Fetching remote diagnostics for 'ssh-remote+10.74.133.173' timed out.
```

</details>
<details>
<summary>Workspace Info</summary>

```

Fetching remote diagnostics for 'SSH: 10.74.133.172' failed: Command failed: "/home/******/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/out/vs/base/node/cpuUsage.sh" 91842

Fetching remote diagnostics for 'ssh-remote+10.74.133.173' timed out.;
```

</details>

**Comment by roblourens** [comment]
Can you explain exactly what you are seeing? How slow is it? Is everything slow (opening files, search etc?)

**Comment by bhack** [comment]
Are these new Process Info reports disclosing target host. Is it a secure policy?

**Comment by JavaCS3** [comment]
@roblourens When there're many ongoing tasks, if you save a file the at this time. The file will be wrote to remote disk after a few seconds

**Comment by JavaCS3** [comment]
@bhack We do have networking secure policy in my company. But I don't know if it's related to this. Usually we need to access public HTTPs server via a proxy

**Comment by roblourens** [comment]
What sort of "task" do you mean?

Is everything slow (opening files, search etc?)

**Comment by bhack** [comment]
@JavaCS3 My comment was target to @roblourens

**Comment by JavaCS3** [comment]
> What sort of "task" do you mean?
> 
> Is everything slow (opening files, search etc?)

Like: language server is parsing some files or installing some plugins and then u modified something and save it. I was cause longer time than it use to be.

**Comment by achamayou** [comment]
I'm seeing this as well, in the form of the little gray disk (indicating an unsaved file), staying on the tab for sometimes several seconds, and up to minutes in some cases. It is unusual, the vast majority of the saves are instant, but quite frustrating when it happens.

**Comment by JavaCS3** [comment]
> I'm seeing this as well, in the form of the little gray disk (indicating an unsaved file), staying on the tab for sometimes several seconds, and up to minutes in some cases. It is unusual, the vast majority of the saves are instant, but quite frustrating when it happens.

Exactly

**Comment by catbadger** [comment]
Seeing this quite often in Ubuntu 18.04. Over ssh connections where I open the ssh connection in nautilus and right click to open a project folder with vscode, saving sometimes takes several minutes. I can confirm that other editors do not have this delay.

**Comment by achamayou** [comment]
So for what it’s worth, this used to happen frequently when editing files on an Azure OS Disk. Editing files on a data disk instead does not exhibit this problem, so I’m doing that instead now.

**Comment by roblourens** [comment]
Interesting @achamayou, what size is your VM? The OS disk is throttled based on the size of the VM. I still wouldn't expect it to be _that_ slow but maybe with some other processes using the disk at the same time...

**Comment by achamayou** [comment]
@roblourens it’s a DC4s, I didn’t realise the disk was throttled. What’s odd about it is that it’s generally fine, with the occasional extreme outlier (ie. the file staying unsaved for several seconds).

I am unable to reproduce this on the data disk though, so it must either be the OS disk or an interaction between it and something in the saving behaviour.

**Comment by roblourens** [comment]
@JavaCS3 is that the case for you too? Are you using the OS disk of an Azure VM?

**Comment by JavaCS3** [comment]
> @JavaCS3 is that the case for you too? Are you using the OS disk of an Azure VM?

No, It's a Vmware VM owned by my company.

**Comment by niranjantdesai** [comment]
I'm facing this problem intermittently too. I'm on Mac OS ssh'ing into my Ubuntu 14.04 workstation.

**Comment by JavaCS3** [comment]
I don't see this issue too often now. Maybe it's related to networking.

**Comment by wi-ski** [comment]
✋ Similar stuff here. Im curious if its Mac's file system events and them... not existing.

**Comment by vikicoder007** [comment]
Its working slow in windows as well. Files are opening too slow around 20-30 seconds even if file is empty and also saving slow too.

**Comment by regiscamimura** [comment]
Same here on a Mac

**Comment by chazeon** [comment]
I have the same issue here on a Mac, connecting to an HPC with SSH connections.

I am working on a large directory with a lots of files. After working for a while VSCode save file would suffer from a serious lag, saving a Python script with ~150 lines of code would take 30s to 1min. During this saving, if I carelessly run the script on the server via another SSH window/terminal, the Python interpreter would be stuck there, cannot run, also cannot be interrupted or killed. I am not seeing any task with high CPU usage. If I interrupt the python interpreter, it will only be interrupted after the saving process was finished.

Reload the window would solve this problem for me, but it is really annoying.

**Comment by gopalrs** [comment]
I can repro the same issue with VS Code version 1.45 on Windows, while ssh-ing to a Ubuntu 18.04 VM. Saving a C++ file takes 1-2 minutes! The performance is simply horrendous. Any suggestions/work arounds?

**Comment by roblourens** [comment]
Is this still an issue? Besides a slow disk this could also be extensions doing something on save (like formatting) and being very slow. Do you have any extensions that you can disable to check?
