### ISSUE TITLE
SSH: Provide option to execute commands before starting vscode-server

### ISSUE THREAD

**Issue by mill1000** [microsoft/vscode-remote-release#1723]
It would be great if SSH Remote offered the ability to run commands/a script before attempting to start the remote server. In some cases it may be beneficial to customize the environment the server is attempting to run in.

e.g. For me, trying to run in CentOS 6 with updated libstdc++ and glibc in my home directory I had to modify the extension source to update LD_LIBRARY_PATH before the `server.sh` script is called.

**Comment by wwarriner** [comment]
Thank you for posting this! I believe it would help solve my issues in #1722 as well.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/141
