### ISSUE TITLE
Long path issue when unzipping Windows host server

### ISSUE THREAD

**Issue by MatisseHack** [microsoft/vscode-remote-release#1724]
- VSCode Version: 1.40.0-insider
- Local OS Version: macOS 10.14.6
- Remote OS Version: Windows 10 1903
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Enable Windows remotes with `remote.SSH.windowsRemotes`
1. Connect to the Windows host via SSH
1. VS Code will hang while trying to set up the host server

On my machine, `server-win32-x64.zip` cannot be extracted to `$env:TEMP/vscode-server-b53811e67e65c6a564a80e1c412ca2b13de02907` because the path is too long. The log will be filled with (seemingly unrelated) errors like:

```
Cannot find path 'C:\Users\USERNAME\AppData\Local\Temp\vscode-server-b53811e67e65c6a564a80e1c412ca2b13de02907\vscode-server-win32-x64\some\long\path' because it does not exist.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:411 char:46
+ ...                 $expandedItems | % { Remove-Item $_ -Force -Recurse }
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\USERNA...test\clobber.js:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
```

Everything works fine after manually extracting `server-win32-x64.zip` to a shorter path (`$env:USERPROFILE\.vscode-server-insiders\bin\b53811e67e65c6a564a80e1c412ca2b13de02907`) and reconnecting to the host.

**Comment by roblourens** [comment]
:(

Do you have a very long username? Otherwise it looks like we are very close to the path limit even at `$env:USERPROFILE\.vscode-server-insiders\bin\b53811e67e65c6a564a80e1c412ca2b13de02907`

**Comment by MatisseHack** [comment]
My username is 17 characters. Probably longer than most, but not beyond reason. Yeah, I only just squeaked by with that _(slightly)_ shorter path.
