### ISSUE TITLE
Remote Containers over Remote SSH

### ISSUE THREAD

**Issue by wasserman** [microsoft/vscode-remote-release#1725]
I develop on Windows using the "Remote - SSH" extension to work on a remote Linux environment.  This works great and I love this feature.  I also run containers on this remote host which I use in my development workflow and would love to attach to the container similar to the "Remote - Containers" extension.  The problem is that even with port forwarding of 2375 doesn't work without some Docker locally installed on Windows.

It'd be great if I could just attach to these remote containers leveraging the Docker software on this remote host.  Basically install the "Remote - Containers" in the context of this "Remote - SSH" target host environment.

**Comment by roblourens** [comment]
Are you able to create an ssh connection to the docker container? Can you explain some more about what doesn't work and why you need:

> install the "Remote - Containers" in the context of this "Remote - SSH" target host environment.

If you can ssh into the container then you should be able to use the SSH extension with that setup.

**Comment by wasserman** [comment]
From the user perspective I want the Docker integration to work in VSCode when the environment is connected to a Remote SSH, interfacing with Docker from the perspective of this remote host.  So if I'm on Windows connected via "SSH: My-Linux-Host" I'd want the "Remote - Containers" extension to be installed on My-Linux-Host and then attaching to a container would be via this remote connection.  It is confusing to me when VSCode is in this remote SSH context yet some features are still behaving like it is connecting from the host that the VSCode UI is running on.

My workflow now is I use the "Terminal" to access the remote host I'm coding on via VSCode and do a tar, docker cp, etc. to sync my changes to the container.  The container originates from docker-hub and is from a Vendor, so being able to destroy and rebuild it without extra requirements would be nice.   I haven't tried to ssh directly to the container since it doesn't have ssh running and I didn't want to jump through extra configuration hoops.  

If I'm working on non-Windows and run Docker directly on the same workstation as VSCode then the Docker "remote" capabilities work well for me.  Windows just complicates this process.  But this request would support other non-Windows scenarios since connecting to a Docker host in AWS or somewhere else would be a similar scenario.
