### ISSUE TITLE
High CPU usage on client end - orphan shutdownProcessMonitor process

### ISSUE THREAD

**Issue by fsackur** [microsoft/vscode-remote-release#1727]
This typically happens once a day or so.

- VSCode Version: 1.39.2 or 1.40.0-insiders (tried both)
- Local OS Version: Win10 1903 (10.0.18362.0)
- Remote OS Version: CentOS 7
- Remote Extension/Connection Type: Container on remote host; access to docker through TCP port forwarded over SSH

Steps to Reproduce:

1. Be running Windows 10 on the desktop
2. Run a dev container on remote CentOS 7 docker host with docker port forwarded over SSH
3. Wait for Code to show "Reconnecting", e.g. because SSH disconnected briefly
4. CPU usage goes up by ~25%
5. Close all visible code windows
6. One process remains, with command `"C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\Code.exe" c:\Users\<username>\.vscode\extensions\ms-vscode-remote.remote-containers-0.81.0\dist\shutdownMonitorProcess \\.\pipe\vscode-remote-containers-dff5f1a56b3805b1be73531b1c096dda476f34d1 -sock si`. That process is consuming 25% CPU on a box with 4 logical cores.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A but does happen with only Python extension in remote

**Comment by chrmarti** [comment]
Are there any other VS Code processes around still when that happens?

**Comment by JohnGalt1717** [comment]
Yes there are.

**Comment by chrmarti** [comment]
Could you enable tracing (`F1` > `Developer: Set Log Level...` > `Trace`) and then reload the window to activate it everywhere. When the problem occurs again, check what is in the `%USERPROFILE%\.vscode\extensions\ms-vscode-remote.remote-containers-0.83.0\dist\shutdownMonitor.log`.

**Comment by JohnGalt1717** [comment]
Why was this closed? I was on vacation and just getting back to stuff.

**Comment by chrmarti** [comment]
It is fixed in the next release.

**Comment by JohnGalt1717** [comment]
OK, started up dev container, waited about 10 minutes and vmmem started taking way more memory and went from 2/3% cpu to 20%.  Even after doing the F1 developer set log level = trace there's no .log file created. Just a .js file of the same name. (I checked after the restart and trace is set to current)

One oddity, don't know if it's related but every time I start up the container Omnisharp downloads and reloads all of the packages for C# dev.

Based on what the cpu usage is doing on vmmem I'd guess this was file monitoring? Because even when it's not using an entire CPU while at idle (20% is one of my CPUs) it's still 2-5% all of the time when it should basically be 0.

**Comment by JohnGalt1717** [comment]
@chrmarti Ah, sorry, just saw your comment after I finished debugging.

**Comment by fsackur** [comment]
@JohnGalt1717 You piggy-backed on 1728, and now this, to describe an issue with vmmem. You may _also_ have the issue described here, but I logged this for something other than whatever is bothering you. Could you kindly log your own issue?

Completely separate note: you might not realise how unfavourably your username comes across. "John Galt" is NOT a good look.

**Comment by JohnGalt1717** [comment]
@fsackur 1. I didn't piggy back on anything. It's all related to the same issue.

2. To the people that I care about the user name comes across very favorably. To those that don't like it, I say "Good. You're the type of person I despise and you've outed yourself."

**Comment by roblourens** [comment]
Need verification steps, or could someone who saw this issue confirm that it is now fixed?

**Comment by fsackur** [comment]
@roblourens my apologies, I confirm the fix. From memory I believe it was 1.40.2 that fixed it but not sure.

**Comment by dbaeumer** [comment]
@fsackur thanks for getting back. Marking as verified then.
