### ISSUE TITLE
Share Git user.name and user.email to containers

### ISSUE THREAD

**Issue by JohnGalt1717** [microsoft/vscode-remote-release#1729]
Every time we rebuild a container we have to reset these options.

It would be really nice if vs code would pick up the .git local project settings for this and if that isn't set, pick up the ones from global and pass them in as the appropriate environment variables.

**Comment by chrmarti** [comment]
If you use a devcontainer.json we already copy the user's `.gitconfig` to the container. Does that not work? (If you attach to a container, there is a fix in the next release that makes this work for that case too.)

**Comment by JohnGalt1717** [comment]
Problem is that if you set it globally it doesn't seem to pass the environment variables or anything to the containers. If you set them locally to the repo then it works fine.

**Comment by chrmarti** [comment]
Could you elaborate? Which environment variables? By 'globally' you mean the user's .gitconfig?

**Comment by JohnGalt1717** [comment]
git config --global user.email "MY_NAME@example.com"

These should be passed into the container somehow so that they work if they're not set in the local project.

**Comment by chrmarti** [comment]
Does that store it in your home folder's `.gitconfig`?

**Comment by JohnGalt1717** [comment]
Don't know. But it's the default in VS.net (full fat)

**Comment by chrmarti** [comment]
Please check what's in your `%USERPROFILE%\.gitconfig`.

**Comment by JohnGalt1717** [comment]
Yup. That's where it's set.

**Comment by chrmarti** [comment]
@JohnGalt1717 Could you give VS Code Insiders a try? The Remote-Containers extension comes in a slightly newer version with fixes in that area for that. See: https://code.visualstudio.com/insiders/

**Comment by JohnGalt1717** [comment]
Appeared to work. Thanks!
