### ISSUE TITLE
pem file support

### ISSUE THREAD

**Issue by MeTaNoV** [microsoft/vscode-remote-release#173]
Hi,
at my company, we are usually using `pem` file to connect to our instances like:

`ssh -i '/path/to/file.pem' ubuntu@hostname`

I didn't find any way to configure remote-ssh to use those files.

**Comment by karmeleon** [comment]
You can specify a .pem file to use in your .ssh/config:
```
Host whatever
    IdentityFile /path/to/file.pem
```

**Comment by SubodhChettri** [comment]
# Read more about SSH config files: https://linux.die.net/man/5/ssh_config
Host remote-vscode
    HostName <HOSTNAME>
    User ec2-user
    IdentityFile d:/PATH/TO/FILE.pem


LOCATED AT: https://code.visualstudio.com/docs/remote/ssh#_getting-started

**Comment by MeTaNoV** [comment]
Thanks a lot @karmeleon and @SubodhChettri, it works like a charm!

**Comment by egamma** [comment]
// fyi @chuxel tips & tricks worthy?

**Comment by Chuxel** [comment]
@egamma The syntax is mentioned in three spots currently:

In the sample here in the main article: https://code.visualstudio.com/docs/remote/ssh#_remembering-hosts-you-connect-to-frequently
Tips and tricks here: https://code.visualstudio.com/docs/remote/troubleshooting#_improving-your-security-with-a-dedicated-key
and again here related to reusing a putty generated key: https://code.visualstudio.com/docs/remote/troubleshooting#_reusing-a-key-generated-in-puttygen

**Comment by egamma** [comment]
@chuxel goodness, thanks.
