### ISSUE TITLE
Open large project with WSL2 bug

### ISSUE THREAD

**Issue by Dijir** [microsoft/vscode-remote-release#1731]
Issue Type: <b>Bug</b>

When I open large project and I try to press CTRL+C to copy some text, it shows "activating extension..." and didn't copy.
After aprox. 1 minute I see that WSL was disconnected and if I would like to reload.

Extension version: 0.40.0
VS Code version: Code - Insiders 1.40.0-insider (5aec74ad3b55bb9463e717ec950e665288accd0f, 2019-10-18T05:33:48.915Z)
OS version: Windows_NT x64 10.0.19008
Remote OS version: Linux x64 4.19.75-microsoft-standard
Remote OS version: Linux x64 4.19.75-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-7980XE CPU @ 2.60GHz (36 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.68GB (97.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|27%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.75-microsoft-standard|
|CPUs|Intel(R) Core(TM) i9-7980XE CPU @ 2.60GHz (36 x 2591)|
|Memory (System)|124.51GB (122.03GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.75-microsoft-standard|
|CPUs|Intel(R) Core(TM) i9-7980XE CPU @ 2.60GHz (36 x 2591)|
|Memory (System)|124.51GB (122.03GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment]
Does this reproduce with all (additional) extensions disabled except Remote - WSL ?

**Comment by Dijir** [comment]
Yes, I have disabled every single extension and the problem persists.

**Comment by aeschli** [comment]
Are you still seeing this?
