### ISSUE TITLE
High latency in terminal

### ISSUE THREAD

**Issue by praveen-srinivasan** [microsoft/vscode-remote-release#1732]
The remote terminal seems to have high latency for keystrokes - SSHing into the same machine via a standard terminal provides a much lower latency typing experience. Is there a way I can debug the issue further?

**Comment by Tyriar** [comment]
Can you define what low and high is exactly? Also what are you connecting to/from?

**Comment by praveen-srinivasan** [comment]
Hi,
This is for the terminal in VSC. In the remote mode, it automatically logs
into the remote machine for you. Compared to a standard ssh session opened
in a parallel regular Linux terminal, typing is slower.

**Comment by Tyriar** [comment]
@praveen-srinivasan is this like 100ms low, 200ms high, or something more extreme like 2s high? Are you connecting from linux to linux?
