### ISSUE TITLE
Remote Containers not working when enabled in remote server

### ISSUE THREAD

**Issue by ain-soph** [microsoft/vscode-remote-release#1734]
- VSCode Version: 1.39.2
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

There is a running docker container on remote server and I need to make modifications in it.

I know there are ways to attach VS code to a container on remote server by forward the docker daemon on server to a localhost port, and then use local extension "remote-containers" to attach them as if they are local containers.
(Option 3 in https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host)

But it's quite inconvenient and I have to establish an ssh tunnel every time.

Expecations:
1. Attach the VS code to remote server by ssh.
2. Enable the "remote-containers" and "Docker" extensions on remote server.
3. Attach the container on remote server.

However, it doesn't work for now.

Reasons I guess:

When I attach the container on remote server, the VS code will open a new window and abandon the old windows. In the new windows, the old remote-ssh information is lost and I've lost connection to the remote server, and I can't connect to the container on remote server therefore.

So I hope I can use "remote-containers" extension on remote server on the basis of "remote-ssh" extension.
I know there must be a forwarding process ( similar to Option 3 in https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host).
But I hope I don't need to establish the tunnel manually every time but let VS code forward the data between "remote-SSH" extension on local laptop and "remote-containers" extension on remote server. "remote-containers" establishes the bridge between the remote server and its container, while "remote-SSH" establishes the bridge between the remote server and local laptop. Finally, the container on remote server could be accessed by local laptop.

Furthermore, I hope all three remote extensions could work in multiple layers.
Something like this:
Local Laptop --remote SSH--> Server1 --remote WSL--> Server 2 --remote containers--> Server 3 --remote containers--> Server 4 

Steps to Reproduce:
1. Install Docker and Remote Development extensions by Microsoft at a Local laptop (including SSH and Container)
2. Run a docker container on remote Server.
`
docker run -ti --net=host --pid=host [image]
`
3. Enable the "remote containers" extension on server rather than local laptop. (Add this to the user settings.json)
`    "remote.extensionKind": {
        "ms-vscode-remote.remote-containers": "workspace"
    },`
4. Connect to the remote Server by remote explorer using SSH.
![image](https://user-images.githubusercontent.com/13214530/67616064-36f06e80-f7a2-11e9-9279-c7471984621b.png)

5. Enable "Docker" and "remote containers" extension on remote server.
![image](https://user-images.githubusercontent.com/13214530/67616077-699a6700-f7a2-11e9-9002-feac57afff09.png)

6. Connect to the container on remote server, which throws an error.
![image](https://user-images.githubusercontent.com/13214530/67616423-70c37400-f7a6-11e9-87ac-e8a40f795062.png)

Or 
![image](https://user-images.githubusercontent.com/13214530/67616437-aff1c500-f7a6-11e9-9647-7c9a0c066e90.png)

The error MSG:
![image](https://user-images.githubusercontent.com/13214530/67616451-f0e9d980-f7a6-11e9-8ec8-f02e643286b4.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
Support for connecting via `ssh://` URIs to a remote Docker daemon is in the works: https://github.com/microsoft/vscode-remote-release/issues/636

**Comment by ain-soph** [comment]
> Support for connecting via ssh:// URIs to a remote Docker daemon is in the works: #636

Which is a good news to hear about. Hope it can come out soon!
