### ISSUE TITLE
.gitignore ignored

### ISSUE THREAD

**Issue by pmonty** [microsoft/vscode-remote-release#1736]
- VSCode Version: 1.40.0-insider
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu-18.04
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. add `node_modules` to a `.gitignore` file
2. `node_modules` is not grayed out

It is definitely remote only issue so I am thinking its either a bug or not a feature yet of WSL Remote? I am new to WSL so thought I would create an issue.

Happy coding people!

**Comment by jolsen71** [comment]
This issue impacts not only what appears in the git changed files sidebar, but also the file explorer sidebar.

This is also an issue with VS Code 1.40.1 (non-insider).

**Comment by joaomoreno** [comment]
@jrieken There might be something happening with decorations on WSL/remote.

**Comment by jrieken** [comment]
> add node_modules to a .gitignore file

🔝 that doesn't mean that node_modules is being ignored when it has been added already. this is most common misunderstanding in gitignore.

**Comment by joaomoreno** [comment]
Oh, great point.  @pmonty did you already check in the node_modules?
