### ISSUE TITLE
Cannot open more than one VSCode window on one running container

### ISSUE THREAD

**Issue by sandman21dan** [microsoft/vscode-remote-release#1737]
- VSCode Version: 1.39.2
- Local OS Version: Mac OS Catalina 10.15 (19A602)
- Remote OS Version: Ubuntu
- Remote Extension/Connection Type: Docker

This issue came up for me recently, it's probably a side effect of some other fix elsewhere

First off here's my use case, I maintain a docker image which contains all my development preferences, like Python, Node, Vim configuration, this way I have a 100 portable dev environment where I can seamlessly work from a Mac, Windows or Linux OS and everything works the same

Plus of course the runtime environment will match where the actual stuff I develop will be run on

Since this is a bit of a monolithic approach where I have all my dependencies on one container, I may have many many projects mounted to the same container rather than (what I assume to be the intended way) running a new container per window or project

I was able to attach as many new windows as I wanted to the same container by running "Remote-Containers: Attach to Running Container" and each would spawn a new window

This is not now the case, when I attach to a running container, the focus simply goes back to the current already connected running container

Steps to Reproduce:

1. Open a new/fresh VSCode window
2. Run the "Remote-Containers: Attach to Running Container"
3. Select the container you want to attach to
4. Select the folder where your project is
5. To open a new window with a different project Run the "Remote-Containers: Attach to Running Container"
6. Select the container you want to attach to
7. You get highlighted to the first container on the same window

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
We now remember the last folder and reopen that the next time you attach to a container of the same image. If that folder is already open in an existing window, we pass focus to that window.

It would make sense for the 'Connect to Container' action on the container node in the Remote Explorer to always open a new window, otherwise that action is redundant to the folder nodes below the container node.

@alexr00 What do you think?

![image](https://user-images.githubusercontent.com/9205389/68489138-ca1bb080-0246-11ea-8ad3-61a5802d8a8b.png)

**Comment by alexr00** [comment]
I think we deliberately made it do the same thing as the action on the folders for consistency. What if we add a new context menu "Connect in New Window"?

**Comment by sandman21dan** [comment]
> I think we deliberately made it do the same thing as the action on the folders for consistency. What if we add a new context menu "Connect in New Window"?

This would absolutely do it, and for me specially "Attach to Running Container in new window" would do the trick

**Comment by chrmarti** [comment]
@alexr00 Sounds good!
