### ISSUE TITLE
Requires multiple independent startups of vscode remote ssh

### ISSUE THREAD

**Issue by starkoff** [microsoft/vscode-remote-release#1738]
Need to add override .vscode-server-insiders or serverDataFolderName to Microsoft VS Code Insiders \ resources \ app \ product.json

Several computers use one login to connect SSH , and as a result they have one $HOME directory.
errors occur during the work with the same connection
Requires multiple independent startups of visual studio code remote ssh

**Comment by roblourens** [comment]
Not really clear what the problem is. Multiple users should really log in with separate user accounts. But even if they don't, this should technically still work. Can you give me more details, like share the Remote-SSH output channel log when there is a problem?

**Comment by starkoff** [comment]
Unfortunately, the server administrator gave 1 account with the username and password for the server and the rights set up for editing the directories of 2 users. There is a restriction for creating new users for simultaneous work.

by issue:
Technically, the entrance goes through and you can connect and work. But after some time, the extensions installed by the first developer begin to introduce problems for another developer who installs other extensions. after a short time it’s clear that the reconstruction of visual studio code is ongoing

The fix helped:
 for different developers, put different serverDataFolderName in the configs of the visual studio code program.

I will try to create a problem again and throw off any logs

**Comment by roblourens** [comment]
> But after some time, the extensions installed by the first developer begin to introduce problems for another developer who installs other extensions. after a short time it’s clear that the reconstruction of visual studio code is ongoing

Still not clear exactly what the issue is
