### ISSUE TITLE
Remote - Containers fails with latest Docker Desktop Tech Preview and WSL 2.

### ISSUE THREAD

**Issue by JohnGalt1717** [microsoft/vscode-remote-release#1739]
- VSCode Version: VS Code Insiders
- Local OS Version: Windows 10 10.0.19008.1000
- Remote OS Version:  Docker Tech Preview 2.1.4.0 (39357
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Install the latest docker tech preview.
2. Make sure that WSL 2 integration is running.
3. Make sure that WSL 2 integration is the default.
4. Install the Remote - Containers extension for vs code insiders.
5. Open workspace that has a dev container setup and choose use when it prompts.
6. Error message "Docker versio n17.06.1 or later required" pops up instead of opening the container in the WSL 2 environment.

Here's the docker version output:

docker version
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2
 Built:             Tue Oct  8 00:54:33 2019
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
 Kubernetes:
  Version:          v1.15.4
  StackAPI:         v1alpha3

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by Chuxel** [comment]
@JohnGalt1717 I am able to get this working with Docker Desktop 2.1.4.0, Win 10 insiders 18990.1, and VS Code 1.40-insiders commit 33cc09da7a314ea0ee5677d1927739af60d16734. 

Given the error, one possibility is that VS Code is not finding docker in the path on the Windows side - which could mean the Docker Tech Preview didn't install properly on there is something going on with the OS path. 

If you copy the contents of the "Dev Containers" terminal output here, we might be able to see a specific error that would hint at the problem. Likely it is something with the Docker Tech Preview itself.

**Comment by JohnGalt1717** [comment]
After restart it appeared to work properly. Odd that it worked fine from cmd, ubuntu wsl, and powershell but didn't work in vs code.

Might want to update the error message to try a restart...

**Comment by JohnGalt1717** [comment]
Spoke to soon:

C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: rpc error: code = Unknown desc = wslpath failed; stderr is "wslpath: /var/run/docker.sock\n": exit status 1.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.
Failed: Starting the development container
Command failed: C:\Program Files\Docker\Docker\resources\bin\docker.exe run -a STDOUT -a STDERR -p 127.0.0.1:44301:44301 -p 127.0.0.1:1562:1562 --mount type=bind,source=<apth>/Api Core,target=/workspaces/Api Core,consistency=consistent
 -l vsch.quality=insider -l vsch.remote.devPort=0 -l vsch.local.folder=d:\Repos\CADLearning\Api Core -v /var/run/docker.sock:/var/run/docker.sock --entrypoint /bin/sh vsc-apicore-f4c864e5ce1c5c596fa0cfe707872ede -c echo Container started ;  while sl
eep 1; do :; done

**Comment by Chuxel** [comment]
@ JohnGalt1717 That is coming from Docker, so likely a tech preview problem.  However, note that you have to restart the tech preview manually each time you start Docker.  That error could mean that Docker Desktop is up, but the WSL preview is not. (I know it's strange - not sure why Docker opted for that experience.)

All of this I'd expect will get sorted out on the Docker side as the tech preview continues.

**Comment by JohnGalt1717** [comment]
OK. I'll wait until the next preview that fixes everything in the current and turns on k8s to report if it's still there. I've switched to classic mode for now. Thanks.

**Comment by Chuxel** [comment]
@JohnGalt1717 Last I saw, neither Docker Compose nor Kubernetes were suppored in the current tech preview.  There are major changes coming soon that supposedly will fix these, but I'd expect it will still be a few releases before things stabilize.

More at https://engineering.docker.com/2019/10/new-docker-desktop-wsl2-backend/
