### ISSUE TITLE
Unable to copy from file from WSL file tree to Windows desktop, etc

### ISSUE THREAD

**Issue by rwilliams** [microsoft/vscode-remote-release#1741]
Issue Type: <b>Bug</b>

With an open editor I attempt to drag a file from the editor to my desktop. A popup for where to save the file opens up and I click save.  The file doesn't appear on my desktop and it fails silently. Using WSL2 with the lastest Windows Insider fast ring build 19008.1000

Extension version: 0.39.9
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.19008
Remote OS version: Linux x64 4.19.75-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (22.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.75-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3500)|
|Memory (System)|30.32GB (29.48GB free)|
|VM|0%|
</details>

**Comment by isidorn** [comment]
Yes, this is unforntunetly not supported due to a Chrome limitation.
Please use the right click -> Download action as a workaround.
Closing as will not fix

**Comment by rwilliams** [comment]
That works. Thanks.
