### ISSUE TITLE
Random reconnects

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1742]
I have been seeing reconnection kicking in randomly more often. Often immediately shortly after connecting to a remote. It goes through reconnection and connects, then is fine after that. I haven't caught it happening with the log level set to "trace" yet and I have no idea why it's happening. @kieferrm also mentioned that he has seen this over the past 2 or 3 weeks. This is always on a stable connection with nothing weird going on in the remote.

@alexandrudima any idea what might have changed?

**Comment by alexandrudima** [comment]
@roblourens No, I'm not sure what would have changed in this way... I have just found https://github.com/microsoft/vscode/issues/83672 though, maybe you had something blocking the UI thread for an extended period of time?

**Comment by alexandrudima** [comment]
It was 10s, @kieferrm doubled it to 20s
