### ISSUE TITLE
Remote-Explorer: Update inline actions on current container

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1752]
Currently the actions are 'Open Folder in Container...' and 'Remove Recent Folder', both don't make much sense on the current container.

![image](https://user-images.githubusercontent.com/9205389/67772195-ef940780-fa59-11e9-8cca-03def3c9f2df.png)

I suggest to replace these with 'Open Container Configuration File' and 'Reopen Locally' ('Close Remote Connection' for containers attached to).

**Comment by alexr00** [comment]
I like 'Reopen Locally', but 'Open Container Configuration File' and 'Close Remote Connection' sound like container actions, not folder actions. 

I'll remove the 'Remove' and 'Open' actions from the active folder and add 'Reopen Locally' to dev container folders and 'Close Folder' to attached folders.
