### ISSUE TITLE
Connection to Docker becomes saturated during high-workload VSCode server processes

### ISSUE THREAD

**Issue by wknechtel** [microsoft/vscode-remote-release#1757]
- VSCode Version: 1.39.2
- Local OS Version: Windows 10 Pro 1809
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Build a Docker container that has a VERY large codebase (I've been using: https://github.com/wknechtel/magento-opensource-dev, which builds a Magento 2 Open Source instance)
2. Install PHP Intellisense or PHP Intelliphense extensions into the container (I've tried both), then reload the window when prompted.
3. Open a folder to begin editing (`/home/magento/www` in the case of the aforementioned container)

Once the intellisense/intelliphence plugin has a chance to realize it needs to index the folder, the process takes many hours to run. While it's running, the connection to the docker container becomes saturated, and VSCode continually has to try to reconnect. The process still runs, but the container is unusable until it's finished. Trying to connect from PowerShell (docker exec -it m23 /bin/bash) works, but you have to wait about 5 minutes before you'll get a connection.  Any commands you try to run also take about 5 min to echo back to the terminal and run.  

The host computer is running an AMD Ryzen 7 2700 eight-core with 16GB RAM and a lovely NVME drive. Host processor sits between 12 & 17% usage while this process occurs, and drops to 2-3% when it's finished.

**Comment by Chuxel** [comment]
@wknechtel How much CPU and RAM did you allocate to docker?  It sounds like it may be on its defaults which is only 2 CPUs and 2 GB of RAM.

**Comment by wknechtel** [comment]
@Chuxel It is indeed on the default allocation.

**Comment by Chuxel** [comment]
@wknechtel Given you're seeing connection interruptions, what is likely happening is not the the channel is getting saturated, but that the actual extension running in the container is getting resource starved. I don't know how efficient those two extensions are with CPU or memory use (or if there's a memory leak in some scenario), but the CPU in the container is probably 100% when it happens or RAM is exceeded. 

Try bumping it up to 4 cores and 4GB and see if that helps. The "Resource Monitor" extension is also something you can install in the container that should give you visibility in the status bar as to what is actually going on when you're seeing it happen.

**Comment by wknechtel** [comment]
That made a remarkable difference. Nice and snappy. That's odd... but thank you.  I apologize for the false flag.
