### ISSUE TITLE
Remote connection fails with ProxyCommand plink.exe

### ISSUE THREAD

**Issue by jdunham22** [microsoft/vscode-remote-release#1759]
Issue Type: <b>Bug</b>

Trying to get remote editing working with plink/pageant since vscode already can use pageant for ssh. ProxyCommand plink can authenticate but then it stalls forever and the remote host reports a bash error.

Here is my ssh config

Host  myremotehost
  HostName myremotehost
  User jdunham
  ProxyCommand C:\Programs\PuTTY\plink.exe jdunham@myremotehost -v -T -sshlog C:\programs\putty\myremotehost.log

note that spaces in the plink pathname didn't work for me, I couldn't find any combination of quotes and separators that would connect to myremotehost at all.

when you execute with -v and press "details" an extension popup, you see this in the terminal:

Connecting to 10.1.10.30 port 22
Writing new session log (SSH packets mode) to file: C:\programs\putty\myremotehost.log
We claim version: SSH-2.0-PuTTY_Release_0.70
Server version: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
Using SSH protocol version 2
Doing ECDH key exchange with curve Curve25519 and hash SHA-256
Server also has ecdsa-sha2-nistp256/ssh-rsa host keys, but we don't know any of them
Host key fingerprint is:
ssh-ed25519 256 ...
Initialised AES-256 SDCTR client->server encryption
Initialised HMAC-SHA-256 client->server MAC algorithm
Initialised AES-256 SDCTR server->client encryption
Initialised HMAC-SHA-256 server->client MAC algorithm
Pageant is running. Requesting keys.
Pageant has 2 SSH-2 keys
Using username "jdunham".
Trying Pageant key #0
Server refused our key
Trying Pageant key #1
Authenticating with public key "jdunham@example.com" from agent
Sending Pageant's response
Access granted
Opening session as main channel
Opened main channel
Started a shell/command
-bash: line 1: $'SSH-2.0-OpenSSH_for_Windows_7.7\r': command not found

Extension version: 0.47.2
VS Code version: Code - Insiders 1.40.0-insider (33cc09da7a314ea0ee5677d1927739af60d16734, 2019-10-28T11:50:41.596Z)
OS version: Windows_NT x64 10.0.18362
Fetching remote diagnostics for 'ssh-remote+myremotehost' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (3.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'ssh-remote+myremotehost' timed out.
</details>

**Comment by benok** [comment]
Hi, I wrote a small wrapper handling this issue.
Could you check this out ?
https://github.com/benok/ssh2plink

**Comment by jdunham22** [comment]
> Hi, I wrote a small wrapper handling this issue.
> Could you check this out ?
> https://github.com/benok/ssh2plink

...
Trying Pageant key #1
Authenticating with public key "jdunham@example.com" from agent
Sending Pageant's response
Access granted
Opening session as main channel
Opened main channel
Allocated pty (ospeed 38400bps, ispeed 38400bps)
Started a shell/command

==> It seemed to get slightly further but is stalling on "Initializing VS Code Server"

**Comment by benok** [comment]
Thanks for trying.  It just works for me.

Hmm,  Do you still set -v option ?
ssh2plink doen't work with -v option like below.
```
Remote.SSH: PATH
C:\some\path\putty\ssh2plink.exe -v
```
If you do, please remove "-v".

I tried to get detail log on success, but VSCode doesn't seem to provide detail log if it successfully connected.

**Comment by jdunham22** [comment]
With the absolute path to either plink or ssh2plink in the SSHRemote:Path setting, I am always prompted for a password even though my keys are loaded in pageant.  With either of those set in the SSH Configuration ProxyCommand setting, then authentication occurs with the SSH key, but vs code always stalls waiting for the remote server to start up.

Is there any "needs-more-info" info needed?

**Comment by benok** [comment]
I too(, and almost always) use pageant on connecting to every host.
I don't use OpenSSH's ssh.exe with ProxyCommand for Remote-SSH plugin.
I use default settings for Remote-SSH plugin except Remote.ssh config.
On putty, specify "Auto-login username" on config, and use pageant.

I want to confirm that with "putty",  you can login to the host  just selecting host without username prompt or password input, right ?
Is the configuration of putty is plain ? 
If not, could you make one from scratch ?

p.s.
I think plink is not supported by Remote-SSH anymore.
I found Remote-SSH confirms that ssh is real OpenSSH (not plink) and using OpenSSH config file to enum hosts, update parameters, etc.

So I try to write ssh2plink, and after an hour or so, it just works on my env at least. 
I doubt that I'll encounter some trouble. But I don't have any trouble using it whole day, 
and so I decided to release this quick'n dirty hack for putty users like us.

I feel it's a bit thread hijacking. If you can't connect using ssh2plink, we should open ticket of ssh2plink and move to there.

I personally wish Remote-SSH to support plink, but I understand plink is just for Windows and supporting plink is not good for cross-platform app like VSCode.
(I know Putty has several amount of users, but I want to know how MS's developers think about this...)

Sorry for long comment. :-)

**Comment by jdunham22** [comment]
Thanks for the effort @benok .  I am also using tmux started from my .bashrc, and it turns out this also has some interference with ssh agents so let me test without tmux first and see whether that improves the situation.
