### ISSUE TITLE
Cannot authenticate against git repository that uses https with Kerberos

### ISSUE THREAD

**Issue by hacst** [microsoft/vscode-remote-release#176]
- VSCode Version: 1.34.0-insider
- Local OS Version: Windows 10
- Remote OS Version: mcr.microsoft.com/dotnet/core/sdk:2.2 (debian slim based)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Checkout a https authenticated repository from an Azure DevOps Server (or any other server with passwordless https authentication) onto a Windows machine
2. Try to use git when remote developing inside of a dotnet core sdk container

This will result in "Authentication failed" for the repository with no possibility of manually entering a username and password as would usually happen when connecting without credentials.

It looks like while credentials.helper is forwarded, no provision is made for Kerberos for which the windows credential helper returns an empty set of credentials. Reproducing the credential helper call manually I get:

```
$ code-insiders --gitCredential get
> protocol=https
> host=XXX
>
< protocol=https
< host=XXX
< path=
< username=
< password=
```
I assume the empty credentials that are returned is what prevents git for asking for https credentials.

Ideally vscode would somehow be able to authenticate automatically using the host credentials even for Kerberos. Otherwise some possibility to fallback to manually authenticate using username and password could be a possible workaround.

**Comment by chrmarti** [comment]
From what I currently understand we somehow need to forward the Kerberos requests on the Linux side to the host OS.

**Comment by hacst** [comment]
Unfortunately I only have a very rough understanding about the inner workings of this authentication method. I would assume that one possible way would be to have the host act as a proxy for the git connections and let it handle the kerberos authentication (e.g. something like https://github.com/nilleb/authentication-proxy ). But it is quite possible that there is a more elegant way.
