### ISSUE TITLE
ConnectTimeout=15 in ssh command too short, no override option in settings

### ISSUE THREAD

**Issue by nairbv** [microsoft/vscode-remote-release#1761]
When attempting to connect to a remote host using RemoteSSH, I occasionally get connection failures due to timeouts. 

The ssh command used includes the option `-o ConnectTimeout=15`, which for certain servers I'm trying to connect to is too short. Looking in the config options for the plugin, I don't see any way to configure ssh options (other than the ssh_config or the path to the command itself).

As a workaround, I've added a bash script that filters out the ConnectTimeout option before calling ssh, and pointed vs-code to my bash script instead of the system ssh command. An option to override this in the timeout setting would be preferable.

**Comment by nairbv** [comment]
workaround ssh-wrapper:

```
#!/bin/bash

options=($@)
indexes=${!options[@]}

for index in ${indexes[@]}
do
    value=${options[$index]}
    if [[ $value =~ -o ]]
    then
        next=$((index + 1))
        option=${options[$next]}
        echo "checking option $option"
        if [[ $option =~ ConnectTimeout= ]]
        then
            echo "removing parameter: $value"
            unset -v 'options[$index]'
            echo "removing parameter: ${options[$next]}"
            unset -v 'options[$next]'
        fi
    fi
done

COMMAND="/usr/bin/ssh ${options[@]}"
echo $COMMAND
$COMMAND

```

**Comment by nairbv** [comment]
@roblourens is this fixed now / is there an associated PR?

**Comment by roblourens** [comment]
This is in today's nightly build of the extension. Unfortunately the code is not open source.e

**Comment by roblourens** [comment]
Verification steps: verify that the new setting `remote.SSH.connectTimeout` is respected
