### ISSUE TITLE
VSCode server can´t run start on WSL 2 (Ubuntu 18.04)

### ISSUE THREAD

**Issue by josephrodriguez** [microsoft/vscode-remote-release#1766]
- VSCode Version:
> Version: 1.39.2 (user setup)
> Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
> Date: 2019-10-15T15:35:18.241Z
> Electron: 4.2.10
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.18362
- Local OS Version:
> OS Name	Microsoft Windows 10 Pro
> Version	10.0.18362 Build 18362
> System Type	x64-based PC
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Use WSL-2 with Ubuntu 18.04
2. Run VSCode
3. Install Remote - WSL extension
4. Pick Remote - WSL: New Window
5. This exception is captured on terminal:

```/home/username/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/server.sh: 12: /home/username/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/server.sh: /home/username/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/node: Exec format error```

**Comment by aeschli** [comment]
Note, WSL 2 is only available in Windows 10 builds 18917 or higher.

Can you paste the full content of the WSL terminal?
