### ISSUE TITLE
Usage on Arch

### ISSUE THREAD

**Issue by Matelasse** [microsoft/vscode-remote-release#1767]
- VSCode Version: 1.39
- Local OS Version: Arch
- Remote OS Version: Any
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Use Arch
2. Download Arch with pacman
3. Try to connect to any SSH host
4. Failed to connect to the remote extension host server (Error: Connection error: Version mismatch, client refused.)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

How can this be the case? Is my impression correct that Arch users who downloaded code from Arch repositories cant use remote ssh extension? If this is the case why dont you build Arch code package yourself? I might be jumping to conclusions but if that really is the case then this is outright absurd.

@chrmarti

**Comment by chrmarti** [comment]
The "remote" functionality (SSH/WSL/Docker) is currently only available for VS Code proper, not 3rd party builds.

You can try running the snap build of VS Code in Arch Linux (which appears to support snaps). See https://code.visualstudio.com/docs/setup/linux for instructions. /cc @joaomoreno

**Comment by Chuxel** [comment]
Yeah I believe the https://aur.archlinux.org/packages/visual-studio-code-bin/ AUR package should work.

**Comment by chrmarti** [comment]
Isn't the AUR package a 3rd party build? That wouldn't work from what I understand.

**Comment by Chuxel** [comment]
@chrmarti There are multiple packages for VS Code in arch, this AUR one comes from the official stable `.tar.gz`. We've seen this with Live Share as well - the AUR package visual-studio-code-bin is the one that is an integrated version of the official package.

"Visual Studio Code (vscode): Editor for building and debugging modern web and cloud applications (official binary version)"

Sources (3)
code_x64_1.39.2.tar.gz
visual-studio-code-url-handler.desktop
visual-studio-code.desktop

It's also a commercial license.

So, unless they've messed with it really recently, it should be working.

**Comment by Matelasse** [comment]
@chrmarti Its not an AUR package, it is in community https://www.archlinux.org/packages/community/x86_64/code/
If you're saying that is something you expect since it's not shipped officially from the code team, then WHY dont you ship it yourself? When I brought this up once in the past Tyriar said there was already a community maintained package doing well and he didnt really know how to package code for Arch. However if that means people are going to miss out on features then I believe you guys should either enable it for all or bring it to Arch users yourself. It's not like Arch is not windows98 to be disregarded like that.

**Comment by chrmarti** [comment]
@Matelasse Have you tried https://aur.archlinux.org/packages/visual-studio-code-bin/ suggested by @Chuxel above?

**Comment by ipstone** [comment]
Hello @chrisdias , I am trying to make vscode remote work on my arch linux, but having connection issues - it keeps timeout, and I couldn't find information in the log what's wrong. yes, I was using the visual-studio-code-bin AUR version. I also tried the official arch open-source version, which has the same issue.

When I am connecting with mac vscode to the ssh server, it works well - so well that I want to enable the same work flow on my arch linux.

I am wondering whether it could be arch linux firewall issues? but as ssh connects well in the terminal, not sure what's wrong in the arch vscode. 

Any suggestions are appreciated.

**Comment by ipstone** [comment]
Here is my ssh connect log (now with the open source vscode)
[11:30:31.318] remote-ssh@0.48.0
[11:30:31.318] linux x64
[11:30:31.320] SSH Resolver called for "ssh-remote+rock", attempt 1
[11:30:31.320] SSH Resolver called for host: rock
[11:30:31.320] Setting up SSH remote "rock"
[11:30:31.336] Using commit id "8b6e0efc0a98639085fabeb5226a516785424796" and quality "insider" for
[11:30:31.338] Testing ssh with ssh -V
[11:30:31.351] ssh exited with code: 0
[11:30:31.351] Got stderr from ssh: OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
[11:30:31.355] Running script with connection command: ssh -T -D 34267 -o ConnectTimeout=15 rock bas
[11:30:31.355] Install and start server if needed
[11:30:31.551] > bind [::1]:34267: Cannot assign requested address
> channel_setup_fwd_listener_tcpip: cannot listen to port: 34267
> Could not request local forwarding.
[11:30:31.552] Got some output, clearing connection timeout
[11:30:31.838] > /home/isaacpei/.bashrc: line 220: bind: warning: line editing not enabled
> ec65297fc2f2: running
[11:30:31.876] > Acquiring lock on /home/isaacpei/.vscode-server-oss/bin/8b6e0efc0a98639085fabeb5226a516
> Found existing installation at /home/isaacpei/.vscode-server-oss/bin/8b6e0efc0a98639085fabeb5226a51678
[11:30:31.915] > Found running server...
>
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>
[11:30:31.920] > Checking server status on port 33141 with wget
> ec65297fc2f2: start
> sshAuthSock====
> agentPort==33141==
> webViewServerPort====
> osReleaseId==centos==
> arch==x86_64==
> webUiAccessToken====
> ec65297fc2f2: end
[11:30:31.920] Received install output:
sshAuthSock====
agentPort==33141==
webViewServerPort====
osReleaseId==centos==
arch==x86_64==
webUiAccessToken====

[11:30:31.921] Remote server is listening on port 33141
[11:30:31.921] Parsed server configuration: {"agentPort":33141,"osReleaseId":"centos","arch":"x86_64
[11:30:31.924] Starting forwarding server. localPort 33835 -> socksPort 34267 -> remotePort 33141
[11:30:31.924] Forwarding server listening on 33835
[11:30:31.925] Waiting for ssh tunnel to be ready
[11:31:04.177] Tunneled remote port 33141 to local port 33835
[11:31:04.177] Resolved "ssh-remote+rock" to "127.0.0.1:33835"
[11:31:04.182] ------

**Comment by ipstone** [comment]
Furthermore, I tried to enable TcpForwarding in my local sshd setup, but it still doesn't work.

**Comment by ipstone** [comment]
Could the issue be the docker setup on my machine modified iptables:

iptables-save
# Generated by iptables-save v1.8.3 on Tue Dec 17 12:33:07 2019
*filter
:INPUT ACCEPT [12459:9028354]
:FORWARD DROP [1:356]
:OUTPUT ACCEPT [9949:1224505]
:DOCKER - [0:0]
:DOCKER-ISOLATION-STAGE-1 - [0:0]
:DOCKER-ISOLATION-STAGE-2 - [0:0]
:DOCKER-USER - [0:0]
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
COMMIT
# Completed on Tue Dec 17 12:33:07 2019
# Generated by iptables-save v1.8.3 on Tue Dec 17 12:33:07 2019
*nat
:PREROUTING ACCEPT [1024132:49720259]
:INPUT ACCEPT [3901:644464]
:OUTPUT ACCEPT [45482:3121506]
:POSTROUTING ACCEPT [45481:3121474]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
COMMIT
# Completed on Tue Dec 17 12:33:07 2019

**Comment by thelittlebug** [comment]
i had the same problem with vscode and arch. as suggested by @Chuxel i deinstalled my vscode and installed https://aur.archlinux.org/packages/visual-studio-code-bin/ via pacman.

after that i started code and installed ms-vscode-remote.vscode-remote-extensionpack

now everything seems working as expected.
