### ISSUE TITLE
Remote Container: Add 'Show Log' to the context menu in the explorer

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#1769]
The context menu shown on a container should also include the 'Show Log' command

![image](https://user-images.githubusercontent.com/172399/68035468-f7ef7b00-fcc3-11e9-8ab7-c265e4ec173a.png)

**Comment by egamma** [comment]
@alexr00 When I filed the feature request I've overlooked that there is already a Container: Show Log in the command palette:

![image](https://user-images.githubusercontent.com/172399/68402404-9031a800-017b-11ea-8666-d9eb792f3a2c.png)

It is confusing to have two commands with different behaviour:
- command palette: shows the dev container log that is shown in the Terminal>Dev Containers for the currently active dev container
- context menus: shows the container log that docker has for a container ('docker logs')

There are different options:
1. use different command names, e.g. use 'Show Container Log' in the context menu
2. always show the Dev Container log (in this case the menu item would only be available for a running container).

In addition, the docker container log isn't as interesting as I expected, it doesn't help us to narrow down an issue, e.g.:
![image](https://user-images.githubusercontent.com/172399/68402715-0e8e4a00-017c-11ea-829c-f4a762a8da17.png)

This raises the question whether there is value in having this context menu entry (and my feature request was not useful, sry).

**Comment by alexr00** [comment]
I don't think having a context menu item to show the dev container log is very useful. There are already at least 3 different ways to get to that log (start up notification, switch terminal, and command palette, maybe remote indicator too?). 

I would either revert the change, or rename the command. For more complex containers (such as selfhost), the log contains more than "Container started", so I am inclined to simply rename the command.

**Comment by egamma** [comment]
@alexr00 

>the log contains more than "Container started", so I am inclined to simply rename the command.

works for me 👍
