### ISSUE TITLE
Allow usage of named volumes inside dev containers

### ISSUE THREAD

**Issue by matevarga** [microsoft/vscode-remote-release#177]
Use case: 
Alice is using VS Code under Windows. She has a large project that takes a while to check out / build, also she tends to have unpushed branches locally. She wants to use VSC remote-containers to benefit from the standardized environment.
According to the current docs/suggestions, Alice would use Docker for Windows and check out the code on Windows. However, this means that code would be shared with the container through SMB, which means lots of lost performance and various other issues (like Maven war-plugin crapping out due some stat commands failing during builds, etc.). 

Solution: Alice clones the repo _inside_ the container, so she gets the benefit of VSC remote dev: she can use her Windows PC while avoiding problems with compilation, performance. Downside: state is lost during container rebuild.

Feature request: option to easily create a named volume that'd store the container's state between rebuilds.

Thanks.

**Comment by matevarga** [comment]
For anyone who'd like to do this: it's possible! 

First create a named volume like 
`docker volume create devenv`

In your `devcontainer.json` put

`	"runArgs": [ "devenv:/workspaces"  <,other params>]`

This way you can  persist /workspaces between container rebuilds.

**Comment by egamma** [comment]
//fyi @chrmarti

**Comment by chrmarti** [comment]
You could also switch to using Docker Compose, there you get to control all aspects of the containers: https://code.visualstudio.com/docs/remote/containers#_using-docker-compose

I'll close this issue as there are already two ways of doing this. Thanks.
