### ISSUE TITLE
Feature request: link to more complete manual for ssh/.config

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode-remote-release#1776]
https://code.visualstudio.com/docs/remote/ssh#_connect-to-a-remote-host says:

> Visual Studio Code uses SSH configuration files and requires SSH key based authentication to connect to your host. 

(By the way, I think the "requires SSH key based authentication" part is outdated.)

The link goes to https://linux.die.net/man/5/ssh_config, which does not cover the `Include` directive, for example, while this link here does:
http://man7.org/linux/man-pages/man5/ssh_config.5.html

**Comment by egamma** [comment]
// fyi @Chuxel

**Comment by Chuxel** [comment]
Updated in https://github.com/microsoft/vscode-docs/pull/3235 !
