### ISSUE TITLE
Does Remote - WSL lock files?

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/vscode-remote-release#1780]
- VSCode Version: 1.39.2
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 18.04 (WSL)
- Remote Extension/Connection Type: WSL

I use Remote - WSL to open a folder. I have open the same folder in Windows app: SmartSVN which is a GUI Subversion client. If I perform a svn command such as Update using SmartSVN while the folder is open in VS Code / Remote WSL, the svn command fails, probably due to file locks, and I have to close VS Code and perform  a svn cleanup operation.

This does not happen if I open the folder directly in VS Code (not using Remote - WSL).

Could Remote - WSL be locking files and causing this problem?

**Comment by aeschli** [comment]
See https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace
