### ISSUE TITLE
Specify remote alternative to /tmp (duplicate of #17)

### ISSUE THREAD

**Issue by dmey** [microsoft/vscode-remote-release#1781]
@roblourens -- this is a duplicate of #17 as I could no longer comment. The issue seem to still persist. Although redefining the path of `TMPDIR ` is a temporary workaround, this may not always work when it has already been defined system-wide and used for other purposes.

### System Info
- VSCode Version: 1.39.2
- Local OS Version: Windows 10
- Remote OS Version: CentOS Linux release 7.6.1810 (Core)
- Remote Extension/Connection Type: SSH/Docker/WSL Remote - SSH (Nightly)  2019.10.42662

**Comment by roblourens** [comment]
Can you describe what the problem actually is? We don't run a script in `/tmp` anymore

**Comment by dmey** [comment]
I'd like to install extensions on the remote however `/tmp` is `root` on my system hence the installation fails.

**Comment by dmey** [comment]
For reference, this is the error message -- 

![image](https://user-images.githubusercontent.com/26348635/68712491-c1531380-0593-11ea-915d-e96d173c3453.png)

**Comment by roblourens** [comment]
Redefining TMPDIR is your best option for now. VS Code itself uses /tmp for a lot of things. Would it help if you were able to set TMPDIR just in VS Code's environment?

**Comment by roblourens** [comment]
@sandy081 there is no way to change this just for extensions, right? I assume we are staging extension downloads in `/tmp` or something right?

**Comment by dmey** [comment]
>Would it help if you were able to set TMPDIR just in VS Code's environment?

yes -- `TMPDIR` is already being used by other services on the remote. I do not think that, in general, it's a good idea to rely on `/tmp` -- you never know what permission the sysadmin set ...

**Comment by roblourens** [comment]
Ok, in that case I think this would be served by https://github.com/microsoft/vscode-remote-release/issues/141
