### ISSUE TITLE
Auto*

### ISSUE THREAD

**Issue by xeor** [microsoft/vscode-remote-release#1784]
I can't find any ways of automatically run containers when vscode starts. Would that be possible?
I'm looking to create different startup-scripts for working on different projects. Getting the "click here to reopen in container" is kinda annoying.

One solution would be to skip the popup if an environment variable is set `VSCODE_AUTOSTART_CONTAINER=true` or something..

**Comment by bamurtaugh** [comment]
Thanks for opening this request! 

We're tracking the request to auto-connect to a remote here: https://github.com/microsoft/vscode-remote-release/issues/120.

Another option is that if you look at your Recent projects on the welcome page and find a dev container project, you can select it, and it'll automatically connect to your dev container:

![image](https://user-images.githubusercontent.com/25310137/96792429-3c7d9600-13af-11eb-9153-6360fab13f02.png)

As we're tracking automatic connection to a remote host through the issue above, closing this thread, but please let me know if you have any other questions or feedback. Thank you!
