### ISSUE TITLE
localPort config parameter not works

### ISSUE THREAD

**Issue by barcia** [microsoft/vscode-remote-release#1786]
- VSCode Version: 1.39.2
- Local OS Version: MacOS Catalina 10.15
- Remote OS Version: Ubuntu 18.04 lts
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Set the "remote.SSH.defaultForwardedPorts" option
2. Restart VSCode

If I set the "remote.SSH.defaultForwardedPorts" option and configure some ports, `name`and `remotePort`option works well, but `localPort` seems that not work.

This is my config:
```json
"remote.SSH.defaultForwardedPorts": [
    {
        "localPort": 8080,
        "name": "example",
        "remotePort": 8080
    }
],
```

<img width="840" alt="Captura de pantalla 2019-11-05 a las 9 20 20" src="https://user-images.githubusercontent.com/5719646/68190704-3039d680-ffae-11e9-93bf-99f22d35a628.png">

**Comment by roblourens** [comment]
That port is probably in use, please check.

**Comment by barcia** [comment]
No, the port is not in use.

I also try after a reboot.
<img width="535" alt="Captura de pantalla 2019-11-13 a las 13 24 22" src="https://user-images.githubusercontent.com/5719646/68763614-29980880-0619-11ea-8e87-65eab7190936.png">

If I create a tunnel manually with SSH, this works correctly.

**Comment by stldo** [comment]
I'm having the same problem. If I configure a port in settings.json, it's set to a random local port. But if I use the "Create New Forward" option, it works correctly.

**Comment by barcia** [comment]
Yes, with "Create New Forward" command also works for me.

**Comment by think2011** [comment]
Yes , I'm having the same problem.

**Comment by bonanov** [comment]
Same issue
I think new port is being assigned before old one manages to disconnect, as vscode reboots almost instantly

**Comment by qiaoxueshi** [comment]
Have this problem got resolved?

**Comment by barcia** [comment]
I don't know @XueshiQiao. In theory it was added for the next milestone.
The endgame of this iteration is planned for the next friday. We will see if is solved.

**Comment by roblourens** [comment]
It's shipped in the nightly extension.
