### ISSUE TITLE
Document the new 'extensionKind' semantics in 1.40

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#1787]
The extension kind was changed to an array so that richer semantics can be expressed. We made the change based on the observation that there are extensions that:
- can run **on both** the UI extension host AND the remote extension host
- can run **only** in the UI extension host and therefore do not run in the browser since there is no UI extension host.

The elements in the `extensionKind` array define the extension hosts where an extension can run. The elements of the array are:
- ui - the extension can run in the UI extension host (no access to the workspace needed)
- workspace - the extension can run in the remote/workspace extension host, must have workspace access.

Examples:
- settings sync, techer.openInBrowser:  `["ui"]`, runs in the UI extension host only
- peacock: `["ui", "workspace"]`, runs either in the UI extension host or the remote extension host, preference is the UI extension host.
- python: `["workspace"]`, runs only in remote extension host. This case is typically inferred automatically.

The documentation (for example [here](
https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location)) needs to be updated and we also want to migrate existing extensions that use the extension kind attribute.

//fyi @alexandrudima

**Comment by Chuxel** [comment]
Is the old value backwards compatible?

**Comment by egamma** [comment]
The old attribute is still supported.

**Comment by egamma** [comment]
Discussed with @Chuxel given the inertia in migrating the community, the proposal is to keep  it backward compatible and tolerate the old attribute.

**Comment by Chuxel** [comment]
@alexandrudima @egamma Quick follow up here - in the case of VSO's browser-based editor (aka VS Code Web), would an extension need to specify `["ui", "workspace"]` for it to work since there's only a remote extension host?  Put another way, is `"ui"` now specific to the VS Code client itself and the local extension host?

**Comment by egamma** [comment]
@Chuxel 

>VS Code Web), would an extension need to specify ["ui", "workspace"] for it to work since there's only a remote extension host? 

["workspace"] is sufficient for an extension to work in VS Code Web.

An extension that defines ["ui", "web"], will also work in VS Code Web. In VS Code desktop it would be loaded into the UI extension host since "ui" is the preference.

>Put another way, is "ui" now specific to the VS Code client itself and the local extension host?

Correct, an extension that has kind ["ui"] will only run when there is a 'UI extension host', which is only the case in VS Code desktop (both remote and local setups).

The new format of defining the extension kind enables us to introduce a kind "web" or "worker" when there is a web worker extension host.

**Comment by Chuxel** [comment]
Clarification added in https://github.com/microsoft/vscode-docs/pull/3235
