### ISSUE TITLE
Fails to show environments

### ISSUE THREAD

**Issue by brianlowe** [microsoft/vscode-remote-release#1788]
Issue Type: <b>Bug</b>

Follow the tutorial at https://docs.microsoft.com/en-us/visualstudio/online/quickstarts/vscode

Step 5 suggests right-clicking the environment name in the "VS Online" panel of "Remote Explorer" to call a context menu with the "Delete" option, but the current environment is not shown. Right-click has no effect.

VS Code pops up this error... "Error running command extension.refreshObjectExplorerNode: command 'extension.refreshObjectExplorerNode' not found. This is likely caused by the extension that contributes extension.refreshObjectExplorerNode."

Extension version: 0.81.1
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

**Comment by chrmarti** [comment]
@Chuxel How do we forward VSO / Cloud Env issues?

**Comment by Chuxel** [comment]
@chrmarti VSO issues should be logged at https://github.com/microsoftdocs/vsonline

Unfortunately it's in a separate org, so we can't transfer. @brianlowe I moved your issue to https://github.com/MicrosoftDocs/vsonline/issues/131 so please watch there for updates.  Thanks!
