### ISSUE TITLE
Cannot create directory '/home/root/.vscode-server': Read-only file system

### ISSUE THREAD

**Issue by thnk2wn** [microsoft/vscode-remote-release#1789]
If not already there, it'd be nice if there was a way to specify where VS Code attempts to create the `.vscode-server` folder. I'm attempting to connect to an IOT device for debugging and get the error:

`mkdir: cannot create directory '/home/root/.vscode-server': Read-only file system`

There are other paths that are writable but I don't see a way to configure VS code to write there instead.

I can probably create a symlink on the device and workaround but IOT devices (even test ones) will tend to be more locked down but it'd still be nice to remotely attach without too much hassle.

As an aside the error message in this case could potentially be more useful and the output parsing seems off.

![image](https://user-images.githubusercontent.com/120529/68215095-aa695b80-ffac-11e9-9644-09825737a11b.png)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/1836
