### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by ericschultz** [Microsoft/vscode-remote-release#179]
Where is the source code? I read the FAQ but VSCode is supposed to be an open source tool. So again, where is the source code?

**Comment by kieferrm** [comment]
Pls see https://code.visualstudio.com/docs/remote/faq#_why-arent-the-remote-development-extensions-or-their-components-open-source.

**Comment by ericschultz** [comment]
As mentioned in my first message, I read the FAQ. You're using GOBS of open source and promote VSCode as an open source tool. This is really uncool and anti-community.

**Comment by bhack** [comment]
@kieferrm I hope that "are not currently open-source" it is not, between the line, "never".
> This is because the VS Code Remote extensions are also used in fully managed remote development services 

I think nobody care about open-sourcing the full managed part of the code, so I hope that at some point you can separate the code useful to be released from the managed one.

**Comment by ericschultz** [comment]
@kieferrm Why would the container extension even use Microsoft services? I shouldn't have to use your services to work with containers on my own machine.

And while I would love if the managed part of the code was available, I don't see that as the major issue. Developing in a container is a MAJOR feature for developing code and it feels pretty anti-user for me to have to either use your services or have to use a proprietary license in your "open source" editor to do it.

**Comment by ericschultz** [comment]
Oh, I get what's going on: you're using this in your proprietary Visual Studio Online and you don't want anyone else to be able to do the same.

Glad my needs as a developer are so high on your list.

**Comment by bhack** [comment]
@ericschultz I understand you point but I don't think that a flame mode it is useful here. 
I think managed code could be proprietary and related to free or payed managed Microsoft services but could be separated for the others remote plugins features that not strictly involved in the managed services.
I hope the the team could do a claim about this topic as an outlook over the plugins cause if all the stuffs will stay embedded with managed services it will be hard to release any part of this plugins of general use.

**Comment by ericschultz** [comment]
@bhack to be clear, I'm not flaming. I expected that core features of VSCode would be open source and I've been telling people how great of an open source editor it was. As a community member, I feel pretty misled.
