### ISSUE TITLE
Add a notification when VS Code Remote - * is installed in VS Online

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#1791]
We are occasionally seeing people asking about using Remote - SSH in Visual Studio Online through various feedback channels.  I expect we'll likely see similar questions about Remote - Containers over time.

Visual Studio Online [has a self-hosting option](https://aka.ms/vso-docs/vscode/self-hosted) that is intended to meet a similar need to Remote - SSH but with internet web support (even if your machine only has outbound internet connectivity). Support for setting this up via the command line is planned. However, when running in VS Online's browser based editor, one might assume that the way to do this is to install Remote - SSH and set it up to connect to your machine - but this will not work and is not intended to work. 

Instead, I'd propose we detect this scenario and provide a notification pointing to the self-hosting option.

(Note that, when used from the VS Online extension for VS Code, you can only be connected to one remote at a time, so this problem does not exist - it's specific to the web experience.)

//cc: @kieferrm @roblourens @chrmarti

**Comment by chrmarti** [comment]
@alexandrudima Can the reworked `extensionKind` in the `package.json` be used to prevent installation of the resolver extensions in VSO?

**Comment by Chuxel** [comment]
@chrmarti @alexandrudima Possibly - if they're set to `"extensionKind": ["ui"]` (using an array).

I'm actually not sure what the user would see here - would it install and then fail to activate?

**Comment by egamma** [comment]
The extensionKind is now set to `["ui"]` and there is warning that it cannot be installed in the remote setup.
