### ISSUE TITLE
Remote Container: `ENOENT: no such file or directory, stat '/espresso.code-workspace'`

### ISSUE THREAD

**Issue by strass** [microsoft/vscode-remote-release#1792]
- VSCode Version: 1.40.0-insider
- Local OS Version: OS X 10.14.4 (18E226)
- Remote OS Version: python:3.7-buster
- Remote Extension/Connection Type: Remote-Container

Steps to Reproduce:

1. Use these devcontainer configs: https://gist.github.com/strass/70ede5f91e0e3fb8ab92da47fe9e085e
2. Start remote container. Container stdout says `ENOENT: no such file or directory, stat '/espresso.code-workspace'` and vscode doesn't mount my workspace. If I copy a fake workspace file `volumes: - ./fake.code-workspace:/espresso.code-workspace` then it mounts the workspace correctly but the relative paths get all messed up.

Let me know what I'm doing wrong!

**Comment by chrmarti** [comment]
Workspace files are supported with some limitations:
- They must contain relative paths.
- The devcontainer.json must be in the same folder.
- The workspace folders must be in a subfolder of the workspace file's folder.

With that, the container will be set up to have the workspace file's folder mounted and VS Code should open the entire workspace inside the container.

Does your setup match this? What's the folder layout you have and what's in the workspace file?

**Comment by strass** [comment]
ok so it looks like I have 2 issues: my workspace file contains relative paths and the devcontainer.json is in .devcontainer/ not the root.

```
.devcontainer\
  - devcontainer.json
  - docker-compose.yml
  - Dockerfile
espresso.code-workspace
```

workspace file:
```
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"typescript.tsdk": "Espresso/node_modules/typescript/lib"
	}
}
```

Is there a suggested fix that works for both local and container development? Do I create a 2nd workspace file for just the container?

Thanks!

**Comment by chrmarti** [comment]
If you have only a single folder, you can open that without a .code-workspace file and put the settings in `.vscode/settings.json` of the folder.

If you want to keep the .code-workspace file, you could move the devcontainer.json up and adjust the paths it contains.
