### ISSUE TITLE
Use container name in URI when attaching

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1794]
The container name is sometimes (Compose, user managed names) stable across containers.

**Comment by alexr00** [comment]
Verified by:
1. Creating a container, attaching, opening a folder.
2. Deleting the container
3. Making a container with the same name
4. Opening the recent entry that was created with step 1. ✔
Also confirmed that if I go to an older version of the containers extension and do step 1 and then update the extension then step 4 doesn't work.
