### ISSUE TITLE
Git stash fails 

### ISSUE THREAD

**Issue by SSmale** [microsoft/vscode-remote-release#1797]
- Version: 1.40.0-insider (user setup)
- Commit: a14de79ac74f2e0e6566d3cc9410eeb7dc769cde
- Date: 2019-11-02T00:39:42.595Z
- Electron: 6.1.2
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Windows_NT x64 10.0.17134
- Remote OS Version: CentOS 7.5
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.make a file change on remote
2. click the built in git stash btn from the git panel 
3. error log from git output
```
> git stash push
usage: git stash list [<options>]
   or: git stash show [<stash>]
   or: git stash drop [-q|--quiet] [<stash>]
   or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]
   or: git stash branch <branchname> [<stash>]
   or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet]
		       [-u|--include-untracked] [-a|--all] [<message>]]
   or: git stash clear
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
What version of Git do you have installed on the remote machine?

**Comment by SSmale** [comment]
1.8.3.1 on the remote 
2.22.0 on local

**Comment by joaomoreno** [comment]
Make sure you update the remote Git to a fresher version.

**Comment by SSmale** [comment]
Is there a min version @joaomoreno ?

**Comment by joaomoreno** [comment]
We do require 2 at least, there should've been a warning about that: https://github.com/microsoft/vscode/blob/7cadd81deecbba7c6c1b885b8c69710a708b5182/extensions/git/src/main.ts#L198
