### ISSUE TITLE
Colon in path when using IPv6 Address on Windows

### ISSUE THREAD

**Issue by Flashs** [microsoft/vscode-remote-release#1799]
- VSCode Version: 1.39.2
- Local OS Version: Windows 10.0.17134
- Remote OS Version: Any
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Try to connect to an IPv6 address like user@2001:0db8:85a3:0000:0000:8a2e:0370:7334

`Failed to write install script to path C:\Users\User\AppData\Local\Temp\vscode-linux-multi-line-command-2001:0db8:85a3:0000:0000:8a2e:0370:7334-271477451.sh. ENOENT: no such file or directory, open 'C:\Users\User\AppData\Local\Temp\vscode-linux-multi-line-command-2001:0db8:85a3:0000:0000:8a2e:0370:7334-271477451.sh'`

I assume the error occurs, because Windows does not allow colons ":" in filenames.

IPv6 Hostaddresses seem to work under Linux, although I just tested if I could connect to localhost over its IPv6 address.

**Comment by roblourens** [comment]
That's fun...

**Comment by roblourens** [comment]
Fixed with 138a9a3760fa59e0a329453daf5fc7200b53d629
