### ISSUE TITLE
Remote SSH - Following path in Debug Console

### ISSUE THREAD

**Issue by leomoty** [microsoft/vscode-remote-release#180]
- VSCode Version: 1.34.0-insider
- Local OS Version: Windows 10
- Remote OS Version: Fedora Server 29
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Tried to debug some code, error was dumped to debug console. Then I tried follow the library code (main.js) by ctrl + clicking.

2. Result:

```
Unable to open 'main.js': Unable to read file (Error: File not found (\home\leomoty\express-prince\node_modules\dotenv\lib\main.js)).
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Not applicable, I guess

**Minimal repro:**

```
const fs = require('fs');
fs.readFileSync('nonexisting');
```

It follows the file path properly under Terminal, but that is not the case for Debug Console.

**Comment by mfmayer** [comment]
I do have the same issue with go development. 
Probably some file path separator issue. The debug output states the path with "/" as separator. After clicking, the file not found popup states the file path with "\" as separator.

**Comment by kylrth** [comment]
I'm also seeing something similar with local Windows and remote Linux, when I click on a link in the problems pane:

```
Unable to open 'SourceFile.cpp': Unable to read file (Error: File not found (vscode-remote://ssh-remote+linux_box/home/user/workspace_directory/home/user/workspace_directory/path/to/SourceFile.cpp))
```

This occurred after running a task that had problem output matched by C/C++'s `gcc` problem matching. Let me know if I need to open a separate issue elsewhere.

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/62012547-88a24200-b13c-11e9-90a8-554f6e2e91d2.png)

@isidorn is it looking on the local side instead of the remote side?

**Comment by isidorn** [comment]
Yes it shuold look localy.
Code pointer https://github.com/Microsoft/vscode/blob/980ad1ce090d58fdac487ad376612ae6e2f23134/src/vs/workbench/contrib/debug/browser/linkDetector.ts#L14

**Comment by leomoty** [comment]
This seems to be fixed. 

![image](https://user-images.githubusercontent.com/1463740/66564620-cf49ea80-eb36-11e9-8ff5-e1f8a04213c3.png)


Version: 1.39.0 (user setup)
Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
Date: 2019-10-09T06:58:04.439Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
