### ISSUE TITLE
Make it easier to put an extension in my devContainer.json

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#1800]
Steps:
1. I set up a dev container config for a specific repo
2. I open the folder in the container
3. I mess around and get extension recommendations that I then install
4. They are now installed in the container but there isn't really a discoverable way to add this to the devContainer config.

**Comment by Chuxel** [comment]
One option would be to follow the pattern that @chrmarti did for the attach case where container extension adds modify the devcontainer.json file, but doesn't save it

**Comment by chrmarti** [comment]
Not sure we want to automatically add the extensions to the devcontainer.json by default because that would introduce a change to the user's repository. Maybe as an opt-in feature.

**Comment by sbatten** [comment]
As a user, I would expect that I could click something in the extensions viewlet to quickly add an extension to the dev container json

**Comment by chrmarti** [comment]
Alternatively we could install the extensions from the devcontainer.json the first time (imagine someone joining the project) and then track the user's extensions outside of devcontainer.json in the user data (imagine project members doing their own customizations).

Automatically updating devcontainer.json would be like automatically updating `.vscode/extensions.json` which we don't do for similar reasons I think.

**Comment by sbatten** [comment]
Understood that we should not update it automatically, and I like the idea you suggest @chrmarti but it is not the same problem I am looking to fix. I merely want a way to quickly add the extension to the devContainer.json from the UI.

Possible steps:
1. User creates a new project
2. User decides to re-open in dev container and chooses a template.
3. User installs a few extensions and wants these to always be part of the container.
4. (today) User looks in extension viewlet at container-installed extensions and has no way to do this quickly today.
(proposed) User looks in the extension viewlet at container-installed extensions and clicks the gear menu and selects `Add to devContainer.json`
