### ISSUE TITLE
Update remote settings when a setting from an extension that is running remotely is changed

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#1801]
Once in devContainer with python extension installed via the devContainer config, I get prompted that IntelliCode support for Python requires a change of setting. I click the action to change the setting but this changes it in user settings, where it should likely apply to the devContainer settings.

from @sandy081 
> This can apply to those settings owned by extensions running remotely. We can change the strategy to update in remote machine if the setting belongs to an extension running remotely.

**Comment by Eskibear** [comment]
I'm from https://github.com/joelspadin-garmin/vscode-private-extension-manager/issues/14 , which is marked as duplicated with this issue. 


#### My experiments
I tested both Codespaces and local dev containers. According to my experiments, both `machine` and `machine-overridable` are affected. When using below API to update settings, 
```ts
vscode.workspace.getConfiguration("foo").update("bar", "value", vscode.ConfigurationTarget.Global)
```

a) [**OK**] if `foo.bar` has already defined in your machine level settings.json
 * e.g. `/home/vscode/.vscode-server/data/Machine/settings.json` or `/home/codespace/.vscode-remote/data/Machine/settings.json`
 * new value is correctly updated inplace.  

b) [**Buggy**] if `foo.bar` is **NOT** explicitly defined in machine level settings.json
 * `"foo.bar":  "value"` is wrongly added in **user level settings.json**, the same as described in this issue, which I believe is an upstream bug.

**Comment by sandy081** [comment]
To verify:

- Write a sample extension that has a setting with scope `machine or `machine-overridable` and a command that executes following code
```
vscode.workspace.getConfiguration().update("setting", "value", vscode.ConfigurationTarget.Global)
```
- Install this extension on remote (You can use DevContainer and install as VSIX)
- Running above command shall update the setting in remote settings (Try when setting is written and not written in the file)
