### ISSUE TITLE
Cannot Use Source Control Installed from Perforce Extension

### ISSUE THREAD

**Issue by cyliang** [microsoft/vscode-remote-release#181]
- VSCode Version: 1.34.0-insider
- Local OS Version: Windows 10.0.17134
- Remote OS Version: CentOS7.1
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install extension **Perforce for VS Code** (`slevesque.perforce`)
2. Open a folder that is a perforce client.
3. Click the source control. It shows "`No source control providers registered`".

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Is third party source control extension supported in vscode-remote? Thank you.

**Comment by Chuxel** [comment]
@cyliang Can you Go to Help > Developer Tools, toggle developer tools, and copy any errors that exist in the Console here?

**Comment by cyliang** [comment]
Hi, the source control works now after I left the session opened for hours. Not sure what happened.
Thanks for your help.
