### ISSUE TITLE
my git config is not at ~/.gitconfig but at ~/.config/git/config

### ISSUE THREAD

**Issue by codekitchen** [microsoft/vscode-remote-release#1811]
- VSCode Version: 1.40.0
- Local OS Version: MacOS 10.15.1 Catalina
- Remote OS Version: Docker Desktop 2.1.0.4
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open any devcontainer
2. `git config -l` will not show your local user git config, and /root/.gitconfig does not exist
3. Or do a `git commit` and see that your username/email are not configured

Basically, my user's git configuration on MacOS is stored at `$HOME/.config/git/config` rather than at `$HOME/.gitconfig`, and it seems like the remote containers extension is not finding the config at that location. I'm using MacOS built-in git version 2.21.0 (Apple Git-122.2).

**Comment by chrmarti** [comment]
Note to self: https://git-scm.com/docs/git-config#Documentation/git-config.txt-XDGCONFIGHOMEgitconfig
