### ISSUE TITLE
Allow choosing different docker files to build the devcontainer

### ISSUE THREAD

**Issue by TravisEz13** [microsoft/vscode-remote-release#1819]
Allow choosing different docker files to build the devcontainer

Our tests and packaging behave differently on different distributions.  Particularly between Debian and Redhat.  Please let us have two configs and choose which one to use for the whole repo.

**Comment by bamurtaugh** [comment]
Thanks for opening this issue @TravisEz13! I believe this is along the lines of https://github.com/microsoft/vscode-remote-release/issues/1165. If you agree, I'll go ahead and close this thread to better consolidate discussion in one location.

**Comment by TravisEz13** [comment]
Agreed.
