### ISSUE TITLE
Cannot move folder with files

### ISSUE THREAD

**Issue by Guoshiqi0830** [microsoft/vscode-remote-release#1822]
Issue Type: <b>Bug</b>

## steps to reproduce
1. open a project
2. create a folder
3. create a file in this folder
4. move this folder to another folder

## error message
Error: EACCESS: permission denied, rename 'xxx' -> 'xxxxx'

## expected results
can move the floder successfully

Extension version: 0.40.2
VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|Memory (System)|15.84GB (8.43GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
What are the permissions on the target folder you want the folder to move to?

**Comment by Guoshiqi0830** [comment]
It's 777.  I cannot use mv in WSL when vscode is open. The error message is also permission denied.
![image](https://user-images.githubusercontent.com/39219120/68650814-dfebe700-0560-11ea-8c0e-0eb73970d449.png)

**Comment by chrmarti** [comment]
Does it work when VS Code is not open? What is the user and group ownership on the target folder?

**Comment by Guoshiqi0830** [comment]
It worked when VS Code is not open. The user and group are default user and group in WSL.
![image](https://user-images.githubusercontent.com/39219120/68651950-69041d80-0563-11ea-80a6-ce5259351e8a.png)

**Comment by aeschli** [comment]
See https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace
