### ISSUE TITLE
Lost connection after opening large file

### ISSUE THREAD

**Issue by forrestjacobs** [microsoft/vscode-remote-release#1824]
Issue Type: <b>Bug</b>

## Steps to reproduce
1. Download and extract the KANJIDIC2 XML file (see https://www.edrdg.org/wiki/index.php/KANJIDIC_Project for a description) on a remote machine by doing something like `curl http://www.edrdg.org/kanjidic/kanjidic2.xml.gz | gunzip > kanjidic2.xml`.
2. Open the file in VS Code using SSH remote extension

## Expected results
Either the file opens and works as expected or, if it cannot, there's an error message explaining what's happening and the file is not opened

## Actual result
The file opens and you can edit as normal for a few seconds, but then a modal "Attempting to reconnect..." window appears followed by "Cannot reconnect. Please reload the window."

Extension version: 0.47.2
VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.19018
Remote OS version: Linux x64 4.9.0-11-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3410)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (3.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: stand|
|OS|Linux x64 4.9.0-11-amd64|
|CPUs|Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz (1 x 2299)|
|Memory (System)|0.97GB (0.22GB free)|
|VM|0%|
</details>

**Comment by mcswell** [comment]
Is this the same bug as https://github.com/microsoft/vscode-remote-release/issues/1087?  The symptoms forrestjacobs reports here are the same as what I've seen when trying to sftp large files, and I put a "me too" note on the 1087 bug report.

**Comment by forrestjacobs** [comment]
@mcswell Reading through the thread, it sounds like the same bug (or at least the experience described matches with mine.)

**Comment by alexdima** [comment]
:+1: Let's track in #1087
