### ISSUE TITLE
Can not confiure debug usin GDB over Remote SSH

### ISSUE THREAD

**Issue by sploid** [microsoft/vscode-remote-release#1825]
Hi all.

I have connected to Linux using Remote SSH connection and written very simple app:
```#include <cstdio>
int main () {
    int n = 4;
    printf (" Initial value of n is %d \n", n);
    return 0;
}
```

I have written launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "gdb",
            "request": "launch",
            "name": "gdb",
            "program": "demo",
            "cwd": "/home/centos/soft/demo",
            "showDevDebugOutput": true
        }
    ]
}
```

I press F5 and see that debugger tries to start and looks like its started.
But I do not see running 'demo' process.
Questions:
1. What information do you need to diagnose the problem?
2. What am I doing wrong?
3. Where can I find logs of the work with gdb?

**Comment by roblourens** [comment]
Please file this on the repo for the debug extension you are using
