### ISSUE TITLE
Disable "attach" contribution on Docker containers when not running as a UI extension

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#1826]
EDIT: Bumped submit

It appears sometime recently the Docker extension got updated to a workspace extension.  This means that our docs are wrong, and if someone connects to a remote host, the "attach to container" gesture won't work as expected.

The previous default was UI which didn't cause these problems.

I've already removed references to the Docker extension for the attach scenario with the introduction of the remote explorer in docs given there are added features (like workspace folder location), but there are other places that will need to be updated.

https://github.com/microsoft/vscode-dev-containers/pull/143 modifies the needed devcontainer.json files for docker scenarios.

//cc: @chrmarti @egamma

**Comment by chrmarti** [comment]
We need to look into removing the Attach to VS Code context menu entry when the Docker extension is running remotely and might want to ignore a `docker.host` setting in that case.

**Comment by Chuxel** [comment]
Docs are now updated, leaving open for adjusting the "Attach" context menu item.

**Comment by egamma** [comment]
@Chuxel 

>It appears sometime recently the Docker extension got updated to a workspace extension. 

What makes you conclude this? We still classify the docker extension as a UI extension in the product.json

![image](https://user-images.githubusercontent.com/172399/69139423-bf6fdf80-0ac0-11ea-91bd-4b918531bc4f.png)

This is also confirmed in the extensions viewlet:
![image](https://user-images.githubusercontent.com/172399/69139569-0f4ea680-0ac1-11ea-883e-31261113b5f1.png)

**Comment by egamma** [comment]
@Chuxel we still want to run the docker extension as UI extension to avoid the breakage you describe. We will make the code changes accordingly.

The docker extension should change the `extensionKind` from "workspace" to ["workspace", "ui"].
