### ISSUE TITLE
.gitignore doesn't propagate changes in VS code

### ISSUE THREAD

**Issue by michalmar** [microsoft/vscode-remote-release#183]
Issue Type: <b>Bug</b>

When I have remote directory versioned by git and I change the remote .gitignore file to exclude certain files/folders -> VS Code doesn't update the git view accordingly, still displays files in excluded folder as modified/untracked.

Extension version: 0.35.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.15.0-1041-azure

**Comment by joaomoreno** [comment]
@bpasero Have you seen missing file change events?

**Comment by bpasero** [comment]
@joaomoreno we are using the exact same file watcher as locally (in this case since it is Linux it should be chokidar), but it is quite possible that the remote does not report file events properly to us.

**Comment by joaomoreno** [comment]
Any way the user can debug that?

**Comment by bpasero** [comment]
@aeschli is it possible to set a logging level on the remote server to see file events appearing in the logs?

**Comment by aeschli** [comment]
@bpasero That used to work when the watcher was part of the remote ext host. Sorry, don't know if that's still the case

**Comment by bpasero** [comment]
@aeschli is it possible to set a logging level on the remote server ?

**Comment by aeschli** [comment]
`Set Log Level` command now also works for the remote file watcher

**Comment by joaomoreno** [comment]
@michalmar Can you still reproduce this?

**Comment by michalmar** [comment]
No, probably  fixed with some update.
