### ISSUE TITLE
Attach to process: cannot put process '18' in debug mode.

### ISSUE THREAD

**Issue by siddjain** [microsoft/vscode-remote-release#1834]
Issue Type: <b>Bug</b>

Try to debug Node.js running in a local docker container and using `Attach by Process ID` configuration of VS Code. The Node.js process in question is the `fabric-chaincode-node` process

```
{
            "type": "node",
            "request": "attach",
            "name": "Attach by Process ID",
            "processId": "${command:PickProcess}",
            "skipFiles": [
                "<node_internals>/**"
            ]
        }
```

Expected
=======
debugger to attach

Observed
=======
Attach to process: cannot put process '18' in debug mode.

Details
=====
```
$ docker exec -it fabricvscodelocalfabric-peer0.org1.example.com-boilerplate-contract-0.0.1 /bin/bash
root@018f157e21b4:/# ps -ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /bin/sh -c cd /usr/local/src; npm start -- --peer.address peer0.org1.example.com:17052
    7 ?        Sl     0:00 npm
   17 ?        S      0:00 sh -c fabric-chaincode-node start "--peer.address" "peer0.org1.example.com:17052"
   18 ?        Sl     0:01 node /usr/local/src/node_modules/.bin/fabric-chaincode-node start --peer.address peer0.org1.example.com:17052
  122 ?        Ss     0:00 sh /root/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/server.sh --disable-user-env-probe --port 0
  129 ?        Sl     0:01 /root/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/node /root/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/main.js --disable-user-env-probe --port 0
 2526 pts/0    Ss     0:00 /bin/bash
 2541 pts/0    R+     0:00 ps -ax
```

```
root@018f157e21b4:/# netstat -tuplen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 127.0.0.11:40701        0.0.0.0:*               LISTEN      0          20210       -
tcp        0      0 127.0.0.1:9229          0.0.0.0:*               LISTEN      0          38439       18/node
tcp6       0      0 :::38849                :::*                    LISTEN      0          28008       129/node
udp        0      0 127.0.0.11:41393        0.0.0.0:*                           0          20209       -
```

Extension version: 0.83.0
VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.9.184-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Attached Container fabricvscodelocalfabric-peer0.org1.example.com-boilerplate-contract-0.0.1-4ab1c1f65a9abbbe060294b3810280889f3bdb1fa9d9c5a8c465cd02c43b917e (fabricvscodelocalfabric-peer0.org1.example.com-boilerplate-contract-0.0.1)|
|OS|Linux x64 4.9.184-linuxkit|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (6 x 2200)|
|Memory (System)|1.95GB (0.51GB free)|
|VM|0%|
</details>

**Comment by weinand** [comment]
@siddjain are you using the "Remote Development" and "Remote Container" extensions to run VS Code inside the container?

**Comment by siddjain** [comment]
Yes i am using those extensions but i am attaching vs code debugger to running process in docker container

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by siddjain** [comment]
attaching screenshot
<img width="438" alt="Screen Shot 2019-11-12 at 3 28 39 PM" src="https://user-images.githubusercontent.com/758321/68808656-0ec89280-061f-11ea-853a-a27a5f4ebcd5.png">

**Comment by siddjain** [comment]
ping. any update on this? here is a video showing the repro steps: https://youtu.be/1qVOKwjpHZI
any help appreciated.

**Comment by siddjain** [comment]
@weinand any update? please see video I have uploaded to youtube showing the problem: https://youtu.be/1qVOKwjpHZI

**Comment by weinand** [comment]
This error message means that we cannot determine what debug port and/or protocol the node process is using which is usually an indication that we could not put the process into debug mode after it was started.

Could you try to start the node process you are interested in with an argument like `--inspect=9229`. In this case the process picker knows already the debug port.
