### ISSUE TITLE
Add a configuration to change where the .vscode-server folder is created.

### ISSUE THREAD

**Issue by DedicatedManagers** [microsoft/vscode-remote-release#1836]
I am trying to use this extension with a Cloudways server.  Unfortunately users cannot create directories in their home directory, which appears to be where this extension is trying to create the .vscode-server directory.  I'd like to be able to change where that directory is created to a folder where the user is able to create a directory.

![vscode](https://user-images.githubusercontent.com/314076/68724548-bdfa6080-0570-11ea-8090-e08a6e606fd9.PNG)

**Comment by DedicatedManagers** [comment]
![image](https://user-images.githubusercontent.com/314076/68724657-fbf78480-0570-11ea-8699-aff08dcc8ebf.png)

**Comment by vict0rsch** [comment]
Having the same exact issue here (for another reason: on our HPC the home directory is not the best way to store this kind of process)!

**Comment by bersbersbers** [comment]
Related: #1639

**Comment by roblourens** [comment]
> Unfortunately users cannot create directories in their home directory, which appears to be where this extension is trying to create the .vscode-server directory.

That's surprising. Out of curiosity, where are you expected to store user data?

**Comment by DedicatedManagers** [comment]
They told me to use the private_html directory.  But I'd think for this use, I would point it towards the tmp directory.

**Comment by DedicatedManagers** [comment]
@roblourens Has this been implemented yet?

**Comment by tanhakabir** [comment]
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/472
