### ISSUE TITLE
VS code on Windows Desktop to login remote linux ssh host with non-passwd rsa key required login password

### ISSUE THREAD

**Issue by shaoxul** [microsoft/vscode-remote-release#1837]
Procedures:
1. create a rsa key in cygwin without a password:
    ssh-keygen -t rsa -P ""
2. copy the rsa pub key to remote linux
    ssh-copy-id server
3. create ssh config file
Host myusername@myhostIP
  ForwardAgent yes
  IdentityFile C:/Cygwin_ENV/cygwin64/home/username/.ssh/id_rsa
4. connect the remote host with the configuration file in 3

Expect:
4. will login successfully without requesting password of login-psw or sshkey-psw.

Actual:
4. will request to input the ssh key password. (if press Enter key in blank input box, it will pop up the login-password request for remote linux)

P.S.  in step 4, VS code on linux works as expected to connet a remote linux host.

====
CPUs	Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)
GPU Status	2d_canvas: enabled
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
multiple_raster_threads: enabled_on
native_gpu_memory_buffers: disabled_software
oop_rasterization: disabled_off
protected_video_decode: unavailable_off
rasterization: enabled
skia_deferred_display_list: disabled_off
skia_renderer: disabled_off
surface_synchronization: enabled_on
video_decode: enabled
viz_display_compositor: disabled_off
webgl: enabled
webgl2: enabled
Load (avg)	undefined
Memory (System)	15.87GB (6.36GB free)
Process Argv	
Screen Reader	no
VM	0%
===
Remote	SSH: **.**.**.**
OS	Linux x64 4.15.0-60-generic
CPUs	Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (8 x 2197)
Memory (System)	31.41GB (0.61GB free)
VM	100%

**Comment by roblourens** [comment]
Does it work as expected if you just run `ssh <your host>` in an external terminal?

Does it work if you set `remote.SSH.path` to the cygwin ssh executable?

**Comment by shaoxul** [comment]
> Does it work as expected if you just run `ssh <your host>` in an external terminal?
Yes.
ssh mylin_name@10.199.114.65 -i /cygdrive/c/Users/mywin_name/.ssh/id_rsa
This private cert `id_rsa` is created without passphrase. And this line command work to login without any further authorization request.


> Does it work if you set `remote.SSH.path` to the cygwin ssh executable?
I set `remote.SSH.path`, now. But it still request for 'Enter passphrase for ssh key'.
There is no 'passphrase' for my key, so I press enter directly. But the extension skipped my ssh key and request for my remote login password.

I think, the point is that, if no 'passphrase' in the ssh key, the extension will ignore the key and use username/password instead.

**Comment by shaoxul** [comment]
[02:15:32.756] SSH Resolver called for host: mylinname@mydevhost
[02:15:32.756] Setting up SSH remote "mydevhost"
[02:15:32.800] Using commit id "f359dd69833dd8800b54d458f6d37ab7c78df520" and quality "stable" for server
[02:15:32.803] Testing ssh with C:\Cygwin_ENV\cygwin64\bin\ssh.exe -V
[02:16:06.192] ssh exited with code: 0
[02:16:06.192] Got stderr from ssh: OpenSSH_7.9p1, OpenSSL 1.0.2p  14 Aug 2018
[02:16:06.193] Using SSH config file "C:\Users\mywin_name\.ssh\config"
[02:16:06.193] Running script with connection command: "C:\Cygwin_ENV\cygwin64\bin\ssh.exe" -D 60168 -F C:\Users\mywin_name\.ssh\config mylinname@mydevhost bash
[02:16:06.195] Install and start server if needed
[02:16:06.339] > 
[02:16:06.340] Got some output, clearing connection timeout
[02:16:08.233] > Enter passphrase for key '/home/mycygwin_name/.ssh/id_rsa':

The problem is:

> [02:16:06.192] Got stderr from ssh: OpenSSH_7.9p1, OpenSSL 1.0.2p  14 Aug 2018

Error occurred.

> [02:16:08.233] > Enter passphrase for key '/home/mycygwin_name/.ssh/id_rsa':

Fallback to use my cygwin  key, which created with passphrase.

I tried the command:
> [02:16:06.193] Running script with connection command: "C:\Cygwin_ENV\cygwin64\bin\ssh.exe" -D 60168 -F C:\Users\mywin_name\.ssh\config mylinname@mydevhost bash
[02:16:06.195] Install and start server if needed

It does not work.

But if I remove the `bash` parameter, then it works.
> "C:\Cygwin_ENV\cygwin64\bin\ssh.exe" -D 60168 -F C:\Users\mywin_name\.ssh\config mylinname@mydevhost

**Comment by roblourens** [comment]
It's using a different key. You are manually specifying the identity file when you do `ssh -i...` you need to add that to an ssh config so vscode can use the right key.
