### ISSUE TITLE
"Docker extension recommended for this file type" with only a Dart file open in remote session

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode-remote-release#1838]
I'm using today's Insiders and have a Flutter project open in a remote Docker container with a single Dart file open:

<img width="1059" alt="Screenshot 2019-11-06 at 9 38 54 am" src="https://user-images.githubusercontent.com/1078012/68286602-4496d580-0079-11ea-9e45-64f7acc24b6d.png">

When I opened it, I got an unexpected recommendation for the Docker extension. There is certainly a Dockerfile in the `.devcontainer` folder, but it's not open.

If I run the **Reload Window** then the recommendation reappears:

<img width="1059" alt="Screenshot 2019-11-06 at 9 39 57 am" src="https://user-images.githubusercontent.com/1078012/68286688-6b550c00-0079-11ea-93ae-01eb116abd22.png">

It's not clear whether VS Code has the notification is being triggered by the Dockerfile in the devcontainer folder, or whether VS Code has decided the Docker extension is good for editing Dart (I'm not sure how to check that).

**Comment by chrmarti** [comment]
Fixed as a side-effect of #1528. Verify separately.
