### ISSUE TITLE
Drag and drop from remote to Windows explorer not working

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode-remote-release#1839]
- VSCode Version: 1.40.0-insider (a14de79)
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Drag a file from the VS Code remote explorer to an explorer window
2. Nothing happens

Using right-click "Download" works fine.

I noticed an odd log output. When drag and dropping, a new line `[13:08:52.512] [Forwarding server 51605] Got connection 32` appears, each time. When using "Download" this doesn't happen.

Also, note that this was working in the past (one or two VS Code releases back).

Dragging the other direction (from explorer to VS Code) works fine.

**Comment by isidorn** [comment]
Actually same underlying limiation as https://github.com/microsoft/vscode-remote-release/issues/1149
Thus closing as duplicate
