### ISSUE TITLE
Improve log window Remote-SSH

### ISSUE THREAD

**Issue by lars18th** [microsoft/vscode-remote-release#184]
Hi,

I don't know why someother has not commented this before. But I feel at time it's quite complicated to see _ALL_ logs of the remote connection. I prefer to have the option of changing automatically to the log window (in the main window and in the new window) with _all_ commands executed by the plugin, in the client and in the server. The current behaviour is quite annoying and difficult to use.

I hope you like to consider it.

**Comment by roblourens** [comment]
We don't watch the server's log file, so it's not straightforward for us to include those logs. And it typically doesn't have any useful info. Is that what you're referring to, or what else are you missing?
