### ISSUE TITLE
Incorrect pre-filled folder name when "Download"ing a folder

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode-remote-release#1840]
- VSCode Version: 1.40.0 insiders
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Right-click on a folder in the VS Code remote explorer and select "Download"
2. The input field contains the folder name of the parent folder of the opened workspace folder, no matter which folder is selected.

**Comment by isidorn** [comment]
This should be fixed via https://github.com/microsoft/vscode/commit/414e916750d741055e3c966a3f4735072a0893ab
Please check it out and let me know how ti behaves
