### ISSUE TITLE
WSL: ARM not supported in stable

### ISSUE THREAD

**Issue by ericvh** [microsoft/vscode-remote-release#1842]
ERROR: Failed to download https://update.code.visualstudio.com/commit:86405ea23e3937316009fc27c9361deee66ffbf5/server-linux-arm64/stable to /home/erivan01/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5-1573667969.tar.gz

**Comment by ericvh** [comment]
as additional clarification, this is WSL2 on top of Arm Surface Pro X.

**Comment by aeschli** [comment]
Currently ARM64 in WSL is in preview and limited to insiders.
I will add a message to the WSL log.

**Comment by Chuxel** [comment]
@aeschli Is ARM64 WSL going to stay in insiders with 1.41 or move to stable (still in preview like Alpine)?

**Comment by aeschli** [comment]
It will be available for stable 1.41 as preview.
I already made the changes in the Remote WSL extension.
