### ISSUE TITLE
Extension stopped working with last update

### ISSUE THREAD

**Issue by Matheus-Mello** [microsoft/vscode-remote-release#1843]
Issue Type: <b>Bug</b>

Remote Explorer is not working after VS Code last update.
I was using it normally yesterday and today, after updating VS, I cannot log in into the server I was logging in yesterday

Extension version: 0.47.2
VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 7, 7|
|Memory (System)|8.00GB (0.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
Are you using SSH, Containers, or WSL? Do you have a screen shot or gif of the the remote explorer behavior you're seeing?

**Comment by Matheus-Mello** [comment]
I'm using SSH.

![Trim VSCode](https://user-images.githubusercontent.com/31036599/69184888-547fd200-0adb-11ea-985a-ea146d550c59.gif)

**Comment by alexr00** [comment]
Looks like this is a problem with connecting to an SSH remote, not with the remote explorer UI. @roblourens over to you!

**Comment by roblourens** [comment]
Can you share the log?
