### ISSUE TITLE
remote-wsl: allow some way to use Windows git for git repo

### ISSUE THREAD

**Issue by ericblade** [microsoft/vscode-remote-release#1844]
I've been digging around for a little while to figure out if there's a way to do this, and I can't seem to find anything, short of altering my WSL .bashrc to force git commands to remap to git.exe .. which isn't exactly preferable.

situation: my WSL installation cannot talk to my work VPN.  Windows can.  Therefore, I'd like to be able to use git.exe in Windows as my git client for remote-wsl folders.

**Comment by letmaik** [comment]
I usually use the git from WSL but then configure the credential helper to use the one from Windows. See also: https://www.edwardthomson.com/blog/git_credential_manager_with_windows_subsystem_for_linux.html

**Comment by ericblade** [comment]
I don't have this problem anymore, as I don't have a VPN that I need to deal with anymore, but although that's a useful thing to have, it doesn't help the problem as stated above.

**Comment by aeschli** [comment]
Closing based on last comment from @ericblade. We currently have no plans to work on this.
