### ISSUE TITLE
Failed to start container

### ISSUE THREAD

**Issue by unfalln** [microsoft/vscode-remote-release#1845]
Issue Type: <b>Bug</b>

VS-Code 1.40.0
OS: Ubuntu 19.10 (Linux x64 5.3.0-23-generic snap)
Docker: 19.03.4
Docker-compose: 1.22.0

I have a project that uses a .devcontainer/docker-compose.yml file to create a stack of containers attached to vscode for a project I'm developing. When I "re-open in container" on my Windows 10 machine at home, the project builds and starts fine, and when I manually run `docker-compose up` on my work Ubuntu machine the services start and I can manually attach vscode to the container I want. But when I use "Re-open in container" on my Ubuntu machine, vscode's automatic build cannot proceed past the command `docker-compose -f <...> config --services` as it gives the error "Service '<service>' configured in devcontainer.json not found in Docker Compose configuration.". When I manually execute `docker-compose -f <...> config --services` it lists the containers in the stack as expected.

The project is clearly set up correctly because I can move to a different machine and run it well, but it just seems there is some sort of context when running in Ubuntu that prevents docker-compose from listing the services correctly when invoked by vscode.

Extension version: 0.83.1
VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T18:14:08.920Z)
OS version: Linux x64 5.3.0-23-generic snap
Remote OS version: Linux x64 5.3.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (4 x 3462)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.54GB (7.71GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Attached Container cairnsholidayspecialists_bra_app (cairnsholidayspecialists_bra_app_1)|
|OS|Linux x64 5.3.0-23-generic|
|CPUs|Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (4 x 3462)|
|Memory (System)|15.54GB (7.71GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
What do you have set as the "service" in your devcontainer.json?

**Comment by unfalln** [comment]
In the case I was working on at the time I reported it, it was set to "app", but I'll see if I can find/build a simple example docker-compose project that reproduces the issue when I get to work in a couple hours.

**Comment by unfalln** [comment]
Many, many apologies, it turns out I had installed the snap of docker side-by-side with the default docker install, but the default install does not provide `docker-compose` which meant that, in most environments, docker-compose was connected to the snap version of the engine, where the rest of the cli was connected to the default install.

Uninstalling the snap version of docker and using https://github.com/docker/compose/releases instructions to manually install docker-compose fixed the issue.
