### ISSUE TITLE
Use other theme when inside on container

### ISSUE THREAD

**Issue by kostaspapad** [microsoft/vscode-remote-release#1846]
I would be nice to have the option to change vscodes theme when inside the container.

**Comment by Chuxel** [comment]
@kostaspapad Great news!  You can do that now thanks to container specific settings.  https://code.visualstudio.com/docs/remote/containers#_container-specific-settings 
 `"workbench.colorTheme"` is the settings.json property you'd set.

**Comment by aeschli** [comment]
Closing.  https://github.com/microsoft/vscode-remote-release/issues/1846#issuecomment-553926893 is the solution.
