### ISSUE TITLE
VS Code Remote Development behind HTTP-Proxy

### ISSUE THREAD

**Issue by DeadRabbits307** [microsoft/vscode-remote-release#1849]
I'm working behind a HTTP-Proxy. Like stated [here](https://github.com/microsoft/vscode-remote-release/issues/15#issue-439763137) 
 **update.code.visualstudio.com** and  
 **marketplace.visualstudio.com**
are set on the Whitelist of the proxy. After a lot of debugging I recognized the downloading of vscode-server with wget (utilizing update.code.visualstudio.com), there is a HTTP302 redirect to 
**https://az764295.vo.msecnd.net/stable/6ab598523be7a800d7f3eb4d92d7ab9a66069390/vscode-server-linux-x64.tar.gz**
which isn't on the whitelist and therefore the download fails. This is very(!) annoying because a lot of time was wasted and I cannot use remote-ssh now behind the proxy.

Therefore: Putting the vscode-server back onto update.code.visualtudio.com would be very pleasent. Is this desire placed here right?

**Comment by roblourens** [comment]
We recently added that hostname to our list of hostnames here https://code.visualstudio.com/docs/setup/network. FYI @joaomoreno
