### ISSUE TITLE
the remote extension installed in Docker containers can be cached

### ISSUE THREAD

**Issue by xinyanmsft** [microsoft/vscode-remote-release#185]
I experimented with VSCode remote with Docker container on C# code. Both with attach to container or create container, it takes quite some time to download the extensions into the remote container.

You guys may consider allow the container mount a directory from host such as ~/.vscode/extensions/* from to use as a cache. If the extension <foo> can be loaded from there, use it. otherwise download to that cache location so it can be used in the future.

**Comment by bhack** [comment]
I've supposed something similar about the K8S case at https://github.com/microsoft/vscode-remote-release/issues/12#issuecomment-489054995. /cc @chrmarti

**Comment by maniacmurphy** [comment]
I have been using the remote container development for a lot of work for the last few months lately.  When I have to rebuild my dev container the longest part is always installing the extensions at the end. I usually use between 2-5 extensions that have to be installed in the container but they are the same extensions, and the same ones I use when I am not developing using containers. 

The output doesn't say it but I suspect it is downloading each time. So this would be a great feature for me

**Comment by chrmarti** [comment]
Implemented as #2227.
