### ISSUE TITLE
Downloading a remote file from explorer does not overwrite a local file with the same name when there is no extension in the filename.

### ISSUE THREAD

**Issue by range4life** [microsoft/vscode-remote-release#1851]
- VSCode Version: 1.40
- Local OS Version: Windows 10 enterprise 10.0.18363
- Remote OS Version: Ubuntu 18.04 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Create a file on local named "testfile" (no extension).
2. Connect to remote SSH server and open a folder
3. Right click a file in the explorer and click download. Click on your local testfile and overwrite it through this download menu (Save as type: All Files)
4. Observe that the contents on local haven't actually been overwritten

Repeating the above steps with the file named "testfile.txt", the overwrite actually occurs.

**Comment by isidorn** [comment]
I am using the [`fileService.copy`](https://github.com/Microsoft/vscode/blob/66f6fe0f547c9cb41fe4e2f04a4b4f479baf92a6/src/vs/workbench/contrib/files/browser/fileActions.ts#L997)
I could pass the `overwrite` flag but that is not what I want. I would expect the fileService to find a new name and copy without overwriting.

**Comment by bpasero** [comment]
@isidorn 

>  I would expect the fileService to find a new name and copy without overwriting.

The file service is not the right place for that, it takes a path and does something with it, but will not start to come up with new file names if there is a conflict. You will have to come up with a filename from the outside if there is a conflict.

**Comment by isidorn** [comment]
Ok, so the `download` would have to do something similar to the copy.
Would have to check if there are overwrites and come up with a new name.
Marking as a feature request for now and we can tackle in the future.

**Comment by Christilut** [comment]
Same problem here but occurs with file extension. Tried it on multiple files and filetypes.

VSCode 1.40.2

**Comment by JenChampagne** [comment]
Same here. I was attempting to download a local copy of a build artifact through SSH remote, and couldn't understand my results at all until I realised that the file transfer was refusing to overwrite despite the dialog which asked me to confirm that I want to overwrite.

**Comment by isidorn** [comment]
Fixed via https://github.com/microsoft/vscode/commit/50124ae2b8ba52af773f27a31c7d59056b217540

**Comment by range4life** [comment]
Thanks for the fix :) looking forward to the release

there is also a slight issue (i won't create a thread for it) that is related tangentially
i tried to workaround this by just deleting the dest file instead of overwriting and i noticed that if i delete the file through the download window, and then click download, it will still ask me if i want to overwrite the (now nonexistent) file. Very minor issue most likely, but thought I'd mention it.
