### ISSUE TITLE
Remote-SSH Cannot connect to Windows Datacenter 2019 (Hosted on AWS) from Mac OSX

### ISSUE THREAD

**Issue by mattemoore** [microsoft/vscode-remote-release#1854]
- VSCode Version:  1.41.0-insider
- Local OS Version:  macOS Catalina 10.15.1
- Remote OS Version: Windows Server 2019 Datacenter 10.0.17763 (**Hosted on AWS**)
- Remote Extension/Connection Type: Remote-SSH 0.47.2 / Remote-Development 0.47.2

Steps to Reproduce:

1.  Install OpenSSH server on remote windows OS following steps found here: https://winscp.net/eng/docs/guide_windows_openssh_server
2.  Enable inbound SSH connection via AWS Security Group
3.  Create new SSH connect as per Remote-SSH extension documents
4.  Connection successful but architecture rejected:

> [09:48:39.025] remote-ssh@0.47.2
> [09:48:39.025] darwin x64
> [09:48:39.027] SSH Resolver called for "ssh-remote+ec2-18-212-254-80.compute-1.amazonaws.com", attempt 1
> [09:48:39.028] SSH Resolver called for host: ec2-18-212-254-80.compute-1.amazonaws.com
> [09:48:39.028] Setting up SSH remote "ec2-18-212-254-80.compute-1.amazonaws.com"
> [09:48:39.043] Using commit id "bf7d03bf88732af0b46e473c663c49e18e839f9c" and quality "insider" for server
> [09:48:39.045] Testing ssh with ssh -V
> [09:48:39.086] ssh exited with code: 0
> [09:48:39.086] Got stderr from ssh: OpenSSH_7.9p1, LibreSSL 2.7.3
> [09:48:39.089] Running script with connection command: ssh -T -D 58957 -o ConnectTimeout=15 ec2-18-212-254-80.compute-1.amazonaws.com bash
> [09:48:39.089] Install and start server if needed
> [09:48:39.512] > The authenticity of host 'ec2-18-212-254-80.compute-1.amazonaws.com (18.212.254.80)' can't be established.
> > ECDSA key fingerprint is SHA256:mJDhYOGyvVRMlnvf00HweLEozprdmJnsr217oG8FYCg.
> > Are you sure you want to continue connecting (yes/no)? 
> [09:48:39.512] Got some output, clearing connection timeout
> [09:48:39.513] Detected fingerprint confirmation message
> [09:48:39.513] Showing fingerprint confirmation dialog
> [09:48:43.462] Got fingerprint response: yes
> [09:48:43.463] "install" wrote data to terminal: "yes"
> [09:48:43.472] > yes
> > Warning: Permanently added 'ec2-18-212-254-80.compute-1.amazonaws.com,18.212.254.80' (ECDSA) to the list of known hosts.
> [09:48:43.794] > Administrator@ec2-18-212-254-80.compute-1.amazonaws.com's password: 
> [09:48:43.795] Showing password prompt
> [09:48:53.284] Got password response
> [09:48:53.284] "install" wrote data to terminal: "********************************"
> [09:48:53.293] > 
> [09:48:53.718] > 2809d3707d76: running
> > **Unsupported architecture: MINGW64_NT-10.0 x86_64**
> > 2809d3707d76##27##
> [09:48:53.972] "install" terminal command done
> [09:48:53.972] Install terminal quit with output: 2809d3707d76##27##
> [09:48:53.973] Received install output: 2809d3707d76##27##
> [09:48:53.973] Unsupported architecture
> [09:48:53.973] Resolver error: The remote host's architecture is not supported
> [09:48:53.976] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"ExitCode","askedPw":"1","askedPassphrase":"0","asked2fa":"0","askedHostKey":"1","gotUnrecognizedPrompt":"0","remoteInConfigFile":"1"},"measures":{"resolveAttempts":1,"exitCode":27,"retries":1}}
> [09:48:53.977] ------
> 

From what I understand this should work as per the docs.  Perhaps this "flavour" of Win10 is not supported yet or perhaps it's because the server is hosted in AWS?

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by egamma** [comment]
@mattemoore the support is still experimental pls see https://github.com/microsoft/vscode-docs/blob/master/remote-release-notes/v1_39.md#remote---ssh-for-windows-remotes.

**Comment by mattemoore** [comment]
Thanks!
Adding this setting made it work: "remote.SSH.windowsRemotes": ["my-windows-host-name"].

Super cool to be able to code the containerization of our windows monolith from vscode on my mac.
