### ISSUE TITLE
Not seeing "Remote-Containers: Add Development Container Configuration Files.." option

### ISSUE THREAD

**Issue by svangeti** [microsoft/vscode-remote-release#1855]
I want to create development environments for azure function python, Java etc., but not seeing "Remote-Containers: Add Development Container Configuration Files.." option from command palette. What am I missing. I have also installed docker image for python.3.6-stretch to see if that solves problem.

**Comment by Chuxel** [comment]
@svangeti What OS are you on?  Are you connected to WSL or a remote SSH host? If so, you'll need to open a local window first. (File > New Window)
