### ISSUE TITLE
Remote containers extension not working at all

### ISSUE THREAD

**Issue by amitlevy21** [microsoft/vscode-remote-release#1858]
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-15T22:58:14.270Z
Electron: 6.1.1
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.19.84-1-MANJARO

Steps to Reproduce:

1. Install Remote Development extension pack
2. Pressing the remote development icon at the bottom left will only show options for the remote ssh extension:
![image](https://user-images.githubusercontent.com/28672915/68995729-8c97d280-0899-11ea-934e-a7ea31730e5f.png)

When I try to do something by searching with `Ctrl+Shift+p`, for example `Remote-Containers: Report Issue`:
![image](https://user-images.githubusercontent.com/28672915/68995744-bbae4400-0899-11ea-828b-709dca854833.png)

Any other command 'Remote-Containers:' command I will try to do will show the same thing.

This also happen when I only install the remote containers extension directly and not by installing the remote development extension pack.

**Comment by Chuxel** [comment]
@amitlevy21 Hmmm.  Given you are on Arch its possible you are missing some dependencies or something along those lines.

Just to double check - Are you using the official VS Code bits or OSS?  The remote extensions only work with the official bits.  The AUR package [visual-studio-code-bin](https://aur.archlinux.org/packages/visual-studio-code-bin/) should work.

Assuming you are on official bits, do you see any errors in the console when you go to Help > Toggle Developer Tools?

**Comment by amitlevy21** [comment]
@Chuxel Nice catch, I am using OSS. It works with the visual-studio-code-bin from the AUR.

I don't see any errors when toggling developer tools.

Is there any hope the remote extensions will work on OSS someday?

**Comment by Chuxel** [comment]
@amitlevy21 We're always listening to feedback here, but you can check out the FAQ for info on why things are the way they are currently: https://code.visualstudio.com/docs/remote/faq#_license-and-privacy

Closing the issue since it sounds like we've resolved your problem which is great!
