### ISSUE TITLE
Support `-u <user>` option for "Attach to Running Container"

### ISSUE THREAD

**Issue by vijay609** [microsoft/vscode-remote-release#1860]
First of all, THANK YOU VERY MUCH FOR SUPPORTING DOCKER CONTAINERS IN VSCODE.

I have a docker image that has an entry point script. The entry point script sets up some configuration using the arguments passed to `docker run` and then does `gosu devuser $@`.

When I start the container from a shell, I land in a bash shell with `devuser` as the user.
If I want to open another shell I run `docker exec -it -u devuser <container_name> bash`, and it again lands me in a shell with `devuser` as the user.

When I attach vscode to this container, vscode attaches as root, since root is the default user for the container.
**What I would like to do is attach to the running container as a particular user that already exists in the docker container.
It would be awesome, if `Attach to Running Container` option supported a `-u` option.**
If this is already possible, please point me to the instructions.
I tried to look for this online (for about an hour), but couldn't find anything.
Thanks again!!

**Comment by lbssousa** [comment]
Related issue: #538

**Comment by chrmarti** [comment]
Fixed with #1155. There is now a `remoteUser` property in the config file.
