### ISSUE TITLE
Cannot get the plots shown from remote ssh or remote container

### ISSUE THREAD

**Issue by asam46** [microsoft/vscode-remote-release#1862]
- VSCode Version: Version: 1.40.1
- Local OS Version: MacOS 10.14.6
- Remote OS Version: ubuntu 18.04
- Remote Extension/Connection Type: SSH/Docker

Steps to Reproduce:

1. Get the dockerfile from https://github.com/rocker-org/rocker/tree/master/r-ubuntu
2. Connect this using vscode extension `Remote - Containers`
3. Open R in the terminal in remote environment:
```r
# install.packages("tidyverse")
library(tidyverse)
data(iris)
summary(iris)
plot(iris$Sepal.Length)
```
The plot cannot be shown, but I can find a new and empty file called `Rplot.pdf` created in the folder which cannot be opened.

I also do the similar test in the remote server using `Remote - SSH` to connect, and cannot get the plots shown.

Actually, I succeed in getting the plots shown in win 10 using vscode and `Remote - wsl` to connect to the wsl, with [xming](https://sourceforge.net/projects/xming/) installed. However, when I use mac and try using `Remote - Containers` and `Remote - SSH` for the works on data science, I cannot get the plots shown even I have installed XQuartz 2.7.11 as suggested by other references.

Could you please give me some advices?
Thanks very much!

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by egamma** [comment]
It looks like that the plot library requires an X Window context which is not available/setup in the container or the SSH box. To make the plot library work you also have to setup X windows for the remote case.
