### ISSUE TITLE
Settings keep getting removed sporadically

### ISSUE THREAD

**Issue by mwidmann** [microsoft/vscode-remote-release#1863]
- VSCode Version: 1.40.1
- Local OS Version: Windows 10 (insider slow) Build 19013.vb_release.191025-1609
- Remote OS Version: Ubuntu 18.04.3 LTS running in WSL2
- Remote Extension/Connection Type: WSL: Ubuntu

Steps to Reproduce:

1. navigate to any project folder in wsl2
2. type `code .`
4. code opens with the WSL: Ubuntu remote connection
5. do some stuff there
6. after a while the `.vscode/settings.json` will be updated throwing out `workbench.colorCustomizations` entry

This is the `.vscode/settings.json` checked into my repository:

```
{
  "workbench.colorCustomizations": {
    "activityBar.background": "#75cda5",
    "activityBar.activeBorder": "#945bc4",
    "activityBar.foreground": "#15202b",
    "activityBar.inactiveForeground": "#15202b99",
    "activityBarBadge.background": "#945bc4",
    "activityBarBadge.foreground": "#e7e7e7",
    "titleBar.activeBackground": "#4fc08d",
    "titleBar.inactiveBackground": "#4fc08d99",
    "titleBar.activeForeground": "#15202b",
    "titleBar.inactiveForeground": "#15202b99",
    "statusBar.background": "#4fc08d",
    "statusBarItem.hoverBackground": "#3aa273",
    "statusBar.foreground": "#15202b"
  },
  // scss+tailwind don't play along well with linting
  "vetur.validation.style": false,
  "peacock.color": "#4fc08d",
}
```

after a while it's getting replaced with this:

```
{
  "vetur.validation.style": false,
  "peacock.color": "#4fc08d",
}
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by egamma** [comment]
@mwidmann I assume you use the peacock extension? Can you confirm that only the peacock related `colorCustomizations` are affected?

**Comment by mwidmann** [comment]
@egamma, no, the peacock setting stays there, the `workbench.colorCustomizations` get removed. Those are features that were available long before the peacock extension was available. 
Do you think it maybe related to the peacock extension?

**Comment by roblourens** [comment]
It's possible, can you try disabling that extension and checking whether it still happens? If so you can file an issue on that extension's repo.

**Comment by mwidmann** [comment]
Thanks for the advice. I disabled the extension and it didn't happen anymore. Will file the issue there.
