### ISSUE TITLE
This workspace has recommended extensions but I can't load it in extension list

### ISSUE THREAD

**Issue by Fonger** [microsoft/vscode-remote-release#1864]
- VSCode Version: 1.40.1
- Local OS Version: Windows 10 1903 Build 18362.476
- Remote OS Version: WSL
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. create a project containing `.vscode/extensions.json`
```json
{
  "recommendations": [
    "apollographql.vscode-apollo",
    "esbenp.prettier-vscode",
    "dbaeumer.vscode-eslint",
    "jpoissonnier.vscode-styled-components",
    "msjsdiag.debugger-for-chrome",
    "eg2.vscode-npm-script",
    "christian-kohler.npm-intellisense",
    "eamodio.gitlens",
    "tombonnike.vscode-status-bar-format-toggle"
  ],
  "unwantedRecommendations": [
    "eg2.tslint",
    "ms-vscode.vscode-typescript-tslint-plugin"
  ]
}
```
2. Open it with vscode remote WSL. You will see a notification in bottom right says this workspace has recommended extensions. Then you hit install
3. You can see it's searching `@recommended` in extension but no results are shown.
![image](https://user-images.githubusercontent.com/5862369/69124796-78ddad80-0adf-11ea-8926-cdc74f8e3469.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by sandy081** [comment]
It works for me in latest builds.
