### ISSUE TITLE
Unable to uninstall extension - error No remote extension installed to resolve ssh-remote.

### ISSUE THREAD

**Issue by JRobertEdwards** [microsoft/vscode-remote-release#1865]
When trying to uninstall the Remote - SSH extension I am met with the error ' No remote extension installed to resolve ssh-remote.'

I'm not able to uninstall the extension at all but am able to disable and enable it. There are no other errors displayed when I try to do this.

In case it's relevant my ssh config files contains these only:
Host londev1edwajo01
  User <username>
  HostName <host address>

VSCode info: 
Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.14393

Issue is very similar to: https://github.com/microsoft/vscode-remote-release/issues/771 

However they were running on an older version of VSCode. I've run a check for updates on it and I am totally up to date.

**Comment by sandy081** [comment]
Do you see this message immediately after uninstalling the extension?

**Comment by JRobertEdwards** [comment]
This was after attempting to uninstall the extension yes,m the uninstall itself did not work because of this error though.

**Comment by sandy081** [comment]
From which window you are trying to uninstall? I mean is that window connected to remote ssh or just a local window?

**Comment by JRobertEdwards** [comment]
It was from a local window, the attempt to ssh to the server could not connect. My guess on this is probably because the ssh extension was loaded on the server and not locally.

**Comment by sandy081** [comment]
Can you please provide a screenshot or gif to show us the repro steps?

**Comment by JRobertEdwards** [comment]
Unfortunately I'm not able to replicate this issue since the server connection is now working fine.

I'm pretty sure this was triggered because the remote server I ssh into had the ssh-remote extension details and not my local version of VScode. That's my best guess at least anyway.

**Comment by sandy081** [comment]
Ok. If you could repro it again, please provide the necessary info.
