### ISSUE TITLE
Help interaction sequence for Remote Explorer

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#1869]
Issue Type: <b>Bug</b>

1) In the remote explorer select `SSH Targets` in the dropdown
2) Click the question mark icon
2) Choose `documentation`
-> I'm presented with a quickpick listing the remote extensions. Since I'm in the `SSH` context I expect the SSH documentation to show up.

Extension version: 0.17.0
VS Code version: Code - Insiders 1.41.0-insider (29b99f85e54aa5af6cd4edf918a67d4f70a10aea, 2019-11-19T10:25:09.288Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.0.0-1022-azure
Remote OS version: Linux x64 5.0.0-1022-azure
Fetching remote diagnostics for 'ssh-remote+az-devbox' timed out.

**Comment by alexr00** [comment]
Since its a top level action, we might want to leave all documentation showing so that users can see the various options.

**Comment by alexr00** [comment]
Per UX discussion, we will only filter to the specific documentation when connected.

**Comment by alexr00** [comment]
We are also conducting a user study to make sure that the help is still discover-able.

**Comment by alexr00** [comment]
Filtering when connected has been added. There is some adoption needed by extensions since it turns out we didn't have this before.

**Comment by mjbvz** [comment]
Verified that filtering works when connected to a remote

I still see the behavior @kieferrm described when not connected to a remote. I also find it confusing but it sounds like this has already been discussed

**Comment by mjbvz** [comment]
Actually there is another confusing case:

1. Connect to remote container
1. In remote explorer, select the `ssh targets`
1. Now go to documentation using question mark icon
1. This always opens the container help

I'll let someone else take a look and see if they think this should be revisited as well

**Comment by roblourens** [comment]
I think that case is by design @mjbvz.

**Comment by alexr00** [comment]
It was by design until https://github.com/microsoft/vscode/issues/86328
