### ISSUE TITLE
Pipenv doesn't work over remote connections

### ISSUE THREAD

**Issue by spott** [microsoft/vscode-remote-release#187]
- VSCode Version: 1.34.0-insider
- Local OS Version: macOS 10.14.4
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.  Open up remote folder with Pipfile in it, install python extension, restart, open remote folder with Pipfile in it again.
2. Get the following error:

```
Workspace contains pipfile but attempt to run 'pipenv --venv' failed with 
'Traceback (most recent call last): 
File "/usr/local/bin/pipenv", line 11, in <module>
 sys.exit(cli()) 
File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 764, in __call__ return
 self.main(*args, **kwargs) 
File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 717, in main
 rv = self.invoke(ctx) 
File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 1114, in invoke
 return Command.invoke(self, ctx) 
File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 956, in invoke
 return ctx.invoke(self.callback, **ctx.params) 
File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 555, in invoke
 return callback(*args, **kwargs) 
File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
 return ctx.invoke(f, obj, *args, *...
```

When I go to the terminal to try and reproduce, I get:

```
$ pipenv --venv
No virtualenv has been created for this project yet!
Aborted!
```

However, in the same folder in a terminal I don't have a problem.

(edited to cleanup traceback)

**Comment by kieferrm** [comment]
@spott I suspect that the environments are initialized differently. Have a look at the `Remote – SSH` output channel. When the server launches we print the environment the server sees.

**Comment by spott** [comment]
@kieferrm What is the command that vscode uses to make the connection?  (the options that are used when doing the SSH?)

**Comment by spott** [comment]
So, I fixed the fact that `pipenv --venv` didn't work in the terminal, but I'm still getting the error.

It looks like that error message is truncated (the `...`) at the end.  How do I see the whole thing?

**Comment by roblourens** [comment]
The error is probably coming from Python or the python extension so I don't know how to see more of it. Where do you actually see the error? If this is still an issue, what did you do to fix it in the terminal?

**Comment by spott** [comment]
I haven't actually had this problem in a while, I'm sorry I should have closed it before now.
