### ISSUE TITLE
Problems running extension tests remotely (SSH).

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/vscode-remote-release#1877]
For the Python extension we have a set of tests that require VS Code to run (launch config: ["Tests (Single Workspace, VS Code, *.test.ts)"](https://github.com/microsoft/vscode-python/blob/master/.vscode/launch.json#L98)).  This requires opening a separate VS Code instance.

When I have the Python extension open in VS Code, via remote (SSH), and run that launch config, it doesn't work.  A new VS Code pops up, but the tests do not run.  Instead I see the following:

* `Failed to connect to the remote extension host server (Error: No remote extension installed to resolve ssh-remote.)`
* `Resolving the authority `ssh-remote` failed`
* in the bottom left corner it says "Disconnected from ssh-remote+\<hostname>"

**Comment by roblourens** [comment]
I see you have the `--disable-extensions` flag in that launch config. That won't work because the SSH extension needs to be running to connect to the remote.

You might try the `--extensions-dir` flag to point to a directory that only has the SSH extension installed?

**Comment by roblourens** [comment]
Ideally you would be able to "disable all extensions except remote resolvers", I can see that being useful. Is that a practical thing to do @sandy081?

**Comment by sandy081** [comment]
yeah this can be done with a special flag.

**Comment by ericsnowcurrently** [comment]
Thanks for the explanation (and the tip), @roblourens.  And a flag for "disable all extensions except remote resolvers" would be very helpful.  Thanks for re-opening the issue. 😄

**Comment by roblourens** [comment]
@sandy081 I will assign it to you then and you can decide whether it's in scope
