### ISSUE TITLE
Attach to container by name instead of id

### ISSUE THREAD

**Issue by nchandran3** [microsoft/vscode-remote-release#1878]
My workflow is that we end up rebuilding our container (sometimes cached so it goes fast) every time my computer restarts or goes to sleep. Once the container is running in WSL2, I then use VSCode to attach to the already running container. 

 I believe this rebuilding the image / restarting my computer gives it a new container ID every time.

This means that VSCode then can't find the container that I attached to previously, and it ends up bloating my VSCode menu with a bunch of remote targets that don't exist anymore. I've also noticed that when looking at the remote containers that VSCode has discovered, it ends up listing options as `image-name-tag` instead of the container name itself. 

Instead, is it possible to just have VSCode attach to a container by name instead of id? All containers that are rebuilt are given the same name, so if VSCode was instead able to just pick the first container that was named appropriately, I wouldn't have to go through the same tedium every time: 

-  Attaching to the remote container through containers menu
- Navigating to my source folder
- VSCode recognizes there's a workspace file --> open workspace
- Reload window with workspace loaded
- Reopen all files I had open previously

Is there some option to allow this? Or can someone please link to the docs where I can configure this option? 

- Version of VS Code: 1.40.1
- Operating system: Windows_NT x64 10.0.18985
- Remote operating system: Container running on WSL2

**Comment by chrmarti** [comment]
/duplicate Fixed with https://github.com/microsoft/vscode-remote-release/issues/1794

**Comment by nchandran3** [comment]
@chrmarti That seems to just be another issue link, is there a PR that closed it? 

Alternatively any docs on how we can connect by container name instead when it rolls out?

**Comment by chrmarti** [comment]
@nchandran3 When you attach to a container it will remember the name with the new release (currently 0.86.0). You can use the new release by installing VS Code Insiders (https://code.visualstudio.com/insiders/) or wait for VS Code 1.41 to be released which will also get the latest release of Remote Containers.
