### ISSUE TITLE
Extensions that use original-fs will need to be modified to fall back to fs when running remote

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#188]
Electron provides a node module called `original-fs` that provides access to base implementation of the `fs` node module instead of Electron's tweaked version. (See [here](https://electronjs.org/docs/tutorial/application-packaging#treating-an-asar-archive-as-a-normal-file).)

The VS Code Server in VS Code Remote Development extensions uses a standard Node.js runtime instead of Electron, so extensions that use `original-fs` will fail in a remote environment because this   alias to `fs` does not exist.

Extensions should stick with the base `fs` implementation when possible, but if `original-fs` is required when running inside VS Code, the code will need to fall back to `fs` if `original-fs` isn't found.  The subversion extension (#135) is an example of one currently using it. 

We need to doc this issue and required changes. As an enhancement, we could also shim `original-fs` in the remote environment to `fs`.

/cc: @rebornix @alexandrudima @egamma @kieferrm

**Comment by alexandrudima** [comment]
:+1: We could definitely shim `original-fs` to point to `fs`

**Comment by Chuxel** [comment]
Not many. I did a search and only found two, but since this is likely a general class of problem, I doc’d that you should generally avoid electron dependencies unless you provide a fallback. 

PR is here, see if you agree with the content: https://github.com/microsoft/vscode-docs/issues/2632

The SVN author is going to patch. TRis was introduced in a recent change which is why we didn’t catch it pre release.

**Comment by rebornix** [comment]
I found 3 extensions declare dependencies on `original-fs`

* GoogleCloudTools.cloudcode
* Shan.code-settings-sync
* WakaTime.vscode-wakatime

**Comment by egamma** [comment]
>Shan.code-settings-sync

We define this extension as a UI extension in the product.json so it should be OK.

**Comment by Chuxel** [comment]
Ok docs now reference the general recommendation of avoiding of relying on electron specific modules and that you should have a fallback if you do.  SVN is looking at a fix, that would only leave two with an unknown number down the road.  Probably not enough to jump on it urgently - should we leave it open for future consideration?

**Comment by egamma** [comment]
@chuxel this issue has been analyzed and can be closed. I've filed a separate issue on shimming original-fs
