### ISSUE TITLE
${workspaceFolderBasename} support in .devcontainer.json

### ISSUE THREAD

**Issue by cdobrescu** [microsoft/vscode-remote-release#1880]
Hello, I'm working on multiple projects that are using the same development container. Currently each project has its own `.devcontainer` configuration. If `${workspaceFolderBasename}` would've been supported in `.devcontainer.json`, than this would allow single `.devcontainer` configuration instance for all projects. 
Imagine the following folder tree  structure:
```
parent/
├── project1
├── project2
└── project3
```
I could  create `.devcontainer` folder in the `parent` directory and in projects[1-3] I would use relative symbolic links to the parent folders `.devcontainer`.
`workspaceMount` configuration will mount the `parent` folder while `workspaceFolder` will be set to something like `remote_parent_path/${workspaceFolderBasename}`

**Comment by Chuxel** [comment]
@cdobrescu You can do this by putting `.devcontainer` in `parent`, opening the folder, and then using File > Open to open the sub folder.  These sub-folders will also appear in the remote explorer next time you connect.  See [here for details](https://code.visualstudio.com/docs/remote/containers#_quick-start-configure-a-sandbox-for-multiple-projects-or-folders).

Would that work?

**Comment by cdobrescu** [comment]
The result of opening the folder in container is creating a `.devcontainer` folder in the project folder, which is how I'm working right now, every project has it own .devcontainer folder with a different devcontainer.json file. Supporting this variable would allow using a single configuration copy for multiple projects.

**Comment by cdobrescu** [comment]
I'll provide more details when i get to the laptop, maybe my initial description wasn't very clear

**Comment by cdobrescu** [comment]
This issue can be closed. I see that support for ${workspaceFolderBasename} has been added. I've tested it and It works
