### ISSUE TITLE
environment variable in linux cannot use in vscode terminal.

### ISSUE THREAD

**Issue by Abbyyan** [microsoft/vscode-remote-release#1883]
I connect to the remote server successfully. In my server, i set some environment variables in .profile and can use it properly. But when i open a terminal in vscode , the environment doesn't work. how can i fix it ? Thanks a lot.

**Comment by roblourens** [comment]
Can you give more details? Which remote type? Note that if you are using SSH, then you will have to restart the remote server for the changes to your environment to take effect.
