### ISSUE TITLE
command 'remote-containers.openRepositoryInVolume' not found

### ISSUE THREAD

**Issue by sebirdman** [microsoft/vscode-remote-release#1886]
- VSCode Version: 1.40.1 (opensource build)
- Local OS Version: Archlinux
- Remote OS Version: None (Yet)
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1. Install ext install ms-vscode-remote.remote-containers
2. Select "Open Repository in Volume" from the command pallet
3. Observe error "command 'remote-containers.openRepositoryInVolume' not found"

**Comment by chrmarti** [comment]
Is there anything in the console? (`Help` > `Toggle Developer Tools`)

**Comment by sebirdman** [comment]
It appears that after installing the microsoft build (from https://aur.archlinux.org/packages/visual-studio-code-bin for my distro) docker works. 

Seems like the opensource build of vscode may not have support for this extension.

**Comment by chrmarti** [comment]
You're right, only the official Microsoft builds can run the Remote Development extensions.
