### ISSUE TITLE
allow other extensions to pass connection string

### ISSUE THREAD

**Issue by 0x6b** [microsoft/vscode-remote-release#1888]
- Visual Studio Code v1.40.0
- Visual Studio Code Remote - SSH Extension, v0.47.2

I'm creating an extension working with the service which creates ephemeral SSH proxy connection with various port number and host name, then connect to the host by this extension. For such use case, it'd be good if I can pass connection string to this extension for opening new remote. At this moment I copied the string to the clipboard and ask the user to paste it to the input box in the document but it's not an intuitive way I think.

It'd be good for other extension developers as well if following commands exposed such capability.

- `opensshremotes.openEmptyWindow`
- `opensshremotes.openEmptyWindowInCurrentWindow`

For exapmle,

```typescript
vscode.commands.executeCommand(
  "opensshremotes.openEmptyWindow",
  "ssh://user@hostname:port"
);
```

Anyway thanks much for the efforts your team have made to bring this fantastic extension.

**Comment by roblourens** [comment]
We do have a command for this, unfortunately they are not well documented or discoverable.

`vscode.newWindow` which takes 

```ts
interface INewWindowAPICommandOptions {
	reuseWindow?: boolean;
	remoteAuthority?: string;
}
```
