### ISSUE TITLE
Remote-SSH: setup X11 for remote display

### ISSUE THREAD

**Issue by zr526799544** [microsoft/vscode-remote-release#1889]
I am a rookie for both code and English，so my description may not so exactly right.I notice there are few issues to look help for ForwardX11 to get a visible GUI for code result. and I follow them try to use matlibplot to draw a picture for my code on remote server. but none of them works......I want to know how to exactly  set my vscode setting to see a picture from the matlibplot run on the remote server.by the way I have already work it by using xming and xshell  but failed on vscode. My Os is WIN10 pro. and remote server is Ubuntu 16.04

**Comment by zr526799544** [comment]
The movement of heaven is full of power,makes oneself strong and untiring.I finally fix it on my own computer. all you need is just  export DISPLAY= yourlocalcompoterip: yourxmingport。
example:
![image](https://user-images.githubusercontent.com/37580152/69513152-cc3d7900-0f81-11ea-9bac-73b35c37eb8d.png)
![image](https://user-images.githubusercontent.com/37580152/69513183-ee36fb80-0f81-11ea-91a7-e26e094ca5c6.png)
![image](https://user-images.githubusercontent.com/37580152/69513037-749f0d80-0f81-11ea-9c7d-d826e73eb348.png)
![image](https://user-images.githubusercontent.com/37580152/69513119-afa14100-0f81-11ea-8ec5-917dcc92998d.png)
and Lauch Xming then you can see you matplot img on Xming.
![image](https://user-images.githubusercontent.com/37580152/69513255-28a09880-0f82-11ea-91f8-9865c13e276b.png)

**Comment by chrmarti** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/267

**Comment by aeschli** [comment]
@zr526799544 Great that you have found a solution and thanks a lot for sharing.
@Chuxel @gregvanl Would be cool to have this in our tips and tricks
