### ISSUE TITLE
Workspace at local, debug both local and remote.

### ISSUE THREAD

**Issue by youngyou** [microsoft/vscode-remote-release#1897]
Save all our codes at client side and we can debug at both local and remote.

**Comment by aeschli** [comment]
Please explain more...

**Comment by youngyou** [comment]
> Please explain more...

Save all files at local and sync files to remote computer, just like [SFTP](https://github.com/liximomo/vscode-sftp). But support remote debug. So we can debug our code on different environment.

**Comment by roblourens** [comment]
This just isn't how VS Code Remote works and we don't plan to support this model. You might be interested in this overview of how it works: https://code.visualstudio.com/docs/remote/remote-overview
