### ISSUE TITLE
Connect to a remote server via `code --folder-uri`

### ISSUE THREAD

**Issue by alsrgv** [microsoft/vscode-remote-release#190]
It would be great to be able to open a remote VS code session from console using a special URIs, e.g.:

```
$ code --folder-uri ssh://server-name/folder-on-server
```

Is there anything like that on the roadmap?

**Comment by ataiya** [comment]
+1, am I mistaken or when you connect to a SSH remote it goes by default to ~/, and there is no way of configuring this?

**Comment by vilic** [comment]
We are also looking forward to this feature while trying to integrate remote development into our workflow.

In our scenario, we would like to create one remote workspace for every feature/fix branch. And thus we'll have other tools to manage the lifecycle of those workspaces and providing links to open in VS Code.

**Comment by vilic** [comment]
Seems like it's already working:

```
code-insiders --folder-uri "vscode-remote://ssh-remote+host/path/to/project"
```

https://github.com/microsoft/vscode-remote-release/issues/505

**Comment by alsrgv** [comment]
@vilic, exactly what I was looking for!  Thanks!

**Comment by ataiya** [comment]
Can I bother you with a bit more details?
I have tried this (IP obfuscated):
```
code-insiders --folder-uri "vscode-remote://12.23.45.67/home/myuser/dev/"
```

but I get
```
Failed to connect to the remote extension host server (Error: Port should be > 0 and < 65536. Received NaN.)
```

**Comment by dahjelle** [comment]
Ah! So the syntax is actually:

```
code --folder-uri "vscode-remote://ssh-remote+12.23.45.67/home/myuser/dev/"
```

(It wasn't obvious to me that `ssh-remote+` was a verbatim part of the command.)

Nice!

**Comment by ataiya** [comment]
Thanks! But I think I found a bug.
In the command above, it works when I use the direct IP address, but if I use the hostname as specified in `~/.ssh/config`, then vscode-insiders cannot connect?

**Comment by aeschli** [comment]
You can also use
`code --remote=ssh-remote+12.23.45.67 /home/myuser/dev/`
