### ISSUE TITLE
Cannot specify SSH port, specifying one confuses the extension and resolves ip:port as a hostname.

### ISSUE THREAD

**Issue by oxygen** [microsoft/vscode-remote-release#1900]
- VSCode Version: 1.40.1
- Local OS Version: 1903
- Remote OS Version: N/A
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
1. code --folder-uri vscode-remote://ssh-remote+root@172.31.240.92:27434

Behaviour:
Error thrown immediately (it does not try to contact the IP address, it tries to resolve it as a hostname and fails):
**Could not establish connection to "172.31.240.92:27434". Could not resolve the hostname.**

The command works fine without specifying a port for servers which have SSH port 22.

**Comment by roblourens** [comment]
You will have to set up an ssh config for that host which contains the port, it's not possible to embed it in the name like that.

**Comment by oxygen** [comment]
I already created a SSH config because that's the only way it works.

However my use case requires to specifically be able to open Visual Studio Code automatically on the remote project.

Does the extension support naming a specific SSH config and then a specific SSH config item to automatically open on start?

According to https://tools.ietf.org/rfc/rfc3986.txt the port number can be specified in an by separating it with `:` after the hostname or IP address.

IPv4 addresses in dotted decimal format (10.30.40.50) cannot contain the `:` character. Hostnames (domain labels and FQDNs) cannot contain the `:`. Yet this extension incorrectly tries to do DNS resolution when it already has the IP address: `172.31.240.92:27434`.

This is a clear bug and needs to be fixed. It blocks users from being able to automatically open a remote SSH Visual Studio Code session at startup.

**Comment by oxygen** [comment]
If you accept pull requests, I can help fix the bug. Just point me to the project that accepts them.

**Comment by roblourens** [comment]
If you already have an ssh config, you can add the port to the ssh config and exclude it from the URI. I know it should technically be ok in the URI, but `:` is also a valid character in the name of an SSH host, so to keep my sanity I am not handling it entered manually.

**Comment by roblourens** [comment]
Actually, I was thinking about how often this issue comes up, eg https://github.com/microsoft/vscode-remote-release/issues/1320, https://github.com/microsoft/vscode-remote-release/issues/515, many others, I will try to support this case. Will continue in https://github.com/microsoft/vscode-remote-release/issues/515. (that issue says it works, but that isn't true anymore)

**Comment by oxygen** [comment]
> If you already have an ssh config, you can add the port to the ssh config and exclude it from the URI. I know it should technically be ok in the URI, but : is also a valid character in the name of an SSH host, so to keep my sanity I am not handling it entered manually.

It doesn't select it from the SSH config, and I have a custom SSH config specified in VS Code which does contain the port. That's poor solution anyway, if it would have worked, and could also lead to other issues like using the wrong port.

**Comment by oxygen** [comment]
>  I will try to support this case.
Thank you!

Let me know if I can help.
