### ISSUE TITLE
Remote SSH Repo contains 2 references to each file

### ISSUE THREAD

**Issue by rafin** [microsoft/vscode-remote-release#1901]
Issue Type: <b>Bug</b>

Repo contains 2 references to each file. If I perform a file search, every file result will contain:
1. A file which is the relative path from the root of the remotely accessed directory. e.g.
```
mydir/tests/test1.py
```
2. A file which is the relative path from my home directory. e.g.
```
jsmith/myprojects/mydir/tests/test1.py
```

This leads to some frustrating behavior where a file will be saved on one reference, but the other will contain changes that haven't been saved, I noticed this only occurs in one of my repos as well.

Extension version: 0.47.2
VS Code version: Code - Insiders 1.41.0-insider (1c9fd8a59787487ca71d8c5ce140569a0e036a15, 2019-11-19T06:28:41.868Z)

**Comment by roblourens** [comment]
Could you hover the tab of each file to see the full path (or run the Copy Path of Active File command) and paste them here and check whether they are exactly the same? Same casing and everything?
