### ISSUE TITLE
Remote Explorer panel is empty

### ISSUE THREAD

**Issue by SSmale** [microsoft/vscode-remote-release#1902]
- VSCode Version: 1.41.0-insider (user setup)
- Local OS Version: : Windows_NT x64 **10.0.17134**
- Remote OS Version: CentOS 7.5
- Remote Extension/Connection Type: SSH
- Extension Version: 0.47.2 

Steps to Reproduce:

1. connect to remote client
2. none of the options are shown in the sidebar

**Comment by roblourens** [comment]
Do you have an ssh config file set up?

**Comment by SSmale** [comment]
@roblourens yes I have been using it fine for 6 months then the other day the panel is empty. I can’t select a new host or previous directories or start any port forwarding. 

I did notice a pop up saying that the ssh explorer extension was no longer needed and not long after that it stopped showing

**Comment by kuelumbus** [comment]
Same problem here.

Version: 1.41.0-insider
Commit: bbf00d8ea6aa7e825ca3393364d746fe401d3299
Date: 2019-12-05T06:56:29.906Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-36-generic snap

![image](https://user-images.githubusercontent.com/44866753/70255503-ee3eb480-1754-11ea-8a2d-b05c402f77c3.png)

"Remote SSH: Connect to host" works and correctly shows all hosts from `~/.ssh/config`

**Comment by roblourens** [comment]
Can you check that the SSH extension is up to date? And are there any errors in devtools? (Help > Toggle Developer tools)

Any idea @alexr00?

**Comment by SSmale** [comment]
I know mine is up to date. I will have a look at the dev tools tomorrow

**Comment by kuelumbus** [comment]
Name: Remote - SSH
Id: ms-vscode-remote.remote-ssh
Description: Open any folder on a remote machine using SSH and take advantage of VS Code's full feature set.
Version: 0.47.2
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh

Errors:
```
[uncaught exception]: Error: Cannot read property 'reprocess' of undefined

TypeError: Cannot read property 'reprocess' of undefined
    at C.onDefaultConfigurationChanged (file:///snap/code-insiders/325/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4593:537)
    at file:///snap/code-insiders/325/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4585:949
    at c.fire (file:///snap/code-insiders/325/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:114:893)
    at Object.registerConfigurations (file:///snap/code-insiders/325/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1646:939)
    at Object.registerConfiguration (file:///snap/code-insiders/325/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1646:612)
    at file:///snap/code-insiders/325/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2843:85
onUnexpectedError @ bootstrap-window.js:213
bootstrap-window.js:216 Error: Cannot read property 'reprocess' of undefined

TypeError: Cannot read property 'reprocess' of undefined
    at C.onDefaultConfigurationChanged (configurationService.ts:498)
    at configurationService.ts:97
    at c.fire (event.ts:581)
    at Object.registerConfigurations (configurationRegistry.ts:195)
    at Object.registerConfiguration (configurationRegistry.ts:182)
    at externalTerminalService.ts:369
    at errors.ts:26
onUnexpectedError @ bootstrap-window.js:216
2console.ts:137 [Extension Host] (node:17281) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:27:3))
t.log @ console.ts:137


```

**Comment by roblourens** [comment]
I don't know whether that error is related, @sandy081 does it look familiar?

If you open a new local window do you see any difference?

**Comment by kuelumbus** [comment]
Yes, the error disappears in a new local window. 
![image](https://user-images.githubusercontent.com/44866753/70269831-28b64a80-1771-11ea-8345-5adac46fd7d8.png)

**Comment by chrmarti** [comment]
Just saw that too:
![image](https://user-images.githubusercontent.com/9205389/70276630-004e4080-17b1-11ea-8592-67408028e649.png)
/cc @alexr00 

The error seems unrelated and is tracked as https://github.com/microsoft/vscode/issues/79809.

**Comment by alexr00** [comment]
Somehow the remote explorer isn't getting all the views the way I expect it to.

**Comment by roblourens** [comment]
I wasn't able to repro, can you include steps @alexr00?

**Comment by roblourens** [comment]
Or someone else who saw it can confirm that it is fixed in the latest insiders build? 
https://code.visualstudio.com/insiders

**Comment by SSmale** [comment]
I can check on Monday when I’m back in the office

**Comment by alexr00** [comment]
I'm not sure how it's happening, so I don't have any repro steps.

**Comment by SSmale** [comment]
I have checked my system and it is now showing the remote hosts and port forwarding as expected. Thanks @alexr00!

**Comment by alexr00** [comment]
Thank you @SSmale!
