### ISSUE TITLE
C/C++ syntax highlighting is not working well on remote mode, such as SSH/WSL

### ISSUE THREAD

**Issue by MxDany** [microsoft/vscode-remote-release#1905]
- VSCode Version:
- Local OS Version:
- Remote OS Version:
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
Please attach a screenshot.

/needsMoreInfo
