### ISSUE TITLE
vscode remote http 403

### ISSUE THREAD

**Issue by Abbyyan** [microsoft/vscode-remote-release#1906]
I have develop an vscode  extension  to send http get request and it works fine on my pc. But when i install it in the server using visix with remote-ssh , it failed and get http 403 error. I tried to write a test.js to send http request on my server and it works , but in vscode extension, it failed . Do you have any suggestions ? Thanks a lot . PS : on my server , curl and wget all works fine.

**Comment by chrmarti** [comment]
Please append the code for the request.
