### ISSUE TITLE
Ubuntu Server stop response when connecting with Remote-SSH

### ISSUE THREAD

**Issue by mai1015** [microsoft/vscode-remote-release#191]
- VSCode Version:
Version: 1.34.0-insider (user setup)
Commit: daf71423252a707b8e396e8afa8102b717f8213b
Date: 2019-05-06T22:08:08.969Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 18.04 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
1. Connect to server in one windows
2. Connect to same server while the first connection is running.

Then two instance start to consume all server resources. Activating extension at the same time. So, the server stop responding.
Is there any way, to delay the process that waits the other services to complete.

Server output:
```
[  OK  ] Created slice User Slice of coder.
         Starting User Manager for UID 1003...
[  OK  ] Started Session 1 of user coder.
[  OK  ] Started User Manager for UID 1003.
```

Extension Installed: Java.
Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Sorry for the slow response. Let me know if this is still an issue.
