### ISSUE TITLE
Using git from both windows and WSL side causes problems

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#1911]
When WSL-Remote is opened on a the mounted drive (`/mnt/c`), the git viewlet starts using Linux Git on a folder that might be accessed by Windows-Git as well.

Reported issues:

https://github.com/microsoft/vscode-remote-release/issues/362

https://github.com/microsoft/vscode/issues/84509

---

Steps:

1. Clone a repo in Windows
2. Open that repo from WSL Remote
3. In Windows, run `git status`

**Comment by aeschli** [comment]
FYI @joaomoreno 
Maybe we find a way to detect that a .git folder was created by Windows Git and then use the Windows Git executable instead.

**Comment by Clovel** [comment]
@aeschli I believe the solution would be to find who blocks the `.git` files and, if it's the **Remote Ext**, try avoiding a permanent lock of the directory. The `.git/` should be locked only when a `git` command is being issued. 

I have a strong feeling that a lock is created but never released here.

**Comment by joaomoreno** [comment]
@aeschli I've done the following:

- Created a git repo in `/mnt/c` from WSL
- Created a git repo in `/mnt/c` from Windows

Both repos seem operational when opened via VS Code WSL Remote.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/84509 points to the problem. I've updated this issue's first post and added good steps.

Problem here seems to be the file watching, since once the WSL Remote window is closed, `git status` works again from Windows. What is interesting, though, is that it keeps working even if you open a new Window. :thinking:

**Comment by joaomoreno** [comment]
Turns out this is https://github.com/microsoft/vscode-remote-release/issues/903.

Another workaround: https://github.com/microsoft/vscode-remote-release/issues/903#issuecomment-521304085
