### ISSUE TITLE
Old SSH sessions build up in the Terminals list

### ISSUE THREAD

**Issue by adilosa** [microsoft/vscode-remote-release#1913]
- VSCode Version: 1.40.1
- Local OS Version: macOS Catalina 10.15.1
- Remote OS Version: Amazon Linux 2 (Karoo)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect over SSH
2. Sleep/wake host machine periodically (causing network to drop)
3. Notice that old sessions build up in the terminals list:

<img width="1014" alt="69669699-353af480-1047-11ea-856d-93f2a407ec6b" src="https://user-images.githubusercontent.com/2894907/69670083-f0638d80-1047-11ea-98bf-a6a9ba5c4ffb.png">

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
That's strange, do you have any ssh-related settings set?
