### ISSUE TITLE
Always in reconnect state

### ISSUE THREAD

**Issue by beathatbear** [microsoft/vscode-remote-release#1914]
Issue Type: <b>Bug</b>

I have maded ssh configuration, and log in remote server success.
However, after few seconds it jump out the "attempting to reconnect in ......." 
log in success and  few seconds later it jump out again
and over and over again... So, I can do nothing in this condition

Extension version: 0.47.2
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763
Fetching remote diagnostics for 'ssh-remote+wy' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (2.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

Fetching remote diagnostics for 'ssh-remote+wy' timed out.
</details>

**Comment by beathatbear** [comment]
bf11811548f2: running
Acquiring lock on /home/wy/.vscode-server/bin/f359dd69833dd8800b54d458f6d37ab7c78df520/vscode-remote-lock.f359dd69833dd8800b54d458f6d37ab7c78df520
Found existing installation at /home/wy/.vscode-server/bin/f359dd69833dd8800b54d458f6d37ab7c78df520...
Found running server...

*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
*

Checking server status on port 44697 with wget
bf11811548f2: start
agentPort==44697==
webViewServerPort====
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====
bf11811548f2: end

**Comment by Weaverzhu** [comment]
i have the similar problem today..

**Comment by jesonsyj11** [comment]
i met the same problem,  does anyone have solutions?

**Comment by roblourens** [comment]
Here are some things that can possibly lead to this:

- An unstable network connection
- Remote extensions that use lots of CPU
- Opening very large files

Do any of those sound relevant to your case?

**Comment by Wanger-SJTU** [comment]
same problem, and so many thead opened for ssh connection

**Comment by beathatbear** [comment]
> Here are some things that can possibly lead to this:
> 
> * An unstable network connection
> * Remote extensions that use lots of CPU
> * Opening very large files
> 
> Do any of those sound relevant to your case?

NONE, i checked all you mentioned. If you need any informations else, just tell me. I have trapped in this  situation for a long time

**Comment by hannesrauhe** [comment]
I see this to with version 1.50.0. It started this morning when I opened VS code.
I closed the workspace, restarted both, the Windows machine running VS Code and the machine running the server. Network is stable.

**Comment by roblourens** [comment]
Stale issue and not actionable right now, closing.
