### ISSUE TITLE
Remote Development: Does not find hosts under `Include <file>`

### ISSUE THREAD

**Issue by dgp1130** [microsoft/vscode-remote-release#1915]
Issue Type: <b>Bug</b>

1) Run the following commands to set up your SSH configuration to load a host from another file.

```shell
echo "Include foo.cfg" >> ~/.ssh/config
echo "Host myhost\n    HostName myhost.mydomain.tld" > ~/.ssh/foo.cfg
ssh myhost # Test, should work.
```

2) Run "Connect to Host" in VSCode.
3) Observe that `myhost` is missing.

There is no way to connect to this host without modifying the `~/.ssh/config` as far as I can tell, which would duplicate the configuration that should only be present in `~/.ssh/foo.cfg`.

Some background: I have some hosts I connect to for my personal configuration, and some other hosts I connect to for work. As a result, I have this setup where my `~/.ssh/config` is simply `Include config.d/*`. Then my personal set up has an install script which adds some hosts to that directory, while my work set up has an install script which adds some different hosts to that directory. This way the two configurations don't conflict and clobber the `~/.ssh/config` file.

I understand that it would probably be difficult for VSCode to track transitive SSH includes and find all relevant hosts manually, however if I just had a means of saying "Try `myhost`, even though you can't find it. Trust me, it definitely exists.", that would probably be good enough. Unfortunately, the UI doesn't seem to support that.

Extension version: 0.17.0
VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:47:00.464Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (5.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/65
