### ISSUE TITLE
Connecting to a SSH server asks for the passkey 3 times

### ISSUE THREAD

**Issue by Abruptive** [microsoft/vscode-remote-release#1916]
Issue Type: <b>Bug</b>

Connecting to a SSH server asks for the passkey 3 times. More than that, it also asks for the password. And then it doesn't save, even with a SSH key file on in the /.ssh folder.

OS	Linux x64 3.10.0-957.12.2.el7.x86_64
CPUs	Intel(R) Xeon(R) CPU E3-1230 v6 @ 3.50GHz (8 x 800)
Memory (System)	15.46GB (0.78GB free)
VM	0%

Extension version: 0.47.2
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 19.0.0
Remote OS version: Linux x64 3.10.0-957.12.2.el7.x86_64

**Comment by roblourens** [comment]
Does the same thing happen when using ssh from an external folder? If not, could you share the full log from the "Remote - SSH" output channel?

![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)
