### ISSUE TITLE
When the computer goes to sleep, it cannot reconnect.

### ISSUE THREAD

**Issue by Abruptive** [microsoft/vscode-remote-release#1917]
Issue Type: <b>Bug</b>

After the computer lid was closed / went to sleep, the editor asks for the passkey again. Then, it doesn't ask for the password, and it gets stuck in "attempting to reconnect...". If you close it all and mount the SSH target folders again, it asks for the passkey and password, and connects successfully.

Extension version: 0.47.2
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 19.0.0
Remote OS version: Linux x64 3.10.0-957.12.2.el7.x86_64
Remote OS version: Linux x64 3.10.0-957.12.2.el7.x86_64

**Comment by roblourens** [comment]
Could you share the full log from the "Remote - SSH" output channel?

![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Comment by Abruptive** [comment]
So at first, it asks for the passkey. Then, it simply does this with no output:

[https://share.getcloudapp.com/geurxgG9](https://share.getcloudapp.com/geurxgG9)

**Comment by Abruptive** [comment]
It happened again and this was the output on a different computer:

![image](https://user-images.githubusercontent.com/8274669/70000811-5ed2af00-1564-11ea-9428-754aeacd30c9.png)

**Comment by Abruptive** [comment]
Not sure if that's the latest log through because it looks like a different timezone. Any other ways to debug?

**Comment by Abruptive** [comment]
![image](https://user-images.githubusercontent.com/8274669/70005352-ff7b9b80-1571-11ea-86e0-7f484851de5e.png)

**Comment by Abruptive** [comment]
![image](https://user-images.githubusercontent.com/8274669/70005389-2043f100-1572-11ea-8ab5-42fc4883893e.png)

**Comment by roblourens** [comment]
I'm looking for the log from the ssh extension, like in my screenshot
