### ISSUE TITLE
opening container workspace results in blank unresponsive screen

### ISSUE THREAD

**Issue by eedwards-sk** [microsoft/vscode-remote-release#1918]
- VSCode Version: 1.40.2
- Local OS Version: Darwin x64 19.0.0
- Remote OS Version: Debian GNU/Linux 9 (stretch)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open Container Workspace
2. Screen goes blank (background color) -- unresponsive, can only close window by using the red button, no menu bar actions or anything will work (even close window or cmd+w)

Notes:

This is intermittent, but seems to be exacerbated by having multiple vscode windows open with multiple dev containers running.

I would like help getting access to debug information so I can determine what the window is doing when it's hung.

![Screen Shot 2019-11-27 at 3 28 57 PM](https://user-images.githubusercontent.com/34585329/69760631-a56e7680-112a-11ea-9a58-77d114aa0b81.png)

```
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: I don't know. The problem is intermittent.

**Comment by chrmarti** [comment]
This sounds like a general issue, not necessarily related to Remote-Containers.

Have you seen this without opening a container too?

**Comment by eedwards-sk** [comment]
This only occurs when opening a workspace using a dev container.

How do I debug?

**Comment by chrmarti** [comment]
@deepak1556 You seem to be tracking a few similar issues. Is this a duplicate?

**Comment by deepak1556** [comment]
This could have been https://github.com/microsoft/vscode/issues/85338 but that is easily reproducible with just having multiple windows open and its not an unresponsive scenario, just rendering issue, triggering a repaint by window minimize , restore would resolve the issue. This looks different, also the fix for it is in the version thats mentioned in this issue.

Might want to check the logs when this issue happens to be sure.

**Comment by eedwards-sk** [comment]
> Might want to check the logs when this issue happens to be sure.

Hey, thank you -- what is the recommended log or log location I should check?

**Comment by eedwards-sk** [comment]
Also, it doesn't seem like #85338 at a glance -- my issue only occurs when opening a workspace, and only with the one in the foreground.
