### ISSUE TITLE
Standard go demo can't connect to port

### ISSUE THREAD

**Issue by themotu** [microsoft/vscode-remote-release#192]
Issue Type: <b>Bug</b>

Port is mapped, shows it's running but curling both container and localhost doesn't work. Changed port and rebuilt a couple times but no go.

Extension version: 0.48.0
VS Code version: Code - Insiders 1.34.0-insider (daf71423252a707b8e396e8afa8102b717f8213b, 2019-05-06T22:03:41.613Z)
OS version: Linux x64 4.17.6-041706-generic snap
Remote OS version: Linux x64 4.17.6-041706-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1852)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|15.44GB (0.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Go|
|OS|Linux x64 4.17.6-041706-generic|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1852)|
|Memory (System)|15.44GB (0.99GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment]
@themotu please provide more information: which demo, what extension are you using (remote-wsl, remote-containers, remote-ssh).

**Comment by themotu** [comment]
Golang container demo

**Comment by chrmarti** [comment]
How are you launching the server.go? Does it print 'Server listening on port ...' to stdout?
