### ISSUE TITLE
Neither curl nor wget is installed - can't download the Server

### ISSUE THREAD

**Issue by p-mayr** [microsoft/vscode-remote-release#1921]
- VSCode Version: 1.40.2
- Local OS Version: Win10
- Remote OS Version: Ubuntu bionic (company dev server, without internet) 
- Remote Extension/Connection Type: SSH

Error: "Neither curl nor wget is installed - can't download the Server"

Our company dev servers are not connected to the internet, neither wget or curl is installed. Is this dependency really necessary if the "Allow Local Server Download" is selected and scp should be used? 

If I manually download and copy the extension to the remote server I can successfully connect to it. 
But if I want to open a folder it reconnects and I receive the error mentioned above.

Thanks!

**Comment by roblourens** [comment]
Yeah, it should fall back on the local download in this case.

**Comment by p-mayr** [comment]
Okay, thanks for clarifying. For now, is there any workaround possible to force local src download, that I can use this awesome extension?

**Comment by roblourens** [comment]
I suspect you could add a script to your path named `curl` that just does `exit 1` or something. Will try to fix this the right way on my end though.

**Comment by connor4312** [comment]
verified by moving curl and wget out of my PATH, saw it fall back to scp automatically
