### ISSUE TITLE
Change server download URL from configuration.

### ISSUE THREAD

**Issue by leoleoasd** [microsoft/vscode-remote-release#1926]
Sometimes. the host and the client are in the same local network and have no access to the internet. If we can build a download server under the local network and change the download URL from configuration, it would be great.

**Comment by roblourens** [comment]
Are you using SSH? When the host has no internet access, the server should be downloaded on the client side already. If this doesn't work, please include the log.

**Comment by leoleoasd** [comment]
> Are you using SSH? When the host has no internet access, the server should be downloaded on the client side already. If this doesn't work, please include the log.

Yes, I'm using SSH. Sometimes the "Got request to download server archive" never showed up and the initializing progess end due to time out. I tried it again and again to get those logs but now it works fine. Are these logs stored somewhere so i can find it?

Also, in some condition, Both the host and the client have no internet access. What will happen if so?

**Comment by roblourens** [comment]
They may still be in your log directory (run "Open Logs Folder" and see nearby folders) but probably have been recycled.

> Both the host and the client have no internet access

This isn't supported yet but it's been requested.
