### ISSUE TITLE
code . return error after last update - errno: -4071

### ISSUE THREAD

**Issue by clemabd** [microsoft/vscode-remote-release#1929]
Hi, 

I updated my VS Code from 1.37 to 

Version: 1.40.2 (system setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

I use WSL and I enter `code .` to open a VS code on each service I work with. 

Since the last update, code . return : 
````
net.js:282
    err = this._handle.open(fd);
                       ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:282:24)
    at createWritableStdioStream (internal/process/stdio.js:179:18)
    at process.getStdout [as stdout] (internal/process/stdio.js:28:14)
    at Object.<anonymous> (C:\Program Files\Microsoft VS Code\resources\electron.asar\browser\init.js:43:13)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:850:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'uv_pipe_open'
}
````

I will revert to a previous version for the moment
Have a nice day

**Comment by aeschli** [comment]
That's a WSL issue (https://github.com/microsoft/WSL/issues/4511) that got visible with the new Electron version. 
Is it just an error in the console and does VSCode still open a remote window?

Also, note, you are on a quite old version of WSL (Windows 10, build 1709). If you can update, that would be solve your issue (I just tested on Windows 1803 and 1910 that opening from the command line works).

@sgehrman Not sure what you mean by 'I'm on Linux'. If you can file a new issue with the VSCode version and the WSL log, that would be great.

**Comment by BNJHope** [comment]
Hi 🙂 

Found a similar issue.

Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Trying to run the command `code --list-extensions` through a Python script. The Python instruction I run is:

`subprocess.run(cmd, shell=True, stdout=subprocess.STDOUT)`

where `cmd` = `cmd.exe /c code --list-extension` when running on WSL and `code --list-extension` when I run it in the command prompt. When I tested this in WSL with any of:
* `stdout=subprocess.STDOUT`
* `stdout=subprocess.PIPE`
* `capture_output=True`

then it has the exact error described above. When we remove any of these, it is no longer an issue. Also works totally as expected in command prompt.

Seems like an issue with opening up pipes for output therefore, potentially with the different interops coming into play being an issue too - hope this is helpful for fixing the issue 🙂

**Comment by ritchieanesco** [comment]
I just recently started to use WSL... Can anyone give a update on this or a workaround?

**Comment by adilmujeeb** [comment]
Any update on this?
I cannot update my Windows OS (Windows 10 - 1709), can i still use VS Code under WSL?

**Comment by aeschli** [comment]
It is only a message in the console, but opening VSCode on the remote WSL window should still work, correct?

**Comment by adilmujeeb** [comment]
> It is only a message in the console, but opening VSCode on the remote WSL window should still work, correct?

No it didnt work. After this error message nothing happened.

**Comment by aeschli** [comment]
You can always open VSCode from the Window side:
- in a Window command prompt: `code --remote=wsl+Ubuntu /home/user/foo`
- or from the remote menu (lower left corner): `Remote-WSL: Open Window...`

**Comment by adilmujeeb** [comment]
> You can always open VSCode from the Window side:
> 
> * in a Window command prompt: `code --remote=wsl+Ubuntu /home/user/foo`
> * or from the remote menu (lower left corner): `Remote-WSL: Open Window...`

Thanks for suggestions.

From command prompt, VS Code gives error - Unknown distro: Ubuntu. Don't know the reason.
From remote menu, i encountered different error. But when checking online, i found the issue under the URL https://github.com/microsoft/vscode-remote-release/issues/133
The workaround mentioned under comment https://github.com/microsoft/vscode-remote-release/issues/133#issuecomment-489627195 worked for me.

So from remote menu i can access / browse the file. But not from WSL command prompt or windows command prompt. My distro is Ubuntu 18.04

**Comment by aeschli** [comment]
Try `code --remote=Ubuntu-18.04`

Looks look you are behind a proxy. Setting the proxy URLs in /etc/wgetrc is probably the best solution, so you only need to do that once.
See
https://github.com/microsoft/vscode-remote-release/issues/133#issuecomment-499476237
