### ISSUE TITLE
Occur Error "TERM environment variable not set"

### ISSUE THREAD

**Issue by rivergold** [microsoft/vscode-remote-release#193]
- VSCode Version: 1.34.0-insider
- Local OS Version: Ubuntu 18.04
- Remote OS Version: CentOS 7
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
**I want to use vscode-remote to connect a remote server which is behind a Gateway Server (also named jump server).** The  connect command in terminal is like `export Variable=<variable data>; ssh hostname@ip -o SendEnv=Variable`. How to use it in VSCode remote and config it ssh_config?

Does this issue occur when you try this locally?: Not test
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by rivergold** [comment]
I find that `ssh -T` caused this error. Is it possible to set `Remote-SSH` without `-T`?

**Comment by roblourens** [comment]
We don't use this anymore
