### ISSUE TITLE
Add path specification to Connect To Host..

### ISSUE THREAD

**Issue by dorianfm** [microsoft/vscode-remote-release#1932]
Rather than having to connect to host then open a folder (and thus an extra window) it would be great if I could just enter the path I want to connect to

eg: example.com/path/to/project/

And that was opened directly, rather than having to jump through several steps. 

(On a related note it would be good if the 'Open Folder' button, once connected, could be configured to open in the same window, not open a new one) 

Thanks!

**Comment by roblourens** [comment]
I don't think we can provide a good experience here since we can't show a real folder picker or validate the path until we are connected. Also the Open Folder menu should open in the same window by default, but this can be customized, e.g. with `window.openFoldersInNewWindow`
