### ISSUE TITLE
Unable to detect Docker on macOS

### ISSUE THREAD

**Issue by andyli** [microsoft/vscode-remote-release#1933]
- VSCode Version: 1.40.2
- Local OS Version: macOS 10.15.1
- Remote Extension/Connection Type: Docker
- "Remote - Containers" Version: 0.83.1

Steps to Reproduce:

1. "open folder in container"
2. Got "Docker version 17.06.1 or later required"

<img width="1060" alt="Screenshot 2019-12-02 at 8 12 51 PM" src="https://user-images.githubusercontent.com/103977/69958665-46509d80-1540-11ea-8202-cc1851f40898.png">

Within the vscode terminal panel:
```
andy@Andys-MBP aports % docker version --format '{{.Server.Version}}'
19.03.5
```

**Comment by andyli** [comment]
Just downgraded "Remote - Containers" to 0.83.0, which worked as expected.

**Comment by chrmarti** [comment]
The error in the console shows that docker is not on the PATH. Nothing changed in that area between 0.83.0 and 0.83.1.

Does it work when you launch VS Code from the dock? And when you launch it from a terminal?

**Comment by andyli** [comment]
Ah, indeed it's not related to any changes between 0.83.0 and 0.83.1. The problem occurs (with either version) when I launch Code using Fork's "Open in Visual Studio Code" feature. Everything works as expected if I launch Code with the dock or from a terminal.

**Comment by chrmarti** [comment]
Does Fork change the PATH, such that `docker` is not on it anymore?

**Comment by andyli** [comment]
I don't know. But I can still run docker in the terminal panel when I open code from Fork.

**Comment by schicks** [comment]
I also get this problem, when opening code using `code -r` in an existing terminal within code. If I instead launch vscode from iterm, I have no problems. 


    VSCode Version: 1.43.2
    Local OS Version: macOS 10.14.6
    Remote Extension/Connection Type: Docker
    "Remote - Containers" Version: 0.106.0

**Comment by chrmarti** [comment]
Another possible workaround is to set the Docker Path to the absolute path of the Docker executable. The setting is currently available with VS Code Insiders (will be in the upcoming VS Code 1.46):
![image](https://user-images.githubusercontent.com/9205389/83598099-2d658b00-a569-11ea-8c89-1c444180697c.png)

**Comment by sheldonhull** [comment]
> Another possible workaround is to set the Docker Path to the absolute path of the Docker executable. The setting is currently available with VS Code Insiders (will be in the upcoming VS Code 1.46):
> ![image](https://user-images.githubusercontent.com/9205389/83598099-2d658b00-a569-11ea-8c89-1c444180697c.png)

Is this for any platform? I need to only use this on macOS, as windows works fine. Would be good to know it won't break my settings between the two. Cheers

**Comment by chrmarti** [comment]
Platform specific settings are tracked as a feature request for VS Code in https://github.com/microsoft/vscode/issues/5595.
