### ISSUE TITLE
Test: Remote Containers using SSH transport

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1935]
Testing #636

- [x] macOS @mjbvz
- [x] linux @alexr00
- [x] windows @alexr00 

Complexity: 3

Note: Test from CorpNet. Otherwise use JIT VM Access (ask me).

Test using an `ssh://` URI as the `DOCKER_HOST` environment variable or the `"docker.host"` setting (install the Docker extension to get that setting):
- Add a user with your SSH public key (often `~/.ssh/id_rsa.pub`) to [chrmarti-docker-machine](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/22597fe7-6f99-41e2-a033-345a493ab393/resourceGroups/chrmarti-docker-machine/providers/Microsoft.Compute/virtualMachines/chrmarti-docker-machine/resetPassword). Ignore the fact that the interface seems to be resetting the SSH key; when you add a new username it will just add a new credential for that user.
- Add key to ssh-agent locally: `ssh-add ~/.ssh/id_rsa`.
- Test the connection: `ssh your_user@40.89.158.7`.
- And there add the user to the docker group: `sudo usermod -aG docker $USER`.
- Test attaching to a container (see [here](https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#testing-remote-containers)) with either the `DOCKER_HOST` environment variable or the `"docker.host"` setting set to `ssh://your_user@40.89.158.7`. (Note that when using the docker CLI yourself, that needs the `DOCKER_HOST` environment variable set.)

**Comment by joaomoreno** [comment]
Windows blocked by https://github.com/microsoft/vscode-remote-release/issues/1946

**Comment by chrmarti** [comment]
@joaomoreno That's the Docker extension's viewlet. The Remote Explorer should work. Please confirm.

**Comment by joaomoreno** [comment]
As I mentioned in the issue:

> When running `Attach to Running Container`, nothing happens

**Comment by joaomoreno** [comment]
I wasn't aware that we should also look into Remote Explorer. Anyway, it just loads forever:

![image](https://user-images.githubusercontent.com/22350/70058895-0d680580-15e0-11ea-8fe5-2ae6dba78dd7.png)

**Comment by JacksonKearl** [comment]
I don't have access to that VM configuration

**Comment by mjbvz** [comment]
@JacksonKearl You can run docker on ubuntu in parallels. I was able to verify one of my other items using that. 

Here are the instructions I followed:  https://docs.docker.com/install/linux/docker-ce/ubuntu/ and https://code.visualstudio.com/docs/remote/containers#_getting-started

**Comment by JacksonKearl** [comment]
@mjbvz Gave me access, but I cannot run docker commands without sudo:

```
jackson@chrmarti-docker-machine:~$ groups jackson
jackson : jackson docker
jackson@chrmarti-docker-machine:~$ docker run -d node:12 sleep infinity
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
```

This then gives the error in Code:
![image](https://user-images.githubusercontent.com/8586769/70110214-2930d300-1603-11ea-9b07-4b1793ccc995.png)

**Comment by chrmarti** [comment]
Sorry for the rough ride guys...

Connection from home is weak for me today, sometimes working, sometime not. Not sure if that has to do with the firewall (which should open using the JIT VM feature in the portal).

@JacksonKearl You might have to log out and back in to make the new group membership effective. I forgot to mention that.

**Comment by alexr00** [comment]
Per @chrmarti 's suggestions I used https://docs.docker.com/machine/drivers/hyper-v/ to create a local vm to test with and just copied my public key over.

**Comment by JacksonKearl** [comment]
Finding that I can no longer even ssh into the machine

**Comment by JacksonKearl** [comment]
Finding that the process hangs on the uname command?

![image](https://user-images.githubusercontent.com/8586769/70193155-25f52000-16b3-11ea-9257-a61ca8947a32.png)

**Comment by alexr00** [comment]
Since I had a working host from testing Windows, I also tested with Ubuntu by re-using the host. I tested that I could attach to the container I had from testing Windows, and I tested that I could attach to a new container that had never been attached to.

**Comment by alexr00** [comment]
@JacksonKearl what image are you using? I tried debian and node:12 and didn't get stuck at uname.

**Comment by chrmarti** [comment]
Getting stuck at `uname` is tracked with #1958. Thanks @alexr00 for also covering Linux!

**Comment by JacksonKearl** [comment]
@alexr00 I tried with alpine, debian, and node:12. And @chrmarti I don't think I had multiple windows, but possibly. @alexr00 thanks for covering Linux!
