### ISSUE TITLE
Test: Remote Containers UID/GID patching on Linux

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1936]
Testing #1155

- [x] linux @mjbvz
- [ ] linux @sbatten

Complexity: 3

Use a local user with different UID/GID than the image's user and verify the container's user has its UID/GID updated:
- Ideally set up a new user with non-trivial (not 1000) UID and GID on your Linux machine / VM and test with that user.
- This only works with single container setup. Use instructions [here](https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#testing-remote-containers), but use the Ubuntu 18.04 & Git definition.
- Add another user to the image by appending to the Dockerfile:
```Dockerfile
RUN groupadd -g 5678 mygroup
RUN useradd -u 1234 -g 5678 -m myuser
USER myuser
```
- Run the rebuild command (`Remote-Containers: Rebuild Container`)
- Open the terminal to verify that you run under `myuser` and run `id` in the terminal to check the numeric ids are those of your local user.
- Remove the `USER myuser` line and instead add `"remoteUser": "myuser"` to the `devcontainer.json` and rebuild the container again.
- Again check in the terminal with `id` that you are running under `myuser` with the local user's numeric ids.

**Comment by sbatten** [comment]
I assume this is intentional given the phrasing of the test item, but it is strange that the `remoteUser` setting takes effect on `Reload Window` but the uid syncing doesn't until rebuild. A technical limitation I assume.

**Comment by chrmarti** [comment]
@sbatten A point I hadn't considered. We might need to refine this further. Thanks.
