### ISSUE TITLE
Test: Remote Containers additional config properties

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1937]
Testing #1201 

- [x] Windows @sandy081
- [ ] anyOS @sbatten 

Complexity: 4

See instructions [here](https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#testing-remote-containers) on how to get to the various setups.

- Test the "remoteEnv" and "remoteUser" property for Dev Containers based on:
  - A single Dockerfile (or image).
  - Docker Compose.
  - Attaching to a container. (Use the command `Remote-Containers: Open Attached Container Configuration File...` to configure.)
  - Changes should apply after reload.
- Test the "containerEnv", "containerUser" and "mount" properties for a single Dockerfile.
  - Changes apply after rebuilding the container.

More information:

#### "remoteEnv" and "containerEnv"

"remoteEnv" and "containerEnv" are object maps specifying environment variables as key-value pairs. The difference between the two is that "containerEnv" applies to the entire container (e.g., you see these when attaching a shell using `docker exec -it <container-id> /bin/bash`) and only updates after rebuilding the container. "remoteEnv" only applies to the VS Code server (e.g., you see these in the integrated terminal) and updates after reloading the window.

#### "remoteUser" and "containerUser"

"remoteUser" and "containerUser" are usernames. To add additional users to a Docker image you can append the following to the Dockerfile:
```Dockerfile
RUN groupadd -g 5678 mygroup
RUN useradd -u 1234 -g 5678 -m myuser
RUN groupadd -g 6789 mygroup2
RUN useradd -u 2345 -g 6789 -m myuser2
```
"containerUser" applies to the entire container (e.g., when attaching a shell using `docker exec -it <container-id> /bin/bash` that shell runs with that user) and this only updates after rebuilding the container. "remoteUser" only applies to the VS Code server (e.g., you see it in the integrated terminal) and updates after reloading the window.

#### "mount"

"mount" is an array of strings following the Docker CLI's syntax for the `--mount` options. E.g., `"source=myvol2,target=/app"` or `"type=bind,source=/local/path,target=/app"`.

**Comment by sbatten** [comment]
@chrmarti I tested on macOS, the `mount` setting didn't have any autocompletion and I couldn't get it to work. No matter what I put in the `devcontainer.json`, there was no effect.
