### ISSUE TITLE
Test: Remote Containers settings for attached containers.

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1938]
Testing #1589

- [x] Windows @dbaeumer 
- [x] anyOS @deepak1556 

Complexity: 2

Use instructions [here](https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#testing-remote-containers) on how to get a container to attach to.

Test the `"settings"` property in the configuration for attached containers:
- Note that the config file applies to all containers of an image.
- When the container is attached to for the first time the settings are copied to the container.
- Once the settings have been copied to the container, they are only copied back to the config file.
- Verify that both the initial copying to the container and the updating of the config file after that work.

**Comment by deepak1556** [comment]
Works well 👍 , identified two issues wrt container workflow.
