### ISSUE TITLE
Test: Remote Containers provisioning and startup performance

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1939]
Test #1823 

- [ ] linux @RMacfarlane 
- [x] windows @roblourens 

Complexity: 3

Use instructions [here](https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#testing-remote-containers) to get a single container with a Dockerfile.

With a single container based on a Dockerfile, enable Debug log level to get timings in the Dev Container log terminal and measure on real hardware (not a VM, take at least 2 measurements each):
- Rebuilding the container.
- Opening the folder in the container after closing it for a while (there is a 10 seconds timeout).
- Reload the window.

Look for the `[xyz ms] Stop (xyz ms): Resolving remote` message for the measurement.

**Comment by roblourens** [comment]
- Rebuilding container
  - Insiders: 8641ms, 7334ms
- Opening after timeout
  - Insiders: 3440ms, 5500ms
- Reload window
  - Insiders: 679ms, 686ms

I was going to do the same tests in stable, but that version of the extension doesn't write the timings. But it feels faster!

**Comment by RMacfarlane** [comment]
Rebuilding container:
- 4077ms, 4004ms
Opening after timeout
- 1201ms, 1253ms
Reload window
- 339ms, 334ms

Awesome, really fast!
