### ISSUE TITLE
Visual Studio IntelliCode is not work

### ISSUE THREAD

**Issue by trobr** [microsoft/vscode-remote-release#194]
🚨 The issue tracker is not for questions 🚨
vscode-remote-release Extension version: 0.12.0
visual studio intellicode version:1.1.6
VS Code version: Code - Insiders 1.34.0-insider
OS version: win10 1809
Remote OS version: ubuntu16.04

I have installed the visual studio intellicode extension and python extension.The python extension is configure finish like this:
![image](https://user-images.githubusercontent.com/40254133/57278418-f6f4dc80-70d8-11e9-82fd-d6cd69683a98.png)
but intellicode do not work when I edit the python file,and this is the log in output window:
```
Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
```

**Comment by egamma** [comment]
Please file the issue against the python extension.
