### ISSUE TITLE
Container stopped during startup

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1944]
@dbaeumer sees the container being stopped during startup. Disabling the shutdown monitor works around it.

**Comment by chrmarti** [comment]
Could be related to #1958 or #1983. Will need to debug on your machine if neither of these fixes it. (#1983 is not fixed in the published version yet.)

**Comment by chrmarti** [comment]
Moving milestone for now.

**Comment by dbaeumer** [comment]
I couldn't reproduce this on latest Insider.

**Comment by chrmarti** [comment]
Closing as duplicate of #1958 or #1983. Thanks!
