### ISSUE TITLE
"installing dev container" never ends

### ISSUE THREAD

**Issue by skyttedk** [microsoft/vscode-remote-release#1947]
Issue Type: <b>Bug</b>

After updating Docker Desktop to version 2.1.0.5 I can no longer attatch to running containers on my local win 10 installation. In the details windows it stops at the following line: Run: docker cp 9dc96a5515f2f1b095f1f035731b58594c447c4d7e00e27d4e24ead753c1babb:/etc/passwd -

Extension version: 0.83.1
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362
Fetching remote diagnostics for 'attached-container+39646339366135353135663266316230393566316630333537333162353835393463343437633464376530306532376434653234656164373533633162616262' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (15.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|

Fetching remote diagnostics for 'attached-container+39646339366135353135663266316230393566316630333537333162353835393463343437633464376530306532376434653234656164373533633162616262' timed out.
</details>

**Comment by chrmarti** [comment]
Can you reset Docker Desktop to factory settings and retry? (Note that reseting removes all containers, images and volumes!)
