### ISSUE TITLE
Repository container workspaces are inconsistent in Open Recent

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#1948]
Testsing https://github.com/microsoft/vscode-remote-release/issues/1931

- I cloned and opened vscode-remote-try-node into vsc-test-volume
- I cloned and opened vscode-remote-try-python into vsc-test-volume
- I cloned and opened vscode-remote-try-python into vsc-test-volume with the folder vscode-remote-try-python2
This is what Open Recent looks like:
![image](https://user-images.githubusercontent.com/38270282/70056346-97fa3600-15db-11ea-91ab-e38408d9dbbc.png)

**Comment by egamma** [comment]
Fixed.
