### ISSUE TITLE
Link to container tutorial on readme doesn't work

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode-remote-release#1950]
Install the remote development extension pack.
In the readme for the extension, find the link to Containers Tutorial under the Getting Started section (it's this link http://aka.ms/vscode-remote/containers/tutorial)

Click the link. 

I get taken to https://www.microsoft.com/en-gb/?ref=aka

**Comment by Chuxel** [comment]
Good catch!  Updated the aka.ms link - you may not see it immediately due to browser caching.
