### ISSUE TITLE
Dev container gets stuck if I provide a remote user that does not exist

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-release#1952]
Testing #1937

Windows

If I provide a remote user that does not exits and reload, container gets stuck:

![image](https://user-images.githubusercontent.com/10746682/70063190-a5b5b880-15e7-11ea-8edf-f3a0c7d765d4.png)

**Comment by sbatten** [comment]
I saw this just happening many times randomly with no correlation to a specific one of these new settings.

**Comment by chrmarti** [comment]
Could be #1958.

**Comment by sbatten** [comment]
In my case, I can hit this with a single window calling rebuild container command

**Comment by chrmarti** [comment]
The log now has a corresponding error message.
