### ISSUE TITLE
No error/feedback when using an docker host without permissions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-remote-release#1953]
Issue Type: <b>Bug</b>

For #1935

**Repo**
1. Set `"docker.host": "ssh://40.89.158.7"` (note missing user name)
1. Now run the `Attach to running container` command

**Bug**
Nothing happens. I'd expect an error to be shown

In the dev tools, I see the following errors:

![Screen Shot 2019-12-03 at 11 54 32 AM](https://user-images.githubusercontent.com/12821956/70084723-b2281a00-15c3-11ea-85be-44d1ccce4542.png)

Extension version: 0.87.0
VS Code version: Code - Insiders 1.41.0-insider (97855786a014be2440751b038b373c3726e11fe8, 2019-12-03T05:35:54.992Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|-psn_0_7812979|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Cannot reach that host anymore, but I think this should be fixed with #1954 and #1955.
