### ISSUE TITLE
Color theme settings doesn't take effect immediately after rebuild

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-remote-release#1956]
When Testing https://github.com/microsoft/vscode-remote-release/issues/1938

Steps to Reproduce:

1) `Open Container Configuration File` and add a setting `"workbench.colorTheme": "Visual Studio Light"`

2) `Reopen in Container` and see that the color theme takes effect

3) Redo step 1) in container window with a new theme

4) Reload window and see the prompt to rebuild the container

5) Once container is rebuilt should see the new theme take effect, but it doesn't unless `Reload Window` command is used

Another side effect, might have same root cause.

1) After step 5) when the new theme is in effect use `Attach to running container` and the newly attached window will have the theme from step 1) unless it is reloaded too.

**Comment by chrmarti** [comment]
I sometimes see it switch back to Dark+ after attaching to a container with the Light theme configured. /cc @sandy081

**Comment by sandy081** [comment]
Can you please try switching themes back and forth works when container window is open?

**Comment by chrmarti** [comment]
Switching themes works. There seems to be a cache somewhere, I just opened a folder in a container and it switched to the Light theme although that was not configured in any of the three possible settings JSONs.

**Comment by sandy081** [comment]
Can you please check if this is same case for all settings or only for themes?

**Comment by chrmarti** [comment]
It's the only one I see this with (after trying a few).

**Comment by sandy081** [comment]
Then I think the cache could be at theming. @aeschli any idea?

**Comment by aeschli** [comment]
The theme service first uses a persisted theme and listens for configuration change events.
I would expect to be a change event once the machine settings are read.

**Comment by sandy081** [comment]
Ok assigning myself to investigate.

**Comment by sandy081** [comment]
@chrmarti I can repro it but I am not able to debug this out of sources ie., VS Code Dev + Dev Container extension as I am seeing following error while opening

```
[8 ms] Start: Resolving remote
[9 ms] Setting up container for folder or workspace: /Users/sandy081/work/vscode-dev-containers/containers/typescript-node-12

[11 ms] Start: Run: git rev-parse --show-toplevel
[23 ms] Start: Check Docker is running
[23 ms] Start: Run: docker info
[129 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/sandy081/work/vscode-dev-containers/containers/typescript-node-12 --filter label=vsch.quality=undefined
[166 ms] Start: Run: docker build -f /Users/sandy081/work/vscode-dev-containers/containers/typescript-node-12/.devcontainer/Dockerfile -t vsc-typescript-node-12-9425b5c6c267d4a2a79cc929975c85b9 /Users/sandy081/work/vscode-dev-containers/containers/typescript-node-12/.devcontainer
Sending build context to Docker daemon  5.632kB
Step 1/5 : FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:12
12: Pulling from vscode/devcontainers/javascript-node
1c6172af85ee: Pull complete 
b194b0e3c928: Pull complete 
1f5ec00f35d5: Pull complete 
93b1353672b6: Pull complete 
3d7f38db3cca: Pull complete 
21e102f9fe89: Pull complete 
224a0b313ce8: Pull complete 
24ea7952e196: Pull complete 
0cffdcdd6d94: Pull complete 
e02b973a6eb7: Pull complete 
Digest: sha256:6c5382a8ef00f006d3f411cb28cead5aa0523a3b43bd060c424b5afef74e30cb
Status: Downloaded newer image for mcr.microsoft.com/vscode/devcontainers/javascript-node:12
 ---> 6005cce56e5a
Step 2/5 : ARG USERNAME=node
 ---> Running in b1118538a441
Removing intermediate container b1118538a441
 ---> c51ab6de1452
Step 3/5 : ARG USER_UID=1000
 ---> Running in 4eba155cf79b
Removing intermediate container 4eba155cf79b
 ---> 4dd22b0fb8f2
Step 4/5 : ARG USER_GID=$USER_UID
 ---> Running in b825850a3daf
Removing intermediate container b825850a3daf
 ---> 4f1622d80635
Step 5/5 : RUN if [ "$USER_GID" != "1000" ] || [ "$USER_UID" != "1000" ]; then         groupmod --gid $USER_GID $USERNAME         && usermod --uid $USER_UID --gid $USER_GID $USERNAME         && chown -R $USER_UID:$USER_GID /home/$USERNAME;     fi     && sudo -u ${USERNAME} npm install -g tslint typescript
 ---> Running in 45ac7973178b
npm WARN deprecated tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
/usr/local/share/npm-global/bin/tslint -> /usr/local/share/npm-global/lib/node_modules/tslint/bin/tslint
/usr/local/share/npm-global/bin/tsc -> /usr/local/share/npm-global/lib/node_modules/typescript/bin/tsc
/usr/local/share/npm-global/bin/tsserver -> /usr/local/share/npm-global/lib/node_modules/typescript/bin/tsserver
+ tslint@6.1.2
+ typescript@3.9.5
added 38 packages from 21 contributors in 6.526s
Removing intermediate container 45ac7973178b
 ---> b701978fc47e
Successfully built b701978fc47e
Successfully tagged vsc-typescript-node-12-9425b5c6c267d4a2a79cc929975c85b9:latest
[121065 ms] Start: Run: docker inspect --type image vsc-typescript-node-12-9425b5c6c267d4a2a79cc929975c85b9
[121110 ms] Start: Run: docker create sha256:b701978fc47e1160c6c504ed821eec87e491c7e880acfae156ce7b9c1a529737
[121196 ms] Start: Run: docker exec -i -u root 852b70c4b66e9f28b26dbf79dacd0a32f9b5aaa60d8913e675714c8ef4a1ad2c cat /etc/passwd
[121234 ms] 
[121234 ms] Error response from daemon: Container 852b70c4b66e9f28b26dbf79dacd0a32f9b5aaa60d8913e675714c8ef4a1ad2c is not running

[121235 ms] Start: Run: docker rm 852b70c4b66e9f28b26dbf79dacd0a32f9b5aaa60d8913e675714c8ef4a1ad2c
[121238 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/sandy081/work/vscode-dev-containers/containers/typescript-node-12 --filter label=vsch.quality=undefined
[121273 ms] Command failed: cat /etc/passwd
```

Can you please investigate or help me in debugging this out of sources?

**Comment by chrmarti** [comment]
@sandy081 Is this with the latest commit of vscode-dev-containers?

**Comment by sandy081** [comment]
I am not sure what you mean by that.. but I used the latest version of vscode-dev-containers extension.

**Comment by chrmarti** [comment]
@sandy081 This appears to be on Linux, right?

**Comment by chrmarti** [comment]
@sandy081 Try setting the `"commit"` in the product.json to the lastest Insiders commit hash.

**Comment by chrmarti** [comment]
@sandy081 You also need to `yarn add https://github.com/microsoft/vsda.git\#660658da0a7c0df399037d0a47d5640fe588119d` in the vscode folder.

Longer term it would make sense to get this again running with the server running out of source, but that is currently broken and needs work to get it back.

**Comment by sandy081** [comment]
This is working for me now. Hence closing this.
