### ISSUE TITLE
Infinite waiting if devcontainer.json "remoteUser" is set to a user that does not exist

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-remote-release#1957]
Issue Type: <b>Bug</b>

For #1936

**Repo**
1. Create a simple container workspace.
1. In the devcontainer.json, set `remoteUser` to a user name that does not exist
1. Try opening the workspace in a container

**Bug**
Connection never completes.

Here's what I see in the `details`:

```
[0 ms] Start: Resolving remote
[14 ms] Setting up container for folder or workspace: /home/matt/Documents/test

[28 ms] Start: Check Docker is running
[103 ms] Start: Run: git rev-parse --show-toplevel
[146 ms] Start: Inspecting container
[400 ms] Start: Run in container: uname -m

```

Extension version: 0.87.0
VS Code version: Code - Insiders 1.41.0-insider (97855786a014be2440751b038b373c3726e11fe8, 2019-12-03T05:31:49.954Z)
OS version: Linux x64 4.15.0-72-generic
Remote OS version: Linux x64 4.15.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (2 x 2194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|6.31GB (2.99GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|57%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js 12|
|OS|Linux x64 4.15.0-72-generic|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (2 x 2194)|
|Memory (System)|6.31GB (2.99GB free)|
|VM|0%|
</details>

**Comment by sbatten** [comment]
This issue came up in the other remoteUser test plan item. Again, I hit this (now on Linux, not macOS), randomly regardless of using that setting. Below is a screenshot without using the `remoteUser` setting.

![image](https://user-images.githubusercontent.com/6561887/70104557-478ed280-15f3-11ea-8963-14bde2803f87.png)
