### ISSUE TITLE
Move attached containers to dev containers

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-remote-release#1963]
Testing https://github.com/microsoft/vscode-remote-release/issues/1938

The container is still shown as attached although I closed the VS Code instance that was attached to it.

<img width="392" alt="capture" src="https://user-images.githubusercontent.com/1931590/70133180-eb28c300-1685-11ea-8deb-64ad2acd672c.png">

**Comment by alexr00** [comment]
"Attached Containers" are containers that you _can_ attach to. This looks correct since it doesn't have the green currently-connected-with-this-window icon.

**Comment by dbaeumer** [comment]
I have to say that the wording is pretty misleading. For me "Attached Containers" are containers I am attached to :-) I would never look for a green circle

**Comment by dbaeumer** [comment]
And actually it is not true. This container I have been attached to and now shows up as Other Containers.

<img width="265" alt="capture" src="https://user-images.githubusercontent.com/1931590/70135268-039adc80-168a-11ea-850d-946a2a15bcaf.png">

**Comment by dbaeumer** [comment]
<img width="848" alt="capture" src="https://user-images.githubusercontent.com/1931590/70135325-27f6b900-168a-11ea-9459-dcf79d6a0a90.png">

**Comment by alexr00** [comment]
We only move the container from Other to Attached once you've opened a folder.

**Comment by dbaeumer** [comment]
I would have never guessed this :-). 

I am also not convinced that this is something others will understand easily. Is this not something that is more a Favorite or Last recently used concept. That I would understand :-)

**Comment by alexr00** [comment]
That's actually what we're using to tell whether a container is Attached or Other. We use the recently opened folders and populate much of the view from there. 
@chrmarti what do you think of changing "Attached" to "Recently Attached"?

**Comment by chrmarti** [comment]
The currently attached container would also show under "Recently Attached"? 🤔

**Comment by alexr00** [comment]
Yes, it would just be a string change in the tree.

**Comment by chrmarti** [comment]
The distinction between Attached Containers and Dev Containers is becoming more artificial as we extend the attach case. Maybe we could have them all under Dev Containers.

**Comment by dbaeumer** [comment]
That makes sense to me. We could also thing about removing `Dev` and simply call them containers. I know that I am developing :-)

**Comment by alexr00** [comment]
Attached containers now show under Dev containers. They do still have different actions since that is needed.
