### ISSUE TITLE
Internet Connection Failure

### ISSUE THREAD

**Issue by huseyindeniz** [microsoft/vscode-remote-release#1967]
Issue Type: <b>Bug</b>

For the last 3-4 months when I am working with VS Code, if I connected to my WSL with WSL Remote extension, after a while my internet connection is broken. I mean, my network adapter says I'm connected to the Internet. I can even ping websites. However, no program on my computer can access to the internet. Outlook, MS Teams, all browsers, Skype and so on can not access to the internet. In the meantime, if I turn off the VS Code the internet comes back. Because of this problem, I have to turn on / off VS Code at least 5 times a day.

PS: I found and opened the developer tools and got following console logs after connection gone.

![consolelog](https://user-images.githubusercontent.com/1695352/70142711-ee827580-16aa-11ea-849f-2fa2de3dfaaa.png)

Extension version: 0.40.3
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.48GB (7.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2601)|
|Memory (System)|15.48GB (7.79GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment]
There's nothing special we do in the WSL Remote extension except starting a server inside WSL and connecting to it.
Maybe WSL related? Do you use WSL1 or WSL2?

**Comment by huseyindeniz** [comment]
Hi @aeschli I use WSL 1 and you are right, normally it should be unrelated. But whenever I open VS Code, internet gone, and comes back when I closed it. 

PS: We checked our network with our support team. We didn't find anything in our network. I also check my computer. I found nothing.

**Comment by huseyindeniz** [comment]
Hi @aeschli 
FYI: I simply removed Remote WSL extension, but I didn't delete .vscode folder in WSL 1. I used Remote SSH for a while. And internet connection failure continued. Then I deleted .vscode folder and problem gone. I worked this way for a while. And today I switched to WSL 2, installed Remote WSL and connected with Remote WSL. I experienced no problem. It is possible that in WSL 1 there might be some problem in .vscode folder.

**Comment by altanka** [comment]
I am experiencing same issue for a long time. I've tried your way with WSL 1 but it didn't work for me. Also closing VS Code is not enough for me. Every time I experience this issue I have to restart LxssManager service.

**Comment by huseyindeniz** [comment]
@altanka  In first days, "closing VS Code" was not working like you said, I was resetting whole computer to solve the issue. After a while, only "closing VS Code" started to solve the problem. Right now I am using WSL 2 for ROS development. It works very well and fast. If it is possible try WSL 2, or use Remote SSH instead of Remote WSL until problem solved.

**Comment by edburns** [comment]
I opened a [related issue](https://github.com/microsoft/WSL/issues/4675) on the WSL github. Please consider upvoting.

**Comment by sweetim** [comment]
experience the same problem, one way to solve this problem is to restart this service
```

**Comment by aeschli** [comment]
Closing as dup of https://github.com/microsoft/WSL/issues/4675
