### ISSUE TITLE
Details section not showing current Repository Container by default

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1968]
Testing #1931

After opening a Repository Container, I'd expect the details section to show for that container.

![image](https://user-images.githubusercontent.com/9205389/70139774-79f00c80-1693-11ea-89e5-4f30c33d78f6.png)

**Comment by alexr00** [comment]
I thought I'd already filed an issue for this but now I can't find it. Thanks for reminding me!
