### ISSUE TITLE
Remove leading / from container name

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1969]
Testing #1931 

The leading / might be from the image name. It would look nicer if we removed that:
![image](https://user-images.githubusercontent.com/9205389/70140518-2b437200-1695-11ea-8f5d-db2daaf53b4a.png)

**Comment by egamma** [comment]
Can no longer reproduce 

![image](https://user-images.githubusercontent.com/172399/72339968-938b6780-36c7-11ea-82fa-280703d7dc53.png)

**Comment by egamma** [comment]
Reopen, still see it when using 'Open Repository in Container'
