### ISSUE TITLE
the file explorer become nothing after use go to definition (F12)

### ISSUE THREAD

**Issue by lfjbb** [microsoft/vscode-remote-release#1973]
![111](https://user-images.githubusercontent.com/35714131/70145375-df1b2080-16da-11ea-9261-ee3d59f81c17.PNG)

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
Please give details steps how you ended up in that situation.

**Comment by lfjbb** [comment]
just use VSCode with the github project "taurusai/kungfu".    please have a try.   just use a few minutes
