### ISSUE TITLE
"Containers" sidebar view has infinite loading bar

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1975]
When I open the remote explorer, I see a progress bar on the Containers view that never goes away. Sometimes the view is empty, sometimes it has containers listed in it, but in both cases, the progress bar is there even for a few minutes.

This is on Windows on a Surface Book 1

**Comment by alexr00** [comment]
I can't reproduce this one. Is there anything in the console? Are you doing things with the containers? We listen to docker events and they can be noisy (I tried to filter to only ones we care about, but they too can be noisy).

**Comment by roblourens** [comment]
I don't see anything in the console, and I'm not doing anything with containers right now. The docker agent is running.
