### ISSUE TITLE
Times in container tooltip

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1976]
Some of the times in the container tooltip are negative, like `Exited -2706 seconds`.

Also I think it should add "ago", and a time in the range of 2706 second should probably be in minutes.

**Comment by alexr00** [comment]
Added the "ago". 
We already "upgrade" to the next largest time unit if we can, but there's no handling of that for negative numbers. We shouldn't be getting negative numbers. Do you know what that value should have been? Are you seeing this with a local docker host or a remote docker host?

**Comment by roblourens** [comment]
Local docker host. It should have been relative recent. For older containers, I saw correct times like "Exited 50 days" or something.

**Comment by alexr00** [comment]
Should be fixed next time the containers extension is updated! If we can't get a real time, then we just don't show a time now.
