### ISSUE TITLE
Progress bar while downloading file

### ISSUE THREAD

**Issue by GeraldNDA** [microsoft/vscode-remote-release#1977]
If you want to transfer a large file from a remote computer onto the local one, there's no easy way to tell when the download is finished and whether the "downloaded file" is actually just a partial file if it stopped downloading for some reason i.e. downloading another file.

**Comment by GeraldNDA** [comment]
Turns out that this might be a duplicate of #1176, I would add that this is very important UX wise since the file exists in the desired directory but isn't actually fully downloaded and the user has no way to tell (other than file size) when it is done. This could also be solved by #1177 which was marked as out of scope. Even if a progress bar isn't possible, I would say some completion message/currently downloading message is warranted.

**Comment by aeschli** [comment]
Yes, sounds like a dup of #1176.

**Comment by xgdgsc** [comment]
How to stop a large file download?

**Comment by GeraldNDA** [comment]
I'm pretty sure downloading another file can stop a download or doing a file operation like renaming can do that. But the easy way would be just to reload window.
