### ISSUE TITLE
Remote-Containers: Create workspace volume mount as current user instead of root

### ISSUE THREAD

**Issue by nphmuller** [microsoft/vscode-remote-release#198]
- VSCode Version: 1.34.0-insider
- Local OS Version: Win 10 1903
- Remote OS Version: Debian GNU/Linux 9 (stretch)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:
1. Create dockerfile:
``` dockerfile
FROM node:lts
USER node
ENV HOME /home/node
```
2. Run `Open folder in Container...`
3. Open terminal to container in VSCode - The terminal should be logged in as `node@containerid`
4. Run `ls -l /workspaces` in container.

Result: The workspace folder and its files have `root:root` permission
Expected: The workspace folder and its files should have `node:node` permission

Note: 
This is not the same issue as https://github.com/microsoft/vscode-remote-release/issues/49
That issue described that new files are created with `root:root` permissions, while the container runs as `root` user. My issue describes that files are created as `root:root`, even when the container user is non-root (`node` in my example).

**Comment by nphmuller** [comment]
Take note that I can't simply `chown` from `postCreateCommand` because `postCreateCommand` runs as non-root and the volume is already owned by root at that point.

**Comment by nphmuller** [comment]
I guess this is more of a Docker issue then a remote-containers issue.
Docker uses the userid and groupid of the host when bind mounting host data. If the ids don't exist in the container it falls back to root.

There are work arounds for this, for example this project: https://github.com/boxboat/fixuid
See this issue for more info (it's closed, but the discussion is still ongoing): https://github.com/moby/moby/issues/7198.

Since I don't actually need this (my problem turned out the be the CIFS filesystem Docker uses when mounting Windows volumes), and this seems the wrong place for this issue, I'm going to close this.

**Comment by chrmarti** [comment]
Reopening to track this issue.

**Comment by chrmarti** [comment]
This seems to work as expected in the latest (requires VS Code Insiders). Could you check if you still see it @nphmuller ?

**Comment by nphmuller** [comment]
I can still repro the bug in 1.36.0-insider via the steps in the initial post.

**Comment by chrmarti** [comment]
You're right, it's Windows specific. I can create a file as user `node` and the file ends up showing `root:root` as ownership. Outside the container the file is owned by the current user.

That's all good except for `root` being shown as the owner inside the container. @Chuxel It might help documenting the quirks the mount points on the host filesystem have. This one for WIndows and #49 for Linux. Mac seems to do a proper mapping of user and group ownership.

**Comment by nphmuller** [comment]
@chrmarti I think the issue got closed because the ‘needs-more-info’ tag wasn’t removed. :)

**Comment by Chuxel** [comment]
@nphmuller You are right - reactivating.  😊

**Comment by Chuxel** [comment]
@nphmuller @chrmarti This has been updated in the docs.  I'm closing since the broader feature that is needed is tracked in #49 and to some extent #46 and #1050.
