### ISSUE TITLE
Reopen a workspace for a repository container hangs

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#1983]
1) Open a repository in a container 
2) Received an update notification from VS Code
3) Update VS Code
-> when reopening the container after reload, then the provisioning of the container will block.

![image](https://user-images.githubusercontent.com/172399/70256181-dfe49e80-173c-11ea-9bb6-26ec6807ee38.png)

The container gets provisioned when executing 'Reload in Container' in this state.

**Comment by chrmarti** [comment]
The monitoring process from the previous session checks if the container is in use after 10 seconds and that check fails when the new session is not fully set up yet.

Repros with the following in the devcontainer.json (no upgrade needed):
```
"postCreateCommand": "rm -f ~/.vscode-server-insiders/data/Machine/.postCreateCommandMarker ; sleep 10s",
```
To repro first rebuild the container with that property added and then reload. (Note that the `sleep 10s` slows down both operations.)

**Comment by alexr00** [comment]
Can be verified with v0.91.0.
