### ISSUE TITLE
Improper "Failed to save file, EACCESS permision denied"

### ISSUE THREAD

**Issue by tbenst** [microsoft/vscode-remote-release#1985]
I see the above error similar to https://github.com/microsoft/vscode-remote-release/issues/1008, however the files are created on the Host and on reboot the extensions are there & work. 

- VSCode Version: 1.40.1
- Local OS Version: Ubuntu 18.04
- Remote OS Version: NixOS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. install an extension locally
1. try to install extension remotely
2. get `Failed to save file, EACCESS permision denied`
3. reboot VScode and voila, it's there!

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by roblourens** [comment]
Are there any details to that error? Anything in devtools (Help > Toggle Developer Tools)?

**Comment by tbenst** [comment]
Not much there acutely on install:
```

onDidNotificationChange | @ | notificationsAlerts.ts:38
(anonymous) | @ | notificationsAlerts.ts:26
fire | @ | event.ts:580
addNotification | @ | notifications.ts:171
error | @ | notificationService.ts:57
(anonymous) | @ | extensionsList.ts:90
fire | @ | event.ts:580
(anonymous) | @ | actionbar.ts:459
fire | @ | event.ts:580
run | @ | actions.ts:193
processTicksAndRejections | @ | internal/process/task_queues.js:89
async function (async) |  | 
run | @ | actions.ts:190
onClick | @ | actionbar.ts:173
(anonymous) | @ | actionbar.ts:143
processImmediate | @ | internal/timers.js:439
```

But on loading the program, I get a bunch of access errors, like:
```
ERR EACCES: permission denied, open '/home/tyler/.vscode-server/extensions/njpwerner.autodocstring-0.4.0/package.json': Error: EACCES: permission denied, open '/home/tyler/.vscode-server/extensions/njpwerner.autodocstring-0.4.0/package.json'
```
The permissions on each of my packages are `-r--r--r--`, as I have them all installed declaratively using NixOS. All of these packages are already installed on both the server & client machine, but when I remote-ssh to server, none are listed, and I have to manually click install, which fails, and then restart, and the package is enabled. Not the end of the world but a bit odd as all the packages are already there. Is there some config file that's being written about what packages are available that's only used by `remote-ssh` but not a local Vscode?

**Comment by sandy081** [comment]
Please share the logs from the following locations
    - View -> Open View… -> Log (Remote)
