### ISSUE TITLE
Time out SSH shouldn't close editor windows so aggressively

### ISSUE THREAD

**Issue by alanhoyle** [microsoft/vscode-remote-release#1988]
- VSCode Version: 1.40.2
- Local OS Version: macOS 10.15.1
- Remote OS Version: RHEL 7.6
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. restore computer from sleep and have the SSH time out

Does this issue occur when you try this locally?: No (n/a)
Does this issue occur when you try this locally and all extensions are disabled?: No (n/a)

---------------

I am working on a project with remote SSH and I end up having half-a-dozen or so files open at the same time.  

About one in five times my computer wakes up from sleep and I have to "restore/reload" the remote window, I get a time out and another request to reconnect/restore/reload.  However, when it does that second restore/reload, most, if not all, of my editor panes disappear, and there's no easy way to restore my editor session.  I end up having to go to the explorer and manually search for and reopen the individual files, as they don't even appear in the "Open Recent" menu.  I see a few ways to fix this that might help others in other ways:  

1. Remote-SSH extension shouldn't be so aggressive in closing panes if there's a time-out.
2. Files opened in the manual search should end up in the "Open Recent" menu
3.  A new general feature to allow me to manually save a point-in-time of an editor view.  I could restore by reloading and it would restore the editor layout and which files are loaded into each editor.

**Comment by roblourens** [comment]
A couple things going on here... 

> About one in five times my computer wakes up from sleep and I have to "restore/reload" the remote window, I get a time out and another request to reconnect/restore/reload.

Is it normally slow to connect to your remote? Would a longer timeout help or do you think there is a separate issue in connecting to your remote?

> However, when it does that second restore/reload, most, if not all, of my editor panes disappear, and there's no easy way to restore my editor session

When you open a folder that you previously opened, it should always open the same editors you had open previously, and persist the "recently opened" files and so on. When this happens, does it have exactly the same folder open as before? Like you see the correct files in the Explorer?

The "Open recent" menu under the File menu won't contain files that were opened in the current folder, just files that were opened on their own outside of the folder. But you should see the previous files in the "recently opened" section in quick open (cmd+p)

**Comment by alanhoyle** [comment]
I'm not sure whether a longer timeout would help here.  The issue is that when there's a timeout and retry, it closes the editor panes before the second retry.

**Comment by roblourens** [comment]
Yes, it shouldn't do that, that's the second part of my questionss
