### ISSUE TITLE
Can't open two folders with different cases on remote

### ISSUE THREAD

**Issue by pc-tradelab** [microsoft/vscode-remote-release#199]
- VSCode Version:
Version: 1.34.0-insider
Commit: daf71423252a707b8e396e8afa8102b717f8213b
- Local OS Version:
OS: Linux x64 4.15.0-47-generic
- Remote OS Version:
OS: Linux x64 4.15.0-47-generic
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Create a "foo" folder on remote
2. Create a "Foo" folder on remote
3. Try to open "foo" then "Foo" in your workspace : you can't open "Foo" folder

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
Can you explain how you are trying to open "Foo", and how it doesn't work? I don't have any problem opening both of them although only one shows up in "Recently opened". VS Code in general has some issues with this scenario, https://github.com/microsoft/vscode/issues/12448, I don't think there is anything ssh-specific.

**Comment by pc-tradelab** [comment]
Hello,
I still have the problem with remote-shh 0.42.
To open the remote folder , right-clik on  workspace tab > Add Folder to Workspace, in the command palette, I type /home/Foo (/home/foo being already opened in the workspace), press enter , and nothing happens ( /home/foo is still opened and /home/Foo is not opened)
