### ISSUE TITLE
Resource manager doesn't show all directories

### ISSUE THREAD

**Issue by XiaoTianCan** [microsoft/vscode-remote-release#1990]
I used macos 10.12.6 to ssh a server with ubuntu 14.04. 

How to reproduce:
step 1: ssh to a remote server, and we can check files/directories in the resource manager
step 2: In a terminal, make two new directories named as "test" and "Test" respectively using command "mkdir" in a same existing directory
step 3: refresh the resource manager, then we can only find "test". "Test" is not shown. But we can find both of them through command "ls" in a terminal

**Comment by aeschli** [comment]
We currently treat all remote file systems as case-insensitive. That means `test` and `Test` look like the same file.
@isidorn The check whether a file system is case-sensitive or not is async. IMO the file explorer could add support for that and pass that a log all operations that are filtering or finding files.

**Comment by isidorn** [comment]
Yes the fileExplorer should check that asyncly and nowhere should we have code isWindows and the like.
Here's the issue that caputres that I believe https://github.com/microsoft/vscode/issues/48258

**Comment by isidorn** [comment]
Should be fixed via https://github.com/microsoft/vscode/issues/48258
Please try out vscode insiders from tomorrow
