### ISSUE TITLE
Multiple VSCode run on remote server opens only on first user

### ISSUE THREAD

**Issue by lucaRRRdev** [microsoft/vscode-remote-release#1992]
Issue Type: <b>Bug</b>

When 2 users are connected with Remote Desktop on a remote server, if one user runs VSCode, the second user cannot use it: it will open VSCode in the first user's session!

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
xml|Dot|2.5.0
azure-pipelines|ms-|1.157.4
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.9.0
vscode-logicapps|ms-|0.2.24
mssql|ms-|1.7.1
azure-account|ms-|0.8.7
powershell|ms-|2019.11.0
trailing-spaces|sha|0.3.1

</details>

**Comment by roblourens** [comment]
Do the users have the same `$HOME`? The server is installed here and we assume that there is one per user.

**Comment by lucaRRRdev** [comment]
Users have different home folders however we created 'data' subfolder within VSCode folder containing subfolders 'user-data' and 'extensions' so the application is really portable

**Comment by roblourens** [comment]
Sorry, I don't really understand what you're saying. Can you share a log from the Remote-SSH output channel when you try to connect?

**Comment by lucaRRRdev** [comment]
Likewise, I don't understand how your question relates to our issue.


Let me explain once more:

We have VSCode portable on a remote Win2016 server.

We have migrated to portable mode as explained in link https://code.visualstudio.com/docs/editor/portable.
"This mode enables all data created and maintained by VS Code to live near itself, so it can be moved around across environments."

The issue is then happening when 2 users (with admin rights) open a remote desktop session on the remote server.
When 1st user launch VSCode, all is OK.
When 2nd user launch VSCode, it does not open in his own session, but in the session of the 1st user.

Problem is occurring because we use this portable mode as all user and extensions data is common to both users.


Is this behavior by design or is anyone planning to fix it?

**Comment by roblourens** [comment]
Ok, I think I understand. You filed this issue in the `vscode-remote-release` repo, so I thought you were connecting with our "remote" extensions, e.g. Remote-SSH. But it sounds like you are not doing that, you are using remote desktop to use SSH.

Like you say, the two users are launching vscode with the same data directory. But, you can launch vscode with a manually specified user data directory by using the `--user-data-dir` flag. You can point that to any directory and then the new vscode instance will run independantly from the original instance.
