### ISSUE TITLE
The "install" terminal does not exit on win10

### ISSUE THREAD

**Issue by innerlee** [microsoft/vscode-remote-release#1993]
- VSCode Version: 1.40.2
- Local OS Version: latest win10 insider
- Remote OS Version: ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. connect to ssh remote in win10
2. there is a "install" terminal left. It is supposed to auto close.

Note:
On ubuntu, the "install" terminal can auto close successfully.

![image](https://user-images.githubusercontent.com/9464825/70368597-a603cb80-18e7-11ea-8510-6d6ebcaf30e0.png)

**Comment by roblourens** [comment]
Do you have `remote.SSH.showLoginTerminal` set? Can you try disabling it?

**Comment by innerlee** [comment]
Thank you so much! I set the flag for debugging months earlier and forgot...
