### ISSUE TITLE
Updates to user groups are not applied.

### ISSUE THREAD

**Issue by Xachman** [microsoft/vscode-remote-release#1997]
https://github.com/microsoft/vscode-remote-release/issues/658 My issue is the same as this closed issue. User groups are not updated until the system is restarted or something like that.  In my case I'm using SSH in a docker container.  After making updates to user groups the groups will not apply only in vscode until I restart the docker container.  I can SSH in a normal terminal and they are updated fine.

- VSCode Version: 1.40.2
- Local OS Version: Windows 10 Pro
- Remote OS Version: Debian
- Remote Extension/Connection Type: SSH/Docker/WSL  SSH

Steps to Reproduce:

1. Add User To Group
2. Reload VS code

Does this issue occur when you try this locally?: Yes/No No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No No

**Comment by chrmarti** [comment]
Is this the Remote-SSH or the Remote-Containers extension?

**Comment by Xachman** [comment]
This is Remote-SSH.  Im using docker containers and installing users and ssh in those containers.  But the connection is using the Remote-SSH extension.  This last time it happened I fixed it by killing my created users sshd and bash processes by process id.  I'm assuming based on that issue i noted that this isn't related to using docker and is just some product of how the connection is made.

**Comment by chrmarti** [comment]
The command `Kill VS Code Server on Host...` might also do it. /cc @roblourens

**Comment by roblourens** [comment]
Not sure what you mean by user groups. But, if you changed something about the environment then you may have to restart the server like @chrmarti suggests.

**Comment by Xachman** [comment]
@roblourens What I mean by user groups is linux groups.  Specifically running something like usermod -aG <group> <user>.    How do you restart the server?  Are you talking about the remote server or something else?

**Comment by roblourens** [comment]
Yeah, the remote server. Run the command `Kill VS Code Server on Host` then connect again.
