### ISSUE TITLE
Bugzpper

### ISSUE THREAD

**Issue by jkingon** [microsoft/vscode-remote-release#1999]
// ENABLE PREEMPTIBLE OPTION
gcloud compute instances create my-vm --zone us-central1-b --preemptible

- VSCode Version:
- Local OS Version:
- Remote OS Version:
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by jkingon** [comment]
Copy and paste and its should fix the problem

**Comment by jkingon** [comment]
Issue fixed no more problem remotely

**Comment by chrmarti** [comment]
I don't fully understand, but it sounds like you fixed the issue. Closing.
