### ISSUE TITLE
`machine` scope settings defined in user settings need to be ignored in the remote context

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#2]
When a `machine` scoped setting is defined in a user setting, then it needs to be ignored in a remote context.

**Comment by sandy081** [comment]
@roblourens I fixed it in the model and schema, can you please make sure the user settings in remote window does not show machine settings?

**Comment by roblourens** [comment]
Yeah I did that a long time ago

**Comment by egamma** [comment]
@roblourens @sandy081 can the issue be closed now?

**Comment by sandy081** [comment]
@roblourens Not sure if it is fixed in UI. I still see machine settings in user settings in remote window

![image](https://user-images.githubusercontent.com/10746682/58323965-cbd2f280-7e25-11e9-8776-8240641d9ca0.png)

**Comment by roblourens** [comment]
Oh I thought this was about app-scoped settings in the Remote tab.

**Comment by roblourens** [comment]
Wait are we sure we want to prevent this? It still seems like a valid way to configure things? Maybe I connect to lots of remotes that are configured the same way and I don't want to configure each remote independently?

If I set the setting in user settings JSON will it still be respected for the remote?

**Comment by sandy081** [comment]
Machine settings scoped to a machine and by definition they vary per machine. So I think it makes sense to not to respect local machine settings configured in user settings in a remote window.

**Comment by roblourens** [comment]
It seems like they likely vary per machine, but they don't have to, and if they don't, we are removing a potentially valid use case, for what benefit?

**Comment by roblourens** [comment]
Anyway I'll fix this and we can always tweak it later

**Comment by sandy081** [comment]
I would rather more concerned about if they vary which will break. 

@roblourens Instead of hiding machine settings in the user settings, is it possible to show them and add a warning icon? This will help users to understand about it?

**Comment by roblourens** [comment]
Sure but I think we should do the same for all settings that are invalid for the scope.

**Comment by isidorn** [comment]
I verified that the git.path does not show up both in the .json file and in the settings ux -> verified
