### ISSUE TITLE
Pick up `terminal.integrated.env.*` for running commands

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#200]
We currently don't pick up `terminal.integrated.env.*` when running these commands. (@alexr00 Are tasks doing that?)

@AngellusMortis What do you get for `PATH=/bin zsh -lic 'echo $PATH'`? That's what VS Code runs to extract the environment variables (it does it in a single pass).

_Originally posted by @chrmarti in https://github.com/microsoft/vscode-remote-release/issues/35#issuecomment-489921362_

**Comment by egamma** [comment]
answer from @alexr00 https://github.com/microsoft/vscode-remote-release/issues/35#issuecomment-490022164

**Comment by Chuxel** [comment]
@chrmarti @egamma Just to double check here, that comment indicated an expected behavior, but then a [later comment indicated a problem](https://github.com/microsoft/vscode-remote-release/issues/35#issuecomment-490234412) with it in VS Code Remote.  Just so I'm super clear, is this the feature request but #35 is a bug at this point?  (Or is the bug in #35 no longer an issue)

**Comment by chrmarti** [comment]
These are distinct issue. This one would help work around the bug in #35, but the cause of #35 is still unknown. We need to follow up in #35 on the tracing @joaomoreno added, but didn't seem to work when I tried it.

**Comment by Chuxel** [comment]
@chrmari Great, thanks - I had them merged in my head and in planning discussions which is incorrect.

**Comment by jamescasbon** [comment]
I think this is needed to support remote development.  Lets say I have two workspaces which require different $PATH settings.  Currently I have no way to set these.  I can use .bashrc to set a path, but it is picked up in both environments. 

If I were developing locally, I could launch two code processes 

    env PATH=/path/A code workspaces/A
    env PATH=/path/B code workspaces/B

but there is no equivalent for the opening a remote ssh workspace.

**Comment by chrmarti** [comment]
Applying all environment variables applied to the integrated terminal might not be what we need. There are now `"containerEnv"` and `"remoteEnv"` in the devcontainer.json to control environment variables too. Closing as out-of-scope.
