### ISSUE TITLE
Fail to attach vs code to container 

### ISSUE THREAD

**Issue by damienrj** [microsoft/vscode-remote-release#2003]
- VSCode Version:  1.40.2 
- Local OS Version: 10.15 (OSX)
- Remote OS Version: python:3.7.4-stretch
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. DOCKER_HOST=tcp://localhost:23750 code .
2. Attach shell works though it seems to connect twice.
```
docker exec -it 2d80aa7b4d39ffb3a1b918ac60267fa17d0292593f225a78f1534f9ed76496a2 /bin/sh -c "[ -e /bin/bash ] && /bin/bash || /bin/sh"
source /Users/damien/envs/empty/bin/activate
/Users/damien/.zshrc:161: operation not permitted: /dev/nulls

docker exec -it 2d80aa7b4d39ffb3a1b918ac60267fa17d0292593f225a78f1534f9ed76496a2 /bin/sh -c "[ -e /bin/bash ] && /bin/bash || /bin/sh"
root@damien-workstation:/current# source /Users/damien/envs/empty/bin/activate
bash: /Users/damien/envs/empty/bin/activate: No such file or directory
root@damien-workstation:/current# 
```
3. Attach Visual Studio code fails
```
Cannot attach to the container with id 2d80aa7b4d39ffb3a1b918ac60267fa17d0292593f225a78f1534f9ed76496a2, it no longer exists.
```
I can connect to local containers without issues, and this used to work until very recently.

**Comment by chrmarti** [comment]
On 3: Does `F1` > `Remote-Containers: Attach to Running Container...` work? (It looks like you recreated the container, but VS Code's history remembers only the previous id. This will improve with the next release where it remembers the container's name instead.)

Does that help?

On 2: These look like things changed on your local disk. E.g., what's in your `.zshrc` at line 161?  Is there still a `/Users/damien/envs/empty` environment?

**Comment by damienrj** [comment]
`Remote-Containers: Attach to Running Container...` gives the same error.  The container is running the whole time without failing `2d80aa7b4d39ffb3a1b918ac60267fa17d0292593f225a78f1534f9ed76496a2` is still running, and has been up for several days. 

On line 161 I was adding ssh keys, so I commented that out. It is interesting, it looks like the `bash: /Users/damien/envs/empty/bin/activate: No such file or directory` message is coming because I was using my python from my empty virtualenv.  Once I switched to the system python the message becomes 
```
docker exec -it 2d80aa7b4d39ffb3a1b918ac60267fa17d0292593f225a78f1534f9ed76496a2 /bin/sh -c "[ -e /bin/bash ] && /bin/bash || /bin/sh"

docker exec -it 2d80aa7b4d39ffb3a1b918ac60267fa17d0292593f225a78f1534f9ed76496a2 /bin/sh -c "[ -e /bin/bash ] && /bin/bash || /bin/sh"
root@damien-workstation:/current# 
```

**Comment by chrmarti** [comment]
Attaching to a container with `DOCKER_HOST=tcp://localhost:23750` works for me with the latest stable release 0.83.1 and the upcoming release's candidate 0.92.0 available for the VS Code Insiders build. Which version of Remote-Containers are you using?

**Comment by damienrj** [comment]
I was using the latest stable version 0.83.1, I just tried the insider version with the newest extension and it didn't work but am getting a more clear error and have an idea what is going on now because it gives a chance to look for other containers, but the containers it sees are the locally running ones, not the ones from the host.  
I am starting vs code via `DOCKER_HOST=tcp://localhost:23750 code .` and that works fine for the first instance of the IDE, but when I attach it is not looking at the docker_host.  I think the new window is not keeping this setting that was passed via startup. 

If I add it in the `setings.json` file I am able to attach correctly, but that used to not be needed. The reason it is not in the setting file is that we have is setup as an alias to quickly be able to start vs code pointing to either the local or remote docker host.  `code file` vs `remote code file`

**Comment by damienrj** [comment]
The main goal of using the environment variable is to make it easy to switch between local and remote docker without editing the setting file all time. Since the new window doesn't seem to see the environment variable DOCKER_HOST anymore is there a different way to switch docker hosts?

**Comment by chrmarti** [comment]
You can use the `"docker.host"` setting, that also works as a workspace setting, e.g. if you switch hosts depending on your workspace.

**Comment by chrmarti** [comment]
I can reproduce the problem when I keep another (unrelated) VS Code window open while changing DOCKER_HOST. We could pass DOCKER_HOST to the attaching window the same way we do for the "docker.host" setting to fix this.

**Comment by damienrj** [comment]
It turns out it still works on a labmates machine 

## Working Machine
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

eamodio.gitlens@10.2.0
lextudio.restructuredtext@116.0.0
liximomo.sftp@1.12.9
ms-azuretools.vscode-docker@0.9.0
ms-mssql.mssql@1.8.0
ms-python.python@2020.1.57204
ms-vscode-remote.remote-containers@0.94.0
njpwerner.autodocstring@0.4.0
yzhang.markdown-all-in-one@2.6.1
```

## Not working machine
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

eamodio.gitlens@10.2.0
foxundermoon.shell-format@7.0.0
lextudio.restructuredtext@116.0.0
liximomo.sftp@1.12.9
ms-azuretools.vscode-docker@0.9.0
ms-mssql.mssql@1.8.0
ms-python.python@2020.1.57204
ms-vscode-remote.remote-containers@0.94.0
ms-vsliveshare.vsliveshare@1.0.1456
njpwerner.autodocstring@0.4.0
searKing.preview-vscode@2.0.3
Shan.code-settings-sync@3.4.3
streetsidesoftware.code-spell-checker@1.7.20
Tyriar.sort-lines@1.9.0
yzhang.markdown-all-in-one@2.6.1
```

The thing that jumps out at me is `OS: Darwin x64 19.2.0` vs `OS: Darwin x64 18.7.0`
