### ISSUE TITLE
Fail to use C++ extension on remote ubuntu server

### ISSUE THREAD

**Issue by apeforest** [microsoft/vscode-remote-release#2005]
Issue Type: <b>Bug</b>

```
[Error - 3:15:55 PM] Starting client failed
Launching server using command /home/ubuntu/.vscode-server/extensions/ms-vscode.cpptools-0.26.2/bin/Microsoft.VSCode.CPP.Extension.linux failed.
```

I logged onto the remote server and could not find the folder .vscode-server as indicated.

Extension version: 0.40.3
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 17.7.0
Remote OS version: Linux x64 4.4.0-1096-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 34.221.97.252|
|OS|Linux x64 4.4.0-1096-aws|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (64 x 1201)|
|Memory (System)|480.28GB (471.56GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Are you using SSH for remote? Can you make sure you have the latest version of the extension and share the log from the Remote-SSH output channel?
