### ISSUE TITLE
Remote server binds to inappropriate network interfaces

### ISSUE THREAD

**Issue by andrask** [microsoft/vscode-remote-release#2011]
Running the remote server interactively shows that it is not bound to the localhost address:

    $ bash -x /home/myuser/.vscode-server/bin/f359dd69833dd8800b54d458f6d37ab7c78df520/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown --port=0

    + case "$1" in
    ++ dirname /home/myuser/.vscode-server/bin/f359dd69833dd8800b54d458f6d37ab7c78df520/server.sh
    + ROOT=/home/myuser/.vscode-server/bin/f359dd69833dd8800b54d458f6d37ab7c78df520
    + /home/myuser/.vscode-server/bin/f359dd69833dd8800b54d458f6d37ab7c78df520/node /home/myuser/.vscode-server/bin/f359dd69833dd8800b54d458f6d37ab7c78df520/out/vs/server/main.js --host=0.0.0.0 --enable-remote-auto-shutdown --port=0

    *
    * Visual Studio Code Server
    *
    * Reminder: You may only use this software with Visual Studio family products,
    * as described in the license https://aka.ms/vscode-remote/license
    *

    IP Address: 192.168.0.121
    IP Address: 192.168.0.7
    Extension host agent listening on 38603

    [11:01:06] Extension host agent started.

The addresses of eth0 are used instead of the loopback interface.

As a result, the VSCode GUI shows two errors:
    
     Could not fetch remote environment
     Failed to connect to the remote extension host server (Error: Time limit reached)

Changing the --host parameter does not fix the issue. The binary seems to bind to the eth0 addresses only.

On erroneous --host names the following an error is shown and the eth0 addresses are bound:

    $ /home/myuser/.vscode-server/bin/f359dd69833dd8800b54d458f6d37ab7c78df520/server.sh --host=nonexistent --enable-remote-auto-shutdown --port=2112

    *
    * Visual Studio Code Server
    *
    * Reminder: You may only use this software with Visual Studio family products,
    * as described in the license https://aka.ms/vscode-remote/license
    *

    IP Address: 192.168.0.121
    IP Address: 192.168.0.7
    [11:23:36] Error occurred in server
    [11:23:36] Error: getaddrinfo ENOTFOUND nonexistent
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'nonexistent'
    }

Steps to Reproduce:

1. connect to remote host with multiple nics
2. eth0 should be a non-routed address (it is not clear if the IP is used by the client to connect or only the port)

Expected behavior:

1. the --host parameter must be respected by the server component
2. the error messages should contain more diagnostic information to show what connections were attempted and what configuration the server is using currently.

Version info:

- VSCode Version: 1.40.2
- Local OS Version: Linux x64 4.4.0-170-generic
- Remote OS Version: Centos 7.7
- Remote Extension/Connection Type: SSH/Docker/WSL

**Comment by roblourens** [comment]
That's not the host that the server is listening on, it's just logging the result of `os.networkInterfaces()`. Why are you trying to start the server manually?

Are you using the Remote-SSH extension? Can you share the log from the Remote-SSH output channel?

**Comment by roblourens** [comment]
Maybe it shouldn't log that if `--host` is used? @alexdima

**Comment by andrask** [comment]
@roblourens Thank you for your reponse. I'm sorry. vscode was unable to establish connection to the started server components and showed the errors notifications I mentioned:

    Could not fetch remote environment
    Failed to connect to the remote extension host server (Error: Time limit reached)

I tried to diagnose what was happening.

I repeated the test. Seems like node was really bound to 127.0.0.1:

    $ sudo ss -lntp | grep node
    LISTEN     0      128    127.0.0.1:45932                    *:*                   users:(("node",pid=3050,fd=18))

    $ curl -v 127.0.0.1:45932
    * About to connect() to 127.0.0.1 port 45932 (#0)
    *   Trying 127.0.0.1...
    * Connected to 127.0.0.1 (127.0.0.1) port 45932 (#0)
    > GET / HTTP/1.1
    > User-Agent: curl/7.29.0
    > Host: 127.0.0.1:45932
    > Accept: */*
    > 
    < HTTP/1.1 404 Not Found
    < Content-Type: text/plain
    < Date: Sat, 14 Dec 2019 07:32:27 GMT
    < Connection: keep-alive
    < Transfer-Encoding: chunked
    < 
    * Connection #0 to host 127.0.0.1 left intact
    Not found

Here is the output of the install terminal: (I didn't notice this because it closed automatically once the server download finished)

    e113cb1e8cb8: running
    Acquiring lock on /home/myuser/.vscode-server/bin/f359dd69833dd8800b54d458f6d37ab7c78df520/vscode-remote-lock.f359dd69833dd8800b54d458f6d37ab7c78df520
    Installing to /home/myuser/.vscode-server/bin/f359dd69833dd8800b54d458f6d37ab7c78df520...
    Downloading with wget
    wget download failed

    LC_PAPER=hu_HU.UTF-8
    LC_ADDRESS=hu_HU.UTF-8
    XDG_SESSION_ID=5439
    LC_MONETARY=hu_HU.UTF-8
    HOSTNAME=speciallocalhostname.internal
    SHELL=/usr/sbin/wsh
    HISTSIZE=1000
    SSH_CLIENT=10.x.x.x 45706 22
    DOCKER_HOST=tcp://127.0.0.1:2376
    LC_NUMERIC=hu_HU.UTF-8
    USER=myuser
    LC_TELEPHONE=hu_HU.UTF-8
    MYSQL_HISTFILE=/dev/null
    LESSSECURE=1
    TMOUT=300
    DOCKER_TLS_VERIFY=1
    VSCODE_AGENT_FOLDER=/home/myuser/.vscode-server
    PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/myuser/.local/bin:/home/myuser/bin:/opt/nokia/myuser/bin
    MAIL=/var/spool/mail/myuser
    LC_IDENTIFICATION=hu_HU.UTF-8
    PWD=/home/myuser/.vscode-server/bin/f359dd69833dd8800b54d458f6d37ab7c78df520
    LANG=en_US.UTF-8
    LC_MEASUREMENT=hu_HU.UTF-8
    HISTCONTROL=ignoredups
    HOME=/home/myuser
    SHLVL=2
    LOGNAME=myuser
    SSH_CONNECTION=10.x.x.x 45706 192.168.0.12 22
    LESSOPEN=||/usr/bin/lesspipe.sh %s
    XDG_RUNTIME_DIR=/run/user/1001
    LC_NAME=hu_HU.UTF-8
    _=/usr/bin/printenv
    OLDPWD=/home/myuser
    Trigger client server download
    VSCODE_ARCH==x64==
    e113cb1e8cb8__trigger_vscode_server_download__
    Waiting for client to transfer server archive...
    Waiting for /home/myuser/.vscode-server/bin/f359dd69833dd8800b54d458f6d37ab7c78df520/vscode-scp-done.flag and vscode-server-linux-x64.tar.gz to exist
                                    Found flag and server on host
    LC_PAPER=hu_HU.UTF-8
    LC_ADDRESS=hu_HU.UTF-8
    XDG_SESSION_ID=5439
    LC_MONETARY=hu_HU.UTF-8
    HOSTNAME=speciallocalhostname.internal
    SHELL=/usr/sbin/wsh
    HISTSIZE=1000
    SSH_CLIENT=10.x.x.x 45706 22
    DOCKER_HOST=tcp://127.0.0.1:2376
    LC_NUMERIC=hu_HU.UTF-8
    USER=myuser
    LC_TELEPHONE=hu_HU.UTF-8
    MYSQL_HISTFILE=/dev/null
    LESSSECURE=1
    TMOUT=300
    DOCKER_TLS_VERIFY=1
    VSCODE_AGENT_FOLDER=/home/myuser/.vscode-server
    PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/myuser/.local/bin:/home/myuser/bin:/opt/nokia/myuser/bin
    MAIL=/var/spool/mail/myuser
    LC_IDENTIFICATION=hu_HU.UTF-8
    PWD=/home/myuser
    LANG=en_US.UTF-8
    LC_MEASUREMENT=hu_HU.UTF-8
    HISTCONTROL=ignoredups
    HOME=/home/myuser
    SHLVL=2
    LOGNAME=myuser
    SSH_CONNECTION=10.x.x.x 45706 192.168.0.12 22
    LESSOPEN=||/usr/bin/lesspipe.sh %s
    XDG_RUNTIME_DIR=/run/user/1001
    LC_NAME=hu_HU.UTF-8
    _=/usr/bin/printenv
    OLDPWD=/home/myuser/.vscode-server/bin/f359dd69833dd8800b54d458f6d37ab7c78df520
    Starting server...
    Waiting for server log...
    Waiting for server log...
    
    *
    * Reminder: You may only use this software with Visual Studio family products,
    * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
    *
    
    e113cb1e8cb8: start
    sshAuthSock====
    agentPort==45932==
    webViewServerPort====
    osReleaseId==centos==
    arch==x86_64==
    webUiAccessToken====
    e113cb1e8cb8: end
  
Is there some more diagnosis could I run?

> Maybe it shouldn't log that if --host is used? @alexdima

I guess that's a good idea.

**Comment by roblourens** [comment]
Could you share the full output of the Remote-SSH output channel so we can check whether the port has been forwarded to the local side?

**Comment by andrask** [comment]
Thank you, we are progressing!

> Could you share the full output of the Remote-SSH output channel so we can check whether the port has been forwarded to the local side?

Where can I get those? The above log is the only one I've found so far.

BTW. Enabling port forwarding solved the issue. So "AllowTCPForwarding yes" is mandatory for the plugin to work. This should be added to the documentation, I guess: https://code.visualstudio.com/docs/remote/linux

On the other hand it would be great if the plugin checked whether forwarding is possible and report to the user with a proper error message if failed. Port forwarding is disabled for security measures and would be great if it were not required for this plugin to work. Unfortunately, having ssh access doesn't imply that any other ports will be accessible on the target host.

**Comment by roblourens** [comment]
It is mentioned on this page: https://code.visualstudio.com/docs/remote/troubleshooting#_troubleshooting-hanging-or-failing-connections

I would like to show a better error message but I can't necessarily know the configuration of the ssh server, and can't know for sure whether it has that flag enabled or not. Unfortunately this is a common issue. I have this request to avoid it - https://github.com/microsoft/vscode-remote-release/issues/92 - but I'm not really sure what the alternative would be.

**Comment by roblourens** [comment]
For future reference, I'm referring to the log in the output pane here 


![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Comment by andrask** [comment]
Thanks a lot. So the basic question is how could one funnel HTTP connections over SSH without port forwarding. This should be doable with some clever trick. :+1:
