### ISSUE TITLE
Containers: gzip: stin: unexpected end of file

### ISSUE THREAD

**Issue by yngwi** [microsoft/vscode-remote-release#2016]
Container based workspaces don't start anymore since 1.41.0. The command that unzips the vscode server in the container fails with `gzip: stdin: unexpected end of file`. The fixes mentioned in https://github.com/microsoft/vscode-remote-release/issues/1856 don't work for me, neither did an install of the latest insider build. I'm submitting this issue because I have not seen it mentioned that the problem also occurs in windows-host based docker containers. 

_Manually rolling back to VSCode Version 1.40.2 and disabling auto updates fixes the problem._

- VSCode Version: 1.41.0
- Local OS Version: Windows 10
- Remote OS Version: Debian 9 (node:lts)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open remote folder

__Log:__

```
[6858 ms] Start: Run: docker exec -w /root/.vscode-server-insiders/bin/9579eda04fdb3a9bba2750f15193e5fafe16b959_1576184283038 -u root -i 65509213ce16cca843b0e4d35b91ee748a11860b40fec43473d86c8bc6c91da8 tar --no-same-owner -xz --strip-components 1
[7623 ms] 
[7623 ms] 
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

[7628 ms] Command failed: C:\Program Files\Docker\Docker\Resources\bin\docker.exe exec -w /root/.vscode-server-insiders/bin/9579eda04fdb3a9bba2750f15193e5fafe16b959_1576184283038 -u root -i 65509213ce16cca843b0e4d35b91ee748a11860b40fec43473d86c8bc6c91da8 tar --no-same-owner -xz --strip-components 1
```

**Comment by chrmarti** [comment]
As a workaround you can delete the faulty tar.gz from your temp folder's `vsch` folder. Could you first check what the size of the file is?

/cc @aeschli In case you have additional insights since we last spoke about the corrupt downloads.

**Comment by yngwi** [comment]
It now works in the insider build `1.42.0-insider` from today (2019-12-16).

**Comment by yngwi** [comment]
I'm sorry I've just now seen your reply, @chrmarti, do you mean the temp folder on windows?

**Comment by chrmarti** [comment]
@yngwi Were you by any chance short on disk space recently? (Trying to understand how that folder might have ended up like that.)

**Comment by yngwi** [comment]
Not that I know of

**Comment by zhangzitao** [comment]
I have the same problem. It seems like the process of downloading vscode's dev server file get wrong.
1. So I uninstall Vscode, delete ```~/.vscode``` & ```~/lib/application support/Code```
2. Reinstall vscode
3. Reboot my mac
Problem solved

**Comment by TheBegining** [comment]
> I have the same problem. It seems like the process of downloading vscode's dev server file get wrong.

Same situation,After rebuild faild at downloading vscode dev server.It happend

**Comment by adamkl** [comment]
For anyone else that runs into this issue on a Mac and doesn't want to clobber their VSCode install, here's what I did to find the location of the `vsch` folder:
`sudo find / -name "vscode-server*"` 
From there you can just delete the offending folder and try reconnecting to your container.

_Apparently, the folder found by running the command above should also be the same as what is stored in the TMPDIR environment variable. So you should be able accomplish the same as the `find` command by doing `echo $TMPDIR`. That should also point you to the correct place._

**Comment by roblourens** [comment]
Verified by code inspection, looks like the extension will retry to download one more time if the first download is corrupt.
