### ISSUE TITLE
Remote SSH [Windows]: Pushing to git never completes

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-remote-release#2018]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/35271042/70755152-e8654800-1ced-11ea-8fb0-536376c24a65.png)

It appears that pushing to Git via a Windows remote never completes and just endlessly spins.

Extension version: 2019.12.16800
VS Code version: Code - Insiders 1.41.0-insider (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-10T21:42:59.146Z)
OS version: Darwin x64 19.0.0
Remote OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: surface-win10|
|OS|Windows_NT x64 10.0.19041|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|15.93GB (2.47GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Do you see anything in the Git output channel?

**Comment by misolori** [comment]
Nothing interesting:

```log
Reading git index versions...
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git config --get commit.template
> git show :src/vs/base/browser/ui/menu/menu.css
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git pull --tags origin master
From https://github.com/microsoft/vscode
 * branch                    master     -> FETCH_HEAD
> git push origin master:master
> git show :src/vs/base/browser/ui/menu/menu.css
```

**Comment by roblourens** [comment]
If you run `git push` in the terminal, what happens?

**Comment by misolori** [comment]
Nothing happens after pushing from the terminal either, logs are the same

**Comment by roblourens** [comment]
So if you run `git push` in the terminal there is no output and it never completes? How about `git push -v`? Maybe you can show me next time we are in the same room

**Comment by WSLUser** [comment]
I'm not sure this is specific to Windows. I've sometimes had issue on a remote Linux too.

**Comment by misolori** [comment]
This may be a WSL issue, when I run `git push` in both the  VS Code terminal and a separate terminal they both hang.
