### ISSUE TITLE
If a location requires the NO_PROXY environment variable it cannot be accessed.

### ISSUE THREAD

**Issue by jakegt1** [microsoft/vscode-remote-release#202]
- VSCode Version: 1.34.0-insiders
- Local OS Version: Mac OSX High Sierra
- Remote OS Version: Centos 7
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to a machine where the no_proxy env variable is needed to avoid proxy issues.
2. Cannot download/access anything with no_proxy. (i was using the Java extension for ex. This works fine locally.)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: N/A - unsure how to do this without an extension

This is a bit thin on the ground but i'm not sure how else to explain this.

**Comment by chrmarti** [comment]
Maybe related: #213

**Comment by jakegt1** [comment]
It's possible, but i'm not sure - all i note is that right now http_proxy & https_proxy variables seem to be working fine, but no_proxy is not being adhered to on a remote connection. 

for reference, no_proxy is currently set in my bashrc (and appears when i echo $no_proxy in the remotely connected terminal), but does not seem to apply in extensions.

**Comment by roblourens** [comment]
Can you explain more about exactly what doesn't work? Can you download extensions? Certain extensions have the wrong behavior?

**Comment by jakegt1** [comment]
@roblourens I can download extensions but (from what i can tell), if an extension needs to download something that cannot be served via the proxy (aka, it's an exception via the NO_PROXY variable) the NO_PROXY variable is ignored and proceeds to attempt to download something through the proxy (and then failing.)
It's kind of hard to reproduce, but my situation is as follows:

* Using java extension with a gradle project where the gradle repository is inside intranet
* Have to use proxy for anything outside of the intranet
* Gradle fails due to attempting to download from the repository inside the intranet, with a 502 (happens when it tries to go through the proxy then to the intranet, which shouldn't be happening due to the NO_PROXY env var.)

**Comment by roblourens** [comment]
How do you set the env var? This could be an environment issue also, can you try again with the new nightly version of the ssh extension? It's a bit better there: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly

**Comment by jakegt1** [comment]
Set via export in my .bashrc. Not sure if that's the correct way to do it, but it *has* been picking up the http_proxy variable from somewhere, so i guess it must have been from there.

**Comment by jakegt1** [comment]
Also to note, it still happens with the nightly version.

**Comment by jakegt1** [comment]
Okay, i actually think this is to do with the downstream project. Have made an issue there, will close this one

Issue is here if anyone is interested: https://github.com/redhat-developer/vscode-java/issues/943
