### ISSUE TITLE
Folder history

### ISSUE THREAD

**Issue by yedane** [microsoft/vscode-remote-release#2021]
Issue Type: <b>Bug</b>

Hello, 

Since Remote SSH: Explorer has beend decaprecated, in my ssh targets list, I cannot see the history of my opened folder. 

Extension version: 0.47.2
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 3.10.0-327.el7.x86_64

**Comment by roblourens** [comment]
Please make sure you have the latest versions of all extensions. If you open new folders, on those remotes, do you get new history?

**Comment by yedane** [comment]
@roblourens 
Yes, I do have the latest version on all my extensions. 
There isn't history when I open new folder, it's the same on all my remotes.

**Comment by roblourens** [comment]
How are you opening the remote, and the folder?

**Comment by yedane** [comment]
I activated the "Use Local Server" setting, but I have the same problem without it. 

1. Choose my remote on the remote explorer - ssh targets.
2. Input password. 
3. Open folder
4. Input path of my project
5. And OK button

**Comment by roblourens** [comment]
Do you see the hosts in the explorer though? Can you maybe share a screenshot just to be sure I understand the situation?

Also does it work maybe with a Host that doesn't have `@` in it?

**Comment by yedane** [comment]
This is how my remote explorer look like: 

![image](https://user-images.githubusercontent.com/8882331/71079646-ee46a780-218b-11ea-8717-2276d9b0480c.png)

Their is no history on each remote. 
For example test is without @, and it works. 

I found that my recent remote folder are displayed on "Open recent"(Ctrl +r) and I can open them.

**Comment by roblourens** [comment]
> For example test is without @, and it works.

Are you saying that if you don't use `@` then you do get history for that item?

**Comment by yedane** [comment]
Yes, without @, I have folder history on remote explorer
