### ISSUE TITLE
After first run of code from WSL2 - file opening delay preserves.

### ISSUE THREAD

**Issue by sandric** [microsoft/vscode-remote-release#2022]
- VSCode Version: 1.40.2
- Local OS Version: Windows 10 Pro 2004
- Remote OS Version: WSL 2
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Open new wsl 2 terminal session
2. Run `code test_1.txt`
3. Wait ~ 5 seconds for server to start and open file
4. Run `code test_2.txt` in the same terminal session
5. Wait the same 5 seconds
6. Open `WSL` terminal session in vs code
7. Run `code test_2.txt` from wsl terminal session from within vs code terminal
8. See no delay at all.

My issue with opening files from remote wsl terminal via 'code' command and long lag coming from fact that the same bash session but in vs code terminal have no lag at all. Should there be some command then to not close vs code remote server connection? What command does vs code terminal session run that it has no lag when opening files? Or can I connect to this unlaggable session? Should I run `~/.vscode-server/bin/.../server.sh` somehow in my terminal session to get rid of lag? Thanks.

**Comment by aeschli** [comment]
Running `code` from the integrated terminal and from a WSL shell are actually very different.
From the integrated terminal we have a `code` on the path that directly talks to the running VSCode server.
From the WSL shell we invoke VSCode in the Windows side.

Can you run `code --verbose` in the WSL shell to get more information where the delay comes from?

**Comment by sandric** [comment]
I already kind of figured out how it works - it creates socket, code executable under `.vscode-server` and set up `VSCODE_IPC_HOOK_CLI` env variable.
To be able to jump to file as quickly as in vs code terminal I had to place this in my `~/bin` folder, and call as with `vscode-run <filename>` (in case it will be helpful to anyone like me):

```bash
#!/bin/sh

VSCODE_IPC_HOOK_CLI=$(ls -t /tmp/vscode-ipc-*.sock | head -1) $(ls -t /home/sandric/.vscode-server/bin/*/bin/code | head -1) $@
```

**Comment by aeschli** [comment]
That's a cool trick. 
I would still be interested to understand why the regular way takes so long. Can you run with verbose?

**Comment by sandric** [comment]
Sure, will run it later today

**Comment by sandric** [comment]
Here's my verbose output, not sure how it will help, but as you can see, it triggers main Code.exe instead of `.vscode-server/bin` binary for session:

```
~ ^ code --verbose .tmux.conf
Invoking: /mnt/c/Users/sandr/AppData/Local/Programs/Microsoft VS Code/Code.exe resources/app/out/cli.js --verbose --file-uri=vscode-remote://wsl+Ubuntu/home/sandric/.tmux.conf --remote=wsl+Ubuntu in /mnt/c/Users/sandr/AppData/Local/Programs/Microsoft VS Code
```

**Comment by aeschli** [comment]
Even more debug info will be visible with `VSCODE_WSL_DEBUG_INFO=true code .`
