### ISSUE TITLE
Unable to query the TypeScript extension from our extension

### ISSUE THREAD

**Issue by henryju** [microsoft/vscode-remote-release#2023]
Hi,

VSCode 1.40.2
Remote Development 0.19.0

We have detected that our extension (SonarLint) is not working when using remote-ssh. In our extension `activate` method, [we are querying the `vscode.typescript` extension](https://github.com/SonarSource/sonarlint-vscode/blob/818d7a09dbd91bc35f5bd79d0616c8c3710be97d/src/extension.ts#L143), but it returns `undefined`. I'm suspecting maybe one extension is running on UI side, while the other is on server side, but looking at the `Running Extensions` panel, this is not clear to me:
![image](https://user-images.githubusercontent.com/281596/70807162-385f1000-1dbd-11ea-8d94-9f80f1c0a772.png)

To me it would make sense that the two extensions are running remotely, and that our extension can access to the TypeScript extension.

Any help is welcome!

**Comment by sandy081** [comment]
Looks like both are running remotely. Do you have an extension dependency on typescript extension - https://code.visualstudio.com/api/references/extension-manifest

**Comment by henryju** [comment]
> Do you have an extension dependency on typescript extension
No because we don't want to enforce users to have the TypeScript extension. We want to query when the extension is present, and adapt accordingly.

**Comment by sandy081** [comment]
If you are accessing another extension during runtime you have to add the dependency otherwise it may not get activated and not available to you.

**Comment by henryju** [comment]
> otherwise it may not get activated and not available to you

This doesn't look right. `VSCode.extensions.getExtension` returns an [Extension](https://code.visualstudio.com/api/references/vscode-api#Extension) object, having an `isActivate` attribute. What the point if you can only query activated extensions?

**Comment by henryju** [comment]
Also note that this is working fine when not using the ssh mode: I can query the TypeScript extension even without declaring a dependency on it, and even if it is not yet activated.

**Comment by sandy081** [comment]
Sorry, you are right. You do not need dependency to access an extension.

@alexdima Passing over to you.

**Comment by egamma** [comment]
@henryju there are two typescript extensions, one does syntax coloring and is run on the UI side and the other does the language features. I assume you want to access the language features.

Looking at your code you are querying for the syntax coloring extension:

```typescript
const tsExt = VSCode.extensions.getExtension('vscode.typescript');`
```
This extension runs on the UI side and is not accessible to you. To access the language features extension you should use:
```typescript
const tsExt = VSCode.extensions.getExtension('vscode.typescript-language-features');`
```

**Comment by henryju** [comment]
Make sense, thanks!
