### ISSUE TITLE
Cannot open folder in WSL in VSCode 1.41

### ISSUE THREAD

**Issue by stellirin** [microsoft/vscode-remote-release#2030]
Issue Type: <b>Bug</b>

Since I upgraded to VSCode 1.41 the 'Reopen Folder in WSL' option does nothing. I can choose it but there is no reaction from VSCode and the folder stays open. Console shows the following error:

```
  ERR authority must start with wsl+: Error: authority must start with wsl+
	at Object.t.getDistroFromAuthority (c:\Users\stellirin\.vscode\extensions\ms-vscode-remote.remote-wsl-0.41.5\dist\extension.js:1:18582)
	at c:\Users\stellirin\.vscode\extensions\ms-vscode-remote.remote-wsl-0.41.5\dist\extension.js:1:56646
```

Extension version: 0.41.5
VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (18.89GB free)|
|Process Argv|C:\my\dev\folder|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode-remote-release/issues/2038
