### ISSUE TITLE
remote ssh says "Got connection X"

### ISSUE THREAD

**Issue by hmassalha** [microsoft/vscode-remote-release#2034]
- VSCode Version: January 2020 (version 1.42)
- Local OS Version: Mojave 10.14.4
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
Hi, I am using Remote-SSH 0.48.0 to connect to the server of my workplace via secured VPN. I used to work like this for months.
I can't tell why, but from yesterday I have a running terminal only after the first connection to the server, which will very fast get to mode 'not responding'. And from that point, I can't start a new terminal. In the output window I got the following:
<img width="449" alt="Screen Shot 2019-12-16 at 6 09 37" src="https://user-images.githubusercontent.com/10478803/70878583-c22ff880-1fca-11ea-9f6d-5851360faa2c.png">

Any suggestions? 
Thanks, HM

**Comment by roblourens** [comment]
Can you explain some more? The terminal is not working? I don't quite understand this -

> from yesterday I have a running terminal only after the first connection to the server, which will very fast get to mode 'not responding'

 Can you share the full log?
