### ISSUE TITLE
win7 can not define ssh port 

### ISSUE THREAD

**Issue by jackeyang** [microsoft/vscode-remote-release#2036]
Issue Type: <b>Bug</b>

win7
vscode 
cannot  custom ssh port 

Extension version: 0.47.2
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:38.728Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (6.50GB free)|
|Process Argv|E:\workspace_wx\mmsearch\mmsearchitilnodelogicsvr|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
If you are using a custom ssh port you will need to set up an ssh config. if you can connect with `ssh host` from an external terminal then it should work in vscode too. See the docs for tips on creating an ssh config. Please give more details if that doesn't help.
