### ISSUE TITLE
Change color for remote session task bar

### ISSUE THREAD

**Issue by krazyito65** [microsoft/vscode-remote-release#204]
In previous versions of the insider, the color of the remote ssh/container extension was green, now it is a blue color and it blends in with the rest of the bottom task bar.  I would like the option to be able to change it becasue I liked to see at a glance that I am on a remote session and not on my local.

Maybe even the option for different colors based on if you're on SSH/Container/WSL/Off ?  Or be able to set up a regular expression to assign specific colors to different text on the extension.

**Comment by egamma** [comment]
pls see https://stackoverflow.com/questions/55958171/how-can-i-change-the-color-of-the-remote-icon-in-the-vs-code-status-bar
