### ISSUE TITLE
Can not edit files with code when connected to WSL: Debian

### ISSUE THREAD

**Issue by JustAMicrobe** [microsoft/vscode-remote-release#2040]
Issue Type: <b>Bug</b>

I just installed the Debian WSL and installed apache2. Did not change anything so far. Now i wanted to edit the apache config by openening VS Code from the WSL App by typing "code ." inside of the root folder and navigating up to the conf.

The error i get is always the same: 
Failed to save 'apache2.conf': Unable to write file (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/etc/apache2/apache2.conf')

i also get the error when trying to open the file like:
"code /etc/apache2/apache2.conf"

Extension version: 0.41.6
VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.68GB (5.35GB free)|
|Process Argv|--file-uri=vscode-remote://wsl+Debian/etc/apache2/apache2.conf --remote=wsl+Debian|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|Memory (System)|11.68GB (5.35GB free)|
|VM|0%|
</details>

**Comment by JustAMicrobe** [comment]
I am able to edit the apache2 configs now by following the comment of [rgherta](https://github.com/microsoft/vscode-remote-release/issues/1008). But i can only change contents inside of the apache2 folder now (command: sudo chown -R myUser /etc/apache2/). 

I would love to edit all the files everywhere with vs code because i am not experienced in using VIM. Is there a workaround to be able to change any file inside the debian subsystem from VSCode?

**Comment by WSLUser** [comment]
If you want to edit everything, then you need to be `root`. You should only be editing files either on a Windows mount `/mnt/c/workspace` or under your user directory: `/home/username/workspace`.

**Comment by aeschli** [comment]
The Remote -WSL extension runs as a Linux process with the default WSL user. That's usually the user that was created when the distro was initialized. But WSL also allows you to change the default user of a distro, see https://docs.microsoft.com/en-us/windows/wsl/user-support.
