### ISSUE TITLE
Fall back to http long polling when using remote feature.

### ISSUE THREAD

**Issue by trigun539** [microsoft/vscode-remote-release#2042]
Some browsers do not support WebSockets and thus, the remote capability of VS Code breaks. Would be great if this was implemented. Thanks

**Comment by roblourens** [comment]
Which browser are you using? We likely won't support any browser that doesn't support WebSockets.

**Comment by trigun539** [comment]
Older versions of IE

**Comment by roblourens** [comment]
Those won't be supported, sorry.
