### ISSUE TITLE
Workaround for reload Window

### ISSUE THREAD

**Issue by lucsoft** [microsoft/vscode-remote-release#2045]
Can a SSH Connection not just reconnect? 
why doest it needs to reload the window?

can this be changed?

**Comment by roblourens** [comment]
Please give more details about exactly what is going on

**Comment by lucsoft** [comment]
when connection is lost like entered password wrong or timeout 

it wannts always to reload the window

can it not just reconnect without reloading everything

**Comment by roblourens** [comment]
If you entered the password wrong, then it sounds like it failed to connect in the first place. If it connects then loses internet connection, it will reconnect. But if the initial connection fails, then it will reconnect without reloading the window.

**Comment by lucsoft** [comment]
nope thats wrong it trys once and then its want to reload the page

**Comment by lucsoft** [comment]
![image](https://user-images.githubusercontent.com/11093382/71116735-f6770500-21d4-11ea-878e-f4ac9f3ef1a4.png)
(shutdown is only for the screenshot, this is still the same when i lost the connection it always says reload )

i just wannt a button to reconnect or do it automatically 

please

**Comment by roblourens** [comment]
Can you share the log from the Remote-SSH output channel?

**Comment by lucsoft** [comment]
well ist often just a timeout no error
[21:11:52.647] > root@X.X.X.X's password: 
[21:11:52.648] Got some output, clearing connection timeout
[21:11:52.648] Showing password prompt
[21:12:53.142] Got password response
[21:12:53.143] "install" wrote data to terminal: ""
[21:12:53.152] > 
[21:13:48.631] > Connection reset by X.X.X.X port 22
[21:13:48.881] "install" terminal command done
[21:13:48.881] Install terminal quit with output: Connection reset byX.X.X.X port 22
[21:13:48.881] Received install output: Connection reset by X.X.X.X port 22
[21:13:48.882] Stopped parsing output early. Remaining text: Connection reset by X.X.X.X port 22
[21:13:48.882] Failed to parse remote port from server output
[21:13:48.883] Resolver error: 
[21:13:48.885] ------


i get a message where its says reconnect in 30 secs but then wen it found it agan it shows the message that it wants to reload. the thing is can it not just reconnect without reloading everything (window)

**Comment by roblourens** [comment]
Please share the full log, I'm still trying to understand the full scenario and actual problem. Like does it only go through reconnection once before giving up and showing the Reload Window dialog?

**Comment by lucsoft** [comment]
It trys to reconnect (no problem there) but when the server is back online and it wannst to reload the window (or cancel the session) but not just reconnect without reload

I cant get the log anymore directy from the remote ssh module because every modules gets unloade or something like that

https://pastebin.com/w4CjaWVr

![image](https://user-images.githubusercontent.com/11093382/71217242-652f8d80-22bd-11ea-9723-8749eba7bcdd.png)

**Comment by roblourens** [comment]
Oh, there is another issue where we hide the log after this happens, that needs to be fixed too. To work around it, please do this to get the log:

- Run "Open Logs Folder"
- Find an 'exthost#' folder that has a Remote-SSH.log file under it which looks like it corresponds to the bad run

![image](https://user-images.githubusercontent.com/323878/71219745-03e6ca80-227b-11ea-9f57-8c7b339bfb56.png)

Share that log

**Comment by lucsoft** [comment]
here is the log https://pastebin.com/jkN5J28V

**Comment by roblourens** [comment]
It connects initially, then is disconnected by the host:

> Connection to 192.168.8.102 closed by remote host.

Then fails to reconnect

> ssh: connect to host 192.168.8.102 port 22: No route to host

It seems like your server is kicking vscode off. Sorry, I don't know why it would do that.

Are you able to use ssh through a terminal for long sessions?

**Comment by lucsoft** [comment]
after the connection works it wants to reload
i know that i closed the session by rebooting the system
just to show you it

after the server is up it finds it but then it needs a reload. Why?

do you know what im asking you?

**Comment by roblourens** [comment]
Yeah, if you rebooted the server then you will need to reload the window. That's just the way it works by design.
