### ISSUE TITLE
Add default download path configuration

### ISSUE THREAD

**Issue by idanpa** [microsoft/vscode-remote-release#2047]
Would be nice to configure the default download path on the local machine.

(I want to add a keyboard shortcut to download files without the need to fill the path)

**Comment by aeschli** [comment]
Can you give more context? Screenshot and steps would clarify things. Unclear to me what download you are referring to..

**Comment by idanpa** [comment]
Sorry for being unclear.
Steps to reproduce:
Right click on a file in the explorer -> Download
Opens a dialog on top with:

`/home/idanp/file_name.py`

I would like to change the default directory it use (so I could just hit enter instead of changing the path each time)

Thanks!

**Comment by isidorn** [comment]
Let's close as dup of https://github.com/microsoft/vscode-remote-release/issues/2536
