### ISSUE TITLE
Could not ebtaslish connection to "host". The VS code server failed to start

### ISSUE THREAD

**Issue by qsphan** [microsoft/vscode-remote-release#2049]
I have used remote developmont for several months, and it had worked quite well. Suddenly, from last Friday, I couldn't connect. **I'm still able to ssh to my remote machine**. There were similar issues, but I couldn't find an answer for my case:
- https://github.com/microsoft/vscode-remote-release/issues/80
- https://github.com/microsoft/vscode-remote-release/issues/1344

The configuration is:
- VSCode Version: 1.42.0-insider
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 16.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open VScode
2. It automatically tried to connect, and showed the error in the title.

Full server log:
```
[10:01:21.101] > Server did not start successfully. Full server log >>>
> The factory method of "vs/platform/product/common/product" has thrown an exception
> SyntaxError: /u/qsphan/.vscode-server-insiders/bin/241d4048aabc31db0baed66bb3d58cf3210d981d/product.json: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at Object.Module._extensions..json (internal/modules/cjs/loader.js:799:27)
>     at Module.load (internal/modules/cjs/loader.js:641:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at Function.s [as __$__nodeRequire] (/u/qsphan/.vscode-server-insiders/bin/241d4048aabc31db0baed66bb3d58cf3210d981d/out/vs/loader.js:32:963)
>     at Object.<anonymous> (/u/qsphan/.vscode-server-insiders/bin/241d4048aabc31db0baed66bb3d58cf3210d981d/out/vs/server/remoteExtensionHostAgent.js:295:490)
>     at Function.t._safeInvokeFunction (/u/qsphan/.vscode-server-insiders/bin/241d4048aabc31db0baed66bb3d58cf3210d981d/out/vs/loader.js:20:548)
>     at Function.t._invokeFactory (/u/qsphan/.vscode-server-insiders/bin/241d4048aabc31db0baed66bb3d58cf3210d981d/out/vs/loader.js:20:795)
>     at t.complete (/u/qsphan/.vscode-server-insiders/bin/241d4048aabc31db0baed66bb3d58cf3210d981d/out/vs/loader.js:21:10)
>     at s._onModuleComplete (/u/qsphan/.vscode-server-insiders/bin/241d4048aabc31db0baed66bb3d58cf3210d981d/out/vs/loader.js:31:490)
>     at s._resolve (/u/qsphan/.vscode-server-insiders/bin/241d4048aabc31db0baed66bb3d58cf3210d981d/out/vs/loader.js:31:41)
>     at s.defineModule (/u/qsphan/.vscode-server-insiders/bin/241d4048aabc31db0baed66bb3d58cf3210d981d/out/vs/loader.js:25:184)
>     at r (/u/qsphan/.vscode-server-insiders/bin/241d4048aabc31db0baed66bb3d58cf3210d981d/out/vs/loader.js:32:180)
>     at c (/u/qsphan/.vscode-server-insiders/bin/241d4048aabc31db0baed66bb3d58cf3210d981d/out/vs/loader.js:16:958)
>     at Object.<anonymous> (/u/qsphan/.vscode-server-insiders/bin/241d4048aabc31db0baed66bb3d58cf3210d981d/out/vs/server/remoteExtensionHostAgent.js:276:763)
>     at Object.<anonymous> (/u/qsphan/.vscode-server-insiders/bin/241d4048aabc31db0baed66bb3d58cf3210d981d/out/vs/server/remoteExtensionHostAgent.js:478:442)
>     at t._createAndEvalScript (/u/qsphan/.vscode-server-insiders/bin/241d4048aabc31db0baed66bb3d58cf3210d981d/out/vs/loader.js:17:3)
>     at /u/qsphan/.vscode-server-insiders/bin/241d4048aabc31db0baed66bb3d58cf3210d981d/out/vs/loader.js:16:639
>     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3) {
>   phase: 'factory',
>   moduleId: 'vs/platform/product/common/product'
> }
> <<< End of server log
> b89dbbe9fe2d##32##
> 
[10:01:21.434] "install" terminal command done
[10:01:21.434] Install terminal quit with output: b89dbbe9fe2d##32##
[10:01:21.434] Received install output: b89dbbe9fe2d##32##
[10:01:21.435] Resolver error: The VS Code Server failed to start
[10:01:21.438] ------
```

**Comment by qsphan** [comment]
![VScode](https://user-images.githubusercontent.com/7419516/71024546-03530600-20ba-11ea-9606-1321f55308f7.png)

**Comment by roblourens** [comment]
Hm, could you show the contents of `/u/qsphan/.vscode-server-insiders/bin/241d4048aabc31db0baed66bb3d58cf3210d981d/product.json`?

**Comment by qsphan** [comment]
@roblourens This file is empty, and I'm sure I've never touched it.

**Comment by almuth** [comment]
same problem happen after install latest update today, before update it work well.

Version: 1.41.0 (user setup)
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:37:42.077Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

[14:52:38.213] > Server did not start successfully. Full server log >>>
> 
[14:52:38.235] > <<< End of server log
> a710649b7742##32##   
> 
[14:52:38.567] "install" terminal command done
[14:52:38.567] Install terminal quit with output: a710649b7742##32##   
[14:52:38.567] Received install output: a710649b7742##32##   
[14:52:38.569] Resolver error: The VS Code Server failed to start
[14:52:38.571] ------

**Comment by roblourens** [comment]
@almuth possibly a different issue, please open a new issue.

@qsphan does it work with the new Insiders update today? Or can you try running "Kill VS Code Server on Host..." and reconnecting?

**Comment by qsphan** [comment]
@roblourens could you elaborate on how to "Kill VS Code Server on Host..."? I would like to try this before installing latest update.

**Comment by roblourens** [comment]
You can run that command from the command palette (ctrl+shift+P or cmd+shift+P)

**Comment by qsphan** [comment]
Thanks @roblourens . It works, I'm closing this issue.
