### ISSUE TITLE
Install Remote Plugin From VSIX?

### ISSUE THREAD

**Issue by cliffburdick** [microsoft/vscode-remote-release#205]
After having this issue:

https://github.com/microsoft/vscode-remote-release/issues/89

Which the cpp people seem to think can be solved by installing from the VSIX, it would be nice to have a way to install a VSIX manually on the remote server using remote-ssh.

Client: Windows 10
Server: Ubuntu 18.04

**Comment by egamma** [comment]
@cliffburdick this is supported, get the VSIX on the remote box and follow these steps https://code.visualstudio.com/api/advanced-topics/remote-extensions#installing-a-development-version-of-your-extension.

**Comment by cliffburdick** [comment]
@egamma got it -- for anyone wondering how to get the C++ extension working, you must do the following:

1) Use the insiders edition extension
2) Disable extension auto-update
3) Install from VSIX

**Comment by egamma** [comment]
@Chuxel not sure how to best spread this workaround.

**Comment by Chuxel** [comment]
@egamma I can add this into the extension tips and tricks section.

**Comment by egamma** [comment]
:+1: thanks
