### ISSUE TITLE
Reconnecting to SSH impossible

### ISSUE THREAD

**Issue by stuartthomas25** [microsoft/vscode-remote-release#2050]
Issue Type: <b>Bug</b>

When SSH becomes disconnected it is truly a pain in the ass to reconnect. This happens to me a lot and really drives me crazy

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 19.0.0
Fetching remote diagnostics for 'SSH' failed: Connecting with SSH timed out

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|19, 23, 13|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: Connecting with SSH timed out
</details>Extensions: none

**Comment by stuartthomas25** [comment]
I SSH over a VPN to access remote files. When I close my computer and the VPN resets, I lose access to the remote files, which is fine, but "Reconnecting to SSH" does not work. Since these files are not saved locally, I can't even close the window and open a new one without losing any new work. I have to copy all the files to another document, close the window, and open it again. I love VSCode except for this problem.

**Comment by roblourens** [comment]
Ok first let's look at 

> "Reconnecting to SSH" does not work

Can you share the log from the Remote-SSH output channel which should tell us why it wasn't able to reconnect?

> I can't even close the window and open a new one without losing any new work

I don't quite understand the problem. If you open the same folder on the remote, even by reloading the window, you should see the same files.

**Comment by stuartthomas25** [comment]
There is nothing in the Remote-SSH log since it's not connected (I'm assuming). Here's a gif of the problem: 
![ezgif-6-f745ef262891](https://user-images.githubusercontent.com/5956054/71773823-34dd2580-2f32-11ea-9cfc-587eaadb1055.gif)

**Comment by roblourens** [comment]
That's interesting, I filed another issue for that problem. That command should work when you are disconnected. https://github.com/microsoft/vscode/issues/88111

A workaround might be to run the command "Reload Window", which should reconnect to the same remote and the same folder, does that work for you?

**Comment by stuartthomas25** [comment]
Ah, beautiful. Works for me, thank you.
