### ISSUE TITLE
VSC Remote-WSL errors when attempting to run

### ISSUE THREAD

**Issue by nrmendoza** [microsoft/vscode-remote-release#2052]
![error_VSC_windows](https://user-images.githubusercontent.com/58484626/71043905-4d091400-20ed-11ea-8f88-3dd60fea9c35.PNG)
![error_WSL_terminal](https://user-images.githubusercontent.com/58484626/71043906-4d091400-20ed-11ea-8672-1d5900c51361.PNG)

the error_WSL_terminal I get when I execute 'code .'. I followed every step closely, yet neither method on the website works for me. Please help!

**Comment by aeschli** [comment]
Can you paste the full content of the WSLTerminal here? 
Are you behind a proxy?
