### ISSUE TITLE
Remote attach using non-root account would fail directly

### ISSUE THREAD

**Issue by xnervwang** [microsoft/vscode-remote-release#2053]
- VSCode Version: 1.42.0-insider
- Local OS Version: Windows 10 Enterprise 19041.1
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH (using password, no SSH key)

Steps to Reproduce:

1. When I attach to a process ID in remote Ubuntu (I'm using an user account which has sudo permisson), the VSCode terminal asks:
> Superuser access is required to attach to a process. Attaching as superuser can potentially harm your computer. Do you want to continue? [y/N]

Then I input `y` and enter. It shows error message directly:
```
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ===
Authentication is needed to run `/usr/bin/gdb' as the super user
Authenticating as: narwhal,,, (narwhal)
Password: [1] + Stopped (tty output)       /usr/bin/pkexec "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-jq3xeuls.opj" 1>"/tmp/Microsoft-MIEngine-Out-cqs0ub2g.t9b"
You have stopped jobs.
```

2. If I use Ubuntu local VSCode to attach to the process ID, after I input `y` and enter, a new Window would popup and ask me to input password. Then everything is OK.

3. Then I tried to use Windows VSCode to connect this SSH by root user, Windows VSCode doesn't ask for password and it can attach to the process ID directly.

So in summary, remote attach with a non-root account would fail directly, I expected it should ask for my password.

The section in launch.json:
```
{
            "name": "(gdb) Attach vml_dummy_client",
            "type": "cppdbg",
            "request": "attach",
            "program": "${workspaceFolder}/out/storage/vml/vml_dummy_client",
            "processId": "${command:pickProcess}",
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
},
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by xnervwang** [comment]
OK let me answer my question by myself though I don't know if this is the best solution. Sine it seems this is caused by pkexec when it need to ask for password, so I tried to get a solution to avoid pkexec to ask for password. So I added a new file /usr/share/polkit-1/actions/com.ubuntu.pkexec.gdb.policy:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">
<policyconfig>

  <action id="com.ubuntu.pkexec.gdb-settings">
    <icon_name>gdb-settings</icon_name>
    <defaults>
      <allow_any>yes</allow_any>
      <allow_inactive>yes</allow_inactive>
      <allow_active>yes</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">/usr/bin/gdb</annotate>
    <annotate key="org.freedesktop.policykit.exec.allow_gui">true</annotate>
  </action>

</policyconfig>
```

Now my Windows VSCode won't ask for superuser password so I can avoid this issue.

**Comment by roblourens** [comment]
I'm glad you found a solution. Besides that, you would need to set up x forwarding or another way for ubuntu to ask for your password, and you would have to set that up yourself, I don't think vscode can help here.
