### ISSUE TITLE
Please consider enabling busybox as possible SSH targets (no hard bash requirement)

### ISSUE THREAD

**Issue by vbondzio** [microsoft/vscode-remote-release#2054]
Issue Type: <b>Feature Request</b>

It would be nice to use Remote-SSH to targets without bash that use busybox, like routers or other "embedded" devices. 

If I alias bash to busybox sh (kind of hard at the moment due to /etc/profile not being editable easily) would there be any other roadblock later? 

Thanks in advance!

Extension version: 0.48.0
VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

**Comment by roblourens** [comment]
> would there be any other roadblock later?

Maybe. Your remote also needs to meet these requirements: 
 https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites

and the install script needs `flock` which may or may not be an issue. I think I have avoided bash-only syntax but can't guarantee it.

**Comment by vbondzio** [comment]
While strings and ldd aren't installed, the libraries are on the required level. flock isn't their either thought :-(. I couldn't find the install script in the vcode repository, could you maybe link me to it? Thanks again and Happy Holidays!

**Comment by roblourens** [comment]
The code for this isn't OSS unfortunately. Missing flock will be a blocker for now. I also have this feature request for busybox: https://github.com/microsoft/vscode-remote-release/issues/1747
