### ISSUE TITLE
context: ../ option does not change docker context to parent directory

### ISSUE THREAD

**Issue by codeliger** [microsoft/vscode-remote-release#2055]
- VSCode Version: 1.41.0
- Local OS Version:  Ubuntu 18.04.2 LTS
- Remote OS Version: https://github.com/microsoft/vscode-remote-try-node
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1.  Add the `context` property to the .devcontainer/devcontainer.json with the value of `../`
2. Save the File
3. Ctrl + Shift + P
4. Reopen Folder in Container
5. See ../ appended to the end of the current docker context instead of replacing it.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Did not try because should not be relevant.

**Comment by chrmarti** [comment]
Could you post the log terminal's output here? (`F1` > `Remote-Containers: Show Log`)
