### ISSUE TITLE
debug breakpoint opens absolute path

### ISSUE THREAD

**Issue by payonel** [microsoft/vscode-remote-release#2057]
setting a breakpoint in `main.cpp` opens a 2nd tab at `/home/payonel/code/sandbox/main.cpp`
I've tested this with the same exact sandbox test locally and remotely, and only the remote debug experience opens the full path in an otherwise duplicate tab (not using the one from clicking main.cpp in vscode folder browser)
```
{
  "version": "0.2.0",
  "configurations": [
      {
          "name": "gdb"
          ,"type": "cppdbg"
          ,"request": "launch"
          ,"MIMode": "gdb"
          ,"program": "${workspaceRoot}/a.out"
          ,"cwd": "${workspaceRoot}"
          ,"externalConsole": false
      }
  ]
}
```

**Comment by payonel** [comment]
also note that the debug build uses relative paths, for consideration, the output of `-exec where`
```
#0  main () at main.cpp:42
```

**Comment by roblourens** [comment]
Please file this on the repo for the debug extension you're using

**Comment by payonel** [comment]
I'm using `ms-vscode.cpptools` with the system `gdb` on linux
but this doesn't happen when debugging locally, it only happens when using `vscode-remote`
