### ISSUE TITLE
Python Modules not in PATH (WSL)

### ISSUE THREAD

**Issue by HolgerDoerner** [microsoft/vscode-remote-release#206]
- VSCode Version: 1.34.0-insider (user setup)
- Local OS Version: Windows 10 Version 1809 (OSBuild 17763.457)
- Remote OS Version: Ubuntu 1804
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Connect to local WSL-Instance
2. Install Module with PIP `pip install --user molecule`
3. Try to call the Module `$ molecule`
4. Get output `molecule: command not found`

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

I am working inside of WSL with Python and I recognized that Modules installed with PIP are not visible on the PATH inside of VSCode-Terminal. They can only be called with `python -m mymodule`, consequently I also get errors when modules are called from other modules and the execution fails.

Inside of a normal Terminal-Window everything works as expected.

Currently I am working with Ansible and Molecule for Unit-Tests, but I have to do all commandline work in an separate Terminal.

Any thoughts on this?

**Comment by egamma** [comment]
@qubitron?

**Comment by HolgerDoerner** [comment]
As a work-around I put `$HOME/.local/bin` manually to the `$PATH`.

It seems like VSCode doesn't load `$HOME/.profile` which would prepend the user BIN-directories to `$PATH` !?

**Comment by egamma** [comment]
@aeschli?

**Comment by ocboogie** [comment]
I'm having the same issue, with pip and rustup. It definitely seems like VSCode isn't loading `.profile`.

**Comment by aeschli** [comment]
With the latest remote-wsl update (0.35) this should be fixed:
- The VSCode server is started in an interactive login shell. Which shell is used depends on the what shell is configured. See [here](https://medium.com/@vinhp/set-and-use-zsh-as-default-shell-in-wsl-on-windows-10-the-right-way-4f30ed9592dc) for more information on how to specify a shell.
  - By default, `bash` is used as shell. Bash will look up startup files at `/etc/profile` first and then find any startup file that comes first among `~/.bash_profile`, `~/.bash_login`, `~/.profile`. If none of this process seems unnecessary, you may include all startup settings in `~/.bashrc`.

**Comment by aeschli** [comment]
Marking as fixed, please reopen if that's not true for you

**Comment by ocboogie** [comment]
Yeah everything works for me! :tada:

**Comment by HolgerDoerner** [comment]
Yes, I also can confirm that everything is working fine now!
Thank You very much, good job! 😸
