### ISSUE TITLE
WSL2 connectivity issues with build 19536

### ISSUE THREAD

**Issue by meatherly** [microsoft/vscode-remote-release#2060]
Issue Type: <b>Bug</b>

The error pop up shows:
Unable to open 'my-app': Unable to read file (Error: connect ECONNREFUSED ::1:43283).

I also don't have any of my installed extensions. Please let me know if there is anything I can do to help you guys debug the issue. 

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.19536
Fetching remote diagnostics for 'WSL: Ubuntu' failed: connect ECONNREFUSED ::1:43283

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (7.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu' failed: connect ECONNREFUSED ::1:43283
</details>Extensions: none

**Comment by meatherly** [comment]
Today I tried restoring my windows instance by using the restore tool and after it was done restoring it removed Windows insiders preview 15536.1000 and the issue went away. I'll try reinstalling that version to see if the problem comes back.

**Comment by meatherly** [comment]
After installing the update it seems like the problem is back. I can launch code and it connects to the folder but when I run `nc -lk 0.0.0.0 3000 | bash` and try to access it from the windows side with chrome `localhost:3000` I can't.

**Comment by aaronpowell** [comment]
I think there may be a problem with the `19536.1000` build of Windows as I'm hitting problems with wsl2 networking which is seen as things like the extension can't find the remote instances and when running something from wsl2 the port(s) aren't exposed.

**Comment by aaronpowell** [comment]
_cross referencing a potentially relevant WSL issue https://github.com/microsoft/WSL/issues/4769_

**Comment by brennaman** [comment]
I restored Windows to the version prior to 19536.1000 and my WSL issue went away as well.

**Comment by slooker** [comment]
> I restored Windows to the version prior to 19536.1000 and my WSL issue went away as well.

How did you restore?  I'm running into the same issue right now and can't seem to figure out how to go back to the old build.

**Comment by brennaman** [comment]
@slooker to restore to previous version go to Windows Settings -> Update & Security -> Recovery.  From there you should see a section "Go back to the previous version of Windows 10".

**Comment by aeschli** [comment]
dup of #2060

It's a WSL2 issue.
I just released a new version of the extension - Remote - WSL 0.42.1 - that should work around the issue. It requires VSCode Insiders (1.42.0). It would be great if you can give it a try. If it works I can also make a version for the stable VSCode (1.41.1).

**Comment by aaronpowell** [comment]
@aeschli looks like the latest update resolves the problem (running Win10 19536 and VS Code Insiders 1.42.0).

**Comment by bplasmeijer** [comment]
No issue anymore with (Remote - WSL 0.42.1) @aeschli ; I did test the sleep and hibernate mode.

Thanks a lot.
Bart

**Comment by oorestisime** [comment]
Same here, issue fixed with the new version.

**Comment by gualterandre** [comment]
I can confirm as well. Fixed with VC Code Insiders. Waiting on VSCode stable release.

**Comment by Nathan-Furnal** [comment]
Hi, will we see a quick patch for VS Code proper or do we have to wait until the update? 

Thanks for the good work

**Comment by aeschli** [comment]
I just published Remote - WSL 0.41.7 that works with VSCode Stable (1.41).

**Comment by Nathan-Furnal** [comment]
Thanks a ton ! I’ll install it asap

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Martin Aeschlimann <notifications@github.com>
Envoyé : Tuesday, January 7, 2020 5:04:35 PM
À : microsoft/vscode-remote-release <vscode-remote-release@noreply.github.com>
Cc : Nathan Furnal <nathan_furnal@hotmail.com>; Comment <comment@noreply.github.com>
Objet : Re: [microsoft/vscode-remote-release] WSL2 connectivity issues with build 19536 (#2060)


I just published Remote - WSL 0.41.7 that works with VSCode Stable (1.41).
