### ISSUE TITLE
[devctr] user choice of terminal shell is ignored in 1.42

### ISSUE THREAD

**Issue by fsackur** [microsoft/vscode-remote-release#2061]
A recent update (this stopped working for me on Friday 13 Dec) has broken my choice of `zsh` as my shell - now, opening an new terminal tab gives me `bash`. `zsh` is working and I can enter it manually.

Version: 1.42.0-insider (user setup)
Commit: e74405d11443c5361c31e2bc341866d146eee206
Date: 2019-12-19T05:31:04.916Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Install zsh into dev container image
2. Set `"settings": {"terminal.integrated.shell.linux": "/usr/bin/zsh"}` in devcontainer.json
3. All new terminals launch `bash` instead of `zsh`
4. When I inspect `settings.json` in the remote, I do see `"terminal.integrated.shell.linux": "/usr/bin/zsh"`
5. When I manually run `zsh`, it does its first-run cloning, so `zsh` is not being launched under-the-hood, AFAICS.

Please let me know what logs you'd like and I'll provide them!

**Comment by chrmarti** [comment]
Do you have a `.vscode/settings.json` in your workspace? That can override the remote settings.

**Comment by fsackur** [comment]
I've tried with and without that file. I also tried with and without settings in my local settings.json.

I am using a non-root user which is created in the image. It has always been this line: 
`useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME`

I believe the settings as described used to override that.

I changed that line to point to zsh instead, which fixes my problem because I now get zsh in new terminals, but the setting still has no effect because new terminals now always open zsh.

So perhaps a better problem desription would be:
"terminal.integrated.shell.linux setting has no effect in dev container when running as non-root user with shell set by useradd"

**Comment by chrmarti** [comment]
This is working for me. How do you specify which user should be used? (Since there are several ways to do that.)

And could you append a screenshot of the settings editor when you search for that setting, like:
![image](https://user-images.githubusercontent.com/9205389/94573126-11050100-0272-11eb-9e5c-aa9a7919cb1f.png)
(That says where it is modified.)

**Comment by fsackur** [comment]
Hi @chrmarti ,

I feel bad because I didn't update this issue. I can confirm that I've been happily booting into zsh for months now.

In my devcontainer.json I have
`"terminal.integrated.shell.linux": "/usr/bin/zsh",` - that setting doesn't show up in the settings GUI editor, but it does show up in settings.json in the `Remote [Dev Container: foo]` section (section? config container? config tree?)
![image](https://user-images.githubusercontent.com/3678789/95323506-327b7380-0896-11eb-8db4-ce2f240e212f.png)

I do not have `terminal.integrated.automationShell.linux` set in devcontainer.json but it's /bin/sh in my user settings for some reason. Doesn't appear to be hurting anything.

I believe that this is confirmation that the setting is now working as expected.

I have `SHELL=/bin/bash` in the container image, and my user entry in `/etc/passwd` shows `/bin/bash`, but Code is overriding that (as I want), and all my terminals open in zsh.
