### ISSUE TITLE
Support for RequestTTY/-t SSH option

### ISSUE THREAD

**Issue by ngollan** [microsoft/vscode-remote-release#2062]
The remote SSH extension currently always starts the remote server with the `-T` option, which makes the root shell process not run as a login shell. On remote systems using some shells like `dash`, this means no initial script like `.profile` is executed.

My current use case would be to inject an `ssh-agent` into the session that is then shared for all processes.

Please add a setting that allows to swap the `-T` parameter for `-t` and possibly evaluate that parameter to the appropriate `RequestTTY` option in a generated host entry.

**Comment by roblourens** [comment]
When the remote server first starts, it spawns process of `$SHELL -il` that will evaluate your initial scripts, and we copy the environment from that process into the newly spawned remote extension host.

The ssh process is not necessarily the root process of VS Code's remote processes so `-t` wouldn't work the way you expect.

If you are modifying your `.profile` and expecting to see the results in the remote environment, you should know that we only do this user environment discovery once when the server starts, and you can force it to run again by running the commadn "Kill VS Code Server on Host...", let me know if that helps.
