### ISSUE TITLE
Unable to configure terminal for remote-ssh to windows server

### ISSUE THREAD

**Issue by Mossop** [microsoft/vscode-remote-release#2063]
- VSCode Version: 1.42.0-insider e74405d11443c5361c31e2bc341866d146eee206
- Local OS Version: OSX 10.15.2
- Remote OS Version: Windows 10 Pro 19041.1
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to a remote workspace
2. Attempt to configure a terminal via terminal.integrated.shell.windows and terminal.integrated.shellArgs.windows
3. Launch a terminal and expect it to use the configured terminal.
4. Terminal always launches Powershell

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by dashkan** [comment]
@Mossop ,

I can't even connect. I have OpenSSH server configured on windows server and trying to connect from macOS.

```Unsupported architecture: MINGW64_NT-10.0-17763 x86_64```

Do you mind sharing how you got it to connect?

I created a [StackOverflow](https://stackoverflow.com/questions/59418523/remote-editing-over-ssh-to-windows-server) question also.
