### ISSUE TITLE
remote ssh makes site unresponsive on EC2 (t3.small)

### ISSUE THREAD

**Issue by mubasshir** [microsoft/vscode-remote-release#2064]
- VSCode Version: 1.41.0
- OS Version: MacOS Catalina 10.15.1

Steps to Reproduce:

1. Install vscode remote ssh plugin
2. connect to EC2 instance via SSH

Does this issue occur when all extensions are disabled?: No

**Comment by mubasshir** [comment]
It's mostly nodejs based app proxying by Nginx.  But it has happened with Wordpress site as well.

**Comment by roblourens** [comment]
The remote may just need more ram/CPU, we need some headroom.
