### ISSUE TITLE
[Bug] Can no more attach/connect container if both begin by the same name.

### ISSUE THREAD

**Issue by Yivan** [microsoft/vscode-remote-release#2065]
Hello,

I updated vscode to last version 1.41.1, and remote extensions are up to dates too.
I haven't had this problem before.

It concerns Remote containers extension.

If two containers get the same begining name, vscode will always open the same container.
In my case, one is `pms-phpmyadmin` and the other `pms-php`. I want to attach/connect `pms-php` but no way. Every action on `pms-php` attach/connect `pms-phpmyadmin`.

I think this is because they begin the same name...
It was working ok before last update.

It is a pretty blocking one, as i can no more at all connect/attach the container i need to work: `pms-php`.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/9025839/71214156-3a413b80-22b5-11ea-9a3f-92b3709ad97e.png)

Thanks.

**Comment by chrmarti** [comment]
Does `F1` > `Remote-Containers: Attach to Running Container...` work?

**Comment by Yivan** [comment]
Thansk for looking into it.
Same problem by going through the palette.

Choosing pms-php here:

![image](https://user-images.githubusercontent.com/9025839/71311403-0c780600-241f-11ea-8927-f5fc9a3be192.png)

...open the pms-phpmyadmin container. : (

The only way for now is to kill the pms-phpmyadmin containers and after all menu/palette open this one like intended.

Seems really two containers beginning the same name make a problem. It should not.

For information, i tried attach other container in the same docker-compose project stack:
- pms-apache: work great
- pms-redis: attach this good one (but cannot install vscode server inside)
- pms-redis-commander: attach this good one (but cannot install vscode server inside)

You can see pms-redis have same begining name but don't seems have the problem. Maybe because vscode server cannot be installed inside. In pms-php and pms-phpmyadmin it can.
Can it be a sort of history/cache... ?

Thanks!

**Comment by chrmarti** [comment]
Found the problem, thanks.

Could you open a new issue for the case where the server doesn't install?

**Comment by Yivan** [comment]
Thanks a lot for the fix.

For the server which doesn't install it is normal in the pms-redis and pms-redis-commander, they are alpine ones. This was just to check for opening the good containers relative to its name (as both begin by pms-redis).
I will test when fix is available, and open if needed an issue if there is a problem of install for the php container.
I confirm this issue can be closed.

**Comment by alexr00** [comment]
@chrmarti I tried to repro the original issue by renaming two debian containers I have to be "abcd-efg" and "abcd-efghij"; however, I couldn't repro the issue on stable so I can't verify that it no longer happens in insiders. Are there any additional steps?

**Comment by chrmarti** [comment]
@alexr00 Were you using `--name`? How did you rename?

**Comment by alexr00** [comment]
I had two existing containers and I did `docker rename`

**Comment by chrmarti** [comment]
Cannot reproduce anymore. There was some randomness involved in that it depended on which container was returned as the first result of a substring match. Maybe the latest Docker version changed the ordering logic (guessing).

I suggest to verify by code review.

**Comment by alexr00** [comment]
Verified by code review
