### ISSUE TITLE
[Bug] Settings docker.host using ssh:// or tcp:// don't work, ssh tunnel work.

### ISSUE THREAD

**Issue by Yivan** [microsoft/vscode-remote-release#2066]
- VSCode Version: 1.41.1
- Local OS Version: Windows 10 uptodate (stable channel)
- Remote OS Version: debian buster uptodate
- Remote Extension/Connection Type: Docker

Using remote containers, it work fine with the ssh tunnel (and fast). ssh:// tunnel don't work.
It cannot fetch containers list and nothing is indicated in Output panel.

~~Can it be linked to: https://github.com/PowerShell/Win32-OpenSSH/issues/1263
I encounted this issue.
For information `Remote ssh` work well. This problem is for `Remote containers` on remote host with docker (so by SSH).~~

~~If this is linked to the agent problem, could you maybe adapt code to try to SSH by another way (if git bash is installed for instance) ? ssh-agent of Windows 10 seems pretty old and does not support ssh-rsa2-512 which is used by my keys (generated from the Gitlab procedure, so pretty classic).
And why Remote SSH work but not Remote containers... is the ssh process different ?~~

=> Update, see my comment just below please.

Like I say it creating the tunnel (via Gitbash) works fine, but it is annoying to have to do this.

Thanks.

**Comment by Yivan** [comment]
I made further tests on my Windows 10 using other ways to connect to remote containers.

The setup is the following:
- host: Windows 10 Pro uptodate (not insider, stable channel)
  - VSCode uptodate (1.41.1), extensions updated.
- remote machine: vagrant-docker (an HyperV VM on the same Windows computer). It contains:
  - Debian Buster OS, uptodate
  - Docker uptodate, with some containers running (`docker ps` display them)

Windows firewall has been disable during all the tests and there is no firewall on the VM side.
Everytime `docker.host` has been changed, VSCode has been closed and restarted.
I tryed to reboot Windows too.

**Method 1: by ssh tunnel**
- Running a ssh tunnel: `ssh -NL localhost:23750:/var/run/docker.sock vagrant@vagrant-docker`
- In `settings.json`: `"docker.host": "tcp://localhost:23750"`
=> Work ok

**Method 2: with direct ssh protocol**
- In `settings.json`: `"docker.host": "ssh://vagrant@vagrant-docker"`
=> Don't work: try to find containers, endless progress blue bar on the remote containers panel on vscode gui) and the pannel stay empty (no logs are written in extension logs)
Finally, I don't think it is related to https://github.com/PowerShell/Win32-OpenSSH/issues/1263, as I installed https://github.com/PowerShell/Win32-OpenSSH/releases which has not this ssh bug but got the same problem/result in VSCode.
Running `ssh vagrant@vagrant-docker` in Powershell log me directly (with my private key) in the remote computer so all is ok on the ssh side I think.

**Method 3: with docker API**
- "docker.host": "tcp://vagrant-docker:2376"
=> Don't work, display `Get started with containers by installing and starting Docker or visiting the help section above.`
I installed manually only the `docker.exe` files (extracted from the last Docker for Windows install package, as I don't want install full docker on the Windows).
On a Windows gitbash shell running: `DOCKER_HOST=vagrant-docker:2376 docker ps` list well the containers.
In the same Windows gitbash shell, I tried to run VSCODE with: `DOCKER_HOST=vagrant-docker:2376 Code.exe` (with the settings.json docker.host commented), VSCode open well, but same problem/result than with the settings.json.


**Questions please:**

So for now only tunnel seems reliable.
Maybe you could add a button to create the tunnel from the VScode GUI ?
Another idea: Connection to "Remote SSH" so the other extension, will create this tunnel or allow to list container of this remote ssh host in the Remote container panel. Would be nice.

What about method 2, why it doesn't work ?

What about method 3, why it doesn't work ? Do we need having dockerd (the daemon running ? It has no use as container are remote here), if yes it should not prevent using Remote containers on a remote host.

Hope it help !
Thanks.

**Comment by chrmarti** [comment]
For `ssh://` to work you currently need to add your private key to the ssh-agent. Is your private key listed with `ssh-add -l`?

Method 2 and 3 should work. Could you check if there is anything in the dev console? (Help > Toggle Developer Tools)

**Comment by Yivan** [comment]
Thanks for looking into this issue.

---

For method 2 (SSH):

All concerning SSH keys seems ok, please see:

![container-ssh](https://user-images.githubusercontent.com/9025839/71311745-aee5b880-2422-11ea-93c2-2789d7916b83.png)

Strangely if i was using method 1 just before (tunnel) sometime the containers are listed (a cache I imagine). I tried to open one so (but no connnection). On Developer Console Log i got:

![image](https://user-images.githubusercontent.com/9025839/71311820-d7ba7d80-2423-11ea-8263-525df7fe7446.png)

There is no log when i click refresh the list and containers. Only the infinite loading (blue line moving).

---

For method 3 (TCP docker API), i got the following message in the developer console when wanting to list the containers:

![image](https://user-images.githubusercontent.com/9025839/71311971-0a657580-2426-11ea-951e-25112daa019e.png)

Hope it helps!

**Comment by chrmarti** [comment]
When you `ssh` to the box it asks you for a password. Could you change that to only require the private key? There is currently no way for you to enter the password in Remote-Containers.

When you use TCP, you might be using SSL (supported by dockerd). For that to work, you also need to set the `"docker.certPath"` and `"docker.tlsVerify"` settings.

**Comment by Yivan** [comment]
For SSH, it is always the case, there is a private key. Like I said it in my first post, it ask password because of the https://github.com/PowerShell/Win32-OpenSSH/issues/1263 bug.
See in the vscode screenshot please: `warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512).` So the ssh-agent fall back to password.

The only possible fix was to install a new version of ssh-agent for windows (https://github.com/PowerShell/Win32-OpenSSH/releases), i do it, but it change nothing.
But I will install it again so i can provider you the logs in this case.
In all case this is not a good way to have to install this to make Remote ssh working. The problem is the windows ssh-agent (the one provided with w10) has not been patched with the fix and use always the old ssh agent.

If i desactivate the agent (service desactivated), the ssh user@machine work well, it is only when the ssh-agent is activated.
So maybe a fix could be VSCode don't force to have the the ssh-agent activated, so ssh will work (but ssh-agent is used to copy the ssh keys in the remote host if i have well anderstand). This could be leave to the final user to do it.

---

For the tcp, tls is desactivated (remote docker host and i forced too on json vscode settings). It change nothing. And like i say it running from my host in a Git Bash `DOCKER_HOST=vagrant-docker:2376 docker ps` works fine. But same host in json settings of vscode don't work.
So i am pretty sure it is not a tls/certificates problem.

To go further i tested on PowerShell by setting the DOCKER_HOST variable, and work great.

![image](https://user-images.githubusercontent.com/9025839/71384777-91138180-25e3-11ea-98bb-37eeb17844e6.png)

(host is vagrant-unique1 here because i made side test on this VM, but the same than vagrant-docker in this issue).

To go even further I added DOCKER_HOST to the environment settings of Windows.
So opening a powershell and run `docker ps`, it display well the list of the remote containers.
Opening VSCode (i commented the docker.host settings.json before, and restarted vscode) has always the same problem...
Why powershell can see it, and not vscode... their seems to be a problem.

Thanks.

**Comment by Yivan** [comment]
Ok I reinstalled the last version of https://github.com/PowerShell/Win32-OpenSSH/releases so ssh-agent work well (**but this is just a workaround and this should be fixed on vscode to not rely on the windows agent i think**). This time i rebooted the computer to be sure all is ok after the install.

It list containers! But that's all, because any actions on them bring an error (removing a container, open a container...). Here is some screenshot.

The list, please see the terminal, ssh work well.

![screen1](https://user-images.githubusercontent.com/9025839/71385277-bc4ba000-25e6-11ea-8aa5-7ca75ad013e8.png)

Trying remove a container:

![image](https://user-images.githubusercontent.com/9025839/71385237-6c6cd900-25e6-11ea-9ec6-4d7da368005d.png)

Trying connect to a container:

![image](https://user-images.githubusercontent.com/9025839/71385304-ed2bd500-25e6-11ea-9857-91adf9202652.png)

So there is always a problem... is the list of containers just a residual cache and in fact connection is not done at all as any action on them don't work ...? Or something else...?

**Comment by Yivan** [comment]
Hello, I come back to this issue please. Do you need any other informations ?
We would really like to be able to use the remote container with direct ssh method (method 2), this is priority, and with API method (method 3), less prioritary I think as it need to open the docker socket externally.

Actually we must use method 1 which involve running manually the ssh tunnel each time on Windows before running vscode. Maybe an option to create the tunnel directly from vscode could be added ? (should I open another issue for this ?)

If you need further information to fix method 2 and 3, feel free to ask any.
Thanks again.

**Comment by hholst80** [comment]
Please update the bug subject. The tcp:// endpoint works.

**Comment by Yivan** [comment]
@hholst80 Thanks for your insight.
I should be keept in the subject, because in the case I describe it doen't work on my side. So it seems there si a problem.
Like I said, if i do "docker ps" on a windows shell I see the remote container. But in vscode... no.

For now only creating manually a tunnel (method 1) work. Both ssh (method 2) and tcp (method 3) don't work.
I hope it could be fixed, no new on this issue this last month.
I can provide any necessary information to help on this!

Thanks.

**Comment by hholst80** [comment]
Try setting DOCKER_HOST, DOCKER_TLS_VERIFY=1 and DOCKER_CERT_PATH in your User environment prior to starting VSCode. Code always call out to CLI but if there is an edge case where the settings is not propagated to the instantiated CLI call then it will not work. Setting a user session wide environment variable will cover you in that case.

**Comment by Yivan** [comment]
@hholst80 @chrmarti 

I tried again, but no lucks...
I setted DOCKER_HOST as environment variable (user and system), close VSCode and restart it.
I tested with those vscode json settings too (and restarted vscode):
```
    "docker.host": "10.213.237.2:2376",
```
and too:
```
    "docker.host": "10.213.237.2:2376",
    "docker.tlsVerify": "0",
    "docker.certPath": "",
```

(
but those last one seems to bring additionnal problems, especially the line `"docker.tlsVerify": "0"`

![image](https://user-images.githubusercontent.com/9025839/74163868-49909580-4c23-11ea-98fd-935335a89ed1.png)
)

If i run "docker ps" from powershell it works fine:

![image](https://user-images.githubusercontent.com/9025839/74163061-18fc2c00-4c22-11ea-8c40-f2cc00ef45ed.png)

I do not use TLS. Is it mandatory for VSCode ? (it is a local VM so do I not need this layer of security).

Here is a screenshot of the developper tool panel on vscode (only using "docker.host": "10.213.237.2:2376" and "docker.certPath": "" and DOCKER_HOST system and user variable) :

![image](https://user-images.githubusercontent.com/9025839/74163437-ad668e80-4c22-11ea-8c72-b48113bc21c4.png)

It seems to try to use SSL... and complain about SSL version. I use Git for Windows (uptodate on stable channel which provide openssl, pretty classic developper stack).

What I don't get is if on powershell "docker ps" works fine, why not vscode isn't able to list containers...

Thanks.

**Comment by Yivan** [comment]
Any news on it ? The issue is labeled need info, i can provide if needed so this issue could be resolved please.

Just to update: i just tried with last VS Code 1.42.1 and remote extension updated (and Windows 10 uptodate on stable channel).
I generated an ed25519 key to test again SSH method because it seems to help (https://github.com/PowerShell/Win32-OpenSSH/issues/1263#issuecomment-590133215), but it changes nothing and vs code cannot connect.

On powershell running `docker ps` display well the remote conainers and  `ssh vagrant@vagrant-docker` log me directly in the VM (where is docker and where i can run docker ps to list containers). So from powershell/windows point of view all works fine.

Am I alone to have this problem ? But the stack here is really pretty classic, nothing fancy. Same problem on our others developpers computers. Could people share experience ? Thanks.

**Comment by chrmarti** [comment]
Are you sure you have the Docker daemon configured to not use TLS? https://docs.docker.com/engine/reference/commandline/dockerd/ says: "It is conventional to use port 2375 for un-encrypted, and port 2376 for encrypted communication with the daemon."

**Comment by Yivan** [comment]
Thanks @chrmarti for coming back to this.
As it is, it use 2376 unencrypted (I didn't configure anything special).
Like i say it, `docker ps` work great from powershell (using env variable DOCKER_HOST at `10.213.237.2:2376`). So why vscode cannot communicate ? (i tried disabling firewall windows, this is the only security software on the computer, but change nothing)

Here `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 459
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-6-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.791GiB
 Name: vagrant-docker
 ID: QBGI:YG3A:IZEN:X2LP:LDF6:ZRHE:4VV5:QUK6:NDHE:4E5K:R6KY:5YWJ
 Docker Root Dir: /c/var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:2376 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: No swap limit support
```
At the end it says well 2376 unencrypted.

On VS code, the message is always: `Get started with containers by installing and starting Docker or visiting the help section above.`

Any other info I can provide you to check into this ?

Aside of this SSH method don't work too, is it related ?

Thanks

**Comment by Yivan** [comment]
By the way here is my `/etc/docker/daemon.json`:

```

{
  "data-root": "/c/var/lib/docker",
  "bip": "172.17.0.1/24"
}
```

And daemon is started with the default systemctl command (i didn't added any custom arguments).

**Comment by Yivan** [comment]
Alleluia ! I changed docker port to 2375 and docker.host to this value, and works fine.
So it seems **there is a pbl with VSCode on other port unencrypted**... (some hardocded values ?).
As windows/powershell works well with unencrypted 2376, VSCode don't.
I think it give you some infos to track the bug.

So only SSH method don't work now (changing docker host port to 2375 changed nothing, it always don't work, and not related i think).
For this SSH part any information I can provide ? Like i say it from powershell "ssh vagrant@vagrant-docker" log me in directly in the VM, but `ssh://vagrant@vagrant-docker` as setting on vscode don't work.
Thanks.

**Comment by hholst80** [comment]
Just watch out for the weird semantics of DOCKER_TLS_VERIFY it should be set to an empty string and nothing else.

**Comment by hholst80** [comment]
Using DOCKER_HOST=ssh://vagrant@vagrant-docker like connection string requires a fairly new version of docker and its client libraries. I would assume that vscode ships with a too old version. (no, it does not work for me either).

**Comment by Yivan** [comment]
@hholst80 Thanks. The docker.exe (cli client) is a very recent version.
But following your message and my previous remark about ed25519 keys being better supported by the native ssh windows agent, it tried again to use ssh with this ed25519 key by adding it to ssh agent (i haven't try this before)... and miracle... it works.
So the problem is definitly the problem i have pointed at the start of this issue, windows ssh agent don't work well and is buggy: https://github.com/PowerShell/Win32-OpenSSH/issues/1263

@chrmarti As the two problems concerning tcp and ssh method have a better explaination now, i will close this issue, and open two new separated issue for the two bug with better explaination now that we know the cause.
