### ISSUE TITLE
wsl would not reconnect

### ISSUE THREAD

**Issue by dkout** [microsoft/vscode-remote-release#207]
Issue Type: <b>Bug</b>

There is no way to restart wsl and reconnect to it. It got stuck at: `Failed to connect to the remote extension host server (Error: connect ECONNREFUSED 127.0.0.1:50392)`

Extension version: 0.32.0
VS Code version: Code - Insiders 1.34.0-insider (daf71423252a707b8e396e8afa8102b717f8213b, 2019-05-06T22:08:08.969Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (5.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by egamma** [comment]
@aeschli any ideas how to track this issue down further.

**Comment by aeschli** [comment]
@dkout How did you get in that state? Normally WSL doesn't go away...

**Comment by brifly** [comment]
I had a similar issue - I managed to get it into that state by opening a very large json file and then force turning on features like code folding.
