### ISSUE TITLE
90s timeout is too short when download server on client side

### ISSUE THREAD

**Issue by DC-Shi** [microsoft/vscode-remote-release#2073]
- VSCode Version: 1.40.2
- Local OS Version: Windows_NT x64 10.0.18362
- Remote OS Version: Ubuntu 18.04.2 LTS
- Remote Extension/Connection Type: WSL

Reason: it cannot download the file in 90s.
Workaround currently: download manually(but if updated, need manually download again)
Solution: have some parameter to config the timeout.

Steps to Reproduce:

1. Have a not that fast internet connection, i.e. with only 2Mb/s
2. Open a remote window: Remote-WSL New Window
3. open any wsl folder
4. (it will automatically download server on client side, vscode-server-linux-x64.tar.gz)
5. VS Code Server for WSL failed to start. No messages received for 90s

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: if disabled other extensions and keep wsl only, Yes.

**Comment by aeschli** [comment]
This got fixed in the latest version of Remote WSL (0.41.6). It requires VSCode 1.41.

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode-remote-release/issues/1655
