### ISSUE TITLE
WSL2 fails to start in VS Code

### ISSUE THREAD

**Issue by TerryJey** [microsoft/vscode-remote-release#2083]
Issue Type: <b>Bug</b>

This started happening after a recent windows update (insider build). WSL2 is installed.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.19041
Fetching remote diagnostics for 'WSL: Ubuntu-18.04' failed: connect ECONNREFUSED ::1:32829

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (9.80GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/mnt/c/projects --remote=wsl+Ubuntu-18.04|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu-18.04' failed: connect ECONNREFUSED ::1:32829
</details>Extensions: none

**Comment by TerryJey** [comment]
The error was: connect ECONNREFUSED ::1:32829

I can confirm that I am no longer getting this error after a second machine reboot. Seems this error is intermittent. Happy for this to be closed.

**Comment by aeschli** [comment]
Thanks a lot for the update!

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode-remote-release/issues/2037
