### ISSUE TITLE
Config for remote shell

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode-remote-release#2088]
Usually people would config a zsh to use inside vscode locally. But it would cause vscode remote to try to launch the remote zsh(quite possibly not installed or unconfigured for productive use). I hope there would be an option of default shell launch for remote and that default should be bash.

**Comment by Tyriar** [comment]
You can use terminal.integrated.shell.linux in your remote settings to configure this, however I recommend not setting that at all and instead letting VS Code pick up the default for the system it's running on (`$SHELL`)

**Comment by xgdgsc** [comment]
I konw that config, but setting at every server isn' t good enough. Then why would vscode opens zsh everytime connecting to a new server even the $SHELL is bash?

**Comment by Tyriar** [comment]
@xgdgsc 

> however I recommend not setting that at all and instead letting VS Code pick up the default for the system

That will help avoid setting it on the remote.

**Comment by xgdgsc** [comment]
But it would also open bash locally. What if I want to use zsh locally on linux without changing global $SHELL, and use bash on servers?

**Comment by Tyriar** [comment]
@xgdgsc why don't you want to change the default shell? The setting is available for just that reason but it come with the trade off that you need to change the remote settings as well.

**Comment by xgdgsc** [comment]
I' m in a controled ldap working enviornment. I have issues with login when I change shell with chsh.ldap. So I' d rather only change shell in preferences of each terminal program.

**Comment by Tyriar** [comment]
@xgdgsc well you need to configure it per remote then, or convince your admin to let you change the shell.
