### ISSUE TITLE
How should I shut down the process when I exit the remote connection

### ISSUE THREAD

**Issue by shadowmimosa** [microsoft/vscode-remote-release#2089]
🚨 The issue tracker is not for questions 🚨

When I close the remote connection, there are multiple vscode server processes on the server.
Aren't these processes shutting down automatically?
Can only be closed manually one by one?

```
xuan     16874  0.0  0.8 671880 16576 ?        Sl   Dec23   0:00 /home/xuan/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/node /home/xuan/.vscode-server/extensions/ms-python.python-2019.11.50794/out/client/debugger/debugAdapter/main.js
```

Thanks

![Snipaste_2019-12-24_10-20-38](https://user-images.githubusercontent.com/38422761/71390224-6ef91e00-263a-11ea-996d-abd8fd25d31b.png)

**Comment by aeschli** [comment]
@shadowmimosa Is this with Remote-WSL. SSH or remote containers?
