### ISSUE TITLE
Password Authentification

### ISSUE THREAD

**Issue by BernierCR** [microsoft/vscode-remote-release#209]
Hello. I am asking for password based authentication, not key. My organization does not let us log in with keys. I also need to use sudo. I need this extension to log in with passwords, and run sudo before mounting anything. It's ok if I have to manually type in my password each time, wouldn't want to have to store it in plaintext after all. 

Is this feature at all feasible?

**Comment by roblourens** [comment]
Password auth is supported, but you will have to set a setting, `remote.SSH.showLoginTerminal`, and enter your password twice for each window. See https://code.visualstudio.com/docs/remote/troubleshooting#_enabling-alternate-ssh-authentication-methods for details.

I'm not sure which commands you would need to use `sudo` for, you can try it and let me know if it works.

**Comment by BernierCR** [comment]
OK cool. 

So I tried this. The first time, the terminal opened, it tried to activate my conda in that terminal, probably shouldn't do that. I saw the password prompt. But then it disappeared before I could enter a password. 

Each time after that, it fails without even showing me the terminal. Well it starts to show the terminal, but disappears before I can see it. Then I get this error. 

Can't connect to -----: unreachable or not Linux x86_64 (packet_write_poll: Connection to UNKNOWN port -1: Permission denied)

The server is reachable and it's linux. Standard RHEL EC2 instance. 

I got rid of the conda activation by changing to the standard python interpreter. Same thing. The terminal disappears before I can type in a password, except that first time. Weird. 

So what does packet_write_poll: Connection to UNKNOWN port -1: Permission denied) mean? 

Thanks

**Comment by BernierCR** [comment]
OK, so if i try to SSH from WSL, it works great. But this extension needs to SSH from windows. If I try to SSH from windows, I get getsockname failed: Not a socket. That's probable the problem. Now what does that one mean?

**Comment by BernierCR** [comment]
ok, so some of that was due to trying to use ControlMaster . This doesn't work on windows, and your documentation doesn't mention that. 

After that, this happens. 

Corrupted MAC on input.
ssh_dispatch_run_fatal: Connection to 10.65.59.58 port 22: message authentication code incorrect

It will connect with a supported mac like this. 

ssh -m hmac-sha2-256 user@host

However, the vscode extension can't change the mac. How to fix this underlying OpenSSH issue?

**Comment by BernierCR** [comment]
ok, so I set some macs in the .ssh/config. This stuff should all be clear in the instructions. I get that this is preview so the documentation may be incomplete, but please make sure whoever is responsible for the documentation knows about these problems. 

Now we get to the real problem. 

Password:
Connected to SSH Host - Please do not close this terminal
channel 3: open failed: administratively prohibited: open failed
channel 3: open failed: administratively prohibited: open failed
channel 4: open failed: administratively prohibited: open failed

I need you to add a sudo to the very beginning of your script if you can. I need root access, even after this part, because that is how the ebs drive with the code on it is mounted to require. 

Thank you very much.

**Comment by roblourens** [comment]
- You're right about ControlMaster on Windows, I filed this to find a workaround and document it (I've been at the build conference all week and will update the docs soon): https://github.com/microsoft/vscode-remote-release/issues/96 
- I haven't encountered an issue with the mac yet, so in this case your server only supports that particular mac, so you have to tell the client which one to use? I am assuming that users will have set that in their ssh config so they aren't typing it every time they connect, and I can try to call that assumption out in the docs too.
- Now it sounds like TCP forwarding is disabled on your server, is that the case? There is no script to which I can add sudo. We forward a port from the host with a command like: `ssh hostname -N -L localhost:4321:localhost:4321`
