### ISSUE TITLE
Browser opens localhost instead of Forwarded Ports.

### ISSUE THREAD

**Issue by 10lk** [microsoft/vscode-remote-release#2090]
- VSCode Version:
1.41.1
- Local OS Version:
Windows 10 Pro
- Remote OS Version:
Debian GNU/Linux 9 (Visual Studio Online)
- Remote Extension/Connection Type: SSH/Docker/WSL
? (Visual Studio Online)

Steps to Reproduce:

1. Connect to an instance of Visual Studio Online with Visual Studio Code.
2. Start the server with `npm start` on the command line.
3. Right-click the target port of ENVIRONMENT DETAILS> Forwarded Ports.
4. Press Open Port in Browser.
5. Browser opens the localhost URL instead of the Visual Studio Online Forwarded Ports URL.  
However, Connect VIsual Studio Online with a browser instead of VSCode, and press Open Port in Browser to open the URL of Forwarded Ports.
![image](https://user-images.githubusercontent.com/15144931/71395753-a972b300-265a-11ea-8049-5683d6716422.png)
![image](https://user-images.githubusercontent.com/15144931/71396067-f4d99100-265b-11ea-9fa2-9d6d3b2279c3.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by alexr00** [comment]
Moved to VS Online: https://github.com/MicrosoftDocs/vsonline/issues/272
