### ISSUE TITLE
Browser opens The "Enviroments" page of Visual Studio Online  instead of Forwarded Ports.

### ISSUE THREAD

**Issue by 10lk** [microsoft/vscode-remote-release#2092]
- VSCode Version:
1.41.1
- Local OS Version:
Visual Studio Online, Client : Oculus Quest + FireFox Reality 7
- Remote OS Version:
Debian GNU/Linux 9 (Visual Studio Online)
- Remote Extension/Connection Type: SSH/Docker/WSL
? (Visual Studio Online)

Steps to Reproduce:

1. Connect to an instance of Visual Studio Online with FireFox Reality 7.
2. Start the server with `npm start` on the command line.
3. Right-click the target port of ENVIRONMENT DETAILS> Forwarded Ports.
4. Press Open Port in Browser.
5. Browser opens "Enviroments" page of Visual Studio Online instead of the Visual Studio Online Forwarded Ports URL.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by egamma** [comment]
Moved to VSO.
