### ISSUE TITLE
SSH CANOT find network drive

### ISSUE THREAD

**Issue by viponedream** [microsoft/vscode-remote-release#2094]
connect to the remote computer( installed in vmware)
it can open the c: d: driver , but can't open the X: (link the the network location not localdrive)
![QQ图片20191224223021](https://user-images.githubusercontent.com/16624529/71416843-4bb38a80-269d-11ea-83c9-e4a5366af252.png)

**Comment by roblourens** [comment]
Sorry, I don't quite understand your scenario. You are connecting from windows to another machine? How are you trying to open the network path?

**Comment by viponedream** [comment]
![QQ图片20200105230949](https://user-images.githubusercontent.com/16624529/71782051-80660100-3010-11ea-9a71-65e6ec4ac56a.png)

**Comment by viponedream** [comment]
remote computer is installed in vmware.
from local host, i can connect to the D drive. not X drive

**Comment by viponedream** [comment]
![QQ图片20200105231323](https://user-images.githubusercontent.com/16624529/71782081-008c6680-3011-11ea-9977-16028b943400.png)

**Comment by roblourens** [comment]
I still need more details. Why can't you connect to the X drive, what happens when you try to do it?
