### ISSUE TITLE
Permission denied when connecting to .vscode-server

### ISSUE THREAD

**Issue by sasninja** [microsoft/vscode-remote-release#2095]
Issue Type: <b>Bug</b>

Immediately after upgrade of VS code I no longer can use remote SSH connection.

VS Code Output:

```
[08:49:36.162] remote-ssh@0.48.0
[08:49:36.162] win32 x64
[08:49:36.163] SSH Resolver called for "ssh-remote+ubusrv-local", attempt 1
[08:49:36.163] SSH Resolver called for host: ubusrv-local
[08:49:36.163] Setting up SSH remote "ubusrv-local"
[08:49:36.186] Using commit id "9579eda04fdb3a9bba2750f15193e5fafe16b959" and quality "stable" for server
[08:49:36.186] Testing ssh with ssh -V
[08:49:36.241] ssh exited with code: 0
[08:49:36.241] Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[08:49:36.243] Using SSH config file "C:\Users\Thoma\Connections\vscode\config_vs_code_v03"
[08:49:36.243] Running script with connection command: ssh -T -D 50785 -F C:\Users\Thoma\Connections\vscode\config_vs_code_v03 ubusrv-local bash
[08:49:36.245] Install and start server if needed
[08:49:36.246] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[08:49:36.440] > 
[08:49:36.440] Got some output, clearing connection timeout
> 
> Enter passphrase for key 'C:\Users\Thoma\Connections\vscode\id':
[08:49:47.493] > 
> 
[08:49:47.920] > b5f8bc149d78: running
> mkdir: cannot create directory ‘/home/thomas/.vscode-server’Creating the server install dir fa
> iled...
> b5f8bc149d78##34##
> : Permission denied
> 
[08:49:48.200] "install" terminal command done
[08:49:48.201] Install terminal quit with output: : Permission denied
[08:49:48.201] Received install output: : Permission denied
[08:49:48.202] Resolver error: Permission denied
[08:49:48.205] ------
```

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.17763
Fetching remote diagnostics for 'SSH' failed: Permission denied

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (5.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: Permission denied
</details>Extensions: none

As a workaround I tried on the remote server: chmod -R 777 .vscode/ .vscode-server/ but that did not solve it.

**Comment by roblourens** [comment]
Does `/home/thomas/.vscode-server` already exist? The command we try to run is `mkdir -p /home/thomas/.vscode-server/bin/9579eda04fdb3a9bba2750f15193e5fafe16b959`

I don't know why the log looks a little messed up like it's missing a couple newlines...

**Comment by sasninja** [comment]
If the output of the log looks like it's missing a couple of line- I
deleted the logon banner.  Also the home directory is encrypted. But at the
time it was unencrypted.

Thomas Panasiewicz
linkedin.com/in/thomaspanasiewicz

**Comment by roblourens** [comment]
Does that mean you expect to not have permission to create a directory?

**Comment by sasninja** [comment]
I do, but without crazy customization I have to log in via SSH first and
then unencrypt the home folder.

Since the home folder is encrypted the SSH keys don't sit in home but since
I didn't customize the VS code commands I have to do the extra step of
unencrypting the home folder first.  If I don't unencrypt it first I get a
bad pipe error. But in this case I was in and working and then I upgraded
and it just stopped working.

Thomas Panasiewicz
linkedin.com/in/thomaspanasiewicz

**Comment by roblourens** [comment]
So if you log in with ssh yourself, and run that mkdir command, does it work? Or something like `echo "mkdir -p /home/thomas/.vscode-server/bin/9579eda04fdb3a9bba2750f15193e5fafe16b959" | ssh hostname bash`

What we are trying to do is pretty simple and if it doesn't work, I am guessing there is something strange going on with your encryption setup.

**Comment by sasninja** [comment]
Sure, I can definitely write to my home directory.

Thomas Panasiewicz
linkedin.com/in/thomaspanasiewicz

**Comment by roblourens** [comment]
Ok, but can you try that exact command, and try with vscode one more time? Because that's essentially what we do, and it is pretty simple so I'm not sure what else to ask.

**Comment by sasninja** [comment]
I can. However I was in the middle of a project to I had to roll my vs code
back a version. I won't be able to try it untill next weekend.

Thomas Panasiewicz
linkedin.com/in/thomaspanasiewicz

**Comment by jacksonmoji** [comment]
I am running into the same issue :(.

**Comment by roblourens** [comment]
@jacksonmoji please try to give more details, see the questions I asked above.

**Comment by jacksonmoji** [comment]
@roblourens 

Below is the message I get when I try to run the ssh:

[20:55:48.992] > Creating the server install dir failed...
> 803971cc2fc4##34##
> mkdir: cannot create directory ‘/home/jackson/.vscode-server/bin’: Permission denied
[20:55:49.246] "install" terminal command done
[20:55:49.247] Install terminal quit with output: mkdir: cannot create directory ‘/home/jackson/.vscode-server/bin’: Permission denied
[20:55:49.247] Received install output: mkdir: cannot create directory ‘/home/jackson/.vscode-server/bin’: Permission denied
[20:55:49.250] Resolver error: Permission denied
[20:55:49.271] ------

**Comment by roblourens** [comment]
Can you do that manually? Or see https://github.com/microsoft/vscode-remote-release/issues/2095#issuecomment-570437264

**Comment by jacksonmoji** [comment]
@roblourens 

I managed to get it working. Thanks.

**Solution**
I just changed permissions accordingly in the remote machine. The user ( **Jackson** in my context ) account that I was logging in with had no permissions to the directory ( .vscode-server/bin ) -- since vscode was trying to access via my account. So I changed the permissions for the directory that I need for the remote access operations.

Your comments provided some useful insights for me. Appreciate the help.

**Comment by roblourens** [comment]
Great, glad that worked!

**Comment by ramblingenzyme** [comment]
@roblourens I'm running into this too, I connected to the container after it failed to start and /home/$USER/.vscode-server is being created by root so I had to create $HOME/.vscode-server at the bottom of my Dockerfile, bit silly if you ask me.

**Comment by roblourens** [comment]
Sounds like you are using the Remote-Containers extension, this issue was just about SSH, you could open a new issue for your scenario.

**Comment by ramblingenzyme** [comment]
Oh, sorry about that, you are indeed correct. Will do.
