### ISSUE TITLE
Slow file download

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode-remote-release#2100]
- VSCode Version:  1.41.1
- Local OS Version: ubuntu 16.04
- Remote OS Version: centos 7.6
- Remote Extension/Connection Type: SSH 
Steps to Reproduce:

1. download a large file(GB) from a server in LAN
 
With vscode the speed is about 2M/s(seeing in file explorer, since there' s no progress bar), while using Filezilla I can get 12M/s.

**Comment by isidorn** [comment]
We are not doing anything special in vscode.
I can leave this open as a feature request and assign it to backlog candidates as we do not have immediate plans to fix this.

**Comment by vadbes46** [comment]
Tried to figure out where I can see the status of downloading folders/files
Once started downloading one folder I am not sure when it finishes and starting to download another folder at a time corrupted binary files so they we incomplete

**Comment by isidorn** [comment]
Closing as no plan to fix
