### ISSUE TITLE
Can't create new go container

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#2104]
- Run "Try a sample"
- Pick "go"
- Creating the go container fails, just saying that a long command exited with a non-zero exit code

I think this is the real error:

```
[116252 ms] get "golang.org/x/tools/cmd/gopls": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at //golang.org/x/tools/cmd/gopls?go-get=1
get "golang.org/x/tools/cmd/gopls": verifying non-authoritative meta tag
package golang.org/x/tools/cmd/gopls: cannot find package "golang.org/x/tools/cmd/gopls" in any of:
        /usr/local/go/src/golang.org/x/tools/cmd/gopls (from $GOROOT)
        /go/src/golang.org/x/tools/cmd/gopls (from $GOPATH)
```

Removing that gopls line from the Dockerfile fixed it

**Comment by Chuxel** [comment]
The path upstream changed.  I just resolved this in vscode-dev-containers and the try repo.  LMK if you still see it with latest.

**Comment by dsyer** [comment]
I'm seeing this error now. I seem to have an op to date remote container plugin. How do I get the "latest" Dockerfile?

**Comment by roblourens** [comment]
Does the Containers extension need to be republished?

**Comment by chrmarti** [comment]
You're right, this needs to be published first. Until then you can update the path in your Dockerfile like https://github.com/microsoft/vscode-dev-containers/commit/75ce586e1e7a934b6b1e0456bdc473f222d1749c.
