### ISSUE TITLE
Spelling mistake in remote.WSL.debug (package.json)

### ISSUE THREAD

**Issue by ldd** [microsoft/vscode-remote-release#2105]
- VSCode Version:1.41.1
- Remote - WSL Version: 0.41.6
- Remote Extension/Connection Type: WSL

I think I found a spelling mistake in one of your configuration properties.

For `remote.WSL.debug`, in `package.json` it says
> "If set, the output in the WSL log is shows debug information"

It needs to be:
> "If set, the output in the WSL log shows debug information"

**Comment by aeschli** [comment]
Thanks!
