### ISSUE TITLE
vscode does not load SSH config and remote SSH stops working

### ISSUE THREAD

**Issue by onedigit** [microsoft/vscode-remote-release#2109]
Issue Type: <b>Bug</b>

The remote SSH (nightly) extension was installed and has been working, but has stopped working at all now.  Even tried uninstalling and re-installing it, but it just won't work. It no longer shows the contents from ~/.ssh/config. 

When I try to add a new entry, the UI doesn't actually show any errors.  In the remote SSH log file all I see is this:

[10:31:25.255] Log Level: 1
[10:31:25.255] remote-ssh-nightly@2019.12.34080
[10:31:25.255] linux x64

Nothing more.

Extension version: 2019.12.34080
VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:58:23.119Z)
OS version: Linux x64 5.3.16-300.fc31.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz (12 x 3989)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|31.05GB (22.99GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Please give more details about exactly what is "not working"

> When I try to add a new entry

What do you mean exactly and what is the problem?
