### ISSUE TITLE
vscode-server extensionHost calls wget incorrectly

### ISSUE THREAD

**Issue by dave-irvine** [microsoft/vscode-remote-release#2110]
Issue Type: <b>Bug</b>

Not sure if this is the right place to report this, but when you are using Remote SSH and try to install an extension remotely, the following process chain gets set up:

```sh
node <snip>bootstrap-fork --type=extensionHost --uriTransformerPath=<snip>/uriTransformer.js
\_ /bin/bash
    \_ /bin/sh -c wget --version > /dev/null if [ $? -eq 0 ] then ?wget --connect-timeout=7 --dns-timeout=7 -q  -O - http://169.254.169.254/metadata/v1/id else ?curl --version > /dev/null ?if [ $? -eq 0 ] ?then ??curl --connect-timeout 7 -s  http://169.254.169.254/metadata/v1/id ?fi fi exit 0
```

If you have wget installed, then it spawns this command:

```sh
\_ wget --connect-timeout=7 --dns-timeout=7 -q -O - http://169.254.169.254/metadata/v1/id
```

which by default will cause wget to retry this connection 20 times, which with a 7 second timeout each retry takes quite some time.

A fix would be to pass `--tries=1` to wget. Its not needed with curl as that tries only once by default.

Extension version: 0.48.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (5.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: devmachine2electricboogaloo|
|OS|Linux x64 4.15.0-72-generic|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (4 x 1895)|
|Memory (System)|1.91GB (0.30GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
`--tries` should be set as long as `remote.SSH.allowLocalServerDownload` is enabled (and it's enabled by default) have you disabled that setting?

**Comment by dave-irvine** [comment]
I don't believe I have overriden this setting. I can't see it in `setting.json`.

**Comment by roblourens** [comment]
Sorry, there are actually 2 places we use wget, and I was looking at the wrong one. Should be fixed in tomorrow's nightly version of the extension.
