### ISSUE TITLE
How to get rid of vscode remote-mode? 

### ISSUE THREAD

**Issue by long-nguyenxuan** [microsoft/vscode-remote-release#2112]
After tried vscode remote-development, 
Now I need to do some simple local-development (eg: open a git local repository, edit then push) but the vscode keep asking me to enter password to connect to my remote ubuntu server.  
And if I `Esc` the vscode close immediately. 
Tried disable remote development extension, now I can't install extension anymore cause vscode tried to "Install remote" instead of install on local machine normally.

I can't uninstall Remote Development extensions cause of `No remote extension installed to resolve ssh-remote`, even delete vscode and install a new fresh one 

So, how could I switch back to local-mode as before?

**Comment by roblourens** [comment]
If you just open a new window, it will be a local window. You can also run the command "Close remote connection"

**Comment by long-nguyenxuan** [comment]
> If you just open a new window, it will be a local window. You can also run the command "Close remote connection"

thanks very much for command `Close remote connection`
