### ISSUE TITLE
permission issues when wsl-mode

### ISSUE THREAD

**Issue by Oskang09** [microsoft/vscode-remote-release#2113]
* Reopen folder in WSL
![error](https://user-images.githubusercontent.com/15674107/71652015-2093ff80-2d5d-11ea-9d6b-7f4c9b414366.PNG)

* Reopen folder in Windows / Close vscode
![sucess](https://user-images.githubusercontent.com/15674107/71652017-22f65980-2d5d-11ea-935e-7cad19a6a92d.png)

- VSCode Version: 1.14.1
- Local OS Version: Windows_NTx64 10.0.18362
- Remote OS Version:  Ubuntu 18.04 Bionic
- Remote Extension/Connection Type: WSL

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by aeschli** [comment]
It's very likey https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace that you see.

Please try `"remote.WSL.fileWatcher.polling": true` (VSCode restart required)
