### ISSUE TITLE
Frequent Login Required and Also Remote Extensions are not working Properly

### ISSUE THREAD

**Issue by blazedxi** [microsoft/vscode-remote-release#2114]
Issue Type: <b>Bug</b>

Connect to Remote Desktop And Reload the Workspace

Extension version: 0.48.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-1064-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ujjwal.southeastasia.cloudapp.azure.com|
|OS|Linux x64 4.15.0-1064-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (2 x 2294)|
|Memory (System)|15.64GB (11.64GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Need more details

**Comment by blazedxi** [comment]
So the Remote Development extension I installed has these major issues.

1. We need to provide a password every time the workspace reconnects. Don't have any way to save that.
2. This extension reconnects almost every 10 to 15 mins, even If my internet speed is good.
3. Sometimes only the workspace gets reconnected all the extensions installed over the remote doesn't.  And we don't have any way to refresh or fix it. The only way is to enable or disable the extensions and reload the workspace. Which most of the time fails with the error Broken Pipe.

**Comment by roblourens** [comment]
1. I recommend setting up key-based ssh auth https://code.visualstudio.com/docs/remote/troubleshooting#_configuring-key-based-authentication
2. Can you share the log from the remote-ssh output channel from a time when this happened? Also what extensions are you using, and are you working in a very large workspace or opening a large file?
3. Not sure what is going on here exactly. Can you tell me exactly what you see when the extensions are "not connected"?

**Comment by blazedxi** [comment]
@roblourens 
I am using the extension 

> Remote Development
Most of the time the error states cannot write to non-existing pipeline close remote.

So Remote Development extension allows us to connect to the remote workspace, which is built on the virtual python environment. That environment doesn't connect most of the time.

**Comment by roblourens** [comment]
Can you share the log from the remote-ssh output channel from a time when this happened?
