### ISSUE TITLE
Icons missing in scm provider view on remote SSH instance

### ISSUE THREAD

**Issue by mjcrouch** [microsoft/vscode-remote-release#2115]
When a `SourceControlResourceState` provides an `iconPath` via its `decorations` property - the icon does not appear in the source control view when running via remote - SSH

When I enable the developer console and look at sources, I can see that it is trying to load the remote icon path with a local file:// path, e.g. file:///remote_filesystem_name/my_user/.vscode-server/extensions/...

In contrast, when I look at an icon for an element in a `TreeView` provided by a different extension, I can see that it has been loaded using 127.0.0.1:61150/vscode-remote-resource?path=....

I am looking specifically at the perforce extension. The source can be seen at https://github.com/stef-levesque/vscode-perforce/blob/master/src/scm/DecorationProvider.ts and https://github.com/stef-levesque/vscode-perforce/blob/master/src/scm/Resource.ts

Screenshot demonstrates this
![icons-not-working](https://user-images.githubusercontent.com/49367953/71665305-48329a00-2d54-11ea-9df0-17aa6c121769.PNG)

For reference, this screenshot shows it working locally (see the 'E' icon on the right - which would be status-edit above)
![icons-working](https://user-images.githubusercontent.com/49367953/71665317-4ec11180-2d54-11ea-9605-68762c5deefc.PNG)

- VSCode Version: 1.41.1 ( though I don't think I have seen it working on any version)
- Local OS Version: Windows 7 Enterprise SP1
- Remote OS Version: RHEL 7.6 
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install & set up the perforce extension
2. Open a file in perforce
3. The icons are missing

(obviously if you don't have a perforce server, it would be simpler to reproduce by writing a resource provider that returns an icon path and installing it on a remote vscode instance)

Note that the built in git extension doesn't have this issue despite having very similar source - however I cannot see the icons anywhere in the loaded sources on the development tab so I suspect it is doing something slightly different due to being built in

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by joaomoreno** [comment]
@alexdima @jrieken I am not knowledgeable on the rewriting being done here. Do you mind checking what's wrong?

**Comment by alexdima** [comment]
@joaomoreno I think it is because the protocol is using a string to transport an URI here -- https://github.com/microsoft/vscode/blob/d6d9148182d666cb48a07c1fac93fdc27af47496/src/vs/workbench/api/common/extHost.protocol.ts#L714

**Comment by joaomoreno** [comment]
Thanks @alexdima, I'll pick it up from here.

**Comment by connor4312** [comment]
I tried to run this and am seeing CSP issues that prevent loading the icon:

![image](https://user-images.githubusercontent.com/2230985/75479286-1d2f8580-5954-11ea-99fb-9230f9f1b546.png)

**Comment by joaomoreno** [comment]
@connor4312 SVGs aren't allowed due to security issues concerns. Did you try PNG?

**Comment by connor4312** [comment]
I'll give png a shot. It's somewhat surprising that svg would work locally but fail in the remote.

**Comment by connor4312** [comment]
I run into the same issue with pngs

![image](https://user-images.githubusercontent.com/2230985/75580559-deb1cd80-5a1c-11ea-8e5f-9e4c29d6c0e2.png)

**Comment by mjcrouch** [comment]
My understanding of the svg block is that unsigned svgs are blocked for things that might appear on the marketplace, to prevent security issues for people who haven't installed the extension yet and are just browsing - i.e. extension package icon, badges, readme and changelog

the svgs already work fine for menu icons on the remote host, just the scm ones were missing

**Comment by joaomoreno** [comment]
@connor4312 That definitely looks like a separate issue. The URIs are correct.
