### ISSUE TITLE
The process tried to write to a nonexistent pipe

### ISSUE THREAD

**Issue by joephill11** [microsoft/vscode-remote-release#2117]
- VSCode Version:1.41.1
- Local OS Version:10.0.17763
- Remote OS Version:ubuntu 18.04.3
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1.open up ssh session to remote host username@ip address 
2.recieve error message attached 
![vscode error message](https://user-images.githubusercontent.com/40478857/71674335-f20c2980-2d48-11ea-9e5b-1b4e27486313.PNG)

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Please share the full log, but it looks like you are getting a "permission denied" error.
