### ISSUE TITLE
Rename Symbol not working

### ISSUE THREAD

**Issue by vivekpayasi** [microsoft/vscode-remote-release#2118]
- VSCode Version: 1.41.1
- Local OS Version: macOS Mojave 10.14.6
- Remote OS Version: CentOS Linux release 7.6.1810 (Core)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Write some code (I tried in python) with a particular variable used at multiple places.
2. Go any instance of that variable, right-click and do `Rename Symbol`.
3. It opens a box to rename; enter a new name and press enter/return.
4. No change happens in the code and a notification pops up saying: `No result.`
<img width="137" alt="Screen Shot 2020-01-03 at 16 52 19" src="https://user-images.githubusercontent.com/9135530/71721541-747d1200-2e4b-11ea-9edb-05a5b6d732ca.png">

Locally, it works perfectly fine.

**Comment by egamma** [comment]
Please file the issue against the python extension with a reproducable case.
