### ISSUE TITLE
Remote server unable to connect

### ISSUE THREAD

**Issue by 95th** [microsoft/vscode-remote-release#2119]
The remote server suddenly stops working. To get it back to work, I have to shutdown and restart the WSL VM.
![Annotation 2020-01-03 222911](https://user-images.githubusercontent.com/22871609/71736992-7ad5b300-2e78-11ea-913f-5c0dd0c805af.png)

- VSCode Version:
~$ code --version
1.41.1
26076a4de974ead31f97692a0d32f90d735645c0
x64

- Local OS Version: Windows 10 Version 10.0.19536 Build 19536
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: WSL 

Steps to Reproduce:

1. Try to open any remote directory.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode-remote-release/issues/2060

It's a WSL2 issue.
I just released a new version of the extension: `0.42.1` that should work around the issue. It requires VSCode Insiders (1.42.0). It would be great if you can give it a try. If it works I can also make a version for the stable VSCode (1.41.1)

**Comment by 95th** [comment]
@aeschli Thank you. I'll try that today and let you know.

**Comment by 95th** [comment]
Hi. The fix seems to be working. Connection hasn't died for some time now.
