### ISSUE TITLE
[WSL] File search is unreliable in remote workspaces

### ISSUE THREAD

**Issue by davidbailey00** [microsoft/vscode-remote-release#212]
- VSCode Version: 1.34.0-insider
- Local OS Version: Windows 10 1903 (10.0.18362.86)
- Remote OS Version: Ubuntu 18.04.2
- Remote Extension/Connection Type: WSL

**Steps to Reproduce:**

1. Press `CTRL`+`P`
2. Attempt a fuzzy search. For example, to find the file `e2e-tests/path-prefix/package.json`, type the following: `e2e/path/package`

**Expected result:**

The file `e2e-tests/path-prefix/package.json` is found

**Does this issue occur when you try this locally?**
No (works fine on Windows 10 natively and Ubuntu 19.04 natively, using the same Code version)

**Does this issue occur when you try this locally and all extensions are disabled?**
No (as above)

**Other notes:**

Using the Remote plugin with WSL, this doesn't seem to work even when typing out the full path, i.e. `e2e-tests/path-prefix/package.json`. However, oddly, when just typing `e2e-tests`, the file is shown in the list. As soon as I type `/` after `e2e-tests`, all the results are gone, so it seems to potentially be an error in handling of the slash character.

**Comment by roblourens** [comment]
I think you are right about the `/`, this is probably the same as https://github.com/microsoft/vscode/issues/73331
