### ISSUE TITLE
Extention enabled on SSH: and disabled locally

### ISSUE THREAD

**Issue by daravi** [microsoft/vscode-remote-release#2120]
Issue Type: <b>Bug</b>

There is an info icon (letter 'i' in a circle), for my extensions while connected over ssh with the tooltip:
"Extention enabled on SSH:... and disabled locally"

However the extensions are enabled both locally and remotely.

Extension version: 0.48.0
VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:57:35.999Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.18.0-80.11.2.el8_0.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (3.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: linux|
|OS|Linux x64 4.18.0-80.11.2.el8_0.x86_64|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (4 x 3600)|
|Memory (System)|7.63GB (5.64GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
> However the extensions are enabled both locally and remotely.

Can you explain the problem some more? Extensions can only be enabled in one place. So that doesn't mean that _you_ have disabled the extension locally, just that it is disabled because it is running remotely.

**Comment by daravi** [comment]
@roblourens Then the issue can be closed. I thought it means that in local scope the extension is disabled regardless of currently being connected to remote host.
