### ISSUE TITLE
vscood with wsl can not rename filename

### ISSUE THREAD

**Issue by cheukswiss** [microsoft/vscode-remote-release#2121]
Issue Type: <b>Bug</b>

vscod-wsl file permission problem: file already opened in vscode, cannot modify file name
E.g:
1.wsl: $ mv [ole_filename] [new_filename] ------- Permission denied
2. Using F2 rename and set a newname enter in the explorer in vscode, the file name cannot be changed

Extension version: 0.41.6
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

**Comment by aeschli** [comment]
What you see is very likely https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace

Please try `"remote.WSL.fileWatcher.polling": true"`
