### ISSUE TITLE
Failed to download & extract vscode-server

### ISSUE THREAD

**Issue by geekox86** [microsoft/vscode-remote-release#2124]
- VSCode Version: 1.42.0-insider
- Local OS Version: macOS Catalina 10.15.2
- Remote OS Version: Windows Server 2016
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to server through Remote Development extension
2. Download fail!

I am getting the following error while trying to connect from my Mac to Windows Server 2016 (with OpenSSH v8.1.0.0p1-Beta). Any clue on how to solve this?

```
Failed to download & extract vscode-server. - The underlying connection was closed: An unexpected error occurred on a send.
[07:47:20.552] > Looking for existing server in C:\Users\Administrator\.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729
[07:47:20.558] > Downloading VS Code Server
[07:47:24.066] > Failed to download & extract vscode-server. - The underlying connection was closed: An unexpected error occurred on a send.
> e83e985ee2f7##25##
[07:47:24.403] "install" terminal command done
[07:47:24.404] Install terminal quit with output: e83e985ee2f7##25##
[07:47:24.404] Received install output: e83e985ee2f7##25##
[07:47:24.404] Server download failed
[07:47:24.404] Resolver error: Downloading VS Code Server failed. Please try again later.
[07:47:24.407] ------
```

I am using VS Code Insider:
```
Version: 1.42.0-insider
Commit: 7c0095ee2d064033fc13184127a9adc603454729
Date: 2019-12-20T07:55:38.353Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
```

Extensions:
```
Remote Development 0.19.0
Remote - SSH 0.48.0
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by geekox86** [comment]
@aeschli BTW, I have configured the firewall inbound rule correctly for TCP port 22.

Yesterday, I was able to connect to Windows 10, but not to Windows Server 2016. I also get an error message after connection is established with Windows 10 saying "Terminal was terminated with code 1".

**Comment by roblourens** [comment]
You are the not the first one to report this error, but unfortunately, I have no idea what it means.

**Comment by geekox86** [comment]
@roblourens How can I help to provide more info?

**Comment by geekox86** [comment]
@roblourens So, is this a confirmed bug now?

**Comment by roblourens** [comment]
I have not been able to reproduce this and I am not sure what to ask right now. Windows support is a bit rough and "experimental" right now but I will have to dig in. Maybe some outbound firewall rule on the windows side, or security limitation in powershell? I'll set up a Windows Server machine later to test.

**Comment by geekox86** [comment]
Great, thank you for your excellent efforts.

**Comment by suzuryo3893** [comment]
I met the situation like yours.
My vscode on Windows10 could download the file but not install server successfully.

In my case, https://github.com/microsoft/vscode-remote-release/issues/15#issuecomment-489969139 helped me. This is a solution for now.
It is not clear but I guess firewalls or virus security apps disturb downloading & installing process, as roblourens mentions.

**Comment by roblourens** [comment]
I think this was fixed in https://github.com/microsoft/vscode-remote-release/issues/2261. Will be fixed in the nightly build currently.
