### ISSUE TITLE
Code . (no longer working) 

### ISSUE THREAD

**Issue by gg-mg** [microsoft/vscode-remote-release#2125]
Type code . in the terminal. When doing this for the first time, you should see VS Code fetching components needed to run in WSL. This should only take a short while, and is only needed once.

I have been using code . to open terminal but my ubuntu command line interface no longer recognizes it. I am getting this feedback

Command 'code' not found, did you mean:
  command 'cdde' from deb cdde
  command 'node' from deb nodejs
  command 'tcode' from deb emboss
  command 'cde' from deb cde
  command 'ode' from deb plotutils
  command 'cobe' from deb python-cobe
Try: sudo apt install <deb name>

What's the remedy?

Please reach me on ggichuki@yahoo.com with the solution.

**Comment by aeschli** [comment]
How it works is that WSL inherits the Windows PATH which has VSCode on the path.
Please make sure that's the case.
- run `env | grep PATH` on the WSL side.
- maybe reinstall code on the Windows side and make sure you allow the installer to add VSCode to the path

**Comment by gregorywaynepower** [comment]
Hey @aeschli,

I noticed that the "code" command working on the WSL side (including my WSL Terminal), however, it does work in Windows Terminal. Here is my output from `env | grep PATH`.

`env | grep PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Intel/iCLS Client:/mnt/c/Program Files/Intel/iCLS Client:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Program Files/dotnet:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/mnt/c/Program Files/nodejs:/mnt/c/Program Files (x86)/Microsoft Visual Studio/Shared/Python37_64:/mnt/c/Program Files (x86)/Microsoft Visual Studio/Shared/Python37_64/Scripts:/mnt/c/Users/SEM/AppData/Local/Programs/Python/Python36-32:/mnt/c/Users/SEM/AppData/Local/Programs/Python/Python36-32/Scripts:/mnt/c/Users/SEM/Anaconda3:/mnt/c/Users/SEM/Anaconda3/Scripts:/mnt/c/Users/SEM/AppData/Roaming/Python/Python37/Scripts:/mnt/c/Program Files/WindowsApps/Microsoft.WindowsTerminal_0.7.3451.0_x64__8wekyb3d8bbwe:/mnt/c/Program Files (x86)/Intel/iCLS Client:/mnt/c/Program Files/Intel/iCLS Client:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Program Files/dotnet:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/mnt/c/Users/SEM/AppData/Local/Programs/Microsoft VS Code`

As we can see `/mnt/c/Users/SEM/AppData/Local/Programs/Microsoft VS Code` is in the PATH, which should allow me to use the "code" command.

**Comment by aeschli** [comment]
It has to be `/mnt/c/Users/SEM/AppData/Local/Programs/Microsoft VS Code/bin`...

**Comment by gregorywaynepower** [comment]
Thank you for the help!

**Comment by gg-mg** [comment]
None of this has sorted my problems as yet.
These are the steps.
I  installed Visual Studio 2019(community).
On WSL, (code .) does not pop the Visual Studio ...I didn't use the brackets on WSL, its for emphasis.
On running /mnt/c/Users/ggich/AppData/Local/Programs/Microsoft VS Code/bin on WSL, the feedback is -bash: /mnt/c/Users/ggich/AppData/Local/Programs/Microsoft: No such file or directory.
On running env | grep PATH, the feedback is
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2019.522.0_x64__79rhkp1fndgsc:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Java/jdk1.8.0_231/bin:/mnt/c/Users/ggich/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/ggich/AppData/Local/GitHubDesktop/bin:/mnt/c/php-7.4.1-nts-Win32-vc15-x64:/mnt/c/xampp/php/windowsXamppPhp:/snap/bin

I do not see any Miscrosoft VS Code path

**Comment by rs-13-11** [comment]
i ran 

env | grep PATH

got following result :

/home/rslinux/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/oracle_jdk13/bin:/opt/maven/bin:/usr/lib/aws-cli/v2/2.0.0/bin:/mnt/c/dev_tools/VSCode/bin:/home/rslinux/.local/bin


I have /mnt/c/dev_tools/VSCode/bin in my path still when i run code . on wsl side it doesn't launch vscode.

Is it madatory to have it in program files ??


another thing 
when i installed wsl2 i chose to do it using 

Install On server option 
https://docs.microsoft.com/en-us/windows/wsl/install-on-server

**Comment by aeschli** [comment]
No it doesn't have to be in `Program Files`. The `bin` folder needs to be on the PATH and it contains a shell script called `code` (no file extension). `which code` should ind it. Maybe also check the executable bit. But normally that's set when you use the VSCode installer on windows to install VSCode.

We haven't tested the `Remote - WSL` extension with WSL on Windows Server, so that could be it.

What does `uname -r` return when called in a WSL shell?

**Comment by rs-13-11** [comment]
> No it doesn't have to be in `Program Files`. The `bin` folder needs to be on the PATH and it contains a shell script called `code` (no file extension). `which code` should find it. Maybe also check the executable bit. But normally that's set when you use the VSCode installer on windows to install VSCode.
> 
> We haven't tested the `Remote - WSL` extension with WSL on Windows Server, so that could be it.
> 
> What does `uname -r` return when called in a WSL shell?

Apologies for coming back late on this , here is what is the kernel version is 

"4.19.84-microsoft-standard"

**Comment by aeschli** [comment]
@rs-13-11  `appendWindowsPath=false` explains while the the WSL path does not contain the VSCode bin folder.
@gg-mg The WSL path looks strange, especially the segment with `CanonicalGroupLimited`. I would edit the PATH on the Window side and clean it out and make sure that the VSCode bin folder is on it.
