### ISSUE TITLE
Cannot start VScode with WSL

### ISSUE THREAD

**Issue by mukerong** [microsoft/vscode-remote-release#2134]
Hello,

I have read the [instruction](https://code.visualstudio.com/docs/remote/wsl) to try to open VScode in WSL terminal. However, if I type `code .` it will return this:

![image](https://user-images.githubusercontent.com/23180334/71923620-41d06380-3142-11ea-8901-75ec085c9928.png)

I have re-installed VSCode to make sure it has been added to PATH. If I open VSCode through VSCode WSL terminal, it will work:

![image](https://user-images.githubusercontent.com/23180334/71923691-70e6d500-3142-11ea-91a6-c21505b45f1c.png)

I have Windows 10 with Ubuntu 18.04 LTS. I also installed zsh and oh-my-zsh.

Is there a way to open VSCode in WSL with 1code`?

Thanks,
Rachel

**Comment by aeschli** [comment]
@mukerong What Windows 10 build are you using?

**Comment by mukerong** [comment]
Here is the system detail:

![image](https://user-images.githubusercontent.com/23180334/71998577-bfed4280-31f4-11ea-8048-d1eb2b35150a.png)

**Comment by aeschli** [comment]
@mukerong Thanks, yes, that explains it. You're on a quite old Windows build and WSL that has shipped with it has the pipe issue that have been 'fixed' in the meantime. Any chance you can update your Windows build?

**Comment by mukerong** [comment]
@aeschli 

This is a computer computer so probably not. I didn't realize old build can cause issues like this. I can use alias for now for a workaround before I can update my Windows build.

Thank you!

**Comment by mukerong** [comment]
@aeschli 

When I work on it more, I noticed the `alias` workaround doesn't really help. I did the following:

![image](https://user-images.githubusercontent.com/23180334/72635055-c2484e80-3910-11ea-8e76-28d4eba78b39.png)

After execute this alias, VSCode will be opened under **Windows System** not **WSL**. Is there a way to make the alias work?

**Comment by aeschli** [comment]
To directly open a remote window you need to add `--remote=wsl=Ubuntu --folder-uri=/home/your/folder/in/wsl`

**Comment by tanhakabir** [comment]
@mukerong are you still seeing this issue?

**Comment by mukerong** [comment]
@tanhakabir, It still doesn't work, but I found a workaround. I think we can close it for now.
