### ISSUE TITLE
SSH config comments are parsed and displayed as hosts

### ISSUE THREAD

**Issue by Kyle-sandeman-mrdfood** [microsoft/vscode-remote-release#2135]
- Version: 1.41.1
- Commit: 26076a4de974ead31f97692a0d32f90d735645c0
- Date: 2019-12-18T14:57:51.166Z
- Electron: 6.1.5
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Darwin x64 19.2.0  (OSX 10.15.2)
- Remote OS Version: N/A
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Add a comment after the end of a Host entry in .ssh/config
2. Open list of hosts to connect to via bottom left remote button
 
![image](https://user-images.githubusercontent.com/48314306/71962125-79521500-3201-11ea-8952-dc733a49c06d.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes (assumed. Remote is the only extension I have regarding ssh)

**Comment by roblourens** [comment]
This is actually correct, surprisingly enough. If you use `ssh identity` in an external terminal, it will try to connect using that config.
