### ISSUE TITLE
ECONNREFUSED connecting to WSL

### ISSUE THREAD

**Issue by Menci** [microsoft/vscode-remote-release#2136]
Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19536

- Remote OS Version: WSL 2
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Open a WSL workspace

![image](https://user-images.githubusercontent.com/11341955/71979504-d6c58080-3258-11ea-922f-d84f7de1398f.png)

In WSL:

```bash
$ sudo ss -tl
State             Recv-Q            Send-Q                         Local Address:Port                                Peer Address:Port            Process            
LISTEN            0                 128                                  0.0.0.0:vcom-tunnel                              0.0.0.0:*                                  
LISTEN            0                 128                                  0.0.0.0:http                                     0.0.0.0:*                                  
LISTEN            0                 128                                  0.0.0.0:rsh-spx                                  0.0.0.0:*                                  
LISTEN            0                 128                                        *:34787                                          *:*                                  
LISTEN            0                 128                                        *:45469                                          *:*                                  
LISTEN            0                 128                                     [::]:rsh-spx                                     [::]:*             
```

In Windows, I can connect to WSL:

```
C:\Users\Menci>curl 172.29.81.64:34787 -v
* Rebuilt URL to: 172.29.81.64:34787/
*   Trying 172.29.81.64...
* TCP_NODELAY set
* Connected to 172.29.81.64 (172.29.81.64) port 34787 (#0)
> GET / HTTP/1.1
> Host: 172.29.81.64:34787
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: text/plain
< Date: Wed, 08 Jan 2020 12:53:26 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
<
Not found* Connection #0 to host 172.29.81.64 left intact
```

Windows Firewall turned off.

Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Are you on the latest version of the Remote - WSL extension? (0.41.7)

**Comment by Menci** [comment]
Yes. And I can't reproduce it. I don't know why it's attempting to connect to an IPv6 address `::1`. I'm using WSL 2 and doesn't have IPv6 connection in WSL.

**Comment by aeschli** [comment]
Can you attach the WSL log (`Remote - WSL: Show log...`)?
With (0.41.7), we try first to connect to the WSL2's IP. If that fails we use localhost (IPV6).

Both should work but Windows Build 19536 has a known issue with localhost.
