### ISSUE TITLE
Attach Visual Studio Code from Docker containers treeview can use wrong container name

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-remote-release#2140]
The Remote Containers extension attaches the "Attach Visual Studio Code" command to container treeview nodes of the Docker ([`vscode-docker`](https://github.com/microsoft/vscode-docker)) extension.  When executed, the command uses a data object from that node (`containerDesc`) to obtain information about that container (a raw object ultimately provided by Docker).  In particular, it uses the first element of the `Name` array to obtain the name of the container, which it then uses further on in its implementation.

However, there are scenarios where containers can be "linked" by name, where a container technically has several names, a "canonical" name and the linked names.  In those scenarios, the `Name` array will contain *all* of the names, in a non-deterministic order.  Therefore, blindly choosing the first element of the array can result in using the linked name, which can then cause Docker operations to fail.  The solution is to look for and choose the canonical name from that list; the canonical name will be the one that does *not* contain a '/' character aside from the prefix.  (It's probably safest, in general, to refer to a container by ID rather than name when possible.)

This issue is related to [vscode-docker#1523](https://github.com/microsoft/vscode-docker/issues/1523).

**Comment by egamma** [comment]
@chrmarti fyi I've submitted a PR.

**Comment by diablodale** [comment]
Hi. @egamma would you please cross-reference the PR so it and this issue are linked?

**Comment by chrmarti** [comment]
@diablodale The PR is linked, but it's in a private repo (which is why you don't see it).

**Comment by chrmarti** [comment]
@philliphoff Thanks for passing this along!

**Comment by dbaeumer** [comment]
@chrmarti any steps?

**Comment by chrmarti** [comment]
No, I just replicated the suggested fix from the Docker extension. I suggest to verify by code inspection unless @philliphoff knows an easy way to reproduce.

**Comment by philliphoff** [comment]
@chrmarti @dbaeumer Easy?  Unfortunately, no.  The ordering of the names is non-deterministic so I was only able to reproduce the scenario exactly once (prior to my fix, but not afterwards).  I've just got my fingers crossed that it resolves the issue (and a couple of unit tests).

**Comment by alexr00** [comment]
Verified by code inspection. There are no places where ContainerInfo.Names is used on it's own now.
