### ISSUE TITLE
DOCKER_HOST not used for viewing containers

### ISSUE THREAD

**Issue by marcpawl** [microsoft/vscode-remote-release#2142]
Version: 1.42.0-insider
Commit: cba31b819ea99836daf51cee56299348e9c6d20b
Date: 2020-01-08T05:35:29.477Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0

What I would like to see is some messages that will make the debugging of the install easier.  Why is the step not progressing, after a few minutes I would like to see an error message giving clues.
e.g. Unable to connect to docker port, or command docker ps did not return in a timely manner.

Steps to Reproduce:

1.  Create ssh keys and verify that ssh works without password
2. In .bashrc setup DOCKER_HOST environment variable
basement:~ marcpawl$ echo $DOCKER_HOST
ssh://marcpawl@dcrdev
3. Reboot 
4. docker ps -a
Connects to remote host and shows 1 active container and 1 exited container.
5. From bash prompt, start code
6. Select Remote Explorer
7. explore "Containers"
progress scroll keeps going forever, but no results occur
8. View Terminal
basement:~ marcpawl$ echo $DOCKER_HOST
ssh://mpawlowsky@dcrdev
basement:~ marcpawl$

**Comment by ibalajiarun** [comment]
I am running into the same issue as well. I have set the docker.host setting as mentioned here: https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host and used a devcontainer.js file. Below is the terminal log I get:

```
[0 ms] Start: Resolving remote
[2 ms] Setting up container for folder or workspace: /Users/balaji/workplace/devcontainers/sgx-threshsign

[14 ms] Start: Check Docker is running
```
and its struck here.

**Comment by ibalajiarun** [comment]
I have since figured it was a problem with the hostname. I used the host alias from .ssh/config but vscode couldn't resolve it.

**Comment by chrmarti** [comment]
Tracking as upstream: https://github.com/apocas/docker-modem/issues/113

**Comment by chrmarti** [comment]
@marcpawl You could add the private key to your ssh-agent as a workaround.

**Comment by chrmarti** [comment]
This should work now that we have moved off Dockerode.
