### ISSUE TITLE
Lost intellisense

### ISSUE THREAD

**Issue by rajesh-chawla** [microsoft/vscode-remote-release#2146]
Unfortunately, I've lost intellisense when I code in the container. How can I go about troubleshooting this? So far, I've tried reopening the container as well as rebuilding it.

Any pointers would be appreciated.

**Comment by deinman** [comment]
Yes, I've seen this on both machines I've run it on here. Here's the logs including the complete container rebuild:

[20200110_devContainerLogs.txt](https://github.com/microsoft/vscode-remote-release/files/4045821/20200110_devContainerLogs.txt)

Looking at the log it looks to be an issue with my network's HTTPS cert injection causing the container to not be able to get the local issuer cert. 

Line 292: `unable to get local issuer certificate`

Is there maybe a flag that I could set somewhere to allow insecure certs?

**Comment by Chuxel** [comment]
//cc: @chrmarti  Any idea why this would be happening on container create but not via the UI?  It's the same acquisition code path, correct?

**Comment by chrmarti** [comment]
I think there is a fallback when going through the UI that will use the Chromium network stack on the UI-side to get the extension when getting it on the remote side failed. /cc @sandy081

**Comment by chrmarti** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/986
