### ISSUE TITLE
Allow remote docker daemon's host environment variables in devcontainer.json mount commands

### ISSUE THREAD

**Issue by yamlCase** [microsoft/vscode-remote-release#2147]
My scenario: 
1. Windows 10 is running VS Code
2. I have %DOCKER_HOST% set to a remote linux machine.

This works well, *except* I have to hard-code a volume mount path in devcontainer.json.  How can I use the remote host's environment variables?

for example: I'd like an environment variable like `WSPATH="${HOME}/workspaces"` and be able to use it in the workspaceMount parameter like so:

`"workspaceMount": "source=${WSPATH}/thisproject=/workspace,type=bind,consistency=cached"`

Reason:
I'm trying to write my devcontainer.json and Dockerfile as generic as possible without hard coding paths for better distribution cleanliness.

**Comment by chrmarti** [comment]
I'm not sure there is a way for us to lookup the remote Docker host's environment variables. DOCKER_HOST probably points to a TCP port and that's all we have to get to the remote machine.

If DOCKER_HOST is set to an `ssh://` URL, we could try to open an shell session, but that would come with a performance hit (although we would only do that when the devcontainer.json uses environment variables from the Docker daemon).

**Comment by yamlCase** [comment]
Yes, I'm using ssh:// for the remote host.  But I don't think opening a session first to get envs, then opening another session for the actual docker work it the cleanest path.  

Could we use a new sigil to indicate "don't expand this var locally, pass this '${something}' as a string to the remote host"

Docker daemon would of course have to be able to take in the environment var and do it's own expansion.

**Comment by chrmarti** [comment]
I agree, although that means that this is outside of the scope of this extension.

**Comment by chrmarti** [comment]
Closing as out-of-scope because this would require support on the Docker daemon's side too.
