### ISSUE TITLE
Please reopen 50417

### ISSUE THREAD

**Issue by rbtcollins** [microsoft/vscode-remote-release#2148]
I believe it still happens per the bug I opened, misguidedly, on npm - https://github.com/nodejs/node/issues/31269

microsoft/vscode#50417

**Comment by aeschli** [comment]
I suspect you are seeing https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace

Can you try `"remote.WSL.fileWatcher.polling":  true" in the settings, close VSCode, wait a few seconds before restarting and see if this solves the issue?

**Comment by rbtcollins** [comment]
Indeed that did stop the interaction with node thank you.

**Comment by rbtcollins** [comment]
Though I do have a puzzling question, which is why, since I excluded node_modules, in watcher excludes, this shows up and needed the workaround : which is why I was asking for 50417 to be reopened :). 

![image](https://user-images.githubusercontent.com/499678/72187808-8b2ff400-345d-11ea-90f8-e7563a21e699.png)

**Comment by aeschli** [comment]
I think what happens is that with watcher filter `**/node_modules/*/**`, the subfolders of `node_modules` still gets a watcher. Can you change it to  `**/node_modules/**`?

Please add comments to microsoft/vscode#50417 if you want that to be opened (or open a new issue with self contained description and reproducible steps)

**Comment by alexpaluzzi** [comment]
I am also now experiencing this issue with WSL. I cannot add comments to #50417 because it is locked.

**Comment by aeschli** [comment]
Please open a new issue with a full description what you see.

**Comment by rbtcollins** [comment]
@aeschli  sorry for the delay, was at conference actually using the repo and all. 

With the node modules pattern set to `**/node_modules/**` in *all* three config locations, and polling disabled ( I think? --fileWatcherPolling=0 is on the server command line), the error I was suffering is not reproducible.

Where is the node modules pattern coming from, so I can file a bug there, as your suspicion appears to be correct.

**Comment by aeschli** [comment]
The pattern comes from the VSCode defaults. It's set like that on purpose, so that you can expand `node_modules` one level and see the latest list of installed modules.
Obviously, for WSL this isn't the best.
I'm kind of tempted to solve that by setting polling the default in WSL1.

**Comment by aeschli** [comment]
No action planed
