### ISSUE TITLE
postCreateCommand is not executing on a remote container

### ISSUE THREAD

**Issue by Vaelek** [microsoft/vscode-remote-release#2150]
- VSCode Version: 1.41.1
- Local OS Version: Windows 10 1903 Build 18362.535
- Remote OS Version: python:3.7.4-stretch development container running on CentOS 7.7.1908 host
- Remote Extension/Connection Type: Remote docker dev container over SSH tunnel

Steps to Reproduce:

1. Launch the remote dev container
2. postCreateCommand never runs
3. Look in ~/.vscode-server/data/Machine and see .postCreateCommandMarker is there
4. Delete .postCreateCommandMarker
5. Reload window
6. .postCreateCommandMarker is recreated and still nothing executes

In the dev container startup log, I see the following
`Run: docker exec 5d9e5621c153f011d7a026a12fcdfe78243458a82ef8ddb8d5785f14cccf80ae /bin/sh -c set -o noclobber ; mkdir -p '/home/vscode/.vscode-server/data/Machine' && { > '/home/vscode/.vscode-server/data/Machine/.postCreateCommandMarker' ; } 2> /dev/null`

`Run: docker exec 5d9e5621c153f011d7a026a12fcdfe78243458a82ef8ddb8d5785f14cccf80ae test -f /home/vscode/.vscode-server/.postCreateCommandMarker`

The first line causes .postCreateCommandMarker to be created, before it is tested

Does this issue occur when you try this locally?: Yes

When running in a local dev container, there is the addition of an identical line that creates .installExtensionsMarker, with no previous or subsequent test for its existence. Extensions are not installed automatically either in both cases.

**Comment by chrmarti** [comment]
Note that there are two paths: One under `.vscode-server/data/Machine` and one under `.vscode-server/.postCreateCommandMarker`. Maybe the second still exists? (The second one is an old path we should remove now.)
