### ISSUE TITLE
Wrong user name when connect to ipv6 server in windows

### ISSUE THREAD

**Issue by jiangyangzhou** [microsoft/vscode-remote-release#2151]
- VSCode Version: 1.42.0 insider
- Local OS Version: Windows 10 18362.295
- Remote OS Version: Ubuntu 16.04.2
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. open Remote-SSH connect to host
2. tap username@20xx:xxxx:xxxx:xxxx...(ipv6)
3. Connect  
And I got:
![image](https://user-images.githubusercontent.com/26026602/72199264-93dff480-3474-11ea-9214-3b8a7fa4e19b.png)

This is a wrong username c76b is the postfix of ipv6 address.
(Ps: This Bug doesn't affect ssh connection, and I am happy to see Windows ipv6 connection problem fixed in insider version.)

**Comment by roblourens** [comment]
> This Bug doesn't affect ssh connection

Does that mean that if you type in the right password for your user, it still connects successfully?

Can you share the log from the Remote-SSH output channel?
