### ISSUE TITLE
devcontainer.json remoteEnv/containerEnv has no effect

### ISSUE THREAD

**Issue by fvanmaele** [microsoft/vscode-remote-release#2152]
- VSCode Version: 1.41.1 (system setup) / 1.42.0-insider (system setup)
- Local OS Version: Windows 10 Education 1809 17763.914
- Remote OS Version: Ubuntu 19.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Add a new value for PATH with `remoteEnv` or `containerEnv` as described in [Advanced Container Configuration](https://code.visualstudio.com/docs/remote/containers-advanced#_adding-environment-variables)
2. Rebuild container
3. Open folder in container
3. Run `echo $PATH` in Terminal window, notice that `PATH` remains at the old value

`devcontainer.json`
```
// For format details, see https://aka.ms/vscode-remote/devcontainer.json or the definition README at
// https://github.com/microsoft/vscode-dev-containers/tree/master/containers/docker-existing-dockerfile
{
	"name": "Existing Dockerfile",

	// Sets the run context to one level up instead of the .devcontainer folder.
	"context": "..",

	// Update the 'dockerFile' property if you aren't using the standard 'Dockerfile' filename.
	"dockerFile": "..\\Dockerfile",

	// Uncomment the next line to have VS Code connect as an existing non-root user in the container. 
	// On Linux, by default, the container user's UID/GID will be updated to match your local user. See
	// https://aka.ms/vscode-remote/containers/non-root for details on adding a non-root user if none exist.
	"remoteUser": "autograder",

	// Set variables that apply to VS Code and related subprocesses
	"remoteEnv": {
		"PATH": "/home/autograder/.local/bin/:${containerEnv:PATH}"
	},

	// Uncomment the next line if you will use a ptrace-based debugger like C++, Go, and Rust
	// "runArgs": [ "--cap-add=SYS_PTRACE", "--security-opt", "seccomp=unconfined" ],

	// Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-in-docker for details.
	// "mounts": [ "source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind" ],

	// Use 'settings' to set *default* container specific settings.json values on container create. 
	// You can edit these settings after create using File > Preferences > Settings > Remote.
	"settings": { 
		// This will ignore your local shell user setting for Linux since shells like zsh are typically 
		// not in base container images. You can also update this to an specific shell to ensure VS Code 
		// uses the right one for terminals and tasks. For example, /bin/bash (or /bin/ash for Alpine).
		"terminal.integrated.shell.linux": null
	},

	// Use 'appPort' to create a container with published ports. If the port isn't working, be sure
	// your server accepts connections from all interfaces (0.0.0.0 or '*'), not just localhost.
	// "appPort": [],

	// Uncomment the next line to run commands after the container is created - for example installing git.
	// "postCreateCommand": "apt-get update && apt-get install -y git",

	// Add the IDs of extensions you want installed when the container is created in the array below.
	"extensions": []
}
```
`Dockerfile`
```
FROM ubuntu:19.04

RUN apt-get update --fix-missing
RUN apt-get install -y gcc
RUN apt-get install -y make
RUN apt-get install -y build-essential
RUN apt-get install -y git convmv dos2unix diffutils cmake unzip rename
RUN ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime

# Install autodriver
WORKDIR /home
RUN useradd -m -s /bin/bash autograder
RUN mkdir -p autograder/.local/bin

# Debugging support
RUN apt-get install -y gdb libc6-dbg clang
RUN apt-get install -y parallel
```
Terminal output
```
autograder@934b19234a0b:/workspaces/IPI_WS19$ echo $PATH
/home/autograder/.vscode-server-insiders/bin/960cddb992cc96d47f56b633b361909f1b5b3353/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

Does this issue occur when you try this locally?: N/A (Issue is only applicable on the remote)
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by chrmarti** [comment]
@aeschli Are we overwriting PATH in the server?

**Comment by chrmarti** [comment]
The extension is passing the modified PATH via `extensionHostEnv` to VS Code. Other environment variables pass through that unaffected, but PATH seems to be lost along the way and the container's default then applies.

**Comment by roblourens** [comment]
For containers do you use the `--disable-user-env-probe` flag? If not yeah I see that we override the PATH after setting the extensionHostEnv value, with `let PATH = userShellEnv['PATH'] || processEnv['PATH'];`

I guess we would have to merge the extensionHostEnv PATH in at the front of this.

**Comment by chrmarti** [comment]
We use `--disable-user-env-probe`. (Not sure if that affects it, `extensionHostEnv` seems to be set only on the extension host side, but maybe I'm misreading the code? https://github.com/microsoft/vscode/blob/74733e1d3c09faf87a60c12f5d3bd7c65be48e03/src/vs/workbench/api/node/extHostExtensionService.ts#L97)

**Comment by chrmarti** [comment]
Fixing it as you suggest. 👍

**Comment by roblourens** [comment]
I think we need to merge the two, not replace PATH entirely. Are you using it to add something to PATH or do you actually want to replace it entirely?

**Comment by chrmarti** [comment]
In this case, the user wants to add to the PATH and can include to the original PATH.

Not sure what you mean by merging, could you explain?

**Comment by roblourens** [comment]
I mean setting it to `PATH1 + PATH2` but if the user "can include the original PATH" then I guess that is not a problem for your case.

**Comment by chrmarti** [comment]
It might be best to avoid merging two `PATH` values because they can overlap and the order of the entries matters - so two `PATH`s can contradict each other. (The order determines the lookup order for executables and the first match wins.)
