### ISSUE TITLE
WSL: File watcher excludes not working and tsserver fails to start

### ISSUE THREAD

**Issue by alexpaluzzi** [microsoft/vscode-remote-release#2155]
Version: 1.41.1 (user setup)
Commit: 26076a4
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

Open any .js or .ts file in my project
After opening and watching "Initializing js/ts server...". I verbose logging shows a whole mess of stuff, happy to put it all here if needed.
Some that stick out:

`[Trace - 19:30:30.496] Response received: updateOpen (2). Request took 137986 ms. Success: true`

This took over 2 minutes.

`[Trace - 19:30:31.120] Response received: getSupportedCodeFixes (3). Request took 138609 ms. `Success: true

This took another 2 minutes.

`[Trace - 19:30:37.291] Response received: configure (4). Request took 144779 ms. Success: true`

Again.

Then it just kind of hangs. I noticed when I try to force some intellisense (with ctrl+space) I see these errors:

```
[Error  - 19:35:46.867] ReaderError
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be an integer. Received NaN
	at Function.concat (buffer.js:449:5)
	at l.append (/home/alex/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/extensions/typescript-language-features/dist/extension.js:1:210613)
	at t.Reader.onLengthData (/home/alex/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/extensions/typescript-language-features/dist/extension.js:1:211680)
	at Socket.<anonymous> (/home/alex/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/extensions/typescript-language-features/dist/extension.js:1:211607)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

I tried reinstalling VS Code. I tried Insiders. All my extensions (except for WSL Remote) are disabled. Happy to help or get more information if needed.

Coincidentally, this pop-up also started at the same time. I have many `node_modules` folders in this project. I want to exclude them all.
![image](https://user-images.githubusercontent.com/1376892/72277276-a8042d00-35ff-11ea-9a13-ff29c9576ba6.png)

I have tried polling and tried playing with the exclusions settings.

**Comment by aeschli** [comment]
Toe get more information on what's going on can you:
- invoke `Developer: Set Log Level...`, select `Trace`
- close all VSCode windows, wait a few seconds
- open a remote window, open your project folder
- invoke `Developer: Show Log...`, select `Remote Server`

There you can see what the file watcher reports

**Comment by alexpaluzzi** [comment]
It definitely looks like the file watcher is watching the entire directory and ignoring my exclude globbing of `**/node_modules/**`. No matter what pattern I attempt, it looks like it watches the entire thing.

**Comment by aeschli** [comment]
Closing the issue. If you still see this please speak up.
