### ISSUE TITLE
Selecting the '+' icon in the SSH-Remote extension's 'Forwarded Ports' tree view fails to display an input dialogue

### ISSUE THREAD

**Issue by pd93** [microsoft/vscode-remote-release#2159]
Issue Type: <b>Bug</b>

Related to: https://github.com/microsoft/vscode-remote-release/issues/685

1. Install vscode insiders & the nightly Remote-SSH extension
2. Connect to a remote server using the Remote-SSH extension
3. Navigate to the 'Forwarded Ports' section of the SSH explorer
4. Click the '+' icon that appears on mouse hover (Forward a Port button)
5. The following error appears in the Developer Tools Console instead of a dialogue box popping up

```
 ERR TreeError [RemoteTunnels] Data tree node not found: [object Object]: Error: TreeError [RemoteTunnels] Data tree node not found: [object Object]
    at Y.getDataNode (file:///C:/Users/<user>/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1081:14)
    at Y.reveal (file:///C:/Users/<user>/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1080:577)
    at file:///C:/Users/<user>/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5000:720
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

Extension version: 2020.1.11041
VS Code version: Code - Insiders 1.42.0-insider (5e758c10c969d668730f036abfc557d9cfb62b87, 2020-01-13T09:52:21.788Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (24.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
Can you provide a screen shot of what the Forwarded Ports view looks like before you click the '+'? I tested on the b40e5ce729 insiders build and I'm not seeing any errors.

**Comment by pd93** [comment]
It looks as I'd expect it to. Just no button functionality.

![image](https://user-images.githubusercontent.com/9294862/72424231-8e88ef80-377d-11ea-8fe9-a7fc1dccb624.png)

No idea if either of these errors are related? They show up in the developer console when opening a remote target:

```
console.ts:137 [Extension Host] (node:11172) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:27:3))
```
```
t.log @ console.ts:137
abstractExtensionService.ts:396 Activating extension 'vscode.login' failed: Cannot find module '/home/pete/.vscode-server-insiders/bin/b40e5ce729ce49b7311e92f65f1f21c514aa9c2c/extensions/vscode-account/out/extension.js'
Require stack:
- /home/pete/.vscode-server-insiders/bin/b40e5ce729ce49b7311e92f65f1f21c514aa9c2c/out/vs/loader.js
- /home/pete/.vscode-server-insiders/bin/b40e5ce729ce49b7311e92f65f1f21c514aa9c2c/out/bootstrap-amd.js
- /home/pete/.vscode-server-insiders/bin/b40e5ce729ce49b7311e92f65f1f21c514aa9c2c/out/bootstrap-fork.js.
```

**Comment by alexr00** [comment]
Very weird, I'm still not able to get that error to happen. Have you done anything with the Forwarded Ports view before it happens (besides clicking the '+')? Does it still occur if you reload and then try?

**Comment by pd93** [comment]
Just tried this on my personal machine with a fresh install of Insiders and the nightly Remote SSH extension. Still having this issue.

Additionally, I've just noticed that VSCode only picks up the first `LocalForward` in my SSH config file. I have a few ports open using multiple `LocalForward` directives. Both ports are being forwarded fine, but VSCode's "Detected" section does not reflect this.

```
Host myhost
    HostName        x.x.x.x
    LocalForward    8000 127.0.0.1:8000
    LocalForward    1433 127.0.0.1:1433
```

**Comment by sguillia** [comment]
I also have this when opening an extension host

```
Activating extension 'vscode.login' failed: Cannot find module '/usr/share/code-insiders/resources/app/extensions/vscode-account/out/extension.js'
Require stack:
- /usr/share/code-insiders/resources/app/out/vs/loader.js
- /usr/share/code-insiders/resources/app/out/bootstrap-amd.js
- /usr/share/code-insiders/resources/app/out/bootstrap-fork.js.
```

**Comment by alexr00** [comment]
Got a repro and I'm looking into it

**Comment by alexr00** [comment]
Fix will be in the next insiders. Please let me know if it works for you!

**Comment by pd93** [comment]
@alexr00 Seems to be working for me now. Thanks!

![image](https://user-images.githubusercontent.com/9294862/72889235-1c795300-3d07-11ea-9f0b-43c983d5e955.png)

I've opened a separate issue for the multiple `LocalForward` directives mentioned above (see #2190)

**Comment by alexr00** [comment]
Verified by OP.
