### ISSUE TITLE
Hello/Hello for Business support, or password encryption for configs

### ISSUE THREAD

**Issue by ClairelyClaire** [microsoft/vscode-remote-release#2161]
[I posted this awhile ago](https://github.com/microsoft/vscode-remote-release/issues/1617) and completely forgot to come back to it.

My original feedback was:

It would be very useful if the SSH extension supported encrypting account passwords in the config file, or authentication using Hello/Hello for Business.

To clarify, I don't mean Hello or encryption as the SSH authentication mechanism, I mean encryption as in the text file that holds the SSH configs using encryption, so users can store their SSH passwords for faster login.

As of now, it's pretty tedious to have to retype a long, secure password every time I change directories once I've connected to a server. I'd rather save my password, but not if I have to save it in plaintext.

If the plugin could instead support _encrypted_ SSH configs with either something transparent or interactive, it would make managing sessions a lot easier on the user.

**Comment by roblourens** [comment]
Same answer - This extension doesn't implement any auth or encryption at all, and I don't plan on changing that.  It sounds like you basically want to auth with a private/public key pair, instructions for using that are here: https://code.visualstudio.com/docs/remote/troubleshooting#_configuring-key-based-authentication
