### ISSUE TITLE
Command failure on Remote SSH connection

### ISSUE THREAD

**Issue by timothybrooks** [microsoft/vscode-remote-release#2163]
Issue Type: <b>Bug</b>

When connecting to a remote server, I receive multiple error popups stating:

> The terminal process command '/bin/sh -c 'wget --version > /dev/null
> if [ $? -eq 0 ]
> then
> 	wget --connect-timeout=7 --dns-timeout=7 -q --header Metadata-Flavor:Google -O - http://metadata.google.internal/computeMetadata/v1/instance/id
> else
> 	curl --version > /dev/null
> 	if [ $? -eq 0 ]
> 	then
> 		curl --connect-timeout 7 -s --header Metadata-Flavor:Google http://metadata.google.internal/computeMetadata/v1/instance/id
> 	fi
> fi
> exit 0'' failed to launch (exit code: {2})

Note that I can SSH to the remote server on an external terminal without issue.

Extension version: 0.48.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.0.0
Remote OS version: Linux x64 4.15.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: em1.ist.berkeley.edu|
|OS|Linux x64 4.15.0-72-generic|
|CPUs|Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz (56 x 2200)|
|Memory (System)|502.57GB (16.67GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Hm, are you still connected successfully after that happens? Like can you open a new terminal and run commands?
