### ISSUE TITLE
ECONNREFUSED when extensions need Internet access

### ISSUE THREAD

**Issue by enozero** [microsoft/vscode-remote-release#2166]
Issue Type: <b>Bug</b>

In several extensions (Kubernetes, Terraform, Java) when I'm inside a remote container, they are trying to download from the Internet. All the connections fail with ECONNREFUSED 127.0.0.1:9000. I'm not quite sure when I started seeing this happen.

If I bring up a terminal inside the container through VS Code, I can issue cURL commands to the Internet sites and those succeed.

Extension version: 0.94.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.9.184-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_159783|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: WMX Cloud|
|OS|Linux x64 4.9.184-linuxkit|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (6 x 2300)|
|Memory (System)|5.82GB (0.79GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Did you set a proxy in the VS Code settings?

**Comment by enozero** [comment]
Ugh... there's one that's set at the system level... Thanks!
