### ISSUE TITLE
download extension timeout + tricking vscode remote into thinking it is installed

### ISSUE THREAD

**Issue by Noezor** [microsoft/vscode-remote-release#2167]
- VSCode Version: 1.42.0-insider
- Local OS Version: Ubuntu 18.04.3 LTS
- Remote OS Version:CentOS Linux release 7.7.1908
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

I'm ssh'ing to a machine on my entreprise network which is connected to a proxy. The proxy seems setup properly. I'm using up to date Remote extensions.

1. Connect to SSH host
2. Download extension written under "Install in SSH: servername"
3. Wait for timeout

Console log (Remote Server with trace) :

> [2020-01-16 12:48:31.526] [remoteagent] [info] Installing extension: davidanson.vscode-markdownlint
> [2020-01-16 12:52:46.118] [remoteagent] [error] Failed to install extension: davidanson.vscode-markdownlint connect ETIMEDOUT 13.107.6.175:443
> [2020-01-16 12:52:46.642] [remoteagent] [info] Installing the extension: davidanson.vscode-markdownlint
> [2020-01-16 12:54:54.023] [remoteagent] [info] Extracted extension to /home/npion/.vscode-server-insiders/extensions/.davidanson.vscode-markdownlint-0.33.0: davidanson.vscode-markdownlint
> [2020-01-16 12:54:54.024] [remoteagent] [info] Renamed to /home/npion/.vscode-server-insiders/extensions/davidanson.vscode-markdownlint-0.33.0
> [2020-01-16 12:54:54.028] [remoteagent] [info] Installation completed. davidanson.vscode-markdownlint
> [2020-01-16 12:54:54.032] [remoteagent] [info] Successfully installed the extension: davidanson.vscode-markdownlint

Then, VSCode asks for reload to finish installation. After reloading, it indicates "Extension is enabled on 'SSH:servername' but is disabled locally" even though it is not the case.

![bug-vscode](https://user-images.githubusercontent.com/8218350/72526790-7db4a880-3867-11ea-874b-17c1159c7a5c.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

So I think there are 2 things on this issue. My problem + what seems like a bug. I'd guess VSCode is tricked into believing the extension was successfully downloaded because of an existing directory from the previous failed installation. It's also not quite clear why the logs report "Installing the extension" twice.

**Comment by roblourens** [comment]
Are you sure it's not actually installed? It looks like it timed out once then successfully installed.

**Comment by Noezor** [comment]
Every download times out once and then gets "succesfully installed" then. Also, if I launch a VSCode locally, it does not tell me any extension is disabled and I can use normally.

Do you know how I could troubleshoot if it is not properly installed or if it's that VSCode is improperly classifying extension as not enabled locally ?

**Comment by Noezor** [comment]
Ok interestingly enough it seems that the Python Extension has been detected on remote after rebooting. It still shows as not activated locally even though it is. (same for other extensions). I don't see any debilitating bug though. Should we close ?

**Comment by roblourens** [comment]
If it's installed on the remote, it won't be used on the local machine (because it's being used on the remote) so maybe you are just misinterpreting the UI? If the extension works, I think you're good :)
