### ISSUE TITLE
Locale issue in dev containers

### ISSUE THREAD

**Issue by zlliang** [microsoft/vscode-remote-release#2169]
- VSCode Version: 1.41.1
- Local OS Version: macOS Catalina 10.15.2
- Remote OS Version: Debian 10.2
- Remote Extension/Connection Type: Docker

I find a locale issue appears when using the integrated terminal in a dev container. Here are steps to reproduce:
1. Create a dev container via the following `.devcontainer/devcontainer.json`:

   ```json
   {
     "name": "demo",
     "image": "debian"
   }
   ```

   This container uses the official `debian:latest` image.
2. Reopen in the dev container.
3. Open the integrated terminal and run `perl`, and the locale-related warnings appear:

   ```bash
   root@10ae756f49d8:/workspaces/demo# perl
   perl: warning: Setting locale failed.
   perl: warning: Please check that your locale settings:
           LANGUAGE = (unset),
           LC_ALL = (unset),
           LANG = "en_US.UTF-8"
       are supported and installed on your system.
   perl: warning: Falling back to the standard locale ("C").
   ```

4. However, running the dev container in `Terminal.app` and the local integrated terminal does not cause the warnings:

   ```bash
   > docker exec -it 10ae756f49d8 bash
   root@10ae756f49d8:/# perl
   ```
   No warning here.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
You can turn off locale detection in VS Code's settings to avoid having LANG set in the integrated terminal:
![image](https://user-images.githubusercontent.com/9205389/72711331-19486080-3b69-11ea-9840-3be72b2c41c3.png)

**Comment by zlliang** [comment]
Thanks a lot!
