### ISSUE TITLE
Easy way to disconnect

### ISSUE THREAD

**Issue by mseare** [microsoft/vscode-remote-release#217]
Issue Type: <b>Feature Request</b>

Love the Remote - SSH extension!  How do I easily and safely disconnect from the remote host?

Extension version: 0.35.0
VS Code version: Code - Insiders 1.34.0-insider (daf71423252a707b8e396e8afa8102b717f8213b, 2019-05-06T22:07:35.830Z)
OS version: Darwin x64 17.7.0
Remote OS version: Linux x64 4.9.90-xenomai-3.0.7

**Comment by roblourens** [comment]
All you have to do is close the window - there is nothing else you have to do to disconnect.

If you want to totally clean up everything that vscode installs on the remote, there is a command you can run, "Uninstall VS Code Server from host"
