### ISSUE TITLE
Suggestion: Remote Containers - /workspaces permissions should not be root

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-remote-release#2173]
Suggestion: The `/workspaces` folder should have the same permission as the user of the container, `vscode` and not `root`.

The reason for this is that I am trying out Remote Containers and I want to clone another repository into the `/workspaces` folder, but I can't because I get a permission error.  It seems to me that the whole `/workspaces` folder is for me to put folders into to try out and work on, so I should by default have permission to use it. Sure i can `sudo` or `chown` the folder, but its a sample, so it should be easy :).

- execute command `Remote - Containers: Try A Sample`
- pick Python
- open terminal, `cd /workspaces`
- `git clone` your favorite repository (to add another folder to your workspaces)

Result: permission denied, as the `/workspaces` folder is owned by `root`, not `vscode` in this case.

**Comment by chrmarti** [comment]
We can `chown` it together with the cloned folder. If there are multiple containers using the same volume the last one will win and the others might not have write access to `/workspaces`.
