### ISSUE TITLE
Performance Improvements for Dev Container

### ISSUE THREAD

**Issue by ShMcK** [microsoft/vscode-remote-release#2174]
### Issue

How to improve performance inside of the VSCode Remote Dev Container?

Performance is currently a downer on an otherwise amazing feature/extension!

### Method

I followed the ["Getting started with Dev Containers"](https://code.visualstudio.com/remote-tutorials/containers/getting-started) tutorial using the Node.js example. The result was significantly slower than I expected.

As a metric, I installed the [Jest test runner](https://jestjs.io/) and ran a simple default test from the command line a dozen times.

```
Outside of Container:   < 1s
In Dev Container:      ~5-10s
```

I tried again with a simple bash script to measure performance. The script just loops over 100,000 numbers and writes the current number to a file.

```
#!/bin/bash
 for i in $(seq 1 10000); do echo $i > file.txt; done
```

Results from running the Bash script several times:

```
Outside of Container:   ~2s
In Dev Container:       ~20-30s
```

### Details

Running on: 

```
Apple Macbook 
Processor: 1.4 GHz Quad-Core Intel Core i5
Memory: 16 GB

Docker Desktop: 2.1.0.5 (latest stable)
Docker Engine: 19.03.5
Docker Compose: 1.24.1
```

### Attempts

I tried adjusting my Docker engine defaults: increasing CPU, Memory, Swap - but results remained similar to those above.

I read [Speeding up Docker on MacOS](https://engageinteractive.co.uk/blog/making-docker-faster-on-mac) and followed any optimizations to verify the issue is unlikely caused by my particular current computer configuration.

### Request(s)

1. Can you provide documentation of ways to improve Docker performance when using the VSCode Remote Dev Container extension?

2. Could performance be improved for Remote Dev Containers in future releases?

3. Could Docker resources be configured in the `.devcontainer` folder in a way that would allow for more performance friendly containers?

**Comment by egamma** [comment]
Have you tried:
- opening the repository into a container directly using the 'Open Repository in Container...' command. This command clones the repository into a docker volume and does not use a bind mount. Since there is no bind mount you have no direct access to the files from outside the container. It would be interesting to run you same benchmark in this setup. 
- have you looked into how use volume mounts manually as described in the documentation https://code.visualstudio.com/docs/remote/containers-advanced#_improving-container-disk-performance

**Comment by chrmarti** [comment]
I can reproduce your measurement on Mac. Using a volume or just the container's filesystem brings it down to the timing you see locally. This is a limitation of the filesystem driver doing the mount on the Mac's filesystem from what we see.
