### ISSUE TITLE
Support simple file sync when project is copied locally

### ISSUE THREAD

**Issue by ackvf** [microsoft/vscode-remote-release#2175]
My local PC and server are both Windows 10, I have tried all the possible solutions, even trying to set the remote SSH to use a WSL as a default shell and connect to a remote WSL over SSH instead, because my server's Windows architecture wasn't supported (by the experimental insiders extension).

Loading the project over mapped drive via network seemed fine, but the JS/TS language server loads after 10 or more minutes later.

So I was thinking, I do have a copy of the files locally, so can't I simply work locally and synchronise all changes to the remote as efficiently and fast as possible? Could you support that?

PS:
Even though there are command line tools and scripts for file synchronisation already, they are clumsy to use or don't really support watching for changes well or introduce way much overhead. Being implemented as a vscode-remote-development extension, it could leverage the actual VSCode's emitted events and perform the synchronisation more quickly and efficiently.

**Comment by roblourens** [comment]
Yeah like you said, there are other external tools for that. But we don't plan to support that officially.

**Comment by ackvf** [comment]
I didn't write the PS to undermine myself. I meant it honestly and you, turning me down like that, doesn't sound like you put even a single thought on that. I spent two days on making my remote development feasible, I did a huge research before writing it. The vast variety of already existing file-sync solutions just don't do the right job for a very specific use-case that the code development is.

Why I wrote this is because you already have the know-how of probably an efficient communication between a local VSCode instance and a VSCode-server. If it is possible to leverage this to write an extension for remote development, than accept my apologies and please forward me to some resources.

--- 

So I still feel like instead of being limited to use only supported extensions that can run on both, the client and server, it would be much more efficient and possibly easier(?) to have a local copy of the files, run the full extension set locally without limitation (just like local development) and only issue file changes commands to the vscode-server instance.

The thing is:
Instead of mirroring local settings and extensions to the server and run both in a fragile tandem,
mirror server files to the client, let the user develop locally while signalling the server of only the content changes.

**Comment by roblourens** [comment]
If you want to tell me what problem you are having with remote development, I'd be happy to help you debug it. But the alternative that you suggest doesn't really fit into vscode's remote development model, and seems like something like rsync, or even OneDrive, or some other purpose-built tool would do a better job of it than us.
