### ISSUE TITLE
Using Remote-SSH on closed network

### ISSUE THREAD

**Issue by ericj79** [microsoft/vscode-remote-release#2176]
I am trying to use the Remote-SSH extension on a closed network, but on the first connect ti tries to download something for the remote host and install it, which fails. Is it possible to create an offline version of the extension  for people to install that has the remote install packages pre-downloaded? Similar to how the C/C++ extension now has offline VSIX files. Or could you make the various remote install files available for download, so I could install them manually on my remote machine?
In this case my local machine is Windows and my remote machine is Linux (Ubuntu 19.04).

**Comment by Coderx7** [comment]
I'm having the very same problem. both my dev system and the remote server are isolated . 
I want to use remote-ssh to connect to the remote server, but fail becasue there is no internet. 
I have already read the discussion at #161 but it doesnt work becasue both the host and the remote are isolated from internet.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/1242
