### ISSUE TITLE
RDP session becomes unusable, strongly slow, due to the blue "loading bars" animation

### ISSUE THREAD

**Issue by KevinGuancheDarias** [microsoft/vscode-remote-release#2177]
- VSCode Version: 1.41.1
- Local OS Version: Windows 7 SP1
- Remote OS Version: Docker version 19.03.1, build 74b1e89e8a
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open a RDP session to the Windows 7 machine
2. Open a project with a .devcontainer dir
3. Press launch in container
4 While the bars keep moing the session becomes almost unusable, unless you minimize the vscode window

I can't find the extension source code, maybe it's not opensource?. I wanted to look around in the source code to remove the bars by myself till other solution becomes available

Best regards! :wine_glass:

**Comment by roblourens** [comment]
Which bars are you talking about?

**Comment by KevinGuancheDarias** [comment]
The ones that display while the system prompts password on (ssh), or while it displays "Starting devcontainer"

![image](https://user-images.githubusercontent.com/6832422/73872911-82f28b00-4848-11ea-92ff-c013a4d84c1d.png)

I don't know how are you guys doing the animation, but looks like RDP doesn't really like it, CPU on client machine hits high usage in RDP client (mstsc) and connection becomes slow, or even crash 

After the blue disappears connection becomes fast again, and CPU usage for mstsc is again low

![image](https://user-images.githubusercontent.com/6832422/73873082-d533ac00-4848-11ea-9e9b-1ca77a3d5b44.png)

Thank you for your time!

**Comment by roblourens** [comment]
Is that true of any animation in the RDP session? I doubt there would be anything vscode-specific here

**Comment by KevinGuancheDarias** [comment]
If there are other animations in the session, the behavior would be the same I just avoid using graphical applications when I'm using RFP, but I expect to be able to develop from VSCode in the RDP session

If you think this can't be considered as a bug, maybe it should be considered a "Feature request", something like "be able to disable VSCode animations in the editor config"

Sometimes i have to kill VSCode from outside, as docker container launching hangs, and it's impossible to stop from the session, due to the loading bars

Thanks in advance! :wine_glass:

**Comment by roblourens** [comment]
Sorry that you have this issue. I'm not sure it's really practical for us to address this. I will leave it open for now.

**Comment by roblourens** [comment]
Have you tried running vscode locally and connecting to your remote container?

**Comment by KevinGuancheDarias** [comment]
Defining `DOCKER_MACHINE` env var and tunnelling the docker port over SSH allows me to run the containers in local VSCode, but then I would have to work both locally and remotelly, as I have to use some GUI tools in the remote machine, such as Eclipse (support for Java is not great enough to use VSCode for now).

Anyway if you don't think this should be fixed no problem, I know it's not a common use case

Only one quick question, are these loading bars something core in VScode that the extension "tells" VSCode to display, or it's extension animation own code?

**Comment by roblourens** [comment]
One of them is driven by vscode, one of them is the extension telling vscode to show a progress bar.
