### ISSUE TITLE
Why are logs for connections stored directly in user directory of remote host?

### ISSUE THREAD

**Issue by Stormwaker** [microsoft/vscode-remote-release#2178]
Lots of reports are saved directly in user directory on remote host. It's just a bit annoying having to clear home folder few times every day because of all the reports that are popping up there. Is this how the reporting is supposed to behave?

**Comment by roblourens** [comment]
Can you explain more about what "reports" you are seeing and what the issue with them is?

**Comment by Stormwaker** [comment]
This is how my user folder on server machine looks like now:
```
report.20200129.094733.17272.0.001.json
report.20200129.094757.17284.0.001.json
report.20200130.083443.24318.0.001.json
report.20200130.083507.24451.0.001.json
report.20200130.083531.24468.0.001.json
report.20200130.083557.24481.0.001.json
report.20200130.083623.24494.0.001.json
report.20200130.083648.24506.0.001.json
report.20200130.083712.24518.0.001.json
report.20200130.102713.14112.0.001.json
report.20200130.102739.15733.0.001.json
report.20200130.102804.17240.0.001.json
report.20200130.102831.17678.0.001.json
report.20200130.102857.19341.0.001.json
report.20200130.102923.20946.0.001.json
report.20200130.102950.22611.0.001.json
report.20200131.111329.3579.0.001.json
report.20200131.111354.3726.0.001.json
report.20200131.111418.3741.0.001.json
report.20200131.111443.3755.0.001.json
report.20200131.111506.3767.0.001.json
report.20200131.111532.3779.0.001.json
report.20200131.111556.3792.0.001.json
```
The issue is that it's not the right folder for storing such reports/logs. They're created on server machine while using Remote Development.

**Comment by roblourens** [comment]
That's not from vscode or this extension as far as I know. What are the contents of one of those files? They could be from an extension or some other tool?
