### ISSUE TITLE
Failed to connect to the remote extension host server (Error: Could not establish tunnel to "gic" (Max wait time exhausted).)

### ISSUE THREAD

**Issue by tianyehedashu** [microsoft/vscode-remote-release#218]
- VSCode Version: insider 1.34
- Local OS Version: win10
- Remote OS Version: linux
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.disable ssh forwarding in remote server 
2.connect remote ssh

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Can you explain what you mean? 

> disable ssh forwarding in remote server

Do you mean disabling TCP port forwarding? Remote-SSH will not work with this disabled.
