### ISSUE TITLE
Cannot install on remote if OS is NixOS

### ISSUE THREAD

**Issue by aabs** [microsoft/vscode-remote-release#219]
- VSCode Version: Latest Insiders Build
- Local OS Version: Win 7
- Remote OS Version: NixOS 18.09
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to remote server running nixOS
2. Ensure bash is default shell on remote end

Does this issue occur when you try this locally?: NA
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Error messages received in OUTPUT console:

```
SSH Resolver called for "ssh-remote+work2"
SSH Resolver called for host: work2
Setting up SSH remote "work2"
Using commit id "473af338e1bd9ad4d9853933da1cd9d5d9e07dc9" and quality "insider" for server
Install and start server if needed
> 
> bash: line 164: /bin/bash: No such file or directory
> 
"install" terminal command done
Received install output: bash: line 164: /bin/bash: No such file or directory
Failed to parse remote port from server output: bash: line 164: /bin/bash: No such file or directory
```

This works because NixOS does not follow the std linux filesystem hierarchy, therefore `/bin/bash` is not there.  Can you please change yr script(s) to the more portable `/usr/bin/env bash` which should run OK.  Thanks.

**Comment by roblourens** [comment]
Yes - https://github.com/microsoft/vscode-remote-release/issues/124

**Comment by aabs** [comment]
Ah, Sorry.  Didn't see that one.
