### ISSUE TITLE
Only the first `LocalForward` directive is detected in .ssh/config

### ISSUE THREAD

**Issue by pd93** [microsoft/vscode-remote-release#2190]
Issue Type: <b>Bug</b>

I have an SSH config file that specifies multiple port forwards (see below):

```
Host myhost
    HostName        x.x.x.x
    LocalForward    8000 127.0.0.1:8000
    LocalForward    1433 127.0.0.1:1433
```

[ssh_config(5)](https://linux.die.net/man/5/ssh_config) states that:

> Multiple forwardings may be specified

Both ports are being forwarded by SSH fine, but VSCode's "Existing Tunnels" section does not reflect this. If I swap the order of the `LocalForward` directives, the forwarded port that VSCode detects changes. This implies it only reads the first instance of `LocalForward`.

Extension version: 2020.1.28320
VS Code version: Code - Insiders 1.42.0-insider (68615717819b3731705d92ec06b52edd47665291, 2020-01-22T05:31:57.634Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-166-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (25.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev|
|OS|Linux x64 4.4.0-166-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (1 x 2497)|
|Memory (System)|3.85GB (0.23GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Thanks, this is from a bug in the ssh config parsing library I use.
