### ISSUE TITLE
Nested(?) volumes not working as expected on expected on Windows

### ISSUE THREAD

**Issue by issacg** [microsoft/vscode-remote-release#2191]
- VSCode Version: 1.41.1
- Local OS Version: Windows 10 Pro 18363.592
- Remote Extension/Connection Type: Docker
- Docker Desktop Version: 2.2.0.0 (Using Hyper-V backend)

Steps to Reproduce:

1. Create a .devcontainer project.  I'm using Node.js but that doesn't seem relevant to reproducing the bug
2. Following [the directions](https://code.visualstudio.com/docs/remote/containers-advanced#_improving-container-disk-performance) I added 2 volume mounts - one nested in the workspace, and the second not
```
"mounts": [
		"source=vsc-backup-node_modules,target=/workspace/app/node_modules,type=volume",
		"source=vsc-backup-vscext,target=/root/.vscode-server/extensions,type=volume"
	],	
	"workspaceMount": "source=${localWorkspaceFolder},target=/workspace,type=bind,consistency=cached",
	"workspaceFolder": "/workspace/app",
```
3) Running docker inspect immediately when container is running (post-build; just when vscode is injecting its magic) shows all three expected mounts:
```
> docker inspect distracted_fermi
[snip]
 "Mounts": [
                {
                    "Type": "bind",
                    "Source": "/host_mnt/c/hass/cerebro-hass/backup",
                    "Target": "/workspace",
                    "Consistency": "cached"
                },
                {
                    "Type": "volume",
                    "Source": "vsc-backup-node_modules",
                    "Target": "/workspace/app/node_modules"
                },
                {
                    "Type": "volume",
                    "Source": "vsc-backup-vscext",
                    "Target": "/root/.vscode-server/extensions"
                }
            ],
[snip]
```

However, immediately inspecting from inside the container only shows two mounts:
```
>docker exec   distracted_fermi mount
[snip]
grpcfuse on /workspace type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
/dev/sda1 on /root/.vscode-server/extensions type ext4 (rw,relatime)
[snip
```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes (Except the remote extension)

**Comment by issacg** [comment]
This smells similar to https://github.com/docker/for-mac/issues/3976

However, I can't find a similar issue in docker for-win and the symptoms seems a bit different.  I've also been as careful as possible not to touch anything in the Windows OS side - closing explorer windows, editors, staying away from that folder in the command prompt, etc...   

I'm never able to see the mount inside the container.  So it's not quite the same as the above which seems to be more about "mysterious unmounting" whereas mine doesn't seem mounted to begin with...

**Comment by issacg** [comment]
OK, apparently this is upstream and was reported as I was opening this :)

https://github.com/docker/for-win/issues/5540

**Comment by chrmarti** [comment]
Closing as upstream, thanks.
