### ISSUE TITLE
File sharing issues with Docker for Windows 2.2.0.0

### ISSUE THREAD

**Issue by EricHripko** [microsoft/vscode-remote-release#2193]
- VSCode Version:
```
1.41.1
26076a4de974ead31f97692a0d32f90d735645c0
x64
```
- Local OS Version: `Windows 10`
- Remote OS Version: `RHEL 7.7`
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Install _Docker 2.2.0.0_
2. Open any project in _Remote - Containers_
3. Modify any file and attempt to save
4. Observe _Failed to save_ pop-up despite nothing modifying the file except from yourself
![Conflict](https://user-images.githubusercontent.com/707679/72989753-ca0f6380-3de6-11ea-9d75-c61464690225.png)

Please note that Docker for Windows updated the way [file sharing works](https://www.docker.com/blog/deep-dive-into-new-docker-desktop-filesharing-implementation/). I've checked the last modified time of the 'conflicting file' in the terminal and it looked correct. Therefore, I am submitting the issue here. If it's a problem with the new file sharing implementation, I'll happily shoot an issue to [Docker folks](https://github.com/docker/for-win/issues).

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by EricHripko** [comment]
Possibly related to https://github.com/docker/for-win/issues/5543, although `stat` returns correct times for me whilst VSC fails to save every time.

**Comment by stephen-turner** [comment]
I think this is docker/for-win#5528

**Comment by Gehbrial** [comment]
I've been having the same issue.

**Comment by SeniorSupportEngineer** [comment]
I've been having the same issue. Rolled back to 2.1.0.5. Because the new version is really bad. Allot of issue. Also the command docker-compose run --rm php-cli sh gives errors. But there's a workaround for that. But I really don't understand why the version 2.2.0.0 is released.

**Comment by ntaylor-barnett** [comment]
This would explain some of the big issues I've been having with my development container! Our make script use to download a PACT tar, extract it and then install it, but it ran in the default "workspace" folder that VSCode maps for you into the container. Every time without fail, something "tar" did would cause the connection to the file system to break and would get it stuck with "transport disconnected" errors that could only be resolved by restarting docker.

I have already established a workaround for this problem by just working in a non-mapped folder, but it is still a big breaking change!

**Comment by chrmarti** [comment]
This should be fixed with `2.2.0.3` of Docker for Windows. (https://github.com/docker/for-win/issues/5543#issuecomment-584636039)

**Comment by EricHripko** [comment]
Yep, can confirm that `2.2.0.3` fixes the issue for me. Thanks 👍
