### ISSUE TITLE
Test auto platform detection for Remote-SSH

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#2196]
Refs: https://github.com/microsoft/vscode-remote-release/issues/25

- [x] macOS @rebornix
- [x] linux @RMacfarlane
- [x] windows @chrmarti

Complexity: 3

---

Test machines available:
https://github.com/microsoft/vscode-internalbacklog/issues/700

- Install the nightly SSH extension
- Set `"remote.SSH.useLocalServer": true`
- If you had previously set `remote.SSH.windowsRemotes`, get rid of it
- Test connecting to the linux remote and the windows remote, just verify that it connected successfully (and that it connected to real windows, not WSL)

**Comment by chrmarti** [comment]
@roblourens The Windows test box does not have a SSH server running at the moment.

Also: On my current Windows install, the ssh CLI does not pick up my .ssh/config anymore. Any idea why that would be?

**Comment by chrmarti** [comment]
Not sure what went wrong, but the ssh config is being picked up again. The Windows box looks like it is being worked on to get sshd running. I'll defer testing until this is done.

**Comment by roblourens** [comment]
Oh crap, sorry, I had taken it down to debug something. I just started it up again.

Also, I had to start it on a non-standard port, because I think the connection I'm on right now is blocking port 22. Added that to the issue, make sure you copy that config line.

**Comment by RMacfarlane** [comment]
The first time I tried to connect to the Windows box, it timed out. I hit retry without copying any details from the output channel, and it's now connecting to both machines perfectly. So I think this was just a transient problem, but thought I'd mention it anyway.

**Comment by rebornix** [comment]
I tested with the VM created by @roblourens and they worked just fine. However when I try to connect to my own Windows box, it always timeouts. I can ssh to it so not sure why it can't finish launching the server.

**Comment by roblourens** [comment]
@rebornix please file an issue with the log

**Comment by rebornix** [comment]
@roblourens thanks, here it is #2262

**Comment by Chuxel** [comment]
> Set `"remote.SSH.useLocalServer": true`

@roblourens Should we mention this setting in docs and the README to avoid confusion?
