### ISSUE TITLE
Reopen Folder in WSL giving UriError with WSL 2

### ISSUE THREAD

**Issue by gyroknight** [microsoft/vscode-remote-release#2197]
- VSCode Version: 1.42.0-insider
- Local OS Version: Windows 10 Education 2004 19041.21
- Remote OS Version: Ubuntu 19.10
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Open folder in normal mode
2. Attempt to use "Remote-WSL: Reopen folder in WSL" command from Command Palette

The WSL log shows the following error:
[2020-01-25 18:22:54.327] Error: [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character

Issue did not occur with WSL 1, only occurs with WSL 2.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by aeschli** [comment]
What Windows folder path do you have open?

**Comment by gyroknight** [comment]
`C:\Users\Vincent\OneDrive - Northeastern University\`, however the same issue occurs on shorter paths with no spaces in them, e.g. `C:\test\`

**Comment by aeschli** [comment]
Can you run `wsl.exe wslpath -u 'c:\test\'` from a Windows command prompt and paste the result here?

**Comment by gyroknight** [comment]
```
fish: Unexpected end of string, quotes are not balanced
wslpath -u 'c:\test\'
           ^
```

Looks like [fishshell](https://github.com/fish-shell/fish-shell) is causing the issue, I have it set as my default shell. Fish seems to require escaped characters to actually be escaped, otherwise it doesn't consider it a valid string, which is why `wslpath -u 'c:\test\'` doesn't work but `wslpath -u 'c:\\test\\'` does.

**Comment by gyroknight** [comment]
It considers the `\'` as a delimited quote, `wslpath -u 'c:\test\\'` also works.
