### ISSUE TITLE
can not attach terminal in docker container

### ISSUE THREAD

**Issue by zhangzheyu2simple** [microsoft/vscode-remote-release#220]
- VSCode Version:1.34.0-insider
- Local OS Version:Ubuntu 16.04.5 LTS 64-bit
- Remote OS Version:python:3
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1.after setting up vscode-remote-try-python 

![image](https://user-images.githubusercontent.com/40783573/57352899-60d4bb00-7199-11e9-8c0b-7bf1fa598627.png)
docker ps

![image](https://user-images.githubusercontent.com/40783573/57352935-8792f180-7199-11e9-8e84-dc23a8009cfd.png)

2.I can not attach a terminal to the container
![image](https://user-images.githubusercontent.com/40783573/57353056-de003000-7199-11e9-86ea-c63fbc002f0d.png)

while  I can run 

`docker exec -it 434a sh`

to access into the container and everything works well

is this a bug? what does vscode do when it attaches a terminal to a container?

**Comment by zhangzheyu2simple** [comment]
terminal return 
`execvp(3)  failed :no such file or directory`

**Comment by egamma** [comment]
@zhangzheyu2simple I suspect that the shell is not found. what shell do you have configured in your settings? Can you try to configure bash or sh?

![image](https://user-images.githubusercontent.com/172399/57356456-bf397380-7170-11e9-88f7-8dbf7a1a4e08.png)

**Comment by wilkice** [comment]
> @zhangzheyu2simple I suspect that the shell is not found. what shell do you have configured in your settings? Can you try to configure bash or sh?
> 
> ![image](https://user-images.githubusercontent.com/172399/57356456-bf397380-7170-11e9-88f7-8dbf7a1a4e08.png)

I had the same problem when using **SSH** , but solved with your settings. Thanks. :smile:

**Comment by egamma** [comment]
@sandy081 should this setting be a machine specific setting, that is not automatically applied in the remote case?

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/38
