### ISSUE TITLE
Allow rebuild container without cache

### ISSUE THREAD

**Issue by rubensa** [microsoft/vscode-remote-release#2200]
Sometimes I have a **Dockerfile** that installs software downloaded form Internet.  If download fails (cause a network failure or something), the image is build anyway.

The problem is that I can't force **VSCode** to rebuild the image (so, once the network issue is fixed, the software can be downloaded and installed) using **Remote-Containers: Rebuild Container** as it always uses cache.

Please provide a **Remote-Containers: Rebuild Container without Cache**, or similar command, containing the **--no-cache** option.

**Comment by holms** [comment]
Any reaction to this? I'm not sure if this not related, but when I even push Rebuild container, it starting container again, and pop-up appears to rebuild container, pushing that button it goes in circles again without building anything.

**Comment by AlexisLessard** [comment]
I too would like this feature. I sometimes have issues in nodejs where an issue with docker itselfs requires me to rebuild the entire image. But I can't. My only workaround is to change the source image from `node:12` to `node:11` and vice-versa. This should be either an option in .devcontainer.json or an entirely new command.

**Comment by JohnBetaCode** [comment]
do an echo "something" run command when you want to rebuild, ugly, but useful

**Comment by Alaric84** [comment]
yes I think especially for devcontainers where we want always with the latest version the --no-chache option should be possible. I would be happy with a buildArgs in the devcontainer.json
Better to have the no-chache everytime (and pay this with some seconds startup time) than to have outdated stuff in the development environment.

**Comment by johnmarkwayve** [comment]
Work around: copy the `docker build` command from the log, append `--no-cache` and run in a separate terminal, return to vscode and "Re-open in Container" to use the refreshed cache

**Comment by ThomasTosik** [comment]
Is there any plan for this? After some time and issues i stumbled upon this issue and its frustrating that i can not truly rebuild/clean (with --no-cache). Manualy deleting an image only works sometimes but when you are working in a bigger context; this leads often to "delete all images because i dont now comfortably what layer is used by cache".

**Comment by aniongithub** [comment]
Maintainers, this sort of thing would be trivial if this extension was open-sourced, you'd get a PR in no time flat. Please consider open sourcing this extension!
