### ISSUE TITLE
Test: Remote-Containers simplified adding extensions

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2204]
Refs: #1800

- [x] anyOS @mjbvz
- [x] anyOS @rebornix

Complexity: 3

---

Test:
- `devcontainer.json`'s `"extensions"` property is linted for the syntax of the extension ids.
- `devcontainer.json`'s `"extensions"` property has content proposals based on the locally installed extensions.
- The Extension viewlet has a context menu action on extensions to add the extension to the `devcontainer.json`.

On how to use Remote-Containers for testing see https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#testing-remote-containers.

**Comment by rebornix** [comment]
> devcontainer.json's "extensions" property has content proposals based on the locally installed extensions.

Before creating an issue, I want to confirm if I did anything wrong. I didn't see the suggestions for local installed extensions. The other features work as advertised.

**Comment by chrmarti** [comment]
@rebornix That doesn't seem to work, tracking with #2204. Thanks!
