### ISSUE TITLE
Test: Remote-Containers' "forwardPorts" property in devcontainer.json

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2208]
Refs: #1009

- [x] anyOS @isidorn
- [x] anyOS @deepak1556

Complexity: 3

---

Test the new "forwardPorts" property for the devcontainer.json. The listed ports should be forwarded when the container comes up. You can see the forwarded ports in the Remote Explorer (note that the UI there is tested separately).

On how to use Remote-Containers for testing see https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#testing-remote-containers.

/fyi @alexr00

**Comment by isidorn** [comment]
Works well overall 👏
