### ISSUE TITLE
Test: Remote-Containers pre-built container images

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#2209]
Refs: https://github.com/microsoft/vscode-dev-containers/issues/140

- [x] macOS @alexdima
- [x] Windows @sana-ajani
- [x] Linux @aeschli

Complexity: 2

---

1. Get version 0.99.1 of the Remote - Containers extension or later (should release tomorrow)
2. Use "Remote-Containers: Add Development Container Configuration Files..." on a folder without a `.devcontainer` folder.
3. Select one of the following:
    - [x] Alpine 3.10 & Git
    - [x] Debian 9 & Git
    - [x] Debian 10 & Git
    - [x] Node.js 10
    - [x] Node.js 12
    - [x] Node.js 10 & TypeScript
    - [x] Node.js 12 & TypeScript
    - [x] Ubuntu 18.04 & Git
4. Verify the links in `.devcontainer/devcontainer.json` and `.devcontainer/Dockerfile` work.
5. Use `Reopen Folder in Container` and verify you are able to create the container
6. Use the product a bit as you would normally to verify there are no critical missing pieces in the image.

**Comment by alexdima** [comment]
brilliant! :heart:
