### ISSUE TITLE
Test Reveal Explorer in WSL

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#2211]
Refs https://github.com/microsoft/vscode-remote-release/issues/1659

- [x] Windows @dbaeumer
- [x] Windows @sana-ajani

Complexity: 1

---

- Open a Remote - WSL window on a folder
- Select a file or folder in the explorer and run `Reveal Explorer` from the context menu or command palette

**Comment by dbaeumer** [comment]
Cool :-)

**Comment by sana-ajani** [comment]
Nice, this is convenient!
