### ISSUE TITLE
Test piping to stdin

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#2212]
Refs https://github.com/microsoft/vscode-remote-release/issues/1764

- [x] Windows @bpasero  (WSL)
- [x] Linux @joaomoreno  (SSH)
- [x] Mac @btholt (Containers)

Complexity: 1

---

- Open a Remote - WSL/SSH/Container  window on a folder
- In the integrated terminal, pipe content to code: `ps aux | code-insiders -)`
- Make sure that `code-insiders --help` explains the syntax as well.

**Comment by fiveisprime** [comment]
The correct file opens with no content and the shell command waits until the editor is closed to resume

![image](https://user-images.githubusercontent.com/1186948/73285788-681a7980-41ab-11ea-92e9-ffe6e95bd698.png)

Windows@19551.1005
WSL@2
Insiders@latest

**Comment by btholt** [comment]
The correct file opens with the correct output. The shell command does pause until you send a signal to stop or you close the file.

![Screen Shot 2020-01-28 at 2 52 01 PM](https://user-images.githubusercontent.com/999523/73312543-ceb88b00-41dd-11ea-89fd-d77655ca55e8.png)

macOS@10.15.1
Docker Desktop@19.03.5
Insiders@latest
Container: node:12.14.1 (which is Debian 9.11)

**Comment by fiveisprime** [comment]
Appears to work, but it feels strange that it a) holds onto the shell and b) doesn't infer the scheme. For example, `cat package.json | code-insiders -` opens as `.txt` and holds onto the shell. Opening everything as `.txt` is reasonable, but is the hang expected?

Looks like the `cat` completes, but `code-insiders -` is running. 

![image](https://user-images.githubusercontent.com/1186948/73323145-477a1000-41fb-11ea-9988-44c86f89f70b.png)

**Comment by aeschli** [comment]
@fiveisprime The 'hanging' is 'as-designed'. https://github.com/microsoft/vscode/issues/39682 is the request to change that.
We only get the content (as a stream). We don't have code that guesses a language id from content.
