### ISSUE TITLE
remote-ssh settings.json ignored with default value if set in the UI

### ISSUE THREAD

**Issue by omartin2010** [microsoft/vscode-remote-release#2214]
Issue Type: <b>Bug</b>

We have written the needed data into
Issue Type: Bug

Connect to a remote SSH environment ;
Have the User settings (local setting) of Jedi to False ;
Have the Remote (SSH:host) language server to set Jedi (in the case of `Python` , see [this issue](https://github.com/microsoft/vscode-python/issues/9775) to True (in the UI, not in the actual file).
The language server that will load is the Microsoft Python Analysis Engine, and not the Jedi server even if set to true, until you actually put it in the Settings. json file. In other words, if set to default value, and therefore not written in `settings.json`, it seems to ignore the remote parameter.

Extension version: 2020.1.58038
VS Code version: Code - Insiders 1.42.0-insider (f3dbcea32a6b52ce819dc863e778fb8517357f61, 2020-01-24T05:38:14.538Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux arm64 4.9.140-tegra

Extension version: 0.48.0
VS Code version: Code - Insiders 1.42.0-insider (5dcf2c96b6562b3aa879dbb455de4b58e17cb804, 2020-01-27T11:23:59.719Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux arm64 4.9.140-tegra

**Comment by roblourens** [comment]
This is another instance of https://github.com/microsoft/vscode/issues/58038
