### ISSUE TITLE
Duplication in remote name message

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-remote-release#2217]
Refs: https://github.com/microsoft/vscode-remote-release/issues/2206

Go through the setup from repository flow.
Why the message in brackets `(e.g microsoft/vscode-remote-try-node)`? This is already mentioned to the user with the placeholder message. To make the message simpler I suggest t oremove the message in brackets.

Also why do we always say "Press enter to confirm, escape to cancel"?! Isn't this obvious, why does every dialog have to have this? Also we do not do this in vscode code.
I would suggest to also remove that.

![Screenshot 2020-01-28 at 12 07 50](https://user-images.githubusercontent.com/1926584/73258868-e33d5900-41c6-11ea-836b-56c7605617e8.png)

**Comment by chrmarti** [comment]
"Press 'Enter' to confirm or 'Escape' to cancel" is from QuickInput (and previously from QuickOpen's input box).

Having the example in the description to guide the user while typing seems to make sense to me. Not sure what we would win from removing that.

**Comment by Tyriar** [comment]
I also would have created this, the example is already in the textbox, so there's no point repeating it. It's just more text that the user needs to read. Maybe change one of them to `user/repo`?

**Comment by egamma** [comment]
The message has been updated.
