### ISSUE TITLE
Forwarded ports validation in devcontainer.json should be smarter

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-remote-release#2218]
Refs: https://github.com/microsoft/vscode-remote-release/issues/2208

Have a `forwadedPorts` field in you `devcontainer.json`. Have port outside fo the range, for example `100000`. Open that devcontainer.json in a container. Notice the ugly error

I would expect some smarter `forwardedPorts` validation. For example an error if the port is out of range. I am not sure if that is possible to be done from the extension, but I do something similar internally for launch.json validation.
Code pointer for inspiration 
https://github.com/microsoft/vscode/blob/5c6b51aaaf06af9a49e5567ab1f4caa16fd198d1/src/vs/workbench/contrib/debug/common/debugger.ts#L224

![Screenshot 2020-01-28 at 12 30 11](https://user-images.githubusercontent.com/1926584/73260378-11706800-41ca-11ea-8f0c-eab82fe30c61.png)

**Comment by alexr00** [comment]
@chrmarti FYI, I updated the devContainer.json schema to have min and max for forwardedPorts values.

**Comment by chrmarti** [comment]
Thanks @alexr00 !
