### ISSUE TITLE
Forwarded ports view should keep order stable

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-remote-release#2219]
Refs: https://github.com/microsoft/vscode-remote-release/issues/2208

1. Have some ports forwarded
2. Change some local port of the those
3. That forwarding is now moved to the end of the list :bug:

The list should be stable as that is an easier UX to understand.

![hello](https://user-images.githubusercontent.com/1926584/73260858-2699c680-41cb-11ea-84ab-079eb20a697f.gif)

**Comment by alexr00** [comment]
Planned order: sort ascending by port number.
