### ISSUE TITLE
Forwarded Ports changes to ports has no effect after reload

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-remote-release#2220]
Refs: https://github.com/microsoft/vscode-remote-release/issues/2208

When I set the `forwardedPorts`  in the `devcontainer.json` it always forward port `N` to local port `N`.
If I change this in the Forwarded Ports view, for example I forward port 'N' to 'M' this will not be preseved and next time I start the workspace `N` will still be forwarded to 'N'.

This might be the issue that Forwarded Ports view does not store it's state properly.

I see the `forwardedPorts` as the default value, however all changes that the user does in the Forwaded Ports view should be applied on top.

![hello](https://user-images.githubusercontent.com/1926584/73261041-8db77b00-41cb-11ea-954c-dcf0b67300ca.gif)

**Comment by alexr00** [comment]
Hmm, this is an ordering issue I think. The forwarded ports view would restore it's state, then containers would set the forwarded ports, overwriting the state that you want to keep.

**Comment by chrmarti** [comment]
Cannot reproduce. I think you didn't enable restoring the forwarded ports. The suggested change still makes sense.

**Comment by roblourens** [comment]
I run the repro steps above but see the same result. It should be persisting the port that I picked, right?

I am using the latest version of the containers extension which appears to have the fix.

**Comment by chrmarti** [comment]
@isidor @roblourens There is a user setting you need to enable in order for VS Code to restore the ports. Did you do that?
![image](https://user-images.githubusercontent.com/9205389/73522641-330b6280-4409-11ea-8cbc-016d15acdef5.png)

This might be a feature request for automatically updating the devcontainer.json's "forwardPorts" when the user adds / removes one. This is not implemented.

**Comment by roblourens** [comment]
I missed that. It works
