### ISSUE TITLE
Forwarded ports: enter does not Set Local Port

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-remote-release#2221]
Refs: https://github.com/microsoft/vscode-remote-release/issues/2208

Catalina, open Forwaded Ports view, have some port forwaded, press enter to change local port -> no effect :bug:

Even though the context menu picks up the keyboard shortcut

![Screenshot 2020-01-28 at 12 44 01](https://user-images.githubusercontent.com/1926584/73261251-fbfc3d80-41cb-11ea-902d-f0a777ac5502.png)

**Comment by alexr00** [comment]
The corresponding F2 shortcut on Windows works. Does right click to set label work on Mac?

**Comment by isidorn** [comment]
Yeah. Just Enter has no effect -> I think the tree is eating your keybinding, you need to give it bigger weight.

**Comment by alexr00** [comment]
That was part of it, thanks for the pointer!
