### ISSUE TITLE
Unknown attributes in devcontainer.json not flagged

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-remote-release#2222]
Refs: https://github.com/microsoft/vscode-remote-release/issues/2207

1. Have an unknown attribute in the devcontainer.json, for example `appPort2`
2. Notice how `appPort2` is not flagged with a warning

I think we have a closed set of allowed attributes and everything outside of them should be flagged with a warning / error.

**Comment by chrmarti** [comment]
It is harder than I thought to do this in our schema. (https://json-schema.org/draft-06/json-schema-release-notes.html#q-what-happened-to-all-the-discussions-around-re-using-schemas-with-additionalproperties)

Reverting for now.

**Comment by mjbvz** [comment]
Unclear what the state of this work is based on the history but I don't see any warnings in the current insiders build:

![Screen Shot 2020-02-26 at 4 32 52 PM](https://user-images.githubusercontent.com/12821956/75401009-b9ef1600-58b5-11ea-944b-4fd5ca9ec3ba.png)

**Comment by chrmarti** [comment]
Not sure why @Tyriar closed this, maybe a side-effect of merging in distro. It's definitely not fixed.

**Comment by Tyriar** [comment]
@chrmarti yes I pushed when updating distro, the actual commit that closed it is yours and is linked though.

**Comment by chrmarti** [comment]
Fixed since. Closing.
