### ISSUE TITLE
"extensions" could offer a list of extensions as suggestions

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-remote-release#2223]
Have a dockerfile with an "extensions" field.
In the suggest box we could ideally offer all the id's of all the extensions which can hopefully be fetched from the marketplace.
Currently it is a bit tedious to fill this in.

![Screenshot 2020-01-28 at 14 51 04](https://user-images.githubusercontent.com/1926584/73270030-38389980-41de-11ea-8b89-c61b405ef4b5.png)

**Comment by chrmarti** [comment]
You should get the list of installed extension as proposals. There is no marketplace API at the moment.

**Comment by isidorn** [comment]
I have more installed extensions and they are not offered in this case.
