### ISSUE TITLE
Support updateRemoteUserUID for Docker Compose

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#2228]
> We were originally tracking this as #49, but given support is already in place for image and Dockerfile scenarios, I'm raising this to make the issue easier to find.

A critical issue for Linux users is that bind mounting uses the exact same UID and GID as the user in the container when interacting with files. The end result is that, if you are running as root or with UID/GID values that don't exist on the host OS, the files are modified as root.

We've implemented the `updateRemoteUserUID` property in devcontainer.json when the `image` and `dockerFile` properties are used, but not with `dockerComposeFile`. This can be confusing, and the only remaining reason that UID/GID comments exist in many Dockerfiles in vscode-dev-containers.  Rounding out this support would clean up quite a few things and streamline the user experience across the board because of it.

//cc: @chrmarti

**Comment by interob** [comment]
This issue is referred to from various (closed) issues; will this issue be worked on?

Not sure how I can contribute to resolving this -- but if so, I'd be happy to.

**Comment by interob** [comment]
@bamurtaugh I am curious if you are planning to review this item and/or assign it to be resolved in P1 or P2? I would be happy to contribute if there is any way that I can.

Thanks for following up.

**Comment by bamurtaugh** [comment]
Hi @interob, we're tracking this item as part of our backlog; there isn't a set completion date at this point. If we need any additional information or you can help in any way, we'll be sure to let you know. Thank you for following up and for the offer!

**Comment by interob** [comment]
@chrmarti I noticed you closed this one; does it mean this is fixed/implemented?

**Comment by chrmarti** [comment]
Yes, this is fixed in Remote-Containers 0.184.0 I'm releasing right now. (Normally there are a few days or more before a fix is released.) You'll need VS Code Insiders to get that version. Let me know if it doesn't work as expected.
