### ISSUE TITLE
Git config conflicts with dotfiles feature

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#2230]
Testing #2203 

When testing the new dotfiles support with the provided dotfiles repo, I get errors when running stow due to already having a gitconfig. It seems that the feature of copying over your local .gitconfig to the remote machine conflicts with the dotfiles feature. Also, I am not sure if you are forcing git to be installed on the dev container if using the dotfiles feature even if the docker image/docker file does not contain it already. 

Either way, I think this should be documented well or made smoother.

**Comment by chrmarti** [comment]
`stow` is one of several ways dotfiles can be installed. Failing on an existing file is specific to the tool you use.

Which Docker image were you using?

**Comment by sbatten** [comment]
The node js + mongo db one. Yea, makes sense that it is specific, but if we think `.gitconfig` is common enough in dotfiles repos, we should make sure we document the interaction with dev containers and the local `.gitconfig`.

**Comment by chrmarti** [comment]
@Chuxel Not sure if you are preparing a section on the dotfiles. Maybe you could mention that containers can come with dotfiles preinstalled and that these can conflict with the dotfiles repository?

**Comment by chrmarti** [comment]
We are now installing the dotfiles repository before we copy the local .gitconfig into the container (and that we only do if there  is no .gitconfig already.) Closing as fixed with that. (It is still up to the user to make sure the image comes with Git installed. We log and continue if it is not.)
