### ISSUE TITLE
Apply incremental devcontainer.json changes automatically

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-remote-release#2232]
Refs #2207 and related https://github.com/microsoft/vscode-remote-release/issues/2224

I think any change to the dev container should either result in a suggestion to rebuild the container--as in the related issue--or an automatic update to the current state, if possible. For instance, if I change the devcontainer.json to add a forwarded port or change a default setting, it'd be nice to have that take effect automatically.

**Comment by chrmarti** [comment]
Forwarded ports take effect on reload, maybe we can just ignore them when checking for differences.

**Comment by chrmarti** [comment]
On applying the changes without reload: We have so far avoided being overly automatic, users might be working on their configuration without expecting it to immediately take effect. Still something to think about. 🤔

**Comment by alexr00** [comment]
Verified that I don't see the rebuild prompt on reload when all that's changed is `forwardPorts`
