### ISSUE TITLE
Port forwarding: IPv6 addresses are listed

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#2234]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode-remote-release/issues/2195.

On my ssh box I have a vnc server running on port 5901.

I see the following two entries in the Remote Explorer:
![image](https://user-images.githubusercontent.com/4674940/73295352-5f7e6f00-41bc-11ea-8130-71c0b9c9a976.png)

-> I don't expect to see the IPv6 entry.

Extension version: 2020.1.38400
VS Code version: Code - Insiders 1.42.0-insider (c4b6a6b537de49a734d0eedea06152ea37dfdb6a, 2020-01-28T05:34:51.242Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.0.0-1022-azure

**Comment by alexr00** [comment]
Why don't you expect to see the IPv6 entry? I added them because I figured that users would want to see them.
