### ISSUE TITLE
Port forwarding: Presentation of detected ports

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#2239]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode-remote-release/issues/2195.

1) run `npx http-server -p 9876` on the ssh box
2) Refresh the `Forwarded Ports` section in the Remote Explorer
-> `0.0.0.0:9876` shows as new entry. I'd expect to see `9876 not forwarded`.

Also, together with https://github.com/microsoft/vscode-remote-release/issues/2234, I now see three different presentations of ports:

![image](https://user-images.githubusercontent.com/4674940/73296584-dcaae380-41be-11ea-9913-71934b628d35.png)

Extension version: 2020.1.38400
VS Code version: Code - Insiders 1.42.0-insider (c4b6a6b537de49a734d0eedea06152ea37dfdb6a, 2020-01-28T05:34:51.242Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.0.0-1022-azure

**Comment by alexr00** [comment]
None of them should say "not forwarded" since it's in the parent tree node and is redundant.

**Comment by roblourens** [comment]
I still see the presentation with the `0.0.0.0` address, and without. What does the difference imply?

**Comment by alexr00** [comment]
0.0.0.0 indicates all interfaces, and just the port number indicates localhost. I figured showing localhost. We've had users be confused when we don't distinguish between all interfaces and localhost so we need to show some difference for them.
