### ISSUE TITLE
Disable "add to devcontainer.json" action for builtin extensions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-remote-release#2245]
Testing #2204

**Repo**
1. Open a folder with a `.devcontainer/devcontainer.json`
1. Now open the built-in extensions view
1. Right click on an extension

**Bug**
The `Add to devcontainer.json` action is available even though including a built-in extension in this likely doesn't make much sense

**Comment by chrmarti** [comment]
@sandy081 Is there a way to disable the command for built-in extensions? (I'm using the `"extension/context"` menu.)

**Comment by sandy081** [comment]
As of now you can't. I will provide a context where you can set.

**Comment by sandy081** [comment]
Added `isBuiltInExtension` context. You can add this to your when context.
