### ISSUE TITLE
Only enable "Add to devcontainer.json" action for folders that have a devcontainer.json

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-remote-release#2246]
Testing #2204

**Repo**
1. Open an empty folder
1. Go to extensions view
1. Right click on an extension

**Bug**
`Add to devcontainer.json` still shows in this menu. Clicking on it triggers this:

![Screen Shot 2020-01-28 at 3 39 06 PM](https://user-images.githubusercontent.com/12821956/73315229-67eaa000-41e4-11ea-858e-c2ec4cdd50cd.png)

I suggest we only enable this action in folders what we know have a `devcontainer.json`

**Comment by chrmarti** [comment]
I don't think I can write a "when" clause for this without a custom context. A custom context would require the extension to activate on "*" which we want to avoid.

I'll bail out with an info message instead of creating a devcontainer.json.
