### ISSUE TITLE
Show prompt to reopen in container

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode-remote-release#2247]
Re: https://github.com/microsoft/vscode-remote-release/issues/2209

I've used the command "Remote-Containers: Add Development Container Configuration Files" to add the .devcontainer folder. I expected to see a toast prompt telling me to "reopen in container" (as a first time user, I wouldn't know about the command).

**Comment by Chuxel** [comment]
Actually, this command used to do that. @chrmarti, did something get changed here this iteration?

**Comment by chrmarti** [comment]
That toast has a 'Don't show again' button. Just checked it is still there when running with a new user data dir. 👍
