### ISSUE TITLE
remote containers python sample pylint path problem

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-remote-release#2250]
- VSCode Version:
```
Version: 1.42.0-insider
Commit: c4b6a6b537de49a734d0eedea06152ea37dfdb6a
Date: 2020-01-28T05:34:51.242Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0
```

- Local OS Version: macOS High Sierra

- Remote Extension/Connection Type: Docker

**Steps to Reproduce**

1. Install Remote Containers extension
2. From the command palette, choose `Remote-Containers: Try a Sample...`
3. Pick Python
4. open a python file 

**Result** 

When you open the python file you get an error that `pylint` can't be found, it is expecting it to be in `/usr/local/bin/pylint` when in fact it is installed in `/usr/local/share/pip-global/bin/pylint`

Confirmed that if I set the remote setting `"python.linting.pylintPath": "/usr/local/share/pip-global/bin/pylint"` everything works.

**Comment by Chuxel** [comment]
Good catch - missed that edit when I resolved the problem of needing to do sudo.  Looks like I manually updated it in my container so it looked like it worked. DOH!  Fixed with https://github.com/microsoft/vscode-remote-try-python/commit/f83bad5711d8124ce108eac5ab3526abc256490a
