### ISSUE TITLE
Forwarded ports view should retain the mapping

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-remote-release#2251]
Refs: https://github.com/microsoft/vscode-remote-release/issues/2208

1) Have some ports forwarded
2) Start a server on one of the forwarded ports, so that it can be stopped
3) `Stop Forwarding port` from context menu on the busy port
3) Notice the mapping now moved to `Not Forwarded` label
4) `Forward a Port` from context menu
5) The port is forwarded but the mapping is now displayed as `0.0.0.0:3000 -> localhost:3000` , `0.0.0.0` makes ui bit less consistent although its correct. 

Also the context menu label in step 4) would be better named as `Forward Port` rather than `Forward a Port`, the latter gives the feeling of allowing user to configure a new port while thats not the case.

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/964386/73331663-5ff92300-4219-11ea-95a3-e266d97a851a.gif)

This is slightly different from https://github.com/microsoft/vscode-remote-release/issues/2219, hence I moved it to a new bug.

**Comment by alexr00** [comment]
Context menu text has been changed!

For showing 0.0.0.0, this is intentional. We've had uses be confused when if we don't distinguish between localhost and all interfaces.

**Comment by deepak1556** [comment]
> For showing 0.0.0.0, this is intentional. We've had uses be confused when if we don't distinguish between localhost and all interfaces.

Thanks makes sense!
