### ISSUE TITLE
Forwarded ports doesn't allow port that conflicts with host port

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-remote-release#2252]
Refs https://github.com/microsoft/vscode-remote-release/issues/2208

1) Have some ports forwarded

Say the mapping now looks like
```
3000 -> localhost:3000
1000 -> localhost:54285
9222 -> localhost:9223
```
2) Add a new forwarded port `9223`, although this a valid local port from the container that doesn't conflict , since it conflicts with the host port thats already being used for forwarding, the ui doesn't consider this new port.

3) The mapping remains unaffected

Expect mapping to have a new entry with `9223` forwarded.

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/964386/73332589-0c3c0900-421c-11ea-8989-34399d0a8918.gif)

**Comment by alexr00** [comment]
Already fixed by a949bf8de44c628b1700268b2989d932b4eb4c1e
