### ISSUE TITLE
Forwarded ports ui does not work correctly for not forwarded ports

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-remote-release#2253]
Refs https://github.com/microsoft/vscode-remote-release/issues/2208

1) Forward ports
2) `Stop Forwarding Port` on one of them
3) Add the same port thats stopped
4) Now there is no way to clear the port from `Not Forwarded` label.

![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/964386/73333368-6c33af00-421e-11ea-8416-6b9e3f31da97.gif)

**Comment by alexr00** [comment]
This is intentional. Not Forwarded ports are ports that we see that you have something listening on. Since you still have a server running on 3000 in shows under Not Forwarded.

**Comment by alexr00** [comment]
I am open to other names for "Not Forwarded" though. In the past it has been called "Candidates" but we renamed to "Not Forwarded since it was the most descriptive.

**Comment by deepak1556** [comment]
Just to confirm, in the example above  port `3000` is under both Forwarded label and Not Forwarded label , is that correct ? That was the bug I was focusing on.

**Comment by alexr00** [comment]
When you used the + next to the Not Forwarded port, you forwarded 0.0.0.0:3000 to localhost:3000. When you manually entered "3000" you forwarded localhost:3000 to localhost:3000. So it is still correct, Do you think that will be too confusing?

**Comment by deepak1556** [comment]
Oh cool, that was not immediately visible to me as pressing `+` next to the Not Forwarded port seemed like a noop, but I don't have idea on how to make this better. Maybe we can leave this as such and loop back incase more users report. Thanks!

**Comment by alexr00** [comment]
Sounds good. If we get lots of feedback that this is confusing I can add "localhost" in front of ports where it makes sense. It just seemed like it would be a lot of repeated localhost since I expect localhost to be the most common.
