### ISSUE TITLE
Backing up remote workspace/folder

### ISSUE THREAD

**Issue by joksi82** [microsoft/vscode-remote-release#2254]
Issue Type: <b>Feature Request</b>

I have a git repo cloned into docker container and I'm developing my code by attaching vscode window to container. However, sometimes my computer gets Windows updates and policy forces the reboot for the machine. Usually this destroys the running container completely and after reboot it is not anymore existing. I guess this is an issue of the docker.

However, it would be nice to have a feature in vscode to recover workspace/folder that was created inside the container to minimize the risk of losing some work in case Windows is rebooted suddenly.

Extension version: 0.94.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134

**Comment by chrmarti** [comment]
The container should still exist, it should just be stopped. (This is Docker's behavior independent of Remote-Containers.)

Do you see the container with `docker ps -a`?

**Comment by joksi82** [comment]
I did try `docker ps -a` but container was gone also from that list. In the vscode "Welcome" page container was shown in the recent projects ("folder_name [Dev Container]") but wasn't able to open container anymore either from there.

**Comment by chrmarti** [comment]
I don't know why the container would disappear. If Docker volumes are preserved you could use that to checkout your repository, or if that doesn't make it through the update you could checkout the repository locally and mount that folder with the container. (In that case it might be interesting to use a devcontainer.json that will automate creation of the container. See https://code.visualstudio.com/docs/remote/containers#_quick-start-open-an-existing-folder-in-a-container.)

Closing as this is not a problem with VS Code or the extension from what we understand.
