### ISSUE TITLE
Stopping container shows progress in view

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-remote-release#2258]
See screen shot and the two progress bars. Why does Stop Container need to show progress in the background of a modal dialog ?

![capture](https://user-images.githubusercontent.com/1931590/73360884-215c7a80-42a4-11ea-8a71-7a57db3453ed.png)

**Comment by alexr00** [comment]
I thought it made sense since you're taking action on the container. But I can see why it might be too busy.
