### ISSUE TITLE
not support for mutithread Debug

### ISSUE THREAD

**Issue by kangkang59812** [microsoft/vscode-remote-release#226]
- VSCode Version: 1.34.0-insider (1.34.0-insider)
- Local OS Version: macOS10.14.2
- Remote OS Version: ubuntu 16.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. I use pytorch's dataloader to load data.(The dataloader itself seems to use multiprecessing and num_workers !=0 , but when I set the num_workers=0 it works well. )
2. The vscode-remote use ptvsd to debug. When I use pdb to debug my code all things goes well even the num_workers !=0.
`File "/home/lkk/.vscode-remote/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/daemon.py", line 145, in start
                raise RuntimeError('already started')
            RuntimeError: already started`

Does this issue occur when you try this locally?: can't do that locally
Does this issue occur when you try this locally and all extensions are disabled?:

**Comment by egamma** [comment]
@kangkang59812 please file the issue against the vscode-python repository.

//fyi @qubitron

**Comment by qubitron** [comment]
Related to:
https://github.com/microsoft/ptvsd/issues/943

**Comment by dave-epstein** [comment]
This is happening to me too (incidentally, also with PyTorch).
