### ISSUE TITLE
The underlying connection was closed: An unexpected error occurred on a send

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#2261]
https://github.com/microsoft/vscode-remote-release/issues/78#issuecomment-571002756

Sometimes downloading the remote server on Windows fails with an error message like 

```
Failed to download & extract vscode-server. - The underlying connection was closed: An unexpected error occurred on a send.
```

Seems to be a cert issue because one user reports that the `SkipCertificateCheck` property fixes it.

**Comment by daniel-liuzzi** [comment]
This seems to be more of a protocol issue than a cert issue. On my Windows Server 2016 box `[System.Net.ServicePointManager]::SecurityProtocol` returns `Ssl3, Tls`.
[According to SSL Server Test](https://www.ssllabs.com/ssltest/analyze.html?d=update.code.visualstudio.com), _update.code.visualstudio.com_ supports **TLS 1.2 only**, which would explain the connection refused.

This can be confirmed in PowerShell by trying to connect to https://update.code.visualstudio.com/ before and after turning TSL 1.2 on:

```
> Invoke-WebRequest https://update.code.visualstudio.com/

Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a send.
At line:1 char:1
+ Invoke-WebRequest https://update.code.visualstudio.com/
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand


> [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12


> Invoke-WebRequest https://update.code.visualstudio.com/

StatusCode        : 200
StatusDescription : OK
Content           : Hello from VS Code! 👋
RawContent        : HTTP/1.1 200 OK
                    request-context: appId=cid-v1:8109e553-6232-492a-afca-b78cea9b431c
                    Strict-Transport-Security: max-age=31536000
                    X-Content-Type-Options: nosniff
                    X-Source-Commit: 5b1e6aaf6afec2feec21...
Forms             : {}
Headers           : {[request-context, appId=cid-v1:8109e553-6232-492a-afca-b78cea9b431c], [Strict-Transport-Security,
                    max-age=31536000], [X-Content-Type-Options, nosniff], [X-Source-Commit,
                    5b1e6aaf6afec2feec218a378676e943da8f7885]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : System.__ComObject
RawContentLength  : 24
```

**Comment by jsg2021** [comment]
Is there a simple way to turn it on in a persistent way?

**Comment by jsg2021** [comment]
I’m wondering if the error reported to the user could suggest the solution here?

**Comment by roblourens** [comment]
This should be fixed in the nightly extension now!

**Comment by jsg2021** [comment]
I was looking for the commits, but I can't find the code :} I guess this part isn't out in the open.

**Comment by roblourens** [comment]
Yeah the extension is not open source

**Comment by daniel-liuzzi** [comment]
Tried the latest nightly and everything works perfectly now. Thanks a low @roblourens !
