### ISSUE TITLE
Root folder in explorer does not expand to show contents

### ISSUE THREAD

**Issue by ntaylor-barnett** [microsoft/vscode-remote-release#2263]
- VSCode Version: 1.41.1
- Local OS Version: Windows 10 1709
- Remote OS Version: Debian GNU/Linux 10 (buster)
- Remote Extension/Connection Type: Docker
- Docker version: 19.03.5

A folder entry in the workspace that has its path set to the root folder dopes not expand properly. It appears in the explorer like any other, and properly changes colour to reflect the status of its children (i.e: turns red if something under it has compile errors), but expanding it shows no contents. This means that when using a dev container, I am currently unable to explore any of the files and folders in the root path that are not explicitly under one of the folders added as a workspace folder.

I believe this has happened after upgrading to the latest version of docker desktop. My other machine opening the same workspace in an older version (19.03.2) works fine. If it helps, i can upgrade my other machine to the latest docker desktop and see if it reproduces the problem, but i would like to avoid intentionally putting my other machine into an invalid state if possible.

Steps to Reproduce:

1. Open a workspace in a container
2. Add a new folder to the workspace that points to the root where the workspace exists (by either editing the workspace file and adding an entry with the path ".", or right clicking in the explorer, choosing "Add Folder to workspace" and selecting the root path)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Dump of docker version (broken state):**
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Dump of docker version (stable state):**
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by chrmarti** [comment]
Others have reported issues with the filesystem in the latest Docker version (2.2.0.0, #2193). Does downgrading Docker help?

**Comment by ntaylor-barnett** [comment]
> Others have reported issues with the filesystem in the latest Docker version (2.2.0.0, #2193). Does downgrading Docker help?

Just confirmed. Downgrading Docker Desktop to 2.1.6.1 resolves all the issues I had.

**Comment by chrmarti** [comment]
Thanks for confirming.
