### ISSUE TITLE
SSH agent forwarding broken

### ISSUE THREAD

**Issue by oxygen** [microsoft/vscode-remote-release#2264]
- VSCode Version: 1.41.1
- Local OS Version: 1903
- Remote OS Version: CentOS 7 and others
- Remote Extension/Connection Type: SSH

Entry in the SSH config used by VS Code:
```
Host some-name-of-this-host-config
  HostName some.hostname.xxx
  User root
  Port 21
  AddKeysToAgent yes
  ForwardAgent yes
```

The Visual Studio Code Remote SSH extension enables developers to work remotely on other servers.

Many teams use git over SSH (on the remote server) mostly to not have to type in passwords and to automate code pulls, etc. (git over HTTP), but more importantly for the added security through SSH Key Forwading.

Teams, or even a single developer, working on remote servers **must not** configure their private keys on the remote server as they will no longer be private (sysadmins and other developers share the same remote servers). Since SSH private keys are master keys which open many doors (in this case GitHub), this is most dangerous.

*SSH Key Forwarding is thus crucial to achieving the main goal of the VS Code SSH Remote development extension*,  otherwise security would easily be compromised (private key leaks, user and password exposure, etc.).

This issue has already been reported, confirmed by others and then closed and muted here:
[https://github.com/microsoft/vscode-remote-release/issues/1396](https://github.com/microsoft/vscode-remote-release/issues/1396)

**Comment by roblourens** [comment]
Could you share the full log from the "Remote - SSH" output channel?

![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Comment by wozniakty** [comment]
I saw this same issue occur yet again with version 50 of the extension.  Moving the extension to 49 resolves it for me, for now...

**Comment by oxygen** [comment]
BTW, most people are pageant users, instead of ssh-agent.exe
Not sure if this could be the problem for some.
