### ISSUE TITLE
devcontainer.json schema now doesn't allow any of the properties

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#2265]
For example, "name" gets a squiggle. The properties all show up with a trigger suggestions, but they all get a squiggle when entered. You can easily see this by running the python sample and opening the devcontainer.json.

**Comment by chrmarti** [comment]
Fixed with https://github.com/microsoft/vscode/commit/8046438bb13cc424399978a895530f9076a7045e.
