### ISSUE TITLE
SSH: Provide option to configure timeout on connection timedout error

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-remote-release#2266]
It would be nice to have a "configure `remote.SSH.connectTimeout`" option.

![image](https://user-images.githubusercontent.com/8586769/73479377-b9ae3a00-434c-11ea-9bd1-ed463d2cdbe6.png)
![image](https://user-images.githubusercontent.com/8586769/73479384-bf0b8480-434c-11ea-903a-9840ac75c6e8.png)

Ref #1761

**Comment by roblourens** [comment]
This setting now exists

**Comment by roblourens** [comment]
Eh, I would rather leave it for people to discover on their own. I think the number of cases where they legitimately need more than 15s to connect is probably smaller than the number of cases where this is just due to some connection issue.
