### ISSUE TITLE
[ssh] improve experience when connecting to Alpine < 2.7

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#2271]
- start alpine 2.5 with ssh as a local docker container: 
   `run docker run -d -p 2222:22 arvindr226/alpine-ssh`
- connect to the image and install the missing dependecies
   `ssh root@localhost -p 2222` (use `root` as password)
   `apk update && apk add musl libgcc libstdc++`
- Invoke `Remote - SSG: Connect to host...` with `root@localhost:2222` (use `root` as password)

A notification is shown:
`The remote host may not meet VS Code Server's prerequisites for glibc and libstdc++`

And later the server starts to fail with
```
[12:18:39.458] > Server did not start successfully. Full server log >>>
> /root/.vscode-server-insiders/bin/9e8c4c247a779cdd1f4f53db963bc6124a28ac2f/server.sh: line 12: /root/.vscode-server-insiders/bin/9e8c4c247a779cdd1f4f53db963bc6124a28ac2f/node: not found
> <<< End of server log
```

The documentation correctly mentions that Alpine 2.7 is required. But it would have been nice if the startup could give me the correct warning.

**Comment by roblourens** [comment]
What would the correct warning be, something about Alpine in particular or is 

> The remote host may not meet VS Code Server's prerequisites for glibc and libstdc++

an accurate warning?

**Comment by aeschli** [comment]
Note that in the steps, `ibgcc libstdc++` were installed. So the  message `The remote host may not meet VS Code Server's prerequisites for glibc and libstdc++` is puzzling.

I suggest to add the following sentence:
`Consult https://code.visualstudio.com/docs/remote/linux for more information`

**Comment by roblourens** [comment]
Actually, it already has a "more info" button that will take you to that link, maybe you didn't notice that.

**Comment by aeschli** [comment]
Verified in code. Couldn't verify with the original steps due to8itf vvnib8kb #4394.
