### ISSUE TITLE
SSH connection prompts for password and gets stuck

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/vscode-remote-release#2275]
- VSCode Version: 1.41.1
- Local OS Version: Windows 10 18362
- Remote OS Version: Centos 7.6
- Remote Extension/Connection Type: SSH
- Remote SSH Plugin 0.48.0

I have successfully connected to a remote Centos 7.6 host using SSH, but there are two issues:

1) I see a prompt for password in the Terminal window:

    <username>@<hostname> password:

The password appears several times, for instance when opening a folder. 

Can I stop this when using SSH?

2) The connection appears not to complete. The terminal output gets stuck at:

    webViewServerPort====
    osReleaseId==centos==
    arch==x86_64==
    webUiAccessToken====
    3753bee952a0: end

How can I fix this please?

**Comment by roblourens** [comment]
Read about ssh auth in the docs here: https://code.visualstudio.com/docs/remote/ssh#_connect-to-a-remote-host

There's nothing wrong with that log snippet that you posted. Is there another problem?
