### ISSUE TITLE
Label service has wrong path separator when using an SSH Windows remote and `remote.SSH.useLocalServer`

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#2276]
Originally found here: https://github.com/microsoft/vscode-remote-release/issues/1596#issuecomment-580738485

To repro, use the setting `remote.SSH.useLocalServer` and connect to a Windows remote with the SSH extension. Put a breakpoint in labelService.ts in `getSeparator`. Run the Open File or Open Folder command. See that '/' is returned instead of the correct Windows path separator `'\'`.

**Comment by roblourens** [comment]
Good catch!
