### ISSUE TITLE
Reinstalling server on every new insiders

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-remote-release#2278]
Complaint heard at 1ES conference:

Team has a single remote server they all Remote-SSH into for builds. Some of the team members are on insiders, but often on different versions. On each new connection, they have to wait to reinstall the server any time the previous connector was on a different version of insiders. This apparently adds up to be a lot of time waiting and they were hoping for a faster startup experience.

**Comment by roblourens** [comment]
This is in the nightly version of the extension :)

**Comment by roblourens** [comment]
I appreciate them using Insiders but this is not likely to change.
