### ISSUE TITLE
ARM64 is not supported

### ISSUE THREAD

**Issue by peter197321** [microsoft/vscode-remote-release#2279]
I'm trying to build and debug a simple C++ app (hello_world), I'm connected (ssh) to arm64 machine, I'm getting error:

![image](https://user-images.githubusercontent.com/46971586/73577650-c67e7b00-447d-11ea-8335-7f929ff40a1e.png)

"Architecture ARM64 is not supported" - how to avoid this error?

**Comment by roblourens** [comment]
Please file this on the vscode-cpptools repo. But most likely just as it says, the extension doesn't support the ARM architecture.
