### ISSUE TITLE
Cannot use docker edge on mac (unsure if also windows)

### ISSUE THREAD

**Issue by jakegt1** [microsoft/vscode-remote-release#228]
- VSCode Version: 1.34.0-Insiders
- Local OS Version: Mac OSX High Sierra
- Remote OS Version: N/A
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Install docker edge
2. Cannot connect via docker.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by abdul** [comment]
I think, it worked fine earlier (probably a couple of days after it's release). 

When I checked it earlier today, I am getting error "Docker version 17.06.1 or later required". 

The Docker for Mac is running, and I have latest version of VSCode Insider with up to date extensions.

![Screen Shot 2019-05-28 at 8 30 14 PM](https://user-images.githubusercontent.com/64568/58488713-74b38180-8187-11e9-8a21-30790ff7e98a.png)

**Docker and Machine Specs:**

![Screen Shot 2019-05-28 at 8 30 46 PM](https://user-images.githubusercontent.com/64568/58488755-8e54c900-8187-11e9-8602-1cb32dc4b6d9.png)

![Screen Shot 2019-05-28 at 8 30 36 PM](https://user-images.githubusercontent.com/64568/58488767-93197d00-8187-11e9-8fc6-01bc6450eec9.png)

**Comment by sbatten** [comment]
@jakegt1 is this still an issue?
