### ISSUE TITLE
Remote Doesn't work with Signed SSH Keys.

### ISSUE THREAD

**Issue by drpdishant** [microsoft/vscode-remote-release#2281]
- Version: 1.42.0-insider
- Local OS Version: Fedora 31 (Linux x64 5.3.14-300.fc31.x86_64)
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Configure Hashicorp Vault Server as a Secrets Management for SSH Servers
2. Get Users SSH public key signed using Vault Server
3. Store the signed ssh key to your /.ssh directory as `id_rsa-cert.pub`
4. Try connecting to the server using ssh without passing any identity file and it should be successful.
5. Configure remote server in ~/.ssh/config file with required parameters.
6. VSCode Remote Won't be able to connect to the Remote Server, whereas it works fine with ssh from terminal.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Can you explain some more, what error do you see? And can you share the log from the Remote-SSH output channel?
