### ISSUE TITLE
Remote SSH crashing VS Code extension host

### ISSUE THREAD

**Issue by altano** [microsoft/vscode-remote-release#2283]
- VSCode Version:
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0

I tested on Insiders as well.

- Local OS Version:
OS: Windows_NT x64 10.0.18362

- Remote OS Version:
Ubuntu container hosted on Proxmox. `uname -a`:
```
Linux code 5.0.21-2-pve #1 SMP PVE 5.0.21-3 (Thu, 05 Sep 2019 13:56:01 +0200) x86_64 x86_64 x86_64 GNU/Linux
```
- Remote Extension/Connection Type: SSH/Docker/WSL
Remote SSH

Steps to Reproduce:
1. Connect to host over SSH (and open a folder with a small # of files) and then wait. Will crash even if I'm idle.
1. Happens very frequently, several times an hour.
1. Remote SSH will become disconnected. It either hangs on the reconnection window or I will also get a pop-up in the lower right that says "Extension Host Terminated Unexpectedly"

I opened the log folder and the only thing I can find that looks like it is related to the crash is I see these lines leading up to the crash:
```
[2020-02-01 15:48:30.460] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode-remote.remote-ssh' took 98% of 5124.739ms, saved PROFILE here: 'C:\Users\alan\AppData\Local\Temp\exthost-da6158.cpuprofile' [{"id":"ms-vscode-remote.remote-ssh","total":5007163,"percentage":98},{"id":"program","total":116916,"percentage":2},{"id":"self","total":510,"percentage":0}]
[2020-02-01 15:48:48.521] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode-remote.remote-ssh' took 97% of 5172.403ms, saved PROFILE here: 'C:\Users\alan\AppData\Local\Temp\exthost-a4d484.cpuprofile' [{"id":"ms-vscode-remote.remote-ssh","total":5015332,"percentage":97},{"id":"program","total":156419,"percentage":3},{"id":"self","total":469,"percentage":0}]
```
Here is a random sampling of these cpuprofile files: https://files.terriblefish.com/exthost-cpuprofile-samples.zip

Does this issue occur when you try this locally?: n/a
Does this issue occur when you try this locally and all extensions are disabled?: I can't disable all extensions as this is a problem with the Remote-SSH extension

**Comment by altano** [comment]
Some more diagnostic info:

On the machine that is acting up: I have absolutely no trouble maintaining an ssh connection to the container in the Windows Terminal (using Windows' native open-ssh client), using a vanilla "ssh <host>" command. It's not a problem inherent to ssh or the host.

I have second machine with the same version of VS Code and the same settings and extensions (I use the settings syncing extension between the two). That second machine is NOT having this problem.

**Comment by roblourens** [comment]
Thanks, could you share the log from the Remote-SSH output channel as well? The perf trace makes it look like the ssh process is producing lots of output and the log should show us what the output was.

**Comment by roblourens** [comment]
Like this:
![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Comment by altano** [comment]
@roblourens is there a log file on disk that has that data? I can’t get it from the output window because to fix this failed state I have to reload the window, which makes me lose all output.

**Comment by roblourens** [comment]
Yes, run the "Open Logs Folder" command, and find it in one of the "exthost" folders

**Comment by altano** [comment]
I figured out the source of the problem: I had a large # of errors in my output b/c of some incorrect `LocalForward` directives in my ssh config. This was causing the host to crash. I don't think these should crash the extension host so if anyone wants to investigate further, this is exactly the erroneous config I had:

```
host code
    Hostname code
    User alan
    Port 22
    ForwardAgent yes
    LocalForward 127.0.0.1:3000 127.0.0.1:3000
    LocalForward 127.0.0.1:8000 127.0.0.1:8000
    LocalForward 127.0.0.1:8080 127.0.0.1:8080
```
