### ISSUE TITLE
Git clone failed. Bad configuration option: usekeychain

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-remote-release#2284]
On MacOS, `Remote-Containers: Open Repository in Container` fails if my local config has entries that linux doesn't understand. For instance, the GitHub-suggested default of:

```
Host *
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_rsa
```

Will cause the clone stage to fail with the above error.

Possibly related to work in cloning the local ssh over to the remote in #1980?

**Comment by poleguy** [comment]
I had a similar issue with git clone.
Fixeb by adding to the first line of the file:
IgnoreUnknown AddKeysToAgent,UseKeychain

Adding this under "Host *" is not effective.

**Comment by 435201823** [comment]
windows环境下没有AddKeysToAgent字段，我直接写的：
Host *
  AddKeysToAgent yes
  IdentityFile ~/.ssh/id_rsa
可以正常拉去私库。
不知道有没有替代品，暂时没查到

**Comment by chrmarti** [comment]
Is this still a problem? We no longer mount `.ssh/config` into the container.
