### ISSUE TITLE
Investigate copying known_hosts to container

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2285]
Follow-up to #1980. Related to #2284.

known_hosts or the entire .ssh should be copied.

**Comment by Chuxel** [comment]
Also might help with https://github.com/microsoft/vscode-remote-release/issues/2317 which appears to pertain to remote open repo in container scenarios.

**Comment by bhack** [comment]
We need to also better inform UX (I've tested in linux) cause if you don't have the host approved from command line it is really hard to understand this from Vscode UX failure.

**Comment by bhack** [comment]
Also we could analyze al the repository Git remotes.

**Comment by bhack** [comment]
Any news on this? the last chat was at https://github.com/microsoft/vscode-remote-release/issues/1941#issuecomment-599542605

**Comment by chrmarti** [comment]
@bhack Including this for the June milestone.

**Comment by RMacfarlane** [comment]
@chrmarti Could you post verification steps for this issue?

**Comment by chrmarti** [comment]
Verification:
- Have a workspace folder with a `.devcontainer.json`:
```json
{
  "image": "node:12"
}
```
- In a local terminal run `ssh git@github.com`.
- If you are asked to verify the authenticity of the host, please confirm (after that permission to connect is denied which is expect).
- Reopen that folder in a container.
- In the integrated terminal run `ssh git@github.com`.
- Verify that you are not asked to verify the authenticity of the host (instead permission is immediately denied).

(When you verify the authenticity of the host locally, the host is added to your `known_hosts`. We now copy that file into the container, so the same hosts are trusted.)
