### ISSUE TITLE
Stopped displaying the list of available hosts to connect

### ISSUE THREAD

**Issue by Dmitry1987** [microsoft/vscode-remote-release#2286]
Issue Type: <b>Bug</b>

Was working until last week, the list of hosts does not display.
Nothing changed, ssh_config file is the same. I tried to recreate, uninstall and reinstall, etc', the plugin just doesn't work anymore.

Extension version: 0.48.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|-psn_0_57358|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Can you explain more about where the list is missing from?

Can you share your ssh config?

**Comment by Dmitry1987** [comment]
Yeah so I had the same config, all worked fine until one day disappeared for no reason.

This is how it looks 
![image](https://user-images.githubusercontent.com/9369080/73876735-59b40980-480c-11ea-90d4-f6176bdd4c19.png)
![image](https://user-images.githubusercontent.com/9369080/73876808-77816e80-480c-11ea-913c-cd5dbcde9c4d.png)

And my config is:
```
dima@Dmitrys-MacBook-Pro ~ % cat ~/.ssh/config
# Read more about SSH config files: https://linux.die.net/man/5/ssh_config
Host runner3.aws
    HostName runner4.aws
    User devops
Host runner4.aws
    HostName runner4.aws
    User devops
Host runner5.aws
    HostName runner4.aws
    User devops
Host prometheus.aws
    HostName prometheus.aws
    User devops
Host prometheus-devops.aws
    HostName prometheus-devops.aws
    User devops
Host nginx-dev.aws
    HostName nginx-dev.aws
    User devops
Host nginx-testing.aws
    HostName nginx-testing.aws
    User devops
Host nginx-prod.aws
    HostName nginx-prod.aws
    User devops
Host nginx-devops.aws
    HostName nginx-devops.aws
    User devops
Host nginx-staging.aws
    HostName nginx-staging.aws
    User devops
Host ansible.aws
    HostName ansible.aws
    User devops

```

lol as is :D ,
 I have them all in my /etc/hosts to map to IPs.  It all worked really well I was happy about the plugin :( so convenient. I tried all other plugins afterwards but they're not good.

**Comment by Dmitry1987** [comment]
Like this, in /etc/hosts

![image](https://user-images.githubusercontent.com/9369080/73877044-d9da6f00-480c-11ea-96a2-47f4c8b93e12.png)


so all looks correct... the plugin just broke.  Can we see a debug mode logs from the plugin or VScode somehow?

**Comment by roblourens** [comment]
Hm, nothing wrong with your ssh config. Has the extension been updated to 0.49? Also, as a test can you try running the command "Connect to Host" and checking whether you see the hosts show up in that list?

**Comment by Dmitry1987** [comment]
![image](https://user-images.githubusercontent.com/9369080/73881027-76543f80-4814-11ea-858b-8d45a45b2915.png)
I have 0.48 seems... but it's latest that it shows:

![image](https://user-images.githubusercontent.com/9369080/73881125-a69bde00-4814-11ea-99dd-5ed7a0f63b1e.png)

**Comment by roblourens** [comment]
Sorry, I forgot that 0.49 requires the new version of vscode which was just released today.

**Comment by Dmitry1987** [comment]
well it still doesn't work, and I upgraded to latest of all.

**Comment by Dmitry1987** [comment]
![image](https://user-images.githubusercontent.com/9369080/74497594-fcb2f600-4e92-11ea-9b09-40fab51291de.png)
and upgraded the plugin. The list of hosts just remains empty :( .

**Comment by Dmitry1987** [comment]
oh wow, what just fixed it is deleting the ~/.ssh/config file and letting VScode recreate it
