### ISSUE TITLE
Quick pick files aren't opening the real files in WSL

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-remote-release#2290]
Notice 2 entries:

![image](https://user-images.githubusercontent.com/2193314/73680066-761b3f00-4670-11ea-8c3c-f2797c579dfc.png)

When I open the first and make a change I get 2 tabs:

![image](https://user-images.githubusercontent.com/2193314/73680093-82070100-4670-11ea-9223-bab42b644965.png)

I'm assuming this is a problem with the WSL extension as I don't see it in local. It could also be an issue with the quick pick as opening from the explorer doesn't show this behavior.

**Comment by aeschli** [comment]
The WSL extension is just about starting the remote server. So likely what you see is a remote issue.
Can you add more details about the setup so I can reproduce this?

**Comment by Tyriar** [comment]
I had this repo opened https://github.com/Tyriar/xterm.js and it's on Windows slow insiders ring WSL2 Debian I believe. Any other details you're looking for?

**Comment by aeschli** [comment]
I tried to reproduce, but didn't get the two entries.
Do you still see this?
