### ISSUE TITLE
Remote SSH error when searching (spawn ENOENT)

### ISSUE THREAD

**Issue by bilby91** [microsoft/vscode-remote-release#2291]
When trying to search a for a file that was not previously opened by manually selecting it, I'm getting the following error:

```
spawn /home/bilby91/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/node\_modules/vscode-ripgrep/bin/rg ENOENT
```

I have confirmed that the file exists and it is owned by the same user that runs the vs-code process remotely.

- VSCode Version: 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0)
- Local OS Version: macOS 10.15.1
- Remote OS Version: 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Remote Extension/Connection Type: SSH/Docker/WSL: SSH

Steps to Reproduce:

1. Open remote workspace
2. Find a file that was not opened previously using CMD + P

**Comment by roblourens** [comment]
Can you check whether that file exists? It's possible that the remote server is not fully installed for some reason. Also I don't know why there is a backslash in front of the underscore but that shouldn't be necessary.

**Comment by bilby91** [comment]
@roblourens Thanks for the quick response!

I did mention the following:

```
I have confirmed that the file exists and it is owned by the same user that runs the vs-code process remotely.
```

I've attempted deleting the `~/.vs-code/bin` and let the setup piece recreate everything but still same issue. Everything else seems to be working fine.

**Comment by roblourens** [comment]
Oops, thanks. 
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by bilby91** [comment]
@roblourens Hey, just tried the insiders build and I have the same issue

**Comment by roblourens** [comment]
Oh, is it possible that you have a folder in your workspace that doesn't exist?

**Comment by bilby91** [comment]
@roblourens It was a missing directory on my workspace!

Maybe this error message can be improved ? 

Thanks
