### ISSUE TITLE
Local user settings not applying on ssh host

### ISSUE THREAD

**Issue by ivirshup** [microsoft/vscode-remote-release#2293]
Issue Type: <b>Bug</b>

My local user settings are not applying when editing on a server over ssh, contrary to [the documentation](https://code.visualstudio.com/docs/remote/ssh#_ssh-hostspecific-settings).

For example, key-binds are different on the remote server. Styling seems the same. In the settings for the server, settings are marked as "Modified in: User", though that does not seem to apply.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/8238804/73711547-501e9900-475b-11ea-92ce-1993be400d1a.png">

<img width="736" alt="image" src="https://user-images.githubusercontent.com/8238804/73711551-557be380-475b-11ea-833f-f1c921d4e22a.png">

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.3.0
Remote OS version: Linux x64 4.18.0-80.11.2.el8_0.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|64.00GB (43.40GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: gadi|
|OS|Linux x64 4.18.0-80.11.2.el8_0.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8268 CPU @ 2.90GHz (48 x 1200)|
|Memory (System)|250.29GB (32.83GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
language-cython|guy|0.0.6
theme-monokai-pro-vscode|mon|1.1.14
vscode-apache|mrm|1.2.0
vscode-docker|ms-|0.10.0
remote-containers|ms-|0.94.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.41.9
vscode-remote-extensionpack|ms-|0.19.0
python|ms-|2020.1.58038

</details>

**Comment by roblourens** [comment]
The effective setting will be the User one in this case because it is not modified in the Remote-specific settings. That's just saying that it's not overridden for that remote specifically.
