### ISSUE TITLE
Open window on client from terminal on server via SSH

### ISSUE THREAD

**Issue by iAbadia** [microsoft/vscode-remote-release#2299]
I love how when using VSCode Remote Development with WSL I can type `code .` on the WSL instance and a window opens on my Windows VSCode client. Would this be possible somehow when using SSH?

**Comment by roblourens** [comment]
It is possible in the integrated terminal in vscode when that window is already in a remote session, but not from another terminal - we have no way to reach back to your local machine and run code.
