### ISSUE TITLE
Cannot install on v1.33.1

### ISSUE THREAD

**Issue by OliElli** [Microsoft/vscode-remote-release#23]
- VSCode Version: 1.33.1 (user setup)
- Local OS Version: Windows 10
- Remote OS Version: N/A
- Remote Extension/Connection Type: All

Steps to Reproduce:
1. Have VS Code v1.33.1
2. Try to install ms-vscode-remote.vscode-remote-extensionpack or any of it's members

Error received when installing via VS Code marketplace:
"Unable to install because, the extension 'ms-vscode-remote.vscode-remote-extensionpack' compatible with current version '1.33.1' of VS Code is not found."

**Comment by Tyriar** [comment]
This is correct, you can only use the extensions on the Insiders build as per https://code.visualstudio.com/blogs/2019/05/02/remote-development
