### ISSUE TITLE
No link detection for Dockerfile in devcontainer.json when in container

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#2304]
Repro steps:
Open the container sample Azure Functions Node & 8
Reopen in container
Open the devcontainer.json file
Expected: Dockerfile has an underline and is a link
Actual: ctrl+click doesn't do anything. Dockerfile isn't underlined and isn't a link
![image](https://user-images.githubusercontent.com/38270282/73923838-cb06c180-48cb-11ea-80f5-32ff8146baea.png)

**Comment by chrmarti** [comment]
Still an issue on Windows. (Works on Mac.)

**Comment by chrmarti** [comment]
Working now. Thanks.
