### ISSUE TITLE
bad pathname in problems tab

### ISSUE THREAD

**Issue by ryan-jonesford** [microsoft/vscode-remote-release#2307]
Issue Type: <b>Bug</b>

When running the debugger (gdb) It found that I had an error and on the problems tab it has my file listed with the error information. When I click the file I get an error that says it cannot be opened because it doesn't exist. So I have it create the file and the path to the file is repeated.
example.
My file path - /home/me/main.cc
file path that gets created - /home/me/home/me/main.cc

Windows host, linux dev machine

launch.json file contains:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "enter program name, for example ${workspaceFolder}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

Extension version: 0.19.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 3.10.0-327.el7.x86_64
Remote OS version: Linux x64 3.10.0-327.el7.x86_64
Remote OS version: Linux x64 3.10.0-327.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: jonesfrm-rtc.projects.sys|
|OS|Linux x64 3.10.0-327.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (4 x 1995)|
|Memory (System)|7.64GB (0.37GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: jonesfrm-rtc.projects.sys|
|OS|Linux x64 3.10.0-327.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (4 x 1995)|
|Memory (System)|7.64GB (0.37GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: jonesfrm-rtc.projects.sys|
|OS|Linux x64 3.10.0-327.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (4 x 1995)|
|Memory (System)|7.64GB (0.37GB free)|
|VM|100%|
</details>

**Comment by egamma** [comment]
This looks like an issue of the C++ extension, pls report the issue against this extension.
