### ISSUE TITLE
Handle Proxy Issues on Remote 

### ISSUE THREAD

**Issue by modbw** [microsoft/vscode-remote-release#231]
- VSCode Version: 1.34.0-insiders (user setup)
- Local OS Version: Windows 10 1703 Enterprise
- Remote OS Version: Debian GNU/Linux 8
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Create a remote SSH session
2. Try to install any extension (tested ms-vscode.cpptools, cschlosser.doxdocgen, twxs.cmake)

![image](https://user-images.githubusercontent.com/4498104/57370764-2ebf5b00-7191-11e9-938b-7f36c720cdae.png)

After creating the remote connection I try to install an extension which results in the above notifications.

**Comment by modbw** [comment]
```
[2019-05-08 13:00:53.810] [remoteagent] [info] Scanned user extensions: 0\n
[2019-05-09 07:49:47.892] [remoteagent] [info] Scanning extensions using UI language: en
[2019-05-09 07:49:47.914] [remoteagent] [info] Scanned user extensions: 0
[2019-05-09 07:49:47.919] [remoteagent] [info] Scanned user extensions: 0
[2019-05-09 07:49:47.928] [remoteagent] [info] Scanned user extensions: 0
[2019-05-09 07:49:47.996] [remoteagent] [info] Scanned system extensions: 24
[2019-05-09 07:49:48.002] [remoteagent] [info] Scanned system extensions: 24
[2019-05-09 07:49:48.680] [remoteagent] [info] Scanned user extensions: 0
[2019-05-09 07:50:06.412] [remoteagent] [info] Scanned user extensions: 0
[2019-05-09 07:50:06.414] [remoteagent] [info] Scanned user extensions: 0
[2019-05-09 07:50:06.428] [remoteagent] [info] Scanned system extensions: 24
[2019-05-09 07:50:06.537] [remoteagent] [info] Scanned user extensions: 0
[2019-05-09 07:50:06.552] [remoteagent] [info] Scanned system extensions: 24
[2019-05-09 07:50:17.597] [remoteagent] [info] Installing extension: twxs.cmake
[2019-05-09 07:50:17.793] [remoteagent] [info] Scanned user extensions: 0
[2019-05-09 07:50:18.297] [remoteagent] [error] Failed to install extension: twxs.cmake unable to verify the first certificate ```

Seems to be a certificate problem with our company proxy. Is it possible to disable certificate checking for VSCode remote extension installing?

**Comment by sandy081** [comment]
Yeah this is known proxy issues and above settings will not help on remote. 

@chrmarti How can we handle the proxy issues on remote given that we do not have access to electron?

**Comment by chrmarti** [comment]
Certificates should be picked up from the remote OS. One issue is that the remote extension host picks up the proxy configuration from the host OS (#213).

@modbw Do you have all relevant certificates installed on the remote machine you SSH into?

**Comment by modbw** [comment]
@chrmarti Certificates should be installed OK as tests with curl and wget shows. If there is anything I can test additionally let me know.

**Comment by chrmarti** [comment]
@sandy081 Then we don't load the credentials from the OS. Wouldn't that be the same with the local extension management? We should look into bringing that on par with the extension hosts.

**Comment by sandy081** [comment]
Local extensions management is an electron process which uses chromium network stack. We cannot bring them on par unless we also use electron on remote which we do not want. 

Other solution which is in the plate from beginning is to stream installation from local to remote. It means download it on renderer and stream it to remote.

**Comment by chrmarti** [comment]
Got it. So one other direction would be to reuse the proxy and certificates code I've written for the extension host in proxyResolver.ts for the remote extension management.

**Comment by sandy081** [comment]
yeah makes sense

**Comment by aldanor** [comment]
Same problem here; company proxy with internal certificates, leading to a 'unable to get local issuer certificate'. Would be nice if it was possible to configure this properly for the remote side (both the proxy and certs, in case they can't be properly picked up automatically). Plus, an option to ignore certificate validation for the remote side.

**Comment by EmbeddedBacon** [comment]
Recently update to VSCode 1.35.0.  Attempted to install a few extensions as noted by other users.  I am running VSCode on Windows 10 and ssh into a CentOS box.  I do have the proxy configuration (i.e., "http:proxy" set so extension, mainly CPP Tools, can be installed properly.  Would it be possible for VSCode to picked up the proxy, if set, on the local side and use them on the connecting side?

**Comment by EmbeddedBacon** [comment]
Perhaps outside the scope of this item, but will VSCode be able to install the extension I enabled on the host side (local) to the remote side automagically?  I am wondering if I will need to install the extension each time connecting to the remote machine.  I am not sure this is the case since I can't install any extensions at the moment.

**Comment by kmalloc** [comment]
same problem here with 1.35.0, extension for remote can not be installed.

![image](https://user-images.githubusercontent.com/2180606/59187257-a37a2080-8ba7-11e9-92cc-9d8789eb28fa.png)

my remote host is behind a proxy.

**Comment by EmbeddedBacon** [comment]
I know this topic is close, but VSCode 1.36 just came out and Remote-SSH also updated.  I retried setting up a remote editing session then tried to install the C/C++ extension.  It did download and install correctly.  Even went through the C/C++ insiders updating.  Thanks for getting this to work.  Now, just need to start editing files and see if the rest of it works.

```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux / x86_64)' (8529 KB)  Done!
Downloading package 'ClangFormat (Linux / x86_64)' (812 KB)  Done!
Downloading package 'Mono Framework Assemblies' (5368 KB)  Done!
Downloading package 'Mono Runtime (Linux / x86_64)' (1862 KB)  Done!

Installing package 'C/C++ language components (Linux / x86_64)'
Installing package 'ClangFormat (Linux / x86_64)'
Installing package 'Mono Framework Assemblies'
Installing package 'Mono Runtime (Linux / x86_64)'

Finished installing dependencies

IntelliSense Engine = Tag Parser.
Autocomplete is enabled.
Error squiggles are enabled if all header dependencies are resolved.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
Code browsing service initialized
  Folder: /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include/ will be indexed
```

**Comment by kmalloc** [comment]
I am still experiencing the same issue after upgraded to 1.36, remote-ssh:0.44

![image](https://user-images.githubusercontent.com/2180606/60707438-58e98b00-9f3e-11e9-8d20-a8f5129550ce.png)

![image](https://user-images.githubusercontent.com/2180606/60707456-6141c600-9f3e-11e9-9f57-8842f1eb6776.png)

**Comment by sandy081** [comment]
This issue is about downloading extensions and what you are seeing is downloading the server. Can you please file a separate issue and let us know which remote extension are you using?

**Comment by heiwais25** [comment]
@kmalloc In my case, I could solve that issue by adding `http_proxy` in the `~/.wgetrc` file in the server. What I did in the `~/.wgetrc` is like this.
```
user_proxy=on
http_proxy=<proxy address>
https_proxy=<proxy address>
ftp_proxy=<proxy address>
```
I hope it could help you
