### ISSUE TITLE
Handshake failed: no matching key exchange algorithm

### ISSUE THREAD

**Issue by Yangff** [microsoft/vscode-remote-release#2314]
- VSCode Version: 1.43.0-insider
- Local OS Version: 10.0.18362
- Remote OS Version: Ubuntu 18.04.3
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Set `docker.host` in `settings.json`
2. Try to connect to remote container
3. These error messages show up in devtools

"Handshake failed: no matching key exchange algorithm"
![Snipaste_2020-02-07_12-41-35](https://user-images.githubusercontent.com/1381921/74056238-38d3eb80-49a7-11ea-9298-7c0545f1db85.png)

However, I'm able to connect to remote via ssh or docker directly. 

Also, remote ssh works properly. 

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

```
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
```

/etc/ssh/sshd_config
```
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
```

**Comment by chrmarti** [comment]
@Yangff Not an expert on key exchange algorithms, maybe yours doesn't match any of the defaults here: https://www.npmjs.com/package/ssh2-streams ?

**Comment by Yangff** [comment]
@chrmarti 
yes.. it doesn't match any of these.

**Comment by chrmarti** [comment]
Are the supported ones not strong enough or why is there no overlap between the two sets?

**Comment by Yangff** [comment]
@chrmarti I don't know who make such configuration on the server.. I'm just an user. 
I find some clues.. I mean maybe some administrators read articles like this one https://stribika.github.io/2015/01/04/secure-secure-shell.html and decide to disable all other key exchange algorithms...

**Comment by chrmarti** [comment]
It looks like you would need ssh2-streams to support additional key algorithms by default. Could you open an issue for them here: https://github.com/mscdex/ssh2-streams?

**Comment by Yangff** [comment]
Seems like they already has a PR for that https://github.com/mscdex/ssh2-streams/pull/141
And I also created a new one https://github.com/mscdex/ssh2-streams/pull/149

**Comment by Yangff** [comment]
@chrmarti It's supported in https://github.com/mscdex/ssh2-streams/releases/tag/v0.4.9 this version.

**Comment by chrmarti** [comment]
We no longer use Dockerode and with that ssh2-streams. Closing.
