### ISSUE TITLE
Can no longer forward to port 80 as it is in use (apparently)?

### ISSUE THREAD

**Issue by njbmartin** [microsoft/vscode-remote-release#2315]
Issue Type: <b>Bug</b>

Since updating to the latest version of VS Code, I can no longer forward to port 80. Not entirely sure why this would be the case...

Extension version: 0.101.0
VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:33.119Z)
OS version: Darwin x64 19.3.0
Remote OS version: Linux x64 4.19.76-linuxkit
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 2, 1|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js (latest LTS)|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|5.81GB (4.48GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js (latest LTS)|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|5.81GB (4.48GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Please give more info. Probably that port is actually in use? Try `lsof -i :80` to see which process is using it.

**Comment by njbmartin** [comment]
Not sure what else I can give you other than it _used_ to work just fine until I updated to the latest VS Code. I tried many things to work out whether the port was in use, and came to the conclusion that it wasn't in use. `lsof -i :80` doesn't show anything listening.

Background:
If I click on a link in the terminal to a web server running inside the dev container, it will automatically forward the port if available, or assign a random port (I love this feature).

This works as expected, except for port 80. If I go to the Remote Explorer and try to change to local port to 80 I get an error "The local port 80 is not available. Port number xxxxx has been used instead".

Annoyingly, if I run `docker run -p 80:80 nginx` it uses port 80 just fine.

So, it's definitely not in use.

**Comment by roblourens** [comment]
Ok, we did change how port forwarding works in the last extension update, but actually I think you need to be admin to open ports that are < 1024, and I just checked that we were enforcing that before too... how were you forwarding the port before?

**Comment by njbmartin** [comment]
_it just worked_. In all honesty, I wasn't doing anything special. No elevated priveledges etc.

**Comment by roblourens** [comment]
I looked into this some more. The restriction that I was thinking of is only for the Remote-SSH extension, not the Container one that you are using.

@alexr00 does the new remote explorer block using ports of <1024? I think you need to be admin for that on Windows but not Linux. Or do you have another idea?

**Comment by alexr00** [comment]
The remote explorer doesn't block any port number. If your system requires admin then it should simple pick another available port. @njbmartin are you seeing a different available port get picked?

**Comment by roblourens** [comment]
Yes sounds like it's using another port, @njbmartin can you forward to other low ports besides 80?

**Comment by njbmartin** [comment]
I can't forward to any ports below 1024, as you suggested. But I'd like to stress that before I updated to the latest VS code, it worked just fine.

**Comment by alexr00** [comment]
I wonder if this is because for containers the host was always 127.0.0.1, but now we don't specify a hostname so it uses 0.0.0.0. I'll try that out in March and see if we can switch to use localhost.

**Comment by mic-hnk** [comment]
The same happens to me. No forwarded port can be set to local port < 1024. Instead, they are forwarded to a random port. Nothing is using affected local ports.

VS Code Version: 1.42.1
Remote Development extension Version: 0.19.0
Remote - SSH Version: 0.49.0

**Comment by alexr00** [comment]
I tried out https://github.com/microsoft/vscode-remote-release/issues/2315#issuecomment-592486497, but it didn't help anything. Will consider revising later.

**Comment by nadar** [comment]
When working with a reverse proxy, which is commonly running on port 80, it would be very convenient to map port 80

**Comment by PatoBeltran** [comment]
I'm facing this same issue with port 443. 

I have a server running windows where I have docker and a web app configured to use ssl. I also have a windows client (laptop) that I use to connect with the ssh vscode extension. Using my windows machine, when I forward port 443 it works fine to assign local 443 to remote 443. In my Mac client, however, when I try forwarding port 443 it doesn't allow me (it does the same for any port < 1024) and just asking a random one to forward to remote 443.

In my case, since the app is configured with custom local domains I need it to be 443 in my local as well, which makes it so that I cannot use my Mac to test using this method.

**Comment by alexr00** [comment]
Would be solved by https://github.com/microsoft/vscode-remote-release/issues/3922
