### ISSUE TITLE
Remote SSH feature request: Keep remote server and terminal sessions running after disconnect

### ISSUE THREAD

**Issue by jlynchMicron** [microsoft/vscode-remote-release#2316]
Would it be possible to add a feature where you could set a time limit for keeping a remote workspace session running, even after a network disconnect?  There have been a number of times where I have either hopped between wifi connections or disconnected and reconnected after some time has passed, and all my terminal sessions attached to a workspace have been lost.  I think it would be a nice feature to have a persistence option for remote workspaces so you do not have to re-setup the terminal session you had before a disconnect.

**Comment by roblourens** [comment]
We actually do try to do this, with a timeout of up to 3 hours. Are you disconnected for longer than 3 hours, or is it failing to reconnect within that time frame?

**Comment by jlynchMicron** [comment]
I have never measured it before, but it could be a time frame like that.  Would it be possible to have an option to let the user pick how long that time period would be?  It would be nice to be able to set that period to like 3 days so your session will last over the weekend when you are not at work and your laptop is powered off.

**Comment by roblourens** [comment]
We have https://github.com/microsoft/vscode-remote-release/issues/1701 for this feature request
