### ISSUE TITLE
~/.ssh and docker.sock should not be mounted by default into devcontainer 

### ISSUE THREAD

**Issue by hholst80** [microsoft/vscode-remote-release#2317]
- VSCode Version: 1.43.0-insider
- Local OS Version:  Windows 10 1903
- Remote OS Version: Arch
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Setup Docker to use a remote Docker Engine server by specifying `DOCKER_HOST=tcp://remote.local:2376`, `DOCKER_TLS_VERIFY=1` and `DOCKER_CERT_PATH=C:/users/user/.machine/machines/remote`
2. Open any devcontainer repository in container

![image](https://user-images.githubusercontent.com/6200749/74085852-ae11f000-4a7d-11ea-98b5-ac67e6ab5336.png)

(note that on this machine my username randomly is "henri")

Obviously, the mounts are wrong. Nothing from the local machine should be mounted into the cointainer. TBH I do not know why anything related to docker engine is attempted to be installed into a development container, by default.

**Comment by hholst80** [comment]
The error is the same if I first connect via a Remote-SSH to the host where dockerd is running. It is not possible to use a remote docker engine for development as-is. Blocker or known workaround?

**Comment by chrmarti** [comment]
This is done for a temporary container that needs to clone the repository and build the DevContainer's image.

Cloning might need ssh and  building the image requires the Docker daemon.

Using this issue to track the temporary container. #2285 is tracking the DevContainer's part.

**Comment by connor4312** [comment]
@chrmarti can you add verification steps?

**Comment by chrmarti** [comment]
@hholst80 Since this is a very specific setup, could you install the latest version the Remote-Containers extension (0.106.0) in VS Code Insiders and check if the problem is fixed?

**Comment by hholst80** [comment]
This is a standard workflow with docker machine. If you reference the fix PR I will evaluate.

**Comment by chrmarti** [comment]
This is currently closed source. Please see https://code.visualstudio.com/docs/remote/faq#_license-and-privacy for the details.

**Comment by bhack** [comment]
@chrmarti Any new about modularization? At https://code.visualstudio.com/docs/remote/faq#_why-arent-the-remote-development-extensions-or-their-components-open-source seems that there is some space to opensource some components.

**Comment by chrmarti** [comment]
@bhack I'm not aware of any work in that direction.

**Comment by bhack** [comment]
@chrmarti It would have given a little scalability to the repository. After months you're a bit inundated with the combinatorics explosion of configurations setup and use edge use cases fix without any community PR support.

**Comment by hholst80** [comment]
OK. I wasn't aware. In any way the problem is sort of still there. It will allow me to push, but it has disabled my cache settings. I am not happy about that.

```
$ git push                                                      
Remote-Containers CLI: RPC pipe not configured. Message: {"command":"fill","stdin":"protocol=https\nhost=github.com\n"}
Username for 'https://github.com': hholst80
Password for 'https://hholst80@github.com': 
Remote-Containers CLI: RPC pipe not configured. Message: {"command":"approve","stdin":"protocol=https\nhost=github.com\nusername=hholst80\npassword=CLEARTEXT\n"}
Enumerating objects: 34, done.
Counting objects: 100% (28/28), done.
Delta compression using up to 8 threads
Compressing objects: 100% (16/16), done.
Writing objects: 100% (16/16), 1.62 KiB | 1.62 MiB/s, done.
Total 16 (delta 12), reused 0 (delta 0)
remote: Resolving deltas: 100% (12/12), completed with 9 local objects.
To https://github.com/X/Y.git
   a98d2c6..5371865  master -> master
```
