### ISSUE TITLE
Docker entrypoint not used

### ISSUE THREAD

**Issue by alexpearce** [microsoft/vscode-remote-release#232]
- VSCode Version: 1.34.0-insider, daf71423252a707b8e396e8afa8102b717f8213b
- Local OS Version: Arch rolling
- Remote OS Version: CentOS 7
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Define a Dockerfile with an `ENTRYPOINT` command, e.g.
```docker
FROM debian

COPY entrypoint.sh /etc/entrypoint.sh

ENTRYPOINT ["/etc/entrypoint.sh"]
CMD "bash"
```
with entrypoint script:
```bash
#!/usr/bin/env bash

echo 'Entrypoint running'

export ENTRYPOINT_RUN=1

exec "$@"
```
2. Build the image, run a container, and attach to it in VS Code.
3. Observe how none of the commands executed in the image run the entrypoint script (e.g. open a terminal in VS Code and `echo $ENTRYPOINT_RUN`).

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

---

From what I can tell, 'attaching' to the container means executing commands with `docker exec <container ID> <command>`. So, this is arguably a limitation of `docker exec` which does not run via the entrypoint (only `docker run` does). But, I opened this to see if people have ideas about workarounds.

My entrypoint scripts sets up the environment for the user running in the container, e.g. creating a user and group with the same UID and GID as the host user, and setting some PATHs. I can move most of this to a `bash_profile` or `bashrc`, but I'd have the same symptoms: `docker exec` doesn't run commands through the shell.

One idea: add an `entrypoint` key to `devcontainer.json` to allow an entrypoint to be specified. That is: rather than using `docker exec <container ID> sh -c "<command>"` as is done now, allow for `docker exec <container ID> <entrypoint script> <command>`.

**Comment by chrmarti** [comment]
devcontainer.json supports a `"postCreateCommand"` command that is run once per container. Does that help in your case?

**Comment by alexpearce** [comment]
Thanks a lot for the feedback!

> devcontainer.json supports a "postCreateCommand" command that is run once per container. Does that help in your case?

I didn't think I could use `devcontainer.json` when attaching to an already-running container. Can I? I tried this definition but it isn't valid (missing `dockerFile`)

```json
{
	"name": "LHCb",
	"extensions": [],
	"postCreateCommand": [
		"ls"
	]
}
```

If I can, I think I'd have the same symptoms. I guess the `postCreateCommand` would be run by VS Code in the attached container like this:

```
docker exec <container ID> <postCreateCommand>
```

and then subsequent commands are run as usual, i.e.

```
docker exec <container ID> <command>
```

The issue remains that the `<command>` is not run through the `ENTRYPOINT` of the container (nor of the shell of the user running in the container).

**Comment by chrmarti** [comment]
The devcontainer.json is not supported when attaching to a container. Let's use this issue to track your request. We would probably not reuse `ENTRYPOINT`, but this needs more thought first.
