### ISSUE TITLE
remote-ssh: cannot remove bad host

### ISSUE THREAD

**Issue by mdegans** [microsoft/vscode-remote-release#2320]
I made a typo in adding a host so that I was trying to connect with key authentication with a user that didn't exist. There seems to be no easy way to remove a bad configuration (right click only hast "connect to host...".

I was able to add a user (with a typo) to the remote host, add my pubkey to that user's authorized_keys, and successfully log in, but "Uninstall" from the f1 search didn't work for me even then. The host remains in the list. Is there only one user per host?

I feel it should be easier to edit or remove incorrect configurations, even if this would leave the remote host with some stale software installed. As it is, I am blocked from adding a correct configuration by the typo I made initially with no obvious way I can see to fix it.

**Comment by mdegans** [comment]
I was actually able to resolve this by editing the config file to remove the incorrect user, however it might be nice to have menu options for this, as well as support for multiple users per host.

**Comment by hholst80** [comment]
For future reference you can always edit your ssh_config. This is the source of truth for the remote ssh hosts in VS code.
![image](https://user-images.githubusercontent.com/6200749/74098778-321ab500-4b1c-11ea-9fe5-b17f240b4f5f.png)
![image](https://user-images.githubusercontent.com/6200749/74098789-5bd3dc00-4b1c-11ea-955c-b1a2bb9b18f3.png)

**Comment by mdegans** [comment]
Thanks. I wasn't clear that's what was going on, but now it makes sense. Still, an option to remove a host might be nice. At this point this issue might be considered more of a feature request, I suppose, so i'm closing it.
