### ISSUE TITLE
Support ${workspaceFolder}

### ISSUE THREAD

**Issue by hholst80** [microsoft/vscode-remote-release#2322]
Currently, only `${localWorkspaceFolder}` is supported in `devcontainer.json`. I would need also to know where the container workspace is provisioned in order to mount up the data folder. For specific local development, in a non-docker workflow, external data is always available in the `data` directory relative to where the program is located. As it is not possible to mount a directory relative to the workdir inside a docker container this causes some challenges. I consider the external data to be configuration and the application code should not be concerned if it is running inside a docker container or not.

Use case:

```
{
    "name": "Package",
    "dockerFile": "Dockerfile",
    "appPort": [8888],
    "runArgs": ["--network=dev", "--volume=dev-data:${workspaceFolder}/data"],
    "settings": {
        "terminal.integrated.shell.linux": "/bin/bash"
    },
}
```

**Comment by hholst80** [comment]
There is a potential recursion / dependency issue in the fact that the variable itself can be set in the json. Going forward this might no be the best way to implement it. Any feedback from other users?

**Comment by Chuxel** [comment]
@hholst80 Currently the mount path is automatically determined based on the location of the git root to ensure git operations work.  However, you can specify the folder that the workspace mounts into as follows:

```json
"workspaceMount": "source=${localWorkspaceFolder},target=/workspace,type=bind,consistency=delegated",
"workspaceFolder": "/workspace"
```

You can then mount things under `/workspace` as appropriate using either the `mounts` or `runArgs` properties.

That should resolve your issue, correct?

**Comment by hholst80** [comment]
That was not the issue to mount the git dir. I had a docker volume for the data that was to be mounted on top of the git mount. No matter, I have discontinued devcontainer.json workflow and I am now using docker-compose directly with the >Remote attach workflow as that supports most of the odd and unsual things I'm apparently doing. ;-)
