### ISSUE TITLE
Wrong username on SSH connection

### ISSUE THREAD

**Issue by snakuzzo** [microsoft/vscode-remote-release#2326]
- VSCode Version: 1.4.2
- Local OS Version: Ubuntu 19.10
- Remote OS Version: Raspbian 10
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Setting up a new connection
2. Try to connect

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

I'm trying to connect to my RaspberryPi using Remote SSH extension.
This is my /home/snakuzzo/.ssh/config

```
Host mydoman.duckdns.org:8444
  HostName mydoman.duckdns.org
  User pi
```
When I try the connection it uses my local username (snakuzzo) and not specified username...and the connection fails.
On my macOS everything works fine, using same extension on Ubuntu not.

Thanks

**Comment by roblourens** [comment]
If you run `ssh 'mydoman.duckdns.org:8444'` in an external terminal does it work? 

Also if you mean to connect to a different port, you will need to change that to add `Port 8444` to the config.

**Comment by snakuzzo** [comment]
If I try to connect by terminal...it works.

If I try `ssh pi@mydomain.duckdns.org -p8444` using this config...

```
Host mydomain.duckdns.org:8444
  HostName mydomain.duckdns.org
  User pi
```

...it works

If I try to change my config file like this....

```
Host mydomain.duckdns.org
  HostName mydomain.duckdns.org
  User pi
  Port: 8444
```
...and try to connect by terminal it doesn't work...

```
snakuzzo@SnakuzzoWork:~$ ssh pi@mydomain.duckdns.org -p8444
/home/snakuzzo/.ssh/config: line 4: Bad configuration option: port:
/home/snakuzzo/.ssh/config: terminating, 1 bad configuration options
```

It's not a connectivity problem...the problem is that the extension take my local username and not username `pi` specified in my config file

![image](https://user-images.githubusercontent.com/7205371/74165014-cbcd8980-4c24-11ea-9537-636cb5315101.png)

**Comment by roblourens** [comment]
In your first example, you are not using the config file because you have provided the username and port on the command line. In your second example, your config is incorrect because there should be no `:` after Port, just like the error says.

**Comment by snakuzzo** [comment]
I know everything...it was just to answer to your message. Look at the first config. That's the right config I'm using and the result is the screenshot. So...
With this config...

```
Host mydomain.duckdns.org:8444
  HostName mydomain.duckdns.org
  User pi
```
I have the "screenshot problem".  Look at the username

**Comment by roblourens** [comment]
Sure but all the ssh extension does is literally run ssh with the host that you give it. `ssh mydomain.duckdns.org:8444`. If ssh doesn't find an ssh config for that, it uses your local user name, which is what you are seeing. So either the config file is in the wrong place or there is something wrong with the config.

**Comment by snakuzzo** [comment]
On macOS I have same configuration and it works fine. On Ubuntu not

**Comment by mwinters-stuff** [comment]
I just started having the same problem on ubuntu, connecting on the command line didnt work - what I did was specify the port number in the config..

Prior config
```
Host localhost:2222
  HostName localhost
  User mathew
```

```
> ssh localhost -p 2222
mwinters@localhost's password:
```

Changed config
```
Host localhost
  HostName localhost
  User mathew
  Port 2222
```

```
> ssh localhost -p 2222
mathew@localhost's password:
```

Now VS Code works too.

**Comment by snakuzzo** [comment]
As yoi can see in my previous posts, I also tried your solution, but it didn't worked

**Comment by roblourens** [comment]
@snakuzzo I don't see where you tried that exact thing. And like I said, all we do is run a simple ssh command with no ssh option arguments, so if you can get that to work, then vscode should work as well.

**Comment by snakuzzo** [comment]
Just to update...this mortning I tried again using this configuration...

```
Host mydomain.duckdns.org
  HostName mydomain.duckdns.org
  User pi
  Port: 8444
```

After some tries it worked. I don't know why same configuration initially went wrong and now it's ok.

Thank you for your patience

**Comment by roblourens** [comment]
I'm glad it's working but I still think you need to remove the `:` after Port :)

**Comment by snakuzzo** [comment]
You're right!
My fault!
