### ISSUE TITLE
cannot install cpptools-extension in remote-ssh host

### ISSUE THREAD

**Issue by davidwangd** [microsoft/vscode-remote-release#2327]
- VSCode Version: 1.42
- OS Version: Windows10 version 19041

Steps to Reproduce:

1. start vscode and connect to any remote-ssh(i've tried four remote connections and this problem occured on every remote host)
2. try to install the c++ Intellisense extension
3. it will report network connection error and some other extensions such as python and cmake-tools will be installed finely.
5. This is not quite a big problem since I still can install the extension via vsix. But i still hope this problem get fixed.

Does this issue occur when all extensions are disabled?:  No

**Comment by sandy081** [comment]
Can you please provide
Please follow these steps

- please share the logs from the following locations
    - View -> Open View… -> Log (Remote)
    - View -> Open View… -> Log (Window)

**Comment by davidwangd** [comment]
I had been trying to uninstall the extension which installed via vsix and re-install it to repeat the error but it did not appeared. Since currently i have no more remote host to test. i may not be able to provide the log. Sorry for disturbing. I will close this issue and reopen when the error occurs again. hope not :)
