### ISSUE TITLE
Why does my remote development on VS code opens the check remote option by itself?

### ISSUE THREAD

**Issue by brando90** [microsoft/vscode-remote-release#2330]
My VS code integrated terminal changes by itself to "check remote" eventually once I am connected to a remote. Why is it doing that and how do I stop it?

e.g. see image to understand what I mean:

Image of what it looks like:

![Screen Shot 2020-02-10 at 10 37 43 AM](https://user-images.githubusercontent.com/1855278/74169831-90fe2e00-4bf1-11ea-9cf0-53512056c9b8.png)

-----

- VSCode Version: Version: 1.41.1
- Local OS Version: macOS Catalina version 10.15.3
- Remote OS Version:  CentOS Linux 7 (Core)
- Remote Extension/Connection Type: SSH (the one remote sync uses)

From VS Code:
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

```
(automl-meta-learning) miranda9~/automl-meta-learning $ hostnamectl
   Static hostname: localhost.localdomain
Transient hostname: vision-01.cs.illinois.edu
         Icon name: computer-server
           Chassis: server
        Machine ID: 722ced1a818c412a9ee6f4889d01942f
           Boot ID: c8fcb95d128b4090833667dd89323dc5
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1062.1.2.el7.x86_64
      Architecture: x86-64
```

# Steps to Reproduce:

1. I connect to my cluster with ssh and password
2. eventually as I develop the terminal switches by itself to check remote

----

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

-----

SO: question: https://stackoverflow.com/questions/59995086/why-does-my-remote-development-on-vs-code-opens-the-check-remote-option-by-itsel

**Comment by roblourens** [comment]
This is https://github.com/microsoft/vscode-remote-release/issues/1760, from the Python extension, and they are working on fixing it.
