### ISSUE TITLE
VSCode remote server can't connect

### ISSUE THREAD

**Issue by nffdiogosilva** [microsoft/vscode-remote-release#2331]
I've seen a similar issue related to this already closed (#923). The issue was supposed to be fixed already in a prior VSCode version... but I have the latest VSCode and Remote extension versions:

- VSCode Version: 
`Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0`

- Local OS Version: **macOS 10.14.6 (Mojave)**
- Remote OS Version: **debian 9.9**
- Remote Containers Version: **0.101.0**
- Remote Extension/Connection Type: **Docker**

devcontainer.json:
```{
  "name": "****",
  "dockerComposeFile": "docker-compose.yml",
  "service": "app",
  "workspaceFolder": "/workspace",
  "extensions": ["ms-python.python", "VisualStudioExptTeam.vscodeintellicode"],
  "settings": {
    "_workbench.uiExtensions": ["peterjausovec.vscode-docker"],

    /* PYTHON SETTINGS */
    "python.pythonPath": "/usr/local/bin/python",
    // Testing
    "python.testing.pytestEnabled": true,
    // Linting
    "python.linting.pep8Enabled": false,
    "python.linting.pylintPath": "/root/.local/bin/pylint",
    // Formatting
    "python.formatting.provider": "black",
    "python.formatting.blackPath": "/root/.local/bin/black",
    "python.formatting.blackArgs": ["-S", "-l 120"]
  },
}
```

Steps to Reproduce:

1. Remote-Containers: Reopen in a container

Output: 

`Command failed: docker exec -w /root/.vscode-server/bin/ae08d5460b5a45169385ff3fd44208f431992451_1581353938794 -u root -i 6af58a363be687d56d78d005591d2c05d5e797c6902014a8ec859f459c0801cf tar --no-same-owner -xz --strip-components 1`

Does this issue occur when you try this locally?: Yes

**Comment by nffdiogosilva** [comment]
Can you guys report any feedback yet? Thank you

**Comment by chrmarti** [comment]
Could you append the full output from the log terminal?
