### ISSUE TITLE
Support Local-First Writing that then syncs to Remote

### ISSUE THREAD

**Issue by Skowt** [microsoft/vscode-remote-release#2333]
**Praise:**
Currently with the Remote SSH extension, I can do all my work without needing to hog the CPU of my machine which is awesome. For the most part, everything works very well. 

**Context:**
However, there's a bit of distance between myself (South Africa) and the machine (London).

I've noticed this primarily when creating new blank notes (CMD + N) and then trying to quickly jot down commands or when I press Enter to add a new line. If I press enter and start typing too quickly, the text either continues on the same line or starts at the beginning of the next line (e.g. before the automatic indentation works). 

**Feature Request:**
I'd love to have a feature where VS Code writes to a temporary cache / file locally on my machine and then continuously syncs to the remote server with perhaps a few seconds delay. This would be similar to some Cloud Apps like Google Docs/Excel where you make a few changes and then see the 'Saving...' indicator when there's been a brief pause in activity. 

By doing this the line breaks and typing would feel as responsive as they do when coding locally but you'd have the benefit of continual saving as you go along. Obviously a break in connection could cause issues but I believe that's a small setback vs the improvements in performance.

Happy to test this out or add more detail if necessary. Thanks for hearing me out!

**Comment by roblourens** [comment]
I understand the latency issue, I've had it myself too. But it's not likely that we will support this workflow natively with VS Code Remote, it's just not the scenario that we are targeting. But you can probably set this up yourself with something like rsync (https://linux.die.net/man/1/rsync) or even OneDrive.

**Comment by Skowt** [comment]
I'd go the rsync route but we don't store any code locally, so there's nothing to sync over. Having a local temporary file that then syncs over while you're writing or when a pause is detected then would eliminate that lag you experience when typing. 

Thanks though for the reply and review @roblourens 👍
