### ISSUE TITLE
Cannot attach to remote-container

### ISSUE THREAD

**Issue by ilkarman** [microsoft/vscode-remote-release#2334]
- VSCode Version: 1.43.0-insider
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 16.04.4
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. I run the docker container on remote and within it setup my SSH server:
`sudo /etc/init.d/ssh start`
2. Locally I create an SSH tunnel:
`ssh -NL localhost:54320:/var/run/docker.sock LOGIN@SERVER`
3. Locally, my vscode has the following settings.json:
```
{
    "docker.host":"tcp://localhost:54320"
}
```
4. Once the tunnel is launched, I can see the container in Remote Explorer, Containers
5. However, when I 'Attach to a Container', I get 'An error occured attaching to the container':

> [23 ms] Start: Check Docker is running
> [110 ms] Start: Inspecting container
> [185 ms] Start: Run in container: uname -m
> [723 ms] x86_64
> [723 ms] 
> [723 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
> [776 ms] NAME="Ubuntu"
> VERSION="16.04.4 LTS (Xenial Xerus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 16.04.4 LTS"
> VERSION_ID="16.04"
> HOME_URL="http://www.ubuntu.com/"
> SUPPORT_URL="http://help.ubuntu.com/"
> BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
> VERSION_CODENAME=xenial
> UBUNTU_CODENAME=xenial
> [776 ms] 
> [777 ms] Start: Run in container: cat /etc/passwd
> [789 ms] Start: Run in container: test -d /root/.vscode-server-insiders
> [845 ms] 
> [845 ms] 
> [845 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server-insiders/data/Machine' && { > '/root/.vscode-server-insiders/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
> [900 ms] 
> [900 ms] 
> [900 ms] Exit code 2
> [901 ms] Start: Run in container: test -d /root/.vscode-server-insiders/bin/8d17dc1e84d53f5fd4ed0d05fabaa3062259633d
> [906 ms] 
> [907 ms] 
> [907 ms] Exit code 1
> [907 ms] Installing VS Code Server for commit 8d17dc1e84d53f5fd4ed0d05fabaa3062259633d
> [907 ms] Start: Run in container: mkdir -p /root/.vscode-server-insiders/bin/8d17dc1e84d53f5fd4ed0d05fabaa3062259633d_1581429863516
> [968 ms] 
> [968 ms] 
> [969 ms] Start: Run: docker exec -w /root/.vscode-server-insiders/bin/8d17dc1e84d53f5fd4ed0d05fabaa3062259633d_1581429863516 -u root -i b4e1ddafeed7952737bf6a87d1c9fa35c816186d2f121f1d23dcacfc46eec062 tar --no-same-owner -xz --strip-components 1
> [1207 ms] 
> [1208 ms] "--workdir" requires API version 1.35, but the Docker daemon API version is 1.26
> 
> [1210 ms] Command failed: C:\Program Files\Docker\Docker\resources\bin\docker.exe exec -w /root/.vscode-server-insiders/bin/8d17dc1e84d53f5fd4ed0d05fabaa3062259633d_1581429863516 -u root -i b4e1ddafeed7952737bf6a87d1c9fa35c816186d2f121f1d23dcacfc46eec062 tar --no-same-owner -xz --strip-components 1

I'm able to connect using PyCharm but not with VSCode. Unfortunately I don't have sudo access to the remote to update the docker daemon, so if there is any way around it that would be great

**Comment by chrmarti** [comment]
Working dir for `docker exec` was introduced with 17.12.0-ce (2017-12-27).

**Comment by chrmarti** [comment]
I'm leaning towards making that the minimal required version. (The alternative is to avoid using that option.)

**Comment by chrmarti** [comment]
@Chuxel FYI, 17.12.0-ce is the minimal version (and has been for some time). I'll update the version check in code.

**Comment by connor4312** [comment]
Verified by code review
