### ISSUE TITLE
Blue sceen with powerline installed

### ISSUE THREAD

**Issue by Pixsky8** [microsoft/vscode-remote-release#2336]
Issue Type: <b>Bug</b>

When using powerline with a powerline compatible font, opening a vscode WSL-remote window with terminal makes windows' blue screen pop-up.

Removing powerline / the powerline font fixes the issue from what i've tested but only after a 2nd blue screen.

I couldn't try on another PC to see if it was my install but i have tried reinstalling both the vscode-server and the extention which did not fix the issue.

EDIT: I have also tried multiple powerline compatible fonts.

Extension version: 0.42.3
VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (9.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2001)|
|Memory (System)|15.86GB (9.21GB free)|
|VM|50%|
</details>

**Comment by Pixsky8** [comment]
Fully deleting vs code's extension fixed the problem.

**Comment by Pixsky8** [comment]
Reinstalling VS Code helped, before crashes happened when powerline was active (with or without the custom font), now it only happens when using a custom font.

**Comment by egamma** [comment]
Do you observe the same issue when using WSL2?

**Comment by Pixsky8** [comment]
I don't think i have access to WSL2 since i'm on OS build n° 18362.657, however i don't have any issue using the Windows Terminal app found on the microsoft store.

**Comment by Pixsky8** [comment]
what info do i need to add?

**Comment by aeschli** [comment]
I wasn't able to reproduce a crash.

- `sudo apt install golang-go`
- `sudo apt install powerline-shell`
- adding to `.bashrc`
```
GOPATH=$(go env GOPATH)
echo GOPATH $GOPATH

function _update_ps1() {
    PS1="$($GOPATH/bin/powerline-go  -error $? -modules cwd,perms,git,hg,jobs,exit,root)"
}

if [ "$TERM" != "linux" ] && [ -f "$GOPATH/bin/powerline-go" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
```
- open remote wsl window. open integrated terminal. I see the new shell

Any steps I missed?
