### ISSUE TITLE
Workaround missing host key during verification step 

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#2337]
Continuing https://github.com/microsoft/vscode-remote-release/issues/1525

Need a workaround to get the actual host key, like by starting ssh in a terminal using the traditional method.

**Comment by JacksonKearl** [comment]
VSN plz

**Comment by roblourens** [comment]
- Use windows
- Enable the `remote.SSH.useLocalServer` setting
- Clear your `~/.ssh/known_hosts` file
- Connect to a remote
- You should see the host key fingerprint prompt and it should contain the host key fingerprint (looks like some hash). It should not say `unknown` or anything weird.
