### ISSUE TITLE
SendEnv and SetEnv are ignored

### ISSUE THREAD

**Issue by mlcdf** [microsoft/vscode-remote-release#2344]
Hello,

To be honest, I don't know if this is really a bug, or the feature request. I didn't manage to find a list of all `ssh_config` directives supported by VSCode.

- VSCode Version: 1.42
- Local OS Version: Windows 10
- Remote OS Version: RHEL
- Connection Type: SSH

Steps to Reproduce:

1. In the server, add `AcceptEnv GIT_AUTHOR_NAME` in `/etc/ssh/sshd_config`
2. Restart sshd `systemctl restart sshd`
3. Locally, add `SetEnv GIT_AUTHOR_NAME="Maxime"` to your `ssh_config`
4. Connect via SSH to the server 
5. Run `printenv | grep GIT`. No match found.

Same behaviour with `SendEnv`.

**Comment by roblourens** [comment]
I am looking at this, it seems like SetEnv should work but I can't even get it to work in a simple case, using ssh from a terminal.

I add `SetEnv FOO=bar` to my config, the sshd_config has `AcceptEnv FOO`, restarted the server, but my FOO variable isn't set in an ssh session. I'm confused. Does the SetEnv case work for you, using ssh from an external terminal?

**Comment by roblourens** [comment]
Nevermind, I restarted the server again and it's working now. Investigating.

**Comment by roblourens** [comment]
`SetEnv` works for me in vscode. Here is one thing to consider - we start a server on your remote, and its environment doesn't change one it has started. So if you connect, change `SetEnv`, and connect again, you won't see the change reflected in the remote environment. You can force it to restart by running the command "Kill VS Code Server on Host". Does that explain the issue you are seeing?

If changing SetEnv often is something we need to support, I would have to think about how to load that environment into each new remote extension host process...

**Comment by mlcdf** [comment]
Yes, it does work when I run `ssh MY_SERVER` via Git Bash (for Windows).

**Comment by mlcdf** [comment]
I restarted `vscode-server` and it worked. 

> we start a server on your remote, and its environment doesn't change one it has started

Is this explain somewhere in the documentation? Otherwise, a little note about this in the documentation might be a great addition.

Thank you again and sorry for the false bug report. Have a nice day!
