### ISSUE TITLE
Quick Open ctrl+p shows empty list when using Remote SSH

### ISSUE THREAD

**Issue by Ragnoroct** [microsoft/vscode-remote-release#2345]
Issue Type: <b>Bug</b>

Open a folder in remote ssh and try to quick open a file using ctrl+p

It will only show you files that you've recently opened instead of filtering the currrently opened directory/workspace.

Extension version: 0.49.0
VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 3.10.0-1062.9.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7440HQ CPU @ 2.80GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.56GB free)|
|Process Argv|--ignore-gpu-blacklist|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev|
|OS|Linux x64 3.10.0-1062.9.1.el7.x86_64|
|CPUs|Common KVM processor (12 x 2399)|
|Memory (System)|31.81GB (2.15GB free)|
|VM|29%|
</details>

**Comment by roblourens** [comment]
Are you sure you have a folder open? Can you include some screenshots of this behavior so I'm clear on the issue?

**Comment by Ragnoroct** [comment]
Sure. I can do that tomorrow.

**Comment by Ragnoroct** [comment]
Using local workspace
![local_workspace](https://user-images.githubusercontent.com/19155205/75054067-f8409b80-5497-11ea-8bb9-c256db68e08e.gif)

Using SSH Remote workspace
![ssh_workspace](https://user-images.githubusercontent.com/19155205/75054068-f8d93200-5497-11ea-8f2b-f2cd5e231aa7.gif)

**Comment by roblourens** [comment]
Can you check that those files are not covered by exclude patterns or the .gitignore file? https://github.com/microsoft/vscode/wiki/Search-Issues#missing-search-results

**Comment by Ragnoroct** [comment]
🤦‍♂ That was it. I'm sorry for wasting time. Adding `"search.useIgnoreFiles": true` solved the problem.

```
//the .gitignore file
# Ignore everything in this directory
*
# Except this file
!.gitignore
```
