### ISSUE TITLE
REMOTE HOST IDENTIFICATION HAS CHANGED!

### ISSUE THREAD

**Issue by macarthuror** [microsoft/vscode-remote-release#2346]
- VSCode Version: 1.42
- Local OS Version: Windows 10 
- Remote OS Version:
- Remote Extension/Connection Type: SSH/Docker/WSL

Similar to #976

Steps to Reproduce:

1. Remote-ssh connect Host
(If the Identification of the hosting change the error appears)
2. Error

```
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Already try `ssh-keygen -R <host>` but nothing changed.

Help

**Comment by roblourens** [comment]
Can you share the contents of the Remote-SSH output channel when this happens?

**Comment by macarthuror** [comment]
Is already solved
I ran the following command `ssh-keygen -R <host>` in every single shell (`cmd`, `powershell`, `WSL Bash` and `Git Bash`).
The shell who is using, in my case, visual studio code to connect with the server was `Git Bash`
