### ISSUE TITLE
Timeout occurred when connecting to reomte via ssh. Option `RequestTTY=force` is needed.

### ISSUE THREAD

**Issue by mirsking** [microsoft/vscode-remote-release#2348]
- VSCode Version: 1.42.0
- Local OS Version: Ubuntu 18.04
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

Timeout occurred when connecting to reomte via ssh

![image](https://user-images.githubusercontent.com/6286383/74402512-69ac9880-4e5f-11ea-8d5d-3a7cb0df898c.png)

when I try the ssh command in a local teminal with `-v` option, it shows that timeout occurred when "Sending command: bash"

![image](https://user-images.githubusercontent.com/6286383/74402663-dfb0ff80-4e5f-11ea-9c47-dd021997b2d5.png)

And it just worked when I tried the "RequestTTY=force" options, i.e.  `ssh -v -o RequestTTY=force gpu3 bash`, with the help of 
  https://superuser.com/questions/1246446/ssh-is-stuck-at-sending-command-but-login-without-a-command-works

Therefore, can `RequestTTY=force` option be able to added into remote ssh command ? 

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
That's interesting, do you have any idea why that's an issue on this remote?

Does adding `RequestTTY force` to your ssh config work?

**Comment by mirsking** [comment]
I find it often happends with the operations as blew.
1. open two instances of vscode with two different remote hosts named with HostA & HostB
2. close one instance with HostA
3. open a new instance to connect HostA while HostB is still connected.
4. I cannot open the new instance to connect HostA now,  and I aslo cannot connect HostA in termianl with `ssh -v gpu3 bash`, while connecting HostA in termial with `ssh -v -o RequestTTY=force gpu3 bash` just works.

And when I closs all the instances of vscode and reopen an instance to connection HostA, it just works.

**Comment by roblourens** [comment]
Does adding `RequestTTY force` to your ssh config work?

Is there anything unusual about the setup of your ssh server that you think might cause this? I haven't seen this issue.

**Comment by mirsking** [comment]
> Does adding `RequestTTY force` to your ssh config work?
> 
> Is there anything unusual about the setup of your ssh server that you think might cause this? I haven't seen this issue.

No, it doesn't work when adding `RequestTTY force` to ssh config, since the option has not been added into the ssh process of vscode remote.

Nothing special.

**Comment by roblourens** [comment]
Adding it to the ssh config is exactly the same as adding it on the command line, so that doesn't make sense to me. Assuming the config is being used.

**Comment by mirsking** [comment]
> Adding it to the ssh config is exactly the same as adding it on the command line, so that doesn't make sense to me. Assuming the config is being used.

But I didn't see the config in the detail window of vscode. 

![image](https://user-images.githubusercontent.com/6286383/75642283-e15b2f80-5c75-11ea-8069-bb9380ddb420.png)

**Comment by roblourens** [comment]
ssh reads your config file and uses those options, they won't show up on the command line there.
