### ISSUE TITLE
Stop spamming report.*.json files in my home directory

### ISSUE THREAD

**Issue by dapirian** [microsoft/vscode-remote-release#2349]
Running vscode remote ssh spams a ton of `report.*.json` files in my home directory of the remote machine, seemingly maybe every minute or so a new one shows up. Everything seems to work fine, so I don't know what these files/errors are indicative of practically speaking.

- VSCode Version:
1.42.0
- Local OS Version:
OSX
- Remote OS Version:
Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Run vscode remote ssh
2. Admire spam of report.*.json files in my home directory

Of interest in the files might be:
`"event": "Allocation failed - JavaScript heap out of memory",`
```
"commandLine": [
      "~/.vscode-server/bin/ae08d5460b5a45169385ff3fd44208f431992451/node",
      "~/.vscode-server/bin/ae08d5460b5a45169385ff3fd44208f431992451/out/bootstrap-fork",
      "--type=watcherService"
    ],
```

```
"javascriptHeap": {
    "totalMemory": 2164359168,
    "totalCommittedMemory": 2163311624,
    "usedMemory": 2025695160,
    "availableMemory": 65309240,
    "memoryLimit": 2197815296,
```

**Comment by roblourens** [comment]
That's not something that we do on purpose, it sounds like the file watcher is crashing and writing that? @deepak1556 do you recognize this from electron/node?

Is that the exact contents of the file? If not can you share the full file?

**Comment by cmhzc** [comment]
> That's not something that we do on purpose, it sounds like the file watcher is crashing and writing that? @deepak1556 do you recognize this from electron/node?
> 
> Is that the exact contents of the file? If not can you share the full file?

I encountered same issue, I'm sharing the full file(with personal information wiped) below.

`{
  "header": {
    "event": "Allocation failed - JavaScript heap out of memory",
    "trigger": "FatalError",
    "filename": "report.20200217.100620.21907.0.001.json",
    "dumpEventTime": "2020-02-17T10:06:20Z",
    "dumpEventTimeStamp": "1581905180976",
    "processId": 21907,
    "cwd": "/home/$USER",
    "commandLine": [
      "/home/$USER/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node",
      "/home/$USER/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/bootstrap-fork",
      "--type=watcherService"
    ],
    "nodejsVersion": "v12.4.0",
    "glibcVersionRuntime": "2.23",
    "glibcVersionCompiler": "2.17",
    "wordSize": 64,
    "arch": "x64",
    "platform": "linux",
    "componentVersions": {
      "node": "12.4.0",
      "v8": "7.4.288.27-node.18",
      "uv": "1.29.1",
      "zlib": "1.2.11",
      "brotli": "1.0.7",
      "ares": "1.15.0",
      "modules": "72",
      "nghttp2": "1.38.0",
      "napi": "4",
      "llhttp": "1.1.3",
      "http_parser": "2.8.0",
      "openssl": "1.1.1b",
      "cldr": "35.1",
      "icu": "64.2",
      "tz": "2019a",
      "unicode": "12.1"
    },
    "release": {
      "name": "node",
      "headersUrl": "https://nodejs.org/download/release/v12.4.0/node-v12.4.0-headers.tar.gz",              "sourceUrl": "https://nodejs.org/download/release/v12.4.0/node-v12.4.0.tar.gz"
    },
    "osName": "Linux",
    "osRelease": "4.15.0-74-generic",
    "osVersion": "#83~16.04.1-Ubuntu SMP Wed Dec 18 04:56:23 UTC 2019",
    "osMachine": "x86_64",
    "host": "bigvid-g10"
  },
  "javascriptStack": {
    "message": "No stack.",
    "stack": [
      "Unavailable."
    ]
  },
  "nativeStack": [
    {
      "pc": "0x0000000000aadaf5",
      "symbol": "report::TriggerNodeReport(v8::Isolate*, node::Environment*, char const*, char const*, std::string const&, v8::Local<v8::String>) [/home/$USER/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node]"
    },
    {
      "pc": "0x000000000098fec3",
      "symbol": "node::OnFatalError(char const*, char const*) [/home/$USER/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node]"
    },
    {
      "pc": "0x0000000000b1552e",
      "symbol": "v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/$USER/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node]"
    },
    {
      "pc": "0x0000000000b158a9",
      "symbol": "v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/$USER/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node]"
    },
    {
      "pc": "0x0000000000f20105",
      "symbol": " [/home/$USER/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node]"           },
    {
      "pc": "0x0000000000f2aa6b",
      "symbol": "v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/home/$USER/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node]"
    },
    {
      "pc": "0x0000000000f2b787",
      "symbol": "v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/$USER/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node]"
    },
    {
      "pc": "0x0000000000f2e225",
      "symbol": "v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/home/$USER/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node]"
    },
    {
      "pc": "0x0000000000ef9250",
      "symbol": "v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/home/$USER/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node]"
    },
    {
      "pc": "0x00000000011cb0ce",
      "symbol": "v8::internal::Runtime_AllocateInNewSpace(int, unsigned long*, v8::internal::Isolate*) [/home/$USER/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node]"
    },
    {
      "pc": "0x0000000001a93942",
      "symbol": " [/home/$USER/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node]"           }
  ],
  "javascriptHeap": {
    "totalMemory": 2150977536,
    "totalCommittedMemory": 2147362536,
    "usedMemory": 2121361968,
    "availableMemory": 51368600,
    "memoryLimit": 2197815296,
    "heapSpaces": {
      "read_only_space": {
        "memorySize": 524288,
        "committedMemory": 32024,
        "capacity": 523976,
        "used": 31712,
        "available": 492264
      },
      "new_space": {
        "memorySize": 4194304,
        "committedMemory": 1358392,
        "capacity": 2095904,
        "used": 308256,
        "available": 1787648
      },
      "old_space": {
        "memorySize": 2138693632,
        "committedMemory": 2138513992,
        "capacity": 2114078032,
        "used": 2113923008,
        "available": 155024
      },
      "code_space": {
        "memorySize": 688128,
        "committedMemory": 615264,
        "capacity": 459840,
        "used": 459840,
        "available": 0
      },
      "map_space": {
        "memorySize": 528384,
        "committedMemory": 494064,
        "capacity": 344160,
        "used": 344160,
        "available": 0
      },
      "large_object_space": {
        "memorySize": 6299648,
        "committedMemory": 6299648,
        "capacity": 6291536,
        "used": 6291536,
        "available": 0
      },
      "code_large_object_space": {
        "memorySize": 49152,
        "committedMemory": 49152,
        "capacity": 3456,
        "used": 3456,
        "available": 0
      },
      "new_large_object_space": {
        "memorySize": 0,
        "committedMemory": 0,
        "capacity": 2095904,
        "used": 0,
        "available": 2095904
      }
    }
  },
  "resourceUsage": {
    "userCpuSeconds": 109.478,
    "kernelCpuSeconds": 18.579,
    "cpuConsumptionPercent": 272.461,
    "maxRss": 3073888256,
    "pageFaults": {
      "IORequired": 0,
      "IONotRequired": 3682154
    },
    "fsActivity": {
      "reads": 88,
      "writes": 8
    }
  },
  "uvthreadResourceUsage": {
    "userCpuSeconds": 40.5506,
    "kernelCpuSeconds": 5.48977,
    "cpuConsumptionPercent": 97.9583,
    "fsActivity": {
      "reads": 0,
      "writes": 8
    }
  },
  "libuv": [
  ],
  "environmentVariables": {
    "MAIL": "/var/mail/$USER",
    "SSH_CLIENT": 
    "USER": $USER,
    "LC_TIME": "zh_CN.UTF-8",
    "SHLVL": "2",
    "HOME": "/home/$USER",
    "LC_MONETARY": "zh_CN.UTF-8",
    "LOGNAME": $USER,
    "_": "/home/$USER/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/server.sh",
    "XDG_SESSION_ID": "1314",
    "PATH": "/home/$USER/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games",
    "VSCODE_AGENT_FOLDER": "/home/$USER/.vscode-server",
    "LC_ADDRESS": "zh_CN.UTF-8",
    "XDG_RUNTIME_DIR": "/run/user/1013",
    "LC_TELEPHONE": "zh_CN.UTF-8",
    "LANG": "en_US.UTF-8",
    "SHELL": "/bin/bash",
    "LC_NAME": "zh_CN.UTF-8",
    "LC_MEASUREMENT": "zh_CN.UTF-8",
    "LC_IDENTIFICATION": "zh_CN.UTF-8",
    "PWD": "/home/$USER",
    "SSH_CONNECTION": ,
    "LC_NUMERIC": "zh_CN.UTF-8",
    "LC_PAPER": "zh_CN.UTF-8",
    "VSCODE_INJECT_NODE_MODULE_LOOKUP_PATH": "/home/$USER/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/remote/node_modules",
    "VSCODE_LOGS": "/home/$USER/.vscode-server/data/logs/20200217T100505",
    "VSCODE_PARENT_PID": "21524",
    "AMD_ENTRYPOINT": "vs/platform/files/node/watcher/unix/watcherApp",
    "PIPE_LOGGING": "true",
    "VERBOSE_LOGGING": "true"
  },
  "userLimits": {
    "core_file_size_blocks": {
      "soft": 0,
      "hard": "unlimited"
    },
    "data_seg_size_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "file_size_blocks": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "max_locked_memory_bytes": {
      "soft": 65536,
      "hard": 65536
    },
    "max_memory_size_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "open_files": {
      "soft": 1048576,
      "hard": 1048576
    },
    "stack_size_bytes": {
      "soft": 8388608,
      "hard": "unlimited"
    },
    "cpu_time_seconds": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "max_user_processes": {
      "soft": 515107,
      "hard": 515107
    },
    "virtual_memory_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    }
  },
  "sharedObjects": [
    "/lib/x86_64-linux-gnu/libdl.so.2",
    "/lib/x86_64-linux-gnu/librt.so.1",
    "/usr/lib/x86_64-linux-gnu/libstdc++.so.6",
    "/lib/x86_64-linux-gnu/libm.so.6",
    "/lib/x86_64-linux-gnu/libgcc_s.so.1",
    "/lib/x86_64-linux-gnu/libpthread.so.0",
    "/lib/x86_64-linux-gnu/libc.so.6",
    "/lib64/ld-linux-x86-64.so.2"
  ]
}`

**Comment by deepak1556** [comment]
@roblourens the report is generated by node https://nodejs.org/docs/v12.4.0/api/report.html , its an experimental feature that shouldn't be on by default , do we know if we are using this feature in remote-server ?

**Comment by deepak1556** [comment]
Regarding the crashing file watcher, not sure which one we use nsfw or chokidar for remote servers, /cc @bpasero for additional inputs.

**Comment by bpasero** [comment]
@aeschli did the file watchers for remote, I think we use Chokidar now.

**Comment by roblourens** [comment]
I was looking at this a little. If I open the root `/` in a remote window, I see the watcher continuously crashing and restarting. If I open the root in a local window on the same machine that I am remoting to, I saw it print the famous `ENOSPC` error and show a notification. So I am wondering whether the same thing is happening in both cases but we just don't handle that error case properly in the remote case.

**Comment by roblourens** [comment]
But to be clear in the remote window I don't see the ENOSPC error anywhere

**Comment by diwu1989** [comment]
I'm hitting this same issue too right now

**Comment by grantwwu** [comment]
Here's a helpful script (only tested on Ubuntu 18.04):

```
export DIR_TO_DELETE=/home/grant.wu
find "$DIR_TO_DELETE" -maxdepth 1 -type f -regextype egrep -regex "$DIR_TO_DELETE/report.[[:digit:]]{8}.([[:digit:]]+.)+json" -delete
```

I put this in `/etc/cron.hourly`.

**Comment by jpan127** [comment]
My coworkers and I are annoyed at this too.  We use remote SSH daily and it is racking up the order of thousands of reports.

How do we disable this?

**Comment by grantwwu** [comment]
@jpan127 Have you tried my cronjob script?

**Comment by jpan127** [comment]
Thanks grant! No I have not, but I am sure it works great. I can do it myself but I rather not ask everyone in my company to add a cron job 😅.  Ideally the extension can fix this problem, or send it to `/tmp`.

**Comment by HaiyiMei** [comment]
Hello, I'm facing the same issue as you guys. Hoping for a bug fixing of this.

**Comment by fanyix** [comment]
Hi, is there any update on this issue? It's annoying I need to delete those report files on a daily basis.

**Comment by hologerry** [comment]
Now, it is spamming the workspace directory!
Please fix this issue.

**Comment by iseesaw** [comment]
![Xnip2020-09-06_19-03-06](https://user-images.githubusercontent.com/31267864/92324370-a77b4380-f073-11ea-87d4-3f8f0accc3b5.jpg)

**Comment by pjgao** [comment]
same issues

**Comment by jonculver** [comment]
Now also seeing a core file with every crash which fills up my home directory even faster. Crash happens every 2 minutes. Sample report file attached.

$ ls -l ~/core.node.*
-rw------- 1 jculver eng 104910848 Sep 11 10:11 /users/jculver/core.node.14536
-rw------- 1 jculver eng 104914944 Sep 11 10:13 /users/jculver/core.node.16343
-rw------- 1 jculver eng 104914944 Sep 11 10:15 /users/jculver/core.node.16759
-rw------- 1 jculver eng 104910848 Sep 11 10:17 /users/jculver/core.node.17487
-rw------- 1 jculver eng 104914944 Sep 11 10:19 /users/jculver/core.node.18152


[report.20200911.101920.18152.0.001.txt](https://github.com/microsoft/vscode-remote-release/files/5218526/report.20200911.101920.18152.0.001.txt)

**Comment by windxrz** [comment]
same issues

**Comment by ivallesp** [comment]
Same issue here...

**Comment by roblourens** [comment]
@deepak1556 you recently did some investigation here, do you know how we can disable this?

**Comment by deepak1556** [comment]
Last update was I pinged a member of the electron team who is also on the node.js team for thoughts /cc @codebytere , this is weird one that reports are generated even when it is behind experimental flag on this node version.

**Comment by radutomy** [comment]
Same issue here.

**Comment by radutomy** [comment]
I think issue has to do with the Python extension for vscode. Uninstalling it stopped these annoying reports.

**Comment by LiChenda** [comment]
Same issue here.

**Comment by maningning** [comment]
same issues

**Comment by bixing-udemy** [comment]
Same issue here.

**Comment by alterapars** [comment]
Same issue here

**Comment by artistro08** [comment]
Same issues.

**Comment by urnotjessie** [comment]
same issues

**Comment by ankurash** [comment]
same issue. 

> Version: 1.53.0 (user setup)
> Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
> Date: 2021-02-03T20:36:38.611Z (4 days ago)
> Electron: 11.2.1
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Windows_NT x64 10.0.19041

**Comment by jotix16** [comment]
👀👀

**Comment by sunnyleevip** [comment]
same issue.

**Comment by EricFuma** [comment]
Similar environment and same issue. I use python for development and didn't have this problem before, but when I install **ipdb** package and do some setting, this situation happened. So I uninstall ipdb package, and the problem disappears.    
`pip install ipdb`     
`pip uninstall ipdb`

**Comment by Maelfyn** [comment]
Same issue here. How do I disable this feature? It's really annoying.

**Comment by roblourens** [comment]
Much has changed, please let me know if this is still an issue
