### ISSUE TITLE
alias cann't get in remote terminal

### ISSUE THREAD

**Issue by Abbyyan** [microsoft/vscode-remote-release#2350]
I've install the remote-ssh extensions and it works well . But when i use the `terminal` in the shell, it can't show the `alias` i set. The alias was set in `~/.profile` and `.bashrc`, however , only the alias in the`.bashrc` can be get. Is there some settings to get the alias? Thanks a lot.

**Comment by Abbyyan** [comment]
OK, after a few tries , it figured out that the alias can't be get just because it was set in the `.profile`, while the alias set in the `.bashrc` can be get properly.  
But in the linux system,  the config file was get as follows `.bash_profile > .progfile > .bashrc`. Is there any way to configure the vscode and let the `.profile ` work if there is a `.profile` config file.

**Comment by Abbyyan** [comment]
Now i find all the alias can't be found when opened with remote terminal . Is there any settings that the alias can be get in the remote situation? Thanks a lot.

**Comment by Abbyyan** [comment]
It's weird that the `PATH` env variable set in the `.profile` can be found , but the alias can't be found in any situation. Is there any settings can change this situation please? Thanks a lot.

**Comment by roblourens** [comment]
Sorry, I'm not sure, the remote terminal environment should include these. Maybe you can set them up in bashrc
