### ISSUE TITLE
Fragment property of Uri (DocumentLink.target) is removed when extension runs on remote machine

### ISSUE THREAD

**Issue by djadeja** [microsoft/vscode-remote-release#2352]
- VSCode Version: 1.42
- Local OS Version: Windows 10
- Remote OS Version: Linux RHEL 7.6
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
1. My extension (showing document links) is installed on remote machine (using Remote-SSH), the shown document link does not jump to provided line number. Instead it jumps to the first line of the file.
2. Extension uses following API,
When extension creates a [DocumentLink ](https://code.visualstudio.com/api/references/vscode-api#DocumentLinkProvider) using following code,
const linkTarget = vscode.Uri.parse(`file:${lineobj.fileName}#${lineobj.lineNum}`);
const docLink = new vscode.DocumentLink(linkRange, linkTarget);
3. The shown document link does not show the fragment part in its tool-tip and the document link does jump to first line of the file, *which is not expected*. 
4. Fragment property of Uri ([DocumentLink](https://code.visualstudio.com/api/references/vscode-api#DocumentLinkProvider).target) is removed when extension runs on remote machine.

The issue only happens when remote.
Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

From primary analysis, it looks like, transformOutgoing function from /out/vs/server/uriTransformer.js does not consider fragment stored in URI while trasnforming from 'file' to 'vscode-remote'. And resulting trasnformed URI have only path, but not its related fragment(line number).

**Comment by egamma** [comment]
Please provide a minimal extension that illustrates the issue so that we can reproduce it.

**Comment by djadeja** [comment]
> Please provide a minimal extension that illustrates the issue so that we can reproduce it.

I have created a [minimal extension](https://github.com/djadeja/findall) which can be used to illustrate the issue.

Steps to reproduce the issue:
- Install [findall](https://github.com/djadeja/findall) extension manually (As it is not available in marketplace yet).
- Open any file which contains text.
- Run Command "FindAll: Find All in Current File". Enter text to search and press Enter key.
- A new window is opened with search results. Please, note that the results has **links** (text with underline). This link can be used to jump to the location of the text in searched file.

**Issue:**
When above steps are performed with file opened using Remote-SSH Targets. The links from results does not jump to the actual target line number and the link's tool-tip does not show the line number.

Please, let me know if more information is required.

**Comment by djadeja** [comment]
Please, re-open this issue, as I am not able to reopen this issue which is closed by vscodebot.

**Comment by djadeja** [comment]
> This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!

Hi @egamma, 

I have created a [minimal extension](https://github.com/djadeja/findall) which can be used to illustrate the issue.
Please, re-open the issue or please let me know how can I re-open this issue.

Thanks
