### ISSUE TITLE
Install and use Remote SSH without internet connection

### ISSUE THREAD

**Issue by orangeswim** [microsoft/vscode-remote-release#2354]
We develop on an isolated network without internet connection on local or remote machine.

- VSCode Version:  1.43.0-insider
- Local OS Version: Windows_NT x64 10.0.18363
- Remote OS Version: CentOS7
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Both computers on an Air-gapped network without internet connection
2. Install extension on vs-code via vsix file and setup ssh keys
3. Attempt connection...
```
Downloading with wget

wget download failed
wget: unable to resolve host address ‘update.code.visualstudio.com’
```
#78 issue was closed recently, but this issue isn't solved. I need a way to install remote extension completely offline without internet connection. Files necessary should be explicitly packaged together with the extension or listed for download.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: No other extensions installed. Fresh install.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/1242
