### ISSUE TITLE
"Failed to set up socket for dynamic port forward" when using `AddressFamily inet6` in `ssh_config`

### ISSUE THREAD

**Issue by staticfloat** [microsoft/vscode-remote-release#2355]
- VSCode Version: `1.42.0-insider`
- Local OS Version: `MacOS 10.15.2`
- Remote OS Version: `Ubuntu 16.04`
- Remote Extension/Connection Type: `SSH`

Steps to Reproduce:

1. Set up a remote `AddressFamily inet6` in your `~/.ssh_config`. 
2. Attempt to connect, observe this in the debug logs:
```
Failed to set up socket for dynamic port forward to remote port 40531: connect ECONNREFUSED 127.0.0.1:55128. Is the remote port correct?
```

It occurs to me that SSH may be binding to `::1` rather than to `127.0.0.1`.  Doing some simple experiments with `nc` show that this is likely the case:

```bash
# fails immediately
$ nc 127.0.0.1 55128
# Waits for input, signifying it has successfully opened a socket
$ nc ::1 55128
# Also waits for input, signifying it has successfully opened a socket
$ nc localhost 55128
```

While the `AddressFamily inet6` directive is not common; it is occasionally useful when working with DNS entries that give different hosts based on address family.

**Comment by roblourens** [comment]
Weird, I have an ipv4 HostName in my config, and I can add `AddressFamily inet6` to my config and connect from a terminal just fine, but when I connect through vscode, it says `Could not resolve hostname`. But that step seems to work for you?

**Comment by staticfloat** [comment]
Yes, I have an explicit entry in `/etc/hosts` to make connecting with non-SSH programs just as easy.  To make this more concrete:

```
cat /etc/hosts | grep win64bot3
fd37:5040::3d14:d116:b247:ce81 win64bot3.wireguard
```

```
$ cat ~/.ssh/config | grep -A 5 win64bot3
Host win64bot3
  AddressFamily inet6
  HostName win64bot3.wireguard
  User Administrator
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  Port 2222

```

This is usually not an issue for me, except for when I'm tethering my laptop through my phone; in that situation my mobile carrier gives me a default DNS server that responds to everything with one of those awful "did you mean" pages.  This is awful practice, of course, but results in `win64bot3.wireguard` resolving to an ipv4 address as well as an ipv6 address.  My workaround for this is to tell `ssh` to always use the ipv6 address (via `AddressFamily inet6`), but this causes `ssh` to bind only to `::1`, rather than its usual behavior of binding to `127.0.0.1` and `::1`.  You can verify this by first, with no `AddressFamily` entry, doing an `ssh` port forward then using `netstat` to observe what's being listened on:

```
ssh -L 8080:localhost:8080 win64bot3
```

```
# Without `AddressFamily inet6` in ~/.ssh/config
$ netstat -nab | grep 8080
tcp4       0      0  127.0.0.1.8080         *.*                    LISTEN               0          0
tcp6       0      0  ::1.8080               *.*                    LISTEN               0          0
```

Versus:
```
# With `AddressFamily inet6` in ~/.ssh/config
$ netstat -nab | grep 8080
tcp6       0      0  ::1.8080               *.*                    LISTEN               0          0
```

Luckily, there's an easy fix; using `localhost` instead of `127.0.0.1` seems to work across both situations.

**Comment by samuela** [comment]
I'm getting the same error with the following SSH config:
```
Host host1
 HostName host1.cs.washington.edu
 User myuser
Host host2 host2.cs.washington.edu
 HostName host2.cs.washington.edu
 User myuser
 ProxyJump host1
```
I'm remote SSHing into host2.

**Comment by albatros69** [comment]
I'm also being bitten by the same issue (it seems). I can't get a remote connection working in VScode to an IPv6 only SSH server. I also get the same error message
```
Failed to set up socket for dynamic port forward to remote port 42837: connect ECONNREFUSED 127.0.0.1:36535. Is the remote port correct?
```

**Comment by albatros69** [comment]
Hello,
How to force VS code to use ::1 instead of 127.0.0.1 in remote-SSH?
I would like to do this on a per-host basis on the VS code client, for some remote servers which are IPv6-only configured (AddressFamily inet6 in sshd).
Regards,

**Comment by meepen** [comment]
hi, i've installed vscode insiders and remote ssh nightly but it seems this hasn't been fixed. 

netstat -plnt shows that it is only listening on ipv4:
```
tcp        0      0 127.0.0.1:38607         0.0.0.0:*               LISTEN      11438/node          
tcp6       0      0 :::22                   :::*                    LISTEN      -  
```

**Comment by tanhakabir** [comment]
@meepen what does your config look like?

**Comment by meepen** [comment]
.ssh/config
```
Host ipv6.memer.home
  HostName ipv6.memer.home
  User meep
```

If I may make a suggestion, maybe just using `localhost` instead of `::1` or `127.0.0.1` will do the trick?

**Comment by meepen** [comment]
also to note: the domain isn't actually mine, it's in /etc/hosts

**Comment by tanhakabir** [comment]
Hm and what exact error do you see? In my testing I noticed `localhost` didn't seem to work when you have a config like this:
```
Host foobar
  HostName ::ffff:a83e:1db0
  User foo
  AddressFamily inet6
```

**Comment by staticfloat** [comment]
Confirmed that with SSH nightly it's working now.  Thanks guys!

**Comment by RodBelaFarin** [comment]
I've tested it with SSH nightly and an IPv6 host.

Error:

> Could not establish connection to "1111:2222:3333:4444:5555:6666:7777": Could not resolve hostname.

For me it seems that it's trying to use only seven blocks of the IPv6 address. The host address is:

`1111:2222:3333:4444:5555:6666:7777:8888`

So the IPv6 address consists of the maximum of eight blocks, but only seven are mentioned in the error message.

My config looks like this

```
Host 1111:2222:3333:4444:5555:6666:7777:8888
  HostName 1111:2222:3333:4444:5555:6666:7777:8888
  User foo
```

**Comment by tanhakabir** [comment]
@RodBelaFarin this is a different issue with the parsing, created a new issue here: https://github.com/microsoft/vscode-remote-release/issues/5907
