### ISSUE TITLE
Remote SSH timeout too aggressive and not configurable

### ISSUE THREAD

**Issue by broady** [microsoft/vscode-remote-release#2356]
Issue Type: <b>Bug</b>

1. attempt to SSH to a server that takes a while to connect
2. observe Remote SSH extension timeout

My SSH server requires two-factor authentication via a ubico security key. If I don't press it in time, Remote SSH times out.

Extension version: 0.36.0
VS Code version: Code - Insiders 1.34.0-insider (daf71423252a707b8e396e8afa8102b717f8213b, 2019-05-06T22:07:35.830Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.2.17-1rodete3-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|32, 51, 35|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: cbro|
|OS|Linux x64 5.2.17-1rodete3-amd64|
|CPUs|Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz (6 x 2299)|
|Memory (System)|11.73GB (0.18GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
You can set `remote.SSH.connectTimeout`, does that help?

**Comment by roblourens** [comment]
Also, you are using a very old version of Insiders, and of the extension, you should update so you get all the latest features, like that extension

**Comment by broady** [comment]
Thanks. I'm on a new computer now and I'm going to try the non-insiders version. I'll try this setting. Thanks.
