### ISSUE TITLE
SSH: "gzip: stdin: not in gzip format" after updating to 1.42.1

### ISSUE THREAD

**Issue by sergei3000** [microsoft/vscode-remote-release#2360]
- VSCode Version: 1.42.1
- Local OS Version: MacOS Catalina 10.15.2
- Remote OS Version: Red Hat Enterprise Linux Server release 7.4 (Maipo)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Just trying to connect as usual via a button in Remote Explorer menu
2. See logs:
```
[11:01:42.739] > Downloading with wget
[11:01:43.456] > Download complete
[11:01:43.463] > 
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> mv: cannot stat ‘vscode-server-linux-x64*/*’: No such file or directory
> WARNING: tar exited with non-0 exit code
```

Does this issue occur when you try this locally?: NA
Does this issue occur when you try this locally and all extensions are disabled?: NA

So after updating to version 1.42.1 VS Code can not connect to remote server. I had to downgrade back to 1.41.

**Comment by roblourens** [comment]
Can you check whether `~/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0` exists and what the contents are?

**Comment by sergei3000** [comment]
@roblourens it does exist and contains these files:
```
(base) [serzakharov@mn-hdap40 26076a4de974ead31f97692a0d32f90d735645c0]$ ls -alh
total 42M
drwxr-xr-x  6 serzakharov domain_users  190 Feb 14 17:00 .
drwxr-xr-x  5 serzakharov domain_users  166 Feb 14 10:47 ..
-rw-r--r--  1 serzakharov domain_users  14K Dec 18 18:02 LICENSE
drwxr-xr-x  2 serzakharov domain_users   26 Dec 18 18:05 bin
drwxr-xr-x 28 serzakharov domain_users 4.0K Dec 18 18:05 extensions
-rwxr-xr-x  1 serzakharov domain_users  42M Dec 18 18:04 node
drwxr-xr-x 67 serzakharov domain_users 4.0K Dec 18 18:05 node_modules
drwxr-xr-x  3 serzakharov domain_users  154 Dec 18 18:05 out
-rw-r--r--  1 serzakharov domain_users 1021 Dec 18 18:02 package.json
-rw-r--r--  1 serzakharov domain_users  20K Dec 18 18:02 product.json
-rwxr-xr-x  1 serzakharov domain_users  222 Dec 18 18:02 server.sh
(base) [serzakharov@mn-hdap40 26076a4de974ead31f97692a0d32f90d735645c0]$ 
```

**Comment by roblourens** [comment]
Sorry, I gave you the commit for 1.41 instead of 1.42.1. Could you check in `~/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054`? And could you share the full log?

**Comment by sergei3000** [comment]
@roblourens first I looked and that directory existed but completely empty.

Then I updated to 1.42 again to get you the full log, and this time it just worked!

I guess this issue can be closed now. Thanks.

**Comment by roblourens** [comment]
Sorry, I'm not sure what happened the first time, must have been a random glitch, thanks for your patience

**Comment by FEG2034** [comment]
Hi @roblourens :
I have the same problem. It cann't be solved by downgrading back to 1.41. There is a detail explanation [here](https://stackoverflow.com/questions/60257299/after-connection-to-remote-destination-but-download-0-size-vscode-server-linux-x). Could you please help me find out what's going on ?

- Offline. But there is a proxy help Remote SSH server connect to https://update.code.visualstudio.com
- VS Code version: 1.42.1
- VS CodeRemote-SSH Extension version: 0.49.0
- Local host OS version: Win 7
- Remote SSH server OS version: Ubuntu 18.04.01 image on RHEL 7.5
( My target ssh server is a Kubernetes Pod equipped with openssh-server, wget, gzip, tar package on RHEL 7.5. )

BTW : I made a experiment to simulating connection from win 7 to remote SSH server (CentOS). This environment is allow to connect to Internet directly.

**Comment by roblourens** [comment]
Does it also allow these other domains? https://code.visualstudio.com/docs/remote/faq#_what-are-the-connectivity-requirements-for-vs-code-server

Is it possible that the proxy is blocking the download but making it appear that the download is succeeding?

**Comment by FEG2034** [comment]
Hi @roblourens 
There is no problem with connecting to other domains. In the remote SSH server `wget https://update.code.visualstudio.com/commit:${commit_id}/server-linux-x64/stable` directly, then it pop out following message : 
```
--2020-02-20 10: 10:00:37-- https://update.code.visualstudio.com/commit:${commit_id}/server-linux-x64/stable
Resolving <proxy hostname> <proxy ip>
Connecting to <proxy hostname>|<proxy ip>|:<port>... connected
Proxy request sent, awaiting response... 302 Found
Location: https://vscode.cdn.azure.cn/stable/${commit_id}/vscode-server-linux-x64.tar.gz [following]

--2020-02-20 10: 10:00:37-- https://vscode.cdn.azure.cn/stable/${commit_id}/vscode-server-linux-x64.tar.gz
Connecting to <proxy hostname>|<proxy ip>|:<port>... connected
Proxy request sent, awaiting response... 302 Moved Temporarily
Locatoin: http://172.17.12.133:15871/cgi-bin/blockpage.cgi?ws-session=3389065048 [following]

--2020-02-20 10: 10:00:38-- http://172.17.12.133:15871/cgi-bin/blockpage.cgi?ws-session=3389065048
Connecting to 172.17.12.133:15871... connected
HTTP request sent, awaiting response... 200 OK
Length: 3297 (3.2k) [text/html]
Saving to: `stable`

2020-02-20 10: 10:00:38 (6464 MB/s) - `stable` saved [3297/3297]
```

Is it necessary setting proxy into `.curlrc` ? I hope to  preview the source code, it may be helpful to find out how VS Code triggers my remote SSH server to do ( such as `wget`, `curl`, `gzip` ). THX

Proxy White List :
    - *.vo.msecnd.net
    - update.code.visualstudio.com
    - code.visualstudio.com
    - go.microsoft.com
    - vscode.blob.core.windows.net
    - marketplace.visualstudio.com
    - *.gallery.vsassets.io
    - *.gallerycdn.vsassets.io
    - rink.hockeyapp.net
    - vscode.search.windows.net
    - raw.githubusercontent.com
    - vsmarketplacebadge.apphb.com
    - az764295.vo.msecnd.net

**Comment by roblourens** [comment]
You might try setting up the proxy in that rc file to see if that helps. First we try to use wget if available, if not, we use curl.

If your proxy is set up in the environment in a bashrc file or something like that then it should be applied here but it's possible that there's an issue and it is not using the proxy configuration.

**Comment by FEG2034** [comment]
I have set up the `/etc/wgetrc` with parameters `https_proxy` and `ca_certificate`. 

I tried to figure out what's going on while VS Code trigger my remote SSH server download `vscode-server-linux-x64`. 

Then I found out there is an process
```
wget --connnect-timeout=7 --dns-timeout=7 -nv -O vscode-server-linux-x64 https://update.code.visualstudio.com/commit:${commit_id}/server-linux-x64/stable
```
![image](https://user-images.githubusercontent.com/26348889/75006337-61320e80-54ac-11ea-8f36-87f6fd71e3cb.png)

But the size of `~/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/vscode-server-linux-x64` is always 0 bytes.

I can run this command directly in my remote SSH server and download complete `vscode-server-linux-x64`, which means proxy and environment variable are fine. Is it possible that the next step of `gzip` or `tar` affects pipeline ? Cloud you please give me a brief description about `wget` and `gzip` pipeline or source code ?

**Comment by roblourens** [comment]
The environment of the install script could be different, can you check the full log, it should have printed the environment at some point.

All we do is wget then tar. Your download completed in about a second so the 7 second timeouts probably aren't involved here.
