### ISSUE TITLE
Unable to attach to a docker container in remote host 

### ISSUE THREAD

**Issue by akshath27188** [microsoft/vscode-remote-release#2361]
Issue Type: <b>Bug</b>

1)Edit settings.json 
 Under Docker: Host:  ssh://username@remoteip
2) Click on "Open a remote window icon" 
3) Click on Remote-Containers: Attach to Running Container

Result :
Nothing is listed even though container is running remotely 
Note: I am able to connect to the file system of the same machine through VSCODE: Remote-SSH

Remote System :
amazon m4.large ec2 instance 

Extension version: 0.101.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.14.158-129.185.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 34.216.134.67|
|OS|Linux x64 4.14.158-129.185.amzn2.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (2 x 2300)|
|Memory (System)|7.79GB (4.42GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Does the Remote Explorer show the containers? Is there anything in the console (`Help` > `Toggle Developer Tools`)?
