### ISSUE TITLE
Terminal panel opens with out of place expand caret

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode-remote-release#2364]
Version: 1.43.0-insider
Commit: 4c9161a3f125f5a788aafa73a4ecfcb27dcfc319
Date: 2020-02-14T05:26:38.779Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:
1. Remote SSH > Connect to Host
2. New window opens and the panels on the bottom have an out of place caret to expand the panel. 

![image](https://user-images.githubusercontent.com/9721254/74562667-282ff200-4f20-11ea-9893-047b6fcd390c.png)

**Comment by roblourens** [comment]
I think this is already fixed by Steven
