### ISSUE TITLE
Allow use of NVidia OpenGL within VsCode Development Container

### ISSUE THREAD

**Issue by rirlswift** [microsoft/vscode-remote-release#2366]
Opening a container that requires Docker NVidia (OpenGL) support fails, reporting: 
   unknown flag: --gpus all

Please see the issue mark down [[HERE](https://github.com/rirlswift/vscode-opengl-issue/blob/master/issue.md)]

**Comment by Chuxel** [comment]
Try separating the flag in your runArgs as follows: "--gpus", "all"

Docker will likely process what I saw in the devcontainer.json as passing in the flag "--gpus all" from the command line rather than two separate args.

**Comment by rirlswift** [comment]
The issue is resolved by your suggestion. See [here ](https://github.com/rirlswift/vscode-opengl-issue/blob/master/fix.md) for more information.
