### ISSUE TITLE
connection to windows failed

### ISSUE THREAD

**Issue by LinkeyLeo** [microsoft/vscode-remote-release#2367]
- VSCode Version: 1.43.0-insider(commit:4c9161a3f125f5a788aafa73a4ecfcb27dcfc319)
- Local OS Version: macOS 10.15.3 (19D76)
- Remote OS Version: Windows 10 Insider Bulid 19559
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. add window machine to 'Windows Remotes' setting
2. try connect windows machine through remote extension - ssh

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

connection keeping failed with following error
![image](https://user-images.githubusercontent.com/10334184/74587034-9eb81700-5028-11ea-9153-3ba99dd760b7.png)

by review the output windows, i find the extension is trying to execute following command

> ssh -T -D 53045 -o ConnectTimeout=15 192.168.137.1 powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -Command "**\$e=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('_[AUTOGENERATED BASE64 SCRIPT]_'))))**; powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -EncodedCommand \$e"

where the problem appearing is the value of Command parameter, after my own fix and test, it should be like following

> ssh -T -D 53045 -o ConnectTimeout=15 192.168.137.1 powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -Command "**powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -EncodedCommand $([Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('_[base64 encoded script generated by extension]_')))))**"

i have modified my local extension.js to temporary resolve it, hope you can fix this in the next release.

**Comment by LinkeyLeo** [comment]
after a few tries, i found that was cased by default shell, i changed the default shell from cmd to powershell core, that could case some parsing difference on string.

though, if it's possible for you to add compatibility for powershell for powershell is a more modern shell, and make pwsh default probably a more often choose

**Comment by roblourens** [comment]
Could you try installing the nightly version of the ssh extension and check whether this still happens? Also please include the full log in the future, it includes useful info like what version you are using.
