### ISSUE TITLE
Failed to parse remote port from server output: bash: no job control in this shell

### ISSUE THREAD

**Issue by livc** [microsoft/vscode-remote-release#237]
- VSCode Version:Version 1.34.0-insider (1.34.0-insider)
- Local OS Version: macos  10.14.4
- Remote OS Version: CentOS Linux 7
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open connection in VS code.
2. get the error log in new window.

```
SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a22503430227d"
SSH Resolver called for host: P40
Setting up SSH remote "P40"
Using commit id "daf71423252a707b8e396e8afa8102b717f8213b" and quality "insider" for server
Install and start server if needed
> bash: no job control in this shell
"install" terminal command done
Received install output: bash: no job control in this shell
Failed to parse remote port from server output: bash: no job control in this shell
```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
@livc what shell is your default shell on P40?

If it's bash then there seems to be a junk missing in your log. Can you please try:
1) <kbd>F1</kbd> > `Remote-SSH: Uninstall VS Code Server from Host...`
2) Select P40
3) Retry to connect to P40
Paste the full log from the Output channel.

Thanks!

**Comment by livc** [comment]
@kieferrm Hi, thanks for your reply.

My default is bash, but I add `exec ~/.linuxbrew/bin/zsh` to `.bashrc`, so it will change to zsh. I do this way because I don't have the root to change default shell.

When I remove this line, the vscode remote works!
I don't know if there is better way to handle this kind of issue.

Thanks!

**Comment by kieferrm** [comment]
@livc we don't support yet other login shells, only `bash`. Working on it.
