### ISSUE TITLE
Windows USERNAME env overriding user setting in ssh file

### ISSUE THREAD

**Issue by hopkinsp** [microsoft/vscode-remote-release#2370]
Issue Type: <b>Bug</b>

If running windows and your user account is something like Firstname.Surname, the USERNAME variable is set to this and anything you set in the User field of the SSH config file is never honoured.

Windows 7.

Extension version: 0.49.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2687W 0 @ 3.10GHz (16 x 3092)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (0.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by hopkinsp** [comment]
Ah maybe the settings file is being ignored in someway, remover User and changed HostName to user@hostname, it seemed to ignore that as well.

**Comment by roblourens** [comment]
Need more details about exactly what you are seeing
