### ISSUE TITLE
Connection error: Version mismatch, client refused

### ISSUE THREAD

**Issue by AlgoRythm-Dylan** [microsoft/vscode-remote-release#2374]
- VSCode Version: 1.41.1
- Local OS Version: Linux x64 4.19.102-1-MANJARO
- Remote OS Version: Linux x86_64 4.15.0-76-generic Ubuntu 18.04.4 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Attempt to connect to server

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Notes: This happened to a colleague at work also running Manjaro. This does not happen on my Windows machine (as client) when connecting to the same server.

**Comment by kittawat49254** [comment]
i think i got the same error and i also happen to using manjaro too but my Host is raspberry pi 4 running raspbian buster.
can you post remote ssh log here so i can check if this is the same exact issue and dont have open a new issue.

**Comment by chrmarti** [comment]
What are the ssh client's and the ssh server's versions? This sounds like they are not compatible and this might not be related to SSH-Remote.

**Comment by AlgoRythm-Dylan** [comment]
> 
> 
> What are the ssh client's and the ssh server's versions? This sounds like they are not compatible and this might not be related to SSH-Remote.

I will edit with actual version numbers later, but I can SSH from one machine to the other, so the SSH versions are likely compatible. It is only VS Code + Remote Dev that will not connect, so perhaps it is more strict.

**Comment by 5shekel** [comment]
i can ssh into remote, but vscode remote ssh throws the mismatch version error
`~/.vscode-server-oss/.xxx.log`
```

IP Address: xxx
IP Address: xxx
Extension host agent listening on 35687


[19:01:29] Extension host agent started.
[19:01:30] [127.0.0.1][bc2ca968] Version mismatch, client refused.
[19:01:30] [127.0.0.1][e6e4143d] Version mismatch, client refused.
```

remote is ubuntu 18 
$ ssh -v localhost
```
debug1: Local version string SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
```
local is arch linux 
```
debug1: Local version string SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
```

**Comment by 5shekel** [comment]
related #1767 #2099

**Comment by roblourens** [comment]
Your issue references are correct, Remote in general isn't supported with OSS versions of vscode
