### ISSUE TITLE
Can not install on remote if default shell is nushell

### ISSUE THREAD

**Issue by corbinu** [microsoft/vscode-remote-release#2376]
- VSCode Version: 1.42.1
- Local OS Version: Windows 10 Pro 19564.rs_prerelease.200207-1438
- Remote OS Version: Ubuntu 19.10
- Remote Extension/Connection Type: SSH and WSL

Steps to Reproduce:

1. Try to connect to an environment with Nushell set as the default shell.

This is inline with #363, #19, and #567 just need the startup script to work for Nushell (https://www.nushell.sh/)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Please try with the nightly version of the Remote-SSH extension, and if it still doesn't work, attach the log from the "Remote-SSH" output channel


![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Comment by corbinu** [comment]
@roblourens In a fun twist of fate for me nu added -c support in todays 0.10 release so this is working now. Sorry to bother.
