### ISSUE TITLE
Code Highlighting Failed

### ISSUE THREAD

**Issue by zhao170628** [microsoft/vscode-remote-release#2378]
Issue Type: <b>Bug</b>

1. Start VS Code.
2. Open a folder.
3. Open a C++ source file.
4. Press Ctrl+Shift+P.
5. Type "Remote-WSL: Reopen Folder in WSL".
6. Press Enter.
7. Visible parts of the code can not be highlighted properly, such as macros, variables, type names and so on.

Extension version: 0.42.3
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1608)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (7.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1608)|
|Memory (System)|15.80GB (7.81GB free)|
|VM|67%|
</details>

**Comment by aeschli** [comment]
Do you have the C++ extension installed on the WSL side as well?

**Comment by fig02** [comment]
+1, having issues with C projects as well. It happens with both wsl 1and 2. I do have the extension installed on the wsl side.

**Comment by fig02** [comment]
recorded a quick video if it helps. the issue happens when opening files that are contained in wsl, regardless of launching code through wsl or not: https://youtu.be/q_Jeyxa1WTU

**Comment by fig02** [comment]
Looks like its being taken care of https://github.com/microsoft/vscode-cpptools/issues/3942

**Comment by sean-mcmanus** [comment]
Fixed with 0.29.0 of the C/C++ extension.
