### ISSUE TITLE
Reload Window dialogue is displayed twice after SSH reconnect fails

### ISSUE THREAD

**Issue by hutchisr** [microsoft/vscode-remote-release#2382]
- VSCode Version: 1.42.1
- Local OS Version: macOS Catalina 10.15.3 (Darwin x64 19.3.0)
- Remote OS Version: Multiple (Reproduced on Ubuntu 18.04.4 LTS)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Cause SSH connection and subsequent reconnect to fail (disable network/disconnect wifi/etc.)
2. Click "Reload" when dialogue appears. a second identical dialogue will appear, clicking Reload or Cancel on this second dialogue seems to do nothing.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by roblourens** [comment]
I will reopen https://github.com/microsoft/vscode-remote-release/issues/1485 to track this
