### ISSUE TITLE
forwardPorts doesn't seem to be needed?

### ISSUE THREAD

**Issue by achandlerwhite** [microsoft/vscode-remote-release#2385]
I noticed that I seem to be able to connect to my app running in the dev container regardless if I set `forwardPorts`. This seemed counter intuitive based on the current documentation. Thanks!

- VSCode Version: 1.42.1
- Local OS Version: macOS 10.15.3
- Remote OS Version: Debian 9
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open any asp.net core app project in VS Code in a container.
2. Comment out any appPorts or forwardPorts settings, reload the window.
3. Run the app and observe you can connect from the host.

**Comment by chrmarti** [comment]
You might have this setting enabled:
![image](https://user-images.githubusercontent.com/9205389/74950137-f8d92380-53fe-11ea-9f6b-d45bde8c3aa4.png)

Or you are clicking on a link inside VS Code for which we automatically establish a forwarding.

**Comment by achandlerwhite** [comment]
@chrisdias I'm definitely cmd-clicking the link in vs-code. Thanks for the response! That is a nice little feature-- I don't see it in the [docs located here](https://code.visualstudio.com/docs/remote/containers#_forwarding-or-publishing-a-port) though--might be worth a mention?

**Comment by chrmarti** [comment]
@Chuxel For the doc suggestion.

**Comment by Chuxel** [comment]
This is in docs, but neglected to close the isssue.
