### ISSUE TITLE
nodejs out of memory 

### ISSUE THREAD

**Issue by Abbyyan** [microsoft/vscode-remote-release#2386]
https://github.com/microsoft/vscode-remote-release/issues/1884#issuecomment-563137485
Because the issue was been closed but the question hasn't been solved, so i asked the problem here again. I've tried to open a smaller folder and it does worked . But the question is often i open the total folder in the remote . I think the `out of memory ` mainly due to the `file watcher` as reported in 
```shell
"commandLine": [
      "/data/home/abby/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/node",
      "/data/home/abby/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/bootstrap-fork",
      "--type=watcherService"
    ],
```
So is there any methods to close the `watcherService` or could you please show more detail about how to ` adapting the file watcher exclusions in VS Code's settings.` ? Thanks a lot. 

Thanks  a lot .  @chrmarti

**Comment by Abbyyan** [comment]
> [#1884 (comment)](https://github.com/microsoft/vscode-remote-release/issues/1884#issuecomment-563137485)
> Because the issue was been closed but the question hasn't been solved, so i asked the problem here again. I've tried to open a smaller folder and it does worked . But the question is often i open the total folder in the remote . I think the `out of memory ` mainly due to the `file watcher` as reported in
> 
> ```shell
> "commandLine": [
>       "/data/home/abby/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/node",
>       "/data/home/abby/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/bootstrap-fork",
>       "--type=watcherService"
>     ],
> ```
> 
> So is there any methods to close the `watcherService` or could you please show more detail about how to ` adapting the file watcher exclusions in VS Code's settings.` ? Thanks a lot.
> 
> Thanks a lot . @chrmarti

I can hep to give more information about this problems. Hope for your suggestions . Thanks

**Comment by Abbyyan** [comment]
Is that means https://github.com/microsoft/vscode/issues/3998 which add some files into`files.watcherExclude` ?

**Comment by chrmarti** [comment]
@Abbyyan Yes, please try adding large folders you don't need watched to that setting.

**Comment by Abbyyan** [comment]
> @Abbyyan Yes, please try adding large folders you don't need watched to that setting.

Thanks a lot . I've tried to add `files.watcherExclude` into settings.json and it does work. Thanks a lot.
```json
"files.watcherExclude": {
          "**": true
     },
```

**Comment by chrmarti** [comment]
Thanks, closing.
