### ISSUE TITLE
Source Control not working with symbolic links to folders.

### ISSUE THREAD

**Issue by sz4l3k** [microsoft/vscode-remote-release#239]
- VSCode Version: 1.34.0-insider
- Local OS Version: Windows 10
- Remote OS Version:
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Make a symbolic link in WSL to a Windows folder e.g. ln -s Dir /mnt/c/Users/user/dir
2. Open code-insiders inside Dir ( or subfolder of Dir) with git repo.
3. Edit a file and save.
4. Note: Git Decorators are not displayed in explorer tab.
5. Switch to Source Control tab.
6. Path of the edited file is displayed without the usage of symbolic link while the ones in explorer are. Right clicking and opening file creates new file tab instead of switching to the one that is already open. ( Code seems to treat those two opened files as different ones. )

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/5970
