### ISSUE TITLE
Missing Remote-Containers: Forward Port from Container

### ISSUE THREAD

**Issue by jwyglendowski-precisionlender** [microsoft/vscode-remote-release#2396]
We have written the needed data int
Issue Type: <b>Bug</b>

This options appears to be missing from the extension. I followed the steps outlined in https://github.com/Microsoft/vscode-remote-try-go. Using forwardPorts in the devcontainer.json resolved the issue but doesn't explain why the option is missing to begin with.

I am running the following:

Docker Desktop on 2.2.0.3
VS Code Version: 1.42.1 (system setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
ms-vscode-remote.remote-containers 0.101.1
Extension version: 0.101.1
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.19.76-linuxkit

**Comment by chrmarti** [comment]
There is the more general `Forward a Port` command now. We removed the old command that was specific to Remote-Containers. The new command works with all Remote-Development extensions.

**Comment by jwyglendowski-precisionlender** [comment]
@chrmarti Thank you for your response. I am not seeing that on the command palette either. 
![image](https://user-images.githubusercontent.com/40304875/75038827-3e403400-5485-11ea-8783-21480f9d9f42.png)

I have almost all the extensions. Am I missing another extension?
![image](https://user-images.githubusercontent.com/40304875/75038744-089b4b00-5485-11ea-9202-9b9113e21534.png)

**Comment by chrmarti** [comment]
That command would only be shown in a window that is already connected to a remote (container / WSL / SSH). Does it not?

**Comment by jwyglendowski-precisionlender** [comment]
So clearly it's a misunderstanding on my part. And now that I see it that makes perfect sense. It's only available in the context of the connected container. Thanks for clearing that up.

![image](https://user-images.githubusercontent.com/40304875/75070156-ad874980-54c0-11ea-9e8d-32072c660f14.png)
