### ISSUE TITLE
Connecting to SSH platforms using WSL

### ISSUE THREAD

**Issue by aurelienfalco** [microsoft/vscode-remote-release#2397]
Hi,

I'm not sure if this should be a bug, a feature request or just a question so here it is.
I want to connect to a remote platform using SSH such as configured in my linux subsystem.
So I can connect to WSL using the "Remote - WSL" extension but then I can't install the "Remote - SSH" extension _on_ the WSL remote.

Is there any way we could have the Remote SSH available on WSL?

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/937

**Comment by roblourens** [comment]
Actually to be sure, do you want to use WSL's SSH to connect to some remote, or do you want to use SSH to connect to WSL?

**Comment by aurelienfalco** [comment]
I would like to use WSL's SSH to connect to some other remote, yes (therefore, using the ssh configuration of WSL). It looks like issue #937 is indeed about this.
