### ISSUE TITLE
SSH config does not get created if the specified folder does not yet exist

### ISSUE THREAD

**Issue by DeeHants** [microsoft/vscode-remote-release#2400]
When using "Add New SSH Host", it asks for the command, then a ssh config file to update.
If the folder of the specific folder does not exist, it silently fails.
After manually creating `%userprofile%\.ssh\`, the command worked as expected.

Version: 1.42.1 (system setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
Good catch, thanks!
