### ISSUE TITLE
Workflow for setting custom USER_UID in development workflows

### ISSUE THREAD

**Issue by hholst80** [microsoft/vscode-remote-release#2401]
The example devcontainer.json files and associated Dockerfiles support a build argument called USER_UID that defaults to 1000. 

What is the appropriate workflow for working in a team with several different USER_UID (every developer has their own UID != 1000).

**Comment by Chuxel** [comment]
@hholst80 This is dynamically updated to match your local one if you specify `remoteUser` in the Dockerfile and image case.  https://github.com/microsoft/vscode-remote-release/issues/2228 tracks adding this same support for Docker Compose.

**Comment by hholst80** [comment]
Our current workflow is to specify USER_UID in environment and pass that to our docker-compose.yml developer build and build the local developer images (environments) tailored for the user. We do not use devcontainer.json at all but I was curious if it could be used to mitigate the need to pass around all those build arguments. It makes the docker-compose build more complex to read and manage correctly.

**Comment by hholst80** [comment]
Just throwing out ideas. If we don't land in anything useful this can be closed. 

What I think is needed is some kind of "Pass build arguments" to the Dockerfile build from vscode. The user could then specify it's preferred user ID and have a custom built user ID in the Dev container.

**Comment by Chuxel** [comment]
If you don't want to use automation, the good news is that passing build arguments has been implemented this iteration in devcontainer.json.  See #46.  You can reference local environment variables when setting args using ${localEnv:VARNAME}.  For Docker Compose, you can use a `.env` file and then reference that in your Compose file for build arguments.
