### ISSUE TITLE
`who am i` returns nothing

### ISSUE THREAD

**Issue by tautomer** [microsoft/vscode-remote-release#2403]
- VSCode Version: 1.42.1
- Local OS Version: Microsoft Windows [Version 10.0.19041.84]
- Remote OS Version: Red Hat Enterprise Linux 7.6
- Remote Extension/Connection Type: SSH
Steps to Reproduce:

1. Connect to a server in a terminal. `who am i` returns username, TTY, date and IP
2. Connect to the same server in VS Code remote. `who am i` does not return anything.

Meanwhile, `$SSH_CLIENT` or `pinky` will not show the VS Code remote session. `netstat` does show the connection of both terminal and VS Code.

Is it by design?

**Comment by roblourens** [comment]
@Tyriar do you know whether we would expect `who am i` to have a result in a terminal in a remote workspace?

**Comment by Tyriar** [comment]
This is by design. The terminal should act as if you were local as that's how it's launched, not as if you were connected over an SSH connection.

**Comment by tautomer** [comment]
> This is by design. The terminal should act as if you were local as that's how it's launched, not as if you were connected over an SSH connection.

Thanks for the reply. So it's impossible to know the IP address of my local computer in the terminal then.

**Comment by Tyriar** [comment]
Impossible by doing it that way, it might be possible another way?
