### ISSUE TITLE
Using fs-extra in WSL copy error

### ISSUE THREAD

**Issue by brianignacio5** [microsoft/vscode-remote-release#2404]
In our extension, we are using using fs-extra to copy some files from a template folder within our extension to a user created new folder.

Expected behavior:
- Files being copied from one place to another

Observed behavior:
- cb.apply is not a function error. This error was found in fs-extra and fixed by using graceful-fs 4.2.2 as shown [fs-extra repo issue 687](https://github.com/jprichardson/node-fs-extra/issues/687).

Proposed solution:
Update .vscode-server to use graceful-fs 4.2.2. Even if we add it to our extension to enforce it , vscode-server still has this error.

- VSCode Version: 1.42.1
- Local OS Version: Windows 10.0.19564.1000
- Remote OS Version: Ubuntu 18.04 on WSL 2
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Install vscode remote extension on WSL, this will create ~/.vscode-server
2. Install your extension that uses fs-extra copy.
3. Copy some files, an error is shown in Help -> Toggle Developer Tools

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
Won't your extension just use whatever version of graceful-fs you include? Why would it use node modules from the vscode server?

**Comment by roblourens** [comment]
Also it looks like we did this last month, you can check whether the Insiders build resolves your issue

https://github.com/microsoft/vscode/issues/89887

**Comment by roblourens** [comment]
It sounds like you are describing the same issue, let me know if the Insiders build doesn't resolve your issue

**Comment by brianignacio5** [comment]
> Won't your extension just use whatever version of graceful-fs you include? Why would it use node modules from the vscode server?

My question exactly. Tried using specific version in package.json, deleted node_modules and re-run npm I, no changes. Log still showed older version.

Thanks, will test with Insiders version.
