### ISSUE TITLE
Test: "initializeCommand" in devcontainer.json

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2407]
Refs: #1045
- [x] windows @egamma 
- [x] anyOS @mjbvz

Complexity: 3

---

On setting up DevContainers for testing: https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#testing-remote-containers

`"initializeCommand"` in the devcontainer.json is an optional property that can be set to a string (run in a shell) or an array of strings (run without shell). Verify:
- This always runs first when starting / connecting to a DevContainer.
- Case 1: One of: Single-container (image or Dockerfile) or docker-compose.
- Case 2: Repository container when the container does not exist yet or is rebuilt.
  - Check the command runs before the Docker image is built (note that there is an auxiliary image built first, the command runs only after that, but before the user image is built).
- Case 3: Repository container when the container already exists.

The working directory of the command should be the workspace folder. Except with the repository container, the command runs locally on the host OS.

**Comment by bpasero** [comment]
I verified that a config such as `"initializeCommand": "yarn"` gets run when I open a folder in docker on Windows. 

I am not sure I understand the Case 1-2-3 matrix you ask for and I am also not skilled enough in remote containers to know how to set this up (I appreciate how [this docs](https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#testing-remote-containers) gave me a good step by step description). 

Are there docs for how to setup the other cases?

**Comment by chrmarti** [comment]
@bpasero 

Case 1 is really just https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#single-container-with-dockerfile-or-image. It sounds like you already did that.

Case 2 and 3 is https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#repository-container with:
- Case 2: Make sure the container does not exist yet or rebuild it. (Just one of the two.)
- Case 3: Make sure the container already exists and connect to it.
- Run `Remote-Containers: Show Log` to inspect the current log and check your command was run in both cases.

**Comment by bpasero** [comment]
@chrmarti ok. any reason that command is not in the default commands list?

![image](https://user-images.githubusercontent.com/900690/75264108-35d25b00-57ef-11ea-9423-92b09df880f1.png)

**Comment by chrmarti** [comment]
@bpasero The command is there when you are not connected to a remote already.

**Comment by mjbvz** [comment]
I tested on MacOS. Ran into a few hiccups but seems to work overall

**Comment by sbatten** [comment]
Blocked by the above issue.

**Comment by egamma** [comment]
Verified that the blocking issue on Windows is resolved.
Covered cases 1, 2, 3.
