### ISSUE TITLE
docker.host with jump

### ISSUE THREAD

**Issue by lcxywfe** [microsoft/vscode-remote-release#2411]
I want to attach a container in a remote host, and I add following to the setting.json
"docker.host":"ssh://your-remote-user@your-remote-machine-fqdn-or-ip-here"
but how can I ssh with a jump host, the ssh config file doesn't seem to work.

**Comment by chrmarti** [comment]
We no longer use the Dockerode module, the SSH config should work. Could you try and let me know if that's the case?
