### ISSUE TITLE
code command not working locally when simultaneously using remote ssh

### ISSUE THREAD

**Issue by hacker-h** [microsoft/vscode-remote-release#2412]
- VSCode Version: 1.42.1
- Local OS Version: Ubuntu 19.10
- Remote OS Version: Raspbian GNU/Linux 10 (buster)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. launch an ssh remote session in vscode
2. open files on this remote session using the `code FILENAME` command
3. watch that the file(s) are opened in vscode
4. try to open files locally using the `code FILENAME` command
5. note that no file(s) are opened in vscode 

Does this issue occur when you try this locally?: No (requires remote)
Does this issue occur when you try this locally and all extensions are disabled?: No (requires remote extension)

**Comment by roblourens** [comment]
I don't totally understand, can you explain what exactly you are doing when you say you `try to open files locally using the code FILENAME command`?

**Comment by hacker-h** [comment]
After installing vscode you can code the `code` command.
Execute it without arguments to merely open Visual Studio Code.
If you add a file or directory path it will try to open it in a Visual Studio Code tab.

**Comment by roblourens** [comment]
I understand that. So you are logging into a machine with VS Code remote, and also using the same machine locally, opening a terminal, and typing `code file`? And what exactly happens when you do that?

This scenario works for me. What is the result of `which code` in that local terminal?
