### ISSUE TITLE
Cannot install .vscode folder on remote server at root directory

### ISSUE THREAD

**Issue by burningalc** [microsoft/vscode-remote-release#2418]
When I connect to the server and vscode starts to install .vscode folder, I got the following error:
mkdir: cannot create directory ‘[Server Directory]/user/.vscode-server’: Permission denied

I looked up at a couple of past issues including
https://github.com/microsoft/vscode-remote-release/issues/940#issuecomment-510232416

> mv ~/.vscode-server /my/big/disk/
> ln -s /my/big/disk/.vscode-server ~/.vscode-server

but found no luck in making it work since I also do not have the permission to execute symbolic link commands on the server.

I can only do mkdir on '[Server Directory]/user/public_html', is there any way I can navigate to /public_html right after vscode connects to the server?

Thanks a lot.

**Comment by roblourens** [comment]
I think you probably want a setting to pick a custom install path: #472
