### ISSUE TITLE
vscode will not start Jupyter server instance when using Remote - SSH extension

### ISSUE THREAD

**Issue by mpitucha** [microsoft/vscode-remote-release#2420]
Issue Type: <b>Bug</b>

Visual Studio Code will not start Jupyter server instance on its own when using Remote - SSH extension. When I click on "Run Cell" in a lineated .py file I get gollowing error message:

```Activating Python 3.7.3 64-bit ('venv': virtualenv) to run Jupyter failed with Error: StdErr from ShellExec, 'import warnings' failed; traceback:
Traceback (most recent call last):
  File "/data/datascience/users/mpitucha/cb_analysis/venv/lib/python3.7/warnings.py", line 554, in <module>
    _processoptions(sys.warnoptions)
  File "/data/datascience/users/mpitucha/cb_analysis/venv/lib/python3.7/warnings.py", line 208, in _processoptions
    _setoption(arg)
  File "/data/datascience/users/mpitucha/cb_analysis/venv/lib/python3.7/warnings.py", line 214, in _setoption
    import re
  File "/data/datascience/users/mpitucha/cb_analysis/venv/lib/python3.7/re.py", line 122, in <module>
    import enum
ModuleNotFoundError: No module named 'enum'.
```

`venv` created in the project directory is based on Python 3.7.3. The issue first occured ~2 weeks ago, I've never observed it before.

If I start Jupyter server on my own and then specify an URI in VSCode settings, then my code can be executed on it.

The issue occurs only when using remote machine.

My local machine has Ubuntu 19.10 and a remote one 16.04

Extension version: 0.49.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.0-40-generic
Remote OS version: Linux x64 4.4.0-165-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3433)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.36GB (5.24GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ds01|
|OS|Linux x64 4.4.0-165-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (32 x 1245)|
|Memory (System)|251.81GB (4.15GB free)|
|VM|0%|
</details>

**Comment by mpitucha** [comment]
[console log](https://github.com/microsoft/vscode-remote-release/files/4247062/-1582581301174.log)

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
