### ISSUE TITLE
Test SSH to mac server

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#2421]
- [ ] macOS @JacksonKearl 
 - [x] macOS @jrieken
 
 Complexity: 3

Set up a macOS SSH server, connect to it with the (nightly) Remote-SSH extension, and verify all basic VS Code functionality.

You can start an SSH server on mac by enabling "Remote Login"

![image](https://user-images.githubusercontent.com/323878/75206540-884a4380-572b-11ea-98ca-5af36b055cb2.png)

One of you, please connect from a Windows client, the other from any os.

**Comment by jrieken** [comment]
Tested this with a Mac client.

**Comment by JacksonKearl** [comment]
Tested on Windows.
