### ISSUE TITLE
${localWorkspaceFolder} using wrong slashes

### ISSUE THREAD

**Issue by waquner** [microsoft/vscode-remote-release#2423]
- VSCode Version: 1.42.1
- ms-vscode-remote.remote-containers: 0.101.1 (also tried back to 0.97.0)
- Local OS Version: Win 10
- Remote Extension/Connection Type: Docker
- Docker: version 19.03.5, build 633a0ea

All of a sudden ${localWorkspaceFolder} translates to a path using a single backslashes instead of 2 backslashes or a forward slash, which results in an error when the extensions runs `docker run`:

`docker.exe: Error response from daemon: Das System kann die angegebene Datei nicht finden.`
(Translated: The system can't find the specified file)

Example:

`"source=${localWorkspaceFolder}=/workspace,type=bind,consistency=cached"`

in the mounts Array in devcontainer.json
translates to

`--mount source=c:\Users\XXX\Documents\projectdir,target=/workspace,type=bind,consistency=cached`

when docker run is executed

When trying the same command with 2 backslashes or forwardslashes, docker dun seems to work

I tried different extension version, but maybe it's an issue with docker? Any suggestions?

**Comment by waquner** [comment]
Unfortunately I can't use docker dev containers at all anymore. Even a newly created config ("javascript-node:0-10") shows

`docker.exe: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /host_mnt/c/Users/XXX/Documents/project`

**Comment by chrmarti** [comment]
Could you try resetting the credentials for the file sharing in Docker Desktop's settings?

**Comment by waquner** [comment]
Strange... after 2 Windows restarts it started to work again, sorry to have bothered you.

Shoud I close this issue?

**Comment by chrmarti** [comment]
No problem. Yes, closing. 👍
