### ISSUE TITLE
[ssh] remote sh to wsl issue has file watcher block issues

### ISSUE THREAD

**Issue by ketozhang** [microsoft/vscode-remote-release#2425]
Very similar to microsoft/vscode#81647, however this time instead of using Remote-WSL, I used Remote-SSH to access an WSL server for the purpose of accessing the server outside the host device.

The solutions to microsoft/vscode#81647 as advertised in many places by @aeschli would not help because Remote-SSH does not have the equivalent configuration.

Attempted closing VSCode window with Remote-SSH session. Doing this releases the lock.

**Comment by ketozhang** [comment]
>  My assumption is that using SSH to connect to a WSL distro is not that common. Do you agree?

Possibly, not sure how most people use WSL; ssh into WSL however have been frequently covered throughout 2018-19. Although out of topic, is it more common to see SSH into Windows then WSL? The only alternative of course is to have a dedicated Linux server.

**Comment by aeschli** [comment]
Closing the issue as no action is planed
