### ISSUE TITLE
Ubuntu WSL

### ISSUE THREAD

**Issue by ToqYang** [microsoft/vscode-remote-release#2426]
Issue Type: <b>Bug</b>

Close the vs code of a moment to other and show the error in wsl

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763
Fetching remote diagnostics for 'WSL: Ubuntu' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (3.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.
</details>Extensions: none

**Comment by aeschli** [comment]
@ToqYang Please add more details, maybe a screenshot?

**Comment by ToqYang** [comment]
<img width="957" alt="Problem" src="https://user-images.githubusercontent.com/45366195/75285030-db7fcd00-57e3-11ea-9c74-eed9d5e11f19.PNG">
<img width="960" alt="Extension" src="https://user-images.githubusercontent.com/45366195/75285038-de7abd80-57e3-11ea-88c9-5806bcdb9832.PNG">

**Comment by aeschli** [comment]
Thanks @ToqYang. Can you attach the full content of WSL terminal? (as seen in the first screenshot).
There seems to be an error when starting up the server.

**Comment by ToqYang** [comment]
[Error.txt](https://github.com/microsoft/vscode-remote-release/files/4262704/Error.txt)
I send you, the complete log error, when I try initialize the server. Thanks!

**Comment by aeschli** [comment]
```
Error: Cannot find module './mysql.pub'
[2020-02-27 16:26:41.044] Require stack:
[2020-02-27 16:26:41.044] - /home/toqyang/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node_modules/diagnostic-channel-publishers/dist/src/index.js
```

@ToqYang  Is still still an issue? Looks like the server is missing a file. An update might have fixed that.


If yoiu still see it, can you do a
ls `/home/toqyang/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node_modules/diagnostic-channel-publishers/dist/src/` and see if `mysql.pub.js` is really missing? I tested that it's part of our install

https://github.com/microsoft/vscode-remote-release/issues/2690 is the same issue.
