### ISSUE TITLE
Container: inconsistent labels

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#2427]
I am using Docker on Windows and opened one folder in the container and one repository. The labels look weird for the latter:

![image](https://user-images.githubusercontent.com/900690/75264496-c4df7300-57ef-11ea-8963-c5cff8da5f1c.png)

**Comment by bpasero** [comment]
Maybe due to https://github.com/microsoft/vscode-remote-release/issues/2428

**Comment by chrmarti** [comment]
This appear to be fixed:
![image](https://user-images.githubusercontent.com/9205389/97227589-fe7cd980-17d5-11eb-9a65-95ae1777eec5.png)
