### ISSUE TITLE
Sort folders in the SSH targets view

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#2429]
![image](https://user-images.githubusercontent.com/323878/75271849-bb371a80-57b1-11ea-8bb6-6ecd48a7969a.png)

These would be more useful sorted alphabetically or in MRU order

**Comment by gugavaro** [comment]
@roblourens I see the tree is now auto sorted by mru. how can I switch to alphabetically?
thanks!

**Comment by roblourens** [comment]
Not supported but you could open a new feature request for it if it would be helpful.
