### ISSUE TITLE
Cannot connect to remote machine over ssh - no way to debug because the terminal is not kept open

### ISSUE THREAD

**Issue by gitpbg** [microsoft/vscode-remote-release#243]
I can ssh to my machine, but cannot do anything with the remote-ssh extension.  It logs in to the machine, I see the MOTD but then there is some error and the window promptly closes.  The window needs to be kept open to allow debugging of connection issues.   I do have "remote.SSH.showLoginTerminal": true

Extension version: 0.35.0
VS Code version: Code - Insiders 1.34.0-insider (daf71423252a707b8e396e8afa8102b717f8213b, 2019-05-06T22:08:08.969Z)
OS version: Windows_NT x64 10.0.17763
<other information deleted because it was WSL, I am NOT trying to connect to WSL over SSH>

**Comment by egamma** [comment]
Can you pls attach the output shown in View -> Output -> Remote - SSH.

**Comment by martyfranchuk** [comment]
I've been having the same problem. View-Output ... is empty. The terminal gets wiped clean before the stdout can be read. By some trickery. (prtScrn) I captured the output, before getting wiped clean.

The Rmote-SSH is OVERLY enforcing the Linux x64 construct. I can SHH into my Win10, and my Raspberrypi, but the Remote-SSH will reject the 'working' connection, since it doesn't g=find the Linux x64 tag it is looking for. (what in Linux are they doing that would be specific to x64 architecture? Isn't that what the OS is handling, removing the HW mapping??)

I MAINTAIN, that this SSH will work with other platform connections, IF they did not enforce this restriction; perhaps a 'warning' would suffice. Just in case.

But, I digress; YES, The showLoginTerminal = true; gets WIPED OUT.

**Comment by gitpbg** [comment]
Replaced machine names and usernames for privacy.
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
Confirming that machine is a valid reachable host
Running type "C:\Users\USERNAME\AppData\Local\Temp\vscode-linux-multi-line-command-MACHINENAME.sh" | ssh  MACHINENAME to confirm the host platform
Confirming that MACHINENAME  is a valid reachable host
Running type "C:\Users\USERNAME\AppData\Local\Temp\vscode-linux-multi-line-command-MACHINENAME.sh" | ssh  MACHINENAME to confirm the host platform
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> Warning: no access to tty (Bad file descriptor).
> Thus no job control in this shell.
> 
> stty: standard input: Inappropriate ioctl for device
> stty: standard input: Inappropriate ioctl for device
> stty: standard input: Inappropriate ioctl for device
> TERM: Undefined variable.
> 
> stty: standard input: Inappropriate ioctl for device
> stty: standard input: Inappropriate ioctl for device
> stty: standard input: Inappropriate ioctl for device
> TERM: Undefined variable.
> 
"uname" terminal command done
<machine name>: unreachable or not Linux x86_64. (TERM: Undefined variable.)
"uname" terminal command done
<machine name>: unreachable or not Linux x86_64. (TERM: Undefined variable.)

when I run uname -m on this machine I get:
uname -m
x86_64
uname -r
4.1.15.pnotify

**Comment by kieferrm** [comment]
@gitpbg what do you get when you run `uname -ms`?

**Comment by gitpbg** [comment]
uname -ms
Linux x86_64

**Comment by rivergold** [comment]
I met the same problem. And I think the error is caused by `ssh -T` in `Remote-SSH`. The followings are the `ssh -v` log:

```bash
debug1: Sending env LC_NUMERIC = zh_CN.UTF-8
debug1: Sending env LC_PAPER = zh_CN.UTF-8
debug1: Sending env LC_MEASUREMENT = zh_CN.UTF-8
debug1: Sending env LC_ADDRESS = zh_CN.UTF-8
debug1: Sending env LC_MONETARY = zh_CN.UTF-8
debug1: Sending env LANG = en_US.UTF-8
debug1: Sending env LC_NAME = zh_CN.UTF-8
debug1: Sending env LC_TELEPHONE = zh_CN.UTF-8
debug1: Sending env LC_CTYPE = en_US.UTF-8
stty: standard input: Inappropriate ioctl for device
TERM environment variable not set.
/etc/profile.d/bastion-client.sh: line 35:  6679 Killed                  /usr/local/share/.virtualenvs/security/bin/bastionssh.py -c
All identities removed.
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 4084, received 3812 bytes, in 2.5 seconds
Bytes per second: sent 1628.7, received 1520.2
debug1: Exit status 0
```

Is it possible to set `Remote-SSH` not use `-T`?

**Comment by roblourens** [comment]
Lots has changed, please open a new issue if there is still a problem.
