### ISSUE TITLE
Extensions view stuck loading while container is starting

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-remote-release#2430]
Ref #2415

When connecting to a container that is still initializing, the extensions view shows a constant loading screen, which makes it feel broken to me. Better messaging here might help?

**Comment by sandy081** [comment]
It's same everywhere and its trying to load extensions.

![image](https://user-images.githubusercontent.com/10746682/75338127-86e55c00-588e-11ea-92fe-20c94b8c6fdb.png)
