### ISSUE TITLE
Open repository keeps reusing broken local copy even after update is pushed

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-remote-release#2435]
Testing #2407

**Repo**
1. Using a repository with a container that has a `initializeCommand` that will fail (https://github.com/mjbvz/test-contianer/tree/715ae930cc472905d837c12c7548c23b550a8633)
1. Try opening this repo using the `Open Repository` command
1. It fails as expected
1. Now push an update the repository that fixes the issue
1. Run `Open repository` again and select the same location

**Bug**
VS Code still uses the old container definition. I can't figure out how to force it to update to the new repository definition.

I see the following logs:

```
[904 ms] fatal: destination path '/workspaces/test-contianer' already exists and is not an empty directory.
[929 ms] Repository 'mjbvz/test-contianer.git' was already cloned into '/workspaces/test-contianer'.
```

**Related**
- #2428

**Comment by chrmarti** [comment]
Could be solved with https://github.com/microsoft/vscode-remote-release/issues/2428#issuecomment-591349599.

**Comment by chrmarti** [comment]
The error dialog now offers to open a 'Recovery Container' in which the Git repo can be advanced to the latest commit.
