### ISSUE TITLE
Can not reconnect to the conatiner once the connection is lost

### ISSUE THREAD

**Issue by vpinnaka** [microsoft/vscode-remote-release#244]
Issue Type: <b>Bug</b>

When docker container is stopped, Remote container is disconnected and reconnecting screen appears. However, even after restarting the docker container Remote container is not able to reconnect and I can't close the `VScode` window at this time, the only way is forcefully quit the program from activity monitor.
**OS** : macOS 10.14.4  
![Screen Shot 2019-05-08 at 12 15 35 PM](https://user-images.githubusercontent.com/15952348/57401701-14827e80-718b-11e9-9126-9e37611cae46.png)

Extension version: 0.51.0
VS Code version: Code - Insiders 1.34.0-insider (daf71423252a707b8e396e8afa8102b717f8213b, 2019-05-06T22:07:35.830Z)
OS version: Darwin x64 18.5.0
Fetching remote diagnostics for 'attached-container+61313338303665623132313536636535336639376563343530316232373162386532353365396138316636353866343830336237663533363338343361373736' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|-psn_0_3933120|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'attached-container+61313338303665623132313536636535336639376563343530316232373162386532353365396138316636353866343830336237663533363338343361373736' timed out.
</details>

**Comment by chrmarti** [comment]
There is reconnection logic, but that only works if the remote extension host running in the container keeps running, so that does not apply when stopping the container.

We should probably bail out instead of trying to reconnect.
