### ISSUE TITLE
SSH maxReconnectionAttempts default value

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-remote-release#2444]
Issue Type: <b>Bug</b>

https://github.com/microsoft/vscode-remote-release/issues/2010

Instead of having `null` be the default which is treated as 8, would it be clearer to just make the default 8?

VS Code version: Code - Insiders 1.43.0-insider (b0be0672c210f1fa76109ce675365bb785657e84, 2020-02-26T05:28:00.237Z)
OS version: Darwin x64 18.7.0

remote-ssh-nightly|ms-|2020.2.35520

</details>

**Comment by roblourens** [comment]
The number of reconnection attempts is controlled by vscode, and it could change at any time. `null` is actually interpreted as 'infinity'. But I left the max in there as 8 to avoid confusing users who try to set it to 1000. But I dunno maybe it's another reason to move this setting to the core. Maybe I'll talk to Alex about it later.
