### ISSUE TITLE
Saturated Connections: Attempting to reconnect window repeatedly pops up and reconnects; steals keyboard every time

### ISSUE THREAD

**Issue by Imisnew2** [microsoft/vscode-remote-release#2445]
- VSCode Version: 1.42.1
- Local OS Version: MacOS 10.14.6
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to a remote machine.
2. Saturate the connection (e.g. initiate several downloads of sufficiently large files).
3. Watch, as the 'Attempting to reconnect...' window periodically pops up and reconnects

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

Although my connection is saturated, it's not actually disconnecting. Using the console, I can still type commands, even before the '... in 5 seconds.' timer has reached 0. In that sense, this is a bug. However, I'd be happy if there was an option to suppress the modal dialog popup that keeps stealing my keyboard (i.e. #760). This may be a duplicate of the more nebulous #246, but given it only happens to me when I've saturated my connection, I'm still filing this bug.

**Comment by roblourens** [comment]
Where are you typing commands, do you mean in the terminal?

**Comment by Imisnew2** [comment]
Yes, I meant the terminal.

**Comment by roblourens** [comment]
Can you try this? Run "Set Log Level", pick "Trace", and reproduce this issue again. Then share the   log from the "Log (Window)" output channel. It should have some more info about what we think disconnected.
