### ISSUE TITLE
userhome is set incorrectly when connecting to a Windows remote

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#2449]
Similar to https://github.com/microsoft/vscode-remote-release/issues/2276

It appears to be set to /home/alros when I use `"remote.SSH.useLocalServer": true,`, but if I use `remote.SSH.windowsRemotes` then it is correctly c:\users\alros

**Comment by roblourens** [comment]
Where are you seeing that? It looks like I am registering the right separator, where is the user home wrong?

**Comment by alexr00** [comment]
If you open have no files or folder open, and haven't opened any files or folders in that window you can see user home in the file picker by trying to open a file or folder.

**Comment by roblourens** [comment]
I did that but it looks correct to me 
![image](https://user-images.githubusercontent.com/323878/75698849-49087f00-5c64-11ea-94b0-58b2efae957f.png)

**Comment by alexr00** [comment]
Hmm. I had debug into and saw that it was set incorrectly in the environment. I can't test it again now because I'm not in the office, but if you don't see it then that's good enough for me.
