### ISSUE TITLE
Server Timeout

### ISSUE THREAD

**Issue by gartnera** [microsoft/vscode-remote-release#245]
It appears that the remote portion will keep running unless you specifically kill it. Could you add logic to automatically stop the server after an hour of inactivity? Or maybe just stop the server when the user closes the folder?

**Comment by egamma** [comment]
Which remote extension are you using?
The server is kept alive for 3hours in case you want to reconnect due to a connection loss. It will be killed afterwards. Didn't this happen?

**Comment by skarcha** [comment]
Same problem here. SSH extension.

**Comment by gartnera** [comment]
I'm using the SSH extension. The processes definitely don't shutdown after 3 hours of activity. I created a new environment and let it sit for >3 hours. See below.

```
$ ps auxf | grep vscode-remote
agartner  4013  0.0  0.0   4628   804 ?        S    15:24   0:00 sh /home/agartner/.vscode-remote/bin/daf71423252a707b8e396e8afa8102b717f8213b/server.sh --port=0
agartner  4020  0.0  0.0 1282824 43928 ?       Sl   15:24   0:04  \_ /home/agartner/.vscode-remote/bin/daf71423252a707b8e396e8afa8102b717f8213b/node /home/agartner/.vscode-remote/bin/daf71423252a707b8e396e8afa8102b717f8213b/out/remoteExtensionHostAgent.js --port=0
agartner  4334  0.0  0.0  14428  1120 pts/0    S+   23:15   0:00          \_ grep --color=auto vscode-remote
$ date
Thu May  9 23:15:20 UTC 2019
```
