### ISSUE TITLE
[WSL] VSCode hangs when using by 2 Windows users simultaneously

### ISSUE THREAD

**Issue by fadeevab** [microsoft/vscode-remote-release#2450]
- VSCode Version: 1.42.1
- OS Version: Windows 10 1909

![image](https://user-images.githubusercontent.com/5967447/75474412-a0c29400-599f-11ea-80ef-f967bacf5e9b.png)

Steps to Reproduce:

1. Login to User1
2. Open VSCode with WSL: it's OK
3. Login to User2 (don't logout the User1, don't close the VSCode).
4. Open VSCode with WSL: it hangs on the Opening Remote Connection

Does this issue occur when all extensions are disabled: Yes

Workaround: Go to User1 and close VSCode.

**Comment by noemartinez** [comment]
This is also happening to me. I have separate accounts for personal and work use, so it would be super nice to address this. 

VS Code 1.48.1
OS Version: Windows 10, Version 2004, Build 19041.450
