### ISSUE TITLE
Remote-WSL extension with C++ extension debugging not working

### ISSUE THREAD

**Issue by pieandcakes** [microsoft/vscode-remote-release#2453]
- VSCode Version: 1.42.1
- Local OS Version: Windows
- Remote OS Version: WSL Ubuntu 18.04
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Install C++ extension
2. Create a basic hello world app.
3. configure a new launch.json AND set `externalConsole` to "true"

Expected: External console to work

Actual:
VS Code hangs on "Wait for connection completion"

Notes:

* When Developer Tools is open, I see "ERR can't find terminal application 'xterm': Error: can't find terminal application 'xterm'" in the Console. What am I supposed to set it to?

* If I enable `traceResponse` logging to get the VS Code DAP messages, I see:
```
--> C (runInTerminal-30): {"type":"request","command":"runInTerminal","arguments":{"kind":"external","title":"cppdbg: a.out","cwd":"","args":["sh","/tmp/Microsoft-MIEngine-Cmd-99bqczdn.p3e"],"env":{}},"seq":30}
```
I expect that to launch `sh <filename>` and if I copy that command and enter it into a WSL window, debugging will start.

related to Microsoft/vscode-cpptools#4936

**Comment by weinand** [comment]
I don't think that the Ubuntu used with WSL has any graphical applications (e.g. "xterm") installed.
So by default there is no "terminal application" configured for the `"externalConsole": true` option.
Yes, you can try to install "xterm" yourself and configure it to run its UI in Windows.
But why the hassle?
Just set "externalConsole" to false and VS Code will happily use its built-in terminal.

**Comment by pieandcakes** [comment]
@weinand I think the comment is why is it just hanging. I don't see the protocol sending back a failure when it can't launch `xterm`.

From the extension standpoint, is it possible to tell when we are in the WSL scenario so we can force externalConsole to be false?

**Comment by weinand** [comment]
> I think the comment is why is it just hanging. I don't see the protocol sending back a failure when it can't launch xterm.

Ok, I'll look into this...

> From the extension standpoint, is it possible to tell when we are in the WSL scenario so we can force externalConsole to be false?

Yes, it is possible to find the type of remote extensionHost via the ??? API. But I do not recommend to disable "externalConsole" completely for WSL. A WSL user can install "xterm" and then it makes sense to set "externalConsole" to true.

**Comment by weinand** [comment]
I've created https://github.com/microsoft/vscode/issues/92380 to track the problem that no errors are property returned from the 'runInTerminal' DAP request.

**Comment by weinand** [comment]
With the fix for https://github.com/microsoft/vscode/issues/92380
the following alert is shown for the original problem:

![2020-03-11_12-25-59](https://user-images.githubusercontent.com/1898161/76412327-b5396000-6393-11ea-8a89-c7fbc2bc1894.png)

**Comment by pieandcakes** [comment]
@wardengnaw
