### ISSUE TITLE
When change the default ssh shell to powershell on windwos ssh server remote connection always fail.

### ISSUE THREAD

**Issue by zuoxiaofeng** [microsoft/vscode-remote-release#2454]
Issue Type: <b>Bug</b>

1. change the default ssh shell from cmd to powershell on windows ssh server
2. try open a windows ssh server remote window will failed.

VS Code version: Code - Insiders 1.43.0-insider (b0be0672c210f1fa76109ce675365bb785657e84, 2020-02-26T05:30:24.470Z)
OS version: Windows_NT x64 10.0.18362
Fetching remote diagnostics for 'SSH' failed: Connecting with SSH timed out

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (7.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: Connecting with SSH timed out
</details>Extensions: none

**Comment by roblourens** [comment]
I see, I did break this for windows hosts with powershell as the default shell. Should be fixed now.
