### ISSUE TITLE
Remote containers with TCP don't work on port 2376 unencrypted.

### ISSUE THREAD

**Issue by Yivan** [microsoft/vscode-remote-release#2458]
Hello,

This issue follow https://github.com/microsoft/vscode-remote-release/issues/2066 and discussion with @chrmarti @hholst80
Purpose is to start from fresh on just this issue for TCP now that the problem is detailled.

It has been found that if docker is started with port 2376 unencrypted, VSCode remote containers cannot connect to the docker remote host.

**Facts:**

Remote linux docker (on `vagrant-docker` hostname) run with:

```
/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock -H tcp://0.0.0.0:2376
```

On Windows, on powershell, running this command display well the list of containers (with environment variable `DOCKER_HOST=vagrant-docker:2376`):
```
docker ps
#... list of containers, all is ok
```

But VSCode remote containers cannot connect and list containers.
**Just changing the docker port to 2375, and VSCode manage to connect.**

As there is no reason that vscode cannot connect to 2376 unencrypted when docker cli client manage on its side, there is a problem / hardcoded value / forcing 2376 to be secure / etc. on the VSCode remote extension.

**What is expected:**
Like docker client can, VSCode remote extension should be able to connect, wihout having to force the port to 2375.

Thanks.

**Comment by chrmarti** [comment]
Is this still an issue? We remove our dependency on a library that might have caused this.

**Comment by Yivan** [comment]
We changed our port to 2375 of all our docker instance, so it will not be easy to check now.
I think you can close it and I will repost here or open new task linked to this one if we encounter the problem.

Thanks.

**Comment by chrmarti** [comment]
Closing, thanks.
