### ISSUE TITLE
ssh username not be used when use ssh port-forward

### ISSUE THREAD

**Issue by mozhata** [microsoft/vscode-remote-release#2462]
- VSCode Version:
```
$ code --version
1.42.1
c47d83b293181d9be64f27ff093689e8e7aed054
x64
```
- Local OS Version:
MacOS 10.15.3
- Remote OS Version:
```
Linux version 4.18.0-25-generic (buildd@lgw01-amd64-033) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019
```
- Remote Extension/Connection Type: SSH
**by port forward**  `ssh -L 22033:REAL_REMOTE_IP:22 -Nf jump@JUMP_ADDR_IP`
Steps to Reproduce:

1. "Add New Host" by enter "ssh root@127.0.0.1 -p 22033"
and get configfile `~/.ssh/config`
```
Host 127.0.0.1:22033
  HostName 127.0.0.1:22033
  User root
```
2. select connect to `127.0.0.1:22033`
and vscode prompt me to enter password for `mozhata@127.0.0.1` **wrong username**
details from terminal:
```
mozhata@127.0.0.1's password: 
```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
The config in the config file should actually have a line like `Port 22033`. That's what I get when I follow your steps. Could you try installing the Nightly version of the SSH extension instead, regenerate the config, and see whether that resolves your issue?

If not, you could just change the HostName to just `127.0.0.1` and add the Port line.

**Comment by mozhata** [comment]
> The config in the config file should actually have a line like `Port 22033`. That's what I get when I follow your steps. Could you try installing the Nightly version of the SSH extension instead, regenerate the config, and see whether that resolves your issue?
> 
> If not, you could just change the HostName to just `127.0.0.1` and add the Port line.

reinstall resolved, thanks very much !
