### ISSUE TITLE
Not keep ssh connection open

### ISSUE THREAD

**Issue by mbtolou** [microsoft/vscode-remote-release#2464]
Issue Type: <b>Bug</b>

reconnect message
detect wrong user

Extension version: 0.49.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 3.10.0-1062.12.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.11GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2B7b22686f73744e616d65223a2231302e302e302e313339222c2275736572223a22726f6f74227d/data3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.0.0.139|
|OS|Linux x64 3.10.0-1062.12.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (56 x 1200)|
|Memory (System)|251.61GB (1.69GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Please give more details, and include the log from the Remote-SSH output channel. Also you could try this with the nightly version of the extension which has many new fixes
