### ISSUE TITLE
Mozilla 'configure' script runs much slower in vscode-remote (ssh) terminal

### ISSUE THREAD

**Issue by jandem** [microsoft/vscode-remote-release#2465]
I use VSCode for SpiderMonkey development and I recently noticed that running the 'configure' script is _much_ slower (on the order of 11 seconds -> 50 seconds) in vscode-remote than when I use ssh directly and run it. Piping the output to /dev/null makes no difference.

Colleagues using a similar setup are seeing the same issue.

These are fast:
* ssh directly and run configure
* ssh manually from the vscode terminal without using the remote-development extension
* (nested) ssh login inside the vscode-remote terminal

Info:
- VSCode Version: 1.42.1
- Local OS Version: macOS 10.14.6
- Remote OS Version: Ubuntu 19.10
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. [Download](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Source_Code/Mercurial) mozilla-central or mozilla-unified source code (`hg clone https://hg.mozilla.org/mozilla-unified`)
2. Run `./mach bootstrap` once to install dependencies
3. Run `./mach configure` inside a vscode remote terminal and via a direct ssh connection and compare the times you get.

**Comment by moztcampbell** [comment]
I also am hitting this and notice that I reproduce the slowness by simply using `child_process.spawn` in a nodejs environment unrelated to vscode. I'm not clear which nodejs is slowing things down or if there are tricks that vscode could use.

**Comment by moztcampbell** [comment]
With some help from the firefox build team, we tracked it down to `ulimit` for open files being significantly different in the nodejs case versus ssh. This was causing some cleanup code in the firefox build system to be much slower.

Probably can be closed as not a vscode issue.

**Comment by jandem** [comment]
Closing. I'm glad we tracked this down :)
