### ISSUE TITLE
Remote Development with a docker container in the remote server

### ISSUE THREAD

**Issue by nijkah** [microsoft/vscode-remote-release#2467]
- VSCode Version: 1.42.1
- Local OS Version: Windows 10 Pro, 1909. (Build 18353.657). Local Docker Desktop is installed
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: **SSH**/**Docker**/WSL

I want to work in a container in a remote server. But it doesn't work.

Steps to Reproduce:

I checked these two articles.

(1) https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host
(2) https://code.visualstudio.com/docs/containers/ssh

(1) Failed. If I specify docker host as ssh information and accessed the server, it does not show any docker information as shown bellow. 

![image](https://user-images.githubusercontent.com/25769408/75732788-d87e6280-5d36-11ea-810d-0fa23129b519.png)

(2) Failed. I followed these steps.

1. I installed [Remote Development] extension in VS Code.
2. Remote-SSH: Connect to the host. It works fine.
3. I Installed [Docker] extension on the remoter server.
4. Now I can see my containers and images in a docker tab.
5. I clicked one container and clicked [Attach Visual Studio Code] and it says There are no running containers to attach to.

![docker](https://user-images.githubusercontent.com/25769408/75731338-baaefe80-5d32-11ea-8c40-cb1f83e7b413.PNG)

So, I followed steps in https://florian-kriegel.de/blog/?p=234, which uses ssh tunneling.
1. Add "docker.host": "tcp://localhost:23750" in settings.json for vs code. 
2. Open vs-code and open terminal with wsl. 
3. I type **ssh -NL localhost:23750:/var/run/docker.sock user@hostname**.
4. I clicked docker tab without additional Remote-SSH. It shows containers and images well.
5. I can attach to containers in the remote server.

But, I think this process is quite cumbersome and does not match with the documentation.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by anirudth** [comment]
Did you solve this issue? I also face issue (2)., i.e Docker extensions.

**Comment by nijkah** [comment]
> Did you solve this issue? I also face issue (2)., i.e Docker extensions.

Yes, you have to specify the docker socket in the terminal of vs code.
You can refer [this](https://florian-kriegel.de/blog/?p=234)

I wonder why maintainers do not include this in the documentation.

But, I recommend you to establish a direct ssh port in the docker container.
Then, you can access the container with just ssh plugin!

Steps for direct ssh are below,

1. When running docker, use -p option for port forwarding. Like this. docker run -p [remote port]:22 -it [docker image]
2. Install ssh server, allow "PermitRootLogin" in /etc/ssh/sshd_config, and run sshd.
3. Then you can just access the docker container from the remote server with "ssh root@[remote IP] -p [remote port]

**Comment by anirudth** [comment]
Oh cool. Thanks.
