### ISSUE TITLE
Remove SSH extension's `realpath` dependency 

### ISSUE THREAD

**Issue by mklemarczyk** [microsoft/vscode-remote-release#247]
Searched and no similar.
- VSCode Version:
- Version: 1.34.0-insider (user setup)
- Commit: 473af338e1bd9ad4d9853933da1cd9d5d9e07dc9
- Date: 2019-05-01T00:22:05.899Z
- Electron: 3.1.8
- Chrome: 66.0.3359.181
- Node.js: 10.2.0
- V8: 6.6.346.32
- OS: Windows_NT x64 10.0.17763
Local OS Version: 1809 Build 17763.437
Remote OS Version: SUSE Linux release 11 SP1
Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to remote host without VS Code server installed
2. The error message will be displayed in Output, saying that realpath not found.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Why to not include the bash realpath method in the installation script?
It have usage only there.

**Comment by roblourens** [comment]
We are in the process of removing this: https://github.com/microsoft/vscode-remote-release/issues/97

**Comment by mklemarczyk** [comment]
Thank you :) +1
