### ISSUE TITLE
Remote Containers Overwrites global git config credential.helper

### ISSUE THREAD

**Issue by nchandran3** [microsoft/vscode-remote-release#2470]
# Issue
VS Code ends up setting the global git config option `credential.helper` on containers to be a script that I believe helps use the native credential stores. 

Unfortunately, this causes issues when developing in containers where the home directory is mounted. Attaching to a container for development ends up clobbering git config globally, and causes issues when not developing using the remote containers extension. 

For example, if I open Ubuntu (WSL2) and do a `git config --global credential.helper store`, followed by running a docker container which mounts my home directory (it's a development container and we want to keep user settings from their environment), and then attach VS Code to the running container and do a `git config --global --list`, we can see that the `credential.helper` has been replaced. 

Looking at the details of the dev server installation, we can see the following line which is the culprit: 

```console
 Start: Run in container: command -v git >/dev/null 2>&1 && git config --global credential.helper '!f() { /home/username/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node /tmp/vscode-remote-containers-12a3bcf20e537e2721e9e699b4f54877d29da4fa.js $*; }; f' || true
```

Usually this isn't an issue but when I am not running the container and want to do git operations on the same machine subsequently after developing in the remote container, it ends up failing: 

```console
$ git pull upstream master
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '/tmp/vscode-remote-containers-58f75e3c959511b82ebef243f0240277c97936ca.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

This then ends up prompting me for my git credentials, and can be quite a nuisance -- especially when using a PAT. 

I end up having to issue a `git config --global credential.helper store` every time after disconnecting from the remote container.

# User Data
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19037

# Reproduction
Steps to Reproduce:

1. Attach VS Code to Running Docker Container

Ends up running the command when installing the `VS Code Server` on the container: 

Does this issue occur when you try this locally?:  No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by nchandran3** [comment]
Is any guidance available for this?

**Comment by chrmarti** [comment]
@nchandran3 I'll add a setting to turn this off.
