### ISSUE TITLE
Can't connect to windows remote with GnuWin32 installed

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#2471]
From https://github.com/microsoft/vscode-remote-release/issues/1721#issuecomment-593753001

```
[12:22:13.187] > uname -rsv
[12:22:13.243] > windows32 2.6.2 9200
```

**Comment by roblourens** [comment]
Thanks for pointing this out @suzuryo3893, I'd appreciate if you try it out in the next build of the Nightly version of this extension

**Comment by suzuryo3893** [comment]
I tried 2020.3.3840 - insiders says it is released  for an hour - but the issue still remains.
I will wait for the next build.

**Comment by roblourens** [comment]
Yeah should be `.5358`, thanks

**Comment by Ghostliming** [comment]
After modifying "\ HKEY_LOCAL_MACHINE \ SOFTWARE \ OpenSSH" in the registry to modify OpenSSH's defaultShell to CMD, using .5358 will work.
Thank you all!

**Comment by roblourens** [comment]
It should also work with powershell with the nightly version of the extension. I would appreciate you opening a new issue with the log from the Remote-SSH output channel from connecting with powershell and the nightly extension, if you want to dig into it some more.

**Comment by suzuryo3893** [comment]
I tried `.6782` and succeeded. Thank you.
FYI, I also tried on powershell and it also worked well.

**Comment by roblourens** [comment]
Thanks!
