### ISSUE TITLE
Stuck: [Remote - SSH 0.49.0] Setting up SSH Host DEV: (details) Initializing VS Code

### ISSUE THREAD

**Issue by playcock** [microsoft/vscode-remote-release#2472]
- VSCode Version: 1.42.1 (user setup)
- Local OS Version: Windows_NT x64 10.0.17763
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH
- Remote - SSH version 0.49.0

I have successfully used the vscode's extension Remote-SSH on a few remote servers. However, I cannot get past the "Acquiring lock" message in my vscode terminal on one particular server and would like to know how to. The terminal displays the "Acquiring Lock" line in the terminal and nothing else follows. I have even let this connection try to resolve itself overnight and it just time out.

I cannot determine if this is an issue with Remote-SSH vscode extension or if it is something on my end. I have confirmed with the Server Administrator that ssh configuration is identical between this server and the other server that I am using the Remote-SSH vscode extension successfully on. I am also authenticated on the server and it is not a firewall issue.

![image](https://user-images.githubusercontent.com/9416592/75803865-1edebc00-5d4d-11ea-9494-fd762224d0c5.png)
![image](https://user-images.githubusercontent.com/9416592/75803885-24d49d00-5d4d-11ea-9b15-2b3267bb21bf.png)
![image](https://user-images.githubusercontent.com/9416592/75803781-f8b91c00-5d4c-11ea-8098-a315f24a1ec8.png)

When the attempt appears to have finally timed out. The message that gets left is
```
[15:48:54.081] "install" terminal command done
[15:48:54.082] > Connection reset by <ip address> port 22
> 
[15:48:54.084] Install terminal quit with output: Acquiring lock on <vscode-remote-lock file>
[15:48:54.085] Received install output: Acquiring lock on <vscode-remote-lock file>
[15:48:54.090] Stopped parsing output early. Remaining text: Acquiring lock on <vscode-remote-lock file>
[15:48:54.090] Failed to parse remote port from server output
[15:48:54.092] Resolver error: 
[15:48:54.108] ------
```

**Comment by roblourens** [comment]
It looks like either some old installer process is stuck open, or it failed to clean up its lockfile for some reason. You could try manually deleting the lockfile at that path, or you could try installing the nightly version of the extension where I actually just made some improvements around the locking.

**Comment by playcock** [comment]
@roblourens I have manually deleted the .vscode-server directory recursively at /home/playcock/.vscode-server/ a couple of times before deciding whether to post this as a possible issue here.

How long ago did you make the new improvements to the nightly version? Have these updates been pushed out since after 2/28/2020? I ask because I have tried the nightly version on 2/28/2020.

**Comment by roblourens** [comment]
Yeah, that version of the nightly extension would have the latest stuff. Are you saying that even after cleaning up the server directory and connecting with the nightly, you get the same error? Could you try doing that again and sharing the log?

**Comment by playcock** [comment]
I'll try that again. Thank you for your attention on this. From what I have been connecting to successfully, the extension is meeting my expectations.

**Comment by playcock** [comment]
@roblourens I installed the nightly version and am able to connect successfully. Thank you for maintaining this. Will the updates in the nightly build that helped me connect successfully be part of your main build in version 0.50?

**Comment by roblourens** [comment]
Great, let me know if it comes up again. Yeah the new extension release will go out when we release the next VS Code update, either tomorrow or maybe Monday.
