### ISSUE TITLE
Support ${remoteWorkspaceFolder} in devcontainer.json

### ISSUE THREAD

**Issue by felipecassiors** [microsoft/vscode-remote-release#2473]
Provide a way to reference [VS Code variables](https://code.visualstudio.com/docs/editor/variables-reference) in [Remote Containers `devcontainer.json` `containerEnv` and `remoteEnv`](https://code.visualstudio.com/docs/remote/containers#_devcontainerjson-reference). Such as:

```json
"containerEnv": { 
  "WORKSPACE_FOLDER": "${variable:workspaceFolder}" 
}
```

**Comment by chrmarti** [comment]
There is `${localWorkspaceFolder}`, does that help?

**Comment by felipecassiors** [comment]
@chrmarti ${localWorkspaceFolder} resolves the host path for the workspace. I need the path in the remote container.

In my use case we have a "`bin`" folder, with executables, and wanted it to be part of an environment variable.

I made a trick using the `postCreateCommand` to make it work.

``` json
"postCreateCommand": "pip install -r virtualenv/requirements.txt; echo \"export PYTHONPATH=\"$(pwd):$(pwd)/pyplumbing\"\" >> \"$HOME/.bashrc\""
```

**Comment by chrmarti** [comment]
@felipecassiors Makes sense. (Thought we had this request somewhere, but can't find it anymore.)

**Comment by felipecassiors** [comment]
Right, but how about support all the VS Code variables instead of just one?

https://code.visualstudio.com/docs/editor/variables-reference

**Comment by felipecassiors** [comment]
Closed erroneously. 

Do you think it might be useful to support other VS Code variables as well?

https://code.visualstudio.com/docs/editor/variables-reference

**Comment by chrmarti** [comment]
Adding `containerWorkspaceFolder`, `localWorkspaceFolderBasename` and `containerWorkspaceFolderBasename` as per https://github.com/microsoft/vscode-remote-release/issues/2697#issuecomment-609854675.
