### ISSUE TITLE
[Feature Request] VSCode Setting to suppress "Could not find a non-windows SSH" toast

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-remote-release#2479]
This pops up every time since I'm using win32_openssh on my local machine as my SSH client for several reasons (native Keepass KeeAgent support, Kerberos, etc.) and don't install the local git SSH into my path. Since i'm using SSH keys the password warning is irrelevant.
![image](https://user-images.githubusercontent.com/15258962/75901611-a67f0600-5df3-11ea-91a8-e11be30bd185.png)

It's easy enough to dismiss by hitting ESC but allowing for a "I know what I'm doing" vscode setting would be nice.
Recommended Setting Name: `Remote.SSH.SuppressWindowsSSHWarning`

**Comment by roblourens** [comment]
Added "Don't show again" to that popup, thanks for the suggestion

**Comment by JustinGrote** [comment]
Don't show again is good enough, forgot that was an option! :)
