### ISSUE TITLE
Downloading VS Code Server results in "Error: connect ETIMEDOUT xxx.xxx.xxx.xxx:443 at TCPConnectWrap.afterConnect [as oncomplete]"

### ISSUE THREAD

**Issue by WooLNinesun** [microsoft/vscode-remote-release#2483]
I am following https://code.visualstudio.com/docs/remote/containers#_quick-start-try-a-dev-container

* Cloned https://github.com/Microsoft/vscode-remote-try-node
* Enter the `vscode-remote-try-node` folder with vscode-insider
* Clicked the "Open a remote window" at the bottom left
* Selected "Remote-Containers: Reopen in Container..."
* It now starts the building/installation process.

Once it reaches the "Start: Downloading VS Code Server", it errors out
```
[2020-03-05T15:38:14.414Z] [PID 21913] [159887 ms] 
[2020-03-05T15:38:14.415Z] [PID 21913] [159888 ms] 
[2020-03-05T15:38:14.417Z] [PID 21913] [159890 ms] Start: Downloading VS Code Server
[2020-03-05T15:38:48.221Z] [PID 21913] [193694 ms] Error: connect ETIMEDOUT 58.251.150.80:443
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
```

This exact thing happens on everything I tried to do:

* Open folder in container
* Open workspace in container
* Attach to running container
* Try a sample

My docker working fine. I can see my images and containers.
I can even see the containers that the Remote extension tries to create. They are stopped. But can be started and "Attach Shell" to.

---
VSCode Version:
```
$ code-insiders --version
1.43.0-insider
b53d3c26f35df3da2d3f2ed472e73c8edf4f90d0
x64
```
Extension Remote - Containers: 0.106.0
Docker Engine:
```
$ docker --version
Docker version 19.03.7, build 7141c199a2
```
OS
```
$ uname -a
Linux dellxps13 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
```

I also tried disabling Firewall(iptables). Same result

**Comment by roblourens** [comment]
Sorry for the late response. many things have changed since March. Please let me know whether this is still an issue.
