### ISSUE TITLE
Docker-Devcontainer: Launch.json ignores "terminal.integrated.shellArgs.linux"

### ISSUE THREAD

**Issue by mickare** [microsoft/vscode-remote-release#2484]
When running debugers in the `launch.json` configuration, the terminal settings for the shell (in `devcontainer.json`) are ignored.

- VSCode Version: 1.42.1
- Local OS Version: Ubuntu 19.10
- Remote OS Version: Docker image Ubuntu 18.04.4 LTS (osrf/ros:melodic-desktop-full-bionic)
- Remote Extension/Connection Type: Docker

**Steps to Reproduce:**
1. Add following lines to the `"settings"` in `devcontainer.json`:
```json
		"terminal.integrated.shell.linux": "/bin/bash",
		"terminal.integrated.shellArgs.linux": [
			"-l"
		]
```
2. Inside Dockerfile set a environment variable in `profile.d`:
```
RUN echo "export LAUNCH_VSCODE_TEST=1" > /etc/profile.d/05-vscode-test.sh
```
3. Add a `launch.json` configuration (e.g. GDB) and try to read the environment variable.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by Tyriar** [comment]
@weinand does debug ignore overwrite `shellArgs`?
