### ISSUE TITLE
Do not lookup local proxy when running remote

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2487]
https://github.com/microsoft/vscode-docker/issues/1648

For local containers the local lookup makes sense, but not for remote SSH hosts or remote containers.

**Comment by chrmarti** [comment]
@aeschli @roblourens I'm introducing an additional option for resolvers to turn on using the local proxy in the remote extension host. The default will be off (unlike today).
- For WSL we'd want that to always be on because WSL runs in the same network as its Windows host. I.e., adoption needed.
- For SSH we'd want that to be off because an SSH host can be anywhere. I.e., no adoption needed.
- For Containers we can try to be smart and turn it on when running with local containers and turn it off when using remote containers. I.e., adoption needed.

**Comment by aeschli** [comment]
I released a new version of remote-WSL for 1.44 with the new `--no-host-proxy` parameter.
