### ISSUE TITLE
`Local Server Download` download same file too many times.

### ISSUE THREAD

**Issue by zeed-w-beez** [microsoft/vscode-remote-release#2488]
### Can you just use commit hash as part of the folder name instead of a timestamp ?

I use the [insider version of vscode](https://code.visualstudio.com/insiders/)(release each day) and have several SSH remote targets configured.  

Everytime after I upgrade the vscode version, and use the __same new__ version vscode to connect to different SSH target, the `vscode-server-linux-x64.tar.gz` file will be downloaded again and again. But the content is exactly the same.

![image](https://user-images.githubusercontent.com/20834022/76140918-380fa180-609a-11ea-9827-737ccf25568e.png)

![image](https://user-images.githubusercontent.com/20834022/76141396-bff7aa80-609e-11ea-8d88-0615c9ffdd0c.png)

**Comment by roblourens** [comment]
Would it help to just delete that file after it is downloaded and transferred to the remote? Are you concerned about the extra time to redownload it, or the storage space of having multiple copies?

**Comment by zeed-w-beez** [comment]
@roblourens The main concern is to spend repetitive time. This can be annoying when the internet speed is not good.

My suggestions: I prefer to do this in a predictable way. So in some special cases, I can complete these steps manually. Download with url `https://update.code.visualstudio.com/commit:{{HASH}}/server-linux-x64/insider` , scp to remote `~/.vscode-server-insiders/bin/{{HASH}}/` then unzip it. If so, security is also an aspect to consider.

**Comment by zeed-w-beez** [comment]
Well, I can't find where the source code is, can you show me where it is? 
Is it open source?

**Comment by roblourens** [comment]
It's not open source

**Comment by roblourens** [comment]
Nervous about doing this because sometimes there are issues with getting an invalid download, like when going through a proxy that messes with traffic, and it's less safe to reuse a download from a previous run. Going to close this as out of scope.
