### ISSUE TITLE
SSH: Connecting with "bash" command may result in broken shell session

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode-remote-release#2490]
Extension version: 0.49.0
VS Code version: Code - Insiders 1.43.0-insider (5996fb81591e92fd0c547dc45e3f0350026d5962, 2020-03-06T23:17:52.931Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 el7.x86_64

The server environment I'm using behaves differently depending on whether "bash" is used as SSH command or not. Compare:
```sh
$ ssh <server> bash
echo $SHELL
/bin/bash
echo $TMPDIR

```
(Note the missing `$` after login)
vs.
```sh
$ ssh <server>
# ...long login banner...
(base) -bash-4.2$ echo $SHELL
/bin/bash
(base) -bash-4.2$ echo $TMPDIR
/path/to/tmp/dir/...
```
The first shell is essentially broken and has none of the usual environment variables like $TMPDIR defined. This is an issue because VS Code Remote uses the first form and then doesn't get the correct $TMPDIR etc. Note that the visible "user" terminal sessions inside VS Code are fine, they seem to be launched without "bash" as command.

I'm not sure if this is an issue with the server or not (I'm not controlling it and it will likely never change), but VS Code should have the option to not explicitly launch "bash" when connecting to avoid such issues.

**Comment by roblourens** [comment]
Can you try with the nightly version of the extension? It doesn't do that anymore.

**Comment by letmaik** [comment]
I just tested it, works great! Thanks!

**Comment by roblourens** [comment]
Great, thanks for trying it!

**Comment by dmey** [comment]
Has this been broken?  

```
Name: Remote - SSH (Nightly)
Id: ms-vscode-remote.remote-ssh-nightly
Description: Open any folder on a remote machine using SSH and take advantage of VS Code's full feature set.
Version: 2020.3.44100
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly
```

```
Version: 1.43.2 (user setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by letmaik** [comment]
@roblourens I'm seeing this issue again after updating Insiders. Can't connect to my VM anymore because it appends "bash" as command. Can you fix this? It's kinda blocking.

```
Version: 1.45.0-insider (user setup)
Commit: 2225d77536d12fea2eda04930f431a5eb0930bba
Date: 2020-04-09T09:22:11.706Z (1 wk ago)
OS: Windows_NT x64 10.0.18363
```

SSH extension: 2020.4.9540 (also tried stable)

**Comment by letmaik** [comment]
Hm, very confusing... I tried with regular non-insiders VS Code and there it worked. And then I went back to Insiders and it started working again.

**Comment by roblourens** [comment]
Sorry for the confusion. I changed the default of the `remote.SSH.useLocalServer` setting then changed it back recently. I think that you want `"remote.SSH.useLocalServer": true`.
