### ISSUE TITLE
remote ssh unstable connecting to small AWS instances 

### ISSUE THREAD

**Issue by IanBadcoe** [microsoft/vscode-remote-release#2491]
- VSCode Version: 1.42.1
- Local OS Version: Windows 10 1909
- Remote OS Version: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-1060-aws x86_64)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. setup an AWS t2 micro instance with an ssh access key
2. connect to that via code/remote/ssh using a local key (mine has a passphrase, this may not be a factor)
3. edit files on the remote workspace for some time

Result:
- after a moderate time the "will reconnect in XX seconds dialog appears"
- after that disappears the status pop-up says reconnecting/installing
- terminal window never progresses to asking for the passphrase, however
- remote machine become uncontactable and AWS monitoring shows it at 100% CPU
- subsequent investigation of logs on remote machine (after forced reboot) suggest that the code client uses Node and that multiple Node processes have consumed all available memory and been terminated by the OS

It is not clear whether the remote client code develops a problem and this terminates the connection, or the momentarily dropped connection triggers the problem.

I would investigate further but a complete crash and reboot cycle takes at least 10 minutes so I'm going back to accessing via a Samba mapped drive which seems to be completely stable, if a touch slow at times...

**Comment by roblourens** [comment]
This is probably related to https://github.com/microsoft/vscode-remote-release/issues/2349. You can confirm by checking whether the busy processes are the fileWatcher processes.

**Comment by IanBadcoe** [comment]
I thought I had replied on here before, sorry.

It depends what you mean by "large folder" the total source files are few, but there is a git repo in there as well, which adds a lot of overhead, there's 1470 files in total...

I see Why you think this is the same issue as #2349, e.g. the repeated attempts to reconnect and the instance CPU maxed out...  However I don't have any report files in my home directory...

**Comment by roblourens** [comment]
I don't always get report.json files, only once in a while. But there is definitely an issue with processes running wild and then the client getting disconnected.
