### ISSUE TITLE
Progress bar, or dedicated download pane

### ISSUE THREAD

**Issue by devolution2409** [microsoft/vscode-remote-release#2492]
Hi,
Tried to search in opened issues for 'progress bar', didn't find it.

Would it be possible to implement a progress bar when you download a file using context menu on a file in the project tree?

Or some pane containing the ongoing download aswell as their progress?
For large files it becomes quite tedious to view the progress by refreshing the folder in explorer.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/73996
