### ISSUE TITLE
remote ssh window seams read local env variables.

### ISSUE THREAD

**Issue by niudai** [microsoft/vscode-remote-release#2494]
- VSCode Version: 1.42.1
- Local OS Version: Microsoft Windows [Version 10.0.19577.1000]
- Remote OS Version:  Ubuntu 16.04.6 LTS
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1. set local environment variable 'http_proxy' and 'https_proxy' to 127.0.0.1:10809
2. open remote window using remote-ssh extension which connects to remote ubuntu server.
3. "Markdown Pdf " extension pops up info window saying that download chromium is failed due to connecting error with 127.0.0.1:10809. So it seems vscode is still using '127.0.0.1:10809' as the https proxy, but $https_proxy env variable on ubuntu remote machine is '127.0.0.1:10808'. 

According to vscode setting, if 'http.proxy' is not set, it would use 'http_proxy' and 'https_proxy' environment var as the default proxy. In the remote vscode, I think it would read the env var on the remote machine, not the local machine.

Proxy on remote server works just fine,  so the issue is temporaly solved by setting http.proxy in `./vscode/settings.json`.

So the thing is vscode try to read http_proxy env var on local machine even if I'm connecting to linux server, and the https downloading is made indeed by remote machine, which is kind of not consistent.

What I wish is the proxy is automatically set according to the env var in the remote machine.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
This is https://github.com/microsoft/vscode-remote-release/issues/2487
