### ISSUE TITLE
Remote-Containers: Forward Port from Container reports "no commands matching"

### ISSUE THREAD

**Issue by mwoodpatrick** [microsoft/vscode-remote-release#2496]
I'm following the README.md in vscode-remote-try-php and everything is running as expected and I'm able to run the 

   php -S 0.0.0.0:8000

and Linux reports:

      [Mon Mar  9 12:04:44 2020] PHP 7.4.3 Development Server (http://0.0.0.0:8000) started

but when I enter 

     Remote-Containers: Forward Port from Container

in the command palette I get

   No commands matching

I don't see this command listed in the palette see attached image. What am I doing wrong, what's the best way to debug this?

![forward_port](https://user-images.githubusercontent.com/2222402/76211697-0d216c80-61c4-11ea-8ce0-6ffb878f969c.jpg)

**Comment by chrmarti** [comment]
We recently remove that command. Should be fixed in 0.106.0 of the extension.

**Comment by mwoodpatrick** [comment]
Si what's the replacement command & where can I find the documentation on this change

**Comment by chrmarti** [comment]
It is just `Forward a Port` now. It is more convenient to use the Forwarded Ports section of the Remote Explorer:
![image](https://user-images.githubusercontent.com/9205389/76329377-c713f800-62ec-11ea-8152-c2a6e88a525d.png)


@Chuxel https://code.visualstudio.com/docs/remote/containers#_temporarily-forwarding-a-port needs a small update on this.

**Comment by mwoodpatrick** [comment]
Many thanks for the pointer & picture the latter really help and is much appreciated. When I read the description in the php example:

     https://github.com/Microsoft/vscode-remote-try-cpp

I was expecting there to be a command in the palette with the string: "Remote-Containers: Forward Port from Container" and that was absent

Press <kbd>F1</kbd> and run the **Remote-Containers: Forward Port from Container...** command.
   - Select port `8000`.
   - Click "Open Browser" in the notification that appears to access the web app on this new port.

**Comment by Chuxel** [comment]
@chrmarti I'm reopening this as a doc issue to help anyone else that hits this.  I hadn't realized this change had happened, so all docs are not out of date.  All try repos in addition to docs and some dev container definition READMES will need an update.

**Comment by mwoodpatrick** [comment]
Many thanks BTW what is the URL for the github source repository for the REMOTE extension?

**Comment by chrmarti** [comment]
The remote extensions are not open source. Please see the [FAQ](https://code.visualstudio.com/docs/remote/faq#_license-and-privacy) for details.

**Comment by mwoodpatrick** [comment]
Anyone know where there is schema definition for devcontainer.json as opposed to scattered usage examples?

**Comment by chrmarti** [comment]
That happens to be here (for technical reasons): https://github.com/microsoft/vscode/blob/master/extensions/configuration-editing/schemas/devContainer.schema.json

**Comment by Chuxel** [comment]
This is now updated.
