### ISSUE TITLE
Kerberos Authentication for Remote SSH

### ISSUE THREAD

**Issue by zdog234** [microsoft/vscode-remote-release#250]
Hello! We use gssapi (kerberos) authentication for connecting to our on-prem computing environment w/ PuTTY. I'm not sure what would be necessary to make this work, but it would be awesome if I could use kerberos authentication with vscode remote.

Thanks! Loving this extension :)

**Comment by DavidA2014** [comment]
I'm using VS Code Stable 1.35.1 on Windows 10 with Remote SSH 0.42.2.

I can connect to a Centos 7.6 machine using Kerberos authentication (with public SSH key installed on remote machine).  The remote connection is working and I'm not prompted for password.  I'm afraid I don't understand these authentication mechanisms and so don't know what to expect. But I hope this feedback is useful.

**Comment by avylove** [comment]
@DavidA2014 it sounds like you're using ssh keys not Kerberos to authenticate.

@zdog234 This is more of a problem with the SSH clients for Windows. I haven't tested the Microsoft openssh clients, hopefully they support Kerberos.

Here's a small hack to use a Kerberos-enabled plink instead. This assumes you have a system install of VSCode on the client and you're using Centrify PuTTY, but adjust the paths to match your installation.

Create  **C:\Program Files\Microsoft VS Code\bin\ssh.bat** with the following contents.
`"C:\Program Files (x86)\Centrify\Centrify PuTTY\plink.exe" -ssh -K %*`

I also posted this on [StackOverflow](https://stackoverflow.com/questions/56030686/is-it-possible-to-use-kerberos-authentication-with-visual-studio-code-remote/56781481#56781481)

**Comment by avylove** [comment]
Previous plink workaround broke with the June release because they added some options to the ssh command that aren't supported with plink.

**Comment by blaylockbk** [comment]
For the record, the plink.exe method worked for me today with vscode 1.59.0. (Some have reported it was broken).
I followed the answer here: https://stackoverflow.com/a/60780533/2383070

1. Install Remote SSH extension
![image](https://user-images.githubusercontent.com/6249613/128911983-e09c5819-604d-4b00-9d78-30d296f78b99.png)


2. Create file `C:\Users\<userName>\ssh.bat` with the following contents:
```
echo OpenSSH
powershell -NoProfile -ExecutionPolicy Bypass %~dp0ssh.ps1 %*
```

3. Create file `C:\Users\<userName>\ssh.ps1` with the following contents:
```
$ArgArray = [System.Collections.ArrayList]$Args
$ind = $ArgArray.IndexOf("-F")
if ($ind -ge 0) {
  $ArgArray.RemoveAt($ind)
  $ArgArray.RemoveAt($ind)
}
Write-Host $ArgArray
& 'C:\path\to\plink.exe' $ArgArray
```

4. In VS Code user settings, set remote SSH path to the ssh.bat file you created
![image](https://user-images.githubusercontent.com/6249613/128911668-7670401d-7e60-4e65-9b96-4fc5f5260729.png)

```
"remote.SSH.path": "C:\\Users\\<userName>\\ssh.bat",
```

5. In Putty, save a session for your remote server
![image](https://user-images.githubusercontent.com/6249613/128914313-0dc76ce5-ccda-472d-8a07-cc0fa2c6b794.png)

6. In VS Code, open the Remote Explorer side panel and configure a new remote to the name of your saved Putty profile.
```
Host myRemote
  HostName myRemote
  User userName
```

**Comment by lxchx** [comment]
If you have already configured Kerberos Authentication on WSL, then you can also use the following method to connect to remote server using WSL.
1. Install Remote SSH extension
2. Create file C:\Users\<userName>\ssh.bat with the following contents:
```
wsl --exec ssh %*
```
3. In VS Code user settings, set remote SSH path to the ssh.bat file you created
4. Configure your remote server in vs code (and also sync to WSL).
5. Enjoy
> PS: This method uses ssh in WSL, which means that the configuration for ssh is in ~/.ssh/config in WSL, not the windows counterpart. You may consider copying this configuration file to windows periodically.

**Comment by FelixLange1998** [comment]
> For the record, the plink.exe method worked for me today with vscode 1.59.0. (Some have reported it was broken). I followed the answer here: https://stackoverflow.com/a/60780533/2383070
> 
> 1. Install Remote SSH extension
>    ![image](https://user-images.githubusercontent.com/6249613/128911983-e09c5819-604d-4b00-9d78-30d296f78b99.png)
> 2. Create file `C:\Users\<userName>\ssh.bat` with the following contents:
> 
> ```
> echo OpenSSH
> powershell -NoProfile -ExecutionPolicy Bypass %~dp0ssh.ps1 %*
> ```
> 
> 3. Create file `C:\Users\<userName>\ssh.ps1` with the following contents:
> 
> ```
> $ArgArray = [System.Collections.ArrayList]$Args
> $ind = $ArgArray.IndexOf("-F")
> if ($ind -ge 0) {
>   $ArgArray.RemoveAt($ind)
>   $ArgArray.RemoveAt($ind)
> }
> Write-Host $ArgArray
> & 'C:\path\to\plink.exe' $ArgArray
> ```
> 
> 4. In VS Code user settings, set remote SSH path to the ssh.bat file you created
>    ![image](https://user-images.githubusercontent.com/6249613/128911668-7670401d-7e60-4e65-9b96-4fc5f5260729.png)
> 
> ```
> "remote.SSH.path": "C:\\Users\\<userName>\\ssh.bat",
> ```
> 
> 5. In Putty, save a session for your remote server
>    ![image](https://user-images.githubusercontent.com/6249613/128914313-0dc76ce5-ccda-472d-8a07-cc0fa2c6b794.png)
> 6. In VS Code, open the Remote Explorer side panel and configure a new remote to the name of your saved Putty profile.
> 
> ```
> Host my.remote.address
>   HostName myRemote
>   User userName
> ```
> 
> ☝🏻 one issue with the above method is that now all SSH connections are authenticated with plink. However, you might need to connect to some remotes with the standard SSH method. I modified the `ssh.bat` file to specify which remotes to use the plink method and use the standard SSH executable for all others:
> 
> ```
> @echo off
> 
> if %1 == -V GOTO :version
> if %4 == "myFirst.remoteHost.address" GOTO :plink
> if %4 == "mySecond.remoteHost.address" GOTO :plink
> if %4 == "myThird.remoteHost.address" GOTO :plink
> 
> REM use the built in ssh by default
> GOTO :default_ssh
> 
> :version
> echo OpenSSH
> GOTO :eof
> 
> :plink
> powershell -NoProfile -ExecutionPolicy Bypass %~dp0ssh.ps1 %*
> GOTO :eof
> 
> :default_ssh
> ssh.exe %*
> GOTO :eof
> ```

I just tried to set up Kerberos authentication like it was suggested here, however, upon selecting the remote host for the remote connection, the Kerberos dialogue pops up to get a new ticket even though I already have an existing ticket that still works. When I connect with putty directly the ticket is used correctly. Do you have any suggestions?

**Comment by DayBeha** [comment]
> 

Do you know how to do this on Ubuntu?

**Comment by turtlewi9** [comment]
Can this be modified to connect with an oracle keberos connection?

**Comment by magnuzno** [comment]
> For the record, the plink.exe method worked for me today with vscode 1.59.0. (Some have reported it was broken). I followed the answer here: https://stackoverflow.com/a/60780533/2383070

When I try this method today, I am stuck with the error:
```
Checking ssh with ""remote.SSH.path": "C:/Users/magnuzno/ssh.bat", -V"
Got error from ssh: spawn "remote.SSH.path": "C:/Users/magnuzno/ssh.bat", ENOENT
The specified path "remote.SSH.path": "C:/Users/nomar/ssh.bat", is not a valid SSH binary
```
VSCode then proceeds to try other SSH clients until it gets to OpenSSH, which fails because it doesn't have "myRemote" mapped. Anyone able to get VSCode to use plink today? Or perhaps this work around is now broken?

**Comment by magnuzno** [comment]
`login as: 
FATAL ERROR: No supported authentication methods available (server sent: gssapi-keyex,gssapi-with-mic)`

I've made progress but I am still stuck. I was successful in getting VSCode to attempt ssh via plink. Now, it seems the gssapi authentication is not getting applied correctly when trying to login to the server. 

I have it configured in Putty. When I use the Putty GUI to login to "myRemote" saved session it logs in no problem. For some reason I'm still unsuccessful with VSCode using the method here.

I re-read my own comment and was able to fix my previous problem. It was a rookie mistake but in case it affects anyone else, here's where I was confused:
Remote.SSH: Path field in the GUI should simply read C:\Users\<<user>>\ssh.bat. @blaylockbk shares a code block but that is what the resulting settings.json file should display. That is not what you put into the GUI field.

**Comment by magnuzno** [comment]
To revisit the gssapi issue I was having. In this case, the fix was ensuring the username was defined in the Putty session. I had the username defined in the config file, but not in Putty. VS Code was not prompting for the username since it was in the config file but also not correctly passing the username / authentication. Easy fix!
