### ISSUE TITLE
"Open Web UI" command doesn't work

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#2503]
The SSH extension uses `openExternalUri` with a URI with the local forwarded port, but that command actually expects the remote port and tries to set up a new port forwarding.

I think the only way to fix it is to use the remote port and let vscode set up a new port forwarding.

**Comment by joaomoreno** [comment]
How can I run this `Open Web UI` command?

**Comment by roblourens** [comment]
- Set `"remote.SSH.enableWebAccess": true`
- Run "Kill VS Code Server On Host" and reconnect to install the server with the web ui
- Run that command in the command palette

**Comment by joaomoreno** [comment]
After step 2 now I get this:

![image](https://user-images.githubusercontent.com/22350/83767760-4f046680-a67e-11ea-8b55-1e36d328faab.png)

**Comment by roblourens** [comment]
Oh, I think that's ok. I could fall back more gracefully but we don't really expect this to be a common real user use case, that's why the setting is private.

**Comment by misolori** [comment]
Verified that this command opens the web version of VS Code that's connected to the remote (which is 👌 nice). Though I do see the various different icons (red vs green), but don't think it's for this issue.

![image](https://user-images.githubusercontent.com/35271042/83807242-9af7e100-a667-11ea-9712-978939810212.png)
