### ISSUE TITLE
Support for non-blocking connection failures/retries

### ISSUE THREAD

**Issue by bgreenlee** [microsoft/vscode-remote-release#2505]
I do a lot of my remote work on VMs that are only accessible when I'm connected to our corporate VPN. When I wake up my laptop from sleep, before I've had a chance to connect to our VPN, the VSCode windows with remote projects open pop up a dialog with "Cannot reconnect. Please reload the window."

![cannot-reconnect](https://user-images.githubusercontent.com/2901/76263872-4d610900-621d-11ea-8062-9a9d65ebeead.png)

I have to go through and click Reload Window on each one (usually twice, for some reason) in order to get VSCode's icon to stop bouncing angrily at me.

I would prefer that it not pop up any modal dialogs, and instead perhaps turn the remote host panel in the status bar red, or wait to pop up the dialog until I do something in that window that requires remote access.

**Comment by roblourens** [comment]
Well, everything in the window requires remote access, so I can't do exactly what you suggest, however we do try to reconnect without reloading the window. After some fairly long amount of time retrying, we give up and you will see this message. Also if the failure appears to be a failure that we can't recover from, we won't retry and you will see this message.

When you get this, can you share the log from the Remote-SSH output channel? Then I can tell whether it timed out retrying, or whether reconnecting gave an error that it might actually be able to recover from.

**Comment by xgdgsc** [comment]
I hope there is an option to not make the window alert on taskbar. With more than 20 window open connecting to dozens of servers opened using vscode remote, it is a pain to click on task bar to make it normal.  I usually won' t need that much connection but want to keep the window open. So I just want an option to disable the alert on taskbar on disconnection. I will need that connection only when I open the window.
