### ISSUE TITLE
Debugging in docker container -- unable to read file

### ISSUE THREAD

**Issue by bferg88** [microsoft/vscode-remote-release#2506]
Issue Type: <b>Bug</b>

Debugging in a container, VS Code reports it is unable to open any files. The path it gives that it cannot open is at :"/workspace/..." -- but VS Code mounts at "/workspaces/...", so of course it's not finding any files. 

Extension version: 0.106.0
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:44:52.965Z)
OS version: Linux x64 5.3.0-40-generic
Remote OS version: Linux x64 5.3.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.43GB (5.58GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Shrug|
|OS|Linux x64 5.3.0-40-generic|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4400)|
|Memory (System)|15.43GB (5.58GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Did you attach to an existing container or did you create the container with a devcontainer.json?

**Comment by bferg88** [comment]
My apologies. I built the project, then renamed the directory, so when I went to debug. The debugger was reporting source files to be in locations that had since changed. Sorry to waste your time.
