### ISSUE TITLE
code -r filename to open file from the built-in terminal

### ISSUE THREAD

**Issue by shi-yan** [microsoft/vscode-remote-release#251]
vscode can open a file from commandline:

code -r filename.

if would be nice to have the same feature when using vscode with a container.

sometimes, I need to modify a config file on the container, and the file is outside my project folder. it would be nice if the built-in terminal can open that file for editing.

**Comment by aeschli** [comment]
In a remote window, open the integrated terminal and use `code-insiders fileName/folderName`. That's already implemented.
In WSL you can also do it from a WSL shell (not only the integrated terminal)

Is that what you were looking for?

**Comment by shi-yan** [comment]
yes, this is what I looked for. Thank you!
