### ISSUE TITLE
Not able to connect to aws from windows vscode remote ssh

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-remote-release#252]
Issue Type: <b>Bug</b>

set the config file.
it keeps on saying "confirming that <host> is reachable

Extension version: 0.36.0
VS Code version: Code - Insiders 1.34.0-insider (daf71423252a707b8e396e8afa8102b717f8213b, 2019-05-06T22:08:08.969Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (8.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Can you show the full log from the "Remote - SSH" output channel?

**Comment by bamurtaugh** [comment]
Since this issue is quite old and from a now deleted user, going to close it out.
