### ISSUE TITLE
Key password saved after restart but not in ssh-agent, and is unsaved after various actions

### ISSUE THREAD

**Issue by sfsccn** [microsoft/vscode-remote-release#2521]
- VSCode Version: 1.43
- Remote - SSH: 0.50.0
- Local OS Version: Windows 10 1903 (with Windows OpenSSH)
- Remote OS Version: Ubuntu 19.10
- Remote Extension/Connection Type: SSH

**Summary**

I just upgraded to 1.43. Now, there are times when I can connect to a remote machine using a key pair and I don't need to enter the password again after restarting VSCode. When this happens, I don't see the key in the Windows OpenSSH agent via `ssh-add -l`. Certain actions cause the password to no longer be saved (see below). This persists even after manually adding keys to the agent via `ssh-add`. I thought VSCode used the agent but that no longer seems to be the case. The [1.43 remote release notes](https://github.com/microsoft/vscode-docs/blob/master/remote-release-notes/v1_43.md) do mention a new "connection sharing" feature, perhaps that explains what I'm seeing here?

**Steps to Reproduce**

1. Open a connection to a remote linux machine in Remote Explorer
2. VSCode asks for the key password: enter it
3. After a successful connection exit VSCode
4. Open VSCode: key password is not required, it connects to remote linux machine without it
5. Open Windows shell (command prompt or powershell, with or without admin privileges)
6. Enter `ssh-add -l`. **Expected**: ssh key used above is listed. **Actual**: "The agent as no identities". 

If the keys aren't in the agent, how are they saved? How can they be deleted?

**The key password is somehow unsaved after simply opening another program**

1. Repeat steps 1-3 above
2. Open PowerShell but don't do anything in it
3. Close PowerShell (required)
4. Open VSCode: this time it asks for the key password. Just opening PowerShell somehow unsaves the key password? Furthermore, it asks for the key password even after I've added manually the key to the agent using `ssh-add` in Windows PowerShell. This is unexpected, I thought VSCode used the agent.
5. Other programs besides PowerShell have the same effect: Command Prompt, Word, Excel

**The key password is also unsaved after opening a different ssh connection**

1. Repeat steps 1-3 above for linux machine A
2. Open a different connection to a new linux machine B. It asks for a key password. Enter it and connect successfully, then exit VSCode.
3. Open VSCode and connect back to machine A. Now it asks for the key password. The process of connecting to a new machine seems to unsave the key password. Is that what's supposed to happen in the new "connection sharing" feature?

**Keys in the Windows ssh-agent are not forwarded to the remote**

1. Ensure that `ForwardAgent yes` in set the ssh configuration file for a remote
2. Load a key in the Windows agent using `ssh-add` in PowerShell or Command Prompt
3. Connect to the remote
4. While in the remote, ssh to another machine that has this key in `authorized_keys`
5. **Expected**: key is forwarded, no password required. **Actual**: password required, key not forwarded. I think the expected behavior occured in previous versions of VSCode. I suppose this is consistent with the observations above that the Windows agent is no longer used?

**Using VSCode Insiders Version 1.44**

The Insiders Version does not seem to save the key password at all, it needs to be entered every time. This happens even if I add the key to the agent using `ssh-add`. 

Overall, I thought key passwords were managed in the Windows OpenSSH agent as described [here](https://code.visualstudio.com/docs/remote/troubleshooting#_installing-a-supported-ssh-client). Has the system changed? What's the new system?

Thanks.

**Comment by sfsccn** [comment]
These issues appear to be resolved by changing `remote.SSH.path` (initially blank)  to `C:\WINDOWS\System32\OpenSSH\ssh.exe` as described in #2522.

**Comment by roblourens** [comment]
Sorry for the trouble. Yes, your workaround is what I recommend for now.

**Comment by roblourens** [comment]
I will dupe this against https://github.com/microsoft/vscode-remote-release/issues/2522
