### ISSUE TITLE
Not differentiating between wsl and windows

### ISSUE THREAD

**Issue by kmc79** [microsoft/vscode-remote-release#2526]
I have wsl enabled on my remote Windows machine, with its ssh server listening on port 123
I also have the remote Windows ssh server listening on port 124

When I ssh from command line to the wsl one, it correctly brings me to '/home/user/'
When I ssh to Windows it brings me to the 'C:/users/' dir

My ssh config file is set up like:

Host remotePC
    HostName 192.168.168.30
    User myusername
    Port 124

Host remoteWsl
    HostName 192.168.168.30
    User myusername
    Port 123

When I connect to remoteWsl in vsc it correctly opens up in the wsl.
When I connect to remotePC in vsc it still brings me to the wsl.

My guess is this is because the remote server is running vscode on just one port (the wsl one) and this is what its connecting to.

Is this type of setup possible?

- VSCode Version: 

Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

- Local OS Version: Windows 10.0.18362
- Remote OS Version: 10.0.18363
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Configure ssh host to connect to wsl on remote server
2. Configure ssh host to connect to remote windows server
3. In vscode attempt to connect to windows ssh host

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Have you disabled the `useLocalServer` setting? If so, you need to add the host to the `remote.SSH.windowsHosts` setting list. If not, please include the log from the Remote-SSH output channel.

**Comment by kmc79** [comment]
> 
> 
> Have you disabled the `useLocalServer` setting? If so, you need to add the host to the `remote.SSH.windowsHosts` setting list. If not, please include the log from the Remote-SSH output channel.


I tried adding to `remote.SSH.windowsHosts` but that option was greyed out in my settings.

Adding it to `remote.SSH.windowsRemotes` did work though!


Thanks @roblourens
