### ISSUE TITLE
Remote-SSH passphrase prompt despite running ssh-agent on Windows 10

### ISSUE THREAD

**Issue by justClouds** [microsoft/vscode-remote-release#2530]
- VSCode Version: 1.43.0 
- Local OS Version: Windows 10 build 19559
- Remote OS Version: Debian 10 (Kernel 4.19.98-1)
- Remote Extension/Connection Type: SSH-Remote
- OpenSSH version on Win10: OpenSSH_for_Windows_8.0p1, LibreSSL 2.6.5

Despite having the key added to ssh-agent, it still prompts for the passphrase every time I connect using Remote-SSH to the remote host. When doing a direct SSH client connection, it works without passphrase. Also from a PS shell inside VSCode it works without asking for the passphrase.

Steps to Reproduce:

1. Open PowerShell 7 prompt on W10.
2. Generate RSA key with ssh-keygen (including passphrase).
3. Start ssh-agent service (net start ssh-agent).
4. Add key to ssh-agent: ssh-add key-file.
5. Check if key is added (ssh-add -l) -> it is...
6. Test SSH connection to remote host from command prompt -> works without passphrase prompt.
7. Start VSCode (with Remote-SSH extension installed).
8. Connect to remote host --> Passphrase prompt.

There are multiple issues reporting something similar, but the resolutions there are not applicable because the ssh-agent is running and has the right key and also the SSH connection works.

The SSH connection is defined in the `config` file with IP address, user and port number (no key file because that is stored in the ssh-agent).

**Comment by xgdgsc** [comment]
And I had to change full path to `ssh.exe` to simply `ssh` in `ProxyCommand` to connect successfully on windows (which is ok). These are two differences I see after update.

**Comment by hickeng** [comment]
Seeing the same issue on Windows Insider Fast Track with vscode insider.

**Comment by xgdgsc** [comment]
This is very annoying regression. I have to input passphrase several times a day with dozens of remote vscode windows due to network interruptions. Please consider making it a high priority in the time of coronavirus when many programmers would work from home.

**Comment by roblourens** [comment]
I believe this should fix it.

`"remote.SSH.path": "C:\\WINDOWS\\System32\\OpenSSH\\ssh.exe"`, let me know if not.

Duping with https://github.com/microsoft/vscode-remote-release/issues/2521
