### ISSUE TITLE
When a remote ssh on Windows is running, the remote PC can't open a VSCode instance

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/vscode-remote-release#2532]
Version 1.43, code server started by cmd, not in wsl

**Comment by roblourens** [comment]
Please give some more details about what you are doing and seeing here

**Comment by Jack-Works** [comment]
0. There are 2 PCs (both Windows) call them A and B.
1. A can ssh to B by Windows built-in OpenSSH server and client.
2. Start VSCode on A and connect to B by SSH
3. Start VSCode on B (doesn't show UI, only process I can see in taskmgr)

**Comment by roblourens** [comment]
How are you trying to start vscode on B? This scenario works for me

**Comment by Jack-Works** [comment]
Oh strange it works now. Thanks
