### ISSUE TITLE
Better UI/UX to push code to remote dev host

### ISSUE THREAD

**Issue by pgmabv99** [microsoft/vscode-remote-release#2533]
As a user I would like to  have a better set of features  to push my local sources/change to remote host. 

To put it differently  , I would like to worry about local source only and never see /worry about the remote source file copies needed for the remote run/debug.

Suggestions could be: 

- push all (sync all) workspace sources to remote host every time run/debug is started. Inform the user about stats of the sync
- provide UI similar to GIT source control  UI in VSCODE (list of files that are not synced and relevant actions on these files)
- remote full reset and re-sync

My current experience (with GO)  was very confusing as the launch.json allows to specify both local and remote source location without the  indication as to who is responsible for the sync.
If the local and remote source diverge the debugger still starts (no warning !) and appears to combine the local breakpoints with remote somehow.

I did read the article  
 https://code.visualstudio.com/docs/remote/troubleshooting#_using-rsync-to-maintain-a-local-copy-of-your-source-code

In my opinion this is still another software stack item . We already have GIT to synchronize/push /clone.  it would be nice to extend that paradigm to place source files on the remote host for daily debug sessions.

**Comment by roblourens** [comment]
It's not clear whether you are using VS Code Remote or not. Did you install one of the remote extensions like Remote-SSH?

**Comment by pgmabv99** [comment]
Rob, hi
yes, i installed  remote SSH . that allows me to navigate remote Linux folders and edit files there. 

However this is the anti-pattern  that  i want to avoid . I would like to keep/edit  my files locally on win , do GIT commits locally on win and have the studio transfer file to "some remote " folder for build /debugging. 
The physical names and root path of these remote folders should be hidden from me.
I should be able to change remote hosts as i want and have files auto transfered to a new host for a new build 

my 2 cents

thanks

**Comment by roblourens** [comment]
It looks like you saw the section about rsync. It's possible to set up a system like this yourself but it's not what we are trying to build with vscode remote.
