### ISSUE TITLE
Download Default File Name

### ISSUE THREAD

**Issue by ChechireBobcat** [microsoft/vscode-remote-release#2536]
Issue Type: <b>Bug</b>

In a recent update the behavior for downloading a remote file changed.  Previously the downloaded file would be (by default) have the same name as the remote file.  Now a name has to always be entered in the ui before saving.  

OS-Windows10, sshing into Linux x64 4.15.0-60-generic.

Extension version: 0.50.0
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.15.0-60-generic

![image](https://user-images.githubusercontent.com/36306983/76554862-d2356800-6453-11ea-8e7f-a72a89d88a34.png)

![image](https://user-images.githubusercontent.com/36306983/76554808-bcc03e00-6453-11ea-93a7-2db63b05fc29.png)

**Comment by mill1000** [comment]
Also seeing this issue. 

My remote host is an older release: `Linux 2.6.32-431.el6.x86_64`

**Comment by DanielKristofKiss** [comment]
I have the same issue with OSX host and Linux remote. 
Extension version: 0.50.0 and 0.49.0

ersion: 1.44.0-insider
Commit: b0791e5236f462fbb785e9a00319705607cefb9d
Date: 2020-03-10T11:17:54.705Z (3 days ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by VVakko** [comment]
Same issue with macOS Mojave 10.14.6 host and Ubuntu 20.04 remote.

Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (1 wk ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by ylin-ai** [comment]
Any plans to fix this issue, please? @isidorn

**Comment by isidorn** [comment]
There are no immediate plans to fix this.
However here's a code pointer for potential PRs that fix this
https://github.com/microsoft/vscode/blob/2f63aa9e559089436aa237f9c256ebad56913e42/src/vs/workbench/contrib/files/browser/fileActions.ts#L1024

**Comment by dantman** [comment]
Same issue on macOS connected to `Ubuntu 20.04.1 LTS` via Remote - SSH.

```
Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T17:39:53.251Z (1 wk ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0
```

The default filename is always "Untitled":
<img width="350" alt="Screen Shot 2020-09-17 at 5 33 17 PM" src="https://user-images.githubusercontent.com/53399/93541743-1aa27680-f90c-11ea-9630-3f7502f07fad.png">

**Comment by exdyna** [comment]
got the same issue on Windows 10 Pro for Workstation connected to CentOS 7 via remote - ssh. The default filename is empty.

**Comment by wkjung** [comment]
Same issue on Windows 10 education and remote ubuntu 18.04.

**Comment by benlindsay** [comment]
Same issue on a mac here.

**Comment by JulesRenz** [comment]
Also present on Remote - Containers (currently running v0.148.0) on MacOS

**Comment by whyisyoung** [comment]
I'm using Visual Studio Code 1.15.1 and macOS 10.15.7.
When I try to download files from remote, the default filename is "Untitled".

I think 1.15.1 already included @alexr00's fix, right?
