### ISSUE TITLE
How to show alias in vscode remote terminal?

### ISSUE THREAD

**Issue by Abbyyan** [microsoft/vscode-remote-release#2539]
In linux , we usually set some alias like `alias gs='git status' ` to make it easier to run some program.  And i can use `which gs` to see the alias. But in vscode terminal , it will show `no gs in the PATH`. Why does the alias will find in the `$PATH` environment? And how can i show the alias in the vscode remote terminal? Thanks a lot.

**Comment by roblourens** [comment]
Does it work if you set up those aliases in your `~/.profile`? I assume you have them set up in `~/.bashrc` or something now?

**Comment by Abbyyan** [comment]
Now i've tried and find that only when i set it in the `.bashrc` and restart all the vscode instance(The most important is restart the vscode-SSH extensions in my opinion ) , the alias can works. But when i set it in the `.profile` , it doesn't work.

**Comment by roblourens** [comment]
You will also have to get the remote vscode server to restart after you change your bashrc or profile, which you can do by running the command `Kill VS Code Server on Host...`
