### ISSUE TITLE
Terminating Local Server / Connecting with SSH timed out

### ISSUE THREAD

**Issue by Y13297** [microsoft/vscode-remote-release#2542]
- VSCode Version
 ![image](https://user-images.githubusercontent.com/44807042/76608695-5fd98c00-6516-11ea-8b75-756c5ac3933a.png)
- Remote OS Version: Windows Server 2012 RC 2
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

- Open remote

vscode output:

```
[10:07:19.770] > uname -rsv
[10:07:19.770] stderr> 'uname' is not recognized as an internal or external command,
[10:07:19.770] stderr> operable program or batch file.
[10:07:19.771] Platform: windows
[10:07:19.771] Remote command length: 7520/8192 characters
[10:07:19.773] > <username>@<server> C:\Users\<username>>
[10:07:19.833] > powershell -NoProfile
[10:07:19.956] stderr> W[10:07:19.956] stderr> [10:07:19.956] stderr> [10:07:19.957] stderr> [10:07:36.364] Terminating local server
[10:07:36.367] Resolver error: Connecting with SSH timed out
[10:07:36.374] ------
[10:07:36.575] Local server exit: null
```

**Comment by opopnhwth** [comment]
I have the same problem.

**Comment by roblourens** [comment]
Can you try something? On your remote, in a terminal, run `powershell -NoProfile`. Is there any output after that?

**Comment by roblourens** [comment]
Other people seeing this issue, what Windows version on the remote?

**Comment by roblourens** [comment]
We actually only officially support Windows 10/Server 2016/2019 https://code.visualstudio.com/docs/remote/linux

(But it would still be helpful to get an answer to the question above, maybe I can unblock it)

**Comment by opopnhwth** [comment]
Remote OS Version: Windows 10 1903
Local OS : deepin Linux

after run powershell -NoProfile,output:
      尝试新的跨平台 PowerShell https://aka.ms/pscore6

**Comment by xlfsummer** [comment]
Same problem, but output is different:

![image](https://user-images.githubusercontent.com/20750969/76872092-e7bcee80-68a6-11ea-93b6-6efdf6743815.png)

Default codepage of cmd on the remote computer is 936

**Comment by roblourens** [comment]
Ok, I think these are https://github.com/microsoft/vscode-remote-release/issues/2351

**Comment by Y13297** [comment]
> Can you try something? On your remote, in a terminal, run `powershell -NoProfile`. Is there any output after that?
```
Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. All rights reserved.
```

The remote is English, but the work around mentioned in #2351 :
```
"remote.SSH.useLocalServer": false,
"remote.SSH.windowsRemotes": ["<your remote hostname>"] // only if the remote is Windows
```

does solve the problem. Not the complete install though, extracting the vscode-server zip fails, but extracting it manually gets VS code remote up and running. Thank you for your help!
