### ISSUE TITLE
Cant display 2 different remote machine with the same IP but in different port

### ISSUE THREAD

**Issue by BagusYusuf** [microsoft/vscode-remote-release#2543]
- VSCode Version:  1.43.0
- Local OS Version: Wondows 10
- Remote OS Version: Ubuntu 16.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Create ssh target with a specific port
2. Create 2nd-ssh target with the same IP but with different port
3. the VS-Code will only show the first one

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Are you just adding those entries to your ssh config? It doesn't work that way, you will have to give them different names.

**Comment by BagusYusuf** [comment]
I just add the host by using provided + button
then put the ssh address with port
I think it my fault, it work fine after i give the different name,

thank you very much

**Comment by roblourens** [comment]
No problem, yeah in that case you will have to customize the name after it's added to the config.
