### ISSUE TITLE
Cannot attach on running remote dockers to multiple servers using DOCKER_HOST env var

### ISSUE THREAD

**Issue by remss** [microsoft/vscode-remote-release#2544]
- VSCode Version:1.43.0 (Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a)
- Local OS Version: Windows 10.0.18363 
- Remote OS Version: Debian 9
- Remote Extension/Connection Type: SSH+Docker
- All extensions are disabled except "Docker" and "Remote Devlopment"

## Steps to Reproduce

Assuming I want to develop in remote running docker containers (`ct1` and `ct2`) from two different servers (`srv1` and `srv2`)

1. In a powershell 
```
PS> $Env:DOCKER_HOST="ssh://srv1"
PS> code
```
2. In VSCode > Docker panel, docker containers from `srv1` are listed correctly, right click on `ct1` > "Attach Visual Studio Code"
3. A second VSCode opens with the remote session, I can open a folder (from container `ct1` on server `srv1`)

4. In a powershell 
```
PS> $Env:DOCKER_HOST="ssh://srv2"
PS> code
```
5. In VSCode > Docker panel, docker containers from `srv2` are listed correctly, right click on `ct2` > "Attach Visual Studio Code"
6. A second VSCode opens with the remote session, but I got an error alert: "Cannot attach to the container with name/id ct2, it no longer exists."

## Additional info

In the error alert I can click on "Choose container". Then in the select box I see running containers from `srv1`! So it seems there is a mix up between ssh tunnels, it fails to attach `ct2` on `srv2` because it's using `srv1` ssh connection from the first session.

**Comment by chrmarti** [comment]
Does it work when you set the `docker.host` setting instead?

**Comment by remss** [comment]
Yes it works fine using docker.host settings, so the issue is related to the DOCKER_HOST env var.

1. Start VSCode (no DOCKER_HOST env var)
2. In Settings, set docker.host to ssh://srv1
3. In Docker panel, docker containers from srv1 are listed correctly, right click on ct1 > "Attach Visual Studio Code"
4. A second VSCode opens with the remote session, I can open a folder (from container ct1 on server srv1)
5. Back to first VSCode , in Settings, set docker.host to ssh://srv2
4. In Docker panel, docker containers from srv2 are listed correctly, right click on ct2 > "Attach Visual Studio Code"
5. A third VSCode opens with the remote session, I can open a folder (from container ct2 on server srv2)

**Comment by chrmarti** [comment]
Continue tracking as https://github.com/microsoft/vscode-remote-release/issues/2544.
