### ISSUE TITLE
Failure building dev container when mount path contains spaces

### ISSUE THREAD

**Issue by samburger** [microsoft/vscode-remote-release#2549]
Issue Type: <b>Bug</b>

<b>VS Code Info</b>
Version: 1.43.0 (system setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
<b>Extension Version</b>: 0.106.0  

Containers running in Docker Desktop (i.e. not WSL).

**Steps to Reproduce**: 

1. Create project directory containing spaces  
2. Open directory in VS Code  
3. Create new Dev Container config (I used Python: Miniconda)  
4. Add mount argument (full `devcontainer.json` below)
5. Build container & reload  
6. Observe build error `bare " in non-quoted-field`

Contents of `devcontainer.json`:  
```
// For format details, see https://aka.ms/vscode-remote/devcontainer.json or this file's README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.106.0/containers/python-3-miniconda
{
	"name": "Python 3 - Miniconda",
	"context": "..",
	"dockerFile": "Dockerfile",
	// Set *default* container specific settings.json values on container create.
	"settings": {
		"terminal.integrated.shell.linux": "/bin/bash",
		"python.pythonPath": "/opt/conda/bin/python",
		"python.linting.enabled": true,
		"python.linting.pylintEnabled": true,
		"python.linting.pylintPath": "/opt/conda/bin/pylint"
	},
	// Add the IDs of extensions you want installed when the container is created.
	"extensions": [
		"ms-python.python"
	],
	"mounts": [
		"source=\"d:\\Dropbox\\Codespace\\path with spaces\",target=/test,type=bind"
	]
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],
	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "python --version",
	// Uncomment to connect as a non-root user. See https://aka.ms/vscode-remote/containers/non-root.
	// "remoteUser": "vscode"
}
```

Attempting to invoke the same `--mount` arguments in a command line works fine and brings up the expected container shell.   
E.g. `docker run -it --mount source="d:\Dropbox\Codespace\path with spaces",target=/replays,type=bind vsc-pathwithspaces-8dafda5e5233c08fa9ad57b87e6c86f7`
There seems to be some discrepancy in how quotes are escaped in the JSON: the logs appear to print a perfectly functional command. 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'dev-container+643a5c44726f70626f785c436f646573706163655c736c61707069' timed out.
</details>

**Comment by hholst80** [comment]
The source path should not be quoted instead escape spaces like `\ `

**Comment by samburger** [comment]
Thanks: the linter gave `invalid escape character in string` for the spaces, but it worked that way.
