### ISSUE TITLE
Cannot Launch Extensions for Debugging Inside of Container

### ISSUE THREAD

**Issue by AngellusMortis** [microsoft/vscode-remote-release#255]
- VSCode Version: 1.34.0-insider / 693a13cd32c5be798051edc0cb43e1e39fc456d9 / x64
- Local OS Version: Ubuntu 18.04
- Remote OS Version: Debian GNU/Linux / 9 (stretch) (`node:lts`)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:
1. https://code.visualstudio.com/api/advanced-topics/remote-extensions

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

I tried the follow the guide on how to [debug remote extensions](https://code.visualstudio.com/api/advanced-topics/remote-extensions#debugging-your-extension-in-a-remote-environment) and when I attempt to use use the provided launch task

```jsonc
{
    "name": "Launch Extension (Container)",
    "type": "extensionHost",
    "request": "launch",
    "runtimeExecutable": "${execPath}",
    "args": [
        "--extensionDevelopmentPath=${workspaceRoot}",
        "${workspaceFolder}"
    ],
    "stopOnEntry": false,
    "sourceMaps": true,
    "outFiles": [
        "${workspaceRoot}/dist/**/*.js"
    ],
    "preLaunchTask": "npm: watch"
}
```

It always exits with a exit code of 1

![image](https://user-images.githubusercontent.com/490848/57460556-52db7480-7243-11e9-9a79-b44ac41d6150.png)

When I attempt to run the command manually from bash, it always get the following:

```bash
root@1b022ec12b1d:/workspaces/vscode-extension# code-insiders --extensionDevelopmentPath=${workspaceRoot} .
Ignoring option extensionDevelopmentPath: not supported for code-insiders.
root@1b022ec12b1d:/workspaces/vscode-extension# echo $?
130
```

**Comment by weinand** [comment]
@AngellusMortis does it make a difference if you use this launch config:
```js
{
    "name": "Launch Extension (Container)",
    "type": "extensionHost",
    "request": "launch",
    "args": [
        "--extensionDevelopmentPath=${workspaceFolder}"
    ],
    "stopOnEntry": false,
    "sourceMaps": true,
    "outFiles": [
        "${workspaceFolder}/dist/**/*.js"
    ],
    "preLaunchTask": "npm: watch"
}
```

Explanation:
- don't pass `${workspaceFolder}` as a workspace folder argument because that folder is already open in VS Code and trying to open it again just makes VS Code activate the corresponding window.
- `${workspaceRoot}` should work but is deprecated; use `${workspaceFolder}` instead.

**Comment by AngellusMortis** [comment]
No. The issue is the `extensionDevelopmentPath` option. It does not seem to exist at all on the VS Code remote server.

**Comment by weinand** [comment]
It might be unsupported when running `code-insiders` from the command line, but when using a launch config it is definitely supported. 
Passing `--extensionDevelopmentPath=${workspaceRoot}` on the command line makes no sense as the shell will try to substitute `${workspaceRoot}` which doesn't exist.

Please try my launch config from above.

**Comment by AngellusMortis** [comment]
As as I already said no, it does not work. The launch config you just gave me the essentially the same one that comes with the `yo code` generated code. 

The `extensionDevelopmentPath` options still exists on the local version of VS Code when executed from command line manually, it just does not do anything. The remote is specifically telling me it does not exist. 

```
Ignoring option extensionDevelopmentPath: not supported for code-insiders.
```

**Comment by AngellusMortis** [comment]
I tried the same thing on my Windows 10 machine with same set up and seems like it works fine. I think the issue is that for some reason on my machine VS Code Insiders cannot open the new window to do the debugging. So I guess I just have to do it all on my Windows machine.

**Comment by weinand** [comment]
Please note: I've removed the 2nd argument "${workspaceFolder}" from the "args" array. That's definitely not generated by "yo code".

The command line argument is not used in the remote case. So the command line message "Ignoring option extensionDevelopmentPath: not supported for code-insiders." doesn't prove anything.
