### ISSUE TITLE
Everything I attempt to do with the extension, I get command 'opensshremotes.*' not found

### ISSUE THREAD

**Issue by jtagcat** [microsoft/vscode-remote-release#2550]
- VSCode Version: 1.43.0
- Local OS Version: Fedora 31
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Try to use the extension, execute any command: for example `>Remote-SSH: Connect to Host... `  or `>Remote-SSH: Add New SSH Host...`
2. Notification, err: `command 'opensshremotes.openEmptyWindow' not found` or `command 'opensshremotes.addNewSshHost' not found`

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by hullu198** [comment]
Try the insider version, that fixed it for me

**Comment by roblourens** [comment]
Did you see this after failing to connect to a remote? There is a known issue there. Do you see it in a working local window?

**Comment by jtagcat** [comment]
> Did you see this after failing to connect to a remote? 

No.
> Do you see it in a working local window? 

Wdym?

**Comment by roblourens** [comment]
I just mean a working window that can open local files and so on, just as opposed to a window that failed to connect to a remote. Could you just try restarting vscode, try it again, and attach a screenshot so I can be sure I understand what you're doing?
