### ISSUE TITLE
New Update Seems to Have Broken my Remote SSH Connection

### ISSUE THREAD

**Issue by JSkylerNuth** [microsoft/vscode-remote-release#2551]
Issue Type: <b>Bug</b>

Still trying to test if the update was indeed the culprit but all signs point to it since it was working fine Monday and only change has been the automatic update that apparently took place that same day and would've restarted with the reboot it did over the night. 

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.17763
Fetching remote diagnostics for 'SSH' failed: Could not resolve hostname

Extensions: none

**Comment by biltongza** [comment]
I got this as well. I went down a wild goose chase trying to figure out what went wrong. My SSH host is a Linux VM running on my own machine and I wound up resetting its network completely. I eventually just added its IP to my hosts file to get it to connect.

However, now public key authentication is not working unless I set `remote.SSH.useLocalServer` to `false`. If I set that to true, it always asks me for my password on the host (which it always rejects even with the correct password). Something is very unhappy in this latest update.

**Comment by tsquillario** [comment]
`rm -rf ~/.vscode-server/` on the remote machine fixed it for me

**Comment by jghal** [comment]
I just started seeing it and believe the issue is this bit

```
[16:45:43.849] Checking ssh with "ssh -V"
[16:45:44.140] > OpenSSH_for_Windows_8.0p1, LibreSSL 2.6.5
[16:45:44.140] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[16:45:44.142] Got error from ssh: spawn C:\Windows\System32\OpenSSH\ssh.exe ENOENT
[16:45:44.142] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[16:45:45.078] > OpenSSH_8.2p1, OpenSSL 1.1.1d  10 Sep 2019
[snip]
[16:45:45.455] Spawned 1752
[16:45:45.900] > local-server> Spawned ssh: 8332
[16:45:46.235] stderr> OpenSSH_8.2p1, OpenSSL 1.1.1d  10 Sep 2019
```

So it's using the `ssh` executable bundled in Git for Windows, when I actually want to use the native OpenSSH for Windows (the _C:\Program Files\OpenSSH-Win64\ssh.exe_ 8.0 version that is the only version in my PATH and that was discovered via `ssh -V`). I have my agent and .ssh\config setup for that native OpenSSH and instead it's using the Git for Windows copy and asking for my key passphrase and mostly failing, sometimes it connects but then it's not forwarding my agent like I have configured so Git operations don't work. 

Setting `remote.SSH.useLocalServer: false` fixes it but that is a rather unintuitive way to control what SSH _client_ is being used to connect to the remote.

**Comment by biltongza** [comment]
@jghal I can confirm that using the ssh client from git for windows doesn't appear to use my public key for auth. SSH bundled with windows does.

```
C:\Users\logan.dam> cd '..\..\Program Files\Git\usr\bin'
C:\Program Files\Git\usr\bin> .\ssh.exe archvm
logan.dam@archvm's password:
```

**Comment by nick-walt** [comment]
Since the latest update VSCode has been unable to connect to a remote host. It seems to be wanting to re-install itself on the Ubuntu host and I guess that might be due to the update. I'm wondering if updating its server installation is failing.

Final output:
```
[12:22:29.216] > c59bc771ae6d: running
> 
[12:22:29.225] > Acquiring lock on /home/ubuntu/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec
> 76b5300ddd/vscode-remote-lock.ubuntu.ff915844119ce9485abfe8aa9076ec76b5300ddd   
> \ln /home/ubuntu/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vsc
> ode-remote-lock.ubuntu.ff915844119ce9485abfe8aa9076ec76b5300ddd.target /home/ubu
> ntu/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lo
> ck.ubuntu.ff915844119ce9485abfe8aa9076ec76b5300ddd
> Installation already in progress...
> c59bc771ae6d##24##
> ln: failed to create hard link '/home/ubuntu/.vscode-server/bin/ff915844119ce948
> 5abfe8aa9076ec76b5300ddd/vscode-remote-lock.ubuntu.ff915844119ce9485abfe8aa9076e
> c76b5300ddd': File exists
> 
[12:22:29.225] Received install output: c59bc771ae6d##24##
[12:22:29.225] Server installation process already in progress - waiting and retrying
[12:22:29.494] "install" terminal command done
[12:22:29.494] Install terminal quit with output: 
[12:22:30.226] Resolver error: 
[12:22:30.228] ------
```
