### ISSUE TITLE
Setting for specifying exact tar binary to use during install

### ISSUE THREAD

**Issue by maciejmatczak** [microsoft/vscode-remote-release#2554]
Hi,
I am having an issues with weird specific corporate setup and an old default tar version:
```text
\tar --version
tar (GNU tar) 1.13.25
Copyright © 2001 Free Software Foundation, Inc.
```
Gives such error during remote installation:
```text
[10:39:41.118] > Download complete
> a3c420facf11%%2%%
> tar: This does not look like a tar archive
> tar: Skipping to next header
> tar: Archive contains obsolescent base-64 headers
> 
```

I am able to use newer binary, but I can't find any way to actually make installation process use it. As far as I know - all .bashrc/profile settings are ignored with the non interactive ssh connections, it could only be done with explicit tar binary's full path.

Thanks for considering,

Maciej

**Comment by roblourens** [comment]
We just use tar on the path. Your bashrc should still take effect (but the default bashrc sometimes explicitly bails if it detects a non-interactive session)

**Comment by maciejmatczak** [comment]
Hi @roblourens,
It's my second approach after #1163.
So, what VS Code exactly runs?
Something like that `ssh host -c 'bash -c tar ...'`?

This https://serverfault.com/questions/936746/bashrc-is-not-sourced-on-ssh-command is not quite promising, is it?

**Comment by roblourens** [comment]
You can try something like `echo printenv | ssh host` to test.

A `~/.profile` should be invoked, you can try making your modification there.

**Comment by maciejmatczak** [comment]
Ok, so:

`echo 'tar --version | ssh host` gives me tar 1.28 (2014), but that uses my standard shell
and that's for sure not the way how VS Code invokes that part.

`ssh host "bash -c 'tar --version'"` gives me tar 1.13 (2001), it's non interactive shell.

It is really important to now how remote plugin invokes this commands, without that we can only guessing...

Having this installation step more verbose would help as well, `which tar`, `tar --version`, at least for conforming what is exactly happening there exactly, not guessing.

**Comment by roblourens** [comment]
It depends on whether or not you have `useLocalServer` disabled but what we do is essentially either like the first option in your comment above, or that but with `bash` appended.

I think it should run printenv in this case when it fails, do you see the environment written out in the log? If it doesn't, would that help? Like seeing the PATH should tell you whether it will find the tar you expect.

**Comment by maciejmatczak** [comment]
`PATH` does not help in terms of determining alias value for `tar` I have.

Can you be specific on the example, how VS Code invokes that command, please? My default shell is not a bash on that server, hence you need to somehow sneak it into invocation. What do you mean by appending?

**Comment by danilaml** [comment]
I have the same problem (even the same tar version found in, I believe, CentOS 7).
`ssh` doesn't execute any bashrc files and has `PATH=/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin` by default. It seems there is no way to fix this (note that changing sshd_config is not an option).
For the moment I have to resort to manually downloading and unpacking the archive into the folder expected by VS, which can get quite annoying since it's required after each update.
Perhaps VSCode could provide some general "run this command/script after ssh connection is established" option.

**Comment by roblourens** [comment]
@danilaml A `~/.profile` should be invoked, you can try making your modification there.

@maciejmatczak  It should be the same as `echo 'tar --version' | ssh host bash`

**Comment by maciejmatczak** [comment]
@roblourens, thanks for an exact example.

`echo 'tar --version' | ssh host bash`  - gives old tar
`echo 'tar --version' | ssh host bash -i`  - gives new tar

I tried `.profile`, `.bashrc_profile`, `.bashrc`, combinations. None of it seems to work in non-interactive shell.

Maybe the .profile is actually sourced, but I would guess that it is used by a default shell and right after `bash` is spawned, it doesn't initialize with any of those files.

**Comment by roblourens** [comment]
It sounds like this was fixed with shell settings, which I think is the right way to do this.
