### ISSUE TITLE
SSH jump host not following prerequisites for remote host

### ISSUE THREAD

**Issue by Dreaddune** [microsoft/vscode-remote-release#2556]
I have never played around with ssh jump hosts before, but since I have to work from home, I've recieced a non-root user in one, such that I can the remote host I'm normally working on.

However, the jump host runs Centos 6 with Glibc version 2.12, and also a low version of libstdc++, which wouldn't be compatible with the final remote host according to https://code.visualstudio.com/docs/remote/linux, but it still crashes.

Is it possible to use these low-version packages, or am I entirely out of luck?

(The jump host does not have git, so I can't build the packages from scratch..)

Edit: I am using WSL

**Comment by roblourens** [comment]
if I understand correctly, it wouldn't matter if the jump host doesn't meet the prereqs, because we don't run any code on the jump host, just the final host. What do you see if you try to connect exactly?

**Comment by Dreaddune** [comment]
Good question.
After having played around with it for a couple of hours, i admitted defeat and posted the question above. 

Having just started vscode up again, it works as expected - the SSH connection works as a charm, and I now have access to my workspace.

Sorry for cluttering up the issue-bord. 
I'll be closing the question now
