### ISSUE TITLE
TypeScript task failed to start on remote ssh Windows host

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/vscode-remote-release#2563]
- VSCode Version: 1.43.0
- Local OS Version: Windows 10
- Remote OS Version: Windows 10
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open a TypeScript project on the remote
2. `Tasks: Run Task`/`tsc watch - tsconfig.json`
3. Failed: It tries to start the command `\Users\Jack\Workspace\project\node_modules\.bin\tsc.cmd -p \Users\Jack\Workspace\project\tsconfig.json --watch` where `\Users\...` is not a valid path in cmd I think

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by gbhojraj** [comment]
I think I'm having a similar problem (Windows 10 host/Ubuntu VM), where my tasks are being run in a local terminal rather than on the remote. Just set up this environment and I don't normally use Tasks, so I'm not sure if there are additional ways to configure how they run.

**Comment by alexr00** [comment]
@Jack-Works do you have this setting: `"remote.SSH.useLocalServer": true`?
@roblourens is that setting still supposed to be needed? I'm trying to repro by sshing to localhost, and I can only get it to work with `useLocalServer`.

**Comment by roblourens** [comment]
Depends on the setup. But once you are connected the task should work the same.

**Comment by Jack-Works** [comment]
> @Jack-Works do you have this setting: "remote.SSH.useLocalServer": true?

It is true by default in my vscode, I didn't configure this option

**Comment by alexr00** [comment]
@Jack-Works can you try with version 1.44+ ? I wasn't able to reproduce the issue there.

**Comment by Jack-Works** [comment]
VSCode Version: 1.44.2
Local OS Version: Windows 10
Remote OS Version: Windows 10
Remote Extension/Connection Type: SSH
Remote SSH version: 0.51.0

Step: Open a typescript project on remote machine
F1 - run task - `tsc: watch - tsconfig.json`

```
> Executing task: \Users\Jack\Workspace\Project\node_modules\.bin\tsc.cmd -p \Users\Jack\Workspace\Project\tsconfig.json --watch <

The terminal process terminated with exit code: {0}

Terminal will be reused by tasks, press any key to close it.
```

Exit with no error message

**Comment by alexr00** [comment]
Do you have a tasks.json and if so can you share it?

**Comment by Jack-Works** [comment]
The typescript task is auto detected

```jsonc
{
    // 有关 tasks.json 格式的文档，请参见
    // https://go.microsoft.com/fwlink/?LinkId=733558
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "build",
            "problemMatcher": []
        },
        {
            "type": "npm",
            "script": "start",
            "problemMatcher": []
        },
        {
            "type": "npm",
            "script": "storybook",
            "problemMatcher": []
        },
        {
            "type": "npm",
            "script": "start:ios",
            "problemMatcher": []
        },
        {
            "type": "npm",
            "script": "lint",
            "problemMatcher": ["$eslint-compact"]
        }
    ]
}

```

**Comment by Jack-Works** [comment]
The typescript task is auto detected
```jsonc
{
    // 有关 tasks.json 格式的文档，请参见
    // https://go.microsoft.com/fwlink/?LinkId=733558
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "build",
            "problemMatcher": []
        },
        {
            "type": "npm",
            "script": "start",
            "problemMatcher": []
        },
        {
            "type": "npm",
            "script": "storybook",
            "problemMatcher": []
        },
        {
            "type": "npm",
            "script": "start:ios",
            "problemMatcher": []
        },
        {
            "type": "npm",
            "script": "lint",
            "problemMatcher": ["$eslint-compact"]
        }
    ]
}

```

**Comment by Jack-Works** [comment]
Oh, it seems like all kind of tasks are broken: this is npm auto detected task:

```
> Executing task: npm run build <

The terminal process command 'pwsh.exe -Command npm run build' failed to launch (exit code: {2})

Terminal will be reused by tasks, press any key to close it.
```

**Comment by Jack-Works** [comment]
But if I run the command `pwsh.exe -Command npm run build`, it is working

**Comment by alexr00** [comment]
Do you have the `terminal.integrated.automationShell.windows` or `terminal.integrated.shell.windows` settings set? I'm still unable to repro with either detected typescript or npm tasks.

@roblourens I'm using SSH to 127.0.0.1. Should that be sufficient to test?

**Comment by Jack-Works** [comment]
I figured out why: Please set this to "windows" in your config

```json
{
    "window.zoomLevel": 1,
    "remote.SSH.remotePlatform": {
        "remote-windows-host-name": "windows"
    }
}
```
