### ISSUE TITLE
Clipboard from terminal

### ISSUE THREAD

**Issue by fsackur** [microsoft/vscode-remote-release#2564]
I use dev containers.

The one thing I still can't do is copy from the terminal entirely with the keyboard.

I can paste from the clipboard into the terminal but, to copy, I have to mouse-select text. This is, ultimately, because X11 forwarding is not available.

Personally, I want the experience I have on Windows, where I can use shift-arrow to highlight text and Ctrl-C to copy to the system clipboard. I'm not too bothered by the exact key sequence used, although I've managed to get my desired combos working in `zsh` as described here: https://stackoverflow.com/questions/56517662/how-do-i-highlight-text-for-copying-and-pasting-in-the-vs-code-terminal/59987458#59987458

I have managed to get to where `Ctrl-X` copies to a file, but I still have a mountain of work to do, and any solution will be somewhat hacky and not suitable for mass adoption. And it requires `zle` or, possibly, `readline`.

I suspect that any solution will require a little hacking in a `.profile` script. Not sure of any way to avoid that.

My suggestion: 
- allow the vscode-server binary to be invoked from within the terminal in the remote host, to place text onto the system clipboard in the UI host
- expose this as a unix socket, creating env var REMOTE_CONTAINERS_CLIPBOARD_IPC

This could allow the following:

`print -rn -- $CUTBUFFER > $REMOTE_CONTAINERS_CLIPBOARD_IPC`

where CUTBUFFER contains the text you wish to copy to the UI host's clipboard.

**Comment by Tyriar** [comment]
There are these commands available to be keybound to select within the terminal:

![image](https://user-images.githubusercontent.com/2193314/78555089-23214d80-77c1-11ea-8616-c934cf0b2d9e.png)

I use these for example:

```
// Terminal command tracking on Windows and Linux
{ "key": "ctrl+up",          "command": "workbench.action.terminal.scrollToPreviousCommand", "when": "terminalFocus" },
{ "key": "ctrl+down",        "command": "workbench.action.terminal.scrollToNextCommand", "when": "terminalFocus" },
{ "key": "ctrl+shift+up",    "command": "workbench.action.terminal.selectToPreviousCommand", "when": "terminalFocus" },
{ "key": "ctrl+shift+down",  "command": "workbench.action.terminal.selectToNextCommand", "when": "terminalFocus" },
```

**Comment by fsackur** [comment]
Thanks @Tyriar , that's good to know. Personally, I hanker after the keyboard nav you can get with a single-purpose terminal.

I'm happy for this to be closed, but would you have any advice on whether an extension could potentially interact with a buffer editor, e.g. readline? Is that something anyone else has done?

**Comment by Tyriar** [comment]
@fsackur right now extensions cannot access the buffer at all, we've discussed this at length internally and decided against it for security/perf reasons.

See this proposed api https://github.com/microsoft/vscode/issues/78502#issuecomment-559835968:

https://github.com/microsoft/vscode/blob/cc12934f76800d4b92ab0ff487804f934b25f1bd/src/vs/vscode.proposed.d.ts#L840-L862
