### ISSUE TITLE
Consider prompting users for platform instead of autodetection

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#2568]
When `remote.SSH.useLocalServer` is enabled (the default) we try to detect the platform of the remote. To do this, we connect with an ssh command that doesn't have a RemoteCommand, e.g. `ssh myhost`, then send a command to start a bash or powershell session, then send the install script.

There are a couple issues that are hard to fix

- Some versions of the Windows OpenSSH server don't work: https://github.com/microsoft/vscode-remote-release/issues/2475
  - Alternate workaround: it is possible to detect the error message that we get in this case, we can show a notification or something
  - No other workaround other than wait for the fixed version to be released
- This doesn't work when the default shell is fish/tcsh/csh: https://github.com/microsoft/vscode-remote-release/issues/2509
  - Alternate workaround: use `-tt` for all sessions, has weird side effects, maybe could introduce some other weird issues

And an easy way out of these issues would be to just ask the user for the platform of the remote on the first connection via a quickpick with 3 options, cache that in a setting, and set `bash` or `powershell` as the command in the ssh connection string. The setting would look like 

```json
"remote.SSH.platform": {
  "host1": "windows",
  "host2": "linux"
}
```

**Comment by jamespottsSAFC** [comment]
So I am having problems in that I normally have the default shell for OpenSSH on my remote machine set to git bash however VS Code remote only works when I have the default shell set to cmd. Is there a work around for this until the user is able to tell code what platform it is using? Apologies if this is the wrong place to ask!

**Comment by roblourens** [comment]
That not really related to this issue, please open a new issue and include the log from the Remote-SSH output channel.

**Comment by Chuxel** [comment]
@roblourens Actually looking at this - is this different than is what is in 0.51?

**Comment by roblourens** [comment]
Yeah, in 0.51 I only ask for the platform when useLocalServer is disabled. Asking for it when it is enabled would be a last-resort workaround for the issues above, I don't plan to do that though.
