### ISSUE TITLE
Consider simplifying Remote SSH support, similar to what is offered by Apache NetBeans

### ISSUE THREAD

**Issue by jmcpeek** [microsoft/vscode-remote-release#257]
For reference, the KB Article from NetBeans:
* https://netbeans.org/kb/docs/cnd/remotedev-tutorial.html

**Preword:**

First, let me say - thanks for the great feature! The options for different remote development workflows are a big improvement to what was previously available.

**Request:**

With that said, I can't help but wonder if the approach (at least for Remote - SSH) could/should be modified.

In NetBeans, there are not remote host requirements beyond: SSH and GNU toolchain[1].

File are transparently synced between local host and remote host, and all development, debugging occurs _on the remote files_ but _in the comfort of your local development environment_.

In the case of C/C++, you didn't even need gdbserver. It transparently interfaced with the remote GDB _as if_ it were local to your machine.

[1]: Obviously, there are new toolchains to support these days, including non-C/C++ options. That's a limitation of NetBeans support falling behind, prior to its transition to Apache's Incubator.

**Benefits:**

In doing so, it would seem possible to get away from the need for a vscode server as well as the entire concept of "remote" or "local" plugins.

By transparently passing through the interactions from remote to local, everything can operate as a "local" plugin.

Further, I believe moving to a model like this would accelerate (perhaps make immediate) support for MacOS, Windows, and non-x86_64 Linux remote hosts.

**Down side:**

The one benefit I see going away is that, remote plugins on the remote host allow for "seamless" transition from one local host to another local host, with only the need for a fresh install of vscode.

**Postword:**

I understand that this would be a non-congruent architectural change.

But, seeing that the technology is in preview, I wanted to raise the question/opportunity before it becomes an impossibility.

**Comment by carnesen** [comment]
It certainly seems like that ship has sailed. In the blog post announcement of the feature they explain why the remote agent is necessary to achieve the buttery-smooth development experience we VS Code aficionados have come to love and expect.

**Comment by roblourens** [comment]
Running plugins on the remote really is a core benefit of the whole model. This isn't just about editing files remotely. There are lots of details in the blog post and docs about how vscode remote works and why it's designed the way it is.
