### ISSUE TITLE
Want to be able to map paths with sudo

### ISSUE THREAD

**Issue by murpg** [microsoft/vscode-remote-release#2572]
I am pretty much locked in my home folder for setting folder paths. I want to be able to set the path to my default web folder. I can't do it because I have to connect as ubuntu.
I cannot map /web as my folder. In my configuration file, how can I do ubuntu sudo su -?
```
ubuntu@ip-172-31-32-99:~$ cd /web
bash: cd: /web: Permission denied
ubuntu@ip-172-31-32-99:~$ sudo su
root@ip-172-31-32-99:/home/ubuntu# cd /web
root@ip-172-31-32-99:/web# 

```

**Comment by chrmarti** [comment]
Is this using Remote-SSH? Couldn't you change the owner on `/web` to `ubuntu`?
