### ISSUE TITLE
EACCESS error when removing file.

### ISSUE THREAD

**Issue by timfelle** [microsoft/vscode-remote-release#2574]
- VSCode Version: 1.43.0
- Local OS Version: Windows 10 1903 -Build 18362
- Remote OS Version: Ubuntu 18.04.4 LTS
- Remote Extension/Connection Type: WSL

I have the often mentioned permission issue when using WSL and VSCode together using your extension.
I have tried the steps mentioned in:
[https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace](https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace)

However they had no effect. Can you advice on another approach to solve it except waiting 6 months for windows 10 2004 to be ready?

**Comment by egamma** [comment]
Please provide more information on how you have configured your polling interval.

**Comment by timfelle** [comment]
So i dont know what changed. But in the last week some update have fixed something. Thank you anyway.
For future reference, this combination works for me:
"remote.WSL.fileWatcher.polling": true,
"remote.WSL.fileWatcher.pollingInterval": 5000

**Comment by andreamaruccia** [comment]
I have this too, I think we should reopen this issue.

here are my details:
OS
```
Local OS: `Microsoft Windows [Version 10.0.18362.720]`
Remote OS Version: Ubuntu 18.04.4 LTS
Remote Extension/Connection Type: WSL
```
vscode
```
Version: 1.43.2 (system setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
```
settings
```
    "remote.WSL.fileWatcher.polling": true,
    "remote.WSL.debug": false,
    "remote.WSL.fileWatcher.pollingInterval": 10000,
```
