### ISSUE TITLE
open remote file from command line, while reusing open vscode window

### ISSUE THREAD

**Issue by rualark** [microsoft/vscode-remote-release#2577]
These commands work:

code --remote ssh-remote+myubuntubox /home/x/projects/foo
code --file-uri vscode-remote://ssh-remote+myubuntubox/home/x/projects/test.code-workspace

Buy I cannot add --reuse-window to them so that file is opened in the already opened project in vscode.

**Comment by aeschli** [comment]
Tested in the latest insiders and `code-insiders --remote wsl+ubuntu -r /home/aeschli/workspaces/vscode-uri` works
