### ISSUE TITLE
Process left behind by each SSH connection

### ISSUE THREAD

**Issue by vadimcn** [microsoft/vscode-remote-release#258]
Issue Type: <b>Bug</b>

Each SSH (re)connection leaves behind a `sleep infinity` orphan process on the remote host.

Extension version: 0.36.0
VS Code version: Code - Insiders 1.34.0-insider (daf71423252a707b8e396e8afa8102b717f8213b, 2019-05-07T05:14:45.885Z)
OS version: Linux x64 4.15.0-48-generic
Remote OS version: Linux x64 4.15.0-48-generic

**Comment by roblourens** [comment]
When losing connection, the ssh tunnel process may or may not go down. If it doesn't, you can accumulate ssh tunnel processes or terminals over time.

We need to keep track of which tunnels were created by the resolver and clean them up when the resolver is invoked again

These will be cleaned up when the window is reloaded at least...

**Comment by vadimcn** [comment]
To clarify: these appear as children of the `init` process (i.e. orphans), so  parent process has actually exited.

**Comment by roblourens** [comment]
They should be associated with an ssh process on the client which is a child of the window's extension host, so if everything is shut down cleanly, they should go away when the window on the client goes down.

**Comment by vadimcn** [comment]
Not sure we are talking about the same thing: I see these on the *server* machine.  
While a session is active, they are parented to `sshd`.  Here's the tree I see in `htop`:
```
init
│
...
├─ /usr/sbin/ssh -D
   └─ sshd: <username> [priv]
      └─ sshd: <username>@notty
         └─ sleep infinity
```
When the session gets disconnected, `sleep infinity` is re-parented to `init`.

**Comment by roblourens** [comment]
Oh ok, maybe my assumption is incorrect then.

**Comment by roblourens** [comment]
The fix is to use `ssh -t`, only when using the "show login terminal" setting
