### ISSUE TITLE
Issue with non-ascii characters in local windows user name

### ISSUE THREAD

**Issue by zhuo1angT** [microsoft/vscode-remote-release#2580]
When I use SSH remote to connect my server, the following error poped up.

![Inked捕获_LI](https://user-images.githubusercontent.com/24938839/77063016-f37bf280-6a17-11ea-9338-b5343547ff88.jpg)

It seems that the file path, my windows account name in Chinese, didn't get encoded.
I don't know if I get that error log right, if not, could you please tell me how can I resolve it?
Thanks a lot.

**Comment by zhuo1angT** [comment]
VS Code 1.43.1
both Remote SSH 0.49.0 & 0.50.0 didn't work

**Comment by rzhao271** [comment]
@zhuo1angT closing this issue for now. Feel free to reply if it is still showing up for you on the latest VS Code.
