### ISSUE TITLE
Remote SSH connect doesn't follow SSH_AUTH_SOCK

### ISSUE THREAD

**Issue by CzBiX** [microsoft/vscode-remote-release#2584]
Issue Type: <b>Bug</b>

I installed "git for windows", and set `SSH_AUTH_SOCK` environment variable in `%userprofile%/.profile`. It works well when I ssh to remote in the `git-bash` command.
But "Remote SSH" doesn't follow it. I tried add environment in Windows, or `terminal.integrated.env.windows` in VSC settings, neither of variables works.

Extension version: 0.50.0
VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.19041

**Comment by ksurl** [comment]
try in system properties environment variables (sysdm.cpl -> advanced)

**Comment by CzBiX** [comment]
Weird, I tried it at before, but won't work. Now it works.
Maybe I forget to restart VSC. 
@ksurl Thanks, man
