### ISSUE TITLE
Remote WSL cli: support installing extensions

### ISSUE THREAD

**Issue by alanlivio** [microsoft/vscode-remote-release#2589]
I tried to install an extension in WSL2 and I received the following error.

` ` ` 
$ code --install-extension
` ` ` 
` ` ` 
  Ignoring option install-extension: not supported for code.
` ` `

**Comment by rapgru** [comment]
@aeschli Do you know of any other method for installing extensions on a remote host? I automated my Windows setup with Boxstarter and would like to non-interactively install extensions in WSL.

Related issues requesting similar functionality are #2749, #2704 and #2393.

**Comment by chatziko** [comment]
@rapgru : just curious, did you find a workaround for this?

**Comment by rapgru** [comment]
@chatziko 
Unfortunately not, I just keep a list of extensions I have to install manually after the installation script. If you put the effort in and come up with a solution, please let me know!

**Comment by ZhangYuef** [comment]
Does anyone have ideas on this issue? 

I cannot install Python extension on a remote host by using extension viewlet.

**Comment by aeschli** [comment]
@ZhangYuef Installing using the extension viewlet. should work. Please file a separate issue. 
This issue is about installing a remote extension through the remote cli.

**Comment by ZhangYuef** [comment]
> @ZhangYuef Installing using the extension viewlet should work. Please file a separate issue with more details.
> This issue is about installing a remote extension through the remote cli.

Thank for pointing out. I open a new issue #3853 to find help for my problem.

**Comment by marwan-at-work** [comment]
Would love to see this issue get resolved as this can unlock a lot of automation for remote development

**Comment by alanlivio** [comment]
I workaround this issue by create a alias to Windows binary: 
`alias code="cmd.exe /c 'C:\Program Files\Microsoft VS Code\bin\code'"`
By doing this, run `code --install-extension` works.
It enable automate installation of extensions but it install only the Windows side of the VS Code. 
I still need open WSL connection to enable the extensions in WSL side of the VS Code.

**Comment by hasayakey** [comment]
easy!!! in wsl use code . to open current folder in VSCode, then Extensions->install from VSIX

**Comment by marwan-at-work** [comment]
@hasayakey that is not automat-able

**Comment by PavelSosin-320** [comment]
This is theoretically automatable if you have Windows Pro with enabled remote execution. Ansimble can work with Windows host. If you have a strong IT team behind your back you can execute Powershell script or Playbook. Ask your corporate IT. Don't do it at home!

**Comment by alanlivio** [comment]
Yes @hasayakey it not automatable.

**Comment by aeschli** [comment]
The remote CLI in the integrated terminal of remote windows now supports:

`code --install-extension idOrPathToVSIX` in combination with `--force`
`code --uninstall-extension idOrPathToVSIX` in combination with `--force`
'code --list-extensions` in combination with --show-version and --category
