### ISSUE TITLE
overrideCommand in devcontainer.json has no effect

### ISSUE THREAD

**Issue by art-in** [microsoft/vscode-remote-release#259]
- VSCode Version: 1.34.0-insider (user setup)
- Local OS Version: Windows 10.0.17763 x64
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Using existing Dockerfile with `ENTRYPOINT` script.  
2. Setting `"overrideCommand": true` (which is default) in devcontainer.json explicitly.

I expect that `ENTRYPOINT` script will not be executed when opening folder in container.  
But it is still executed.  

<details>
<summary>Dockerfile</summary>

```
FROM ubuntu:18.04

# set entry (forwards args from cli)
ENTRYPOINT ["bash", "/opt/project/scripts/run.sh"]

# install tools
RUN apt-get update
RUN apt-get install -y curl xz-utils

# install nodejs
RUN mkdir -p /opt/node
WORKDIR /opt/node
RUN curl https://nodejs.org/dist/v10.15.3/node-v10.15.3-linux-x64.tar.xz -o node-v10.15.3-linux-x64.tar.xz
RUN mkdir -p /usr/local/lib/nodejs
RUN tar -xJvf node-v10.15.3-linux-x64.tar.xz -C /usr/local/lib/nodejs
ENV PATH=/usr/local/lib/nodejs/node-v10.15.3-linux-x64/bin:$PATH

# copy project sources
COPY . /opt/project/
WORKDIR /opt/project/

# install project dependencies
RUN npm install

# build project
RUN /opt/project/scripts/build.sh
```

</details>

<details>
<summary>devcontainer.json</summary>

```
{
	"name": "vscode-docker-node",
	"context": "..",
	"dockerFile": "../docker/Dockerfile",
	"appPort": [3000, 8080],
	"extensions": [
		"eamodio.gitlens",
		"dbaeumer.vscode-eslint"
	],
	"runArgs": [
		"-v",
		"/var/run/docker.sock:/var/run/docker.sock"
	],
	"overrideCommand": true
}
```

</details>

**Comment by drorata** [comment]
An expected use case is to have a `Dockerfile` with an `ENTRYPOINT` defined for the actual operation. However, having the entry point in the `Dockerfile` block opening the folder in the container. Any thoughts?

**Comment by artin-phares** [comment]
@drorata probably entry operation fails for some reason and at the time vscode tries to connect to container it is already stopped.

in my case entry operation fails because of lack of cli arguments.  
as a workaround i've added `sleep infinity` to my entry if no args, assuming it was started by vscode.

**Comment by drorata** [comment]
@artin-phares can you provide a more detailed example. I tried something like appending `ENTRYPOINT [ "/prj/entrypoint.sh"]` to `Dockerfile` where `/prj/entrypoint.sh` is:

```bash
#!/bin/bash
set -e

if [ -z "$1" ]
  then
    echo "No argument supplied"
    sleep infinity
  else
    python app.py $@
fi
```
but it doesn't work.

**Comment by artin-phares** [comment]
@drorata 

i'm using this in my `run.sh`

```bash
# handle args
while test $# -gt 0
do
    case "$1" in
        --dev) ARG_DEV=1 ;;
        --backend-url*) ARG_BACKEND_URL=$1 ;;
        # sleep infinity instead of just exit, because when container starts with
        # vs-code 'open folder in container' entry point with this script is not 
        # getting overriden with "sleep infinity" as it should.
        # https://github.com/microsoft/vscode-remote-release/issues/259
        *) echo "Invalid argument '$1'." && sleep infinity ;; # TODO: exit 1
    esac
    shift
done
```

so yeah, it's not "lack of cli args", but rather "lack of *required* cli args + having unknown args".  
and on unknown args we going `sleep infinity`.

**Comment by drorata** [comment]
I'm sorry but, I don't understand the example given by @artin-phares. Where do you actually call your code?

**Comment by chrmarti** [comment]
`"overrideCommand": true` not overriding `ENTRYPOINT` is a bug tracked with this issue. I plan on fixing that.

**Comment by chrmarti** [comment]
Verification: Have a Dockerfile with an ENTRYPOINT set to something random, so the container would not start if that wasn't overridden. Verify that Remote Containers can start the container when `"overrideCommand"` is `true` and cannot start it when it is `false`.
