### ISSUE TITLE
Cannot run react application using vscode with ssh remote plugin to WSL.

### ISSUE THREAD

**Issue by wangbohan2000** [microsoft/vscode-remote-release#2592]
When I use ssh remote plugin to connect tot WSL on windows, React APP cannot be started through vscode built-in terminal.

**Comment by bamurtaugh** [comment]
Hey @wangbohan2000, do you have any additional info here? Also, we're [adding info to the docs ](https://github.com/microsoft/vscode-docs/pull/4106)about how to SSH into a remote WSL host, so perhaps that could address your scenario?

**Comment by bamurtaugh** [comment]
Please feel free to let us know if you're still experiencing any issues here. Thank you!
