### ISSUE TITLE
Can't SSH tunnel when it was working fine yesterday

### ISSUE THREAD

**Issue by Blinines** [microsoft/vscode-remote-release#2593]
- VSCode Version: 1.43.1
- OS Version: Windows 10
- Extension : Remote - SSH

I have had some problems when using the Remote development package recently, and more specifically when using the SSH Tunnel. While it worked perfectly fine within the first few weeks, nowadays VSCode often fails to connect to the host, and as I don't change the parameters I still can't find what's not working well.

On Thursday I noticed that an updated version was released : 1.43.1. Hence I cleaned the .vscode-server folder (rm -r ~/.vscode-server) on my remote machine and rebuilt the SSH tunnel configuration yesterday and it was working perfectly fine. When I tried to log in today, the connection to host failed, and it seems to be because I have an accent in my name. It seems that the remote machine struggles to read the `è`, hence causing an error, but the `locale` is set to UTF-8 and it was working before. I also don't have sudo privileges on the remote machine. I searched the already opened issues but none seemed to correspond to my specific problem..

The last logs are as follows : 
Can't open user config file "C:\\Users\\[userid with utf8]\\.ssh\\config"
Failed to parse remote port from server output
Resolver error

Does anyone has an idea on how to fix this ? Or is there is any other turanround ?

Thanks a lot for your help!

**Comment by roblourens** [comment]
Does this help?

```
"remote.SSH.useLocalServer": false,
"remote.SSH.windowsRemotes": ["<your remote hostname>"] // only if the remote is Windows
```

if not could you share the full log from the Remote-SSH output channel? Thanks

**Comment by Blinines** [comment]
Hello @roblourens ,
Thank you for your response ! 

I had already set those options to the `settings.json` file on the remote machine, yet it is still not working.

You will find below the corresponding logs from the Remote-SSH output channel.

![log_ssh](https://user-images.githubusercontent.com/32418335/77258262-d47c9b00-6c79-11ea-80e0-3ceb98ae9ca7.PNG)


Thanks again !
Best

**Comment by roblourens** [comment]
They need to be set in settings on the local machine

**Comment by Blinines** [comment]
@roblourens 
I changed the settings on the local machine and it worked this morning!

Thanks a lot for your support, I hope I won't have any other problems !

Thanks again,
Best
