### ISSUE TITLE
Reload SSH shell bash session is lost

### ISSUE THREAD

**Issue by HthSolid** [microsoft/vscode-remote-release#2596]
I've searched for duplicates but couldnt find a matching one to my request.

If the connection is lost or you reconnect/reload, the bash sessions are lost, it would be great if the connection would restore the previous terminal shell bash sessions, as they are still running on the remote machine.

**Comment by roblourens** [comment]
I recommend using something like tmux, which excels at this exact scenario. But we don't plan to implement this builtin to vscode.
