### ISSUE TITLE
Cant open readonly file on Remote Containers

### ISSUE THREAD

**Issue by comefigo** [microsoft/vscode-remote-release#2598]
I'm sorry, my English is not good.
I think this is probably a bug.

- VSCode Version:  1.43.0
- Local OS Version: Microsoft Windows 10 Pro 18363
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. clone https://github.com/microsoft/vscode-remote-try-go to local
2. run remote container.
3. crete readonly text file ( before write some text to this text file)  on explorer.
4. open this readonly text file on VSCode(Remote container mode) and get cant open error message by VSCode. but it can open on Local mode.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by Chuxel** [comment]
This is likely caused by an "upstream" Docker bug with 2.2.0.4. There is an experimental version that supposedly has it fixed:

https://github.com/docker/for-win/issues/6016#issuecomment-600285551

**Comment by comefigo** [comment]
thx @Chuxel 

its a docker problem!?
ok. Im try Docker stable version 👍
