### ISSUE TITLE
SSH Remote skipping nodejs breakpoints from Windows to Linux (CentOS 7.7) 

### ISSUE THREAD

**Issue by TonyApuzzo** [microsoft/vscode-remote-release#2599]
I searched but couldn't find any exact matches in open issues.

- VSCode Version:
  1.43.1 and 1.44.0-insiders 2020-03-22
- Local OS Version:
   Windows 10 Insider Version 10.0.19587 Build 19587
- Remote OS Version:
```
$ cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
$ uname -a
Linux development-centos-7 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ node --version
v12.16.1
```

- Remote Extension/Connection Type: SSH/Docker/WSL

SSH

Steps to Reproduce:

demo.js
```
console.log('First')
console.log('Second')
console.log('Third')
```

launch.js
```
    {
      "type": "node",
      "address": "localhost",
      "request": "launch",
      "name": "Run Current File",
      "program": "${file}",
      "skipFiles": ["<node_internals>/**"],
      "protocol": "inspector",
      "stopOnEntry": false
    }
```

0. Establish a workspace
1. Create `demo.js` in the workspace, note that the window's path label shows the workspace folder relative path in it e.g. _folder1 · folder2_
2. Add the launcher
3. Set a breakpoint at any line in `demo.js`
4. Run the launcher
5. Note that the breakpoint does not hit
6. Change "stopOnEntry" to `true`
7. Run the debug launcher
8. Unexpectedly, a new editor tab is opened for `demo.js` and this new window has no breakpoints set. Note that the titlebar for this window shows the truncated fully-qualified path from root e.g. _/home/.../code..._.
9. Note that the debugger stops on line 1 in this new window based on stopOnEntry being true.
10. Note that if you do create a new breakpoint at line 3 in this new tab and click resume, that breakpoint does hit
11. Note that in the file-history, there are two listings for `demo.js`, if you close and re-open the file using the first entry then breakpoints are not hit in that window. If you re-open the second window, then breakpoints are hit.

Unfortunately the kinda-sorta-workaround I described here does not work if you are using an actual project since it isn't posible to get the working editor to pop up if it isn't the "first" editor that gets opened automatically.

Does this issue occur when you try this locally?: Yes/No
No -- when running local on the VM (or remotely logged in over xRDP), the debugger works as expected.

Does this issue occur when you try this locally and all extensions are disabled?: Yes/No
Yes -- well, I do have to enable at least the remote extension

**Comment by TonyApuzzo** [comment]
Another note: this is affecting all my debugging, the above is just the smallest reproducer I could find.  Right now this bug is a total blocker for running Mocha and Jest tests in my project over SSH Remoting.

**Comment by roblourens** [comment]
Could you try this with our new debugger implementation? It fixes some issues that might help here. https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger
