### ISSUE TITLE
Remove Linux (x86_64) Restriction

### ISSUE THREAD

**Issue by martyfranchuk** [microsoft/vscode-remote-release#260]
A lot of people having the same connect error. Just because...

The Remote-SSH is OVERLY enforcing the Linux x86_64 construct. I can SSH into my Win10, and my Raspberrypi, but the Remote-SSH will reject the 'working' connection, since it doesn't find the Linux x64 tag it is looking for. (what in Linux are they doing that would be specific to x64 architecture? Isn't that what the OS is handling, removing the HW mapping??)

I MAINTAIN, that this Remote-SSH will work with other platform connections, IF they did not enforce this restriction; perhaps a 'warning' would suffice. Just in case.

 Willing to bet, the Linux portion is not necessary, either. Systems hosting SSH can be pretty sure to allow related command constructs (scp, ...)

**Comment by mjbvz** [comment]
This is already being tracked per platform, such as #24 and #71. It is not an arbitrary restriction, the server really just does not work on those other platforms right now
