### ISSUE TITLE
Mixed debugging within docker dev container

### ISSUE THREAD

**Issue by andrewbridge** [microsoft/vscode-remote-release#2600]
- VSCode Version: 1.43.1
- Local OS Version: macOS Catalina 10.15.2
- Remote OS Version: Amazon Linux 2 (Karoo) (`ID_LIKE="centos rhel fedora"`)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:
### `devcontainer.json`
```json
{
	"image": "[custom image in a private code repository]",
	"forwardPorts": ["various ports to serve web interfaces"],
	"runArgs": [
		"--cap-add=SYS_PTRACE",
		"--security-opt",
		"seccomp=unconfined"
	],
	"extensions": [
		"ms-vscode.cpptools",
		"ms-vscode.cmake-tools",
		"hbenl.vscode-test-explorer",
		"derivitec-ltd.cmake-test-adapter",
		"ms-dotnettools.csharp",
		"fernandoescolar.vscode-solution-explorer",
		"derivitec-ltd.vscode-dotnet-adapter"
	  ],
	  "mounts": [
		  "source=${localEnv:HOME}/.gitconfig,target=/root/.gitconfig,type=bind,consistency=cached",
		  "source=${localEnv:HOME}/.ssh,target=/root/.ssh,type=bind,consistency=cached"
	  ]
  }
```

### `launch.json`
```json
{
            "name": "(gdb) Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "/usr/share/dotnet/dotnet",
            "processId": "${command:pickProcess}",
            "additionalSOLibSearchPath": "${workspaceFolder}/src/build/Debug/Cpp/",
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        },
        {
            "name": "Run C#",
            "type": "coreclr",
            "request": "launch",
            "program": "${workspaceFolder}/src/AppProject/bin/Debug/netcoreapp2.2/AppProject.dll",
            "args": [],
            "cwd": "${workspaceFolder}/src/AppProject",
            "stopAtEntry": false,
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development",
                "EnvironmentName": "Development",
                "LD_LIBRARY_PATH": "${workspaceFolder}/src/build/Release/Cpp/;$LD_LIBRARY_PATH"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        }
}
```

When running a .Net Core 2.2 codebase containing C# and C++
1. Launch "Run C#"
2. Launch "(gdb) Attach" and select the dotnet process started by the previous launch

The above steps work successfully when running via an equivalent VM image over SSH, i.e. I am able to debug through both C# and C++ code in the same debugging session.

However, the same steps do not work via Docker container. [I've posted the output I see following the 2nd attach in a Docker environment to PasteBin.](https://pastebin.com/Y94BC6LX)

As I am able to debug C# and C++ separately, and as I've seen it work in alternative, remote environments I'm raising it as a bug here rather than a question elsewhere. However, if this is user error or if there's a more appropriate place for my question/issue, apologies in advance and I'd be happy to close/move to a better place.

As our codebase is not setup to build natively in macOS, I have not been able to compare the bug locally, only in alternative remote environments as described above.

**Comment by chrmarti** [comment]
Have you tried installing an SSH server in the container and connecting using Remote-SSH to compare? I wonder if this could be specific to your Docker image, but not necessarily to Remote-Containers.
