### ISSUE TITLE
Current or Nightly: "command 'opensshremotes.XYZ' not found"

### ISSUE THREAD

**Issue by sixtyfive** [microsoft/vscode-remote-release#2601]
(This might or might not be a duplicate/regression of #621)

- VSCode Version: 1.44.0
- Local OS Version: Solus OS with latest updates applied
- Remote OS Version: ArchLinux
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install VSCode
2. Install either the current or the nightly version of Remote-SSH
3. Try to do anything (open the help, connect to a host, doesn't matter)

The error message is always the same, "command 'opensshremotes.XYZ' not found" where XYZ would be "getHelp" and "openEmptyWindow" for the above two examples.

**Comment by roblourens** [comment]
Also had https://github.com/microsoft/vscode-remote-release/issues/2550 filed but I haven't been able to reproduce this.

Where are you clicking in step 3? Just asking becuse there are multiple ways to do those things (although it shouldn't matter)

**Comment by sixtyfive** [comment]
> Where are you clicking in step 3? Just asking becuse there are multiple ways to do those things (although it shouldn't matter)

I press F1, type "ssh", and then choose from the filtered list. What other ways are there?

**Comment by benjaminbauer** [comment]
Same here:

-     VSCode Version: 1.43.2
-     Local OS Version: Ubuntu 18.04 LTS
-     Remote OS Version: ArchLinux
-     Remote Extension/Connection Type: SSH

**Comment by sixtyfive** [comment]
>     * Local OS Version: Ubuntu 18.04 LTS 
>     * Remote OS Version: ArchLinux

I also tried with Solus as the Remote OS now. Same thing.

**Comment by benjaminbauer** [comment]
Might this be an issue with the windowmanager? I am using [i3](https://i3wm.org/), which is not what most people test with

**Comment by sixtyfive** [comment]
How does the window manager interfere with an Electron plugin's internal circuitry? FWIW, mine is Budgie, which is Gnome-3-based, which is fairly widely-used. No, this is something else.

**Comment by roblourens** [comment]
How did you all install vscode on Arch? Are you using the official microsoft build?

**Comment by roblourens** [comment]
And if you open the developer tools (Help > Toggle developer tools) do you see any errors in the console that might be related to activating this extension?

**Comment by benjaminbauer** [comment]
> How did you all install vscode on Arch? Are you using the official microsoft build?

Nevermind, I just realized, that I am using https://github.com/VSCodium/vscodium/ and thus this is related to https://github.com/VSCodium/vscodium/issues/266

Cannot reproduce the issue on the official 1.43.2 build.

Sorry for the confusion!

**Comment by sixtyfive** [comment]
Hmm, sorry for being late.

My version is this:

```
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-27T06:58:28+02:00
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.5.7-150.current
```

Can we re-open, Rob?

**Comment by roblourens** [comment]
Is this the official Microsoft build of vscode?

**Comment by sixtyfive** [comment]
I have no idea. The way I installed it was to go to Solus's Software Center, search for Visual Studio Code, and hit the "Install" button. Is there any way to be certain beyond the above _implication_ that it's not the official build?
