### ISSUE TITLE
Config local mirror workspace in order to working on unstable network connections

### ISSUE THREAD

**Issue by FajunChen** [microsoft/vscode-remote-release#2603]
Remote ssh should have local cache for remote workspace, thus working on local copies is still possible even when the connection is temporary down.

**Comment by roblourens** [comment]
We don't plan to do this but you might check out a workflow like this: https://code.visualstudio.com/docs/remote/troubleshooting#_using-rsync-to-maintain-a-local-copy-of-your-source-code
