### ISSUE TITLE
Connected to the remote server in VScode, but failed to debug(connection refused)

### ISSUE THREAD

**Issue by zeal-github** [microsoft/vscode-remote-release#2604]
- VSCode Version: 1.43.1
- Local OS Version: windows 10
- Remote OS Version: Ubuntu 14
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. connect to host
2. debug an arbitrary file(python)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

I can successfully connect to a remote host in Vscode using SSH connecting. And actually I have used the remote debug function for several days. Today my server host is forced to add a firewall that rejects all input flow except the ssh connection. I can still successfully connect to the remote host in the VScode. How ever, when I try to debug a python file, vscode throw an error as:
```
  File "/home/lab-lin.ziyao/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher/__main__.py", line 42, in main
    launcher.connect(launcher_port)
  File "/home/lab-lin.ziyao/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher/../../debugpy/launcher/__init__.py", line 27, in connect
    sock.connect(("127.0.0.1", launcher_port))
```
and popup an error window like:
![image](https://user-images.githubusercontent.com/40826585/77388599-8c6d8d80-6dcb-11ea-9558-e1139ad59f80.png)
I have asked my network manager to close the firewall but the bug still exists. I try my other remote server, everything is ok. I don't know why and cannot find similar issues on the web.

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues

Thanks!
