### ISSUE TITLE
Used to Be Able to Connect to Remote Servers - Cannot Anymore

### ISSUE THREAD

**Issue by playcock** [microsoft/vscode-remote-release#2605]
VSCode Version: 1.43.0 (user setup)
Local OS Version: Windows_NT x64 10.0.18363
Remote OS Version: Ubuntu 18.04
Remote Extension/Connection Type: SSH
Remote - SSH(Nightly) version 2020.3.32580

When this extension works, it is simply amazing and makes me feel like I cannot do development without it.

It meets all of my expectations and it has been highly enjoyable discovering the additional tools it offers.

Lately, I am disheartened that I have been experiencing the worst of time trying to connect to my remote servers again and again.

I cannot connect to my remote servers.

This is the Output from my Terminal:
![image](https://user-images.githubusercontent.com/9416592/77459503-33572700-6dd6-11ea-9ed8-a40dd1e9e241.png)

**Comment by roblourens** [comment]
Does this help?

```
"remote.SSH.useLocalServer": false,
"remote.SSH.windowsRemotes": ["<your remote hostname>"] // only if the remote is Windows
```

**Comment by playcock** [comment]
I'm going to try that.

**Comment by playcock** [comment]
> Does this help?
> 
> ```
> "remote.SSH.useFlock": true
> ```

Unfortunately, no, it didn't help. Thanks though.

This is my settings.json, if that helps:
```
{
    "update.mode": "none",
    "php.validate.executablePath": "C:\\xampp\\php\\php.exe",
    "php.executablePath": "C:\\xampp\\php\\php.exe",
    "remote.SSH.useFlock": true
}
```

**Comment by roblourens** [comment]
Could you share the log again with that flag? Also you could try this

**Comment by playcock** [comment]
> Also you could try this
> 
> ```
> "remote.SSH.useLocalServer": false,
> "remote.SSH.windowsRemotes": ["<your remote hostname>"] // only if the remote is Windows
> ```
I added the useLocalServer setting. The remote servers are Ubuntu, so I did not add the windowRemotes setting.
```
{
    "update.mode": "none",
    "php.validate.executablePath": "C:\\xampp\\php\\php.exe",
    "php.executablePath": "C:\\xampp\\php\\php.exe",
    "remote.SSH.useFlock": true,
    "remote.SSH.useLocalServer": false
}
```
> Could you share the log again with that flag?

Sure thing! Here it is:

![image](https://user-images.githubusercontent.com/9416592/77465871-bb8dfa00-6ddf-11ea-9add-40d01e86391b.png)

**Comment by playcock** [comment]
> Could you share the log again with that flag?
Here you go. Thank you!

![image](https://user-images.githubusercontent.com/9416592/77467583-a1a1e680-6de2-11ea-80b9-92a5d25de2b9.png)

**Comment by roblourens** [comment]
Thanks. You can remove that setting I told you to set, and delete the file referenced in the first log "failed to create hard link". 

I am tracking this issue in https://github.com/microsoft/vscode-remote-release/issues/2518

**Comment by playcock** [comment]
@roblourens Thanks for working with me through this. I jumped through some hoops, killing locks, deleting tars, etc, rinse, repeat and I am again able to connect to my remote servers. I really like this extension when I have it working. I think one of my most favorite features is being able to use the vscode "Find in Folder" on the remote servers. Thanks again!
