### ISSUE TITLE
Test asking for remote server platform + disabling useLocalServer on Windows

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#2606]
Test https://github.com/microsoft/vscode-remote-release/issues/2569

- [x] Windows @mjbvz 
- [x] macOS @JacksonKearl 

Complexity: 2

---

Basically there are two changes
- When `useLocalServer` is disabled, we will show a popup asking the user for the platform of the remote
- `useLocalServer` will be disabled by default on Windows (see the linked issue for background)

Steps
- Clear out any `remote.SSH.remotePlatform` setting that is already set (if you have been using ssh nightly, it may have been populated already)
- Connect to a remote of any platform
- On Windows by default, you should get a prompt asking for the platform of the remote.
- On non-windows by default, you should not
  - Please test that the experience did not change on non-windows. Then, manually disable `useLocalServer` and continue testing the experience below.
- Then, you should get an explanatory notification and the selection should be stored in the `remote.SSH.remotePlatform` user setting
- If you connect again, and the setting is set, you should not get the platform prompt
- Share any feedback about the experience/wording/etc

**Comment by JacksonKearl** [comment]
A bit confused, should `useLocalServer` be enabled by default on non-windows? I thought we couldn't reliably detect the server OS regardless of platform?

**Comment by roblourens** [comment]
It should be enabled by default on non-windows, and we can more or less reliably detect the server OS when it is enabled.

**Comment by roblourens** [comment]
There should be no changes to the experience by default on non-windows. I would like you to test that and then disable useLocalServer and test that the above steps work. Sorry, steps are unclear.

**Comment by mjbvz** [comment]
Experience on windows matches what you describe and made sense to me.

Super small nit, `remotePlatform` uses markdown in its description but it is rendered as plaintext

![Screen Shot 2020-03-25 at 5 53 52 PM](https://user-images.githubusercontent.com/12821956/77599380-b0ab9600-6ec1-11ea-95e6-1781b57f016d.png)

**Comment by roblourens** [comment]
Will leave this open so the assignment tool calculates your points.

**Comment by Morgy93** [comment]
Well, "it works", but would it somehow be possible to get that information from ssh config?
I'm not sure if there's an option that could be (ab)used for that, but comments would work at least.

```
Host this-is-my-host.cloud
    # Platform linux
    HostName this-is-my-host.cloud
    User root
    ForwardAgent yes
```

I'm asking because everyone in our company is using the same ssh config file and this way I could auto deploy these settings for everyone 🙂

**Comment by roblourens** [comment]
Is it possible for you to deploy the vscode setting in the settings.json?

**Comment by Morgy93** [comment]
Sadly not, the ssh config is shared between users, but the settings.json is managed by everyone individually.
I mean it's not super important to have this feature, it was just some idea of mine. 🙂

**Comment by roblourens** [comment]
I can see that something like this would be useful, and can imagine this coming up again. I will keep it in mind, thanks.

**Comment by vilic** [comment]
@roblourens It would be nice to have some wildcard support, the hosts of our remote servers are dynamically assigned. It is a little bit annoying to choose a platform every time and result in a long remote platform list in settings.json.

**Comment by Morgy93** [comment]
Wildcard support would actually even solve my "deploy issue" mentioned earlier. 👍

**Comment by roblourens** [comment]
Good idea, I opened https://github.com/microsoft/vscode-remote-release/issues/2997
