### ISSUE TITLE
Fetching the wrong SSH config

### ISSUE THREAD

**Issue by alex310110** [microsoft/vscode-remote-release#2607]
- VSCode Version: 1.43.1
- Local OS Version: Windows 10 Enterprise 1903 18362.720
- Remote Extension/Connection Type: SSH

I'm working in a company-customized SSH environment, so I might not be able to share some detail, but I think I found the issue and worked-around it. This broke on last Friday (2020 Mar 20), so I suppose it's because of the recent extension release.

I noticed the usage of "-F" flag of ssh command to point to an SSH config file; I wonder this is newly added, and I think it broke the flow in my company setup. Basically it's now using -F flag to use ~/.ssh/config by default which doesn't have company's customized SSH configs. If I set to use the ssh_config file the company ssh.exe regularly uses, this file is restricted to be read-only, so it can't save my hosts and cause write permission issue. The workaround is to copy the content of read-only ssh_config file to ~/.ssh/config.

I hope it provides enough detail for this issue if -F flag is indeed recently added to the release. Thanks.

**Comment by roblourens** [comment]
This should be fixed in the Nightly version of the Remote-SSH extension, could you check? (uninstall the stable extension first) https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly

**Comment by alex310110** [comment]
Hi Rob, Nightly version works. Thanks!

**Comment by alex310110** [comment]
Does the Nightly version do SSH multiplexing? This doesn't seem to be working in Nightly compared to the stable release. Is there any expectation on when the fix will hit stable release?

**Comment by roblourens** [comment]
Thanks for confirming! Sorry I'm not sure what you are referring to by ssh multiplexing.

**Comment by roblourens** [comment]
This fix will be in stable by EOW

**Comment by alex310110** [comment]
If I execute "Remote-SSH: New Window on Active Host" / opensshremotes.openEmptyWindowOnCurrentHost on stable release, this is very fast and probably reusing the existing SSH connection. This is not the case on Nightly where I need to establish another SSH connection. There's additional authenticating step in my company's SSH, so that this is observable.

**Comment by roblourens** [comment]
Yeah - you can actually get that experience back by setting `remote.SSH.useLocalServer` to true, then set `remote.SSH.configFile` to the correct path to your config file. And I'm curious why we are not discovering your config in that file correctly...

Is there a config with the same name in `~/.ssh/config`? Or is it in a non-standard location but configured with ssh some other way?

**Comment by alex310110** [comment]
I think it's a non-standard location, and the SSH on my company Windows is heavily customized for security reasons. It's located at C:\<some-package-name>\etc\ssh_config, and the file is read-only.

**Comment by roblourens** [comment]
Ok. I'm curious how ssh is discovering it in that case. But setting `configFile` is probably best for your case.

**Comment by alex310110** [comment]
Within <some-package-name> folder seems to be a cygwin system by itself, and it's where the ssh.exe is located. But I'm no expert on this to tell exactly how...
