### ISSUE TITLE
VSCODE force Close when i close ssh connection that opened in current windows vscode

### ISSUE THREAD

**Issue by marvin46** [microsoft/vscode-remote-release#2609]
VSCODE force Close after closing an ssh remote that opened in a current window vscode.
just open remoe ssh in current window, and when you close ssh remote or disconnet ssh, the vscode is closed too. 

Extension version: 0.50.1
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 6.1.7601
Remote OS version: Linux x64 3.10.0-962.3.2.lve1.5.25.10.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|5.90GB (2.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: alika|
|OS|Linux x64 3.10.0-962.3.2.lve1.5.25.10.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz (16 x 2499)|
|Memory (System)|23.54GB (3.63GB free)|
|VM|100%|
</details>

**Comment by roblourens** [comment]
Sorry  I don't understand the issue, please give more details.

**Comment by marvin46** [comment]
If you open ssh connection in current window, 
Next,
After ssh is connected, just do close ssh connection or disconnect ssh, 
So 
The Whole VS Code is closed too, 
I think that should be closed is only the ssh connection, not VS Code Window

Best Regards 
Marvin Priyatno

**Comment by roblourens** [comment]
Do you mean "Close remote connection"? The window should reload as a local window. Is that not what you see?
