### ISSUE TITLE
[Remote-SSH] Doesn't support passphrase (fails to connect)

### ISSUE THREAD

**Issue by dcwither** [microsoft/vscode-remote-release#261]
- VSCode Version: Version 1.34.0-insider (1.34.0-insider) daf71423252a707b8e396e8afa8102b717f8213b
- OS Version: Mac OS 10.14.4

Steps to Reproduce:
1. Have ssh key set up with passphrase
2. Attempt connection
![X22MhZpsT2di3jXvCveKfzacFUOw_sqKKiM4Bn_u9GezyRtPV_TvmVIAlCmEQ5F6S2hiP9Ij-OrCi5bafOZ0MHL51NG9LNIi-WVBxAF-mItMY4JIX7Pddv5xjFlsTTob7DvqMqXZ](https://user-images.githubusercontent.com/1641405/57475692-ad77cf00-7249-11e9-8497-882247736c38.gif)

Expected:
- Requests passphrase and waits before continuing

Actual:
- Fails immediately, and closes terminal

Does this issue occur when all extensions are disabled?: No

**Comment by kieferrm** [comment]
It seems like ssh complains about a bad passphrase. I'm guessing you were asked for a passphrase, entered it, but mistyped. I suspect we add the passphrase to the ssh-agent without checking first whether the passphrase actually works.

**Comment by dcwither** [comment]
Hi @kieferrm, thanks for the quick response. The passphrase was never entered, so I don't know when we had the opportunity to mistype it.

**Comment by dcwither** [comment]
![bad passphrase](https://user-images.githubusercontent.com/1641405/57487411-58e24d00-7265-11e9-91ea-946a7cf19c9a.png)

Looks like one of the frames had this "bad passphrase" message before closing the terminal, but no passphrase was entered (not even the first time it was loaded).

**Comment by sadasant** [comment]
I had a similar issue. What worked for me was to *paste* the passphrase instead of typing it 🤔 Now things are working normally.

**Comment by roblourens** [comment]
Sorry for the delayed response. If this is still happening, could you share the output from the "Remote - SSH" output channel?

Not sure why it doesn't give you a chance to enter the passphrase.
