### ISSUE TITLE
ssh remote could not connect to remote machine

### ISSUE THREAD

**Issue by sakizhu** [microsoft/vscode-remote-release#2610]
I can connect to remote  machine  through windows command line，like this
![image](https://user-images.githubusercontent.com/9567827/77523842-54e10d00-6ec1-11ea-855c-68a00edb6565.png)
but when I used remote ssh extension to connect remote machine , it has some error like this 
![image](https://user-images.githubusercontent.com/9567827/77523957-835ee800-6ec1-11ea-9afb-f5de475ae4cc.png)
and on the left-buttom, it shows connect success
![image](https://user-images.githubusercontent.com/9567827/77524058-af7a6900-6ec1-11ea-8807-913ea96d0769.png)
but when I open directory on remote machine, it only shows the directory in wondows
 
![image](https://user-images.githubusercontent.com/9567827/77524165-dafd5380-6ec1-11ea-87ac-d6e93ab87115.png)

could you please help me， is's something wrong with my config?

**and the remote machine is a docker container**
and i don't know if it is the root reason

**Comment by logchan** [comment]
Try downgrading to `0.49`.

I also had issue connecting to remote since `0.50`.

**Comment by roblourens** [comment]
Please share the log from the Remote-SSH output channel. 

Also does this help?

```
"remote.SSH.useLocalServer": false,
"remote.SSH.windowsRemotes": ["<your remote hostname>"] // only if the remote is Windows
```

**Comment by zhaoxf4** [comment]
I also had same issue in 0.50.1.
I have four servers, server 2~4 is ok but sever 1 couldn't be connected(maybe administrator restore sth).
```
[22:23:55.838] Log Level: 2
[22:23:55.843] remote-ssh@0.50.1
[22:23:55.843] win32 x64
[22:23:55.845] SSH Resolver called for "ssh-remote+server_1", attempt 1
[22:23:55.846] SSH Resolver called for host: server_1
[22:23:55.846] Setting up SSH remote "server_1"
[22:23:55.850] Acquiring local install lock: C:\Users\zhaoxf4\AppData\Local\Temp\vscode-remote-ssh-server_1-install.lock
[22:23:55.863] Looking for existing server data file at c:\Users\zhaoxf4\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-server_1-0ba0ca52957102ca3527cf479571617f0de6ed50-0.50.1\data.json
[22:23:55.864] Using commit id "0ba0ca52957102ca3527cf479571617f0de6ed50" and quality "stable" for server
[22:23:55.865] Install and start server if needed
[22:23:55.870] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[22:23:55.910] > OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
[22:23:55.914] Using SSH config file "C:\Users\zhaoxf4\.ssh\config"
[22:23:55.914] askpass server listening on \\.\pipe\vscode-ssh-askpass-451d7fbd4363df87f2784660fa5467163f3d67b4-sock
[22:23:55.915] Spawning local server with {"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-f295d53425a8db9e73622075ef27c73230729286-sock","sshCommand":"C:\\Program Files\\Git\\usr\\bin\\ssh.exe","sshArgs":["-v","-T","-D","3031","-F","C:\\Users\\zhaoxf4\\.ssh\\config","server_1"],"dataFilePath":"c:\\Users\\zhaoxf4\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-server_1-0ba0ca52957102ca3527cf479571617f0de6ed50-0.50.1\\data.json"}
[22:23:55.915] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\zhaoxf4\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.50.1\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Users\\zhaoxf4\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\zhaoxf4\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.50.1\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-451d7fbd4363df87f2784660fa5467163f3d67b4-sock"}
[22:23:55.973] Spawned 11388
[22:23:56.052] > local-server> Spawned ssh: 13376
[22:23:56.072] stderr> OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
[22:23:56.335] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:G+a2WH4zXfz0zCf/GppnDqjxGT4Tg515pTlMHghOJfs
[22:23:56.510] Got askpass request: {"request":"The authenticity of host 'XXX.199.6.77 (XXX.199.6.77)' can't be established."}
[22:23:56.511] Detected first line fingerprint confirmation message
[22:23:56.511] Showing fingerprint confirmation dialog
[22:23:56.512] Listening for interwindow password on \\.\pipe\vscode-ssh-askpass-e632a275b0fe115182dd42b6e07c14d184ccedd9-sock
[22:23:56.512] Writing password prompt to globalState
[22:24:16.220] Fingerprint dialog canceled
[22:24:16.220] Interactor signaled cancel
[22:24:16.221] Cleaning up other-window auth server
[22:24:16.251] stderr> Host key verification failed.
[22:24:16.266] > local-server> ssh child died, shutting down
[22:24:16.272] Local server exit: 0
[22:24:16.273] Received install output: OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:G+a2WH4zXfz0zCf/GppnDqjxGT4Tg515pTlMHghOJfs
Host key verification failed.

[22:24:16.273] Stopped parsing output early. Remaining text: OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019debug1: Server host key: ecdsa-sha2-nistp256 SHA256:G+a2WH4zXfz0zCf/GppnDqjxGT4Tg515pTlMHghOJfsHost key verification failed.
[22:24:16.274] Failed to parse remote port from server output
[22:24:16.274] Resolver error: 
[22:24:16.278] ------
```
I change git to openssh, no use. 
I downgrade from 0.50 to 0.49, i can connect sever 1 but the names of recently opened files are changed.
So I think maybe it can be solved by cleaning the cache about fingerprint and recent-open-flies.
However, how to do? I didn't find.

**Comment by roblourens** [comment]
`Fingerprint dialog canceled`

Did you see a popup asking to accept the host's ssh key fingerprint?

**Comment by zhaoxf4** [comment]
> 
> 
> `Fingerprint dialog canceled`
> 
> Did you see a popup asking to accept the host's ssh key fingerprint?

Yes, I see it. But i couldn't connect whether i select continue or cancel.

**Comment by roblourens** [comment]
Oh, so you saw it and selected "continue" and this happens? Weird...

You should be able to work around it at least by connecting to that host in a normal terminal and accepting the host key there.

**Comment by zhaoxf4** [comment]
> 
> 
> Oh, so you saw it and selected "continue" and this happens? Weird...
> 
> You should be able to work around it at least by connecting to that host in a normal terminal and accepting the host key there.

emmm, I can connect it in cmd by cmd.

**Comment by hassanmunirr** [comment]
I have been stuck with the same problem for 8 hours.

**Comment by hassanmunirr** [comment]
> I also had same issue in 0.50.1.
> I have four servers, server 2~4 is ok but sever 1 couldn't be connected(maybe administrator restore sth).
> 
> ```
> [22:23:55.838] Log Level: 2
> [22:23:55.843] remote-ssh@0.50.1
> [22:23:55.843] win32 x64
> [22:23:55.845] SSH Resolver called for "ssh-remote+server_1", attempt 1
> [22:23:55.846] SSH Resolver called for host: server_1
> [22:23:55.846] Setting up SSH remote "server_1"
> [22:23:55.850] Acquiring local install lock: C:\Users\zhaoxf4\AppData\Local\Temp\vscode-remote-ssh-server_1-install.lock
> [22:23:55.863] Looking for existing server data file at c:\Users\zhaoxf4\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-server_1-0ba0ca52957102ca3527cf479571617f0de6ed50-0.50.1\data.json
> [22:23:55.864] Using commit id "0ba0ca52957102ca3527cf479571617f0de6ed50" and quality "stable" for server
> [22:23:55.865] Install and start server if needed
> [22:23:55.870] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
> [22:23:55.910] > OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
> [22:23:55.914] Using SSH config file "C:\Users\zhaoxf4\.ssh\config"
> [22:23:55.914] askpass server listening on \\.\pipe\vscode-ssh-askpass-451d7fbd4363df87f2784660fa5467163f3d67b4-sock
> [22:23:55.915] Spawning local server with {"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-f295d53425a8db9e73622075ef27c73230729286-sock","sshCommand":"C:\\Program Files\\Git\\usr\\bin\\ssh.exe","sshArgs":["-v","-T","-D","3031","-F","C:\\Users\\zhaoxf4\\.ssh\\config","server_1"],"dataFilePath":"c:\\Users\\zhaoxf4\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-server_1-0ba0ca52957102ca3527cf479571617f0de6ed50-0.50.1\\data.json"}
> [22:23:55.915] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\zhaoxf4\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.50.1\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Users\\zhaoxf4\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\zhaoxf4\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.50.1\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-451d7fbd4363df87f2784660fa5467163f3d67b4-sock"}
> [22:23:55.973] Spawned 11388
> [22:23:56.052] > local-server> Spawned ssh: 13376
> [22:23:56.072] stderr> OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
> [22:23:56.335] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:G+a2WH4zXfz0zCf/GppnDqjxGT4Tg515pTlMHghOJfs
> [22:23:56.510] Got askpass request: {"request":"The authenticity of host 'XXX.199.6.77 (XXX.199.6.77)' can't be established."}
> [22:23:56.511] Detected first line fingerprint confirmation message
> [22:23:56.511] Showing fingerprint confirmation dialog
> [22:23:56.512] Listening for interwindow password on \\.\pipe\vscode-ssh-askpass-e632a275b0fe115182dd42b6e07c14d184ccedd9-sock
> [22:23:56.512] Writing password prompt to globalState
> [22:24:16.220] Fingerprint dialog canceled
> [22:24:16.220] Interactor signaled cancel
> [22:24:16.221] Cleaning up other-window auth server
> [22:24:16.251] stderr> Host key verification failed.
> [22:24:16.266] > local-server> ssh child died, shutting down
> [22:24:16.272] Local server exit: 0
> [22:24:16.273] Received install output: OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:G+a2WH4zXfz0zCf/GppnDqjxGT4Tg515pTlMHghOJfs
> Host key verification failed.
> 
> [22:24:16.273] Stopped parsing output early. Remaining text: OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019debug1: Server host key: ecdsa-sha2-nistp256 SHA256:G+a2WH4zXfz0zCf/GppnDqjxGT4Tg515pTlMHghOJfsHost key verification failed.
> [22:24:16.274] Failed to parse remote port from server output
> [22:24:16.274] Resolver error: 
> [22:24:16.278] ------
> ```
> 
> I change git to openssh, no use.
> I downgrade from 0.50 to 0.49, i can connect sever 1 but the names of recently opened files are changed.
> So I think maybe it can be solved by cleaning the cache about fingerprint and recent-open-flies.
> However, how to do? I didn't find.

Here is how I fixed it.

Remove the .vscode-server/ folder on your host machine and try again. Apparently, the conflicting key was in this folder on my Ubuntu machine

1. go to /home/user/.vscode-server/ on your host machine 
2. rm -r .vscode-server

Hope it works for you too.

**Comment by zhaoxf4** [comment]
> **Here is how I fixed it.**
> 
> Remove the .vscode-server/ folder on your host machine and try again. Apparently, the conflicting key was in this folder on my Ubuntu machine
> 
> **1. cd /home/user/.vscode-server/ on your host machine 2. ls -a 3. rm -r .vscode-server**
> 
> Hope it works for you too.

Thanks，i try it but don't match me. I think there some problems in my client host.

**Comment by hassanmunirr** [comment]
> > **Here is how I fixed it.**
> > Remove the .vscode-server/ folder on your host machine and try again. Apparently, the conflicting key was in this folder on my Ubuntu machine
> > **1. cd /home/user/.vscode-server/ on your host machine 2. ls -a 3. rm -r .vscode-server**
> > Hope it works for you too.
> 
> Thanks，i try it but don't match me. I think there some problems in my client host.

Have you tried removing known_host file on your client as well? I re-install VS code and removed all .SSH settings on the client as well.

**Comment by zhaoxf4** [comment]
> Have you tried removing known_host file on your client as well? I re-install VS code and removed all .SSH settings on the client as well. The log file you showed here looks exactly the same as mine
Yes I try removing known_host on client and reboot.
I could't connect and I think remove fingerprint can solve it.
However, I didn't find it.
This figure will tell you what happened.
![](https://raw.githubusercontent.com/zhaoxf4/picbed/master/2020/2020-03-26-18-35-16-KsgQi37hvXsgLTFP.png)

**Comment by hassanmunirr** [comment]
> > Have you tried removing known_host file on your client as well? I re-install VS code and removed all .SSH settings on the client as well. The log file you showed here looks exactly the same as mine
> 
> Yes I try removing known_host on client and reboot.
> I could't connect and I think remove fingerprint can solve it.
> However, I didn't find it.
> This figure will tell you what happened.
> ![](https://raw.githubusercontent.com/zhaoxf4/picbed/master/2020/2020-03-26-18-35-16-KsgQi37hvXsgLTFP.png)

I found this fingerprint on my host machine. I believe you have to search for the location of
.vscode-server on your host machine.

What I did was to connect to my remote machine using putty and windows power shell to double-check if the problem is at host end or local. Both Putty and Power both connected to the host without any problems. 

After I logged into to host with putty I used the command **$ Locate .vscode-server**
to locate where does **VScode** stores fingerprint information. I suppose deleting this .vscode-server containing this fingerprint might solve the problem. Not sure where else can I point you to.

**Comment by zhaoxf4** [comment]
> I found this fingerprint on my host machine. I believe you have to search for the location of
> .vscode-server on your host machine.
> 
> What I did was to connect to my remote machine using putty and windows power shell to double-check if the problem is at host end or local. Both Putty and PowerShell connected to the host without any problems.
> 
> After I logged into to host with putty I used the command **$ Locate .vscode-server**
> to locate where does **VScode** stores fingerprint information. I suppose deleting this .vscode-server containing this fingerprint might solve the problem. Not sure where else can I point you to.

Maybe I need root to updatedb.... I can locate .vscode-server but I couldn't see it......
```
~$ locate .vscode-server
/data0/zhaoxf4/.vscode-server

~$ rm /data0/zhaoxf4/.vscode-server
rm: cannot remove '/data0/zhaoxf4/.vscode-server': No such file or directory

```
Thanks for you. I can use version 0.49 now.

**Comment by zhaoxf4** [comment]
Today I upgrade version 0.51.0, I remove the document .vscode-server/ in my server. It didn't work well.
So I uninstall vscode and remove "C:\Users\xxx\.vscode" and "C:\Users\xxx\AppData\Roaming\Code" in my client. 
Then I install vscode and install remote-ssh version 0.51.0.
And remove .vscode-server/ again. 
Finally, it works ok, then I need to restore other extensions.

**Comment by hassanmunirr** [comment]
> Today I upgrade version 0.51.0, I remove the document .vscode-server/ in my server. It didn't work well.
> So I uninstall vscode and remove "C:\Users\xxx.vscode" and "C:\Users\xxx\AppData\Roaming\Code" in my client.
> Then I install vscode and install remote-ssh version 0.51.0.
> And remove .vscode-server/ again.
> Finally, it works ok, then I need to restore other extensions.
Awesome!

**Comment by roblourens** [comment]
If anyone is having an issue with 0.51, please open a new issue. @sakizhu please let me know if your issue persists with 0.51

**Comment by sakizhu** [comment]
> If anyone is having an issue with 0.51, please open a new issue. @sakizhu please let me know if your issue persists with 0.51

I found the reason is the remote machine didn't set the sshd configure optio “AllowTcpForwarding yes” in /etc/ssh/sshd_config.l and /etc/ssh/sshd_config
