### ISSUE TITLE
Unable to install extensions in VS Code

### ISSUE THREAD

**Issue by mihir-shah99** [microsoft/vscode-remote-release#2616]
I am unable to install extension in VS Code remote WSL Window. It shows "permission denied". Now, I tried "remote.WSL.fileWatcher.polling": true and I also increased The Polling Interval to 10000. Still the issue persists. I am using WSL1.

**Comment by bamurtaugh** [comment]
Hey @mihir-shah99, are you still experiencing this? If so, could you try [upgrading to WSL 2](https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace-in-wsl-1)?

**Comment by mihir-shah99** [comment]
Hey, nope I'm not facing this issue now, forgot to close this 😅
