### ISSUE TITLE
sudo commands

### ISSUE THREAD

**Issue by 999-Victor** [microsoft/vscode-remote-release#2617]
I use Remote-SSH and connect to a server as sudo user (not root).

As #1035 I can't save some files. In devtools console are only access error and the notice

```
[Extension Host]
No editors associated with document: \etc\nginx\conf.d\80.conf
```

Also I can't open some folders (with no error, it's just like empty), I can't rename some folders, delete them etc. (access error), but I can do that all in console with `sudo` command. I may edit and save files in a console editor with sudo, like `sudo vi /file`, and I can use `sudo mc`, for example, but I want to use VSCode only.  

I can't connect as root because there is `PermitRootLogin no` option in ssh config and I need to create files with another sudo user.

Make it possible to connect as sudo if it will help
```
Open On SSH Host in Current Window
Open On SSH Host in New Window
> Open On SSH Host in Current Window as sudo
> Open On SSH Host in New Window as sudo
Remove From Recent List
``` 
or add "Retry as sudo" buttons and sudo commands in the explorer, please.

**Comment by 999-Victor** [comment]
@roblourens hey! please let me know if I make language mistakes and you just can't understant this issue currently.

**Comment by roblourens** [comment]
I believe this is https://github.com/microsoft/vscode-remote-release/issues/690
