### ISSUE TITLE
SSH connection keeps asking to enter password repeatedly.

### ISSUE THREAD

**Issue by khubishah** [microsoft/vscode-remote-release#2618]
Issue Type: <b>Bug</b>

It never used to happen before but not it just won't stop asking for the password.
1. SSH Remote - enter ssh connection ssh username@... 
2. It will prompt you for the password.
3. Step 2 will keep repeating AGAIN and AGAIN and AGAIN. 

Extension version: 0.50.1
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bluenote10** [comment]
Related to: https://github.com/microsoft/vscode-remote-release/issues/2518

I have a similar issue, but it is not an infinite loop like in the linked issue. I have to enter the password 5 to 15 times then it works.

**Comment by roblourens** [comment]
Most likely #2518 if you see `ln: failed to create hard link` in the log
