### ISSUE TITLE
Remote System Explorer

### ISSUE THREAD

**Issue by tiptronic85** [microsoft/vscode-remote-release#2622]
I developed for so many years with Eclipse, Europa first and all the other versions then, and it has the extension "Remote System Explorer".
This extension is perfect for whose work with remote vps or remote machines because you can add a lot of connections and you can see it in tree mode.

My feature request is to take ispiration from this plugins to make vscode perfect fitted to me and i think for so many others people.

This is the [link of the extension](https://marketplace.eclipse.org/content/remote-system-explorer-ssh-telnet-ftp-and-dstore-protocols#group-details).
[This is the link to the screenshot](https://marketplace.eclipse.org/sites/default/files/styles/ds_solution_screenshot/public/RSESample_small.gif?itok=qLGioI4D).

Thank you in advance.

**Comment by roblourens** [comment]
Our remote extensions give you the Remote Explorer viewlet. It's not clear whether this is what you are looking for or not

**Comment by tiptronic85** [comment]
> Our remote extensions give you the Remote Explorer viewlet. It's not clear whether this is what you are looking for or not

Yes of course, for one project.
Did you see the screenshot i linked?

With Remote System Explorer it's multi-project, you can set all your projects and open files from one project and another one in the same time.

This is awesome.

In vscode you can open only one project a time, but if you work in a helpdesk you follow more customers and when you are waiting an answer from one, you open another customer's code.

I hope you understand the need.
Thank you
