### ISSUE TITLE
Remote-SSH fails to connect to remote Windows machine when OpenSSH default shell is not cmd.exe

### ISSUE THREAD

**Issue by jamespottsSAFC** [microsoft/vscode-remote-release#2625]
- VSCode Version: 1.43.2
- Local OS Version: Windows 10
- Remote OS Version: Windows Server 2012 R2
- Remote Extension/Connection Type: SSH

I have the default shell for my OpenSSH set to git bash, however this breaks my VSCode Remote. It only works when I set the default shell to cmd.

Remote ssh version: OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
Local ssh version: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

This is the output from VSCode:

[vscoderemotelog.txt](https://github.com/microsoft/vscode-remote-release/files/4396206/vscoderemotelog.txt)

I have the following settings enabled for the extension:

Use Local Server: false
Remote Platform: windows

**Comment by roblourens** [comment]
Did this work before?

**Comment by jamespottsSAFC** [comment]
No it has been like this since I installed VS code remote

**Comment by roblourens** [comment]
Lots has happened here, should work now
