### ISSUE TITLE
"StrictHostKeyChecking no" setting ignored

### ISSUE THREAD

**Issue by ltalirz** [microsoft/vscode-remote-release#2626]
- VSCode Version: 1.43.2
- Local OS Version:  1.43.2
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

### Steps to Reproduce:

1. Set up remote host in your `.ssh/config` file. E.g.
```
Host remote
  Hostname 1.2.3.4
  User abc
```
2. Connect to host via ssh, so that a line for the host is added to the `.ssh/known_hosts` file
3. Rebuild the remote server (or do any other action that causes its public ssh *server* key to change)
4. When connecting to your host, you now get a message like this:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that the RSA host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx.
Please contact your system administrator.
Add correct host key in /home/localuser/.ssh/known_hosts to get rid of this message.
Offending key in /home/localuser/.ssh/known_hosts:12
RSA host key for 1.2.3.4 has changed and you have requested strict checking.
Host key verification failed.
```
5. Add line `StrictHostKeyChecking no` to the host configuration in your `.ssh/config`. You can now ssh into the remote server again (with warnings)
6. Try connecting to the remote server via VSCode remote ssh plugin. This fails, and you will get a connection timeout.

![Screenshot 2020-03-28 at 00 11 38](https://user-images.githubusercontent.com/1053245/77807630-be5f4800-7088-11ea-9bfc-4c78f7f585b8.png)

### Expected result:

Connecting via VSCode remote ssh plugin should either just work, or , alternatively, the error message should provide a clearer hint of why it didn't work.

### Workaround:

Simply remove the offending line from your `.ssh/known_hosts` file and you'll be able to connect via VSCode again.

**Comment by ltalirz** [comment]
I guess a relevant bit of information is in [this PR](https://github.com/microsoft/vscode-docs/pull/2860/files#diff-81339f0f570869f9b4158139006cccdbR137) but somehow I can't find this in the [current docs](https://code.visualstudio.com/docs/remote/troubleshooting)

**Comment by roblourens** [comment]
Could you share the log from the Remote-SSH output channel when this happens? It should work. or it might work if you disable `remote.SSH.useLocalServer`
