### ISSUE TITLE
[Request] Make themes purely client-side by default

### ISSUE THREAD

**Issue by bryanburke** [microsoft/vscode-remote-release#2628]
Currently, the workbench theme seems to be server-side. For example, if I install and use a theme from an extension locally but do not install that same theme on the server (for example, in a Dev Container), VS Code applies the default dark theme when I connect to the remote environment.

While the ability to delegate theming to the server might be useful in certain circumstances, I believe letting the client fully control theming by default makes more sense in the vast majority of use cases. Therefore, I would like to request that VS Code Remote by default respect all theme-related settings, including editor and workbench color customizations, that the client defines.

**Comment by roblourens** [comment]
Theme extensions should be installed locally and themes can be set by settings in the local user settings, or workspace settings, or remote user settings.

It's possible that the `workbench.colorTheme` setting is set in your dev container workspace settings, does that explain it?

**Comment by bryanburke** [comment]
Hmm... I think my issue was caused by the particular theme extension I was using: [Base16 Theme Generator](https://marketplace.visualstudio.com/items?itemName=golf1052.base16-generator&ssr=false)

Apparently, that extension generates the selected theme "on the fly," whatever that means.

I can confirm that other theme extensions, when applied locally, work as expected with VS Code Remote, and do not cause the switch back to the default dark theme I described.

**Comment by roblourens** [comment]
Cool, please file an issue on that extension's repo if needed.
