### ISSUE TITLE
Connection to remote SSH not working, python extension not loading

### ISSUE THREAD

**Issue by prasiyer** [microsoft/vscode-remote-release#2629]
What: Connection to remote SSH vscode server not working, python extension also not loading

![image](https://user-images.githubusercontent.com/57724404/77354423-d04f8c80-6d10-11ea-8487-6771ef00d06c.png)
version: 1.43.1

Error message in console: 
(node:7728) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

I see similar issues that have been reported. But i am not able to see the fix.

Please let me know if you additional information.

**Comment by roblourens** [comment]
@prasiyer so it's working now? If you see it again please include the log from the Remote-SSH output channel.
