### ISSUE TITLE
[Remote-SSH] Open remote file in ssh session

### ISSUE THREAD

**Issue by cloudhan** [microsoft/vscode-remote-release#263]
I'd like to request a feature, just for convenience.

Say, I have a vscode that is "Editing on SSH:remote"
And I have another terminal ssh to remote.

Is it possible to do
```
cloudhan@remote $ code /remote/file/to/be/open/locally
```
and then magically (programmatically) the file open in the vscode session?

**Comment by egamma** [comment]
From the integrated terminal in VS Code you can execute `code-insiders file`, does this cover your needs?

**Comment by cloudhan** [comment]
Perfect, I didn't even know that. It should be sufficient for now.

But still would be better if this feature can be used in other terminal.
