### ISSUE TITLE
[Request] Allow external build args file

### ISSUE THREAD

**Issue by myermian** [microsoft/vscode-remote-release#2630]
**Current:**
When a new team member starts at our company, they set up their development environment the first day. Most of the environment comes preloaded, but we utilize a special command line tool which requires a unique code per user as part of the licensing. This isn't a problem though, the user downloads and installs the CLI tool, and during the installation of the tool enters their unique key. Yes, we could always just share a key, but that would violate the licensing agreement and our company does not want to do that.

**Remote Containers:**
We are trying to move to remote development containers. When I tested this out, everything worked perfectly fine as the command line tool is also available in linux. When I installed it using my unique key, the tool performed appropriately, and just to test it I installed it with an invalid key and it produced an error.

I cannot use my own key in the Dockerfile, so I utilized `ARG` in the Dockerfile. Now, I have to somehow pass in the `ARG`, but I cannot put my unique key in the devcontainer.json file and check that into source control, so instead I leave the argument value empty in the devcontainer.json file. This works, but is very annoying because team members must modify the devcontainer.json file and it is making a mess with our check ins. Did someone accidentally check in their own modified devcontainer.json file ... well, we can't have that in git history, so we have to fix our git history.

**Potential solution:**
We could allow for an external ARGS file. This would allow us to have team members create something like ".devcontainer/devcontainer.local.args" and use gitignore to ensure a "local" file does not get checked in.

**Comment by chrmarti** [comment]
You could use build args support with local variable substitution:
```json
{
	"build": {
		"dockerfile": "Dockerfile",
		"args": {
			"LICENSE_KEY": "${env:LICENSE_KEY}"
		}
	}
}
```

Does that work for your case?
