### ISSUE TITLE
Opening symlinked files via the CLI will open a broken window

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-remote-release#264]
Repro:

1. Open terminal in an SSH window
2. Run `code-insiders ~/.bashrc`

![image](https://user-images.githubusercontent.com/2193314/57488195-4406b900-7267-11e9-8719-d704bdb97828.png)

Using `-r` is even worse as it reloads and bricks the current window

**Comment by aeschli** [comment]
Tried with today's build and `code-insiders ~/.bashrc` seems to work in a SSH window. Please reopen if you still see issues.

**Comment by Tyriar** [comment]
This still happens.

**Comment by Tyriar** [comment]
Problem seems specific to dot files?

**Comment by Tyriar** [comment]
The problem I've been seeing is specific to symlinked files.

**Comment by Tyriar** [comment]
To verify make sure symlinked files and folders act as expected.
