### ISSUE TITLE
Proxy connection timed out. Is the remote port correct

### ISSUE THREAD

**Issue by oumingyang** [microsoft/vscode-remote-release#2640]
Issue Type: <b>Bug</b>

when I remote connect my ubuntu18.04LST  server, it report Proxy connection timed out. Is the remote port correct. Before that i just installed a nfs server on the server.  I have tried connected to a Centos7 server, it seems work well.

Extension version: 0.51.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17134
Fetching remote diagnostics for 'ssh-remote+master_i5_16g' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (6.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'ssh-remote+master_i5_16g' timed out.
</details>

**Comment by roblourens** [comment]
Can you give some more details about your setup? It sounds like we are having issues with your proxy?
