### ISSUE TITLE
Test: Progress report in Remote-Containers

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2644]
Refs: #2499 #2498 #2481

- [x] macOS @rebornix
- [x] windows @connor4312

Complexity: 4

---

Got through the 4 test scenarios at https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#testing-remote-containers and check the progress notification makes sense.

Also watch out for any problems introduced by some of the larger refactorings during this milestone.

**Comment by connor4312** [comment]
Seems to all work pretty well
