### ISSUE TITLE
Test: User supplied project name

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2645]
Refs: #222

- [x] anyOS @rebornix
- [x] anyOS @JacksonKearl

Complexity: 3

---

- Run the Docker Compose setup: https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#docker-compose
- Note that `docker ps -a` shows the containers having names derived from the project folder name.
- Change the project name and reopen the folder in a container:
  1. By setting the COMPOSE_PROJECT_NAME environment variable and starting Code from the terminal.
  2. By setting the COMPOSE_PROJECT_NAME environment variable in a `.env` file in the project folder.
- Check with `docker ps` that the containers are named accordingly.
- Note that the environment variable should win over the value in `.env` if both are given.

**Comment by JacksonKearl** [comment]
For me, the `.env` had to be in the parent directory of the `docker-compose.yml`. Is that expected?

**Comment by chrmarti** [comment]
@JacksonKearl Not sure, which OS and docker-compose version are you on?

**Comment by JacksonKearl** [comment]
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

macOS 10.14.6

**Comment by chrmarti** [comment]
@JacksonKearl You're right, the `.env` should be in the project folder (the working directory for the `docker-compose` command). Thanks for pointing this out.

**Comment by rebornix** [comment]
It works as described.
