### ISSUE TITLE
Test: Attach to Kubernetes container

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2647]
Refs: #2497

- [ ] anyOS @egamma 
- [x] anyOS @sbatten

Complexity: 3

---

- Enable Kubernetes in Docker Desktop for Mac or Windows.
- Make sure you have `kubectl` (the Kubernetes CLI) installed.
- Install the Remote-Containers and Kubernetes extensions: https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools
- Create some simple sample container in Kubernetes (search for simple examples, so we get better coverage or ping me if that dead-ends).
- Attach to the Kubernetes container from the Kubernetes explorer view's context menu on its pod (that can contain multiple containers).
- Check things are working (e.g., Git credentials are forwarded from the host into the container).

**Comment by sbatten** [comment]
This was quite a pain on windows due to https://github.com/docker/for-win/issues/1962, but once it set up, everything worked.

**Comment by chrmarti** [comment]
@sbatten Sorry about that, I thought using Docker Desktop would be the easiest way to get at a Kubernetes install. Another option would be to install minikube (https://kubernetes.io/docs/tasks/tools/install-minikube/).

**Comment by egamma** [comment]
It was straightforward on OS X and things worked fine.
