### ISSUE TITLE
Cannot open a pull request without a devcontainer.json file

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#2654]
Testing https://github.com/microsoft/vscode-remote-release/issues/2638

1. Have a pull request in a private, non-microsoft, repo where there is no devcontainer.json.
2. Open Repository in Container and paste in pull request url (mine was `https://github.com/alexr00/playground/pull/38`)
3. Choose a new unique volume
4. Get a prompt to add a devcontainer.json file, selecte node 10
5. Almost immediately after that I get 
![image](https://user-images.githubusercontent.com/38270282/78011446-e0d0ba00-7343-11ea-8884-5f18ce834da4.png)
reloading results in the same.

**Comment by alexr00** [comment]
Issue occurs even with public repos and from all entry-points (also tried from PR view context menu).

**Comment by egamma** [comment]
Caused by mixing local Win paths with posix paths... fixed.
