### ISSUE TITLE
Recent entry for container PRs could use polish

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#2655]
Testing https://github.com/microsoft/vscode-remote-release/issues/2638

![image](https://user-images.githubusercontent.com/38270282/78012644-918b8900-7345-11ea-84ad-f50859fda156.png)

Seeing `__UNIQUE__` in the recent list feels a bit out of place and it looks like an implementation detail that has escaped into the UI. Perhaps the volume could simple be called `unique volume`?

**Comment by egamma** [comment]
duplicate of  #2653
