### ISSUE TITLE
Repository Container: Improve message when PR/branch does not exist

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2657]
Issue Type: <b>Bug</b>

#2638 

Also: The volume for the branch stays behind. Maybe a check could be done upfront.

Branch:

![image](https://user-images.githubusercontent.com/9205389/78015111-33f93b80-7349-11ea-9950-cba0e7cc96c6.png)

PR:

![image](https://user-images.githubusercontent.com/9205389/78015326-8e929780-7349-11ea-94f9-2f8b29eb0d11.png)

Extension version: 0.109.0
VS Code version: Code - Insiders 1.44.0-insider (d7d1147d6b764a48b789000c03088ee9afabcd8a, 2020-03-31T08:22:34.682Z)
OS version: Darwin x64 19.2.0
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.44GB free)|
|Process Argv|-psn_0_3851180|
|Screen Reader|no|
|VM|22%|

|Item|Value|
|---|---|
|Remote|Container vscode-remote-containers_devc…|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|7.78GB (0.29GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment]
Now doing an upfront check and show a nicer modal dialog when the URL is a repository. 
![image](https://user-images.githubusercontent.com/172399/112273488-b2976900-8c7d-11eb-92d7-cba82eeb8c94.png)

Also changed the notification for a non existing PR to a modal dialog.

**Comment by egamma** [comment]
Verification requires a remote container extension version > 0.165
