### ISSUE TITLE
Name of Remote-Containers: Add Container Configuration File... command misleading?

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#266]
This is a forked topic off of https://github.com/microsoft/vscode-dev-containers/issues/31. (The issue wasn't moved since there's still a valid dev container definition discussion there.)

The **Remote-Containers: Add Container Configuration File...** command acts similar to **Open Folder in Container...** or **Reopen Folder in Container** if no `devcontainer.json` is present. The difference is that it doesn't open the folder in the container after its done.

Specifically this command allows you to quickly add a `devcontainer.json` file and, if you pick a dev container definition, other files to your project that you can customize before using.

Specifically it will:
1. Detect if you have Dockerfile or Docker Compose file and offer to generate a `devcontainer.json` to reuse them if so
2. Regardless, it provides a list of pre-defined Dev Container Definitions originating from the open source https://github.com/Microsoft/vscode-dev-containers repo that you can pick from if you so choose.
3. Once you pick an option, the required files are added to the current folder.

The discussion on https://github.com/microsoft/vscode-dev-containers/issues/31 is that this command's name may not be properly conveying its intent.

A few potential alternate names for the command include:

1. Add Dev Container Definition to Folder... 
2. Add Dev Container Files to Folder... 
3. Create Dev Container Files...
4. Add devcontainer.json to Folder... 
5. Create devcontainer.json File... 

Others?

//cc: @chrmarti @misolori @brunoborges

**Comment by chrmarti** [comment]
Is it misleading because:
- It suggests there will be only 1 additional file.
- It says 'Container' which is more general than dev container.

I'd then add `Add Dev Container Configuration...` to the race.

**Comment by egamma** [comment]
I'd expand on the proposal from @chrmarti:

`Add Dev Container Configuration Files...` 

The Docker extension uses `Add Docker Files to Workspace`, I don't think the suffix '...to Workspace' is needed, but it would be more accurate than the proposed '...to Folder'.

We should then also align the quick pick title to the command name

![image](https://user-images.githubusercontent.com/172399/57508975-4e769080-7303-11e9-9de8-33c4738ad5d1.png)

**Comment by brunoborges** [comment]
👍
