### ISSUE TITLE
Remote explorer empty container list

### ISSUE THREAD

**Issue by bhack** [microsoft/vscode-remote-release#2660]
- VSCode Version: insiders
- Local OS Version: linux
- Remote OS Version: linux
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1.When I click the remote explorer the container list is empty and i got: `The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined`

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by egamma** [comment]
Can you provide more information about the state you where in when this happened:
- did you have any remote containers?
- if yes, was there anything special about the remote containers you had?
- can you share a screenshot of the containers shown in the Docker extension?

**Comment by bhack** [comment]
Yes the container is open and I'am working in the container in Vscode (editor/terminal).
I've used a classic python3 container already available in the list. But this happen also with other containers..

![immagine](https://user-images.githubusercontent.com/1710528/78029218-81cd6e00-7360-11ea-873e-a6875fdcece0.png)

**Comment by egamma** [comment]
Is there an exception in the developer's tool console.
Help>Toggle Developer Tools>Console

**Comment by bhack** [comment]
Yes I've already posted in the description. The extended version is:
```
notificationsAlerts.ts:38 TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
	at Function.from (buffer.js:219)
	at Object.t.getParseDevContainerAuthority (/home/user/.vscode-in…dist/extension.js:1)
	at I.trySetEntry (/home/user/.vscode-in…dist/extension.js:1)
	at I.setRecentEntries (/home/user/.vscode-in…dist/extension.js:1)
	at async I.setContainerTypes (/home/user/.vscode-in…dist/extension.js:1)
	at async I.getChildGroups (/home/user/.vscode-in…dist/extension.js:1)

**Comment by alexr00** [comment]
@chrmarti have there been any changes to how the authority of container URIs are structured?

**Comment by chrmarti** [comment]
Can reproduce after running `code --folder-uri=vscode-remote://dev-container/foobar`. We can protect against that case.
