### ISSUE TITLE
'Empty view' actions shown in Remote Explorer under some containers

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2661]
(After working around #2658 with a try-catch that could, but seems unlikely to, affect this.)

![image](https://user-images.githubusercontent.com/9205389/78022140-bdfad180-7354-11ea-901e-5ce9456d8904.png)

/cc @egamma in case these are related.

**Comment by alexr00** [comment]
It looks like this could have happened if listing containers failed or if all containers disappeared while the tree is refreshing. I added an extra check to prevent this.
