### ISSUE TITLE
Problems connecting to a remote Ubuntu 18.04 using Remote-SSH extension

### ISSUE THREAD

**Issue by bradunov** [microsoft/vscode-remote-release#2662]
- VSCode Version: 1.43.2
- Remote-ssh Version: 0.51.0
- Local OS Version: Windows 10 1909 (build 18363.720)
- Local SSH version: OpenSSH.Client~~~~0.0.1.0
- Remote OS Version: Ubuntu 18.04.2 LTS
- Remote Extension/Connection Type: SSH

I have a stock Ubuntu 18.04 install with Open-SSH server. I am trying to connect to it from my Windows desktop using VSCode (1.43.2) and Remote-SSH (0.51.0).

I followed [this](https://code.visualstudio.com/docs/remote/troubleshooting#_installing-a-supported-ssh-client) process to install OpenSSH client on Windows. I've set up a key and verified that I can connect from a powershell command line to the Ubuntu. 

However, when I try to connect from VSCode (Remote-SSH: Connect to host), I get the following error: 

    [12:21:20.006] Log Level: 2
    [12:21:20.020] remote-ssh@0.51.0
    [12:21:20.021] win32 x64
    [12:21:20.023] SSH Resolver called for "ssh-remote+XX.XX.XX.XX", attempt 1
    [12:21:20.023] SSH Resolver called for host: XX.XX.XX.XX
    [12:21:20.023] Setting up SSH remote "XX.XX.XX.XX"
    [12:21:20.058] Using commit id "0ba0ca52957102ca3527cf479571617f0de6ed50" and quality "stable" for server
    [12:21:20.059] Install and start server if needed
    [12:21:21.689] getPlatformForHost was canceled
    [12:21:21.690] Resolver error: Connecting was canceled
    [12:21:21.697] ------

I tried adding `"remote.SSH.useLocalServer": false` to settings.json, but the behavior is exactly the same. 

Oddly enough, if I add the following line
`"remote.SSH.windowsRemotes": ["XX.XX.XX.XX"]`
to my settings.json, then it connects, but breaks because (I guess) it wrongly assumes the other side is Windows. 

Any suggestions?

**Comment by roblourens** [comment]
Same as https://github.com/microsoft/vscode-remote-release/issues/2636 hmm...

Do you get a popup asking for the platform of the remote? It is saying that the popup was canceled.

Workaround, set:

```json
"remote.SSH.remotePlatform": {
  "remotehostname": "linux"
}
```

**Comment by bradunov** [comment]
@roblourens : I get it now. There was a popup at the top of the window, not very visible. But there was also a link at bottom on the window saying "click for more detail". I clicked on it without noticing the popup. But that closed the popup and reported an error. After your explanation, I looked more carefully, noticed the popup, selected Linux, and everything ran smoothly.

**Comment by roblourens** [comment]
Hm, I will think about how to make it more noticeable, thanks
