### ISSUE TITLE
Label `6 in ...` missing some context

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2663]
Issue Type: <b>Bug</b>

#2638 

Would `PR 6 in ...` be easier to understand?

![image](https://user-images.githubusercontent.com/9205389/78024009-f223c180-7357-11ea-9422-86c136f9dae5.png)

Extension version: 0.109.0
VS Code version: Code - Insiders 1.44.0-insider (d7d1147d6b764a48b789000c03088ee9afabcd8a, 2020-03-31T08:22:34.682Z)
OS version: Darwin x64 19.2.0
Remote OS version: Linux x64 4.19.76-linuxkit
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.15GB free)|
|Process Argv|-psn_0_3851180|
|Screen Reader|no|
|VM|22%|

|Item|Value|
|---|---|
|Remote|Container vscode-remote-containers_devc…|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|7.78GB (0.25GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js Sample|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|7.78GB (0.25GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Similarly, the commit id could be shortened to (the customary) 7 characters:
![image](https://user-images.githubusercontent.com/9205389/78027468-b25fd880-735d-11ea-8007-103b42096348.png)

**Comment by egamma** [comment]
Now showing the repository name instead of just the PR number.

![image](https://user-images.githubusercontent.com/172399/78220538-097ebe00-74c2-11ea-96fa-f84f68be1230.png)
