### ISSUE TITLE
build.args doesn't seem to pass arguments at build time to remote container

### ISSUE THREAD

**Issue by msalvaris** [microsoft/vscode-remote-release#2669]
- VSCode Version: 1.43.1 (user setup)
- Local OS Version: Windows_NT x64 10.0.18363
- Remote OS Version: Ubuntu 16.04
- Remote Extension/Connection Type: Docker

Tried both 0.19 and 0.20 versions of remote development extension

Steps to Reproduce:

1. Set build.args to
	"build.args":{
		"DOCKER_GID": "129",
		"USER_ID": "1000"
	},
        In the docker image use those args
2. Build docker container on remote host

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Are there any examples using build.args? Just want to make sure that I am not making any errors

**Comment by Chuxel** [comment]
@msalvaris The syntax is a bit different.  Try the following:

```Dockerfile
"build": {
    "args":{
        "DOCKER_GID": "129",
       "USER_ID": "1000"
    }
}
```

**Comment by msalvaris** [comment]
I thought I had tried that variation but tried it again and it worked! Thanks @Chuxel !
