### ISSUE TITLE
User supplied project name wont apply if existing containers have an old name

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-remote-release#2670]
Ref #2645

Two directions:
1. Create containers with prefix `a` by setting in `.env` file
2. Close out connection, but don't remove containers.
3. Launch vscode from terminal with env var set to `b`.
4. Open in Contianer
5. 🐛 the old containers seem to be reused (`a` prefix).

Similarly:
1. Create containers with prefix `a` by setting in terminal
2. Close out connection, but don't remove containers.
3. Launch vscode from terminal with no env var set, but make a `.env` with prefix `b` set.
4. Open in Contianer
5. 🐛 the old containers seem to be reused (`a` prefix).

If I go into the container explorer and manually remove the shut down containers after closing the connection, the new env vars are respected.

**Comment by chrmarti** [comment]
Both cases work for me as expected. Did you maybe `export COMPOSE_PROJECT_NAME` in your terminal, so the value suck around or something? Anything I might miss?

**Comment by JacksonKearl** [comment]
Hm, I might have lost the terminal env var somewhere along the way. Cant reproduce anymore.
