### ISSUE TITLE
SSH: Unable to connect to windows host without forwarding

### ISSUE THREAD

**Issue by zdavidsen** [microsoft/vscode-remote-release#2672]
- VSCode Version: 1.43.2
- Remote  - SSH Version: 0.51.0
- Local OS Version: Windows 10 10.0.17134
- Remote OS Version: Windows 10 10.0.18362
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Disable agent forwarding
2. Disable dynamic forwarding
3. Attempt to connect (I'm using an ssh key, don't know if password authentication also fails)
4. Connection hangs at "Setting up SSH tunnel"

Debug output shows that the "ssh tunnel command completed unexpectedly" after attempting to execute what looks like a bash script in powershell.  Setting windows openssh default shell to powershell or cmd produces the same error, setting default shell to bash fails even sooner (while trying to parse a powershell command, go figure).

Enabling either agent forwarding or dynamic forwarding results in a successful connection, but fails to fetch remote environment, as well as `Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.)`

```
....
[17:05:28.840] Spawning tunnel with: ssh -T -L 127.0.0.1:60535:127.0.0.1:60071 192.168.56.101 powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -Command "powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -EncodedCommand $([Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('ZWNobyAtZSAnQ29ubmVjdGVkIHRvIFNTSCBIb3N0IC0gUGxlYXNlIGRvIG5vdCBjbG9zZSB0aGlzIHRlcm1pbmFsJyAmJiB3aGlsZSB0cnVlOyBkbyBzbGVlcCAxODA7IGVjaG8gLW4gJyAnOyBkb25l')))))"  # RemoteSSHConfigurationScript
[17:05:28.841] Terminal shell path: C:\windows\System32\cmd.exe
[17:05:28.943] > 
[17:05:29.853] > #< CLIXML
> 
[17:05:29.889] > <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
> <S S="Error">At line:1 char:69_x000D__x000A_</S><S S="Error">+ ... Connected to
> SSH Host - Please do not close this terminal' &amp;&amp; while t ..._x000D__x000
> A_</S><S S="Error">+
>     ~~_x000D__x000A_</S><S S="Error">The token '&amp;&amp;' is not a valid state
> ment separator in this version._x000D__x000A_</S><S S="Error">At line:1 char:86_
> x000D__x000A_</S><S S="Error">+ ... H Host - Please do not close this terminal'
> &amp;&amp; while true; do sleep 1 ..._x000D__x000A_</S><S S="Error">+
>                                                        ~_x000D__x000A_</S><S S="
> Error">Missing statement body in do loop._x000D__x000A_</S><S S="Error">    + Ca
> tegoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException_x0
> 00D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : InvalidEndOfLine_x000D
> __x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>
[17:05:30.163] "SSH Tunnel" terminal command done
[17:05:30.163] SSH tunnel command completed unexpectedly
```
(In case it saves any time, that powershell command evaluates to `echo -e 'Connected to SSH Host - Please do not close this terminal' && while true; do sleep 180; echo -n ' '; done`)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Didn't try

**Comment by roblourens** [comment]
> Disable dynamic forwarding

I should check this in code, but I consider this mode basically deprecated and it won't work with windows hosts. Is there a reason you can't use this?

**Comment by zdavidsen** [comment]
Nope, no reason that I can't use it. I was just mucking around in the
settings trying to get things to work and turned off forwarding because I
don't need/want it.

**Comment by roblourens** [comment]
Can you try connecting with the defaults and share the log if it doesn't work?

**Comment by zdavidsen** [comment]
I can (sort of) connect while using the defaults, but as I mentioned above it pops up two error messages, `Could not fetch remote environment` and `Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.)`
I don't remember seeing anything obvious in the logs when I did that, but here's the log if you want to look
[log.txt](https://github.com/microsoft/vscode-remote-release/files/4416504/log.txt)

**Comment by roblourens** [comment]
Oh, it's weird to get `Unauthorized client refused` on the first connection. You are using the official build of VS Code from our website, right? Not VSCodium or something else?

**Comment by zdavidsen** [comment]
Yeah, I'm using stock VS Code from the Microsoft website.  Doesn't matter if the server is already running or not either.

**Comment by roblourens** [comment]
@alexdima any idea what's going on here?

**Comment by zdavidsen** [comment]
Here's a log at trace level
[trace.txt](https://github.com/microsoft/vscode-remote-release/files/4421755/trace.txt)

**Comment by alexdima** [comment]
The auth handshake is the very first message exchanged. If the stream is somehow corrupt, it triggers this error. If node is corrupt and cannot load native assemblies, it triggers this error (see https://github.com/microsoft/vscode-remote-release/issues/103).

I believe in this case this is just the very first thing that doesn't work, but I don't think the root cause is in the auth handshake itself.

**Comment by roblourens** [comment]
Oh right, most people are seeing that due to using linux remotes where our node can't run, but I see you're using windows 10 which shouldn't have exactly the same problem. @zdavidsen can you check this file for errors: `~/.vscode-server/.<vscode version hash>.log`

**Comment by zdavidsen** [comment]
Do I need to do something to increase the log level for the server?  The only thing there right now is the same `unauthorized client refused` message

**Comment by roblourens** [comment]
No. Can you just try running the command "Kill VS Code Server on Host" then connect again so it will redownload the server? Maybe the download is corrupt.

**Comment by zdavidsen** [comment]
I don't know how helpful this will be, but here's the server log
[serverlog.txt](https://github.com/microsoft/vscode-remote-release/files/4422419/serverlog.txt)

**Comment by roblourens** [comment]
Yeah no new info, thanks though.

**Comment by zdavidsen** [comment]
@roblourens Any new info on this, or anything I can do to help investigate?
