### ISSUE TITLE
Mininet resource Issue

### ISSUE THREAD

**Issue by krunalmiracle** [microsoft/vscode-remote-release#2673]
Issue Type: <b>Bug</b>

*** Error setting resource limits. Mininet's performance may be affected. when starting the mininet program.

Extension version: 0.42.4
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (21.03GB free)|
|Process Argv|C:\Users\Kruskechi\Desktop\final_topology.py|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2201)|
|Memory (System)|31.85GB (21.03GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Need more information
