### ISSUE TITLE
Remote ssh Does not report on permissions error with .ssh

### ISSUE THREAD

**Issue by patrikniebur** [microsoft/vscode-remote-release#2675]
This issue is difficult to catch when nothing is reported, if permission error was reported it would be easier to fix. Once I correct the permissions according to [troubleshooting guide ](https://code.visualstudio.com/docs/remote/troubleshooting#_fixing-ssh-file-permission-errors) I can connect without problem

- VSCode Version: 1.43.2
- Local OS Version: macOS Catalina v10.15.4
- Remote OS Version: irrelevant
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. set permissions of `~/.ssh` folder to `600`
2. type in "> remote ssh: Add new ssh host" to command palette 
3. fill in ssh command
4. nothing happens (reporting permissions error would help)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
I get this error in a popup in the bottom right

`Command 'Remote-SSH: Add New SSH Host...' resulted in an error (EACCES: permission denied, open '/Users/roblou/.ssh/config')` but it's easy to miss, is it possible that you didn't notice it?

**Comment by patrikniebur** [comment]
I've checked again and this is what I get after I select connect (and nothing happens)

<img width="1108" alt="Screen Shot 2020-04-06 at 8 05 38 AM" src="https://user-images.githubusercontent.com/6452693/78508764-71dce080-77dd-11ea-8ab3-52cfc31e4c94.png">

**Comment by roblourens** [comment]
So you picked the config file and it just didn't write anything into that file, with no error?

**Comment by patrikniebur** [comment]
Exactly. Flow goes like this:
Remote-SSH: Connect to Host >  + Add New SSH Host > ssh prompt I type in `ssh root@192.168.1.22` > Select SSH config file to update  
And here whichever I select it just closes the prompt and nothing else happens. Nothing in the output and no notification.

**Comment by patrikniebur** [comment]
If you're not able to replicate this let me know how I could help. I've seen this exact problem across 3 different devices (2x mac pro, 1 iMac all on latest osx)

**Comment by roblourens** [comment]
I am testing this with `chmod 600 ~/.ssh` is that exactly what I should do to reproduce it? 

I figure it shouldn't but I wonder if it is it able to _read_ the ssh config file in your case, like if you run "Connect to Host" do any hosts from the config file show up?

**Comment by patrikniebur** [comment]
Yes that's the right command if it is where your ssh config is stored too.

I don't think it is able to read the ssh config file because it won't show any hosts. That's what I meant before:
> Also worth noting that if permissions are not set correctly it doesn't list hosts from the config file, so I'm guessing it can't read the file and won't log this either

**Comment by roblourens** [comment]
Ok. Sorry but it seems like if no error is showing up then we are not getting an error from Node's fs module, I have to just close this.

**Comment by patrikniebur** [comment]
No worries, but I thought it would be very useful to have this error reported. It would save me at least an hour trying to figure out the problem which I've seen on other osx machines. 
OT: Is this plugin going to be open sourced?

**Comment by roblourens** [comment]
Sorry, I will keep an eye open for the issue in the future. We don't have any current plans to open source it.
