### ISSUE TITLE
WSL / Docker / composer install: file not found error

### ISSUE THREAD

**Issue by aaronellington** [microsoft/vscode-remote-release#268]
- VSCode Version: 1.34.20-insider d6aa8eaf30c71df32d4543290675808440def630 x64
- Local OS Version: Windows 10.0.17763
- Remote OS Version: Windows WSL Ubuntu 18.04
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. start with a docker project that runs `composer install` on startup
2. start and stop the docker container with no issues (docker for windows is properly configured to run along with WSL)
3. Open the project in VS Code using the WSL extension
4. try to start the docker container again and it complains about not being able to remove some files it just added
5. close VS code 
6. try to start the docker container again and it works just fine

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Other information related to this issue:
- it's a Symfony project so other directories are causing issues too (`var/cache/dev`). Basically, anything that it has files that are deleted and recreated quickly.
- Using `files.watcherExclude` fixes it all cases (not a terrible solution since it helps VS Code run faster too)
- The files get into a state that I can't delete them until I close VS Code. Trying all of the following fails until I close VS Code:
    - dragging the files into the recycle bin via Windows Explorer 
    - `sudo rm -rf vendor/` from WSL

**Comment by egamma** [comment]
Since files.watcherExclude avoids the problem this looks like a auplicate of https://github.com/Microsoft/WSL/issues/3395. This is a known limitation of WSL that will be addressed in WSL2.
