### ISSUE TITLE
Refresh of file explorer does not work correctly while connected to WSL2

### ISSUE THREAD

**Issue by QuadraticQuokka** [microsoft/vscode-remote-release#2680]
Issue Type: <b>Bug</b>

The auto refresh of the file explorer side bar does not seem to work when connected to WSL2 (Ubuntu).

**The following attempts all did not show up in VS Code (Running VS Code with the `--verbose` flag, does NOT register a file event in those cases either):**

* Create a file in WSL bash, either integrated in VS Code or another terminal
* Create a file in WSL bash automatically with `npm init`
* Create a file in windows (no matter the way either)

When opening the corresponding folder in VS Code normally, without the extension, everything works as expected and all changes made in the above ways get shown immediatly as they happen.

A manual refresh of the file explorer with command "File: refresh explorer" then *solves* the issue, and all files that got created get shown in the explorer side bar. 

Extension version: 0.42.4
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.84-microsoft-standard

**Comment by aeschli** [comment]
Are you working a location in `/mnt/c/`?
