### ISSUE TITLE
VSCode Remote Caused Server CPU to increase to 100%

### ISSUE THREAD

**Issue by andrewpolemeni** [microsoft/vscode-remote-release#2684]
The CPU reached a 100% capacity with the remote ssh plugin after being logged out. The time that this process what running was 364:08:80 and happened 4/1/2020 at 6:19 PM.  The command that was run is "node".

The output of ps aux | grep node:
home/apolemeni/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/node /home/apolemeni/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/home/apolemeni/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/uriTransformer.js=

**Comment by roblourens** [comment]
Is this still an issue?
