### ISSUE TITLE
Polish: Kubernetes remote indicator shows too much detail

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#2686]
Testing #2647

![image](https://user-images.githubusercontent.com/172399/78333731-ac027400-758a-11ea-9081-9d87ea8aefe6.png)

Could we just show 'hello-node'  the kubernetes container name
![image](https://user-images.githubusercontent.com/172399/78333857-e835d480-758a-11ea-8dda-c5df38c8b9cd.png)

**Comment by chrmarti** [comment]
Is that a replicated pod or how did it get its name?

We currently use `Kubernetes: ${pod_name}/${container_name} (${image_name})` as the label.

We could change that to `${container_name} in ${pod_name} (${image_name})`. (Or prefix that with `K8s:` or `Kube:`.)

**Comment by chrmarti** [comment]
This would look like:

Short names:
![image](https://user-images.githubusercontent.com/9205389/78642624-52b08280-78b3-11ea-9a6c-f56b6301d62e.png)

Long pod name:
![image](https://user-images.githubusercontent.com/9205389/78642893-b6d34680-78b3-11ea-9469-73c172f569d2.png)
