### ISSUE TITLE
$PATH is changed in the bash of vs code

### ISSUE THREAD

**Issue by wjsgzcn** [microsoft/vscode-remote-release#2687]
- VSCode Version: 1.43.2
- Local OS Version: win10
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH/Docker/WSL
WSL

Steps to Reproduce:

1. install dotnet tools, "dotnet tool update --global dotnet-ef"
2. open terminal in vs code, run "dotnet ef", cannot run
3. echo $PATH, cannot find the path of dotnet tools
4. use windows terminal open wsl directly, and "dotnet ef" can be run, check $PATH contains dotnet tools.

Why the $PATH is different between the windows terminal bash and vs code bash?

**Comment by tanhakabir** [comment]
@wjsgzcn are you still seeing this issue?
