### ISSUE TITLE
WSL Keeps freezing

### ISSUE THREAD

**Issue by TomGrobbe** [microsoft/vscode-remote-release#2694]
Issue Type: <b>Bug</b>

Hard to reproduce, some days it freezes after a few seconds, sometimes after a few minutes, and sometimes it never freezes.

When i say freeze, I mean I can still edit, but I can't use the debugger (start/stop/jump in code), use git (extensions), type in the terminal/console window. Saving a file, depending on the size, takes a very long time (>5/10 seconds). Search in workspace/folders/files completely stops working, search in current/opened file(s) still works.

Rebooting PC does not help usually. It's very, very random and sometimes it can last an entire day (even with pc/vscode restarts), other times it can be gone after a few freezes, or sometimes it never happens.

Extension version: 0.42.4
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (19.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3701)|
|Memory (System)|31.93GB (19.06GB free)|
|VM|0%|
</details>

**Comment by TomGrobbe** [comment]
Additional info:

I haven't tested it with other languages, but I'm using the Python extension, and all code is either Python or html/css/js. Debugging Python (Django) code.

To solve this issue I usually close down visual studio code completely, open the Ubuntu terminal, type `top` to look for all vscode and python related processes to be killed (usually takes around 5-10 seconds after closing vscode) and then I reopen vsc. Then it's a random amount of time, anywhere from a few seconds, to a few minutes, sometimes a few hours before it freezes up again.

**Comment by aeschli** [comment]
This issue needs to be filed against 
https://github.com/Microsoft/vscode-python/issues
Would you mind filing the issue there? (Unfortunately, the issue-transfer tool only works with write access on both repos, which I haven't)

**Comment by TomGrobbe** [comment]
I've made a new issue for it in the linked repo, link is above.
