### ISSUE TITLE
rg consumes all memory and vscode's server is OOM killed

### ISSUE THREAD

**Issue by aarongolliver** [microsoft/vscode-remote-release#2698]
Issue Type: <b>Bug</b>

Upon opening a remote folder `rg` is spawned, in some scenarios it consumes all memory until it (and the rest of the vs code server) is OOM killed

Steps to Reproduce:
- create a ssh remote session as the root user, and open up the root directory `/`.
- rg spawns in the background, slowly consumes memory
- wait
- eventually vscode's server that spawned rg is OOM killed

temporary workaround:
- create a ssh remote session as the root user, and open up the root directory `/`.
- open up a remote shell (ctrl ~)
- run `killall rg`

the command line of rg is something like

`/root/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/node_modules/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g**/package.json -g!**/.git -g!**/.svn-g!**/.hg -g!**/CVS -g!**/.DS_Store -g!**/node_modules/** --no-ignore--follow --no-config --no-ignore-global`

you can see it on top of  `top`... `%MEM` slowly increases until it's forcibly terminated 

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                            
 8564 root      20   0  441036 419452   3316 S 787.3  2.4  11:47.46 rg
```

I have tried disabling all other remote extensions, but that hasn't worked

Extension version: 0.51.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-91-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-7980XE CPU @ 2.60GHz (36 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.71GB (107.09GB free)|
|Process Argv|--no-ansi|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: root.golliver.me|
|OS|Linux x64 4.15.0-91-generic|
|CPUs|Intel(R) Core(TM) i9-7980XE CPU @ 2.60GHz (8 x 2591)|
|Memory (System)|16.73GB (2.31GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/1257
