### ISSUE TITLE
C/C++ Debugger

### ISSUE THREAD

**Issue by PrashantSedhain** [microsoft/vscode-remote-release#2699]
Issue Type: <b>Bug</b>

Hello there, my c/c++ debugger for remote ssh is not being installed correctly. Every time I open ssh, it starts the installation and keeps running for long long time. It used to work for me before, I don't know what's the issue now,

Extension version: 0.51.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-133-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (8.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|SSH: fox03.cs.utsa.edu|
|OS|Linux x64 4.4.0-133-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz (12 x 2600)|
|Memory (System)|15.67GB (14.45GB free)|
|VM|100%|
</details>

**Comment by roblourens** [comment]
Please file on the extension repo, if it's still an issue
