### ISSUE TITLE
Could not find an sshd parent of this process.(Windows10pro & Non administrator account)

### ISSUE THREAD

**Issue by yeruoforever** [microsoft/vscode-remote-release#2701]
- VSCode Version: VSCode 1.43.2
- Local OS Version: Win 10 pro 1909 /18362.752
- Remote OS Version:Win 10 workstation 1909/18363476
- Remote Extension/Connection Type: SSH 0.51.0

Steps to Reproduce:
1.open the VSCode.
2.use a Non administrator account to connect a remote machine.
3.occur an error.
I have a account on remote machine which groups as follows:
![image](https://user-images.githubusercontent.com/19868036/78632923-da59b980-78d2-11ea-8009-5565b22ac9ec.png)
when I connect to remote machine, an  error occurred:
![image](https://user-images.githubusercontent.com/19868036/78632458-a3cf6f00-78d1-11ea-9372-d0c155d38281.png)

The first error message is 'Could not find an sshd parent of this process'.
The complete information is as follows：

```
[13:13:17.627] Showing password prompt
[13:13:23.771] Got password response
[13:13:23.772] "install" wrote data to terminal: "**********"
[13:13:23.789] > 
> 
[13:13:24.496] > #< CLIXML
> 
[13:13:24.505] > dc9029bca61b: running
[13:13:24.515] > 
> 
[13:13:29.699] > Could not find an sshd parent of this process
[13:13:29.707] > 
> 
[13:13:29.720] > <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
> <Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCust
> omObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"
> ><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC
> ><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1
> "><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing m
> odules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T
> ><SR>-1</SR><SD> </SD></PR></MS></Obj><S S="Error">Get-CimInstance : 拒绝访问 _x
> 000D__x000A_</S><S S="Error">At line:19 char:15_x000D__x000A_</S><S S="Error">+ 
> $parentPID = (Get-CimInstance win32_process | ? processid -eq $curren ..._x000D_
> _x000A_</S><S S="Error">+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_x000D__x00
> 0A_</S><S S="Error">    + CategoryInfo          : PermissionDenied: (root\cimv2:
> win32_process:String) [Get-CimInstance], CimException_x000D__x000A_</S><S S="Err
> or">    + FullyQualifiedErrorId : HRESULT 0x80041003,Microsoft.Management.Infras
> tructure.CimCmdlets.GetCimInstanceCommand_x000D__x000A_</S><S S="Error"> _x000D_
> _x000A_</S></Objs>
[13:13:30.047] "install" terminal command done
[13:13:30.048] Install terminal quit with output: _x000A_</S></Objs>
[13:13:30.049] Received install output: _x000A_</S></Objs>
[13:13:30.051] Stopped parsing output early. Remaining text: _x000A_</S></Objs>
[13:13:30.051] Failed to parse remote port from server output
[13:13:30.053] Resolver error: 
[13:13:30.061] ------
```

But when I use 'administrator' to connect  remote machine, there is no problem.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by wpbrown** [comment]
Duplicates https://github.com/microsoft/vscode-remote-release/issues/2648

**Comment by redspinnacker** [comment]
We're using a Windows 10 host machine and ran into the same issue. I resolved this error by setting the default command shell to PowerShell. It initially defaulted to the standard windows command prompt.

**Comment by bamurtaugh** [comment]
Hey @yeruoforever, since it looks like this duplicates the issue #2648 linked above, going to close it out. Please feel free to let me know if I might have missed anything or if you have any other questions or feedback, and I'd be happy to reopen or discuss further. Thank you!
