### ISSUE TITLE
password auth is needed for each new project/ window

### ISSUE THREAD

**Issue by ychechik** [microsoft/vscode-remote-release#2702]
- VSCode Version: 1.43.2
- Local OS Version: windows 10
- Remote OS Version: ubuntu 18.04
- Remote Extension/Connection Type: SSH/Docker/WSL: SSH

Steps to Reproduce:

1. open remote ssh for some project
2. input password- working...
3. open a new project on same remote pc- need to enter password again

This was fixed in this release, and it worked well for two weeks, but then it stopped working again :(

**Comment by bamurtaugh** [comment]
Hey @ychechik! Can you verify if you're still experiencing issues here (since it worked in a certain release but not others)?

**Comment by bamurtaugh** [comment]
Please feel free to let us know if you're experiencing any issues- thank you!
