### ISSUE TITLE
Missing git file status icons

### ISSUE THREAD

**Issue by ShoshinNikita** [microsoft/vscode-remote-release#2703]
- **VSCode Version**: 1.41.0-1.43.2
- **Local OS Version:** Windows 10
- **Remote OS Version:** Ubuntu 18.04.3
- **Remote Extension/Connection Type:** SSH

**Steps to Reproduce:**

1. Open any directory with git repository
2. Edit, remove or add file
3. Open `Source Control`
4. Icons are missing:

    ![image](https://user-images.githubusercontent.com/30220965/78702385-2b889e00-7911-11ea-8a2a-56616fea7290.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

***

It seems VSCode tries to load icons from remote machine:

![image](https://user-images.githubusercontent.com/30220965/78703058-3db70c00-7912-11ea-8d45-8a308ca24be8.png)

These icons do exist:

![image](https://user-images.githubusercontent.com/30220965/78703095-4e678200-7912-11ea-8a57-f47103440898.png)

If I change the path to local one an icon will appear:

![image](https://user-images.githubusercontent.com/30220965/78703449-d77eb900-7912-11ea-8a75-cbe7a44c9c37.png)

**Comment by joaomoreno** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/103073
