### ISSUE TITLE
Initializing forever

### ISSUE THREAD

**Issue by luckydog1996** [microsoft/vscode-remote-release#2708]
- VSCode Version: x64-1.43.2
- Local OS Version:
- Remote OS Version: ubuntu 18.04.4 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.I can connect to the SSH host by running the ssh username@hostname command from a terminal 
2.using VScode remote extension to connect, there is a notification on the lower right corner "Initializing Vscode server" and it just stuck there with no progress. I have been waiting for 24h. The remote server I try to connect is in work since others can use ssh remote to connect.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
If this is still an issue, please add the full log from the Remote-SSH output channel
