### ISSUE TITLE
[Feature Request] File Synchronization 

### ISSUE THREAD

**Issue by AlexandreGarino** [microsoft/vscode-remote-release#2709]
Please provide File Synchronisation like mutagen.io does especially for Remote Containers.

> Mutagen’s file synchronization uses a novel algorithm that **combines the performance of the rsync algorithm with bidirectionality and low-latency filesystem watching**. It can be used (for example) to synchronize code between your laptop and a remote container in effective real-time, allowing you to edit code with your editor of choice and have it pushed to the remote environment almost instantly. Because it uses differential transfers, **Mutagen’s synchronization also works effectively for transferring large binary files such as images or build artifacts**.

> Mutagen provides four different synchronization modes:
**two-way-safe** (Default): In this bidirectional synchronization mode, both endpoints are treated with equal precedence, and conflicts are only automatically resolved if they don’t result in data loss (for example, modifications on one endpoint can can overwrite deletions of the corresponding content on the other endpoint). If conflicts can’t be automatically resolved, they are stored in the session state (and can be enumerated with the mutagen sync list command).
**two-way-resolved**: This is the same as two-way-safe, except that the alpha endpoint automatically wins all conflicts, including cases where alpha’s deletions would overwrite beta’s modifications or creations. No conflicts can occur in this synchronization mode.
**one-way-safe**: In this unidirectional synchronization mode, changes are only allowed to propagate from alpha to beta. Deletions on beta are overwritten by content from alpha (i.e. the content comes right back), but modifications and creations on beta can’t be overwritten by alpha (unless both endpoints have made the same modifications or created the same content). Conflicting contents on beta that can’t be overwritten will be recorded to the session state (and can be enumerated with the mutagen sync list command). Extra content on beta that doesn’t conflict with contents on alpha is simply ignored.
**one-way-replica**: In this unidirectional synchronization mode, beta becomes an exact replica of alpha. Any modifications or additional content on beta are instantly overwritten or removed, respectively. No conflicts can occur in this synchronization mode.

Source -- https://mutagen.io/documentation/synchronization

Related issues:
- #2001

**Comment by chrmarti** [comment]
Could you describe the scenario you have in mind? Is editing large files like in #2001? Or having a local project folder and sending its files to the container?

**Comment by AlexandreGarino** [comment]
The first use case to address is to synchronize local project folder to a container.

The way the mutagen.io project have implemented this feature address the large file synchronization issue as well.

HTH

**Comment by chrmarti** [comment]
You could use the `devcontainer.json`'s `"initializeCommand"` to start a secondary container that mounts a volume and then create a mutagen sync session with that container, such that the volume gets all the project files. The `devcontainer.json`'s `"workspaceMount"` would then need to be set to mount the same volume and `"workspaceFolder"` would need to be set to the path of the project folder inside the devcontainer with the volume mounted.

Would that work?

/fyi @Chuxel @egamma
