### ISSUE TITLE
Port forwarding issues

### ISSUE THREAD

**Issue by dbshch** [microsoft/vscode-remote-release#271]
- VSCode Version: 1.34.20-insider
- Local OS Version: Win 10 1809
- Remote OS Version: multiple Linux OS tested
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to server
2. Forward Port from Active Host or use ssh config to forward port

I've searched the issues but saw no one related, is it only me met this issue?

I followed the instructions in https://code.visualstudio.com/docs/remote/ssh#_forwarding-a-port-creating-ssh-tunnel. But the behavior seems strange.

When using "temporarily forwarding a port", it says "a notification will tell you the localhost port you should use to access the remote port", but actually you will input the localhost port. Is the document outdated? But after specifying the localhost port, it seems useless. For example, forward server:8080 to localhost:8082, I can only access my service on localhost:8080 but not on 8082. If the ports both are 8080, I can access it on 8080.

When using the ssh config method, it behaves the opposite way. In config, I use "LocalForward 127.0.0.1:8082 127.0.0.1:8080". I think it's forwarding server:8080 to localhost:8082? I can access it on 8082 but not on 8080. It's the opposite to temporarily forwarding.

Also, when using the ssh config method, the forwarding ports are not shown in the section "Forwarded Ports". Is it a missing feature? It's a little confusing when using this method.

Does this issue occur when you try this locally?: 
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
> When using "temporarily forwarding a port", it says "a notification will tell you the localhost port you should use to access the remote port", but actually you will input the localhost port.

When you use `Remote – SSH: Forward port from active Host...` you enter the number of the port on the server/remote box that you want to forward to your local box. At no point do we ask you to enter a port on your local box.

![image](https://user-images.githubusercontent.com/4674940/57540742-3eaa7c80-7302-11e9-8683-a566e50dff69.png)

The documentation describes that correctly. 

If the port number that is used on the remote box is available on the local box we will use it. If not, we will search for a free port.

**Comment by kieferrm** [comment]
> Also, when using the ssh config method, the forwarding ports are not shown in the section "Forwarded Ports". Is it a missing feature? It's a little confusing when using this method.

Yes, pls file a separate feature request for this. Thanks!

**Comment by dbshch** [comment]
Ok, I didn't notice the second prompt is the name.

> If the port number that is used on the remote box is available on the local box we will use it. If not, we will search for a free port.

I thought local will use a different port and notify it every time since the document didn't say it will first check the port availability.
 
> After entering a port number, a notification will tell you the localhost port you should use to access the remote port. For example, if you forwarded an HTTP server listening on port 3000, the notification may tell you that it was mapped to port 4123 on localhost. You can then connect to this remote HTTP server using http://localhost:4123.

So I think the document still a little not precise.
Also, can't specify the local port might be a little not user friendly in some cases?

Thanks.

**Comment by jjeejj** [comment]
Cannot specify local port，local mapping ports can only be identical to remote service port. 
![image](https://user-images.githubusercontent.com/15176971/58383477-f382b000-8009-11e9-95f7-3cc26cac79db.png)
**name the local port ,not local port**
