### ISSUE TITLE
Remote Debugging C++ From mac to linux times out

### ISSUE THREAD

**Issue by mdborges** [microsoft/vscode-remote-release#2710]
I'm trying to remote debug a C++ hello world program running on my linux machine from my mac machine.  I am able to use remote development to ssh to the machine fine.  I can see files and modify them on the linux machine through vs code running on my mac no problem.  However, when I try to launch or attach (if I pre-run the program on linux), nothing happens in vs code.  Even when I set logging to have engineLogging: true, I get no output in the debug console.  I searched through the VS Code logs and found that whenever I try to launch or attach this is error is logged:

`[2020-04-08 16:09:47.357] [renderer5] [error] timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3044:67)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3043:339
    at async t.RawDebugSession.shutdown (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3041:336)
`

My launch.json file is attached (named launch.txt).

Any idea of what I could be doing wrong either on my mac or linux machine?

Thanks,
Matt

[launch.txt](https://github.com/microsoft/vscode-remote-release/files/4452646/launch.txt)

**Comment by gqshell** [comment]
I am getting same issue from Windows VS Code connecting to Remote Linux host.  Is there a verbose flag or anything to get additional info on what is timing out?

**Comment by mdborges** [comment]
It ended up being a PATH issue for me.  Whenever I ssh'd to my linux machine I always had gdb in my PATH but however vscode connects, it was causing my startup scripts (like .profile) to be executed in a way that did not have gdb in the PATH.  I got lucky and found one line in one of the startup scripts which I was given set the PATH without referencing the current PATH.  By making sure I only prepend or append to PATH (and never set it explicitly), the timeout issue went away.

So I would double check that gdb is in your PATH and make sure you don't have any startup scripts which set PATH explicitly without referencing either the existing PATH or don't include gdb.

It would have saved a lot of time if vscode gave a more explicit message about gdb not being in the PATH instead of a generic timeout message.

Matt

**Comment by gqshell** [comment]
Thanks for the reply.  So my remote machine is managed by my company so I can't change the .profile - only a file that gets sourced from there (.profile.user).  There wasn't anything that sets PATH in either file so I tried adding a line to add GDB to the PATH but it didn't seem to change anything.  Is there a way to emulate how VS code connects so I can check if GDB is in the path?
