### ISSUE TITLE
Port forwarded localhost translated to 127.0.0.1 when opened externally, breaks things like self-signed HTTPS

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#2711]
Issue Type: <b>Bug</b>

Extension version: 0.112.0
VS Code version: Code - Insiders 1.44.0-insider (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T21:42:32.364Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|17%|

|Item|Value|
|---|---|
|Remote|Dev Container: C# Sample|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (4 x 2492)|
|Memory (System)|3.85GB (0.19GB free)|
|VM|0%|
</details>

When clicking on a link in the terminal that contains `localhost` (e.g. https://localhost:5001), the local browser is always opened to `127.0.0.1` instead.  You can also see this same behavior when using `serverReadyAction` in `launch.json`.  The problem is that this can cause problems with things like self-signed HTTPS certs.

This likely happens for all remote extensions, but I encountered it with Remote - Containers:

Repro:
1. Use **Remote-Containers: Try a Sample...** and select .NET Core
2. Follow the directions to enable HTTPS in the sample [here](https://github.com/microsoft/vscode-remote-try-dotnetcore#enabling-https).
3. Start debugging (F5)
4. Click on `http://localhost:5000` or `https://localhost:5001` in the debug window

**Expected:** Web page appears
**Actual:** `https://127.0.0.1:5001` is opened in the browser which results in a certificate error.  If you change this to `https://localhost:5001`, everything works.

What should happen to avoid this is that "localhost" is preserved if localhost is in the URI and 127.0.0.1 is used instead if this was in the URI.

**Comment by Alirezanet** [comment]
I have the same problem. any update on this?

**Comment by aeschli** [comment]
Tried to verify in with the following steps:
- Use Remote-Containers: Try a Sample... and select .NET Core
- In the remote window, run F5
- click https://localhost:5001 in the debug window

Browser opens on https://127.0.0.1:5001

Should be https://localhost:5001
(I skipped the container setup setup steps, but I assume to verify the issue that's not needed)

**Comment by alexr00** [comment]
This is in the devcontainer.json for that sample: 
```json
	"forwardPorts": [5000, 5001],
```
which means that the containers extension is already forwarding them with 127.0.0.1. Can you try again, but before you F5 go to the forwarded ports view and Stop Forwarding those ports?

**Comment by Alirezanet** [comment]
I have very similar problem in Wsl2 not remote container's. should I create new issue ?

**Comment by chrmarti** [comment]
Updating this for `"forwardPorts"` in the devcontainer.json too.

@Alirezanet I see @alexr00's fix is in common code, you could try VS Code Insiders to check if it fixes your case too: https://code.visualstudio.com/insiders/

**Comment by Alirezanet** [comment]
interesting... I did not changed anything and its working correctly in Vscode insiders...
thanks

**Comment by alexr00** [comment]
Verified by @aeschli
