### ISSUE TITLE
After moving directories, Intellisense shows error squiggles despite being able to jump to the proper header definition

### ISSUE THREAD

**Issue by Clee681** [microsoft/vscode-remote-release#2712]
Issue Type: <b>Bug</b>

Hello,

After moving my directories around, Intellisense is showing an error squiggle for a `.c` file. Despite the error, I'm able to successfully jump to the header definition. I tried resetting the Intellisense database, but that didn't help. Any assistance would be greatly appreciated!

Extension version: 0.112.0
VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 19.4.0
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Pipeline Dev Container|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (6 x 2900)|
|Memory (System)|1.94GB (0.07GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Is the project folder mounted from the Mac filesystem? Does it work when you do the same on the local filesystem? And does the problem occur every time you move the directories or only this time?

**Comment by Clee681** [comment]
> Is the project folder mounted from the Mac filesystem?

Yep, the VS Code workspace was mounted from the Mac filesystem into the Docker dev container.

> Does it work when you do the same on the local filesystem?

Unfortunately, I don't think I can test this given that my local filesystem doesn't have the proper libraries installed. This is actually the main reason why I'm using a dev container, so that I can manage my C programming environment a little easier.

> And does the problem occur every time you move the directories or only this time?

This is the first time I tried moving directories around. Also, I should note that I moved the location of the `.devcontainer` within the workspace as well.

## Steps to recreate

Hopefully, the below description helps reproduce the issue I was seeing. The main changes I made to the filesystem were removing the `operator` directory (i.e. collapsing the folder structure one level) as well as renaming the `pipeline` subdirectory to `webrtc`.

### Before

```
├── operator
│   ├── .clang-format
│   ├── .vscode
│   │   ├── c_cpp_properties.json
│   │   └── settings.json
│   ├── .devcontainer
│   │   ├── Dockerfile
│   │   └── devcontainer.json
│   ├── ingest
│   │   ├── Dockerfile
│   │   ├── Makefile
│   │   ├── include
│   │   │   └── pipeline.h
│   │   └── pipeline.c
│   └── pipeline
│       ├── Dockerfile
│       ├── Makefile
│       ├── include
│       │   ├── pipeline.h
│       │   └── server.h
│       ├── pipeline.c
│       └── server.c
```

### After

```
.
├── .clang-format
├── .devcontainer
│   ├── Dockerfile
│   └── devcontainer.json
├── .vscode
│   ├── c_cpp_properties.json
│   └── settings.json
├── ingest
│   ├── Dockerfile
│   ├── Makefile
│   ├── include
│   │   └── pipeline.h
│   └── pipeline.c
└── webrtc
    ├── Dockerfile
    ├── Makefile
    ├── include
    │   ├── pipeline.h
    │   └── server.h
    ├── pipeline.c
    └── server.c
```

After making the above changes, I started to see error squiggles in the `webrtc/pipeline.c` file despite the type being present in the `webrtc/include/pipeline.h` header. Also, it weirdly jumped me to the `ingest/include/pipeline.h` header file when I renamed the `webrtc/include/pipeline.h` file to `webrtc/include/webrtc.h`.

**Comment by chrmarti** [comment]
I assume this is caused by the C++ extension. Please file a new issue for it: https://github.com/microsoft/vscode-cpptools/issues. Thanks.
