### ISSUE TITLE
after latest update the remote connection does not work properly

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode-remote-release#2717]
Issue Type: <b>Bug</b>

After the latest update (0.112.0),  the git does not get initialized in a properly working git repository folder. revert to version 0.111.0 and everything works as expected.

Extension version: 0.111.0
VS Code version: Code - Insiders 1.44.0-insider (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T21:41:19.483Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-96-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: angular_serve|
|OS|Linux x64 4.15.0-96-generic|
|CPUs|Intel Xeon E312xx (Sandy Bridge, IBRS update) (4 x 2399)|
|Memory (System)|7.79GB (6.77GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Could you attach the log or a screenshot showing the problem? There were no Git related changes between 0.111.0 and 0.112.0.

**Comment by chrmarti** [comment]
Also make sure to use the latest version of VS Code stable or insiders. (There was a fix in a recent Insiders build.)

**Comment by sanket-bhalerao** [comment]
i can see this is working fine now.
closing the issue.
