### ISSUE TITLE
Changing location of lockfiles

### ISSUE THREAD

**Issue by dawidstezycki** [microsoft/vscode-remote-release#2718]
We have a problem with tmp directory filling up due to many users using it and being cleaned only once a day. I would like to be able to point a directory for the lockfiles so that i can create my own tmp that's stored not in a common space.

**Comment by roblourens** [comment]
Normally they are stored in your home folder, did you set `remote.SSH.lockfilesInTmp`?

**Comment by dawidstezycki** [comment]
Yes, to fix issue with NFS home directory.

**Comment by roblourens** [comment]
Ok, you might try it again since now I use `ln` instead of `flock` for locking, and that might resolve your NFS issue. But I will keep this open as a feature request.

**Comment by roblourens** [comment]
Now you would have to disable the `useFlock` setting, still a valid workaround though.
