### ISSUE TITLE
VSCode unable to be opened from WSL2 after importing to a new PC.

### ISSUE THREAD

**Issue by CyberiumShadow** [microsoft/vscode-remote-release#2720]
- VSCode Version: 1.44.0
- Local OS Version: Win10 2004 (19041.172)
- Remote OS Version: 4.19.84-microsoft-standard (Ubuntu)
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Open WSL via default distro with `wsl` in `cmd` or `pwsh`
2. Attempt to open VSCode within WSL with `code .`
3. Error occurs: ```/mnt/d/Programs/Microsoft VS Code/bin/code: 37: /mnt/d/Programs/Microsoft VS Code/bin/code: cannot create /tmp/remote-ws
l-loc.txt: Permission denied
/mnt/d/Programs/Microsoft VS Code/bin/code: 43: /mnt/d/Programs/Microsoft VS Code/bin/code: /mnt/c/Users/johns/.vscode/e
xtensions/ms-vscode-remote.remote-wsl-0.42.4/scripts/wslCode.sh: not found```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Main Note: This error started occurring after I had exported the distro and imported it to a new PC

**Comment by magusd** [comment]
I started getting this error after an update.

I ran wsl.exe -u root and I was able to start vscode from the wsl terminal.

Solved for my wsl regular user with:

`rm -rf .vscode-server`

Then `code .` started working again

**Comment by bamurtaugh** [comment]
Thanks for the guidance @magusd! @CyberiumShadow please let us know if you're still experiencing this or if the above suggestions do/don't work for you.
