### ISSUE TITLE
[Remote-SSH] Open remote file in ssh session from any other terminal

### ISSUE THREAD

**Issue by dufferzafar** [microsoft/vscode-remote-release#2721]
This is similar to #263 and #766 - where it was suggested that we can use `code` or `code-insiders` command from the *integrated terminal* to open a file in VSCode.

But. what about any other terminal?

Is it possible to edit a file by running a command like this from some terminal (other than the integrated one?)

```
user@remote $ code /remote/file/to/be/open/locally
```

**Comment by roblourens** [comment]
No, unfortunately that's not really possible

**Comment by dufferzafar** [comment]
@roblourens I don't know anything about how Remote SSH works, so I' probably wrong but I was actually going to look into how the VS Code client talks to the server and if I'm already SSH'ed into that remote can't I just send a command to the server to open that file?

And if this isn't supported right now, do you think it can be? in future maybe? as you can see there were other requests for this feature so people do seem to want it.

**Comment by dufferzafar** [comment]
Currently, whenever I need to open a file from the terminal, I have to copy the path manually from the terminal and then paste it to the Quick Open pallette in VS Code.

**Comment by roblourens** [comment]
The main issue is that it needs to send a message to VS Code running on the client and tell it to open that file. An external SSH session doesn't have any way to launch programs on your client or to tell the client to open a file.

**Comment by dufferzafar** [comment]
@roblourens Um, maybe I'm not explaining correctly. I agree that there is no wa a random SSH session can tell VS Code to open a file. 

But, what if the SSH session is to a remote which the VS code client is connected to?

For eg.

* VS Code client (running on my laptop) is connected to a server running on my office machine.

* From my laptop, I'm also SSH'ed into my office machine, via a terminal + tmux setup.

Now, since the vscode server is running on the office machine and I have an SSH connection to it, I can see the server process in htop, i know it's PID, i know the port it is listening to.

Shouldn't I also be able to tell the client to open a file?

**Comment by roblourens** [comment]
If you really want this, here is what you need -

- in the remote vscode integrated terminal, `echo $VSCODE_IPC_HOOK_CLI`
- copy that value into the external terminal session like `VSCODE_IPC_HOOK_CLI=xyz` 
- Then make sure you invoke the `code` command from the server, like `~/.vscode-server/bin/<somehash>/bin/code` - in the integrated terminal we add this location to the beginning of PATH, but you can copy it from there if you want too

Not officially supported but there you go

**Comment by dufferzafar** [comment]
So, the real issue is with the VSCODE_IPC_HOOK_CLI variable, as it changes on every connection, right?

Will this not be supported in the future as well?

**Comment by roblourens** [comment]
It has to be different per window and connection. I don't see that changing.

**Comment by dufferzafar** [comment]
Um, it the can't change, then will it be possible for thr Remote SSH plugin to write this information in some file on the remote server?

```
echo $VSCODE_IPC_HOOK_CLI > ~/.vscode-server/instances/1
```

Now I'll be able to create a shell function on the remote that can just read this.

**Comment by roblourens** [comment]
Not planning on that but you can certainly write an extension to do that.

**Comment by dufferzafar** [comment]
Okay, I'll look into this. I've never written a VS Code extension before. The API seems pretty exhaustive, so could you point me to which APIs would be involved in writing an extension like this? 

As I said, what I want to achieve is to just execute a command as soon as the Remote SSH extension has established a working SSH connection. The extension will execute a command in that context (so it has the `$VSCODE_IPC_HOOK_CLI` variable.)

I'll also write a shell wrapper that will be used on the remote - this will be straightforward.

Also, I couldn't find the code for the Remote SSH plugin on this repository. Is the code not on GitHub?

**Comment by roblourens** [comment]
You should be able to get the value of that variable directly off `process.env`, I assume, not 100% sure if it is in the Extension Host process environment. And the activate method on your extension will be called when the connection has been established.

**Comment by dufferzafar** [comment]
So I've beein digging on this further and I can confirm that the [method suggested](https://github.com/microsoft/vscode-remote-release/issues/2721#issuecomment-612530084) by does work.

It took me the following commands:
```bash
export VSCODE_IPC_HOOK_CLI="/tmp/vscode-ipc-ed5a7cd1-87be-4141-893f-85c94138265d.sock"
~/.vscode-server-insiders/bin/e8dbc5ea6092ba73ae70069d3e730f2cc56addff/bin/code-insiders FILENAME
```

All that's left now is to make it "cleaner", I listed all the sockets in my tmp directory `ls /tmp/vscode-ipc-*` and there's too many of them. Not all them must be "live" right now. @roblourens Is there a way to "clean" all stale sockets? 

If only one socket remains there, then I could just use that. Won't need to create a VS Code extension.

**Comment by dufferzafar** [comment]
I have this script for now, that I call `vsr` like [`nvr`](https://github.com/mhinz/neovim-remote).

```bash
#!/bin/bash

# A tool like neovim-remote (nvr) that can open files in the VS Code that is connected to a remote server
# See this issue for discussion: https://github.com/microsoft/vscode-remote-release/issues/2721

# These variables are essentially configurable?
VSCODE_SERVER_ROOT=~/.vscode-server-insiders
VSCODE_IPC_PREFIX=/tmp/vscode-ipc-

# TODO: Auto-detect the latest hash by listing the directory
VSCODE_SERVER_HASH=e8dbc5ea6092ba73ae70069d3e730f2cc56addff
VSCODE_SERVER_BIN=$VSCODE_SERVER_ROOT/bin/$VSCODE_SERVER_HASH/bin/code-insiders

# Got this by doing echo $VSCODE_IPC_HOOK_CLI in the VS Code internal terminal
if [ -z ${VSCODE_IPC_HOOK_CLI+x} ]; then
    VSCODE_IPC_HOOK_HASH=ed5a7cd1-87be-4141-893f-85c94138265d
    export VSCODE_IPC_HOOK_CLI=$VSCODE_IPC_PREFIX$VSCODE_IPC_HOOK_HASH.sock
fi

# Launch VS Code now!
$VSCODE_SERVER_BIN "$@"
```

So you can just `vsr path/to/file` to edit it in the locally running VS code.

**Comment by dufferzafar** [comment]
I've updated the script above which finds which VS code socket to use by grepping `/proc/net/unix/`
