### ISSUE TITLE
[Remote SSH] Different server path directory

### ISSUE THREAD

**Issue by dufferzafar** [microsoft/vscode-remote-release#2722]
Run the VS Code Remote SSH server from a different path.

By default, the server runs from `~/.vscode-server-insiders` but I have NFS running on the home directory, which might make things slow.

I also have an SSD drive attached on `/spare/ssd`, how do I run the server from a different path? 

I couldn't find a setting for this - and I guess the setting would have to be per-remote?

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/472
