### ISSUE TITLE
1.44 breaks remote docker

### ISSUE THREAD

**Issue by cyberhound1** [microsoft/vscode-remote-release#2724]
- VSCode Version: 1.44
- Local OS Version: MacOs 10.15.4
- Remote OS Version:
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Select Open Folder in Container and select folder
2. In this instance the folder contains a jruby on Rails project.
3. The following error occurs:
[0 ms] Start: Resolving remote
[1 ms] Setting up container for folder or workspace: /Users/james/RubyOnRails/patientdmzformv4.2.10

[11 ms] Start: Check Docker is running
[11 ms] Start: Run: docker info
[978 ms] Error: EISDIR: illegal operation on a directory, read

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No
Docker Container starts normally with docker-compose up
I have been using this project with vs code remote extension for six months and i worked normally until this new version of vs code installed.

**Comment by chrmarti** [comment]
Could you attach your devcontainer.json?

**Comment by cyberhound1** [comment]
devcontainer.json attached

**Comment by chrmarti** [comment]
@cyberhound1 Mail attachments do not get through. Could you attach from github.com?

**Comment by cyberhound1** [comment]
// See https://aka.ms/vscode-remote/devcontainer.json for format details.
{
	"dockerComposeFile": "docker-compose.yml",
	"service": "patient-form",
	"workspaceFolder": "/usr/src/app",
	"extensions": [
		"bung87.rails",
		"rebornix.ruby",
		"castwide.solargraph",
		"misogi.ruby-rubocop",
		"sianglim.slim",
		"bung87.vscode-gemfile",
		"vortizhe.simple-ruby-erb"
	]
}

**Comment by chrmarti** [comment]
Could you also attach the docker-compose.yml and the Dockerfile (if any)?

Is this the latest version of the extension? (>=0.112.0)

**Comment by cyberhound1** [comment]
The info you requested is provided below.  As background I have been using this as a development platform on a daily basis since for over a year.  Also I have been using the remote container extension since I became aware of it almost a year ago I think. I have never had a problem until I opened vscode after an update.  I posted the issue that same day.

The extension version is 0.112.0
docker-compose.yml file:
version: '3.0'
services:
  patient-form:
    build: .
    #dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3035:3035"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/app
  
  database:
    image: microsoft/mssql-server-linux
    volumes:
      - data-mssql:/var/opt/mssql
    env_file:
      - .env/database
    ports:
      - "1433:1433"

volumes:
  data-mssql:

Dockerfile:
FROM jruby:9

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 0

WORKDIR /usr/src/app

RUN apt-get update -yqq
RUN apt-get install -yqq --no-install-recommends apt-transport-https

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add
 
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update -yqq && apt-get install -yqq --no-install-recommends nodejs
RUN apt-get install -yqq --no-install-recommends yarn inotify-tools

COPY Gemfile Gemfile.lock ./
COPY package.json yarn.*  ./
RUN bundle install
RUN yarn install

COPY . .
COPY mssql-jdbc-7.0.0.jre8.jar /opt/jruby/lib

CMD ["bin/rails","s", "-b", "0.0.0.0"]

**Comment by cyberhound1** [comment]
The bold throws errors if....Gemfile.lock is a commented out line that came through in bold when I posted the comment.

**Comment by cyberhound1** [comment]
Additional info. I can start the container with 'docker-compose up' and attach to it.
It is when I click open folder in container or click on the link in 'Recent' of a container that was previously successfully opened ( before the latest update ) by using the open folder from container.

**Comment by chrmarti** [comment]
We don't handle the case where `.env` is a folder in the project root. To work around this until we have the fix out, you could rename the `.env` folder (and update the references in docker-compose.yml which gave me the hint).
