### ISSUE TITLE
Enable Dockerfile/devcontainer.json iteration from repository containers - support to inspect a volume

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#2726]
I started using repository containers to update the vscode-remote-try-* samples but ended up moving back to the local filesystem because there was no way to iterate on the Dockerfile or devcontainer.json file once in the repository.  

The issue is that, once it failed, there was no way to recover. This is because you cannot "reopen locally" given the is in a volume. Practically speaking, you need to do all your container iteration in a local clone of a repo, then push.  That workflow hiccup will slow adoption IMHO.

To recommend use of the repository container from the start, we'd need some way need to be able to edit these files from VS Code despite their being in a volume and allow a container rebuild without risk.

One possible way to resolve this issue would be to replace "Reopen locally" with "reopen in temporary container" or something similar that mounts the same volume but with a simple image that contains little more than basic editing and Git.  (e.g. A simple approach could be to have the extension drops a pre-defined devcontainer.json in a temp folder that includes the volume as the workspace mount and then do "open folder in container on it.)

This is related, but separate from, #2435 and #2428 which assumes you've pushed an update to the repository (whereas here you would not).

//cc: @egamma @chrmarti

**Comment by Chuxel** [comment]
Related to https://github.com/MicrosoftDocs/vsonline/issues/51

**Comment by chrmarti** [comment]
I agree with the safe-mode container approach. A simple way of implementing it would be to pass a flag `safemode: true` in the authority and with that set skip reading the devcontainer.json from the project folder and instead set the config to a safe default. That config could be in code to avoid having the user opening the temp file.
