### ISSUE TITLE
What's the difference beween SFTP plugin and Remote Dev?

### ISSUE THREAD

**Issue by Ricky1986** [microsoft/vscode-remote-release#2729]
Issue Type: <b>Feature Request</b>

I think that the SFTP plugin is better than the Remote Dev Plugin.
coz SFTP is faster and more stable.
And SFTP is easy to set-up.

Extension version: 0.20.0
VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

**Comment by roblourens** [comment]
There's a good writeup here https://code.visualstudio.com/docs/remote/remote-overview
