### ISSUE TITLE
Folder settings are not applied when a multi-root workspace is opened in SSH/WSL/Containers

### ISSUE THREAD

**Issue by iyuge2** [microsoft/vscode-remote-release#273]
Issue Type: <b>Bug</b>
- reproduce
1. click the python version button
![image](https://user-images.githubusercontent.com/17513434/57507835-7b8e6780-7332-11e9-9e9d-333903def94d.png)
2. select the other python version
![image](https://user-images.githubusercontent.com/17513434/57507877-92cd5500-7332-11e9-81f0-0ac9db570672.png)
3. check the setting.json, the python path actually changed as I wished
![image](https://user-images.githubusercontent.com/17513434/57507940-c01a0300-7332-11e9-9d27-8e3c8ad01061.png)
4. However, when I run my codes, the python version is still the default version before I changed.
![image](https://user-images.githubusercontent.com/17513434/57508339-d2e10780-7333-11e9-85ae-5c84ca5ca4a7.png)

- This problem doesn't happen when I use vscode locally.

Extension version: 0.13.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:21:48.884Z)
OS version: Darwin x64 18.5.0
Remote OS version: Linux x64 4.18.0-18-generic

**Comment by egamma** [comment]
We need more info:
- which extension are you  using vscode-remote-containers, vscode-remote-ssh, vscode-remote-wsl?
- is the setting.json the user, workspace, or machine settings? See https://code.visualstudio.com/docs/remote/ssh#_ssh-hostspecific-settings
- does the container have the other python versions installed?
- can you share your devcontainer definition files (devcontainer.json and the corresponding dockerfile).

**Comment by iyuge2** [comment]
- I am using vscode-remote-ssh.
- is the setting.json of the workspace.
I have found this problem will happen when I use a workspace, but when I just open my project as a folder, this problem won't happen.

**Comment by iyuge2** [comment]
- I am using vscode-remote-ssh.
- It's the setting.json of the a folder.
![image](https://user-images.githubusercontent.com/17513434/57510644-ebecb700-7339-11e9-86d9-ff0e8eb9e10e.png)

- I have found when I open my project as a folder, not in a workspace, this problem won't happen.

**Comment by iyuge2** [comment]
And when I change the python path in the setting.json of workspace, this problem won't happen too.

**Comment by letmaik** [comment]
I face the same problem. When you select an interpreter then it changes the local settings, not the remote settings. If I manually change the remote settings.json, it works.

**Comment by egamma** [comment]
@iyuge2 you have closed the issue, can you share how you resolved your problem?

**Comment by iyuge2** [comment]
@egamma , sorry for my impoliteness. Actually, I didn't solve this problem. I found this problem would happen only when I open multiple project folders in one workspace (remote vscode). And I want to select another python version for one project folder in this workspace, it failed. 
Now, I open my project as an independent folder or save as an independent workspace. This problem won't happen again.

**Comment by egamma** [comment]
@iyuge2 looks like you worked around this problem and there is an issue when you have workspace with multiple root folders. We should understand what his going on.

**Comment by sandy081** [comment]
@iyuge2 May I know if this works when you open multiple python folders (those exist in the local machine) as a workspace ?

**Comment by iyuge2** [comment]
In the local machine, it works. But, for the remote, still not working.

**Comment by bhatiaabhinav** [comment]
I have the same exact same issue when using remote-wsl as well

**Comment by juliussimonelli** [comment]
I have a similar issue when I have multiple project folders open in one workspace. Here's a description of what I'm seeing:
When I open up VSCode - Insiders on a remote ssh, on the bottom left I see in yellow "Select Python Interpreter". When I click on this a menu opens from the top showing various Python interpreter location (e.g. /usr/local/bin/python), but when I click on one nothing happens (no Python interpreter is selected). I also tried by pressing F1 and selecting "Python: Select Interpreter", but again nothing happens when I click on one of the options. If I try to run the file in the debug window, I'll get an error about selecting a python interpreter, which I can then click on to bring up the same menu and get the same results.

**Comment by karrtikr** [comment]
This issue occurs with both `vscode-remote-ssh` and `vscode-remote-wsl` extension.

**Comment by tunnij** [comment]
Same issue here with remote-ssh. When I open as folder there is no issue but when opened as workspace then selecting a different env (I'm using conda) then the env doesn't change (in the status bar or when run).

**Comment by wongjn** [comment]
I have experienced this issue with `vscode-remote-wsl`. What I've generally found is that no *Workspace **Folder*** settings are applied in a multi-root workspace; only *Global* or *Workspace*.

**Comment by eykamp** [comment]
I can reproduce this issue when opening a remote ssh workspace (I can't choose a Python interpreter); if I open the same location as a folder, I do not have the issue (I can select an interpreter).

**Comment by replay** [comment]
> I can reproduce this issue when opening a remote ssh workspace (I can't choose a Python interpreter); if I open the same location as a folder, I do not have the issue (I can select an interpreter).

That works for me too, thanks for figuring that out

**Comment by git4lad** [comment]
Do we have any ETA for fixing this issue ?

**Comment by juliussimonelli** [comment]
I am also having the error with just a single folder in my workspace. I'm running the stable build of VSCode. I tried adding the folder to my workspace but every time I click to change the Python Interpreter it doesn't take. I can see the path change in settings.json "python.pythonPath", but it still says "Select Python Interpreter".

**Comment by brettcannon** [comment]
We're tracking this at https://github.com/microsoft/vscode-python/issues/5724, so it's best if people 👍 that issue and provide details there (tracking stuff cross-repo isn't fun 😞 ).

**Comment by brettcannon** [comment]
@Chuxel after investigating the issue looks to be on the VS Code side due to folder settings not being sent (see [this comment](https://github.com/microsoft/vscode-python/issues/5724#issuecomment-495954971)).

**Comment by Chuxel** [comment]
@sandy081 @brettcannon Thanks - missed that.  Updated the issue title to reflect the real issue to avoid further confusion.

**Comment by sandy081** [comment]
To verify:

Write an extension that reads `python.pythonPath` setting by passing workspace folder resource

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    let disposable = vscode.commands.registerCommand('extension.testResourceSetting', async () => {
        const config: vscode.WorkspaceConfiguration = vscode.workspace.getConfiguration('python', vscode.workspace.workspaceFolders[0].uri);
        vscode.window.showInformationMessage(`Python path: ${config.get('pythonPath')}`);
    });
    context.subscriptions.push(disposable);
}

export function deactivate() {
}
```

- Open a remote window (SSH, WSL or Dev Container) and install Python and your extension (above).
- Open multi folder workspace in remote window
- Open folder settings of first folder and change `python.pythonPath` value
- Run command `extension.testResourceSetting` and verify that it prints the value you changed to.
