### ISSUE TITLE
Remote ssh extension won't work on latest insiders

### ISSUE THREAD

**Issue by derekriemer** [microsoft/vscode-remote-release#2732]
Issue Type: <b>Bug</b>

1. try to connect to ssh using an agent.

Actual: Vscode shows that everything failed from an authentication failure, then, initiates the agent, but throws away the result. I'm using a custom agent from work that does fancy things with security keys.

VS Code version: Code - Insiders 1.45.0-insider (2225d77536d12fea2eda04930f431a5eb0930bba, 2020-04-09T09:22:11.706Z)
OS version: Windows_NT x64 10.0.18362
Fetching remote diagnostics for 'SSH' failed: Connecting with SSH timed out

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.75GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: Connecting with SSH timed out
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
debugger-for-chrome|msj|4.12.6

</details>

**Comment by roblourens** [comment]
Fixed in https://github.com/microsoft/vscode/commit/44c5185373d5f209cd6c0b5d29a216fb801da34e

I will try to get an Insiders release out today but I'm having other unrelated build issues.

**Comment by roblourens** [comment]
In the meantime, you can use vscode Stable

**Comment by roblourens** [comment]
Ok, I released an Insiders build that should fix this. Sorry!
