### ISSUE TITLE
File Permissions

### ISSUE THREAD

**Issue by brewea** [microsoft/vscode-remote-release#2735]
Issue Type: <b>Bug</b>

Unable to open file due to permissions

Unable to open 'CPSC1010': Unable to read file 'vscode-remote://wsl+ubuntu/mnt/c/Users/brewe/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/home/brewea/school/CPSC1010' (NoPermissions (FileSystemError): Error: EACCES: permission denied, stat '/mnt/c/Users/brewe/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/home/brewea/school/CPSC1010').

Extension version: 0.44.2
VS Code version: Code - Insiders 1.45.0-insider (44c5185373d5f209cd6c0b5d29a216fb801da34e, 2020-04-10T18:12:33.780Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|7.93GB (2.15GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|7.93GB (2.15GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
This looks like the file might have the wrong permissions. Were you able to solve this issue?

**Comment by brewea** [comment]
> This looks like the file might have the wrong permissions. Were you able to solve this issue?

Issue was solved with a reinstall. Not sure what caused the issue.
