### ISSUE TITLE
Avoid empty terminals on reconnect (Check remote and Update SSH_AUTH_SOCK)

### ISSUE THREAD

**Issue by dumbPy** [microsoft/vscode-remote-release#2737]
- VSCode Version: 1.43.2
- Local OS Version: Ubuntu 18.04.2
- Remote OS Version: Ubuntu 18.04.2
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. On Connection drop and reconnection

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

### Bug/Feature Request?
Every time the  network outs for a few second and the vscode reconnects, it leaves 2 extra non functional terminals called `Check remote` and `Update SSH_AUTH_SOCK`  
Since my connection is quite shaky, I end up having 100+ of these useless (to me) terminal in 24 hrs, within which my useful terminals are scattered.

If they are essential for the remote connection to work, may be moving them to `Output` tab of the minibuffer instead of the `Terminal` tab, would be great.

![screenshot of the terminals](https://ibin.co/5IkvvuvPCziM.png)

**Comment by roblourens** [comment]
See https://github.com/microsoft/vscode-remote-release/issues/1760, make sure you have the latest version of VS Code and the Python extension.
