### ISSUE TITLE
Same folder with different cases are treated as different folders on Windows Host

### ISSUE THREAD

**Issue by sunliangqin** [microsoft/vscode-remote-release#2738]
![image](https://user-images.githubusercontent.com/211268/79052062-a6d7a180-7be8-11ea-8c06-feac158ab8c6.png)

Windows file system is case insensitive. The two paths above are actually pointing to the same folder. Ideally we should only list one of them.

**Comment by roblourens** [comment]
This is coming from vscode, it's out of the extension's hands. But this summer and also the past month there has been more work to normalize these in vscode.
