### ISSUE TITLE
PPK Invalid format , Windows 10

### ISSUE THREAD

**Issue by jinyeng** [microsoft/vscode-remote-release#2739]
I am trying remote-ssh on windows 10 VS Code and pulling out my hair with issues one after other. Now I am stuck at following. Using same key I am able to login via multiple ssh clients. Windows 10 is using OpenSSH. 

![image](https://user-images.githubusercontent.com/58823520/79058133-eaa5c780-7c37-11ea-8d8a-cd3ee07bbab7.png)

![image](https://user-images.githubusercontent.com/58823520/79058147-10cb6780-7c38-11ea-9ba8-99162d9b4fb8.png)

**Comment by roblourens** [comment]
https://code.visualstudio.com/docs/remote/troubleshooting#_reusing-a-key-generated-in-puttygen
