### ISSUE TITLE
remote container-try an example: Docker returned an error. make sure the docker daemon is runing

### ISSUE THREAD

**Issue by sisrfeng** [microsoft/vscode-remote-release#2740]
- VSCode Version:  the latest
- Local OS Version: win 10
- Remote OS Version: ubuntu 16.04 LTS
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/53520949/79065308-edf58d80-7ce1-11ea-9515-f1e8b8c73faf.png)
![image](https://user-images.githubusercontent.com/53520949/79065310-f3eb6e80-7ce1-11ea-9b0f-85a034f0fed7.png)
![image](https://user-images.githubusercontent.com/53520949/79065366-6b210280-7ce2-11ea-8b06-89c944ba9017.png)

2.it seems that my problem is different from https://github.com/microsoft/vscode-remote-release/issues/975  

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
What do you get for `docker info` in a terminal?

**Comment by chrmarti** [comment]
Could you also check what is in the console? (`Help` > `Toggle Developer Tools`)

**Comment by sisrfeng** [comment]
many thanks!

local:
PS C:\Users\noway> docker info
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 19.03.8

Remote:

docker info
Client:
 Debug Mode: false

Server:
 Containers: 53
  Running: 2
  Paused: 0
  Stopped: 51
 Images: 78
 Server Version: 19.03.5

May I have your email? There remain other information, but I' m afraid that there are some private things.

**Comment by chrmarti** [comment]
Could you also check what is in the console? (`Help` > `Toggle Developer Tools`)

There should be an error object, it would be interesting what is in there. Hopefully that comes with no private information.

**Comment by sisrfeng** [comment]
thanks ！

无法读取文件 means : can not read file
出现未知错误。有关详细信息，请参阅日志 means: An unknown error occur.For more information, please refer to the log

![image](https://user-images.githubusercontent.com/53520949/79218884-cf2efc80-7e83-11ea-9826-a248dd3924fd.png)
![image](https://user-images.githubusercontent.com/53520949/79218925-dfdf7280-7e83-11ea-8901-a81fffeea48d.png)

**Comment by sisrfeng** [comment]
docker info
Server:
 Containers: 53
  Running: 2
  Paused: 0
  Stopped: 51
 Images: 78
 Server Version: 19.03.5
 Storage Driver: aufs
  Root Dir: /var/lib/docker/aufs
  Backing Filesystem: extfs
  Dirs: 309
  Dirperm1 Supported: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 
Kernel Version: 4.15.0-76-generic
 Operating System: Ubuntu 16.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 125.8GiB
 Name: ubuntu
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: the aufs storage-driver is deprecated, and will be removed in a future release.

The following is hidden:
Username: 
 Registry:
 Labels:
 Experimental: 
 Insecure Registries:

**Comment by chrmarti** [comment]
Could you scroll to the top of the console and attach what is there? The first few errors are the most relevant.

**Comment by sisrfeng** [comment]
![image](https://user-images.githubusercontent.com/53520949/79231990-808c5d00-7e99-11ea-8450-10cd130ed195.png)
![image](https://user-images.githubusercontent.com/53520949/79232037-94d05a00-7e99-11ea-869b-92a76c1fea96.png)
![image](https://user-images.githubusercontent.com/53520949/79232114-add90b00-7e99-11ea-818b-580b5ff549ae.png)
![image](https://user-images.githubusercontent.com/53520949/79232123-b0d3fb80-7e99-11ea-84a3-7740ee4e05ce.png)
![image](https://user-images.githubusercontent.com/53520949/79232130-b29dbf00-7e99-11ea-892b-158e0d95c704.png)

**Comment by sisrfeng** [comment]
Do I need to provide more information?
Thanks!

**Comment by chrmarti** [comment]
`docker info` failed. Could you run that from the command line to see if it works there?

**Comment by sisrfeng** [comment]
thanks!
![image](https://user-images.githubusercontent.com/53520949/79960371-e68b6c80-84b7-11ea-9ba9-6d638ea12076.png)
![image](https://user-images.githubusercontent.com/53520949/79960388-edb27a80-84b7-11ea-921c-b2c097333616.png)

![image](https://user-images.githubusercontent.com/53520949/79960166-aaf0a280-84b7-11ea-9273-9c23db9de4bd.png)

![image](https://user-images.githubusercontent.com/53520949/79960126-9dd3b380-84b7-11ea-848a-03d51d0597de.png)

**Comment by chrmarti** [comment]
What do you get when you run `docker info` from a terminal?

**Comment by sisrfeng** [comment]
in mobaxterm:

:~$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 55
  Running: 1
  Paused: 0
  Stopped: 54
 Images: 79
 Server Version: 19.03.5
 Storage Driver: aufs
  Root Dir: /var/lib/docker/aufs
  Backing Filesystem: extfs
  Dirs: 314
  Dirperm1 Supported: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-76-generic
 Operating System: Ubuntu 16.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 125.8GiB
 Name: ubuntu
 ID: Q35Z:LIWA:FW5U:FPDO:FX2P:4OYO:YWOQ:YN2R:ZNBX:ITWC:YAVY:BIS3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: goodpen
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: the aufs storage-driver is deprecated, and will be removed in a future release.

**Comment by sisrfeng** [comment]
in vscode terminal( ssh to remote):
@ubuntu ~]$ docker info                                                      
Client:
 Debug Mode: false

Server:
 Containers: 55
  Running: 1
  Paused: 0
  Stopped: 54
 Images: 79
 Server Version: 19.03.5
 Storage Driver: aufs
  Root Dir: /var/lib/docker/aufs
  Backing Filesystem: extfs
  Dirs: 314
  Dirperm1 Supported: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-76-generic
 Operating System: Ubuntu 16.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 125.8GiB
 Name: ubuntu
 ID: Q35Z:LIWA:FW5U:FPDO:FX2P:4OYO:YWOQ:YN2R:ZNBX:ITWC:YAVY:BIS3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: goodpen
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: the aufs storage-driver is deprecated, and will be removed in a future release.

**Comment by chrmarti** [comment]
What's the exit code of `docker info`? (Run `echo $?` right after running `docker info`.)

**Comment by sisrfeng** [comment]
(base) name@ubuntu:/$ echo $?
0

**Comment by sisrfeng** [comment]
DO I need to provide more information？ thx

**Comment by chrmarti** [comment]
I have improved logging for the next version (0.118.0). We need to retry with that. Thanks!

**Comment by Sir-hennihau** [comment]
I know you are using windows, but anyways I wanna drop this here.

I installed docker from snap repositories and got the same error. I could resolve it by installing from the official docker repositories. Did you maybe install from an Appstore or something similar, @sisrfeng?.

Somewhere the systemlinks didn't work properly for me.

**Comment by chrmarti** [comment]
@sisrfeng Is this still an issue?

**Comment by zingdle** [comment]
@chrisdias Same issue here. I'm using `0.134.0` to run a container on a remote host.

I tried both but none worked:

```
{
  // "docker.host":"tcp://localhost:23750"
  "docker.host": "ssh://user@ip"
}
```

Debug console: `Command failed: docker version --format {{.Server.Version}}`. There's no more logging. However the remote host and local host can run this command without error return code.   

Interestingly, the same config works on my `Ubuntu 20.04` on `WSL2`, but failed with `Ubuntu 20.04` on bare machine.

**Comment by chrmarti** [comment]
@zingdle Could you check what is in the Remote-Containers log? (`F1` > `Remote-Container: Show Log`)

**Comment by zingdle** [comment]
@chrmarti  Sorry for my late response. It says

```
[257314 ms] Start: Run: docker version --format {{.Server.Version}}
[257355 ms] proxy: unknown scheme: socks
```

I checked `.docker/config.json` on both remote and local machine but neither set socks proxy.

**Comment by chrmarti** [comment]
@zingdle Do you have `HTTP_PROXY` or `HTTPS_PROXY` variables set?

**Comment by zingdle** [comment]
@chrmarti Thanks! Unset those variables works for me. 

But that only worked for me when using `tcp://localhost:23750` but it hangs when using `ssh://user@ip`. Maybe I'll open another issue to track the problem.

**Comment by chrmarti** [comment]
Sounds good. I'll close this issue here as it has several discussions and all have kind of ended. Please open new issues for each remaining issue. Thanks.

**Comment by zingdle** [comment]
@PavelSosin-320 I'm following [this](https://code.visualstudio.com/docs/remote/containers-advanced#_connect-using-vs-code-settings-or-local-environment-variables) to create and connect to a remote dev container. 

> It's clearly stated that the only secure connection option is TLS 1+!

I can't find related document so could you please let me know?

Further discussion is here: https://github.com/microsoft/vscode-remote-release/issues/3626
