### ISSUE TITLE
Local server download doesn't work for win10 ia32

### ISSUE THREAD

**Issue by villelahdenvuo** [microsoft/vscode-remote-release#2741]
Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T08:23:56.137Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Remote OS Version: Windows 10 Pro 1909 (ia32)
Remote Extension/Connection Type: SSH
Steps to Reproduce: Connect to Remote

Does this issue occur when you try this locally?: No

<details>
<summary>Logs</summary>

```
> 4cbd723b8b8b%%1%%
[15:19:05.400] > Failed to download & extract vscode-server. - Not Found
> Trigger client server download
> 4cbd723b8b8b:trigger_server_download
> platform==windows==
> vscodeArch==ia32==
> destFolder==C:\Users\xxx\.vscode-server\bin\2aae1f26c72891c399f860409176fe435a154b13==
> 4cbd723b8b8b:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for C:\Users\xxx\.vscode-server\bin\2aae1f26c72891c399f860409176fe435a154b13\vscode-scp-done.flag and vscode-server.zip to exist
[15:19:05.400] Got malformed request to download on client, invalid arch: undefined
[15:19:05.401] Resolver error: Client-side server download failed
```

</details>

I checked the script and it seems to try to download this file: https://update.code.visualstudio.com/commit:2aae1f26c72891c399f860409176fe435a154b13/server-win32-ia32/stable which returns Not Found. I noticed that the x64 variant download works correctly, so it seems like the ia32 build is missing, can I get it from anywhere or can I use some older build?

**Comment by aleybe** [comment]
Also have this issue.  Pretty much exactly the same as above except remote OS is Win Server 2016

**Comment by aleybe** [comment]
Also have this issue.  Pretty much exactly the same as above except remote OS is Win Server 2016

**Comment by monody1** [comment]
I have the same issue and remote OS is x64(win10 pro) but the log show "vscodeArch==ia32=="

**Comment by vatshat** [comment]
Same here I've got Windows 32 bit on virtualbox. Any update please?

**Comment by monody1** [comment]
> Same here I've got Windows 32 bit on virtualbox. Any update please?

I figured it out by change to the original ssh by win10

**Comment by DeadRabbits307** [comment]
any update?

**Comment by roblourens** [comment]
Sorry for the slow response. We no longer have a 32-bit windows server. But it sounds like maybe there was a case where 32-bit was incorrectly detected when connecting to a 64-bit windows remote, is that the case for anyone?

**Comment by villelahdenvuo** [comment]
Mine was an old Windows tablet that I don't own anymore. If someone has issues with the architecture detection, they can open a new issue. I'm closing this as won't fix.
