### ISSUE TITLE
dotnet shell command not found

### ISSUE THREAD

**Issue by SynergiAios** [microsoft/vscode-remote-release#2747]
- VSCode Version: 1.44.0
- Local OS Version: MacOS Catalina 10.15.4
- Remote OS Version: Windows 10 Pro 1909 build 18363.720
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
_Maybe just on my system_
1. run Debug -> .Net Core Launch (console) 

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No
Does this issue occur on nightly build?: Yes

**### ERROR**
```
> Executing task: c:/Users/flori/repos/qasphalt-client/dotnet build C:\Users\flori\repos\qasphalt-client/src/Client/Asphalt.Client/Asphalt.Client.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <

The terminal shell path "c:/Users/flori/repos/qasphalt-client/dotnet" does not exist

Terminal will be reused by tasks, press any key to close it.
```

So the issue occurs when you try to use the vscode debugger. The launch.json wants to execute the pretask build. The task requires dotnet.exe. The problem is, it can't find the dotnet.exe and thus fails. I provided a ton of information as the weird thing is, that I can show using procmon, that the process actually found dotnet.exe where it should be. But it continued searching for it. Please check all the provided Informations as this seems extremely weird to me.

[dotnet_info.txt](https://github.com/microsoft/vscode-remote-release/files/4469312/dotnet_info.txt)

Here the launch.json & tasks.json used
[json_files.zip](https://github.com/microsoft/vscode-remote-release/files/4469323/json_files.zip)

Here the export of the captured procmon events for node.exe, rg.exe, dotnet.exe & sshd.exe
[procmon_events.zip](https://github.com/microsoft/vscode-remote-release/files/4469324/procmon_events.zip)

Version for LocalOS, RemoteOS, VSCode & Remote SSH Plugin
<img width="556" alt="local_OS_Info" src="https://user-images.githubusercontent.com/10873296/79117339-2ac98f00-7d8b-11ea-8901-189f97c11e36.png">
<img width="474" alt="remote_os_info" src="https://user-images.githubusercontent.com/10873296/79117354-35842400-7d8b-11ea-9d26-fe1f60ad4921.png">
<img width="419" alt="vscode_info" src="https://user-images.githubusercontent.com/10873296/79117393-49c82100-7d8b-11ea-8030-84508c74a8c4.png">
<img width="1083" alt="vscode_remote_plugin_info" src="https://user-images.githubusercontent.com/10873296/79117399-4c2a7b00-7d8b-11ea-8c43-49c23e532717.png">

Path variable of windows remote os
<img width="619" alt="path_var" src="https://user-images.githubusercontent.com/10873296/79117370-3cab3200-7d8b-11ea-8b66-60dffd1242ad.png">

Image of procmon event with SUCCESS state for the dotnet.exe where it is located
<img width="376" alt="SS_successEntry_dotnet" src="https://user-images.githubusercontent.com/10873296/79117412-53518900-7d8b-11ea-92e3-7b0055c46b92.png">

You can clearly see with procmon that Node.exe received a SUCCESS when trying to check for dotnet.exe. But still it continued to search everywhere else.

Tried a clean install of VSCode, the plugins, dotnet sdk, ... on both OS. Nothing changed. Also tested with insider build - still the same. 

**To calrify this only happens when using vscode remote. When testing this locally on the remote machine it works just fine.**

**Comment by SynergiAios** [comment]
Here another screenshot of showing, that when running dotnet run in the remote console it works, but when using the vscode debugger it doesn't work, as it can't find the dotnet shell command
<img width="1792" alt="Screenshot 2020-04-14 at 01 54 47" src="https://user-images.githubusercontent.com/10873296/79171738-25079400-7df3-11ea-9bd4-4c7cda712838.png">

**Comment by SynergiAios** [comment]
And I tried putting the dotnet.exe into a different place and added this to the system path variable. Here is a screenshot of procmon where you can see two SUCCESS on different locations for the dotnet.exe, but node.exe continues searching for it. What is going on here?
![Capture](https://user-images.githubusercontent.com/10873296/79173209-2a66dd80-7df7-11ea-8873-8a8e21eea928.PNG)

**Comment by SynergiAios** [comment]
I have aquired more intel. The issue only occurs, if I connect with my mac. to my windows host. I tried everything, setting "Local Server" to off and making sure the remoteSSH.platform is set to "windows" for the host. Everything double checked. Also reinstalled VSCode on my mac and removed everything. No Success. Everytime I try it with my mac, it fails, because it cannot find the dotnet shell command. Anyone any Info to this, why I this happens when connecting remote via mac to windows host?

**Comment by SynergiAios** [comment]
What Settings or something can I check/change to get this running? Anyone?

**Comment by diegomesata** [comment]
Hello, I have the same problem with your same configuration, I found I workaround:

The error I got is: 

The terminal shell path "c:/Projects/MyProject/dotnet" does not exist

I think is a problem with PowerShell, that can't run the dotnet command in that way, I created a .bat called dotnetcmd.bat in c:\Projects\MyProject\

dotnet %*

The in the taks.json file I changed the command for my dotnetcmd.bat

 "tasks": [
        {
            "label": "build",
            "command": "dotnetcmd.bat",
..

I now it build fine!

**Comment by jethas-bennettjones** [comment]
I'm having this problem as well, but I'm connecting from a Windows host to a Windows host, so it might not be isolated to Mac hosts only.

**Comment by roblourens** [comment]
Sorry for the slow response. I know some things with tasks have changed in the meantime, is this still an issue?
