### ISSUE TITLE
VS Code Server for WSL closed unexpectedly.

### ISSUE THREAD

**Issue by osioke** [microsoft/vscode-remote-release#2748]
Version: 1.44.0 (user setup)
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-07T23:31:18.860Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

Windows OS: Windows_NT x64 10.0.19603

Remote connection: WSL2

Linux Distro: Ubuntu 18.04.4 LTS

Steps to reproduce:
My WSL integration to VS Code worked seamlessly before, so using just steps may not capture everything.

I tried to open a folder from my Ubuntu WSL2 terminal which usually works, but instead of loading the folder, I get the message:

`Command 'code' not found, did you mean: ...`

On opening VS Code, I get the error:

```
VS Code Server for WSL closed unexpectedly. 
Check WSL terminal for more details.
```

Checking the VS Code terminal, I see:

```
[2020-04-13 11:48:07.697] sh: 1: /mnt/c/Users/Osioke/.vscode/extensions/ms-vscode-remote.remote-wsl-0.44.2/scripts/wslServer.sh: Input/output error
[2020-04-13 11:48:07.721] VS Code Server for WSL closed unexpectedly.
```

I expected typing `code <the folder name>` to open the folder in VS Code, and I expected opening VS Code to load my files and folders in my WSL distro. It usually does this, not sure what has changed now.

**Comment by toshimaru0123** [comment]
I resolved that by applying Windows and VS Code update.

Version: 1.44.2 (system setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by egamma** [comment]
@osioke can you still reproduce the problem with the setup described here https://github.com/microsoft/vscode-remote-release/issues/2748#issuecomment-616210650

**Comment by osioke** [comment]
@egamma after the latest update to Windows and VSCode, this is resolved. Thanks!

Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19608
