### ISSUE TITLE
Update Alpine error message for opening VS Code

### ISSUE THREAD

**Issue by mattwojo** [microsoft/vscode-remote-release#2750]
- VSCode Version: 1.41.1
- Local OS Version: Windows_NT x64 10.0.19546
- Remote OS Version: 0.41.9
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Install Alpine distribution (after WSL is enabled)
2. Try to open VS Code from the Alpine distro command line, using: `code .`

You will receive this error message:

> MININT-LOBGCR8:~/alpine-docs/alpine-github# code .
> WARNING: Ignoring APKINDEX.70f61090.tar.gz: No such file or directory
> WARNING: Ignoring APKINDEX.ca2fea5b.tar.gz: No such file or directory
> libstdc++ is required to run the VSCode Server:
> Please open a wsl shell as root ('wsl -d Alpine -u root') and run 'apk update && apk add libstdc++'

This error message should be updated.

Please change the error message to: 
"From the Alpine shell root (use `cd ~` to open the root directory), run `apk update && apk add libstdc++`

The current error message asks someone to use the command 'wsl -d Alpine -u root' which will not work from the Alpine distro (and also doesn't open Alpine root from PowerShell). Please remove that part as it's not necessary and confuses the instructions which are otherwise pretty simple and straightforward.

Thank you!

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by mattwojo** [comment]
@aeschli Is this something that you can help with?

**Comment by aeschli** [comment]
@mattwojo Thanks, I made the change (it's not open source)

**Comment by mattwojo** [comment]
Thanks @aeschli ! :)
