### ISSUE TITLE
vs code unable to detect venv using remote-ssh extension

### ISSUE THREAD

**Issue by rADikal8e7** [microsoft/vscode-remote-release#2751]
- VSCode Version: Version: 1.45.0-insider
- Local OS Version: OS: Darwin x64 19.4.0
- Remote OS Version: CentOS Linux release 7.7.1908
- Remote Extension/Connection Type: SSH ms-vscode-remote.remote-ssh Version: 0.51.0
- Python Extension version: Name: Python Id: ms-python.python Version: 2020.3.71659

Steps to Reproduce:

1. Connect to remote server using remote-ssh extension
2. Create a venv in a location that is **not** the workspace folder.
3. Set the venv path in the workspace settings file.
```
	"settings": {
		"python.pythonPath": "/home/py3-venv/bin/python",
		"python.venvPath": "/home/py3-venv"
```
4. The venv isnt listed when choosing an interpreter.

Workaround tried:
1. Tried to restart the vscode insiders.
2. set the venvpath and python path one at a time and both
3. developer tools console output doesnt show venv

<img width="609" alt="image" src="https://user-images.githubusercontent.com/6048537/79163222-80a23500-7d93-11ea-8ea5-24100a004ea4.png">

4. In the above snapshot the venv is based on py3.8 but i dont see it getting activated if i select it leading me to believe its only choosing that version from local bin not the venv folder
5. Tried initializing a new integrated terminal to see if it gets activated in that window but no luck.

Let me know what additional logs are required to triage this.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: NA

**Comment by rADikal8e7** [comment]
Could this be an issue with the python extension itself? https://github.com/microsoft/vscode-python/issues/11136

**Comment by rADikal8e7** [comment]
Figured out the workaround.
It only seems to honor the `python.Path` in `settings.json` in remote workspace folder rather than the env setting in `workspace settings.json`

As soon as i set the following in `settings.json` in `.vscode folder` that is created in the remote folder the venv could be selected in the interpreter.

```
{
    "python.pythonPath": "/home/py3-venv"
}
```

I feel the behavior is contrary to the expectations so i am going to leave this issue open for better clarification.

**Comment by scalavision** [comment]
I agree this is incredibly confusing, seems I am not able to set the python path for the remote python project at all. I have my venv outside of the workspace ..

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
