### ISSUE TITLE
Support read-only root filesystem

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2755]
Nice job! Can we also support the scenario where read-only root filesystems are enabled?

_Originally posted by @erihanse in https://github.com/microsoft/vscode-remote-release/issues/12#issuecomment-612280555_

**Comment by chrmarti** [comment]
@erihanse We currently write to the home folder and the tmp folder. Is that not possible in your setup?

**Comment by erihanse** [comment]
We often don't mount the home folder, but mount a tmp-folder. I'm not sure what a good solution for this would look like, but is it possible to specify where the extension writes to?

**Comment by chrmarti** [comment]
We look up the tmp folder with `$TMP` I think (using Node.js' `os.tmpdir()`) and the home folder by inspecting `/etc/passwd` for the user we connect with. You could try setting that to a valid path for that user.
