### ISSUE TITLE
Improve logging when connection to Docker daemon fails

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2758]
Though I have now an additional issue: while the Docker extension can see all containers on the remote machine, the Remote - Containers gets stuck on trying to find them:
```
CommandService#executeCommand remote-containers.explorerTargetsRefresh
MainThreadTreeViews#$refresh targetsContainers undefined
```

Versions:
```
Id: ms-vscode-remote.remote-containers
Version: 0.112.0
```
```
Id: ms-azuretools.vscode-docker
Version: 1.0.0
```
```
Version: 1.45.0-insider (user setup)
Commit: 4f05de82a75569601bc2dc894023383b4ce1c2c0
Date: 2020-04-13T17:53:50.995Z
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

_Originally posted by @PALuczak in https://github.com/microsoft/vscode-remote-release/issues/2080#issuecomment-613266534_

**Comment by chrmarti** [comment]
@PALuczak What do you set the Docker Host setting to?

**Comment by PALuczak** [comment]
In my config I have:
```
"docker.host": "ssh://username@192.168.11.111"
```
(username and IP replaced with equivalent placeholders)

SSH is configured for key-based authentication, so no password is required for login.

**Comment by chrmarti** [comment]
Could you attach a screenshot of when it gets stuck? And could you check if there is anything in the console? (`Help` > `Toggle Developer Console`)

**Comment by PALuczak** [comment]
![image](https://user-images.githubusercontent.com/12057745/79223368-7e0a1300-7e59-11ea-9d0e-2e1e6e437a1a.png)

The `MainThreadTreeViews#$refresh targetsContainers undefined` shows up if I press refresh in the containers window:
 
![image](https://user-images.githubusercontent.com/12057745/79223615-f670d400-7e59-11ea-85a1-c86da29aa894.png)

**Comment by chrmarti** [comment]
There is this blue line under the Containers section header indicating that it is still loading the list of containers and their status. 🤔

Does `F1` > `Remote-Containers: Attach to Running Container...` work?

**Comment by PALuczak** [comment]
> 
> 
> There is this blue line under the Containers section header indicating that it is still loading the list of containers and their status. 🤔

And if I leave it alone for 4 hours it will still be there.

Running `Remote-Containers: Attach to Running Container` shows up on the extension host trace, but as far as I can see that is all it does.

**Comment by chrmarti** [comment]
What do you get in PowerShell for:
```powershell
$env:DOCKER_HOST='ssh://username@192.168.11.111'
docker version
```
(Mainly checking connectivity.)

**Comment by PALuczak** [comment]
I have figured out the issue: since I have multiple SSH keys the `docker.host` should be set to `ssh://username@alias` based on the entries in `~/.ssh/config` otherwise, it tries to use the wrong key for authentication. It even works without docker running on the local machine.

Thank you for all the time spent working on this issue (and #2080)!

**Comment by chrmarti** [comment]
Glad you figured this out. We need to improve logging for this and similar cases.
