### ISSUE TITLE
go to define lost when recover from sleep with remote-wsl

### ISSUE THREAD

**Issue by lubocheng** [microsoft/vscode-remote-release#2759]
- VSCode Version: 1.44.0
- Local OS Version: Microsoft Windows [版本 10.0.19041.173]
- Remote OS Version: Ubuntu 18.04 with wsl2
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. coding with remote-wsl, everything seems ok
2. go to lunch,computer sleep after several minutes
3. recover from sleep and continue to coding, find something wrong with go to define etc. seems that the connection is disconnected between me and files  
4. there is only a close option says"Close Remote Connection", but where is the reconnect option? only you can do is reopen remote folders currently

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Hope there are some ways to avoid this annoying condition.

**Comment by tanhakabir** [comment]
@lubocheng are you still seeing this issue?
