### ISSUE TITLE
Local environment variables not available when used in docker-compose

### ISSUE THREAD

**Issue by thomas-lucas1985** [microsoft/vscode-remote-release#2764]
- VSCode Version: 1,44
- Local OS Version: Windows 10 Enterprise V1909
- Remote OS Version:
- Remote Extension/Connection Type: Docker

Hi

We are using a docker development container for building an Angular project. The docker-compose file is defined in devcontainer.json.

In our docker-compose file, we are mounting some volumes. For one of these, we use a windows environment variable to refer to the local user directory of the host e.g.
volumes:
  - type: bind
     source: $HOME\file
    target: directory/in/container/file

Until our recent update to vscode v1.44, this was working fine, but now after the update we get following warning when trying to connect to the dev container.
WARNING: The HOME variable is not set. Defaulting to a blank string.
Off course, this results in an error of the container not being built.

The issue doesn't seem to be related to Docker, because if I manualy start the configuration via docker-compose, no issues/warnings are filed and all files/folder are correctly mounted.

Also when downgrading to vscode 1.43, the issue doesn't occur.

Maybe I need to add some extra configuration after the upgrade? However I couldn't find anything related to this.
Otherwise probably a bug?

Kind regards
Thomas
![remote containers error](https://user-images.githubusercontent.com/47103076/79310544-6e8fd600-7efc-11ea-87a6-63e48652283d.png)
![docker-compose-extract](https://user-images.githubusercontent.com/47103076/79310555-72bbf380-7efc-11ea-8195-b9fd33d45845.png)

**Comment by chrmarti** [comment]
Please use `$USERPROFILE` instead. We set `HOME` in the past, but that caused other issues (#2046).
