### ISSUE TITLE
eslint rules: enable "no-throw-literal" rule

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#2767]
VS Code has enabled the "no-throw-literal" rule, suggest to do the same in remote-containers. There are a handful of violations in the code.

The rule can be enabled here: https://github.com/microsoft/vscode-remote-containers/blob/316736c305066d3248249a26529fa3691c3a85b8/.eslintrc.js#L39

**Comment by chrmarti** [comment]
Wrapping the three cases in `Promise.reject` for now to not block enabling of the rule.
