### ISSUE TITLE
Remote host keep asking for password while logging in with key

### ISSUE THREAD

**Issue by dvirginz** [microsoft/vscode-remote-release#2768]
The steps, following the Tips and Tricks VS code [post](https://code.visualstudio.com/docs/remote/troubleshooting#_reusing-a-key-generated-in-puttygen):
1) create key with Putty KeyGen.
2) converted the private key to openssh
3)saved the keys
4) In the local machine, in `C:\Users\user\.ssh\config` I added
```
Host station_name
  HostName host_name
  User my_name
  IdentityFile C:\Users\user\.ssh\config\privateputty
```
5)In PowerShell typed:
` $USER_AT_HOST="my_name@host_name"`
` $PUBKEYPATH="$HOME\.ssh\publicputty"`
`$pubKey=(Get-Content "$PUBKEYPATH" | Out-String); ssh "$USER_AT_HOST" "mkdir -p ~/.ssh && chmod 700 ~/.ssh && echo '${pubKey}' >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys"`

Verified that the key copied to the remote server.
But still, everytime I connect to the machine, It asks for a password again.

**Comment by roblourens** [comment]
We just expose whatever auth prompts ssh gives us. There must be something that isn't set up right.
