### ISSUE TITLE
Searching for files by path broken

### ISSUE THREAD

**Issue by svalentin** [microsoft/vscode-remote-release#2770]
- VSCode Version: 1.44.1
- Local OS Version: Microsoft Windows NT 10.0.18363.0
- Remote OS Version: Ubuntu 16.04.6 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Use a Windows OS with Remote SSH extension connected to a Linux machine.
2. Use Control+P to start searching for a file
3. Search for a file by partial path with more than 1 folder in the path. Example: If file is in X/Y/Z/file.py search for "Y/Z/file.py" or even the full "X/Y/Z/file.py" path.

Note: searching for "Z/file.py" works. It's only when going back more than 1 folder that it stop working. Searching for "Y/Z/" also doesn't produce any result when it should find all the files in the folder.

Does this issue occur when you try this locally?: No
On a local workspace, searching for "Y\Z\file.py" works as expected. (Have to use backslashes since it's now a Windows path)

Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by svalentin** [comment]
Reinstalled VSCode 1.43.2 and this works again. Looks like version 1.44 caused something to break here.

**Comment by AaronFriel** [comment]
I encountered this issue as well and it has mysteriously started working again, sans me reinstalling anything.

**Comment by svalentin** [comment]
Sorry, your issue seems different. In your issue you mentioned it didn't work at all except for recently opened files. For me, Control P works normally except when searching for file paths with more than 2 directories.
That said, yes, I still have this issue with VSCode Version 1.44.1 and Remote Development SSH connected to a Linux box

**Comment by roblourens** [comment]
I think this issue with slashes has been fixed - can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

Was https://github.com/microsoft/vscode/issues/94871

**Comment by svalentin** [comment]
That looks like the same issue I opened here. Thanks! Will test on Monday.

**Comment by svalentin** [comment]
Can confirm this bug is fixed in vscode insiders version 1.45.0-insider

**Comment by roblourens** [comment]
Thanks!
