### ISSUE TITLE
Cannot review PR in Dev Container

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-remote-release#2771]
```
Version: 1.45.0-insider
Commit: 92ff20ac39c7507fdf4164e2bedfdfb700805fe1
Date: 2020-04-14T18:06:32.175Z
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0
```

Using the GH PR extension to review a PR in a Dev Container

Right click on PR, choose "Checkout Pull Request in Dev Container"
Got a quick pick to choose a Dev Container type (i believe)
Not sure why I have to pick something... as I think about it, some time passes (maybe 30sec?) and I get this error:

![image](https://user-images.githubusercontent.com/1487073/79393291-e58f9380-7f29-11ea-9e14-21e4cc62da6f.png)

I start over and now I get this error:

![image](https://user-images.githubusercontent.com/1487073/79393577-7ebeaa00-7f2a-11ea-8f76-533d44ad63f5.png)

I think maybe I have a container running that is broke, and that needs to be shutdown. I check using the Docker extension, but no containers are running.  

I try the scenario again so I can see what "More Actions" does, which gives me this:

![image](https://user-images.githubusercontent.com/1487073/79393605-8e3df300-7f2a-11ea-9230-78593bc8ae9c.png)

- Reload Windows puts me back in the same problem
- Open Repository sends me to the repo in the browser (doesn't fix the problem)
- Open Recent gives me a quick pick of recent workspaces (doesn't fix the problem)
- Open Documentation sends me to a wall of text about Docker Desktop?

So... I give up and go local.

**Comment by Chuxel** [comment]
@chrisdias Yeah, this may be related to https://github.com/microsoft/vscode-remote-release/issues/2726 if you ended up with a bad config somehow. I remember that happened with the samples previously. The same situation exists with custom Dockerfile support in VSO, so a similar solution is being discussed there.

**Comment by egamma** [comment]
@chrisdias 

>Not sure why I have to pick something... as I think about it, some time passes (maybe 30sec?) and I get this error

Since your reviewing the PR in a dev container the repository needs to contain a definition for the used dev container. 

You have not picked a dev container configuration and the current error message is scary and needs to be improved plus there needs to be a way to inspect the failed container.

**Comment by egamma** [comment]
Handle the case where a user does not pick a dev container configuration when one does not exist gracefully.

To verify:
- Remote-Containers: Open Repository in Container
- Enter a repository container without a dev container definition
- Cancel when prompted for selecting a container definition

You should get an error dialog with the option to try again. When you select cancel then the window should be reset.

**Comment by aeschli** [comment]
I don't get a prompt for the dev container. I filed https://github.com/microsoft/vscode-remote-release/issues/2891

**Comment by aeschli** [comment]
Marking as verified as there is no longer the strange error, just the error to try again
