### ISSUE TITLE
Download a tar/zip file over SSH isn't working

### ISSUE THREAD

**Issue by LITDataScience** [microsoft/vscode-remote-release#2773]
Issue Type: <b>Bug</b>

Tried downloading a tar file, but it doesn't work after downloaded. The file got corrupted maybe.

Extension version: 0.51.0
VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 5.3.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (20.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.24.142.90|
|OS|Linux x64 5.3.0-46-generic|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 4387)|
|Memory (System)|46.99GB (23.66GB free)|
|VM|0%|
</details>

**Comment by rzhao271** [comment]
Closing for now. @LITDataScience feel free to reply if this issue still applies to you on the latest version of VS Code (preferably Insiders edition).
It would probably also help if you provided which file it was, or whether it was on any tar file.
