### ISSUE TITLE
bash: fork: retry: Resource temporarily unavailable

### ISSUE THREAD

**Issue by gaozhidf** [microsoft/vscode-remote-release#2774]
- VSCode Version: 1.43.2
- Local OS Version: MacOS 10.15.4
![image](https://user-images.githubusercontent.com/5724898/79428302-8f3d5600-7ff8-11ea-9645-34d29650b131.png)
- Remote OS Version: Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. vscode created too much processes in my remote server, and make it resource temporarily unavailable
```
bash: fork: retry: Resource temporarily unavailable
bash: fork: retry: Resource temporarily unavailable
bash: fork: retry: Resource temporarily unavailable
bash: fork: retry: Resource temporarily unavailable
bash: fork: Resource temporarily unavailable
bash: wait_for: No record of process 2393
bash: fork: retry: Resource temporarily unavailable
bash: fork: retry: Resource temporarily unavailable
```
![image](https://user-images.githubusercontent.com/5724898/79427800-d70fad80-7ff7-11ea-847b-7a9daabe77b7.png)
![image](https://user-images.githubusercontent.com/5724898/79427853-e7c02380-7ff7-11ea-90e1-977035ac394b.png)

**Comment by roblourens** [comment]
If this is still an issue, please let me know and give some more details about what I can do to reproduce this.

**Comment by datenteiler** [comment]
Hi,

- VS Code 1.51.0
- openSUSE Tumbleweed Kernel 5.9
- Remote machine: Debian Linux 4.9.0-11-amd64
- Remote Extension/Connection Type: SSH 

I can confirm, it's still an issue:

Linux 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64
Last login: Sun Nov  8 15:50:04 2020 from 2a02:560:4a7c:ea00:2472:3199:806a:706e
-bash: fork: retry: Resource temporarily unavailable
-bash: fork: retry: Resource temporarily unavailable
-bash: fork: retry: Resource temporarily unavailable
-bash: fork: retry: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash-4.4$ 

The OS has limited my ability to "fork" and stops me creating new threads or processes on the remote machine. I am not and cannot become root on this server.

With VS Code:

Version: 1.51.0
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:16:10.374Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.1-1-default

**Comment by roblourens** [comment]
> The OS has limited my ability to "fork" and stops me creating new threads or processes on the remote machine.

Sorry I'm not sure what we can do about this, it sounds like an issue.
