### ISSUE TITLE
Port forwarding in Remote SSH is not working

### ISSUE THREAD

**Issue by lbogdan** [microsoft/vscode-remote-release#2776]
- VSCode Version: latest - **1.44.1 (user setup)**
- OS Version: **Windows_NT x64 10.0.18363**

### What were you trying to achieve?

Forward a port  in a Remote SSH session.

### How to reproduce?

Go to "Remote Explorer" pane, click on "+" / "Forward a port" in the "Forwarded Ports" section.

Alternatively, open Command Pane, search and select "Forward a Port", enter port number.

### What is the expected behavior?

You're prompted for the local and remote ports and the port forwarding is enabled.

### What is the observed behavior?

I get this error in the Developer Tools:

```
 ERR Cannot read property '1' of null: TypeError: Cannot read property '1' of null
	at /root/.vscode-server/bin/a9f8623ec050e5f0b44cc8ce8204a1455884749f/out/vs/server/remoteExtensionHostProcess.js:763:742
	at Array.map (<anonymous>)
	at e.getSockets (/root/.vscode-server/bin/a9f8623ec050e5f0b44cc8ce8204a1455884749f/out/vs/server/remoteExtensionHostProcess.js:763:652)
	at e.$findCandidatePorts (/root/.vscode-server/bin/a9f8623ec050e5f0b44cc8ce8204a1455884749f/out/vs/server/remoteExtensionHostProcess.js:763:295)
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
```
and nothing else happens.

Does this issue occur when all extensions are disabled?: Can't test, as Remote SSH is in itself an extension.

**Comment by lbogdan** [comment]
Because this is quite annoying for me, I did a bit of digging around what could cause this.

## Debugging

Looking at `$findCandidatePorts()` source code, it does an `exec`:

```js
          async $findCandidatePorts() {
          // ...
            const n = await new Promise((e) => {
                l.exec(
                  "ls -l /proc/[0-9]*/fd/[0-9]* | grep socket:",
                  (t, i, n) => {
                    e(i);
                  }
                );
              }),
```

, which stdout's is then sent to `getSockets`:

```js
          async $findCandidatePorts() {
          // ...
            const o = this.loadListeningPorts(t, i),
              a = this.getSockets(n).reduce(
                (e, t) => ((e[t.socket] = t), e),
                {}
              ),
```

, and `getSockets()` is:

```js
          getSockets(e) {
            return e
              .trim()
              .split("\n")
              .map((e) => {
                const t = /\/proc\/(\d+)\/fd\/\d+ -> socket:\[(\d+)\]/.exec(e);
                return { pid: parseInt(t[1], 10), socket: parseInt(t[2], 10) };
              });
          }
```

Running the `exec()`'d `ls -l /proc/[0-9]*/fd/[0-9]* | grep socket:` command from a shell, it actually returns an error:

```sh
$ ls -l /proc/[0-9]*/fd/[0-9]* | grep socket:
bash: /bin/ls: Argument list too long
```

, so stdout is empty (`""`), and because threre's no error handling, `"".split("\n")` returns `[""]`, the regex `.exec("")` returns `null`, and indexing that (`t[1]`) throws.

## Proposed Solution

First step would be properly handling the error case.

Now, the error is caused because the `/proc/[0-9]*/fd/[0-9]*` filename expansion returns too many matches. We can cheat a little, and replace that command with `ls -lR /proc/[0-9]*/fd | grep socket:`, the expansion would return less matches, and it ends up working on the same machine:

```sh
$ ls -lR /proc/[0-9]*/fd | grep socket: | head
lrwx------ 1 systemd-resolve systemd-journal 64 Apr 25 12:58 12 -> socket:[890147500]
lrwx------ 1 systemd-resolve systemd-journal 64 Apr 25 12:58 13 -> socket:[890147502]
[...]
$ ls -lR /proc/[0-9]*/fd | grep socket: | wc -l
62874
```

(note that this might still fail on machines with **lots** of processes, though - I had around 4000 processes on my machine)

**Comment by lbogdan** [comment]
Ping?

**Comment by alexr00** [comment]
Using `ls -lR /proc/[0-9]*/fd` instead of `ls -l /proc/[0-9]*/fd/[0-9]*` causes us to lose the pid, which is needed later. I will not make any further changes here for now.

If we find that many uses are hitting this issue with lots of process, I'll figure out how to support that better.

**Comment by tealeg** [comment]
@alexr00 can't you use ```lsof -U``` to do the same thing without globbing?

**Comment by alexr00** [comment]
Closing as the error case is fixed and there have not been further reports.
