### ISSUE TITLE
Search doesn't work after opening a workspace from a dev container

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-remote-release#278]
**Repo**

1. Clone https://github.com/Microsoft/vscode-extension-samples locally
1. Open the folder
1. Run the `Reopen in container` command. Select the node 8 container
1. Once the folder has been reopened in the container, go to the `samples.code-workspace` file
1. Click on the `open workspace` button in that file. The workspace should open (still inside the container)
1. Now try performing a file search

**bug**
Search fails. In the dev tools console, see the errors:

```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:238 [Extension Host] Error: spawn /root/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/node_modules/vscode-ripgrep/bin/rg ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
	at onErrorNT (internal/child_process.js:406:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
t.log @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:238
```

I talked with  @roblourens about this issue and we were not sure what was supposed to happen if you open a workspace this way or if this scenario is supposed to be supported

**Comment by egamma** [comment]
I'm now seeing this error when I perform a search

![image](https://user-images.githubusercontent.com/172399/57535117-dbd8d580-7341-11e9-928d-8d807f45c883.png)
