### ISSUE TITLE
Setting to turn off copying of .gitconfig

### ISSUE THREAD

**Issue by bkmeneguello** [microsoft/vscode-remote-release#2780]
- VSCode Version: 1.44.1
- Local OS Version: macOS 10.14.6
- Remote OS Version: Debian 10
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. set "remote.containers.gitCredentialHelperConfigLocation" to "none"
2. Launch a new container
3. ˜/.gitconfig should not be created/copied (I want a pristine configuration inside container)

Does this issue occur when you try this locally?: Not relevant
Does this issue occur when you try this locally and all extensions are disabled?: Not relevant

**Comment by damienrj** [comment]
We are also having a related issue where our local git isn't compatible with our remote and this overrides the gitconfig in the container.

**Comment by chrmarti** [comment]
`remote.containers.gitCredentialHelperConfigLocation` is about where the credentials helper should be registered. To address this issue we will need an additional setting.

**Comment by chrmarti** [comment]
Fixed with https://github.com/microsoft/vscode-remote-release/issues/2267.
