### ISSUE TITLE
Error when using Attach Visual Studio Code

### ISSUE THREAD

**Issue by BernierCR** [microsoft/vscode-remote-release#2781]
I tried to attach to a kubernetes pod, but get an error. Other features are working. I can show logs, ssh in, list files, etc. Attach is not working. All it says is: 

Error running command remote-containers.attachToK8sContainerFromViewlet: Command failed: kubectl get pod [POD_NAME] -o json --namespace [NAMESPACE]. This is likely caused by the extension that contributes remote-containers.attachToK8sContainerFromViewlet.

This isn't very informative. Can you help please? Thanks.

**Comment by ntextreme3** [comment]
I don't see any error when I click "Attach Visual Studio Code". Just nothing happens

**Comment by BernierCR** [comment]
OK, update. 

If i manually run the kubectl get pod part on WSL, the command works. However, afaik, kubernetes extension doesn't work on WSL. 

So I have to run it from windows. If I run this command manually in the terminal, I get a connection error. 

Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it. 

I don't know what that is about or who to report this too.

**Comment by Kuzbekov** [comment]
I confirm the same behaviour. It happens because this command does not respect kubeconfig that placed not on different place. As workaround, you can copy your kubeconfig to ~/.kube/config and that should help.

**Comment by BernierCR** [comment]
Hey, I no longer work on this project so can't help with this bug right now. I'm sorry. Hopefully be working again soon and help with more bugs again. On Oct 13, 2020 4:12 AM, Christof Marti <notifications@github.com> wrote:
Where is your kubeconfig and how does the Kubernetes extension discover it?

**Comment by chrmarti** [comment]
This definitely should be working. Let us know when you get back to it. Closing this issue for now since we don't have actionable information on it. Thanks.
