### ISSUE TITLE
Terminal Tab Context is lost

### ISSUE THREAD

**Issue by vinvinodk** [microsoft/vscode-remote-release#2782]
Hi Team,

I use Remote SSH Extenstion. When we use VSCode Terminal over the remote linux machine. The tabbing is not working inside the terminal context. (ie "ls /folder1/(press tab now)" is not listing folder names, instead it is switching to next vscode window).  It was working on previous releases but not working in the current version i m reporting. 

It is needed atleast in Terminal. I can see this latest release switches to next next windows but inside terminal Switching should be disabled atleast.

**Comment by Tyriar** [comment]
> instead it is switching to next vscode window

It sounds like you either have tab focus mode enabled or you have a custom keybinding set which is causing this behavior.

![image](https://user-images.githubusercontent.com/2193314/80385844-7421e000-885b-11ea-8084-9dd0ba755024.png)
