### ISSUE TITLE
Remote-SSH: Better support shared users

### ISSUE THREAD

**Issue by zobo** [microsoft/vscode-remote-release#2783]
There are cases when more persons are using a shared user on a development server. Although vscode-remote works there are strange side cases (people ending up getting ENV from a different user, shared extensions...).

Suggest to add a "remote context id" that would somehow namespace more vscode-server instances that clients connect to.

Each user could set their own unique ID on the client, and then always connect to their own vscode-server instance, not to that of their coworker.

Perhaps that could be as simple as adding another path element to:

/root/.vscode-server/{uniq-user-identifier}/bin/...

**Comment by zobo** [comment]
Did some research and it seems it's possible to achieve this by editing "serverDataFolderName" in your local product.json. Is there any way to override this variable in settings.json or other user location?

**Comment by zobo** [comment]
I believe this issue #1738 was describing the same problem. The question is, is it possible to run completely separate vscode-server instances, and control which to connect to via a command line parameter or some setting...

**Comment by roblourens** [comment]
If you want multiple users logging in independently, you just need multiple user accounts on the remote. We are not going to reinvent the "user" wheel.

**Comment by zobo** [comment]
Sadly, sometimes that's just how it is and cannot be avoided (like described in #1738). Another use case would be running more than one instance for myself on a box that has one user available for me with incompatible extensions (or different versions of extensions).
A very simple way to enable a workaround like this, would be to allow an override of the `serverDataFolderName` value from ENV on the server, when the remote bootstraps.
I'd love to provide a PR, but seems this part of vscode is closed source.
