### ISSUE TITLE
Can't access a nuget container via vscode-remote dev

### ISSUE THREAD

**Issue by AndersonSFerreira** [microsoft/vscode-remote-release#2784]
- VSCode Version: 1.44.1
- Local OS Version: Manjaro Kyria 19.0.2
- Remote OS Version: Debian Stretch 9.12 

I have the containers configured as follows:

![image](https://user-images.githubusercontent.com/5570453/79564789-af672680-8085-11ea-8120-ac9d4713abf9.png)

to run a nuget server, I used the following command:

docker run --name nuget-server --network=shared-net --restart unless-stopped  -p 9001:80 --env-file baget.env -v "$(pwd)/baget-data:/var/baget" loicsharma/baget:latest

as you can see, I configured it so that the nuget is used on the shared-net network

with vscode-remote I couldn't find an option for configuring the network, so I changed the network through the portainer

I configured my remote project with the nuget.config file, and when trying to restore the packages installed on my local nuget server the following error is shown

![image](https://user-images.githubusercontent.com/5570453/79564999-1e447f80-8086-11ea-8d86-39804d1e1726.png)

does anyone know the correct way to configure a vscode-remote project so that it is possible to access other containers?

**Comment by chrmarti** [comment]
Could you try adding `"runArgs": ["--network=shared-net"]` to the devcontainer.json and see if that works?
