### ISSUE TITLE
VSCode doesn't close previous SSH process after reconnecting

### ISSUE THREAD

**Issue by wkia** [microsoft/vscode-remote-release#2785]
- VSCode Version: 1.44.2
- Local OS Version: Windows 7
- Remote OS Version: centOS 7
- Remote Extension/Connection Type: SSH

If ssh connection is lost, VSCode opens new SSH.exe process to reconnect, but doesn't close the previous one.

Steps to Reproduce:

1. Start VSCode and connect to a remote server.
2. Open Task Manager and find ssh.exe
3. You should see the only SSH.exe process similar to "`ssh.exe -T -D 12345 <IP_ADDRESS> bash`"
4. Wait for SSH connection is lost and VSCode reconnect to a remote server (see Screenshot 1)
5. After reconnect, open Task Manager and find ssh.exe process 
6. You should see **several** SSH.exe processes similar to "`ssh.exe -T -D 12345 <IP_ADDRESS> bash`" (see Screenshot 2). The more reconnecting, the more SSH processes, the more CPU usage.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: not applicable

**Screenshot 1:**
![2020-04-17 18_21_38-reconnect](https://user-images.githubusercontent.com/17044077/79586094-5a550000-80d9-11ea-86d7-a7e9148b01a5.png)

**Screenshot 2:**
![2020-04-17 18_22_35-Windows Task Manager](https://user-images.githubusercontent.com/17044077/79586161-6d67d000-80d9-11ea-9de2-af1a2f5beea7.png)

**Screenshot 3**
![2020-04-20 18_03_31-Windows Task Manager](https://user-images.githubusercontent.com/17044077/79767336-dcd7fc80-8331-11ea-951b-4b677c1ca2cf.png)

**Comment by roblourens** [comment]
Sorry for the slow response. I think this should be fixed by now. Please let me know if not.

**Comment by sergzub** [comment]
@chrmarti @roblourens @bamurtaugh 
Hi,
I also consistently observe the same problem on a similar configuration.
In addition, I don't have a very fast connection (<1 Mbps) and a really large repository on the remote.
How can it be fixed?
Can I increase some timeout values for ssh?
