### ISSUE TITLE
Can't follow error in Problems tab in C++ project under WSL

### ISSUE THREAD

**Issue by dzvancuks** [microsoft/vscode-remote-release#2786]
Version: 1.44.0 (system setup)
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-07T23:31:18.860Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
**WSL**

Steps to Reproduce:

1. Open pure makefile project in VSC under WSL, e.g. Ubuntu 16.04 with gcc and make.
2. Configure tasks.json for compilation (see below).
3. Create error. E.g.` int a = "a";`
4. Compile project using task.
5. Switch to PROBLEMS tab and click on error message.
5. Popup message will inform that:
> Unable to open 'file.cpp': Unable to read file 'vscode-remote://wsl+ubuntu-16.04/file.cpp' (Error: Unable to resolve non-existing file 'vscode-remote://wsl+ubuntu-16.04/file.cpp').

![image](https://user-images.githubusercontent.com/744090/79588426-95a4fe00-80dc-11ea-99a7-115005963cc0.png)

tasks.json:
 `{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Make project",
            "type": "shell",
            "command": "make",
            // use options.cwd property if the Makefile is not in the project root ${workspaceRoot} dir
            "options": {
                "cwd": "${workspaceRoot}"
            },
            // start the build without prompting for task selection, use "group": "build" otherwise
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared"
            },
            // arg passing example: in this case is executed make QUIET=0
            "args": [
                "QUIET=0"
            ],
            // Use the standard less compilation problem matcher.
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": [
                    "absolute"
                ],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        }
    ]
}`

Same issue if change problemMatcher to `"fileLocation": "relative",`.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by egamma** [comment]
Please report the issue against the C/C++ extension.

**Comment by sean-mcmanus** [comment]
The user is not using any feature provided by the C++ extension. I'm not even sure if they have the C/C++ extension installed. This seems like some issue with problem matching in general; however, I wasn't able to repro the bug...maybe it requires WSL2 and I may be using WSL1?

**Comment by dzvancuks** [comment]
I've re-tested without extensions and it seems it does not affect behavior. This is not C++ extension issue. Updated description.
@sean-mcmanus, I use WSL1

**Comment by dzvancuks** [comment]
Attaching test project. Open it in WSL and hit Start Debugging in Run tab
[test.tar.gz](https://github.com/microsoft/vscode-remote-release/files/4521059/test.tar.gz)
