### ISSUE TITLE
MacOS Client to Windows Host not working

### ISSUE THREAD

**Issue by SynergiAios** [microsoft/vscode-remote-release#2790]
- VSCode Version: 1.44.0
- Local OS Version: MacOS Catalina 10.15.4
- Remote OS Version: Any Windows (tried Windows 10 Pro and Windows 2019 Server Core)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect with a mac via VSCode Remote to a Windows Host
2. Create dotnet core console project
3. Press Debug button
4. Error: dotnet shell command not found

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Tested on Inside build too, same issue. I also created another issue regarding to the dotnet shell command not found with more infos - https://github.com/microsoft/vscode-remote-release/issues/2747

Now as I tested more, I can clearly say it is a general macos->windows issue. I have tested with 2 different mac's and 2 different windows hosts. If I connect with a windows client to the windows host everything is working as expected. When connecting with a macos client, the error occurs.

**Comment by SynergiAios** [comment]
If anyone else is coming across this issue, I just discovered out of curiosity, what would happen, when I say ignore and debug anyways. Conclusion - it worked. So as a workaround, till this get's properly fixed, just press debug anyways and continue having fun

**Comment by bamurtaugh** [comment]
Hey @SynergiAios, are you still experiencing this issue?

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/2747
