### ISSUE TITLE
Resolver error: The remote host's platform is not supported

### ISSUE THREAD

**Issue by Menci** [microsoft/vscode-remote-release#2791]
- VSCode Version: 
- Local OS Version:

```
Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19551
```

- Remote OS Version: elementaryOS 5.1 (Ubuntu 18.04, Linux 5.3.0-46-generic)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to the host, success
2. Open a folder, the chooser works properly
3. Then the error happens

```
[00:39:44.585] Log Level: 2
[00:39:44.590] remote-ssh@0.51.0
[00:39:44.590] win32 x64
[00:39:44.592] SSH Resolver called for "ssh-remote+syzoj-ng.test", attempt 1
[00:39:44.593] SSH Resolver called for host: syzoj-ng.test
[00:39:44.593] Setting up SSH remote "syzoj-ng.test"
[00:39:44.620] Using commit id "ff915844119ce9485abfe8aa9076ec76b5300ddd" and quality "stable" for server
[00:39:44.623] Install and start server if needed
[00:39:44.629] Checking ssh with "ssh -V"
[00:39:44.703] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[00:39:44.708] Running script with connection command: ssh -T -D 28756 syzoj-ng.test bash
[00:39:44.713] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[00:39:45.114] > d6ebd63779b8: running
> ]0;C:\WINDOWS\System32\cmd.exe
[00:39:45.115] Got some output, clearing connection timeout
[00:39:45.130] > Acquiring lock on /home/Menci/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec7
> 6b5300ddd/vscode-remote-lock.Menci.ff915844119ce9485abfe8aa9076ec76b5300ddd     
[00:39:45.146] > \ln /home/Menci/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vsco
> de-remote-lock.Menci.ff915844119ce9485abfe8aa9076ec76b5300ddd.target /home/Menci
> /.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.
> Menci.ff915844119ce9485abfe8aa9076ec76b5300ddd
> Found existing installation at /home/Menci/.vscode-server/bin/ff915844119ce9485a
> bfe8aa9076ec76b5300ddd...
[00:39:45.162] > Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status on port 33709 with wget
> d6ebd63779b8: start
> sshAuthSock====
> agentPort==33709==
> osReleaseId==elementary==
> arch==x86_64==
> webUiAccessToken====     
> tmpDir==/run/user/1000== 
> platform==linux==
> d6ebd63779b8: end
[00:39:45.162] Received install output: 
sshAuthSock====
agentPort==33709==
osReleaseId==elementary==
arch==x86_64==
webUiAccessToken====     
tmpDir==/run/user/1000== 
platform==linux==

[00:39:45.165] Resolver error: The remote host's platform is not supported
[00:39:45.168] ------




[00:39:45.922] > 
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by Menci** [comment]
This bug can't be reproduced every time. Sometimes I can open the remote directory successfully.

I printed the "platform" and found it's `undefined` when error:

```js
throw c.ExitCode(35, "The remote host's platform '" + r.platform + "' is not supported");
```

```
[Window Title]
Visual Studio Code

[Content]
Could not establish connection to "Menci-Desktop". The remote host's platform 'undefined' is not supported.

[Close Remote] [More Actions...] [Retry]
```

As a workaround, I changed:

```js
if (r.platform === s.Platform.Linux) n = s.Platform.Linux;
```

to:

```js
if (r.platform === s.Platform.Linux || !r.platform) n = s.Platform.Linux;
```

Now it works without problem. But why the `s.platform` becomes `undefined`?  
I'm not familiar with vscode-remote's protocol so I'm afraid I can't do more debugging.

**Comment by quah6o** [comment]
Hi @Menci 
I have the same problem. Can you tell me where I have to change these workaround?

**Comment by Menci** [comment]
Sorry I forgot which file I edited. You can `grep -r 'The remote host's platform` in the extension directory to find it.

**Comment by quah6o** [comment]
Thank you.
```
~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.51.0/out/extension.js
```

**Comment by rayate2410** [comment]
> This bug can't be reproduced every time. Sometimes I can open the remote directory successfully.
> 
> I printed the "platform" and found it's `undefined` when error:
> 
> ```js
> throw c.ExitCode(35, "The remote host's platform '" + r.platform + "' is not supported");
> ```
> 
> ```
> [Window Title]
> Visual Studio Code
> 
> [Content]
> Could not establish connection to "Menci-Desktop". The remote host's platform 'undefined' is not supported.
> 
> [Close Remote] [More Actions...] [Retry]
> ```
> 
> As a workaround, I changed:
> 
> ```js
> if (r.platform === s.Platform.Linux) n = s.Platform.Linux;
> ```
> 
> to:
> 
> ```js
> if (r.platform === s.Platform.Linux || !r.platform) n = s.Platform.Linux;
> ```
> 
> Now it works without problem. But why the `s.platform` becomes `undefined`?
> I'm not familiar with vscode-remote's protocol so I'm afraid I can't do more debugging.

Started facing same issue when I copied my ssh-key to remote machine to enable password-less login in vscode. 

After applying the fix provided, it started working for me. Thank you so much.

**Comment by minscof** [comment]
I have the same bug, but I can't find the file to patch
is it  ~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.51.0/out/extension.js on the local machine ?

**Comment by roblourens** [comment]
Sorry for the slow response. Please let me know if this is still happening, I fixed something related earlier.
