### ISSUE TITLE
Integrated Terminal using outdated golang

### ISSUE THREAD

**Issue by kevineaton603** [microsoft/vscode-remote-release#2794]
Issue Type: <b>Bug</b>

I recently upgrade my Golang version from 1.10 => 1.13 on WSL Ubuntu Server to test WebAssembly.

In the server, get the correct version number when running `go version`. But in the integrated terminal I get my old version.

1. `sudo apt-get install golang`
2. `code .` (Location of project)
3. `wget https://dl.google.com/go/go1.13.3.linux-amd64.tar.gz`
4. `sudo tar -xvf go1.13.3.linux-amd64.tar.gz `
5. `sudo rm -rf /usr/local/go`
6. `sudo mv go /usr/local`
7. `export GOROOT=/usr/local/go`
8. `export GOPATH=$HOME/golang` (Loaction of your project)
9. `export PATH=$GOPATH/bin:$GOROOT/bin:$PATH`
10. `code .`
11. In integrated terminal, `go version`

Extension version: 0.44.2
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.28GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/home/keaton/golang/wa-test --remote=wsl+Ubuntu-18.04|
|Screen Reader|no|
|VM|44%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|Memory (System)|7.89GB (2.28GB free)|
|VM|44%|
</details>

**Comment by egamma** [comment]
Could it be that you have setup the integrated terminal so that it runs against Windows and not against WSL? Can you inlcude a screenshot.

**Comment by kevineaton603** [comment]
@egamma I discovered my issue was. I needed to set some of the go environment variables in my `~/.profile` so when the terminal started up, it pointed to the correct version of go.
