### ISSUE TITLE
Failing to install some extensions on remote machine(error: ENOENT)

### ISSUE THREAD

**Issue by anilnayak** [microsoft/vscode-remote-release#2803]
- VSCode Version: 1.44.1
- Local OS Version: Windows 10 11763.1158
- Remote OS Version: Linux Ubuntu 14.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to remote machine using SSH-Remote
2. Go to extensions -> Git Lens -> Click Install in SSH: <host-name>

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

I see an error dialog with this message - "ENOENT: no such file or directory, mkdir"

Not sure if this is issue with the Git Lens extension or SSH-Remote. Some of the other extension has same behavior too

**Comment by Nosferican** [comment]
Sometimes I have hit that issue when the process in VS Code does not have the `PATH` environmental variable restricting.

**Comment by anilnayak** [comment]
not sure how it's fixed. I tried again with V 1.45.1 and it's working.
