### ISSUE TITLE
New WSL Window always shows terminal

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-remote-release#2806]
This is so annoying since the terminal opens and gets focus, stealing some keybindings, notably <kbd>Ctrl R</kbd>, a common keyboard shortcut run right after a window opens.

![image](https://user-images.githubusercontent.com/22350/79875648-3865c100-83ea-11ea-8bdd-3a83420cde86.png)

**Comment by aeschli** [comment]
No changes planed.
