### ISSUE TITLE
Empty Dockerfile required when it's generated via InitializeCommand

### ISSUE THREAD

**Issue by ob** [microsoft/vscode-remote-release#2807]
- VSCode Version:
Version: 1.44.1
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:47:00.296Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
- Local OS Version:
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287
- Remote OS Version:
- Remote Extension/Connection Type: SSH/Docker/WSL
Docker
Steps to Reproduce:

1. Generate the Dockerfile via an `initializeCommand` script.
2. Point the `"dockerFile"` attribute in `.devcontainer/devcontainer.json` to the `Dockerfile` that will be generated.

VS Code complains that the `Dockerfile` doesn't exist when in fact it'll be generated by the `initializeCommand` script.

The workaround is to check in an empty `Dockerfile` that will get overwritten by the `initializeCommand`. Maybe the error checking could be loosened up if there exists an `initializeCommand` attribute?

**Comment by chrmarti** [comment]
We do some upfront validation and stop if the Dockerfile does not exist. I agree, we could loosen the checks in this case.
