### ISSUE TITLE
Unable to launch vscode in remote mode from WSL2 (custom kernel)

### ISSUE THREAD

**Issue by onomatopellan** [microsoft/vscode-remote-release#2809]
- VSCode Version: 1.45.0-insider Windows version
- Local OS Version: Windows 10 2004 build 19041.207
- Remote OS Version: Ubuntu 20.04 kernel 4.19.104-microsoft-standard+
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. cd ~
2. code-insiders .

VSCode opens in normal mode and not in remote mode.
I think it's because of [this](https://github.com/microsoft/vscode/blob/763748e43cfa243d6e003a0f5fbfa1fcf6edec8c/resources/win32/bin/code.sh#L14) line in code.sh.
With Microsoft [latest](https://github.com/microsoft/WSL2-Linux-Kernel/tree/linux-msft-wsl-4.19.y) linux kernel 4.19.104 $WSL_BUILD becomes 0.

```bash
onoma:~$ uname -r
4.19.104-microsoft-standard+
onoma:~$ uname -r | sed -E 's/^[0-9.]+-([0-9]+)-Microsoft|([0-9]+).([0-9]+).([0-9]+)-microsoft-standard|.*/\1\2\3\4/'

onoma:~$ 
```

**Comment by onomatopellan** [comment]
Ok, I found the problem. It seems the kernel build system like to append '+' to the kernel's local version string whenever it detects that the source tree is version controlled with Git.
Adding **\\+?** at the end of the string does the trick.

```bash
onoma:~$ uname -r
4.19.104-microsoft-standard+
onoma:~$ uname -r | sed -E 's/^[0-9.]+-([0-9]+)-Microsoft|([0-9]+).([0-9]+).([0-9]+)-microsoft-standard\+?|.*/\1\2\3\4/'
419104
onoma:~$ 
```
Since WSL2 supports custom kernels I still think code.sh should be modified so this problem won't happen to more people.

**Comment by onomatopellan** [comment]
As workaraound every time VSCode-insiders is updated I need to do this:
`sed 's/standard/standard\\+?/g' "$(which code-insiders)"`

For VSCode woulde be:
`sed 's/standard/standard\\+?/g' "$(which code)"`

After that `code-insiders .` launches VSCode with Remote Mode enabled.

**Comment by imoldfella** [comment]
@onomatopellan Thank you so much! I didn't quite understand your instructions but I changed code.sh to 
WSL_BUILD="41975"
And that fixed the issue. I would have not have thought to look there. I guess you are suggesting rebuilding the kernel to have the name visual code is expecting so that upgrades of code don't undo the fix?

**Comment by onomatopellan** [comment]
@imoldfella Correct. If the compiled kernel version looks like `x.x.x-microsoft-standard` VSCode Remote will always work. In your case it's the `-rc4` [EXTRAVERSION](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/Makefile#n5) that makes return an incorrect WSL_BUILD. Compiling the kernel with `make EXTRAVERSION=""` should get rid of the `-rc4`.

**Comment by nicknitewolf** [comment]
Can I say that https://github.com/microsoft/vscode/commit/c93c29c357579925f54e7d1d07eace1c0b8f8e30#diff-5457d0ab2360916eb877b2f44c2a1b6fR23 this is still an issue. It still tries to DETECT A WINDOWS BUILD NUMBER, even though custom kernels / WSL2 do not have such a thing. Whatever you have implemented is not proper @aeschli

**Comment by nicknitewolf** [comment]
what I'm referring to is the greater than or equal check `if [ $WSL_BUILD -ge 17063 ]; then` if I wasn't clear enough
