### ISSUE TITLE
Remote-Containers: Sync (extension) settings via devcontainers.json

### ISSUE THREAD

**Issue by nphmuller** [microsoft/vscode-remote-release#281]
One of the great features of the remote tools for containers is that I can share the required extensions for my development team. However, it currently seems that there is no way to specifiy custom settings for these extensions. 

For example: I want to share the `Trim whitespace on save` setting for the `Trailing Spaces` extension. This setting is by default disabled.  Currently there seems to be no way to enable this setting for my entire team through devcontainers.json (or another way that I can check into my git repositry).

**Comment by kieferrm** [comment]
Give this a try: https://github.com/microsoft/vscode-remote-try-java/blob/f041d909d83a60cd394713bdfc7f8a3edd3285e2/.devcontainer/Dockerfile#L9

**Comment by Chuxel** [comment]
@nphmuller The specifics of how this works is described here: https://code.visualstudio.com/docs/remote/containers#_container-specific-settings

**Comment by nphmuller** [comment]
@kieferrm @Chuxel 
Thanks, I missed that! Example of RTFM 😁
