### ISSUE TITLE
Go To Definition not working

### ISSUE THREAD

**Issue by JohnChain** [microsoft/vscode-remote-release#2816]
- VSCode Version: 1.44.2(user setup)
- Local OS Version: win10 x64
- Remote OS Version: ubuntu18.04 aarch64
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. install c/c++ extention to remote 
2. press "F12" / "ctrl + leftClick" / rightClick menu 

this Issue seems not what im facing (#522)[https://github.com/microsoft/vscode-remote-release/issues/522]

![M7THVHA1HCIBMQDY7U2SEOR](https://user-images.githubusercontent.com/1732598/80053963-b93ecd00-8550-11ea-8ee7-7a58f42a4d52.png)
![LG@A%LNM92CYIHD((PRS2~R](https://user-images.githubusercontent.com/1732598/80053971-bba12700-8550-11ea-964e-322adfb3435d.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
If this is still an issue, please file an issue with details on the C++ extension repo
