### ISSUE TITLE
Auto-install extensions in parallel

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode-remote-release#2819]
When using the auto-install extensions at connection feature, each extension is installed sequentially. I don't see any reason as to why this couldn't have been done in parallel.

This would also have a nice side effect of shortening the time it takes for proxy timeouts for when things don't work for no apparent reason (see #2186), because each proxy timeout will now be independent of other timeouts that came before.

**Comment by sandy081** [comment]
@chrmarti May I know what feature user is talking about?

**Comment by chrmarti** [comment]
@sandy081 I think this is the extension installation into the SSH target machine using the CLI installer. Containers would presumably benefit from performance improvements too.

**Comment by sandy081** [comment]
Recently (in current October milestone),I refactored CLI and improved performance by installing extensions in parallel - https://github.com/microsoft/vscode/issues/109427
