### ISSUE TITLE
Open file from remote terminal

### ISSUE THREAD

**Issue by jxramos** [microsoft/vscode-remote-release#2821]
I'm attempting to run `code` from the terminal and expect a file that resolves from the working directory when given as an argument to `code` should have it open up in the current editor of the active remote development session.

So in the TERMINAL, I can see the remote session puts a `code` executable on the path....

```bash
~/repo/proj$ which code
/home/USERX/.vscode-server/bin/GUID_STRING/bin/code
```

However when I go to launch a file from that program nothing happens.
```bash
~/repo/proj$ code fileX.txt
/usr/share/code/bin/../code: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/share/code/bin/../code)
```

I can get the program to print the help string...
```bash
~/repo/proj$ code --help
/usr/share/code/bin/../code: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/share/code/bin/../code)
Visual Studio Code 1.39.2

Usage: code [options][paths...]

To read from stdin, append '-' (e.g. 'ps aux | grep code | code -')

Options
  -d --diff <file> <file>           Compare two files with each other.
  -a --add <folder>                 Add folder(s) to the last active window.
...
```

Here's my version details...
> Version: 1.44.2
> Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
> Date: 2020-04-16T17:07:18.473Z
> Electron: 7.1.11
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Darwin x64 18.7.0
> 
> 

I'm remotely connecting to an Ubuntu Linux desktop.

**Comment by chrmarti** [comment]
It looks like you end up using a full install of VS Code at `/usr/share/code` instead of the remote wrapper at `/home/USERX/.vscode-server/bin/GUID_STRING/bin/code`. Can you try invoking `/home/USERX/.vscode-server/bin/GUID_STRING/bin/code` with its full path?

**Comment by jxramos** [comment]
yah, using the full GUID path works, how interesting. The thing that's curious is that the which command resolves to that full GUID path, so when I run code I would think that that path is what is running. How in the world is the second one resolving when I _call_ code vs when I _which_ code??

```
$ which -a code
/home/USERX/.vscode-server/bin/GUID_STRING/bin/code
/usr/bin/code
```

**Comment by chrmarti** [comment]
The order in the `PATH` environment variables determines which one is picked. (Not sure what order `which` shows.)
