### ISSUE TITLE
Resolving the authority "wsl" failed

### ISSUE THREAD

**Issue by codinggosu** [microsoft/vscode-remote-release#2822]
Attempting to launch vscode from wsl2 with command "code ." fails with errors:

Failed to connect to the remote extension host server (Error: No remote extension installed to resolve wsl.)
Resolving the authority `wsl` failed
The 'Remote - WSL' extension is recommended as you have Windows Linux Subsystem (WSL) installed on your system.

However, re-launching vscode by running vscode on host os (clicking on vscode shortcut in windows) works fine, and can connect to the wsl.

- VSCode Version:
Version: 1.42.1 (system setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041
- Local OS Version:
Microsoft Windows [Version 10.0.19041.208]
- Remote OS Version:
WSL2 Ubuntu 18.04
- Remote Extension/Connection Type: SSH/Docker/WSL
WSL2
Steps to Reproduce:

1. "code ." in any directory in wsl2

I have tried the following debugging procedures:
- re-installing vscode in host os
- removing the folders from .vscode-server/bin as suggested by replies from similar issues

![image](https://user-images.githubusercontent.com/16798331/80175281-1d848e00-8630-11ea-97f6-fad5dabc924d.png)

**Comment by mukminkamal** [comment]
Maybe try to uninstall the Remote - WSL extension first then try launch vscode again from wsl2 with command "code ." Then install back the Remote - WSL extension.

**Comment by codinggosu** [comment]
woah that actually worked, I don't know if I did that the first time but it didn't work, and now it's working due to an update

or I just didn't do that the first time for some reason

but it works now!
thanks
