### ISSUE TITLE
Can't find attach to running container

### ISSUE THREAD

**Issue by deepankarm** [microsoft/vscode-remote-release#2823]
Issue Type: <b>Bug</b>

Inside a remote-ssh, I am trying to attach a running container. Can't find the option (see attached)!

![image](https://user-images.githubusercontent.com/9050737/80214871-2fc6f200-8659-11ea-832c-9c4a21afe048.png)

Extension version: 0.112.0
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.0.0-1029-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: tl-server|
|OS|Linux x64 5.0.0-1029-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (12 x 2596)|
|Memory (System)|110.14GB (50.20GB free)|
|VM|0%|
</details>

**Comment by PavelSosin-320** [comment]
Off course! Nobody keeps track between workspace and it's Development machine - remote container! Remote containers are not even labeled as "Development machines". Hopefully, SSH server is successfully started in the remote container which is not promised by the Docker architecture by any way. Docker containers are headless by default and has to be initialized externally via --init option.

**Comment by deepankarm** [comment]
Hi @chrmarti,

I saw your comment on the below issue. I have been facing something similar. 
https://github.com/microsoft/vscode-remote-release/issues/384#issuecomment-494667610

Upon trying **Attach Visual Studio Code** to a running container inside containers view, getting the below error.

![image](https://user-images.githubusercontent.com/9050737/81170853-01caa180-8fb9-11ea-81b0-a5a884429ffc.png)

Here's the error in the Developer tools

![image](https://user-images.githubusercontent.com/9050737/81170939-2f174f80-8fb9-11ea-83ef-d7ad462d96b3.png)

Here's the output of the same command on the terminal.

```console
$ which -a docker
/usr/bin/docker
$
$ docker version --format '{{.Server.Version}}'
19.03.5
$ echo $status
0
```
Any help would be appreciated.

**Comment by chrmarti** [comment]
@deepankarm You cannot connect to a container directly from within Remote-SSH. Please see https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host on how to configure Remote-Containers to connect through an SSH connection.
