### ISSUE TITLE
SSH server keeps disconecting 

### ISSUE THREAD

**Issue by manurastogi** [microsoft/vscode-remote-release#2825]
Issue Type: <b>Bug</b>

The ssh server just keeps diconnecting with a port error

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.17763
Fetching remote diagnostics for 'SSH' failed: Connecting was canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: Connecting was canceled
</details>Extensions: none

**Comment by roblourens** [comment]
@manurastogi  Are you able to connect from an external terminal?

**Comment by manurastogi** [comment]
Thank you @hnakamur. That worked for me. 
@roblourens : Thanks for checking with me.

**Comment by roblourens** [comment]
Are you saying that setting `showLoginTerminal` fixed this? That's interesting, I don't know why that would be...

**Comment by hnakamur** [comment]
No, I'm not saying so.
Enabling showLoginTerminal is to show log messages for debugging.

Deleting the lock file fixed this.
> And I logined the target server and removed the existing file.

**Comment by roblourens** [comment]
I see that in your case @hnakamur but in @manurastogi the logs didn't seem to show the lock file issue (which others have reported and I am tracking in another issue0
