### ISSUE TITLE
Connection issues when .ssh/config connection has multiple names

### ISSUE THREAD

**Issue by veilrap** [microsoft/vscode-remote-release#283]
- VSCode Version: 1.34
- Local OS Version: 18356.1
- Remote OS Version: Ubuntu 16.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.  Have an entry in .ssh/config with multiple names, i.e.:
Host alias1 alias2 alias3
  Hostname alias1.com
2. Try to connect via remote ssh
3. Connection fails with "command not found"
4. Remote all the aliases but 1
5. remote-ssh connection succeeds

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Working on this, got an issue at https://github.com/microsoft/vscode-remote-release/issues/64

**Comment by roblourens** [comment]
Will use this issue just for the multiple names per line part.
