### ISSUE TITLE
French translation issue on remote connection close

### ISSUE THREAD

**Issue by GuiPoM** [microsoft/vscode-remote-release#2831]
Hello,

Using latest version of vscode 1.44.2 and latest version of the plugin, the internationalized text for closing the remote connection is wrong:

![image](https://user-images.githubusercontent.com/11942518/80282196-66ac0f00-8710-11ea-9956-7fdd51fd6c50.png)

Should be "Fermer la connexion à distance"
I would also loved to contribue in french translation there, but I could not find where the resources are. So at least entering an issue might help !

**Comment by SylChamber** [comment]
I think the issue is with the French language pack. I may have located the faulty string in the [main.i18n.json file in vscode-loc](https://github.com/microsoft/vscode-loc/blob/master/i18n/vscode-language-pack-fr/translations/main.i18n.json).

**Comment by GuiPoM** [comment]
> I think the issue is with the French language pack. I located the faulty string in the [`main.i18n.json` file in the `vscode-loc` repo](https://github.com/microsoft/vscode-loc/blob/master/i18n/vscode-language-pack-fr/translations/main.i18n.json).
> 
> I think that's where the issue should be submitted.
> 
> The faulty string is in `"vs/workbench/contrib/remote/browser/remoteIndicator"."closeRemote.title"`. If I compare with the `en-GB` translation, there should be no `&`s in `closeRemote.title`. I looked at all `.title` strings, and there never is any `&`s in them in the `en-GB` translation. There is only one occurence in the `fr` translation, the faulty string.

Thanks for the hint, I suggested a PR to fix that translation.
