### ISSUE TITLE
"Open on SSH host in current window" switches focus to the other window that has that remote folder open instead of opening in the window

### ISSUE THREAD

**Issue by omkensey** [microsoft/vscode-remote-release#2833]
Issue Type: <b>Bug</b>

1. Open two VSCode windows
2. In one, open a remote folder over an SSH remote using "Open on SSH host in current window"
3. In the other, try to open the same remote folder the same way

Actual result: Focus switches to the window that already has the remote folder open

Expected result: the remote folder opens a second time in the same VSCode window

Extension version: 0.51.0
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 5.5.17-200.fc31.x86_64
Remote OS version: Linux x64 4.18.0-147.8.1.el8_1.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 3375)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.29GB (2.87GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: slide-server|
|OS|Linux x64 4.18.0-147.8.1.el8_1.x86_64|
|CPUs|Intel Core Processor (Haswell, IBRS) (1 x 3192)|
|Memory (System)|1.79GB (0.57GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
That's expected and given by VS Code. (There must be a feature request for VS Code, but I can't find it right now.)
