### ISSUE TITLE
Development containers: what happens after Docker Desktop restart, Docker daemon restart, docker container restart

### ISSUE THREAD

**Issue by PavelSosin-320** [microsoft/vscode-remote-release#2836]
I tried to return to the state before Docker Desktop restarts, Docker daemon restart, docker container restart, and didn't find how. Attach to a running container shows all my 34 running containers. The entire context has lost except Explorer. There is no container filter. Why I see my MySQL container in my local Kubernetes instance? Please, either label container with workspace or keep connection from the workspace to the container.

**Comment by egamma** [comment]
Not clear what the problem is. What do you mean by 

>The entire context has lost except Explorer

Can you add a screenshot that illustrates your problem.
