### ISSUE TITLE
I cant get off of wsl.exe for linux i didnt want it but now I cant get off.

### ISSUE THREAD

**Issue by BludmaneWireless** [microsoft/vscode-remote-release#2837]
Issue Type: <b>Bug</b>

The terminal process terminated with exit code: 4294967295
im trying to get back to the normal cmd prompt but thats what it shows me that error please help me put it back to normal

Extension version: 0.44.2
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (1.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by BludmaneWireless** [comment]
I guess i have to use visual studio code insider

**Comment by chrmarti** [comment]
Were you able to resolve the issue? If not, could you attach a screenshot?
