### ISSUE TITLE
Server fails to start when default shell is powershell

### ISSUE THREAD

**Issue by owahltinez** [microsoft/vscode-remote-release#2839]
- VSCode Version: 1.44.2
- Local OS Version: OSX Catalina
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. In remote OS, set default shell to powershell: `sudo chsh $USER -s $(which pwsh)`
2. In local OS, use VSCode remote extension to connect via SSH

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Notes: changing the default shell back to bash fixes the problem.

**Comment by owahltinez** [comment]
This issue is still present in the most recent release of vscode. Can someone take a look?

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/2509
