### ISSUE TITLE
Can't connect to ssh remote with space in hostname

### ISSUE THREAD

**Issue by MarioHewardt** [microsoft/vscode-remote-release#284]
- VSCode Version: 1.34.0-insider
- Local OS Version: Windows_NT x64 10.0.17763
- Remote OS Version: Ubuntu 16.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Create host config to VM running locally
2. Try to connect using Remote-SSH

The output of view->output->remote-ssh:
 ---
Confirming that Ubuntu 16.04 is a valid reachable host
Running type "C:\Users\marioh\AppData\Local\Temp\vscode-linux-multi-line-command-Ubuntu 16.04.sh" | ssh  Ubuntu 16.04 to confirm the host platform
ConfigFileWatcher: closing output:extension-output-%232
> 
> xxx@yyyy's password:
> 
> 
> bash: 16.04: command not found
> 
"uname" terminal command done
Ubuntu 16.04: unreachable or not Linux x86_64. (bash: 16.04: command not found)
----

Running 'uname' in a PuttT window generates the following: Linux

Changing the IP to an invalid IP errors out before asking for password which seems to indicate that a connection was actually made but something else is going wrong. 

Does this issue occur when you try this locally?: SSH
Does this issue occur when you try this locally and all extensions are disabled?:

**Comment by roblourens** [comment]
It looks like there is a space in your remote hostname which I don't handle correctly.

**Comment by MarioHewardt** [comment]
That did the trick. Thanks.

**Comment by roblourens** [comment]
So your host name must be in quotes in your ssh config, right? Just trying to figure out whether there's a way to have a space in a host name without using quotes...

**Comment by roblourens** [comment]
Upstream issue: https://github.com/cyjake/ssh-config/issues/17
