### ISSUE TITLE
Test downloading extension VSIXs to a cached folder

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-release#2842]
Ref - #2227

- [x] anyOS @chrmarti
- [x] anyOS @mjbvz

Complexity: 3

---

1. Start code with arg `--extensions-download-dir` and providing a path for downloading extension VSIXs
2. Go to extension view and install an extension
3. Make sure that VSIX is downloaded to above provided directory
4. Uninstall the extension, and also go to Extensions Folder using command `Extensions: Open Extensions Folder` and delete the extension (This is to make sure that extension is downloaded again).
5. Install the extension again. 
6. Make sure that downloaded VSIX is used. You can test that by making sure that there is no request to Marketplace for the VSIX. To test that, 
  - Open shared process (`Developer: Toggle Shared Process`) and go to networks tab
  - There is no request to Marketplace to download VSIX Eg: `https://........../Microsoft.VisualStudio.Services.VSIXPackage`
7. Delete the downloaded VSIX in the above pointed directory and follow steps 4 & 5.
8. Make sure that VSIX is downloaded again to the above pointed directory. 
9. Make sure that we cache only recent 20 VSIXs.
  - Use extension packs with many extensions to install or uninstall bunch of extensions
  - Clean up is done when code is started. So you have to restart for clean up to kick off.

**Comment by chrmarti** [comment]
Works well!
