### ISSUE TITLE
Test improved dev container configuration

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#2844]
Ref - #2757

- [x] anyOS  @chrmarti
- [x] anyOS @jrieken

Complexity: 3

---

When configuring a workspace as a dev container using `Remote Containers: Add Development Configuration Files' then the list of container definitions from the [repository](https://github.com/microsoft/vscode-dev-containers/tree/master/containers) shown in the quick pick  is now sensitive to the current workspace. 

For example, when the workspace is a Node.js application using TypeScript, then the dev container configurations for Node.js and TypeScript should appear on top of the list. 

The order in the list is as follows:
- configurations that match a platform or languages of the workspace
- configurations that are generally useful (e.g. Alpine)
- 'Show all configurations...' shows all configurations including the ones that are not considered relevant for this workspace.

For multi root workspaces the first folder is considered.

### Verification

- Open workspaces using different platforms and languages that are supported by definitions from  [repository](https://github.com/microsoft/vscode-dev-containers/tree/master/containers).
- Run `Remote Containers: Add Development Configuration Files' and verify that the suggested configurations are relevant to the workspace.

**Comment by jrieken** [comment]
Looking good but https://github.com/microsoft/vscode-remote-release/issues/2865 is worry-some because I have seen this often but cannot reproduce reliable
