### ISSUE TITLE
"Install" terminal window remains up and is not closable.

### ISSUE THREAD

**Issue by arijun** [microsoft/vscode-remote-release#2845]
Whenever VS code remote tries to connect with the remote machine it opens a new terminal window titled "Install". If my VPN is down it can try and fail to do that tens of times, leaving a "Install" terminal window open each time. When I click the trash icon to close the tty it clears the tty but doesn't close it.

![image](https://user-images.githubusercontent.com/4633429/80372719-a142b280-889c-11ea-82b5-49bc5dcc5388.png)

- VSCode Version: 1.43.2
- Local OS Version: Windows 10 1709
- Remote OS Version: Debian 8.10
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
1. Open a new remote  
2. Install window stays open

**Comment by arijun** [comment]
Is there any further info I can provide that might be a help in diagnosing the issue? Is there any workaround I can use besides reloading the window?

**Comment by roblourens** [comment]
Should be fixed now
