### ISSUE TITLE
Test: WSL2 support

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2849]
Ref - #2779

- [x] windows @aeschli
- [x] windows @Tyriar

Complexity: 5

---

### Preparation

- Install Windows Insiders build 18917 or later and WSL2:
  - https://docs.microsoft.com/en-us/windows/wsl/wsl2-install
  - 'Slow' ring will do it.
  - Install a WSL distro, e.g. Ubuntu, through the Windows Store.
  - Switch that distro to WSL2 (see again above link).
- Install Docker Desktop 'Edge':
  - https://download.docker.com/win/edge/Docker%20Desktop%20Installer.exe
- Enable WSL2 support in Docker Desktop and the WSL distro:
  - https://docs.docker.com/docker-for-windows/wsl-tech-preview/
  - Note that there are two checkboxes, one for the feature and one for the distro, each on a different page of Docker Desktop's settings.

### Testing

Test basic operations using `Remote-Containers` commands and the Remote Explorer while having:
- open a local folder under `\\wsl$\Ubuntu\...` (if Ubuntu is your distro).
- open the same folder(s) with the Remote-WSL extension.
- while being connected to a container with a WSL folder (starting from one of the two above) as its base.

You don't need to test 'attaching' to an existing container nor opening a container from a repository (these are not using WSL2). Only test opening from a folder with a devcontainer.json:
- with a single container: https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#single-container-with-dockerfile-or-image
- and with Docker Compose: https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#docker-compose

Check that Git credentials are forwarded from the WSL distro:
- Install Git and a Git credential helper in the WSL distro.
- Verify you can use `git` on a private repository without being asked for the credentials in the WSL distro.
- Verify you can do the same in a dev container started from a WSL folder.

### Notes

If using a Parallels VM, make sure to enable nested virtualization and be generous with RAM and cores:
![image](https://user-images.githubusercontent.com/9205389/80410657-3eb4db00-88cb-11ea-8cb6-30cb1d379a39.png)

**Comment by aeschli** [comment]
Great work!
