### ISSUE TITLE
Remote - SSH does not connect to remote Linux x86_64 host because it misreads output of uname command

### ISSUE THREAD

**Issue by jonnybaik** [microsoft/vscode-remote-release#285]
- VSCode Version: 1.34.20-insider (user setup)
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 16.04.6 LTS
- Remote Extension/Connection Type: SSH

**Steps to Reproduce:**

1. Run 'Remote-SSH: Connect to Host'
2. Connect to a host that runs a log-out script on exit.
3. Fail to connect to host due to the extension missing the output to the `uname` command and incorrectly reading a different output.

**Possible Cause and Explanation:**

I am trying to connect to a Linux box at work that runs a script on user exit to clean temporary files. It seems that when the "Remote - SSH" extension checks to see if the host is running `Linux x86_64`, it does not catch the return value of the `uname -ms` (which my remote system correctly outputs as `Linux x86_64`), but instead catches some other output from the post-log-out script that runs on my remote system. 

The error message I get from VSCode says:

`remote-ubuntu: unreachable or not Linux x86_64. (removing TMPDIR = /tmp/myusername/21914)`

If you look below at the output of `Remote - SSH`, the text in parentheses is clearly the last line of output from the log-out script on the remote machine and not the output to the `uname -ms` command, which can be seen near the bottom of the output. It seems that the extension is checking the last line of output instead of the output to the `uname` command.

**Output of `Remote - SSH`:**

```
Picking SSH host
Selected remote-ubuntu
Using SSH config file "C:\Users\username\.ssh\config"
Confirming that remote-ubuntu is a valid reachable host
Running type "C:\Users\username\AppData\Local\Temp\1\vscode-linux-multi-line-command-remote-ubuntu.sh" | ssh -F C:\Users\username\.ssh\config remote-ubuntu to confirm the host platform
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-142-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> Warning: Permanently added [redacted hostname] to the list of known hosts.
> 
> [...]
> [... output from log-in script removed ...]
> [...]
> 
> Linux x86_64
> cleaning up temporary directories
> removing TMPDIR = /tmp/myusername/21914
> 
"uname" terminal command done
remote-ubuntu: unreachable or not Linux x86_64. (removing TMPDIR = /tmp/myusername/21914)
```

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by roblourens** [comment]
Since the install script is no longer run in an interactive login shell, I am guessing this won't be an issue, let me know if that is not the case. (this is in the nightly ssh extension, stable update coming soon)

**Comment by jonnybaik** [comment]
Thanks, I can confirm that this bug is fixed for my use case.

**Comment by Ebenholt** [comment]
I hit this bug by having verbose output on in my ssh config
.ssh/config
HOST *
	LogLevel VERBOSE

Thanks for fixing it.

**Comment by roblourens** [comment]
I filed https://github.com/microsoft/vscode-remote-release/issues/665 for that @Ebenholt
