### ISSUE TITLE
Test: New devcontainer.json variables

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2851]
Ref - #2473

- [x] windows @egamma
- [x] macOS @deepak1556

Complexity: 3

---

The macOS assignment can also be done on Linux. (Not sure how to tell the bot.)

Test the new variables for the devcontainer.json: `${containerWorkspaceFolder}`, `${localWorkspaceFolderBasename}` and `${containerWorkspaceFolderBasename}`.

To get a setup with a devcontainer.json either use:
- a single container: https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#single-container-with-dockerfile-or-image
- or Docker Compose: https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#docker-compose

**Comment by deepak1556** [comment]
works well on macOS, couldn't test on linux.

**Comment by chrmarti** [comment]
@deepak1556 All properties get variables in their values substituted. `containerEnv` is a good test because it doesn't break anything and can be easily verified. 👍 

(You only need to do one platform, I wanted to give the choice between the two.)
