### ISSUE TITLE
Difficult to debug mocha and nodejs

### ISSUE THREAD

**Issue by brucemackenzie** [microsoft/vscode-remote-release#2853]
Issue Type: <b>Bug</b>

Really having trouble figuring out the magic sauce to allow for debugging mocha execution of typescript/nodejs app. Works fine outside of hosted container mode.

Extension version: 0.112.0
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.3.0
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Center ID NodeJS Contain…|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (4 x 2600)|
|Memory (System)|4.82GB (0.78GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment]
Can you pls share a repository that illustrates what you have tried but what did not work?

Do you succeed in debugging just node.js?

Is this specific to mocha debugging?
