### ISSUE TITLE
Test: Podman support

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2854]
Ref - #116

- [x] linux @mjbvz
- [x] linux @weinand

Complexity: 4

---

Install the latest version (to get a fix in conmon >= 2.0.14 https://github.com/containers/libpod/issues/5046#issuecomment-605612801) of Podman on Linux and add a symlink `docker` -> `podman` to the PATH.

Run the Smoke-Test (https://github.com/microsoft/vscode-remote-release/wiki/Remote-Containers-Smoke-Test) ignoring the Docker Compose part (not supported with Podman at the moment) and test basic operations using `Remote-Containers` commands and the Remote Explorer.

**Comment by weinand** [comment]
@chrmarti how do you install podman >= 2.0.14 on Ubuntu 18.04 LTE or 19.10 (on Parallels)?
I'm trying this for hours now...

**Comment by weinand** [comment]
Giving up on installing podman 2.0.14. 
Will test with podman 1.9.0

**Comment by chrmarti** [comment]
@weinand Sorry, it's `conmon` that needs to have version 2.0.14 or later. Podman 1.9.0 should work.

**Comment by PavelSosin-320** [comment]
@chrmarti 
Unfortunately, docker service provider resolution is not so simple: the same machine can have several providers:
**docker**, if neither podman is installed nor kubernetes orchestration is enabled - port 2375 or port 2376
**podman**, if podman is installed and docker is suppressed port ???
**kuberenetes** if it is enabled in the  Docker Desktop settings or minikube is installed - port 6443 
maybe docker swarm - port  2375/2376 ?
Nothing can prevent the installation of all 3 on the same machine. They don't conflict. Every CLI looks at its own dot file in the User-profile folder. **It is a user preference for what to use**.

**Comment by chrmarti** [comment]
@PavelSosin-320 #2887 will make the name and path of the Docker executable configurable so you can configure `podman` there. That will only work for Docker CLI compatible CLIs of course.

**Comment by Nuc1eoN** [comment]
I've got rootless podman working on archlinux, along with the package `podman-docker` which symlinks docker to podman I guess.

However vscode stil wouldn't recognize my config, saying "Failed to connect. Is Docker running?"

Is there something I'm missing?

**Comment by chrmarti** [comment]
@Nuc1eoN Check what is in the log (`F1` > `Remote-Containers: Show Log`). There is now also a setting for the Docker executable where you can set `podman`, with that you don't need `podman-docker` anymore.

Please open a new issue if this is not working as expected. 👍

**Comment by Nuc1eoN** [comment]
@chrisdias `Remote-Containers: Show Log` doesnt exist for me. Do I need a special setup?
Never used docker/podman through vscode, so I might be totally missing something :thinking:

**Comment by chrisdias** [comment]
@chrmarti see above ^^

**Comment by chrmarti** [comment]
@Nuc1eoN Make sure you are using the latest version of VS Code (1.46) and have the Remote-Containers extension installed (version 0.117.1).

**Comment by Nuc1eoN** [comment]
@chrisdias `Remote-Containers: Show Log` gives me an empty terminal with no output.
`Remote-Containers: Settings` shows the error:
```
Command 'Remote-Containers: Settings' resulted in an error (command 'remote-containers.settings' not found)
```

**Comment by Nuc1eoN** [comment]
Anyways do I even need the extension?
I am trying to make the built-in functionailty work for now:
![image](https://user-images.githubusercontent.com/2538022/84671291-7d5c2e80-af27-11ea-82ce-4bc4b4380a51.png)

**Comment by PavelSosin-320** [comment]
There is a common issue in Docker Desktop CE with docker logs. I suppose that although json-file log driver is the default the corresponding plugin is missed as docker plugin ls shows. The plugin mechanism is working generally because if I install a plugin it is shown but this specific one is missed and I didn't find it in the Dockerhub repository. Such plugins are platform-dependent, I afraid that there is no suitable for WSL yet  :(

**Comment by chrmarti** [comment]
That's the Docker extension, please open an issue for them including the value you set for `docker.host`. Thanks.

Open issue here: https://github.com/microsoft/vscode-docker/issues
