### ISSUE TITLE
.c, .h, .cc not suggesting C/C++ container definition

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2859]
#2844

https://en.wikibooks.org/wiki/C%2B%2B_Programming/Programming_Languages/C%2B%2B/Code/File_Organization lists a few other possible extensions for C++.

**Comment by egamma** [comment]
Added the additional C++ file types. Since the container definition is for C++ (and C++ is a different language than C) I've not added the c file types.
