### ISSUE TITLE
No language specific definitions proposed for .sql files

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2861]
#2844

There are two definitions including Postgres.

Should we have more SQL related definitions? /cc @Chuxel

**Comment by chrmarti** [comment]
There is also a definition including MariaDB.

**Comment by egamma** [comment]
Databases are currently not detected. We could add .sql as a supported language to the corresponding container definitions.
```
Python 3 & PostgreSQL: Python
Node.js 12 & PostgresSQL: Node.js, JavaScript, Postgres DB
```

**Comment by Chuxel** [comment]
> Should we have more SQL related definitions? /cc @Chuxel

Generally there's value in doing that, yes. They're good examples of Docker Compose use and should be pretty common. However, we'd need to carve out capacity to do it - particularly in areas where the immediate team is not an expert. The PHP one was added by a community member which was awesome.
