### ISSUE TITLE
Questionable config ranking

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-remote-release#2863]
re #2844

* open https://github.com/microsoft/vscode-github-issue-notebooks/
* run 'add dev container config'

This is a typescript project, a vs code extension, so I would expect that "node & typescript" shows higher up

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/1794099/80485890-7ae34c80-895a-11ea-928a-67f8f9f6db0c.png">

**Comment by egamma** [comment]
@jrieken here is what I did:
- git clone the repo
- npm install
- yarn watch
- Add dev container config
I'm getting this sort order with TypeScript higher up in the list. Any hint what you did do differently?

![image](https://user-images.githubusercontent.com/172399/80526738-82731780-8993-11ea-810e-2b8df14eeb75.png)

**Comment by egamma** [comment]
I get the same order after running the integration tests which add vscode to .vscode-test folder.

One approach is to honour the .gitignore file or to hard code the exclusion of .vscode-test...
