### ISSUE TITLE
Having Powershell 7 as default integrated terminal makes remote connection fail

### ISSUE THREAD

**Issue by jakegt1** [microsoft/vscode-remote-release#2872]
- VSCode Version: 1.44.2
- Local OS Version: Windows 10 2004 RP
- Remote OS Version: Windows 10 1903
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Use Powershell 7 in integrated.terminal.shell.windows
2. Connect to remote server

Fails to start the server and says to read logs on server, server logs are empty.

Fixed when i removed the field.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by rzhao271** [comment]
Closing this issue as part of housekeeping. @jakegt1 feel free to reply if this issue still occurs for you on the latest version of VS Code (preferably Insiders edition).
