### ISSUE TITLE
When opening large files on remote, connection becomes unstable and remote keeps trying to reconnect non stop

### ISSUE THREAD

**Issue by stemoor** [microsoft/vscode-remote-release#2874]
I have been having this issue that whenever I try to open a large file (231kb) in the remote machine, the connection stops and Remote SSH keeps on trying to reconnect endlessly. The only solution I found is to try and close the file as fast as possible and reload window multiple times until the connection becomes stable again. 

I am using the latest version of Remote SSH and Visual studio code 1.44.2

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/1087
