### ISSUE TITLE
Containers WSL2: `Command failed: docker info`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#2876]
Testing #2849

- have an Alpine WSL2 distro that is not the default distro
- in the Docker Desktop settings the distro is enabled for integration
- reopening a folder from that distro fails as `docker` can not be found

**Comment by chrmarti** [comment]
Is there a `docker` executable in the distro when you check on the command line? Maybe the WSL2 integration of Docker Desktop malfunctioned? (Related: https://github.com/microsoft/vscode-remote-release/issues/2868)

**Comment by aeschli** [comment]
No, `docker` is not on the path of the Alpine distro. But I have  `Alpine` checked in the Docker Desktop settings.
So yes, this is for sure a Docker Desktop issue. Either the integration failed, or it has to do with Alpine.
I think what needs to be done on our side is a better error dialog with a link to help (how to enable the integration, how to debug it, known limitations (Alpine?), how to file issues against Docker Desktop).

**Comment by chrmarti** [comment]
Fixed with #2868 then. That checks for `docker` on the WSL side and shows an error dialog with a link to an article about the WSL2 integration tech preview on docker.com. (The same linked from the test item.)
