### ISSUE TITLE
extensions-download-dir doesn't add `.vsix` extension to downloads

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-remote-release#2878]
From #2842

**Repro**
1. Using `extensions-download-dir`
1. Download an extension

**Bug**
The downloaded file does not include a file extension. It should likely end with `.vsix`

**Comment by mjbvz** [comment]
I suspect users are not supposed to look in the download directory but I just found this a little weird while testing #2842

**Comment by sandy081** [comment]
Yeah this is not meant for users and only for caching. So it is not important to have .vsix extension.
