### ISSUE TITLE
extensions-download-dir doesn't seem to respect 20 cache limit until restarting VS Code

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-remote-release#2879]
Refs #2842

**Repro**
1. On MacOS using `--extensions-download-dir `
1. Download a bunch of extension packs

**Bug**
It looks like we just keep accumulating cached extensions until VS Code is restarted:

<img width="689" alt="Screen Shot 2020-04-28 at 2 19 18 PM" src="https://user-images.githubusercontent.com/12821956/80539044-9f8bf400-895b-11ea-976f-b139a576eb72.png">

My expectation was that the 20 extension limit would also be enforced while VS Code is still running

**Comment by mjbvz** [comment]
Reading through #2842 again, this does seem by-design but it means that once you hit the 20 download limit, you will always have more than 20 extensions in that cache

**Comment by sandy081** [comment]
Yeah clean up is always done on start up.
