### ISSUE TITLE
Docker bin PATH isn't discovered on Mac with Powershell as user shell

### ISSUE THREAD

**Issue by lypanov** [microsoft/vscode-remote-release#288]
VSCode Version: 1.34.0-insider
Local OS Version: macOS Mojave 10.14.4
Remote OS Version: node:lts (Docker Image)
Remote Extension/Connection Type: Docker
Docker Desktop for Mac: 2.0.0.2 (30215)
Docker Engine: 18.09.1

Steps to Reproduce:
Install Docker Desktop for Mac ( docker command is placed to /usr/local/bin ).
Install Powershell
Setup Powershell as user shell using chsh
Run git clone https://github.com/Microsoft/vscode-remote-try-node
Open vscode-remote-try-node using vscode-insider
Run Open Folder in Container on vscode-insider
I got an error that Docker version 17.06.1 or later required

I assume Powershell is being run with -lic which it of course doesn't support. If the fix should be in Powershell, or VS Code itself, I'm unsure. But it'd be lovely to have different MS products work together.

**Comment by egamma** [comment]
@lypanov not sure this is related to Powershell, can you reproduce the problem when you use bash?

See also https://github.com/microsoft/vscode-remote-release/issues/74

**Comment by lypanov** [comment]
Before creating this issue I fixed it locally by using chsh to switch back to bash (and then modified my terminal application to get me back to lovely Powershell again). Reading https://github.com/microsoft/vscode-remote-release/issues/35#issuecomment-489921362 led me to creating the issue and pointing out the lack of -lic support. Part of it is already fixed in Powershell but more is probably needed ( https://github.com/PowerShell/PowerShell/issues/3600 ).

**Comment by chrmarti** [comment]
https://github.com/microsoft/vscode-remote-release/issues/2887 added a setting for the Docker CLI path.
