### ISSUE TITLE
VS Code Remote connection suddenly started crashing 

### ISSUE THREAD

**Issue by abhishekr700** [microsoft/vscode-remote-release#2889]
- VSCode Version: 1.44.2
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 18 x86_64
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

Honestly, I have not changed a single file in the ssh configuration. It worked until yesterday, started failing today, When creating connection, the window just crashes. Clicking reopen keeps on repeating the same thing.

Here is the ssh log
[1-Remote - SSH.log](https://github.com/microsoft/vscode-remote-release/files/4551727/1-Remote.-.SSH.log)
[main.log](https://github.com/microsoft/vscode-remote-release/files/4551730/main.log)

1. Connect with ssh

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by rzhao271** [comment]
Closing for now as part of housekeeping. @abhishekr700 feel free to reply if this issue still occurs for you on the latest version of VS Code (preferably Insiders edition).
