### ISSUE TITLE
Welcome screen after attaching to running container

### ISSUE THREAD

**Issue by thomiel** [microsoft/vscode-remote-release#289]
Whenever I attach VSCode to a container, it starts with no specific folder opened. What I would expect is that it opens my workspace folder on start and apply the workspace settings. 
![Bildschirmfoto von 2019-05-12 02-14-04](https://user-images.githubusercontent.com/11477743/57576621-500b9a00-7464-11e9-9ad4-3d6be8909592.png)

**Comment by egamma** [comment]
When attaching to a running container it is not known what your current workspace folder is. Therefore the user has to pick the folder.

To create a container setup for a particular workspace folder, we recommend to create a `devcontainer.json` pls see https://code.visualstudio.com/docs/remote/containers#_quick-start-open-a-folder-in-a-container
