### ISSUE TITLE
Starting container with podman doesn't finish

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-remote-release#2890]
Refs: https://github.com/microsoft/vscode-remote-release/issues/2854

I was following the steps to run the Smoke-Test (https://github.com/microsoft/vscode-remote-release/wiki/Remote-Containers-Smoke-Test).
The step "Wait for container to start and Code to connect to it." did not finish for me.

I took this screenshot after 10 minutes of waiting:

<img width="1169" alt="2020-04-29_15-14-18" src="https://user-images.githubusercontent.com/1898161/80600585-e695ea00-8a2c-11ea-9b70-9e73093228c2.png">

After the "Developer: Reload Window" command everything seemed to be ok:

<img width="1168" alt="2020-04-29_15-22-31" src="https://user-images.githubusercontent.com/1898161/80600842-41c7dc80-8a2d-11ea-90ef-81fd3a113b68.png">

**Comment by chrmarti** [comment]
@weinand What do you get for `podman info`? It looks like `podman events` does not output a start event for that container. Could you retry with the `remote.containers.logLevel` setting set to `trace` and attach the full container log? (That will include the events.)

**Comment by weinand** [comment]
After updating to podman 1.9.1 I was no longer able to reproduce the problem.

**Comment by chrmarti** [comment]
Thanks!
