### ISSUE TITLE
Sql Server Connection Integrated Security not working as expected when debugging .NET Core  application via VScode remote SSH

### ISSUE THREAD

**Issue by Smoovsky** [microsoft/vscode-remote-release#2892]
Hi there,
I hope this is the right place to report this issue.

I'm running on the latest version of vscode remote SSH, the target platform is Windows(for integrate security to work).
When trying to connect to sql server database with integrated security during a remote debug session, anonymous login exception always pop up as I can see it was trying to login as **NT Anonymous**.
I can confirm that on the remote machine, the debugged process was running under the correct domain account(which I configured SSH), even with elevated privilege. Programmatically, I can acquire current user principal with 
```
WindowsIdentity.GetCurrent()
```
which also appears to be the correct one.

Is this expected behavior, what can I do if I want to use integrated security during a remote debug session?

Thanks.

**Comment by roblourens** [comment]
We literally just run a command with "ssh", we have no control over this.
