### ISSUE TITLE
remote install of vscode-server stalls

### ISSUE THREAD

**Issue by ICO-Dev** [microsoft/vscode-remote-release#2898]
843160c8ef0c: running
Acquiring lock on /home/ico-install/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.ico-install.ff915844119ce9485abfe8aa9076ec76b5300ddd
\ln /home/ico-install/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.ico-install.ff915844119ce9485abfe8aa9076ec76b5300ddd.target /home/ico-install/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.ico-install.ff915844119ce9485abfe8aa9076ec76b5300ddd
Found existing installation at /home/ico-install/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd...

Found running server...

*
* Reminder: You may only use this software with Visual Studio family products, 
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
*

Checking server status on port 26567 with wget
843160c8ef0c: start     
sshAuthSock====
agentPort==26567==      
osReleaseId==ol==       
arch==x86_64==
webUiAccessToken====    
tmpDir==/run/user/1000==
platform==linux==       
843160c8ef0c: end       

At this point the cursor slowly marches across the screen. This particular time I let it run for 12 hours...
The cursor made all the way across the screen, wrapped around and was halfway across again.

"Remote.SSH: Allow Local Server Download" and "Remote: Download Extensions Locally" are both checked in Settings.

Target machine is OL 7.8

**Comment by lingelizabeth** [comment]
I'm having this issue right now, did you find a fix?

**Comment by rzhao271** [comment]
@ICO-Dev closing for now. I'm not sure if this issue depends on the version of VS Code, but feel free to reply either way if this issue still occurs for you.
