### ISSUE TITLE
Does not work with LCOW

### ISSUE THREAD

**Issue by giggio** [microsoft/vscode-remote-release#29]
- VSCode Version: insiders
- Local OS Version: Microsoft Windows [Version 10.0.17763.437]
- Remote OS Version: does not matter
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Use Docker for Windows with Windows containers
0. Pull a Linux version, i.e. `docker pull --platform=linux node:12`.
0. Use that image on your remote settings
0. Try to open the folder remotely

When you try to open the folder it fails. This is related to https://github.com/moby/moby/issues/35425
You get an error `invalid mount config for type "bind": source path must be a directory.` because of the `.gitconfig` file from HOME.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by egamma** [comment]
@giggio this is a known limitation.

@chuxel we should mention this in the docs.

**Comment by jsheetzati** [comment]
Are we able to customize the run command? I want to replace how the extension is binding the .gitconfig. I rather just have it bind the entire directory to get around the limitation.

**Comment by Chuxel** [comment]
@jsheetzati The "runArgs" property in devcontainer json lets you specify additional volume mounts (e.g. via -v or --mount).  You can also change the default mount using the "workspaceMount" property combined with "workspaceFolder" to tell VS Code where you set the mount point in the container.  That supports anything the --mount property supports.

**Comment by jsheetzati** [comment]
Thanks @Chuxel. I was playing around with those options, but it seems like there is not a way to customize how .gitconfig gets binded. Due to LCOW not supporting binding a single file, I was hoping to override the .gitconfig binding and just bind my entire user directory.

```
Run: docker run -a STDOUT -a STDERR --mount src=c:\Dev\cea\Web,dst=/workspace,type=bind -v /host_mnt/c/Users/jsheetz/.gitconfig:/root/.gitconfig -l vsch.quality=stable -l vsch.local.folder=c:\Dev\cea\Web -l vsch.remote.devPort=0 vsc-web-8b25b88147e98f539fb8bcaaf880810d /bin/sh -c echo Container started ;  while sleep 1; do :; done
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: invalid volume specification: '/host_mnt/c/Users/jsheetz/.gitconfig:/root/.gitconfig'.
```

**Comment by Chuxel** [comment]
@jsheetzati Ahhh go it - that's the key.  Very good to know - thank you for clarifying.  @chrmarti - FYI.  I know we've talked about giving the option to alter the .gitconfig mount for other reasons (#509), but this is another hit on that particular issue.

**Comment by chrmarti** [comment]
I would prefer not having a separate property in the devcontainer.json for this.

We could allow an array for `workspaceMount` and have the default include the `.gitconfig` mount. You could then overwrite both the workspace and the `.gitconfig` mounts by setting that property. 🤔

**Comment by Chuxel** [comment]
@chrmarti That works from my perspective. Would both a string or single entry then omit the .gitconfig mapping?  Or just an array with one value?

**Comment by chrmarti** [comment]
The presence of the property would omit the .gitconfig mapping unless it is explicitly included.

Another option would be to copy the .gitconfig over if the exists on the host, but not in the container. (We currently have to inspect the image to get at the home folder in /etc/passwd before we launch the actual container with the .gitconfig mount which takes another slice of our startup time.)

**Comment by Chuxel** [comment]
I believe this is now resolved since we're copying the .gitconfig file rather than mounting it, correct?

**Comment by jsheetzati** [comment]
Unfortunately, still seeing issues using LCOW.
```
Run: docker cp 61de04ed6b185c746f9bc34c8e696347046420abc76bc70388b7b315001fa558:/etc/passwd -
Error response from daemon: filesystem operations against a running Hyper-V container are not supported

Command failed: C:\Program Files\Docker\Docker\Resources\bin\docker.exe cp 61de04ed6b185c746f9bc34c8e696347046420abc76bc70388b7b315001fa558:/etc/passwd -
```

**Comment by chrmarti** [comment]
We no longer mount any files into the container (unless configured in the devcontainer.json) and we no longer use `docker cp`. Is this still an issue? If so, what does the log show?

**Comment by giggio** [comment]
@chrmarti I'm not sure, I haven't use LCOW in a long time. After WSL2 and it's Docker integration I don't need it anymore. If nobody can produce a repro, feel free to close the issue.

**Comment by chrmarti** [comment]
@giggio Thanks, closing then.
