### ISSUE TITLE
Failed to parse remote port 

### ISSUE THREAD

**Issue by stovv** [microsoft/vscode-remote-release#290]
Issue Type: <b>Bug</b>

From **Windows 10 16299** to **SUSE Linux Enterprise Server 11 (x86_64)**

I installed the vscode-server using the vscode-remote.sh script from the tmp directory, but after restarting the output was

```
SSH Resolver called for "ssh-remote+test_serv"
SSH Resolver called for host: test_serv
Setting up SSH remote "test_serv"
Using commit id "57b550c559b945eb9d871dbf2b2e4cb9e31e2551" and quality "insider" for server
Install and start server if needed
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> ************************************************
> Use of this system by unauthorized persons or
> in an unauthorized manner is strictly prohibited
> ************************************************
> 
> 
> Password:
> 
> 
> bash: no job control in this shell
> 
> 
> stty: standard input: Inappropriate ioctl for device
> stty: standard input: Inappropriate ioctl for device
> stty: standard input: Inappropriate ioctl for device
> stty: standard input: Inappropriate ioctl for device
> stty: standard input: Inappropriate ioctl for device
> stty: standard input
> Found existing installation...
> Found running server...
> Дч╗hШ<ЬЦЛj╗hШ=Ь?П.╗hШ>Ь╚Ж:╗hШ?ЬЗИ╗hШ@ЬNРs╗hШAЬ=Ж@╗hШHЬ╪Сm╗hШIЬоЕ4╗hШJЬEСd╗hШKЬ+Бa╗hШLЬъП'╗hШMЬ╚Ж?╗hШNЬП?╗hШOЬ Бл╗hШPЬwЗ
> ╗hШQЬcР╗hШRЬ?Иs╗hШSЬEСp╗hШTЬIЗч╗hШUЬЙО?╗hШVЬ┼Л╗hШWЬ?П?╗hШXЬ?О=╗hШYЬПОи╗hШZЬзПO╗hШ[ЬъПЗ╗hШ\Ь:З│╗hШ]Ь?Д?╗hШ^Ь'О7╗hШ_ЬА-
> ╗hШ`ЬZЖУ╗hШaЬёП?╗hШbЬГ^╗hШcЬsАл╗hШdЬЁД<╗hШeЬDЖч╗hШfЬШНO╗hШgЬ'Со╗hШhЬ?П<╗hШiЬEС<╗hШjЬ?Иm╗hШmЬяАI╗hШnЬ^Пg╗hШoЬШНR╗hШpЬEС?╗
Л╪╗lШDЯ?Л?╗lШEЯ?Л%╗lШFЯ?Лu╗lШGЯ?Лv╗lШHЯ?Лw╗lШIЯ?Лe
...(too long output)
> ╗lШJЯ?Лf╗lШKЯ?Лg╗lШLЯ?Лh╗lШMЯчЛ\╗lШNЯчЛ]╗lШOЯчЛ^╗lШPЯЛJ╗lШQЯЛK╗lШRЯ·Л7╗lШSЯ№Л%╗lШTЯєЛ"╗lШUЯєЛ#╗lШVЯєЛ$╗lШWЯ?Л╗lШXЯ?Л╗
> lШYЯ┐Л<╗lШZЯ-Лw╗lШ[Я-Лx╗lШ\ЯRЛ╪╗lШ]ЯRЛ?╗lШ^ЯRЛ%╗lШ_
"install" terminal command done
Received install output: lШYЯ┐Л<╗lШZЯ-Лw╗lШ[Я-Лx╗lШ\ЯRЛ╪╗lШ]ЯRЛ?╗lШ^ЯRЛ%╗lШ_
Failed to parse remote port from server output: lШYЯ┐Л<╗lШZЯ-Лw╗lШ[Я-Лx╗lШ\ЯRЛ╪╗lШ]ЯRЛ?╗lШ^ЯRЛ%╗lШ_
```

Extension version: 0.37.0
VS Code version: Code - Insiders 1.34.20-insider (57b550c559b945eb9d871dbf2b2e4cb9e31e2551, 2019-05-10T17:36:45.765Z)
OS version: Windows_NT x64 10.0.16299
Fetching remote diagnostics for 'SSH' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed.
</details>

**Comment by stovv** [comment]
After trying to start again, this error appeared
```
Using commit id "57b550c559b945eb9d871dbf2b2e4cb9e31e2551" and quality "insider" for server
Install and start server if needed
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> ************************************************
> Use of this system by unauthorized persons or
> in an unauthorized manner is strictly prohibited
> ************************************************
> 
> 
> Password:
> 
> 
> bash: no job control in this shell
> 
> stty: standard input: Inappropriate ioctl for device
> stty: standard input: Inappropriate ioctl for device
> 
> 
> stty: standard input: Inappropriate ioctl for device
> stty: standard input: Inappropriate ioctl for device
> stty: standard input: Inappropriate ioctl for device
> stty: standard input: Inappropriate ioctl for device
> stty: standard input: Inappropriate ioctl for device
> stty: standard input: Inappropriate ioctl for device
> 
> Found existing installation...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> c1879836-2124-4856-aef0-a07e590aa450==33891==
> Warning: bad ps syntax, perhaps a bogus '-'? See http://procps.sf.net/faq.html
> 
"install" terminal command done
Received install output: Warning: bad ps syntax, perhaps a bogus '-'? See http://procps.sf.net/faq.html
Failed to parse remote port from server output: Warning: bad ps syntax, perhaps a bogus '-'? See http://procps.sf.net/faq.html
```

**Comment by xuchen-plus** [comment]
Same problem here.

**Comment by juancri** [comment]
Got this error connecting from Ubuntu (16.04) to Amazon Linux (AL2012.03):

```
SSH Resolver called for "ssh-remote+HIDDENHOSTNAME
SSH Resolver called for host: HIDDENHOSTNAME
Setting up SSH remote "HIDDENHOSTNAME"
Using commit id "57b550c559b945eb9d871dbf2b2e4cb9e31e2551" and quality "insider" for server
Install and start server if needed
> bash: no job control in this shell
> Found existing installation...
> Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
> Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> 397d4fc5-1608-42d0-8c0a-c8fd2e006a4b==1:1
> 1:13
> 1:36859==
"install" terminal command done
Received install output: 1:36859==
Failed to parse remote port from server output: 1:36859==
```

**Comment by stovv** [comment]
I read this [guide](https://code.visualstudio.com/docs/remote/troubleshooting#_installing-a-supported-ssh-client) and removed OpenSSH from my pc and add **GIT BASH** bin folder to **%PATH%** and... the error has changed, probably for the better
```
SSH Resolver called for "ssh-remote+test_serv"
SSH Resolver called for host: test_serv
Setting up SSH remote "test_serv"
Using commit id "57b550c559b945eb9d871dbf2b2e4cb9e31e2551" and quality "insider" for server
Install and start server if needed
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> ************************************************
> Use of this system by unauthorized persons or
> in an unauthorized manner is strictly prohibited
> ************************************************
> Password:
> 
> 
> bash: no job control in this shell
> 
> Found existing installation...
> Warning: bad ps syntax, perhaps a bogus '-'? See http://procps.sf.net/faq.html
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> ee73a5d6-c487-4d47-82bd-521fab921a92==60407==
> 
"install" terminal command done
Received install output: ee73a5d6-c487-4d47-82bd-521fab921a92==60407==
Server is listening on port 60407
Spawning tunnel with: ssh  nnspidt005 -L localhost:13431:localhost:60407 "echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity"
Spawned SSH tunnel between local port 13431 and remote port 60407
Waiting for ssh tunnel to be ready
> 
> ************************************************
> Use of this system by unauthorized persons or
> in an unauthorized manner is strictly prohibited
> ************************************************
> Password:
> 
> 
> Connected to SSH Host - Please do not close this terminal
> 
Tunneling remote port 60407 to local port 13431
Resolving "ssh-remote+nnspidt005" to "localhost:13431", attempt: 1

```

**Comment by xuchen-plus** [comment]
Found a workaround. Add
`export PS_PERSONALITY=bsd`
to suppress the "bogus -"  warning from the output of `ps` command.

**Comment by stovv** [comment]
>The factory method of "vs/platform/product/node/product" has thrown an exception
> SyntaxError: /home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/product.json: Un
> expected end of JSON input
>     at JSON.parse (<anonymous>)
>     at Object.Module._extensions..json (internal/modules/cjs/loader.js:708:27)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Function.i [as __$__nodeRequire] (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e
> 7afabd50d01/out/vs/loader.js:31:381)
>     at Object.<anonymous> (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/ou
> t/vs/server/remoteExtensionHostAgent.js:227:765)
>     at Function.t._safeInvokeFunction (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7a
> fabd50d01/out/vs/loader.js:19:945)
>     at Function.t._invokeFactory (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd5
> 0d01/out/vs/loader.js:20:175)
>     at t.complete (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loa
> der.js:20:412)
>     at s._onModuleComplete (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/o
> ut/vs/loader.js:30:614)
>     at s._resolve (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loa
> der.js:30:174)
>     at s.defineModule (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs
> /loader.js:24:534)
>     at o (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js:31
> :789)
>     at c (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js:17
> :118)
>     at Object.<anonymous> (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/ou
> t/vs/server/remoteExtensionHostAgent.js:227:579)
>     at Object.<anonymous> (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/ou
> t/vs/server/remoteExtensionHostAgent.js:388:595)
>     at t._createAndEvalScript (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d0
> 1/out/vs/loader.js:17:162)
>     at /home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js:16:76
> 2
>     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
> SyntaxError: /home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/product.json: Un
> expected end of JSON input
> 
>     at JSON.parse (<anonymous>)
>     at Object.Module._extensions..json (internal/modules/cjs/loader.js:708:27)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Function.i [as __$__nodeRequire] (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e
> 7afabd50d01/out/vs/loader.js:31:381)
>     at Object.<anonymous> (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/ou
> t/vs/server/remoteExtensionHostAgent.js:227:765)
>     at Function.t._safeInvokeFunction (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7a
> fabd50d01/out/vs/loader.js:19:945)
>     at Function.t._invokeFactory (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd5
> 0d01/out/vs/loader.js:20:175)
>     at t.complete (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loa
> der.js:20:412)
>     at s._onModuleComplete (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/o
> ut/vs/loader.js:30:614)
>     at s._resolve (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loa
> der.js:30:174)
>     at s.defineModule (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs
> /loader.js:24:534)
>     at o (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js:31
> :789)
>     at c (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js:17
> :118)
>     at Object.<anonymous> (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/ou
> t/vs/server/remoteExtensionHostAgent.js:227:579)
>     at Object.<anonymous> (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/ou
> t/vs/server/remoteExtensionHostAgent.js:388:595)
>     at t._createAndEvalScript (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d0
> 1/out/vs/loader.js:17:162)
>     at /home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js:16:76
> 2
>     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
> { errorCode: 'load',
>   moduleId: 'iconv-lite',
>   neededBy: [ 'vs/base/node/encoding' ],
>   detail:
>    { Error: Cannot find module 'iconv-lite'
>        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>        at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>        at Module.require (internal/modules/cjs/loader.js:637:17)
>        at require (internal/modules/cjs/helpers.js:20:18)
>        at t.load (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/load
> er.js:16:247)
>        at e.load (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/load
> er.js:13:587)
>        at i (/home/user.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js
> :28:371)
>        at Object.errorback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/o
> ut/vs/loader.js:28:492)
>        at e.triggerErrorback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01
> /out/vs/loader.js:13:952)
>        at /home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js:13
> :657
>        at ReadFileContext.callback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afab
> d50d01/out/vs/loader.js:16:617)
>        at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13) code: 'MODULE_NOT_FOUND' } }
> { errorCode: 'load',
>   moduleId: 'applicationinsights',
>   neededBy: [ 'vs/platform/telemetry/node/appInsightsAppender' ],
>   detail:
>    { Error: Cannot find module 'applicationinsights'
>        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>        at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>        at Module.require (internal/modules/cjs/loader.js:637:17)
>        at require (internal/modules/cjs/helpers.js:20:18)
>        at t.load (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/load
> er.js:16:247)
>        at e.load (/home/user.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/load
> er.js:13:587)
>        at i (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js
> :28:371)
>        at Object.errorback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/o
> ut/vs/loader.js:28:492)
>        at e.triggerErrorback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01
> /out/vs/loader.js:13:952)
>        at /home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js:13
> :657
>        at ReadFileContext.callback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afab
> d50d01/out/vs/loader.js:16:617)
>        at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13) code: 'MODULE_NOT_FOUND' } }
> 
> { errorCode: 'load',
>   moduleId: 'semver',
>   neededBy:
>    [ 'vs/workbench/services/extensions/node/extensionPoints',
>      'vs/platform/extensionManagement/node/extensionManagementService',
>      'vs/code/node/cliProcessMain' ],
>   detail:
>    { Error: Cannot find module 'semver'
>        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>        at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>        at Module.require (internal/modules/cjs/loader.js:637:17)
>        at require (internal/modules/cjs/helpers.js:20:18)
>        at t.load (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/load
> er.js:16:247)
>        at e.load (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/load
> er.js:13:587)
>        at i (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js
> :28:371)
>        at Object.errorback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/o
> ut/vs/loader.js:28:492)
>        at e.triggerErrorback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01
> /out/vs/loader.js:13:952)
>        at /home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js:13
> :657
>        at ReadFileContext.callback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afab
> d50d01/out/vs/loader.js:16:617)
>        at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13) code: 'MODULE_NOT_FOUND' } }
> { errorCode: 'load',
>   moduleId: 'yauzl',
>   neededBy: [ 'vs/base/node/zip' ],
>   detail:
>    { Error: Cannot find module 'yauzl'
>        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>        at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>        at Module.require (internal/modules/cjs/loader.js:637:17)
> 
>        at require (internal/modules/cjs/helpers.js:20:18)
>        at t.load (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/load
> er.js:16:247)
>        at e.load (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/load
> er.js:13:587)
>        at i (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js
> :28:371)
>        at Object.errorback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/o
> ut/vs/loader.js:28:492)
>        at e.triggerErrorback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01
> /out/vs/loader.js:13:952)
>        at /home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js:13
> :657
>        at ReadFileContext.callback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afab
> d50d01/out/vs/loader.js:16:617)
>        at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13) code: 'MODULE_NOT_FOUND' } }
> { errorCode: 'load',
>   moduleId: 'yazl',
>   neededBy: [ 'vs/base/node/zip' ],
>   detail:
>    { Error: Cannot find module 'yazl'
>        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>        at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>        at Module.require (internal/modules/cjs/loader.js:637:17)
>        at require (internal/modules/cjs/helpers.js:20:18)
>        at t.load (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/load
> 
> er.js:16:247)
>        at e.load (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/load
> er.js:13:587)
>        at i (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js
> :28:371)
>        at Object.errorback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/o
> ut/vs/loader.js:28:492)
>        at e.triggerErrorback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01
> /out/vs/loader.js:13:952)
>        at /home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js:13
> :657
>        at ReadFileContext.callback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afab
> d50d01/out/vs/loader.js:16:617)
>        at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13) code: 'MODULE_NOT_FOUND' } }
> { errorCode: 'load',
>   moduleId: 'minimist',
>   neededBy: [ 'vs/server/remoteExtensionHostAgent' ],
>   detail:
>    { Error: Cannot find module 'minimist'
>        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>        at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>        at Module.require (internal/modules/cjs/loader.js:637:17)
>        at require (internal/modules/cjs/helpers.js:20:18)
>        at t.load (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/load
> er.js:16:247)
>        at e.load (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/load
> er.js:13:587)
>        at i (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js
> :28:371)
>        at Object.errorback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/o
> ut/vs/loader.js:28:492)
>        at e.triggerErrorback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01
> /out/vs/loader.js:13:952)
>        at /home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/loader.js:13
> :657
>        at ReadFileContext.callback (/home/user/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afab
> d50d01/out/vs/loader.js:16:617)
>        at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13) code: 'MODULE_NOT_FOUND' } }
> 4039db9e-2391-4f3f-bcd1-6a38918dcfc0====
> 
"install" terminal command done
Received install output: 4039db9e-2391-4f3f-bcd1-6a38918dcfc0====
Failed to parse remote port from server output: 4039db9e-2391-4f3f-bcd1-6a38918dcfc0====

**Comment by matthewess** [comment]
```shell
remote-ssh-nightly@2019.6.29700
darwin x64
SSH Resolver called for "ssh-remote+devbox", attempt 1
SSH Resolver called for host: devbox
Setting up SSH remote "devbox"
Using commit id "c7d83e57cd18f18026a8162d042843bda1bcf21f" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_7.9p1, LibreSSL 2.7.3
Install and start server if needed
> Found existing installation at /nail/home/mess/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f...
> Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Checking server status with wget
> fee48fdd-17de-4e1c-a114-82f8daf22132==34351====
"install" terminal command done
Received install output: fee48fdd-17de-4e1c-a114-82f8daf22132==34351====
Failed to parse remote port from server output: fee48fdd-17de-4e1c-a114-82f8daf22132==34351====```

**Comment by juan-kabbali** [comment]
Hi, sometimes it happens because possibly a vscode-server ssh is already running from previous connections. 

So you could try killing legacy vscode processes in the target machine. 

`kill $(ps aux | grep vscode | awk '{print $2}')
`

It works for me.

**Comment by kylrth** [comment]
I also often need to use `Remote-SSH: Connect to Host...` from the command palette (`Ctrl+Shift+P`) to instead of just opening the remote workspace from `File -> Open Recent`.

I've also done `rm -rf ~/.vscode-server` on the remote, but I'm not sure if that's what has fixed it.

**Comment by carlinmack** [comment]
Reinstalling VS Code fixed this error for a day but the error is back now. Performing the two previous comments doesn't fix it. Strangely `kill $(ps aux | grep vscode | awk '{print $2}')` returns `kill: (4593) - No such process` and subsequent reruns increases the PID. I assume that somehow the process is continuously starting and restarting? Trying to guess the PID to kill doesn't seem to work either. I've been trying to fix this issue for 2-3 weeks now.

**Comment by kylrth** [comment]
That happens because the grep also captures the grep process because it
contains the word "vscode", but by the time the kill command tries to kill
that PID the grep process is already over. The increasing PID is just
because successive calls to grep will have an increasing process number.

**Comment by bringtree** [comment]
~/.vscode-server need access permission。

**Comment by muniryasir** [comment]
After an update yesterday I faced the same issue, my target machine is Debian 9 and host is Windows 10, I tried all solutions, listed in the thread. Debian 9 is AWS micro instance

**Comment by muniryasir** [comment]
fixed on its own after another update and 1 day of keeping it closed!

**Comment by mdutton3** [comment]
I was also having this issue and it was fixed with an update.  This is dumb, but it caught me -- you need to update the Remote SSH extension, and vscode itself.

**Comment by roblourens** [comment]
Closing as lots has changed - please file new issues with the log if anyone is still having trouble.
