### ISSUE TITLE
PR in Dev Container - Pick list doesn't go away

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-remote-release#2904]
Version: 1.45.0-insider
Commit: a0fe37870c42e0704a492cdc6b8550b4cf23f63c
Date: 2020-04-30T05:36:26.465Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0

Extensions needed:

Nightly GitHub PR extension
Remote Containers extension

Open a repo/workspace that has a pull request you can work on
Make sure the workspace/repo does NOT already have a devcontainer in it
Right click on the pr and choose "Checkout Pull Request in a Dev Container"

The container picker comes up, search for Node (in my case) and pick one.

Result: Nothing appears to happen, but I think it created the devcontainer, but the quick pick list of containers doesnt go away:

![image](https://user-images.githubusercontent.com/1487073/80767866-c6822b80-8afd-11ea-82a5-aa3c04fc5199.png)

**Comment by egamma** [comment]
Always hide the quick pick https://github.com/microsoft/vscode-remote-release/issues/2904
