### ISSUE TITLE
Permission denied despite owning file; Git interference

### ISSUE THREAD

**Issue by Smerdokryl** [microsoft/vscode-remote-release#2908]
- VSCode Version: 1.44.2
- Local OS Version: 10.0.19041.207
- Remote OS Version: Debian (uh.. the one from windows store? Unsure about version number)
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. >su username
2. Edit file in Code, everything is fine (file is `-rw-rw-rw- 1 username username`)
3. Do something in git. Say, rebase, such that git reports this file as having a conflict
4. Open code to edit file again, say to resolve the conflict
5. Cannot save file because EACCES: permission denied, open 'file path'
6. Check to discover that file is now `-rw-r--r-- 1 username username` (which is a strange thing for git to do, but should not cause the permission problem, since I'm logged in as the file owning user)

**Comment by Smerdokryl** [comment]
Update: I noticed that when I `su username` and run code, the code terminal window still shows the default user, not `username`. 

Doing `su username` in there does not fix anything, though

**Comment by Smerdokryl** [comment]
Update: WSL log shows Starting server from the other user's (not `username`'s) folder

**Comment by bamurtaugh** [comment]
Hey @Smerdokryl, are you still experiencing this issue? Do any of the [permission denied steps here](https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace-in-wsl-1) apply to or help your scenario?

**Comment by bamurtaugh** [comment]
Please let me know if you are still experiencing this issue, and I'd be happy to reopen/discuss further. Thank you!
