### ISSUE TITLE
The remote extension host server should not listen on 0.0.0.0

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode-remote-release#291]
In "Remote - SSH" scenario, the remote extension host server is listening on `0.0.0.0` which is accessible from other users on the network.  This is vulnerable. 

```
ubuntu@80a320f69a16:~$ lsof -i
COMMAND PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node     61 ubuntu   13u  IPv6 606544      0t0  TCP *:46655 (LISTEN)
node     61 ubuntu   14u  IPv6 606907      0t0  TCP localhost:46655->localhost:35756 (ESTABLISHED)
node    179 ubuntu   12u  IPv6 606902      0t0  TCP localhost:46655->localhost:35754 (ESTABLISHED)
ubuntu@80a320f69a16:~$ ps ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /bin/sh -c /usr/sbin/sshd -D && tail -f /dev/null
    6 ?        S      0:00 /usr/sbin/sshd -D
   54 ?        S      0:00 sh /home/ubuntu/.vscode-remote/bin/57b550c559b945eb9d871dbf2b2e4cb9e31e2551/server.sh --port=0
   61 ?        Sl     0:02 /home/ubuntu/.vscode-remote/bin/57b550c559b945eb9d871dbf2b2e4cb9e31e2551/node /home/ubuntu/.vscode-remote/bin/57b550c559b945eb9d871dbf2b2e4cb9e31e2551/out/remoteExtensionHostAgent.js --port=0
  172 ?        Ss     0:00 sshd: ubuntu [priv]
  178 ?        S      0:00 sshd: ubuntu
  179 ?        Rl     0:01 /home/ubuntu/.vscode-remote/bin/57b550c559b945eb9d871dbf2b2e4cb9e31e2551/node /home/ubuntu/.vscode-remote/bin/57b550c559b945eb9d871dbf2b2e4cb9e31e2551/out/bootstrap-fork --type=extensionHost
  193 pts/0    Ss     0:00 /bin/bash
  199 pts/0    R+     0:00 ps ax
```

![スクリーンショット 2019-05-13 8 07 59](https://user-images.githubusercontent.com/10665499/57588934-326b2d00-7557-11e9-96c9-d145a344ff18.png)

The remote extension host server should use UNIX domain sockets. [OpenSSH can forward](https://man.openbsd.org/ssh#L_2) a local socket to a UNIX socket on the remote server. 

If "Remote - SSH" is not supposed to be used on a usual server logged in by multiple users, that should be documented.

**Comment by LeuisKen** [comment]
Or we can consider something like token to make it more secure as I mentioned in the referenced issue.

**Comment by blocke** [comment]
So...

Listening on all interface is terrible
Listening on localhost and not a user restricted user socket is bad

I had assumed at least there was a token check in play. Perhaps I was incorrect in making that assumption. If true than it would be shockingly horrific security.

I'm hoping someone can chime in with more specific information as to the security model here as I personally view it as simply not safe to run anywhere without it.

**Comment by zao** [comment]
Stating it plainly:
* Listening on all interfaces allows anyone on the network (which may be the whole internet) to connect to the service.
* Listening on localhost allows anyone on a shared login node (including people who have stolen shells) to connect to the service.
* Documenting (and possibly even implementing in the first place) token-based or equivalent security is essential to running this service on an internet-facing or multi-user machine.

The current documentation instills a false sense of security talking about transport security but mentions nothing about the listen socket it sets up.

The source as installed on the remote server is pretty much impossible to audit as it's minified so we can't tell what it does.

Until these concerns are addressed, we will unfortunately have to forbid usage of vscode-remote on our site.

**Comment by zao** [comment]
@tamuratak On the subject of UNIX domain sockets, it's notable that not all filesystems (AFS) support them in the home directory - so if they go that route, they will have to put them in a place like `$XDG_RUNTIME_DIR` as discussed previously in #22593 when they last tried using them.

**Comment by roblourens** [comment]
Closing as dupe of https://github.com/microsoft/vscode-remote-release/issues/1016
