### ISSUE TITLE
SSH Conda Environment Default Error

### ISSUE THREAD

**Issue by travpurc** [microsoft/vscode-remote-release#2910]
# Environment: 

- VSCode Version: 1.44.2
  Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
- Local OS Version: Windows_NT x64 10.0.18363
- Remote OS Version: Azure VM - Linux - CentOS - 3.10.0-693.11.6.el7.x86_64
- Remote Extension/Connection Type: SSH

# Issue: 
The default conda environment for a remote SSH Linux connection starts in an invalid environment. The environment values point to a different environment than is configured as default. This causes the environment to get into a faulty state where libraries are not correctly associated together when running Jupyter notebooks (and no change of kernels will change it).

# Steps to Reproduce (and work-around):

0. From VS Code SSH Into Azure VM and use the terminal to interact with the machine:

_-=-=-=-=-=-= Terminal Steps =-=-=-=-=-_
1. [admin@AzureVM jupyterNotebooks]$ conda env list
```
# conda environments:
#
base                     /anaconda
py35                     /anaconda/envs/py35
dev-37         *  /home/admin/.conda/envs/dev-37
```

2. [admin@AzureVM jupyterNotebooks]$ which pip
    `/anaconda/envs/py35/bin/pip`

**3. [admin@AzureVM jupyterNotebooks]$ conda deactivate**
   _This step is required to make the "fake" starting environment actually go away and allow me to use the environment I want_

4. [admin@AzureVM jupyterNotebooks]$ conda env list
```
# conda environments:
#
base                     * /anaconda
py35                     /anaconda/envs/py35
dev-37         /home/admin/.conda/envs/dev-37
```

5. [admin@AzureVM jupyterNotebooks]$ which pip
`/anaconda/envs/py35/bin/pip`

6. [admin@AzureVM jupyterNotebooks]$ conda activate dev-37

7. **(dev-37)** [admin@AzureVM jupyterNotebooks]$ conda env list
```
# conda environments:
#
base                     /anaconda
py35                     /anaconda/envs/py35
dev-37         *  /home/admin/.conda/envs/dev-37
```

8. **(dev-37)** [admin@AzureVM jupyterNotebooks]$ which pip
`~/.conda/envs/dev-37/bin/pip`

9. **(dev-37)** [admin@AzureVM jupyterNotebooks]$ jupyter notebook

Now the Jupyter notebook is started with the dev-37 environment. This does not occur without deactivating the incorrect (nameless - appears to be "py35") start-up environment. The environment will never contain the correct python modules if just activating - it appears to get into a "lost state" where if you skip the deactivate of the original default environment that it never associates new environments correctly even if you activate base then back to dev-37 (`which pip` will always be incorrect).

Does this issue occur when you try this locally (with git bash)? **No** - Git bash does not have this issue and works without having to deactivate the original environment that is accessed from the terminal

Does this issue occur when you try this locally and all extensions are disabled?: unknown

**Comment by roblourens** [comment]
Not clear what the vscode issue is here, is the environment wrong? Maybe this should be an issue on the Python extension?
