### ISSUE TITLE
Remote platform can't be write 

### ISSUE THREAD

**Issue by cqh963852** [microsoft/vscode-remote-release#2911]
- VSCode Version: 1.44.2
- Local OS Version: win10 18363.592
- Remote OS Version: debian buster
- Remote Extension/Connection Type: SSH

![image](https://user-images.githubusercontent.com/17702287/80823741-beb2ac00-8c0f-11ea-90c8-a8b0e1fa9e16.png)

It says `remote.SSH.remotePlatform is not a registered configuration`

So I need select the platform each time I try connect to remote server from ssh.
![image](https://user-images.githubusercontent.com/17702287/80824024-38e33080-8c10-11ea-9473-df9dba3ce9f9.png)

**Comment by carltonf** [comment]
As a workaround, I downgraded Remote SSH extension back to 0.48.0 and this issue doesn't show up.
VSCode version: 1.45.1

**Comment by Dhrumil** [comment]
I am also getting the same issue while multiple people are connecting to same VS Code server. DO we have any resolution for this issue?

**Comment by roblourens** [comment]
Is this still happening? I think I made a change that could have impacted this earlier.
