### ISSUE TITLE
Remote CLI doesn't have -a option

### ISSUE THREAD

**Issue by rlivings39** [microsoft/vscode-remote-release#2912]
We have a workflow where we need to open files and add workspace folders from a giant source tree. To make this easier, we tend to use the command line `code -a` to add a workspace folder and have developed a simple [fzf-based extension](https://github.com/rlivings39/vscode-fzf-quick-open) to do this.

Having the `-a` option for the remote ssh `code` CLI would be a huge help for that workflow.

```
$ code -a subdir                                                                                                                                        
Ignoring option a: not supported for code.
At least one file or folder must be provided.
$ which code                                                                                                                                            
/home/rlivings/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/bin/code
```

**Comment by aeschli** [comment]
`-a` got added in the meantime (in since the July build)
