### ISSUE TITLE
Upgrade to Windows 2004 -> Docker 2.2.3 -> Docker & docker compose WSL terminal 

### ISSUE THREAD

**Issue by PavelSosin-320** [microsoft/vscode-remote-release#2913]
After the optional/inforced upgrade of pre-requisits, I installed docker &  docker-compose in my favorite WSL 2.0 distro and now I'm able to use docker in its natural POSIX & bash environment and improved networking with proxied access to the docker daemon. 
Windows User_Profile folder can be addressed using POSIX notation /home/user/myuser and mounted to the Docker container's /home/container user folder as volume and propagates most of the User's profile to the running container. Env variables can be easily propagated via .env file.

**Comment by PavelSosin-320** [comment]
I also found that Docker Desktop installs DockerProxy for me to help me to solve "Working behind  corporate or local firewall" problem like SSH through my Norton:
PS C:\WINDOWS\system32> Get-Process -Id (Get-NetTCPConnection -LocalPort 2375).OwningProcess

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    239      17    25780      28600       5.77  18008   1 com.docker.proxy

**Comment by PavelSosin-320** [comment]
**DIY solution for real brave Cloud application developers with no single line of code:
Prerequisites:**

1. Just released Windows 2004 installed and WSL 2.0 enabled
2. Docker Desktop for Windows ver 2.2.3 installed
3. Ubuntu distro from Microsoft store installed, marked as default and converted to ver 2
4. Docker and Docker-compose CLIs for Ubuntu WSL  following [Install Docker CLI](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly)
-----------
Steps:
Invoke VSCode Powershell terminal using ctrl-shift `
invoke cmd
invoke WSL default distro with your windows user: wsl -u myuser
- now you are in the local powerful Ubuntu distro with your userprofile propagated to Ubuntu as ~
you have access to all Docker and docker-compose capabilities including docker container commit for fast changes and saving modified containers as a personalized image without a rebuild.
You can create and modify your compose file using the corresponding VSCode plugin and deploy it to the local or remote Docker Swarm instantly for testing purposes.
You can use any containerized build systems using official images like Grunt and doketteJdk8.
You can use Helm3.1 container to deploy  Kubernetes stack.
Don't forget to mount your local profile ~ to the container user profile ~ - this is the common method of invocation of official images.
If your workspace is portable as Docker volume you can teleport yourself changing DOCKER_HOST value and invoking your personalized container there, for example inside Dev Pipeline.

**Comment by PavelSosin-320** [comment]
Now I simply define WSL Ubuntu as the default terminal and found that my environment is propagated completely correct. I tried to pull GitHub repository without any installation, etc. using Alpine/git container as microservice and credentials from my Windows profile into my Windows Workspace. As expected it was OK because official 
![GitMicroserviceWith WSL](https://user-images.githubusercontent.com/54495912/80907672-84d1ca80-8d21-11ea-9dca-b15264fee288.png)
Alpine/Git microservice is designed and implemented as a valid microservice and if it is used correctly it simply works without Microsoft Logo.
I also checked the memory footprint of my stack including WSL , DockerDesktop, which is WSL2.0 image too and found that it is incredibly small - a portion of Chrome footprint although includes both Orchestration engines.
I also found an additional bonus - DockerProxy on the board developed by J Randell for the saint purpose: forget all "how to ... behind corporate proxy" forever. It was installed with the DockerDesktop 2.2.3.
![WSLMemoryFootprint](https://user-images.githubusercontent.com/54495912/80907898-5bb23980-8d23-11ea-815c-cc891c7ce737.png)
![DockerDesktopMemory](https://user-images.githubusercontent.com/54495912/80907900-5ce36680-8d23-11ea-917e-8a3771c1f449.png)

**Comment by PavelSosin-320** [comment]
Upgrade to Windows 10 2004 & WSL 2 & Docker desktop 2.3 is the big headache indeed because every component is not 100% back compatible but since the 2004 release is the new Windows's base code line & WSL's base code line & Docker's base code line I don't see any alternative.

**Comment by chrmarti** [comment]
@PavelSosin-320 Are there any remaining issues here?
