### ISSUE TITLE
Remote debugger cannot hit the breakpoint.

### ISSUE THREAD

**Issue by ssrlive** [microsoft/vscode-remote-release#2915]
Hi here, 
Remote debugger cannot hit the breakpoint. 
The execution flow passed directly.
What did I miss?

![image](https://user-images.githubusercontent.com/30760636/80853244-bc793d80-8c61-11ea-8702-68018a35caa5.png)

**Comment by rzhao271** [comment]
Closing this issue for now as part of housekeeping.

@ssrlive feel free to reply if this issue still occurs for you on the latest version of VS Code (preferably Insiders edition). Also, if applicable, does this issue occur for you locally?
