### ISSUE TITLE
debugging whit root permission

### ISSUE THREAD

**Issue by liubailin2017** [microsoft/vscode-remote-release#2916]
Issue Type: <b>Feature Request</b>

I am in the remote process, I use gdb debugging, need root permission, how to solve.

Extension version: 0.51.0
VS Code version: Code - Insiders 1.45.0-insider (4bd206856db30c27d38aa0f1fbe74bac6156edc7, 2020-04-29T05:33:59.143Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-91-generic

**Comment by liubailin2017** [comment]
i want to use sudo gdb

**Comment by chrmarti** [comment]
You need to setup sudo on your remote machine yourself. That is not something the extension can do.
