### ISSUE TITLE
Resolver error: Failed to write install script to path ...\Python37\vscode-linux-multi-line-command----ace-233888483.sh

### ISSUE THREAD

**Issue by YikeWang1103** [microsoft/vscode-remote-release#2920]
- VSCode Version: VSCodeUserSetup-x64-1.44.2
- Local OS Version: win7
- Remote OS Version: Ubuntu18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Start to connect remote server
2. Error prompt as follows
![image](https://user-images.githubusercontent.com/7753150/80898354-fd8e5200-8d34-11ea-84a1-13da35fe683d.png)
3. It seems that the script of remote development is trying to install something under the path of .../Python37/vscode-linux-multi-line-command----ace-233888483.sh at each time when I try to connect remote server, which is not available. Does anyone know how to deal with it? Thanks in advance!

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by suryaprakaz** [comment]
Hi @YikeWang1103 Were you able to solve this issue?

**Comment by bamurtaugh** [comment]
Since it's been some time since the issue was opened and there hasn't been an update, going to close it out for now. But @YikeWang1103 @suryaprakaz if you're still experiencing it, please just let me know, and I'd be happy to reopen. Thank you!

**Comment by suryaprakaz** [comment]
For those who may still be experiencing it: I had to create a new user in windows for it to work again.
