### ISSUE TITLE
High cpu usage of node process in Remote-WSL extension

### ISSUE THREAD

**Issue by dingqunfei** [microsoft/vscode-remote-release#2921]
- VSCode Version: 1.44.2
- Local OS Version: Windows_NT x64 10.0.18363
- Remote OS Version: WSL Ubuntu 20.04
- Remote Extension/Connection Type: Remote-WSL v0.44.2

Steps to Reproduce:

1. I code or debug in WSL, following this https://code.visualstudio.com/docs/cpp/config-wsl.
2. Step by Step following the tutorial, after installed the remote-wsl , the node process has a high cpu occupation forever.
3. I disabled the extension one by one. When Remote-WSL extension is disabled, the CPU usage is low. Does this extension cause high occupation? I just code or debug in VSCode by WSL, and the Remote-WSL helps me to use gcc/gdb in WSL. By the way, this is no database icon or flame in the status bar.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No
![微信图片编辑_20200502005044](https://user-images.githubusercontent.com/11921211/80898544-4b0bbe80-8d37-11ea-905f-38a84ab98e27.jpg)
![微信图片编辑_20200502005121](https://user-images.githubusercontent.com/11921211/80898546-4e06af00-8d37-11ea-8ceb-f895b4333c78.jpg)

**Comment by csibesz07** [comment]
- VSCode Version: 1.44.2 (user setup)
- Local OS Version: Windows_NT x64 10.0.18363.778, Windows 10 Pro N
- Remote OS Version: WSL Ubuntu 20.04
- Remote Extension/Connection Type: Remote-WSL v0.44.2

I see the same issue. I have the same versions as reporter. 
Just reinstalled windows 10, everything the latest.
I have 2 WSL VSCode window open, both using one core fully (99, 98). Some kind of livelock.
Tried to revert back to VSCode 1.35, same there. Should try to older ubuntu version and see if it makes difference.
![wsl_cpu_usage](https://user-images.githubusercontent.com/17401384/80912926-64f9d100-8d38-11ea-84a8-7778281006d9.jpg)

**Comment by dingqunfei** [comment]
YES, Phenomenon appears after upgraded to WSL-Ubuntu20.04

**Comment by Manntis** [comment]
Agreed.  @csibesz07 downgrading VSCode WSL to Ubuntu 18.04 resolved the issue for me as well.  I tried all of the file watching related fixes with no luck.  (https://github.com/Microsoft/vscode-remote-release/issues/90)

**Comment by emeygret** [comment]
probably due to this  : https://discourse.ubuntu.com/t/ubuntu-20-04-and-wsl-1/15291
and this : https://github.com/microsoft/vscode-remote-release/issues/864

**Comment by emeygret** [comment]
solve with patched libc6 : 
wget "https://launchpadlibrarian.net/474302949/libc6_2.31-0ubuntu8+lp1871129~1_amd64.deb"
sudo dpkg -i libc6_2.31-0ubuntu8+lp1871129~1_amd64.deb

no issue with wsl2, and issue seems to be fixed in wsl1 in next version

**Comment by frct1** [comment]
> solve with patched libc6 :
> wget "https://launchpadlibrarian.net/474302949/libc6_2.31-0ubuntu8+lp1871129~1_amd64.deb"
> sudo dpkg -i libc6_2.31-0ubuntu8+lp1871129~1_amd64.deb
> 
> no issue with wsl2, and issue seems to be fixed in wsl1 in next version
> 
> more information in [microsoft/WSL#4898](https://github.com/microsoft/WSL/issues/4898)

Hey, it seems to be working. Thank you very much!
