### ISSUE TITLE
Failed to download & extract vscode-server (UseBasicParsing)

### ISSUE THREAD

**Issue by carlosloch** [microsoft/vscode-remote-release#2923]
- VSCode Version: 1.44.2
- Local OS Version: Windows 10
- Remote OS Version: Windows Server 2012 R2
- Remote Extension/Connection Type: SSH/Docker/WSL

I'm trying to connect with a Windows Server 2012 R2 system, but isn't possible to install vscode-server:

[00:04:11.628] "Copy server to host" terminal command done
[00:04:11.686] > Downloading VS Code Server
> ee89fc372607%%1%%
**> Failed to download & extract vscode-server. - No se encuentra ningun parametro que coincida con el nombre del parametro 'UseBasicParsing'.**
> Trigger client server download
> ee89fc372607:trigger_server_download
> platform==windows==
> vscodeArch==x64==
> destFolder==C:\Users\Administrador\.vscode-server\bin\ff915844119ce9485abfe8aa9076ec76b5300ddd==
> ee89fc372607:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for C:\Users\Administrador\.vscode-server\bin\ff915844119ce9485abfe8aa9076ec76b5300ddd\vscode-scp-done.flag and vscode-server.zip to exist
> 
[00:04:12.892] > Found flag and server on host
[00:04:12.993] > 
> 
[00:04:13.003] > Expanding server into C:\Users\Administrador\AppData\Local\Temp\g4h2edfx.1oe
[00:04:13.020] > 
> ee89fc372607%%2%%
[00:04:13.045] > 
> 
**[00:04:13.729] > vscode-server failed to start. - El termino 'Expand-Archive' no se reconoce como nombre de un cmdlet, funcion, archivo de script o programa ejecutable. Compruebe si e
> scribio correctamente el nombre o, si incluyo una ruta de acceso, compruebe que dicha ruta
[00:04:13.848] >  es correcta e intentelo de nuevo.**
[00:04:13.853] > 
> ee89fc372607: start
> sshAuthSock====
> agentPort====
> osReleaseId==windows==
> osVersion==6.3.9600==
> arch==x64==
> platform==windows==
> ee89fc372607: end
[00:04:13.854] Received install output: 
sshAuthSock====
agentPort====
osReleaseId==windows==
osVersion==6.3.9600==
arch==x64==
platform==windows==

[00:04:13.856] Failed to parse remote port from server output
[00:04:13.857] Resolver error: 
[00:04:13.864] ------

[00:04:14.331] > 
> Install script is 6476, watching sshd parent 6616

**Comment by brianhatchet** [comment]
I fixed this issue by upgrading powershell on Windows 2012. Expand-Archive does not exist in PS4, so upgrading to 5 will fix it.

**Comment by bamurtaugh** [comment]
@carlosloch Are you still experiencing this issue? Does @brianhatchet's solution help?

**Comment by bamurtaugh** [comment]
Please feel free to let us know if you're still experiencing any issues- thank you!
