### ISSUE TITLE
Add refresh action to not forward port's context menu

### ISSUE THREAD

**Issue by wizhippo** [microsoft/vscode-remote-release#2927]
Issue Type: <b>Bug</b>

At the moment you cannot remove past forwarded ports under 'Not Forwarded'.

Should be be able to right click on them and select delete/remove.

Extension version: 0.51.0
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux arm 4.19.97-v7+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (16.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: redpoop|
|OS|Linux arm 4.19.97-v7+|
|CPUs|ARMv7 Processor rev 4 (v7l) (4 x 1200)|
|Memory (System)|0.85GB (0.20GB free)|
|VM|0%|
</details>

**Comment by bamurtaugh** [comment]
It does seem like we get into this interesting state where you cannot remove a "Not Forwarded" port, even if your app is no longer running.

Here my app isn't running anymore, but my only option is to still forward the port:

![image](https://user-images.githubusercontent.com/25310137/98595086-5f9eb580-228a-11eb-952c-eb499a1185e5.png)

The way I could make the above port disappear was to forward it again when the app still wasn't running:

![image](https://user-images.githubusercontent.com/25310137/98595314-b0aea980-228a-11eb-8bca-c9a7108c00ab.png)

And then stop forwarding:

![image](https://user-images.githubusercontent.com/25310137/98595411-cde37800-228a-11eb-90a1-57984eb3160f.png)

![image](https://user-images.githubusercontent.com/25310137/98595429-d5a31c80-228a-11eb-8ea5-6790b4299c72.png)

cc @alexr00

**Comment by alexr00** [comment]
We can only fetch "Not Forwarded" ports when you refresh the forwarded ports view. (Technical limitation: finding "not forwarded" ports is expensive). I could add "Refresh" in the context menu for not forwarded ports if that would help.

**Comment by bamurtaugh** [comment]
I think adding "Refresh" in the context menu is a good idea. It makes sense to me now that I would've needed to refresh, and if "Refresh" had been an option in the context menu, I think that could've helped resolve my scenario, and it speaks to @wizhippo's expected flow of right-clicking to delete/remove.

**Comment by alexr00** [comment]
Since ports to forward are detected from the proc filesystem every 2 seconds, set `"remote.autoForwardPorts": false` and verify that there is no "Refresh" action in the forwarded ports view.
