### ISSUE TITLE
When failing to start offer 'Open Folder in WSL'

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2928]
If on Windows and Remote-WSL is installed.

**Comment by connor4312** [comment]
@chrmarti can you add verification steps?

**Comment by chrmarti** [comment]
On Windows:
- Update to the latest Windows release 2004.
- Update to the latest Docker Desktop and enabled its WSL 2 backend.
- Install a WSL Distro (e.g., search for WSL Ubuntu in the store).
- Convert WSL Distro to WSL 2, e.g.: `wsl --set-version Ubuntu 2`
- Install Remote-WSL extension in VS Code.
- Open a WSL VS Code window. (`Remote-WSL: New Window`)
- Open an empty folder with the WSL window.
- `Remote-Containers: Add Development Container Configuration Files...` and pick any.
- Change the generated Dockerfile at `.devcontainer/Dockerfile` to have an error.
- `Remote-Containers: Reopen in Container`.
- Verify that the error dialog that eventually opens offers to `Reopen in WSL` and that action works as expected.
- `Remote-Containers: Reopen in Container` again.
- Choose `More Actions...` this time and then `Reopen Locally` to open the folder without Remote-WSL.
- Uninstall the Remote-WSL extension.
- `Remote-Containers: Reopen in Container` again.
- Verify that now the error dialog offers `Reopen Locally` and `Reopen in WSL` is no longer available (also not from `More Actions...`).

**Comment by JacksonKearl** [comment]
Currently blocked by https://github.com/microsoft/vscode-remote-release/issues/3140 on verifying this.

**Comment by JacksonKearl** [comment]
Re #3140, running `wsl --set-default Ubuntu` is required for `Remote-WSL: New Window` to work.
