### ISSUE TITLE
create a new terminal not working in vscode remote containers

### ISSUE THREAD

**Issue by cedric05** [microsoft/vscode-remote-release#293]
Issue Type: <b>Bug</b>

fails with `execvp failed.: no such file or directory`

Extension version: 0.53.0
VS Code version: Code - Insiders 1.34.20-insider (57b550c559b945eb9d871dbf2b2e4cb9e31e2551, 2019-05-10T17:32:52.030Z)
OS version: Linux x64 5.0.0-13-generic
Remote OS version: Linux x64 5.0.0-13-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 3241)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 1, 1|
|Memory (System)|31.27GB (23.01GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Attached Container vsc-tryied-a8d01b1b17ce7e473c7eb8f3a98a596e (/mystifying_hellman)|
|OS|Linux x64 5.0.0-13-generic|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 3241)|
|Memory (System)|31.27GB (23.01GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment]
pls see https://github.com/microsoft/vscode-remote-release/issues/220#issuecomment-490374437
Does this fix your problem?

**Comment by cedric05** [comment]
it does solve my problem thanks.
