### ISSUE TITLE
Variables not replaced in attach config

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2935]

**Comment by connor4312** [comment]
@chrmarti can you add verification steps?

**Comment by chrmarti** [comment]
To verify:
- `docker run -d ubuntu sleep infinity`
- Attach to the new container from the Remote Explorer.
- Once attached: Run command `Remote-Containers: Open Container Configuration File`.
- Change the file to:
```json
{
	"remoteEnv": {
		"TEST1": "${containerEnv:PATH}",
		"TEST2": "${localEnv:PATH}"
	}
}
```
- Reload the window.
- Open integrated terminal.
- Check `set | egrep '^TEST'` shows the two environment variables with the embedded variables correctly replaced.
