### ISSUE TITLE
Add Remote-Containers to docker and kubectl recommendations

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2936]
Add Remote-Containers to `docker` and `kubectl`  and `podman` executable recommendations.

**Comment by chrmarti** [comment]
I see the change, but I don't see the recommendation. @sandy081 What are the conditions for an exe based recommendation to be shown?

**Comment by sandy081** [comment]
Not all exe based recommendations are shown instead they are shown randomly mixed with other recommendations. We (for some reason I do not know why as I did not implement that) randomly and show only subset of exe based + other recommendations.
