### ISSUE TITLE
Customize SSH targets list

### ISSUE THREAD

**Issue by fakhamatia** [microsoft/vscode-remote-release#2938]
Option to change Icon of servers. like OS, monitor, camera, server, embedded, Pi icons

Option to create groups. I want to use 50 ssh target

Option to set a directory for ssh, not recent list. on `Test` Server I only use `/var/www/html` directory, It does not necessarily show directory every time.

![Screenshot from 2020-05-05 17-56-16](https://user-images.githubusercontent.com/20030910/81072555-9078e900-8efb-11ea-8853-27a8a9f9a4fb.png)

**Comment by william-bohannan** [comment]
Grouping SSH targets would be nice feature +1, Or perhaps give the ability to give them a color?
