### ISSUE TITLE
Duplicated files opened, breakpoints not visible

### ISSUE THREAD

**Issue by WurmD** [microsoft/vscode-remote-release#2939]
Issue Type: <b>Bug</b>

1. Connect through SSH to ubuntu machine
2. Set breakpoint in first line of main()
3. "Start Debugging"

Duplicated file is opened where:

- Breakpoints are not visible (but execution stops in set breakpoint)
- File path with prepended "/mnt"

Screenshot: https://www.dropbox.com/s/uulamo66bs4s8sg/breakpointnotvisible.png?raw=1

Extension version: 0.51.0
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.84-microsoft-standard
Remote OS version: Linux x64 4.15.0-96-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (17.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|Memory (System)|24.85GB (24.24GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 144.76.103.190|
|OS|Linux x64 4.15.0-96-generic|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 900)|
|Memory (System)|62.77GB (2.12GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
If this is still an issue, please file an issue on the C++ debug extension
