### ISSUE TITLE
Issue with validating server signature with Windows 10 ssh client

### ISSUE THREAD

**Issue by jozefizso** [microsoft/vscode-remote-release#294]
- VSCode Version: 1.34.20-insider (user setup)
  Commit: 57b550c559b945eb9d871dbf2b2e4cb9e31e2551
  Date: 2019-05-10T17:36:45.765Z
  Electron: 3.1.8
  Chrome: 66.0.3359.181
  Node.js: 10.2.0
  V8: 6.6.346.32
  OS: Windows_NT x64 10.0.17763
- Local OS Version: Windows 10 x64 1809 Enterprise
- Remote OS Version: Alpine Linux x64 3.9
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Setup Alpine Linux 3.9
2. [Configure Windows 10 SSH service](https://code.visualstudio.com/docs/remote/troubleshooting#_ssh-tips)
3. Try to connect to the Alpine host
4. VS Code will display progress "Confirming that alpine is reachable" and it never finishes.

**Remote - SSH** logs:

```
Confirming that alpine is a valid reachable host
Running type "C:\Users\Jozef\AppData\Local\Temp\vscode-linux-multi-line-command-alpine.sh" | ssh  alpine to confirm the host platform
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> The authenticity of host 'alpine.vm.local (10.16.32.38)' can't be established.
> ECDSA key fingerprint is SHA256:cBU96cpEexHcbIW2EIj3r8/FFnCIdJoghfksI29alkY.
> Are you sure you want to continue connecting (yes/no)?
"uname" wrote data to terminal: "yes"
> Are you sure you want to continue connecting (yes/no)? ye
> Are you sure you want to continue connecting (yes/no)? yes
> Warning: Permanently added 'alpine.vm.local,10.16.32.38' (ECDSA) to the list of
> known hosts.
> 
> warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
> 
> jozef@alpine.vm.local's password:
```

The **known_hosts** file has the server signature stored as **ecdsa-sha2-nistp256**.

**Comment by kkdawkins** [comment]
+1 Hit this issue.

**Comment by roblourens** [comment]
Is this still an issue? Can you ssh from the command line?

**Comment by Dalot** [comment]
I've had this issue before and it's resolved at the moment. I'm not sure if the fix was caused by the server reboot or the last update of vscode remote.
