### ISSUE TITLE
Using a DOCKER_HOST running with moby

### ISSUE THREAD

**Issue by schuster-rainer** [microsoft/vscode-remote-release#2942]
I'm working on a project where we are using the iotedge-hub with the moby runtime. So we don't have docker in this setup but just installing the moby runtime. Is it possible to run vscode remote with the moby runtime? 

I'm just getting an error that the version number is not correct expecting at least version 17.06 of docker

**Comment by chrmarti** [comment]
We currently rely on the Docker CLI being present. Is this still an issue?

**Comment by schuster-rainer** [comment]
I don't think docker cli is missing. I guess it's the version check breaking it. We switched to a dev workflow where we use iotedgehubdev instead of iotedge. Still I think it could be an interesting option  for remote work that need to be done or just for using a different container runtime (that still has the required features)

**Comment by chrmarti** [comment]
Not sure I understand: Do you have a Docker (or Docker-compatible) CLI for managing the runtime?

**Comment by schuster-rainer** [comment]
Yes. iotedge is using moby-engine as a runtime (https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?tabs=linux). Same cli ... I mean docker-ce is also built on top of moby-engine. So I'm not aware of all the features on top of that. The proble is docker docker --version is of course reporting some other version. 

First I tried to hack the version check in the VSCode extension in my plugin dir but didn't work immediately, so I stopped trying. Maybe it's as easy as having a setting (allow non compliant docker engine, or allow different engine). 

I've just been wondering what features you precisely need that you query the cli for a version of 17.06 and above. I'm pretty confident the moby-runtime will do, as it powers all the iotedge modules if you are using the Azure SDK 

Here is a Dockerfile with da DIND installation using ubuntu 18:04

```
FROM ubuntu:18.04

RUN apt-get update \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get -y install --no-install-recommends ca-certificates apt-utils apt-transport-https curl gpg \
  && curl https://packages.microsoft.com/config/ubuntu/18.04/multiarch/prod.list > ./microsoft-prod.list \
  && cp ./microsoft-prod.list /etc/apt/sources.list.d/ \
  && curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg \
  && cp ./microsoft.gpg /etc/apt/trusted.gpg.d/ \
  && apt-get update \
  && apt-get -y install moby-engine

CMD [ "bash" ]
```

```
docker build . -t device-runtime
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock device-runtime bash
```

And it seemed like current versions on ubuntu report differently now:

```
Docker version 19.03.13+azure, build cd8016b6bcc51a51f577bcffb37e6a870f7813f9
```

Which makes it kind of obsolete here. 

When using debian:stretch it still reports the moby version, not the docker version

```
Docker version 3.0.13+azure, build dd360c7c0de8d9132a3965db6a59d3ae74f43ba7
```

Last time I checked and reported this on ubuntu it also reported as 3.*

**Comment by chrmarti** [comment]
Closing the issue under the assumption that this has been fixed upstream.
