### ISSUE TITLE
vscode-ripgrep overloadrs remote system

### ISSUE THREAD

**Issue by vhood** [microsoft/vscode-remote-release#2946]
- VSCode Version: 1.44.2 (system setup)
- Local OS Version: Windows 7 Pro
- Remote OS Version: CentOS 8
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to root directory - /
2. My remote server is responding too slowly
3. I start htop utility
4. I found all my CPU's under 100% and the fattiest processes are default vscode-ripgrep
![Screenshot_1](https://user-images.githubusercontent.com/55533574/81175167-b958b700-8fab-11ea-8461-cf9ca693af77.png)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/1257
