### ISSUE TITLE
Settings work incorrectly when one more folder is added to existing workspace

### ISSUE THREAD

**Issue by Dinno** [microsoft/vscode-remote-release#295]
Issue Type: <b>Bug</b>

I have a workspace which was created by opening remote folder. Then I added one more folder to the workspace by pressing right button inside workpace panel and selecting "Add Folder to Workspace...". After that my linter settings stopped working. My linter was set to pep8 but after that it became pylint again. Attempts to change current linter had no effect. After reopening workspace with only one folder all returned to normal.

Extension version: 0.37.0
VS Code version: Code - Insiders 1.34.20-insider (57b550c559b945eb9d871dbf2b2e4cb9e31e2551, 2019-05-10T17:36:45.765Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.14.15-5

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|31%|

|Item|Value|
|---|---|
|Remote|SSH: dev-rep01hd|
|OS|Linux x64 4.14.15-5|
|CPUs|Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz (32 x 2699)|
|Memory (System)|251.88GB (56.93GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment]
See also #273

**Comment by sandy081** [comment]
@Dinno What is the setting that is not working and it is from which extension? Also May I know if this works when you open multiple such projects (those exist in the local machine) as a workspace ?
