### ISSUE TITLE
trying to use private git mods causes device or resource busy on setup

### ISSUE THREAD

**Issue by aoighost** [microsoft/vscode-remote-release#2952]
I'm trying to set up go mod and a private github repo for the module and when I try to run the following bash file and get error: could not write config file /home/vscode/.gitconfig: Device or resource busy

 Bash file

#!/bin/bash
access_token=token
username=username
go env -w GOPRIVATE=github.com/$username

git config --global url."https://$username:$access_token@github.com".insteadOf "https://github.com"

**Comment by Chuxel** [comment]
@chrmarti Is this due to the automatic credential forwarding we have in place?

Moving to issues repo rather than sample.

**Comment by chrmarti** [comment]
Are you running the script manually or as `postCreateCommand` (does it work when run manually)? Shouldn't be related to the credential forwarding, maybe something during startup when we copy the .gitconfig.
