### ISSUE TITLE
Jupyter notebook theme and look not matching on remote containers to that on local

### ISSUE THREAD

**Issue by rohit-rr** [microsoft/vscode-remote-release#2953]
Issue Type: <b>Bug</b>

1. Open python sample remote container
2. Create a jupyter notebook file
3. Open jupyter notebook
4. Notice that jupyter notebook look and theme is different from that when opened on local machine. The comments and outputs are merged with no distinguishing space.

Extension version: 0.20.0
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
![VSCode_jupyter_normal](https://user-images.githubusercontent.com/25548892/81321918-d0350180-90b0-11ea-9db3-33f87bd01eca.png)
![VSCode_jupyter_in_container](https://user-images.githubusercontent.com/25548892/81321924-d1fec500-90b0-11ea-8384-0eea18d3bb80.png)

|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Could you attach screenshots of local and remote?

**Comment by rohit-rr** [comment]
Jupyter notebook view on local - ![81321918-d0350180-90b0-11ea-9db3-33f87bd01eca](https://user-images.githubusercontent.com/25548892/81545720-e7b50880-9396-11ea-8a2c-6d2646074666.png)

Jupyter notebook view on remote container - ![81321924-d1fec500-90b0-11ea-8384-0eea18d3bb80](https://user-images.githubusercontent.com/25548892/81545747-ef74ad00-9396-11ea-96d0-b1ce63914d64.png)

The display elements of the jupyter notebook were off, for example in the local there is a clear separation block between the code and the output. While in the remote container the jupyter notebook just had one merged black block for the code and the output (as seen in the code line `plt.plot(l)`. Both had the same theme applied to them.

I hope these are the screenshots you requested.

**Comment by chrmarti** [comment]
/causedByExtension

The background doesn't adapt to the color theme:
![image](https://user-images.githubusercontent.com/9205389/98372160-9df36500-203d-11eb-9439-821b05b8a103.png)

I think this is a problem with the Python extension (since the foreground does adapt). Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
