### ISSUE TITLE
Opening folder with Show Local exits from WSL

### ISSUE THREAD

**Issue by hlouzada** [microsoft/vscode-remote-release#2954]
Issue Type: <b>Bug</b>

It is expected that when opening a folder connected to WSL, VS Code opens in the current WSL connection, however, it is disconnecting and opening outside WSL.

Steps to reproduce:
1. Connect WSL
2. Open Folder
3. Show local
4. Open folder
5. VSCode disconnects from WSL

Extension version: 0.44.2
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.19619
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3299)|
|Memory (System)|12.36GB (11.52GB free)|
|VM|0%|
</details>

**Comment by Chuxel** [comment]
@hlouzada This is expected since this is how you can get back to editing files in the Windows filesystem.  Rather than clicking Show Local, you can navigate using the custom file tree that appears.  Make sense?

**Comment by hlouzada** [comment]
@Chuxel It makes sense, sorry it didn't cross my mind that I could navigate the custom file tree, and use it as a GUI for browsing the files and folders locations. Thank you.
