### ISSUE TITLE
Command `code` is not detected by WSL

### ISSUE THREAD

**Issue by 3axap4eHko** [microsoft/vscode-remote-release#2962]
- VSCode Version: 1.45
- Local OS Version: Windows 10 Pro 2004
- Remote OS Version: 4.19.84-microsoft-standard
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1. Press `Win` button
2. type `wsl`
3. Press `Enter`
4. type `code`
5. `Command 'code' not found, but can be installed with: sudo snap install code`

Does this issue occur when you try this locally?: No
In my powershell terminal command `code` works perfectly.
Does this issue occur when you try this locally and all extensions are disabled?: No

I saw already closed PR: https://github.com/microsoft/vscode-remote-release/issues/1042
But I also saw docs: https://code.visualstudio.com/remote-tutorials/wsl/run-in-wsl, and I think something is wrong 😃 

BTW command `code` for WSL works only from powershell or cmd by typing `wsl code`

### UPD
I've created file /etc/profile.d/00-wsl2.sh to start `systemd`
```bash
SYSTEMD_PID=$(ps -ef | grep '/lib/systemd/systemd --system-unit=basic.target$' | grep -v unshare | awk '{print $2}')

if [ -z "$SYSTEMD_PID" ]; then
   sudo /usr/sbin/daemonize /usr/bin/unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target
   SYSTEMD_PID=$(ps -ef | grep '/lib/systemd/systemd --system-unit=basic.target$' | grep -v unshare | awk '{print $2}')
fi

if [ -n "$SYSTEMD_PID" ] && [ "$SYSTEMD_PID" != "1" ]; then
    exec sudo /usr/bin/nsenter -t $SYSTEMD_PID -a su - $LOGNAME
fi
```

**Comment by onomatopellan** [comment]
what's the output of `echo $PATH`?

`/mnt/c/Users/username/AppData/Local/Programs/Microsoft VS Code/bin` should be there in order to `code` to work.

**Comment by 3axap4eHko** [comment]
NVM I fixed it

**Comment by Yiyiyimu** [comment]
> NVM I fixed it

Hi I came into the same problem, how did you fix it?
