### ISSUE TITLE
VS Code Server update shows "Permission denied" message from WSL

### ISSUE THREAD

**Issue by AjitDingankar** [microsoft/vscode-remote-release#2966]
- VSCode Version: 1.45.0
- OS Version: Windows 10 

About:
```
Version: 1.45.0 (system setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763
```

Steps to Reproduce:

1. Open WSL.
1. Run `code newfile` 
1. Note message in console to the effect of: 
```
mv: cannot move <HOME>/.vscode-server/bin/<SHA>-<RELEASE> to <HOME>/.vscode-server/bin/<SHA>: Permission denied
```
* VS Code still opens and works.
* Permissions are OK (777 with my user and group)

Does this issue occur when all extensions are disabled?: Yes/No
Can't check since there isn't an update immediately after the one that showed the error above, 
and also because the "Remote WSL" extension is required to open a file from WSL! ;-)

**Comment by klmos** [comment]
I got the same issue. Doing the mv manually in wsl terminal then retry the remote extension connection solved the issue for me.

**Comment by bamurtaugh** [comment]
Hey @AjitDingankar, are you still experiencing this issue? Does the suggestion above or [here](https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace-in-wsl-1) help?

**Comment by bamurtaugh** [comment]
Please let me know if you are still experiencing this issue, and I'd be happy to reopen/discuss further. Thank you!

**Comment by MountainLogic** [comment]
I am seeing this also.  I seem to be unable to open /mnt/c for coping files from bash so perhaps this is the issue?

foo@computer:~/wip/TWE_Daemon$ code .                                                                                                                  Updating VS Code Server to version 940b5f4bb5fa47866a54529ed759d95d09ee80be                                                                               Removing previous installation...                                                                                                                         Installing VS Code Server for x64 (940b5f4bb5fa47866a54529ed759d95d09ee80be)                                                                              Downloading: 100%                                                                                                                                         Unpacking: 100%                                                                                                                                           mv: cannot move '/home/foo/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be-1608407854' to '/home/foo/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be': Permission denied                                                                                                                mv: cannot move '/home/foo/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be-1608407854' to '/home/foo/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be': Permission denied                                                                                                                mv: cannot move '/home/foo/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be-1608407854' to '/home/foo/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be': Permission denied                                                                                                                mv: cannot move '/home/foo/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be-1608407854' to '/home/foo/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be': Permission denied                                                                                                                mv: cannot move '/home/foo/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be-1608407854' to '/home/foo/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be': Permission denied                                                                                                                WARNING: Unable to move /home/foo/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be-1608407854. Trying copying instead.                       Unpacked 1722 files and folders to /home/foo/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be.
