### ISSUE TITLE
Schema validation fails for valid devcontainer.json

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#2967]
I'm seeing schema validation errors for valid `devcontainer.json` files when using `tv4` to do the validation. This is causing all dev container tests to appear as if they fail.  This happened with the recent update to the schema to accommodate not having an image/dockerfile/dockerComposeFile.

Specific error:
```text
Data is valid against more than one schema from "oneOf": indices 0 and 1, Code: 12, dataPath: , schemaPath: /oneOf
```

Example valid json that fails:
```json
{
	"name": "Alpine 3.10",
	"dockerFile": "Dockerfile",
	"settings": {
		"terminal.integrated.shell.linux": "/bin/ash"
	},
	"extensions": []
}
```

Any ideas?

**Comment by chrmarti** [comment]
It looks like tv4 does not handle `additionalProperties: false`: https://github.com/microsoft/vscode/blob/c650757bd48b936987f1be4350a8f359b1a76550/extensions/configuration-editing/schemas/devContainer.schema.json#L320

That branch of the `oneOf` should not match due to the `dockerFile` property the above config has.

**Comment by Chuxel** [comment]
Hmmm - `ajv` gives me the same result (which supports draft-07).  I may just have to disable the test for now given the vscode validator is inside the json language server.

**Comment by chrmarti** [comment]
`ajv` doesn't like the combination of `"object"` and `"$ref"` it seems:
```
$ ajv validate -s extensions/configuration-editing/schemas/devContainer.schema.json -d ../test/devcontainer.json
$ref: keywords ignored in schema at path "#/oneOf/1"
../test/devcontainer.json invalid
[
  {
    keyword: 'oneOf',
    dataPath: '',
    schemaPath: '#/oneOf',
    params: { passingSchemas: [Array] },
    message: 'should match exactly one schema in oneOf'
  }
]
```

Refers to:
```json
		{
			"type": "object",
			"$ref": "#/definitions/devContainerCommon",
			"additionalProperties": false
		}
```

https://www.jsonschemavalidator.net/ doesn't complain. Not sure who is at fault. @aeschli Do you know?

**Comment by aeschli** [comment]
I think the spec says that the object that has the $ref must not have any other properties.
In VSCode we don't complain about that and merge the referenced object on top of the $ref object.

**Comment by chrmarti** [comment]
There might be no way of having `"#/definitions/devContainerCommon"` once with and once without `"additionalProperties": false` then.
