### ISSUE TITLE
Please help! Excessive number (80-100) of processes generated when VSCode is using remote development

### ISSUE THREAD

**Issue by anttin2020** [microsoft/vscode-remote-release#2969]
Hi!

I am not 100% sure this is bug but I have tried everything I know and tried to find solution in the internet (i'm NOT Linux pro, far from it).
I use VSCode to edit code (Python backend, Vue/Vuetify frontend) both at work and at home, same results in both but at work the limits are much higher so the actual problem occurs at home.
At home, I use remote webhotel (cPanel system) where I have limit of 1GB RAM and 100 processes which should be well enough. The /proc/version tells:
"Linux version 3.10.0-962.3.2.lve1.5.25.10.el7.x86_64 (mockbuild@buildfarm03.cloudlinux.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Wed May 29 04:37:40 EDT 2019"
The libc etc. versions are fine so there should be no problems.
I use some other extensions too but same results with only Remote-development so the other extensions are not affecting this.

BEFORE starting VSCode Remote session the number of processes is around 2-10/100 and memory usage is around 50-200MB/1GB or even less, depending on if I have other SSH connection active and/or how long time ago I closed VSCode (it takes sometimes even 15-30 min for all processes to die, sometimes they stay running even overnight :o)
BUT when I start VSCode Remote session, the process count jumps to 80-100/100 and almost any work is impossible, except direct editing. Any feature (like error checking) is often unable to start a process.
This is not always the same but within minutes usually goes to 80+ processes and soon to the limit, even if I do nothing on VSCode. Memory usage is huge too.
Please see the attached screenshots of cPanel Statistics. Note that I did nothing on VSCode between those screenshots. There was one file open in editor but I did not touch it.

I have tried Insiders, not the very latest version but Insiders was way worse, it used even more memory and went to 100 almost immediately so I switched to normal VSCode and as there has been no info about anything related to this had been changed, I don't think the Insider helps.

- VSCode Version: 1.45.1
- Local OS Version: Win 10
- Remote OS Version: Linux version 3.10.0-962.3.2.lve1.5.25.10.el7.x86_64 (more details above)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Start VSCode Remote session
2. Open a file
3. See process count skyrocket

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Can anyone help with this? Any tips/ideas/thoughts are very welcome, I am wasting most of my time trying to fix this problem instead of creating nice app. VSCode is great but this almost kills all the fun :)

Thank you very much!

Antti

Before
![vscode-before](https://user-images.githubusercontent.com/65116899/81500482-28e7e280-92db-11ea-95b9-d161fba83fbd.png)

Immediately after starting Remote session
![vscode-after1](https://user-images.githubusercontent.com/65116899/81500479-271e1f00-92db-11ea-8003-ceb0028344a7.png)

Few minutes later
![vscode-after2](https://user-images.githubusercontent.com/65116899/81500480-284f4c00-92db-11ea-934c-0eb3b1b12ae2.png)

After about 15 minutes
![vscode-after3](https://user-images.githubusercontent.com/65116899/81500481-284f4c00-92db-11ea-868e-fe75e4dab6b2.png)

**Comment by anttin2020** [comment]
Anyone?

**Comment by anttin2020** [comment]
Any ideas? This drives me crazy :|

**Comment by anttin2020** [comment]
Seriously, this is fatal problem and makes otherwise nice tool almost unusable :(
If I'm lucky I can debug or do syntax checking for few minutes but then again I need to kill all VSCode processes and reload the window and then again if I'm lucky I can work properly another few minutes.
VSCode CANNOT need 80+ processes for real.

Please help!

**Comment by anttin2020** [comment]
update 1.45.1 seems to be even worse, now simple editing (no debug etc.) for about 15 minutes is enough. Without warning the reconnect dialog appears. And immediately when I reload the window (reconnect won't work until I kill the VSCode processes so reload window is necessary), the process count is back to 80+ and soon 100 :(

**Comment by anttin2020** [comment]
Another symptom related to this, when I start VSCode remote, it usually takes 5-7 retries before the VSCode server actually starts. I hope this will help to figure out what is wrong.
Please give any info about this, is this known bug or something you have never heard before?

**Comment by anttin2020** [comment]
This quite boring talking to myself but here is VSCode log from one of those failed server starts.
It would be really nice if somebody would reply something, this problem is driving me crazy and towards abandoning VSCode.
So please help!

[12:28:51.625] Log Level: 2
[12:28:51.625] remote-ssh@0.51.0
[12:28:51.625] win32 x64
[12:28:51.627] SSH Resolver called for "ssh-remote+mysite.com", attempt 1
[12:28:51.627] SSH Resolver called for host: mysite.com
[12:28:51.627] Setting up SSH remote "mysite.com"
[12:28:51.629] Using commit id "5763d909d5f12fe19f215cbfdd29a91c0fa9208a" and quality "stable" for server
[12:28:51.630] Install and start server if needed
[12:28:51.633] Checking ssh with "ssh -V"
[12:28:51.669] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[12:28:51.671] Running script with connection command: ssh -T -o ClearAllForwardings=true mysite.com bash
[12:28:51.673] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[12:28:51.749] > 
> > 
> 
> ]0;C:\WINDOWS\System32\cmd.exe
[12:28:51.749] Got some output, clearing connection timeout
[12:28:51.756] > 
> 
> 
[12:28:52.266] > 26de30e68d62: running
> 
[12:28:52.291] > Acquiring lock on /home/mysite/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29
> a91c0fa9208a/vscode-remote-lock.mysite.5763d909d5f12fe19f215cbfdd29a91c0fa9208
> a
> 
[12:28:52.300] > \ln /home/mysite/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/v
> scode-remote-lock.mysite.5763d909d5f12fe19f215cbfdd29a91c0fa9208a.target /home
> /mysite/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/vscode-rem
> ote-lock.mysite.5763d909d5f12fe19f215cbfdd29a91c0fa9208a
> 
[12:28:52.309] > Found existing installation at /home/mysite/.vscode-server/bin/5763d909d5f12fe
> 19f215cbfdd29a91c0fa9208a...
> 
[12:28:52.337] > Found running server...
> 
> *
> 
[12:28:52.347] > * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
[12:28:52.355] > Server did not start successfully. Full server log at /home/mysite/.vscode-ser
> ver/.5763d909d5f12fe19f215cbfdd29a91c0fa9208a.log >>>
> <<< End of server log
> 26de30e68d62##32##
> 
[12:28:52.355] Received install output: 26de30e68d62##32##
[12:28:52.356] Resolver error: The VS Code Server failed to start
[12:28:52.358] ------

**Comment by anttin2020** [comment]
Here is the log referred above. Usually also the Typescript/javascript language tools fail to start so I tried the typescript next addon but for some reason it does not seem to work either, at least that log text refers to something like that.

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


IP Address: 77.240.19.28
IP Address: 77.240.19.156
IP Address: 77.240.19.198
IP Address: 77.240.19.232
IP Address: 77.240.19.104
IP Address: 10.43.3.28
Extension host agent listening on 36736

[12:28:50] Extension host agent started.
[12:28:52] Deleted from disk ms-vscode.vscode-typescript-next /home/mysite/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.0.20200527
[12:28:52] Deleted from disk mtxr.sqltools /home/mysite/.vscode-server/extensions/mtxr.sqltools-0.21.9

**Comment by anttin2020** [comment]
Could someone please say something, I still haven't found any solution and this makes VSCode near unusable. If this is wrong place to ask for help then please tell me where should I go. If I have not given enough info about the problem then please tell me what more info you need.
I am willing to give more info if needed but just please say SOMETHING.
I just joined Github because of this so if there are some 'protocols' here to get answers then I have no idea about those so please explain.
As I have said above, I cannot be the only person in the world who is using VSCode in webhotel or other environment with limited resources.

I have now waited for a MONTH without a single reply so what is wrong?

**Comment by Chuxel** [comment]
@roblourens 1 GB we know is really not enough RAM to run Remote Development for anything other than basic scenarios due to source maps, indexes, etc.  So, the RAM use is not surprising. My off hand reaction is the number of processes are not surprising either, but do you agree?

@anttin2020 Unlike something like the SSHFS extension, quite a bit runs on the remote device which is why you are seeing RAM consumption like that. Essentially part of VS Code itself is running remotely.

**Comment by anttin2020** [comment]
Thank you @Chuxel, finally somebody replied :)

> @roblourens 1 GB we know is really not enough RAM to run Remote Development for anything other than basic scenarios due to source maps, indexes, etc. So, the RAM use is not surprising. My off hand reaction is the number of processes are not surprising either, but do you agree?
> 
> @anttin2020 Unlike something like the SSHFS extension, quite a bit runs on the remote device which is why you are seeing RAM consumption like that. Essentially part of VS Code itself is running remotely.

My code is pretty simple, one HTML with one JS frontend and one Python backend. Uses MySQL but only few tables. So nothing huge.
I understand part of VSCode is running remotely, it usually takes 5-7 trials for it to get it running (another mystery) but why VSCode needs 100 processes? Even large 3D software does not need that much :o
Are there any ways to reduce the process count?
I'll need to check the SSHFS extension, maybe it could make VSCode run locally but still automatically upload the changes to server? In this case it would be enough. Of course then I couldn't debug the Python code but that is not problem as I found nice terminal interactive debugger pudb. If you have any other tips for SSHFS or other alternative for Remote Development, please let me know. There are too many extension for VSCode to know which one is the best for this :)

Anyway, thank you very much for your reply!
Now I know VSCode just is huge resource hog and therefore sadly probably not suitable for this case.

**Comment by PavelSosin-320** [comment]
@anttin2020 If you use Docker dev containers the min memory is 4Gb at least. The process count is simple: docker daemon + each created container, i.e. subprocess regardless of it's status + all processes spawned inside containers which poses the danger to become zombi if container's main process doesn't propagate SigKill to the child processes. If you observe "process leak, please describe your scenario in more detail.

**Comment by anttin2020** [comment]
No I don't use docker, just plain SSH, no containers either. One remote workspace.

**Comment by Chuxel** [comment]
@PavelSosin-320 FYI - The SSH extension is known to work on Raspberry Pi 3 devices that have 1.5GB of RAM.

@anttin2020 The number of processes is not really an indicator of RAM consumption but rather concurrency. The model here is not a sync one, but designed to provide a high fidelity user experience that is the same as you would experience if everything was on your local machine. That means running things like extensions remotely along with indexing the code, running searches, etc on the remote device. Extensions like SSHFS allow you to edit files remotely, but you will not see the same quality of experience because of network overhead. Both options are valid and available depending on your scenario and what you need. These extensions tackle a problem that there historically was no solution for beyond using text-based editors.  

That said, I don't know if that many processes is unusual or not - we've seen issues before, but that is why I'm asking @roblourens.  One question: Do you have any extensions installed on the device?

**Comment by anttin2020** [comment]
> @anttin2020 The number of processes is not really an indicator of RAM consumption but rather concurrency. The model here is not a sync one, but designed to provide a high fidelity user experience that is the same as you would experience if everything was on your local machine. That means running things like extensions remotely along with indexing the code, running searches, etc on the remote device. Extensions like SSHFS allow you to edit files remotely, but you will not see the same quality of experience because of network overhead. Both options are valid and available depending on your scenario and what you need. These extensions tackle a problem that there historically was no solution for beyond using text-based editors.

The RAM consumption is not the main problem, the process count reaching 100 (limit in my webhotel) is.
I tried VSCode SSHFS extension and it works but many other extensions, including the most important ones like Local History don't work so I cannot use it.
I also tried SSHFS-WIN which mounts remote folder to drive in Windows level and it works but permissions are stupid as I can only edit files, not create new ones nor directories. That would be necessary for e.g. Local History to work. It seems that the options to SSHFS-WIN either do not work or then the docs have errors because I'm not the only one that have similar problems with it.

Do you happen to know some other VSCode or Windows tool that would actually works? :)

I also tried SFTPDrive but it is much slower than SSHFS and seems unreliable.

> 
> That said, I don't know if that many processes is unusual or not - we've seen issues before, but that is why I'm asking @roblourens. One question: Do you have any extensions installed on the device?

I have some but I have also tried with all except Remote disabled, same result, maybe a bit later but anyway the process count increases to limit and then everything fails.

Any ideas are still very welcome :)

**Comment by anttin2020** [comment]
@roblourens, exactly, that process count is crazy :)

Here is Process Explorer capture, not telling much (more like cheating, claiming 0 all remote processes) :D
![vscode_process-explorer](https://user-images.githubusercontent.com/65116899/84369962-495bd300-abe0-11ea-9bf4-9208b111851b.png)

I made aliases for real process data i.e. same result that the webhotel statistics panel shows (vsallproc=all=statistics display, vsproc=vscode only):
alias vslist='pgrep -f vscode'
alias vsproc='sum=0 ; nums=$(for pd in $(pgrep -f vscode); do find /proc/$pd -name "children" 2>/dev/null | wc -l; done) ; for pc in ${nums[@]}; do (( sum+=pc )); done; echo $sum ;'
alias vsallproc='find /proc -name "children" 2>/dev/null | wc -l'

Here are results of those (note NO files open in VSCode, that's why the process count is 'only' 67 and memory 300MB):
$ vslist
16511
23918
23926
24082
24129
24206
24212
$ vsproc
61
$ vsallproc
67
And here is the ps xa result:
$ ps xa
  PID TTY      STAT   TIME COMMAND
16507 pts/0    Ss+    0:00 -bash
16511 ?        Sl     0:00 /home/username/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node /home/username/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /home/username/.cache/typescript/3.8 --e
17426 ?        S      0:00 sleep 180
18688 pts/2    R+     0:00 ps xa
23918 ?        S      0:00 sh /home/username/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown --disable-telemetry --port=0
23926 ?        Sl     0:03 /home/username/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/node /home/username/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/out/vs/server/main.js --host=127.0.0.1 --enable-remote-auto-shutdown --disable-telemetry --port=0
24016 ?        Ss     0:00 bash
24082 ?        Rl     0:06 /home/username/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/node /home/username/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/home/username/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67c
24129 ?        Sl     0:02 /home/username/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/node /home/username/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/out/bootstrap-fork --type=watcherService
24206 ?        Sl     0:00 /home/username/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/node /home/username/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=24082
24212 ?        Sl     0:00 /home/username/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/node /home/username/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=24082
25394 pts/2    Ss     0:00 /bin/bash

I hope someone can figure out the problem from these :)

Thank you!

**Comment by roblourens** [comment]
I'm really confused by this output, where are those processes in `ps`? It shows a similar result on my remote, but some of the "children" that it's including have a PID that does not belong to a running process. I am not sure how to interpret the stuff under `/proc/$pid` but is it possible that it's counting processes that were spawned at one point but aren't running anymore?

**Comment by anttin2020** [comment]
I don't know anything else than the fact that those numbers (vsallproc) match exactly the statistics display in cPanel (webhotel control panel) and vsproc shows those that are related to vscode. When I close VSCode Remote, they go down to 2-5 (I have normal SSH terminal connection running in addition to VSCode Remote so I can see the process counts even when VSCode is not running, that  causes those few processes) so it is VSCode Remote that keeps those processes running. Also because of that they are not any 'hanging' processes or if they are, they are still seen by the linux system as running ones and so cause the process limit of 100 get reached very easily.

And because ps obviously could not show the child processes, I did extensive search in the internet and based on the results I created those aliases to see the real total process count, I am not linux guru, not even close :)

So I have not a slightest idea what those processes are but they are 100% surely caused by VSCode Remote, no other connection creates that many. If I simply connect with SSH/SFTP, there are 2-3 new processes, that's all.
And as they 'die' within seconds when I close VSCode Remote, it shows that it is vscode that keeps them active or at least makes the system to see them like that.
Maybe that is the problem that vscode does not kill the unused processes but leaves them somehow hanging unused and so adding to process count? :)

Thank you!

**Comment by roblourens** [comment]
I don't think we are looking at a list of real processes

```
       /proc/[pid]/task/[tid]/children (since Linux 3.5)
              A space-separated list of child tasks of this task.  Each
              child task is represented by its TID.

              This option is intended for use by the checkpoint-restore
              (CRIU) system, and reliably provides a list of children only
              if all of the child processes are stopped or frozen.  It does
              not work properly if children of the target task exit while
              the file is being read!  Exiting children may cause non-exit‐
              ing children to be omitted from the list.  This makes this
              interface even more unreliable than classic PID-based
              approaches if the inspected task and its children aren't
              frozen, and most code should probably not use this interface.

              Until Linux 4.2, the presence of this file was governed by the
              CONFIG_CHECKPOINT_RESTORE kernel configuration option.  Since
              Linux 4.2, it is governed by the CONFIG_PROC_CHILDREN option.
```

I can't really explain the numbers you are seeing, and I'm not sure where to go from here, sorry.

**Comment by anttin2020** [comment]
Ok, that is anyway the exact same number that I get in cPanel statistics and sadly that is what defines the processes I am using and the limit of 100 is based on that value :(

Anyway, thank you very much for you help, I am loking for other solution instead of VSCode Remote i.e. SSHFS :)

**Comment by PavelSosin-320** [comment]
@Chuxel There are native limitations for the number of containers too. I suppose very few users pay attention to how many containers the local docker engine can maintain, Even less look at containers number is shown in docker info output and almost nobody does docker container prune due to obscure documentation. Every container which has exited but not evicted has its own cost in the process count and disk space. The out-of-resources situation in the docker **doesn't produce any error message** but only exit code 137. After Win 10 2004 Home release it's indeed possible to run Docker on 8Gb laptop without paying for Pro license.  But it doesn't include **certain container resource requirements**. In the out-of-memory/disk space cases **container can fail to start silently** with exit code 137.
It doesn't look good how docker reclaims container resources too.
docker system df
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              89                  14                  17.43GB             16.31GB (93%)
Containers          58                  25                  39.16kB             22.28kB (56%)
Local Volumes       43                  5                   229.7MB             444.9kB (0%)
Build Cache         0                   0                   0B                  0B
