### ISSUE TITLE
Log no longer appears when using Reopen Locally after a failure

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#2971]
Extension version: 0.117.0
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

Repro:

1. Reopen a folder in a container with a Dockerfile that should fail to build
2. Once it fails, say reopen locally

Expected: Log of the failure appears
Actual: No log appears, nor is there an option presented to show it

**Comment by chrmarti** [comment]
Ack, we have 2 experiments prepared, A is to just open locally, B is to open the log locally and C is to open the devcontainer.json locally. Should maybe have made opening the log A. As a workaround you can use `Remote-Containers: Open Log File...`.

**Comment by Chuxel** [comment]
@chrmarti Quick ping on this one - I still see the same problem in the current insiders build.

**Comment by chrmarti** [comment]
Yeah, I don't want to change this right now as the experiment is being set up. It should get fixed as we increase the percentage for 'B'. /cc @sana-ajani

**Comment by Chuxel** [comment]
@chrmarti @sana-ajani @bamurtaugh This particular bug is getting pretty frustrating. My understanding of the experiment was about which button would cause the log to appear.  Right now, there's no way to get the log to show up without using a separate command and digging through the list.

The thing we did at the same time as doing this was no longer have a separate window appear to edit the dev container file. The problem now is the log is gone, so you're left not knowing what happened or being able to go back and reference.

I'm a bit unclear how having the log appear is affecting the experiment.

**Comment by bamurtaugh** [comment]
I agree we'd want to address this one since good user logs seem to be a recurring theme throughout the extensions. From my understanding of the experiment and metrics as well, I didn't think log appearance itself would affect it. I believe some other factors of the experiment are still being ironed out, but the core metrics are already determined. @sana-ajani would likely be better able to confirm.

**Comment by chrmarti** [comment]
@Chuxel I underestimated the amount of work involved to get the experiment up and running. I now see the experiment in action in Insiders, so we should be getting close.

You can use `F1` > `Remote-Containers: Open Log File...` to open any log files.

**Comment by Chuxel** [comment]
@chrmarti Yeah the issue here is people don't know that - I've recently heard numerous complaints about not seeing the log. So the UX right now of requiring `F1` is problematic. I don't understand how this is related to the experiment - we should be showing the log in either case.

**Comment by chrmarti** [comment]
@sana-ajani Assigning to you since you control the assignments in the experiment. Unless the experiment indicates otherwise we should turn on the "Show Log" case once the experiment is done.

**Comment by chrmarti** [comment]
Fixed with the experiment settling for opening the devcontainer.json.
