### ISSUE TITLE
Respect ssh config includes

### ISSUE THREAD

**Issue by develerik** [microsoft/vscode-remote-release#2976]
It would be great if the ssh remote extension could show hosts defined in an included file.

For example in my `~/.ssh/config` file I have a line telling to include another file `Include config_local` and in this included file I defined all my ssh host configurations. If I now click on the remote connection button in vs code it doesn't show me any connection I defined in the included file.

**Comment by SuNNjek** [comment]
For some reason this already works for me, but I found if I use a wildcard like `Include config.d/*` it doesn't include all the files in the config.d directory

**Comment by Nowaker** [comment]
Likewise, `Include *.d` syntax doesn't work either.

```
% grep -F .d ~/.ssh/config
Include *.d
% ls ~/.ssh/*.d
/home/nowaker/.ssh/something.d
```

**Comment by roblourens** [comment]
I think a dupe of https://github.com/microsoft/vscode-remote-release/issues/2446
