### ISSUE TITLE
Loading and git operations slowed down

### ISSUE THREAD

**Issue by alexandercerutti** [microsoft/vscode-remote-release#2977]
Issue Type: <b>Performance Issue</b>

I think the issue regards the April 2020 Update, but I'm not completely sure, because I wasn't able to downgrade Remote -WSL. I tried to downgrade VSCode to March update and I'm still having the same problems (I wasn't).

First VSCode + Remote loading now takes more time to complete.
Moreover, when I want to commit few rows of a file that have different changes, it takes up to 10/15 seconds to stage the change, and 10/15 seconds to commit or to open the indexed files changes.

I've tried to open my project without Remote - WSL and installed git. I had no problems with staging rows or open index files.

Extension version: 0.44.2
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (2.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz (8 x 1498)|
|Memory (System)|7.60GB (2.13GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    86	  6836	code main
    2	    72	  1016	   window (Issue Reporter)
    0	     7	  7560	   C:\Users\alexa\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-d69a79b73808559a91206d73d7717ff5f798f23c.exe /verysilent /update="C:\Users\alexa\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-d69a79b73808559a91206d73d7717ff5f798f23c.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0	    19	 15952	     "C:\Users\alexa\AppData\Local\Temp\is-IGKFV.tmp\CodeSetup-stable-d69a79b73808559a91206d73d7717ff5f798f23c.tmp" /SL5="$E0564,55885417,168960,C:\Users\alexa\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-d69a79b73808559a91206d73d7717ff5f798f23c.exe" /verysilent /update="C:\Users\alexa\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-d69a79b73808559a91206d73d7717ff5f798f23c.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0	   163	  7932	   window (passkit-visual-designer [WSL: Ubuntu] - Visual Studio Code)
    0	    57	 10196	     extensionHost
    0	    28	 13360	       electron_node wslDaemon.js 
    0	     6	 14704	         C:\windows\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" ff915844119ce9485abfe8aa9076ec76b5300ddd stable .vscode-server 0  '
    0	     5	  7468	           C:\windows\System32\lxss\wslhost.exe {27d7aba3-d3f9-48e8-87f6-23b67bc96f6b} 488 496 500
    0	    13	 13836	             console-window-host (Windows internal process)
    0	    11	  8840	           console-window-host (Windows internal process)
    0	    12	  9616	   electron-crash-reporter
    0	   235	 11596	   gpu-process
    0	    61	 11804	   shared-process
    0	    31	 12464	   utility

Remote: WSL: Ubuntu
CPU %	Mem MB	   PID	Process
    0	     0	    19	remote agent
    0	     0	    35	   watcherService
    0	     0	   351	   extensionHost
    0	     0	   407	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	   408	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: WSL: Ubuntu|    Folder (passkit-visual-designer): 161 files|      File types: tsx(47) less(25) svg(19) ts(12) json(5) otf(4) png(2)
|                  gitignore(1) js(1) html(1)
|      Conf files: package.json(1) tsconfig.json(1) webpack.config.js(1)
|                  launch.json(1) settings.json(1)
|      Launch Configs: chrome;
```

</details>

**Comment by alexandercerutti** [comment]
I've tried to reinstall VSCode and install also the Insider version, but nothing changed at all. Staging, diff-ing, and committing is really painful.

Weirdly, I've also tried to downgrade VSCode-Remote WSL but I still have problems. I've tried to remove the VSCode WSL servers in `/home/<user>/.vscode-servers/bin` but nothing changed.
I don't really know what to do, but I practically cannot develop anymore using VSCode with WSL. 😕

**Comment by alexandercerutti** [comment]
Upgrading to Windows Insiders + WSL 2, the performance got back up almost normally. What I noticed is that when staging or unstaging a chunk of code, it doesn't disappear but remains highlighted as changed until you don't change the file you are viewing.

**Comment by bamurtaugh** [comment]
Thanks for the updates @alexandercerutti. Since it sounds like things are working again as expected, going to close this issue, but please let us know if you run into any other issues or have any other questions.
