### ISSUE TITLE
Parallel running for updates and common usage

### ISSUE THREAD

**Issue by HsunGong** [microsoft/vscode-remote-release#2978]
I subscribe the lastest channel of VSCODE. However, I found that once if the vscode gets update, and I can not use vscode-remote while downloading the newest core of `remote`.

My situation is : 
(1) Vscode pushs a update 
(2) Update vscode in my local computer
(3) Update vscode in remote VPS

However, while during STEP 3, I can not use vscode-remote while downloading.
This is confusing because my VPS has low speed connection with `vscode-remote download server`.

**Comment by chrmarti** [comment]
Which Remote extension is this? Could you attach its log?
