### ISSUE TITLE
Publish source code for contributing

### ISSUE THREAD

**Issue by WSLUser** [microsoft/vscode-remote-release#298]
I'd want to see each of the Remote extensions have their source code available as in any normal open-source software. Since these extensions are for the open-source VS Code, all work, including this extension should be done in the open in the spirit of working with the open-source community. If that means changing license to MIT, then do so.

**Comment by egamma** [comment]
@WSLUser the current license situation is explained in the FAQ https://code.visualstudio.com/docs/remote/faq#_license-and-privacy

**Comment by WSLUser** [comment]
Thanks for that link. I understand why you made the decision but I don't accept that as a valid reason to not allow others to submit PRs to the source code to make the extensions better for everyone.  Your team is only so large and there is much to do to make these extensions work to their full potential bug free. Let others help. It's in the best interest of everyone.

**Comment by Biswa96** [comment]
Though it is possible to "see" the source code, you-know-how.
