### ISSUE TITLE
Cannot connect multiple VSC using remote development

### ISSUE THREAD

**Issue by srth12** [microsoft/vscode-remote-release#2981]
I have multiple branches in a server. If I try to connect to another branch in the same server using remote development plugin it won't connect. It will start to go in a loop over and over again but not connect to the server at all. 

Even if I use only one branch, and if I restart or reconnect my network it will start to reconnect again and again and stop after some time.

**Comment by rzhao271** [comment]
@srth12 Closing for now as part of housekeeping. Feel free to reply if this issue still occurs for you on the latest version of VS Code (preferably Insiders edition).
