### ISSUE TITLE
Reconnecting

### ISSUE THREAD

**Issue by aleemdxb** [microsoft/vscode-remote-release#2984]
Issue Type: <b>Bug</b>

Successfully connected to linux host but keeps on getting disconnected and automatically reconnecting every now and then many it very difficult to work in remote mode .

Extension version: 0.51.0
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:59:33.029Z)
OS version: Windows_NT ia32 6.1.7601
Remote OS version: Linux x64 4.14.177-139.253.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.86GB (8.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: xxxxxx.compute-1.amazonaws.com|
|OS|Linux x64 4.14.177-139.253.amzn2.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (1 x 2400)|
|Memory (System)|0.96GB (0.18GB free)|
|VM|0%|
</details>

**Comment by rzhao271** [comment]
@aleemdxb closing this issue for now as part of housekeeping. Feel free to reply if the issue still persists for you on the latest version of VS Code (preferably tested with Insiders edition).
