### ISSUE TITLE
Buggy/crahsing when attempting to copy large directory over SSH

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-remote-release#2989]
Tried to paste a large local directory into the SSH remote's explorer, now seems to have crashed something and the window keeps attempting to reconnect. I additionally got the message for "cannot track changes in large directory, click here to learn how to fix", but clicking on the information button did not do anything.

**Comment by Re66** [comment]
> Tentei colar um grande diretório local no explorador do remoto SSH, agora parece ter travado algo e a janela continua tentando se reconectar. Além disso, recebi a mensagem "não é possível rastrear alterações em um diretório grande, clique aqui para saber como corrigir", mas clicar no botão de informações não adiantou.
