### ISSUE TITLE
remote ssh keep saying "attempting to reconnect"

### ISSUE THREAD

**Issue by David-Dawei** [microsoft/vscode-remote-release#2995]
- VSCode Version: 1.45.0
- Local OS Version: window10 
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.open vscode
2.connect to remote
[vscode_bug.docx](https://github.com/microsoft/vscode-remote-release/files/4626991/vscode_bug.docx)

**Comment by LiyouZhou** [comment]
seeing the same

**Comment by sinestic** [comment]
Sadly same problem here. The day after yesterday was working very well. From yesterday every time i click on connect after some second it ask me to reconnect and after a few of attempts it connect successfully, but when i click on extensions or in a file in the folder it aske again to reconnect

**Comment by npmurphy** [comment]
Remote SSH is happy enough for me with no extensions and is very usable. 

But if I load the **Python extension**, the VSCode attempts to reconnect 60 seconds after the "Loading python extension" text appears. On another machine the same occurs but the reconnect time is 30 seconds after "Loading python extension". 

I suspect the issue might be related to 

Some complicating factors: I am going through google-authenticator 2FA and a jump host. 
I attach my [Remote-SSH output](https://github.com/microsoft/vscode-remote-release/files/4688177/client.log), and [the log generated on the server](https://github.com/microsoft/vscode-remote-release/files/4688180/5763d909d5f12fe19f215cbfdd29a91c0fa9208a.log).

**Comment by colindomoney** [comment]
I'm having the same issue connecting to an Ubuntu host. Initial connection is fine, but after a few minutes I get into a loop of continuous reconnects/disconnects. SSH at CLI is fine, tried nightly version of Remote-SSH, removed and re-installed remote server, set to Bash shell, disabled localServer option, disabled ALL extensions, etc. all to no avail.

**Comment by PavelSosin-320** [comment]
Please, mention your build. I got new updates for my Win 10 2004  2005 pre-release every few hours, mostly related to WSL 2 and suffered from Windows instability in WSL, Docker Desktop, Docker desktop WSL integration, and everything related to it. It looks like MS made to many incompatible changes simultaneously to fulfill as many feature requests as possible. Try to look at event and error logs and search solution in Google. I have switched to Ubuntu 20.04 LTS (from MS Store) which already adopted to Win 10 2004.

**Comment by PavelSosin-320** [comment]
P.S. !!!!  The new WSL2 distros have their own IP address behind the new Windows internal DNS as shown under VEthernet and Host Windows is resolved via generated /etc/hosts inside distro.
