### ISSUE TITLE
Unable to connect to linux Remote-SSH host.

### ISSUE THREAD

**Issue by thec0sm0s** [microsoft/vscode-remote-release#2999]
- VSCode Version: 1.45.0
- Local OS Version: Windows 10 1909
- Remote OS Version: NA
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Specify `HostName`, `IdentityFile` and `User` in `~/.ssh/config`.
2. Use windows like path as I require: `C:\users\thecosmos\.ssh\emina.ppk` for `IdentityFile`.
3. Perform: `Remote-SSH: Connect to host ...`

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/34530901/81947638-6b345b00-961e-11ea-8a54-268a331cfa06.png)

**Comment by smaug9** [comment]
ppk, is a putty specific file. you'll need to convert the key to openssh.
https://code.visualstudio.com/docs/remote/troubleshooting#_reusing-a-key-generated-in-puttygen

**Comment by thec0sm0s** [comment]
Thanks a lot! Got it working.
