### ISSUE TITLE
'search files' returns no results with complex paths

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode-remote-release#3001]
<details>
  <summary>system information</summary>

Version: 1.44.2 (system setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

CPUs | Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: enabledrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.66GB (2.40GB free)
Process Argv |  
Screen Reader | no
VM | 0%
</details>

<details>
<summary>extensions</summary>

Extension | Author (truncated) | Version
-- | -- | --
remote-ssh | ms- | 0.51.0
remote-ssh-edit | ms- | 0.51.0
remote-wsl | ms- | 0.44.2
svn-scm | joh | 2.11.1

</details>

Steps to Reproduce:

1. `mkdir -p a/b ; touch a/b/c.txt`
2. search (ctrl-p) for `c.txt`: 1 result found
3. search (ctrl-p) for `b/c.txt`: 1 result found
4. search (ctrl-p) for `a/b/c.txt`: **no results found**

this occurs with both `remote-ssh` and `remote-wsl`.

Does this issue occur when you try this locally?: **No**
Does this issue occur when you try this locally and all extensions are disabled?: **No**

**Comment by Spongman** [comment]
i can't repro this any more in 1.49.1

**Comment by bamurtaugh** [comment]
@Spongman Thanks for the update. Since it sounds like it may have been resolved, going to close it out, but if you experience it again, please just let us know. Thank you!
