### ISSUE TITLE
VS Dev container deployed to orchestration engine exited successfully but preliminary

### ISSUE THREAD

**Issue by PavelSosin-320** [microsoft/vscode-remote-release#3002]
- VSCode Version:
- Local OS Version: Windows 10 2004
- Remote OS Version: Docker 2.3 in swarm node on the local machine
Docker 2.3 Server 19.03 WSS 2.0, 
Kernel Version: 4.19.104-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64

Steps to Reproduce:
1. Activate swarm mode using docker swarm init
2. Deploy base vscode dev container as service:
docker service create --name=paveldevcontainer --replicas 1 --publish published=22,target=220,protocol=tcp mcr.microsoft.com/vscode/devcontainers/base:alpine-3.10
Deployment started but cycles over statuses starting-ready-running-.....
4. Check if Service is created:
C:\WINDOWS\system32>docker service ls
C:\WINDOWS\system32>docker service ps paveldevcontainer
ID                  NAME                      IMAGE                                                     NODE                DESIRED STATE       CURRENT STATE             ERROR               PORTS
hns1dys5e34p        paveldevcontainer.1       mcr.microsoft.com/vscode/devcontainers/base:alpine-3.10   docker-desktop      **Ready**               Ready 4 seconds ago
kkdjheqzghh4         \_ paveldevcontainer.1   mcr.microsoft.com/vscode/devcontainers/base:alpine-3.10   docker-desktop      **Shutdown**            Complete 4 seconds ago
4. Check service's task status on the local node:
C:\WINDOWS\system32>docker ps --all  --filter is-task=true
CONTAINER ID        IMAGE                                                     COMMAND                  CREATED             STATUS                      PORTS               NAMES
33c9cc0a8bef        mcr.microsoft.com/vscode/devcontainers/base:alpine-3.10   "/bin/sh"                1 second ago        Created                                         vscodeDevContainer.1.hjfhrr6wzbodknn8apt9l94vi
e1722aa5bd9a        mcr.microsoft.com/vscode/devcontainers/base:alpine-3.10   "/bin/sh"                5 seconds ago       Created                                         paveldevcontainer.1.xx3w0vxpd09co3i3gf6fxek78
7a81b08d3164        mcr.microsoft.com/vscode/devcontainers/base:alpine-3.10   "/bin/sh"                6 seconds ago       **Exited (0) 1 second ago**                         vscodeDevContainer.1.cqoeem047cpo32aq4hcl4gysl
53cca68581e2        mcr.microsoft.com/vscode/devcontainers/base:alpine-3.10   "/bin/sh"                11 seconds ago      Exited (0) 5 seconds ago                        paveldevcontainer.1.psnyc3lhjryd3lxnh500dx71p
cc916dab6ea8        mcr.microsoft.com/vscode/devcontainers/base:alpine-3.10   "/bin/sh"                12 seconds ago      Exited (0) 6 seconds ago                        vscodeDevContainer.1.tccu5t22qcaruhvtc2f44dc5j 

Does this issue occur when you try this locally?: No this is non-local landscape on the local machine.
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No
Actual:
Dev container deployed to remote node exited immediately after starting with status success.
Expected:
-- Container reaches the ready status and waits until be run. Then Container is waiting for ssh access from User's client machine.
Hint: dev container is initialized incorrectly and **exited when the root process is finished**.
Obviously, because the Alpine SSH server works OK for me! It uses its own entry point.sh script which **starts sshd daemon** and it's keeping container running while **sshd** is listening.
Otherwise, swarm doesn't have any reason to keep this container instance.[Alpine SSHD entryoint](https://github.com/sickp/docker-alpine-sshd/commit/22fe8db139143701e2c9d3c5a2f505e22bea8253#diff-e79a0f502dec2178e3ff24104a22e39a)

**Comment by chrmarti** [comment]
Tracking with #3056.
