### ISSUE TITLE
Better 2FA Support

### ISSUE THREAD

**Issue by nwillems94** [microsoft/vscode-remote-release#3003]
Issue Type: <b>Bug</b>

1. Set `"remote.SSH.showLoginTerminal": false` in settings
2. No prompt appears when remote asks for token. (selecting details on the setup prompt brings up the install terminal). 

Terminal output:
```
To access the system:

1) If not using ssh-keys, please enter your TACC password at the password prompt
2) At the TACC Token prompt, enter your 6-digit code followed by <return>.

TACC Token Code:
 ```

VS Code should prompt for token. Perhaps allowing user to specify the format of the two-factor challenge as suggested by #2170 ?
Setting `"remote.SSH.showLoginTerminal": true` is a workaround. 

Extension version: 0.51.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 3.10.0-957.5.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (9.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: stampede2.tacc.utexas.edu|
|OS|Linux x64 3.10.0-957.5.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz (28 x 2600)|
|Memory (System)|92.84GB (0.74GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Can you try setting `"remote.SSH.useLocalServer": true` in your setting.json and let me know whether it works with that?

**Comment by nwillems94** [comment]
Yes that does seem to work 

(With the warning: Failed to find a non-Windows SSH installed. Password prompts may not be displayed properly! Disable `remote.SSH.useLocalServer` if needed.)

**Comment by roblourens** [comment]
That setting is not the default because of some potential issues with Windows OpenSSH (the warning), if it works for you, you can ignore it, and it should be the default some day
