### ISSUE TITLE
An empty folder is created for any folders mounted to a volume within the workspace

### ISSUE THREAD

**Issue by myermian** [microsoft/vscode-remote-release#3008]
- Version: 1.45.1 (user setup)
- Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
- Date: 2020-05-14T08:27:35.169Z
- Electron: 7.2.4
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- Local OS: Windows_NT x64 10.0.18362
- Remote OS Version: mcr.microsoft.com/dotnet/core/sdk:3.1
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Create a project and utilize remote development containers.
2. Create a volume mount to a folder that is part of the workspace path.

It seems a bit weird that when I bind mount my node_modules folder to a named volume mount, as per the guide suggests, that an empty folder in my host OS (windows) is created. It doesn't do any harm, but can we make it so that folders that are mounted to a volume are not created on the host OS?

https://code.visualstudio.com/docs/remote/containers-advanced#_improving-container-disk-performance

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by PavelSosin-320** [comment]
@myermian Please, clarify! What do you mean when you say "volume on the host OS". Docker volumes are created/mounted inside the Docker file system. You can see them inside the volumes folder under Docker filesystem root. It is easy if you use WSL2. It is impossible to create something outside. You can create NTFS volume outside your node mounted at "target" Docker FS if you use swarm. But bind volumes have to point to an existing path in the Host FS. Imagine **linux ln -s** -it doesn't create any folder.

**Comment by myermian** [comment]
> @myermian Please, clarify! What do you mean when you say "volume on the host OS".

I didn't say "volume on the host OS", but let me explain it better. This is what I have in my **devcontainer.json** file:
```
"mounts": [
  "source=vscode-yarn-cache,target=/usr/local/share/.cache/yarn/v6,type=volume",
  "source="sample-node_modules,target=/workspace/WebApp/ClientApp/node_modules,type=volume"
]
```

I have two folders mounted to docker volumes. If I rebuild the container, those folders remain populated because the contents are stored on a docker volume. This is all normal and expected.

What is strange is that even though the node_modules folder is mounted to a docker volume, an empty folder named node_modules is created on the host OS as well. I'm not sure if this is a bug or by design, but why would an empty folder be created on the host OS when the directory is mounted to a docker volume?

![image](https://user-images.githubusercontent.com/10632162/82559745-1f157900-9b3e-11ea-9961-2da6795bb870.png)

**Comment by PavelSosin-320** [comment]
This question shall be addressed to the Docker'svolume driver developers.
It can be some driver's implementation constraint, for example, symlink can
be created without having FS i-node but hard link requires FS i-node.

**Comment by Chuxel** [comment]
@myermian This is because a folder is actually getting created in the container that is linked to the volume.  What happens is:

1. The local workspace folder is bind mounted into the container.
2. A node_modules folder is created in the container and the volume for node_modules is attached to it.

The creation of the node_modules folder technically occurs in the bind mount. So you get an empty folder.

**Comment by chrmarti** [comment]
This is Docker's behavior. Closing as upstream.
