### ISSUE TITLE
Windows update create remote disconnection and reconnect loop

### ISSUE THREAD

**Issue by sinestic** [microsoft/vscode-remote-release#3013]
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
- Remote OS Version: .051
- Remote Extension/Connection Type: SSH/Docker/WSL SSH

I had server timed out right after the successful connection and i read some issue before that i'm writing right now. 
With some back thinking to the day that begins this problem, i founded that i installed an update of Windows 10. I just uninstalled it and now it work like a charm (for now)

The update is the kb4556799. I think that can create some incompatibility.

**Comment by roblourens** [comment]
Still an issue?
