### ISSUE TITLE
Fail to login with my server with key, alway asked me to input my server password

### ISSUE THREAD

**Issue by alvin08s** [microsoft/vscode-remote-release#3015]
Issue Type: <b>Performance Issue</b>

Fail to login with my server with key, alway asked me to input my server password, I want to login in with key. I have already added id_rsa.pub, and other ssh clinet logined successful.

Extension version: 0.51.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-31-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (8.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.108.9.33|
|OS|Linux x64 4.4.0-31-generic|
|CPUs|Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (64 x 2793)|
|Memory (System)|251.36GB (10.95GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    99	 31232	code main
    0	    35	 10832	   utility
    0	     0	 17964	     
    0	     0	  2956	       
    0	     0	 39976	       
    0	     0	 39908	     
    0	    75	 20956	   window (Issue Reporter)
    0	    23	 24748	   electron-crash-reporter
    0	   171	 29940	   gpu-process
    0	    85	 34648	   shared-process
    0	   212	 38112	   window (Settings - vivo-3a-beta (Workspace) [SSH: 10.108.9.33] - Visual Studio Code)
    0	    78	 27796	     extensionHost
    0	     8	 27868	     console-window-host (Windows internal process)
    0	     5	 39228	     C:\windows\System32\cmd.exe /c (type "D:\Users\11111191\AppData\Local\Temp\vscode-linux-multi-line-command-10.108.9.33-589061986.sh" | ssh -T -D 12204 10.108.9.33 bash) & exit /b 0
    0	     8	 35024	       ssh  -T -D 12204 10.108.9.33 bash

Remote: SSH: 10.108.9.33
CPU %	Mem MB	   PID	Process
    0	     0	 43866	remote agent
    0	     0	 45651	   extensionHost
    0	     0	 45658	   watcherService
    0	     0	 46747	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: SSH: 10.108.9.33;
```

</details>

**Comment by smaug9** [comment]
i found that running the ``FixUserFilePermissions.ps1`` from OpenSSH-Win64 enabled me to use ssh keys within vscode/remote-ssh.

**Comment by roblourens** [comment]
If the key works from an external terminal, it should work from vscode.
