### ISSUE TITLE
Implement standart interaction mechanism with remote/managed containers

### ISSUE THREAD

**Issue by PavelSosin-320** [microsoft/vscode-remote-release#3017]
Since interaction with remotely running containers or service replicas via terminal's streams redirection is impossible due to input stream being disabled, Please, implement the common interaction mechanism based solely on docker exec.
Actual
   - shell terminal is opened.
Expected:
   docker exec mycontId help returns a list of commands predefined as Linux aliases
   docker exec mycontId command executes the predefined command with provided parameters
This mechanism is supported by all orchestration engines as a part of Docker spec.
This mechanism is secure because communication uses Docker tls security while communicating via Docker secured port.
This mechanism ensures the container's safety because doesn't allow removal of the container's structure. or stoppage of essential services like sshd.
This mechanism protects other containers on the same docker network from the non-authorized access.

**Comment by chrmarti** [comment]
We already use `docker exec` everywhere. Closing.
