### ISSUE TITLE
Unable to connect to SiteGround Host via SSH

### ISSUE THREAD

**Issue by BernardKintzing** [microsoft/vscode-remote-release#3018]
- VSCode 
                Version: 1.45.1
                 Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
                 Date: 2020-05-14T08:33:47.663Z (4 days ago)
                 Electron: 7.2.4
                 Chrome: 78.0.3904.130
                 Node.js: 12.8.1
                 V8: 7.8.279.23-electron.0
                 OS: Darwin x64 19.4.0
- Remote Development Version: 0.20.0
- Local OS Version: macOS Catalina 10.15.4
- Remote OS Version:
NAME=Fedora
VERSION="31 (Thirty One)"
                                      ID=fedora
                                      VERSION_ID=31
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open Remote Development
2. Select _Remote-SSH: Connect to Host..._
3. Select _Add New SSH Host_
4. Enter `ssh USER@HOST_NAME -p PORT`

I get the error message: Could not establish connection to "host". The VS Code Server failed to start.

Log:
```
[14:53:12.387] > Starting server with command... /home/u791-cx44naehgfgu/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/home/u791-cx44naehgfgu/.vscode-server/.5763d909d5f12fe19f215cbfdd29a91c0fa9208a.log" < /dev/null
[14:53:12.388] > Waiting for server log...
[14:53:12.884] > Waiting for server log...
[14:53:13.419] > Waiting for server log...
[14:53:13.891] > Waiting for server log...
[14:53:14.537] > Waiting for server log...
[14:53:14.949] > Waiting for server log...
[14:53:16.570] > Waiting for server log...
> Waiting for server log...
[14:53:16.613] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Server did not start successfully. Full server log at /home/u791-cx44naehgfgu/.vscode-server/.5763d909d5f12fe19f215cbfdd29a91c0fa9208a.log >>>
> node: ../deps/uv/src/unix/core.c:544: uv__close_nocheckstdio: Assertion `fd > -1' failed.
> /home/u791-cx44naehgfgu/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/server.sh: line 12: 45004 Aborted                 "$ROOT/node" ${INSPECT:-} "$ROOT/out/vs/server/main.js" "$@"
> <<< End of server log
> 65abff18e926##32##
[14:53:16.614] Received install output: 65abff18e926##32##
[14:53:16.614] Terminating local server
[14:53:16.628] Resolver error: The VS Code Server failed to start
[14:53:16.630] Local server exit: 15
[14:53:16.633] ------
```

Using the same `ssh USER@HOST_NAME -p PORT` command in the terminal I can SSH with no problems

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by casey1701** [comment]
I'm having the same problem! I know this worked before. I entered mine like this:

Host website.com
  HostName website.com:18765
  User u1346-96g3dddyffe9
  IdentityFile ~/.ssh/sshfile

**Comment by BernardKintzing** [comment]
@casey1701 I was not able to figure it out. It appears that SiteGround servers do not run Node; therefore VSCode can not connect to the server. I was able to get around the issue by mounting the server using sshfs. [This Tutorial](https://www.digitalocean.com/community/tutorials/how-to-use-sshfs-to-mount-remote-file-systems-over-sshl)

**Comment by hkammer** [comment]
@BernardKintzing I've had this exact problem with VS Code SSH remote > Siteground.  Any further insight?
Also, is there another link to the DigitalOcean article you included?

**Comment by BernardKintzing** [comment]
@hkammer It seems like the Siteground server don’t have the right packages to allow vscode remote servers to run. I am not sure why the previous link is broken but I ended up mounting the server locally onto my mac using this tutorial.
