### ISSUE TITLE
Option to not ask for names when downloading folder/multiple files

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode-remote-release#3020]
I usually don't want to change names on folder download or multiple file download. Hope there is an option to disable asking and replicate the names on server.

**Comment by bersbersbers** [comment]
This would be especially valuable for multiple downloads.

In addition, kind of orthogonal to this (but I am not sure this warrants a separate issue), the initial save-to location is always the same in my case. Downloading multiple files currently means not only confirming the file name each file, but also changing the save-to location for each file.
