### ISSUE TITLE
When using proxy or vpn, 127.0.0.1 address is not available.

### ISSUE THREAD

**Issue by cxq1992** [microsoft/vscode-remote-release#3021]
When I use a proxy or VPN(must be using 127.0.0.1), vscode remote ssh can link to remote server(in my case, a local VM), but can not retrieve server info, like open a folder, etc.
I get a error which is 
`"Failed to connect to the remote extension host server (Error: connect EADDRNOTAVAIL 127.0.0.1:4458)"`
Any similar situation and solution? Thanks~

**Comment by roblourens** [comment]
If this is still an issue, please try again and include the log from the Remote-SSH output channel

**Comment by cxq1992** [comment]
> If this is still an issue, please try again and include the log from the Remote-SSH output channel

Thank you. The issue didn't happen afterwards.
