### ISSUE TITLE
Need same devcontainer.json both on windows & mac

### ISSUE THREAD

**Issue by TheBegining** [microsoft/vscode-remote-release#3022]
The devcontainer.json on Windows
```
{
    "name": "Existing Docker Compose (Extend)",
    "dockerComposeFile": [
        "..\\docker-compose.yml",
        "docker-compose.yml"
    ],
    "service": "devcontainer",
    "workspaceFolder": "/workspace",
    "settings": {
        "terminal.integrated.shell.linux": null
    },
    "extensions": []
}
```
The devcontainer.json on Mac
```
{
    "name": "Existing Docker Compose (Extend)",
    "dockerComposeFile": [
        "../docker-compose.yml",
        "docker-compose.yml"
    ],
    "service": "devcontainer",
    "workspaceFolder": "/workspace",
    "settings": {
        "terminal.integrated.shell.linux": null
    },
    "extensions": []
}
```

Is there a way for me to set up the "dockerComposeFile" field same and make them work?

**Comment by rickardp** [comment]
Did you try the Mac one on Windows? Because that is the canonical way of writing cross-platform paths and I have this for the "dockerFile" property and it seems to work...

**Comment by TheBegining** [comment]
> Did you try the Mac one on Windows? Because that is the canonical way of writing cross-platform paths and I have this for the "dockerFile" property and it seems to work...

Thank you ,I have try it.It works fine.
