### ISSUE TITLE
Remote-SSH connection stucks

### ISSUE THREAD

**Issue by Taeboush** [microsoft/vscode-remote-release#3026]
latest version of vscode & remote-ssh
both centos 7.7  and centos 8.1 have been tried but the same issue
remote.SSH.showLoginTerminal: true
remote.SSH.useLocalServer: false

here's the log after i input password:
> 9845af879560: running
> Acquiring lock on /root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/vscode-remote-lock.root.5763d909d5f12fe19f215cbfdd29a91c0fa9208a
> \ln /root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/vscode-remote-lock.root.5763d909d5f12fe19f215cbfdd29a91c0fa9208a.target /root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/vscode-remote-lock.root.5763d909d5f12fe19f215cbfdd29a91c0fa9208a
> Found existing installation at /root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a...
> XDG_SESSION_ID=3
> SHELL=/bin/bash
> SSH_CLIENT=myip 35598 22
> USER=root
> VSCODE_AGENT_FOLDER=/root/.vscode-server
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
> MAIL=/var/mail/root
> PWD=/root
> LANG=en_US.UTF-8
> HOME=/root
> SHLVL=2
> LOGNAME=root
> SSH_CONNECTION=myip 35598 172.18.48.192 22
> LESSOPEN=||/usr/bin/lesspipe.sh %s
> XDG_RUNTIME_DIR=/run/user/0
> _=/usr/bin/printenv
> Starting server with command... /root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/root/.vscode-server/.5763d909d5f12fe19f215cbfdd29a91c0fa9208a.log" < /dev/null
> Waiting for server log...
> Waiting for server log...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 9845af879560: start
> sshAuthSock====
> agentPort==42196==
> osReleaseId==centos==
> arch==x86_64==
> webUiAccessToken====
> tmpDir==/run/user/0==
> platform==linux==
> 9845af879560: end

and there's no more log and i've to shut it down by CTRL+C
again and again

**Comment by trueman1990** [comment]
I got the same issue using the newest vscode version 1.45.1.

**Comment by FelipeMLopez** [comment]
Same here.
I reinstalled everything, vscode 1.45.1 and remote-ssh 0.51.0 (Ubuntu 18.04), and it's working fine so far. If the problem comes up again, I'll let you know.

**Comment by qqq689** [comment]
How to get WhatsApp code through a link or another number

في الأربعاء، ٢٧ أيار، ٢٠٢٠ ١:٠٠ ص Felipe M. López <notifications@github.com>
كتب:

**Comment by bamurtaugh** [comment]
Are folks still experiencing this issue, or has updating/reinstalling everything seemed to mitigate it?

**Comment by FelipeMLopez** [comment]
Hi Brigit,
Right now I have installed version 1.50.1 of VS and remote-SSH 0.55.0, and everything seems to work perfectly. I have not experienced this problem again.

**Comment by bamurtaugh** [comment]
Thanks so much for the update @FelipeMLopez! Going to close out this issue, but happy to reopen if other folks mention they're still experiencing it.
