### ISSUE TITLE
VSCode Freezing SSH Remote Plugin

### ISSUE THREAD

**Issue by ambigus9** [microsoft/vscode-remote-release#3027]
Hi, currently i'm getting some random freezing on VSCode while using SSH Remote Plugin. 

I tried with Ubuntu 20.04 and Windows10. Here is an screenshot about the cpu consuming while is freezing...

![Captura de pantalla de 2020-05-21 10-06-09](https://user-images.githubusercontent.com/16579856/82578953-b684c700-9b52-11ea-8ba2-3c668b58674e.png)

Help me, please!

**Comment by ambigus9** [comment]
Switching **off** `git.autorefresh` in the **Settings** apparently solve the problem.

**Comment by bamurtaugh** [comment]
Thanks for the update @ambigus9! Please feel free to let us know if you have any other questions or feedback.
