### ISSUE TITLE
Better Sync Between VS Code Local & Remote

### ISSUE THREAD

**Issue by drcrook1** [microsoft/vscode-remote-release#303]
When configuring Python & Python Unit Tests in either remote or local it seems that the settings do not consistently remain in either.

I will configure unit tests, test frameworks & test directories repeatedly.  If I change any settings (requirements or baseline container dependencies) these settings appear to not stay.

It would be great if more effort could be placed in features to support consistency between the two environments.

**Comment by drcrook1** [comment]
A Great example of this is __pycache__ folder and .pyc files.  if I edit these files on a local host machine (not the docker container running onthe host) and test out testing or really anything; it creates these files.

In the resulting image that gets run, those are persisted.  From a python unit testing perspective (at a minimum) this means that the tests are not discovered.  I have to manually go through my files & folders and delete ALL __pycache__ folders.  In my case, I have ~4000-ish files and that sucks terribly.

**Comment by egamma** [comment]
@drcrook1 pls describe your setup in more detail, what remote extension are you using?

The VS Code extensions do not sync state, are you using the setting synch extension?

//CC @qubitron

**Comment by AngellusMortis** [comment]
> I have to manually go through my files & folders and delete ALL **pycache** folders. In my case, I have ~4000-ish files and that sucks terribly.

```bash
find . -iname "__pycache__" -type d -exec rm -rf {} \;
```

And I think he is refering to the fact that remotes (including Containers, which is kind of annoying) persist there own "Remote Settings" in a location, that by default, is destructible. So if I [settings to make py.test work](https://code.visualstudio.com/docs/python/unit-testing#_test-configuration-settings) and then the container is destroyed, those settings go away. 

This [docker-in-docker example](https://github.com/microsoft/vscode-dev-containers/blob/master/containers/docker-in-docker/.devcontainer/Dockerfile#L11) is the best way I have figured out to handle it. Essentially you either copy or mount a settings file to `~/.vscode-remote/data/Machine/settings.json` when the container either gets built or launched. Then that Remote settings file can be stored in your repo and committed as part of the development configs.

**Comment by Chuxel** [comment]
@AngellusMortis @drcrook1 Yeah if this is about settings, then [we've documented this as the approach](https://code.visualstudio.com/docs/remote/containers#_default-container-specific-settings) to handle ensuring settings stick around.

The python dev container definition actually has a `.devcontainer/settings.vscode.json` file in it that you can modify to keep settings around. [See here](https://github.com/microsoft/vscode-dev-containers/blob/master/containers/python-3/.devcontainer/settings.vscode.json).

**Comment by Chuxel** [comment]
I should also say that if you add settings to the workspace or user, they are also reused inside the container.  The main purpose for the container specific settings is absolute paths and things that you may want to vary by container like your theme or a color in the UI.
