### ISSUE TITLE
VSCode-Server not installing/running on Windows Server 2012R2

### ISSUE THREAD

**Issue by ChristophPa** [microsoft/vscode-remote-release#3032]
- VSCode Version: 1.45.1
- Local OS Version: Windows 10
- Remote OS Version: Windows Server 2012R2
- Remote Extension/Connection Type: SSH

I have 2 Windows Server 2012R2, one is working one is working fine and the other one has the following problem :( 
I also tried with VSCode Insiders and Remote -SSH(Nightly)

Any help is appreciated. Perhaps this is a windows settings issue?
I have no clue.

**Steps to Reproduce:**

1. SSH ist working fine
2. Connect to remote-host
3. vscode-server.zip is copied to server but the expanding server into temp ist not working

```
> 13:54:14.746] "Copy server to host" terminal command done
> [13:54:15.792] > Found flag and server on host
> [13:54:15.796] > 
> > Expanding server into C:\Users\XXXXXXX\AppData\Local\Temp\axwp1itz.fad
> [13:54:15.815] > 
> > 7c3dc2b7b55e%%2%%
> > 
> [13:54:31.594] > vscode-server failed to start. - A parameter cannot be found that matches parameter name 'DestinationPath'.
> [13:54:31.612] > 
```
4. Server failed to start...... There is no folder with unzipped server-stuff.

**I tried this Workaround: manually unzip server.zip**

1. I can start the server on the remote host without issues
2. VSCode cannot start the server correctly

```
13:34:28.880] > 
> Starting server with command... & 'C:\Users\XXXXX\.vscode-server\bin\5763d9
> 09d5f12fe19f215cbfdd29a91c0fa9208a\server.cmd' --host=127.0.0.1 --enable-remote-
> auto-shutdown --port=0  *> 'C:\Users\XXXXXX\.vscode-server\.5763d909d5f12fe1
> 9f215cbfdd29a91c0fa9208a.log'
> 
[13:34:32.975] > Server did not start successfully. Full server log at C:\Users\XXXXX\.vscod
> e-server\.5763d909d5f12fe19f215cbfdd29a91c0fa9208a.log >>>
[13:34:32.984] > 
> 
[13:34:33.033] > <<< End of server log
[13:34:33.040] > 
> 859d68ad2d11##32##
> 
[13:34:33.041] Received install output: 859d68ad2d11##32##
[13:34:33.044] Resolver error: The VS Code Server failed to start
[13:34:33.054] ------

```
==> The log file is not created. If I create one before running the log file ist deleted. So I have no log about the Error there, except that the log file ist missing :/

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by aaronggi** [comment]
I just fixed this issue locally with a workaround. I'm hoping it's the same issue you're seeing, since I had the same errors -- 

**Issue:**
A PowerShell module I had previously installed, **Pscx** has a command, `Expand-Archive` that clobbers the default powershell `Expand-Archive`

**Temporary Fix:**
Specify the module to be used when invoking `Expand-Archive`.
_Note: This should be performed on the **client** box (i.e. the one doing the connecting)_
In `C:\Users\<User>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.51.0\out\extension.js`:
Do a search&replace such that `Expand-Archive` is replaced with `Microsoft.PowerShell.Archive\\Expand-Archive`

Hopefully that helps!

**Comment by ChristophPa** [comment]
Hi, thanks a lot! 
This was exactly my problem with the pscx-module.

**Comment by drk-mtr** [comment]
I don't appear to have the pscx module installed, but I had the same issue and the fix was the same - thanks!

I think it's probably worth keeping the issue open, since it's only resolved via a manual workaround?

**Comment by aaronggi** [comment]
hey @drk-mtr, this had kinda fallen off my radar but I agree. And also I'm glad the fix worked for you! 

I'll clone the repo and submit a pull request this weekend, so hopefully nobody else has to go through the headache
