### ISSUE TITLE
Environment variables not available when running Self-Hosted Codespace

### ISSUE THREAD

**Issue by jcansdale** [microsoft/vscode-remote-release#3033]
- VSCode Version: 1.45.1
- Local OS Version: Mac OS 10.14.6
- Remote OS Version: Widnows 10
- Remote Extension/Connection Type: Self-Hosted Codespace

Steps to Reproduce:

1. Create Self-Hosted Codespace in Windows
2. Connect to Self-Hosted Codespace
3. New Terminal
4. `echo $env:ProgramFiles` (or some other well known envvars)
5. Many Envvars are not available

This stopped build scripts for target project from working. 😢

**Comment by Chuxel** [comment]
Since this is related to the Codespaces service, can you please raise it in the service's repository here: https://github.com/microsoftdocs/vsonline ?

Unfortunately, I can't transfer it myself.  Closing since the right folks will not see it in this repo.
