### ISSUE TITLE
.gitconfig gets copied before postCreateCommand runs

### ISSUE THREAD

**Issue by danecreekphotography** [microsoft/vscode-remote-release#3036]
- VSCode Version: 1.45.1
- Local OS Version: Windows 10.0.19041
- Remote OS Version: node:alpine
- Remote Extension/Connection Type: Dev Container

Steps to Reproduce:

1. Create a new simple project in a git repo that uses node:alpine as the base for the dev container (node:alpine doesn't include git tools by default)
2. Modify the devcontainer.json file to have a postCreateCommand of `apk --no-cache update && apk --no-cache upgrade && apk --no-cache add git` to install git
3. Rebuild the container and attempt to do something involving git from within VSCode

Result: Errors from VSCode about git
Expected result: No errors

At this point if you re-launch the container (not rebuild, just open local then open in container again) git will magically work.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**More details**

As best I can tell this happens because the step to copy .gitconfig over to the container happens before postCreateCommand is run to install git. This means the .gitconfig command fails (you can see it in the output logs when the container builds). When the container is closed and re-opened it works though because at that point git's been installed.

Right now I'm working around this by installing git via a Dockerfile in the .devcontainer folder. This works, however all the published guidance leads people down the path of thinking postCreateCommand is the way to do this but it isn't. Some examples:

Inside the devcontainer.json file:

`  // Uncomment the next line to run commands after the container is created - for example installing git.`

[In the documentation](https://code.visualstudio.com/docs/remote/containers#_indepth-setting-up-a-folder-to-run-in-a-container): 

`For example, here is a devcontainer.json that adds git and the Git Lens extension to the base Debian 9 container image:`

and here:

`A command string or list of command arguments to run inside the container after is created. The commands execute from the workspaceFolder in the container. Use && in a string to execute multiple commands. For example, "yarn install" or "apt-get update && apt-get install -y git".`

**Random musings**

While using Dockerfile to get around this is perfectly functional it's not exactly approachable for people new to all this stuff (like me). I wasted quite a lot of time wondering what on earth was going on before I realized this was the underlying issue.

Ideally one *should* be able to just do this configuration via devcontainer.json since that's what it's there for. Maybe:

1. Add a `preCreateCommand` that runs earlier in the process?
2. Move the .gitconfig copy to after `postCreateCommand`?

**Comment by danecreekphotography** [comment]
So I'll admit I'm not 100% what's going on here, since on my laptop I have no issues with the git install being in postCreateCommand (just tried to reproduce the issue now to get the specific error messages), however I was seeing this all day yesterday on my desktop which lead me to open the issue :(

**Comment by chrmarti** [comment]
We do the Git setup before `postCreateCommand` runs, so that can take advantage of it.

Installing packages as part of the Dockerfile makes sense because you benefit from the caching of the image. With `postCreateCommand` the install runs each time you create a new container.

**Comment by danecreekphotography** [comment]
That makes sense, but why does the documentation specifically say to use postCreateCommand to install git? I have moved the install of git to a Dockerfile, but I did lose a lot of time to trying to figure out how to make this work because the docs said postCreateCommand was the way to do it.

Also, for people using dev containers and not well-versed in Dockerfiles (like me 😁 a few weeks ago) the Dockerfile solution is quite a barrier to overcome before using remote containers. postCreateCommand is a lot simpler

**Comment by chrmarti** [comment]
@Chuxel Should we remove the example showing Git install in postCreateCommand from the documentation? The issue with that is that we copy .gitconfig and configure the credentials helper before postCreateCommand, but only if we see `git` already installed.

**Comment by Chuxel** [comment]
Given when you are saying, yes - the example is intended to show how an existing image can be reused for small things without creating a custom dockerfile. I can switch to something like installing nano.

**Comment by chrmarti** [comment]
Recently reversed order for https://github.com/microsoft/vscode-remote-release/issues/3882
