### ISSUE TITLE
long time to connect remote, and drop frequently

### ISSUE THREAD

**Issue by DaiZack** [microsoft/vscode-remote-release#3038]
Issue Type: <b>Performance Issue</b>

I can connect to the remote ubuntu server through a Openvpn fast by ssh in WSL. 
But when I try to connect with VS-code, the connection is build fast, but cannot start the terminal , sometimes can connect but spend very long time. no output during the terminal starting. (PS: I was able to connect it very fast during the last whole year, this issue just come out last week, and lasts till now)

Extension version: 0.51.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.15.0-96-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.8.0.106|
|OS|Linux x64 4.15.0-96-generic|
|CPUs|Intel Core Processor (Haswell, no TSX) (8 x 3092)|
|Memory (System)|28.75GB (7.07GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   106	 11968	code main
    0	   253	 10424	   gpu-process
    0	    67	 10960	   window (undefined)
    1	    72	 14376	   window (Issue Reporter)
    0	    28	 15560	   utility
    0	   180	 16984	   window (● config - Desktop - Visual Studio Code)
    0	    11	  2608	     watcherService 
    0	    11	  9956	       console-window-host (Windows internal process)
    0	    72	  4084	     extensionHost
    0	    34	 11664	     searchService
    0	     6	 12308	     winpty-process
    0	    68	 15880	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    12	 17228	       console-window-host (Windows internal process)
    0	   181	 17056	   window (Extension: Python - Visual Studio Code)
    0	     6	  7468	     winpty-process
    0	    10	 10200	       console-window-host (Windows internal process)
    0	     4	 16808	       C:\WINDOWS\System32\cmd.exe /c (type "C:\Users\dieze\AppData\Local\Temp\vscode-linux-multi-line-command-10.8.0.106-601649565.sh" | ssh -T -D 52178 zdai@10.8.0.106 bash) & exit /b 0
    0	     4	  8756	         C:\WINDOWS\system32\cmd.exe  /S /D /c" ssh -T -D 52178 zdai@10.8.0.106 bash"
    0	     7	  6688	           plink  -T -D 52178 zdai@10.8.0.106 bash    
    0	     6	 15008	     winpty-process
    0	     4	  3708	       C:\WINDOWS\System32\cmd.exe /c (type "C:\Users\dieze\AppData\Local\Temp\vscode-linux-multi-line-command-10.8.0.106-245671375.sh" | ssh -T -D 52191 zdai@10.8.0.106 bash) & exit /b 0
    0	     4	 10144	         C:\WINDOWS\system32\cmd.exe  /S /D /c" ssh -T -D 52191 zdai@10.8.0.106 bash"
    0	     8	 12488	           plink  -T -D 52191 zdai@10.8.0.106 bash    
    0	    10	 12176	       console-window-host (Windows internal process)
    0	    66	 18200	     extensionHost
    0	    14	 17892	   electron-crash-reporter
    0	    81	 17948	   shared-process

Remote: SSH: 10.8.0.106
CPU %	Mem MB	   PID	Process
    0	     0	  3038	remote agent
    0	     0	  3196	   extensionHost
    0	     0	  7718	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  7719	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● config - Desktop - Visual Studio Code)
|    Folder (Desktop): 19 files
|      File types: lnk(12) pdf(6) ini(1)
|      Conf files:
|  Remote: SSH: 10.8.0.106;
```

</details>

**Comment by roblourens** [comment]
Terminal issue is maybe https://github.com/microsoft/vscode-remote-release/issues/2313
