### ISSUE TITLE
[wsl2][docker] Windows git config applied to container

### ISSUE THREAD

**Issue by hsimah** [microsoft/vscode-remote-release#3041]
I set up my WSL2, Docker and vs code environment this weekend.

I am finding an issue when attempting to use git:
```
root@bb7f765df0d6:/var/www/html# git clone git@github.com:hsimah/my-repo.git
Cloning into 'my-repo'...
fatal: cannot run C:/Windows/System32/OpenSSH/ssh.exe: No such file or directory
fatal: unable to fork
```
Dockerfile:
```
FROM wordpress:latest
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get -y install --no-install-recommends apt-utils dialog 2>&1 \
    && apt-get -y install git \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
ENV DEBIAN_FRONTEND=dialog
```

If I remove the Dockerfile install of git and run `apt-get update && apt-get install git` from my container there is no issue. In this case git uses my host ssh keys (loaded via ssh-agent service on Windows) and can pull and push both via terminal or vs code itself.

There are no errors or warnings in the log.

EDIT: Okay I did some digging and for some reason my Windows git config is being pulled into my container:
```
core.sshcommand=C:/Windows/System32/OpenSSH/ssh.exe
core.editor="C:\Users\hamis\AppData\Local\Programs\Microsoft VS Code\Code.exe" --wait
```
I updated these manually and this fixes my issue.

Question now is how did this happen? Is this a bug or something wonky with my configuration?

**Comment by chrmarti** [comment]
/duplicate #2267

Tracking with #2267.
