### ISSUE TITLE
trying to use podman results in "Docker version 17.06.1 or later required"

### ISSUE THREAD

**Issue by FlorianLudwig** [microsoft/vscode-remote-release#3042]
- VSCode Version: 1.45.1
- Local OS Version: Fedora 31
- Remote OS Version: Fedora 31
- Remote Extension/Connection Type: Container

Steps to Reproduce:

1. have podman instead of docker
2. Install addon
3. attach to running container
4. "Docker version 17.06.1 or later required"

```
$ docker version
Version:            1.9.2
RemoteAPI Version:  1
Go Version:         go1.13.10
OS/Arch:            linux/amd64
```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
We relax the version check only if the executable (after following all symlinks) is called `podman`. Does that explain the behavior? Did you rename the executable yourself or was it installed this way?

**Comment by FlorianLudwig** [comment]
I installed "podman-docker" which is a shell script wrapper around docker. I removed it and made it a symlink - now it works.

**Comment by chrmarti** [comment]
I see, we can investigate improving that check.

Remote-Containers will have a setting to specify the "Docker" CLI (which can then be `podman`) with VS Code 1.46 (currently available with VS Code Insiders).

**Comment by DMouse10462** [comment]
Some additional info (Fedora 32, same issue with `podman-docker` installed):
```
[user@localhost ~]$ whereis docker
docker: /usr/bin/docker /usr/share/man/man1/docker.1.gz
```

Contents of `/usr/bin/docker` (added by `podman-docker` package):
```
#!/usr/bin/sh
[ -f /etc/containers/nodocker ] || \
echo "Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg." >&2
exec /usr/bin/podman "$@"
```

On my system (Fedora Silverblue), this area of the filesystem is intentionally immutable, so manual edits to this area aren't (easily) possible or recommended. I did a `touch /etc/containers/nodocker` as is suggested to suppress the additional output from the wrapper script, but it may be useful to know that the default installation prints that echo line to stderr.

**Comment by DMouse10462** [comment]
It may be useful to use the `docker -v` or `docker --version` commands to differentiate between "podman" and "Docker"; both clearly state their name followed by the word version and a corresponding version string. 

Running `docker version` does not seem to have consistency between the two; Docker displays its full name as "Docker Edition - %distType%" where podman does not report its name at all with the versions I tested (see below).

# Examples

Docker Community Edition on Ubuntu 20.04
```
user@host:~$ docker -v
Docker version 19.03.6, build 369ce74a3c
user@host:~$ docker version
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Podman on Fedora 32 Silverblue
```
[user@host ~]$ docker -v
podman version 2.0.2
[user@host ~]$ docker version
Version:      2.0.2
API Version:  1
Go Version:   go1.14.3
Built:        Wed Dec 31 19:00:00 1969
OS/Arch:      linux/amd64
```

**Comment by chrmarti** [comment]
Fixing by using `docker -v`, thanks @DMouse10462 !

**Comment by JacksonKearl** [comment]
I can't seem to figure out how to install podman-docker and it's proving an impossible phrase to search. Can anyone help verify that this is working now or provide steps on how I can verify?

**Comment by DMouse10462** [comment]
Which distribution? It's available in CentOS/Fedora's repos and the AUR. I'm using Fedora 32 and the package is able to be installed without issue.

https://pkgs.org/search/?q=podman-docker

**Comment by JacksonKearl** [comment]
@DMouse10462 Yes that would explain it, I was on Ubuntu. Are you able to confirm that it works now?

**Comment by DMouse10462** [comment]
I got it to list my containers, therefore "solving" the titled issue, but couldn't actually get containers to work in practice. Existing Fedora toolbox containers failed to install the server and new containers created in VS Code couldn't access folders due to permissions issues, but these could also be Fedora Silverblue/ostree quirks. I've yet to be able to test it on a non-ostree distro as my other daily driver is Pop! OS (which uses Docker and not Podman).

**Comment by DMouse10462** [comment]
Got a Fedora Workstation 32 install running and, again, no docker version error. However, the socket path used "/var/run/docker.sock" is only available as root, and user-level socket files are located in `/run/user/$UID/podman/podman.sock` per [discussion](https://github.com/containers/podman/issues/4499#issuecomment-609893190) in containers/podman#4499.

This is _technically_ beyond the scope of the issue of podman not being detected at all, but if this issue represents podman _support_ within the extension then this issue is within scope. The specific error I receive upon attempting to create a container with a repository in a new volume is as shown:

![Screenshot from 2020-08-09 02-09-03](https://user-images.githubusercontent.com/2002606/89726152-58df7880-d9e5-11ea-9c9b-03e270f4268e.png)

**Comment by JacksonKearl** [comment]
@DMouse10462 thanks for the investigation! I'll loop in @chrmarti for how to handle this going forward.

**Comment by chrmarti** [comment]
Using a volume is tracked as https://github.com/microsoft/vscode-remote-release/issues/2881. It is currently not supported.

To verify: Install podman-docker and make sure Remote-Containers does not complain about Docker not being a recent enough version.

**Comment by DMouse10462** [comment]
In that case, I can verify from Fedora Workstation 32 that installing `podman-docker` and attempting to use it causes the extension to no longer complain about the Docker version and allows the extension to be used.

Thanks for the heads-up on issue 2881.
