### ISSUE TITLE
Cannot start VSCode from WSL command line 

### ISSUE THREAD

**Issue by MithicSpirit** [microsoft/vscode-remote-release#3044]
Issue Type: <b>Bug</b>

1. Open WSL Ubuntu from Windows Terminal or the Ubuntu app
2. Run `code .`
3. Nothing happens (except for a new line)

Extension version: 0.44.2
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3400)|
|Memory (System)|15.95GB (7.02GB free)|
|VM|0%|
</details>

Note: `code` is definitely on my PATH, as can be seen from the following: 
```sh
$ echo $PATH
/home/mithic/.nvm/versions/node/v12.16.3/bin:/home/mithic/.local/bin:/home/mithic/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/SageMath 9.0:/mnt/c/Program Files/dotnet/:/mnt/c/Users/rpc01/.windows-build-tools/python27/:/mnt/c/Users/rpc01/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/rpc01/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/rpc01/AppData/Local/Programs/Microsoft VS Code/bin
$ which code
/mnt/c/Users/rpc01/AppData/Local/Programs/Microsoft VS Code/bin/code
```

**Comment by aeschli** [comment]
can you run `bash -x "$(which code)" ?
Also `code . --verbose`

**Comment by MithicSpirit** [comment]
Just tried it again and it seems to run fine now. I think it might be due to me updating to WSL 2 a couple of days ago.
