### ISSUE TITLE
Test: Extensions are cached

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#3052]
Refs: #2227

- [x] windows @RMacfarlane
- [x] anyOS @weinand

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%233052%0A%0A)

---

- Setup a devcontainer (see any of the [instructions](https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#testing-remote-containers)).
- Add a list of extensions to its devcontainer.json (or the attach config, if you are using the attach case). (E.g., using 'Add to devcontainer.json' from the Extensions viewlet's context menu.)
- Rebuild the container and verify the extensions are installed.
- Enable 'trace' logging in the settings:
![image](https://user-images.githubusercontent.com/9205389/82996582-75cef700-a005-11ea-82c5-6537b0e1e2eb.png)
- Rebuild the container and verify the extensions are copied over from the local cache.
  - `Remote-Containers: Show Log` and search for `extensions cache`. One of these entries should say that it copies the extensions to the remote.

If you are using a single container:
- Add `"mounts": ["type=volume,src=extensionsCache,target=/home/node/.vscode-server-insiders/extensionsCache"]` to your `devcontainer.json`.
- Verify that rebuilding the container now copies the extensions to the container only once, after that the copies on the mounted volume are used. (Again check the log with 'trace' level enabled.)
- Note: If you are running the container as another user than root, you will need to create the `extensionsCache` folder in the container with that user as the owner in your Dockerfile first (a Docker limitation). E.g.:
```Dockerfile
FROM node:12
USER node
RUN mkdir -p /home/node/.vscode-server-insiders/extensionsCache
```

/fyi @Chuxel Not sure if you want to document the advanced case of mounting a volume (see above).

**Comment by weinand** [comment]
I'm seeing:
```
[2016 ms] Extensions cache, copy to remote: andreweinand.mock-debug-0.41.0, eamodio.gitlens-10.2.1
```
@chrmarti that's the correct log message, right?

**Comment by chrmarti** [comment]
@weinand That's the right message. And yes "copy to remote" means that the copies from the mounted volume are not used. I realize the "mounts" definition above says `/home/node` when it would be `/root` in your case, maybe that's the issue?

**Comment by weinand** [comment]
@chrmarti after changing the path in the container.json from `/home/node` to `/root` I see a
```
[2008 ms] Extensions cache, copy to remote: None
````
That looks better, right?

**Comment by chrmarti** [comment]
@weinand Yes, thanks. 👍
