### ISSUE TITLE
Test: GPG forwarding

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#3053]
Refs: #72

- [ ] windows @connor4312
- [x] anyOS @bpasero

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%233053%0A%0A)

---

- Install GPG locally (E.g., [GPGTools for Mac](https://gpgtools.org/), [Gpg4win for Windows](https://www.gpg4win.org/)).
  - Note that one pitfall can be that an already running VS Code might not have the new install on its PATH yet. Restart VS Code to be sure.
- List existing keys: `gpg --list-secret-keys --keyid-format LONG`
- Generate a new key if you don't have one already: `gpg --gen-key`
- Test installation locally:
  - Test file: `echo test > test.txt`
  - Sign: `gpg --output test.sig --detach-sig test.txt`
  - Verify: `gpg --verify test.sig test.txt`
- Create `Dockerfile` in empty folder:
```Dockerfile
FROM mcr.microsoft.com/vscode/devcontainers/base:0-alpine-3.10
RUN apk update \
    && apk add --no-cache gnupg
```
- Open folder and run `Remote-Containers: Reopen in Container` command.
  - Pick `From 'Dockerfile'` in configuration picker.
- Check the socket and two files are in the container: `ls ~/.gnupg` should show `S.gpg-agent  pubring.kbx  trustdb.gpg`
- Repeat the above test in the container:
  - Test file: `echo test > test.txt`
  - Sign: `gpg --output test.sig --detach-sig test.txt`
  - Verify: `gpg --verify test.sig test.txt`

If there is time: Repeat with a Debian base image:
- Create `.devcontainer.json` in an empty folder:
```json
{
	"image": "node:12",
	"remoteUser": "node"
}
```
- Reopen folder in container.
- Repeat above tests in container.
(Note: Using user `node` because `root` in this particular image comes with files in `~/.gnupg` and we don't overwrite existing files.)

/fyi @Chuxel In case any of this helps with documentation.

**Comment by airtonix** [comment]
Needs:

- opt in flag in vscode settings
- support installing gnupg via `.devcontainer.json` `postCreateCommand` (we're not modifying our dockerfiles)

**Comment by bpasero** [comment]
Verified both for the `Dockerfile` as well as `.devcontainer.json` on Linux (Ubuntu 18).

**Comment by connor4312** [comment]
Works beautifully
