### ISSUE TITLE
Can't view images when doing ssh-remote, port other than 22 is used.

### ISSUE THREAD

**Issue by zehongs** [microsoft/vscode-remote-release#3055]
- VSCode Version: 1.46.0-insider
- OS Version: Catalina 10.15.4; Darwin x64 19.4.0

Why I can't view an image through ssh-remote mode? 
My situation is port22 is disabled, and I login by `ssh -p NUMBER name@ip -A`, where the host listens to that port. 

Steps to Reproduce:

1. Login to ssh-remote with `-p` specified. Simply can't view images in any window/tab. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
@zehongs do icons show up in the explorer?
What kind of image are you trying to load?

**Comment by zehongs** [comment]
@egamma 
- ![image](https://user-images.githubusercontent.com/25296730/83022776-9c6d4c00-a05e-11ea-8941-1128211c521d.png)
- Very standard images, which could be opened by the stable version.

Plus1: I reinstalled the insider version, still can't work. The stable-version can work. I reinstalled the stable version, can work.
Plus2: Not only images, I also can't "view" jupyter notebook(again, insider-version). The output seems quite normal.

![image](https://user-images.githubusercontent.com/25296730/83023144-1c93b180-a05f-11ea-8547-e1844f8f2b7e.png)

<details>
  <summary>jupyter output</summary>
Starting Jupyter from /opt/conda/bin/python with command line --no-browser --notebook-dir=/tmp/435b02b2-c926-42ac-b101-ca9fb1bd09f3 --config=/tmp/435b02b2-c926-42ac-b101-ca9fb1bd09f3/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0 --ip 127.0.0.1 --allow-root
[I 21:13:46.847 NotebookApp] The port 8888 is already in use, trying another port.
[I 21:13:46.955 NotebookApp] JupyterLab extension loaded from /opt/conda/lib/python3.7/site-packages/jupyterlab
[I 21:13:46.956 NotebookApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 21:13:46.958 NotebookApp] Serving notebooks from local directory: /tmp/435b02b2-c926-42ac-b101-ca9fb1bd09f3
[I 21:13:46.958 NotebookApp] The Jupyter Notebook is running at:
[I 21:13:46.958 NotebookApp] http://127.0.0.1:8889/?token=8db5a70eaae1a675649117ea6c22c4527db0b1e0847cf23d
[I 21:13:46.959 NotebookApp]  or http://127.0.0.1:8889/?token=8db5a70eaae1a675649117ea6c22c4527db0b1e0847cf23d
[I 21:13:46.959 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:13:46.962 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/nbserver-61618-open.html
    Or copy and paste one of these URLs:
        http://127.0.0.1:8889/?token=8db5a70eaae1a675649117ea6c22c4527db0b1e0847cf23d
     or http://127.0.0.1:8889/?token=8db5a70eaae1a675649117ea6c22c4527db0b1e0847cf23d
[I 21:13:47.112 NotebookApp] Creating new notebook in /
[I 21:13:47.259 NotebookApp] Kernel started: 9aeb018e-f5db-4b0a-8dbd-cdf359045a93
[I 21:13:47.892 NotebookApp] Creating new notebook in /
[I 21:13:48.006 NotebookApp] Kernel started: 4f024896-7451-4796-a613-39791d15924c

</details>

**Comment by bamurtaugh** [comment]
Hey @zehongs, following-up on this thread, are you still running into this issue? And was/is this just an issue with VS Code Insiders?

**Comment by zehongs** [comment]
Thanks for the following-up. But I've switched to stable release version now!
