### ISSUE TITLE
Option to specify global docker-compose environment file or docker-compose working directory

### ISSUE THREAD

**Issue by rucciva** [microsoft/vscode-remote-release#3067]
We would like to run Dev Container that extend our current docker-compose environment, whose files (including .env file) reside in a certain sub folder in the workspace. Specifying `env_file` only on the service used as dev container is not enough since there are other services that depends on the inherited environment from docker-compose `.env` file. Currently, [vscode can  only pick up the file from the root of the workspace](https://code.visualstudio.com/docs/remote/containers-advanced#_option-2-use-an-env-file).  

So we need an option in `.devcontainer/devcontainer.json` to specify the location of this environment files, much like `--env-file` in docker-compose command line flag. We would like to avoid moving the environment files since it would become an inconvenience for our members that are not using Dev Container. Thanks

**Comment by rucciva** [comment]
> A simple resolution here could be to have a docker-compose file that extends your main one that is only reference in devcontainer.json. That can then reference either your other env file or add a set of variables directly. See https://aka.ms/vscode-remote/containers/docker-compose/extend

Actually i did this. but it's not enough.

My directory structure is like the following:

```
/
/build
/build/docker
/build/docker/.env
/build/docker/docker-compose.yml
/build/docker/docker-compose.override.yml
```

I usually run docker-compose by first entering `/build/docker` directory, thus making entry in `/build/docker/.env` available to be used automatically inside docker-compose.yml. Some of the services defined in `docker-compose.yml` use those environments, for example:

```
services:
  myservice:
    ...
    environment:
     - MY_ENV
     - MY_OTHER_ENV=test_${MY_ENV}
```

these services are not the one who will be used as dev container, instead it will be dependencies of the dev container.

now if i use dev container by using other docker-compose, say `.devcontainer/docker-compose.yml` and extend the existing docker-compose.yml, vscode will run docker-compose from `/`, not from `/build/docker`. thus `/build/docker/.env` will not be used by docker-compose, rendering needed environment empty. I can point my dev container to use `/build/docker/.env` using `env_file` but not that simple with myservice, especially for `MY_OTHER_ENV`. 

creating a new .env file is possible workaround but now i need to mainntains two env files which some of the value are the same. It would be simpler if i can specify where the env file for the docker-compose globally, or even better, where the docker-compose should be started

**Comment by Chuxel** [comment]
Got it - I don't believe we have a way to do this today (unless @chrmarti knows of a trick I do not). So, marking as a feature request.

**Comment by rucciva** [comment]
Great, thank you very much @Chuxel

**Comment by chrmarti** [comment]
Tracking as https://github.com/microsoft/vscode-remote-release/issues/2706.
