### ISSUE TITLE
Cannot have two different remote connections to the same server

### ISSUE THREAD

**Issue by JPTIZ** [microsoft/vscode-remote-release#3069]
- VSCode Version: 1.45.1
- Local OS Version: Linux 5.6.13-arch1-1
- Remote OS Version: Microsoft Windows Server 2019 Standard (Version 10.0.17763 N/A Build 17763)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Have a simple Windows Server setup with:
  - Compiler;
  - OpenSSH server installed and started;
  - Accessible through `<user>@<address>` via SSH;
  - Two users (e.g. "One" and "Two").
2. Have, in one computer, VSCode to connect to `One@address` via Remote-SSH;
3. Have, in *another* computer, VSCode to connect to `Two@address` via Remote-SSH too;
4. `One`'s connection will work out of the box and can even use debugging tools;
5. `Two` will fail because there's already a connection running:
  ```
vscode-server with 5763d909d5f12fe19f215cbfdd29a91c0fa9208a is already running.
[14:45:34.628] > Server did not start successfully. Full server log at...
  ```

Does this issue occur when you try this locally?: _I don't have the resources to test it :(_
Does this issue occur when you try this locally and all extensions are disabled?: Yes (except for Remote-SSH extension).

**Comment by roblourens** [comment]
If this is still an issue, please share the full log
