### ISSUE TITLE
Can't open two container folders due to EADDRINUSE

### ISSUE THREAD

**Issue by ahayzen** [microsoft/vscode-remote-release#307]
- VSCode Version: 1.34.20-insider 57b550c559b945eb9d871dbf2b2e4cb9e31e2551
- Local OS Version: Ubuntu 18.04.2 LTS
- Remote OS Version: any (I was using Debian Stretch)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Create two remote dev container projects
2. Open folder in container to project A
3. Notice the project open successfully and the bottom left green part has the name of the container
4. Open a new window (File -> New Window)
5. Open folder in container to project B
6. Notice that this fails to open, the bottom left green part is stuck saying "Opening remote...". If one looks in the console the following has failed.  Furthermore note that the container of project B doesn't stop when vscode is closed, as it failed to open successfully.

```
Run: docker exec -w /home/developer/.vscode-remote/bin/57b550c559b945eb9d871dbf2b2e4cb9e31e2551 8ce7b4a1fafeceeee62086efc66437da8f5a4656bab12529d2dcca7d8a7537fc /bin/sh -c PATH="/home/developer/.vscode-remote/bin/57b550c559b945eb9d871dbf2b2e4cb9e31e2551/bin:$PATH" /home/developer/.vscode-remote/bin/57b550c559b945eb9d871dbf2b2e4cb9e31e2551/server.sh --disable-telemetry --port 9753
Remote configuration data at /home/developer/.vscode-remote
*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*
IP Address: 192.168.1.249
IP Address: 172.17.0.1
Error occurred in server
{ Error: listen EADDRINUSE :::9753
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at Server.listen (net.js:1466:7)
    at T._start (/home/developer/.vscode-remote/bin/57b550c559b945eb9d871dbf2b2e4cb9e31e2551/out/vs/agent/remoteExtensionHostAgent.js:373:582)
    at T.<anonymous> (/home/developer/.vscode-remote/bin/57b550c559b945eb9d871dbf2b2e4cb9e31e2551/out/vs/agent/remoteExtensionHostAgent.js:371:371)
    at Generator.next (<anonymous>)
    at o (/home/developer/.vscode-remote/bin/57b550c559b945eb9d871dbf2b2e4cb9e31e2551/out/vs/agent/remoteExtensionHostAgent.js:16:221)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 9753 }
```

This is because container for project A is already using port 9753, so project B cannot use this for the vs code server.

Can vscode not track the containers it has open and increase/change the port number for each project that is opened ?

Does this issue occur when you try this locally?: n/a
Does this issue occur when you try this locally and all extensions are disabled?: n/a

**Comment by chrmarti** [comment]
9753 should be the port inside the container, on the host a random port should be chosen. Are the containers sharing the network interface?

**Comment by OutdatedVersion** [comment]
I am also running into this issue, @chrmarti. 

In our case, we are using the host's networking within the container. I'm not sure how to continue.

**Comment by chrmarti** [comment]
Try setting `"devPort"` to a different port in the devContainer.json of the second container.

**Comment by ahayzen** [comment]
Yes I was using `--network=host` to allow for auto sharing of X11 sockets into the container, changing this to `--volume=/tmp/.X11-unix:/tmp/.X11-unix` allows for multiple container folders to be opened :clap:   

The `devPort` seems useful as well for containers that you need to be using host.  Do you think it would be worth adding to the docs ( https://code.visualstudio.com/docs/remote/containers ) about how using `--network=host` will cause this limitation and you should use `devPort` to manually choose a different port ?

**Comment by OutdatedVersion** [comment]
Yeah, I also dropped the use of the host networking. Though, added it back for something else. The second container is not able to connect to the remote extension host server.

My dev port is set to 9755, but the extension is attempting to connect to `37742`. I am not sure if this is related or not, so I could definitely use some guidance.

**Comment by chrmarti** [comment]
@OutdatedVersion `devPort` is the container's port which is exposed on a random (free) port of the host machine. The extension connecting to a different port than `devPort` is expected. Make sure you rebuild the container (e.g., by manually deleting it or using the Rebuild Container command in VS Code) after changing `devPort`.
