### ISSUE TITLE
Remote SSH fails when connecting to Ubuntu 20.04 (Focal Fossa) servers

### ISSUE THREAD

**Issue by sarapayne** [microsoft/vscode-remote-release#3070]
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-31-generic

- SSH

Steps to Reproduce:

1. Setup two servers, one using 19.04, the other using 20.04. 
2. Copy the local SSH public key to both new servers.
3. Test with the terminal to ensure connection to both servers work - it does in my case
4. Using vs code Remote-SSH: Connect To host
5. Add the details for your 19.04 server.. this should work, at least mine does. 
6. Repeat step 5 but with your 20.04 server details, it will fail.

ssh -p 7000 username@IpAddressOfServer

```
[18:57:01.715] Spawned 40295
[18:57:01.817] > local-server> Spawned ssh: 40303
[18:57:01.819] stderr> OpenSSH_8.2p1 Ubuntu-4, OpenSSL 1.1.1f  31 Mar 2020
[18:57:16.828] stderr> ssh: connect to host **UrlRemoved** port 22: Connection timed out
[18:57:16.829] > local-server> ssh child died, shutting down
[18:57:16.834] Local server exit: 0
```

For some reason, when connecting to the focal fossa servers it is attempting to do something on the default port 22 instead of the port supplied. This results in a time out for obvious reasons.

**Comment by roblourens** [comment]
If this is still an issue, can you share the full log? Does it work if you set up an ssh config with that custom port?
