### ISSUE TITLE
Unable to write file EACCES permission denied error when attempting save a read-only file

### ISSUE THREAD

**Issue by slymz** [microsoft/vscode-remote-release#3071]
Saving to a read-only file does not work the way it does locally.  Attempting to do so yields the following error:

```
Failed to save 'foo.txt': Unable to write file 'vscode-remote://ssh-remote+bargrill/home/slymz/foo.txt' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/home/slymz/foo.txt')

[Retry] [Save As...] [Discard]
```
## System info

Version: 1.46.0-insider (user setup)
Commit: e1d8f5155c0db5ffdc130c9aa0f14efac02dfdfb
Date: 2020-05-13T18:20:10.752Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

- Remote OS Version: Debian 10
- Remote Extension/Connection Type: SSH

## Steps to Reproduce:

1. Create a file, and chmod -w 
2. Edit the file in VSCode remote ssh session, attempt to save.

## Does this issue occur when you try this locally?

No.  When attempting to save a read-only file, "Overwrite?"  "Save As" "Discard" options are presented, and choosing overwrite adjusts permissions as needed and saves correctly.   Tried locally both on host (Windows, fwiw) and on client machine with the same version of VSCode.

Does this issue occur when you try this locally and all extensions are disabled?: Yes.  I  "Disable all extensions"ed on the client. Renabled Remote - SSH. Connected and tried again.  Same failure.

**Comment by bpasero** [comment]
![recording](https://user-images.githubusercontent.com/900690/111295432-a5f68d80-864b-11eb-9430-10695401da9a.gif)
