### ISSUE TITLE
IPv6 address treated as hostname not address

### ISSUE THREAD

**Issue by matthewberryman** [microsoft/vscode-remote-release#3072]
- VSCode Version: 1.45.1, 1.46.0-insider Commit: 9e439b13d5784538333bee044ca1d1a992bc1c90
- Local OS Version: macOS 10.15.5
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
1. Have an IPv6 address listed in ~/.ssh/config
2. Try and connect through VSCode, Could not establish connection to "ipv6_address_redacted". Could not resolve hostname. Connecting via ssh at command line works fine, however. 

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: N/A - cannot do this without the extension

**Comment by roblourens** [comment]
If this is still an issue, can you give an example of the ssh config?

**Comment by matthewberryman** [comment]
Thanks, have re-tested with latest VSCode stable & insiders and can confirm this is working now for me in both.
