### ISSUE TITLE
remote containers is completely broken for insiders release

### ISSUE THREAD

**Issue by airtonix** [microsoft/vscode-remote-release#3074]
Someone decided to make an insider release that imposes gpg without a settings feature flag.

So now, using remote-container with insiders is completly broken for anyone that can't update their dockerfile.

**Comment by Chuxel** [comment]
//cc: @chrmarti

**Comment by chrmarti** [comment]
Could you append the Dev Containers log? (`F1` > `Remote-Containers: Show Log` or click the link in the progress notification in the lower right during startup.)
