### ISSUE TITLE
Server did not start successfully. 

### ISSUE THREAD

**Issue by ChristophPa** [microsoft/vscode-remote-release#3075]
VSCode Version: 1.45.1
Local OS Version: Windows 10
Remote OS Version: Windows Server 2012R2
Remote Extension/Connection Type: SSH

I use the same vscode setup successful to connect to about 10 other hosts. But this one troubles me.

Thanks for help and advice!

**Steps to Reproduce:**

1. Trying to connect to remote host
2. Server did not start successfully - log file missing

```
[08:01:59.873] > #< CLIXML
> 
[08:01:59.883] > 9f0cf79daa55: running
> 
[08:02:00.224] > Acquiring lock on C:\Users\xyz\.vscode-server\bin\5763d909d5f12fe19f215cb
> fdd29a91c0fa9208a\vscode-remote-lock.5763d909d5f12fe19f215cbfdd29a91c0fa9208a   
[08:02:00.232] > 
> Looking for existing server in C:\Users\xyz\.vscode-server\bin\5763d909d5
> f12fe19f215cbfdd29a91c0fa9208a
> 
[08:02:00.241] > vscode-server already installed. Skipping download...
> Starting server with command... & 'C:\Users\xyz\.vscode-server\bin\5763d9
> 09d5f12fe19f215cbfdd29a91c0fa9208a\server.cmd' --host=127.0.0.1 --enable-remote-
> auto-shutdown --port=0  *> 'C:\Users\xyz\.vscode-server\.5763d909d5f12fe1
> 9f215cbfdd29a91c0fa9208a.log'
> 
[08:02:04.481] > Server did not start successfully. Full server log at C:\Users\xyz\.vscod
> e-server\.5763d909d5f12fe19f215cbfdd29a91c0fa9208a.log >>>
[08:02:04.499] > 
> <<< End of server log
[08:02:04.507] > 
> 9f0cf79daa55##32##
[08:02:04.507] Received install output: 9f0cf79daa55##32##
[08:02:04.508] Resolver error: The VS Code Server failed to start
[08:02:04.514] ------




[08:02:05.255] > 
> <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
> <Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCust
> omObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"
> ><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC
> ><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1
> "><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing m
> odules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T
> ><SR>-1</SR><SD> </SD></PR></MS></Obj><S S="Error">cat : Cannot find path 'C:\Us
[08:02:05.536] > 
> ers\xyz\.vscode-server\.5763d909d5f12fe19f2_x000D__x000A_</S><S S="Error"
> >15cbfdd29a91c0fa9208a.log' because it does not exist._x000D__x000A_</S><S S="Er
[08:02:05.642] > 
> ror">At line:200 char:1_x000D__x000A_</S><S S="Error">+ cat $logfile_x000D__x000
> A_</S><S S="Error">+ ~~~~~~~~~~~~_x000D__x000A_</S><S S="Error">    + CategoryIn
[08:02:05.646] > 
> fo          : ObjectNotFound: (C:\Users\xyz...91c0fa9208a.l _x000D__x000A_</S
> ><S S="Error">   og:String) [Get-Content], ItemNotFoundException_x000D__x000A_</
[08:02:05.664] > 
> S><S S="Error">    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.C
> ommands.GetCo _x000D__x000A_</S><S S="Error">   ntentCommand_x000D__x000A_</S><S
>  S="Error"> _x000D__x000A_</S></Objs>
[08:02:06.005] "install" terminal command done
[08:02:06.006] Install terminal quit with output:  S="Error"> _x000D__x000A_</S></Objs>
```

**Workaround/Troubleshooting:**

1. If I start the server on the host, it starts fine and generates a log file

```
*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


IP Address: 10.71.12.108
Extension host agent listening on 64602


[08:12:04] Extension host agent started.
```

2. Afterwards I can connect successfully with vscode

```
vscode-server already installed. Skipping download...
 [08:12:44.179] > vscode-server with 5763d909d5f12fe19f215cbfdd29a91c0fa9208a is already running.
[08:12:44.224] > fdbb9fcd52d2: start
[08:12:44.233] > 
sshAuthSock====
agentPort==64602==
osReleaseId==windows==
osVersion==6.3.9600==
arch==x64==
platform==windows==
fdbb9fcd52d2: end
Install script is 8564, watching sshd parent 9532
```

**Comment by ChristophPa** [comment]
Any hint anyone? Would appreciate it :)

**Comment by AshleyMinshall** [comment]
Hi @ChristophPa 
I had the same issue (MacOS connecting to Windows pc). I switched to the nightly build and I can connect now. Might be fixed in the next update?

**Comment by roblourens** [comment]
Sorry for the delayed response. Is this still happening @ChristophPa?  I don't think there are any major fixes waiting in the nightly build but that might be worth a shot too. Also would like to hear exactly what you did for 

> If I start the server on the host, it starts fine and generates a log file

**Comment by CoffeeKing68** [comment]
For the record for me, its not working anymore (Nightly and latest). I don't know why, I get this output now:

> [09:51:39.373] stderr> #< CLIXML
[09:51:39.671] > Acquiring lock on C:\Users\Ashley Minshall\.vscode-server\bin\91899dcef7b8110878ea59626991a18c8a6a1b3e\vscode-remote-lock.91899dcef7b8110878ea59626991a18c8a6a1b3e
[09:51:39.685] > 
[09:51:39.691] > Looking for existing server in C:\Users\Ashley Minshall\.vscode-server\bin\91899dcef7b8110878ea59626991a18c8a6a1b3e
> Downloading VS Code Server
> 0d342529a149%%1%%
[09:52:07.016] > Expanding server into C:\Users\Ashley Minshall\AppData\Local\Temp\kzlafniz.4tn
[09:52:07.017] > 
> 0d342529a149%%2%%
[09:52:20.639] > Failed to download & extract vscode-server.
[09:52:20.641] > 
> 0d342529a149##25##
[09:52:20.641] Received install output: 0d342529a149##25##
[09:52:20.642] Server download failed
[09:52:20.642] Terminating local server
[09:52:20.645] Resolver error: Downloading VS Code Server failed. Please try again later.
[09:52:20.665] Local server exit: 15
[09:52:20.671] ------

Hope it helps

**Comment by roblourens** [comment]
It sounds like it's failing to unzip the .zip, I don't know why that would be. After this happens, the downloaded .zip should still be at I think `C:\Users\Ashley Minshall\.vscode-server\bin\91899dcef7b8110878ea59626991a18c8a6a1b3e\vscode-server.zip`, do you see it? Are you able to unzip it?

**Comment by ChristophPa** [comment]
> Sorry for the delayed response. Is this still happening @ChristophPa? I don't think there are any major fixes waiting in the nightly build but that might be worth a shot too. Also would like to hear exactly what you did for
> 
> > If I start the server on the host, it starts fine and generates a log file

If I start the vscode-server on the server in powershell like this. Then the server is up and running and a log file is generated. I also can connect with vscode remote then.

& 'C:\Users\xxx\.vscode-server\bin\5763d909d5f12fe19f215cbfdd29a91c0fa9208a\server.cmd' --host=127.0.0.1 --enable-remote-auto-shutdown --port=0  *> 'C:\Users\xxx\.vscode-server\.5763d909d5f12fe19f215cbfdd29a91c0fa9208a.log'

**Comment by ChristophPa** [comment]
> For the record for me, its not working anymore (Nightly and latest). I don't know why, I get this output now:
> 
> > [09:51:39.373] stderr> #< CLIXML
> > [09:51:39.671] > Acquiring lock on C:\Users\Ashley Minshall.vscode-server\bin\91899dcef7b8110878ea59626991a18c8a6a1b3e\vscode-remote-lock.91899dcef7b8110878ea59626991a18c8a6a1b3e
> > [09:51:39.685] >
> > [09:51:39.691] > Looking for existing server in C:\Users\Ashley Minshall.vscode-server\bin\91899dcef7b8110878ea59626991a18c8a6a1b3e
> > Downloading VS Code Server
> > 0d342529a149%%1%%
> > [09:52:07.016] > Expanding server into C:\Users\Ashley Minshall\AppData\Local\Temp\kzlafniz.4tn
> > [09:52:07.017] >
> > 0d342529a149%%2%%
> > [09:52:20.639] > Failed to download & extract vscode-server.
> > [09:52:20.641] >
> > 0d342529a149##25##
> > [09:52:20.641] Received install output: 0d342529a149##25##
> > [09:52:20.642] Server download failed
> > [09:52:20.642] Terminating local server
> > [09:52:20.645] Resolver error: Downloading VS Code Server failed. Please try again later.
> > [09:52:20.665] Local server exit: 15
> > [09:52:20.671] ------
> 
> Hope it helps

Perhaps this helps you too. But I'm not 100% sure if this is your problem.

**Comment by Kaushy** [comment]
For anyone facing this issue in future this may help. I installed the new version of VSCode (July edition) and connected to my remote server and it doesn't work. I believe the reason was that in the remote server I had two versions of VSCode server installed. Deleting VSCode from remote server allowed the new connection to reinstall itself and establish connection. On my server I did this (Or where ever your remote .vscode-server folder resides). Inside the server, under bin i had two folders as in the screenshot which probably was causing the issue. 

![Screenshot 2020-08-19 at 13 55 05](https://user-images.githubusercontent.com/4283649/90637402-dac07480-e223-11ea-965b-b73c8660865f.png)


rm -r /user/xxxx/home/.vscode-server/

Now connect from VSCode and it worked.

**Comment by ChristophPa** [comment]
> For anyone facing this issue in future this may help. I installed the new version of VSCode (July edition) and connected to my remote server and it doesn't work. I believe the reason was that in the remote server I had two versions of VSCode server installed. Deleting VSCode from remote server allowed the new connection to reinstall itself and establish connection. On my server I did this (Or where ever your remote .vscode-server folder resides). Inside the server, under bin i had two folders as in the screenshot which probably was causing the issue.
> 
> ![Screenshot 2020-08-19 at 13 55 05](https://user-images.githubusercontent.com/4283649/90637402-dac07480-e223-11ea-965b-b73c8660865f.png)
> 
> rm -r /user/xxxx/home/.vscode-server/
> 
> Now connect from VSCode and it worked.

This does not change anything in my case :(

**Comment by ChristophPa** [comment]
It ist very fast, one sec perhaps

**Comment by roblourens** [comment]
I'm just guessing at things here but when it prints that message

> Full server log at C:\Users\xyz\.vscode-server\.5763d909d5f12fe19f215cbfdd29a91c0fa9208a.log >>> [...]

maybe you could check to see whether that file is actually empty or if it has useful contents a few seconds later?
