### ISSUE TITLE
Remote ssh stopped working, can't connect anymore (bash: XYZ: command not found)

### ISSUE THREAD

**Issue by AlfredoMS** [microsoft/vscode-remote-release#308]
- VSCode Version: 1.34.20-insider
- Local OS Version: Win10 Enterprise 1809 (Windows_NT x64 10.0.17763)
- Remote OS Version: Linux 3.10.0-693.11.6.el7.x86_64
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Set up a client vs code with remote SSH. Connect and do some python remote debugging. Everything works ok.
2. Next day set up vs code insiders with remote ssh on a different machine. Try to connect with the same host. SSH prompts terminal for password, right after that it shows error message:
---
Can't connect to XYZ: unreachable or not Linux x86_64 (bash: XYZ: command not found)
---
Can't connect to XYZ: unreachable or not Linux x86_64 (Cannot execute command-line and remote command.)
---

My remote configuration file:

Host XYZ
    HostName XYZ.foo.bar.edu
    User myusername

VS Addon settings:
{
    "remote.SSH.showLoginTerminal": true
}

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: NA

**Comment by AlfredoMS** [comment]
I was able to check back on the first computer where I set the ssh config, and it is still working. Despite me deleting the .vscode-remote dir on the remote server.

The OS and code-insiders version is the same. As far as I can tell the only difference is on the computer where it works it is opening a new code window after I enter my ssh password the first time.

**Comment by AlfredoMS** [comment]
Found the issue, the only difference was a space character in the HostName. So it seems like somebody already reported this: https://github.com/microsoft/vscode-remote-release/issues/284

**Comment by roblourens** [comment]
Glad you figured it out, thanks

**Comment by subni9** [comment]
how to use the extension when i am working on busy box with no bash. just ash
