### ISSUE TITLE
hide docker-desktop and docker-desktop-data

### ISSUE THREAD

**Issue by rfgamaral** [microsoft/vscode-remote-release#3081]
When I use the command `Remote-WSL: New Window using Distro...` I'm presented with the following:

![image](https://user-images.githubusercontent.com/96476/83327840-d9ac2680-a276-11ea-8fb8-bc3db41b280b.png)

- `Debian` is my new WSL 2 instance
- `DebianLegacy` is my old WSL 1 instance
- `docker-desktop` and `docker-desktop-data` were created by Docker Desktop and I never used them directly

What I'm requesting is a configuration option to hide both `docker-desktop` and `docker-desktop-data` WSL instances. Or, instead of configuration options, maybe detect these types of WSL instances and hide them by default?

Either way, these shouldn't be used directly by users (AFAIK), so they should probably be hidden from the interface. Right?

**Comment by PavelSosin-320** [comment]
I think that it will be better to create the list of enabled distros because tomorrow other distros and their versions, like Ubuntu 1804, 2004 can be added, etc. and nobody can know, which of them can be used as a server.

**Comment by aeschli** [comment]
We use `wslconfig /l` to get all available distros. So I guess if `docker-desktop` and `docker-desktop-data` should not be used by user they probably also should also not show there, or they should be marked in a special way. @benhillis any opinion?

**Comment by benhillis** [comment]
Adding @simonferquel.

**Comment by benhillis** [comment]
I agree, it's probably a good idea to have these special types of distros marked in some way.  I'll add this to the backlog.

**Comment by simonferquel** [comment]
@benhillis would be nice, but make sure to add a flag for listing "hidden" distros as well (or provide an API for that)

**Comment by aeschli** [comment]
I pushed a change to hide `docker-desktop` and `docker-desktop-data` (hard coded, for now) from the distro selection dialog.
