### ISSUE TITLE
Dev Container: Allow for "Open Folder" outside of the dev container

### ISSUE THREAD

**Issue by jlorich** [microsoft/vscode-remote-release#3085]
I switch between projects a lot, and when working in a dev container sometimes I want to exit the container and open another file.  To do this I currently need to choose "reopen locally" and then "file->open folder" to see any of my local filesystem.  It would be beneficial in the dev container instance if I could have something like an "open local folder" option which would let me automatically exit the dev container or jump into a new one for that other folder.

**Comment by chrmarti** [comment]
The regular `File` > `Open Folder` should show you a folder picker with a button 'Show Local' to switch to picking a local folder. `Remote-Containers: Open Folder in Container...` is also available when currently connected to a container, so you can switch to another Dev Container with that.

Does this address the feature request?

**Comment by jlorich** [comment]
Perhaps I am a blind idiot. Thank you.
