### ISSUE TITLE
Remote SSH: Git gutter not showing

### ISSUE THREAD

**Issue by giosakti** [microsoft/vscode-remote-release#309]
- VSCode Version: 1.34.20-insider
- Local OS Version: Windows_NT x64 10.0.17763 (Windows 10 Pro)
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open any repository via remote SSH
2. Modify something on the file
3. Colored gutter indicator not showing, but it is showing when I open local repository.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by niallel** [comment]
I saw the same thing when I had only 1GB of memory on my server. Also there were 2 node processes running at 40%.

When I increased to 2GB all the problems went away and git started showing the changes.

**Comment by giosakti** [comment]
The VM that I used is a pristine VM with 4GB RAM and no background job running.

Another interesting thing is: 

when I open git view on vscode, I need to press refresh everytime I modify my files to make the changes reflected on git view.

**Comment by joaomoreno** [comment]
Similar to https://github.com/microsoft/vscode-remote-release/issues/314

Do other Git features work in that case?

**Comment by giosakti** [comment]
@joaomoreno in `explorer view`, when I create a file it is displayed instantly without refresh
however that file won't show on `source control view` unstaged changes until I hit refresh

**Comment by joaomoreno** [comment]
What if you create a file using the command line?

**Comment by giosakti** [comment]
just tried it, the file will be automatically updated in the Explorer pane, but not in Source Control pane (need to click refresh)

**Comment by ryansully** [comment]
Is your remote directory symlinked? I had the same issue with git gutters when connected to a symlinked directory, but when I changed to the source directory, I saw gutters again.
https://github.com/microsoft/vscode/issues/5970

**Comment by giosakti** [comment]
yeah you're correct.. I just checked.
This is the same issue with microsoft/vscode#5970

Closing this in favor of that.
