### ISSUE TITLE
Unexpected DEBUG env added

### ISSUE THREAD

**Issue by dreamerblue** [microsoft/vscode-remote-release#3091]
When I start a terminal and run dev scripts on vscode remote, it outputs many lib debug logs (see screenshots below). Then I found it's because of the extra DEBUG env so the the libs output debug logs.

I can reproduce on two remote servers (one is CentOS when I run `npm run dev` in terminal, and another is Ubuntu when I run Node.js debug commend via `F5`).

console.log(process.env.DEBUG)

```
*,-*:debug,-*:*:debug,-*:*:*:debug,-*:*:*:*:debug,-*:*:*:*:*:debug
```

echo $path

```
/root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/bin /root/.nvm/versions/node/v10.20.0/bin /root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /root/bin /root/bin
```

![screenshot-vscode-remote-debug-env](https://user-images.githubusercontent.com/19774268/83374449-400f8100-a3fe-11ea-8b1c-df100bd0dfb6.png)

- VSCode Version: 1.45.1
- Local OS Version: macOS 10.15.4
- Remote OS Version: CentOS 6/Ubuntu 18.04 both
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open a terminal under remote, or start a node.js debug
2. Output the `process.env.DEBUG` in Node.js
3. It outputs `*,-*:debug,-*:*:debug,-*:*:*:debug,-*:*:*:*:debug,-*:*:*:*:*:debug`

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by jugglingthebits** [comment]
I see a very similar issue (#3247 ) with the Remote: WSL extension locally - it might be the same issue.

**Comment by dahjelle** [comment]
I've run into this on macOS as well.

Extension Version: 0.51.0
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

---

You can also try `echo $DEBUG` from the terminal.

**Comment by dreamerblue** [comment]
Run `echo $DEBUG` in vscode terminal (remote server):

```
*,-babel*,-*:debug,-*:*:debug,-*:*:*:debug,-*:*:*:*:debug,-*:*:*:*:*:debug
```

Run Run `echo $DEBUG` in vscode terminal (local):

```
```

**Comment by dreamerblue** [comment]
Update: It's caused by SQLTools ext.

**Comment by bamurtaugh** [comment]
Thanks for the update @dreamerblue. Since it sounds like this isn't a Remote-SSH issue, closing this thread, but if I've missed something or folks have other questions or issues, I'm happy to reopen or discuss further. Thank you!
