### ISSUE TITLE
(Re)install default extensions

### ISSUE THREAD

**Issue by Morgy93** [microsoft/vscode-remote-release#3092]
Basically I'd love to have an action like `workbench.extensions.installLocalExtensions` just for all extensions defined for `remote.SSH.defaultExtensions`, so I don't have to select them manually for (re)installing.
Maybe even something like `workbench.extensions.action.reinstall` for all `remote.SSH.defaultExtensions`.

Something like `workbench.extensions.(re)installDefaultExtensions` which just loops through `remote.SSH.defaultExtensions` and uses `workbench.extensions.installLocalExtensions` to install each extension would probably fulfill my needs and should be easy to implement.

**Comment by roblourens** [comment]
Not clear what problem this is solving. If it's still an issue, please give some more details.
