### ISSUE TITLE
Remote Containers: Image Preview:  "An error occurred while loading the image"

### ISSUE THREAD

**Issue by matt-deboer** [microsoft/vscode-remote-release#3095]
> Version: 1.46.0-insider
> Commit: 2c1871d538c64df71af4902deba47d7fa4b53f27
> Date: 2020-06-01T11:50:47.719Z
> Electron: 7.3.0
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Linux x64 5.4.0-33-generic snap

This was just updated a few hours ago, but the issue was also occurring with the previous version as well.

**Steps to reproduce:**
1. Place a single image file inside a new folder.
1. Open this folder in vs-code
1. In the Explorer view, click on the image file.
1. The image preview is displayed normally.
1. Issue command `Remote-Containers: Reopen In Container`, and choose any container definition (I choose the Ubuntu image)
1. Once the container opens, click on the same image in the Explorer view
1. "An error occurred while loading the image" is shown in the editor pane.

This functionality was working previously (I don't know the exact version, but probably as of a month ago).

**Comment by chrmarti** [comment]
What image format is this?

**Comment by matt-deboer** [comment]
It looks like this was discussed in https://github.com/microsoft/vscode/issues/98768, and closed with the most recent insiders update. 
I can confirm that image previews in remote containers are working again.
