### ISSUE TITLE
Can't connect to a internal gpu server in private network. 

### ISSUE THREAD

**Issue by richarddwang** [microsoft/vscode-remote-release#3098]
My lab has a private network like this
```
(public address: 133.3.133.133, host name: my.lab.host.name)
lab-gateway (private address: 192.168.0.1)
 |__labgpu01 (private address: 192.168.0.3)
 |__labgpu02 (private address: 192.168.0.4)
```

**I want to leverage labgpu01, but I always got `!hostname` ran in cell of my remote ipynb print `lab-gateway`**

with choosing to connect lab in my `.ssh/config`
```
Host *
    AddKeysToAgent yes
Host lab
    HostName my.lab.host.name
    User remoteuser
```
Is it impossible to connect a specific one of gpu servers ? 

# Extra info
We now do ssh tunnel
```
localuser@localhost ~ $ ssh -L 8888:localhost:9000 username@my.lab.host.name -t ssh -L 9000:localhost:9000 labgpu01
remoteuser@labgpu01 ~ $ jupyter notebook
```
with `~/.jupyter/jupyter_notebook_config.py`
```
c = get_config()
c.NotebookApp.ip='*' 
c.NotebookApp.password = 'sha1:...'
c.NotebookApp.open_browser=False 
c.NotebookApp.port=9000 
```
and then start `localhost:8888` in our home browser, or make jupyter of *not remote development* vscode connect to `localhost:8888`

**Comment by roblourens** [comment]
I think you want the ProxyCommand or ProxyJump ssh config directives, check those out.
