### ISSUE TITLE
Allow custom PATH for using newer git version from /usr/local/git 

### ISSUE THREAD

**Issue by sandeep-sidhu** [microsoft/vscode-remote-release#31]
Allow custom PATH for using newer git version from /usr/local/git 

I have updated git on the system but using custom path via .bashrc and .profile files from /usr/local/git  but vscode keeps using default system git.

Allow a way to define custom PATH for listening agent to use.

**Comment by kieferrm** [comment]
@sandeep-sidhu, you're using the Remote-SSH extension to connect to the box? 

1) We run an interactive login shell to launch the VS Code server. Once you're connected to your SSH box, open the 'Remote-SSH' output channel. There you see the environment in which the VS Code Server was launched. Check if PATH is correct. You might have to change your `.bash_profile` file. 

2) Alternatively: Open the settings editor. There is now a new tab label `Remote (SSH: <your box>)`. Go to the tab, search for 'git path'. This will allow you to specify a custom path for git.

**Comment by sandeep-sidhu** [comment]
@kieferrm   thanks for quick reply.

yes, Im using Remote-SSH extension, and works like a treat, thanks again to everybody who worked on this.

I had the path setup in my .bash_profile, and in the TERMINAL channel, I could see the PATH setup correct, but git extension was always complaining about git version 1.8 while I had 2.1 installed in /usr/local/git/bin/


I followed your 2 steps in, and set following in settings.json for that particular host, and it worked.

`{
    "git.path": "/usr/local/git/bin/git"
}`

**Comment by kybom** [comment]
I have the same problem. Remote os is centos7.

**Comment by roblourens** [comment]
Lots has changed here. Please open a new issue if there is still a problem.
