### ISSUE TITLE
Dragging file into terminal uses wrong path separator

### ISSUE THREAD

**Issue by prashantv** [microsoft/vscode-remote-release#310]
VS Code Version:
```
Version: 1.34.20-insider (user setup)
Commit: 57b550c559b945eb9d871dbf2b2e4cb9e31e2551
Date: 2019-05-10T17:36:45.765Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```
- Local OS: See above, Windows.
- Remote OS Version: Ubuntu Server 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open terminal
2. Drag file into terminal

Expect:
Path of the remote path with `/` separator (as used on unix) to be shown

Got:
Remote path, but using `\` as the separator, which is not valid, as `\` is used to escape on Linux.

**Comment by KenYN** [comment]
Still present for me; Right-Click and Copy Path then Paste into Terminal gives the correct forward slash, though.
