### ISSUE TITLE
Extentions not loading

### ISSUE THREAD

**Issue by aravindhank11** [microsoft/vscode-remote-release#3101]
Issue Type: <b>Bug</b>

At times, especially during low bandwidth cases, the extensions are getting activated over ssh.

Extension version: 0.47.2
VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 19.2.0
Fetching remote diagnostics for 'ssh-remote+dev1' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 7, 7|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'ssh-remote+dev1' timed out.
</details>

**Comment by aravindhank11** [comment]
My extensions include:
C/C++ intelli sense  - 0.27.1
Git Blame - 3.0.1
GitLens - 10.2.1
scope4code - 0.1.4
vscode-proto3 - 0.4.2

**Comment by roblourens** [comment]
Not clear what the issue is.
