### ISSUE TITLE
Support to open a folder from a volume in a container

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#3106]
Testing https://github.com/microsoft/vscode-remote-release/issues/3099

After I inspect the volume and fix the problem with my dockerfile I want to "continue" opening my folder in a container. What is the path to do that? I check the command in the remote indicator and tried the "Open Folder in Container" command, but it fails when I pick a remote folder.

**Comment by egamma** [comment]
@alexr00 you have to open the repository again using "Open Repository in Container", but I see that it is tempting to just open folder from the volume. I'll change this into a feature request.

**Comment by chrmarti** [comment]
Also `Rebuild and Reopen in Container` would make sense since the user might be fixing an issue with the Dockerfile.

**Comment by Chuxel** [comment]
Yeah I commented on this in #3123 - the problem with using Open Repository in Container again is that you have to re-enter the information. That's frustrating when you do it frequently.

I used the MRU to get back to the container, but that's not ideal either.

**Comment by egamma** [comment]
This has been addressed and there now is a 'reopen in container' command.
