### ISSUE TITLE
Is random port safe enough?

### ISSUE THREAD

**Issue by LeuisKen** [microsoft/vscode-remote-release#311]
Hi, I'm exploring how the vscode remote extension works, and I find that if I start a vscode remote server by remote ssh, anyone can connect my host if they know what the host and port is by register a custom remote authority resolver.

So I wonder that is random port safe enough since the host is not hard to know and the port can be scanned. Maybe we need something like session or token to ensure that the vscode remote server was connected by the proper user?

Thanks!

**Comment by tamuratak** [comment]
Related to #291. I agree with you. "Remote - SSH" is totally insecure.

**Comment by LeuisKen** [comment]
> Related to #291. I agree with you. "Remote - SSH" is totally insecure.

You are right, look like duplicate.
