### ISSUE TITLE
Inspect Volume: Have no more than 3 buttons on error dialog

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#3114]
#3099

We have so far tried to avoid having more than 3 buttons. Should we remove the 'Close Remote` one?

![image](https://user-images.githubusercontent.com/172399/83481235-7c45ee80-a49d-11ea-9487-e951e623b131.png)

**Comment by egamma** [comment]
Removed the Close Remote button.

**Comment by chrmarti** [comment]
@egamma Should that be the same:
![image](https://user-images.githubusercontent.com/9205389/94823720-74bf3380-0404-11eb-88a6-3312a2b2817b.png)

**Comment by chrmarti** [comment]
I don't see the fix in source, reopening.

**Comment by egamma** [comment]
@chrmarti sry I've reverted the change since I really missed not having the 'close remote' button in the dialog. Let's discuss again in November.

**Comment by egamma** [comment]
Having 3 buttons is a good goal, but my own user testing revealed that 4 are preferred, closing.
