### ISSUE TITLE
'Open Folder in Container' fails for repository dev containers

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#3115]
- Open a repository in a container
- Run the 'Remote Containers: Open Folder in Container' command from the command palette.
- This is now showing a file picker on the remote file system. Originally we have shown a local file picker, which has avoided this issue.

![image](https://user-images.githubusercontent.com/172399/83610258-77f20200-a57f-11ea-8a94-e46e2a275c55.png)

**Comment by jbergler** [comment]
I've encountered this problem too, my use case is as follows:

Many of us are mac users and we've been unable to get the filesystem performance to where we want it if a volume is mounted from the host OS. To get around this we open the repository in a container.

Until now we have only needed one container for our project.
As we look at adding another container we want to leverage the [connecting to multiple containers at once](https://code.visualstudio.com/docs/remote/containers-advanced#_connecting-to-multiple-containers-at-once) workflow.

I had hoped that we could make our repository devcontainer have docker-in-docker support, and then run the docker-compose multi-folder workflow from inside that.

It would seem that for our use case, the remote file picker is correct, we'd also need the rest of whatever "Open folder in Container" is trying to do to execute inside the remote.

**Comment by chrmarti** [comment]
@jbergler We don't support the nesting at the moment. I'll fix this by not showing the remote filesystem (except if it is WSL). Please open a feature request.
