### ISSUE TITLE
Connect to host in same window via command palette

### ISSUE THREAD

**Issue by tblut** [microsoft/vscode-remote-release#3116]
The current behavior when connecting to a new host via the command palette is that a new instance is opened. It would be nice if I were able to connect to a host in the current instance. The Remote Explorer supports this already, so it would be awesome if this were possible through the command palette as well.

**Comment by andycraig** [comment]
Hi @tblut, I would like this feature too and was going to create a request for it. Why did you close this issue?

**Comment by tblut** [comment]
Hey, because I, for some reason, didn't see that it is already implemented with "Remote-SSH: Connect Current Window to Host..." in the command palette.

**Comment by andycraig** [comment]
I didn't see it either! That solves my problem too. Thank you!
