### ISSUE TITLE
Workspace setting config to autostart in selected WSL distro

### ISSUE THREAD

**Issue by shivapoudel** [microsoft/vscode-remote-release#3119]
There should be a setting for workspace file to autostart VSCode in WLS 2 distro. If we need to auto-switch workspace then they should act accordingly?

**Comment by bamurtaugh** [comment]
If I'm reading this correctly, would you say this is a WSL-specific version of the feature request here: https://github.com/microsoft/vscode-remote-release/issues/120? If so, I'll go ahead and close this thread to avoid duplicates.

**Comment by shivapoudel** [comment]
I have commented over there so you can keep track of feature request over there. Feel free to close this ticket and follow-up over there  :)

**Comment by bamurtaugh** [comment]
@shivapoudel Great, thank you for your response! Closing this issue and will continue tracking feedback there instead :).
