### ISSUE TITLE
Document how to remove server from ssh remote

### ISSUE THREAD

**Issue by kissge** [microsoft/vscode-remote-release#312]
Issue Type: <b>Feature Request</b>

I think I've hit a bug and I cannot connect to a certain host.
From an observation that exitting a VSCode instance or even shutting down Windows didn't resolve the problem, I'm suspecting that the server program that was installed on the remote host needs reinstalling--can I easily achieve this?

Thanks.

Extension version: 0.14.0
VS Code version: Code - Insiders 1.34.20-insider (57b550c559b945eb9d871dbf2b2e4cb9e31e2551, 2019-05-10T17:36:45.765Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 5.0.5-arch1-1-ARCH

**Comment by lars18th** [comment]
Hi @kissge ,

This function exists: Call to "Remote-SSH: Uninstall VS Code Server from Host..." from your VS Code Client.

However, I suggest to create a shell script that anyone can download with a simple "wget" and execute _inside the server_ to remove the installation of the VS Code Server. With this will be more easy to do it that using the VS Code Client.

Regards.

**Comment by kissge** [comment]
Oops, thanks for pointing that out!
You're absolutely right, as that function is not working simply because I cannot connect to the host, and that's why I want to uninstall the server :(

**Comment by kissge** [comment]
For reference for someone hitting the same issue, let me note that simply removing `~/.vscode` and `~/.vscode-remote` seems not working:

```
SSH Resolver called for "ssh-remote+**********"
SSH Resolver called for host: **********
Setting up SSH remote "**********"
Using commit id "57b550c559b945eb9d871dbf2b2e4cb9e31e2551" and quality "insider" for server
Install and start server if needed
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> bash: cannot set terminal process group (78732): Inappropriate ioctl for device
> bash: no job control in this shell
> Installing...
> Downloading with wget
> 
> WARNING: tar exited with non-0 exit code
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> cat: /home/*****/.vscode-remote/.57b550c559b945eb9d871dbf2b2e4cb9e31e2551.log: N
> o such file or directory
> Server did not start successfully. Full server log:
> cat: /home/*****/.vscode-remote/.57b550c559b945eb9d871dbf2b2e4cb9e31e2551.log7bf
> 6dac6-2183-4401-a3d2-68286d887efe====
> : No such file or directory
> 
"install" terminal command done
Received install output: : No such file or directory
Failed to parse remote port from server output: : No such file or directory
```

**Comment by lars18th** [comment]
> For reference for someone hitting the same issue, let me note that simply removing `~/.vscode` and `~/.vscode-remote` seems not working:

Sure! It's mandatory to use the **uninstall** function.

**Comment by roblourens** [comment]
Yes the Uninstall command is correct. It just does two things - delete the server code on the remote and kill any running processes. Your log shows that the code was deleted but that confused a running server.

**Comment by kissge** [comment]
Why closed?
How is it possible to run that command when the VSCode client cannot connect to the host?

**Comment by lars18th** [comment]
Hi @roblourens ,

> How is it possible to run that command when the VSCode client cannot connect to the host?

I feel you need almost to document:
1. The subdirectory to remove: `rm -rf ~/.vscode-remote`.
2. The name of the process to kill: `killall ....` (I don't know the correct name).

Regards.

**Comment by roblourens** [comment]
If vscode can't connect, then how is the server installed?

**Comment by lars18th** [comment]
Hi @roblourens ,

With the current number of errors, it is quite easy for the server to have been installed but not be able to reconnect. Therefore, if the user knows how to do a manual uninstall, then much better. At time, the only missing question it's the name of the server process to killing it.

Regards.

**Comment by roblourens** [comment]
I'm not aware of any issue that lets vscode connect a few times then spontaneously stop being able to connect unless the user changes their configuration. However it would make sense to document all of this.

**Comment by kissge** [comment]
> Maybe there is some issue after installing the server but if the server is installed then the Uninstall command should be capable of running on the remote.

> issue that lets vscode connect a few times then spontaneously stop being able to connect unless the user changes their configuration

Yes, that's exactly what I've been hitting lately!
Since a few days ago I was using VSCode Remote Development successfully, but suddenly it started to refuse connecting. I'd be happy to debug it but for now I have too little knowledge, e.g. where I can get verbose output during connection output.
Thanks for all those clarification on this issue ticket.

**Comment by roblourens** [comment]
Can you share the output from the "Remote - SSH" output channel?

**Comment by kissge** [comment]
I've found that actually connecting itself is successful, but there's something wrong during "Open Folder" (or apparently, during listing files on the home directory on the remote host; since recent folders can be opened).
The log doesn't look like have anything interesting.

```
SSH Resolver called for "ssh-remote+********"
SSH Resolver called for host: ********
Setting up SSH remote "********"
Using commit id "e83e24a0c9225becd7341e56952177a20d5d4629" and quality "insider" for server
Install and start server if needed
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> bash: cannot set terminal process group (69905): Inappropriate ioctl for device
> bash: no job control in this shell
> Found existing installation...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 598a570f-da28-4f0f-8b64-11a4fcb63d5b==43603==
> 
"install" terminal command done
Received install output: 598a570f-da28-4f0f-8b64-11a4fcb63d5b==43603==
Server is listening on port 43603
Spawning tunnel with: ssh  ******** -N -L localhost:31121:localhost:43603
Spawned SSH tunnel between local port 31121 and remote port 43603
Waiting for ssh tunnel to be ready
Tunneling remote port 43603 to local port 31121
Resolving "ssh-remote+********" to "localhost:31121", attempt: 1
SSH Resolver called for "ssh-remote+********"
SSH Resolver called for host: ********
Setting up SSH remote "********"
Using commit id "e83e24a0c9225becd7341e56952177a20d5d4629" and quality "insider" for server
Install and start server if needed
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> bash: cannot set terminal process group (69990): Inappropriate ioctl for device
> bash: no job control in this shell
> 
> 
> Found existing installation...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> ee3d509f-b15f-49b1-91ec-9fa588514109==43603==
> 
> 
"install" terminal command done
Received install output: ee3d509f-b15f-49b1-91ec-9fa588514109==43603==
Server is listening on port 43603
Spawning tunnel with: ssh  ******** -N -L localhost:38327:localhost:43603
Spawned SSH tunnel between local port 38327 and remote port 43603
Waiting for ssh tunnel to be ready
Tunneling remote port 43603 to local port 38327
Resolving "ssh-remote+********" to "localhost:38327", attempt: 2
Tunnel(43603) stderr: channel 2: open failed: connect failed: Connection refused
```

**Comment by roblourens** [comment]
> Tunnel(43603) stderr: channel 2: open failed: connect failed: Connection refused

This looks like a problem but I don't know what it would be.

> I've found that actually connecting itself is successful, but there's something wrong during "Open Folder" (or apparently, during listing files on the home directory on the remote host; since recent folders can be opened).

Can you explain exactly what you try and what you see?

**Comment by samueldy** [comment]
> Hi @roblourens ,
> 
> > How is it possible to run that command when the VSCode client cannot connect to the host?
> 
> I feel you need almost to document:
> 
> 1. The subdirectory to remove: `rm -rf ~/.vscode-remote`.
> 2. The name of the process to kill: `killall ....` (I don't know the correct name).
> 
> Regards.

So `~/.vscode-server/bin/<long ID>/bin/code` is a shell script that calls `node` on `~/.vscode-server/bin/<long ID>/out/remoteCli.js`. So the relevant process to kill is `node`? (Although probably not the best thing to `killall`.)

**Comment by bunchoftrees** [comment]
I'm running into this issue, but to dovetail off of @samueldy - I'm unable to kill the node `node` processes. They're owned by me, but they appear to be unkillable.

**Comment by roblourens** [comment]
Try `kill -9` if you are not already

**Comment by bunchoftrees** [comment]
@roblourens - yep, already tried. We ended up just rebooting the remote server yesterday to kill the processes, but it's unreasonable to do that repeatedly, and we're back in the same state again today.
