### ISSUE TITLE
The workspace can not be opened in a container: Folder 'c:\repos\tmp\ is not a subfolder of shared root folder c:\repos\shared

### ISSUE THREAD

**Issue by eissko** [microsoft/vscode-remote-release#3122]
- VSCode Version: 1.45.1
- Local OS Version: Windows 10. 1909
- Remote OS Version:Centos 7
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. having repository c:\repos\shared\ and mapped it /repos/shared as workspacefolder attribute in devcontainer.json 

2. under this repository workspace with only folders:

 "folders": [
        {
            "path": "./"
        },...
3. open Remote-Containers: Open Workspace in Container
4. workspace is opened successfully
5. adding new folder to the workspace which is folder of remote filesystem running within container, but it is out of the /repos/shared level, example /repos/tmp
6. after folder is added to workspace, it creates new path in workspace definition as ../tmp

here starting the problem.

7. close Remote Container session and open it again. you will get the error message that  
"The workspace can not be opened in a container: Folder 'c:\repos\tmp\ is not a subfolder of shared root folder c:\repos\shared"

and interesting thing is when I open Remote Container through the Welcome page -> Recent -> clicked on the workspace, everything works perfectly fine and the check if ../tmp is under c:\repo\shared is not executed and Remote Container is opened nicely as expected.

Why there is different behavior when opened through Remote-Containers: Open Workspace in Container and workspace is listed through the explorer and different behavior (which is working one) through the Welcome page - recent - workspace?

If there is this check executed - is there a way to specify in the workspace file definition that this path is related to local system a this to remote?

Thanks

**Comment by chrmarti** [comment]
The check tries to make sure the workspace file does not refer to a local folder that is not available in the container. That does not work well in your case.

**Comment by dan-1d** [comment]
Related: Same error when attempting
Remote-Containers: Add Development Container Configuration Files

I've already started a container outside vscode, and successfully attached to it.

I now want to simply edit the connection so that future uses will automatically install the extensions I specify (e.g., Python). However, the menu option above yields the error message
"The workspace can not be opened in a container: Folder 'path/to/workspace/files' is not a subfolder of shared root folder '/path/to/workspaces/conf/files"

**Comment by jongio** [comment]
I ran into this today and would like to second that it would be nice to be able to add folders that aren't sub-folders of the workspace file location

azsdke2e
azsdke2e2

**Comment by Chuxel** [comment]
@chrmarti Given the only downside in this situation is a missing folder, and we're clearly seeing interest here, should we remove this check given it's not quite working right?

**Comment by chrmarti** [comment]
We might still want to avoid having users run into the issue that a folder is not available in the container. To still allow for the case here, we could offer to 'ignore' that not all folders are subfolders to the workspace file's folder.

**Comment by mike43525** [comment]
Hello @chrmarti, I have been silently watching this issue and was expecting it to be fixed in February 2021. It's been now moved to the backlog. Any plans on fixing it? Please just allow us to ignore the warning and move on :)

Cheers

**Comment by chrmarti** [comment]
Adding the option to continue despite the warning. Currently you will have to confirm each time, that could be improved.
