### ISSUE TITLE
Dev container iteration when using "Inspect volume" flow ideally would mirror bind mounts

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#3123]
Testing #3099

Right now I'm working on https://github.com/microsoft/vscode-dev-containers/issues/339 to create a development container for Code - OSS. I plan to switch to using the "open repo" flow now that I can iterate on it.

However, as I started using it, I'm not finding it quite as convenient as the bind mount flow.  In this case I do the following:

1. Open folder in container...
2. On error, click reopen locally
3. Make my edits
4. Reopen in container
5. Go to 2.

I'd envisioned the workflow for using this inspect feature being like this:

1. Open repository in container...
2. On error, click "reopen in recovery container"
3. Make my edits
4. Reopen in container
5. Go to 2.

The "inspect volume" that appears in step 2 didn't quite click immediately as something I'd do to fix a Dockerfile issue.  Once I was inspecting, I also had no quick way to get back, I had to use the MRU list to do it. This is different enough that I'll likely have to have a second section on iterating in docs to describe it - and it's not quite as natural. Going back to "Open Repo in Conatiner" would force me to re-enter the URL and would actually create a new container even if I reused the same volume.

As I build things out, I'll end up doing this iteration in rapid succession since there's no "debug" flow for Dockerfiles... it's like classic "run plus debug output" workflows. So, this is a frequent flow.

**Comment by egamma** [comment]
Related #3112, #3111
