### ISSUE TITLE
.gitconfig not being copied over using Docker Edge + WSL2

### ISSUE THREAD

**Issue by jlorich** [microsoft/vscode-remote-release#3124]
- VSCode Version: 1.45.1
- Local OS Version: Win 10 Pro 2004 + WSL2 Ubuntu 20.04 LTS
- Remote OS Version: Ubuntu 19.04
- Remote Extension/Connection Type: Docker
- Docker Version: 2.3.1.0

Steps to Reproduce:

1. Open container
2. .gitconfig is not copied

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

## Description:

I have a .gitconfig both in my user folder on Windows and on WSL2 yet when I open something with remote-containers neither are copied over.  I do see the credential helper once I installed git for Windows, but there's still no config.  I am using the edge version of docker desktop to start containers inside WSL2.  It's not clear where the intended location the git config should be copied from is, but neither work.  I've tried with multiple different backend containers and the result is the same.

#### WSL:

```
jlorich@DESKTOP-HHE4T4V:~/projects/iot-edge-offline-dashboarding$ git config --list --show-origin
file:/home/jlorich/.gitconfig   user.email=joseph@lorich.me
file:/home/jlorich/.gitconfig   user.name=Joey Lorich
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.ignorecase=true
file:.git/config        remote.origin.url=git@github.com:AzureIoTGBB/iot-edge-offline-dashboarding.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
```

#### Git-Bash on Windows:
```
jlorich@DESKTOP-HHE4T4V MINGW64 ~
$ git config --list --show-origin
file:C:/Program Files/Git/etc/gitconfig http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig core.fscache=true
file:C:/Program Files/Git/etc/gitconfig core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig credential.helper=manager
file:C:/Users/jlorich/.gitconfig        user.name=Joey
file:C:/Users/jlorich/.gitconfig        user.email=joseph@lorich.me
```

#### Remote-container:

```
iotedgedev@372c730cdd8e:~$ git config --list --show-origin
file:/home/iotedgedev/.gitconfig        credential.helper=!f() { /home/iotedgedev/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node /tmp/vscode-remote-containers-79983685729da59cb58c832fba91ad8d3d5f8bcf.js $*; }; f
```

**Comment by chrmarti** [comment]
Is the folder you are opening on a Windows or an a WSL filesystem?

Could you attach the devcontainer.json and Dockerfile?

**Comment by Bazalia** [comment]
I have the same issue. The folder I'm opening is inside WSL. Also I don't have a devcontainer.json because I'm attaching to a running container.

**Comment by chrmarti** [comment]
Could you attach the log (`F1` > `Remote-Containers: Show Log`)?

**Comment by Bazalia** [comment]
[vscode-remote-container-log.txt](https://github.com/microsoft/vscode-remote-release/files/4851609/vscode-remote-container-log.txt)

**Comment by chrmarti** [comment]
@Bazalia The log shows `Copy C:\Users\omars\.gitconfig to /home/node/.gitconfig`. Did that not succeed?

**Comment by Bazalia** [comment]
After checking again I found that it does. But I wanted it to copy over .gitconfig from WSL not windows

**Comment by chrmarti** [comment]
You are attaching to the container, we don't have any indication that you would prefer the WSL .gitconfig in this case. (With a devcontainer.json on the WSL filesystem we do copy the WSL's .gitconfig.)

@Bazalia  Could you open a new issue as a feature request for this? We'll keep tracking @jlorich 's issue here. (Waiting for his log.)

**Comment by jlorich** [comment]
Sorry for the long delay, though this is still an issue:

[devcontainer.log](https://github.com/microsoft/vscode-remote-release/files/4977071/devcontainer.log)
[devcontainer.json.txt](https://github.com/microsoft/vscode-remote-release/files/4977072/devcontainer.json.txt)

You can clearly see the error coping over my local git config, though if I run the container specified in the `devcontainer.json` directly there is no `.gitconfig` present.  It appears the credential helper is creating a `.gitconfig` first, and then the copy fails.

**Comment by jlorich** [comment]
Okay I blew away all my local copies of the container, updated docker desktop, updated vscode... and now it's copying over fine.

 ¯\_(ツ)_/¯
