### ISSUE TITLE
Cannot push from container

### ISSUE THREAD

**Issue by bhack** [microsoft/vscode-remote-release#3127]
- VSCode Version: insider
- Local OS Version: Debian stable
- Remote OS Version: Debian stable
- Remote Extension/Connection Type:Docker

Steps to Reproduce:
I still need to use this workaround https://github.com/microsoft/vscode-remote-release/issues/2087#issuecomment-571140124 to push from the container.

**Comment by chrmarti** [comment]
Would copying `known_hosts` fix this? (#2285)

**Comment by bhack** [comment]
Oh yes sorry I was in that ticket but I supposed It was solved in the meantine instead Is still active. 
I will follow progress there.
