### ISSUE TITLE
Option to automatically pull image on rebuild

### ISSUE THREAD

**Issue by rickardp** [microsoft/vscode-remote-release#3128]
(I am not sure what the intended behavior is so this might not be a bug but rather a feature request then. If so, please move accordingly.)

We are trying out a workflow where the base of our build system sits in a base image shared across many projects. This base image is actively developed and the master branch is considered stable, and hence we want all devs to be able to easily upgrade to the latest version. We currently build this image on our build servers and publish it using the latest tag.

The devcontainer.json contains .e.g.

    "context": "..",
    "image": "our-fancy-buildsystem:latest",

We want the instructions to developers to be to just hit Ctrl+Shift+P and choose rebuild container whenever something useful is pushed to this environment. However, doing so will not pull the image. I did not find any documentation on what intended behavior is, but my expectation was that among other things the image was always pulled in this case.

Now the workaround is quite clumsy,
* Open a terminal window
* Type "docker pull our-fancy-buildsystem:latest"
* Switch to vscode
* Rebuild container

We expected to find a single command to cater for this use case.

- VSCode Version: 1.45.1
- Local OS Version: Windows 10
- Remote OS Version: Docker for windows
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Have the "image" of devcontainer.json point to e.g. a ":latest" tag
2. Rebuild the image and push (on another machine)
3. Choose "Rebuild container"
4. The image is not pulled.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
Have you tried running `docker pull` using the `"initializeCommand"` property?

**Comment by stephanrenggli** [comment]
As you described using docker pull via the "initializeCommand" works and successfully pulls the latest image. However the previously built container based on the now old image is started.

Is there any way for VSCode to detect the presence of a newer image and offer to rebuild the container like it does when a change to .devcontainer.json is detected?
This way developers wouldn't have to manually start the rebuild if they notice the docker image has changed.

See our .devcontainer.json:
```
{
  "image": "ansible_development_image:latest",
  "extensions": [
    "vscoss.vscode-ansible",
    "wholroyd.jinja",
    "samuelcolvin.jinjahtml",
    "esbenp.prettier-vscode",
    "yzhang.markdown-all-in-one"
  ],
  "settings": {
    "terminal.integrated.shell.linux": "/bin/bash"
  },
  "initializeCommand": "docker pull ansible_development_image:latest",
  "postCreateCommand": "chmod -R 644 ../ansible/"
}
```

**Comment by rickardp** [comment]
@stephanrenggli I would prefer if pulling is strictly opt-in (much like Docker build, where you have the —pull option). Many images may be pinned to a specific version and this would mean a useless roundtrip to a container registry.

**Comment by rickardp** [comment]
@chrmarti  As @stephanrenggli said, I didn’t figure out how to abort the container from there and start a new one since Docker pull just runs and exits cleanly. Also, I would have to specify the image twice, error prone!

**Comment by stephanrenggli** [comment]
@rickardp This is true, however I think it would be nice if there was an option to enable this behavior. We currently use GitLab registry and only ever keep one latest version, so a prompt for rebuilding or just a way of detecting a changed base image would be very useful to us.

**Comment by rickardp** [comment]
@stephanrenggli Exactly. The lack of such an option is why I opened this ticket.

I think my original problem description was a bit vague though, as I think introducing the option is better, but since there was no mention of pull on build I kind of expected that to be default behavior.

**Comment by PavelSosin-320** [comment]
This base image is actively developed ??? **But does it mean that it is randomly released** to the public repository? How do you succeed to support it? The proven solution for such a scenario is to use a local docker image repository, like the registry image with very short access time. It makes pull time irrelevant. A good example is the rolling update of Docker-based Clusters which keeps entire cluster both up-to-date and consistent at any point of time thanks to short pull/tag/push time.

**Comment by PavelSosin-320** [comment]
As in Docker documentation: [Deploy Registry server](https://docs.docker.com/registry/deploying/)

**Comment by rickardp** [comment]
@PavelSosin-320 Who said anything about public? In my case I use the Azure ACR and the base image is indeed actively developed. This works very well for us.

**Comment by aaronadamsCA** [comment]
I'd also like to see either a "Pull Image and Rebuild Container" command (in the spirit of `--pull`) or a standalone "Pull Image" command (in the spirit of `docker-compose pull`).

Right now I have to (train people to) either open a separate VS Code window, run **Docker Images: Pull**, and select the right image; or open a local terminal, and run the correct `docker pull mcr.microsoft.com/vscode/devcontainers/...` command. And then, once that's done, rebuild their container.

While hardly a deal-breaker, given how infrequently containers are rebuilt, it's a bit of a pain to have to remember the half-extension-half-not solution every time.

Thanks!

**Comment by twodrops** [comment]
I too support this feature-request. Due to the lack of this feature, we use a version number to reference the image in 'devcontainer.json' which is then updated each time a new image is released.

'"image": "ansible_development_image:0.0.1"'

VScode detects a change in 'devcontainer.json' and triggers a notification to "Rebuild" and the rebuild now pulls the new image as it finds a new image version.

**Comment by PavelSosin-320** [comment]
Please, check that this feature is not supported by the container engine by default as a part of the mandatory orchestration engine feature "Rolling updates". It can be one of the configurable policies. Of course, the Engine must be able to roll back the version automatically if the state reconciliation fails or manually using "docker service rollback".

**Comment by bhack** [comment]
Any news on this?

**Comment by chrmarti** [comment]
The "Rebuild Without Cache" commands also pull a new image. Closing as fixed with https://github.com/microsoft/vscode-remote-release/issues/2200.
