### ISSUE TITLE
Can't connect to host: unreachable or not Linux x86_64 

### ISSUE THREAD

**Issue by mirsking** [microsoft/vscode-remote-release#313]
It happened when I used vscode remote-ssh plugin to ssh to a pure new server.

- VSCode Version:  1.34.20 insider
- Local OS Version: ubuntu 18.04
- Remote OS Version: ubuntu 16.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
1. A pure new ssh server A which you have never ssh to it by client C.
2. Use vscode remote-ssh plugin to ssh to it from client C, it just failed.
3. Open a terminal and ssh to A from C, message below will be showed
```
The authenticity of host 'xxx' can't be established.
ECDSA key fingerprint is : blabla
Are you sure you want to continue connecting (yes/no)?
```
4. Input yes and press enter, After that vscode remote-ssh can ssh to the server successfully.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Could you try this?

- Delete your `~/.ssh/known_hosts` file (or if there are other hosts in it, just open it and delete the line for this server)
- Open vscode, run "Set Log Level", set to Trace
- Try connecting again
- Find the Output channel called "Remote - SSH" and share the logs here

We should be detecting that message and passing it on to you but that is not working for some reason.

**Comment by alexanderwiebe** [comment]
I was getting the same issue connecting to my raspberry pi

I setup the hostname `asdf` and was able to access it via `ssh asdf`.  I found this link and followed the steps from @roblourens 

```
Confirming that asdf is a valid reachable host
Running ssh -o ConnectTimeout=15  "asdf" bash << 'EOSSH'
uname -sm
EOSSH to confirm the host platform
ConfigFileWatcher: closing output:extension-output-%233
"uname" terminal received data: "The authenticity of host '172.16.1.90 (172.16.1.90)' can't be established.
ECDSA key fingerprint is SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.
Are you sure you want to continue connecting (yes/no)? "
"uname" terminal received data: "y"
"uname" terminal received data: "e"
"uname" terminal received data: "s"
"uname" terminal received data: ""
"uname" terminal received data: "Warning: Permanently added '172.16.1.90' (ECDSA) to the list of known hosts.
"
"uname" terminal received data: "pi@172.16.1.90's password: "
"uname" terminal received data: ""
"uname" terminal received data: "Linux armv7l"
"uname" terminal command done
asdf: unreachable or not Linux x86_64. (Linux armv7l
)
```

Here's the details on the Raspberry Pi:
```
Linux raspberrypi 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l
```

Thanks
