### ISSUE TITLE
ssh connection always fails if remote had to downoad/install ssh server

### ISSUE THREAD

**Issue by jineens** [microsoft/vscode-remote-release#3130]
Issue Type: <b>Bug</b>

1) have the server need to download and install the remote server (aka every morning with vscode-insiders)
2) connect with the remote code extension with ssh

expected:
server downloads and installs and then we connect

actual:
server downloads and installs and then... fails to connect. On retry this connects fine.

From my observations (sorry, forgot to grab the log) I think that the first start of the server after install takes longer then if the server was already more or less running, and that the client tries to connect to soon after starting the new server.

This is really annoying because it happens every morning when I sign in.

Extension version: 0.51.0
VS Code version: Code - Insiders 1.46.0-insider (595d2b9b916d063aadfc2c1a8c8f6df5b45572a8, 2020-06-03T05:43:09.908Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: my-machine-name|
|OS|Windows_NT x64 10.0.18362|
|CPUs|Intel(R) Core(TM) i9-9940X CPU @ 3.30GHz (28 x 3312)|
|Memory (System)|63.71GB (50.23GB free)|
|VM|0%|
</details>

**Comment by flapili** [comment]
Hi, I have a similar problem, not sure if it's exactly the same or not

the host is a VM on virtualbox

```
root@debian:~# uname -a
Linux debian 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
root@debian:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```


[.5763d909d5f12fe19f215cbfdd29a91c0fa9208a.log](https://github.com/microsoft/vscode-remote-release/files/4736333/default.5763d909d5f12fe19f215cbfdd29a91c0fa9208a.log)
the logs only containt "main: ligne 371: /root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/server.sh: Aucun fichier ou dossier de ce type"

[tree.txt](https://github.com/microsoft/vscode-remote-release/files/4736340/tree.txt)
tree.txt from `tree .vscode-server > tree.txt`

**Comment by roblourens** [comment]
If this is still an issue, please include the full log, it's not clear what the problem is
