### ISSUE TITLE
Documented vscode / vscode-server / extension version mappings

### ISSUE THREAD

**Issue by umdstu** [microsoft/vscode-remote-release#3136]
In an enterprise environment, where we have to manually install and update VSCode and extensions, trying to manage the version compatibilities is a nightmare. I have not found them readily documented anywhere. It would be much easier to have a table in a README somewhere than to have to jump through some hoops. 

eg.
VSCode       VSCodeServer      Extensions
1.41.1           26076a....5c0       remote-ssh_0.48.0, remote-ssh-edit_0.48.0 to remote-ssh-edit_0.49.0

And so on.
I hope you'll consider this, thanks!
stu

**Comment by roblourens** [comment]
Sorry, not sure what compatibilities you are referring to. Please let me know if this is still an issue.

**Comment by umdstu** [comment]
... yes it's still an issue. Why close it before getting a response?

**Comment by roblourens** [comment]
Because after several months usually people don't reply, and I am cleaning up issues.

But still

> Sorry, not sure what compatibilities you are referring to.
