### ISSUE TITLE
Remote WSL: Source Control not showing changed files

### ISSUE THREAD

**Issue by vitormhenrique** [microsoft/vscode-remote-release#314]
- VSCode Version: 1.34.20
- Local OS Version: Windows 10
- Remote OS Version:  Ubuntu 18.04.2 LTS
- Remote Extension: WSL

Steps to Reproduce:

1. Open a project on WSL with source control
2. Make changes to any file
3. _Source control does not identify changes_
4. Restart vscode
5. vscode will **now** identify changes and will be able to stage / push to source control

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by niallel** [comment]
I saw the same thing when I had only 1GB of memory on my server. Also there were 2 node processes running at 40%.

When I increased to 2GB all the problems went away and git started showing the changes.

**Comment by vitormhenrique** [comment]
I haven’t tried having remote ssh, but with windows subsystem for linux I don’t have control over the size of the VM ram allocation (do I?)

**Comment by joaomoreno** [comment]
@vitormhenrique Do any extensions work when you're in that state?

**Comment by vitormhenrique** [comment]
Mostly, I can still push data from the GitHub, I can't commit of course because vscode thinks there is nothing changed to be able  to stage / commit.

If i do a "push" or"sync" it will figure it out that something changed and will allow to stage / commit.

Check the print screen, the comment is a new info, that the local git is aware of, so on the terminal "git diff" shows the correct changes, but vs code does not show anything under changes.


![2019-05-16 14_06_08-models py - lancium_box  WSL  - Visual Studio Code - Insiders](https://user-images.githubusercontent.com/3967383/57880432-555e4100-77e4-11e9-8575-db980af8b28f.png)

**Comment by joaomoreno** [comment]
Do file events work at all? If you create a file using the terminal, does it show up in the file explorer?

**Comment by vitormhenrique** [comment]
yes, they do, touch test_file.py create and show the file on the file explorer, however, same behavior for Source Control screen, it does not show up any changes over there.

**Comment by joaomoreno** [comment]
Can't repro this on WSL at all.

**Comment by bpasero** [comment]
@joaomoreno fyi (because I have seen the code recently), could this be related to the check you do in git land if the window is focused or not? I noticed (in the web) that I was hard coding the window focus to `false` and nothing was working. Just wondering if remote extension could suffer from the same issue.

**Comment by mcpower** [comment]
I can reproduce this on my machine. This problem seems to be due to symlinks in the repository path:

```
$ git init repo
Initialized empty Git repository in /home/mcpower/vscode-no-changes/repo/.git/
$ ln -s repo symlinked-repo
$ touch repo/file
$ code repo  # shows "file" as being new
$ code symlinked-repo  # does not show "file" as being new
```

As a workaround, you can run `code` in the non-symlinked path (using `realpath` or similar utilities).

Windows 1803, running on VS Code Stable 1.35.0. "Remote - WSL" is version 0.38.0, while "Remote Development" is version 0.15.0.

**Comment by ryansully** [comment]
This seems to be related to https://github.com/microsoft/vscode/issues/5970.

**Comment by joaomoreno** [comment]
@vitormhenrique:

1. Do you have symlinks at all?
2. Can you still repro this on the latest builds?

**Comment by DavidASolis** [comment]
I can reproduce this issue. I am opening the repo via a symlink to /mnt/c/...  As well as, I have several symlinks with relative paths in the repo itself.

**Comment by vitormhenrique** [comment]
Yes!

I do have syslinks!!

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/5970
