### ISSUE TITLE
"The specified task cannot be tracked."

### ISSUE THREAD

**Issue by bascott** [microsoft/vscode-remote-release#3146]
Issue Type: <b>Bug</b>

1. Attempt to a debug a .Net Core project over remote ssh with prelaunchTask "build".
2. Below error occurs, build task starts and completes a few seconds later.
![image](https://user-images.githubusercontent.com/2665771/84043168-93884e80-a96b-11ea-8853-4085094552b3.png)

Current workaround: Delete prelaunchTask, build manually and then debug.

Extension version: 0.51.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Windows_NT x64 10.0.18363
Remote OS version: Windows_NT x64 10.0.18363

**Comment by roblourens** [comment]
If still an issue, please open an issue on the .net extension repo
