### ISSUE TITLE
"No source control providers registered"

### ISSUE THREAD

**Issue by ridhwaans** [microsoft/vscode-remote-release#3147]
The Source Control sidebar section is empty, with a message "No source control providers registered", even though there is an existing Git installation inside WSL Ubuntu. In WSL, running `which git` or `where git` shows that git is installed `/usr/bin/git`, but the Source Control is not recognized in the Remote VSCode window. There should be some information on the taskbar and sidebar for Git management.

- VSCode Version: latest
- Local OS Version: Windows 10 version 2004
- Remote OS Version: Ubuntu 20.04 focal(on the Windows Subsystem for Linux) x86_64 Linux 4.19.104-microsoft-standard
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Install latest WSL and Ubuntu instance (https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2)
2. Install Remote - WSL extension in VSCode
3. From the bottom left taskbar corner, click Remote - WSL: New Window
4. Go to Source Control in the sidebar (by default Ctrl+Shift G G)
5. "No source control providers registered"

Does this issue occur when you try this locally?: No issue because Git is disabled locally
Does this issue occur when you try this locally and all extensions are disabled?: no

**Comment by bamurtaugh** [comment]
Hey @ridhwaans, are you still experiencing this issue?

**Comment by ridhwaans** [comment]
yes it does in a WSL Ubuntu window

**Comment by joaomoreno** [comment]
What does `Git: Show Git Output` show?

**Comment by ridhwaans** [comment]
it says `no matching commands` after pressing f1. this is in a WSL remote window. `Gitlens` is installed in it and it works  
Outside in a local VScode window, `Remote - WSL` is installed, `Git 1.0.0` is disabled

**Comment by joaomoreno** [comment]
If you run `Extensions: Show Disabled Extensions`, is git disabled?

**Comment by ridhwaans** [comment]
yes, git is disabled. it says it is "disabled globally by the user". sometimes the git extension isnt visible in the installed, recommended & disabled panes  
I enabled it in a WSL window and it works as expected.

**Comment by joaomoreno** [comment]
@sandy081 Another case of git appearing disabled. 🤔
