### ISSUE TITLE
Remote containers not working on Mac OS

### ISSUE THREAD

**Issue by vrmerlin** [microsoft/vscode-remote-release#3149]
- VSCode Version: 1.45.1
- Local OS Version: macOS Mojave 10.14.6
- Remote Extension/Connection Type: Docker
- Docker Desktop for macOS: 2.3.0.3

Steps to Reproduce:
1. Installed Docker Desktop, and insured i can successfully run containers from the command line and VSC, without problem.
2. Installed Remote Containers 0.117.1
3. Selected "Remote-Containers: Try a Sample..."
4. Selected the Java sample

When I do this, the workspace resets, and pops up a dialog box that says "The 'docker' command was not found. Make sure Docker is installed". Also in the terminal, I see the following:

> [0 ms] Start: Resolving remote
> [3 ms] Start: Check Docker is running
> [3 ms] Start: Run: docker info
> [9 ms] Docker returned an error code ENOENT, message: spawn docker ENOENT

I'm running all the "latest and greatest", and Docker is working just fine from the command line. Also, the Docker extension in VSC is working fine too (I can start/stop docker-compose.yml, inspect containers and container logs, etc, from within VSC).

Any ideas what might wrong with my configuration?

**Comment by chrmarti** [comment]
Try starting VS Code from the terminal, maybe the updated PATH has not been picked up by the dock?

**Comment by vrmerlin** [comment]
No, i tried that and the same problem occurred.

**Comment by chrmarti** [comment]
What do you get for `which -a docker` in the terminal?

**Comment by vrmerlin** [comment]
When i do ```which -a docker``` I get back ```/usr/local/bin/docker```

**Comment by chrmarti** [comment]
Try setting `/usr/local/bin/docker` as the value for the Docker CLI path setting. Does that help?
![image](https://user-images.githubusercontent.com/9205389/85128557-d7176e00-b231-11ea-8d34-56b60396ba92.png)

**Comment by sat0yu** [comment]
I've run into the same error and resolved with @chrmarti 's suggestion https://github.com/microsoft/vscode-remote-release/issues/3149#issuecomment-646588532

**Comment by chrmarti** [comment]
Closing this as we haven't heard back from OP.
