### ISSUE TITLE
Open remote workspace from local machine

### ISSUE THREAD

**Issue by tmr4** [microsoft/vscode-remote-release#3151]
This may be related to feature requests #511 and #777. 

I'd like to open a remote session by clicking on a workspace file on my local machine.  You can currently save a remote workspace to your local machine but when you try to open it after closing the current session, remote folders are noted with a "Unable to resolve workspace folder" warning and a remote session is not established.  I've tried various edits to the workspace file to specify a uri for the remote connection.  The first line below is most similar to that when saving a remote workspace to a local machine where the remote host is a long string which I assume is the ID for the current remote connection (below I've replace this string with a host named "remote" from my ssh config file)

"uri": "vscode-remote://ssh-remote+remote/home"

I also tried

"uri": "ssh-remote://remote/home"
"uri": "remote://home"

and many other variations but none work.

Of course a workaround is fairly straight forward: open the remote and then open the workspace on the remote machine.  But a single step would be great.

**Comment by PavelSosin-320** [comment]
The big mess happens in the transition from Hyper-V based Docker Desktop because old "Shared drives"  becomes /mnt/Letter/ fs mount points according to /etc/wslconf configuration and old folder list in Workspace configuration became incorrect. And this is not an "experimental" feature because on my new laptop with Windows Home is the only option. I can mount any remote FS to my WSL distro create symlink but it is possible only with POSIX folders!

**Comment by roblourens** [comment]
Once you have opened the remote workspace, you can find it again in "Recently Opened". This is what I do and recommend.

**Comment by tmr4** [comment]
Thanks for pointing that out.  Still, it's not the same.  Having to scroll/search through a long list of projects is not the same as clicking on the workspace file in the project's local directory.

I understand though that you have a lot of features to consider but I'm not sure why this wasn't allowed to go through the 60 day upvote period.

**Comment by roblourens** [comment]
With the way workspaces are implemented, it's not as straightforward to implement it this way as it sounds, so it's not really practical for us to consider, sorry.
