### ISSUE TITLE
Extensions in state "installing" forever if installing in WSL: Ubuntu-18.04

### ISSUE THREAD

**Issue by Linkadoo** [microsoft/vscode-remote-release#3152]
Issue Type: <b>Bug</b>

Expected behavior: Possible to install an extension in WSL.
Actual behavior: Only possible to install extensions locally. If I click the "Install in WSL: Ubuntu-18.04" for an extension in the Extensions tab, the extension changes to the state "Installing" and is stuck there until VS Code is closed. When reopening the extension is still not installed. I have also tried installing manually via .vsix-file with the same result, installable locally but not in WSL.

Steps to reproduce:
1. Open VS Code via Remote-WSL.
2. Try to install an extension in WSL, such as ms-dotnettools.csharp (which I can successfully install locally).

Reproducible all the time and for all extensions I have tried.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (20.24GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/home/linus --remote=wsl+Ubuntu-18.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|31.82GB (20.24GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Doxygen|bbe|1.0.0
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
vim|vsc|1.14.5

</details>

**Comment by sandy081** [comment]
Please share the logs from the following location
    - View -> Open View… -> Log (Remote Server)

**Comment by Linkadoo** [comment]
Output from Log (Remote Server) is presented below. Note that there is no response in the output when I click on a "Install in WSL: Ubuntu-18.04", only the button that is shifting state to "Installing".

Output:
*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


[2020-06-09 15:15:48.196] [remoteagent] [info] Extension host agent started.
[2020-06-09 15:15:48.488] [remoteagent] [info] [::ffff:127.0.0.1][4b2e0618][ManagementConnection] New connection established.
[2020-06-09 15:15:48.490] [remoteagent] [info] [::ffff:127.0.0.1][4e6f602c][ExtensionHostConnection] New connection established.
[2020-06-09 15:15:49.583] [remoteagent] [info] [::ffff:127.0.0.1][4e6f602c][ExtensionHostConnection] <321> Launched Extension Host Process.

**Comment by sandy081** [comment]
Can you please enable log level to trace and see if you see more output?

Can you also please share Log (Window) ?

**Comment by Linkadoo** [comment]
I'm attaching the logs from Log (Window) and again Log (Remote Server) with log level set to trace. 

At around 10:39:47 I clicked on Install on WSL: Ubuntu-18.04 for extension ms-python.python. I marked it in the remoteagent log, but not the renderer1 log. I've also altered the log slightly due to private content, but that should not impact anything relevant for this.

[renderer1_installing_mspython_trace_level.log](https://github.com/microsoft/vscode-remote-release/files/4757614/renderer1_installing_mspython_trace_level.log)
[remoteagent_installing_mspython_trace_level.log](https://github.com/microsoft/vscode-remote-release/files/4757615/remoteagent_installing_mspython_trace_level.log)

**Comment by sandy081** [comment]
It seems on WSL it got stuck at request - `https://az764295.vo.msecnd.net/extensions/marketplace.json`

Can you please check from your WSL if you are able to make this request successfully? May be you have connectivity issues from your WSL?

**Comment by Linkadoo** [comment]
Sorry for late answer. Yes, you seem to be correct. When using curl or wget I get stuck in an infinite wait. Pasting the curl dialogue below. I'll investigate the issue and reply in this thread. Thanks!
![image](https://user-images.githubusercontent.com/15641220/84758138-5a805780-afc5-11ea-977e-37222a4a55a5.png)

**Comment by sandy081** [comment]
Sure.

**Comment by daniel-cohen** [comment]
I had the same problem as you: Trying to install any extension under wsl 2 was just stuck.
Based on what I've seen in this ticket and here: https://github.com/microsoft/vscode-remote-release/issues/1358
I've tried to run:
`curl -XGET https://az764295.vo.msecnd.net/extensions/marketplace.json -v`
which just errored out with:
`Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 117.18.232.200:443...
* TCP_NODELAY set
* Connected to az764295.vo.msecnd.net (117.18.232.200) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to az764295.vo.msecnd.net:443
`

But, I wasn't behind any proxy! I was however, connected through VPN and as soon as I disconnected it I could make the curl request and then also install the extensions. 
I hope this help

**Comment by bamurtaugh** [comment]
Hey @Linkadoo, are you still experiencing this issue/were you able to investigate further? 

@daniel-cohen Thanks for the info. Am I interpreting your comment correctly to mean that the issue lies with WSL/the VPN connection rather than the Remote-WSL extension?
