### ISSUE TITLE
Cannnot reconnect to WSL after Windows resumes

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-remote-release#3158]
```
Version: 1.46.0-insider (user setup)
Commit: 9f89da69154ac6c99dfa7c82986e2df95b7bbe0b
Date: 2020-06-08T22:10:54.220Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```

I think this is new behavior? If I have an instance of VS Code open on a Ubuntu instance and the computer goes to sleep, when i log back in again I get a reconnect prompt:

![image](https://user-images.githubusercontent.com/1487073/84164234-23d79980-aa27-11ea-9274-db6a3ce42bd4.png)

To repro
- ubuntu image on wsl
- open a folder on linux
- let the computer go to sleep
- wake, log back into comuter
- result: Reconnect Dialog

**Comment by andrp92** [comment]
This happens a lot to me.

**Comment by aeschli** [comment]
@chrisdias Can you run `powercfg /a` and let me know what sleep states are available on your machine?

**Comment by chrisdias** [comment]
This no longer happens for me all the time, only occasionally, but I can't identify exactly when.

```
d:\src>powercfg /a
The following sleep states are available on this system:
    Standby (S0 Low Power Idle) Network Connected
    Hibernate
    Fast Startup

The following sleep states are not available on this system:
    Standby (S1)
        The system firmware does not support this standby state.
        This standby state is disabled when S0 low power idle is supported.

    Standby (S2)
        The system firmware does not support this standby state.
        This standby state is disabled when S0 low power idle is supported.

    Standby (S3)
        The system firmware does not support this standby state.
        This standby state is disabled when S0 low power idle is supported.

    Hybrid Sleep
        Standby (S3) is not available.
        The hypervisor does not support this standby state.
```

**Comment by tristanbrown** [comment]
This has been happening to me too, starting sometime in 2020. When Windows resumes, I get the "Cannot reconnect. Please reload window" message. I used to be able to just click the "reload window" button, and everything would be fine after that. But starting about a month ago, after the window reloads, a message pops up giving a 5 second countdown before it tries to reconnect again. If I let it try to reconnect in that way, it always fails and gives the "Cannot reconnect. Please reload window" message _again_. The only way to break the cycle is to manually click the "reload window" button before the 5 second countdown expires. 

This has become incredibly annoying.

**Comment by ablankenship10** [comment]
I have this issue a lot after a windows reinstall that wasn't happening my first time using it. Before I had tweaked WSL with a few modifications to how the network was connected to host and a different systemd script I think which may have helped, but those were hacks at the time and now there I think was more official WSL support for those things that I didn't use random git users scripts to make those work.

Anyway, I don't only get this popup when it wont reconnect. Sometimes it just shows me a notification in the bottom right that it couldn't open my file in the remote. Using the bottom left button on the toolbar that says (WSL: Ubuntu) fails to reconnect as well. It seems as though this attempt to reconnect is failing to do the same flow as the initial connect for some reason.

**Comment by rekire** [comment]
I have the same problem, however I think this started when I changed my IP range of my home network. This might trigger this issue.

**Comment by aeschli** [comment]
Thanks @aurisnoctis. SSH and WSL are quite different regarding the way reconnection works. 
This issue is about WSL. A while back we came up with a new connection method that fixed the reconnection issues that we suffered for a long time.

Therefore I'm closing this issue as fixed.

**Comment by aurisnoctis** [comment]
OK, is the "Reconnect. Please reload the window"-Issue also fixed for users connecting to a Linux machine via ssh? All issues about that seem to be closed but it's not solved (for me at least). Thank you for pointing me somewhere re my description above - either documentation or related issues are welcome. 🙏

**Comment by aeschli** [comment]
@aurisnoctis If there's no open issue about reconnect in SSH, please file a new issue that describes your setup and your steps.
