### ISSUE TITLE
not find the directory to run my script

### ISSUE THREAD

**Issue by Raul-Flores** [microsoft/vscode-remote-release#3159]
Issue Type: <b>Bug</b>

:~$ /usr/bin/python3 c:/Users/rflores/Desktop/test/test.py
/usr/bin/python3: can't open file 'c:/Users/rflores/Desktop/test/test.py': [Errno 2] No such file or directory

Extension version: 0.44.2
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.79GB (36.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|36%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|47.79GB (36.68GB free)|
|VM|36%|
</details>

**Comment by rzhao271** [comment]
@Raul-Flores I think because you're on remote, 

1. Check under /mnt/ to see if the C: drive got mapped to somewhere like /mnt/c/, rather than call c:/... directly
2. If that still doesn't work, try upgrading to the latest version of VS Code. 

Meanwhile, I'll close this issue for housekeeping. 
Feel free to reply if the steps above did not work for you.
