### ISSUE TITLE
Remote SSH: workbench.colorCustomizations partially works

### ISSUE THREAD

**Issue by dobosgy** [microsoft/vscode-remote-release#3164]
Issue Type: <b>Bug</b>

On a remote workspace in the .vscode/settings.json there are custom workbench colors definied:
```
"workbench.colorCustomizations": {
        "activityBar.background": "#cccccc",
        "activityBar.foreground": "#000000",
	"statusBar.background": "#cccccc",
	"statusBar.foreground": "#000000"
 }
```
Opening the remote workspace, the two `activityBar` colors don't work, however the `statusBar` colors does.

If something changed in `workbench.colorCustomizations` section and saved, the defined colors appear.
It is tried on two machines.

This worked before 1.46 version.

Extension version: 0.51.0
VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:04.923Z)
OS version: Linux x64 5.4.0-37-generic
Remote OS version: Linux x64 4.4.0-174-generic
Remote OS version: Linux x64 4.4.0-174-generic

**Comment by roblourens** [comment]
Works for me, please let me know if this is still an issue
