### ISSUE TITLE
Go 0.14.3 fails starting gopls running remote ssg

### ISSUE THREAD

**Issue by jimgrier** [microsoft/vscode-remote-release#3167]
Issue Type: <b>Bug</b>

I am running Remote SSH to edit at my company's site. Beginning with Go 0.14 extension, gopls would not work. I was able to work around by forcing install of
Go 0.13.1, but with the latest Code release I can no longer downgrade from Go 0.14.3. 
This severely impairs utility.

Extension version: 0.51.0
VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.3.0
Remote OS version: Linux x64 4.9.0-9-amd64
Remote OS version: Linux x64 4.9.0-9-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (4.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: scs|
|OS|Linux x64 4.9.0-9-amd64|
|CPUs|Intel Xeon E312xx (Sandy Bridge) (2 x 2699)|
|Memory (System)|7.80GB (6.26GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: scs|
|OS|Linux x64 4.9.0-9-amd64|
|CPUs|Intel Xeon E312xx (Sandy Bridge) (2 x 2699)|
|Memory (System)|7.80GB (6.26GB free)|
|VM|0%|
</details>

**Comment by Chuxel** [comment]
Thanks for raising the issue - Please log an issue in the Go extension repository here: https://github.com/golang/vscode-go/issues for someone to take a look. (Unforuntatley I cannot transfer it there.)  Thanks!
