### ISSUE TITLE
Remote-ssh issue

### ISSUE THREAD

**Issue by George-Qi** [microsoft/vscode-remote-release#3169]
Issue Type: <b>Bug</b>

I can connect my CentOS virtual machine through powershell using both root and normal-user, But today, I can connecting VM through Root user instead of normal user, I don't know why.

Extension version: 0.51.0
VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 3.10.0-1127.8.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (10.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|SSH: CentOS-root|
|OS|Linux x64 3.10.0-1127.8.2.el7.x86_64|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (1 x 2808)|
|Memory (System)|0.95GB (0.06GB free)|
|VM|100%|
</details>

**Comment by rzhao271** [comment]
Closing this issue for housekeeping. @George-Qi feel free to reply if this issue still occurs for you on the latest version of VS Code (preferably Insiders edition).
