### ISSUE TITLE
Building custom devcontainer causes DNS corruption?

### ISSUE THREAD

**Issue by illeatmyhat** [microsoft/vscode-remote-release#3172]
Environment Information:
```
Version: 1.47.0-insider
Commit: 6af2987903c22bf9b19762d589bc46d4be636dc4
Date: 2020-06-11T15:49:50.228Z (13 hrs ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0 (OSX Catalina)
```
- Name of Dev Container Definition with Issue: Custom

I attempted to [create my own devcontainer image featuring TypeScript, Node 14, and Python 3.8](https://gist.github.com/illeatmyhat/a58d425b08cfd89a77405dc4ca6a3526).
There is a spurious issue where I build this Dockerfile and the DNS for either `raw.githubusercontent.com` or `deb.debian.org` becomes corrupt both on the host and in Docker, causing a `couldn't resolve host` issue for that domain.

Resolving the DNS corruption issue is a matter of running `sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder`, then performing a Purge/Clean Data through Docker Desktop's Troubleshoot UI. Sometimes a factory reset works better.

I eventually [condensed that devcontainer image](https://gist.github.com/illeatmyhat/3af3386465e79284f7ecf5497aab8415) by removing redundant code, and inlining the contents of `common-debian.sh` to reduce the number of downloads from GitHub. This did not change the spurious DNS corruption issue.

Both Dockerfiles often fail to build at various stages due to common network connection issues to Debian, pip repositories. After failing a sufficient number of times, the DNS corruption sets in.
```bash
> docker run busybox nslookup https://raw.githubusercontent.com/python/typing/master/.gitignore 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8:53

** server can't find https://raw.githubusercontent.com/python/typing/master/.gitignore: NXDOMAIN

*** Can't find https://raw.githubusercontent.com/python/typing/master/.gitignore: No answer
```
I have built the image by directly using the terminal, and in VS Code using the `Remote-Containers: Rebuild Container` command.
I can confirm that the issue occurs in both scenarios, so the issue likely lies in the image, but I don't see any reason for the DNS to become corrupt.

Tangent: creating a devcontainer image is far too much work.

**Comment by Chuxel** [comment]
Interesting - it's possible you may be hitting an issue with [time drift](https://github.com/docker/for-mac/issues/4347) that I've seen cause connections to the Debian package repo to fail. It's a Docker Desktop problem where the host and container times get out of sync. It usually happens if the machine is put to sleep and awoken and restarting Docker Desktop fixes the problem.  I haven't seen the DNS issue you're referring to otherwise - so that's interesting.  @chrmarti Any ideas here?

> Tangent: creating a devcontainer image is far too much work.

Happy to take any feedback on what makes you feel this way and/or what we could do to help.

**Comment by chrmarti** [comment]
@illeatmyhat Note that `docker busybox` command you provide uses the URL instead of just the hostname. Using the hostname there appears to be an issue with busybox's uclibc version:
```
$ docker run --rm busybox:uclibc nslookup raw.githubusercontent.com 8.8.8.8

Unable to find image 'busybox:uclibc' locally
uclibc: Pulling from library/busybox
Digest: sha256:cd421f41ebaab52ae1ac91a8391ddbd094595264c6e689954b79b3d24ea52f88
Status: Downloaded newer image for busybox:uclibc
Server:		8.8.8.8
Address:	8.8.8.8:53

Non-authoritative answer:
raw.githubusercontent.com	canonical name = github.map.fastly.net

*** Can't find raw.githubusercontent.com: No answer
```

Musl and glibc versions appear to work correctly:
```
$ docker run --rm busybox:musl nslookup raw.githubusercontent.com 8.8.8.8

Server:		8.8.8.8
Address:	8.8.8.8:53

Non-authoritative answer:
raw.githubusercontent.com	canonical name = github.map.fastly.net

Non-authoritative answer:
raw.githubusercontent.com	canonical name = github.map.fastly.net
Name:	github.map.fastly.net
Address: 151.101.0.133
Name:	github.map.fastly.net
Address: 151.101.64.133
Name:	github.map.fastly.net
Address: 151.101.128.133
Name:	github.map.fastly.net
Address: 151.101.192.133
```

**Comment by chrmarti** [comment]
@illeatmyhat Is this still an issue?

**Comment by illeatmyhat** [comment]
As far as I haven't been using vscode at all lately, no.

**Comment by chrmarti** [comment]
Closing for now, let us know when this comes up again. Thanks.
