### ISSUE TITLE
Hight load cpu on server over 100%

### ISSUE THREAD

**Issue by S1ROZHA** [microsoft/vscode-remote-release#3173]
Issue Type: <b>Bug</b>

Hight load cpu on server over 100%
When I connect through a remote ssh
The server boots at 100 +% and works very slowly, but as soon as I close it everything works stably
![image](https://user-images.githubusercontent.com/20708709/84534555-cecfa800-acf2-11ea-8693-7ece2583aa65.png)
it is also seen that the Initializing JS / TS Language Features loads endlessly
![image](https://user-images.githubusercontent.com/20708709/84534723-20783280-acf3-11ea-89d9-84826e9148be.png)

Extension version: 0.51.0
VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.9.0-9-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: s1rozha|
|OS|Linux x64 4.9.0-9-amd64|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (1 x 2199)|
|Memory (System)|0.48GB (0.01GB free)|
|VM|0%|
</details>

**Comment by rzhao271** [comment]
@S1ROZHA does this issue still occur for you on the latest version of VS Code? If so, what about with extensions disabled?
