### ISSUE TITLE
File Rename participant takes too long

### ISSUE THREAD

**Issue by munael** [microsoft/vscode-remote-release#3176]
- VSCode Version: 1.46.0-Insiders
- Local OS Version: Windows 10 (1909)
- Remote OS Version: N/A
- Remote Extension/Connection Type: N/A

Steps to Reproduce:

1. Install the preview of SSH extension
2. Open a _local_ repo with some files
3. Rename a file through the explorer view
4. Rename can take 2-3 seconds

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
Do you know whether you have an extension that's doing some work when the file is renamed?

**Comment by roblourens** [comment]
What does this have to do with the SSH extension? It's not active if you have only opened a local repo.

Do you have an extension that's doing some work when a file is renamed?
