### ISSUE TITLE
Cannot Exit Remote Login

### ISSUE THREAD

**Issue by oli1230** [microsoft/vscode-remote-release#3178]
Issue Type: <b>Bug</b>

Set up remote ssh login
Use it a bunch and its fine
Open VSCode one day and it wants me to log into ssh
Hit "esc" to cancel: closes entire VSCode program
Open VSCode again
Wants me to log in again, so I do
Then i type the command to exit the ssh session in the terminal - and it does
Try to install an extension and only option is "install on ssh"
Also the top of the screen still indicates I am connected to remote server - or at least VSCode thinks I am
Uninstall and Reinstall VSCode - still tries to get me to log into that same ssh server

Extension version: 0.51.0
VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.18.0-147.8.1.el8_1.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.88GB (9.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: rlogin.cs.vt.edu|
|OS|Linux x64 4.18.0-147.8.1.el8_1.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz (64 x 3159)|
|Memory (System)|376.14GB (373.10GB free)|
|VM|0%|
</details>

**Comment by rzhao271** [comment]
There should be a 'Close Remote Connection' command @oli1230 
Closing this issue for now as part of housekeeping. Feel free to reply if this issue still occurs after updating to the latest VS Code and trying that.
