### ISSUE TITLE
Option to change location of .vscode-server(-insiders) folder

### ISSUE THREAD

**Issue by Michaelhobo** [microsoft/vscode-remote-release#3179]
I believe my entire devcontainer.json file's changes aren't being picked up, 

- VSCode Version:
Version: 1.47.0-insider (user setup)
Commit: 7e4cc2c435927e5a2845897961a2af10ee7f784d
Date: 2020-06-12T06:03:53.183Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
- Local OS Version: Windows 64-bit Pro w/ WSL2 Pengwin as host
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:
My environment: git repo inside WSL2, and I build the devcontainer from an existing Dockerfile.

I mount my source into the devcontainer here: 
"workspaceMount": "source=${localWorkspaceFolder},target=/home/user,type=bind",
"workspaceFolder": "/home/user",
I saved my environment as a workspace, which I store somewhere on my windows host.
1.  Open workspace (double click on my workspace file in windows host). This puts me inside my docker container.
2. Modify devcontainer.json. e.g. change settings.terminal.integrated.cwd from "/home/user" to "/home"
3. Command Pallette > Remote-Containers: Rebuild Container. Sometimes, a popup prompts me to rebuild my container because my devcontainer.json changed. Rebuilding that way also reproduces my problem.
4. After restart, open a new terminal. I expect to be dropped inside /home, but I'm dropped into /home/user instead.

### Maybe the wrong file is being read?

In the Remote Explorer tab, under my container's attributes, there's the Configuration field. When I double-click it, it goes shows my devcontainer file, at \\wsl$\WLinux\home\michaelhobo\repos\ee_0\.devcontainer\devcontainer.json

But, when I right-click > Open Container Configuration File, it goes to an empty file at \home\michaelhobo\repos\ee_0\.devcontainer\devcontainer.json

Could this extension be reading from the wrong file somewhere on reload?

### Multiple rebuilds

I had a few times where a popup prompted me to rebuild because my devcontainer.json changed. I accepted the rebuild prompt, and after the rebuild, the prompt happens again... just to further illustrate the problem

### Trying it a few different ways

I also tried doing this from WSL - I opened my source folder in WSL instead, then I reopened that window in the remote container. Same problem.

I also tried removing the container by going to Remote Explorer tab on the left pane > Containers dropdown > right click and remove the dev container.

**Comment by chrmarti** [comment]
Make sure you are using `"settings"` and nest the settings in that:
```json
   "settings": {
      "terminal.integrated.cwd": "..."
   },
```

**Comment by Michaelhobo** [comment]
Yup, I am doing that:

`{
	"name": "Buildenv",
	"context": "..",
	"dockerFile": "../Dockerfile",
	"settings": {
		"terminal.integrated.shell.linux": "/bin/bash",
		"terminal.integrated.shell.windows": "/bin/bash",
		"terminal.integrated.cwd": "/home/user",
	},
	"extensions": [
               ...
	],
	"workspaceMount": "source=${localWorkspaceFolder},target=/home/user,type=bind",
	"workspaceFolder": "/home/user",
}`

**Comment by chrmarti** [comment]
Your folder's `.vscode/settings.json` can override the container setting. Please check that.

Also check if the setting was correctly copied to the container (aka machine) settings:
![image](https://user-images.githubusercontent.com/9205389/84769185-b94dcd00-afd5-11ea-962e-14ed7f64b84d.png)

**Comment by Michaelhobo** [comment]
Aha, It seems like the .vscode-server-insiders/data/Machine/settings.json wasn't updated when I changed devcontainer.json and rebuilt. it seems like either these settings shouldn't be in settings.json, or they should get updated with the devcontainer.json's contents.

**Comment by chrmarti** [comment]
Only realized: You mount `/home/user` and there is a marker file `.vscode-server-insiders/data/Machine/.writeMachineSettingsMarker` that will prevent the settings.json from being written again. When you delete that marker, the settings.json next to it should be updated.

**Comment by Michaelhobo** [comment]
Is there a suggested way to allow changes to the devcontainer.json? It seems pretty counter-intuitive to delete a dotfile in order to prompt a devcontainer.json settings change, when the UI prompts for changes in devcontainer.json to be picked up.

**Comment by Michaelhobo** [comment]
Removing the .writeMachineSettingsMarker file does mitigate the issue though.

**Comment by chrmarti** [comment]
This is a limitation that occurs when you mount the home folder because then 'rebuilding' the container does not delete the `~/.vscode-server-insiders` folder.

**Comment by Michaelhobo** [comment]
Is there a way to change where .vscode-server-insiders gets mounted? My source contains a few things which go into the homedir

**Comment by Michaelhobo** [comment]
Well, I guess I only really need to put the .bashrc in the homedir (and maybe a few other dotfiles). I can work around this now that I know what's happening, but I'd still prefer to move the .vscode-server-insiders dir (or flush it when mounting it).

I do wish the documentation were clearer about this. I couldn't find ANYTHING about this, but I realized that it's buried in here:
https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild
