### ISSUE TITLE
code points to different executable after running "install 'code' command in PATH"

### ISSUE THREAD

**Issue by AnakinMac** [microsoft/vscode-remote-release#3180]
- VSCode Version:  1.46.0
- Local OS Version: macOS 10.15.6
- Remote OS Version: macOS 10.15.3
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Make sure on remote machine code is not installed in PATH.
2. Run "which code" in ssh terminal, output is /Users/username/.vscode-server/bin/.../bin/code
3. Run "install 'code' command in PATH" in remote VSCode.
4 Run "which code" again in ssh terminal, now code points to /usr/local/bin/code

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
I think this should be disabled in a remote window

**Comment by joaomoreno** [comment]
Yeah for sure.
