### ISSUE TITLE
BUG: SSH plugin hangs on Checking server status on port 44249 with wget.

### ISSUE THREAD

**Issue by Spacelord09** [microsoft/vscode-remote-release#3181]
- VSCode Version: 1.46
- OS Version: Debian 10.4 / Windows 10

Steps to Reproduce:

1. Install nftables and drop all unwanted ports(I've only allowed SSH and some webserver stuff.)
2. Install the official ssh extension in your local vscode.
3. Connect to your host. (On the first connect that should work.)
4. If I disconnect the established session and do'nt kill the server process manually I can't reconnect. It hangs at ```Checking server status on port 44249 with wget```(Port 44249 is a placeholder)

If I manually kill the server process or reboot the remote machine(server) it's working again.

Is this a bug? I've tried the nightly version of the ssh plugin. Same behavior
 

Does this issue occur when all extensions are disabled?: Yes/No
N/A

**Comment by roblourens** [comment]
We need an open port for the server, it sounds like maybe you have blocked that port with nftables? Also it's not clear exactly what you are doing when you "disconnect the established session and don't kill the server process".

**Comment by Spacelord09** [comment]
Hello @roblourens thank you for your answer.

Yes I've blocked all ports I don't use. only the ssh and webserver ports are enabled.
As far as I could determine, there is always a random port used which means I can't open the port.
Can I configure the port statically to allow it in nftables?
Why is the port not forwardet through ssh? I think thats the best solution?

**Comment by roblourens** [comment]
It is forwarded through ssh, it is not expected to be externally accessible. Would that not be the issue here then?

**Comment by Spacelord09** [comment]
@roblourens It works when Im stopping nftables bevor connect? Are you sure that the port is forwarded in all cases?

**Comment by Spacelord09** [comment]
@roblourens I've found the solution!

I've forgotten to add a `iifname lo accept` to my nftables input chain ;D
