### ISSUE TITLE
Folder in remote containers with the same name

### ISSUE THREAD

**Issue by spolezhaev** [microsoft/vscode-remote-release#3182]
- VSCode Version: 1.45.1
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Open remote container on the remote host using 'docker.host' and open folder in it
2. Open remote container with the same name on another remote host
In the second remote container, the same folder as in the first container is trying to be opened without letting to choose it (when you open containers with different names, welcome screen with an option to open the folder is displayed). Also if you're trying to open containers once again, the folder from the last closed container is trying to be opened in both.

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
@Piteryo Is this when you 'Attach' to the container? (Not using a `devcontainer.json` I guess?)

**Comment by Piteryo** [comment]
> @Piteryo Is this when you 'Attach' to the container? (Not using a `devcontainer.json` I guess?)

Yep, I didn't use `devcontainer.json`

**Comment by chrmarti** [comment]
We remember the last folder used with the same image. We should check if that folder exists before trying to open it.

**Comment by dian-yu-luo** [comment]
I have a image name "myimage",I have create a container by "myimage",when I create another container by "myimage" and attach  
it in vscode ,It try to open the same folder,
it rember last folder by folder name ,but is It is normal that we create the same folder in different container ,why not remember the same folder by container id and folder name

**Comment by chrmarti** [comment]
@dian-yu-luo Not sure this helps in your particular case, but you can associate a configuration file with a container name using `F1` > `Remote-Containers: Open Named Container Configuration File` while attached to the container.

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/8328
