### ISSUE TITLE
Attach VScode in alpine3.12 with proxy behind

### ISSUE THREAD

**Issue by willy1920** [microsoft/vscode-remote-release#3183]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. run interactive image alpine3.12
2. attach vscode to that container

Does this issue occur when all extensions are disabled?: Yes/No

error (apk update && apk add libstdc++)

**Comment by chrmarti** [comment]
Try configuring the proxy in Docker's settings: https://docs.docker.com/network/proxy/

Does that make it work?
