### ISSUE TITLE
Remote-SSH gets very unstable after performing large file operations

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-remote-release#3184]
I have an Azure VM running on a Standard HDD os disk, any time I perform operations (delete, rename, etc) on larger files (hundreds of MB) from explorer, the entire connection seems to crash and I constantly get the reconnection dialog. 

I'm additionally put in a state where backup saves cannot complete, which means the "reload window" operation silently fails (it hangs on the save completing, but the ssh link seems totally broken so the save never goes through)

**Comment by JacksonKearl** [comment]
(note that `rm large_file` on a normal terminal connection is still very fast)

**Comment by roblourens** [comment]
Probably just have to put this under https://github.com/microsoft/vscode-remote-release/issues/1087 but cc @alexdima

**Comment by JacksonKearl** [comment]
Hm, the other one is about opening the file, which makes some sense to saturate the network connection as the data does need to be transferred. But to simply delete, move, or rename a file shouldn't saturate the network connection.

**Comment by alexdima** [comment]
@JacksonKearl Could you please double check if this still happens? Does it make a difference if the files are `.txt` or `.ts` ?

**Comment by JacksonKearl** [comment]
All good now :)
