### ISSUE TITLE
No GPG forwarding if using a remote container from within WSL2

### ISSUE THREAD

**Issue by mattford63** [microsoft/vscode-remote-release#3191]
Version: 1.47.0-insider (user setup)
Commit: 0288447572790f983c350905bd1fc5b754970a0a
Date: 2020-06-15T07:44:14.223Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

- Remote Extension/Connection Type: SSH/Docker/WSL2

No SSH or GPG forwarding if using a remote container from within WSL2.

Steps to Reproduce:

1. From within WSL2 navigate to a repo with a `.devcontainer`.  
2. Launch with `code .`
3. Switch to remote container.

It seems the .ssh and .gpg files aren't copied or sockets setup.

SSH on WSL using the Windows ssh-agent or to remote machines works as expected.

**Comment by RyanTheAllmighty** [comment]
Can also confirm I'm seeing this issue. Going from Windows directly to Remote Container works fine, but from WSL2 to the same container doesn't work.

**Comment by chrmarti** [comment]
Tracking SSH forwarding with WSL2 as #2925.

**Comment by chrmarti** [comment]
Fixed with https://github.com/microsoft/vscode-remote-release/issues/2925. Tested with the pinentry program in WSL configured to use the Gpg4win pinentry, `~/.gnupg/gpg-agent.conf`:
```
pinentry-program "/mnt/c/Program Files (x86)/Gpg4win/bin/pinentry.exe"
```
