### ISSUE TITLE
Unable to connect to Raspberry Pi Desktop (and potential other x86_64 systems)

### ISSUE THREAD

**Issue by BlackC0ffee** [microsoft/vscode-remote-release#3194]
Issue Type: <b>Bug</b>

This issue happens when trying to connect to connect remotely to Raspberry Pi Desktop.
- Install Raspberry Pi Desktop as VM or on a desktop/laptop.
- Connect with Visual studio code remotely to the machine running Raspberry Pi Desktop.
- This results in a `node: not found`-error
- Checking the Raspberry Pi Desktop shows that file exists under `/home/pi/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321`
- Running the file node result in a `-bash: ./node: No such file or directory`-error
- Running the command ldd against node results in `not a dynamic executable`
- The command `uname -m` outputs `x86_64`

## Workaround:
Install gcc-multilib:
```sudo apt-get install gcc-multilib```

## Potential fix:
Add some library checks to `server.sh`

Extension version: 0.51.0
VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.19.0-8-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (3.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: RpiDev|
|OS|Linux x64 4.19.0-8-amd64|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (1 x 3700)|
|Memory (System)|1.95GB (0.98GB free)|
|VM|100%|
</details>

**Comment by roblourens** [comment]
If this is still an issue, can you share the full log from the Remote-SSH output channel?
