### ISSUE TITLE
VSCode Server Node Process consuming heavy resources

### ISSUE THREAD

**Issue by Mshivam2409** [microsoft/vscode-remote-release#3195]
- VSCode Version:1.46.0
- Local OS Version: Windows 10 2004
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type:WSL

Steps to Reproduce:

1. Open any folder is WSL
2.The Node process of Vscode Remote Server starts up and starts consuming almost all of RAM and Cpu resources.Seems to be a memory leak. The attached Screenshot shows it.Node would go on consuming resources ending in a BSOD.
![Screenshot (68)](https://user-images.githubusercontent.com/53910337/84741791-332d8880-afcd-11ea-86bd-4e3e196d0249.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by escape0707** [comment]
I use ArchLinux WSL1 and this `node` process is continuously taking up about 18 per cent of my CPU and makes the CPU fan rotates loudly. Is there anything I can do?

**Comment by escape0707** [comment]
> 
> 
> I use ArchLinux WSL1 and this `node` process is continuously taking up about 18 per cent of my CPU and makes the CPU fan rotates loudly. Is there anything I can do?

I think this issue addressed it: https://github.com/microsoft/vscode/issues/97568#issuecomment-630822277

**Comment by bamurtaugh** [comment]
Thanks for the update @escape0707. With that resolution, going to close out this issue, but please feel free to let us know if you have any other questions or feedback.
