### ISSUE TITLE
F12 Go To Definition not working

### ISSUE THREAD

**Issue by soul4soul** [microsoft/vscode-remote-release#320]
- VSCode Version: 1.34.20-insider
- Local OS Version: Windows_NT x64 10.0.17763
- Remote OS Version: CentOS Linux release 7.4.1708 (Core) 3.10.0-693.21.1.el7.x86_64
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to remote machine with SSH and password, default port 22
2. Open remote folder (My folder contained a C library, driver, and application)
3. Click on a symbol/function/define
4. Press F12

Nothing happens.

I expect to be sent to the file and location of the definition of the selected symbol.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Didn't test

**Comment by egamma** [comment]
@soul4soul Did you install the C/C++ extension into the SSH box?

**Comment by soul4soul** [comment]
You're correct. Once I installed the extensions go to definition began working.
