### ISSUE TITLE
server.sh with Check failed: reservation_.SetPermissions 

### ISSUE THREAD

**Issue by billyrayxbox** [microsoft/vscode-remote-release#3201]
Running on my webhost's Linux server, server.sh failed with:

```
[halifax]$ ./server.sh
#
# Fatal error in , line 0
# Check failed: reservation_.SetPermissions(protect_start, protect_size, permission).
#
#
#
#FailureMessage Object: 0x3e1a02f4170./server.sh: line 12: 31517 Illegal instruction     (core dumped) "$ROOT/node" ${INSPECT:-} "$ROOT/out/vs/server/main.js" "$@"

```
Doing a search on this error led me to https://help.dreamhost.com/hc/en-us/articles/360029083351-Installing-a-custom-version-of-NVM-and-Node-js

running 

`setfattr -n user.pax.flags -v "mr" $(find $NVM_DIR -type f -iname "node" -o -iname "npm" -o -iname "npx")`

in the ~/.vscode-server/bin dir allowed server.sh to run ok on the next attempt (confirmed in terminal and by a successful connection with vscode).

**Comment by Stabledog** [comment]
Same problem here, same solution -- running setfattr allows Vscode to connect to my shared-server at dreamhost.com

**Comment by gavalenzuela** [comment]
i can't connect to my shared dreamhost server with vscode:
`setfattr -n user.pax.flags -v "mr" $(find $NVM_DIR -type f -iname "node" -o -iname "npm" -o -iname "npx")`
the server sends me an error:
`#
# Fatal error in , line 0
# Check failed: reservation_.SetPermissions(protect_start, protect_size, permission).
#
#
#
#FailureMessage Object: 0x3a22ff8b030./server.sh: line 12:  2657 Illegal instruction     (core dumped) "$ROOT/node" ${INSPECT:-} "$ROOT/out/vs/server/main.js" "$@"`
i don't understand what fails.

**Comment by roblourens** [comment]
Sorry for the slow response. If this is still an issue, do you understand what the issue on dreamhost is or what the setfattr command does?

**Comment by roblourens** [comment]
Since people keep finding this issue, we discussed a fix at https://github.com/microsoft/vscode-remote-release/issues/4780#issuecomment-823702080
