### ISSUE TITLE
VS Code Detects Timeouts When SSH Connection Is Still Alive

### ISSUE THREAD

**Issue by bkhant1** [microsoft/vscode-remote-release#3204]
Hi, 

Upon opening (or reloading) VS code with the remote extension, I always hit the SSH reconnection popup 2 or 3 times.
![image](https://user-images.githubusercontent.com/24943925/84902882-4b70d680-b0a5-11ea-9c33-62acb525da8a.png)

My connection to the host is not fast (around 100kbps). What seems to be happening is that at startup VS code client sends about 4Mb of data to the host, cluttering the connection. While that process is ongoing, my ping to the remote explodes (can go over 5 seconds). 

I guess this might be why the VS code client detects a timeout. That does cause VS code to open a new SSH connection. However, the old SSH connection is still alive and did NOT time out.

![image](https://user-images.githubusercontent.com/24943925/84903929-9ccd9580-b0a6-11ea-909d-e3903d5775b7.png)

Now this is not really a problem in itself, but it looks like the remote extension host doesn't support well all those reconnections. It takes ages to start, and randomly after all the uploading is done, my installed extensions are not activated. 

![image](https://user-images.githubusercontent.com/24943925/84907592-4adb3e80-b0ab-11ea-999e-e906162e3ba3.png)

Please let me know if you need any more information,
Thanks

**Comment by jiamings** [comment]
+1, I think I had this issue as well after applying the latest update of vscode.

**Comment by bkhant1** [comment]
Same actually, seems like it happens every time after a VS code update, then after a few days it goes back to normal.

**Comment by roblourens** [comment]
Closing under the general issue: https://github.com/microsoft/vscode-remote-release/issues/1257
