### ISSUE TITLE
WSL Remote Extension Failing on Build 20150

### ISSUE THREAD

**Issue by sirredbeard** [microsoft/vscode-remote-release#3207]
Summary:

![image](https://user-images.githubusercontent.com/33820650/84952788-90eecd00-b0c0-11ea-954f-8a9709cd0eac.png)

Extension installs and connects: https://gist.github.com/sirredbeard/99deef6ed6bec365707f390f15796d58

Then errors:

![image](https://user-images.githubusercontent.com/33820650/84952612-3b1a2500-b0c0-11ea-953e-6d4d9a27d4c6.png)

It seems to be trying to connect on 127.0.0.1:39761 and failing.

127.0.0.1:39761 does not resolve, but localhost:39761 does:

![image](https://user-images.githubusercontent.com/33820650/84952839-a5cb6080-b0c0-11ea-841b-cfa622558d62.png)

- VSCode Version: 
![image](https://user-images.githubusercontent.com/33820650/84952224-b0d1c100-b0bf-11ea-8dce-6e0f8eb20c4b.png)
- Local OS Version: Windows 10 Pro 20150
![image](https://user-images.githubusercontent.com/33820650/84952478-073eff80-b0c0-11ea-805a-0f35c0a17097.png)
- Remote OS Version: Ubuntu 20.04
![image](https://user-images.githubusercontent.com/33820650/84952549-22aa0a80-b0c0-11ea-9189-334aeca9cefe.png)

- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Install Ubuntu on WSL 2
2. Install Remote WSL extension in Code Insiders
3. Connect to Ubuntu using Remote WSL extension

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by bjornmonkey** [comment]
i also have this issue

**Comment by sirredbeard** [comment]
Dupe of #3212
