### ISSUE TITLE
Sort "Not Forwarded" ports

### ISSUE THREAD

**Issue by orena1** [microsoft/vscode-remote-release#3208]
It would be great if there was an option to sort the "Not Forwarded" ports. For example,  I need to forward 6006, 6007, 6008 etc.. and as the "Not Forwarded" ports are not sorted by port number I need to search for them.

![image](https://user-images.githubusercontent.com/8983713/84956190-56f1eb00-b101-11ea-8ddc-79e28cb6b941.png)

related to this: #2219 but as far as I understand this is only for the "Forwarded"..

Thanks

**Comment by alexr00** [comment]
We no longer show "Not Forwarded" ports.
