### ISSUE TITLE
Default behavior for open new connection should be the same

### ISSUE THREAD

**Issue by AndersonZhangyq** [microsoft/vscode-remote-release#3210]
Currently, in remote explorer, when you select SSH Targets and click the open folder icon, the default behavior is to open in the **new** window. When you select WSL Targets and click the open folder icon, the default action behavior is to open in the **current** window. 

It's kind of annoying when you need to connect remote and use WSL in the same time. It would be great to make the default behavior the same.

Version: 1.46.0 (user setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
Remote-SSH: v0.51.0
Remote-WSL: v0.44.3

**Comment by roblourens** [comment]
I like new folder better for ssh because the user might have to re-auth so it's annoying to lose your current window.
