### ISSUE TITLE
Workaround: With Windows OpenSSH, keys added to ssh-agent do not work connecting to later Ubuntu servers

### ISSUE THREAD

**Issue by benliddicott** [microsoft/vscode-remote-release#3215]
- VSCode Version:
- Local OS Version:
- Remote OS Version:
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1. Use windows bundled OpenSSH client
2. Add keys to ssh-agent using ssh-add
3. Attempt to connect to remote server in VS Code
4. You will be asked for your passphrase anyway.
   * Message appears in Remote - SSH log: warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512) 

I'm aware this appears to be a bug in Windows OpenSSH ssh-agent, but I'm posting this here as a workaround in case it helps others.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Workaround using PuTTY plink**

* Convert your key to PuTTY format using the PuTTYGen tool.
* Configure an identical session in PuTTY.
* Have Pageant running and the key loaded
* Connect to it once and approve the server identity
* Create a batch file as shown below, and save it as "c:\workdir\fakessh.cmd" (or another convenient location).
* Configure vs code to use your wrapper command

**VS Code settings**
```
    "remote.SSH.path": "C:\\workdir\\fakessh.cmd",

```

**Batch File contents**
```cmd
@echo off
set SCRIPTDIR=%~dp0
if ARG%1==ARG-V goto :VERSION
REM Assuming plink is in your path. Otherwise specify full path here.
plink %*

goto :EOF
:VERSION
echo "OpenSSH wrapper for plink"
:EOF
```

So. if you have a .ssh/config entry like this:

```
Host foo-server1
    HostName 192.35.46.57
    User foouser
    ForwardAgent yes
    ForwardX11 yes
    TCPKeepAlive yes
```
Then you have to set up an **identical** configuration in PuTTY with the **same name** and options, and connect to it once.

That done, VS code can connect without asking for the passphrase or password

**Comment by bluefeet** [comment]
This is great.

I tried doing a similar thing but using `wsl ssh` instead of `plink`.  I would have expected it to work but it still fails the same way in VS Code (with a "Could not establish connection to..." error).  On powershell it works just fine as I can `C:\workdir\fakessh.cmd user@host` just fine.

**Comment by samliddicott** [comment]
Thanks! A note to those who don't know:
Having imported your private key using PuttyGen, save private key as a ppk file which you then double-click each time you logon (to import it into pagent) and then you won't have to supply a password when you connect.
