### ISSUE TITLE
OSError: [Errno 97] Address family not supported by protocol

### ISSUE THREAD

**Issue by DragoonKP** [microsoft/vscode-remote-release#3217]
Issue Type: <b>Bug</b>

Try running a socket program or scapy to send a ICMP() packet to google.com

Extension version: 0.44.3
VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.81GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/home/kishanlal/documents/Accedian/scapy_tutorial --remote=wsl+Ubuntu-18.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2801)|
|Memory (System)|15.85GB (6.81GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment]
Please give more details. Is this related to the Remote WSL extension or is this simply a WSL issue?
