### ISSUE TITLE
Add setting for user-defined repository-container paths

### ISSUE THREAD

**Issue by stuartleeks** [microsoft/vscode-remote-release#3218]
The existing remote-container experience allows for devcontainer definitions to be external from the source repo by adding them to [vscode-dev-containers/repository-containers](https://github.com/microsoft/vscode-dev-containers/tree/master/repository-containers).

It would be useful to have this functionality available from other, user-configurable locations. This would be beneficial when working with repos that don't want a devcontainer for whatever reason, but while a developer is building out a devcontainer definition (that they may then contribute to vscode-dev-containers when ready). Since the definitions from the vscode-dev-containers repo are statically included with the extension, the lead time for getting a devcontainer definition into the extension includes the PR review time and the time until the next remote-containers extension release. This feature would provide a useful way forwards in that period.

I propose adding a `remote.containers.repository-container-paths` setting that is an array of additional paths to check when attempting to open a workspace in a devcontainer prior to using the definitions.

**Comment by lawrencegripper** [comment]
I'd love to see this feature, I currently have a devcontainer for Kubernetes built which has come more hacky/person touches so isn't really fit for the public repo (working on that) but I'd love an easy what for this to magically wire up to the k8s repo when open in VSCode without having to hack with symlinks.

**Comment by chrmarti** [comment]
Would such a configuration win over the one in the repository itself? Similar to the one in the repository winning over the one in the extension.

**Comment by stuartleeks** [comment]
Interesting question!

I was imaging that this would be used when there wasn't a devcontainer in the repo (as with the existing repository-container handling), so was thinking that the order of precedence would be:

1. repo devcontainer
2. local repository container definitions
3. vscode-dev-containers/repository-containers

Does that seem reasonable?

**Comment by chrmarti** [comment]
You could argue that 1. and 2. should be swapped because the user has more control over 'local container definitions' than over the 'repo devcontainer' (which likely is shared through SCM).

**Comment by stuartleeks** [comment]
Yeah, I see your point. Will go back to the PR branch I have in progress and take a look at that :-)

**Comment by chrmarti** [comment]
Merged the PR from @stuartleeks.

**Comment by connor4312** [comment]
I tried to verify this by cloning the dev containers repo and fiddling with `django/django`, then adding this to my local settings:

```
"remote.containers.repositoryConfigurationPaths": [
  "C:/Users/Connor/Documents/Github/vscode-dev-containers/repository-containers"
],
```

However, trying to open the repo in a container resulted in an error:

![](https://memes.peet.io/img/20-07-90962e99-1e94-4e98-9647-3a6be2dd7019.png)

```
[3840 ms] Start: Run in container: test -f /C:/Users/Connor/Documents/Github/vscode-dev-containers/repository-containers/github.com/django/django/.devcontainer/Dockerfile
[3842 ms] 
[3842 ms] 
[3842 ms] Exit code 1
[3842 ms] Start: Run: docker rm -f ce63a0e43942ea5501ee7928020034c58e4971e3280bbf477e011cdffb44f719
[4125 ms] Remote-Containers server terminated (code: 137, signal: null).
```

**Comment by chrmarti** [comment]
Let's track the feature for local folders here and the bug with cloning in a volume with #3310.

Closing for verification of the feature.
