### ISSUE TITLE
Can't establish connection to linux machine. couldn't establish tunnel to server, max wait time exausted

### ISSUE THREAD

**Issue by LittleLittleCloud** [microsoft/vscode-remote-release#322]
- VSCode Version: insider
- Local OS Version: windows 10
- Remote OS Version: ubuntu16
- Remote Extension/Connection Type: SSH

I connected it successfully for once, but after that, it just fail out
Here's the log

![image](https://user-images.githubusercontent.com/16876986/57734577-06cf6c00-7657-11e9-9248-a12e1f538a7a.png)

I already set the PasswordAuthentication to yes BTW, doesn't know if that matters or not

**Comment by leomoty** [comment]
I have the same issue, I can connect to a specific server from one machine and not from another.

**Comment by roblourens** [comment]
Does it help if you set `remote.SSH.showLoginTerminal`?

**Comment by leomoty** [comment]
Hey @roblourens, in my case, it actually does, was able to successfully login after setting `showLoginTerminal`.

**Comment by LittleLittleCloud** [comment]
yup it does, thanks!
