### ISSUE TITLE
Remote Container doesn't list all commands on a remote host

### ISSUE THREAD

**Issue by codypenta** [microsoft/vscode-remote-release#3220]
Issue Type: <b>Bug</b>

I do most of my development work on a remote machine. After SSH into an instance, I try looking for: 

- Remote-Containers: Open workspace in container
- Remote-Containers: Try a sample

but neither of these command options exist. They do however exist when I'm running VSCode locally.

Docker is properly configured (I can see docker info in the side bar) and I've made sure to install Docker extension locally. What's weird is the `Install in SSH: <remote-host>` doesn't appear for `Remote - Container`. So I couldn't install that into the remote-host. Is there a way around this?

Extension version: 0.122.1
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux arm64 4.15.0-1065-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|-psn_0_667811|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: IDE|
|OS|Linux arm64 4.15.0-1065-aws|
|CPUs|unknown (2 x 0)|
|Memory (System)|7.62GB (6.79GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Support for opening a Remote-Containers session from a Remote-SSH session is tracked as https://github.com/microsoft/vscode-remote-release/issues/2994.
