### ISSUE TITLE
Existing gpg setup breaks with code v1.46.0

### ISSUE THREAD

**Issue by hansendx** [microsoft/vscode-remote-release#3221]
- VSCode Version: 1.46.0
- Local OS Version: Ubuntu 20.04 LTS
- Remote OS Version: Debian GNU/Linux 10 (buster) (python:3.8.3-slim-buster)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Mount a folder containing gpg files inside the docker container at `/root/.gnupg/` via docker-compose.yml. This is separate from my ~/.gnupg folder on the host. I created the keys for the dev container inside the container.
2. Start code and reopen project in container.

* `gpg --list-secret-keys` returns nothing.
* Trying to sign a commit returns
```
error: gpg failed to sign the data
fatal: failed to write commit object
```
* `echo "test" | gpg --clearsign` returns
```
gpg: no default secret key: No secret key
gpg: [stdin]: clear-sign failed: No secret key
```

Content of /root/.gnupg seems unchanged. I mounted a copy of the folder at  /root/gnupg and the diff for both folders only returns
```
File .gnupg/S.gpg-agent is a socket while file gnupg/S.gpg-agent is a socket
File .gnupg/S.gpg-agent.browser is a socket while file gnupg/S.gpg-agent.browser is a socket
File .gnupg/S.gpg-agent.extra is a socket while file gnupg/S.gpg-agent.extra is a socket
File .gnupg/S.gpg-agent.ssh is a socket while file gnupg/S.gpg-agent.ssh is a socket
```
I don't know if that means, that they are different sockets. 

Signing with gpg works if:

* I mount the gnupg folder on the host somewhere else than `/root/.gnupg` and copy its content to `/root/.gnupg/` after opening the project as dev container.
* I enter the fresh containers shell directly via docker and call `gpg --list-secret-keys` before opening it with code.

I tried the tests from https://github.com/microsoft/vscode-remote-release/issues/3053 on a clean `python:3.8.3-slim-buster` image and could not get them to work 

```
root@e5251a0bfb4e:/workspaces/test# ls ~/.gnupg
S.gpg-agent  trustdb.gpg
root@e5251a0bfb4e:/workspaces/test# echo test > test.txt
root@e5251a0bfb4e:/workspaces/test# gpg --output test.sig --detach-sig test.txt
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
```

The hosts gpg version is 2.2.19, the containers version is 2.2.12.
My ~/.gnupg folder does not have a pubring.kbx file but a pubring.gpg file.
The extra gnupg folder for the container does have a pubring.kbx file.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
We seem to overwrite the `.gnupg/S.gpg-agent` socket your gpg-agent created. Does restarting the gpg-agent in the container make it work again? (I'd expect that to recreate the socket.)

On the test with the buster image: We copy `pubring.kbx` to the container if it exists, but not `pubring.gpg`. It seems we should copy that too.

**Comment by hansendx** [comment]
Restarting the gpg-agent did not recreate the socket for me.
After trying that I removed the S.gpg-agent socket file, ran `echo "test" | gpg --clearsign` which worked.
Commit signing also worked from then on.
Looking in .gnupg/, gpg recreated the S.gpg-agent socket and created three more socket files S.gpg-agent.browser,  S.gpg-agent.extra and  S.gpg-agent.ssh.

Thank you for the quick feedback on the problem.

**Comment by chrmarti** [comment]
Do you copy your private key with the Dockerfile into the container? I wonder if we should check if there are any private keys in `.gnupg` and disable the GPG forwarding feature if there are (during startup of Remote-Containers). What files/folders are in `~/.gnupg`?

**Comment by hansendx** [comment]
My Dockerfile does not change anything about the gpg setup of the base image.
I mount the whole folder into the container with docker-compose at /root/.gnupg.
When I first set this up, I mounted an empty folder and created the key inside the container.

The only other thing gpg related is a section in my custom ~/.bashrc
``` bash
if [ -d "${HOME}/.gnupg" ]; then
  git config --global user.signingkey $(gpg --list-secret-keys --keyid-format LONG | sed -En "s/^sec.*\/([A-Z0-9]*)\s.*$/\1/p")
  export GPG_TTY=$(tty)
fi
```

The .gnupg folder contains:

```
d openpgp-revocs.d
d private-keys-v1.d
- pubring.kbx
s S.gpg-agent
s S.gpg-agent.browser
s S.gpg-agent.extra
s S.gpg-agent.ssh
- trustdb.gpg
```

**Comment by chrmarti** [comment]
Fix is to skip the GPG forwarding when there are any files in the `.gnupg/private-keys-v1.d` folder.

**Comment by roblourens** [comment]
@chrmarti is there an easy way to verify this flow, or some steps to set up GPG forwarding?

**Comment by chrmarti** [comment]
To verify, you need GPG installed locally.

First verify that forwarding is setup:
- Run command `Remote-Containers: Try a Sample...`.
- Pick Node.
- When the window has finished loading, open an internal terminal.
- Check with `ls -l ~/.gnupg` that there is a `S.gpg-agent` socket.
  - If you have local `pubring.kbx` and `trustdfb.gpg` they would be copied there too.

Then verify the fix that skips forwarding if there is a private key in the container (the idea of the forwarding is to keep private keys out of the container, having one in there very likely means that forwarding is not desired):
- Still in the internal terminal, run:
```
mkdir -p ~/.gnupg/private-keys-v1.d
echo test > ~/.gnupg/private-keys-v1.d/test.key
rm ~/.gnupg/S.gpg-agent
```
- Reload window
- Verify with `ls -l ~/.gnupg` that there is *no* `S.gpg-agent` socket this time.
