### ISSUE TITLE
Ability to filter SSH Targets in left pane

### ISSUE THREAD

**Issue by slothstronaut** [microsoft/vscode-remote-release#3229]
I looked through the existing feature requests, didn't see any mention of this.

I have over 100 entires in the SSH targets list for remotes so its become cumbersome to find the correct host in the list, would be great to have a simple filter that updates the list upon every keystroke to filter the ssh targets and show the hosts that I'm looking for.

**Comment by roblourens** [comment]
You can do this the same way all trees are filtered in vscode, just type while it's focused :)
