### ISSUE TITLE
authentication fail

### ISSUE THREAD

**Issue by pengjianaixue** [microsoft/vscode-remote-release#3233]
Issue Type: <b>Bug</b>

in current version, when I input the password in password windows, can not finish the remote identity authentication, but in previous version ,the password input is in the terminal, and it's can authentication success.

Extension version: 0.51.0
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
OS version: Linux x64 5.3.0-59-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 1, 1|
|Memory (System)|7.75GB (3.73GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by rzhao271** [comment]
Closing for now as part of housekeeping. @pengjianaixue feel free to reply if this issue still happens for you on the latest version of VS Code (preferably Insiders edition).
