### ISSUE TITLE
Investigate whether we should automatically forward ports based on output

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#3235]
We can scrape the terminal or other output for things that look like ports to be forwarded. Other extensions do this already, so it might be worth moving to the core.

**Comment by gyzerok** [comment]
It is great, that you are sharing the work you are doing on GitHub. Personally I very much like following iteration plans for VSCode and Remote Extensions. Thank you!

Would it be possible to give a bit more details in the issues? Sometimes issues seem to make sense for you internally, but I feel that they don't make as much sense for a outsider, which a little bit cuts the whole initiative of you being open with the plans.

**Comment by alexr00** [comment]
Updated the description!

**Comment by alexr00** [comment]
To verify, connect to your favorite remote (SSH or containers, not WSL) and run something that causes a `host:port` (ex: http://localhost:3000/) string to output to the terminal. Open the Remote Explorer Ports view and verify that the port now shows as forwarded. Verify that you can connect to it locally.

**Comment by weinand** [comment]
starting verifying this...
