### ISSUE TITLE
Inconsistent file preview behavior when opening local and remote files

### ISSUE THREAD

**Issue by Caian** [microsoft/vscode-remote-release#3239]
With default File Preview settings, when opening a local file using the open file dialog (File > Open File), the opened file does not open as a preview. But when opening a remote file using the same method, though through the file path pop-up, it opens as a preview.

I disabled `Preview From Quick Open`, but the problem remains. The only way to disable this behavior is through the `Enable Preview` setting which is editor-wide and therefore undesirable.

I find this behavior inconsistent because they are both commands to open a file.

- VSCode Version: 1.47.0-insider
- Local OS Version: Linux Mint 19.3
- Remote OS Version: Linux Mint 19.3
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open a file using `File > Open File` menu
2. The file should not open as preview
3. Connect to a remote server though SSH
4. Open a remote file
5. The file should open as preview

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Sorry for the slow response. Please check whether this is still an issue in Insiders, we are doing work here.

**Comment by Caian** [comment]
The problem persists for vscode insders v1.52.0 with Remove-ssh v0.55.0.

**Comment by bpasero** [comment]
Good catch 👍 . via https://github.com/microsoft/vscode/commit/1357f6d4940ee109222d3469b88363e35caa2d73
