### ISSUE TITLE
Cant connect WSL: Wrong windows version detected: Windows_NT x64 6.2.9200

### ISSUE THREAD

**Issue by Eyakub** [microsoft/vscode-remote-release#3243]
Issue Type: <b>Bug</b>

[2020-06-22 02:41:29.994] Resolving wsl+Ubuntu, resolveAttempt: 1
[2020-06-22 02:41:30.050] Starting VS Code Server inside WSL (Ubuntu)
[2020-06-22 02:41:30.050] Extension version: 0.44.4, Windows build: 9200. Multi distro support: not available. WSL path support: disabled
[2020-06-22 02:41:30.376] Launching C:\WINDOWS\System32\bash.exe -c '"./scripts/wslServer.sh" cd9ea6488829f560dc949a8b2fb789f3cdc05f5d stable .vscode-server 0  ' in c:\Users\sorka\.vscode\extensions\ms-vscode-remote.remote-wsl-0.44.4}
[2020-06-22 02:41:30.489] cd9ea6488829f560dc949a8b2fb789f3cdc05f5d: -c: line 0: unexpected EOF while looking for matching `''
[2020-06-22 02:41:30.489] cd9ea6488829f560dc949a8b2fb789f3cdc05f5d: -c: line 1: syntax error: unexpected end of file
[2020-06-22 02:41:30.489] VS Code Server for WSL closed unexpectedly.
[2020-06-22 02:41:30.489] For help with startup problems, go to
[2020-06-22 02:41:30.489] https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 6.2.9200
Fetching remote diagnostics for 'WSL: Ubuntu' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.
Fetching remote diagnostics for 'WSL: Ubuntu' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.

Fetching remote diagnostics for 'WSL: Ubuntu' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.
</details>Extensions: none

**Comment by aeschli** [comment]
what is your window build?
in the wsl shell, what does `uname -r` return?

**Comment by infantiablue** [comment]
Got the same problem:

[2020-06-25 03:13:41.480] Resolving wsl+Ubuntu, resolveAttempt: 1
[2020-06-25 03:13:41.634] Starting VS Code Server inside WSL (Ubuntu)
[2020-06-25 03:13:41.635] Extension version: 0.44.4, Windows build: 9200. Multi distro support: not available. WSL path support: disabled
[2020-06-25 03:13:42.072] Launching C:\WINDOWS\System32\bash.exe -c '"./scripts/wslServer.sh" cd9ea6488829f560dc949a8b2fb789f3cdc05f5d stable .vscode-server 0  ' in c:\Users\truon\.vscode\extensions\ms-vscode-remote.remote-wsl-0.44.4}
[2020-06-25 03:13:44.353] cd9ea6488829f560dc949a8b2fb789f3cdc05f5d: -c: line 0: unexpected EOF while looking for matching `''
[2020-06-25 03:13:44.353] cd9ea6488829f560dc949a8b2fb789f3cdc05f5d: -c: line 1: syntax error: unexpected end of file
[2020-06-25 03:13:44.353] VS Code Server for WSL closed unexpectedly.
[2020-06-25 03:13:44.353] For help with startup problems, go to
[2020-06-25 03:13:44.353] https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips

**Comment by aeschli** [comment]
@infantiablue What is your Windows version? You can run `systeminfo` in a Windows console to see the OS Version.

**Comment by infantiablue** [comment]
@aeschli here is my OS version when running `systeminfo`

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation

**Comment by aeschli** [comment]
@infantiablue Do you get exact the same error message as in the issue description above?
>... cd9ea6488829f560dc949a8b2fb789f3cdc05f5d: -c: line 0: unexpected EOF while looking for matching `''

**Comment by infantiablue** [comment]
@aeschli yes, exactly as I copied from the WSL console. I tried to install VS, and upgrade to WSL 2 but still didnt work.

**Comment by aeschli** [comment]
Does it also say `Windows build: 9200` ?

**Comment by aeschli** [comment]
I'm puzzled why the log contains `Windows build: 9200`.
In the VSCode window, can you open the dev tools (`Developer: Toggle Developer Tools`), go to the promt in console tag and run `require('os').release()`?

![image](https://user-images.githubusercontent.com/6461412/86092297-9a5b3a80-baad-11ea-81ab-3ae38e17837a.png)

**Comment by infantiablue** [comment]
it display `"6.2.9200"`

**Comment by aeschli** [comment]
It seems you are running VSCode in Window 8 compatibility mode.

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/86907707-c44bd700-c115-11ea-84c5-326eb9f42f9d.png)

Can you make sure the check box is not set?

**Comment by PavelSosin-320** [comment]
I don't have any problem to start VSCode with my current Windows 10 version but what I see after the opening of VSCode, sorry, is not related to the Windows reality of Windows 10 2004 WSL 2.0 and to build 20151 + at all. I don't see in which distro my bash opened, where is my Linux mounts, where is my cross-distro mounts? Where is my Linux environment why did I land at Linux home/user ? It looks better in the Linux interop mode: $command.exe -> Code. than Windows native.  Everything looks like pre-2004 Windows version. Indeed, incompatible but VSCode lags behind Windows

**Comment by aeschli** [comment]
@PavelSosin-320 Do you see the same as described in the issue description? If not, please file a new issue.

**Comment by PavelSosin-320** [comment]
No, I succeeded to start VSCode on my Windows:
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.20161

Windows 2004 build 20161.1000
WSL Linux core 4.19.121-microsoft-standard ( from wsl -u root uname -r )
Default Linux distro Ubuntu 20.04 V2 state "running" ( from wsl -l -v )
WSL 2 distro IP on Eth0 inet 172.17.245.1 - accessible ( from wsl -u root ifconfig and ping 172.17.245.1 )

**Comment by PavelSosin-320** [comment]
Mentioned in the issue Windows version is unsupported: [Windows version support](https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions) Upgrade is available. [Upgrade Win 8 to Win 10 ](https://www.zdnet.com/article/heres-how-you-can-still-get-a-free-windows-10-upgrade/) What is it "Compatibility mode" at all for unsupported versions? SLA is signed by both parties, terminated means terminated.

**Comment by aeschli** [comment]
@PavelSosin-320 Please file a separate issue.

**Comment by infantiablue** [comment]
> It seems you are running VSCode in Window 8 compatibility mode.

it worked successfully, thank you very much for your support

**Comment by aeschli** [comment]
@infantiablue Any idea how you ended up in Window 8 compatibility mode?

**Comment by PavelSosin-320** [comment]
Yet another update and VSCode shows the same view of the File system as other Windows tools.
But I'm still puzzling how to distinguish Cmd terminal from wsl Cmd.exe terminal, PowerShell from wsl PowerShell.exe terminal, Open Folder locally and wsl Explorer.exe on Windows Host. OK, I know because I  crafted all wsl.conf, hosts, and resolv.conf There is only 1 Windows but already 10 different WSL distros. Most problematic: I have no idea in which distro my terminal is opened: wsl -d <distro-name> ???
When I'm already inside I need a simple trick: 
env ->
SHELL=/bin/bash
WSL_DISTRO_NAME=Ubuntu-20.04
Otherwise, I don't know what I do.

**Comment by aeschli** [comment]
@PavelSosin-320 Please stop positing in this issue. If you want us to help or fix anything, create a new issue and describe step by step what you do, what you see, and what you would expect to see. Also, note that this repo is for the WSL VSCode extension. WSL issues need to go to https://github.com/microsoft/wsl

**Comment by Eyakub** [comment]
Sorry for late but in that time as I failed to solve I've reinstalled the windows.

**Comment by infantiablue** [comment]
> @infantiablue Any idea how you ended up in Window 8 compatibility mode?

I am not really sure, maybe when upgrading from Win 7, I have touched some configuration without notice. (I've tried to install VS, upgraded WSL2 but still didn't work until your solution)
