### ISSUE TITLE
Env var DEBUG set when it shouldn't in terminal

### ISSUE THREAD

**Issue by jugglingthebits** [microsoft/vscode-remote-release#3247]
When I open a wsl2 terminal in vscode, the env var DEBUG is set to `*,-babel*,-*:debug,-*:*:debug,-*:*:*:debug,-*:*:*:*:debug,-*:*:*:*:*:debug`. This makes using the terminal really inconvenient, because many nodejs use this env var to enable debug logging.

The DEBUG env var isn't set when I simply open an Ubuntu terminal outside vscode.

Extension version: 0.44.4
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (2.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1991)|
|Memory (System)|12.37GB (6.92GB free)|
|VM|0%|
</details>

**Comment by dahjelle** [comment]
I've run into this on macOS as well. 

Extension Version: 0.51.0
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by bamurtaugh** [comment]
Hey @jugglingthebits @dahjelle are you still experiencing this issue? https://github.com/microsoft/vscode-remote-release/issues/3091#issuecomment-653850462 seemed to suggest it was caused by the SQLTools extension in at least one use case.

**Comment by dahjelle** [comment]
I haven't run into it for quite some time, no! Thanks for checking in!

**Comment by jugglingthebits** [comment]
No it's fixed, closing this
