### ISSUE TITLE
Problem with connecting to Raspberry 4

### ISSUE THREAD

**Issue by TomekAdamowicz** [microsoft/vscode-remote-release#3248]
Hi,

I try to connect to my raspberry pi4, it asking for platform and then for the password, but after all, I can't connect.

What is the problem?

```
[19:13:14.595] Log Level: 2
[19:13:14.599] remote-ssh@0.51.0
[19:13:14.599] win32 x64
[19:13:14.600] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a223139322e3136382e312e313130222c2275736572223a22746164616d6f227d", attempt 1
[19:13:14.600] SSH Resolver called for host: roman@192.168.1.110
[19:13:14.600] Setting up SSH remote "192.168.1.110"
[19:13:14.618] Using commit id "cd9ea6488829f560dc949a8b2fb789f3cdc05f5d" and quality "stable" for server
[19:13:14.619] Install and start server if needed
[19:13:18.549] Checking ssh with "ssh -V"
[19:13:18.616] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[19:13:18.618] Running script with connection command: ssh -T -D 55355 roman@192.168.1.110 bash
[19:13:18.623] Terminal shell path: C:\Windows\System32\cmd.exe
[19:13:18.805] > 
[19:13:18.805] Got some output, clearing connection timeout
[19:13:19.017] > roman@192.168.1.110's password:
[19:13:19.017] Showing password prompt
[19:13:23.738] Got password response
[19:13:23.738] "install" wrote data to terminal: "***********"
[19:13:23.769] > 
> 
[19:13:24.207] > 019751043bce: running
> 
[19:13:24.233] > Acquiring lock on /home/roman/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789
> f3cdc05f5d/vscode-remote-lock.roman.cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
> \ln /home/roman/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/vsc
> ode-remote-lock.roman.cd9ea6488829f560dc949a8b2fb789f3cdc05f5d.target /home/tad
> amo/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/vscode-remote-lo
> ck.roman.cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
> 
[19:13:24.270] > Found existing installation at /home/roman/.vscode-server/bin/cd9ea6488829f560d
> c949a8b2fb789f3cdc05f5d...
> SHELL=/bin/bash
> PWD=/home/roman
> LOGNAME=roman
> XDG_SESSION_TYPE=tty
> HOME=/home/roman
> LANG=en_GB.UTF-8
> VSCODE_AGENT_FOLDER=/home/roman/.vscode-server
> SSH_CONNECTION=192.168.1.108 55359 192.168.1.110 22
> XDG_SESSION_CLASS=user
> USER=roman
> SHLVL=1
> XDG_SESSION_ID=c19
> XDG_RUNTIME_DIR=/run/user/1001
> SSH_CLIENT=192.168.1.108 55359 22
> PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
> MAIL=/var/mail/roman
> _=/usr/bin/printenv
> Starting server with command... /home/roman/.vscode-server/bin/cd9ea6488829f560
[19:13:24.296] > 
> dc949a8b2fb789f3cdc05f5d/server.sh --host=127.0.0.1 --enable-remote-auto-shutdow
> n  --port=0 &> "/home/roman/.vscode-server/.cd9ea6488829f560dc949a8b2fb789f3cdc
> 05f5d.log" < /dev/null
> Waiting for server log...
> 
[19:13:24.803] > Waiting for server log...
> 
[19:13:25.304] > Waiting for server log...
> 
[19:13:25.828] > Waiting for server log...
> 
[19:13:26.332] > Waiting for server log...
> 
[19:13:26.833] > Waiting for server log...
> 
[19:13:27.331] > Waiting for server log...
> 
[19:13:27.866] > Waiting for server log...
> 
[19:13:28.366] > 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Server did not start successfully. Full server log at /home/roman/.vscode-serve
> r/.cd9ea6488829f560dc949a8b2fb789f3cdc05f5d.log >>>
> /home/roman/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/server.
> sh: 12: /home/roman/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
> /server.sh: /home/roman/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc0
> 5f5d/node: not found
> <<< End of server log
> 019751043bce##32##
> 
[19:13:28.366] Received install output: 019751043bce##32##
[19:13:28.366] Resolver error: The VS Code Server failed to start
[19:13:28.369] ------



[19:13:28.820] "install" terminal command done
[19:13:28.820] Install terminal quit with output: 
[19:13:39.372] Picking SSH host
[19:13:52.242] Selected roman@192.168.1.110
```

**Comment by ruleGreen** [comment]
I also encountered this problem, it seems cause by the update?

**Comment by ednl** [comment]
I had this too and found out that it was caused by "arm_64bit=1" in /boot/config.txt. That boots a 64bit kernel but it's otherwise still 32bit RaspiOS with 32bit userland. However, "uname -m" now reports aarch64 instead of armv7l, so Code probably downloads a 64bit version of node that it then can't start. That's the "node not found" error. Node is there, but it's the wrong version.

Work-around: rm -fr ~/.vscode-server/, comment out the arm_64bit=1 directive in config.txt, reboot, reconnect with Code which now loads a new 32bit version that works, re-enable arm_64bit, reboot, and it will still work.

**Comment by ednl** [comment]
Another possible work-around, if you have multiple Pi4s, is to copy the whole ~/.vscode-server directory (e.g. using rsync -a) from a working installation to a Pi4 that's running the 64bit kernel. I did this for a Pi4 which I didn't want to reboot twice, and it worked.

**Comment by eweitz** [comment]
> Work-around: rm -fr ~/.vscode-server/, comment out the arm_64bit=1 directive in config.txt, reboot, reconnect with Code which now loads a new 32bit version that works, re-enable arm_64bit, reboot, and it will still work.

That workaround fixed the issue for me.  Thanks @ednl!

**Comment by roblourens** [comment]
Does anyone know, is there a different command I should be running other than `uname` to check which bitness of server should run?

**Comment by ednl** [comment]
I just asked on their forum. For now, I can only think of a hard-coded secondary check:

ARCH=$(uname -m)
[ "$ARCH" = "aarch64" ] && grep 'arm_64bit=1' /boot/config.txt && ARCH=armv7l

**Comment by roblourens** [comment]
That's a good suggestion. I am actually more inclined to use the check with `/boot/config.txt` so it would be scoped to this scenario. The output of `file` doesn't look like it's meant to be parsed. And it's very different between linux and mac. Is this config always in `/boot/config.txt` for Raspberry Pi?

**Comment by ednl** [comment]
> Is this config always in `/boot/config.txt` for Raspberry Pi?

Yes. There *has* to be a FAT (-32) /boot partition for the GPU to start the process, and that's the only place that config.txt can go.

**Comment by roblourens** [comment]
Thanks for checking that. I think that's a better route than understanding what's in `config.txt`. I am still nervous about assuming that anything will hold true over everyone's machine but I'll keep thinking about it.

**Comment by long2ice** [comment]
> I had this too and found out that it was caused by "arm_64bit=1" in /boot/config.txt. That boots a 64bit kernel but it's otherwise still 32bit RaspiOS with 32bit userland. However, "uname -m" now reports aarch64 instead of armv7l, so Code probably downloads a 64bit version of node that it then can't start. That's the "node not found" error. Node is there, but it's the wrong version.
> 
> Work-around: rm -fr ~/.vscode-server/, comment out the arm_64bit=1 directive in config.txt, reboot, reconnect with Code which now loads a new 32bit version that works, re-enable arm_64bit, reboot, and it will still work.

That's great! Which trouble me so long, thanks!

**Comment by noisysoil** [comment]
Including Raspberry Pi 3 that also supports a 64-bit kernel.
The workarounds (e.g. https://github.com/microsoft/vscode-remote-release/issues/3248#issuecomment-667713057) stated here work on Pi 3 platform too.

**Comment by dakky** [comment]
Hurm i'm not shure if it's a good recommendation to switch back to 32bit kernel only for have this plugin selcting the "correct" (or better to say wrong?) node arch. 

To correct way should be, that the plugin checks the kernel and then picks the right package.
[This comment is the correct approaech IMHO](https://github.com/microsoft/vscode-remote-release/issues/3248#issuecomment-669886276)

**Comment by Hri7566** [comment]
when i connect vscode via ssh to my pi 4 (2gb model), it uses too much ram and my pi legit flatlines and every process hangs for ~2 minutes, and sometimes it freezes completely and needs to be brutally unplugged

this issue has destroyed 2 sd cards and it costs me hours of work and there's been nothing i can do about it for almost two months now, before then it was completely fine

**Comment by n8henrie** [comment]
FWIW, I have tried [a number of workarounds](https://github.com/microsoft/vscode-remote-release/issues/2947#issuecomment-814470343) without luck. Also running a 64bit kernel on RPi 4.

Unfortunately I also converted to a BTRFS root, and when I try to switch back to a 32bit kernel as recommended above I get a non-bootable system (likely didn't create a 32bit initramfs with BTRFS modules).

While I'm sure I could figure out generating an appropriate initramfs, my workaround was even simpler: I have another RPi that's still running a 32 bit kernel, so I just reached out to it with VS Code SSH Remote, then `rsync`ed the `.vscode-server` directory to the other Pi. Hacky but worked like a charm.

One thought I had -- this would certainly be a *much* less aggravating problem if there was just an option to let the user override the automatically detected system. Certainly getting everything working automatically is a great goal, but in the meantime it would sure be nice to let end users set up an environment variable or something to give it a hint!

**Comment by ednl** [comment]
> While I'm sure I could figure out generating an appropriate initramfs, my workaround was even simpler: I have another RPi that's still running a 32 bit kernel, so I just reached out to it with VS Code SSH Remote, then `rsync`ed the `.vscode-server` directory to the other Pi. Hacky but worked like a charm.

Yep! That worked for me, too: #issuecomment-651721862

**Comment by GamfaleanuVlad** [comment]
> Another possible work-around, if you have multiple Pi4s, is to copy the whole ~/.vscode-server directory (e.g. using rsync -a) from a working installation to a Pi4 that's running the 64bit kernel. I did this for a Pi4 which I didn't want to reboot twice, and it worked.

Is there a way to get that directory without having a second raspberry pi? I have just one. Could I use WSL to generate that folder and transfer it to my Pi? Or is there any link for it?

**Comment by ednl** [comment]
> Is there a way to get that directory without having a second raspberry pi? I have just one. Could I use WSL to generate that folder and transfer it to my Pi? Or is there any link for it?

No. It works because the files in that directory are tailored to the architecture and possibly the OS, in this case 32-bit ARM Raspberry Pi OS. But you can still do this: #issuecomment-651329362

**Comment by nadnerb33** [comment]
Is there any solution to this yet?

I tried commenting out `arm_64bit=1` but my Pi wouldn't boot after that change. I had to remove the SD and change it back using my laptop.
I also tried copying an existing `.vscode-server` directory from another SD card I was previously using on the same Pi. This looked like it was working as the output mentioned it had found an old server install was said it would clean up. It downloaded a few things and generally took a bit longer, but still ended up with the same error about not finding node.

**Comment by GamfaleanuVlad** [comment]
> No. It works because the files in that directory are tailored to the architecture and possibly the OS, in this case 32-bit ARM Raspberry Pi OS. But you can still do this: [#issuecomment-651329362](https://github.com/microsoft/vscode-remote-release/issues/3248#issuecomment-651329362)

Welp, I figured out that this error is because of my Super Niche use case :D. I am trying to use the preempt_rt kernel patch on the Raspberry Pi OS for an university project. I tried using `arm_64bit=1` and I have the same issue as @nadnerb33 . I understand that this is an edge of an edge case. Thanks for trying, tho :D.

**Comment by alealclag** [comment]
> I had this too and found out that it was caused by "arm_64bit=1" in /boot/config.txt. That boots a 64bit kernel but it's otherwise still 32bit RaspiOS with 32bit userland. However, "uname -m" now reports aarch64 instead of armv7l, so Code probably downloads a 64bit version of node that it then can't start. That's the "node not found" error. Node is there, but it's the wrong version.
> 
> Work-around: rm -fr ~/.vscode-server/, comment out the arm_64bit=1 directive in config.txt, reboot, reconnect with Code which now loads a new 32bit version that works, re-enable arm_64bit, reboot, and it will still work.

Hi! I've been for some days trying to solve this until I came to this issue and found this solution, but there was no line like that in my config.txt. I even tried to add the line arm_64bit=0, which made my Raspi not being able to boot (if this happened to any of you, just take out the SD card and edit the config.txt from another PC). 

But what I found when trying this is that there was another suspicious line: the command that indicates the kernel image, which in my case was `kernel=kernel8.img` (On Raspi 4 it should be `kernel7l.img`). Changed it, removed `~/.vscode-server`, rebooted, tried to connect again with VS Code and voilà!! 

So apart from showing a different case's solution, I also wanted to thank you!!!!

**Comment by roblourens** [comment]
I think the base issue here is actually the same as https://github.com/microsoft/vscode-remote-release/issues/2947
