### ISSUE TITLE
Python Intellisense uses 100% CPU, hangs

### ISSUE THREAD

**Issue by rosstex** [microsoft/vscode-remote-release#3250]
- VSCode Version: 1.47.0-insider
- Local OS Version: Mac OS 10.15.1
- Remote OS Version: Ubuntu 20.04 LTS
- Remote Extension/Connection Type: SSH

The Python Intellisense remote extension continually breaks. When I first start VSCode and start typing, it will display suggestions for what I type. As soon as I accept one, it breaks and stops working on the next line. The Python extension (completion.py) uses 100% CPU. If I wait a minute, it will appear again.

Similarly with rolling over functions/ fields with CMD held down. If I wait and then move my mouse around, it will identify links to function sources. But the links start to lag behind the location of my mouse, and after a few seconds it stalls and stops working for a minute.

Note that I am running an Anaconda build of Python.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by chrmarti** [comment]
This sounds more like an issue with the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
