### ISSUE TITLE
Go To Definition is not working with WSL extension.

### ISSUE THREAD

**Issue by angelrove** [microsoft/vscode-remote-release#3256]
Issue Type: <b>Bug</b>

Go To Definition in VS Code is not working for me with WSL extension.

Extension version: 0.44.4
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.03GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/home/angelrove/develop/nestti-integracion --remote=wsl+Ubuntu-18.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|Memory (System)|12.35GB (10.10GB free)|
|VM|0%|
</details>

**Comment by bamurtaugh** [comment]
Hey @angelrove, are you still experiencing this with the latest version? If so, do you have any other extensions enabled as well?

**Comment by aeschli** [comment]
@angelrove Can you add more details. A code sample, any additional extensions involved?

**Comment by bamurtaugh** [comment]
Please feel free to let us know if you are still experiencing this issue, and we'd be happy to reopen/discuss further. Thank you!
