### ISSUE TITLE
Remote WSL over SSH

### ISSUE THREAD

**Issue by garymm** [microsoft/vscode-remote-release#3257]
I use a Mac as my GUI to run VS Code client.
I have a Windows box and I can connect to it over SSH, including using VSCode Remote-SSH.
I've installed Windows Subsystem for Linux (WSL). I can get into the WSL shell in the built-in terminal (there's a drop down in the VSCode terminal pane that lets me choose WSL).
However I can't open files from the WSL file system in the VSCode editor.
For now I've resorted to connecting to the windows box using Microsoft Remote Desktop and using Remote-WSL.

**Comment by garymm** [comment]
I managed to work around this by using OpenSSH on Windows and setting the SSH command to "bash.exe" as described here:
https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration

With that, running "code" in the terminal opens files from the WSL file system just fine.

If you want to be able to SSH to both the Windows host and WSL, this won't work, but I only need SSH access to WSL, so this is a pretty simple solution for me.

**Comment by jkoritzinsky** [comment]
I got this working by configuring a second ssh server in vscode that ran the `wsl.exe` command upon opening the ssh connection and having the first one just be ssh without any additional commands.

**Comment by SeanSyue** [comment]
> I got this working by configuring a second ssh server in vscode that ran the `wsl.exe` command upon opening the ssh connection and having the first one just be ssh without any additional commands.

@jkoritzinsky How did you configure the `wsl.exe` command? I added the following lines in my client's ssh `config` file:
```
RequestTTY force
RemoteCommand wsl
```
but I still cannot open files stored in wsl through vscode.

**Comment by bamurtaugh** [comment]
Thanks for the discussion! I believe the doc [here](https://code.visualstudio.com/docs/remote/troubleshooting#_ssh-into-a-remote-wsl-2-host) may also help.
