### ISSUE TITLE
Can not Open Folder in Container

### ISSUE THREAD

**Issue by qvjp** [microsoft/vscode-remote-release#3258]
- VSCode Version: 1.46.1(user setup)
- Local OS Version: Windows10 Pro 2004 19041.330 
- Name of Dev Container Definition with Issue: ubuntu 20.04

Steps to Reproduce:

1. Attach to container, open a directory, it's ok
2. use crtl + shift + p select `remote-containers: openfolder in container`, open another directory, got an error: 
![image](https://user-images.githubusercontent.com/17522949/85870024-1c720780-b7ff-11ea-884f-0c989bf23de0.png)

**Comment by Chuxel** [comment]
@qvjp Are you already in the container when you run this command? Did you select a folder inside the container?

If so, you can just use "File > Open Folder" to open another folder.

**Comment by qvjp** [comment]
@Chuxel Thank you, it's work.
