### ISSUE TITLE
Cannot use vscode as git.core.editor

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/vscode-remote-release#3261]
- Version: 1.47.0-insider (user setup)
- Commit: 9bf6af04dcb5c2e531cedca83cd188939ca1b0db
- Local OS Version: Windows_NT x64 10.0.18363
- Remote OS Version: Windows_NT x64 10.0.18363
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. My local OS and remote OS is a replica. They have the same vscode config, same git config, can ssh to each other.
2. When executing `git rebase -i HEAD~5`, git will try to open the vscode on the remote OS.
3. My `git.core.editor` is `code-insiders --wait` (same on the local and remote os)

In the vscode terminal, if I run

```shell
which code-insiders.cmd
c:\Users\Jack\.vscode-server-insiders\bin\9bf6af04dcb5c2e531cedca83cd188939ca1b0db\bin\code-insiders.cmd
```

In the remote OS, it is

```shell
which code-insiders.cmd
C:\Users\Jack\AppData\Local\Programs\Microsoft VS Code Insiders\bin\code-insiders.cmd
```

It seems like git is using `C:\Users\Jack\AppData\Local\Programs\Microsoft VS Code Insiders\bin\code-insiders.cmd` instead of `c:\Users\Jack\.vscode-server-insiders\bin\9bf6af04dcb5c2e531cedca83cd188939ca1b0db\bin\code-insiders.cmd` even I run git in the vscode remote-ssh terminal. How can I configure vscode or git to let it work on both local and via remote-ssh?

**Comment by roblourens** [comment]
Sorry for the slow response. Is this still an issue?

**Comment by Jack-Works** [comment]
> Sorry for the slow response. Is this still an issue?

Yes, I tried again just now, it still not working

**Comment by Jack-Works** [comment]
Does it caused by git bash don't read Windows environment variable PATH?

**Comment by Jack-Works** [comment]
Ok I don't know why but I changed from 

> \[core\]
> 
>     editor = cmd /c code-insiders --wait

to

> \[core\]
> 
>     editor = powershell -NoProfile -Command code-insiders --wait

It works now.
