### ISSUE TITLE
RG processes after disconnect

### ISSUE THREAD

**Issue by therblack** [microsoft/vscode-remote-release#3263]
- VSCode Version: 1.45.1
- OS Version: windows 7x64

Steps to Reproduce:

1. Connect to Linux server using remote extension
2. If the remote extension disconnects (mine seems to regularly) there are often many rg processes left running (they need to be killed manually on the server)

**Comment by roblourens** [comment]
These are processes from a search triggered by the user or an extension, and they are children of the now-disconnected remote extension host process. You can look at the command line args of these processes to get some clue about what triggered them or why they are slow to complete.
