### ISSUE TITLE
Test: Guidance to open a repository in a volume

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#3265]
Refs: #3199

- [x] anyOS @deepak1556
- [x] windows @JacksonKearl

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%233265%0A%0A)

---

When your workspace folder has a devcontainer.json (`Add Development Container Configuration Files` command) and is part of a Git repository, the 'Reopen in Container' notification has guidance for cloning the repository in a Docker volume.

Verify:
- The guidance makes sense.
- If you have local changes, there is a follow-up notification explaining that these won't be in the volume.
- The Repository Container prompt opens with the current repository filled in.
  - Verify this supports non-default branches.
  - Verify this supports secondary Git remotes.

**Comment by JacksonKearl** [comment]
I'm not seeing this notification on MacOS, remote containers v0.124.0.

**Comment by chrmarti** [comment]
@JacksonKearl You might have turned it off entirely before (that is preserved). Do you have it on Windows? (You're assigned for Windows.)

**Comment by deepak1556** [comment]
Verified on macOS, really cool feature 👍 

Maybe this can be clarified here, can open issue if needed. The guidance notification to clone in volume currently has a link to https://code.visualstudio.com/docs/remote/containers , wouldn't it be better to point to the part of documentation that talks about the difference between cloning in a volume vs opening in a container ?
