### ISSUE TITLE
Test: Allow disabling "reopen" notification per folder

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#3267]
Refs: #3197

- [x] anyOS @deepak1556
- [x] windows @rebornix

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%233267%0A%0A)

---

When your workspace folder has a devcontainer.json (`Add Development Container Configuration Files` command) the 'Reopen in Container' notification is shown. Verify that you can turn it off per folder and also for all folders at once.

**Comment by rebornix** [comment]
Works as expected. The only catch is I didn't find how to revert the change.

**Comment by deepak1556** [comment]
same issue as @rebornix , otherwise works fine.
