### ISSUE TITLE
Test: Adopt onStartupFinished

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#3268]
Refs: #3196

- [x] anyOS @egamma 
- [x] anyOS @kieferrm

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%233268%0A%0A)

---

Open a new (empty) window, run `Show Running Extensions` command and verify the Remote-Containers extension activates after everything else has started up. (The delay might not be noticeable.)

**Comment by egamma** [comment]
Works nicely, I had the same issue as @Chuxel el in https://github.com/microsoft/vscode-remote-release/issues/3293

**Comment by kieferrm** [comment]
@chrmarti this works for an empty window, however when I reload a window that has a folder open that contains a devcontainer spec I see it startup pretty much immediately, i.e. a bunch of other extensions activate after the containers extensions. That's how it's supposed to work?

**Comment by chrmarti** [comment]
@kieferrm Yes, we activate immediately when there is a devcontainer.json in the workspace folder. We added the deferred activation, so we can check if we have devcontainer.json built into the extension (currently only for a small set of repositories).
