### ISSUE TITLE
Dev Container fails on build/rebuilds on first try : extensionsCache cannot be found

### ISSUE THREAD

**Issue by sr229** [microsoft/vscode-remote-release#3269]
- VSCode Version: 1.47.0-insider (9bf6af04dcb5c2e531cedca83cd188939ca1b0db)
- Local OS Version: Windows_NT x64 10.0.20152
- Name of Dev Container Definition with Issue: N/A

It seems that `extensionsCache` is causing the build to fail. However, on retries it works finally, just on build/rebuilds it fails.

![image](https://user-images.githubusercontent.com/14976516/85965505-73d6ca00-b9ef-11ea-8039-3593bec54120.png)

Steps to Reproduce:

1. Clone this Project -> https://github.com/sr229/clarisa
2. Open a Container in `gateway/` and build it.
3. It should continue to the workspace but fails upon successful build. Retrying allows it to continue further.

**Comment by Chuxel** [comment]
//cc: @sandy081 @chrmarti Any ideas why this would happen?  The Go extension's ID was changed, but this refers to the old ID.  Could that cause this?

**Comment by sandy081** [comment]
I suspect this is due to the rename because error says following command in container is failed

`ls /root/.vscode-server-insiders/extensionsCache`

May be related to the extensions cache that we added recently? @chrmarti might have more insights

**Comment by chrmarti** [comment]
The folder wasn't created because the only listed extension id does not exist. Will make this more robust.

@sandy081 Could the CLI somehow support old extension ids? It seems this will break a lot of configurations.

**Comment by sandy081** [comment]
Unfortunately there is no way as Marketplace completely wipes out old id. This is same in all configurations where extension ids are used (extensionDependencies, extensionPacks, recommendations etc.,)
