### ISSUE TITLE
Autoimport not working

### ISSUE THREAD

**Issue by imeredith** [microsoft/vscode-remote-release#327]
Issue Type: <b>Bug</b>

I have a typescript project with Remote Development installed and configured to use WSL. Everything seems to be working great, apart from that autoimport suggestions are not working.

I uninstalled the plugin and autoimport works, then reinstalled and it stopped working. 

I have made sure the option is enabled for both remote and local in the settings. I also tried using the projects typescript version instead of bundled version but it made no difference 

With Remote Development: 
![image](https://user-images.githubusercontent.com/140492/57760670-29917b80-7750-11e9-951a-36771bec7c65.png)

Without Remote Development (its actaully just normal release version of vscode but its the same as code-insiders without remote dev installed):
![image](https://user-images.githubusercontent.com/140492/57760898-90af3000-7750-11e9-8114-9cb1f2b896ff.png)

Extension version: 0.35.0
VS Code version: Code - Insiders 1.34.20-insider (57b550c559b945eb9d871dbf2b2e4cb9e31e2551, 2019-05-10T17:36:45.765Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (4.26GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+default/<redacted> --remote=wsl+default|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|Memory (System)|15.95GB (4.26GB free)|
|VM|0%|
</details>

**Comment by imeredith** [comment]
I just tried this again and realized that its only an issue when trying to import fro, external modules. Auto import work fine with things within one project

**Comment by mjbvz** [comment]
Can you please re-test this using a VS Code 1.35 insiders build?

**Comment by imeredith** [comment]
VS Code 1.35 insiders still has the same issue

**Comment by imeredith** [comment]
Can confirm issue still present on 1.36

**Comment by imeredith** [comment]
Its working now.
