### ISSUE TITLE
Cannot connect to Windows host that has busybox installed

### ISSUE THREAD

**Issue by tangmi** [microsoft/vscode-remote-release#3270]
VSCode Remote SSH doesn't seem to want to connect to a Windows host that has `busybox` installed. Removing `busybox` resolves the issue.

- VSCode Version: 1.46.1
- Local OS Version: macOS Mojave 10.14
- Remote OS Version: Windows 10.0.19041.330
- Remote Extension/Connection Type: SSH/Docker/WSL: SSH

Steps to Reproduce:

1. Install `busybox` on Windows host (I use [scoop](http://blog.lukesampson.com/busybox-for-windows): `scoop install busybox`)
2. Try to connect from the client, noting the output:

```
...
[11:24:27.982] stderr> Authenticated to hostname ([hostname]:22).
[11:24:28.008] > Microsoft Windows [Version 10.0.19041.330]
> (c) 2020 Microsoft Corporation. All rights reserved.
[11:24:28.009] > 
> user@HOST C:\Users\user>echo 'ready: a76b3d6ea503'
[11:24:28.011] > 'ready: a76b3d6ea503'
> 
> user@HOST C:\Users\user>
[11:24:28.013] > uname -rsv
[11:24:28.057] > Windows_NT 10.0 19041
[11:24:28.062] > 
> user@HOST C:\Users\user>
[11:24:44.563] Terminating local server
[11:24:44.566] Resolver error: Connecting with SSH timed out
[11:24:44.570] ------




[11:24:44.575] Local server exit: 15
```

I can tell from the log that the VSCode Remote calls `uname` (included in `busybox`), which seems to execute fine. I can even do `echo uname -rsv | ssh hostname` and get the same output as above. I'm not sure what VSCode Remote does next--I can't seem to find the source for this extension(?)--but it looks like it hangs with no output on the next prompt and times out.

In case it helps, `busybox` adds the following programs to the path: `[`, `[[`, `ar`, `arch`, `ash`, `awk`, `base64`, `basename`, `bash`, `bunzip2`, `busybox`, `bzcat`, `bzip2`, `cal`, `cat`, `chmod`, `cksum`, `clear`, `cmp`, `comm`, `cp`, `cpio`, `cut`, `date`, `dc`, `dd`, `df`, `diff`, `dirname`, `dos2unix`, `dpkg`, `dpkg-deb`, `du`, `echo`, `ed`, `egrep`, `env`, `expand`, `expr`, `factor`, `false`, `fgrep`, `find`, `fold`, `fsync`, `ftpget`, `ftpput`, `getopt`, `grep`, `groups`, `gunzip`, `gzip`, `hd`, `head`, `hexdump`, `httpd`, `iconv`, `id`, `inotifyd`, `ipcalc`, `kill`, `killall`, `less`, `link`, `ln`, `logname`, `ls`, `lzcat`, `lzma`, `lzop`, `lzopcat`, `man`, `md5sum`, `mkdir`, `mktemp`, `mv`, `nc`, `nl`, `od`, `paste`, `patch`, `pgrep`, `pidof`, `pipe_progress`, `pkill`, `printenv`, `printf`, `ps`, `pwd`, `readlink`, `realpath`, `reset`, `rev`, `rm`, `rmdir`, `rpm`, `rpm2cpio`, `sed`, `seq`, `sh`, `sha1sum`, `sha256sum`, `sha3sum`, `sha512sum`, `shred`, `shuf`, `sleep`, `sort`, `split`, `ssl_client`, `stat`, `strings`, `su`, `sum`, `tac`, `tail`, `tar`, `tee`, `test`, `time`, `timeout`, `touch`, `tr`, `true`, `truncate`, `ts`, `ttysize`, `uname`, `uncompress`, `unexpand`, `uniq`, `unix2dos`, `unlink`, `unlzma`, `unlzop`, `unxz`, `unzip`, `usleep`, `uudecode`, `uuencode`, `vi`, `watch`, `wc`, `wget`, `which`, `whoami`, `whois`, `xargs`, `xxd`, `xz`, `xzcat`, `yes`, `zcat`.

Does this issue occur when you try this locally?: Yes(?)
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Thanks!

**Comment by rzhao271** [comment]
@tangmi closing this issue for housekeeping. Feel free to reply if this issue still shows up on the latest VS Code (preferably Insiders edition).
