### ISSUE TITLE
Intermittently locks up computer until hard reboot

### ISSUE THREAD

**Issue by peredwardsson** [microsoft/vscode-remote-release#3275]
Issue Type: <b>Bug</b>

Unable to reproduce it reliably, but the issue occurs when writing Python code via WSL. I get a popup saying that connection was lost and that asks me to reconnect manually or wait for 5 seconds before VSCode does so for me. However, it is unable to reconnect given any tried time, some functions cease working outside of VSCode. Most notably, trying to reboot does nothing and hitting ctrl+alt+delete makes the computer lock up. 

My only solution has been to reboot via the power button.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 x 3792)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (10.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 x 3792)|
|Memory (System)|15.93GB (10.75GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
language-julia|jul|0.16.11
python|ms-|2020.6.90262
cpptools|ms-|0.28.3
vscode-yaml|red|0.8.0
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0

</details>

**Comment by aeschli** [comment]
Any chance to open a WSL shell and make a `ps -ax` to see what's going on?

**Comment by peredwardsson** [comment]
See below. Couple of notes: formatting was messed up inside bash but I tried to fix it before posting. Also, issues are currently not happening. I'll try to repeat and post again when it reoccurs.

```
  PID TTY      STAT   TIME COMMAND
    1 ?        Ssl    0:00 /init ro
   10 tty1     Ss     0:00 /init ro
   11 tty1     S      0:00 -bash
   12 tty2     Ss     0:00 /init ro
   13 tty2     S      0:00 sh -c "$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" cd9ea6488829f560dc949a8b2fb789f3cdc05f5                                        
   14 tty2     S      0:00 sh /mnt/c/Users/per/.vscode/extensions/ms-vscode-remote.remote-wsl-0.44.4/scripts/wslServer.s   
   23 tty2     S      0:00 sh /home/per/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/server.sh  --port=0
   25 tty2     Sl     0:13 /home/per/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/node /home/per/.vscode-   
   43 tty2     Sl     0:13 /home/per/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/node /home/per/.vscode-   
   61 tty2     Sl     1:14 /home/per/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/node /home/per/.vscode-   
   80 pts/0    Ss     0:00 /bin/bash
   291 tty2     Sl     1:33 /usr/bin/python3 /home/per/.vscode-server/extensions/ms-python.python-2020.6.90262/pythonFile  
   306 tty2     Sl     0:00 /home/per/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/node --max-old-space-si   
   307 tty2     Sl     0:21 /home/per/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/node --max-old-space-si   
   320 tty2     Sl     0:00 /home/per/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/node /home/per/.vscode-  
   327 tty2     Sl     0:00 /home/per/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/node /home/per/.vscode-  
   334 tty2     Sl     0:01 /home/per/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/node /home/per/.vscode-  
   342 tty2     Sl     0:42 /home/per/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/node /home/per/.vscode-  
   621 tty2     Sl     0:00 /home/per/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/node /home/per/.vscode- 
   4369 tty2     S      0:01 /usr/bin/python3 /home/per/.vscode-server/extensions/ms-python.python-2020.6.90262/pythonFile 
   6040 tty2     S      0:00 /usr/bin/python3 /home/per/.vscode-server/extensions/ms-python.python-2020.6.90262/pythonFile 
   6497 tty3     Ss     0:00 /init ro
   6498 tty3     S      0:00 -bash
   6667 tty3     R      0:00 ps -ax
```

**Comment by aeschli** [comment]
Do you still see this?

**Comment by peredwardsson** [comment]
Negative, closing for now.
