### ISSUE TITLE
Allow editing of .devcontainer/Dockerfile after failed container build

### ISSUE THREAD

**Issue by david-s-svedberg** [microsoft/vscode-remote-release#3277]
Just a bit inconvenient to have to open the Dockerfile in a different editor, I know I can "Reopen Locally" but then I loose the error message.

Opening the file at the failing Command would be even nicer.

**Comment by Chuxel** [comment]
//cc: @chrmarti Shouldn't the log file be opening when you do "Reopen Locally"?
