### ISSUE TITLE
Named configuration files don't have any schema applied

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-remote-release#3284]
Testing #3266

I didn't know what kind of things the file could contain from the issue alone, so I tried to find some completions, but there aren't any

![](https://memes.peet.io/img/20-06-09c977aa-cfc1-4d28-8fe8-d0aaea6095be.png)

**Comment by chrmarti** [comment]
That should have been in todays Insiders build. Are you on the latest?

**Comment by connor4312** [comment]
I thought I was, but I must not have been. Verified I'm up to date and it now works.
