### ISSUE TITLE
Version control tracking information is not updated in the file explorer

### ISSUE THREAD

**Issue by dan1994** [microsoft/vscode-remote-release#3285]
**Details**

- VSCode Version: 1.46.1
- Local OS Version: Windows 10 Home 2004 (Build 19041.329)
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: WSL

**Steps to Reproduce**

- Open a git tracked folder in VS code.
- Change the content of any file and save.
(The sidebar doesn't show the file as modified)
- Reload VS code
(Now the file appears as modified in the sidebar)
- Restore the original file contents
(The file is still marked as modified until reload...)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by danecreekphotography** [comment]
I believe I'm seeing something similar to this with Remote - Containers. I keep getting lists of files showing as modified but they have no changes in them. If I re-open the folder locally the files show correctly as unmodified.

**Comment by bamurtaugh** [comment]
cc @aeschli Does it look like this issue relates to #2310?

**Comment by dan1994** [comment]
Yeah, that's definitely it.
Was hoping to easily share my projects between Windows and WSL by putting them in the `C:` drive, and accessing them through `/mnt/c`.
I hope the other way around will work better (moving my projects to the WSL fs, and accessing from windows through `\\wsl$\`).

**Comment by dan1994** [comment]
Sadly, this seems to occur the other way around as well.
I've transferred all my projects into WSL, and now windows projects I'm working on that sit inside WSL don't have their tracking information updated when using the non-remote VS code.

**Comment by pergpau** [comment]
Exactly the same problem as dan1994 has. And restarting vsc shows the modifications.

My code files are in the linux file system (not mnt).

**Comment by pergpau** [comment]
I can add that it does work when using VSC WSL remote, but not when opening VSC from Windows.

**Comment by aeschli** [comment]
@pergpau No file events on on the Windows side on `\\wsl$\...`. That's https://github.com/microsoft/WSL/issues/4739

Missing file events on the WSL side on `/mnt/c`, that's https://github.com/microsoft/vscode-remote-release/issues/3959.

Unfortunatly these are both WSL issues and there's currently nothing we can do in the Remote-WSL extension.
