### ISSUE TITLE
Typing in bash lags couple of seconds

### ISSUE THREAD

**Issue by FerhatAkgun** [microsoft/vscode-remote-release#3288]
I am using the remote extensions for a while to edit and compile code on my remote linux machine.
I have recognized a lagging problem in the bash window, where the window does not react to any input for multiple seconds.

I have recorded the performance via devtools, when the lagging occurred. When you load the attached profile, you will see the issue at the very beginning.
Somewhere at the beginning I am typing into the bash window. Probably at around 500ms.
The entered input appears at about 9500ms

I double checked by connecting to the same machine via putty. There I didn't see any lagging.

[Profile-20200630T213322.zip](https://github.com/microsoft/vscode-remote-release/files/4854147/Profile-20200630T213322.zip)

Extension version: 0.51.0
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.4.0-148-generic

**Comment by jasonwilliams** [comment]
Looks related to https://github.com/microsoft/vscode/issues/100427

**Comment by roblourens** [comment]
Maybe due to the linked issue or just due to some extension or something else using lots of CPU on your remote. We also made changes recently to improve terminal typing performance in these situations.
