### ISSUE TITLE
Opening container via clone into new volume is confusing when the devcontainer file is untracked

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-remote-release#3289]
Testing #3265

If you create a new untracked devcontainer.json file, the "Would you like to open this via clone or mount" prompt appears. If you hit clone it will tell you that untracked files won't be included, but it's still odd to fill out the `devcontainer.json`, then have it totally discarded and need to make a new one. 

This could be especially confusing if people might not understand that the configuration needs to be tracked in the first place.

I think it would make sense to disallow opening via clone if you have local changes, for advanced users stashing wont be a hinderance and for beginners it avoids a lot of potential confusion.

**Comment by chrmarti** [comment]
Fix is to check if the devcontainer.json exists on the remote tracking branch.

**Comment by JacksonKearl** [comment]
Whats the release schedule for this extension? (for verification)

**Comment by chrmarti** [comment]
@JacksonKearl Just published 0.125.0. Thanks!
