### ISSUE TITLE
Show "unable to watch for file changes in this large workspace" warning in the client VS Code install

### ISSUE THREAD

**Issue by sav-valerio** [microsoft/vscode-remote-release#329]
I'm using the **Remote SSH** extension (_awesome work by the way!_) along with an **Ubuntu remote system**, still I noticed that the **Explorer section** on the left side **would not update** when adding/deleting any files/folder.

After some hours of troubleshooting I noticed that opening the folder directly on the Ubuntu machine would give me the infamous "[unable to watch for file changes in this large workspace](
https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc)" warning.

The required update in the **sysctl.conf** fixed the problem.

I'm suggesting then to **show this warning message also on the client VS Code** (in my case the one that I'm running on Windows).
It should be relatively easy and this little thing might save a lot of troubleshooting time to others.

**Comment by bpasero** [comment]
Yes we need to wire this through somehow as notification.

//cc @aeschli
