### ISSUE TITLE
Odd formatting in MRU list in VS Code home screen when using container name-based attach config

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#3290]
Testing #3266

After attaching to a container and setting up a named configuration I am noticing some odd formatting in the MRU list in the VS Code home screen.

![image](https://user-images.githubusercontent.com/312252/86185602-951ce080-baeb-11ea-8a47-cd48026f408a.png)

"toster-strudle" and "toster-strudle3" are the names I assigned to the containers.

**Comment by chrmarti** [comment]
We try to prevent recent entries from attached containers. How did you open them?

**Comment by Chuxel** [comment]
Via the Remote Explorer initally.  I might have shut down VS Code and then started it up again which could have re-attached.
