### ISSUE TITLE
Containers: Volume => `Inspect` vs `Inspect in Visual Studio Code` confusing

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-remote-release#3291]
It seems "Inspect" opens up an editor with the volume's metadata, and "Inspect in Visual Studio Code" opens a new workspace attached to the volume. Clicking the treeitem seems to not doing anything. Maybe clicking could open the metadata editor, and "Inpect" could do the full mount proccess?

![image](https://user-images.githubusercontent.com/8586769/86186211-5720bc00-baed-11ea-8c8d-bdfae9094b09.png)

**Comment by chrmarti** [comment]
Inspect is from the Docker extension (like the view and viewlet). Inspect in VS Code is contributed by Remote-Containers.

I think it makes sense for single-click to not do anything beyond selecting the item. It becomes hard to select without triggering an action otherwise.

**Comment by chrmarti** [comment]
Closing since we are not in charge except for contributing the second action.
