### ISSUE TITLE
Certain remote-container commands are not working as intended when clone in volume

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-remote-release#3295]
Testing #3265

Scenario I:

* Clone in volume
* Click `Dev Container..` status bar icon
* `Remote-Containers: Open Folder in Container` does nothing

Scenario II:

* Clone in volume
* Command Palette > `Remote-Containers: Reopen in container`, nothing happens
*. Not sure if this is intended under this context, if not a notification should be shown for invalid command

**Comment by chrmarti** [comment]
Fixing `Open Folder in Container`. The `Reopen in Container` case might need a context to only activate in the 'inspect volume' case. Moving to you @egamma .

**Comment by egamma** [comment]
duplicate of https://github.com/microsoft/vscode-remote-release/issues/3144
