### ISSUE TITLE
Zombie progress notification when clone in volume process is abruptly discontinued

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-remote-release#3297]
Testing #3265

* Clone in volume
* enter github entrypoint
* Create volume prompt is shown
* Press esc which exits the prompt
* Progress Notification is still shown and cannot be closed directly

**Comment by chrmarti** [comment]
https://github.com/microsoft/vscode-remote-containers/commit/16cda6e154a2c20c42088eff9f55e15aa1b9a2bb
