### ISSUE TITLE
Remote - SSH: Constantly disconnects while running "Initializing JS/TS language features"

### ISSUE THREAD

**Issue by SomervilleTom** [microsoft/vscode-remote-release#3298]
I run VisualStudio code on a robust Windows 10 Pro host, using SSH to connect to a CentOS 7 guest VM running on a VMWare Workstation Player hypervisor. There are no issues with SSH, third-party SSH clients work fine, other IDEs that connect to guest VM using SSH work just fine. I am debugging NodeJS/Javascript and HTML on the guest.

In the past week or so, the VSC has become completely unusable. At random times, the IDE disconnects, offers a sequence of confusing dialogs about reconnecting or disconnecting or whatever, then sits and burns CPU cycles while a little status area says "Initializing JS/TS language features". During these times, it frequently grabs keyboard focus from other windows and apps.

I've seen what appear to be bug reports about similar issues with "JS/TS language features". Those are each marked as "closed" and/or "resolved" even though no workaround or solution is described and even though many comments reporting the issue are present.

If I can't find a work-around soon, I'll have to switch to a different IDE. The current version is unusable.

**Comment by navari-technologies** [comment]
I can confirm that I'm facing the same issue.

I have a project with Python and React (Javascript) files. I can work on Python files continuously for hours without the SSH disconnecting. But, after some time working with React files, the SSH will disconnect and repeatedly try to reconnect.

To further isolate the issue, I deactivated the built-in "TypeScript and JavaScript Language Features" extension in VSCode (which is extremely annoying, as I now have no code completion) and I was able to edit React files without the SSH losing connection. Basically, with that extension enabled, working on any JS or TS files causes the SSH connection to drop. While disabling this extension fixes the issue.

I also noticed that this extension (when enabled) is causing the CPU on my server to spike. This could be what is resulting in the dropped SSH connection and something that other people have reported.

Agreed, until this is resolved, this extension is unusable.

**Comment by SomervilleTom** [comment]
@navari-technologies: If you get a chance, can you please describe how you disabled that extension? I haven't been able to find the needed incantations in the preferences file (or underlying json). I'm eager to give up code completion in exchange for a working IDE.

Oh, and for what it's worth, I've been running VSCode from inside my CentOS 7 guestVM using the knome desktop. This makes the RemoteSSH extension unnecessary. The same "TypeScript and Javascript Language Features" extension brings my entire system to its knees. It looks to me as though it's that built-in extension that is the real problem.

With the built-in "TypeScript and Javascript Language Features" extension makes VSC unusable.

**Comment by navari-technologies** [comment]
@SomervilleTom - Here are the steps I took:

1. Open VSCode and click on the "Extensions" link in the left sidebar
2. In that window, you'll see "..." in the top right corner
3. In that list, select "Show Built-in Extensions"
4. Further filter by typing "typescript" in the search box, which should show the "TypeScript and Javascript Language Features" extension
5. Click on the cog icon for the extension and select "Disable" or "Disable (Workspace)"
6. You'll probably need to restart VSCode for the changes to take affect

After the above, I was able to work on my React project without any SSH disconnection issues -- granted it came at the cost of not having code completion. Really hope that, if it is this extension, they resolve this soon.

**Comment by SomervilleTom** [comment]
Ah ... the old secret hidden "..." menu trick. Worked like a charm!

Now that I've turned off automatic updates (because they don't work anyway, at least on my Windows 10 pro host system, because of an independent bug) and now this, the editor again seems to be usable again.

**Comment by Chuxel** [comment]
//cc: @roblourens Is this a general problem with the TS/JS language server or something specific to SSH?  Wonder if this should be in the vscode repo instead.

**Comment by roblourens** [comment]
You will get disconnected from the remote if something takes up too many cycles for too long in the extension host, and it sounds like the TS extension is doing that here. Is your remote low on CPU/RAM? cc @mjbvz

**Comment by SomervilleTom** [comment]
I don't know what "too many cycles for too long in the extension host" means. The Windows 10 pro host has 4GB. The two remote hosts each have 2GB. One of the "remotes" is a guest VM running on VMWare Workstation Player on the same Windows 10 Pro as host as the VSC that I'm using. I see the issue on both remote hosts.

My VSC works fine while "TypeScript and Javascript Language Features" is turned off. I don't use those features even if it works.

I appreciate your help. Let me know if I can provide more info.

**Comment by roblourens** [comment]
I just mean that if a process is very busy for a long time, then the vscode client will think that the remote has disconnected.

3 GHz? 😁 

2GB is probably pushing it... I don't think we declare a particular recommended minimum but if you watch the host while the vscode server is running on it, I'm guessing you will see our processes using every bit of memory, and that's probably slowing it down. Even with the TS extension disabled, you might see the same issue from the filewatcher extension if you open a large workspace.

**Comment by SomervilleTom** [comment]
3Ghz indeed.

Since starting this thread, I've had to upgrade the EC2 instances to t2.large. That means 8GB RAM, up from 2G. I've pretty much punted my local guest VM.

This is all because I'm running Neo4J and it's also hungry for RAM.

**Comment by SomervilleTom** [comment]
Let me know if there's some sort of benchmark or test that you'd like me to run.

**Comment by roblourens** [comment]
Hopefully the experience will be better with more RAM - let me know how it goes
