### ISSUE TITLE
Start up takes about 5 minutes

### ISSUE THREAD

**Issue by BMarelli** [microsoft/vscode-remote-release#330]
Issue Type: <b>Performance Issue</b>

Followed the instructuions  on how to open code-insiders  acording the documentations

Extension version: 0.35.0
VS Code version: Code - Insiders 1.34.20-insider (57b550c559b945eb9d871dbf2b2e4cb9e31e2551, 2019-05-10T17:36:45.765Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.4.0-17134-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (2.46GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+default/mnt/c/Users/marel/Documents/Facultad/EDyAL/Practica3 --remote=wsl+default|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17134-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.79GB (2.46GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    74	 14324	code-insiders main
    0	    59	  6328	   shared-process
    1	    67	 13968	   window (Issue Reporter)
    0	   221	 16440	   window (scolas.c - Practica3 [WSL] - Visual Studio Code - Insiders)
    0	    51	 18764	     extensionHost
    0	    14	 15284	       electron_node wslDaemon.js 
    0	     4	 21804	         C:\WINDOWS\System32\wsl.exe bash -i -c "./scripts/wslServer.sh 57b550c559b945eb9d871dbf2b2e4cb9e31e2551 insider .vscode-remote  "
    0	     4	 15028	           C:\WINDOWS\System32\lxss\wslhost.exe {46c62b7a-b5fe-48f8-b328-b591554054ff} 400 384 388
    0	     5	 18956	             console-window-host (Windows internal process)
    0	     4	 21856	           console-window-host (Windows internal process)
    0	   606	 21212	   gpu-process

Remote: WSL
CPU %	Mem MB	   PID	Process
    0	     0	  2993	remote agent
    0	     0	  3006	   extensionHost
    0	     0	  3029	     /bin/bash
    0	     0	  3120	       zsh
    0	     0	  3049	     /home/bautistamarelli/.vscode-remote/extensions/ms-vscode.cpptools-0.23.0/bin/Microsoft.VSCode.CPP.Extension.linux
    0	     0	  4231	       /home/bautistamarelli/.vscode-remote/extensions/ms-vscode.cpptools-0.23.0/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 3049 18
    0	     0	  4449	       /home/bautistamarelli/.vscode-remote/extensions/ms-vscode.cpptools-0.23.0/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 3049 24
    0	     0	  3114	     /home/bautistamarelli/.vscode-remote/bin/57b550c559b945eb9d871dbf2b2e4cb9e31e2551/node /home/bautistamarelli/.vscode-remote/bin/57b550c559b945eb9d871dbf2b2e4cb9e31e2551/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=3006
    0	     0	  3016	   watcherService
    0	     0	  4467	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  4468	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: WSL|    Folder (Practica3): 75 files|      File types: bin(24) ipch(20) c(10) h(4) json(4) o(2) sh(1) txt(1)
|                  sqlite(1) config(1)
|      Conf files: makefile(1) settings.json(1);
```

</details>

**Comment by aeschli** [comment]
@BMarelli Can you paste the link of the instructions you followed? SSH, dev container or WSL?

**Comment by BMarelli** [comment]
https://code.visualstudio.com/docs/remote/wsl

**Comment by aeschli** [comment]
In the progress notification, can you click Details to see where the time is spent? Updating the server or starting it?

**Comment by BMarelli** [comment]
Actually the problem is that when i launch vscode-insiders from within wsl, i have to wait about 5 mins at the terminal before vscode even opens.
Also others commands are slow to run

**Comment by aeschli** [comment]
It's a general issue with WSL?

**Comment by aeschli** [comment]
When starting up, please click on `Details` and open the WSL terminal and see where the time is spent...
