### ISSUE TITLE
Clone in Volume guidance doc link

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#3302]
Verified on macOS, really cool feature 👍 

Maybe this can be clarified here, can open issue if needed. The guidance notification to clone in volume currently has a link to https://code.visualstudio.com/docs/remote/containers , wouldn't it be better to point to the part of documentation that talks about the difference between cloning in a volume vs opening in a container ?

_Originally posted by @deepak1556 in https://github.com/microsoft/vscode-remote-release/issues/3265#issuecomment-652164688_

**Comment by chrmarti** [comment]
@Chuxel Can we have an additional section in the docs to link to that explains 'Clone in Volume'?

**Comment by egamma** [comment]
... and the difference to 'Open Folder in Container'. It should explain the perf improvements that are mentioned in the notification:

![image](https://user-images.githubusercontent.com/172399/86232476-4a0ad800-bb94-11ea-9cfd-ae798d6124b1.png)

**Comment by Chuxel** [comment]
I created https://aka.ms/vscode-remote/containers/open-repo to point to "Quick start: Open a Git repository or GitHub PR in an isolated container volume". It specifically calls out the advantages of a volume and has a link to advanced docs on using volumes to improve performance.

**Comment by chrmarti** [comment]
Updated:
![image](https://user-images.githubusercontent.com/9205389/86326578-37e77300-bc42-11ea-8134-9d8ab9aadc27.png)
