### ISSUE TITLE
Cannot launch a debugging configuration in WSL due to inability to find the manifest.json

### ISSUE THREAD

**Issue by Xeoth** [microsoft/vscode-remote-release#3305]
Issue Type: <b>Bug</b>

I cannot use a launch configuration, as an ENOENT error saying "no such file or directory" is thrown.

## Steps to reproduce

1. Connect to WSL
2. Make a debugging configuration (I used the "Launch WebExtension" one, shown below)
3. Select the configuration in the "Run" section
4. Click the green triangle "play" button

I assume it's because `C:\mnt\...` does not actually exist and is just being "simulated" by WSL.

The launch.json configuration:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch WebExtension",
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "addonPath": "${workspaceFolder}/extension"
        }
    ]
}

```
Extension version: 0.44.4
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

**Comment by weinand** [comment]
Do you see the same problem when you try to launch a "node" launch configuration?

I suspect that the "Firefox" application wants to run in the UI and it does not make sense to run it in (non-UI) WSL.
