### ISSUE TITLE
Unable to use cmake tools.

### ISSUE THREAD

**Issue by IkonOne** [microsoft/vscode-remote-release#3306]
Issue Type: <b>Bug</b>

I am posting this issue here and not in the cmake-tools repo because it is only present while trying to configure a remote project.

Steps to reproduce:

On a Windows 10 machine running OpenSSH server, have a cmake project that builds and runs when using vscode with cmake-tools locally.
On a mac, connect to the windows 10 machine using remote-ssh and try to configure.
It fails with an error along the lines of 'command "cmake.configure" DNE'.

Extension version: 0.51.0
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0
Remote OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|8.00GB (1.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.0.3|
|OS|Windows_NT x64 10.0.18362|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|7.92GB (4.31GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Sorry for the slow response. If this is still an issue, make sure that extension is installed on the remote, not just locally, or file an issue on their repo to investigate.
