### ISSUE TITLE
New SSH socket setting says dynamic forwarding is disabled - which can be a bit confusing

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#3308]
Testing #3273

The setting for the new Unix socket mode mentions that dynamic port forwarding is disabled.

![image](https://user-images.githubusercontent.com/312252/86420707-48bcd680-bc8c-11ea-9c93-0164d8b6b40d.png)

At first I thought this was a reference to "Forward a Port" not working. Perhaps this should say something like "Disables all connection multiplexing related settings (local server, dynamic forwarding)"?

**Comment by Chuxel** [comment]
BTW - I should say that it works great otherwise!

**Comment by roblourens** [comment]
Hm yeah it is confusing, maybe I just shouldn't try to describe that part in the description but can spell it out more in the docs/release notes.
