### ISSUE TITLE
Issue while adding Folder to workspace after attaching to container

### ISSUE THREAD

**Issue by sujathaganti** [microsoft/vscode-remote-release#3309]
Issue Type: <b>Bug</b>

Hello , 
I am getting below error when i try to do "FILE->Add folder to Workspace"  after attaching to docker container.  I have installed Remote container plugin priorily.

What could be the cause of issue?

[19 ms] Start: Resolving remote
[21 ms] Setting up container /ACSF_SINPE_1

[21 ms] Start: Run: docker inspect --type container /ACSF_SINPE_1
[79 ms] Error: Can not add index to parent of type property
        at m (/Users/sujathaganti/.vscode/extensions/ms-vscode-remote.remote-containers-0.122.1/dist/extension.js:1:87447)
        at Module.T (/Users/sujathaganti/.vscode/extensions/ms-vscode-remote.remote-containers-0.122.1/dist/extension.js:1:92158)
        at /Users/sujathaganti/.vscode/extensions/ms-vscode-remote.remote-containers-0.122.1/dist/extension.js:1:666642

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 18.7.0
Fetching remote diagnostics for 'Container' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'Container' failed.
</details>Extensions: none

**Comment by wangjia1990** [comment]
I met a same problem too.

![image](https://user-images.githubusercontent.com/57082128/87003194-c4b7a100-c1ed-11ea-8490-b59dbb5c7ccd.png)

**Comment by chrmarti** [comment]
Could you open the corresponding configuration (`F1` > `Remote-Containers: Open Attached Container Configuration File...`) and post it here?

**Comment by wangjia1990** [comment]
{
	"workspaceFolder": "/autobot/openAPI-component",
	"extensions": [
		"ms-vscode.cmake-tools",
		"ms-vscode.cpptools",
		"xaver.clang-format"
	],
		"xaver.clang-format"
	]
}

**Comment by sujathaganti** [comment]
Hi All,

This issue was solved for me.
Though I couldn't tell the exact reason how it got solved,
But one change i observed was after attaching to container , to open code
folder ,
instead of doing "open *File → **Add Folder to WorkSpace , and select the
folder "*
 i clicked on "open folder" under Modem , in explorer page and then
selected the code path and surprisingly i didn't get the error.

Thanks,
Sujatha

**Comment by bamurtaugh** [comment]
Thanks for the update @sujathaganti! 

@wangjia1990 can you confirm if you're still experiencing this issue?

**Comment by chrmarti** [comment]
The JSON looks like a concurrent update might have corrupted it. Needs more thought on how this happened and how we can prevent it.

**Comment by RMacfarlane** [comment]
@chrmarti What's the best way to verify this fix?

**Comment by chrmarti** [comment]
To verify: Attach to a container and then add/remove extensions and add/remove forwarded ports concurrently and make sure the JSON (`Remote-Containers: Open Container Configuration File`) updates and remains valid.

**Comment by sbatten** [comment]
I did my best to make this happen with no luck so I will count as verified. Clearly we can reopen if others repro
