### ISSUE TITLE
NoPermissions (FileSystemError): Error: EACCES: permission denied

### ISSUE THREAD

**Issue by BenDavidson90** [microsoft/vscode-remote-release#3315]
- VSCode Version: 1.46.1
- Local OS Version: Windows 10
- Remote OS Version: Debian 10
- Remote Extension/Connection Type: SSH

Hi, I installed Remote-SSH today for editing files on my home server but got a problem:
I can't create/edit/delete files in /var/www, it throws me this error:
`Unable to write file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a224a6565646f6d227d/var/www/test' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/var/www/test')`

The directory and files are owned by www-data but my user is in the www-data group and permissions seems good:  rwxrwxr-x
I can create/edit/delete files when i ssh from cmd with the same user but nothing with VSCode.

If i change permission to 777 it works but it's not a solution for me.

**Comment by jayjansheski** [comment]
I'm having this problem as well; the issue for me is that I'm ssh-ing with `ec2-user` but I need to `sudo su another-user` once I'm connected in order to have the proper permissions. I'm able to successfully switch users in the terminal of VSCode, but it seems the editor is still using `ec2-user`.

**Comment by Chuxel** [comment]
@roblourens Is there anything here that would cause group permissions not to be applied when saving a file?

**Comment by roblourens** [comment]
If I understand correctly this sounds the same as https://github.com/microsoft/vscode-remote-release/issues/3399 @bpasero 

I went through the full repro steps on that issue, and it works fine for me.

![image](https://user-images.githubusercontent.com/323878/88254092-e9d5f600-cc68-11ea-85c5-a44e1115e46f.png)

Does this look like I am running the same scenario as you?

**Comment by Herms24** [comment]
Hey try this out

https://youtu.be/DwdRm18NaC8

I made a video, had the same error. 

Try going into the file your having issues with, should be in a hidden file, and simply type in terminal after that: 
 sudo chown -R <username> <directory_name>


Worked perfectly for me.
