### ISSUE TITLE
Windows CMD Integration

### ISSUE THREAD

**Issue by georgekrax** [microsoft/vscode-remote-release#3317]
I am currently using **WSL 2** with **Ubuntu 20.04**, in my Windows operating system. But I found out that WSL, makes development with **Node.js** extremely slow (about 2 minutes to start an **Express** server). So, I tried it out with the regular CMD of Windows (10), and it worked in just 15 seconds only. So I would like to use **WSL Remote** in **VS Code**, but also the regular **CMD** of Windows. I have not found a solution till now, as when I am asked to select the default integrated terminal, it only shows me a list with **bash**, **sh**, **fish** etc. So, I would like to ask if I can use in **WSL Remove** both the **fish** & the **CMD** terminals, in the same window and workspace. For now, I will need to have opened another CMD window open, separately from VS Code.

Is there any way this can be done in the future? Or, can I actually solve my issue, with some configurations?

**I appreciate every help and answer**

**Comment by georgekrax** [comment]
Well, I managed to **solve my issue**, by returning to **WSL 1**, but it would still be nice in the **VS Code** to both work on the **Windows CMD** and simultaneously in* *Ubuntu**.

*I will try to return to **WSL 2 **, and test again the integration, if it is fast like **WSL 1**

**Comment by PavelSosin-320** [comment]
In the new WSL 2 if you have CMD you have Linux shell, bash, any, via wsl ,,,
If you have Linux shell you have Command via program.exe or powershell.exe .... - interoperability!

**Comment by georgekrax** [comment]
Thanks for the help! But I found that **WSL 1**, was the problem, as it was making everything **5x - 10x** times slower!
