### ISSUE TITLE
Open GitHub URL instead of built-in devcontainer.json

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#3322]
To avoid having users edit the built-in config which is lost when the extension updates.

**Comment by roblourens** [comment]
I'm not sure when a configuration is "built-in"

**Comment by chrmarti** [comment]
We bake in a few configurations: https://github.com/microsoft/vscode-dev-containers/tree/master/repository-containers/github.com

Verification:
- Clone, e.g., Azure Account: `git clone https://github.com/microsoft/vscode-azure-account.git`.
- Open folder and verify that the 'Reopen in Container' notification is shown with a link at the top opening the devcontainer.json in the browser:
![image](https://user-images.githubusercontent.com/9205389/87132210-d3599300-c295-11ea-9560-e29470a5dd3e.png)

Note: If the notification doesn't show, you might have turned it off in the past. Run the command `Remote-Containers: Reset Don't Show Reopen Notification` and reload the window.
