### ISSUE TITLE
Remote Container does not respect workspace's integrated shell setting

### ISSUE THREAD

**Issue by lephuongbg** [microsoft/vscode-remote-release#3323]
- VSCode Version: 1.46.1
- OS Version: Ubuntu 18.04
- Name of Dev Container Definition with Issue:

**Steps to Reproduce:**

1. Set User Setting's `terminal.integrated.shell.linux` to **/usr/bin/fish**
2. Try "Open Repository in Container", then use "microsoft/vscode-remote-try-python".
3. Remove Remote's User Setting' `terminal.integrated.shell.linux` config.
2. Set Workspace Setting's `terminal.integrated.shell.linux` to **/bin/bash**.
3. Open integrated terminal.

**Expected result:**

Terminal opens with bash shell.

**Actual result:**

Terminal can not be opened with error: _The terminal shell path "/usr/bin/fish" does not exist_.

**Comment by Chuxel** [comment]
@sandy081 @chrmarti Workspace settings should override container specific settings, correct?

@lephuongbg How did you update the remote setting in step 3? Updating devcontainer.json will not cause it to take effect unless you "Rebuild". However, if you updated it via the Remote tab in the Settings UI in VS Code, it should take effect on reconnect.

**Comment by lephuongbg** [comment]
@Chuxel I did it by following the settings page from here:

![image](https://user-images.githubusercontent.com/1001176/86711967-796b8a00-c057-11ea-96de-a9051acc634c.png)

to here:

![image](https://user-images.githubusercontent.com/1001176/86711866-6062d900-c057-11ea-86d1-0917128f6561.png)

**Comment by lephuongbg** [comment]
> However, if you updated it via the Remote tab in the Settings UI in VS Code, it should take effect on reconnect.

As I can see, it takes effect immediately in this case. If I comment out the line in Remote Setting, I can not open any new terminal on the same remote session. The same when I revert Remote Setting's shell back to /bin/bash, I can open new terminal right away.

**Comment by chrmarti** [comment]
You need to first allow the workspace settings to overwrite shell with `F1` > `Terminal: Manage Workspace Shell Permissions`. (A security measure for when the workspace file is from a repository.)

Does that make it work?

**Comment by lephuongbg** [comment]
That does work 🎉, thanks a lot. 

P/S: So it's actually not a Remote Container's problem then, just that it's seldomly needed to set workspace-level shell config for non-remote projects. If only there was a notice when user tried to set workspace-level shell settings, that would be a lot of time saved.

**Comment by chrmarti** [comment]
When I tried this I got a notification asking me if I want to allow or disallow the workspace setting. Maybe you had disallowed that previously and the notification no longer showed. (Or there is a bug with when the notification shows.)
