### ISSUE TITLE
"Clone in volume" warning should be modal

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#3325]
I clicked "clone in volume" and was confused for a bit because it seemed like nothing had happened. Then I realized it was waiting on a notification (the one that says "Local changes not pushed to the Git remote will not be available in the Docker volume"). I actually had a several notifications at the time due to opening with a new user-data-dir and took me a second to realize what was going on. Since this blocks opening, I think it should be modal.

**Comment by chrmarti** [comment]
There is another secondary notification when you click `Don't Show Again` asking if you want to hide only for this or for all folders. Would you make this modal too?

I have avoided modal message dialogs because the user's focus is already on notifications.

**Comment by roblourens** [comment]
If it's blocking opening the folder, it seems like it should be modal, but I don't know

> because the user's focus is already on notifications

Yeah I guess that's true, it was probably an unusual case that I was in where I had a long list of notifications already

**Comment by chrmarti** [comment]
Closing with the above reasoning. Thanks.
