### ISSUE TITLE
Upcoming: "Attach Visual Studio Code" will fail on ACI containers

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-remote-release#3327]
Related to #88. The Docker extension is adding support for ACI containers in https://github.com/microsoft/vscode-docker/issues/2102. The context menu for "Attach Visual Studio Code" still appears (because the context value hasn't changed), but trying it fails:
![image](https://user-images.githubusercontent.com/36966225/86806980-681a8180-c047-11ea-8762-937bd010be4c.png)

Ideally, "Attach Visual Studio Code" would work (i.e. #88) but if that is not yet feasible then the option should probably be hidden.

We (the Docker extension team) don't plan to change the context values on the container nodes, but we will probably add new contexts using the `setContext` command. When we get further along I will update this issue with that. Assuming new contexts are added the Remote - Containers extension could hide the "Attach Visual Studio Code" command from the context menu when a given context is present/absent.

**Comment by karolz-ms** [comment]
The new context value is available now; it is called `vscode-docker:aciContext`. When `vscode-docker:aciContext` is true, the "Attach Viusal Studio Code" command should **NOT** be shown.

[The change that introduced the new context value](https://github.com/microsoft/vscode-docker/commit/5f32d26fe331ddc34b5a40fb2f34ac84dae47cac)

**Comment by bwateratmsft** [comment]
Here is an example of it in action:
https://github.com/microsoft/vscode-docker/blob/7620a9881737c55ef1a1e5e3645af0159dc47362/package.json#L367-L371

**Comment by Chuxel** [comment]
Just to double check - we're using the pure Docker CLI now, so technically this should work. Is there a reason explicitly not to show it rather than fix it?

**Comment by karolz-ms** [comment]
I am not super familiar with how VS Code local-to-remote bridge works, but given that the container runs on Azure Container Instances (ACI) with no public connectivity beyond app port(s) (which are taken by the container's main process), I don't think VS Code will have the opportunity to inject itself into the container and set up the bridge?

**Comment by bwateratmsft** [comment]
@Chuxel It won't work unfortunately; limitations in ACI make it impossible. The most immediate error is this:
![image](https://user-images.githubusercontent.com/36966225/87723915-850e2d80-c788-11ea-9373-337deff22f82.png)

More importantly though, ACI does not support any arguments to `docker exec` calls beyond the initial executable. So, you can do `docker exec -it sh`, but you _cannot_ do `docker exec -it echo hello`. I assume Remote - Containers uses this functionality.

**Comment by Chuxel** [comment]
Yeah, it's CLI limitations rather than the remoteness that is the problem. We make extensive use of `exec` for a number of things. Hopefully that resolves itself over time then.

**Comment by chrmarti** [comment]
The CLI limitation isn't new anymore, I remember having seen this quite a while ago. I'll add the check to our when clause. Thanks for the heads-up!

**Comment by RMacfarlane** [comment]
@chrmarti How do you get an azure container instance to show up in the tree? I've tried following the tutorial [here](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-tutorial-prepare-app) to build an image and have pushed it to an Azure container registry, I see the locally running container and trying to attach to it gives "Alpine Linux 3.9 or later required."

Verification steps?

**Comment by karolz-ms** [comment]
@RMacfarlane here are instructions on how to deploy a container to ACI using Docker CLI: https://docs.docker.com/engine/context/aci-integration/

The Docker view in VS Code should be able to detect Docker context change to ACI and update automatically. HTH!
