### ISSUE TITLE
Cant connect to port 7356 as a default ssh port for the guest machine.

### ISSUE THREAD

**Issue by restlessankyyy** [microsoft/vscode-remote-release#3328]
- VSCode Version: May 2020. 1.46
- OS Version: Mac OS / Win 10

Steps to Reproduce:

1. Change the SSH port of Linux VM to something else rather than generic port 22
2. Add SSH Key to your to machine
3. Try Connecting to the Linux guest machine. It will give a port error

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Did you set up an SSH config that has that port? https://code.visualstudio.com/docs/remote/ssh#_remember-hosts-and-advanced-settings

**Comment by restlessankyyy** [comment]
Didn't work for me.

**Comment by restlessankyyy** [comment]
How do you configure port in the SSH config file. Any sample or example will be much appreciated.

**Comment by roblourens** [comment]
See the link above for how to create a config file, and add a directive like `Port 1234`

more details https://man7.org/linux/man-pages/man5/ssh_config.5.html
