### ISSUE TITLE
The VS Code Server failed to start[Segmentation fault (core dumped)]

### ISSUE THREAD

**Issue by gemark** [microsoft/vscode-remote-release#3329]
- VSCode Version: 1.46.1
- Local OS Version: win10 10.0.18363 Build 18363
- Remote OS Version: VirtualBox Ubuntu 18.04 server LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

//////////////////////////////////////////////////////////////
SSH_CLIENT=192.168.137.1 9965 22
> MAIL=/var/mail/root
> SHELL=/bin/bash
> SHLVL=2
> VSCODE_AGENT_FOLDER=/root/.vscode-server
> LOGNAME=root
> XDG_RUNTIME_DIR=/run/user/0
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
> _=/usr/bin/printenv
> Starting server with command... /root/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/server.sh --host=127.0.0.1 --enable-remote-auto-shu
> tdown  --port=0 &> "/root/.vscode-server/.cd9ea6488829f560dc949a8b2fb789f3cdc05f5d.log" < /dev/null
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[12:52:41.765] > 
> 
[12:52:42.093] > Waiting for server log...
> 
[12:52:42.596] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
[12:52:42.623] > Server did not start successfully. Full server log at /root/.vscode-server/.cd9ea6488829f560dc949a8b2fb789f3cdc05f5d.log >>>
> **Segmentation fault (core dumped)**
> <<< End of server log
> 490fe632fd26##32##
[12:52:42.623] Received install output: 490fe632fd26##32##
[12:52:42.624] Resolver error: The VS Code Server failed to start
[12:52:42.632] ------

[12:52:42.721] > 
> 
[12:52:43.414] "install" terminal command done
[12:52:43.416] Install terminal quit with output: 

///////////////////////////////////////////////////////////////////
node ./out/vs/server/main.js

node[4107]: ../src/node_file.cc:561:void node::InternalModuleStat(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[0]->IsString()' failed.
 1: node::Abort() [node]
 2: 0x5555b3ecc0dd [node]
 3: 0x5555b3f0207f [node]
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
 5: 0x5555b384ab62 [node]
 6: 0x5555b384b0af [node]
 7: 0x1359223040bd
Aborted (**core dumped**)

**Comment by BrendanSimon** [comment]
Yep.  The `node` binary is definitely broken for me too.  Tried insiders and it has the same issue.  Tried removing the `.vscode-server` directory and it got reinstalled, but still the segfault happens.

**Comment by roblourens** [comment]
Sorry for the slow response. Is this still an issue?
