### ISSUE TITLE
GCC problem matcher doesn't appear to work with Remote SSH

### ISSUE THREAD

**Issue by senkumartup** [microsoft/vscode-remote-release#3333]
Unable to open 'some_ui_utils.cpp': Unable to read file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a22426161735f446f6c7068696e227d/src/ui/some_ui_utils.cpp' 
(Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a22426161735f446f6c7068696e227d/src/ui/some_ui_utils.cpp').

**Comment by roblourens** [comment]
Please open an issue with more details on the extension that provides that problem matcher
