### ISSUE TITLE
Allow copying a file from Visual Studio Code Remote SSH to a local computer

### ISSUE THREAD

**Issue by ibogosavljevic** [microsoft/vscode-remote-release#3336]
When I create a project in Visual Studio Code Remote SSH everything works fine. I compile on the remote server and as a result I get an artifact I want to inspect on my local machine. I find the artifact in the directory tree, right click on it, select copy, then I open a folder, I want to click Paste but the button is grayed out.

**Comment by lpic10** [comment]
I can download a file to my local environment if I right click it on explorer tab, then selecting "Download..."
