### ISSUE TITLE
Support mosh protocol

### ISSUE THREAD

**Issue by xatier** [microsoft/vscode-remote-release#334]
It would be nice to support mosh protocol [1] in vscode, which is extremely useful in environment with poor internet connection (such as in-flight wifi).

[1] https://mosh.org/

**Comment by wxdao** [comment]
vscode remote ssh requires ssh port forwarding to access the agent. AFAIK mosh doesn't provide such a feature.

**Comment by egamma** [comment]
@wxdao correct.
