### ISSUE TITLE
High CPU error resulting in VSCode Server for WSL closing unexpectedly

### ISSUE THREAD

**Issue by scottgemmell** [microsoft/vscode-remote-release#3340]
- VSCode Version: 1.47.0
- Local OS Version: Version 1909 (OS Build 1836.900)
- Remote OS Version: 0.44.4

- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Windows_NT x64 10.0.18363

Initially, I had an issue similar to 
https://github.com/microsoft/vscode-remote-release/issues/2921

My CPU was running very high resulting in my fans being unbearably noisy. Sounded like jet taking off after few minutes use of VSCode. I found it had something to do with VSCode extension "Remote - WSL" .

I tried the steps suggested in comments for 2921
`wget "https://launchpadlibrarian.net/474302949/libc6_2.31-0ubuntu8+lp1871129~1_amd64.deb"`
`sudo dpkg -i libc6_2.31-0ubuntu8+lp1871129~1_amd64.deb`

and it seemed good. I could open Vscode with the extension running and I heard no increased noise. However, once last night and several times this morning I get a big blue screen saying my PC was restarting after uploading error info to Windows. There was stop code: KERNEL_SECURITY_FAILURE.

I got the blue screen while using terminal in vscode.

After the latest restart, when WSL extension is running I get an error from Vscode. I will attach an image.
![g2fPe7n 1](https://user-images.githubusercontent.com/6575117/87136631-ac9a5d00-c293-11ea-8c62-5a824b9d2ef7.png)
![QXO3l17 1](https://user-images.githubusercontent.com/6575117/87135904-a35cc080-c292-11ea-95ef-1ef6add701b4.jpeg)

I am blocked from working at the [moment.](url) Any help greatly appreciated.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
Hey @scottgemmell, thanks for the details here. Are you still experiencing this issue? I was going to recommend looking into #2921, but I see you already have.

**Comment by bamurtaugh** [comment]
Set of CPU usage/performance issues: 

https://github.com/microsoft/vscode-remote-release/issues/3434
https://github.com/microsoft/vscode-remote-release/issues/3161
https://github.com/microsoft/vscode-remote-release/issues/3195
https://github.com/microsoft/vscode-remote-release/issues/3340

Some solution info that worked for some folks:
https://github.com/microsoft/vscode-remote-release/issues/2921#issuecomment-624564199
https://github.com/microsoft/vscode/issues/97568
