### ISSUE TITLE
SSH "Forwarded Ports" disappears after selecting "Containers"

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode-remote-release#3341]
Version: 1.47.0 (user setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
- VSCode Version: 1.47.0
- Local OS Version: Windows 10 latest
- Remote OS Version: Ubuntu 16.04.1
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.  open a remote window
![image](https://user-images.githubusercontent.com/1189869/87160988-73df9f80-c2f6-11ea-8c75-2a4ad19c1287.png)

2. select "Containers"
![image](https://user-images.githubusercontent.com/1189869/87161030-80fc8e80-c2f6-11ea-834d-471d5f883bb5.png)

 Containers replaces port forwarding and the menu stuck at "ssh targets".

Also I sometimes see duplicate menu on reload window:

![image](https://user-images.githubusercontent.com/1189869/87161651-6a0a6c00-c2f7-11ea-8607-b1fed7c8d5e8.png)

**Comment by roblourens** [comment]
Sorry for the slow response. We've made changes here, let me know if it's still an issue
