### ISSUE TITLE
Can not attach to a container

### ISSUE THREAD

**Issue by BaroDevelopment** [microsoft/vscode-remote-release#3343]
disIssue Type: <b>Bug</b>

I gave the Docker app all permissions but still can not attach to it.
![Image](https://cdn.discordapp.com/attachments/730722064402481252/731157406138237028/unknown.png)

It says in the logs that it is lacking some permissions which is weird since i gave Docker and VSC all permissions possible.
I am using a Mac. 💻 

Extension version: 0.128.0
VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:01:54.115Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.49GB free)|
|Process Argv|-psn_0_278596|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
What are the ownership and permissions on the ~/.ssh folder from within the container?

**Comment by BaroDevelopment** [comment]
I used  inside the container the following **sudo chmod 777 .ssh/** and it worked - thanks!
