### ISSUE TITLE
SSH-Remote connection trouble

### ISSUE THREAD

**Issue by Daniel4774** [microsoft/vscode-remote-release#3346]
Issue Type: <b>Bug</b>

Sometimes the ssh connection works, sometimes it doesnt. I connect, type in my password and then it mentions "fork", " retry" "resource temporarly unavailable". And then a white text box shows up saying that vs code has failed to start server.

VS Code version: Code - Insiders 1.48.0-insider (e7920dce7bfd0b707ebfc0a5379c6edd2233e475, 2020-07-10T11:58:37.847Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (1.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.29.0-insiders2

</details>

**Comment by roblourens** [comment]
Where do you see those messages? Could you share the log from the Remote-SSH output channel, from a time when it doesn't work?

**Comment by Daniel4774** [comment]
Yes here it is copied and pasted and here are two pictures right before typing my password to log in and after I hit enter and wait a few seconds.[12:33:31.814] Log Level: 2[12:33:31.826] remote-ssh@0.51.0[12:33:31.827] win32 x64[12:33:31.832] SSH Resolver called for "ssh-remote+systems4.cs.uic.edu", attempt 1[12:33:31.832] SSH Resolver called for host: systems4.cs.uic.edu[12:33:31.833] Setting up SSH remote "systems4.cs.uic.edu"[12:33:31.908] Using commit id "e7920dce7bfd0b707ebfc0a5379c6edd2233e475" and quality "insider" for server[12:33:31.911] Install and start server if needed[12:33:33.716] Checking ssh with "ssh -V"[12:33:33.831] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5[12:33:33.838] Running script with connection command: ssh -T -D 52251 systems4.cs.uic.edu bash[12:33:33.851] Terminal shell path: C:\WINDOWS\System32\cmd.exe[12:33:33.943] > > > > > > > > > > > > > > > > > > > > > > > > ]0;C:\WINDOWS\System32\cmd.exe[12:33:33.943] Got some output, clearing connection timeout[12:33:33.953] > > > > > > > > > > > > > > > > > > > > > > > > [12:33:34.243] > dflore36@systems4.cs.uic.edu's password: [12:33:34.245] Showing password prompt[12:34:46.208] Got password response[12:34:46.209] "install" wrote data to terminal: "*************"[12:34:46.228] > > [12:34:47.626] > c94081c12813: running> [12:34:47.632] > bash: fork: retry: Resource temporarily unavailable> [12:34:48.775] > bash: fork: retry: Resource temporarily unavailable> [12:34:50.744] > bash: fork: retry: Resource temporarily unavailable> [12:34:51.857] > bash: fork: retry: Resource temporarily unavailable> [12:34:53.695] > Acquiring lock on /AD-home/dflore36/.vscode-server-insiders/bin/e7920dce7bfd0b70> 7ebfc0a5379c6edd2233e475/vscode-remote-lock.dflore36.e7920dce7bfd0b707ebfc0a5379> c6edd2233e475> [12:34:53.708] > \ln /AD-home/dflore36/.vscode-server-insiders/bin/e7920dce7bfd0b707ebfc0a5379c6e> dd2233e475/vscode-remote-lock.dflore36.e7920dce7bfd0b707ebfc0a5379c6edd2233e475.> target /AD-home/dflore36/.vscode-server-insiders/bin/e7920dce7bfd0b707ebfc0a5379> c6edd2233e475/vscode-remote-lock.dflore36.e7920dce7bfd0b707ebfc0a5379c6edd2233e4> 75> Found existing installation at /AD-home/dflore36/.vscode-server-insiders/bin/e79> 20dce7bfd0b707ebfc0a5379c6edd2233e475...> bash: fork: retry: Resource temporarily unavailable> [12:34:54.887] > bash: fork: retry: Resource temporarily unavailable> [12:34:56.774] > bash: fork: retry: Resource temporarily unavailable> [12:34:57.991] > bash: fork: retry: Resource temporarily unavailable> [12:34:59.736] > Found running server...> > *> * Reminder: You may only use this software with Visual Studio family products,> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) [12:34:59.746] > > *> > [12:34:59.757] > bash: fork: retry: Resource temporarily unavailable[12:34:59.769] > > [12:35:00.757] > bash: fork: retry: Resource temporarily unavailable> [12:35:02.699] > bash: fork: retry: Resource temporarily unavailable> [12:35:03.827] > bash: fork: retry: Resource temporarily unavailable> [12:35:05.770] > Server did not start successfully. Full server log at /AD-home/dflore36/.vscode-> server-insiders/.e7920dce7bfd0b707ebfc0a5379c6edd2233e475.log >>>> > > *[12:35:05.785] > > * Visual Studio Co<<< End of server log> c94081c12813##32##> [12:35:05.788] Received install output: c94081c12813##32##[12:35:05.792] Resolver error: The VS Code Server failed to start[12:35:05.809] ------[12:35:07.087] "install" terminal command done[12:35:07.088] Install terminal quit with output:    Two pics .. Sent from Mail for Windows 10 From: Rob LourensSent: Friday, July 10, 2020 12:01 PMTo: microsoft/vscode-remote-releaseCc: Daniel4774; AuthorSubject: Re: [microsoft/vscode-remote-release] SSH-Remote connection trouble (#3346) Where do you see those messages? Could you share the log from the Remote-SSH output channel, from a time when it doesn't work?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by roblourens** [comment]
Not sure what this implies: `bash: fork: retry: Resource temporarily unavailable`

Is it possible that you are logging into a cluster where this sort of thing is not allowed?
