### ISSUE TITLE
"Add Development Container Configuration Files" command generates wrong devcontainer.json on Windows

### ISSUE THREAD

**Issue by sarisia** [microsoft/vscode-remote-release#3350]
- VSCode Version:
- Local OS Version:

Version: 1.47.0 (user setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19645

- Remote OS Version:
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open folder which contains `docker-compose.yml` with VSCode
2. Command palette -> Remote-Containers: Add Development Container Configuration Files... -> From 'docker-compose.yml'

Above command generates `.devcontainer/devcontainer.json` which has Windows style relative path to
`docker-compose.yml` :
```json
{
	"name": "Existing Docker Compose (Extend)",

	// Update the 'dockerComposeFile' list if you have more compose files or use different names.
	// The .devcontainer/docker-compose.yml file contains any overrides you need/want to make.
	"dockerComposeFile": [
		"..\\docker-compose.yml",
		"docker-compose.yml"
	],
...
```

This devcontainer can be opened on Windows, but cannot be opened on macos or on WSL2.
`devcontainer.json` which was generated on macos or WSL2 can be opened on Windows,
so `Remote-Containers: Add Development Container Configuration Files...` command shouldn't
generate the file uses relative path which depends on local OS type.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
To verify, use Windows:
- Create a Dockerfile and a docker-compose.yml file in your local workspace folder (files can be empty).
- `F1` > `Remote-Containers: Add Development Container Configuration Files`
- Pick the existing Dockerfile or docker-compose.yml (test both).
- Verify that the created devcontainer.json uses the forward slash `/` as path separator.
