### ISSUE TITLE
Frequent disconnection from the server when multiple windows open in nested directories. 

### ISSUE THREAD

**Issue by jaepil-choi** [microsoft/vscode-remote-release#3352]
- VSCode Version: 1.47.0
- Local OS Version: Windows 10.0.19041 N/A Build 19041
- Remote OS Version:  NAME="Ubuntu" / VERSION="14.04.5 LTS, Trusty Tahr"
- Remote Extension/Connection Type: **SSH**/Docker/WSL

Steps to Reproduce:

Say A directory is inside B directory at the server. 

1. Open VSCode instance by connecting to the server via ssh and then open A directory. 
2. Open another VSCode instance by connecting to the server via ssh and then open B directory. 

Soon enough, the first window will disconnect from the server and show "connecting to remote", which never connects back and hangs forever. If you reload the window, it will be fine for a few minutes but again will crash and you'll have to reload the window, again, in perpetuity, throughout the universe. 

At first, I thought it was due to some large file changes but even if there weren't any particular file changes in the filesystem, it disconnected. Then I suspected some collision between liver server extension and other extensions but again, I didn't have any particular extensions that could possibly break server connection. (Aside from Python extension, everything else is just plain linters, prettifiers, etc.) 

Just wanted devs and people to know and give proper warning that opening multiple windows in nested directories can cause this issue. It cost me like a week to figure out and it massively impacted my productivity at work. Hope this saves other people's time dealing with this issue.  

Does this issue occur when you try this locally?: Yes/**No** The issue is disconnection from the server, so it can't be tested locally. 
Does this issue occur when you try this locally and all extensions are disabled?: Yes/**No** The same.

**Comment by jaepil-choi** [comment]
I just posted a new issue. Even though I didn't open a window in nested manner, VSCode still crashes and disconnects from the remote server.

**Comment by Chuxel** [comment]
We do not officially support Ubuntu 14.04 (we start with 16.04), so this could be related to that. Older versions of Ubuntu may not meet the minimum requirements, but its good to see you seemed to actually get connectivity working.

How powerful is the machine you are connecting to?  Do you see this when connecting to a more recent Ubuntu version?

Either way, could you post your logs?

**Comment by jaepil-choi** [comment]
@Chuxel , 

Thanks for the comment. I didn't know there was minimum OS version requirement. 
The machine(remote server) is strong enough though. It's company server so 100GB+ Ram and strong server CPU is provided. 

As for the log, you mean the log from developer's tab right? I already posted the full log in the other thread, https://github.com/microsoft/vscode-remote-release/issues/3496

For now, I'm avoiding opening multiple instance of VSCode connected to the same server. This gives me stability but it's a bit inconvenient though.

**Comment by roblourens** [comment]
There is no reason why windows would interact with each other in this case, and I can't repro an issue. Only thing I can think of is that the top window is on a very large workspace and you just hit issues with opening very large workspaces like covered in https://github.com/microsoft/vscode-remote-release/issues/1257
