### ISSUE TITLE
"Attempting to reconnect..." repeated forever. 

### ISSUE THREAD

**Issue by jaepil-choi** [microsoft/vscode-remote-release#3353]
- VSCode Version: 1.47.0
- Local OS Version: Windows 10.0.19041 N/A Build 19041
- Remote OS Version: NAME="Ubuntu" / VERSION="14.04.5 LTS, Trusty Tahr"
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1. Connect to the server via ssh and just work for < 1 minute, it will crash. 
2. Since this is obviously not a helpful reproduction steps, I'll instead attach a screenshot. 

<img width="1909" alt="vscode_endless_disconnect" src="https://user-images.githubusercontent.com/25889304/87240999-963dfe00-c459-11ea-902a-36c015f71d2f.png">

It is weird that it works on one day and it doesn't work the other day. That implies it's more of my environment's problem rather than VSCode's problem but I see tons of people saying their connection gets dropped mid-work. 

I opened the developer console to track the problem but if that's not enough, please tell me how to attach more detailed logs. 

Thank you. 

This is ongoing issue and it keeps happening. I attached another log screenshot, this time unfolded all warning logs. 

<img width="411" alt="vscode_error_log_magnified" src="https://user-images.githubusercontent.com/25889304/87241192-8aebd200-c45b-11ea-94d3-1b32d41b1c71.png">

Does this issue occur when you try this locally?: Yes/**No** It's remote server connection issue. Thus I can't try it locally. 
Does this issue occur when you try this locally and all extensions are disabled?: Yes/**No**

**Comment by EricChen1248** [comment]
I've been having the same issue since about 2 weeks ago. Gotten quite annoying.

I've tried disabling all the extensions that I don't *need* to work. This is the remaining list

```Python
Pylance
Remote SSH
Remote SSH: Editing Configuration File
C#
vscode-icons
ASP.NET Core switcher
Docker
SQLTools
SQLTools MySQL/MariaDB
Visual Studio Intellicode```

It's also definitely not a network issue because I have both an external database viewer and a terminal open to HTOP connected to the server that never breaks connection, and my colleague sitting right beside me on the same connection also connects to the server just fine.

**Comment by jaepil-choi** [comment]
@EricChen1248 

Agreed. 
I have putty Tmux open at the same time and it never loses connection. 
I suspect large filespace that has frequent io. When there's high io, it almost definitely dies.

**Comment by jaepil-choi** [comment]
Upon connection, VSCode says 

"Unable to watch for file changes in this large workspace. Please follow the instructions link to resolve this issue."

which is explained in detail at: https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc

I'd like to try limiting the file watcher's scope. I think it is currently trying to watch ALL the files in the server, not just my files in a small directory. 

Official documentatoin says: 

--------------------------------------
Another option is to exclude specific workspace directories from the VS Code file watcher with the files.watcherExclude setting. The default for files.watcherExclude excludes node_modules and some folders under .git, but you can add other directories that you don't want VS Code to track.

"files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/*/**": true
  }
-------------------------------------

But my question is: 

1. Where does file watcher "watch"? In what scope? Does it attempt to watch ALL the files in the server? 
2. When I added this settings (actually, only below 2 lines) to .vscode/settings.json, file watcher warning STOPPED popping out. 

    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/*/**": true,
        "**/.hg/store/**": true,

        **"/**": true,
        "/home/my-user-name-john-doe/**": false**
      }

I was trying to say: "Hey VSCode, stop watching all the file changes in the / root directories and only focus on MY directory." 

Did I make myself clear here? Is the above settings does exactly what I was trying to say? 


UPDATE: 
Even though VSCode file watcher no longer pops too large workspace error, ssh disconnects like crazy. It makes no difference :( 
I

**Comment by jaepil-choi** [comment]
I disabled all extensions and started to open one by one to find the culprit and when I did, the server disconnection issue was gone. 

Previously, I had anaconda extension on VSCode and the server's interpreter was also anaconda python. Maybe that's what unexpectedly terminated extension host and disconnected ssh all the time? 

Not sure, but enabling only minimum extensions solved the issue on my end. 

However, @EricChen1248 didn't have Anaconda installed and still experienced the issue so I might be wrong.

**Comment by EricChen1248** [comment]
Did it work fine for you yesterday? I got 2 disconnected the whole day two days ago, and not a single disconnected today. Maybe you could try reinstalling anaconda. Based on the timing on both of our ends, I think it's more likely it's something we have in common being updated yesterday.

**Comment by jaepil-choi** [comment]
@EricChen1248 Maybe I could, but I don't really need Anaconda extension in my server env so I kept it disabled for good... No problem since the posting and everything's good to go. 

When some other extension kills the extension host, remote gets disconnected because of course, Remote SSH is also a part of the extension host. I think MS could consider implementing Remote SSH separately from the extension host so that the connection doesn't die because of one lousy extension.
