### ISSUE TITLE
Reopen locally from dev container on WSL doesn't go back to WSL remote

### ISSUE THREAD

**Issue by johnnyhuy** [microsoft/vscode-remote-release#3354]
- VSCode Version: 1.46.1
- Local OS Version: Windows 10.0.19041 Build 19041
- Name of Dev Container Definition with Issue: Reopen locally from dev container on WSL doesn't go back to WSL remote

## Steps to Reproduce

1. Open a project via WSL remote that has dev container setup
2. Build and open in dev container
3. Reopen back to local and it goes to the Windows filesystem view of the project

It's expected to go back to the WSL remote view instead.

### Open into dev container in WSL remote

![image](https://user-images.githubusercontent.com/27847622/87238624-4f93d800-c448-11ea-87e8-b96325e8f321.png)

### Reopen locally

![image](https://user-images.githubusercontent.com/27847622/87238605-f75cd600-c447-11ea-85da-d361cad96f8e.png)

### Doesn't return back to WSL remote

![image](https://user-images.githubusercontent.com/27847622/87238611-1e1b0c80-c448-11ea-91dc-c6fe3346e8cd.png)

## Notes

- WSL 2 in use
- Ubuntu 20 installed on WSL 2
- Docker WSL 2 backend

**Comment by Chuxel** [comment]
//cc: @chrmarti @aeschli

**Comment by chrmarti** [comment]
There is a Reopen in WSL command doing what you suggest.

**Comment by johnnyhuy** [comment]
Apologies but I can't seem to find it under my command menu.

![image](https://user-images.githubusercontent.com/27847622/87553778-acb4b580-c6f6-11ea-8d0c-bc8459b9b6b7.png)

**Comment by chrmarti** [comment]
Not sure why that wouldn't show up. Are you on latest version of the Remote-Containers extension?

**Comment by johnnyhuy** [comment]
I'm on the latest Remote-Container extension `v0.128.0`. It looks like I can reopen locally and then the `Remote-WSL: Reopen folder in WSL` button would appear. I can't seem to replicate that behaviour in the remote container as it would intermittently appear.

![image](https://user-images.githubusercontent.com/27847622/89025949-1e356a80-d36b-11ea-91a0-56ceca8d7f15.png)

**Comment by chrmarti** [comment]
Which commands do you get when clicking on the lower-left green remote indicator while connected to the container?

**Comment by johnnyhuy** [comment]
Hey, I'll close this one off. No further action required. Thanks for the assistance 🙂
