### ISSUE TITLE
Retain remote session when coming back to VSCode from computer sleep

### ISSUE THREAD

**Issue by tigerinus** [microsoft/vscode-remote-release#3355]
I've read https://github.com/microsoft/vscode/issues/35118 and I am using tmux as a workaround as of now.

However, the problem is I often have several projects open in several VSCode windows.

Everytime I come back from lunch and wake up the computer, I have to attach to the right tmux session from window to window. Another scenario I hate is I have to close my laptop and run to a meeting, then wake up the laptop. Because of this I hesitate to bring my laptop around or I keep my laptop open and hope the wifi network is not disconnected.

Also there are things that cannot be worked around via tmux. E.g. debug session, running task, etc.

It'd be nice to introduce a concept of session in vscode-server to make it stateful.

Thanks for looking into this feature request.

**Comment by roblourens** [comment]
So it should actually be able to reconnect to the same session with your open terminals and debug sessions, within 3 hours. I assume your lunch breaks are shorter than that.

When this happens do you get a message that says "reconnection failed" or something like that, and a prompt to reload the window? Do you ever get a reconnection dialog/progress bar that does successfully reconnect?

**Comment by tigerinus** [comment]
> So it should actually be able to reconnect to the same session with your open terminals and debug sessions, within 3 hours. I assume your lunch breaks are shorter than that.
> 
> When this happens do you get a message that says "reconnection failed" or something like that, and a prompt to reload the window? Do you ever get a reconnection dialog/progress bar that does successfully reconnect?

Yes I got reconnect and reloaded the window, but all my previous SSH sessions are gone (if not using tmux trick).

I guess I have to separate the question into two:

1. Debug and long running task via SSH - are these two scenarios resume-able after resuming the computer from sleep or network disconnection? (are you talking about this?)

2. Integrated terminal sessions via SSH (not using tmux) - is this resume-able after resuming the computer from sleep or network disconnection? (obviously it doesn't work the way expected)

**Comment by roblourens** [comment]
> Yes I got reconnect and reloaded the window

All of this is reconnectable, but you should only be prompted to reconnect if reconnection fails. We can look at the log to try to figure out why it is failing for you.

- Connect to your remote
- Run the command "Open extension logs folder" (under the command palette, F1)
- Find the "Remote -  SSH.log" for your window based on the timestamp
- Reproduce this issue
- Check the log for errors/share it with me
- And if there is nothing interesting in that log, we can check the log in the "Log (Window)" output channel in vscode.

**Comment by tigerinus** [comment]
> > Yes I got reconnect and reloaded the window
> 
> All of this is reconnectable, but you should only be prompted to reconnect if reconnection fails. We can look at the log to try to figure out why it is failing for you.
> 
> * Connect to your remote
> * Run the command "Open extension logs folder" (under the command palette, F1)
> * Find the "Remote -  SSH.log" for your window based on the timestamp
> * Reproduce this issue
> * Check the log for errors/share it with me
> * And if there is nothing interesting in that log, we can check the log in the "Log (Window)" output channel in vscode.

Sorry but I don't think you know what I am talking about. 

To be extremely clear, let list 3 scenarios:

1 - debugging via SSH
2 - long running task via SSH
3 - terminal session via SSH

I think you are talking about 1, but not 2 and 3. Can you at least confirm before I go and try? 

I really doubt it works for 2 and 3. I believe @Tyriar knows what I am talking about.

**Comment by tigerinus** [comment]
I understand implementation-wise these scenarios might have different dev ownerships. But as a user, being able to resume my coding work (debugging, long running task, terminal sessions with command history, etc.) at anytime is one single atomic feature.

I feel this feature needs attention from a PM first, since it potentially requires architectural change to vscode-server. My bet is if this needs to happen, vscode-server must have something like tmux built-in.

It doesn't have to happen anytime soon because I understand the challenge. I just want to make sure the problem itself is well understood before postponing or closing this feature request.

**Comment by roblourens** [comment]
Yeah, I am talking about all of those scenarios, they are all designed and PM'd and implemented and I'm trying to figure out why reconnection is not working for you.

**Comment by tigerinus** [comment]
> Yeah, I am talking about all of those scenarios, they are all designed and PM'd and implemented and I'm trying to figure out why reconnection is not working for you.

OK. A very simple repro for 3:

1) type some command like `top` in the integrated terminal via SSH.
2) disconnect from network and reconnect
3) reload the window like you said

Expect: `top` is still running
Actual: `top` is gone.

**Comment by roblourens** [comment]
Yes, that is the problem that you are describing. And in the working scenario, it would reconnect and you would not have to reload the window. But in your case it seems like it is failing to reconnect and so you have to reload the window. If you reload the window, it will never reconnect.

**Comment by tigerinus** [comment]
Yes, this feature request is asking for that I can always reconnect and resume my remote development work without worrying about any condition.

**Comment by roblourens** [comment]
I understand that. I can't argue about this anymore. I am just asking for help in diagnosing the issue. https://github.com/microsoft/vscode-remote-release/issues/3355#issuecomment-657264137

**Comment by tigerinus** [comment]
> I understand that. I can't argue about this anymore. I am just asking for help in diagnosing the issue. [#3355 (comment)](https://github.com/microsoft/vscode-remote-release/issues/3355#issuecomment-657264137)

The 'reconnect' scenario (instead of reloading) works fine within 3hrs.

For other scenarios like reloading, VScode update restart, come back to work next day, etc., the state is not retained. And there is not much relevant error in the log.

**Comment by PavelSosin-320** [comment]
Just for reference - [Statefull terminal](https://eternalterminal.dev/)  which keeps sessions alive over disconnections.

**Comment by roblourens** [comment]
I see. This is not supported, and is not likely to be supported for technical limitations. Earlier you said that it happens over a lunch break which made me think there was a different issue.
