### ISSUE TITLE
Erroneous "Disconnected from SSH" status and eternal "Attempting to reconnect", but everything else works

### ISSUE THREAD

**Issue by munael** [microsoft/vscode-remote-release#3358]
- VSCode Version: 1.48.0-insider ; 2020-07-10
- Local OS Version: Windows 10, v1909
- Remote OS Version: Ubuntu 16.04 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Have a spotty internet connection
2. Open a moderately large remote workspace
3. Open settings and search for "color"
4. Switch to "remote" version of settings
5. Change the color theme (for remote only) to something else
6. VSCode should go say it's disconnected and try reconnecting now
7. If all goes "well", you can dismiss the message (to the bottom right corner) and continue using VSC, opening files and so on. Terminals are fine as well.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes (but don't have an easy repro for that)

**Comment by rzhao271** [comment]
Closing this issue for housekeeping. 
@munael this issue also seems it'd be hard to reproduce, but please reply if this issue still occurs for you on the latest version of VS Code (preferably Insiders edition).
