### ISSUE TITLE
Add uri parameter to openFolder command

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#336]

**Comment by egamma** [comment]
//fyi @Chuxel this request came through you.

**Comment by Chuxel** [comment]
//cc: @ArthurMa1978 @Sneezy  FYI - This is a replacement for the original internal issue pre-go-live.

@chrmarti FYI - The other request was for the ability to open a workspace this way, but obviously an "Open Workspace in Container..." command would need to exist first. 😊

**Comment by Chuxel** [comment]
@chrmarti @egamma FYI - Raised https://github.com/microsoft/vscode-remote-release/issues/387 to make sure we've got the workspace topic covered.

**Comment by egamma** [comment]
@chrmarti any reason to keep this issue open?

**Comment by chrmarti** [comment]
No, this is in as 'remote-containers.openFolder' with `(uri?: vscode.Uri, options?: IOpenFolderAPICommandOptions)` optional arguments.
