### ISSUE TITLE
Unable to download server via corporate proxy

### ISSUE THREAD

**Issue by andrew-sumner** [microsoft/vscode-remote-release#3361]
- The linux server has no internet access so download is being done locally.
- The vscode-server.tar.gz file is an html file with a message from the proxy server stating "Please wait a moment while we launch our security service."

- VSCode Version: 1.47.0
- Local OS Version: Windows 10
- Remote OS Version: Redhat Linux
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. A linux server with no internet access
2. A authenticated proxy server

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Are you able to download extensions through vscode? If so this should have been fixed in https://github.com/microsoft/vscode-remote-release/issues/1903. Let me know if it's still an issue.
