### ISSUE TITLE
Attempting to reconnect all the time 

### ISSUE THREAD

**Issue by maruthinh** [microsoft/vscode-remote-release#3367]
Although many people have reported it, but there seems to be no proper answer to solve it. 

- VSCode Version: 1.47.1
- Local OS Version: Ubunutu 20.04 LTS
- Remote OS Version: Cent OS 7
- Remote Extension/Connection Type: SSH

At first it connects to remote hose properly but after a few seconds, sometimes, after a minutes, I get this pop-up showing attempting to reconnect. This is happening all the time. I am trying to open files in folder containing around 20 files. 

![Screenshot from 2020-07-15 10-48-44](https://user-images.githubusercontent.com/4444574/87506766-bce27b80-c689-11ea-8822-7fa6f0bf9f51.png)

**Comment by jaepil-choi** [comment]
Same here, does your remote's disconnection triggered by (or followed by) "extension host terminated unexpectedly", too?

**Comment by jaepil-choi** [comment]
@maruthinh Do you have anaconda extension enabled? When I disabled that extension, it won't get disconnected anymore.

**Comment by maruthinh** [comment]
> Same here, does your remote's disconnection triggered by (or followed by) "extension host terminated unexpectedly", too?

Yes that too happens

**Comment by maruthinh** [comment]
> @maruthinh Do you have anaconda extension enabled? When I disabled that extension, it won't get disconnected anymore.

That's interesting. I will check that. Thanks @jaepil-choi

**Comment by maruthinh** [comment]
> @maruthinh Do you have anaconda extension enabled? When I disabled that extension, it won't get disconnected anymore.

No. I have not enabled anaconda extension in vscode

**Comment by jaepil-choi** [comment]
@maruthinh Well, maybe the other extension is the culprit but the only sure-fire way to resolve this is to disable ALL extensions and enable 1 by 1, starting from Remote SSH. For me, this method made the problem go away forever. Now the connection never dies.

**Comment by roderickjonathon** [comment]
I have the same issue but on Windows 10.  It got really bad a few months ago, deleting .vscode-server and .vscode-remote which fixed it last time but it seems to have crept back. Deleting those folder no longer resolves the issue.

**Comment by maruthinh** [comment]
@roderickjonathon  Thanks a lot. I will check with that. I was frustrated so much that, I had switched to vim
