### ISSUE TITLE
Either hangs or crashes when trying to launch docker container

### ISSUE THREAD

**Issue by exal99** [microsoft/vscode-remote-release#3368]
- VSCode Version: 1.47.1
- Local OS Version: Windows 10.0.19042
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

When I try to reopen my project inside the container it usally works once. Then if i close the connection and try to open it again either (if the containers aren't runing) they crash and gives me an error:

![image](https://user-images.githubusercontent.com/20404499/87525914-704b7000-c68a-11ea-8b6e-6a54bb99231b.png)

Or if the containers are allready running it just freezes when i tries to launch:

![image](https://user-images.githubusercontent.com/20404499/87526166-c3252780-c68a-11ea-8c60-c6ccfdd4ee80.png)

I can sort of "fix" the problem by deleting my .devcontainer folder and generating a new one and relaunching it. Then it works once again but as soon as I close it I'm back to square one.

Running my containers with docker-compose from the WSL-terminal is never any problem.

**Comment by chrmarti** [comment]
Is the container you are connecting to still running when it fails? (You need to keep it running yourself when using Docker Compose.)

There is a chance this is a problem with our automatic stopping of the containers. Try adding `"shutdownAction": "none"` to the devcontainer.json to check.

**Comment by chrmarti** [comment]
Closing as we need more information from the reporter to track this down.
