### ISSUE TITLE
not able to get dev desktop id in terminal.

### ISSUE THREAD

**Issue by snemohan** [microsoft/vscode-remote-release#3370]
Issue Type: <b>Bug</b>

not able to get dev desktop id in terminal.

Extension version: 0.51.0
VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.9.184-0.1.ac.235.83.329.metal1.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev-dsk-snemohan-1c-6854235e.eu-west-1.amazon.com|
|OS|Linux x64 4.9.184-0.1.ac.235.83.329.metal1.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz (4 x 2893)|
|Memory (System)|7.31GB (1.86GB free)|
|VM|0%|
</details>

**Comment by rzhao271** [comment]
Closing for housekeeping. @snemohan feel free to reply if this issue still occurs for you on the latest version of VS Code (preferably Insiders edition). Also, if it _is_ still occurring for you there, please mention repro steps.
