### ISSUE TITLE
Extension  .exe issue

### ISSUE THREAD

**Issue by Jolsana** [microsoft/vscode-remote-release#3372]
The terminal process "C:\WINDOWS\System32\cmd.exe /c (type "C:\Users\SIGNXS~1\AppData\Local\Temp\vscode-linux-multi-line-command-" | ssh -T -D 65336) & exit /b 0" terminated with exit code: 4294967295.

**Comment by rzhao271** [comment]
Closing this issue for housekeeping. @Jolsana feel free to reply (with your setup please, and repro steps) if this issue still occurs for you on the latest VS Code (preferably Insiders edition).
