### ISSUE TITLE
Remote will make the server stuck

### ISSUE THREAD

**Issue by hzb** [microsoft/vscode-remote-release#3373]
- VSCode Version: 1.47.1 
- Local OS Version: macOS 10.15.6
- Remote OS Version: Debian 9.5
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect the remote server with SSH
2. Work on it more than some hours (I am not sure how long will this appear, what happened to me here is sometimes about four hours, sometimes about eight hours, sometimes about two hours)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

More detail:

- The remote server will be stuck, sometimes it can be automatically restored, and sometimes the server needs to be restarted.

- One of the remote servers is configured with 4 cores and 8 G of memory, and other is configured with 1 core and 1 G of memory, both of them have this issue.

**Comment by rzhao271** [comment]
Closing this issue for housekeeping. @hzb feel free to reopen this issue if it still occurs for you on the latest VS Code (preferably Insiders edition), and after checking to see if there's any timeout/keepalive settings you can set in this case.
