### ISSUE TITLE
Debugger starting up in only specific repo

### ISSUE THREAD

**Issue by tehandyb** [microsoft/vscode-remote-release#3374]
Hi when I open a new WSL window in a certain project then I get an issue with the node debugger starting up. I don't think this is an issue with the project because I have deleted everything within the project and the issue still occurs. I think there is some configuration causing the debugger to start up when I open this project. This is for node 10.17. I can start the WSL remote session from another project, then cd into the troublesome directory and there is no issue. But when I do a file > open on the troublesome directory I get the debugger issues again. Anytime I try to run any npm command the debugger will start running.

**Comment by bamurtaugh** [comment]
Hi @tehandyb, are you still experiencing this issue? If so, could you please provide a bit more information? i.e. any sort of error logs, trace-level telemetry, or screenshots of the issues you're seeing with the debugger, any additional information you may have about the troublesome project.

**Comment by tehandyb** [comment]
Hi @bamurtaugh I'm not getting the issue anymore, it just disappeared somehow :)

**Comment by bamurtaugh** [comment]
Thanks for the update @tehandyb :)
