### ISSUE TITLE
Some commands not found in VSCode remotely connection WSL2 Linux distribution 

### ISSUE THREAD

**Issue by Davidrjx** [microsoft/vscode-remote-release#3376]
In WSL2 command prompt, type 'code .',  then enter, some messages show message 'Failed to run "go env' to find GOPATH as the "go" binary cannot found in either.... Now, i am not clear what happened, could anyone has solution?

**Comment by chrmarti** [comment]
Could you append the entire output from the terminal?

**Comment by bamurtaugh** [comment]
If you're still experiencing this issue and would be able to provide the entire output from the terminal, please let us know. Thank you!

**Comment by Davidrjx** [comment]
thanks you your reply, i use debian distribution in win store as default, the result is ok.
