### ISSUE TITLE
Strange git staging behaviour when using VSCode Remote:WSL

### ISSUE THREAD

**Issue by connorhsm** [microsoft/vscode-remote-release#3378]
- VSCode Version: 1.48.0-insider (Was also occurring on 1.47.x, used insider for testing as instructed)
- Local OS Version: Windows 10 Pro 20H2
- Remote OS Version: Ubuntu 20.04 LTS (for/on WSL)
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Make multiple changes within the same file within a repository
2. With the file open, hover over the tab next to the line number, indicating that there is an unstaged change to the current repository
3. View the change and then select stage by clicking the plus icon.
4. Notice the indication of an unstaged change has now disappeared.
5. Repeating steps 2-4 to stage the next change.
6. Upon staging the next stage, notice the first item you staged, the unstaged indication has returned.

Does this issue occur when you try this locally?: No (Working as intended when Remote WSL is disabled)
Does this issue occur when you try this locally and all extensions are disabled?: No

And some other generally odd behaviour revolving around staging, such as after staging a line, the lines below are suddenly marked as an unstaged and untracked line in git?

I've reloaded VSCode each time after seeing this occur and the issue persists. I've tried across multiple repositories, two similar Python-based projects and another holding mostly bash scripts and documentation. Each time, I would reproduce this while using the WSL for VSCode and would not be able to repeat it when the VSCode window was not open using WSL or the plugin was disabled.

I find that even changes that have been staged and committed to the local repo will even show up as unstaged again after staging the next change.
I've been putting up with this for a little while, some times highlighting and selecting stage highlighted is an effective workaround, but not always. I'm a bit fed up now.

I haven't been able to find anyone else speaking about this and or can't get the right phrase of the issue.
Any help appreciated.

**Comment by adrianghc** [comment]
Is the repository that you are working with in a Windows directory?

**Comment by connorhsm** [comment]
> 
> 
> Is the repository that you are working with in a Windows directory? If so, does your problem sound like [this one](https://github.com/microsoft/vscode/issues/102243)?

Yes and yes. That recording depicts it perfectly.

Duplicate of #102243
