### ISSUE TITLE
`Could not establish connection` after password prompt wait

### ISSUE THREAD

**Issue by ychechik** [microsoft/vscode-remote-release#3379]
- VSCode Version: 47.1
- Local OS Version: windows10
- Remote OS Version: linux ubuntu
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. wait 2 minutes with the `enter password` promt
2. enter correct password
3. get the following error:
![image](https://user-images.githubusercontent.com/58138282/87674886-5049a880-c77f-11ea-9a81-06cd7310e6e9.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
There is a timeout, you will just have to be a little quicker :)
