### ISSUE TITLE
Comments in SSH config can break SSH

### ISSUE THREAD

**Issue by bedenko** [microsoft/vscode-remote-release#338]
ssh config file allows for comments in form of a line beginning with '#'.

However, if there is comment in the middle of the line, ssh works fine, but vscode does not.
My request would be, to provide more verbose output of problem of failed connection, because currently there are no indications of this ( output of Remote-SSH is blank).

Or perhaps allow for such comments even if the default behavior of ssh does not list them.

**Comment by bedenko** [comment]
One more thing, that i noticed:
remote machine needs to have internet access for the first time, when connecting or upgrading vscode (curl of wget).
This is often not the case in production environments of containers.

Is it possible as a feature request, to proxy-tunnel those downloads through ssh? This would improve user experience.

Currently connection fails, also with very hidden signs of what is happening.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/15 is tracking the issue of offline remotes.

**Comment by roblourens** [comment]
Something like this was fixed awhile ago and comments work fine for me now, please give me an example if you still see an issue.
