### ISSUE TITLE
Enter password each new project opening - regression bug

### ISSUE THREAD

**Issue by ychechik** [microsoft/vscode-remote-release#3380]
- VSCode Version: 47.1
- Local OS Version: windows10
- Remote OS Version: linux ubuntu
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. open one window project with SSH
2. open another project/ new window in the same remote pc
3. needs to enter password again
This had been fixed briefly several months ago- but now it happens again

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by Chuxel** [comment]
//cc: @roblourens Is this related to some of the tweaks we've had to make to useLocalServer?

**Comment by roblourens** [comment]
You can get the old behavior back by enabling the `useLocalServer` setting. It was enabled by default briefly and now is disabled by default on Windows.

**Comment by ychechik** [comment]
The 'useLocalServer' setting was enabled from the start (didn't changed it at any time) 
![image](https://user-images.githubusercontent.com/58138282/88472736-c936c600-cf1e-11ea-971c-99871880ef5f.png)

Don't think this is the reason- can you reopen this issue?

**Comment by roblourens** [comment]
Is it enabled in the "User" scope? That is what actually matters here.

**Comment by ychechik** [comment]
indeed enabled in "user" scope (and remote and workspace, not available in folder scope).

**Comment by roblourens** [comment]
Sorry, I forgot I have to do something weird with this setting, it will only activate as enabled if you explicitly set it in your settings.json. `"remote.SSH.useLocalServer": true` this is because the default is platform-specific.

**Comment by ychechik** [comment]
OK. I've put this explicitly in my user settings.json and it works. I still believe that this is a bug... If this setting is enabled by default in all scopes it should just work, no?

**Comment by roblourens** [comment]
That setting causes other issues for some setups on Windows, so I can't enable it by default for everyone, unfortunately. And the fact that it appears enabled enabled in the settings UI is due to me applying this platform-speciifc override to the default value.
