### ISSUE TITLE
Expected globals not appearing

### ISSUE THREAD

**Issue by amlcodes** [microsoft/vscode-remote-release#3381]
- VSCode Version: insiders, lates
- Local OS Version:mac 
- Remote OS Version: ubuntu
- Remote Extension/Connection Type: Docker

If you docker run and exec a particular image, node and npm are available. If you use a Dockerfile to automatically provision a devenvironment for your project to use with Remote - Containers, node and npm are not available.

Am I missing some configuration?

Steps to Reproduce:

1. `docker run {image}` then `docker exec -it {name} bash` an image // node and npm available
2. .devcontainer/Dockerfile: // node and npm unavaible
```
FROM {image}

ENTRYPOINT ["zsh"]
```

**Comment by amlcodes** [comment]
I'm also able to just use `{ ... image: repo/image:tag }` and be brought right into where I need to be with node and npm available. I'd like to be able to provision the devenvironment further than where I get with the base image.

**Comment by amlcodes** [comment]
bash has nvm, npm, and node. zsh does not.

**Comment by Chuxel** [comment]
@amlcodes Most images do not have zsh installed in them. Can you be more specific with your example by providing the Dockerfile?

How is nvm getting installed?  (e.g. by default, nvm only augments .bashrc, not .zshrc)

Are you seeing nvm missing in the terminal or somewhere else?

**Comment by amlcodes** [comment]
In my Dockerfile I needed
```
RUN echo 'eval "$(ssh-agent -s)"' >> /home/ubuntu/.zshrc
RUN echo '. /usr/local/nvm/nvm.sh' >> /home/ubuntu/.zshrc
```
