### ISSUE TITLE
DEBUG set in terminals

### ISSUE THREAD

**Issue by themightychris** [microsoft/vscode-remote-release#3389]
I'm not positive yet that this is caused by Remote SSH but it seems that way, and it seems to be semi-recent.

All terminal sessions when I'm connected to a remote host via SSH start with `DEBUG` defined in the environment:

```console
$ echo $DEBUG
*,-babel*,-*:debug,-*:*:debug,-*:*:*:debug,-*:*:*:*:debug,-*:*:*:*:*:debug
```

This looks like a value a nodejs runtime would be using, and isn't defined in any bash profile on either machine. VSCode run directly on either machine doesn't show this. Having `DEBUG` set in every terminal session causes unexpected behavior from many tools. I find myself having to start every terminal session with `unset DEBUG` and any built-in terminal launchers like the Kubernetes extension become unusable:

<img width="1424" alt="Screen Shot 2020-07-18 at 10 36 18 AM" src="https://user-images.githubusercontent.com/458494/87854876-d5999e00-c8e2-11ea-969c-2caa17ec3b9c.png">

**Comment by roblourens** [comment]
We definitely don't set that variable anywhere. You might try searching your home directory for that string? I think something is probably setting it in some script on your machine.
