### ISSUE TITLE
Remote-SSH: open file autocomplete overwrites what you type

### ISSUE THREAD

**Issue by eyalsh** [microsoft/vscode-remote-release#339]
Issue Type: <b>Bug</b>

Steps to reproduce:
- Use the Remote-SSH extension to connect to a remote server
- Launch Open File (Ctrl+O)
- Wheh you start typing a directory name there's autocompletion in action but it overwrites what you type resulting in an unusable experience as when you press Enter (so it'll open the path you just entered) it attempts to a open a bad path
- It seems to be related to the speed you're typing in

Extension version: 0.37.0
VS Code version: Code - Insiders 1.34.20-insider (57b550c559b945eb9d871dbf2b2e4cb9e31e2551, 2019-05-10T17:32:52.030Z)
OS version: Linux x64 4.15.0-47-generic
Remote OS version: Linux x64 4.4.0-1079-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.53GB (3.99GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: eyal-compute|
|OS|Linux x64 4.4.0-1079-aws|
|CPUs|AMD EPYC 7571 (16 x 2199)|
|Memory (System)|61.81GB (55.80GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Are you on a slow connection? A gif would help a lot, if possible.

**Comment by eyalsh** [comment]
Not on a slow connection. GIF attached. The scenario is I'm typing "examples" quickly.
The problem seems to occur when you type fast
![Peek 2019-05-20 16-45](https://user-images.githubusercontent.com/1096746/58026371-ffa8d200-7b1e-11e9-8ac2-79ed7d15ebd7.gif)

**Comment by alexr00** [comment]
@eyalsh thank you for the gif. Can you try updating to insiders 1.35?

**Comment by eyalsh** [comment]
@alexr00 Updated to 1.35. Problem persists

**Comment by alexr00** [comment]
@eyalsh I've removed the auto complete as you type. The auto complete as you arrow through files is still in place. Fixed with 59fe2d19fdbd010323f3469a080fda132ae2fb80
