### ISSUE TITLE
File '/app/node_modules/@types/express/index.d.ts' is not a module.

### ISSUE THREAD

**Issue by rotemironsrc** [microsoft/vscode-remote-release#3391]
Issue Type: <b>Bug</b>

in local i will not get an error,
but only inside the container.

Extension version: 0.128.0
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.4.0
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: node.js typescript docke…|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (4 x 2300)|
|Memory (System)|3.85GB (1.12GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Could you share your project? (Or a simple example demonstrating the problem.)

**Comment by rotemlevi** [comment]
I didn't change anything, just used the project of the typescript in docker recipe

**Comment by bamurtaugh** [comment]
Hey @rotemironsrc, are you still experiencing this issue? As mentioned above, would you be able to share your project or any example of your problem here?

@rotemlevi Are you also still experiencing this problem? Would you be able to provide a link to the project/recipe you're using?
