### ISSUE TITLE
SSH: VSCode does not respect filesystem permissions

### ISSUE THREAD

**Issue by mkot02** [microsoft/vscode-remote-release#3399]
- VSCode Version: 1.47.2
- OS Version: Red Hat Enterprise Linux Server release 7.7
- Remote-SSH Version: v0.51.0

VSCode with Remote-SSH extension doesn't respect filesystem w permission for group.

Steps to Reproduce (on remote server):

1. Create users **user1**, **user2**:
```
[root]# useradd -U user1
[root]#useradd -U user2
```
2. Add **user1** to group **user2**:
```
[root]# usermod -a -G user2 user1
```
3. Create folder owned by **user2**, with 2775 permissions:
```
[root]$ mkdir -p -m 2775 /opt/test_dir
[root]$ chown user2:user2 /opt/test_dir
```
4. As **user1** create test file and folder to make sure that permissions works:
```
[user1]$ cd /opt/test_dir
[user1]$ mkdir dir1
[user1]$ touch file1
[user1]$ ls -la
total 0
drwxrwsr-x  3 user2 user2 31 Jul 20 07:14 .
drwxr-xr-x. 5 root  root  53 Jul 20 07:13 ..
drwxrwsr-x  2 user1 user2 6  Jul 20 07:14 dir1
-rw-rw-r--  1 user1 user2 0  Jul 20 07:14 file1
``` 
5. Open /opt/test_dir folder in VSCode on remote user using Remote-SSH extension
6. Try to create new folder **dir2** using VSCode:
> Error: EACCES: permission denied, mkdir '/opt/test_dir/dir2'
7. Try to create new file **file2** using VSCode:
> Unable to write file 'vscode-remote://ssh-remote+myserver.example.com/opt/test_dir/file2' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/opt/test_dir/file2')
8. Change ownership of **/opt/test_dir** folder:
```
[root]# chown user1:user2 /opt/test_dir
```
9. Execute steps 6&7 one more time. This time folder and file are created. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@roblourens this is really nothing I can fix on my layer, the server will have to be started in a way that it has sufficient permissions to write. I cannot write under a different user via node.js code.

**Comment by mkot02** [comment]
I also tried to create/change file using VSCode integrated terminal and it behave in the same way as GUI: **Permission denied**.

**Comment by mkot02** [comment]
Follow-up:
I was able to solve the problem by removing ~/.vscode-server folder and starting VSCode with SSH-Remote again.

**Comment by shreyansp** [comment]
Also worked by killing all vscode-server processes on remote, after setting the required user/group permissions
`ps aux | grep .vscode-server | awk '{print $2}' | xargs kill -9`

**Comment by PasaOpasen** [comment]
solved this by running 

```
ps aux | grep *username* | grep .vscode-server | awk '{print $2}' | xargs kill -9
```

(kill user processes is enough)

**Comment by adrianjean** [comment]
Too bad this won't be fixed as this is definitely related to vscode caching issue — luckily the advice by @mkot02 and others solved the issue for me as well.

**Comment by NKFabian** [comment]
Your Instructions helped for me. Trying to use VSRemote on a Raspberry Pi.. 
thanks a lot!!

**Comment by mecfletcher** [comment]
@shreyansp You're a lifesaver. Thank you!
