### ISSUE TITLE
ProxyCommand SSH config not working

### ISSUE THREAD

**Issue by BryanHitchcock** [Microsoft/vscode-remote-release#34]
- VSCode Version: 1.34.0 (insiders)
- Local OS Version: Windows 10 (1809)
- Remote OS Version: CentOS Linux 7 (Core)
- Remote Extension/Connection Type: SSH

I'm trying to connect to `hostB` (that's not the real host name, of course), however, it's only accessible after connecting to `hostA`. To accomplish this, I created the following SSH config file:
```
Host hostA
    HostName hostA.location.edu
    User bryan
Host hostB
    ProxyCommand ssh hostA.location.edu -W %h:%p
    HostName hostB.location.edu
    User bryan
```
Executing `ssh hostB` in my local terminal successfully connects to `hostB` (localhost -> hostA -> hostB), however, connecting to `hostB` via the remote-ssh extension yields the following error:

![image](https://i.imgur.com/jXS7Jq8.png)

Steps to Reproduce:

1. Create a SSH config file following the localhost -> hostA -> hostB paradigm.
2. `ssh hostB` via the terminal and observe the jump working properly.
3. Connect to `hostB` via remote-ssh in vscode and observe the error shown above.

**Comment by tralston** [comment]
Same problem here. Although it ran fine on my Mac, same config file.

**Comment by TheStoof** [comment]
This is the same issue that I reported in #18

**Comment by BryanHitchcock** [comment]
@TheStoof Oops, you're right! I'll close this issue so we can continue the conversation at #18.

**Comment by BryanHitchcock** [comment]
Another issue describing this bug: #1172
