### ISSUE TITLE
How to config Remote-ssh file to connect a remote machine

### ISSUE THREAD

**Issue by marchboy** [microsoft/vscode-remote-release#340]
Host 192.168.6.238
      HostName 192.168.6.238
      User root
      PasswordAuthentication *****
      Port 22

this configure failed to connect and it returns "Can't connect to 192.168.6.238: unreachable or not Linux x86_64 (se".)"

**Comment by marchboy** [comment]
Host 192.168.6.238
    HostName 192.168.6.238
    User root
    PasswordAuthentication *****
    Port 22

this configure failed to connect  and it returns "Can't connect to 192.168.6.238: unreachable or not Linux x86_64 (se".)"

**Comment by jitcoder** [comment]
not to state the obvious but are you able to ssh into the machine using your terminal?

**Comment by Yablon** [comment]
I configure my config file like this, and can connect to my private server.

Host ...
    User yablon
    HostName ...
    Port 2289
    IdentityFile D:\home\...\.ssh\id_rsa

**Comment by marchboy** [comment]
> I configure my config file like this, and can connect to my private server.
> 
> Host ...
> User yablon
> HostName ...
> Port 2289
> IdentityFile D:\home....ssh\id_rsa

Thanks a lot! And how to generate the "id_rsa" file ?

**Comment by Yablon** [comment]
@marchboy I generate my id_rsa file with Windows ssh-keygen.exe

**Comment by marchboy** [comment]
> @marchboy I generate my id_rsa file with Windows ssh-keygen.exe

Thanks again~

I generate "id_rsa" file with Windows ssh-keygen and transport the id_rsa.pub file into  ~.ssh/authroized_keys .

Now , I can connect my private server by using "ssh root@192.168.6.238"

but I configure the  config file like this:

Host 192.168.6.238
HostName 192.168.6.238
User root
IdentityFile C:\Users\Administrator\.ssh\id_rsa
Port 22

It also doesn't work..., VSCode returns "Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.)"

**Comment by marchboy** [comment]
> I configure my config file like this, and can connect to my private server.
> 
> Host ...
> User yablon
> HostName ...
> Port 2289
> IdentityFile D:\home....ssh\id_rsa



Thanks again~ I generate "id_rsa" file with Windows ssh-keygen and transport the id_rsa.pub file into  ~.ssh/authroized_keys .
Now , I can connect my private server by using "ssh root@192.168.6.238"

but I configure the  config file like this:
Host 192.168.6.238
HostName 192.168.6.238
User root
IdentityFile C:\Users\Administrator\\.ssh\id_rsa
Port 22

It also doesn't work..., VSCode returns "Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.)"
