### ISSUE TITLE
Please don't include hostnames in bug reports

### ISSUE THREAD

**Issue by rgov** [microsoft/vscode-remote-release#3400]
Issue Type: <b>Bug</b>

See below, populated by the issue reporter. I understand I can opt out of including *all* the information, but it seems like the hostname is not particularly useful for your diagnosis compared to the rest of the system info like OS version. And it carries downsides about exposing private information (corporate network layouts, etc).

Extension version: 0.20.0
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0
Remote OS version: Linux x64 4.15.0-111-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 6, 5|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|14%|

|Item|Value|
|---|---|
|Remote|SSH: lrauv-vm.local|
|OS|Linux x64 4.15.0-111-generic|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (2 x 3502)|
|Memory (System)|3.83GB (2.10GB free)|
|VM|100%|
</details>

**Comment by Chuxel** [comment]
//cc: @roblourens

**Comment by roblourens** [comment]
It's not necessarily a network hostname, most users give a custom name to their remotes. And I don't think it's generally considered confidential information. Also it can be useful for users just to know _which_ remote an issue was filed for. I think that users should review information included in the issue template before publishing.
