### ISSUE TITLE
Include open repo in container "projects" in Recent + allow to Pin (windows taskbar)

### ISSUE THREAD

**Issue by ntziolis** [microsoft/vscode-remote-release#3401]
Currently when starting a container via open repository in container, there is no entry in the recent list in windows taskbar which also means they cannot be pinned.

Note:
- There is an entry in the recent list inside of vscode
- And clicking this entry does work
- However it means starting vscode (which defaults to the last open project) and then switching from within vscode
- It's a minor thing but when switching 5-10 times on a day between projects it becomes very tedious. 

We have migrated all our devs to develop inside containers via the open repo in container feature. While they love the fact that they never have to deal with dev setup ever again. They do complain about switching projects being a pain.

I'd be happy to take a swing at a PR if you provide me with some pointers where in the codebase this is likely to be found.

**Comment by bpasero** [comment]
I think @aeschli added support for this, but maybe I am mistaken.

**Comment by ntziolis** [comment]
Let me know if this is already in the published version then I'm happy to test and confirm.

**Comment by aeschli** [comment]
Since a while we have remote entries also in the taskbar.


![Image](https://user-images.githubusercontent.com/6461412/207938398-734189f2-c5a6-4c7a-8d93-d79539bfa465.png)


Please speak up if that's not what you meant or doesn't work for you.
