### ISSUE TITLE
Support for docker-compose files when opening a repository in container

### ISSUE THREAD

**Issue by ntziolis** [microsoft/vscode-remote-release#3404]
Right now when using docker-compose + open repository in container the following error message is displayed
![image](https://user-images.githubusercontent.com/265338/88075030-85d40480-cb78-11ea-9645-1781c7f6d78a.png)

We absolutely need this as we have multi machine development environments + use a remote docker host. All of our development is migrating to this model and this is the last major remaining blocker.

Is there anything we can do to assist in moving this forward?

**Comment by Chuxel** [comment]
@egamma @chrmarti I didn't find an existing issue for this but I know we've discussed it. Is there one logged already?

**Comment by ntziolis** [comment]
@Chuxel I'm not clear how this can be used in combination with open from repository? Having access to git + credentials is they key piece we are interested in. 

We can absolutely get a container to run with a docker compose file + remove containers (open folder as container). The issue is the git piece. How do we get that wired up?

**Comment by Chuxel** [comment]
@ntziolis Open repository in container does not support Compose right now, but your git credentials should be automatically forwarded to any container you use as long as you install git inside it. That's done across the board. This is a convenience to prevent any manual setup of the container itself.

**Comment by chrmarti** [comment]
Tracking missing test as #3607.

There is also more opportunity for consolidation in the single container case where we could use a CLIHost for the build container to share more code between the local folder and volume cases. (The Docker Compose case already does this.)
