### ISSUE TITLE
Open Source the Remote extensions or at least allow contributions from community somehow

### ISSUE THREAD

**Issue by ntziolis** [microsoft/vscode-remote-release#3405]
These extensions should be open source / open for contributions considering:
- issues + feature requests piling up
- these extensions are at the core of the developer workflow
- and last but not lease microsoft trying to be more open

We are willing to help but right now our hands are tied since there is no way to contribute code.

**Comment by cjconrad2** [comment]
Agreed. Would love to contribute support for windows containers, but don't have the ability to.

**Comment by Chuxel** [comment]
Thanks for the feedback! Unfortunately, we do not have a way to do this at the moment. Check out the FAQ for current information the licensing. 
 https://code.visualstudio.com/docs/remote/faq#_license-and-privacy

**Comment by ntziolis** [comment]
Former blue badge here, we are happy to sign whatever to assist in coding this. Our flexibility goes as far as creating a 0$ PO (we are registered MS contractor already).
