### ISSUE TITLE
Copy&Paste files in vscode file explorer does not work

### ISSUE THREAD

**Issue by ntziolis** [microsoft/vscode-remote-release#3407]
There is no way to duplicate a file via the GUI right now

- VSCode Version: 1.48.0 insiders
- Local OS Version: Windows 10 1909
- Remote OS Version: latest mcr.microsoft.com/vscode/devcontainers/typescript-node:0-10
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open folder in Container
2. Navigate to file explorer within vscode
3. Select a file
4. Copy the file either via context menu or CTRL+C
5. Paste the file either via context menu or CTRL+V
6. Nothing happens

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by Chuxel** [comment]
@chrmarti Has this been implemented yet?  I suspect this is a feature request.

**Comment by ntziolis** [comment]
Since there is no way to review the code its hard to determine if its missing vs not working.

I fully understand that in your eyes this is a feature that is not yet implemented. But in the eyes of the user this is a functionality that does exist in vscode and that is not working when using remote containers. Hence a user would consider this a bug or at the very least a notable and unexpected limitation.

Is there a list of limitations when working with remote containers yet that I or others can review before filing issues?

**Comment by Chuxel** [comment]
In some cases there are limitations that are not written down, which we can then add to docs. Trying to determine whether this is the case here. (Also, FYI - there's a number of team members on vacation, so you may notice slower response times at the moment.)

**Comment by ntziolis** [comment]
No rush, this was merely meant to improve the feedback you are getting.

**Comment by chrmarti** [comment]
This works on Mac, but not on Windows. I don't see anything related in the logs. @isidorn Could this be an issue with the Explorer?

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/100797
