### ISSUE TITLE
File Ownership Issue

### ISSUE THREAD

**Issue by ghood97** [microsoft/vscode-remote-release#3410]
Issue Type: <b>Bug</b>

When I use `code .` to open VSCode from WSL2, any files/directories that I create directly in the VSCode interface (FIle -> New File/Folder), are given the owner of root and the group of root instead of the user that is currently logged in. When I create the files/directories in the WSL2 command line via `touch test.js` or `mkdir test` the ownership and group is correctly set to my user. Is there a way to change this behavior?

Extension version: 0.44.4
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (5.99GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-Five-P/home/ghood97/repos/5-principles/src --remote=wsl+Ubuntu-Five-P|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-Five-P|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|12.35GB (10.84GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment]
The Remote-WSl extension always uses the default WSL user. There's a feature request that WSL-Remote also starts with a non-default users: https://github.com/microsoft/vscode-remote-release/issues/286.

The current solution is to change the default user: see https://github.com/microsoft/vscode-remote-release/issues/286#issuecomment-492402644
