### ISSUE TITLE
[Feature request] More verbose output on docker-compose build errors

### ISSUE THREAD

**Issue by cmp102** [microsoft/vscode-remote-release#3411]
I find it a little bit annoying that, when the docker-compose command fails when rebuilding a container, no explanation is shown to why it failed and it doesn't give me too many options. I have to manually execute the command on the terminal to see why it failed, most of the times being trivial reasons such as an env var not being set. This can be confusing for other developers that aren't really acquainted with how docker works.

I propose that the logs should show all docker-compose errors when the command fails.

**Comment by cmp102** [comment]
A coworker has shown me that in his Windows machine, the docker-compose errors logs already appear. It seems that this doesn't work in Linux and Mac.

**Comment by chrmarti** [comment]
A recent fix should have improved this (https://github.com/microsoft/vscode-remote-release/issues/3205). Can you retry with Remote-Containers 0.128.0 or later?

**Comment by cmp102** [comment]
Yes, It works now.
Thank you.
