### ISSUE TITLE
Error while trying to connect to remote.

### ISSUE THREAD

**Issue by saketd403** [microsoft/vscode-remote-release#3412]
Hi,
   I started to get this error  when trying to access folder named "groupnorm" on remote server - 

Unable to open 'groupnorm': Unable to read file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a227375626d69742d632e6870632e656e67722e6f7265676f6e73746174652e656475222c2275736572223a226465736169736175227d/nfs/dgx2-5/saurabhd_05/groupnorm' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a227375626d69742d632e6870632e656e67722e6f7265676f6e73746174652e656475222c2275736572223a226465736169736175227d/nfs/dgx2-5/saurabhd_05/groupnorm').

VS code was working fine for last 3 months.

**Comment by roblourens** [comment]
Is that the right path (starting with `/nfs/...`

Can you give exact steps to reproduce this issue?
