### ISSUE TITLE
wsl2: Debugging with external terminal does not work

### ISSUE THREAD

**Issue by andrp92** [microsoft/vscode-remote-release#3413]
- VSCode Version: 1.47.2
- Local OS Version: 2004
- Remote OS Version: Debian 10.3
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Set up a launch setting to debug any app. 
2. Set the configuration parameter:  **"console": "externalTerminal"**.
3. Try launching the debbuger or running the app. The following error will show up: 

![image](https://user-images.githubusercontent.com/28060986/88229831-6ce25680-cc3f-11ea-9c1e-38af3e8641c6.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by andrp92** [comment]
I have tried using different settings for **"terminal.external.linuxExec",** but seems like **xterm** is the only option there. The only thing I'm trying to achieve here is to be able to watch the logs outside of vscode. 

If terminal can be run internally on the vscode there should be a way to run it externally too at the end, it's the same wsl bash running in backend.

**Comment by Chuxel** [comment]
@andrp92 An external terminal is not supported in the remote extensions.

//cc: @weinand Didn't we already fix this to use internal so it didn't error?

**Comment by andrp92** [comment]
@Chuxel I see. Are they any plans to support that some time in near future or not?

If it's not supported I agree it has to be fixed so people stop having this errors and please add it somewhere in documentations. I couldn't find any reference that tells me what you are telling me now. 

Thanks.

**Comment by weinand** [comment]
The configuration parameter "console" is provided by some debug extensions. It is not introduced by VS Code.

**Comment by egamma** [comment]
@andrp92 what language did you try to debug when you ran into this problem, C++?

**Comment by Chuxel** [comment]
@egamma In some cases, you can't change the external terminal setting.  I see this in the Ionide extension's solution explorer. I thought we'd resolved this by defaulting to the internal termal even if external was set.  (At a minimum we'll want to do this for Codespaces.)

**Comment by andrp92** [comment]
@egamma Python
