### ISSUE TITLE
drag&drop file between remote and local creates empty file

### ISSUE THREAD

**Issue by itaysk** [microsoft/vscode-remote-release#3414]
Seems like a regression that broke this feature?: https://github.com/microsoft/vscode-remote-release/issues/73
right click -> download still works

- VSCode Version: 1.47.2
- Local OS Version: MacOS 10.15.5
- Remote OS Version: 
- Remote Extension/Connection Type: SSH
- Remote Extension Version: Remote - SSH (Nightly) v2020.7.22500

Steps to Reproduce:

1. connect to remote (ssh)
2. drag file into local
3. created file is empty (0 bytes)

Does this issue occur when you try this locally?: irrelevant
Does this issue occur when you try this locally and all extensions are disabled?: irrelevant

**Comment by Chuxel** [comment]
@roblourens This seems like a regression, correct?

**Comment by isidorn** [comment]
We do not change anything in this area. Might be due to an electron update
@itaysk can you reproduce with latest vscode insiders?
