### ISSUE TITLE
WSL Ubuntu 20.04 - zsh: command not found: code

### ISSUE THREAD

**Issue by andradei** [microsoft/vscode-remote-release#3417]
- VSCode Version: 1.47.2
- Local OS Version: Windows 2004 OS build 19041.388
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Start Windows Terminal on Ubuntu 20.04
2. type `code .`

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

When I first installed VSCode and the Remote - WSL extension, `code .` worked from WSL. I don't know what make it break, but maybe it was after I installed and configured `zsh`.

I followed [this suggestion](https://github.com/microsoft/vscode-remote-release/issues/2962#issuecomment-634523626) to try to fix the problem.

But even with `code` on my `PATH`, WSL seems to not find the binary as if the path was never set. See below how I manually added it to the path from **~/.zshenv**.

VS Code is installed:

```
$ ls -la /mnt/c/Users/My\ User/AppData/Local/Programs/Microsoft\ VS\ Code/bin
total 4
drwxrwxrwx 1 andradei andradei  512 Jul 22 11:45 .
drwxrwxrwx 1 andradei andradei  512 Jul 22 11:45 ..
-rwxrwxrwx 1 andradei andradei 1969 Jul 15 18:22 code
-rwxrwxrwx 1 andradei andradei  132 Jul 15 18:22 code.cmd
```

`code` is on `PATH`:

```
$ cat ~/.zshenv
...
export PATH="/mnt/c/Users/My\ User/AppData/Local/Programs/Microsoft\ VS\ Code/bin:$PATH"
...

$ echo $PATH
/home/me/.nvm/versions/node/v14.6.0/bin:/mnt/c/Users/My\ User/AppData/Local/Programs/Microsoft\ VS\ Code/bin:/usr/local/go/bin...
```

Still can't find it:

```
$ which code
code not found

$ code .
zsh: command not found: code
```

However, running `code with an absolute path works!

```
$ /mnt/c/Users/My\ User/AppData/Local/Programs/Microsoft\ VS\ Code/bin/code .
```

And Initiating a WSL: Ubuntu-20.04 session from (local) VSCode works too.

**Comment by andradei** [comment]
A (temporary) solution I found was to add the following to my `.zshrc`

`alias code='/mnt/c/Users/My\ User/AppData/Local/Programs/Microsoft\ VS\ Code/bin/code'`

**Comment by PavelSosin-320** [comment]
There is WSL 2 configuration parameter controlling how Host path is inherited. by WSL distro: %USERPROFILE%/.wslconfig. 
Up to user to decide which Windows executables invoked via WSL interop mechanism are invoked using Linux path.
Performance consideration should be taken into account.

**Comment by andradei** [comment]
@PavelSosin-320 Could you provide me a link of how this works?

**Comment by andradei** [comment]
The issue was that I installed Ubuntu-20.04 manually instead of through the Microsoft Store.
I tried a lot of different configurations but it seems that something crucial is missing when you install Linux under WLS2 from the GitHub repo manually.

I don't what manual configuration would be required to get this working, but installing from the Microsoft Store worked.

**Comment by andradei** [comment]
Might be related, [this also helped me fix the issue](https://github.com/microsoft/WSL/issues/5296#issuecomment-665372337)

**Comment by razorblade446** [comment]
I did something, and not sure if this might solve your situation: 

1. Stop WSL (wsl --shutdown)
2. Remove WSL Remote extension from VSCode
3. Reinstall WSL Remote extension from VSCode

I opened the WSL window again and now code command works
