### ISSUE TITLE
`build.args` not passed to `docker-compose` build

### ISSUE THREAD

**Issue by grahamlyons** [microsoft/vscode-remote-release#3420]
- VSCode Version: 1.47.2 17299e413d5590b14ab0340ea477cdd86ff13daf x64
- Local OS Version: macOS 10.15.5 (19F101)
- Remote OS Version: python:2.7.18-slim (Debian)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Create `docker-compose.yml` file with a service that has a local build
2. Create `Dockerfile` with an `ARG`, for that build
3. Add a check for the `ARG` e.g. `RUN : "${FOO?Missing foo}"`
4. Add variable to global shell environment for user e.g. `~/.zshrc`
5. In `.devcontainer/devcontainer.json` add `build.args` - `"build":{"args":{"FOO":"${localEnv:FOO}"}},`
6. Open project folder in a container, specifying an existing `docker-compose.yml`

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

The logs show that the `docker-compose` build is done incidentally via the `up` command - the logs show the command:
```
~/Library/Application Support/Code/logs/20200101T000000/exthost1/ms-vscode-remote.remote-containers/remoteContainers.log:[2020-01-01T00:00:00.000Z] [PID 1] [20 ms] Start: Run: docker-compose --project-name myproject -f ~/myproject/docker-compose.yml -f ~/myproject/.devcontainer/docker-compose.yml up -d --build
```

The `build.args` don't seem to be passed to `docker-compose` and this may be because the build phase is not separated - the `up` command doesn't support the `--build-arg` flag.

**Comment by Chuxel** [comment]
Yes, this is expected.  Docker compose has its own, more robust mechanism for storing build arg, context, and references to dockerfiles. See https://aka.ms/vscode-remote/devcontainer.json for properties supported for Docker Compose and "General" for those that apply to all scenarios.  The one in devcontainer.json is for simple single image/Dockerfile scenarios that don't need the rest of compose's functionatlity.

If you don't want to modify the file directly, you can use a second override docker-compose.override.yml file. `dockerComposeFile` is an ordered array property.

**Comment by grahamlyons** [comment]
Aah, that's very helpful. Thanks @Chuxel, that makes total sense.
