### ISSUE TITLE
High CPU usage with rg command in Remote SSH

### ISSUE THREAD

**Issue by sigmarising** [microsoft/vscode-remote-release#3421]
- VSCode Version: 1.47.2
- Local OS Version: Windows10 x64 2004
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Reproduce:
First, I use the ssh in pwsh connect to remote server (AliYun ECS Ubuntu 18.04, CPU core 2, RAM 4GB), and run `top` command to monitor the process. And everything run well there:

<img width="960" alt="Snipaste_2020-07-25_08-45-56" src="https://user-images.githubusercontent.com/25470568/88445292-33366900-ce54-11ea-877c-ba46760e4524.png">

Next, I connect with vscode-remote-ssh, and do nothing in vscode:

<img width="960" alt="Snipaste_2020-07-25_08-46-24" src="https://user-images.githubusercontent.com/25470568/88445326-6973e880-ce54-11ea-8176-e4cf078632f1.png">

Then, I notice that in `top` panel, there are new `rg` command with high cpu usage:

<img width="960" alt="Snipaste_2020-07-25_08-46-43" src="https://user-images.githubusercontent.com/25470568/88445348-932d0f80-ce54-11ea-86e7-865db30f238b.png">

When I shutdown the vscode-remote-ssh, the high cpu usage process `rg` are gone.

---

I usually connect to ECS with vscode-remote-ssh. But these days, I suffer from high latency in remote bash interactive no matter in vscode-remote-ssh or ssh command line tools. After repeated investigation, I found that ECS suffer from high cpu usage which may caused by vscode-ripgrep.

This can be reproduced every times until now.

**Comment by roblourens** [comment]
Please check whether any tips here help: https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory

**Comment by sigmarising** [comment]
> Please check whether any tips here help: https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory

I follow the instruction and turn the settings `search.followSymlinks: false`. And the `rg` process doesn't occupy high cpu usage any more.

Thanks a lot for your help.
