### ISSUE TITLE
Does not open explorer in pod k8s when I do attach vscode

### ISSUE THREAD

**Issue by nedlosster** [microsoft/vscode-remote-release#3422]
- VSCode Version:  1.47.2
- Local OS Version: 18.04.1-Ubuntu
- Remote OS Version: Centos 7 in container
- Remote Extension/Connection Type: k8s/container

Steps to Reproduce:

1. Connecting to the pod in k8s.
![0](https://user-images.githubusercontent.com/9947598/88452286-14d96900-ce66-11ea-8435-ac78ebe8b624.png)

2. Connection was successful. I can open the terminal in the pod.
![1](https://user-images.githubusercontent.com/9947598/88452310-47836180-ce66-11ea-86a8-3c9e814acecb.png)

3. I'm trying to open the file system in explorer. The list of files is visible.
![2](https://user-images.githubusercontent.com/9947598/88452354-a943cb80-ce66-11ea-9a17-e4ff4fdc5068.png)

4. But then an error occurs.
![3](https://user-images.githubusercontent.com/9947598/88452387-fa53bf80-ce66-11ea-87e7-06f4c249bc62.png)

Errors:

- Unable to open 'voip_gui': Unable to read file 'vscode-remote://k8s-container+podname=voip-gui-backend-dev-0+namespace=voip-gui-dev+name=backend-dev+image=werf-registry.kube-system.svc.cluster.local:5000/voip-gui/voip-gui-dev:1.121/workspace/voip_gui' (TypeError: Cannot destructure property 'contents' of 'this._folderConfigurations.get(...)' as it is undefined.).

- Failed to connect to the remote extension host server (Error: Cannot destructure property 'contents' of 'this._folderConfigurations.get(...)' as it is undefined.) 

While investigating the problem, I found a pattern:

This error occurs when a pod is created from an image that has a port number (:5000)  in its name. In this instance:
Image: warp-registry.cube-system.svc.cluster.local:5000/voip-goip/voip-guide v:1.121
![5](https://user-images.githubusercontent.com/9947598/88452657-30923e80-ce69-11ea-820a-7fd7e0f33423.png)

When I connect to a pod whose image name doesn't have a port number, everything is fine.

![6](https://user-images.githubusercontent.com/9947598/88455178-f5e5d180-ce7b-11ea-97dc-df6aefa90c78.png)

![4](https://user-images.githubusercontent.com/9947598/88452613-e9a44900-ce68-11ea-9651-7d382991d578.png)

There is an error when connecting to a minikube and a full k8s cluster.

I hope for help.

**Comment by alberto-riggi** [comment]
I run in the same issue using different versions of vs code and extensions.
Thanks to  @nedlosster I actually found a (dirty and incredibly ugly) workaround. Maybe you are using the same workaround already.
I am using microk8s and the ugly workaround was to retag the image without the registry port, save it and import it locally in the node where I wanted to deploy the pod. Like mentioned here `https://microk8s.io/docs/registry-images`
Once there, I could use that new name for the image of the container and it worked (as you noticed with the posgres image).
I saw there should be something similar for minikube but I have no experience there. 
Hope it helps somehow.

**Comment by nedlosster** [comment]
I didn't wait for the developers to solve this problem.
My solution is not to use image registry on non - standard ports.
This is how I launch a mini cube for development in it:
```
minikube start --addons registry 

kubectl wait --for=condition=available --timeout=60s --all deployments -A
kubectl -n kube-system wait --for=condition=ready --timeout=120s pods -l actual-registry=true
kubectl -n kube-system wait --for=condition=ready --timeout=120s pods -l registry-proxy=true
kubectl -n kube-system wait --for=condition=ready --timeout=120s pods -l app.kubernetes.io/component=controller

cat <<EOF | kubectl --namespace kube-system apply -f -
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: registry-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
spec:
  rules:
  - host: "werf-registry.kube-system.svc.cluster.local"
    http:
      paths:
      - path: /
        backend:
          serviceName: "registry"
          servicePort: 80
EOF

export REGISTRY_IP=$(kubectl -n kube-system get service registry -o=template={{.spec.clusterIP}})

minikube ssh "cat /etc/hosts |  grep -v werf-registry | sudo tee /etc/hosts"
minikube ssh "echo '$REGISTRY_IP werf-registry.kube-system.svc.cluster.local' | sudo tee -a /etc/hosts"

sudo sed -i -e '/^.*werf-registry.*l$/d' /etc/hosts
echo `minikube ip`" werf-registry.kube-system.svc.cluster.local" | sudo tee -a /etc/hosts

kubectl -n kube-system wait --for=condition=ready --timeout=120s pods -l app.kubernetes.io/component=controller
echo "for test registry [[curl -X GET werf-registry.kube-system.svc.cluster.local/v2/_catalog]"
echo "for login [[docker login werf-registry.kube-system.svc.cluster.local -u admin -p admin]]"
```

You also need to add to /etc/docker/daemon.json:
```
{
	  "insecure-registries": ["werf-registry.kube-system.svc.cluster.local"]
}
```

Now you can normally connect VSCode to Pod with Images from this registry.

**Comment by alberto-riggi** [comment]
@nedlosster 
Thanks for the feedback, We were thinking to do something like that too. This is very helpful.
Appreciate it!
Regards

**Comment by Lupus** [comment]
Highly un-intuitive error... Ran into this today when tried to attach to Kubernetes pod for the first time. It seems this can also be worked around by opening your container from recent and trying to open folder again after it failed. Can't tell the exact sequence, but I managed to get through with some fiddling.

**Comment by chrmarti** [comment]
To verify:
- Install a Kubernetes runtime (e.g., Docker Desktop or minikube) and (if not included) the `kubectl` CLI.
- Start a Pod including a port number in the image name: `kubectl create deployment hello-node --image=k8s.gcr.io:443/echoserver:1.4`
- Install the Kubernetes extension.
- Attach to the Pod from the Kubernetes viewlet:
![image](https://user-images.githubusercontent.com/9205389/101374977-23716b80-38af-11eb-89ba-c9d7fa5792f5.png)
- 'Open Folder' in the Pod:
  - Verify the window reloads and successfully reconnects to the Pod and has the folder open.
- Cleanup: `kubectl delete deployment hello-node`

**Comment by aeschli** [comment]
Verified/ @chrmarti Thanks for the easy step!
