### ISSUE TITLE
Allow opening remote files in the same window as local ones

### ISSUE THREAD

**Issue by NightMachinary** [microsoft/vscode-remote-release#3423]
In emacs, remote files are nothing "special" and are handled the same as normal files. You can see how the remote file is simply a file that has `/ssh:...:/` prepended to it:

![image](https://user-images.githubusercontent.com/36224762/88454104-26306e80-ce82-11ea-8bb9-4dd126e3e573.png)

This allows me to jump between my remote and local files (and indeed, between different versions of the same file) easily, all from a single window (or "frame" in emacs lingo). However, vscode forces me to open a new window for each remote, and it also does not allow me to easily jump between my files; E.g., there is no quick way to open a remote file from a local window using the usual navigation hotkeys such as `CMD+p`. So to switch between remote and local files, I first have to switch to a vscode window that is connected to the remote, and then do `CMD+p`. This multiple window requirement uses up more RAM, clutters my desktop, and makes it hard for me to define shortcuts for switching between different programs in my window management software. I currently have a global keyboard hotkey for switching to any of my common apps; `Fn+c` is the hotkey that switches to vscode. But this only works if there is a single vscode window.

**Comment by roblourens** [comment]
I understand the request, and that's a cool emacs feature, I actually didn't realize it could do that. But this assumption in vscode about one window per remote is baked into it at the lowest level and it's not technically feasible for us to do this.

**Comment by PavelSosin-320** [comment]
This is a conceptual issue that MS faces in any place: POSIX vs Windows32. POSIX assumes that any artifact has an absolute and relative URL. Workspace root is the based URL for any Workspace artifact. The relative URL is the display URL. Full URL, i.e. absolute PATH is displayed by demand, i.e. right-click. Displaying the absolute URL in the explorer UI is not practical.
