### ISSUE TITLE
vscode does not open remote files that start with a dot

### ISSUE THREAD

**Issue by NightMachinary** [microsoft/vscode-remote-release#3424]
```
Version: 1.48.0-insider
Commit: e7920dce7bfd0b707ebfc0a5379c6edd2233e475
Date: 2020-07-10T11:55:11.286Z (2 wks ago)
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 19.0.0
- Remote OS Version: Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
- Remote Extension/Connection Type: SSH
```

Steps to Reproduce:

1. Run `code-insiders --reuse-window --remote ssh-remote+sth /home/sth/.zsh_history` for any text file starting with a dot
2. vscode will think that file is a directory, reloads its window, and then shows nothing:
![image](https://user-images.githubusercontent.com/36224762/88455387-259bd600-ce8a-11ea-86a3-a4ef4a780d68.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
I can repro

**Comment by bpasero** [comment]
I think Martin added the CLI support for remotes, probably at the `electron-main` layer we cannot really tell if the path is a file or folder.

**Comment by aeschli** [comment]
Yes there's guessing involved: If it has a file extension, it's a file or a workspace. By defaults it's a folder.
I changed that now when something starts with a dot it's a file.

**Comment by bpasero** [comment]
This is probably better but you might still have folders with leading dots.

**Comment by aeschli** [comment]
Yes, but at least you can force the opening of a folder by adding a slash

**Comment by aeschli** [comment]
To force that a folder is opened, add slash to the path or use:

`code --folder-uri vscode-remote://ssh-remote+sth/home/ubuntu/folder.with.dot`

To force that a file is opened add `--goto` or use:

`code --file-uri vscode-remote://ssh-remote+sth/home/ubuntu/fileWithoutExtension`
