### ISSUE TITLE
Allow opting out of platform support check

### ISSUE THREAD

**Issue by tyeth** [microsoft/vscode-remote-release#3426]
I accept that microsoft have now closed (#669  ) the arm6 raspberry pi zero thread, based on it having 512mb of ram and possibly having a poor experience with some or all of the remote debugging plugins, and no-one vocalising other arm6 hardware desires, although the loose promise to revisit the decision if performance can be guranteed int he future.

Please let us be the judge of how poor the experience we will tolerate is, as sometimes there is very little choice in the matter.

I'd like users to be included in the decision.

My personal use is very low resource, python script debugging, file injesting, serial stuff that sort of thing. I'm also using plotly to generate an output file that takes 12 secoinds, and I'd expect that to take probaly 30-90 in debug mode. Is that level acheivable?

**Comment by PavelSosin-320** [comment]
I don't think that acceptable response time is a topic for user's voting. This is an objective, product-wide KPI. 
For example, for Web applications, the acceptable response time is limited by the browser's HTTP timeout which can't be changed or very tricky to change, depends on the browser. Nodejs HTTP has its own built-in HTTP timeout. Even 90% of users will vote for unlimited HTTP timeout it will be not feasible.

**Comment by tyeth** [comment]
Definitely agree with you, but also that a large application shouldn't be
the sole focus of this project.

**Comment by PavelSosin-320** [comment]
The project sizing doesn't matter because it can be mitigated by the Progress indicator. But when Progress indicators become to be must be shown can't be the result of user's voting - every UX professional can provide the exact figures.

**Comment by tyeth** [comment]
Care to elaborate on that?

**Comment by Chuxel** [comment]
Just to clarify, the issue is really not about debugging or the size of the project, but rather running half of VS Code on the device given the architecture. Disconnects, crashes, etc when you run out of RAM is the primary consideration. Doing anything else then exacerbates the problem. 

That said, a possible option we could consider would be to allow people to opt into disabling platform checks to try unsupported platforms.

@roblourens - What do you think about that idea? Would it work?

**Comment by roblourens** [comment]
Do we know that our ARM build will even start on that device? I think it's going to be a bad experience, and then people are going to file lots of issues about it. I could write an obvious warning to the log though. From the number of issues I've gotten with people trying to use small 1GB VMs, I really think it's just going to run wild and crash the device.

If you tell me the output of `uname -sm` I can provide a build that will try to start up and you can tell me what the experience is like.

**Comment by PavelSosin-320** [comment]
@Chuxel This is not a feature request. Publishing of hardware requirements and software pre-requisites is a good practice. The development team can't test and maintain the product on all possible hardware configurations backward. Forward compatibility is much more important. Support for old, obsolete hardware is always out of the scope of the product maintenance cycle.
Support of the new hardware is always in the scope because it improves user experience.

**Comment by Chuxel** [comment]
@PavelSosin-320 Not quite sure where you are going with the comment here. We've published support already. There are, however, hard blocks in the code beyond published support. We could investigate allowing an opt into disabling the check to enable scouting. That would not change anything in terms of what is said to be supported.

**Comment by tyeth** [comment]
I think I may have overstated what I expect, I actually _don't expect debug support_ but **just basic remote file and terminal** support as it's essentially a low end linux box. Is there a way to get remote ssh plugin and remote explorer plugin to work without remote debug?

 Debug is a wish list feature.

In my head vscode is a glorified text editor with intellisense; terminal and VCS support, the execute and debug is a wonderful but not always supported feature depending on platform/language/tooling/user config.

**Comment by roblourens** [comment]
[remote-ssh-nightly-0.55.0.zip](https://github.com/microsoft/vscode-remote-release/files/5329261/remote-ssh-nightly-0.55.0.zip)

Sorry for the slow response. Here's a private build that will download the "armhf" server for "armv6l".

**Comment by tyeth** [comment]
Sadly vs server bombed with illegal instruction. nothing else in log.
https://pastebin.com/61u1qQYf

**Comment by roblourens** [comment]
Dang. Thanks for trying it

**Comment by roblourens** [comment]
Since the server won't run on that device, I don't think that making the platform check optional is helpful
