### ISSUE TITLE
support attach to old distro container (centos5.11, ubuntu10.04...)

### ISSUE THREAD

**Issue by davidtazy** [microsoft/vscode-remote-release#3429]
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:15.161Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.40-04224-g891a6cce2d44

- Remote OS Version:  astj/centos5-vault
- Remote Extension/Connection Type: Docker ?

Steps to Reproduce:

1.docker run -it --rm astj/centos5-vault bash
2.in vscode Remote-Containers: attach to running container

error:

```
Start: Run in container: mv -n /root/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf_1595795900477 /root/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf
[2397 ms] 
[2397 ms] mv: invalid option -- n
Try `mv --help' for more information.
[2397 ms] Exit code 1
[2433 ms] Command in container failed: mv -n /root/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf_1595795900477 /root/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf
```

centos 5 does not have -n option for mv command.

could you consider using another tool like rsync?

it will be awesome to use  modern tools on old distro!

**Comment by Chuxel** [comment]
Unfortunately, Remote - Containers / SSH requires a more recent version of C++ than is available in those older distros.  Worse yet, it's node that requires it and neither Node nor V8 support it. So, sadly, we won't be able to add official support for things that are that old. There is a workaround described here that may or may not work for you: https://code.visualstudio.com/docs/remote/linux#_updating-glibc-and-libstdc-on-rhel-centos-6
