### ISSUE TITLE
macos - c++ intellisense not working with Remote SSH

### ISSUE THREAD

**Issue by git4lad** [microsoft/vscode-remote-release#343]
Looks like C++ IntelliSense  not working when used with remote ssh

- VSCode Version: 1.34.20-insider (1.34.20-insider)
- Local OS Version: Mac OS - 10.14.5
- Remote OS Version: Fedora 30 (Server Edition) - Linux 5.0.13-300.fc30.x86_64 x86_64
- Remote Extension/Connection Type: SSH/Docker/WSL - SSH

**Comment by egamma** [comment]
Cannot reproduce given the information given. Can you please file an issue against the C++ extension with some detailed steps.

**Comment by git4lad** [comment]
Hey @egamma , Thanks for response. 
"can't reproduce"  - so for you c++ intellisense works ? Just asking as then that means i am doing something wrong! 
I will raise bug for extension based on response.
