### ISSUE TITLE
Add theme customisation option when connected

### ISSUE THREAD

**Issue by albireox** [microsoft/vscode-remote-release#3433]
VSCode provides a customisation option `statusBarItem.remoteBackground` to change the colour of the remote window indicator. Would it be possible to have separate configurations for the colour when it's connected and when it's not? I like to be quickly aware if I'm working on a remote machine so I change the colour of the indicator to something bold, but I'd prefer to have something more subtle when working on a local window.

**Comment by Chuxel** [comment]
One way you can do this is with machine level configurations to do this. See:

SSH:  https://code.visualstudio.com/docs/remote/ssh#_ssh-hostspecific-settings
Containers: https://code.visualstudio.com/docs/remote/containers#_container-specific-settings

**Comment by albireox** [comment]
I hadn't thought of that but it works great! Since I don't have that many remote machines that solution works fine for me and probably it's not needed to implement anything else.

**Comment by Chuxel** [comment]
Glad to hear it!! Closing as resolved.
