### ISSUE TITLE
WSL 2 High CPU Usage

### ISSUE THREAD

**Issue by yinmax** [microsoft/vscode-remote-release#3434]
- VSCode Version: 1.46.1
- Node.js: 12.8.1
- Local OS Version: Windows 10 Pro, Version 2004, Build 19041.388
- Remote OS Version: Ubuntu 18.04, WSL2
- Remote Extension/Connection Type: WSL

Steps to Reproduce:
When opening a folder in WSL using VSCode, I get high CPU usage. 

Here is what my task manager looks like:
![Capture1](https://user-images.githubusercontent.com/32028171/88572125-e8575580-cffb-11ea-9df4-637af659b1ad.PNG)

And here is what the 'top' command gives me inside the WSL Connection:
![Capture2](https://user-images.githubusercontent.com/32028171/88572217-0755e780-cffc-11ea-815f-78ab828d1d5f.PNG)

I looked around and couldn't find a similar issue here so I am making a new post. When running the WSL 2 terminal by itself there are no issues. The issue only happens when I use 'Remote - WSL' Extension (v0.44.4) in vscode and connect to WSL.

**Comment by bamurtaugh** [comment]
Hey @yinmax, are you still experiencing this issue? Does it look like #2921 or https://github.com/microsoft/vscode/issues/97568#issuecomment-630822277 might help your scenario if so (I think they apply largely to WSL1 though)?

**Comment by bamurtaugh** [comment]
Set of CPU usage/performance issues: 

https://github.com/microsoft/vscode-remote-release/issues/3434
https://github.com/microsoft/vscode-remote-release/issues/3161
https://github.com/microsoft/vscode-remote-release/issues/3195
https://github.com/microsoft/vscode-remote-release/issues/3340

Some solution info that worked for some folks:
https://github.com/microsoft/vscode-remote-release/issues/2921#issuecomment-624564199
https://github.com/microsoft/vscode/issues/97568

**Comment by yinmax** [comment]
The issue still persists with a specific folder, but it might be the result of having too many nested folders/files under it. I have been actively avoiding folders with too many nested folders/files and it has been working fine.

Feel free to close this issue.

**Comment by bamurtaugh** [comment]
Thanks for the update @yinmax!
