### ISSUE TITLE
Delete SSH targets

### ISSUE THREAD

**Issue by titamrtn** [microsoft/vscode-remote-release#3438]
There are many SSH targets that i'll never re-use, it's may good to have abilty to delete them.

**Comment by roblourens** [comment]
This is a good idea, but from past experience I am nervous about adding this, because it may not be clear that we are deleting them permanently from the user's config.

**Comment by titamrtn** [comment]
> This is a good idea, but from past experience I am nervous about adding this, because it may not be clear that we are deleting them permanently from the user's config.

Maybe by adding a prompt that will notice user that it will delete the content ssh/config.

**Comment by milopersic** [comment]
What?  This isn't happening?

**Comment by TheMaverickProgrammer** [comment]
yall mad dumb for not adding this

**Comment by rendell04** [comment]
Up

**Comment by anishakaul** [comment]
Please someone help! I need that delete target button.

**Comment by zeyuanyin** [comment]
> Thank you. It would be great to have ability to delete it by just right-clicking and then click on delete.


But it is inefficient to delete one by one in this way. 
I just want to clean the connect history but it seems there is no way to clean all with one click.

I try to delete and add the host back in the .ssh/config, but the history is still here.

**Comment by lightmelodies** [comment]
I tried to delete `~/.vscode-server/data/User/globalStorage` on linux or `~/Library/Application\ Support/Code/User/globalStorage` on mac, and the connect history gone. This also break thing like theme settings, but not hard to recovery.

**Comment by MrWangJustToDo** [comment]
up

**Comment by MrWangJustToDo** [comment]
up
