### ISSUE TITLE
Could not get clipboard contents (Remote - WSL)

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode-remote-release#3443]
- VSCode Version: `1.47.3`
- Local OS Version: `Microsoft Windows [Version 10.0.19041.388]`
- Remote OS Version: `Pengwin 20.7.0` (Debian)
- Remote Extension/Connection Type: `WSL`

Steps to Reproduce:

1. Open VSCode from WSL. ( `code .` )
2. Install [Paste JSON as Code](https://marketplace.visualstudio.com/items?itemName=quicktype.quicktype) extension
3. Add a new file `a.ts`
4. Copy JSON string to your clipboard

    ```json
    {
        "a": 1
    }
    ```

5. Run `F1` > `Paste JSON as Code` then enter a symbol name `aa`.

6. You will see an error called `Could not get clipboard contents`.

![image](https://user-images.githubusercontent.com/88981/88875472-e7b8fc00-d253-11ea-9f11-73e0f59b2291.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

I'm wondering that is this problem can be fixed by the extension side?

I also open an issue for the extension there: https://github.com/quicktype/quicktype/issues/1532

**Comment by Chuxel** [comment]
@doggy8088 This is unlikely to be a remote issue.  You can refer the extension author to this extension guide: https://code.visualstudio.com/api/advanced-topics/remote-extensions

They likely are not using the VS Code clipboard API. If they have further issues, they can raise it here for discussion.
