### ISSUE TITLE
excess cpu usage of "node" process!

### ISSUE THREAD

**Issue by dgvai** [microsoft/vscode-remote-release#3446]
Issue Type: <b>Bug</b>

just open anyfile "code ." 

Extension version: 0.44.4
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (2.89GB free)|
|Process Argv|--file-uri=vscode-remote://wsl+Ubuntu-20.04/home/dgvai/.zshrc --remote=wsl+Ubuntu-20.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|       Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2501)|
|Memory (System)|7.84GB (2.89GB free)|
|VM|0%|
</details>

**Comment by Chuxel** [comment]
Which extension are you using? Can you provide your logs? This does not repo for me.
