### ISSUE TITLE
too high cpu ~30% in remote tools and wsl2

### ISSUE THREAD

**Issue by jcbritobr** [microsoft/vscode-remote-release#3448]
Plugin is taking too much cpu  ~30% using wsl2 on win10 64.
os used in vm is ubuntu 20.04
using with golang and bookmarks plugin.

**Comment by aeschli** [comment]
Can you use the Process Explorer to find out which process is using the time?

**Comment by jcbritobr** [comment]
Hello, It was fixed in last windows updated. I couldn't reproduce it anymore. There was something with libc and ubuntu 20.04.
