### ISSUE TITLE
Allow use of nvidia runtime with remote docker devcontainer

### ISSUE THREAD

**Issue by taylorkangbeck** [microsoft/vscode-remote-release#345]
I'd like to be able to do deep learning work in a remote docker container that can access a gpu via nvidia-docker.

I was able to create a .devcontainer for my python project, then by setting the DOCKER_HOST environment variable, I was able to have it spin up the container on my remote machine. However, since the `docker run` happens behind the scenes, I'm unable to specify the nvidia runtime (e.g. `docker run --runtime=nvidia`). So even though I'm able to edit code, nvidia's cuda is unavailable.

Please add support for enabling the nvidia runtime, or more generically, adding arguments to the docker run command that vscode does with the devcontainer.

**Comment by Chuxel** [comment]
@taylorkangbeck Are you using Docker Compose or a Dockerfile?  For a dockerfile, add 
```json
"runArgs": ["--runtime=nvidia"]
```
to devcontainer.json.

For Docker compose, you add `runtume: nvidia` to your service, but you might have to use Docker Compose v2.6 -- The searching I did online indicated it might not be in v3 yet.

**Comment by taylorkangbeck** [comment]
ahh thank you! I can't believe runArgs was staring me in the face like that.
