### ISSUE TITLE
Go to Definition opens /local/home/<user>/project_name/file.cpp

### ISSUE THREAD

**Issue by JohnRThomas** [microsoft/vscode-remote-release#3451]
To recreate:
Open remote cpp file.
Right-click symbol that is defined in that file.
Go To Definition
Second editor opens with local cached version of the file instead of the remote file.

Two editors will be open Foo.cpp (project/Foo.cpp), Foo.cpp (/local/home/<user>/project/Foo.cpp)

Expected outcome:
Symbol opens in editor that is already open.

VSCode
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z (2 wks ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

Extensions:
Remote Development: v0.20.0
Remote - SSH: v0.51.0
Remote - Containers: v0.128.0
C/C++: v0.29.0

**Comment by JohnRThomas** [comment]
I wonder if the c++ extension is using ${workspaceFolder} to open the path, which refers to the local machine and not the remote folder.

**Comment by roblourens** [comment]
If it's still an issue, please file on the CPP extension
