### ISSUE TITLE
Remote SSH not working since update on July 30.

### ISSUE THREAD

**Issue by davepark0323** [microsoft/vscode-remote-release#3452]
- VSCode Version: 1.47.3
- Local OS Version: Windows 10 Pro 2004
- Remote OS Version: Ubuntu 18.04 on virtualbox
- Remote Extension/Connection Type: SSH (Remote-ssh 0.51.0)

I have tried to change a default shell to pwsh, git bash, and wsl bash, but no luck.

It had been working fine, but since update this morning, not working.

I have tested ssh with powershell 7.0.3/wsl bash, but no issue for connection. Only remote-ssh in vscode has an issue now.

-- Here is an output message --
[21:10:18.807] Log Level: 2
[21:10:18.812] remote-ssh@0.51.0
[21:10:18.812] win32 x64
[21:10:18.814] SSH Resolver called for "ssh-remote+postgresql", attempt 1
[21:10:18.814] SSH Resolver called for host: postgresql
[21:10:18.814] Setting up SSH remote "postgresql"
[21:10:18.829] Using commit id "91899dcef7b8110878ea59626991a18c8a6a1b3e" and quality "stable" for server
[21:10:18.831] Install and start server if needed
[21:10:18.836] Checking ssh with "ssh -V"
[21:10:18.896] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[21:10:18.898] Running script with connection command: ssh -T -o ClearAllForwardings=true postgresql bash
[21:10:18.901] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[21:10:19.862] > 674cb0607db6: running
> ]0;C:\WINDOWS\System32\cmd.exe
[21:10:19.862] Got some output, clearing connection timeout
[21:10:19.926] > 674cb0607db6: running
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[21:10:19.969] > Acquiring lock on /run/user/1001/vscode-remote-lock.hdanalyst1.91899dcef7b8110878ea59626991a18c8a6a1b3e
[21:10:19.988] > \ln /run/user/1001/vscode-remote-lock.hdanalyst1.91899dcef7b8110878ea59626991a18c8a6a1b3e.target /run/user/1001/vscode-remote-lock.hd
> analyst1.91899dcef7b8110878ea59626991a18c8a6a1b3e
> Installing to /home/hdanalyst1/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e...
> 674cb0607db6%%1%%
> Downloading with wget
[21:10:35.376] > Download complete
> 674cb0607db6%%2%%
[21:10:35.676] > tar: Skipping to next header
[21:10:35.919] > tar: Exiting with failure status due to previous errors
[21:10:35.925] > WARNING: tar exited with non-0 exit code
[21:10:35.947] > WARNING: /home/hdanalyst1/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/node doesn't exist. Download/untar may have fai
> led.
[21:10:35.960] > WARNING: /home/hdanalyst1/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/server.sh doesn't exist. Download/untar may hav
> e failed.
[21:10:35.967] > SSH_CONNECTION=192.168.56.1 4779 192.168.56.100 22
> LANG=en_US.UTF-8
> XDG_SESSION_ID=9
> USER=hdanalyst1
> PWD=/home/hdanalyst1
> HOME=/home/hdanalyst1
> SSH_CLIENT=192.168.56.1 4779 22
> MAIL=/var/mail/hdanalyst1
> SHELL=/bin/bash
> SHLVL=2
[21:10:36.018] > 
> VSCODE_AGENT_FOLDER=/home/hdanalyst1/.vscode-server
> LOGNAME=hdanalyst1
> XDG_RUNTIME_DIR=/run/user/1001
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
[21:10:36.025] > 
> _=/usr/bin/printenv
> OLDPWD=/home/hdanalyst1/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e
> Starting server with command... /home/hdanalyst1/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/server.sh --host=127.0.0
> .1 --enable-remote-auto-shutdown  --port=0 &> "/home/hdanalyst1/.vscode-server/.91899dcef7b8110878ea59626991a18c8a6a1b3e.log" < /dev/
> null
> Waiting for server log...
[21:10:36.033] > 
[21:10:36.543] > Waiting for server log...
[21:10:37.061] > Waiting for server log...
[21:10:37.575] > Waiting for server log...
[21:10:38.095] > Waiting for server log...
[21:10:38.630] > Waiting for server log...
[21:10:39.132] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
[21:10:39.168] > Server did not start successfully. Full server log at /home/hdanalyst1/.vscode-server/.91899dcef7b8110878ea59626991a18c8a6a1b3e.log >
> >>
> main: line 371: /home/hdanalyst1/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/server.sh: No such file or directory
> <<< End of server log
> 674cb0607db6##32##
[21:10:39.169] Received install output: 674cb0607db6##32##
[21:10:39.171] Resolver error: The VS Code Server failed to start
[21:10:39.175] ------

[21:10:39.514] > 
[21:10:40.051] "install" terminal command done
[21:10:40.051] Install terminal quit with output: 

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by jpear1** [comment]
I am having this same issue on:
VSCode Version: 1.47.3
Local OS: Windows 10 Home 1903
Remote OS: Debian GNU/Linux 10 (buster)

[log.txt](https://github.com/microsoft/vscode-remote-release/files/5005613/log.txt)

**Comment by cosmith-at-flvs** [comment]
Same issue here, I believe. Started this morning after update.

> Version: 1.47.3 (user setup)
> Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
> Date: 2020-07-23T13:12:49.994Z
> Electron: 7.3.2
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.18363
> 



> 8d275f2862ea: running
> Acquiring lock on /home/cosmith/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/vscode-remote-lock.cosmith.91899dcef7b8110878ea59626991a18c8a6a1b3e
> \ln /home/cosmith/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/vscode-remote-lock.cosmith.91899dcef7b8110878ea59626991a18c8a6a1b3e.target /home/cosmith/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/vscode-remote-lock.cosmith.91899dcef7b8110878ea59626991a18c8a6a1b3e
> Found existing installation at /home/cosmith/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e...
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status on port 44910 with wget
> 8d275f2862ea: start     
> sshAuthSock====
> agentPort==44910==      
> osReleaseId==centos==   
> arch==x86_64==
> webUiAccessToken====    
> tmpDir==/run/user/1012==
> platform==linux==       
> 8d275f2862ea: end

**Comment by kicker10BOG** [comment]
Same issue here.

**Comment by hoanghai20021989** [comment]
Same here also

**Comment by roblourens** [comment]
I see this

> [21:10:35.676] > tar: Skipping to next header
> [21:10:35.919] > tar: Exiting with failure status due to previous errors
> [21:10:35.925] > WARNING: tar exited with non-0 exit code

Is the `.tar.gz` still in place after this for you to examine? Might it be corrupted? Do you have a proxy or something that might be interfering with the download?

Or do you have a really old version of tar on your path for some reason?

If you run the "Kill VS Code Server on Host" command and try again, does it work?

**Comment by davepark0323** [comment]
> I see this
> 
> > [21:10:35.676] > tar: Skipping to next header
> > [21:10:35.919] > tar: Exiting with failure status due to previous errors
> > [21:10:35.925] > WARNING: tar exited with non-0 exit code
> 
> Is the `.tar.gz` still in place after this for you to examine? Might it be corrupted? Do you have a proxy or something that might be interfering with the download?
> 
> Or do you have a really old version of tar on your path for some reason?
> 
> If you run the "Kill VS Code Server on Host" command and try again, does it work?

Where can I find "tar.gz" file?

I have a tar version "tar (GNU tar) 1.29" and I don't have any proxy configured.

I have tried multiple times to run the "Kill VS...", but didn't work.

Also, I have tried after removng .vscode-server folder, but didn't work. 

Please let me know if there is anything I need to remove first.

**Comment by jpear1** [comment]
I've run Kill VSCode Server on Host, it also didn't fix the problem. I did get a slightly more helpful `tar` error though:
```
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

Downgrading to version 50.1 or 49.0 did not fix the problem.

I'm running tar 1.30.

The odd thing is, it seems like the tar is actually being extracted. Take a look as these successive `ls`'s I took during the server install process:

[ls1.txt](https://github.com/microsoft/vscode-remote-release/files/5017278/ls1.txt), [ls2.txt](https://github.com/microsoft/vscode-remote-release/files/5017276/ls2.txt), [ls3.txt](https://github.com/microsoft/vscode-remote-release/files/5017277/ls3.txt)

There is clearly a tar file there in ls1 and it seems to get extracted during ls2 and ls3, but I still get an error message in VSCode. I guess it fails partway through and gets removed before that?

**Comment by ddveras** [comment]
Same issue using WSL 2, rolled back VSCode to May 2020 (version 1.46) and it's is working again.

**Comment by roblourens** [comment]
Could you try downloading this onto your remote:  
https://az764295.vo.msecnd.net/stable/91899dcef7b8110878ea59626991a18c8a6a1b3e/vscode-server-linux-x64.tar.gz


and see if it works to untar it with `tar -xf vscode-server-linux-x64.tar.gz`?

**Comment by davepark0323** [comment]
I have downloaded the file above and copied it to my ubuntu and then executed the tar. It worked fine and I can see server.sh script in the folder.

Is it all you need?

**Comment by roblourens** [comment]
That's confusing because those are the exact steps that the script takes, which is producing that error above. Let's try something else. 

- Uninstall the Remote-SSH extension
- Install this build (Download, rename to `.vsix`, run the command "Extensions: Install From VSIX"): 
[remote-ssh-nightly-0.53.0.zip](https://github.com/microsoft/vscode-remote-release/files/5025341/remote-ssh-nightly-0.53.0.zip)
- Try connecting again. It will
  - Print the tar version so we can see whether there's some other tar binary on your path in this ssh session
  - And leave the .tar in place after installation fails, so we can check whether the download is corrupted, or try to do the same operation on the same binary

**Comment by rukmal** [comment]
I have been able to work around this issue (temporarily) by deleting the `~/.vscode-server` directory on the target server.

**Comment by jpear1** [comment]
@roblourens I followed your instructions. A manual tar also failed on ` vscode-server.tar.gz`. Again, `tar --version` gives `tar (GNU tar) 1.30`

Here's all three logs:
[terminal-log.txt](https://github.com/microsoft/vscode-remote-release/files/5044429/terminal-log.txt)
[tar-log.txt](https://github.com/microsoft/vscode-remote-release/files/5044430/tar-log.txt)
[.91899dcef7b8110878ea59626991a18c8a6a1b3e.log](https://github.com/microsoft/vscode-remote-release/files/5044433/91899dcef7b8110878ea59626991a18c8a6a1b3e.log)

I'm not sure if this is true for everyone having this problem, but the internet connection on my machine has to go through VirtualBox. May be related.

**Comment by roblourens** [comment]
@jpear1 Was that the tar that the extension downloaded or did you manually download it from https://github.com/microsoft/vscode-remote-release/issues/3452#issuecomment-668750916?

Can you run `md5` on it? Suspecting that the download is corrupted.

**Comment by jpear1** [comment]
Both files failed to extract, but fail at different points in the process.

Here are both the checksums:
```
$ md5sum vscode-server.tar.gz # Downloaded by the extension
2f31ddc14f338f44a06cd6ec41f08504  vscode-server.tar.gz
```
```
$ md5sum vscode-server-linux-x64.tar.gz # Downloaded directly from link from github comment
8fad740ada444f590eaf1753f454fa29  vscode-server-linux-x64.tar.gz
```

**Comment by nic-kill** [comment]
Also getting this issue, deleting `~/.vscode-server` as per @rukmal 's suggestion did work but hopefully this won't need to be done each time and a fix is found.

**Comment by rukmal** [comment]
> Also getting this issue, deleting `~/.vscode-server` as per @rukmal 's suggestion did work but hopefully this won't need to be done each time and a fix is found.

I have only had to do this once, and it has not come up since. This first happened to me over 2 months ago, so this fix seems to hold.

Perhaps it's a migration-related issue? I'm not too familiar with the source code to provide a better explanation, but this definitely happened to me after a prior upgrade.

I suspect the lock is not being released correctly when you trigger an update with an active connection.

**Comment by LukeSilva** [comment]
I'm also getting this, no mention of `tar` in the log. Deleting `~/.vscode-server` on the remote did not work.
It appears that the untar has worked, with the server directories appearing. MD5 sums are as follows:

```
luke@vps:~/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e$ md5sum server.sh
29e03987a53b0126cf28d396e38d51d9  server.sh
luke@vps:~/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e$ md5sum node
0908c090c37e3fd7356cca61744f5dc6  node
luke@vps:~/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e$ md5sum out/vs/server/main.js
17cd0fec9875f69f9a1022b9e6ffb1e9  out/vs/server/main.js
```

Connection Log:
```
d53e3be81e25: running
Acquiring lock on /home/luke/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/vscode-remote-lock.luke.91899dcef7b8110878ea59626991a18c8a6a1b3e
\ln /home/luke/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/vscode-remote-lock.luke.91899dcef7b8110878ea59626991a18c8a6a1b3e.target /home/luke/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/vscode-remote-lock.luke.91899dcef7b8110878ea59626991a18c8a6a1b3e
Installing to /home/luke/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e...
d53e3be81e25%%1%%
Downloading with wget
Download complete
d53e3be81e25%%2%%
SSH_CONNECTION=[MY-IP] 55560 [REMOTE-IP] 22
LANG=C.UTF-8
XDG_SESSION_ID=3
USER=luke
PWD=/home/luke
HOME=/home/luke
SSH_CLIENT=[MY-IP] 55560 22
MAIL=/var/mail/luke
SHELL=/bin/bash
SHLVL=2
VSCODE_AGENT_FOLDER=/home/luke/.vscode-server
LOGNAME=luke
XDG_RUNTIME_DIR=/run/user/1000
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
_=/usr/bin/printenv
OLDPWD=/home/luke/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e
Starting server with command... /home/luke/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/home/luke/.vscode-server/.91899dcef7b8110878ea59626991a18c8a6a1b3e.log" < /dev/null
Waiting for server log...

*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
*

d53e3be81e25: start
sshAuthSock====
agentPort==45499==
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====
tmpDir==/run/user/1000==
platform==linux==
d53e3be81e25: end
```

**Comment by jpear1** [comment]
@roblourens 
Something a little odd happened before I went to do this. I misinterpreted your comment and went through the following process:
- Manually tried to `gunzip` the files from 12 days ago. This failed on the file downloaded from github and succeeded on the file downloaded by the extension 12 days ago.
- Successfully extracted the successfully unzipped `.tar` archive downloaded 12 days ago.
- Tried to connect using what I later learned was an updated version of the nightly build.
- **Successfully connected**, then closed connection
- Ran `rm -r .vscode-server`
- Tried to reconnect, but failed with the same tar error in the terminal log. This time, however, the extension didn't leave a `.tar.gz` file in place. This is why I think the extension was automatically updated to a new version of nightly.

After this, I went through your instructions again:
- Uninstalled extension and re-installed with your link
- Removed `.vscode` and tried to reconnect
- Found the `.tar.gz` file in place again
- Tried to `gunzip` it, but this time got the same error I got with the archive I downloaded directly from your github comment. ([error](https://pastebin.com/yMmjfpPZ))
- Untarred both archives in test folders and got these results:
```
application/vscode-server-linux-x64$ tree -L 2 # downloaded by extension
.
├── node
└── server.sh

0 directories, 2 files
```
```
github/vscode-server-linux-x64$ tree -L 2 # downloaded from github comment
.
└── extensions
    ├── html-language-features
    ├── jake
    ├── markdown-language-features
    ├── ms-vscode.js-debug-companion
    └── typescript-language-features

6 directories, 0 files
```

**Comment by roblourens** [comment]
Ok, so it seems clear that the tar can't be downloaded properly. And it sounds like basically the same thing happens when you download it manually vs when the extension downloads it. Really confusing. You don't get any errors when downloading it manually? Do you have a proxy, or anything else unusual with your internet connection?

**Comment by jpear1** [comment]
I don't get any errors when downloading, even with `wget --verbose`. Also, it works fine on my WSL Ubuntu 20.04 installation.

However, I finally managed to replicate this with a file besides the vscode server archive. Earlier, I tried downloading a somewhat small `.tar.gz` file and didn't have any corruption, but I tried a large one (200MB) and finally got the same error.

So I guess it's a problem with my VM's connection that appears very infrequently, so that it only affects large packages? Kind of odd, I would have thought that `wget` or something involved in the download would verify a download's integrity.

**Comment by roblourens** [comment]
> I would have thought that wget or something involved in the download would verify a download's integrity.

I would assume that it would error if the download is interrupted, but it won't verify that the bits were transferred correctly.

**Comment by scj7508** [comment]
I am having this same issue on:
Local OS: Windows 10 Pro Version 1909
Remote OS: ubuntu-20.04.1/centos7  on VirtualBox
However, It's ok when  the same os is on hyper-v ...

So,  I thought there is some problem with my local netwok created by virtualbox ,
It's ok on the same os created by hyper-v, It's really strange .

**Comment by roblourens** [comment]
Continuing discussion re: tar issues: https://github.com/microsoft/vscode-remote-release/issues/3396
