### ISSUE TITLE
No file based recommendation when workspace extension is installed locally

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#3453]
- Install Python extension locally.
- Reopen in DevContainer.
- Python extension is now disabled.
- Open Python file in DevContainer.
- Expected: Python extension gets recommended.
- Actual: No recommendation is shown.

The recommendation is shown when the Python extension is not installed locally.

**Comment by chrmarti** [comment]
Related: https://github.com/microsoft/vscode-remote-release/issues/413

**Comment by rebornix** [comment]
I'm still not seeing the recommendation, if that's what I should test.

**Comment by sandy081** [comment]
Are you seeing the recommendation in normal window? 
Can you please try on a fresh user data dir?

**Comment by chrmarti** [comment]
This works for me now. Closing and labelling as verified. Thanks.

**Comment by sandy081** [comment]
Thanks @chrmarti..  I was about to comment that it is working for me.
