### ISSUE TITLE
devcontainer.json not loading custom localEnv values correctly using WSL2

### ISSUE THREAD

**Issue by ewhitesides** [microsoft/vscode-remote-release#3456]
- VSCode Version: 1.47.2
- OS Version: WSL2 Ubuntu

Steps to Reproduce:

0. export MY_TOKEN='myvalue'
1. create a project with ./devcontainer/devcontainer.json
2. add the following params: 
"build": { 
		"args": { 
			"MY_TOKEN":"${localEnv:MY_TOKEN}"
		} 
}
3. ctrl-shift-p -> rebuild and reopen container
4. note how it fails to load value of MY_TOKEN when generating the build command.
5. using something like ${localEnv:HOME} does seem to work though, so it seems to be only affecting custom env values
6. directly making the docker build command in terminal seems to work just fine.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
Found a way to extract the environment variables from a WSL login shell. If your `.profile` / `.bash_profile` sources `.bashrc`, this will include the environment variables from that too. Note that some `.bashrc`s have a check for whether the shell is interactive and terminate silently when not, so environment variables from the `.bashrc` would still be missing. (Haven't found a way to run an interactive login shell without invoking the shell a second time which could cause problems by sourcing the profile and rc a second time.)

**Comment by connor4312** [comment]
I'm having some trouble reproducing this. I added an `export MY_VERSION="14"` to the top of .zshrc (my default shell), .bashrc, and .profile (there was no .bash_profile) and was unable to access `${localEnv:MY_VERSION}` in the devcontainer.json.

**Comment by chrmarti** [comment]
@connor4312 Could you retry with setting that variable in `~/.zshenv`? (http://zsh.sourceforge.net/Intro/intro_3.html)

**Comment by chrmarti** [comment]
Closing again for verification.
