### ISSUE TITLE
Lost connection to the remote server

### ISSUE THREAD

**Issue by JaveyWang** [microsoft/vscode-remote-release#3459]
Issue Type: <b>Bug</b>

I am using a macbook pro 2020 laptop, for no reason at all, the remote server often lost connection (maybe half an hour), and I have to reconnect it, this will interrupt my working progress.

Extension version: 0.51.0
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.5.0
Remote OS version: Linux x64 4.4.0-21-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|-psn_0_3089138|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.21.2.12|
|OS|Linux x64 4.4.0-21-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (56 x 1200)|
|Memory (System)|125.79GB (17.87GB free)|
|VM|0%|
</details>

**Comment by Chuxel** [comment]
Could you post your logs from when this happened?
