### ISSUE TITLE
Nodejs Debugging when node is installed via nvm (ie. node is in a different folder but exists in PATH)

### ISSUE THREAD

**Issue by jitcoder** [microsoft/vscode-remote-release#346]
- VSCode Version: April 2019 (version 1.34)
- Local OS Version: macOS 10.14.4
- Remote OS Version: AWS AMI EC2 instance (w.e. the free tier one is with 1gb mem 1 cpu)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Create AWS EC2 instance
2. Create/Use security group that allows port 22
3. SSH into the box
4. `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash`
5. `source ~/.bashrc`
6. `nvm install 10`
7.  `mkdir ~/projects`
8. `mkdir ~/projects/hello-node`
9. `cd ~/projects/hello-node`
10. `npm init -f`
11. Open this remote folder after setting up and connecting to the host
12. create index.js
```javascript
console.log('hello world!');
```
13. run

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

After following reproduce steps you should see an error complaining about not being able to find node in path.
I reconnected to the host to make sure the updated PATH env var is picked up with same results.

I verified my path is correct, /usr/local/bin/node however does not exist, node is in PATH but in a different folder.

I figured even though the error is complaining about not finding node in path its not really using path so I created a symlink and then it worked.

**Comment by roblourens** [comment]
If the vscode server was started before installed nvm, then nvm will not yet be in the path for vscode's environment. You can force it to restart by running "Uninstall VS Code Server from Host".

Your bashrc should be run in the server's environment but we are still working on these issues...

**Comment by roblourens** [comment]
Lots has changed, let me know if this is still an issue.
