### ISSUE TITLE
Redundant copy

### ISSUE THREAD

**Issue by luomou97** [microsoft/vscode-remote-release#3460]
Issue Type: <b>Bug</b>

when i use remote development and open a jupyter file(.ipynb), once i paste a piece of code to jupyter, the terminal bash will paste the same copy, too.

Extension version: 0.20.0
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.4.0-42-generic
![818IJWD$ K{WA%}OS7)YFKC](https://user-images.githubusercontent.com/44665299/89142006-cc622f80-d578-11ea-94fa-3d6d6b41b7e9.png)

**Comment by chrmarti** [comment]
This looks like it is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
