### ISSUE TITLE
Node Debugging - autoAttachChildProcesses Can't Attach to Subprocess on Linux aarch64

### ISSUE THREAD

**Issue by MrRogerHuang** [microsoft/vscode-remote-release#3461]
- VSCode Version: 1.47.3
- Local OS Version: macOS Catalina 10.15.6
- Remote OS Version: Ubuntu 20.04.1 LTS aarch64 on Raspberry Pi 4
- Remote Extension/Connection Type: SSH
- autoAttachChildProcesses is enabled in launch.json.

Steps to Reproduce:

1. Try debug this simple example by VSCode Remote - SSH extension on Ubuntu 20.04.1 LTS aarch64 on Raspberry Pi 4:
```git clone https://github.com/MrRogerHuang/NodeForkExample```
2. Only the main program process is attached as shown in CALL STACK in this screen shot:
![image](https://user-images.githubusercontent.com/49478723/89139316-dc761100-d570-11ea-911f-e8887b85e550.png)

Additionally, if I debug NodeForkExample on Raspbian 10 32-bit on the same Raspberry Pi 4, the subprocess is correctly attached:
![image](https://user-images.githubusercontent.com/49478723/89143886-afc8f600-d57e-11ea-9525-3ae32a679b4a.png)

**Comment by MrRogerHuang** [comment]
VSCode 1.48.0-insider and Remote - SSH (Nightly) v2020.7.38340 don't fix this problem.

**Comment by MrRogerHuang** [comment]
I find a workaround - using compound, e.g.:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [

    {
      "name": "Attach",
      "port": 12345,
      "request": "attach",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "type": "node"
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Debug",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${workspaceFolder}/index.js",
      "autoAttachChildProcesses": true
    }
  ],
  "compounds": [
    {
      "name": "Compound",
      "configurations": ["Debug", "Attach"]
    }
  ]
}
```

So, the actual problem is autoAttachChildProcesses does not work on Ubuntu aarch64 on Raspberry Pi 4.

**Comment by bamurtaugh** [comment]
Thanks for the update @MrRogerHuang. Since it looks like this was resolved, going to close this thread, but please let us know if you have any other questions or feedback, and we'd be happy to discuss further or reopen.
