### ISSUE TITLE
dataloader's workers are out of shared memory

### ISSUE THREAD

**Issue by trevordowdle** [microsoft/vscode-remote-release#3462]
I'm running some deep learning within a container and I get the following error:

`DataLoader worker (pid 12613) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.`

In short I need to increase the shared memory of the docker container.
https://github.com/pytorch/pytorch/issues/2244

Is there a way to do with this within the this vs code plugin so that it boots up or creates a container with more shared memory?

**Comment by Chuxel** [comment]
If you are on macOS or Windows, you'll can give Docker more memory.

1. Right-click on the Docker task bar item and select Settings / Preferences.
2. Go to Resources > Advanced to increase CPU, Memory, or Swap.

**Comment by trevordowdle** [comment]
Thank you for your response,

I did leave out some relevant information, I am on Windows.

In my case I am only seeing Proxies, Network, and WSL Integration under Resources.  With no Advanced option visible.

![image](https://user-images.githubusercontent.com/4210581/89199727-37f1d000-d56c-11ea-99aa-cce5c21cb750.png)

**Comment by Chuxel** [comment]
Got it, in that case, you can give more capacity to WSL2 itself: https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig

**Comment by chrmarti** [comment]
Not sure this applies, but `docker run` has a `--shm-size` option. You can add that with `"runArgs"` in your devcontainer.json.

**Comment by chrmarti** [comment]
Closing as question.
