### ISSUE TITLE
Function / method list on remote ssh connection.

### ISSUE THREAD

**Issue by hdale** [microsoft/vscode-remote-release#3464]
I have VSC 1.47.3 with the new preview version extension of Remote Development (suite) 0.20.0.
I hope I just did not find this feature, but I think it is missing on remote ssh connection, to view the function list of a PHP file. When opening a file from a local folder I get the function list with cmd + shift +O, but not on remote connection. 
Pls. add this feature if possible.

**Comment by bamurtaugh** [comment]
Trying to determine if this is a bug or feature request. Are you still experiencing this @hdale? I would have thought cmd + shift +O would work via remote SSH, but perhaps this is a feature request.

**Comment by roblourens** [comment]
You can install a PHP language extension
