### ISSUE TITLE
VS Code does not prompt to install Remote-Containers extension

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-remote-release#3466]
- VSCode Version: 1.47.3
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Clone https://github.com/burkeholland/grand-central-station in WSL
2. Open project in VS Code (Remote WSL)
3. Remote - Containers extension is not recommended even though a .devcontainer folder is present

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

![2020-08-03_10-28-39](https://user-images.githubusercontent.com/686963/89217856-89ad5100-d592-11ea-98a2-29b4a82414ce.gif)

**Comment by chrmarti** [comment]
Reproduced without WSL in 1.47.3. I get a notification for installing Python when opening a Python file, but none for Remote-Containers when opening a devcontainer.json.

@egamma This might be expected given the configuration. Should we change that to also show a notification when opening a devcontainer.json?

**Comment by egamma** [comment]
In the scenario from @burkeholland the user opens a folder with a .devcontainer configuration. The user does not open the devcontainer.json file. Recommending the Remonte Containers in this scenario makes good sense, but recommending an extension based on the existence of the devcontainer configuration in the workspace is currently not done.

There is config based extension support for git `configBasedExtensionTips`, but the support is currently specific to git and its remotes. @sandy081 I assume it is currently not possible to use this configBasedExtensionTips for this scenario?

**Comment by egamma** [comment]
@chrmarti a recommendation for devcontainer.json was added for 1.48 and in the latest insiders I'm getting a recommendation when opening a devcontainer.json file. 

![image](https://user-images.githubusercontent.com/172399/89503264-97e3b300-d7c6-11ea-83ed-2029d2dd661e.png)

**Comment by sandy081** [comment]
> There is config based extension support for git configBasedExtensionTips, but the support is currently specific to git and its remotes. @sandy081 I assume it is currently not possible to use this configBasedExtensionTips for this scenario?

@egamma It is possible to add Remote containers extension as a workspace config based recommendation and can also make it important - following notification is shown if configured

<img width="466" alt="image" src="https://user-images.githubusercontent.com/10746682/89509145-383dd580-d7cf-11ea-8059-5443194d0acc.png">

**Comment by burkeholland** [comment]
This would work. Would it be appropriate to make that change automatically when a .devcontainer configuration is added?

**Comment by sandy081** [comment]
To verify -

- Open a repo that has `.devContainer` folder in VS Code insiders (user fresh user data directory). Eg: https://github.com/microsoft/vscode-dev-containers/tree/master/containers/typescript-node

- Make sure you get a recommendations prompt for this repository
- Install action installs remote containers extensions
- Show Recommendations shows workspace extensions which has remote containers extension

**Comment by alexr00** [comment]
@sandy081 The install action in the recommendations prompt only installed the first recommended extension (containers). The other two recommended extensions were not installed. Is this expected?

**Comment by sandy081** [comment]
Can you please let me know what extensions are they? A screenshot would be great.

**Comment by alexr00** [comment]
I used the Java 8 dev container folder from the vscode-dev-containers repo. I went to grab a screen shot, and not I don't get the notification for recommendations at all. I used a fresh users-data-dir.

**Comment by alexr00** [comment]
No notifications: 
![image](https://user-images.githubusercontent.com/38270282/92227696-ed36e100-eea6-11ea-804d-c463970b19a4.png)

**Comment by sandy081** [comment]
Good catch, its not working when there are no workspace recommendations. Fixed.
