### ISSUE TITLE
Unable to Open empty folder in container

### ISSUE THREAD

**Issue by StevenDavisTechNotes** [microsoft/vscode-remote-release#3467]
Issue Type: <b>Bug</b>

1. Open VS Code in an empty folder without "_" in the path.
2. The only extension if Remote - Container.  Docker Desktop is set to Linux containers.  Wsl2 shows docker-desktop, but Ubuntu is the default in WSL.
3. Open folder in container
4. Select Node 8 or Python 3
5. VSCode attempts to build image
Setting up container for folder or workspace: c:\Src\Projects\Containers\VSCodeAttach3
Run: docker build -f c:\Src\Projects\Containers\VSCodeAttach3\.devcontainer\Dockerfile -t vsc-vscodeattach3-cc8573c941abe3b73d88c5645827f95d c:\Src\Projects\Containers\VSCodeAttach3\.devcontainer
Failed: Building an image from the Dockerfile.
Error: Unable to start terminal process: CreateProcess failed
        at new WindowsPtyAgent (c:\Users\Steven.Davis\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsPtyAgent.js:63:36)

6. The very same docker build command pasted in PowerShell or cmd is successful.

Extension version: 0.81.1
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.19041
Fetching remote diagnostics for 'Dev Container: Node.js 8' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz (8 x 3494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.98GB (18.08GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'Dev Container: Node.js 8' failed.
</details>

**Comment by chrmarti** [comment]
Please update to the latest version of VS Code and Remote-Containers and check if the problem is still there.

**Comment by StevenDavisTechNotes** [comment]
Thank you for solving my issue.  Don't know how VS Code got out-ot-date.
Thank you, Steven
