### ISSUE TITLE
Selecting 'edit' for SSH config file with `~` in path fails with error EACCES

### ISSUE THREAD

**Issue by rootAvish** [microsoft/vscode-remote-release#347]
Issue Type: <b>Bug</b>

Reproduction steps:

Setup a vagrant VM.

Get a ssh config from the vagrant command, as with: `vagrant ssh-config > ~/.ssh/vagrant-ssh`

Add this config file to the "Remote:SSH config file" entry from the configuration.

- From the `Remote-SSH: connect to host...` command Go to `configure ssh host` option, choose file with path `~/.ssh/vagrant-ssh`

Nothing happens, it's a silent failure, however the developer tools console logs this error:

`ERR EACCES: permission denied, mkdir '~': Error: EACCES: permission denied, mkdir '~'
`

Extension version: 0.37.0
VS Code version: Code - Insiders 1.35.0-insider (a69d0f8b218498e22b7c3a0f76926cc6322e6106, 2019-05-17T05:15:22.680Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.66GB free)|
|Process Argv|-psn_0_1577345|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Yes, the ssh config option only works with an absolute path currently...

**Comment by sbatten** [comment]
not working on windows

**Comment by roblourens** [comment]
Verification steps: On windows, set `"remote.SSH.configFile"` to a path that starts with `~`.
