### ISSUE TITLE
OpenSSH integration: intercept askpass prompts/support PKCS#11 prompts

### ISSUE THREAD

**Issue by Flameeyes** [microsoft/vscode-remote-release#3470]
Currently, there doesn't seem to be any way to provide answers to askpass prompts on Windows, making it impossible to answer prompts such as those introduced by PKCS#11 PIN requests.

If I understand this correctly, currently the SSH support does explicitly prompt the user for password or private key passphrase, but it does so with prompt matching rather than implementing an askpass rpc command.

**Comment by roblourens** [comment]
Also see https://github.com/microsoft/vscode-remote-release/issues/3432 for implementing the same prompt matching

**Comment by Flameeyes** [comment]
Thanks!

`"remote.SSH.useLocalServer": true` was already set, but it doesn't seem to make a difference.

`"remote.SSH.showLoginTerminal": true` does work with the prompt up. I've subscribed to the other issue to follow up on the more human-friendly option :)

**Comment by roblourens** [comment]
> "remote.SSH.useLocalServer": true was already set, but it doesn't seem to make a difference.

Hm. In your user settings? This is my preferred way forward and the other direction is sort of a workaround. Could you share the log from the Remote-SSH output channel when trying to log in with this set?

**Comment by Flameeyes** [comment]
![image](https://user-images.githubusercontent.com/74834/89331940-7a113380-d68a-11ea-81ad-ce3ffec4a807.png)

Yeah it looks like this was enabled by default for me on my copy. It's on Windows 10.

So I need to make a correction, now that I know what to look for, it does work if I click "details" when it would otherwise timeout, and type in the PIN. So yeah that works better than the other setting :)

**Comment by roblourens** [comment]
Here is the tricky thing, this setting has a platform-specific default and isn't applied on windows unless it is literally configured in your settings.json with `"remote.SSH.useLocalServer": true`, so just because the checkmark is checked in the UI, doesn't mean it will be applied on Windows. Sorry about this, I need a better solution.

**Comment by Flameeyes** [comment]
Okay setting it straight to the JSON had it explode at first, but it looks like it might have been caused by it defaulting to use Git's SSH binary (I had not realised that Git for Windows install its own, more recent SSH version… it's not first in the PATH!)

[remotessh.log](https://github.com/microsoft/vscode-remote-release/files/5028385/remotessh.log)

Then I explicitly had it go for the ssh-in-PATH (which is the OpenSSH_for_Windows build), and that… worked perfectly fine!

**Comment by roblourens** [comment]
Huh, I don't know why git ssh is crashing, many people use that. But I'm glad you got it working!
