### ISSUE TITLE
Basic node.js debugging does not work

### ISSUE THREAD

**Issue by hypermoose** [microsoft/vscode-remote-release#3471]
- VSCode Version:1.47.3
- Local OS Version: Windows 10 1909
- Remote OS Version: Raspbian 10
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Setup an SSL connection to a Raspberry Pi 4 
2. Create a simple node.js app via npm init and just one line Console.log("hello");
3. Create a launch.json of type node
4. Hit debug and the app starts on the remote machine but breakpoints do not work and console output does not show up

Does this issue occur when you try this locally?:  No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by hypermoose** [comment]
I am manually able to run "node --nolazy --inspect-brk=9229 index.js" via Terminal and then do an attach and get debugging to work.  Is there something I can do to launch.json to make this more seamless?  I see no errors in Output

**Comment by roblourens** [comment]
If this is still an issue, please file an issue on the microsoft/vscode-js-debug repo
