### ISSUE TITLE
command 'opensshremotes.openEmptyWindow' not found

### ISSUE THREAD

**Issue by drjinying** [microsoft/vscode-remote-release#3473]
Hi,

I'm having issue with VS Code on Ubuntu 20.04.
Nothing happened when I clicked "Remote-SSH: Connect to host..."

In the output panel I saw:

[2020-08-04 17:15:31.644] [renderer1] [error] command 'opensshremotes.openEmptyWindow' not found: Error: command 'opensshremotes.openEmptyWindow' not found
    at u._tryExecuteCommand (file:///snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3944:836)
    at file:///snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3944:717

Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:51:39.791Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic snap

**Comment by tomer1** [comment]
Same with linux Manjaro - gnome 
VS Code:1.47.3
Electron: 7.1.14
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.19-2-MANJARO

**Comment by yaazkal** [comment]
Hi, same error here on FreeBSD: `command 'opensshremotes.openEmptyWindow' not found`

That message appears as an error notification but not in the output log.

![image](https://user-images.githubusercontent.com/5897701/94828441-175cbf80-03cf-11eb-9c27-5331c1075e67.png)

```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-07-29T19:17:52.746Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: FreeBSD x64 12.1-RELEASE-p10
```

**Comment by roblourens** [comment]
Very strange, if this is still an issue, can you tell me where you click the command when you see this?
