### ISSUE TITLE
Python 3 debug on SSH host shows error "Cannot read property 'trim' of null"

### ISSUE THREAD

**Issue by seyong92** [microsoft/vscode-remote-release#348]
- VSCode Version: 1.35.0-insider
- Local OS Version: macOS 10.14.4
- Remote OS Version: Ubuntu 16.04.5 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Go to a project using python 3.5
2. Click "Debug" -> "Start debugging"
3. Shows error "Cannot read property 'trim' of null"

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by yihao31** [comment]
I meet the same problem when I use conda-env to debug my code. I use Python 3.7.3. Local Version is  Windows 10. Have you solved this problem?
![shot_20190517215709](https://user-images.githubusercontent.com/22350011/57933362-b9216080-78ef-11e9-8060-2a2b49795825.png)

**Comment by jicowan** [comment]
Getting the same error when connecting to the sample python container (MacOS & Code Insiders)

**Comment by permissionx** [comment]
I encountered this problem too no matter whether use a remote conda environment.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/73867
