### ISSUE TITLE
Low memory remotes - too many threads and too much RAM used

### ISSUE THREAD

**Issue by jp31415926** [microsoft/vscode-remote-release#3482]
- VSCode Version: 1.48.0 (latest insiders)
- Local OS Version: Windows 10 x64
- Remote OS Version: Ubuntu 16.04.4 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

Trying to use SSH remote to edit files on a makefiile project on a remote linux machine that only has 4GB of RAM and 2 Intel Atom CPU codes. VSCode kicks off multiple threads and locks the machine up because of memory usage or CPU usage. Users need a way to limit how many threads are run on the machine and how much RAM is used.

**Comment by busslina** [comment]
Same issue with Raspberry Pi 3 wiith 1GB ram
