### ISSUE TITLE
Dev Container - postStartCommand hangs

### ISSUE THREAD

**Issue by tdowdle** [microsoft/vscode-remote-release#3488]
- VSCode Version: 1.47.3
- Local OS Version: Mac OS Catalina 10.15.6
- Remote OS Version: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-12
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1.  From a new folder create a db.json file with the following contents:
`{
  "test": [
    { "id": 1,
      "name": "ABC"
   }
 ]
}`
2. Remote-Containers: Open Folder in Container.  - Select the node 12 pre configured image
3. Modify the devcontainer.json
- forward port 3000
- install node package json-server post create
- run the json-server post start
```
"forwardPorts": [3000],
"postCreateCommand": "npm install --save-dev json-server",
"postStartCommand": "npx json-server --watch db.json"
```
4. Rebuild the container.

What happens:

During the rebuild process, VS Code hangs on starting server.. 
The problem arises with the `postStartCommand` 

Expect to happen:

The rebuild to finish, and then be able to automatically launch the json server when starting the container.

**Comment by chrmarti** [comment]
We wait for the `postStartCommand` to finish because we don't know if anything depends on it or not. You could add a `&` to the end of the command to let the shell fork a detached subprocess and continue.
