### ISSUE TITLE
Add 'Connect Current Window to Host' to Remote Quick Access

### ISSUE THREAD

**Issue by andycraig** [microsoft/vscode-remote-release#3490]
With the 'Remote - SSH' extension, clicking the Remote 'Quick Access' status bar item in the lower left corner shows these commands:

- Remote-SSH: Connect to Host...
- Remote-SSH: Open Configuration File...
- Remote-SSH: Getting Started

I would like to suggest that the command 'Remote-SSH: Connect _Current Window_ to Host...' be added to these. This would increase its discoverability (I found out about this command via an Issue, #3116). Also, I find I use it a lot more than 'Remote-SSH: Connect to Host...', and it would be nice if it was that little bit more accessible.

Thank you for these fantastic extensions!

**Comment by roblourens** [comment]
Sure. If the remote-containers extension gets a dozen commands there, why can't ssh have one more... 🤔

**Comment by andycraig** [comment]
Thank you very much!
