### ISSUE TITLE
dev-container & createFileSystemWatcher behaviour

### ISSUE THREAD

**Issue by CaribouJohn** [microsoft/vscode-remote-release#3491]
I have searched for duplicates and the nearest I found was a problem #1381 which is the same but in wsl. I tested this on code-insiders today.

Version: 1.48.0-insider (user setup)
Commit: 2277c8e2a3e1cc630a6397301ba54a1dccd8a60d
Date: 2020-08-07T11:32:09.993Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.20185

- VSCode Version: 1.48.0-insider
- Local OS Version: Win 10 
- Remote OS Version: 
[sagadmin@b5ac36a8b7b2 apama-dev-container]$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.8 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.8"

- Remote Extension/Connection Type: Docker dev-container

Steps to Reproduce:

1. Create FileSystemWatcher
     `this.fsWatcher = workspace.createFileSystemWatcher("**/*.dependencies");`
2. trigger changes in the watched resource 
     `this.fsWatcher.onDidChange((_item) => {...}`

The problem doesn't happen in ssh or wsl , only when the extension is activated in a dev-container

It appears that the File System watcher isn't actually triggering. Perhaps it isn't watching the right place (the workspace is the default mounted local directory in the container) or because of the indirection of docker/containerisation it isn't doing the right thing?

Does this issue occur when you try this locally?: No

**Comment by chrmarti** [comment]
What's the local (Windows) path of the mounted folder? And which version of Docker Desktop do you have installed?

**Comment by CaribouJohn** [comment]
I attached the setup of the dev container 
[apama-dev-container.zip](https://github.com/microsoft/vscode-remote-release/files/5092801/apama-dev-container.zip)

The setup was  at c:/development/docker/apama-dev-container 

which appears to the the mounted volume inside the container.

It loads an extension I wrote that uses the file system watcher to determine if the contens of the workspace change

(the extension : https://github.com/CaribouJohn/pysys-vscode-extension)

**Comment by chrmarti** [comment]
Looks like https://github.com/microsoft/WSL/issues/4739. We are tracking that on our side as https://github.com/microsoft/vscode-remote-release/issues/3497.
