### ISSUE TITLE
Can't install extensions dependent on Azure Account using SSH Remote

### ISSUE THREAD

**Issue by AronT-TLV** [microsoft/vscode-remote-release#3492]
Issue Type: <b>Bug</b>

I am running VS Code remote with ssh.

When I try to install on the remote ssh server an extension I have installed successfully on my local machine, but that is dependent on Azure Account extension, I get the following error:
```
Unable to install extension 'ms-vscode.azure-account' as it is not compatible with VS Code '1.47.3'.
```

Even if I preinstall the `azure-account` extension on the remote ssh (which I can do), I get the above error. 
Some examples of extensions that give that error when I try to install them on the ssh side:
mshdinsight.azure-hdinsight
ms-azuretools.vscode-cosmosdb
ms-kubernetes-tools.vscode-aks-tools

Extension version: 0.51.0
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 4.15.0-1092-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.89GB free)|
|Process Argv|-psn_0_86037|
|Screen Reader|no|
|VM|22%|

|Item|Value|
|---|---|
|Remote|SSH: dmdevspark01.westeurope.azurecontainer.io|
|OS|Linux x64 4.15.0-1092-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (4 x 2397)|
|Memory (System)|15.64GB (1.03GB free)|
|VM|0%|
</details>

**Comment by RMacfarlane** [comment]
@sandy081 I haven't been able to reproduce this myself yet, but there's been a similar report to this about the GHPRI extension: https://github.com/microsoft/vscode-pull-request-github/issues/2006

It seems like sometimes the remote just tries to install the latest version of an extension from the marketplace instead of the version that's compatible with the current VSCode version

**Comment by sandy081** [comment]
VS Code client and server will always be in sync with product version. I can only expect this error to happen if server is not on the same version as client.

May I know if users can repro this consistently and if so what are the versions of client & server?

**Comment by AronT-TLV** [comment]
I listed the version above, but since this was opened there have been newer versions and the problem has gone away. It must have been a temporary glitch in that particular version.

Thanks
