### ISSUE TITLE
bug/feature - extension install

### ISSUE THREAD

**Issue by iamrekas** [microsoft/vscode-remote-release#3493]
- VSCode Version: 1.47.3
- OS Version: win 10

Steps to Reproduce:

1.open remote connection
2.try install any extension

Available install only on remote connected server. it's wrong, cause i wanna install on local, but must to open new instance to install local... 

and version if installed SPECIFIED installed already please DON't UPDATE.. force update IS NOT GOOD! sometimes must install older version for bug workaround in new version.

Srry, if it already fixed.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
Yah this is designed because in a remote window it is more obvious to install an extension that can work on remote window remotely.

**Comment by sandy081** [comment]
There is now a new command `Install Remote Extensions Locally` available to install remote extensions locally.
