### ISSUE TITLE
Devcontainer extensions specify versions

### ISSUE THREAD

**Issue by iamrekas** [microsoft/vscode-remote-release#3494]
In .devcontainer.json is option extensions - for an array of extension IDs, even better can be if it's can have version.
For example: fellixfbecker.php-debug@1.0.0

**Comment by chrmarti** [comment]
Remote-Containers uses the CLI to install a specific version. Currently this version is not pinned by the CLI. For now you can turn off automatic update of extensions to keep the version you specified in the devcontainer.json.

@sandy081 Assigning to you for the missing pinning. I thought we had an issue for that, but can't find it at the moment.

**Comment by sandy081** [comment]
Here is the issue https://github.com/microsoft/vscode/issues/63903 to support pinning.

Closing this as duplicate
