### ISSUE TITLE
Upgrade to `mosh` in terminal if available

### ISSUE THREAD

**Issue by timsuchanek** [microsoft/vscode-remote-release#3499]
While I'm aware, that the [mosh](https://mosh.org/) protocol [can't be used](https://github.com/microsoft/vscode-remote-release/issues/334) as a replacement for the ssh protocol due to lack of port forwarding, it should be possible to use `mosh` for the terminal windows.

That is already possible with a workaround - I can start a local terminal and `mosh` into my instance.

Instead, I would like `mosh` automatically to be used if available on the remote host.

The main reason for me is speed of typing and stability in 4G of mosh.

Do you think that's possible?

Thanks!

**Comment by achimnol** [comment]
I second the request, mosh for the **terminals** (not for the remote development extension), either manually configured or automatically detected.
