### ISSUE TITLE
Allow customization of $PATH for Building Docker Container

### ISSUE THREAD

**Issue by AngellusMortis** [microsoft/vscode-remote-release#35]
If you are pulling Docker images from the Google Container Registery, you need `gcloud` installed, which on many systems is installed by default at `~/google-cloud-sdk/bin/docker-credential-gcloud`.

This path is obviously not in the path by default. It seems that VS Code is not following any `rc` file for terminals to initialize a custom path. It would be nice if there was a good way to specify the PATH that gets used (if their already is, let me know can close out the ticket).

**Comment by chrmarti** [comment]
Why do you not want to add it to your regular PATH?

**Comment by AngellusMortis** [comment]
I have it added in my PATH in my `zshrc` file, but VS Code does not use that. On Ubuntu, I can actually install `gcloud` from a PPA and get it in the default Path, but on MacOS, there is no option to do that.

**Comment by chrmarti** [comment]
VS Code tries to read the environment variables from the default shell. What is `process.env.SHELL` in VS Code's dev tools (Help > Toggle Developer Tools)?

Also check if you have set zsh as your default shell, You can set it with:
```
chsh -s `which zsh`
```

**Comment by AngellusMortis** [comment]
My default is `zsh`, but it is not inheriting the $PATH variable from my `.zshrc`.
 
![image](https://user-images.githubusercontent.com/490848/57221649-00455280-6fce-11e9-8b6a-d2708689d8e2.png)


How is it initializing the environment variables for the default shell?

**Comment by chrmarti** [comment]
Is the terminal screenshot from the internal terminal when launching from the dock?

What's the error message you see that lets you conclude the PATH is incomplete?

**Comment by AngellusMortis** [comment]
> Is the terminal screenshot from the internal terminal when launching from the dock?

No, it was an external one, but I get the same thing in the integrated terminal as well. 

> What's the error message you see that lets you conclude the PATH is incomplete?

Sorry, it took a bit to set this back up. Like I said, I had used a PPA to actually put `gcloud` in the system $PATH, but I put it back to where Google installs it (`~/google-cloud-sdk`). This is the error I get:

```
Setting up container for folder: /home/cbailey/dev/groot
Run: docker-compose -f /home/cbailey/dev/groot/docker-compose.yml -f /home/cbailey/dev/groot/.devcontainer/docker-compose.vscode.yml -f /home/cbailey/dev/groot/docker-compose.override.yml up -d
Creating network "groot" with the default driver
Building web
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/local/lib/python3.6/dist-packages/compose/cli/main.py", line 127, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python3.6/dist-packages/compose/cli/main.py", line 1080, in up
    to_attach = up(False)
  File "/usr/local/lib/python3.6/dist-packages/compose/cli/main.py", line 1076, in up
    silent=options.get('--quiet-pull'),
  File "/usr/local/lib/python3.6/dist-packages/compose/project.py", line 475, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent)
  File "/usr/local/lib/python3.6/dist-packages/compose/service.py", line 358, in ensure_image_exists
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/compose/service.py", line 1082, in build
    platform=self.platform,
  File "/usr/local/lib/python3.6/dist-packages/docker/api/build.py", line 251, in build
    self._set_auth_headers(headers)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/build.py", line 313, in _set_auth_headers
    credstore_env=self.credstore_env
  File "/usr/local/lib/python3.6/dist-packages/docker/auth.py", line 96, in resolve_authconfig
    authconfig, registry, store_name, env=credstore_env
  File "/usr/local/lib/python3.6/dist-packages/docker/auth.py", line 127, in _resolve_authconfig_credstore
    store = dockerpycreds.Store(credstore_name, environment=env)
  File "/usr/local/lib/python3.6/dist-packages/dockerpycreds/store.py", line 25, in __init__
    self.program
dockerpycreds.errors.InitializationError: docker-credential-gcloud not installed or not available in PATH
Failed: docker-compose up
Command failed: docker-compose -f /home/cbailey/dev/groot/docker-compose.yml -f /home/cbailey/dev/groot/.devcontainer/docker-compose.vscode.yml -f /home/cbailey/dev/groot/docker-compose.override.yml up -d
```

Also, I verified manually adding it to my `terminal.integrated.env.linux` setting in my User Settings does not help either.

```
{
    "terminal.integrated.env.linux": {
        "PATH": "/home/cbailey/google-cloud-sdk:${env:PATH}"
    },
}
```

**Comment by chrmarti** [comment]
We currently don't pick up `terminal.integrated.env.*` when running these commands. (@alexr00 Are tasks doing that?)

@AngellusMortis What do you get for `PATH=/bin zsh -lic 'echo $PATH'`? That's what VS Code runs to extract the environment variables (it does it in a single pass).

**Comment by alexr00** [comment]
Yes, the terminal tasks uses does include environment variables set using `terminal.integrated.env.*`, but  tasks does not expand those environment variables. So if you define `MY_ENV_VAR` using `terminal.integrated.env.*` then have a task that does `echo %MY_ENV_VAR%` it will work. But if your task does `echo ${env:MY_ENV_VAR}` then it will not expand.

**Comment by AngellusMortis** [comment]
> What do you get for PATH=/bin zsh -lic 'echo $PATH'?

I get the expected value posted in the screenshot on the left above (because it logged me in and used my `.zshrc`).

I do not think the `docker-compose` command that gets ran to build the Docker images before Attaching VS Code is actually running the `-i` or the `-l` options though. Otherwise I would not get that stacktrace saying `docker-credential-gcloud` is not in my PATH.

**Comment by chrmarti** [comment]
You're right, we run: https://github.com/Microsoft/vscode/blob/master/src/vs/code/node/shellEnv.ts

That runs $SHELL with `-lic` and executes Node to print the entire environment to stdout from where we pick it up and set it for extensions and other processes. Somehow that fails to pick up your PATH.

/cc @joaomoreno for ideas.

**Comment by chrmarti** [comment]
@joaomoreno Could you log 'trace' level information in `shellEnv.ts` including the full command being executed and its output?

**Comment by joaomoreno** [comment]
Ready to go on my branch: https://github.com/microsoft/vscode/commits/joao/next

**Comment by AngellusMortis** [comment]
@chrmarti So the both is just going to close this issue and #74 when there was absolutely no ask to us from the team? This is an issue that needs to be resolved. Docker builds are not using the user's configured shell `$PATH` or we cannot extend it, anyone have a a slightly customized Docker build will have trouble (including everyone that uses GCP, which is our use case).

**Comment by chrmarti** [comment]
@AngellusMortis Thanks for the reminder.

@joaomoreno I don't see the additional log messages in the latest insiders when starting with `--log trace`. I see the change is checked in. Anything in addition I need to do?

**Comment by joaomoreno** [comment]
It should be on the main process.

**Comment by chrmarti** [comment]
@joaomoreno I see trace messages for the main process, but not these. This should always be triggered, shouldn't it?

**Comment by joaomoreno** [comment]
It should yeah... :thinking:

**Comment by chrmarti** [comment]
@AngellusMortis Could you attach your `.zshrc`?

And could you run the following and attach its output?
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games /usr/share/code-insiders/code-insiders --verbose
```

**Comment by jakegt1** [comment]
As #74  is closed i'll come here for assistance..

`/usr/local/bin` is default on the PATH in any shell i use, but for some reason i get the same error described in https://github.com/microsoft/vscode-remote-release/issues/74#issuecomment-493092630.

I'm guessing that the code has hardcoded env? annoyingly in mac it's not possible to create files in /usr/bin or /bin, so i can't validate it.

**Comment by chrmarti** [comment]
@jakegt1 Where does `/usr/local/bin` come from? `/etc/paths`?

What is your shell and what do you get for: `PATH=/bin $SHELL -lic 'echo $PATH'`?

**Comment by jakegt1** [comment]
@Chrmarti Sorry for not responding to this..

My shell is fish. 

Output of the command (but considering PATH=/bin doesn't work on fish, so `env PATH=/bin $SHELL -lic 'echo $PATH')
/Users/jtorranc/.local/bin /opt/gradle/gradle-5.3.1/bin /Users/jtorranc/.nimble/bin /usr/local/opt/coreutils/libexec/gnubin /usr/local/opt/findutils/libexec/gnubin /opt/gradle/gradle-1.12/bin /Users/jtorranc/.local/bin /usr/local/opt/grep/libexec/gnubin /usr/local/opt/llvm@4/bin /usr/local/opt/findutils/libexec/gnubin /usr/local/bin /usr/bin /bin /usr/sbin /sbin

**Comment by chrmarti** [comment]
@jakegt1 Does it work when you start VS Code from a terminal window?

Could you start `code --verbose` and check what output you get in the terminal containing 'getUnixShellEnvironment'?

**Comment by mzeo** [comment]
@chrmarti I have this problem as well, and it works when I start VC Code from a terminal window. I have `/usr/local/bin` in `/etc/paths`.

**Comment by chrmarti** [comment]
@mzeo Could you also start `code --verbose` and check what output you get in the terminal containing 'getUnixShellEnvironment'?

**Comment by jakegt1** [comment]
@chrmarti funnily enough, when i started it from my terminal.. it worked fine, and I could use containers as expected. You can define that as a workaround if you like.

**Comment by jakegt1** [comment]
Why it doesn't happen when starting vscode from the shortcut though is odd.

**Comment by twhittock** [comment]
This occurs when docker was previously installed using homebrew. Running code from the terminal is a workaround.

**Comment by chrmarti** [comment]
@twhittock Where does homebrew place the addition of `docker` to `$PATH`?

**Comment by twhittock** [comment]
docker is installed by homebrew into /usr/local/bin

PATH includes that location by default since 10.10 - homebrew doesn't mess with the global configuration, AFAIK.

/etc/paths looks like this (unmodified)
```
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

**Comment by jakegt1** [comment]
I never installed it using homebrew.

**Comment by grahame** [comment]
I'm hitting this too. I'm running Docker Desktop, shell is `/bin/zsh`, docker is in `$PATH` at `/usr/local/bin/docker`, which is also in `/etc/paths`

**Comment by msudgh** [comment]
Same to me on macOS and Docker Desktop, I compromised all mentioned points with my env and it seems VSCode does not pick preferred user's SHELL to resolve paths.

**Comment by chrmarti** [comment]
If you see this when launching from the Mac's dock, but not when launching from the terminal:
- Add `process.argv.push('--verbose');` as the first line to `/Applications/Visual Studio Code.app/Contents/Resources/app/out/main.js`.
- Close all VS Code windows and reopen.
- `F1` > `Output: Focus on Output View`
- Pick `Log (Main)` from the combo box.
- Search for `getUnixShellEnvironment` in that log and post all lines containing it here (make sure to obfuscate any private information).
- Remove the previously added line from `main.js`.
