### ISSUE TITLE
How to switch back from sh to bash?

### ISSUE THREAD

**Issue by nphmuller** [microsoft/vscode-remote-release#350]
- VSCode Version:
```
Version: 1.35.0-insider (user setup)
Commit: a69d0f8b218498e22b7c3a0f76926cc6322e6106
Date: 2019-05-17T05:18:13.839Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362
```
- Remote OS Version: Debian Stretch (through `node:lts` Docker image)
- Remote Extension/Connection Type: Docker

Since the latest insider release, the default terminal has switched from bash to sh.
Was this an intentional change? Can I change this back to bash somehow? I think bash is much user friendlier (tab completion doesn't work properly, current directory not showing, etc). Or did this happen because of the container image I use, which VSCode now respects better?

**Comment by pd93** [comment]
> Or did this happen because of the container image I use, which VSCode now respects better?

@nphmuller I noticed from the last couple of updates that VSCode will now respect the default shell of whatever environment you're running the remote in. If the container you're running the remote VSCode server in has `sh` as the default (or only) shell, you will get an `sh` prompt.

You can put the setting `"terminal.integrated.shell.linux": "/bin/bash"` in your remote vscode `settings.json` to force a `bash` shell if it's available.

**Comment by roblourens** [comment]
Thanks @pd93

**Comment by Chuxel** [comment]
The other way to fix this is to add a SHELL env var into your Dockerfile.  

```Dockerfile
ENV SHELL /bin/bash
```

I just added these to all of the vscode-dev-containers base definitions going forward.
