### ISSUE TITLE
WSL-remote for fuse-sshfs

### ISSUE THREAD

**Issue by isVoid** [microsoft/vscode-remote-release#3502]
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

- Remote OS Version: Ubuntu 18.04 LTS
- Remote Extension/Connection Type: WSL 

Steps to Reproduce:

1. Mount a partition via fuse.sshfs
2. In that folder, run `code .`
3. Error shown: `/mnt/c/Users/xxx/AppData/Local/Programs/Microsoft VS Code/Code.exe: Invalid argument`

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Can you run `VSCODE_WSL_DEBUG_INFO=true code .` to get more information?

**Comment by Daegalus** [comment]
I am getting this exact problem with an SSHFS mounted drive in my WSL2 instance on Ubuntu 20.04.

Here is the debug info:
```sh
>> VSCODE_WSL_DEBUG_INFO=true code .
+ COMMIT=ea3859d4ba2f3e577a159bc91e3074c5d85c0523
+ APP_NAME=code
+ QUALITY=stable
+ NAME=Code
+ DATAFOLDER=.vscode
+ realpath /mnt/c/Users/Yulian Kuncheff/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/Yulian Kuncheff/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/Yulian Kuncheff/AppData/Local/Programs/Microsoft VS Code/bin
+ VSCODE_PATH=/mnt/c/Users/Yulian Kuncheff/AppData/Local/Programs/Microsoft VS Code
+ ELECTRON=/mnt/c/Users/Yulian Kuncheff/AppData/Local/Programs/Microsoft VS Code/Code.exe
+ IN_WSL=false
+ [ -n Ubuntu ]
+ IN_WSL=true
+ [ true = true ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID
+ wslpath -m /mnt/c/Users/Yulian Kuncheff/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ CLI=C:/Users/Yulian Kuncheff/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/Yulian Kuncheff/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/Yulian Kuncheff/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --locate-extension ms-vscode-remote.remote-wsl
+ cat /tmp/remote-wsl-loc.txt
+ WSL_EXT_WLOC=
+ [ -n  ]
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/Yulian Kuncheff/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/Yulian Kuncheff/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js .
/mnt/c/Users/Yulian Kuncheff/AppData/Local/Programs/Microsoft VS Code/Code.exe: Invalid argument
```

The major thing i noticed is `WSL_EXT_WLOC` is blank. When i run the same command in my home directory, it loads fine with `WSL_EXT_WLOC` set correctly. (and i can access the sshfs subdirectories, it just seems to fail at launch from the CLI)

I then checked explorer.exe access, and when i try to navigate into the sshfs mount, I get a inaccessibility error saying its an invalid address.
