### ISSUE TITLE
Cannot connect to remote via ssh unless .vscode-server folder on the remote is deleted

### ISSUE THREAD

**Issue by MarkoMFilip** [microsoft/vscode-remote-release#3503]
- VSCode Version: 1.47.3
- OS Version: MS Windows 10 Enterprise 10.0.17763
- Remote OS Version: Ubuntu 18.04.4

Steps to Reproduce:

1. Try to connect to a remote via ssh from VSCode and get the following output (note: I exchanged the remote name with "< remote >"):
```
[14:38:47.598] Log Level: 2
[14:38:47.598] remote-ssh@0.51.0
[14:38:47.598] win32 x64
[14:38:47.600] SSH Resolver called for "ssh-remote+<remote>", attempt 1
[14:38:47.600] SSH Resolver called for host: <remote>
[14:38:47.600] Setting up SSH remote "<remote>"
[14:38:47.609] Using commit id "91899dcef7b8110878ea59626991a18c8a6a1b3e" and quality "stable" for server
[14:38:47.611] Install and start server if needed
[14:38:47.614] Checking ssh with "ssh -V"
[14:38:47.659] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[14:38:47.662] Running script with connection command: ssh -T -D 63250 <remote> bash
[14:38:47.666] Terminal shell path: C:\windows\System32\cmd.exe
[14:38:47.780] > 
[14:38:47.780] Got some output, clearing connection timeout
[14:38:48.277] > 50fa0c6793a4: running
> 
[14:38:48.309] > Acquiring lock on /home/markofilipovic/.vscode-server/bin/91899dcef7b8110878ea59
> 626991a18c8a6a1b3e/vscode-remote-lock.markofilipovic.91899dcef7b8110878ea5962699
> 1a18c8a6a1b3e
> \ln /home/markofilipovic/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a
> 1b3e/vscode-remote-lock.markofilipovic.91899dcef7b8110878ea59626991a18c8a6a1b3e.
> target /home/markofilipovic/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8
> a6a1b3e/vscode-remote-lock.markofilipovic.91899dcef7b8110878ea59626991a18c8a6a1b
> 3e
> Found existing installation at /home/markofilipovic/.vscode-server/bin/91899dcef
> 7b8110878ea59626991a18c8a6a1b3e...
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
[14:38:48.357] > Checking server status on port 35669 with wget
> failed: Connection refused.
> 50fa0c6793a4##28##
> 
[14:38:48.358] Received install output: 50fa0c6793a4##28##
[14:38:48.359] Server status check failed - waiting and retrying
[14:38:48.611] "install" terminal command done
[14:38:48.612] Install terminal quit with output: 
[14:38:49.362] Running script with connection command: ssh -T -D 63250 <remote> bash
[14:38:49.363] Terminal shell path: C:\windows\System32\cmd.exe
[14:38:49.478] > 
[14:38:49.478] Got some output, clearing connection timeout
[14:38:50.016] > 50fa0c6793a4: running
> Acquiring lock on /home/markofilipovic/.vscode-server/bin/91899dcef7b8110878ea59
> 626991a18c8a6a1b3e/vscode-remote-lock.markofilipovic.91899dcef7b8110878ea5962699
> 1a18c8a6a1b3e
> \ln /home/markofilipovic/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a
> 1b3e/vscode-remote-lock.markofilipovic.91899dcef7b8110878ea59626991a18c8a6a1b3e.
> target /home/markofilipovic/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8
> a6a1b3e/vscode-remote-lock.markofilipovic.91899dcef7b8110878ea59626991a18c8a6a1b
> 3e
> 
[14:38:50.044] > Found existing installation at /home/markofilipovic/.vscode-server/bin/91899dcef
> 7b8110878ea59626991a18c8a6a1b3e...
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
[14:38:50.079] > Checking server status on port 35669 with wget
> failed: Connection refused.
> 50fa0c6793a4##28##
```

This keeps on repeating several times.

As per advice of @roblourens , running the command 
` wget --no-proxy -nv -O - http://127.0.0.1:35669/delay-shutdown `
produces
` failed: Connection refused. ` 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by MarkoMFilip** [comment]
> 
> 
> Can you describe what happens after deleting the remove .vscode-server? Does it resolve the problem or does this re-occur?

It resolves the issue until the next host restart. But while working in the same session, ever disconnecting from the remote completely doesn't prevent reconnecting again without problems. It really re-occurs only when the host machine is restarted, and it does so without fail. The only solution then is to connect to the remote with an external terminal and delete the entire .vscode-remote folder.

**Comment by basnijholt** [comment]
I am also experiencing this problem.

This issue reports the same thing but is closed: https://github.com/microsoft/vscode-remote-release/issues/2828.

**Comment by MarkoMFilip** [comment]
> 
> 
> So the problem is
> 
>     * You are able to connect successfully
> 
>     * You restart the host
> 
>     * Then the above situation happens
> 
> 
> Is that right? If so, that's strange because the log says that we have detected a running server process. If you restarted the host, the server should not be running, so the code that detects it must be wrong. The actual failure just says that it couldn't communicate with the running server, so that makes sense.
> 
> To find a running server we just run something sort of like
> 
> `ps ax | grep 91899dcef7b8110878ea59626991a18c8a6a1b3e`
> 
> Could you try that when you are in this state and share the output? If you have updated vscode you will have to update the version hash.

Alright, so, first I made sure that I cannot connect to the remote through VSCode. Then I opened an external terminal, and ran
`ps ax | grep db40434f562994116e5b21c24015a2e40b2504e6`

Here is the output
```
5643 ?        Ssl    0:10 /home/markofilipovic/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/node -e  ????const net = require('net'); ????process.stdin.pause(); ????const client = net.createConnection({ port: 34219 }, () => { ?????client.pipe(process.stdout); ?????process.stdin.pipe(client); ????}); ????client.on('close', function (hadError) { ?????process.exit(hadError ? 1 : 0); ????}); ????client.on('error', function (err) { ?????process.stderr.write(err && (err.stack || err.message) || String(err)); ????}); ???
10041 ?        Ssl    0:00 /home/markofilipovic/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/node /tmp/vscode-remote-containers-server-e0f6726b6e88eb4ae039be57de7b9cc495cd9fa9.js
10167 ?        Ssl    0:10 /home/markofilipovic/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/node -e  ????const net = require('net'); ????process.stdin.pause(); ????const client = net.createConnection({ port: 34219 }, () => { ?????client.pipe(process.stdout); ?????process.stdin.pipe(client); ????}); ????client.on('close', function (hadError) { ?????process.exit(hadError ? 1 : 0); ????}); ????client.on('error', function (err) { ?????process.stderr.write(err && (err.stack || err.message) || String(err)); ????}); ???
10320 ?        Sl     0:15 /home/markofilipovic/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/node /home/markofilipovic/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/out/bootstrap-fork --type=watcherService
15979 ?        Ssl    0:00 /home/markofilipovic/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/node /tmp/vscode-remote-containers-server-33e04aaf94632f023696a2a86d10af793a995aa9.js
20283 ?        Ssl    0:00 /home/markofilipovic/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/node /tmp/vscode-remote-containers-server-cc060cd73ad30ff4c774b270edadcb25b02818b0.js
20366 pts/31   S+     0:00 grep --color=auto db40434f562994116e5b21c24015a2e40b2504e6
22457 ?        Ssl    0:00 /home/markofilipovic/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/node /tmp/vscode-remote-containers-server-68d7c288ed38d464698d5d146a6bc767500f5709.js
24468 ?        S      0:00 sh /home/markofilipovic/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/server.sh --disable-user-env-probe --disable-telemetry --port 0 --extensions-download-dir /home/markofilipovic/.vscode-server/extensionsCache
24470 ?        Sl     0:40 /home/markofilipovic/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/node /home/markofilipovic/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/out/vs/server/main.js --disable-user-env-probe --disable-telemetry --port 0 --extensions-download-dir /home/markofilipovic/.vscode-server/extensionsCache
25491 ?        Sl     0:16 /home/markofilipovic/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/node /home/markofilipovic/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/out/bootstrap-fork --type=watcherService
```

**Comment by roblourens** [comment]
Hm, are you also using Remote-Containers on the same machine?

**Comment by MarkoMFilip** [comment]
> 
> 
> Hm, are you also using Remote-Containers on the same machine?

Yes. We have a bunch of containers on the remote machine that are always running. Normally, we can both ssh into the remote and attach to containers on that remote at the same time. Interestingly, when we are not able to ssh into the remote (due to whatever is causing this problem), we can _still_ attach to the remote containers.

**Comment by roblourens** [comment]
It sounded like this was breaking after you restart the host, but from this it sounds like you restarted the host, then attached with Remote-Containers, and now you can't connect?

This is a little strange, it almost looks like that is `ps` output from inside the container, not outside of it, since it shows the remote server running but it's an instance launched by Remote-Containers which would be launched inside the container.

**Comment by MarkoMFilip** [comment]
The situation is as follows.
Guest/Remote computer is almost always on (restarted only for mandatory updates), and has a suit of Docker containers permanently running on it.
Host computer is a personal laptop that is used during work time and shut down afterwards.
After booting up the host, it is possible to normally connect to the remote through terminal (WSL1). It is also possible to connect to any of the remote containers in the same way.
On the other hand, it is not possible to connect to the remote through VSCode. However, it _is_ possible to attach to a remote container through VSCode. The order of these two actions doesn't matter. SSH-ing to remote is impossible (without deleting .vscode-server) no matter if I attached to remote container before or after trying SSH.

**Comment by roblourens** [comment]
Thanks, my confusion was that you switched around the term "host" which I usually use for the remote machine, ie the one that is "hosting" the remote session and server. Now I understand though, but rebooting your local machine really shouldn't impact anything like this.

I still don't understand the output of `ps` though, and I think that is key to understanding this.

@chrmarti in a remote container scenario, is there a vscode server started outside of the containers?

**Comment by chrmarti** [comment]
@roblourens No, but the container processes are visible on the host side (the machine that runs the Docker daemon).

**Comment by roblourens** [comment]
Oh yeah, that makes sense. It's interesting that this hasn't come up yet, it breaks the weak way that Remote-SSH tries to find a running server.

I think the best fix is to add some flag that lets us detect whether the server process was started by Remote-SSH, so that Remote-SSH's server is managed separately from the server started by wsl/containers. Because they could start it with different flags or handle the lifecycle differently.

**Comment by connor4312** [comment]
@roblourens can you add verification instructions?

**Comment by roblourens** [comment]
- Have a Linux machine with Docker and the SSH server set up
- Open a dev container on that remote
- And SSH to the same remote
