### ISSUE TITLE
Does not display the hostname of the remote workspace

### ISSUE THREAD

**Issue by serend1p1ty** [microsoft/vscode-remote-release#3508]
- VSCode Version: Latest
- Local OS Version: Windows10
- Remote OS Version: Ubuntu16.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/39628662/90088530-bd863480-dd51-11ea-9067-c1e1bea2f1d7.png)

The first `NAE4PS` is in the `a` host, second `NAE4PS` is in `b` host.
The hostname should be displayed like the third NAE4PS in `c` host

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by Chuxel** [comment]
@ChrisLee63 What does your SSH config file look like for these three hosts?

**Comment by ChrisLee63** [comment]
@Chuxel 
Hi, my config is as follows:
```
Host 1080Ti
  HostName xxx.xxx.x.xxx
  User zjli

Host TeslaV100
  HostName xxx.xxx.x.xxx
  User zjli

Host 2080Ti
  HostName xxx.xxx.x.xxx
  User zjli
```

**Comment by roblourens** [comment]
And you did successfully connect to these hosts?

**Comment by serend1p1ty** [comment]
Yes, of course.
