### ISSUE TITLE
Fail to use special characters from non EN keyboards in terminal

### ISSUE THREAD

**Issue by thochra** [microsoft/vscode-remote-release#351]
Issue Type: <b>Bug</b>

Keypress on special characters like `é` `à`  for french keyboard do not cause input in the terminal when using a remote project (linux target).

`~` is also unaccessible which is even more anoying.

Extension version: 0.14.0
VS Code version: Code - Insiders 1.34.20-insider (e83e24a0c9225becd7341e56952177a20d5d4629, 2019-05-15T18:06:45.467Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.18.0-1014-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.23.2|
|OS|Linux x64 4.18.0-1014-azure|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (4 x 2591)|
|Memory (System)|5.83GB (0.05GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Is this different in a remote window vs local window?

**Comment by thochra** [comment]
Hello @roblourens,
You're right I did not try with a local terminal session.


Here are the results for a french keyboard trying to output an `é` => pressing key `2` above `w` if you have a qwerty layout:
* Local powershell
  * works as expected
* Local wsl.exe (ubuntu bash shell)
  * works as expected
* Remote linux bash shell (ubuntu server)
  * outputs nothing


Also I did notice this morning that I was able to output the `~` char compared to 3 days ago. I don't have an explanation for that...
Here are the results for a french keyboard trying to output a `~` => combination of `alt gr` + `2` with a qwerty layout:
* Local powershell
  * first attempt outputs in an `é`
  * second attempt output an `é~`
* Local wsl.exe (ubuntu bash shell)
  * same result as powershell
* Remote linux bash shell (ubuntu server)
  * first attempt outputs nothing
  * second attempt or pressing `space` outputs an `~` which is the expected behavior
