### ISSUE TITLE
Allow skipping distro selection via config entry

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vscode-remote-release#3511]
This ties into https://github.com/microsoft/vscode-remote-release/issues/3081 which for me causes the problem that I always have to deal with this selector even though I only have on distro.

I would love to see a config option to specify a default distro and VSCode to then skip the selection process and use that container instead.

**Comment by bamurtaugh** [comment]
Just to clarify, how would this flow be different than using the **Remote-WSL: New Window** command?

**Comment by Stanzilla** [comment]
It would re-open the current folder inside of a configured WSL distro. the new window command just opens *a* window but does not go to the folder.

**Comment by aeschli** [comment]
I pushed a change to hide `docker-desktop` and `docker-desktop-data` (hard coded, for now) from the distro selection dialog. That should fix your issue too as we don't show the picker if there's only one available distro.

**Comment by Stanzilla** [comment]
Awesome, thank you!
