### ISSUE TITLE
Upload and download experience

### ISSUE THREAD

**Issue by dbshch** [microsoft/vscode-remote-release#3513]
There is no progress bar or any prompt for uploading and downloading files. I can only know the uploading is done when a editor of that file pops out. But for downloading and uploading multiple files, I have to manually check the size of each file to know the progress.

Also, after uploading a file the editor will always pop out. That distrubs the experience of the editor.
The file even has to be downloaded again when the editor pops out just after uploading, but I don't need to view it (and vscode can't view it) when I'm uploading some packages. It is a severe problem when uploading big files on slow or metered network. This problem also exists in clicking some large files by mistake. I have no way except reloading the whole vscode to stop downloading the files.

**Comment by isidorn** [comment]
This is all good fedback and makes sense, I am not sure when we will tackle this thus assigning to Backlog.

**Comment by isidorn** [comment]
As for progress there is an issue in vscode repo for showing progress for slow running operatoins. This would be tackled by that.
The rest I am marking as out of scope for now.
