### ISSUE TITLE
Attaching to running conainer does not expose bound mount volume

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode-remote-release#3514]
Issue Type: <b>Bug</b>

If I have a container running that is bound to a local directory using the -v flag, connecting to it with the VSCode remote containers extension does not show the volume in the file explorer.

Extension version: 0.134.0
VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 5.4.40-04224-g891a6cce2d44
Remote OS version: Linux x64 5.4.40-04224-g891a6cce2d44

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (4 x 1607)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|14.21GB (14.19GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|40%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|

|Item|Value|
|---|---|
|Remote|Dev Container: Python 3 - Anaconda|
|OS|Linux x64 5.4.40-04224-g891a6cce2d44|
|CPUs|06/8e (4 x 1607)|
|Memory (System)|14.21GB (0.68GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Not sure what is expected here. Can you use `File` > `Open Folder` to open the volume's folder?
