### ISSUE TITLE
Every One Can help me ? i am struck with this.

### ISSUE THREAD

**Issue by jamel3oy** [microsoft/vscode-remote-release#3516]
try to open remote ssh  but it struck with this.
![Screen Shot 2563-08-14 at 13 04 33](https://user-images.githubusercontent.com/9563152/90218718-baad4180-de2e-11ea-9ab4-0cc849d67ff0.png)

**Comment by rzhao271** [comment]
Closing this issue for housekeeping. @jamel3oy feel free to reply if this issue still occurs for you on the latest VS Code (preferably Insiders edition).
