### ISSUE TITLE
Set DEVCONTAINER=true environment variable

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-remote-release#3517]
This would be good, so scripts can get to know if they're running from a devcontainer or not. VS Codespaces have the `CODESPACES` by the way.

So far, I have to do:
```bash
function is_devcontainer() {
  if [ -n "${REMOTE_CONTAINERS_IPC+x}" ] || [ -n "${REMOTE_CONTAINERS_SOCKETS+x}" ] || [ -n "${VSCODE_REMOTE_CONTAINERS_SESSION+x}" ]; then
    return 0
  else
    return 1
  fi
}
```

Because the referenced variables are not set all the time.

**Comment by felipecassiors** [comment]
Oh, my bad. 

It does not show up on https://github.com/microsoft/vscode-dev-containers/issues yet, should I close this one and create it there?

**Comment by Chuxel** [comment]
@felipecassiors Nope - I transferred it. The link works from both places when that happens, it's just offically in the vscode-remote-release repo now.  :smile:

**Comment by chrmarti** [comment]
@felipecassiors You could add this to your devcontainer.json yourself:
```json
	"remoteEnv": {
		"DEVCONTAINER": "true"
	}
```
That would cover Remote-Containers and Codespaces. (@Chuxel is there a list of devcontainer.json properties supported by Codespaces?)

**Comment by Chuxel** [comment]
@chrmarti Yes, this would work fine, but the general request is to have a common way to do it. We could coordinate to get that added.  The other one I think may be good to add is `LOCAL_WORKSPACE_PATH` given that is needed for bind mounting in docker-from-docker.  The example does the above to work around that, but it would be reasonable to just have it there.

**Comment by felipecassiors** [comment]
> @felipecassiors You could add this to your devcontainer.json yourself:
> 
> ```json
> 	"remoteEnv": {
> 		"DEVCONTAINER": "true"
> 	}
> ```
> 
> That would cover Remote-Containers and Codespaces.

I see, but it would just cover the `devcontainer`s I maintain. I need such a variable because of my `dotfiles`, since I perform some installation steps which are specific for `devcontainer` or `codespaces`.

**Comment by chrmarti** [comment]
Got it. Would it make sense to call it REMOTE_CONTAINERS? Codespaces is running a devcontainer too. We could also make it DEVCONTAINER for both Codespaces and Remote-Containers (and maybe have all 3 to be clear?).

**Comment by felipecassiors** [comment]
> Got it. Would it make sense to call it REMOTE_CONTAINERS? Codespaces is running a devcontainer too. We could also make it DEVCONTAINER for both Codespaces and Remote-Containers (and maybe have all 3 to be clear?).

It makes sense, and I believe the best is to have all the 3 as you said. :-)

**Comment by chrmarti** [comment]
Setting REMOTE_CONTAINERS=true. Please open additional requests for additional variables.

**Comment by felipecrs** [comment]
@chrmarti thank you so much. So there is no `DEVCONTAINER=true`?

**Comment by chrmarti** [comment]
Not right now, we need to coordinate with Codespaces to make sure they introduce that too (going by our earlier discussion). Please open a new issue if you want to see that implemented too.

**Comment by felipecrs** [comment]
> Not right now, we need to coordinate with Codespaces to make sure they introduce that too (going by our earlier discussion). Please open a new issue if you want to see that implemented too.

Alright. It's ok, this already fits my purpose.

**Comment by felipecrs** [comment]
@chrmarti I just tested here, and the variable does not seem to be set when the `dotfiles` installation happens. It's only available after. Therefore, I still need to rely on `VSCODE_REMOTE_CONTAINERS_SESSION`.

Note: `CODESPACES` is set on GitHub Codespaces during the dotfiles installation.

**Comment by chrmarti** [comment]
@felipecrs That should be fixed in the latest (0.143.0) could you verify? Thanks.

**Comment by felipecrs** [comment]
@chrmarti Verified!

![image](https://user-images.githubusercontent.com/29582865/94559634-64e1fc80-0216-11eb-8283-e7047d7b9a4d.png)

I was not able to install v0.143.0 on VSCode stable though, so I installed in the insiders version. Is that expected?

**Comment by chrmarti** [comment]
@felipecrs Thanks! Yes, that version is only available for VS Code Insiders and then for VS Code 1.50 when that is released.

**Comment by felipecrs** [comment]
Awesome, thanks.
