### ISSUE TITLE
Unable to debug Linux C program with VS - WSL

### ISSUE THREAD

**Issue by ilGianfri** [microsoft/vscode-remote-release#352]
- VSCode Version: 1.35.0
- Local OS Version: 18362.113
- Remote OS Version:
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Configure WSL debug like showed here https://code.visualstudio.com/docs/remote/wsl
2. Create a simple C program and hit F5
3. Program will be built but not debugged

Gcc will build the program but it will not start and debug it.

![image](https://user-images.githubusercontent.com/5341363/57936952-3b485f80-78c5-11e9-84ef-3ff224c00260.png)
![image](https://user-images.githubusercontent.com/5341363/57936921-266bcc00-78c5-11e9-9264-c5d389f3c03e.png)

Downgrading to VSCode v1.34.20 makes everything work correctly.

launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "gcc build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "gcc build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}
```

tasks.json
```
{
    "tasks": [
        {
            "type": "shell",
            "label": "gcc build active file",
            "command": "/usr/bin/gcc",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "/usr/bin"
            }
        }
    ],
    "version": "2.0.0"
}
```
test.c

```
#include <stdio.h>

void main()
{
	printf("hello");
}
```

**Comment by taurusjun** [comment]
I have the issue after updating VS insder to 1.35

**Comment by weinand** [comment]
@isidorn I can reproduce this at least for C/C++ and Python.
For C/C++ I do not see any errors but debugging doesn't start.
Python shows this error:
![2019-05-20_16-44-08](https://user-images.githubusercontent.com/1898161/58030260-87daa780-7b1e-11e9-9a3e-b09a9d5a011a.png)

Debugging node.js works fine.

The problem already occurs in the first 1.35 release from 5 days ago (982e7bc2f1).

I haven't pushed any changes in May.
Are you aware of changes that might affect this?

**Comment by Chuxel** [comment]
@weinand There's a report that C++ debugging doesn't work in insiders even w/o VS Code Remote here: https://github.com/microsoft/vscode/issues/73987#issuecomment-493982007

**Comment by yamcenutzer** [comment]
As before, when such things come up, nobody knows where to complain about this issue:
- vscode, c++ extension or remote extension.

Any ideas?

**Comment by weinand** [comment]
@yamcenutzer VS Code is always a good starting point.
