### ISSUE TITLE
Unable to setup a remote session to a Linux server

### ISSUE THREAD

**Issue by sumukhatv** [microsoft/vscode-remote-release#3520]
- VSCode Version: 1.47.3
- Local OS Version: Windows 10
- Remote OS Version: 4.10.0-19-generic
- Remote Extension/Connection Type: SSH/Docker/WSL: SSH

Steps to Reproduce:

1. Initiate a remote session to the server
2. Gets stuck with this output:
_vscodeArch==x64==
destFolder==/home/user/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e==
996a2728b442:trigger_server_download_end
Waiting for client to transfer server archive...
Waiting for /home/user/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/vscode-scp-done.flag and vscode-server.tar.gz to exist_    

Does this issue occur when you try this locally?: Yes/No: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
If this is still an issue, please share the full log
