### ISSUE TITLE
Stuck at "Waiting for vscode-scp-done.flag and vscode-server.tar.gz to exist"

### ISSUE THREAD

**Issue by af-productions** [microsoft/vscode-remote-release#3528]
Issue Type: <b>Bug</b>

I updated VS Code to the July 2020 version and after the update completed, I attempted to connect to a Linux machine, that already has VS Code Server installed and then i go a message saying "Setting up SSH Host Downloading VS Code Server" and when I clicked on Details I noticed, that it´s stuck at "Waiting for vscode-scp-done.flag and vscode-server.tar.gz to exist". I was able to connect just minutes before I restarted VS Code to apply the update without any issues. I also tried going back to the June 2020 version and it was working fine again but as soon as I updated to the July version, it stopped working again.
I thought maybe something on that machine maybe isn´t working correctly, so I tried connecting to a different machine, that the VS Code Server has not yet been installed on, butI´m having the exact same issue there

Extension version: 0.51.0
VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19041
Fetching remote diagnostics for 'ssh-remote+7b22686f73744e616d65223a2245564f706c7573227d' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (23.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'ssh-remote+7b22686f73744e616d65223a2245564f706c7573227d' timed out.
</details>

**Comment by L-mNguyen** [comment]
I ran into the same issue as you. By following this StackOverflow post, I was able to fix this issue.
https://stackoverflow.com/questions/56718453/using-remote-ssh-in-vscode-on-a-target-machine-that-only-allows-inbound-ssh-co

**Comment by af-productions** [comment]
Thanks for your solution, it worked! I really hope they can fix this issue soon. There are a lot of people in the company I work for who need to access a bunch of servers via vscode every day and need to be able to do that quickly and without any issues. So until they fix that, I have to manually download and update vscode-server on every one of those servers. It used to work without any issues via the allowLocalServerDownload feature of remote-ssh. The current release is the first one where this does not work.

**Comment by Chuxel** [comment]
@roblourens Possible regression or settings default impact?

**Comment by roblourens** [comment]
Sorry for the trouble, I'm not aware of any relevant changes, and it's still working for me. Can one of you share the log from the Remote-SSH output channel for a run where this does not work?

**Comment by af-productions** [comment]
Hi, the issue seems to have been solved in the 1.49.0 version. Ever since the update I haven't had this issue again. I can downgrade to the old version and send you the log of you want.

**Comment by jrmims** [comment]
Working great for me with version 1.49.1!

**Comment by roblourens** [comment]
No need, but please let me know whether you see it again!

**Comment by af-productions** [comment]
Alright. Thanks
