### ISSUE TITLE
Set USER environment variable by default

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-remote-release#3531]
Start a container and you'll note that the `$USER` environment variable won't be set. This variable should be injected in the container by VSCode since it knows which is the user name.

In my case, I use this environment variable in my `dotfiles/install` script.

![image](https://user-images.githubusercontent.com/29582865/90197777-1c759900-dda6-11ea-9276-a68a7849f5d7.png)

Workaround:

```JSONC
// devcontainer.json
{ 
  "containerUser": "vscode",
  "containerEnv": {
      "USER": "vscode"
    }
} 
```

# Useful references

https://unix.stackexchange.com/questions/76354/who-sets-user-and-username-environment-variables/76369#76369

**Comment by Chuxel** [comment]
Similar kind of request to #3517. I'll update the common script to do this for anything in vscode-dev-containers.

**Comment by chrmarti** [comment]
Can you use `id -un`?

**Comment by felipecassiors** [comment]
> Can you use `id -un`?

Yes, this helps to work around it.

**Comment by Chuxel** [comment]
Yeah I added `export USER=$(whoami)` to the `common-debian.sh` script used in the devcontainers repo.

**Comment by felipecassiors** [comment]
But @Chuxel, how adding it to `common-debian.sh` would solve the problem? The variable must be available in the container's environment, and not only in the script's environment.

If you meant injecting it to `.bashrc`, then we come back to what I said earlier:



> @Chuxel that would not solve the problem, since `.bashrc` and `.zshrc` are replaced when using `dotfiles`.
> 
> We need to find a different approach.

**Comment by felipecassiors** [comment]
I added a reference in the PR description:

> https://unix.stackexchange.com/questions/76354/who-sets-user-and-username-environment-variables/76369#76369

**Comment by Chuxel** [comment]
> If you meant injecting it to .bashrc, then we come back to what I said earlier
Yes, that's what the script does - it was a FYI for @chrmarti :smile:

**Comment by chrmarti** [comment]
`USER` is normally set by `login` from what I read. I'm for using `id` (or `whoami` depending on compatibility across distros) in your scripts and avoid adding more env variables by the extension.

**Comment by felipecrs** [comment]
I understand the reason and I can settle on that.

However, when you boot up a Ubuntu or any other Linux distribution, even a headless virtual machine with Multipass or WSL2, they have this variable set. So the goal was to make the environment a bit user-friendlier, being more look-alike the traditional development environment.

**Comment by chrmarti** [comment]
Closing for now, we can revisit if we find stronger reasons to add it. Thanks.
