### ISSUE TITLE
~/.bashrc variables changes dont´t take effect on process.env (Nodejs)

### ISSUE THREAD

**Issue by RafaelYegrosTR** [microsoft/vscode-remote-release#3532]
- VSCode Version: 1.46.1
- Local OS Version: Windows 10 Enterprise
- Remote OS Version: Red Hat 7.8
- Remote Extension/Connection Type: SSH/Docker/WSL : SSH

Steps to Reproduce:

1. Define a variable at remote Host ~/.bashrc ex: "export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.262.b10-0.el7_8.x86_64/jre"

2. Add the remote host at VSCode. (The server side stuff´s to support VSCode connection, will be installed)

3. Change the previous ~/.bashrc variable "export JAVA_HOME=/usr/lib/jvm/java-1.9.xxx/jre"

4. Run any NodeJS program at server with active debug. 

5. You will be able to see trough debug that process.env.JAVA_HOME won´t change to "/usr/lib/jvm/java-1.9.xxx/jre" even running "source ~/.bashrc".

Workaround: Use VSCode command bar, to uninstall VSCode lib´s at server and install it again (https://code.visualstudio.com/docs/remote/troubleshooting#_cleaning-up-the-vs-code-server-on-the-remote)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
The workaround is the suggested fix for now
