### ISSUE TITLE
[Remote-SSH] Passphrase persistence

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-remote-release#354]
Hello team! 🌞 

I really like the Remote-SSH plugin! Congratulations for all the effort you guys have invested in this 👏 

One thing I keep doing is that I keep needing to paste the passphrase over and over (and in so many places) each time I close my laptop and move somewhere else. Some way of persisting the passphrase would be amazing.

Please let me know what you guys think! Thank you for your time!

**Comment by benliddicott** [comment]
@sadasant The solution is to use public-key authentication :-) Once you have it set up you'll never go back to passwords.

**Comment by roblourens** [comment]
If you are referring to a passphrase for a key, the solution is to set up the ssh agent as described here: https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent

If you mean "user password" then the solution is to use an ssh key. See the steps here: https://code.visualstudio.com/docs/remote/ssh#_connect-to-a-remote-host
