### ISSUE TITLE
Click from internal terminal does not open project related file but /mnt/path-to-file  

### ISSUE THREAD

**Issue by distante** [microsoft/vscode-remote-release#3542]
- VSCode Version: 1.48.0
- Local OS Version: Windows 10 (1908)
- Remote OS Version: WSL Ubuntu 20.04
- Remote Extension/Connection Type: SSH to WSL

Steps to Reproduce:

1. Connect to a remote WSL server using ssh.
2. Log some relative path in your project (in my case a file created with the angular cli : 
![image](https://user-images.githubusercontent.com/5490201/90613981-5d3c3a80-e20a-11ea-809f-003fb54b09c7.png)
3. ctrl+click on path to open it on code, it opens with a non project related path (also It is not selected on the project files panel)
![image](https://user-images.githubusercontent.com/5490201/90614272-bdcb7780-e20a-11ea-96a5-be81406e708d.png)

As extra, the "recent files" list gets filled with those wrong paths 

![image](https://user-images.githubusercontent.com/5490201/90615013-c40e2380-e20b-11ea-9d2a-0fc3caba4375.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No (SSH is needed to connect to remote ;) )

**Comment by Tyriar** [comment]
This is working as designed. If we cannot verify the path is a relative path (we only do when it's printed with `./`), then we just open the quick open with the text added, and that's first because you recently opened it.
