### ISSUE TITLE
Reopen in Container does nothing under WSL2

### ISSUE THREAD

**Issue by hastarin** [microsoft/vscode-remote-release#3543]
Issue Type: <b>Bug</b>

**Steps to reproduce**

- Open WSL2 (in my case Ubuntu-20.04)
- cd to ~/
- mkdir testbug
- cd testbug
- code .
- F1
- Add Development Container Configuration Files...
- Pick anything
- Click Reopen in Container

**Result**
Nothing happens

No error is output anywhere.

Is there a way to debug this further?

Extension version: 0.134.0
VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (19.59GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/jon/source/platform/core-afl --remote=wsl+Ubuntu-20.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz (8 x 3095)|
|Memory (System)|7.77GB (6.40GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Could be #3525, can you retry with the just released 0.134.1 version of Remote-Containers?

If that doesn't fix it, check what is in the log (`F1` > `Remote-Containers: Show Log`) and the dev console (`Help` > `Toggle Developer Tools`).

**Comment by hastarin** [comment]
Thank you @chrmarti the logs immediately helped me to identify the issue.

In my case I had a docker context I'd set months ago and forgotten about that was prompting for an SSH login.

Interestingly enough this means even when trying to run via WSL2 that the call to "docker" was happening under windows and not via WSL2.

I tried to find a Troubleshooting section via Google or in [the documentation](https://code.visualstudio.com/docs/remote/containers) but failed.  It might be good to have those basic steps mentioned somewhere in there?

**Comment by chrmarti** [comment]
@Chuxel Should we mention `Remote-Containers: Show Log` in the documentation?
