### ISSUE TITLE
Containers: Improve error when trying to start container from a WSL1 distro

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#3544]
Verifying #3525

- Have Docker Desktop for Windows installed with the WSL2 backend enabled
- Have the Remote WSL and the Remote Containers extension installed
- Use the Remote WSL extension to open a folder in a WSL1 distro
- Run `Remote-Containers: Reopen in Container`

Error shows up:
`Docker returned an error. Make sure the Docker daemon is running.`

Would be great if the error message say that a WSL2 distro is required

**Comment by chrmarti** [comment]
Going with: 
![image](https://user-images.githubusercontent.com/9205389/90742145-a99d7e00-e2cf-11ea-93c9-7061a11423d5.png)
