### ISSUE TITLE
Change default dotfiles folder from ~/dotfiles to ~/.dotfiles

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-remote-release#3549]
Browsing dotfiles.github.io, I see that `~/.dotfiles` is more often the place where people clone their `dotfiles` repository instead of `~/dotfiles`.

I just wanted to open the discussion.

**Comment by chrmarti** [comment]
Codespaces is using `~/dotfiles`, I probably took it from there.

**Comment by chrmarti** [comment]
Going through a few of the repositories linked from dotfile.github.io both locations seem to be similarly popular and there is no consensus. (Another popular option is to source the install script directly from GitHub.) Closing as we do have the setting to support both locations. Thanks.
