### ISSUE TITLE
The terminal process "/bin/bash '-1'" failed to launch (exit code: 2).

### ISSUE THREAD

**Issue by cwcoffman** [microsoft/vscode-remote-release#3550]
Issue Type: <b>Bug</b>

Can run devcontainer on Mac - can't open a terminal.  No docs on how to fix this.

Extension version: 0.134.1
VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_41641908|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Python 3|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (4 x 2200)|
|Memory (System)|1.94GB (0.36GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
I see this when I add '-1' as a shell argument for Linux in the settings:
![image](https://user-images.githubusercontent.com/9205389/91016921-d1e9ed00-e5ed-11ea-8203-628cc8b2dc52.png)

Note that there are multiple scopes for settings (User, Remote, Workspace), please check all of them:
![image](https://user-images.githubusercontent.com/9205389/91017004-f04fe880-e5ed-11ea-9924-e3ca4a655b92.png)

Does that explain it and removing it fixes the problem?
