### ISSUE TITLE
A way to pass arguments to the `opensshremotes.openEmptyWindow` command

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-remote-release#3552]
It would be great if there was a way to pass the host configuration to the `opensshremotes.openEmptyWindow` command so that rather than opening a quick picker to select the config to use, it could just execute the command with the provided host. 

Our specific use case would be in the [Azure VM extension](https://github.com/microsoft/vscode-azurevirtualmachines).  We think it would be a very useful feature for users to be able to right-click their Azure VMs and just connect directly to their VM from there.  While the remote extension experience is great as is, it requires our users to change views and can be mildly confusing for newer users.

**Comment by bamurtaugh** [comment]
@roblourens It would be great to connect the Remote-SSH and Azure VM extensions. 

I know we're focusing on cleanup this upcoming iteration, but I wanted to get this on your radar and get your thoughts. Clarified/discussed the idea a bit more in [this issue](https://github.com/microsoft/vscode-azurevirtualmachines/issues/105#issuecomment-703882136) as well.

**Comment by roblourens** [comment]
What exactly do you need to pass, all the parameters that can go into an ssh config? Will it already exist in the user's ssh config? Should it get written there?

**Comment by nturinski** [comment]
For my particular needs, I think I just need to pass in the host/hostname of currently available targets.  Rather than adding to the config, I would rather be able to run the "Connect to Host in New Window" command from my extension with the specific VM the user targeted.

Another useful parameter could be to control the behavior of the window ie current window vs. new window.

**Comment by roblourens** [comment]
Don't know whether you have access to see the linked commit, but you can now pass these args to 
`opensshremotes.openEmptyWindow` or `opensshremotes.openEmptyWindowOnCurrentHost`

```
interface IOpenWindowsArgs {
	host: string;
	userName?: string;
	port?: number;
}
```

**Comment by nturinski** [comment]
Awesome!  Thanks @roblourens
