### ISSUE TITLE
下载服务器的文件到本地

### ISSUE THREAD

**Issue by A-lazy-pig** [microsoft/vscode-remote-release#3554]
Issue Type: <b>Bug</b>

下载服务器的文件到本地的时候，经常断开连接，并且下载下来的文件，或者目录都是缺失的

Extension version: 0.51.0
VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.90GB (2.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bamurtaugh** [comment]
I believe the issue here is:

Download the file from the server to the local

When downloading files from the server to the local, the connection is often disconnected, and the downloaded files or directories are missing

**Comment by roblourens** [comment]
If this is still an issue, please give more details
