### ISSUE TITLE
If `runServices` in devcontainer.json doesn't contain `service` vscode hangs forever connecting to the container with no error

### ISSUE THREAD

**Issue by benjamingwynn** [microsoft/vscode-remote-release#3555]
- VSCode Version: 1.49.0-insider
- Local OS Version: macOS 10.13.6 (17G7024)
- Remote OS Version: n/a
- Remote Extension/Connection Type: Docker
```
Version: 1.49.0-insider
Commit: 44ad54d9faa4604ab17628e8396e072258187737
Date: 2020-08-21T06:14:54.511Z
Electron: 9.2.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0
```

Steps to Reproduce:

1. Create a devcontainer in the folder with the `runServices` key, without the service from the `service` included.
2. Restart the folder in the dev container.

vscode will hang on "Starting container" after starting the instances listed in `runServices`. The logs provided by Dev Containers in the terminal show the other services starting, and using Docker and docker-compose on the command line confirms this. I believe vscode simply doesn't continue as the service it expected in the `service` key is never started.

Not starting the service is the correct behaviour, as stated in the documentation:

> An array of services in your Docker Compose configuration that should be started by VS Code. These will also be stopped when you disconnect unless "shutdownAction" is "none". Defaults to all services.

However, vscode should probably either return an error to the developer informing them that listing the services they wish to develop on in their docker-compose.yml is not enough (which is the mistake I made), or also start `service` regardless of if it exists in `runServices`.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by StevenLiekens** [comment]
I also had this problem. I expected that the value of the _service_ key would implicitly be added to the _runServices_ array.
