### ISSUE TITLE
Remote SSH terminal fails on a Cpanel environment

### ISSUE THREAD

**Issue by murrwood** [microsoft/vscode-remote-release#3557]
Issue Type: <b>Bug</b>

Attempting to do remote development in a Cpanel Shared hosting eenvironment.  The SSH portion is successful but the terminal extension fails.  Message is The terminal process failed to launch: A native exception occurred during launch (forkpty(3) failed.).

Extension version: 0.51.0
VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 5.4.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) Dual  CPU  E2180  @ 2.00GHz (2 x 1994)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|3.83GB (0.14GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by iantrudell** [comment]
I am also receiving the same error.

Extension version: 0.51.0
VS Code version: 1.48.2
Local OS Version: Windows 10
Remote OS Version: CentOS 7

**Comment by murrwood** [comment]
I was able to resolve the issue.  Turns out that my Cpanel was set to an SSH environment called jail shell.  I got the Cpanel admin to give me the normal bash shell and things worked.
