### ISSUE TITLE
Unable to start pwsh within WSL Remote Development extension in the integrated terminal

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-remote-release#356]
Issue Type: <b>Bug</b>

1. Start WSL Remote extension
2. Open Integrated Terminal
3. With PowerShell Core installed in WSL, start `pwsh`

### Expected

PowerShell shows the prompt

### Actual

PowerShell does not show the prompt

### Notes

If I try to run pwsh in conhost WSL, pwsh starts as expected.

![image](https://user-images.githubusercontent.com/2644648/57947049-b17f9e80-7892-11e9-9c3f-1b8c6588cfba.png)

@Tyriar any thoughts here? It might be a PowerShell bug, but if you can help me diagnose this we can get more info.

Extension version: 0.36.0
VS Code version: Code - Insiders 1.35.0-insider (a69d0f8b218498e22b7c3a0f76926cc6322e6106, 2019-05-17T05:18:13.839Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.93GB (8.44GB free)|
|VM|0%|
</details>

**Comment by TylerLeonhardt** [comment]
Likely related, this means the PowerShell extension fails to start up:

![image](https://user-images.githubusercontent.com/2644648/57947542-05d74e00-7894-11e9-9b08-550e531fd084.png)

My plan was to use WSL Remote Development to test the PowerShell extension builds on Linux this way, but it seems like we're not quite there yet.

**Comment by Tyriar** [comment]
This looks like a pwsh bug, this is what gets sent by the pty:

![image](https://user-images.githubusercontent.com/2193314/58045727-299ace00-7af8-11e9-95b5-710e6be98f40.png)

When I try this on a Linux window it works but there is a bit of a delay before the prompt shows up, typing then messes up the cursor position. This screenshot was made by pressing `pwsh<enter>hello`

![image](https://user-images.githubusercontent.com/2193314/58046103-3a980f00-7af9-11e9-8b0b-a9a9ffca61dc.png)

**Comment by TylerLeonhardt** [comment]
@Tyriar your first screenshot is linux or wsl?

Seems to be setting and querying the console position. 

I still don't quite see how this would be pwsh bug if it works fine in conhost.exe. Why would vscode terminal vs conhost have a difference?

Question: the terminal within a "Remote Development - WSL session" vs a regular windows terminal (in VSCode) where I run `bash` or `ubuntu`... is there a difference at all?

**Comment by Tyriar** [comment]
@TylerLeonhardt the first screenshot is Windows in a WSL window, the second is an Ubuntu 18.04 VM. Note that in both of these windows conhost isn't touched at all, they are both be using the Linux pty backend. Could be a WSL bug? 🤔 

> Question: the terminal within a "Remote Development - WSL session" vs a regular windows terminal (in VSCode) where I run bash or ubuntu... is there a difference at all?

Windows terminal is `Conhost <-> cmd <-> WSL bridge(?) <-> bash`, Remote is `node-pty <-> bash` (on the remote).

**Comment by TylerLeonhardt** [comment]
> Could be a WSL bug? 🤔 

Could be... I might have to wait for WSL 2 and try again...

> Windows terminal is Conhost <-> cmd <-> WSL bridge(?) <-> bash, Remote is node-pty <-> bash (on the remote).

Sorry I didn't mean conhost here, I meant... VSCode, not using the Remote extension. Using wsl in the VSCode integrated terminal.

How does this^ differ from the Remote extension's use of the terminal with WSL?

I hope that's less confusing lol lots of pieces

**Comment by Tyriar** [comment]
> Sorry I didn't mean conhost here, I meant... VSCode, not using the Remote extension. Using wsl in the VSCode integrated terminal.

For that it's much more complicated: `node-pty <-> (con|win)pty <-> Conhost <-> cmd <-> WSL bridge(?) <-> bash`

**Comment by rkeithhill** [comment]
@TylerLeonhardt I can start VSCode, start a pwsh terminal, load WSL bash and then turn around and load pwsh (Linux) and that works fine. 
![image](https://user-images.githubusercontent.com/5177512/58124001-61724600-7bca-11e9-95ad-4562b0a8265c.png)

**Comment by TylerLeonhardt** [comment]
Yeah - I get the feeling that there's something funny here maybe with vscode's lack of using the WSL bridge... or maybe lack of using conhost in the Remote Development extension...

I don't have the full understanding of the pieces. 

@Tyriar this seems surprisingly scoped to just an issue in the terminal in the Remote Development experience.

**Comment by Tyriar** [comment]
Please try again with tomorrow's build, hopefully the bug fix related to DSR I did today will fix the problems.

**Comment by TylerLeonhardt** [comment]
Looks like there wasn't an insiders drop today. Let's wait for one tomorrow

**Comment by rkeithhill** [comment]
`pwsh` no longer hangs on startup for me. This is with today's insiders build.

**Comment by TylerLeonhardt** [comment]
Same! We can close this now. Thanks all
