### ISSUE TITLE
connect with two or more ssh users at the same time

### ISSUE THREAD

**Issue by void32** [microsoft/vscode-remote-release#3563]
I would like to be able to connect to a remote with two or more ssh users at the same time. Currently, this is not possible because the name of the ssh target is the host from the ssh config file.

My current workaround is to rename the _host_ so it is prefixed with the username. I tried to call it _user_@_hostname_ but then VSCode does not populate the _recent list_.

**Comment by roblourens** [comment]
You will need different ssh configs or to type `user1@host` then `user2@host`. Maybe I don't understand the problem though.

**Comment by void32** [comment]
That's my current workaround. I create several hosts for the same remote machine. So the .ssh/config becomes like this:

```
Host <remote machine>
  User <remote user>
  HostName <remote machine>
Host user2-<remote machine>
  User user2
  HostName <remote machine>
```


This is a bit tedious, maybe [Remote Explorer](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) could handle this, so the UX/UI becomes more intuitive?
