### ISSUE TITLE
Git: Auto Repository Detection not work on remote containers

### ISSUE THREAD

**Issue by curoky** [microsoft/vscode-remote-release#3565]
- VSCode Version: 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13)
- Local OS Version: Darwin x64 19.6.0
- Remote OS Version: docker container on Debian GNU/Linux bullseye/sid
	- uname -a : Linux devbox 4.14.81.bm.15-amd64 #1 SMP Debian 4.14.81.bm.15 Sun Sep 8 05:01:33 UTC 2019 x86_64 GNU/Linux
- Remote Extension/Connection Type: SSH/Docker

Steps to Reproduce:

1. ssh to docker container
2. source control page is empty

   ![image](https://user-images.githubusercontent.com/53091022/91070927-13b87900-e66a-11ea-93ea-d90b27cfb664.png)

3. the git repo will be detected only after opening the file which is in git repo.

**Comment by tanhakabir** [comment]
@curoky are you still seeing this issue?

**Comment by curoky** [comment]
It looks like the problem has been fixed, thanks 🥳.
