### ISSUE TITLE
SSH login encountered a problem：Failed to connect to the remote extension host server (Error: XHR failed）

### ISSUE THREAD

**Issue by TongzhouZhu** [microsoft/vscode-remote-release#3570]
Failed to connect to the remote extension host server (Error: XHR failed）

**Comment by bamurtaugh** [comment]
Thanks for opening this. I believe this is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/3349, so closing this thread. Please feel free to let us know if you have any other questions or feedback!
