### ISSUE TITLE
Failure to connect to VS Code Server

### ISSUE THREAD

**Issue by dcmdorazio** [microsoft/vscode-remote-release#3575]
Issue Type: <b>Bug</b>

Attempted to connect to a "Remote - SSH" server through the green connection button at the bottom left cornere of the VS Code IDE. Continue steps to log into the server. 

Extension version: 0.51.0
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by germanolleunlp** [comment]
Same here

**Comment by lvmingzhe** [comment]
Same here

**Comment by Chuxel** [comment]
Can you please include your log details? Thanks.

**Comment by dcmdorazio** [comment]
Here's my log details:

[21:49:04.776] > Server did not start successfully. Full server log at /home/student/.vscode-serv
> er/.e790b931385d72cf5669fcefc51cdf65990efa5d.log >>>
> main: line 371: /home/student/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf6
> 5990efa5d/server.sh: No such file or directory
> <<< End of server log
> 32058af2eb14##32##
[21:49:04.776] Received install output: 32058af2eb14##32##
[21:49:04.778] Resolver error: The VS Code Server failed to start
[21:49:04.782] ------

**Comment by Chuxel** [comment]
If you remove the `/home/student/.vscode-server` folder and retry, does the problem go away?

If not, can you include the entire log after it fails? This looks like just the last part.

**Comment by dcmdorazio** [comment]
@Chuxel You are the man! Thank you so much! It fixed the problem.

**Comment by eromoe** [comment]
After update vscode today, I got this error too .

**Comment by dcmdorazio** [comment]
**Update:** Reopened
@Chuxel & @eromoe  I appologize, i had it working and then the error cam up again once VS Code updated. How do you delete this folder? I am having a brain fart.

**Comment by dcmdorazio** [comment]
@eromoe I completely forgot how to delete the `.vscode-server` folder. How did you do this? If you could relay your process, that would be fantastic!

~Cody

**Comment by eromoe** [comment]
It is on you user home folder

**Comment by dcmdorazio** [comment]
@eromoe  Through my Remote SSH Terminal? When I deleted the `.vscode-server` folder before, I could have sworn it was in my file explorer. I can't see it in the explorer, and it will not allow me to delete the directory through the terminal.

Where am I going wrong or getting confused?
