### ISSUE TITLE
Issue with R since last VS Code update

### ISSUE THREAD

**Issue by asitemade4u** [microsoft/vscode-remote-release#3578]
Issue Type: <b>Bug</b>

- I have updated VS Code to the very last version. I work on the last version of Debian 10  Stretch
- I am developping with R using a Remote container based upon Conda. Until now, everything was working perfectly.
- I use the [R](https://github.com/Ikuyadeu/vscode-R) addon to execute the R code
- Now, when I execute R code I get an error:
```R
> 0~# HEADER: Save Pics                                                                                                    
+ source("kuq-nki/kuq-nki/plc/R/ini.R")1~
Error: unexpected numeric constant in:
"0~# HEADER: Save Pics
source("kuq-nki/kuq-nki/plc/R/ini.R")1"
```
As I understand it, R now nests every instructions within a **prefix** `~0` and a **suffix** `1`, hence the error

Please help as I am in production.
Best,
Stephen

Extension version: 0.134.1
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:56:10.074Z)
OS version: Linux x64 4.19.0-10-amd64
Remote OS version: Linux x64 4.19.0-10-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 1500 Quad-Core Processor (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.66GB (6.60GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: Python 3 - Miniconda|
|OS|Linux x64 4.19.0-10-amd64|
|CPUs|AMD Ryzen 5 PRO 1500 Quad-Core Processor (8 x 2300)|
|Memory (System)|15.66GB (6.61GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Is this an issue with the R code? You might need to file an issue with the project providing that.

**Comment by andycraig** [comment]
Hi @asitemade4u, this might be because you have the setting `R: Bracketed Paste` enabled. If not, please open an issue at https://github.com/Ikuyadeu/vscode-R and we will help you out.

**Comment by chrmarti** [comment]
Thanks @andycraig. Closing as an issue not with Remote-Containers.
