### ISSUE TITLE
Error: listen EACCES 127.0.0.1:9753

### ISSUE THREAD

**Issue by giggio** [microsoft/vscode-remote-release#358]
VSCode Version:
* Version: 1.35.0-insider (user setup)
* Commit: a69d0f8b218498e22b7c3a0f76926cc6322e6106
* Date: 2019-05-17T05:18:13.839Z
* Electron: 3.1.8
* Chrome: 66.0.3359.181
* Node.js: 10.2.0
* V8: 6.6.346.32
* OS: Windows_NT x64 10.0.17763

- Repo: using sample from https://github.com/Microsoft/vscode-remote-try-node

Also verified with the Node.js sample.

Steps to Reproduce:

1. Open folder in container

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: Yes

This is the full log:

````
Setting up container for folder: c:\p\rabiscos\vscode-remote-try-rust
Run: docker exec 5e32fb7ffd769ce80e39562e734efc54b7d71fc3652bd82d5cdecf8a53d4e89a /bin/sh -c (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
Run: docker exec 5e32fb7ffd769ce80e39562e734efc54b7d71fc3652bd82d5cdecf8a53d4e89a test -d /root/.vscode-remote/bin/a69d0f8b218498e22b7c3a0f76926cc6322e6106
Run: docker exec 5e32fb7ffd769ce80e39562e734efc54b7d71fc3652bd82d5cdecf8a53d4e89a test -d /root/.vscode-remote/extensions
Run: docker exec 5e32fb7ffd769ce80e39562e734efc54b7d71fc3652bd82d5cdecf8a53d4e89a test -f /root/.vscode-remote/.postCreateCommandMarker
Extension host agent is already running.
Error: listen EACCES 127.0.0.1:9753
        at Server.setupListenHandle [as _listen2] (net.js:1313:19)
        at listenInCluster (net.js:1378:12)
        at doListen (net.js:1492:7)
        at process._tickCallback (internal/process/next_tick.js:63:19)
````

If you need more info please let me know.

**Comment by chrmarti** [comment]
We need to handle EACCES like we handle EADDRINUSE.

**Comment by giggio** [comment]
I noticed that after a computer restart the error went away. But I had no idea of what was happening, and I can't reproduce it anymore.
