### ISSUE TITLE
Need command for editing different remotes' settings.json in command palette

### ISSUE THREAD

**Issue by NewtMa** [microsoft/vscode-remote-release#3584]
There's a settings.json in the remote, I think it's under the `Machine` directory,  but I cannot access it through the command palette, it always suggest the host's settings.json, not the remote's.

**Comment by sandy081** [comment]
There is a command to open it

<img width="622" alt="image" src="https://user-images.githubusercontent.com/10746682/91741631-46f09000-ebb5-11ea-8d4d-917bf95ec2df.png">
