### ISSUE TITLE
Default config for attaching to containers

### ISSUE THREAD

**Issue by smhc** [microsoft/vscode-remote-release#3585]
The SSH remote extension runs the extension host using a login shell, which sources in .profile and .kshrc. This sets up the runtime environment correctly for extensions that depend on environment variables.

However the container/docker extension simply uses 'docker exec' when attaching to existing containers, and this does not run a login shell. Consequently any extensions started do not have a correct environment and commonly fail.

e.g vscode appears to run the following to run the host:
```
docker exec -i -u myuser -e VSCODE_REMOTE_CONTAINERS_SESSION=53627264-3da6-420b-ab74-afdd4810f4381598533888068 5b88c83c230b456e4489a112998a1651dc7c6c936c39d3e9c812d221c5606da6 /home/myuser/.vscode-server-insiders/bin/b58f4549b2919fa3a5dc52df83f4ba60780c625f/node -e 
```

I would like it to run the following instead:
```
docker exec -i -u myuser -e VSCODE_REMOTE_CONTAINERS_SESSION=53627264-3da6-420b-ab74-afdd4810f4381598533888068 5b88c83c230b456e4489a112998a1651dc7c6c936c39d3e9c812d221c5606da6 /usr/bin/ksh -lc "/home/myuser/.vscode-server-insiders/bin/b58f4549b2919fa3a5dc52df83f4ba60780c625f/node -e "
```

Note the addition of '/usr/bin/ksh -lc'. This would ideally use the 'automationShell' setting when invoking node.

**Comment by smhc** [comment]
I see the new option to the insiders build pretty much does what I am describing above:
```json
{
	"userEnvProbe": "loginInteractiveShell"
}
```

However this needs to be set per container name/image. It would be great if we could specify a default for all attached containers - in my situation the image and the container name regularly change but the connection method stays the same.

Is there a 'default attached devcontainer.json' setting somewhere?

**Comment by Chuxel** [comment]
@chrmarti I think this is covered under the 1.57 release, correct?

**Comment by chrmarti** [comment]
There is no setting, but the default is now `"userEnvProbe": "loginInteractiveShell"`. Closing as fixed, thanks.
