### ISSUE TITLE
${localWorkspaceFolder} is not substituted

### ISSUE THREAD

**Issue by krotton** [microsoft/vscode-remote-release#3588]
- VSCode Version: `1.48.2 (system setup)`
- Local OS Version: `Windows_NT x64 10.0.19041`
- Remote OS Version: `mcr.microsoft.com/vscode/devcontainers/base:0-ubuntu-20.04`
- Remote Extension/Connection Type: `Docker`

Steps to Reproduce:

1. Add `"remoteEnv": { "LOCAL_WORKSPACE_FOLDER": "${localWorkspaceFolder}" }` to `devcontainer.json`,
2. See that `echo $LOCAL_WORKSPACE_FOLDER` resolves to a raw string of `${localWorkspaceFolder}` inside the container, making it impossible to mount anything in a docker-in-docker scenario.

Note: exactly the same thing happens with `containerEnv`.

Does this issue occur when you try this locally?: Doesn't make sense.
Does this issue occur when you try this locally and all extensions are disabled?: Doesn't make sense.

**Comment by krotton** [comment]
I think it may be related to Docker Desktop's WSL2 backend.

As a workaround, instead of relying on `${localWorkspaceFolder}`, I currently refer directly to the mounted docker volume's contents: `/var/lib/docker/volumes/myvolume/_data/`.

**Comment by chrmarti** [comment]
You seem to be using a volume. There is no 'local workspace folder' in this case since we don't make assumptions about how and where the volume is being persisted.

**Comment by Chuxel** [comment]
@chrmarti In order for Docker-from-Docker to work, you need to know what the OS volume is. I think in this case it would be reasonable to return the volume name so that you could use "-v" inside the container.

**Comment by Chuxel** [comment]
This is also part of the reason for #2888, #3034

**Comment by chrmarti** [comment]
@krotton What do you want to use it for? Would the volume name help in your case?

**Comment by krotton** [comment]
I'm bind-mounting a configuration file to a specific path inside a container. In my case the volume name would help, because I can freely choose the path, but it's not a generic solution (unless there is a way in Docker to mount a specific file from the volume instead of the whole volume I'm not aware of).

**Comment by chrmarti** [comment]
Replacing `${localWorkspaceFolder}` with the volume name won't work for mounting the correct folder because that can be subfolder inside the volume. https://github.com/moby/moby/issues/32582 would help, but that is not implemented yet.
