### ISSUE TITLE
Keep silent when disconnected on Windows

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode-remote-release#3594]
https://github.com/microsoft/vscode-remote-release/issues/2505

You should keep silent like in linux KDE does when disconnected from remote. Otherwise user would be annoyed with orange vscode  remote windows that wouldn' t be used for current work session from even other workspaces on Windows 10.

Happens every day if you are used to suspending computer every night.

**Comment by Chuxel** [comment]
Duplicate of #3526
