### ISSUE TITLE
Cannot delete windows folders when vscode with wsl connection is open

### ISSUE THREAD

**Issue by itgenie98** [microsoft/vscode-remote-release#3598]
- VSCode Version: 1.48.1
- Local OS Version: Windows 1909
- Remote OS Version: WSL Linux Debian Buster
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. use a project that uses cmake
2. place it somewhere outside the wsl (/mnt/c or else)
3. open the project over wsl
4. make a subfolder named build
5. Install/ Open Visual Studio 2019 Developer Command Prompt v16.7.1
6. run cmake in the build folder
7. try to delete the build folder
8. check some directorys inside: on some you even cannot make anything in the security tab

Does this issue occur when you try this locally?: No - when vscode simply uses windows paths everything is fine

**Comment by aeschli** [comment]
In the steps, how is Visual Studio Code involved?

**Comment by itgenie98** [comment]
In step 3, the folder containing the cmake project is opened with vscode, either with running "code ." in the folder or with "Remote WSL: Reopen Folder" (or simply "open folder" when you have a vscode in wsl mode open)

**Comment by aeschli** [comment]
Is that WSL1? I believe what you are seeing is https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace-in-wsl-1

**Comment by itgenie98** [comment]
Yes im using WSL 1, thanks for the info!
I read that the problem will not be patched, that means this issue can be closed as well?

**Comment by aeschli** [comment]
Yes, there won't be a fix. The best is to change the watcher to polling, unless you have a very big project.
