### ISSUE TITLE
Host is down

### ISSUE THREAD

**Issue by hmohapatra1** [microsoft/vscode-remote-release#3599]
Issue Type: <b>Bug</b>

sudo systemctl status vsftpd
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
please help

Extension version: 0.44.4
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|7.91GB (2.21GB free)|
|VM|0%|
</details>

**Comment by PavelSosin-320** [comment]
Do you mean that systemctl doesn't work in WSL? It is because Microsoft WSL doesn't support systemd. WSL images have their own proprietary init as PID 1 and can't support systemd, i.e. systemctl, dbus, service autostart, ............
Only Mirosoft WSL team can help you, me, and many others.

**Comment by hmohapatra1** [comment]
> Do you mean that systemctl doesn't work in WSL? It is because Microsoft WSL doesn't support systemd. WSL images have their own proprietary init as PID 1 and can't support systemd, i.e. systemctl, dbus, service autostart, ............
> Only Mirosoft WSL team can help you, me, and many others.

Got it , Thanks you so much
