### ISSUE TITLE
Cannot install on a server without internet access

### ISSUE THREAD

**Issue by salehqt** [Microsoft/vscode-remote-release#36]
Our servers are running in a very secure enterprise environment and they don't allow outbound connections to the internet. I had to manually transfer the server package and rig the script to install it.

It would be great if VSCode could just SCP the server package into the server instead of using wget.

**Comment by underchemist** [comment]
seems related to #15

**Comment by LabhanshAgrawal** [comment]
> Our servers are running in a very secure enterprise environment and they don't allow outbound connections to the internet. I had to manually transfer the server package and rig the script to install it.
> 
> It would be great if VSCode could just SCP the server package into the server instead of using wget.

Hi, can you tell me how you installed it manually?
Thanks

**Comment by salehqt** [comment]
I don’t think the authors would approve of my methods.

An alternative way is to remote into an SSH machine with internet access (like a local VM) and have the server component installed. Then copy the installed directory (~/.vscode-remote) to the server without internet access.
