### ISSUE TITLE
Remote SSH - Go to implementation doesn't work (No implementation found...)

### ISSUE THREAD

**Issue by chendave** [microsoft/vscode-remote-release#3601]
- VSCode Version:
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763
- Local OS Version: win10
- Remote OS Version: Ubuntu 18.04.3 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. setup vscode with remote ssh
2. connect with remote golang project (https://github.com/kubernetes/kubernetes)
3. right click on the interface and click "Go to implementations", it always say "no implementation found for ..."

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

This works when the source is imported locally, and it is used to work for me before I switch to another new laptop and re-setup everything, all other features works for me except this one.

I just don't know how to trouble shooting this issue? Could anyone help me?

**Comment by bamurtaugh** [comment]
Possibly related to https://github.com/microsoft/vscode-remote-release/issues/2816?

**Comment by roblourens** [comment]
If this is still an issue, please file an issue on the Go extension repo
