### ISSUE TITLE
Test remote extension welcome views

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#3602]
Refs: https://github.com/microsoft/vscode-remote-release/issues/3504

- [x] wsl @lszomoru
- [x] ssh @alexdima
- [x] dev container @mjbvz

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%233602%0A%0A)

---

WSL:
- Have the WSL extension installed. Do **not** have WSL installed. Verify that you get a relevant welcome message in the remote explorer view when you select WSL.
- Have the WSL extension installed. Do have WSL installed. Do **not** have any distros installed. Verify that you get a relevant welcome message in the remove explorer view when you select WSL.

SSH:
- Have the SSH extension installed. Remove all your ssh configs. Verify that you get a relevant welcome message in the remote explorer view when you select SSH.

Dev Container:
- Have the containers extension installed. Do not have docker started (or don't have it installed). Verify that you get a relevant welcome message in the remote explorer view when you select containers.
- Have the containers extension installed. Have docker running. Do not have any containers. Verify that you get a relevant welcome message in the remote explorer view both when you have a folder open and when you don't have a folder open.

**Comment by lszomoru** [comment]
@aeschli, are you planning to publish a new build of the WSL extension? 
At the moment I am blocked on validating the new WSL welcome experience. Thanks!

**Comment by alexdima** [comment]
:+1: Here is the message I get in the SSH Targets view: "No SSH hosts have been configured yet"

**Comment by aeschli** [comment]
@lszomoru Published Remote-WSL 0.44.5

**Comment by lszomoru** [comment]
@alexr00 when I click on the `Remote Explorer` with WSL not being installed I am seeing the following error notification:

![image](https://user-images.githubusercontent.com/3372902/91841434-a8b30780-ec52-11ea-8c74-99fd73f1a5a1.png)

Is that expected? After I dismiss the notification I can see the welcome message in the viewlet.
I can repro this every time I reload the window and click on the `Remote Explorer ` viewlet.

**Comment by alexr00** [comment]
I'm not sure if that's intentional, but it isn't a good experience. I'll take a look.

**Comment by lszomoru** [comment]
Filed https://github.com/microsoft/vscode-remote-release/issues/3611
