### ISSUE TITLE
Test: DevContainer Options in Dockerfile

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#3603]
Refs: #3590

- [x] anyOS @egamma
- [x] anyOS @alexr00

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%233603%0A%0A)

---

Using Remote-Containers:
- Open empty folder
- Run command: Add Development Container Configuration Files
- Pick one of the definitions with `[Option]` comments in their Dockerfile, e.g.:
  - Azure Ansible
  - Azure Terraform
  - Java
- Make sure you can configure these `[Option]`s with a multi-pick QuickPick at the end.
- Make sure the devcontainer.json reflects your choices (`"build"."args"` map).

**Comment by alexr00** [comment]
Tested with Windows.
