### ISSUE TITLE
Test: Clone Docker-Compose repository into volume

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#3604]
Refs: #3404

- [x] anyOS @bpasero
- [ ] anyOS @Tyriar

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%233604%0A%0A)

---

Using Remote-Containers:
- Check from time to time that there is no `vsc-volume-bootstrap` container staying around (these should be temporary).
- Run command: `Clone Repository in Container Volume...`
- Use `chrmarti/node-mongo-devcontainer` as the repository.
- Verify the DevContainer starts successfully.
- ESlint extension should be installed.
- Try reloading the window and verify the container comes up.
- Try running the command: `Rebuild Container` and verify the container comes up.
- Break the configuration in `.devcontainer` and `Rebuild Container`.
- Verify that you are offered a Recovery Container to fix the configuration.
- Verify that after fixing the configuration you can again `Reopen in Container`.

**Comment by bpasero** [comment]
@chrmarti thanks for providing nice and clear steps, helps a lot to verify as someone that is not an expert in this area.

**Comment by Tyriar** [comment]
The recovery container is pretty neat, as a user I might not know what to do once I've fixed the issue though (reopen in container or reload the other window?).
