### ISSUE TITLE
Connection attempt uses wrong host name

### ISSUE THREAD

**Issue by justageek** [microsoft/vscode-remote-release#3605]
- VSCode Version: 1.48.2
- Local OS Version: Mac OS 10.14.6
- Remote OS Version: CentOS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. My host name is brian.development.cashtn.com, my username is brian
2. Trying to connect attempts to provide the password for brian@development.cashtn.com, the wrong host name.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
Do you have an SSH config set up with these details? What is it? Remote-SSH is just using whatever details you give it an invoking ssh.
