### ISSUE TITLE
Put default distro on top in Select WSL distro menu

### ISSUE THREAD

**Issue by RomanKornev** [microsoft/vscode-remote-release#3606]
When using 'Reopen Folder in WSL':
It would be nice if default distro was on top or if there was a way to completely skip this menu by setting it to always open the default distro

![image](https://user-images.githubusercontent.com/5807561/91773967-7670be00-ebf0-11ea-9b91-186de60b8635.png)

**Comment by aeschli** [comment]
will. be fixed in next release of the Remote-WSL extension
