### ISSUE TITLE
Failed to connect to the remote extension host server (Error: connect ECONNREFUSED ::1:37485)

### ISSUE THREAD

**Issue by albinjanzen** [microsoft/vscode-remote-release#3608]
I get this error when I try to open a new window both from the command line and from vscode. 

"Failed to connect to the remote extension host server (Error: connect ECONNREFUSED ::1:37485)"

- VSCode Version: 1.49.0-insider
- Local OS Version: 18363.1049
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: WSL2
Steps to Reproduce:

1. Remote WSL: New Window

![image](https://user-images.githubusercontent.com/35869961/91830809-8b2a7180-ec43-11ea-81d5-6d37df6ab8b8.png)

**Comment by albinjanzen** [comment]
It works when i change to the wsl version 1

**Comment by aeschli** [comment]
Can you paste the full content of the WSL log (Command: `Remote-WSL: Show Log`)?

**Comment by albinjanzen** [comment]
This issue was resolved with the update: 2004: 19041.450
