### ISSUE TITLE
ssh session exists immediately

### ISSUE THREAD

**Issue by saiyan86** [microsoft/vscode-remote-release#361]
Issue Type: <b>Bug</b>

After connecting to the remote host, I can see uname session in intergrated terminal for a second, then the ssh session exists immediately. In developer tool, the error is: 
```
workbench.main.js:2367 Can't connect to RasperryPi: unreachable or not Linux x86_64 (Linux aarch64)
onDidNotificationChange @ workbench.main.js:2367
```

Extension version: 0.37.0
VS Code version: Code - Insiders 1.35.0-insider (6ac87465f297a9068bf767f45d6f372fc5697de9, 2019-05-17T17:48:07.036Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/13
