### ISSUE TITLE
Container picker closes when focus moves out

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#3610]
Testing #3604

This should stay open:

![image](https://user-images.githubusercontent.com/900690/91837725-abaaf980-ec4c-11ea-878a-c19ac512934a.png)

**Comment by connor4312** [comment]
seems like this still needs to be published cc @chrmarti

**Comment by chrmarti** [comment]
@connor4312 Published with Remote-Containers 0.139.1. 👍
