### ISSUE TITLE
Help and Feedback - Error while clicking on items

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-remote-release#3612]
Testing #3602

Clicking on the following items in the `Help and Feedback` view bring up an error notification: 
* Get Started
* Read Documentation
* Provide Feedback
* Review Issues

Seems to be due to the fact that the `Codespaces` extensions is installed so we might have to redirect this.

![image](https://user-images.githubusercontent.com/3372902/91848863-6641f880-ec5b-11ea-8842-a1976a1345d7.png)

![image](https://user-images.githubusercontent.com/3372902/91848909-7eb21300-ec5b-11ea-96c4-9d0b4ec513b2.png)

![image](https://user-images.githubusercontent.com/3372902/91848948-8e315c00-ec5b-11ea-961d-c3226aee47e0.png)

![image](https://user-images.githubusercontent.com/3372902/91848990-a1442c00-ec5b-11ea-999a-39e6c93ca9b4.png)

**Comment by alexr00** [comment]
The error notification is coming from the codespaces extension, but I added some defensiveness around the call that causes it so that we still show remote help. I will follow up for the error notification.

**Comment by osortega** [comment]
@lszomoru just to confirm the scenario. You were not signed in to the extension, correct?

**Comment by lszomoru** [comment]
@osortega, correct. The extension is installed, but I am not signed in.
