### ISSUE TITLE
Add setting for umask when creating new files

### ISSUE THREAD

**Issue by msires** [microsoft/vscode-remote-release#3613]
Did search, could find no similar requests

Would like the ability to set umask for the remote process creating files (on linux) with VS Code so I don't have to go to terminal and change them after creation.  If forgotten can result in user permission errors when they attempt to use the files created.
Thanks for considering this!

**Comment by Chuxel** [comment]
@misres Which extension are you referring to with this request?

If Containers, [there isn't a way to do this via Docker](https://github.com/moby/moby/issues/19189), but you should be to add the umask setting to /etc/bash.bashrc (or /etc/zsh/zshrc if you use zsh). Does that help?

**Comment by msires** [comment]
Chuxel,
Remote - SSH, version 0.51.0.
Can't make the change in etc/bash.bashrc since that would be a global change, and not everyone on this machine wants/needs it that way.
Mark

**Comment by roblourens** [comment]
Can you set it in your user bashrc?

**Comment by msires** [comment]
That appears to work, I'll close this issue (duh)
