### ISSUE TITLE
Remote WSL + External Git Client, locking isn't playing nice. 

### ISSUE THREAD

**Issue by dopry** [microsoft/vscode-remote-release#362]
- VSCode Version: 1.35.0-insider
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 18.10
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Open a Git Project in VSCode Remote
2 Open the same repo in Git Extensions.  Start modifying things.
3. Switch to Git Extensions try to stage/unstage files that have been altered or deleted.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Here is one of the specific errors I am seeing...

Unsupported file: 
```
System.UnauthorizedAccessException: Access to the path 'C:\Users\dopry\src\TypeNetwork\api.typenetwork.com\django\fonts\tests\tests.py' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at GitUI.Editor.FileViewer.<>c__DisplayClass81_0.<ViewFileAsync>g__GetFileText|2()
   at GitCommands.AsyncLoader.<>c__DisplayClass11_0`1.<LoadAsync>b__0(CancellationToken token)
   at GitCommands.AsyncLoader.<LoadAsync>d__12`1.MoveNext()
```

There was also an index.lock in git that wouldn't clear until I quit code insider.

**Comment by egamma** [comment]
upstream https://github.com/Microsoft/WSL/issues/3886

**Comment by dopry** [comment]
egamma, how are these the same? The issue your reference seems to be a locking issue inside the remote WSL environment. I'm trying to access the files from the host and getting locking errors. While I cannot say they're not potentially related, I would be sad if this specific test case (access from 3rd Party apps on host not just remote) we're forgotten.

**Comment by zdog234** [comment]
I'm having a tough time grocking the linked upstream issue, but I'm pretty sure I'm running into the same locking issue as @dopry.
@dopry, I was able to fix the issue by adding `"git.autorefresh": false` to my settings. It's a bit annoying, but it's better than the locking issues.

**Comment by zdog234** [comment]
@dopry, I was able to fix the issue by adding `"git.autorefresh": false` to my settings. It's a bit annoying, but it's better than the locking issues.

**Comment by dopry** [comment]
Cool... I'll keep it in mind when I try code-insiders again.

The issues were persistent for me. I found using process explorer that the kernel was holding handles to those files. Close Handle failed with processexplorer, even after several reboots. I eventually have to boot into safe mode and rename the locked files to clear the handles from the kernel so I could edit them.

After that experience, I'm extremely shy of touching any of the remote debugging until it's far more baked.

**Comment by Clovel** [comment]
Hi ! 
I too have a lock issue with Git. I am on **Win10 1809**, using **Ubuntu 18.04.2 LTS**, and I use a combination of GitKraken, VSCode Insiders (1.35.0-insider) and what appears to be v1.0.0 of the Remote - WSL extension. 

When I have VSCode opened, I have issues staging/stashing/fetching from my repositories from both the WSL CLI, and GitKraken. 

On GitKraken, I get : 
> Failed to cretae locked file 'C:/Path/to/.git/refs/remotes/origin/my-branch.lock' Access refused. 

On the WSL CLI, I get : 
`error: cannot lock ref 'refs/remotes/origin/my-branch': Unable to create '/wsl/path/to/.git/refs/remotes/origin/mybranch.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
From ssh://ip:port/repos/my-repo
 ! [new branch]      my-branch     -> origin/my-branch  (unable to update local ref)`

When I exit VSCode, I do not get these issues. Even more interesting, while reloading the VSCode window (from the command palette : "Developer: Reload Window") I get a small time frame during which I can use external git processes.

**Comment by Clovel** [comment]
BTW, Even if I can see why the referenced issue (microsoft/WSL#3886) might be related, this issue shouldn't be closed. Anyone searching for a solution will end here, not on the referenced issue. 

Just my two cents.

**Comment by Clovel** [comment]
I get why you referenced the issue microsoft/WSL#3886, but I do not think this issue should be closed. I have never encountered this issue with the release version of VSCode. This is likely a extension related or VSCode Insiders related issue. 

Also, the related issue might not seem related to git issues at first. People having this problem will likely end up here. 

Just my two cents. 
Thanks, 
Clovel

**Comment by aeschli** [comment]
You are right, this is not related to https://github.com/microsoft/WSL/issues/3886.

The problem is that both Windows Git and Linux Git are accessing the .git folder.
I created https://github.com/microsoft/vscode-remote-release/issues/1911 to track this.
