### ISSUE TITLE
Remote Welcome - Consider reducing the number of 'primary' buttons in welcome

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#3623]
Testing #3602

Currently the Welcome shows 4 primary actions/buttons

![image](https://user-images.githubusercontent.com/172399/91965978-8fbd5b80-ed11-11ea-8f7d-fa3ca6e80ba3.png)

Suggest to make some actions less prominent by using links. Similar to what the Debug View does:

![image](https://user-images.githubusercontent.com/172399/91966212-d448f700-ed11-11ea-9ed4-a6ecef7cd1dc.png)

For example we could make 'Reopen Folder' and 'Try a Sample' show as 'secondary actions' using a link.

**Comment by alexr00** [comment]
Welcome view after changes. Without a folder open:
![image](https://user-images.githubusercontent.com/38270282/91983351-d5871d80-ed2b-11ea-9c59-d02521358372.png)

With a folder open:
![image](https://user-images.githubusercontent.com/38270282/91983526-197a2280-ed2c-11ea-8ded-96c4bddf7666.png)
