### ISSUE TITLE
fail to connet remote server when the shell is fish

### ISSUE THREAD

**Issue by hua03** [microsoft/vscode-remote-release#363]
- VSCode Version: 1.35.0-insider
- Local OS Version: Windows 10 1803
- Remote OS Version: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-43-generic x86_64)
- Remote Extension/Connection Type: SSH

Here is error report:

![image](https://user-images.githubusercontent.com/19561959/57966593-bde52380-7986-11e9-9e9d-84556f2f1c80.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?:No

**Comment by hua03** [comment]
Is caused by the shell Fish！

**Comment by hua03** [comment]
It can't connnet to remote server when i switched bash to fish. 😞

**Comment by xa0082249956** [comment]
Duplicate #33.
