### ISSUE TITLE
remote SSH connect error

### ISSUE THREAD

**Issue by centorchen** [microsoft/vscode-remote-release#3637]
- VSCode Version: 1.48
- Local OS Version: 10.0.18362
- Remote OS Version: ubuntu 16.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
When I use Remote-SSH to connect my ubuntu developer server, it give me an alert:
![image](https://user-images.githubusercontent.com/45955780/92547565-ba666180-f287-11ea-92c2-1c8be35921a8.png)

but in windows powershell, I can connect correct.
![image](https://user-images.githubusercontent.com/45955780/92548069-ac651080-f288-11ea-9c9e-8a159cdc2a63.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Is this still an issue? What is that output in the log in chinese characters, can you share the text?
