### ISSUE TITLE
remote-ssh jupyter notebook fail

### ISSUE THREAD

**Issue by Mkxc** [microsoft/vscode-remote-release#364]
Issue Type: <b>Bug</b>

I operate by remote-ssh, workspace is set up in remote machine. When I try to run cells  in *.ipynb file, no real action token place. Just a message `Start Jupyter Server` shown forever. Even I start the jupyter mannually and set the address in remote workspace setting file ("python.dataScience.jupyterServerURI"), it act in no difference.  By the way, Jupyter with local vscode workspace works fine .

Extension version: 0.37.0
VS Code version: Code - Insiders 1.35.0-insider (6ac87465f297a9068bf767f45d6f372fc5697de9, 2019-05-17T17:48:07.036Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 3.10.0-693.2.2.el7.x86_64

**Comment by sz4l3k** [comment]
I am experiencing the same issue with Remote WSL. Console log on developer tools shows that it's stuck on  'Python Extension: Getting jupyter server options ...'. Tried reinstalling Jupyter and Python but nothing seemed to change anything.

**Comment by roblourens** [comment]
I think this is the same as https://github.com/microsoft/vscode-python/issues/5676. If not please open an issue on that repo.
