### ISSUE TITLE
Unable to push git repo on Remote SSH Windows target

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-remote-release#3644]
- VSCode Version: 1.49.0-insider
- Local OS Version: macOS Catalina
- Remote OS Version: Windows 10
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open a remote SSH connection to a Windows machine
2. cd into a git repo and make a change
3. Go into the Source Control pane and commit your change (this works fine)
4. Click on the "synchronize changes" button on the status bar at the bottom

Expected result:

Changes are pushed

Actual result:

The git action hangs forever

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Sorry for the slow response @TylerLeonhardt. Do you see anything in the Git output channel? How is auth set up for this repo/machine?

**Comment by TylerLeonhardt** [comment]
> Do you see anything in the Git output channel? 

Nothing unusual...

```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.27.0.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --git-dir
Open repository: c:\Users\tyleonha\Code\PowerShell\vscode\vscode-powershell
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git check-ignore -v -z --stdin
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git check-ignore -v -z --stdin
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse testing-something
> git rev-parse --symbolic-full-name testing-something@{u}
fatal: no upstream configured for branch 'testing-something'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
```

> How is auth set up for this repo/machine?

Pretty sure it's the regular HTTPS flow. I cloned it, and when I eventually pushed (over RDP) it popped the login dialog. After that, it doesn't show the dialog anymore.
```
PS C:\Users\tyleonha\Code\PowerShell\vscode\vscode-powershell> git remote -v
origin  https://github.com/TylerLeonhardt/vscode-powershell.git (fetch)
origin  https://github.com/TylerLeonhardt/vscode-powershell.git (push)
upstream        https://github.com/PowerShell/vscode-powershell.git (fetch)
upstream        https://github.com/PowerShell/vscode-powershell.git (push)
```

It's odd... over RDP it works fine as you would expect:

![image](https://user-images.githubusercontent.com/2644648/98846069-70bf0200-2403-11eb-8b43-1e0d0d85dd0c.png)

But in the vscode terminal... it just hangs:

![image](https://user-images.githubusercontent.com/2644648/98846123-83d1d200-2403-11eb-85ad-f67b0f193b09.png)

Something else I can provide? The steps should be easy enough:

* Remote into a Windows machine
* clone a repo and checkout a new branch
* try to push to that branch from the integrated terminal

**Comment by roblourens** [comment]
I'm sure it's trying to show a login dialog. How is that supposed to work @joaomoreno

**Comment by TylerLeonhardt** [comment]
I'm not sure where git stores its cached credentials... but I _feel_ like it could be looking in a location that, for whatever reason, is in a different place under SSH then not.

**Comment by roblourens** [comment]
Any idea @joaomoreno or @eamodio? 

@TylerLeonhardt is the `GIT_ASKPASS` environment var set in your terminal?

**Comment by TylerLeonhardt** [comment]
@roblourens That seems unusual since my target is Windows... unless it's run in gitbash?
```
PS > $env:GIT_ASKPASS
c:\Users\tyleonha\.vscode-server-insiders\bin\92192baf760315ac47fb2caaf3ce6d0778962352\extensions\git\dist\askpass.sh
```

**Comment by eamodio** [comment]
I think this might be a similar issue I had recently. I was able to fix it but upgrading to the latest Git Credential Manager Core beta. Might want to try that.

**Comment by TylerLeonhardt** [comment]
Wow @eamodio, that did the trick! Hope that GA's soon. Guess we can close this.
