### ISSUE TITLE
Run Remote - Containers within a Remote - SSH session

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-remote-release#3645]
Despite the documentation explains several ways of working with remote docker hosts for the Remote - Containers extension, none of them is optimal, since it requires additional configuration on at least one of:

- VSCode settings (`docker.host`)
- The host environment (install docker cli, or configure the env using docker-machine)
- The devcontainer (because of bind mounts, and because SSHFS is not fast enough)

It would be much simpler if the Remote - Containers extension could integrate with Remote - SSH, so it could spawn new `devcontainer`s using the existing tools (docker cli) found in the Remote - SSH current session.

This would be similar to how Remote - WSL and Remote - Containers interoperates.

So, users within a Remote - SSH session could see an option _Reopen in Container_ in the remote options for that session.

![image](https://user-images.githubusercontent.com/29582865/92645337-8ac05500-f299-11ea-8fdd-a99d6a6631e4.png)

**Comment by chrmarti** [comment]
Tracked as https://github.com/microsoft/vscode-remote-release/issues/2994.

Closing as duplicate.
