### ISSUE TITLE
VS Code remote edit doesn't work - but cli ssh with same credentials does work!

### ISSUE THREAD

**Issue by pitosalas** [microsoft/vscode-remote-release#3646]
I am using Insiders VSCode on a Mac. All software is up to date. I am connecting to a raspberry pi over wifi. I am able to ssh successfully: ssh pi@192.168.1.38 prompts for a password which I type in and I have a shell. It works.

Yet when I use the exact same computers, accounts, ip and password with the VScode Remote Explorer add-in, the password is not accepted. I keep getting prompted again for the password.

I am stumped. Any idea?

**Comment by bamurtaugh** [comment]
Hey @pitosalas, does it sound like the suggestions in issue https://github.com/microsoft/vscode-remote-release/issues/3484 might be relevant to your scenario?

**Comment by roblourens** [comment]
Please make sure you entered the username or have it in an ssh config
