### ISSUE TITLE
containerEnv, remoteEnv and postCreateCommand problems

### ISSUE THREAD

**Issue by slmg** [microsoft/vscode-remote-release#3648]
- VSCode Version: `1.48.2`
- Local OS Version: `Ubuntu Focal`
- Remote OS Version: `debian:buster-slim`
- Remote Extension/Connection Type: `Docker`
- Remote Containers Version: `v0.134.1`

**Goal**: run an entry-point script mounted at runtime, to operate in the workspace folder. Do this via the addition of a `bin` folder to the container `PATH` alongside the creation of a `WORKSPACE` environment variable, so as to target the dynamic location of the main app.
<details>
<summary>Example using Docker directly</summary>

  ```sh
>  tree
.
|-- app
|   `-- requirements
|       `-- requirements.txt
`-- bin
      `-- entrypoint

>  cat bin/entrypoint
#!/bin/bash

echo "running ls $WORKSPACE/requirements..."
ls "$WORKSPACE/requirements"

>  docker container run --rm \
        -v $(pwd)/app:/app \
        -v $(pwd)/bin:/some/bin/ \
        -e PATH=/some/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
        -e WORKSPACE=/app \
        debian:buster-slim \
        entrypoint
running ls /app/requirements...
requirements.txt

  ```

</details>

#### Using `containerEnv`

1. Create the executable `entrypoint` in `.devcontainer/bin/`. Configure `.devcontainer/.devcontainer.json` with the below config.

    ```json
    "workspaceMount": "type=bind,src=${localWorkspaceFolder},dst=/home/moby/${localWorkspaceFolderBasename}",
    "workspaceFolder": "/home/moby/${localWorkspaceFolderBasename}",
    "containerEnv": {
        "PATH": "/home/moby/${localWorkspaceFolderBasename}/.devcontainer/bin:${containerEnv:PATH}",
        "WORKSPACE": "/home/moby/${localWorkspaceFolderBasename}",
    },
    "postCreateCommand": "entrypoint",
    ```

1. `Rebuild Container` and see it fail with

    ```sh
    [730 ms] Start: Run: docker run -a STDOUT -a STDERR \
    --mount type=bind,src=/home/user/app,dst=/home/moby/app \
    -l vsch.quality=stable -l vsch.remote.devPort=0 -l vsch.local.folder=/home/user/app \
    -e PATH=/home/moby/app/.devcontainer/bin:${containerEnv:PATH} \
    -e WORKSPACE=/home/moby/app \
    --entrypoint /bin/sh vsc-app-3e0691ccaf88802a71a0d9ec831fcc0e-uid \
    -c echo Container started ; trap "exit 0" 15; while sleep 1 & wait $!; do :; done
    ```
    We can see that **`${containerEnv:PATH}` was not substituted in `PATH`**, which seems to be an issue similar to #3643.
    The **`--entrypoint` option seems a bit suspicious** too, I would have expected to see `--entrypoint entrypoint` or `--entrypoint /bin/sh entrypoint`

1. At this stage, the previously created container needs to be manually deleted

    ```sh
    docker container rm # containerid
    ```

#### Using `remoteEnv`

1. Use the same config as before but using `remoteEnv` instead of `containerEnv`

    ```json
    "workspaceMount": "type=bind,src=${localWorkspaceFolder},dst=/home/moby/${localWorkspaceFolderBasename}",
    "workspaceFolder": "/home/moby/${localWorkspaceFolderBasename}",
    "remoteEnv": {
        "PATH": "/home/moby/${localWorkspaceFolderBasename}/.devcontainer/bin:${containerEnv:PATH}",
        "WORKSPACE": "/home/moby/${localWorkspaceFolderBasename}",
    },
    "postCreateCommand": "entrypoint",
    ```
1. `Rebuild Container`. This time it gets built without issue. Unfortunately I could not find where to access the build logs, which seem to display only on failure (unless I missed something obvious?). However I can certify **the `entrypoint` script did not run**.

1. Run from a shell inside the container. The environment variables seem correctly passed.

    ```sh
    > env | grep PATH
    PATH=/home/moby/.vscode-server/bin/a04[...]bd0/bin:/home/moby/app/.devcontainer/bin:/home/moby/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    > env | grep WORKSPACE 
    WORKSPACE=/home/moby/app
    ```

1. Change the `postCreateCommand` to the below, then `Rebuild Container`.

    ```json
    "postCreateCommand": ["install-requirements"],
    ```
    No change, it it still not run.

1. Change the `postCreateCommand` to the below, then `Rebuild Container`.

    ```json
    "postCreateCommand": "bash .devcontainer/bin/install-requirements",
    ```
    This time it is executed :heavy_check_mark:. **But** unfortunately it does not work as expected :crying_cat_face:.
    I could pinpoint the issue being with the variable `WORKSPACE`, which is not passed to the command.
    I suppose that is a side-effect of `remoteEnv` vs `containerEnv`.
    Though given that `postCreateCommand` is defined in VsCode, I would have expected the `remoteEnv` variable to be passed to it. As the [doc](https://code.visualstudio.com/docs/remote/devcontainerjson-reference#_devcontainerjson-properties) say:

    > `remoteEnv`
    > A set of name-value pairs that sets or overrides environment variables for VS Code (or sub-processes like terminals) but not the container as a whole.

#### Using a combination of `remoteEnv` and `containerEnv`

This is the final configuration I adopted as a workaround. `PATH` and `WORKSPACE` get passed correctly to the container, and the entrypoint finally works as expected. :tada:

```json
"remoteEnv": {
    "PATH": "/home/moby/${localWorkspaceFolderBasename}/.devcontainer/bin:${containerEnv:PATH}",
},
"containerEnv": {
    "WORKSPACE": "/home/moby/${localWorkspaceFolderBasename}",
},
"postCreateCommand": "bash .devcontainer/bin/install-requirements",
```

Thank you for your support on this great extension!

**Comment by chrmarti** [comment]
Thanks for the detailed report. I'm fixing this by passing `remoteEnv` also to the `postCreateCommand`.

**Comment by chrmarti** [comment]
Verification:
- Have a folder with a `.devcontainer.json`:
```json
{
	"image": "debian:latest",
	"remoteEnv": {
		"FOO": "SUCCESS"
	},
	"postCreateCommand": "echo Verifying postCreateCommand: ${FOO:-FAILURE}",
	"postStartCommand": "echo Verifying postStartCommand: ${FOO:-FAILURE}",
	"postAttachCommand": "echo Verifying postAttachCommand: ${FOO:-FAILURE}"
}
```
- Open that folder in a container.
- Run command `Remote-Containers: Show Log`.
- Check that the log has the above 3 outputs saying 'SUCCESS'.
