### ISSUE TITLE
Remote SSH server permission denied during installation

### ISSUE THREAD

**Issue by ibrahmd** [microsoft/vscode-remote-release#3649]
- VSCode Version: 1.48.2
- OS Version: OSX 10.15.5 

Steps to Reproduce:

1. Connect to a remote Linux server that has a default home directory different from "/home", for example "/export/home"
2. User has only rwx access to "export/home/someuser" and not to "/home/someuser"
3. Installation gives the below error:

```
> Starting server with command... /export/home/someuser/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/export/home/someuser/.vscode-server/.a0479759d6e9ea56afa657e454193f72aef85bd0.log" < /dev/null
[07:14:53.507] > Waiting for server log...
[07:14:54.016] > Waiting for server log...
[07:14:54.527] > Waiting for server log...
[07:14:55.039] > Waiting for server log...
[07:14:55.551] > Waiting for server log...
[07:14:56.162] > Waiting for server log...
[07:14:56.575] > Waiting for server log...
[07:14:57.087] > Waiting for server log...
[07:14:57.599] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[07:14:57.603] > Server did not start successfully. Full server log at /export/home/someuser/.vscode-server/.a0479759d6e9ea56afa657e454193f72aef85bd0.log >>>
> main: line 372: /export/home/someuser/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/server.sh: Permission denied
> <<< End of server log
> a1eb8487eec5##32##
[07:14:57.603] Received install output: a1eb8487eec5##32##
[07:14:57.604] Terminating local server
[07:14:57.604] Resolver error: The VS Code Server failed to start
[07:14:57.607] ------




[07:14:57.608] Local server exit: 15
```

I tried using: 
```Remote SSH: Uninstall VS Code Server from Host..```
And manually deleting: 
```rm -r ~/.vscode-remote```

And rerunning and still got the same issue, also tried the insider build and got the same issue. Any ideas?

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
It looks like the server was correctly installed in the `/export/home` directory so do you know why you are missing permission to run that script? Can you check the permissions on the path in the log?

**Comment by ibrahmd** [comment]
All the files have rwx permission, upon further checking, it turns out this is happening because the partition on the server is mounted with noexec option for security, which overrides POSIX permissions:
```
mount | grep export
/dev/sdb1 on /export/home type ext4 (rw,nosuid,nodev,noexec,relatime,user)
```
also 
```
ls -la /export/home/someuser/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/server.sh
-rwxrwxrwx 1 someuser someuser 222 Sep 10 16:30 /export/home/someuser/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/server.sh
```

With noexec option, shell scripts can run with ```sh script.sh``` but not with ```./script.sh```, js and other dynamic code can also run on partitions with noexec option on.

Is there a way to resolve this or perhaps make all the calls to .sh scripts run using ```sh script.sh``` in the call stack of ```server.sh```

**Comment by maksteel** [comment]
Workaround:
---

- create a symlink called `.vscode-server` under your home directory on the remote server 
- the target of the symlink should point to a directory on the remote server where `noexec` option is off or unspecified

> Example:
> ```bash
> ~$ cd ~
> ~$ mv .vscode-server  /dir/on/target/where/noexec/is-set-off 
> ~$ ln -s /dir/on/target/where/noexec/is-set-off/.vscode-server .vscode-server
> ~$ ls -la
>...
>lrwxrwxrwx.  1 user groups 43 Oct  1 11:01 .vscode-server -> /dir/on/target/where/noexec/is-set-off/.vscode-server
> ```
