### ISSUE TITLE
Integrated Terminal does not open in currently opened folder's directory

### ISSUE THREAD

**Issue by vasilescur** [microsoft/vscode-remote-release#3652]
- VSCode Version: 1.48.2
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Attach VS Code to a running Docker container
2. Use the `Open Folder` button to open a folder from the container's filesystem
3. Press the keybind to open the Integrated Terminal; default is <Ctrl + `>

Expected: The new terminal's working directory is the folder that is opened in VS Code.
Actual: The new terminal's working directory is the parent folder, in my case.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
Could you attach a screenshot showing both the Explorer and the Terminal?

**Comment by vasilescur** [comment]
Here's a screenshot. For context:
- The container is called `dev310`
- The `docker run` command for the container was `docker run --name cs310 --mount type=bind,source=C:\Users\vasil\Desktop\CS310,destination=/cs310 -it dev310 bash`. So-- the container's folder `/cs310` is mounted to a folder on my host machine's Desktop.
- The folder that is open in VS Code is `/cs310/team-p1d-2193`, but the terminal opens with the working directory `/cs310`. Not sure if this is because it's the parent of my opened folder, or due to some other reason.

![image](https://user-images.githubusercontent.com/10100323/92948690-c1c47100-f427-11ea-857f-d46a9b8d57e9.png)

**Comment by chrmarti** [comment]
Could you post your devcontainer.json?

**Comment by vasilescur** [comment]
I wasn't using a devcontainer.json. I have the Docker extension, and I just right-click my container and `Attach Visual Studio Code`. 

![image](https://user-images.githubusercontent.com/10100323/93120242-0f8fe200-f691-11ea-9a14-7441a5a6967e.png)

**Comment by chrmarti** [comment]
Do you have a cwd set in your settings:
![image](https://user-images.githubusercontent.com/9205389/93170945-77ddd280-f728-11ea-8208-a17dfb3463af.png)

That would also be set just for your remote or workspace, you would see an indication telling you (e.g,. `Modified in: Remote`):
![image](https://user-images.githubusercontent.com/9205389/93171028-9f349f80-f728-11ea-88e7-bd0b6f8bff81.png)

**Comment by vasilescur** [comment]
Nope, there is no `cwd` set in my settings, neither remote nor local.

**Comment by chrmarti** [comment]
@Tyriar Do you know of any other ways / reasons for the cwd of the terminal to end up being the workspace's parent folder?

**Comment by Tyriar** [comment]
Only other way I can think of is if an extension overwrote the ctrl+` keybinding.

@vasilescur can you enable trace logging and take a log when creating the terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
