### ISSUE TITLE
set a timeout for wget vscode-server archive

### ISSUE THREAD

**Issue by Johnny4Fun** [microsoft/vscode-remote-release#3653]
when the remote end use wget to download vscode-server archive, the wget process seems stuck because of the remote network issue. There is no timeout for this.

Considering that there is already a option for using client to download and transfer the archive to remote end, I recommend to set a timeout for wget process, then once the wget runs over a limit it would be killed and locally downloading would be triggered.

**Comment by roblourens** [comment]
There is already a 7 second timeout for making a connection. What's going wrong with it in your case, is it just dowloading very slowly and so you would want to force downloading from the client?
