### ISSUE TITLE
Remote SSH Extension no longer works

### ISSUE THREAD

**Issue by marklythgoe** [microsoft/vscode-remote-release#3654]
Issue Type: <b>Bug</b>

Trying to connect to remote host for a workspace results in;
[09:05:30.106] remote-ssh@0.51.0
[09:05:30.106] win32 x64
[09:05:30.111] Picking SSH host
[09:06:56.196] Unhandled rejection: undefined
... 21 unhandled rejection errors.

Trying to open config file results in no UI, logs are;
Picking SSH host
[09:08:18.201] Picking SSH host
[09:09:26.618] ConfigFileWatcher: start watching file:///c%3A/Users/mark/.ssh/config
[09:09:26.618] ConfigFileWatcher: adding save listener
[09:09:26.618] ConfigFileWatcher: adding close listener
[09:10:15.681] ConfigFileWatcher: saving file:///c%3A/Users/mark/source/repos/zippydb.code-workspace
[09:10:15.681] ConfigFileWatcher: closing file:///c%3A/Users/mark/source/repos/zippydb.code-workspace

I have followed instructions on troubleshooting by changing settings for;
"remote.SSH.showLoginTerminal": true,
"remote.SSH.useLocalServer": false

I also edited my config, which had 4 entries down to 2 entries, and then also tried renaming config so the extension could create a new one.  Neither resulted in any change in behavior.

Host is Win x64, remotes are Ubuntu 18.04 (multipass/hyper-v). ssh to remotes works fine in bash.

SSH config; (actual user/key replaced here with #...#, but just plain ascii names )
Host primary.mshome.net
  HostName primary.mshome.net
  User #username#
  IdentityFile ~/.ssh/#keyfile#

Extension version: 0.51.0
VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor              (12 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.95GB (38.13GB free)|
|Process Argv|--file-uri file:///c%3A/Users/mark/source/repos/zippydb.code-workspace --crash-reporter-id 5a8f40f2-3042-4de0-a353-c9ac17e198b9|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by marklythgoe** [comment]
reverted to vscode 1.48 and retested, still fails.  appears to be extension issue, will create an extension bug

**Comment by chrmarti** [comment]
Did it work before? Do you know when it broke?

**Comment by marklythgoe** [comment]
Yes, it was working until today.  It would have intermittent issues, but a
vscode restart would usually fix the issue.  I tried using the nightly
build also, but same issues.  I have reverted to external git bash ssh
connections for now.  Let me know if there are any debugging flags for more
info or anything else you want me to try.

Thanks, Mark

**Comment by ahtamjidi** [comment]
Same issue here. It started showing up within the last 24 hours and perhaps after an update.

**Comment by roblourens** [comment]
Sorry, I'm not sure what's going on. Could you update the extension and try again?

**Comment by marklythgoe** [comment]
Hi Rob,
I have tried;
1. uninstall/install of Remote SSH extension and the Remote Development
extension pack.
2. using the nightly build version of the SSH extension

None of that worked.  Let me know if there is anything else I can try or
logs I can provide.

Thanks, Mark

**Comment by roblourens** [comment]
I suppose I need to figure out what `Unhandled rejection: undefined` is. I pushed an update that logs the error object directly and may have more info, would appreciate you letting me know if you see anything else there now.

**Comment by marklythgoe** [comment]
It appears not to be an extension issue.
1. I also get a similar error now on the REST Client extension that was
working until several days ago.  (undefined or null object error).  I have
completely reinstalled vscode, run win updates, reinstalled node... to no
avail.
2. I then did another test and opened an empty folder, and the extension
works.  It appears to be an issue with vscode and my workspace
folder/files, not the extension.

Mark

**Comment by marklythgoe** [comment]
One last update and I think the issue can be closed.  I removed the
extension cache in the 2 cache folders
AppData/Roaming/Code/CachedExtensions[VSIXs].  I then reinstalled the
remote SSH extension and disabled some Azure extensions.  The SSH extension
now works again.  Not quite sure if it was clearing the cache or disabling
other extensions, but definitely not an issue with your extension code.

Mark

**Comment by mrz1973** [comment]
Same here it has worked like a charm until today when I updated to 1.49.. 
Now it hangs on NFS 
Acquiring lock on /home/XXX/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/vscode-remote-lock.XXX.e790b931385d72cf5669fcefc51cdf65990efa5d

**Comment by zehuichen123** [comment]
Same issue, getting stuck here:
```
[16:25:55.953] > Acquiring lock on /ghome/chenzeh/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/vscode-remote-lock.chenzeh.e790b931385d72cf5669fcefc51cdf65990efa5d
```
I've tried to delete .vscode-server folder but it doesn't work.

**Comment by zehuichen123** [comment]
https://github.com/microsoft/vscode-remote-release/issues/2507#issuecomment-598962698
This one works for me!

**Comment by elagina** [comment]
The same issue here started on 09/15 (worked perfectly before). Getting stuck on:

Acquiring lock on ......
 
Adding **"remote.SSH.lockfilesInTmp": true** worked
