### ISSUE TITLE
devcontainer.json Compatible with Windows, OSX, Linux?

### ISSUE THREAD

**Issue by rdmolony** [microsoft/vscode-remote-release#3655]
Would it be possible to adapt the default `"dockerFile": "..\\Dockerfile"` `devcontainer.json` definition on Windows so that the `devcontainer.json` is compatible with Linux and OSX (where this path definition would be `"dockerFile": "../Dockerfile"`)?

It seems to be the only default that would be problematic on other OS out of:

```json
{
	"name": "Existing Dockerfile",
	"context": "..",
	"dockerFile": "..\\Dockerfile",
	"settings": {
		"terminal.integrated.shell.linux": null
	},
	"extensions": [
		"mhutchie.git-graph",
		"eamodio.gitlens",
		"ms-python.python"
	],
}
```

Thanks for creating and maintaining this incredible `VSCode` extension!  It has been incredibly useful in sharing dev environments across my team!

**Comment by Chuxel** [comment]
@chrmarti I know I've seen this issue before but can't find it in the issues list. Looks like on Windows the automated path used for an existing Dockerfile (and probably Docker Compose file) is using the OS path when it should always use the macOS/Linux path.

**Comment by chrmarti** [comment]
Related: #3350
