### ISSUE TITLE
"Files: Exclude" completely ignored

### ISSUE THREAD

**Issue by tomlobato** [microsoft/vscode-remote-release#3659]
- VSCode Version:  1.49.0
- Local OS Version: MacOS Catalina 10.15.3 
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Create/access a remote project, create the directory test_exclude at the root folder with 1 file having "xyz" inside
2. Add test_exclude/** to Files:Exclude configuration in Remote tab
3. Search (Ctrl+Shift+F) for xyz

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
Please check whether any of the tips here help: https://github.com/microsoft/vscode/wiki/Search-Issues
