### ISSUE TITLE
Poor error message when publickey not available

### ISSUE THREAD

**Issue by rossng** [microsoft/vscode-remote-release#3661]
- VSCode Version: 1.49.0
- Local OS Version: Windows 10 Pro 1909 18363.900
- Remote OS Version: Ubuntu 20.04.1
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Set up a local VirtualBox Ubuntu VM which uses key-based auth for SSH
2. Do not make the private key available for use on the host (in my case, forget to unlock KeePass, which I use as an SSH key agent)
3. Attempt to remote from VS Code on the host to the guest VM

You will see the following error: `Could not establish connection to <name>: The process tried to write to a nonexistent pipe.`

This error is very confusing and not useful for the user. OpenSSH, for example, would give this error instead:

> Permission denied (publickey).

which is much more useful IMO.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by bamurtaugh** [comment]
Tagged as feature request to improve the error message.

**Comment by roblourens** [comment]
We do try to parse this out but windows puts it out in a weird way that we miss

**Comment by tanhakabir** [comment]
I believe we've fixed this error in recent versions of the extension. We do prompt more relevant error messages if they exist rather than non-consistent pipe error. More info here: https://github.com/microsoft/vscode-remote-release/issues/5723
