### ISSUE TITLE
Can one connect to remote servers without /root/.vscode-remote/ ?

### ISSUE THREAD

**Issue by uhlhosting** [microsoft/vscode-remote-release#367]
🚨 The issue tracker is not for questions 🚨

If you have a question about VS Code, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code and about
VS Code Remote on https://stackoverflow.com/questions/tagged/vscode-remote.

I am testing t vscode-remote, and I am not sure why on every server i make a connection there are installed bunch of files and folders under /root/.vscode-remote/ . is this normal behaviour? Can one connect to server without these files installed?

And then the fun part is that some OSes such as Centos the remote login is not working.

In one side I see i am connected, the second side returns:

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/6324047/57975476-fce89880-79c9-11e9-8e7d-7dfffa04a1e5.png">

Thus by checking locally the server it has:
`**drwxr-xr-x   5 root root     4096 May 18 23:55 .vscode-remote**`

`Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.)`

Results from centos 6:

```
SSH Resolver called for "ssh-remote+cp"
SSH Resolver called for host: cp
Setting up SSH remote "cp"
Using commit id "6ac87465f297a9068bf767f45d6f372fc5697de9" and quality "insider" for server
Install and start server if needed
> bash: no job control in this shell
> bash: /tmp/tmp.rbKo8UWdOn/vscode-remote-install.6ac87465f297a9068bf767f45d6f372fc5697de9.sh: Permission denied
"install" terminal command done
Received install output: bash: /tmp/tmp.rbKo8UWdOn/vscode-remote-install.6ac87465f297a9068bf767f45d6f372fc5697de9.sh: Permission denied
Failed to parse remote port from server output: bash: /tmp/tmp.rbKo8UWdOn/vscode-remote-install.6ac87465f297a9068bf767f45d6f372fc5697de9.sh: Permission denied
```

**Comment by roblourens** [comment]
VS Code has to install a server on the remote machine that it connects to. This is what runs your remote extensions. The "unauthorized client" issue is being tracked here: https://github.com/microsoft/vscode-remote-release/issues/103
