### ISSUE TITLE
Error building devcontainers in Linux/ARM64 in WSL2

### ISSUE THREAD

**Issue by jamesthurley** [microsoft/vscode-remote-release#3672]
I'm unsure if this is the right place to report this, so apologies if I've got it wrong.

### Versions
- **Local OS Version:** Ubuntu 20.04 in WSL2 running on ARM64 (Surface Pro X)
- **Name of Dev Container Definition with Issue:** The following devcontainer samples:
  - `vscode-remote-try-dotnetcore`
  - `vscode-remote-try-node`
  - `vscode-remote-try-python`

The above are just the sample repos which I've tried so far. I've also tried it on my own repo which uses an anaconda devcontainer and get the same behavior.

### Issue Description
This issue is simplest to reproduce on the command line as shown below. However I get the same issue when trying to start the devcontainer in VSCode through the "Remote - WSL" with "Remote - Containers" extensions.

I'm running these commands on a Surface Pro X, with Ubuntu 20.04 running in WSL2, Docker and Git both installed in Ubuntu.

### Steps to Reproduce
1. Open a WSL prompt.
2. `git clone https://github.com/microsoft/vscode-remote-try-dotnetcore.git`
3. `cd vscode-remote-try-dotnetcore`
4. `cd .devcontainer`
5. `docker build .`

### Expected behavior
Container should build successfully.

### Actual Behaviour
`standard_init_linux.go:211: exec user process caused "exec format error"`

**Comment by Chuxel** [comment]
I am sadly lacking a device to try this on. @fiveisprime Do you have a Surface Pro X still?   

These definitions are not setup for ARM devices currently, but where it is failing really doesn't have anything x86_64 specific. It could be something else.

**Comment by chrmarti** [comment]
All binaries in that image are compiled for x86_64. The error indicates that it cannot run `/bin/sh` for that reason.

**Comment by lucashernangregori** [comment]
Try changing the Dockerfile to use arm64 images instead of x64 ones.
In line 3 change:

FROM mcr.microsoft.com/dotnet/core/sdk:${VARIANT}

to

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster-arm64v8

You can see the tags of the images provided by Microsoft on:
https://hub.docker.com/_/microsoft-dotnet-core-sdk/
https://hub.docker.com/_/microsoft-dotnet-core-aspnet/

I hope that helps

**Comment by chrmarti** [comment]
Wasn't aware we already have them. Thanks @lucashernangregori.

Closing.

**Comment by jamesthurley** [comment]
Thanks everyone, that makes sense that I'd need to change the base image on a case by case basis. 

The fact that everything from .NET to Node to Python devcontainers failed in the exact same way made me think there might be a common solution, but I see now that they were just all failing trying to execute `sh`.

Looking at the [docs](https://code.visualstudio.com/docs/remote/devcontainerjson-reference#_devcontainerjson-properties), I should be able to rig something up referencing an environment variable in the `build.args` section of the `devcontainer.json` to automatically select either the arm64 or x64 base image depending on which computer I open the project on.
