### ISSUE TITLE
Git untracked files only in devcontainer and not in local host

### ISSUE THREAD

**Issue by Norfeldt** [microsoft/vscode-remote-release#3674]
## Versions

- VSCode Version: 1.49.0 e790b931385d72cf5669fcefc51cdf65990efa5d x64
- Local OS Version: macOS Catalina 10.15.6
- Name of Dev Container Definition with Issue: "Existing Dockerfile" (`FROM python:3.8`)

## Issue description

When starting the devcontainer git sees a lot of files as untracked - which are tracked in the local host.

![Screen-Recording-2020-09-14-at-10 21 37](https://user-images.githubusercontent.com/678806/93062067-bade6e00-f674-11ea-9a46-ab001e6a5427.gif)

At first I thought it was a new line issue (which it was not). Then I thought it was something with special danish characters - after fixing that issue the git untracked files issue was still present. 

### Bonus info

Common for the untracked files is that they are "auto-generated". The `.html` files in the RAW directory are html pages downloaded by a scraper. The `.pkl` files are binary pickles made by the builtin python `pickle` lib. 

Tried having another dev (in another country) pulling down the branch and building the container. There was no issue with his git. 🤷‍♂️ don't understand why my devcontainer has to rebuild the git index when entering the container... 

## Steps to Reproduce

1.  `.dockerignore`

```
**/__pycache__
**/.classpath
**/.dockerignore
**/.env
**/.git
**/.gitignore
**/.project
**/.settings
**/.toolstarget
**/.vs
**/.vscode
**/*.*proj.user
**/*.dbmdl
**/*.jfm
**/azds.yaml
**/bin
**/charts
**/docker-compose*
**/Dockerfile*
**/node_modules
**/npm-debug.log
**/obj
**/secrets.dev.yaml
**/values.dev.yaml
.github/
.vscode/
PICKLES/
PROCESSED/
RAW/
chromedriver
README.md
```

2. `Dockerfile`

```
# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.8

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1

ADD .devcontainer/zsh-in-docker.sh .
RUN sh -c "$(cat zsh-in-docker.sh)"
ADD .devcontainer/.zshrc root
ADD .devcontainer/.p10k.zsh root

# Install pip requirements
ADD requirements.txt .
RUN python -m pip install -r requirements.txt

WORKDIR /app
ADD . /app

# RUN git config --global core.quotepath off
# RUN git config --global core.precomposeunicode true

ENTRYPOINT [ "/bin/zsh" ]
```

3. `.devcontainer/decontainer.json`

```
// For format details, see https://aka.ms/vscode-remote/devcontainer.json or this file's README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.134.1/containers/docker-existing-dockerfile
{
  "name": "Existing Dockerfile",
  // Sets the run context to one level up instead of the .devcontainer folder.
  "context": "..",
  // Update the 'dockerFile' property if you aren't using the standard 'Dockerfile' filename.
  "dockerFile": "../Dockerfile",
  // Set *default* container specific settings.json values on container create.
  "settings": {
    "terminal.integrated.shell.linux": "/bin/zsh"
  },
}
```

Do I need to share some of the untracked files via dropbox etc?

**Comment by Chuxel** [comment]
I'm not actually sure what might be happening there. Ever seen anything like this @chrmarti ?

**Comment by Norfeldt** [comment]
hmm... As mentioned I tried to clone the repo onto my desktop at it work fine (no untracked files in the docker container).

But when I remove the old repo in my dropbox folder and clone it back into this dropbox folder - the untracked files appears again (just 98 instead of 1526). So it seems like it might be a dropbox issue???

**Comment by chrmarti** [comment]
Maybe using dropbox to store the Git repository can explain the rebuilding of the index. Never tried that, but if there is more than one machine accessing the Git repository on dropbox, I'd imagine that could cause issues.

If the untracked files are covered by any `.gitignore` entries, but are still shown as untracked, that would also indicate an inconsistency in the Git repository.

**Comment by chrmarti** [comment]
Having the index on dropbox is probably the issue. Make sure you are using a 'bare' repository in dropbox and the clone that locally (non-dropbox): https://stackoverflow.com/questions/1960799/using-git-and-dropbox-together-effectively

Closing as question. Thanks.

**Comment by Norfeldt** [comment]
Thank you @chrmarti and @Chuxel for your time and points.
