### ISSUE TITLE
Unstable port forwarding / connection

### ISSUE THREAD

**Issue by dilsonnn** [microsoft/vscode-remote-release#3678]
Hey guys, I am developing on a secure corporate VM without administrator access, which I use to connect to a RHEL instance using vscode remote which I use to an angular application.

The remote ssh solution works great, however, from time to time it either disconnects or the port forwarding become unstable and I cant access my front-end application using localhost.

Under REMOTE SSH output, from time to time I see this message: 

"Failed to setup socket for dynamic port forward to remote port XXXX: Proxy connection timeout. is The remote port correct?"

- VSCode Version: **1.47.2**
- Local OS Version: Windows NT x64 6.1.7601
- Remote OS Version: Red Hat Enterprise Linux 7.7
- Remote Extension/Connection Type: SSH

**Steps to Reproduce:**

1. Open VS Code and connect remotely using SSH to the server using a private/public key.
2. Start 1-2 terminals and run some application.
3. Port forward all the required ports from the apps.
4. Remote SSH will work fine for a couple of minutes / hours and suddenly becomes unstable. Port forwarding will hang when accessing localhost. In Task manager you will see one or 2 ssh.exe processes  consuming 15-20% of local machine CPU and then it suddenly disconnects. 

Does anyone have an idea if that may be possible issue with vscode / extensions?

It would really helpful if you could shed some light with this possible issue.

**Updates 1 - 17.09.2020:**
Just an quick update. I have been the whole morning developing with remote vscode but using putty to port forwarding and haven't disconnect since.
**Updates 2- 18.09.2020:**
Putty port forwarding solved the instability issue, I have been developing for 2 days without any disconnect, so I would say my problem is somehow related to the built-in port forwarding.  

@alexjironkin
Best,

**Comment by roblourens** [comment]
> VSCode Version: 1.14.2

I'm guessing that this is not correct, can you check that you are using an official vscode build on the latest version?

**Comment by dilsonnn** [comment]
> > VSCode Version: 1.14.2
> 
> I'm guessing that this is not correct, can you check that you are using an official vscode build on the latest version?

Thanks for the heads up, yes it was wrong, the current version I am using is 1.47.2 and the HEAD commit is 17299e413d

**Comment by dilsonnn** [comment]
Feel free to close this.

I believe the root cause was the low space in the ~/ folder of my development virtual machine.

Right now we have like 20 people working with vscode remote without any complain about disconnects.

Best

**Comment by alexr00** [comment]
Thanks for closing @dilsonnn

**Comment by jync** [comment]
Hi... I have exactly this same issue and I'm wondering how best to troubleshoot this.

Running vs-code insiders edition - 1.53.0 - commit: 4d0d36c6ab154d841263c8d223a4bd1b9af07a23

Local dev: macOS Big Sur (11.1)
Remote VM: Linux version 5.4.0-1036-azure (buildd@lgw01-amd64-044) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #38~18.04.1-Ubuntu SMP Wed Jan 6 18:26:30 UTC 2021 (Ubuntu 5.4.0-1036.38~18.04.1-azure 5.4.78)

It was working well today. Then it just suddenly stopped working. At first the browser connection died (terminal curl was working). Then both stopped working.

I've tried restarting VS code (no change). I've tried restarting the VM (initially it works, then it stopped). Is there a way to troubleshoot this problem?

**Comment by dilsonnn** [comment]
> Hi... I have exactly this same issue and I'm wondering how best to troubleshoot this.
> 
> Running vs-code insiders edition - 1.53.0 - commit: 4d0d36c6ab154d841263c8d223a4bd1b9af07a23
> 
> Local dev: macOS Big Sur (11.1)
> Remote VM: Linux version 5.4.0-1036-azure (buildd@lgw01-amd64-044) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #38~18.04.1-Ubuntu SMP Wed Jan 6 18:26:30 UTC 2021 (Ubuntu 5.4.0-1036.38~18.04.1-azure 5.4.78)
> 
> It was working well today. Then it just suddenly stopped working. At first the browser connection died (terminal curl was working). Then both stopped working.
> 
> I've tried restarting VS code (no change). I've tried restarting the VM (initially it works, then it stopped). Is there a way to troubleshoot this problem?

Does the same problem happen when you port forward using putty?
