### ISSUE TITLE
virtual environment

### ISSUE THREAD

**Issue by siran** [microsoft/vscode-remote-release#368]
# Description
While using the Remote - WSL, the Python extension fails to activate the venv on new integrated terminals. 
Python Extension _does_ recognize the venv when debugging.

# Steps to reproduce
1. Open insiders from a WSL folder `code-insiders .`. The Remote - WSL is installed automatically.
2. Install Python extension on in insiders WSL.
3. Reload window
4. Open terminal, create a venv `python3.7 -m venv venv`
5. Select venv's python as the interpreter
6.  Select a python file
7. Close/open an integrated terminal
8. Venv is not automatically activated

# Expected results:
The command `. venv/bin/activate` should be automatically issued in the integrated terminal.

# Actual results
The venv is not automatically activated

**Comment by AngellusMortis** [comment]
> Close/open an integrated terminal

The integrated terminal does not automatically active a virtualenv. You need to use the `Python: Create Terminal` command from the Command Palette. And even then, it will only activate the virtualenv if `python.terminal.activateEnvironment` is set to true.

**Comment by siran** [comment]
Having `python.terminal.activateEnvironment`, using `Python: Create Terminal` is not activating the virtual environment when in `Remote - WSL`. In Windows native it does activate the virtual env.

**Comment by egamma** [comment]
//fyi @qubitron

**Comment by qubitron** [comment]
@luabud @donjayamanne can you take a look? Please copy this to the vscode-python repo if it is an extension issue.

**Comment by DonJayamanne** [comment]
> Venv is not automatically activated

This is an extension issue.

**Comment by siran** [comment]
Thanks for reclassifying!
