### ISSUE TITLE
can't start a terminal if the old cwd went away

### ISSUE THREAD

**Issue by mikelward** [microsoft/vscode-remote-release#3681]
- VSCode Version: 1.47.3
- Local OS Version: Linux
- Remote OS Version: Linux
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Start vscode
2. Remote SSH to your workstation
3. Make a new project directory
4. cd there and run `code .`
5. Close vscode
6. Delete the directory (e.g. you submitted/merged the code, and the project directory is no longer needed)
7. Run `code` (vscode tries to start when it left off)
8. Try to open a terminal (Ctrl+`)

Get an error dialog in the bottom right corner saying "The terminal process failed to launch (cwd) <the full path>".

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by roblourens** [comment]
So vscode has tried to open a folder that doesn't exist right? But you can still go open another folder right?

**Comment by oakad** [comment]
Terminal is generally very unreliable, no matter  other circumstances. #3320 is still a big issue.
