### ISSUE TITLE
got an error message saying "Terminal is dumb, but EDITOR unset" when commiting rebase conflicts 

### ISSUE THREAD

**Issue by NewtMa** [microsoft/vscode-remote-release#3682]
Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:20:50.359Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-47-generic

- Local OS Version: Ubuntu 20.04 LTS 5.4.0-47-generic (update to the latest)
- Remote OS Version: CentOS 7 3.10.0-1127.19.1.el7.x86_64 (update to the latest) on VMWare
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.ssh to the guest machine;
2. using `git rebase branch` and try to resolve conflicts in vscode, and when committing the changes, a window prompts and says "Terminal is dumb, but EDITOR unset", stackoverflow says this happens when you editing conflicts using editors other than vim but the env EDITOR is unset.

Does this issue occur when you try this locally?:  No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
I think you are expected to run `git rebase --continue` during a rebase, not commit, right?

**Comment by NewtMa** [comment]
@roblourens Sorry my English is poor. You're absolutely right. I used the "check" button in the source control tab whose help info said "Commit", and it prompted the error message.

![2020-09-17 09-21-51 的屏幕截图](https://user-images.githubusercontent.com/48610536/93408510-5830e080-f8c7-11ea-8304-f1539ba3a773.png)

**Comment by joaomoreno** [comment]
VS Code should automatically run `git rebase --continue` for you. Can you run `Git: Show Git Output` to see the log of git commands, and check what appears when you click the ✔️ action?

**Comment by brianmhunt** [comment]
I have just started getting this error and the Git output in VS Code looks like this when I click  ✔️:

```
> git rebase --continue
error: Terminal is dumb, but EDITOR unset
Please supply the message using either -m or -F option.
error: could not commit staged changes.
> git config --get-all user.name
> git config --get-all user.email
> git status -z -u
> git symbolic-ref --short HEAD
fatal: ref HEAD is not a symbolic ref
> git rev-parse HEAD
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 7d161f24c388caa67c91d080a2ccba19984c0fa3
> git ls-files --stage -- /Users/bmh/Repos/.../file-thats-edited
> git cat-file -s 41b9002df1fe4d244ff0e14545470119465e3985
> git show --textconv :file-thats-edited
```

_(slightly anonymized)_

**Comment by NewtMa** [comment]
@joaomoreno hi sorry for the delay. here is the git out put log:
```
> git rebase --continue
error: Terminal is dumb, but EDITOR unset
Please supply the message using either -m or -F option.
error: could not commit staged changes.
> git config --get-all user.name
> git config --get-all user.email
> git ls-files --stage -- /path/to /the/conflict/file.h
> git cat-file -s 58235d6725995c2c021ee44bdc755b545286e4f9
> git show --textconv :/path/to /the/conflict/file.h
> git status -z -u
> git symbolic-ref --short HEAD
fatal: ref HEAD is not a symbolic ref
> git rev-parse HEAD
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 12b0edd0bd1efa33c2563d2bbf2b3f695047ddb2
```

**Comment by kczx3** [comment]
I see the same thing...

**Comment by Kungitoo** [comment]
Same

**Comment by PabloRN** [comment]
Same here: So what should we do to continue. Commit by hand before rebase --continue?

**Comment by NewtMa** [comment]
@PabloRN current workaround is rebase the whole thing on your host machine

**Comment by atsikov** [comment]
Had the same while doing interactive rebase and editing one of the commits. After I tried to "Commit Staged (Amend)", the above error popped up.

**Comment by GDLMendonca** [comment]
Temporary Fix: Run `git rebase --continue` in the terminal

**Comment by yaroslavsadin** [comment]
Would that be fixed?

**Comment by jacksteamdev** [comment]
I'm getting this error, it appears that vscode is not passing the commit message!?

```
> git rebase --continue
error: Terminal is dumb, but EDITOR unset
Please supply the message using either -m or -F option.
error: could not commit staged changes.
```

**Comment by programmer04** [comment]
I got this error on version **1.53.2** too in the same situation as described by @atsikov

**Comment by bneijt** [comment]
I had two issues coming to this issue.

First, my `.gitconfig` stated that `vim` was my commit editor. So pushing the checkmark would have `git` open `vim` and that subprocess would happly hang under my vscode waiting for input (verify with something like `pstree`).

Removing that configuration got my git to state it had no editor configured and wanted to start `vi` (which I don't have) so it just errored out.

My current work-around is to start vscode in an environment where `EDITOR="code --wait"` so vscode will open itself as a subprocess to edit the commit message, then saving and closing that file will continue the process normally.
  
    export EDITOR="code --wait"
    code

Version: 1.54.2
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-12T19:27:39.374Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.7-arch1-1

**Comment by djoca** [comment]
Any update about this issue?

**Comment by clauderoy790** [comment]
I'm getting the same problem. It would be great if vs code could run the rebase for us.

**Comment by avinashsk5** [comment]
just run below command in terminal

`git rebase --continue`

after this press "i" from keyborad and then write :wq! 

then  run again 

`git push <branch Name>`

**Comment by akoskm** [comment]
@avinashsk5 that's exactly what we're trying to avoid here. I'd expect vs code to run this when I'm in the middle of a rebase.

**Comment by floriankilian** [comment]
It remains still the same.

I guess it is related to VSCode not giving the commit message argument. Maybe as you cannot edit the commit message in VSCode as it does not allow you to edit the commit message from the previous commit still in the message box.

Used the solution from here:
https://github.com/microsoft/vscode/issues/92628

at least now i can edit the commit message, manually exit the file & it will work. but only a prompt to ask me for the commit message would be 1000x times better.

**Comment by graycodes** [comment]
If you change your git editor to be vscode it stops the above error from happening and you don't need to use a separate terminal. 

```sh
git config --global core.editor "code --wait"
```

VSCode might still show a dialog for each commit but it works.

**Comment by Elliot128** [comment]
Is this going to get fixed? Kind of defeats the purpose of the `Git: Rebase Branch` feature in vscode since it's broken.

**Comment by cprcrack** [comment]
> ```shell
> git config --global core.editor "code --wait"
> ```

Be sure to first [install the `code` command in your PATH](https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line), otherwise this might completely break your VSCode workspace until you do.

**Comment by lszomoru** [comment]
Related to https://github.com/microsoft/vscode/issues/114461.
This issue has been fixed in today's Insiders release (2022-07-21) or later. 
Please give it a try and let me know if you are still experiencing this problem. Thank you!
