### ISSUE TITLE
Remote-Containers 'Existing Dockerfile' broken from 0.138.0

### ISSUE THREAD

**Issue by cameronkerrnz** [microsoft/vscode-remote-release#3683]
- VSCode Version: 1.49.0 (user setup)
- Local OS Version: Windows 10 Enterprise 19041
- Remote OS Version: n/a
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Create a new folder, open it in Code
2. Remote-Containers: Add Development Container Configuration Files ...
3. Show All...
4. Existing Dockerfile    (problem is specific to this one, all others I tested were fine)
5. Note that no .devcontainer folder was created as a result.

I can confirm that this is also broken in the Insiders edition with the latest (0.141.0) version of Remote-Containers.

Remote Containers version 0.136.0 was the last released version that worked; I've checked ('Install Another Version...'), and 0.138.0 was the released version where this broke. When I tried this with Remote Containers version 0.138.0, I get an error message

> Command 'Remote-Containers: Add Development Container Configuration Files...' resulted in an error (ENOENT: no such file or directory, open 'c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-containers-0.138.0\dist\node_modules\vscode-dev-containers\containers\docker-existing-dockerfile\.devcontainer\Dockerfile')

This is interesting because when I was 'Existing Dockerfile' earlier (which may have been 0.136.0) my experience was that it created .devcontainer/ and .devcontainer/devcontainer.json, but *not* .devcontainer/Dockerfile

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
The first options should offer 'Existing Dockerfile' when there is a Dockerfile in the project's main folder:
![image](https://user-images.githubusercontent.com/9205389/93568335-49fac700-f990-11ea-83e8-9e45663684d7.png)

The entry for 'Existing Dockerfile' after you chose 'Show All...' isn't expected to work at the moment (we shouldn't show it). We could fix that by letting you choose the Dockerfile to cover the case where the Dockerfile is in a subfolder.

**Comment by cameronkerrnz** [comment]
Ah, so now the 'Existing Dockerfile...' makes a little more sense to me, although in the behaviour of 0.136.0 (and presumably before) the resulting devcontainer.json references a (non-existant) Dockerfile inside .devcontainer/, which naturally doesn't exist at the time when you use 'Existing Dockerfile...'

It would be great if there was an option to 'Empty Dockerfile for this Dev Container', which would create .devcontainer/ with devcontainer.json *and* an empty, possibly commented, Dockerfile; possibly just containing the following to get someone started and fire their imagination.

```
#FROM ...
```

This would be very useful for people who are using Dev Containers but perhaps aren't expecting to have a useful template already available. In my case, I'm working with creating plugins for Logstash (see https://github.com/cameronkerrnz/logstash-plugin-dev/), and so was creating my own Dev Container image.

**Comment by chrmarti** [comment]
What would the benefit be if the Dockerfile and the devcontainer.json were (almost) empty?

**Comment by cameronkerrnz** [comment]
Discoverability; if people know how to use a Dockerfile, then they can easily get started. This is particularly true in situations where no-such template exists already. For example, I tend to base by containers on centos:8 because that's closer to what we would use as a production environment. Its also a natural way of starting FROM any random container image that you happen to have (eg. locally).

Cheers,
Cameron

**Comment by chrmarti** [comment]
Filtering these out for now (since it is about 'existing' Dockerfile/docker-compose.yml).
