### ISSUE TITLE
teminal can not connnect remote server, it stuck without any error，as follows

### ISSUE THREAD

**Issue by ccmin** [microsoft/vscode-remote-release#3685]
![remotessh](https://user-images.githubusercontent.com/20035453/93461077-c94bb480-f916-11ea-9e54-05702705242f.jpg)

**Comment by ccmin** [comment]
ccmin@192.168.1.196's password: 
e8c2e881e4ec: running
Acquiring lock on /home/ccmin/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/vscode-remote-lock.ccmin.e790b931385d72cf5669fcefc51cdf65990efa5d       
Found existing installation at /home/ccmin/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d...
Found running server...

*
* Reminder: You may only use this software with Visual Studio family products, 
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
*

Checking server status on port 43903 with wget
e8c2e881e4ec: start
sshAuthSock====
listeningOn==43903==
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====
tmpDir==/run/user/1000==
platform==linux==
e8c2e881e4ec: end

**Comment by roblourens** [comment]
If this is still an issue, please share the full log from the Remote-SSH output channel
