### ISSUE TITLE
Can't sideload this extension in the sources build

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-remote-release#3694]
When sideloading the extension in the [sources build](https://github.com/microsoft/vscode/wiki/How-to-Contribute#build-and-run) it doesn't seem to work.

I get this error:
`/mnt/c/Users/user/.vscode-oss-dev/extensions/ms-vscode-remote.remote-wsl-0.44.5/scripts/wslServer-dev.sh: not found`

I need to debug an issue that's arising from the WSL extension and im not sure how to proceed.
Original issue is here:
https://github.com/microsoft/vscode/issues/100427#issuecomment-694968315

**Comment by Chuxel** [comment]
@jasonwilliams The remote extensions only work with the VS Code distribution bits rather than OSS. @Tyriar - are there any other steps Jason can take?

**Comment by Tyriar** [comment]
No you cannot run WSL out of sources unfortunately.
