### ISSUE TITLE
Automatic close VScode on ArchLinux (Manjaro 20.0.1)

### ISSUE THREAD

**Issue by moacirandretti** [microsoft/vscode-remote-release#3695]
- VSCode Version: Version 1.49
- Local OS Version: Manjaro (20.0.1)

Operating System: Manjaro Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.73.0
Qt Version: 5.15.0
Kernel Version: 5.7.19-2-MANJARO
OS Type: 64-bit
Processors: 12 × AMD Ryzen 5 1600 Six-Core Processor
Memory: 7.8 GiB of RAM
Graphics Processor: GeForce GTX 1650/PCIe/SSE2

Hello guys!
I'm want to let you know all that I found some kind of bug with my fresh install of VScode 1.49 with my Manjaro 20.0.1.
The steps to reproduce the bug follow bellow:

Steps to Reproduce the bug:
1. Open VScode and click to "Open Folder" on the blue button located at the left sidebar
2. After click to "Opne Folder" the VScode automaticly close the window and do not send any message or error.

The same bug occurs when I press "ctrl + shift + p" and click on any menu of the command list.

Any good soul can help me with that? 😅 I need to run VSCode to code my projects soon as possible. 🚀🚀🚀

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by kprestel** [comment]
Same issue with me. Very similar setup. I have an older kernel though: `5.4.64-1-MANJARO`

**Comment by bamurtaugh** [comment]
Thanks for the info. Just to clarify, is this happening when you're using the Remote-SSH extension? Or is it that any time you are using VS Code and you select "Open Folder" (regardless of whether you're using Remote-SSH/connected to a remote host), VS Code closes?

**Comment by kid1995** [comment]
When i right clicked on a tab and choose close others, this happen too

**Comment by bamurtaugh** [comment]
@moacirandretti @kprestel Circling back to this issue, are folks still experiencing this problem? And is it when connecting to any remote host from a local Manjaro (20.0.1) OS?

**Comment by kprestel** [comment]
I am not experiencing the problem now. Not sure if it was the latest VSCode release or the manjaro update that did the trick.

**Comment by bamurtaugh** [comment]
Thanks for the update @kprestel. If folks experience this again, please feel free to let us know.
