### ISSUE TITLE
Parse "Match Host" from ssh config

### ISSUE THREAD

**Issue by kylrth** [microsoft/vscode-remote-release#37]
My `/home/user/.ssh/config` file looks like this:

```
Host static
    Hostname some.remote.site
    User kyle
    ControlMaster auto
    ControlPath  ~/.ssh/sockets/%r@%h-%p
    ControlPersist  600

Match Host home exec "nc -w 1 -z 192.168.X.X 22"
    Hostname 192.168.X.X
    User kylrth
    ControlMaster auto
    ControlPath  ~/.ssh/sockets/%r@%h-%p
    ControlPersist  600

Match Host home !exec "nc -w 1 -z 192.168.X.X 22"
    Hostname other.remote.site
    User kylrth
    ControlMaster auto
    ControlPath  ~/.ssh/sockets/%r@%h-%p
    ControlPersist  600
```

I have a computer at home where I do my work, and when I'm at home I'd like to log in with the local IP address. Outside my home network, I want to use a dynamic DNS site. As such, the configuration used when I run `ssh home` will depend on whether `192.168.X.X` is listening on port 22. When I run **Remote SSH: Connect to Host...**, the only configuration I see is `static`. I'd like to see `home` listed there.

**Comment by lars18th** [comment]
Hi,

Futhermore add support to connect through a Proxy (HTTP CONNECT and SOCKS4a) is a must have.

Thank you for this good add-on.

**Comment by roblourens** [comment]
This works if you type `home` into the Connect to Host popup right? But we should parse `Match Host ... ` entries and show those as well...

**Comment by kylrth** [comment]
Yes, it does work to type `home` in the popup.

**Comment by jarrah31** [comment]
+1

Except my config file looks like this:
```
Match exec "/Users/me/onsubnet --not 192.168.1." host docker
 ProxyJump exthost
 Hostname 192.168.1.10
 User user1
 Port 22
```

**Comment by jarrah31** [comment]
The easy fix/solution for this is to add another entry in .ssh/config that points to your Match entry. So, for my example above, the following works and shows up as an entry in Remote SSH:

```
Match exec "/Users/me/onsubnet --not 192.168.1." host docker
 ProxyJump exthost
 Hostname 192.168.1.10
 User user1
 Port 22

Host docker
 Hostname docker
```

**Comment by lramos15** [comment]
@eleanorjboyd How do you suggest verifying this should I just have a Match Host with `return 0` and one with `return 1` and that's suffice to see if the list is populated properly?

**Comment by eleanorjboyd** [comment]
@lramos15, yes that is perfect! Thanks
