### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Developermayank** [microsoft/vscode-remote-release#370]
Issue Type: <b>Bug</b>

mesg: ttyname failed: Inappropriate ioctl for device
[2019-05-19 04:58:00.839] Remote configuration data at /root/.vscode-remote

Extension version: 0.36.0
VS Code version: Code - Insiders 1.35.0-insider (6ac87465f297a9068bf767f45d6f372fc5697de9, 2019-05-17T17:48:07.036Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.4.0-17134-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (1.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17134-Microsoft|
|CPUs|        Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3300)|
|Memory (System)|3.90GB (1.17GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
That message is ok, it's not an error.

Can you tell me exactly what you are trying to do, and what goes wrong?
