### ISSUE TITLE
VS Code Remote: Containers gets denied by selinux

### ISSUE THREAD

**Issue by Yamboy1** [microsoft/vscode-remote-release#3700]
- VSCode Version: 1.50.0-insider
- Local OS Version: Fedora 32
- Remote OS Version: N/A
- Remote Extension/Connection Type: Docker (Actually Podman, but that shoudn't matter)

Steps to Reproduce:

1. Make sure SELinux is enabled and set to "Enforcing"
2. Use the "Open Folder in Container" feature.
3. You shouldn't see any files in the file view, and running an `ls` command in the terminal will give a permission denied.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

This appears to be because an executable from inside the container is trying to access files outside the container, which is blocked.
![Screenshot from 2020-09-20 19-17-37](https://user-images.githubusercontent.com/37413895/93708260-e7205000-fb88-11ea-9620-be9ba6da9b5a.png)

**Comment by chrmarti** [comment]
"Open Folder in Container" mounts the folder into the container. For that to work you need to allow the container to access that local folder I guess.
