### ISSUE TITLE
SSH connection to non-internet connected linux remote will not succeed

### ISSUE THREAD

**Issue by surlyjake** [microsoft/vscode-remote-release#3705]
- VSCode Version: 1.46.1 (user setup)
- Local OS Version: win10.0.18362
- Remote OS Version: Ubuntu Linux 18.04
- Remote Extension/Connection Type: SSH. "Remote - SSH Extension version 0.55.0", "Remote Development version 0.20.0"

Steps to Reproduce:

1. set remote.ssh.allow local server Download : true
2. Connect to Ubuntu remote with no internet access.
3. select 'linux' as the platform of remote host.
4. enter password
5. output will report 
```

downloading with wget
wget download failed
wget: unable to resolve host address 'update.code.visualstudio.com'
```

It seems that the allow local server download option is ignored, as the linux remote still attempts to download a file from visualstudio.com

**Comment by roblourens** [comment]
If this is still an issue, please include the full Remote-SSH output channel log
