### ISSUE TITLE
Allow customizing vscode-server ports

### ISSUE THREAD

**Issue by marius311** [microsoft/vscode-remote-release#3706]
This is a feature request / question. I'm using a remote cluster where port forwarding is disabled administratively by a firewall, however, I can _reverse_ tunnel fine. By this I mean, 

```sh
mylaptop$ ssh -L 1234:localhost:1234 cluster # blocked by firewall
cluster$ ssh -R 1234:localhost:1234 mylaptop # works correctly
```

Using remote-ssh, if I try to connect to this cluster, the initial SSH connection to spawn the server runs fine, but the secondary connection to set up the port forwarding fails, as expected given the above firewall. However, if I could just reverse forward the ports by hand, then I believe it could work. What I need are to figure out what ports are chosen, or set them by hand. 

I've figured out that remote-ssh launches the server with `--port 0`, and I can figure out which emphemral port was chosen by looking in `~/.vscode-server/*.log`, which prints the port. However, I can't figure out what port was chosen on the local side.

A question I have is whether there exists a way I can figure out the local port? If not, my feature request is that 1) there be some way I could figure it out or 2) even better, I could just specify fixed local and remote ports by hand. 

Would be very happy if there are other suggestions for how to deal with this setup. Thanks. 

Some info: vscode 1.49.0, remote-ssh 0.55.0, remote OS Scientific Linux release 7.4, local OS Ubuntu 20.04.

**Comment by gyzerok** [comment]
This issue looks like a duplicate for https://github.com/microsoft/vscode-remote-release/issues/1386.

I would suggest to close this one and upvote the one I mentioned. Hopefully more upvotes will result in sooner fix than more issues.

**Comment by marius311** [comment]
Yep, I think its a dup, thanks. Will close and comment there.
