### ISSUE TITLE
Reconnection to disconnected session fails

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode-remote-release#3707]
When I am disconnected to a remote session, I am unable to reconnect. I attempt to "Connect current window to host", but it raises the following error:

Command 'Remote-SSH: Connect Current Window to Host...' resulted in an error (command 'opensshremotes.openEmptyWindowInCurrentWindow' not found)

I have to close VSCode entirely and restart to connect to remote hosts again.

- VSCode Version: Version: 1.49.1
- Local OS Version: Debian (Linux x64 5.4.48-06434-gd868196d13af)
- Remote OS Version: Ubuntu 16.04
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1. Run remote session
2. Wait for disconnection
3. Attempt to reconnect using  "Connect current window to host"

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by fonnesbeck** [comment]
Perhaps associated with this is the fact that disconnections are a frequent occurrence with long-running (>20 min) sessions. The connectivity issue is related to the extension, and not the network connection itself, as I always have a separate ssh connection active for interacting with the server outside of VSCode, and this session never gets dropped. I simply get a popup that says "Cannot reconnect. Please reload the window". Reloading the window results in the issue above.

**Comment by fonnesbeck** [comment]
I've tried this from multiple machines now, and the same thing occurs every time. I will eventually get an unrecoverable disconnection if I run a session long enough (20-60 min usually sufficient). 

I am using the Python extension primarily on the remote machine, if that is useful information.

**Comment by roblourens** [comment]
I can't repro this, where do you run that command from?

Guessing that if you run that from a new empty window instead of the disconnected remote window, it will work

**Comment by fonnesbeck** [comment]
I've tried it from both the Linux and Windows clients. Yes, it does connect from a new window, but does not reconnect to the same running Python, which is a problem because all the work in that session is lost.

**Comment by roblourens** [comment]
By "where" I meant where in the UI do run that command from (it's in multiple buttons/locations).

And actually, only this month did we release a change to reconnect to your terminal sessions when reconnecting.

**Comment by fonnesbeck** [comment]
I see, sorry. I try to reconnect either by clicking the bottom left corner of the app, where it shows the connection status, or calling up the command with ctrl-P. Neither approach works. 

Regarding the timing, it was happening back in September, which prompted me to open the issue, and then seemed to get less frequent but during the past week or so happens all the time. Im confident that it is not related to the quality of my network connection, though perhaps it's related to AWS, from which my remote connection originates(?).

**Comment by roblourens** [comment]
Ok. I still can't repro it but you should be able to work around it by reloading the window instead, going through "open recent", or "close remote connection"
