### ISSUE TITLE
Forwards ports section not revealed when remote explorer is showing another remote target

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#3709]
- open the remote explorer
- switch to the Codespaces section in the drop down
- start a server which emits the port to the terminal so that it can be scrapped, e.g., `npm start` in  "https://github.com/microsoft/vscode-remote-try-node"
- In the notification that shows that a port has been detected and forwarded 
![image](https://user-images.githubusercontent.com/172399/93856243-01594b80-fcb9-11ea-9387-23fa339a9408.png)
- Select 'Show Tunnels View'
- The view is not shown since the remote container is not switched to the Forwarded Ports view.

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode/commit/615de7379ccc7eb227b5b81d8582003ff94281f9
