### ISSUE TITLE
'Show Tunnels View' -> 'Show Forwarded Ports'

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#3710]
Suggest to rename 'Show Tunnels View' to 'Show Forwarded Ports' to align better with the UI. 
![image](https://user-images.githubusercontent.com/172399/93856385-3fef0600-fcb9-11ea-8fa7-a731ed79bbdf.png)

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode/commit/615de7379ccc7eb227b5b81d8582003ff94281f9
