### ISSUE TITLE
Consider Agent Forwarding to be disabled by default

### ISSUE THREAD

**Issue by W4RH4WK** [microsoft/vscode-remote-release#3711]
- VSCode Version: 1.49.1
- Local OS Version: Windows 10 1909
- Remote OS Version: -
- Remote Extension/Connection Type: SSH

I just noticed that the option `Enable Agent Forwarding` is enabled by default. Some people have noted that agent forwarding can lead to security issues ([1], [2]). Consider having agent forwarding disabled by default.

[1]: https://www.commandprompt.com/blog/security_considerations_while_using_ssh-agent/
[2]: https://heipei.io/2015/02/26/SSH-Agent-Forwarding-considered-harmful/

**Comment by W4RH4WK** [comment]
@bamurtaugh Please excuse me for objecting, but I wouldn't label this as *feature request* since the underlying feature is already there.

I'd like the maintainers to look at this topic from a security point of view and decide whether the default configuration is okay as it is, or should be changed. I advice against having this issue closed automatically by a bot (no offense @vscode-triage-bot).

**Comment by roblourens** [comment]
You still need `ForwardAgent` set in your ssh config for this to work. The setting is just to allow the extension to copy the SSH_AUTH_SOCK from the ssh shell process into your vscode environment.
