### ISSUE TITLE
Not able to load local container definition repository: remote.containers.repositoryConfigurationPaths

### ISSUE THREAD

**Issue by NikiforovAll** [microsoft/vscode-remote-release#3712]
Version: 1.49.1 (system setup)
OS: Windows_NT x64 10.0.19041

- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Clone https://github.com/microsoft/vscode-dev-containers/tree/master/repository-containers
2. Specify `remote.containers.repositoryConfigurationPaths`:
```json
"remote.containers.repositoryConfigurationPaths": [
    "C:/Nikiforov/dev/vscode-dev-containers/repository-containers",
]
```
3. Run the command: "Remote Containers: Open folder in Container"

As result, I don't see files that I'd expect to see when I set this setting on. 

I'm wondering what URL/paths are supported. Can I include git repo to fetch my definitions? Based on what criteria container definitions are added?

**Comment by NikiforovAll** [comment]
Ultimately, I would like to have my container definition on GitHub, something like: https://github.com/NikiforovAll/dev-containers

**Comment by NikiforovAll** [comment]
Ref: #3218

**Comment by chrmarti** [comment]
Which folder are you opening in the container? Does that folder have a Git repository? (It is the Git repository of the folder you are opening in a container that determines which of the configurations in your `repositoryConfigurationPaths` is picked.)

**Comment by NikiforovAll** [comment]
Here is what I've done:

1.  Clone https://github.com/Microsoft/vscode-dev-containers. (Also, I can see the git repository there)
2.  Add path configuration, C:\Nikiforov\dev\vscode-dev-containers\repository-containers\. 
3. Open folder located on my windows machine 'C:\Nikiforov\dev\devconatiners-test2\' 
4. Run `remote-containers.createDevContainerFile` in vscode

Expected container definitions are not displayed.

**Comment by chrmarti** [comment]
These configuration paths work differently: If the local folder ('C:\Nikiforov\dev\devconatiners-test2') is a Git repository matching a configuration (based on its path) in the path you configured, that configuration will be used to open the folder in a container when you trigger `Reopen in Container`.

**Comment by NikiforovAll** [comment]
I'm sorry, but I don't get it. 

>  If the local folder ('C:\Nikiforov\dev\devconatiners-test2') is a Git repository matching a configuration (based on its path) in the path you configured

In my case, it is not a git repository matching a configuration. _devconatiners-test2_, but rather, it is a folder that I want to open in a container defined locally in 'C:\Nikiforov\dev\vscode-dev-containers\repository-containers'. So I've added C:\Nikiforov\dev\vscode-dev-containers\repository-containers to configuration. 

Could you please provide an example?

**Comment by chrmarti** [comment]
We check which Git repository `C:\Nikiforov\dev\devconatiners-test2` is cloned from, e.g. `https://github.com/NikiforovAll/devconatiners-test2`. And then lookup the configuration based on that, e.g., `${repositoryConfigurationPath}/github.com/NikiforovAll/devconatiners-test2` for each of the configured repositoryConfigurationPaths (and also for a built-in one that has all the configurations from https://github.com/microsoft/vscode-dev-containers/tree/master/repository-containers).

**Comment by twodrops** [comment]
Nice feature. Would have been more useful if `remote.containers.repositoryConfigurationPaths` supported remote paths and not just local paths. 
It wasn't quite clear that `remote.containers.repositoryConfigurationPaths` supports only local paths until I read [this](https://github.com/microsoft/vscode-docs/blob/master/remote-release-notes/v1_47.md#configurable-repository-configuration-paths). 
Where can I contribute a patch to the documentation of `remote.containers.repositoryConfigurationPaths`?

**Comment by chrmarti** [comment]
Documentation is here: https://github.com/microsoft/vscode-docs

Thanks!
