### ISSUE TITLE
Naming of cloned dev containers

### ISSUE THREAD

**Issue by KenxinKun** [microsoft/vscode-remote-release#3717]
When cloning a git repo into a dev container, the naming of the generated containers is not picking up with subgroups in Gitlab. In my case, my repos live in a group "common" within the subgroup "lessons-learnt-services", under which there's different repos that I'm trying to open in separate dev containers. As you can see in the screenshot, the containers are named after the "lessons-learnt-services" subgroup, plus a hash, instead of the actual {repo-name}.git, "repo-name", which makes it confusing when trying to reopen them. The current workaround is to inspect the container in the extension and check the original git URL, to make sure the correct one is being opened.

Note that the same name is used in the local devcontainer /workspace/{repo-name} which again adds to the potential confusion.
![Capture](https://user-images.githubusercontent.com/16479107/94017213-12808600-fda7-11ea-9a98-4f489c6efbad.PNG)

Is it possible to fix the automatic naming or instead allow the user to type the name?

**Comment by egamma** [comment]
Now that there is support for rich hovers we can show the full repository name in the hover
![Uploading image.png…]()

**Comment by KenxinKun** [comment]
Thanks Erich, I don't think I can see the PNG you copied in though, it seems to link back the issue URL :o

**Comment by egamma** [comment]
@KenxinKun fixed the image, sry.

**Comment by KenxinKun** [comment]
Indeed, those hover snips would really help!

**Comment by cortex93** [comment]
Same goes for the backing volume name

**Comment by egamma** [comment]
Rich hovers are now in place for both containers and volumes.
