### ISSUE TITLE
"justMyCode": true" isn't not workig - VSCode Remote debugger session tries to open library code which isn't found 

### ISSUE THREAD

**Issue by musamaanjum** [microsoft/vscode-remote-release#3727]
- VSCode Version: 1.49.1
- Local OS Version: Windows 10 19041
- Remote OS Version: Ubuntu 20.04.1
- Remote Extension/Connection Type: WSL

Steps to Reproduce:
1. Start a VS Code session and build hello world sample using printf.
2. Launch the debug session and "Step Into" the printf function. Following error will appear and you'll be unable to move further until you press "Step Out":
Unable to open 'printf.c': Unable to read file 'vscode-remote://wsl+ubuntu-20.04/build/glibc-ZN95T4/glibc-2.31/stdio-common/printf.c' (Error: Unable to resolve non-existing file 'vscode-remote://wsl+ubuntu-20.04/build/glibc-ZN95T4/glibc-2.31/stdio-common/printf.c').

I've tried adding the "justMyCode": true" in `launch.json`, but the debugger still acts weird on the library code and tries to find source code (which isn't present). Then gives the same error (mentioned above) that unable to open etc.

I just want to don't jump into the library code. Is there a way to do this?

**Comment by Chuxel** [comment]
@musamaanjum This likely is an issue with an extension. Could you raise the issue with the extension you're using to debug? (e.g. the C++ extension)
