### ISSUE TITLE
Extreme Performance Issues

### ISSUE THREAD

**Issue by LJNeon** [microsoft/vscode-remote-release#3728]
- VSCode Version: 1.49.2
- Local OS Version: Windows 10 (x64)
- Remote OS Version: Ubuntu 20.04.1
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Attempt to connect remotely.
2. Initial connection will succeed, however it will cause CPU and memory to both jump up to 100% (CPU normally at under 1%, memory normally at 60%). Large volumes of disk reads (800 MB/s) will also occur.
3. Local VSCode will often lose connection and struggle to reconnect, presumably because remote server is overwhelmed.
4. Closing the local VSCode program or leaving it to run for hours does not solve resource usage, only rebooting the remote server appears to solve the problem (until local VSCode attempts to connect next).

Does this issue occur when you try this locally?: No
Does this issue occur when you try this **remotely** and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Are you opening a large workspace? Are you able to watch resource usage while this is happening to see exactly which process is using high cpu/memory? Likely that it's either the file watcher or the ts/js language server

**Comment by LJNeon** [comment]
Yea I would say the workspace is large, but I'm not sure how to see exactly which process is responsible.

**Comment by LJNeon** [comment]
Although I feel like I should clarify, my entire workspace is much less than 800MB, so it's surprising that I'm seeing that volume of reads at any given time.

**Comment by LJNeon** [comment]
Further testing shows that the performance issues only occur once a file is opened, not simply from connecting remotely. I always had files open previously, so connecting would automatically open a file as well.

**Comment by millettmb** [comment]
Having the same issue here. Seemed to be working fine about a week ago, but now it pegs my server CPU at 100% whenever I open VSCode, until I reboot the server. Workspace I'm opening isn't particularly large really. 

Using an SSH config with .pem keys (AWS instance).

Remote server will refuse any additional SSH connections after opening VSCode, and I suspect this may be sending it into a loop of trying to reconnect.

**Comment by LJNeon** [comment]
After looking into it more, I suspect VSCode just uses a lot of memory and that's why my memory is maxed, but my CPU usage varies wildly from 1 CPU core to 2 CPU cores (far bigger difference than double cores could explain) so I suspect VSCode is poorly designed in that regard and can't handle a 1 core VPS that well. I still have no clue on the hours of nonstop 800MB/s reads when my entire project is less than 800MB.

**Comment by millettmb** [comment]
Could it be that the disk usage is due to swap space usage? 

My setup is 1 vCPU and 1GB RAM, so not necessarily the beefiest system to be working on, but I'm just confused as to why it could work fine last week.

**Comment by Chuxel** [comment]
@LJNeon VS Code is actually running extensions, indexing, and many other options on the remote machine in order to provide the full experience. That's what makes the experience so full featured, but it means that it requires more resources than just connecting via a file share. Generally speaking, 2-core 2GB is needed to get a good experience, but it is highly project dependant. For this class of setup, you'll likely want to explore using something like rsync or sshfs.

**Comment by millettmb** [comment]
@Chuxel thanks for the recommendation of sshfs, appears to be much better than VSCode remote

**Comment by LJNeon** [comment]
So overall, VSCode just has high resource usage. Thanks for the help!
