### ISSUE TITLE
Can't connect to ssh remote only with ssh key rsa (scaleway)

### ISSUE THREAD

**Issue by darkterra** [microsoft/vscode-remote-release#373]
Issue Type: <b>Bug</b>

Hello,

I'm on Windows 10, with Visual Studio Code - Insiders just install.
I would like try and test the Remote - SSH extension, to use this extension, I Pay on an cloud provider (Scaleway) an litle linux server.
The only contraint is to connect with only the ssh key (rsa) and no password, because the root user has no password and the server never accept to connect with root and password.

So there is my log on my server (logged with putty and ssh key) :

```
root@Blog-DT:~# tail -f /var/log/auth.log | grep xx.xxx.xx.xx
May 19 12:00:50 Blog-DT sshd[22286]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=xx.xxx.xx.xx  user=root
May 19 12:00:53 Blog-DT sshd[22286]: Failed password for root from xx.xxx.xx.xx port 59652 ssh2
May 19 12:01:11 Blog-DT sshd[22286]: Failed password for root from xx.xxx.xx.xx port 59652 ssh2
May 19 12:01:15 Blog-DT sshd[22286]: Failed password for root from xx.xxx.xx.xx port 59652 ssh2
May 19 12:01:16 Blog-DT sshd[22286]: Connection reset by xx.xxx.xx.xx port 59652 [preauth]
May 19 12:01:16 Blog-DT sshd[22286]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=xx.xxx.xx.xx  user=root
```

xx.xxx.xx.xx is my IP adress where I try to connect on the remote server.

Some one know how to force VS code to use only the passphrase of the ssh key (or nothing if no passphrase is configured for the ssh key) ?

It does not matter if I enter a correct or incorrect passphrase, I always have the password of the requested root account

Extension version: 0.37.0
VS Code version: Code - Insiders 1.35.0-insider (6ac87465f297a9068bf767f45d6f372fc5697de9, 2019-05-17T17:48:07.036Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by AngellusMortis** [comment]
Use the `Remote-SSH: Open Configuration File...` command from the Command Palette and it will open your SSH Config file. You can specify the IP of your remote server as well of the location of your private key.  [Here is an article](https://www.cyberciti.biz/faq/create-ssh-config-file-on-linux-unix/) that talks more about it.

If you want VS Code to not prompt you for passphrase at all, you need to set up a SSH Agent. [Here is the official Microsoft docs](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement) talking about doing SSH on Windows 10.

**Comment by roblourens** [comment]
Thanks @AngellusMortis, yes your key will need to be specified in the ssh config file, or in the ssh agent. Does that help?

**Comment by darkterra** [comment]
Thank @AngellusMortis and @roblourens for your answere.

There is my ssh config file:
```
Host Blog_Scaleway
    HostName 873abce8-8d18-43d0-95ae-17f01c6b439a.pub.cloud.scaleway.com
    User root
    IdentityFile ~/.ssh/id_rsa
    IdentitiesOnly true
```

I trie with and without `IdentitiesOnly true`

Maybe I made a mistake ont the ssh config file, but I think it's ok.

When I look the status of my ssh agent with `Get-Service ssh-agent` the status is **Stopped**.
But I can't start the service without an error `Impossible to start the ssh-agent service on this computer'.'`

Are you shure I need to use an ssh-agent outside of VS Code ?
VS Code "remote development" or "remote-ssh" dosen't have embeded ssh-agent ?

**Comment by roblourens** [comment]
How do you usually ssh to the server? Does `ssh Blog_Scaleway` work without needing a password?

**Comment by darkterra** [comment]
Yes

**Comment by roblourens** [comment]
Do you have to enter a passphrase for the key when you do that? Not sure what's going on, can you share the log from the "Remote - SSH" output channel?

Also does it help if you set `remote.SSH.showLoginTerminal`?

More details: https://code.visualstudio.com/docs/remote/troubleshooting#_enabling-alternate-ssh-authentication-methods

**Comment by darkterra** [comment]
Yes, when I create the rsa key, I add an passphrase.

Shure ! There is the "Remote - SSH" output channel:
![image](https://user-images.githubusercontent.com/7060696/58134056-eb9bc800-7c25-11e9-8b4d-cb4790a1a63b.png)

**Comment by roblourens** [comment]
Ok, so I understand that you can do `ssh Blog_Scaleway` without a passphrase or a password, but when you use vscode, it is missing both. I see that you are using a putty key, there are some extra steps you will need since it isn't supported by OpenSSH. Details here: https://code.visualstudio.com/docs/remote/troubleshooting#_reusing-a-key-generated-in-puttygen
