### ISSUE TITLE
When attaching to remote container automatically install extensions.

### ISSUE THREAD

**Issue by ylilarry** [microsoft/vscode-remote-release#3732]
Currently, extensions are only automatically installed when you use the open in container command, but not when you attach to a running container. My workflow requires me to attach to an arbitrary container and install extensions listed in devcontainer.json, which are required to develop in that container. Is it possible to also automatically install extensions listed in devcontainer.json when attaching?

**Comment by ylilarry** [comment]
To give more context, the reason for my workflow is that I need to launch the container by running a bash script, which sets some environment variables required by docker-compose.yml (those ${VAR:?err} substitutions). I see no way to do this with the open in container command, because devcontainer.json does not provide a way to run custom command to launch the container.

**Comment by chrmarti** [comment]
You can add an array of extension ids to the 'attach' configuration (`"extensions"` property). Use `F1` > `Remote-Containers: Open Attached Container Configuration File...` to open that. Note that for each container extensions will be installed only the first time you attach to it, changes to `"extensions"` in the config file after that will only apply to the next container with the same image name (or container name, if the config is scoped to that).

Does that solve the issue for you?
