### ISSUE TITLE
Cant use sudo to edit files

### ISSUE THREAD

**Issue by CalSmith1** [microsoft/vscode-remote-release#3733]
Issue Type: <b>Bug</b>

When I remote login to linux server, I need to use sudo to edit files for applications. Cant navigate out of my home directory to do this, although terminal lets me do naything I need to. Any way to sync terminal user to editor user?

Extension version: 0.55.0
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:23:33.049Z)
OS version: Linux x64 4.19.0-8-amd64
Remote OS version: Linux x64 3.10.0-1127.19.1.el7.x86_64

**Comment by Chuxel** [comment]
Duplicate of #1688
