### ISSUE TITLE
DOES NOT SHOW CHANGES IN VSCODE

### ISSUE THREAD

**Issue by ernesto-15** [microsoft/vscode-remote-release#3735]
Issue Type: <b>Bug</b>

Can´t see any changes in the Source Control while making changes and cant see changes in the workspace while creating and removing folders or files.

Extension version: 0.44.5
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (3.99GB free)|
|Process Argv|--crash-reporter-id be943b15-3d5c-431d-9e45-98815d6f67be|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2807)|
|Memory (System)|12.38GB (8.84GB free)|
|VM|0%|
</details>

**Comment by windxrz** [comment]
Same issue

**Comment by ernesto-15** [comment]
It seems that the synchronization between Windows files in VSCode remote in WSL does not work properly. I started using VSCode remote just with my Linux files and I have not had any problems until now.

**Comment by aeschli** [comment]
Are you on a mounted folder (`/mnt/c/...`)?

**Comment by ernesto-15** [comment]
Yes, the error only happens when I am on those folders, but when I work on the Linux folders everything goes well.

**Comment by aeschli** [comment]
dup of #3959
