### ISSUE TITLE
The same devcontainer.json cannot be shared by a second Mac Pro

### ISSUE THREAD

**Issue by Celthi** [microsoft/vscode-remote-release#3736]
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:23:52.277Z (1 day ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Have a remote docker host.
2. Create one .devcontainer.json and use the remote host as the docker host by adding the following into the setting.json
  { "docker.host": ''ssh://root@ip"}

3. I can successfully launch the folder in the remote container in my old Mac. (the old Mac's vscode is with version 1.48)
4. Switch a new Mac, and try to open the same folder (the same path, the same .devcontainer.json, and settings.json) but fail.

The error I see is:
```
9176 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.postCreateCommandMarker' ; } 2> /dev/null
[9195 ms] 
[9196 ms] 
[9196 ms] Exit code 1
[9196 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink -f /proc/$pid/cwd ; xargs -0 < /proc/$pid/environ ; xargs -0 < /proc/$pid/cmdline ; } ; echo ; done 2>/dev/null
[9255 ms] Start: Run in container: /root/.vscode-server/bin/e5e9e69aed6e1984f7499b7af85b3d05f9a6883a/server.sh --disable-user-env-probe --port 0 --extensions-download-dir /root/.vscode-server/extensionsCache
[9988 ms] Remote-Containers server: error during connect: Get http://docker/v1.40/containers/fa56461fba80c1f8b6ce9010e7f837d48f340f35a1b4bda395d071472e2b2804/json: command [ssh -l root -- 1.23.10.239 docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=kex_exchange_identification: read: Connection reset by peer
[9995 ms] Error: stream ended with:0 but wanted:9
        at p (/Users/xialu/.vscode/extensions/ms-vscode-remote.remote-containers-0.140.1/dist/extension.js:1:215920)
        at /Users/xialu/.vscode/extensions/ms-vscode-remote.remote-containers-0.140.1/dist/extension.js:1:216090
        at s (/Users/xialu/.vscode/extensions/ms-vscode-remote.remote-containers-0.140.1/dist/extension.js:1:231407)
        at Socket.<anonymous> (/Users/xialu/.vscode/extensions/ms-vscode-remote.remote-containers-0.140.1/dist/extension.js:1:231580)
        at Socket.emit (events.js:228:7)
        at endReadableNT (_stream_readable.js:1185:12)
        at processTicksAndRejections (internal/process/task_queues.js:81:21)

<!-- Check to see if the problem is general, with a specific extension, or only happens when remote -->
Does this issue occur when you try this locally?: I don't understand this question.
Does this issue occur when you try this locally and all extensions are disabled?:Is this possible to do as the extension is required to run open folder inside a container?

**Comment by Celthi** [comment]
I guess the root cause is related to that my new Mac has a newer version OpenSSH than the remote host.
My new mac has ssh with a version:
[15:29]:ssh -V
OpenSSH_8.1p1, LibreSSL 2.7.3
But the remote host is with version:
ssh -V
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017

Somehow the connection will be reset.

**Comment by chrmarti** [comment]
Also check the versions of Docker you have installed, the error message says Docker 18.09 or later is required.

**Comment by Celthi** [comment]
> Also check the versions of Docker you have installed, the error message says Docker 18.09 or later is required.
The docker version is 

[root@tec-l-014576 ~]# docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:03:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:02:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by chrmarti** [comment]
Is that also the version on the remote Docker host?

**Comment by Celthi** [comment]
> Is that also the version on the remote Docker host?

The above is the version in the remote Docker host.
My local docker host In the old  Mac is:
[8:58]:docker version 
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

The new Mac is:



Now I meet the same error in both Mac books.

**Comment by chrmarti** [comment]
Have you tried upgrading SSH client and server to the latest versions? `kex_exchange_identification` seems to be an SSH error while the connection is still being set up. Looking more closely this should not be related to Docker.

**Comment by Celthi** [comment]
> Have you tried upgrading SSH client and server to the latest versions? `kex_exchange_identification` seems to be an SSH error while the connection is still being set up. Looking more closely this should not be related to Docker.

I didn't try the upgrade for SSH as they are 7.9 and 8.1 which is quite new as the newest version is 8.4.
It is quite strange that some commands are successfully run. And all errors are failing at `Get http://docker/v1.40/containers/fa56461fba80c1f8b6ce9010e7f837d48f340f35a1b4bda395d071472e2b2804/json: command [ssh -l root -- 1.23.10.239 docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=kex_exchange_identification: read: Connection reset by peer`
If it is related to SSH, then I would expect something that more random instead of failing at the same point of the commands

**Comment by Celthi** [comment]
> Does `ssh -l root -- 1.23.10.239 docker system dial-stdio` work when you run it from the command line yourself?

Nope. It will block and no response is coming out.

**Comment by chrmarti** [comment]
I think that is expected with that command. Any chance there is a firewall between the two machines? (We had a recent report on that: https://github.com/microsoft/vscode-remote-release/issues/3673#issuecomment-694750363).

**Comment by chrmarti** [comment]
Also marking as upstream since this appears to be an issue outside of VS Code and Remote-Containers.

**Comment by Celthi** [comment]
> Also marking as upstream since this appears to be an issue outside of VS Code and Remote-Containers.

Thanks for promptly looking into this. I'll try to see if it is related to the firewall. By the way, do you know the full command the following error is executing? I would like to execute it manually to see if it can be run. I tried to look into the source code of "Remote-Container" but I couldn't find it.

```
[9988 ms] Remote-Containers server: error during connect: Get http://docker/v1.40/containers/fa56461fba80c1f8b6ce9010e7f837d48f340f35a1b4bda395d071472e2b2804/json: command [ssh -l root -- 1.23.10.239 docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=kex_exchange_identification: read: Connection reset by peer
```

**Comment by chrmarti** [comment]
That looks like `docker inspect --type container fa56461fba80c1f8b6ce9010e7f837d48f340f35a1b4bda395d071472e2b2804`. 👍

**Comment by Celthi** [comment]
workbench.desktop.main.js:formatted:13205 [Extension Host] (node:43342) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ workbench.desktop.main.js:formatted:13184
$logExtensionHostMessage @ workbench.desktop.main.js:formatted:179795
_doInvokeHandler @ workbench.desktop.main.js:formatted:180060
_invokeHandler @ workbench.desktop.main.js:formatted:180060
_receiveRequest @ workbench.desktop.main.js:formatted:179976
_receiveOneMessage @ workbench.desktop.main.js:formatted:179928
(anonymous) @ workbench.desktop.main.js:formatted:179864
fire @ workbench.desktop.main.js:formatted:4138
fire @ workbench.desktop.main.js:formatted:21838
_receiveMessage @ workbench.desktop.main.js:formatted:22035
(anonymous) @ workbench.desktop.main.js:formatted:21939
fire @ workbench.desktop.main.js:formatted:4138
acceptChunk @ workbench.desktop.main.js:formatted:21682
(anonymous) @ workbench.desktop.main.js:formatted:21641
t @ workbench.desktop.main.js:formatted:22068
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
workbench.desktop.main.js:formatted:13205 [Extension Host] rejected promise not handled within 1 second: Error: spawn gpgconf ENOENT
t.log @ workbench.desktop.main.js:formatted:13184
$logExtensionHostMessage @ workbench.desktop.main.js:formatted:179795
_doInvokeHandler @ workbench.desktop.main.js:formatted:180060
_invokeHandler @ workbench.desktop.main.js:formatted:180060
_receiveRequest @ workbench.desktop.main.js:formatted:179976
_receiveOneMessage @ workbench.desktop.main.js:formatted:179928
(anonymous) @ workbench.desktop.main.js:formatted:179864
fire @ workbench.desktop.main.js:formatted:4138
fire @ workbench.desktop.main.js:formatted:21838
_receiveMessage @ workbench.desktop.main.js:formatted:22035
(anonymous) @ workbench.desktop.main.js:formatted:21939
fire @ workbench.desktop.main.js:formatted:4138
acceptChunk @ workbench.desktop.main.js:formatted:21682
(anonymous) @ workbench.desktop.main.js:formatted:21641
t @ workbench.desktop.main.js:formatted:22068
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
workbench.desktop.main.js:formatted:13205 [Extension Host] stack trace: Error: spawn gpgconf ENOENT	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)	at onErrorNT (internal/child_process.js:456:16)	at processTicksAndRejections (internal/process/task_queues.js:81:21)
t.log @ workbench.desktop.main.js:formatted:13184
$logExtensionHostMessage @ workbench.desktop.main.js:formatted:179795
_doInvokeHandler @ workbench.desktop.main.js:formatted:180060
_invokeHandler @ workbench.desktop.main.js:formatted:180060
_receiveRequest @ workbench.desktop.main.js:formatted:179976
_receiveOneMessage @ workbench.desktop.main.js:formatted:179928
(anonymous) @ workbench.desktop.main.js:formatted:179864
fire @ workbench.desktop.main.js:formatted:4138
fire @ workbench.desktop.main.js:formatted:21838
_receiveMessage @ workbench.desktop.main.js:formatted:22035
(anonymous) @ workbench.desktop.main.js:formatted:21939
fire @ workbench.desktop.main.js:formatted:4138
acceptChunk @ workbench.desktop.main.js:formatted:21682
(anonymous) @ workbench.desktop.main.js:formatted:21641
t @ workbench.desktop.main.js:formatted:22068
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
workbench.desktop.main.js:formatted:72532   ERR spawn gpgconf ENOENT: Error: spawn gpgconf ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)
workbench.desktop.main.js:formatted:13205 [Extension Host] Error: Unexpected SIGPIPE	at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap.js:5:284)	at process.emit (events.js:223:5)
t.log @ workbench.desktop.main.js:formatted:13184
$logExtensionHostMessage @ workbench.desktop.main.js:formatted:179795
_doInvokeHandler @ workbench.desktop.main.js:formatted:180060
_invokeHandler @ workbench.desktop.main.js:formatted:180060
_receiveRequest @ workbench.desktop.main.js:formatted:179976
_receiveOneMessage @ workbench.desktop.main.js:formatted:179928
(anonymous) @ workbench.desktop.main.js:formatted:179864
fire @ workbench.desktop.main.js:formatted:4138
fire @ workbench.desktop.main.js:formatted:21838
_receiveMessage @ workbench.desktop.main.js:formatted:22035
(anonymous) @ workbench.desktop.main.js:formatted:21939
fire @ workbench.desktop.main.js:formatted:4138
acceptChunk @ workbench.desktop.main.js:formatted:21682
(anonymous) @ workbench.desktop.main.js:formatted:21641
t @ workbench.desktop.main.js:formatted:22068
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
workbench.desktop.main.js:formatted:205969 Error
    at e.resolveAuthority (workbench.desktop.main.js:formatted:180594)
    at async W._scanAndHandleExtensions (workbench.desktop.main.js:formatted:205967)
    at async W._initialize (workbench.desktop.main.js:formatted:180745)
workbench.desktop.main.js:formatted:205970 Error handled: Not showing a notification for the error
workbench.desktop.main.js:formatted:180441 Error received from starting extension host
(anonymous) @ workbench.desktop.main.js:formatted:180441
Promise.then (async)
e @ workbench.desktop.main.js:formatted:180407
_createInstance @ workbench.desktop.main.js:formatted:71694
createInstance @ workbench.desktop.main.js:formatted:71694
(anonymous) @ workbench.desktop.main.js:formatted:180744
_startExtensionHosts @ workbench.desktop.main.js:formatted:180744
_initialize @ workbench.desktop.main.js:formatted:180722
(anonymous) @ workbench.desktop.main.js:formatted:205704
requestIdleCallback (async)
t.runWhenIdle @ workbench.desktop.main.js:formatted:6006
(anonymous) @ workbench.desktop.main.js:formatted:205704
Promise.then (async)
W @ workbench.desktop.main.js:formatted:205704
_createInstance @ workbench.desktop.main.js:formatted:71694
_createServiceInstance @ workbench.desktop.main.js:formatted:71769
_createServiceInstanceWithOwner @ workbench.desktop.main.js:formatted:71769
_createAndCacheServiceInstance @ workbench.desktop.main.js:formatted:71726
_getOrCreateServiceInstance @ workbench.desktop.main.js:formatted:71726
get @ workbench.desktop.main.js:formatted:71641
initLayout @ workbench.desktop.main.js:formatted:258396
(anonymous) @ workbench.desktop.main.js:formatted:259674
invokeFunction @ workbench.desktop.main.js:formatted:71641
startup @ workbench.desktop.main.js:formatted:259674
open @ workbench.desktop.main.js:formatted:298581
async function (async)
open @ workbench.desktop.main.js:formatted:298560
t.main @ workbench.desktop.main.js:formatted:298683
(anonymous) @ workbench.js:167
async function (async)
(anonymous) @ workbench.js:167
(anonymous) @ bootstrap-window.js:93
t._invokeFactory @ loader.js:1135
t.complete @ loader.js:1135
s._onModuleComplete @ loader.js:1712
s._onModuleComplete @ loader.js:1712
s._resolve @ loader.js:1647
s.defineModule @ loader.js:1284
r @ loader.js:1712
c @ loader.js:795
(anonymous) @ workbench.desktop.main.js:formatted:299386
(anonymous) @ workbench.desktop.main.js:formatted:299386
t._createAndEvalScript @ loader.js:795
(anonymous) @ loader.js:795
u @ loader.js:904
(anonymous) @ loader.js:904
readFileAfterClose @ internal/fs/read_file_context.js:61
workbench.desktop.main.js:formatted:180442 Error
    at e.resolveAuthority (workbench.desktop.main.js:formatted:180594)
    at async W._scanAndHandleExtensions (workbench.desktop.main.js:formatted:205967)
    at async W._initialize (workbench.desktop.main.js:formatted:180745)
(anonymous) @ workbench.desktop.main.js:formatted:180441
Promise.then (async)
e @ workbench.desktop.main.js:formatted:180407
_createInstance @ workbench.desktop.main.js:formatted:71694
createInstance @ workbench.desktop.main.js:formatted:71694
(anonymous) @ workbench.desktop.main.js:formatted:180744
_startExtensionHosts @ workbench.desktop.main.js:formatted:180744
_initialize @ workbench.desktop.main.js:formatted:180722
(anonymous) @ workbench.desktop.main.js:formatted:205704
requestIdleCallback (async)
t.runWhenIdle @ workbench.desktop.main.js:formatted:6006
(anonymous) @ workbench.desktop.main.js:formatted:205704
Promise.then (async)
W @ workbench.desktop.main.js:formatted:205704
_createInstance @ workbench.desktop.main.js:formatted:71694
_createServiceInstance @ workbench.desktop.main.js:formatted:71769
_createServiceInstanceWithOwner @ workbench.desktop.main.js:formatted:71769
_createAndCacheServiceInstance @ workbench.desktop.main.js:formatted:71726
_getOrCreateServiceInstance @ workbench.desktop.main.js:formatted:71726
get @ workbench.desktop.main.js:formatted:71641
initLayout @ workbench.desktop.main.js:formatted:258396
(anonymous) @ workbench.desktop.main.js:formatted:259674
invokeFunction @ workbench.desktop.main.js:formatted:71641
startup @ workbench.desktop.main.js:formatted:259674
open @ workbench.desktop.main.js:formatted:298581
async function (async)
open @ workbench.desktop.main.js:formatted:298560
t.main @ workbench.desktop.main.js:formatted:298683
(anonymous) @ workbench.js:167
async function (async)
(anonymous) @ workbench.js:167
(anonymous) @ bootstrap-window.js:93
t._invokeFactory @ loader.js:1135
t.complete @ loader.js:1135
s._onModuleComplete @ loader.js:1712
s._onModuleComplete @ loader.js:1712
s._resolve @ loader.js:1647
s.defineModule @ loader.js:1284
r @ loader.js:1712
c @ loader.js:795
(anonymous) @ workbench.desktop.main.js:formatted:299386
(anonymous) @ workbench.desktop.main.js:formatted:299386
t._createAndEvalScript @ loader.js:795
(anonymous) @ loader.js:795
u @ loader.js:904
(anonymous) @ loader.js:904
readFileAfterClose @ internal/fs/read_file_context.js:61
workbench.desktop.main.js:formatted:72532   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
workbench.desktop.main.js:formatted:72532   ERR Error
    at e.resolveAuthority (workbench.desktop.main.js:formatted:180594)
    at async W._scanAndHandleExtensions (workbench.desktop.main.js:formatted:205967)
    at async W._initialize (workbench.desktop.main.js:formatted:180745)
DevTools failed to load SourceMap: Could not load content for file:///Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js.map: 
workbench.desktop.main.js:formatted:72532   ERR Unable to read file 'vscode-remote://dev-container+7b22686f737450617468223a222f55736572732f7869616c752f446f63756d656e74732f7365727665725f6465765f6275696c645f5041222c2273657474696e6773223a7b22686f7374223a227373683a2f2f726f6f744031302e32332e31302e323339227d7d/var/lib/jenkins/Projects/microstrategy/Tech/.vscode/settings.json' (Error): Error: Unable to read file 'vscode-remote://dev-container+7b22686f737450617468223a222f55736572732f7869616c752f446f63756d656e74732f7365727665725f6465765f6275696c645f5041222c2273657474696e6773223a7b22686f7374223a227373683a2f2f726f6f744031302e32332e31302e323339227d7d/var/lib/jenkins/Projects/microstrategy/Tech/.vscode/settings.json' (Error)
    at b.doReadAsFileStream (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1730:591)
    at async b.readFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1729:715)
    at async file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3764:8
    at async Promise.all (index 0)
    at async Promise.all (index 0)

**Comment by chrmarti** [comment]
@Celthi Is this still an issue?

**Comment by Celthi** [comment]
Close it as not reproducible anymore.
