### ISSUE TITLE
Overriding SSH executable doesn't override

### ISSUE THREAD

**Issue by cinderblock** [microsoft/vscode-remote-release#3737]
I'm trying to connect to a remote linux host using plink since I use pageant. I've set `remote.SSH.path` to `"C:\Program Files\PuTTY\plink.exe"` but `Code.exe` still runs `ssh.exe`, confirmed by Process Explorer.

**Comment by roblourens** [comment]
Putty is not supported https://code.visualstudio.com/docs/remote/ssh#_remote-ssh-limitations

**Comment by cinderblock** [comment]
Are there any plans to support PuTTY? It seems to be the defacto standard ssh client on Windows.

What is the point of the `remote.SSH.path` option if not to use a different ssh client?
