### ISSUE TITLE
Open VSCode SSH session from terminal

### ISSUE THREAD

**Issue by kingces95** [microsoft/vscode-remote-release#3738]
Given a `~/.ssh/config` of
```
Host myRemote
  HostName myHost.com
  User myUser
```
I'd like to issue the following from the terminal
> $ code --ssh myRemote ~/git/myRepo

and have VSCode an initiate a remote connection to `myUser@myHost.com`, and open the remote folder `~/git/myRepo`.

**Comment by Chuxel** [comment]
You can do this as follows: `code --folder-uri "vscode-remote://ssh-remote+remote_server_goes_here/folder/on/remote/host/here`
