### ISSUE TITLE
Breaks Gcloud/EC2 instance completely, can't even ping it and both consoles say everything is fine

### ISSUE THREAD

**Issue by jermerf** [microsoft/vscode-remote-release#3739]
- VSCode Version: 1.49.2
- Local OS Version: Windows 10 19241.508
- Remote OS Version: Ubuntu 20.04 lts and others
- Remote Extension/Connection Type: SSH

This has happened three times now over the past few months and I gotta say, this is pretty destructive. Literally in middle of typing in a document this time, it loses connection and that's it. Everything on the instance is gone.

Is it gone? I don't know. Can't ping the instance. AWS console says it's fine, nothing wrong. When this happened with gcloud a while back it was the same thing. Tried rebooting, stopping and starting, waiting for a few days hoping. All my work is gone.

Completely different projects, I just have no clue.

I completely lose contact with the instance and I have no way of restoring it and I can't tell you any more. VScode just loses connection and the instance is a total zombie.

Steps to Reproduce:

1. Use it for a while? Like I said in the middle of typing something.

**Comment by roblourens** [comment]
Sorry for the trouble. Is this a low-powered instance? Might just be overwhelming RAM/cpu
