### ISSUE TITLE
Default Remote Container Python example fails when debugging

### ISSUE THREAD

**Issue by XabiBeltza** [microsoft/vscode-remote-release#374]
Issue Type: <b>Bug</b>

- Followed the steps on: https://code.visualstudio.com/docs/remote/containers#_quick-start-try-a-dev-container
- Used Python git example
- Reach step 5 without trouble. I can run commands on Linux container and Intellisense works.
- However, when pressing F5 an error pops saying: Cannot read property 'trim' of null, and suggests opening launch.json. I can't figure out that anything is wrong.

Extension version: 0.53.0
VS Code version: Code - Insiders 1.35.0-insider (6ac87465f297a9068bf767f45d6f372fc5697de9, 2019-05-17T17:48:07.036Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.9.125-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Python Sample|
|OS|Linux x64 4.9.125-linuxkit|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (2 x 2468)|
|Memory (System)|1.93GB (0.11GB free)|
|VM|0%|
</details>

**Comment by antonioj-mattos** [comment]
I had the same issue. Fixed after switching back to `bash`.

For reference https://github.com/microsoft/vscode-remote-release/issues/350#issuecomment-493619458

**Comment by roblourens** [comment]
Also tracked in https://github.com/microsoft/vscode/issues/73867
