### ISSUE TITLE
Use SSH that exists in Bash or other environments

### ISSUE THREAD

**Issue by fxzxmic** [microsoft/vscode-remote-release#3741]
For example, connect to a remote server using SSH in a WSL environment, or use Git SSH.
Git SSH already exists: "`C:\Program Files\Git\usr\bin\ssh.exe`", but you can also use this method: "`Bash.exe -c "ssh <command>"`".
So, can you add this usage and use `%V` instead of `<command>`? Such as "`Bash.exe -c "ssh %V"`".

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/937
