### ISSUE TITLE
Test: Improve the dev container innerloop when cloning a repository into a container volume

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#3743]
Refs #3664 

- [x] anyOS @chrmarti 
- [ ] anyOS @Chuxel 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%233743%0A%0A)

---

- Run `Remote Containers: Clone a repository into a container volume` with a repository that fails to build the container. For example, https://github.com/egamma/vscode-remote-try-node has an incorrect reference to the base docker image in its dockerfile
- When the build of the container fails select 'Reopen in Recovery Container'
- Validate that the devcontainer.json opens
  - test with a `devcontainer.json` in `.devcontainer` and a `.devcontainer.json` at the workspace root.
- Validate that if the creation log opens (it doesn't have to), it opens on the side or behind the `devcontainer.json`. (These are the two experiments we are running.)
- Validate that there is a notification that guides users how to get out of the recovery container
- Validate that this notification can be disabled
- Fix the issue and validate that either 'Reopen in Container' or 'Rebuild Container' rebuilds and reopens the container

**Comment by chrmarti** [comment]
Note that the creation log only opens if your machine happens to be in the experiment group. I'll update the description.

**Comment by bpasero** [comment]
testing is good, closing
