### ISSUE TITLE
Option to have single VSCode Windows for WSL and Local

### ISSUE THREAD

**Issue by swinder0161** [microsoft/vscode-remote-release#3744]
I was wondering, is it possible to have an option that:

1) when WSL session is open already, any file opened from windows using double click also goes to same VSCode windows instead of opening another VSCode local.
VSCode WSL remote session already has support for open local files.

2) When VSCode local windows is open and a new file is opened with command line from WSL like $ code .bashrc. It should open in the already open local vscode window.

3) Option to copy local path of the file when open in remote wsl mode.
for WSL opened file, right click should have option "Copy Path Local" along side "Copy Path" and "Copy Path Relative"

Just want to avoid 2 VSCode windows open at the same time.

**Comment by swinder0161** [comment]
@aeschli Any update for open remote in local?

**Comment by aeschli** [comment]
Sorry, we have currently no plans to support the suggested features.

**Comment by jcrben** [comment]
For those looking for something like this, https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs (https://github.com/SchoofsKelvin/vscode-sshfs) supports mixed local and remote

**Comment by aeschli** [comment]
Closing as out of scope.
