### ISSUE TITLE
Document extensionsCache usage

### ISSUE THREAD

**Issue by rubensa** [microsoft/vscode-remote-release#3746]
Please, provide documentation about this "new" (now not that new really) **extensionsCache** folder purpose and usage scenario.

Looks like instructions linked in https://github.com/microsoft/vscode-remote-release/issues/3052 for setting a devcontainer are in a private repository (not visible for externals).

As far as I guess this folder is for caching extension packages so they must not be downloaded multiple times if they has already been downloaded.

But:

- Can this folder be shared among multiple devcontainers (mounting the volume) with different extensions in **devcontainer.json**?
- I this folder used to cache extensions directly downloaded from the internet or the extensions are downloaded in client vscode and then sent to this folder in the vscode-server?
- How does all this extension download, share, cache really works?

**Comment by rubensa** [comment]
Related info:

- [Avoiding extension reinstalls on container rebuild](https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild)
- [Docker: Extensions are always downloaded again](https://github.com/microsoft/vscode-remote-release/issues/2227)
- [the remote extension installed in Docker containers can be cached](https://github.com/microsoft/vscode-remote-release/issues/185)
- [Test: Extensions are cached](https://github.com/microsoft/vscode-remote-release/issues/3052)

**Comment by chrmarti** [comment]
- Sharing this folder among containers is not guaranteed to always work (it often might).
- There is a similar cache on the host filesystem, we copy extensions from that to the container, additional extensions and newer versions might the be downloaded from inside the container.

**Comment by rubensa** [comment]
Thanks @chrmarti 

- What's that "similar cache on the host filesystem"?  Is **~/.config/Code/CachedExtensionVSIXs** folder?
- I think that **.vscode-server/extensionsCache** is an **vsix** extensions cache folder (similar to **maven** or **npm** cache) but with the "problem" that old extension versions are removed (problem if you share this folder with multiple projects using different extension versions) and without access control (I ended with some corrupted extensions I had to manually remove to make them work again -this could be for concurrent access/modification or for some network problem downloading extensions, not sure-).  Am I right here?
