### ISSUE TITLE
Search in files does not work

### ISSUE THREAD

**Issue by daniol** [microsoft/vscode-remote-release#3747]
Issue Type: <b>Bug</b>

When connected to a remote workspace over **SSH**, the VS search function only finds results on the currently opened files; it shows the "loading progress" but never completes and does not return any other search results.

I would expect that this function executes a grep (or similar command) on the remote system and returns the results.

Remote: SSH (Linux)

Extension version: 0.55.0
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.15.0-38-generic

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/108102
