### ISSUE TITLE
Remote Docker version not detected correctly

### ISSUE THREAD

**Issue by chemelli74** [microsoft/vscode-remote-release#3748]
- VSCode Version:  **1.49.2 (user setup)**
- OS Version:          **Microsoft Windows [Versione 10.0.18363.1082]**

Steps to Reproduce:

1. Install Remote contaner extension
2. Configure docker.host
3. Run `Remote-Containers: Attach to running Conteiner...`
4. Below message is shown on screen:

![image](https://user-images.githubusercontent.com/57354320/94462640-1ef84a80-01bc-11eb-9fed-9f90dad76595.png)

Host is above minimum requirement:

```
admin@home:/$ docker --version
Docker version 18.09.8, build bfed4f5

```

Windows client is running Docker Desktop:

![image](https://user-images.githubusercontent.com/57354320/94463025-a219a080-01bc-11eb-89f3-9d3d9bfca006.png)

Simone

**Comment by chemelli74** [comment]
Found something in the log:

```
[2020-09-28T16:56:11.491Z] [PID 25704] [1167716 ms] Start: Run: docker version --format {{.Server.Version}}
[2020-09-28T16:56:13.888Z] [PID 25704] [1170113 ms] error during connect: Get http://docker/v1.40/version: command [ssh -l my-login  -p 5022 -- my-host-name docker system dial-stdio] has exited with exit status 127, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=sh: docker: command not found
```

but if I ssh and then run `docker`,  command is in path.
Anyway for a raw test I added the path manually:

`C:\>ssh -l my-login -p 5022 -- my-host-name  /usr/local/bin/docker system dial-stdio`

but command never exist.
Running for example:

`C:\>ssh -l my-login -p 5022 -- my-host-name  /usr/local/bin/docker system info`

works perfectly.

Simone

**Comment by chrmarti** [comment]
What did you set `docker.host` to? And does `ssh -l my-login -p 5022 -- my-host-name docker version` (i.e., without the path) work?

**Comment by chemelli74** [comment]
> What did you set `docker.host` to? 

`"docker.host": "ssh://my-login@my-host-name:5022",`

> And does `ssh -l my-login -p 5022 -- my-host-name docker version` (i.e., without the path) work?

Nope; 
I bet ssh doesn't exec user profile somehow; but putty does.
Will add to PATH to /etc/profile and retest.

Simone

**Comment by chemelli74** [comment]
> > And does `ssh -l my-login -p 5022 -- my-host-name docker version` (i.e., without the path) work?
> 
> Nope;
> I bet ssh doesn't exec user profile somehow; but putty does.
> Will add to PATH to /etc/profile and retest.
> 

/usr/local/bin is already in /etc/profile PATH on the remote.
But checking with `ssh -l my-login -p 5022 -- my-host-name set` is not there.
Cannot understand why, but as a quick&dirty solution I did a `ln-s` of docker to /usr/bin

Now I can connect successfully with VScode to my remote container.

I think we can close this issue.
 
Simone

**Comment by chrmarti** [comment]
I think `ssh` might indeed not run any shell startup scripts when run with a command to execute. Thanks.
