### ISSUE TITLE
Debug f5 sunddenly slow for asking parameters

### ISSUE THREAD

**Issue by spicotmex** [microsoft/vscode-remote-release#375]
Issue Type: <b>Performance Issue</b>

* When open remote pwsh script with some mandatory parameters and press F5, 
** Terminal ask for value.  When typing it can take 20 - 30 s to show it in terminal (==> At the first terminal line, not where you are typing (at the end) ????)

* When process start running, every thing is fine, 

* It's look like VS CODE Terminal problem rather than remote server or connectivity ......
** Using bash is fine.
** Edit script with intellisense is fine...
** I don't know when (update ?, another extension,....) suddenly. became slow, specifically when you hit F5 for debug with mandatory parameters. (approximately 1 min for 3 parameters... :( ) 
** I have already uninstall VS CODE, uninstall vs-code server in host....

Extension version: 0.37.0
VS Code version: Code - Insiders 1.35.0-insider (6ac87465f297a9068bf767f45d6f372fc5697de9, 2019-05-17T17:48:07.036Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.15.0-50-generic

**Comment by spicotmex** [comment]
Launching current file w/Arg prompt work fine.... I'll use this rather than waiting for Terminal prompt... :)

**Comment by Tyriar** [comment]
Seems related to pwsh issue in https://github.com/microsoft/vscode-remote-release/issues/356
