### ISSUE TITLE
Test: inherit environment from process where `code .` is executed

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#3751]
Refs: #1700

- [x] Windows @misolori
- [x] Windows @bpasero

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%233751%0A%0A)

---

The remote WSL window now inherits environment from the WSL shell where `code .` is executed.

- open a WSL shell (e.g. Ubuntu from the Windows start menu)
- run `FOO=BAR code-insiders .`
- The remote window that opens should have FOO set (and all variables from the env from that shell)

Test
- test that this also works for multiple windows open at the same time, started from different shells
- test that when opening a remote WSL window from the remote indicator, no environment is inherited
- test for different distros (Alpine, Fedora)

**Comment by bpasero** [comment]
I was only able to test ubuntu.

**Comment by bpasero** [comment]
And Alpine as well 👍

**Comment by misolori** [comment]
Tested on both Ubuntu and Debian
