### ISSUE TITLE
Files changed outside not listing in "Changes" in "Source control" in WSL

### ISSUE THREAD

**Issue by yousufctec** [microsoft/vscode-remote-release#3754]
Issue Type: <b>Bug</b>

Sql and few other files were changed outside the  editor Visual Studio Code. Those files were not listed on the changes in source control part of the git. But when I open the folder in VS Code outside WSL, it worked. Opening again WSL after that worked.

Extension version: 0.44.5
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 2950X 16-Core Processor  (32 x 3493)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.88GB (36.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|15%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|AMD Ryzen Threadripper 2950X 16-Core Processor  (32 x 3500)|
|Memory (System)|63.88GB (36.77GB free)|
|VM|15%|
</details>

**Comment by PavelSosin-320** [comment]
git listens for filesystem changes. Git running in Windows listens to Windows filesystem changes. Git running inside Linux WSL listens to Linux filesystem changes. They are 2 decoupled filesystems connected via P9 protocol. In other words, This is WSL issue first. I don't think that such a case is supported by P9. 
The same is true for NodeJS: NodeJS filesystem listener running in Windows will listen to Windows local filesystem events. NodeJS filesystem listener running in Linux will listen to Linux local filesystem events.  
The full set of filesystem events notifications is defined in LSP spec. I believe that also implementation can be found in the GitHub elsewhere,

**Comment by aeschli** [comment]
dup of #3959
