### ISSUE TITLE
Recovery Container: Extension recommendation notification

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#3756]
#3743

Remote-Containers 0.143.0

After opening the recovery container I got a notification about extension recommendations which doesn't make sense in a recovery container. I think we could disable recommendations in the machine settings of the recovery container which we can control from the recovery container's devcontainer.json. /cc @sandy081 to confirm my observation.

**Comment by sandy081** [comment]
What recommendations are you seeing?

**Comment by chrmarti** [comment]
@sandy081 Not sure:
![image](https://user-images.githubusercontent.com/9205389/94575952-16177f80-0275-11eb-9a25-dc9800c9a5ae.png)

Clicking on 'Show' opens the extensions viewlet with `@recommended` showing workspace and other recommendations. So I guess this is triggered by the workspace recommendations.

**Comment by sandy081** [comment]
These are the extensions from repository (`.vscode/extensions.json`). I agree that this does not makes sense in recovery container. We can use the setting `extensions.ignoreRecommendations` and set it to `true` in remote container settings.
