### ISSUE TITLE
Recovery Container: Double-quotes in notification text

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#3757]
Testing #3743

I think we rarely use double-quotes:

![image](https://user-images.githubusercontent.com/9205389/94554060-c7a8b780-0259-11eb-9dc7-dc4a0a616b2d.png)

For comparison:

![image](https://user-images.githubusercontent.com/9205389/94554090-d7280080-0259-11eb-85d0-ca2921bb3451.png)

**Comment by egamma** [comment]
Removed the double quotes, kept single quotes around the command name:
![image](https://user-images.githubusercontent.com/172399/94735115-83f1a300-036a-11eb-904d-befa51e2cdbe.png)
