### ISSUE TITLE
WSL welcome page replaces normal welcome

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#3759]
Testing #3752

I think that is not nice, because I might be in the middle of clicking "Open Folder" in the welcome editor and suddenly it gets replaced by the WSL welcome.

This needs a proper story how the flow should be, ideally only one welcome appears.

**Comment by aeschli** [comment]
The WSL welcome page has not made it past the experimental stage yet. 

@bamurtaugh What are our plans?

**Comment by bamurtaugh** [comment]
@aeschli since we have a getting started experience and that's the model we're following for extensions overall now, I think we should remove the welcome page code. I'll open a PR to do that.
