### ISSUE TITLE
[1.35] Extension with WebView doesn't work on remote: Python, Git Graph,Edit csv.

### ISSUE THREAD

**Issue by iFanze** [microsoft/vscode-remote-release#376]
Issue Type: <b>Bug</b>

These extensions do work before I reset my Windows 10. But after I reset my Windows, reinstall my softwares including vscode-insider.  I cannot use these  extensions with Remote - SSH on the remote side. I take the screenshots.

![image](https://user-images.githubusercontent.com/6697503/57967273-5a132880-798f-11e9-9dc8-5a09c70eaae0.png)
![image](https://user-images.githubusercontent.com/6697503/57967276-67301780-798f-11e9-89f0-c92e7975fa24.png)

Extension version: 1.5.0
VS Code version: Code - Insiders 1.35.0-insider (6ac87465f297a9068bf767f45d6f372fc5697de9, 2019-05-17T17:48:07.036Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 2.6.32-573.el6.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (12.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.22.51|
|OS|Linux x64 2.6.32-573.el6.x86_64|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|15.44GB (5.93GB free)|
|VM|0%|
</details>

**Comment by tai** [comment]
I have been following similar issue in https://github.com/microsoft/vscode-python/issues/5676 - could it be related?

I'm having an issue getting result displayed in Python Interactive console, which also uses WebView.
It used to work in past version (of VSCode Insiders, Remote-SSH, and Python extension), but now it  shows blank screen with only a title.

**Comment by egamma** [comment]
The Git Graph extension is using the Web View API need to make some adoption work https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-the-webview-api.

//FYI @Chuxel

**Comment by rchiodo** [comment]
This is also happening for the python extension. I've verified that with insiders 1.34.0 our extension loads just fine. With insiders 1.35.0, the webview we have in our extension doesn't load the bundled javascript. 

You can see it here:
![image](https://user-images.githubusercontent.com/19672699/58036954-21836400-7ae1-11e9-933e-8f3f235ba767.png)

This is what it should look like:
![image](https://user-images.githubusercontent.com/19672699/58038020-b25b3f00-7ae3-11e9-93f4-6fdc17cdc8cd.png)

**Comment by Chuxel** [comment]
@Egamma This does not look like an extension issue as @rchiodo mentions.  Git Graph is using the correct message passing pattern and has no local web server from what I can tell.  This may be some sort of regression in 1.35.

**Comment by Chuxel** [comment]
//cc: @mjbvz Did something regress here in 1.35?

**Comment by mjbvz** [comment]
@bpasero I bisected this and believe the error was introduced by https://github.com/microsoft/vscode/commit/afe9a74dbf14bed2908712739d01faf48e158e69 Can you please help investigate as I am not familiar with this code. I believe the same problem also effects loading of icon images from remote

**Comment by mjbvz** [comment]
This should be fixed by https://github.com/microsoft/vscode/pull/74134. Please test using the next VS Code insiders build
