### ISSUE TITLE
"Open Workspace in WSL" missing

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#3760]
Testing #3752

I think to be consistent there should be support to "Open Workspace in WSL".

To reduce clutter, these elements for WSL should maybe be in their own group separated.

**Comment by aeschli** [comment]
@bpasero Is this for the file menu and/or explorer?

I discussed this with @egamma . I'd just stick with the 'Open Folder in WSL' in order to keep the file menus and the explorer compact. We will offer the other variants (Open File/Workspace in WSL) as commands.

**Comment by bpasero** [comment]
Yeah, file menu.

**Comment by aeschli** [comment]
There are currently no plans to add more open entries to the file menu
