### ISSUE TITLE
WSL Welcome: not a lot of additions to our normal welcome?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#3761]
Testing #3752

Looking at the WSL welcome it seems to suggest very similar things like our normal welcome, at least when it comes to opening files or folders. 

What is the idea here? Now it seems we have 2 competing welcome experiences offering similar things.

I would keep the WSL welcome specific to WSL and e.g. ask users to install certain distros, but not offer basic VSCode help.

**Comment by bamurtaugh** [comment]
Closing as we now have a getting started, rather than a welcome page.
