### ISSUE TITLE
Reopening: COMPOSE_PROJECT_NAME in .env or ENV is ignored

### ISSUE THREAD

**Issue by mrmachine** [microsoft/vscode-remote-release#3762]
**NOTE:** This is a reproduction/reopening of #979, which was originally closed by @chrmarti as a duplicate of #512, as a new issue as requested by @chrmarti in https://github.com/microsoft/vscode-remote-release/issues/512#issuecomment-700674505

VSCode Version: 1.36.0
Local OS Version: Arch
Remote OS Version: Docker image python:3.5
Remote Extension/Connection Type: Docker
Steps to Reproduce:

Set COMPOSE_PROJECT_NAME to your needs.
Open folder in container.
Check that --project-name {folder_name} is passed to docker-compose executable.
Expected beahaviour:
VSCode do not pass --project-name by itself. Also it will be nice to have parameter like project_name in .devcontainer.json.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**NOTE:** Additional to the original issue #979, note that:

The [official docs](https://code.visualstudio.com/docs/remote/containers-advanced#_setting-the-project-name-for-docker-compose) still say:

> VS Code will respect the value of the COMPOSE_PROJECT_NAME environment variable if set for the VS Code process or in a .env file in the root of the project.

And yet, VS Code will in fact always bring up containers with `--project-name BASENAME_OF_PROJECT_DIR`

    [3787 ms] Start: Run: docker-compose --project-name FOO -f /Users/tailee/IC/Projects/FOO/docker-compose.yml -f /Users/tailee/IC/Projects/FOO/.devcontainer/docker-compose.dev.yml up -d --build

This CLI arg seems to override `COMPOSE_PROJECT_NAME` exported before launching VS Code from CLI or in `.env` in the project root directory.

**Comment by chrmarti** [comment]
Starting VS Code with `COMPOSE_PROJECT_NAME=myproject code` works for me.

Placing a `.env` in the project root folder (not the `.devcontainer` folder) with `COMPOSE_PROJECT_NAME=myproject2` also works.

You seem to be using an older version of VS Code. You get an equally older version of Remote-Containers with that. Please update. Does that make it work?
