### ISSUE TITLE
Patterns in ssh config file should not be regarded as hosts

### ISSUE THREAD

**Issue by fyang93** [microsoft/vscode-remote-release#3763]
- VSCode Version:1.49.2
- Local OS Version:Win10 ver2004
- Remote OS Version:Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. In `.ssh/config` file, write configuration like follows:
```
Host !proxy *
    ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -W %h:%p proxy
```
which means all other hosts except `proxy` should be proxied.
2. Then you'll see that `!proxy` shows up in the `SSH TARGETS` list on the side panel.

IMHO, such a pattern should not be considered as a target host, referring to [the "Patterns" section](https://linux.die.net/man/5/ssh_config).

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by derekpurdy** [comment]
Out of curiosity was this ever released, or has it not been pushed out yet? I still see the issue in the latest available exentsion.

**Comment by roblourens** [comment]
I didn't push an October release because I thought there weren't any changes, thanks for the prompt.
