### ISSUE TITLE
WSL2 and SSH_AUTH_SOCK not working with remote hosted docker

### ISSUE THREAD

**Issue by issacg** [microsoft/vscode-remote-release#3764]
I'm happily using WSL2 and remote ssh-agent forwarding via the popular npiperelay.exe solution mentioned [here](https://github.com/microsoft/vscode-remote-release/issues/2925)

However, I'm running into a bit of an edge case when trying to use remote hosted docker over SSH (https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host)

I have set up a `.devcontainer/devcontainer.json` as documented in the above link.  I also set `docker.host` in my workspace's `.vscode/settings.json`

However, in this context, vscode is running a fresh WSL command:
```
293 ms] Start: Check Docker is running
[293 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/user/somefolder' && DOCKER_HOST='ssh://user@domain.com' docker 'info'
```

In this case, I can't figure out how to push even just the `SSH_AUTH_SOCK` variable (let alone the full snippet to make the npiperelay magic work, in case no other WSL shell happens to be running to host the magic)

Furthermore, and possibly unrelated, when trying the same under pure-win32 without connecting to WSL2 (under the assumption that this would use the win32 ssh and ssh-agent directly, circumventing the above problem), the remote docker host option seems to be completely ignored, and the container is built and executed locally:

```
[37 ms] Start: Resolving remote
[38 ms] Setting up container for folder or workspace: c:\Users\user\Documents\project

[39 ms] Start: Check Docker is running
[39 ms] Start: Run: docker info
```

**Comment by chrmarti** [comment]
The built-in support for ssh-agent forwarding should work. Could you post the log (`F1` > `Remote-Containers: Show Log` when connected) here?

On running Windows-side ignoring the remote docker host: Make sure you have `docker.host` in `.vscode/settings.json` or the user settings.

**Comment by issacg** [comment]
Logs for WSL@

```
[81 ms] Start: Resolving remote
[85 ms] Start: Run: wsl -d Ubuntu-20.04 -e wslpath -u \\wsl$\Ubuntu-20.04\home\issac\dev\tn-remote
[379 ms] Start: Run: wsl -d Ubuntu-20.04
[556 ms] Setting up container for folder or workspace: /home/issac/dev/tn-remote

[557 ms] Start: Check Docker is running
[557 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/issac/dev/tn-remote' && DOCKER_HOST='ssh://ec2-user@ec2-18-185-157-55.eu-central-1.compute.amazonaws.com' docker 'info'
[8373 ms] errors pretty printing info

[8376 ms] Docker returned an error code 1, message: Command failed: docker info

```

Note that:
```
C:\Users\issac>wsl -d Ubuntu-20.04 -e /bin/sh -c "ssh ec2-user@ec2-18-185-157-55.eu-central-1.compute.amazonaws.com"
ec2-user@ec2-18-185-157-55.eu-central-1.compute.amazonaws.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

C:\Users\issac>wsl -d Ubuntu-20.04 -e /bin/sh -c "echo $SSH_AUTH_SOCK"

```

But...
```
C:\Users\issac>wsl -d Ubuntu-20.04
❯ echo $SSH_AUTH_SOCK
/home/issac/.ssh/agent.sock
❯ ssh ec2-user@ec2-18-185-157-55.eu-central-1.compute.amazonaws.com
Last login: Wed Sep 30 10:12:30 2020 from 176.229.121.124

       __|  __|_  )
       _|  (     /   Amazon Linux 2 AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-2/
[ec2-user@vscode-ip-172-31-13-155 ~]$
```

So it's not getting the variable injected (which kinda makes sense to me when calling `/bin/sh -c "..."`, but I'm not sure what else ought to be happening here)


For the windows side, while reproducing to gather logs, it (happily) worked!  I don't know what the original issue was, since I didn't record the end of the logs yesterday, but I can see today that it behaves the same - appearing, as it were, to run locally when it is actually running remotely. Maybe just as a feature request, be more verbose about the "resolved remote" in the logs.  

Even when it worked now, I was expecting a failure (like I had yesterday) when I saw the identical beginning of log:
```
[68 ms] Start: Resolving remote
[71 ms] Setting up container for folder or workspace: c:\Users\issac\tn-remote

[73 ms] Start: Check Docker is running
[73 ms] Start: Run: docker info
[7238 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=c:\Users\issac\tn-remote --filter label=vsch.quality=stable
[13062 ms] Start: Run: docker build -f c:\Users\issac\tn-remote\.devcontainer\Dockerfile -t vsc-tn-remote-6df1fd882fb48cd40bc58727db2178f2 --build-arg VARIANT=focal c:\Users\issac\tn-remote\.devcontainer
Sending build context to Docker daemon  4.096kB
...
```
nothing to show that it's picked up on the remote host.  It does show in the title bar once the container is started successfully, but that's not helpful when troubleshooting failures like I had yesterday.  I'm assuming that the failure was mis-aligned paths on the remote-path, as I recall assuming it was trying to mount the path locally and thus failing, but that may have not been the case if it was working remotely.

Thanks!!!

**Comment by issacg** [comment]
Also, so you have it for your convenience:

```
C:\Users\issac\tn-remote>wsl -d Ubuntu-20.04 -e /bin/sh -c "cd '/home/issac/dev/tn-remote' && DOCKER_HOST='ssh://ec2-user@ec2-18-185-157-55.eu-central-1.compute.amazonaws.com' docker 'info'"
Client:
 Debug Mode: false

Server:
ERROR: error during connect: Get http://docker/v1.40/info: command [ssh -l ec2-user -- ec2-18-185-157-55.eu-central-1.compute.amazonaws.com docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=ec2-user@ec2-18-185-157-55.eu-central-1.compute.amazonaws.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

errors pretty printing info
```

**Comment by chrmarti** [comment]
Would it work if we passed SSH_AUTH_SOCK to the 'docker info' command like we pass DOCKER_HOST?

**Comment by issacg** [comment]
Yes it would:

```
C:\Users\issac\tn-remote>wsl -d Ubuntu-20.04 -e /bin/sh -c "cd '/home/issac/dev/tn-remote' && DOCKER_HOST='ssh://ec2-user@ec2-18-185-157-55.eu-central-1.compute.amazonaws.com' SSH_AUTH_SOCK='/home/issac/.ssh/agent.sock' docker 'info'"
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-tp-docker)
...
```

**Comment by issacg** [comment]
FWIW, I didn't aggressively test that for edge cases - for example WSL was running and had already brought up my npiperelay magic when I tested that...  Also, I ran it from the command prompt manually, setting SSH_AUTH_SOCK to where I knew it needed to be (it's populated in my WSL shell, but not in my Win32 environment variables)

**Comment by chrmarti** [comment]
We are running the default shell as login shell to read the environment variables. That will start any services the login shell starts. That might include the npiperelay depending on how you set it up.

**Comment by chrmarti** [comment]
Published the fix with 0.148.0 of the extension (currently requires VS Code Insiders).

**Comment by chrmarti** [comment]
To verify:
- Install WSL2 and enable WSL2 on your WSL distro and enable the WSL2 backend in Docker Desktop for Windows.
- Clone the remote-containers repo in WSL and `cd` into the `dind` folder (all in a WSL shell now):
  - If you don't have an `~/.ssh/id_rsa` yet, run: `ssh-keygen -t rsa -b 4096 -C "your_email@example.com"`
  - Run: `ssh-add ~/.ssh/id_rsa`
  - Run: `docker-compose up -d --build`
  - Check it is working:
    - Run: `ssh vscode@localhost -p 2222` (will also add to your `~/.ssh/known_hosts`)
    - Run: `DOCKER_HOST=ssh://vscode@localhost:2222 docker ps` (should be the empty list)
- Open a Remote-WSL window on a WSL folder.
- Add a `.devcontainer.json`:
```json
{
	"image": "alpine",
	"workspaceMount": "",
	"workspaceFolder": "/"
}
```
- Add workspace setting: `"docker.host": "ssh://vscode@localhost:2222"`
- Reopen folder in container and verify it starts up.
- In a WSL shell, verify the container is now listed: `DOCKER_HOST=ssh://vscode@localhost:2222 docker ps`

**Comment by rzhao271** [comment]
@chrmarti I get 'permission denied' when running `ssh vscode@localhost -p 2222`. I set a password for my ssh key. `docker-compose up -d --build` works, though.
Is there any setup I missed on my vscode side? I have Remote-WSL and can open folders within WSL using it.
