### ISSUE TITLE
VS Code WSL remote with non-default user account

### ISSUE THREAD

**Issue by thedacheng** [microsoft/vscode-remote-release#3765]
Right now  VS Code WSL remote only runs with WSL's default user account, even if I launch it from a bash session logged in as the other account with command line "code .".

Please add the feature to allow user to select WSL account the remote session to run with, similar to selecting WSL distribution. Also when launching code from a WSL shell session, the remote session should respect the user account under which the shell session is running.

#1700

**Comment by aeschli** [comment]
The request to run with non-default user is captured in https://github.com/microsoft/vscode-remote-release/issues/286
