### ISSUE TITLE
Inherited environment is not updated after being set

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-remote-release#3767]
Testing #3751

You didn't explicitly mention whether environment variables should update after launch so thought I'd log this anyways.

1. set environment variable `export FOO='true'`
2. launch code via `code .`
3. check variable in code via `echo $F00`
4. change environment variable outside of vs code
5. :bug: vs code still reports `$FOO` as `true`

**Comment by aeschli** [comment]
Ah, sorry, there's no updating. It's like with every command that is started from a shell. The child process gets a copy of the environment but then the two are no longer connected.
