### ISSUE TITLE
relaunching window clears inherited environment variables

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-remote-release#3768]
Testing #3751

1. set environment variable `export FOO='true'`
2. launch code via `code .`
3. check variable in code via `echo $F00`
4. close vs code and re-launch, it should re-open in the same folder
5. :bug: environment variables are cleared

Interesting to note that after you have opened a new WSL window while in a previous windows, the variables persist. It's when you close the window altogether and re-launch that causes issues and I would expect for Code to remember the environment variables.

**Comment by aeschli** [comment]
How do you re-launch? Double clicking the desktop shortcut? You would have to re-launch from the same shell (entering `code-insiders .` to inherit the variables from that shell.

**Comment by misolori** [comment]
I close VS Code and the re-open from the dock. I think the issue I have is that the experience is a bit inconsistent if you open a new WSL window while the variables are captured from the previous terminal session that used `code .` vs if you open VS Code without `code .`. 

As a user, I'd expect either for variables to always persist or to only persist when explicitly opened via `code .`

**Comment by aeschli** [comment]
I don't think it would be good idea to hold on to the environment across restarts. Let's say you install new stuff that also impacts the environment. You would never see these as we would always restore the old state.

Note that this behaves the same with local windows. Typically you have your env defined in system settings (WIndows) or in `.bashrc` or '.profile` (Linux) and that what all windows use by default. Running with a shell specific env is kind of a special case.
