### ISSUE TITLE
can't connect to host:Pseudo-terminal will not be allocated because stdin is not a terminal.

### ISSUE THREAD

**Issue by LvDunn** [microsoft/vscode-remote-release#377]
VSCode version:  1.35.0-insider
type: SSH
my operating system : windows 10
remote host：Ubuntu 18.04.2 LTS
openssh-server version: 1:7.6p1-4ubuntu0.3

i'm on windows10 installed vscode 1.35.0-insider and Remote Development extension pack, try connet  my Ubuntu Linux server. but failed.
this is my log:
```
Pseudo-terminal will not be allocated because stdin is not a terminal.
root@xxxxxx's password:
```
xxxxxx is my ip.

my ssh config like this:
```
Host aliyun
    HostName xxxxxxx
    User root
    Port 22
    IdentityFile C:\Users\xxx\.ssh\id_rsa-remote-ssh
```

**Comment by Shengr** [comment]
you might add this line of config "RequestTTY force" ,and it works for me

**Comment by LvDunn** [comment]
> you might add this line of config "RequestTTY force" ,and it works for me

I tried it, it didn't work.

**Comment by LvDunn** [comment]
when i update vscode ,The problem is solved
