### ISSUE TITLE
Is it possible to use the "Remote - Containers" feature after connecting via "Remote - SSH"?

### ISSUE THREAD

**Issue by mozgbrasil** [microsoft/vscode-remote-release#3771]
Hello good afternoon

Is it possible to use the "Remote - Containers" feature after connecting via "Remote - SSH"?

See the image of the local environment where ssh access the server

I am not shown the possibility to open the project in Docker

![Captura de tela de 2020-09-29 20-36-32](https://user-images.githubusercontent.com/17202780/94627318-8f25cf80-0293-11eb-9f58-c7652b143ecd.png)
![Captura de tela de 2020-09-29 20-37-00](https://user-images.githubusercontent.com/17202780/94627319-9056fc80-0293-11eb-9321-0d5f77e826d5.png)

**Comment by Chuxel** [comment]
Not currently.  See  #2994 for the feature request.
