### ISSUE TITLE
Log colorization issues in terminal

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#3774]
Testing #3750

![image](https://user-images.githubusercontent.com/4674940/94632281-fd13cc00-027e-11eb-85bc-8f08b7b69fee.png)

This shows a couple of issues:
- Standalong numbers inside identifiers are colorized: "Jinja2-`2.11.2`-py2.py3-none-any.whl"
- Standalone integers inside hex numbers are colorized: "f554cb35-41c8-`4635`-936d-52a0e9b24aba1601427958405"

In both cases I'd expect either all or nothing to be colorized.

**Comment by aeschli** [comment]
I'm still seeing numbers in identifiers colorized:
![image](https://user-images.githubusercontent.com/6461412/94899132-083f4580-0493-11eb-88bb-bb7c7062a008.png)
Also
![image](https://user-images.githubusercontent.com/6461412/94899029-d5954d00-0492-11eb-8529-329bdb40a4a4.png)

**Comment by chrmarti** [comment]
Suggested improvement:
![image](https://user-images.githubusercontent.com/9205389/94913661-eef5c380-04a9-11eb-8ff0-ad4951089618.png)

I currently accept multiple `.` within a number. That also colorizes versions and IP addresses. Only accepting one for numbers would also colorize some version numbers, but not those with two dots or more - which might look inconsistent. The other option would be to not allow `.`.

**Comment by JacksonKearl** [comment]
looks good.
![image](https://user-images.githubusercontent.com/8586769/94970238-1011e080-04b9-11eb-88e4-66cc83d2daba.png)
![image](https://user-images.githubusercontent.com/8586769/94970243-156f2b00-04b9-11eb-8582-3b59a6967c4d.png)
