### ISSUE TITLE
Show Last Log does not find a log

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#3775]
Testing #3750

1)  `Remote-Containers: Create Sample...`
2)  choose one and wait until it's created
3) `Remote-Containers: Show Last Log`
-> 
![image](https://user-images.githubusercontent.com/4674940/94633263-a6f45800-0281-11eb-9cab-b4c5c0db7607.png)

Show All Logs has entries, the terminal shows a log. What does it not find?

**Comment by chrmarti** [comment]
It tries to open the previous log. (There is `Remote-Containers: Show Log` for the current log.)

I think `Last` is not clear enough. I propose to change the command's label to `Remote-Container: Show Previous Log` and the info message when none is found to `No previous log file found`.

The case this is trying to address is when the resolver failed and the user returns to a local workbench and wants to look at the resolver's log which is not the current, but the previous one.
