### ISSUE TITLE
debian on wsl2 unable to run code command

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-remote-release#3779]
- VSCode Version: 
Version: 1.50.0-insider (user setup)
Commit: 0c50e1db17168a738235bd7e5c02b9f05ea5df59
Date: 2020-09-30T06:53:41.824Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20161

- Local OS Version: Win 10 Pro Insider Preview (2004) 20161.1000
- Remote OS Version: Debian
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Install debian from Microsoft store
2. Open the distro through VS Code using the WSL extension
3. try running `code` or `code-insiders` from debian terminal
4. :bug: command not found

I can easily open the distro through the WSL extension but for some reason the distro does not have the code commands installed. Tried searching online for help and found nothing.

**Comment by misolori** [comment]
Ok, so I just installed `zsh` and `Oh My Zsh` and now when i run `code` or `code-insiders` it works 🤷‍♂️ might be something to do with my path?

**Comment by aeschli** [comment]
The WSL runtime makes sure that distros inherit the Windows PATH. You can check that with `env | grep path`.

**Comment by bamurtaugh** [comment]
Sounds like this was (hopefully) a path issue? Going to close out this issue for now then, but please feel free to reopen or circle back with any other questions or feedback!

**Comment by avdi** [comment]
I'm seeing this as well. Installed Debian from the Windows Store, path inside Debian does not include any Windows directories. 

```
avdi@viv:~$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

This differs from my Ubuntu WSL instance, which does have windows paths.

**Comment by avdi** [comment]
Ah, looks like this is a known issue between Debian and WSL2: https://github.com/microsoft/WSL/issues/5779
