### ISSUE TITLE
devcontainer.json context support for docker compose

### ISSUE THREAD

**Issue by Virviil** [microsoft/vscode-remote-release#378]
It seems, that `docker-compose up` command is run inside **devcontainer** folder.

This leads to the problems with volumes, defined in docker-compose file.

For example, I use volume to persist postgres data through containers lifetime like this:

```
    volumes:
      - ./docker/data/postgres:/var/lib/postgres/data
```

Running `docker-compose up` inside root of the project will create `./docker/data/postgres` folder.

BUT: Addressing this docker compose like this in `./.devcontainer/devcontainer.json`:

```
    "dockerComposeFile": [
        "../docker-compose.yml"
    ],
```

Will generally resolve it right, but the folder will be created here: `./.devcontainer/docker/data/postgres`

So the solution probably can be in specifying **context** for running **docker-compose up**

**Comment by chrmarti** [comment]
Relative paths should be relative to the compose file (https://docs.docker.com/compose/compose-file/).

Could you post a minimal working example showing the problem? (devcontainer.json and docker-compose.yml, a Dockerfile if needed)

**Comment by Virviil** [comment]
This is a link to the repo, is kept as minimum as possible:

https://github.com/Virviil/compose_bug

**Comment by chrmarti** [comment]
It looks like Docker Compose will use the first docker-compose file for resolving relative paths. When you use `docker-compose -f .devcontainer/docker-compose.extend.yml -f docker-compose.yml` from the command line you will see the same behavior.

Try reversing the order of the two docker-compose files in the devcontainer.json. HTH.

**Comment by Virviil** [comment]
@chrmarti Yep, thanx, this seems to fix the problem.

May be it can be specified in documentation, that the order of the files is important?

Somewhere here: https://code.visualstudio.com/docs/remote/containers#_extending-your-docker-compose-file-for-development

**Comment by Chuxel** [comment]
@chrmarti @Virviil  Yeah we can document that, but the bigger consideration is the relative path. I think is the only real fix to this.

This is effectively what is happening now in the extend case:

```bash
cd .devcontainer && docker-compose -f ../docker-compose.yml -f docker-compose.extend.yml up
```

Build has a context that make things work, but for this volume scenario, the only way I can see to fix this is to support  `context` property in devcontainer.json for dockerComposeFile like we support for the other cases.

**Comment by Chuxel** [comment]
@chrmarti @Virviil Oh wait - Didn't see that the files were reversed in the devcontainer.json [here](https://github.com/Virviil/compose_bug).

**Comment by Virviil** [comment]
@Chuxel 
I'm not sure, but it seems that `docker-compose` resolves the working directory, to which the file paths are relative, as the directory where the first `docker-compose.yml` file is located.

So, even if the `docker-compose` command will be called with absolute path to the `docker-compose.yml` file from any working directory - actual working directory will be resolved right.

But the problem appears when the `docker-compose` files are more then one.
Second and next are called in the context of the first `docker-compose.yml` file, and that's why order is so important.

Thank you for updating the docs!
