### ISSUE TITLE
Opening remote via `code .` after window is already open breaks the window

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode-remote-release#3781]
Testing #3751

1. Open a new wsl window from the WSL extension
2. Open code via `code .`
3. :bug: window breaks

![image](https://user-images.githubusercontent.com/35271042/94717978-e795b500-0305-11eb-9ecc-586d210421f1.png)

**Comment by aeschli** [comment]
Nothing in the WSL log?
