### ISSUE TITLE
Save successfully, but file is unchanged

### ISSUE THREAD

**Issue by XinDongol** [microsoft/vscode-remote-release#3782]
Issue Type: <b>Bug</b>

It will happened sometimes. 

Extension version: 0.55.0
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 5.4.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.52GB (18.13GB free)|
|Process Argv|C:\Users\xind\Downloads\di_submit.py --crash-reporter-id 49e5eaa8-2849-4101-bea5-351f2f610d63|
|Screen Reader|no|
|VM|36%|

|Item|Value|
|---|---|
|Remote|SSH: 172.17.169.45|
|OS|Linux x64 5.4.0-42-generic|
|CPUs|Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz (12 x 1200)|
|Memory (System)|31.05GB (12.95GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
If this is still an issue, please give more details
