### ISSUE TITLE
[IDEA] PiZero Support? 

### ISSUE THREAD

**Issue by Merith-TK** [microsoft/vscode-remote-release#3783]
https://github.com/microsoft/vscode-remote-release/issues/669#issuecomment-640986010 < yes i did read this, dont close just yet

Basically i saw the explination that the limited ram can and most likely will cause issues. My though process is why not make a limited support version for these architectures/devices? Like have it only be capible of utilizing a small subset of features such as the editor and the terminal? and maybe at most 2-5 extensions?

Limit the capability so that it doesnt overwhelm and cause as many issues, but give a popup on connection stating that the arch is not fully supported and that the user may run into issues

EDIT: TLDR, Wouldn't it be possible to allow the PiZero as a target by disabling certain functions such as extensions, and providing a warning that said functions are disabled, or by having the main things such as intellisense run on VScode instead

**Comment by Merith-TK** [comment]
Why was this marked as a duplicate? I provided an concept for how the target device could become supported, nto requesting support for said device

**Comment by roblourens** [comment]
Sorry, it's not practical for us to build a stripped down experience like that.
