### ISSUE TITLE
Get alpine error when dockerfile specifies ubuntu

### ISSUE THREAD

**Issue by rasck** [microsoft/vscode-remote-release#379]
- VSCode Version: 1.34.20-insider
- Local OS Version: MacOS 10.14.3
- Remote OS Version: First Alpine then Ubuntu
- Remote Extension/Connection Type: Docker

Purpose:
I want to make a small demo with Remote to docker based on a newer version of node.

Steps to Reproduce:

1. First I created a Dockerfile based on the newest from `node:lts` i think, it uses alpine as its base image.
3. I then create a container configuration file that refers to my docker file
```
// See https://aka.ms/vscode-remote/devcontainer.json for format details.
{
	"dockerFile": "Dockerfile",
	"extensions": []
}
```
4. Use the command for open the container `Remote-Containers: Reopen Folder In Container`
5. I get the error "Alpine Linux is not supported as the container OS. Try using an image that is not built from Alpine Linux."
6. I then tried to create a Dockerfile based on `ubuntu:latest`
```
FROM ubuntu:latest
USER root
WORKDIR /home/app
COPY ./package.json /home/app/package.json
RUN apt-get update
RUN apt-get -y install curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_11.x  | bash -
RUN apt-get -y install nodejs
RUN npm install

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000
CMD [ "npm", "start" ]
```
7. Again tried the `Remote-Containers: Reopen Folder In Container` and i get the "Alpine Linux is not supported as the container OS. Try using an image that is not built from Alpine Linux." error.

My folder structure:
```
- node_modules
- .devcontainer.json
- .dockerignore
- app.js
- Dockerfile
- index.html
- package-lock.json
- package.json
```

**Comment by chrmarti** [comment]
You need to rebuild the container. There is a command for doing that while inside the container or you just delete the container manually before running the reopen command. HTH.
