### ISSUE TITLE
Serial devices are not visible via /dev/ttyS*

### ISSUE THREAD

**Issue by scubachristopher** [microsoft/vscode-remote-release#3795]
WSL 2, Ubuntu 18.04, updated.
Attach a device (like a Olimex ESP32-EVB board or a Huzza Feather 32) via USB:

```
chris@Christopher-PC:~$ ls -al /dev/ttyS*
crw------- 1 root root 4, 64 Oct  3 12:59 /dev/ttyS0
crw------- 1 root root 4, 65 Oct  3 12:59 /dev/ttyS1
crw------- 1 root root 4, 66 Oct  3 12:59 /dev/ttyS2
crw------- 1 root root 4, 67 Oct  3 12:59 /dev/ttyS3
```

Arduino app allows you to detect and connect to the device and get the board info.  COM6 gives the device information.  But it's not mounted at /dev/ttyS6.  Attempts at 0 - 3 do not provide access to the device.

What **COULD** be fabulous about this environment is development of ESP32 devices via MS Code.  In fact, installing code via:

`~$ code .`

installs the WSL code version.  I can build, all is _wonderful_.  Except you can't serial monitor the device because of this issue.

Please fix!  You would unleash a path from MacOS back to Windows.

**Comment by aeschli** [comment]
You need to file this against WSL: https://github.com/microsoft/wsl
