### ISSUE TITLE
installed programms are not accessable

### ISSUE THREAD

**Issue by Mrityunjoy99** [microsoft/vscode-remote-release#3797]
Issue Type: <b>Bug</b>

i have installed pip,numpy in ubuntu bash termnal but it is not working in the integrated bash terminal

Extension version: 0.44.5
VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (0.79GB free)|
|Process Argv|--crash-reporter-id e22f9cae-6f2d-4f96-bc46-91510187161d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1801)|
|Memory (System)|7.92GB (0.79GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment]
Did you check the environment?
`echo $PATH`

**Comment by Tyriar** [comment]
Also your settings.json file might point out the problem.
