### ISSUE TITLE
Git on SSH connection to Azure not displaying changed lines

### ISSUE THREAD

**Issue by madamemohn** [microsoft/vscode-remote-release#3803]
I’ve got a problem in VS code when I connect via SSH to an Azure compute instance. 

When I change lines in a file that’s tracked by Git I cannot see the line changes inside the file. So what usually looks like this on my local laptop:
 
![grafik](https://user-images.githubusercontent.com/61541143/95183326-1dcfaa80-07c6-11eb-983e-de866753b587.png)

looks like this:
 
![grafik](https://user-images.githubusercontent.com/61541143/95183312-17d9c980-07c6-11eb-9dde-99aecb9f2738.png)

on the SSH connection to Azure. I changed the same lines both times.

- VSCode Version: 1.49.2
- Local OS Version: Windows 10 Enterprise Build 17763
- Remote OS Version: Ubuntu 16.04.7 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. connect via SSH to Azure compute instance
2. open some file that is tracked by GIT
3. change a line

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by joaomoreno** [comment]
@madamemohn Can you reproduce if you connect to another SSH machine?
