### ISSUE TITLE
 Vscode's server is OOM killed

### ISSUE THREAD

**Issue by sunbohong** [microsoft/vscode-remote-release#3808]
- VSCode Version: 1.493
- Local OS Version: macOS 10.15.7
- Remote OS Version:  CentOS7
- Remote Extension/Connection Type: SSH

版本: 1.49.3
提交: 2af051012b66169dde0c4dfae3f5ef48f787ff69
日期: 2020-10-02T17:54:06.165Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Install fabiospampinato.vscode-diff
2. cmd+shift+p
3. Select Diff

Does this issue occur when you try this locally?:No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by sunbohong** [comment]
PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND               
 6948 root      20   0 4332564   1.4g      0 D  0.7 79.1   4:41.29 node                  
 6474 root      20   0  837016   5816      0 D  0.8  0.3   0:25.53 node                  
 6562 root      20   0  747092   2832     72 D  0.8  0.2   0:27.48 node

**Comment by bamurtaugh** [comment]
Do you run into memory issues solely when working with "fabiospampinato.vscode-diff?"

**Comment by sunbohong** [comment]
> Do you run into memory issues solely when working with "fabiospampinato.vscode-diff?"

Yes,i wil run into the same memory issue

**Comment by roblourens** [comment]
Can you use ps to get the full command args of that node process? And how much memory does your remote have? We might just need a little more.

**Comment by sunbohong** [comment]
> Can you use ps to get the full command args of that node process? And how much memory does your remote have? We might just need a little more.

the ps cannot be executed

**Comment by sunbohong** [comment]
After click `DIFF:file`,the remote machine could not respond to any commands
