### ISSUE TITLE
Debugging with external terminal does not work

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-remote-release#381]
Some debug extensions support to use an "external terminal" for running the target program (e.g. Python, Node, C++).

Using this option in a remote scenario (WSL, SSH, Docker Container) might result in the following error:

![](https://user-images.githubusercontent.com/13199757/53056624-d1085600-3460-11e9-8aa6-7d128ff124d7.png)

**Comment by weinand** [comment]
The issue is that some of the linux systems used in the remote scenarios don't have a terminal application "xterm".

The fix is to configure a different terminal emulator via the `terminal.external.linuxExec` setting (or to disable the use of an external terminal in the launch configuration).

Another issue is that the error reporting for this situation is not very helpful.

**Comment by weinand** [comment]
To address the bad error reporting I suggest to improve the error message in two places:

Instead of just returning the somewhat cryptic OS error received from VS Code:

![2019-04-16_10-34-58](https://user-images.githubusercontent.com/1898161/56194583-991e2900-6033-11e9-8629-3bf40e3dbcb1.png)

the affected extensions needs to return a better error message which embeds the OS error as further details.
For instance in Node Debug the same error shows up like this:

![2019-04-16_10-19-54](https://user-images.githubusercontent.com/1898161/56193731-a0dcce00-6031-11e9-99fc-f478350e0378.png)

In addition the error could contain a link that refers to more information about this problem and how to fix it.

In VS Code I will try to detect the "ENOENT" error and map it to a more meaning error message, e.g. "External terminal application 'xterm' not found".

**Comment by weinand** [comment]
In addition debug extensions might want to detect the case that they are running remotely and change the "external terminal" option into an "integrated terminal".

**Comment by weinand** [comment]
I've improved the error message that gets returned from VS Code to the debug extension. With this the error dialog for linux shows this:

<img width="697" alt="2019-04-16_18-47-05" src="https://user-images.githubusercontent.com/1898161/56228884-fc7e7a00-6078-11e9-97bb-b7b5a2cb6a37.png">

**Comment by weinand** [comment]
This was fixed for the April release.

**Comment by pieandcakes** [comment]
@weinand Can you link the commit that fixed this? Thanks

**Comment by weinand** [comment]
@pieandcakes the commit on the VS Code side is this https://github.com/Microsoft/vscode/commit/38cad5d4f67c78cad17bec565242663c965e995e

**Comment by egamma** [comment]
Discussed with @chuxel. The concern is that message is not easy to understand for a windows user that tries SSH or DevContainer for an existing project.

The suggestion to provide some more guidance in the error dialog. Suggestion:
"Cannot launch debug target in terminal (can't find terminal application xterm). Open `launch.json` and change the `console` setting to use the internal console."

**Comment by weinand** [comment]
Yes, improving the message is one thing debug extensions need to do (VS Code provides only the `"can't find terminal application xterm"` part. The rest of the message comes from debug extensions that support an external terminal).

Another is to use the **Integrated Terminal** as the default (instead of the **External Terminal**).

**Comment by pieandcakes** [comment]
>>>The rest of the message comes from debug extensions that support an external terminal and only the extension knows the name of the launch config attribute)

Is there a launch config attribute for users to change the terminal settings? I thought it was only in the VS Code Settings json that the setting existed. We ran into this with users using the RunInTerminal DAP message with external set but the default that VS Code chose doesn't exist on their machine. Once this is shipped, I can give it a shot and see if the experience is better.

I agree that if theres a way to point the user to the settings json option to configure it that would be useful too.

**Comment by weinand** [comment]
@pieandcakes terminal settings for configuring the Integrated and external terminals only exist in the VS Code settings. But a debug extension contributes the attribute that determines what terminal to use, e.g. `externalConsole` for C++ and `console` for Node.js. So the error message that explains what the user has to change must come from the extension too.

Here is the code from node-debug: https://github.com/microsoft/vscode-node-debug/blob/56dc3892885b3122385b785322b00a92d33fdded/src/node/nodeDebug.ts#L1115

The code that improves the `runInTerminal` error message from `"spawn xterm ENOENT"` to `"can't find terminal application xterm"` ships already since two VS Code releases.

**Comment by pieandcakes** [comment]
I understand the `externalConsole` from `true` to `false` change needs to come from us. The common issue we see is in the Linux world where the user has a non-mainstream terminal application as their default but VS Code is set to a different value and in that instance to have a good way for the user to know where to change it to something they have. We have sticky'ed an issue in our repo to help users find and change that setting currently.
