### ISSUE TITLE
"Connect reconnect" window after opening a file

### ISSUE THREAD

**Issue by ChrisRackauckas** [microsoft/vscode-remote-release#3811]
- VSCode Version: 1.49.3
- Local OS Version: Windows 10
- Remote OS Version: Linux
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Remote SSH over
2. Add password to log in
3. Open file
4. Get window

This comes after fixing https://github.com/microsoft/vscode-remote-release/issues/540

**Comment by ChrisRackauckas** [comment]
![Capture](https://user-images.githubusercontent.com/1814174/95357160-85a0f680-0895-11eb-9a01-c5aabc7264b7.PNG)

**Comment by ChrisRackauckas** [comment]
This occurs without remote extensions installed.

**Comment by ChrisRackauckas** [comment]
I can work around this by ssh'ing into the server and killing the hanging VS Code process each time.

**Comment by roblourens** [comment]
Does reloading the window not work? What process are you killing? Please share the Remote-SSH output channel log file
