### ISSUE TITLE
TypeScript Server Crashing

### ISSUE THREAD

**Issue by thelaughingwolf** [microsoft/vscode-remote-release#3813]
Issue Type: <b>Bug</b>

The TypeScript server on the remote keeps crashing. The output log for TypeScript shows, all at the same timestamp, a series of:

Starting TS Server
Not starting server. Too many crashes.

Once the TypeScript server quits restarting, I lose a variety of syntax highlighting.

The system information displayed below looks like it's actually a record of VSCode Remote failing to retrieve the system information it was looking for.

Extension version: 0.20.0
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-118-generic
Fetching remote diagnostics for 'SSH' failed: The process tried to write to a nonexistent pipe

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (4.20GB free)|
|Process Argv|--crash-reporter-id 37ef8f88-b249-4327-a38a-098f6966ffa1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 67.207.84.168|
|OS|Linux x64 4.15.0-118-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz (1 x 1797)|
|Memory (System)|0.96GB (0.54GB free)|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: The process tried to write to a nonexistent pipe
</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
