### ISSUE TITLE
Vs Code hangs and ends with a lot of <stderr> when trying to remote ssh 

### ISSUE THREAD

**Issue by davendramaharaj1** [microsoft/vscode-remote-release#3814]
- VSCode Version: 1.49
- Local OS Version: macOS Catalina 10.15.7
- Remote OS Version: Debian GNU/Linux 10.6
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. On the command palette, click  "Remote-SSH: Connect to Host"
2. Enter relevant information for: user@host
3. Click continue (if prompted)
4. Enter password (if required)

NOTE: When i try the same procedure on someone else's machine, it works. But for me, it doesn't. 

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

![IMG_1044](https://user-images.githubusercontent.com/54917008/95407090-11447280-08ea-11eb-8ed0-14f6dd633205.j

![IMG_1047](https://user-images.githubusercontent.com/54917008/95407095-16a1bd00-08ea-11eb-834f-3479fbd6ac03.jpg)
pg)

**Comment by FatemaTabassum** [comment]
I am having the same problem.. Please resolve/reply to the issue ASAP if you can.

**Comment by roblourens** [comment]
Your ssh server is doing something weird, if something like `echo "echo hello" | ssh host` works then this should work but I don't know what it's doing, sorry
