### ISSUE TITLE
Alpine Linux 3.9 or later required

### ISSUE THREAD

**Issue by marianan** [microsoft/vscode-remote-release#3819]
- VSCode Version: 1.49.3
- Local OS Version: Windows_NT x64 10.0.19042
- Remote OS Version: Alpine Linux v3.11
- Remote Extension/Connection Type: Docker with WSL2
- Remote Development extension version: v0.20.0

Steps to Reproduce:

1. Create a new IoT Edge C# Module in VS code
2. VS Code Palette: Setup IoT Edge simulator then Start IoT Edge Hub simulator in Single Module
3. Open Docker dashboard and make sure azureiotedge-testing-utility container is running
4. In VS code, go to Remote explorer, select the azureiotedge-testing-utility image
5. Right click and select Attach to container
Actual result: Error message "Alpine Linux 3.9 or later required" displays (see screen shot below)
Expected result: Debugger connects to container

![image](https://user-images.githubusercontent.com/10135329/95495829-cdd31e00-0954-11eb-93a3-108f02ebfa49.png)

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
The limitation is on the container's Alpine version. What is the container's distro and version? If it is an image from https://hub.docker.com/_/microsoft-azureiotedge-testing-utility it might be Alpine 3.8 (which is no longer actively supported by Alpine: https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases).
