### ISSUE TITLE
C/C++ dependencies

### ISSUE THREAD

**Issue by sokratis95** [microsoft/vscode-remote-release#3820]
Hi, I am facing a problem with C/C++ extension, using remote ssh plugin

My local pc is on macOS Catalina 10.15.6 and the remote one that I am connecting to is on Ubuntu 16.04.

Despite having the latest version of C/C++ extension (1.0.1) installed on vsc both in my home and remote pc, when vsc starts these messages pop up and C/C++ extension is not working: 
1) Downloading C/C++ language components (Linux / x86_64)
2)The C/C++ extension failed to install successfully. You will need to repair or reinstall the extension for C/C++ language features to function properly. Source: C/C++ (Extension)

The output is:
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed to download https://go.microsoft.com/fwlink/?linkid=2143240
Failed at stage: downloadPackages
Error: Client network socket disconnected before secure TLS connection was established
	at connResetException (internal/errors.js:570:14)
	at TLSSocket.onConnectEnd (_tls_wrap.js:1361:19)
	at Object.onceWrapper (events.js:312:28)
	at TLSSocket.emit (events.js:228:7)
	at endReadableNT (_stream_readable.js:1185:12)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.

I think that this strange behaviour started after updating to 1.0.0

VSC about info
Version: 1.50.0
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:00:00.397Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Thanks in advance!

**Comment by bamurtaugh** [comment]
Did you try the recommendation from the output: `If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.`?

**Comment by bamurtaugh** [comment]
Please feel free to let us know if you're still experiencing any problems or have any other questions here. Thank you!

**Comment by sokratis95** [comment]
> Did you try the recommendation from the output: `If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.`?

By doing the recommended VSIX install the problem was solved, but with latest 1.1.0 update the problem came back again and it needed a VSIX update to be solved for second time.
