### ISSUE TITLE
Forwarded ports view should use welcome views when no ports are forwarded

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#3826]
Currently, it uses the old model of having a list item to indicate that you can do something. Welcome views are the empty view solution now, and their buttons draw better attention to the action that can be taken (forward a port).

**Comment by rzhao271** [comment]
![vscode-forward-a-port](https://user-images.githubusercontent.com/7199958/97354974-76d5b000-1853-11eb-981b-7371865a7a7e.png)

I'm assuming this is the new view?

**Comment by alexr00** [comment]
Yes, that's correct!
