### ISSUE TITLE
"Initializing JS/TS language features" forever

### ISSUE THREAD

**Issue by einarmagnus** [microsoft/vscode-remote-release#383]
Issue Type: <b>Bug</b>

I open a project within WSL and it never seems to finish initializing the JS/TS language runtime.

Extension version: 0.34.0
VS Code version: Code - Insiders 1.34.20-insider (57b550c559b945eb9d871dbf2b2e4cb9e31e2551, 2019-05-10T17:36:45.765Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.83GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+default/home/einarm/download/brizzo-blarf --remote=wsl+default|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.93GB (2.83GB free)|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Please test this using a VS Code 1.35 insiders build
