### ISSUE TITLE
“Failed to establish connection to remote SSH host” Solution

### ISSUE THREAD

**Issue by greenking19** [microsoft/vscode-remote-release#3830]
- VSCode Version:  1.50.0
- Local OS Version: win10
- Remote OS Version: centos7
- Remote Extension/Connection Type: SSH/Docker/WSL

Before, my ssh has been very good, but yesterday I didn’t know what was going on and I couldn’t connect, and the error "Failed to establish connection to remote SSH host" was displayed. Then I kept looking for the problem. I found this problem today. My solution is as follows.
Just write the path of the config file on the setting

![image](https://user-images.githubusercontent.com/43332372/95643171-14a14f00-0ae0-11eb-8f8d-dacc06410611.png)
Hope to help those in need
😉😉

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by bamurtaugh** [comment]
Thank you for sharing @greenking19! As it's now been open for other folks to see, going to close out the thread, but please feel free to let us know if you have anything else you'd like to discuss.
