### ISSUE TITLE
`code .` hangs

### ISSUE THREAD

**Issue by piejanssens** [microsoft/vscode-remote-release#3831]
- VSCode Version: 1.50
- Local OS Version: 1909 Build 18363.1082
- Remote OS Version: Ubuntu 20.04 - 4.19.128-microsoft-standard
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Open Ubuntu WSL
2. Open current folder in VS Code by entering `code .`
3. `code` command hangs and nothing happens

The issue does not occur locally from cmd.exe or PowerShell.
The issue does not occur when executed in WSL in VS Code built in terminal.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by ultrinn** [comment]
I believe I am having this same issue. It gives a return code of 1 then does not run. 

It only appears to be happening in the subfolders of /var/www. I created a subfolder in www and gave my user full permissions (777) and got the same result. My user is the owner and the group. 

If I go to a different directory and run code followed by the full path to the subfolder, it works correctly. If I run code from any other directory and give it the full path to a subfolder in /var/www it works correctly.

I can also run code . on any directory while in the Terminal in vscode.

**Comment by aeschli** [comment]
Can you run `VSCODE_WSL_DEBUG_INFO=true code. --verbose` to get more information?

**Comment by ultrinn** [comment]
This is what I get when I run that command:
COMMIT=d2e414d9e4239a252d1ab117bd7067f125afd80a
+ APP_NAME=code
+ QUALITY=stable
+ NAME=Code
+ DATAFOLDER=.vscode
+ realpath /mnt/c/Users/gerrtrav/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/gerrtrav/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/gerrtrav/AppData/Local/Programs/Microsoft VS Code/bin
+ VSCODE_PATH=/mnt/c/Users/gerrtrav/AppData/Local/Programs/Microsoft VS Code
+ ELECTRON=/mnt/c/Users/gerrtrav/AppData/Local/Programs/Microsoft VS Code/Code.exe
+ IN_WSL=false
+ [ -n Ubuntu-18.04 ]
+ IN_WSL=true
+ [ true = true ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID
+ wslpath -m /mnt/c/Users/gerrtrav/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ CLI=C:/Users/gerrtrav/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/gerrtrav/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/gerrtrav/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --locate-extension ms-vscode-remote.remote-wsl
+ cat /tmp/remote-wsl-loc.txt
+ WSL_EXT_WLOC=
+ [ -n  ]
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/gerrtrav/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/gerrtrav/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js . --verbose
+ exit 1

**Comment by piejanssens** [comment]
```
➜  pietejanssens VSCODE_WSL_DEBUG_INFO=true code . --verbose
+ COMMIT=e5a624b788d92b8d34d1392e4c4d9789406efe8f
+ APP_NAME=code
+ QUALITY=stable
+ NAME=Code
+ DATAFOLDER=.vscode
+ realpath /mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/bin
+ VSCODE_PATH=/mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code
+ ELECTRON=/mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/Code.exe
+ IN_WSL=false
+ [ -n Ubuntu-20.04 ]
+ IN_WSL=true
+ [ true = true ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID
+ wslpath -m /mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ CLI=C:/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --locate-extension ms-vscode-remote.remote-wsl
```

**Comment by piejanssens** [comment]
@aeschli It seems to be stuck on https://github.com/microsoft/vscode/blob/master/resources/win32/bin/code.sh#L46

**Comment by piejanssens** [comment]
Same issue, different user: https://stackoverflow.com/questions/63103002/wsl2-vscode-code-command-to-open-vscode-with-in-ubuntu-no-longer-working

**Comment by piejanssens** [comment]
I am available to provide more info or join a screen sharing / conf call if this would help.

**Comment by aeschli** [comment]
Can you manually run the commands in a WSL shell?
- `ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --locate-extension ms-vscode-remote.remote-wsl` should return a location
- Test whether `echo hello >/tmp/remote-wsl-loc.txt` works
Could be a write permission issue.

**Comment by piejanssens** [comment]
```
➜  ~ cat /tmp/remote-wsl-loc.txt
c:\Users\pietejanssens\.vscode\extensions\ms-vscode-remote.remote-wsl-0.52.0
➜  ~ echo hello >/tmp/remote-wsl-loc.txt
➜  ~ cat /tmp/remote-wsl-loc.txt
hello
```

The first command doesn't return a location. After adding double quotes around the path to Code.exe and the path to cli.js it starts VS Code and opens the cli.js file. The WSL shell stays open and shows this output:

```
➜  ~ ELECTRON_RUN_AS_NODE=1 "/mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/Code.exe" "C:/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js" --locate-extension ms-vscode-remote.remote-wsl

[main 2021-01-05T10:23:13.668Z] update#setState idle
(node:3556) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\pietejanssens\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
                                                                        (node:3556) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\pietejanssens\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
                     (node:23308) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\pietejanssens\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
```

**Comment by piejanssens** [comment]
Seems that vscode-sqlite3 is the culprit?

**Comment by aeschli** [comment]
ah, also needs `WSLENV=ELECTRON_RUN_AS_NODE/w` can you add that before `ELECTRON_RUN_AS_NODE=1` ?

**Comment by piejanssens** [comment]
```
➜  ~ WSLENV=ELECTRON_RUN_AS_NODE/w ELECTRON_RUN_AS_NODE=1 "/mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/Code.exe" "C:/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js" --locate-extension ms-vscode-remote.remote-wsl
c:\Users\pietejanssens\.vscode\extensions\ms-vscode-remote.remote-wsl-0.52.0
```

**Comment by aeschli** [comment]
Ok, that looks good then. I suspect it has to do with the existing values of `WSLENV` as can be seen here
`WSLENV=ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID`.

Does maybe `VSCODE_WSL_DEBUG_INFO=true WSLENV=""' code. --verbose` work?

**Comment by piejanssens** [comment]
No, apart from verbose output it's the same as `code .`:

```
➜  ~ VSCODE_WSL_DEBUG_INFO=true WSLENV="" code . --verbose
+ COMMIT=ea3859d4ba2f3e577a159bc91e3074c5d85c0523
+ APP_NAME=code
+ QUALITY=stable
+ NAME=Code
+ DATAFOLDER=.vscode
+ realpath /mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/bin
+ VSCODE_PATH=/mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code
+ ELECTRON=/mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/Code.exe
+ IN_WSL=false
+ [ -n Ubuntu-20.04 ]
+ IN_WSL=true
+ [ true = true ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:
+ wslpath -m /mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ CLI=C:/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --locate-extension ms-vscode-remote.remote-wsl
```

**Comment by aeschli** [comment]
So, in summary, `WSLENV=ELECTRON_RUN_AS_NODE/w ELECTRON_RUN_AS_NODE=1 "/mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/Code.exe" "C:/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js" --locate-extension ms-vscode-remote.remote-wsl
c:\Users\pietejanssens\.vscode\extensions\ms-vscode-remote.remote-wsl-0.52.0 >/tmp/remote-wsl-loc.txt` works from the terminal, but when part of the shell script it does not terminate, correct?

I think we need to file it against WSL:

**Comment by piejanssens** [comment]
`WSLENV=ELECTRON_RUN_AS_NODE/w ELECTRON_RUN_AS_NODE=1 "/mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/Code.exe" "C:/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js" --locate-extension ms-vscode-remote.remote-wsl c:\Users\pietejanssens\.vscode\extensions\ms-vscode-remote.remote-wsl-0.52.0 >/tmp/remote-wsl-loc.txt` doesn't exit either.

```
➜  ~ echo "" > /tmp/remote-wsl-loc.txt
➜  ~ cat /tmp/remote-wsl-loc.txt

➜  ~ WSLENV=ELECTRON_RUN_AS_NODE/w ELECTRON_RUN_AS_NODE=1 "/mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/Code.exe" "C:/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js" --locate-extension ms-vscode-remote.remote-wsl c:\Users\pietejanssens\.vscode\extensions\ms-vscode-remote.remote-wsl-0.52.0 >/tmp/re
mote-wsl-loc.txt
^C%
➜  ~ WSLENV=ELECTRON_RUN_AS_NODE/w ELECTRON_RUN_AS_NODE=1 "/mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/Code.exe" "C:/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js" --locate-extension ms-vscode-remote.remote-wsl c:\Users\pietejanssens\.vscode\extensions\ms-vscode-remote.remote-wsl-0.52.0 >/tmp/remote-wsl-loc.txt
^C%
➜  ~ cat /tmp/remote-wsl-loc.txt
c:\Users\pietejanssens\.vscode\extensions\ms-vscode-remote.remote-wsl-0.52.0
➜  ~
```

**Comment by piejanssens** [comment]
I completely uninstalled VS Code, deleted all these folders manually and still have the same issue.

- %LocalAppData%\Programs\Microsoft VS Code
- %AppData%\Code
- %UserProfile%\.vscode
- ~/.vscode-server

**Comment by piejanssens** [comment]
Issue persists after updating to `Microsoft Windows [Version 10.0.19042.746]`

**Comment by piejanssens** [comment]
Hey bot, Hey @aeschli,

I don't know what further information I could provide.

**Comment by aeschli** [comment]
Sorry for the time this takes. To me it looks like a WSL interop issue. I still try to nail this down so I can forward the issue to WSL.

Unfortunately an unnecessary parameter snuck in [in my comment here](https://github.com/microsoft/vscode-remote-release/issues/3831#issuecomment-754675824)

So if you can try the following again and let me know whether they terminate

In the WSL shell:
- `WSLENV=ELECTRON_RUN_AS_NODE/w ELECTRON_RUN_AS_NODE=1 "/mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/Code.exe" "C:/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js" --locate-extension ms-vscode-remote.remote-wsl >/tmp/remote-wsl-loc.txt` does not terminate
- `WSLENV=ELECTRON_RUN_AS_NODE/w ELECTRON_RUN_AS_NODE=1 "/mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/Code.exe" "C:/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js" --locate-extension ms-vscode-remote.remote-wsl` prints to the console but does not terminate

**Comment by piejanssens** [comment]
I ran these in the WSL shell and have the same observation, they both do not terminate.

**Comment by piejanssens** [comment]
CTRL+C on the first one closes without any output.
CTRL+C on the second one keeps printing "write failed 32: Broken pipe"

**Comment by aeschli** [comment]
I created https://github.com/microsoft/WSL/issues/6993. @piejanssens Can you subscribe in the other info? If you have any additional infos (e.g. updates to the kernel version or window build you are using, please add the information there.

Closing this issue.

**Comment by piejanssens** [comment]
Subscribed. Thanks @aeschli
