### ISSUE TITLE
Visual Studio Code - Insiders docker returned an error Make sure the docker daemon is running

### ISSUE THREAD

**Issue by dprasadk** [microsoft/vscode-remote-release#384]
### Visual Studio Code - Insiders docker returned an error Make sure the docker daemon is running

In regards to the step given me in README.md file 
Please find docker information for your reference where i am using 🥇 Docker Community edition ( Docker for Windows desktop) and requesting to suggest 

![image](https://user-images.githubusercontent.com/25827250/58003202-e7748b00-7afd-11e9-925a-125f6a5e7952.png)

![image](https://user-images.githubusercontent.com/25827250/58002987-64ebcb80-7afd-11e9-9555-e91b577551b6.png)

When i am attempting to open the cloned copy in ( vscode-insders ) with given options as Remote-Containers : Open folders in Container . i am getting the below error 

![image](https://user-images.githubusercontent.com/25827250/58002667-91ebae80-7afc-11e9-96e9-77384b3b5ee7.png)

I tried the Docker Documentation details here , even though it's not working getting the same error. please suggest, thankful in advance 👍 
![image](https://user-images.githubusercontent.com/25827250/58003073-9ebcd200-7afd-11e9-8d6f-6d7ceabafc4d.png) 
![image](https://user-images.githubusercontent.com/25827250/58003100-b300cf00-7afd-11e9-9f5c-2b99d6e657aa.png)

Kind Regards,
Durga

**Comment by dprasadk** [comment]
**Thanks, Chuxel,**
#### Please find my response
* Are you on Linux or Windows (you mention Docker Desktop for Windows)
   - I am using Windows 
*  If Windows, are you trying to use a remote docker machine?
   - I am connected to my local docker machine and attempting to simulate  Remote Container scenario in reference to given [demo_link](https://www.youtube.com/watch?time_continue=1&v=TVcoGLL6Smo )
   - Please let me know in case i am mistaking.
* Is the "docker" command available from the command line?
  - Yes i am able to execute "docker" from cmd.exe , git-bash  and also from vs-code < power shell > terminal
##### Finally please suggest me how to configure Daemon , make Docker Daemon service running to overcome Visual Studio Code - Insider <ongoing issue : Docker returned error. Make sure Docker Daemon is running>

**Comment by chrmarti** [comment]
What do you get for (with the environment variables set):
```
docker version --format '{{.Server.Version}}'
echo $?
```

**Comment by dprasadk** [comment]
#### Thanks Chrmarti for taking up this issue

**Please find below details**

![image](https://user-images.githubusercontent.com/25827250/58115976-dbc9b700-7c18-11e9-9725-ab9d24d7bbf5.png)

**Comment by chrmarti** [comment]
What do you get for `which -a docker`? 🤔

**Comment by dprasadk** [comment]
![image](https://user-images.githubusercontent.com/25827250/58117611-99a27480-7c1c-11e9-9934-3a0d8245abc0.png)

**Comment by chrmarti** [comment]
When the error dialog is shown: Close the dialog and open the dev tools (Help > Toggle Developer Tools) to check if there is an error in the console.

**Comment by dprasadk** [comment]
#### Thank You Chrmarti
Cheers 👍 i found the solution, 

Earlier i have installed Docker Toolbox for windows, then later i have uninstalled Docker Toolbox and   installed Docker Desktop in my system.
Now when i am attempting to simulate the above example in vscode-insiders, i am getting a pop-up window saying **Make sure the docker daemon is running**".
What i noticed was .
>1- There was no default machine with default switches which was running on Hyper-V , because i believe when i start  working with container , behind the scenes its looking for virtual machine to run the container, in my case somehow the .docker/.........../default(machine)/ca.pem certificates was missing , moreover this path was created by default when i installed Docker Tools in the past and its supporting Virtual Box  which was not right. 
2. Secondly  while creation of Virtual Machines on Hyper-V i am getting below issues
 >![image](https://user-images.githubusercontent.com/25827250/58275056-c63bc500-7db1-11e9-8600-93f66741de1b.png)
3.  So i deleted two Virtual Box drivers still left out in C:/windows/system32/drivers by name [ VBoxNetAdp6.sys and VBoxNetLwf.sys ] 
4. Then i have restarted my V-Machine 
>![image](https://user-images.githubusercontent.com/25827250/58275539-e324c800-7db2-11e9-8cf0-f0d70dd5f7ea.png)
5 I ran eval $(docker-machine env default) for refreshing the environment.
6. Finally replicated the above scenario , where i am successfully able to create Dev-Container in my local, please find the screen snap
![image](https://user-images.githubusercontent.com/25827250/58276249-90e4a680-7db4-11e9-9887-a97fa5c99cb9.png)

Kind Regards,
D.Prasad

**Comment by chrmarti** [comment]
Thanks @dprasadk. Did you check if there was an error in the console and what it was? (Maybe we could improve this case by pointing to documentation on it.)

**Comment by dprasadk** [comment]
Hi @chrmarti , 

While trouble-shooting, i wouldn't found any issues in VScode-insiders **remote - container** docker extension, it was absolutely working fine. The actual [issue](https://github.com/microsoft/vscode-remote-release/issues/384) was from my end  in my system.

Will come back in case of any future issues.

Kind Regards,
@dprasadk
