### ISSUE TITLE
The window has crashed (reason: 'killed')

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-remote-release#3840]
- VSCode Version: Insiders 1.51.0 605bc4
- Local OS Version: Windows_NT x64 10.0.19041
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: WSL

I had VS Code + Remote WSL opened on a Ubuntu distro. I manually shut down Windows while VS Code was running, and upon restart received the following error:

![image](https://user-images.githubusercontent.com/1487073/95782154-1e63b780-0c84-11eb-8fc8-30a4cec12f13.png)

When I clicked on "reopen", VS Code updated in the background, but never restarted.

When I started VS Code manually, I received this error:

![image](https://user-images.githubusercontent.com/1487073/95782286-68e53400-0c84-11eb-9941-e42d04e9e8ed.png)

Retry -> Same error

I think the root problem was with WSL, as I had other similar issues to this: https://github.com/microsoft/WSL/issues/4377. From that issue I shutdown wsl (`wsl.exe --shutdown`) and then started it again. This fixed WSL and VS Code was able to connect again.

**Comment by aeschli** [comment]
Sounds like a WSL issue. Closing until we can reproduce.
