### ISSUE TITLE
Add X11 display forwarding for Docker containers

### ISSUE THREAD

**Issue by mpusz** [microsoft/vscode-remote-release#3841]
I would like to develop a GUI app in Docker and be able to run it on a local X Server. I was able to do it with a few workarounds here https://github.com/train-it-eu/irrlicht-example. The problem is that the behavior is not consistent among different Docker installations. On Windows (and probably Mac OS) I have to setup:

```json
"remoteEnv": {
  "DISPLAY": "host.docker.internal:0"
}
```

However, on Ubuntu I have to:

```json
"runArgs": [
  ...,
  "--net=host"
],
"remoteEnv": {
  "DISPLAY": ":0"
}
```

So I cannot provide one `devcontainer.json` file that would work for all the cases.

Is there a simpler way to do it? Could you please consider adding this as a VSCode feature? It would be cool to show that you can actually compile, run, and debug SuperTux on a docker container ;-)

GUI performance is also not the best here, but that is another story...

**Comment by chrmarti** [comment]
No solution at the moment for the IP address, but we see better performance when using VNC for developing VS Code in a container (and that avoids the IP address problem):
- https://github.com/microsoft/vscode/blob/master/.devcontainer/devcontainer.json
- https://github.com/microsoft/vscode-dev-containers/blob/master/repository-containers/images/github.com/microsoft/vscode/.devcontainer/base.Dockerfile

Note: On Linux `172.17.0.1` would also work. (https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal)

**Comment by mpusz** [comment]
Thanks for a prompt reply 👍 

> Note: On Linux 172.17.0.1 would also work.

Unfortunately, I was unable to forward X11 display with 172.17.0.1:0 and no `--net=host` 😢 

Could you please provide more information on how can I use VNC or noVNC to run or debug a C++ application having a GUI from within VSCode?

**Comment by chrmarti** [comment]
We don't have documentation on that, but you could copy the approach used in the above linked Dockerfile which is using this script to install VNC and dependencies: https://github.com/microsoft/vscode-dev-containers/blob/master/script-library/desktop-lite-debian.sh

**Comment by chrmarti** [comment]
I think this would be possible with reverse tunnels, marking as duplicate: https://github.com/microsoft/vscode/issues/100222
