### ISSUE TITLE
Dev Container names in Recent Workspaces are ambiguous

### ISSUE THREAD

**Issue by Trass3r** [microsoft/vscode-remote-release#3844]
- VSCode Version: 1.50
- Local OS Version: Win10 2004
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: WSL2

Steps to Reproduce:

1. after using a few different dev containers with similar layout check File->Open Recent or the 'Recent Workspaces' entries in the start menu or task bar context menu
2. it displays lots of ambiguous container entries like '/workspace [Dev Container]' instead of using the name given to the container in the devcontainer.json file

Does this issue occur when you try this locally?: No, WSL folders are fine too

**Comment by aeschli** [comment]
@chrmarti Not sure why you added the `wsl` tag.

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/3937.
