### ISSUE TITLE
Remote-SSH extension doesn't use the SSH agent

### ISSUE THREAD

**Issue by infokiller** [microsoft/vscode-remote-release#3845]
- VSCode Version:

```
1.50.0
93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
x64
```

- Local OS Version: `Arch Linux 5.8.12`
- Remote OS Version: `Ubuntu Linux 4.15`
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Generate an SSH key with a password and add it to an SSH agent (for example using `ssh-add ~/.ssh/id_ed25519_myhost`)
2. Configure SSH agent using `eval "$(ssh-agent -s)"` or `export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"`
3. Launch VSCode remote SSH, for example using `code --folder-uri 'vscode-remote://ssh-remote+hostname/src/username'`

After the last step, VSCode prompts me for a password in the integrated terminal, instead of asking the agent (which should launch a pinentry program externally to prompt me for a password).

**Comment by roblourens** [comment]
Are you sure vscode has that environment? You can try restarting vscode after setting this up or check in the integrated terminal

**Comment by infokiller** [comment]
OK, turns out it was an issue with SSH and firejail interaction, unrelated to VSCode.
