### ISSUE TITLE
Support Installing VSIX from CLI

### ISSUE THREAD

**Issue by adambattenburg** [microsoft/vscode-remote-release#385]
When working inside a remote docker container and trying to install a VSIX file through the CLI, I get the error `Ignoring option install-extension: not supported for code-insiders.`

However, when running the command (`code-insiders --install-extension /path/to/extension.vsix`) not inside a remote container, it functions as expected.

**Comment by egamma** [comment]
@adambattenburg as a workaround you can install the VSIX in the remote case from the Extension Viewlet > ... > Install from VSIX

**Comment by adambattenburg** [comment]
Thanks for the suggestion @egamma! That's what I'm doing currently, but it would be nice to have the full environment setup when building the container.

I thought about issuing the VSCode command to `install VSIX` from a script, but not sure that's possible. I'll look into it and update this issue if it's a good workaround.

**Comment by egamma** [comment]
@adambattenburg we have some documentation for how you can do this using vscode-containers, pls see https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host.

**Comment by not-much-io** [comment]
@egamma I was unable to find information on how to install an extension from the commandline while in remote mode at the link you supplied.

I think currently it isn't supporter?

Usecase: A developer working on making a VSCode plugin might have a neat workflow where they modify their code and run a single command to build, package and install their plugin for instant testing.

Currently without being able to install on the command line a manual step is needed for the install step.

**Comment by HotelCalifornia** [comment]
Same issue occurs when running VS code from inside WSL

**Comment by DavidSouther** [comment]
I just started using Github Codespaces and figured this was the perfect use for the `install` script in my user dotfiles.

**Comment by aramgre** [comment]
As a workaround, you can copy the vsix file to the extensions directory manually, for example in the `postCreateCommand`:
```
cd ~/.vscode-server/extensions && unzip /path/to/extension-name-1.0.0.vsix && mv extension extension-name-1.0.0
```
