### ISSUE TITLE
Add code command to PATH on remote session

### ISSUE THREAD

**Issue by kusnier** [microsoft/vscode-remote-release#3852]
I am using a linux vm on my local machine to develop. My vscode is running directly on my local machine (windows).
It would be nice when the code command will be automatically available in the path of the terminal.

Actually I have to pick up the right version of the command. But it is not clear which of them is the right one.

![image](https://user-images.githubusercontent.com/726429/91526990-24385000-e905-11ea-9d1f-4caf16668475.png)

![image](https://user-images.githubusercontent.com/726429/91526721-90ff1a80-e904-11ea-9939-1a2d3d383342.png)

**Comment by aeschli** [comment]
The integrated terminal in the remote window should have the command on the path. If not, can you check whether the PATH is overwritten for example by a startup script?

**Comment by kusnier** [comment]
> The integrated terminal in the remote window should have the command on the path. If not, can you check whether the PATH is overwritten for example by a startup script?

Thank you for the hint. My setup is always overwritting the PATH. This is the reason why I can not use the code command.

```sh
echo "before: $PATH"
set -gx PATH "/sbin"
prepend_to_path "/usr/sbin"
prepend_to_path "/bin"
prepend_to_path "/usr/bin"
prepend_to_path "/usr/local/bin"
prepend_to_path "/usr/local/sbin"
prepend_to_path "/usr/local/share/npm/bin"
echo "after: $PATH
```

Output:
```sh
before: /home/kuse/.fzf/bin /home/kuse/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/bin /home/kuse/bin/linux /home/kuse/bin/all /usr/local/sbin /usr/local/bin /usr/bin /bin /usr/sbin /sbin
after: /usr/local/sbin /usr/local/bin /usr/bin /bin /usr/sbin /sbin
Welcome to fish, the friendly interactive shell
```
A hint in the documentation could help that the PATH is extended by vscode. But maybe it's more common to takeover previous PATH instead of overwriting it by the own setup. My fault. Thank you 🙇
