### ISSUE TITLE
Remote-Containers Attach to Running Container gives error stream ended with 125

### ISSUE THREAD

**Issue by kzawad1** [microsoft/vscode-remote-release#3855]
- VSCode Version: 1.6.0
- Local OS Version: Ubuntu 20.04.1 LTS
- Remote OS Version: Ubuntu 18.04.4 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. From **Visual Studio Code**, select **View | Command Palette...**.
2. Enter text "Remote-Containers: Attach".
3. Select "Remote-Containers: Attach to Running Container...".
4. Wait for Visual Studio Code to connect to the target and get a list of containers.
5. Select the specific container.
6. Wait for the attach process to execute and the following error to be displayed:
```
[66480 ms] Start: Run in container: /home/user1/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/server.sh --disable-user-env-probe --port 0 --extensions-download-dir /home/user1/.vscode-server/extensionsCache
[70506 ms] Error: stream ended with:125 but wanted:1128865906
        at p (/home/user2/.vscode/extensions/ms-vscode-remote.remote-containers-0.145.0/dist/extension.js:1:247667)
        at /home/user2/.vscode/extensions/ms-vscode-remote.remote-containers-0.145.0/dist/extension.js:1:247837
        at s (/home/user2/.vscode/extensions/ms-vscode-remote.remote-containers-0.145.0/dist/extension.js:1:263154)
        at Socket.<anonymous> (/home/user2/.vscode/extensions/ms-vscode-remote.remote-containers-0.145.0/dist/extension.js:1:263327)
        at Socket.emit (events.js:228:7)
        at endReadableNT (_stream_readable.js:1185:12)
        at processTicksAndRejections (internal/process/task_queues.js:81:21)
[70508 ms] Remote-Containers server terminated (code: 126, signal: null).
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
What do you get when running `docker version`?

**Comment by kzawad1** [comment]
The development machine is:
```
user2@ubuntu:~$ docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
user2@ubuntu:~$ 
```

The target host in the cloud is:
```
user1@ip-x-x-x-x:~$ docker version
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Wed Oct 14 19:00:27 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Oct 14 16:52:50 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
user1@ip-x-x-x-x:~$ 
```

The versions are very similar.

**Comment by kzawad1** [comment]
Where exactly is the source code for this "vscode-remote-release".  This GitHub page does not have any source code.

**Comment by kzawad1** [comment]
I've added step-by-step instruction on how I got this error:
https://drive.google.com/file/d/1cfCifanMXZ7Xyl_6mI8QMImK_ejv_W11/view?usp=sharing

**Comment by PavelSosin-320** [comment]
@kzawad1 Some more deep digging steps for testing of remotely running container:
1.Docker info will say more info and, important!, Which port the daemon listens:
WARNING: API is accessible on http://0.0.0.0:2375 without encryption. Num of running containers.
2. Docker ps will provide Container id for further steps -> containerid
3. Docker top containerid will show if bush is running and opened TTY. Otherwise, "pipe is ended"? Unfortunately, -t only allocates TY but doesn't promise that it is opened inside the container.
4. Docker container ls with the filter or --last to know the exit code if the container has exited before attach, due to starting failure.
5. Docker exec  containerid  /bin/bash pwd to see, mainly to see that container is responsible. - to isolate VSCode from testing.
If Docker engine is OK but the Container has problems try to restart the container. - cross fingers.

**Comment by chrmarti** [comment]
@kzawad1 Thanks for the detailed instructions. This seems to be a problem in one of the modules we use. Could you retry with VS Code Insiders (https://code.visualstudio.com/insiders/) and the latest Remote-Containers (0.149.0) to see if that has been fixed in the latest versions?

**Comment by kzawad1** [comment]
@chrmarti looks great.  Not getting that specific error anymore.

**Comment by chrmarti** [comment]
@kzawad1 Thanks for confirming this is fixed!
