### ISSUE TITLE
Can't connect to remote servers via Remote SSH

### ISSUE THREAD

**Issue by photuris5** [microsoft/vscode-remote-release#3856]
Issue Type: <b>Bug</b>

After the latest update 1.50.1 update I can not connect to our remote servers. 
I enter my password and then a few seconds later it wants my password again. Does not connect. 

Extension version: 0.55.0
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.47GB free)|
|Process Argv|--crash-reporter-id f702a929-f00f-4df2-b2e5-fd2a2d98cdd6|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by photuris5** [comment]
Reverted back to version 1.49 and remote ssh works again.

**Comment by Clem-** [comment]
I managed to get it working on 1.50.1 by disabling `Remote.SSH: Remote Server Listen On Socket` and running the command `Kill VS Code Server on Host`.

**Comment by ulvido** [comment]
same here. cant connect with remote ssh development to my raspberry after 1.50.1 update.

**Comment by imxxw** [comment]
I encountered the same problem, this is my solution:
Remove all the log files in the folder ".vscode-server" on your remote server. Then run vscode client, connect to the remote server , it works again.

**Comment by ulvido** [comment]
> I encountered the same problem, this is my solution:
> Remove all the log files in the folder ".vscode-server" on your remote server. Then run vscode client, connect to the remote server , it works again.

unfortunately it doesn't for me :(

**Comment by m-kratochvil** [comment]
Same issue here, running VS Code on Win10, connecting to remote Linux server.
This was working fine until the upgrade to 1.50, after which starting the remote VSCode server failed and extension repeatedly asked for password.

Solution described by @imxxw worked, I deleted all the `.log` files in the `.vscode-server` folder, AND also everything in the `.vscode-server/data/logs/` folder

**Comment by chrismjones** [comment]
Same issue. Win 10 to remote Ubuntu 20 server. Deleting the logs only did not work for me. I deleted the entire .vscode-server directory before VS Code would remote to the server. Then later in the day could not reconnect again and again deleting the directory allows me access.

**Comment by ulvido** [comment]
> Same issue. Win 10 to remote Ubuntu 20 server. Deleting the logs only did not work for me. I deleted the entire .vscode-server directory before VS Code would remote to the server. Then later in the day could not reconnect again and again deleting the directory allows me access.

this works. deleting all files in ".vscode-server" folder and after that making a connection attemt makes remote machine redownload the server files. this fixes the problem for me.

**Comment by photuris5** [comment]
I cannot remove the vscode-server folder because it states that the device or resource is busy.  This is now not working on 1.49 version or 1.50.1.
Any ideas?

**Comment by ulvido** [comment]
> I cannot remove the vscode-server folder because it states that the device or resource is busy. This is now not working on 1.49 version or 1.50.1.
> Any ideas?

not the folder itself. try to remove all the things inside?

**Comment by photuris5** [comment]
> > I cannot remove the vscode-server folder because it states that the device or resource is busy. This is now not working on 1.49 version or 1.50.1.
> > Any ideas?
> 
> not the folder itself. try to remove all the things inside?

I went into the .vscode-server/data/logs/ and there are 2 folders that will not delete because they are in use. Thanks for any help.

**Comment by photuris5** [comment]
> > > I cannot remove the vscode-server folder because it states that the device or resource is busy. This is now not working on 1.49 version or 1.50.1.
> > > Any ideas?
> > 
> > 
> > not the folder itself. try to remove all the things inside?
> 
> I went into the .vscode-server/data/logs/ and there are 2 folders that will not delete because they are in use. Thanks for any help.

I now get an error: The VS Code Server failed to start.

**Comment by ulvido** [comment]
both sides needs to be latest version?

23 Eki 2020 Cum 00:41 tarihinde Gina Wilson <notifications@github.com> şunu
yazdı:

**Comment by photuris5** [comment]
Okay everyone, try this. 
In the VS Code Command Palette, run "kill VS Code Server on Host". Once I did that, I was able to connect using 1.50.1 with no issues.  *Fingers crossed* 
Thank you @ulvido for your assistance!

**Comment by roblourens** [comment]
Please try again and share the full log from the Remote-SSH output channel after running the "kill" command
