### ISSUE TITLE
I cannot set a new SSH Host

### ISSUE THREAD

**Issue by proguy914629-discord** [microsoft/vscode-remote-release#3862]
Issue Type: <b>Bug</b>

I cannot set a new SSH Host in my Mac...

Extension version: 0.55.0
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 5|
|Memory (System)|8.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id 2875edea-d146-436a-9f76-1bec98874b40|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bamurtaugh** [comment]
Hey @proguy914629-discord, what happens when you try to set a new SSH Host? Are you seeing an error message?
