### ISSUE TITLE
100% CPU load by remote node process

### ISSUE THREAD

**Issue by vpas88** [microsoft/vscode-remote-release#3863]
- VSCode Version: 1.50.1
- Local OS Version: Windows_NT x64 10.0.17763
- Remote OS Version:  Ubuntu 16.04.7 LTS (Linux 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l armv7l armv7l GNU/Linux)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Configure remote ssh connection to a raspberry pi (Linux 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l armv7l armv7l GNU/Linux)
2. Check CPU usage by vscode-server node processes 

Does this issue occur when you try this locally?: n/a
Does this issue occur when you try this locally and all extensions are disabled?: n/a

**Comment by vpas88** [comment]
Reverting to VS Code 1.49 (August 2020 release) solved the problem!

**Comment by roblourens** [comment]
Need more info about what you are actually seeing
