### ISSUE TITLE
Fails to 'git push' - Invalid Certificate Format

### ISSUE THREAD

**Issue by ooobii** [microsoft/vscode-remote-release#3864]
- VSCode Version: 1.50.0
- Local OS Version: Ubuntu 20.04 LTS (Kernel: 5.4.0-47-generic)
- Remote OS Version: Ubuntu 20.04 LTS (Kernel: 5.4.0-51-generic)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open VS Code, connect to stored host profile, and open a folder containing code committed to a GitHub repository.
2. Open the terminal, and verify that the session the terminal has started belongs to the remote machine.
3. execute the command `git pull origin master`, or `git push origin master`.
The output is:
```
❯ git pull origin master
Load key "/home/oobi/.ssh/id_rsa.pub": invalid format
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
This is very odd, being that running the command directly on the remote machine works perfectly fine.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by ooobii** [comment]
It seems as though the setting for "Remote.SSH: Enable Agent Forwarding" is not working properly. In the settings of VSCode of the local machine that connects to the remote machine, I had the property set to enabled (default).

After realizing this wasn't working, I added an host entry to my `/etc/ssh/ssh_config` file to explicitly enable agent forwarding for that particular host:
```
Host VICTORIA
    ForwardAgent yes
```

Once this was added, I had quit and restarted VS Code. Still, no avail.
Next, I had set the "Remote.SSH: Config File" property from blank (default) to `/etc/ssh/ssh_config`.

Once again I quit VS Code, restarted, and attempted the steps listed in the original issue post, and was able to successfully use my key to access GitHub.

I'm not sure if this was machine specific, or if the properties set in the "Settings" page of VSCode are not working as they should.

**Comment by roblourens** [comment]
Not clear what the problem is or whether vscode is involved. If this relies on agent forwarding to work, then you need forwarding enabled in your ssh config.

**Comment by seriema** [comment]
This just started happening today after VS Code was updated to the October release. I've been using my devcontainer just fine for months.

**Comment by ooobii** [comment]
> Not clear what the problem is or whether vscode is involved. If this relies on agent forwarding to work, then you need forwarding enabled in your ssh config.

>... or if the ["Remote.SSH: Enable Agent Forwarding"]properties set in the "Settings" page of VSCode are not working as they should.

**Comment by roblourens** [comment]
> Next, I had set the "Remote.SSH: Config File" property from blank (default) to /etc/ssh/ssh_config.

It sounds like ssh on your system was not looking at this config file until we told it to look at that config file. But it is a default one and should be considered automatically, from what I understand. It's likely that this would work if you used your user config file instead of the system one, but could you share the log from the Remote-SSH output channel, without that Config File setting set, so I can see which ssh is used and see whether there are any clues about why it does not use that config file?
