### ISSUE TITLE
Cannot connect via ssh

### ISSUE THREAD

**Issue by offgabriele** [microsoft/vscode-remote-release#3865]
I'm trying to connect to a Raspberry Pi 4 via Visual Studio Code. I downloaded the Insider version and the Nightly version of Remote-SSH. Via terminal i'm able to connect to the Pi without any problem with private key autentication. However when i connect using vs code it asks me the os, After a while the green banner says i'm connected to host but open a file shows my pc storage and the terminal won'open. Reading online i added `"remote.SSH.showLoginTerminal": true` and the result is that this shows up
```
7946c7511e4d: running
Acquiring lock on /home/pi/.vscode-server-insiders/bin/89c002ab02f87102d91efc83c191ef1174756c6a/vscode-remote-lock.pi.89c002ab02f87102d91efc83c191ef1174756c6a
Found existing installation at /home/pi/.vscode-server-insiders/bin/89c002ab02f87102d91efc83c191ef1174756c6a...
Checking /home/pi/.vscode-server-insiders/.89c002ab02f87102d91efc83c191ef1174756c6a.log and /home/pi/.vscode-server-insiders/.89c002ab02f87102d91efc83c191ef1174756c6a.pid for a running server
Looking for server with pid: 7323
Found running server...

*
* Reminder: You may only use this software with Visual Studio family products, 
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
*

Checking server status on port 35445 with wget
7946c7511e4d: start
sshAuthSock====
listeningOn==35445==
osReleaseId==raspbian==
arch==armv7l==
webUiAccessToken====
tmpDir==/run/user/1000==
platform==linux==
7946c7511e4d: end
channel 3: open failed: administratively prohibited: open failed
channel 3: open failed: administratively prohibited: open failed
channel 4: open failed: administratively prohibited: open failed
```

then the remote keeps spining until it says `SSH: raspberrypi` and two error pops out:
`Could not fetch remote environment`
`Failed to connect to the remote extension host server (Error: Time limit reached)`

- VSCode Version: 1.51.0-insider
- Local OS Version:  Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
- Remote OS Version: 
`
Static hostname: raspberrypi
Icon name: computer
Machine ID: 80f207e057db45d5b0df095bca5dc131
Boot ID: 2fe35fc37dd64b71b99d06ad71b57405
Operating System: Raspbian GNU/Linux 10 (buster)
Kernel: Linux 5.4.51-v7l+
Architecture: arm`
- Remote Extension/Connection Type: SSH

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Make sure tcp forwarding is enabled on your ssh server, that explains the error
