### ISSUE TITLE
Remote SSH times out during password login with `ProxyJump`

### ISSUE THREAD

**Issue by samuela** [microsoft/vscode-remote-release#3867]
Version: 1.50.0
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:01:33.073Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic

- VSCode Version: 1.50.0
- Local OS Version: Ubuntu
- Remote OS Version: Ubuntu
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Have an SSH host with a `ProxyJump`:
```
Host myhost1
 HostName ssh.redacted.com
 User skainswo
 ProxyJump myproxy

Host myproxy
 HostName myproxy.redacted.com
 User skainswo
```
and `myproxy` requires password authentication.
2. `Remote-SSH: Connect to Host...` and select `myhost1`.
3. Don't input any thing in the password dialog and just wait for a few seconds.
4. Notice the "Could not establish connection to "myhost1": The connection timed out." error dialog.

The same thing may happen with general password authentication and no `ProxyJump` but I haven't tested that.

Does this issue occur when you try this locally?: n/a
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
You should have enough time to type a password. If this is happening really quickly, please share the log from the Remote-SSH output channel.

**Comment by samuela** [comment]
@roblourens But why does the timeout start before the password has been entered? That doesn't really make any sense to me. And it's annoying with long passwords, etc.

**Comment by roblourens** [comment]
It should be like... a minute or more? Sounds like that's not what you're seeing, so maybe the log would help me understand what's happening.

**Comment by samuela** [comment]
Ok I'll have to check those logs and send them over.
