### ISSUE TITLE
 Open Workspace in Container... improve support for multi root workspaces

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#387]
Currently opening a `.codeworkspace` in a container is a two step process.  First you "Open Folder in Container", then File > Open Workspace (or by clicking the button in the toast that appears.)

This is partly because we do not currently support opening folders without a common root in a container or opening multiple containers at once.  A workspace file could include multiple folders in entirely different parts of the local filesystem and each of these folders could have their own devcontainer.json files.

To start, we could support an open workspace command that is the equivalent of doing "Open Folder in Container" followed by "Open Workspace" but does not resolve these two limitations.  Specifically it would:

1. Look for a `.devcontainer/devcontainer.json` or `.devcontainer.json` file in the same folder as the `.codeworkspace` file.
2. Mount this folder into the container and open the workspace. The `.codeworkspace` file would only be able to reference sub-folders.

**Comment by chrmarti** [comment]
One more assumption we make for the Docker Compose case is that the workspace file is inside the `"workspaceFolder"` given in the devcontainer.json. There is currently no other way to specify where the workspace file is mounted and the `"workspaceFolder"` property's name is not a great match. /cc @egamma @aeschli

**Comment by mtsmfm** [comment]
This issue doesn't allow us to open multiple containers in a single vscode window and just open multiple dir with only one container definition, correct?

**Comment by chrmarti** [comment]
@mtsmfm That's correct.

**Comment by mtsmfm** [comment]
@chrmarti Can I open an issue for this feature?

**Comment by chrmarti** [comment]
@mtsmfm Yes, thanks.

**Comment by mtsmfm** [comment]
Opend

https://github.com/microsoft/vscode-remote-release/issues/1460
