### ISSUE TITLE
Have multiple vscode windows open to the same WSL folder

### ISSUE THREAD

**Issue by cveld** [microsoft/vscode-remote-release#3871]
Currently there is no way to easily open up a new window of vscode on the same WSL folder.

Tried various routes:
1. In an open wsl session, click File -> New Window. This just opens a regular Windows local filesystem experience.
2. type `code .` in the folder, outside or inside vscode. This just brings focus to the existing instance of vscode with this particular folder.

My use case:
I would like to move a file view to my second monitor so that I can work on two files in the same repo at the same time.

```
code -v

1.50.0
93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
x64
```

**Comment by aeschli** [comment]
This is actually a VSCode restriction: Issue is https://github.com/microsoft/vscode/issues/2686.

**Comment by cveld** [comment]
@aeschli well not completely black/white here. Because for local files it is easy to create a new window and drag files into it, or open additional files from the same local repository.

Not so with WSL.

**Comment by aeschli** [comment]
> Not so with WSL.

Can you elaborate what's missing? I just tried, dragging single files from one remote window into a second window is working. You need to make sure that window is a remote window from the same distro as well. You can also use the file menu or the command line in the integrated terminal.

**Comment by cveld** [comment]
@aeschli When I create a new window from a vscode session that is attached to remote wsl session, the new window is just a regular vscode session. How do I create a new window that is attached to the same remote wsl distro?

**Comment by aeschli** [comment]
Yes, that's it. At some point we also had File > New Window open the same remote window of the same distro. The problem was that some users couldn't find a way to open a non remote window anymore. You would have to to a 'close connection' on the window.
So I'm in favor of keeping the current solution.

**Comment by cveld** [comment]
@aeschli Can the WSL Remote extension just add another entry to the file menu? Then you get two items or nested items:
* Open new window
* Open new window and connect to WSL remote

Another suggestion would be to go for a launcher dialog initially where a user can set defaults:
* "Always show this launcher yes/no"
* "When connected to WSL new window also connect to WSL yes/no"
* Include some help text with actionable links that there are commands in the palette for this behavior as well. Clicking a link will populate the command search box.

This provides at least some UX guidance for new users like me.

**Comment by aeschli** [comment]
Please file a feature for a `New WSL Window` menu entry...
