### ISSUE TITLE
Keychain isn't unlocked when using git repos with the osxkeychain credential helper when connecting remotely

### ISSUE THREAD

**Issue by SteelPhase** [microsoft/vscode-remote-release#3872]
Resolving this issue requires unlocking the macOS Keychain via the execution of `security unlock-keychain`. When that command is run a password is requested. Is there someway we can fix this so that the remote script can determine if the keychain should be unlocked. even a setting to execute it on connect would be useful.

I want it to be clear that there is a bug here, and we at least need to fix that part. The credentials being requested causes the stored credentials in keychain to be blown away. We at a minimum need to try and fix that.

- VSCode Version: v1.50.1
- Local OS Version: Windows 10 Version 2004 (OS Build 19041.572)
- Remote OS Version: macOS Catalina v10.15.7
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

while locally connected to the remote macOS machine

1.  setup git on remote computer to use the `osxkeychain` credential helper
2.  git clone a repo and store the credentials in the keychain.
3. Any future git command that requires authentication will used stored credentials to auth.

Connect over ssh using VSCode remote

1. Connect to cloned repo folder on Remote macOS machine
2. Attempt any authenticated git command
3. Credentials will be requested
4. If the credentials are ignored, or mistyped it causes the stored credentials to get erased.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes
This issue happens over a standard ssh connection as well.

**Comment by roblourens** [comment]
Do you know anything about this @joaomoreno @RMacfarlane 

I don't really understand what's happening here

> 3. Credentials will be requested
> 4. If the credentials are ignored, or mistyped it causes the stored credentials to get erased.

**Comment by SteelPhase** [comment]
i think it's Git's Credential-osxkeychain doing the clear. It's easy enough to get past if you just unlocked the keychain in the terminal.

**Comment by RMacfarlane** [comment]
For
> Credentials will be requested

Is this via a dialog in VS Code? Or from git in the terminal?

**Comment by SteelPhase** [comment]
VSCode redirects git authentication to a ui form that pops up near the top of the VSCode window.

**Comment by SteelPhase** [comment]
Does this still need more info? I'm assuming this is what the bot is complaining about.

**Comment by roblourens** [comment]
Can you help @RMacfarlane or @eamodio, I have no idea what's going on

**Comment by SteelPhase** [comment]
bad bot

**Comment by kigawas** [comment]
Same here. I have to work it around by `git config --global credential.helper store`

**Comment by roblourens** [comment]
I still don't fully understand but it seems like this is essentially an issue for the git extension

**Comment by SteelPhase** [comment]
This is a situation that will only occur with the Remote SSH extension. Past saying it's actually an issue, I don't know where it would best to fix. I would assume this would be the best place to attempt to fix it. unless we want to toss weird edge case solutions into other extensions to support vscode remote.
