### ISSUE TITLE
Auto-fill filename when downloading file

### ISSUE THREAD

**Issue by WurmD** [microsoft/vscode-remote-release#3880]
Issue Type: <b>Feature Request</b>

**Steps to reproduce:**
- Right click file 
- click Download

**Actual behavior:**
Download File window appears with empty "File name:" field

**Desired behavior:**
Download File window appears with "File name:" field filed with filename

Extension version: 0.55.0
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.15.0-118-generic

**Comment by coisox** [comment]
How to upvote? I really need "download" features so I don't need to open WinSCP to download updated file
