### ISSUE TITLE
Move dotfiles installation to after the postCreateCommand

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#3882]
Discussed with Codespaces (https://github.com/MicrosoftDocs/vscodespaces/issues/811) and it makes sense to move dotfiles installation ("personalization") after the postCreateCommand ("customization").

To still enable access to Git repositories, we can set the credentials helper early at the system level (and then again after installing dotfiles or copying the local `.gitconfig` at the local level as we do now).

ssh-agent forwarding and copying of the local `.ssh/known_hosts` can still be done early to allow using Git with ssh remotes.

This will also align Remote-Containers with Codespaces and ensure that the same DevContainer configuration can run on both unchanged.

/cc @felipecrs @jkeech @lostintangent

**Comment by felipecrs** [comment]
I think redoing the configuration before running the `postCreateCommand` and after running `dotfiles` should work for most cases. 

By the way, [I also set the credential helper at the system level in my dotfiles](https://github.com/felipecrs/dotfiles/blob/master/run_once_setup.sh#L201). Fortunately, I skip that when I'm running in a devcontainer.

**Comment by chrmarti** [comment]
Available in 0.146.0 of the extension (for VS Code Insiders).

**Comment by rzhao271** [comment]
@chrmarti what's a way to verify this issue?

**Comment by chrmarti** [comment]
To verify:
- Have a devcontainer.json with `"postCreateCommand": "echo postCreateCommand >>~/dotfiles-test.txt"`.
- Add user setting `"dotfiles.repository": "chrmarti/dotfiles-test"`.
- Rebuild container and verify `~/dotfiles-test.txt` contains `postCreateCommand` before `dotfiles-test`.
