### ISSUE TITLE
ssh default setting for adding ssh target switching user 

### ISSUE THREAD

**Issue by mortifia** [microsoft/vscode-remote-release#3883]
xxxx and yyyy are chosen for the persistence of the explanation.
yyyy is the same yyyy until the end.

step to reproduce:
- adding ssh connection with url not ip and user ex: "ssh xxxx@aaa.bbb-ccc.com:hhhh"
- store setting to : c:\User\yyyy\\.ssh\config
config file example :
```
Host aaa.bbb-ccc.com:hhhh
  HostName aaa.bbb-ccc.com:hhhh
  User xxxx
```
- when I try to log-in he asks me for the password of yyyy
- and he fail to log-in

step to debug:
- modify config file same here :
```
Host xxxx@aaa.bbb-ccc.com:hhhh
  HostName xxxx@aaa.bbb-ccc.com:hhhh
  User xxxx
```
- when I try to log-in he asks me for the password of xxxx
- and he sucess to log-in

i dont know why this use other username ¯\\_(ツ)_/¯

ps: this is one of the other username i use but i never used it for this url and in vsCode :/
ps2: all work fine with ip 🤷‍♂️

**Comment by ItalyPaleAle** [comment]
What happens if you type in the command line (not in VS Code): `ssh xxxx@aaa.bbb-ccc.com:hhhh` , with both configurations?

**Comment by mortifia** [comment]
with win ssh y got this:
```
ssh aaaa-bbbb.cccc.com -p hhhh
yyyy@aaaa-bbbb.cccc.com's password:
```
```
ssh aaaa-bbbb.cccc.com -p hhhh -l xxxx
xxxx@aaaa-bbbb.cccc.com's password:
```
```
 ssh xxxx@aaaa-bbbb.cccc.com -p hhhh
xxxx@aaaa-bbbb.cccc.com's password:
```

**Comment by roblourens** [comment]
Does it work if the Host is not the same as HostName in the first example?
