### ISSUE TITLE
Session Crashes When Renaming a File

### ISSUE THREAD

**Issue by traumasv** [microsoft/vscode-remote-release#3885]
- VSCode Version: vscode 1.50.1
- Local OS Version: Windows 10 Version 1903 x64
- Remote OS Version: Ubuntu 16.04.6
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. ssh on to the remote machine and workspace
2. rename a file

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

The session crashes and remote ssh requires me to authenticate again whenever i try to change the name of a file in the remote directory.

**Comment by roblourens** [comment]
Please give more details
