### ISSUE TITLE
Can't close tabs after git pull

### ISSUE THREAD

**Issue by roneicostajr** [microsoft/vscode-remote-release#3888]
Issue Type: <b>Bug</b>

After pull from git repository, open files that should be updated by the incoming changes do not show changes and cannot be closed.

Extension version: 0.55.0
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 5.4.0-51-generic
Remote OS version: Linux x64 5.0.0-1033-gcp

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 3343)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|15.49GB (3.97GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 100392d9-f44d-4c39-8f2d-03af6f35b1cf|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: 34.95.XXX.XXX|
|OS|Linux x64 5.0.0-1033-gcp|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (1 x 2200)|
|Memory (System)|1.65GB (0.12GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment]
Is this in a Remote-SSH window?

**Comment by bamurtaugh** [comment]
Possibly related? https://github.com/microsoft/vscode-remote-release/issues/3644

**Comment by roblourens** [comment]
>and cannot be closed.

Please expand on this, you click the tab `x` and what happens? Do you see any errors in developer tools (Help > Toggle Developer Tools)?

**Comment by roneicostajr** [comment]
> Is this in a Remote-SSH window?

Yes, it is. I'm currently using it to SSH into my GCP machine.



> > and cannot be closed.
> 
> Please expand on this, you click the tab `x` and what happens? Do you see any errors in developer tools (Help > Toggle Developer Tools)?

When I click the tab `x` it's completly unresponsive, I didn't use Dev Tools (I'll have a look at it next time) but didn't see any errors on the Output or Problems tabs. After further use I also noticed that the issue might not be related only to git pulls but in fact to any change I make to the VM files. 
G Cloud shows a spike of CPU usage every time I lose responsivity and often I lose the connection a couple of minutes later. If the connection is lost with Code still open:

1. I can't reconnect.
2. I have to use terminal to `pkill` code or else it won't close.
3. I have to stop/start my VM or else it'll be locked in around 40% CPU usage, which is very unusual since it's usually under 1%.

**Comment by roblourens** [comment]
@alexdima why would the client go unresponsive when a bunch of a files change on the remote?

**Comment by alexdima** [comment]
@roblourens I don't know. It is possible that the explorer or some other piece in our UI receives very many file change events and so many events come in that the code dealing with them ends up freezing the UI. I remember we have seen this in the past, but this can only be troubleshooted by profiling the renderer process when the issue occurs.

**Comment by roblourens** [comment]
@roneicostajr do you notice some high cpu process in the client too when this happens? You can try to collect a perf trace, although if the UI never becomes responsive again it might not complete.

- In devtools (Help > Toggle Developer Tools), find the Perf tab
- Click the record button
- Reproduce the issue
- Stop recording, save the log, upload it here

**Comment by roneicostajr** [comment]
[Profile-20201124T131110.zip](https://github.com/microsoft/vscode-remote-release/files/5591206/Profile-20201124T131110.zip)


Sorry about the delay, I had some problems the past week. I recorded as soon as I noticed the error occured and let it try reconnection a couple of times.

**Comment by alexdima** [comment]
@roneicostajr I have looked at the profile, but I think you captured a profile while the UI was disconnected from the remote side. So the recording appears to be of the reconnection dialog, and from looking at the profile, there appears to be nothing wrong. Perhaps there was something before the reconnection kicked in?
