### ISSUE TITLE
The setting to disable the "Help and feedback" bar is not remembered

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode-remote-release#3892]
#### VSCode Version:
```
Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```
#### Local OS Version:
```
Windows 10 v. 2004
```
#### Remote OS Version:
```
Ubuntu 20.04
```
#### Connection Type: 
```
WSL
```

#### Steps to Reproduce:

While i disable this option:
![obraz](https://user-images.githubusercontent.com/30685349/96871674-e70abd00-1472-11eb-8eee-b032675d017d.png)
unfortunately it comes back the next time vscode is run.
It shouldn't work that way. All configurable VSCode bars remember this setting.
Maybe this is not a big problem, but you also need to take care of the details ;-)

----

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by alexr00** [comment]
I'm not able to reproduce this issue. The disablement of "Help and Feedback" is per workspace. If you open another workspace, it will be back. If you open the same workspace where you already disabled it, it stays gone.
