### ISSUE TITLE
devcontainer.jscon "${localEnv:VAR_NAME}" read only first word if VAR_NAME variable has spaces

### ISSUE THREAD

**Issue by viniciuslln** [microsoft/vscode-remote-release#3893]
Hello, I'm trying to pass local environment variables to container but only first word are read from the local variable with spaces 

- VSCode Version: 1.50.1
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Docker/WSL

Steps to Reproduce:

1. set variabel on `~/.bashrc` `export VAR_NAME="SOME VAR WITH SPACES" ` 
2. configure `devcontainer.json` like:
```
"containerEnv": {
    "VAR_NAME ": "\"${localEnv:VAR_NAME }\"",
},
``` 
or 

```
"build": {
   "dockerfile": "Dockerfile",
        "args": {
	    "VAR_NAME ": "${localEnv:VAR_NAME }",
        }
},
```
3. IN CONTAINER: reading env (or read arg in Dockerfile) `echo "$VAR_NAME "` prints only `SOME `

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by chrmarti** [comment]
There are spaces after `VAR_NAME` in your configuration:
```
"VAR_NAME ": "\"${localEnv:VAR_NAME }\"",
```

Replacing that with the following makes it work:
```
"VAR_NAME": "\"${localEnv:VAR_NAME}\"",
```

**Comment by viniciuslln** [comment]
Sorry it is a typo when I create this issue.

> 
> Replacing that with the following makes it work:
> 
> ```
> "VAR_NAME": "\"${localEnv:VAR_NAME}\"",
> ```

Unfortunately, that doesn't solve it since it's not the problem I had.

**Comment by chrmarti** [comment]
@viniciuslln I then got the value with spaces in the integrated terminal inside the container. Does that not work for you?

**Comment by viniciuslln** [comment]
@chrisdias Yes, in container's terminal `echo $VAR_NAME` or `echo "$VAR_NAME"` the prints the correct value
