### ISSUE TITLE
Forwarded port rendered without an access address

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#3894]
- 'Remote Containers Try a Sample' -> Node
- `npm install`
- `npm start`
- The port 3000 is correctly scrapped from the console
- There is also a port 39393 detect
This port is rendered without a local access port. 

![image](https://user-images.githubusercontent.com/172399/96900513-78d5f280-1492-11eb-977f-f4b859a5e3cd.png)

**Comment by alexr00** [comment]
@egamma where is 39393 coming from? I don't see where in the try node sample it is.

**Comment by alexr00** [comment]
Figured out what was going on. Fixed by d18f310cfe483fb26014a40b0d5ea3943c9fd448
