### ISSUE TITLE
Ability to forward a range of ports to container

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-remote-release#3898]
Originally from @peredwardsson here: https://github.com/microsoft/vscode-docker/issues/2433

Also related: #1386, especially [this comment](https://github.com/microsoft/vscode-remote-release/issues/1386#issuecomment-656803141)

Issue Type: <b>Feature Request</b>

I'm working with robotics using the ROS ecosystem. In it, you can create services that act as functions that can be called to by other parts of the system. The services are assigned a predetermined IP and a random available port somewhere above 30000. This makes developing in a container frustrating, since I have to manually forward the port of the day into the container. EXPOSE-ing the port in the Dockerfile doesn't help, nor does using "runArgs": ["--expose=30000-65535"] in the devcontainer.json.

I would like to be able to add such a range of ports to the forwardPorts field of devcontainer.json, such that I could use
`"forwardPorts": [30000-65535]`
or
`"forwardPorts": [30000:]` (for "30000 onward")
or maybe even
`"forwardPorts": [*]` (for "all ports")

To the best of my abilities, this doesn't seem doable at the moment. Happy to answer questions should they pop up.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 5.4.0-51-generic snap

**Comment by chrmarti** [comment]
@peredwardsson Would using the host's network be an option? (https://docs.docker.com/network/network-tutorial-host/)

**Comment by peredwardsson** [comment]
Yes, and it does solve the immediate problem, thanks.

**Comment by PavelSosin-320** [comment]
This is not a VSCode feature, this is ContainerNetworkingInterface feature with numerous dependencies. Now docker run -p and docker run --expose are supported. If it is not enough dependencies are from Linux Kernel to Google agreement to change Docker interface because Dcker is Kubernetes Container engine.
