### ISSUE TITLE
Disconnected from WSL

### ISSUE THREAD

**Issue by mariela21180** [microsoft/vscode-remote-release#3899]
Issue Type: <b>Bug</b>

I frequently get the message "Disconnected from WSL: Ubuntu-20.04".

Only after restart the service "LxssManager" it is able to re-connect.

This happens since a couple of days ago. Before it was working normally.

I think that the issue could be related with this Windows update: https://support.microsoft.com/es-es/help/4578968/kb4578968-cumulative-update-for-net-framework

Extension version: 0.50.1
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (20.23GB free)|
|Process Argv|--crash-reporter-id 0c119745-0a6d-45ec-a4f3-b7b39223f62b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (2 x 2904)|
|Memory (System)|2.92GB (0.11GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment]
That sounds like a WSL issue. Can you file it against https://github.com/microsoft/wsl ?
