### ISSUE TITLE
Container-specific settings aren't updated

### ISSUE THREAD

**Issue by SebastianGrans** [microsoft/vscode-remote-release#3900]
- VSCode Version: 1.50.1
- Local OS Version: Ubuntu 20.04
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

**`Dockerfile`**:  
```
FROM ubuntu
```

**`devcontainer.json`**
```json
{
	"name": "Existing Dockerfile",
	"context": "..",
    "dockerFile": "../Dockerfile",
	"settings": { 
		"editor.rulers": [79],
		"terminal.integrated.shell.linux": "/bin/bash"
	},
	"runArgs": [
		"--rm",
		"--user", "1000:1000",
		"-e", "DISPLAY=${env:DISPLAY}",
		"-v", "/etc/group:/etc/group:ro",
		"-v", "/etc/passwd:/etc/passwd:ro",
    	        "-v", "/etc/shadow:/etc/shadow:ro",
    	        "-v", "/etc/sudoers.d:/etc/sudoers.d:ro",
		"-v", "/tmp/.X11-unix:/tmp/.X11-unix:rw",
		"-v", "${localWorkspaceFolder}:/home/<user>/", 
    	        "--workdir", "/home/<user>/"
	]
}
```

1. With the above specified files, run `Reopen in container`. It works and shows a ruler at the 79 characters mark.
2. Edit `devcontainer.json` and add another ruler e.g. `[79, 120]`.
3. `Rebuild and reopen in container`. The new ruler does not appear. 

**Workaround:**  
By deleting the `.vscode` folder and reopen in container, the new settings are applied.

**Comment by chrmarti** [comment]
Settings in `.vscode/settings.json` take precedence over the machine settings (initialized from the `devcontainer.json`). I assume your `.vscode/settings.json` had an `editor.rulers` entry?

**Comment by SebastianGrans** [comment]
Locally I have no `editor.rulers`.

The first time I run the container as described in my first post, the file `.vscode-server/data/Machine/settings.json` gets populated with: 

```json
{
	"editor.rulers": [
		79
	],
	"terminal.integrated.shell.linux": "/bin/bash"
}
```
And rulers are present while editing files (inside the container). If I change it to `"editor.rulers": [79, 120],` in the `devcontainer.json` and rebuild/restart the container, then `.vscode-server/data/Machine/settings.json` is not updated. I.e. no new ruler is added.

**Comment by chrmarti** [comment]
Is `~/.vscode-server` mounted on a persistent storage (bind / volume)? If so: We only write the settings when there is no `.writeMachineSettingsMarker` file in the same folder as the setting.json, you could delete that and the rebuild.

**Comment by SebastianGrans** [comment]
Aha! That explains it. 

But this creates another issue. If I instead mount the folder in `/home/<user>/workspace`, then `/home/<user>/workspace` is owned by `<user>` while `/home/<user>/` is owned by `root` which means that VS Code can't create the `/home/<user>/.vscode-server` since Docker is running as `<user>`. 
```
[1683 ms] mkdir: cannot create directory '/home/<user>/.vscode-server': Permission denied
```

If you try to add this folder during building
```
ARG USER=<user>
RUN mkdir -p /home/$USER/ \ 
        /home/$USER/ \
    && chown -R $USER \
        /home/$USER/ \
        /home/$USER/
```
you get 
```
chown: invalid user: '<user>'
```
since `passwd` is not yet mounted. 
I think all this is caused by how I am sort of adding my own user by adding the `passwd`/`shadow` files. 
If instead I would use the approach explained in the [documentation](https://code.visualstudio.com/docs/remote/containers-advanced#_adding-a-nonroot-user-to-your-dev-container) it would probably not have happened. Since `useradd` would create `/home/<user>/` with the right permissions.

An alternative approach could be to manually create that folder using `mkdir` and `chown` in the `Dockerfile`:

**Conclusion**  
Don't do it the way I did it. The reason I did it this way is because I wanted to be able to access the X server on the host machine. As explained on the [ROS Wiki](http://wiki.ros.org/docker/Tutorials/GUI). It works great if you are running from the terminal, but the VS Code adds an additional layer of complexity. 

But if you want to run a similar setup. I.e. a docker image that does not contain the user, while also automatically updating the VS Code settings on rebuild, you need the following setup: 

**`Dockerfile`**  
```Dockerfile
FROM ubuntu

ARG USER=<user>
ARG UID=<uid>
ARG GID=<gid>
RUN echo "$USER:x:$UID:$GID:$USER,,,:/home/$USER:/bin/bash" >> /etc/passwd # Temporarily "add" a user. 
RUN mkdir -p /home/$USER/ \ # Create the user folder 
        /home/$USER/ \
    && chown -R $USER \
        /home/$USER/ \
        /home/$USER/
```

**`devcontainer.json`**  
```json
{
	"name": "Existing Dockerfile",
	"context": "..",
        "dockerFile": "../Dockerfile",
    
	"workspaceMount": "source=${localWorkspaceFolder},target=/home/grans/,type=bind,consistency=cached",
	"workspaceFolder": "/home/grans/",
	"runArgs": [
		"--rm",
		"--user", "1000:1000",
		"-e", "DISPLAY=${env:DISPLAY}",
		"-v", "/etc/group:/etc/group:ro", 
		"-v", "/etc/passwd:/etc/passwd:ro",
    	        "-v", "/etc/shadow:/etc/shadow:ro",
    	        "-v", "/etc/sudoers.d:/etc/sudoers.d:ro",
		"-v", "/tmp/.X11-unix:/tmp/.X11-unix:rw",
	]
}
```

**Comment by chrmarti** [comment]
You can use numeric ids with chown, e.g. `chown -R 1000:1000 ...`. So you don't need the temporary passwd file. 👍
