### ISSUE TITLE
"solve with patched libc6" suggestion breaks current build

### ISSUE THREAD

**Issue by johnyoonh** [microsoft/vscode-remote-release#3904]
The following command will suggest using "auto-deconfigure" which will forcefully install packages wreaking havoc on the dependencies. The mods closed the issue, so this might cause a huge problem for some people who just want to fix high CPU usage. I am opening the issue just to raise the alarm for newbies who might stumble on this.

solve with patched libc6 : 
wget "https://launchpadlibrarian.net/474302949/libc6_2.31-0ubuntu8+lp1871129~1_amd64.deb"
sudo dpkg -i libc6_2.31-0ubuntu8+lp1871129~1_amd64.deb

no issue with wsl2, and issue seems to be fixed in wsl1 in next version

more information in https://github.com/microsoft/WSL/issues/4898

_Originally posted by @emeygret in https://github.com/microsoft/vscode-remote-release/issues/2921#issuecomment-624564199_

**Comment by sbatten** [comment]
thanks for raising awareness, since there is no action item here, this item will be closed but searchable.
