### ISSUE TITLE
Intall extension failed in remote ssh docker container behind a http_proxy

### ISSUE THREAD

**Issue by zacario-li** [microsoft/vscode-remote-release#3905]
- VSCode Version:
- OS Version:
Win10,
remote docker container(ubuntu 18.04 LTS)  

Steps to Reproduce:

1. create a docker container with http_proxy
2. enter into the container
3. enable the sshd
4. use vscode connect to the remote container by ssh
5. install extensions -> failed

**Comment by roblourens** [comment]
@zacario-li in your case, is this a local container behind the same proxy as your client, or a remote container with a different proxy setup? 

Also, have you looked at the Remote-Containers extension?

**Comment by zacario-li** [comment]
> @zacario-li in your case, is this a local container behind the same proxy as your client, or a remote container with a different proxy setup?
> 
> Also, have you looked at the Remote-Containers extension?

@roblourens my container is a remote container which connects by ssh. The remote container uses a different proxy setup.
I've not tried the 'Remote-Container' extension, I'll try it.

**Comment by roblourens** [comment]
In that case do you think the problem is that it isn't using the proxy, or something else? Are those environment variables set in the integrated terminal?

And you should check out that extension, it might be what you really want.
