### ISSUE TITLE
Extend devcontainer.json with a setting to add the created container to a docker network

### ISSUE THREAD

**Issue by NCC1701M** [microsoft/vscode-remote-release#3907]
Sometimes it's neccessary to access a different container e.g. a database running in a different container on the same machine. The easiest way - in my humble opinion - to let both containers communicate with each other is to set up a docker network.

```bash
docker network create MyDockerNetwork
docker network connect MyDockerNetwork MyContainerA
docker network connect MyDockerNetwork MyContainerB
```

When rebuilding the dev container - e.g. because of a change within the dockerfile - it is necessary to add the new container manually to the existing network.

This could be automatically done after VSCode Remote has build the container. To achive this, the devcontainer.json could be extended by another setting.

For example:
```json
{
	"dockerFile": "Dockerfile",
	"extensions": [
		"// ..."
	],
	"forwardPorts": [
		1234,
		5678
	],
	"mounts": [
		"// ..."
	],
	"network": "MyDockerNetwork"
}
```

**Comment by PavelSosin-320** [comment]
It makes devcontainer.json as powerful and too similar to compose-file.yaml.  Is it so good to use 2 different technology to do the same things? The plugin for development Dockerfiles and Composefiles using YAML already exists for VSCode. Any image, including devcontainer can be built with help of these tools.
On the other hands, devcontainer contains mainly dockerfile parameters when --network is actually run options and relevant only for docker run and docker-compose up.
In the Composefile build and run sections are separated.

**Comment by NCC1701M** [comment]
> It makes devcontainer.json as powerful and too similar to compose-file.yaml.  Is it so good to use 2 different technology to do the same things? The plugin for development Dockerfiles and Composefiles using YAML already exists for VSCode. Any image, including devcontainer can be built with help of these tools.
> On the other hands, devcontainer contains mainly dockerfile parameters when --network is actually run options and relevant only for docker run and docker-compose up.
> In the Composefile build and run sections are separated.

There's some overload when using docker-compose.yml files to achieve this simple task. Additional scripts will be created, the Dockerfile has to be edited and the docker-compose file has to be created. All this - although there is a VSCode command - is some extra work to do. Adding this feature directly to the devcontainer.json would be more developer friendly.

**Comment by PavelSosin-320** [comment]
Development of full set of Docker artifact types is facilitatedby collectuion of existing VSCode plugind. Thanks to narrow specializatuion of these  plugind they can provide very good user ex, oeriance like code assistance, instant code validation, dry run, automated test generation. Every plugin helps in development of certain artifact type.
If the goal is development of the image of singleton, nonscalable standalone container this aproach is valid. If the goal is development of full stack application  separation of concerns. application logic, IPC, deployment and scalability is more user-frendly by my opinion.   It is much more testeable too.
