### ISSUE TITLE
Allow to download the extensions only once to be used on remote connections

### ISSUE THREAD

**Issue by gustavoaca1997** [microsoft/vscode-remote-release#3908]
I am using the remote connection extension to work with a Django application that is running through Docker Compose. Many times the container is deleted and I have to redownload the Python extension. I do not know how the remote connection extension works, but it would be cool that extensions downloaded before could be used inside the container.

**Comment by chrmarti** [comment]
Could you set the log level to 'trace' (see below) and append the Dev Container log (`F1` > `Remote-Containers: Show Log`) after rebuilding the container?
![image](https://user-images.githubusercontent.com/9205389/97328154-04c29280-1876-11eb-9bf3-bf2f9f7f174b.png)
