### ISSUE TITLE
Debug Windows GUI applications over SSH

### ISSUE THREAD

**Issue by pknowles** [microsoft/vscode-remote-release#3909]
OpenSSH on Windows 10 runs as a service. Services cannot launch GUI applications. If vscode were running natively, not over SSH, it would be able to launch and debug the application just fine. This is purely about launching the app and attaching a debugger. No gui interaction is required and the machine may as well be headless.

A workaround for now may be to RDP to the machine, launch the application and attach to it, but that's pretty roundabout. There's also the issue of attaching the debugger in time. Adding sleeps or a loop is possible but yet more fiddling around.

This is the same problem many have had with automated testing, e.g.:

- https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1046
- https://www.jetbrains.com/help/teamcity/known-issues.html#Agent+running+as+Windows+Service+Limitations
- https://stackoverflow.com/questions/19441324/how-to-run-gui-tests-on-a-jenkins-windows-slave-without-remote-desktop-connectio

The above links suggest starting the service manually in a local session, or in a logon script. This seems more like a workaround, but maybe the same could be done for sshd to make vscode work. I did give this a go, starting sshd both as administrator and my user (adding access to C:\ProgramData\ssh\* and using an unpriviliged port) and neither worked.
- https://github.com/PowerShell/Win32-OpenSSH/issues/1304#issuecomment-499046268

Could a solution be related to #390? E.g. could 'runas' be used to start the debugger with elevated permissions to be able to access the GPU?
https://stackoverflow.com/questions/37700536/visual-studio-code-terminal-how-to-run-a-command-with-administrator-rights
https://stackoverflow.com/questions/21466060/how-to-debug-as-nt-authority-system-in-visual-studio

I gather not running as admin isn't the problem. It's that sshd does not have a login session with a GUI available. E.g. from the vscode terminal, the current session is "services":

```
PS C:\> query session
 SESSIONNAME       USERNAME                 ID  STATE   TYPE        DEVICE
>services                                    0  Disc
```

In this case there's only a couple of options:

1. Connect to an existing GUI session (potential issues with the session being locked/at the password screen)

   - https://superuser.com/questions/1572456/run-gui-application-via-openssh-on-windows-10
   - https://superuser.com/questions/531787/starting-windows-gui-program-in-windows-through-cygwin-sshd-from-ssh-client
   - https://stackoverflow.com/questions/5063731/is-there-any-way-to-start-a-gui-application-from-a-windows-service-on-windows-7

2. Create a new gui session that the ssh connection has permission to launch apps in. Can [`mstsc`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mstsc) do this? Is this even possible? There is [`tscon`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/tscon) to switch sessions. Could that be useful?

**Comment by roblourens** [comment]
If you have access to a GUI, why are you using ssh? This isn't the expected workflow for Remote-SSH

**Comment by pknowles** [comment]
> If you have access to a GUI, why are you using ssh?

From that point of view, you can always install rdp/vnc and run vscode on the target, so why use vscode remote dev at all? The answer is the environment is better - faster, prettier, more convenient. I have access to a gui to help debug why remote ssh isn't working. I can think of a few examples where this might be useful:

- The target machine simply has more resources (builds faster, tests faster, maybe neither are even possible locally).
- Developing applications on different hardware to support multiple platforms without having to switch locally
- Developing for hardware you simply don't have locally
- A headless machine or VM is used in automated testing. vscode could be used to debug a failure with the exact same hardware and software environment.

**Comment by roblourens** [comment]
All good points. I think it's probably possible to get the behavior you want with the right configuration, but I don't think it's right for vscode to try to do this itself since it's not the scenario we are focused on.

You can try setting up your debugger to run the right script or set the right environment variables before launching the debug process. Or you can try setting this up yourself in a terminal, launching the process from there, and attaching the debugger. But I don't know much about this and don't have real answers to your questions, sorry.

**Comment by axetroy** [comment]
For me, I have two screens.

One screen to connect to remote machine (Windows)
One screen is my local computer, open vscode to debug the application via remote SSH.

This way I can develop applications with minimal resource consumption.

Unfortunately, It cannot bring up the GUI on Windows. but works in Linux var setting env `export DISPLAY=:1`.

**Comment by ajihyf** [comment]
I think this issue is related to [PowerShell/Win32-OpenSSH issue #998](https://github.com/PowerShell/Win32-OpenSSH/issues/998). I suspect that Microsoft's policies may not be very supportive of starting GUI programs via SSH (after all, they want to sell Windows Server).
However, [Remote Tunneling](https://code.visualstudio.com/docs/remote/tunnels) is capable of launching GUI applications during remote connections, but since the tunnel requires Azure servers for relay, it has high latency and connections often drop.
