### ISSUE TITLE
`code .` opens in the wrong folder

### ISSUE THREAD

**Issue by lifeiscontent** [microsoft/vscode-remote-release#3912]
when I run `code .` VSCode opens in the wrong directory.

![image](https://user-images.githubusercontent.com/180963/97390350-d2c32780-1899-11eb-8705-69020c399a29.png)
![image](https://user-images.githubusercontent.com/180963/97390385-f25a5000-1899-11eb-8a74-94b05dc07c2e.png)

**Comment by aeschli** [comment]
Can you run `code . --verbose >log.txt` in the powershell console? I'm interested in the first part of the output (including `pathsToOpen`)
