### ISSUE TITLE
Improved workflow with existing running processes

### ISSUE THREAD

**Issue by christianalfoni** [microsoft/vscode-remote-release#3917]
Hi there!

We are running multiple docker containers in our environment. Where 2 of those containers are:

1. **Client**: Runs a webpack development process when it starts
2. **Server**: Runs the server process when it starts

Now, the challenge for us is that when we **attach** to these containers we are not able to see the running process in the terminal inside VSCode. The reason this is a problem is:

1. As a **backend** developer you want the **client** to automatically start, which it does now. But you want to avoid jumping out of VScode to look at **server** logs, restarting the server process etc.

2. As a **client** developent you want the **backend** to automatically start, which it does now. But you want to avoid jumping out of VSCode to look at **client** logs, restarting the webpack process etc.

![93IfWWXS](https://user-images.githubusercontent.com/3956929/97564187-79b3da80-19e4-11eb-8679-fa2435e42a16.png)

Is there any way this extension can latch on to the existing running "shell" (Or whatever the correct term is), so that you instantly get a terminal shell for the running process, looking at logs, stopping, starting it etc.

**Comment by PavelSosin-320** [comment]
Docker Container is not a VM or process. The container is cgroup of Host Linux OS processes. It ensures that processes inside container are intentionally isolated from OS processes. It makes synchronization between Host and Container processes very complex - they belong to different namespaces, i.e. can't have shared locks, semaphores, etc.  It is much simpler to synchonize 2 containers via namespes sharing using --pid  2nd container of the run command. I'm not sure that such full-stack debugger exists that knows to do it.
Another reason not to do it is that different full-stack application tiers may use different run-times and languages. Although VSCode uses universal debugging protocol - DAP but DAP Adapters are absolutly independed.

The common technic to debug is using of 2 separate debugging sessions with independend process states and breakpoins

**Comment by PavelSosin-320** [comment]
The debugging workflow for full-stack application is:
1. Start backend service and wait until health-check is OK
2. Wait until backend status is ready to server requests
3. Launch Frontend, mainly browser providing running server URL
4. Instruct backend debugger to wait for backend server attachment
5. Set breakpoint in front-end debugger
6. set break-point in back-end debugger when it starts.
Step-run-inspect code&variables-continue
7. Wait for front-end debugger will reach breakpoint
8. Wait  for back-end debugger .... end if it is not enough multiply  by the number of tiers

**Comment by chrmarti** [comment]
@christianalfoni Have you considered running Webpack inside a tmux session? That is a separate CLI tool to keep shell sessions alive.

We are also working on persisting Integrated Terminals across VS Code sessions, but that might not be what you are looking for.

**Comment by christianalfoni** [comment]
@chrmarti Hi there!

I actually got this working using your TMUX tip, thanks a bunch! One thing to note, if someone else arrives at this issue, is that to make TMUX sessions stay at the foreground is you should define a bash script like this:

```sh
yarn start
tail -f /dev/null
```

The last line of the script ensures that Docker does not exit. Now the **package.json** does:

```json
{
  "scripts": {
    "start": "(tmux new-session -d -s my_session 'webpack-dev-server' || tmux attach -t my_session) && tmux attach -t my_session"
  }
}
```

This script ensures that if you run `yarn start` with an existing session running, it opens the session. If it is not running it starts it and then opens the session.

It is working really well for me, so thanks a bunch 🙏

**Comment by Neutrino-Sunset** [comment]
@christianalfoni I'm trying to work out how to reconnect to a container running `nodemon` or `ng serve` and this might be what I need, but i don't understand it.

What's the script called and how is it used? I don't see how a script containing `yarn start` would have an effect when invoking `yarn start` on the commandline.

**Comment by Neutrino-Sunset** [comment]
I managed to work it out. With this in my docker-compose.yml
```
    tty: true
    stdin_open: true
```
and this in my package.json
```
"start": "(tmux new -s my_session 'nodemon server.js' || tmux attach -t my_session)"
```
It seems to be working fine.
