### ISSUE TITLE
Need a way to trust root CA certs other than turning off SSL

### ISSUE THREAD

**Issue by southwood** [microsoft/vscode-remote-release#3918]
Currently the only way to run VSCode within a corporate network which uses SSL proxying is to disable SSL entirely. For example, with ZScaler I need to set `"http.proxyStrictSSL": false`. This is okay as a short-term work-around but not acceptable for general use.

Also, this doesn't seem to work for extensions or within a dev container. The container is configured to trust the CA certs, but it looks like VSCode pulls in host system CAs when installing extensions in the container. This is partially fixed by setting `"http.systemCertificates": true` as discussed [here](https://github.com/microsoft/vscode/issues/12588).

Please implement a setting to configure additional root CA certs. Maybe a setting to specify a cert which would then be loaded via something like [this](https://www.electronjs.org/docs/api/app#appimportcertificateoptions-callback-linux)?

**Comment by chrmarti** [comment]
Related: https://github.com/microsoft/vscode-remote-release/issues/986

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/2987.

**Comment by southwood** [comment]
The work-around is setting `"http.proxyStrictSSL": false` for the context used by `remoteExtensionHostAgent.js`. You can drop a `settings.json` somewhere in the `.vscode-server` directory tree it gets picked up by this.

Instead of toggling this with the settings file it should work with any CAs if you pull the global /root/.npmrc from the docker container. If it has a `cafile` set, use that regardless of the `strictSSL` setting that is composed by reading proxy config from settings.json. The way it is currently implemented prevents a solution where SSL stays enabled.
