### ISSUE TITLE
Remote - Containers always overrides entrypoint

### ISSUE THREAD

**Issue by tirafesi** [microsoft/vscode-remote-release#3919]
I'm running a container based on `ros:foxy` and its entrypoint `/ros_entrypoint.sh` is never run, meaning `/opt/ros/foxy/setup.bash` is never sourced.

By taking a look at the logs I noticed that the extension seems to always `run` with the option `--entrypoint /bin/sh`, effectively overriding whatever entrypoint was defined in the dockerfile.

Even if I add my own `--entrypoint` option to `runArgs` in `.devcontainer.json`, the extension still overrides it because its `--entrypoint` option always appears after mine:

`docker run ... --entrypoint=/my_entrypoint.sh --entrypoint /bin/sh`

I'm using the option *Clone Repository in Container Volume* to create and run my containers.

System Info:
- VSCode Version: 1.50.1
- Local OS Version: Ubuntu 18.04.5 LTS
- Remote OS Version: Ubuntu 20.04.1 LTS
- Remote Extension/Connection Type: Docker

**Comment by chrmarti** [comment]
You can add `"overrideCommand": false` to your `devcontainer.json` to turn this off.
