### ISSUE TITLE
Feature request: The ability to change primary group for vscode-server

### ISSUE THREAD

**Issue by erichaydel** [microsoft/vscode-remote-release#3921]
I have a project that uses group-specific mounts, so you need to execute a `newgrp group` to access these files.
This can be replicated by running commands with `sg group -c "command"`, since `newgrp` requires opening up a new terminal, and therefore would be tricky to run with `ssh`.
It would be very helpful to add the ability to run vscode-server with a certain primary group so that the file browser works as intended.

If there's any workaround you can think of, that would work as well.

Thanks!

**Comment by roblourens** [comment]
> It would be very helpful to add the ability to run vscode-server with a certain primary group

I don't totally understand the problem, what would we have to do to do this? Does this mean, run that `sg group` command before launching the server?
