### ISSUE TITLE
launch: program does not exist, executable not found by debugger

### ISSUE THREAD

**Issue by 3ddiddE** [microsoft/vscode-remote-release#3924]
- VSCode Version: 1.50.1
d2e414d9e4239a252d1ab117bd7067f125afd80a
x64
- Local OS Version: LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
- Remote OS Version: LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. On remote, create cmake project (only tested with cmake tools) in a folder called anyFolderName
2. Add target named the same as the folder e.g. add_executable(anyFolderName ...)
3. Connect VSCode to remote host
4. Open folder, let cmake tools initialize everything
5. Run CMake: Debug (also with launch.json appropriately set up) you will get "launch: program anyFolderName does not exist"

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
Please file this on the debug extension repo
