### ISSUE TITLE
wslServer.sh: Input/output error

### ISSUE THREAD

**Issue by Perpaterb** [microsoft/vscode-remote-release#3925]
- VSCode Version: 1.50.1
- Local OS Version: Win 10 same with 1908 +
- Remote OS Version: Any Ubuntu

Steps to Reproduce:

1. Mount the WLS root as network drive in Windows.

How to Fix:

1. Unmount the WLS root as network drive in Windows.
2. Add the \\wsl$ folder to your quick access links.

This is just an FYI because I solved my own problem.

**Comment by Perpaterb** [comment]
See OG comment for fix

**Comment by aeschli** [comment]
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/2297

It's a WSL issue. You need to run `wsl --shutdown` to solve the problem.
