### ISSUE TITLE
Code should not modify .gitconfig in any kind of automatic way

### ISSUE THREAD

**Issue by hholst80** [microsoft/vscode-remote-release#3927]
I kindly request that vs code remote STOP MODIFYING .gitconfig which is a userfile and not a key-value store for vscode remote scripts.

I am not suggesting that modifications of gitconfig should be BANNED I am suggestion that any updates to .gitconfig should be triggered by an explicit user-initiated process and with a optional confirmation to update gitconfig.  There has been a sequence of bad design choices around .gitconfig and this needs to be handled in a better way all together.  If the user needs to confirm an update chances are that the script designers make better choices on what and how changes go into .gitconfig.

To start, the vs code remote server component should never automatically modify gitconfig without an attached vscode session that has explicitly asked for a change to be made.

![image](https://user-images.githubusercontent.com/6200749/97775155-bf94ae00-1b5e-11eb-9e3b-e00560c56b5f.png)
![image](https://user-images.githubusercontent.com/6200749/97775159-cde2ca00-1b5e-11eb-9250-da9ac7a1f271.png)
![image](https://user-images.githubusercontent.com/6200749/97775163-d89d5f00-1b5e-11eb-87fd-df6463d8b9ec.png)

**Comment by chrmarti** [comment]
Which remote extension are you seeing this with? What are the changes that are applied?

The only change I'm aware of with Remote-Containers is the setting of a credentials helper while connecting to a container.

**Comment by hholst80** [comment]
> Which remote extension are you seeing this with? What are the changes that are applied?
> 
> The only change I'm aware of with Remote-Containers is the setting of a credentials helper while connecting to a container.

As far as I can see it only adds these [credentials] sections (redundantly). I have not seen exactly when it does so, maybe it is when I connect as you say. If this was something the remote tool could achieve using other means as say using GIT_ASKPASS instead of poking at my configuration files and making a mess.

https://git-scm.com/docs/gitcredentials

**Comment by chrmarti** [comment]
Which remote extension are you seeing this with?

**Comment by hholst80** [comment]
I am seeing this behavior with the remote container plugin.  Maybe the same logic is present in the WSL and remote ssh plug-in as well, but I do not use those myself.

![image](https://user-images.githubusercontent.com/6200749/98009042-6e521c00-1df5-11eb-8235-c7399d4760fa.png)

**Comment by chrmarti** [comment]
Not sure what would trigger that. Could you try turning off the credentials helper in the user settings:
![image](https://user-images.githubusercontent.com/9205389/98086477-1c55d880-1e7f-11eb-85bf-018c5e45cfb9.png)

**Comment by hholst80** [comment]
I was not aware of that setting. Thank you for a perfectly reasonable workaround.

I think it could be informative to inform the user about this and be able to "opt out" from the global setting.

**Comment by chrmarti** [comment]
The screenshot you posted first shows many `[credential]` sections. Was that triggered by that feature? (Not sure how it would, we use the Git CLI to update the credentials helper.)

We're trying to make everything the user normally expects to work to also work in the dev container without the user having to do anything. We could add a notification or something informing the user if this becomes a popular request, but there are already too many notifications for an additional one to be useful in my opinion.

**Comment by hholst80** [comment]
I do not know for *sure* that it was vscode that these these changes to begin with.  I have a few plugins installed normally in both Vim and in Code that could theoretically have modified .gitconfig as well.  I have been tripped before by vs code injecting javascript code for hooks (credential helpers) that have caused other tooling to fail as a result.  After that vscode has been my scapegoat for anything that goes wrong with .gitconfig. 

I will see if I can reproduce the duplicate lines with the latest version of Code.  If not, I am happy with the workaround for the time being. I will re-open this if I can indeed manage to find time and can reproduce it.

Thank you.
