### ISSUE TITLE
forwardPorts to localhost instead of 127.0.0.1

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode-remote-release#3928]
If I add `"forwardPorts": [8000]` to `devcontainer.json`, this (sometimes?) creates `8000 → 127.0.0.1:8000`. But if I type `8000` into the extension UI, this creates `8000 → localhost:8000`.

This inconsistency has caused me enough minor problems (e.g. with OAuth `redirect_uri` whitelisting) that I decided to file this _incredibly_ minor feature request.

**Comment by aaronadamsCA** [comment]
...I suddenly cannot reproduce this behaviour even though I've noticed it for months, so maybe just revise this to "figure out where the 127.0.0.1 sometimes comes from and stop it"?

**Comment by chrmarti** [comment]
This should be fixed with https://github.com/microsoft/vscode-remote-release/issues/2711. Make sure you are on the latest version of the extension (0.145.1 for VS Code 1.50).
