### ISSUE TITLE
Drag-n-drop upload files local->remote and download files remote->local

### ISSUE THREAD

**Issue by romanrehacek** [microsoft/vscode-remote-release#393]
It would be great to be able to upload files from a local to a remote server with drag-n-drop to explorer and the ability to download files from remote to local.

When I try to upload a file (s) from a local to a remote server, drag-n-drop onto the vcode explorer. A directory where I want to upload files is highlighted, but nothing happens.

**Comment by raghavk92** [comment]
is there a way to download a file or folder to user computer from right click menu on a file or folder.

**Comment by andrews05** [comment]
The [documentation for SSH](https://code.visualstudio.com/docs/remote/ssh) mentions in the known issues:
"You cannot drag files out of the File Explorer to your local filesystem to copy them."
But it doesn't say anything about copying from local to remote - is this supposed to work?

**Comment by isidorn** [comment]
No, this is currently not supported. Leaving this open as a feature request. Thanks.

**Comment by LeuisKen** [comment]
I find this feature is working in the latest code-insider, which commit id is "c3fe2d8acde04e579880413ae4622a1f551efdcc". 👍🏻

**Comment by isidorn** [comment]
Yeah this is fixed with latest, forgot to lcose it here.
Thanks for the ping
