### ISSUE TITLE
User not found error when connecting to docker container

### ISSUE THREAD

**Issue by ilinojkovic** [microsoft/vscode-remote-release#394]
I followed detailed [official instructions](https://code.visualstudio.com/docs/remote/containers) on creating `.devcontainer/devcontainer.json` and setting up remote by running `Remote-Containers: Reopen Folder in Container`, however, even with official/provided containers and settings I get the error:
```
Setting up container for folder: /home/ilijas/<path_to>/workspace
Error: (HTTP code 500) server error - linux spec user: unable to find user ilijas: no matching entries in passwd file 
        at /home/ilijas/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.53.0/dist/extension.js:1:151013
        at /home/ilijas/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.53.0/dist/extension.js:1:150976
        at m.buildPayload (/home/ilijas/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.53.0/dist/extension.js:1:150986)
        at IncomingMessage.<anonymous> (/home/ilijas/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.53.0/dist/extension.js:1:150486)
        at IncomingMessage.emit (events.js:187:15)
        at endReadableNT (_stream_readable.js:1090:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
```
In my first attempts I tried to mount a local workspace to remote one, however, since I couldn't resolve this user-not-found error, I removed all of the arguments inside docker settings which regarded user, just to make one dummy container work. In the end I tried the provided Python 2 container, and still no success. I know this is a fresh extension, but still, I hope someone can help.

I posted a [SO question](https://stackoverflow.com/questions/56225259/vscode-cannot-connect-to-docker-container-using-remote-development-extension) but due to lack of activity, I'm posting here as well.

**Comment by egamma** [comment]
@ilinojkovic what platform are you on Linux, OS X? Can you share your .devcontainer folder?
Can you reproduce the problem when use use one of the simple 'try' samples, e.g., https://github.com/microsoft/vscode-remote-try-node.

**Comment by chrmarti** [comment]
@ilinojkovic Please remove the container before you try again. Does that make it work?

**Comment by ilinojkovic** [comment]
Thanks both for the quick response! Here are some further details:
OS: linux
Product: Visual Studio Code - Insiders
Product Version: 1.35.0-insider
Language: en

@egamma I run the example you proposed, and that one does work.
@chrmarti It doesn't even get to a stage where the container is created, so there's nothing to remove and start again.

Additionally, I tried to create a new project and start it inside Python 2 container, with the same config files as before, and it worked. Is there a chance there are some other config files outside `.devcontainer` and `.vscode` that I'm missing? Whatever I seem to do inside my current workspace produces this error.

For the reference, this is inside `.devcontainer`:

**devcontainer.json**
```
// See https://aka.ms/vscode-remote/devcontainer.json for format details.
{
	"name": "Python 2",
	"context": "..",
	"dockerFile": "Dockerfile",
	"workspaceFolder": "/workspace",
	"extensions": [
		"ms-python.python"
	]
}
```

**Dockerfile**
```
#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

FROM python:2

# Copy endpoint specific user settings into container to specify Python path
COPY .devcontainer/settings.vscode.json /root/.vscode-remote/data/Machine/settings.json

# Install git, process tools
RUN apt-get update && apt-get -y install git procps

RUN mkdir /workspace
WORKDIR /workspace

# Install pylint
RUN pip install pylint

# Install Python dependencies from requirements.txt if it exists
COPY .devcontainer/requirements.txt.temp requirements.txt* /workspace/
RUN if [ -f "requirements.txt" ]; then pip install -r requirements.txt && rm requirements.txt*; fi

# Clean up
RUN apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
```

**settings.vscode.json**
```
{
    "python.pythonPath": "/usr/local/bin/python",
    "python.linting.pylintEnabled": true,
    "python.linting.enabled": true
}
```

And empty **requirements.txt.temp**

**Comment by chrmarti** [comment]
@ilinojkovic Is there a stopped container hanging around? The files you posted don't show any user, so I'm guessing there must be some leftover from your earlier trials.

**Comment by ilinojkovic** [comment]
Thanks, @chrmarti ! This did solve the issue, though, it's a bit unintuitive how the two are connected if it's not specified inside `.devcontainer`.

**Comment by chrmarti** [comment]
@ilinojkovic The container has a label with the folder as the value, so it can be found again. When you close the window, the container is only stopped, not removed, for later use. (You could have some changes inside the container you want to keep. Also: Reusing an existing container is slightly faster.)
