### ISSUE TITLE
Remote crashes because of RAM usage

### ISSUE THREAD

**Issue by JonasKruckenberg** [microsoft/vscode-remote-release#3940]
- VSCode Version: 1.50.1
- Local OS Version: macOs 11.0.1 Beta/Windows 10 1909
- Remote OS Version: Ubuntu 20.04.1
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. I have a raspberrypi model 3B with ubuntu set up.
2. Connect via the remote-ssh extension and save some file, 10 lines was enough for me.
( running a command also works, like `rollup -cw` in my case )
3. Depending on how active the remote was at the time to things can happen.
    a The remote disconnects and the vscode window has to be reloaded multiple times to get it working again.
    b The remote disconnects and freezes completely, needing a "hard reboot" ( disconnect the power ) to recover. 
       In this case ssh connections always fail with a time-out error, pinging still works though.

Notes:
- Running `top` shows some nodejs processes that are spawned that take up to 70% of the raspberrypi's CPU. 
I don't know if that is related though.
- This is possibly a dup of #1257 even though the constraint environment makes it different enough for it's own issue.
- I also own a Raspberrypi 4 that I'll test things on when I have the time.

Does this issue occur when you try this locally?:: No (N/A)
Does this issue occur when you try this locally and all extensions are disabled?:: No (N/A)

**Comment by JonasKruckenberg** [comment]
Alright, I wanted to add some more information to this Issue.
1.  [here](https://gist.github.com/JonasKruckenberg/54a17dfe516b15cd859221012fb92ca7) is the cpu utilization when using remote-ssh on my pi. Note that around tick 34 vscode lost the connection and around tick 141 the last one recorded my pi froze completely.
2. The image below seems to indicates that a process is dumping A LOT of data into the RAM. Simultaneous the NetworkManager is ramping up, so maybe some sort of heavy network load? Also note that while this is happening vscode on my local machine still tries to connect.

![Picture1](https://user-images.githubusercontent.com/25329995/98154578-476b1700-1ed5-11eb-8075-6587fa36e510.png)

**Comment by JonasKruckenberg** [comment]
Please let me know If you'd like me to test anything or provide more data/ logs etc.
Cheers!

**Comment by roblourens** [comment]
We do need a decent amount of RAM on the remote, and there isn't much I can do to help. I think you have found the right folder as a dupe
