### ISSUE TITLE
"Open Workspace in Container" does not work with a custom workspace mount

### ISSUE THREAD

**Issue by dslijepcevic** [microsoft/vscode-remote-release#3942]
It seems that when you specify a custom `workspaceMount` and `workspaceFolder` in `devcontainer.json` in order to change the default mount point `/workspaces/$project`, "Open Workspace in Container..." stops working properly and opens up `workspaceFolder` instead of a workspace file that was initially selected.

```json
{
    "workspaceMount": "source=${localWorkspaceFolder},target=/some/path,type=bind,consistency=cached",
    "workspaceFolder": "/some/path",
    ...
}
```

With a default mount point it works correctly.

**Comment by dslijepcevic** [comment]
Just checked, "Open Workspace in Container..." does not work with `docker-compose` dev container either.

**Comment by chrmarti** [comment]
This is working with a single container for me. Could you retry with the latest version (0.148.0) available (requires the just released VS Code version 1.51)?

**Comment by dslijepcevic** [comment]
I tried with the latest version and it seems to be working with `docker-compose`, however, original bug is still present with regular `docker`. I noticed that when using just `docker` the `${containerWorkspaceFolder}` is not a directory but also includes `.code-workspace` file unless `workspaceMount` and `workspaceFolder` are specified. Then it's a directory, and it doesn't open the workspace file as requested.

**Comment by chrmarti** [comment]
To verify:
- Have a workspace file with (at least) a single folder contained within the same folder as the workspace file and add a `.devcontainer.json` to the workspace file's folder:
```json
{
	"image": "debian",
	"remoteEnv": {
		"LOCALWSF": "${localWorkspaceFolder}",
		"CONTAINERWSF": "${containerWorkspaceFolder}"
	}
}
```
- Open Workspace File in Container
- Verify that `printenv | grep WSF` shows the local and container folders of the workspace files (not the workspace files themselves).
- Repeat with a modified `.devcontainer.json` (Rebuild the container after changing it):
```json
{
	"image": "debian",
	"remoteEnv": {
		"LOCALWSF": "${localWorkspaceFolder}",
		"CONTAINERWSF": "${containerWorkspaceFolder}"
	},
	"workspaceMount": "type=bind,src=${localWorkspaceFolder},dst=/foobar",
	"workspaceFolder": "/foobar"
}
```
- Verify that `printenv | grep WSF` shows the local and container folders of the workspace files (not the workspace files themselves).
