### ISSUE TITLE
git commit results in python.exe not found

### ISSUE THREAD

**Issue by theelderbeever** [microsoft/vscode-remote-release#3943]
This maybe hard to debug since I am on a corporate laptop and it could just be some other versioning issues however, when I attempt to commit code from inside a remote container I get an error `/usr/bin/env: ‘python.exe’: No such file or directory`. For some reason the git in the container is looking for a `python.exe` even though it is a linux container. This fails the commit command. `git status`, `git add`, etc all seem to work still.

- VSCode Version:
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763
- Local OS Version: 
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.17763 Build 17763
- Remote OS Version: 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
- Remote Extension/Connection Type: Docker
Docker Desktop: 2.4.0.0 (48506)
Docker Engine: 19.03.13

Steps to Reproduce:

1.  Create devcontainer based on python:3.8 with a git project mounted.
2. Make some file changes
3. `git add .`
4. `git commit -m "some message"`

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
What are the steps to trigger the error? Where is the error shown? And could you attach a screenshot?

**Comment by theelderbeever** [comment]
@chrmarti Figured out the issue. It was from using `pre-commit` hooks and having installed them in the Windows environment and then moved to devcontainers without explicitly reinstalling the hooks while in the container. This caused committing to look for the wrong python. Not a VSCode issue.
