### ISSUE TITLE
Command 'Remote-Containers: Reopen in Container' resulted in an error (spawn ....AppData\Local\Programs\Microsoft VS Code\wsl ENOENT)

### ISSUE THREAD

**Issue by adedaporh** [microsoft/vscode-remote-release#3944]
Issue Type: <b>Bug</b>

1. Installed the both the Docker extension and the Remote Container extension
2. Created a .devcontainer in the root directory of my project
3. created a devcontainer.json in the above directory
4. Created a Dockerfile
5. Ran “Remote-Containers: Reopen in Container” from the command palette

Extension version: 0.145.1
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:57:08.739Z)
OS version: Windows_NT ia32 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.17GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/adedaporh/php-in-docker-demo --remote=wsl+Ubuntu-20.04 --crash-reporter-id ab3c4b85-e9ff-448d-89c5-c9870b1e8d35|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|6.10GB (4.17GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Do you have WSL installed?

**Comment by chrmarti** [comment]
Just now see that you have it. Is the WSL distro running in WSL2 mode? And do you have in Docker Desktop the WSL-backend for this distro enabled? (Can you manually run `docker` within WSL in a terminal?)

**Comment by adedaporh** [comment]
> Just now see that you have it. Is the WSL distro running in WSL2 mode? And do you have in Docker Desktop the WSL-backend for this distro enabled? (Can you manually run `docker` within WSL in a terminal?)

Yes WSL-backend for the distro is enabled and yes i can run 'docker' in the terminal

**Comment by adedaporh** [comment]
![image](https://user-images.githubusercontent.com/33579016/98356730-59a79b00-2024-11eb-9311-77bc08fc0200.png)
@chrmarti Refer to the image above

Also the distro is running on WSL2 mode

**Comment by chrmarti** [comment]
Somehow the WSL executable must be missing from the PATH. What do you get for `get-command wsl` in PowerShell?

**Comment by adedaporh** [comment]
![image](https://user-images.githubusercontent.com/33579016/98412686-ab7a1080-2078-11eb-8bf8-47279ed4d159.png)

**Comment by adedaporh** [comment]
@chrmarti After some digging, the remote-container extension seems to be pointing to a file that does not exist
![image](https://user-images.githubusercontent.com/33579016/98445920-bbe2c780-211a-11eb-8102-b619773826fe.png)
Is this a standard VS Code/WSL path?

**Comment by chrmarti** [comment]
We try to look up `wsl` on the PATH and can't find it. (The path in the error message is kind of a fallback triggering the ENOENT. There might be better ways to handle that.)

**Comment by chrmarti** [comment]
Adding more logging to track this down. (Will be in the next version, 0.150.0, of the extension.)

**Comment by samuellralph** [comment]
Hello @adedaporh, I had the same problem.

I'm running VSCODE on Windows 10 Home 2004, where the remote container extension worked well, but when trying to run remote-WSL I was unable to use the options of the remote-container extension.

Error: Command 'Remote-Containers: Open Folder in Container ...' resulted in an error (spawn C: \ Program Files (x86) \ Microsoft VS Code \ wsl ENOENT)

At first I thought my problem was the extension when reading your issue, I installed other versions of the extension and the problem persisted.

Solution:
The solution to my problem was to uninstall and reinstall VSCODE, this solved my problem.

I hope it helps you.

------------------------- System info ----------------------- -
Microsoft Windows 10 Home Operating System Name
Version 10.0.19041 Build 19041
X64-based PC system type
Intel (R) Core (TM) Processor i5-6400 CPU @ 2.70GHz, 2701 Mhz, 4 Core (s), 4 Logical Processor (s)
Installed Physical Memory (RAM) 16.0 GB

Docker Desktop - Version 2.5.01 (49550)

VSCOD-VERSION:
Version: 1.51.0 (user setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18: 18: 23.642Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Commando: wsl --list --verbose
NAME STATE VERSION
Ubuntu------------------Running-----2
docker-desktop---------Running-----2
docker-desktop-data---Running-----2

**Comment by adedaporh** [comment]
@samuellralph It seems a re-install did the trick. It all seems to be working now.
Thanks.

**Comment by adedaporh** [comment]
I'm closing this issue now since a reinstall of VS Code will resolve this problem.

@chrmarti  Perhaps the next version of the extension will prevent this from happening in the first place.

Thanks for the support.
