### ISSUE TITLE
Complete command: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8) 

### ISSUE THREAD

**Issue by luyahan** [microsoft/vscode-remote-release#3945]
- VSCode Version:1.50.1
- OS Version:Win

Steps to Reproduce:

1.ssh remote on Linux
2.open terminal `bash`
3.input command and press Tab to complete command
3.see warning: 
```
scp ./dbash: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8)
bash: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8)
```

**Comment by luyahan** [comment]
only occurs on command:`scp`

**Comment by roblourens** [comment]
Sorry, I don't know what that means, but I think it's from your remote somehow and not vscode
