### ISSUE TITLE
WSL Terminal take too long to start 

### ISSUE THREAD

**Issue by DanielhCarranza** [microsoft/vscode-remote-release#3946]
When I open VScode the WSL Terminal takes too long to start, some times I have to reopen VScode several times to start. 

CPUs | Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)
-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 7.92GB (1.27GB free)
Process Argv | --folder-uri=vscode-remote://wsl+Ubuntu/mnt/c/Users/compu/Desktop/Proyectos/ --remote=wsl+Ubuntu --crash-reporter-id f884b11d-cbb3-4d95-ae45-4a2c86039ef0
Screen Reader | no
VM | 0%

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
