### ISSUE TITLE
"Attach to Kubernetes Cluster" and debug all the services in the same window

### ISSUE THREAD

**Issue by gionapaolini** [microsoft/vscode-remote-release#3950]
I am developing directly inside a Kubernetes cluster.

To debug all the services together I currently need to attach to each container running in the cluster separately, and this will create new windows.

It would be nice to have a feature like "Attach to Kubernetes Cluster by Namespace" that opens a window that will connect to all the running containers in a specific namespace of a k8s cluster. In this way you can have a sort of DevContainers with all the extensions that you need for that specific namespace and also be able to debug all the services in a single window (similarly to debugging a docker-compose file).

**Comment by Chuxel** [comment]
Unfortunately, same window support is not yet available for Docker Compose either (see https://github.com/microsoft/vscode-remote-release/issues/1460). 

To verify, your request is to be able to attach to (not spin up) multiple containers in a kubernetes cluster in the same window, correct?

**Comment by gionapaolini** [comment]
> 
> 
> Unfortunately, same window support is not yet available for Docker Compose either (see #1460).
> 
> To verify, your request is to be able to attach to (not spin up) multiple containers in a kubernetes cluster in the same window, correct?
> 
> (cc: @chrmarti)

That is correct. And it is indeed very similar to https://github.com/microsoft/vscode-remote-release/issues/1460
