### ISSUE TITLE
Forwarded ports are scraped from the containers creation log

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#3953]
- Open a folder in a container
- Open the creation log in the terminal
- When the creation log shows a URL then it is scraped as a forwarded port, see the screenshot below

![image](https://user-images.githubusercontent.com/172399/98165939-011eb380-1ee7-11eb-8830-156dacb97889.png)

We should not scrap for forwarded ports from the creation log, e.g., we could check for the terminal namge 'dev container' and not scrape from this terminal. @chrmarti is there a better way to exclude this output?

I think this is the same issue as https://github.com/microsoft/vscode-remote-release/issues/3894. The step I forgot in this issue is that I have opened the creation log "show log" from the progress notification.

**Comment by chrmarti** [comment]
The extension prints that URL only when a hidden setting is enabled. We could change the output to no longer register as an URL, but that would also break the terminal's link provider I think. There is another link trigger port forwarding when in debug mode over which we have no control in the extension. A switch to turn the port forwarding for this terminal off would be best.
