### ISSUE TITLE
Add a remote mergetool feature

### ISSUE THREAD

**Issue by pknowles** [microsoft/vscode-remote-release#3954]
One thing my workflow is missing is a 3-way merge tool to resolve conflicts. As far as I know vscode doesn't have one yet.

I currently use meld locally. The following extension could open meld if I were working locally, but it doesn't work with remote dev:
https://github.com/RandomEngy/VSCodeGitDiffAndMergeTool

For now, would it be possible to copy the files locally and launch the user's git mergetool? (yes, ideally this would be possible for other version control too)

Could this be done transparently, so extensions like the above would "just work"?

Assuming the above isn't it, what is the long term "right" way to have a feature like this?

**Comment by pd93** [comment]
There is already [a very popular feature request for 3-way merge support in VSCode](https://github.com/microsoft/vscode/issues/37350). I am guessing that this will support remote scenarios when it is added.

This feature was also added to their [2020 roadmap](https://github.com/microsoft/vscode/wiki/Roadmap#scm).

**Comment by pknowles** [comment]
Looks good. Might not be worth duplicating work here (e.g. start a local tool to diff remote files) unless it's easy/low hanging fruit. Might as well close the issue.
