### ISSUE TITLE
A magical problem may involve server security

### ISSUE THREAD

**Issue by wsysx123** [microsoft/vscode-remote-release#3957]
- VSCode Version:1.50.1
- Local OS Version:Windows 10
- Remote OS Version:Ubuntu 18.04.5 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.Connect the remote server by SSH in vscode
2.Connect a new linux terminal through putty
3.Execute the 'who' command in the new linux terminal
4.It will only display the online users I connected through putty, and not the vscode

If it give hackers the vulnerability to connect to the remote server without trace?

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
I don't fully understand how that command works, but I don't think there's a problem here.
