### ISSUE TITLE
Visual Studio Code Remote development does not cleanup all the processes on the remote

### ISSUE THREAD

**Issue by veaceslav** [microsoft/vscode-remote-release#396]
- VSCode Version:
Version: 1.35.0-insider (user setup)
Commit: 4ca38ce5584d7cd67b435b3c32ef1240c6a29628
Date: 2019-05-21T05:18:31.618Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
- Local OS Version: OS independent(both Windows and Linux exhibit the same problem)
- Remote OS Version: Oracle Linux 7
- Remote Extension/Connection Type: SSH/Docker/WSL : SSH

Steps to Reproduce:

1. Configure remote development using SSH
2. Open and close the sessions multiple times
3. Do a htop on the remote server.
4. Multiple processes from visual studio extensions are started and take up memory

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by roblourens** [comment]
Which processes do you see from which extensions? Need more details.

**Comment by veaceslav** [comment]
![image](https://user-images.githubusercontent.com/2550683/58154348-b87f2600-7c71-11e9-8c0c-a873b6e0d2a9.png)
These are the processes that remain after the VS is closed. They keep adding up if you open and close remote connections repeatedly...

**Comment by roblourens** [comment]
I think these are not actually new processes but different threads in the same process: https://superuser.com/questions/118086/why-are-there-many-processes-listed-under-the-same-title-in-htop

What we expect currently is that the remoteExtensionAgent and server.sh processes will be left behind for old vscode versions, but there is an issue to clean them up: https://github.com/microsoft/vscode-remote-release/issues/203

**Comment by roblourens** [comment]
You can also run the command "Kill VS Code server on remote" to kill them.

**Comment by enricoreich** [comment]
Hello,

I experience the same problem with Remote-SSH after closing VSCode-Insider.

![Screenshot_1](https://user-images.githubusercontent.com/316637/59362391-a9047180-8d33-11e9-827e-205be6e795a8.png)

If I reconnect with VSCode it starts up a new server.sh process with loads of threads AND __it opens a new TCP port__. These ports and processes remain open until I kill all server.sh processes (like this one in the picture) manually. This is **_a big security issue and is unacceptable_**!

The command "Kill VS Code server on remote" literally does nothing except reconnecting the ssh shell.

> Version: 1.36.0-insider (system setup)
> Commit: f291714906cdcb02830b8cfe2485a3c23415b5fe
> Date: 2019-06-12T05:19:53.054Z
> Electron: 4.2.3
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.18362
> Remote-SSH: 0.42.0
