### ISSUE TITLE
Unable to connect to VS Code Remote-SSH on shared web host

### ISSUE THREAD

**Issue by codemaestro** [microsoft/vscode-remote-release#3960]
## Issue Summary:

VS Code Remote-SSH used to connect to the same shared web host. The company assures me that nothing has changed on their end. I can attest that I was able to connect last month. A couple of weeks ago it stopped working. Then suddenly last week I could log in again. Now more frequently the server reports that it fails to start, probable due to the EACCES error in the accompanying log output.

**Note**: On other LINUX servers over which I have full control, VS Code Remote-SSH appears to work fine.

- VSCode Version: 1.50.1
- Local OS Version: macOS 10.14.6 (18G6032)
- Remote OS Version: Linux version 3.10.0-962.3.2.lve1.5.33.el7.x86_64 (mockbuild@buildfarm03.cloudlinux.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Fri Mar 13 09:20:40 EDT 2020
- Remote Extension/Connection Type: SSH

## Steps to Reproduce:

1. CMD+SHIFT+P > Connect current window to host
1. Choose host name (configured in ~/.ssh/config with working SSH key)

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: Yes

## Complete Output of Remote-SSH log file (redacted):

```bash
[08:38:23.396] Log Level: 2
[08:38:23.397] remote-ssh@0.55.0
[08:38:23.397] darwin x64
[08:38:23.398] SSH Resolver called for "ssh-remote+{REMOTE_HOST}", attempt 1
[08:38:23.399] SSH Resolver called for host: {REMOTE_HOST}
[08:38:23.399] Setting up SSH remote "{REMOTE_HOST}"
[08:38:23.407] Using commit id "d2e414d9e4239a252d1ab117bd7067f125afd80a" and quality "stable" for server
[08:38:23.408] Install and start server if needed
[08:38:23.411] Checking ssh with "ssh -V"
[08:38:23.428] > OpenSSH_7.9p1, LibreSSL 2.7.3

[08:38:23.432] Running script with connection command: ssh -T -D 56871 -o ConnectTimeout=1800 {REMOTE_HOST} bash
[08:38:24.807] > 79d2cd782eb3: running
[08:38:24.807] Got some output, clearing connection timeout
[08:38:24.840] > Acquiring lock on /home/{REMOTE_HOME_FOLDER}/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/vscode-remote-lock.{REMOTE_HOME_FOLDER}.d2e414d9e4239a252d1ab117bd7067f125afd80a
> \ln /home/{REMOTE_HOME_FOLDER}/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/vscode-remote-lock.{REMOTE_HOME_FOLDER}.d2e414d9e4239a252d1ab117bd7067f125afd80a.target /home/{REMOTE_HOME_FOLDER}/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/vscode-remote-lock.{REMOTE_HOME_FOLDER}.d2e414d9e4239a252d1ab117bd7067f125afd80a
> Found existing installation at /home/{REMOTE_HOME_FOLDER}/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a...
> XDG_SESSION_ID=c1334692
> SHELL=/bin/bash
> SSH_CLIENT={HOME_IP_ADDR} 56872 {SSH_PORT}
> USER={REMOTE_HOME_FOLDER}
> PASSENGER_INSTANCE_REGISTRY_DIR=/var/passenger
> TMOUT=300
> VSCODE_AGENT_FOLDER=/home/{REMOTE_HOME_FOLDER}/.vscode-server
> PATH=/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/bin:/usr/bin:/opt/cpanel/composer/bin
> MAIL=/var/mail/{REMOTE_HOME_FOLDER}
> PWD=/home/{REMOTE_HOME_FOLDER}
> HOME=/home/{REMOTE_HOME_FOLDER}
> SHLVL=2
> LOGNAME={REMOTE_HOME_FOLDER}
> SSH_CONNECTION={HOME_IP_ADDR} 56872 {REMOTE_IP_ADDR} {SSH_PORT}
> LESSOPEN=||/usr/bin/lesspipe.sh %s
> XDG_RUNTIME_DIR=/run/user/1973
> HISTTIMEFORMAT=%F %T 
> _=/usr/bin/printenv
> Starting server with command... /home/{REMOTE_HOME_FOLDER}/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown --disable-telemetry --socket-path=/run/user/1973/vscode-ssh-remote-server-sock-1604594304 &> "/home/{REMOTE_HOME_FOLDER}/.vscode-server/.d2e414d9e4239a252d1ab117bd7067f125afd80a.log" < /dev/null
> Waiting for server log...
[08:38:25.343] > Waiting for server log...
[08:38:25.835] > Waiting for server log...
[08:38:26.337] > Waiting for server log...
[08:38:26.839] > Waiting for server log...
[08:38:27.341] > Waiting for server log...
[08:38:27.843] > Waiting for server log...
[08:38:28.344] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Server did not start successfully. Full server log at /home/{REMOTE_HOME_FOLDER}/.vscode-server/.d2e414d9e4239a252d1ab117bd7067f125afd80a.log >>>
> 
> 
> *
> * Visual Studio Code Server
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license https://aka.ms/vscode-remote/license
> *
> 
> 
> [11:38:24] Error occurred in server
> [11:38:24] Error: listen EACCES: permission denied /run/user/1973/vscode-ssh-remote-server-sock-1604594304
>     at Server.setupListenHandle [as _listen2] (net.js:1289:21)
>     at listenInCluster (net.js:1354:12)
>     at Server.listen (net.js:1453:5)
>     at pe._start (/home/{REMOTE_HOME_FOLDER}/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostAgent.js:510:445)
>     at pe.start (/home/{REMOTE_HOME_FOLDER}/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostAgent.js:504:816)
>     at processTicksAndRejections (internal/process/task_queues.js:94:5) {
>   code: 'EACCES',
>   errno: 'EACCES',
>   syscall: 'listen',
>   address: '/run/user/1973/vscode-ssh-remote-server-sock-1604594304',
>   port: -1
> }
> <<< End of server log
> 79d2cd782eb3##32##
[08:38:28.344] Received install output: 79d2cd782eb3##32##
[08:38:28.350] Resolver error: Error: The VS Code Server failed to start
	at Function.ExitCode (/Users/{LOCAL_HOME_FOLDER}/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:130495)
	at Object.t.handleInstallOutput (/Users/{LOCAL_HOME_FOLDER}/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:128732)
	at I (/Users/{LOCAL_HOME_FOLDER}/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /Users/{LOCAL_HOME_FOLDER}/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:104774
	at async Object.t.withShowDetailsEvent (/Users/{LOCAL_HOME_FOLDER}/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:109845)
	at async Object.t.resolve (/Users/{LOCAL_HOME_FOLDER}/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:107960)
	at async /Users/{LOCAL_HOME_FOLDER}/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:141955
[08:38:28.352] ------




[08:38:28.640] "install" terminal command done
[08:38:28.640] Install terminal quit with output: 
```

**Comment by roblourens** [comment]
> `> [11:38:24] Error: listen EACCES: permission denied /run/user/1973/vscode-ssh-remote-server-sock-1604594304`

I think this is in `$XDG_RUNTIME_DIR`. Assuming that is not correct or you don't have access to that folder, in which case that variable should be changed

**Comment by codemaestro** [comment]
> > `> [11:38:24] Error: listen EACCES: permission denied /run/user/1973/vscode-ssh-remote-server-sock-1604594304`
> 
> I think this is in `$XDG_RUNTIME_DIR`. Assuming that is not correct or you don't have access to that folder, in which case that variable should be changed

Where is this variable stored, and how can I change it myself? The `/run/user/1973/vscode-` folder doesn't exist, AND I don't have access to that folder since it's outside my home folder.

Is there a way to manually connect VS Code Remote-SSH to a running instance? It seems the .vs-code server is still running on the shared web host when I log in via ssh.

**Comment by roblourens** [comment]
It's an environment variable set up by the system and if it points somewhere that doesn't exist then there is something wrong with the system configuration.

> Is there a way to manually connect VS Code Remote-SSH to a running instance? It seems the .vs-code server is still running on the shared web host when I log in via ssh.

Technically you can start it manually if you run the command in the log at "Starting server with command...", if it doesn't crash in the same way, but we don't really support that usecase.

**Comment by codemaestro** [comment]
Can you explain what is supposed to be available at the location indicated by $XDG_RUNTIME_DIR? My web host says it's an environment variable which has to configure/change on the server via root privileges. I don't have root privileges on this server, and have never needed it to use VS Code Remote-SSH. Did something change in the past couple of release that would require a different environment variable to be used?

**Comment by roblourens** [comment]
Here is some documentation, but this hasn't changed on our end. https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

I think that path should only be hit if you set `remote.SSH.remoteServerListenOnSocket`, did you change that setting recently?
