### ISSUE TITLE
Dispose callback in tunnel api not working as expected

### ISSUE THREAD

**Issue by wachaudh** [microsoft/vscode-remote-release#3961]
- VSCode Version:1.51.0-insider
- Local OS Version: Darwin x64 19.5.0

The [dispose callback](https://github.com/microsoft/vscode/blob/9c008472444ff8d4a3e64f5ee576d28e6c7cc457/src/vs/vscode.proposed.d.ts#L209) in the tunnel api is not behaving as expected. I expected the dispose callback to get invoked when I stop forwarding a port but it doesn't do anything. Seems like [ClosePortAction](https://github.com/microsoft/vscode/blob/0a1b71121c8eb7bddd480b23fbf3826530f9609d/src/vs/workbench/contrib/remote/browser/tunnelView.ts#L829) should be getting referenced in remote explorer like ForwardPortAction and OpenPortInBrowserAction but it's missing. [This](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/Cascade?path=%2Fvscode%2Fcodespaces%2Fsrc%2FcodespacesResolver.ts&version=GBmaster&line=332&lineEnd=332&lineStartColumn=9&lineEndColumn=40&lineStyle=plain&_a=contents) is our implementation of the tunnel api.

**Comment by wachaudh** [comment]
cc: @alexr00

**Comment by alexr00** [comment]
@wachaudh this should be fixed now. Can you confirm whether it's working in insiders?
