### ISSUE TITLE
Unable to open project in WSL2 using "Reopen Folder in WSL..." command

### ISSUE THREAD

**Issue by abarani** [microsoft/vscode-remote-release#3964]
- VSCode Version: 1.51.0 (also tested with 1.52.0-insider 24b28f57)
- OS Version: Windows 10 19041.572 with Ubuntu 20.04 under WSL2

Steps to Reproduce:

1. Open folder under WSL2 file system (using `\\wsl$\Ubuntu-20.04` remote path) using `File > Open folder...`
2. Use `Remote-WSL: Reopen Folder in WSL...` command
3. "Unable to read file" error is shown.

Does this issue occur when all extensions are disabled?: Yes (apart from WSL Remote extension)

This is working correctly with version 1.50.1.

![image](https://user-images.githubusercontent.com/2650264/98360213-b6598480-2029-11eb-8f49-c84425a2f341.png)

**Comment by dittrm** [comment]
I'm not sure, if it's the same problem but if I try to launch VSCode from the wsl console nothing happens. So I open it up manually `Remote-WSL: Reopen/Open Folder in WSL ` and the VSCode Server crashes immediately.

"VS Code Server for WSL closed unexpectedly."
"WSL Daemon exited with code 0"

Version: 1.51.0
OS: Windows_NT x64 10.0.19042
WSL version: 4.19.104-microsoft-standard Debian

**Comment by aeschli** [comment]
Pushed a fix for `Reopen Folder in WSL`  in 0.51.2 released yesterday. Can you test if that solved your issue?

**Comment by abarani** [comment]
This is working as expected now, thank you!

**Comment by dbaeumer** [comment]
Marking as verified according to @abarani comment.
