### ISSUE TITLE
Don't show WSL notifications on macOS

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-remote-release#3965]
![image](https://user-images.githubusercontent.com/35271042/98404403-5a89fe00-201f-11eb-90f5-4e9b7dae113b.png)

I received this notification as I had WSL installed (likely due to Settings Sync). IMO, I shouldn't get any notifications on a platform that isn't supported (i.e. mac)

**Comment by aeschli** [comment]
Fixed in 0.51.2 released yesterday.
