### ISSUE TITLE
Inconsistent file preview behavior when opening local and remote files (updated)

### ISSUE THREAD

**Issue by Caian** [microsoft/vscode-remote-release#3969]
With default File Preview settings, when opening a local file using the open file dialog (File > Open File), the opened file does not open as a preview. But when opening a remote file using the same method, though through the file path pop-up, it opens as a preview.

I disabled `Preview From Quick Open`, but the problem remains. The only way to disable this behavior is through the `Enable Preview` setting which is editor-wide and therefore undesirable.

I find this behavior inconsistent because they are both commands to open a file.

- VSCode Version: 1.52.0-insider
- Local OS Version: Linux Mint 19.3
- Remote OS Version: Linux Mint 19.3
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open a file using `File > Open File` menu
2. The file should not open as preview
3. Connect to a remote server though SSH
4. Open a remote file
5. The file should open as preview

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

This is an updated version of the issue #3239 that was closed by @roblourens without clarification or solution.

**Comment by roblourens** [comment]
Issues can be reopened
