### ISSUE TITLE
`containerWorkspaceFolder` is being replaced by workspace file path

### ISSUE THREAD

**Issue by asilva-pwc** [microsoft/vscode-remote-release#3973]
- VSCode
  Version: 1.51.0
  Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
  Date: 2020-11-05T18:14:40.758Z
  Electron: 9.3.3
  Chrome: 83.0.4103.122
  Node.js: 12.14.1
  V8: 8.3.110.13-electron.0
  OS: Darwin x64 19.6.0

- Local OS Version: macOS Catalina 10.15.7 (19H15)
- Remote OS Version:  Debian 10
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open VS Code command palette and choose "Remote-Containers: Open Workspace in Container..."
2. Choose a workspace file (*.code-workspace)
3. When the devcontainer.json file is loaded, the `containerWorkspaceFolder` variable is replaced by the path of the workspace file, nor the workspace folder.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
Tracked by #3942.
