### ISSUE TITLE
Remote SSH workspace frequently disconnects, requires reentering password or reloading window

### ISSUE THREAD

**Issue by vittvolt** [microsoft/vscode-remote-release#3974]
Issue Type: <b>Bug</b>

With the window connected to a remote location via ssh, let the window sit idle for a while and the connection is down after a while.

Extension version: 0.55.0
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:14:40.758Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.4.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 6, 4|
|Memory (System)|16.00GB (1.35GB free)|
|Process Argv|-psn_0_622744 --crash-reporter-id c18aee71-dfc4-4f5a-9196-c2f998797d64|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 127.0.0.1|
|OS|Linux x64 5.4.0-52-generic|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (1 x 3095)|
|Memory (System)|1.64GB (0.07GB free)|
|VM|100%|
</details>

**Comment by eventualbuddha** [comment]
I've had this same behavior. It seems worse for larger projects, anecdotally. I just tried applying this change to my `sshd_config` to see if it helps: https://unix.stackexchange.com/a/446441.

**Comment by roblourens** [comment]
If the window is not connected (eg the computer is asleep) then the remote will time out and disconnect after some number of hours. If it is connected, here are some things that can cause disconnections in an active window
- Extensions or other processes using lots of CPU or memory
- Very large workspaces that cause VS Code's filewatcher process to use lots of memory
- Anything that disrupts the network connection between the local and remote machines
