### ISSUE TITLE
Dev-container with Podman: Post create and post start scripts will cause errors when Podman is used as Container engine

### ISSUE THREAD

**Issue by PavelSosin-320** [microsoft/vscode-remote-release#3976]
While Entry-script is a part of Docker image metadata, post-create is defined only at VSCode project level.
Podman executes entry-script when starting Pod's containers and  assumes that Container environment is configured.
This is Design bug too!
Podman executes entry-script for every started container based on Container's metadata. It knows how to start container without any VSCode configuration.
It knows about ontainer's image everything and exposes it to orchestration engine.
To initialize Container Podman uses Host Kernel mechanism and Container's built-in initialization method, mostly systemd.
- Remote Extension/Connection Type: /Docker - Podman

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
Please clarify, what is the error you are seeing?
