### ISSUE TITLE
I'm still seeing `docker-desktop` and `docker-desktop-data` in the distro selection dialog.

### ISSUE THREAD

**Issue by uishon** [microsoft/vscode-remote-release#3977]
Although looks like this issue has been resolved back in September - see 
fix posted by @aeschli in https://github.com/microsoft/vscode-remote-release/issues/3081#issuecomment-689474589 - I'm still seeing it in my VS Code. Running latest version (v0.51.1) of the Remote-WSL extension. What am I missing?

**Comment by aeschli** [comment]
I just tested that it works for me on 0.51.1.
Can you run `wslconfig /l` in a windows command prompt and paste the output?

**Comment by uishon** [comment]
Sure. Here.

    Windows Subsystem for Linux Distributions:
    Ubuntu-18.04 (Default)
    docker-desktop-data
    docker-desktop
    Ubuntu-20.04

**Comment by aeschli** [comment]
Can you take a screenshot of the dialog where you see the items? Or is the remote explorer?

**Comment by uishon** [comment]
In the remote explorer. 

![image](https://user-images.githubusercontent.com/10066601/98524723-3d079f00-2280-11eb-931e-5a1ba607b2aa.png)

**Comment by aeschli** [comment]
Ok, thanks, will fix.

**Comment by aeschli** [comment]
Fix is in 0.51.2. If you can verify that would be great.

**Comment by uishon** [comment]
Verified. It works :-). Thanks.

**Comment by dbaeumer** [comment]
Marking as verified due to @uishon comment.
