### ISSUE TITLE
Extension stuck after connection due to tcp forwardning fails

### ISSUE THREAD

**Issue by Mohjive** [microsoft/vscode-remote-release#398]
I can connect to the server but not connect to the remote resources (open folder/see extensions). The extension stalls after connection with the following output in the console:
```
You are connected to: <host>
channel 3: open failed: administratively prohibited: open failed
channel 3: open failed: administratively prohibited: open failed
channel 4: open failed: administratively prohibited: open failed
```
I login using public key authentication without password. It looks similar to #297 but there's no load balancing in the environment I use.

**Comment by roblourens** [comment]
Is it possible that tcp forwarding is disabled on the server via AllowTCPForwarding?

**Comment by Mohjive** [comment]
I did try local port forwarding (-L) and that works. I’ll try remote and dynamic (it would be easier if I knew what type of forwarding remote-ssh tried to set up) tomorrow. And I’ll see if I can check sshd config to see how it’s set up.

**Comment by roblourens** [comment]
We just use local port forwarding.

Another issue that's showed up, is it possible that you attach to a system which dynamically routes to you one of multiple nodes? This is an issue for us because we use multiple ssh calls to connect.

**Comment by Mohjive** [comment]
No, only one node/server. That’s what I tried to explain by referring to the other issue and mention that we don’t use load balancing.

**Comment by roblourens** [comment]
Sorry I'm jumping between a lot of issues today 😁 

Maybe the full log from the "Remote - SSH" output channel would help.

**Comment by Mohjive** [comment]
Tried to find that log or where to enable it, but failed. The window reloads a couple of times and the logs are lost to me. Where can I find them?

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Comment by Mohjive** [comment]
Thanks! Didn't think of the dropdown selection...

I've anonymized <alias>, <host>, <welcome message> and <GUID> (I don't know if the last one was necessary, but I'm catious :) )

I also tried to run the last command `ssh -F h://.ssh/config <alias> -L localhost:13280:localhost:38615` in git bash and it worked without issues.

My _.ssh/config_ is as below (only one entry)
`# Read more about SSH config files: https://linux.die.net/man/5/ssh_config
Host <alias>
    HostName <host>
    User <username>`

Output from Remote - SSH:
`SSH Resolver called for "ssh-remote+<alias>"
SSH Resolver called for host: <alias>
Setting up SSH remote "<alias>"
Using commit id "4ca38ce5584d7cd67b435b3c32ef1240c6a29628" and quality "insider" for server
Using SSH config file "h://.ssh/config"
Install and start server if needed
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> 
<welcome message>
> 
> You are connected to: <host>
> 
> bash: no job control in this shell
> 
> Found existing installation...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> <GUID>
> 
"install" terminal command done
Received install output: <GUID>
Server is listening on port 38615
Using SSH config file "h://.ssh/config"
Spawning tunnel with: ssh -F h://.ssh/config <alias> -L localhost:13280:localhost:38615 "echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity"
Spawned SSH tunnel between local port 13280 and remote port 38615
Waiting for ssh tunnel to be ready
> 
<welcome message>
> 
> You are connected to: <host>
> 
Tunneling remote port 38615 to local port 13280
Resolving "ssh-remote+<alias>" to "localhost:13280", attempt: 1
> channel 3: open failed: administratively prohibited: open failed
> 
> channel 3: open failed: administratively prohibited: open failed
> channel 4: open failed: administratively prohibited: open failed
> 
> Connected to SSH Host - Please do not close this terminal
> `

**Comment by Mohjive** [comment]
I tried to open a tcp session using a redirected port I manually set up, as above. Using netcat to listen on the local port on the remote host and putty to connect to the raw, redirected socket on localhost. Then I get the same message as previously on the remote side: `channel 9: open failed: administratively prohibited: open failed`

**Comment by roblourens** [comment]
Thanks, no new info in the log unfortunately.

> I tried to open a tcp session using a redirected port I manually set up, as above.

I'm not sure I understand exactly what you did here but it sounds like you see the same error when you try to forward a port over ssh the same way, right?

In any case it just sounds like we are not allowed to forward ports on that server for some reason...

**Comment by Mohjive** [comment]
> I'm not sure I understand exactly what you did here but it sounds like you see the same error when you try to forward a port over ssh the same way, right?
Yes, `ssh -L localhost...`, with the same ports as Remote - SSH tried to use. The ssh command worked and I could start netcat to listen on the port on the server, but when I tried to connect to the TCP tunnel from the workstation I got the error above (on the netcat/server side).

**Comment by roblourens** [comment]
Ok. It definitely sounds like `AllowTCPForwarding` is disallowed on the server. Can you check that?
