### ISSUE TITLE
Remote ssh fails to connect in version 0.54.0 and 0.55.0

### ISSUE THREAD

**Issue by tkreind** [microsoft/vscode-remote-release#3982]
- VSCode Version:
1.51.0
- Local OS Version:
MacOS 10.15.7
- Remote OS Version:
Red Hat Enterprise Linux Server 7.8 (Maipo)
- Remote Extension/Connection Type: SSH/Docker/WSL
SSH

Steps to Reproduce:

<img width="500" alt="Screen Shot 2020-11-08 at 7 16 24 PM" src="https://user-images.githubusercontent.com/5393759/98488491-79db8380-21f7-11eb-9b4c-a394913254da.png">

1. Frequently connect to a remote ssh server with extension version 0.54.0 or 0.55.0, possibly having a disconnect or something interrupting connection.
2. Try to connect and have it fail, somewhat randomly, usually 4 or 5 days into connecting to a server frequently.

Noteworthy: Something changed in the jump to 0.51.0 to 0.54.0, I use 0.51.0 without issue frequently, but whenever I try upgrading to the newer version I frequently get this error. It's temporarily fixable by deleting the file that it says it's locking on in another ssh window, but as this isn't an issue with 0.51.0 it should be fixable.

Does this issue occur when you try this locally?: Yes/No
N/A
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No
N/A

**Comment by roblourens** [comment]
You could see whether running the command "Kill vs code server" and trying again unblocks you when this happens. Or you could try setting `"remote.SSH.useFlock": false` to see if that makes a difference.

**Comment by robkut** [comment]
I had the same issue after update, but a restart of my RHEL remote machine fixed it
