### ISSUE TITLE
Improved intellisense for C++ Remote WSL & Remote SSH 

### ISSUE THREAD

**Issue by codersguild** [microsoft/vscode-remote-release#3985]
Currently, IntelliSense doesn't seem to work with remote SSH or remote WSL (a typical scenario would be an SSH to a Ubuntu VM). Is there a way to improve it?

**Comment by codersguild** [comment]
You are right, WSL isn't involved. The C++ IntelliSense doesn't seem to work for Remote SSH and Remote WSL both.

**Comment by aeschli** [comment]
That should work. Can you file it against the c++ extension that you use?
