### ISSUE TITLE
Remote-Containers: "Open Folder in Container" leads to endless searching when using wsl-share on wsl2

### ISSUE THREAD

**Issue by Cyber1000** [microsoft/vscode-remote-release#3988]
- VSCode Version: 1.51.0
- Local OS Version: Win 10 Home - 2004 - 19041.572
- Remote OS Version: Ubuntu 20.04 on WSL2
- Remote Extension/Connection Type: Docker (running with WSL2-engine)

Steps to Reproduce:

I'm new to WSL in general and docker on windows, but not new to Windows, Linux and Docker on linux.
Installed wsl2, docker desktop 2.5.0.0, ubuntu 20.04 in wsl just yesterday, so really fresh and clean.

1. From here: https://code.visualstudio.com/docs/remote/containers#_quick-start-open-an-existing-folder-in-a-container
    - Remote-Containers: Open Folder in Container...
2. Since it's wsl2 there is an information (see https://code.visualstudio.com/docs/remote/containers#_open-a-wsl-2-folder-in-a-container-on-windows), that accessing /mnt/c is slow, so moved my files to my ubuntubox and enter: \\wsl$\Ubuntu-20.04\home\internal\hello-2
3. Now it seems to search a lot of files and directories outside of \\wsl$\Ubuntu-20.04\home\internal\hello-2, even the root path (see screenshot) or /media, and even /mnt. Just for clarification: "internal" is my user I created on ubuntu
4. vscode is unresponsive, sometimes even my ubuntu on wsl2 hangs indefinitely, my computer get's sometimes slow too.
5. After some minutes either:
   a. ubuntu on wsl2 is dead
   b. I can continue selecting "a base dev container definition", like go or whatever.
6. 
   - If 5a -> kill wsl and restart
   - If 5b -> .devcontainer is created and the next time I start this it works immediately

I've searched some threads of vscode, wsl, even ubuntu/docker. I don't know exactly where the extensive search of my wsl-ubuntu comes frome, but it seems that it's vscode related. Hope you can help me here.

Thanks!

![image](https://user-images.githubusercontent.com/1142765/98591867-2a698600-22d1-11eb-868c-28ae83c19047.png)

**Comment by Cyber1000** [comment]
Tried even this now: https://github.com/microsoft/WSL/issues/4966#issuecomment-649503585
Wanted to exclude that the problem is because of an error with PATH-variable, but that doesn't seem to change anything here ...

**Comment by Cyber1000** [comment]
- Disabled all extensions in vscode (except the remote ones) -> error still here
- Just tried VSCode insider-edition and the error seems to have vanished, there are only 4 errors and these files really don't exist, so valid errors ...
   - and it works fast ...
Can someone point me to the fix? hope I haven't overlooked something

What's the release-plan for this 1.52-version?

![image](https://user-images.githubusercontent.com/1142765/98596764-3573e480-22d8-11eb-9cbe-48d1ae62b04a.png)

**Comment by chrmarti** [comment]
@Cyber1000 Fixing this with 0.148.1 for VS Code 1.51. (The schedule for 1.52 is not published yet.)

**Comment by chrmarti** [comment]
@Cyber1000 Could you verify 0.148.1 fixes this issue for you?
