### ISSUE TITLE
WSL: PowerShell hangs during startup from the WSL bash terminal

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/vscode-remote-release#399]
- VSCode Version: 1.35.0 / 2019-05-21
- Local OS Version: Windows 10 1903
- Remote OS Version: Ubuntu 18.04.2 LTS
- Remote Extension/Connection Type: SSH/Docker/WSL WSL

Steps to Reproduce:

1. Install PowerShell Core 6.2.0 in your WSL distro
2. Start a WSL - New Window session
3. Open the default (bash) terminal
4. Execute `pwsh -noprofile`

You'll see the PowerShell startup message but the prompt never comes back.  You can't even <kbd>ctrl+c</kbd> out (although you can background the process). 

Does this issue occur when you try this locally?: Doesn't apply really
Does this issue occur when you try this locally and all extensions are disabled?: Not sure how to get WSL New Window to start without extensions loaded.

**Comment by TylerLeonhardt** [comment]
Hey @rkeithhill! I opened an issue about this a couple days ago :) https://github.com/microsoft/vscode-remote-release/issues/356

**Comment by rkeithhill** [comment]
Duplicate of #356
