### ISSUE TITLE
Listing Containers on a Remote Docker Host fails with "spawn C:\Program Files\Microsoft VS Code\docker ENOENT"

### ISSUE THREAD

**Issue by ecetiner87** [microsoft/vscode-remote-release#3990]
🚨 The issue tracker is not for questions 🚨
Hi all,

There is a strange issue that we came across at our development environment. We have a Remote Docker Host - Centos 7 VM- ; running multiple containers on top of it and **everyone can access Containers from their local Windows 10 machine without issue**. 

However; one of our colleague could not list Containers from his VSCode and when we check logs from **Show Log** he gets following error:

_Remote-Containers 0.148.0 in VS Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c).
[7762 ms] Start: Run: docker version --format {{.Server.Version}}
[7768 ms] **spawn C:\Users\james.murtaugh\AppData\Local\Programs\Microsoft VS Code\docker ENOENT_**

We use SSH Tunneling to connect remote VM as described in https://code.visualstudio.com/docs/remote/troubleshooting . We have exact same environment and settings.json files in each local pc:

-     VSCode Version:1.51.0
-     Local OS Version:Windows 10 
-     Remote OS Version:Centos 7.8
-     Remote Extension/Connection Type: Remote-Containers
-     Remote-Containers Extension Version: 0.148.0

settings.json

```
{
    "git.autofetch": true,
    "git.ignoreLegacyWarning": true,
    "cmake.configureOnOpen": false,
    "terminal.integrated.shell.linux": "/bin/bash",
    "remote.SSH.remotePlatform": {
        "172.16.31.77": "linux",
        "10.32.7.35": "linux"
    },
    "docker.host": "tcp://localhost:23750"
 
}
```

Also; remote-SSH works fine with his VSCode to this specific VM; however he could not list Containers on that VM when he select Containers from list at Remote Explorer.

**Comment by ecetiner87** [comment]
We figured it out; it seems that even service not needed; we need docker-cli on local machines as well to work on remote docker host's containers. We installed docker desktop on his machine and then we can successfully list containers on his VScode as well.

**Comment by bidipeppercrap** [comment]
> We figured it out; it seems that even service not needed; we need docker-cli on local machines as well to work on remote docker host's containers. We installed docker desktop on his machine and then we can successfully list containers on his VScode as well.

How do you install docker-cli (Not Docker Desktop) in Windows 10?

**Comment by PavelSosin-320** [comment]
@bidipeppercrap From Chocolattery. Its repository has the same version.

**Comment by bidipeppercrap** [comment]
> @bidipeppercrap From Chocolattery. Its repository has the same version.

But it is  ma little outdated

**Comment by PavelSosin-320** [comment]
Docker [Choco Docker CLI 19.03](https://chocolatey.org/packages/docker-cli) is the recent specification. Most Docker engine implementations support this spec as 1.40 REST API.  Docker Desktop supports the same spec. I tried it - it was OK. All my Docker CLIs on Linux are 19.03 too. I think that it poses a lower risk than the unstable DockerDesktop CE Edge startup procedure.

**Comment by PavelSosin-320** [comment]
@bidipeppercrap I just tested upgraded the upgraded DockerCLI 19.03.12 from Choco with DockerDesktop engine and it is OK. I recommend it to everybody who wants to save disk space and startup time when working with a remote Docker engine.
