### ISSUE TITLE
Uses too much processing power and Docker crashes on MacOS

### ISSUE THREAD

**Issue by 1st** [microsoft/vscode-remote-release#3993]
Issue Type: <b>Bug</b>

1. Attached to an existing Docker container (but I did also the same thing before with the creation of the Docker container by VS Code - result is the same).
2. When attached to container it starts to use too much processor power and coolers on my MacBook Pro start to work hard
3. After ~10 minutes the VS Code tells about need to reconect
4. At the same time I see that my Docker on MacOS doesn't respond
5. I restart the Docker and all works okay for the next 10 minutes...

I use MacOS 10.15.7 and Docker Desktop 2.5.0.0

Extension version: 0.148.0
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:14:40.758Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.4.39-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 5|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id 03f93316-85d9-46bc-bf9e-934bbede8a89|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container global-citizen-20_app (/gc-ap…|
|OS|Linux x64 5.4.39-linuxkit|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (6 x 2200)|
|Memory (System)|5.81GB (2.33GB free)|
|VM|0%|
</details>

**Comment by 1st** [comment]
Just to note. Then I do not attach via VS Code Remote extension to my running Docker container - it works okay for weeks and I use it normally. Seems that some process is added to the Docker container when I run the VS Code connected to the Docker container.

**Comment by 1st** [comment]
In about 10 minutes I see next alert from VS Code
<img width="634" alt="image" src="https://user-images.githubusercontent.com/630224/98680418-0c9c2f80-236a-11eb-86e2-168ba0cda3d3.png">

then I go to terminal and check if Docker alive:
```sh
% docker ps
Error response from daemon: Bad response from Docker engine
```

**Comment by 1st** [comment]
The `htop` output just after connected to the Docker container from the VS Code:
<img width="1629" alt="image" src="https://user-images.githubusercontent.com/630224/98694717-7a505780-237a-11eb-9868-9710b2517845.png">

The `Remote Containers: Show log` output:
<img width="1629" alt="image" src="https://user-images.githubusercontent.com/630224/98694845-a7046f00-237a-11eb-853b-5500efd99eac.png">

The `Docker Desktop` stats for the running docker container:
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/630224/98695171-02cef800-237b-11eb-8c64-7b05290bc3ea.png">

**Comment by 1st** [comment]
Few minutes later...

Restarted the Docker. Waited when coolers stop working so crazy 😜 

Ran my Docker container again. but this time without attaching the VS Code to the container, like I did before.

The `stop` output:
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/630224/98695981-ec756c00-237b-11eb-89f7-45fc24efdbdc.png">

The `Docker Desktop` stats for the running docker container:
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/630224/98696100-10d14880-237c-11eb-931c-305bc385c804.png">

Something is wrong with the VS Code Remote Container plugin. Can you please check it and let me know, can you find the issue on your Mac computer?

**Comment by 1st** [comment]
Any updates? @JacksonKearl @Chuxel

**Comment by chrmarti** [comment]
@1st What's the command you use to create the container?

**Comment by 1st** [comment]
@chrmarti I run the Docker-compose via VS Code, and then tried to run it myself and then attach to the running container.

As you can see, the Docker container without attached VS Code works almost silently, using almost no resources. But as soon as I attach the VS Code to it -- it starting use 2 GB of memory! It's strange behavior.

**Comment by 1st** [comment]
> @1st What's the command you use to create the container?

`docker-compose -f compose-app.yml up -d`

**Comment by chrmarti** [comment]
Could you attach your configuration? (devcontainer.json, docker-compose.yml, Dockerfile)
