### ISSUE TITLE
Remote window terminal fails with "Error: spawn C:\WINDOWS\System32\wslconfig.exe ENOENT"

### ISSUE THREAD

**Issue by koww** [microsoft/vscode-remote-release#3994]
- VSCode Version: 1.51.0
- Local OS Version: Windows 10
- Remote OS Version: CentOS 7.8
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Access remote SSH targets
2. Check the terminal tab, there it is

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Not affordable to try.

**Comment by koww** [comment]
It is resolved with reset the settings. Not a bug.

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode-remote-release/issues/3999
