### ISSUE TITLE
Remote Terminal Processes are not killed on exiting VS Code

### ISSUE THREAD

**Issue by awadell1** [microsoft/vscode-remote-release#3995]
- VSCode Version: 
Version: 1.51.0 (user setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:18:23.642Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

- Local OS Version: Windows 10 Home Build 19041.572
- Remote OS Version: CentOS Linux Version 7 (Core)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open a Remote - SSH Connection
2. Using the terminal start a REPL session (I've reproduced this with Julia + python)
3. Close VS Code without clicking on the Trash Icon (ie. don't kill the terminal)
4. Connect to the remote with ssh and confirm that the REPL process is still running

Does this issue occur when you try this locally?: No, the process is killed as soon as I close VS Code
Does this issue occur when you try this locally and all extensions are disabled?: No, the process is killed as soon as I close VS Code

This is particularly painful as REPL sessions can take up a decent amount of resources, and this appears to be causing them to accumulate on our cluster's headnode.

**Comment by roblourens** [comment]
Yes, terminal sessions will now live for a little while longer and will be reconnected when connecting to the remote again. The extra time they live depends on the situation, but up to 3 hours.

It can be disabled with `"terminal.integrated.enablePersistentSessions": false`
