### ISSUE TITLE
Detect open/closed ports dynamically independent of the output to the console

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#3996]
Currently ports are automatically detected and opened based on output matched in the console or the debug terminal.

The issue is that some popular apps/tools do not print the port they are listening on the console. For example, an express app generated with the express-gen app, to test open https://github.com/egamma/express-app in a remote container.

To avoid that users do not have to manually forward ports in these case we should automatically detect opened/closed ports based on system information.

Testing https://github.com/microsoft/vssaas-planning/issues/1531

**Comment by egamma** [comment]
https://github.com/github/codespaces/issues/1555

**Comment by alexr00** [comment]
With f19b19018c05ff24e4e9ecd01db04fc6055d4e39 this is complete.
