### ISSUE TITLE
Open remote folder on empty folder in Linux WSL filesystem hangs system for several minutes

### ISSUE THREAD

**Issue by Neutrino-Sunset** [microsoft/vscode-remote-release#3997]
Issue Type: <b>Bug</b>

If I select "Remote-Containers: Open Folder in Container..." on an empty folder on the WSL Linux filesystem, the System process sits at full CPU saturation for about 4 minutes making the entire system completely unusable, after which the VsCode dropdown to "Add development container configuration files" finally appears.

Does the same thing if you point it at a folder that already contains a complete node project with no .devcontainer folder.

It didn't do this a couple of days ago before I installed the latest Docker Desktop update, but no idea whether that's related or just coincidence.

This is on Win 10, with latest Docker Desktop configured to use WSL 2.

Extension version: 0.51.1
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2111)|
|Memory (System)|12.43GB (10.07GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Could you try the latest version of Remote-Containers (0.149.0) which currently requires VS Code Insiders (https://code.visualstudio.com/insiders/)?

If it still occurs there, please attach the dev container log from when the dropdown opens. (`F1` > `Remote-Containers: Show log`).

**Comment by Neutrino-Sunset** [comment]
That works great with version 0.149.0 I get the dropdown to choose a base image in a couple of seconds.

I don't know whether the policy is to close this issue now or leave it open until the insiders build hits release.

**Comment by chrmarti** [comment]
I'll close the issue. If there were a lot of users hitting the issue we would consider backporting the fix. Thanks.
