### ISSUE TITLE
Git not working when opening WSL2 folder in container

### ISSUE THREAD

**Issue by thor4** [microsoft/vscode-remote-release#3998]
I set the following locally **and** in my WSL2 instance with my actual GitHub info:
```
git config --global user.name "Your Name"
git config --global user.email "your.email@address"
```
However, when I open a WSL2 folder in a remote container and try to make an initial commit, I get an error stating "make sure you configure your 'user.name' and 'user.email' in git. Git log shows: 
```
fatal: unable to auto-detect email address (got 'root@36aacb19a08c.(none)')
> git config --get-all user.name
```
When I checkout the config in the terminal I am presented with the following: 
```
(base) root@36aacb19a08c:/workspaces/neuroimaging# git config --list
credential.helper=!f() { /root/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6e9156c2f0c/node /tmp/vscode-remote-containers-ab525e0935bb16981dd337f94d9194611d0a79b0.js $*; }; f
credential.helper=!f() { /root/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6e9156c2f0c/node /tmp/vscode-remote-containers-ab525e0935bb16981dd337f94d9194611d0a79b0.js $*; }; f
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
```

Please advise. Thanks for your help.

**Comment by chrmarti** [comment]
We copy WSL's `~/.gitconfig` to the container unless there already is a `~/.gitconfig` in the container. Please check if your container already has one.

**Comment by thor4** [comment]
Thanks that helped. I guess the WSL gitconfig does not automatically pull from the local Windows gitconfig. I set it manually on WSL, reloaded the container and voila.

Thanks again for the help!

**Comment by bamurtaugh** [comment]
Thanks for the discussion here! It sounds like the issue was resolved, but if anything persists/returns, please feel free to let us know.
