### ISSUE TITLE
Error: spawn C:\WINDOWS\System32\wslconfig.exe ENOENT

### ISSUE THREAD

**Issue by androllen** [microsoft/vscode-remote-release#3999]
- VSCode Version: 1.51.0
- Electron: 9.3.3
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. open vscode 
2. terminal pop up `[2020-11-11 02:27:50.107] Error: spawn C:\WINDOWS\System32\wslconfig.exe ENOENT`

Does this issue occur when [Remote - WSL ms-vscode-remote.remote-wsl](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)  Extension Packs are enabled?: Yes
Does this issue occur when [Remote - WSL ms-vscode-remote.remote-wsl](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)  Extension Packs are disabled?: No

**Comment by tbighetti** [comment]
Update extension "Remote - WSL" - It worked for me

**Comment by aeschli** [comment]
Pushed a fix for 0.51.3
