### ISSUE TITLE
Remote file picker input can backtrack while holding the delete key

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-remote-release#4]
**repo**
1. Open a remote folder (tested with containers and wsl)
1. Open remote file open dialog
1. Start at the end of the path and hold the delete key

**Bug**
While deleting, a segment of deleted path will sometimes be restored

![Apr-26-2019 11-59-54](https://user-images.githubusercontent.com/12821956/56830309-de540f00-681a-11e9-8772-2900d28d6f80.gif)

**Comment by Keno** [comment]
I assume that's covered under this issue, but I see the same behavior with input other than backspace. If I add additional characters before the UI had a chance to offer completions, it'll mess up the input trying to provide the completion. On a moderate latency connection, this happens basically on every key stroke for me.

**Comment by rebornix** [comment]
![remote-file-picker](https://user-images.githubusercontent.com/876920/58651386-05907700-82c6-11e9-868e-fabb4360dc70.gif)

If I deleted quickly, I can see flashing in the remote file picker. Reopen it but it's not a blocker of the release.

**Comment by alexr00** [comment]
This bug is slightly different from the original in that the added text is selected, so it deletes faster.
