### ISSUE TITLE
Error: ENOSPC: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by grantcarthew** [Microsoft/vscode-remote-release#40]
Issue Type: <b>Bug</b>

Looks like the Remote - SSH extension, which is brilliant by the way, opens a few fs watchers. A few too many that is.

Edit: I should add I was trying to run Jest with the --watch option.

System: Hyper-V VM running Debian Sid.
Linux Dev 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux

[Linux: watcher can produce ENOSPC when too many handles open](https://github.com/Microsoft/vscode/issues/7950)

Regards @grantcarthew

Extension version: 0.34.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.9.0-9-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (13.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev|
|OS|Linux x64 4.9.0-9-amd64|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (4 x 2518)|
|Memory (System)|9.74GB (8.24GB free)|
|VM|0%|
</details>

**Comment by kieferrm** [comment]
@grantcarthew try this: https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc.

**Comment by grantcarthew** [comment]
Thanks @kieferrm although I didn't try to fix it. After getting Remote -SSH up and running, very excitedly I might add, I found I didn't get much benefit from it.

My development workflow involves running a Jest test file in watch mode using [Black-Box testing](https://medium.com/@grantcarthew/black-box-testing-a-node-js-web-api-d626f7d651be) and writing code to make the test pass. The odd console.log/dir is all I need.

I ssh into the VM to run the tests and write my code to a mapped drive (SAMBA).

I still think this is a great extension, don't get me wrong.

**Comment by kieferrm** [comment]
No worries. Needs to fit your needs.
