### ISSUE TITLE
Remote SSH Python Workspace

### ISSUE THREAD

**Issue by fabricioradtke** [microsoft/vscode-remote-release#400]
Issue Type: <b>Bug</b>

When using the Remote SSH extension and open two, or more folders in same workspace, has a problem with the Python interpreter. It shows an alert saying "Select Python Interpreter" and chosing a interpreter don't resolve.

Extension version: 0.37.0
VS Code version: Code - Insiders 1.35.0-insider (a5536b8f5a16a10d859f3dec1e59701671bf069e, 2019-05-20T05:15:35.934Z)
OS version: Linux x64 4.4.0-148-generic
Remote OS version: Linux x64 4.4.0-66-generic

**Comment by roblourens** [comment]
Please open this issue on the Python extension repo: https://github.com/microsoft/vscode-python/issues
