### ISSUE TITLE
I can´t connect to a remote ssh server

### ISSUE THREAD

**Issue by Lyted21** [microsoft/vscode-remote-release#4001]
- VSCode Version: 1.51.0
- Local OS Version: Windows 10 Home
- Remote OS Version: i don´t know unfortunately but i can connect to it via windows cmd
- Remote Extension/Connection Type: SSH

Does this issue occur when you try this locally?: No

in the vscode command palette says "Cannot mkdir: Disk quota exceeded

**Comment by roblourens** [comment]
> Cannot mkdir: Disk quota exceeded

This probably simply tells you that the remote disk is full
