### ISSUE TITLE
Predefined variables Bug.

### ISSUE THREAD

**Issue by dbwodlf3** [microsoft/vscode-remote-release#4002]
- VSCode Version: 1.51.0(user setup)
- Local OS Version: Windows10
- Remote OS Version: Ubuntu18.04
- Remote Extension/Connection Type: SSH/Docker/WSL: SSH

Steps to Reproduce:

I try to use Predefined Variables in settings.json like ${workspaceFolder}
but, it doesn't work.

example.
```json
{
    "python./pythonPath": "/usr/bin/python3",
    "python.autoComplete.extraPaths": [
        "${workspaceFolder}/src/ConstraintGenerator"
    ],
}
```
It doesn'twork.

but it works.
```json
{
    "python./pythonPath": "/usr/bin/python3",
    "python.autoComplete.extraPaths": [
        "/home/swlab/smc/src/ConstraintGenerator"
    ],
}
```

I think this problem is different character in debian and windows10 or just not yet applied...
my local host is windows10 but remote is debian linux.
or what.. i don't know. what is prbolem.. so many things to think.

thanks.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by dbwodlf3** [comment]
i tried print ${workspaceFolder} from task.json. it print properly. "/home/swlab/smc" ....

**Comment by roblourens** [comment]
These variables aren't resolved automatically for all config, please file a feature request or bug on the Python extension repo.
