### ISSUE TITLE
no "reconnect" option is available in command menu

### ISSUE THREAD

**Issue by dibalavs** [microsoft/vscode-remote-release#4006]
Steps to Reproduce:

1. connect to employer's vpn.
2. in vscode open ssh connection to remote comuter
3. do work
4. disconnect from vpn
5. close annoying window 
![image](https://user-images.githubusercontent.com/801951/98908157-0d9ba100-24d1-11eb-8b74-cfa9df7a31d6.png)

6. go sleep
7. connect vpn again.
8) try to re-connect (or better to say reload) existing session 
![image](https://user-images.githubusercontent.com/801951/98908330-505d7900-24d1-11eb-8836-6bab19d71184.png)

Actually there is no option to reload workspace I already work with.  you need to find workspace file you previously work and open it again.

vscode information:
Version: 1.51.0 (system setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:18:23.642Z (6 days ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
Remote SSH: 0.56

**Comment by roblourens** [comment]
There is a command, Reload Window, this is what you want.
