### ISSUE TITLE
Use current machine settings in resolver

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#4007]
We should read and apply the current machine settings while the resolver is still running.

From @aaronadamsCA in https://github.com/microsoft/vscode-remote-release/issues/2267#issuecomment-725436126_

**Comment by RMacfarlane** [comment]
@chrmarti How can we verify this?

**Comment by chrmarti** [comment]
Add the following to your devcontainer.json:
```json
	"settings": { 
		"remote.containers.copyGitConfig": false,
		"remote.containers.gitCredentialHelperConfigLocation": "none",
		"dotfiles.repository": "chrmarti/dotfiles-test",
		"dotfiles.targetPath": "~/dotfiles2",
		"dotfiles.installCommand": "~/dotfiles2/install2.sh"
	},
```
Rebuild the container and verify that there is no `~/.gitconfig` and there is a `~/dotfiles2` folder and a `~/dotfiles-test-2.txt` file.
