### ISSUE TITLE
PF UI returns localhost for browser side when copying uri

### ISSUE THREAD

**Issue by wachaudh** [microsoft/vscode-remote-release#4012]
Original discussion is here: https://github.com/microsoft/vscode-internalbacklog/issues/1406

Tried to fix this on the web side per @alexr00 suggestion [here](https://github.com/github/codespaces/issues/1384). However, the suggested fix introduced the [504 issue](https://github.com/microsoft/vssaas-planning/issues/1260#issuecomment-725303645) and the [permissions issue](https://github.com/github/codespaces/issues/1713#event-3985076387). It would be much simpler to fix the copy issue on the vscode side by just retrieving the address with resolveExternalUri in [CopyAddressAction](https://github.com/microsoft/vscode/blob/82c65e753f3dda8e95fc3cd624b68326380ee24c/src/vs/workbench/contrib/remote/browser/tunnelView.ts#L906).

**Comment by alexr00** [comment]
@wachaudh can you go into a bit more detail on why Codespaces can't provide the correct URI when opening the tunnel?

**Comment by alexr00** [comment]
I talked to @wachaudh and I'll make a small change in VS Code to resolve the uri after receiving it. We'll see if this causes the 504 errors again and re-address if needed.

**Comment by alexr00** [comment]
Heard from @wachaudh that all is well here now.
