### ISSUE TITLE
Ports View Polish

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#4021]
🗨 = Under discussion

This is an initial collection of ideas to be discussed further:

- [x] decouple the Ports view from the Remote explorer and show it in the panel when in a remote context. 
- ~~render the target link as clickable link~~ This is inconsistent with any other trees we have. I would prefer to keep the actions as they are.
- [x] 🗨 with dynamic open/closed ports detection render the state whether a service is running at a port. 
- [x] render whether a port is ~~statically~~extension forwarded (e.g. from the devcontainer.json), this will be shown in the port detail, not with an icon, to avoid conflicting with the many other states that need to be shown.
- [x] since the view is shown horizontally change the placement of the inline action in the same way as when the Search results view is shown horizontally (cannot repro currently)
- [x] revisit the use of the term 'forwarded' in the context of the web
- [x] in the Ports available notification add a description to open the Ports view with a command link that opens the Ports view, e.g. `'Open the <link>Ports</link> view to see the available ports'`

**Comment by alexr00** [comment]
When a process is running and available at a currently forwarded port, we now show the process details in the ports description. I think this is a good way to indicate this:

> with dynamic open/closed ports detection render the state whether a service is running at a port in the item's icon. Should also render whether a port is statically forwarded (e.g. from the devcontainer.json).

Example when nothing is running:
![image](https://user-images.githubusercontent.com/38270282/100078706-1468d300-2e44-11eb-990b-ab85f01174f3.png)

Example after hitting F5:
![image](https://user-images.githubusercontent.com/38270282/100080508-35322800-2e46-11eb-8eeb-824cce9a5ffc.png)

**Comment by alexr00** [comment]
Outcome of the UX discussion was that we will keep the word "Forwarded" and align the status bar to match that. The reasoning given was that people understand what forwarded means and we haven't had any feedback from real users that "Forwarded" is confusing in the web.

**Comment by tvvignesh** [comment]
@alexr00 I don't see the refresh button anymore in portforwards window. Also, looks like you have rolled back port forwarding view - it was near terminal yesterday, now its back with remote explorer 😅

Is this still in development? Any place where I should follow this? Thanks.

**Comment by alexr00** [comment]
@tvvignesh thanks for using insiders! We were trying out the Ports view in the Panel in insiders, but we aren't 100% sure we want to put it there yet. Because we are getting close to releasing, it's back in the Remote Explorer for now (you can always drag and drop the view somewhere else if you want to).

The refresh button is gone because forwarding changes are automatically shown without refresh, and we update every 2 seconds for ports that we "discover" and forward for you.

It's in development in the sense that we are still trying to improve the experience around ports (add new feature, make sure users can find it, etc).

**Comment by alexr00** [comment]
As for where to follow what's going on with the Ports view, doing a search for "ports" in our issues is a good start. I'll try to make sure there's always an associated issue for changes I make.

**Comment by tvvignesh** [comment]
@alexr00 Sure. Thanks for your quick reply. No pressure, just wanted to have some clarity.

Btw,, I use VSCode remote ssh as the core part of my dev workflow everyday and I should say what you guys have done is really awesome to see.

I will blog about this sometime. Thanks
