### ISSUE TITLE
remote.SSH.defaultForwardedPorts only showing name sporadically

### ISSUE THREAD

**Issue by NicolasGoeddel** [microsoft/vscode-remote-release#4028]
- VSCode Version: 1.51.1
- Local OS Version: Ubuntu 20.04 LTS
- Remote OS Version: Ubuntu 18.04.5 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Create a workspace file with at least one forwarded port.
2. Open that workspace file.

Here is the workspace file:
```json
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"remote.SSH.defaultForwardedPorts": [
			{
				"localPort": 8080,
				"remotePort": 8080,
				"name": "client1"
			}
		],
		"remote.restoreForwardedPorts": true,
	}
}
```
This is how it looks:
![image](https://user-images.githubusercontent.com/1520064/99430270-69b75880-2909-11eb-8e88-9b3411d8d937.png)

Usually I would expect to see the name *client1* before "8080 -> 127.0.0.1:8080". This sometimes works but only in 1 of 10 cases.

**Comment by roblourens** [comment]
@alexr00 this just uses `vscode.workspace.openTunnel`

**Comment by alexr00** [comment]
I think this could happen if someone (the user for example) forwards the port before Remote SSH calls `openTunnel`. It could also happen if the user removes the forward then re-forwards it.

**Comment by roblourens** [comment]
@NicolasGoeddel this should be fixed in the VS Code Insiders build, could you try it out to confirm? Thanks!

**Comment by NicolasGoeddel** [comment]
I have vscode installed as snap on ubuntu 20.04. Is it possible to install the insider version the same way? I have bad experiences in switching from snap to a normal deb package.

**Comment by alexr00** [comment]
@NicolasGoeddel you can install `code` and `code-insiders` side by side. No need to uninstall first.

**Comment by NicolasGoeddel** [comment]
It seems to work fine after a few tries with different remote workspaces.

**Comment by alexr00** [comment]
Thanks @NicolasGoeddel !
