### ISSUE TITLE
[Feature] Let us define localHost and localIp for remote.SSH.defaultForwardedPorts

### ISSUE THREAD

**Issue by NicolasGoeddel** [microsoft/vscode-remote-release#4029]
It is already possible to define some ports which should be forwarded from the remote machine to my local machine like so:
```json
		"settings": {
		"remote.SSH.defaultForwardedPorts": [
			{
				"localPort": 8080,
				"remotePort": 8080,
				"name": "client1"
			}
		],
		"remote.restoreForwardedPorts": true,
	}
```
Now if I click on the little world icon in the Remote Explorer the address `http://127.0.0.1:8080` will open.
![image](https://user-images.githubusercontent.com/1520064/99431151-94ee7780-290a-11eb-8736-a6704e32f55f.png)
In my case this is not working because my application won't work properly if there is no hostname. Because of that I would like to see the entry `localHost` and `localIp` to define to what address the world icon will lead me and to which local IP address the port will be bound.
The simplest case would be to send me to the URL `http://localhost:8080` instead of `http://127.0.0.1:8080`.

**Comment by roblourens** [comment]
Should the remote host be customizable as well? I suppose so...

**Comment by roblourens** [comment]
Oh, the local host is not customizable by the method we use, @alexr00 is that because of cases like codespaces where someone else has to determine the local host? Could we set a local host that might be ignored, or is there another reason that it's not customizable?

**Comment by alexr00** [comment]
@roblourens we just try to copy the remote host (it can only be 127.0.0.1 or localhost). It looks like you're using 127.0.0.1 by default. Could you just use localhost?

**Comment by roblourens** [comment]
Oh I see. I just used 127.0.0.1 because I've had issues with localhost not being what you expect in certain situations. Do other remote flavors use localhost?

**Comment by NicolasGoeddel** [comment]
I am developing [Plone](https://plone.org/) addons and somehow it does not like raw ip addresses as host. It then just does not load any CSS and JS files. If I use localhost it works correctly.

**Comment by alexr00** [comment]
Remote Containers is using localhost because of microsoft/vscode-remote-release#2711, so it looks like the safer option. If it turns out that we do need to be able to set it we can add api later.

**Comment by roblourens** [comment]
I'll just match that and use localhost.
