### ISSUE TITLE
wsl2 doesn't run .bashrc breaking custom environment

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode-remote-release#4031]
Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
- Remote Extension/Connection Type: WSL v0.51.3

Steps to Reproduce:

1. install wsl2
2. add `export PATH=$PATH:/opt/rh/rh-git218/bin` to `.bashrc`
3. connect to wsl2 in vscode

![image](https://user-images.githubusercontent.com/1088194/99440175-060e3a80-28cb-11eb-985d-3dfbf7a0aaeb.png)

vscode can't find git because wsl2 doesn't run shell. re: https://github.com/microsoft/WSL/issues/6250

please add workaround to run wsl2 commands with shell so environment is correctly configured.

**Comment by PavelSosin-320** [comment]
This is not so simple issue: In the "old" bash-style" WSL attached terminal didn't do login. Now every WSL user has to be created as Linux user to make $HOME/bashrc and Global /etc/bash.bashrc "sourced" during the normal login process and it does it. WSL also differentiates between wsl 'command' and wsl -e 'command' and passes username via -u option.
The "normal login" is an interactive process and in systemd-based Linux distros involve accounts demon. In other words, the requirement is "Support Linux user login to WSL like any remote Linux server explicitly passing user name."
This logic is absolutely necessary to run many applications in WSL but is obviously not back-compatible: what about root and rootless users?
