### ISSUE TITLE
`code` command in WSL2 ignores --reuse-window

### ISSUE THREAD

**Issue by wongjn** [microsoft/vscode-remote-release#4032]
- VSCode Version: 1.52.0-insider/1.51.1
- Local OS Version: Windows 10.0.19041 Build 19041
- Remote OS Version: Ubuntu 18.04.5 LTS
- Remote Extension/Connection Type: WSL2

Steps to Reproduce:

1. Open a folder.
2. In integrated terminal (bash): `code existing.file --reuse-window`
3. See that it opens in a new window.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
Hey @wongjn, thanks for opening. I just tried this on both the latest Insiders and Stable VS Code with Ubuntu 18.04.5 LTS, and I'm unable to repro. Are you still experiencing this issue?

**Comment by wongjn** [comment]
Hi @bamurtaugh, thank you for responding to my issue and taking the time to take a look. I did some further debugging and this happened because I had the native Windows VSCode (`/mnt/e/Program Files/Microsoft VS Code/bin` in my `$PATH` before the injected `/home/username/.vscode-server/bin/…/bin` executable. Swapping this around in my `.bashrc` file fixed this issue. I apologize for reporting a misconfiguration as an issue!

**Comment by bamurtaugh** [comment]
No worries @wongjn - glad you were able to resolve it and thank you for the update!
