### ISSUE TITLE
Unable to install ms-vscode-remote.remote-containers: not found

### ISSUE THREAD

**Issue by nihiluis** [microsoft/vscode-remote-release#4035]
I cant find this extension https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers&ssr=false in the extensions UI.

Installing manually doesn't work either.

I don't use Insiders. I'm using the Arch Linux package.

```
code --install-extension ms-vscode-remote.remote-containers
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en-US)
Installing extensions...
Extension 'ms-vscode-remote.remote-containers' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
Failed Installing Extensions: ms-vscode-remote.remote-containers
```

- VSCode Version: 1.51.1
- Local OS Version: arch linux 5.9
- Remote OS Version:
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No Didnt try

**Comment by chrmarti** [comment]
Arch Linux is using a custom build, not sure if that has access to all extensions in the marketplace. You could try downloading the .vsix through the browser and point `code --install-extension ...` at it. For VS Code 1.51.1 you would need Remote-Containers 0.148.1 (0.149.0+ requires VS Code 1.52+). /cc @sandy081

**Comment by nihiluis** [comment]
Ah ok thanks.

It's a bit tricky, see here
https://bugs.archlinux.org/task/67780
