### ISSUE TITLE
Can't install/find these extensions and when installed with VSIX it doesn't work

### ISSUE THREAD

**Issue by johnnyasantoss** [microsoft/vscode-remote-release#4036]
- VSCode Version: 1.50.1 (I'm using Code OSS)
- Local OS Version: --
- Remote OS Version: --
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Try to find it on the extensions tab using Code OSS

Also, when installed from a VSIX file it doesn't work:

1. Install the extensions using the file
2. Try to connect current window to ssh
3. See that the command failed because it wasn't found.

**Comment by roblourens** [comment]
These extensions are not available for Code OSS, only the full builds
