### ISSUE TITLE
high Cpu Usage when using 

### ISSUE THREAD

**Issue by aschaepper** [microsoft/vscode-remote-release#4038]
I found several Issues with High CPU load, but none of them was clearly the same.

- VSCode Version: 1.51.1 (user Setup)
- Local OS Version: Windows 10 - 1809
- Remote OS Version: ubuntu Ubuntu 20.04.1 LTS
- Remote Extension/Connection Type: SSH / Remote - Containers version v0.148.1

Steps to Reproduce:

1. Point VS Code with remote SSH to a ubuntu 20 machine, and navigate remotely to a folder which contains processes (or recursive folders maybe), in my case: /proc
2. The extension "Remote - Containers" will cause high CPU load on the remote machine.

I could pintpoint the problem to this command, run by the Remote - Container extension:
rg --files --hidden --case-sensitive -g **/*.devcontainer/devcontainer.json/** -g **/*.devcontainer/devcontainer.json -g **/*.devcontainer.json/** -g **/*.devcontainer.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/node_modules -g !**/bower_components -g !**/*.code-search --no-ignore-parent --follow --quiet --no-config --no-ignore-global

Rg does recursive searching for files (I could see this command it in htop). From Htop i copied this command and ran it manually against the /proc folder, and the rg command was complaining that there are inded recursive folder structures, and stopped immediately (without the high load).
However, if the extension runs this command, it looks like it does it slightly different and forever. I can't narrow it down more in detail because its either a blackbox or I'm not skilled enough.

Why do I point vscode to a /proc directory? (I know this sounds silly).
--> Im building a snapcraft based operating system for cloud init stuff, and it looks like the image build mechanism creates the root filesystem and also runs processes in the /proc folder. So theoretically this is all still in a git repository (in the subfolder /proc alongside the other artifacts from the build), because the git repository contains the buildscripts for creating the OS image. But I think it will help in all other cases where there is folder recursion and rg "missbehaves" in the context of the Remote - Container extension.

If you need more infos, please let me know. I did create a cheap recursion (like 3-4 folders with symbolik links to each other so its really infinite theoretically) but this did not cause the extension to do the high load. I had to point to a /proc folder.

Thank you!

**Comment by roblourens** [comment]
You are right about this issue, I am tracking this in https://github.com/microsoft/vscode/issues/110510
