### ISSUE TITLE
open failed: administratively prohibited: open error

### ISSUE THREAD

**Issue by nicolascapin1991** [microsoft/vscode-remote-release#4039]
Hello there,
I'm trying to connect via ssh to a Linux server.
I state that I can connect correctly through the powershell and I can create, modify and delete files and directories.

When I try to connect via VS and Remote-SSH I get this error in the log and then it times out:

`channel 3: open failed: administratively prohibited: open failed`
`channel 3: open failed: administratively prohibited: open failed`
`channel 4: open failed: administratively prohibited: open failed`

I also tried what is recommended in the official guide under the "Enable TCP Forwarding on the remote host" tip, but it doesn't work:
https://code.visualstudio.com/docs/remote/troubleshooting#_troubleshooting-hanging-or-failing-connections

Thanks in advance,
Nicola

**Comment by roblourens** [comment]
It sounds like you found the right section of the docs, but there is nothing else we can do, if tcp port forwarding is not working on the server then this will not work.
