### ISSUE TITLE
Crash when coding with ssh

### ISSUE THREAD

**Issue by ViniDalvino** [microsoft/vscode-remote-release#4043]
Issue Type: <b>Bug</b>

1- Launch ur vps through the microsoft ssh extemsion
2- Code a bit in JS and download module on npm on the vps
3- THe language server should crash

Extension version: 0.56.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.9.0-13-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (0.96GB free)|
|Process Argv|--crash-reporter-id 9f5774af-0474-4f51-98ef-3d4d441242da|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 165.22.225.255|
|OS|Linux x64 4.9.0-13-amd64|
|CPUs|Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz (1 x 1797)|
|Memory (System)|0.97GB (0.73GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Please tell me more about what you are doing. It would help if you can share the code that triggers the crash.

**Comment by ViniDalvino** [comment]
I was coding a node js console app with module required. I don't remember what I was doing beisde that. I wish I could describe more. I am sorry
