### ISSUE TITLE
ssh with password does not work

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-remote-release#4044]
Issue Type: <b>Bug</b>

* Enable ssh on a VM in Parallel Desktop
* Verify that you can ssh into it through command line `ssh parallels@ip`
* Test with remote ssh, it keeps asking for password but never succeeds
* Add your ssh public key to the vm
* Verify that you ssh into it without typing password
* Test with remote ssh, it still asks for password
* Edit ssh config, add 
```
Host vm
  HostName 
  User parallels
```
* Now open this through remote ssh works fine

Extension version: 2020.11.24164
VS Code version: Code - Insiders 1.52.0-insider (78908e7eb4ff12fc2ed0dd1f17200fea48c56ab2, 2020-11-18T12:39:33.450Z)
OS version: Darwin x64 20.1.0
Remote OS version: Linux x64 4.15.0-123-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.37GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vm|
|OS|Linux x64 4.15.0-123-generic|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|7.78GB (0.51GB free)|
|VM|100%|
</details>

**Comment by roblourens** [comment]
This isn't handled, but the pw prompt only showed `parallels@` instead of the full username with space, making this confusing

**Comment by lkulwick** [comment]
disabling flock option in settings helped me with this issue
remote os: fedora30

**Comment by eleanorjboyd** [comment]
Hello! It seems like you were able to solve this issue, I am going to go ahead and close it but if this is not the case please re-open it accordingly.
