### ISSUE TITLE
win10 remote:ssh 1. conpty err 2. VS Code Server failed to start.

### ISSUE THREAD

**Issue by diepes** [microsoft/vscode-remote-release#4045]
- VSCode Version:
- Local OS Version:
  Win10 Version 1909 (OS Build 18363.418)
- Remote OS Version:
  Linux debian 10.6   Kernel 4.19 
- Remote Extension/Connection Type: SSH/Docker/WSL
SSH

Steps to Reproduce:

1. Uninstall and re-install vscode
2. Remote Explorer > SSH Targets > Connect in current window
3. Get error popup "The terminal process failed to launch: A native exception occured during launch (Cannot launch conpty)
4. File preferences settings > Search "conpty" disable "Windows Enable Conpty"
5. Remote Explorer > SSH Targets > Connect in current window
[Terminal]

6. popup [ Could not establish connection to "vbox-debian": The VS Code Server failed to start. ]

Does this issue occur when you try this locally?: Yes/No
No

7. Looking on Linux guest.
```
debian:~$ cat .vscode-server/.e5a624b788d92b8d34d1392e4c4d9789406efe8f.log
/home/user/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/server.sh: 12: /home/user/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/server.sh: /home/user/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node: not found
```

Looking in the Linux ~/.vscode-server/  dir, there is no node executable ?? only directories.
```
debian:~/.vscode-server$ find . -name node
./bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/platform/files/node
./bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/base/node
```

How do i find the installation script ran on remote to get better debug info ?

**Comment by diepes** [comment]
I was about to give-up.

Tried one more time ,  removed installation and tried to connect.
$ rm -rf ~/.vscode-server

Saw wget failure in log, (No url to debug)

but vscode installed and connected.

The contents of the ~/.vscode-server/ dir changed
it contains /bin /data /extensions  and still the two hidden files .e5....log and .pid

Seems very flakey.

**Comment by roblourens** [comment]
> Saw wget failure in log, (No url to debug)

Can you share any details? Sounds like it is working now though? Please share the log form the Remote-SSH output channel if this happens again.
