### ISSUE TITLE
Forwarded ports view in the remote explorer don't show

### ISSUE THREAD

**Issue by magicmayu** [microsoft/vscode-remote-release#4047]
- VSCode Version:
- Local OS Version:
version 2004  OS Build 19546.1000
- Remote OS Version: 
Ubuntu 18.04
- Remote Extension/Connection Type: SSH/Docker/WSL
WSL

Two weeks ago, the forwaded ports view showed when I use remote wsl. I use it for forwarding the wsl port to the host. But today when I open the remote project, and run it, I can't find the forwarded ports view in the remote explorer, so I cannot forward the port to the host.

**Comment by bamurtaugh** [comment]
Hey @magicmayu, are you still experiencing this? If so, can you include a screenshot of your Remote Explorer when you run your app and where your ports view is now missing?
