### ISSUE TITLE
Blank screen on opening remote folder with High Contrast theme

### ISSUE THREAD

**Issue by micoloth** [microsoft/vscode-remote-release#4049]
- VSCode Version: 1.51.1
- Local OS Version: Windows 10 Pro Version	10.0.18363
- Remote OS Version: Ubuntu 18.04.2 LTS (Bionic Beaver)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. open a folder on a remote connection
2. close connection
3. open the same folder again

When I do this, not always but very often (almost always lately) all vscode shows is a black screen (black is the background color in my theme). No top bar, side bar or any other element, just the blank screen.

Note: the connection does work, as i'm able to `remote-ssh > connect to host` and it connects. I can even open other folders, even subfolders and parent folders in the directory tree (via the "open folder" button on the sidebar, or any other way), but when I reopen the same previous folder , after the window reloades then it's blank.

At this point, the only thing that eliminates this problem is deleting and re-cloning the folder on the remote server. 

I tried: deleting the `home/.vscode-server` directory from the host, deleting the `.vscode` directory from my folder, and even doing `remote-ssh > uninstall vs code server from host`. I have tried all these 3 operations at the same time. When I connect again it's fine, but then when I open the same folder, it's blank.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this and all extensions are disabled?: Yes. I have tried to connect with all extensions disabled except for the Remote Development pack, and I have done this immediately after deleting the server from the host. The behavior is exactly as described.

Do you have any idea what might cause this?
Thanks

**Comment by roblourens** [comment]
What's special about this folder? Is it large? 

> At this point, the only thing that eliminates this problem is deleting and re-cloning the folder on the remote server.

This is confusing, so what's the difference between the folder before and after you do this?

**Comment by micoloth** [comment]
Thanks for answering!

> What's special about this folder?

Sorry I wasn't clear. This happens for any folder in my remote server. The first time I open it it's ok, but the second time it won't work.
This doesn't prevent me from opening different folders in the remote server though (if it's for the first time).

> what's the difference between the folder before and after you do this?

That's what I'd like to now!
Does Vscode save some kind of state in some temporary file/folder other than the ones I listed, that might get corrupted?

I'm really not sure where to look here!

**Comment by roblourens** [comment]
I can't think of any state that is saved or anything that would cause this. Do you have another remote that you can try connecting to, to check whether you get the same behavior?

**Comment by micoloth** [comment]
I have made more experiments.. Apparently, it's a problem of the High Contrast theme (?!?)

**Comment by roblourens** [comment]
Strange, it might be helpful if you can share any screenshots or a screen recording of what you are seeing

**Comment by roblourens** [comment]
Strange, maybe something upstream in electron/chromium. Thanks for the details. fyi @deepak1556
