### ISSUE TITLE
Unstable when using Remote:SSH

### ISSUE THREAD

**Issue by juliussimonelli** [microsoft/vscode-remote-release#405]
Issue Type: <b>Bug</b>

I create a port forwarding ssh to a docker instance inside EC2 with something like this `ssh -L 2201:localhost:2222 user@host -N -i ~/.ssh/id_rsa -v`. Then I connect to it using Remote:SSH. This works, but it is very unstable and often breaks when I try to reload it. For example, if I try to add a folder to my workspace it will restart, and when it does it gives me an error saying: Could not establish connection to "localhost". My config file lists my user as root, my port as 2201, and my IdentityFile, so it definitely works sometimes but doesn't other times. Sometimes I can solve this by clicking "Retry" over and over again, but it could take 5 or 10 tries. Other times it never comes back.

VS Code version: Code - Insiders 1.35.0-insider (4ca38ce5584d7cd67b435b3c32ef1240c6a29628, 2019-05-21T05:17:12.031Z)
OS version: Darwin x64 18.5.0
Fetching remote diagnostics for 'SSH' failed.
Fetching remote diagnostics for 'SSH' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed.

Fetching remote diagnostics for 'SSH' failed.
</details>Extensions: none

**Comment by roblourens** [comment]
I don't quite understand your setup, why are you forwarding port 2201 then trying to connect to it with SSH?

Can you share the output channel "Remote - SSH" for one of the failed connection attempts?

**Comment by juliussimonelli** [comment]
`user@host` is an AWS instance running a docker container and I publish port 2222 when I create it the docker container, but I have to map port 2201 on the host to port 2222 in the container.

Here's the output for when it's working (you'll see that I'm using OpenSSH, which I hope isn't causing a problem):
(base) user on ip-10-4-15-227 @ 06:33 PM: ~
$ ssh -L 2201:localhost:2222 username@hostgpu103.domain.info -N -i ~/.ssh/id_rsa -v
OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/user/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug1: /etc/ssh/ssh_config line 52: Applying options for *
debug1: Connecting to hostgpu103.domain.info port 22.
debug1: Connection established.
debug1: identity file /Users/user/.ssh/id_rsa type 0
debug1: identity file /Users/user/.ssh/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.9
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
debug1: match: OpenSSH_7.4 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
debug1: Authenticating to hostgpu103.domain.info:22 as 'username'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:itGD+hxpmhW7f7JzCAsYPAcnmcNXnc3o3j8eNFiFycE
debug1: Host 'hostgpu103.domain.info' is known and matches the ECDSA host key.
debug1: Found key in /Users/user/.ssh/known_hosts:3
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: Will attempt key: /Users/user/.ssh/id_rsa RSA SHA256:7mq+vZt4GAp8wwXVLOuaV3V0OrSiuYHEhlbWxyHS/5Q explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Next authentication method: publickey
debug1: Offering public key: /Users/user/.ssh/id_rsa RSA SHA256:7mq+vZt4GAp8wwXVLOuaV3V0OrSiuYHEhlbWxyHS/5Q explicit
debug1: Server accepts key: /Users/user/.ssh/id_rsa RSA SHA256:7mq+vZt4GAp8wwXVLOuaV3V0OrSiuYHEhlbWxyHS/5Q explicit
debug1: Authentication succeeded (publickey).
Authenticated to hostgpu103.domain.info ([172.31.16.54]:22).
debug1: Local connections to LOCALHOST:2201 forwarded to remote address localhost:2222
debug1: Local forwarding listening on ::1 port 2201.
debug1: channel 0: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 2201.
debug1: channel 1: new [port listener]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Connection to port 2201 forwarding to localhost port 2222 requested.
debug1: channel 2: new [direct-tcpip]
debug1: channel 2: free: direct-tcpip: listening port 2201 for localhost port 2222, connect from ::1 port 56523 to ::1 port 2201, nchannels 3
debug1: Connection to port 2201 forwarding to localhost port 2222 requested.
debug1: channel 2: new [direct-tcpip]
debug1: channel 2: free: direct-tcpip: listening port 2201 for localhost port 2222, connect from ::1 port 56525 to ::1 port 2201, nchannels 3
debug1: Connection to port 2201 forwarding to localhost port 2222 requested.
debug1: channel 2: new [direct-tcpip]
debug1: channel 2: free: direct-tcpip: listening port 2201 for localhost port 2222, connect from ::1 port 56529 to ::1 port 2201, nchannels 3
debug1: Connection to port 2201 forwarding to localhost port 2222 requested.
debug1: channel 2: new [direct-tcpip]

Then I installed the Python plugin and clicked reload and it broke. Here's the output:
, connect from ::1 port 57259 to ::1 port 2201, nchannels 3
debug1: Connection to port 2201 forwarding to localhost port 2222 requested.
debug1: channel 2: new [direct-tcpip]
debug1: channel 2: free: direct-tcpip: listening port 2201 for localhost port 2222, connect from ::1 port 57287 to ::1 port 2201, nchannels 3
debug1: Connection to port 2201 forwarding to localhost port 2222 requested.
debug1: channel 2: new [direct-tcpip]
debug1: channel 2: free: direct-tcpip: listening port 2201 for localhost port 2222, connect from ::1 port 57290 to ::1 port 2201, nchannels 3

Every time I click "Retry" it just spits that out again. I don't see any difference between when it's working and when it isn't.

**Comment by roblourens** [comment]
I see what you're doing now, if you remove the Python extension does it work again?

Can you share the log from the "Remote - SSH" output channel?

**Comment by juliussimonelli** [comment]
Sorry, I misunderstood which output you wanted. The Python extension doesn't appear to be related. I can load VSCode - Insiders, connect to SSH, then under recents I can click on one of my SSH folders (e.g. projects [SSH: localhost]) and it will stop working and give me the error message "Could not establish connection to "localhost"". Here's the output from Remote - SSH:

> bash: no job control in this shell
"install" terminal command done
Received install output: bash: no job control in this shell
Failed to parse remote port from server output: bash: no job control in this shell

**Comment by juliussimonelli** [comment]
And here's the output when it is working:

"install" terminal command done
Received install output: ce9dd424-c1ae-4c64-b053-d853ca4d807b==40327==
Server is listening on port 40327
Using SSH config file "/Users/user/config"
Spawning tunnel with: ssh -F /Users/user/config localhost -L localhost:11955:localhost:40327 "echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity"
Spawned SSH tunnel between local port 11955 and remote port 40327
Waiting for ssh tunnel to be ready
Tunneling remote port 40327 to local port 11955
Resolving "ssh-remote+localhost" to "localhost:11955", attempt: 1
> Connected to SSH Host - Please do not close this terminal

**Comment by roblourens** [comment]
Is that the full output from the case where it does not work? It seems that it did not run the install script at all.

Also you could try the nightly SSH extension build which should get rid of the "job control" warnings at least. https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly

**Comment by juliussimonelli** [comment]
That was the full output. I don't know why this happened but ever since I switched the the nightly builds I haven't been getting any errors at all. I don't know that we really resolved anything but I'm OK to close this.

**Comment by roblourens** [comment]
Hm, well I've fixed a bunch of things, one of them must have been your issue. Thanks for following up.
