### ISSUE TITLE
SSH config host aliases appear as separate targets in VSCode

### ISSUE THREAD

**Issue by knakamura13** [microsoft/vscode-remote-release#4050]
**The problem**
A host with multiple patterns/aliases appears as multiple SSH targets in the Remote Explorer window, even though two or more ssh targets may be identical when you connect to them.

Here is a screenshot of my situation, with two duplicate entries (`pi` and `raspi`) in the SSH Targets list
![image](https://user-images.githubusercontent.com/20162718/99747420-5635fa00-2a8f-11eb-876d-c13338d4a2d4.png)

**Expected behavior**
Each hostname should only appear once in the list of available ssh targets.
Suggestion: the patterns should be grouped together to clearly indicate that two or more patterns belong to the same exact hostname (i.e. clicking on either target would result in the same ssh connection).

Example
Given this example ssh config file:
```
Host pi raspi
  HostName 10.0.0.1
  User pi
```
Instead of listing `pi` and `raspi` as separate ssh targets, the list of available 'SSH Targets' in VSCode should group the two patterns (host aliases) together, like so:
`pi/raspi`
or, alternatively:
`pi, raspi`

**System information**
- VSCode Version: 1.51.1 and 1.52.0-insider
- Local OS Version: MacOS 10.15.7 (Catalina)
- Remote OS Version: N/A
- Remote Extension/Connection Type: SSH

**Steps to reproduce**
1. Edit the ssh config file
2. Add two or more patterns to the `Host` declaration, i.e.: 
```
Host pi raspi
  HostName 1.2.3.4
```

**Comment by roblourens** [comment]
They are separate names, they can have separate rules applied, and so you have to pick which one you want to connect to.
