### ISSUE TITLE
updating vscode blocks SSH to existing workspace

### ISSUE THREAD

**Issue by josebrwn** [microsoft/vscode-remote-release#4055]
Update to vscode 1.51.1 breaks SSH to existing remote workspaces, requires manually deleting ~/.vscode-server on remote server.

_Originally posted by @ilaydabozan in https://github.com/microsoft/vscode-remote-release/issues/2513#issuecomment-613505778_

**Comment by roblourens** [comment]
Please give more details, and the log from the Remote-SSH output channel ideally
