### ISSUE TITLE
Split config and internal server data locations

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/vscode-remote-release#4056]
Currently everything is stored inside `~/.vscode-server-insiders/` (or the equivalent path in case of the regular stable release). Most of it is actually ephemeral; if I deleted it and connected to the remote again, it would be reinstalled; addons may need manual reinstalling or sync from local, but that's it.

However, there's one part which is much more valuable: `~/.vscode-server-insiders/data/Machine/settings.json` containing user-specific settings for that remote!

It would be nice if this file was in a location like `~/.config/vscode-insiders/settings.json` instead of mixed together with all the downloaded stuff from the server. As an extra step, there could be an `extensions.json` in that location as well to keep track of the installed extensions. That way there would be one directory to back up when moving to a new remote and wanting to keep the same setting. In fact, there's a good chance people already do back up `~/.config/`.

**Comment by roblourens** [comment]
You make a valid point, but I think it's easier for us to keep all data that we add together in one place to reduce our footprint in your home directory. I want to make sure that people can figure out what we left behind if they decide to clean up manually.

**Comment by ThiefMaster** [comment]
What about a more obvious directory structure inside the current folder then? e.g. `~/.vscode-server/etc/...` for configs and some other directory for all the other stuff

**Comment by roblourens** [comment]
I think everything that is basically user data is in `data/`. Also you may want to be using Settings Sync to port this data between machines, that is sort of what we optimize for.
