### ISSUE TITLE
User groups not picked up in terminal after restarting Terminal or VSCode

### ISSUE THREAD

**Issue by digitaltyrant** [microsoft/vscode-remote-release#4058]
- VSCode Version: 1.51.1
- Local OS Version: Windows 10.0.19041
- Remote OS Version: Ubuntu 18.04.5 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install Multipass
2. Install Ubuntu 18.04 LTS
3. Install VSCode 1.51.1
4. Install Remote - SSH extension
5. Create RSA key pair
6. Append public key on Ubuntu SSH authorized keys
7. Create SSH config entry for Ubuntu destination using private key
8. Run command `Remote-SSH: Connect to Host...`
9. Choose SSH Config entry for Ubuntu
10. From terminal outside of VSCode SSH into Ubuntu virtual machine
11. Add user to new groups e.g. docker
12. Open new shell for the user and run `groups` command to verify
13. From VSCode Remote-SSH window open terminal
14. Run `groups` command - New group not included
15. Restart terminal in VSCode
16. Run `groups` command - New group not included
17. Restart VSCode entirely
18. Run command `Remote-SSH: Connect to Host...`
19. Choose SSH Config entry for Ubuntu
20. Open terminal in VSCode
21. Run `groups` command - New group not included
22. Run `su - $USER` to open new shell
23. Run `groups` command - New group included

Does this issue occur when you try this locally?: 
Does this issue occur when you try this locally and all extensions are disabled?: 
![vs-extension-bug](https://user-images.githubusercontent.com/51473254/99870835-2b33dd80-2c2a-11eb-92b1-a758404b2b23.png)

**Comment by roblourens** [comment]
What is needed to pick up the change? Does it work if you run "Kill VS Code Server on Host", then try reconnecting? This will restart the server on your remote
