### ISSUE TITLE
in windows, can't save image by wsl:url

### ISSUE THREAD

**Issue by ab12323** [microsoft/vscode-remote-release#4061]
now, I only save image in windows, the image can't not be placed in wsl, because wsl's filer url is "\\wsl$\", it's error url to path
 
i hope can use a file path to save image in wsl. thank

**Comment by bamurtaugh** [comment]
Hi @ab12323, have you tried accessing your files via the `/mnt/<drive letter>/path/` interop mount? If you store your files on the Windows file system, you can access them through both Linux tools and Windows tools through this mount.
