### ISSUE TITLE
Allow to reload window several times after failure

### ISSUE THREAD

**Issue by oi-songer** [microsoft/vscode-remote-release#4062]
I'm using vscode remote dev plugin to work in a remote machine. And when I disconnected, vscode provide a choice of "reload window", which could save all my tabs and content. It's very useful. But if I failed to "reload window", then I can only input my password to reconnect(when I was connecting using Kerberos to identify, I couldn't connect with a empty password), then I can only press `esc`, then retry, which could help me reconnect, but lose all my window.
So I hope I could reload window several times after disconnect, thank you.

**Comment by roblourens** [comment]
It sounds like your issue is that your tabs and editors close when failing to reconnect, is that right? If so that is https://github.com/microsoft/vscode/issues/110062

I don't understand this part, please explain some more

> Another one is fix the "problem" that I can't connect my server using an empty password. I actually don't know how Kerberos works, maybe it's impossible or there are already some solution for that?

**Comment by oi-songer** [comment]
@roblourens Yes, the issue is the same as 110062.

As for this part, I'm using Kerberos to identify myself. When I tried to directly connect to my ssh server, I can easily get connected. It works fine. 

But if I failed to "reload window", then vscode may think I can't connect because I'm using a wrong password, then provide me a textbox to text password. But I have no password, and I can't connect with a empty password. 

Maybe vscode should provide a option to connect without password in this step?

**Comment by roblourens** [comment]
If it didn't ask for a password in the first connection then it shouldn't ask for a password when it reconnects either. I think that if kerberos fails it will fall back to asking for a password? So it seems like something is going wrong on that end.

**Comment by oi-songer** [comment]
@roblourens I tried this today, and it did not ask me the password, just give the option of "retry", which is issue 110062 . I can't really remember when it asked me to text password. If I have the same problem in the future, I will provide you with more information. For now, you can just close this comment. 

Thanks for your help.
