### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by shubhamsugara22** [microsoft/vscode-remote-release#4064]
- Issue Type: `Bug`
- Extension Name: `remote-wsl`
- Extension Version: `0.51.4`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by bamurtaugh** [comment]
Hey @shubhamsugara22, please provide some details about the issue you're experiencing with Remote-WSL. Thank you!
