### ISSUE TITLE
Local echo shows silenced echo in terminal shell (read -s)

### ISSUE THREAD

**Issue by flavioelawi** [microsoft/vscode-remote-release#4065]
- VSCode Version:
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```
- Local OS Version:
```
MacOs Catalina 10.15.7
```
- Remote OS Version:
```
Remote OS: Amazon Linux 2
```

- Remote Extension/Connection Type: SSH/Docker/WSL

SSH

### Steps to Reproduce:

1. Remotely connect via SSH Extension to a POSIX system that has the `read` program
2. Open the remote terminal in VScode, type `read -s`
3. Type something, you will see the output being echoed, showing in cleartext the secured string
4. Press enter, the input is hidden

### Expectation:
I should **not** see the input given to `read -s`

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by connor4312** [comment]
This should be fixed with https://github.com/microsoft/vscode/issues/110359
