### ISSUE TITLE
Resolver error: Error: Failed to find a free local port for dynamic forwarding

### ISSUE THREAD

**Issue by codeworld-GitHub** [microsoft/vscode-remote-release#4067]
- VSCode Version:
- Local OS Version:
- Remote OS Version:
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Can you share the log from the Remote-SSH output channel?

Can you think of any reason that the extension would not be able to find an open port on the local computer? Also please fill in the version/OS info

**Comment by ariesdevil** [comment]
Same issue for me:
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (3 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0
```

**Comment by roblourens** [comment]
Can you share the log from the Remote-SSH output channel?

Can you think of any reason that the extension would not be able to find an open port on the local computer? Also please fill in the version/OS info

**Comment by ariesdevil** [comment]
I can reproduce this issue by opening a new version of [Proxifier](https://www.proxifier.com/), everything is OK when I turn off Proxifier. [As Proxifier said](https://www.proxifier.com/download/bigsur/), the Big Sur introduce a new network extension API, so I think maybe something wrong with the new API.

**Comment by roblourens** [comment]
Seems like there are some known Proxifier/Big Sur issues as you point out. Is this the case for you @codeworld-GitHub? I don't think there is anything that I can do here but if they say issues are fixed later and you still see a problem with VS Code Remote, then please let me know.
