### ISSUE TITLE
Support for connecting to Apple Silicon/M1/ARM64 remote

### ISSUE THREAD

**Issue by smokris** [microsoft/vscode-remote-release#4069]
When I use Visual Studio Code 1.51.1 running on macOS 11.0.1 x86_64 and attempt to connect using remote-ssh 0.56.0 to a macOS 11.0.1 arm64 system, the VS Code Server fails to start on the remote system:

    [13:47:19.278] > /Users/…/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/server.sh: line 12: /Users/…/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node: Bad CPU type in executable

That binary is x86_64 only, whereas (in order for it to work natively / without needing the Rosetta translation layer) it should be arm64 or "Universal" (x86_64 + arm64).
```console
$ file .vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node
.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node: Mach-O 64-bit executable x86_64
```

**Comment by roblourens** [comment]
@joaomoreno are we building the server for this yet? I don't see the mac arm build on our builds page

**Comment by joaomoreno** [comment]
@deepak1556 Is the right person to ping.

**Comment by gorilla-1** [comment]
I have the same issue with my WSL at VS Code 
`e5a624b788d92b8d34d1392e4c4d9789406efe8f: -c: line 0: unexpected EOF while looking for matching `

**Comment by deepak1556** [comment]
Yeah I had left this out for the exploration release, definitely something to add. Thanks for opening the issue!

**Comment by deepak1556** [comment]
Since we download prebuilt node binaries for the remote, and there is no arm64 version available yet. This feature cannot move forward until then.

**Comment by richiksc** [comment]
Is this feature required to move forward with microsoft/vscode#106770, and does it prevent the exploration build from being promoted to Insiders? Just curious.

**Comment by deepak1556** [comment]
Not it doesn't. Once we have vscode stable 1.52, the next insiders following it will contain mac arm builds too.

**Comment by johnwiseheart** [comment]
Definitely excited about this, since I believe its the final thing left to get my corporate set-up working on a new M1 mac. 

For context, we spin up docker containers on our local machines and attach to them - so on M1 mac's, the docker containers are running ARM Alpine, and seeing the error `Alpine Linux is not supported on the hardware architecture 'aarch64' of the container.`

**Comment by rickardp** [comment]
What is the status on the ARM64/Alpine support?

The current workaround for me is to pin every Docker image reference to the SHA256 of the X64 version. I believe there is no setting to force the x64 arch by default, at least I couldn't find one, so this starts to get a little messy.

**Comment by johnwiseheart** [comment]
@deepak1556 wondering if you have any update here? Would love to start using my M1 mac, but this is still blocking me from the workflows required by my company.

**Comment by ascorbic** [comment]
@johnwiseheart Have you tried it? I'm using an M1 as a remote and it works fine.

**Comment by xlc** [comment]
The only issue I have is that shell is launched by x86 process so I have to run a `$ arch -arm64e bash -l` to start arm64 shell

**Comment by johnwiseheart** [comment]
@ascorbic I still see the error `Alpine Linux is not supported on the hardware architecture 'aarch64' of the container.` - are you using Alpine?

**Comment by ascorbic** [comment]
@johnwiseheart Ah I missed that. I'm talking about the Mac M1

**Comment by johnwiseheart** [comment]
Me too! My setup involves running docker containers locally (on the M1) and using the remotes extension to code inside of the containers. So the container host is the M1 - but from what I can tell maybe it's just that Alpine isn't supported on ARM devices?

**Comment by johnwiseheart** [comment]
For what it's worth, changing to a non-alpine distro like Ubuntu fixes this, but unfortunately because the infrastructure is out side of my control that change isnt possible for me.

**Comment by ascorbic** [comment]
Ah, ok. My setup is a headless M1 (running Mac OS) as a compilation server. I've successfully connected to it from Intel and ARM Macs.

**Comment by adamreis** [comment]
I'm running into the same error as @johnwiseheart when trying to open a "remote" (running locally) Alpine ARM container from my M1 mac.

**Comment by NSExceptional** [comment]
So to be clear, we have official macOS ARM64 support working? And we're just waiting on Alpine?

**Comment by johnwiseheart** [comment]
@NSExceptional from what I understand, the remaining issue is still a vscode issue - since ARM64 works on intel macs, but still not on ARM. But I may be wrong - if I do misunderstand, would really appreciate a heads up so I can redirect my issues.

**Comment by a4z** [comment]
does not work, connecting form OSX x86_64 to BigSur on Apple Silicon, with remote ssh

```
 Server did not start successfully. Full server log at /Users/a4z/.vscode-server/.622cb03f7e070a9670c94bae1a45d78d7181fbd4.log >>>
[14:09:25.106] > /Users/a4z/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/server.sh: line 12: /Users/a4z/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node: Bad CPU type in executable
[14:09:25.106] > <<< End of server log
```
to bad .. back to vim ? oh nooo ...

**Comment by Kagami** [comment]
I can connect to arm64 M1 instance with VS Code just fine, but the funny thing is that `uname -m` inside VS Code's terminal will print `x86_64` because the node binary VS Code uses is x64.

I.e. VS Code runs x64 binary of node on remote M1, it works because of the Rosetta emulation, but when it spawns some other processes from inside that node binary everything is emulated too.

From SSH console:
```
% uname -m
arm64
```

From VS Code terminal:
```
% uname -m
x86_64
```

Testing it by hand:
```
% file ~/.vscode-server/bin/123/node
/Users/user/.vscode-server/bin/123/node: Mach-O 64-bit executable x86_64
% ~/.vscode-server/bin/123/node -e 'console.log(require("child_process").execSync("uname -m").toString())'
x86_64
```

I can use just a normal SSH terminal for executing commands instead of VS Code's internal terminal, just a funny observation.

**Comment by a4z** [comment]
I do not have rosetta installed (yet) since I want to know what works with arm, not via rosetta.
(That is the whole point of that remote Mac) 
I guess you have rosetta 2 installed, and VS Code is maybe using that
This would at least explain to me why you have a x86_64 terminal in VS Code.

**Comment by zhaoyao73** [comment]
so install rosetta will work? but losing the point, performance.

**Comment by iiiyu** [comment]
> @ascorbic I still see the error `Alpine Linux is not supported on the hardware architecture 'aarch64' of the container.` - are you using Alpine?

I used the Alpine image. And I also have this problem, look forward to a solution.

So is it possible to use other images like Ubuntu or Debian without this problem?

**Comment by qqq689** [comment]
https://m.facebook.com/profile.php?id=100044481320425

**Comment by cblavier** [comment]
Still doesn't seem to be working with vscode 1.54.1

```
[11:16:29.978] > Server did not start successfully. Full server log at /Users/cblavier/.vscode-server/.f30a9b73e8ffc278e71575118b6bf568f04587c8.log >>>
[11:16:29.981] > /Users/cblavier/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/server.sh: line 12: /Users/cblavier/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node: Bad CPU type in executable
```

**Comment by cblavier** [comment]
Until this is fixed, anyone has a workaround to make vs-code server use another nodejs installation?

**Comment by a4z** [comment]
my workaround is now adding code-server on the M1, ssh tunnel into it and run vs coder there in the browser
not optimal, but better than nothing. 
However, it is kind of unbelievable that this ticket can not be solved in all that months.  If that would be some hobby extension, but that is something Microsoft advertises ....

**Comment by xlc** [comment]
Just run a shell with arm64 and you are good to go.

```
$ arch -arm64e bash -l
$ arch
arm64
```

**Comment by a4z** [comment]
I do not think this is related to our topic, it's not about running VS Code on M1, this works, 
It iss about the remote extensions

> Just run a shell with arm64 and you are good to go.
> 
> ```
> $ arch -arm64e bash -l
> $ arch
> arm64
> ```
> 
> The only thing needs to be done is to make the remote component arm64 or fat binary so that all the process it spawns are arm64 instead of x86

This what is advertised here does not work
https://code.visualstudio.com/docs/remote/ssh

**Comment by xlc** [comment]
Yes. My current daily flow is on x86 mac using vscode remote into my M1 mac mini and build rust project under arm64 mode. And the vs code remote extension executed on my mac mini is x86 and caused the terminal become x86 as well. So I need to run a new shell within x86 terminal to execute arm64 binary.

**Comment by a4z** [comment]
To OP topic says:
> That binary is x86_64 only, whereas (in order for it to work natively / **without needing the Rosetta translation layer**) it should be arm64 or "Universal" (x86_64 + arm64).

and this is what I, and obviously also others, want/need. No rosetta on the remote machine (for reasons)

**Comment by cblavier** [comment]
I actually have no point in using a Silicon M1 machine with Rosetta.
I'm switching my current dev environment from x86 to M1 solely for performance. Everything is running fine, VSCode remote is last missing brick

**Comment by ohsayan** [comment]
Also waiting on this. FWIW:
1. I compiled Node for M1 (native, NOT Rosetta) and installed it on my remote machine (M1 Mac)
2. `cd`ed into the `.vscode-server` directory and found the bin folder that has a copy of the node binary
3. I removed that node binary and symlinked it to the native M1 binary that I built
4. But when I attempted to connect to it from my local machine (x86_64), I got "Connection error: Unauthorized client refused)"

I'm not sure what is causing this to be an "Unauthorized client". I'm using M$ shipped VSCode on local and M$ shipped Remote-SSH on remote, other than switching the node binary.

**Comment by cblavier** [comment]
Up! @deepak1556 any idea if (and when) this issue will be addressed?

**Comment by stingalleman** [comment]
This is crucial in my workflow and I'm also missing this. Really important feature!

**Comment by deepak1556** [comment]
Node version in remote is tied to the version shipped in the desktop client, next stable release of vscode `1.56` will bump the remote version of node to `v14`. Apple silicon support in node was backported to `v14` https://github.com/nodejs/node/pull/38051 but has not been released yet. We will work on getting the remote support once it is released.

**Comment by rickardp** [comment]
Current LTS is 16 so I hope support for this is being worked on

**Comment by aspenluxxxy** [comment]
Is there any manual workaround in the meantime? I'm getting noticeable slowdowns when using Remote SSH to code on my M1 Macbook Air, likely due to this.

**Comment by CharlesJones88** [comment]
> Node version in remote is tied to the version shipped in the desktop client, next stable release of vscode `1.56` will bump the remote version of node to `v14`. Apple silicon support in node was backported to `v14` [nodejs/node#38051](https://github.com/nodejs/node/pull/38051) but has not been released yet. We will work on getting the remote support once it is released.

version 1.56 of vs code is out now, any eta on when a fix can be done?

**Comment by aspenluxxxy** [comment]
Sad, `Connection error: Unauthorized client refused` still occurs whenever you compile an ARM64 Node v14 with the latest VSCode and try to swap out the binaries.

**Comment by ohsayan** [comment]
> Sad, `Connection error: Unauthorized client refused` still occurs whenever you compile an ARM64 Node v14 with the latest VSCode and try to swap out the binaries.

I precisely did that; refer to [this comment](https://github.com/microsoft/vscode-remote-release/issues/4069#issuecomment-824550652)

**Comment by deepak1556** [comment]
> version 1.56 of vs code is out now, any eta on when a fix can be done?

Depends on release of `14.17.0` https://github.com/nodejs/node/pull/38507. We then need to get the change in electron and make a separate release before we can start any work. So no eta at the moment.

> Connection error: Unauthorized client refused still occurs whenever you compile an ARM64 Node v14 with the latest VSCode and try to swap out the binaries.

You would also need to recompile the native modules that are bundled into the server for the arm architecture.

**Comment by aspenluxxxy** [comment]
Ok, so I swapped out the `node` binary with an ARM64 one, edited one of the JS files (`remoteExtensionHostAgent.js`) to patch out the "Unauthorized client refused" error, and recompiled node-pty.

Basic functionality works, but extensions and the terminal are broken.

**Comment by lezuber** [comment]
Any update here? nodejs/node#38507 seems to be released?

**Comment by deepak1556** [comment]
nodejs doesn't seem to release arm binaries for 14.x version https://github.com/nodejs/node/issues/37309#issuecomment-824829119. This has to wait until vscode desktop adopts node 16.x which will be with electron 14 update.

**Comment by youknowone** [comment]
I tried x64 to arm64 connect via remote-ssh and it was successful. Is this now resolved?

**Comment by CharlesJones88** [comment]
> I tried x64 to arm64 connect via remote-ssh and it was successful. Is this now resolved?

No it looks like vs code has to upgrade to electron 16 when that gets released, then they will start looking at a fix

**Comment by astrowonk** [comment]
I also tried from an intel mac to an m1 mac as the host via remote-ssh and it was successful. But the M1 Mac is running the server (Node) with Rosetta.

**Comment by fabge** [comment]
When Remote SSHing from an M1 Macbook Air to an M1 Mac Mini I experience the same issue.
The whole thing is running under Rosetta. Is there any way to fix this?

**Comment by mikehardy** [comment]
@fabge if I understand correctly it won't be fixed completely until VSCode updates to a newer version of node under the covers, which won't happen until it is forward-ported to a newer version of Electron, which requires a bunch of other work, so maybe not for a while.

However, this workaround does the trick for me after I remote ssh in - I have this set in my bash aliases file as `arm64` and I just run it after the ssh connects: `arch -arm64e bash -l` - now your shell is arm64-native

**Comment by Mellbourn** [comment]
@alexdima does closing this indicate that it is fixed? Remote-SSH to Apple Silicon still does not work for me.

**Comment by Absolucy** [comment]
@Mellbourn I assume it'll work in the next major update.

**Comment by JacksonKearl** [comment]
@alexdima On the latest insiders when I try to remote-ssh to my M1 machine I still see `uname -m` return `x86_64`.

**Comment by alexdima** [comment]
Here are the steps:
* From VS Code Insiders, switch to Remote - SSH Pre-Release
* (my version is Remote - SSH v0.77.2022032415)
* (if you are on an arm64 mac, enable System Preferences > Sharing > Remote Login)
* connect to localhost via SSH
* `uname -m` should print `arm64`

> Note: If you have used a specific VS Code Insiders version with Remote - SSH stable, then the x64 version of vscode-server has been downloaded and is cached at `$HOME/.vscode-server-insiders/bin/<commit>`. To get the Remote - SSH Pre-Release to download the arm64 version it is necessary to delete the cache and kill all running vscode server processes.
