### ISSUE TITLE
Remote SSH always uses git, even when disabled on the command line

### ISSUE THREAD

**Issue by stuarteberg** [microsoft/vscode-remote-release#4073]
I want to use the Remote SSH extension without git integration.  (But I don't want to disable git integration in my other VSCode windows.)  I tried launching it with `--disable-extension git`, like this:

```
/usr/local/bin/code --disable-extension git --file-uri vscode-remote://ssh-remote+<MACHINE>/path/to/my/file.txt
```

...but on the remote machine, VSCode still runs `git status -z -u`, which is what I'm trying to avoid.

**Background:**

I am using the CLI to open VSCode and edit a remote file.  The administrator of the remote system noticed that VSCode is launching `git status -z -u` every time I do this, and it takes a long time to run. That's because the file I'm editing happens to be in a git repo with a lot of untracked files, so the `-u` option (a.k.a. `--untracked-files`) is causing git to walk the entire directory tree, and puts an unnecessary load on the remote machine (which I share with others).  How can I prevent Remote SSH from running `git status -u`?

**Edit:** FWIW, I assume the command is coming from [this line.][1]

[1]: https://github.com/microsoft/vscode/blob/8e5a1da05eab6cad2cfb5208098154509c97e049/extensions/git/src/git.ts#L1802

--- 

- VSCode Version: `1.51.1`
- vscode-remote-extensionpack: `0.20.0`
- Local OS Version: `Darwin x64 19.6.0` (macOS 10.15.7)
- Remote OS Version: `Linux x64 3.10.0-957.21.3.el7.x86_64` (Linux CentOS 7)
- Remote Extension/Connection Type: SSH

<details>

<summary>Version details</summary>

```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

</details>

--- 

**Steps to Reproduce:**

1. Use the VSCode CLI to edit a remote file that happens to reside in git repository with MANY untracked files:

    ```
    /usr/local/bin/code --disable-extension git --file-uri vscode-remote://ssh-remote+<MACHINE>/path/to/my/file.txt
    ```

2. From another SSH session on the remote machine, inspect the output of `ps aux | grep git`.  Notice that `git status -z -u` is running, and consuming CPU/IO resources.

--- 

**Does this issue occur when you try this locally?:**
   - Yes

**Does this issue occur when you try this locally and all extensions are disabled?:**
   - N/A -- I can't use the remote extension if all extensions are disabled...

**Comment by roblourens** [comment]
@sandy081 should `--disable-extension` also disable the remote extension?

**Comment by sandy081** [comment]
Yes it should, but the extension id is not `git`, it is `vscode.git`

**Comment by stuarteberg** [comment]
Thank you for the response, @sandy081.

Two points:

1.   You suggested:

      >Please try using `vscode.git` and let us know if it works.

      OK, that worked, thanks!

      For future reference, how can I determine the extension id for built-in extensions?  I don't see the `vscode.git` extension in the extensions pane.  Also, `code --list-extensions` does not list `vscode.git`.

      I tried to infer the extension ID by inspecting the workspace settings file, which contains items like this:

      ```json
              "git.ignoreLimitWarning": true,
      ```

      ...but apparently that's not the full ID.

      Do all built-in extensions simply begin with `vscode.*`?  Is that documented somewhere?


2. (This is regarding @roblourens' question.)  I think he was referring to what I wrote above:

    >Does this issue occur when you try this locally and all extensions are disabled?:
    >
    >   - N/A -- I can't use the remote extension if all extensions are disabled...

   I wrote "N/A" because of the behavior of the `--disable-extensions` flag w.r.t. the remote extension.  I tried to launch VSCode with `--disable-extensions`, but that results in the following error.  It never disappears, even after clicking "Enable and Reload".  Should I open a new issue for this?

    <img width="556" alt="image" src="https://user-images.githubusercontent.com/1655821/101183057-f3129e80-361c-11eb-8592-222acdba99fd.png">

**Comment by roblourens** [comment]
You can see builtin extensions in the extension viewlet by clicking the filter button, then "Built-in"

Then you can click the Git extension to see its extension id here 
![image](https://user-images.githubusercontent.com/323878/101202511-37eb0500-361e-11eb-891f-0745f615d92f.png)

You can also disable it by right clicking it in the sidebar which is maybe what you really want. The `--disable-extensions` flag doesn't disable builtin extensions so it probably doesn't help here anyway, but I would also like a way to disable extensions besides remote resolvers.

**Comment by stuarteberg** [comment]
>You can see builtin extensions in the extension viewlet by clicking the filter button, then "Built-in"

Ah-ha!  Sorry I missed that. Thanks for the tip!

>I would also like a way to disable extensions besides remote resolvers.

OK, I've opened #4141 to track that feature request.

Closing now. Thanks again!
