### ISSUE TITLE
README for this repo links to v1_43 release notes instead of latest

### ISSUE THREAD

**Issue by phil-blain** [microsoft/vscode-remote-release#4074]
- VSCode Version: NA
- Local OS Version: NA
- Remote OS Version: NA
- Remote Extension/Connection Type: SSH/Docker/WSL: NA

Steps to Reproduce:

1. Click the " VS Code release notes" link in the [Releases](https://github.com/microsoft/vscode-remote-release/blob/master/README.md#releases) section of the [README](../blob/master/README.md)
2. End up on `https://code.visualstudio.com/updates/v1_43` instead of `https://code.visualstudio.com/updates/` 

Does this issue occur when you try this locally?: Yes/No NA
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No NA

**Comment by chrmarti** [comment]
Fixed, thanks.
