### ISSUE TITLE
Remote Container: Reopen In Container fails for remote host

### ISSUE THREAD

**Issue by codars** [microsoft/vscode-remote-release#4076]
I'm trying to connect to a remote container (running on a linux host) from my local machine (running on mac osx), but I cannot due to some unknwon reasons:

![image](https://user-images.githubusercontent.com/25216338/100276184-f66ba300-2f15-11eb-82f1-cfe98f8e4a4d.png)

Here's what I did:
1. Make sure my remote machine is ssh-able without password

    ![image](https://user-images.githubusercontent.com/25216338/100276387-4ba7b480-2f16-11eb-8a93-3f2503d2c312.png)

2. Make sure I can run "docker info" in the remote machine

    ![image](https://user-images.githubusercontent.com/25216338/100276732-dd172680-2f16-11eb-9fdc-0a2db5df0b7c.png)

3. In the Settings of vscode, I set the "docker.host" to be my remote machine

    ![image](https://user-images.githubusercontent.com/25216338/100276310-2d41b900-2f16-11eb-8b46-6aec0dc249e5.png)

4. Create .devcontainer/devcontainer.json in the current folder

    ![image](https://user-images.githubusercontent.com/25216338/100276551-95909a80-2f16-11eb-8b3e-bfce335d7b84.png)

5. Use extension, "Remote Container: Reopen In Container"

    ![image](https://user-images.githubusercontent.com/25216338/100276184-f66ba300-2f15-11eb-82f1-cfe98f8e4a4d.png)

Can you please help me figure out how to fix this issue? Thanks!

**Comment by codars** [comment]
Regarding "docker.host", I have tried "ssh://xiaguo@10.0.0.213", not working

**Comment by chrmarti** [comment]
Could you check if this is fixed when using VS Code Insiders and the latest Remote-Containers (0.151.0)?

**Comment by codars** [comment]
Hi @chrmarti, latest VS Code Insider solved my problem. Thanks for your help!

**Comment by chrmarti** [comment]
Thanks for confirming. Closing this issue.
