### ISSUE TITLE
Duplicating VSCode remote containers session causing massive memory leak

### ISSUE THREAD

**Issue by Drakota** [microsoft/vscode-remote-release#4079]
- VSCode Version: 1.52.0-insider
- Local OS Version: Windows 19042.630
- Remote OS Version: Debian 4.19.128-microsoft-standard
- Remote Extension/Connection Type: Docker/WSL

Steps to Reproduce:

1. Install WSL 2
2. Install Docker for Desktop 2.5.0.1 with WSL 2 based engine
3. Clone a C# project inside my default WSL distro (Ubuntu)
4. Open a C# project with VSCode's devcontainer feature ([with this particular devcontainer](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/dotnet-mssql))
5. Running a few commands (`dotnet restore`, `dotnet watch run`), not sure what triggers the issue
6. Check processes and see VSCode remote sessions eating all your RAM away increasingly without doing anything.
![Screenshot 2020-11-26 005529](https://user-images.githubusercontent.com/22665836/100313816-5f3d3480-2f83-11eb-819f-b540c634262e.png)
![Screenshot 2020-11-26 005547](https://user-images.githubusercontent.com/22665836/100313817-606e6180-2f83-11eb-80ff-6a61639eb264.png)
![image](https://user-images.githubusercontent.com/22665836/100314311-5bf67880-2f84-11eb-8ff6-60cde88171ed.png)

[LOGS](https://gist.github.com/Drakota/0e0d1c8565ade30d6a0be5ae560d7aac)

I can stop everything and not do anything and they will still keep spawning and max my RAM and SWAP.

I've reinstalled Windows twice, installed dev release, disabled all extensions, tried on multiple computers with different Windows versions and I get the same issue every time.

I'm really not sure if the extension is what's causing the issue, maybe a mix between WSL and Docker. 
I'll be more than happy to provide any logs that I haven't thought of to help the process to fix this issue.

**Comment by olzhas** [comment]
same thing on the local machine with
```zsh
➜  ~ docker --version
Docker version 19.03.14, build 5eb3275d40
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```
for remote machine with Ubuntu 18.04

**Comment by PavelSosin-320** [comment]
Not related to VSCode or Dev container. 
The same issue regardless of what is running inside WSL distro. I already opened the issue for Microsoft WSL.. **Wmmem** process is eating all computer memory. Possibly, the correction already exists,  But wsl update doesn't work too and I had stopped to use DockerDesktop for Win and switched to Podman because it has zero restart time

**Comment by PavelSosin-320** [comment]
Ubuntu 20.04 distro is the only distro which uses systemd and as I found systemd never rests - see attachement
![Ubuntu2004WSLTop](https://user-images.githubusercontent.com/54495912/101290595-033ca080-380c-11eb-9020-7985e057488d.png)
On another hand, I don't observe any memory leak inside WSL VM. It doesn't redeem it to Windows.
VSCode colleagues, could you communicate it inside Microsoft?

**Comment by PavelSosin-320** [comment]
The only way to release memory used by Vmmem is wsl --shutdown. Every new WSL session or command allocates additional ~100M memory and even wsl --terminate the distro doesn't release it. Is it so hard to detect 100M memory leak?
 The bright point: I use Podman 2 on Ubuntu 20.04 distro and can restore my working Podman stack with no hustles. 
1. reboot Linux
2 wsl --shutdown
3. The restart Ubuntu distro Using Ubuntu command (icon on my taskbar)
4. Start all my needed Pods
.....
Everything is ready including pods created using pod create, run --pod new:
The last step can be automated using podman-generated systemd units.

**Comment by Drakota** [comment]
@PavelSosin-320 I'm aware of the bug with WSL consuming a lot of memory ([this](https://github.com/microsoft/WSL/issues/4166)), but with this issue, if you check in your task manager on Windows it will use a lot of memory, BUT if you look inside your distro and check the RAM usage you will see that it's actually very low. The issue I have with the Remote containers is that it does actually show up in Ubuntu as consuming a huge amount of RAM (represented by my screenshot of htop). So this is a issue that's not related to the one you are talking.

**Comment by chrmarti** [comment]
Similar to https://github.com/microsoft/vscode-remote-release/issues/4485. This could be triggered by a process connecting to the forwarding port on the local machine. The VS Code window usually makes 2 connections.

**Comment by chrmarti** [comment]
@Drakota Is this still an issue and could you post an updated log from using the latest VS Code Insiders (1.55) and Remote-Containers (0.164.1)? There should be additional log output now that will tell us if this is indeed from the connection forwarding. Thanks.

**Comment by Drakota** [comment]
@chrmarti I was still able to reproduce the issue with VSCode Insiders updated & Remote-Containers updated
![image](https://user-images.githubusercontent.com/22665836/112555373-7871b880-8d9e-11eb-9684-f134b2fe1c2a.png)

One thing I've noticed is that it doesn't seems to like any watcher:
```json
{
      "name": ".NET Core Launch (web)",
      "type": "coreclr",
      "request": "launch",
      "preLaunchTask": "watch",
      "program": "${workspaceFolder}/bin/Debug/net5.0/business-rbac.dll",
      "args": [],
      "cwd": "${workspaceFolder}",
      "stopAtEntry": false,
      "serverReadyAction": {
        "action": "openExternally",
        "pattern": "\\bNow listening on:\\s+(https?://\\S+)"
      },
      "env": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "sourceFileMap": {
        "/Views": "${workspaceFolder}/Views"
      }
},
```
I've got this launch configuration that uses watch to reload my application everytime, I change something in my code, I was able to reproduce the issue with a create-react-app project that also reloads on code change and another backend project which uses nodemon.

I was not able to find the additional log output you were talking about here's the logs I have and none seems to have things related to this issue:
![image](https://user-images.githubusercontent.com/22665836/112555698-11083880-8d9f-11eb-95b2-7e26d0c33273.png)

**Comment by chrmarti** [comment]
You can find the current log with `F1` > `Remote-Containers: Show Log`.

**Comment by Drakota** [comment]
Hi @chrmarti, sorry for the delay, I didn't saw your reply.
[Here's the `Remote-Containers: Show log`](https://gist.github.com/Drakota/80f818663a96badf468a99b73cf00aa6)
This is the log after I let the processes accumulate.
![image](https://user-images.githubusercontent.com/22665836/114052605-2def4200-985c-11eb-9359-e86b0cb3f85f.png)

**Comment by chrmarti** [comment]
I'm adding more logging to this. Could you retry with Remote-Containers 0.167.0 (requires VS Code Insiders: https://code.visualstudio.com/insiders/), set the Remote-Containers Log Level to Debug in the settings and again post the log here?

**Comment by Drakota** [comment]
[`Remote-Containers: Show log`](https://gist.github.com/Drakota/2d4fc3d2cf5e6465f1c3dce63ef75c86)

Everything updated
![Screenshot 2021-04-09 203555](https://user-images.githubusercontent.com/22665836/114252621-33d84680-9974-11eb-83b5-648cc1719b00.png)

**Comment by chrmarti** [comment]
Thanks, still looking for a clue what might be going on.

Could you open the Remote Server log (`F1` > `Output: Focus on Output View`) and attach/post its contents here?

Could you also open the dev console (`Help` > `Toggle Developer Tools`) and attach its contents here?

**Comment by Drakota** [comment]
(Here's the logs)[https://gist.github.com/Drakota/d1b0cda35411137fb0b2702041e3d81e]

**Comment by chrmarti** [comment]
It doesn't seem to connect to the VS Code Server. Can you check what runs on the port it connects to by running `netstat -tunlp` inside the container? The port we are looking for might change over time and is the third in the log line:
```
Port forwarding connection from 53501 > 42271 > 42271 in the container.
```

**Comment by chrmarti** [comment]
Hold on, we use that forwarding only for the VS Code Server. So the question is what connects to it. Are the above logs from when you are observing the problem?

**Comment by chrmarti** [comment]
Adding logging to see the connecting process. This will be in the next version and requires the Remote-Containers Log Level to be set to 'trace' in the user settings.

**Comment by chrmarti** [comment]
Added more logging with Remote-Containers 0.170.0. Please give that a try, set the Remote-Containers Log Level setting to trace and post the log here. This version of Remote-Containers currently requires VS Code Insiders: https://code.visualstudio.com/insiders/

![image](https://user-images.githubusercontent.com/9205389/115578737-d32b0100-a2c5-11eb-99ab-fa548a957ace.png)
