### ISSUE TITLE
Can't connect to <host> : unreachable or not Linux x86_64

### ISSUE THREAD

**Issue by matsch01** [microsoft/vscode-remote-release#408]
- VSCode Version: Version 1.35.0-insider
- Local OS Version: OSx 10.14.5 (18F132)
- Remote OS Version: Windows 10 Pro
- Remote Open SSL Version: 1.0.2e
- Remote Extension/Connection Type: SSH

Issue:
Can't remote-ssh via Code-Insiders from my Mac to a Windows PC running Open SSH. 

Both OpenSSH SSH Server and OpenSSH Authentication agent are running on the Windows machine.

I am not using a passphrase

Things that do work:
- I can ssh from my Mac to the Windows machine from the command line.
- I can Remote-SSH via Code-Insiders to other linux boxes using same keys.

Steps to Reproduce:

1. Open Code Insiders
2. In Remote-SSH window connect to Windows config.

**Comment by roblourens** [comment]
Windows is not currently supported https://github.com/microsoft/vscode-remote-release/issues/25
