### ISSUE TITLE
"See all available ports" doesn't do anything

### ISSUE THREAD

**Issue by benedikt-mayer** [microsoft/vscode-remote-release#4080]
- VSCode Version:Version: 1.52.0-insider (user setup)
Commit: 0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d
Date: 2020-11-26T07:36:22.965Z
Electron: 11.0.2
Chrome: 87.0.4280.63
Node.js: 12.18.3
V8: 8.7.220.24-electron.0
- Local OS Version: OS: Windows_NT x64 10.0.19041
- Remote OS Version: Ubuntu 20.10
- Remote Extension/Connection Type: WSL
Steps to Reproduce:

1. Clone a minimal project such as https://github.com/cloudfoundry-samples/dotnet-core-hello-world
2. Start a web application on WSL
3. The notification `Your service running on port 5000 is available. See all available ports` pops up
4. Click on `See all available ports`
5. Nothing happens.

Also, if another application (app A) is already running on port X (in another VS Code WSL window), both windows will show the port X of app A in the notification. Let me know if this should be a separate issue.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by alexr00** [comment]
"See all available ports" shows the "Ports" view. Do you perhaps have the ports view open already?
