### ISSUE TITLE
Remote SSH should consider providing a filter for "candidate" ports

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#4082]
Now that we automatically forward ports and show a notification, port 22 is getting automatically forwarded when using Remote SSH and it is shown in a notification.

The API allows Remote SSH to filter out ports that shouldn't be shown in the Ports view:

https://github.com/microsoft/vscode/blob/dcf4cd2a507c5678afa102968fb93a0ba5727d3d/src/vs/vscode.proposed.d.ts#L257-L257

Since it may be possible that users do want to sometimes forward port 22 (and the ssh port might not always be 22), I don't think this filtering should occur in the core, but I can be convinced otherwise!

**Comment by roblourens** [comment]
I don't see port 22 being detected

![image](https://user-images.githubusercontent.com/323878/100550760-00044c00-3231-11eb-9c03-1364cd4b4963.png)
