### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ZXMDavid** [microsoft/vscode-remote-release#4086]
- Issue Type: `Performance`
- Extension Name: `remote-wsl`
- Extension Version: `0.51.4`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\ADMINI~1\AppData\Local\Temp\ms-vscode-remote.remote-wsl-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bamurtaugh** [comment]
Hey @ZXMDavid, could you please try attaching the necessary file (looks like the name of the file path just got pasted into the issue)? And if you have any additional info/context around your issue, that'd be helpful to share as well.
