### ISSUE TITLE
Containers: Support to define the machine specific settings in the devcontainer.json

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#409]
Today container definitions which require machine specific settings e.g. the [Go container definition](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/go/.devcontainer) define a [settings.vscode.json](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/go/.devcontainer) file that is then copied by the [Dockerfile](https://github.com/microsoft/vscode-dev-containers/blob/543b220ae39ff0b3c082b56c2f538a79ea0223f9/containers/go/.devcontainer/Dockerfile#L32).

The proposal is to simplify this approach and to move the machine specific settings to the same place where the extensions are defined, that is, to the `devcontainer.json` file. There will be a new section `settings` where the machine specific settings can be defined:

`devcontainer.json`
```json
{
	"name": "Go",
	"dockerFile": "Dockerfile",
	"extensions": [
		"ms-vscode.go"
	],
	"settings":  {
		"go.gopath": "/go"
	}
}
```

This approach will also simplify the migration to support running for both the stable and the insiders version. When provisioning the server the container extension can copy the machine specific settings to the 'quality' specific location.

//CC @Chuxel

**Comment by chrmarti** [comment]
Should we name it `"initialSettings"`? Otherwise it can easily be read as the current settings, when they are copied over only once after the container was created.

**Comment by egamma** [comment]
If we want to qualify the setting more then another option is `machineSettings`.

**Comment by egamma** [comment]
//CC @lostintangent fyi

**Comment by Chuxel** [comment]
Another related topic is environment variables. Right now you can specify these via runArgs, but if you don't control the other side, this may not always work. Something for us to consider as we support working with remote containers.
