### ISSUE TITLE
zsh: bad math expression: operand expected at `*100000 + ...' on some linux platforms

### ISSUE THREAD

**Issue by ganler** [microsoft/vscode-remote-release#4090]
# Description

As a non-root linux user who wants to use `zsh` instead of `bash`, we typically add `exec /path/to/zsh -l` in `$HOME/.bashrc`. 

However, for some linux distributions, this will make the Remote SSH functionality of VSCode unavailable (https://github.com/microsoft/vscode-remote-release/issues/2027).

# Environment

This also occurred on my linux server:

## OS

```
# cat /proc/version 
Linux version 3.10.0-514.10.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Fri Mar 3 00:04:05 UTC 2017
```

## .bashrc

```shell
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
export SHELL=$HOME/bin/zsh
exec $SHELL -l
```

---

Thus, I am reporting this issue that I hope if we can make things compatible by modifying codes on the vscode-remote side.

On the user side, the solution proposed in https://github.com/microsoft/vscode-remote-release/issues/2027 is not ideal. One solution that worked for me is to put `exec /path/to/zsh -l` in `.bash_profile` (or `.profile` for ubuntu) instead of `.bashrc`. I hope this note could help. @liuzqt

e.g., my `.bash_profile`:

```shell
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH
export SHELL=$HOME/bin/zsh
[ -z "$ZSH_VERSION" ] && exec $HOME/bin/zsh -l
```

Thanks.

**Comment by roblourens** [comment]
I would also recommend changing your shell with `chsh` instead of redirecting from bash to zsh like this. Also the other suggestion from that issue might help

> You could probably work around it by only running that when in an interactive session.

Glad you found a workaround however

**Comment by ganler** [comment]
> I would also recommend changing your shell with `chsh` instead of redirecting from bash to zsh like this. Also the other suggestion from that issue might help
> 
> > You could probably work around it by only running that when in an interactive session.
> 
> Glad you found a workaround however

Yes. But it is not applicable for non-root users.

**Comment by roblourens** [comment]
I have another issue to try to try to set some var in this environment, but I don't think I can do that reliably. I can't write a script that will be compatible with all shells. Not sure what else I can do on our end.

**Comment by ganler** [comment]
@roblourens  That's fine. At least we have this issue so that people who get into this trouble could follow our proposals and get in touch with us.
