### ISSUE TITLE
Go PATH appears broken

### ISSUE THREAD

**Issue by iJebus** [microsoft/vscode-remote-release#4092]
- VSCode Version: 1.52.0-insider
- Local OS Version: Darwin x64 19.6.0
- Name of Dev Container Definition with Issue: Go

Steps to Reproduce:

1. Create Go dev-container using default settings

```sh
vscode ➜ /workspaces/godevtest $ go
bash: go: command not found
vscode ➜ /workspaces/godevtest $ echo $PATH
/vscode/vscode-server-insiders/bin/x64/0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d/bin:/usr/local/share/nvm/versions/node/v14.15.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/vscode/.local/bin:/home/vscode/.local/bin
```

I imagine it's a pretty easy fix but I don't have time to get into it right now.

**Comment by chrmarti** [comment]
The CLI flag in VS Code was renamed to `--force-disable-user-env`. I'll update the extension.

**Comment by chrmarti** [comment]
To verify:
- `F1` > `Remote-Containers: Try Sample` > `Go`.
- Verify `go` is on the path when you open a terminal.
