### ISSUE TITLE
Remote machine seems to keep falling asleep while connected causing connection loss (SSH)

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-remote-release#4097]
- VSCode Version: `1.52.0-insiders`
- Local OS Version: `Windows 10.0.20262.0` (current Dev Channel) ARM64 (Surface Pro X)
- Remote OS Version: `Windows 10.0.19042.0` (current Beta Channel)
- Remote Extension/Connection Type: `SSH`

Steps to Reproduce:

1. Connect to remote, edit code for a while (longer than the sleep time on the remote)
2. Get disconnect dialog, but reconnect won't work, even a window reload won't work
3. Wake the remote machine (I used a magic packet)
4. Connect to remote again and it will work

**Comment by roblourens** [comment]
I assume that if you just have a normal ssh session on this machine, the same thing will happen, unless you run a program that prevents the host from sleeping. You could try setting `TCPKeepAlive`? If just having an active ssh session should prevent the host from sleeping, you could file an issue on https://github.com/PowerShell/Win32-OpenSSH/issues

**Comment by eamodio** [comment]
Opened: https://github.com/PowerShell/Win32-OpenSSH/issues/1712

Was able to repro with just a terminal SSH session.
