### ISSUE TITLE
Add options to control the consistency of the source mount

### ISSUE THREAD

**Issue by shi-yan** [microsoft/vscode-remote-release#41]
on mac, the workspace folder doesn't seem to be mounted with consistency=cached

this causes low io performance 

see https://stories.amazee.io/docker-on-mac-performance-docker-machine-vs-docker-for-mac-4c64c0afdf99?gi=ab8ea7964793

for details.

`docker run --mount src="$(pwd)/../../myproj",target=/work/myproj,type=bind,consistency=cached`

**Comment by chrmarti** [comment]
Not sure if `cached` will be a safe choice for all workloads. Marking as feature request for now.

In the meantime you could used a Docker Compose file to control all options.

**Comment by shi-yan** [comment]
I agree it shouldn't be a choice for all workloads, I think it should be an option user can set.

But without it, the performance is so bad on mac, it is barely usable. you could try building a large c++ program and compare it with the native performance.

**Comment by chrmarti** [comment]
I have seen the best performance when using a volume mount and checking out the source there. You can do that and/or control the consistency by using a Docker Compose file: https://code.visualstudio.com/docs/remote/containers#_using-docker-compose

**Comment by egamma** [comment]
>I have seen the best performance when using a volume mount and checking out the source there.

@chrmarti @chuxel suggest to document this in tips & tricks?

**Comment by shi-yan** [comment]
so I have tried docker compose, somehow, vscode got stuck at the "creating container" stage. the container was created, as I was able to see it with docker container ls. there is no additional info for me to debug.

**Comment by chrmarti** [comment]
@shi-yan What's in the Dev Container terminal when it gets stuck?

**Comment by Chuxel** [comment]
> I have seen the best performance when using a volume mount and checking out the source there.
> @chrmarti @Chuxel suggest to document this in tips & tricks?

@egamma @chrmarti We could add this in, but VS Code would still volume mount the project using `-v` as well and use that as the working directory. It might cause more confusion than it would help.  If the `workspaceFolder` property worked in the non-compose case, we could redirect it, but it does not.

**Comment by shi-yan** [comment]
@chrmarti this is all the output I saw from the terminal:
`Setting up container for folder: /Users/shiyan/xxx
Run: docker-compose -f /Users/shiyan/xxx/docker/docker-compose.yml up -d --build
Pulling ide (ubuntu:)...
latest: Pulling from library/ubuntu
Recreating docker_ide_1 ... done`

**Comment by chrmarti** [comment]
@shi-yan Is the `"service"` property in your devcontainer.json pointing at an existing service? (Could be #102.)

**Comment by shi-yan** [comment]
could be, I don't remember I set it. I will try again when I get back home. Thanks!

**Comment by shi-yan** [comment]
@chrmarti , yes, the issue is indeed #102, adding "service" resolved it.

**Comment by chrmarti** [comment]
Thanks @shi-yan. Keeping this issue for the consistency option.

**Comment by chrmarti** [comment]
Adding `"workspaceMount"` to override the default mount.

**Comment by connorshea** [comment]
How do you use `workspaceMount`? Is it just the literal args?

**Comment by Chuxel** [comment]
@chrmarti I don't think this particular case is fixed yet.  We'd need to support ${workspaceFolder} to get this to work.  Unfortunately `${env:PWD}` is going to be where VS Code starts, not the workspace location.

This works:
```json
     "workspaceFolder": "/workspace",
    "workspaceMount": "src=/absolute/path/to/where/source/code/is/on/host,dst=/workspace,type=bind"
```

This doesn't:
```json
     "workspaceFolder": "/workspace",
    "workspaceMount": "src=${workspaceFolder},dst=/workspace,type=bind"
```


The remote case is supported, but this one requires an absolute path as things are now which really isn't workable.

**Comment by chrmarti** [comment]
Tracking in #442, so we can test and verify this independently.
