### ISSUE TITLE
sudo group user GDB attach to process failed

### ISSUE THREAD

**Issue by hzcheng** [microsoft/vscode-remote-release#410]
Issue Type: <b>Bug</b>

When I use remote-ssh connecting to my virtual machine, and use gdb to attach to a process, I failed with previldge problem. But I am a sudo user and no window was popped out asking for password.

Extension version: 0.37.0
VS Code version: Code - Insiders 1.35.0-insider (4ca38ce5584d7cd67b435b3c32ef1240c6a29628, 2019-05-21T05:17:12.031Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.18.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: localvm|
|OS|Linux x64 4.18.0-20-generic|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (2 x 1992)|
|Memory (System)|3.85GB (0.58GB free)|
|VM|100%|
</details>

**Comment by roblourens** [comment]
Are you doing this via the C++ extension? If so please file your issue on https://github.com/Microsoft/vscode-cpptools and include some more details about exactly what you did, what error you see, etc.
