### ISSUE TITLE
git add not working

### ISSUE THREAD

**Issue by SultanMu** [microsoft/vscode-remote-release#4100]
Issue Type: <b>Bug</b>

git add not working

Extension version: 0.51.4
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400T CPU @ 2.00GHz (12 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (7.17GB free)|
|Process Argv|--crash-reporter-id e17dd626-54e5-4064-b31e-6ffdf9948caf|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i5-10400T CPU @ 2.00GHz (12 x 1992)|
|Memory (System)|15.83GB (7.17GB free)|
|VM|0%|
</details>

**Comment by bamurtaugh** [comment]
Hey @SultanMu, could you please provide some more info, including any error log and some repro steps/what you were doing?
