### ISSUE TITLE
Test: Server and extension cache on Docker volume

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#4102]
- [x] windows @rebornix
- [x] macOS @mjbvz

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%234102%0A%0A)

---

Make sure you are running the latest Remote-Containers 0.152.0.

- Create a Dev Container with a single container 1) and
  - verify that in `~/.vscode-server-insiders/bin` there is a symbolic link to the server install.
  - verify that in `~/.vscode-server-insiders/extensionsCache` there are symbolic links for those extensions that were already in the cache when the container was created. 2)
- Repeat when cloning a repository into a Docker volume (`F1` > `Remote-Container: Clone Repository in Container Volume...`). E.g.: https://github.com/microsoft/vscode-remote-try-node.git

Notes:
1) Open an empty folder and `F1` > `Remote-Containers: Rebuild and Reopen in Container`.
2) Add a few `"extensions"` to the devcontainer.json if there are none yet and `F1` > `Remote-Containers: Rebuild Container`. Then wait for the VSIXs to be copied to `/vscode/vscode-server-insiders/extensionsCache`. Rebuild again and check the symbolic links indicate use of the cache.

**Comment by mjbvz** [comment]
Looking good on MacOS!
