### ISSUE TITLE
Lack of GLIBCXX_3.4.22 on Ubuntu 16.04 for x86_64

### ISSUE THREAD

**Issue by Fydon** [microsoft/vscode-remote-release#4103]
- VSCode Version: 1.52.0-insider (commit 0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d)
- Local OS Version: Windows 10 (Windows_NT x64 10.0.19042)
- Remote OS Version: Ubuntu 16.04 for x86_64
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect via SSH.

Like #2998 the VM lacks GLIBCXX_3.4.22, which is where [I originally posted this](https://github.com/microsoft/vscode-remote-release/issues/2998#issuecomment-735738520). I was asked to create a new issue given that the fix for that issue is for ARM.
```
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/ubuntu/.vscode-server-insiders/bin/0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d/node_modules/spdlog/build/Release/spdlog.node)
```
Which I confirmed:
```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX_3.4.2
GLIBCXX_3.4.2
GLIBCXX_3.4.20
GLIBCXX_3.4.21
```

Like #3857 I was made aware of the issue by uriTransformer.js taking up 100% of CPU. That issue was closed as it was deemed related to the above issue.

Does this issue occur when you try this locally?: When connecting with VSCode stable using remote or putty I don't experience the issue. The VM doesn't have the resources to run VSCode locally.
Does this issue occur when you try this locally and all extensions are disabled?: When connecting remotely, I tried disabling extensions but it didn't appear to solve the issue.

**Comment by darrenkenny** [comment]
(Copied over from #2998 )

For the record, I'm seeing this same problem with GLIBC on Oracle Linux 7, which is similar to CentOS 7 and RHEL 7 - where the version of libstdc++.so.6 doesn't contain the GLIBCXX_3.4.22 that is being required, it only goes up to GLIBC_3.4.21.

```
*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


IP Address: 100.100.230.168
IP Address: 172.17.0.1
Extension host agent listening on 39571


[09:39:41] Extension host agent started.
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/darrenk/.vscode-server-insiders/bin/f47aae014cf8567f648e68369d66b4106ae89f08/node_modules/spdlog/build/Release/spdlog.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1187:18)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
```

I'm running the latest binaries on OL7. 

This is only happening to me since updating to the latest viscose insider builds, if I downgrade to a version from several weeks back, it works fine again - so I'm presuming there has been some upgrade on the builds of the remote end binaries.

The version that works for me is:

```
Version: 1.52.0-insider
Commit: 24b28f57be22fe3029cb17a1dd72d8d9c2d6468b
Date: 2020-11-06T05:39:23.276Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

I've tried using the OL8 version of the library, but it doesn't work since it starts to drag in other libraries, and eventually fails because the ld-linux.so version is also wrong.

But really, as I think mentioned elsewhere, the binaries on the remote side should probably be statically linked if at all possible to avoid this kind of versioning issue - somewhat akin to what the 'go' language does here for that same reason.

**Comment by levigross** [comment]
Same issue on RHEL 7.6

**Comment by Fydon** [comment]
With VSCode 1.52.0-insider commit `f4187f22026ff6537f2ca8132ad3209fceb5071f` I don't seem to be seeing this issue anymore. There isn't a log about GLIBC and I don't have 100% CPU usage for uriTransformer.js.

@darrenkenny @levigross Is it also working for you now as well?

**Comment by Fydon** [comment]
Actually I see that the Electron version was downgraded from 11.0.2 to 9.3.5 so that is probably why this is working again.

**Comment by darrenkenny** [comment]
It does seem to be working again now, using version:

```
Version: 1.52.0-insider
Commit: 92192baf760315ac47fb2caaf3ce6d0778962352
Date: 2020-12-03T05:41:19.707Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

I'm able to connect to the remote server without any connection errors.

**Comment by deepak1556** [comment]
Would like some early testing for a potential fix with Electron 11 builds , please check https://github.com/microsoft/vscode-remote-release/issues/4087#issuecomment-738572501 for context. Thanks!

**Comment by Fydon** [comment]
Thank you @deepak1556. I take it that the packages are of VSCode? Would you be able to provide a Windows 64 bit build?

**Comment by darrenkenny** [comment]
@deepak1556  - A MacOS build would be good for me too ;-)

**Comment by Fydon** [comment]
Thank you @deepak1556. That seems to work well thank you. The `Inappropriate ioctl for device` is also in the insider buld. #557 says that this is "from reading the shell env", but doesn't say how to get rid of the error. It doesn't appear to cause any issues though.
```
*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

Extension host agent listening on 44781

[04:19:23] Extension host agent started.
[04:19:24] [127.0.0.1][644fd31b][ManagementConnection] New connection established.
[04:19:24] [127.0.0.1][a99ad69c][ExtensionHostConnection] New connection established.
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[04:19:24] [127.0.0.1][a99ad69c][ExtensionHostConnection] <4666> Launched Extension Host Process.
[04:19:24] Listing 0 persistent terminals, 0 total terminals

```

**Comment by deepak1556** [comment]
Thanks for testing! closing the issue. I don't have context on the bash error, definitely not related to the server bits.

**Comment by tysonite** [comment]
#3857 described an original issue I found on ARMv7. I was not able to test fix till now, but I see that the behavior is the same with vs code 1.52.1. uriTransformer.js uses 100% CPU and spdlog.node still requires GLIBCXX_3.4.22:

```
~/.vscode-server$ ldd ./bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node_modules/spdlog/build/Release/spdlog.node
./bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node_modules/spdlog/build/Release/spdlog.node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node_modules/spdlog/build/Release/spdlog.node)
        linux-vdso.so.1 =>  (0xbedce000)
        libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0xb6e7a000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb6e02000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb6dda000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb6db6000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6cca000)
        /lib/ld-linux-armhf.so.3 (0xb6fcd000)
```
