### ISSUE TITLE
Ports: Don't show the Open Browser notification when a port has already been forwarded

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#4105]
- open this app that has been created with React Starter in a Remote Container https://github.com/egamma/my-app
- yarn
- yarn start
- `yarn start` opens the port 3000 in a browser tab.

The notification to open port 3000 also appears in VS Code. Since the port has already been opened (through the Opener service) the notification is not helpful and should not be shown.

![image](https://user-images.githubusercontent.com/172399/100744011-675eff00-33dd-11eb-9e24-249eebad5986.png)

**Comment by alexr00** [comment]
Done with https://github.com/microsoft/vscode/commit/f9d6df8ea1eb3af5db290a71a9b4e02a58e54182
