### ISSUE TITLE
QuickPick to create devcontainer.json takes long to open

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#4107]
It looks like collecting stats takes long. We should use the file type information we get from readDirectory to avoid roundtrips and open the QuickPick early with a progress indicator.

**Comment by chrmarti** [comment]
To verify: Add configuration to Codespace with many files. (Requires update from Codespaces extension.)

**Comment by aeschli** [comment]
Verified by opening vscode-docs in a codespace, removed the existing `devcontainer,json` file, run the `Add Development Container Configuration Files...` command.
Takes around 2 second.

Please speak up if these are the wrong steps.

**Comment by chrmarti** [comment]
It would be best to verify this with the Codespaces extension once that has picked up the fix (presumably with its next release). That currently takes ~4 seconds for me with the test you use with `vscode-docs`. Thanks.

**Comment by aeschli** [comment]
For the record, I tried with Github Codespaces 0.3.2 | 12/4/2020
