### ISSUE TITLE
is it possible use devcontainer in remote-ssh mode?

### ISSUE THREAD

**Issue by markshao** [microsoft/vscode-remote-release#4108]
My vscode is running on my mac , but I have a devbox (Linux based) remotely with docker installed.

Fail to mound workspace from mac to remote devbox  . So I want to try open workspace remotely inside devbox , and hope to active devcontainer in the devbox , but the vscode will not auto detect it when in remote-ssh mode .

I think it will be helpful if we can support it

**Comment by chrmarti** [comment]
Attaching to an existing container while connected through Remote-SSH now works (assuming you don't need to enter credentials to ssh in). Opening a folder in a container is tracked with https://github.com/microsoft/vscode-remote-release/issues/2994.
