### ISSUE TITLE
Is there a way to open vscode in normal windows rather than WSL by default?

### ISSUE THREAD

**Issue by bonniesimon** [microsoft/vscode-remote-release#4109]
Right now when I open vscode from my WSL distro terminal using "code .", it opens in WSL remote mode. But I  don't want this. I want to open vscode in the normal windows mode. Can I achieve this?

**Comment by bamurtaugh** [comment]
Is there a reason you need to use the WSL distro terminal? You could use "code ." from a regular Windows terminal to open VS Code without being connected to WSL.

**Comment by bonniesimon** [comment]
I use the WSL ubuntu terminal to open vscode. But I don't want it to open in remote WSL mode. I would prefer normal vscode.
I use remote WSL for things that don't work in normal vscode mode.

**Comment by bamurtaugh** [comment]
I see - so you typically open VS Code from your Ubuntu terminal, but you only sometimes want to use Remote - WSL with it. Is there a reason you prefer not to be connected to Remote-WSL? 

This would be a feature request as `code .` from a distro terminal when you have Remote - WSL installed in VS Code will automatically connect your new VS Code instance to Remote - WSL.
