### ISSUE TITLE
Notification about VNC on every connection

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#4110]
Testing #4094

Every time I connect to one of my remotes that has a VNC server running, I get this notification

![image](https://user-images.githubusercontent.com/323878/100781469-ee9d7a00-33bf-11eb-91b6-63a893e7d1cb.png)

I have "don't show again" as an option and will probably use that, but it seems unexpected because this service doesn't have any connection to vscode and I thought only child processes of vscode would be automatically forwarded. I don't know whether this is a problem, but it's probably not unusual to have some service running on your ssh remote that is not relevant to the current workspace.

**Comment by alexr00** [comment]
@roblourens I try to exclude processes that were started before VS Code is running. Is this something that is running before you connect?

**Comment by roblourens** [comment]
Yes

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode/commit/0b1892f877e0f842ec3af08d8ee0c4cf914b8bf8
