### ISSUE TITLE
VNC port forwarded twice

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#4111]
Testing https://github.com/microsoft/vscode-remote-release/issues/4094

My VNC server's port is forwarded twice to two local ports. I don't have anything in settings to forward this port. I can run some commands to debug it if needed.

![image](https://user-images.githubusercontent.com/323878/100782305-150fe500-33c1-11eb-8261-daebc8dc6070.png)

**Comment by alexr00** [comment]
@roblourens does this happen every time?

**Comment by roblourens** [comment]
Yeah

**Comment by alexr00** [comment]
@roblourens I wonder if you have some stale state. Do you have `remote.restoreForwardedPorts` set? If so, can you un-forward both ports, reload, then try to repro again?

**Comment by roblourens** [comment]
Oh, that actually seemed to work!
