### ISSUE TITLE
Detected ports duplicate already forwarded environment ports

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#4112]
Testing #4094

I have an ssh configured host like

```
Host robfast-vnc
	HostName 168.62.29.176
	User roblou
	IdentityFile ~/.ssh/azurevm
	LocalForward 5921 localhost:5901
	LocalForward 1234 localhost:4321
	ForwardAgent yes
```

I detect these LocalForward ports and set them in `environmentTunnels`, then they are detected and forwarded again. 

![image](https://user-images.githubusercontent.com/323878/100782734-b139ec00-33c1-11eb-94b3-337228c691bd.png)

**Comment by roblourens** [comment]
Two things, I still see 5901 forwarded, but only once, so that is probably related to the fact that there were two entries originally. Secondly, I still get a notification when 4321 is opened and closed, but nothing new is forwarded.

![image](https://user-images.githubusercontent.com/323878/101072327-b2e6e980-3552-11eb-897c-b71af91321f8.png)

![Dec-03-2020 10-33-26](https://user-images.githubusercontent.com/323878/101072545-0a855500-3553-11eb-8c3b-346a64c10aea.gif)

**Comment by alexr00** [comment]
This looks like a timing issue. I think we are starting auto port forwarding _before_ we set the Detected tunnels from SSH.

**Comment by alexr00** [comment]
@roblourens thanks for catching this. I always test with Containers and never would have found this problem there!

**Comment by roblourens** [comment]
I still see the same two issues mentioned above

**Comment by alexr00** [comment]
@roblourens I can't repro 5901 getting forwarded. Do you have `remote.restoreForwardedPorts` set? That would restore it.

I also can't repro the second issue. I'm using Remote SSH, and I added 
```
	LocalForward 5921 localhost:5901
	LocalForward 1234 localhost:4321
	ForwardAgent yes
```
to my ssh config. Are there any other steps?

**Comment by alexr00** [comment]
@roblourens I think you were hitting https://github.com/microsoft/vscode/issues/112159
The change is in master, and will be in the next insiders since its a candidate. 
Once you have the change, can you try removing all your forwarded port, reloading, then seeing if you still see issue?

**Comment by alexr00** [comment]
I think I got the last timing issue with a recent change. Closing for verification.

**Comment by connor4312** [comment]
@roblourens please verify this one 🙂
