### ISSUE TITLE
Notification when port is unforwarded

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#4115]
Testing #4094

- Start a node server on some port with `npx http-server -p 9874`
- Get a notification that the port is forwarded
- ctrl+c to kill the server
- The port is unforwarded and I get another notification about some other port that was already forwarded

**Comment by roblourens** [comment]
This does not happen every time, but it has happened several times

**Comment by alexr00** [comment]
> I get another notification about some other port that was already forwarded

How was this other port forwarded?

**Comment by roblourens** [comment]
When I was testing this, it was node's debug port

**Comment by roblourens** [comment]
(so an automatically detected and forwarded one)

**Comment by alexr00** [comment]
Didn't mean for this to be closed by the bot!
Same root cause as https://github.com/microsoft/vscode/issues/112159
