### ISSUE TITLE
if curl/wget not availiable, use scp

### ISSUE THREAD

**Issue by Merith-TK** [microsoft/vscode-remote-release#4116]
So the idea came from an error i just recently got when tinkering with my pi3b

I installed a distro on it that did not come with `wget` or `curl`. And I immediatly thought of an work around to it

Use the hosts wget/curl program, (if not availible, could use an ioWriter to get the data and write to file? idk if possible)
Download the tarball/binaries needed. 
Use `scp path/to/file user@server:'~/.vscode-server/where/you/need-it'`

It would be a pretty good fallback as the vast majorities of ssh clients, do have an `scp` command bundled with them,

**Comment by roblourens** [comment]
I actually fixed this recently, you can try the Nightly version of the ssh extension or wait for the next update.

**Comment by Merith-TK** [comment]
oh! that's cool! glad i wasn't the only one with this idea!
