### ISSUE TITLE
Don't remove extension output channels when the EH goes down

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#412]
- Connect to SSH remote
- Go offline long enough that we stop trying to reconnect
- When we decide that the remote EH is gone, we take down all EHs
- When the local EH goes down, we get rid of all extension output channels
- So then I can't see the ssh output channel and that can make it hard to understand some reconnection issues

If some extension crashes the EH it would also be useful to see its logs, so this seems like a generally useful thing to do.

**Comment by roblourens** [comment]
Is there any way we can get this fixed? It's making debugging and handling github issues harder. I am happy to look at it if someone can give me pointers. Dunno if it should have been assigned to @alexandrudima instead.

**Comment by roblourens** [comment]
This is still making it difficult to get the log from people sometimes. Can you give me some pointers on fixing this? The log file is still on disk, I just want the entry to stay in the ouput channel.

**Comment by alexdima** [comment]
@roblourens 

https://github.com/microsoft/vscode/blob/be0aca7188ec6a76e7c2379758c0fbc1e9c21f7b/src/vs/workbench/api/browser/mainThreadOutputService.ts#L52

I did not write that code, but I think that `$dispose` call ends up cleaning the outputs created by extensions from a certain extension host.

**Comment by roblourens** [comment]
@sandy081 I propose 

1. getting rid of the dispose call that @alexdima linked above
2. Changing the registry to replace the current output channel when a new one is registered with the same id, here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/output/common/output.ts#L61

That would mean that if two output channels are registered with the same ID, the second one would win instead of being a no-op, but that shouldn't really happen anyway. Is that ok with you?

**Comment by sandy081** [comment]
@roblourens I do not think it is correct approach as it causes leak. All data associated to an extension should be disposed when it goes down. Also, note that output channel ids are unique and they are created from an incremental id pool. So you won't get the same id.

Right approach is to create a log file for yourself which can persist just like how containers extension does. We can include this functionality in core by creating log file channels using output API which can help other extensions too.

**Comment by roblourens** [comment]
Even if I write to a log file, I can't give users a command to open that log file after we failed to connect because of https://github.com/microsoft/vscode/issues/88111.

I really don't know what else to do - I could write to a log file and console.log the path so it shows up in devtools and a user can retrieve it from there?

**Comment by roblourens** [comment]
This could also go back to not taking down the local EH when we fail to connect but changing that could have other consequences.

**Comment by sandy081** [comment]
I do not understand why the log file approach does not work. My proposal is to let extension contribute a log file while creating an output channel. 

Currently VS Code creates a random file for each output channel. Instead it can use the file provided by the extension and writes into this file. It's up to you to give the same file always or file per session etc., and VS Code shows the complete log from the given file.

And User can run the core command to see this output channel even when extension host is down. Only limitation is that file based output channels will not work in web extension host I think which is ok.

**Comment by roblourens** [comment]
> And User can run the core command to see this output channel 

So the output channel would not be removed when the EH goes down? That's fine with me, or do you mean the "Open log file" command to open the file directly? Also fine with me but currently that command doesn't include extension output channels. And you are proposing new extension API right?

**Comment by sandy081** [comment]
Output channel will be removed always when the EH goes down. I meant you can provide the location of the file on disk to get the logs.

I think you can already do this - providing the location of the output channel log file on disk. Because as I said, output channels are backed by files. They are stored in exthost folder in logs location. You can get the logs location using the command `Open Logs Folder`. Tricky part is that user has to find the right extHost folder. If needed we can have another command to open `extHost` logs folder.

I would go for the second option before trying more changes.

**Comment by roblourens** [comment]
> I think you can already do this - providing the location of the output channel log file on disk.

Not from an extension, as far as I know.

> You can get the logs location using the command Open Logs Folder. Tricky part is that user has to find the right extHost folder. If needed we can have another command to open extHost logs folder.

Yeah, that is what I tell people to do currently and I can't be sure that they found the correct log and not one from a different EH. 

If there was a command to open the extHost logs folder, that would be a big improvement. I could  add an action for that?

**Comment by sandy081** [comment]
> Not from an extension, as far as I know.

Yeah not from an extension. I meant manually.

Yes an action to open extHost logs folder is a good start.

**Comment by roblourens** [comment]
Verifier: Test the new "Open Extension Logs Folder" command

**Comment by aeschli** [comment]
Verified that SSH logs can be accessed through  "Open Extension Logs Folder"
