### ISSUE TITLE
I would like to be able to sync files to remote from the app without rsync explicitly

### ISSUE THREAD

**Issue by hanan-vian** [microsoft/vscode-remote-release#4121]
I would like vscode to support remote file sync like in pycharm professional. https://www.jetbrains.com/help/pycharm/uploading-and-downloading-files.html#59abd
It allows:
* Automatic upload to the server after save and or commit
* excluding and including file patterns or paths (e.g. data)
* running the local file or the remote one (on the remote machine)
* edit the remote or local file and diff between them
* syncing between the local and remote folders
* git operations from the remote or local

**Comment by roblourens** [comment]
Sorry, this is not the use case that we are targeting, but you can use other tools to do this sort of thing like rsync
