### ISSUE TITLE
Extension dependencies are not cached on Docker volume

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-remote-release#4122]
Testing #4102

* Add `rebornix.ruby` to dev container
* Rebuild the image
* In `~/.vscode-server-insiders/extensionsCache`, `rebornix.ruby` is a symbolic link but its dependent extension `wingrunr21.vscode-ruby-0.27.0` is not

**Comment by chrmarti** [comment]
Good point. Remote-Containers doesn't look into the VSIX and doesn't know about the dependencies.

@sandy081 One possible simplification for Remote-Containers might be to support a read-only folder for VSIXes in addition to the existing writable folder. That would then allow the server to pick up extensions including their dependencies from the read-only folder.

**Comment by sandy081** [comment]
How does this read-only folder works? Who is to going to write VSIX here? Why not remote containers sym-link all VSIXes from the current cache folder?

**Comment by chrmarti** [comment]
You're right, I need to check what the performance of linking all VSIXes is. 👍

**Comment by rzhao271** [comment]
@rebornix is this issue resolved for you now?

**Comment by PavelSosin-320** [comment]
Dockerfile doesn't follow symlinks and there is a simple explanation for it exists: ADD and COPY commands create a new Image layer. Every image layer representation in the Docker image file is a tar plus layer's metadata. Could you imagine symlink from tar to tar? Every Docker image layer has to be added separately and be self-sufficient.
Docker image inspect command doesn't show the whole picture. But Skopeo enables to look under the image's hood.

**Comment by PavelSosin-320** [comment]
The solution to bundle dependent extensions: Create tar file ahead with --dereference (follow symlink) option. Then Use ADD to add the whole content of the tar as one layer. 
Pros: fewer layers
Cons: restricted layer sharing between containers i.e. poor scalability.

**Comment by PavelSosin-320** [comment]
@chrmarti Podman 2.1 on WSL is here and it is  very mature now. The implementation of Main container - side car extensions takes 5 minutes. The result is meta - Pod resource file. The result is runnable via Podman play kube. No build, no push, no pull, no cache between.
