### ISSUE TITLE
For docker-compose devcontainer stacks: devcontainer.json runArgs parameter

### ISSUE THREAD

**Issue by ascheucher** [microsoft/vscode-remote-release#4124]
For single Docker container dev environments, there is the parameter runArgs to start the container.
The runArgs parameter is ignored for docker-compose.yml setups, which is a petty!

For example there is no way to define environment variables to be only used in the docker-compopse.yml file. Just in case one does not want to add them to the host environment.

Adding something like this into devcontainer.json would solve this:
```
{
	"name": "Project Name - docker-compose",
	"dockerComposeFile": "docker-compose.yml",
        "runArgs": ["--env-file", ".devcontainer/.env"],
        ...
}
```

Thanks for considering.

**Comment by chrmarti** [comment]
You can list multiple files as an array of strings under `"dockerComposeFile"` and these are then merged by `docker-compose` (https://docs.docker.com/compose/extends/#multiple-compose-files). Does that address you request?

**Comment by ascheucher** [comment]
Sorry for the late response. Missed the update. 

> dockerComposeFile
Sadly no, as the `.devcontainer/devcontainer.json` file is also checked in it's the same in different environments.

The idea behind was to have just different .env files in the different environments.

**Comment by chrmarti** [comment]
Not sure what you mean by "different environments". Is this about Python environments?

Wouldn't a second docker-compose.yml allow you to essentially do the same as you suggest by using `"runArgs"`? That second docker-compose.yml would only have the env-file, Docker Compose then merges the two docker-compose.yml at runtime.

You can also use `"remoteEnv"` or `"settings": { "terminal.integrated.env.linux": ... }` to add environment variables - in case that helps.
