### ISSUE TITLE
"Remote-Containers: Reopen Folder Locally" not available

### ISSUE THREAD

**Issue by thomiel** [microsoft/vscode-remote-release#4126]
Issue Type: <b>Bug</b>

"Remote-Containers: Reopen Folder Locally" option isn't shown and doesn't work any more. Now I always have to close VS Code and reopen it to work locally again.

Extension version: 0.148.1
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.4.0-56-lowlatency

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2899)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.38GB (5.11GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id fcaa9fa2-f367-4862-a313-b11c638f8fef|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by chrmarti** [comment]
That should be available when you open a folder in a container. Which command do you use to connect to the container?

**Comment by thomiel** [comment]
Usually, I use the button of the notification that pops up in the bottom right corner of the application window.

**Comment by chrmarti** [comment]
What does the green corner in the lower left show as a caption and doesn't clicking that open a picker with 'Reopen Locally' at the top? Could you add a screenshot?

**Comment by thomiel** [comment]
I just opened VS Code to make screenshots and Reopen Locally reappeared unexplainably...

Can be closed for now. If it happens again, I will try to remember and reproduce all actions on Code and add a follow-up here,
