### ISSUE TITLE
Keeps on disconnected 

### ISSUE THREAD

**Issue by Muhammad-Irfan324** [microsoft/vscode-remote-release#4127]
Issue Type: <b>Bug</b>

I've tried every solution nothing works 
settings.json
ssh config modify 
nothing works

Extension version: 0.56.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.4.0-56-generic
Remote OS version: Linux x64 5.4.0-1030-gcp

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 648)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|15.51GB (8.94GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 63b6a8ae-ac01-435d-be15-2dfce4f26ff3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pantheon|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pantheon|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: terraform-kubernetes-addoptify|
|OS|Linux x64 5.4.0-1030-gcp|
|CPUs|AMD EPYC 7B12 (2 x 2250)|
|Memory (System)|1.94GB (0.76GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Need more details about what you are seeing and what you are doing when you see it
