### ISSUE TITLE
Can not connect sever with ssh 

### ISSUE THREAD

**Issue by shuhaojie** [microsoft/vscode-remote-release#4128]
Hi VS code,
   I try to connect with my server with VScode but it failed.  I have ssh extension downloaded. There are two things that is worth mention. First, I can connect it with my Terminal. Second, not all the servers are not able to connect. I can connect some of them with VScode. Any suggestion?

**Comment by roblourens** [comment]
Need more details, and please share the log from the Remote-SSH output channel

**Comment by shuhaojie** [comment]
> Need more details, and please share the log from the Remote-SSH output channel

After connecing for about 2 minutes. The VS code says `Could not establish connection "name of my server":XHR failed`. And gives me 3 options: `Retry, More Actions, Close Remote`

**Comment by roblourens** [comment]
please share the log from the Remote-SSH output channel

**Comment by shuhaojie** [comment]
> please share the log from the Remote-SSH output channel
The log information
`Resolver error: Error:XHR failded
at XMLHttpRequest.s.onerror(file://....)`
