### ISSUE TITLE
CyberArk PSM for SSH Proxy Server Support

### ISSUE THREAD

**Issue by ofiriluz** [microsoft/vscode-remote-release#4129]
- VSCode Version: 1.44.0
- Local OS Version: windows 10
- Remote OS Version: Red Hat 7/8
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
1. Simple SSH Connection through PSM for SSH Proxy Server of CyberArk

There is another existing issue about it, and i am trying to investigate why this does not work (i am from the cyberark side)
I would like to better understand if possible how the script that you are sending works, because at the moment we receive unexpectef EOF while searching for `"' and cannot understand why

**Comment by roblourens** [comment]
There are two ways that we send the script through ssh.

- `remote.SSH.useLocalServer` setting disabled (default on Windows): effectively `echo "echo hello" | ssh <yourhost> bash` where "echo hello" is actually a much longer script

If that works in a terminal, then our connection process should work, in theory.

- `remote.SSH.useLocalServer` enabled (default on mac/linux): should work the same as the above, but we actually spawn an ssh process and send the script into its stdin

In https://github.com/microsoft/vscode-remote-release/issues/2736, it looks like the script is getting truncated or corrupted

**Comment by ofiriluz** [comment]
Hi,

Yes i am aware of those two, however i cant seem to find out why it gets sent in chunks in that way, why is the script being sent like this and not via scp/sftp and then executed btw?

I cant find the unminified / unobsfucated version of the code to further investigate :)

**Comment by roblourens** [comment]
Because we don't want to make the user auth twice

Unfortunately it's not open source, but it shouldn't really matter exactly what's in the script. It is a couple hundred lines long.

**Comment by michalwiglasz** [comment]
Hi, regarding

> Because we don't want to make the user auth twice

I am OK with double auth, if it bypasses cyberark problems. What about making this a configuration option?
