### ISSUE TITLE
Add "open in current window option" to remote explorer

### ISSUE THREAD

**Issue by gyzerok** [microsoft/vscode-remote-release#4131]
Hello!

It would be really great to have "open in current window" option in the remote explorer for Remote SSH next to the "open in new window" option. The latter option is shown next to the "remembered" directory in the list.

Currently this is possible with command palette, however this way it does not connect to the home directory and you have to specify the whole path again.

Opening in a new window is a great pain point while using split screen on macOS. It requires to break split screen, close old VSCode and rearrange split screen with the new one.

**Comment by roblourens** [comment]
For which remote type?

**Comment by gyzerok** [comment]
Ah sorry. I am using Remote SSH.

**Comment by roblourens** [comment]
You can get it by right clicking, is that what you want?

![image](https://user-images.githubusercontent.com/323878/101224833-acd13580-3644-11eb-8173-ca99eb15f33e.png)

**Comment by gyzerok** [comment]
Oh my! Looks like this is exactly what I want. Have never discovered that right clicking is an option there. Thank you very much!

I am curios why opening in current window is not the choice selected for the icon, but otherwise the issue is resolved.
