### ISSUE TITLE
Add heuristic for not notifying for high numbered ports

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#4133]
When I press `F5` to run the app, I am prompted that my port was detected, I click on "Open in Browser" and I get this:

![image](https://user-images.githubusercontent.com/1487073/101055339-a8225980-353e-11eb-87ad-c2710c4a3dd5.png)

I'm expecting to see a "Welcome to..." message per `/views/index.jade`.

**Comment by alexr00** [comment]
This happens because the debug port for the application is detected first, so that's the one we show a notification for. As a user though, you might just see the button and click on it.

**Comment by alexr00** [comment]
To verify:

1. You can use the microsoft/vscode-remote-try-node sample
2. Clone that sample into a remote (containers, ssh, or codespaces. Containers will likely be easiest because it is the easiest to restart. A brand new Codespace should also work).
3. Make sure that your remote has been restarted or is new (no F5 or other running of the project yet). The debug port getting discovered first seems to happen more often when the application hasn't been run yet.
4. Open the Ports view. Remove the port that the project uses (3000 if using the suggested sample).
5. Get ready to count seconds!
6. F5 or otherwise run your application, and count the number of seconds before the forwarded port notification appears.
7. Verify that the application port shows in the notification and not the debug port.
8. The number of seconds counted in (6) should be 3 or slightly more than 3. If it is < 3, then try from (1) again, because the debug port wasn't discovered first.

**Comment by roblourens** [comment]
This works for apps that listen to a port, but I still get the notification for node debugging an app that doesn't listen to a port

**Comment by alexr00** [comment]
@roblourens thanks for verifying! Yes, we will still show the notification for a "bad" port if there isn't a "better" one to notify about.
