### ISSUE TITLE
Cannot kill vscode server on remote Windows OpenSSH

### ISSUE THREAD

**Issue by ltvan** [microsoft/vscode-remote-release#4134]
- VSCode Version: v1.51.1
- Local OS Version: Mac 10.15.7
- Remote OS Version: Windows 10, OpenSSH 7.7.2.3
- Remote Extension/Connection Type: SSH v0.56.0

Steps to Reproduce:

1. Connect to a server.
2. Run "Kill VS Code Server on host"
Expect: all node processes are stopped and the .vscode-server\bin folder is deleted.
Actual: The process is still there, and the bin folder cannot be deleted. 

I looked at the code sent to server and see that there is an error in that code:

```
Get-Process node | Where-Object Path -match ".*\.vscode-server.*\bin\.*" | ForEach-Object {Stop-Process -Id $_.Id}
Remove-Item -Force -Recurse $env:USERPROFILE\.vscode-server\bin
```

This code found no process at all due to wrong syntax: `\bin` should be `\\bin`. The correct one is that:

```
Get-Process node | Where-Object Path -match ".*\.vscode-server.*\\bin\.*" | ForEach-Object {Stop-Process -Id $_.Id}
Remove-Item -Force -Recurse $env:USERPROFILE\.vscode-server\bin
```

**Comment by ltvan** [comment]
Additional note: in case that the command is executed, some binaries are deleted but not all (due to running node process), the next time you cannot connect to the remote machine because the vscode-server are corrupted. You have to wait for the node process to stop after some idle time, then execute the kill command again. This time the vscode-server will be cleaned up.

**Comment by roblourens** [comment]
I don't see a problem with this

![image](https://user-images.githubusercontent.com/323878/101260392-603d3700-36e4-11eb-8f54-9582a22d9cc5.png)

What's wrong with that syntax?

**Comment by ltvan** [comment]
This is my result:
![image](https://user-images.githubusercontent.com/545025/101301228-bb993180-386a-11eb-94ca-e90ed2c68317.png)

Windows 10 Enterprise 2004
Powershell 5.1.19041.610

**Comment by roblourens** [comment]
Indeed, it seems like it will be interpreted as a regex. I guess I don't know why it works for me, but `\\` also works and seems more correct
