### ISSUE TITLE
connect to host fails.  Only log message is Picking SSH host

### ISSUE THREAD

**Issue by rwagnergit** [microsoft/vscode-remote-release#4136]
Issue Type: <b>Bug</b>

Remote-SSH: Connect to Host...

Picking SSH host appears in log.

Extension version: 0.56.0
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:16:10.374Z)
OS version: Linux x64 4.4.0-193-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 3148)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.56GB (0.83GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 02c99eea-3e5f-4800-9c9e-81c0cac6eca9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by roblourens** [comment]
Please tell me exactly what you are doing and what goes wrong

**Comment by rwagnergit** [comment]
Just following the instructions at https://code.visualstudio.com/docs/remote/ssh.

Under "Connect to a remote host," step 2.

In VS Code, select Remote-SSH: Connect to Host... from the Command Palette (F1) and use the same user@hostname as in step 1.

When I select "Remote-SSH: Connect to Host...," I get Comment 'Remote-SSH: Connect to Host...' resulted in an error.

**Comment by roblourens** [comment]
Can you check the developer tools (Help > Toggle Dev Tools) for any additional error info?

**Comment by rwagnergit** [comment]
Under Console, I see:

notificationsAlerts.ts:40 Command 'Remote-SSH: Connect to Host...' resulted in an error (An unknown error occurred. Please consult the log for more details.)
onDidChangeNotification @ breadcrumbsModel.ts:39
(anonymous) @ breadcrumbsModel.ts:39
fire @ event.ts:584
addNotification @ notifications.ts:204
error @ breakpointWidget.ts:390
accept @ commandsQuickAccess.ts:126
async function (async)
accept @ commandsQuickAccess.ts:126
(anonymous) @ pickerQuickAccess.ts:186
fire @ event.ts:584
(anonymous) @ quickInput.ts:773
fire @ event.ts:584
(anonymous) @ linkedList.ts:127
fire @ event.ts:584
(anonymous) @ linkedList.ts:127
(anonymous) @ event.ts:753
fire @ event.ts:584
_set @ listWidget.ts:127
set @ listWidget.ts:127
setSelection @ listWidget.ts:1335
onViewPointer @ listWidget.ts:638
(anonymous) @ event.ts:139
fire @ event.ts:584
(anonymous) @ linkedList.ts:127
fire @ event.ts:584
o @ browser.ts:96

**Comment by roblourens** [comment]
Hm, I was hoping for the real error message, can you try sharing the log from the Remote-SSH channel in the Ouput vie?

**Comment by rwagnergit** [comment]
Well, get this.  VScode just crashed, and after it restarted, connect to host works.  Guess we can close this out.
