### ISSUE TITLE
Error in Remote-Containers: Open Folder in Container

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#4137]
Run `Remote-Containers: Open Folder in Container` and select a folder that doesn't have a devcontainer.json

Get the error:
Command 'Remote-Containers: Open Folder in Container...' resulted in an error (Cannot read property 'forceNewWindow' of null)

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/111898
