### ISSUE TITLE
Could not load gcloud config with Cloud Code

### ISSUE THREAD

**Issue by nampdn** [microsoft/vscode-remote-release#4144]
Issue Type: <b>Bug</b>

The extension could not understand gcloud credentials save in /tmp instead of ~/.config/gcloud. This make Cloud Code extensions not able to read the Google SDK login state

Extension version: 0.56.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.2.0
Remote OS version: Linux x64 5.4.49+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id 935bdf3a-e98f-4763-96ef-55f54d23bf98|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: cloud-shell|
|OS|Linux x64 5.4.49+|
|CPUs|AMD EPYC 7B12 (4 x 2250)|
|Memory (System)|15.64GB (13.38GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Please give more details
