### ISSUE TITLE
vsch.local.folder is not a unique way to retrieve the correct container to attach to

### ISSUE THREAD

**Issue by diricxbart** [microsoft/vscode-remote-release#4149]
- VSCode Version: 1.51.1
- Local OS Version: Windows 10
- Remote OS Version: Debian
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Define a .devcontainer.json file to connect to a remote Docker container
2. Save this .devcontainer.json file to a specific path (e.g. `d:\my_dev_container_folder\.devcontainer\devcontainer.json`)
3. A second user has the exact same setup, with the devcontainer.json file saved to the exact same folder
4. User 1 launches the remote environment. VSCode will run the following and see that there's no corresponding running container: `Run: docker ps -q -a --filter label=vsch.local.folder=d:\my_dev_container_folder --filter label=vsch.quality=stable`
5. User 2 now also launches the remote environment. VSCode will run the exact same docker ps filter and see that there is already a matching container running. Now VSCode will connect to this container WHICH IS FROM ANOTHER USER (resulting in all kinds of issues...)

Suspected root cause:
The filter `label=vsch.local.folder=<path_to_.devcontainer_folder>` is not a unique method of checking if we can connect to a running container or if we should start-up a new container.

Does this issue occur when you try this locally?: Not applicable
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by elazar-rsipvision** [comment]
Just figure it out myself after few a hours of investigation...
It should be documented somewhere, at least, I think.
<br></br>
Tags for future users having this issue (hopefully it'll help someone): 
container stops after other user connecting to another container on the same host
connecting to remote ssh container closes other container
my container is crushing when someone else opening his own container even with different name

**Comment by chrmarti** [comment]
Merging with https://github.com/microsoft/vscode-remote-release/issues/2677.
