### ISSUE TITLE
"Save Workspace" is missing option to save locally

### ISSUE THREAD

**Issue by jrseliga** [microsoft/vscode-remote-release#4151]
- VSCode Version: 1.51.1
- Local OS Version: Ubuntu 19.10
- Remote OS Version: N/A
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open a folder in the remote server
2. `Ctrl+P`
3. `Workspaces: Save Workspace As...` 
4. Integrated directory palette pops up, missing **Show Local** button next to **Ok** button.
![Screenshot from 2020-12-07 19-04-07](https://user-images.githubusercontent.com/3277067/101419905-080e5c80-38bf-11eb-8bad-8adc82b5b7f4.png)

> Note the **Open Folder** integrated directory palette does correctly show the **Show Local** button when connected to a remote host.
> ![Screenshot from 2020-12-07 19-03-40](https://user-images.githubusercontent.com/3277067/101419909-093f8980-38bf-11eb-98c0-9e09a3cedf3a.png)

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
We don't support saving a remote workspace file locally. @bpasero is there an open feature request for this?

**Comment by bpasero** [comment]
@aeschli fixed this for December release in https://github.com/microsoft/vscode/issues/109713

**Comment by aeschli** [comment]
It in 1.52, coming out these days.
