### ISSUE TITLE
Reopen in container: Docker returned an error make sure the docker daemon is running 

### ISSUE THREAD

**Issue by ioanna-tsak** [microsoft/vscode-remote-release#4152]
I want to open a project that I have been working before on, in VScode with a remote container. So I try to "reopen in container".
### Result
```Docker returned an error. Make sure the docker daemon is running```
    and in the terminal log I get this message:
```spawn C:\Users\...\AppData\Local\Programs\Microsoft VS Code\docker ENOENT```

> Note that: 
> I have checked the [issue microsoft/vscode#384 ](https://github.com/microsoft/vscode-remote-release/issues/384)but the solution does not seem to apply

### Information
-  Windows Version: 10
-  VScode version: 1.51.1
-  Remote WSL extension: updated

**Comment by chrmarti** [comment]
For some reason `docker` is not on the PATH. Does `docker` work from Powershell? If so, could you try starting VS Code from Powershell and check if it works?

**Comment by ioanna-tsak** [comment]
I am not able to use the cli commands of docker. When I run any docker-related command in command prompt I get this:
`The system cannot execute the specified program`, even though the docker path (`C:\Program Files\Docker\Docker\resources\bin`) is included in the systems' variables path.

**Comment by chrmarti** [comment]
Is the executable still at that path? Maybe your Docker install got corrupted.

**Comment by ioanna-tsak** [comment]
No, it's not there. What I have tried:

1.  **Add docker path to system paths manually**
    -  I added `C:\Program Files\Docker\Docker` to the system paths (not sure if this is the correct path or if I should go in a subfolder)

2. **Uninstall and re-install docker**
     - After re-installing docker the following paths are included in the system paths:
        - `C:\Program Files\Docker\Docker\resources\bin`
        - `C:\ProgramData\DockerDesktop\version-bin`    
-  Result is the same after both attempts: 
        - not able to use docker cli commands
        - not able to open the project in container in VScode

**Comment by chrmarti** [comment]
This is an issue with your Docker install then. I assume you have tried restarting the machine to make sure all changes to the system by Docker Desktop's install are applied?

Closing as upstream. Thanks.
