### ISSUE TITLE
Resolver error: TypeError: t.filter is not a function

### ISSUE THREAD

**Issue by Thomvanoort96** [microsoft/vscode-remote-release#4153]
I'm using the latest version of this plugin, but it happens with earlier versions as well. When I try to connect with ssh, I get this error: 

[10:40:28.205] Resolver error: TypeError: t.filter is not a function
	at /Users/thomvanoort/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:218:2762476
	at Array.forEach (<anonymous>)
	at l.openFolders (/Users/thomvanoort/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:218:2762423)
	at addFolders (/Users/thomvanoort/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:218:2761680)
	at /Users/thomvanoort/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:144264

Any idea of how to fix this? Thanks

**Comment by connor4312** [comment]
ping @roblourens for steps

**Comment by rzhao271** [comment]
@Thomvanoort96 does this issue still occur for you with the latest version of the extension?

**Comment by roblourens** [comment]
No repro steps but the fix was simple. Please let me know if it worked @Thomvanoort96

**Comment by Thomvanoort96** [comment]
@roblourens Haven't had the time to test it fully but it seems to be working without any issue! Thanks so much for helping & fixing it!
