### ISSUE TITLE
Support SSH connection with password entry

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#4154]
Feature request to track support for SSH connections requiring password entry.

**Comment by vmiheer** [comment]
Will https://github.com/microsoft/vscode/issues/105858 be covered in this issue? There seem to be discussion in issue: https://github.com/microsoft/vscode/issues/88309 about universally storing authentications.

**Comment by chrmarti** [comment]
This issue is more limited in scope. Currently there is no way to enter a password. This issue is about allowing that.
