### ISSUE TITLE
Usually have to reload twice when connecting through Remote-SSH

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#4155]
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (3 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

- Remote OS: Debian
- Remote Extension/Connection Type: SSH

Steps / Behavior:

Reporting an issue from @dmurph (who'd have further context)

He usually has to reload twice when connecting through Remote-SSH. 

When he starts work for the day, he's prompted to reload (I believe as a connection in his SSH config needs to recertify): 

![image](https://user-images.githubusercontent.com/25310137/101532154-fa051e00-3948-11eb-8751-252539cf8db8.png)

He'll select “Reload Window” in the notification. Then although he'll be connected to his SSH box upon reload, he'll be notified again to reload, so he'll select “Cancel” the second time.

He usually has two panes of editors open at all times, which he thinks could cause this?

**Comment by roblourens** [comment]
I don't think there is any reason why this would happen exactly twice. This means that the connection disconnected and timed out (doesn't seem likely here) or the extension host process crashed.

If you run "Set Log Level > Trace", try this, and share the log from dev tools (Help > Toggle dev tools) it might reveal something interesting

**Comment by dmurph** [comment]
Connection probably disconnected, as the ssh connections are closed after a certain amount of time with our current authentication process (usually during the night).

**Comment by roblourens** [comment]
Oh, so you just get that dialog twice in a row in the same window, right? This is probably https://github.com/microsoft/vscode-remote-release/issues/1485
