### ISSUE TITLE
X-forwarding causing Resolver Error: t.filter is not a function

### ISSUE THREAD

**Issue by devincody** [microsoft/vscode-remote-release#4156]
I'm seeing the same issue as the one reference below. Fixed when I removed x-forwarding from my .ssh/config file.

Yes, that nightly extension is what I meant. Great, I'm not sure why it was fixed but please let me know if it comes up again. Will release that nightly to stable soon.

_Originally posted by @roblourens in https://github.com/microsoft/vscode-remote-release/issues/3226#issuecomment-650819766_

Edit: VsCode version: 1.51.1 MacOs

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/4153
