### ISSUE TITLE
No syntax highlighting, intellisense/ language features for JS files

### ISSUE THREAD

**Issue by otaconjh** [microsoft/vscode-remote-release#4159]
- VSCode Version: 1.51.1
- Local OS Version: Win 10.0.19042
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Run `code .` to install vscode-server from WSL
2. Open a .js file and a .ts file:
![image](https://user-images.githubusercontent.com/41576511/101632355-b203fb00-3a1d-11eb-8dcb-4c0f71927569.png)
![image](https://user-images.githubusercontent.com/41576511/101632377-bb8d6300-3a1d-11eb-8d9d-adc513a299b3.png)

3. Check installed extensions -> JavaScript Language Basics is not installed in WSL and there is no option to do so:
![image](https://user-images.githubusercontent.com/41576511/101632457-d8299b00-3a1d-11eb-81dd-45588f1cbb4a.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by bamurtaugh** [comment]
Hey @otaconjh, thanks for reporting. 

I just tried out JavaScript and TypeScript with Remote-WSL in the latest VS Code Insiders and Ubuntu 18.04.5 LTS, and I'm seeing syntax highlighting and other language features:

![image](https://user-images.githubusercontent.com/25310137/107590939-580ae780-6bbe-11eb-8e0b-ecbcebc3dad5.png)

Are you still experiencing this?

**Comment by otaconjh** [comment]
Hi @bamurtaugh , no I'm no longer experiencing this. JavaScript Language Basics has been installed on WSL, not sure when that happened. 
Thanks!
