### ISSUE TITLE
edits in splits not synchronized

### ISSUE THREAD

**Issue by djobet** [microsoft/vscode-remote-release#4160]
- VSCode Version: 1.15.1
- Local OS Version: Ubuntu 18.04.4 LTS
- Remote OS Version: Ubuntu 16.04.6 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. open a file in vscode remote in 1st split
2. open the same file in vscode remote in a 2nd split
3. make a change in 1st split, it does not show up in 2nd split

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
Are you sure it's the same file? Can you share a screenshot?

Can you double check the vscode version?

**Comment by djobet** [comment]
ah sorry, made a typo : vscode 1.51.1

**Comment by djobet** [comment]
Just made a test with an empty file and it worked.
So I suspected it was because the file was big (not really believing that), and it worked too.
Then I noticed I had the same file opened twice with different paths : one is an absolute path, the other one is relative to the root of my source directory. I have absolutely no idea how I ended up with such a relative path.
In that context, making a change in split1 with the absolute file path did not change split2 with relative file path.

**Comment by roblourens** [comment]
Ok, I think that issue will be fixed in Insiders and the next stable release, out in a few hours hopefully, you can try and confirm

**Comment by djobet** [comment]
I just had a try in 1.52.0, it is still broken for me.

**Comment by roblourens** [comment]
Can you 

- Open ctrl+P
- Click the "x" next to some files to clear them from the list, in case you saved some bad history from the bug
- Search for one of those files in ctrl+P, open it
- See if the bug happens again

If you want to clear all editor history you can run the "Clear Editor History" command

**Comment by djobet** [comment]
- I started with no files opened.
- I opened one file
- split the editor
- no problem on this setup

I then started to ctrl-click and sure enough, files started to show up duplicated in ctrl-P. As usual, the "recently opened" one showed up as relative to my project directory while I was also seeing the match from the absolute path name.
The one not marked as "recently opened" show up with absolute path name.

So while I agree that if I carefully never choose to open a relative path it works as intended, but I know this is not sustainable in the long term : at one point I will open a file in a hurry and have my 2 splits de-synchronized and will have to merge the file.

**Comment by roblourens** [comment]
Ctrl+click on what? And in which language?

**Comment by djobet** [comment]
I'm coding in c++.
following symbols like method name or class name using ctrl-click leads to file opened twice in my editor  and in ctrl-P.

**Comment by roblourens** [comment]
Could you file an issue on the C++ extension you are using for them to investigate? I am guessing that there is some minor difference in the path between these two files, maybe a difference in case, although that should be ignored. That would explain why it shows an absolute path, because we think it doesn't go under your open folder.

**Comment by djobet** [comment]
done here https://github.com/clangd/vscode-clangd/issues/121
