### ISSUE TITLE
Docker returned an Error. Make Sure the Docker demon is running

### ISSUE THREAD

**Issue by kshamaramesh** [microsoft/vscode-remote-release#4161]
I am finding the above issue even after re-installing the VS code many times and Not able to figure out what could be the issue

- VSCode Version:1.51.1

- Local OS Version: Ubuntu 18.04
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH/Docker/

Steps to Reproduce:

1.I tried my SSH tunneling

Tried with all the possible ways but could not figure this out.

Hoping for the solutions. Thanks inadvance

**Comment by chrmarti** [comment]
Could you append the log from when this happens? (`F1` > `Remote-Containers: Show Log`)

**Comment by kshamaramesh** [comment]
Hello please find the attachment of the logfile below

> abstractExtensionService.ts:840 Extension 'ms-toolsai.jupyter cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ abstractExtensionService.ts:840
console.ts:137 [Extension Host] (node:4766) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:140
abstractExtensionService.ts:840 Extension 'ms-toolsai.jupyter cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ abstractExtensionService.ts:840
console.ts:137 [Extension Host] Error: spawn docker ENOENT	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)	at onErrorNT (internal/child_process.js:456:16)	at processTicksAndRejections (internal/process/task_queues.js:81:21)
t.log @ console.ts:140
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: spawn docker ENOENT
t.log @ console.ts:140
console.ts:137 [Extension Host] stack trace: Error: spawn docker ENOENT	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)	at onErrorNT (internal/child_process.js:456:16)	at processTicksAndRejections (internal/process/task_queues.js:81:21)
t.log @ console.ts:140
log.ts:197   ERR spawn docker ENOENT: Error: spawn docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by chrmarti** [comment]
`docker` is not on the PATH. Does it work when you start VS Code from the console?

**Comment by kshamaramesh** [comment]
Yes VS code would work from console

**Comment by chrmarti** [comment]
Does Remote-Containers work when you start VS Code from the terminal?

**Comment by kshamaramesh** [comment]
No It won't I would get the same error

**Comment by chrmarti** [comment]
Is `docker` on the PATH in the terminal?

**Comment by kshamaramesh** [comment]
The docker path **Docker Root Dir: /var/lib/docker**

No I am accessing Docker in the server it is not the terminal

**Comment by chrmarti** [comment]
Can you run the `docker` command from the terminal?

Also please append the log from when this happens. Use `F1` > `Remote-Containers: Show Log` to show the log. (You previously posted the console log which is not the same.)

**Comment by kshamaramesh** [comment]
I am running the docker from the server(Remotely) where the path is **Docker Root Dir: /var/lib/docker**

Locally also the docker is been installed the Docker path is **/var/snap/docker/common/var-lib-docker**

> 

[22 ms] Remote-Containers 0.148.1 in VS Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f).
[10115 ms] Start: Run: docker version --format {{.Server.Version}}

**Comment by chrmarti** [comment]
Make sure you update to the latest version of VS Code and Remote-Containers. If `docker` is not on the PATH locally, you can add it with the setting:
![image](https://user-images.githubusercontent.com/9205389/102060339-5907de80-3df2-11eb-97b3-979225f53b4b.png)

**Comment by kshamaramesh** [comment]
Hello,

I have updated the version . 

In the setting the executable name is set. But still facing the same issue.
![Screenshot from 2020-12-14 12-02-26](https://user-images.githubusercontent.com/41081955/102074777-9033bb00-3e05-11eb-96f6-3b80f6eb8e9d.png)

**Comment by chrmarti** [comment]
Try setting it to the full path.

**Comment by kshamaramesh** [comment]
Hello,

Tried with setting the  full path but getting the same error.
![Screenshot from 2020-12-14 14-18-37](https://user-images.githubusercontent.com/41081955/102085695-46ec6700-3e17-11eb-8e2b-6989d88c76f4.png)

**Comment by kshamaramesh** [comment]
Hello ,

I have also made the changes in the **settings.json** file but could resolve the issue.
![Screenshot from 2020-12-14 14-57-33](https://user-images.githubusercontent.com/41081955/102089672-d5afb280-3e1c-11eb-8f73-5ad0f296093b.png)

**Comment by PavelSosin-320** [comment]
docker version command returns both docker CLI and docker engine version. This is not a "local" command. The error message  "check for docker is running..." means that Docker CLI can't connect to the server. If Docker CLI docker version invoked from the command line returns only the CLI version but not a server and API version your server engine doesn't run or inaccessible from the client. The Docker CLI is installed in /usr/bin in Linux by the default and in C:\Program Files\Docker\Docker\resources in Windows by Docker Desktop.
/var/lib/docker is only the Docker daemon tree and nothing more if not redefined.
The default local docker socket docker.sock in Linux is located in /var/run - please, check that it exists and opened.
Usage of DOCKER_HOST maybe not supported anymore. please, use docker context.
Please, check docker context ls.

**Comment by PavelSosin-320** [comment]
@kshamaramesh  You can always check presens and full path of the command's executable 
In Linux: which docker -> returns full path to the docker CLI.
In Windows where docker -> returns full path to docker CLI.
If it returns path no additional configuration should be required.

**Comment by chrmarti** [comment]
@kshamaramesh What do you get for `which docker` in a standalone terminal where the Docker CLI works?
