### ISSUE TITLE
ipython doesn't display results

### ISSUE THREAD

**Issue by mosqueteiro** [microsoft/vscode-remote-release#4162]
When using Remote - SSH to connect with a cloud compute instance, I start an ipython session and when results should be displayed they don't show up until another line has been entered/executed. Then the previous results are displayed but now the newest results from the most recent entered/executed line are not displayed.

---

CPUs | Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)
-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 1, 2, 2
Memory (System) | 16.00GB (0.08GB free)
Process Argv | -psn_0_98328 --crash-reporter-id 8f45855f-e228-48ed-bc44-622d14c38b32
Screen Reader | no
VM | 0%

---

Remote | SSH: datadev-3
-- | --
OS | Linux x64 5.4.0-1028-gcp
CPUs | Intel(R) Xeon(R) CPU @ 2.30GHz (2 x 2300)
Memory (System) | 7.28GB (4.75GB free)
VM | 0%

**Comment by roblourens** [comment]
Is this in a terminal? Can you explain a little more? Maybe a screenshot/gif would help
