### ISSUE TITLE
Remote Explorer - Target open/remove icons require horizontal scrolling

### ISSUE THREAD

**Issue by plwalsh** [microsoft/vscode-remote-release#4163]
When viewing the *Remote Explorer* sidebar, my list of SSH Targets is shown with the long path to each workspace folder overflowing the width of the panel. This results in a horizontal scrollbar appearing to view the full paths, which is fine, except for access to the open/remove icons. The icons to quickly open or remove the target with a single click appear all the way at the end of each line, at a width as wide as the longest folder path. Having to horizontally scroll the sidebar all the way to the right, or even expand the whole thing, defeats the purpose of the quick-action icons. It would be great if the icons could appear along the sidebar's right-hand border when hovering over a particular target/folder.

---

- VSCode Version: 1.52.0-insider (c6cb541)
- Local OS Version: Windows_NT x64 10.0.16299
- Remote OS Version: RHEL/Ubuntu
- Remote Extension/Connection Type: SSH

**Comment by roblourens** [comment]
Sounds like you have set `"workbench.list.horizontalScrolling": true`, is that right? If you disable that then you get the behavior you expect

**Comment by plwalsh** [comment]
Good call &ndash; thanks for pointing that out. I don't even recall enabling that setting, but I must've done it a long time ago.

I guess there's no way to have the best of both worlds? I like the horizontal scrolling for use in the *File Explorer* tree, where nested folders cause the filenames (primary info) to creep their way further and further to the right, and having to pause my mouse over a file to wait for the tooltip to pop up and show me the rest of the filename isn't as fluid as just grabbing the scrollbar and scrolling right. But in the case of the *Remote Explorer*, the primary info (target name) is always only indented one level underneath the hostname, while the secondary info (folder path) is what causes the icons to be pushed out of view. In that case, I more often than not, don't need to see the secondary info. And not to mention, the tooltips on the *Remote Explorer* view are fancier and not as much of an eyesore as the ones on the *File Explorer* view lol.

I'm not much of a layout dev, so I'm sure it's a difficult ask to achieve both goals at the same time. Just figured I'd check. Thanks!

**Comment by roblourens** [comment]
Yes, when horizontal scrolling is enabled, the buttons go to the end, no way to get both. You can right click to get the same actions, if that helps.
