### ISSUE TITLE
Make Remote Explorer "Help & Feedback" state remembered across workspaces

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode-remote-release#4165]
- VSCode Version: **1.51.1 (system setup)**
- Local OS Version: **Windows 10 Home 20H2**
- Remote OS Version: **Ubuntu 20.04**
- Remote Extension/Connection Type: **WSL**

## Issue description:
Sorry to have to change your issue template, but the problem is too complicated to be displayed in two steps.
**Below is a detailed description of the problem as a comparison**

## How it works in VSCode:
1. VSCode in native design has bars , eg.:
![obraz](https://user-images.githubusercontent.com/30685349/101737296-f5fe0b00-3ac4-11eb-97d0-83099d810709.png)
![obraz](https://user-images.githubusercontent.com/30685349/101737311-fbf3ec00-3ac4-11eb-80b5-b3753343cff5.png)

2. If we disable all those bars that can be disabled, the last bar disappears and its name moves to the title at the top.
Let's take for example in `EXTENSIONS`:
 
**BARS ENABLED**:
![obraz](https://user-images.githubusercontent.com/30685349/101737932-cb608200-3ac5-11eb-8e51-97dd3d245fae.png)
 
**LAST BAR DISABLED**:
`As you can see, the bars are gone and the name of the last bar has been moved to the title at the top:`
![obraz](https://user-images.githubusercontent.com/30685349/101738180-0e225a00-3ac6-11eb-88c1-d20ea1557036.png)

3. If we reload VSCode, the state of the bars will be remembered.

## How it works in your Remote - WSL extension:

1. If we disable the last bar that can be disabled (in this case, it's Help and Feedback), the last bar still exists.
 
**Help and Feedback ENABLED:**
![obraz](https://user-images.githubusercontent.com/30685349/101739220-85a4b900-3ac7-11eb-88e2-46f27878f6e5.png)
 
**Help and Feedback DISABLED:**
![obraz](https://user-images.githubusercontent.com/30685349/101739269-935a3e80-3ac7-11eb-9592-b4307f9f163c.png)

2. if we are to be **consistent with the general principles of VSCode** operation, it should look like this: _(and the last bar should disappear)_
![obraz](https://user-images.githubusercontent.com/30685349/101739729-3ca13480-3ac8-11eb-8ab3-95ef659f5960.png)

3. The last problem is that if you reload VSCode, the status of the bars will **NOT be remembered**. In fact, this state is not remembered if we are on the local computer only (on remote connection works fine), but if we are to be consistent it should work the same everywhere

---

Does this issue occur when you try this locally?: **Yes**
Does this issue occur when you try this locally and all extensions are disabled?: **Yes**

**Comment by alexr00** [comment]
When you have multiple Remote extensions installed the Remote Explorer sidebar is driven by a dropdown at the top. Because of this, we do not collapse the last view header to the top when there is only one view left, as that conflicts with the drop down. 

I do not see the disabled state of Help and Feedback not get respected after reload. Are you perhaps changing folders? The disabled state is per workspace.

**Comment by kanlukasz** [comment]
> The disabled state is per workspace.

Exactly. The state is remembered for each workspace, so every time we start a new empty VSCode instance, the state goes back to the default. It would be useful if it could also remember the default state.

From what I can see, this is how native bars such as `OPEN EDITORS` work. If you hide the "OPEN EDITORS" bar, it will be hidden for each new empty instance. Of course, each workspace can define this according to individual settings.

**Comment by alexr00** [comment]
@sbatten is there nice way I can make a core view's enablement state be global?

**Comment by sbatten** [comment]
The view descriptor is set to use workspace state here and can be changed.

https://github.com/microsoft/vscode/blob/15f38fe338a791de62b1c448f0035b199ba27a04/src/vs/workbench/contrib/remote/browser/remote.ts#L460
