### ISSUE TITLE
SSH Remote 0.62.0 not compatible with VScode 1.51.1

### ISSUE THREAD

**Issue by deedeeck** [microsoft/vscode-remote-release#4169]
- VSCode Version: 1.51.1
- Local OS Version: Windows 10
- Remote OS Version: N.A
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install VScode 1.51.1
2. Download ms-vscode-remote.remote-ssh-0.62.0.vsix from https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh&ssr=false#overview
3. Start VScode and install extension from vsix file

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Yes, it uses new features. 1.52 coming soon.

**Comment by deedeeck** [comment]
so how can this be resolved? should I wait till VSCode 1.52 is released before this can be used?

**Comment by roblourens** [comment]
If you install the extension through the marketplace, it will give you the latest compatible version
