### ISSUE TITLE
Remote SSH window locks up when opening a large source file

### ISSUE THREAD

**Issue by stephen-waddell-red** [microsoft/vscode-remote-release#417]
- VSCode Version: 1.35.0-insider
- Local OS Version: Windows 10 Pro: 1803 (17134.706)
- Remote OS Version: CentOS Linux release 7.6.1810 (Core)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Set up an SSH session to remote host
2. Try to open a large C++ file (the file in question is ~16,000 lines - smaller files from the same directory open without issue)
3. The whole window completely locks up, then gives the option to Close/Wait/Restart
4. Clicking Wait several times (~5 mins) does not recover
5. Reproducible every time

Initially installed remote versions of GitLens and the MS C++ extension - same behaviour if these are removed.  They are both installed locally.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

None of the easily available logs show any errors - I can run again with more debug enabled if someone tells me how!

**Comment by stephen-waddell-red** [comment]
After further investigation, it doesn't seem to be the size of the file.  Other similarly sized files display OK, but I have found other (much smaller) files that consistently freeze the UI.

The only message in the main log is the following:

`[2019-05-22 16:36:37.938] [main] [error] [VS Code]: detected unresponsive`

**Comment by cs96and** [comment]
I'm having the same problem with WSL.  Opening `<future>`  (aka /usr/include/c++/8/future) will consistenly lock up the vscode window.

**Comment by stephen-waddell-red** [comment]
Magic pixies seem to have fixed this for me overnight.  I assume it was spinning somewhere but none of the logs gave any clues.  If it happens again, are there any debug logs that would be helpful?  The DevTools Console didn't give any clues either

**Comment by egamma** [comment]
@cs96and what happens when you open the same file when you run VS Code locally?

**Comment by cs96and** [comment]
This also seems fixed to me.  I noticed that Code Insiders installed an update for both itself, and the WSL plugin.  I assume something was fixed.
