### ISSUE TITLE
Cannot see "Remote-Containers: Try a Sample..."

### ISSUE THREAD

**Issue by MarkMindlin** [microsoft/vscode-remote-release#4173]
Issue Type: <b>Bug</b>

Cannot see "Remote-Containers: Try a Sample..."

Extension version: 0.148.1
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.23GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/mmindlin/code/validation --remote=wsl+Ubuntu-20.04 --crash-reporter-id 898a912a-40d0-4bbe-94ac-61e1e6fda4b1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|12.39GB (9.01GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Make sure you are not connected to any remote and that you have the Remote-Containers extension installed.

**Comment by MarkMindlin** [comment]
Please elaborate how to check we are not connected to any remote.
We definitely installed the extension.

When typing in command palette we have others command, but not "Try a Sample"

![image](https://user-images.githubusercontent.com/18206302/101884968-918a9b00-3bed-11eb-9fbd-7978f778b4e7.png)

**Comment by chrmarti** [comment]
The lower left corner looks like this when you are not connected:
![image](https://user-images.githubusercontent.com/9205389/101887083-adb21c00-3b9c-11eb-946f-715e76876281.png)

If that has a label, you are connected to some remote. Run the `Remote: Close Remote Connection` command or just open a new empty window.

**Comment by MarkMindlin** [comment]
Great. It did a trick.
I can see "Try a Sample..." now

Thank you

**Comment by chrmarti** [comment]
Thanks, closing the issue then.
