### ISSUE TITLE
Cannot attach VS Code to remote container

### ISSUE THREAD

**Issue by mrmachine** [microsoft/vscode-remote-release#4174]
- VSCode Version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
- Local OS Version: Darwin x64 20.1.0
- Remote OS Version: Linux x64 4.4.0-1110-aws
- Remote Extension/Connection Type: SSH/Docker/WSL

Expected result: Able to `Attach Visual Studio Code` to container on remote host via SSH.

Actual result: Can only `Attach Visual Studio Code` to containers running on my LOCAL machine, even while connected to the remote host via SSH and able to `Attach Shell` to remote containers.

Steps to reproduce:

- `CMD-SHIFT-P` > `Remove-SSH: Connect to host...`
- `ubuntu@mydomain.com` (an Ubuntu LTS EC2 with Docker Engine installed)
- `CMD-SHIFT-X` > search for and install `Docker` extension on the remote host
- Navigate to Docker sidebar
- Right click container and `Attach Shell` -- successful
- Right click container and `Attach Visual Studio Code` -- brings up a list of containers on my LOCAL machine

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.34GB free)|
|Process Argv|--crash-reporter-id 30710210-57bb-4fa9-8da6-c4ab3930cb9c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: mydomain.com|
|OS|Linux x64 4.4.0-1110-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz (16 x 2999)|
|Memory (System)|30.64GB (4.10GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Fixed in Insiders (soon to be released as stable). https://github.com/microsoft/vscode-remote-release/issues/4072#issuecomment-733085835

**Comment by mrmachine** [comment]
@chrmarti Are you sure?

I just tested this in Insiders, and it behaves exactly as described above. While connected to a remote host via SSH, right click on a remote container and choose `Attach Visual Studio Code` brings up a list of LOCAL containers on my machine.

Version: 1.52.0-insider
Commit: 24b28f57be22fe3029cb17a1dd72d8d9c2d6468b
Date: 2020-11-06T05:39:23.276Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

**Comment by chrmarti** [comment]
One limitation is that you need to have a folder open. Please retry with that.

**Comment by mrmachine** [comment]
@chrmarti Thanks, that sort of worked. Even though I right clicked on a specific container and chose `Attach Visual Studio Code`, it just brought up the full list of containers in a select list (after about 20-30 seconds) and the one I had right clicked on was not selected. After selecting the container I wanted, it opened a new VS Code window, but then it seems to just get stuck or timeout/disconnect before I can do anything (like open a folder).

**Comment by chrmarti** [comment]
You could try sharing the SSH connection to speed things up (and maybe avoid the timeouts?) like shown here: https://github.com/microsoft/vscode-remote-release/issues/3938

The ignored selection in the Docker viewlet is tracked with microsoft/vscode#111238.

**Comment by mrmachine** [comment]
This seems to be working a lot better with the SSH config you mentioned. 👍
