### ISSUE TITLE
Replace ENV with ARG in documentation

### ISSUE THREAD

**Issue by OnlineCop** [microsoft/vscode-remote-release#4178]
The section that describes how to reduce Dockerfile build warnings uses `ENV`:

https://code.visualstudio.com/docs/remote/containers-advanced#_debconf-delaying-package-configuration-since-aptutils-is-not-installed

https://github.com/moby/moby/issues/4032#issuecomment-192327844 suggests that `ARG` be used instead, since that only persists while the Docker image is being created, but has no effect when running the container interactively.

**Comment by chrmarti** [comment]
`ARG` wouldn't be available to the `apt-get` command. We could replace the example with:
```
RUN apt-get update \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends apt-utils dialog 2>&1
```
Which is what we use in our definitions too.

**Comment by bamurtaugh** [comment]
Thanks for opening this @OnlineCop! This has been addressed by https://github.com/microsoft/vscode-docs/pull/4226.
