### ISSUE TITLE
Remote-Wsl can't open a directory that it previously could.

### ISSUE THREAD

**Issue by paolord** [microsoft/vscode-remote-release#4179]
Remote-Wsl can't open a directory that it previously could.

Version: 1.52.0 (user setup)
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:45:11.850Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Opened vscode and it can't read my directory in wsl. It shows the error: Unable to open 'app': Unable to read file 'vscode-remote://wsl+debian/home/user/Projects/myprojectsname/app' (Error: connect ECONNREFUSED ::1:40303).
2. I check the wsl logs and the problems tab doesnt show anything. the terminal tab says: 
[2020-12-11 18:30:04.914] WSL resolver response: ::1:40303
[2020-12-11 18:30:04.915] To debug connection issues, open a local browser on http://[::1]:40303/version
3. I open the remote explorer. All green check marks.
4. I check for open issues on this project. There are similar issues, the first one says to update to 1.52.
5. Clicked Restart to Update.
6. I'm now on 1.52 and its still the same.
7. I also checked if I can open wsl with a terminal. it's running. and I also checked my directory. it's still there.
8. Yes. It was already set up before, I used it 5 days a week without a problem until now.

**Comment by brennaman** [comment]
I may have the same issue.  It just started happening today after a VS Code update.

VS Code About Info:
Version: 1.52.0 (user setup)
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:45:11.850Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

When I try to open a wsl directory then I get the following errors:

- Failed to connect to the remote extension host server (Error: connect ECONNREFUSED ::1:42991)

- Could not fetch remote environment

**Comment by byron70** [comment]
Very similar issue this morning with me after updates. I solved this by terminating the WSL distribution and restarting. 

```
> wsl -t Ubuntu-20.04
> wsl -d Ubuntu-20.04
```

**Comment by mgruel** [comment]
I have a similar issue with my connection to the Remote-WSL.
After brief debugging, my issue is tied to the missing / disabled IPv6 support of the WSL.

See https://github.com/microsoft/vscode-remote-release/issues/4018

**Comment by bamurtaugh** [comment]
@paolord @brennaman Thanks for the info - does it sound like the suggestions in either of the above comments could apply to your scenarios?

**Comment by paolord** [comment]
@bamurtaugh  I'm not sure what happened. It started working again after a day.

**Comment by bamurtaugh** [comment]
Thanks for the update @paolord. Going to close out for now since it started working again, but please let us know if this happens again or you run into any other trouble.
