### ISSUE TITLE
VS Code Server needs to support both 'stable' and 'insiders' version of VS Code

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#418]
(text written by @alexandrudima):

Each extension can independently add support for this. To implement, the extensions need to read also the quality from `product.json`, besides the `commit` and use that when downloading `vscode-server` and when installing it. I suggest we adopt the following folders:
- `$HOME/.vscode-server` for stable and
- `$HOME/.vscode-server-insiders` for insiders

IMHO, this would align most closely with what we currently have with VS Code, but it would also mean that current installed extensions would be lost if no special purpose migration code is written by the respective extensions.

Once everything is set up on the extension side, simply launch `vscode-server` and set the environmental variable `VSCODE_AGENT_FOLDER` to point to `$HOME/.vscode-server` or to `$HOME/.vscode-server-insiders`.

- [ ] SSH (must) @roblourens 
- [x] WSL (must) @aeschli 
- [x] docker (optional) @chrmarti

**Comment by alexandrudima** [comment]
fyi @egamma I have updated the description with my proposal.

**Comment by chrmarti** [comment]
Done for containers. It might make sense to have an additional property in the `product.json` for the folder name similar to the existing `"dataFolderName"`.

**Comment by aeschli** [comment]
The latest insider (and stable) server builds have a new property in the `product.json`
"serverDataFolderName": ".vscode-server-insiders"
