### ISSUE TITLE
git user.* attributes are not copied to the dev machine

### ISSUE THREAD

**Issue by valotas** [microsoft/vscode-remote-release#4180]
- VSCode Version: `1.52.0`
- Local OS Version: `Linux NAME 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Remote OS Version: `Linux 47660e0504ce 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 GNU/Linux`
- Remote Extension/Connection Type: `Docker`

Steps to Reproduce:

1. Start a [python workspace](https://github.com/microsoft/vscode-remote-try-python) in a container
2. git config --list | grep user

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

## Insiders version

I couldn't check as for some reason it could not start the container with the insider's version

## Dev Image Dockerfile

```
# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.134.0/containers/python-3/.devcontainer/base.Dockerfile
ARG VARIANT="3"
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}

RUN apt-get update && \
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git-lfs && \
    git lfs install && \
    rm -r /var/lib/apt/lists/*
```

**Comment by chrmarti** [comment]
Does `git lfs install` in your Dockerfile create a `~/.gitconfig` file? We don't overwrite any existing file.

**Comment by valotas** [comment]
My `.gitconfig` looks like

```
[filter "lfs"]
        clean = git-lfs clean -- %f
        smudge = git-lfs smudge -- %f
        process = git-lfs filter-process
        required = true
[credential]
        helper = "!f() { /root/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/node /tmp/vscode-remote-containers-725e6ffc6fe5d27e21816db552229077c1ba3258.js $*; }; f"
```

So I guess that it does create the `[filter "lfs"]` part. Can I do something to fix this?

**Comment by chrmarti** [comment]
You could configure a dotfiles repository in your user settings and let that set the config values. There is also `postCreateCommand` in the devcontainer.json, but that applies to all users (which is ok if you are the only developer on the project of course).

**Comment by valotas** [comment]
Thanks a lot @chrmarti . I am closing this since I do not believe that supporting merging .gitconfig files is something worth looking at at the moment
