### ISSUE TITLE
Remote SSH appears to ignore agent forwarding option

### ISSUE THREAD

**Issue by jeffomatic** [microsoft/vscode-remote-release#4183]
### Summary

I'm using Remote SSH to connect from macOS to an EC2 Ubuntu server. Remote file editing works just fine, but SSH agent forwarding does not appear to work regardless of the value of the `remote.SSH.enableAgentForwarding` option, in either the local or default settings.

I've verified that SSH agent forwarding works if I use `ssh -A` in either iTerm2 or in a VSCode terminal, so this appears to be an issue with the Remote SSH extension specifically, or the SSH libraries it interacts with.

### Setup

Locally, I'm running macOS 10.15.7 (Catalina), using the system `ssh` (`OpenSSH_8.1p1, LibreSSL 2.7.3`).

"About VSCode" displays the following:

- Version: 1.52.0
- Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
- Date: 2020-12-10T22:46:53.673Z (2 days ago)
- Electron: 9.3.5
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Darwin x64 19.6.0

I'm using the "Remote - SSH" extension at version 0.62.0.

I don't believe this is relevant, but the remote host is Ubuntu 20.04. I can dig up more details if necessary.

### Steps to Reproduce

1. Add SSH keys to local agent using `ssh-add`.
2. Via the VSCode terminal, verify that `ssh-add -l` displays the added keys.
3. Verify that the VSCode "Remote.SSH: Enable Agent Forwarding" option is checked. Optionally, explicitly add `remote.ssh.enableAgentForwarding: true` in JSON settings (it will not be present initially, since the default is `true`).
4. Use Remote SSH to connect to the remote host, and verify that remote file interaction works.
5. Via the VSCode terminal (with remote shell session), type `env` and observe that `SSH_AUTH_SOCK` is not present.
6. Via the VSCode terminal, use an SSH-dependent action (e.g., `git clone`) to confirm that agent forwarding is not working.
7. In a separate VSCode window, use `ssh -A` to access the same remote host. Observe that SSH agent forwarding works; i.e., `SSH_AUTH_SOCK` is defined and git commands work as expected.

### Logs

Here's the Remote SSH log at "trace" level: https://gist.github.com/jeffomatic/c56caadb98b3fe96cf9d4aee692d27b1

Some interesting things about the log:

- The extension interacts fine with the local SSH agent, discovering any keys that I've added locally.
- The log shows a list of `remote.SSH` options, but `enableAgentForwarding` does not appear to be present.
- The remote server appears to emit some settings from the remote server's point of view, including what seems to be an empty SSH auth sock, i.e. `sshAuthSock====`.

**Comment by jeffomatic** [comment]
I discovered a workaround for this issue, which is to add `ForwardAgent yes` to the SSH config file. In my case, that's `~/.ssh/config`. Here's an example:

```
Host some-alias
  HostName redacted.us-west-1.compute.amazonaws.com
  User ubuntu
  ForwardAgent yes
```

This allows you to enabled agent forwarding without providing the `-A` flag. For my use case, this is a perfectly acceptable way to go, although other users may not want this always-on behavior.

**Comment by roblourens** [comment]
You need `ForwardAgent` enabled in your ssh config. SSH is the thing that does the actual agent forwarding. You don't need to pay attention to that vscode setting, it is true by default. vscode has to do some extra work to make it work with ssh, but the ssh config is what actually makes it work.

**Comment by jeffomatic** [comment]
@roblourens Thanks for responding, I really appreciate it!

Do I understand correctly that the `remote.ssh.enableAgentForwarding` extension setting doesn't currently do anything? I just conducted a couple of experiments.

1. I thought perhaps that the setting would change the way VSCode writes new entries into the SSH config. With `remote.ssh.enableAgentForwarding` enabled, I added a new host via the "Remote SSH: add host" VSCode command, and it resulted in an entry as follows:

    ```
    Host foo
        HostName bar
        User someuser
    ```

    Notably, the `ForwardAgent yes` directive was not added automatically.

2. Then I thought that perhaps the setting can _disable_ agent forwarding by counteracting the `FowardAgent` directive in SSH config. So, I explicitly added the `ForwardAgent yes` directive to SSH config, and explicitly disabled `remote.ssh.enableAgentForwarding` in VSCode config. After initiating a remote SSH session in VSCode, I noticed that agent forwarding was working fine.

I might be missing something, but based on the above, it would seem that the `remote.ssh.enableAgentForwarding` setting has no observable effect on behavior.

> We can't force it to be always on because the user may not want their credentials shared.

Yep, that's very sensible.

> the ssh config is what actually makes it work

[Per the docs](https://code.visualstudio.com/docs/remote/ssh#_forwarding-a-port-creating-ssh-tunnel), it does seem like the Remote SSH extension is capable of ephemeral session features like temporary port forwarding. Would it be possible for the Remote SSH extension to do something similar with agent forwarding? Such a capability is available on commandline via the `-A` flag, and I'm betting the runtime libssh interface provides something equivalent.

**Comment by roblourens** [comment]
> explicitly disabled remote.ssh.enableAgentForwarding in VSCode config. After initiating a remote SSH session in VSCode, I noticed that agent forwarding was working fine.

If I remember correctly, the only difference you will see with this disabled is that if you go through reconnection (like the ssh connection going down due to losing network), then agent forwarding will stop working in any terminals that you had opened before reconnecting.

> Would it be possible for the Remote SSH extension to do something similar with agent forwarding?

I don't understand why you want the extension to do this instead of SSH. For it to work, something has to know the socket path for your local ssh agent, forward this to the remote, and set the right variable in the remote environment for ssh to find it. SSH will be best at this.
