### ISSUE TITLE
Severe performance regression in 1.52 making vscode unusable

### ISSUE THREAD

**Issue by QwertyZW** [microsoft/vscode-remote-release#4186]
- VSCode Version: 1.52
- OS Version: Windows 10

I'm using vscode with the Microsoft C/C++ intellisense + remote development plugins enabled.

Vscode auto upgraded itself to 1.52. When highlighting any variables/headers/etc, it would simply display "Loading..." for minutes on end. Opening a new file takes about a minute or two to load the git gutter change highlighting.

Sshing into the remote server and looking at htop shows vscode at the top using 100% CPU. This never ends.

I rolled back to 1.51.1 and disabled auto updates and everything is back to normal

**Comment by roblourens** [comment]
If you disable the C++ extension, does the git gutter change highlight show up faster?

**Comment by QwertyZW** [comment]
The extension (along With others) also auto updated, but I didn't have to roll it back. I might look into rolling forWard and debugging this if I have time, but no plans for noW.

For the time being I encourage you to be able to try and reproduce this yourself for the sake of the quality of your future releases. There's nothing special about my setup. Pretty sure soon enough more users Will come With the same problem. Just thought I'd report it While it's still fresh, note the problematic version of vscode and provide a remedy to people suffering from the same problem.

**Comment by alexdima** [comment]
@QwertyZW I have tried to connect to a remote (I chose wsl instead of ssh), I have tried to use the C++ extension and I do not see high CPU usage:

![image](https://user-images.githubusercontent.com/5047891/102279082-201f5500-3f2b-11eb-98c8-171022040a28.png)

**Comment by QwertyZW** [comment]
One thing to note is that I'm working on multiple projects, all in the same WS, approximately 60-70k lines of code in total, with 400k-500k+ lines of code worth of dependency headers.

Try setting up the linux kernel (correct) or a large enough C++ project (qt creator might be a better choice). That should be a similar setup to what I have.

**Comment by QwertyZW** [comment]
Not sure what this means "(I chose wsl instead of ssh)" or if it has any thing to do with the problem. I'm using WSL too. I can run ssh directly from windows commandline (only works after setting up WSL), and I run some other authentication program directly from windows cmd line that  generate a local certificate which vscode then uses. (the program binary is for linux, and I originally installed it for WSL)

**Comment by alexdima** [comment]
@QwertyZW Thank you for the extra information. In this case, this appears to be a problem specific to the C++ extension. I have moved your issue over to the C++ extension https://github.com/microsoft/vscode-cpptools/issues/6676

**Comment by alexdima** [comment]
This might be caused by our new automatic port forwarding feature which scans the remote OS for available ports in order to forward them locally (https://github.com/microsoft/vscode/issues/112843)

**Comment by alexr00** [comment]
@QwertyZW  would you be willing to try the following steps? This would help us confirm that we've found the issue, and you'll also get to use a more up-to-date version.

1. On your remote machine, add the following line to your .bashrc file: `export VSCODE_DISABLE_PROC_READING=true`
2. Install [VS Code Insiders](https://code.visualstudio.com/insiders/)
3. Try to repro your original issue with VS Code Insiders. 

Setting that environment variable will cause VS Code (insiders only right now, I'll make a proper fix that doesn't involve an environment variable for the next stable release), to not do the proc filesystem reading that we do to automatically forward ports for you. This does mean that automatic port forwarding will not work while you have that environment variable set.
