### ISSUE TITLE
Regression: VsCode Remote Container no longer works in 1.52

### ISSUE THREAD

**Issue by MikaelUmaN** [microsoft/vscode-remote-release#4189]
- VSCode Version:
- Local OS Version: Windows 10, 19041.685
- Remote OS Version: Ubuntu-20-04
- Remote Extension/Connection Type: Docker

1. Launch VS code as admin
2. Connect to remote container
3. Open folder in remote container

Since upgrading, I get the following error:
```

[2020-12-14T13:12:52.127Z] [PID 29296] [9 ms] Remote-Containers 0.154.0 in VS Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be).
[2020-12-14T13:12:52.140Z] [PID 29296] [22 ms] Start: Resolving Remote
[2020-12-14T13:12:52.141Z] [PID 29296] [23 ms] Setting up container /data

[2020-12-14T13:12:52.142Z] [PID 29296] [24 ms] Start: Run: docker inspect --type container /data
[2020-12-14T13:12:52.671Z] [PID 29296] [552 ms] Error: Can not add index to parent of type array
	at c:\Users\myname\.vscode\extensions\ms-vscode-remote.remote-containers-0.154.0\dist\extension.js:1:383763
	at Module.F (c:\Users\myname\.vscode\extensions\ms-vscode-remote.remote-containers-0.154.0\dist\extension.js:1:384006)
	at c:\Users\myname\.vscode\extensions\ms-vscode-remote.remote-containers-0.154.0\dist\extension.js:1:687975
```

Disclaimer: This is at work where using vscode is always rather cumbersome. I can get this working with no problem on my own private laptop at my own network. But I have been using vscode with remote development successfully at work until now.

Tried reinstalling the extensions.

## Edit: Workaround

This seems to be some sort of cache-bug when upgrading versions.

Confirming that purging `C:/Users/user/AppData/Roaming/Code` worked on Windows.

**Comment by jgubler** [comment]
I'm experiencing the exact same issue after upgrading to vscode version 1.52.0.

**Comment by jmellafe** [comment]
me too, same issue here

**Comment by jgubler** [comment]
I downgraded the remote-containers version to 0.152.1 and 0.151.0, both do not seem to affect/remediate the issue.
I'm guessing this is a vscode main issue.

**Comment by jmellafe** [comment]
Downgrading to remote-containers 0.148.1 and VS Code 1.51.1 does not solve the issue neither

**Comment by jmellafe** [comment]
The error does not reproduce on VS code 1.50.1 and remote-containers 0.145.1

**Comment by jgubler** [comment]
@jmellafe I cannot confirm that, I'm still getting the error in Remote-Containers 0.145.1 in VS Code 1.50.1.
That being said, I simply installed 1.50.1 on top of my existing installation and then rolled back the remote-containers extension via the "Install Another Version" context menu.
Did you perform some additional cleaning in between?

**Comment by jmellafe** [comment]
yes, I totally uninstalled VS Code, removed ~/.vscode and ~/.config/Code folders, and then installed version 1.50.1. Maybe simply deleting those folders fixes it.

**Comment by frobinet** [comment]
I had the same issue. It seems to be related to some cached config somewhere. In my case (running windows), I removed `C:/Users/user/AppData/Roaming/Code`, and restarted everything. Now working with latest version of both VSCode and remote-containers extension.

**Comment by jgubler** [comment]
I'm running it on Windows as well, uninstalling VSCode and purging `<user_home>/.vscode` before reinstalling did not suffice for me, but purging `C:/Users/user/AppData/Roaming/Code` did.
Can confirm that the newest versions of both Remote - Containers and VSCode itself are running again.

**Comment by MikaelUmaN** [comment]
Confirming that `C:/Users/user/AppData/Roaming/Code` purged worked on Windows.

This seems to be a cache bug. Editing the original post and letting the maintainers decide if they want to close this or not.

**Comment by Mattval-mva** [comment]
I am running it on ubuntu and I have the same problem. Someone got it too ?

**Comment by jmellafe** [comment]
> I am running it on ubuntu and I have the same problem. Someone got it too ?

Yes, I got it in ubuntu. My advise is to:

1. delete the caches folders: ~ /.vscode and ~/.config/Code
2. If this do not fix the problem, downgrade to 1.51 or 1.50

**Comment by Mattval-mva** [comment]
I deleted the caches but now I can't open the containers it doesnt respond 

> > I am running it on ubuntu and I have the same problem. Someone got it too ?
> 
> Yes, I got it in ubuntu. My advise is to:
> 
>     1. delete the caches folders: ~ /.vscode and ~/.config/Code
> 
>     2. If this do not fix the problem, downgrade to 1.51 or 1.50

**Comment by chrmarti** [comment]
Likely an issue with the attach config. Check if the JSON of these configs is valid. You can open them using `F1` > `Remote-Containers: Open Attach Container Configuration File...`. (Make sure you are using the latest version 0.154.1 which fixes a bug with the listing of these configs.)

**Comment by LaCandela** [comment]
Confirming that C:/Users/user/AppData/Roaming/Code purged worked on Windows10

**Comment by chrmarti** [comment]
Could everyone seeing this check their attach configurations (`F1` > `Remote-Containers: Open Attach Container Configuration File...`) for errors in the JSON and post the JSON here for investigation?

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/4208 where we have a content sample. Thanks.
