### ISSUE TITLE
cannot read property local of undefined. 

### ISSUE THREAD

**Issue by jbrandli** [microsoft/vscode-remote-release#419]
Issue Type: <b>Bug</b>

Use remote-ssh extension to connect to Centos VM. Attempt to install extension in the remote machine. See two error notifications, "Cannot read property local of undefined" and "Failed to install extension try downloading manually"

The manual install from download fails with the "cannot read property local" error again. 

This happens for all the extensions I've tried.  I've also tried chmod 777 and chown to my user on the ~/.vscode-remote folder 

Extension version: 0.37.0
VS Code version: Code - Insiders 1.35.0-insider (4ca38ce5584d7cd67b435b3c32ef1240c6a29628, 2019-05-21T05:18:31.618Z)
OS version: Windows_NT x64 10.0.16299
Remote OS version: Linux x64 3.10.0-957.10.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 172.20.48.5|
|OS|Linux x64 3.10.0-957.10.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4116 CPU @ 2.10GHz (4 x 2100)|
|Memory (System)|15.51GB (10.19GB free)|
|VM|100%|
</details>

**Comment by sandy081** [comment]
@jbrandli How are you installing the extension and what extension you are installing?
