### ISSUE TITLE
remote container v1.52.0 breaks in environments with volume restricted docker setups

### ISSUE THREAD

**Issue by sethbax** [microsoft/vscode-remote-release#4192]
- VSCode Version: 1.52.0
- Local OS Version: windows 10 1909
- Remote OS Version: debian 10
- Remote Extension/Connection Type: Docker

I run remote-docker on a server with some security restrictions on docker, one of them is that I can only mount specific directories into a container and named volumes are also disabled.
The new feature to use a volume to cache server and extensions naturally doesn't work there see (https://github.com/microsoft/vscode-docs/blob/master/remote-release-notes/v1_52.md#vs-code-server-and-extension-cache-on-docker-volume)

exact message on failure is as follows: 
```
Error response from daemon: plugin limit-volumes 
failed with error: AuthZPlugin.AuthZReq: -v /vscode not allowed
```

Is there any way to either disable this or provide a directory instead of a names volume?

**Comment by chrmarti** [comment]
Adding a setting with 0.154.1 of the extension:
![image](https://user-images.githubusercontent.com/9205389/102337784-382abf00-3f93-11eb-8400-77b4283c60e3.png)
