### ISSUE TITLE
Repository clones into wrong folder

### ISSUE THREAD

**Issue by zifik** [microsoft/vscode-remote-release#4193]
Issue Type: <b>Bug</b>

My git repository is listed under a subgroup in a private GitLab instance. This makes my clone URL look like: `git@gitlab.myserver.com:myproject/subgroup1/subgroup2/myrepo.git`

When using `Remote-Containers: Clone repository in Container Volume...`, and selecting `Create a unique volume` the folder that is created in the container is `/workspace/subgroup1` when it should be `/workspace/myrepo`.  All names for the project seen in the container also reflect `subgroup1` and not `myrepo`.

This can potentially create issues with other projects in the same subgroup and creates confusion with identifying which container and which volume belongs to which project.

Please note that this also affects the volume name on the container host.

Extension version: 0.154.0
VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.4.0-58-generic

Update: 
In an attempt to understand this more I realized that if I pick `Create a new volume...` with the intent of sharing among several repositories, then I get the opportunity to supply a name for the repo.  It defaults to "subgroup1", but in overriding that with the actual name of the repo, the resulting docker image, container, volumes, and folder names all appear to be correct.  I will proceed with this approach.

**Comment by J0F3** [comment]
That's something that I noticed also (with GitLab) and my workaround was the same. So just using the `Clone repository in Named Container Volume...` and the specify the names by myself. 

But I think it is still a bug that it picks ups the wrong names when using `Clone repository in Container Volume` where the names are automatically defined.

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/5388. Thanks.
