### ISSUE TITLE
Show stdout and stderror from entrypoint scripts and commands

### ISSUE THREAD

**Issue by supernova2468** [microsoft/vscode-remote-release#4194]
Our dev container has an entrypoint script that runs at container runtime to inject secrets into various files and locations needed by other tasks, it also sets up some config based on the user than is running the container. 

This script requires some things to be in place in the repository and in the environment in order to do its job. It currently errors out when it doesn't find what it needs, but it is only reported as 

`Error response from daemon: Container **CONTAINER HASH** is not running.` 

It would be nice to have the option to show the error from the script so the user can understand the problem. Right now the process is to set overrideCommand back to true, then having the user run the script to see the real error, not the most user friendly. 

I could also take advantage of the postAttachCommand and its siblings to run this script, but these do not print out the error either. Showing something like the below. 

`[PID 24936] [5665 ms] Command failed: /bin/sh -c /bin/entrypoint.py`

Feature request to allow post container start scripts to provide error feedback to the user.

**Comment by chrmarti** [comment]
You should see the output when you rebuild the container. (You won't see it when you reload the window after the rebuild failed.)

**Comment by supernova2468** [comment]
Welp... 

Totally missed it, apologies for the ticket.
