### ISSUE TITLE
Installing extension on WSL gets stuck

### ISSUE THREAD

**Issue by GkqqNkKC** [microsoft/vscode-remote-release#4195]
- VSCode Version: 1.15.1
- Local OS Version: Windows 10 x64
- Remote OS Version: Ubuntu 20.04.1 LTS
- Remote Extension/Connection Type: WSL

### Steps to Reproduce
1. Click install button of an extension (in this case already locally installed)

### Additional info
- I have just made a clean WSL 2 install and ran `apt update && apt upgrade`
- The button mentioned in steps above does nothing, not even a popup. In order to see anything at all, I had to press on the cloud button which lets me choose which local extensions I wanna install into remote. This way, a notification pops saying it's installing the extensions. It hangs forever
- Extension I mainly tried is `https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools`, but obviously others runs into the same issue
- I launched remote window by clicking the green connect icon from bottom left and select `New Window`

### Possible duplicate / opens automatically-closed issue
This bug looks way too similar to https://github.com/microsoft/vscode-remote-release/issues/3152

Trying `curl -XGET https://az764295.vo.msecnd.net/extensions/marketplace.json -v` also hangs forever for me

I don't use any VPN, but I'm using a PPPoE connection (with user and pass). I do not own the network, so I'm not able to make any changes. Probably this shouldn't be an issue anyway as I was able to install locally, and the WSL has internet access

**Comment by halfhorst** [comment]
FYI I have some more data for you (came by way of 3152). I was running NordVPN and that was my issue. I know you said you aren't running one, nonetheless your network may be the problem

**Comment by GkqqNkKC** [comment]
I took a look again into the problem. I changed the network and tried again. It works

Even though my problem is kinda solved, I believe this issue shall stay open. I don't believe someone actually hardcoded the restriction to that specific url (especially as I'm not the single one which had the issue). Maybe deeper research shall be done. Other components may be affected too (not only extension downloading)

**Comment by sumitkumarkar01** [comment]
I am having the same problem.
And typing
`curl -XGET https://az764295.vo.msecnd.net/extensions/marketplace.json -v`
Also hangs for me and after a long time I get this error.
`Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 117.18.232.200:443...
* TCP_NODELAY set
* Connected to az764295.vo.msecnd.net (117.18.232.200) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to az764295.vo.msecnd.net:443
* Closing connection 0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to az764295.vo.msecnd.net:443`

**Comment by bamurtaugh** [comment]
cc @sandy081

**Comment by sandy081** [comment]
It seems you have network connection issues in your WSL hence extension installation is getting stuck. In these cases we recommend to use following setting `remote.downloadExtensionsLocally` and set it to `true` so that extensions are downloaded locally and streamed into WSL.

@aeschli FYI

**Comment by elimarkov** [comment]
I had the same issue with my VPN (PIA) turned on. Turning VPN off solved the problem.
