### ISSUE TITLE
Wrong proxy configuration when building development container on remote host

### ISSUE THREAD

**Issue by graylock** [microsoft/vscode-remote-release#4196]
I am developing on a remote host inside a docker container using the VSCode Remote Container extension. Thereby, I followed the guidelines given in the [offical manual](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host), which worked nicely. Thereby, I have set the `docker.host` variable using a SSH connection, e.g. `ssh://user@remote-ip`.

There exist only one problem: The remote machine sits behind a gateway and therefore using proxy configuration to access the internet. The docker client and deamon is configured there and everything works fine on the remote machine. But when using VSCode Remote Container to build the docker image, the proxy configuration from the docker client on the local machine is used. I have tested this with the `config.json` file (inside the `.docker` folder). This would be no problem, when one could specifiy the proxy configuration there for a given endpoint (e.g. the SSH connect). But unfortunatly, the default configuration is used regardless of the specified docker.host.

Here is a snipped of the `config.json` file:

```json
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://127.0.0.1:3001",
     "httpsProxy": "http://127.0.0.1:3001"
   },
   "ssh://username@remote-ip":
   {
     "httpProxy": "http://192.168.0.1:3001",
     "httpsProxy": "http://127.0.0.1:3001"
   }
 }
}
```

I know that I could specify the proxy settings within the devcontainer.json, but since I am developing on multiple remote machines with different proxy configurations I wanted to avoid to adjust the devcontainer.json everytime.

**Comment by chrmarti** [comment]
Does this configuration work when you use `docker` from the command line yourself? This looks like it might be a problem with Docker.

**Comment by PavelSosin-320** [comment]
Docker is not guilty! The configuration of proxy, other network infrastructure things come to the Running containers from the dot-files located in the User's home folder: .docker, kube, etc.. when CLI connects to the server, Server-less Cloud infra  it takes security keys from here. One fast file edit or environment var switch and the user is switched to another server or infra provider.
[Configure proxy](https://docs.docker.com/network/proxy/) - genious solution.
Taking into account that the user may already have it..............
Running docker build correctly can solve everything.

**Comment by graylock** [comment]
Actually it is no problem with docker. For example I can use docker context to specify an endpoint and then build on the remote host using the option `network` to use the proxy configuration on the remote machine. E.g.:

```
docker context use my-remote-host
docker build --network host .
```

This actually uses the proxy configuration on the remote host, which is what I would assume should be the default way, and not the proxy configuration on the local host as VSCode Remote Container extension does it.

**Comment by chrmarti** [comment]
@graylock Does it work in VS Code when you keep `my-remote-host` as the current context?

**Comment by chrmarti** [comment]
@graylock Does it work in VS Code when you keep `my-remote-host` as the current context?

**Comment by graylock** [comment]
Unfortunately, no. Somehow the configured context is ignored by VS Code - Remote Containers extension. It could be also the case, that there is a problem since my local machine runs Windows 10 (Windows for Docker) and the remote machine runs Linux (Ubuntu 18.04).

**Comment by chrmarti** [comment]
Remote-Containers uses the Docker CLI without specifying a context and should just use the currently active one. Currently, if you switch the context while VS Code is already running, you will need to restart VS Code (to reload the Remote-Containers extension).

Can you also check the Docker extension's viewlet? That should show the containers of the currently active context the same way Remote-Containers does.

**Comment by PavelSosin-320** [comment]
@graylock The Docker context in use is stored in the User's home folder locally. This is the purpose of the Docker context - easy switch between Docker end-points at the user level use Docker context use xxx.
Regardless of OS type, 2 computers can use different proxy depends on how they are connected to the network or how the server in use connected to the network. As usual: local private network -> no proxy.
You can use docker context export / import to copy contexts to your machines.

**Comment by graylock** [comment]
@chrmarti Restarting VS Code helped so that the docker context is used. Unfortunatly, still the proxy configuration from my local machine (../.docker/config.json) is used instead of the one placed on the remote host with the correct proxy configuration. But I think now it is more a problem of Docker (or me not configuring everything right) rather then the VS Code Remote Extension. Since I tried to do everything from command line and still the local proxy configuration is used instead of the one from the remote machine. So you can close this issue here. Sorry that you had to investigate time here. And thanks for helping me!
