### ISSUE TITLE
A console tool to open remote files VS code (and could be set to EDITOR)

### ISSUE THREAD

**Issue by ppanhoto78** [microsoft/vscode-remote-release#4197]
Hello, vs code team.

I think it would be nice if we had a command that would act as a proxy to vscode-remote and cause it to open files in the editor pane. Even though we have a great editor at hand, we still rely on `emacs`/`vim`/`nano` (or variants of these) for some tasks that require $EDITOR environment variable. Some examples would be pressing `v` on `less` to edit a file or some exotic source control tool that requires $EDITOR to edit commit messages or even piping the output of some command straight to VS code.

I hope you find this useful.

**Comment by chrmarti** [comment]
There is `code` when you are inside an integrated terminal in VS Code while connected remotely. Does that not work?

**Comment by ppanhoto78** [comment]
Been using this extension since pre-release and only found it now that
you've pointed me out. Has it always been there?
The command worked well when invoked directly but showed a few glitches
when invoked through EDITOR or VISUAL settings.
For example, viewing a file with less and pressing  "v" created a second
file before opening the correct file in the editor.

I may ping on this thread if I find something important.

Thanks,

**Comment by chrmarti** [comment]
I think `less` passes the line number as the first parameter and VS Code takes that as the first of two filenames and opens it as a new file. 🤔 

Maybe open a new issue in the main repository: https://github.com/microsoft/vscode/issues/new/choose

Thanks.

**Comment by ppanhoto78** [comment]
I'll close this
