### ISSUE TITLE
Cannot launch C/C++ debugging session by remote-ssh

### ISSUE THREAD

**Issue by pkjq11** [microsoft/vscode-remote-release#4198]
- VSCode Version:1.52.0
- Local OS Version:macos10.15.7
- Remote OS Version:ubuntu18.04
- Remote Extension/Connection Type: SSH

I worked on a mac and developed on a remote Linux server by remote-ssh. Nonw I can compile projects and debug them on the command line with GDB. But when I start the debugger, a blue loading bar appears under the arrow and nothing happens. I've added logging to launch.json, but output window only print "Launch configuration" and debug console print nothing.

Steps to Reproduce:
I submitted an issue in vscode-cpptools:  https://github.com/microsoft/vscode-cpptools/issues/6675
I found a similar problem: https://github.com/microsoft/vscode-cpptools/issues/6541 and steps to reproduce can find here

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
I'll close this in favor of the vscode-cpptools issue, but we can reopen if it seems to be a vscode-specific issue.
