### ISSUE TITLE
code page 65001

### ISSUE THREAD

**Issue by chinant** [microsoft/vscode-remote-release#42]
When the system code page changes from 936 to 65001, the issue is below:
 /ms-vscode-remote.remote-wsl-0.32.0/scripts/wslCode.sh: No such file or directory

**Comment by aeschli** [comment]
Does your user folder name contain any special characters?

**Comment by chinant** [comment]
@aeschli
I modified the registry to set the cmd‘s code page to become 65001
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processo\] "autorun"="chcp 65001"
then opening a terminal in WSL and run vscode use the code-insiders command line
![issue](https://user-images.githubusercontent.com/4104851/57356216-79959e80-71a2-11e9-9438-25865024252f.jpg)

**Comment by aeschli** [comment]
Oh, I see, thanks, that was helpful.
