### ISSUE TITLE
_updateEnableProposedApi is called to late for resolvers

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-remote-release#420]
The extension services updates the `enabledProposedApi` flags, e.g based on product.json, but for resolvers that's too late resulting in proposed api usage errors

https://github.com/microsoft/vscode/blob/573db674611aff1420b7b5d627339acd235c95d4/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L842

**Comment by alexandrudima** [comment]
Fixed via https://github.com/microsoft/vscode-distro/commit/85b95652d97437ce7b9c7856c6206a5f04498471
