### ISSUE TITLE
Can't install extensions to remote

### ISSUE THREAD

**Issue by albydnc** [microsoft/vscode-remote-release#4200]
I am trying to install some extensions to the remote server (C++, Doxygen, Cmake Tools) by clicking the button on the extension manager, but nothing happens.

- VSCode Version: 1.52.0
- Local OS Version: Pop_OS! 20.10
- Remote OS Version: CentOS 7
- Remote Extension/Connection Type: SSH

Does this issue occur when you try this locally?: NO
Does this issue occur when you try this locally and all extensions are disabled?: NO

**Comment by sandy081** [comment]
Please enable log level to trace `F1 -> Set Log Level` and perform the operation again and provide us following logs 

- View -> Open View… -> Log (Window)
- View -> Open View… -> Log (Remote)
