### ISSUE TITLE
remote ssh disconnecting + extensions don't work

### ISSUE THREAD

**Issue by itaysk** [microsoft/vscode-remote-release#4201]
Couple of days ago I have started to experience disconnects every couple of minutes or so:
`Cannot reconnect. Please reload the window` which I do and it reconnects, until next time.  
Also none of the extensions work, not even the build it git tab. But I can edit files and use the terminal.

I have tried:
1. restarting VSCode host and the SSH target
2. reinstalling the extension while moving from nightly to stable
3. delete `~/.vscode-server`.

Environment:
Version: 1.52.0
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:46:53.673Z (5 days ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
Remote SSH: 0.62.0
Remote target: Ubuntu 19.10

Logs:
https://pastebin.com/t3zFuWKd
https://pastebin.com/SucVdXG0
https://pastebin.com/pRFMWZGH
https://pastebin.com/QwDJeTHZ

Thanks

**Comment by tk3369** [comment]
I am also having the same issue since Monday.  At first, I thought it may a network slowness issue but everything else works fine.

Environment:
Version: 1.52.0 (user setup)
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:45:11.850Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by itaysk** [comment]
disconnects occur reliably after 2 minutes
possibly related to https://github.com/microsoft/vscode-remote-release/issues/4182

**Comment by roblourens** [comment]
Could you try disabling any local and remote extensions?

Also please do this:

- Run the command "Set Log Level" > Trace
- Try again
- Share the logs from the devtools console (Help > Toggle Developer Tools)

**Comment by roblourens** [comment]
And another thing to try, could you try setting this `"remote.autoForwardPorts": false` to disable a new feature that we added this month? Would like to see if that makes a difference.

**Comment by alexdima** [comment]
This might be caused by our new automatic port forwarding feature which scans the remote OS for available ports in order to forward them locally (https://github.com/microsoft/vscode/issues/112843)

**Comment by itaysk** [comment]
@roblourens @alexdima thanks but that didn't help. Weirdly, I THINK that for the first time that I tried to disable auto port forward, and also the first time I tried to disable extensions, it did not disconnect. But I cannot reproduce so I guess it's an error on my test. Now it is disconnecting reliable every 2 min with port forward disabled and no extensions (besides remote ssh).
traces:
could not connect: https://pastebin.com/whriRYTH
disconnected after 2 min: https://pastebin.com/BUAyzHE4

**Comment by itaysk** [comment]
perhaps related to https://github.com/microsoft/vscode/issues/112791 ?

**Comment by itaysk** [comment]
possibly related https://github.com/microsoft/vscode-remote-release/issues/4204

**Comment by alexr00** [comment]
@itaysk would you be willing to try the following steps? This would help us confirm that we've found the issue, and you'll also get to use a more up-to-date version.

1. On your remote machine, add the following line to your .bashrc file: `export VSCODE_DISABLE_PROC_READING=true`
2. Install [VS Code Insiders](https://code.visualstudio.com/insiders/)
3. Try to repro your original issue with VS Code Insiders. 

Setting that environment variable will cause VS Code (insiders only right now, I'll make a proper fix that doesn't involve an environment variable for the next stable release), to not do the proc filesystem reading that we do to automatically forward ports for you. This does mean that automatic port forwarding will not work while you have that environment variable set.

**Comment by itaysk** [comment]
@alexr00 didn't help :(
log: https://pastebin.com/KN8pGTiQ

**Comment by alexr00** [comment]
@itaysk thanks for trying.

@roblourens is the server started up for SSH in a way that would prevent the .bashrc from getting sourced? It seems like this might the case for containers.

**Comment by roblourens** [comment]
If you had already connected to that host, you have to force restart the server by  running the command "Kill VS Code Server on Host" to get it to pick up your new config

**Comment by itaysk** [comment]
@roblourens thanks.. but that didn't help either :(

**Comment by itaysk** [comment]
@roblourens @alexr00 @alexdima is there anything else I could try, or provide you further information to help pin this issue down?

**Comment by alexr00** [comment]
@itaysk can you grab the latest insiders build and try again? The permanent fix for https://github.com/microsoft/vscode-remote-release/issues/4201#issuecomment-748975574 is in there.

**Comment by itaysk** [comment]
@alexr00 I've just tried with latest insiders - works! Then I tried with the "old" installation that I have (1.52.1) - also works! now I'm suspicious. Is it possible that just connecting with the new insiders version first, had fixed the issue on the server? They only other change I've made is upgrading the OS to Big Sur. Anyway.. I'm going to close this for now. thanks for the help

**Comment by alexr00** [comment]
@itaysk using the new version and then the old version should have any impact on the issue that the new version solves. However, that issue was not 100% repro for everyone who saw it, so it's possible that whatever transient state causes the issue was no longer happening.
