### ISSUE TITLE
"Remote-Containers: Close Remote Connection" should not shutdown a container that VsCode did not start

### ISSUE THREAD

**Issue by Neutrino-Sunset** [microsoft/vscode-remote-release#4203]
- VSCode Version: 1.52
- Local OS Version: Win 10 Pro
- Remote OS Version: Alpine 3.11
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

Dockerfile
```
FROM node:lts-alpine
```
docker-compose.yml
```version: "3.8"
services:
  node6:
    build: ./
    stdin_open: true
    volumes:
      - ./:/node6
```
.devcontainer.json
```
{
  "dockerComposeFile": "./docker-compose.yml",
  "service": "node6",
  "workspaceFolder": "/node6"
}
```

Run `docker-compose up -d --build`
While the container is running in VsCode CTRL+R select `node6 [Dev Container]` to attach VsCode to the running container.

Now, how do you detach VsCode from the container without shutting the container down? Closing VsCode or running `Remote-Container: Close Remote Connection` both close the container.

I don't think VsCode should shut down a container that it didn't start itself. I want to be able to spin up a cluster of containers, attach VsCode to one to debug something, then detach VsCode and continue.

**Comment by chrmarti** [comment]
We don't remember who started the container. You can disable automatic shutdown by adding the following to your devcontainer.json:
```json
"shutdownAction": "none",
```
