### ISSUE TITLE
Failed to connect to the remote extension host server (Error: Time limit reached)

### ISSUE THREAD

**Issue by alhabarneh** [microsoft/vscode-remote-release#4204]
Issue Type: <b>Bug</b>

-The version with issues is Nov 2020 1.52
-The errors I have been having are:

> Could not fetch remote environment
> Failed to connect to the remote extension host server (Error: Time limit reached)

I've started getting these issues since I updated my vscode to Nov 2020 1.52, I connect remote ssh through sublime and webstorm to my server with no issues at all. So I decided to rollback to an older version of vscode! I rolledback to Oct 2020 1.51 and now it works just fine!

Extension version: 0.61.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.2.0
Remote OS version: Linux x64 2.6.32-754.el6.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 83e8eb20-a8cd-421f-9341-d13a8fbb48fd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: texas.commandlink.com|
|OS|Linux x64 2.6.32-754.el6.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (2 x 2397)|
|Memory (System)|3.87GB (0.15GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Can you try installing version 0.56 of the Remote-SSH extension? You can right click the extension, pick "Install another version".

It probably won't help but I want to eliminate that variable.

**Comment by alexdima** [comment]
This might be caused by our new automatic port forwarding feature which scans the remote OS for available ports in order to forward them locally (https://github.com/microsoft/vscode/issues/112843)

**Comment by alhabarneh** [comment]
> What extensions do you have installed? Can you try disabling them? And do you have the "HTML CSS Support" extension? Had an issue reported with it.

@roblourens thank you for replying! I have disabled all of my extensions but it didn't work, I don't have HTML CSS Support extension.

**Comment by PavelSosin-320** [comment]
This issue is not software engineering issue!. There is some modest paper works is required to reserve a narrow port interval for VSCode as well-known ports and add it to already reserved by Microsoft reserved ports. If search of available ports is narrowed to 100 ports, i.e. 100 users per server it can be done in seconds. lsof takes less the 1 second and after substraction from reserved port interval produces available port list.

**Comment by alexr00** [comment]
@alhabarneh would you be willing to try the following steps? This would help us confirm that we've found the issue, and you'll also get to use a more up-to-date version.

1. On your remote machine, add the following line to your .bashrc file: `export VSCODE_DISABLE_PROC_READING=true`
2. Install [VS Code Insiders](https://code.visualstudio.com/insiders/)
3. Try to repro your original issue with VS Code Insiders. 

Setting that environment variable will cause VS Code (insiders only right now, I'll make a proper fix that doesn't involve an environment variable for the next stable release), to not do the proc filesystem reading that we do to automatically forward ports for you. This does mean that automatic port forwarding will not work while you have that environment variable set.

**Comment by sean-mcmanus** [comment]
FYI, today I started getting "Failed to connect to the remote extension host server (Error: connect ECONNREFUSED ::1:40009)", and I fixed it via doing a "wsl --shutdown"...might be a different issue though.

**Comment by alhabarneh** [comment]
I uninstalled then re-installed all extensions and for some reason it worked just fine!
