### ISSUE TITLE
Corrupted Container Config File After Reload

### ISSUE THREAD

**Issue by andyljones** [microsoft/vscode-remote-release#4208]
- VSCode Version: 1.52.1
- Local OS Version: macOS 10.15.5
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

This was a transient bug and I've been unable to reproduce it. 

It occurred after a weak internet connection lead to vscode spawning the 'reconnect in 5...' window. I hit reload, and I got a generic error box and the following log

```
[2 ms] Remote-Containers 0.154.1 in VS Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523).
[15 ms] Start: Resolving Remote
[15 ms] Setting up container /scalinglaws

[16 ms] Start: Run: docker inspect --type container /scalinglaws
[1549 ms] Error: Can not add index to parent of type array
        at /Users/andyjones/.vscode/extensions/ms-vscode-remote.remote-containers-0.154.1/dist/extension.js:1:383763
        at Module.F (/Users/andyjones/.vscode/extensions/ms-vscode-remote.remote-containers-0.154.1/dist/extension.js:1:384006)
        at /Users/andyjones/.vscode/extensions/ms-vscode-remote.remote-containers-0.154.1/dist/extension.js:1:687975
```

From the error message, I guessed some config file had been corrupted, and indeed opening the config file for the container,

```
/Users/andyjones/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/imageConfigs/scalinglaws%3alatest.json
```

it had broken syntax:

```
[
		5000,
		9095,
		8083,
		8000,
		36022,
		45555,
		51539,
		33651,
		46837,
		41019,
		53629,
		50847,
		59905,
		58913,
		36161,
		47299,
		41443,
		44069,
		44261,
		48613,
		54565,
		43881,
		51817,
		42377,
		36459,
		59467,
		39087,
		44689,
		34033,
		60209,
		49203,
		41749,
		49821,
		58469,
		58793,
		57393
	],
		41749,
		49821,
		58469,
		58793,
		57393
	]	51539,
		33651,
		46837,
		41019,
		53629,
		50847,
		59905,
		58913,
		36161,
		47299,
		41443,
		44069,
		44261,
		48613,
		54565,
		43881,
		51817,
		42377,
		36459,
		59467,
		39087,
		44689,
		34033,
		60209
	],
	"extensions": [
		"andyljones.tablatex",
		"ms-python.python",
		"ms-python.vscode-pylance",
		"ms-toolsai.jupyter",
		"ms-vscode.cpptools"
	]
}
```

Looks like a torn write to my amateur eye? Anyway, fixing up the syntax by copy-pasting in the structure of another container's config file fixed things.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
Maybe the race condition between two VS Code windows attached to the same container. This could be triggered by the new automatic port forwarding in VS Code 1.52.

**Comment by chrmarti** [comment]
Fix is available with version 0.154.2 of the extension.

**Comment by connor4312** [comment]
@chrmarti are there verification steps available?

**Comment by chrmarti** [comment]
@connor4312 I often saw it when starting to listen on multiple ports at the same time. These would be picked up and cause the race condition to hit. This is when attaching to a container (without devcontainer.json).
