### ISSUE TITLE
Docker entrypoint not used

### ISSUE THREAD

**Issue by alex-weej** [microsoft/vscode-remote-release#4209]
Someone else opened this in https://github.com/microsoft/vscode-remote-release/issues/232 but I can't reopen that as it was closed due to inactivity. Grrr...

We need to run an entrypoint command to set up some dynamically computed environment. `ENV` in Dockerfile does not let you compute it from running a command, so we set `ENTRYPOINT some-environment-setup`. However, the VS Code extension does not work as expected as it seems to override the entrypoint.

**Comment by PavelSosin-320** [comment]
The best way to configure Docker container environment is to pass --env or --env-file when dev-container is started. It is already supported. Since ENTRY_POINT is a part of image it can be "inherited" by another container or overridden by docker run. It is not the best place to configure an environment if it is not something very generic for a group of images. Entry point usually starts something.

**Comment by ariyo-live** [comment]
Similar to Alex, I am having a problem getting the **CMD** and **ENTRYPOINT**  commands to run on startup when creating a container with vscode and the remote-containers extension, nearly spending two days working on this.  For now, I have a work around.  We can develop and test in vscode, but in creating any production containers that need startup commands _(e.g. containers in cloud services)_, we need to create the images and containers manually using the docker commands _(e.g. docker build, docker run, ..._).

**Comment by PavelSosin-320** [comment]
@ariyo-live When you are creating any container image you are thinking about how it will be deployed to production environment. Muliple things can be defined or overriden during deplooyment like --entrypoint. user, published ports, networks, etc. This is the reason why docker run has so many options and docker-compose has deploy section. many container image properties are only defaults. dev-container extensions knows to do only one thing: build dev-environment as  OCI container image and run it as standalone container not managed by docker engine. It is not a "deployer". The way to deploy something as a cloud service you have to find in another place like docker-compose with all section in-use runned as docker stack deploy using corresponding VSCode plugin, creation of resource yaml using podman, creation of deployment yaml, etc. Then use the proper deployer.  This is not a workaround.

**Comment by ariyo-live** [comment]
> @ariyo-live When you are creating any container image you are thinking about how it will be deployed to production environment. Muliple things can be defined or overriden during deplooyment like --entrypoint. user, published ports, networks, etc. This is the reason why docker run has so many options and docker-compose has deploy section. many container image properties are only defaults. dev-container extensions knows to do only one thing: build dev-environment as OCI container image and run it as standalone container not managed by docker engine. It is not a "deployer". The way to deploy something as a cloud service you have to find in another place like docker-compose with all section in-use runned as docker stack deploy using corresponding VSCode plugin, creation of resource yaml using podman, creation of deployment yaml, etc. Then use the proper deployer. This is not a workaround.

Thanks Pavel... I appreciate your help.
