### ISSUE TITLE
WSL2 High CPU Usage when running VSCode WSL2 with IntelliJ Idea + VcXsrv

### ISSUE THREAD

**Issue by leobastiani** [microsoft/vscode-remote-release#4210]
- VSCode Version: 1.52.1
- Local OS Version: Windows 10 19041.572
- Remote OS Version: 4.19.128-microsoft-standard
- Remote Extension/Connection Type: WSL2

Steps to Reproduce:

1. Download, install and run VcXsrv with ` -multiwindow -clipboard -wgl -ac -noprimary -clipboard`
1. Set DISPLAY environment variable
1. Download, install and run [IntelliJ Idea](https://www.jetbrains.com/idea/download/#section=linux)
1. Run VSCode on WSL2

Does this issue occur when you try this with VSCode without WSL?: No
Does this issue occur when you try this with VSCode with WSL and all extensions are disabled?: Yes

I took a screenshot when I run everything together. Although 12% of CPU usage isn't as much, it increases to 60%~80% when I run my Java application on Intellij. Without Intellij, VSCode takes less then 1% of my CPU, my application and Intellij stays below 1% of CPU usage.
![image](https://user-images.githubusercontent.com/8663061/102524095-418d5780-4077-11eb-99d0-fae9e523e69a.png)
Why is VSCode using more CPU when I open Intellij? That's what I wonder.
This still happens when I open VSCode and Intellij in different working directories.

**Comment by alexdima** [comment]
This might be caused by our new automatic port forwarding feature which scans the remote OS for available ports in order to forward them locally (https://github.com/microsoft/vscode/issues/112843)

**Comment by leobastiani** [comment]
after applying https://github.com/microsoft/vscode/issues/112843#issuecomment-748895800 it is working fine
thank you 🤗

**Comment by alexdima** [comment]
FYI @alexr00
