### ISSUE TITLE
doesn't always conect

### ISSUE THREAD

**Issue by noor-debug** [microsoft/vscode-remote-release#4214]
when I try to connect to ssh remote sometimes it does and sometimes it doesn't , without a reason ,it tells me to retry and after that could not establish .. I need help

**Comment by trevarj** [comment]
I have this same issue when I disconnect by just X'ing out or shutting down the remote machine. The next day, when I try to reconnect to the workspace it always says there's no route to host. It eventually connects after I restart VSCode a few times.

I think it may be due to a non-graceful shutdown? Didn't get to troubleshoot much yet.

On Ubuntu and latest version of VSCode on both machines.

**Comment by roblourens** [comment]
Please give more details @noor-debug such as the log from the Remote-SSH output channel

**Comment by trevarj** [comment]
@roblourens 
For me it's as follows:

1. Start a remote ssh session
2. Do some work
3. From the terminal in VSCode, shutdown the remote machine (`sudo shutdown now`). VSCode connection will try to reconnect. Just close the window.
4. Start up remote machine again
5. Open VSCode
6. File -> Open Recent -> Click the previous ssh connection
7. Does not immediately connect and fails with "no route to host" even though the machine is running and sshd as well.
8. If you continuously click "Retry" to connect again, it eventually works after a 5-6 tries, but by then you lose all your opened tabs.

VSCode: `1.52.1`
SSH Extension is up to date
OS: Pop!OS (Ubuntu 20.10)

**Comment by roblourens** [comment]
`no route to host` this sounds like an error from SSH, not from vscode.

**Comment by trevarj** [comment]
> `no route to host` this sounds like an error from SSH, not from vscode.

My thoughts too, but it's weird when I can connect to SSH normally through a terminal and then when I repeat the above it starts being weird.

**Comment by roblourens** [comment]
All we are doing is running a command roughly equivalent to something like `echo uname | ssh <your host>`. If that works at the same time that vscode is showing this error, then you could share the log to see if it has some more details.
