### ISSUE TITLE
Show download progress and speed when downloading VS Code Server

### ISSUE THREAD

**Issue by fakhamatia** [microsoft/vscode-remote-release#4216]
Please show download progress and speed when downloading VS Code Server from server or client 

![Screenshot from 2020-12-18 13-44-16](https://user-images.githubusercontent.com/20030910/102602993-7c56c480-4137-11eb-8152-bfc62f2adce7.png)

**Comment by roblourens** [comment]
Don't really have a graceful way to do this unfortunately
