### ISSUE TITLE
ln: failed to create symbolic link '/var/run/docker.sock': File exists

### ISSUE THREAD

**Issue by edburns** [microsoft/vscode-remote-release#4218]
Issue Type: <b>Bug</b>

1. Git clone https://github.com/Azure/azure-sdk-for-java

2. In WSL2, cd to the place where I cloned it.

3. code .

4. When prompted to open the devcontainer.json file, say yes.

5. After a while, this message happens.

Docker CLI already installed.
Docker Compose already installed.
ln: failed to create symbolic link '/var/run/docker.sock': File exists
The command '/bin/sh -c if [ "${INSTALL_DOCKER}" = "true" ]; then         rm -f /usr/local/share/docker-init.sh         && bash /tmp/library-scripts/docker-debian.sh "true
" "/var/run/docker-host.sock" "/var/run/docker.sock" "codespace";     fi     && rm -rf /var/lib/apt/lists/* /tmp/library-scripts/' returned a non-zero code: 1
[1191763 ms] Command failed: docker build -f /home/edburns/workareas/azure-sdk-for-java/.devcontainer/Dockerfile -t vsc-azure-sdk-for-java-b94cf9ee3431af642d9afffb741bb8df --build-arg INSTALL_DOCKER=true /home/edburns/workareas/azure-sdk-for-java/.devcontainer

Extension version: 0.154.1
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (0.25GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/edburns/workareas/azure-sdk-for-java --remote=wsl+Ubuntu --crash-reporter-id 3831bddc-40f9-4e40-9569-5dcd049d789c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|12.43GB (0.64GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092

```

</details>

**Comment by chrmarti** [comment]
The base image `FROM mcr.microsoft.com/vscode/devcontainers/universal:0-linux` likely added Docker, so you can remove the install of Docker from the Dockerfile.
