### ISSUE TITLE
Using `docker-compose.yml` with its `.env` when both not in current workspace

### ISSUE THREAD

**Issue by niccolomineo** [microsoft/vscode-remote-release#4220]
I am using a `docker-compose.yml` and a `.env` for it both one level higher than my current workspace, where I have my `.devcontainer` folder with its `devcontainer.json` file.

Is there a way to point to such `.env` in my `devcontainer.json` file?

I would like to avoid replicating the `.env` in my current workspace.

**Comment by chrmarti** [comment]
If you need the environment variables to apply to your containers only, you can set `env_file` in the `docker-compose.yml`: https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option

Otherwise tracked in https://github.com/microsoft/vscode-remote-release/issues/2706.

**Comment by niccolomineo** [comment]
No, I meant passing variables from the `.env` to the `docker-compose.yaml` itself.
