### ISSUE TITLE
unable to tern off port forwarding 

### ISSUE THREAD

**Issue by enpclark** [microsoft/vscode-remote-release#4221]
Issue Type: <b>Bug</b>

I've disabled port forwarding in the user, workspace and general settings but the setting is not respected. SSH is still port forwarding from the server. How do i turn it off?

Extension version: 0.62.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-58-generic snap
Remote OS version: Linux x64 5.4.0-1030-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 2037)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.37GB (9.93GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 32972d83-b7aa-4275-9779-e9dd67cdeea9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: ec2-3-8-175-247.eu-west-2.compute.amazonaws.com|
|OS|Linux x64 5.4.0-1030-aws|
|CPUs|Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (1 x 2399)|
|Memory (System)|1.94GB (0.45GB free)|
|VM|0%|
</details>

**Comment by alexr00** [comment]
Can you please share a screenshot of the Ports view? (command palette -> Remote Explorer: Focus on Ports View)

**Comment by enpclark** [comment]
[image: image.png]

Hi Alex,

sorry for the delay, Here is a screenshot.

Thanks,
Emmanuel
