### ISSUE TITLE
Live Server Preview is not working in WSL 2

### ISSUE THREAD

**Issue by jason-migz** [microsoft/vscode-remote-release#4222]
- VSCode Version:
1.52.1
- Local OS Version:
Windows 10 Pro build 19042.685
- Remote OS Version:
Linux Ubuntu 20.04
- Remote Extension/Connection Type: SSH/Docker/WSL
Live Server v5.6.1
Steps to Reproduce:

1. open your project from WSL command line by typing `code .`
2. hit `CTRL + p` and type `> live server: open with live server` and click it
3.) it will automatically open in browser
4.) make change in your html file from VS Code
5.) check the browser window if your changes appeared

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by bamurtaugh** [comment]
Hey @jason-migz, it looks like this could be https://github.com/ritwickdey/vscode-live-server/issues/720, in which case it'd be an upstream issue. 

Just to verify, when you mention:

> Does this issue occur when you try this locally?: Yes
> Does this issue occur when you try this locally and all extensions are disabled?: Yes

Do you mean you're also having issues with Live Server Preview when not using WSL?
