### ISSUE TITLE
Design issue: Dev-container post-create hook contradicts the Docker-engine logic

### ISSUE THREAD

**Issue by PavelSosin-320** [microsoft/vscode-remote-release#4223]
Although Docker is used only as container runtime it keeps all its features and algorithms used for Container management. One of the Docker assumptions is that the Container is able to reach the desired state in a limited time, otherwise, it must be purged and replaced with a new healthy container instance. Otherwise, Docker will eat Host resources unlimited due to repeating creation attempts. It happens!
The current dev-container post-create hook designed behavior:
The post-create hook is applied to an unknown container state and neither committed nor rolled back.
The container can exit preliminary before or during the hook execution due to various events like errors, OOM, or other out-of-resource conditions. docker's user can observe container exit code using docker ls --all But the exit code observation feature is not implemented in dev-container extension. 
Users can choose between using -rm option and be blind to the container's exit reason or skip this option and keep the dead container taking risk of resource leak, unreleased locks, etc.
The container's environment can be configured and passed to the running container using existing VSCode features.
This is pre-create hook, not post-create.
Desired container modification process aligned with Docker logic:
All post-image-creation container modifications can be applied only on the healthy, already running container and committed to the new image using Docker container commit. Then, the intermediate-state container must be removed to release resources.
The new container instance shall be created from the new image. Unfortunately, post-create hook will be triggered again and it is very hard to prevent it from running.
Exit from the container before commit will roll the image back to the original version making this process safe.

**Comment by PavelSosin-320** [comment]
Design self-review: docker container export and docker container import can be used as docker commit alternative.

**Comment by chrmarti** [comment]
If you want the changes applied in the `postCreateCommand` to be persisted in an image, you can move the command to the `Dockerfile`. The `postCreateCommand` runs on the already running container.

**Comment by PavelSosin-320** [comment]
@chrmarti The irony that if dev-container is OCI container then OCI standard allows some kinds of hooks [OCI container hooks](https://github.com/containers/podman/blob/master/pkg/hooks/docs/oci-hooks.5.md)  but Podman never released this feature because a hook can stall container execution for the time unacceptable for container engine. Such a container becomes not portable. There are some still open issues regarding post-create functionality. Container post-create is entry-point and it can be passed as docker run option. It looks like some people believe that according to the documentation they can alter, install some software or configure the container using **postCreateCommand.**

**Comment by chrmarti** [comment]
We are not using the OCI hooks at the moment. It looks like they are operating at a lower level than we want for `"postCreateCommand"`.

**Comment by PavelSosin-320** [comment]
Podman doesn't use OCI hooks too.  The reason why not to use them is the unpredictable time needed to make the container "healthy" and functional. There is no obvious mechanism to check when "post-hooks" have completed. How long to wait? When to abort the execution because the timeout is expired.  This is a very long asynchronous operation that doesn't change the container state and emits a Docker event. In the absolute majority of cases, the health-check timeout is set to something about 50 sec by the default The docker is built to serve multiple users and requests in parallel on the same server. But it has no user limit and load-balancer or queue. Standalone Docker engine works well if all operations are short. In a multiuser environment, every request has a timeout to release resources locked by the user's request.
The Kubernetes and Swarm can afford only some kinds of container and pod hooks because their resources are horizontally scalable.
