### ISSUE TITLE
Python Interpreter Selection Problem

### ISSUE THREAD

**Issue by FunkyKoki** [microsoft/vscode-remote-release#4225]
Issue Type: <b>Bug</b>

1. Connect a remote host using 'remote ssh' and open a python project folder, then select a python interpreter in the remote host device
2. Open another VS Code window and open a local folder which is also a python project, here comes the problem: the pop-up python interpreter selection interface shows the interpreters in the host, not the local host. 

Hope to be solved soon~

Extension version: 0.62.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.4.0-58-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.87GB (12.43GB free)|
|Process Argv|--crash-reporter-id 4b43c000-9fec-46c6-b495-e20a7cfee15c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.193.154.188|
|OS|Linux x64 5.4.0-58-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz (16 x 1433)|
|Memory (System)|125.79GB (83.32GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
