### ISSUE TITLE
Can't open, rename or delete files that contains ":" on linux

### ISSUE THREAD

**Issue by cleiveliu** [microsoft/vscode-remote-release#4227]
- VSCode Version:1.52.1(user setup)
- Local OS Version:windows 10 home, 19041.685
- Remote OS Version:Linux version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 8 23:39:32 UTC 2018 (On vbox)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.Exploer create a file, named `x:x.py`, and it shows as `X:x.py`
2.When you right click at the `X:x.py`, you can't rename it or delete it, but you can rename or delete it in terminal

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No, because `x:x.py` is not a valid file name on windows.

**Comment by bpasero** [comment]
When you say you cannot rename or delete, whats the error?

**Comment by cleiveliu** [comment]
```shell
$ ls # empty
$ touch x:x.py t:T.py
$ ls 
t:T.py  x:x.py
```

- 1 In the vscode exploer, the `x:x.py` shows as `X:x.py`, the `t:T.py` shows as `T:T.py` ;
- 2 when your mouse right click on the `X:x.py` or `T:T.py` and click `rename` or `Delete Permanently`, it did't work like normal name files.
  -  when you rename a file like `T:T.py` to `sss.py`, it shows `Error: ENOENT: no such file or directory, rename '/root/code_quan/empty_for_shell/T:T.py' -> '/root/code_quan/empty_for_shell/sss.py'` on the right corner of this window.
  ![https://raw.githubusercontent.com/cleiveliu/images/master/screenshot-2021-01-09-111137.png](https://raw.githubusercontent.com/cleiveliu/images/master/screenshot-2021-01-09-111137.png)
  - when you delete a file like `T:T.py`, it shows `vscod...://ssh-remote%2B{your ip addr}/path/to/T%3AT.py does not exist and can not be deleted` on the popup window.
  ![https://raw.githubusercontent.com/cleiveliu/images/master/screenshot-2021-01-09-111225.png](https://raw.githubusercontent.com/cleiveliu/images/master/screenshot-2021-01-09-111225.png)

**Comment by bpasero** [comment]
My feeling is that the `:` in the name possibly corrupts the URI and we fail to open the right path. I cannot reproduce running out of sources though with our test resolver. 

@aeschli if you have a chance to try to reproduce this in WSL running out of sources that would be great, or teach me how I can debug the remote in WSL?

**Comment by PavelSosin-320** [comment]
Because Linux including WSL distro is POSIX system! One of the main reasons to have WSL is to have POSIX system. Only Windows is not POSIX OS in use today. POSIX is the collection of RFC standards. According to POSIX, the 1st colon is the separator between URN and authority, i.e user@host. URN is one of the known protocols in most cases: FILE:, HTTP, SSH, WSL, ............. The second colon The 1st slash starts the PATH portion of the URL.
The entire Internet is a huge POSIX system. It doesn't understand C:, D:, E: , \, etc.
The special characters must be escaped using backslash or %unicode value.

**Comment by aeschli** [comment]
The problem is with `fileService.resolve`. 
```
getBaseLabel (labels.ts:88)
toFileStat (fileService.ts:228)
doResolveFile (fileService.ts:196)
await in doResolveFile (async)
resolve (fileService.ts:169)
``

I thought labels is only about representation, e.g. rendering of labels. Why does the fileService use it?

**Comment by bpasero** [comment]
@aeschli how does that result in a problem though?

Each `stat` carries a `name` property, same as node.js stat does. Given a `URI` we need to get the name, and the only method for that purpose is the one used. If there is a bug in that method, I think we should fix it there, no?

**Comment by aeschli** [comment]
`createFile` creates the new resource and then does a stat. Due to the bug that stat has a wrong stat.name, but correct stat.resource).
A FileOperationEvent is created with that stat as target, and the target name is used by the explorer to create a ExplorerItem.

**Comment by bpasero** [comment]
The `IFileService` will no longer convert lowercase drive letters to uppercase but keep it. On top of that, I fixed the `getBaseLabel` method too.
