### ISSUE TITLE
When inside Remote Container, "User" settings should map to "Container" settings

### ISSUE THREAD

**Issue by navneetkarnani** [microsoft/vscode-remote-release#4230]
Issue Type: <b>Bug</b>

I am using the "Remote Containers" extension to connect to a Docker container where I do my development for a project.

When I install the Lombok extension on the host machine, it updates the "User" settings to have the "javaagent" with the path of the jar from the user home directory.

When I am working inside a "Remote Container" hosted on my local Docker machine, I have the option to install extensions that are relevant to that container. But, at this time, when I install the extension, the "User" setting already has the "javaagent" entry from the host, and hence the Java language server fails to start. The host user directory is not available on the Container. 

The work around is to open the user settings.json file and remove the "javaagent" entry from there. But then, that means I cannot use the extension on my host machine.

When running inside a container, the extension settings should be added to the "Remote" settings instead of the "User" settings.

Extension version: 0.154.1
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0
Remote OS version: Linux x64 4.19.121-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (0.86GB free)|
|Process Argv|--crash-reporter-id 0dec9fd0-c8fd-4152-a33c-72a9d4647e00|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container dev:latest (/dev-infra_api-server_1)|
|OS|Linux x64 4.19.121-linuxkit|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (2 x 1600)|
|Memory (System)|3.85GB (0.36GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30237827
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30236630
vsjup459cf:30237188

```

</details>

**Comment by chrmarti** [comment]
@sandy081 Can you confirm: The extension needs to handle this by making the setting scoped as `"machine"` or `"machine-overridable"` and probably by using the machine scope when writing the setting.

**Comment by sandy081** [comment]
Yes, the extension needs to change the scope of the setting to `machine` or `machine-overridable` so that its value from user settings is ignored when opened in remote window.

**Comment by sandy081** [comment]
@navneetkarnani Please file issue against the extension to change the setting scope.
