### ISSUE TITLE
Unable to access host machine's git when connected to dev container

### ISSUE THREAD

**Issue by zebralight** [microsoft/vscode-remote-release#4231]
I found [this bug report](https://github.com/microsoft/vscode-remote-release/issues/2591) that was shown as resolved, but I'm unable to access host machine's git when connected to the dev container and am prompted to install git.  My workaround is to disconnect and run git operations from host machine.

- VSCode Version: 1.52.1
- Local OS Version: Linux x64 5.9.14-arch1-1
- Remote OS Version: ubuntu latest
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

use `Dockerfile`:
```
FROM ubuntu:latest
RUN apt-get -y update
COPY . /usr/src
WORKDIR /usr/src
```
and `devcontainer.json`:
```
{
    "name": "Existing Dockerfile",
    "dockerFile": "../Dockerfile",
    "settings": {
        "terminal.integrated.shell.linux": null
    },
}
```
1. open terminal
2. run `mkdir sample`
3. run `cd sample`
4. open vs code (the rest are in vs code)
5. open command palette
6. run `Remote-containers: Open folder in container`
7. select path for `sample` directory
8. if prompted to build image, confirm
9. see this popup as well as git functionality disabled from vs code sidebar
![2020-12-24-133632_380x118_scrot](https://user-images.githubusercontent.com/1592194/103106775-2e393980-45ed-11eb-93b1-dc33fce3bd90.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
That's expected. You currently need to install Git into the container. E.g., replace your `RUN apt-get` line in the Dockerfile with: `RUN apt-get update && apt-get -y install git`.

The reason for this is that the Git integration runs inside the container and does not have access to the Git installed on the host.
