### ISSUE TITLE
Allow dismissing reopen in container notification permanently for a workspace

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-remote-release#424]
> Right now whenever I open a project with dev container configuration, it will ask me if I want to reload the folder in dev container. But I can't dismiss the notification forever, which is annoying as I will see notifications for a lot of projects even if I don't want to use container for some of them.

**Comment by RMacfarlane** [comment]
@chrmarti This doesn't seem to be scoped to a workspace, after using "Don't Show Again" on one workspace, it never appears for others

**Comment by chrmarti** [comment]
That's correct and by design. I forgot to mention that.
