### ISSUE TITLE
remote.extensionKind appears incompatible with docker-compose Remote Containers

### ISSUE THREAD

**Issue by EricHripko** [microsoft/vscode-remote-release#4241]
- VSCode Version: _1.50.1_
- Local OS Version: _Windows 10_
- Remote OS Version: _RHEL7_
- Remote Extension/Connection Type: _Docker_

Steps to Reproduce:

It doesn't seem to be possible to use any extensions locally if your Remote Containers setup relies on `docker-compose`. This appears to be the case for both files on Windows filesystem and WSL2 filesystem.

- Create a `docker-compose` based setup for VSC Remote Containers, sample below
```jsonc
// See https://aka.ms/vscode-remote/containers for the
// documentation about the devcontainer.json format
{
    "dockerComposeFile": [
        "docker-compose.yml"
    ],
    "workspaceFolder": "/workarea",
    "service": "dev",
    "settings": {
        "remote.extensionKind": {
            "vscode.git": [
                "ui"
            ],
            "vscode.github": [
                "ui"
            ]
        }
    }
}
```
- Open this setup with Remote Containers
- Observe extensions failing to operate, as they're trying to access `C:\workarea` instead of the host path that maps to `/workarea` in the container
```
[2020-12-29 17:41:58.273] [renderer1] [error] ENOENT: no such file or directory, scandir 'C:\workarea': Error: ENOENT: no such file or directory, scandir 'C:\workarea'
[2020-12-29 17:44:02.044] [renderer1] [error] read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:200:27)
[2020-12-29 17:45:58.783] [renderer1] [warning] Workbench did not finish loading in 10 seconds, that might be a problem that should be reported.
[2020-12-29 17:46:00.663] [renderer1] [error] ENOENT: no such file or directory, scandir 'C:\workarea': Error: ENOENT: no such file or directory, scandir 'C:\workarea'
```

Does this issue occur when you try this locally?: _No, but this is specific to running an extension locally whilst developing remotely._
Does this issue occur when you try this locally and all extensions are disabled?: _No, but this is specific to running an extension locally whilst developing remotely._

**Comment by chrmarti** [comment]
These extensions are not prepared to run as UI extensions.

**Comment by EricHripko** [comment]
Hi @chrmarti 👋 Thank you for your response.
Could these eventually be UI extensions? If so, is there anywhere else I should be submitting my issue?

**Comment by chrmarti** [comment]
Hi @EricHripko, why do you want to run them as UI extensions?

**Comment by EricHripko** [comment]
Setting up `git` inside the container is a chore when you have everything on the host already:
- `git` is quite a chunky package and frequently depends on `perl`, `tcl`, `tk` on top of pulling in X libs
- If you use Git over SSH, you now also need to install an SSH client manage SSH keys inside the container. This could now be nearing 1GB just to run `git`
- `git` in Docker for Windows introduces further setup burden:
  - Pre-WSL2, using `git` inside required extra config to ensure that permissions are sane (otherwise everything gets marked as `755`)
  - Post-WSL2, you now have to make sure that permissions/ownership is correct (otherwise files are created with `root` as owner)

**Comment by chrmarti** [comment]
> * `git` is quite a chunky package and frequently depends on `perl`, `tcl`, `tk` on top of pulling in X libs

`git` itself shouldn't require any UI packages. Check you are not installing 'suggested' packages.

> * If you use Git over SSH, you now also need to install an SSH client manage SSH keys inside the container. This could now be nearing 1GB just to run `git`

Why would you use SSH to get into the container? You local Git install still works for local folders (these can be mounted in a container at the same time).

> * `git` in Docker for Windows introduces further setup burden:
>   
>   * Pre-WSL2, using `git` inside required extra config to ensure that permissions are sane (otherwise everything gets marked as `755`)
>   * Post-WSL2, you now have to make sure that permissions/ownership is correct (otherwise files are created with `root` as owner)

Post-WSL2: Make sure you are using non-root user in the container. We update that user's UID and GID to match those of the WSL user. If that doesn't work, please append the full log (`F1` > `Remote-Containers: Show Log`) from opening in the container.

**Comment by EricHripko** [comment]
> git itself shouldn't require any UI packages. Check you are not installing 'suggested' packages

You're right regarding X libs; these can be avoided. However, the rest of the listed dependencies would still be pulled in.

> Why would you use SSH to get into the container? You local Git install still works for local folders (these can be mounted in a container at the same time).

To clarify, I was referring to accessing Git repositories over SSH (e.g., `git@github.com:microsoft/vscode-remote-release.git`) as opposed to HTTPS (e.g., `https://github.com/microsoft/vscode-remote-release.git`). In this case, user would need an SSH client and keys installed inside the container.

>  Make sure you are using non-root user in the container

This adds extra complexity to the containers and also isn't totally reliable. For example, a common practice of setting UID/GID inside container to match UID/GID on the host leads to some tools breaking (since they try and fail to get extra user information from `/etc/passwd`).

**Comment by EricHripko** [comment]
Hi @chrmarti - based on above, do you think it's reasonable to expect Git functionality to support `extensionKind`?

**Comment by chrmarti** [comment]
Your suggestion makes sense, it would be non-trivial to implement. The Git extension is not aware of the fact that the repository is also available locally and would first have to be made aware of that and the local path of the repository.
