### ISSUE TITLE
VS Code Remote SSH not using agent to manage passwords

### ISSUE THREAD

**Issue by hgezim** [microsoft/vscode-remote-release#4244]
- VSCode Version: Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (2 days ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. In a remote server, clone a GitHub repo.
2. Ensure you use an SSH key with a password for GitHub
3. Connect VS code to remote server using Remote - SSH
4. Open a foler that's checked in git
5. Go to Source Control pane and do a git pull
6. You should receive a permission denied error (expected)
7. Open a terminal (ensure it's in the remote server)
8. Run `eval "$(ssh-agent -s)"` then `ssh-add` and enter password to your default SSH key.
9. `cd <git dir>` and run `git pull`
10. That should work without issue.
11. Now go to Source Control click Pull.

Expected results:

This pull to work since `git pull` in the terminal works.

Actual results:

> git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

![Xnip2020-12-18_17-09-50](https://user-images.githubusercontent.com/124675/102674618-d9f90a00-4153-11eb-9c8a-d4d4e483f027.png)

Does this issue occur when all extensions are disabled?: Unsure.

**Comment by hgezim** [comment]
I tried using the remote ssh-agent.

**Comment by roblourens** [comment]
Do you have `ForwardAgent` set in your SSH config? As a test, can you try disabling the setting `remote.SSH.enableAgentForwarding`?

**Comment by hgezim** [comment]
The same thing happened after disabling ` remote.SSH.enableAgentForwarding` (I didn't restart VS Code):

```

> git push -u origin dev

git@github.com : Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights

and the repository exists.

```

**Comment by roblourens** [comment]
You will have to restart vscode. You can check that your terminal is talking to the ssh agent with `ssh-add -l`

**Comment by hgezim** [comment]
I turned off Agent Forwarding for both user and remote settings:

Push context menu from Source Control gives me this error:

```
> git push origin dev:dev
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

`git push` from the remote terminal works without issue.

```
$ ssh-add -l
256 SHA256:<KEY> <email> (<key name>)
```

**Comment by roblourens** [comment]
What is `echo $SSH_AUTH_SOCK`?

**Comment by hgezim** [comment]
On the remote machine:

```
$ echo $SSH_AUTH_SOCK

$
```

On local:

```
/private/tmp/com.apple.launchd.<rand chars>/Listeners
```

**Comment by roblourens** [comment]
I guess your original steps say that you started the ssh agent in the terminal before running the git command in that terminal, right? Well then the ssh agent is not set up in vscode's environment. A common thing to do is to start it in some shell setup script. But that variable needs to be set in vscode's environment, not just a terminal. https://www.ssh.com/ssh/agent

**Comment by lucasresck** [comment]
Hi, @roblourens and @hgezim, how are you? I am also running into this issue in a remote Ubuntu machine, maybe you could assist me.

I have a successfully configured GitHub repository using a SSH key in this remote machine and I can successfully connect to this machine using VS Code's Remote - SSH extension. However, VS Code's Git does not work after starting ssh-agent at the terminal and adding my passphrase to it, as @hgezim said.

I tried to create scripts inside `.bashrc` and `.bash_profile`, they in fact can start ssh-agent on login or terminal login, but VS Code does not recognize it. I understand that I have to start ssh-agent before initializing VS Code through the SSH connection, but I don't know how to do it. Do you have any tip, please?

Just in case, I was taking a look at [VS Code Remote Development Tips and Tricks](https://code.visualstudio.com/docs/remote/troubleshooting) and I read:

> Resolving hangs when doing a Git push or sync on an SSH host
>
> If you clone a Git repository using SSH and your SSH key has a passphrase, VS Code's pull and sync features may hang when running remotely.
> Either use an SSH key without a passphrase, clone using HTTPS, or run git push from the command line to work around the issue.

Is this the case for me too?

Thanks in advance.
