### ISSUE TITLE
The terminal will be reused by the task, press any key to close it.

### ISSUE THREAD

**Issue by DominicccLUO** [microsoft/vscode-remote-release#4245]
Issue Type: <b>Bug</b>

Wsl remote, ubuntu20.04, the terminal cannot be input when compiling, but it can be compiled successfully.
Before you can operate directly in the terminal, now you need to use the command line.
Terminal prompt: The terminal will be reused by the task, press any key to close it.

Extension version: 0.52.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.4.0-53-generic
Remote OS version: Linux x64 5.4.0-53-generic
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (1.86GB free)|
|Process Argv|--crash-reporter-id 86a0631e-6f35-4e19-b803-c9afb86015af|
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.237.128|
|OS|Linux x64 5.4.0-53-generic|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (4 x 2592)|
|Memory (System)|7.75GB (1.29GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.237.128|
|OS|Linux x64 5.4.0-53-generic|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (4 x 2592)|
|Memory (System)|7.75GB (1.29GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.91GB (1.86GB free)|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440cf:30237828
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30236630
pythonvspyt859:30239450

```

</details>

**Comment by bamurtaugh** [comment]
Hey @DominicccLUO, could you provide some additional context here - what exactly is the problem you're seeing? The title of your issue is, "The terminal will be reused by the task, press any key to close it,' but that is expected terminal output when working in various workflows. 

Are you having trouble using the terminal? Can you give us more info about what steps you were doing and how to reproduce the issue you're facing?
