### ISSUE TITLE
"Docker Compose required" - "Open Workspace in Container" broken on macOS

### ISSUE THREAD

**Issue by dslijepcevic** [microsoft/vscode-remote-release#4247]
Issue Type: <b>Bug</b>

![vscode-docker-compose-bug](https://user-images.githubusercontent.com/1915869/103447839-c2ac3780-4c90-11eb-8425-005d3b9475f3.gif)

"Open Workspace in Container" does not work with containers based on `docker-compose` on macOS. "Open Folder in Container" followed by "Open Workspace" is working properly. 

`test.code-workspace`:
```json
{
    "folders": [
        {
            "name": "test",
            "path": "."
        }
    ]
}
```

`.devcontainer.json`:
```json
{
    "dockerComposeFile": "docker-compose.yml",
    "service": "devbox",
    "workspaceFolder": "/code"
}
```

`docker-compose.yml`:
```json
version: "3.8"
services:
    devbox:
        image: ubuntu:16.04
        volumes:
            - ".:/code:cached"
        stdin_open: true
        tty: true
```

Extension version: 0.154.1
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0
Remote OS version: Linux x64 4.19.121-linuxkit
Docker Desktop version: 3.0.3 (51017)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.88GB free)|
|Process Argv|--crash-reporter-id 2be86b01-12c3-46de-8586-1d620288e4c4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container|
|OS|Linux x64 4.19.121-linuxkit|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2193)|
|Memory (System)|1.94GB (0.24GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
`docker-compose` does not seem to be on the `PATH`. Where is that added to the `PATH`?

**Comment by dslijepcevic** [comment]
@chrmarti Docker compose *is* in the `PATH` as you can see by me opening the exact same dev container using a different VSCode command ("Open Folder in Container").

**Comment by chrmarti** [comment]
ACK, following your steps reproduces the issue. Thanks.
