### ISSUE TITLE
Update dev container definitions in extension more frequently / "out-of-band"

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#425]
Currently dev container definitions available in the drop down **Remote-Containers: Create Container Configuration File...** and **Open/Reopen Folder in Container** if no devcontainer.jso is present are updated when the extension is released.

These all originate from the open source https://github.com/Microsoft/vscode-dev-containers repository. We keep these up to date and are starting to see some great community contributions as well!

However, these updates will be coming in more frequently than our current update cycle for the extension -- and this difference will increase as the extension stabilizes and we do not need to release patches as often.

We therefore should consider updating the dev container definitions based on the contents of the GitHub repository at least on some periodic basis (e.g. daily). This could be done as simply as an in-place replacement of the assets in the extension for now. An alternative would be to go directly to GitHub to get the definitions each time but this can result in rate limits, so we will need to consider more robust ways we could do this over time as the list gets larger.

**Comment by rubensa** [comment]
Should it be possible to have an option for "live" discovery (possible with a local cache to avoid constantly checking the remote repository and rebuilding the list)?
This would allow to add a configuration for setting an alternative/additional URL for the remote dev-container definitions repository (see: https://github.com/microsoft/vscode-remote-release/issues/4852).

**Comment by Chuxel** [comment]
@rubensa Yes! In fact, this has evolved quite a bit since this point and is actively being discussed here as a general capability of the dev container spec: https://github.com/devcontainers/spec/issues/7

This will allow self-publishing either publicly or privately as well.

**Comment by rubensa** [comment]
:muscle: Great news!  Thanks for the info @Chuxel

**Comment by rubensa** [comment]
see: https://github.com/microsoft/vscode-remote-release/issues/4852#issuecomment-1301833371

**Comment by Chuxel** [comment]
This was just released!  Templates and Dev Container Features now update out of band.

See https://containers.dev/implementors/templates and https://containers.dev/implementors/templates-distribution for info on Templates. Before too long a quick start repo for templates will be available at https://github.com/devcontainers/template-starter 

Out-of-band Dev Container Feature support shipped in the previous iteration. The easiest way to get going on creating custom Dev Container Features is using the https://github.com/devcontainers/feature-template
