### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by yulrizka** [microsoft/vscode-remote-release#4252]
- Issue Type: `Performance`
- Extension Name: `remote-ssh`
- Extension Version: `0.62.0`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.52.0-insider`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by yulrizka** [comment]
I think this might be due to huge host on my .ssh/config file.

**Comment by roblourens** [comment]
What do you mean by "huge"? Maybe it is taking us a long time to parse the ssh config? I know that I do it multiple times which is not efficient.

**Comment by yulrizka** [comment]
yes, my ssh config has a lot of entries. When I try to add an ssh connection, It was just hang and use a lot of cpu resources. Once i start with an empty ssh config it works just fine.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/2857
