### ISSUE TITLE
Explore a 'WSL stub' extension that guides users to install the WSL extension

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#4255]
Creating a public issues to track our progress on the WSL stub extension exploration/implementation.

**Comment by aeschli** [comment]
The VSCode build for Windows now contains the `remote-wsl-recommender` extension. It adds items to the remote menu helping users to install WSL and the Remote WSL extension.
All that is behind experiments, so we can find out what is most useful and user-friendly way to do so.

**Comment by joaomoreno** [comment]
@aeschli Should there be a TPI for this?

**Comment by aeschli** [comment]
I will create one...
