### ISSUE TITLE
Allow selective indexing per folder or a .ignoreindexing instead of just indexing everything from the session root

### ISSUE THREAD

**Issue by MostHated** [microsoft/vscode-remote-release#426]
It would be useful to perhaps have either a .indexignore you can put into the root of folders you don't care to index at the time, or possibly a way to call indexing of specific folders of interest and just ignore those not currently needed for this session. 

I open a root multi project folder and then go to whichever project I am interested in working on from there but sometimes go up a level to look at things and what not, but the initial login ends up doing some pretty hefty indexing off the bat, so it would be nice to try and scope that out to only currently relevant folders somehow.

Thanks,
-MH

**Comment by egamma** [comment]
@MostHated can you describe the setup you are having that is causing problems? What language what extension?

Is this issue specific to vscode-remote or does it apply to vscode in general?

**Comment by MostHated** [comment]
This is VSCode remote. Example is, I open it up, go to the Remote-SSH menu item on the left, select a connection and open it in a new window it will connect and load up. This particular folder is pretty much all Terraform (*.tf) HCL code. When I last opened it, it took probably 5 minutes or so before it finished indexing everything and the console would stutter while typing, so I just had to sit back and wait for it to complete. 

I was under the impression that the indexing was a process related to connecting via VSCode Remote-SSH, I don't recall having seen it before, so I didn't believe it was an extension aside from the Remote-SSH one. Is this not the case and I was mistaken?

**Comment by egamma** [comment]
> it took probably 5 minutes or so before it finished indexing everything

VS Code itself doesn't do any indexing. Do you have extensions installed that do indexing?

VS Code is watching folders for file changes. You can exclude folders from being watched using the setting `files.watcherExclude`. Can you try whether this helps.

**Comment by MostHated** [comment]
Ok, my apologies. I had not seen it happen until I installed and used Remote, so I just assumed it was Remote that was doing it. I will try and see if I can narrow down what ext. is actually doing it and go ahead and close this. 

Thanks!
-MH
