### ISSUE TITLE
Show the progress and speed of copying files to remote server

### ISSUE THREAD

**Issue by BenjaminChoou** [microsoft/vscode-remote-release#4261]
Show the progress and speed of copying files to remote server.

**Comment by chrmarti** [comment]
Which kind of remote is this? Containers?

**Comment by BenjaminChoou** [comment]
> Which kind of remote is this? Containers?

Not a container. 

```
Welcome to NVIDIA DGX Server Version 4.99.11 (GNU/Linux 5.4.0-42-generic x86_64)
```
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

When I drag a file to the remote server, I only got this notification but without progress and speed.

![image](https://user-images.githubusercontent.com/19500127/103877892-a5ec8580-5110-11eb-86e3-be515698b9b8.png)

**Comment by isidorn** [comment]
We already have issue capturing this: that we want to improve our explroer progress
You can find the duplicates here https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+assignee%3Aisidorn+progress+label%3Afile-explorer
