### ISSUE TITLE
Connecting through jumpbox but extensions not working

### ISSUE THREAD

**Issue by ericsanch** [microsoft/vscode-remote-release#4269]
I am connecting to a remote host for development using a jump box in the order local -> jump -> remote. I can successfully connect to 'remote' through 'jump', but debugger extensions seem to not work when connected. I can compile and debug code when SSH'd directly to 'jump' without issue, but when logging into 'remote' I get the following error:

`terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
[Error - 7:59:22 PM] Connection to server got closed. Server will not be restarted.` 

And when I create a hello world test program in 'remote,' I get the following errors the following two errors when attempting to compile and run a program.
`Error: The cppbuild task detection didn't contribute a task for the following configuration:
{
    "label": "C/C++: gcc build active file",
    "type": "cppbuild",
    "command": "/bin/gcc",
    "args": [
        "-g",
        "${file}",
        "-o",
        "${fileDirname}/${fileBasenameNoExtension}"
    ],
    "options": {
        "cwd": "${workspaceFolder}"
    },
    "problemMatcher": [
        "$gcc"
    ],
    "group": {
        "kind": "build",
        "isDefault": true
    },
    "detail": "Task generated by Debugger."
}`

and subsequently
`Could not fin the task 'C/C++: gcc build active file'.` alert with the options of editing the tasks.json or launch.json files (which have been set up for the test project)

The SSH connection to remote is successful because I am able to work with files and even run gcc in the terminal within vscode to compile/run, but the compiler extension doesn't seem to be working with the server.

local os: Mac OS 10.15.7
server os: CentOS 7
VS Code version: 1.52.1
Remote - SSH version: 0.62.0
C/C++ extension version 1.1.3

**Comment by roblourens** [comment]
Please file this issue on the repo for the vscode-cpptools extension:

https://github.com/microsoft/vscode-cpptools/issues

Thanks!
