### ISSUE TITLE
Backlog for WSL1 improvements

### ISSUE THREAD

**Issue by auchenberg** [microsoft/vscode-remote-release#427]
This issues tracks the backlog for improvements for WSL1, given that WSL2 isn't shipping yet.

**Issues:**
- [x] Source Control not showing changed files https://github.com/microsoft/vscode-remote-release/issues/314
- [x] Non-empty folders in the open workspace can't be renamed. Better error messages when failing to rename folder in WSL1 https://github.com/microsoft/vscode-remote-release/issues/208

**Comment by egamma** [comment]
@auchenberg 

>Non-empty folders in the open workspace can't be renamed. Better error messages when failing to rename folder in WSL1

This backlog item doesn't have an issue, please add and link one.

**Comment by auchenberg** [comment]
@egamma Updated.
