### ISSUE TITLE
Opening a Codespace repository with a minimal 'devcontainer.json' file fails

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#4273]
Clone the repository https://github.com/egamma/rock-paper-scissors.git into a volume

![image](https://user-images.githubusercontent.com/172399/103922808-93744b00-5114-11eb-9e12-10c463660828.png)

The `devcontainer.json``

```json
{
    "extensions": ["codespaces-contrib.codeswing", "vsls-contrib.codetour"]
}
```

@chrmarti I thought we handle this case gracefully. Is this a regression?

**Comment by chrmarti** [comment]
This code path isn't covered yet (no regression). Nice sample!
