### ISSUE TITLE
Provide a setting that allows a choice between terminal out put vs. proc filesystem for auto port forwarding

### ISSUE THREAD

**Issue by astrowonk** [microsoft/vscode-remote-release#4274]
- VSCode Version: 1.52.1
- Local OS Version: Windows 10 Enterprise: Version 1709
- Remote OS Version:  RHEL 7
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Run Multiple Python Unit tests via the Python extension.
2. See dozens of port forwardings (presumably from internal python extension usage), one per test, fill the Ports View, in the range of ports 35000-38000
3. open a python http.server on the command line, e.g. `python -m http.server 8080`
4. Port 8080 is not autoforwarded.

3 and 4 used to work with earlier versions of VS Code / Remote. I will continue testing to see if I can revert to a combo where this worked properly. I'm 99% sure I never saw 1/2 happen until sometime in the last few weeks. Auto port forwarding is on in settings.

Does this issue occur when you try this locally?: N/A this is a remote feature.
Does this issue occur when you try this locally and all extensions are disabled?:  N/A

**Comment by alexr00** [comment]
Do  steps 3 and 4 work if you do them without running all the tests?

**Comment by astrowonk** [comment]
> 
> 
> Do steps 3 and 4 work if you do them without running all the tests?

Negative, @alexr00 - even if I don't do any unit tests and just try to open the simple http.server on 8080 in the VS Code terminal on the remote, the port isn't forwarded.  A few weeks ago, this was definitely autoforward the port. (a feature that delighted me at the time!)

**Comment by alexr00** [comment]
@astrowonk thanks for continuing to provide more information! Would you be willing to try VS Code Insiders? Its a nightly build, and I've made a lot of changes in the auto port forwarding recently. I'd like to know if you still see if those changes impact this issue.

**Comment by astrowonk** [comment]
> 
> 
> @astrowonk thanks for continuing to provide more information! Would you be willing to try VS Code Insiders? Its a nightly build, and I've made a lot of changes in the auto port forwarding recently. I'd like to know if you still see if those changes impact this issue.

Hmm, I just tested the Insiders build and Python unit tests aren't working there at all. Like, just nothing not even an error in the Python test log, so also no ports showing up in the Ports section.

And also, auto port forwarding via `python -m http.server 8080` on the terminal is still not working.

**Comment by alexr00** [comment]
Python unit test discovery not working sounds like a bug with the Python extension you have installed. I recommend filing an issue in their repo.

Looks like there might have been a bug in the version of insiders you tried with the `python -m http.server 8080`. I installed version eaa959d34b863dec932077d94daece22504a396b and I saw 8080 get forwarded automatically.

Once the issue with the Python extension not discovering tests is resolved, you can add the following setting to prevent all the extra ports from being forwarded (available in insiders, will be in the next stable release):

```json
	"remote.portsAttributes": {
		"35000-38000": {
			"onAutoForward": "ignore"
		  }
	}
```

Please let me know how that works for you!

**Comment by astrowonk** [comment]
Python discovery is still broken in the latest Insiders. I'll mention this over there.

I'm not having any luck getting 8080 autoforwarded when I install Insiders, and type the python command with http.server.

I also installed the nightly of the SSH Remote.

Version: 1.53.0-insider (system setup)
Commit: eaa959d34b863dec932077d94daece22504a396b
Date: 2021-01-18T05:13:25.733Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.16299

And vs-code remote ssh nightly v2021.1.19621.

**Comment by alexr00** [comment]
Are you running your service on 8080 as superuser? Since VS Code is not running as superuser, that would prevent us from being able to detect that there's anything running on 8080.

**Comment by astrowonk** [comment]
Maybe it's working and just not updating the UI? With insiders + nightly everything, it doesn't immediately show port 8080 forwarded (like it used to), but if I control-click the `http://0.0.0.0:8080/` link in the terminal, it does autoforward and everything works and then 8080 appears in the "Ports" list.

**Comment by alexr00** [comment]
@astrowonk we do all the forwarding when you click on the link too in case you have automatic forwarding turned off. So that at least is expected. If you start your process using a different non-privileged port (maybe 3000?) do you still see it not get auo-detected?

And, sanity check: Is this setting set to true? 	`"remote.autoForwardPorts": true`

**Comment by astrowonk** [comment]
@alexr00 Maybe I'm in some sort of test group? On my Macbook, whether it's nightly+insiders or release versions, I see this pop up after I run `python -m http.server`
<img width="463" alt="Screen Shot 2021-02-01 at 6 47 41 AM" src="https://user-images.githubusercontent.com/13702392/106470266-46af3600-646e-11eb-9669-3cc467bc9b80.png">

but if I try the same thing from windows to a RHEL remote (work machines), I don't see this dialog, the port doesn't show in Ports, not until after I control click-on the link in terminal.

**Comment by alexr00** [comment]
@astrowonk it seems like there's something about RHEL that doesn't let VS Code read the proc filesystem. Having a setting to toggle between using the proc filesystem to find ports to auto forward vs. using terminal output seems like a fair feature request. I think that's probably the best way to solve this issue.

**Comment by astrowonk** [comment]
> 
> 
> @astrowonk it seems like there's something about RHEL that doesn't let VS Code read the proc filesystem. Having a setting to toggle between using the proc filesystem to find ports to auto forward vs. using terminal output seems like a fair feature request. I think that's probably the best way to solve this issue.

Thanks for the reply and explanation @alexr00. Did Remote only recently start trying to use the proc file system to find ports?

**Comment by alexr00** [comment]
Yes, we started using the proc filesystem for port detection with version 1.52. Before that, it was all based on terminal + debug console output.

**Comment by alexr00** [comment]
The new setting is `remote.autoForwardPortsSource`, though this may still change.

**Comment by rzhao271** [comment]
@astrowonk is this issue resolved for you now?
@alexr00 any verification steps?

**Comment by astrowonk** [comment]
Seems to be working as advertised with the remote nightly  and insiders. I switched to using output instead of process.

**Comment by rzhao271** [comment]
Thanks! Marking as verified
