### ISSUE TITLE
Allow for explicitly setting the remote server to work around all the SSH and port forwarding issues

### ISSUE THREAD

**Issue by salexpdx** [microsoft/vscode-remote-release#4275]
I read the titles on all the issues with the SSH tag and didn't see anything like this.  I did see a huge number of people that were having issues that I think could be solved by this feature request being acted on. 

My situation is that I have a windows desktop that due to corporate policy can't have the windows OpenSSH client installed onto it.  I do have a different SSH client that I can use to login and forward ports.   I also have Cygwin which uses open ssh but seems to just hang after the password prompts.  I've tried the UseLocalServer as true and false and neither option provides relief.

The way that I think this feature could be best fixed would be allowing for being able to specify a host and IP address that the VS Code remote plugin can use to make the connection.  At this point, it would be on me to download and setup the VSCode remote server on the linux box, open up a SSH connection with port forwarding and get all that configured and then provide the IP address (localhost) and port # in the settings.

It seems like you are fighting a long battle that you will lose due to the wide variety of system configurations.  For the standard configurations, it's great to have the helpers but for those who don't have standard systems or needs, being able to win by allowing them the flexibility to run what you care about (the vs code remote development server) in different environments will prevent you from the huge list of one off needs.

**Comment by roblourens** [comment]
For this scenario, the remote server/Remote-Tunnels extension are the answer https://marketplace.visualstudio.com/items?itemName=ms-vscode.remote-server
