### ISSUE TITLE
Support opening repositories in containers through URL handling

### ISSUE THREAD

**Issue by CarlosDomingues** [microsoft/vscode-remote-release#4278]
I'm using the [Remote-Containers](https://code.visualstudio.com/docs/remote/containers) extension to share ready-to-use development environments with my team. 

As described in the [documentation](https://code.visualstudio.com/docs/remote/containers#_quick-start-open-a-git-repository-or-github-pr-in-an-isolated-container-volume), it's now possible to open a remote repository by using the **Remote-Containers: Clone Repository in Container Volume** command.

It would be really cool if we had badge in our repos like so: https://img.shields.io/badge/Launch%20Project-VS%20Code-purple

Then my developers would just click on it and open the project in VS Code, in a ready-to-use environment.

Related to microsoft/vscode#4883. 

The badge could link to something like:

vscode://open?url=https://github.com/microsoft/vscode.git?command=remote-containers-clone-repository-in-container-volume

**Comment by joaomoreno** [comment]
It might be yeah... we'd have to try it out.

**Comment by egamma** [comment]
The URI handler is now available in insiders and will be in stable once 1.58 ships.
The syntax is `vscode-insiders://ms-vscode-remote.remote-containers/cloneInVolume?url=https://github.com/microsoft/vscode-remote-try-python`

**Comment by CarlosDomingues** [comment]
Thanks, I've been using this feature to open Gitpod locally for a while. We can close this issue.
