### ISSUE TITLE
code command is missing in the integrated terminal

### ISSUE THREAD

**Issue by Diluka** [microsoft/vscode-remote-release#4279]
- VSCode Version: 1.52.1
- Local OS Version: windows/mac
- Remote OS Version: wsl/linux
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1. open integrated terminal
2. type code <path/to/the/file> --> something like `Command 'code' not found, did you mean:`

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by aeschli** [comment]
That works for me.
What is `env | grep PATH` showing?

**Comment by Diluka** [comment]
> That works for me.
> What is `env | grep PATH` showing?

in wsl
```
diluka@Diluka-Z7:~$ code

Command 'code' not found, did you mean:

  command 'cde' from deb cde (0.1+git9-g551e54d-1.1build1)
  command 'cdde' from deb cdde (0.3.1-1build1)
  command 'tcode' from deb emboss (6.6.0+dfsg-7ubuntu2)
  command 'ode' from deb plotutils (2.6-10build1)
  command 'node' from deb nodejs (10.19.0~dfsg-3ubuntu1)

Try: sudo apt install <deb name>

diluka@Diluka-Z7:~$ env | grep PATH
PATH=/home/diluka/.nvm/versions/node/v12.20.0/bin:/opt/graalvm-ce-java8-20.2.0/bin:/vscode/vscode-server/bin/x64/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by Diluka** [comment]
@aeschli thx, I found the problem. Once I tried the `graalvm` extension, it set the `PATH` env in `settings.json` `terminal.integrated.env.linux`. This is override the real one on remote host.

**Comment by aeschli** [comment]
@Diluka Thanks for figuring it out!
