### ISSUE TITLE
Broken font for remote terminal 

### ISSUE THREAD

**Issue by razhangwei** [microsoft/vscode-remote-release#428]
Issue Type: <b>Bug</b>

When open the remote terminal, the font was broken, and the issue would disappear if I change the color theme. 

Extension version: 0.37.0
VS Code version: Code - Insiders 1.35.0-insider (955afd60a5e4177d1fdf1c3a4a02dc4e0ca7d781, 2019-05-22T18:03:07.494Z)
OS version: Darwin x64 18.5.0
Remote OS version: Linux x64 3.10.0-957.12.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: nebula-9|
|OS|Linux x64 3.10.0-957.12.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz (24 x 2393)|
|Memory (System)|125.74GB (108.50GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment]
@razhangwei please provide more details on how the font was broken. Add a screenshot that illustrates the problem. Which color theme did you use that exposed the problem.
