### ISSUE TITLE
How to module load on HPC

### ISSUE THREAD

**Issue by lonelykid** [microsoft/vscode-remote-release#4280]
🚨 The issue tracker is not for questions 🚨
This has been brought up in https://github.com/microsoft/vscode-remote-release/issues/2982, https://github.com/microsoft/vscode-remote-release/issues/690, https://github.com/microsoft/vscode-remote-release/issues/1722. The module I'm testing is texlive, and I'm using the plugin Latex workshop. What I have tried:
1. ``"terminal.integrated.shellArgs.linux": ["-c", "module load texlive"]`` This seems not work. module command is not found
2. Module seems to be a function.
````
$ where module
module () {
        eval $($LMOD_CMD zsh "$@") && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}
````
I tried
``"terminal.integrated.shellArgs.linux": ["-c", "eval $(/usr/share/lmod/lmod/libexec/lmod /usr/bin/zsh load texlive); exec $SHELL -l"]``. ``exec $SHELL -l`` is necessary, otherwise the terminal will exit after executing. This works for the terminal. But not for the extensions.
3. Adding to ``.zshrc`` or ``.zshenv`` works. But this is less flexible.

Then I realize the shellArgs is only run when terminal is openned, not at ssh connnection. That's why the extensions does not have the PATH. **So the question is: how can we specify commands to be run at ssh connection for each project?** Then we can use ``export PATH`` or ``module load`` to set correct environment. Adding to RemoteCommand in ssh config also works. But it's not very convenient to manage in different projects and you have to be careful cuz RemoteCommand is run before the environment is set up. Something like ``remote.SSH.runAtConnection:~~~`` would be nice to have.

If you have a question about VS Code, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code and about
VS Code Remote on https://stackoverflow.com/questions/tagged/vscode-remote.

**Comment by lonelykid** [comment]
I got method 2 working by adding ``exec $SHELL -l``. But latex workshop still does not recognize it. I'm still looking into it. This might be a Latex workshop issue.

**Comment by roblourens** [comment]
"at ssh connection for each project" is hard because we have to make the ssh connection before we know what project you are using.

I think this is generally covered by #1722 though. Although I think it's unlikely that we will be able to do a per-workspace solution. There is no definition of workspace or workspace settings until we have connected to your remote, and at that point, it is to late for what you want.
