### ISSUE TITLE
Remote Development Hangs in Confirming Reachability

### ISSUE THREAD

**Issue by 1600** [microsoft/vscode-remote-release#429]
Issue Type: <b>Bug</b>

just configure a SSH host config, and connect via Remote - SSH : Connect to Host...  then it stuck forever validating host reachability.

Extension version: 0.14.0
VS Code version: Code - Insiders 1.35.0-insider (955afd60a5e4177d1fdf1c3a4a02dc4e0ca7d781, 2019-05-22T18:07:55.791Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sfodor2** [comment]
I set the ssh keys and it worked

**Comment by mjacksonlgh** [comment]
I set my ssh keys and still have issues.

This is the last line in the 'remote - ssh' log:
Running type "C:\Users\MJ\DOCUME~1\MobaXterm\slash\var\log\xwin\vscode-linux-multi-line-command-mars.sh" | ssh  mars to confirm the host platform

'uname' is the only content in the .sh file.

If I open a cmd window, the command appears to work from there.  If I just run 'ssh mars' I can ssh in to the box fine.  It's Ubuntu LTS 18.04 on AWS.

**Comment by mjacksonlgh** [comment]
If I launch code-insiders from the Ubuntu app/CLI, it works!  It just doesn't work from MobaXterm, our preferred CLI.

Hope it helps.

**Comment by roblourens** [comment]
Please everyone open your own issues. @1600 can you share the full log from the "Remote - SSH" output channel?

**Comment by sfodor2** [comment]
My issue was fixed with a reinstall.

Thanks

**Comment by wallacepreston** [comment]
@sfodor2 You reinstalled VS Code and simply typing in your `<username>@<hostname>` worked?  I am getting the same error of it hanging at "Confirming that ... is reachable"

**Comment by roblourens** [comment]
Closing this issue as the OP hasn't responded. Please everyone open your own issues with logs.
