### ISSUE TITLE
Lack of GLIBCXX_3.4.22 on Ubuntu 16.04 for ARMv7l

### ISSUE THREAD

**Issue by tysonite** [microsoft/vscode-remote-release#4290]
#3857 described an original issue I found on ARMv7. I was not able to test fix till now, but I see that the behavior is the same with vs code 1.52.1. uriTransformer.js uses 100% CPU and spdlog.node still requires GLIBCXX_3.4.22:

```
~/.vscode-server$ ldd ./bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node_modules/spdlog/build/Release/spdlog.node
./bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node_modules/spdlog/build/Release/spdlog.node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node_modules/spdlog/build/Release/spdlog.node)
        linux-vdso.so.1 =>  (0xbedce000)
        libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0xb6e7a000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb6e02000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb6dda000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb6db6000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6cca000)
        /lib/ld-linux-armhf.so.3 (0xb6fcd000)
```

Not sure if the fix was released, though. My vs code has those versions:

![image](https://user-images.githubusercontent.com/196535/104185437-06880500-5426-11eb-81c2-a3042b40c541.png)

_Originally posted by @tysonite in https://github.com/microsoft/vscode-remote-release/issues/4103#issuecomment-757935086_

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/2998
