### ISSUE TITLE
Port forwards will die and cannot be recreated without restarting the server

### ISSUE THREAD

**Issue by richardpringle** [microsoft/vscode-remote-release#4291]
Issue Type: <b>Bug</b>

Port forwards stop working such that requests just hang. The SSH connection in the terminal works fine. Files are properly saved, etc. This is really annoying because I have to restart the server (and kill all my existing connections/terminal sessions)

Extension version: 0.61.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0
Remote OS version: Darwin x64 19.6.0
Remote OS version: Darwin x64 19.6.0
Remote OS version: Darwin x64 19.6.0
Remote OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 3|
|Memory (System)|32.00GB (5.45GB free)|
|Process Argv|--crash-reporter-id 48f1cbb2-3f64-41ef-a90c-8fa613b179ce|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: kmac|
|OS|Darwin x64 19.6.0|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|Memory (System)|32.00GB (1.22GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: kmac|
|OS|Darwin x64 19.6.0|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|Memory (System)|32.00GB (1.22GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: kmac|
|OS|Darwin x64 19.6.0|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|Memory (System)|32.00GB (1.22GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: kmac|
|OS|Darwin x64 19.6.0|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|Memory (System)|32.00GB (1.22GB free)|
|VM|0%|
</details>

**Comment by richardpringle** [comment]
This happens with both regular port-forwards as well as over sockets. I also tried opening up a second port forward to the same port from a different window (uses a different local port) and that didn't work either.

**Comment by roblourens** [comment]
What type of remote is this? How are you setting up the port forwards? And removing and re-adding the forward doesn't work?

**Comment by richardpringle** [comment]
It's an SSH remote? All the info should be in the ticket. It's a Mac connecting to another Mac.

I try adding and removing port forwards and it doesn't help. Adding new port forwards also doesn't work.

This generally happens after a certain amount of time (say 24h) without use. It wouldn't be a problem if I didn't have to restart the server and re-establish all of my ash connections and terminals, etc. 

The logs don't tell me much either.

**Comment by alexr00** [comment]
How are you forwarding the ports?

**Comment by richardpringle** [comment]
`Cmd + p` -> `>Forward a Port` -> type the port to forward

**Comment by richardpringle** [comment]
Yeah, it's still there.

**Comment by alexr00** [comment]
Will investigate further in February.

**Comment by alexr00** [comment]
@richardpringle I'm trying to repro this, and I haven't had any luck yet (it's slow going as just checking in every couple hours to see if a forwarded port is still working). Is this still an issue you see with the latest release?

**Comment by richardpringle** [comment]
@alexr00, I actually haven't run into this for a couple of weeks. And it's also difficult for me to reproduce. If you want, you can close this and I'll re-open it if I run into the issue again.

It definitely wasn't just a problem with the old version as I went through a couple of versions experiencing the issue, but I haven't seen it in a while. 

The main issue is that it's really difficult to debug.

**Comment by alexr00** [comment]
@richardpringle thanks for the reply. There have been a few changes that impact the port forwarding mechanism since 1.51.1, so  it would make sense that the behavior changed. I'll close this for now, but yes, please do re-open or ping this issue if you start seeing it again.
