### ISSUE TITLE
command 'opensshremotes.openEmptyWindow' not found

### ISSUE THREAD

**Issue by Hentze0808** [microsoft/vscode-remote-release#4293]
Hi

I am still facing this issue. I have tried to uninstall the add-on and VSC it self, without any luck.

This happens when pressing F1 and selecting "Remote-SSH: Connect to Host..."

Any help would be aprecheated.

/Ragnar

Very strange, if this is still an issue, can you tell me where you click the command when you see this?

_Originally posted by @roblourens in https://github.com/microsoft/vscode-remote-release/issues/3473#issuecomment-723222610_

**Comment by Ainevsia** [comment]
same here

**Comment by roblourens** [comment]
Could you try again with the latest version of insiders? https://code.visualstudio.com/insiders

If it still happens, could you share a screenshot, and check for errors in the devtools (Help > Toggle Developer Tools)

**Comment by jpear1** [comment]
I had this same problem, using insider's edition allowed me to connect properly.

**Comment by roblourens** [comment]
Thanks for confirming

**Comment by jpear1** [comment]
Actually, I tried this with VSCode stable (1.52.1) and didn't encounter the problem. It only exists in the OSS build (ver 1.52.1, installed from https://archlinux.org/packages/community/x86_64/code/).

**Comment by roblourens** [comment]
VS Code Remote is only supported with the official builds, not OSS builds.

**Comment by 0m4r** [comment]
I have got the same on OSX and VSCodeInsider.
I am not quite sure it was related, but I solved it with this answer (adapting it to VSCodeInsider, of course)

https://github.com/microsoft/vscode/issues/7426#issuecomment-425093469
