### ISSUE TITLE
Remote SSH fails after 10 minutes then fails to reconnect for AWS EC2 Linux

### ISSUE THREAD

**Issue by CKozanecki** [microsoft/vscode-remote-release#4294]
- VSCode Version: 1.52.1
- Local OS Version: Windows 10 Enterprise 18363
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Create a micro instance of  Ubuntu 20.04 in AWS EC2
2. Connect to the instance from Windows Machine running VSCode remote SSH
3. Start up docker container on remote server for Mongo DB
4. Start writing application to talk with Mongo DB container
5. after 10 minutes of writing code, find Remote SSH disconnects
6. Can no longer connect to remote computer with VSCode Remote SSH
7. Can still SSH to machine from Powershell or WSL

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
From past user reports it seems that micro instances are generally too underpowered to run VS Code Remote. You probably just need more CPU/RAM
