### ISSUE TITLE
SSH: Cannot reconnect to Windows Server

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-remote-release#4298]
( I am trying to reproduce #4287 )
```
Version: 1.53.0-insider
Commit: 9bfa4c1d55892571b5936599fd628a5bfb9ac1db
Date: 2021-01-13T09:37:16.215Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Darwin x64 19.6.0
----
Remote - SSH extension version 0.62.0
```

* connect to a Windows server
* disconnect the network connection
* the vscode server is killed immediately
* when the network is repaired, a new vscode server is spawned and reconnection fails

https://user-images.githubusercontent.com/5047891/104505834-cde25a00-55e4-11eb-8f9e-6e63ed8f6d82.mp4

**Comment by roblourens** [comment]
I see this too, I know it worked at some point because it took a lot of work, the remote server is supposed to be spawned detached from the install script, and that is not happening anymore.

> On Windows, Start-Process creates an independent process that remains running independently of the launching shell. 

And it's clearly not detached

**Comment by roblourens** [comment]
Oops. This was a dumb powershell issue from a missing `global:`, I'm embarrassed that it was around for awhile but there are relatively very few users on windows servers vs linux.
