### ISSUE TITLE
Document the 'workspaceMount' attribute

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#430]
pls see https://github.com/microsoft/vscode-remote-release/issues/41#issuecomment-495075283

Let's also add an example for how to use to address https://twitter.com/connorjshea/status/1131403001170518016

//CC @chrmarti

**Comment by connorshea** [comment]
I'm currently stumped on how to use this since I can't figure out how to give the attribute my present working directory (short of hardcoding it, I guess)

**Comment by Chuxel** [comment]
@egamma This particular issue (#41) is not fully supported by just adding the workspaceMount option.  We need to support using `${workspaceFolder}` (#306) to really get this to work.  I reopened #41 and will hold off documenting that until we can make a good reccomendation for how that would work.

However, it does support the remote case much better (#171), so I'm adding the property and refining the remote docs.

**Comment by Chuxel** [comment]
Documented https://github.com/microsoft/vscode-docs/commit/e09e4f5da471a5b4dcb62c78353d26574a5fedd4

Will update once #41 (and/or #306) are closed.

**Comment by connorshea** [comment]
Thanks!
