### ISSUE TITLE
Documentation to allow Remote-SSH SendEnv / SetEnv environment variables

### ISSUE THREAD

**Issue by johnorourke** [microsoft/vscode-remote-release#4301]
Resolves #2344 and #836 to allow Windows local environment variables to be inherited by the remote connection, specifically GIT_AUTHOR_EMAIL, GIT_AUTHOR_NAME, but also 'DISPLAY' if you're running remote X11 clients etc so it could replace this extension: https://github.com/joelspadin/vscode-remote-x11

(Documentation change request)

By upgrading the Windows ssh client from OpenSSH 7.x to OpenSSH 8.x, you get support for the "SendEnv" and "SetEnv" SSH commands.  To successfully set an environment variable on your Windows client, that gets inherited by a Remote-SSH VS Code connection:

(tested with Windows 10 build 19042)

* upgrade OpenSSH on your Windows 10 machine:
  * via "Manage Optional Features", remove the OpenSSH client (it's v7.x) - reboot to remove it fully
  * download the x32 or x64 version from https://github.com/PowerShell/Win32-OpenSSH/releases (build 8.x)
  * extract it into C:\Program Files\OpenSSH\ (might need to start Explorer as Administrator)
  * add it to your Path:
    * open "Edit the System Environment Variables" and click Environment Variables
    * under "System variables", edit "Path" and
    * add a new one for "C:\Program Files\OpenSSH\"
  * open a Windows command prompt and run "ssh -V" and see that you're now on version 8.x
* Set any environment variables you want to send:
  * open "Edit the environment variables for your account"
  * click New to add each one that you need (eg. GIT_AUTHOR_NAME, GIT_AUTHOR_EMAIL, GIT_COMMITTER_NAME, GIT_COMMITTER_EMAIL, DISPLAY, ...)
* in VS Code, add a Remote-SSH connection:
  * follow the instructions to add a new host, if you haven't already: https://code.visualstudio.com/docs/remote/ssh
  * open the ssh config (F1,then "Remote-SSH: Open Configuration File...")
  * add the setting "SendEnv GIT_*" (put your environment variables here, space-separated, wildcards allowed)
* on the remote server:
  * edit `/etc/ssh/sshd_config` as root, and change the AcceptEnv line to include your new variables (eg. `AcceptEnv LC_* GIT_*`)
  * restart the ssh daemon eg. `service sshd restart` assuming it's a Linux host

Usage notes:
* if you change the Windows variables, you'll need to [a] kill the remote VS Code host using the "Remote-SSH:  Kill VS Code Server on Host..." command, AND [b] fully close and re-open VS Code
* if you connect but the VS Code server is already running on the remote, it won't inherit your variables - use the "Remote-SSH: Kill VS Code Server on Host..." command after you connect, and choose the "Reconnect" option

**Comment by johnorourke** [comment]
@dannyalan @roblourens  @mlcdf just mentioning FYI because the related tickets are closed.

**Comment by roblourens** [comment]
Thanks, but this is a documentation change request for what exactly?

**Comment by johnorourke** [comment]
Hi @roblourens , I think it could be documented either

* here: https://code.visualstudio.com/docs/remote/ssh
* or here: https://code.visualstudio.com/docs/remote/troubleshooting#_installing-a-supported-ssh-client

**Comment by roblourens** [comment]
These steps do not really seem specific to VS Code, this is more about windows SSH and that feature in general, so I don't think that is the right place for them. They are now searchable in our issue tracker at least. Thanks for sharing.
