### ISSUE TITLE
vscode  ext  remote-WSL ,  terminal open error

### ISSUE THREAD

**Issue by GSRLW** [microsoft/vscode-remote-release#4303]
版本: 1.52.1 (user setup)
提交: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
日期: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

名称: Remote - WSL
ID: ms-vscode-remote.remote-wsl
说明: Open any folder in the Windows Subsystem for Linux (WSL) and take advantage of Visual Studio Code's full feature set.
版本: 0.52.0
发布者: Microsoft
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl

WSL:  Linux XXXX 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Fedora-Remix-for-WSL_31.5.0.0_x64_arm64.appxbundle

When I installed my new WSL environment, everything was fine when I first installed it, and the Vscode environment can run normally. But today, it was discovered that there was a problem again, and an error was reported when opening the terminal under the WSL environment. This error indicates that some environment in the terminal has been changed. Another problem is that in some cases this problem will cause the C++ extentions to fail to open the debug mode and fail to debug. (This problem is not reproduced here temporarily) So I hope to ask you how to deal with this error so that there is no error.

![image](https://user-images.githubusercontent.com/35130268/104557088-9bd00700-567b-11eb-9c96-b1bd28b3b15a.png)

**Comment by GSRLW** [comment]
this question show sometimes ,   but I don't know ..
this is my .bashrc file
![image](https://user-images.githubusercontent.com/35130268/104562446-557ea600-5683-11eb-8dc5-210162ff7055.png)

if need more files ,  I will find and show...

**Comment by bamurtaugh** [comment]
Hey @GSRLW - I believe the error you're showing is due to some contents of the .bashrc file. Should your first `then` be moved to the next line? Do any of the suggestions here help? https://stackoverflow.com/questions/10496758/unexpected-end-of-file-and-error-importing-function-definition-error-running https://github.com/drush-ops/drush/issues/2065#issuecomment-227820550
