### ISSUE TITLE
Resolvers are running even if they are disabled

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-release#431]
- Open a remote window (WSL or SSH or Dev Container) - I used SSH.
- Disable the respective remote extension (SSH)
- Reload the window
🐛 SSH connection is established

**Comment by rebornix** [comment]
I'm still seeing this issue with the steps @sandy081 described above for both SSH and Container.

**Comment by sandy081** [comment]
Moving this to June

**Comment by joaomoreno** [comment]
@egamma Given the existence of nightly versions of our own remote extensions, this is now more relevant. See https://github.com/microsoft/vscode-remote-release/issues/652

@jrieken @sandy081 I wonder if any of you would pick this up?

**Comment by sandy081** [comment]
Will look into this.

**Comment by RMacfarlane** [comment]
I'm still seeing the same behavior with the original steps
