### ISSUE TITLE
Linux SLES 11 SP4 x86_64: architecture unsupported

### ISSUE THREAD

**Issue by HectorB-2020** [microsoft/vscode-remote-release#4312]
- Extension version: 0.62.0
- VSCode Version: 1.52.1, Electron 9.3.5, Node.js 12.14.1
- Local OS Version: Windows Server 2012R2
- Remote OS Version: Linux SLES 11 SP4 x86_64
- Connection Type: SSH Reflection for Secure IT 7.2.1.99 on x86_64-suse-linux-gnu (64-bit)

Steps to Reproduce:

1. Ctrl-Shift-P - Remote-SSH: Connect to Host...
2. Select previously added host or create new record
3. Answer Linux for "platform"
4. Enter password
5. Error: Could not establish connection to "host.domain": The remote host's architecture is not unsupported.

Some errors from OUTPUT window:

`sed: invalid option -- 'E'`
 ... followed by sed's command line help.

Received install output:
```
exitCode==27==
listeningOn====
osReleaseId==sles==
arch====
tmpDir==/tmp==
platform==linux==
unpackResult====
didLocalDowload==0==
dowloadTime====
installTime====
extInstallTime====
serverStartTime====
```

```
[timestamp] Unsupported architecture 
[timestamp] The remote host's architecture is not unsupported
  at Function.ServerInstallError (c\Users\...\extension.js:1:64207)
  at (c\Users\...\extension.js:1:61973)
...
```

Windows ssh command line is able to establish conection to the same host, password is accepted, remote shell is working.

The same VS Extension (0.62.0) works normally for other remote SLES systems with OpenSSH servers installed.

Can this be incompatibility with different remote SSH server?
SSH: Reflection for Secure IT

**Comment by roblourens** [comment]
Seems like your version of `sed` doesn't support the `-E` flag and this is breaking code I run to check the architecture. Do you know where this came from or why that would be? I can rewrite this to avoid that particular flag but I'm afraid we'll just run into another issue down the line.

**Comment by HectorB-2020** [comment]
```
/usr/bin/sed --version
GNU sed version 4.1.5
````
And yes, `sed --help` does not produce `-E`.

The other machine where this works has newer sed v4.4.
It prints `-E` among other command line parameters indeed.

But both the old and the new support `-r` or `--regexp-extended`.

**Comment by roblourens** [comment]
That looks like a fairly old version of sed, right? The help text says `for portability use POSIX -E` and sed for mac does not have `-r`. I don't want to add a workaround just for sed here, I suspect you would hit another issue later in the script, eg I've also had issues with older versions of tar not liking our tar archive. So I think I just have to say that this isn't supported, sorry.

**Comment by HectorB-2020** [comment]
Unfortunately sed v4.1.5 is the latest available version for SLES 11 SP4.

I wonder what other command line tools are needed?

**Comment by roblourens** [comment]
Ok. If it's not sed or tar then it's going to be the glibc version or something else. https://code.visualstudio.com/docs/remote/linux Sorry

**Comment by roblourens** [comment]
Actually I decided to experiment with fixing this, see https://github.com/microsoft/vscode-remote-release/issues/3129#issuecomment-766533868 and let me know if it works for you.

**Comment by HectorB-2020** [comment]
Thank you very much indeed! What exact version should it be to try?

**Comment by roblourens** [comment]
`v2021.1.35460`
