### ISSUE TITLE
SSH shouldn't ask for password again after switching folders

### ISSUE THREAD

**Issue by k2l8m11n2** [microsoft/vscode-remote-release#4313]
If I'm already connected to a server and open another folder on the same server, the window always reloads and asks me for the SSH password again. Can we reuse the existing connection so I don't need to reauthenticate every time?

**Comment by roblourens** [comment]
You can set `"remote.SSH.useLocalServer": true` in your settings.json to enable this, it is disabled by default on windows.

**Comment by k2l8m11n2** [comment]
I have it enabled and it still reloads the windows and asks for my password every time I switch folders.

**Comment by roblourens** [comment]
Could you share the log from the Remote-SSH output channel from the second window after doing that?

- Open a remote window
- Open a different folder on the same remote host, asks for pw when it shouldn't
- Share the log from this second window

**Comment by k2l8m11n2** [comment]
It appears that the actual issue is with the settings GUI. I noticed in the log that it still said `"remote.SSH.useLocalServer": false` despite the checkbox being checked so I added it to the config manually. That fixed the issue I originally had. It seems as if the GUI thinks that the `useLocalServer` default is `true` so it doesn't add the setting to the config file.

**Comment by roblourens** [comment]
This is just due to the way the default is applied on windows, unfortunately. It has to be configured as "true" in json. Should be cleared up soon. Thanks for finding that.
