### ISSUE TITLE
Test remote.portsAttributes

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#4317]
Refs: https://github.com/microsoft/vscode-remote-release/issues/4046

- [x] macOS @RMacfarlane
- [x] linux @connor4312
- [x] windows @aeschli

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%234317%0A%0A)

---

1. Read the description of the setting `remote.portsAttributes`. Verify that it is clear.
2. Verify that you can set a label for a single port number.
3. Verify that you can set a label for a range of ports (not an expected scenario, but it should still work).
4. Verify that you can set an `onAutoForward` option for a single port number. Try all the options. Verify that the descriptions make sense and that they work the way you'd expect.
5. Do not verify the `elevateIfNeeded` property, since no one supports elevating yet.
6. Verify that setting multiple ranges and/or single ports works. 
7. Verify that if you set a range and a single port within that range, that the properties are merged (single port settings get priority).

**Comment by rebornix** [comment]
On the linux environment I have, I'm currently seeing https://github.com/microsoft/vscode-remote-release/issues/4384 which blocked the testing cc @chrmarti
