### ISSUE TITLE
Open the folder in container via the Code command

### ISSUE THREAD

**Issue by ZackTherrien** [microsoft/vscode-remote-release#4318]
There is a feature in VSCode to open the current folder/file in VSCode via the `code` command.

Ex: `code .` opens the current folder in VSCode.

The problem however is that doing so opens the folder in a regular VSCode window.

I'd like to either specify a command line option to automatically open the folder in a docker container if the folder contains a `.devcontainer` folder, or to automatically open the container without being prompted.

An example option could be `code --in-container .`

**Comment by chrmarti** [comment]
Tracked with https://github.com/microsoft/vscode-remote-release/issues/2133.
