### ISSUE TITLE
Remote-SSH Error : version mismatch, client refused (Insiders 1.53)

### ISSUE THREAD

**Issue by guidiandrea** [microsoft/vscode-remote-release#4320]
- VSCode Version: 1.53.0 Insiders
- OS Version: Windows 10

I'm trying to connect to a remote machine via ssh. I'll first say that I was able to connect to that machine with VSCode 1.52 but I wanted to use Jupyter Notebooks from VSCode insiders so I installed it.

Steps to Reproduce:

1.  Command Palette -> Remote-SSH: Connect to Host (Linux)
2.  I get an error: Failed to connect to the remote extension host server (Error: Connection error: Version mismatch, client refused.)

I got the vscode-server version from: 
https://update.code.visualstudio.com/latest/server-linux-x64/stable

Maybe the version's not correct?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by guidiandrea** [comment]
The remote machine I’m working with has no Internet connection so we install the server manually. And it worked before.



Inviato da myMail per iOS


lunedì 18 gennaio 2021, 20:01 +0100 da notifications@github.com  <notifications@github.com>:

**Comment by roblourens** [comment]
In that case, the extension will download the correct server on the client side and transfer it to the remote. If that isn't working, please share the log from the Remote-SSH output channel. If the client is offline too, then that is covered by this issue: https://github.com/microsoft/vscode-remote-release/issues/1242
