### ISSUE TITLE
Remote server pollutes audit logs: "unsuccessfully opened-file /proc/19/fd"

### ISSUE THREAD

**Issue by cipri-tom** [microsoft/vscode-remote-release#4321]
I am in the stance of being both user and sysadmin of our boxes. I've had some failures recently due to audit logs getting full. Upon closer inspection, I noticed thousands of messages like this:

```
At 11:16:37 01/19/2021 ciprian unsuccessfully opened-file /proc/34066/fd using /bin/dash
At 11:16:37 01/19/2021 ciprian unsuccessfully opened-file /proc/34195/fd using /bin/dash
At 11:16:37 01/19/2021 ciprian unsuccessfully opened-file /proc/34416/fd using /bin/dash
At 11:16:37 01/19/2021 ciprian unsuccessfully opened-file /proc/34978/fd using /bin/dash
At 11:16:37 01/19/2021 ciprian unsuccessfully opened-file /proc/35127/fd using /bin/dash
At 11:16:37 01/19/2021 ciprian unsuccessfully opened-file /proc/35890/fd using /bin/dash
At 11:16:37 01/19/2021 ciprian unsuccessfully opened-file /proc/36240/fd using /bin/dash
At 11:16:37 01/19/2021 ciprian unsuccessfully opened-file /proc/36325/fd using /bin/dash
```

They come in batches of about 516 (+/- 4), and a batch is logged every 2 seconds. 

This is happening consistently across 2 different machines when the VSCode Remote window is open. They stop after I close the VSCode remote window.
 
My colleague using VSCode version 1.47.3 does not generate such messages.
We both have the same extensions installed remotely:
 - Python
 - PyLance
 - vscode-pdf
 
In addition, I also have the Jupyter extension, but I don't have any jupyter file opened or even in the project directory.

What could be generating these messages ?

---

- VSCode Version:  1.52.1
- Local OS Version: MacOS 10.15.7
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to a remote SSH server 
2. Watch the audit file

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by alexr00** [comment]
The VS Code remote process looks at your proc filesystem to try to find ports to automatically forward for you. If you upgrade to version 1.53, then you can turn this feature off using the setting `remote.autoForwardPorts`. This setting exists in 1.52.*, however, it doesn't fully turn off the port detection, so I expect that your logs would still fill up unless you have version 1.53.*

**Comment by cipri-tom** [comment]
Indeed, this solved it ! Thank you !

**Comment by cipri-tom** [comment]
@alexr00 is there a way to control this for everyone on a server ? After I went and told every user of the server to turn upgrade and turn off the setting, a new user came, forgot to tell them, and again filled up the logs and disabled the machine (it's enough that they leave VS code open during the weekend).

We'd be really grateful if we could disable this behaviour server side. It really looks like a rogue process trying to DOS the audit process.

Thanks a lot !

**Comment by alexr00** [comment]
VS Code doesn't have a concept of system wide settings, they're all per user or per workspace. Are all the users on your server using the same source controlled project? If so, you could could set `remote.autoForwardPorts` as a workspace setting then commit that settings change to your repo. https://code.visualstudio.com/docs/getstarted/settings#_creating-user-and-workspace-settings
