### ISSUE TITLE
PR in volume: Cannot open PR description / file diffs

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#4322]
Issue Type: <b>Bug</b>

I cannot open PR description / file diffs from the PR viewlet:

![image](https://user-images.githubusercontent.com/9205389/105053188-f8169a80-5a70-11eb-99ff-3446ac4a6fc7.png)

The `origin` remote points at the fork, when I manually changed that to point to the main repository, it started working.

Extension version: 0.154.2
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.4.39-linuxkit

**Comment by egamma** [comment]
@chrmarti 

When this happens, do you see the status bar item from the GHPR extension that shows the PR under review?
<img width="580" alt="image" src="https://user-images.githubusercontent.com/172399/105524201-9ad45080-5cdf-11eb-932b-163422f224b6.png">

Is the repository you have tried owned by an org, e.g., 'microsoft' or a personally owned repository (there is known limitation with PRs an org owned repositories). If yes, can you reproduce the problem with a personally owned repository?

**Comment by chrmarti** [comment]
Yes, that status bar item is there. I'm using https://github.com/chrmarti/vscode-regex/pull/43.

**Comment by egamma** [comment]
Problem confirmed when using the GHPR extension locally then the origin points to the main repository

<img width="460" alt="image" src="https://user-images.githubusercontent.com/172399/105574622-11b42c80-5d66-11eb-9e3f-11d899542826.png">

When reviewed in a container, then the origin points to the fork
<img width="553" alt="image" src="https://user-images.githubusercontent.com/172399/105574656-3b6d5380-5d66-11eb-8438-60e6865e8507.png">
