### ISSUE TITLE
EPERM: operation not permitted, open

### ISSUE THREAD

**Issue by VenRoot** [microsoft/vscode-remote-release#4323]
- VSCode Version: 1.52.1
- Local OS Version: Win10 20H2 (Build 19042.746)
- Remote OS Version: debian 9.12
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install the Remote - SSH Package
2. Try to connect

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes (with all, but the required SSH Package)

I just installed VSCode to try it out. I used Atom with the remote-ftp Package, I found the similar package "Remote - SSH" Package quickly in VSCode and installed it.

Then, when I added my remote and tried to connect, I instantly got this message
![Screenshot 2021-01-19 230706](https://user-images.githubusercontent.com/39433121/105099184-89a2fe00-5aab-11eb-9b7b-67d4efd83a91.jpg)

After that I tried to connect using PS. Then I instantly noticed that PS isn't allowed to access my ssh-config anymore, which never happened before, so it had to be VSCode corrupting the permissions somehow.
![Screenshot 2021-01-19 230804](https://user-images.githubusercontent.com/39433121/105099245-a6d7cc80-5aab-11eb-8b01-532a19e77c73.jpg)

I looked for a solution, why I can't even ssh from the terminal anymore and found out, that I'd have to disable inheritance and remove any other user except me from the permissions. So I did and that fixed it for the terminal, but NOT for VSCode. I'm the owner of that directory with full permissions.

I hope I can help with that

Sincerly
Ven

**Comment by roblourens** [comment]
Sorry for the trouble, but vscode does not change your ssh config permissions, so I'm not sure what happened. The windows SSH wiki has some notes about file permissions here https://github.com/PowerShell/Win32-OpenSSH/wiki/Security-protection-of-various-files-in-Win32-OpenSSH, and a utility script for fixing permissions here https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/openssh/FixUserFilePermissions.ps1, hope that helps
