### ISSUE TITLE
Terminal not working when connecting to remote linux host from windows

### ISSUE THREAD

**Issue by Nand087** [microsoft/vscode-remote-release#4324]
Issue Type: <b>Bug</b>

1. Attempt to connect to one of your SSH targets from a Windows host.
2. This is what I see on the terminal panel.
``` 
Checking server status on port 35679 with wget
7add9b3fc6c4: start
sshAuthSock====
webUiAccessToken====
listeningOn==35679==
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1001==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
7add9b3fc6c4: end
```
3. On the right side of the terminal, under the drop down to choose a __shell__, all I see is `1: install`.

Extension version: 0.62.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.0-62-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.85GB (5.13GB free)|
|Process Argv|--crash-reporter-id d89f5b74-b40b-429e-9b7f-71895e8afab8|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: netautomation|
|OS|Linux x64 5.4.0-62-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (4 x 2599)|
|Memory (System)|3.84GB (0.60GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
vstry914:30244301
pythonvsdeb440cf:30242243
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30236630
pythonvspyt600cf:30247032

```

</details>

**Comment by roblourens** [comment]
You can click the `+` next to the dropdown to create a new terminal. Does that work for you?

**Comment by Nand087** [comment]
> 
> 
> You can click the `+` next to the dropdown to create a new terminal. Does that work for you?

Yes it does. Thank you @roblourens!
