### ISSUE TITLE
SSH Server crashing

### ISSUE THREAD

**Issue by andiaa734** [microsoft/vscode-remote-release#4327]
- VSCode Version: 1.35.0-insider
- Local OS Version: Windows 10 20H2
- Remote OS Version: Debian Buster (RPi 4)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open remote connection, start coding as usual, debug a little bit, go away for a hour to have a coffee
2. Come back. notice that nothing is working anymore. SSH is disconnected, SSH Server on remote host is crashed.
Even Putty cannot connect anymore. None of the Systems have gone to stand by. Trying to reconnect can work sometimes. But then ssh is very slow.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
The header says that you were on 1.35, this is a pretty old version, please try updating.
