### ISSUE TITLE
Copy/Paste between two different VS Code instances with different aws instances connected to it

### ISSUE THREAD

**Issue by raghavk92** [microsoft/vscode-remote-release#433]
- To be able to copy and paste stuff(large sizes 1-50gb) from 1 vscode-insiders instance(lets say aws instance connected via ssh at ip 1.1.1.1) to another vscode-insiders instance(lets say connected to aws instance via ssh at ip 2.2.2.2) . 

So what i am suggesting is if there is a possibility to execute valid statements like scp or rsync whichever is faster to be executed when a large file from one code-instance is dragged and dropped to another  code-instance (both instances connected to different servers).

- Also please add a download button in the right click menu for every file or folder. (if we press download on a folder it should zip itself and get downloaded to the users system).

Thanks
P.S. dont know if these features are somehow already available

**Comment by vict0rsch** [comment]
agree with the need for a download button :)

**Comment by sbatten** [comment]
the download feature is already implemented

**Comment by raghavk92** [comment]
@sbatten Although when i file is downloaded we are not able to see the progress bar for how much a file or folder is downloaded . So notifications for the progress bar for the downloads as well notification to download complete and pointing to the file from vscode would also be a good feature to have

**Comment by bpasero** [comment]
I don't think we can implement this easily given the one window does not know about the other's connection. @isidorn owns this experience.
