### ISSUE TITLE
code command from WSL opens with remote extension

### ISSUE THREAD

**Issue by obsgolem** [microsoft/vscode-remote-release#4331]
- VSCode Version: 1.52.1
- Local OS Version: Windows 10 2004 19041.685
- Remote OS Version: Ubuntu 2004
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Run `code filename.txt` from within a Windows folder in WSL
2. VSCode launches a new window with the folder open in WSL rather than in Windows

I would prefer this behavior to be optional so that I can use WSL to browse my filesystem while still editing within the Windows filesystem. I would also prefer it to open in my existing window rather than a new one.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by bamurtaugh** [comment]
Thanks for opening @obsgolem. As I believe the first part of your request is the same as https://github.com/microsoft/vscode-remote-release/issues/4109 and the existing window request is covered in https://github.com/microsoft/vscode-remote-release/issues/4289, closing as a duplicate. 

If I've missed or misunderstood any part of your issue, please just let me know, and I'm happy to discuss further. Thank you!
