### ISSUE TITLE
Language Basics

### ISSUE THREAD

**Issue by leelhn2345** [microsoft/vscode-remote-release#4334]
Issue Type: <b>Bug</b>

Why are these 2 extensions disabled on WSL? 
It was enabled globally few days ago.
Docker language basics & YML language basics

![image](https://user-images.githubusercontent.com/64735315/105323396-0dbcc900-5c05-11eb-9aa4-ff6df755f388.png)

Extension version: 0.52.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.21277
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 4900HS with Radeon Graphics          (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.42GB (5.58GB free)|
|Process Argv|--crash-reporter-id bf77eaf0-1c9c-4c4b-87d6-3c6efe693d39|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 4900HS with Radeon Graphics (16 x 2994)|
|Memory (System)|7.48GB (4.92GB free)|
|VM|0%|
</details>

**Comment by sandy081** [comment]
Can you please hover on the info icon or open the extension in the editor to see why it is disabled.

**Comment by leelhn2345** [comment]
> Can you please hover on the info icon or open the extension in the editor to see why it is disabled.

![image](https://user-images.githubusercontent.com/64735315/106106218-2dfa0400-6180-11eb-8021-389101ff5d8f.png)

This is what was shown when i hovered above the extension icon.

![image](https://user-images.githubusercontent.com/64735315/106106313-4ff38680-6180-11eb-8600-eac35396ce79.png)

When i right click on the extensions, the 'enable' function wasnt available to me.

**Comment by leelhn2345** [comment]
ok nevermind i just got it settled. it was the docker extension that caused this. 

I reinstalled docker and there isn't anymore of this issue.
