### ISSUE TITLE
multiple duplicated columns

### ISSUE THREAD

**Issue by calidion** [microsoft/vscode-remote-release#4337]
Issue Type: <b>Bug</b>

Don't know how to reproduce.

It ocurrs when editing remote project with C++ and CMake,

see the status bar of vscode in the attached picture 

Extension version: 0.62.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.8.0-38-generic
Remote OS version: Linux x64 5.4.0-62-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2316)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|7.69GB (0.25GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 0b2bc794-7e93-4ce1-9d4f-be3ab1847977|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|unity|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|unity|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.3.16|
|OS|Linux x64 5.4.0-62-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2420 0 @ 1.90GHz (24 x 1415)|
|Memory (System)|15.63GB (4.32GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440cf:30242243
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773cf:30236630
vstes627:30244334
pythonvspyt600:30247031

```

</details>

see the status bar

![2021-01-21 23-52-09屏幕截图](https://user-images.githubusercontent.com/131776/105375525-bd189080-5c43-11eb-80f8-11e2b2c5b25b.png)

**Comment by bamurtaugh** [comment]
Do you ever see any duplication with C++/CMake columns when working locally? Or is it just with SSH (/just this one time)?

**Comment by calidion** [comment]
I am sure it occurs  only with ssh, because i have been using CMake locally for a long time.

**Comment by roblourens** [comment]
If this is still an issue, please open an issue on the extension
