### ISSUE TITLE
Unable to use .env for build args data

### ISSUE THREAD

**Issue by troykelly** [microsoft/vscode-remote-release#4338]
There seems to be a lot of confusion around bringing in data from `.env` for passing to `build.args`.

Every time it's asked for - it's linked to an unrelated bug or feature request and closed. [Here](https://github.com/microsoft/vscode-remote-release/issues/1857) and [here](https://github.com/microsoft/vscode-remote-release/issues/46).

If data is _only_ in .env (not in the local environment) - how should it be passed as build arguments to the build process?

`localEnv` doesn't work - it's not in the local environment.
`--env-file` doesn't work - it's not been built yet.

Does not work:
```json
{
  "name": "Node.js",
  "build": {
    "dockerfile": "Dockerfile",
    "args": {
      "VARIANT": "12",
      "NPM_TOKEN": "${localEnv:NPM_TOKEN}",
      "GITHUB_TOKEN": "${GITHUB_TOKEN}"
    }
  },
  "runArgs": [
    "--env-file",
    "${localWorkspaceFolder}/.env"
  ]
}
```

**Comment by chrmarti** [comment]
`docker build` doesn't support env files, only `docker run` does. Labelling as feature request.

**Comment by eitsupi** [comment]
If the issue #4352 in the backlog is resolved, I think this issue will be resolved as well.
