### ISSUE TITLE
Hangs/Stalls on "Setting up SSH Host  [server] Initializing VS Code Server

### ISSUE THREAD

**Issue by alpdevel** [microsoft/vscode-remote-release#434]
- VSCode Version: 1.35.0-insiders
```
Version: 1.35.0-insider
Commit: 4ca38ce5584d7cd67b435b3c32ef1240c6a29628
Date: 2019-05-21T05:18:31.618Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
```

- Local OS Version: Windows 10. (v10.0.17.134)
- Remote OS Version: Red Hat Enterprise Linux v7.2
- Remote Extension/Connection Type: SSH

### Items of Note
settings.json files content
```{
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "remote.SSH.showLoginTerminal": true,
    "terminal.integrated.rendererType": "dom",

    "terminal.integrated.shell.linux": "/bin/csh"

}
```

Steps to Reproduce:

1. Connect to host in new window using this configuration
```
Host <my alias name >
    HostName <my host name >
    User <my user name >
    RemoteCommand bash -l
```
2. A new VSCode Window Appears

 Setting up SSH Host_<host>_: ([details](command:opensshremotes.revealTerminal "Show details in terminal")) Initializing VS Code Server

Does this issue occur when you try this locally?: Have not tried
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
Having a RemoteCommand in your config can break things - can you try the nightly SSH extension build to see if that fixes it? https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly

**Comment by alpdevel** [comment]
After some further research, I think the core issue is that my VM does not have internet access. So downloading the VS Code server is not going to work
