### ISSUE TITLE
Test: Extension management in the remote integrated terminal

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#4340]
Refs: https://github.com/microsoft/vscode-remote-release/issues/2589

- [x] Windows @sandy081 WSL
- [x] AnyOS: @weinand Dev Container
- [x] AnyOS: @sbatten SSH

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%234340%0A%0A)

---
- Open the integrated terminal in a remote window
- Run the remote CLI (`code-insiders` resp `code`) with the newly added commands `install-extension`, uninstall-extension`, list-extensions`, 

Test
- `code --install-extension idOrPathToVSIX` in combination with `--force`
  Installs an extension on remote if is a workspace extension, or local if it is a UI extension.
- `code --uninstall-extension idOrPathToVSIX` in combination with `--force`
   Uninstalls an extension on remote and/or local
- `code --list-extensions` in combination with `--show-version` and `--category`
  Lists all installed extension, regardless if local or remote, enabled or disabled

Compare against the regular CLI
- Try installing and uninstalling from a VSIX
- Test error cases (extension already installed, not installed...)

**Comment by weinand** [comment]
Please note, that `--show-versions` uses the plural form. The test description from above got it wrong.
