### ISSUE TITLE
Icons disappear in the latest Insider build

### ISSUE THREAD

**Issue by tvvignesh** [microsoft/vscode-remote-release#4341]
Hi. I just updated to the latest insider build and a lot of the extension icons have now disappeared in Remote SSH instance from the left pane but they do work when clicked. Screenshot with logs below. The icons of the extensions show up without Remote SSH though.

<img width="953" alt="1" src="https://user-images.githubusercontent.com/1165845/105486557-b38b3900-5cd4-11eb-9f51-9a41a8564cbd.PNG">

Version: 1.53.0-insider (user setup)
Commit: 4f2341834e646360e603953b62bf6c6020b07a29
Date: 2021-01-22T08:57:22.447Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.21292

**Comment by lachaib** [comment]
I get the same with **Remote-Container**

Version: 1.53.0-insider
Commit: 4f2341834e646360e603953b62bf6c6020b07a29
Date: 2021-01-22T08:55:11.282Z (4 hrs ago)
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

**Comment by roblourens** [comment]
This is now fixed, apologies

**Comment by tvvignesh** [comment]
@roblourens 👍 But is it released yet? I still face the same issue after updating to the next build.

Version: 1.53.0-insider (user setup)
Commit: ed72c64b87ede96fb51bc16870f9d2ecbf4fcc57
Date: 2021-01-22T17:18:22.679Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.21292

**Comment by roblourens** [comment]
Here is the issue, there will be another fix tomorrow: https://github.com/microsoft/vscode/issues/114743
