### ISSUE TITLE
A user needs to enter the password more than once

### ISSUE THREAD

**Issue by ArturGudiev** [microsoft/vscode-remote-release#4343]
1) When I try to connect to a remote host, VS code starts to ask me for a password. I often need to enter the same password several times.

2) If I want to change the current directory in the same host (to which I've already been connected), I need to reenter the password for the host again.

**Comment by roblourens** [comment]
`1.` shouldn't happen. If you share the log from the Remote-SSH output channel, that might help me find the issue.

`2.` may be fixed if you use the setting `remote.SSH.useLocalServer`, although you may find other issues, depending on your setup.
