### ISSUE TITLE
VS Code Server Aborting while connecting to SiteGround server via ssh

### ISSUE THREAD

**Issue by nsdotorg** [microsoft/vscode-remote-release#4346]
Issue Type: <b>Bug</b>

Steps: Connect to Remote Server (SiteGround) via ssh on VSCode through Remote SSH extension

Error Details
****************
node: ../deps/uv/src/unix/core.c:556: uv__close_nocheckstdio: Assertion `fd > -1' failed.
./server.sh: line 12: 51746 Aborted                 "$ROOT/node" ${INSPECT:-} "$ROOT/out/vs/server/main.js" "$@"

Extension version: 0.63.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0
Fetching remote diagnostics for 'SSH' failed: The VS Code Server failed to start
Fetching remote diagnostics for 'SSH' failed: The VS Code Server failed to start
Fetching remote diagnostics for 'SSH' failed: The VS Code Server failed to start

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 29655067-3b29-49e4-a8a8-acbcedfa4ce4|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: The VS Code Server failed to start

Fetching remote diagnostics for 'SSH' failed: The VS Code Server failed to start

Fetching remote diagnostics for 'SSH' failed: The VS Code Server failed to start
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt600cf:30247032

```

</details>

**Comment by roblourens** [comment]
What's the OS and architecture of the remote? Does it meet the reqs here? https://code.visualstudio.com/docs/remote/linux
