### ISSUE TITLE
Debugging issues with WSL Ubuntu in vscode

### ISSUE THREAD

**Issue by blQSheep** [microsoft/vscode-remote-release#4349]
Hello Friends,

After setting up WSL Unbutu for VSCode according to the [ WSL-Tutorial](https://code.visualstudio.com/docs/remote/wsl-tutorial), i cannot use the integrated VSC Debugging tool while in remote mode. 
I can only run my code with the "python3 file.py" command in the terminal,  or by selecting the play buttton next to the tab area, which will execute the /bin/python3 "path/to/my/file.py" in the terminal console and therefore run my code.

But everytime i try to run my code in debugging mode (F5) it returns this alert:

"The terminal process failed to launch: 
Path to shell executable "C:\Windows\System32\wsl.exe" does not exist." (Which is not true, because it exists there)

Also when i try to select my python interpreter i only get to choose 
/usr/bin/python3
/bin/python3
(these don't have pip, so they're basicly useless for me)
my local python interpreter or the anaconda distro paths are not listed and not supported when i try to enter the path manually.

Thank you guys in advance!

- VSCode Version: 1.52.1
- Local OS Version: Windows 10 Home
- Remote OS Version: WSL 2
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
Thanks for opening this @blQSheep. 

The [tutorial mentions installing pip](https://code.visualstudio.com/docs/remote/wsl-tutorial#_python-development) in your WSL distro. Did you execute that command (I'm just trying to understand the part where you mention they don't have pip).

Also, if you're able to use the green play button to run your code, it sounds like you may have selected an interpreter. Did you select one from the status bar?

![image](https://user-images.githubusercontent.com/25310137/106185145-4dc90200-6157-11eb-830f-cf9fd03f75bf.png)

![image](https://user-images.githubusercontent.com/25310137/106185182-54577980-6157-11eb-8da0-8d0ddd28cc45.png)

Then when you F5, do you select the option to select a Python File debug configuration, and then you run into issues?

![image](https://user-images.githubusercontent.com/25310137/106184778-d5fad780-6156-11eb-8a64-becf835c58d9.png)
