### ISSUE TITLE
Settings from settings.json should be injected before extension install

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#435]
Thanks to https://github.com/microsoft/vscode-remote-release/issues/409 you can now add container specific `settings.json` values to `devcontainer.json`.  This works great except for one use case: forcing an extension to install in a different place.

Currently the `docker-in-docker`, `docker-in-docker-compose`, and `kubernetes-helm` dev container definitions all force the docker extension to run as a workspace extension so that you can take advantage of the extensions full feature set.  We also point to these as a way to unlock these features in your own definitions in documentation.

Unfortunately the settings are added **after** the extensions are installed which means the Docker extension fails to install (since it tries to do it locally).

We should flip the order of these two operations.

**Comment by chrmarti** [comment]
It looks like extensions listed in the devcontainer.json are always installed remotely even when they are UI extensions. Am I missing something? (Your request makes sense otherwise.)

**Comment by Chuxel** [comment]
@chrmarti Docker was changed to be a UI extension with gaps in its feature set, the dev container definitions above both enable you to use the Docker CLI from inside the container **and** use the Docker extension as a workspace extension.  I added the following to `devcontainer.json`:

```json
	"settings": {
	    "remote.extensionKind": {
			"peterjausovec.vscode-docker": "workspace"
		}	
	}
```

This doesn't work and Docker is still installed as a UI extension because the settings are applied after the extensions are installed.  Previously I had this baked into the Dockerfile which then ensured the settings file was present prior to extension install and everything worked.

**Comment by joewood** [comment]
I'm seeing an issue that may be related to this. The extension loader is complaining about "self signed" certs (I'm behind a proxy), even if the container settings has string SSL: false. I suspect the settings are being applied after the extensions are attempted to load.
