### ISSUE TITLE
Port forwarding is failing intermittently but consistently

### ISSUE THREAD

**Issue by tetious** [microsoft/vscode-remote-release#4351]
Issue Type: <b>Bug</b>

Traffic over forwarded ports seems to have become very unreliable. This manifests most visibly with http 400s showing in the browser when working with a webserver, but whatever is doing the forwarding is actually returning the 400, as the request never makes it to the forwarded backend. I don't know much about how the forwarding works behind the scenes. 

I've been able to repro this with two different remote machines, and it is consistent enough that the feature is not really usable. Every pageload has about half of the resources fail to load with 400. 

This started happening in early last week's Insider build.

Please let me know if I can provide any other useful details. Thanks!

Extension version: 0.63.0
VS Code version: Code - Insiders 1.53.0-insider (ed72c64b87ede96fb51bc16870f9d2ecbf4fcc57, 2021-01-22T17:28:27.701Z)
OS version: Darwin arm64 20.2.0
Remote OS version: Linux x64 5.4.0-60-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 14c50ee1-a00b-46b0-abaf-6965d9e59493|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: penny|
|OS|Linux x64 5.4.0-60-generic|
|CPUs|Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz (8 x 1516)|
|Memory (System)|23.37GB (0.26GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment]
Does the port view show anything interesting? 

@alexdima I think you know more about the tunneling.

**Comment by janvotava** [comment]
It happened to me when using remote Docker through an SSH connection. It seemed that it was opening new SSH connections for every tunneled connection. I think setting `ControlMaster` in the SSH config helped to mitigate this problem a little. But what helped to fix this problem, even more, was connecting to the raw Docker socket through spiped.

**Comment by aNickzz** [comment]
The log from apache shows the requests coming through but the beginning of the request body is getting lost sometimes.

I had my `main.css` open in chrome and just hitting refresh and checking when it fails shows this in the log (note that I've removed some uninteresting stuff).

```log
127.0.0.1 - - [date-time] "GET /site/css/main.css?m=1604454885 HTTP/1.1" 200 1693 "-" "user-agent stuff"
127.0.0.1 - - [date-time] "GET /site/css/main.css?m=1604454885 HTTP/1.1" 200 1694 "-" "user-agent stuff"
127.0.0.1 - - [date-time] "GET /site/css/main.css?m=1604454885 HTTP/1.1" 200 1693 "-" "user-agent stuff"
127.0.0.1 - - [date-time] "/main.css?m=1604454885 HTTP/1.1" 400 0 "-" "-"
127.0.0.1 - - [date-time] "/main.css?m=1604454885 HTTP/1.1" 400 0 "-" "-"
127.0.0.1 - - [date-time] "GET /site/css/main.css?m=1604454885 HTTP/1.1" 200 1693 "-" "user-agent stuff"
127.0.0.1 - - [date-time] "/main.css?m=1604454885 HTTP/1.1" 400 0 "-" "-"
127.0.0.1 - - [date-time] "GET /site/css/main.css?m=1604454885 HTTP/1.1" 200 1694 "-" "user-agent stuff"
```

I did see one request come through that lost everything except up to the last `1` in `HTTP/1.1`:

```log
127.0.0.1 - - [date-time] "1" 400 0 "-" "-"
```

Though I'm not sure which asset this request was for, I have a feeling it was for the homepage as it lines up with the number of characters lost, which is 13 (oooh spooky)

```plaintext
GET /site/css/main.css?m=1604454885 HTTP/1.1
GET / HTTP/1.1
             | snip
```

I also didn't once see a request to the favicon fail.

For all of these requests, the network log in chrome shows that the requests are correct when they are sent.

<details>
<summary>vscode version info</summary>

Version: 1.53.0-insider (user setup)
Commit: 7b0cfdd04ad530a9c8d782c618afd79290be3d64
Date: 2021-01-27T08:59:32.031Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

</details>

**Comment by tetious** [comment]
For me, it happens even when running things on the host directly. I was able to repro running a dotnet 5 web api app as well as well as whatever ng serve uses these days. (lost track. webpack dev server?)

**Comment by alexdima** [comment]
I have pushed a fix on our server-side code and the fix will be available in tomorrow's Insiders.
