### ISSUE TITLE
Install in WSL not working for extentions

### ISSUE THREAD

**Issue by sumitkumarkar01** [microsoft/vscode-remote-release#4356]
- VSCode Version: 1.52.1
- Local OS Version:  20H2
- Remote OS Version: 20.04.1
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1.Open a new remote window in WSL
2. Try to install any extension using install in wsl 

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

![image](https://user-images.githubusercontent.com/47745916/105736958-928a4880-5f5f-11eb-9ce0-c62c6f27ed9f.png)
### Presssing this nothing happens

**Comment by bamurtaugh** [comment]
cc @sandy081

**Comment by sandy081** [comment]
- Please enable log level to trace using the command `Set Log Level`
- Try to reproduce the issue
- Provide us with following logs
  - F1 > Open View > Log (Window)
  - F1 > Open View > Log (Remote Server)

**Comment by sumitkumarkar01** [comment]
Selecting Install in WSL the extension installs locally without any prbolem but doesn't install in wsl
**Log(Window)**
`[2021-01-29 19:22:39.933] [renderer1] [debug] Webview(extensionEditor): will post message on 'focus'`
`[2021-01-29 19:22:39.933] [renderer1] [debug] Webview(extensionEditor): did post message on 'focus'`
`[2021-01-29 19:22:47.986] [renderer1] [trace] RequestService#request https://austin.gallerycdn.vsassets.io/extensions/austin/code-gnu-global/0.2.2/1499506417980/Microsoft.VisualStudio.Code.Manifest`
`[2021-01-29 19:22:48.020] [renderer1] [debug] Webview(extensionEditor): will post message on 'focus'`
`[2021-01-29 19:22:48.020] [renderer1] [debug] Webview(extensionEditor): did post message on 'focus'
`
**Log (Remote Server)**
`[2021-01-29 19:23:12.163] [remoteagent] [trace] Started scanning user extensions`
`[2021-01-29 19:23:12.177] [remoteagent] [trace] Scanned user extensions: 1`
`[2021-01-29 19:26:50.924] [remoteagent] [trace] ExtensionManagementService.refreshReportedCache`
`[2021-01-29 19:26:50.924] [remoteagent] [trace] RequestService#request https://az764295.vo.msecnd.net/extensions/marketplace.json`
`[2021-01-29 19:28:12.212] [remoteagent] [trace] Started scanning user extensions`
`[2021-01-29 19:28:12.221] [remoteagent] [trace] Scanned user extensions: 1`

**Comment by sumitkumarkar01** [comment]
As you can see here I am tring to install the extension C++ intellisense and it has been installed locally but not in wsl 
![image](https://user-images.githubusercontent.com/47745916/106280938-bce24b80-6268-11eb-941f-df28544903dc.png)

**Comment by sandy081** [comment]
@sumitkumarkar01 May I know if the logs are captured after you clicked on `Install in WSL: Ubuntu` button? I would expect the remote server log to show Installing messages. Can you also please try enabling the setting `remote.downloadExtensionsLocally` to true?

**Comment by sumitkumarkar01** [comment]
Yes that was captured after I pressed install in wsl when the extension is locally installed.
Now that I have removed it from local and tried again It shows these in logs

`[2021-02-02 23:11:38.633] [remoteagent] [trace] ExtensionManagementService.refreshReportedCache`
`[2021-02-02 23:11:38.634] [remoteagent] [trace] RequestService#request https://az764295.vo.msecnd.net/extensions/marketplace.json`
`[2021-02-02 23:12:55.113] [remoteagent] [trace] Started scanning system extensions`
`[2021-02-02 23:12:55.114] [remoteagent] [trace] Started scanning user extensions`
`[2021-02-02 23:12:55.184] [remoteagent] [trace] Scanned user extensions: 1`
`[2021-02-02 23:12:55.255] [remoteagent] [trace] {"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/sumit/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/package.json"}`
`[2021-02-02 23:12:55.290] [remoteagent] [trace] Scanned system extensions: 30`
`[2021-02-02 23:12:55.900] [remoteagent] [trace] Started scanning system extensions`
`[2021-02-02 23:12:55.900] [remoteagent] [trace] Started scanning user extensions`
`[2021-02-02 23:12:55.937] [remoteagent] [trace] Scanned user extensions: 1`
`[2021-02-02 23:12:55.975] [remoteagent] [trace] {"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/sumit/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/package.json"}`
`[2021-02-02 23:12:55.990] [remoteagent] [trace] Scanned system extensions: 30`
`[2021-02-02 23:12:56.056] [remoteagent] [trace] Started scanning system extensions`
`[2021-02-02 23:12:56.057] [remoteagent] [trace] Started scanning user extensions`
`[2021-02-02 23:12:56.103] [remoteagent] [trace] Scanned user extensions: 1`
`[2021-02-02 23:12:56.145] [remoteagent] [trace] {"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/sumit/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/package.json"}`
`[2021-02-02 23:12:56.178] [remoteagent] [trace] Scanned system extensions: 30`

**Comment by sumitkumarkar01** [comment]
@sandy081 Yes after enabling `remote.downloadExtensionsLocally` everything works

**Comment by sandy081** [comment]
Seems connections issues in WSL

Assigning to @aeschli for further investigation

**Comment by aeschli** [comment]
@sandy081 Where can we find logs that show the failed request? Having the URL I would try to make a `curl` on a WSL shell to see if it is related to WSL or us.

**Comment by sumitkumarkar01** [comment]
@aeschli Sorry I didn't understand. Can you please tell me what I need to do?

**Comment by aeschli** [comment]
@sandy081 Can you give an example of a URL that we use to download an extension?

**Comment by sandy081** [comment]
@aeschli Please enable the log level to trace and you can find the corresponding requests in your shared process log

**Comment by sandy081** [comment]
Here is an example URL

```
https://editorconfig.gallery.vsassets.io/_apis/public/gallery/publisher/EditorConfig/extension/EditorConfig/0.16.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?redirect=true&install=true
```

**Comment by sumitkumarkar01** [comment]
@sandy081 When I curl to the link I get this output
`curl -v https://editorconfig.gallery.vsassets.io/_apis/public/gallery/publisher/EditorConfig/extension/EditorConfig/0.16.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage\?redirect\=true\&install\=true`
*   Trying 13.107.6.175:443...
* TCP_NODELAY set
* Connected to editorconfig.gallery.vsassets.io (13.107.6.175) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=visualstudio.com
*  start date: Nov 18 13:10:37 2020 GMT
*  expire date: Nov 18 13:10:37 2021 GMT
*  subjectAltName: host "editorconfig.gallery.vsassets.io" matched cert's "*.gallery.vsassets.io"
*  issuer: C=US; O=Microsoft Corporation; CN=Microsoft RSA TLS CA 01
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55e8839ce670)
> GET /_apis/public/gallery/publisher/EditorConfig/extension/EditorConfig/0.16.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?redirect=true&install=true HTTP/2
> Host: editorconfig.gallery.vsassets.io
> user-agent: curl/7.68.0
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 302
< cache-control: no-cache, no-store, must-revalidate
< pragma: no-cache
< expires: -1
< location: https://editorconfig.gallerycdn.vsassets.io/extensions/editorconfig/editorconfig/0.16.4/1607315835386/Microsoft.VisualStudio.Services.VSIXPackage
< p3p: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
< set-cookie: VstsSession=%7B%22PersistentSessionId%22%3A%228426133e-2c95-4a14-8c5f-e6fd704a2470%22%2C%22PendingAuthenticationSessionId%22%3A%2200000000-0000-0000-0000-000000000000%22%2C%22CurrentAuthenticationSessionId%22%3A%2200000000-0000-0000-0000-000000000000%22%2C%22SignInState%22%3A%7B%7D%7D;SameSite=None; domain=.visualstudio.com; expires=Wed, 11-Feb-2026 04:34:14 GMT; path=/; secure; HttpOnly
< x-tfs-processid: 464864f5-51b6-4b00-bf97-e75f8e5557b8
< strict-transport-security: max-age=31536000; includeSubDomains
< activityid: 4a385ac1-f0c4-42d1-8aaa-d99837414107
< x-tfs-session: 4a385ac1-f0c4-42d1-8aaa-d99837414107
< x-vss-e2eid: 4a385ac1-f0c4-42d1-8aaa-d99837414107
< request-context: appId=cid-v1:84715e31-583a-4723-a46d-946169b2f4a8
< access-control-expose-headers: Request-Context
< x-content-type-options: nosniff
< x-msedge-ref: Ref A: 7526264051CE444BB06632958A1756C4 Ref B: SG1EDGE0309 Ref C: 2021-02-12T04:34:14Z
< date: Fri, 12 Feb 2021 04:34:14 GMT
< content-length: 0
<
* Connection #0 to host editorconfig.gallery.vsassets.io left intact

**Comment by aeschli** [comment]
Do you still see this issue?
