### ISSUE TITLE
Activate all extensions in devcontainer.json on workspace start

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-remote-release#4358]
For example, I have the vscode-python extension set in my devcontainer.json. However, the Python extension only activates when I open a Python file.

While this would make sense in a development environment for multi purposes in order to keep the VS Code window fast, it does not make sense in the development container scenario.

The first time the Python extension gets activated, it downloads a bunch of things and takes some time to properly starts up. This is also the case with the Typescript and Javascript extensions, and probably way more.

Because of this, if I open a terminal before I open a Python file, the terminal won't automatically source my venv, because the Python extension (unloaded), was not there already.

**Comment by felipecrs** [comment]
A better tag would be containers.

**Comment by chrmarti** [comment]
This sounds to me like the Python extension should activate before a terminal opens. @Tyriar Do you know if an extension can do this?

**Comment by Tyriar** [comment]
I don't think there's a nice way around this problem currently. I wonder if there should be a special activation event for this particular case where the extension is very likely to be used 🤔 we certainly don't want to eagerly activate the Python extension in general. One workaround could be to have one of these files in the repo:

https://github.com/microsoft/vscode-python/blob/61da153eae3a904d26c5dda555c960ecf6ba4ade/package.json#L86-L87

**Comment by felipecrs** [comment]
> we certainly don't want to eagerly activate the Python extension in general

Absolutely.

> One workaround could be to have one of these files in the repo:

I ended doing that, but it's just a solution for the Python extension.

---

The proposal was more generic and broad. It would enhance the experience of developing in containers.

**Comment by chrmarti** [comment]
We selectively activate extensions when they are needed for optimizing performance. The Python case could be fixed with an additional activation event in VS Code and the Python extension adopting it. Other extensions would need to be looked at individually to decide if any fixes are needed.

**Comment by felipecrs** [comment]
> We selectively activate extensions when they are needed for optimizing performance.

This was already stated in the issue description. :)

Nonetheless, as explained earlier, in the `devcontainer` scenario, the extensions were previously selected for use, therefore, most of them should be required for the proper use of the development environment. The same generic motivation for not activating them preemptively could not apply here.

Actually, the inverse may be desired: as some extensions take a long time to activate for the first time (and remember: the first time in devcontainers is supposed to happen frequently), would be good if we could activate them as part of the devcontainer startup. I'm not talking about the extensions to expose an additional activation event, but VSCode preemptively activating them.

I would expect it as a new option in the `devcontainer.json`:

```json
{
  "activateExtensionsOnStartup": true
}
```
