### ISSUE TITLE
Test: WSL recommender extension

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#4360]
Refs: https://github.com/microsoft/vscode-remote-release/issues/4255

- [x] Windows @sbatten 10, any version > 1903 (May 2019)
- [x] Windows @misolori preview build >= 20262 (https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso?wa=wsignin1.0)

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%234360%0A%0A)

---

Windows builds without WSL & VSCode without 'Remote - WSL' extension installed

Start VSCode
- Verify that our of the box there's no remote indicator visible. All the functionality is enabled by experiments
- Set `"remote.WSLRecommender.allExperiments": true` to bypass the experiments and to enable all the functionality

- Verify that you now get the remote indicator with two menu entries: `Open Folder in WSL...` and `Getting Started with WSL`
- Run `Open Folder in WSL...` 
    - If you are in a Windows build >=  20262 it offers to install WSL (`Install Now`)
    - Verify  that `Install Now` will show a dialog to elevate Windows and run the WSL install command
- Test the documentation links

- Verify that after installing WSL (and a reboot) running `Open Folder in WSL...` will get a dialog that offers to install the `Remote - WSL` extension if not yet installed

**Comment by sbatten** [comment]
Tested on WoA, everything went quite smoothly.

**Comment by misolori** [comment]
I seem to be stuck on this state:

![image](https://user-images.githubusercontent.com/35271042/105927178-548d3300-5ff8-11eb-8571-08e5e90e8f6c.png)

![image](https://user-images.githubusercontent.com/35271042/105927184-5820ba00-5ff8-11eb-93c4-336ff5847cc1.png)

Restarting results in nothing changed and i'm stuck in this endless loop. I'm assuming this a WSL issue?

**Comment by aeschli** [comment]
Yes, when you restart Windows, WSL should be installed. E.g. `wsl --list` should work from the Windows command prompt.
Can you uninstall WSL (`Turn Windows features on or off`), reboot and try again? If it reproduces, let's file an issue against https://github.com/microsoft/wsl. All what happens on `Install Now` is running `wsl --install` in an elevated powershell terminal.

**Comment by misolori** [comment]
I had to manually install a distro after re-enabling WSL, not sure if that's part of the install step. Otherwise this did work, however there is a lot of going back and forth, like after installing the extension you have to go back to the remote badge to open the menu. Wish there were some prompts that guided you if you clicked through the toast.
