### ISSUE TITLE
Inconsistent command capitalisation

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode-remote-release#4363]
Testing #4316

The command label has inconsistent capitalisation. You can see that this hover:

![image](https://user-images.githubusercontent.com/1704059/105836844-bc765600-5fc5-11eb-9dd3-30f9e377eb4e.png)

Is inconsistent with this hover:

![image](https://user-images.githubusercontent.com/1704059/105836885-cc8e3580-5fc5-11eb-8c45-2744d99aa0f3.png)

I don't know what the guidelines are but at least one of these should be changed to be consistent with the other. @misolori - what are the guidelines around capitalisation?

**Comment by misolori** [comment]
We don't have a topic for this, but I believe our pattern is to use sentence casing for non-command text. I can add this to the guidelines.

**Comment by alexr00** [comment]
@Tyriar in this case the "Follow Link" for terminal links should be "Follow link". Shall I make the change while I'm there?

**Comment by Tyriar** [comment]
@alexr00 sure
