### ISSUE TITLE
Asked for password more than once

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-remote-release#4366]
Testing #4362

When attaching to a container I'm asked 3 times for password:

![2021-01-26_16-56-53 (1)](https://user-images.githubusercontent.com/1898161/105869764-e183bc80-5ff7-11eb-902d-6f077a812740.gif)

The same happens when attaching to a container with `Remote-Containers: Attach to Running Container`

Two more examples:

![2021-01-26_16-48-31 (1)](https://user-images.githubusercontent.com/1898161/105869830-f4968c80-5ff7-11eb-9a7c-8e6544a77456.gif)

First for the "refresh" command, then for the "Go" sample.

**Comment by chrmarti** [comment]
Thanks for catching. Fixing a last minute breakage.

The instructions were imprecise: There will be one prompt from Remote-SSH when the Remote-SSH window opens and one prompt from Remote-Containers when the first Remote-Containers command is invoked. But there should be no more than that. There should be only one prompt when connecting to the container (from Remote-Containers, Remote-SSH does not participate in that case).

To verify please see test plan item #4362 for setup instructions and verify Windows and either Mac or Linux. (Can be two verifiers.)

**Comment by JacksonKearl** [comment]
Tested MacOS and worked fine.

On Windows:
Got this error after entering my password for refreshing the remote containers view on Windows, no user impact that I saw.
![image](https://user-images.githubusercontent.com/8586769/106340799-d9be5500-624f-11eb-83c7-ae59bfec444c.png)
When connecting to container, I had to enter password twice and the prompt doesn't actually tell me what I'm entering a password for. On attaching to future containers I only had to enter once, but the prompt still doesn't tell me what I need.
![image](https://user-images.githubusercontent.com/8586769/106341069-cc559a80-6250-11eb-822a-88b1a77685b2.png)

When I went back to check if the prompt had more information on Mac though, the `Containers` view was empty?
![image](https://user-images.githubusercontent.com/8586769/106341363-de840880-6251-11eb-99db-b8aa6e9b58e1.png)

**Comment by JacksonKearl** [comment]
When I tried connecting to the ssh remote again from my Windows box I get this error:
![image](https://user-images.githubusercontent.com/8586769/106341874-a8478880-6253-11eb-9c33-e8ff8ce21416.png)

Docker-compose down and up did not fix

**Comment by JacksonKearl** [comment]
Wasn't able to reproduce the windows asking twice issue, created a some new issues for the prompt not saying what it's prompting and MacOS losing the containers context.
