### ISSUE TITLE
Remote agent should discover the correct environment the same way that VS Code does

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#437]
Currently the resolver extension tries to install the remote agent by starting a shell that runs the user's startup scripts. This leads to all sorts of issues. The agent or remote EH should discover its environment by launching the user's shell and grabbing its environment. This is the same method that VS Code does. It might not be perfect but at least it will be the same.

https://github.com/microsoft/vscode/blob/f794ad0a221ff325373e04bb1fc2b5f9bc64b309/src/vs/code/node/shellEnv.ts#L12

Dropping `-il` from the bash server install script will make many things easier.

**Comment by roblourens** [comment]
FYI @chrmarti and @aeschli, I'm going to have the agent run the shellEnv code and copy that environment into the new spawned EH.

**Comment by roblourens** [comment]
How I tested this:

- Install zsh
- Set as default shell using chsh
- Set up NVM in ~/.zshrc (and not in .bashrc)
- Run an npm task
- Before this change, the task fails because npm is not on the path
- After this change, the task runs successfully using npm configured by ~/.zshrc

**Comment by roblourens** [comment]
This is now implemented so you shouldn't have to run the install script with `-il` if you don't want.

**Comment by chrmarti** [comment]
That's great, thanks @roblourens for tackling this!

**Comment by underchemist** [comment]
Is there a workaround for users whose authentication is handled by another server i.e. LDAP? I cannot change my default shell using chsh on my remote server because my username is not in `/etc/passwd` due to authentication being handled through LDAP

**Comment by roblourens** [comment]
@underchemist Can you open a new issue with some more details about exactly what problem you are seeing?

**Comment by underchemist** [comment]
I may have been conflating some issues here actually.

I thought that in order to have zsh be your default shell you had to set it to your default shell using chsh. However I just uncommented the offending snippets in my .bash_profile (which activated my zsh shell if the shell was a login shell) and everything works as expected. When connecting with vscode I have a bash shell and when connecting through a normal terminal I have a zsh shell. 

I guess the next question for me is is it possible to make the integrated terminal spawn with my zsh shell?

**Comment by chrmarti** [comment]
@underchemist There is a setting for the shell to be used under Linux. You could add that to you `devcontainer.json`'s `"settings"` property, so it is copied to the container after it is created. You could also add it to your user settings, the downside of that is that it will affect all your containers - not all might have zsh installed.
