### ISSUE TITLE
List of extensions not reflecting in vscode extensions viewlet

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-remote-release#4370]
Testing #4361

According to the extensions viewlet, at any time I have only eslint installed.

![devtools-still-installed](https://user-images.githubusercontent.com/7199958/105875820-1d486300-5fb3-11eb-8308-7d8c00243bef.png)

**Comment by aeschli** [comment]
Pushed a fix in the Remote-WSL extension (0.53.2)
