### ISSUE TITLE
"--show-version" not available for code-insiders

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-remote-release#4371]
Testing #4340

"--show-version" is not available for code-insiders (whereas "--category" is)

<img width="702" alt="2021-01-26_18-32-16" src="https://user-images.githubusercontent.com/1898161/105881545-f0bd3700-6004-11eb-9a1b-f8d5f09817eb.png">

**Comment by sandy081** [comment]
Its `--show-versions`.

**Comment by weinand** [comment]
@sandy081 why the plural form? The other flag "--category" is singular.

**Comment by sandy081** [comment]
@weinand Good question, there are no multiple versions of extension. I do not have clue why it is plural (Its been there from beginning I suppose).
