### ISSUE TITLE
"--force --install-extension" doesn't update to latest version

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-remote-release#4372]
Testing #4340

- in integrated terminal in docker container run `code-insiders --force --install-extension ms-azuretools.vscode-docker@1.9.0` to install previous version of Docker extension
- now try to install latest by omitting the version and using "--force": `code-insiders --force --install-extension ms-azuretools.vscode-docker`

Observe: 
1.9.1 version is not installed:
<img width="862" alt="2021-01-26_18-53-50" src="https://user-images.githubusercontent.com/1898161/105884049-d6388d00-6007-11eb-8e11-7de48628148d.png">

I think my confusion originates from the mixed messages about "--install-extension --force":

In the test plan item I read "--force ... installs an extension on remote if is a workspace extension, or local if it is a UI extension."

But this message says: "Extension 'ms-azuretools.vscode-docker' v1.9.1 is already installed. Use '--force' option to update to latest version or provide '@<version>' to install a specific version, for example: 'ms-azuretools.vscode". 

Wouldn't it be clearer to have different "--forceSomething" instead of overloading a single magic "--force"? Or even better introduce new options like "--installRemote" or "--installUI".

**Comment by aeschli** [comment]
Was that your setup?
- `ms-azuretools.vscode-docker' v1.9.1 ` installed locally
- `code-insiders --force --install-extension ms-azuretools.vscode-docker@1.9.0`. Installs v1.9.0 remotly
- `code-insiders --force --install-extension ms-azuretools.vscode-docker` finds it locally and doesn't want to update.

**Comment by weinand** [comment]
@aeschli yes, that was my setup

**Comment by sandy081** [comment]
@aeschli It means all extension CLI management features shall be made multi server (local and remote) aware. Looking at other issues, I felt it would be simple and consistent if remote CLI only manages remote server extensions just like local CLI handles only local extensions. It means:

- `list-extensions` - lists extensions only from remote
- `install-extension` - installs extension only on remote
- `uninstall-extension` - uninstalls extension only on remote

It might be too smart to understand if remote cli manages extensions on both sides. I also think constraining remote cli only to remote will also be consistent when user does above operations opening bash (say from WSL or SSH machine) using server cli.

**Comment by TylerLeonhardt** [comment]
Worked in Remote - SSH:

```
PS C:\Users\tyleonha> code-insiders --force --install-extension ms-azuretools.vscode-docker@1.9.0
Installing extensions on SSH: TYLEONHA-DESK1...
Updating the extension 'ms-azuretools.vscode-docker' to the version 1.9.0
Installing extension 'ms-azuretools.vscode-docker' v1.9.0...
Extension 'ms-azuretools.vscode-docker' v1.9.0 was successfully installed.

PS C:\Users\tyleonha> code-insiders --force --install-extension ms-azuretools.vscode-docker
Installing extensions on SSH: TYLEONHA-DESK1...
Updating the extension 'ms-azuretools.vscode-docker' to the version 1.9.1
Installing extension 'ms-azuretools.vscode-docker' v1.9.1...
Extension 'ms-azuretools.vscode-docker' v1.9.1 was successfully installed.
PS C:\Users\tyleonha>
```
