### ISSUE TITLE
No offer to install wsl extension, only show

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#4375]
Testing #4360

The notification that shows when you "Open folder in WSL" without the extension offers to show the extension, but does not give me a one-click install and continue option.

Some form of "Install and Continue" would be nice.

**Comment by aeschli** [comment]
For the install button you need a Windows preview build >= 20262. @sbatten On what build version were you?

**Comment by sbatten** [comment]
Sorry for not being more descriptive:

My build is 19041, so I know I don't get `wsl --install`

BUT, after I've set up WSL, I get a notification that says I need the **Remote WSL extension**. Surely, we can one click install the extension and proceed without the user needing to open the view container.
