### ISSUE TITLE
--list-extensions shows a confusing set of extensions

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#4377]
Testing #4340

When running `--list-extensions` from the remote CLI, I cannot tell if an extension is installed in the remote.

The list contains all my extensions (including workspace extensions that have not been installed in the remote yet).

e.g. Mock Debug is listed even though it is only installed locally and not enabled in the remote.

`--list-extensions` should show groups like the extensions view. Local Extensions (UI), Remote Extensions (Workspace), and potentially others even though they are not enabled.

**Comment by aeschli** [comment]
I changed that the remote CLI command only work with remote extensions. I also improved the command output to reflect that:

![image](https://user-images.githubusercontent.com/6461412/106157257-cf825500-6182-11eb-8054-4c87a721c87d.png)

![image](https://user-images.githubusercontent.com/6461412/106157347-e9239c80-6182-11eb-80ae-154ae311ced5.png)

**Comment by sbatten** [comment]
labeling as bug for verification purposes
