### ISSUE TITLE
remote cli extension management too opaque about extension install location

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#4378]
Testing #4340

Similar to https://github.com/microsoft/vscode-remote-release/issues/4377 but broader

Repro:
1. Open VS Code without a remote connection
2. Install Mock Debug Extension
3. Connect to remote
4. Use remote cli to list extensions (shows all extensions including mock debug which is not enabled/installed on remote)
5. use remote cli to uninstall extension (operation uninstalls the extension locally)
6. use remote cli to install extension (operation installs the extension on the remote)

5 and 6 confusingly do not complement each other

**Comment by aeschli** [comment]
The cli currently doesn't allow to specify the install location, it's decided based on the extension kind.

**Comment by aeschli** [comment]
I changed the feature to only work on remote extensions: https://github.com/microsoft/vscode/pull/115302
