### ISSUE TITLE
Developer: Reload Window no longer reloads bashrc for devcontainer

### ISSUE THREAD

**Issue by jhampson-dbre** [microsoft/vscode-remote-release#4379]
Remote Containers v0.155.1

Until recently, I could change an exported environment variable defined in the `.bashrc` inside my container, select `Developer: Reload Window`, and the environment variable change would be effective after the reload. Today, I changed an environment variable in `.bashrc`, selected `Developer: Reload Window`, but the variable was still not in the environment. I fully close out of VS Code, reopened it, and the environment variable was set as expected.

Looking through release notes I see:
"This month, we gave VS Code Remote the ability to persist your terminal sessions and reattach to them later, such as after a window reload."

I assume that the reload I was doing was attaching to a persistent session, so the environment variables were not reloaded as they had been in the past.

I see there is setting `Terminal > Integrated: Enable Persistent Sessions` that could be disabled, but I actually like the idea of this feature. It would be nice if there was a way to choose "soft" or "full" reload from the command pallet, or some other way to selectively control this feature without having to toggle settings.

**Comment by alexdima** [comment]
@jhampson-dbre So you would want that `.bashrc` is sourced again. Isn't there some linux command that does this, like `source ~/.bashrc`. I think that would make the current terminal get the new environment variable. Alternatively, you could click on the "Trash" icon in the terminal and make a new one, I think the new one should get your new environment variable.

cc @Tyriar @roblourens to correct me if I'm way off.

**Comment by Tyriar** [comment]
Yes, you should use `source ~/.bashrc` (shorthand `. ~/.bashrc`) to bring that terminal's environment up to date. I'd rather not get in the business of adding commands that send specific text to the terminal because they won't work cross platform/cross shell, be hard to discover and get limited usage.

**Comment by jhampson-dbre** [comment]
That's a good point about re-sourcing it from the terminal. It was just surprising that all of the sudden this seemed to stop working. I agree that there is no need to making re-sourcing the environment part of that of the "persistent terminal" feature.

Now that I think about it, maybe I'm confusing VS Code's remote environment and the terminal's environment. Does does VS Code still respect `userEnvProbe` setting when "persistent terminal" is active? In other words, we have extensions that rely on environment variables set in our container's `bashrc`. Previously, if we needed to adjust an environment variable that is used by an extension (for example, setting `HTTP_PROXY`, or adding a directory to `PATH`), we would change it in `bashrc`, reload window, and it would be inherited in VS Code's remote env. If VS Code still runs the `userEnvProbe` on `Reload Window` and picks up the new environment variables, but the terminal itself still uses the old environment, then this is less impactful (as we can just re-source bashrc to update the terminal).

Either way, I think having an option to to do a full reload (i.e. the previous behavior) from command pallet, instead of toggling configuration settings on and off, would still be helpful. Sometimes "weird stuff" happens and it was easy to do a `Reload Window` to knock all the bits back into place. As I mentioned, I think the persistent terminal is a great feature and most of the time I would like to use this, but it would be nice to have an easier way to sometimes choose the old behavior without having to toggle the "enable persistent terminal" off and on.

**Comment by alexdima** [comment]
> we have extensions that rely on environment variables set in our container's `bashrc`

The "Reload Window" behavior of the remote extension host did not change. I think perhaps you have been using terminals as a way to "troubleshoot" env variables as seen in the extension host. But that was never a reliable way to do it. To give a simple example, extensions have access to an env variable called `VSCODE_NLS_CONFIG`. This env variable would not show in terminals even if it was available to extensions.

> Sometimes "weird stuff" happens and it was easy to do a Reload Window to knock all the bits back into place

Reload Window was never cleaning up everything. For example, the server process would survive before reloads. Now, besides the server process, the existing terminal sessions survive. Now you need to press the garbage can icon and make a new terminal to get a new terminal.

**Comment by jhampson-dbre** [comment]
@alexdima I can confirm that the the environment variable changes in `bashrc` are still picked up in the VS Code extension host on `Reload Window`. The confusion was on my part, since previously after a reload both the terminal environment and VS Code extension host environment (at least the part inherited from `bashrc`) would pick up any `bashrc` changes. So after making a `bashrc` change, doing `Reload Window` and then trying to run a command in terminal that failed due to the environment not being reset, I made the invalid assumption that VS Code was also unaware of my `bashrc` change, but this is not the case. 😳

Now that I understand how all of this is working, I agree the best option is to do as suggested and re-source the variables in the terminal or to open a new terminal session and kill the old one. Thanks for taking the time to walk through this with me.
