### ISSUE TITLE
Failed to parse remote port from server output

### ISSUE THREAD

**Issue by LukaHorvat** [microsoft/vscode-remote-release#438]
I can connect to a remote once. When the new connection starts up the server everything works. But if I then close VS Code and reopen it (so that it tries to reconnect with the server still running) I get this:

```
...extra server welcome message stuff omitted...
> 
> Found existing installation...
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 219276aa-dee5-4af5-ad9d-8c7b9aec820a==35351==
> bash: cannot set terminal process group (5740): Inappropriate ioctl for device
> bash: no job control in this shell
> 
"install" terminal command done
Received install output: bash: no job control in this shell
Failed to parse remote port from server output: bash: no job control in this shell
```

Seems like it does work and it's supposed to parse that string but it instead tries to parse the last error line (which probably doesn't matter).

Killing the server (either manually by killing the process or via the command palette option) and then restarting VS Code again reconnects successfully. 

- VSCode Version: 1.35.0
- Local OS Version: Win 10 64bit 10.0.17763
- Remote OS Version: Ubuntu 18.04.2 LTS
- Remote Extension/Connection Type: SSH

**Comment by Lujaw** [comment]
I was able to connect to the remote machine via ssh.
But after the update on Vscode Insiders, I am also getting the same error.

**Comment by egamma** [comment]
see also #332

**Comment by LukaHorvat** [comment]
It's similar, like a couple of other issues, but I think it's not the same. In my case the output is present, it just doesn't get parsed. And the later problems in that same issue don't exist for me since I'm able to connect using the way I mentioned.

**Comment by LukaHorvat** [comment]
I modified the extension so it only uses `-lc` instead of `-ilc` when invoking bash and this fixes my issue. Is there a reason for the interactive flag?

**Comment by rtmatx** [comment]
I have the same issue. Where did you modify the setting from `-lc` to `-ilc`

**Comment by LukaHorvat** [comment]
@rtmatx I don't think there's a setting for it. I opened the extension's code in `%HOME%\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-explorer-0.42.0\out`, found the `ilc` string and replaced it. That being said, my changes seem to be overwritten now (probably the extension updated) but it still works.

**Comment by roblourens** [comment]
Sounds like it's working now and I would expect this to be fixed, closing.
