### ISSUE TITLE
remote.portsAttributes: add defaultSnippets 

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#4382]
Testing #4317

```
"remote.portsAttributes": {
   '//| code completion: no proposals
}
```

[defaultSnippets](https://github.com/microsoft/vscode/blob/e06ef891b704240ce2e49bfe0d239b104a10a90b/src/vs/workbench/services/themes/common/colorThemeSchema.ts#L159) should be added so it's easy to add a new rule

**Comment by alexr00** [comment]
Cool feature, I didn't know about defaultSnippets!
