### ISSUE TITLE
Run debug and tasks as a different user 

### ISSUE THREAD

**Issue by memco** [microsoft/vscode-remote-release#4387]
When editing remotely I work on some systems where the code I am editing and debugging requires it to be run as a different user than the one I issue to log in. I would love a feature added to allow running as a different user or perhaps a better way to keep my session when I launch a debugger. Currently if I connect to the remote, switch users and then launch the debugger it opens a new terminal with the login user shell not the one I just switched to

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/690
