### ISSUE TITLE
RemoteCommand support within settings instead of default RemoteCommand=none

### ISSUE THREAD

**Issue by kristoferpelchat** [microsoft/vscode-remote-release#4388]
First off this extension (Remote-SSH specifically) is WONDERFUL! I use it almost exclusively now for remote dev for cloud machines!

Please see [this](https://github.com/microsoft/vscode/issues/48659#issuecomment-570815118) link as it explains quite a bit. You will notice here that there is a workaround for this that I use, and it does work VERY well! However, when I go to a different system I must always remember to do this. You will notice they reference that this works on macOS and Linux. I have tested this on macOS and it works wonderfully. I assume though the created of this is correct in that perhaps it does not work in Windows, hence why it is like this.

It would be WONDERFUL if you could provide some settings to allow usage of `RemoteCommand` in the `ssh` config file. Since this doesn't work in Windows is it possible for you to perhaps have a note stating that this only works on macOS and Linux at the moment? 

I feel there are other commands that are shutoff too that you could perhaps do the same with, but `RemoteCommand` is EXTREMELY useful to elevate privileges on the remote machine with a `sudo su -`, if you are given that right on the system.

I use this AWESOME extension extensively for all my development now as we only develop in containers. Docker on a Mac is STILL a resource hog and we now use AWS machines for all our dev. This plugin allows us to do this but elevating permission`s is extremely important as we only run `docker-compose` for instance as root.

Please let me know if you need anymore information. I don't even think this needs a UI option, even if there is some property (`enable.RemoteCommand`) I set in the settings file...that would work better than having to perform this workaround always.

Please also note that I DO NOT remove the `bash` portion that is in [this](https://github.com/microsoft/vscode/issues/48659#issuecomment-570815118). I only remove the RemoteCommand so I can use that and elevate permissions.

**Comment by roblourens** [comment]
I was investigating this in https://github.com/microsoft/vscode-remote-release/issues/4474, but am still unsure about the potential impact. Removing `bash` is not really workable however. WHy do you need that?

**Comment by kristoferpelchat** [comment]
@roblourens I updated my description above. I do NOT perform the `bash` portion of the workaround [here](https://github.com/microsoft/vscode/issues/48659#issuecomment-570815118). I only use the `RemoteCommand` portion and that works beautifully for me. IMHO, that is the only thing that needs to be addressed. Merely the ability to set the `RemoteCommand` to whatever you choose in your `config` `ssh` file (which for me is `sudo su -` to elevate permissions).

**Comment by roblourens** [comment]
You could test the version of the extension in https://github.com/microsoft/vscode-remote-release/issues/4474#issuecomment-779563693 and verify that it works for you.
