### ISSUE TITLE
Some remote servers not shutting down

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#4390]
![image](https://user-images.githubusercontent.com/323878/106185198-5b7e8780-6157-11eb-9673-e186a481b565.png)

These are servers from several insiders builds going back to 9 days ago. They should shut down when there are no active EH connections for a few hours. Do you know if anything changed @alexdima? 

Looking at the server log, most were started and never got a connection:

![image](https://user-images.githubusercontent.com/323878/106186396-14919180-6159-11eb-85fe-b3aa64e37fe0.png)

Just one of them did have connections and it looks like it tried to shut down:

![image](https://user-images.githubusercontent.com/323878/106186455-296e2500-6159-11eb-9f7f-ad004adc6a3f.png)

And that's a strange place to stop

![image](https://user-images.githubusercontent.com/323878/106188050-502d5b00-615b-11eb-99c3-2e70de47eaa4.png)

**Comment by alexdima** [comment]
The only thing that I can think of is that `this.dispose()` throws which prevents execution from reaching `process.exit(0)`.
The registered disposables are:
- `FileService`
- `DiskFileSystemProvider`
- `appInsightsAppender.flush()`
- `ErrorTelemetry`
Perhaps one of these decides to throw in their `dispose` method. I've added server-side start-up telemetry, so it might be the `appInsightsAppender`.

But this doesn't explain the other servers not going down. I never 100% understood the auto-shutdown logic you added here, could you walk me through it?

**Comment by alexdima** [comment]
It looks to me that perhaps `_waitThenShutdown` should be called from the `initialize` method as well? Otherwise a server without any connections will never shut down by itself, as you observe?

**Comment by roblourens** [comment]
I can add a try/finally on that, although I would expect the exception to show up in the log... 

So looking at the code, I'm wondering whether it actually broke recently or if this is a missing case. If you go through reconnection after a long time when the remote agent has shut down, then the ssh resolver will start an agent, and vscode will connect to it, and it decides that its EH is gone. So it never gets an EH. So either we need to start the timer right away or change the ssh resolver to not start a new agent during reconnection.

**Comment by roblourens** [comment]
Yeah I guess it should be safe to start an agent that never gets a connection. If this isn't new then I don't know why I don't have 12 months of agents running. But I'm trying to see if it reproes in stable.

**Comment by roblourens** [comment]
Stable has this same behavior, I'll fix it in Feb

**Comment by pete312** [comment]
VSCode server does not shutdown on vscode exit.  Ive tried the option of closing the window. exit vscode and close connection. All of which leave the 

from linux client  (centos7 with mate wm https://mate-desktop.org/ )  Im seeing the in

**Comment by roblourens** [comment]
Steps

- Connect to a Remote-SSH host
- Separately `ssh yourHost` in a local terminal in another window, so you can run commands without a vscode server
- In that terminal, run `ps ax | grep server-main` and verify that the vscode server from step 1 shows up
- In a local vscode window, run "Kill VS Code Server on Host", pick the host that you connected to in step 1. This kills that server process
- Verify that window gets permanently disconnected
- In the ssh terminal, run the `ps` command again and verify that a server appears, it was started by the window trying to reconnect
- Wait at least **5 minutes**
- In the ssh terminal, run the `ps` command again and verify that the server has shut down, since it never got a successful connection
