### ISSUE TITLE
Persistent Terminal Sessions break SSH Forwarding

### ISSUE THREAD

**Issue by ob** [microsoft/vscode-remote-release#4391]
Issues that might be related: 
https://github.com/microsoft/vscode-remote-release/issues/1835
https://github.com/microsoft/vscode-remote-release/issues/4244
https://github.com/microsoft/vscode-remote-release/issues/2731

```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

Steps to Reproduce:

1. Open VS Code to an remote ssh server (I do it via the command line `code --folder-uri "vscode-remote://ssh-remote+$USER@$HOST/$PATH"`)
2. Open a Terminal in VS Code and verify that `SSHForwardAgent` is working:
```
% ssh-add -l
< my keys are in the output>
% ls -lad  $SSH_AUTH_SOCK  
lrwxrwxrwx 1 coder eng 31 Jan 28 18:59 /tmp/vscode-ssh-auth-sock-296507842 -> /tmp/ssh-yTxuJUVldI/agent.14507
% ls -lad  $(realpath $SSH_AUTH_SOCK)
srwxr-xr-x 1 coder eng 0 Jan 28 18:58 /tmp/ssh-yTxuJUVldI/agent.14507
```

3. Close the VS Code window and immediately connect again, then try the same:
```
% ssh-add -l
Error connecting to agent: No such file or directory
% ls -lad $SSH_AUTH_SOCK
lrwxrwxrwx 1 coder eng 31 Jan 28 18:59 /tmp/vscode-ssh-auth-sock-296507842 -> /tmp/ssh-yTxuJUVldI/agent.14507
% ls -lad $(realpath $SSH_AUTH_SOCK)
realpath: ‘/tmp/vscode-ssh-auth-sock-296507842’: No such file or directory
drwxr-xr-x 14 coder eng 4096 Jan 12 17:11 .
```

4. Now wait 5 minutes and connect again in the same way and it's fixed (output similar to 2).

**WORKAROUND**: you can turn off "Terminal > Integrated: Enable Persistent Sessions" and the issue goes away.

**POSSIBLE SOLUTION**: When Integrated Persistent Sessions are enabled, perhaps VS Code should abstract the `SSH_AUTH_SOCKET` via indirection. For regular `ssh`, I have this in my `~/.ssh/rc` file in the remote side:

```
$ cat ~/.ssh/rc
#!/bin/bash

if [ ! -S ~/.ssh/ssh_auth_sock ] && [ -S "$SSH_AUTH_SOCK" ]; then
  ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi
```

Which allows me to reconnect multiple times and reuse the `SSH_AUTH_SOCK` if it has already been established by another ssh session.

**Comment by roblourens** [comment]
Thanks for the analysis - you are right, but I think https://github.com/microsoft/vscode-remote-release/issues/1835 is the only way forward. We do rewrite SSH_AUTH_SOCK with this vscode-owned path so that we can patch it up for reconnections (within the same window, when its connection is lost) but there isn't really a good way for me to do this when a new terminal is persisted in a new window, other than what I have to do in the other issue, which is having the user reload the terminal with a fixed environment.
