### ISSUE TITLE
Prompt to reopen in dev container not showing up

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-remote-release#4392]
- VSCode Version: Insiders
- Local OS Version: Windows
- Remote OS Version: 
- Remote Extension/Connection Type: Docker Compose

Testing #4297

Steps to Reproduce:

1. Open a local VS Code workspace/folder with a valid docker file
2. The prompt suggesting that the workspace can be reopened in a container doesn't show up

**Comment by chrmarti** [comment]
The prompt is triggered when there is a `.devcontainer.json` or `.devcontainer/devcontainer.json` file in the workspace folder. Do you have one?

**Comment by rzhao271** [comment]
Yep, here's how my workspace looks:

![testworkspace-devcontainer](https://user-images.githubusercontent.com/7199958/106626762-e0d5b380-652c-11eb-8c8f-32c3a65d801f.PNG)

Extensions:
Extension | Author (truncated) | Version
-- | -- | --
terraform | 4op | 0.2.1
read-only-indicator | ale | 3.4.0
mock-debug | and | 0.45.4
vscode-intelephense-client | bme | 1.6.3
vscode-eslint | dba | 2.1.14
gitlens-insiders | eam | 2021.2.204
tsl-problem-matcher | eam | 0.3.1
EditorConfig | Edi | 0.16.4
vscode-npm-script | eg2 | 0.3.13
codespaces | Git | 0.6.1
vscode-memfs | jri | 0.0.3
git-graph | mhu | 1.28.0
vscode-docker | ms- | 1.9.1
dotnet-interactive-vscode | ms- | 1.0.207203
vscode-dotnet-runtime | ms- | 1.0.0
python | ms- | 2021.1.502429796
vscode-pylance | ms- | 2021.1.3
jupyter | ms- | 2020.12.414227025
remote-containers | ms- | 0.158.0
remote-ssh | ms- | 0.63.0
remote-ssh-edit | ms- | 0.63.0
remote-wsl | ms- | 0.53.2
cpptools | ms- | 1.2.0-insiders3
vscode-github-issue-notebooks | ms- | 0.0.60
vscode-js-profile-flame | ms- | 0.0.13
vsliveshare | ms- | 1.0.3577
vsliveshare-audio | ms- | 0.1.91
vsliveshare-pack | ms- | 0.4.0
debugger-for-chrome | msj | 4.12.12
vscodeintellicode | Vis | 1.2.11
explicit-folding | zok | 0.9.1
