### ISSUE TITLE
[bug] .ssh/config → inline comments not supported

### ISSUE THREAD

**Issue by razielvamp666** [microsoft/vscode-remote-release#4393]
`.ssh/config`:

```
Host server1 # thiS iS firsT serveR
        Hostname 1.1.1.1
        User user1
        IdentityFile ~/.ssh/id_rsa

# sepaRAted coMMent

Host server2 # SECOND SERVER
        Hostname 2.2.2.2
        User user2
        IdentityFile ~/.ssh/id_rsa
```

VS Code Remote Explorer's targets list:
![vscode](https://user-images.githubusercontent.com/20613106/106222108-34d95300-6222-11eb-92b0-6268814e70fb.jpg)

Looks like only rows started from # treated as comments.   
`^#` is the insufficient condition.

**Comment by roblourens** [comment]
Actually, this is unusual but this is correct for how ssh configs are parsed. `#hello` in the Host line declares a host named "#hello". Only `#` at the beginning of a line declares a comment.
