### ISSUE TITLE
Argument parsing bugs in activation command and script causing connection failure using username with whitespaces on a Windows host

### ISSUE THREAD

**Issue by zerychao** [microsoft/vscode-remote-release#4395]
- VSCode Version: 1.52.1
- Local OS Version: Windows_NT x64 10.0.21292 & Darwin x64 20.1.0
- Remote OS Version: Windows_NT x64 10.0.21292
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

Connecting macOS or Windows clients to Windows host using username with whitespaces like `Zery Chao` gets timeout errors and weird UI states.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Further inspection:

The log inside the `.vscode-server` directory on the server side gives me
```
(node:18828) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\Zery'
```
which indicates there's a problem with parsing of path arguments. So I checked the terminal output on the client side (both macOS and Windows) and found the subsequent path of argument `--connection-secret` in the server activation command is missing quotation marks:
```
[20:35:34.941] > Starting server: & 'C:\Users\Zery Chao\.vscode-server\bin\ea3859d4ba2f3e577a159bc91e3074c5d85c0523\server.cmd' --start-server --host=127.0.0.1 --enable-remote-auto-shutdown --port=0 --connection-secret C:\Users\Zery Chao\.vscode-server\.ea3859d4ba2f3e577a159bc91e3074c5d85c0523.token   *> 'C:\Users\Zery Chao\.vscode-server\.ea3859d4ba2f3e577a159bc91e3074c5d85c0523.log'
```
In the mean time, the argument parsing scripts inside mentioned `server.cmd`, namingly line 15 and 16
```
if "%1"=="" goto after_loop
set RESTVAR=%RESTVAR% %1
```
are using `%1` instead of `%~1`, making it problematic to parse arguments already with quotation marks. If I directly add quotation marks around the `--connection-secret` path, this script will go wrong since `"%1"` in the last loop will be replaced by `""C:\Users\Zery Chao\.vscode-server\.ea3859d4ba2f3e577a159bc91e3074c5d85c0523.token""` and creating semantic errors.

So my workaround is to manually change the `%1` in line 15 to `%~1` and replace `%1` in line 16 with `"%~1"` in the script and run the command with added quotation marks in another console before connection. It is now working smoothly but I don't think this is a decent solution.

**Comment by Ash258** [comment]
Can confirm issue on latest SSH nightly 2021.2.12420 and latest vscode insiders 1.54.0-insider Commit: 6ac9a3ecb3698e82bf901f11bbb5940f6bc3c197

- Local OS: Windows 10.0.19042 N/A Build 19042
- Remote OS: Windows 10.0.19042 N/A Build 19042

`& 'C:\Users\Development User\.vscode-server-insiders\bin\6ac9a3ecb3698e82bf901f11bbb5940f6bc3c197\server.cmd' --start-server --host=127.0.0.1 --enable-remote-auto-shutdown --port=0 --connection-secret C:\Users\Development User\.vscode-server-insiders\.6ac9a3ecb3698e82bf901f11bbb5940f6bc3c197.token --disable-telemetry *> 'C:\Users\Development User\.vscode-server-insiders\.6ac9a3ecb3698e82bf901f11bbb5940f6bc3c197.log'`

**Comment by aeschli** [comment]
Thanks @zerychao for the good analysis. I fixed the bat files.

Assigning to @roblourens to add quotes around the --connection-secret path
