### ISSUE TITLE
MacOS containers view empty on reconnecting to ssh docker host

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-remote-release#4399]
ref https://github.com/microsoft/vscode-remote-release/issues/4366 , #4362 

Following the steps in the test plan item, when I connect back to the remote-ssh host after the first connection, the containers view is empty and tells me that I do not have docker started.
![image](https://user-images.githubusercontent.com/8586769/106341363-de840880-6251-11eb-99db-b8aa6e9b58e1.png)

**Comment by chrmarti** [comment]
Did you have a folder open? Currently we need a folder open in Remote-SSH to work around microsoft/vscode#111371.

**Comment by JacksonKearl** [comment]
Yes, I confirmed I did have a folder open.

**Comment by chrmarti** [comment]
Could you append what is in your `Remote-Containers: Show Log` when you see this?

**Comment by JacksonKearl** [comment]
Haven't been able to reproduce.
