### ISSUE TITLE
ipdb debugging experience

### ISSUE THREAD

**Issue by ehu-ai** [microsoft/vscode-remote-release#4400]
Issue Type: <b>Bug</b>

When I use the remote SSH extension to edit some python files on the server, IPDB debugging through the integrated terminal has high latency when I try to step or print things.

Extension version: 0.63.0
VS Code version: Code - Insiders 1.53.0-insider (1a9dd758530782ee4bb09a15bdc484f3dcb9b5a3, 2021-01-26T05:23:15.725Z)
OS version: Darwin arm64 20.1.0
Remote OS version: Linux x64 5.4.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.54GB free)|
|Process Argv|--crash-reporter-id 69322fb5-a47e-49d2-b77b-ae6a6479595e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: DineshRoomServer|
|OS|Linux x64 5.4.0-52-generic|
|CPUs|Intel(R) Xeon(R) W-2295 CPU @ 3.00GHz (36 x 1200)|
|Memory (System)|251.40GB (91.53GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2prompt:30219162
vstry244:30244315
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139
pythonvspyt600cf:30251589
core-portspanelcf:30233468
coreuntitledfile:30249963

```

</details>

**Comment by roblourens** [comment]
Most likely this is just due to the latency in your network connection. If you think that python debugging is more high latency than other parts of vscode, please open an issue on the extension's repo.
