### ISSUE TITLE
Parse errors

### ISSUE THREAD

**Issue by cybath** [microsoft/vscode-remote-release#4401]
- VSCode Version:  Version: 1.52.1
- Local OS Version: 10.15.7
- Remote OS Version: Ubuntu 20.04.2
- Remote Extension/Connection Type: SSH/Docker/WSL

Reference [https://github.com/microsoft/vscode/issues/115470]

Loading v .62 does not resolve the error. 
when attempting to ssh on .62 error:
 [11:30:40.089] Failed to parse remote port from server output

@gjsjohnmurray

**Comment by roblourens** [comment]
Need more details. Please include the full log and try with the latest version of vscode and the extension.
