### ISSUE TITLE
Podman 3.0 RC has been released, under community testing. Please, adopt in vscode-remote-release implementation

### ISSUE THREAD

**Issue by PavelSosin-320** [microsoft/vscode-remote-release#4402]
Reference issue: https://github.com/microsoft/vscode-remote-release/issues/116#
#

@chrmarti Podman 3.0  RC has been released to community testing. I'm testing it under Fedora 33 WSL distro with systemd and genie for full features support.
It doesn't require root user privileges but supports them.
One of the main benefits is [Podman transport versatility](https://www.redhat.com/sysadmin/7-transports-features).  On another hand, the registry configuration and image specification are much stricter than in Docker and require separate the registries.conf file.

**Comment by chrmarti** [comment]
@PavelSosin-320 Does anything break with 3.0? I was expecting that the Podman CLI would remain compatible with the Docker CLI.
