### ISSUE TITLE
Can I use this remote extension to connect a Linux server requires SSH Key with passphrase? If yes, how? 

### ISSUE THREAD

**Issue by charlesschen** [microsoft/vscode-remote-release#4404]
🚨 The issue tracker is not for questions 🚨

If you have a question about VS Code, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code and about
VS Code Remote on https://stackoverflow.com/questions/tagged/vscode-remote.

**Comment by roblourens** [comment]
Yes. If it's not working, need more details and the log
