### ISSUE TITLE
Add ability to remove existing target in Remote Explorer

### ISSUE THREAD

**Issue by AaronMT** [microsoft/vscode-remote-release#4406]
Right clicked on a target in the remote explorer and there was no option to remove a target. I am looking for a way to remove a target in the UI. This should be trivial to add. Aside, how do I remove an existing target?

![Screen Shot 2021-02-01 at 1 42 04 PM](https://user-images.githubusercontent.com/102331/106503235-60af3f80-6493-11eb-83b6-5af848b90bd5.png)

Using v0.63.0

**Comment by roblourens** [comment]
These are just read from your SSH config file, you can remove them there
