### ISSUE TITLE
Renaming Inspect in VS Code to Explore using Remote Containers

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-remote-release#4408]
Currently, within the Docker Extension on the Volumes tab, when users right click a volume, they are given three options. 

![image](https://user-images.githubusercontent.com/20650058/106503837-03a78f80-647b-11eb-95a5-4bf03366316f.png)

The Docker team was discussing the naming of the second option "Inspect in VS Code" and feel that it is slightly confusing and could be more discoverable. The first option Inspect, simply opens up a json file with plenty of metadata about the volume. This second option is unclear because the user is already in VS Code and we all agreed it is a surprise to use that another VS Code is launched with a remote container and can show the user the volume file structure. 

We are requesting that this command be renamed to "Explore using Remote Containers" to provide greater visibility to this awesome extension and make it clearer to our users.

Sidenote: This feature is AWESOME 🚀🚀

**Comment by egamma** [comment]
@ucheNkadiCode thanks for the suggestion, it makes a lot of sense. Renames as follows:

![image](https://user-images.githubusercontent.com/172399/109154114-21ac9b00-776e-11eb-91ee-c6c6090364f2.png)
