### ISSUE TITLE
Randomly disconnecting from container

### ISSUE THREAD

**Issue by MartinBreznik** [microsoft/vscode-remote-release#4418]
- VSCode Version: 1.52.1
- Local OS Version: 1909 windows 10 pro
- Remote OS Version: ubuntu 18.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Connect to running container,
2. Start writing code,
3. Wait for what appear to be completely random disconnects (sometimes after an hour of work, sometimes instantly, often in short intervals),
4. Eather you get connected back after a few seconds or you're unable to establish another connection.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Is this with Docker Desktop running the Docker daemon locally?

**Comment by MartinBreznik** [comment]
Sorry for the delay, yes the issue happens with Docker Desktop running the Docker daemon locally.

**Comment by chrmarti** [comment]
Is the workspace folder on a WSL2 filesystem? Might anything pause or stop the container?

**Comment by MartinBreznik** [comment]
> Is the workspace folder on a WSL2 filesystem? Might anything pause or stop the container?

It's not using the WSL2 filesystem, nothing is able to stop the container as it stays online during the disconnect when checking with Windows Powershell. It was replicated multiple times using the exact same host pc state with different results, it was also replicated across the last 4 docker versions and multiple devices it's severity seems to slightly change from one update to another (some docker desktop versions seem to crash the extension a lot more often than others) it also seems that the crash frequency varies within the same docker desktop versions (one day it might crash 5-20 times/day, the other day it drops down to 2 times/day while using the exact same hardware and software on the host device).

**Comment by chrmarti** [comment]
Could you append your devcontainer.json, Dockerfile and any other files needed to reproduce this?

**Comment by chrmarti** [comment]
Please also append the log from such a session. (`F1` > `Remote-Containers: Show Log`)

**Comment by MartinBreznik** [comment]
Remote-containers log:
[remote container.log.txt](https://github.com/microsoft/vscode-remote-release/files/6108426/remote.container.log.txt)

container image used: 
https://hub.docker.com/_/ubuntu

dockerfile:
not used

devcontainer.json:
not used

**Comment by chrmarti** [comment]
Is there anything additional in the dev console? (`Help` > `Toggle Developer Tools`)

**Comment by chrmarti** [comment]
Maybe check with VS Code Insiders 1.55 and the latest Remote-Containers version (that comes with a fix that might affect this).
