### ISSUE TITLE
Dev containers url decode websites

### ISSUE THREAD

**Issue by dmateusp** [microsoft/vscode-remote-release#4421]
- VSCode Version: 1.52.1
- Local OS Version: Darwin x64 19.6.0
- Name of Dev Container Definition with Issue: Python 3

I am trying to set up a `devcontainer` to develop on [dbt](https://www.getdbt.com/). In our set up we use the [snowflake-connector-python](https://github.com/snowflakedb/snowflake-connector-python/) to authenticate to our Data Warehouse through SSO + Web browser.

Inside a dev container, the authentication fails and I have tracked it down to the devcontainer url decoding websites before opening them. (It decodes the SAML request)

Here's a a simple command that reproduces the issue:

```bash
python -mwebbrowser https://google.com/hello%2Fworld
```

Opens `https://google.com/hello/world` on my host machine rather than `https://google.com/hello%2Fworld`.

**Comment by rzhao271** [comment]
Verified. The web page opens properly, though the dialog still shows the decoded URI.
![slash](https://user-images.githubusercontent.com/7199958/109201617-e783cf00-7756-11eb-8e09-8ed333f213b9.PNG)
