### ISSUE TITLE
APT: The keys are ignored as the file has an unsupported filetype with Vscode connecting.

### ISSUE THREAD

**Issue by mashirozx** [microsoft/vscode-remote-release#4422]
- VSCode Version: 1.52.1
- Local OS Version: Windows_NT x64 10.0.19041
- Remote OS Version: Ubuntu 20.04.2 LTS (Ubuntu Base)
- Remote Extension/Connection Type: SSH

Local:
```
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

Remote:
```
LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

Steps to Reproduce:

1. Install a new Ubuntu Base Environment
2. Connect with Vscode through SSH
3. Run `apt update`, got gpg key errors below (but warnings doesn't show on device's original console, I mean without vscode connecting):

apt update through vscode remote ssh session console:
![image](https://user-images.githubusercontent.com/16148054/106976168-e5030a80-6792-11eb-815e-623ed64a78f5.png)

apt update on device only (no vscode connecting):
![image](https://user-images.githubusercontent.com/16148054/106976301-1c71b700-6793-11eb-80d4-5e7009faf9e9.png)

NB: Actually I installed the Ubuntu Base on my Android device through [Termux](https://github.com/termux/termux-app), the Ubuntu image install script [here](https://github.com/MFDGaming/ubuntu-in-termux/blob/master/ubuntu.sh). The Android host device info follows:
![image](https://user-images.githubusercontent.com/16148054/106977025-7e7eec00-6794-11eb-8d6b-6cae8f111693.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
"on device only" is this normal SSH in a terminal or in a local session? Can you try in a normal SSH session outside of vscode to compare?

**Comment by mashirozx** [comment]
> apt update through vscode remote ssh session console:
> ![image](https://user-images.githubusercontent.com/16148054/106976168-e5030a80-6792-11eb-815e-623ed64a78f5.png)
> 
> apt update on device only (no vscode connecting):
> ![image](https://user-images.githubusercontent.com/16148054/106976301-1c71b700-6793-11eb-80d4-5e7009faf9e9.png)

Well, the first screenshoot was ran on vscode through Remote SSH, the second  one was ran on the Ubuntu device's screen directly (no any SSH connect).

But I also tesed a normal SSH session like Putty was also OK, it didn't have any warning after `apt update`, and the apt warnings occur only in SSH session through Vscode remote.  I don't know if Remote SSH did anything on system underlying layer? 

I also use Remote SSH to connect normal Ubuntu server, never met this trouble before, not sure if it is because [Ubuntu Base](https://wiki.ubuntu.com/Base) is defferent?

**Comment by roblourens** [comment]
Sorry, I just don't know anything about this, and I can't help troubleshoot it. A good first place to start might be to run `printenv` in all scenarios and check whether there is anything different about the environments.
