### ISSUE TITLE
Git credential still copied to container even if `remote.containers.gitCredentialHelperConfigLocation` is set to "none"

### ISSUE THREAD

**Issue by zhanzhenzhen** [microsoft/vscode-remote-release#4426]
- VSCode Version: 1.52.1 (and also 1.53)
- Local OS Version: macOS Big Sur 11.2
- Remote OS Version: Alpine 3.12
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

Set these settings:

```
"remote.containers.copyGitConfig": true
"remote.containers.gitCredentialHelperConfigLocation": "none"
```

Git config isn't copied. That's good. But the credential helper is still connected to the local environment. I can `git clone` any of my private repos without entering password in the container's `ash` shell.

When I type `git config --list` in container's shell, there's still a `credential.helper` section:

```
credential.helper=!f() { /root/.vscode-server/bin/...
```

The difference is that when `gitCredentialHelperConfigLocation` is `"global"`, there're 3 `credential.helper` lines:

```
credential.helper=!f() { /root/.vscode-server/bin/...
credential.helper=!f() { /root/.vscode-server/bin/...
credential.helper=!f() { /root/.vscode-server/bin/...
```

When it's `"none"`, there's only one `credential.helper` line.

I want to use container to isolate the code, which may be harmful to my local computer. I don't want the code in the container to know my Git password or be able do any Git operation like in my local environment. But now there seems no isolation regarding Git.

Does this issue occur when you try this locally? No
Does this issue occur when you try this locally and all extensions are disabled? No

**Comment by chrmarti** [comment]
I'll check why `"remote.containers.gitCredentialHelperConfigLocation": "none"` doesn't fully disable the forwarding.

This won't make the container safe to run untrusted code though. 1) We also forward ssh and gpg agents. 2) Docker containers are not considered a secure sandbox.

**Comment by aeschli** [comment]
Verified by
 - in the settings add 
 ```
"remote.containers.copyGitConfig": true
"remote.containers.gitCredentialHelperConfigLocation": "none"
```
- create a new container
- `git config --list` in the container does not show `credential.helper=!f() { /root/.vscode-server/bin/...`

- remove the settings
- ope the container again, `git config --list` shows `credential.helper=!f() { /root/.vscode-server/bin/...`
