### ISSUE TITLE
Offer to update the port attributes in devcontainer.json when a user assigns a label to a port

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#4433]
When the user assigns a label to a port in the Ports view there should be support to update the `portAttributes` label in `devContainer.json.

![image](https://user-images.githubusercontent.com/172399/107155722-46390280-697a-11eb-9a6b-1cdd9c96d254.png)

This is similar to supporting updating the devContainer.json from the extensions view.

**Comment by chrmarti** [comment]
Do we update the label in the machine settings? Would we add a port to the machine settings or only update existing ones?

The devcontainer.json is shared and persists across rebuilds. Would we want the default to be that changes are not shared, but persist across rebuilds? (Not sure we can do that currently.)

**Comment by egamma** [comment]
The goal is a good experience for the consumers of a devcontainer. This means the label should come from the devcontainer.json so that all users benefit from an assigned label. 

One way to make this explicit would be to have a separate action 'Set Label and update devcontainer.json'.
