### ISSUE TITLE
Enable the Simple Browser for previewing end points exposed by forwarded ports

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#4436]
Support to preview a service running on a forward port in an editor on the side as shown below.

This should only be enabled on the desktop and not in the Web

![image](https://user-images.githubusercontent.com/172399/107160186-ff0c3b00-6994-11eb-8c2b-e6714a00e7c5.png)
<img width="628" alt="image" src="https://user-images.githubusercontent.com/172399/107186550-c431f380-69e4-11eb-97cb-6d097b142616.png">

**Comment by egamma** [comment]
See also https://github.com/microsoft/vscode-remote-release/issues/4434

**Comment by alexr00** [comment]
@mjbvz For forwarded ports, I always want to open the simple browser (or whatever installed opener the user has) to the side. The appears to be the default right now. 👍

However, would it make sense to clearly define this in the API? In the API, there are no open options:

https://github.com/microsoft/vscode/blob/d0205792b0e01ae323cd9c7ef4c10b517e820da4/src/vs/vscode.proposed.d.ts#L2516-L2533

Should the external opener API support something like `ViewColumn`?

https://github.com/microsoft/vscode/blob/5115a8eae7919a3a75ace7a770d666f3fcf036c4/src/vs/vscode.d.ts#L753-L760

**Comment by mjbvz** [comment]
@alexr00 We currently leave this up to the opener implementation.  The simple browser does support view column for its own command: https://github.com/microsoft/vscode/blob/542de8e0093d4ba36c3ace23a663b9f68d76d8ba/extensions/simple-browser/src/extension.ts#L42


The original intent of `openExternal` was to launch an external program, so some options such as view column would not always make sense. I'll think about it more to see if there's a good compromise

**Comment by alexr00** [comment]
Closing this issue as completed then, since simple browser opens to the side by default.
