### ISSUE TITLE
Icons missing in the Simple Browser - when used for previewing forwarded ports

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#4437]
pls see the screenshot below

![image](https://user-images.githubusercontent.com/172399/107187440-4a026e80-69e6-11eb-8896-f8eb738f1d84.png)

**Comment by mjbvz** [comment]
Confirmed in remote. Should be fixed by https://github.com/microsoft/vscode/commit/46e28e3bbea3c33771ca999402350b1b17527d0c

To verify:

1. Connect to a ssh workspace
2. set:

     ```
	"workbench.externalUriOpeners": {
		"*": "simpleBrowser.open"
	}
     ```

3. Click on a link to `http://example.com` in a file to open the simple browser
