### ISSUE TITLE
WSL console hangs after a few minutes of work

### ISSUE THREAD

**Issue by AlexanderBodnya** [microsoft/vscode-remote-release#444]
Issue Type: <b>Bug</b>

Every few minutes WSL console becomes unresponsive and hangs with all extensions installed inside WSL and all other things such as linter, Pyton interpreter and such.

Happens most during unit tests runs

Extension version: 0.36.0
VS Code version: Code - Insiders 1.35.0-insider (5e1f9440d280b0b04cba843df6a0032bf517a2f0, 2019-05-24T05:18:40.781Z)
OS version: Windows_NT x64 10.0.16299
Remote OS version: Linux x64 4.4.0-43-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (8.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-43-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|15.81GB (8.44GB free)|
|VM|0%|
</details>

**Comment by lars18th** [comment]
Hi @AlexanderBodnya ,

Perhaps related to #443. I see that the behaviour is unstable when the remote host is doing intesive tasks.

Regards.

**Comment by AlexanderBodnya** [comment]
Hello, @lars18th 

I didn't investigate the issue thoroughly, but I think it might be the reason. I saw CPU consumption by node server skyrocketed when the issue occured. I was not able to see server logs, unfortunately, for apparent reasons.

**Comment by AlexanderBodnya** [comment]
After today's update I'm unable to reproduce the issue at request. I've used Remote - WSL extension for the few hours and it worked OK. I think the issue can be closed, since it works OK now and I'm unable to reproduce on demand.
