### ISSUE TITLE
echo Not found

### ISSUE THREAD

**Issue by mathewgomas** [microsoft/vscode-remote-release#4440]
Issue Type: <b>Bug</b>

Visual Studio Code Server

Extension version: 0.53.2
VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.93GB free)|
|Process Argv|--crash-reporter-id 073c2452-087d-46d8-847c-a77a1e6fdca4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz (4 x 3600)|
|Memory (System)|3.03GB (2.83GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Need more details
