### ISSUE TITLE
Support 32-bit remote development (simple workaround suggestion)

### ISSUE THREAD

**Issue by rganesan** [microsoft/vscode-remote-release#4453]
I understand there's no interest in supporting 32-bit (i686 arch) which I fully understand. We unfortunately are stuck having to develop for a 32-bit environment. The good news is we can install 64-bit libraries (glibc, libstdc++) and therefore 64-bit node binaries. We have managed to get VS Code Remote working reasonably well with this setup. 

The only glitch is that the Linux personality defaults to 32-bit and the shell reports arch as i686. This causes remote installation to bail out. We have managed to work around this by setting an SSH environment variable in ssh_config and using it to fake the arch in the shell launched by remote. This mostly works but breaks some stuff (for example build tools choose the wrong target directory). 

So this is an enhancement request to add an extension setting to disable the arch check in the remote shell. By disabling the arch check, I mean simply assume that remote is a supported architecture and proceed. This will help other developers stuck in a 32-bit environment like us but can use this workaround (install 64-bit libraries needed for VS Code Remote). I suspect this may also ease developing support for other architectures that are currently unsupported.

**Comment by roblourens** [comment]
From an offline discussion, we decided that if we detect a 32-bit OS, we can probe `uname -r` for the string `x86_64` to check for 64-bit support. This solution is sort of particular to this customer but I think it's safe and reasonable.

**Comment by rganesan** [comment]
Thanks for the prompt resolution on this issue. Much appreciated!

**Comment by aeschli** [comment]
@rganesan Can you verify that fixes works?

**Comment by Imagix** [comment]
I'm the "offline discussion" with roblourens.  Yes, it works.  I've been using it for the last 2 weeks and it has not had any trouble.

**Comment by rzhao271** [comment]
Marking as verified based on comment above.
