### ISSUE TITLE
Suggest storing source code in WSL2 when /mnt folder is opened

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#4454]
When using WSL 2 on the Windows file system mount we want to show a recommendation to recommend moving the project files to the Linux file system for optimal file system performance.

More information can be seen at https://docs.microsoft.com/en-us/windows/wsl/compare-versions#performance-across-os-file-systems

**Comment by aeschli** [comment]
@bamurtaugh The current message is:
`You're currently using WSL 2 on the Windows file system mount. If possible, move your project files to the Linux file system for optimal file system performance.` with a link to https://docs.microsoft.com/en-us/windows/wsl/compare-versions#performance-across-os-file-systems

Feedback and improvements are welcome!

**Comment by bamurtaugh** [comment]
I like the prompt! For users who may not be aware of this issue, or who may not fully understand the difference in the file systems, I think the link to the doc will be really helpful. 

I'm curious to see how people interact with the prompt, and also how many people get it in the first place (i.e. how prominent of an issue is this) and how many people continue getting it over time (i.e. do we see a decline over time if folks are now aware of the best practice/change their storage techniques?).

**Comment by aeschli** [comment]
Right now, the message will show up as long as the user has pressed 'Do not show again'.

I made an update so that we also get telemetry when the dialog is not showing due to  'Do not show again'. That way we can measure if the non-performant usage of WSL1 resp WSL2 declines.

**Comment by bamurtaugh** [comment]
I think that's a good addition too! I think the telemetry we have in place should now help us see if this prompt sparks user interest and affects behavior/helps their performance over time.

**Comment by PavelSosin-320** [comment]
@dbaeumer Think twice!
Cons of the Linux rootFS usage:
1. Limited size. When it is full then expansion of RootFS esxt4 vhxd is a mess
2. No automatic backup in Azure and other backup services - configuration is required. It likes to fail and hang OneDrive
3. Export to tar and moving to the Cloud storage requires 10Gb local free space at least and may last a long time if the connection is not very fast.
4. Reading from Linux RootFS to the Windows FS is not too fast too. It is slow.

**Comment by dbaeumer** [comment]
I think you meant @aeschli.

**Comment by PavelSosin-320** [comment]
I mean the maintenance problems can overweight performance gains. Many maintenance functions executed on the Windows folders automatically don't cover Linux FS, starting from virus scan to automatic cloud backup. The rootFS is ext4, i.e. no remote FS access or sharing is possible. Is any IT automation possible? The decision to use this feature produces massive additional, unexpected IT workload from a developer.
