### ISSUE TITLE
Unable to make the extension work on ubuntu 18.04

### ISSUE THREAD

**Issue by sym39** [microsoft/vscode-remote-release#446]
Hello all, 

I tried multiple times to install the "Remote Development extension pack" without success.

Here the error message:
```
Unable to install because, the extension 'ms-vscode-remote.vscode-remote-extensionpack' compatible with current version '1.34.0' of VS Code is not found.
```

Here the installed versions of code and code-insiders in my machine
```
dpkg -l
ii  code                                          1.34.0-1557957934                                        amd64        Code editing. Redefined.
ii  code-insiders                                 1.35.0-1558675526                                        amd64        Code editing. Redefined.
```

Also I tried installing via snap without success too (apparently same versions are installed)

Is the extension not working yet on ubuntu or do I miss something?
Thanks in advance,

--
Sylvain

**Comment by egamma** [comment]
>Unable to install because, the extension 'ms-vscode-remote.vscode-remote-extensionpack' compatible with current version '1.34.0' of VS Code is not found.

You must install the extension in the VS Code Insider version, pls see the documentation.

**Comment by sym39** [comment]
> > Unable to install because, the extension 'ms-vscode-remote.vscode-remote-extensionpack' compatible with current version '1.34.0' of VS Code is not found.
> 
> You must install the extension in the VS Code Insider version, pls see the documentation.

Ah - my bad, I though that code-insiders was a component/library used by the code binary itself - the name "extension" sounds more "library" that "binary" to me, sorry for this mistake.
--
Sylvain
