### ISSUE TITLE
Ssh remote - manage to connect through the terminal, but not through the remote explorer

### ISSUE THREAD

**Issue by tristanlefranc** [microsoft/vscode-remote-release#4463]
Evening... So I am coming from notepad, and learning how to work with VScode.
 So far, I learned a lot, find lot s of issue and over came those, but am now stuck with an issue I do not understand. 

I am now trying to access my online repertory on my webserver.
 I followed up the guide here: https://code.visualstudio.com/docs/remote/ssh

I did manage to access my server through the terminal window / shell,
I typed `ssh user@domain` then my password
It connected and  showed the following  in the log :

> "Linux infong-eu27 4.4.246-icpu-061 #2 SMP Thu Nov 26 10:58:41 UTC 2020 x86_64"

This tells me that it is working on Linux.
I could see my repertory on the distant server by typing  "Ls", and could navigate among them. 
So far, so good!

Second phase: Connecting through the remote explorer.

step 1:
 I configured the ssh with the same credential I used with the terminal.

step 2:
 I am opening the "remote explorer", I can see my server's name. I right click on it and select "connect".
![image](https://user-images.githubusercontent.com/78965143/107834733-5a746980-6d97-11eb-9b7b-110944a68301.png)

Step 3:
I am then asking to choose the system. I am picking Linux as show earlier when connecting through the terminal.

Step 4: 
I am entering the same password i used before to connect in the terminal.

step 5
 well, infinite loading... or very long one till I get 2 notifications / errors:

1. Could not fetch remote environment
2. Failed to connect to the remote extension host (error time limit..)
![image](https://user-images.githubusercontent.com/78965143/107835239-0cf8fc00-6d99-11eb-8bf2-002eadf10c25.png)

That being said, also, it says in the bottom left corner, in the "remote window", it show the server I tried to connect on.
![image](https://user-images.githubusercontent.com/78965143/107834825-b0491180-6d97-11eb-850d-e54428a664aa.png)

Now, when I looked with my ftp software, it seems that VS did manage to access the folder, as it created a folder and files in it, on my distant webserver 
![image](https://user-images.githubusercontent.com/78965143/107834919-0453f600-6d98-11eb-9f5e-f91ca563520a.png)

I also, managed following your instruction, to crate a ssh pair key. Copied through terminal the part on my distant server, and modified the ssh config file in Vs, by adding identifykey and the file name, and was successful.
when i tried to connect to my remote server right after, i was not asked for my password, but my key pass. 
but again, same issue ... super loading and timed out. 

Any clue on how I could fix this? 
Thankyou in  advance! 

...

**Comment by bamurtaugh** [comment]
Thanks for reporting @tristanlefranc. Do your local and remote systems meet the requirements here: https://code.visualstudio.com/docs/remote/ssh#_system-requirements? What type (version, OS) of local and remote systems are you using?

Would you be able to include your Remote - SSH output logs as well?
