### ISSUE TITLE
Remote - SSH (Nightly) - installation clarification

### ISSUE THREAD

**Issue by dugaquilin** [microsoft/vscode-remote-release#4465]
disclosures
 - very new to vscode
 - using putty for raspberry pi for years
 - leaning node.js

Question: in the Vscode  program the Extension Pack (1) says the following:
Installation
Install VS Code or VS Code - Insiders and this extension.

Install an OpenSSH compatible SSH client.

If you do not have a SSH host set up, follow the directions for Linux, Windows 10 / Server (1803+), or macOS or create a VM on Azure.

[sorry, cut and paste from vscode to here looses formatting]
The 2nd point says - install an OpenSSH compatible SSH client.

I have Putty installed on my Windows computer already and it is working.
I have Windows 1- x64 and when I go to the command prompt and enter ssh - pi@mypihostname ... it works

So, what do you mean install an OpenSSH compatible SSH client?  
do you mean install it on the Raspberry Pi (aka the remote client)
Or
do you mean install it on the Windows computer that I am trying to do the remote vscode connection to the pi from

The statements are not clear enough for me to know which.

I am not able to get my vscode on windows to connect to my raspberry pi, which is working fine for my putty SSH sessions.

maybe there are some assumptions being made by the people writing the instructions and perhaps should not be overlooked.

Thanks

**Comment by zersiax** [comment]
I believe that the extension depends on the ssh command actually being available on your path. Putty is a GUI to connect over SSH, but doesn't allow other programs to leverage that same functionality.
If you open cmd, and you type ssh, and you get the old " ssh is not recognized as a command, operable program or batchfile"  notification, there's your issue.
From memory, I believe you can enable the openSSH client from Windows Optional features these days, or with this powershell command:
Add-WindowsCapability -Online -Name OpenSSH.Client*
May need to reboot after, but should get you unstuck :)

**Comment by bamurtaugh** [comment]
Thanks for opening @dugaquilin. I think https://code.visualstudio.com/docs/remote/ssh#_system-requirements may help clarify a bit as it specifies "Local: A supported OpenSSH compatible SSH client must also be installed," which would be your Windows machine. Perhaps we could consider updating the extension's readme to make it clearer.

As for why you may be having trouble getting your Pi to connect: the version of your Pi may be playing a role. For instance, we have the following feature request open for armv6l on a Raspberry Pi Zero: https://github.com/microsoft/vscode-remote-release/issues/669. There's also the following issue open for the Raspberry Pi 4: https://github.com/microsoft/vscode-remote-release/issues/3248. 

We also have the following open for PuTTY Pageant, in case it may be relevant: https://github.com/microsoft/vscode-remote-release/issues/61.
