### ISSUE TITLE
Can't work with Remote-SSH on complex (but common) setup

### ISSUE THREAD

**Issue by voldemortX** [microsoft/vscode-remote-release#4467]
- VSCode Version: 1.53.2
- Local OS Version: Win10
- Remote OS Version: Ubuntu 20.04.1
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.  My use case is: I have my own laptop (win10 with vscode), and I want to connect to my server, which is in fact a container mounted by root in a physical remote server, which does not use SSH at port 22, and my login user does not have root access. 
2. Usually when I SSH my server with other software, after entering password there would be a selection menu for different mounted containers, but when I use vscode-remote, this selection menu does not appear and I can't get in any containers. Although I can still browse my files.
3. Because of this, there are 2 other problems. First, there is no wget or curl, so I choose `LocalSeverDownload`, but it always try to upload `vscode-server-linux-x64.tar.gz` via port 22 (my server does not use 22 for SSH), **that should be a bug?** I have to upload that file manually to make the connection. Although after that, the extensions can be correctly uploaded without trouble.
4. Second, the vscode process does not quit after I close vscode on my laptop, which results in I can't connect again until that process quit on linux side (either automatically a couple minutes after, or my manager use root to terminate it manually).

My use case is quite common actually, for people who use remote servers inside NAT with different container environments, and don't have root access. And I just can't make it work with vscode-remote.
Feel free to close this if the solution need to be on my own, not on this extension.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
You might want to read about developing in remote containers: https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host

> my server does not use 22 for SSH

You will need to set up an ssh config which specifies the port.

> the vscode process does not quit after I close vscode on my laptop, which results in I can't connect again until that process quit on linux side

The server stays running for a bit. Why is this a problem, what error do you get trying to connect again?

**Comment by voldemortX** [comment]
> You might want to read about developing in remote containers: https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host
> 

Thanks, I'll try that. But that means I still need docker on my local machine.

> 
> You will need to set up an ssh config which specifies the port.
> 

I did specify the port and I successfully connected to remote. It is only the vscode-server files, they still try to upload through port 22, thus I had to manually copy the files.

> The server stays running for a bit. Why is this a problem, what error do you get trying to connect again?

The server stays running for a few minutes I think. If I reconnect within these minutes, I get "Could not establish connection to <remote ip> Downloading vscode-server failed, please install either curl or wget on the remote". Seems to be a redundant attempt to download vscode-server files even when the files are already there. If I ask my administrator with root access to kill the vscode-server thread or wait for it to timeout, I can reconnect without issues.

**Comment by voldemortX** [comment]
@tanhakabir I did not install docker on my local machine, so I still have to do the task kill & sometimes manual file upload (after updates). Anyways, I guess in my case a FTP sync plugin is more appropriate.

**Comment by tanhakabir** [comment]
I see! I'm sorry we couldn't completely solve this for you! I'm closing this issue for now since it seems you've found a workaround
