### ISSUE TITLE
mangled `node_modules` path 

### ISSUE THREAD

**Issue by haberdashPI** [microsoft/vscode-remote-release#447]
Issue Type: <b>Bug</b>

I see the following error on my remote ssh project:

`spawn /home/davidlittle/.vscode-remote/bin/5e1f9440d280b0b04cba843df6a0032bf517a2f0/node\_modules/vscode-ripgrep/bin/rg ENOENT`

Looks like `node_modules` is being mangled into `node\_modules` for some reason?? The file `/home/davidlittle/.vscode-remote/bin/5e1f9440d280b0b04cba843df6a0032bf517a2f0/node_modules/vscode-ripgrep/bin/rg` exists on the remote host.

Extension version: 0.37.0
VS Code version: Code - Insiders 1.35.0-insider (5e1f9440d280b0b04cba843df6a0032bf517a2f0, 2019-05-24T05:15:17.681Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 3.10.0-957.5.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|-psn_0_807109|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.160.200.212|
|OS|Linux x64 3.10.0-957.5.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (4 x 1200)|
|Memory (System)|62.45GB (3.00GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Can you clarify where you see the error and what you are trying to do?

**Comment by haberdashPI** [comment]
This bug comes up *sometimes* when I try to use cmd-P to open a file. But sometimes it works just fine. I haven't narrowed down the situations where it does or doesn't occur. I will keep an eye out for it and provide any further details that I can identify that lead to the problem.
