### ISSUE TITLE
unable to open 'ssh_repositorie'

### ISSUE THREAD

**Issue by F-Y-M** [microsoft/vscode-remote-release#4477]
Unable to open 'ssh_repositorie': Unable to read file 'vscode-remote://ssh-remote+7v44e623a22534465223a225354433a22227d/repositories/ssh_repositorie' (Error: No remote extension installed to resolve ssh-remote.).

this is the message that shown when try to connect to my repositorie, i try uninstall it and reinstall it but doesn't work, even uninstall the visual. and if try to connect another repositorie this message show:

Command 'Remote-SSH: Add New SSH Host...' resulted in an error (command 'opensshremotes.addNewSshHost' not found)
 
![imagen](https://user-images.githubusercontent.com/55666365/108080967-6e8dc480-703e-11eb-9b6c-ca719b9af0ea.png)
and no configuration icons appear. i already have installed ssh in my computer, thanks for your answers

**Comment by bamurtaugh** [comment]
Thanks for filing @F-Y-M. Just to clarify:

- Which version of the Remote-SSH extension do you have installed in VS Code?
- Are you able to connect to your SSH box by other means (i.e. in an external terminal not in VS Code)?
