### ISSUE TITLE
Look for common ssh command locations if ssh not found in the path

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#448]
After observing customers setting up SSH on Windows, one of the challenges is that customers face is that SSH may not be in the path even if it is installed on the system.  In particular a SSH client is delivered with Git that is on a large percentage of systems but Git's install defaults do not put it in the path. Things can be further confused by the fact that developers may have VS Code's terminal set to to use Git's bash implementation, WSL, or be externally using something like [cmder](https://cmder.net/) that makes it appear `ssh.exe` is in the path when it actually is not. Windows 10 ships a native client, but it is not present by default and not everyone knows about it.

I'd propose we enhance the SSH detection code to do the following in order of precedence:
1. settings.json specified path
2. ssh from the path
3. %WINDIR%\System32\OpenSSH\ssh.exe (where Win 10 installs it)
4. %PROGRAMFILES%\Git\usr\bin\ssh.exe
5. %PROGRAMFILES(x86)%\Git\usr\bin\ssh.exe
6. wsl ssh (need to verify this works well particularly on WSL 2)
6. Error with a good message saying SSH was not found directing people to use settings.json if required.

//cc: @roblourens

**Comment by jdevmx** [comment]
There is another situation when your company policies don't allow you to add the path, that is my case, I know about OpenSSH, I know how to install it but can't install it cause of that. So I really think that this will be a good feature
