### ISSUE TITLE
Remote SSH password entry box looks like it has focus but does not have focus

### ISSUE THREAD

**Issue by LuAPi** [microsoft/vscode-remote-release#4484]
- VSCode Version: 1.53.1
- Local OS Version: Windows 10 Pro build 19041.804
- Remote OS Version: macOS 10.12.6 , Ubuntu 16, Ubuntu 18, Ubuntu 20
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to a SSH remote you use a password for authentication for. You will be prompted for the password when the password entry box already having focus and you can immediately start typing (expected behaviour).
2. Open a new VSCode window and open another SSH remote from the recent list (or right clicking on the vs code icon and picking from that recent list) that you also use a password for authentication.
3. A new VSCode window opens with a password entry prompt with a blinking cursor and blue border indicating the field has focus, if you start typing nothing is entered in the field, you have to actually click in the field before typing. Clicking on another window does properly defocus the field.

Alternatively:
1. Close all VSCode windows and give something else focus
2. Right click on the pinned VSCode icon on the start bar and select a recently used remote SSH entry that you use a password to authenticate
3. A new VSCode window opens with a password entry prompt with a blinking cursor and blue border indicating the field has focus, if you start typing nothing is entered in the field, you have to actually click in the field before typing. Clicking on another window does properly defocus the field.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No
Can't really test this locally, but it does still happen with all extensions except SSH remote disabled.

**Comment by roblourens** [comment]
I don't understand the difference between steps 1 and 2. Does this happen when there are 2 password boxes active at once, or does it depend on how you start connecting? I can't reproduce it.

**Comment by LuAPi** [comment]
There aren't ever two password boxes active at once.
The difference between steps 1 and 2 of the steps to reproduce is that at the start of step 2 the window that has focus is the window that was opened and connected at the end of step 1, where as at the start of step 1 you just have the default local vscode starting window open.

I just tried it again and I had to repeat step 2 twice this time.
I also tested just running one monitor instead of three to see if it was a multi-monitor issue but that had no effect.

If it helps when this issue occurs the vscode icon is pulsing orange on the start bar while the new window is on top with it's password entry box looking like it is selected.

**Comment by roblourens** [comment]
Can't repro this. The orange blink means that the window is not actually focused. I still don't understand how you are opening a new vscode window in the background, please tell me exactly what buttons you click. But it sounds like there is a disagreement between the OS and Electron about whether the window is focused and I doubt there's anything I can do about it.
