### ISSUE TITLE
Sync to remote often does not work

### ISSUE THREAD

**Issue by challamzinniagroup** [microsoft/vscode-remote-release#4486]
Issue Type: <b>Bug</b>

Very frequently (maybe 50% of the time?) saving a file does not sync back to the remote source. Multiple saves on the same file version has no effect: I sometimes have to continue making different edits two, three, even four times, before a save will finally sync to remote. The remote source in my specific case is an already hosted website consisting of pure HTML, CSS, and JavaScript. Edit a file, save, refresh the browser tab - nothing. No changes. Make a new edit, save, refresh browser, still nothing. A third edit, save, refresh, and finally - the changes have synced back and now display. 

Extension version: 0.64.0
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.4.0-65-generic snap
Remote OS version: Linux x64 4.19.0-12-cloud-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3162)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.29GB (1.93GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id c74f632d-abcb-4132-9029-58c8d04eb73a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH:|
|OS|Linux x64 4.19.0-12-cloud-amd64|
|CPUs|AMD EPYC 7571 (2 x 2199)|
|Memory (System)|0.94GB (0.15GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Seems most likely that this is an issue with your browser cache or webserver. We write edits back to the remote filesystem soon after you save the file. Try verifying with another editor or `cat` the file to check.

**Comment by challamzinniagroup** [comment]
@roblourens Thanks for the reply. I think you are most likely correct in that it was possibly some kind of browser caching issue or something similar.
Unfortunately, this was a small, quick project - and wrapped up shortly after I posted this. So I no longer have access to the specific environment or use-case to check or test anything.
The issue can be closed, and thanks again for the reply! On the whole I absolutely love the extension. Thanks for the great work!
