### ISSUE TITLE
Cant seem to Connect To Remote Running Container 

### ISSUE THREAD

**Issue by akash3456** [microsoft/vscode-remote-release#449]
i get this message when i attempt to attach vscode insider to a running windows container

![image](https://user-images.githubusercontent.com/5895095/58359371-0d41bd00-7e7b-11e9-8dc3-f68780c3b108.png)

**Comment by Chuxel** [comment]
@akash3456 Windows containers are not yet supported. It would be awesome if you'd upvote #445 if you are interested in them!  Closing as a duplicate.

**Comment by akash3456** [comment]
Ok thanks

**Comment by Chuxel** [comment]
Since this happens on with Linux containers, can you tell me the steps you used to create the container?  Also, have you shared your local drives via Docker settings?  If not, you can see an error.

**Comment by Chuxel** [comment]
Oh - and Alpine is not supported yet if you used an alpine container. See #54

**Comment by akash3456** [comment]
this is the message for linux containers:

![image](https://user-images.githubusercontent.com/5895095/58373101-5e57bc80-7f20-11e9-896c-6ad6015dcd75.png)

**Comment by chrmarti** [comment]
Does setting the home folder in the Dockerfile with `ENV HOME path` help? (See https://github.com/microsoft/vscode-remote-release/issues/22#issuecomment-488843424.)

**Comment by akash3456** [comment]
Why do i need to do this and the container in question was created using docker run against a solr image.

**Comment by akash3456** [comment]
so what i have tried is the following: 
![image](https://user-images.githubusercontent.com/5895095/58432991-faaeca00-80ac-11e9-8196-dd361020a6ec.png)

same error occured when connecting to it remotely.

**Comment by chrmarti** [comment]
/duplicate #22

From looking at the Dockerfile for solr, `ENV HOME /var/solr/data` should work. This is currently a limitation.

**Comment by akash3456** [comment]
looks setting the env home to solr data dir didnt work as same error occured

**Comment by chrmarti** [comment]
@akash3456 Make sure to rebuild the container. (Either remove the container manually or go through More Actions... on the error dialog and then choose to rebuild.)

**Comment by akash3456** [comment]
I did that got the same thing. Are you able to showcase to me from your setup that this does actually work as I’m not convinced tbh

**Comment by chrmarti** [comment]
```Dockerfile
FROM solr
ENV HOME /var/solr/data
```
Works for me. What's the error message you get with that?

**Comment by akash3456** [comment]
https://github.com/microsoft/vscode-remote-release/issues/449#issuecomment-495937564

Is the error message

**Comment by chrmarti** [comment]
I would expect that for the old container created without `ENV HOME ...`. Can you delete the current container manually and then retry? (E.g., use `docker ps -a` to list all containers and then `docker rm <container-id>` to delete the old one.)

**Comment by akash3456** [comment]
so i deleted the container changed the docker file to the following : 

FROM solr
ENV HOME /var/solr/data


i get the following message when remoting into it;
![image](https://user-images.githubusercontent.com/5895095/58697338-4ef9c880-8391-11e9-831d-f0caa3017c63.png)

**Comment by chrmarti** [comment]
Maybe you're on an older version of the solr image? `/var/solr` exists in my version and is owned by user `solr`.

**Comment by akash3456** [comment]
latest image is used

**Comment by akash3456** [comment]
it seems the var/solr/data does not exist in the running container. on the solr user

**Comment by akash3456** [comment]
can you show me how yours is working at all please? 
via vscode remote

**Comment by akash3456** [comment]
whats the default root user password when creating a linux container

**Comment by akash3456** [comment]
how to run commands as root in dockerfile

**Comment by akash3456** [comment]
its worked, remoed expose 8983
tanks
