### ISSUE TITLE
"Remote - SSH" output refers to "remote.SSH.sshPath"

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode-remote-release#4491]
- VSCode Version: 1.53.2 (also today's insider)
- Local OS Version: Windows 10
- Remote OS Version: OpenSUSE Leap 15.2
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect
2. Look at "Remote - SSH" output
3. See this:
```
[06:23:46.819] "remote.SSH.sshPath": undefined
```
Unless I am mistaken, `"remote.SSH.sshPath"` is now `"remote.SSH.path"`.

**Comment by bersbersbers** [comment]
Interestingly, it does show the correct value of `remote.SSH.path`
```
[06:40:59.360] "remote.SSH.sshPath": C:\Tools\OpenSSH\ssh.exe
```
and  this value seems to take effect, so this is purely an output issue.

**Comment by roblourens** [comment]
Typo, thanks
