### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by luongthenhan** [microsoft/vscode-remote-release#4493]
- Issue Type: `Bug`
- Extension Name: `remote-ssh`
- Extension Version: `0.64.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.53.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by bamurtaugh** [comment]
Hey @luongthenhan - could you please provide some more information about what issue you're facing and paste the info from your clipboard?
