### ISSUE TITLE
Cannot debug a React application running from a dev container

### ISSUE THREAD

**Issue by tomatac** [microsoft/vscode-remote-release#4494]
Issue Type: <b>Bug</b>

When I am trying to debug a react application from a Docker dev container I get the message: “Unable to attach to browser”.
It looks like by default the debugger is starting a debugging service on a random port. I get a message in the lower right hand side of the window: “Your service running on port 46241 is available” and I get an option to “Open in Browser”. If I click Open in Browser a new Chrome tab starts at http://localhost:46241/ but debugging session never starts. I just get a blank tab with a spinning icon in the tab title.

For this test I am using the default “Node.js” remote container generated with “Remote-Containers Add Development Container Configuration File …” -> Node.js
My launch.json configuration for debugger:
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}/app1"
        }
"npm start" works as expected (starts the application in the browser) 

How can I troubleshoot this issue?

Extension version: 0.158.0
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.8.0-43-generic snap
Remote OS version: Linux x64 5.8.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (8 x 3792)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.64GB (0.61GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 993eb652-3945-48f9-9f80-2a42c2c4c4e4|
|Screen Reader|no|
|VM|33%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js|
|OS|Linux x64 5.8.0-43-generic|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (8 x 3792)|
|Memory (System)|15.64GB (0.61GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by robtac** [comment]
I'm having the same issue. Debugging while not in the remote environment works perfectly, but debugging while in the container environment doesn't work. Tested with javascript in create-react-app default program.

**Comment by chrmarti** [comment]
Does the debug extension run remotely and would need to connect to the locally running Chrome? /cc @connor4312

**Comment by connor4312** [comment]
There's a known issue on Linux https://github.com/microsoft/vscode-js-debug/issues/908
