### ISSUE TITLE
Default value for remote.SSH.useLocalServer is shown as true

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode-remote-release#4496]
See the bottom of this snapshot:

![image](https://user-images.githubusercontent.com/12128514/108475335-dcc9c580-7290-11eb-8651-40042a12785f.png)

By contrast, my testing shows that the default value of `remote.SSH.useLocalServer` is `false`.

**Comment by bersbersbers** [comment]
I should add I am testing on Windows, and I have found this in https://github.com/microsoft/vscode-remote-release/issues/2475#issuecomment-773752303:

> This mode is already disabled on windows clients by default because of other issues

Really, some documentation of this feature (in particular, its assumptions and limitations) in a single location would be great ;)

**Comment by bamurtaugh** [comment]
Thanks for reporting @bersbersbers. I'm on Windows and just tried adding `remote.SSH.useLocalServer`, and it appears to default to true:

![image](https://user-images.githubusercontent.com/25310137/109236090-c4bbdf80-7783-11eb-845a-1ea8ce4d960a.png)

![image](https://user-images.githubusercontent.com/25310137/109236137-dbfacd00-7783-11eb-87ce-1b284f9c95ed.png)

What did you see in your testing?

I agree further documentation on this setting sounds like a good idea - would you expect to find that in the [Remote - SSH docs](https://code.visualstudio.com/docs/remote/ssh)? [Remote tips and tricks/troubleshooting](https://code.visualstudio.com/docs/remote/troubleshooting)? Somewhere else?

**Comment by bersbersbers** [comment]
> Thanks for reporting @bersbersbers. I'm on Windows and just tried adding `remote.SSH.useLocalServer`, and it appears to default to true:
> 
> ![image](https://user-images.githubusercontent.com/25310137/109236090-c4bbdf80-7783-11eb-845a-1ea8ce4d960a.png)
> 
> ![image](https://user-images.githubusercontent.com/25310137/109236137-dbfacd00-7783-11eb-87ce-1b284f9c95ed.png)
> 
> What did you see in your testing?

Functionally, I see that if you omit `remote.SSH.useLocalServer` from settings, it behaves the same way as if you set it to `false`. 

> I agree further documentation on this setting sounds like a good idea - would you expect to find that in the [Remote - SSH docs](https://code.visualstudio.com/docs/remote/ssh)? [Remote tips and tricks/troubleshooting](https://code.visualstudio.com/docs/remote/troubleshooting)? Somewhere else?

To be honest, I rarely read the VS Code documentation by picking a topic and reading all about it. This is at least partially due to me having been using VS Code for about 3 years now, so I have read some of these pages in earlier versions, and it's hard to keep track of changes. Anyway, I think I want to say I don't care much as long as I found useful information when I type 
> "remote.ssh.uselocalserver" site:code.visualstudio.com
into Google (or Bing).

**Comment by roblourens** [comment]
It defaults to false on windows - unfortunately our extension config model doesn't really support per-OS defaults, so you get this confusing contradiction. That was supposed to be temporary but it may last a little while longer. I will be revisiting this in March, probably adding multiple settings, as I work around https://github.com/microsoft/vscode-remote-release/issues/2475. I will make sure to add descriptions for the settings - thanks for pointing that out.
