### ISSUE TITLE
Cannot connect to Win Server 2019

### ISSUE THREAD

**Issue by Keltirion** [microsoft/vscode-remote-release#4498]
- VSCode Version: 1.53.2
- Local OS Version: 20H2 19042.804
- Remote OS Version: 1809 17763.1757
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to Win server

I'm and admin on the machine, tried also insiders version with nightly extension no luck there. Worked fine on win server 2016. Error I get in the output.
```

Server failed to start. - Program 'icacls.exe' failed to run: Win32 internal err
> or "Access is denied" 0x5 occurred while reading the console output buffer. Cont
> act Microsoft Customer Support Services.At line:4 char:1
> + icacls $ai_ /reset /Q
```

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/4524
