### ISSUE TITLE
Webpack watch mode (for hot module reload) doesn't work with remote Node.js container

### ISSUE THREAD

**Issue by ketanhdoshi** [microsoft/vscode-remote-release#4499]
- VSCode Version: 1.47.2
- Local OS Version: Windows 10 Pro, 20H2, OS Build 19042.685
- Remote OS Version: 4.19.128-microsoft-standard
- Remote Extension/Connection Type: Docker 

I'm using a very vanilla setup. The remote container is VSCode's tutorial container - https://github.com/microsoft/vscode-remote-try-node. The .devcontainer.json and Dockerfile are taken straight from that repo. Node.js version v14.15.4.

I am trying to follow webpack's Getting Started guide - https://webpack.js.org/guides/development/

The "watch mode" doesn't work at all, with "webpack --watch", webpack-dev-server or webpack-dev-middleware. That is the basis for HMR (hot module reload), without which development is extremely unproductive. So I really want to get this working.

Steps to Reproduce:

1. Open a remote container using VSCode's node.js tutorial
2. Create a simple webpack setup as per webpack's Getting Started guide.
3. Run webpack in watch mode using any of the three options mentioned above. It compiles the code once.
4. Now edit a Javascript file. webpack is supposed to detect that the file changed and recompile the code.
5. But nothing happens.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

I haven't tried this locally. I don't want to set up node.js locally.

**Comment by chrmarti** [comment]
This shouldn't be Dev Container specific, but must be a general issue with containers. E.g., see https://stackoverflow.com/questions/42445288/enabling-webpack-hot-reload-in-a-docker-application and probably others.

**Comment by ketanhdoshi** [comment]
Thanks for the pointer. I added the polling option to webpack and it is now able to pick up file changes. I haven't tried installing inotify-tools on the node.js Docker image to see whether webpack gets notified.
