### ISSUE TITLE
Support piping into VS Code from WSL

### ISSUE THREAD

**Issue by osyrisrblx** [microsoft/vscode-remote-release#450]
It seems like piping into code from WSL doesn't currently work. This would be an awesome feature to have!
```
ps aux | grep code | code -
```

**Comment by egamma** [comment]
@osyrisrblx since VS Code Remote WSL requires the insider version your command line also has to refer to the insider version:

>ps aux | grep code | code-insiders -

Did you try this?

**Comment by osyrisrblx** [comment]
Oh, I forgot to mention that I have code aliased to code-insiders. For me, this just opens an empty file called "-".

**Comment by osyrisrblx** [comment]
Running that command does as I described:
![image](https://user-images.githubusercontent.com/9200592/58450760-1c1bb000-80c5-11e9-98be-c24f168132d8.png)
