### ISSUE TITLE
Test: Prioritize 'core' definitions when adding container configs

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#4501]
Refs: #4447

- [x] any @chrmarti 

Complexity: 2

Authors: @egamma

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%234501%0A%0A)

---

Verify `Remote-Containers: Add Development Container Configuration Files...` only offers 'core' definitions on the first page and all definitions only when picking 'show all'. 

- For a workspace with no popular filetype (e.g. a workspace with only a single Readme.md), all Core configurations are recommended
- For a populated workspace only the Core configurations which have a score are recommended.

A 'core' definition is a definition that has the Category core in its meta data in the Readme of the configuration.

This is the an example Readme https://github.com/microsoft/vscode-dev-containers/blob/master/containers/javascript-node/README.md#summary

This is an example category definition 
![image](https://user-images.githubusercontent.com/172399/108963271-2e4fc700-767a-11eb-908e-c2d2e6a426f1.png)

The dev container configurations can be found here https://github.com/microsoft/vscode-dev-containers/tree/master/containers

**Notice** the category of the Docker configurations have recently been re-categorized and still show up in the list, pls ignore them

![image](https://user-images.githubusercontent.com/172399/108968674-5b53a800-7681-11eb-88ea-16bf1c3c7a50.png)

**Comment by sandy081** [comment]
I am hitting #4525 and I would wait until it is fixed before continuing testing

**Comment by egamma** [comment]
@sandy081 the empty workspace is a special case this should not block you from testing that the recommendations work for a populated workspace.

**Comment by egamma** [comment]
I have a fix, but the extension build shows some warnings and I'm not comfortable publishing an extension with warnings. I therefore want to wait until christof is back and we will make the fix available then and test again.

Removing the test plan assignments and labels.
