### ISSUE TITLE
Unable to ssh to any remote machine, putty ssh works (Could not establish connection)

### ISSUE THREAD

**Issue by tdvginz** [microsoft/vscode-remote-release#4505]
- VSCode Version: 1:53:2
- Local OS Version: Windows 10 Enterprise 20H2
- Remote OS Version: ubuntu 18.04
- Remote Extension/Connection Type: SSH

It started only today, and it doesn't work with vs insiders as well.

Tried 
"remote.SSH.useLocalServer": true
and
"remote.SSH.useLocalServer": false
Both doesn't work.

Any solutions to similar issues (#4491 , #4496) didn't help either.

![image](https://user-images.githubusercontent.com/64267097/108597543-37971600-7392-11eb-95e0-d5935f316a48.png)

**Comment by bersbersbers** [comment]
Take a look at the "Remote - SSH" output window.

**Comment by tdvginz** [comment]
I'm closing the issue as it was 100% my fault, I inserted a typo in the config file in `~/.ssh` on the same day I updated the ssh client and vscode, so I mistakenly thought it has something to do with the other posts here.

Thanks.
