### ISSUE TITLE
Remote search ripgrep fails due to missing workspaces

### ISSUE THREAD

**Issue by abeck70** [microsoft/vscode-remote-release#451]
See Fix #42219 - don't invoke ripgrep on workspace folders that don't exist

- VSCode Version:Version 1.35.0-insider (1.35.0-insider
- Local OS Version:macOS
- Remote OS Version:Centos7
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Used a workspace definition from my git that had missing folders.
2. Search returns a ripgrep error message

Fix #42219 - don't invoke ripgrep on workspace folders that don't exist

Once I deleted the workspace folders that are not present on the remote machine, search worked again.

Does the above fix need to be ported across?

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
I think this has been fixed, can't repro
