### ISSUE TITLE
Terminal completion text becomes broken with multiline filenames

### ISSUE THREAD

**Issue by hofingermarkus** [microsoft/vscode-remote-release#4510]
# System:
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.21313
Remote OS: Ubuntu x64 18.04 

# Steps to Reproduce:
Code completion in the terminal broke for multiline strings.
If one has very large filenames / foldernames, the completion seems to overwrite the displayed text on windows.
However, it seems to be a display only error. 
One can still navigate and change commands with the keyboard e.g. from `ls long_filename` to `cd long_filename` by pressing `pos1` and then changing the text, even though it is not displayed corretctly.

This error must have been introduced around the time the forward prediction for remote servers was added to the terminal.
I have only ever experienced this effect when working remote from windows and being connected to a linux machine.
So I hope this is the right place for this bug report.

# Example GIF
Here is an example, where I copy & paste filenames with the mouse by doulbe & right clicking.
As can be seen parts of the text are overwritten and displayed incorrectly.
However the commands are still executed corretly.
![VSCODE_Multiline_Breaking](https://user-images.githubusercontent.com/12088794/108708885-4dcbe000-7512-11eb-845e-baf757ad49f1.png)

**Comment by bamurtaugh** [comment]
cc @Tyriar @connor4312 In case you have any insights regarding the role of type ahead in this issue.
