### ISSUE TITLE
Test portsAttributes in devcontainer.json

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#4514]
Refs: https://github.com/microsoft/vscode-remote-release/issues/4445

- [x] macOS @gregvanl
- [x] linux @isidorn
- [x] windows @sbatten

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%234514%0A%0A)

---

1. Open your favorite containers sample in a container. You can use the "Remote-Containers: Try a sample..." command for example.
2. Open the devcontainer.json and add a `portsAttributes` property.
3. Verify that you get suggestions if you want them.
4. Rebuild the container.
5. Verify that your `portsAttributes` are applied to your forwarded ports and any new ports you forward.

**Comment by isidorn** [comment]
Works well. Could have been a bit larger complexity because the docker setup on LInux takes some times.
What does not work: changing a `portsAttributes` in devcontainer.json requires a container rebuild. Though I guess that is expected so I did not file an issue.

**Comment by alexr00** [comment]
@isidorn my apologies on the complexity. I assumed that everyone had docker setup already 🤦‍♀️

**Comment by isidorn** [comment]
I do have it, but on the macOS :)

**Comment by gregvanl** [comment]
@alexr00 Should the instructions be for step 4 but "Rebuild the container" rather than "Reload"? It seems like changes I make to `portsAttributes` don't take effect unless I rebuild the container.

**Comment by alexr00** [comment]
Yes, my bad. It should be rebuild. Thank you for catching!  Instructions updated.
