### ISSUE TITLE
Test "Preview in Editor"

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#4515]
Refs: https://github.com/microsoft/vscode-remote-release/issues/4436

- [x] ssh @kieferrm
- [x] dev container  @lszomoru

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%234515%0A%0A)

---

1. Connect to your remote. 
2. Start an application on your remote that listens on a port and can be opened in a browser. The microsoft/vscode-remote-try-node is a good repo to use for testing.
3. Verify that you get a notification about the port that your application listens on being auto-forwarded.
4. Use the button in the notification to "Preview in Editor".
5. Verify that the simple browser opens to the side with your application.
6. Open the "Ports" view.
7. Use the action in the "Ports" view to "Preview in Editor".
8. Verify that the simple browser opens to the side with your application. If it's already open, you'll need to close it first to see it re-open.

**Comment by kieferrm** [comment]
I changed the assignments between @lszomoru and myself. Don't have docker on my M1 yet.

**Comment by lszomoru** [comment]
The flow works as advertised in a dev container 👏🏻
