### ISSUE TITLE
matplotlib plot not showing up when running python installed on WSL

### ISSUE THREAD

**Issue by fnery** [microsoft/vscode-remote-release#452]
- VSCode Version: 1.35.0-insider
- Local OS Version: Windows_NT x64 10.0.17763
- Remote OS Version: Ubuntu 18.04.2 LTS
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

```
import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 20, 100)  # Create a list of evenly-spaced numbers over the range
plt.plot(x, np.sin(x))       # Plot the sine of each x point
plt.show()                   # Display the plot
```

Running this on a python 3.7.3 conda environment installed on WSL. All runs without errors but the plot is not shown anywhere.

**Comment by kangkang59812** [comment]
solve it ? I have showed a pic successfully when first using it. But now this situation happend to me.

**Comment by egamma** [comment]
Moving to vscode-python for initial investigation.

**Comment by qubitron** [comment]
@fnery to clarify are you running the code in the terminal and expecting the image to appear in a separate window? If so, this won't work due to a fundamental limitation of the WSL not having ability to show UI. 

Instead you can run the code in the Python Interactive window in order to see the output. Can you try Right-click on the file and select ```Run Current File in Python Python Interactive window```?

Thanks!
Dan

**Comment by fnery** [comment]
Thanks @egamma and @qubitron!

@qubitron yes I had tried `Run Current File in Python Python Interactive window` and indeed the plot is shown. FYI the reasons why I was interested in the "separate window" behaviour are:

- more interactive (pan/zoom figure, etc)
- no need to start a python interactive window
- in my workflow it helps me having multiple figures in separate windows to make it simpler for quick visual comparisons (I guess I could adapt my workflow but just throwing it out there)

Also, before these new remote development features (amazing work by the way) I used VS code installed on WSL and used an X-server to show GUIs. In this scenario, the plot would appear in a separate window as shown in the following figure:

![unnamed](https://user-images.githubusercontent.com/3774685/58435377-300ce500-80b8-11e9-9d8d-46f0af3d0334.png)

Any idea if sorting out the UI issue would be in your future plans? Just wondering as it is not uncommon for me to launch GUIs (from linux libraries) programmatically.

Many thanks again,
Fabio

**Comment by qubitron** [comment]
It's not something I'm aware of on our current plans, we would have to discuss further on how this could be accomplished.

//CC @Chuxel @davorabbit @brcan @luabud

**Comment by egamma** [comment]
> If so, this won't work due to a fundamental limitation of the WSL not having ability to show UI.

This is correct, feature requests for WSL are better discussed in the WSL repository.

**Comment by qubitron** [comment]
@fnery in the June release we added a plot viewer with pan/zoom so that should help address your needs: https://devblogs.microsoft.com/python/python-in-visual-studio-code-june-2019-release/
