### ISSUE TITLE
Cannot SSH to Windows Host (Powershell error)

### ISSUE THREAD

**Issue by tecandrew** [microsoft/vscode-remote-release#4521]
- VSCode Version: 1.53.2
- Local OS Version: Darwin x64 20.3.0
- Remote OS Version: Windows_NT x64 10.0.19042
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. SSH to a Windows host (have tried with macOS client and another Windows OS client)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

# Overview

I can SSH into the system just fine with a regular terminal, but can not using VS Code extension. With some tinkering around it seems like the SSH extension spins up the server using an illegal statement separator `&&`. This command works with Powershell 7 (PSCore/pwsh), but the default installed Powershell within` \System32\PowerShell` does not.

I'm also using a different SSH version (OpenSSH-Win64) from the one installed via the "Extra Features" option within Windows 10.

# Extension Settings
```
    "remote.SSH.enableAgentForwarding": false,
    "remote.SSH.useFlock": false,
    "remote.SSH.remoteServerListenOnSocket": true,
    "remote.SSH.enableDynamicForwarding": false,
    "remote.SSH.useLocalServer": false,
    "remote.SSH.showLoginTerminal": true,
    "remote.SSH.logLevel": "trace",
    "remote.SSH.localServerDownload": "auto",
    "terminal.integrated.shell.windows": "pwsh",
```

# Error and Log

- Could not fetch remote environment
- Failed to connecto to the remote extension host server (Error: Time limit reached)

```
lafcadio@tec-pc.local's password: 
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Andrew Tec> echo -e 'Connected to SSH Host - Please do not close this terminal' && while true; do sleep 180; echo -n ' '; done
At line:1 char:69
+ ... Connected to SSH Host - Please do not close this terminal' && while t ...
+                                                                ~~
The token '&&' is not a valid statement separator in this version.
At line:1 char:86
+ ... H Host - Please do not close this terminal' && while true; do sleep 1 ...
+                                                                  ~
Missing statement body in do loop.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine
```

EDIT:

I managed to kludge a workaround using CMD's `mklink` to create a sort of symbolic link that points `powershell.exe` to `pwsh.exe`. Still doesn't work for some reason, so I'm not sure what's going on...

```
lafcadio@tec-pc.local's password: 
PowerShell 7.1.2
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\Andrew Tec> echo SSH_AUTH_SOCK=$SSH_AUTH_SOCK && echo -e 'Connected to SSH Host - Please do not close this terminal' && while true; do sleep 180; echo -n ' '; done
ParserError: 
Line |
   1 |  . H Host - Please do not close this terminal' && while true; do sleep 1 .
     |                                                                 ~
     | Missing statement body in do loop.
```

**Comment by bamurtaugh** [comment]
Thanks for reporting @tecandrew. Does this sound like https://github.com/microsoft/vscode-remote-release/issues/2475?

**Comment by roblourens** [comment]
Please share the full log from the Remote-SSH output channel. And are you sure that you don't have `remote.SSH.remotePlatform` set in your settings? We are sending the bash script, not the powershell script, seems that we assume we are talking to a linux machine, which is driven by that setting..

**Comment by tecandrew** [comment]
The `remote.SSH.remotePlatform` parameter is set `"windows"`. Not sure why it's sending over a bash script? Just attempted to fresh connection to a Windows 10 host from a Windows 10 client. Resulting VS code pop-up error came out with:

```
Unable to write to Folder Settings because no resource is provided
Could not fetch remove environment
Failed to connecto to the remove extension host server (Error: webSocket close with status code 1006)
```

I've attached the relevant logs to this comment

[output-remote-ssh.txt](https://github.com/microsoft/vscode-remote-release/files/6087649/output-remote-ssh.txt)
[terminal-output.txt](https://github.com/microsoft/vscode-remote-release/files/6087647/terminal-output.txt)


@bamurtaugh that issue seems familiar; we share the same OpenSSH version, but the resulting error seems different.

**Comment by roblourens** [comment]
Do you have `"remote.SSH.enableDynamicForwarding": false`?

**Comment by tecandrew** [comment]
Yes. The previous attempts had `"remote.SSH.enableDynamicForwarding": false`. Just attempted with it as `true`, but seems like it just hangs.

[vscode-ssh-dynamicforwarding-true.txt](https://github.com/microsoft/vscode-remote-release/files/6110428/vscode-ssh-dynamicforwarding-true.txt)

**Comment by roblourens** [comment]
Ok, that's a setting that enables some code that should be called deprecated. Now everything looks as it should. What exactly do you see? Any useful output in the devtools console (Help > Toggle Developer Tools)

**Comment by roblourens** [comment]
It looks like you have dynamic forwarding disabled again? This mode was never implemented for windows hosts so it's not unexpected.
