### ISSUE TITLE
What it the exact setting to disable overwriting git credential.helper config?

### ISSUE THREAD

**Issue by wxdao** [microsoft/vscode-remote-release#4527]
The issue #2441 was closed without any explanation on what had been done on the specific user setting added to address the problem.

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/1405249/108821070-0e77bf00-75f8-11eb-94a5-a4cb291990c4.png">

**Comment by bamurtaugh** [comment]
Thanks for opening @wxdao. I believe the setting you're looking for is `remote.containers.gitCredentialHelperConfigLocation`. 

Please let me know if that helps.

**Comment by wxdao** [comment]
> Thanks for opening @wxdao. I believe the setting you're looking for is `remote.containers.gitCredentialHelperConfigLocation`.
> 
> Please let me know if that helps.

Thanks. It works.
