### ISSUE TITLE
"open any folder" binds container image to subfolder folder 1:1

### ISSUE THREAD

**Issue by dboreham** [microsoft/vscode-remote-release#4528]
- VSCode Version: 1.54.0
- Local OS Version: 10.0.21318
- Remote OS Version: Ubuntu 18.04/Docker Desktop 20.10.2
- Remote Extension/Connection Type: Docker/WSL

Steps to Reproduce:

1. Create a multi-folder, multi-devcontainer project along the lines suggested in: https://github.com/microsoft/vscode-remote-release/issues/254#issuecomment-491124819
2. Observe that it is impossible to have more than one devcontainer associated with any specific folder.
3. Observe that having opened `container1-src` in a VSCode window, it will now be impossible to see any files from the explorer that are outside this folder.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Background:

While "open any folder in a devcontainer", in a separate VSCode window sounds great, in practice this 1:1 association between a folder and a devcontainer is inconvenient for many projects. For example I have a project (all in one big git repo) that comprises a pile of scala, a pile of react/js, and a pile of Ruby. There _are_ distinct subfolders associated with the scala and the react, but the ruby is used for dev tooling that needs to access potentially any file in the project. Furthermore when working on, say, scala, you often want to refer to , say, doc files that are not in the scala subdirectory. Those files are invisible in your "scala" VSCode window. 

It seems that this issue has already been recognized in the context of vcs support -- each devcontainer may mount the "git root", also project repo root directory, so the devcontainer can see the entire tree, but VSCode's UI can't.

Proposed solution: decouple devcontainer specification from folder. Allow "open folder with devcontainer foo".

**Comment by dboreham** [comment]
In the meantime I discovered a workaround, of sorts, for this:

1. Define a set of containers, one for each type of development to be encountered in the repo (java, c++, etc), reference them via a devcontainer.json and associated docker-file.yml in the project root. Define one of them to be the one used for "open folder in container" (e.g Java).
2. Once started (which will happen automatically when the root folder is opened in container), you can pick any of the "other" containers in remote explorer, right click for "attach new window". This opens a new VSCode window associated with that container (e.g. C++). Now, in that new window you will see that it has no folder open, but you can proceed to open any folder including the project root.

This achieves (I think) the desired outcome : multiple different devcontainers all capable of being used in conjunction with the same project directory.

**Comment by PavelSosin-320** [comment]
Do you mean "Additional toolchains" or "Project with multiple targets / natures / runtimes"? In the Visual Studio and Eclipse such projects require deep anesthesia. After compiler or runtime upgrade the project has to be exported and imported back, then target version reconfigured, warnings corrected, ...

**Comment by dboreham** [comment]
All I want is : the existing feature where you can define a devcontainer (immutable toolchain) to be used with each of several subdirs in a project, to be extended such that you can opt to open the same folder with two or more different containers.

If your project is organized such that , say, all the C++ is under one subdir, and all the Golang is under another subdir, then everything is great. But not all projects are organized that way.  Often for example there's some tool that needs to be run as a pre-processor over the entire top level directory.

**Comment by PavelSosin-320** [comment]
@dboreham Great! It is the 1st use-case: extension via dockerized toolsets. Ironically, this requirement has been raised by Erich Gamma, discussed, agreed, and has been implemented by the other IDE of the same brand "Cloud-based IDE as a service" as dev-container VSCode extension some years ago. But it is missed in the VSCode itself. The solution is very simple:
Organize dev-environment as a "Workspace" container providing workspace volume or bind mount, git, tty, shell, ..., add SDK's as pre-built (*)  separate side-car containers sharing the same volume / mount at the same container's path, pack everything into single docker-compose or Podman's pod file,  up everything together, and open Workspace container terminal. SDK's don't need any entry-point or terminal - they can be used in the "command mode" with relative parameter paths.
 The "official" SDK images are already published in the DockerHub, like Nodejs+npm, Java+Maven, .Net SDK.
You can try it by yourself without waiting for the new Devcontainer extension version.
(*) to avoid too long several Docker images. build.

**Comment by dboreham** [comment]
I believe that's exactly what I'm doing. Problem is possibly with the existing doc (see cited reference at the top) which suggests a workflow where the user opens a folder that has an associated "sdk" container. I don't believe this works, because things become confused between the container names such that you end up with two copies sometimes. I have found that an alternative approach where the user instead opens a new window for each sdk container, then separately in that window opens the relevant folder, does seem to work (in that you don't get colliding containers created). However then it seems you lose the ability to read the .devcontainer.json file per-folder. I have a hunch that the original example posted (see above) doesn't work. I'll see if I can find some time to prove that, or create a new example project to illustrate and reproduce. Unfortunately I found all this by attempting to integrate a real product with VSCode devcontainers, so I can't publish what I am running at present.

**Comment by PavelSosin-320** [comment]
Sure, I upvote it. I already tried to build  Podman's pod combinations consisting of VSCode base dev-container and Nodejs image or Python image. The workspace is easily available via base-container's terminal. Nodejs tools are available via Podman exec on the same shared workspace.
