### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by ErikGrimes** [microsoft/vscode-remote-release#453]
- VSCode Version:
1.35.0-insider
- Local OS Version:
Windows 10 Pro  Build 17763
- Remote OS Version:
Debian GNU/Linux 9 (stretch)
- Remote Extension/Connection Type: SSH/Docker/WSL
Docker
Steps to Reproduce:

1. git clone https://github.com/Polymer/lit-element.git
2. Open in remote container "Node latest"
3. npm install

The install runs slowly, eventually failing with the error below.

```
npm ERR! path /workspaces/lit-element/node_modules/accessibility-developer-tools
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/workspaces/lit-element/node_modules/accessibility-developer-tools' -> '/workspaces/lit-element/node_modules/.accessibility-developer-tools.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-25T13_10_57_876Z-debug.log
```

npm install for the same package succeeds if you do if from a directory within the container that is not volume mounted from the host.

Other projects fail during npm install with different error messages after taking several minutes or simply hang.

Does this issue occur when you try this locally?: No

**Comment by chrmarti** [comment]
I wonder if this is related to Window's filenames being case-insensitive.

**Comment by chrmarti** [comment]
Cloning the project in WSL or in a Docker volume should work around the slow performance. Can you check if it also fixes the error?
