### ISSUE TITLE
Delete port: Was expecting this at the end of the row

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#4533]
Testing #4515.

Rather than seeing this in the port column I was expecting that I'd see the `x` at the end of the row as it applies to the whole row. The actions to copy the address etc. make sense where they are although it's uncommon for our UI.

![image](https://user-images.githubusercontent.com/4674940/108895658-bd040b80-75c8-11eb-8344-860c0641f924.png)

**Comment by alexr00** [comment]
@misolori I'd love to get your input here! Should I move the "x" to its own column at the end of the row?

**Comment by misolori** [comment]
Yea, if we have other actions that apply to the entire port then those should all be grouped together. Wondering if the ones from `Local Address` should also be moved to the end? They look a little odd in the middle of the row. Have only copy would make sense but when there are multiple there it stands out.

Dropbox does it this way:
![image](https://user-images.githubusercontent.com/35271042/109033837-e5007700-767b-11eb-8a10-fcbcd1707251.png)

While OneDrive has an ellipsis with all actions next to the title:
![image](https://user-images.githubusercontent.com/35271042/109034020-0c574400-767c-11eb-917a-c217026c52ba.png)

So maybe something like this:

![image](https://user-images.githubusercontent.com/35271042/109035013-13cb1d00-767d-11eb-8b6a-9a0d7645045f.png)

**Comment by alexr00** [comment]
My main issue having them at the end is that we then only have 3 actions. And I agree that we should have max of 3 actions together. However, there are more than 3 actions that we want to show 😅 : close, copy, open browser, open preview. If the requirement is that we absolutely, 100%, _must_ show more than three actions, would you still have them at the end?

**Comment by misolori** [comment]
Agreed, I'd pick the two most important ones and then add the rest into an ellipsis? You could surface the reset of the right-click menu options there as well:

![image](https://user-images.githubusercontent.com/35271042/109043068-c99a6980-7685-11eb-97b9-eb39f8bdee32.png)

**Comment by alexr00** [comment]
We have more than two that must show as inline actions. Given that, I will leave the action in individual cells for now.
