### ISSUE TITLE
Delete Port: Was expecting Delete key to delete port forwarding 

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#4534]
Testing #4515

With this focus selecting I was expecting <kbd>DEL</kbd> to be the same as pressing the `x`:

![image](https://user-images.githubusercontent.com/4674940/108895881-005e7a00-75c9-11eb-8e4f-034ff06a9c4d.png)

**Comment by alexr00** [comment]
The primary keybinding for close port on Mac was cmd+backspace. I have added a secondary keybinding for delete.
