### ISSUE TITLE
Cannot give keyboard input for post commands

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-remote-release#4539]
Testing #4502

Version : 1.54.0-insider (user setup)
Commit : 9ecd3fc3022e8c154aff868f74bd5d77f7d4a2ea
Date : 2021-02-23T10:46:22.816Z
Electron : 11.3.0
Chrome : 87.0.4280.141
Node.js : 12.18.3
V8 : 8.7.220.31-electron.0
OS : Windows_NT x64 10.0.19042

I have the following commands:
```json
"postCreateCommand": ["echo", "POST CREATE"],
"postStartCommand": ["echo", "POST START"],
"postAttachCommand": ["echo", "POST ATTACH"],
```

When I have the container open, and rebuild it, I do get the post commands running in a separate terminal, but I'm unable to give keyboard input, other than when it accepts a key to close the terminal at the very end:
![post-attach](https://user-images.githubusercontent.com/7199958/108925279-226bf280-75f1-11eb-8033-facb846fdc1b.PNG)

Same issue when I use the following commands:
```json
"postCreateCommand": "echo CREATE",
"postStartCommand": "echo START",
"postAttachCommand": "echo ATTACH",
```

This is using the VS Code devcontainer.json with just the post command fields switched.

**Comment by chrmarti** [comment]
The echo command doesn't accept input. Could you retry with a command that does? Or just a long running command that you can interrupt with Ctrl+C.

**Comment by rzhao271** [comment]
Yep, that works. Was able to cancel a long-running task with Ctrl+C, and also get in input with the `read` command.
