### ISSUE TITLE
Start in WSL if WSL was used when exiting VS Code

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode-remote-release#454]
If I am using remote WSL and close VS Code and then start it again, it starts in local environment. It would be nice if it remembered to start in WSL when starting it again. Someone using WSL most likely intend to continue working in WSL upon start of VS Code.

This is how remote ssh works, where if I start VS Code again it connects to the ssh host I was connected to when closing VS Code.

**edit**: I just noticed that it _does_ indeed start in WSL, but only if you have some file open from WSL. If you just connect to WSL, do not open or have any files open, close VS Code, start VS Code again - that is when you end up in local and not WSL. If that is desired behavior this could be closed.

**Comment by egamma** [comment]
@thernstig this is the intended behaviour. 
// fyi @aeschli
