### ISSUE TITLE
Remote groups in integrated terminal

### ISSUE THREAD

**Issue by GuillaumeQuenneville** [microsoft/vscode-remote-release#4540]
Issue Type: <b>Bug</b>

I created a group in a remote session. If I ssh normally the group is added. If I start an integrated terminal the group does not exist. If i do "sudo su thisuser" the group then appears. Restarting vs code and full reboot client does not fix the issue. Haven't tried restarting server.

edit: shell is zsh.  Trying to add user to group in the nonexistent group state says that user is already a member of the group.

 Extension version: 0.64.0
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.3.0
Remote OS version: Linux x64 5.8.0-36-generic

<img width="1254" alt="Screen Shot 2021-02-23 at 8 25 48 PM" src="https://user-images.githubusercontent.com/32133082/108931292-67098500-7615-11eb-92d8-4ecc28484397.png">

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (3.75GB free)|
|Process Argv|--crash-reporter-id 9859473f-495d-4ac0-b1d6-7238681cb3c8|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: laplace|
|OS|Linux x64 5.8.0-36-generic|
|CPUs|AMD Ryzen Threadripper 3990X 64-Core Processor (128 x 2194)|
|Memory (System)|251.64GB (149.18GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30263000

```

</details>

**Comment by GuillaumeQuenneville** [comment]
The error fixed itself with time. I find it odd that the state of the SSH session survived a reboot? Maybe explicitely closing an ssh session should clean up the ssh stuff on the client side if this is what happened?

The higher level problem this error caused is that the anaconda group was required for the python extension so the automatic detection wasn't working.

**Comment by bamurtaugh** [comment]
Thanks for reporting @GuillaumeQuenneville, and glad to hear the error isn't persisting. 

> I find it odd that the state of the SSH session survived a reboot?

Does it sound like the terminal reconnection work is what was unexpected here? https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_51.md#terminal-reconnection

**Comment by GuillaumeQuenneville** [comment]
Yes! I should read the change-logs..

If I recall correctly, I also tried closing the integrated terminal with the garbage can icon. Maybe an explicitly killed terminal should not be persisted? It was the first thing I tried and it should cover all the cases where the persistence behaviour isn't wanted.

Feel free to close if you feel it's appropriate since this was intended behaviour.

Thank you

**Comment by GuillaumeQuenneville** [comment]
Hi again,

I did more testing, it persists the garbage icon.

I also read through all the terminal commands in the command palette. It also persists the "kill the active terminal session" action which implies that it should be killed.

Maybe change the kill active session behaviour or add a new command.

Steps to reproduce.
- create new group
- add user to group
- there's no way (from what I can tell) to kill terminal session so that group permissions get updated?

This affects the autodiscovery of a few different plugins amongst other things if the group is what gives you permissions to a directory with the plugins executable (anaconda python) for example.

**Comment by bamurtaugh** [comment]
Thanks for the additional info @GuillaumeQuenneville!

cc @meganrogge @Tyriar @roblourens For feedback/question on behavior for what seems to be terminal reconnection.

**Comment by bamurtaugh** [comment]
Didn't intend for this issue to closed based on my last comment alone, but I think the bot thought I was tagging it. Reopening to allow discussion, but we can certainly close again if it was intended.

**Comment by GuillaumeQuenneville** [comment]
No problem! I know what the problem is now so it's not a problem for me :)

I found this other issue with the same problem
https://github.com/microsoft/vscode-remote-release/issues/658
Their solution was to kill the vs code server process. Maybe there's a more graceful approach.

**Comment by Tyriar** [comment]
> there's no way (from what I can tell) to kill terminal session so that group memberships get refreshed?

So reconnection does mean the same terminal will persist across reloads, as for killing, the bin icon will destroy it.

There are 2 things that may be influencing this:

- The environment that the window uses is based on the server, which I believe will only shut down when all windows go down (or 3 hours later, I'm not 100% sure). You can run this to kill the server to make sure it's fresh when you open a new window:
  ![image](https://user-images.githubusercontent.com/2193314/109827594-b725b000-7bf0-11eb-99f8-f5c7a0e0dd27.png)
- The terminal is not like a regular ssh connection, rather it uses an ssh connection and launches a local terminal over there, using the existing ssh connection for transport.

Regardless, I'd say this is working as intended.
