### ISSUE TITLE
Ports view Local Address actions hover slow to appear on macOS

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-remote-release#4541]
Testing #4514

With a port autoforwarded, go to the Ports view and hover over the actions in the Local Address column.

For some reason, the hovers tooltips are very slow to appear on macOS (~ 1 second)

The tooltips appear as expected on Windows without a noticeable lag.

**Comment by alexr00** [comment]
@gregvanl Those are just the default tooltips. I've tested this before, and on Windows and Linux, the default seems to be about 500ms. On Mac, the default is about 1500ms.
