### ISSUE TITLE
portsAttributes label values are sticky after updating

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-remote-release#4542]
Testing #4514

Repros on macOS and Windows 10.

1. Fill in a portAttributes setting with a label "blah".
2. Build the container and test the port forwarding.
3. Update the portAttributes setting to label "Blah Port".
4. Rebuild the container and test the port forwarding.

The preview label value is displayed.

![image](https://user-images.githubusercontent.com/12818376/108930944-a3c88280-75fb-11eb-8dc1-c163d4c38ed1.png)

Other attributes do update correctly after rebuilding the containers (for example `onAutoForward` changes to take effect)

**Comment by gregvanl** [comment]
I think the repro is that I used the Forward a Port button and set the port to 3000 and that action pulled in the label. That entry is then sticky.

**Comment by sana-ajani** [comment]
I can repro in Windows 10

**Comment by sbatten** [comment]
Yea, another repro is to change the port and the label persists even though the port isn't in the portAttributes anymore. I suppose this could be expected behavior.

**Comment by alexr00** [comment]
@sbatten the behavior you're seeing is intended, because port properties are saved/restored 

Looks like I am giving preference to the save/restored value, rather than the setting.
