### ISSUE TITLE
ssh password login with special characters 

### ISSUE THREAD

**Issue by brunoyuv** [microsoft/vscode-remote-release#4543]
- VSCode Version: both insider version and latest
- Local OS Version: macOS Big Sur and Catalina 
- Remote OS Version: Ubuntu 21 and CentOS 6
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.click the green ssh connect button/ status bar item. 
2. select Remote SSH: Connect to host
3. type in a host with special characters (for example mine have []{$)#-)
4. it will tell you that your password is wrong even if you are right.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by bamurtaugh** [comment]
Thanks for reporting @brunoyuv. I believe this is being tracked in https://github.com/microsoft/vscode-remote-release/issues/4138, so going to close this issue. But if your issue is different, please let me know, and happy to discuss further.
