### ISSUE TITLE
Ports view: expect to be able to tab or move into the local address column

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-remote-release#4544]
Testing #4516

I was initially stymied as to how to set the local address in the Ports view. I expected to be able to navigate to that column via mouse or keyboard and edit the Local Address value. 

It took me several minutes to figure out that it was changeable via a context menu.

Using the hand cursor on hover is also confusing. The hand cursor usually means an item is clickable but click or double-click do nothing on a Ports view table row.

**Comment by alexr00** [comment]
The hand cursor matches what we currently do in lists, so I think this is correct. @joaomoreno in case its not.

Tabbing to edit the local address is covered by https://github.com/microsoft/vscode/issues/117399
