### ISSUE TITLE
Old session (open editors etc) is lost when connection after a vscode reload fails

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/vscode-remote-release#4548]
Issue Type: <b>Bug</b>

When reconnecting to the remote fails (e.g. due to an ssh timeout) I can retry, but after it succeeds, my previous session is lost - any editors I had open before are gone.

This is extremely annoying because you may have kept specific editors open to remind you what you were working on, and while restarting for an update or any other reason is not very disruptive (otherwise I wouldn't do it), losing the open editors IS annoying.

Extension version: 0.64.0
VS Code version: Code - Insiders 1.54.0-insider (4e1234963a10831b2cf76ff08c4c657e3b7a2866, 2021-02-24T05:16:17.421Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-gentoo

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.43GB free)|
|Process Argv|--crash-reporter-id c6195c38-5aa8-4897-b60d-c88b99231d15|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: eluvian|
|OS|Linux x64 5.4.72-gentoo|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor (12 x 3839)|
|Memory (System)|31.35GB (5.02GB free)|
|VM|0%|
</details>

**Comment by bamurtaugh** [comment]
Thanks for reporting @ThiefMaster.

We have related issues tracking disconnects and the behavior to handle them: https://github.com/microsoft/vscode-remote-release/issues/1087, https://github.com/microsoft/vscode-remote-release/issues/1257, https://github.com/microsoft/vscode-remote-release/issues/3096. To help with tracking, do you think your issue relates to any of those as well? Although it seems like the preservation of editors would technically be a new request.

Also related - we now have terminal reconnection: https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_51.md#terminal-reconnection.

**Comment by roblourens** [comment]
This is https://github.com/microsoft/vscode/issues/110062
