### ISSUE TITLE
Remote - SSH can not installed on vscode 1.34

### ISSUE THREAD

**Issue by longv2go** [microsoft/vscode-remote-release#455]
- VSCode Version: 1.34
- Local OS Version: macos 10.14.3 (18D109)

when install Remote -SSH, it shows the error message " 无法安装。找不到与 VS Code 当前版本 (1.34.0) 兼容的扩展“ms-vscode-remote.remote-ssh”。

**Comment by egamma** [comment]
This is intended, the VS Code Remote preview requires VS Code insiders, pls see the documentation.
