### ISSUE TITLE
Should hardcoding new port attribute in devcontainer.json update ports view?

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-remote-release#4555]
Testing #4433

I tried adding a new label for port 6080 directly into devcontainer.json as follows:
```json
	"portsAttributes": {
		"5901": {
			"label": "vncviewer"
		},
		"6080": {
			"label": "test2"
		}
	}
```

but the ports view still has the original name of the port.
![port-name-unchanged](https://user-images.githubusercontent.com/7199958/109047987-5eec2c80-768b-11eb-9136-ed494a6ade0c.PNG)

**Comment by alexr00** [comment]
This is intended. Updating devcontainer.json often/usually requires a rebuild or reload, so the behavior is consistent.
