### ISSUE TITLE
Preview in editor action from ports view not working

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-remote-release#4557]
Testing #4516

After forwarding a port and then running a process on the same port I get this notificaiton:

![image](https://user-images.githubusercontent.com/35271042/109068344-95827100-76a4-11eb-88ac-979acc923202.png)

I then click on "Preview in Editor" and it opens in the browser, which I think is not expected because that's the same action as "Preview in Browser"

**Comment by alexr00** [comment]
@misolori I'm not able to repro this. Are you using desktop?

![recording (42)](https://user-images.githubusercontent.com/38270282/109164152-64747000-777a-11eb-945c-49e5d04ed48d.gif)

**Comment by alexr00** [comment]
Hmm. If you're using web looks like we have a bug there. That button shouldn't show in web.

**Comment by alexr00** [comment]
I'm going to assume this was web and fix that bug :)

**Comment by misolori** [comment]
Yes, this was on Codespaces. Thanks!
