### ISSUE TITLE
Use locally defined devcontainer.json

### ISSUE THREAD

**Issue by MHacker9404** [microsoft/vscode-remote-release#4561]
I would like to define one or more local devcontainer.json files that I can use to open GitHub repos that don't have their own file.  I do not want to have to define a folder structure for every single GH repo, nor do I want to push these JSON files to the GH repository.

**Comment by Chuxel** [comment]
@MHacker9404 That sounds like this capability: https://code.visualstudio.com/docs/remote/create-dev-container#_alternative-repository-configuration-folders

Are you in need of something more?

**Comment by MHacker9404** [comment]
No – because unless I’m missing something – this would require creating a folder structure for every repository.

I want to create a single default devcontainer.json that I can use for any repository that doesn’t already have the file.
