### ISSUE TITLE
Cannot ssh to a linux server

### ISSUE THREAD

**Issue by Jaimecclin** [microsoft/vscode-remote-release#4562]
Issue Type: <b>Bug</b>

2021/2/26

After updating my VScode, I cannot ssh to my work station. Error message is timeout, everytime. I've tried my windows original powershell and it worked perfect. So I speculate it's ab extension error...

Extension version: 0.64.0
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.24GB free)|
|Process Argv|--crash-reporter-id a5069521-ce80-45b2-bd13-1d1cd6f1637c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by bamurtaugh** [comment]
Could you please include your logs (i.e. Output > "Remote - SSH" panel)?
