### ISSUE TITLE
Node-explosion on diconnect

### ISSUE THREAD

**Issue by beppo-sturmtief** [microsoft/vscode-remote-release#4565]
Hi, 
first: many thanks for the great tool!

I am facing the following problem: I use the remote extension to work on a webhosting-account (VSCode on Windows, target on linux) . But my internet connection has a problem and regularily disconnects. Whenever this happens, the VS Code connection breaks too, and i cannot reconnect because of timeouts - and the website goes down, too. When i patiently com throug with ssh/putty, i find the node process running rampant at 100% CPU load, drowning out the whole server. this is a real problem on a 1 CPU (virtual) server as it takes out the whole system.

Best regards and thanks again,
Simon

**Comment by beppo-sturmtief** [comment]
Additional Info:

Remote SSH AddOn version: 0.64.0 

VS Code: 

Version: 1.53.2 (system setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by roblourens** [comment]
Can you check the command arguments of that node process? And are you using any extensions on the remote?
