### ISSUE TITLE
Unable to create initializeCommand script that works across Windows and Codespaces

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-remote-release#4568]
## Context
I am trying to create a script that would add some variables to .env file at the root of the repo **before** dev container(s) are spun up E.g. some variables contain passwords shared between the dev container and the database (dependency) container. I can't make it to work on Windows (with Linux-based devcontainer) and also in Codespaces. @Chuxel suggested I open an issue.

- VSCode Version: 1.53.2
- Local OS Version: Windows 10 Enterprise 20H2 build 19042.804
- Remote OS Version: Ubuntu 20.04 (not really important)
- Remote Extension/Connection Type: Docker devcontainer (Docker Desktop 3.1.0 in WSL2 mode)

## Steps to Reproduce

1. Start with https://github.com/microsoft/vscode-dev-containers/tree/master/containers/javascript-node-postgres 
2. Add `scripts` folder with the following files

#### scripts/initrepo:
```shell
#!/usr/bin/env bash

echo "Repo initialization done!"
```

#### scripts/initrepo.cmd:
```
powershell scripts/initrepo.ps1
```

#### scripts/initrepo.ps1:
```
Write-Host "Repo initialization done!"
```

3. Add the following to `devcontainer.json`

```json
  "initializeCommand": "scripts/initrepo"
```

4. Do "Reopen in Container" gesture in VS Code

## Expected
- when run on Windows, the `initrepo.cmd` should be launched and call `initrepo.ps1` successfully
- when run in GitHub Codespaces, or on Mac/Linux, the `initrepo` script should be run successfully

## Actual
(this is from Windows)

```console
[2021-02-26T01:54:55.661Z] [PID 91920] [375 ms] Server API version: 1.41
[2021-02-26T01:54:55.798Z] [PID 91920] [512 ms] Start: Run: C:\WINDOWS\system32\cmd.exe /c scripts/initrepo
[2021-02-26T01:54:55.929Z] [PID 91920] 'scripts' is not recognized as an internal or external command,
operable program or batch file.
[2021-02-26T01:54:55.932Z] [PID 91920] [646 ms] Command failed: C:\WINDOWS\system32\cmd.exe /c scripts/initrepo
```

I tried various ways of quoting/prefixing the script name, as well as the array syntax for the `initializeCommand` setting, but so far I was unable to come up with something that would work both on Windows, as well as in Codespaces.

Something to consider: perhaps `devcontainer.json` could support a set of platform-specific properties just like `launch.json` does: https://code.visualstudio.com/docs/editor/debugging#_platformspecific-properties  We could make `initializeCommand` one of these per-platform-overridable properties.

**Comment by karolz-ms** [comment]
@bamurtaugh FYI

**Comment by karolz-ms** [comment]
Another user had essentially the same suggestion: https://github.com/microsoft/vscode-remote-release/issues/3981

**Comment by chrmarti** [comment]
This might work if you put the scripts in the workspace folder.

Related: #2067

**Comment by karolz-ms** [comment]
@chrmarti  if you mean putting scripts in the root folder of the workspace, I tried that too, unfortunately same problem 😞

**Comment by chrmarti** [comment]
Implementing this by making the array variant check for executables on Windows by the various executable extensions supported by Windows. E.g., `"initializeCommand": [".devcontainer/init"] will now run `init.cmd` (if that exists) on Windows and `init` on Linux and Mac.

The string variant of `"initializeCommand"` is run by the platform's default shell and parsing and updating that might have corner cases that are difficult to handle, so I'm avoiding that for now.

Another option would have been to allow `"initializeCommand"` to be a map from platforms to commands, but there are requests for other properties to become overridable by platform and I think we better address all these requests in a consistent way at some point.
