### ISSUE TITLE
Support to use Containers with a remote DOCKER_HOST

### ISSUE THREAD

**Issue by JMDC-SUN** [microsoft/vscode-remote-release#457]
A sl3_get_record error occurred

> Error: write EPROTO 8324:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:d:\_vsts\3\s\vendor\node\deps\openssl\openssl\ssl\record\ssl3_record.c:252:
> 
>         at WriteWrap.afterWrite [as oncomplete] (net.js:833:14)

Case: Developing inside a container on a remote Docker host
remote Docker :  18.09.6/centos7.5
client Docker:  Docker desktop/windows10

I set  DOCKER_HOST to host_ip:2376, when I run " Remote-Containers: Reopen Folder in Container command",  sl3_get_record error occurred.

**Comment by egamma** [comment]
// fyi @chrmarti

**Comment by chrmarti** [comment]
That should work if you set the environment variable before launching VS Code from the same (external) terminal. Does the Docker extension show the containers from the remote host?

(Note that I'm adding (not released yet) support for the Docker extension's `"docker.host"` setting, see #171.)

**Comment by JMDC-SUN** [comment]
Thank you very much! 
I guess my host docker daemon use port 2376(means tls), but not set ssh key for docker.
I change host docker daemon  port  from 2376 to 2375 for not use TLS. VS code show container list in Docker extention and attach to any running containers on host. It work very Well.

**Comment by chrmarti** [comment]
Thanks @JMDC-SUN . Closing this issue then.
