### ISSUE TITLE
Javascript breakpoint not work when setcap nodejs

### ISSUE THREAD

**Issue by clarkttfu** [microsoft/vscode-remote-release#4572]
- VSCode Version: 1.53.2
  Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
  Date: 2021-02-11T11:45:54.515Z (2 wks ago)
  Electron: 11.2.1
  Chrome: 87.0.4280.141
  Node.js: 12.18.3
  V8: 8.7.220.31-electron.0
  OS: Darwin x64 20.3.0
- Local OS Version: MacOS 11.2.2
- Remote OS Version: Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
1. `sudo setcap cap_net_admin+ie $(which node)`
2. start a debug session inside vscode and use the default nodejs executable

Expected:
VScode should stop at breakpoint.

Does this issue occur when you try this locally?: No, so far as I know, MacOS does not support Linux capabilities
Does this issue occur when you try this locally and all extensions are disabled?: Not apply

**Comment by clarkttfu** [comment]
This issue has been existed for months.. It was good before April 2020.

**Comment by clarkttfu** [comment]
`sudo setcap cap_net_admin+ie` to the vscode server's node executable does not work either.

**Comment by clarkttfu** [comment]
I also submitted https://github.com/microsoft/vscode-js-debug/issues/852

**Comment by connor4312** [comment]
Duplicates the linked issue
