### ISSUE TITLE
open source this extension

### ISSUE THREAD

**Issue by christian-korneck** [microsoft/vscode-remote-release#4574]
I was looking for the sources of the `ms-vscode-remote.remote-containers` extension (was interested to see if I can add a convenience config option and potentially send a PR), but couldn't find it. This rep seems to only host docs and issues.

Am I right that this extension is currently not open source? If so, this is a "feature" request to open source it.  :)

**Comment by chrmarti** [comment]
This is currently not on the roadmap. Please see https://code.visualstudio.com/docs/remote/faq#_license-and-privacy for additional information. Thanks.
