### ISSUE TITLE
Forwarded ports

### ISSUE THREAD

**Issue by jasper-zanjani** [microsoft/vscode-remote-release#4578]
Issue Type: <b>Bug</b>

I can't see the Forwarded Ports section in the Remote Explorer! I tried uninstalling and reinstalling and combed through the settings to see if there is some way to reveal it, but it looks as though this feature has been removed entirely!

Extension version: 0.20.0
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.21313
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (23.36GB free)|
|Process Argv|--crash-reporter-id 855721de-7b11-4a8f-9c8b-1beebb08b77e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3407)|
|Memory (System)|15.59GB (14.46GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30264245
pythontbcf:30260844

```

</details>

**Comment by roblourens** [comment]
It has been moved to the panel, you will see a "Ports" view there now.

**Comment by jasper-zanjani** [comment]
I am running VS Code 1.53.2 on both Windows and Linux machines.
I don't see any Ports section in the Panel on either operating system, but my Linux machine still has the Forwarded Ports in the Sidebar (see below)
![vscode](https://user-images.githubusercontent.com/8889926/109640382-6b0a3b00-7b1e-11eb-831b-b9f967b3482f.png)

This section was present in Windows until recently, and if it has been moved to the Panel then it is well-hidden!

**Comment by jasper-zanjani** [comment]
My work computer is also version 1.53.2 (user) and I can see the Ports section! what is going on?!

![vscode](https://user-images.githubusercontent.com/8889926/109653509-1cb16800-7b2f-11eb-948c-bb9ff84efafa.png)

**Comment by roblourens** [comment]
Sorry in 1.54 it's in the panel. I'm not sure what you're seeing on Windows, can you share a screenshot?

**Comment by jasper-zanjani** [comment]
![image](https://user-images.githubusercontent.com/8889926/109797892-0f0be900-7be8-11eb-9188-0e899cb5ed3d.png)

I simply can't see the Forwarded Ports section on VS Code on my home computer. I've tried removing and adding the Remote extension and uninstalling/reinstalling VS Code, to no avail.

**Comment by alexr00** [comment]
The "Ports" view is not available when connected to a WSL remote since no port forwarding is needed in that case.

**Comment by jasper-zanjani** [comment]
That is untrue
