### ISSUE TITLE
Building process hangs with postCreateCommand

### ISSUE THREAD

**Issue by Amblizer** [microsoft/vscode-remote-release#458]
- VSCode Version: 1.35.0-insider
- Local OS Version: Windows_NT x64 10.0.17763
- Remote OS Version: Debian 9
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Non-stop app will prevent build-process to complete. For example to run Jupiter notebook after building, I put the following line in `devcontainer.json`:

``` md
"postCreateCommand": "jupyter notebook --ip=0.0.0.0 --allow-root --no-browser"
```

2. Open the folder in container, and the "Installing Dev Container" notice and flowing banners hang perpetually.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
We wait for the `"postCreateCommand"` to complete. That is by design, so you can set up things before we launch.

You can add `"overrideCommand": false` to your `devcontainer.json` and then use `CMD` in the Dockerfile to run the notebook.
