### ISSUE TITLE
Attach Visual Studio Code to Windows Containers Fails

### ISSUE THREAD

**Issue by 41GitHub** [microsoft/vscode-remote-release#4580]
Is it possible to Attach to a Windows container?

**Issue**
Right click on a Windows Container -> Attach Visual Studio Code
failure in Windows system call: The user name or password is incorrect.

- VSCode Version: 1.53.2
- Local OS Version: Win 10
- Remote OS Version: Windows 2016 Server
- Remote Extension/Connection Type: 

Steps to Reproduce:

1. Right click on a Windows Container -> Attach Visual Studio Code

**Comment by chrmarti** [comment]
Not currently. Duplicate of https://github.com/microsoft/vscode-remote-release/issues/445.
