### ISSUE TITLE
[port-forwarding]Add port to forwarding is not working

### ISSUE THREAD

**Issue by lordzpipo** [microsoft/vscode-remote-release#4582]
Host: MacOS 10.15.7
Guest: Windows 10

using remote-ssh tabs to add port for forwarding in vscode is not working
have to manually add the command `LocalForward <port> localhost:<port>` in ssh config file

vscode version: 1.53.2

**Comment by roblourens** [comment]
Sorry, what do you mean "remote-ssh tabs"?

**Comment by lordzpipo** [comment]
hi @roblourens, before major update, 
remote-ssh service has a tabs on navbar, it something like current version (portal tabs in terminal area)

**Comment by roblourens** [comment]
I still don't know what you mean. A screenshot might help.
