### ISSUE TITLE
Please upgrade Docker Compose to >=1.26 in `vsc-volume-bootstrap` image

### ISSUE THREAD

**Issue by mrmachine** [microsoft/vscode-remote-release#4588]
I am trying to `Clone Repository in Container Volume` and my `devcontainer.json` file inside my repository on GitHub is configured to use a `docker-compose.yml` file which in turn has `env_file: .env`, plus Docker Compose in general is hardcoded to read the `.env` file if it exists.

My `.env` file (also in the repository) is in a format that is only compatible with Docker Compose >=1.26. It looks like this:

```
export FOO='BAR'
```

Earlier versions of Docker Compose`, including 1.24.1 as found in the `vsc-volume-bootstrap` image expect a simpler format:

```
FOO=BAR
```

We no longer use this format because it is less compatible with other tools and quirky. For example, the value is a literal string with no escaping. So with `FOO="bar"` I would end up with a value of `"bar"` (including the double quotes).

Currently, this manifests an error when attempting to bring up the composition:

```
In file /workspaces/FOO/.env: environment variable name 'export IMAGE_TAG' may not contains whitespace.
```

**Comment by mrmachine** [comment]
I manually updated this file: `~/.vscode/extensions/ms-vscode-remote.remote-containers-0.158.0/scripts/volumeBootstrap.Dockerfile` to use `FROM alpine:3.13.2`, and that gives me Docker Compose 1.27.4 and fixes the problem. It'd be great to see that change in the extension itself.

**Comment by RMacfarlane** [comment]
Verified by looking at the code change.
