### ISSUE TITLE
"Forward a Port" command from command palette doesn't handle validation correctly

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#4591]
![image](https://user-images.githubusercontent.com/38270282/109796860-f7992400-7c18-11eb-86ab-1958ba71662a.png)

This should be an info, not an error, and you should be allowed to proceed past it. Generally, it should match the behavior in the Ports view:

![image](https://user-images.githubusercontent.com/38270282/109797842-46938900-7c1a-11eb-90dd-310d88f35272.png)

**Comment by RachelGuo76** [comment]
@alexr00 Verified this bug on VS Code #[1.54.1](https://code.visualstudio.com) (Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8) with build #[1.0.3920](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4527664&view=results) on macOS Big Sur 11.1, this bug still reproduces, would you mind taking a look at it again?
![image](https://user-images.githubusercontent.com/67084699/110089152-b51a4780-7dd0-11eb-95fe-848f41757030.png)

**Comment by alexr00** [comment]
Thank you for verifying!
