### ISSUE TITLE
Request: Default theme setting(s) for remote workspaces

### ISSUE THREAD

**Issue by shepazon** [microsoft/vscode-remote-release#4593]
As someone working on multiple projects, some using remote workspaces for my day job, some using local workspaces also for my day job (using the remote ssh extension), and others using local workspaces for personal projects, and as someone who uses terminals and other such things frequently, a key problem I run into is that unless I manually configure a workspace to look different, I can't tell the difference between local and remote workspaces.

That's a problem for several reasons:

* Hard to keep straight which projects are where
* Hard to easily check that remote projects are all saved properly before disconnecting from the VPN that lets me access work
* Hard to be sure I'm working in the right mindset while working -- job or personal? official project or experimental hack on my local machine?

It would be very useful if among the configuration options available for remote workspaces were the ability to specify which theme to use by default when creating a new workspace, or for workspaces that don't override the theme.

**Comment by roblourens** [comment]
You can do this by setting the theme in your remote settings (see the Remote tab in the settings editor). Does that help?

**Comment by shepazon** [comment]
@roblourens I'm aware of that, but I would like something that's automatic. A separate default theme for remote windows. That way, I can avoid problems of being unclear which host I'm talking to (especially when using a terminal session in the window).

For example, when I'm using iTerm2 to work in Terminal, my local windows are an almost-black background (with a very slight red tinge, white foreground, with a red badge "Local" in the top-right corner in large letters. Remote windows appear with a noticeably greenish background, bright green foreground text (reminiscent of a good ol' green-screen CRT), and the green badge "Cloud" in the top-right corner.

These happen automatically. If I open a local window, then `ssh` to a remote server, the window automatically changes over to the cloud theme so I know what I'm using.

This is the behavior I want to reproduce in VS Code, in order to help keep all my numerous windows and connections clear. Bonus points for the ability to set individual default themes by remote hostname. :)

**Comment by roblourens** [comment]
> Bonus points for the ability to set individual default themes by remote hostname. :)

This is exactly what is already possible. So I still don't understand the difference between what you are asking for and how remote settings work. Set it once on the remote and it will apply to every window that connects to that remote.

**Comment by shepazon** [comment]
Yes, but not to *all* remotes. The idea is to have a default theme automatically applied to every remote window.

From: Rob Lourens ***@***.***>
Reply-To: microsoft/vscode-remote-release ***@***.***>
Date: Monday, March 15, 2021 at 2:06 PM
To: microsoft/vscode-remote-release ***@***.***>
Cc: "Shepherd, Eric" ***@***.***>, Author ***@***.***>
Subject: Re: [microsoft/vscode-remote-release] Request: Default theme setting(s) for remote workspaces (#4593)


Bonus points for the ability to set individual default themes by remote hostname. :)

This is exactly what is already possible. So I still don't understand the difference between what you are asking for and how remote settings work. Set it once on the remote and it will apply to every window that connects to that remote.

**Comment by roblourens** [comment]
It sounds like you want it per-remote hostname though right? We aren't likely to support separate settings for all remotes vs local windows, but we have settings applied automatically to every window of a particular host.
