### ISSUE TITLE
Opener service can add an extra http to addresses

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#4595]
The opener service allows internal URIs to be translated into external URIs. Some of these external URIs will end up having http or https already part of the URI. In this case, we should respect that scheme and not try to add or change it.

**Comment by RMacfarlane** [comment]
@alexr00 what's the best way to verify this fix?

**Comment by alexr00** [comment]
To verify:
1. Make a Codespace from https://github.com/plisy/pf-echo.
2. Connect to the Codespace from desktop.
3. F5 and wait for it to finish.
4. Open the Ports view, right click on the port and "Make Public".
5. Right click on the Port and "Open in Browser".
6. Verify that the URL that opens in your browser only has one http and doesn't have both http and https.
