### ISSUE TITLE
Not possible to execute postCreateCommand with pseudo tty for interactive commands

### ISSUE THREAD

**Issue by thexperiments** [microsoft/vscode-remote-release#4597]
- VSCode Version: 1.53.2
- Local OS Version: Ubuntu 20.04
- Remote OS Version: Ubuntu 18.04 
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. have a .devcontainer/devcontainer.json
2. have a "postCreateCommand" configured which needs an interactive shell (for example a login)
3. build the devcontainer
4. the build seems to stop, click on the notification to see the terminal
5. terminal shows log in prompt but you cant interact with it

I tried to exchange the command for a command which executes the script within a new shell

`"postCreateCommand" : "bash -i /tmp/entrypoint.sh",`

but this did not help.

My guess is that the problem is that vs code issues the postCreateCommand with `docker exec -i` where it would need a `docker exec -it`. Sadly the -t parameter is not supported by the runArgs config.

Our use case is configuring/logging-in several tools inside the container on first creation.

Looking forward to your suggestions.

**Comment by chrmarti** [comment]
Could you retry with the latest versions (VS Code 1.54 and Remote-Containers 0.163.0? That will automatically open a terminal for `"postCreateCommand"` and allows for keyboard input.

**Comment by thexperiments** [comment]
Great, just installed the insider build via snap (1.55) and it works like a charm without any additional things like extra interactive shell or so.

Will work with insider version for now. I guess snap non-insider code is a bit behind.
