### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-remote-release#4598]
Would be great if this project kept a changelog! 🙇

**Comment by roblourens** [comment]
Not sure which project you are looking at, but you can see the vscode release notes which has a link to remote-specific release notes here: https://code.visualstudio.com/updates/v1_54#_remote-development

Not at the individual bug fix level for remote extensions, but for important changes.

**Comment by janosh** [comment]
Good to know there are notes! I think they would find a wider audience though if they were found in the changelog tab of the extension page in VS Code itself or in this repo. At least that's where I was expecting them based on other extensions.

With changelog tab
![Screen Shot 2021-03-04 at 20 58 32](https://user-images.githubusercontent.com/30958850/110022686-85b1ff00-7d2c-11eb-9934-ca0bae5c558b.png)

Without changelog tab
![Screen Shot 2021-03-04 at 20 58 09](https://user-images.githubusercontent.com/30958850/110022682-8480d200-7d2c-11eb-9d0e-21bea8347536.png)

**Comment by roblourens** [comment]
If there was a page that just linked to here: https://github.com/microsoft/vscode-docs/tree/main/remote-release-notes would that be helpful or confusing?

**Comment by janosh** [comment]
I think that would be very helpful!
