### ISSUE TITLE
 PWD enviroment var set by remote extension breaks expectations

### ISSUE THREAD

**Issue by jrussellsmyth** [microsoft/vscode-remote-release#4599]
Under windows during remote devcontainer execution, vscode is forcing the PWD envirnoment var to be the location of the vscode binary, rather than the actual working directory.  This will break compose based builds that depend on PWD being the location of the project.

This is particularly problematic for externalized devcontainer configurations where compose "." shortcut will mean the externalized location rather than the project folder.

This is inconsistent with Mac host use, where PWD is not overridden.

- VSCode Version: 1.53.2
- Local OS Version: Windows 10
- Remote OS Version: any 
- Remote Extension/Connection Type: Docker

within a devcontainer config with a compose file, add a volume mapping $PWD:$PWD

expected behavior is binding a path within the container matching the exact path of the project to the matching host path, ie if project is in 
/home/myname/project
on the host, that path should be bound to 
/home/myname/project
within the contianer.

observed behavior is that PWD is set to the location of the vscode binary.

**Comment by chrmarti** [comment]
I don't see where we set PWD. Is this still a problem with VS Code 1.54?

**Comment by jrussellsmyth** [comment]
@chrmarti I spent some time narrowing down the conditions that provoke the issue a bit. This only occurs when the sources are on WLS filesystem. You can see in the logs that PWD is set on the command line being executed, overriding the value of PWD we would expect to be available in the shell.

Attached is a minimal devcontainer that will exhibit the behaviour.

The ability to use the PWD var in our compose files is used extensively to allow us to externalize our devcontainer configs, including the compose files, and still be able to properly reference paths in the project folder. Because our compose files are not in our project, the relative path capability of compose is not adequate.
[testcase.zip](https://github.com/microsoft/vscode-remote-release/files/6092216/testcase.zip)

**Comment by aeschli** [comment]
Verified with sample project [testcase.zip](https://github.com/microsoft/vscode-remote-release/files/6092216/testcase.zip)
- installed in a WSL distro at `/home/aeschli/workspaces/testcase`
- added a line `$PWD:$PWD` to the volumes in .devcontainer/docker-compose.yml
- in the started container, verified that there's a folder `/home/aeschli/workspaces/testcase`

If these are not the correct steps, please speak up.
