### ISSUE TITLE
port forwarding not auto start after vscode version update to 1.54

### ISSUE THREAD

**Issue by jjasoncool** [microsoft/vscode-remote-release#4601]
- VSCode Version:1.54
- Local OS Version:fedora 33
- Remote OS Version: centos 7
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. start debug 
2. Port forwarding cannot be started automatically and needs to be added manually. 
3. This problem will not occur until the version of vscode is updated. 

![圖片](https://user-images.githubusercontent.com/24731867/110055239-9481cb80-7d97-11eb-8197-ceaa24f4c615.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
The default changed for Remote-SSH, but you can override it by setting `"remote.autoForwardPortsSource": "process"` in your remote settings (Run the command F1 > `Preferences: Open Remote Setting`)
