### ISSUE TITLE
Stop importing local Git config into containers

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode-remote-release#4603]
This is essentially a reopen of #2267, because the issue is not resolved.

Currently when building a fresh Linux container on a Windows machine, I end up with this `~/.gitconfig` inside the container:

```
[core]
	editor = \"C:\\Users\\aaron\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe\" --wait
[user]
	name = Aaron Adams
	email = aaron@XXXXX.ca
[credential]
	helper = "!f() { /home/node/.vscode-server/bin/XXXXX/node /tmp/vscode-remote-containers-XXXXX.js $*; }; f"
```

Specific problems I have with this:

- The `core.editor` is invalid on Linux.
- I don't want my user name or email imported into the container.
- I don't want other developers' local configurations imported into their containers.

My current workaround is to append `git config --global --remove-section core; git config --global --remove-section user; git config --global core.editor "code --wait"` to `postCreateCommand` in `devcontainer.json`, but this is an ugly fix. It also presumes there aren't other settings in a developer's local `.gitconfig` that could affect/break Git inside the container.

This behaviour is something we should be able to easily disable in the container configuration. Each developer should not need to know this very specific implementation detail of remote containers.

More broadly, I think automatically importing a user's local Git config (including their name and email address!) into every remote container violates expectations. If somebody wants their Git config imported into all of their containers, I think they should configure that locally. It shouldn't be the default behaviour.

**Comment by chrmarti** [comment]
This is available as a setting:
![image](https://user-images.githubusercontent.com/9205389/110098143-242b7800-7da0-11eb-84bb-5dfc77661143.png)

**Comment by aaronadamsCA** [comment]
But that setting is not respected in `.vscode/settings.json`. There's no way to ship that setting with the container.

![image](https://user-images.githubusercontent.com/1505561/110111593-e1be6700-7db0-11eb-82b8-8930fc4717e2.png)

It's also just not correct default behaviour.

**Comment by chrmarti** [comment]
You can set this in your user settings, that will apply it to all dev containers, or in the devcontainer.json's "settings" property, that will copy it to the container's settings.

A better default might be to only copy specific properties over.

**Comment by aaronadamsCA** [comment]
Thank you for responding @chrmarti, I appreciate you discussing this even if you didn't necessarily agree with it.

I really appreciate the tip regarding `devcontainer.json`. That is non-obvious but it works great!

I still question why the local configuration is imported by default, but with a working _shippable_ setting to disable that behaviour, I'm good.

I'm now running the following shell script as my `postCreateCommand`:

```sh
git config --global core.editor "code --wait"
git config --global diff.tool vscode
git config --global difftool.vscode.cmd "code --wait --diff \$LOCAL \$REMOTE"
git config --global merge.tool vscode
git config --global mergetool.vscode.cmd "code --wait \$MERGED"
yarn install
```

Maybe in the future this extension would consider setting more than just `credential.helper` by default; "text editor sets itself as text editor" seems like fair game in terms of behaviour, and would probably improve ease of use for most folks.

**Comment by chrmarti** [comment]
Creating a feature request from that, thanks.
