### ISSUE TITLE
Opening a container prompts for language extension suggestions

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-remote-release#4608]
On the latest Insiders:

1. Have one or more language packs installed (I do for testing things)
2. Open a new container
3. Get notification spam for each language page

![](https://memes.peet.io/img/21-03-9907e903-30ec-49b5-8e52-17622fd35d87.png)

**Comment by chrmarti** [comment]
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/4617
