### ISSUE TITLE
Remote SSH - Automatic connection when starting VSCode

### ISSUE THREAD

**Issue by rhero12** [microsoft/vscode-remote-release#461]
- VSCode Version: MacOS 10.9
- Local OS Version: MacOS Mojave 10.14.3

Hi,

Whenever I quit VSCode and open again it automatically tries to connect to the last SSH session I had open. I was wondering if there's a way to stop this from happening? I also don't seem to be able to disconnect from an SSH session unless I quit the app. Am I missing something simple? (I feel like I must be overlooking something).

Thanks in advance!

**Comment by egamma** [comment]
@rhero12 
>Whenever I quit VSCode and open again it automatically tries to connect to the last SSH session I had open. 

This is the intended behaviour. VS Code will reopen the last opened workspace, if this was a remote workspace then VS Code will re-establish the remote connection. You can configure this using the setting `window.restoreWindows`.

>I also don't seem to be able to disconnect from an SSH session unless I quit the app. 

pls see https://github.com/microsoft/vscode-remote-release/issues/403#issuecomment-494595933
