### ISSUE TITLE
vscode.extensions.onDidChange not triggered when installing an extension

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-remote-release#4610]
Version: 1.55.0-insider
Commit: 04770364fdc1bebeca9d1a257df2cacce06b35d6
Date: 2021-03-05T15:41:28.520Z (1 day ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
- Remote OS Version: ubuntu 20.04
- Remote Extension/Connection Type: Docker/Codespaces

Steps to Reproduce:

1. Grab this repo: https://github.com/TylerLeonhardt/vscode-auth-test/
2. Notice that https://github.com/TylerLeonhardt/vscode-auth-test/blob/main/src/extension.ts just does `vscode.extensions.onDidChange`
3. Run the extension
4. Install another extension like `Vim`
5. Notice that `vscode.extensions.onDidChange` does not get triggered.

### Expected

A notification pops up because of the code:
```ts
        vscode.extensions.onDidChange(() => {
		vscode.window.showInformationMessage('extensions changed!');
	});
```

### Actual

No notification

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by sandy081** [comment]
@TylerLeonhardt 

- Is this happening only with vim extension?
- Is the extension that is installed is getting activated?

**Comment by TylerLeonhardt** [comment]
> Is this happening only with vim extension?

No. It seems to happen with any extention I install in Remote.

> Is the extension that is installed is getting activated?

Yes.

Have you tried the repro steps above? Can you not repro?

**Comment by sandy081** [comment]
It works for me

![image](https://user-images.githubusercontent.com/10746682/110344544-dfb50c00-802d-11eb-93b9-cf226a134547.png)

Probably the extension you are installing is getting installed locally and not on remote. Try installing an extension that will be installed remotely for eg., vetur.

Extension that is installed locally will be activated on local extension host and hence the change event is not triggered in the remote extension host. CCing @alexdima if he would like to add more info.

**Comment by TylerLeonhardt** [comment]
Let's close this... I think my problem is that my extension I'm debugging isn't activating for some reason...

**Comment by TylerLeonhardt** [comment]
Also need to deal with this issue too...
https://github.com/microsoft/vscode-remote-release/issues/4628
