### ISSUE TITLE
High CPU zombie Docker processes on Apple M1 from Remote - Containers

### ISSUE THREAD

**Issue by verekia** [microsoft/vscode-remote-release#4612]
On my Apple M1 laptop, the Remote - Containers extension causes random high CPU **docker** processes to appear. Doesn't matter if the Docker daemon is running or not, these process appear, and do not go away, even after I close VS Code. They typically use 98-99% of CPU %, but I've had some at 150% ou 200%+. As I use VS Code, they can stack up to consume a lot of my computer's resource. They make it impossible for me to use remote containers reasonably.

Disabling the extension prevents them from appearing.

### VSCode Version
Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:45:03.974Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.1.0
Happens with both the Universal install, and the Apple Silicon install.

Version: 1.55.0-insider
Commit: 04770364fdc1bebeca9d1a257df2cacce06b35d6
Date: 2021-03-05T15:45:15.004Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.1.0

### Local OS Version
Model Name:	MacBook Pro
Model Identifier:	MacBookPro17,1
Chip:	Apple M1
Total Number of Cores:	8 (4 performance and 4 efficiency)
Memory:	16 GB
System Firmware Version:	6723.50.2

### Remote Extensions
Remote - Containers: 0.163.0
Remote Development: 0.20.0

### Docker
Version 3.1.0 (60984) Tech Preview
Engine 20.10.3

### Steps to Reproduce:

1. Open VS Code with **Remote - Containers** enabled. Doesn't matter if the Docker daemon is running or not.
2. Click around, open projects, select the Remote dev view, open files, including Docker files. The high CPU process appears pretty randomly. I haven't been able to find what causes it exactly. They sometimes appear without doing anything. I had 2 appear while writing this ticket without touching VS Code at all, as VS Code was open in the background.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No. It seems only caused by "Remote - Containers".

<img width="1440" alt="Screenshot 2021-03-07 at 22 58 08" src="https://user-images.githubusercontent.com/522007/110247083-a49dd480-7f6a-11eb-912e-59834ecdce47.png">

See the detailed logs in this Gist:

https://gist.github.com/verekia/1cd945168b97f1babeb910c2d81b1eec

My guess is that the Remote - Containers extension performs checks to see what containers are currently running using the docker binary, but these calls somehow go wrong and trigger the massive consumption of resources.

It seems from the logs that the call to docker made by the extension is going through Rosetta 2 for some reason.

**Comment by chrmarti** [comment]
We poll with `docker context ls` for the current context. Does that command work for you?

One simple improvement I will include is that the polling only starts when the Remote-Explorer viewlet shows the Containers tree for the first time.

**Comment by verekia** [comment]
With or without Docker for Mac running I get the same result:

```sh
~ > docker context ls
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT               KUBERNETES ENDPOINT   ORCHESTRATOR
default *           moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                         swarm
```

**Comment by chrmarti** [comment]
Please try the updated Remote-Containers 0.163.1 to check if that fixes it. Possibly related: #4614

**Comment by verekia** [comment]
Unfortunately, it did not.

<img width="785" alt="Screenshot 2021-03-09 at 00 15 10" src="https://user-images.githubusercontent.com/522007/110356484-99b27500-803a-11eb-9d3d-2c242a1e19e5.png">

(that was after restarting VS Code completely and having no other docker process running)

**Comment by chrmarti** [comment]
Could you check what the process parameters are? (`ps -p <process id>`)

**Comment by verekia** [comment]
Sure, thank you.

```sh
~ > ps -p 3119
  PID TTY           TIME CMD
 3119 ??         0:56.65 docker context ls --format {{json .}}
```

**Comment by chrmarti** [comment]
Could you run `docker context ls --format '{{json .}}'` manually to see if it has anything to do with Remote-Containers?

**Comment by verekia** [comment]
I ran it hundreds of time and it eventually did trigger the unwanted process!

It happened in both a normal shell and under a Rosetta shell (with `env /usr/bin/arch -x86_64 /bin/zsh --login`)

```
~ > docker context ls --format '{{json .}}'
^[[A{"Current":true,"Description":"Current DOCKER_HOST based configuration","DockerEndpoint":"unix:///var/run/docker.sock","KubernetesEndpoint":"","ContextType":"moby","Name":"default","StackOrchestrator":"swarm"}
~ > docker context ls --format '{{json .}}'
^[[A{"Current":true,"Description":"Current DOCKER_HOST based configuration","DockerEndpoint":"unix:///var/run/docker.sock","KubernetesEndpoint":"","ContextType":"moby","Name":"default","StackOrchestrator":"swarm"}
~ > docker context ls --format '{{json .}}'
^[[A{"Current":true,"Description":"Current DOCKER_HOST based configuration","DockerEndpoint":"unix:///var/run/docker.sock","KubernetesEndpoint":"","ContextType":"moby","Name":"default","StackOrchestrator":"swarm"}
~ > docker context ls --format '{{json .}}'
^[[A{"Current":true,"Description":"Current DOCKER_HOST based configuration","DockerEndpoint":"unix:///var/run/docker.sock","KubernetesEndpoint":"","ContextType":"moby","Name":"default","StackOrchestrator":"swarm"}
~ > docker context ls --format '{{json .}}'
^[[A{"Current":true,"Description":"Current DOCKER_HOST based configuration","DockerEndpoint":"unix:///var/run/docker.sock","KubernetesEndpoint":"","ContextType":"moby","Name":"default","StackOrchestrator":"swarm"}
~ > docker context ls --format '{{json .}}'
^[[A{"Current":true,"Description":"Current DOCKER_HOST based configuration","DockerEndpoint":"unix:///var/run/docker.sock","KubernetesEndpoint":"","ContextType":"moby","Name":"default","StackOrchestrator":"swarm"}
~ > docker context ls --format '{{json .}}'
assertion failed [abi_info.kind == AbiKind::TranslatedCode]: emulated forward to an arm pc that isn't in translated code. arm_pc=0x1056234d8 abi_kind=6 emulation_interval=[0x105631048,0x10563105c) instruction_interval=[0x105631034, 0x10563105c) x86_rip=0x100d823
(ThreadContextRegisterState.cpp:677 move_to_instruction_boundary)
```

**Comment by verekia** [comment]
Related:
https://github.com/hashicorp/terraform/issues/27257

**Comment by chrmarti** [comment]
Could you open an issue for Docker at https://github.com/distribution/distribution/issues? I don't have an M1 machine available for testing. Thanks.

**Comment by verekia** [comment]
@chrmarti Sorry, I'm a bit confused. I'm not familiar with how Docker operates its repositories, but this repo seems to be about container registries? I'm not sure how to introduce the issue there. May I have a bit of context on why this is the right place to open an issue about my Docker process issue? Thank you.

**Comment by chrmarti** [comment]
Sorry, somehow pasted the wrong link. Since found the following which could be the issue you see: https://github.com/docker/for-mac/issues/5166

**Comment by verekia** [comment]
Thank you. Looks like it's an Apple / Docker problem, so we can close this issue :) At least we now have a bit of documentation on the matter.
