### ISSUE TITLE
"Opening dev container" hangs on Mac OS.

### ISSUE THREAD

**Issue by fwip** [microsoft/vscode-remote-release#4614]
- VSCode Version: 1.54.1
- Local OS Version: Mac Catalina 10.15.7
- Remote OS Version: Centos 8
- Remote Extension/Connection Type: Docker
- Docker For Mac version: 3.1.0 (51484)

Steps to Reproduce:

1. Open repository with previously-working docker configuration.
2. Execute "reopen in container" or "rebuild and reopen in container"
3. Observe hang.

"Starting Dev Container" sits without making progress.

Log:
```
[4 ms] Remote-Containers 0.163.0 in VS Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8).
[914 ms] Start: Resolving Remote
[915 ms] Setting up container for folder or workspace: /Volumes/projects/stamlims2
[934 ms] Start: Check Docker is running
[935 ms] Start: Run: docker version --format {{.Server.APIVersion}}
```

Running `docker version --format {{.Server.APIVersion}}` manually works, and reports `1.41`.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A, Yes

This happens across several of my projects that were working normally last week. I have tried reinstalling VS Code and this extension without luck.

**Comment by fiznool** [comment]
Same issue here 😢

**Comment by okiess** [comment]
Same here for all my docker-compose based dev containers.

**Comment by andreiborisov** [comment]
Can confirm that the issue exists

**Comment by andreiborisov** [comment]
Installing 0.134.1 version of the extension resolves the issue (maybe slightly newer versions will also work)

**Comment by megri** [comment]
@andreiborisov Confirmed working here as well, thank you!
Was the version number a random pick or did you test later versions?

**Comment by fiznool** [comment]
> Installing version 0.134.1 of the extension resolves the issue (newer versions may also work)

Thank you!!

I've just tried a few versions and the last good version is 0.149.0, the issue starts appearing from 0.150.0 onwards.

For others coming here, to install an older version of the Remote Containers extension:

- Open your codebase in a normal VSCode window, i.e. _not_ in a dev container
- Open the _Extensions_ pane in the left hand menu
- Find the _Remote - Containers_ extension and click on the settings cog
- From the menu, choose _Install Another Version..._
- In the menu, select __0.149.0__

This seems to work fine.

<img width="667" alt="Screenshot 2021-03-08 at 11 12 37" src="https://user-images.githubusercontent.com/820863/110314199-774f3600-7fff-11eb-8b5b-1e1a78e33e60.png">

**Comment by chrmarti** [comment]
Remote-Containers 0.158.0 was the version released alongside VS Code 1.53. That should be safe to go back to.

I'm preparing a fix for later today/tomorrow.

**Comment by chrmarti** [comment]
Please try the updated Remote-Containers 0.163.1 to check if that fixes it.

**Comment by fwip** [comment]
Confirmed, this is fixed now. I appreciate the speedy turnaround, y'all do good work.
