### ISSUE TITLE
Use remote.portAttributes for the remote samples

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#4616]
The vscode-remote-try-* samples currently leverage dynamically forwarded ports, and with the addition of the remote.portAttributes setting: https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_53.md#port-attributes, these samples would make a good location to showcase this setting in action.

- Introduce remote.portAttributes in the samples
     - Determine which specific settings we'd like to use - i.e. I thought including a "My Port" label and notifying on autoforward made sense
- Update the README to explain the remote.portAttributes
- Review the README's overall and update them with any other dev containers or Codespaces updates (i.e. dev containers in Codespaces can now be rebuilt)

I also realized we discussed updating "samples" to include the new port settings, but didn't specify _which_ samples - do we want/need to update any of https://github.com/microsoft/vscode-dev-containers/tree/master/containers samples and/or readmes to include remote.portAttributes?

**Comment by bamurtaugh** [comment]
Started this process with the remote-try-go repo: https://github.com/microsoft/vscode-remote-try-go/pull/30.

**Comment by bamurtaugh** [comment]
I believe I've now opened PRs for all relevant try-* repos (i.e. they forward ports in some way):
- Go https://github.com/microsoft/vscode-remote-try-go/pull/30 (already merged)
- Node https://github.com/microsoft/vscode-remote-try-node/pull/21
- Python https://github.com/microsoft/vscode-remote-try-python/pull/18
- .NET Core https://github.com/microsoft/vscode-remote-try-dotnetcore/pull/21
- PHP https://github.com/microsoft/vscode-remote-try-php/pull/7

**Comment by Chuxel** [comment]
FYI - There appears to be a bug in processing settings in devcontainer.json in GitHub Codespaces that is preventing these updates from working.

**Comment by bamurtaugh** [comment]
Went ahead and merged since they've been tested in Remote-Containers, and the readme updates followed the same format as the first Go PR. Since I believe that addresses all the try-* repos, closing this one out.

If there are any other updates that should be done beyond these that you think of, just let me know!
