### ISSUE TITLE
Allow "Remote-Containers: Clone Repository in Container Volume" to show all branches

### ISSUE THREAD

**Issue by chemelli74** [microsoft/vscode-remote-release#4619]
Default config is to configure git to fetch only main repo and not branches.
I had to change **cloned_repo/.git/config** to achive this:

Old : `fetch = +refs/heads/dev:refs/remotes/origin/dev`

New: `fetch = +refs/heads/*:refs/remotes/origin/*`

Would be handy to have an option from UI when you first run clone repository in Container volume to choice if fetching only main repo or all branches as well.

**Comment by chrmarti** [comment]
We clone using `--branch`. I guess that pins the branch in the `.git/config`.

**Comment by chemelli74** [comment]
> We clone using `--branch`. I guess that pins the branch in the `.git/config`.

Yup, this is the reason.
Are you considering an option to choice between single branch / entire repo ?

Simone

**Comment by chrmarti** [comment]
We could just always do this.

Note for myself: https://stackoverflow.com/questions/17714159/how-do-i-undo-a-single-branch-clone

**Comment by Juice10** [comment]
@chrmarti I noticed you closed this issue, but I can't seem to find a corresponding PR or commit. Do you know if this issue was solved?

**Comment by chrmarti** [comment]
@Juice10 The fix will be in the next version of Remote-Containers, likely 0.170.0. That will initially require VS Code Insiders to run, but then become available for VS Code 1.56 once that is released. (The Remote Development extensions are not OSS, see https://code.visualstudio.com/docs/remote/faq#_license-and-privacy.)

**Comment by leighmcculloch** [comment]
> We clone using `--branch`. I guess that pins the branch in the `.git/config`.

It's the `--depth=1` that the plugin is using that causes the fetch origin search path to be limited to the branch.

**Comment by chrmarti** [comment]
Just released Remote-Containers 0.170.0. Please give that a try. Currently requires VS Code Insiders: https://code.visualstudio.com/insiders/

**Comment by aaronadamsCA** [comment]
Thanks, `git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"` did the trick to fix a repository cloned using VS Code 1.55.2.

To help anyone searching for this:

If you get "no such branch" when using the GitHub Pull Requests and Issues extension to check out a PR branch, this is probably the root cause. Drop to terminal and run the above command, and you'll be good to go!
