### ISSUE TITLE
Allow to specify an environment file (SDK) to source after ssh login

### ISSUE THREAD

**Issue by ctxnop** [microsoft/vscode-remote-release#4622]
### Use case

Cross-development in C and C++ environments are often based on a SDK which provides a file to source that define many environment variables like compiler path and default options. All yocto based distributions provides such a SDK, even if the target is the same arch as the host, because it's not only a matter of CPU arch, it's also a matter of dependencies.

See an exemple here (the SDK is sourced in step 5): https://docs.huihoo.com/automotivelinux/docs/getting_started/en/dev/reference/setup-sdk-environment.html

### Expected

I would like to have a way to specify the path of the said environment file that it has to be sourced before running any tool (cmake, make, gcc, etc...) and also when opening a terminal.

### Attempts

The ssh config file may already have something: RemoteCommand.
Not sure if it is enough of really working the way I expect it. I tried to add ```RemoteCommand "touch /home/myuser/remotecommand.test"``` just to check if it could be used, but the file wasn't create, so it seems that this option is currently ignored.

If something to achieve that is already done, then the documentation should makes it clear directly on the first how-to-setup page as it's a really common issue to solve when cross-developing.

**Comment by roblourens** [comment]
Could be this https://github.com/microsoft/vscode-remote-release/issues/4474 or this https://github.com/microsoft/vscode-remote-release/issues/1722

**Comment by ctxnop** [comment]
> Could be this #4474 or this #1722

I'm not really sure to agree with you. As I explained, I TRIED RemoteCommand to solve my issue and it doesn't work. It does not means that it's the way to go. The issue I have is I need to source a SDK so that any command remotely run by vscode is inside the right environment.

If, to solve the issue, RemoteCommand is the right and only way to go, then ok, this issue is a duplicate. But if there is other means to achieve this, then this issue it's not a duplicate as I don't ask to use RemoteCommand.

**Comment by roblourens** [comment]
I think that RemoteCommand is probably the best way to do it, and it is ignored currently because of that issue I linked. The other issue handles some other cases of customizing the scripts that run while connecting to the remote.

But this has come up before and it's probably useful to be thinking about it separately with some vscode-specific config too so I'll keep this open for discussion.

Do you have a workflow with local vscode for this, for example do you source this sdk in a terminal, then launch vscode from the terminal to inherit its environment? Or have you checked whether the C++ extension provides this functionality to fix the environment?

**Comment by ctxnop** [comment]
Usually I source the sdk then start a vscode inside this terminal to inherit the env. I think it's the easiest, fastest and most reliable way to work with those kind of sdk.
In theory, if the sdk was well made, then we should source it once before calling cmake, then everything is in cmakecache so you don't have to worry anymore. Which tend to means that it's should be the cmake extention job to work around this issue.
Unfortunately this shouldn't be done this way because those kind of sdk often provide a custom build of cmake that should be used instead of the local one. Also, you may want to use something else than cmake. And finally, I already encountered few sdk that did really nasty thing so that inheriting the environment may no be enough... But I'm not sure it'd a good idea to support such bad pratices.

**Comment by roblourens** [comment]
We now have RemoteCommand support, so I'll close this
