### ISSUE TITLE
High CPU usage in WSL after last update

### ISSUE THREAD

**Issue by Salmondx** [microsoft/vscode-remote-release#4637]
After recent update of VSCode, a CPU usage of a `node` process from vscode-remote extension is incredibly high. This process constantly consumes 30-40% of CPU.

VSCode version: **1.54.1**
vscode-remote extension version: **0.54.2**
WSL 1
Ubuntu 18.04

I tried to run vscode's developer tools to check resources usage and to collect performance profile, it doesn't show anything. Also disabling all other extensions doesn't help. Obviously it works ok only when I run vscode natively in windows, not from WSL.

Any ideas why it is happening and what info I can provide to you to help with debugging?

**Comment by Salmondx** [comment]
Rolling back to the previous version of extension (1.54.0) also didn't help. Looks like the problem is again with WSL? Any suggestions how to debug what is causing node to consume so much CPU in idle?

**Comment by Salmondx** [comment]
https://github.com/microsoft/WSL/issues/4898

I tried to follow this issue, but my libc version is `2.27-3ubuntu1.4`, not `>=2.30`

**Comment by aeschli** [comment]
Can you check the Process Explorer (`Help > Open Process Explorer`) and scroll to the bottom to the WSL processes? Would eb interesting to see which process is busy.

**Comment by Salmondx** [comment]
Thanks for a response! Looks like process explorer shows that wsl processes doesn't consume any resources:
![image](https://user-images.githubusercontent.com/9963444/110826586-149daa80-824a-11eb-9e02-3d594fa08e3c.png)

But at the same time this is what I see in windows task manager:
![image](https://user-images.githubusercontent.com/9963444/110826682-2da65b80-824a-11eb-96df-f358a6aa567a.png)

And if I open file location of this process, it opens folder with vscode-remote extension:
![image](https://user-images.githubusercontent.com/9963444/110826787-4a429380-824a-11eb-8322-40375b015861.png)

**Comment by telecasterer** [comment]
I have the exact same issue

**Comment by aeschli** [comment]
Can you set `"remote.WSL.fileWatcher.polling": false` and see if the problem goes away?

**Comment by telecasterer** [comment]
> Can you set `"remote.WSL.fileWatcher.polling": false` and see if the problem goes away?

Thanks but that doesn't fix it for me.

**Comment by Salmondx** [comment]
@aeschli tried to disable polling and it helped. So something is broken with file polling in a new vscode release/WSL?

**Comment by Piroro-hs** [comment]
I have the same issue and disabling the polling helped (CPU usage by `node` process 50% -> 1%).

**Comment by aeschli** [comment]
watching by file polling is CPU costly by nature. It's basically scanning the open folder every 5 seconds (Can be configured by `remote.WSL.fileWatcher.pollingInterval`).

But polling is currently the only way to get reliable file events when on a  `/mnt/..`.

**Comment by Salmondx** [comment]
I'm using WSL and vscode-remote extension since it was released, and I never had such problem until recent vscode release. In the exact same environment, without any changes it was working fine until ~week ago.

Maybe they changed a default polling interval or something else?

**Comment by aeschli** [comment]
I have now disabled polling by default. Published ms-vscode-remote.remote-wsl@0.54.5
