### ISSUE TITLE
No more "forwarded port" pannel

### ISSUE THREAD

**Issue by Moulagofre** [microsoft/vscode-remote-release#4642]
Issue Type: <b>Bug</b>

Experienced the suprise today to not have the "forwarded ports" pannel anymore. Some of my ports are correctly forwarded, some not. And, obviously, I can't even manage them.

Extension version: 0.65.1
VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.3.18-lp152.33-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.63GB free)|
|Process Argv|--crash-reporter-id f65706f3-49e5-4355-ba92-064340a751ee|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev.fiction-factory.fr|
|OS|Linux x64 5.3.18-lp152.33-default|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (2 x 2712)|
|Memory (System)|5.87GB (1.44GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by Moulagofre** [comment]
Ok they're back ^^'
![2021-03-10_13h54_42](https://user-images.githubusercontent.com/19334022/110632776-4cecac80-81a8-11eb-8639-9ce1a54357fe.png)

**Comment by Moulagofre** [comment]
Maybe next time it could be a nice thing to notify people. I had to search for it and lost 15min.

**Comment by alexr00** [comment]
> I had to seek it and lost 15min.

@Moulagofre are you referring to how the "Ports" view moved from being in the Remote Explorer in the sidebar to moving to the bottom in the panel? The move was included in our Remote Release notes: https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_54.md#ports-view-table-layout

**Comment by Moulagofre** [comment]
> > I had to seek it and lost 15min.
> 
> @Moulagofre are you referring to how the "Ports" view moved from being in the Remote Explorer in the sidebar to moving to the bottom in the panel? The move was included in our Remote Release notes: https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_54.md#ports-view-table-layout

Yes exactly. Sorry I missed release notes. But what I wanted to say is to notify people of changes directly on vs code. I had to search for those informations inside vs code and on the internet and it's pretty anoying. Isn't it possible to generate a popup window or a message that tells "Hey some things have changed, look release notes here (link)". I don't know, I'm just asking :)

**Comment by alexr00** [comment]
We have the setting `update.showReleaseNotes`, which defaults to `true` so that it's easy to see what has changed. I get what you're saying about showing a notification, but we make so many changes with each release that there would be a lot of notifications if we tried to make one for each change.
