### ISSUE TITLE
Attempting to debug an extension inside a remote container breaks the extension host

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-remote-release#4644]
On the latest Insiders:

1. Try to debug an extension
2. Debugging will not connect, and the extension host for the debugging (parent) window starts reconnecting. Eventually I'm faced with the "reconnect" dialog

Error in the console:

![](https://memes.peet.io/img/21-03-b94705a9-f6ae-4360-9e15-8674c75955a3.png)

**Comment by chrmarti** [comment]
Could you share your configuration and log? (`F1` > `Remote-Containers: Show Log`, devcontainer.json, Dockerfile)

**Comment by connor4312** [comment]
Sure

- Log here: https://memes.peet.io/img/21-03-b7c8430c-f054-4960-af39-201895b8c1db.txt
- Repo here: https://github.com/connor4312/vssaas-2013-repro (just a hello world)
