### ISSUE TITLE
Remote Containers from WSL2: ${localWorkspaceFolder} doesn't match $PWD env variable

### ISSUE THREAD

**Issue by vovimayhem** [microsoft/vscode-remote-release#4647]
Consider the following files:

`docker-compose.yml`:

```yml
version: "3.7"

services:
  demo:
    image: debian:latest
    working_dir: ${PWD}
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:${PWD}
```

`.devcontainer/devcontainer.json`:

```json
{
    "service": "demo",
    "workspaceFolder": "${localWorkspaceFolder}",
    "dockerComposeFile": "../docker-compose.yml"
}
```

If I try to open this folder in a WSL terminal, and launch Code (as suggested in https://github.com/microsoft/vscode-remote-release/issues/4506#issuecomment-783641959), and ask to re-launch as a devcontainer, the launch doesn't complete successfully, as the tree view won't display anything:

<img width="765" alt="Capture1" src="https://user-images.githubusercontent.com/1915931/110705350-e6718980-81bb-11eb-9320-870e5186bdf2.PNG">

If I run `docker-compose exec demo pwd` in a separate terminal, is evident that the extension is somehow not doing what's expected:

<img width="709" alt="Capture2" src="https://user-images.githubusercontent.com/1915931/110705469-0dc85680-81bc-11eb-9e87-2ee8bc3dba23.PNG">

Notice that instead of `/home/someuser/my-demo` (or whatever directory you run the test), the actual directory is `/mnt/c/Users/someuser/AppData/Local/Programs/Microsoft VS Code Insiders`, and that's where the mounted code lies.

Running the same configuration with plain docker compose will work as expected:

<img width="674" alt="Capture3" src="https://user-images.githubusercontent.com/1915931/110706563-af9c7300-81bd-11eb-99e2-5ec2f902b9f0.PNG">

### System Configuration
- VSCode Version: "Visual Studio Code Insiders - Insiders" version 1.55.0-insider (user setup) (5d80c30e5b6ce8b2f5336ed55ad043490b0b818f)
- Local OS Version: Windows 10 (Windows_NT x64 10.0.19041)
- Remote OS Version: Debian
- Remote Extension/Connection Type: Docker

### Steps to Reproduce:

1. Open a WSL2 Terminal (I'm using debian)
2. Clone this repository & change directory to it: `git clone git@github.com:vovimayhem/vscode-remote-release-issue-4647.git demo && cd demo`
3. Open the directory in code: `code .`
4. Choose `Remote Containers: Rebuild and Reopen in container`
5. Observe that the code is never displayed in the tree view.
6. Back on the WSL2 terminal, run: `docker-compose exec demo pwd` and observe that the directory in the container doesn't match with the terminal's.
7. Run `docker-compose run --rm demo pwd` and see what is the expected behavior. 

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Doesn't apply - It's the extension's functionality.

**Comment by vovimayhem** [comment]
FYI, on macOS works as expected.

**Comment by vovimayhem** [comment]
> @chrmarti I need the paths to match, because I'm launching other containers from within the first one (I have the docker client installed in the first container, and sharing the docker socket), and the child containers must have a subfolder within the first container... I can't do that the way I need to if I can't make the paths match.

**Comment by chrmarti** [comment]
Fixed with https://github.com/microsoft/vscode-remote-release/issues/4599. (Not released in a new version yet.)
