### ISSUE TITLE
Current working directory is invalid

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode-remote-release#4652]
Issue Type: <b>Bug</b>

When logging on to a remote Linux host, the login succeeds, but selecting a directory leads to the following error:

```
The terminal process failed to launch: Starting directory (cwd) "xxxxx" does not exist.
```

Extension version: 2021.3.13860
VS Code version: Code - Insiders 1.55.0-insider (9b2ee7fb7d970b9a628fdb3545bdd01d67078d16, 2021-03-11T05:13:39.061Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.4.0-56-generic
Remote OS version: Linux x64 5.4.0-56-generic
Remote OS version: Linux x64 5.4.0-56-generic
Remote OS version: Linux x64 5.8.7

<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
wslfolderdoc:30268769
vscoresta800cf:30265948
vspre833cf:30267465

```

</details>

**Comment by roblourens** [comment]
Do other things work besides the terminal? Or is the window broken? What else do you see?

**Comment by anatolyburakov** [comment]
@roblourens nothing else worked, downgrading to 1.54.0 solved the issue. however, i've updated again just to gather more info for this bug, and this time, everything works. so, no idea what happened, but seems to not be a problem any more.
