### ISSUE TITLE
Create container will timeout while downloading vscode server

### ISSUE THREAD

**Issue by QiFenPocket** [microsoft/vscode-remote-release#4653]
- VSCode Version: 1.54.1 on MacOS, 1.52.1 on Win10
- Local OS Version: MacOS Big Sur 11.2.3, Win10 
- Remote OS Version: Debian 11
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. install remote-containers
2. Open command plate and select Remote-Container: Open folder in container
3. Select Folder, docker-compose.yaml, service name
4. Container build will stuck on Start: Downloading VS Code Server
5. Show Error: connect ETIMEDOUT 101.206.209.250:443 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by yihanlin** [comment]
Encounter this issue too. Not only the container, I also tried to connect to a remote environment via ssh, and same error happened.

**Comment by chrmarti** [comment]
Are you behind a network proxy? (I don't see 101.206.209.250 as a public DNS entry.)

**Comment by QiFenPocket** [comment]
No any network proxy.
I tried 3rd different networking environment (company, home ADSL, mobile LTE)

It's become normal now. 
Maybe it's problem of Taiwan's ISP.

thanks.
