### ISSUE TITLE
Cant join remote session

### ISSUE THREAD

**Issue by samthingswrong** [microsoft/vscode-remote-release#4657]

**Comment by enkia** [comment]
In my case, (macOS Big Sur 11.2.3 using Vscode 1.54.2) Remote-SSH is entirely unresponsive so there is no output to provide other than: 
`[15:08:08.928] Log Level: 2`

None of the below seem to do anything at all:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/255730/111043060-7e66b180-840e-11eb-8fc7-7b5ddeea8ecf.png">

Remote-SSH is responsive again when downgrading to Vscode 1.53.2.

**Comment by enkia** [comment]
I fixed my issue by deleting ~/Application Support/Code and copying back User/settings.json, keybindings.json, snippets.

**Comment by roblourens** [comment]
I'm not sure what happened in your case, but thanks for the follow up.  No response yet from others, will close.
