### ISSUE TITLE
Test Installing Extension Packs

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-release#466]
Testing https://github.com/microsoft/vscode-remote-release/issues/11

- [x] ssh @mjbvz
- [x] dev container @jrieken
- [x] wsl @misolori 

Complexity: 3

Note: An extension can be tagged as ui extension in its package.json or VS Code product.json or by user using `remote.extensionKind` setting. 

Search for an extension pack and install it. If extension pack is tagged as UI extension then it is installed only and completely in local. Otherwise, extension pack is completely installed in remote and if extension pack has any UI extensions, then those UI extensions are also installed locally.

Try installing different kind of extension packs that has all workspace extensions or ui extension or mixed. Eg: PHP Pack, Angular Essentials etc.

**Comment by mjbvz** [comment]
Angular essentials is a good mixed pack to test as it includes themes and language services (although why the `winter is coming` theme is an 'angular essential' is another matter entirely...)
