### ISSUE TITLE
Activating extension 'ms-vscode-remote.remote-ssh' failed: [nullExtensionDescription]

### ISSUE THREAD

**Issue by JeffSolo** [microsoft/vscode-remote-release#4662]
Issue Type: <b>Bug</b>

```
[2021-03-12 12:47:44.754] [exthost] [error] Activating extension ms-vscode-remote.remote-ssh failed due to an error:
[2021-03-12 12:47:44.758] [exthost] [error] Error: [nullExtensionDescription]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api nullExtensionDescription
```

Remote-SSH stopped working on my Early 2015 MacBook Pro, after no known system or VSCode updates/changes.

Remote-SSH extension fails to load, so trying to execute any commands results in`command 'opensshremotes.*' not found`. 

These errors only display when trying to run Remote-SSH commands from command palette. Clicking the `Add New`, `Configure`, or `Refresh` buttons next to "SSH Targets" in the side panel simply do not respond after click,  nor log any errors. 

Installing older versions of Remote-SSH produced the same error, as does installation in VSCode Insiders. 

I tried a complete delete and reinstall, including the removal of these files and folders:
```
 ~/Library/Preferences/com.microsoft.VSCode.helper.plist 
~/Library/Preferences/com.microsoft.VSCode.plist 
~/Library/Caches/com.microsoft.VSCode
~/Library/Caches/com.microsoft.VSCode.ShipIt/
~/Library/Application\ Support/Code/
~/Library/Saved\ Application\ State/com.microsoft.VSCode.savedState/
~/.vscode/
```
With Remote-SSH as the only installed extension on a clean VSCode installation produced the same error. 
Running  with `--enable-proposed-api ms-vscode-remote.remote-ssh` did not work.

The extension does, however, work fine on a fresh install when logged in as a different user.

Similar closed issues:
#4293
#3473
#2601

Extension version: 0.65.1
VS Code version: Code 1.54.2 (Universal) (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:09.783Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 5, 11|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id fbe036cc-6160-4389-a95d-69e5e2a98573|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
dockersubset:30270708
vspre833:30267464
vsdfh931:30275552

```

</details>

**Comment by roblourens** [comment]
Is this an official vscode build installed from our website?

Are you using any other extensions and do they work?

**Comment by JeffSolo** [comment]
Yes, both the VSCode and Insiders builds were downloaded and installed directly from the official website. 
I also tried builds installed via Homebrew. 
All other extensions work without error.

**Comment by roblourens** [comment]
What does this `nullExtensionDescription` imply @sandy081?

**Comment by JeffSolo** [comment]
It started functioning properly again today after I worked on a completely unrelated task. 

I made a time machine backup (at a point where Remote-SSH was already giving this error), and after some unrelated failed work, reverted my entire user home folder to the original time point. 

Although the backup was made after Remote-SSH had stopped functioning, this appears to have fixed it somehow.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/118812
