### ISSUE TITLE
Empty mount point in VScode in Remote: WSL

### ISSUE THREAD

**Issue by jeffguorg** [microsoft/vscode-remote-release#4668]
Issue Type: <b>Bug</b>

Hi, this is Jeff using Windows Insider build 31223 with wsl2 and mount options.

I found that VSCode WSL server will not list files in mount points. It only shows files in WSL root partition.

Reproduction:
- follow every exact step to manually setup wsl2 with ubuntu 20.04(unable to login to microsoft account, so i manually install wsl, windows terminal and ubuntu): https://docs.microsoft.com/zh-cn/windows/wsl/install-win10
- mount drive as described in: https://devblogs.microsoft.com/commandline/access-linux-filesystems-in-windows-and-wsl-2
  - set my drive offline in disk management
  - wsl --mount <DRIVE> --bare
  - mount partition in WSL. there are files in mount point
- connect to wsl in VSCode
- open directory in VSCode. but the mount point is empty. it only list names in wsl partition.

Extension version: 0.54.3
VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.21332
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Fetching remote diagnostics for 'SSH' failed: Connecting was canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (24.86GB free)|
|Process Argv|--crash-reporter-id 2ab02298-6f0c-445b-8ea4-7449d82d2632|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|Memory (System)|23.48GB (22.26GB free)|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: Connecting was canceled
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
vspre833cf:30267465
vsdfh931:30275552

```

</details>

**Comment by jeffguorg** [comment]
And I tried to mount the partition not in wsl, but directly with `wsl --mount <DRIVE> --partition 1`. this time the mount point works in VSCode.

Why?

**Comment by alexr00** [comment]
@jeffguorg can you share a screen shot of what you're seeing in VS Code?
