### ISSUE TITLE
terminal display abnormal.

### ISSUE THREAD

**Issue by zx06** [microsoft/vscode-remote-release#467]
Issue Type: <b>Bug</b>

terminal display abnormal in wsl.
![image](https://user-images.githubusercontent.com/12474586/58470413-395b8780-8174-11e9-91f2-deeb288c47ec.png)

Extension version: 0.36.0
VS Code version: Code - Insiders 1.35.0-insider (84deb302d7e9ea991a1d0edfd4b4261143f659ff, 2019-05-28T07:56:45.055Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|        Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3101)|
|Memory (System)|7.88GB (0.75GB free)|
|VM|0%|
</details>

**Comment by AlexandreOuellet** [comment]
I seem to be having a very similar issue too

![image](https://user-images.githubusercontent.com/5200252/58481814-296b8580-812b-11e9-9415-ad11356f494a.png)

Extensions:
Remote - containers : 0.55.0
Remote - Development: 0.14.0

Version: 1.35.0-insider (user setup)
Commit: 84deb302d7e9ea991a1d0edfd4b4261143f659ff
Date: 2019-05-28T07:56:45.055Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/74183

Please share your settings.json/platform over on that issue
