### ISSUE TITLE
Activating extension ms-vscode-remote.remote-containers failed due to an error (printenv failed)

### ISSUE THREAD

**Issue by CherryDT** [microsoft/vscode-remote-release#4674]
Issue Type: <b>Bug</b>

After the last update, no extensions are working in my WSL projects, and I can see this error in the extension host output:

```
[2021-03-13 17:49:19.811] [exthost] [error] Activating extension ms-vscode-remote.remote-containers failed due to an error:
[2021-03-13 17:49:19.811] [exthost] [error] {"message":"Command failed: printenv ","stdout":{"type":"Buffer","data":[69,0,115,0,32,0,103,0,105,0,98,0,116,0,32,0,107,0,101,0,105,0,110,0,101,0,32,0,86,0,101,0,114,0,116,0,101,0,105,0,108,0,117,0,110,0,103,0,32,0,109,0,105,0,116,0,32,0,100,0,101,0,109,0,32,0,97,0,110,0,103,0,101,0,103,0,101,0,98,0,101,0,110,0,101,0,110,0,32,0,78,0,97,0,109,0,101,0,110,0,46,0,13,0,13,0,10,0]},"stderr":{"type":"Buffer","data":[]},"code":4294967295}
```

Turning this buffer content into a string gives:
```
'Es gibt keine Verteilung mit dem angegebenen Namen.\r\r\n'
```

Literally this would translate to "There is no distribution with the given name." (although "Verteilung" is a very awkward translation here, I'm assuming it's supposed to mean Linux distributions? That shouldn't be translated at all then.)

I know that technically each "remote" mode is an extension but I'm filing this here because it seems something goes wrong before that even, because a WSL project shouldn't be using the "container" remote thingy (it should use WSL), right?

VS Code version: Code - Insiders 1.55.0-insider (04770364fdc1bebeca9d1a257df2cacce06b35d6, 2021-03-05T15:40:03.281Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.4.0-19041-Microsoft
Remote OS version: Linux x64 4.4.0-19041-Microsoft

**EDIT:** Just realized this verison isn't up to date despite updating today, I checked again and got another update, but it's the same problem there. New version is:
Version: 1.55.0-insider (system setup)  
Commit: 06b54543d660353a04cdab6554d1f27266a537fd  
Date: 2021-03-12T05:15:35.786Z  
Electron: 11.3.0  
Chrome: 87.0.4280.141  
Node.js: 12.18.3  
V8: 8.7.220.31-electron.0  
OS: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (3.00GB free)|
|Process Argv|--crash-reporter-id c6356cfd-7a7a-4cee-93f1-a6019521c8bb|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.86GB (3.00GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.86GB (3.00GB free)|
|VM|0%|
</details><details><summary>Extensions (87)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
Doxygen|bbe|1.0.0
vscode-standardjs-snippets|cap|0.8.15
LogFileHighlighter|emi|2.11.0
vscode-svelte-snippets|fiv|0.5.0
vscode-cloak|joh|0.3.0
Lua|key|0.0.9
vscode-nsis|Kry|0.0.1
VBScript|lug|0.0.2
dotenv|mik|1.0.1
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-ssh-explorer|ms-|0.56.0
remote-wsl|ms-|0.54.3
ejs-language-support|Qas|0.0.1
vscode-autohotkey|sle|0.2.2
rewrap|stk|1.14.0
vscode-todo-highlight|way|1.0.4
rebound-delete|aar|1.1.0
paste-fixer|aar|1.0.0
vscode-color|ans|0.4.5
svelte-intellisense|ard|0.7.1
vscode-intelephense-client|bme|1.6.3
htmltagwrap|bra|0.0.7
vscode-standardjs|che|1.4.0
npm-intellisense|chr|1.3.1
bracket-select|chu|2.0.2
gitignore|cod|0.6.0
compulim-vscode-closetag|Com|1.2.0
insert-use-strict|cri|1.0.2
jshint|dba|0.11.0
vscode-eslint|dba|2.1.17
vscode-new-file|dku|4.0.2
vscode-npm-source|dku|1.0.0
xml|Dot|2.5.1
gitlens|eam|11.3.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.17
crystal-lang|fau|0.4.0
flow-for-vscode|flo|1.5.0
kaitai-struct-vscode|fud|0.7.0
gc-excelviewer|Gra|3.0.41
rest-client|hum|0.24.4
RelativePath|jak|1.4.0
hungry-delete|jas|1.6.0
join-comment-aware|joh|0.0.3
typings-autoinstaller|jvi|1.2.0
nodejs-repl|los|0.5.15
edge|luo|0.3.2
twig-language-2|mbl|0.9.2
rainbow-csv|mec|1.8.1
ecdc|mit|1.4.0
find-jump|mks|1.2.4
prettify-json|moh|0.0.3
vscode-azureresourcegroups|ms-|0.3.0
vscode-cosmosdb|ms-|0.16.0
python|ms-|2021.2.636928669
jupyter|ms-|2021.4.641214696
azure-account|ms-|0.9.7
cpptools|ms-|1.2.2
powershell|ms-|2021.2.2
node-modules-resolve|nau|1.0.2
prettier-standard-vscode|num|0.8.1
svelte-extractor|pro|0.0.3
quicktype|qui|12.0.46
java|red|0.76.0
vscode-yaml|red|0.16.0
json-organizer|rin|0.0.4
LiveServer|rit|5.6.1
ActiveFileInStatusBar|Ros|1.0.3
vscode-paste-and-indent|Rub|0.0.8
bracket-jumper|sas|1.1.8
trailing-spaces|sha|0.3.1
rewrap|stk|1.14.0
ignore-gitignore|stu|1.0.1
svelte-vscode|sve|104.6.4
sort-lines|Tyr|1.9.0
use-strict-everywhere|vee|0.1.3
bracket-padder|via|0.3.0
codetour|vsl|0.0.46
gitdoc|vsl|0.0.7
quokka-vscode|Wal|1.0.349
change-case|wma|1.0.0
join-lines|wma|0.2.2
FilterText|yhi|0.0.15
html-css-class-completion|Zig|1.20.0

</details>

**Comment by CherryDT** [comment]
```
[7 ms] Remote-Containers 0.164.1 in VS Code 1.55.0-insider (06b54543d660353a04cdab6554d1f27266a537fd).
[27 ms] Start: Run: wsl -d default
[325 ms] Es gibt keine Verteilung mit dem angegebenen Namen.

[326 ms] 
[326 ms] Exit code 4294967295
[326 ms] Start: Run: wsl -d default -e /bin/sh -c cd '/mnt/c/Users/david/proj/***' && printenv
[640 ms] Es gibt keine Verteilung mit dem angegebenen Namen.

[640 ms] 
[640 ms] Exit code 4294967295
```

...which now makes me wonder if this broke maybe not due to the VSCode update as I thought but maybe due to a _Windows_ update...?

I'm using WSL1 exclusively, and `wsl -l` prints:

```
Z:\>wsl -l
Windows-Subsystem für Linux-Distributionen:
Legacy (Standard)

```

Maybe `wsl -d default` stopped working in the last Windows update...?

After I reopened the workspace from scratch instead of opening it from the recent projects list, the log shows it's using `wsl -d Legacy` instead of `wsl -d default` and then it works.

**Comment by chrmarti** [comment]
@aeschli Do you know if there was any automated renaming of WSL1 distros with a recent Windows update? Was `default` as the distro name at some point supported to fall back to the default distro?

**Comment by aeschli** [comment]
`wsl -d default` is new to me, don't think that was supported unless you have a distro of that name, which I've never come across.

In the WSL extension we have the remote authority `wsl+default` that will open the current default distro. It is/was only used when the remote WSL extension runs on old Window builds before Windows 10, May 2019 Update, version 1903.

**Comment by CherryDT** [comment]
That is interesting. I can see that the weird MRU workspaces which are now broken are set to `wsl+default` as you said, although most of them were first opened (or even created) only recently, and I don't think I was on 1903 that long... but regardless, I guess it shouldn't break in this not-so-obvious way when opening them now, should it?

**Comment by aeschli** [comment]
`wsl+default` is still supported and works in Remote WSL, we're just avoid creating such URIs >= 1903, but rather resolve the name of the default ditro.
If opening a `wsl+default` URI is broken, I want to look into it. Can you describe the steps based on Remote+WSL commands?

How is Remote Containers involved here? Is doing anything with `wsl+xyz` URIs?

**Comment by chrmarti** [comment]
The only error we are looking at is from Remote-Containers if I'm not mistaken. It looks like Remote-Containers might have picked up 'default' from one of these older WSL URIs.

**Comment by CherryDT** [comment]
> Can you describe the steps based on Remote+WSL commands?

I'm not sure what you mean - my steps were using "new window: wsl", "add new folder to project" and "save workspace" a few days or weeks ago, and simply picking the workspaces from the MRU list today.

**Comment by chrmarti** [comment]
This should be fixed since. Closing, thanks.
