### ISSUE TITLE
Always have to log in twice

### ISSUE THREAD

**Issue by TravisLlado** [microsoft/vscode-remote-release#4679]
Issue Type: <b>Bug</b>

Whenever I step away from my computer and my computer display turns off, VSCode disconnects from the remote computer. When I wake my computer back up, the remote computer login prompt is instantly displayed, requesting my password. 100% of the time, I enter the password, wait a few seconds, and VSCode says it could not connect and asks for my password a second time, and on the second attempt it logs in correctly.

Extension version: 0.65.1
VS Code version: Code - Insiders 1.55.0-insider (892a1083cb2b9b3987ff7edc85376b5d9764433d, 2021-03-16T05:11:50.271Z)
OS version: Darwin x64 20.3.0
Remote OS version: Linux x64 4.4.0-31-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.71GB free)|
|Process Argv|--crash-reporter-id 59b5e7e7-e7ff-454f-9611-dce47e33f26c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.67.10.21|
|OS|Linux x64 4.4.0-31-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 1499)|
|Memory (System)|62.85GB (18.13GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
vscoresta800:30265947
vsc_aa:30263845
vspre833cf:30267465
vsfjg287:30275553

```

</details>

**Comment by roblourens** [comment]
Could you share the log from the Remote-SSH output channel when this happens? Likely ssh or some piece of the auth flow has timed out, and it's not necessarily possible for me to know when that happens.
