### ISSUE TITLE
Test WSL: Support shells other than bash

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#469]
- [x] anyOS @sbatten 
- [x] anyOS @chrmarti

Complexity: 3

There were various issues filed by users that want `tmux`, `zsh` or `fish` as their default shell.
WSL now starts the server using the configured default shell. Each shell has it's own profile scripts.

- change your default shell to `tmux`, `zsh` or `fish`. Open a WSL shell and enter
`chsh -s $(which tmux) $USER.`
- close and open the shell and verify that the shell is used
- open a WSL window. Check that the window opens . Check the WSL log that the shell is used.
- verify that the shells interactive login shell script(s) are invoked. See http://hyperpolyglot.org/unix-shells#startup-file

**Comment by sbatten** [comment]
tested with fish and zsh

**Comment by pwwang** [comment]
Not passed if I have `/path/to/fish --login` at the end of `~/.profile` instead of using `chsh /path/to/fish`, in case I don't have elevated privilege.
