### ISSUE TITLE
Can't choose Python interpreter from menu

### ISSUE THREAD

**Issue by grandrew** [microsoft/vscode-remote-release#4691]
- VSCode Version:
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:24.277Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
- Local OS Version:
OS: Linux x64 5.4.0-66-generic snap
- Remote OS Version:
(local)
- Remote Extension/Connection Type: NONE

Steps to Reproduce:

1. Click on "Select Python Interpreter" at the bottom
2. Click on desired interpreter from menu pop-up in the top
3. Nothing happens. No logs in console, the action is completely ignored.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

I would appreciate any help with debugging this issue as I do not know where to start looking.

**Comment by bamurtaugh** [comment]
> Does this issue occur when you try this locally?: Yes

Just to clarify - are you unable to select a Python interpreter even in local VS Code sessions not connected to a remote SSH box?

**Comment by grandrew** [comment]
It is not SSH box, issue is local. This may be related to https://github.com/microsoft/vscode-python/issues/3535

Figured out that this happens on some of my files. When I focus the editor on a specific .py file that I want to run, interpreter suddenly disappears and becomes unselectable

**Comment by bamurtaugh** [comment]
Thanks for the additional info. Sounds like it could be the issue you linked, and that closing this issue is appropriate as it isn't on the Remote-SSH side but rather local.
