### ISSUE TITLE
Integrated Terminal of VSCode can not see environment variables (defined in Dockerfile) when using remote-ssh to access container in docker

### ISSUE THREAD

**Issue by ciaochiaociao** [microsoft/vscode-remote-release#4695]
- VS Code Version: 1.54.3
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. `docker pull nvcr.io/nvidia/pytorch:19.05-py3` 
2. `docker run -it -p 2222:22 --runtime nvidia nvcr.io/nvidia/pytorch:19.05-py3 bash`
3. Inside the container `apt update; apt install -y openssh-server; service ssh start; useradd docker`
4. `echo ${_CUDA_COMPAT_PATH}` (/usr/local/cuda/compat)
5. In VSCode remote ssh to that container (`ssh -p 2222 docker@localhost`)
6. Open the terminal inside VSCode and `echo ${_CUDA_COMPAT_PATH}` (None)
7. But if I use Windows Terminal, it can correctly echo the variable

**Comment by roblourens** [comment]
When I run the first command, I get `invalid reference format`. Not a Docker expert, do you know if I need to set something else up first?

Or do you know how it sets the environment variable, so I can replicate it in a simpler environment?

**Comment by ciaochiaociao** [comment]
My apology: it should be `docker pull nvcr.io/nvidia/pytorch:19.05-py3`

**Comment by roblourens** [comment]
I don't have the "nvidia runtime" set up and don't really want to figure that out for this issue. If you know more about how the environment variable is set up I can try it in a simpler environment.

> But if I use Windows Terminal, it can correctly echo the variable

Meaning if you ssh into it from a terminal?
