### ISSUE TITLE
Show 'Checkout Pull Request in Dev Container' only if Dev Container configured for repo

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-remote-release#4697]
user assumed that there will be a Dev Container set up for him given this open in the drop down so only show the option if there is a devcontainer file

![image](https://user-images.githubusercontent.com/12758612/111699483-708da380-87f5-11eb-8f3f-e5e506cea65d.png)

**Comment by chrmarti** [comment]
If there is no devcontainer.json the user is asked to pick a predefined configuration from a list during startup of the dev container session.

**Comment by tanhakabir** [comment]
Hmm my hunch is then this should be a fine experience; I'll reopen if I see more feedback against this
