### ISSUE TITLE
Debug console is not showing log statements

### ISSUE THREAD

**Issue by jorenbroekema** [microsoft/vscode-remote-release#4699]
- VSCode Version: 1.54
- Local OS Version: Windows 10 Home, 10.0.19041 Build 19041
- Remote OS Version: Ubuntu 20.04.1 LTS
- Remote Extension/Connection Type: WSL --> v0.54.6

Steps to Reproduce:

1. Follow https://code.visualstudio.com/api/get-started/your-first-extension
2. Open your new scaffolded extension with VS Code in WSL2
3. Go to extensions and disable all extensions, then enable Remote - WSL extension and reload. This is to show the issue is not caused by other extensions.
4. F5
5. Open Debug Console and not that there's no log: `Congratulations, your extension "bar-extension" is now active!` even though there's a console log statement in extension.ts `console.log('Congratulations, your extension "bar-extension" is now active!');` 

Does this issue occur when you try this locally?: No, it works fine (the console log) when I run the same steps on Windows 10 local OS even with all my extensions enabled.
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
Thanks for reporting @jorenbroekema. I just tried running an extension in WSL2, and while it loaded properly:

![image](https://user-images.githubusercontent.com/25310137/112397462-5f460a80-8cbf-11eb-8e82-0441d4db8e77.png)

I experienced the following error message in the previous window:

![image](https://user-images.githubusercontent.com/25310137/112397515-784ebb80-8cbf-11eb-9b69-2f488ec8e283.png)

Is this what you saw?

**Comment by jorenbroekema** [comment]
Hmmm no I got no such error on the window from where I launched.

**Comment by bamurtaugh** [comment]
cc @aeschli if you have any thoughts? @jorenbroekema mentions in another thread:

> I tried running this on Windows 10 with all extensions disabled. Console log works there.
> 
> However, I work in WSL2, so doing --disable-extensions won't work because you need the Remote - WSL extension. So instead, I went to extensions and clicked "Disable all extensions", then re-enabled Remote - WSL and reloaded the editor. Then, my console log does not show in my debug console.
> 
> So the cause of this problem may be related to Remote - WSL extension.

**Comment by aeschli** [comment]
I can reproduce in 1.54.3, but not in the latest 1.55 (coming out any of these days)

**Comment by jorenbroekema** [comment]
Can confirm it is fixed for me in 1.55 👍
