### ISSUE TITLE
ssh-copy-id doesn't work for Window host

### ISSUE THREAD

**Issue by teristam** [Microsoft/vscode-remote-release#47]
Hi,

I am following the instruction at https://code.visualstudio.com/docs/remote/troubleshooting#_ssh-tips to work with a Mac client and Windows 10 host.

I have generate the public key on the Mac successfully, but when I try to use `ssh-copy-id` to upload the file to remote Window host, I encounter the following error:
```
'exec' is not recognized as an internal or external command,
operable program or batch file.
'cat' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
```
May I ask is any other way to upload the key file to the remote host? Thank you!

**Comment by Tyriar** [comment]
/duplicate https://github.com/Microsoft/vscode-remote-release/issues/25
