### ISSUE TITLE
Contribute SSH terminal from remote ssh

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-remote-release#4700]
Thought of something that might be useful. Fluent Terminal (among others) allow launching tabs with remote connections:

![image](https://user-images.githubusercontent.com/2193314/111779071-e71cb680-8872-11eb-981a-bb953c423192.png)
![image](https://user-images.githubusercontent.com/2193314/111779129-f865c300-8872-11eb-9953-2958dcc2a894.png)

Because of work done for js debug, the ssh extension could contribute a terminal similar to the js debug terminal when it's present.

![image](https://user-images.githubusercontent.com/2193314/111779311-382caa80-8873-11eb-8e76-7b41e8f02d9e.png)

This could be as easy as launching some command that triggers a quick pick which just creates a terminal using ssh/args.

**Comment by roblourens** [comment]
So it would just start an ssh terminal in a local window? I wouldn't add this to Remote-SSH because I think it would cause confusion with what Remote-SSH is. It could be useful in another extension though.

**Comment by Tyriar** [comment]
But it would only be visible in the new terminal dropdown? I'd add it to core but don't want to bring parsing of the SSH config there.

I see remote - SSH as making working with SSH easier, remote connected windows are part of that and it seems like a quick win to also allow launching remote terminals convenient.

Another extension could work but then hardly anyone would use it.

**Comment by Tyriar** [comment]
@roblourens in case you unsubscribed

**Comment by roblourens** [comment]
Kinda funny, I just closed this exact request in https://github.com/microsoft/vscode/issues/119273

It's still weird to me because using the SSH resolver and using this feature would be mutually exclusive. I see it as a remote resolver extension, not a "anything related to SSH" extension. We use a library for ssh config parsing, it would be easy for another extension to set it up.

**Comment by Tyriar** [comment]
> It's still weird to me because using the SSH resolver and using this feature would be mutually exclusive.

I wouldn't think so, force a local terminal each time and allow sshing into an arbitrary machine regardless of whether the window has an active docker, SSH or wsl connection. I wouldn't think it would matter what type of connection the window is using since the user still may want to do that.

I could make a separate extension but would prefer not to because:

- This is not public api, I'm not sure if it uses the proposed check currently, but if it doesn't if should.
- If users want SSH integration they'll reach for remote SSH already.
- It's likely a tiny piece of code if added to remote SSH.

I think the other issue validates that it's a useful idea and place to put it. Again, this would go in core ideally but would prefer not to bring in the SSH parsing lib.

**Comment by roblourens** [comment]
What's the extension API? Would like to try it

**Comment by Tyriar** [comment]
Here's js-debug's usage: https://github.com/microsoft/vscode-js-debug/blob/6fb3beafeab14f52a78fb84e8575b4ea0ee4ccec/package.json#L204-L211

I checked and it is indeed protected by a proposed API check.

**Comment by Tyriar** [comment]
After we bring in icons, this would be able to use custom icons as well which will help differentiate them from other terminals in the current remote. We have the `globe` icon which would work nicely here.

**Comment by Tyriar** [comment]
Apparently the shortcut for connect to remote computer on PowerShell ISE is ctrl+shift+r https://github.com/microsoft/vscode/issues/10546#issuecomment-434460930

Also the profiles contribution API will be stabilized in June, the PR for the final changes to the API was just merged https://github.com/microsoft/vscode/issues/120369

**Comment by roblourens** [comment]
Would rather see another extension do this, but it would be fairly easy using the `ssh-config` npm module

**Comment by shishiata55-del** [comment]
Meet
