### ISSUE TITLE
Pageant ignored

### ISSUE THREAD

**Issue by AdamReece-WebBox** [microsoft/vscode-remote-release#4702]
Issue Type: <b>Bug</b>

I have an SSH key pageant running of which works fine for every application so far, apart from VS Code.

When I use the SSH feature in VS Code it keeps prompting me to login with a password, which is not what should be happening. The key mounted in pageant is just ignored. I've tried this on different Windows hosts, none of which work as expected.

I'm not seeing a setting in the extension to use a pageant or socket path to one. Is this just unsupported? (I thought that VS Code uses OpenSSH for its SSH client, so should be supported.) I've found a few garbled and dated answers elsewhere about but none seem to be relevant.

Extension version: 0.65.1
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.67GB (2.93GB free)|
|Process Argv|--crash-reporter-id 97515f76-23b6-4f93-b0e4-d8df3e77a934|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'ssh-remote+adam.dev' timed out.
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
vscoresta800cf:30276762
vspre833cf:30267465
vsfjg287:30275553
vshan820cf:30276953

```

</details>

**Comment by roblourens** [comment]
How does OpenSSH talk to Pageant? Essentially vscode is just running a command with `ssh` and if things are configured correctly, it will work same as it does for you in an external terminal.

**Comment by AdamReece-WebBox** [comment]
Good question.

The pageant I'm using is [KeeAgent for KeePass](https://lechnology.com/software/keeagent/). This has the option to write out socket files for compatibility with Cygwin (MSYS) and msysGit, though I've not needed to do that.

- OpenSSH for Windows "OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5" appears to not pick up an agent at all.
- OpenSSH within Cygwin uses its own pageant bridge binary "ssh-pageant", which in turn keeps a bridging socket at virtual path "/tmp/.ssh-pageant-${USERNAME}", but I've not had to point that to anywhere specific. ("ssh-pageant" picks up KeeAgent without further configuration.)
- FileZilla and PuTTy "just works" (TM), I've not had to point them to a specific socket.
- TortoiseGIT doesn't need a specific socket, it just needs to use "TortoiseGitPlink.exe" that is supplied with it.

Using OpenSSH for Windows in very very verbose mode it doesn't appear to see that any agent exists:

```
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: C:\\Users\\Adam Reece/.ssh/id_rsa
debug3: no such identity: C:\\Users\\Adam Reece/.ssh/id_rsa: No such file or directory
debug1: Trying private key: C:\\Users\\Adam Reece/.ssh/id_dsa
debug3: no such identity: C:\\Users\\Adam Reece/.ssh/id_dsa: No such file or directory
debug1: Trying private key: C:\\Users\\Adam Reece/.ssh/id_ecdsa
debug3: no such identity: C:\\Users\\Adam Reece/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: C:\\Users\\Adam Reece/.ssh/id_ed25519
debug3: no such identity: C:\\Users\\Adam Reece/.ssh/id_ed25519: No such file or directory
debug1: Trying private key: C:\\Users\\Adam Reece/.ssh/id_xmss
debug3: no such identity: C:\\Users\\Adam Reece/.ssh/id_xmss: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
```

OpenSSH within Cygwin however succeeds:

```
debug1: Next authentication method: publickey
debug1: Offering public key: adam.reece@example.co.uk.id_rsa_aes RSA SHA256:OLGl/c4xZXslVusmTbiQMW5FJjShGDlFRtuU/DXk7Io agent
debug1: Server accepts key: adam.reece@example.co.uk.id_rsa_aes RSA SHA256:OLGl/c4xZXslVusmTbiQMW5FJjShGDlFRtuU/DXk7Io agent
debug1: Authentication succeeded (publickey).
```

PuTTY also succeeds:

```
Authenticating with public key "adam.reece@example.co.uk.id_rsa_aes" from agent
```

**Comment by AdamReece-WebBox** [comment]
I noticed in KeeAgent's settings that there is necessity for special behaviour when working with Windows' distribution of OpenSSH:

![image](https://user-images.githubusercontent.com/16222407/111821620-c720dd80-88da-11eb-97a5-fe3ceb0bfe04.png)

Looks like for this to work the "OpenSSH Authentication Agent" [ssh-agent] service needs to be stopped and disabled. After turning off that service and enabling that KeeAgent option OpenSSH for Windows seems to use pageant fine. Consequently VSCode also works fine.

Thanks for the investigatory direction. :)

**Comment by roblourens** [comment]
Cool, thanks for following up :)
