### ISSUE TITLE
Why every time repeating password after file edit?

### ISSUE THREAD

**Issue by JoiHan** [microsoft/vscode-remote-release#4704]
Hello,

I have set no password for each login, but no idea to set no password when update file after each code edit.

**Comment by bamurtaugh** [comment]
Hi @JoiHan, I want to make sure I understand what you're experiencing here. 

> I have set no password for each login

Have you set up key based authentication: https://code.visualstudio.com/docs/remote/troubleshooting#_configuring-key-based-authentication, and now you're facing trouble with it?
