### ISSUE TITLE
failed to connect to the remote extension host server(Error:Handler already set)

### ISSUE THREAD

**Issue by DIVE128** [microsoft/vscode-remote-release#4705]
the vs code print(failed to connect to the remote extension host server(Error:Handler already set))

**Comment by roblourens** [comment]
Please include the log from the Remote-SSH output channel

**Comment by DIVE128** [comment]
There is not any information in the Remote-SSH output channel. After uninstalling vscode,deleting cache information and extension folder,and then installing vs code again, the issue is fixed.

**Comment by bamurtaugh** [comment]
Thanks for the update @DIVE128. If you experience any trouble in the future, please let us know!
