### ISSUE TITLE
SSH_AUTH_SOCK is not updated when it should

### ISSUE THREAD

**Issue by lozhn** [microsoft/vscode-remote-release#4709]
Issue Type: <b>Bug</b>

In the output of the extension is it said that 

```
[14:28:42.235] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-BaJW5V7Agv/agent.16810" "/tmp/vscode-ssh-auth-sock-852156072"
```

Which means the `$SSH_AUTH_SOCK` needs to be updated

But for some reason this env var happend to be `/tmp/ssh-seIkLSg1wZ/agent.448` - this file doesn't exist so I couldn't ssh to github etc.

I'm almost sure that the problem arose after I added "dynamic port forwarding" via VSCode (it's when VSCode asks "do you want me to forward this port?")

Because when this dynamic port forwarding was enabled, the `$SSH_AUTH_SOCK` was empty. 

So when I manually exec `export SSH_AUTH_SOCK=<filepath from the extensions log>` ssh started to work again 

Extension version: 0.65.1
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.3.0
Remote OS version: Linux x64 5.8.0-41-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 702a56cc-5231-418d-a772-a990d9695282|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: <REDACTED>|
|OS|Linux x64 5.8.0-41-generic|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 2174)|
|Memory (System)|31.36GB (2.76GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
vscoresta800cf:30276762
vspre833:30267464
vsfjg287:30275553
vshan820:30276952

```

</details>

**Comment by bamurtaugh** [comment]
@alexr00 Can you think of anything with dynamic port forwarding that would cause this behavior?

**Comment by alexr00** [comment]
Port forwarding doesn't know about ` $SSH_AUTH_SOCK`. Maybe @roblourens knows more?

**Comment by roblourens** [comment]
Please share the full log. Also do you have `terminal.integrated.inheritEnv` set?

**Comment by lozhn** [comment]
What is full log? Is it aggregated by the VSCode somewhere, or this is just the output in the "Output > Remote" tabs?

**Comment by lozhn** [comment]
Couldn't reproduce on a clean ubuntu 20.04 bash. If the problem will appear again I'll try to record all the steps to reproduce and report in here

**Comment by roblourens** [comment]
Thanks, and yes that output channel is the log that I am looking for
