### ISSUE TITLE
portsAttributes are used but not documented

### ISSUE THREAD

**Issue by davidstrauss** [microsoft/vscode-remote-release#4711]
I see that support was added recently with #4445, but the directive isn't [documented in the expected place](https://code.visualstudio.com/docs/remote/devcontainerjson-reference). It would be helpful to get an official description of how it functions.

**Comment by bamurtaugh** [comment]
Thanks for the feedback @davidstrauss. In the meantime, they have been added to the [Remote-Try-* samples](https://github.com/search?q=org%3Amicrosoft+vscode-remote-try-&type=Repositories) dev container definitions and READMEs (i.e. [Remote Try Python dev container sample](https://github.com/microsoft/vscode-remote-try-python/blob/master/.devcontainer/devcontainer.json)) if you'd like a point of reference. But I'd also expect to find them in the devcontainer.json docs reference.
