### ISSUE TITLE
FR: Download dialog box be opened in the last folder used

### ISSUE THREAD

**Issue by Jackiexiao** [microsoft/vscode-remote-release#4712]
agree with @tcalmant  , download dialog box should be opened in the last folder we used

**Comment by bamurtaugh** [comment]
@Jackiexiao To clarify - which extension would this download folder setting be targeting? And would it be for anything downloaded while working remotely, or something specific?

**Comment by Jackiexiao** [comment]
![image](https://user-images.githubusercontent.com/18050469/112086531-5a9e2b00-8bc7-11eb-81e2-c7edfef9ce36.png)

@bamurtaugh

**Comment by tcalmant** [comment]
+1 even though I'd like the download dialog box be opened in the last folder we used (to allow a faster re-download of the same bunch of files)
