### ISSUE TITLE
Trouble with attaching vscode to a container on remote

### ISSUE THREAD

**Issue by hithisisdhara** [microsoft/vscode-remote-release#4717]
I have docker images on a remote server. (dhara-dev as well as a school server). Docker is locally installed on the server. In order to connect to the server, I have the vs-code remote app installed on my local (mac). Also, to run the vs-code docker remotely I have the vs-code docker app installed on the remote. Now, when I start the vs-code docker app in remote after connecting to remote, I do see the containers, and if they are running, I am able to attach the shell (from vs-code docker app, right-click and click "attach Shell"). but can't attach the "attach Visual Studio Code" option. I get the following error when I try. How should I address this issue? 
<img width="471" alt="Screen Shot 2021-03-20 at 12 42 49 PM" src="https://user-images.githubusercontent.com/5340975/111877442-cdb26200-8979-11eb-8e41-4bdcfbd8db9a.png">

**Comment by bwateratmsft** [comment]
Transferring this over to microsoft/vscode-remote-release since the Attach VS Code feature is from the Remote - Containers extension.
