### ISSUE TITLE
Test Ports view label polish

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#4718]
Refs: https://github.com/microsoft/vscode-remote-release/issues/4624 https://github.com/microsoft/vscode/issues/117573

- [x] macOS @tanhakabir
- [x] linux @isidorn
- [x] windows @meganrogge

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%234718%0A%0A)

---

1. Connect to a remote. Anything other than WSL is good for testing.
2. Open the Ports view. Forward a port if you don't have any already forwarded.
3. Verify that there is at most one "set label" related command in the context menu of any port.
4. Verify that there is an inline action to set the label of a port.
5. Verify that you can double click on a port to set the label.

**Comment by isidorn** [comment]
On linux I can also double click to set a port label.
Also on context menu I do not have any Set Label action. But since 0 is up to 1 I did not file an issue.
I think this is all fine, but just let me know if I should file an issue for either of these.

Anyways works nicely!

**Comment by alexr00** [comment]
All that is good. Thanks for testing!
