### ISSUE TITLE
Test additional portsAttributes

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#4719]
Refs: https://github.com/microsoft/vscode-remote-release/issues/4623

- [x] macOS @rebornix
- [x] linux @isidorn 
- [x] windows @rzhao271

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%234719%0A%0A)

---

1. Connect to a remote. For step 2, your remote must be linux. All other steps can be tested with a Windows remote if you wish. Anything other than WSL is good for testing.
2. The setting `remote.portsAttributes` is not new this iteration, but it now accepts a regex as a property. This regex will match on the cmdline of discovered ports (if you're using SSH open your Machine user settings and set `remote.autoForwardPortsSource` to `process` then reload to get cmdline association). Read the setting and make sure it's clear. Try out this new regex property. For example, 
  - Open the microsoft/vscode-remote-try-node sample. 
  - F5 or run `npm run start`. Look at the running process associated with your port in the Ports view.
  - Make a regex that will match that running process and add it to your `remote.portsAttributes` setting. Note that the `devcontainer.json` for this repo modifies this setting in your machine user settings, so you'll need to either delete that setting or modifier it there.:
```json
".+\\/server.js": {
 "onAutoForward": "openPreview"
}
```
  - Stop your listening process and restart it again. Verify that your `onAutoForward` behavior is respected.
3. The setting `remote.unconfiguredPortsAttributes` (The name of this setting has been changed to `remote.otherPortsAttributes` based on feedback. If you are testing on a newer build than a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e then you'll need this new name.) is new this iteration. Verify that it's description is clear. Try out the setting, and verify that it is respected.

**Comment by isidorn** [comment]
I already had a test plan item for ports on LInux so I assigned myself to Linux to preserve setup and moved @deepak1556 to Windows. I hope that is fine, I checked your platform availablility and Win should be ok for you.
