### ISSUE TITLE
Choose different remote installation directory for SSH

### ISSUE THREAD

**Issue by dave-epstein** [microsoft/vscode-remote-release#472]
By default, VSCode Remote SSH "mounts" itself at ~/.vscode-remote. I have two different servers that share the same home directory that's network shared, so I can't connect to both instances at once without some weird things happening (e.g. if I edit a file in one instance, the other instance disconnects - I imagine they're overwriting each other and clashing somehow).

It would be great if it was possible to specify in some config file where we want VSCode to install itself on the remote machine.

Version of VSCode: 1.35.0
Remote connection type: SSH
OS: Win10
Remote OS: Ubuntu 14.04 on both servers
Extensions: just the Python one, but I imagine this is irrelevant
Reproducible steps:
1) get two different servers that share the same home directory
2) try to connect to both at the same time
3) do various things (R/W operations) on one machine and the other machine's connection will be interrupted/closed
Expectation: be able to work on two machines at once that share the same home directory by being able to change where VSCode Remote installs

Thanks!

**Comment by tbuyukliev** [comment]
i'm also with a shared home directory and it has a very limited quota. i'd rather not keep binaries on it. i need to have per-host configuration of where .vscode-remote is placed, or even better if the location is controlled by some environment variable from the remote system.

**Comment by m-manohar** [comment]
I am running into exactly the same problem. I connect to a bunch of remote servers that share the same home directory (nfs). The problem is not just that the sessions can't exist simultaneously, it's worse- only the session from the last connected server will work. Trying to connect to a server/session that was used earlier fails. Only solution at that point is to delete the .code-server directory.

**Comment by lgladdy** [comment]
Same issue here when running on a managed VPS from someone like cloud ways - You can't create new folders in the home directory.

Seems logical that you should be able to specify a different location for the folder to live.

**Comment by leandromacedo** [comment]
I also have the same problem... Is there any solution for that?

**Comment by marcinz** [comment]
I guess no solutions yet? I was trying to find the source code of the extension itself. Is it publicly available? I mean, this sounds like a pretty easy thing to customize the server directory for different hosts.

**Comment by dnlm** [comment]
I'd need this too. Remote server does not grant wrtite permissions to home directory itself, only subdirectories :(

**Comment by bedge** [comment]
Another use case - many ec2 instances where the only configured user is ec2-user.

One possible solution here is to look at the SSH_CLIENT env variable:
`SSH_CLIENT=10.1.17.246 34712 22`

This is unique for each login source, so everyone that may be using one of these systems uses a unique and consistent SSH_CLIENT variable.

If one could specify a script to run on the target to generate the .vscode-server dir name to use.

eg:
$> ~/bin/gen-vscode-server-dir.sh
~/ec2-user/.10.1.17.246.vscode-server      <- returns dir name to use

This should work for all of the above use cases. 

Perhaps another option is to have a fallback/flexibility is for a local script to run first with the hostname as a parameter. This way, if the remote script doesn't, the local script could upload it, then retry the process.

eg: run locally:
~/bin/upload-gen-vscode-server-dir.sh   <- uploads gen-vscode-server-dir.sh to ~/bin

run remote:
$> ~/bin/gen-vscode-server-dir.sh
~/ec2-user/.10.1.17.246.vscode-server      <- returns dir name to use

**Comment by dbabokin** [comment]
I managed to workaround this issue for the scenario with several machine with the same network home by creating symlink to the local dir:
```bash
cd /users/my_user
mkdir .vscode-server
ln -s /users/my_user/.vscode-server ~/.vscode-server
```

You need to create `/users/my_user/.vscode-server` on every machine that you are going to use, of course.

**Comment by tbuyukliev** [comment]
not completely on-topic, but i noticed that the cpptools extension also stores a lot of data in home, under ~/.cache/vscode-cpptools .

**Comment by keidikapllani** [comment]
> not completely on-topic, but i noticed that the cpptools extension also stores a lot of data in home, under ~/.cache/vscode-cpptools .

There is a settings options for that called C_Cpp.intelliSenseCachePath which lets you choose a custom path for the precompiled headers that it is storing in the .cache folder

**Comment by gsiawGH** [comment]
I have similar situations as others above, i have two servers (e1 and e2) that both mount the same homedirectory with  limited space (company policy).

somehow, i was able to move the vscode-server to another sandbox area

~/.vscode-server -> /sandbox/.e1_vsc/.vscode-server

i am able to delete everything under /sandbox/.e1_vsc/.vscode-server  , and i can connect to e1 over and over.

but if i try to connect with e2, even after deleting /sandbox/.e1_vsc/.vscode-server/* , or even creating a second link, like
~/.vscode-server -> /sandbox/.e2_vsc/.vscode-server

the connection always fails during installation:
mkdir: cannot create directory '~/.vscode-server': File exists
Failed to create the remote server's install directory

this is from macbook to redhat server

Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by AlbertSSj** [comment]
> I managed to workaround this issue for the scenario with several machine with the same network home by creating symlink to the local dir:
> 
> ```shell
> cd /users/my_user
> mkdir .vscode-server
> ln -s /users/my_user/.vscode-server ~/.vscode-server
> ```
> 
> You need to create `/users/my_user/.vscode-server` on every machine that you are going to use, of course.

This workaround stopped working today :-(
The install doesn't accept links anymore.

**Comment by jawhalen8463** [comment]
I am noticing that this issue seems to have stalled as it has been open for nearly a year. Is it still being considered for development. Setting an initial directory upon connect is usually a simple process. Since this is SO important for the vast majority of us, I am concerned it is not being triaged properly.

**Comment by AndrewGaspar** [comment]
We have an additional rub from this issue in that we have home directories mapped to multiple systems with different architectures (x86, arm, and powerpc). Unfortunately, you can't have multiple installs of the server, and so when connecting to the ARM after installing on x86, you get an error due to the invalid binary format.

**Comment by dufferzafar** [comment]
@dbabokin I was just wondering if symlink is the right solution for this. My home directory is on NFS and quite slow, really. Will there be noticeable speed differences if I move my `~/.vscode-server` directory to an SSD and symlink it?

**Comment by dbabokin** [comment]
@dufferzafar First use of the machine and installing new extensions is slow, but other than that it works pretty well for me. But it's just a workaround for the problem.

**Comment by dufferzafar** [comment]
@dbabokin Why is first use and extension install slow? That seems counter intuitive. If we're moving things off NFS and onto SSD then shouldn't it be faster?

But I do agree that this is just a workaround. It'd be great to have this supported by the extension itself.

**Comment by dbabokin** [comment]
@dufferzafar good point, I haven't compared it with NFS location, just noticed that it's slow. Probably it's just due to download speed. Hosting the folder on NFS location is not an options for me at all - due to size limits for the home folder.

**Comment by GongT** [comment]
My **HACK**:
<details>
<summary>First I need the server know the SSH session is from VSCode, I don't have a "good" way.</summary>

1. ## Change VSCode settings
```json
{ "remote.SSH.configFile": "C:/Users/GongT/.ssh/config-vscode" }
```

2. ## Create file C:/Users/GongT/.ssh/config-vscode
```
SendEnv USERNAME
Include ~/.ssh/config
```

3. ## Add server sshd config: (/etc/ssh/sshd_config)
```
AcceptEnv USERNAME
```

4. Restart sshd service
</details>

<details>
<summary>Then I need a monkey patch.</summary>
Place this file at `/dev/profile.d/vscode.sh`

```bash
case "$0" in
*bash*)
	;;
*)
	return # not BASH
esac

case "$-" in
*i*)
	return # is interactive
esac

if [[ "$USERNAME" ]]; then
	echo "Detected VSCode session; USERNAME=$USERNAME; SSH process PID is $$" >&2
	unset USERNAME

	if [[ "$PROXY" ]]; then
		export http_proxy="$PROXY" https_proxy="$PROXY"
		echo "Using proxy for download VSCode server: $PROXY" >&2
	fi

	declare -xr VSCODE_SERVER_HACK_ROOT=/data/AppData/VSCodeRemote

	function ns_exec() {
		set -x
		unshare --pid --fork --kill-child --mount-proc --propagation=unchanged "$@"
	}

	function bash() {
		sed "s|export VSCODE_AGENT_FOLDER=|export VSCODE_AGENT_FOLDER=$VSCODE_SERVER_HACK_ROOT # |g" \
			| ns_exec /usr/bin/bash "$@"
	}
fi

```
</details>

<details>
<summary>💦💦💦</summary>

1. Move `.vscode-server(-insiders)` away
1. Download server release with proxy
1. Move VSCode server in new PID namespace

</details>

**Comment by prasiyer** [comment]
Is this request being worked on?

**Comment by ZachNew** [comment]
I too would like to see this feature in VS code. Is there any update?

**Comment by Sheridan-Tech** [comment]
When will this be completed? Our home directories are stored remotely and as such this is adding latency. Do I need to symlink them?

**Comment by mariosimao** [comment]
I also need this. I having the same issue since VSCode Remote was released. Multiple servers with a shared home. I had to create multiple local users like: `username-vscode`, but it is by far not the best solution.

**Comment by kjoyce77** [comment]
Another vote for this -- ideally it could read an environment variable upon installation and install it wherever it is pointed.

**Comment by dliedtke** [comment]
+1 for this feature request.

**Comment by paidhi** [comment]
I would like to point out that in some environments you have no say in how the remote system is setup. You don't get a personal user account on the remote host but are forced to share a "group account" with multiple people. Being able to specify the directory on the remote would allow using the extension without messing up other peoples environment.

**Comment by iannacone** [comment]
+1 for my managed where i have no permissions on the root

**Comment by NerijusNoreika** [comment]
+1. No permission on root and this extension is not usable.

**Comment by gethurb** [comment]
This is a really helpful feature. In my case, I need to share home dir but I don't want others to share my extensions.

**Comment by meshalawy** [comment]
+1 for the feature is needed. Limited quota on disk and the storage is shared across the cluster. Currently doing the hack of symlinks on every machine (+50). Would be much better if the location of vscode-server is configurable.

**Comment by ahxt** [comment]
+1 for this feature request. Would be much better if the location of vscode-server is configurable.

**Comment by marekmaurizio** [comment]
Unusable on cloudways for this reason.

**Comment by anilnayak** [comment]
+1 for this feature request. All my remote machines shares the same shared home directory and sometime it fails connecting to one of the remote server

**Comment by LeeJAJA** [comment]
+1 for this feature request.

**Comment by OliverScherf** [comment]
+1

**Comment by maxned** [comment]
I want this as well.

**Comment by mariosimao** [comment]
Wanting this for a wile

**Comment by davidvandemaele** [comment]
+1 for this feature request.

**Comment by mcsSteam** [comment]
+1 very much

**Comment by KarthikJay** [comment]
Any updates/timelines for this request?

**Comment by HsuJv** [comment]
+1 for this feature request.

**Comment by fredludlow** [comment]
I've been hitting this problem on and off for a while, which I think (similar to descriptions above) is due to having shared service accounts across multiple machines, i.e. multiple developers SSH into a "dev_user" account on multiple machines, in each case /home/dev_user points to the same NFS mount. 

The main issue is if the dev_user account is running the vscode-server (the remote part of the remote SSH plugin) on one machine, you can't start it on another, and end up in a loop of "Server installation process already in progress - waiting and retrying". As a fix/workaround for this setting `"remote.SSH.lockfilesInTmp": true` is working for me.

However, it would still be better if I could specify my own individual vscode-server install directory on the remote as different human users have different preferred plugins and installing all of them in a shared linux account creates an absolute mess! (And changing the way we login to these remote boxes is not going to be an easy sell just to get one IDE working!)

**Comment by liolok** [comment]
Feature needed +1

**Comment by rhathas** [comment]
+1. No permission on root so i can't use this

**Comment by shawnweeks** [comment]
NoExec on NFSv4 /home required per DoD STIGS, need to be able to set this to an alternative location.

**Comment by deworben** [comment]
+1 for this feature request.

**Comment by kedewei** [comment]
+1 for this feature request.

**Comment by septatrix** [comment]
Another aspect is user like me who would like the installation to conform to the XDG standard. I.e. using `.local/bin`, `.cache` etc.

**Comment by MagereR** [comment]
+1 for this feature request.

**Comment by tanhakabir** [comment]
Just merged in a PR to add this feature. It'll be out on Remote-SSH Nightly tomorrow! You can try it out with the setting `remote.SSH.serverInstallPath`. Please let me know if there's anything unexpected!

**Comment by alippai** [comment]
Sounds great! Does it allow $USER as a variable in the path? Eg /tmp/$USER to avoid collision on a machine with shared users

**Comment by alippai** [comment]
Well, we just have to avoid sharing the settings :)

**Comment by tanhakabir** [comment]
`$USER` should work as well for the installation location

**Comment by NerijusNoreika** [comment]
@tanhakabir  one quick feedback 

![image](https://user-images.githubusercontent.com/7057307/142567711-2acf2996-8800-4c13-9727-09c87aa3c95c.png)

**Comment by ShengdingHu** [comment]
> Just merged in a PR to add this feature. It'll be out on Remote-SSH Nightly tomorrow! You can try it out with the setting `remote.SSH.serverInstallPath`. Please let me know if there's anything unexpected!

Sounds great! Can you provide more information on how to use it?

**Comment by ShengdingHu** [comment]
> Just merged in a PR to add this feature. It'll be out on Remote-SSH Nightly tomorrow! You can try it out with the setting `remote.SSH.serverInstallPath`. Please let me know if there's anything unexpected!

Could we use this to set a different server path for each project? Different projects use different pull-ins which I believe is specified in the .vscode_server folder

**Comment by LiveFreeAndRoam** [comment]
Can I use this per host?

Most hosts I use will use the default, but some hosts need a custom `serverInstallPath`.  E.g. How would I configure host1 to use one path, host2 to use a different path, and hosts to use the default path?

**Comment by bersbersbers** [comment]
> E.g. How would I configure host1 to use one path, host2 to use a different path, and other hosts to use the default path

I haven't tried, but if `$USER` works, see 
https://github.com/microsoft/vscode-remote-release/issues/472#issuecomment-972161775, then I'd expect `$HOSTNAME` and others to work as well.

**Comment by VictorYing** [comment]
>I'd expect $HOSTNAME and others to work as well.

That variable substitution doesn't address the problem I share with ShengdingHu and LiveFreeAndRoam: the desire is to use the remote host name as part of some condition, so that I can apply a particular `serverInstallPath` setting only when SSH-ing to a particular remote.

The documentation indicating that the `serverInstallPath` setting is "a map of remote host to absolute path" could use some clarification, especially I'm not familiar with other vscode settings whose values are expected to be a map. I'd like to know I can make the setting conditional upon whether the remote host name contains a substring matching a pattern or something like that. (I really think substring matching would make this more user friendly.) If the setting requires equality between the map key and the full remote name string and not just a substring, I'd like clarification on what counts as the remote's "name": do I have to specify the remote's the FQDN or if it's based on the alias I have in my ~/.ssh/config that I'm using to SSH to the remote, or if the vscode remote server just checks the value of $HOST or $HOSTNAME after reaching the remote? It's not ideal to need to figure this out by trial and error, when SSH-ing to a shared remote server that the user may have little control over, where failures result in accidentally installing the server in unwanted places that need to be manually cleaned up.

**Comment by LiveFreeAndRoam** [comment]
> > E.g. How would I configure host1 to use one path, host2 to use a different path, and other hosts to use the default path
> 
> I haven't tried, but if `$USER` works, see [#472 (comment)](https://github.com/microsoft/vscode-remote-release/issues/472#issuecomment-972161775), then I'd expect `$HOSTNAME` and others to work as well.

Unfortunately, that won't work. The hostname needs to be part of the key, not the value. I think the only way to solve this is to provide a per-host setting, something like:
```
"remote.SSH.host1.serverInstallPath": "/writeable-store"
```

**Comment by tanhakabir** [comment]
The settings would look like this where the key is the host and the value is the absolute path.

```
"remote.SSH.serverInstallPath": {
    "work": "/test/location",
    "home": "/foobar"
}
```

If multiple hosts share the same server but different paths then multiple instances of the vscode server will be installed at each specified path.

**Comment by bersbersbers** [comment]
This is working great. For the record, another folder `.vscode-server` or `.vscode-server-insiders` is created inside the folder that you configure, which allow using the same setting (`/data`, in this case) across stable and insiders, effectively getting rid of solutions such as this:

```
l ~
...
lrwxrwxrwx  1 bers bers   .vscode-server -> /data/.vscode-server/
lrwxrwxrwx  1 bers bers   .vscode-server-insiders -> /data2/.vscode-server-insiders/
```
