### ISSUE TITLE
Internals of connecting to remote-host

### ISSUE THREAD

**Issue by suyashdeshpande** [microsoft/vscode-remote-release#4720]
Hi Team,

When we connect vscode to a remote host using ssh, as per my understanding it doesn't bring code to our local.
But how does it perform code search under the hood. Does it search in the remote host and bring the output to our local machine or does it brings files to our local machine and then search in them.

And how does the autocomplete works under the hood? As per my understanding, vscode needs to be aware of the code to suggest autocomplete. If it is aware of the code, isn't my local vscode reading the code, that means code is being pulled to my local machine from the remote host. 

Thanks

**Comment by roblourens** [comment]
You might find this useful https://code.visualstudio.com/docs/remote/remote-overview
