### ISSUE TITLE
Test: "initializeCommand" for all platforms

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#4721]
Refs: #4568

- [x] macOS @mjbvz
- [x] linux @deepak1556
- [x] windows @sandy081

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%234721%0A%0A)

---

Have devcontainer.json with an `"initializeCommand"` using the property's array syntax (first element is the command or script, remaining elements are parameters to it) to run a script in the workspace. The path to the script should use slashes (not backslashes) to be portable and there should be a file with that exact name and the executable bit set for Linux/MacOS and a file with that name and `.cmd` or `.bat` as extension for Windows. This setup should be the same independent of the OS you test on.

When reopening this folder in a dev container:
- On Windows:
  - Verify the `.cmd` or `.bat` file is run.
  - Copy the workspace to a WSL path and when reopening that in a dev container verify the shell script is run.
  - Publish to a GitHub repo and when reopening that in a dev container verify the shell script is run. (`Remote-Containers: Clone Repository in Container Volume...`)
- On Linux/MacOS:
  -  Verify the shell script is run.

**Comment by sandy081** [comment]
@chrmarti I cannot test the step that involves WSL as it needs WSL2 and I do not have that installed. I would check if others (@mjbvz or @deepak1556) have this set up or can you please check if someone else have this set up to test?

**Comment by aeschli** [comment]
I tested on WSL.
I found it surprising that while I have a local window open (on \\wsl$\Ubuntu\home\aeschli\workspaces\foo\.devcontainer\devcontainer.json), the initializeCommand is a Linux path
