### ISSUE TITLE
Binaries left behind after update 

### ISSUE THREAD

**Issue by mforkel** [microsoft/vscode-remote-release#4724]
I am using Remote - SSH with remote hosts running Debian Buster and Raspbian Stretch. After an update of VS Code on Windows, the corresponding version of VS Code Server is automatically installed on those hosts, but the binaries of the last version are not removed. E.g., after the update to VS Code 1.54.3, the directory `~/.vscode-server/bin/fd6f3bce6709b121a895d042d343d71f317d74e7`, which was created for VS Code 1.54.2, still exists. With Remote - WSL, the last version is automatically removed.

**Comment by roblourens** [comment]
We do keep the last 5 versions, and they will be cleaned up after that. It's not unusual to connect from different machines with different vscode versions so I am just leaving the old versions until they are totally obsolete.

**Comment by mforkel** [comment]
I became aware of the old versions when I started having problems reconnecting to a server on a Raspberry Pi after an update (_Could not establish connection to "server". The VS Code Server failed to start_). Renaming and/or deleting the old versions solved those problems for me. So the number of versions tolerable might be hardware dependent. While 2 seems to work (right after the update), 5 seemed to be too much. Would you consider making the number configurable?

**Comment by roblourens** [comment]
I don't see why having old versions installed would affect starting the server. Are you low on disk space? Can you share the log from the Remote-SSH output channel when it fails for this reason?

**Comment by mforkel** [comment]
Disk space is not the problem. I though it might be some kind of timing issue on the slow RPi but did not really check.

I have been deleting the old version after each update manually for a while now. I will restrain from that, see what happens and report.

**Comment by tanhakabir** [comment]
@mforkel closing this issue for now, but let me know if you've seen this issue recently after deleting!
