### ISSUE TITLE
Not getting any suggestions in devcontainer.json file

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-release#4728]
Testing #4721

![image](https://user-images.githubusercontent.com/10746682/112131181-91754080-8bc9-11eb-9a17-8ffd861b0ca7.png)

**Comment by chrmarti** [comment]
Which build is this? (The schema is in the built-in Configuration Editing extensions.)

**Comment by sandy081** [comment]
It was yesterday's insiders build

**Comment by chrmarti** [comment]
@aeschli Any idea how this might happen?

**Comment by aeschli** [comment]
I'm not aware of any changes that might cause this.

Also I'm not able to reproduce on Windows nor on Linux: Version: 1.55.0-insider (user setup), Commit: 8437d38d364ba93b53c1e659c20b1c86f710ec28, Date: 2021-03-24T08:16:02.872Z

**Comment by sandy081** [comment]
It works for me now in latest insiders. No clue why it was not working before. So closing.
