### ISSUE TITLE
Test: 'remote-containers.openFolder' command

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#473]
https://github.com/microsoft/vscode-remote-release/issues/336

- [ ] Windows @roblourens
- [x] anyOS @rebornix 

Complexity: 2

Write a test extension for the 'remote-containers.openFolder' command with `(uri?: vscode.Uri, options?: IOpenFolderAPICommandOptions)` as optional arguments.

**Comment by roblourens** [comment]
I'm not sure why this command exists when `vscode.openFolder` exists, but it seems to work fine.

**Comment by chrmarti** [comment]
@roblourens It should open the folder inside a container where `vscode.openFolder` should open the folder locally. 🤔
