### ISSUE TITLE
onAutoForward: open preview not respected

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-remote-release#4730]
Testing #4719

1. Linux, dev container, `microsoft/vscode-remote-try-node` sample
2. Have the following setting
```
"remote.portsAttributes": {
        ".+\\/server.js": {
            "onAutoForward": "openPreview"
        }
    }
```
3. Start you app. Port is auto forwarded, but the preview does not open for me

![Screenshot 2021-03-23 at 11 38 34](https://user-images.githubusercontent.com/1926584/112133773-51fc2380-8bcc-11eb-8ec2-f070bfbfca5e.png)

**Comment by alexr00** [comment]
Looks like the devcontainer.json has been updated to include this setting too:
https://github.com/Microsoft/vscode-remote-try-node/blob/30b1b9d838f844fc89377a1569e0ab794eb7f5ea/.devcontainer/devcontainer.json#L27-L33

I think you set this in your user settings, so it would have been overridden by the devcontainer.json setting, which ends up in your machine user settings.
