### ISSUE TITLE
remote.unconfiguredPortsAttributes is a bad name

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-remote-release#4732]
Testing #4719

I do not like this name for two reasons:
1. we should not use negation if not needed - the "un" part
2. it is not really clear that this means to the rest or the other ports

Due to this I suggest the following name

`remote.otherPortsAttributes`
`remote.allPortsAttributes` - clarify in settings that the other specific setting has priority

**Comment by alexr00** [comment]
I still like `other`, so `remote.otherPortsAttributes` sounds good to me.
