### ISSUE TITLE
Ability to open a host shell while in remote container session

### ISSUE THREAD

**Issue by gcemaj** [microsoft/vscode-remote-release#4736]
Certain tools and configurations live only on the host (git in this case)

would be great to have the ability to open a shell for the local host directly in the integrated terminal

**Comment by Tyriar** [comment]
There's an existing command for that: 
![image](https://user-images.githubusercontent.com/2193314/112293898-e065b900-8c4f-11eb-8854-5ed5f88b6940.png)

It's a little hidden because I don't think enough people will need it to warrant a dedicated spot in the UI.
