### ISSUE TITLE
Command: Clone Repository in Container volume fails in windows

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-release#4739]
Testing #4721

I am using following repo - https://github.com/sandy081/test-devcontainer-sample.git

![image](https://user-images.githubusercontent.com/10746682/112161662-a4990800-8beb-11eb-8678-ae053fc72efd.png)

**Comment by chrmarti** [comment]
Is there anything in the console or log?

**Comment by sandy081** [comment]
Again it worked now. No clue why it did not before.
