### ISSUE TITLE
Remote server fails to initialize when default shell is not bash

### ISSUE THREAD

**Issue by jyn514** [microsoft/vscode-remote-release#4740]
Issue Type: <b>Bug</b>

1. Log into the remote server (e.g. `ssh build-server`)
2. Change the default shell to tcsh (`chsh /usr/bin/tcsh`)
3. Try to open a project with VSCode Remote.

Expected behavior: VSCode works normally.
Actual behavior: VSCode gives many syntax errors and the extension hangs.

```
[11:24:30.941] > Warning: no access to tty (Inappropriate ioctl for device).
> Thus no job control in this shell.
[11:24:31.010] > ready: ab65e0ec240b
[11:24:31.098] > Linux 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24)
[11:24:31.099] Platform: linux
[11:24:31.185] stderr> bash: line 3: syntax error near unexpected token `fi'
[11:24:31.185] stderr> bash: line 3: `		fi'
[11:24:31.194] stderr> function: Command not found.
[11:24:31.194] stderr> Bad : modifier in $ '-'.
[11:24:31.194] > ab65e0ec240b: running
[11:24:31.195] stderr> fi: Command not found.
[11:24:31.195] stderr> found_glibc: Undefined variable.
[11:24:31.195] stderr> Unmatched '"'.
[11:24:31.195] stderr> SERVER_PID: Undefined variable.
[11:24:31.196] stderr> =: Command not found.
```

I see there was a previous issue about this for the fish shell (https://github.com/microsoft/vscode-remote-release/issues/404). I think closing that as a duplicate of https://github.com/microsoft/vscode-remote-release/issues/33 was incorrect - I don't want VSCode to support tcsh, I just want it to be smart enough to open bash in a subshell. That would let it handle arbitrary shells with syntax it doesn't understand instead of adding them one at a time.

Extension version: 0.65.1
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.4.0-67-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 3199)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|7.42GB (1.27GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 560efb9d-26ab-4d8e-aeda-d1ca98b8b6ac|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|LXDE|
|XDG_CURRENT_DESKTOP|LXDE|
|XDG_SESSION_DESKTOP|LXDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by dariomx** [comment]
I believe that this relates to this older issue:

https://github.com/microsoft/vscode-remote-release/issues/2527

and appears to be triggered only from MAC; is that your case as well?

A workaround seems to be to downgrade to 0.49 as explained here:

https://stackoverflow.com/questions/60748384/warning-no-access-to-tty-bad-file-descriptor-visual-studio-code

Hope that helps,
Cheers.

**Comment by jyn514** [comment]
No, that doesn't look related at all. I'm using Linux and the SSH connection works fine if I change the default shell.

**Comment by Xenopathic** [comment]
Try the nightly SSH extension, I found that it works with Fish (not tested with Csh) while the stable extension doesn't.

**Comment by jyn514** [comment]
This is not related to fish. I am using tcsh as my default shell. I don't want or need VSCode to support tcsh, I just want it to spawn a new bash process.

**Comment by roblourens** [comment]
I think this is the same type of issue as what's tracked in https://github.com/microsoft/vscode-remote-release/issues/2509. Setting `"remote.SSH.useLocalServer": false` will probably work around the issue.
