### ISSUE TITLE
Provide a command: 'Clone GitHub Pull Request into Container Volume'

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#4745]
Support for cloning a PR is currently too hidden in the 'Clone Repository into a Container Volume' dialog, users have to know that they can also paste in a GitHub PR URL.

**Comment by egamma** [comment]
To verify:
- run the command 'Remote Containers: Clone GitHub Pull Request in Container Volume...'
- Enter a GitHub PR URL

Verify that the PR is opened in a dev container.

**Comment by chrmarti** [comment]
Verified the new command in 0.165.1.
