### ISSUE TITLE
Upgraded to newest version and it stopped working.

### ISSUE THREAD

**Issue by chelseas** [microsoft/vscode-remote-release#4746]
Testing the nightly version of the extension and it also gives the same error:

Could not establish connection to "remote_machine": spawn ENOTDIR.

(where "remote_machine" is my server)

- VSCode Version:
- Local OS Version:
Version: 1.54.0
Commit: 42e27fe5cdc58539dad9867970326a297eb8cacf
Date: 2021-03-03T02:17:59.499Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.5.0

- Remote OS Version: Ubuntu 16.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Try to initiate a remote ssh window.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by roblourens** [comment]
Please update to the latest vscode version, this should be fixed.
