### ISSUE TITLE
Extending devcontainer.json with custom configuration

### ISSUE THREAD

**Issue by tomferon** [microsoft/vscode-remote-release#4748]
Configuration at `.devcontainer/devcontainer.json` can be version-controlled and shared between developers. However, some might want to customise it to their needs and environment. 

It would be very useful to be able to add a file such as `.devcontainer/devcontainer.extend.json` which would be merged and override configuration in `.devcontainer/devcontainer.json` so that the latter can be version-controlled while the former isn't.

(While searching for a solution to this, I noticed the [documentation](https://code.visualstudio.com/docs/remote/create-dev-container#_using-localhost-in-docker-compose) mentions `.devcontainer/devcontainer.extend.yml` although it's most likely a typo and should read `.devcontainer/docker-compose.extend.yml`)

**Comment by eitsupi** [comment]
+1
This feature is similar to the ability to configure `settings.json` in multiple locations, or `docker-compose.override.yml`, which I find very useful.

There are other feature requests #4723 #4538 #3541 that want to set the container other than `devcontainer.json` included in the project.
