### ISSUE TITLE
port auto forward is not working

### ISSUE THREAD

**Issue by lordzpipo** [microsoft/vscode-remote-release#4750]
Issue Type: <b>Bug</b>

start a service using cli `php -S localhost:9000`
auto forward message box pop out but pressing `browser` will not working
but tested visit the service in guest comp (mac) is working

expected result is able to visit my service on my host (windows) in browser.

Extension version: 0.65.1
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Darwin x64 19.6.0
Remote OS version: Darwin x64 19.6.0

**Comment by roblourens** [comment]
Can you give more details, what is not working? Does it look like the port is not forwarded at all? Any different if you try to forward the port manually?

**Comment by lordzpipo** [comment]
> Can you give more details, what is not working? Does it look like the port is not forwarded at all? Any different if you try to forward the port manually?

sorry for the delay, it's look like the port is not forwarded at all

if i manually add the port in my .ssh file, then port forward work fine

example:
```
Host macbook
  HostName 192.168.1.100
  User username
  PORT 2468
  LocalForward 8888 localhost:8888
  LocalForward 3000 localhost:3000
  LocalForward 9000 localhost:9000
```

**Comment by alexr00** [comment]
> auto forward message box pop out but pressing browser will not working

Can you share a screen shot or a recording of this?
