### ISSUE TITLE
initializeCommand: Looks for a shell file when opened on a local window 

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#4751]
Testing #4721

- Open VSCode on ` \wsl$\Ubuntu\home\aeschli\workspaces\foo`
- generate a `.devcontainer/devcontainer.json` file
- place `init.bat` next to `devcontainer.json`
- add `"initializeCommand": ["./init.bat"]`
- Error `/bin/sh: 1: ./init.bat: not found`

I admit this probably uncommon to open a folder on wsl$

**Comment by chrmarti** [comment]
For WSL paths we run the initializeCommand in WSL. For that the script needs to have the executable bit set and contain a Linux script. (Also: The path is relative to the workspace folder, this is tracked in #4752.) Closing "as designed", thanks.
