### ISSUE TITLE
initializeCommand: Relative path not relative to `devcontainer.json` file

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#4752]
Testing #4721

- Open VSCode on ` \wsl$\Ubuntu\home\aeschli\workspaces\foo`
- generate a `.devcontainer/devcontainer.json` file
- place `init.sh` next to `devcontainer.json`
- add `"initializeCommand": ["./init.sh"]`
- Error `/bin/sh: 1: ./init.bat: not found`

- place the file one level up
- now it works

I would have expected that the path is relative to the `devcontainer.json` file.
If that's as designed, it would be good to have the full path in the 'not found' error message

**Comment by chrmarti** [comment]
This is inconsistent with other paths that are all relative to the devcontainer.json. It is somewhat consistent with other commands, that all run with the workspace folder as their working directory. Changing this would be break, keeping it as-is for now.

**Comment by chrmarti** [comment]
`postCreate/Start/AttachCommand` are actually the same. That's different from `dockerFile`, `context` and `dockerComposeFile`. This is hard to change now, we can consider if we ever do a breaking revision of the format. Closing for now, thanks.
