### ISSUE TITLE
"code-insiders ." does not work when try to open a folder in WSL

### ISSUE THREAD

**Issue by AAkhilleus** [microsoft/vscode-remote-release#476]
I have Win10 Pro version 1903 build 18362.116, my distros are: OpenSuse Leap 15 and Ubuntu (installed from MS Store). I've followed the instructions from [Developing in WSL](https://code.visualstudio.com/docs/remote/wsl), section _Installation_, and when I try to execute _code-insiders_ from my distro I get an error message:

```
[suseUser@mypc ~]$ code-insiders .
If 'code-insiders' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf code-insiders
```
This behavior also occurs for: **explorer**, **code**

What's wrong?

**PS:**
VSC Insiders
```
Version: 1.35.0-insider (user setup)
Commit: 84deb302d7e9ea991a1d0edfd4b4261143f659ff
Date: 2019-05-28T07:56:45.055Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362
```
VSC
```
Version: 1.34.0 (system setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362
```

**Comment by AAkhilleus** [comment]
I just found what is the root of my problem: the distro.

`explorer`, `code`, `code-insiders` commands ONLY work through UBUNTU and I was using OpenSuse.

This **warning** is lacking in every article on Web I read, including on VSC site (example: _Developing in WSL_). This is a disadvantage for other distros. Very bad.

**Comment by aeschli** [comment]
We verified that WSL remote works with every distro (exept Alpine).
Can you open a shell of the distro and check what the PATH? The path should inherit the path from Windows. If not, this is an issue in WSL and need to be filed there.
What I've seen is that when changing the user in WSL, the environment looses the paths from windows. https://github.com/microsoft/vscode-remote-release/issues/286
