### ISSUE TITLE
The remote host's architecture is not supported.

### ISSUE THREAD

**Issue by IQIUM** [microsoft/vscode-remote-release#4762]
When I used the plug-in to connect to Ubuntu 16.04,32 virtual machine, the plug-in gave me an error: Could not establish connection to "Ubuntu32"：The remote host's architecture is not supported.
After searching online, the answer to the question I got may be that the Ubuntu version is too old and 32 bits are not supported. Is my understanding correct? If so, will the backorder support the 32-bit run?

**Comment by roblourens** [comment]
Correct, 32 bit Linux is no longer supported, sorry
