### ISSUE TITLE
The alias about "ls" in ~/.bashrc will not work , but it's strange that all the other settings in /.bashrc worked, including aliases that don't target "ls".

### ISSUE THREAD

**Issue by zhibisora** [microsoft/vscode-remote-release#4763]
Issue Type: <b>Bug</b>

The OS of remote server: CentOS 7.7.1908(Py2.7.5)

If you use the vscode remote-SSH plug to log in to the remote server, you will not be able to use the "ls" related alias set in the ~/.bashrc file of the remote server, but other contents set in the ~/.bashrc file can be used, what's more, the aliases that don't target "ls" can also be used.

I tested "alias ls='ls -l --color=auto'" and "alias ll='ls -al --color=auto'"(without ""), and then kill the vscode process in the server and closed the vscode in local, after these all, I restart them and use the command "alias" in the command line.

The consequence is 
alias ls='ls --color=auto'
alias ll='ls -l --color=auto'

![微信截图_20210325212933](https://user-images.githubusercontent.com/73344387/112480662-39009780-8db1-11eb-8ffb-d7a760a1913c.png)
(configuration & result)

That's unfortunately. 
I don't want this result.
Maybe aliases about 'ls' were covered by other  configuration file.

My solution of this question is write these configuration into /etc/bashrc, then, they will work as local or other ssh connections.

Extension version: 0.65.1
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2894)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.37GB (8.36GB free)|
|Process Argv|--crash-reporter-id b71577a3-92da-42d1-a6d1-dbfd5cec5944|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30280384
pythontb:30265425
vspre833:30267464
vshan820:30276952

```

</details>

**Comment by roblourens** [comment]
I think that either there is a conflict with another config file, or the other aliases are coming from another config file. Either way, I think that this is an issue with your configuration, not the Remote-SSH extension.
