### ISSUE TITLE
Test: WSL uses .vscode-server / .vscode-server-insiders instead of .vscode-remote

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#477]
https://github.com/microsoft/vscode-remote-release/issues/418

- [x] insiders @rebornix 
- [x] stable @mjbvz 

Complexity: 2
- install https://github.com/microsoft/vscode-remote-release/files/3228743/remote-wsl-0.36.1.vsix.zip (rename from `.vsix.zip` to `vsix`)
- use WSL with an older insiders build that still creates a `~/.vscode-remote` in the WSL file system
- install an extension
- use WSL with the latest insiders build (a429fd1356).
- verify in the log that it moves  `.vscode-remote` to `.vscode-server-insiders`
- check that the extension you have installed still is there
- for stable create a stable build and check that `.vscode-server` is used

**Comment by aeschli** [comment]
[remote-wsl-0.36.1.vsix.zip](https://github.com/microsoft/vscode-remote-release/files/3228743/remote-wsl-0.36.1.vsix.zip)

**Comment by mjbvz** [comment]
@aeschli By `stable`, do you mean the stable versions of the remote extensions?

**Comment by aeschli** [comment]
@mjbvz I would suggest to trigger a stable build from master and test on that.

**Comment by mjbvz** [comment]
Ok, thanks @aeschli. I didn't realize we were releasing stable with remote support this iteration
