### ISSUE TITLE
Every so often it will disconnect and I will need to enter my password

### ISSUE THREAD

**Issue by goodbreathseth** [microsoft/vscode-remote-release#4773]
Issue Type: <b>Bug</b>

I'm using cisco VPN on a Vue + laravel project.  Every so often my compiler will freeze and close and I'll need to re-enter my password for the extension (not necessarily in that order)

Extension version: 0.65.1
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.14.219-161.340.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (8.90GB free)|
|Process Argv|--crash-reporter-id fd751111-dab8-40fc-837e-81ff0e783202|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: webdevbatch2a|
|OS|Linux x64 4.14.219-161.340.amzn2.x86_64|
|CPUs|AMD EPYC 7571 (2 x 2199)|
|Memory (System)|1.92GB (0.07GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
pythonvspyt943cf:30280190
openwsldoc:30280162
vspre833cf:30267465
vshan820cf:30276953

```

</details>

**Comment by roblourens** [comment]
What is the issue - that it gets disconnected or that you have to reenter your password? The pw is expected, you have to enter this for each connection.

**Comment by roblourens** [comment]
Here are some things that can cause disconnections
- Extensions or other processes using lots of CPU or memory
- Very large workspaces that cause VS Code's filewatcher process to use lots of memory
- Anything that disrupts the network connection between the local and remote machines
