### ISSUE TITLE
Not able to debug with attaching to process inside container

### ISSUE THREAD

**Issue by lemonglutton** [microsoft/vscode-remote-release#4775]
Hey I am trying to debug application in remote container by attaching to process. The problem is that I am not able to do that because my breakpoints there are all the time inactive. Not sure what's the root of that, I have posted this issue also on stackoverflow. Its under this link: https://stackoverflow.com/questions/66805465/debugging-in-vscode-remote-containers

- VSCode Version: 1.54.3
- Local OS Version: Win10 10.0.1863
- Remote OS Version: Debian GNU/Linux 10 (buster) -> container
- Remote Extension/Connection Type: docker

Steps to Reproduce:

1. Create new Go dev container configuration file
2. Add _--privileged_ to runArgs
2. Create debugging configuration for your application, for "attaching to process" debugging config
3. Build and open remote container
4. Try to debug application by clicking "Start debugging" button
5. Choose particular process associated with your app
6. Observe that added breakpoints are inactive

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Can you try setting a breakpoint in server.go and hit F5 in the Go sample? (`F1` > `Remote-Containers: Try a Sample...`)

**Comment by lemonglutton** [comment]
Hello, thanks for response!
I have checked that image and it turns out that the situation is the same as in mine. Launching app via debugger works just fine, but when trying to attach to process breakpoints are inactive and debugger is bypassed when doing request from postman.
(I have added this configuration for attaching to process)

Some screenshots:

Launch server configuration works, attach to process conf is not working - maybe there something wrong here?
![debugConfOfficial](https://user-images.githubusercontent.com/34936474/112830198-81aaa000-9092-11eb-9379-3c664f6a4ae9.png)

![choosing process](https://user-images.githubusercontent.com/34936474/112830195-81120980-9092-11eb-868a-5eeef8888dee.png)

![inactiveBreakpoint](https://user-images.githubusercontent.com/34936474/112830200-82433680-9092-11eb-936e-1c35f6aa5947.png)


Thanks in advance, regards!

**Comment by chrmarti** [comment]
It seems some flags are needed when building. It works for me when I build with `go build -gcflags="all=-N -l" -o server`.

I also had to do `echo 0 >/proc/sys/kernel/yama/ptrace_scope` as root. Not sure if that's always required. (Found in https://bitworks.software/en/2017-07-24-docker-ptrace-attach.html.)

**Comment by lemonglutton** [comment]
Yes there is something in it. I also came across link that you provided. It seems there is a problem with go run and compiling in fly - I am not able to attach to this process.
When I used gin watcher https://github.com/codegangsta/gin which produces binary each time code changes and I am able to attach to it -didnt have to add anything more. Same with go build command you posted. So it means that it has to do something with go run command.

**Comment by lemonglutton** [comment]
Yes there is something in it. I also came across link that you provided. It seems there is a problem with go run and compiling in fly - I am not able to attach to this process.
When I used gin watcher https://github.com/codegangsta/gin which produces binary each time code changes and I am able to attach to it -didnt have to add anything more. Same with go build command you posted. So it means that it has to do something with go run command and its optimalizations under the hood?

**Comment by chrmarti** [comment]
It didn't work when I used `go run server.go`. It only worked when I used `go build -gcflags="all=-N -l" -o server` to get a binary and then launched that with `./server` (using the Go sample). Have you tried that?

**Comment by lemonglutton** [comment]
Yes, command you have posted are working for me also. So I can now attach to the process. Thanks!
Got one more question.  Are you going to prioritize this as an issue? I mean that we are not able to attach to process with go run command? Not sure though if its more related with vsCode or dvelve debugger itself.

**Comment by chrmarti** [comment]
I'm not an expert on Go, the build flags might be required for the debugger to have the required debugging information in the binary. Maybe ask on StackOverflow as  a Go-only question (independent of VS Code and Remote-Containers). Thanks.
