### ISSUE TITLE
Activating extension '[extension name]' failed: Unexpected token '?'.

### ISSUE THREAD

**Issue by WilliamVenner** [microsoft/vscode-remote-release#4785]
Hi there,

I am getting an error which is breaking my extension when I use it in a Remote SSH environment, unfortunately I have no idea how to debug this as the stack trace is mostly useless and the error is very ambiguous.

```
Activating extension 'venner.vscode-glua-enhanced' failed: Unexpected token '?'.
```

The error does not occur in a local environment.

- VSCode Version: 1.54.3
- Local OS Version: Windows 10 Pro 20H2
- Remote OS Version: Debian 10, Linux 4.19.0-13-amd64
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install https://marketplace.visualstudio.com/items?itemName=venner.vscode-glua-enhanced
2. Open a `.lua` file

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Console Log**

[-1617070100687.log](https://github.com/microsoft/vscode-remote-release/files/6225671/-1617070100687.log)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/4692
