### ISSUE TITLE
Not prompted to install extensions when opening in a remote container

### ISSUE THREAD

**Issue by cmamigonian** [microsoft/vscode-remote-release#4788]
I see two issues:

1. There no longer seems to be the `Open Named Configuration File` command anymore, therefore I can't have extensions installed automatically when starting a new container with the same name.
2. Using the `extensions.json` file in my source repo opened in my remote container does not prompt to install recommended extensions.

- VSCode Version: 1.54.3
- Local OS Version: Windows 10
- Remote OS Version: RHEL 7.6
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open command palette and search for `Open Named Configuration File`.  This command no longer seems to exist.
2. Attach to a running Docker container on a remote Linux host.
3. Open a folder in the container that has a `.vscode/extensions.json` file.
4. No prompt to install recommended extenstions.

**Comment by chrmarti** [comment]
You should still see the command while you are attached to a container:
![image](https://user-images.githubusercontent.com/9205389/113098145-65c10e80-91f8-11eb-9efe-56dabf5def5f.png)

You can also get a list of all configurations at any time (the window doesn't have to be attached to a container):
![image](https://user-images.githubusercontent.com/9205389/113098260-8db07200-91f8-11eb-8fe4-5db37821af26.png)

The notification for `.vscode/extensions.json` recommendations only shows once per URI. For containers it might make sense to show it once per container.

Maybe more convenient is when you add the list of extensions you want to install to the configuration file's `"extensions"` property as a string array.

**Comment by cmamigonian** [comment]
Ah I forgot you had to be in the container to access that command.  I do see it now.  Thank you!
