### ISSUE TITLE
Interop error when trying to authenticate git with VSCode Source Control

### ISSUE THREAD

**Issue by emiliosanches** [microsoft/vscode-remote-release#4790]
- VSCode Version: 1.54.3
- Local OS Version: Windows 10 20H2 build 19042.867
- Remote OS Version: Ubuntu 20.04.2 LTS
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Set git config global to use git-credential-manager.exe as credential.helper
2. Start WSL Remote window in VSCode
3. Try to perform any action that needs authentication using the Source Control buttons. 
  i.e: pull commits clicking the button on status bar
  [Third icon in this image](https://prnt.sc/1105cki)

When I run `git pull -u origin [branch]` from a terminal, it executes with no problems. But, when I try to pull using VSCode, it asks me for a password (it shouldn't do that) and in git log, it shows the following error:

```bash
<3>init: (22164) ERROR: UtilConnectToInteropServer:300: connect failed 2
<3>init: (22177) ERROR: UtilConnectToInteropServer:300: connect failed 2
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by aeschli** [comment]
Sorry, I don't know what the problem is. I doubt this is caused by the WSL extension.
I found this:
https://superuser.com/questions/1602401/vscode-terminal-behaves-strangely-when-opening-a-project-that-is-inside-wsl2
