### ISSUE TITLE
env vars not populated with remote ssh into docker (see 836)

### ISSUE THREAD

**Issue by BjoernKellermann** [microsoft/vscode-remote-release#4792]
This is a dublication to issue 836, where conversation is limited to contributors, but still a problem...

- VSCode Version: 1.54.3
- Local OS Version: Windows_NT x64 10.0.19041
- Remote OS Version: Docker
- Remote Extension/Connection Type: SSH into Docker

Steps to Reproduce:

1. log into remote Docker via ssh
2. run any python script having os.environ['my_env_var_name'] or a corresponding watch in debugger
-> got KeyError

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

launch.json:
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Remote File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "cwd": "/usr/local/airflow/dags",
            "pathMappings": [{
                "localRoot": "${workspaceFolder}",
                "remoteRoot": "/usr/local/airflow"}    
            ]
        }
    ]
}`

**Comment by BjoernKellermann** [comment]
Sshd seems to vipe out env vars. Please see
- https://stackoverflow.com/questions/216202/why-does-an-ssh-remote-command-get-fewer-environment-variables-then-when-run-man
- https://wilsonhong.medium.com/linux-ssh-command-using-with-environment-variables-e5b7ebb43d30

Maybe you can find a way. For security reasons we have to develop on a remote machine which get credentials and connections injected by env vars.

**Comment by chrmarti** [comment]
Related: #2994

**Comment by chrmarti** [comment]
Fixed as https://github.com/microsoft/vscode-remote-release/issues/4781.
