### ISSUE TITLE
Docker returned an error. Make sure the Docker daemon is running 

### ISSUE THREAD

**Issue by tao-bai** [microsoft/vscode-remote-release#4794]
I tried to connect the containers on my server via vs code. specifically, I connected to my server with remote-ssh, then used the extension docker to connect the container: attach vscode. It worked before. Not sure what happened. 
Anyone can help?

the server: ubuntu 20.04
pc: win10

**Comment by chrmarti** [comment]
Could you attach your Remote-Containers log from when this fails? (`F1` > `Remote-Containers: Show Log`)

**Comment by tao-bai** [comment]
Thank you! I just fixed it. No problem now.
