### ISSUE TITLE
The Attach Visual Studio Code context menu item in the Kubernetes extension does nothing when clicked from a VSCode window attached to a WSL2 remote.

### ISSUE THREAD

**Issue by doncarlosx** [microsoft/vscode-remote-release#4797]
Based on my search I believe there is one existing issue, but it was closed because the reporters were not responsive.
https://github.com/microsoft/vscode-remote-release/issues/2781

- VSCode Version: 1.55.0-insider (user setup) Commit c185983a683d14
- Local OS Version: Windows 10 Home Version 20H2 OS Build 19042.867 Windows Feature Experience Pack 120.2212.551.0
- Remote OS Version: Ubuntu 20.04.1 LTS
- Remote Extension/Connection Type: WSL2

Steps to Reproduce:

1. Download VSCode.
2. Install `ms-vscode-remote.vscode-remote-extensionpack`.
3. Install `ms-kubernetes-tools.vscode-kubernetes-tools`.
4. Connect VSCode to Ubuntu WSL2.
5. Install/enable Kubernetes extension in WSL2 remote.
6. Navigate to Kubernetes sidebar.
7. Have some sort of kube config in place in the WSL2 filesystem.
8. Expand cluster -> workloads -> pods.
9. Right click on pod.
10. Click Attach Visual Studio Code.
11. Observe that there is no prompt for a container or error message.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

But it is worth noting, I tested this feature on mac os and it works great. Between that and this comment https://github.com/microsoft/vscode-remote-release/issues/2781#issuecomment-635483628 I'm inclined to believe that there is some sort of disconnect between the Remote extension and the Kubernetes extension. I guess this because the Remote extension is not installed in the WSL2 remote, but the Kubernetes extension is, so maybe the Remote extension is somehow looking in the wrong (i.e. Windows based) places for tooling or config?

Let me know what else I can do to help diagnose this!

I'm attaching a short mp4 to try and lean on a (moving) picture being worth a thousand words.
https://user-images.githubusercontent.com/38721/113160381-12a08900-9203-11eb-9a10-bcaf2cfb1c02.mp4

**Comment by chrmarti** [comment]
Your guess is correct. One way to work around this would be to set up kubectl on Windows and connect it to the WSL cluster. Then you don't need to connect VS Code to WSL and the Kubernetes and Remote-Containers extensions should work similarly to Mac.

**Comment by chrmarti** [comment]
Some thoughts:

This could be implemented by either of:
- Using Remote-WSL to open a WSL window, optionally with a folder that is then used as the working directory for `kubectl`. (This would also pick up any local kubeconfig.yaml https://github.com/microsoft/vscode-remote-release/issues/4998.)
- Adding a user setting to configure how `kubectl` should be called.

The first option would go well with the Kubernetes extension using kubectl from WSL when connected with Remote-WSL.
