### ISSUE TITLE
follow link file:line ignores line number with remote-ssh

### ISSUE THREAD

**Issue by ymartineau** [microsoft/vscode-remote-release#4801]
- VSCode Version: 1.54.3 (user setup)
- Local OS Version: Windows_NT x64 10.0.18363
- Remote OS Version:  Linux x64 3.10.0-1127.8.2.el7.x86_64
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. install scope4code extension
2. generate cscope database "Cscope: Build database"
3. on a symbol, run: "Cscope: Find this C symbol", it opens a new tab with list of symbols with /absolute/path/file:line format:

All references found for symbol: "processAbc":
/a/b/c:.cpp:93 <global> bool processAbc(void * foo, bar_t bar)
/a/b/d:.cpp:7 <global> bla::processAbc(we, ze, resp);

4. ctrl+click or "follow link" on the file, it opens the file but not at the right line number.

Does this issue occur when you try this locally?: No (tested "locally" on a linux VM with a vnc connection and the vscode client on this linux VM, and tested on windows host locally)
Does this issue occur when you try this locally and all extensions are disabled?: not tested (I don't know how I could test)

Please forgive me if the issue is not reported on the right repository.
I'm really new to vscode. I suppose the line and numbers are provided to some kind of vscode API, so I wanted to debug the value provided from the scope4code extension, I found the following lines:

https://github.com/xulion/scope4code/blob/master/src/FindResultDoc.ts#L22

that look interesting (I may be looking at the wrong place...), but I don't know how to debug those statements. Is there some kind of "trace tool" of the api between extensions and vscode itself that would eventually run without building nor debugging the extension itself?

Thank you,

yohann

**Comment by roblourens** [comment]
Do you own this API @jrieken?

**Comment by roblourens** [comment]
Please also file this issue on the extension. They can investigate to make sure that they are sending the right range.
