### ISSUE TITLE
Opening HTML file in browser

### ISSUE THREAD

**Issue by amcheers** [microsoft/vscode-remote-release#4805]
Issue Type: <b>Bug</b>

When I attempt to open HTML file in browser the Home directory cannot be found by Windows.

Extension version: 0.54.6
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.76GB (5.12GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/acheers/code/amcheers/profile --remote=wsl+Ubuntu --crash-reporter-id 9cc88d4b-d7c7-41c6-a150-0d6faf4e872c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|Memory (System)|9.14GB (8.65GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
wslfolderdoccf:30282075
vscoresta800:30279781
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30283453

```

</details>

**Comment by aeschli** [comment]
How exactly do you open the HTML file?
