### ISSUE TITLE
Could not fetch remote environment after install docker desktop application

### ISSUE THREAD

**Issue by Roy-Kid** [microsoft/vscode-remote-release#4810]
- VSCode Version: 1.55.0
- Local OS Version: window10 19043
- Remote OS Version: ubuntu 20
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. It's ok to use remote: wsl to connect WSL
2. I install the docker desktop application
3. Can't connect wsl anymore: Could not fetch remote environment; Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by shawnrmoss** [comment]
Did you ever find a solution to this?  Im experiencing the exact same thing.

**Comment by aeschli** [comment]
In a Windows command prompt, can you do a `wls --list` ?
The docker-desktop must not be the default distro.
