### ISSUE TITLE
Cannot use npm uninstall

### ISSUE THREAD

**Issue by zkldi** [microsoft/vscode-remote-release#4811]
Issue Type: <b>Bug</b>

Seems like npm uninstall in the in-vscode-bash-shell (under WSL) doesn't work. Fails with EPERM. Vscode also seems to be holding the files hostage, as it appears nothing can rename files in node_modules while wsl:ubuntu vscode is open.

Extension version: 0.54.6
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3499)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (7.03GB free)|
|Process Argv|D:\\Documents\\_repos\\Kamaitachi-Black\\ktblack-server --crash-reporter-id 48d7e234-b6ae-4235-8b01-babb48b24fb9|
|Screen Reader|no|
|VM|40%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3501)|
|Memory (System)|15.68GB (7.04GB free)|
|VM|40%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30283811
wslfolderdoccf:30282075
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30283453

```

</details>

**Comment by aeschli** [comment]
Is this WSL1?
See https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace-in-wsl-1

**Comment by zkldi** [comment]
It would be WSL1, yes. Is this fixed under WSL2?

**Comment by aeschli** [comment]
Yes, this is fixed for WSL2

**Comment by zkldi** [comment]
No worries then, this should be okay to close.
