### ISSUE TITLE
Git autorefresh not working with WSL2

### ISSUE THREAD

**Issue by NeoLight1010** [microsoft/vscode-remote-release#4814]
Issue Type: <b>Bug</b>

The Git extension does not autorefresh when working with WSL2. My workspace is in \\wsl$\

Extension version: 0.54.6
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.36GB (1.52GB free)|
|Process Argv|--crash-reporter-id a3794b3d-2891-4d1a-a8b0-b54e4dcfe32b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics (12 x 2994)|
|Memory (System)|5.69GB (0.30GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
pythonvspyt943:30280189
openwsldoc:30282072
vsget980:30284045
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30283453

```

</details>

**Comment by aeschli** [comment]
It's a known WSL2 issue that file events are not reliable when on a `wsl$` mount.

WSL issue: microsoft/WSL#4739
