### ISSUE TITLE
SSH extension doesn't parse the include directive

### ISSUE THREAD

**Issue by ismail** [microsoft/vscode-remote-release#4817]
I have in my ssh config: `include *.conf` and all the host definitions live there:

```
; cat local.conf
Host i10z i10z.com
Hostname i10z.com
Port 4160
```
But these do not show in the SSH extension's host list. Would be nice if the `include` directive could be supported.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/2446
