### ISSUE TITLE
Breakpoints unbounded while debugging - Blazor client

### ISSUE THREAD

**Issue by Ursanon** [microsoft/vscode-remote-release#4819]
- VSCode Version: `1.55.0`
- Local OS Version: Ubuntu 20.04
- Remote OS Version: Debian 10 (buster-slim)
- Remote Extension/Connection Type: Docker

Currently every breakpoint inside blazor's `@code` is marked as `unbounded`.

Steps to Reproduce:

1. Create sample blazor wasm project (follow [official tutorial](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio-code))
2. Create breakpoint

Does this issue occur when you try this locally?: **No**
Does this issue occur when you try this locally and all extensions are disabled?: **No**

Workaround: debug it locally.

**Comment by chrmarti** [comment]
Could you share your code from the tutorial in a Git repository?
