### ISSUE TITLE
Handling invalid path for workspaceFolder in devcontainer.json

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-remote-release#482]
Testing https://github.com/microsoft/vscode-remote-release/issues/475

- Open some folder
- Run `Create Container Configuration File...`
- Add a "workspaceFolder" property to the devcontainer.json that isn't a path to anything:

```
{
	"name": "Node.js (latest LTS) & TypeScript",
	"dockerFile": "Dockerfile",
	"extensions": [
		"ms-vscode.vscode-typescript-tslint-plugin"
	],
	"workspaceFolder": "garbage"
}
```
- Run `Reopen Folder in Container`

My expectation was that I would see some kind of error notification. Instead I'm now in a container with weird state, the file explorer shows the full remote authority and clicking on it causes an error about the url not being absolute:
 
![Screen Shot 2019-05-28 at 11 02 47 AM](https://user-images.githubusercontent.com/3672607/58500985-3773d300-8138-11e9-94b9-0074e7ab47ab.png)

**Comment by chrmarti** [comment]
Adding a check for `workspaceFolder` being an absolute path. We don't know if that path exists at that point, but it being an absolute path makes sure that the remote window opens in a more regular way. A non-existing folder will then be shown with a warning in the explorer of the remote window.
