### ISSUE TITLE
Box to enter/edit file name closes after a couple of seconds

### ISSUE THREAD

**Issue by gustavoeddfernandes** [microsoft/vscode-remote-release#4820]
- VSCode Version: 1.55.0
- Local OS Version: Mac OS 11.2.3 
- Remote OS Version: Raspbian GNU/Linux 10 (buster)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Create a new file or folder in the remote server using the file Explorer or select an existing file in the remote server and press RETURN to rename it.
2. Start typing the new file name and notice that the file Explorer "refreshes" a couple seconds later and prevents the complete file name from being entered.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/112293
