### ISSUE TITLE
How to debug an extension inside a development container?

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-remote-release#4821]
I want to test how my extension works in a development container, in the following scenario:

1. I develop it in WSL with Remote - WSL
2. When I press F5 it opens the extension host in Remote - WSL as intended
3. When I navigate to a folder which has the .devcontainer definition and hit "Reopen in container", my extension doesn't seem to be installed there.

So, how am I supposed to test an extension inside a development container?

I could not find this answer by myself so I'm sorry if it's my fault, but otherwise, I think this should be documented somewhere.

**Comment by chrmarti** [comment]
Have you tried reopening the extension's folder in a devcontainer and then F5-ing it from there?

**Comment by felipecrs** [comment]
I think that would cause my extension to be debugged in the same container I'm developing it.

My goal was to debug it in a devcontainer initialization. For some reason the language server for my extension is failing to start when it gets activated on a creation of a devcontainer, and it's hard to debug as it only happens in such scenario.

**Comment by chrmarti** [comment]
I think you would need:
- Your extension mounted at `~/.vscode-server/extensions/you.your-extension`.
- The remote extension host start in debugging mode and wait for a second VS Code window to attach to it for debugging.

@sandy081 Is it enough to have an extension's source project mounted into the extensions folder for it to be activated?
@connor4312 How could we get the remote extension host started with `--inspect-brk`?

**Comment by connor4312** [comment]
The way I do this is to develop the extension in the same container as I'm testing in, then F5'ing from there. I don't think there's another way to do this.

**Comment by sandy081** [comment]
> Is it enough to have an extension's source project mounted into the extensions folder for it to be activated?

Ye
