### ISSUE TITLE
Port forwarding polish

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#4826]
- [x] Render forwarded ports with a filled green dot
- [x] Render entries in the 'Local Address' column as links on hover. Show a hover that enables to follow the link using 'cmd+click' (same as URLs are handled in the terminal)
- [x] Make the command 'Set label and update devcontainer.json' the primary action in the ports view

**Comment by misolori** [comment]
Another item to consider here is if we'd want to de-emphasize the "Add Ports" button since that is that is much more prominent. Given that this is less likely to be used compares to other actions, my suggestion is to go back to the previous version of using the `+` on the side:

![image](https://user-images.githubusercontent.com/35271042/113747348-25f89c00-96bc-11eb-9874-a680b3b4d4f3.png)

**Comment by alexr00** [comment]
Added the green. I copied the green color that we have for marking the current container the containers view in the remote explorer:

![image](https://user-images.githubusercontent.com/38270282/113873851-799ae080-97b5-11eb-997e-22c85bbedb94.png)

**Comment by alexr00** [comment]
For theming, the color is called "portWithRunningProcess.foreground"

**Comment by misolori** [comment]
@alexr00 should we select a default from an existing color and then override it in our default themes? We've done that before (like the remote indicator) where we want a specific color that doesn't theme well

**Comment by alexr00** [comment]
That makes sense to me. I couldn't find a good green color in our existing colors. I could use the same color as the remote indicator.

**Comment by misolori** [comment]
Yea either the remote or the debug start (`debugIcon.startForeground`) would work 👍

**Comment by alexr00** [comment]
Added the terminal inspired hover text and underline:

![recording (52)](https://user-images.githubusercontent.com/38270282/114022444-10c56e00-9872-11eb-8024-0f8acdf95e2b.gif)

**Comment by alexr00** [comment]
I actually started with `debugIcon.startForeground`, but I found it too be too pale:

![image](https://user-images.githubusercontent.com/38270282/114023074-b842a080-9872-11eb-83b4-28608f435368.png)

The remote indicator default looks a bit nicer, so I'll go with that and override it in the default themes as suggested:

![image](https://user-images.githubusercontent.com/38270282/114023314-05267700-9873-11eb-9fae-279961606a25.png)

I've also changed the name of the color to be a bit more consistent with the other colors: `ports.iconRunningProcessforeground`.

Finally, I updated all the built in themes to have a reasonable color (certainly open to changes here) set for `ports.iconRunningProcessforeground`.

**Comment by alexr00** [comment]
Taking inspiration from the terminal for the hover:
![recording (54)](https://user-images.githubusercontent.com/38270282/114399474-3e2b5800-9ba1-11eb-9531-e98eed1c3ec4.gif)

**Comment by alexr00** [comment]
> Make the command 'Set label and update devcontainer.json' the primary action in the ports view 

Requires some small package.json adoption from Codespaces for the Codespaces extension to adopt this. I have already made the required change in Remote - Containers.
