### ISSUE TITLE
Remote Explorer: Simplify how Containers are rendered

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#4829]
Currently the remote explorer shows both the container and the folder that has been opened. 
![image](https://user-images.githubusercontent.com/172399/113686003-19c60c00-96c7-11eb-842f-4c9978934cb9.png)

In most cases a remote container has been opened on a single folder only and to simplify the appearance we can combine the nodes into a single node. This is similar how it is done in the Codespaces contribution:

![image](https://user-images.githubusercontent.com/172399/113685561-ab814980-96c6-11eb-8b74-3bab997e34ad.png)

In addition we should not show all container information in the tree label but move some of the information into the hover and make the hover richer (leveraging the new markdown support). Code spaces is showing a rich hover, but not yet using the markdown rendering support.

![image](https://user-images.githubusercontent.com/172399/113685827-ef744e80-96c6-11eb-884d-51916191fee5.png)

For example something like this
<img width="355" alt="image" src="https://user-images.githubusercontent.com/172399/113686803-f51e6400-96c7-11eb-90e4-99e87d89af5b.png">

See also the related issues #3823, #3717

**Comment by alexr00** [comment]
Flatter list + nicer hover:

![image](https://user-images.githubusercontent.com/38270282/114556658-37681800-9c69-11eb-9e34-763f666d3510.png)
