### ISSUE TITLE
IntelliSense for settings in dev container json

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-remote-release#483]
Re https://github.com/microsoft/vscode-remote-release/issues/471

It would be awesome that we can specify schema for `settings` section and have IntelliSense while writing them.

**Comment by chrmarti** [comment]
Not sure how easy / hard that is. @aeschli @sandy081 Can we somehow use the settings schema for a property in the devcontainer.json?

**Comment by aeschli** [comment]
In the schema for the dev container, just do `"settings": { "ref": "vscode://schemas/settings/machine" }`

**Comment by rebornix** [comment]
It's amazingly awesome!
