### ISSUE TITLE
Slim down the rendering of the remote command palette

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#4831]
The command palette shows redundant information and we should investigate into a slimed down rendering.

![image](https://user-images.githubusercontent.com/172399/113688847-f94b8100-96c9-11eb-86bc-8318420f4a60.png)

Investigate into a rendering as is done for themes
![image](https://user-images.githubusercontent.com/172399/113688995-21d37b00-96ca-11eb-9dae-be829e5d1f4e.png)

**Comment by aeschli** [comment]
![quickitemfilter](https://user-images.githubusercontent.com/6461412/114368633-df081c00-9b7d-11eb-8d00-ed07c5f8345d.gif)
