### ISSUE TITLE
have to reload the window after excute `pkill node`

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/vscode-remote-release#4833]
version: all latest

after excute `pkill node`
I have to re-login and reload the window

is this a bug?

**Comment by chrmarti** [comment]
If you do this on the remote machine (WSL / container / SSH): Yes, you need to reload the window. Not sure where you see the re-login.

**Comment by HomyeeKing** [comment]
just after run `pkill node` , then password input popup
![image](https://user-images.githubusercontent.com/49113249/113841779-a86c8300-97c4-11eb-824e-a97bc3ef9a74.png)

**Comment by chrmarti** [comment]
What kind of account is the password for? This might be triggered by a local extension.

**Comment by HomyeeKing** [comment]
the password of the remote machine

**Comment by roblourens** [comment]
The remote server is a node process, if you kill it then you will have to reconnect, yes.
