### ISSUE TITLE
Attach VSCode via docker extension to docker on remote server results in error

### ISSUE THREAD

**Issue by tyrionlannistar** [microsoft/vscode-remote-release#4837]
Hello community, did anyone experience the same problem?

I run VSCode on a windows 10 machine and connect to my Ubuntu workstation via the extension Remote - SSH.
The docker container is running on the ubuntu workstation.
After installing the docker extension I can use it to start and stop the remote docker container and even attach a VSCode terminal to the docker.
However, when trying to attach VSCode to the docker, it fails: "Docker returned an error. Make sure the Docker daemon is running."
The corresponding log file of this error message gives me following:

Start: Run: docker version --format {{.Server.APIVersion}}
[2303492 ms] findLocalWindowsExecutable: Exectuable 'docker' not found on PATH 'C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\OpenText\Viewer\bin;C:\Program Files\7-Zip;C:\Program Files\PuTTY\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Users\...\AppData\Local\Microsoft\WindowsApps;;C:\Users\...\AppData\Local\Programs\Microsoft VS Code\bin'.
[2303494 ms] spawn C:\Users\...\AppData\Local\Programs\Microsoft VS Code\docker ENOENT

Why would the docker extension look on my windows machine for a running docker daemon, although it is installed on the remote workstation?
Any idea how i could solve this issue?

Thank you.

**Comment by chrmarti** [comment]
The Remote-Containers extension is installed locally and requires the Docker CLI to connect to a remote Docker Daemon.

**Comment by tyrionlannistar** [comment]
Hello chrmarti!
Nope, the remote containers is installed on the remote machine via ssh. Otherwise I would not be able to start and stop the docker on the remote machine. 
Unfortunately, the VS Code attachment to the docker does not work, as it is supposed to do...
https://code.visualstudio.com/docs/containers/choosing-dev-environment#_remote-machine
Please keep the ticket open.

**Comment by tyrionlannistar** [comment]
Hello @chrmarti, after reading more about remote docker, I think I did not miss-understand the way of connecting to the remote docker, as I followed this instruction: ghttps://code.visualstudio.com/docs/containers/choosing-dev-environment#_remote-machine
Please open this ticket again, so I do not have to create a new ticket.

**Comment by tyrionlannistar** [comment]
I solved the issue: The docker extension was interfering with the remote-container extension. After uninstalling the docker extension, it is possible to attach visual studio code to a running docker on a remote host.

@chrmarti I do not understand your concept of closing tickets, before an issue is solved.

**Comment by chrmarti** [comment]
Sorry about that, I thought the question was answered. I'm surprised the Docker extension caused this. let me know if you have additional insights on how or why this happened.
