### ISSUE TITLE
Vscode keeps restoring auto forwarded ports in my Docker Container

### ISSUE THREAD

**Issue by TurboGofre** [microsoft/vscode-remote-release#4843]
Vscode keeps restoring Auto forwarded ports on reload or restart despite "remote.restoreForwardedPorts" is set to false on user, remote and workspace. As my Metals server use a random one each session, I end up with dozens of forwarded ports that I need to remove manually.

- VSCode Version: 1.55.0
- Local OS Version: Windows 10 20H2
- Remote OS Version: openSUSE Leap 15.2
- Remote Extension/Connection Type: Docker
- Docker Image OS: Debian 10 (Buster)
- Extension : Metals

Steps to Reproduce:

1. Open my workspace. Port is auto forwarded for Metals server
![image](https://user-images.githubusercontent.com/19334022/113918083-4a4e9880-97e2-11eb-804b-d5955e448c81.png)
2. Close and reopen vscode workspace or use reload window command
3. A new port is forwarded (as Metals get a random one each time) as well as the old one
![image](https://user-images.githubusercontent.com/19334022/113918962-5424cb80-97e3-11eb-8a0b-01b3dcec3e67.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by alexr00** [comment]
Auto forwarded ports should never be restoring. Can you share a screenshot of the Ports view when it has many of these wrongly restored ports?

**Comment by TurboGofre** [comment]
Hello @alexr00.

Here is the screenshot you asked for.
I used the "reload window" command on my workspace 5 times. Result :
![image](https://user-images.githubusercontent.com/19334022/114049893-1e87ed00-988c-11eb-81a8-db1d6d9ca2c0.png)

Best regards

**Comment by alexr00** [comment]
Thanks @TurboGofre.

@chrmarti Most of those ports are coming from the Remote Containers extension calling `openTunnel`. Do you have any ideas as to why the extension would be doing that?

**Comment by chrmarti** [comment]
@TurboGofre Are you using a devcontainer.json to create the container or are you attaching to an existing container?

When attaching we remember the forwarded ports in a local configuration file. Maybe that's feature we need to remove now.

**Comment by alexr00** [comment]
@chrmarti if you are iffy about removing the feature entirely, then you could turn it on/off based on whether auto forwarding is enabled.

**Comment by TurboGofre** [comment]
Hello @chrmarti. Exactly, you are right I'm attaching to an existing container. Maybe I should give a try to devcontainer.json

**Comment by chrmarti** [comment]
@alexr00 It seems auto-forwarding solves the same problem in a simpler (for the user) way. I'll remove the tracking of forwarded ports with the config file. Thanks.
