### ISSUE TITLE
User not shown as logged in with `who` or `users` command when connecting with Remote SSH

### ISSUE THREAD

**Issue by mdgilene** [microsoft/vscode-remote-release#4846]
- VSCode Version: 1.55.0
- Local OS Version: Windows 10
- Remote OS Version: Centos 7
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to remote server with remote SSH
2. Execute `who` or `users` command and see the user used to establish the remote ssh connection is not listed.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by roblourens** [comment]
I think this is because the SSH connection does not have a pty. I don't think there is anything i can do to help with this, but am open to suggestions, sorry.
