### ISSUE TITLE
"userEnvProbe" does not handle exported bash function correctly

### ISSUE THREAD

**Issue by range3** [microsoft/vscode-remote-release#4848]
- VSCode Version: 1.55.0
- Local OS Version: Windows 10 Home 2004 build 19041.867
- Remote OS Version: debian 10
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open an empty folder with VSCode
2. Remote-Containers: Add Development Container Configuration Files > C++ > debian-10
3. Add  "userEnvProbe": "interactiveShell" to devcontainer.json 
4. Remote-Containers: Rebuild and Reopen in Container
5. Add an user defined bash function to /home/vscode/.bashrc for example, 
```bash
_test_func() {
  echo test
}
export -f _test_func
```
6. Developer: Reload Window
7. Reopen the terminal and then get errors.
```bash
bash: _test_func: line 1: syntax error: unexpected end of file
bash: error importing function definition for `_test_func'
bash: _test_func: line 1: syntax error: unexpected end of file
bash: error importing function definition for `_test_func'
vscode ➜ /workspaces/user-env-probe $ env
"'@><=;|&(
BASH_FUNC__test_func%%=() {  echo "test"
SHELL=/bin/bash
LSCOLORS=Gxfxcxdxdxegedabagacad
...
BASH_FUNC__test_func%%=() {  echo "test"
}
_=/usr/bin/env
vscode ➜ /workspaces/user-env-probe $ 
```
The first two lines of output in /usr/bin/env are weird.
If set "userEnvProbe": "none", this error will not occur.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by chrmarti** [comment]
This is a problem with the extension not handling multiline environment variables. We are using `printenv` to read the environment variables and that uses newline as the separator between two variables, so we can't tell when a newline belongs to the variable value. Some versions of `printenv` support the `-0` option to use the NUL character, but not all versions do (e.g., Alpine's BusyBox does not).
