### ISSUE TITLE
When the browser disconnects, VS Code kills the entire extension host (and therefore all running extensions)

### ISSUE THREAD

**Issue by hakimehmordadi** [microsoft/vscode-remote-release#4849]
Hi there! 👋

I created a vs-code extension for code sharing. For running extension I'm using code-server. I'm using web socket for real-time sending and receiving messaged (In this case users mouse position or text highlights).

I open every files which I want to share in browser as tabs.

BUT

When I closed all tabs, my extension goes deactivated, web socket is stopped and I got error.

- VS Code Version:1.55.0
- OS Version: amazon_linux:2

Steps to Reproduce:

1- Run code-server with ( ./code-server ) command
2- Copy my extension into ( .local/code-server/extensions ) folder
3- Open two browser (chrome/firefox) with (http://localhost:8080) address
4- Open share folder in browsers
5- Open files inside share folder as tab in browsers

Does this issue occur when all extensions are disabled?: This error goes my extension disabled

**Expected**
When user1(chrome) select part of text, user2(firefox) should see that in it's own browser with different color, this should happens for user2 (Like micro-soft live share)

**Actual**
Users can select code and other user can see selection of other users BUT when closing all files error accures

**Screenshot**

![2021-04-06T14_35_391](https://user-images.githubusercontent.com/31950758/113812761-e5645580-9783-11eb-8eec-6ae9385c550d.png)
![2021-04-06T14_35_39](https://user-images.githubusercontent.com/31950758/113812777-eac1a000-9783-11eb-9aae-c65e0ee7b9da.png)
![2021-04f-06T14_35_39](https://user-images.githubusercontent.com/31950758/113812778-eac1a000-9783-11eb-8395-397f21ec015b.png)

**Comment by chrmarti** [comment]
Sounds like an problem with https://github.com/cdr/code-server. Please open an issue for that repository.

**Comment by hakimehmordadi** [comment]
I created issue at the first time for code-server, they said it is the vs-code issue, then i created the issue for code-server, they you said it is code-server error, 

Okay, what is it? Not code-server nor vs-code  doesn't responsible for the issue?  It doesn't make sense, there is issue but doesn't responsible for fixing it 

AND

Without fixing, you close the issue ? What is this?????????????????????

**Comment by hakimehmordadi** [comment]
I created issue at the first time for code-server, they said it is the
vs-code issue, then i created the issue for code-server, they you said it
is code-server error,

Okay, what is it? Not code-server nor vs-code doesn't responsible for the
issue? It doesn't make sense, there is issue but doesn't responsible for
fixing it

AND

Without fixing, you close the issue ? What is this?????????????????????

**Comment by chrmarti** [comment]
We are not the authors of code-server. For us to investigate we need steps to reproduce the problem using VS Code without code-server.
