### ISSUE TITLE
It's confusing to have extension pack installed remotely but child extensions installed locally

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-remote-release#485]
Refs:  #466

![image](https://user-images.githubusercontent.com/35271042/58502602-adc60480-813b-11e9-90cc-9a795ff43d5d.png)

I tried installing a theme extension pack ([Tyriar Theme Pack](https://marketplace.visualstudio.com/items?itemName=Tyriar.theme-pack)) and the extension pack was installed remotely but the child extensions are UI extensions, so they were installed locally. 

I find this really confusing and expected to find the theme extension pack installed locally because they're one package (in my head). The main question I have is: what is the point of having a theme extension pack installed remotely when themes are installed locally? What benefit is that to the user?

**Comment by sandy081** [comment]
I see your point which is also thought about. As said, a pack is considered as workspace extension unless explicitly defined as UI kind. This rule is same for all extensions. 
So, if a pack is ui pack it has to be tagged as UI kind.
