### ISSUE TITLE
VSCode Remote extension doesn't expose Docker ports correct

### ISSUE THREAD

**Issue by HenrikBach1** [microsoft/vscode-remote-release#4858]
- VSCode Version: 1.56.0
- Local OS Version: Microsoft Windows 10 Pro - 10.0.19042
- Remote OS Version: Debian GNU/Linux 10 (buster)
- Remote Extension/Connection Type: Docker: 1.11.0/20.10.5, build 55c4c88 - WSL: 0.54.6

Steps to Reproduce:

1. Run ./Server.py with Python 3 inside vscode and its associated devcontainer:
```
vscode ➜ /workspaces/Python-VSC-dev-containers/python (main ✗) $  /usr/bin/env /usr/local/bin/python /home/vscode/.vscode-server-insiders/extensions/ms-python.python-2021.3.680753044/pythonFiles/lib/python/debugpy/launcher 41927 -- /workspaces/Python-VSC-dev-containers/python/Network/Server.py 
```
Ports associated with above execution:
![image](https://user-images.githubusercontent.com/10473382/114140430-8718ad80-9910-11eb-94ba-4f078801be31.png)

2. Run ./Client.py with Python 3 in vscode devcontainer:
```
vscode ➜ /workspaces/Python-VSC-dev-containers/python/Network (main ✗) $ python3 ./Client.py 
Client started...
Connecting to ef48b6e86a0b:9999
Thank you for connecting

vscode ➜ /workspaces/Python-VSC-dev-containers/python/Network (main ✗) $ ./Client.py 
Client started...
Connecting to ef48b6e86a0b:9999
Thank you for connecting
```
```
C:\Users\henri>netstat -a | find "9999"
  TCP    0.0.0.0:9999           DESKTOP-VC184G4:0      LISTENING
  TCP    172.17.192.1:9999      DESKTOP-VC184G4:56125  ESTABLISHED
  TCP    172.17.192.1:56125     DESKTOP-VC184G4:9999   ESTABLISHED
  TCP    [::]:9999              DESKTOP-VC184G4:0      LISTENING
```

3. Run ./Client.py with Python 3 in terminal on localhost:
```
henri@DESKTOP-VC184G4 ~
$ cd ~/Projects/Python-VSC-dev-containers/python/Network

henri@DESKTOP-VC184G4 ~/Projects/Python-VSC-dev-containers/python/Network
$ python
python.exe      python3.6       python3.6m.exe  pythonw.exe

henri@DESKTOP-VC184G4 ~/Projects/Python-VSC-dev-containers/python/Network
$ python --version
Python 3.9.1

henri@DESKTOP-VC184G4 ~/Projects/Python-VSC-dev-containers/python/Network
$ python ./Client.py
Client started...
Connecting to DESKTOP-VC184G4:9999

```

Does this issue occur when you try this locally and all extensions are disabled?: N/A

Above files/project is attach to this post: 
[python.zip](https://github.com/microsoft/vscode-remote-release/files/6283730/python.zip)

**Comment by HenrikBach1** [comment]
Even though I found that a service on my (development) machine was using port 9999 and in that respect changed port 6666 (which isn't used at my machine, the problem still persists.

nmap shows:
```
$ nmap DESKTOP-VC184G4
Starting Nmap 7.80 ( https://nmap.org ) at 2021-04-11 09:31 ope
Nmap scan report for DESKTOP-VC184G4 (172.17.192.1)
Host is up (0.0013s latency).
Other addresses for DESKTOP-VC184G4 (not scanned): fe80::b993:1034:7194:7178 fe80::51bc:3d66:215a:6d05 fe80::d0b6:82d3:c461:bcd5 fe80::d886:222b:10e:ec74 172.17.16.1 169.254.188.213 192.168.0.89
Not shown: 992 closed ports
PORT     STATE SERVICE
135/tcp  open  msrpc
139/tcp  open  netbios-ssn
445/tcp  open  microsoft-ds
2179/tcp open  vmrdp
3389/tcp open  ms-wbt-server
6000/tcp open  X11
6666/tcp open  irc
9999/tcp open  abyss

Nmap done: 1 IP address (1 host up) scanned in 1.83 seconds
```

Trying to connect to the server through a Cmd-shell or Cygwin-bash-shell both gives:
```
C:\Users\henri\OneDrive - Københavns Erhvervsakademi\Private\Projects\Python-VSC-dev-containers\python\Network>python ./UDPClient.py
Connecting to DESKTOP-VC184G4:6666
Traceback (most recent call last):
  File "C:\Users\henri\OneDrive - Københavns Erhvervsakademi\Private\Projects\Python-VSC-dev-containers\python\Network\UDPClient.py", line 23, in <module>
    (jarvisMsg, serverAddr) = clientSocket.recvfrom(BUFFER_SIZE)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

**Comment by chrmarti** [comment]
Make sure the client is connecting to localhost / 127.0.0.1. The forwarded port is only available on the local network interface.

**Comment by chrmarti** [comment]
@alexr00 The screenshot of the Ports view above shows the port 9999 twice, once with and once without process. Does that make sense or is this a bug?

**Comment by alexr00** [comment]
Having port 9999 twice is a bug. I'll see if I can repro.

**Comment by alexr00** [comment]
I'm not able to repro the double port issue. I'll keep an eye out for it though.

**Comment by HenrikBach1** [comment]
I don't have any success with the clients connecting to the localhost/127.0.0.1. Neither, when running them inside the DevContainer or outside from a terminal. Either the network interface rejects the connections or they just hangs.

With respect to duplicates of port 9999 (in the TCP example), I can't remember whether I somehow manually designated that port, too (if that is possible in VSCode).

**Comment by chrmarti** [comment]
If the client can't connect to the server using localhost when both are running inside the container, the server must be listening on a different network address. Try letting the server listen on localhost.

**Comment by HenrikBach1** [comment]
What puzzles me is that the .devcontainer/devcontainer.json file exposes/forwards port 6666, but it can't be seen on the localhost, but only in the container:

```
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	"forwardPorts": [6666],
```

I used the python/Network/UDP*.py server/client example.

/Henrik

**Comment by chrmarti** [comment]
We only forward TCP connections, but not UDP.

Is your local machine Windows with WSL2? Or Linux? (Looking at the above, I see Windows and Linux command prompts.)

**Comment by HenrikBach1** [comment]
Thank you.

Sorry for the confusion. My fault.

Previously it was a Windows with WSL 2 for Docker (Docker Desktop) to function and maybe Cygwin bash for testing external behavior towards the container.

Now (the last post) is a Fedora Linux with Docker CE.

I'll try to test TCP.

**Comment by HenrikBach1** [comment]
Testing TCP gives me these results, depending on trying to connect to loopback-address (127.0.0.1) or via hostname through socket:

In DevContainer:
```
vscode ➜ /workspaces/python/Network $ netstat -at | grep 6666
tcp        0      0 6265657bab1c:6666       0.0.0.0:*               LISTEN     

# Trying to connect to loopback-address (127.0.0.1):
vscode ➜ /workspaces/python/Network $ ./TCPClient.py 
Connecting to '('127.0.0.1', 6666)'
Traceback (most recent call last):
  File "/workspaces/python/Network/./TCPClient.py", line 20, in <module>
    sock.connect(server_address)
ConnectionRefusedError: [Errno 111] Connection refused
...
# Trying to connect via hostname through socket:
vscode ➜ /workspaces/python/Network $ python ./TCPClient.py 
Connecting to '('6265657bab1c', 6666)'
Sending: 'This is the message.  It will be repeated.'
Received: 'This is the message.  It will be repeated.'
Socket closed
...
vscode ➜ /workspaces/python/Network $ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.2  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:ac:11:00:02  txqueuelen 0  (Ethernet)
        RX packets 515  bytes 1745567 (1.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 395  bytes 61018 (59.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 5260  bytes 1068649 (1.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5260  bytes 1068649 (1.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vscode ➜ /workspaces/python/Network $ 
```

On localhost no forwarded port is available:
```
[sad@localhost ~]$ netstat -at | grep 6666
[sad@localhost ~]$ 
```

Although VSCode claims so: 
![Screenshot from 2021-05-31 16-15-17](https://user-images.githubusercontent.com/10473382/120206481-88d56200-c22b-11eb-9c93-0867fa45a55d.png)

I've attached latest files to this post.
[python-2020-05-31-1618.tar.gz](https://github.com/microsoft/vscode-remote-release/files/6570828/python-2020-05-31-1618.tar.gz)

**Comment by chrmarti** [comment]
The screenshot indicates that 6666 is forwarded as localhost:6667. Could you check if that is working?

**Comment by HenrikBach1** [comment]
I did that. None of them are working:

```
[sad@localhost ~]$ netstat -at | grep 6667
[sad@localhost ~]$ netstat -at | grep 6666
[sad@localhost ~]$ 
```

**Comment by HenrikBach1** [comment]
Bump

**Comment by alexr00** [comment]
I'm not able to reproduce this issue. @HenrikBach1 do you still see it?
