### ISSUE TITLE
[FEATURE REQUEST] Remote - SSH: Support for settings sync of the SSH Targets

### ISSUE THREAD

**Issue by ole1986** [microsoft/vscode-remote-release#4859]
Since my remote machine list is growing but I do need to switch between several computer (>=3) it can be hard to reconfigure the SSH Targets.

Especially the directories of such connection are also going be a lot but always differ from other machines.

Is there any chance to include this into the "Settings sync" feature?

**Comment by bamurtaugh** [comment]
cc @sandy081 Thoughts? This almost sounds related to https://github.com/microsoft/vscode/issues/113774, although I'm not sure if the SSH config file falls under the category of "custom user files from extensions."

**Comment by roblourens** [comment]
Maybe if we did microsoft/vscode#113774 I would consider it, but I'm not that enthusiastic about it.
