### ISSUE TITLE
How to fetch the remote connection on the server side ?

### ISSUE THREAD

**Issue by Riqzz** [microsoft/vscode-remote-release#4862]
Hello, I use command "w" on server to check users who log in remotely, but I cannot fetch the users who are connected through vscode remotely. Isn't vscode connected using ssh? But why can't I see.

**Comment by Riqzz** [comment]
And  how can I get the information who connect

**Comment by bamurtaugh** [comment]
I believe this is a dupe of https://github.com/microsoft/vscode-remote-release/issues/4846?

**Comment by Riqzz** [comment]
I have solved it. All connected users can be found at `/dev/pts/`
