### ISSUE TITLE
When WSL connected, On the windows side, clicking "create a launch.json file" option does nothing

### ISSUE THREAD

**Issue by NickVH-MS** [microsoft/vscode-remote-release#4863]
I am connected to WSL2 Ubuntu 18.04 , which is containing a particular tented large project.

When I click "Create a launch.json file", or really anything else under the debug menu, nothing happens at all. No opportunity to paste my GDB connect stuff. Very frustrating.

**Comment by bamurtaugh** [comment]
Hi @NickVH-MS - I just tried creating a launch.json using WSL2 Ubuntu 18.04 via Remote-WSL, and I was able to generate the file:

![image](https://user-images.githubusercontent.com/25310137/114788125-c93d5700-9d35-11eb-9f01-326d6bb8b439.png)

![image](https://user-images.githubusercontent.com/25310137/114788153-d5291900-9d35-11eb-8114-579b252724c5.png)

Do you see any output from **Remote WSL: Show Log**? Do you only experience this issue on this specific project, or is it when using Remote-WSL in general?
