### ISSUE TITLE
Resolver error: Error: SSH user name cannot include the character " - GCP Connection

### ISSUE THREAD

**Issue by aksg87** [microsoft/vscode-remote-release#4868]
- VSCode Version:
Version: 1.56.0-insider (Universal)
Commit: 01466cf692c3e54f0eeb82ef0539a42391f185de
Date: 2021-04-12T05:14:36.459Z (14 hrs ago)
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

- Remote Extension/Connection Type: SSH/Docker/WSL 
SSH

Steps to Reproduce:

1. Connect to a GCP instance with the flag `--dry-run` which will send the SSH terminal command generated by GCP back.

`ssh -t -i /Users/firstname.lastname/.ssh/google_compute_engine -o CheckHostIP=no -o HostKeyAlias=compute.901506291484525092 -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/Users/firstname.lastname/.ssh/google_compute_known_hosts -o ProxyCommand="/Users/firstname.lastname/miniconda3/bin/python3 -S /Users/firstname.lastname/Downloads/google-cloud-sdk/lib/gcloud.py beta compute start-iap-tunnel tn-g-pytorch-xqcznmxl %p --listen-on-stdin --project=tl-45hh4agf37eb5pnc92cnt --zone=us-central1-a --verbosity=warning" -o ProxyUseFdpass=no 'firstname_lastname_company_com@compute.901506291484525092`

2. Confirm this command works in the terminal by pasting it into your terminal. You will need to add quotes around -o ProxyCommand parameters for this to work correctly.
3.  In VSCode, try to connect to a GCP instance using the same SSH terminal command 
4. You will see an error as follows. This seems like an issue with the way VSCode is parsing this valid SSH command.

```
...
[15:19:40.676] Setting up SSH remote "compute.901506291484525092"
[15:19:40.681] Resolver error: Error: SSH user name cannot include the character "
```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Seems like your command is missing a quote, maybe that is the issue.

**Comment by roblourens** [comment]
Actually I think you just want to remove the quote from the command that you paste into vscode.

We are not interpreting that command as a shell, and quotes don't get removed. The problem is that `'` is a valid ssh username character, but it's hard for us to escape it correctly for all shells, so I have just banned it.

**Comment by aksg87** [comment]
Thanks for the suggestions! I ended up creating the host file manually
which solves the issue.
