### ISSUE TITLE
Require service when dockerComposeFile is set in devcontainer.json

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-remote-release#487]
https://github.com/microsoft/vscode-remote-release/issues/475

To prevent 
![Screen Shot 2019-05-28 at 11 27 50 AM](https://user-images.githubusercontent.com/3672607/58503224-16fa4780-813d-11e9-9a47-a737a9e3ff2c.png)
when a user has a devcontainer.json with `dockerComposeFile` but no `service` property, I suggest adding 

```
  "dependencies": {
    "dockerComposeFile": ["service"]
  }
```

to our json schema for devcontainer.json, if we support dependencies

**Comment by chrmarti** [comment]
The part of the schema with `"dockerComposeFile"` has `"service"` as a required property. Shouldn't that be enough? https://github.com/microsoft/vscode/blob/6964233e81c68f5a5f34e7eb1da0836e1d539f14/extensions/configuration-editing/schemas/devContainer.schema.json#L117 /cc @aeschli

**Comment by aeschli** [comment]
@chrmarti `Require` only works for properties in objects. Looks like dockerComposeFile isn't an object.
For arrays theres `contains`
```json
{
   "type": "array",
   "contains": {
     "type": "number"
   }
}
```

**Comment by chrmarti** [comment]
@aeschli `"dockerComposeFile"` and `"service"` are both properties on the same object (or fragment of an object). Shouldn't that work then?

**Comment by aeschli** [comment]
Ah, I believe what's missing is `type: 'object'` on dockerComposeFile

**Comment by chrmarti** [comment]
Adding `"type": "object"` where missing. An error was shown also without that, the decoration might be a little subtle. Closing for verification.
