### ISSUE TITLE
High CPU usage from multiple windows when upgrading server

### ISSUE THREAD

**Issue by 4wrxb** [microsoft/vscode-remote-release#4875]
High-line is that when I resume a session where an update to the SSH Server is required each window that was on that remote host keeps trying to connect which is slowing the install. This can be compounded by "remote.SSH.localServerDownload" since the added load slows the SCP client's copy during install.

- VSCode Version: 1.55.2
- Local OS Version: Windows 10 Enterprise 1909
- Remote OS Version: SLE12v5
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Update VS Code (e.g. "restart to update") with multiple windows open on the remote host.
2. After VS Code is updated all windows attempt to connect to the host, detect an install is required, and windows other than the active install enter a loop waiting for the install to complete.
3. This looping process has no time-out or other throttle resulting in high CPU usage form the render process slowing the system.
 
Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by roblourens** [comment]
> This looping process has no time-out or other throttle resulting in high CPU usage form the render process slowing the system.

The retry loop does not do any substantial work, it's mostly waiting. Not clear where this CPU usage is coming from.

**Comment by 4wrxb** [comment]
Apologies in the delay, in my spare time I have attempted to capture meaningful performance data, but this is proving difficult.

From what I can observe the rendering process seems to be the most consistent high-cpu, but the number of SSH processes launched in a short period is extreme (>100/minute from just 4 windows).

Ultimately this results in one of two errors from VS Code (I've also seen prompts to restart unresponsive windows etc):

1) A "timeout" from waiting windows
2) A "ssh install not found" error from either the waiting **or installing** window

The timeout error has resulted in my session being lost and the workspace being opened without any files (including unsaved files) previously open. The ssh not found error can be corrected by restarting all VS Code windows. But if the window that encountered the error was the one updating vscode-server then the entire process is at risk of repeating since the install (over scp) must begin again.

**Comment by roblourens** [comment]
Could you show me the logs from the Remote-SSH output channel when this happens?

**Comment by 4wrxb** [comment]
Something about trying to reproduce this goes significantly faster than a real install... even when I delete the ~/.vscode-server/bin area and switch hosts (all our disks, including home, are NFS). The 'waiting' windows then simply timeout normally after a few retries (seems to be between when the server installs and starts). I cannot reproduce the behavior that causes issues with the install itself.

Regardless, here's the logs from two retries in one window parallel to the SCP re-install log. From what I can recall, the retrying log is representative of the misbehaving windows.

[logs.zip](https://github.com/microsoft/vscode-remote-release/files/6438444/logs.zip)

note: due to the sensitivity of the environment I have replaced some strings and removed the remote server's env report.

**Comment by roblourens** [comment]
It should have kept retrying...

I assume this is from you replacing this line? `Install terminal quit with output: *******************************************************` It seems like the extension failed to parse the output but from the log, I can't figure out why, it looks well formed. But I have seen this with windows in the past where the output contains some terminal escape sequences or invisible characters that make the parsing fail.

**Comment by 4wrxb** [comment]
That line is as is from the log, but it only happened when I was attempting to re-produce by deleting the $HOME/.vscode-server/bin directory. I tried twice to get a "normal" install to occur, but something was still speeding up the install.

In the new-install case the local download + upload + install process takes longer than two retries (and the waiting windows continue retrying until things start failing). When I first reported this one window's retry count was in the high 20's (based on the task toast in the bottom right of the window).

**Comment by 4wrxb** [comment]
FYI with the latest release things went a little differently. Possibly because I closed all running programs prior to re-opening VS code after the update (and had only 3 windows going).

This time both "waiting" windows failed on their retry shortly before the SCP finished. Once these windows were in the connection failure state they calmed down and install complete successfully.

This failure state is also cleaner that my previous updates from a session restore perspective because it allows the window to be reloaded.
[logs2.zip](https://github.com/microsoft/vscode-remote-release/files/6464130/logs2.zip)

Circling back to my original point however, it seems extreme that these waiting windows are making so many SSH connections (7 successful connections in 16 seconds) and I suspect that has been causing my issues. In a normal reconnect case the retry has a more reasonable delay. Exponential back-off may not be right since Remote - SSH knows the install will complete, but surely some rate-limit would help here.

**Comment by roblourens** [comment]
There is something weird going on, but I don't know what it is. Your retry window didn't even retry that many times. It's supposed to try up to 30 times but it randomly stopped after a few. It looks like the reconnecting ssh process either crashed or terminated early for some reason. I also still don't think that the reconnecting windows are contributing that much load. I think the main issue is just some flakiness somewhere in your setup or server.
