### ISSUE TITLE
"SyntaxError: Unexpected end of JSON input" building container

### ISSUE THREAD

**Issue by clarktlaugh** [microsoft/vscode-remote-release#4882]
Issue Type: <b>Bug</b>

Run "Remote-Containers: Add  Development Containers Configuration Files"
Select "Go" for the container type
Run "Remote-Containers: Rebuild and Reopen in Container"

Expected no errors.

Received:
```
Successfully tagged vsc-devcontainertest-eaf895d31859fdf487f323f0b6162f2e:latest
[2021-04-14T19:11:23.642Z] [PID 17806] [3970 ms] Start: Run: docker inspect --type image vsc-devcontainertest-eaf895d31859fdf487f323f0b6162f2e
[2021-04-14T19:11:24.083Z] [PID 17806] [4411 ms] SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at nf (/home/clarkl/.vscode/extensions/ms-vscode-remote.remote-containers-0.166.1/dist/extension/extension.js:202:1206)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async sc (/home/clarkl/.vscode/extensions/ms-vscode-remote.remote-containers-0.166.1/dist/extension/extension.js:202:944)
	at async sD (/home/clarkl/.vscode/extensions/ms-vscode-remote.remote-containers-0.166.1/dist/extension/extension.js:238:1129)
	at async ZV (/home/clarkl/.vscode/extensions/ms-vscode-remote.remote-containers-0.166.1/dist/extension/extension.js:224:10014)
	at async OP (/home/clarkl/.vscode/extensions/ms-vscode-remote.remote-containers-0.166.1/dist/extension/extension.js:224:6631)
	at async AV (/home/clarkl/.vscode/extensions/ms-vscode-remote.remote-containers-0.166.1/dist/extension/extension.js:205:9612)
```

This happens 100% of the time.

I have run the `docker inspect` command manually and run the resulting JSON output through JSONLint and the output is valid.

Docker version info:
```
Client:
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        cd8016b6bc
 Built:             Fri Feb  5 15:56:39 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       bd33bbf
  Built:            Fri Feb  5 15:58:24 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

Extension version: 0.166.1
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:02.931Z)
OS version: Linux x64 5.8.0-49-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (2 x 1497)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 1|
|Memory (System)|7.75GB (0.99GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 7feda2a5-9ea5-454b-81be-466ee5ce5a28|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|budgie-desktop|
|XDG_CURRENT_DESKTOP|Budgie:GNOME|
|XDG_SESSION_DESKTOP|budgie-desktop|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30283811
wslfolderdoc:30282074
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by chrmarti** [comment]
Could you attach the JSON?

**Comment by clarktlaugh** [comment]
[docker-inspect.json.txt](https://github.com/microsoft/vscode-remote-release/files/6325011/docker-inspect.json.txt)

**Comment by chrmarti** [comment]
That looks good, JSON.parse also accepts it. Maybe there is some additional output when that command runs in the extension. Could you try with the most recent version of Docker?

**Comment by clarktlaugh** [comment]
It worked with the latest version installed via apt (https://docs.docker.com/engine/install/ubuntu/):
```
$ docker version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:28 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by clarktlaugh** [comment]
The other detail I didn't mention (because I just realized it).... my previous version of docker was installed as a snap.  I know I have experienced various issues with snap-installed things vs non-snap things, so maybe that's a culprit.

**Comment by chrmarti** [comment]
Thanks. Closing as fixed upstream.
