### ISSUE TITLE
Why is the git clone done with --depth 1 ?

### ISSUE THREAD

**Issue by gparmeggiani** [microsoft/vscode-remote-release#4883]
I think this is the cause for #3294

Also, if I try to run `git pull --unshallow` as a workaround I get the following error:
`fatal: Unable to create '/workspaces/repository/.git/shallow.lock': File exists.`

Also related to #4619

**Comment by chrmarti** [comment]
We do this for efficiency followed by a `git pull --unshallow` in the background afterwards. While the unshallow is running we can already read the devcontainer.json and build the Dockerfile or download the image.

https://github.com/microsoft/vscode-remote-release/issues/4619#issuecomment-793486531 will address the issue of not showing all branches.

Are there any issues beyond that? (E.g., you shouldn't have to run unshallow manually, maybe check your log for errors `F1` > `Remote-Containers: Show Log`.

**Comment by gparmeggiani** [comment]
Thanks for the reply. I missed the part where you do `git fetch --unshallow`
To get my branches back I had to
```
git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git pull
```
I hope #4619 will fix the situation.
