### ISSUE TITLE
Auto open multiple browser windows unexpectedly in remote dev mode

### ISSUE THREAD

**Issue by soulwu** [microsoft/vscode-remote-release#4886]
- VSCode Version: 1.55.2
- Local OS Version: Darwin x64 20.3.0
- Remote OS Version: Linux version 3.10.0-327.ali2019.alios7.x86_64 (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) )
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Init a react app by cra: `yarn create react-app test-app`
2. Start development: `cd test-app && yarn start`

Then vscode will open multiple browser window with several different random port number like:
- http://localhost:60559/
- http://localhost:60557/
- http://localhost:60558/
- ...

and with the correct port window: http://localhost:3000/

Expected behavior is: Only open one window with url 'http://localhost:3000/'

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by alexr00** [comment]
Please share any `remote.*` settings you have set.

**Comment by soulwu** [comment]
> Please share any `remote.*` settings you have set.

### `Remote - SSH` plugin config
![image](https://user-images.githubusercontent.com/1633638/115174077-2735ba00-a0fb-11eb-90bf-fcf80ec0f9d0.png)
![image](https://user-images.githubusercontent.com/1633638/115174147-4f251d80-a0fb-11eb-9a40-1825dfc0d65c.png)

### `remote.*` config on my local machine
![image](https://user-images.githubusercontent.com/1633638/115174533-002bb800-a0fc-11eb-8fc9-cbdd9afbfac8.png)

**Comment by alexr00** [comment]
Can you share the value of `remote.portsAttributes`?

**Comment by soulwu** [comment]
> Can you share the value of `remote.portsAttributes`?

My `remote.portsAttributes` is empty

![image](https://user-images.githubusercontent.com/1633638/115215398-09d21180-a136-11eb-9305-652410b74c20.png)

**Comment by alexr00** [comment]
With your current config, I can't repro that browser windows are opening. Does the issue reproduce if you disable all extension other than the required Remote SSH extension?

**Comment by alexr00** [comment]
Also, can you share the value of `remote.portsAttributes` in your user settings? https://github.com/microsoft/vscode-remote-release/issues/4886#issuecomment-822327385 looks like it's your workspace settings.

**Comment by soulwu** [comment]
> Also, can you share the value of `remote.portsAttributes` in your user settings? [#4886 (comment)](https://github.com/microsoft/vscode-remote-release/issues/4886#issuecomment-822327385) looks like it's your workspace settings.

`remote.portsAttributes` in my user settings is empty too.

**Comment by soulwu** [comment]
> With your current config, I can't repro that browser windows are opening. Does the issue reproduce if you disable all extension other than the required Remote SSH extension?

I disabled all plugins both in local and remote except `Remote - SSH`, `Remote -SSH: Editing Configuration Files` and `Chinese (Simplified) Language Pack for Visual Studio Code`

I ran `yarn start` in an app created by `create-react-app` without any modification

Then two browser windows are opened with port `3000` and `60560`


https://user-images.githubusercontent.com/1633638/115333867-f58d2380-a1cc-11eb-95ea-85da5e385d62.mov

**Comment by alexr00** [comment]
This appears to be coming from `yarn start`, not from VS Code.
