### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by xinyuluo** [microsoft/vscode-remote-release#4887]
- Issue Type: `Performance`
- Extension Name: `remote-ssh`
- Extension Version: `0.65.3`

- OS Version: `Darwin x64 20.3.0`
- VS Code version: `1.55.2`

[ms-vscode-remote.remote-ssh-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-remote-release/files/6316301/ms-vscode-remote.remote-ssh-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by roblourens** [comment]
Do you have a really large ssh config? Seems that we spend too much time parsing it. We do this more times than necessary, there is an issue for that.
