### ISSUE TITLE
Remote - Containers - Incorrect command generated on Windows with Linux remote docker host

### ISSUE THREAD

**Issue by Roang-zero1** [microsoft/vscode-remote-release#489]
- VSCode Version: 1.35.0-insider (user setup)
- Local OS Version: Windows 10 Pro 17134
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Set up Docker on Ubuntu and enable remote access through port 2375
2. Set up Docker for Windows Desktop (without enabling Hypervisor)
2. Install VSCode Insider and Remote dev extension
3. Set DOCKER_HOST environment variable
4. Clone the https://github.com/Microsoft/vscode-remote-try-python repository
5. Modify devcontainer.json (https://code.visualstudio.com/docs/remote/containers-advanced#_using-devcontainerjson-to-work-with-a-remote-dev-container)
6. Open Folden in Container
7. Build succeeded but run command is incorrect:
`docker run -a STDOUT -a STDERR -p 127.0.0.1:9000:9000 --mount src=remote-workspace,dst=/workspace,type=volume,volume-driver=local -v C:\Users\lbr\.gitconfig:/root/.gitconfig -l vsch.quality=insider -l vsch.local.folder=c:\Users\lbr\Documents\VersionControl\vscode-remote-try-python -l vsch.remote.devPort=9753 vsc-vscode-remote-try-python-6ba2a80726410b4e361ef2fe1406d8bc /bin/sh -c echo Container started ;  while sleep 1; do :; done`

If I fix the issues with the command:
1. `-v C:\Users\lbr\.gitconfig:/root/.gitconfig` replaced with `-v /root/.gitconfig`
2. `-c echo Container started ;  while sleep 1; do :; done` replaced with `-c "echo Container started ;  while sleep 1; do :; done"`
all subsequent runs are successful.

Working command: `docker run -a STDOUT -a STDERR -p 127.0.0.1:9000:9000 --mount src=remote-workspace,dst=/workspace,type=volume,volume-driver=local -v /root/.gitconfig -l vsch.quality=insider -l vsch.local.folder=c:\Users\lbr\Documents\VersionControl\vscode-remote-try-python -l vsch.remote.devPort=9753 vsc-vscode-remote-try-python-6ba2a80726410b4e361ef2fe1406d8bc /bin/sh -c "echo Container started ;  while sleep 1; do :; done"`

Does this issue occur when you try this locally?: This is a remote only use case
Does this issue occur when you try this locally and all extensions are disabled?: This is a remote only use case, remote dev is the only enabled extension.

**Comment by Chuxel** [comment]
@chrmarti I can repro this too - I think this just happens to work on macOS because the pathing is the same which is where I'm guessing we've done the most testing here.  (And others that reported it working must have been too.) The first ":" in "C:" is tripping things up when it runs on Linux since there are two in the string. We may need a property to disable git config forwarding.

**Comment by chrmarti** [comment]
I'll use a Linux path to (hopefully) work around this without introducing a new property.

This needs more thought to properly fix. Having the gitconfig by default seems to be a good feature. Instead of mounting we could also copy the file, that would also work when using a remote Docker host.

**Comment by Chuxel** [comment]
> Having the gitconfig by default seems to be a good feature. 

Agreed!

**Comment by rebornix** [comment]
Considering the existence of #509, I think it's a verification-found.

**Comment by chrmarti** [comment]
#509 can be worked around by setting an empty `"workspaceMount"` property in the devcontainer.json. This one should be fixed independently. Closing again for verification.

Verifier: Set the `"workspaceMount"` property in the devcontainer.json to an empty string to avoid #509.

**Comment by chrmarti** [comment]
@joaomoreno Uncovered a case where setting `"workspaceMount"` to the empty string would not work. Workaround for that is to also set `"workspaceFolder"` (which might be needed anyway). Reopening for fixing this case.

**Comment by chrmarti** [comment]
Verification: Set `"workspaceMount"` to the empty string and do not set `"workspaceFolder"`. Verify that the created container does not mount the host folder (e.g., the window will fail to open the folder) by checking `docker exec <container-id> mount` from the host machine.

**Comment by roblourens** [comment]
Trying to verify but I don't understand what I'm looking for.

I did this

> Set "workspaceMount" to the empty string and do not set "workspaceFolder"

and am able to connect to the contain and open files as normal, but I am expecting to see the window fail to open the folder?

**Comment by roblourens** [comment]
And I see

`osxfs on /workspaces/vscode-remote-try-dotnetcore type fuse.osxfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)`

In the output of `docker exec <container-id> mount`

**Comment by roblourens** [comment]
Ok I stopped and deleted the container, tried again, and now I can't open the folder in the window, and the folder doesn't show up as mounted.
