### ISSUE TITLE
drag and drop remote files to macOS Finder

### ISSUE THREAD

**Issue by hzpc-joostk** [microsoft/vscode-remote-release#4895]
Issue Type: <b>Bug</b>

Downloading files from an SSH remote by dragging it from the VSCode file explorer doesn't work.

1. open a folder on SSH remote
1. (try dragging a local file from Finder to the remote; works)
1. try dragging a remote file from VSCode explorer to Finder
1. a file with expected name (and extension) appears
1. the file is empty

I expected the file to be copied including its contents.

Downloading using the `Download` option from VSCode explorer's context menu works though.

Extension version: 0.65.3
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 3.10.0-1062.1.2.el7.x86_64
Remote OS version: Linux x64 3.10.0-1062.1.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 6769468b-ce18-4d4f-b56c-3a014f473b17|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: linuxkweek1-proxy|
|OS|Linux x64 3.10.0-1062.1.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz (16 x 1958)|
|Memory (System)|125.87GB (90.49GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: linuxkweek1-proxy|
|OS|Linux x64 3.10.0-1062.1.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz (16 x 1958)|
|Memory (System)|125.87GB (90.49GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
wslfolderdoccf:30282075
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by isidorn** [comment]
We already have some issue that capture this, closing as duplicate and you cantry to find them by looking for the file-explorer tag either in this repo or the vscode one
Thank you
