### ISSUE TITLE
SSH Remote extensions are not shown on local client

### ISSUE THREAD

**Issue by juulie** [microsoft/vscode-remote-release#4896]
- VS Code Version:1.55.1
- OS Version:Chrome OS

Steps to Reproduce:

1. Connect to SSH server that has extensions pre installed
2. Note that even though connection has succeeded. The SSH:'ServerName" will show "No extensions found" in the Extensions View

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Can you please let me know how do you know that extensions are pre installed ?
