### ISSUE TITLE
Git clone uses --depth which causes issues and is inconvenient

### ISSUE THREAD

**Issue by leighmcculloch** [microsoft/vscode-remote-release#4901]
When using the `Remote-Containers: Clone Repository in Container Volume` (`remote-containers.openRepositoryInVolume`) command to clone a repository, and when choosing GitHub, the repository is cloned using the `--branch` and `--depth` options to perform a shallow clone. Using the depth option makes it much harder to interact with the repository at the command line because the `remote.origin.fetch` will be configured to only fetch the specified branch.

When using VSCode's built-in clone functionality without remote containers, it does not use these options, so it seems like the remote containers clone functionality has diverged from the VSCode clone functionality.

This difference in approaches where the remote containers uses a shallow clone is really inconvenient for me as a developer and that inconvenience is much worse than anytime I lose doing a full clone. 

The main pain point I find is that the `remote.origin.fetch` is configured differently in the clone repository for shallow clones. In a full clone it will be configured as `+refs/heads/*:refs/remotes/origin/*`, but in a shallow clone it will be configured as `+refs/heads/main:refs/remotes/origin/main`.

The impact that has is when I run `git checkout <branch>` for another branch at the origin, git will not find it:
```
error: pathspec '<branch>' did not match any file(s) known to git
```

Instead I have to run a longer series of commands, which is inconvenient.
```
git fetch origin <branch>
git checkout -b <branch> FETCH_HEAD
```

There are other reasons as well for why using shallow clones for development are not recommend. A [blog post on the GitHub blog](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/) talks about why using `--depth` and shallow clones is bad for developers. To quote directly from the blog:

> `git clone --depth=1 <url>` creates a shallow clone. These clones truncate the commit history to reduce the clone size. This creates some unexpected behavior issues, limiting which Git commands are possible. These clones also put undue stress on later fetches, so they are **strongly discouraged for developer use**. They are helpful for some build environments where the repository will be deleted after a single build.

There was also a [second GitHub blog post](https://github.blog/2020-12-22-git-clone-a-data-driven-study-on-cloning-behaviors/) that made similar statements.

It would be awesome if the git clone functionality that remote containers used is consistent with the built-in clone functionality of VSCode.

**Comment by leighmcculloch** [comment]
Another way to work around this issue for anyone that is also being troubled by it is to run these functions in the repo after checkout that will refetch other heads and reset how the git commands search and relate to other branches.
```
git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
git fetch
```

**Comment by gparmeggiani** [comment]
Can you check if the "GitLens" and "GitHistory" plugins show a correct history (when looking up a specific line history)? In my case they don't: they show just one commit.
I think this is related to the initial clone with depth of 1 and then some cache not properly cleared or something similar.

**Comment by chrmarti** [comment]
We unshallow the repo in the background. Fetching all branches is tracked as https://github.com/microsoft/vscode-remote-release/issues/4619. Once fixed, I think that should address all concerns.

**Comment by leighmcculloch** [comment]
Another way around this issue I've found is to put the following on my dotfiles that is installed into every devcontainer:
```
git config --global remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
```
