### ISSUE TITLE
wslpath not working with recent windows 10 insider update

### ISSUE THREAD

**Issue by boringuy** [microsoft/vscode-remote-release#4904]
- VSCode Version: 1.56.0-insider
- Local OS Version: 10.0.21354 Build 21354
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: WSL
- Logs:
  [6 ms] Remote-Containers 0.167.0 in VS Code 1.56.0-insider (94d369e27d19f598228961e9feb0413f2edabe5d).
  [69 ms] Start: Resolving Remote
  [70 ms] Start: Run: wsl -d Ubuntu-20.04 -e wslpath -u \\wsl\Ubuntu-20.04\projects\sp-envoy
  [152 ms] Command failed: wsl -d Ubuntu-20.04 -e wslpath -u \\wsl\Ubuntu-20.04\projects\sp-envoy

Steps to Reproduce:

1. setup any wsl con dev container 
2. wsl command failed as shown above

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Recent update of Windows Insider Version changed "wsl" to "wsl.localhost" to avoid conflict to hostname that's also named "wsl". "wsl$" will still work correctly but as far as I understand, "wsl$" was changed to "wsl" in a patch to be more posix compliant. This should like an easy fix or provide option for the extension to change this to suit the version of Windows the user is using. Thank you!

**Comment by boringuy** [comment]
Example outputs of wslpath running inside WSL:

```
andy@DESKTOP:/projects$ wslpath -u '\\wsl.localhost\Ubuntu-20.04\projects\abc'
/projects/abc
andy@DESKTOP:/projects$ wslpath -u '\\wsl\Ubuntu-20.04\projects\abc'
wslpath: \\wsl\Ubuntu-20.04\projects\abc
andy@DESKTOP:/projects$ wslpath -u '\\wsl$\Ubuntu-20.04\projects\abc'
/projects/abc
```

**Comment by boringuy** [comment]
The change is described in here under the "Changes and Improvements" section:
https://blogs.windows.com/windows-insider/2021/04/07/announcing-windows-10-insider-preview-build-21354/

**Comment by bamurtaugh** [comment]
This sounds like https://github.com/microsoft/vscode-remote-release/issues/4789. 

I was just able to open a project from the WSL file system (using Remote-WSL) in a dev container (using Remote-Containers) and it worked. Would you be able to try with the latest Remote-Containers (0.169.0) in Insiders?

**Comment by boringuy** [comment]
Thank you for the reply. Updating to 0.169.0 seems to be the same:
```
[62 ms] Remote-Containers 0.169.0 in VS Code 1.56.0-insider (b4816cfd1f4161a3bb272354d181a9947760ee26).
[62 ms] Start: Resolving Remote
[64 ms] Start: Run: wsl -d Ubuntu-20.04 -e wslpath -u \\wsl\Ubuntu-20.04\projects\sp-envoy
[169 ms] Command failed: wsl -d Ubuntu-20.04 -e wslpath -u \\wsl\Ubuntu-20.04\projects\sp-envoy
```
I wonder if there is some setting I have that's wrong but I check all the extension settings, nothing related to changing the "wsl" part.

**Comment by bamurtaugh** [comment]
@chrmarti any insights?

**Comment by bamurtaugh** [comment]
Thanks for the update @boringuy! Please let us know if you have any other questions or feedback.
