### ISSUE TITLE
Only .zshrc has an effect in WSL terminal

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#491]
Testing https://github.com/microsoft/vscode-remote-release/issues/469

Feel free to close if this is as expected. I compared with an external WSL Shell.

Configure zsh as the default shell and add a `.zshrc`, `.zprofile`, and `.zlogin`. In the external shell, all 3 take effect. In the integrated terminal, only the `.zshrc` is run.

**Comment by khuongduybui** [comment]
I'm not sure about zsh, but with fish shell, there is a `-l` (login) options.
I'm willing to bet that if you specify something similar in your terminal arguments, all 3 files will take effect.

**Comment by aeschli** [comment]
WSL no longer uses a startup script to start the server. We now rely on the server to probe the environment and start the EH with the resulting env.
