### ISSUE TITLE
Remote development fails on 

### ISSUE THREAD

**Issue by GuillaumeDesforges** [microsoft/vscode-remote-release#4911]
In devtools:

```
The terminal process failed to launch: A native exception occurred during launch (The module '/home/guillaumedesforges/.vscode-server-insiders/bin/8aff878db2542eea2dfb571c8bb485118bbb3113/node_modules/node-pty/build/Release/pty.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 83. This version of Node.js requires NODE_MODULE_VERSION 72. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`).).
```

Version
```
Version: 1.56.0-insider (system setup)
Commit: 8aff878db2542eea2dfb571c8bb485118bbb3113
Date: 2021-04-19T05:15:35.845Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
```

remote os:
```Linux poseideep 5.4.97 #1-NixOS SMP Wed Feb 10 08:25:33 UTC 2021 x86_64 GNU/Linux```
my nixpkgs 21.05pre269929.ff96a0fa563

Steps to Reproduce:

1. connect to remote host

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

#### Things I've tried

Running `npm install node-pty` on the remote folder `~/.vscode-server-insiders/bin/8aff878db2542eea2dfb571c8bb485118bbb3113/node_modules/node-pty/build/Release/pty.node` folder fails because it requires private access to some private ms git repos

```
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/microsoft/vsda.git/'
```

**Comment by roblourens** [comment]
Are you for some reason trying to run this with your own version of node instead of the one packaged in the server?

**Comment by GuillaumeDesforges** [comment]
Yes I do. I have to, because otherwise the `./node` in this folder gives "Not found" error. Basically, I have to create a symbolic link to my own node `ln -s $(which node) node` .

But since I have to do that before VSCode on remote does npm install, I'm a bit confused.

This flow has been working for a year I would say, so not sure what changed and broke.

**Comment by roblourens** [comment]
This isn't really a supported workflow tbh. We also package other native modules which you can't build yourself.

But if I had to guess, we just bumped our electron version, we might have bumped the remote node version as well, so make sure you are linking the right version.

**Comment by GuillaumeDesforges** [comment]
> we just bumped our electron version

Too bad that the server binaries are coupled to the node version of the client, but I could make it work by bumping nodejs version on my server. Case closed, thanks
