### ISSUE TITLE
.git

### ISSUE THREAD

**Issue by kasuteru** [microsoft/vscode-remote-release#4912]
I am working on WSL2 in Windows 10, using VSCode 1.55.2 and remote-containers 0.116.1

According to the documentation, 

> The extension will automatically copy your local .gitconfig file into the container on startup so you should not need to do this in the container itself.
[Link](https://code.visualstudio.com/docs/remote/containers#_sharing-git-credentials-with-your-container)

However, in my setup, this does not seem to happen:

local git: 

```
git config -l --show-origin
file:H://.gitconfig     user.name=My Name
file:H://.gitconfig     user.email=My Email
file:H://.gitconfig     core.autocrlf=false
... other config here...
```

remote container:

```
git config -l --show-origin
file:/etc/gitconfig     credential.helper=!f() { lots of stuff here }; f
file:/home/vscode/.gitconfig    credential.helper=!f() { lots of stuff here }; f
file:.git/config        core.repositoryformatversion=0
...
```

No idea what is causing this, since the plugin is still in development, maybe it isn't even implemented yet? Any ideas what is going wrong? Let me know what additional info you need. For now, I will just manually set it after container startup.

Edit: Credential transfer (for pushing) is working fine...

**Comment by chrmarti** [comment]
An existing `.gitconfig` would not be overwritten. Does your container contain a `.gitconfig`? A dotfiles repository's `.gitconfig` would also take precedence and there is a user setting to disable the feature.

**Comment by kasuteru** [comment]
> An existing `.gitconfig` would not be overwritten. Does your container contain a `.gitconfig`? A dotfiles repository's `.gitconfig` would also take precedence and there is a user setting to disable the feature.

It was the first one - another .gitconfig file had already been autocreated by my setup. I tested it with a newly generated folder w/o the file and it seems to work as described. Closing this, thank you.

**Comment by kasuteru** [comment]
Unfortunately, the same problem occured again. Not sure what I did differently, but again, the local .gitconfig settings were not copied. I tried the following approach:

- Create a new folder locally, in Windows
- Open that folder locally in VSCode
- Run "Remote containers: Add development container configuration files"
- Select Python 3 -> 3.7 -> No node.js
- Rebuild container
- Check git config in container - name and email are not set.

I also tried this with an existing git repository folder instead of an empty one, same result. Two .gitconfig files are created inside the container, but they are the same and both only contain credential.helper=!f() {....}

Am I doing something wrong, or is auto-setting name & email not intended in this workflow?

**Comment by chrmarti** [comment]
If the project folder is in WSL, we copy WSL's `.gitconfig`. Do you have one there?

**Comment by chrmarti** [comment]
It's still copied from Windows when the workspace folder is on Windows. Only when the workspace folder is in WSL (\\wsl\... or using Remote-WSL) will it be copied from the WSL distro's home folder.

Could you attach the log from when you rebuild the container? (`F1` > `Remote-Containers: Show Log`)
