### ISSUE TITLE
Remote Explorer for Container shows no container only when no folder opened in VSCode over Remote SSH

### ISSUE THREAD

**Issue by limerhyme** [microsoft/vscode-remote-release#4913]
I'm using Remote SSH extension to access the linux server where docker is running.
Just after the Remote SSH session is started, the file explorer of VSCode will typically be in a *no folder opened* state.
At this moment, Remote Container extension is not able to show the docker containers running on the server.
However, after opening some (server's) folder, it will appear properly.
This is a strange behavior.

- VSCode Version:
  ```
  Version: 1.55.2 (user setup)
  Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
  Date: 2021-04-13T09:35:57.887Z
  Electron: 11.3.0
  Chrome: 87.0.4280.141
  Node.js: 12.18.3
  V8: 8.7.220.31-electron.0
  OS: Windows_NT x64 10.0.19042
  ```
- Local OS Version:
  ```
  Edition	Windows 10 Pro
  Version	20H2
  Installed Date	‎2021/‎01/‎23
  OS Build 19042.928
  Experience	Windows Feature Experience Pack 120.2212.551.0
  ```
- Remote OS Version:
  ```
  $ uname -a
  Linux myserver 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
  ```
- Remote Extension/Connection Type: SSH
- List of extensions that you have installed:  
  - [Remote Development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) v0.20.0 (WSL v0.54.6, SSH v0.65.4, SSH Editing v0.65.4 Container v0.166.1)
  - Note: I usually use the Docker extension, but in order to check this issue, I have installed a new VSCode. I did not install the Docker extension at this time. That is, this issue does not seem to be related to Docker extensions at least.
-  `settings.json`:
   ```js
   {
     "remote.containers.logLevel": "trace",
     "remote.SSH.logLevel": "trace"
   }
   ```

Steps to Reproduce:
1. Open new VSCode window in my Local PC.
2. Go to *Remote Explorer* tab, then select *SSH Targets* view.
3. Select `myserver` and do *Connect to Host in Current Window*.
4. VSCode on the server will be opened. Now *Explorer* tab indicates *NO FOLDER OPENED*.
5. Verify that some docker container is running. Open the integrated terminal, then run:
   ```
   $ docker ps
   CONTAINER ID   IMAGE    COMMAND   CREATED          STATUS          PORTS     NAMES
   66871b696f33   xxxx     yyyy      13 minutes ago   Up 13 minutes             zzzzz
   ```
5. Go to *Remote Explorer* tab, then select *Container* view.
6. No container will be shown. Instead, there is *Get started with containers by installing and staring Docker or by visiting the help view.*
7. Back to *Explorer* tab, click *Open Folder*, and open some folder.
8. Go to *Remote Explorer* tab, then select *Container* view.
9. The running container `66871b696f33` is shown in *Other Containers*.

What you expected to see, versus what you actually saw:  
I think it is better that the container is shown in the *Remote Explorer* even if no folder is opened.

Errors from the Dev Tools Console (open from the menu: Help > Toggle Developer Tools):  
Please see the attachment file. [-1618923443736.log](https://github.com/microsoft/vscode-remote-release/files/6343951/-1618923443736.log)

I guess that the key of this issue is in the error of `docker version --format {{.Server.APIVersion}}` command:
```
> (new TextDecoder).decode(Uint8Array.from(errorobject.stdout.data))
error during connect: This error may indicate that the docker daemon is not running.: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engine: The system cannot find the file specified.
```
From this error, it is assumed that Remote Container extension is in Windows mode when no folder is opened even if VSCode is connected via Remote SSH to the linux server.

My additional experiments:
- Local PC -> VSCode: New Window -> No folder opened -> OK (it shows the docker containers working on the local PC).
- Local PC -> VSCode: New Window -> Connect to WSL using Remote WSL -> No folder opened -> OK (it shows the docker containers working on the local PC).
- Local PC -> VSCode: New Window -> Connect to the server using Remote SSH -> No foldedr opend -> NG.
- Local PC -> VSCode: New Window -> Connect to the server using Remote SSH -> No foldedr opend -> open some folder -> OK (it shows the docker containers working on the server).
- Install [Docker](https://github.com/microsoft/vscode-docker) Extension into VSCode on the server, Docker tab shows the running container.
  Although *Attach Visual Studio Code* command also fails with the dialog message:
  ```
  Docker returned an error. Make sure the Docker daemon is running.
  ```

![screenshot](https://user-images.githubusercontent.com/29333985/115406623-50089d00-a22a-11eb-9d58-8357d6c422e5.png)

Thanks.

**Comment by limerhyme** [comment]
I will try to debug the extensions. Does anyone know where the source repository is?

**Comment by chrmarti** [comment]
This requires https://github.com/microsoft/vscode/issues/111371.

**Comment by TylerLeonhardt** [comment]
@limerhyme can you give VS Code Insiders a try and let us know if this is working for you now?

**Comment by limerhyme** [comment]
Hello, @TylerLeonhardt.
Today I tried insiders and verify that the reported problem was solved!
The container appears correctly and there is no problem when attaching to it.
Thank you all 😄 

![screenshot](https://user-images.githubusercontent.com/29333985/135723613-e216187e-4e2b-4633-aa43-b5ea606c55cc.png)
