### ISSUE TITLE
can't connect remote host via ssh

### ISSUE THREAD

**Issue by forget2save** [microsoft/vscode-remote-release#4916]
- VSCode Version: 1.55.2
- Local OS Version: windows 10
- Remote OS Version: ubuntu 18
- Remote Extension/Connection Type: SSH
- Logs:
Warning: remote port forwarding failed for listen port 233
6d0002c3c41b: running
Acquiring lock on myhome/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/vscode-remote-lock.zhu.3c4e3df9e89829dce27b7b5c24508306b151f30d
Found existing installation at myhome/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d...
Checking myhome/.vscode-server/.3c4e3df9e89829dce27b7b5c24508306b151f30d.log and myhome/.vscode-server/.3c4e3df9e89829dce27b7b5c24508306b151f30d.pid for a running server
Looking for server with pid: 4175
Found running server...

Checking server status on port 44915 with wget
6d0002c3c41b: start
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==44915==
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==01af981d-5700-4d66-9221-a0f4b6a79fd1==
6d0002c3c41b: end

Steps to Reproduce:

1. set port forwarding on the router of my remote host
        router                            remote
xxx.xxx.xxx.xxx:233------>xxx.xxx.xxx.xxx:233
2. connect to the port via vscode remote-ssh
command: ssh username@routerip -p 233
3. stucking.......

It seems remote-ssh requires another random port to get the file tree on the remote host.
ssh service on the remote host is working when I use the powershell to connect

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
We have to forward a port, and this is random. Your machine might have multiple active connections, would being able to specify a fixed range help you?

**Comment by forget2save** [comment]
Yes, I think specifying a fixed range of ports might help. Please do tell me how to configure it. Thanks.

**Comment by forget2save** [comment]
> We have to forward a port, and this is random. Your machine might have multiple active connections, would being able to specify a fixed range help you?

Yes, I think specifying a fixed range of ports might help. Please do tell me how to configure it. Thanks.

**Comment by roblourens** [comment]
Working on it here https://github.com/microsoft/vscode-remote-release/issues/1386
