### ISSUE TITLE
Version 0.65.4 of SSH extension does not work

### ISSUE THREAD

**Issue by zombiezen** [microsoft/vscode-remote-release#4917]
- VSCode Version: 1.55.2
- Local OS Version: Linux x64 5.4.99-12983-g8b7876ab9f5e
- Remote OS Version: N/A
- Remote Extension/Connection Type: SSH
- Logs: Unable to get logs. The command spits out: "Command 'Remote-SSH: Show Log' resulted in an error (command 'opensshremotes.showLog' not found)"

Steps to Reproduce:

1. Open Remote Explorer to SSH. It is empty, and no actions are available:

![Screenshot 2021-04-20 8 43 50 PM](https://user-images.githubusercontent.com/181535/115493778-3ca10600-a219-11eb-87d7-84ea54cdab32.png)

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

Reverting to 0.65.3 fixes the issue.

**Comment by roblourens** [comment]
Works for me. Any errors in the window log? (Output > Log (Window))

**Comment by zombiezen** [comment]
Oddly, I can't get it to reproduce now. I didn't see anything in "Output > Log (Extension)", but I didn't think to check the window log.

I'll close this issue out, and if I'm able to reproduce the problem I'll reopen. Sorry for the noise.
