### ISSUE TITLE
set workspaceFolder to sibling folder doesn't work

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-remote-release#492]
re https://github.com/microsoft/vscode-remote-release/issues/475

Attempts to set workspace folder to the sibling folder of `.devcontainer` for https://github.com/microsoft/vscode-dev-containers/tree/master/containers/typescript-node-lts doesn't work with all following settings

```
"workspaceFolder": "./test-project"
"workspaceFolder": "test-project"
"workspaceFolder": "../test-project"
```

**Comment by chrmarti** [comment]
We now check `workspaceFolder` is an absolute path. Closing.
