### ISSUE TITLE
Let Ports view users turn off auto forwarding but still poll for process information.

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#4923]
There are projects out there that for various reason need to have auto port forwarding turned off. However, it is still beneficial in these projects to fully fill in the Ports view with process information, shown in rectangles here:

![image](https://user-images.githubusercontent.com/38270282/115573661-3c5c4580-a2c1-11eb-8b0e-2716d7daf980.png)

Given the existing ports settings, this could be a difficult thing to explain to users. We already have these related settings:
`remote.autoForwardPorts`
`remote.autoForwardPortsSource`
`remote.portsAttributes`
`remote.otherPortsAttributes`

The goal should be to have a simple way to let users turn the process polling on, even though auto forwarding is off.

**Comment by alexr00** [comment]
@cmbrose FYI, there is a new options `processAlways` on `remote.autoForwardPortsSource`. This setting may change in the next couple days as I gather feedback on it.

**Comment by cmbrose** [comment]
@alexr00 it looks like the new setting got reverted yesterday - what's the latest here? Is there an alternative way to do this?

**Comment by alexr00** [comment]
I removed the setting in favor of (what I hope are) good defaults. When a remove extension uses a `tunnelProvider` we now do the process polling so long as `remote.autoForwardPortsSource` is set to `process` even when `remote.autoForwardPorts` is false.

**Comment by cmbrose** [comment]
Makes sense - thanks for the info!
