### ISSUE TITLE
Support ssh to remote AIX machine

### ISSUE THREAD

**Issue by skotlex** [microsoft/vscode-remote-release#493]
- VSCode Version: 1.34.0-Insider
- Local OS Version: Windows_NT x64 10.0.17763
- Remote OS Version: AIX 7.1.0.0
- Remote Extension/Connection Type: SSH

Error in using extension after installation
Connection using cmd and openssh proceeds normally, but remote plugin generates the following error:
*message= xxx: unreachable or not Linux x86_64 (AIX 00F8DC904C00)

※ ssh config
Host [test_server]
User [user_id]
HostName [ip_address]
Port [port_number]
PubkeyAuthentication no

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by landongn** [comment]
can you connect over openSSH in powershell/cmd? you might need to go configure the setting to allow vscode to prompt for the ssh password.  It's not enabled by default.

**Comment by mjbvz** [comment]
We currently only support `Linux x86_64` (as determined by `uname`). Updating title to make this a feature request to support AIX

**Comment by skotlex** [comment]
@mjbvz thank you
