### ISSUE TITLE
Migrate to the `statusBar/remoteIndicator` menu contribution point

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#4934]
- [x] WSL
- [x] Container https://github.com/microsoft/vscode-remote-containers/pull/121
- [x] SSH https://github.com/microsoft/vscode-remote-ssh/pull/115
- [x] Github

Adopting https://github.com/microsoft/vscode/issues/121180

`statusBar/windowIndicator` is now deprecated and still restricted to extensions with proposed API enabled.

The new menu contribution point is named `statusBar/remoteIndicator`and public.

For `statusBar/remoteIndicator`, only menu entries are accepted with a group name that follows the syntax described below.
All other entries are filtered. A warning message is printed in the log.

The new group format is as follows:

- For commands from remotes: `remote_${order}_${remoteName)_${internalGrouping}`
- For commands from virtual file systems: `virtualfs_${order}_${fileScheme)_${internalGrouping}`

- `order` is a double digit number used to sort entries with the same supergroup (remote, virtualfs)
   - I suggest (to preserve the previous order): `wsl`:10: `ssh`: 20, `containers` 30
- `remoteName` is first part of the remoteAuthority (wsl, ssh,...)
- `fileScheme` is the URI schema of the virtual file system
- `internalGrouping` is of free use for each contribution

`_` is an invalid character in remoteNames or fileScheme, so we use it in favor of `/` as previously suggested.

Examples:
`remote_50_wsl_1-open@1`
`virtualfs_github-fs_9-help@9`

**Comment by roblourens** [comment]
Also the codespaces extension. cc @osortega

**Comment by osortega** [comment]
@aeschli I think the order number is not specified for GitHub Codespaces in the description but I'll be using the order number `40` if it's not yet used by any other extension.

**Comment by aeschli** [comment]
@osortega 40 is good!

**Comment by jkeech** [comment]
Which version of VS Code did this new contribution start shipping in? For the remote name, codespaces uses an authority like `codespaces+{codespaceName}`. Will the dynamic nature of the authority affect this in any way? We won't be able to have our contributions in package.json match the full/exact authority for each codespace remote connection.

**Comment by aeschli** [comment]
@jkeech This shipped in 1.56. The remote name is just the first part of the authority and does not include the `+` and everything after.

`remote_40_codespaces_yourOwnGrouping` should work for you.

**Comment by aeschli** [comment]
Opened https://github.com/microsoft/vscode-remotehub/issues/139 for fixing the RemoteHub categories
