### ISSUE TITLE
Editing file using code -w in terminal does not return focus to terminal when closed in remote container

### ISSUE THREAD

**Issue by leighmcculloch** [microsoft/vscode-remote-release#4936]
This is a transfer of https://github.com/microsoft/vscode/issues/120695.

- VSCode Version: 1.55.2
- Local OS Version: macOS 11.2.3
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Docker
- Logs: N/A

Steps to Reproduce:

1. Open terminal
2. Run command `code -w file`
3. `file` will open in the editor
4. make some changes or add text to `file`
5. Close file, such as with `CMD-W`
6. Focus remains in the editor, and does not return to the terminal

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by aeschli** [comment]
@bpasero I see that in Windows on a non-remote window the terminal in-deed gets the focus back. Is this intentional? How does it work?

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/blob/1733f27dfb370560dbee9204f84621680736b001/src/vs/workbench/contrib/terminal/electron-sandbox/terminalNativeContribution.ts#L44-L53

**Comment by aeschli** [comment]
No plans to support this in remote
