### ISSUE TITLE
Improve wording for the WSL recommendation

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#4938]
As discussed, explain more in the WSL recommendation dialog:

![image](https://user-images.githubusercontent.com/6461412/115859690-d2fb4480-a430-11eb-9c5f-433be1fc3b56.png)

**Comment by aeschli** [comment]
@bamurtaugh I went ahead and pushed. Any improvements are welcome

**Comment by bamurtaugh** [comment]
Really like the greater detail here! What do you think about slightly adjusted wording like:

> The Windows Subsystem for Linux (WSL) must be installed to complete the action. WSL lets developers run a GNU/Linux environment directly on Windows without the overhead of a traditional virtual machine. VS Code, through the Remote-WSL extension, can then open folders and run commands, extensions, and the terminal in WSL.

Thoughts?

**Comment by aeschli** [comment]
Back from vacation. Yes, sounds good. I'll see if I can still make the change.
