### ISSUE TITLE
File not found: docker.exe moved after Docker Desktop update

### ISSUE THREAD

**Issue by Lucurious** [microsoft/vscode-remote-release#4939]
Today, an automatic update of my Docker Desktop installation (current version: 3.3.1 (63152)) seems to have moved the docker.exe from 'C:\Program Files\Docker\Docker\resources\docker.exe' to 'C:\Program Files\Docker\Docker\resources\bin\docker.exe'.

As a result, VS Code was not able to find the docker executable and the extension failed with the 'Is the docker daemon running?' error.
I don't know how the docker.exe is currently being resolved by the extension, however a full reboot of my system didn't fix the problem.
I could not find a way to change the docker.exe path in the extension, however I resolved the issue by creating a symlink from the original to the new location of docker.exe, which allowed the extension to function correctly again (afaik).

The resolution method for the docker executable will have to be updated to check both locations for the executable (as soon as possible), as this docker update will otherwise render the extension useless.

I would also like to suggest changing the error dialog to be more descriptive of the problem, as 'Is the docker daemon running?' is a very vague way of saying that 'The docker.exe was not found!', although this is of course of lesser importance right now.

**Comment by chrmarti** [comment]
Is the new location of the executable on the `PATH`? We use that to do the lookup.

**Comment by chrmarti** [comment]
An update to the `PATH` would only be picked up when restarting VS Code. Related: https://github.com/microsoft/vscode-remote-release/issues/4963
