### ISSUE TITLE
recently used list has started forgetting hostnames

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode-remote-release#4943]
Issue Type: <b>Bug</b>

this is a regression: the remote-ssh extension has started forgetting hostnames in the recently-used list:

![image](https://user-images.githubusercontent.com/1088194/115969864-0fdc3f80-a4f4-11eb-8939-cc16cc658019.png)

notice how the first two items in the list are missing the hostname. if i click on either of those it connects to the correct hostname. it's just not being displayed in the list, and, most importantly: it's not found when entering the hostname in the textbox above.

Extension version: 0.65.4
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.66GB (30.66GB free)|
|Process Argv|--crash-reporter-id 70645636-42ae-4864-b371-1810b42a2956|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.35GB (30.11GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.35GB (30.11GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820cf:30276953
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by bamurtaugh** [comment]
How are you connecting to your hosts/getting this list of hosts to appear in the command palette (i.e. are you selecting Remote-SSH: Connect to Host...)? Can you give an example (even if the hostname is redacted) of what you see in the first two entries of the command palette versus what the hostname for these remote boxes is in your ssh config file?

**Comment by Spongman** [comment]
`Ctrl-R`

_all_ of the entries look like this:

<directory-name> [SSH (:<hostname>)?] <parent-directories>

eg.

project1 [SSH: my-host] /home/user1
project3 [SSH: my-host] /home/user2

the first two are the same, they're just missing the <hostname> for some reason.

**Comment by bamurtaugh** [comment]
I wonder if this is specific to Remote-SSH, or something with remote development in the recently used list in general. 

I used `ctrl+r` and filtered by WSL, and I found that WSL projects may be experiencing a similar phenomenon (some mention specific distro, others just WSL; can't filter those that don't mention distro by their distro).

![image](https://user-images.githubusercontent.com/25310137/116325949-35797b00-a778-11eb-8ab1-07f5086c4c46.png)

**Comment by Spongman** [comment]
yeah, i have the same issue with WSL items as well. this is definitely something that started happening recently - i have been using this feature for ages now and never had this problem before.

**Comment by roblourens** [comment]
Longstanding issue for all remotes, tracked here https://github.com/microsoft/vscode/issues/110153
