### ISSUE TITLE
About port forward

### ISSUE THREAD

**Issue by CCA8290** [microsoft/vscode-remote-release#4944]
After I updated vscode to version 1.55, when using Remote -SSH , the port forwarding disappeared, and the remote version is 0.65.4
![](https://raw.githubusercontent.com/CCA8290/Pic_save/master/1.png)

**Comment by bamurtaugh** [comment]
@CCA8290 Can you try the command "Ports: Focus on Ports View"? That should bring it into focus. 

You should be able to see it in the terminal area:

![image](https://user-images.githubusercontent.com/25310137/116162794-5922bf80-a6ab-11eb-9ec5-871558414bd8.png)

**Comment by CCA8290** [comment]
I got it，thank you very much！

**Comment by CCA8290** [comment]
> @CCA8290 Can you try the command "Ports: Focus on Ports View"? That should bring it into focus.
> 
> You should be able to see it in the terminal area:
> 
> ![image](https://user-images.githubusercontent.com/25310137/116162794-5922bf80-a6ab-11eb-9ec5-871558414bd8.png)

Yes，I got it，thank you very much！

**Comment by bamurtaugh** [comment]
Great! You're very welcome 😄
