### ISSUE TITLE
remoteUser seems to take uid of local computer even if docker.host is set to another docker-host

### ISSUE THREAD

**Issue by Cyber1000** [microsoft/vscode-remote-release#4946]
- VSCode Version: 1.55.2
- Local OS Version: Windows 10 (works well) and Fedora 33 (has the bug)
- Remote OS Version: raspbian (64bit - arm)
- Remote Extension/Connection Type: Docker - there is actually an entry "docker.host":"ssh://pi@my-rpi4" in my settings.json
- Dockerfile uses mcr.microsoft.com/dotnet/sdk:5.0-focal (if this matters, but I don't think so)
- devcontainer.json is extended, so that I can start the docker-container on my rpi from remote win10/fedora33
```
	"workspaceMount": "source=/opt/dockerdev/blazor,target=/workspace,type=bind,consistency=cached",
	"workspaceFolder": "/workspace",
```

Preconditions:
1. you have to use linux to reproduce, I used fedora, but from the bug I've seen, it doesn't seem to be fedora specific
2. in devcontainer.json your remoteUser should be set to vscode
2. the user you run vscode should have an uid higher than 1000, in my special case my user has uid 1010
3. the user on the remote computer should have a different uid, in my case the user pi on my rpi4 has 1000

Steps to Reproduce:
1. take Fedora 33 (I think it may be with every linux), open the folder
2. It says it has found a devcontainer.json and asks if you want to start the container
3. The container is started remotely on my rpi4, since I have this docker.host entry in settings.json
    vscode-user inside the container (on my rpi4) has id 1010 (like my local user, I started vscode from), this doesn't really work well, since my rpi4 user, where the workspace resides has id 1000.

If I start the same folder from windows 10 with exactly the same setup (docker on rpi4) everything works well, since vscode inside my container on my rpi4 now has id 1000, like my docker-user on the rpi4 itself. Maybe it's because windows itself has no equivalent of uid it could use here, so it just uses the uid 1000 which matches. 

Expected behaviour:
- If I use "docker.host":"ssh://pi@my-rpi4" to remotely connect to another computer, I would expect that the vscode-user inside the container get's the same uid of pi@my-rpi4 and not the uid of my local user.

Temporary fix:
- I've read https://code.visualstudio.com/docs/remote/containers-advanced#_specifying-a-user-for-vs-code and found that "updateRemoteUserUID": false keeps the uid of the vscode-user at 1000 (the default) which (coincidentally) matches with the uid of my remote user.

Proposal:
- I don't know exactly how you find out the id of the current user , but it must be something like `id -u`
- If there is a docker.host in settings.json I would propose executing something like `ssh://pi@my-rpi4 id -u`
this does the same on the remote

**Comment by chrmarti** [comment]
When you use the Remote-SSH extension to open a folder on an SSH server and then reopen that folder in a container, we use the UID of the user on the SSH server.

Using the UID from the SSH server without first connecting with Remote-SSH is currently out of scope. Thanks.
