### ISSUE TITLE
Test: Stable vs. Insiders in Remote Containers

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#495]
https://github.com/microsoft/vscode-remote-release/issues/418

- [x] Windows @alexr00
- [x] Windows docker compose @alexr00 
- [x] macOS @Tyriar 

Complexity: 3

(Note: The CLI command requires a fix to #490, please ignore that for now.)

Use Stable (1.35 RC) and Insiders to test running side-by-side with the same container. Make sure extensions, settings and CLI command name are distinct for the two. Mix single container, Docker Compose and Attach to Container cases.

**Comment by bpasero** [comment]
My testing is blocked by https://github.com/microsoft/vscode-remote-release/issues/500

**Comment by bpasero** [comment]
@rebornix please assign someone from Redmond to test this once #500 is resolved

**Comment by alexr00** [comment]
@rebornix and @chrmarti I was unable to test docker compose on Windows because of #503. Otherwise, Windows testing is done.

**Comment by alexr00** [comment]
With a suggestion from @chrmarti I tested compose and hit https://github.com/microsoft/vscode-remote-release/issues/504
