### ISSUE TITLE
Test Ports view improvements

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#4951]
Refs: https://github.com/microsoft/vscode-remote-release/issues/4826

- [x] dev container @digitarald
- [x] ssh @joaomoreno
- [x] anyOS @mjbvz

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%234951%0A%0A)

---

If testing with SSH, set the following setting then reload:

```
"remote.autoForwardPortsSource": "process"
```

For anyOS, use any remote extension other than WSL (SSH, Containers, or Codespaces are all good).

Linux remotes only: Ports with an associated process now show a green filled circle icon in the Ports view. 
- Verify that the icon shown in the Ports view for ports with an associated process is a green filled circle using the default light and dark themes.
- Verify that all the other built in themes have a reasonable color for the same icon.

The local address column of the ports view now gets special treatment to indicate that the local address is a link. It is intended to look/feel like a link in the terminal.
- Verify that when you hover over the local address of a port it gets underlined.
- Verify that the ctrl/cmd + click action works.
- Verify that clicking the link in the resulting hover works. 

There is new behavior around the "Set Label" action in the Port column.
- For Containers, verify that the inline action to set the label (the tag icon) is "Set Label and Update devcontainer.json".
- For SSH, verify that the inline action to set the label is "Set Label"
- For all, verify that there is only one labelling inline action.
- For all, verify that there is only one labelling action in the context menu.

**Comment by mjbvz** [comment]
@alexr00  I think this is by design, but should the circle indicator be hidden when you are connected to a window/macOS host? For those remote machine types, are there any states besides the unfilled circle?

**Comment by digitarald** [comment]
> For Containers, verify that the inline action to set the label (the tag icon) is "Set Label and Update devcontainer.json".

@alexr00 even though I have a devcontainer open (just added it), this the tag is "Set Port Label". Even after _Rebuild_. Do I need to do something else to make it default?

![image](https://user-images.githubusercontent.com/8599/116330005-6f02b400-a781-11eb-8bb6-271c5747826f.png)

**Comment by alexr00** [comment]
@digitarald do you have the latest version of the Remote Containers extension installed?

**Comment by joaomoreno** [comment]
This is not only very cool but super polished, great work @alexr00.
