### ISSUE TITLE
Test - Clone Repo in Container Volume Improvements

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#4952]
Refs: https://github.com/microsoft/vscode-remote-release/issues/4830

- [x] dev container @alexr00 
- [x] dev container @bamurtaugh 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%234952%0A%0A)

---

The Remote Explorer has a new view 'DEVVOLUMES'. It shows the volumes created by 'Clone Repository in Container Volume' or 'Clone GitHub Pull Request in Container Volume' and supports to manage the volumes. 

#### Simple Setup - Create a new volume for each cloned repository

Clone a repository in a container volume
- Verify that the label shows the repository name, branch, and creation time.
- Verify that when cloning a PR into a container volume using the command 'Clone GitHub Pull Request in Container Volume' the PR # is shown in the label and the hover. 

Hover over the volume name
- verify that the hover shows the repository, branch, creation time, the name of the container that is use the volume
- verify that the links in the hover navigate to the repo/branch/PR

Delete the created container from the Remote Explorer's Container section
- Verify that you are prompted to also delete the volume

Create a dangling volume by not deleting a volume created for a container when prompted
- Verify that the hover shows that the volume is not used by any container

Open the dangling volume in a development container using the context menu action 'Explore in Development Container'
- Verify that the volume contents shown in the dev container

Remove the unused volume using the 'Remove Unused Volumes' command shown in the toolbar or the command palette

#### Advanced setup - clone multiple repositories into a single named volume

Create a new named volume for cloning a repository using the command 'Clone Repository in Named Container Volume'. You will be prompted for the volume name and the target folder name.

Clone an additional repository into the same volume using the context menu action 'Clone Repository in Volume'
- Verify the contents of the volume using the 'Explore Volume in Dev Container' command
- Verify that the hover shows that the volume is used by the two containers you have created

Delete one of the containers
- Verify that you are not prompted to delete the volume since it is still in use by the other container

#### Test the view welcome.

Delete all containers and volumes using the Docker CLI or Docker extension and open the Remote Explorer for Containers
-  Verify that the 'DEVVOLUMES' view shows a welcome message to clone a repository in a container volume.

**Comment by bamurtaugh** [comment]
LGTM! 

I had one question - since putting the URL to a GitHub PR in `Clone Repository in Container Volume` seems to have the same net result as placing it in `Clone GitHub Pull Request in Container Volume`, I wondered why we designate two separate commands. Is it to help raise awareness that users can clone a repo or PR directly? 

The docs PR to reflect these changes will be merged in once we ship 1.56: https://github.com/microsoft/vscode-docs/pull/4489.

**Comment by egamma** [comment]
>I had one question - since putting the URL to a GitHub PR in Clone Repository in Container Volume seems to have the same net result as placing it in Clone GitHub Pull Request in Container Volume, I wondered why we designate two separate commands. Is it to help raise awareness that users can clone a repo or PR directly?

@bamurtaugh correct this was done to raise awareness for PRs and to make it consistent with RemoteHub (which in the meantime has evolved to provide a full blow PR picker, which will be adopted as soon as there will be API).
