### ISSUE TITLE
DEVVOLUME hovers take +10 seconds to show

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#4956]
Testing #4952

When hovering over one of the volumes in the DEVVOLUMES view on Windows, it takes about 13-16 seconds before the "loading..." hover is replaced with the extension provided hover. Is there any way that can be shortened?

**Comment by egamma** [comment]
@alexr00 how many containers do you have active when you observe this delay?

The costly operation is to compute which containers use a particular volume, this requires inspecting all the active containers.

**Comment by alexr00** [comment]
I have deleted a bunch of containers today, so now I have 6 containers, and the hover takes ~5 seconds, which is way better. Before, I probably had >15 containers.

**Comment by egamma** [comment]
Good catch, spawning processes on Windows is much slower.
