### ISSUE TITLE
Hide DevVolumes view when docker isn't running

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#4957]
Testing #4952

I stopped docker, and this is what the Remote Explorer shows.

![image](https://user-images.githubusercontent.com/38270282/116235081-b119fe80-a75d-11eb-8124-b3f4804d1d8e.png)

**Comment by egamma** [comment]
I left it intentionally blank since I did not want to replicate what is in the Containers view. What would you suggest to show in the Dev Volumes view when docker is not running?

**Comment by alexr00** [comment]
I think ideally it could be hidden with a `when` clause in the `package.json`. Leaving it empty so that content of the Containers view is not replicated make sense.
