### ISSUE TITLE
Warn on port collisions when forwarding ports 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#4958]
Right now, we get some confusion and friction from users when they're working on a remote project from VS Code because engineers may also have the same project open and running locally. When they go to start their development server for in the remote project, the port is auto forwarded and will just pick a random port because the desired local port is already taken by the same project running locally. It would be really neat if when a port is bound that has a collision with another process listening on that point, we warned the user.

**Comment by alexr00** [comment]
I think we still want to automatically forward the port to a random port since not all users are going to care what port gets used, especially since VS Code tries to patch all the gaps (for example, even if you click on a link in the terminal the correct local port will be used).

However, showing some kind of notification that a different port was used could be useful. We can include a "never show this again" option in the notification.

**Comment by cmbrose** [comment]
Extending this a little, should be behavior be different in the case where the user manually tries to set the local port via the context menu and we fail to get that port? In that case there's probably a reason that the user wanted that exact port and using a random one probably isn't helpful.

**Comment by joshaber** [comment]
That's a really interesting distinction @cmbrose.

I know there's some (understandable!) reticence around adding more port configuration, but perhaps we should be able to indicate as part of port configuration whether the local port _must_ match the forwarded port:

```
{
  "portsAttributes": {
    "80": {
      "requireLocalPort": true,
      "label": "web"
    }
    ...
  }
  ...
}
```

Then if the local port isn't available VS Code should loudly signal that and not pick a random port.

**Comment by alexr00** [comment]
Since it has take all the way until now for there to be a request to have a warning or error around this, I'm inclined to think that the current default behavior is good and that we should require opt in. I kind of like @joshaber suggestion.

**Comment by alexr00** [comment]
When the local port is set via the "Change Local Address Port" context menu action, we will be more aggressive in showing that the local port can't be used. This used to be just a notification. Now, its a full dialog:

![image](https://user-images.githubusercontent.com/38270282/117977760-73a69b00-b331-11eb-8ce6-0a743bf27747.png)

**Comment by alexr00** [comment]
New setting property:
```
  "remote.portsAttributes": {
    "3000": {
      "requireLocalPort": true
    }
  }
```
