### ISSUE TITLE
Remote-Containers - update link in the getting started text

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-remote-release#4961]
Testing #4931

Nit: It's very cool that we initiate the download, and installation of Docker though, I would suggest that we use a different word for the hyperlink. Clicking on a link that says "Docker" set my expectations that I will be redirected to the "Docker" website. On Windows we should probably use "installing" as the text for the link.

![image](https://user-images.githubusercontent.com/3372902/116259726-593bc180-a776-11eb-9c26-5a0699752af2.png)

**Comment by chrmarti** [comment]
Updating to:
![image](https://user-images.githubusercontent.com/9205389/116878228-5847db80-ac1f-11eb-8efb-b7c162cb4217.png)
