### ISSUE TITLE
Remote-Container - Reopen folder in Container does not offer to install Docker

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-remote-release#4962]
Testing #4931

After opening a folder, I have clicked on the `Reopen Folder in Container` menu but I have gotten the following error. In the background you can see the details of the Remote-Containers extension in case I am using an incorrect version. I am also getting the same error independent on which command do I pick from the Remote-Containers category.

![image](https://user-images.githubusercontent.com/3372902/116260264-d2d3af80-a776-11eb-88b9-b3631766ada6.png)

**Comment by lramos15** [comment]
Think this is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/4960

**Comment by chrmarti** [comment]
Closing as duplicate of https://github.com/microsoft/vscode-remote-release/issues/4960, thanks.
