### ISSUE TITLE
Remote-Containers: VSCode needs to be restarted after the installation

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-remote-release#4963]
Testing #4931

VSCode has guided me though with the "Docker" installation but after Docker has been installed, and the deamon was started, VSCode did not pick this up. I have tried reloading the window but that did not help. I kept on getting errors that `docker` is not on the path. I have to quit VSCode and start it again. If this is known, we should warn users that after installing docker the need to restart VSCode. Did I miss that?

**Comment by rzhao271** [comment]
It worked for me on Mac, though I had to start the daemon manually. After the daemon started, I was able to relaunch the workspace in a container.

**Comment by chrmarti** [comment]
This is Windows-specific because only there does the install add to the PATH.
