### ISSUE TITLE
Created dangling volume from named container volume and wasn't prompted to delete it

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#4965]
Testing #4952

I seem to have created a dangling volume and wasn't prompted to delete it when testing **Advanced setup - clone multiple repositories into a single named volume**

- Create a new named volume "containers-collect" using the command 'Clone Repository in Named Container Volume'
- Clone one repo and then another into containers-collect volume
- Explore contents of the volume using the 'Explore Volume in Dev Container' command
- Hover over containers-collect: label reads that it's in use by 3 containers (the 2 containers from the repos I cloned, plus the inspection dev container)
- Delete the dev container from the second repo I cloned into containers-collect, hover over containers-collect: label reads that it's in use by 2 containers (the first one I cloned, plus the inspection dev container)
- Delete the first dev container I cloned into containers-collect, hover over it: label reads it's in use just by inspection dev container
- Close remote connection, delete inspection dev container. I am not prompted to also delete the volume (although I expected to be prompted). When I hover over containers-collect, I can see it's a dangling volume in use by no containers:

![image](https://user-images.githubusercontent.com/25310137/116273180-62a53980-a736-11eb-9a41-14389c8dd428.png)
I am able to remove containers-collect manually since it isn't in use by any dev containers. 

Version: 1.56.0-insider (user setup)
Commit: 5080d21c0b538b996c83fb7b14a746f656eaef15
Date: 2021-04-26T17:23:39.588Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

Remote-Containers v0.172.0

**Comment by egamma** [comment]
Repro steps:
1. clone repository in container volume 
2. select the volume that was created in the previous step in the DevVolumes view in the Remote Explorer
3. from the context menu run 'Explore in Development Container' 
4. close the remote connection
5. remove the container created in step 1 in the Remote explorer -> you will not be prompted to delete the volume
6.  remove the container created in step 3 -> you now should be prompted to delete the volume
