### ISSUE TITLE
Single folder container entry doesn't have folder indication

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#4967]
Testing #4949

I can understand that if I've only ever opened a single folder in a container that listing the folder is not important, but if I've opened many folders and then X'd all but one, its less obvious. I find it strange in the dev container scenario to not provide the folder you open into.

There is also the button to open container which uses a folder icon. But the tooltip says open container. I would expect `open <folder name> in container`

**Comment by alexr00** [comment]
Since the specific goal here was to not show the single folder, I'm going to leave that as is. However, it sounds like the command label needs improvement.

**Comment by alexr00** [comment]
Because the open folder command is statically contributed, we can't have the whole folder be in the tooltip. I have updated the command title/tooltip to be "Open Folder in Container".

**Comment by alexr00** [comment]
For verifier, this will require version 0.173.0 of Remote Containers to verify, which may or may not exist at the time you read this comment.
