### ISSUE TITLE
Codespaces hovers feel bad comparatively

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#4968]
Testing #4949

Not sure what the action item would be from this feedback, but since you asked to compare the two, the dev container hovers feel so much better than the codespaces hover now that I want those to be enhanced.

**Comment by alexr00** [comment]
@sbatten can you provide a screen shot? I know the codespaces team has been working on improving them.

**Comment by sbatten** [comment]
![image](https://user-images.githubusercontent.com/6561887/116425648-4cab7d80-a7f7-11eb-89bb-00840757e868.png)

**Comment by alexr00** [comment]
Looks like they just merged the change that improves these hovers last Friday and it just isn't in the build yet!

The new Codespaces hovers look veeerrry similar to the new Containers hovers (we took some inspiration from them).
