### ISSUE TITLE
Attach to container opens to a folder?

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#4969]
Testing #4949

I find it strange that `Attach to container` opens to a folder. This makes it seem like its really `Open container in new window`. But if that were the case, I would expect the same action to be present on the individual folder items when the container has multiple folder entries.

**Comment by chrmarti** [comment]
We remember the last folder you opened with the same Docker image. The reasoning is that this will likely be the folder you want to open again.

**Comment by sbatten** [comment]
That makes sense, but it feels strange to happen on the new container items which functioning as a compact version of:
```
container [container actions]
  folder [folder actions]
```

because now this tree entry item is effectively associated with 2 folders

**Comment by chrmarti** [comment]
I see, it might make sense to ignore the 'last folder' when opening from the Remote Explorer to make this more deterministic for the user.

**Comment by chrmarti** [comment]
We seem to have removed the Attach command from these tree items.
