### ISSUE TITLE
Bottom border of button in ports view not shown

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-remote-release#4970]
Testing #4951

1. In a remote (ssh in my case)
1. Open multiple ports in the ports view
2. Now tab to the  `set port label` button

**bug**
The bottom border is missing:

![Screen Shot 2021-04-27 at 5 23 49 PM](https://user-images.githubusercontent.com/12821956/116328294-8fc90a80-a77d-11eb-8361-d604f63a9be3.png)

When hovering over the button normally, it looks like the button itself may be getting clipped (notice how the top has rounded corners but the bottom does not:

![Screen Shot 2021-04-27 at 5 25 03 PM](https://user-images.githubusercontent.com/12821956/116328337-a7a08e80-a77d-11eb-80c7-fce5b34d5536.png)

**Comment by alexr00** [comment]
@joaomoreno I think this might be more action bar fallout.
