### ISSUE TITLE
Remote-SSH Plugins whether support unix system?

### ISSUE THREAD

**Issue by Allen1218** [microsoft/vscode-remote-release#4973]
##  Remote-SSH Plugins whether support unix system?
For example : HP Itanium?

Because, I use remote-SSH plugin to connect Unix system with WIN10, connection fail.
Could you reply me?

 thanks!

**Comment by bamurtaugh** [comment]
Closing as a duplicate of https://github.com/microsoft/vscode-remote-release/issues/4976.
