### ISSUE TITLE
SSH connection with ProxyCommand or ProxyJump not work

### ISSUE THREAD

**Issue by denissanga** [microsoft/vscode-remote-release#4980]
Hi,
I'm working with VSCode on Windows and I use two servers. I need to connect to one server with ssh command using an intermediate server as bridge to which I connect with ssh command too.

For a better explanation:
PC(VSCode)     --ssh-->     Server 192.168.1.x     --ssh-->     Server 192.168.2.x

I tried to find online many suggestions or tutorials but no one works.
Can someone help me to create this bridge?

For example I tryed:

_Host 192.168.2.10
    HostName 192.168.2.10
    User root
    Port 22
    ForwardX11 yes
Host 192.168.3.10
    HostName 192.168.3.10
    User root
    Port 22
    IdentityFile C:/Users/.ssh/id_rsa
    ForwardX11 yes
    ProxyCommand ssh -W %h:%p 192.168.2.10_ ...or... _ProxyJump 192.168.2.10_

I can connect to 192.168.3.10 when Proxy is commented

Thank you

**Comment by shesh1123** [comment]
Hi,

Not sure if you are still facing this issue.

If yes, try below config.

Host 192.168.2.10
HostName 192.168.2.10
User root
Port 22
ForwardX11 yes


Host 192.168.3.10
HostName 192.168.3.10
User root
Port 22
IdentityFile C:/Users/.ssh/id_rsa
ForwardX11 yes
ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -W %h:%p 192.168.2.10
