### ISSUE TITLE
ForwardX11 yes not work

### ISSUE THREAD

**Issue by denissanga** [microsoft/vscode-remote-release#4981]
Hi all, I'm trying to plot on local pc the screen running on a server but seems that after connection the X11 Forwarding not work giving me the following error: _Error in GXSTRT: Unable to connect to X server_
Instead, if I connect to server using putty, with _Enable X11 forwarding_ and setting the X11 authentication protocol: _MIT-Magic-Console-1_, I can see on my local pc the remote screen.
I posted the configuration in _config_
_Host 192.168.1.10
    HostName 192.168.1.10
    User root
    Port 22
    IdentityFile C:/Users/.ssh/id_rsa
    ForwardX11 yes_

thank you very much
Best Regards

**Comment by roblourens** [comment]
It seems like on windows there might be more setup needed than what the extension currently does, which is just forwarding the DISPLAY variable. I don't know enough to debug this, but there is some discussion in https://github.com/microsoft/vscode-remote-release/issues/4600

**Comment by denissanga** [comment]
Thank you for your answer but following all suggestions it still not work:
in details I used vscode with WSL terminal and I open ssh machine with:

Host 192.168.1.10
HostName 192.168.1.10
User root
Port 22
IdentityFile C:/Users/.ssh/id_rsa
ForwardAgent yes
ForwardX11 yes
ForwardX11Trusted yes


On remote machine (linux centos) I added in bashrc the line export DISPLAY=localhost:0.0
In the local machine (win 10) I installed xming too and I opened it.

after connection, if I run "grads" I obtain:

"GX Package Initialization: Size = 11 8.5
Error in GXSTRT: Unable to connect to X server"

thank you very much 
best regards
