### ISSUE TITLE
Default shell not used

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#499]
Issue Type: <b>Bug</b>

https://github.com/microsoft/vscode-remote-release/issues/469

I have tmux configured as my default shell, yet:

![image](https://user-images.githubusercontent.com/9205389/58551025-6610ad00-820f-11e9-88e5-62062f31e70e.png)

Extension version: 0.36.0
VS Code version: Code - Insiders 1.35.0-insider (6964233e81c68f5a5f34e7eb1da0836e1d539f14, 2019-05-29T05:18:15.943Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.4.0-17134-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|24.00GB (4.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17134-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|24.00GB (4.07GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment]
WSL no longer uses a startup script to start the server. We now rely on the server to probe the environment and start the EH with the resulting env.
