### ISSUE TITLE
Varying messages when Docker or container can't start up

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#4991]
I chatted about this with @PaulYuk.

When Docker isn't running, I get the following error message, which is helpful:

![image](https://user-images.githubusercontent.com/25310137/116745638-38f74700-a9b0-11eb-9a29-86dced11d7f4.png)

However, Paul and I encountered an instance where he got the following error, when Docker was properly running and he hadn't changed any code in his container configuration: 

![image](https://user-images.githubusercontent.com/25310137/116745921-a60adc80-a9b0-11eb-91dc-034a0ae583c0.png)

![image](https://user-images.githubusercontent.com/25310137/116745859-91c6df80-a9b0-11eb-8a40-8b413e9b86ad.png)

I believe I've also encountered this at seemingly arbitrary times as well. 

Are there common reasons a container may fail to start with Remote-Containers, even if the user has Docker running and hasn't changed any configuration in their container definition and it was working previously (and ends up working when they try connecting again)? Could we guide them to any resources, like how we guide users to Docker.com in the case Docker isn't running?

**Comment by chrmarti** [comment]
We try to give more information when we can detect what went wrong. Do you have the full log from such a case?

**Comment by bamurtaugh** [comment]
If I run into the second scenario, I'll provide the logs. @Paulyuk Would you have a full log from when you've experienced this? I have the screenshot from when we chatted, but the full text log would be great if you're able to repro.
