### ISSUE TITLE
code or code-insiders is not installed

### ISSUE THREAD

**Issue by davetapley** [microsoft/vscode-remote-release#4992]
```
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

Steps to Reproduce:

1. Add [these files](https://gist.github.com/davetapley/205f0e9e4ffff44c1b16421b094787f6) to an empty directory.
  ( generated with `Remote-Containers: Add Development Container Configuration Files...`)

2. Open directory in VS Code
3. Choose 'Reopen in Container'
4. Type `code` in to `bash` in integrated terminal
5. Observe: `code or code-insiders is not installed`

Does this issue occur when all extensions are disabled?: Yes †

† I couldn't do it with `--disable-extensions` because I need the `ms-vscode-remote.remote-containers` extension to repro and microsoft/vscode#81950 prevents any extensions from working. However I was able to use technique from https://github.com/microsoft/vscode/issues/81950#issuecomment-554936557 to enable solely `ms-vscode-remote.remote-containers` and confirm issue still exists.

---

As noted [here](https://stackoverflow.com/a/62880366/21115) `code` is in the container:

```
 ~/.vscode-server/bin/[HEX]/bin/code
```

**Comment by chrmarti** [comment]
What is the container terminal's `PATH` value?

**Comment by davetapley** [comment]
```
vscode ➜ /workspaces/devcontainer-missing-code $ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/vscode/.local/bin
```

Sure enough, `/home/vscode/.local` is missing:

```
vscode ➜ /workspaces/devcontainer-missing-code $ ls -la /home/vscode
total 60
drwxr-xr-x  1 vscode vscode 4096 May  3 17:01 .
drwxr-xr-x  1 root   root   4096 Apr 30 02:17 ..
-rw-------  1 vscode vscode  198 Apr 30 19:03 .bash_history
-rw-r--r--  1 vscode vscode  220 Feb 25  2020 .bash_logout
-rw-r--r--  1 vscode vscode 4870 Apr 30 02:17 .bashrc
drwxr-xr-x  3 vscode vscode 4096 Apr 30 18:39 .config
-rw-r--r--  1 vscode vscode  634 May  3 17:01 .gitconfig
drwxr-xr-x  2 vscode vscode 4096 Apr 30 02:17 .oh-my-bash
drwxr-xr-x 12 vscode vscode 4096 Apr 30 02:17 .oh-my-zsh
-rw-r--r--  1 vscode vscode  807 Feb 25  2020 .profile
drwxr-xr-x  2 vscode vscode 4096 Apr 30 18:37 .ssh
drwxr-xr-x  5 vscode vscode 4096 Apr 30 18:37 .vscode-server
-rw-r--r--  1 vscode vscode 3713 Apr 30 02:17 .zshrc
```

**Comment by chrmarti** [comment]
Make sure you have Inherit Env enabled in your settings:
![image](https://user-images.githubusercontent.com/9205389/116965997-73fac280-acaf-11eb-97a0-9a360e4a5590.png)

The `~/.local/bin` PATH-entry appears to be part of the container's `/etc/bash.bashrc` and doesn't matter in this case.

**Comment by davetapley** [comment]
@chrmarti yep, that was it! Thanks 💯
