### ISSUE TITLE
Only one vscode

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [microsoft/vscode-remote-release#4995]
I have a device running ubuntu with usual vscode desktop gui client installed and I want to access it remotely. I hope to use the settings and extensions of the vscode gui client I already have, instead of create a .vscode-server. And I also hope I can sync the settings to the client device. I think it is really useful if someone use many devices such as public PCs to access the same server out of home and use the server directly at home.

**Comment by roblourens** [comment]
We won't support this exact scenario, because using vscode locally is different from running the remote server. But, you can get what you want with our new settings sync feature: https://code.visualstudio.com/docs/editor/settings-sync
