### ISSUE TITLE
Can't connect to a remote host when path to .pem file has spaces

### ISSUE THREAD

**Issue by RewForeN** [microsoft/vscode-remote-release#4999]
I tried to connect to an AWS EC2 Instance using the given `.pem` file to connect via SSH.

I used the following command where this extension prompts the SSH command:

`ssh -i "C:\path with spaces\Key.pem" root@x.x.x.x.example.com`

And the config file looked something like this:

```
Host x.x.x.x.example.com
  HostName x.x.x.x.example.com
  IdentityFile C:\path with spaces\Key.pem
  User root
```

**The problem** is that the path has spaces and an error is thrown. **The fix** is simply to add quotation marks around the path in the config file. So the config file should look like this:

```
Host x.x.x.x.example.com
  HostName x.x.x.x.example.com
  IdentityFile "C:\path with spaces\Key.pem"
  User root
```

**Comment by roblourens** [comment]
Thanks, opened https://github.com/cyjake/ssh-config/pull/43

**Comment by TylerLeonhardt** [comment]
@RewForeN do you think you could verify this is fixed in the nightly version of Remote - SSH? https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly

That will help us a ton. Otherwise, @roblourens can you provide verification steps?

**Comment by RewForeN** [comment]
@TylerLeonhardt I don't have access to the server that required the Identity file anymore, so I can't confirm.

However, I installed the nightly version and typed a sample command; `IdentityFile` remains unquoted just like before.

**Comment by rzhao271** [comment]
Marking as verification found based on comment above.

**Comment by roblourens** [comment]
This is working for me, please try again

**Comment by rzhao271** [comment]
I just realized there was a nightly version. Verified
