### ISSUE TITLE
Debugging XUnit unit tests remotely crashes IntelliSense

### ISSUE THREAD

**Issue by aadnk** [microsoft/vscode-remote-release#5003]
When debugging unit tests (XUnit) in a .NET  5.0 project remotely using the "Remote - SSH" extension, any assertions that fail will also cause OmniSharp to be killed and IntelliSense to stop working in Visuaul Studio Code. Restarting OmniSharp is also not sufficient to fix this - I had to restart the SSH connection to get IntelliSense working again.

Steps to reproduce:
1. Install Visual Studio Code with the "Remote - SSH" extension (tested on Windows 10 1909)
2. Setup SSH to a remote machine with .NET Core, I use an Amazon Linux EC2 instance.
3. Setup a XUnit test project:
    ```
    mkdir SimpleTest
    cd SimpleTest
    dotnet new xunit
    ```
4. Make the default unit test in UnitTest1.cs always fail:
    ```
        public void Test1()
        {
            Console.WriteLine("Executing test");
            // Should always fail
            Assert.True(1 == 0);
        }
    ```
5. Start the unit test using the "Debug Test" link above Test1 (see screenshot).
6. The debugger will pause on the "Assert.True" line. After clicking continue, it will crash and IntelliSense will be broken until you reconnect to the SSH server.

## Screenshot
![image](https://user-images.githubusercontent.com/1276508/117134869-7724aa00-ada6-11eb-9fa7-7d034b6a634d.png)

## Source Code

[SimpleTest.zip](https://github.com/microsoft/vscode-remote-release/files/6426771/SimpleTest.zip)

**Comment by roblourens** [comment]
Please file this on the repo for the C# extension, thanks
