### ISSUE TITLE
Can not jump to function definition

### ISSUE THREAD

**Issue by daixiang0** [microsoft/vscode-remote-release#5006]
- VSCode Version: 1.55.2
- Local OS Version: Win10
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: SSH/Docker/WSL SSH
- Logs:

Steps to Reproduce:

1. Prepare SSH
2. Open a workspace, open a code file, try Ctrl + right click a function

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
What language? Do you have an extension installed for that language?

**Comment by daixiang0** [comment]
@roblourens it is c++ code, it works use local files while fail with ssh remote mode.

**Comment by roblourens** [comment]
Please open an issue on their extension or see their docs for support

**Comment by daixiang0** [comment]
Root cause is that c++ extension is not installed by default.
