### ISSUE TITLE
Add command to bring me to no-remote context

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#501]
Currently I am stuck in "Docker" context.

**Comment by Chuxel** [comment]
I'd actually propose we do this across the board including SSH. I've seen enough people ask how to get out of the remote context I think it makes sense.  /cc: @kieferrm @roblourens

**Comment by bpasero** [comment]
Yeah agree and I thought we decided that already.

**Comment by aeschli** [comment]
The empty remote window is the starting point of every remote experience
- New WSL Window, Connect to SSH Host, both result in an empty remote window.
- Then you do open folder / open workspace
- So close folder / close workspace should bring you back to the empty remote window


IMO what we need is an action 'Close Remote', that is in the remote menu and in the global menu.

**Comment by Chuxel** [comment]
>New WSL Window, Connect to SSH Host, both result in an empty remote window.

@aeschli I'm not sure that's the right behavior given some of the feedback and issues that have been raised.  I just raised #511 on the SSH part of this.  In theory, I could see WSL being a bit of a special case since people could think of it as a pure local experience.

**Comment by aeschli** [comment]
I don't think WSL is anything special here. We want the same experience on all the remotes.

I fully agree that the empty window approach is not intuitive for some use cases. When you exactly know what you want to open, the empty window is not something you want or need. You'd rather see a dialog first and the window later. But that's not easy to implement given our current architecture where the resolver needs to have a window for output.
But I'm also convinced that once you understand that you always need an empty window first (until you can use the recent history), it works well. The empty window first also solves some issues for us. One issue is that we have 3 different artifacts you can open: files/folders and workspaces, with 3 (MacOs: 2) different commands and keyboard shortcuts.
I suggest we make the empty window experience better, e.g. by showing a welcome page with prominent `open` buttons.

**Comment by Chuxel** [comment]
@aeschli Good points - maybe we continue that part of it over in #511.

In either event, it does seem like we need some sort of explicit close if it isn't close folder since people do not seem to be finding New Window as a way to do it based on GH, Twitter, conversations, etc.

**Comment by kieferrm** [comment]
More VS Code users use `Run Task` than `Close Folder`. That suggests to me that even if `Close Folder` would open a local window most users wouldn't try that command. So, I think we should look at `Close Folder` separate from 'How do I disconnect'.

### Close Folder

It seems to me that users fall broadly into three categories:
- primary use case is remote (Remote)
- primary use case is local (Local)
- going back an forth on a single folder (see https://github.com/microsoft/vscode-remote-release/issues/510 for an example)

I'm not sure the last group is affected as they want to keep working on the same folder, so `Close Folder` seems like an odd choice to achieve the context switching.

For the first two groups it makes sense that `Close Folder` preservers their default context. I don't think that we have a good indicator (other than history) that would allow us to differentiate the Remote from the Local group. In cases where this applies we usually go for a user setting. We can then discuss whether and if so in which way `New Window` may also be affected by such a setting (see https://github.com/microsoft/vscode-remote-release/issues/527).

### How do I disconnect

It seems that for some users 'close the remote window and open a new window' flow is also unintuitiv. I'd speculate that users almost exclusively fall into the group of users that use Remote only occassionally. They seem to be looking for a more explicit notion of 'get me back to my normal context'.

When taking the SSH perspective, it would make sense to introduce a `Disconnect from active SSH Host` command that is available through the bottom left remote indicator when in a SSH context. It would also be symmetric in the way that you can use the remote indicator to connect to and disconnect from SSH hosts.

Similar commands would make sense also for WSL and Containers although the naming seems more tricky. `Leave WSL` and `Disconnect from Container` might make sense.

**Comment by aeschli** [comment]
I added a new command `Close Remote Connection`. 
![image](https://user-images.githubusercontent.com/6461412/59265022-c60e4700-8c44-11e9-9b83-360fab5a9864.png)

![image](https://user-images.githubusercontent.com/6461412/59264961-9f501080-8c44-11e9-82a0-7609f418958e.png)

- the command reopens the window without an authority
- If you prefer a different name, let me know. I chose the name as we already use `Close Remote` in the error dialog.
- The command is contributed by the platform, no changes needed by remote extensions. Please speak up if you prefer that the extension contributes that command (e.g. because you rather want to call a custom command)
