### ISSUE TITLE
Extension kept asking permission to "enable and reload" after enable workspace trust support

### ISSUE THREAD

**Issue by NewtMa** [microsoft/vscode-remote-release#5019]
- VSCode Version: 1.56.0
- Local OS Version: Ubuntu 20 04 LTS with 5.4.0-72-generic
- Remote OS Version: CentOS 7 with 3.10.0-1160.24.1.el7.x86_64
- Remote Extension/Connection Type: SSH
- Logs:
[Host machine side log]
```
[10:18:39.124] Log Level: 2
[10:18:39.130] remote-ssh@0.65.4
[10:18:39.131] linux x64
```

[No Remote machine side extension log]

Steps to Reproduce:
https://github.com/github/feedback/discussions/categories/codespaces-feedback
1. enable `security.workspace.trust.enabled` setting;
2. choose "I trust this workspace";
3. and it kept prompting this window asking to enable Remoe-SSH extension and reload

![2021-05-08 10-04-40屏幕截图](https://user-images.githubusercontent.com/48610536/117522693-513a1800-afe7-11eb-95c1-a30f9081f219.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by bamurtaugh** [comment]
cc @sbatten

**Comment by sbatten** [comment]
@NewtMa I see you are using 1.56 of VS Code. While this is the latest stable release of VS Code, the workspace trust feature is in preview and many changes have been made in the latest insiders. Please verify with the latest insiders and SSH extension.

**Comment by sbatten** [comment]
Closing as outdated
