### ISSUE TITLE
Dev Container log terminal's name does not show in Terminal tabs(Preview)

### ISSUE THREAD

**Issue by eitsupi** [microsoft/vscode-remote-release#5020]
- VSCode Version:1.56.0
- Local OS Version:Windows
- Remote OS Version:Ubuntu 20.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Set the VSCode setting `"terminal.integrated.tabs.enabled": true`
2. Use the command `remote-containers.reopenInContainer`
3. Select "show log"
4. Add "New Terminal" and show the Terminal tabs

![image](https://user-images.githubusercontent.com/50911393/117531814-72b6f600-b01f-11eb-9232-cacc97da3bca.png)
![image](https://user-images.githubusercontent.com/50911393/117531815-7480b980-b01f-11eb-80f1-d7a1f9f902b9.png)

**Comment by chrmarti** [comment]
@Tyriar This appears to be fixed in 1.57-insiders. Good to close?
