### ISSUE TITLE
Connecting to non-bash device (OpenWRT)

### ISSUE THREAD

**Issue by thepian** [microsoft/vscode-remote-release#5021]
On the OpenWRT device I'm using bash isn't present, but rather /bin/ash. It seems that a script is sent by the tool that fails.

```
ready: 62f49ac44598
Linux 4.9.118 #77 PREEMPT Wed Feb 3 11:06:36 UTC 2021
-ash: bash: not found
-ash: syntax error: unexpected "(" (expecting "then")
Transferred: sent 18688, received 2264 bytes, in 0.1 seconds
Bytes per second: sent 318397.1, received 38572.9
```

**Comment by bamurtaugh** [comment]
Thanks for your issue @thepian! I believe this is being tracked in https://github.com/microsoft/vscode-remote-release/issues/542, so going to close this. If I've missed/misunderstood any part of your issue, please just let me know.
