### ISSUE TITLE
Unable to port forward from compute node in HPC

### ISSUE THREAD

**Issue by Subratappt** [microsoft/vscode-remote-release#5023]
From a terminal, we can do a port forwarding from a compute node of HPC to our local machine using,

`ssh -L 8282:compute001:8585 user@my_hpc`

where compute001,compute002 etc are the nodes in HPC. 

In this case, in Remote SSH we can forward a port only from localhost:8585 (**Remote**) to localhost:8282 , but not from **compute001:8585** to  localhost:8282

is there any workaround?

- VSCode Version: 1.56
- Local OS Version: Big Sur
- Remote OS Version: CentOS 7
- Remote Extension/Connection Type: SSH/Docker/WSL

**Comment by Subratappt** [comment]
> The direction is from the entity making the request to the entity responding to the request. Remote SSH can forward ports from the local machine (my_hpc) running the VSCode frontend to the remote machine running the VSCode server (compute001).
> What you want is reverse port forwarding [microsoft/vscode#100222](https://github.com/microsoft/vscode/issues/100222)
> AFAIK it's in the backlog.

I think there are some misunderstandings in question because I wrote  **forward to compute node** instead of **forward from compute node** .

**Actually what I want is**

`ssh -L 8282:compute001:8585 user@remote_hpc`

But using Remote SSH what I can able to do is similar to the following command,

`ssh -L 8282:localhost:8585 user@remote_hpc`

and this is the screenshot from vs code while connected to **remote_hpc** and forwarded remote port 8585 to local port 8282

![image](https://user-images.githubusercontent.com/40207448/117946956-612a6280-b32d-11eb-9337-61234835b462.png)

I want to forward remote **compute001:8585** (not the _localhost:8585_) to local localhost:8282

**Comment by alexr00** [comment]
@Subratappt think I see what you're asking. You want to make compute001:8585 accessible from localhost:8282 on your local machine, where compute001 **is not** the remote you're connected to with the Remote SSH extension. Is that correct?

I see why it would be useful, but that is out of scope since VS Code doesn't have anything running on your third machine, compute001.

**Comment by alexr00** [comment]
If its something that you can accomplish from the command line, you might consider making a [task ](https://code.visualstudio.com/Docs/editor/tasks#_custom-tasks)for it:
```
		{
			"label": "Make compute 8585 available locally",
			"command": "ssh -L 8282:compute001:8585 user@remote_hpc",
			"problemMatcher": [],
			"runOptions": {
				"runOn": "folderOpen"
			}
		}
```

**Comment by Subratappt** [comment]
> @Subratappt think I see what you're asking. You want to make compute001:8585 accessible from localhost:8282 on your local machine, where compute001 **is not** the remote you're connected to with the Remote SSH extension. Is that correct?
> 
> I see why it would be useful, but that is out of scope since VS Code doesn't have anything running on your third machine, compute001.

Yes, you are correct, Remote SSH is connected to `remote_hpc` and `compute001` is one of the node connected to `remote_hpc`.

**Comment by Subratappt** [comment]
> If its something that you can accomplish from the command line, you might consider making a [task ](https://code.visualstudio.com/Docs/editor/tasks#_custom-tasks)for it:
> 
> ```
> 		{
> 			"label": "Make compute 8585 available locally",
> 			"command": "ssh -L 8282:compute001:8585 user@remote_hpc",
> 			"problemMatcher": [],
> 			"runOptions": {
> 				"runOn": "folderOpen"
> 			}
> 		}
> ```

Thanks for this script.
