### ISSUE TITLE
VSCode Remote SSH extension does not fetch Git credentials from launch host

### ISSUE THREAD

**Issue by navneetkarnani** [microsoft/vscode-remote-release#5025]
Issue Type: <b>Bug</b>

Steps to reproduce:
- Create a Ubuntu VM on DigitalOcean
- Configure with login using key, instead of password
- Add configuration to ~/.ssh/config to use the right public key file
- Connect to the machine using Remote SSH extension
- Start terminal
- Try a `git clone` from a private repo, where the credentials are acceptable from the host that is running VS Code.

Expected:
Like "Remote Containers", the ssh credentials should be used from the laptop.

Actual:
Remote SSH does not use the "host" git credentials. Needs to get a "local/on the machine" credential.

Extension version: 0.65.4
VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin x64 20.4.0
Remote OS version: Linux x64 5.4.0-51-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.36GB free)|
|Process Argv|/Users/navneet/.ssh/config --crash-reporter-id 0dec9fd0-c8fd-4152-a33c-72a9d4647e00|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: remote-host|
|OS|Linux x64 5.4.0-51-generic|
|CPUs|DO-Regular (1 x 2199)|
|Memory (System)|0.96GB (0.10GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by roblourens** [comment]
Is your ssh key in the local ssh agent, and that is what you want to forward? Do you have ForwardAgent set in your config?

**Comment by navneetkarnani** [comment]
Yes, they key is in the local agent. 

I haven't set up anything specific. Don't need to do anything on the Remote Container Workflow.

Also, I did not see anything in the documentation that points me to any samples or types of forwarding agents.

**Comment by navneetkarnani** [comment]
With 1.56.2, I notice that, despite having created a local key on the remote host, and added that to the git server, the VSCode git fails on push, but when I use the terminal to `git push`, that works fine.

**Comment by roblourens** [comment]
> I haven't set up anything specific.

We are only spawning ssh here, you need to configure ssh to forward as usual
