### ISSUE TITLE
Containers: Git credentials helper is using wrong credentials

### ISSUE THREAD

**Issue by rubensa** [microsoft/vscode-remote-release#5026]
I have a problem with git credentials when I'm using the Remote Development Extension with Docker.
In the host everything works as expected.

In the host machine I have a `.ssh/config` file with tree different users configured for GitHub, like this:
```
Host github.com
	HostName github.com
	User git
	IdentityFile ~/.ssh/id_rsa_user1
Host github.com-user2
	HostName github.com
	User git
	IdentityFile ~/.ssh/id_rsa_user2
Host github.com-user3
	HostName github.com
	User git
	IdentityFile ~/.ssh/id_rsa_user3
```
Whit this configuration, from the host, I can connect to different github repositories using different users (each with it's own certificate).

For example, if I want to use connect to a repo using user3 I can simply clone the repo like this:
`git clone git@github.com-user3:user3/the-repo-name.git`

And I want to connect using the user1 (the default one) I can simply clone the repo like this:
`git clone git@github.com:user1/the-repo-name.git`

The certificate to use for the connection is based on the Host propery value, which is checked against the repository URL (`github.com-user3` in the fist example and `github.com` in se second; so `~/.ssh/id_rsa_user3` is used for the first connection and `~/.ssh/id_rsa_user1` for the second).

The problem I'm currently having is that, in a VSCode Terminal, the git credentials helper is, somehow, mixing credentials.
In a VSCode instance, for the repo with the user3, works as expected, but in other VSCode instance, for the repo with default user, it tries to use the user3 credentials.

```bash
$ git push
ERROR: Permission to user1/the-repo-name.git denied to user3.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

In the Docker container everything looks Ok, as the environment variable REMOTE_CONTAINERS_IPC is set and looks like the credentials helper ls "reaching" the host credentials (but the wrong ones for some repos).

- VSCode Version: 1.56.0
- Local OS Version: Ubuntu 20.04.2
- Remote OS Version: Ubuntu 20.04.1
- Remote Extension/Connection Type: Docker
- Logs: No logs as the git command is issued manually in the terminal.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by rubensa** [comment]
Looks like the problems was that in one container (the one that works) I was mounting my `.ssh` folder and in the other one (the one that does not work) I was not.

I think that the remote credentials helper should work without need to mount my `.ssh` folder in the container.

**Comment by chrmarti** [comment]
If that doesn't work, please attach the log (`F1` > `Remote-Containers: Show Container Log`) from that session.

**Comment by rubensa** [comment]
Tried just now, but no luck.  It's always using the first certificate to try to authenticate and, as it success, uses the wrong credentials for the repository.

**Comment by rubensa** [comment]
> It is possible that this does not work over an ssh-agent connection.

@chrmarti I found that that's the problem.

The easiest way to make it work is by copying `.ssh/config` and all `.ssh/*.pub` files from the host to the container (the private part of the key is not needed as that should be provided by the ssh-agent).

It would be great if that file copy could be automated on first container build or on container connect (for updates in the host), with an option to disable this automated copy if you don't want it to happen.

**NOTE**: As an alternative "manual" configuration (until this is eventually supported) you can copy just the `.ssh/id_rsa_user1.pub` (or the pub part of the key your repo needs) from the host to the `.ssh/id_rsa.pub` file in the container (as this is one of the predefined credential files used by ssh-agent).  Then the right key is used (as the matching private for the provided public key among all available keys is used).

**Comment by rubensa** [comment]
@chrmarti Could this automated copy of `.ssh/config` and `.ssh/*.pub` from host to container be done (as is currently been done for `.ssh/known_hosts`) or is not an option for any reason I'm missing?

**NOTE**: Other option could be to add new `devcontainer.json` properties like `postCreateCommand`, `postStartCommand` and `postAttachCommand` but to be run on the host machine (like `initializeCommand`), so the user could execute a `docker copy` command.  Also access to some variable with the container id should be provided (so the target container could be referenced in the copy command).  The container id must somehow currently be used internally by vscode-remote to interact with the container but don't know if that id is exposed to be used by other scripts.

**Comment by chrmarti** [comment]
We might consider adding a config option (a user setting, probably not in the devcontainer.json since it's user-specific) to copy arbitrary files to the container.

Another option might be to use `ssh-add` on the host machine to add the key you need and remove the others. Running multiple `ssh-agent`s on the host, one for each key, could also work, but I don't know if that would be convenient.

**Comment by rubensa** [comment]
I think that a user setting is not enough as for the same user you need to copy different files for different containers so I think that the setting should be linked to the specific container (and user).  
Is there some kind of `devcontainer.json` by user override mechanism available?  Think that right now that mechanism does not exist and you must "touch" locally any thing you want to override in the project `devcontainer.json`.

I don't know if using multiple `ssh-agent` on the host could be automated but think It would be difficult to get the "link" between the right agent with the right VSCode workspace.

**Comment by chrmarti** [comment]
https://github.com/microsoft/vscode-remote-release/issues/3279 is about overlaying devcontainer.json (in a slightly different context).

**Comment by rubensa** [comment]
> #3279 is about overlaying devcontainer.json (in a slightly different context).

Nice to know about that proposal.

**Comment by rubensa** [comment]
@chrmarti I think that It's a bit difficult for this issue to be upvoted as there is not a specific feature-request and the description in the original issue is not very correct (I know now, after all the comments, but not when I opened the original issue).

To summarize (should I open a new feature-request with this?):

**Featrue-Request**: Automate the copy of `~/.ssh/config` and `~/.ssh/*.pub` from the host to the container.

- This process should be done as currently is been done for `~/.ssh/known_hosts`.
- Ideally there should be a setting for the container and user pair (see: #3279 about overlaying `devcontainer.json`).
- As, for now, this is not possible, the config setting should be allowed both as a user (for all containers for this user) and `devcontainer.json` (for all users of this container) setting.  You can choose with one to use.

This should solve the problem that the ssh client inside the container is not providing the right ssh credentials (when multiple credentials are added to the host `ssh-agent`).

**Comment by chrmarti** [comment]
A new issue would make sense. 👍 

What is the reason mounting the `.ssh` folder is not a workable solution?

**Comment by rubensa** [comment]
Cause is "risky" as, if you mount your hole .ssh folder, the Container has access to your private ssh keys (and that's the reason for using the ssh-agent in the first place, isn't it?)   With the provided proposal, the Container only sees the public keys and the ssh-agent in in charge for providing the private ones.

**Comment by rubensa** [comment]
Feature request created: https://github.com/microsoft/vscode-remote-release/issues/5207

**Comment by chrmarti** [comment]
Continuing there, thanks.
