### ISSUE TITLE
No intellisense in python

### ISSUE THREAD

**Issue by TheLogan** [microsoft/vscode-remote-release#5027]
Issue Type: <b>Bug</b>

I'm afraid there's not much to say as far as steps go.
I just installed wsl 2 on my pc, setup remote ssh to my raspberry pi started a python file, but I have no intellisense, I'm not sure what I can try, I've attempted to log out and back in again to no avail.

Extension version: 0.64.0
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux arm 5.10.17-v7l+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (6.23GB free)|
|Process Argv|--crash-reporter-id 1efda3ab-0f5c-4420-8588-0cf4e8fcf834|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.0.53|
|OS|Linux arm 5.10.17-v7l+|
|CPUs|ARMv7 Processor rev 3 (v7l) (4 x 1500)|
|Memory (System)|3.74GB (3.42GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvsnew554cf:30291488
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
bridgeflight:30299254

```

</details>

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
