### ISSUE TITLE
Ignoring default terminal

### ISSUE THREAD

**Issue by gparmeggiani** [microsoft/vscode-remote-release#5029]
I just updated to the latest vscode and, therefore to Remote-Containers 0.177.0
and I noticed that it loads `sh` as the default shell when starting VSCode. I did configure `bash` as my default and if I create a new terminal with "terminal > new terminal" it works fine and bash starts.

I tried the same with remote-SSH and it works fine.

Could this be a regression bug? Could it be that I'm misconfiguring something in devcontainer.json?

- VSCode Version: 1.56.0
- Local OS Version: WIndows 10 1909
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Docker
- Logs: N/A

Steps to Reproduce:

Open a new vscode instance with remote Containers while having bash set as default.

**Comment by chrmarti** [comment]
Where do you set bash as default? (/etc/passwd, user settings, devcontainer.json settings)

**Comment by gparmeggiani** [comment]
I'm using a non-root user on a Ubuntu 20.04 container. To create the "dev" user I followed the instructions here https://code.visualstudio.com/docs/remote/containers-advanced#_adding-a-nonroot-user-to-your-dev-container

I checked /etc/passwd and it has sh as the shell, not bash.

I'm setting the default shell in the user settings (in the AppData folder in Windows) like so:
```
    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "bash"
        }
    },
    "terminal.integrated.defaultProfile.linux": "bash"
```

I now tried to change the login shell in /etc/passwd (I added `-s /bin/bash` in the Dockerfile when calling `useradd`) and it works fine ( I get the bash shell).

However, I still think this is an issue. In my opinion it should be possible to override the /etc/passwd shell with the vscode settings (user settings or devcontainer.json settings)

**Comment by gparmeggiani** [comment]
Also, In my devcontainer.json file I have the following:

```
"settings": {
        "terminal.integrated.detectLocale": "off"
}
```

And it is no longer applied to the default terminal that is started after opening up vscode. The setting is however applied if I create a new terminal, after vscode started.
This is a regression over the previous vscode remote - containers behavior

**Comment by chrmarti** [comment]
The wrong first shell opening is fixed in VS Code Insiders. The same might be true for the defaultLocale, could you give the Insiders build a try (installs alongside the stable version): https://code.visualstudio.com/insiders/
