### ISSUE TITLE
Can't reopen in container: vscode-dev-containers\containers\docker-existing-docker-compose 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#503]
Testing https://github.com/microsoft/vscode-remote-release/issues/495

I tried to open the docker-existing-docker-compose sample from the containers repo, and it failed:
```
Setting up container for folder: d:\repos\Microsoft\vscode-dev-containers\containers\docker-existing-docker-compose
Run: docker-compose -f d:\repos\Microsoft\vscode-dev-containers\containers\docker-existing-docker-compose\docker-compose.yml -f d:\repos\Microsoft\vscode-dev-containers\containers\docker-existing-docker-compose\.devcontainer\docker-compose.yml config --services
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: 'd:\\repos\\Microsoft\\vscode-dev-containers\\containers\\docker-existing-docker-compose\\docker-compose.yml'
Command failed: C:\Program Files\Docker\Docker\Resources\bin\docker-compose.exe -f d:\repos\Microsoft\vscode-dev-containers\containers\docker-existing-docker-compose\docker-compose.yml -f d:\repos\Microsoft\vscode-dev-containers\containers\docker-existing-docker-compose\.devcontainer\docker-compose.yml config --services
```

**Comment by chrmarti** [comment]
Could you try a different sample?

@Chuxel Should we make this sample self-contained in that it comes ready to run?

**Comment by alexr00** [comment]
Tried the Node and Mongo template per your suggestion: https://github.com/microsoft/vscode-remote-release/issues/504

**Comment by Chuxel** [comment]
@chrmarti @alexr00 We could add some test assets, but the idea is this is applied to your existing project when you have a Dockerfile as a base.  So if you dropped it into a project without an existing Dockerfile, it wouldn't work. I'd envisioned these to be used by the automated process when we detect a Dockerfile or Docker Compose file so we can more easily update the contents.

**Comment by chrmarti** [comment]
@Chuxel Should we update the wizard to use these when using an existing Dockerfile / docker-compose.yml? And not show them in the list of definitions when starting without one?

**Comment by Chuxel** [comment]
@chrmarti Yeah I think that's a great idea.  Only note is the Docker Compose one uses the "extend" trick, so there's a few "your-service-name-here" spot in the docker-compose.yaml file that would need to get modified.

**Comment by chrmarti** [comment]
Tracking as #3683 now.
