### ISSUE TITLE
[Critical] VSCode Server does not work as expected

### ISSUE THREAD

**Issue by kpalatzky** [microsoft/vscode-remote-release#5035]
- VS Code Version: `1.56.0 (user setup), Commit: cfa2e2`
- OS Version: `Windows_NT x64 10.0.18363`

Steps to Reproduce:

1. Connect to SSH Remote Host
2. Open directory (Do not open any files in main view)
3. Use Search / File search
4. Searches does not find anything. (There are also more problems with git & co)

Does this issue occur when all extensions are disabled?: Yes/No
Yes. I disabled all plugins except the `ms-vscode-remote.remote-ssh` since this is required to reproduce this error.

**Comment by kpalatzky** [comment]
@roblourens you are right, i do not have `Log (Remote Extension Host)`. I currently have the following log entries when i am connected to my remote host:

- `Tasks`
- `Extensions`
- `Remote - SSH`
- `Microsoft`
- `Authentication`
- `GitHub`
- `Authentication`
- `Log (Extension Host)`
- `Log (Settings Sync)`
- `Log (Window)`
- `Log (Shared)`
- `Log (Main)`
- `Log (Remote Server)`

Now how can I find out why the remote extension host is not connected?

**Comment by kpalatzky** [comment]
@roblourens you are right, i do not have `Log (Remote Extension Host)`. I currently have the following log entries when i am connected to my remote host:

- `Tasks`
- `Extensions`
- `Remote - SSH`
- `Microsoft`
- `Authentication`
- `GitHub`
- `Authentication`
- `Log (Extension Host)`
- `Log (Settings Sync)`
- `Log (Window)`
- `Log (Shared)`
- `Log (Main)`
- `Log (Remote Server)`

Now how can I find out why the remote extension host is not connected?

You find a full log of `Remote - SSH` (I changed the domain / IP Addresses ) attached: 
[vscode.log](https://github.com/microsoft/vscode-remote-release/files/6464268/vscode.log)

When i connect with VS-Code ` sudo lsof -i -P -n`  shows the new 2 entries:

```


sshd      32499            root    4u  IPv4 147942      0t0  TCP 10.26.104.56:22->10.97.0.18:60697 (ESTABLISHED)
sshd      32515       kpalatzky    4u  IPv4 147942      0t0  TCP 10.26.104.56:22->10.97.0.18:60697 (ESTABLISHED)
```

**Comment by kpalatzky** [comment]
@roblourens Any update on this?

**Comment by kpalatzky** [comment]
@chrmarti @egamma Since this ticket was moved. Can you guys please have a look at this.

This currently hinders us enormously in our work, as almost no feature work

**Comment by kpalatzky** [comment]
@chrmarti  @egamma  @roblourens Can you please help us debug further here. We would like to fix this bug as soon as possible!

**Comment by coldcaz** [comment]
Unfortunately this is a serious problem for me and my colleagues right now. Without a working Git integration and all the extensions, and especially the not properly worked search feature, most reasons I use VS Code for a no longer given.

However, I really like working with VS Code and in general it's working perfectly fine. Is there any information I could provide you with that might help getting this fixed?

**Comment by chrmarti** [comment]
Have you checked https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc as suggested? Does this still occur when you turn file watching off completely? How much space is left on the mounted disks? Are you seeing this with any SSH server or only with specific ones?

**Comment by coldcaz** [comment]
@chrmarti I added `files.watcherExclude`and `search.exclude` for some not required folders (node_modules, build result, ...). This removed the `accept: Too many open files` error. However, file search, extensions and git integration are still not working.

However, I get the message 
`[2021-05-20 12:22:56.351] [remoteagent] [info] [127.0.0.1][c0f32e38][ExtensionHostConnection] The client has reconnected.`
logged every couple of seconds into the Log (Remote Server) window. I'm wondering if this might be causing the issue? 

I just tried everything with a clean VS Code installation on both server and client, unfortunately without any change.
My remote machine has ~50GB of free space left, so I don't think this should be causing the issue.

**Comment by chrmarti** [comment]
Regular `The client has reconnected.` messages could indicate a connection problem. Maybe compare the sshd versions between a SSH server with and a SSH server without the problem.

Also: Does this occur will any workspace folder or only a specific one?

**Comment by kpalatzky** [comment]
@chrmarti Both servers are up to date:

Working:
`OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020`

Non-Working:
`OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020`

On both servers i opened `/var/log/apt` (I never opened this folder before using vscode). And still it is working for the "working" one and not working for the not working one. 
So i would assume it occur for any workspace folder. 

It should probably not be due to SSH directly. I am almost always connected to the server with SSH (Windows Terminal) - this connection never has any problems.

**Comment by kpalatzky** [comment]
@chrmarti  Any update on this?

**Comment by kpalatzky** [comment]
@chrmarti @egamma @roblourens any update?

**Comment by chrmarti** [comment]
@kpalatzky Unfortunately not. My best guess is a connection problem, but I don't know how to confirm/disconfirm that. Can you increase the log level for the SSH server and the SSH client and see if that helps narrowing it down?

**Comment by coldcaz** [comment]
Hey @chrmarti,
it seems like with the latest update everything works fine again. I did nothing apart from installing the latest version (via the update pop-up), so I assume something got fixed here.
I'm now running on:

- VS Code v.1.58.0
- VS Code Remote SSH v.0.65.7

However, thanks for your support. From my side, this one can be closed.

**Comment by kpalatzky** [comment]
The ticket is also fixed for me. The client can connect to the "Remote Extension Host" again.

VS Code v.1.58.0
VS Code Remote SSH v.0.65.7
