### ISSUE TITLE
default ssh connection

### ISSUE THREAD

**Issue by sjd-lab** [microsoft/vscode-remote-release#5036]
Issue Type: <b>Feature Request</b>

After connecting and working in remote server (I use ssh for remote python). On re-opening vs code, it tries to reconnect. But there is no option to cancel the reconnection attempt. May be vs code is opened just for viewing a local file.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

**Comment by sjd-lab** [comment]
Yes of course I can open another window, close connection etc... But an escape, while connection attempt would be nice/convinient feature i think.

**Comment by roblourens** [comment]
While it's connecting, you can open a new folder, or an empty window, or whatever you want to do, so I don't really see the need for a cancel button or something like that.
