### ISSUE TITLE
Containers + stable + insiders + compose has version mismatch

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#504]
Testing https://github.com/microsoft/vscode-remote-release/issues/495

1. Have an empty folder open in stable.
2. Reopen in container and choose the Node & mongo template
3. Once stable is done opening in the container, open insiders on the same folder.
4. That folder now has a .devcontainer folder and can be re opened in container. Reopen it in container.
5. "Failed to connect to the remote extension host server (Error: Connection error: Version mismatch, client refused.)"

**Comment by chrmarti** [comment]
/duplicate #500

Not the same error, but #500 could have caused this and neither @alexr00 nor I can reproduce it with the latest version of the extension.
