### ISSUE TITLE
Confusing terminology when opening containers

### ISSUE THREAD

**Issue by Oliver-Sellwood** [microsoft/vscode-remote-release#5046]
- VSCode Version: 1.56
- Remote Extension/Connection Type: Docker

Hi,

I find the terminology a little confusing when attaching vs opening folder in container and end up usually guessing which one I want.

The current terminologies are `Attach to Container` and `Open Folder in Container`. From my point of view it would involve less guess work if they said something like `Open in New Window` and `Open in This Window`.

Thanks!

**Comment by chrmarti** [comment]
There are more differences: `Open Folder in Container` requires a `.devcontainer/devcontainer.json` file in the folder that includes configuration on how to create the container. `Attach` requires an existing container.

**Comment by Oliver-Sellwood** [comment]
I haven't used `devcontainer.json` personally. I only ever launch a container and then `attach` in the list of containers.  But both these are options on an existing container that has already been attached to at least once

**Comment by chrmarti** [comment]
I guess one ambiguity here is that 'Folder' in 'Open Folder in Container' doesn't say if it is a local folder (which it is) or some folder in a container. We could clarify by making it 'Open Local Folder in Container'.

**Comment by Oliver-Sellwood** [comment]
Here is a rough set of steps to repro

1. Create a container `docker run --rm -it python:3.8 bash`
2. Open code, navigate to containers screen and find the container just launched
3. the only option for this container is `Attach to Container`, clicking this opens in a new window
4. Close all code instances and start a new one (that isn't connected to the container)
5. Go back to the Containers screen, now there are two options `Attach to Container` and `Open Folder` in Container`
   a. Clicking `Open Folder` replaces the current code instance 
   b. Clicking `Attach to Container` opens a new code instance
   
   
> I guess one ambiguity here is that 'Folder' in 'Open Folder in Container' doesn't say if it is a local folder (which it is) or some folder in a container
For my use case there is no local folder (or if there is code doesn't know about it because I deployed the container outside of code)

**Comment by chrmarti** [comment]
Keeping the established labels for now. Thanks.
