### ISSUE TITLE
Provide a way to programmatically launch remote folder with provided ssh config entry

### ISSUE THREAD

**Issue by vilic** [microsoft/vscode-remote-release#505]
We are trying to prepare remote development environment for each feature/fix, and thus connection config would vary each time.

**Comment by roblourens** [comment]
You should be able to do this with the `vscode.openFolder` command with a URI like `vscode-remote://ssh-remote+hostname/path/to/project` but SSH should provide an easier to use command

**Comment by roblourens** [comment]
I think you can do this via the CLI args, as mentioned in the other isseu
