### ISSUE TITLE
Can you open vscode and connect via ssh from your client's terminal?

### ISSUE THREAD

**Issue by alshdavid** [microsoft/vscode-remote-release#5053]
I'd like to open vscode from the terminal window but have it connect to my ssh remote automatically upon opening, does such a feature exist?

I'm thinking something like:

```
code ssh:HomePC:/home/username/project
code ssh:username@remote.mydest.com:/home/username/project
```

**Comment by bamurtaugh** [comment]
Thanks for your issue @alshdavid! 

I believe this would fall under https://github.com/microsoft/vscode-remote-release/issues/656. If I've misunderstood the request here, please just let me know. Thanks!
