### ISSUE TITLE
devcontainer crashes with no useful logs

### ISSUE THREAD

**Issue by lhl2617** [microsoft/vscode-remote-release#5054]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: Windows 10 Version 20H2 (OS Build 19042.867)

Steps to Reproduce:

1. Clone this repository: https://github.com/jeandeaual/lilypond-template
2. Start the devcontainer in that repository
3. Open `main.ly`
4. You should see a `Play MIDI` button in the status bar below--click it.
  ![image](https://user-images.githubusercontent.com/33488131/118205323-f9bd0180-b457-11eb-82ba-258b2e242578.png)
5. Devcontainer crashes with no useful logs
  ![image](https://user-images.githubusercontent.com/33488131/118205390-283adc80-b458-11eb-99e8-c81c3554500f.png)
  ![image](https://user-images.githubusercontent.com/33488131/118205423-3852bc00-b458-11eb-8bc6-b10aaa624cea.png)
 Docker container appears to still be running
  ![image](https://user-images.githubusercontent.com/33488131/118207450-997c8e80-b45c-11eb-914f-45062160c321.png)

More details:

- The extension in question (https://github.com/lhl2617/VSLilyPond) works fine locally.

- All MIDI-related features cause this behavior--I'm investigating why, but not having any logs is cumbersome.

- This issue can be replicated with VSCode Remote-WSL2

**Comment by chrmarti** [comment]
I guess this doesn't reproduce when you play by command in the integrated terminal?

Does it reproduce when all you do is install lilypond and the extension in a debian:buster container?

**Comment by lhl2617** [comment]
After further investigation it is because of an extension dependency that calls out to system code--it crashed catastrophically and the error was not caught in the electron environment

I'll treat this as solved
