### ISSUE TITLE
CMake configure issue

### ISSUE THREAD

**Issue by haeginh** [microsoft/vscode-remote-release#5058]
I am working on C++ project which includes multiple files and headers of external libraries.
For the configuration, I am using CMake extensions which works wonderfully in local usages.
However, when I do the same thing in remote-SSH, vsCode cannot not configure the included files and report problems, even though configure&build with CMake succeeded.
Due to this issue, vsCode generates a bunch of  "cannot open source file **.hh" and smart completion of intellisense also dosen't work. 
Is there any way I can use intellisense with the configuration with CMake in Remote-SSH?

**Comment by chrmarti** [comment]
Could you file an issue for the extension that isn't working? Include any logs the extension might write. Thanks.
