### ISSUE TITLE
Test: Stable vs Insiders with SSH

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#506]
https://github.com/microsoft/vscode-remote-release/issues/418

- [x] Windows
- [x] Non-Windows @lramos15 

Complexity: 2

Use Stable (1.35 RC) and Insiders to test running side-by-side with the same SSH remote. Make sure extensions, settings and CLI command name are distinct for the two.

The Stable server should be installed under `~/.vscode-server`, Insiders under `~/.vscode-server-insiders`

**Use the Nightly SSH extension for both cases**

**Comment by roblourens** [comment]
Part 2:

Data and extensions will be migrated from ~/.vscode-remote to ~/.vscode-server

Please try this:

- Delete `~/.vscode-server*` if you attached with nightly before
- Connect with the stable version of the SSH extension and install some extensions
- Connect with the nightly version of SSH and ensure that the extensions are still there

**Comment by mjbvz** [comment]
Signing off on part 2. Tested this with both a VS Code 1.35 stable and VS Code insiders and confirmed extensions / data is migrated

**Comment by roblourens** [comment]
Thanks!
