### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by rusakakstp** [microsoft/vscode-remote-release#5061]
Issue Type: <b>Bug</b>

[13:51:17.929] stderr> -bash: line 2: /bin/uname:  permission denied

my ssh account doesn't have permission for /bin/uname cause of i'm using web hosting. How can i connect with this account?

Extension version: 0.64.0
VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:35:15.302Z)
OS version: Darwin x64 19.0.0
Fetching remote diagnostics for 'SSH' failed: Connecting with SSH timed out

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: Connecting with SSH timed out
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by roblourens** [comment]
Can you suggest another way to detect the platform? Also you can set `"remote.SSH.useLocalServer": false` to work around this. But if you don't have permission for uname, my guess is that it will fail at another step.
