### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by AugustoEstevaoMonte** [microsoft/vscode-remote-release#5062]
When i open VSCode today i got this bug:

/mnt/c/Users/augus/AppData/Local/Programs/Microsoft VS Code/bin/code: 46: cannot create /tmp/remote-wsl-loc.txt: Permission denied

Please help me!

**Comment by bamurtaugh** [comment]
Thanks for your issue. You've been using Remote-WSL successfully up to this point?

Does restarting WSL help? Something like:

```
wsl --shutdown
wsl
```

**Comment by AugustoEstevaoMonte** [comment]
Restarting is not working, I had new errors today and I can't even access anymore.

`/mnt/c/Users/augus/AppData/Local/Programs/Microsoft VS Code/bin/code: 46: cannot create /tmp/remote-wsl-loc.txt: Permission denied
/mnt/c/Users/augus/AppData/Local/Programs/Microsoft VS Code/bin/code: 52: /mnt/c/Users/augus/.vscode/extensions/ms-vscode-remote.remote-wsl-0.56.2/scripts/wslCode.sh: not found`

**Comment by bamurtaugh** [comment]
What version of WSL (i.e. WSL 1/2, distro), VS Code, and Remote-WSL are you using?

Was Remote-WSL previously working for you, and it randomly started giving you this error, or started giving you this error after any sort of Windows or VS Code update?
