### ISSUE TITLE
Explore publishing Remote-Containers through CI/CD

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#5069]

**Comment by chrmarti** [comment]
@JacksonKearl Thanks for putting the sample for the gated workflow together! While studying that I realized that I regularly test a VSIX and then have to add another commit to fix or polish something. Due to that I also only add a version tag after testing, when I'm ready to publish the VSIX.

I have now put together a workflow triggered on a version tag, that then downloads and publishes the VSIX built earlier. (Not tested on the actual extension yet.) That turned out reasonably simple, let me know if you have any feedback, thanks! https://github.com/microsoft/vscode-remote-containers/blob/main/.github/workflows/publish-remote-containers.yml

**Comment by JacksonKearl** [comment]
Neat trick, makes sense to me!
