### ISSUE TITLE
Recovery container does not work on ARM based Mac (e.g. M1)

### ISSUE THREAD

**Issue by ryangoss** [microsoft/vscode-remote-release#5072]
While editing the Dockerfile for the VSCODE-REMOTE-TRY-PYTHON dev container I made a mistake in syntax which made the image not build.  I attempted 'Open Dockerfile in Recovery Container', but this failed to load with this pop-up

> Alpine Linux is not supported on the hardware architecture 'aarch64' of the container.

Here's the console from the container
```
[809 ms] Start: Run in container: uname -m
[1030 ms] aarch64
[1031 ms] 
[1031 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[1032 ms] NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.2
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

The 'Learn More' option just tells me about Linux with remote systems https://code.visualstudio.com/docs/remote/linux

Note I have Alpine Linux running in many other containers on my Mac.

**Comment by chrmarti** [comment]
Tracked as https://github.com/microsoft/vscode-remote-release/issues/4462, thanks.
