### ISSUE TITLE
Temp directory not found on Windows if TEMP directory is set to other drive

### ISSUE THREAD

**Issue by hooyao** [microsoft/vscode-remote-release#5075]
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

- VSCode Version: 1.56.2 (user setup)
- Local OS Version: Windows_NT x64 10.0.19042
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: SSH
- Logs: Could not establish connection to "121.89.244.77": Failed to write install script to path Z:\AppData\Local\Temp\vscode-linux-multi-line-command-121.89.244.77-756851628.sh. ENOENT: no such file or directory, open 'Z:\AppData\Local\Temp\vscode-linux-multi-line-command-121.89.244.77-756851628.sh'.

Steps to Reproduce:

1. Set Windows environment variable `TEMP` and `TMP` to `Z:\TEMP` <== any directory other than default
2. Try to connect remote host via SSH, error dialog pops up
3. If creating AppData\Local\Temp in Z:\TEMP, it works as expected. Obviously, the plugin doesn't test if the Temp directory exists, if not it doesn't create by itself.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
I don't think it's right for the extension to create a temp directory that doesn't exist. To me that would indicate that something else went wrong.
