### ISSUE TITLE
Invalid mount path when connecting docker from windows to linux

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-remote-release#509]
Re #474

* Followed https://github.com/microsoft/vscode-remote-release/issues/474#issuecomment-496870048 to connect from Windows to a docker daemon on Ubuntu VM
* Open folder in container https://github.com/microsoft/vscode-dev-containers/tree/master/containers/typescript-node-lts 
* See below error

```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: invalid mount config for type "bind": invalid mount path: 'c:/Users/penlv/code/vscode-dev-containers' mount path must be absolute.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'
```

**Comment by rebornix** [comment]
It's actually a duplicate of https://github.com/microsoft/vscode-remote-release/issues/489 but I still see this issue with 0.57.0

**Comment by chrmarti** [comment]
We automatically mount the project folder, but that is not possible when using a Docker daemon running on a different machine / VM. I'm not sure if there is an easy and reliable way to detect this case and not do the mount. (We could just not do it when `"docker.host"` is set.)

**Comment by egamma** [comment]
Closing: the user has to define `workspaceMount` in this setup.

**Comment by Chuxel** [comment]
Actually this is still an issue.

**Comment by Chuxel** [comment]
The specific issue here is with an .gitconfig resulting in an invalid mount point.  The mount **does not fail**, however, Docker automatically creates a new path on the host to support the requirement.  For example, on my mac, .gitconfig is under `/Users/chuck/.gitconfig` for a user. Here's what I see on my remote Ubuntu SSH machine:

```
📁 Users
     📁 chuck
          📁 .gitconfig
📁 home
     📁 clantz
          📁 .ssh
          📁 .vscode-server
          📁 Repos
          📄 .gitconfig
```

The `Users` directory tree is created by Docker as a result of specifically the `.gitconfig` volume mount that you cannot override right now.

**Comment by wmeints** [comment]
This also fails when you're using Docker Desktop on Windows. I would expect for it to work normally there as this is a scenario that is widely used.

**Comment by Chuxel** [comment]
@wmeints If you running into trouble while using Docker locally, then that's a separate issue.  Docker for Windows is known to work (I use it every day 😊).  If you are using Windows containers (less common), then that's #29.  But, if you're running Linux, it would be great if you'd raise an issue on it with your log details so we can try to help you sort it out.

**Comment by wmeints** [comment]
Thanks for the kind reply. I investigated it further and found some really weird behavior. I Will open a separate issue for that.

**Comment by chrmarti** [comment]
https://github.com/microsoft/vscode-remote-containers/commit/4f76bf525bc138e8fbc2bbfdc21f19c406e4cefa

**Comment by chrmarti** [comment]
Verifier: The fix was to copy the .gitconfig into the container instead of trying to mount it. https://github.com/microsoft/vscode-remote-containers/commit/4f76bf525bc138e8fbc2bbfdc21f19c406e4cefa

Verify that the .gitconfig (if it exists in your local home folder) is indeed copied to the container (if it does not exist there yet) when the container is first created (but not later, e.g., after manually deleting it from the container).
