### ISSUE TITLE
Unable to Remote SSH into Virtualbox guest running Alpine Linux 3.13

### ISSUE THREAD

**Issue by bdutta** [microsoft/vscode-remote-release#5090]
Issue Type: <b>Bug</b>

Trying to setup a dev environment with VS-Code (downloaded/installed last night) running on Windows 10 Enterprise (fairly up to date), by remote SSH into a guest VM running on Virtualbox hypervisor, with the guest OS being Alpine Linux 3.13. I can use Windows SSH client (from cmd terminal) to log into the guest VM as `ssh -p 8022 myusername@127.0.01` successfully, and the guest VM already has `git` and `wget` installed. I was expecting to be able to use this remote-development setup, since Alpine Linux (>= 3.9) seems to be supported used in Containers and WSL (so in theory, I assumed it to be workable in Virtualbox). 

Extension version: 0.65.4
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (21.24GB free)|
|Process Argv|--crash-reporter-id 41503a03-e6dd-41db-9faf-8417180142d1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30301612
vscorehovct:30302760
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by bamurtaugh** [comment]
cc @roblourens is Alpine Linux supported for Remote-SSH? Based on our [docs](https://code.visualstudio.com/docs/remote/linux), it looks like it's supported in Remote - Containers and Remote - WSL only, but wasn't sure if using Virtualbox would affect anything.

**Comment by roblourens** [comment]
Alpine is not supported for SSH, I haven't been able to get it to work. https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites
