### ISSUE TITLE
Display username in connection for remote-ssh session

### ISSUE THREAD

**Issue by huili80** [microsoft/vscode-remote-release#5095]
It would be useful to display username and host name in connection instead of just host name.

**Comment by PavelSosin-320** [comment]
Yes!, I vote for this feature of course because modern Linux allows the creation of several isolated sessions (slices) for the rootless users via systemd-sshd and systemd-user with different privileges (out-of-the-box!!!) and it will be a big mess if the remote user will use the wrong session.

**Comment by bamurtaugh** [comment]
Thanks for the request @huili80. Where would you envision displaying the username? I'd envision the remote indicator in the lower left could get quite long showing both the user and host.

**Comment by huili80** [comment]
Aside from potentially being too long, I would like to see "SSH: <user>@<host>" in every spot where it currently only shows "SSH: <host>", including the remote indicator in the lower left, the window title bar, settings, to name a few examples.

If having both <user> and <host> makes it too long, maybe we could have an option to say whether to display both <user>@<host>, or just <host>. Additionally, it would be great if we could assign a "label" to a SSH session in ssh configurations, so instead of showing <host> (or <user>@<host>), it would just show the "label", and possibly let a tooltip show the full <user>@<host> info when hovering mouse over.

Thanks for considering this request!
