### ISSUE TITLE
Remote containers connecting to previously configured docker.host even after changing the docker.host 

### ISSUE THREAD

**Issue by parmanandchaturvedi** [microsoft/vscode-remote-release#5097]
- VSCode Version: 
  Version: 1.56.2 (user setup)
  Commit: 054a9295330880ed74ceaedda236253b4f39a335
  Date: 2021-05-12T17:13:13.157Z
  Electron: 12.0.4
  Chrome: 89.0.4389.114
  Node.js: 14.16.0
  V8: 8.9.255.24-electron.0
  OS: Windows_NT x64 10.0.18363
- Local OS Version: Windows 10 Enterprise build 1909 
- Remote OS Version: Linux  4.19.107-1.wf31.x86_64 #1 SMP Mon Mar 2 09:26:01 EET 2020 x86_64 x86_64 x86_64 GNU/Linux
- Remote Extension/Connection Type: SSH/Docker/WSL: SSH
- Logs:
[157951 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[204164 ms] 
error during connect: Get http://docker/v1.40/version: command [ssh -l mbm -p 22 -- <hostname> docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=ssh: connect to host <hostname> port 22: Connection timed out

Steps to Reproduce:

1.  open VS code, add docker.host as ssh://<hostname>:<port> in settings.json  
2. go to remote containers explore tab, it shows remote containers
3. now change the docker.host as ssh://<hostname2>:<port> in settings.json to new host , save and reload the window 
4. Again go to go to remote containers explore tab, it tries to find the containers, but gets an error which clearly shows it is trying to connect to previously configured docker host i.e ssh://<hostname>:<port>

**Comment by chrmarti** [comment]
The Remote Explorer shouldn't need a window reload. "Connection timed out" suggests there might be a problem with your network connection to the remote host. Can you ssh to the machine from the shell?
