### ISSUE TITLE
SSH authentication succeeds but crashes immediately after

### ISSUE THREAD

**Issue by m0bi5** [microsoft/vscode-remote-release#5099]
- VSCode Version:1.56.2
- Local OS Version: macOS BigSur 11.3.1
- Remote OS Version: Ubuntu 16.04.6
- Remote Extension/Connection Type: SSH
- Logs:

```

Authenticated to REMOTE_IP_HERE
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-154-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

0 packages can be updated.
0 updates are security updates.


ready: e876ecf7858c
Linux 4.4.0-154-generic #181-Ubuntu SMP Tue Jun 25 05:29:03 UTC 2019
e876ecf7858c: running
bash: line 1: _exitcode: command not found
bash: line 2: syntax error near unexpected token `elif'
bash: line 2: `	elif [[ $ALLOW_CLIENT_DOWNLOAD == "1" ]]; then'
-sh: 4: function: not found
-sh: 69: [[: not found
-sh: 90: [[: not found
-sh: 155: Syntax error: "(" unexpected (expecting "then")
Transferred: sent 17056, received 3616 bytes, in 1.0 seconds
Bytes per second: sent 16313.2, received 3458.5

[20:05:47.665] Failed to parse remote port from server output
[20:05:47.666] Resolver error: Error: 
	at Function.Create (/Users/m0bi5/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:64641)
	at Object.t.handleInstallOutput (/Users/m0bi5/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:63284)
	at Object.e [as tryInstallWithLocalServer] (/Users/m0bi5/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:386419)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/m0bi5/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:294035
	at async Object.t.withShowDetailsEvent (/Users/m0bi5/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:405329)
	at async /Users/m0bi5/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:384890
	at async E (/Users/m0bi5/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:381658)
	at async Object.t.resolveWithLocalServer (/Users/m0bi5/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:384517)
	at async Object.t.resolve (/Users/m0bi5/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:295505)
	at async /Users/m0bi5/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:127:110530
[20:05:47.671] ------

```

Steps to Reproduce: Just following the normal steps suggested in the documentation. 

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by rddesmond** [comment]
Not necessarily a solution, but I was able to get ssh to work with no modifications to the configs (on either server-side or client-side), by downgrading the plugin to 0.49.  (I haven't tested to see where the breaking change is though.)

A different error, but I got the 0.49 version from https://github.com/microsoft/vscode-remote-release/issues/3958.  Perhaps it's related?

My specs are similar:
> VSCode Version:1.56.2
> Local OS Version: Ubuntu 20.04.2
> Remote OS Version: Ubuntu 16.04.6
> Remote Extension/Connection Type: SSH

**Comment by ykun91** [comment]
I have encountered same issue, it seems that it was caused by the `sh` shell.
use `usermod -s /bin/bash` to change shell to `bash` solved my problem.

> VSCode Version:1.60.0
> Remote-SSH Version: v0.65.7

**Comment by zhuhaoqiang0** [comment]
change login shell from /bin/sh to /bin/bash solve my problem
login the remote sever from command line and then type chsh and change the login in shell

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/5439

**Comment by VaheShelunts** [comment]
> change login shell from /bin/sh to /bin/bash solve my problem login the remote server from command line and then type chsh and change the login shell

This was also the life-saving solution to my problem. I was going crazy already with the error I was getting. Thank you!!!
