### ISSUE TITLE
How to make a choice in the menu vscode remote when connected?

### ISSUE THREAD

**Issue by drtvader** [microsoft/vscode-remote-release#5103]
I'm trying to connect to the server where it is necessary to make a choice in the menu, but this does not work.
http://joxi.ru/E2pxXO8tGzPM32
Here is a screen with the problem, how can I get around this?

**Comment by bamurtaugh** [comment]
Hi @drtvader, it looks like you experienced an error. Can you please paste your full SSH output logs?

Can you also include a bit more information, including the version VS Code and Remote - SSH you're using, and your local and remote OS?
