### ISSUE TITLE
Invalid mount path when trying to run a Windows devcontainer

### ISSUE THREAD

**Issue by alexkirsz** [microsoft/vscode-remote-release#5106]
- VSCode Version: 1.54.3
- Local OS Version: Windows 10 Pro 20H2 19042.985
- Remote OS Version:  Windows Server Core 20H2 19042.985
- Remote Extension/Connection Type: Docker
- Logs:

```
[5782 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount source=c:\workspace,target=C:\workspace,type=bind,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=c:\workspace -l vsch.quality=stable -l vsch.remote.devPort=0 --entrypoint /bin/sh vsc-workspace-2525c8d4d8025e776eae29a8440a45e2 -c echo Container started ; trap "exit 0" 15; while sleep 1 & wait $!; do :; done
docker: Error response from daemon: invalid mount config for type "volume": invalid mount path: '/vscode'.
See 'docker run --help'.
```

Steps to Reproduce:

1. Use a windows docker image (e.g. `mcr.microsoft.com/windows/servercore`)
2. Open the dev container. The generated `docker run` command will use an invalid mount point for the VSCode folder. I couldn't find a way to customize this mount point, like I had to do for the `workspaceMount` in order to replace `/workspace` with `C:\workspace`.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by alexkirsz** [comment]
Windows containers aren't supported https://github.com/microsoft/vscode-remote-release/issues/445

**Comment by bamurtaugh** [comment]
Hi @alexkirsz, as you mention, Windows containers aren't currently supported. I'm going to close this issue in favor of https://github.com/microsoft/vscode-remote-release/issues/445. If I've missed/misunderstood any part of your issue, please just let me know. Thank you!
