### ISSUE TITLE
Failed to parse remote port from server output

### ISSUE THREAD

**Issue by BenjaKemp** [microsoft/vscode-remote-release#5111]
VS Cde Version: 1.56.2 (Universal)
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.3.0

```
: 7254a40d78b3
Linux 4.4.0-1110-aws #121-Ubuntu SMP Fri Jun 12 04:21:59 UTC 2020
bash: line 1: _exitcode: command not found
bash: line 2: syntax error near unexpected token `elif'
bash: line 2: `	elif [[ $ALLOW_CLIENT_DOWNLOAD == "1" ]]; then'
-sh: 4: function: not found
7254a40d78b3: running
-sh: 69: [[: not found
-sh: 90: [[: not found
-sh: 155: Syntax error: "(" unexpected (expecting "then")
Transferred: sent 17056, received 3696 bytes, in 0.2 seconds
Bytes per second: sent 85114.9, received 18444.2

[09:05:27.044] Failed to parse remote port from server output
[09:05:27.044] Resolver error: Error: 
	at Function.Create (/Users/ben.kemp/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:64641)
	at Object.t.handleInstallOutput (/Users/ben.kemp/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:63284)
	at Object.e [as tryInstallWithLocalServer] (/Users/ben.kemp/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:386419)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/ben.kemp/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:294035
	at async Object.t.withShowDetailsEvent (/Users/ben.kemp/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:405329)
	at async /Users/ben.kemp/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:384890
	at async E (/Users/ben.kemp/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:381658)
	at async Object.t.resolveWithLocalServer (/Users/ben.kemp/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:384517)
	at async Object.t.resolve (/Users/ben.kemp/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:295505)
	at async /Users/ben.kemp/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:127:110530
[09:05:27.048] ------


```

trying to connect to  remote server using ssh. It recognises that the password is correct but won't allow me to connect. There are no resources that i've found anywhere that tackle the same issue. All ideas welcomed

**Comment by lopezj1** [comment]
Having same issue:
Version: 1.56.2 (user setup)
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.16299

**Comment by bamurtaugh** [comment]
Seems potentially related to/same error as https://github.com/microsoft/vscode-remote-release/issues/5099.

**Comment by coconetlero** [comment]
Same problem here. The problem appears when I upgrade VSC. 

This solution works for me:
Then a good solution that can work is: to connect to your server through terminal (vscode terminal, gnome-terminal, whatever)! Then go and remove /Home/<user>/.vscode-server

Try to connect after it! At the attempt the server will be re-installed completly all anew! And good chances it will works! (I did that and it worked! So whatever that was going wrong on the vscode-server! you start all over! And the state or whatever go a new and problem resolved!

However you loose things, config, meta data, ... (you start a new!) In my case it didn't matter!

One can explore the .vscode-server structure, and elements! And you can save some part that you bring up later! (I didn't check!) (may do later)! It's an option!

From:
https://stackoverflow.com/questions/64034813/vs-code-remote-ssh-connection-not-working

**Comment by unakaroshi** [comment]
> This solution works for me:
> Then a good solution that can work is: to connect to your server through terminal (vscode terminal, gnome-terminal, whatever)! Then go and remove /Home//.vscode-server

I've tried that already. Unfortunately it also does not work. Neither with VSCode or the VSCode-Insiders.

**Comment by SrishtiSrivastavaWork** [comment]
Faced the same issue.
Resolved it by changing the login shell on the remote server to /bin/bash. This change can be done easily using the chsh command in the remote server. By default, when an account is created in Ubuntu, the shell is set to /bin/sh, which cannot understand and run the advanced syntax of bash language (which your vscode is probably using).
