### ISSUE TITLE
Intelephense cannot index on remote for autocompletion

### ISSUE THREAD

**Issue by TechNyquist** [microsoft/vscode-remote-release#5112]
- VSCode Version: **1.56.2**
- Local OS Version: **Ubuntu 20.04.2 LTS**
- Remote OS Version: **Ubuntu 18.04.5 LTS**
- Remote Extension/Connection Type: **SSH**

Steps to Reproduce:
1. Install SSH-Remote & Intelephense
2. Open remote PHP workspace
3. Try hit F12 on some class to take advantage of "Go to definition" feature -> "No definition found for X"

Does this issue occur when you try this locally?: **No**
Does this issue occur when you try this locally and all extensions are disabled?: **No**

At first we tried [a ticket on Intelephense extension](https://github.com/bmewburn/vscode-intelephense/issues/1739), but it's not clear what piece of the pipe is actually responsible for this malfunction, as from Intelephense point of view it should work seamlessly, and it doesn't have any clue on what side it is actual working.
For this reason I'm opening this issue to further investigate on where could be the actual responsibility.

So far it seems that Intelephense extension can't index files. It is installed on remote machine though. It is sending a request for "textDocument/definition", and response is empty. Only after a "textDocument/didOpen" (on file open), file is actually indexed and completion works for that specific file.

```
[Trace - 3:10:36 PM] Sending request 'textDocument/definition - (175)'.
Params: {
    "textDocument": {
        "uri": "file:///var/www/vhosts/website.com/libs/helper.php"
    },
    "position": {
        "line": 6,
        "character": 51
    }
}


[Trace - 3:10:36 PM] Received response 'textDocument/definition - (175)' in 3ms.
Result: []
```

Any chance that this could be somehow related to SSH-Remote extension? I stay open to any hint, or more info, about this. 
Thanks.

**Comment by TechNyquist** [comment]
UPDATE: the problem occurs if paths in workspace settings pass through mounted directories.

In our case we have this mount:
`/data/vhosts                                    /var/www/vhosts                         none    defaults,bind   0 0`

If in settings we setup Intelephense path as `/var/www/vhosts/the_project` it doesn't work (as for the issue).
If we set `data/vhosts/the_project` it works as expected.

**Comment by roblourens** [comment]
Good clue. Does that mean that the extension is failing to open that file? I may have to send you back to the extension's repo then.

**Comment by TechNyquist** [comment]
No, rather it means that the extension asks for what file contains a symbol definition and VS API responds "None".

**Comment by roblourens** [comment]
Not a language server expert but isn't it VS Code sending a `textDocument/definition` to the extension and the extension replying none?

**Comment by TechNyquist** [comment]
Neither I. I'll forward this question to the extension author. That's quite critical to know what to blame.

**Comment by TechNyquist** [comment]
Forget what I wrote.
The real issue are not mounted directories but **symlinks**. This is a fact.
We have few of them in workspace and indexing just halts when "searching for files" hits them. Replacing them with regular folders just solves and everything works as expected.

Again, at this point I'm not sure what extension is responsible for this now. I'm still not enough prepared on the subject to blame reliably. I must rely on your analysis for this.

**Comment by roblourens** [comment]
Sorry, I don't really understand the issue, I need a more specific description. What sort of search? How are the symlinks involved?

**Comment by TechNyquist** [comment]
Before indexing Intelephense is performing a "scan for files" on every project in workspace. A pair of our projects have symlinks pointing to directories outside the project's tree. That scan hangs when hitting those symlinks.
I'd like to craft a minimal workspace that reproduces this for you, but I'm very busy right now. I'll provide that ASAP. Thanks.

**Comment by mijorus** [comment]
I just want to share the solution to a similar issue I used to have.
I my case, it was caused by `remote.extensionKind` being set to `ui` for intelephense
