### ISSUE TITLE
A better way to connect to remote containers in VS Code

### ISSUE THREAD

**Issue by altjx** [microsoft/vscode-remote-release#5114]
I'm trying to find a quicker way to access remote containers on SSH servers via VS Code. I am currently using Remote - SSH and Remote - Containers.

Here's what I have to do in order to successfully accomplish the goal (the long/hard way):

1. Connect to a remote SSH server via VS Code using the Remote SSH Plugin.
2. After connecting, I have to open a folder (this is a must, otherwise Remote - Containers doesn't work)
3. After opening a folder on the remote SSH server, I have to list the containers that are running
4. Next, I have to use the Remote - Containers plugin to Attach to Running Container
5. After attaching to the container, I have to open up the folder on the remote container.
6. I think the part that makes this so lengthy is steps 2, 3, and possibly 4.

As mentioned in step 2, I absolutely have to open a folder on the remote SSH server. If I don't do this, then I run into issues while trying to Attach to Running Container, as I believe there may be a bug in the plugin that assumes the container is local, even though I'm connected via SSH. Opening the folder seems to "do the trick" so to speak.

I'm not quite sure where the configuration of all of this is being stored so that VS Code knows what how to perform step 5, but if I could just figure that part out, I can write a script around this to automate the process so that I can just simply open up VS Code being already connected to the container that I've defined in a previous step.

Is there a way that I can make this process more simpler? This plugin has changed my life, but just looking for a way to make it easier and quicker if possible.

**Comment by chrmarti** [comment]
You could add the ssh connection to your local Docker's contexts and then use that context to connect to the remote containers. The Remote Explorer will show the remote containers without using Remote-SSH.

In your local shell:
```
docker context create myremote --default-stack-orchestrator=swarm --docker host=ssh://myuser@myremote
docker context use myremote
```

Docker remembers the active context. `docker context use default` sets it back to the local Docker daemon.

**Comment by chrmarti** [comment]
Hope that works. Closing as answered question.
