### ISSUE TITLE
Changes to user's groups on remote host does not propagate to vscode terminal after closing and reopening vscode

### ISSUE THREAD

**Issue by Zeebrow** [microsoft/vscode-remote-release#5115]
- VSCode Version: 1.56.2
- Local OS Version: 10.0.18363
- Remote OS Version: CentOS Linux release 8.3.2011  kernel 4.18.0-240.22.1.el8_3.x86_64
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

on remote host as mike:
1. sudo groupadd group1
2. sudo usermod -aG group1 mike
3. verify mike is in group1 by running `groups`

from vscode terminal:
4. configure ssh connection and start remote session as non-root user (mike)
5. from vscode teminal, verify mike is in group1 by running `groups`

on a new remote host session as mike:
6. sudo gpasswd -d mike group1
7. logout/login
8. verify mike is no longer in group1 by running `groups`

from vscode terminal:
9. close vscode
10. reopen vscode
11. click "Remote Explorer" plugin on left column, find remote host in target, and Connect to Host in New Window
12. run `group` and find that mike is still in group1

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A
I'm running code that only has meaning on Linux filesystems

**Comment by Zeebrow** [comment]
settings.json:
```
{
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter.notebook.ipynb",
            "filenamePattern": "*.ipynb"
        }
    ],
    "git.confirmSync": false,
    "git.autofetch": true,
    "remote.SSH.remotePlatform": {
        "192.168.1.xxx": "linux"
    },
    "remote.SSH.showLoginTerminal": true,
    "terminal.integrated.enablePersistentSessions": false,
    "remote.SSH.enableAgentForwarding": false,
    "terminal.integrated.automationShell.linux": ""
}
```

**Comment by bamurtaugh** [comment]
Have you tried "Kill VS Code Server on Host" and then reconnecting?
