### ISSUE TITLE
process "node" cpu 100%

### ISSUE THREAD

**Issue by aprilweet** [microsoft/vscode-remote-release#5117]
Issue Type: <b>Bug</b>

Sometimes it does not work...

Extension version: 0.65.4
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.18GB free)|
|Process Argv|--crash-reporter-id 19923a66-ba14-467d-bcd2-0b34ce6a2c53|
|Screen Reader|no|
|VM|57%|

|Item|Value|
|---|---|
|Remote|SSH: |
|OS|Linux x64 |
|CPUs|Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz (16 x 2494)|
|Memory (System)|62.67GB (5.63GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehovct:30309550
bridgeflightcf:30302070
vscod805cf:30301675

```

</details>

**Comment by aprilweet** [comment]
![image](https://user-images.githubusercontent.com/10728431/120159089-680b0d80-c227-11eb-8f28-42aa37d26518.png)

**Comment by bamurtaugh** [comment]
Which extension are you using? What do you mean by "Sometimes it does not work..." - what does not work, what exactly isn't functional, how often do you experience this behavior, etc? Can you share full logs?
