### ISSUE TITLE
The Remote WSL extension is recommended to install on OS X

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#5123]
Testing microsoft/vscode#125004

- On OS X run 'Install Additional Remote Extensions'
- Notice that the WSL extension is recommended
![image](https://user-images.githubusercontent.com/172399/120332129-b9ca9b00-c2ee-11eb-8f9a-2a31fd8215ed.png)

**Comment by aeschli** [comment]
The same with all other extension view queries. The queries can propose extensions that are not useful for your platform.

We would require a way to annotate for which platforms an extension is. Our queries would have to specify our platform(s).

Maybe we get that with the work on platform specific extensions on the Marketplace. For Remote-WSL we would then only publish a Windows variant.

**Comment by sandy081** [comment]
Current thinking with platform specific extensions is that we still show all extensions in the search view and show an error while installing the extension that it is not compatible with current platform - just like vs code engine compatibility.
