### ISSUE TITLE
Remote - Containers, Node error on arm64

### ISSUE THREAD

**Issue by rafrafek** [microsoft/vscode-remote-release#5124]
- VSCode Version: 1.56.2 arm64
- Local OS Version: Ubuntu Desktop 21.04 arm64
- Remote OS Version: Ubuntu Desktop 21.04 arm64 (it is docker on the same Raspberry Pi 4 8GB)
- Remote Extension/Connection Type: Docker
- Logs: [remoteContainers-2021-06-01T16-24-26.100Z.log](https://github.com/microsoft/vscode-remote-release/files/6578245/remoteContainers-2021-06-01T16-24-26.100Z.log)

Steps to Reproduce:

1. Try Node example of `Remote - Containers` https://github.com/microsoft/vscode-remote-try-node/issues/28
2. Error:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

**Comment by bamurtaugh** [comment]
Hi @rafrafek, it looks like this was answered in https://github.com/microsoft/vscode-remote-try-node/issues/28#issuecomment-852325379, so closing this issue. If you have any other questions, please just let us know. Thank you!

**Comment by chrmarti** [comment]
Tracked as https://github.com/microsoft/vscode-dev-containers/issues/558.
