### ISSUE TITLE
No modal when preferred local port is taken 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-remote-release#5125]
Testing #5118

> Try forwarding ports via auto port forwarding and by manually forwarding a port when the preferred local port is not available and verify that there is a modal dialog when you have requireLocalPort set for that port.

Perhaps I'm doing something wrong here, but I have `requireLocalPort` set for `7000`, I locally forwarded that port via `npx http-server -p 7000` in a local window, and then it allowed me to forward that port in the container.

![recording - 2021-06-01T110522 358](https://user-images.githubusercontent.com/29464607/120370289-419dae80-c2c9-11eb-961f-9c3842e0ea3e.gif)

**Comment by mjbvz** [comment]
@meganrogge Also try passing in an explicit `localhost` address when starting the server:

```
npx http-server -p 7000 -a localhost
```

I only got the modal after starting the server this way
