### ISSUE TITLE
Inspect volume pulls up prompt rather than going directly into restricted mode

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-remote-release#5126]
Testing #5121

In the testplan item, the inspect volume steps say that the inspected devvolume starts in restricted mode.
However, I get to the select trust screen instead.

I can still choose to go into restricted mode, and manually enable trust for certain subfolders, though.

**Comment by chrmarti** [comment]
The dialog comes after the window has reloaded into the remote workspace. That's actually expected. The test description is inaccurate. Fixed that only now. Thanks!
