### ISSUE TITLE
Open folder in container not loading restricted folder

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-remote-release#5127]
Testing #5121

I'm trying to use the "Remote-Containers: Open Folder in Container..." command on the Mac to open an untrusted/restricted folder. However, the folder doesn't load.
The command works perfectly fine with local folders that are already trusted.

**Comment by chrmarti** [comment]
@rzhao271 Does the window reload or just nothing happens? I can't reproduce with today's build.

**Comment by rzhao271** [comment]
Things seem to be working with the new update. A dialog popped up saying I had to trust the folder, I clicked cancel, and it opened locally in restricted mode.

**Comment by lszomoru** [comment]
Seeing the dialog is the expected behaviour. This has been fixed with https://github.com/microsoft/vscode/commit/272208523b5489a4bc92d6c0799a793daf4bac42

**Comment by rzhao271** [comment]
That's good, I'll close this issue.
