### ISSUE TITLE
remote SSH, not prompted for password ?

### ISSUE THREAD

**Issue by mckenzm** [microsoft/vscode-remote-release#513]
Using config file.
Using Port 8082.
Password authentication.
Known hosts updated OK - so making the trip.

 Not only taking forever to connect, but how should I be prompted for a password or view a banner ?

**Comment by Polygonalr** [comment]
Try adding `"remote.SSH.showLoginTerminal": true` in your settings.

**Comment by SimonOsipov** [comment]
@Polygonalr Thanks, that helped!

**Comment by Chuxel** [comment]
@mckenzm I am going to switch this to a feature request since ideally we should be showing the terminal in these situations rather than relying on you having to know to do this - I suspect you are not alone in this experience.  😊

**Comment by mckenzm** [comment]
This is good, there is a check box under the extension settings for SSH to always show, but it would be nice to have it on-demand since people may have a mix of password and identity file hosts.

**Comment by roblourens** [comment]
Yes we need to 

- Use @Tyriar's new background terminal API
- Run all ssh commands in a terminal
- Watch the terminal for recognized output such as a pw prompt
- Reveal the terminal (or show an input box)

**Comment by roblourens** [comment]
Now I will use background terminals for all ssh commands, look for the password prompt and show a quick input for the password, even without that setting set.
