### ISSUE TITLE
Reopen in Container - more details on why trust is needed 

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-remote-release#5130]
Testing #5121

We should provide more information about why workspace trust is needed to open a folder in a container:
![image](https://user-images.githubusercontent.com/3372902/120619315-257e4680-c45c-11eb-9c55-d8181cd73f83.png)

**Comment by chrmarti** [comment]
Proposal: "Opening a folder in a Dev Container may execute arbitrary code both inside and outside the container."

![image](https://user-images.githubusercontent.com/9205389/120664722-76f1fa00-c48b-11eb-9d7b-7cb62a450176.png)
