### ISSUE TITLE
Clone Repository in Container Volume fails in an untrusted workspace

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#5134]
- Open an empty window
- Run `Clone Repository in Container Volume`
![image](https://user-images.githubusercontent.com/172399/120671855-11edd280-c492-11eb-8649-873ea11bf91d.png)

This commands uses an API command exposed by the GitHub extension which fails in an untrusted workspace since the extension is not activated.

The extension already defines workspace trust to be limited:
```json
"capabilities": {
		"untrustedWorkspaces": {
			"supported": "limited",
			"description": "Opening a folder in a container requires workspace trust."
		},
		"virtualWorkspaces": true
	},
```

See also https://github.com/microsoft/vscode/issues/125395

**Comment by lszomoru** [comment]
Change the to the Git extension, not to support untrusted workspace has been reverted.

**Comment by chrmarti** [comment]
Verified this works with today's Insiders build. Labelling as `under-discussion` for June since we might need to update Remote-Containers depending on how this will be handled by the Git and GitHub extensions.

**Comment by lszomoru** [comment]
Thanks for the nudge @chrmarti. I would like to keep this one opened to make sure that this scenario is being validated as part of the work that I am doing to break out some of the functionality of the `vscode.git` extension into the `vscode.git-base` extensions. What's interesting is that the Remote Containers extension depends on a command provided by a separate extension but that dependency is not being called out in the `package.json`. is this expected? Could this be fixed?

**Comment by chrmarti** [comment]
The repository picker is not essential for Remote-Containers to work, we could add a runtime check instead.

**Comment by lszomoru** [comment]
@chrmarti, can we close this issue now that the repository picker has been moved to the `git-base` extension?

**Comment by chrmarti** [comment]
Yes, thanks @lszomoru.
