### ISSUE TITLE
The one-time trust dialog for cloning a repository into a container is scary

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#5136]
The first time you clone a repository into a container we show this scary dialog with a lot of text:
![image](https://user-images.githubusercontent.com/172399/120705197-ce0dc400-c4b7-11eb-89de-573107dc9cd4.png)

A button with the label 'OK, Don't Show Again' is something I've never seen. An improvement would be 'OK' and have a 'Learn More' button that is a link to some documentation which explains the issue. 

With a Learn More button the message in the dialog can be shortened to: 
'We recommend to only a clone a repository in a container volume, when you trust the authors of the repository'.

However, for SSH we do not show such a one time dialog that reminds the user to only connect to a trusted SSH box. There, this is only mentioned in the documentation.

**Comment by egamma** [comment]
Assigning to May for discussion.

**Comment by chrmarti** [comment]
Updating based on the discussion during standup:
- `I Understand` replaces `OK, Don't Show Again`.
- Additional `Learn More` button. (Using aka.ms to point to a temporary target until the updated documentation goes live. https://github.com/microsoft/vscode-docs/issues/4580)
- Using shorter sentences to reduce the amount of text.

![image](https://user-images.githubusercontent.com/9205389/120780369-55931b80-c528-11eb-84d1-1446d846cfe3.png)

Similarly for attaching to a container:

![image](https://user-images.githubusercontent.com/9205389/120780420-6774be80-c528-11eb-85d4-1b1b2d3eb6d4.png)

https://github.com/microsoft/vscode-remote-release/issues/5131 is tracking the addition of extension API to show a custom dialog with a 'Shield' icon to make all security dialogs look the same.

It was also suggested that QuickPick (which follows after this dialog to pick a repository) could add support for displaying a security message (with the text shortened further).

/cc @dbaeumer @jrieken @lszomoru @sbatten

**Comment by egamma** [comment]
@chrmarti one potential wording tweak, replace 'I Understand' with 'Got It' this is how one time educational messages are treated in GitHub.

**Comment by chrmarti** [comment]
'Got It' looks good to me. Updated screenshots:
![image](https://user-images.githubusercontent.com/9205389/120799449-0d332800-c53f-11eb-8b17-2621f0e15234.png)

![image](https://user-images.githubusercontent.com/9205389/120799594-3ce23000-c53f-11eb-9338-1bd822c4335d.png)

/cc @bamurtaugh

**Comment by bamurtaugh** [comment]
Updated the screenshots in our docs PR: https://github.com/microsoft/vscode-docs/pull/4585.
