### ISSUE TITLE
Empty remote window constantly reloads when resolver returns isTrusted: true

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#5139]
Seen when attaching to a container. It does not reload without `isTrusted: true` or when directly opening a folder in the container (without going through the empty window, that reloads immediately).

Version: 1.57.0-insider
Commit: 387e2f39ebbbf50d4b488f900b2a745972764015
Date: 2021-06-04T05:12:22.451Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

**Comment by alexdima** [comment]
@chrmarti What are the precise steps? (like for dummies please) I spent 30 minutes today trying to figure out the distinction between an empty window and an empty workspace.

**Comment by chrmarti** [comment]
With Docker and Remote-Containers using VS Code Insiders:
- Start a new container on the command line: `docker run -d alpine sleep infinity`.
- Run the command `Remote-Container: Attach to Running Container...`.
- Pick the newly created container.
- If it opens a folder: File > Close Folder.
- Observe: Window keeps reloading when the resolver finishes.

**Comment by alexdima** [comment]
I can reproduce. Kind of funny. I will update the title to reflect that this is infinite reloading, not just once.

**Comment by lszomoru** [comment]
Fixed with https://github.com/microsoft/vscode/commit/bcdfe884a3c1ffd4f795d19eb86657bb96050722
