### ISSUE TITLE
Workspace folder is created inside root folder of the container. 

### ISSUE THREAD

**Issue by jiornojiovanni** [microsoft/vscode-remote-release#5140]
- VSCode Version: 1.56.2
- Local OS Version: Fedora 34
- Name of Dev Container Definition with Issue: i tried the NodeJS and the Go devcontainers.

When I open a devcontainer my project files aren't usable, as they are inside a workspace folder under the root of the container. So I can't access them and I can't create files.

Steps to Reproduce:

1. Launch devcontainer.
2. Can't read, write or create files inside the workspace.
![immagine](https://user-images.githubusercontent.com/31773561/120808921-d44c8080-c549-11eb-98c7-5920d0794cca.png)

**Comment by Chuxel** [comment]
This is expected but the permissions should be correct on the `/workspace` folder and its sub contents.  The only reason I can think of that might cause this is if you are using rootless docker with a non-root user.  The problem here is that your user is mapped to root. So for the bind mount only root can access the files (it's an annoying problem).  Is that your situation?

//cc: @chrmarti

**Comment by jiornojiovanni** [comment]
I installed docker from the official repository and then added myself to the docker group (I followed the instructions given by the remote container extension).
I tried with both the default user and with root in devcontainers.json (It's the autogenerated one, I haven't touched it).

> Opening something in a container volume is not subject to the same problem. (The "clone repository in container volume" command.)

Tried it now and it fails.
![immagine](https://user-images.githubusercontent.com/31773561/120811960-d82dd200-c54c-11eb-8ee0-365de21de1cc.png)

**Comment by jiornojiovanni** [comment]
I edited my previous comment as I thought I was doing something wrong with the clone "repository in container" command, but yes it also doesn't work. It can't read the devcontainer.json inside it thanks to the insufficient permission.
![immagine](https://user-images.githubusercontent.com/31773561/120813332-14156700-c54e-11eb-8fde-a7771958ade9.png)

**Comment by chrmarti** [comment]
What do you get for `ls -la /workspaces`?

**Comment by jiornojiovanni** [comment]
```
$ ls -la /workspaces/
total 0
drwxr-xr-x. 1 root   root    18 Jun  4 15:23 .
drwxr-xr-x. 1 root   root   188 Jun  4 15:23 ..
drwxr-xr-x. 1 vscode vscode  74 Jun  4 13:56 palma-IRC
```
When inside the project folder:
![immagine](https://user-images.githubusercontent.com/31773561/120825657-e46c5c00-c559-11eb-806f-1e8c74e744ba.png)

**Comment by chrmarti** [comment]
You seem to be using SELinux (going by the dot in the permissions). We are tracking this as https://github.com/microsoft/vscode-remote-release/issues/1333.
