### ISSUE TITLE
Update devcontainer.json schema with "hostRequirements"

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#5144]
```json
"hostRequirements": {
  "cpus": 8,
  "memory": "16gb", // otherwise is bytes - allows for other units like mb, or k
  "storage": "32gb" // otherwise is bytes - allows for other units like tb, or mb, or k
}
```

**Comment by rzhao271** [comment]
@chrmarti I'm wondering how to verify this issue?
I added the following to my `devcontainer.json`, and rebuilt and reopened the workspace in a container, and the container opened as usual:

```json
"hostRequirements": {
	"cpus": 100,
	"memory": "2kb",
	"storage": "1mb
}
```

**Comment by chrmarti** [comment]
@rzhao271 I should have mentioned: This is only implemented in Codespaces right now.

To verify make sure you get proposals for the new properties, their format (number or number with unit) is validated and there are no errors/warnings when using valid values.

**Comment by rzhao271** [comment]
@chrmarti I adjusted the values in Codespaces Web and rebuilt the container.
The values pass validation, but I'm not sure whether Codespaces handled the values properly.

![examplecs](https://user-images.githubusercontent.com/7199958/121213229-e7ee3480-c832-11eb-8447-dcf13cbca8c2.PNG)

**Comment by chrmarti** [comment]
I'm not sure what the fallback is when the requirements can't be met. /fyi @jshorty see screenshot above.

**Comment by jshorty** [comment]
At the moment the only place where these get used is in surfacing the list of available machine types for a new/existing codespace— for example here's the UI in GH to create one for `github/github`:
![Screen Shot 2021-06-09 at 9 10 00 AM](https://user-images.githubusercontent.com/7283521/121380869-7978a780-c902-11eb-8193-2de03886cb41.png)
and related `hostRequirements`:
```
  "hostRequirements": {    // Require specs of the extremeLinux machine type for codespaces
    "storage": "64gb",
    "memory": "64gb"
  },
  ```
When creating from within VS Code it'll filter the list down to eligible choices but won't display these grayed-out ones.

There isn't really a fallback in either case, we'll just display warning messages— but in GH the modal context should help explain. In the VS Code case, I believe the extension would give the following error:
```
"There are currently no machine types available for which you have access. Please check the repository's devcontainer configuration or contact support."
```

**Comment by rzhao271** [comment]
@chrmarti I'll let you create a new issue for https://github.com/microsoft/vscode-remote-release/issues/5144#issuecomment-857790997 as you see fit.

Marking this issue as verified.

**Comment by jshorty** [comment]
If desired, we could update the GH API to give a more specific message in the case where the user would have access to one ore more machine types, but they're all excluded by devcontainer requirements.
