### ISSUE TITLE
Docker icon not showing up?

### ISSUE THREAD

**Issue by aronchick** [microsoft/vscode-remote-release#5146]
- VSCode Version:
Version: 1.56.2 (Universal)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z (3 wks ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin arm64 20.5.0

- Local OS Version: Big Sur
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Open VSCode with MS Docker extension installed 
2. Notice that docker icon is not there

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: (need extension)

I hate to file this, because there are a number of other issues out there that dance around it, but i've tried setting Docker host manually in the extension list, andi it's definitely installed, but I just can't get the icon to show up.

![image](https://user-images.githubusercontent.com/51317/120904739-93647280-c602-11eb-99d3-64e48d2aa8a9.png)

**Comment by bamurtaugh** [comment]
Based on the screenshot above, it looks like the Docker icon isn't showing up even when you aren't connected to Remote-SSH? 

If you right-click in the sidebar, do you have the Docker extension checked off to show up? 

![image](https://user-images.githubusercontent.com/25310137/121101104-0ced9380-c7b0-11eb-945c-fcf34d9b2146.png)

If both of the above are true, and the Docker extension is the only extension that isn't showing up (locally and remotely), it sounds like opening an issue in the Docker extension repo would make sense: https://github.com/microsoft/vscode-docker/issues.

**Comment by aronchick** [comment]
ugggghgh - I'm an idiot.

That said, I had no idea that was even an option (right clicking and hiding). I wonder if there's a way to indicate that hiding is an option.

Thanks - feel free to closer.

**Comment by bamurtaugh** [comment]
No worries at all, and glad it worked! If it makes you feel any better, I also just had my Docker extension icon hidden, and I realized I needed to unhide to help troubleshoot here :)

If we see more folks running into this, this is certainly a good one to keep in mind, so thank you for reporting! Closing for now.
