### ISSUE TITLE
Default Profile not set when using terminal.integrated.defaultProfile.*

### ISSUE THREAD

**Issue by taylorbartley** [microsoft/vscode-remote-release#5148]
### Environment
- VSCode Version: 1.56.2
  - 054a9295330880ed74ceaedda236253b4f39a335

- Local OS Version:
```
Windows 10 Home
21H1
Build: 19043.1023
``` 
- Remote OS Version: 
```
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
```
- Remote Extension/Connection Type: 
```
WSL 
Remote - Containers v0.177.2
Remote - WSL v0.56.4
```
- Logs: Unsure what I could provide. 

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: n/a

### Issue
Default Profile is not being set on container build. 

Terminal setting of `terminal.integrated.shell.*` has been deprecated, and now a combination of these two is recommended:
- `terminal.integrated.defaultProfile.*
- `terminal.integrated.profiles.*`

When I build/open a container, I have to chose "Select default profile", then select the profile I'd like as default. 

### Steps to Reproduce:

1. Add to `devcontainer.json` the following entries
```
"terminal.integrated.defaultProfile.linux": "bash",
"terminal.integrated.profiles.linux": {
    "bash": {
        "path": "/bin/bash",
        "args": ["--login"],
        "overrideName": true
    }
}
```
2. Build container.

The "bash" will be an option, but not default until  set. 

Integrated terminal documentation: https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration

I've noticed that if I set the profile name to something like "bash profile", and add another entry such as `"bash": null`, I can terminate the entry terminal, then start a new one, and the default `bash profile` will load properly. I'm not sure why I would need to set a custom name field, and remove an existing one, for this to work.

**Comment by bamurtaugh** [comment]
cc @meganrogge @Tyriar

**Comment by meganrogge** [comment]
This is a duplicate and is fixed in insiders. Will be fixed in the stable build we're releasing this week.
