### ISSUE TITLE
Cannot reconnect after disconnect

### ISSUE THREAD

**Issue by JeffersonQin** [microsoft/vscode-remote-release#5151]
- VSCode Version: 1.53.2
- Local OS Version: Windows 10 ARM 10.0.19042
- Remote OS Version: Windows 10 20H2 19042.985
- Remote Extension/Connection Type: SSH
- Device: Surface Pro X

Steps to Reproduce:

1. connect to remote
2. close the laptop for a few minutes
3. the remote tool will inform me to type in password again since it disconnected
4. cannot reconnect any more

![image](https://user-images.githubusercontent.com/30655701/120960994-8759eb80-c78f-11eb-9906-04c80364ffc5.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
Can you please share your full logs from the Remote SSH output channel? Also, do you experience this when you upgrade your version of VS Code? And what version of Remote-SSH are you using?
