### ISSUE TITLE
Show name of dev container in recently opened list

### ISSUE THREAD

**Issue by Stadly** [microsoft/vscode-remote-release#5152]
In the list of recently opened folders & workspaces, the different projects are identified from the folder name and, if existing, the workspace name from the `.code-workspace` file. This works well when developing locally or in WSL, or if all projects have a `.code-workspace` file (which AFAIK only multi-root workspaces need). When using a dev container, however, it is often difficult to tell the different projects apart. For instance, multiple dev containers may use the same folder structure, and are hence indistinguishable unless they have a  `.code-workspace` file. In my case, several different projects are called `html [Dev Container] /var/www` in my recent list.

I suggest to show the dev container name in the list, instead of just "Dev Container".

![image](https://user-images.githubusercontent.com/7263579/121000175-34ca0080-c78a-11eb-8dbd-4dd644c61093.png)

![image](https://user-images.githubusercontent.com/7263579/121000227-41e6ef80-c78a-11eb-907f-7ffb1040ff64.png)

**Comment by liunanhao** [comment]
@Stadly
after the remote-containers version ​v0.145.1,my container folder name  in recently opened list like this
![2cdda109d15325685a42ea94b0229ef](https://user-images.githubusercontent.com/41946722/123051001-e0827a00-d433-11eb-9950-7a31ad737d90.png)
how did you make the container folder like that.

**Comment by Stadly** [comment]
@liunanhao I first start vscode in WSL 2 before starting the dev containers. Can that make a difference? How is your setup?

**Comment by liunanhao** [comment]
> @liunanhao I first start vscode in WSL 2 before starting the dev containers. Can that make a difference? How is your setup?

I did not use wsl 2,i use docker with ssh to connect my remote container.

**Comment by Stadly** [comment]
Then that's the reason. I guess for you as well, it would be useful if the name of the development container was shown instead of just `[Dev Container]`. If so, please give an upvote to the first message so we can get this added to the backlog :)

**Comment by liunanhao** [comment]
of course
