### ISSUE TITLE
Allow usage of GitHub default environment variables in devcontainer.json

### ISSUE THREAD

**Issue by raballew** [microsoft/vscode-remote-release#5154]
As a user I want to build a devcontainer image per commit, to ensure that I can provide the exact same environment at a later stage even if dependencies changed in the meantime.

Therefore I would like to use the default GitHub actions environment variables [1] to do something similar to:

```
{
    "image": "docker.pkg.github.com/<user>/<repo>/devcontainer:${env:GITHUB_SHA}",
    "name": "devcontainer",
    ...
}
```

Think about a workflow where a GitHub action builds and publishes `docker.pkg.github.com/<user>/<repo>/devcontainer:${env:GITHUB_SHA}` for each commit and other users can use the exact same environment with Codespaces afterwards.

[1] https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables

**Comment by chrmarti** [comment]
We might want to use something not specific to GitHub, like `${commitId}`.

**Comment by raballew** [comment]
@chrmarti From my point of view I was explicitly referring to the GitHub env vars since this would enable the usecase I currently have. But if you would like to name it differently and it integrates in the workflow as described above, this looks good to me.
