### ISSUE TITLE
Using remote-containers command on remote-ssh connected to linux, vscode looks for Docker instance on the local machine instead of on the remote

### ISSUE THREAD

**Issue by weilannw** [microsoft/vscode-remote-release#5155]
Issue Type: <b>Bug</b>

1) On Redhat 8.3 with Docker 20+, create a docker container
2) connect to remote with the vscode ssh extension
3) ctrl+shift+p -> Attach to a running container
4) Get error prompt with button to install docker

Workaround:
Open a folder on the remote (`code 'dir-name'`), and in the new window the attach command succeeds as it now sees Docker on the remote.

Extension version: 0.177.2
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.18.0-240.22.1.el8_3.x86_64
Remote OS version: Linux x64 4.18.0-240.22.1.el8_3.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (20.09GB free)|
|Process Argv|--crash-reporter-id 38b0f955-eff4-492f-aaed-58b470c0a9c0|
|Screen Reader|no|
|VM|36%|

|Item|Value|
|---|---|
|Remote|SSH: 10.90.245.22|
|OS|Linux x64 4.18.0-240.22.1.el8_3.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz (8 x 2299)|
|Memory (System)|7.59GB (1.04GB free)|
|VM|57%|

|Item|Value|
|---|---|
|Remote|SSH: 10.90.245.22|
|OS|Linux x64 4.18.0-240.22.1.el8_3.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz (8 x 2299)|
|Memory (System)|7.59GB (1.04GB free)|
|VM|57%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
pythonvsuse255cf:30311221
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by chrmarti** [comment]
Tracked as https://github.com/microsoft/vscode-remote-release/issues/5155.
