### ISSUE TITLE
Cannot read property 'remote.containers.gitCredentialHelperConfigLocation' of undefined

### ISSUE THREAD

**Issue by cdorsal** [microsoft/vscode-remote-release#5159]
- VSCode Version: 1.56.2
- Local OS Version: Windows 10 1903
- Remote OS Version: RHEL 8.2
- Remote Extension/Connection Type: SSH/**Docker**/WSL
- Logs:   
    TypeError: Cannot read property 'remote.containers.gitCredentialHelperConfigLocation' of undefined
                at Jn (c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-containers-0.177.2\dist\extension\extension.js:143:6639)
                at processTicksAndRejections (internal/process/task_queues.js:93:5)
                at async cM (c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-containers-0.177.2\dist\extension\extension.js:243:1665)
                at async c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-containers-0.177.2\dist\extension\extension.js:273:1384

Steps to Reproduce:

1. Create docker container running RHEL 8.2
2. Start container
2. Command "Attach to Running Container"
3. Select running container
4. See error "An error occurred attaching to the container."

**Note:** This used to work, about a month ago, before updating VSCode.

Does this issue occur when you try this locally?: **Yes**/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/**No**

**Comment by chrmarti** [comment]
Could you check what is in `~/.vscode-server/data/Machine/settings.json` in the container?

**Comment by chrmarti** [comment]
Seeing that when the file is empty. I'll add a check. Workaround is to delete the empty file or add `{}` to it.

**Comment by cdorsal** [comment]
@chrmarti good catch! That was the issue. Confirmed removing the file and trying to attach addresses the issue. Adding a check would be a good idea, and/or a more verbose error message.
