### ISSUE TITLE
Can't install extensions for WSL2 (Ubuntu 20.04)

### ISSUE THREAD

**Issue by rollingstarky** [microsoft/vscode-remote-release#5162]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: **1.56.0**
- OS Version: **Windows_NT x64 10.0.18363**
- WSL Version: **Ubuntu 20.04.02**

Steps to Reproduce:

1. Open a new remote window in WSL
2. Try to install any extension using install in WSL

I was trying to install **cpptools** extension for my WSL Ubuntu system. When I click the "install in WSL: Ubuntu-20.04" button, the button's text turned into "installing" and nothing else happend. Then the fan of my laptop started to running heavily. After about half an hour, the progress stopped and it says "Can't reconnected. Please reload the window.". Whatever I chose "Reload" or "Cancel", nothing changed.

I have tried several times, including install manully from "cpptools-linux.vsix", or install other extensions. It just failed in similar situation. But I can install extensions for the Windows 10 host system.

<img width="492" alt="vscode error" src="https://user-images.githubusercontent.com/18411431/119776153-2a407900-bef7-11eb-9744-ed5aac291a3d.png">

[vscode log window.txt](https://github.com/microsoft/vscode/files/6551633/vscode.log.window.txt)

[vscode log remote server.txt](https://github.com/microsoft/vscode/files/6551634/vscode.log.remote.server.txt)

**Comment by alexdima** [comment]
@rollingstarky I have tried to reproduce, but I could not. I suspect that perhaps I have a fast internet connection or a fast desktop PC. I have added more logging to the reconnection logic to identify the cause of a reconnection. Could you please install our latest https://code.visualstudio.com/insiders/ and when the issue reproduces, can you please attach the window log (`F1 > Developer: Show Window Log`).

**Comment by rollingstarky** [comment]
@alexdima I just tried. With this insider version, I can install any extension successfully. There are no errors showed.
🤣🤣🤣

**Comment by rollingstarky** [comment]
@alexdima And I tried with the normal version too, this time it worked. I don't know what changed.
I mean I merely done nothing. It just recovered by itself. 🤣🤣🤣
Thanks for your response. And sorry for bother you all.

**Comment by rollingstarky** [comment]
@alexdima I think I found a possible reason, but I'm not sure. I used [pipes.sh](https://github.com/pipeseroni/pipes.sh) as my WSL's splash screen animation. That is to say, I added the shell script ``pipes.sh`` to my ``.zshrc`` configuration file.
With that option, VSCode can't start the WSL shell or install any extension either, it seemed stucked. 
recently I disibled that feature for some other reason, and suddenly the situation became normal. So I think maybe that is the reason. If you are interested, maybe you can test yourself. Anyway, thanks again.
