### ISSUE TITLE
get stuck on connection reset

### ISSUE THREAD

**Issue by yarix** [microsoft/vscode-remote-release#5167]
Issue Type: <b>Bug</b>

when the installation for the remote server is getting a "connection reset" the installation never ends, and the VS-Code is stuck.
 
![image](https://user-images.githubusercontent.com/6409857/121653892-d496cf80-caa5-11eb-8ae5-6b654043b92c.png)

Extension version: 0.65.6
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (13.81GB free)|
|Process Argv|--crash-reporter-id dae04fa2-0d49-4551-9c24-8ad32f2875a8|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Seems that you're having trouble downloading the server. Have you tried multiple times? Can you share the full log?

**Comment by yarix** [comment]
yes. i have tired many times. 

due to company policy and many VPNs on the way from home to vm on the lab, the connection get rest during the upload at various times. the bugs here are:
1. when the connection is rest, there is no indication on the UI for that and the VS Code is stuck with message `Setting up SSH Host vm.company.com: Copying VS Code Server to host with scp`. 
2. there is no retry / continuation of the process even after manual intervention (restart VS)

where / how do i get the full log?

**Comment by bamurtaugh** [comment]
You can execute **Remote-SSH: Show Log** from the Command Palette. We have more information [here](https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues) on logs and reporting issues.
