### ISSUE TITLE
Connect to ssh server on mac: unreachable or not Linux x86_64 (Darwin x86_64 )

### ISSUE THREAD

**Issue by ipstone** [microsoft/vscode-remote-release#517]
Hello, I have vscode insider/remote worked like a charm to linux server, but when I am trying to connect to mac ssh, I have the following error msg 

`Can't connect to mac_workstation: unreachable or not Linux x86_64 (Darwin x86_64 ) `

My mac workstation runs 10.12.6, with sshd version: OpenSSH_7.4p1, LibreSS.0

I have searched with the error msg, there are suggestions of using remote nightly, which I have tried, but giving the following error msg: 

```Can't connect to .... : unreachable or not Linux x86_64 (command-line: line 0: Bad configuration option: remotecommand )```

Ideas to fix this? Thank you in advance

**Comment by mjbvz** [comment]
Duplicate of #24
