### ISSUE TITLE
Container parameter for remote-containers.attachToRunningContainer command

### ISSUE THREAD

**Issue by smhc** [microsoft/vscode-remote-release#5171]
The remote-containers.attachToRunningContainer command currently prompts for a container to connect to. If a container is provided it would be preferable to use that container immediately. This will be useful for an extension I maintain.

e.g:

```js
vscode.commands.executeCommand('remote-containers.attachToRunningContainer', 'mycontainer')
```

The 'Docker' extension currently supports attaching to a container, but the menu item is added by the remote containers extension. i.e there is inversion of control.

Alternatively document how to use the 'remote-containers.attachToRunningContainerFromViewlet' command to attach vs code using a view item.

**Comment by chrmarti** [comment]
Updating it to take the container id as a string argument. (This will be in the next release for 1.58 Insiders and then later 1.58 stable.)

**Comment by smhc** [comment]
Fantastic thanks. Will this work with container name as well, or does it need to be the numeric id? (Or hopefully the two are interchangeable and this is a redundant question)..

**Comment by chrmarti** [comment]
Both will work! 👍

**Comment by chrmarti** [comment]
@smhc Did you get a chance to test this?

**Comment by smhc** [comment]
Hi, just tested it and it seems to work ok. 

It does still seem to have a bug where it can't find the container when recently switching contexts.
i.e I was performing a 'docker context create/use' just prior to running the attach command and it shows all the containers for the target context as expected, but if you select one you get an error that 'it no longer exists'.

The logs for the error scenario:

```
[614 ms] Remote-Containers 0.185.0 in VS Code 1.58.0-insider (cc528230987ce3ac61fc4f094ae247d5ff24db3c).
[613 ms] Start: Resolving Remote
[619 ms] Setting up container: /mycontainer
[626 ms] Start: Run: docker inspect --type container /mycontainer
[61170 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[62644 ms] 1.41
[62647 ms] Start: Run: docker ps -q
[64062 ms] Start: Run: docker inspect --type container b63a2ec761d0 2581808f617d
```

If I then try again with the context already established, it works ok and the logs are (note the Context: line)

```
[446 ms] Remote-Containers 0.185.0 in VS Code 1.58.0-insider (cc528230987ce3ac61fc4f094ae247d5ff24db3c).
[444 ms] Start: Resolving Remote
[450 ms] Setting up container: /mycontainer1
[451 ms] Context: mycontext
[455 ms] Start: Run: docker inspect --type container /mycontainer1
[1280 ms] Start: Check Docker is running
[1280 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[2075 ms] Server API version: 1.41
[2080 ms] Start: Inspecting container
[2082 ms] Start: Run: docker inspect --type container 2581808f617dc06d660643f1f04aac7e45978ffd8c19d91bf09d0d1a92fc49c9
```

I get this problem when both passing the container name and when not passing the container name.

Aside from that somewhat unrelated bug the attach to target container does work ok, when it works :)

**Comment by smhc** [comment]
Just wondering if the problem here is recognised as a bug, more information is required or whether there is a possible workaround? Or should I raise a new issue?

Basically when switching contexts externally using 'docker context use' the attach to container still uses the old context when connecting and thus results in an error about the container not being found. You will experience this bug even when using the 'Remote explorer' extension. 

Is there a way to purge and reload the cached docker context that 'attach to container' is using?

**Comment by chrmarti** [comment]
Updated to `bug`. Thanks.

**Comment by smhc** [comment]
FYI for now I am using what appears to be an internal API. This works much better as I do not need to switch contexts via docker, perhaps I don't even need this extension. It would be nice if this was officially exposed or documented:

```js
            const connDetails = JSON.stringify({
                containerName: container,
                settings: {
                    context: context
                }
            });
            const jsonConnDetails = `attached-container+${Buffer.from(connDetails, 'utf8').toString('hex')}`;
            vscode.commands.executeCommand('vscode.newWindow', {
                remoteAuthority: jsonConnDetails
            });
```

**Comment by chrmarti** [comment]
This should work now as we update the previously picked up context when that changes.
