### ISSUE TITLE
Docker container "Extensions cache, remote removals" loop

### ISSUE THREAD

**Issue by phillip-corning-edb** [microsoft/vscode-remote-release#5172]
Issue Type: <b>Bug</b>

Since the 1.57 update of vsode I'm unable to develop in Docker containers.

When I attach to the container it gets stuck in a loop continuously saying:
"Extensions cache, remote removals: None"

Extension version: 0.183.0
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.895Z)
OS version: Linux x64 5.8.0-55-generic
Restricted Mode: No
Remote OS version: Linux x64 5.8.0-55-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2838)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|31.00GB (16.66GB free)|
|Process Argv|--unity-launch --crash-reporter-id 62bf5d74-1f69-4320-85f7-b8ec7095cecf|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: Ubuntu|
|OS|Linux x64 5.8.0-55-generic|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2838)|
|Memory (System)|31.00GB (16.67GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
pythonvsuse255:30319631
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by giodamelio** [comment]
I am having the same issue since I updated to 1.57.0 . Trying to load a devcontainer setup that uses `docker-compose` and a couple of images.

**Comment by giodamelio** [comment]
I can confirm that downgrading manually to [1.56.2](https://code.visualstudio.com/updates/v1_56) allowed the remote container to work again.

**Comment by chrmarti** [comment]
Could you attach your `devcontainer.json` and any other files required to run the dev container (`Dockerfile`, `docker-compose.yml`) and the log from such a hang (`F1` > `Remote-Containers: Show Container Log`)?

**Comment by giodamelio** [comment]
From my side the container files are just the community Elixir + Postgres template

https://github.com/microsoft/vscode-dev-containers/tree/v0.166.1/containers/elixir-phoenix-postgres

**Comment by chrmarti** [comment]
Could you also attach the log from the hang (`F1` > `Remote-Containers: Show Container Log`)?

**Comment by gaozhidf** [comment]
Same problem!!!!!!!


![image](https://user-images.githubusercontent.com/5724898/122170255-f088df80-ceb0-11eb-8c24-94be2802ebab.png)
Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:22:31.215Z (6 days ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.3.0


And logs as below:
```
[1784 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "
[2089 ms] Extension host agent is already running.
[2089 ms] Start: Run in container: cat /root/.vscode-server/data/Machine/.devport 2>/dev/null || cat /root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/.devport 2>/dev/null
[2096 ms] 37509
[2096 ms] 
[2097 ms] Port forwarding for container port 37509 starts listening on local port.
[2098 ms] Port forwarding local port 37509 to container port 37509
[2495 ms] userEnvProbe PATHs:
Probe:     '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
Container: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
Merged:    '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
[11797 ms] Extensions cache, remote removals: None
[71803 ms] Extensions cache, remote removals: None
[131813 ms] Extensions cache, remote removals: None
[191884 ms] Extensions cache, remote removals: None
[251949 ms] Extensions cache, remote removals: None
[311978 ms] Extensions cache, remote removals: None
```

**Comment by hastarin** [comment]
I had a similar issue here with a container using docker-compose and launching via WSL2 Ubuntu. 

By reverting the Remote Containers extension to 0.178.0 I was able to get the container building again.

0.179.0 or higher and it has the same issue described.

The problem is made obvious by the UI not showing the file browser and the various extra Tasks not showing under that dropdown.

I tried a few different versions of the waitFor argument as per https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_57.md in case it was related to that change but had no luck with that.

**Comment by chrmarti** [comment]
Does adding `"userEnvProbe": "none"` to the devcontainer.json work around the problem?

If so, could you enable tracing for Remote-Containers in the settings and append the log (`F1` > `Remote-Containers: Show Container Log`) from a startup that hangs?

![image](https://user-images.githubusercontent.com/9205389/122556709-1e4e5f80-d03c-11eb-9f9c-0041ba9c19f0.png)

**Comment by hastarin** [comment]
@chrmarti Yes that does work around the problem.  Isn't none meant to be the default? https://code.visualstudio.com/docs/remote/devcontainerjson-reference

[remote_container_hang_existing_container.txt](https://github.com/microsoft/vscode-remote-release/files/6683364/remote_container_hang_existing_container.txt)

**Comment by chrmarti** [comment]
@hastarin We need to update the documentation, thanks.

Could you attach your `~/.profile`, `~/.bash_profile` and `~/.bashrc`?

**Comment by hastarin** [comment]
[profile.txt](https://github.com/microsoft/vscode-remote-release/files/6690101/profile.txt)
[bashrc.txt](https://github.com/microsoft/vscode-remote-release/files/6690102/bashrc.txt)

@chrmarti These are from my WSL2 Ubuntu. Are those the ones you need?

**Comment by chrmarti** [comment]
@hastarin I would need the ones from the container. It looks like `/bin/bash -lic ...` inside the container does not complete.

**Comment by chrmarti** [comment]
Related: https://github.com/microsoft/vscode/issues/126996#issuecomment-866972961 (The user had a `exec zsh` in `~/.profile`.)

**Comment by hastarin** [comment]
[bashrc.txt](https://github.com/microsoft/vscode-remote-release/files/6707339/bashrc.txt)
[profile.txt](https://github.com/microsoft/vscode-remote-release/files/6707342/profile.txt)

@chrmarti here are things from the container. I guess the eval of keychain may cause an issue for a non interactive shell if it's prompting for a password.

BTW Am I loosing anything by using the suggested workaround?

**Comment by chrmarti** [comment]
You could wrap the keychain part in:
```sh
if [ -t 1 ]; then
  # keychain part
fi
```
to only run it when there is a tty attached.

The workaround won't run these scripts when extracting environment variables, so the updates to PATH in the .bashrc won't be available in VS Code's tasks and launch configs. Maybe that's not needed in your case.

**Comment by chrmarti** [comment]
Continued in #5196.
