### ISSUE TITLE
through SSH connection, click on big file makes down the connection

### ISSUE THREAD

**Issue by moisesbites** [microsoft/vscode-remote-release#5173]
When you click on a file name in Explorer, VS Code tries to open in the editor. Ok. But, when you are through SSH connection, big file turn down the connection. So. would be good, if the MS Code check before open the size, and if it is a big size file, it ask by confirmation before to try to download to open file.

**Comment by roblourens** [comment]
Sorry, I don't think it's really practical for us to do
