### ISSUE TITLE
Integrated terminal - session not working correctly

### ISSUE THREAD

**Issue by houseofdouglas** [microsoft/vscode-remote-release#5176]
Issue Type: <b>Bug</b>

I just upgraded to the lastest VS Code this morning and now when I connect to a remote host and  attempt to run "docker ps" I get "Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json": dial unix /var/run/docker.sock: connect: permission denied".

I am not sure if it is part of the new Workspace Trust changes, but this is a bummer. If I ssh in terminal or the integrated terminal within VSCode it works just fine, but running that command from within a Remote SSH Target it won't work.

Extension version: 0.65.7
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No
Remote OS version: Linux x64 4.14.232-176.381.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (29.96GB free)|
|Process Argv|--crash-reporter-id 2e36171b-63ac-42b6-830c-165a9be1a07e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.51.50.121|
|OS|Linux x64 4.14.232-176.381.amzn2.x86_64|
|CPUs|AMD EPYC 7571 (16 x 2539)|
|Memory (System)|61.80GB (57.56GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
pythonvsuse255cf:30319632
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by chrmarti** [comment]
Is the user you are logged in with part of the `docker` group (check the output of running `groups`)? (See https://docs.docker.com/engine/install/linux-postinstall/.)

**Comment by houseofdouglas** [comment]
ec2-user adm wheel systemd-journal docker

But I wonder if the local VS Code client and the remote ssh server were out of sync... I just got back from vacation, booted up the remote server and now everything is working as expected. No issues (which feels like a relief.)

**Comment by chrmarti** [comment]
Closing as resolved then, thanks.
