### ISSUE TITLE
add support for crul instead of wget on remote server download

### ISSUE THREAD

**Issue by yarix** [microsoft/vscode-remote-release#5179]
Using the ssh remote extension, and selecting `remote.SSH.localServerDownload=off` the remote server is using wget command. in some cases the wget command needs to get tweeks like the one suggested in #4444, and there are cases where it's not enough. for example when there are enterprise proxy and firewalls which terminate and replace SSL certificates. in such cases even wget with `--no-check-certificate` does not work.

```
[root@vm-rhel01 b4c1bd0a9b03c749ea011b06c6d2676c8091a70c]#  wget --no-check-certificate -nv -O vscode-server-linux-x64.tar.gz https://update.code.visualstudio.com/commit:b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/server-linux-x64/stable
WARNING: cannot verify update.code.visualstudio.com's certificate, issued by ‘/emailAddress=CyberSecurity_Network_Ops@MyCompany.com/C=US/O=MyCompany Technology Incorprated/OU=CyberSecurity/CN=MyCompany SSL Decyption Authority’:
  Self-signed certificate encountered.
WARNING: cannot verify az764295.vo.msecnd.net's certificate, issued by ‘/emailAddress=CyberSecurity_Network_Ops@MyCompany.com/C=US/O=MyCompany Technology Incorprated/OU=CyberSecurity/CN=MyCompany SSL Decyption Authority’:
  Self-signed certificate encountered.
2021-06-13 10:11:45 URL:https://az764295.vo.msecnd.net/stable/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/vscode-server-linux-x64.tar.gz [45622348/45622348] -> "vscode-server-linux-x64.tar.gz" [1]
[root@vm-rhel01 b4c1bd0a9b03c749ea011b06c6d2676c8091a70c]#
```

On the other hand, if curl is used, the file can be downloaded:
```
curl -L -k --proxy http://myCompany:83 --output vscode-server-linux-x64.tar.gz https://update.code.visualstudio.com/commit:b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/server-linux-x64/stable
```
another benefit of curl is that the proxy can be set on the specific request instead of configuring the proxy globally.

**Comment by yarix** [comment]
BTW: as last resort for manual installation:
1. download the file on the remote server (using the wget/curl/sftp... any method that works manually)
2. extract the zip file to `~/.vscode-server/bin/COMMIT_ID/` with: `tar -xvzf vscode-server-linux-x64.tar.gz --strip-components 1`
3. restart vscode and re-connect to ssh server (with ssh remote extension).

**Comment by krishnakumar4a4** [comment]
I have an extensive process that works after fiddling out a lot. This solves the problem when you are unable to have good internet on remote machine. Hopefully this will help someone.

# Problem:

Sometimes remote ssh plugin automatically updates itself and on the target remote machine when you attempt to connect. 

```bash
# This is the connection log in your vscode output terminal
[12:45:15.058] > Acquiring lock on /home/username/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/vscode-remote-lock.username.2d23c42a936db1c7b3b06f918cde29561cc47cd6
[12:45:15.065] > Installing to /home/username/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6...
[12:45:15.069] > 9eb15858dab8%%1%%
[12:45:15.073] > Downloading with wget

# On the remote machine, if you run "ps -efl|grep code"
0 S username 15796 15795  0  80   0 - 37987 sk_wai 12:45 ?        00:00:00 wget --tries=1 --connect-timeout=7 --dns-timeout=7 -nv -O vscode-server.tar.gz https://update.code.visualstudio.com/commit:2d23c42a936db1c7b3b06f918cde29561cc47cd6/server-linux-x64/stable
```

On my target machine, internet is pathetic. wget command always fails with following error log in vscode output terminal

```bash
> Waiting for /home/username/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/vscode-scp-done.flag and vscode-server.tar.gz to exist
> Found flag and server on host
[12:49:57.683] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/home/username/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6"}
[12:49:57.683] Downloading VS Code server locally...
```

# Solution:

1. Download the vscode-server.tar.gz from machine with good internet
2. scp the binary to remote machine
3. Retry connecting from vscode to remote machine and when you see this `Downloading with wget` in output terminal
4. SSH to remote machine
5. On remote machine
    1. Run `ps -efl|grep code` and copy the `commit id` and keep note of `process id` of wget process
    2. Run `cp vscode-server.tar.gz /home/username/.vscode-server/bin/<commit-id-from-previous-step>/`
    3. Also run `touch /home/username/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/vscode-scp-done.flag`
    4. Run `kill <process id>`
    5. Note: all these above steps on remote machine should run before wget command fails with timeout on vscode output window.
6. If you switch back to you vscode output terminal, you should see a log like this which is fine

    ```bash
    [12:45:15.073] > Downloading with wget
    [12:49:57.678] > wget download failed
    ```

7. Now vscode will skip download process and verify if download is successful looking at `vscode-scp-done.flag` file and `vscode-server.tar.gz` in `/home/username/.vscode-server/bin/<commit-id-from-previous-step>/` folder
8. After few seconds SSH connection will continue to work given you dont have any other SSH issues

After looking at lot of references. I have a feeling I kind of mimicked the process mentioned [here](https://github.com/microsoft/vscode-remote-release/issues/1034) rather manually.
