### ISSUE TITLE
Terminal Bug (forkpty(3))

### ISSUE THREAD

**Issue by Eliarama** [microsoft/vscode-remote-release#5180]
Issue Type: <b>Bug</b>

hello , 

I cant remote debug & execute. the terminal fail to open. 

vscode show the following error : 
The terminal process failed to launch: A native exception occurred during launch (forkpty(3) failed.).

Remote host : Centos 7 
localhost : win 10 

To reproduce the error , i start debug on remote host , or open a new terminal with the vscode panel. 

Regards , 
Eli Arama 

Extension version: 0.65.7
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.9.87-xxxx-std-ipv6-64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.22GB free)|
|Process Argv|--crash-reporter-id 50f88164-a456-432b-9274-0a0e68e7a14a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: XXX
|OS|Linux x64 4.9.87-xxxx-std-ipv6-64|
|CPUs|Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz (8 x 899)|
|Memory (System)|31.13GB (4.68GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
pythonvsuse255cf:30319632
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by bamurtaugh** [comment]
Thanks for reporting, can you please include the full logs? More info [here](https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues).
