### ISSUE TITLE
Installing Go Extension on Vs Code - WSL2 Ubuntu-18.04

### ISSUE THREAD

**Issue by j0nimost** [microsoft/vscode-remote-release#5182]
Issue Type: <b>Performance Issue</b>

* Set up a WSL2 Ubuntu-18.04 version 2
* Install Go
* Install and Start Vscode
* Try installing Go Extension

#### Expected Behavior:
The package installs in a few minutes

#### Actual Behavior: 
Package never completes installation resulting in degraded vscode perfomance

Extension version: 0.56.5
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (2.47GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/home/j0nimost/projects/src/github.com/j0nimost/newsc --remote=wsl+Ubuntu-18.04 --crash-reporter-id e66d0dc6-ad49-4136-9193-548d5636d2ee|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1991)|
|Memory (System)|12.36GB (10.58GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    97	 10656	code main
    0	    85	  4124	   shared-process
    0	    60	  3916	     ptyHost
    3	   487	 17944	   gpu-process
    0	    53	 19220	   utility
    0	    26	 22404	   crashpad-handler
   13	   211	 25544	   window (Extension: Go - newsc [WSL: Ubuntu-18.04] - Visual Studio Code)
    0	    78	 20484	     extensionHost
    0	    60	 22060	       electron_node wslDaemon.js 
    0	     7	  6172	         C:\WINDOWS\System32\wsl.exe -d Ubuntu-18.04 sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" b4c1bd0a9b03c749ea011b06c6d2676c8091a70c stable .vscode-server 0  '
    0	    11	 11788	           console-window-host (Windows internal process)
    0	     6	 23340	           C:\WINDOWS\system32\lxss\wslhost.exe {55a18898-2c00-4d8d-b95e-cf6534c1000a} 536 564 568 {da4d0cc7-1885-4121-8ab2-40bf1502b17e}
    0	    14	  5852	             console-window-host (Windows internal process)
    2	   100	 26008	   window (undefined)
    0	    82	 26080	   window (Issue Reporter)
    0	     4	 26864	   

Remote: WSL: Ubuntu-18.04
CPU %	Mem MB	   PID	Process
    0	     0	  8160	remote agent
    0	     0	  8171	   ptyHost
    0	     0	  8191	   watcherService
    0	     0	  8224	   extensionHost
    0	     0	  8237	     /home/j0nimost/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/node /home/j0nimost/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=8224
    0	     0	  8512	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  8513	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: WSL: Ubuntu-18.04|    Folder (newsc): 12 files|      File types: go(6) md(1) mod(1) sum(1)
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
pythonvsuse255:30319631
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by bamurtaugh** [comment]
Thanks for reporting, do you encounter this behavior (i.e. unable to install extensions) with any other extensions, or just Go? Would you be able to share logs as well (more info [here](https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues))?

**Comment by j0nimost** [comment]
Just Go, I restarted wsl and the installation was completed.
