### ISSUE TITLE
building remote-container fails

### ISSUE THREAD

**Issue by vascoosx** [microsoft/vscode-remote-release#5184]
Issue Type: <b>Bug</b>

This happens when building

```
[13521 ms] [01:37:48] Extension host agent started.
[14047 ms] Port forwarding connection from 54876 > 40721 > 40721 in the container.
[14047 ms] Start: Run in container: /root/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/node -e 
[14050 ms] [01:37:48] [::ffff:127.0.0.1][f8675099][ManagementConnection] New connection established.
[14777 ms] [01:37:49] [::ffff:127.0.0.1][460fa89a][ExtensionHostConnection] New connection established.
[14785 ms] [01:37:49] [::ffff:127.0.0.1][460fa89a][ExtensionHostConnection] <204> Launched Extension Host Process.
[18278 ms] Remote-Containers server: Remote to local stream terminated with error: {
  message: 'connect ENOENT \\\\.\\pipe\\openssh-ssh-agent',
  name: 'Error',
  stack: 'Error: connect ENOENT \\\\.\\pipe\\openssh-ssh-agent\n' +
    '    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)'
}
[22846 ms] Extensions cache, remote removals: None
```

Extension version: 0.177.2
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.10.25-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.33GB free)|
|Process Argv|--crash-reporter-id 2c92c7ef-10f5-46e4-81e2-60f5aba54509|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Dr|
|OS|Linux x64 5.10.25-linuxkit|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (2 x 2712)|
|Memory (System)|2.92GB (0.89GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by chrmarti** [comment]
Make sure the ssh-agent is running. See the Windows section under https://code.visualstudio.com/docs/remote/containers#_using-ssh-keys. Does that make it work?

**Comment by vascoosx** [comment]
Thank you very much it worked after I executed these 3:

```powershell
Set-Service ssh-agent -StartupType Automatic
Start-Service ssh-agent
Get-Service ssh-agent
```
