### ISSUE TITLE
Recovery container fails in arm devices

### ISSUE THREAD

**Issue by KenxinKun** [microsoft/vscode-remote-release#5187]
- VSCode Version: 1.56.2
- Local OS Version: macOS Big Sur 11.4
- Name of Dev Container Definition with Issue: recovery container

Steps to Reproduce:

1. Trying to clone a repo into dev container with any failure, triggering the "open in recovery container"
2. Whilst VS code tries to open the repo in the recovery container, it fails to build said container because the "alpine" image does not support ARM architecture

Proposed solution: make recovery containers based on an image that is fully supported across all architectures.

**Comment by Chuxel** [comment]
//cc: @chrmarti

**Comment by KenxinKun** [comment]
Thought I'd upload a screenshot of the error. Do note that alpine as a base image does seem to work with a simpler `docker run -it alpine` on the same machine so I'm not entirely sure why this error is referencing the architecture as incompatible...
<img width="271" alt="Screenshot 2021-06-14 at 20 34 48" src="https://user-images.githubusercontent.com/16479107/121949176-13e84900-cd50-11eb-9055-fa45fc37d210.png">

**Comment by chrmarti** [comment]
Related: https://github.com/microsoft/vscode-remote-release/issues/4462

**Comment by chrmarti** [comment]
Fixed with the adoption of the new server build for Alpine on arm64. Available with Remote-Containers 0.195.0 (currently requires VS Code Insiders).
