### ISSUE TITLE
Remote extension stuck at "Activating Extensions..." when any option selected

### ISSUE THREAD

**Issue by rosstex** [microsoft/vscode-remote-release#5192]
- VSCode Version: 1.57.0
- Local OS Version: Darwin x64 20.6.0. MacOS 11.5 Beta (20G5033c)
- Remote OS Version: N/A
- Remote Extension/Connection Type: SSH
- Logs: N/A

Steps to Reproduce:

1. Open the Remote menu from the bottom-left
2. Click any action
3. VSCode displays "Activating Extensions..." for a few seconds, then disappears and nothing happens

This includes all options (connect, show SSH config, etc.). I have tried uninstalling/deleting the extension, and erasing my VSCode install + all supporting files, no luck.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by rosstex** [comment]
I've tried to collect any logs in it, but I can't find remote extension logs in Output or the Dev Tools.

**Comment by rosstex** [comment]
I was able to solve this by switching to the Insiders branch of VSCode, with either the stable or insiders branch of the Remote - SSH extension.

**Comment by bamurtaugh** [comment]
Thanks for the updates @rosstex! It sounds like the latest changes in VS Code Insiders were sufficient to address this one, so I'll close out this issue. If you're still experiencing any trouble, please just let us know, and I'm happy to reopen/discuss further.
