### ISSUE TITLE
Stuck in "Opening Remote"

### ISSUE THREAD

**Issue by max06** [microsoft/vscode-remote-release#5196]
- VSCode Version: 1.57.0
- Local OS Version: Win10 21H1
- Remote OS Version: Win10 21H1 
- Remote Extension/Connection Type: SSH+Docker
- Logs:
```
[8764 ms] 
[8764 ms] Extensions cache, link in container: None
[8765 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "
[9082 ms] Extension host agent is already running.
[9082 ms] Start: Run in container: cat /root/.vscode-server/data/Machine/.devport 2>/dev/null || cat /root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/.devport 2>/dev/null
[9143 ms] 36929
[9143 ms] 
[9143 ms] Port forwarding for container port 36929 starts listening on local port.
[9144 ms] Port forwarding local port 36929 to container port 36929
[9238 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.onCreateCommandMarker' ; } 2> /dev/null
[9301 ms] 
[9301 ms] 
[9301 ms] Exit code 2
[9302 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.updateContentCommandMarker' ; } 2> /dev/null
[9364 ms] 
[9364 ms] 
[9365 ms] Exit code 2
[9365 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.postCreateCommandMarker' ; } 2> /dev/null
[9426 ms] 
[9426 ms] 
[9426 ms] Exit code 2
```

Steps to Reproduce:

Unclear. I'm running a remote container, remote machine hibernates. I wake it up the next morning, and reload my vscode window on my local machine forcing it to reconnect. And now it's stuck at the above log position. It also happened yesterday morning, I was able to fix it by opening the container with vscode on the remote machine and rebuilding it - but that's definitely something I'd like to avoid. Issues started with the last upgrade to 1.57.0.

**Comment by max06** [comment]
I can confirm vscode 1.56.2 indeed works.

**Comment by Anaxamandor** [comment]
I was able to connect to running docker containers using VSCode last week, but today it gets hung up "installing server" message.  I'm not aware of any changes I've made to my setup, but Windows 10 did get an update in between these times.  Things I tried:  rolling back this extension version, rebooting, recreating the container, turning off my NordVPN, changing the VPN to Canada, turning off hyper-v, rebooting, turning in on an rebooting.  No results on any of the above.

**Comment by chrmarti** [comment]
Does VS Code 1.57 work with Remote-Containers 0.177.2? You can install older versions from the Extensions viewlet's gear icon of Remote-Containers:
![image](https://user-images.githubusercontent.com/9205389/122585075-5dd87400-d05b-11eb-8109-8908d7952305.png)

**Comment by max06** [comment]
@chrmarti Not tested yet due to being dependend on the functioning version 1.56.2.

But I've tested older versions (past 3, 2 months old) and they also refused to work. So I think the new vscode release is the culprit...

**Comment by chrmarti** [comment]
Only VS Code 1.57 is using Remote-Containers 0.183.0, so it's not clear if the new VS Code or the new Remote-Containers is the culprit.

Could anyone seeing this check if VS Code 1.57 works with Remote-Containers 0.177.2? (You can install older versions from the Extensions viewlet's gear icon of Remote-Containers, see screenshot above.)

**Comment by max06** [comment]
@chrmarti Whoops, I didn't knew about that! 

Gonna try later on and report back here, once I've got a second machine up and running.

**Comment by phuebner** [comment]
@chrmarti I am experiencing the same issue. I was running VS Code 1.57 and Remote-Containers 0.183. 

When I roll back to Remote-Containers 0.177.2 I can connect to the container as expected. Version 0.178.0 is also still working. Functionality is broken starting with version 0.179.0

**Comment by chrmarti** [comment]
Does adding `"userEnvProbe": "none"` to the devcontainer.json work around the problem?

We changed the default to `"userEnvProbe": "loginInteractiveShell"`. That would cause a hang if `~/.profile`, `~/.bash_profile` or `~/.bashrc` (or any of their equivalents for other shells) do not finish. Someone mentioned doing `exec zsh` in `~/.bashrc` (https://github.com/microsoft/vscode/issues/126996#issuecomment-866972961), someone mentioned running a command that waits for user input (https://github.com/microsoft/vscode-remote-release/issues/5172#issuecomment-867423431).

These cases could be worked around by wrapping the command that does not finish in the shell startup script in something like:
```sh
if [ -t 1 ]; then
  # command that does not finish
fi
```

**Comment by max06** [comment]
That's actually what I'm doing, with `fish` instead of zsh. I know there's an option in vscode to launch another shell, but it needs to be set for every new container again. Gonna try your suggestion with the latest vscode and extension versions 👍🏼

**Comment by max06** [comment]
Sorry for the delay!

I'm now running 1.57.1 with Extension version 0.183.0 - after adding your suggestion to my dotfiles. And so far (tm) it seems to work. Goona update vscode now on my daily driver, using the same container.

**Comment by chrmarti** [comment]
Updating to log the process tree of the probe after 2 seconds and continuing without after 10 seconds.

**Comment by rzhao271** [comment]
@chrmarti I'm wondering how to verify this issue?

**Comment by max06** [comment]
(Please ignore me, if I'm wrong here)

```bash
$ docker run -ti --name issue-5196 mcr.microsoft.com/vscode/devcontainers/python:0-3 bash
---
root ➜ / $ apt-get update
root ➜ / $ apt-get install -y fish
root ➜ / $ echo "fish" >> ~/.bashrc
```
-> Attach vscode ... and it's broken.

Edit the `~/.bashrc` and replace the last line with
```
if [ -t 1 ]; then
  fish
fi
```
-> Reload the hanging vscode window ... fixed.

**Comment by chrmarti** [comment]
Thanks @max06. That includes the fix on your side, to verify only the fix in the extension:

Use the above steps, but do not change the `~/.bashrc` to use an `if`. Let it start `fish` unconditionally. While attaching VS Code, open the log (link in the progress notification) and verify that it logs the process tree after 2 seconds of waiting for the probe, that should show `fish` as a child process, and it continues startup without waiting for the probe after 10 seconds of waiting.

**Comment by max06** [comment]
You're welcome. 
Possible comm issue due to autism: Do you want me to verify the fix? If yes, the latest available version for me is 0.183. I'd need a hint on how to proceed. 

Imho, relying on a timeout is usually not my preferred solution. Since I have no clue what `userEnvProbe` is actually doing, I'm not sure if that's enough here or if a hint like "Can't probe the user env. Make sure to not run never ending processes." would be a better way to go. (Just my 2 cents.)

**Comment by chrmarti** [comment]
@max06 If you're available for verifying, you could install VS Code Insiders which gets the latest version of Remote-Containers including the fix. The timeout is really just a way to avoid being stuck. I'm updating the log message to include a sentence about waiting for user input (not released yet): "userEnvProbe taking longer than 10 seconds. Avoid waiting for user input in you shell's startup scripts. Continuing."

**Comment by max06** [comment]
@chrmarti Absolutely going to do this 👍🏼 
Happy about the future message 🥳

**Comment by max06** [comment]
There you go:

```
[6427 ms] userEnvProbe: loginInteractiveShell (default)
[6428 ms] userEnvProbe shell: /bin/bash
...
[8963 ms] userEnvProbe taking longer than 2 seconds. Process not found.
[16763 ms] userEnvProbe taking longer than 10 seconds. Continuing.
[16763 ms] Start: Run in container: /bin/sh -c # Watch installed extensions
[16764 ms] Start: Run in container: /bin/sh -c # Watch machine settings
```

(I just noticed that `Attach to Container` and `Attach in New Window` are both opening a new window.)

**Comment by chrmarti** [comment]
Thanks @max06!

(The names are not very clear, `Attach in New Window` always opens a window with no folder open, `Attach to Container` opens the last open folder in the container.)

**Comment by GLStephen** [comment]
I can say that using the VS Code Insiders build did nothing for this issue for me. But downgrading to 1.56.2 fixed it.

**Comment by chrmarti** [comment]
@GLStephen If there are any remaining issues, could you open a issue to track these? Thanks.
