### ISSUE TITLE
Can't open file in editor.

### ISSUE THREAD

**Issue by EdwardAndrew** [microsoft/vscode-remote-release#5197]
Issue Type: <b>Bug</b>

Open directory from WSL with `code .`
File tree will load, but clicking on a file does not load it in the editor.

Extension version: 0.56.5
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (20.15GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/home/ed/DAZN/acc-experiments --remote=wsl+Ubuntu-18.04 --crash-reporter-id 3e3cc00c-82aa-489a-986e-276ab93c5abc|
|Screen Reader|no|
|VM|29%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3695)|
|Memory (System)|25.00GB (24.43GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by max06** [comment]
Same issue now after downgrade vom 1.57.0 to 1.56.2

**Comment by max06** [comment]
I had to cleanup my whole vscode installation (with https://superuser.com/questions/1380208/how-to-completely-uninstall-visual-studio-code-from-windows-10/1380253) before installing the previous version (1.56.2) again to make it work. I'd really like to know what happened...

**Comment by bamurtaugh** [comment]
@EdwardAndrew Are you still experiencing this? If so, can you share relevant logs? Info here: https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues.

@max06 You may have experienced a different issue if yours was with Remote - Containers versus Remote - WSL (unless both were related to VS Code Server). If you have any relevant logs and additional details you could share as well, that'd be great.

**Comment by EdwardAndrew** [comment]
> 
> 
> @EdwardAndrew Are you still experiencing this? If so, can you share relevant logs? Info here: https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues.
> 
After reinstalling vscode using @max06's suggestion I am no longer experiencing this issue.

**Comment by max06** [comment]
I've just upgraded to 1.57.1 with 0.183 and can still open files. Maybe something was messed up in my profile... :/

**Comment by bamurtaugh** [comment]
Thanks for the updates @EdwardAndrew @max06! It sounds like neither of you are experiencing this issue anymore, so I'll close this out for now. If you do start seeing it again, please just let us know, and we can reopen/discuss further.
