### ISSUE TITLE
Extremely slow git operations via the UI

### ISSUE THREAD

**Issue by eladsegal** [microsoft/vscode-remote-release#5200]
Issue Type: <b>Performance Issue</b>

Any git operation via the UI takes a few seconds to complete when working remotely on WSL.

It is affecting all of my repositories, and is reproduced even with a new empty one:
1. Connect to a WSL Ubuntu-18.04 target (didn't check for other OSs).
2. Create a new folder and run `git init` in it.
3. Use VS Code Remote Explorer to connect to WSL and open the folder.
4. Create a new file in it.
5. Staging the created file takes a few seconds, and also unstaging or diff.

This doesn't happen when I work locally (i.e. without the Remote extension), and also doesn't happen when I work with Remote - SSH.
In VSCode on WSL, when checking out what happens in the Git output after an operation, I can see that it takes some time from the click until the commands are shown, and also there is some time between each command.
In regular/SSH VSCode, everything in the Git output is shown immediately after the click for a git operation.

I saw https://github.com/microsoft/vscode/issues/120883 so I am not 100% sure the issue is related to the Remote WSL extension, but I am opening it here since I only managed to reproduce it with it.

Extension version: 0.56.5
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3991)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.26GB free)|
|Process Argv|--crash-reporter-id 884db275-f67a-4a3f-a58b-1a476aeacceb|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4001)|
|Memory (System)|15.88GB (5.26GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   119	 21036	code main
    0	   130	 11148	   gpu-process
    0	    64	 11420	   utility
    0	    87	 14852	   window (Issue Reporter)
    0	   206	 19548	   window (test.py - test [WSL: Ubuntu-18.04] - Visual Studio Code)
    0	   136	 28240	     extensionHost
    0	    75	 26412	       electron_node wslDaemon.js 
    0	    56	 22460	   crashpad-handler
    0	    99	 23980	   shared-process
    0	    64	   760	     ptyHost

Remote: WSL: Ubuntu-18.04
CPU %	Mem MB	   PID	Process
    0	     0	  5868	remote agent
    0	     0	  5879	   ptyHost
    0	     0	  8821	     /bin/bash
    0	     0	  8760	   extensionHost
    0	     0	  8950	     /home/eladsegal/.vscode-server/extensions/ms-python.python-2021.5.926500501/languageServer.0.5.59/Microsoft.Python.LanguageServer
    0	     0	  8767	   watcherService
    0	     0	  9038	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  9039	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: WSL: Ubuntu-18.04|    Folder (test): 2 files|      File types: py(1)
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30321503
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by gaojs2019** [comment]
I have the same problem

**Comment by bamurtaugh** [comment]
Thanks for reporting. Would you be able to share your WSL and git output channels?

Also just to verify @gaojs2019 - do you only experience this with Remote - WSL similar to @eladsegal, or do you think this could also be https://github.com/microsoft/vscode/issues/120883 for you?

**Comment by eladsegal** [comment]
Hi @bamurtaugh, seems that I can no longer reproduce the issue.
In the past few days I worked locally or via Remote - SSH instead of WSL. I launched WSL now to get the outputs, but I see that git operations are just as fast as they used to be and I don't recall any change I've made in the environment.

I'll let you know if I encounter this again.

**Comment by eladsegal** [comment]
Hi @bamurtaugh, I am experiencing the exact same issue again.

Extension version: 0.58.5
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3991)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.86GB free)|
|Process Argv|--crash-reporter-id 884db275-f67a-4a3f-a58b-1a476aeacceb|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4001)|
|Memory (System)|15.88GB (3.86GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593cf:30376535
vssld246:30401890
vscexrecpromptt2:30404948
vscop804cf:30404767
vscop940:30404999

```

</details>

**Comment by bamurtaugh** [comment]
@lszomoru @aeschli any ideas on what could cause this or how to help diagnose?

**Comment by aeschli** [comment]
If you run the same git commands in the integrated terminal in the WSL window, is that fast?
Also, can you do a `whereis git` to make sure that git is not git from windows.

**Comment by eladsegal** [comment]
- Yes, the exact git commands are fast in the integrated terminal, it uses bash.
- ```
    $ whereis git
    git: /usr/bin/git /mnt/c/PROGRAM FILES/GIT/CMD/git.exe /usr/share/man/man1/git.1.gz
    ```
    WSL git version is 2.17.1. Windows git version is 2.29.2.windows.1.
    In the top of the git output tab I have
    ```
    Validating found git in: git
    Using git 2.17.1 from git
    ```

**Comment by lszomoru** [comment]
@eladsegal, could you please download the latest version of Insiders as we are now including some additional information (timestamp, execution time) in the Git Output that hopefully will shed some light on the performance degradation that you are seeing.

**Comment by eladsegal** [comment]
@lszomoru, I downloaded it and checked the Git Output.
The times there are just a few milliseconds for `git ls-tree -l HEAD`, but the actual loading times in the UI are a lot longer.
Here's an example I recorded with a relatively short loading time.

2.06 seconds from the click until the `git ls-files` command is shown in the Git Output.
2.46 seconds from the click until the diff is shown.

![](https://im2.ezgif.com/tmp/ezgif-2-ebb73df3e8.gif)

**Comment by lszomoru** [comment]
@eladsegal, looks like the image that you have uploaded is a broken link. Can you please try uploading the image again. Thanks!

**Comment by eladsegal** [comment]
Sorry, now it should be fine!

**Comment by hldd3n** [comment]
I have the same issue. Removed all VSCode Remote Extensions and when I open code from WSL terminal VSCode Source Control feature works perfectly fine.

**Comment by EmreOzkose** [comment]
I have the same issue, working on a few servers. I faced this issue with a server that I usually working on. Then I switch to another server. Then vscode works fine. Then I tried to find what causes this. My teammate started a deep learning training and it uses a lot of CPU (I think it should use GPU?????). I think the reason is that. One of your teammates can allocate the whole server with his/her own works. The solution might be htop>f9, but not recommended.

**Comment by lszomoru** [comment]
@eladsegal, sorry for not getting back to you on this, as this issue got lost in the sea of issues assigned to me. Over the last couple of milestones we have done some work to improve the Source Control performance with more work to come next year so I wanted to check in with you to see if you are still having performance issues while using Source Control?
