### ISSUE TITLE
Bash shells without titles

### ISSUE THREAD

**Issue by thistlillo** [microsoft/vscode-remote-release#5201]
Issue Type: <b>Bug</b>

All of a sudden my Visual Studio Code, attached to a remote container in a Kubernetes cluster, stopped showing the names of the remote bash shells.

![image](https://user-images.githubusercontent.com/6717655/122081930-d4793580-cdff-11eb-8021-b42b2016e061.png)

Extension version: 0.177.2
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043
Remote OS version: Linux x64 4.15.0-142-generic

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by Tyriar** [comment]
I believe updating to 1.57 will fix this
