### ISSUE TITLE
SSH Targets missing after update

### ISSUE THREAD

**Issue by Fireant456** [microsoft/vscode-remote-release#5202]
Issue Type: <b>Bug</b>

The list is not populating, the config files still show the remotes but the UI is not showing them.

Extension version: 0.65.7
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.25.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (15.81GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bcad1.sonoransoftware.com/home --crash-reporter-id 013f239e-4915-442e-83c5-37f213a572b6|
|Screen Reader|no|
|VM|40%|

|Item|Value|
|---|---|
|Remote|SSH: cad1.sonoransoftware.com|
|OS|Linux x64 3.10.0-1160.25.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (8 x 3200)|
|Memory (System)|31.25GB (24.22GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
pythonvsuse255cf:30319632
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by Fireant456** [comment]
Seems it is infrequent, sometimes it will load and others it will not.

**Comment by roblourens** [comment]
Nothing changed on my end, when it doesn't show up can you check the devtools console for errors? (Help > Toggle Developer Tools)

**Comment by moono** [comment]
Same issue here.
I don't see any remote container lists on 'REMOTE EXPLORER' but still can access with 'Recent' history tab on Welcome page.
I use both 'SSH Targets' and 'Containers', but only 'Containers' are not shown..
This issue happened after I updated my docker desktop (I guess).

My setup is like following
* vscode on Windows 10
  * docker desktop version: 3.5.1
* remotes(SSH target & remote containers) are on Ubuntu


Below is my vscode screenshot...
![image](https://user-images.githubusercontent.com/6761398/124402774-5b6d5e00-dd6d-11eb-8b93-a456a016950f.png)

**Comment by moono** [comment]
oh this issue is about SSH targets, I should register new issue.
Sorry for the interrupt..
