### ISSUE TITLE
Auto port forwarding = false not respected when there's a tunnel provider

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#5208]
There is a race that occurs when auto port forwarding is off but there is also a tunnel provider registered.

In this case, even though auto port forwarding is off we still watch the proc filesystem so that the process info in the ports view can be filled in. However, because of the race, auto port forwarding still occurs.

**Comment by alexr00** [comment]
Fixed in main by https://github.com/microsoft/vscode/commit/41c86e5bb8c29f801d6036b738c0c6b548be58e5

**Comment by cmbrose** [comment]
Verified that this fix works as expected in codespaces for the `github/github` repro

**Comment by aloTu** [comment]
thanks！
