### ISSUE TITLE
Problem Installing Extensions & Missing Terminal

### ISSUE THREAD

**Issue by ruzicr** [microsoft/vscode-remote-release#5210]
Hi, when I open VSCode through my Ubuntu WSL there's no terminal and clicking 'install in WSL:Ubuntu' does not install extensions, there's a window in the bottom right running endlessly saying 'Installing Extensions'

**Comment by bamurtaugh** [comment]
Hi @ruzicr, thanks for reporting. It sounds like your issue could be https://github.com/microsoft/vscode-remote-release/issues/5129? If you think it may be the same issue, perhaps we can close this one and track together in that issue?

**Comment by bamurtaugh** [comment]
Going to close this one out in favor of the other linked issue. If folks are experiencing something unique here, please just let me know, and happy to discuss further. Thanks!
