### ISSUE TITLE
Go To Definition not working

### ISSUE THREAD

**Issue by Jeffhabs** [microsoft/vscode-remote-release#522]
- VSCode Version: Code - Insiders Version 1.35.0-insider
- Local OS Version: macOS Mojave Version 10.14
- Remote OS Version: Ubuntu 18.04.2 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
1. connect to remote server using ssh, no password. connects fine
2. open project directory on remote server (contains typescript/javascript)
3. Click on a symbol/function/variable
4. Select F12, command pallet >go to definition, or cmd+click won't go to definition. Nothing happens.

Does this issue occur when you try this locally?: No, when I open my project directory locally "Go To Definition" works just fine. 

Does this issue occur when you try this locally and all extensions are disabled?: No, when not connecting using ssh this works fine.

**Comment by Jeffhabs** [comment]
Intellisense also doesn't seem to be working. Here are a few screen shots comparing vscode-insider locally vs remote using ssh.

Vscode-insider local directory:
![Screen Shot 2019-05-30 at 3 29 08 PM](https://user-images.githubusercontent.com/10523812/58666241-ffaf8b80-82ef-11e9-905b-56136b1516b2.png)
![Screen Shot 2019-05-30 at 3 29 15 PM](https://user-images.githubusercontent.com/10523812/58666245-01794f00-82f0-11e9-8cb6-05cbab432927.png)

Vscode-insider remote directory:
![Screen Shot 2019-05-30 at 3 29 25 PM](https://user-images.githubusercontent.com/10523812/58666253-0a6a2080-82f0-11e9-9c04-54cca26a247d.png)
![Screen Shot 2019-05-30 at 3 29 31 PM](https://user-images.githubusercontent.com/10523812/58666257-0d651100-82f0-11e9-8773-2e7ac682d700.png)

**Comment by Jeffhabs** [comment]
Also something interesting. When I select to change my typescript version on the status bar I get this error when connected remotely via ssh:
![Screen Shot 2019-05-30 at 5 26 34 PM](https://user-images.githubusercontent.com/10523812/58671652-971cda80-8300-11e9-8af8-4a2094d52668.png)

This doesn't occur locally, it seems like there is an issue with the built-in Typescript & Javascript language features extension?

**Comment by far1s** [comment]
Same issue

**Comment by davidhtml** [comment]
Same here

**Comment by Zacharias030** [comment]
Same

**Comment by illiriks** [comment]
same issue

**Comment by mjbvz** [comment]
Possibly https://github.com/microsoft/vscode/pull/75547

@Jeffhabs Can you please test in the next VS code insiders build to see if that is the case. Also check the developer tools logs to see if there are any errors using the `Developer: toggle developer tools` command

**Comment by Jeffhabs** [comment]
@mjbvz It looks like everything is working again, although I do get these errors in my developer tools:
![image](https://user-images.githubusercontent.com/10523812/60121555-911feb00-9740-11e9-95e9-a5acf80c33ad.png)

Not sure if that is related, but I can confirm that I have a `package.json` at that path:
![image](https://user-images.githubusercontent.com/10523812/60121679-d6dcb380-9740-11e9-9ae9-0376bde3ea6b.png)

**Comment by mjbvz** [comment]
@Jeffhabs Thanks for testing. Can you see if the errors about the `package.json` come back again. I don't think they are related to the issue here. If you do see these errors again, please open another issue
