### ISSUE TITLE
Unable to write to Folder Settings because no resource is provided

### ISSUE THREAD

**Issue by SaltFish001** [microsoft/vscode-remote-release#5221]
Issue Type: <b>Bug</b>

打开VScode并选自WSL2 下的文件夹,会显示 -未提供资源，因此无法写入"文件夹设置"。- (Unable to write to Folder Settings because no resource is provided.)

Extension version: 0.56.5
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.42GB (48.80GB free)|
|Process Argv|--crash-reporter-id fdc4fb05-7364-4884-aee9-58a466e76ee2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics (16 x 2894)|
|Memory (System)|49.76GB (44.46GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehovct:30309550
vscod805cf:30301675
vscextlang:30322306
binariesv615cf:30323120

```

</details>

**Comment by chrmarti** [comment]
Please provide steps to reproduce.

**Comment by yash-fn** [comment]
Open project directory over SSH connection using the VScode server and Microsoft's SSH extension and then attempt to save tasks.json. the json file successfully saves but then I get this error and the tasks refuse to show up as an option from command bar.

**Comment by yash-fn** [comment]
Well. So not sure what I did other than delete folder and rsync a new copy, but now it works. Perhaps permissions error?

**Comment by yash-fn** [comment]
Could I have please more details about what specifically triggers this error? What files comprise "Folder Settings" and what resources are being referenced?

**Comment by SaltFish001** [comment]
I bought a new computer, and copy my wsl to this new computer.I don't have this problem again.I think this problem maybe a permissions error. @yash-fn @chrmarti . Sorry for the late reply.And I'm sorry for my poor English.

**Comment by SaltFish001** [comment]
> Please provide steps to reproduce.

Use command 'code project/xxx' in Windows Terminal. All of them are Node project. Then I'll got this information. Before I update my VS Code, I won't get the message.

**Comment by SaltFish001** [comment]
> Could I have please more details about what specifically triggers this error? What files comprise "Folder Settings" and what resources are being referenced?

I have no "Folder Settings". I always use the default settings. All the folder look like this pic.
![image](https://user-images.githubusercontent.com/42058801/125007981-152d3d00-e094-11eb-95cc-b4fc0ec15dbe.png)

**Comment by zhz** [comment]
I got the same problem and don't know the details, but I remove the message by delete the whole `User` directory in `~/.local/share/code-server` and vscode will create a new one.  you can backup the file `settings.json` before delete it and put it back in the new `User` directory.
