### ISSUE TITLE
localEnv not working on M1

### ISSUE THREAD

**Issue by pieterv-icloud-com** [microsoft/vscode-remote-release#5223]
- VSCode Version: 1.57.1
- Local OS Version: macOSBig Sur M1 Chip
- Remote OS Version: Debian 10
- Remote Extension/Connection Type: Docker

I have the following environment variables set in my devcontainer.json file:

	"containerEnv": {
		"GITHUB_TOKEN": "${localEnv:GITHUB_TOKEN}"
	},

	"remoteEnv": {
		"GITHUB_TOKEN": "${containerEnv:GITHUB_TOKEN}"
	},

This works a 100% when running on an intel chip, but the environment variables are never set on a M1 chip.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Where do you set `GITHUB_TOKEN`? Are you doing this the same way on both machines?

**Comment by pieterv-icloud-com** [comment]
I do this within my ~/.zprofile file on both machines

**Comment by chrmarti** [comment]
Does it work when you start VS Code from the terminal?
