### ISSUE TITLE
Remote Containers issue in multi stage build

### ISSUE THREAD

**Issue by hkford** [microsoft/vscode-remote-release#5224]
- VSCode Version: 1.57.0
- Local OS Version: macOS Mojave 10.14.6
- Docker Desktop for Mac Version: 3.4.0
- Remote Extension/Connection Type: Docker
- Logs:

```
 => ERROR [stage-1 2/8] COPY --from=python . .                             0.6s
------
 > [stage-1 2/8] COPY --from=python . .:
------
[2021-06-18T11:23:59.260Z] cannot replace to directory /var/lib/docker/overlay2/eysnzxu02s9qz5srpuzz6zcs1/merged/usr/include/mysql with file
```

Steps to Reproduce:

I am using Remote-Containers extension (ms-vscode-remote.remote-containers) and wrote Dockerfile like below. When I try to open in container, get error above. 

```Dockerfile
FROM python:3.8.3 AS python

FROM node:14
COPY --from=python . .

RUN npm -g install typescript 
```

But when I commented out multi stage build, I could open in container. 

```Dockerfile
#FROM python:3.8.3 AS python

FROM node:14
#COPY --from=python . .

RUN npm -g install typescript 
```
Recently I upgraded Docker Desktop for Mac, and after the upgrade remote containers of multi stage build fails.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Can you build the image manually from the shell? This might be independent of Remote-Containers.

**Comment by hkford** [comment]
Running `docker build` from the shell also failed. I created [an issue](https://github.com/docker/for-mac/issues/5775) in Docker Desktop for Mac.

**Comment by chrmarti** [comment]
Closing as upstream issue, thanks.
