### ISSUE TITLE
Installing extensions in WSL Remote: Ubuntu 20.04 hangs forever (and other issues)

### ISSUE THREAD

**Issue by Apocryphon-X** [microsoft/vscode-remote-release#5226]
## Issue Type: <b>Bug</b>

Install of any extension hangs forever on WSL-Remote. Clicking on <kbd>Install in WSL: Ubuntu</kbd> doesn't do anything.

## Other issues:
-  Integrated terminal is not working inside WSL Remote.
- Git support is not working inside WSL Remote.

## Failed attempts of fix:

- Re installation of VS Code.
- Re installation of WSL extensions.
- Re installation of `~/.vscode-server`.

## Logs with Trace level:
More details in files.
- Remote Server: [remoteagent.log](https://github.com/microsoft/vscode-remote-release/files/6679617/remoteagent.log)
![image](https://user-images.githubusercontent.com/40130428/122624326-5027ec00-d065-11eb-9159-2b5817f5476b.png)

- Window: [renderer10.log](https://github.com/microsoft/vscode-remote-release/files/6679618/renderer10.log)
![image](https://user-images.githubusercontent.com/40130428/122624290-266ec500-d065-11eb-96c3-38cbf048d33a.png)

## List of available versions:
~~Version 0.56.5 its extremely buggy for me, it literally doesnt do anything.~~
![image](https://user-images.githubusercontent.com/40130428/122624479-fc69d280-d065-11eb-99d6-ac46eaf28923.png)

------

Extension version: 0.56.4
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (5.18GB free)|
|Process Argv|--crash-reporter-id 8aecf3b2-9232-4e5d-a8e9-1ec523d9bde1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|12.35GB (11.96GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
binariesv615:30323119
```

</details>

**Comment by bamurtaugh** [comment]
Thanks for reporting. I wonder if this may be https://github.com/microsoft/vscode-remote-release/issues/5129? We also got https://github.com/microsoft/vscode-remote-release/issues/5210. It seems like the set of these may be able to get grouped together in https://github.com/microsoft/vscode-remote-release/issues/5129.

**Comment by bamurtaugh** [comment]
Going to close out in favor of the linked issue. If you're experiencing a problem different than that, happy to discuss further. Thank you!
