### ISSUE TITLE
Remote Containers - Bind mount not working on Mac M1

### ISSUE THREAD

**Issue by ItalyPaleAle** [microsoft/vscode-remote-release#5228]
- VSCode Version: 1.57.1
- Local OS Version: macOS 11.4 on Apple Silicon (M1)
- Remote OS Version: Docker Desktop for Mac 3.4.0
- Remote Extension/Connection Type: SSH/Docker/WSL

Using bind-mount from a folder on the local machine, every operation fails with `Operation not permitted`. VS Code can't show the files in the workspace folder, and all commands (including `ls` and even with `sudo`) fail.

I have tried using both gRPC and the legacy OSX mount.

Steps to Reproduce:

1. Open a project, for example a Node.js project in the local machine
2. Use "reopen in container" and choose the base image (verified for Node.js and Go using the official images)
3. Files don't show up in VS Code
4. Any command in the workspace folder fails

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by chrmarti** [comment]
Make sure you allow Docker to access your files (`System preferences` > `Security & Privacy` > `Privacy` > `Files and Folders`):
![image](https://user-images.githubusercontent.com/9205389/122724818-9acb8300-d274-11eb-8cea-3ab67561b1a1.png)

**Comment by ItalyPaleAle** [comment]
Of course, that was it. Thank you for pointing me there @chrmarti

**Comment by chrmarti** [comment]
I'll check if we can show a dialog explaining what could be the problem.

**Comment by chrmarti** [comment]
Closing as we don't see this often.
