### ISSUE TITLE
Is it possible to support mosh or similar functions in the future?

### ISSUE THREAD

**Issue by Sdator** [microsoft/vscode-remote-release#5230]
Those who have used mosh should know that it is very good and perfectly solves the problem of delay and lag, especially in a bad network. This is very suitable for remote office. Maybe a similar function can be added to solve this problem in the future?

Thanks!

**Comment by Tyriar** [comment]
We actually already have a similar feature called local echo that prints what was types eagerly before a response is received from the server. Read more about it on the `terminal.integrated.localEchoLatencyThreshold` setting
