### ISSUE TITLE
Can't establish connection to "host": The vs Code server failed to start

### ISSUE THREAD

**Issue by mushlih-almubarak** [microsoft/vscode-remote-release#5232]
- VSCode Version: 1,57
- Local OS Version: Windows 10 Home
- Remote OS Version: Linux
- Remote Extension/Connection Type: SSH
- Logs:
[18:08:31.644] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==Linux==
arch==x86_64==
tmpDir==/run/user/3487==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[18:08:31.646] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\Mushlih\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64593)
	at c (c:\Users\Mushlih\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:58918)
	at Object.t.handleInstallOutput (c:\Users\Mushlih\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:63335)
	at Object.t.tryInstall (c:\Users\Mushlih\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:415135)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\Mushlih\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:294918
	at async Object.t.withShowDetailsEvent (c:\Users\Mushlih\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:406463)
	at async Object.t.resolve (c:\Users\Mushlih\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:295994)
	at async c:\Users\Mushlih\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:127:110656
[18:08:31.651] ------

[18:08:32.106] "install" terminal command done
[18:08:32.110] Install terminal quit with output: 

# Steps to Reproduce:

1. I connected to ssh using this command: ssh user@IPAddress -p portNumber
2. The error "Can't establish connection to "host": The vs Code server failed to start" appears

# Additional information:

VS Code consuming a lot of memory on my server, which causes my server to won't/deny the SSH connection from VSCode.
Because I see that the "Number Of Processes" and "Physical Memory Usage" sections at cPanel are almost full, even though previously it was only a few percent.
How can there be no extensions installed on the remote so it's not heavy? And can I download the vs code server file so that I can upload it manually on my server later?

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
To double-check - are you able to successfully SSH into this machine via an external terminal, just not through Remote - SSH in VS Code? And those are the complete output logs?

> How can there be no extensions installed on the remote so it's not heavy?

Have you tried disabling all extensions (there is a **Disable All Installed Extensions** command in the Command Palette)?

> And can I download the vs code server file so that I can upload it manually on my server later?

The server is to be installed and updated automatically by VS Code, more info [here](https://code.visualstudio.com/docs/remote/faq#_can-vs-code-server-be-installed-or-used-on-its-own).

**Comment by mushlih-almubarak** [comment]
> are you able to successfully SSH into this machine via an external terminal
Yes, I tried it via terminal which is in vscode and it worked

> Have you tried disabling all extensions (there is a Disable All Installed Extensions command in the Command Palette)?
Does this just disable the extension in vscode or disable it on the server as well?

**Comment by bamurtaugh** [comment]
> Does this just disable the extension in vscode or disable it on the server as well?

I just double-checked in a Remote-WSL session, and it disabled all extensions (those installed locally and on the remote). This did include Remote-WSL itself though, so VS Code prompts to re-enable Remote-WSL and reload my workspace so that I can continue working in the remote session.

**Comment by mushlih-almubarak** [comment]
> It disabled all extensions (those installed locally and on the remote).

Is there a way to delete it from the server?  not just disable it?

**Comment by bamurtaugh** [comment]
I don't believe there is a command for that - did disabling the extensions make any difference?

**Comment by mushlih-almubarak** [comment]
> did disabling the extensions make any difference?

First, this appears:
![pq](https://user-images.githubusercontent.com/72560310/124349504-fe9c6700-dbf7-11eb-8232-9561dfa9012f.jpg)
Then I click reload window and SSH connects successfully.

Then, I tried to open the public_html folder on my host, but the SSH is disconnected, and got this error:
![image](https://user-images.githubusercontent.com/72560310/124349450-b715db00-dbf7-11eb-8af3-fea566223090.png)

And when I see at the stats in my Cpanel, it's almost full:
![image](https://user-images.githubusercontent.com/72560310/124349412-833ab580-dbf7-11eb-84fe-51eb47365ab4.png)

**Comment by mushlih-almubarak** [comment]
> did disabling the extensions make any difference?

First, this appears:
![pq](https://user-images.githubusercontent.com/72560310/124349504-fe9c6700-dbf7-11eb-8232-9561dfa9012f.jpg)
Then I click reload window and SSH connects successfully.

Then, I tried to open the public_html folder on my host, but the SSH is disconnected, and got this error:
![image](https://user-images.githubusercontent.com/72560310/124349450-b715db00-dbf7-11eb-8af3-fea566223090.png)

And when I see at the stats in my Cpanel, it's almost full:
![image](https://user-images.githubusercontent.com/72560310/124349412-833ab580-dbf7-11eb-84fe-51eb47365ab4.png)

**Comment by bamurtaugh** [comment]
Have you tried the command "Kill VS Code Server on Host?" This will remove the server, which can fix a wide range of issues and error messages you may see, such as "Could not establish connection to server_name: The VS Code Server failed to start."

**Comment by mushlih-almubarak** [comment]
Tried it but still can't connect.
Then I tried again but vs code didn't finish (maybe stuck?) connecting the SSH, last log:
```
Waiting for client to transfer server archive...
Waiting for /home/u4384288/.vscode-server/bin/507ce72a446***b27b7**c37225***b15afa9f48/vscode-scp-done.flag and vscode-server.tar.gz to exist
```

it's stuck like this (About 20 minutes):
![image](https://user-images.githubusercontent.com/72560310/125102592-2140eb00-e0e4-11eb-913f-218b4d8f7cf8.png)

**Comment by roblourens** [comment]
I suspect the problem is just not enough resource availability on your remote. The error in your last screenshot, "Cannot allocate memory" will be an issue and there's nothing we can do about that.

**Comment by mushlih-almubarak** [comment]
Ok, thank you
