### ISSUE TITLE
Can't connect to dev container after update

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#5238]
I had a dev container running and then updated to the latest version of Insiders. Reloading the window, opening a new window and then opening the dev container via Open Recent etc. did not help. The only remedy was to quit and restart VS Code. It seems that we lost PATH in the environment from which VS Code relaunched after the update. 

![image](https://user-images.githubusercontent.com/4674940/123014752-c1281600-d37b-11eb-93b3-5f5606d1acbe.png)

**Comment by chrmarti** [comment]
I have seen `yarn` missing in tasks recently. Restarting VS Code helped. @bpasero Have there been any recent changes in the shell environment probing?

**Comment by bpasero** [comment]
I do not think this ever worked simply because an update of VSCode is very likely to be called from Squirrel and thus would not keep the original environment we had around. Probably nothing we can fix unless we could pass on the environment in the `quitAndInstall` method:

https://github.com/microsoft/vscode/blob/a8f860beecc574eeac8581c48036d22d0aeacf6a/src/vs/platform/update/electron-main/updateService.darwin.ts#L113-L113

**Comment by joaomoreno** [comment]
> I do not think this ever worked simply because an update of VSCode is very likely to be called from Squirrel and thus would not keep the original environment we had around.

But why would Code not resolve the env once again? That appears to be new, since I have never seen this issue before.

**Comment by bpasero** [comment]
> But why would Code not resolve the env once again

I don't know? I think here are your rules:

https://github.com/microsoft/vscode/blob/6cd2784c46e6f676173045d083323a700000a40e/src/vs/platform/environment/node/shellEnv.ts#L25-L44

**Comment by joaomoreno** [comment]
Right. Given that there were recent changes here and I have never seen the issue before, I suspect the issue is new and due to the recent changes and not the logic which has existed for a long time. I can try to repro.

**Comment by joaomoreno** [comment]
@kieferrm Have you seen this since?

**Comment by tanhakabir** [comment]
Closing this issue since it seems inactive.
