### ISSUE TITLE
User confusion around the `unreachable or not Linux x86_64` ssh message

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-remote-release#524]
There seems to be small but steady stream of issues about not being able to connect to various non-linux86_64 machines. For example, in the last day or so: #520 #493 #517 

These issues include the error text that explains what is going wrong but are still being filed as bugs instead of feature requests, which suggests that we need to improve the error message itself. 

Some ideas:

* Have separate error messages for `host not reachable` and `unsupported OS`
* If connecting to an unsupported OS, explicitly say: "This OS is not supported" and link to our docs / ask for them to file a feature request

**Comment by roblourens** [comment]
It's hard because I can't tell the difference between arbitrary uname output and some arbitrary error message. It's probably easier to improve the error message case than the uname case, except for uname examples that I know to look for.

**Comment by roblourens** [comment]
This error is gone
