### ISSUE TITLE
Remote WSL: "Add folder to workspace" on a single-root workspace prompts Workspace Security prompt then never adds it

### ISSUE THREAD

**Issue by darkvertex** [microsoft/vscode-remote-release#5240]
- VSCode Version: 1.57.1 (user setup, from commit: 507ce72a4466fbb27b715c3722558bb15afa9f48, date: 2021-06-17T13:28:07.755Z)
- Local OS Version: Windows x64 10.0.19042
- Remote OS Version: Ubuntu 20.04.2 LTS
- Remote Extension/Connection Type: WSL
- Logs: N/A

Steps to Reproduce:

1. Open a git repo with VSCode on WSL storage.
2. File->"Add folder to workspace" and add another repo also from WSL.
3. Notice it prompts the "Do you trust this codebase?" ([Workspace Trust](https://code.visualstudio.com/docs/editor/workspace-trust)) prompt but just before you can say Yes, the entire window reloads.
4. After the window reloads, your second repo was not added and the Workspace Trust prompt does not appear again. You're back to step 1. 🤔

Does this issue occur when you try this locally?: No, but it might be because when not remote, there is no window reload.

**Comment by bamurtaugh** [comment]
cc @sbatten and @lszomoru for potential insights.

**Comment by sbatten** [comment]
this is resolved in insiders and will be released in stable at the end of this milestone. https://github.com/microsoft/vscode/issues/126015
