### ISSUE TITLE
Multiple vscode instances can't enter the same container at the same time 

### ISSUE THREAD

**Issue by MohamedAliRashad** [microsoft/vscode-remote-release#5246]
- VSCode Version: 1.57.1
- Local OS Version: Ubuntu 20.04
- Remote OS Version: linux
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. make a container in a remote machine
2. enter the remote machine through ssh then enter the docker container
3. from another device enter the same remote machine and then try to enter the same container

**Comment by bamurtaugh** [comment]
@chrmarti I believe this is the expected behavior as we don't intend for multiple users to connect at the same time?

**Comment by chrmarti** [comment]
The same VS Code version can connect to different folders of the same container. We could lift the requirement for having to use the same VS Code version and run multiple VS Code Servers (as we are for Codespaces now). The folder limitation is being worked on in VS Code (https://github.com/microsoft/vscode/commit/b1b44a3910c7df865eea155c3c367c2ec085b2bd).

@MohamedAliRashad What's the error / unexpected behavior you get?

**Comment by MohamedAliRashad** [comment]
@chrmarti I get disconnected and unable to reconnect again.
If i tried to connect again (after shutting and reopening vscode), i kick the other user out and the cycle continues.

**Comment by chrmarti** [comment]
@MohamedAliRashad Would using different Linux user accounts inside the container be an option? You can set that with `"remoteUser": "account"` in the attach config (`F1` > `Remote-Containers: Open Attached Container Configuration File...`).

**Comment by MohamedAliRashad** [comment]
@chrmarti we are using different accounts to access the remote machine

**Comment by chrmarti** [comment]
@MohamedAliRashad Can you try using different accounts accessing the container? What is the reason for sharing a single container?

**Comment by MohamedAliRashad** [comment]
@chrmarti We are using different accounts to accesss the remote machine and the container.
Development crossover.

**Comment by chrmarti** [comment]
This should work and might be a bug. How do you specify which account to use in the container? Do the two accounts in the container have separate home folders?

**Comment by MohamedAliRashad** [comment]
@chrmarti My last comment was a mistake from my side, i am unable to give separate accounts in containers.
Is there another solution ?

**Comment by chrmarti** [comment]
Make sure you are both running the exact same version of VS Code and try again. If the second still disconnects the first, please attach the log (`F1` > `Remote-Container: Show Container Log`) of both.
