### ISSUE TITLE
git gutter not working using Remote-ssh

### ISSUE THREAD

**Issue by Migelo** [microsoft/vscode-remote-release#5247]
- VSCode Version: 1.57.1
- Local OS Version: Ubuntu 20.04.2 LTS
- Remote OS Version: SUSE Linux Enterprise Server 15 SP2
- Remote Extension/Connection Type: SSH
- Logs:
[git_extension.log](https://github.com/microsoft/vscode-remote-release/files/6711102/git_extension.log)
[remote-ssh.log](https://github.com/microsoft/vscode-remote-release/files/6711105/remote-ssh.log)

Steps to Reproduce:

1. connect to a remote server
2. open any file under version control 
3. no git gutter indicators are shown

On the other hand both the source control tab works and
![image](https://user-images.githubusercontent.com/6537512/123308254-bad49e00-d523-11eb-8df9-45647ea3c658.png)

in the side-by-side file comparison changed lines are shown. 
![image](https://user-images.githubusercontent.com/6537512/123308369-db9cf380-d523-11eb-9ed6-32d2c4f6d157.png)

The `scm.diffDecorations` is set to `all`. 

The only clue to the issue is in git extension log, namely line:
`Open repository: /freya/u/mihac/gpu_testbed` 
The path above is wrong, the correct path is `/u/mihac/gpu_testbed`.
If I mount the server using `sshfs` and use vscode on the mounted folder git gutter shows. 

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
cc @eamodio for any potential insights.

**Comment by Migelo** [comment]
I managed to get git gutter indicators by debugging the file. It appears vscode sees two different versions of the same file. One in the work directory and another one in `/freya/u/mihac/gpu_testbed`.

Please see the video below.
https://user-images.githubusercontent.com/6537512/123989428-2e195c80-d9c9-11eb-8656-22b3c5fd154c.mp4

So I believe the problem with the remote session is that it thinks the files are in `/u/mihac/gpu_testbed` as shown by these lines in the log:
```
Opening repository for path='/u/mihac/gpu_testbed/dg_data_io.cu' failed; ex=Error: spawn ENOTDIR
```
Because once the debugger starts and git gutter indicators are shown the git appears to be looking at `/freya/u/mihac/gpu_testbed` as shown by these lines in the log:
```
> git show --textconv :dg_data_io.cu
> git ls-files --stage -- /freya/u/mihac/gpu_testbed/dg_data_io.cu
> git cat-file -s c3bad6cd7c03503c7a637cd56441e58ce46498b2
```

The full git log below.
[git_log.txt](https://github.com/microsoft/vscode-remote-release/files/6742260/git_log.txt)

**Comment by Migelo** [comment]
Ok, it appears my issue is simply another version of the popular symlink issue https://github.com/microsoft/vscode/issues/5970. The user home folders on the remote machine are supposedly located in `/u/USERNAME`. But `/u` is actually a symlink to `/freya/u`.
```
$ ls -l /u
lrwxrwxrwx 1 root 8 Oct 29  2019 /u -> /freya/u/
```

If I connect to the remote host and navigate to `/freya/u/mihac/gpu_testbed` git gutter indicators are shown. Closing this issue.

**Comment by eamodio** [comment]
@Migelo thank you so much for getting to the bottom of this.
