### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mfJara** [microsoft/vscode-remote-release#5248]
- Issue Type: `Performance`
- Extension Name: `remote-wsl-recommender`
- Extension Version: `0.0.10`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\T410\AppData\Local\Temp\ms-vscode-remote.remote-wsl-recommender-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bamurtaugh** [comment]
@mfJara It looks like you pasted the name of the file but not the actual contents - could you please share that file and any other relevant logs/information? 

Also just to verify - is the `remote-wsl-recommender` causing the high CPU load, or is `remote-wsl`? If its the recommender, how did you determine this?

**Comment by mfJara** [comment]
Hello there,

Sorry the whole notification process was automatically executed by VS Code.
Plus I have no idea of where can I retrieve any logs/information files and
finally any "determination" was done actually by VS Code itself, so
I am 100% unable to give you an acceptable answer.  =(

Nevertheless...
Later on that day I noticed that there was a Windows update download being
executed in the background and once the update was
completed my VS Code ran normally.

So I kindly suggest let us drop this issue report and keep observing my VS
Code behavior.  =)

How about that?

Thank you in advance.

Manuel.

**Comment by bamurtaugh** [comment]
Sounds great, thanks so much for the update @mfJara! Also for future reference, here's information on collecting logs for remote development in case you are curious: https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues.

Happy to reopen if you have any other questions or start running into any other issues.

**Comment by mfJara** [comment]
Thank you so much for the information
.I am taking note of this reporting issues process.

Thank you again.

Take care.

Manuel.
