### ISSUE TITLE
The process tried to write to a nonexistent pipe.

### ISSUE THREAD

**Issue by TimoVink** [microsoft/vscode-remote-release#525]
- VSCode Version: **1.35.0-insider**
- Local OS Version: **Windows_NT x64 10.0.16299**
- Remote OS Version: **Amazon Linux 2**
- Remote Extension/Connection Type: **SSH**
- SSH Client: **OpenSSH_7.9p1, OpenSSL 1.1.1a  20 Nov 2018**

Steps to Reproduce:
1. Configure remote host's ssh config
2. Try to connect from Visual Studio Code using _Remote SSH: Connect to host... > aws_
3. Connection fails with the error: **Can't connect to aws: unreachable or not Linux x86_64 (The process tried to write to a nonexistent pipe.)**

I've verified that running `ssh aws` in my shell _does_ connect, though it posts a warning: **Could not create directory '/u//.ssh'.** Probably due to Roaming Profiles?

**Comment by kieferrm** [comment]
Running a vanilla AWS Linux box on Lightsail work without complications both from macOS and Windows. Anything interesting in the `Remote - SSH` output channel?

**Comment by TimoVink** [comment]
Ah, thanks for pointing me to that output channel. The last line before the error is I'm seeing:
`Running type "C:\Users\TF256~1.VIN\AppData\Local\Temp\vscode-linux-multi-line-command-aws.sh" | ssh -F C:\Program Files\Git\etc\ssh\ssh_config aws to confirm the host platform`

It looks like the space in "Program Files" is causing the issue. If I change `remote.SSH.configFile` to `C:\PROGRA~1\Git\etc\ssh\ssh_config` I can connect successfully.

**Comment by kieferrm** [comment]
@TimoVink do you use the nightly version of the Remote extension? We had the quoting issue yesterday and fixed it around midday PT.

Pls reopen if needed.

**Comment by TimoVink** [comment]
Hey Kai,

I tried again using the following build:
- **Id:** ms-vscode-remote.remote-ssh-explorer-nightly
- **Version:** 2019.5.44100

I now see the following when trying to connect:
`Running type "C:\Users\TF256~1.VIN\AppData\Local\Temp\vscode-linux-multi-line-command-aws.sh" | ssh -F C:\Program Files\Git\etc\ssh\ssh_config "aws" bash to confirm the host platform`

Note that the host name is now properly quoted, but the path to the `ssh_config` file is still not. Which causes the following error:

```
>
> Can't open user config file C:\\Program: No such file or directory
> 
> The process tried to write to a nonexistent pipe.
>
```

I can easily work around this by not using a path with a space in it. Up to you if you want to re-open to track the quoting issue.

Thanks again for the assistance!
