### ISSUE TITLE
> @derived-coder Did installing wget or curl resolve the issue?

### ISSUE THREAD

**Issue by Abhiram4572** [microsoft/vscode-remote-release#5256]
> @derived-coder Did installing wget or curl resolve the issue?

yes, thanks. Actually, it is because that I use a wrong openssl lib... Thanks for your response!

_Originally posted by @amazingAmy in https://github.com/microsoft/vscode-remote-release/issues/3054#issuecomment-700741904_

Please let me know the fix in detail

**Comment by bamurtaugh** [comment]
@Abhiram4572 It looks like this may have been intended as a reply in another thread rather than a new issue. Going to close this out, but if you're experiencing a new issue, please just let us know. Thanks!
