### ISSUE TITLE
Password based authentication closing SSH Tunnel weird behavior

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-remote-release#526]
Issue Type: <b>Bug</b>

If you close the SSH Tunnel which says don't close, it normally reconnects on Mac and Windows if using keys. If you don't use keys and instead use password authentication closing that terminal leads to it saying the window has crashed on Windows or the attempting to reconnect overlay is on top of the terminal in Mac so I cannot enter my password. 

*Steps:*
1. Ensure `"remote.SSH.showLoginTerminal": true` in your settings
2. Configure and connect to a remote host which you don't have keys to
3. Close the SSH tunnel terminal

VS Code version: Code - Insiders 1.35.0-insider (e9c50663154c369a06355ce752b447af5b580dc3, 2019-05-30T05:18:06.502Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (5.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|18%|
</details>

**Comment by roblourens** [comment]
Don't close it then 😆 

On Mac you can always click "dismiss" to enter your password. But otherwise I don't think it's worth trying to fix this.
