### ISSUE TITLE
Test: URI Handler for Remote Containers

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#5261]
- [ ] anyOS @chrmarti 
- [ ] anyOS @joaomoreno 

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%235261%0A%0A)

---

There is now a URI Handler to clone a repository in a container volume. The URI has the following format: `vscode-insiders://ms-vscode-remote.remote-containers/cloneInVolume?url=https://github.com/microsoft/vscode-remote-try-python`

Test that the URI works from the browser and that error conditions like docker not running/installed or non-existing repositories are reported to the user.

**Comment by joaomoreno** [comment]
@egamma Works very nicely. Unsure whether you can control this but it would work best if it would open the container in a new window instead of replacing my current workspace.

**Comment by egamma** [comment]
@joaomoreno I agree and this should be doable, when attaching to a running container then we also open a new window.
