### ISSUE TITLE
Host requirements memory should be presented in a human-friendly way

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-remote-release#5264]
Testing #5262

Using the units as specified in the host requirements would be best:

<img width="444" alt="Screen Shot 2021-06-29 at 5 14 34 AM" src="https://user-images.githubusercontent.com/2193314/123795542-fa3f1980-d898-11eb-8cd0-9e3e1bece249.png">

When there is no memory in the host requirements, using some large unit would be preferable as I can't tell what 2083807232 bytes is without thinking:

<img width="434" alt="Screen Shot 2021-06-29 at 5 16 06 AM" src="https://user-images.githubusercontent.com/2193314/123795686-1d69c900-d899-11eb-859d-177369b682da.png">

**Comment by chrmarti** [comment]
Updated:
![image](https://user-images.githubusercontent.com/9205389/123939456-6f454880-d998-11eb-8840-9c1f7a9d1156.png)
