### ISSUE TITLE
Host requirements storage isn't showing up right

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-remote-release#5265]
Testing #5262

It shows it as ram?

<img width="444" alt="Screen Shot 2021-06-29 at 5 17 39 AM" src="https://user-images.githubusercontent.com/2193314/123795880-55710c00-d899-11eb-9ba6-c3f5455e1364.png">

**Comment by chrmarti** [comment]
Ooops, using #5264 to track.
