### ISSUE TITLE
Avast detects virus when ssh from other network using Remote SSH

### ISSUE THREAD

**Issue by essarn** [microsoft/vscode-remote-release#5269]
- VSCode Version: 1.57.1
- Local OS Version: macOS Big Sur 11.2.3
- Remote OS Version: Windows 10 Pro 19043.1081
- Remote Extension/Connection Type: SSH

My main Windows machine has an SSH server setup using OpenSSH. It is possible to successfully connect using my public IP both from the local network and another external network. 

The problem is that my antivirus software Avast always reports a "Command line detection" when connecting from an external network as seen here https://imgur.com/a/8jeM8if. Everything works as intendned but obviously, it is not good that a false positive (assuming) is being triggered.

Should I contact Avast about this or do you guys have any other information?

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
Thanks for reporting @essarn. Perhaps you can try allowing VS Code in the firewall? This answer is for Remote-WSL, but similar principle: https://superuser.com/questions/1477420/which-exceptions-should-i-add-for-wsl-and-hyper-v-in-avast-firewall.

**Comment by essarn** [comment]
This has now been fixed by avast so closing.
