### ISSUE TITLE
New window should automatically connect to same remote host

### ISSUE THREAD

**Issue by praveen-srinivasan** [microsoft/vscode-remote-release#527]
When I open a new window from a window that is connected to a remote host, the new window opens up not connected to the same host. Would it be possible for the new window to automatically connect to the same remote host?

**Comment by kieferrm** [comment]
@praveen-srinivasan how would you expect then to get a local window?

**Comment by praveen-srinivasan** [comment]
It could be a different option. Right now AFAIK there isn't one.

**Comment by praveen-srinivasan** [comment]
One thing I discovered was "Workspaces: Duplicate Workspace in New Window" which is related.

**Comment by sbatten** [comment]
There is a command `New Window on Active Host`
