### ISSUE TITLE
Mounting to remote host on another machine

### ISSUE THREAD

**Issue by jeremy-chua** [microsoft/vscode-remote-release#5270]
VSCode Version: 15.57.1
Sample project: https://github.com/microsoft/vscode-remote-try-go

I'm running a dev container from Windows 10 pro to a linux docker host on another machine. I'm faced with an error "Invalid Mount" when running remote dev container. The docker host setting works fine.

This issue, https://github.com/microsoft/vscode-remote-release/issues/489 mentioned a workaround. Howver, i'm not sure how it is configured using mounts in .devcontainer.json

Will greatly appreciate if someone a share how can i mount local folder on the dev container.

Thanks in advanced!

**Comment by Chuxel** [comment]
There's detailed information in our docs if you have not seen it: https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host

The key thing is mounts happen on the remote machine, not your local one.

**Comment by jeremy-chua** [comment]
Sorry for the late response. 
I used named volume which is also desired.
