### ISSUE TITLE
UNRESPONSIVE extension host — 'ms-vscode-remote.remote-ssh-explorer-nightly'  on startup of local workspace

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-remote-release#528]
Extension version: 2019.5.43037
VS Code version: Code - Insiders 1.35.0-insider (5c65d9bfa4c56538150d7f3066318e0db2c6151f, 2019-05-30T21:56:44.782Z)
OS version: Darwin x64 18.6.0

**Steps**
1. With ssh explorer pane open
1. Update VS Code

**Bug**
This causes the following `UNRESPONSIVE extension host` report:

```
 WARN UNRESPONSIVE extension host, 'ms-vscode-remote.remote-ssh-explorer-nightly' took 75% of 2038.601ms, saved PROFILE here: '/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/exthost-350c83.cpuprofile' 
Array(17)

{id: "Angular.ng-template", total: 44980, percentage: 2}
{id: "bierner.lit-html", total: 1219, percentage: 0}
{id: "dbaeumer.vscode-eslint", total: 911, percentage: 0}
{id: "eamodio.gitlens", total: 88010, percentage: 4}
{id: "EditorConfig.EditorConfig", total: 695, percentage: 0}
{id: "gc", total: 114, percentage: 0}
{id: "johnpapa.vscode-peacock", total: 1019, percentage: 0}
{id: "monokai.theme-monokai-pro-vscode", total: 445, percentage: 0}
{id: "ms-vscode-remote.remote-ssh-explorer-nightly", total: 1529585, percentage: 75}
{id: "ms-vscode.vscode-typescript-tslint-plugin", total: 774, percentage: 0}
{id: "ms-vsliveshare.vsliveshare", total: 9615, percentage: 0}
{id: "PKief.material-icon-theme", total: 9585, percentage: 0}
{id: "program", total: 27539, percentage: 1}
{id: "self", total: 103502, percentage: 5}
{id: "vscode.git", total: 171153, percentage: 8}
{id: "vscode.merge-conflict", total: 135, percentage: 0}
{id: "vscode.typescript-language-features", total: 3257, percentage: 0}
```

Here's the cpuprofile:
[remote-ssh.cpuprofile.zip](https://github.com/microsoft/vscode-remote-release/files/3239160/remote-ssh.cpuprofile.zip)

**Comment by roblourens** [comment]
The profile only show it taking 100ms to activate the explorer extension which seems fine. There's a lot of blank space in the profile so maybe it's not complete or corrupted?

**Comment by mjbvz** [comment]
Yeah this is very weird. @jrieken do you have any idea why the ssh extension is being flagged in this case?

**Comment by jrieken** [comment]
In doubt, it's always code loading? Is the extension minified?

**Comment by roblourens** [comment]
Yes

**Comment by roblourens** [comment]
This isn't actionable but let me know if you see it again @mjbvz
