### ISSUE TITLE
Cannot open png file in remote

### ISSUE THREAD

**Issue by LiZeC123** [microsoft/vscode-remote-release#5282]
Issue Type: <b>Bug</b>

1. Connect to a remote server
2. Open a png file

I checked the error log, it seems that it is because of the path, but I have not done any related configuration. I downloaded the picture locally and can be opened with vscode normally, so I think this problem may be related to the Remote-SSH plug-in. There is the error log:

![image](https://user-images.githubusercontent.com/11004853/124339644-79f31e00-dbe2-11eb-9e3d-8bc575a58d89.png)

Extension version: 0.65.7
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.15.0-130-generic
Remote OS version: Linux x64 4.15.0-130-generic
Remote OS version: Linux x64 4.15.0-130-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.43GB (0.61GB free)|
|Process Argv|--crash-reporter-id 1bb15eeb-6c8d-44e6-adb8-3c11e2091cad|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 深度学习|
|OS|Linux x64 4.15.0-130-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (48 x 1197)|
|Memory (System)|62.79GB (27.55GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 深度学习|
|OS|Linux x64 4.15.0-130-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (48 x 1197)|
|Memory (System)|62.79GB (27.55GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 深度学习|
|OS|Linux x64 4.15.0-130-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (48 x 1197)|
|Memory (System)|62.79GB (27.55GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30331937
binariesv615:30325510
aatestflightcf:30331712

```

</details>

**Comment by bersbersbers** [comment]
I have the same problem

![image](https://user-images.githubusercontent.com/12128514/126953443-68c121b1-7fe7-41ad-999a-f5b3613dc2a4.png)

with a different error message however (a warning, in fact):

> [Deprecation] Subresource requests whose URLs contain embedded credentials (e.g. `https://user:pass@host/`) are blocked. See https://www.chromestatus.com/feature/5669008342777856 for more details.

Interestingly, I see similar issues, with the same warning, in https://github.com/eamodio/vscode-gitlens/issues/1172#issuecomment-881278805 and in https://github.com/microsoft/vscode/issues/128309. But I begin to think that VS Code Remote is at the core of the issue.

The issue exists
- without any other extension installed,
- in VS Code 1.57.1 and 1.58.x (with Remote SSH stable and Insiders), but never in VS Code Insiders during that time (Remote SSH stable and Insiders)
- with a clean reinstall of remote and local VS Code
- when I open a remote (multi-root) `.workspace` file, but not when I connect to the same server without opening a workspace.

I wonder if my installation is broken somehow - which files would I need to inspect/clean to find this out?

**Comment by bersbersbers** [comment]
Contrary to the other issues (with GitLens and Markdown), for this problem, I see a Network request such as this one in the Developer Tools:

> Request URL: https://vscode-remote%2Bssh-remote%2Bbers@myhostname.vscode-resource.vscode-webview.net/home/bers/project/Example.png?version%3D1627287381337

I'd assume that this is the request that Chrome blocks, based on the presence of an `@` character.

In VS Code Insiders (Remote SSH stable), the same request looks like this:

> Request URL: https://vscode-remote+ssh-remote+myhostname.vscode-resource.vscode-webview.net/home/bers/project/Example.png?version%3D1627288544744

Note that `bers@` is missing.

And then I remembered where I had seen that kind of expression before: I start VS Code stable (and not Insiders!) using a shortcut such as

> vscode://vscode-remote/ssh-remote+bers@myhostname/home/bers/project/project.code-workspace

And that's how the username is introduced into resource requests! I removed `bers@` from the shortcut, and everything is working again (PNGs, GitLens, Markdown Math). So I guess the bug is this: 

### Opening remotes using `vscode://vscode-remote/ssh-remote+user@host` breaks resources.

**Comment by bamurtaugh** [comment]
Thanks for the detailed report. Is this now being tracked as https://github.com/microsoft/vscode/issues/128309?

**Comment by bersbersbers** [comment]
I find it reasonable to assume that VS Code can/should fix this by escaping/encoding "@" characters on their side, so I'd say yes.

**Comment by bamurtaugh** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/128309 - if there is an additional issue here, please just let me know, and happy to discuss further.
