### ISSUE TITLE
explorer.exe "connect failed" from bash

### ISSUE THREAD

**Issue by lxvm** [microsoft/vscode-remote-release#5284]
- VSCode Version: copied from Help>About
```
Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.22000
```
- Local OS Version: Windows 11 Version 21H2 (OS Build 22000.51)
- Remote OS Version: Debian GNU/Linux 11 (Testing)
- Remote Extension/Connection Type: WSL
- Logs: None

Steps to Reproduce:

1. open a terminal (Ctrl + \`) from a WSL remote window and type `$ explorer.exe` in bash
2. Error message: `<3>init: (1910) ERROR: UtilConnectUnix:467: connect failed 111`

I can open Explorer from a bash session in Windows Terminal, and was expecting I could do the same from the VSCode terminal.

**Comment by bamurtaugh** [comment]
Thanks for reporting. I just tried `explorer.exe` in a Remote-WSL integrated terminal in VS Code, and it worked. Can you share the full Remote-WSL logs? And does this occur every time you attempt to launch an Explorer?

**Comment by PavelSosin-320** [comment]
Windows 11: RIP Explorer. MsEdge is in Program files (x86)/Microsoft/Edge/application/ MSEddge.exe It works! 6hours of reconfiguration and counting

**Comment by lxvm** [comment]
I don't use Windows for most of my work so I haven't tried this in the past month but today it works again. I can't reproduce the behavior so I'll close the issue. Thanks!
