### ISSUE TITLE
Remote Explorer list for containers not showing

### ISSUE THREAD

**Issue by moono** [microsoft/vscode-remote-release#5285]
- VSCode Version: 1.57.1 
- Local OS Version: Windows_NT x64 10.0 19041
- Remote OS Version: Ubuntu 18.04 
- Remote Extension/Connection Type: Docker
- Logs: 

Steps to Reproduce:

1. Open VSCode
2. Select Remote Explorer icon

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

---
I don't see any remote container lists on 'REMOTE EXPLORER' but still can access with 'Recent' history tab on Welcome page.
I use both 'SSH Targets' and 'Containers', but only 'Containers' are not shown..
This issue happened after I updated my docker desktop (I guess).

![image](https://user-images.githubusercontent.com/6761398/124403295-9a50e300-dd70-11eb-8389-89b65336d300.png)

![image](https://user-images.githubusercontent.com/6761398/124403360-ef8cf480-dd70-11eb-831e-0c94ff014301.png)

**Comment by chrmarti** [comment]
Did you switch the context? What do you get when running: `docker context ls`? (Contexts are also shown in the Docker viewlet.)

**Comment by moono** [comment]
I just typed `docker context ls` in my windows and I get like,

![image](https://user-images.githubusercontent.com/6761398/124524150-db123000-de34-11eb-9b88-2e27a6ae0ce0.png)

**Comment by chrmarti** [comment]
Does `docker ps` show the containers you would expect? That uses the current context. You can switch the current context using the CLI or the Docker viewlet of the Docker extension.

**Comment by moono** [comment]
I think there is some miscommunication here?
I should elaborate more about my setup.

* I have two machine: Windows 10 (call it `A`), Ubuntu 18.04 (call it `B`)
  * So the actual docker containers are running on `B`.
  * And vscode is running on `A`
* I followed this link [Developing inside a container on a remote Docker host](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host) to setup remote development settings.
  * Both `A` and `B` have installed Docker
  * vscode remote extension pack is installed on `A`'s vscode
  * SSH key is set and etc...
* I use to see `B`'s container lists on remote explorer viewlet (because I have set `docker.host` as my remote machine `B` in `settings.json` on `A`'s vscode)
* I also use to see my recent work folders (including remote container ones) on Recent section on welcome page when I opened vscode.
* But now, I __cannot__ see any remote container lists on remote explorer viewlet.
* However, I still __can__ connect remote container and work inside container when I click recent work folders from Recent section on welcome page (or ctrl+r to open recent work folder history)

And for your question;
* `docker ps` shows containers that I expects.
* I will attach my docker viewlet's screenshot too. (I don't remember what docker viewlet looked like  when this was working correctly, because I never opened docker viewlet before..)
![image](https://user-images.githubusercontent.com/6761398/124680958-77eecf00-df02-11eb-9364-05a950e2935e.png)

**Comment by chrmarti** [comment]
The `DOCKER_HOST` environment variable and with that the `docker.host` setting only apply when using the default context, you seem to have switched to the `desktop-linux` context. Does it start working when you switch to the default context using `docker context use default`? (Reload VS Code if it doesn't pick it up automatically.)

**Comment by moono** [comment]
Wow. I just changed to default context and it works.!!
Thank you so much!!

**Comment by chrmarti** [comment]
The recent entries include the `docker.host` and context settings which keeps the working when switching the context.

Closing as answered.
