### ISSUE TITLE
devcontainer: bind mounted files are owned by root even if container using a non-root user with same UID/GID as host user

### ISSUE THREAD

**Issue by aallrd** [microsoft/vscode-remote-release#5296]
- VSCode Version: 1.57.1
- Local OS Version: Fedora 34
- Remote OS Version: RHEL 7.6
- Remote Extension: Docker (podman 3.1.2)

When starting a development container in my project, the files mounted inside the dev container are owned by root despite running as the default container USER. As a result, I cannot create or edit files.

I have followed the documentation [Adding a non-root user to your dev-container](https://code.visualstudio.com/docs/remote/containers-advanced#_adding-a-nonroot-user-to-your-dev-container) in order to use the configured USER in my image instead of root.

The UID/GID of my user on my Fedora workstation are the same ones as for the default USER _test_ in my image:
```
$ id
uid=1000(aallrd) gid=1000(aallrd) groups=1000(aallrd),10(wheel),974(docker) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
$ podman run --rm -it devenv-image id
uid=1000(test) gid=1000(test) groups=1000(test)
```

I am using the below _devcontainer.json_ configuration:
```
{
	"name": "devenv-image",
	"image": "devenv-image",
	"settings": { 
		"terminal.integrated.shell.linux": "/bin/bash"
	},
	// Required for an empty mount arg, since we manually add it in the runArgs
	"workspaceMount": "",
        // SELlinux protected
	"runArgs": [
		"--volume=/home/aallrd/work/project:/workspaces/project:Z"
	]
}
```

In VSCode, this is what I get in the terminal:
```
[test@2cd791b95643 project]$ ls -ltr /workspaces
total 0
drwxr-xr-x. 1 root root 806 Jul  6 19:20 project
[test@2cd791b95643 project]$ touch aa
touch: cannot touch ‘aa’: Permission denied
```

Do you know if I missed something in my configuration setup?

**Comment by chrmarti** [comment]
No, I'm not familiar with the combination of SELinux and Podman. You will probably find the same ownerships when you bind mount a folder using only the Docker CLI. Maybe ask on StackOverflow?

**Comment by aallrd** [comment]
So I went down the rabbit hole for the podman/rootless/UID stuff and found the answer to my questions.
Here are some great Dan Walsh articles for people stumbling on this issue as I did:
- [Running rootless Podman as a non-root user](https://www.redhat.com/sysadmin/rootless-podman-makes-sense)
- [Should you use the --user flag in rootless containers?](https://www.redhat.com/sysadmin/user-flag-rootless-containers)

To quote: _By default, rootless Podman runs as root within the container._

So it shows files as owned by root but it is actually mapped to your UID on the host, so you can actually already read/write to the mounted volume.

In order to have the files listed as the USER declared in the Dockerfile, add the `--userns=keep-id` flag in the `runArgs`.

You can also use the `podman unshare` command to run chown and set the UID/GID of the shared directory: 

```
podman unshare chown 200:200 -R /home/aallrd/work/project
```
