### ISSUE TITLE
bash: package: command not found after apt-get install package

### ISSUE THREAD

**Issue by rafsaf** [microsoft/vscode-remote-release#5297]
Tried it on two different computers with **Windows** with standard and fresh docker CLI and wsl2 configuration

Steps to Reproduce:

1. create a new empty folder `testxyz`, open it with code
2. `ctrl+shift+p` and select **Remote-Containers: Open folder in container**, 
3. click `open` when first dialog shows up, then choose "Python 3.9" in second one.
4. wait till container is ready
5. run `sudo apt-get update`
6. run `sudo apt-get install -y minizinc` (about 400mb), wait a while...
7. run `minizinc`

### EXPECTED 

to be something like `minizinc -h [options]` etc. suggesting that everything is fine with this package and it can be used in this container.

### AND IT SHOWS 

`bash: minizinc: command not found`

### AFTERTHOUGHTS 

It does not also work as `sudo minizinc`.

BUT the package seems to be downloaded, becouse after running again `sudo apt-get install -y minizinc` we have

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
minizinc is already the newest version (2.1.7+dfsg1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

1. It doesn't work directly in Docker file too, tried it like this:

```dockerfile
(.devcontainer/Dockerfile)
# ... default stuff

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends minizinc
```
i get the same result (IT IS installed but cannot be runned).

2. It doesn't work when using Docker CLI directly also (logging to container and same commands as above)

What am i doing wrong :d

**Comment by chrmarti** [comment]
Not familiar with that package. I suggest you take a look at its contents to see what the command names are.
