### ISSUE TITLE
Cannot connect remote server (Error: Handler already set!) On certain remote folders

### ISSUE THREAD

**Issue by Mactarvish** [microsoft/vscode-remote-release#5298]
When trying to browse log by Remote-SSH : Show Log, I got the same error.

- VSCode Version:1.57.1
- Local OS Version: Mac big sur
- Remote OS Version:Ubuntu 18.04
- Remote Extension/Connection Type: SSH
- Logs:

I've worked under a certain remote folder by vscode-remote for about half years, but today when I connected to it, I got the error `Cannot connect remote server (Error: Handler already set!)`:
![image](https://user-images.githubusercontent.com/13399458/124695467-ce193d80-df15-11eb-8720-a35f628ee758.png)

By the way, only this folder directory is bad, other directories work well.
How to solve it ?

**Comment by IssamLaradji** [comment]
A lot of people are having this same issue and it is making it very difficult to debug code on the server. I am not sure why it is not being looked at by the team.

**Comment by Mactarvish** [comment]
Removing all info about VScode on my Mac and redownloading it solved this issue.
