### ISSUE TITLE
EACCES with docker in LXD container 

### ISSUE THREAD

**Issue by nehz** [microsoft/vscode-remote-release#5299]
VSCode: 1.57.1
Container extension: 0.183.0
```
[22 ms] Remote-Containers 0.183.0 in VS Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48).
[22 ms] Start: Resolving Remote
[25 ms] Start: Check Docker is running
[25 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[29 ms] spawn docker EACCES
[31 ms] Docker returned an error code EACCES, message: spawn docker EACCES
```

Docker and VSCode are both inside a LXD unprivileged container with "security.nesting=true"
Docker in command line runes fine with normal user: 

```
docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.
...
```

What would be the best way to debug this?

**Comment by chrmarti** [comment]
Maybe VSCode's extension host process does not have permission to execute the `docker` CLI?

**Comment by nehz** [comment]
Thanks, anyway to check what it is executing as? I would of assumed it would be the same as the user running VSCode ?

**Comment by chrmarti** [comment]
Correct, it's the same user as VS Code runs with. Can that user run `docker version`? (I guess it would if it can run a container, but I'm not familiar with your particular setup.)

**Comment by nehz** [comment]
Turn's out need do `sudo --login` for switching users. For some reason though `docker` in console inside vscode still works
