### ISSUE TITLE
remote file unexpected update

### ISSUE THREAD

**Issue by wtnbgo** [Microsoft/vscode-remote-release#53]
Issue Type: <b>Bug</b>

1. open remote file 
2. input any text
3. file is overwrited without Save command

Is this a specification?

Extension version: 0.34.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft
Remote OS version: Linux x64 3.10.0-862.3.3.el7.x86_64

**Comment by kieferrm** [comment]
@wtnbgo do you have autosave enabled?

**Comment by wtnbgo** [comment]
@kieferrm  you got it!!   thanks
