### ISSUE TITLE
Don't suppress progress bar when downloading server

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-remote-release#530]
I'm on a bad internet connection and had to just stare at this for several minutes not knowing if there was an issue or not (while connecting to a local VM sharing my bad internet):

<img width="1027" alt="Screen Shot 2019-05-30 at 6 08 03 PM" src="https://user-images.githubusercontent.com/2193314/58674829-72c3fc80-8306-11e9-9128-95fdf96da204.png">

We could just show the progress bar via:

```
wget <endpoint> -q --show-progress --progress=bar:force 2>&1
```

**Comment by roblourens** [comment]
Will it still look like a progress bar in the output channel?

**Comment by Tyriar** [comment]
Oh yeah, it's an output channel 😦. Were you planning on replacing this step with a background terminal?

**Comment by roblourens** [comment]
I wasn't planning on replacing the output channel, but we are running it in a terminal, so we can show the progress bar and if you click "details" then you will see the terminal with the progress bar.

**Comment by roblourens** [comment]
This is much better...
