### ISSUE TITLE
Variables such as ${workspaceFolder} not resolved in runArgs

### ISSUE THREAD

**Issue by aallrd** [microsoft/vscode-remote-release#5301]
VSCode Version: 1.57.1
Local OS Version: Fedora 34
Remote OS Version: RHEL 7.6
Remote Extension: Docker (podman 3.1.2)

I am trying use the `${workspaceFolder}` variable in the `runArgs` property of my _devcontainer.json_ file to use the folder opened by VSCode:
```
"runArgs": [
  "--volume=${workspaceFolder}:/workspaces/${workspaceFolderBasename}:Z",
]
```

However building the container fails with this error indicating that the variable was not resolved:
```
[2021-07-06T16:59:09.847Z] Error: error creating named volume "${workspaceFolder}": error running volume create option: names must match [a-zA-Z0-9][a-zA-Z0-9_.-]*: invalid argument
```

Is it expected?

Could it be the same issue as https://github.com/microsoft/vscode-remote-release/issues/5007 ?

**Comment by chrmarti** [comment]
The variable names are slightly different for the devcontainer.json, so we can distinguish between the local names and the names inside the container. `--volume=${localWorkspaceFolder}:/workspaces/${localWorkspaceFolderBasename}:Z` should work.

**Comment by chrmarti** [comment]
See also https://code.visualstudio.com/docs/remote/devcontainerjson-reference#_variables-in-devcontainerjson.
