### ISSUE TITLE
Add `devcontainer` CLI - open folder in Remote-Containers

### ISSUE THREAD

**Issue by stuartleeks** [microsoft/vscode-remote-release#5302]
Add a new (optional) `devcontainer` CLI  to Remote-Containers.

Initially supported command will be `devcontainer open` to allow opening a folder with a dev container definition directly in Remote-Containers to avoid the prompt to re-open as a dev container

**Comment by egamma** [comment]
See also https://github.com/microsoft/vscode-remote-release/issues/2133

**Comment by stuartleeks** [comment]
Released to the insiders channel in version 0.188.0

**Comment by stuartleeks** [comment]
Demo video here: https://twitter.com/stuartleeks/status/1416039483313639424
