### ISSUE TITLE
Task does not run on folderOpen under Remote - WSL

### ISSUE THREAD

**Issue by kazarmy** [microsoft/vscode-remote-release#5309]
Issue Type: <b>Bug</b>

I have something like the following in my `tasks.json`:

```json
    {
      "label": "tsc watch: subprojectName/tsconfig.json",
      "type": "typescript",
      "tsconfig": "subprojectName/tsconfig.json",
      "option": "watch",
      "problemMatcher": [
        "$tsc-watch"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "presentation": {
        "clear": true
      },
      "runOptions": {
        "runOn": "folderOpen"
      }
    }
```

That task does not run when I open its WSL workspace folder (with VSCode running on Windows). Also,

1. I have done `Tasks: Manage Automatic Tasks in Folder` -> `Allow`.
2. Manually running the task via `Ctrl` + `Shift` + `B` works.

----

Extension version: 0.58.2
VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (7.81GB free)|
|Process Argv|--crash-reporter-id 0198d331-5e46-4651-b501-67cf2be1e237|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)|
|Memory (System)|12.41GB (11.62GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscorehov:30309549
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by bamurtaugh** [comment]
cc @alexr00 (since you may have insights regarding the tasks aspect?)

**Comment by alexr00** [comment]
@kazarmy I'm not able to repro this issue. I tried with the [hello world sample extension](https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-sample) and this task:

```json
		{
			"type": "typescript",
			"tsconfig": "tsconfig.json",
			"option": "watch",
			"problemMatcher": [
				"$tsc-watch"
			],
			"group": "build",
			"label": "tsc: watch - tsconfig.json",
			"runOptions": {
				"runOn": "folderOpen"
			}
		}
```

Can you confirm that you're using the Remote - WSL extension to connect to your WSL folder? Is the the folder you're opening on one of your mounted Windows drives, or is it in the WSL filesystem?

**Comment by kazarmy** [comment]
> @kazarmy I'm not able to repro this issue. I tried with the [hello world sample extension](https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-sample) and this task:

I tried the [hello world sample extension](https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-sample) too with your task, no joy. I did get the (somewhat late) notification that asked me whether automatic tasks should run after I opened the folder, but after clicking "Allow and run" and reopening the folder, the task did not run.

> Can you confirm that you're using the Remote - WSL extension to connect to your WSL folder?

![WSL extension active](https://user-images.githubusercontent.com/12002672/127867838-8a44acad-d867-4c37-be65-19ba8e6dd2bf.PNG)

> Is the the folder you're opening on one of your mounted Windows drives, or is it in the WSL filesystem?

What you mean by "mounted Windows drives" isn't exactly clear to me, but the folder I'm opening doesn't start with `/mnt/` so I presume it's in the WSL filesystem.

----

This issue isn't critical to me because I can do `Ctrl + Shift + B` to run `tsc watch` manually. About the only thing I think is different from the norm is that I have the SVN extension installed.

**Comment by alexr00** [comment]
@kazarmy did you already trust the workspace?

**Comment by kazarmy** [comment]
umm yes

![trust-helloworld-sample](https://user-images.githubusercontent.com/12002672/129170242-02ce8e08-82d8-413b-9abc-38187443dca4.png)

**Comment by alexr00** [comment]
@kazarmy do you still see this issue? I don't have any other ideas for how to repro, so if you're still seeing it I can add some extra logging and we can try to figure out from there.

**Comment by kazarmy** [comment]
Unfortunately yes ... emm how are you going to do the extra logging?

**Comment by alexr00** [comment]
I can add the logging as debug logging to our insiders build in October. Then, if you can help I'll ask you to download our [insiders built](https://code.visualstudio.com/insiders/), enable debug logging, and share the output.

**Comment by kazarmy** [comment]
Ok it appears that I can help.

**Comment by alexr00** [comment]
@kazarmy I was never able to repro this issue, but I was able to repro and fix https://github.com/microsoft/vscode/issues/136715. I think the cause was the same.

**Comment by kazarmy** [comment]
I will attempt to (perhaps foolishly) change my copy of `workbench.desktop.main.js` in `C:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench` and see whether adding the `await` statement works, probably tomorrow.

**Comment by alexr00** [comment]
@kazarmy no need to make any changes there :) An upcoming [insiders build](https://code.visualstudio.com/insiders/) will have the fix, and insiders will install side by side with the stable build you already have installed.

**Comment by kazarmy** [comment]
There doesn't to be a way to confirm the last git commit of an insiders build (yes I have read https://code.visualstudio.com/blogs/2016/05/23/evolution-of-insiders ... daily in what timezone?) but I guess waiting a couple of days won't hurt.
