### ISSUE TITLE
Can not connect to containers after I connect to my server by using remote-ssh extension.

### ISSUE THREAD

**Issue by joyous-coder** [microsoft/vscode-remote-release#5313]
- VSCode Version:  1.58.0
- Local OS Version:  win10 20h2
- Remote OS Version: ubuntu 20.04
- Remote Extension/Connection Type: SSH/Docker/
- Logs: 
```bash
[1199657 ms] Remote-Containers 0.187.0 in VS Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6).
[1199656 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[1200647 ms] error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified.
```

Steps to Reproduce:

1. First I use `Remote-SSH`  to connect to my server.
2. Then I try to use commend `attach to running containers`  to connect to containers
Usually after doing this , vscode would jump into the containers. But now it seems that the Remote-containers extension only allows me to  attach to my docker desktop's containers in windows system , not containers in remote servers . 

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by joyous-coder** [comment]
When I start my docker desktop in windows and build some containers , the extension doesn't throw this exception again. It shows the container I build in win10

**Comment by joyous-coder** [comment]
Turn out the 'docker.host' configuration in settings.json help me jumps into remote containers

**Comment by chrmarti** [comment]
When you connect with Remote-SSH make sure to open a folder in VS Code. Does that make it work? (Known issue.)

**Comment by joyous-coder** [comment]
Yeah，it works 👍🏻👍🏻

**Comment by joyous-coder** [comment]
Thanks！！！

**Comment by joyous-coder** [comment]
> When you connect with Remote-SSH make sure to open a folder in VS Code. Does that make it work? (Known issue.)

Will this be fixed in the future version??

**Comment by chrmarti** [comment]
Yes, no timeline though. We need to add API in VS Code. Tracking as https://github.com/microsoft/vscode-remote-release/issues/4913.
