### ISSUE TITLE
Dev container not stopping when closing vscode

### ISSUE THREAD

**Issue by fonzcastellanos** [microsoft/vscode-remote-release#5316]
- VSCode Version: 1.58.0
- Local OS Version: Windows 10 Home 10.0.19041
- Remote OS Version: WSL2 Ubuntu 20.04.1 LTS
- Remote Extension/Connection Type: Docker/WSL
- Logs:
  - [remoteContainers-2021-07-12T03-31-56.579Z.log](https://github.com/microsoft/vscode-remote-release/files/6798558/remoteContainers-2021-07-12T03-31-56.579Z.log)
  - [shutdownMonitor-2021-07-12T03-31-56.579Z.log](https://github.com/microsoft/vscode-remote-release/files/6798567/shutdownMonitor-2021-07-12T03-31-56.579Z.log)

The last line of the shutdownMonitor log file (see below) shows `docker`, not `docker-compose`, being executed to stop the dev container.

> [2021-07-12T03:33:45.329Z] Unexpected error: Command failed: docker --project-name vscode-docker-shutdown-bug -f /home/alfonso/workspace/vscode-docker-shutdown-bug/docker-compose.dev.yml stop -t 0

Steps to Reproduce:

1. Launch Windows Terminal and open a Ubuntu 20.04 tab, which is where steps 2, 3, and 6 will be executed.
2. Clone the minimally configured repository located here: https://github.com/fonzcastellanos/vscode-docker-shutdown-bug.
3. Execute the commands below.
```bash
    cd vscode-docker-shutdown-bug
    code .
```
4.  Execute **Remote-Containers: Rebuild and Reopen In Container** in vscode and wait until completion. 
5. Close vscode. 
6. Run `docker container ls` and you should see the container from image _vscode-docker-shutdown-bug_my-service_  as up. 

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by i-ky** [comment]
Duplicates #5321.
