### ISSUE TITLE
Option to "Open Folder in Container" is not present

### ISSUE THREAD

**Issue by etuverajr01** [microsoft/vscode-remote-release#532]
Issue Type: <b>Bug</b>

<img width="961" alt="remote-container-not-working" src="https://user-images.githubusercontent.com/51110849/58680938-a5b8cf80-839c-11e9-8c48-bb45e3e37afe.png">

1. Install the Remote - Containers extension
1. Press F1 and type `Remote-Containers` to filter the list. 
1. Option to `Open Folder in Container` is missing.

For the record, I am attempting to do this using the `https://github.com/microsoft/vscode-remote-try-python` sample repo. I also have an existing working Docker Desktop installation.

Extension version: 0.57.0
VS Code version: Code - Insiders 1.35.0-insider (5c65d9bfa4c56538150d7f3066318e0db2c6151f, 2019-05-30T21:57:25.685Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.4.0-17134-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (7.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17134-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|15.82GB (7.21GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
You're in a WSL session, that command is not available there. Try cloning that repository on Windows and then open the folder in a container from a new (non-WSL) window.

**Comment by etuverajr01** [comment]
I've done both, making sure to open VS Code insiders from the Start Menu instead of a WSL terminal, and it still shows WSL in the lower left-hand corner.

I'm curious - how exactly does it determine if its a WSL session or not?

**Comment by chrmarti** [comment]
It is a WSL session when it run the VS Code Server under Linux and shows you the Linux filesystem.

Try opening a new window with Ctrl + N, that should be an empty local window, and "Open Folder in Container" from that.

**Comment by etuverajr01** [comment]
There we go, that seems to have done it. Everything's working fine now, thanks!

**Comment by chrmarti** [comment]
Closing then, thanks.
