### ISSUE TITLE
Cannot select a specific terminal when using remote-ssh

### ISSUE THREAD

**Issue by Ezra-Yu** [microsoft/vscode-remote-release#5326]
🚨 The issue tracker is not for questions 🚨

When I try to connect to the server, an error like this is reported
![image](https://user-images.githubusercontent.com/18586273/125416052-081766f5-e9a4-4f09-9380-2399159000df.png)

But I have switched the path of the local terminal, and there is no problem running the terminal locally
![image](https://user-images.githubusercontent.com/18586273/125416580-eb5086fb-7317-415f-9e24-336432952c7e.png)

**Comment by bamurtaugh** [comment]
Although you see that message in the first screenshot, does it affect or limit your functionality at all? Or do you still have a fully functional session?
