### ISSUE TITLE
Connect to host entries in GH PR view

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-remote-release#5327]
I tried to checkout and clicked the top entry due to muscle memory 😢 

![image](https://user-images.githubusercontent.com/2193314/125514227-1833e01b-878f-4920-8dac-03414008e23d.png)

I don't know what the top two are meant to do but they don't work:

![image](https://user-images.githubusercontent.com/2193314/125514301-0aba56e5-fd10-4699-929e-3a86750c646c.png)

**Comment by Tyriar** [comment]
There's also a connect to host in new window button on hover

**Comment by bamurtaugh** [comment]
cc @alexr00 as well

**Comment by alexr00** [comment]
Looks like the SSH extension is contributing commands to the PR view's context menu.

**Comment by roblourens** [comment]
Oh this was fixed awhile back.
