### ISSUE TITLE
Failed to connect to the remote extension host server (Error: Connection error: Version mismatch, client refused.)

### ISSUE THREAD

**Issue by kmui2** [microsoft/vscode-remote-release#533]
- VSCode Version: 1.34.20-insider (system setup)
- Local OS Version: Windows_NT x64 10.0.17763
- Remote OS Version: Ubuntu 16.04.6 LTS
- Remote Extension/Connection Type: SSH
- Extension Version: 0.39.0

Steps to Reproduce:

1. Select `Remote-SSH: Connect to Host...` from menu and then choose **any** host.
2. Wait until the notification pops up.

Note: It worked before (EDIT: presumably 0.37.0) but then I suddenly get this error. I only get this on this computer I'm using. I can connect normally on my Ubuntu 18.04 VM to the host below without the error below.

(Host is `sapir`)

![image](https://user-images.githubusercontent.com/17896701/58682222-555a5700-8335-11e9-9040-679d15e4ee14.png)

![image](https://user-images.githubusercontent.com/17896701/58682385-f21cf480-8335-11e9-81d3-131486ef291a.png)
![image](https://user-images.githubusercontent.com/17896701/58682403-0103a700-8336-11e9-9f45-c29e354df294.png)
![image](https://user-images.githubusercontent.com/17896701/58682409-0eb92c80-8336-11e9-93b1-5c908a3eca9b.png)

(Host is `vmware`)
![image](https://user-images.githubusercontent.com/17896701/58682640-09101680-8337-11e9-918b-5a4dce1c8d8a.png)

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by DanielKristofKiss** [comment]
Something went wrong with the Remote - SSH extension version 0.39.0.
Downgrade it to the previous version 0.37.0 "solves" the issue.

**Comment by sitepodmatt** [comment]
Seeing the same thing

**Comment by kmui2** [comment]
I can confirm that downgrading worked out for me. I've also disabled auto update in the meantime too. I'd like the above error message above to be both more clear and handled properly.

Also, from the discussion above, it seems important for bug reports to include the extension version number as well.

**Comment by roblourens** [comment]
Can you make sure that vscode insiders is updated? It looks like this will happen if you are using insiders from a couple days ago.

**Comment by kmui2** [comment]
This works using insiders couple days ago (0.37.0) but not with the most recent (0.39.0).

**Comment by roblourens** [comment]
I mean the vscode insiders version, not the extension version. You should be using vscode 1.35.0-insiders at 2737cde4facc8411982862742f5c6cd3dabef323

**Comment by kmui2** [comment]
Sorry didn't realize that. Anyways, I did try updating to 1.35.0-insiders but that produced the same result so it's not tied with the insiders version.

**Comment by roblourens** [comment]
Ok and you're sure it's the very latest 1.35 insiders? Could you post the log one more time using that version?

**Comment by kmui2** [comment]
I was switching from insiders 1.35 to 1.34 prior to reporting the bug and recalled that I got it both times which was why I didn't post a log. Okay, so this time I uninstalled 1.34 completely and installed 1.35 and got the same result in #536.

![image](https://user-images.githubusercontent.com/17896701/58736159-761cbe00-83c2-11e9-8dcb-d433f7f70421.png)

**Comment by roblourens** [comment]
Hm... are you sure that your vm is still reachable? If you run that command or even just `ssh vmware` in a terminal can you connect?

**Comment by kmui2** [comment]
Yes. So `sapir` is a remote Ubuntu 16.04 server while `vmware` is the Ubuntu 18.04 VM. I can SSH to both of them and use the extension on both of them on insiders 1.35 with Remote SSH version 0.39.0. 

I've got to switch back to 1.34 and 0.37.0 so I could continue my work. Sorry about that.

**Comment by kmui2** [comment]
Sorry, there really was an issue with `ssh vmware`. Ignore `vmware` for now.

**Comment by roblourens** [comment]
Are you sure that you need an old version of vscode Insiders? If there is an extension issue, the latest 1.35 insiders should work with the 0.37 extension right?

**Comment by roblourens** [comment]
@sitepodmatt @DanielKristofKiss Are you still having this issue?

**Comment by kmui2** [comment]
I can try upgrading to 1.35 and 0.39.0 later again.

**Comment by lamtranweb** [comment]
I ran into this same problem.... somehow I got the `Connection error: Version mismatch, client refused` error.  So I downgraded to 0.37.0 and it worked again.

Then I noticed that my VSCode Insider says something like "Restart to upgrade"... I did, then I upgraded my SSH extension back to 0.39.0 and it worked too.

Confirmed that my VSCode Insider is at `2737cde4facc8411982862742f5c6cd3dabef323` version.

**Comment by roblourens** [comment]
Thanks @lamtranweb, that's the problem I was expecting... sorry, I should have realized this would only work with a very up to date vscode build.

**Comment by roblourens** [comment]
@BilalDendani I see you had this problem too, are you using the latest VS Code insiders? Can you check if you are updated then try the latest extension version again?

**Comment by BilalDendani** [comment]
@roblourens 
My latest VS Code is 
`
Version: 1.35.0-insider
Commit: 0284236851a94b116f468345f6e98688a737015d
Date: 2019-05-31T21:25:54.986Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.19-100.fc27.x86_64
`
I updated to the latest extension Remote-SSH 0.39.0. Now it is working.

**Comment by roblourens** [comment]
Thanks for confirming

**Comment by BilalDendani** [comment]
thanks @roblourens .

**Comment by sitepodmatt** [comment]
Is there any way for remote extensions to specify minimum client version in manifest before updating? Presuming latest client supported 0.37 too?

**Comment by roblourens** [comment]
Yes but Insiders versions are not versioned individually so I can't limit the extension to the recent one where it works. I updated the extension a few days after the breaking change and thought that would be enough. In general if you are using Insiders, I recommend updating often.

**Comment by roblourens** [comment]
Also with the next vscode release, the remote extensions will be usable in stable vscode.

**Comment by sitepodmatt** [comment]
Thanks Rob, noted, new user and loving the experience so far, decided to leave the intellij world within a few hrs, keep it up

**Comment by kmui2** [comment]
Just installed 1.35 insiders again and the extension works this time!
```
Version: 1.35.0-insider (user setup)
Commit: 0284236851a94b116f468345f6e98688a737015d
Date: 2019-05-31T21:32:42.295Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

**Comment by roblourens** [comment]
Great, thanks for following up.

**Comment by CristianHR** [comment]
update the version of your vscode insider, that solved my problem

**Comment by gawinwong** [comment]
vscode1.35.0 
remote-ssh 0.42
still occur this problem
could someone give some ideas

**Comment by kmui2** [comment]
Did you use the auto-update? Try installing from their [website](https://code.visualstudio.com/insiders/).

**Comment by liamrathke** [comment]
Working for me on macOS 10.13.6 High Sierra, VSCode Insiders 1.36.0, and Remote SSH 0.42
