### ISSUE TITLE
Remote Development offline installation

### ISSUE THREAD

**Issue by Gladiatech** [microsoft/vscode-remote-release#5330]
Not strictly a technical issue but is there a way to download the right commit of the remote development for the specific vscode release?
I am asking because working in a box not internet connected I need to carry on an offline installation, usually I let the installation failing looking at the commit to download but I would like just to be capable to download everything in one shot.

cheers

**Comment by roblourens** [comment]
So the client and server are both without internet access?

**Comment by Gladiatech** [comment]
Server is completely isolated apart from the connection to my laptop, the laptop has internet access but it's heavily limited by the corporate firewall, I cannot for example download anything big like vscode or the remote server component.
I use a trick to transfer everything to the laptop from my personal computer and from the laptop to the box using winscp this is why it would be handy to know the commit number of the remote development server.

**Comment by roblourens** [comment]
It's the same as the commit of the client. We have this feature request
https://github.com/microsoft/vscode-remote-release/issues/1242
