### ISSUE TITLE
VS Code can not start WSL Server [version 1.58.1]

### ISSUE THREAD

**Issue by S3Y3D** [microsoft/vscode-remote-release#5332]
- VS Code Version: 1.58.1
- OS Version: Windows 10 Pro

Hi, I've just updated VS Code to 1.58.1 [I mean it updates automatically every time]
Since the latest version (1.58.1), WSL sever could not be run!
I download and install the previous version (1.57.1) and it was solved!
Unfortunately, I did not take any screenshots or any logs, and I'm on version 1.57.1 now.
PLEASE fix that.
🌻

**Comment by aeschli** [comment]
I just tested with 1.58.1 Windows_NT x64 10.0.19043, Remote-WSL extension version 0.52.2 and all worked.

Please try again and attach the Remote-WSL for more information

**Comment by SMRHG** [comment]
> I just tested with 1.58.1 Windows_NT x64 10.0.19043, Remote-WSL extension version 0.52.2 and all worked.
> 
> Please try again and attach the Remote-WSL for more information

OK, sure.

**Comment by SMRHG** [comment]
> I just tested with 1.58.1 Windows_NT x64 10.0.19043, Remote-WSL extension version 0.52.2 and all worked.
> 
> Please try again and attach the Remote-WSL for more information

![Issue](https://user-images.githubusercontent.com/59525413/125604805-7231db12-f675-470b-97c6-168447b93667.png)

I just updated to the latest version again, WSL works! but it shows me those red comments there in the terminal.
Does it need to add further logs?
Thanks in advance 🌻🙏
