### ISSUE TITLE
Failed to download VS Code Server ... HTTP 407 - authenticationrequired

### ISSUE THREAD

**Issue by MarkMindlin** [microsoft/vscode-remote-release#5337]
Issue Type: <b>Bug</b>

Partly Similar to
https://github.com/microsoft/vscode/issues/117153
Corporate VPN
Steps to reproduce:
- Open VSCode in WSL2 with VPN
- Set Proxy setting
- Reopen in Container
Expected results:
- a project will be opened in container 
- proxy settings will be derived from the WSL2
- VS Code Server will be downloaded and updated
Actual results:
- the proxy setting is empty in container
- VS Code Server is not downloaded
- Error message appear 
"Failed to download VS Code Server ... HTTP 407 - authenticationrequired"
- attempt to put value to the proxy setting in container is not successful - error appears in Notifications: "Unable to write to Folder Settings because no resource is provided"

Extension version: 0.187.0
VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.91GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/mmindlin/code/validation --remote=wsl+Ubuntu-20.04 --crash-reporter-id f01a1ef0-0999-46ff-8606-79c6c186976a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|12.39GB (10.00GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by chrmarti** [comment]
Try setting `"http.proxy"` to your `http://user:password@proxy-server`.

**Comment by MarkMindlin** [comment]
Yes, I can set the proxy setting when first open project in VSCode
> code .

BUT, In container, I CANNOT.

Here is my settings.json (
Folder /C:/Users/USERNAME/AppData/Roaming/Code/User/settings.json

{
    "yaml.schemas": {
        "file:///home/USERNAME/.vscode-server/extensions/atlassian.atlascode-2.9.1/resources/schemas/pipelines-schema.json": "bitbucket-pipelines.yml"
    },
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter.notebook.ipynb"
    },
    "aws.logLevel": "verbose",
    "http.proxy": "http://MyProxyUserName:MyProxyPassword@MyProxyServer:3128",
    "http.proxyAuthorization": null,
    "http.proxyStrictSSL": false,
    "remote.containers.logLevel": "trace",
    "remote.WSL.debug": true
}

**Comment by MarkMindlin** [comment]
Workarounded by downgrading the VS Code (was 1.58 - down to 1.52.1) and Jupyter extension

Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by chrmarti** [comment]
Could you check that you set `"http.proxy"` not only in your remote settings (for WSL2), but also in your user settings? (There are `User`, `Remote` and `Workspace` tabs near the top of the settings editor.)

We decoupled user and remote settings for `http.*` in a recent milestone (which might explain why it still works in 1.52).
