### ISSUE TITLE
Temporary port forwarding to non-localhost interfaces

### ISSUE THREAD

**Issue by leighmcculloch** [microsoft/vscode-remote-release#5340]
The temporary port forwarding feature is very useful, however it only supports port forwarding to the localhost interface on the host. It would be very useful if it was possible to configure which interface or address to bind to.

One example use case is port forwarding to the host for sharing across a VPN when working or demoing with colleagues.

**Comment by leighmcculloch** [comment]
A work around to this limitation is to use `socat` on Mac/Linux systems to listen on the other interface and port forward to localhost for port forwarding into the container. Example:

```
socat TCP-L:8001,bind=100.11.11.12,fork,reuseaddr TCP:127.0.0.1:8001
```

It works, but it is inconvenient.

**Comment by 1o1w1** [comment]
+1

**Comment by bamurtaugh** [comment]
Thanks for opening! I think this is https://github.com/microsoft/vscode-remote-release/issues/1386, so closing as a duplicate. If I'm mistaken, please just let me know, and more than happy to reopen/discuss further.
