### ISSUE TITLE
Unable to login to my linux using remote ssh, it prompts from multiple time to login, but doesnt succeed.

### ISSUE THREAD

**Issue by satishkrish-cloud** [microsoft/vscode-remote-release#5348]
Issue Type: <b>Bug</b>

Open vs code on  Macbook
install extension remote ssh
try loggin into the linux vm using ssh.

Extension version: 0.65.7
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

**Comment by bamurtaugh** [comment]
Can you please provide more information as outlined [here](https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues)? Thanks!

**Comment by satishkrish-cloud** [comment]
Done


Remote-SSH login issue into linux host · Issue #5399 ·
microsoft/vscode-remote-release (github.com)
<https://github.com/microsoft/vscode-remote-release/issues/5399>

**Comment by bamurtaugh** [comment]
Closing in favor of https://github.com/microsoft/vscode-remote-release/issues/5399
