### ISSUE TITLE
Extension is unable to find config file

### ISSUE THREAD

**Issue by thatreguy** [microsoft/vscode-remote-release#535]
I tried connecting to a remote server using settings in my config file. However for some reason vsode throws up error saying it is unable to locate the file. While I can clearly access the file from command line. Any ideas what might be causing this ?

ls -alh ~/Dropbox/config/ssh/config
```
-rw-------@ 1 emp_010  admin   638B May 31 10:27 /Users/emp_010/Dropbox/config/ssh/config
```

Logs:

```
remote-ssh@0.39.0
SSH Resolver called for "ssh-remote+digitalocean"
SSH Resolver called for host: digitalocean
Setting up SSH remote "digitalocean"
Using commit id "5c65d9bfa4c56538150d7f3066318e0db2c6151f" and quality "insider" for server
Using SSH config file "/Users/emp_010/Dropbox/config/ssh/config"
Install and start server if needed
> Found existing installation at /root/.vscode-server-insiders/bin/5c65d9bfa4c56538150d7f3066318e0db2c6151f...
> Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> 8887625f-f398-49d2-b4e0-673d7e54909b==44431==
"install" terminal command done
Received install output: 8887625f-f398-49d2-b4e0-673d7e54909b==44431==
Server is listening on port 44431
Using SSH config file "/Users/emp_010/Dropbox/config/ssh/config"
Spawning tunnel with: ssh -F /Users/emp_010/Dropbox/config/ssh/config digitalocean -N -L localhost:29289:localhost:44431
Spawned SSH tunnel between local port 29289 and remote port 44431
Waiting for ssh tunnel to be ready
Tunnel(44431) stderr: Can't open user config file  /Users/emp_010/Dropbox/config/ssh/config: No such file or directory

Could not establish tunnel to "digitalocean" (Max wait time exhausted).
Could not establish tunnel to "digitalocean" (Max wait time exhausted).

```

**Comment by kmui2** [comment]
Looks like only the admin has read and write permissions for the config. Could be an issue if the file is being attempted to be read by another user.

**Comment by ublftij** [comment]
Similar issue in my environment.
In my case,

I am working on Windows Host, Linux Client. It was working perfectly fine until a hour ago. It just stopped working when I open new window to open another project on the linux server. Since then, I've never successfully open projects via ssh.

<pre>
> Found existing installation at /home/devuser/.vscode-server-insiders/bin/5c65d9b
> fa4c56538150d7f3066318e0db2c6151f...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 65008574-57aa-495e-a6aa-05dd5a19b420==34585==
> 
"install" terminal command done
Received install output: 65008574-57aa-495e-a6aa-05dd5a19b420==34585==
Server is listening on port 34585
Using SSH config file "C:\Users\XXXXX\.ssh\config"
Spawning tunnel with: ssh -F C:\Users\XXXXX\.ssh\config myserver -N -L localhost:31865:localhost:34585
Spawned SSH tunnel between local port 31865 and remote port 34585
Waiting for ssh tunnel to be ready
Tunnel(34585) stderr: Can't open user config file  C:\\Users\\XXXXX\\.ssh\\config: Invalid argument

Could not establish tunnel to "myserver" (Max wait time exhausted).
Could not establish tunnel to "myserver" (Max wait time exhausted).
</pre>

**Comment by ublftij** [comment]
I don't know why, but I could avoid this problem by `"remote.SSH.showLoginTerminal": true` in settings.json.

With this option being true, it always succeed to connect to the remote,
and always fails with false.
Hope this helps.

**Comment by thatreguy** [comment]
> I don't know why, but I could avoid this problem by adding `"remote.SSH.showLoginTerminal": true` in settings.json.
> 
> With this option being true, it always succeed to connect to the remote,
> and always fails with false.
> Hope this helps.

This works. Thanks @ublftij !

**Comment by roblourens** [comment]
Thanks for the report, this should be fixed in the nightly ssh extension, would appreciate if someone can try it out and let me know?

**Comment by jellevandenhooff** [comment]
I still see the same issue:
```
remote-ssh@0.39.0
SSH Resolver called for "ssh-remote+devbox"
SSH Resolver called for host: devbox
Setting up SSH remote "devbox"
Using commit id "2737cde4facc8411982862742f5c6cd3dabef323" and quality "insider" for server
Using SSH config file "/Users/jelle/.ssh/config.devbox"
Install and start server if needed
> Found existing installation at /home/ubuntu/.vscode-server-insiders/bin/2737cde4facc8411982862742f5c6cd3dabef323...
> Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> 8217cd42-618d-42ba-950c-784c736eeb42==35737==
"install" terminal command done
Received install output: 8217cd42-618d-42ba-950c-784c736eeb42==35737==
Server is listening on port 35737
Using SSH config file "/Users/jelle/.ssh/config.devbox"
Spawning tunnel with: ssh -F /Users/jelle/.ssh/config.devbox devbox -N -L localhost:3776:localhost:35737
Spawned SSH tunnel between local port 3776 and remote port 35737
Waiting for ssh tunnel to be ready
Tunnel(35737) stderr: Can't open user config file  /Users/jelle/.ssh/config.devbox: No such file or directory

Could not establish tunnel to "devbox" (Max wait time exhausted).
Could not establish tunnel to "devbox" (Max wait time exhausted).
```

I am running
```
Name: Remote - SSH (Nightly)
Id: ms-vscode-remote.remote-ssh-nightly
Description: Open any folder on a remote machine using SSH and take advantage of VS Code's full feature set.
Version: 2019.5.44311
Publisher: Microsoft
```

**Comment by roblourens** [comment]
Can you make sure you uninstall the stable ssh extension first? Disabling remote extensions actually does not work currently. Should have mentioned that 😁

**Comment by jellevandenhooff** [comment]
@roblourens thanks, nightly works with other extension removed.

**Comment by thatreguy** [comment]
> Disabling remote extensions actually does not work currently

Better to put this in the Marketplace description?

**Comment by roblourens** [comment]
Good point, I've added it to the nightly's readme

**Comment by alexr00** [comment]
Based on [this comment](https://github.com/microsoft/vscode-remote-release/issues/535#issuecomment-497978105) marking as verified.
