### ISSUE TITLE
> @Friksel, I apologize, this shouldn't have been closed. I thought I was waiting to hear back from you for something but actually you had answered my questions to date. I am tracking dozens of confusing issues every day and make mistakes.

### ISSUE THREAD

**Issue by HCGM** [microsoft/vscode-remote-release#5350]
> @Friksel, I apologize, this shouldn't have been closed. I thought I was waiting to hear back from you for something but actually you had answered my questions to date. I am tracking dozens of confusing issues every day and make mistakes. 

Alright. Thanks for your apologies and clearing that up. Apologies and I understand. For me it also had to do with problems I faced with using the plugin for some months now and it takes too much time for me to keep trying to work around them. And that's a pitty, because I really like this extension and it creates an important workflow in my job that would otherwise be a pain to do. So if the extension connects everything is fine, but when it doesn't connect for hours it's very frustrating, because than I literally cannot do my job. Although I understand it's still in preview and I understand you guys work very hard on this.

So thanks for re-opening the issue.

> I'm still not sure what your issue is but if you are interested in trying one more thing, this may be fixed in the nightly build of the ssh extension. Find "Remote - SSH (Nightly)" in the marketplace (and uninstall the stable version). If you have set `remote.SSH.showLoginTerminal`, then disabling that might help too.

I was about to try the nightly build, but first I removed the showLoginTerminal setting I indeed had set. Removing this setting fixed the problem instantly. When adding showLoginTerminal: true again the problem got back and I never got a connection with that setting set to true. Removing the setting again fixed the connectionproblem again. After leaving it out I had no problems anymore. Today I had no problems connecting after that. Hope it holds!! And glad this fixed the connection problems (at least for now).

What I don't understand is why removing a setting to just show or hide the terminal should affect the connection to be made. Especially because the error message I previously got was that there was unparsable output. I'm very interested; Could you please let me know why this just showing/hiding of the terminal affects the connection of the extension? And are there any plans on fixing this so we can leave the terminal open during connecting? (which would be welcome in the future for debugging-reasons perhaps)

BTW it's working in VS Code 1.37.1 now too.

Thanks for the quick reactions and great it's working now (at least for now, hope it holds!!). And let this extension be a very stable extension. Because it's just a briljant idea and great and important tool to have. I'd rather stay with this extension than needing to look for alternatives. So keep up the great work.

_Originally posted by @Friksel in https://github.com/microsoft/vscode-remote-release/issues/1137#issuecomment-527573940_

**Comment by HCGM** [comment]
You are my LEGEND Friksel! Thanks to your comment, I resolved the which I've been working on for more than consecutive 8 hours yesterday and half an hour today. Good luck on your job and good luck on me as a research assistant at SRIBD!

**Comment by bamurtaugh** [comment]
Looks like this was resolved in the other thread, so going to close out this issue. If there is a new outstanding issue here, please let me know, and happy to discuss further. Thanks!
