### ISSUE TITLE
Docker compose service name as number in quoted not working

### ISSUE THREAD

**Issue by AmitRDesai** [microsoft/vscode-remote-release#5356]
- VSCode Version: 1.58.2
- Local OS Version: Windows 10 21H1
- Name of Dev Container Definition with Issue:
I have a service name "2020" in my docker-compose.yml file. I was working fine in version 0.183.0. But version above 0.183.0 I am not able to start dev container it is throwing an error

ERROR: In file '/tmp/docker-compose.devcontainer.containerFeatures-1626702558314
.yml', the service name 2020 must be a quoted string, i.e. '2020'

In the docker-compose file, I have used quotes.

I think in the newer version it is trying to copy the original yml file and that copied file does not have quotes.

**Comment by chrmarti** [comment]
The "features" yml is part of an exploration that shouldn't run yet. Could you post your devcontainer.json? (Related: https://github.com/microsoft/vscode-remote-release/issues/5317)

**Comment by AmitRDesai** [comment]
```
{
  "name": "2020",
  "dockerComposeFile": "../docker-compose.yml",
  "service": "2020",
  "workspaceFolder": "/app",
  "shutdownAction": "stopCompose",
  "runServices": [
    "2020",
    "assets"
  ],
  "extensions": [
    "dbaeumer.vscode-eslint",
    "angular.ng-template",
    "eamodio.gitlens",
    "esbenp.prettier-vscode"
  ]
}
```

**Comment by chrmarti** [comment]
Does adding `"updateRemoteUserUID": false` to the devcontainer.json work around the issue?
