### ISSUE TITLE
Remote container extension installation works spuriously and randomly

### ISSUE THREAD

**Issue by AntonioL** [microsoft/vscode-remote-release#5357]
- VSCode Version:
Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:09:06.581Z (5 days ago)
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 18.7.0
- Remote Extension/Connection Type: Docker
- Logs:

Steps to Reproduce:

1. I am on a laptop behind a company firewall, I set up proxy for vanilla VS Code (no remote) in the setting.json:
```json
    "http.proxy": "MY_COMPANY_PROXY",
    "http.proxyStrictSSL": false,
```

The above settings work fine in the vanilla VS Code environment (no remote).

2. I attach to a specific container and I am trying to install some extensions. No luck. I do this via the Docker extension by selecting the relevant running container, right click and I select "Attach to VS Code".

3. I remember that before I had managed installing some extensions on a container by amending the Remote Container configuration:
```json
{
	"extensions": [
		"llvm-vs-code-extensions.vscode-clangd",
		"ms-vscode.cmake-tools",
		"ms-vscode.cpptools",
		"twxs.cmake"
	],
	"workspaceFolder": "/Users/alombardo10/feeds-news/malay",
	"remoteUser": "dev",
	"remoteEnv": {
		"NODE_TLS_REJECT_UNAUTHORIZED" : "0",
		"NODE_EXTRA_CA_CERTS": "/etc/ssl/certs/ca-bundle.trust.crt"
	},
	"settings": {
		"http.proxyStrictSSL": false,
		"https.proxy": "http://proxy.bloomberg.com:81"
	}
}
```

But no luck, it has been spinning for 10 (and more minutes).

The main issue is that I have no visibility regards to the extension installation process, there is no reason for which it is super slow inside Docker. I tried going to Output tab on the bottom side of the window for some clue to troubleshoot this but I could not find anything/

Can you advise on how I can get more visibility on this issue? Any relevant logs I can paste here since under Output I do not get anything useful, maybe it is a proxy issue but I cannot find any evidence of it (and it still works with vanilla VS Code)? It is feeling like a lottery installing an extensions on a Remote Container. Thanks for advising

**Comment by chrmarti** [comment]
What does `F1` > `Remote-Containers: Show Container Log` show?

**Comment by AntonioL** [comment]
Eventually they got installed after some time (like 10 mins after creating this issue).

This slowness is killing me though, I am hypothesising might be to the slowness of I/o on mounted volume in Docker. 

Can you confirm what is the best log to refer to (and then I will close the ticket) for the next time this happens is this the one:


> What does `F1` > `Remote-Containers: Show Container Log` show?


?

@chrmarti

**Comment by chrmarti** [comment]
That's the one I would be interested in first, yes.
