### ISSUE TITLE
Its asking me for a sudo password on the WSL but i did not set up any

### ISSUE THREAD

**Issue by StefanVinica** [microsoft/vscode-remote-release#5358]
Issue Type: <b>Bug</b>

i cant continue to use the wsl extension and donwload stuff without a sudo password but i just did not setup any password

Extension version: 0.58.2
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (2.62GB free)|
|Process Argv|--crash-reporter-id 56c05d73-8b8c-432f-b29c-202f17a51466|
|Screen Reader|no|
|VM|31%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (2 x 2903)|
|Memory (System)|4.82GB (0.15GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by StefanVinica** [comment]
![image](https://user-images.githubusercontent.com/26149819/126392749-279fce70-7b59-4f9f-8a86-7e461f9d2af7.png)

**Comment by bamurtaugh** [comment]
Hi @StefanVinica, thanks for reporting. In order to use your WSL distro, even if you didn't set up a password through Remote-WSL (as there isn't an option to do so), you created a username and password for the distro itself when you installed it, so you will need to use that. More information here: https://docs.microsoft.com/en-us/windows/wsl/user-support.
