### ISSUE TITLE
Remote - SSH doesn't work in 0.39.0

### ISSUE THREAD

**Issue by seyong92** [microsoft/vscode-remote-release#536]
- VSCode Version: 1.35.0-Insider
- Local OS Version: macOS 10.14.5
- Remote OS Version: Ubuntu 16.04.5 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

After update to 0.39.0, I cannot make SSH connection to my linux server. (When I rollback to 0.37.0, it works again.)

It shows the message below.

Can't connect to [MY_USERNAME]@[MY_SERVER_DOMAIN] -p [PORT]: unreachable or not Linux x86_64 (ssh: Could not resolve hostname [MY_SERVER_DOMAIN] -p [PORT]: nodename nor servname provided, or not known )

**Comment by roblourens** [comment]
@seyong92 did you type the `-p port` yourself when connecting to the host? This will not work anymore, you have to include a custom port in your ssh config, then connect with just the hostname or username by itself

**Comment by seyong92** [comment]
I solved the problem after using ssh config, thanks :)
