### ISSUE TITLE
Installing extensions on remote location fails

### ISSUE THREAD

**Issue by cparker24** [microsoft/vscode-remote-release#5365]
I'm trying to install a couple extensions on an SSH host and I keep receiving the same error message on some of them.

"Unknown system error -122: Unknown system error -122, open '/home/cameron.parker/.vscode-server/extensions/.8a0e93d5-1554-4fdd-8e4c-4c827be7cb22/dist/typeshed-fallback/stdlib/chunk.pyi'"

This error happens when I try installing Pylance or ROOT File Viewer, but I was able to install other extensions without issue. I am aware of other threads where this issue was caused by a limit on file counts, so I tried cleaning everything non-essential out first so I would have room for about 5000 files, but this didn't help. I also tried installing them on a vscode server in a directory without the file limits and this also did not work. What mostly confuses me is how this affects certain extensions but not others. I have also been able to use these extensions locally, so they only fail to install remotely.

- VSCode Version: 1.58.2
- Local OS Version: Windows_NT x64 10.0.22000
- Remote OS Version: CentOS 7
- Remote Extension/Connection Type: SSH

**Comment by bamurtaugh** [comment]
Can you share the log from the Remote Extension Host output channel (Output: Focus on Output View), and select Log (Remote Extension Host) from the dropdown?

**Comment by cparker24** [comment]
> Can you share the log from the Remote Extension Host output channel (Output: Focus on Output View), and select Log (Remote Extension Host) from the dropdown?

I actually did some more digging and it turns out it was file count limits, it was just that the Pylance extension would create around 7,000 files before it maxed out.

**Comment by bamurtaugh** [comment]
Thanks for the update @cparker24. Sounds like we can close this one out (i.e. an issue on Pylance extension side?) - if I'm mistaken or there's further investigation/discussion here, please just let me know!
