### ISSUE TITLE
Terminal does not set the USER environment breaking cross-compiled Go tools

### ISSUE THREAD

**Issue by leighmcculloch** [microsoft/vscode-remote-release#5370]
- VSCode Version: 1.52.1
- Local OS Version: macOS 11.1
- Remote OS Version: `Linux 159762ce8558 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Remote Extension/Connection Type: Docker
- Logs: ?

The `USER` environment variable is not set in the VSCode terminal, however in the standard Mac Terminal it is set. When I compare the output of `env` in the VSCode terminal and the Mac Terminal app the outputs are much the same except that the `USER` environment variable is present in Mac Terminal and set appropriately to the username of the signed in user, but VSCode does not have that.

This impacts tools built with Go that were cross-compiled for Mac, which is common. Go's [`user.Current()`](https://golang.org/pkg/os/user/#Current) function loads information about the current user and when cross compilation is used it relies on the presence of common environment variables like `USER` to determine the username of the currently logged in user. If a cross-compiled tool that relies on `user.Current` is run inside VSCode's terminal it will get the error:
```
user: Current requires cgo or $USER set in environment
```

Mac Terminal and terminals in other unix and linux based operating systems often set the USER environment variable, and tools and scripts often rely on it. It is inconvenient and unexpected that VSCode's Terminal does not.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

This problem also happens when using VSCode's native terminal editor without remote containers: https://github.com/microsoft/vscode/issues/115288.

**Comment by chrmarti** [comment]
This would like be fixed with microsoft/vscode#115288. Tracking as upstream.

**Comment by leighmcculloch** [comment]
I've discovered this is isolated to just some of the devcontainers I use, which I assume means this is a result of those devcontainers Dockerfile setups which I will investigate, but clearly isn't an issue with VSCode.

I had created this because I thought it related to https://github.com/microsoft/vscode/issues/115288, but clearly that isn't the case.
