### ISSUE TITLE
Test: `devcontainer` CLI

### ISSUE THREAD

**Issue by stuartleeks** [microsoft/vscode-remote-release#5373]
Refs: #5302, #5349 

- [x] windows @joyceerhl 
- [x] wsl @rzhao271
- [x] linux @deepak1556
- [x] macOS @rzhao271

Complexity: 3

Authors: @stuartleeks, @chrmarti 

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%235373%0A%0A&assignees=stuartleeks,chrmarti)

---

## Setup

After installing Docker Desktop and the latest Remote-Containers extension, launch VS Code and run the "Remote-Containers: Install devcontainer CLI" command.

The steps below should be completed for both Dockerfile and docker-compose based dev containers.
- To create a Dockerfile based dev container, create a folder, open in VS Code, and use the "Add development container configuration files" command and pick a single container configuration such as "NodeJS"
- To create a docker-compose based dev container, create a folder, open in VS Code, and use the "Add development container configuration files" command and pick a single container configuration such as "NodeJS & Mongo DB"

### In the project folder

1. Start a terminal (outside of VS Code)  in the project folder (i.e. the one containing the `.devcontainer` folder)
2. Run `devcontainer build`. This should complete successfully and you should see the `docker build` output
3. Run `devcontainer build` again. This time you should see `CACHED` against the build steps indicating that cached layers have been used
4. Run `devcontainer build --no-cache`. This time you should not see any cached layers, i.e. no `CACHED` in the output
5. Run `devcontainer build --image-name test1`. After this, `docker images` should show the `test1` image (run `docker rmi test1` to remove it)
6. Run `devcontainer open`. This should open VS Code directly into the Remote-Containers extension, i.e. should show the `Dev Container:` remote indicator at the left of the window's status bar without prompting to re-open as a dev container
7. Close VS Code

### Outside the project folder

1. Change to a different folder in the terminal
2. Run `devcontainer build <relative path to project folder>`. This should perform a cached build of the dev container
3. Run `devcontainer open <relative path to project folder>`. This should open the project directly into the dev container
4. Close VS Code
5. Run `devcontainer build <absolute path to project folder>`. This should perform a cached build of the dev container
6. Run `devcontainer open <absolute path to project folder>`. This should open the project directly into the dev container
7. Close VS Code

### WSL-specific extra test

1. Launch a Windows shell (e.g. Command Prompt or PowerShell)
2. Run `devcontainer build <wsl path>`. You can get the `<wsl path>` value by running `wslpath -w <project folder>` inside WSL to get a `\\wsl$\...` path. This should build the dev container image
3. Run `devcontainer open <wsl path>`. This should open VS Code directly into the Remote-Containers extension
4. Close VS Code

**Comment by joyceerhl** [comment]
I had to use `devcontainer-insiders` instead of `devcontainer` in my shell, and I didn't have Docker installed so I added that to the setup instructions. Other than that, everything worked as described in the provided steps.
