### ISSUE TITLE
Not compatible with vs code 1.57.1

### ISSUE THREAD

**Issue by hartness** [microsoft/vscode-remote-release#5374]
No way of finding out what its compatible with

**Comment by chrmarti** [comment]
0.183.0 is the last version of Remote-Containers working with VS Code 1.57.1.

The release notes for remote development for VS Code 1.57 contain the corresponding Remote-Containers version in the `Containers` section title: https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_57.md. Similarly for other VS Code versions.
