### ISSUE TITLE
Remote container using ssh docker host cannot download vscode server behind corporate proxy

### ISSUE THREAD

**Issue by leifwalsh** [microsoft/vscode-remote-release#5375]
I believe this was previously reported in #3157, which I think was kind of incorrectly marked as a duplicate of microsoft/vscode#12588, and locked. I guess it's kind of a duplicate in that it's related, but resolving that wouldn't fix the behavior bug here, by itself, necessarily. 

I observed this on vscode insiders. 

- VSCode Version: 1.59.0-insider (user setup)
- Local OS Version: Windows_NT x64 10.0.18363
- Remote OS Version: Debian GNU/Linux 9.13 (stretch)
- Remote Extension/Connection Type: Docker (with `DOCKER_HOST` set to `ssh://a-linux-machine`)
- Logs:

Steps to Reproduce:

1. Install Remote Containers extension and docker CLI on windows, set `DOCKER_HOST` environment variable to `ssh://linux-domain-name`
2. Create a local folder with a devcontainer spec that will open the folder in any devcontainer (I chose the `node` image arbitrarily). 
3. Run Rebuild Container. 

The remote extension will run some docker commands to try to start the remote container, it will start one and pull the image, but then when it tries to fetch the vscode-server tarball, it fails with HTTP 407 because it cannot authenticate to our proxy to reach the internet. 

I haven't been able to figure out where it's making this request from, or how it has determined that the request should go through the proxy, actually, but it tries and then fails to authenticate. On the windows side, we have a Proxy Auto-Config set up, and the windows vscode process is able to use this to reach through the proxy (and it does authentication correctly), on the Linux side, I can't determine why it's choosing to go through the proxy. We tried tcpdumping and stracing everything inside the container and can't see any requests that look like this. I also tried running code-insiders on windows with `--log-net-log` and I don't see any requests that look like this. 

Whatever is happening, it results in a final log entry that looks like this:

```
Installing VS Code Server for commit abcd123
Start: Downloading VS Code Server
abcd123 x64 insider
Failed to download VS Code Server (https://update.code.visualstudio.com/commit:abcd123/server-linux-x64/insider): HTTP 407 - Proxy Authentication Required
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by leifwalsh** [comment]
We currently use Remote SSH and it works well (with Allow Local Server Download, to download the server on the windows side where PAC and proxy authentication work well, and copy it to the remote with scp). I wonder if it would be possible to create an analogous mechanism for Remote Containers, where the client on windows could fetch the server component and copy it into the container?

**Comment by chrmarti** [comment]
Remote-SSH is using VS Code's '_workbench.downloadResource' command to download using the Chromium network stack which better supports proxies than the proxy support we have when an extension uses Node.js' `https` module.

**Comment by leifwalsh** [comment]
Should I interpret that to mean that the 407 is likely coming from the Remote Containers extension on the Windows side? And further, that #3157 and this ticket really would be trivially fixed by microsoft/vscode#12588? 

In that case I'd be fine closing this, unless it's helpful for you all to have a tracking ticket about using the Chromium network layer specifically in Remote Containers.

**Comment by chrmarti** [comment]
Let's track using VS Code's '_workbench.downloadResource' command here. That might be the easiest of the available options to fix this.

**Comment by leifwalsh** [comment]
Great, thanks!

**Comment by gosuwachu** [comment]
I am also affected by this issue. I use Remote SSH to connect to my dev box, and then Remote Containers to open folder in a container, but that last step fails because vs code is not using my http proxy to download vs code server.

Are there any workarounds to get this to work?

**Comment by chrmarti** [comment]
Fixed as https://github.com/microsoft/vscode-remote-release/issues/5928. Will be in the next pre-release version of Remote-Containers.
