### ISSUE TITLE
Cannot connect from MacOS 10.13

### ISSUE THREAD

**Issue by yorkshirelandscape** [microsoft/vscode-remote-release#5376]
Issue Type: <b>Bug</b>

I am trying to use my old Macbook Air running MacOS 10.13 High Sierra to do some development and was pleased to see that it was supported. I'd like to use the Remote SSH extension, which is terrific, but it doesn't seem to be working. When I try to add a host, it gets as far as asking me where my config files are, but after I select one, nothing happens. The command palette closes and... nothing. I'm connecting to a Debian Buster machine that I have no trouble ssh'ing into through Terminal.app. Any thoughts?

Also, I love this new multi-platform, open-source, GitHub-using Microsoft. Keep up the good work!

Extension version: 0.65.7
VS Code version: Code 1.58.2 (Universal) (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 17.7.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2557M CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 7, 9|
|Memory (System)|4.00GB (0.03GB free)|
|Process Argv|-psn_0_4264977|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306cf:30341832
bridge0708:30335490

```

</details>

**Comment by bamurtaugh** [comment]
Thanks for reporting and for your kind words! Are you able to share any logs or additional info to help us diagnose further? https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues

**Comment by yorkshirelandscape** [comment]
Actually, I'm not sure what's changed, but it's working now. Thanks anyway for getting back to me.
