### ISSUE TITLE
Hyperlink to open a ssh connection to a host

### ISSUE THREAD

**Issue by moduleon** [microsoft/vscode-remote-release#5377]
Hi,

Is that possible to create a hyperlink to open a ssh connection to a host?
Something like: 
`vscode://ms-vscode-remote.remote-ssh/open?host=user@x.x.x.x`

Thank you

**Comment by bersbersbers** [comment]
That would be `vscode://vscode-remote/ssh-remote+user@host/home/user`.

Be aware of https://github.com/microsoft/vscode/issues/128309, though, so try to put the `user@` part into your SSH config.

**Comment by moduleon** [comment]
Thank you so much @bersbersbers, you rock 😁

**Comment by bamurtaugh** [comment]
Thanks for jumping in here, @bersbersbers 😄

**Comment by moduleon** [comment]
Hi @bersbersbers, it's me again :) would you know how to force vscode to open a new window instead of using the ones already opened?

**Comment by bersbersbers** [comment]
Using a hyperlink? Not sure.

At the CLI, use `-n`, see https://code.visualstudio.com/docs/editor/command-line
