### ISSUE TITLE
Rebuild Without Cache and Reopen in Container command is not shown in recovery container

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-release#5384]
Testing #5372

May be this is expected but as from the instructions I do not see `Rebuild Without Cache and Reopen in Container` command in recovery container

![image](https://user-images.githubusercontent.com/10746682/127137892-f0abeda4-167a-45ee-8041-0592c76be220.png)

**Comment by chrmarti** [comment]
Imprecise test instructions. Does this one work as expected?

**Comment by sandy081** [comment]
You mean which one?

**Comment by chrmarti** [comment]
The “Without Cache” one should rerun all of the Dockerfile.

**Comment by sandy081** [comment]
Yeah it does work as expected.
