### ISSUE TITLE
Ability to docker-commit a devcontainer

### ISSUE THREAD

**Issue by MitchK** [microsoft/vscode-remote-release#5387]
We are working on a large software project inside of a Git mono repo where a complete build of the (Node.js) application takes around ~30min. Switching feature branches therefore take a long time.

It seems like `vscode-dev-containers` could solve our problem, by being able to commit/cache a workspace locally in some form or shape before switching Git branches and restore it after switching a commit.

My first thought was using `docker commit` to commit a workspace and restore it later. However, there are two problems we don't have a solution to:
- Build artifacts and dependencies are stored inside of the workspace. The workspace is being mount to the container and therefore would not be committed when running `docker commit`
  - Perhaps we could point `node_modules` to a different location inside of the container using `export NODE_PATH=...`. But I'm not sure if that would work within a `lerna` mono repo with many `node_modules` folders
- How would we restore an a committed container in VSCode? It seems like the image reference is configured statically in the configuration.

**Comment by chrmarti** [comment]
You can control the workspace mount with the `"workspaceMount"` property. The difficulty is that you might still want to have your source changes persisted (locally or in a Docker volume) across container rebuilds.

**Comment by PavelSosin-320** [comment]
@chrmarti The problem will be .git metadata necessary to manage your sources. If the .git metadata is "frozen" inside the docker image created by the docker commit then next time when devcontainer will be recreated from the image will be certainly out-of-sync with the workspace state.  If managed source code and dev tools have to be synchronized using git hooks (shell scripts ) to trigger tools rebuild is a more feasible option. I am almost sure that it is achievable.

**Comment by PavelSosin-320** [comment]
Nothing can replace the server-side git delta storage. The local git folder structure is very static - it is frozen during git init. 
Storage big portions of data inside OCI image means fat image and huge image layer - this is the way to the performance hell when docker creates container OverlayFS folders from the layer's tars. Big project means intensive git usage for dev integration. So it can be very easy to add automatic devcontainer rebuild upon checkout (post-checkout) or rebase (pre-rebase) hooks - The current folder is always set to the project root.

**Comment by chrmarti** [comment]
Since you would end up having multiple clones of the same Git repo in the proposed Docker commits, you could instead just check out the same repository multiple times in different folders and then switch between folders to switch between branches.

Unless you are on Linux, using a Docker volume (`F1` > `Remote-Containers: Clone Repository in Container Volume`) might improve filesystem performance.
