### ISSUE TITLE
Failed to connect to remote server

### ISSUE THREAD

**Issue by Chao86** [microsoft/vscode-remote-release#5398]
After configing my server as follow:
![image](https://user-images.githubusercontent.com/44365146/127614776-cc72172a-ac8a-4791-a352-b65ef950bfd9.png)
I started to connect to remote server, however, it failed.
![image](https://user-images.githubusercontent.com/44365146/127615000-f7c3a70d-b518-4196-9991-f16c49e4a362.png)
How to solve this issue?

**Comment by bamurtaugh** [comment]
cc @roblourens Based on `Running the contributed command: '_workbench.downloadResource' failed`, does this sound like https://github.com/microsoft/vscode-remote-release/issues/4743 / https://github.com/microsoft/vscode/issues/128492?

**Comment by roblourens** [comment]
@Chao86 Could you start VS Code with --log-net-log=netlog.json, retry to connect to the SSH remote and then post the created netlog.json here?

**Comment by tanhakabir** [comment]
Closing this issue for now due to inactivity! @Chao86 please let us know if you're still facing this issue
