### ISSUE TITLE
Support Alpine

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode-remote-release#54]
Issue Type: <b>Bug</b>

Please add support for alpine images

Extension version: 0.12.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:21:48.884Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Ilhicas** [comment]
This would be highly appreciated.

![image](https://user-images.githubusercontent.com/14908129/57135066-15d53500-6da0-11e9-907f-32784596a50a.png)

**Comment by lnikell** [comment]
if that's possible to solve by installing some libraries inside the container, let us know, please.

**Comment by egamma** [comment]
@lnikell 

>if that's possible to solve by installing some libraries inside the container, let us know, please.

It is not possible to fix this by installing additional libraries, sorry.

**Comment by MarkKoester** [comment]
Does anyone know what the current plans are for supporting Alpine? Is this something that's currently being worked on? Is there a timeline for when support is expected?

**Comment by b01** [comment]
Is it possible to get an explanation of why this extension does not work with Alpine?

**Comment by Chuxel** [comment]
@b01 In short: Alpine is musl based instead of glibc, which means that there's work to do to ensure native components work properly. It's the same problem as #423.

**Comment by chrmarti** [comment]
Available in 0.63.0 of the Remote Containers extension. This currently needs the latest Insiders build: https://code.visualstudio.com/insiders/

**Comment by chrmarti** [comment]
Note that for now Alpine support will only be available with VS Code Insiders (https://code.visualstudio.com/insiders/) and not in the upcoming VS Code 1.36.

We keep this back so extension authors have time to adapt to the additional platform. Many extensions will not need any adoption, but some have native OS dependencies and will require updates and testing.

**Comment by bm-stschneider** [comment]
Already enjoying the alpine support in the insiders version.

**Comment by coderafei** [comment]
can not run
Server did not start successfully. Full server log >>>
> /home/afei/.vscode-server-insiders/bin/0f3794b38477eea13fb47fbe15a42798e6129338/server.sh: line 12: /home/afei/.vscode-server-insiders/bin/0f3794b38477eea13fb47fbe15a42798e6129338/node: not found
> <<< End of server log
