### ISSUE TITLE
Remote WSL - unable to connect with WSL when opening VSCode in the root of project

### ISSUE THREAD

**Issue by jamborski-dev** [microsoft/vscode-remote-release#5401]
I am writing a React app. It was all fine until out of the blue the remote stopped being able to connect to the WSL when opening VSCode by `code .` and getting error popup with 'Cannot reconnect. Please reload the window.'  and 'Reload Window' & 'Cancel' options. It has happened shortly after `npm install sass` package. Uninstalling didn't do much. Also it seems like it disconnects only from the root of this particular project. If I go up the directory and execute `code .` it works perfectly fine. Tried to disable all extensions apart of Remote WSL, but still the same effect. Reinstalled the Remote WSL extension, also no luck. 

Extension in version 0.58.2

VSCode: 
Version: 1.58.2 (user setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.22000

WSL:
OS: Ubuntu 20.04 focal
Kernel: x86_64 Linux 4.19.128-microsoft-standard

**Comment by bamurtaugh** [comment]
Do you have any sort of WSL output logs? https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues

**Comment by bamurtaugh** [comment]
If you're still experiencing this/have any additional logs, please let us know, and I'd be happy to reopen and discuss further. Thank you!
