### ISSUE TITLE
SSH connection bug, maybe?

### ISSUE THREAD

**Issue by coder-lg** [microsoft/vscode-remote-release#5404]
Does this issue occur when all extensions are disabled?: No
(I use extensions)

- VS Code Version: 1.58(latest)
- OS Version: Windows 7 Build 7601

Steps to Reproduce:

1. Get the Remote-SSH extension
2. Try connecting to a computer
3. Instead of asking password of server PC, it asks password of client PC

Let me explain:
I got OpenSSH Server on my secondary Win10 PC so that I may use WSL directly from my primary Win7 PC via VSCode.
Whenever I try to open up the Remote SSH window for connecting to my Win10 PC, it has to ask the password of the Win10 PC, not the Win7 one. Like, see it like this:
Win10 SSH line= ssh UserWin10@Win10PC
Win7 SSH line= ssh UserWin7@Win7PC
Whenever I try putting the password for UserWin10, it asks for the password of UserWin7, when UserWin7 by default doesn't HAVE a password. How can I fix this?

**Comment by coder-lg** [comment]
> I don't quite understand the situation... you are trying to use SSH through WSL on the Win7 PC, connecting to the Win10 PC, but it "it asks for the password of UserWin7, when UserWin7 by default doesn't HAVE a password"
> 
> Can you share the log from the Remote-SSH output channel? 

Not through WSL, through VSCode

**Comment by coder-lg** [comment]
The **reason** I got SSH on my other computer was:
- WSL(Debian, Ubuntu)
- Access to files for programming/testing apps
But now it doesn't ask the other PC's(WIn 10) password, it asks for the Win 7 PC I use when the current computer(Win 7) doesn't have the password.

**Comment by coder-lg** [comment]
Like this:
![VSCode Error](https://user-images.githubusercontent.com/76845820/127959278-78b3741d-9253-4c89-ad63-5cb2e7715940.png)
I am always like `???`. Can you find a fix for this, because VSCode has port forwarding, which is the main reason I need Remote-SSH to word.

**Comment by coder-lg** [comment]
Moreover, the output is blocked immediately.

**Comment by coder-lg** [comment]
Managed to get the output. Here it is. I removed some thngs like user name, host name for privacy
```output
[time] Log Level: 2
[time] remote-ssh@0.65.7
[time] win32 x64
[time] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2247616e6573684a227d", attempt 1
[time] "remote.SSH.useLocalServer": false
[time] "remote.SSH.showLoginTerminal": false
[time] "remote.SSH.remotePlatform": {"Win10PC":"windows"}
[time] "remote.SSH.path": undefined
[time] "remote.SSH.configFile": undefined
[time] "remote.SSH.useFlock": true
[time] "remote.SSH.lockfilesInTmp": false
[time] "remote.SSH.localServerDownload": auto
[time] "remote.SSH.remoteServerListenOnSocket": false
[time] "remote.SSH.showLoginTerminal": false
[time] "remote.SSH.defaultExtensions": []
[time] "remote.SSH.loglevel": 2
[time] SSH Resolver called for host: Win10PC
[time] Setting up SSH remote "Win10PC"
[time] Using commit id "c3f126316369cd610563c75b1b1725e0679adfb3" and quality "stable" for server
[time] Install and start server if needed
[time] Checking ssh with "ssh -V"
[time] Got error from ssh: spawn ssh ENOENT
[time] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[time] Got error from ssh: spawn C:\Windows\System32\OpenSSH\ssh.exe ENOENT
[time] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[time] > OpenSSH_8.5p1, OpenSSL 1.1.1k  25 Mar 2021

[time] Remote command length: 5993/8192 characters
[time] Running script with connection command: "C:\Program Files\Git\usr\bin\ssh.exe" -T -D 57360 "Win10PC" powershell
[time] Terminal shell path: C:\Windows\System32\cmd.exe
[time] > 
[time] Got some output, clearing connection timeout
[time] > UserWin7@Win10PC's password:
[time] Showing password prompt
[time] Password dialog canceled
[time] "install" terminal command canceled
[time] Resolver error: Error: Connecting was canceled
	at Function.Canceled (c:\Users\UserWin7\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64855)
	at c:\Users\UserWin7\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:414488
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
[time] ------
```
The entire output without the time, hostname, and username of the computers.

**Comment by coder-lg** [comment]
This started happening from last week.

**Comment by Gsonovb** [comment]
I have the same problem

**Comment by coder-lg** [comment]
Hey @Gsonovb does it ask for client PC password or server PC password?

**Comment by roblourens** [comment]
@coder-lg the log shows that it's using git SSH, not windows ssh, which is not on the path. That might mean that it isn't using the ssh config file you expect.

```
[time] Checking ssh with "ssh -V"
[time] Got error from ssh: spawn ssh ENOENT
[time] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[time] Got error from ssh: spawn C:\Windows\System32\OpenSSH\ssh.exe ENOENT
```

Are you sure ssh is installed on windows here?

**Comment by coder-lg** [comment]
I haven't installed SSH on the Winu PC because I use PuTTY and Git Bash mainly for SSH CLI connection. How can I do it for Windows 7 PCs?

**Comment by coder-lg** [comment]
I simply give it like so: 
```
SSH UserWin10@Win10PCHostName
```
And get connected via PuTTY, Got Bash or MobaXTerm

**Comment by Gsonovb** [comment]
> Hey @Gsonovb does it ask for client PC password or server PC password?

No, I configured a private key to log in.
Use ` SSH dev@VSpreview ` Command can log in

**Comment by coder-lg** [comment]
wdym?

**Comment by roblourens** [comment]
Not sure why ssh is on the PATH in your terminal but not vscode's PATH. You can either:

- Move your ssh config to git's ssh config file
- Or include the username when connecting in vscode. When the remote host picker pops up, enter `UserWin10@Win10PCHostName`

**Comment by coder-lg** [comment]
> Not sure why ssh is on the PATH in your terminal but not vscode's PATH. You can either:
> 
> - Move your ssh config to git's ssh config file
> - Or include the username when connecting in vscode. When the remote host picker pops up, enter `UserWin10@Win10PCHostName`

What do you mean? Can you include a step-by-step guide, please?

**Comment by roblourens** [comment]
1. Find git's ssh config file on your machine. This might be `c:\Program Files\Git\etc\ssh\ssh_config` or it might be somewhere else. You could put your ssh config there.
2. Or:

- Run the command "Connect to Host"
- In the popup, enter `UserWin10@Win10PCHostName`

**Comment by coder-lg** [comment]
Will try it soon. Thanks!

**Comment by coder-lg** [comment]
@roblourens, it WORKED! Thanks for the idea!!!
