### ISSUE TITLE
vscode remote ssh insiders recently stopped working with remote.downloadExtensionsLocally

### ISSUE THREAD

**Issue by leifwalsh** [microsoft/vscode-remote-release#5407]
- Version: 1.59.0-insider (user setup)
- Commit: 104bc571e956e4af623905ef10dfcc8f0fdac625
- Date: 2021-07-30T13:25:42.497Z
- Electron: 13.1.7
- Chrome: 91.0.4472.124
- Node.js: 14.16.0
- V8: 9.1.269.36-electron.0
- OS: Windows_NT x64 10.0.18363
- Remote Extension/Connection Type: SSH
- Logs: (from `Log (Window)`)

```
[2021-08-03 11:40:22.803] [renderer1] [error] ["Error: connect ETIMEDOUT 13.107.42.18:443","    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)"]
[2021-08-03 11:40:23.028] [renderer1] [error] connect ETIMEDOUT 13.107.42.18:443: Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```

Steps to Reproduce:

1. Install latest VS Code Insiders with the Remote - SSH (Nightly) extension, and connect to another machine that is firewalled from the internet.
2. Configure `"remote.downloadExtensionsLocally": true`.
2. Attempt to install an extension that should be installed remotely (e.g. `ms-python.python`)

It will eventually time out with the logs above. 

Using the stable build of VS Code and the Remote - SSH extension doesn't have this problem, and the insiders channel was fine until a few days ago.

Installing extensions that install locally works fine, only extensions that want to be installed remotely fail.

I'm confused why the `connect ETIMEDOUT` error is showing up in `Log (Window)`, since I assume that relates to things that happen locally, while this connection failure seems like it's happening on the remote side, and I see no failed network connections in the Developer Tools network pane.

It seems like this is somehow related to the changes around having extensions use the Chromium network stack, but it seems like it also could be a regression in paying attention to the `remote.downloadExtensionsLocally` setting?

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by leifwalsh** [comment]
If I configure (in remote scope) `http.proxy` to `http://localhost:3128` it fails differently (connection refused), but if I also forward that port from the windows side, suddenly everything works. So I think this is equivalent to #3987 except I'm hitting it when downloading extensions "locally" and in #3987 it's happening when downloading the VS Code server.

**Comment by chrmarti** [comment]
@leifwalsh Could you start VS Code with `--log-net-log=netlog.json`, retry connecting with Remote-SSH and then post the created netlog.json here?

Same: #5398 and #5360.

**Comment by leifwalsh** [comment]
I think my initial analysis of the situation was wrong. I think the extensions (python, pylance, jupyter) are all being downloaded locally and copied to the remote side as expected, but then one of those extensions is trying to access the network again during its install process and that's what's being blocked, likely because that extension isn't using `_workbench.downloadResource`.

I've tried three configurations. In each case, I made sure the python/pylance/jupyter extensions were uninstalled, made sure the proxy settings were configured as below before starting code-insiders, and then turned on the Developer Tools and turned on Disable Cache before trying to install the extension.

We have a corporate proxy that responds with HTTP 407 to challenge clients to do SPNEGO Proxy-Authorization to reach the outside network. We also have a local process you can run that forwards external network requests to that proxy, but provides responses to that auth challenge on behalf of clients.

1. With no proxy settings, I see the extensions get downloaded in the Developer Tools, but then installation fails and I get the following logs in Log (Window) output:

```
[2021-08-09 22:07:10.682] [renderer1] [error] ["Error: connect ETIMEDOUT 13.107.42.18:443","    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)"]
[2021-08-09 22:07:10.718] [renderer1] [error] connect ETIMEDOUT 13.107.42.18:443: Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```

This is what leads me to believe it's something in the extension installation process, not the extension download, that's failing.

2. With `http.proxy` set to point directly at our corporate proxy (that does 407 as above), installation succeeds! So I think whatever installation step is running does know how to do SPNEGO.

3. With `http.proxy` pointed at our local proxy process that doesn't require the client to do 407, installation also succeeds now. I think something in my environment must have required the port forward before, and I'm not sure what.

So I think this is just a case of whatever that extension is connecting to at install time needing to be pointed at a proxy because it isn't using `_workbench.downloadResource`.

I have `--log-net-log` output from each of the three runs above, which I can ask for permission to upload if you think you need it. But after the above analysis I'm pretty confident it's just that problem and hopefully you won't need them.

**Comment by leifwalsh** [comment]
(Latest tests done with this version:)

Version: 1.60.0-insider (user setup)
Commit: 1ee61f368ee0570feeb220605578a8768d99e762
Date: 2021-08-09T06:11:00.971Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by leifwalsh** [comment]
Oh, here's one other datapoint (which maybe I should report to the python extension): it fails to download the IntelliCode model under scenarios 1 and 2, but succeeds with 3, so whatever it's using to download that model probably doesn't know how to handle Proxy-Authorization challenges.

This one's a little harder to reproduce because I think it only downloads a fresh IntelliCode model after extension upgrades?

**Comment by chrmarti** [comment]
@sandy081 I see two issues when installing extensions with the server startup:
1) There is no way to tell the server what the `http` user settings are (that I'm aware of) when passing `--use-host-proxy`.
2) Without `--use-host-proxy` I'd expect the machine `http` settings to be used, but that does not seem to be the case.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/130962
