### ISSUE TITLE
RemoteSSH forces insecure practices on Windows 10 Pro

### ISSUE THREAD

**Issue by SomervilleTom** [microsoft/vscode-remote-release#5408]
RemoteSSH/VisualStudioCode forces me to keep a copy of my private SSH key in the standard filesystem location -- a location that is therefore known to every black-hat who might attempt to penetrate my system. This is an abysmal practice, and exemplifies why most security professionals that I work with abhor Microsoft.

I'm using Remote - SSH v0.65.4. I do remote development on several remote Linux machines. I use a single ed25519 keypair with a single private key that I keep on my Windows 10 Pro system. I am the only user. I practice key rotation, and I keep this keypair in a location on my C: that I maintain. I have multiple other apps on this system that use this file location with no problem.

So far as I can tell, OpenSSH (on Windows) refuses to use the private key at that location that I maintain because it claims that the permissions are too loose.  In order to use the RemoteSSH extension, I therefore have to either place a copy of my private key in a location that any intruder knows or -- even worse -- generate a key-pair specific to VSC/RemoteSSH.

This is a terrible practice that should be corrected.

**Comment by roblourens** [comment]
OpenSSH on windows does check the permissions on keys, there is a guide here about how to set them up correctly: https://github.com/PowerShell/Win32-OpenSSH/wiki/Security-protection-of-various-files-in-Win32-OpenSSH#authorized_keys

**Comment by SomervilleTom** [comment]
I fear you miss the point.

In the link you cite, please note that all the directories cited are subdirectories of C:\\Users. The links you provide offer no guidance (I think because it isn't possible!) for how to set the permissions of an arbitrary C: subdirectory so that OpenSSH will accept them.

**Comment by roblourens** [comment]
I don't understand why those steps wouldn't work for an arbitrary location. But if ssh is complaining about them, you can file an issue on windows' ssh here: https://github.com/PowerShell/Win32-OpenSSH/issues. vscode/this extension doesn't put any special requirement on keys, we just invoke ssh.

**Comment by SomervilleTom** [comment]
I understand that you're doing the best you can. Please try to hear me as someone from outside the Microsoft landscape. I use VSC and and RemoteSSH because it is currently the best toolset for my work. I am not and do not want to become familiar with ANY Microsoft internals. I want tools that just work. I'm continuing this exchange as one senior developer sharing information with another senior developer about an issue I'm having with your toolchain.

So far as I can discern, it is at least difficult for mere mortals to apply the necessary permissions to an arbitrary directory on the C: drive so that OpenSSH will accept them. I have already looked at the Windows Explorer options (from the property menu), they are of no help. I have already done various web searches to find an answer, they were not helpful.

The point I'm trying to pass along is that when when Remote SSH just invokes openSSH normally, that decision creates this vulnerability for every Windows10 user who follows accepted key management practices. That's your decision, not mine. I've informed you of the issue. In my view, it is YOUR job -- not mine -- to coordinate with Microsoft resources so that your tool works properly.

In a reasonable environment like Linux or Unix, this process is simple and straightforward -- apply `chmod` and `chown` commands to a suitable `.ssh` subdirectory and the task is done. So far as I can tell, the Microsoft counterpart involves an incomprehensible mess of Microsoft-specific names, tools, jargon, and commands.

I hope that you're able and willing to do whatever has to be done in inside the MS world to make this easier and I appreciate the attention you've already given this.

**Comment by roblourens** [comment]
I appreciate the feedback and your patience, but I don't have enough info to take this forward or even fully understand the issue. The link I gave has advice on using `icacls` to manage permissions on files and says

> private keys need to be owned by the user and no other user should have access to user's key files.

It seems like you have interpreted this to say that the key has to be in a certain folder, but I don't think that is true, provided you set the permissions of that other folder correctly. 

I think the best way forward would be for you to open an issue on the repo linked above and tell them exactly what the error message says and exactly which commands you tried to run to set the permissions correctly, and they are qualified to tell you what you need to do or decide whether the error message is in error.
