### ISSUE TITLE
Remote ssh environment and path control 

### ISSUE THREAD

**Issue by yassinm** [microsoft/vscode-remote-release#5409]
I am trying to use vscode in remote ssh mode for golang development. This is not specific to golang per say but affects all remote ssh development when one wants more control on what binaries are put in the path. From what i can tell there is no way i can set environment variables on the remote instance in a controlled way right now.

I think now it assumes remote ssh is based on your bashrc/bash_profile to set your environment. But since i am using the remove development for multiple projects i am not able to set my environment variables correctly. This for example affects what compilers/debuggers and runtimes you can have in your path.

This feature request is to make a way i can force vscode to use specific environment settings ? Something like the .vscode launch configuration but for remote ssh where you can specify what environment variables to use. is this something in the works already since i could not find something similar so far ?

**Comment by roblourens** [comment]
Do you want the environment variables in terminals? Or in the remote EH? What is your workflow in local windows?

**Comment by yassinm** [comment]
@roblourens in the remote EH for now. There is no way i can set what environment vscode will see. From the terminal i can figure what to do.

**Comment by roblourens** [comment]
We don't support something like that. The closest you can get right now is using SendEnv in your ssh config, or changing your bashrc (neither of these are really sufficient though).

Covered in some issues like
https://github.com/microsoft/vscode-remote-release/issues/141
https://github.com/microsoft/vscode-remote-release/issues/1139
