### ISSUE TITLE
[Bug]: 'Add to devcontainer.json' should work inside the container

### ISSUE THREAD

**Issue by jaron-l** [microsoft/vscode-remote-release#5410]
- VSCode Version: 1.58.2
- Local OS Version: Windows 10 19043
- Remote OS Version: WSL Ubuntu 20.04
- Remote Extension/Connection Type: Docker
- Logs: I checked all logs as described [here](https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues) but no log entries were made when following the workflow inside a container.

When right-clicking an extension in the marketplace, you are presented with an option to 'Add to devcontainer.json' that will add an extension to that file to install it in the container. This only works when you are not already inside the container. Otherwise, when you click the button, nothing happens.

Steps to Reproduce:
1. Open folder with a devcontainer.json definition inside it.
2. Reopen the workspace inside the defined container
3. Browse to an extension in the marketplace
4. Right-click the extension
5. Click 'Add to devcontainer.json'

Expected result:
The extensions id should be added to the devcontainer.json file under the extensions tag.

Actual result:
Nothing happens

Does this issue occur when you try this locally?: No. The extension does get added correctly if you are not in the container
Does this issue occur when you try this locally and all extensions are disabled?: No (Though you need the remote extension for 'Add to devcontainer.json' to show up).

**Comment by chrmarti** [comment]
Could you append your devcontainer.json?

**Comment by jaron-l** [comment]
I was able to replicate this on several of the microsoft example devcontainers, so it really can be any of the defaults.

If it helps, here's the rust one:
```json
// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.191.0/containers/rust
{
	"name": "Rust",
	"build": {
		"dockerfile": "Dockerfile"
	},
	"runArgs": [
		"--cap-add=SYS_PTRACE",
		"--security-opt",
		"seccomp=unconfined"
	],

	// Set *default* container specific settings.json values on container create.
	"settings": {
		"lldb.executable": "/usr/bin/lldb",
		// VS Code don't watch files under ./target
		"files.watcherExclude": {
			"**/target/**": true
		},
		"rust-analyzer.checkOnSave.command": "clippy"
	},

	// Add the IDs of extensions you want installed when the container is created.
	"extensions": [
		"vadimcn.vscode-lldb",
		"mutantdino.resourcemonitor",
		"matklad.rust-analyzer",
		"tamasfe.even-better-toml",
		"serayuzgur.crates"
	],

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "rustc --version",

	// Comment out connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "vscode"
}
```

**Comment by chrmarti** [comment]
Reproduced when using a WSL folder.

**Comment by ryomo** [comment]
Same here.
The added extension was written to ` C:\home\{user}\workspace\{myproject}\.devcontainer\devcontainer.json`.

**Comment by Neutrino-Sunset** [comment]
Is there no way to vote for an issue to promote its visibility? This issue is a major ballache. If you've opened a repo url directly into a container then your files would live in a volume, in which case I'm not really sure how you would work around this.

**Comment by jaron-l** [comment]
@Neutrino-Sunset you can add the thumbs up 👍emoji on the original issue report. That's how I've always seen people do it

**Comment by chrmarti** [comment]
Fixed since. Thanks.
