### ISSUE TITLE
unable to see the remote - ssh extension icon in VS Code after installed it to connect to linux server

### ISSUE THREAD

**Issue by chandu999** [microsoft/vscode-remote-release#5411]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by bamurtaugh** [comment]
Please see the guidance here for reporting issues with sufficient info: https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues. Also, it looks like the info was still on the clip board and didn't get pasted into the issue here.

**Comment by tanhakabir** [comment]
Closing this issue for now due to inactivity! @chandu999 please let us know if you're still seeing this problem
