### ISSUE TITLE
Remote - Containers: .dockerignore does not seen to take place on ADD

### ISSUE THREAD

**Issue by GustavoFenilli** [microsoft/vscode-remote-release#5414]
- VSCode Version: 1.58.2
- Local OS Version: Windows_NT x64 10.0.19042
- Remote OS Kernel: 5.4.72-microsoft-standard-WSL2
- Remote OS Version: Alpine Linux 3.13.5
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Have this folder structure
![image](https://user-images.githubusercontent.com/14954720/128258440-e812c905-e547-4eca-9c0c-7686fc81f458.png)
2. Delete node_modules
3. Run The folder inside the container
4. It fails, does not create the node_modules inside host, nor inside the docker container.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
Do you expect the `node_modules` from `npm i --silent` in the `Dockerfile.dev` to show up in the dev container? That is hidden by the local folder mounted with:
```
volumes:
  - .:/app
```
inside the `docker-compose.yml`.

**Comment by GustavoFenilli** [comment]
the local folder mounted with `.:/app` should ignore if there is or not a node_modules on the host machine, so that the `npm i --silent` from` Dockerfile.dev` can create inside the dev container the folder correctly so it does mirror it.

The problem is that if there is a `node_modules` on the host, it works fine, npm installing packages inside the container mirror the host `node_modules` and so on.
But if there is not a `node_modules` on the host, it fails running the `npm run serve` because there is no node_modules inside the container that run `npm i --silent`, also even if I try to `npm i` inside the container manually after this, It gives errors regarding permissions.

**Comment by chrmarti** [comment]
`Dockerfile.dev` runs before the container is created and `/app` is mounted. You could instead add `"postCreateCommand": "npm i --silent"` to your `devcontainer.json`.

**Comment by GustavoFenilli** [comment]
I could do that, meaning that I would only make file copies inside the Dockerfile.dev correct? but doesn't that go agaist the idea of the building stage from docker?

**Comment by chrmarti** [comment]
The files you add in the Dockerfile.dev are actually all hidden by mounting the local folder. For deploying to production adding everything to the image makes sense, for the devcontainer you might want to keep the source on your local filesystem (or a Docker volume), so you can rebuild the container without loosing your changes to the source code.

**Comment by GustavoFenilli** [comment]
That makes sense, I will changing the devcontainer to apply those.
