### ISSUE TITLE
Support installing `devcontainer` CLI independently of Remote-Containers

### ISSUE THREAD

**Issue by stuartleeks** [microsoft/vscode-remote-release#5415]
To support building dev container images in CI builds, publish the `devcontainer` CLI so that it can be installed and run independently of the Remote-Containers extension.

(This would be a step towards supporting [this request](https://github.com/microsoft/vscode-remote-release/issues/4771#issuecomment-811855126))

**Comment by felipecrs** [comment]
This would be a very good feature for me, which have automated ways to setup the development environment of each of my team member. The devcontainer cli installation today is a pitfall, as it is fully manual.

Publishing as a npm package would be more than enough. :)

**Comment by chrmarti** [comment]
Available at https://github.com/microsoft/vscode-remote-release/packages/1019896.

**Comment by felipecrs** [comment]
Wow, this is very cool. But is there any major reason why not to publish it to npm.js instead? Many other vscode-related packages from Microsoft are being published there, and not being on NPM adds a burden to the installation process, as we have to set the repository and so.

**Comment by felipecrs** [comment]
Not only the standalone installation but also when other people would like to add this package to their devDependencies in package.json.

**Comment by felipecrs** [comment]
Also, if you actually publish to npm.js, I would suggest you to name the package as `devcontainer` only, so that `npx devcontainer build` would work out-of-the-box. Otherwise, if the package was named `devcontainer-cli`, it would need to be called as `npx -p devcontainer-cli devcontainer build`.

**Comment by chrmarti** [comment]
@felipecrs We are not sure how the community would feel about a non-OSS package on npmjs.org, so we decided to start with publishing it to the GitHub registry.

On naming: We have started using the `@vscode` scope, so it might be `npx @vscode/dev-container`. If you install the package, the executable is just `devcontainer` (or `devcontainer-insiders` when part of the extension in VS Code Insiders).

**Comment by chrmarti** [comment]
For the verifier: Check that you can install the package and run the CLI.
```
npm login --registry=https://npm.pkg.github.com
npm install --registry=https://npm.pkg.github.com/microsoft @microsoft/dev-container-cli
npx @microsoft/dev-container-cli
```

**Comment by stuartleeks** [comment]
> Also, if you actually publish to npm.js, I would suggest you to name the package as `devcontainer` only, so that `npx devcontainer build` would work out-of-the-box. Otherwise, if the package was named `devcontainer-cli`, it would need to be called as `npx -p devcontainer-cli devcontainer build`.

The `package.json` for the CLI has the [`bin` property](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#bin) set so that the command is set as `devcontainer` even though the package  is `dev-container-cli`

**Comment by felipecrs** [comment]
> The `package.json` for the CLI has the [`bin` property](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#bin) set so that the command is set as `devcontainer` even though the package is `dev-container-cli`

You are absolutely right. Sorry for my confusion.

It means that the package could even be submitted as something like `@vscode-remote/devcontainer-cli` or `@vscode-non-oss/devcontainer-cli` to npm.js to make it even more clear that they are not like the other vscode packages, which are OSS.

**Comment by chrmarti** [comment]
We have removed the package, looking into alternatives.

**Comment by felipecrs** [comment]
Is there any news?

**Comment by chrmarti** [comment]
Sorry, forgot to post an update: This is available on npmjs.com as https://www.npmjs.com/package/@vscode/dev-container-cli.

**Comment by felipecrs** [comment]
Amazing. Thanks a lot!

**Comment by felipecrs** [comment]
@chrmarti this package is missing the `open` command:

![image](https://user-images.githubusercontent.com/29582865/143718700-6b4261ac-26a5-464f-b3a1-bc15889e4eb1.png)

**Comment by chrmarti** [comment]
@felipecrs We don't have that (yet) because the association between the NPM package with one of your VS Code installations is less obvious (there could be several, e.g., stable and insiders). If this is of interest, could you file a feature request? Thanks!

**Comment by felipecrs** [comment]
I just did it. Thank you.

https://github.com/microsoft/vscode-remote-release/issues/5957
