### ISSUE TITLE
Can't open workspace via SSH 'cause of execution control

### ISSUE THREAD

**Issue by 0xdecade** [microsoft/vscode-remote-release#5417]
Issue Type: <b>Bug</b>

1. Open VSCode
2. Install ms-vscode-remote.remote-ssh
2. Add ssh connection
3. Open ssh connection
4. Add a folder to workspace
5. Save workspace
6. Close VS Code
7. Open VS Code
8. Open previously saved workspace
9. After credentials entered VS Code will be restarted without any warnign

Dirty workaroud: disable execution control e.g. pass --disable-workspace-trust argument to Code.exe

Suggestion:
You can notice that VS Code trying to ask about trust. So I think problem is in this feature of VS Code, but can't be sure.

I already used the "Extension bisect" feature from command pallete and this wasn't helpful too.

Extension version: 0.65.7
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-77-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.14GB free)|
|Process Argv|--crash-reporter-id db99fa0d-caf2-4098-a87d-9db3003dbae9|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: aStation|
|OS|Linux x64 5.4.0-77-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (4 x 2099)|
|Memory (System)|3.84GB (0.64GB free)|
|VM|7%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473

```

</details>

**Comment by bamurtaugh** [comment]
cc @sbatten for any thoughts on workspace trust mention above: "You can notice that VS Code trying to ask about trust. So I think problem is in this feature of VS Code, but can't be sure."

**Comment by sbatten** [comment]
I was not able to repro this issue. I am able to open save workspaces in ssh with or without trusting the workspace ahead of time.

**Comment by 0xdecade** [comment]
I confirm that. Problem is gone with 1.60. 2 vscode and  0.65.8 extension. Now modal window is visible and it allows to choose a variant. Thanks for the response.
