### ISSUE TITLE
Push images to a Docker Registry on successful build to be pulled by others

### ISSUE THREAD

**Issue by evgri243** [microsoft/vscode-remote-release#5423]
The Idea is to allow to specify both a container image and a dockerfile in the same .devcontainer definition with additional env-variable called ${.devcontainerContextHash}. Then the logic can be as follow:
1. The extension tries to pull an image with the specified DevContainer definition hash from the specified Docker Registry.
2. If available, it uses it as is to start the container.
3. If not, builds the container and pushes it to the registry to be used by others.

Example:
```json
{
  "build": {
	  "dockerfile": "Dockerfile",
	  "image": "cr.example.com/project-devcontainer:python-${.devcontainerContextHash}",
          "pushOnSuccess": true
  }
}
```

Motivation:
Image sizes are getting bigger and build time takes longer. Our current container with only a few required apt and pip packages has recently achieved 5GB in size spending about 30mins every time to rebuild. Docker Buildx improved the timing, but this logic can make it even better and save time not only for me but others.
Especially, this logic can prove beneficial for GitHub Codespaces improving timing for new-comers and other people exploring the repo.

Additionally, the same container image from the same container registry can be used with DevOps pipelines building a single image cycle, but that is up to DevOps engineers to design.

**Comment by Chuxel** [comment]
Thanks for the feature request!  There is a dev container CLI starting to form in the latest version of the Remote - Containers extension that has a build command which is targeted at this kind of scenario over time.  Having a first class experience for referencing an image and a Dockerfile as you suggest is also something @chrmarti and @bamurtaugh have wondered about.

//cc: @2percentsilk @jkeech @joshspicer @stuartleeks  who have also been talking about different aspects of this as a FYI

**Comment by stuartleeks** [comment]
In the 1.58 release, the [`cacheFrom` property](https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_58.md#devcontainerjson-support-for---cache-from) was added to `devcontainer.json` 

If you set this then Remote-Containers will include the value(s) you set as `--cache-from` options to the `docker build` command. If you're using BuildKit, I think you get the end result that you want for parts 1 & 2 of your suggestion.

I've used this in conjuction with building and pushing the image in a CI build (N.B. this assumes you are using BuildKit):
- CI builds and pushes to `myregistry/devcontainer`
- `cacheFrom` is set to `myregistry/devcontainer` in `devcontainer.json`
- The `cacheFrom` value is included in the `docker build` step, so it downloads the cache manifest from the registry (nice and small) and then uses that to determine which layers are a cache hit. These layers are automatically pulled by docker as needed

A nice feature of using `cacheFrom` is that for an image with 10 layers where the first 6 can be used but the final 4 are stale, only the 6 layers that satisfy the cache are pulled, compared to all 10 if you manually pull the image before building.
