### ISSUE TITLE
Ports protocol api for web not behaving as expected 

### ISSUE THREAD

**Issue by wachaudh** [microsoft/vscode-remote-release#5424]
The ports protocol context menu doesn't reflect the protocol assigned to the tunnel object. This happens in codespaces web on the latest versions of insiders and stable.

Repro steps for codespaces:

1. Update codespaces workbench to set the tunnel protocol as the context menu selection. Do this by adding `protocol: tunnelOptions.protocol` to the tunnel object [here](https://devdiv.visualstudio.com/OnlineServices/_git/vsclk-core?path=%2Fsrc%2FPortal%2FPortalWebsite%2FSrc%2FWebsite%2Fpackages%2Fvso-workbench%2Fsrc%2Fvscode%2Fproviders%2FtunnelProvider.ts&version=GCcd9bb41195cb918881a69261118cc72d5d2a73c7&line=50&lineEnd=50&lineStartColumn=1&lineEndColumn=45&lineStyle=plain&_a=contents).
2. Try to change the protocol through the context menu.  Confirm the protocol is correctly being assigned to the tunnel object by setting a breakpoint.

Current Behavior:

The protocol ui doesn't reflect the protocol assigned to the tunnel object.  

Expected Behavior:

The checkmark for selected protocol should reflect the protocol assigned to the tunnel object.

Making a similar change in the codespaces extension works as expected on the desktop versions of insiders and stable.

**Comment by alexr00** [comment]
@wachaudh is there a way I can repro this without trying to make changes to the Codespaces extension since I'm not setup to build that from source?

**Comment by wachaudh** [comment]
Discussed repro steps offline.

**Comment by alexr00** [comment]
I tried to repro, but everything is still working well and I see the expected behavior.

**Comment by klvnraju** [comment]
Thanks for looking into this Alex. I just validated that it works as expected.
