### ISSUE TITLE
[Win] Remote SSH to linux host shows only "install" terminal and "code" command not found

### ISSUE THREAD

**Issue by NiklasRosenstein** [microsoft/vscode-remote-release#5429]
> - VSCode Version: 1.59.0 (user setup)
> - Local OS Version: Windows 10
> - Remote OS Version: Debian 9.13
> - Remote Extension/Connection Type: SSH
> - Logs: [remote-ssh.log](https://github.com/microsoft/vscode-remote-release/files/6953059/remote-ssh.log)

__Description__

When I connect to my Linux host via Remote SSH, I observe the following behavior:

* Using `"remote.SSH.useLocalServer": true`:

  * (Neutral) A warning pops up about password prompts that may not be displayed and suggesting to turn off useLocalServert.
  * (Good) A terminal is instantly opened
  * (Bad) I cannot access `code` from this terminal or any other terminal (See screenshot (1))

* Using `"remote.SSH.useLocalServer": false`:

  * (Bad) No initial terminal free-to-use terminal is opened, but instead this "install" terminal stays open (See screenshot (2))
  * (Bad) I cannot access `code` from a new terminal that I create

__RemoteSSH Config__

```json
  "remote.SSH.showLoginTerminal": true,
  "remote.SSH.useLocalServer": false,  // or true, see above
  "remote.SSH.enableAgentForwarding": true,
```

__Workarounds__

* What seems to work is to remove the `-l` argument from the integrated terminal settings, but that does not initialize the shell with my `.profile`. I can then manually source it, and `code` is available after that (that means my `.profile` does not accidentally remove the path to the `code` binary from `PATH`)
* (Haven't done this yet, but it should work) I can read out the `VSCODE_GIT_ASKPASS_NODE` environment variable to construct to the path the `bin/` folder of the VSCode server installation manually in my `.profile`.

__Screenshots__ 

(1)

<img src="https://user-images.githubusercontent.com/1318438/128680983-21be041c-06e8-4f46-b9b5-f4ae6215ff0c.png" width="200px">

(2)

<img src="https://user-images.githubusercontent.com/1318438/128679510-a63a6e42-0b25-49bc-923b-a1f896fe775c.png" width="200px">

**Comment by NiklasRosenstein** [comment]
The workaround works 👍 

```sh
# Workaround for https://github.com/microsoft/vscode-remote-release/issues/5429
if ! command -v code >/dev/null && [ ! -z "$VSCODE_GIT_ASKPASS_NODE" ]; then
echo a
  export PATH=$PATH:"$(dirname "$VSCODE_GIT_ASKPASS_NODE")/bin"
fi
```

**Comment by roblourens** [comment]
Sorry, I don't understand what problem I am supposed to see in the screenshots. Can reopen if there is an issue here.

**Comment by roblourens** [comment]
What do you have for `terminal.integrated.inheritEnv`?
