### ISSUE TITLE
Loading bash profile into container

### ISSUE THREAD

**Issue by taiya** [microsoft/vscode-remote-release#5430]
Issue Type: <b>Feature Request</b>

Not really a bug, but rather a feature request for better documentation (as I assume this is a pretty common request).

Adapting some information from here to vscode https://github.com/moby/moby/issues/1861

`.devcontainer.json`:
```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.140.1/containers/python-3
{
  "name": "containername",
  
  // --- OPTION A: loads from pre-built container
  "image": "docker.io/username/containter:latest",
  
  // Which folders to mount
  "mounts": [   "source=${localEnv:HOME}/.bash_profile,target=/root/.bash_profile,type=bind,consistency=cached"
  ],

  // starts a login shell (i.e. loads /root/.bash_profile)
  "postAttachCommand": "/bin/bash -l",
}
```

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.25-linuxkit

**Comment by taiya** [comment]
@chrmarti right now when you start a container and execute bash therein, bash is **not** executed in login mode, so from what I understand the *.bash_profile* is not automatically sourced. I have a bunch of aliases defined in that file, and I want them to exist in my container.

I have also tried this, but with no luck :)
```
"postAttachCommand": "source ~/.bash_profile",
```

**Comment by chrmarti** [comment]
`"loginInteractiveShell"` should source `~/.bash_profile`, maybe you also have a `~/.profile` and that wins? (Not sure which takes precedence.)
