### ISSUE TITLE
changing settings in the remote scope for a devcontainer should save them to the `"settings"` section in `devcontainer.json`

### ISSUE THREAD

**Issue by DetachHead** [microsoft/vscode-remote-release#5431]
like how changing workspace settings outputs them to `.vscode/settings.json`

**Comment by chrmarti** [comment]
The devcontainer.json is meant for sharing with the team, not all settings changes might be meant for that.

**Comment by DetachHead** [comment]
@chrmarti isn't that also the case with `settings.json`? If you don't want to share settings you would change them in the user settings right?

**Comment by chrmarti** [comment]
User settings additionally apply to all remotes and workspace folders which might again not be what you want.
