### ISSUE TITLE
Downloading files

### ISSUE THREAD

**Issue by rctneil** [microsoft/vscode-remote-release#5436]
Hi,

I've connected to our server using this extension and SSH.

I can see a file listing in the VSCode sidebar. When I drag a file from the file list to my local Desktop, the file shows on my Desktop but it's an empty version of the file.  It's a file with the correct name but of 0kb in size.

I can right click the file in VSCODE and use the Download option and this works fine but dragging it out fails.

Any ideas how to resolve this?

Neil

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode/issues/128975
