### ISSUE TITLE
The code server website 500

### ISSUE THREAD

**Issue by StatLee** [microsoft/vscode-remote-release#545]
![image](https://user-images.githubusercontent.com/11553945/58757257-cc613c80-853b-11e9-96c3-8d0c62719e87.png)
https://update.code.visualstudio.com/commit:0284236851a94b116f468345f6e98688a737015d/server-linux-x64/insider: 2019-06-02 13:38:48 ERROR 500: Internal Server Error.

**Comment by kmehant** [comment]
This seems a serious problem @StatLee I have the same issue.
@Chuxel Please help!

**Comment by rajeeshdf** [comment]
I'm also seeing this same error

**Comment by StatLee** [comment]
> This seems a serious problem @StatLee I have the same issue.
> @Chuxel Please help!

Yes, it has affected the development machine initialization. :(

**Comment by StatLee** [comment]
> I'm also seeing this same error

I didn't find a way to install it manually.

**Comment by MagedMYoussef** [comment]
I'm also seeing the same issue this morning.

**Comment by levisonchen** [comment]
I got this 500 error too. :(

**Comment by DanielSchuech** [comment]
Got the same error 5 minutes ago but seems to be fixed now

**Comment by msalvaris** [comment]
Yep, all good now

**Comment by kmehant** [comment]
It works now! I think we can close this issue now @StatLee 
Fixed #545

**Comment by StatLee** [comment]
Ok,Thx.
