### ISSUE TITLE
new version will make remote ssh not work

### ISSUE THREAD

**Issue by jchalex** [microsoft/vscode-remote-release#5450]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by jchalex** [comment]
![image](https://user-images.githubusercontent.com/11224001/129302895-9f42c0e6-f1fe-438f-b81f-c853105a9b94.png)

![image](https://user-images.githubusercontent.com/11224001/129302945-d57002cc-8fd2-4223-92bf-6849357bca13.png)

![image](https://user-images.githubusercontent.com/11224001/129302970-17bfe69f-b09c-49ab-b122-8ec095b925c5.png)

**Comment by bamurtaugh** [comment]
Can you please post the full logs rather than a screenshot (https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues) and include some repro steps (i.e. what led to the logs/error)? Thanks!

**Comment by bamurtaugh** [comment]
If you're still experiencing and can provide the details mentioned above, that'd be great. Thank you!
