### ISSUE TITLE
Error while cloning repository with devcontainer config in remote container

### ISSUE THREAD

**Issue by sparkeplug** [microsoft/vscode-remote-release#5462]
![image](https://user-images.githubusercontent.com/10337388/129597715-83b51894-710f-4b75-8b56-cc9b20ebefc4.png)

- VSCode Version: 1.59.0
- Local OS Version: Windows NT x64 10.0.19043
- Reproduces in: Remote - Containers 
- Name of Dev Container Definition with Issue: Getting error when i clone a repository in a new remote container. ALPINE image.

Steps to Reproduce:

1. Added new configs for devcontainer. Selected ALPINE image.
2. Cloned a repository that contains the above config.
3. Getting errors as shown in screenshot

**Comment by chrmarti** [comment]
@sparkeplug You seem to be running with `<your-package-list-here>` which is meant to be replaced with your list of packages.

**Comment by sparkeplug** [comment]
Had this issues by directly cloning my repository inside an Alpine image without changing anything in DOCKERFILE. But somehow managed to add config files to the repo and it worked. As far as this issue is concerned, i cannot recreate it again with a different repo. Hence closing this issue.
