### ISSUE TITLE
Remote-SSH not properly sourcing /etc/profile with user shell set to zsh

### ISSUE THREAD

**Issue by thully** [microsoft/vscode-remote-release#5465]
When trying to connect with Remote-SSH using a user account with zsh as the default shell, it seems that the /etc/zprofile (and thus /etc/profile) are not being properly sourced. I noticed this because the umask used by the VSCode GUI and terminal is defaulting to that in /etc/login.defs instead of the value set in /etc/profile, resulting in unexpected permission problems. This does not happen when a user has bash as the default shell, but may happen with other shells (but has not been tested).

- VSCode Version: 1.59.0
- Local OS Version: Windows 10 Pro 19042.1165
- Remote OS Version: CentOS 8.4
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Set up a user on the remote OS with zsh as their default shell
2. Set up Remote-SSH using this user to log in.
3. Create files using the VS Code GUI and/or terminal

Result - file permissions use umask from /etc/login.defs, not /etc/profile as it does when I SSH in normally.

**Comment by zorrobiwan** [comment]
similar to #5567 ?

**Comment by roblourens** [comment]
We connect running `bash` on your remote, so `~/.bashrc` will be sourced. You can change that to source your zsh profile.
