### ISSUE TITLE
Mac OS: VSCode Remote Container fails to start after Docker update

### ISSUE THREAD

**Issue by notslow** [microsoft/vscode-remote-release#5483]
- VSCode Version: 1.59.1
- Local OS Version: 11.5.2 (20G95)
- Remote OS Version: Debian Buster (FROM rust:1.54 container)
- Remote Extension/Connection Type: Docker 
- Logs:

> `[2021-08-20T16:03:49.570Z] Remote-Containers 0.191.1 in VS Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa).`
> `[2021-08-20T16:03:49.570Z] Start: Resolving Remote`
> `[2021-08-20T16:03:49.572Z] Setting up container for folder or workspace: /Users/afast/code/redis-cidr`
> `[2021-08-20T16:03:49.572Z] Context: desktop-linux`
> `[2021-08-20T16:03:49.574Z] Start: Check Docker is running`
> `[2021-08-20T16:03:49.574Z] Start: Run: docker version --format ={{.Server.APIVersion}}`
> `[2021-08-20T16:03:49.575Z] Stop (1 ms): Run: docker version --format {{.Server.APIVersion}}`
> `[2021-08-20T16:03:49.575Z] spawn docker ENOENT`
> `[2021-08-20T16:03:49.575Z] Stop (1 ms): Check Docker is running`
> `[2021-08-20T16:03:49.577Z] Docker returned an error code ENOENT, message: spawn docker ENOENT`
> `[2021-08-20T16:03:49.579Z] Stop (5 ms): Run: docker version --format {{.Server.APIVersion}}`

Steps to Reproduce:

1. Open a new workspace
2. Add a local Dockerfile
3. Add devcontainer files
4. Reopen in container

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

I finally restarted my Mac to get the latest updates. Docker Desktop is now at v3.6.0 (67351). I tried restarting my local dev containers (both Debian) and both are erroring out with different errors.

Error 1: "Docker Version 17.12.0 or later required"
Error 2: "The 'docker' command was not found. Make sure Docker is installed."

> `➜ $ which docker`
> `/usr/local/bin/docker`

> `➜ $ docker -v`
> `Docker version 20.10.8, build 3967b7d`

VSCode Version:
Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:53:52.479Z (1 day ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.6.0

Docker Version:
v3.6.0(67351)
Engine: 20.10.8

Thanks!

**Comment by notslow** [comment]
Solved, https://github.com/microsoft/vscode-docker/issues/3161

Need to set the Docker path variable to the full path:  docker.DockerPath => /usr/local/bin/docker

**Comment by ttotal** [comment]
remote.containers.dockerPath => /usr/local/bin/docker
