### ISSUE TITLE
Live Share Does not work in Remote - Containers

### ISSUE THREAD

**Issue by DevDanM1** [microsoft/vscode-remote-release#5485]
Issue Type: <b>Bug</b>

Trying to share a Live Share link from VS Code when VS Code is attached to a Docker Container does not work.

Steps to reproduce:
1) Get a docker container running
2) Select "Attach VS Code"
3) Attempt to start a collaborative Live Share session and realize it won't work.

Extension version: 0.191.1
VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.68GB (54.52GB free)|
|Process Argv|--crash-reporter-id 952a0a5c-2407-4048-b899-24b805ae6ef9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30353136
vsdyn420:30354109

```

</details>

**Comment by chrmarti** [comment]
This appears to be an issue with the Live Share extension. Could you file an issue for that at https://github.com/MicrosoftDocs/live-share/issues? Thanks.
