### ISSUE TITLE
Remote-SSH failing on specific servers

### ISSUE THREAD

**Issue by albatros69** [microsoft/vscode-remote-release#5488]
- Version : 1.59.1 (Commit : 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa)
- Local OS Version: debian 11
- Remote OS Version: debian 11 or debian 10
- Remote Extension/Connection Type: SSH
- Logs: [logs.txt](https://github.com/microsoft/vscode-remote-release/files/7025983/logs.txt)

Steps to Reproduce:

1. Simply try to connect to specific servers and the ssh tunnels fail to be established

I have identified two servers I can't get a remote connection to from VS Code (there're maybe more, but I didn't identified them yet, meaning the other ones I tried worked). I try from the exact same client each time. All the servers are debian 10 or 11. The two failing servers are respectively debian 10.10 and debian 11, so the culprit doesn't seem to lie here.

I obviously checked the SSH configuration and they're exactly the same on the failing servers and the successful ones. The difference I see is that on successful ones, ssh process has been spawned on the servers to handle the tunnel. This is not the case on the failing ones.

I tried every hint I gathered here (disabling Dynamic ports and so on), but to no avail. And, since there's no message to give a clue, I'm quite puzzled...

**Comment by albatros69** [comment]
Hello,
I forgot to stress that I would be happy to follow any debug or troubleshooting procedures, or to test any possible hint to help pinpoint the culprit.
Thanks in advance,

**Comment by bamurtaugh** [comment]
Have you also tried the troubleshooting steps mentioned here: https://code.visualstudio.com/docs/remote/troubleshooting#_troubleshooting-hanging-or-failing-connections?

**Comment by albatros69** [comment]
I sure did, without any success unfortunately.

**Comment by roblourens** [comment]
Is it possible that tcp port forwarding is not allowed on your ssh server? There is an option for this in the ssh server config.

**Comment by roblourens** [comment]
All I can say is that ssh is telling us that forwarding the port failed. Maybe port forwarding is enabled but that port is blocked by a firewall? `39553`

**Comment by roblourens** [comment]
All I can say is that forwarding the port failed. If port forwarding is enabled, maybe that port on the server is blocked by a firewall?

`Failed to set up socket for dynamic port forward to remote port 45901: connect ECONNREFUSED 127.0.0.1:39553. Is the remote port correct?`

It's also possible that the server died after starting successfully, but I think that's less likely. But you could check it, the pid of the server is printed in the log.
