### ISSUE TITLE
VSCode to auto-detect 443 and 8443 ports as https

### ISSUE THREAD

**Issue by klvnraju** [microsoft/vscode-remote-release#5489]
Scenario:
- With the new protocol changes implemented
- Create a new server in a codespace say in port 443 (or 8443)
- Share the port

Expected:
VSCode calls tunnelFactory with `tunnelOptions.protocol` set to `https`

Actual:
Should send with `https` set

The reason why codespaces should not override:
- Let us say that codespaces overrides the tunnelOptions.protocol to https (if it sees port is 443 or 8443)
   - The scenario where customer creates a `http` server on 443 will automatically be set to https and would not work
   - And say customer tries overriding to `http` from context menu, codespaces extension will not know if the user explicitly did it or VSCode is sending it by default
 - Since VSCode has the source of truth (I guess VSCode stores http/https it in remote settings), it seems correct to implement to default the initial assumption of defaulting to `https` for 443 and 8443 ports.

cc @alexr00, please let us know if you need more information regarding the same.

**Comment by alexr00** [comment]
This seems reasonable. We can do this by modifying the default value of `remote.portsAttributes` to be the following:

```json
	"remote.portsAttributes": {
		"443": {
			"protocol": "https"
		},
		"8443": {
			"protocol": "https"
		}
	}
```

This give the users a clear view of why those ports default to `https` and allows them to override those values if they choose.

For users who already have `remote.portsAttributes` set in their user settings I can add a migration to insert these two ports so they don't miss out on this.
