### ISSUE TITLE
Infinite startup loop for npm project in VS Code Dev Containers

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-remote-release#5496]
- VSCode Version:
![image](https://user-images.githubusercontent.com/41597107/130523400-b6abd027-6852-4c79-b7a4-c8c90bc1b574.png)

- Local OS Version:
![image](https://user-images.githubusercontent.com/41597107/130523447-c58ccbc4-fc0e-4719-8e42-2a71761922fc.png)

- Reproduces in: <Codespaces | Remote - Containers | Both> Just remote containers - haven't tried CodeSpaces yet.

- Name of Dev Container Definition with Issue:
mcr.microsoft.com/vscode/devcontainers/typescript-node:0-14-buster

Steps to Reproduce:

1. `git clone https://github.com/Azure-Samples/js-e2e-static-web-app-with-cli`
2. `cd js-e2e-static-web-app-with-cli`
3. `npm install`
4. `npm run start-app`

In local VS Code, this correctly starts for dev runtimes for React and Functions. In the container, if falls into an infinite loop just continuing to spin up more dev runtimes - or at least that is what it looks like it is doing.

[start.log](https://github.com/microsoft/vscode-dev-containers/files/7035202/start.log)

**Comment by Chuxel** [comment]
Does this happen in WSL?  There's nothing that points to a remote containers problem here that I can see. More likely some sort of Linux incompatibility.

Looking at package.json, I think you've got a typo that may just happen to work on Windows.

```
    "start-api": "cd api & npm start",
    "start-app": "cd app & npm start",
```

Needs to be
```
    "start-api": "cd api && npm start",
    "start-app": "cd app && npm start",
```

`&` alone on macOS or Linux would put the `cd` into the background, immediately return and then run npm start, which would happen in the current directory and cause the behavior you see.

**Comment by diberry** [comment]
Good catch - thank you.

**Comment by Chuxel** [comment]
Closing as resolved - LMK if it ends up being something container related.
