### ISSUE TITLE
Prompt showed for security key user presence does not dismiss after complete

### ISSUE THREAD

**Issue by cmoog** [microsoft/vscode-remote-release#5497]
- VSCode Version:
1.59.1
- Local OS Version:
11.5.2
- Remote OS Version:
Ubuntu 20.04
- Remote Extension/Connection Type: SSH/Docker/WSL
SSH

Steps to Reproduce:

1. Connect to server with an authorized key of type `ecdsa-sk`. 
2. Touch the security key to establish user presence.
3. Confirm that the dialogue does not dismiss.

<img width="535" alt="Screen Shot 2021-08-23 at 5 18 20 PM" src="https://user-images.githubusercontent.com/7585078/130527085-98ec80c8-78cc-4cc0-abde-73f1a64bb6a8.png">

**Comment by roblourens** [comment]
How does that key work? I know that some just enter text like a keyboard device. What is the usual experience?

**Comment by roblourens** [comment]
Will have to do some research to figure out how we can get the key, but as a workaround, it would probably work for you to set `"remote.SSH.showLoginTerminal": true`. It should reveal the terminal, and you can log in through that terminal instead of our prompt.
