### ISSUE TITLE
Exact setting to disable git helper in vscode remote

### ISSUE THREAD

**Issue by markomitranic** [microsoft/vscode-remote-release#5500]
Issue #4527 had been closed without any specific/detailed actions or explanations being taken. Same for issue #2441

@wxdao @hholst80

There are many more issues like this one, all asking for the same thing, an option to disable shameless self-injection of the helper into our projects. :D I like to keep my config empty, git hooks magic is a bad idea, mmkay. 

The settings everyone seems to be looking for is:
```json
{
    "remote.containers.copyGitConfig": false,
    "remote.containers.gitCredentialHelperConfigLocation": "none",
}
```

What is interesting - is that this seems to remain undocumented, the issues reffering to it seem to be getting closed without response, and furthermore, the setting itself is greyed out in all remote locations - which leads you to beleive that it is not supported there. A simple hover over it, however, shows a tooltip which instead claims that it is supported but not available in remote editor windows. (whatever that means) The point is, it works. It stops propagating gitconfig from my local machine.

Anyway, what else can we do to ease this pain? Idk, any ideas are welcome really. Perhaps at least making the setting not be greyed out :P

I am creating this issue to raise awareness for the soluton. Keyword porn for google purposes:
Any sort of `.gitconfig` propagation or git helpers should be (and are) seamlessly optional. Some of us may want to disable git helper in containers without node access. Injecting `credential.helper=!f() { /root/.vscode-server/bin/` into gitconfig without our explicit knowledge is kinda sus.

**Comment by markomitranic** [comment]
Ehh, unfortunately for everyone involved, i was wrong. This setting seems to actually do nothing of value in remote containers. Which means that we are back to square one - we don't have a way of disabling this behaviour. We have a setting which promises that but does not deliver.

Any thoughts?

**Comment by hholst80** [comment]
@jako Thank you for the investigation and the solution. If anyone that finds this issue and solution presented, where do they type in this configuration?

**Comment by Jako** [comment]
wat? 🙃

**Comment by hholst80** [comment]
> wat?

Sorry, autocomplete? I have no idea what happened there, but I often have problems with the input UI on my phone. My own fault though. :-)

**Comment by markomitranic** [comment]
> @markomitranic Thank you for the investigation and the solution. If anyone that finds this issue and solution presented, where do they type in this configuration?

Good point @hholst80 , the abovementioned strings are standard vscode settings. You should put them in your editor settings file, or your project's settings file, depending on the scope you want it to cover.

In my case, I never want this to happen, so I have added it to my editor settings JSON file. `Cmd + Shift + P` and type `Preferences: Open Settings (JSON)`. A new tab opens with my settings, in it, a JSON object will be shown. You can also follow this handy tutorial: `https://dev.to/thegeoffstevens/vs-code-settings-you-should-customize-5e75`

If you were to place these settings within the container, I have no idea if they would take effect, sorry.

**Comment by markomitranic** [comment]
@chrmarti hmm, I wonder why you said that, I placed these settings into my local settings.json, and they now work across all ssh remotes as well as pods and container remotes (no idea about devcontainer.json, I despise that feature)

I always assume that is because local user settings take precedence in all remotes.
