### ISSUE TITLE
Should not have to reconfirm versions for unmodified feature selections when updating an existing devcontainer configuration

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-release#5507]
Testing #5495

1. Select all features
2. Go through process of picking which version of go, python, ruby etc. I want
3. Run `Configure Container Features` 
4. Deselect docker-in-docker option
5. Go through process of re-confirming all versions of go, python, ruby even though my selections for those didn't change

**Comment by chrmarti** [comment]
Users might want to change some of the versions, we don't actually know. Maybe we can add a 'Finish' toolbar button to accept all current values.
