### ISSUE TITLE
wsl not starting

### ISSUE THREAD

**Issue by Yashbontala** [microsoft/vscode-remote-release#5512]
Issue Type: <b>Bug</b>

just suddenly stopped working wsl when i entered the ```git config --global credential.helper store```

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Fetching remote diagnostics for 'WSL: Ubuntu' failed: VS Code Server for WSL failed to start. No messages received for 90s
Check WSL terminal for more details.
Fetching remote diagnostics for 'WSL: Ubuntu' failed: VS Code Server for WSL failed to start. No messages received for 90s
Check WSL terminal for more details.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (0.62GB free)|
|Process Argv|--crash-reporter-id 068ec035-27b9-4c7c-9489-1d715b5dc4b8|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu' failed: VS Code Server for WSL failed to start. No messages received for 90s
Check WSL terminal for more details.

Fetching remote diagnostics for 'WSL: Ubuntu' failed: VS Code Server for WSL failed to start. No messages received for 90s
Check WSL terminal for more details.
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn420:30356812
vscus224cf:30358040
vssid140:30358036

```

</details>

**Comment by bamurtaugh** [comment]
Thanks for the clarification and glad it's working again! Feel free to file a new issue if you run into any trouble.
