### ISSUE TITLE
add newHost not found 

### ISSUE THREAD

**Issue by rahulnegi20** [microsoft/vscode-remote-release#5519]
Issue Type: <b>Bug</b>

I am unable to connect to remote ssh with any extension.

Extension version: 2021.8.18181
VS Code version: Code - OSS 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-20T18:17:12.523Z)
OS version: Linux x64 5.10.59-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU 3865U @ 1.80GHz (2 x 800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|3.71GB (0.25GB free)|
|Process Argv|--extensions-dir /home/rahulnegi/.var/app/com.visualstudio.code-oss/data/vscode/extensions --disable-crash-reporter --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by bamurtaugh** [comment]
Thanks for opening, please review the doc [here](https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues) on the type of info we need to help troubleshoot.
