### ISSUE TITLE
Move Remote-SSH out of preview

### ISSUE THREAD

**Issue by GitMensch** [microsoft/vscode-remote-release#5520]
The [Remote-SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) extension was released as preview in 2019. It of course still has issues (as Visual Studio Code and other software has), but can't be seen as a "preview" any more.

I totally see the point of the WSL and Container extensions to be in Preview and also assume that at least the Container extension shares code with proprietary products - but the Remote-SSH should be only vscode+ssh, shouldn't it?

I have an issue with environments that allow "stable vscode" but not "code in preview that may be removed or needs a paid license/subscription"later on, so:

* What is missing to move the remote-ssh extension (not the extension pack) out of "Preview" state?
* Are there any (at least rough) iteration plans when this may happen?
* Is there any decision what happens with the license when the remote-ssh extension is moved out of preview? I guess the most likely two licenses would be either MIT (definitely preferred here) or the same as the Visual Studio Code binaries found at https://code.visualstudio.com/license.

**Comment by chrisdias** [comment]
@bamurtaugh @Chuxel  I know you've been thinking about this...

**Comment by eleanorjboyd** [comment]
@bamurtaugh, this can be closed right since we have released a stable version of this extension? Or I am misunderstanding what this next step for the remote-explorer extension is?

**Comment by bamurtaugh** [comment]
@eleanorjboyd The preview label is on both the stable and insiders versions, so this is a separate issue.

As described [here](https://github.com/microsoft/vscode-remote-release/issues/6256#issuecomment-1031793887), this issue tracks the preview label, which is also described in our [docs](https://code.visualstudio.com/docs/remote/faq#_why-arent-the-remote-development-extensions-or-their-components-open-source).

**Comment by bamurtaugh** [comment]
Thanks again for the discussion here! We're currently working on removing the "Preview" label from our remote extensions, and you should see the update reflected in the coming days.

**Comment by GitMensch** [comment]
> Is there any decision what happens with the [license](https://marketplace.visualstudio.com/items/ms-vscode-remote.remote-ssh/license) when the remote-ssh extension is moved out of preview? I guess the most likely two licenses would be either MIT (definitely preferred here) or the same as the Visual Studio Code binaries found at https://code.visualstudio.com/license.

It currently says "MICROSOFT PRE-RELEASE SOFTWARE LICENSE TERMS MICROSOFT VISUAL STUDIO CODE REMOTE DEVELOPMENT EXTENSIONS".

> I totally see the point of the WSL and Container extensions to be in Preview and also assume that at least the Container extension shares code with proprietary products - but the Remote-SSH should be only vscode+ssh, shouldn't it?

.... and therefore hope that Remote-SSH will be a truly free license under MIT with the full source code published.
