### ISSUE TITLE
port forwarding not working with vscode 1.59.1

### ISSUE THREAD

**Issue by christinecb** [microsoft/vscode-remote-release#5521]
🚨 The issue tracker is not for questions 🚨

If you have a question about VS Code, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code and about
VS Code Remote on https://stackoverflow.com/questions/tagged/vscode-remote.

**Comment by alexr00** [comment]
@christinecb can you please share a screenshot of where you see the error?

**Comment by christinecb** [comment]
@alexr00 : here is a screenshot with the error message:
![2021-08-30 10_07_16-](https://user-images.githubusercontent.com/42608375/131308514-082f97a0-3abe-4f2e-97e3-6bc70473b2bd.png)

**Comment by christinecb** [comment]
And the same with an earlier version of vscode (1.54.3). There is no error message and there is someting in the "Running Process" column of the ports tab :
![2021-08-30 10_21_23](https://user-images.githubusercontent.com/42608375/131309646-f721c598-d3be-4e35-8f05-6c1c9866de96.png)

**Comment by alexr00** [comment]
@christinecb are you using the same version of the PHP extension in both of those screenshots?

**Comment by christinecb** [comment]
![2021-08-30 16_51_27](https://user-images.githubusercontent.com/42608375/131358825-2d93b96c-cced-4401-afed-156820d1e96d.png)

**Comment by alexr00** [comment]
Can you connect to your forwarded port using a browser?

**Comment by christinecb** [comment]
In both of case I can't connect to the forwarded port using a browser.

**Comment by christinecb** [comment]
I have tried to pass this command into my web docker container:  "telnet 10.20.9.50 9003" and with vscode 1.54.3 the connection is ok but with vscode 1.59.1 the connection can't be established.

I also to change the php debug extension (robberphex.php-debug instead of felixfbecker.php-debug) with the same result: Port forwarding does not work anymore in vscode 1.59.1

**Comment by alexr00** [comment]
I'm not able to reproduce port forwarding not working. Can you provide a link to a github repository with a project that easily reproduces the issue?

**Comment by christinecb** [comment]
Hi, yes I am still experiencing this issue. The problème is not from a project in particular, it is more about the way we work in our company. The sourcecode of our project is hosted on a centos VM, and we develop from a workstation with vscode and the ms-vscode-remote.remote-ssh.
In this configuration, we need to redirect the xdebug port from the VM to localhost for the debug to work. (Without the port redirection, we don't see the debug informations throw the debug client).
This port redirection works well in the last version of vscode I was using (1.54.3) and since I updated vscode, the port redirection does not work anymore.
To reproduce the problem, you can create a sample project (no matter which project) on a distant VM and try to debug it throw the vscode debug client making a port forwarding. 

But there is probably an easier way to test the port forwarding without creating a VM to host a project.....

**Comment by alexr00** [comment]
> To reproduce the problem, you can create a sample project (no matter which project) on a distant VM and try to debug it throw the vscode debug client making a port forwarding.

@christinecb this kind of setup still works for me. Can you provide a complete sample project to test with?
