### ISSUE TITLE
Edit file as administrator/sudoer

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-remote-release#5522]
Issue Type: <b>Feature Request</b>

I have a raspberry and I would like to edit files like the apache VirtualHost.
I don't want to set the right at 777 and I don't want to connect me as root.
I would like to save as sudoer and type the password of the account

Extension version: 0.65.7
VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux arm 5.10.52-v7+

**Comment by bamurtaugh** [comment]
Thanks for opening @NWittersheim. Could you elaborate a bit more on the change or feature request you'd like to see here for the Remote-SSH extension specifically?
