### ISSUE TITLE
SSH remote connections not close

### ISSUE THREAD

**Issue by Victsz** [microsoft/vscode-remote-release#5523]
I have several vscode window instance on different projects but connecting to a same Linux box. When close one of the windows will not release any ssh connection. If I close all vscode windows, then the ssh connections will be released.

Version: 1.58.0 (user setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:55.083Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

Remote SSH v0.65.7

**Comment by Victsz** [comment]
> Can you explain some more what you mean by this?
> 
> > windows will not release any ssh connection.

I have multi vscode instance on different remote projects from same box. for example, two vscode, which will have 6 (3 connections for each) connections to the remote box. when close one of two vscode, I expect only 3 connections will be left, but there are still 6 connections.

and i close one o

**Comment by roblourens** [comment]
How are you checking that? If you close all the vscode windows, do the connections get closed?

**Comment by Victsz** [comment]
> Multiple vscode windows will share connections in some cases. When all the windows closed, all the connections were closed. I don't really think there is an issue here. When I try this, the number does not increase per window.

it is an issue
the connetions will accumulate and finally exceed the max limit of ssh for server.
open and close a instance wont release its corresponding resource. it is an obvious issue.
