### ISSUE TITLE
Azure Functions/Python docker image download getting stuck

### ISSUE THREAD

**Issue by sinedied** [microsoft/vscode-remote-release#5528]
I'm trying to use the Azure Static Web Apps dev container image within my local VS Code, and every time the image download for the Azure Functions/Python docker image get stuck at the same point:

![image](https://user-images.githubusercontent.com/593151/131347038-ffdca6e8-e078-47c3-b0c4-b1fa1a291077.png)

The download is stuck indefinitely a 520.09MB.

I tried multiple times, and a colleague of mine has the same issue (with a different location, machine and OS).

Maybe there's something wrong with the registry?

**Comment by chrmarti** [comment]
That downloads successfully for me. I see different image hashes, maybe this is a problem with the older versions. Try running `docker pull mcr.microsoft.com/azure-functions/python:3.0-python3.8-core-tools` and see if that succeeds.

**Comment by sinedied** [comment]
Today I got it working on the first try. Seems that may have been a temporary issue with the registry.
Thanks for your help, I'm closing this.
