### ISSUE TITLE
Can the schedule for the depreciation of the image tag in container json be made public?

### ISSUE THREAD

**Issue by rirlswift** [microsoft/vscode-remote-release#5529]
I have asked the [question ](https://stackoverflow.com/questions/68985807/dev-container-json-image-tag-depreciated-in-insiders-1-60-0)on stack .
It might be useful to some of us who are using the image tag in our container definitions to know when this functionality is going to be officially removed so we can plan and execute the necessary reworking our use-cases?

The removal shows up in insiders 1.60.0

**Comment by chrmarti** [comment]
There are no plans for removing that. Could you append your devcontainer.json? My guess is that you have some other property that makes the JSON validation pick another part of the JSON schema that does not have that property (e.g., `"dockerComposeFile"`).

**Comment by rirlswift** [comment]
appending devcontainer.json - this now happens in  the august release, reverting to july.

```
 {
  "name": "Swift DevOps Gradle.",
  "context": "..",
  "image": "swiftx/ubuntu-gradle:v21",
  "runArgs": [
    "--name","swift-do-gradle-builder",
    "--hostname", "swift-do-gradle-container",
    "--workdir", "/workspaces/gradle",
    "-u", "swift",
    "-v","${env:HOME}${env:USERPROFILE}/.gitconfig:/home/swift/.gitconfig",
    "-v","${env:HOME}${env:USERPROFILE}/.ssh:/home/swift/.ssh",
    "-v","${env:HOME}${env:USERPROFILE}/.devcontainer:/home/swift",
    "-v","${env:HOME}${env:USERPROFILE}/bin:/home/swift/bin",
    "-v", "/var/run/docker.sock:/var/run/docker.sock",
    "--rm",
    "--privileged=true"
  ],

  "settings": {
    "terminal.integrated.shell.linux": "/bin/bash"
  }

```

**Comment by chrmarti** [comment]
`"context"` is only used when also specifying a Dockerfile, please remove that. (That makes the JSON validator look for the properties used with a Dockerfile and `"image"` is not one of them.)
