### ISSUE TITLE
UID not remapped when repository cloned into container volume.

### ISSUE THREAD

**Issue by Clockwork-Muse** [microsoft/vscode-remote-release#5530]
Also affects Insiders builds.

- VSCode Version: 1.59.1 (snap package)
- Local OS Version: Ubuntu 20.04.3
- Remote Extension/Connection Type: Docker
- Logs:
[ContainerLog.txt](https://github.com/microsoft/vscode-remote-release/files/7078331/ContainerLog.txt)

Steps to Reproduce:

1. Start new VSCode window with a user with UID != 1000
2. Install the remote development extensions.
3. Select command `Remote-Containers: Clone Repository in Container Volume` (or `Remote-Containers: Clone Repository in Named Container Volume`), and supply a repository with a dockerfile that creates a new non-root user (like the [netcore sample](https://github.com/microsoft/vscode-remote-try-dotnetcore)).  Clone the repository.
4. Verify that the UID is _not_ remapped to match the external user, via `id` or similar.

This appears to occur regardless of whether there are any bind mounts at all (for example, an X11 port).  This is in contrast to cloning the repository and then reopening it in the container, which does update the UID.

**Comment by chrmarti** [comment]
We only saw the need for updating the UID when mounting a local folder.

Where do you need the updated UID in the volume case?

**Comment by Clockwork-Muse** [comment]
Because in my actual case I'm also bind-mounting other things, which _do_ need to have the remapped `UID` - X11 ports, docker sockets, other files from the host (like config/auth files for gcloud).

In that case, being able to put the repository into a volume is a nice way to isolate the repository a little more.

**Comment by chrmarti** [comment]
We could support `updateRemoteUserUID` in this case too (and maybe keep it disabled by default).

**Comment by aeschli** [comment]
- created a new user on my Fedora box (UID 1001)
- vscode insiders with latest remote containers extension (v0.198.0)
- run `Remote-Containers: Clone Repository in Container Volume`, pick https://github.com/microsoft/vscode-remote-try-dotnetcore
- in the remote window open the terminal, `echo $UID` is 1000

not sure if that's the expected result or if additional steps are needed

**Comment by chrmarti** [comment]
@aeschli Could you set `"updateRemoteUserUID": true` in the devcontainer.json and rebuild the container? With that you should get the same UID in the container as you have on the host (1001). (There are a few conditions that need to hold, e.g, the UID and the default GID must not be used in the container yet.)

**Comment by aeschli** [comment]
Now it works!

The hover is misleading here:
![image](https://user-images.githubusercontent.com/6461412/135460957-7d974680-7c2b-49c8-82be-06bfcd4896b3.png)

**Comment by chrmarti** [comment]
Changing "On by default." to "On by default when opening from a local folder.". Thanks!
