### ISSUE TITLE
Add "Open Folder in Container..." to the sidebar right click context menu for folders

### ISSUE THREAD

**Issue by allanbarklie** [microsoft/vscode-remote-release#5537]
The context menu that appears when you right click on a folder in the side bar already has several "Open in" options.
It would be great to add the "Open Folder in Container..." option.

I can't currently find a way to launch this command with a folder already in context - after firing the command  I currently have to manually pick it from the subsequent folder selection UI.
This option would be very handy for directly launching it.

I would also like it to open a new instance of vs code rather than reusing the current one.

**Comment by chrmarti** [comment]
@JacksonKearl FYI, I don't think there is an "Open In..." submenu planned, but let me know if there is.

@allanbarklie I see "Open in Integrated Terminal", are there others?

**Comment by JacksonKearl** [comment]
No "Open In" submenu planned. I have @chrisdias's [lovely extension](https://marketplace.visualstudio.com/items?itemName=chrisdias.vscode-opennewinstance) installed to contribute some more `Open In...` type commands: 
![image](https://user-images.githubusercontent.com/8586769/132435341-cd09d984-b34e-4591-8534-368eef3eb6e4.png)

@allanbarklie an extension would be able to contribute similar items for containers if the remote containers extension exposes a command to open a specific folder in a container. cc @chrmarti would know more about that.

**Comment by allanbarklie** [comment]
@chrmarti  
cc @JacksonKearl 

I currently have the following Open in options:
Open in Integrated Terminal
Open in Windows Terminal
Open in Windows terminal (Profile)

The idea would be for the remote container extension to add an option:
Open in Container

Hopefully that makes sense

![image](https://user-images.githubusercontent.com/42612310/132490373-98a7bce0-bddb-412c-9e2a-8487021b4140.png)

**Comment by allanbarklie** [comment]
I hadn't remembered using an extension but my windows terminal options come from:
https://marketplace.visualstudio.com/items?itemName=Tyriar.windows-terminal
