### ISSUE TITLE
Support for podman inside of WSL2

### ISSUE THREAD

**Issue by bmayfi3ld** [microsoft/vscode-remote-release#5539]
Due to the new licensing from Docker, Docker Desktop may not be a desired solution for many businesses. 

Since podman is already able to run inside WSL2 and it is supported on Linux Machines. I wonder if it could be adapted to be used on Windows. 

Easiest setup would to be able to handle the call to the podman executable inside of WSL2 from Windows, which is done with the command
```bash
wsl podman
wsl podman --version
```

So in the config you could update the path to be "wsl podman"

I of course don't know if there would be other issues with attaching and mounting to the container. 

Similar to issue https://github.com/microsoft/vscode-remote-release/issues/5538 which references the new licensing as a problem for MacOS as well.

**Comment by bmayfi3ld** [comment]
Further looking into it, it looks like when the folder your trying to open is on the WSL2 filesystem the dev container is already routed through WSL2 directly and podman already works.  So this is an easy existing solution for people. 

But it seems when the folder is on the Windows filesystem remote containers always tries to use windows commands to launch and does not work. Maybe there would be a way to configure how the remote container is launched? That may have connotations on ssh agent forwarding and env vars though I suppose.      

I just have some users that aren't as comfortable with running linux and I'm seeing if I can give them a solution that works as closely with Windows as I can.

**Comment by chrmarti** [comment]
I don't think Podman can mount a Windows folder (please check, I'm not sure), so your users will probably have to use the WSL filesystem.

**Comment by chrmarti** [comment]
Btw., I'm not sure if Docker CLI packages for Linux/WSL are affected by the Docker Desktop change.

**Comment by Trass3r** [comment]
> But it seems when the folder is on the Windows filesystem remote containers always tries to use windows commands to launch and does not work.

Note that doing this is discouraged by MS anyway because the file system performance will be really bad.

**Comment by Trass3r** [comment]
I found it quite hard getting podman to work actually. You need to follow these:
https://code.visualstudio.com/docs/remote/containers#_can-i-use-podman-instead-of-docker (outdated though)
https://dev.to/bowmanjd/using-podman-on-windows-subsystem-for-linux-wsl-58ji

The big problem is that performance is really bad by default cause of fuse-overlayfs:
https://news.ycombinator.com/item?id=25169423
It's basically unusable without https://www.redhat.com/sysadmin/podman-rootless-overlay which only seemed to work for me after upgrading to pre-release Ubuntu 21.10 and thus podman 3.2.1 (kernel was 5.14 before already).

And the weird default user id mapping was another big problem:
https://github.com/containers/podman/issues/2898
https://github.com/containers/podman/pull/3196
Had to use this:
```js
    "remoteUser": "vscode",
    "runArgs": [
        "--userns=keep-id"
    ],
```

And in the end it'll still use cgroups v1 it seems cause of https://github.com/microsoft/WSL/issues/6662#issuecomment-847827158

**Comment by bmayfi3ld** [comment]
> I don't think Podman can mount a Windows folder (please check, I'm not sure), so your users will probably have to use the WSL filesystem.

I was able to mount it through the wsl c mount. 
`[bmayfield ~]$ podman run -it -v /mnt/c/Users/bmayfield/Downloads:/extratmp --entrypoint sh busybox`

> Btw., I'm not sure if Docker CLI packages for Linux/WSL are affected by the Docker Desktop change.

That is how I understand it.    May be a better route to just install Docker CLI on windows. When I was researching that some sites suggested trying out podman instead. 

> Note that doing this is discouraged by MS anyway because the file system performance will be really bad.

Agreed, but I'm going for ease of use, not performance.

> I found it quite hard getting podman to work actually. You need to follow these:

Those are good resources and the main ones I was looking at. So far is has performed well for the use cases I have.

**Comment by Chuxel** [comment]
Let's also separate this request from Docker Desktop since Docker CE/EE (or Moby if you build it) can run in WSL as well w/o Docker Desktop (among other solutions that have been thrown around like nerdctl, just using a Minikube cluster plus the Docker CLI, etc).

To be clear, this is a 100% fair request - Podman was a great available alternative to the Docker/Moby CLI/Engine before and still is for those wanting to use containers on Linux (including WSL). #5538 is talking about the install prompt that appears and whether we should reconsider that, but as stated there, there is not a drop-in alternative for Docker Desktop itself which targets broad support and is more than just the Docker CLI and Engine.

**Comment by PavelSosin-320** [comment]
Not hard! Podman uses FUSE to mount volumes, i.e. the abstraction level that allows mounting and see any type of filesystem as a single FS in the userspace. The recent Docker version does the same. It simply works.
_podman run -it -v /mnt/c/users/pavel:/home/pavel localhost/ubuntuvolume ls /home/pavel/_
Another issue is that instead of mounting workspace as volume to container Podman can mount Container to a workspace or do nothing and create a workspace as anonymous volume declared in the image using "image config".

**Comment by Trass3r** [comment]
> Podman was a great available alternative to the Docker/Moby CLI/Engine before and still is for those wanting to use containers on Linux (including WSL).

I don't know, it was a PITA from beginning to end on WSL. Even after finally getting it to run (see above) the performance was really bad (even simple commands and auto-complete take a long time to run, esp. after startup) and it started making other problems like suddenly failing on container exit with `ERRO[0000] Cannot get exit code: invalid character '\x00' looking for beginning of value` or not being able to delete images anymore `ERRO[0000] error joining network namespace for container ...: error retrieving network namespace...: unknown FS magic...: ef53`.

Docker is a better [alternative](https://dev.to/bowmanjd/install-docker-on-windows-wsl-without-docker-desktop-34m9).
Only networking was a bit of a problem, requiring `"iptables": false` and `--network=host`.

**Comment by PavelSosin-320** [comment]
Stack Podman 3.3 + Fedora34 WSL distro + systemd-genie 1.40 (avoiding root privs usage) + buildah 1,2 ( for image configuration w/o rebuild)  + certain set of systemd units to hands-free dev env starting (Theia)  + Network configuration necessary for working in the double stack Internet infra with local forwarder + published Docker REST API (usable for self-update) works OK.
Podman stack based on the recent Fedora 34 WS works OK too.

**Comment by chrmarti** [comment]
@bmayfi3ld I'm adding a user setting to always run commands in WSL, also for Windows paths and when there is no local path when attaching to an existing container.

**Comment by trallnag** [comment]
@Trass3r, setting up Podman on WSL becomes really easy if Systemd is setup 😉. Then `sudo apt install podman` is enough. I'm currently switching to [systemd-genie](https://github.com/arkane-systems/genie) as means of getting Systemd to work and I hope that over the longterm WSL will have Systemd out of the box. Or at least not break systemd-genie.

**Comment by rzhao271** [comment]
@chrmarti are there specific verification steps for this issue, or is it covered by the TPI?

**Comment by chrmarti** [comment]
The steps are slightly different:
- Set the `Remote > Containers: Docker Path` setting to the full path of where `docker` is installed in your default WSL distro (`/usr/bin/docker`?). (This ensures the command would fail on Windows.)
- Enable the new setting `Remote > Containers: Execute in WSL`.
- Open a folder on the Windows filesystem and run `Remote-Containers: Reopen Folder in Container`.
  - Pick a dev container config if the folder doesn't have one already.
- Verify the folder successfully opens in the container.

Reset the `Remote > Containers: Docker Path` setting when done.
