### ISSUE TITLE
No write permission when using remote-container with non-root user

### ISSUE THREAD

**Issue by keosu** [microsoft/vscode-remote-release#5542]
- VSCode Version: 1.58.0
- Local OS Version: win10
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: no write permission  
I am using a remote container(non-root user) and I mapped a folder to the container. I do have write permission if using terminal for edit, but can't save the changes with the vscode GUI that would trigger permission denied error.

Steps to Reproduce:

1. connect to the remote container with non-root user and open the mapped folder
2. open some file and edit, then try to save it, the error dialog pops up
3.  If I edit the file in the terminal, nothing happens

**Comment by Chuxel** [comment]
Please provide a bit more information about your environment.  Can you share your devcontainer.json + Dockerfile? Is your source code in WSL or Windows?  Are you using Docker Desktop?

**Comment by keosu** [comment]
> Please provide a bit more information about your environment. Can you share your devcontainer.json + Dockerfile? Is your source code in WSL or Windows? Are you using Docker Desktop?

Thanks for reply. I am using docker client on win10 and set up a docker context to connect the docker container running my remote linux server in SSH way. My source folder is on my remote linux server and I map it as a container volume.
The command I use to start the container:
```sh
 docker run  -e UID=$(id -u) -e GID=$(id -g) -it -v  $HOME/works/:/work my_img_name
```
The container would switch to a non-root user and I have permission of  **/work** folder when I use a terminal, but error happens when I using the vscode GUI.
I found that my .vscode-server would be installed to /root/.vscode-server and the server process would be running with root user(I know this using the command *ps -ef* command) in the termial. The root user couldnot modify my folder.

My steps to open VSCode:
1. open VSCode in Windows
2. click the remote explorer in the left panel and select the Container dropdown menu
3. right-click my container and select *Attach to Container*
Then the remote server would run as root user, My current question is how could I start the remote server without root?
