### ISSUE TITLE
Podman: Invalid handle

### ISSUE THREAD

**Issue by max06** [microsoft/vscode-remote-release#5545]
# Version stuff
```
- Version: 1.60.0-insider (system setup)
- Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
- Date: 2021-09-01T10:40:58.134Z
- Electron: 13.1.8
- Chrome: 91.0.4472.164
- Node.js: 14.16.0
- V8: 9.1.269.39-electron.0
- OS: Windows_NT x64 10.0.19042

- Remote Extension/Connection Type: Docker - v0.194.0
```

**Be careful!** The latest podman installer for windows seems to bring a bug, adding a single `"` to your $Path env-var. 

# Conditions:
- Have a working podman setup - in this case it's a remote ubuntu server (through vpn) with podman running rootless.
- VSCode set to `"remote.containers.dockerPath": "podman"`

```
PS C:\Users\max06\test> podman ps -a
CONTAINER ID  IMAGE                          COMMAND     CREATED      STATUS                  PORTS       NAMES        
25acfaa87d78  docker.io/library/bash:latest  bash        3 hours ago  Exited (0) 3 hours ago              adoring_bassi
```

Executed locally to confirm remote connection!

# Error
Terminal shows:
```
[6247 ms] Start: Run: podman version --format {{.Server.APIVersion}}
[6941 ms] Stop (694 ms): Run: podman version --format {{.Server.APIVersion}}
[6946 ms] time="2021-09-02T21:25:28+02:00" level=error msg="Das Handle ist ungültig."
```

Repeatedly. Whatever I'm trying to do, opening a local folder in a container, cloning into a volume, doesn't matter.

# Debugging Approach
Executing the command manually
- in a powershell terminal in vscode: `Error: unknown shorthand flag: 'i' in -inputFormat`
- in a regular powershell window: Same
- in a regular cmd window: `3.2.3` <- **Works**

If you need something, ping me!
Thank you very much!

**Comment by chrmarti** [comment]
> Executing the command manually

That is `podman version --format {{.Server.APIVersion}}`? If not, could you try running that? (The last parameter might need quotes in Powershell / cmd.)

**Comment by max06** [comment]
It works if I wrap the template string into quotes. But it looks like VSCode is running that command in a Powershell env and therefore not getting the expected output.

**Comment by max06** [comment]
More detailed: 
```
C:\Users\max06>podman version --format {{.Server.APIVersion}}
3.2.3

C:\Users\max06>podman version --format "{{.Server.APIVersion}}"
3.2.3
```

```
PS C:\Users\max06> podman version --format {{.Server.APIVersion}}
Error: unknown shorthand flag: 'i' in -inputFormat
PS C:\Users\max06> podman version --format "{{.Server.APIVersion}}"
3.2.3
```

**Comment by chrmarti** [comment]
We run the command without using a shell. Note that the error the extension logs is different from the one you see in Powershell. Continuing to track this in https://github.com/microsoft/vscode-remote-release/issues/3929.
