### ISSUE TITLE
Cannot use hyper-v container (Windows 10)

### ISSUE THREAD

**Issue by draggeta** [microsoft/vscode-remote-release#555]
I cannot connect to remote containers on a Windows 10 host. The containers are running in Windows mode with one Windows container running in process isolated mode and a linux container running in Hyper-V mode. I'm trying to develop in the Linux container. When the remote session starts, I receive an error similar to:

```powershell
Setting up container for folder: c:\git\draggeta\docker-dev-environment
Run: docker exec 0912d059cd20c2a1d79c4e7eade1cff486fdfa6acbe59cc1f6e472f34bb44883 test -d /root/.vscode-server-insiders
Run: docker exec 0912d059cd20c2a1d79c4e7eade1cff486fdfa6acbe59cc1f6e472f34bb44883 /bin/sh -c set -o noclobber ; mkdir -p '/root/.vscode-server-insiders/data/Machine' && { > '/root/.vscode-server-insiders/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
Run: docker exec 0912d059cd20c2a1d79c4e7eade1cff486fdfa6acbe59cc1f6e472f34bb44883 /bin/sh -c (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
Run: docker exec 0912d059cd20c2a1d79c4e7eade1cff486fdfa6acbe59cc1f6e472f34bb44883 test -d /root/.vscode-server-insiders/bin/0284236851a94b116f468345f6e98688a737015d
Installing VS Code Server for commit 0284236851a94b116f468345f6e98688a737015d
Run: docker exec 0912d059cd20c2a1d79c4e7eade1cff486fdfa6acbe59cc1f6e472f34bb44883 mkdir -p /root/.vscode-server-insiders/bin/0284236851a94b116f468345f6e98688a737015d_1559606110611
Run: docker cp C:\Users\TONY~1.FOR\AppData\Local\Temp\vsch\0284236851a94b116f468345f6e98688a737015d\vscode-server-linux-x64.tar.gz 0912d059cd20c2a1d79c4e7eade1cff486fdfa6acbe59cc1f6e472f34bb44883:/root/.vscode-server-insiders/bin/0284236851a94b116f468345f6e98688a737015d_1559606110611
Error response from daemon: filesystem operations against a running Hyper-V container are not supported
Failed: Copying VS Code server to container
Command failed: C:\Program Files\Docker\Docker\Resources\bin\docker.exe cp C:\Users\TONY~1.FOR\AppData\Local\Temp\vsch\0284236851a94b116f468345f6e98688a737015d\vscode-server-linux-x64.tar.gz 0912d059cd20c2a1d79c4e7eade1cff486fdfa6acbe59cc1f6e472f34bb44883:/root/.vscode-server-insiders/bin/0284236851a94b116f468345f6e98688a737015d_1559606110611
```

The error seems to be caused that you are not allowed to write/copy to a running Hyper-V container, but sadly I need both Windows and Linux containers at the same time.

- VSCode Version: 1.35.0-insider
- Local OS Version: Windows 10 1903
- Remote OS Version:  Debian GNU/Linux 9 (stretch) (container)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Start insiders and point it to folder
2. try to connect to remote

Does this issue occur when you try this locally?: Yes

EDIT: For clarity.

**Comment by bamurtaugh** [comment]
Hey @draggeta, thanks for opening this! If I'm not mistaken, it looks like this is essentially a more specific version of https://github.com/microsoft/vscode-remote-release/issues/445, and since there hasn't been recent discussion here, I'm going to close this issue.

If you have any other questions or feedback, please feel free to let us know, and thanks for trying out the extension!
