### ISSUE TITLE
Show Log from Container Creation Progress notification has no effect

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#5556]
- Try a Remote Container sample
- Click the show log link from the progress notification

![image](https://user-images.githubusercontent.com/172399/132459420-bcb3401c-c3b9-4efd-8824-99d2fd36b242.png)

=> nothing happens

Opening the terminal once the container is built shows an empty terminal
![image](https://user-images.githubusercontent.com/172399/132459802-78926c54-a7cf-4e23-91c9-904d8d745e58.png)

**Comment by chrmarti** [comment]
Nothing has changed on the extension's side. It still works when you wait until the resolver is done. My guess is that something changed with the latest VS Code Insiders builds. /cc @Tyriar @meganrogge

**Comment by chrmarti** [comment]
@meganrogge I'm also seeing this with the 1.60.1 candidate and I see a fix from you going in. Could that cause this?

**Comment by Tyriar** [comment]
In console:

```
ERR Terminal creation failed: Error: Terminal creation failed
	at E.createExtensionTerminal (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:33986)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/blob/e880f7ef3d2ca036a8467cb65fa3e6d64ef0d3e4/src/vs/workbench/api/common/extHostTerminalService.ts#L170-L173

**Comment by Tyriar** [comment]
Maybe the change to make `createTerminal` async caused this somehow?

**Comment by Tyriar** [comment]
Looks like that's it; the below isn't awaited within `$createTerminal` and it's what causes `_id` to eventually get updated on the exthost:

https://github.com/Microsoft/vscode/blob/c1427cc3292c7658cfc04127bbd651f4aefe5cfe/src/vs/workbench/api/browser/mainThreadTerminalService.ts#L143-L149

**Comment by Tyriar** [comment]
It doesn't seem to repro using the extension-terminal-sample, not sure why it's only happening for dev containers.
