### ISSUE TITLE
Vetur Extension not work correct

### ISSUE THREAD

**Issue by JMDC-SUN** [microsoft/vscode-remote-release#556]
- VSCode Version: VSCode insider 1.35.0
- Local OS Version:  Windows10
- Remote OS Version: remote Docker : 18.09.6/centos7.5
- Remote Extension/Connection Type: Docker

I use Vetur Extension, but it  not work correct.
When I "Toggle Line Comment" to the javascript source in vue.file, it use html tag to comment.
How can I resolve this ?

`    `

**Comment by egamma** [comment]
@JMDC-SUN can you reproduce the problem when you run VS Code locally?

**Comment by JMDC-SUN** [comment]
Using local vscode, The .vue file is as a vue language file, no any problem.
![image](https://user-images.githubusercontent.com/49149068/59490641-31b01880-8ec0-11e9-9812-bdbcde795b1f.png)

![image](https://user-images.githubusercontent.com/49149068/59490626-278e1a00-8ec0-11e9-92c3-2b6313b75467.png)

Using  vscode Insiders, The .vue file is as a vue.js language file, has issue.

![image](https://user-images.githubusercontent.com/49149068/59490850-a5eabc00-8ec0-11e9-9688-767689aada2d.png)

![image](https://user-images.githubusercontent.com/49149068/59490885-b9962280-8ec0-11e9-9415-b6a7bc30da9a.png)

**Comment by JMDC-SUN** [comment]
I try it on Vscode 1.35.1 with Remote Development.

I comment htmls in the template tag of vue.js file. It not work correct.
![image](https://user-images.githubusercontent.com/49149068/59571947-a8c5f680-90e4-11e9-9521-ea5e69e14403.png)

I comment javascript souce in the script tag of vue.js file. It work well.
![image](https://user-images.githubusercontent.com/49149068/59572003-fcd0db00-90e4-11e9-8298-32cb87c8e22e.png)

My environment: 
----------------------------------------
Version: 1.35.1 (user setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
----------------------------------------

**Comment by octref** [comment]
@aeschli Not sure what went wrong. Vetur uses `embeddedLanguages` to mark embedded regions. It seems in remote, `comments` of language configuration is not loaded correctly.

**Comment by JMDC-SUN** [comment]
It worked! Thank you  very much!
