### ISSUE TITLE
Can't connect to the remote container directly using SSH tunneling

### ISSUE THREAD

**Issue by dmvictor** [microsoft/vscode-remote-release#5566]
- VSCode version: 1.60.0
- Remote-containers version: 0.194.0
- local OS: Windows 10 Enterprise 19042
- local Docker version: 20.10.8, build 3967b7d (Docker Desktop 4.0.0)
- remote host OS: Ubuntu 16.04.6 LTS (kernel version: 4.15.0-106-generic)
- remote host Docker version: Server version 20.10.6

I followed the procedures and tips in this [page](https://code.visualstudio.com/docs/containers/ssh) to connect to the remote Docker engine directly using SSH tunneling. The remote host is running Docker and the specified container is running with the following docker run command. 
```
sudo docker run --gpus all --shm-size=8g -it -v /path/to/the/directory:/mmpose/data -p 10001:10001 -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY mmpose
```

In the container, I've installed the OpenSSH server and set the sshd_config file properly. I can ssh to it in the VSCode terminal without any issue.

In my local host, I created a Docker context like this:
```
[
    {
        "Name": "mmpose_container",
        "Metadata": {},
        "Endpoints": {
            "docker": {
                "Host": "ssh://root@192.168.100.113:10001",
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "C:\\Users\\dmvictor\\.docker\\contexts\\meta\\214f3c6adeec83db44247b321c8c37d781190e03aac1c38cf5f0831430b2c894",
            "TLSPath": "C:\\Users\\dmvictor\\.docker\\contexts\\tls\\214f3c6adeec83db44247b321c8c37d781190e03aac1c38cf5f0831430b2c894"
        }
    }
]
```

Afterward, I issued "docker context use mmpose_container" in Windows PowerShell, trying to activate the Docker context pointing to the remote machine. Actually, I could not see the created docker context in the Docker viewlet of the Docker extension.

![Image 1710](https://user-images.githubusercontent.com/11869587/132811282-f1e0ce79-374c-4bac-950b-d53ac6bdadd3.png)
![Image 1716](https://user-images.githubusercontent.com/11869587/132811334-e4b8b738-62a7-4c69-9cc0-680310d356e5.png)

When I used the Command Palette (Ctrl+Shift+P) to issue the `Remote-Containers: Attach to Running Container...` command to attach the running container. The Dev Containers terminal showed the following message:
```
[106499 ms] Remote-Containers 0.194.0 in VS Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff).
[106498 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[2223526 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[2226271 ms] 
[2226271 ms] error during connect: Get "http://docker.example.com/v1.24/version": command [ssh -l root -p 10001 -- 192.168.100.113 docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=kex_exchange_identification: Connection closed by remote host
```

As a matter of fact, I just want to edit the code in the container from my Windows VSCode. 
Is there anything I did wrong in my procedure? Thank you!

**Comment by chrmarti** [comment]
How do you `ssh` into the machine in the terminal? `ssh://root@192.168.100.113:10001` seems incorrect because you're probably not using `root` on the remote machine, but a regular user and `10001` is the port from the container, when you want the ssh port (defaulting to 22). Once logged in using `ssh`, does `docker ps -a` work?

**Comment by dmvictor** [comment]
I used `ssh://dmvictor@192.168.100.113` to log into the remote machine in the terminal, corresponding to the 2nd and 4th results in my previous post. When I logged into my remote machine using ssh, `docker ps -a` worked with no problem.

**Comment by chrmarti** [comment]
Does `docker --host ssh://dmvictor@192.168.100.113 ps -a` work locally?

**Comment by dmvictor** [comment]
No. The response is "Cannot connect to the Docker daemon at http://docker.example.com. Is the docker daemon running?"

**Comment by chrmarti** [comment]
What is the output of `docker --debug --host ssh://dmvictor@192.168.100.113 ps -a` locally?

**Comment by dmvictor** [comment]
The output was showed as following:
```
time="2021-09-16T15:47:38+08:00" level=debug msg="commandconn: starting ssh with [-l dmvictor -- 192.168.100.113 docker system dial-stdio]"
time="2021-09-16T15:47:39+08:00" level=debug msg="commandconn (ssh):failed to open the raw stream connection: dial unix /var/run/docker.sock: connect: permission denied\n"
time="2021-09-16T15:47:39+08:00" level=debug msg="commandconn: starting ssh with [-l dmvictor -- 192.168.100.113 docker system dial-stdio]"
time="2021-09-16T15:47:39+08:00" level=debug msg="commandconn (ssh):failed to open the raw stream connection: dial unix /var/run/docker.sock: connect: permission denied\n"
time="2021-09-16T15:47:39+08:00" level=debug msg="commandconn: starting ssh with [-l dmvictor -- 192.168.100.113 docker system dial-stdio]"
time="2021-09-16T15:47:40+08:00" level=debug msg="commandconn (ssh):failed to open the raw stream connection: dial unix /var/run/docker.sock: connect: permission denied\n"
time="2021-09-16T15:47:40+08:00" level=debug msg="FIXME: Got an status-code for which error does not match any expected type!!!: -1" module=api status_code=-1
Cannot connect to the Docker daemon at http://docker.example.com. Is the docker daemon running?
```

**Comment by chrmarti** [comment]
It looks like the `dmvictor` account does not have access to the Docker socket on `192.168.100.113`. Can `dmvictor` run `docker ps` on that remote machine or do you change to a different account first?

**Comment by dmvictor** [comment]
I got the problem. Actually, `dmvictor` need `sudo` to run `docker ps`. 
I modified the permission of `/var/run/docker.sock` to 777 and I can attach VS Code to my running container now. Thanks for your help!

**Comment by chrmarti** [comment]
If you don't want to open access to Docker to all users, you could add your account to the `docker` group. (https://docs.docker.com/engine/install/linux-postinstall/)
