### ISSUE TITLE
Clone to open in container does not recursively get submodules

### ISSUE THREAD

**Issue by kriswuollett** [microsoft/vscode-remote-release#5569]
- VSCode Version: 1.60.0
- Local OS Version: macOS 11.5.2
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: Docker-in-Docker (my copy)

Steps to Reproduce:

1. Add Docker-in-Docker setup to a repo that contains git submodules
2. The `initializeCommand` in `devcontainer.json` makes use of a script within a submodule
3. Container building fails due to file not found

Current workaound:

* Add `git submodule update --init --recursive &&` prefix to the `initializeCommand`.

Should getting all code available, including submodules, be done at initialization time?

**Comment by Chuxel** [comment]
@chrmarti Is there an option we have to recurse submodles for "Clone Repo in..."

//cc: @bamurtaugh

**Comment by chrmarti** [comment]
There is no such option in the UI at the moment.

**Comment by phongngthanh** [comment]
Having --recurse-submodules options for cloning to container would make sharing the devcontainer settings for multi-repo a lot easier. Propagating devcontainer.json settings currently requires changing by hand each devcontainer.json in each repo; using devcontainer.json as a submodule would solve this problem I think.
