### ISSUE TITLE
Show ports for other containers in docker-compose

### ISSUE THREAD

**Issue by aNickzz** [microsoft/vscode-remote-release#5572]
I have a setup that starts 3 containers via a docker-compose.yml. Aside from the `dev` container, there are `mysql` and `phpmyadmin`.

In the Ports view, VSCode shows (and links to) port 80 in the `dev` container, it would be great if it could also show a link to the `phpmyadmin` container too. Currently, I need to go through the docker Dashboard to find and use the link there, as the bound port is not consistent.

**Comment by aNickzz** [comment]
See also: #5578

**Comment by aNickzz** [comment]
I noticed that I can reference other hosts when adding ports in the Ports view, eg. I can add `phpmyadmin:80` which will create a tunnel and give me a link. It would be suitable to be able to populate this via workspace/container settings.

**Comment by alexr00** [comment]
@aNickzz the works for this has been done as part of https://github.com/microsoft/vscode-remote-release/issues/3450 and it will be available in the next stable release.
