### ISSUE TITLE
Categorize SSH Targets defined in the config file

### ISSUE THREAD

**Issue by JakobMiesner** [microsoft/vscode-remote-release#5574]
It would be beneficial if we could categorize the SSH Targets in the Remote Explorer view.
I have multiple targets for work and multiple targets for private projects defined in my config and sometimes lose track of which category a target is from.

**Comment by bamurtaugh** [comment]
Part of the request from https://github.com/microsoft/vscode-remote-release/issues/2938; not sure if you'd rather tag as dupe or feature request @roblourens?

**Comment by william-bohannan** [comment]
Grouping SSH targets would be nice feature +1, Or perhaps give the ability to give them a color?
