### ISSUE TITLE
git-credential-manager prompts for user selection until run on local OS

### ISSUE THREAD

**Issue by ahwitz** [microsoft/vscode-remote-release#5577]
- VSCode Version: 1.53.2 (user setup)
- Local OS Version: Windows_NT x64 10.0.18363
- Remote OS Version: `centos-release-7-8.2003.0.el7.centos.x86_64`
- Remote Extension/Connection Type: Docker
- Logs: possibly n/a?

### Steps to Reproduce:

This is a weird one, but I wanted to report it in case it's something fixable/something that suggests other problems. Has happened to me on two machines, and to a colleague on one machine.

- Something lapses with git-credential-manager.
- All (git) remote-facing git actions on the remote OS (through command line, or through extensions like Git Graph) prompt a git-credential-manager popup on the host. 
- Clicking my username lets the current action succeed, but popups persist.

I found that triggering the popup once on the local OS and selecting my username there successfully prevented the popups from happening on the remote OS. Also confirmed that worked for my colleague.

If there's any more info we can get you, let me know and I'll send it on. Don't know if anyone else internally is dealing with the problem, or how easy to reproduce it'll be. Or if it's even worth fixing.

Does this issue occur when you try this locally?: See above, related to connection between remote and local
Does this issue occur when you try this locally and all extensions are disabled?: See above, same

**Comment by chrmarti** [comment]
Which credential manager are you using on the local OS? Was the local OS in all instances Windows?

**Comment by ahwitz** [comment]
Windows 10 in all cases, and managed by an organization. I'm not a Windows user normally, so the best answer I can give is "the default one", I think? It seemed to proxy the user that I was logged in to my computer as through to Azure DevOps, and that user didn't show up in the Credential Manager under Control Panel.

If there's anything in particular you want me to check/run on that machine to get more information, let me know. I have full admin access on that laptop.

**Comment by chrmarti** [comment]
We are using `git credential fill` locally to do the lookup. I'd expect that to work the same way as when a local `git clone` does the lookup.

You mention clicking on your user name, could you attach a screenshot?

**Comment by ahwitz** [comment]
![image](https://user-images.githubusercontent.com/3514397/133435556-a48d7158-acdf-4517-a510-b1f15a632bc6.png)

That's the popup we were getting. Screenshot taken from aforementioned colleague.

**Comment by chrmarti** [comment]
How do you trigger this window locally, so it stops showing up? Using `git clone` on the command line?

**Comment by ahwitz** [comment]
Yup, any git command from the local OS in VSCode. Includes command-line git, includes the Git Graph UI.

**Comment by ahwitz** [comment]
Possibly related: as of Friday, `git push` gives me `fatal: unable to access 'https://dev.azure.com/....': Could not resolve host: dev.azure.com; Unknown error` errors on the remote OS, while `git fetch` gives me no errors. Both fetch and push work on the local OS.

**Comment by chrmarti** [comment]
@ahwitz Let me know if this is still an issue. "Could not resolve host" sounds like DNS resolving was broken in the container.

**Comment by ahwitz** [comment]
We haven't been running into it after finding that fix, and I haven't heard of anyone else from our office running into the issue despite being one of the first points of contact for when stuff like this happens.

The only reason I don't think it was a DNS issue is because it succeeded after acknowledging the popup we shared a screenshot of, so the same request did work after manually confirming the user. Will send more details or try to get in touch if we find someone who has run into the issue again.
