### ISSUE TITLE
[Remote-SSH] http[s]_proxy not passed to child process.

### ISSUE THREAD

**Issue by MengJie** [microsoft/vscode-remote-release#558]
- VSCode Version:
1.35.0-insider
Version: 1.35.0-insider (user setup)
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T00:13:30.572Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
- Local OS Version:
Win10 1809 17763.437
- Remote OS Version:
 Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-50-generic x86_64)
- Remote Extension/Connection Type: SSH/Docker/WSL
SSH
Steps to Reproduce:

1. Make sure the remote OS have no direct internet access.
2. Set the http_proxy and https_proxy in .bashrc
3. Set up connection to remote os in the Remote-SSH
4. Open the connection, the remote os try to use wget download VSCode-Inside-Server.
   But it not success.

I check the environment variables of the wget process in the remote os, the http[s]_proxy is
not set.
After I set the proxy for wget in the .wgetrc, the VSCode-Insider-Server installation is success.
But I can't Install other extension remotely.

This issue can not be reproduced in the version 0.37.0, it's occurred in version 0.41.0.

Thanks.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Where is the http_proxy variable set?

**Comment by roblourens** [comment]
Is bash your default shell?

If you open a vscode terminal, is the variable set in that terminal?

**Comment by MengJie** [comment]
Hi, @roblourens 
Yes, bash is my default shell. And the variables is set in that termimal.

**Comment by roblourens** [comment]
> I check the environment variables of the wget process in the remote os, the http[s]_proxy is
not set.

Can you explain what you mean, how did you check the environment of that process?

The .bashrc should be run by the install script but sometimes a .bashrc will bail out if it's not in an interactive session. Is that the case? What if you try setting those variables at the top of the script?

**Comment by MengJie** [comment]
> Can you explain what you mean, how did you check the environment of that process?

1.  `ps aux | grep wget` can figure out the pid of the running wget process.
1.  `cat /proc/[pid]/environ` will list all the environment variables of that process.

> The .bashrc should be run by the install script but sometimes a .bashrc will bail out if it's not in an interactive session. Is that the case? What if you try setting those variables at the top of the script?

No. It might not be that case.  I have tried setting the variables in .bashrc and .bash_profile. And In the same setting, it worked in an old version (0.37.0).

**Comment by roblourens** [comment]
Ok so you don't have something like 

```
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```

keeping that line from running? That is in my default .bashrc.

What if you run `ssh host "echo $HTTP_PROXY"`?

**Comment by MengJie** [comment]
No, I don't have that.
> What if you run ssh host "echo $HTTP_PROXY"?

It print my proxy setting.

**Comment by roblourens** [comment]
Ok. That's strange because that's essentially exactly what the install script is doing, so I have no clue why the environment would be correct in that case but not during install.

**Comment by MengJie** [comment]
@roblourens Yes, you are right. I follow your instruction and solve the problem. Thanks a lot.
