### ISSUE TITLE
How is the .env file used 

### ISSUE THREAD

**Issue by JackCaster** [microsoft/vscode-remote-release#5589]
I am trying to set some env variables to pass to the dockerfile at build time. [Here](https://code.visualstudio.com/docs/remote/containers-advanced#_option-2-use-an-env-file) you write:
> If you have a large number of environment variables that you need to set, you can use a .env file instead. **VS Code will automatically pick up a file called .env in your workspace root**, but you can also create one in another location.

Could you explain what "automatically" means in this context? Does it mean that if I create a `.env` file in the root folder of the workspace, the env variables defined in that file will be loaded automatically by VSCode? And if so, how can I access them?

**Comment by chrmarti** [comment]
It's `docker-compose` that automatically picks up the `.env` file. The behavior of that has changed in version 28 from reading the `.env` file from the current working directory (the workspace folder) to the folder of the first `docker-compose.yml`. (https://github.com/microsoft/vscode-remote-release/issues/4560)

You could try passing the environment variables from the `.env` (in the correct folder) to the build by adding build arguments to the `docker-compose.yml` referring to the environment variables.
