### ISSUE TITLE
Error when .gitconfig is not accessible

### ISSUE THREAD

**Issue by joewood** [microsoft/vscode-remote-release#559]
- VSCode Version: Insider build 2019-06-04T00:13:30
- Local OS Version: Windows 10
- Remote OS Version: None (local container)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open folder in container
2. Immediate error: 

```
Error: (HTTP code 500) server error - error while creating mount source path '/host_mnt/c/Users/WoodJoe/.gitconfig': mkdir /host_mnt/c/Users/WoodJoe/.gitconfig: permission denied 
```
On windows I have a `.gitconfig` file in my %HOMEPATH%. Not sure why the extension to attempt to create a directory (maybe to auto-mount the volume). This is not a permission error, this is **mkdir** returning an error because a file exists where it's trying to create a directory.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: n/a

**Comment by joewood** [comment]
The specific problem from this is the generated command on docker for mounting gitconfig. This was actually a permission error accessing home directory from the account that the docker daemon is running. Opening up permissions to the git config fixed the issue.

**Comment by chrmarti** [comment]
Closing as the permissions on the file were the problem.
