### ISSUE TITLE
The detailed release notes link to `master` branch rather than `main` in marketplace

### ISSUE THREAD

**Issue by stone-zeng** [microsoft/vscode-remote-release#5590]
- VSCode Version: 1.60.1
- Local OS Version: Darwin x64 21.1.0
- Remote OS Version:
- Remote Extension/Connection Type: SSH/Docker/WSL
- Logs:

Steps to Reproduce:

1. Open <https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh#release-notes>
2. The "detailed release notes" links to the `master` branch rather than `main`
3. This issue also appears in the extension page in VSCode

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Fixed, will show up in the next release, thanks
