### ISSUE TITLE
Variables are not correctly expanded in devcontainer.json

### ISSUE THREAD

**Issue by JackCaster** [microsoft/vscode-remote-release#5591]
In my `devcontainer.json` I am using the variable `${localEnv:VARIABLE_NAME}` to set some build arguments:

```
{
	"name": "my name",
	"dockerFile": "Dockerfile",
	"build": {
		"args": {
			"VARIABLE_NAME":"${localEnv:VARIABLE_NAME}"
		}
	},
...
}
```
but this is not working as expected. The variable passed to the build command is the workspace location 
```
docker build -f c:\dev\myproject\.devcontainer\Dockerfile -t vsc-myproject-bc631c6bf0bd7b7306126250b3220d16 --build-arg VARIABLE_NAME= c:\dev\myproject
```
Is this a bug? How can I pass local env variable to the docker build command? Would you be able to help?

**Comment by chrmarti** [comment]
How do you set the local environment variable? Does `${localEnv:PATH}` work?

**Comment by JackCaster** [comment]
Good point. PATH worked. So I removed, re created, and restarted the pc and now also my custom variable works. Thanks!
Though, it still remain perhaps a bug that that variable was expanded to the workspace location.

**Comment by chrmarti** [comment]
The space separates the build arg from the final argument which is the context folder. So the build arg's value is the empty string. You can use `A${localEnv:NOT_EXIST}B` to verify.
