### ISSUE TITLE
Why does containers use onStartupFinished?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-remote-release#5594]
Added in https://github.com/microsoft/vscode-remote-release/issues/3196, why does containers eagerly load? This adds extra overhead too all non-container windows.

**Comment by chrmarti** [comment]
There are a few devcontainer configs built-in for well-known repositories that we check against when the extension activates.

**Comment by Tyriar** [comment]
If that's all can we try contribute to the repos with them and remove the need to activate? Containers is one of my slowest extensions to start up and it's activated for every workspace which makes me want to disable it as I'm trying to figure out why my Windows build has become slow.

**Comment by chrmarti** [comment]
What's the typical activation times you see for Remote-Containers vs. other extensions?

The main reason for checking for a devcontainer config is the 'Reopen in Container' notification we show when there is a config. This has improved discoverability for the builtin configs which are otherwise hidden away. Adding telemetry to find out if this sees much user interaction.

**Comment by Tyriar** [comment]
> The main reason for checking for a devcontainer config is the 'Reopen in Container' notification we show when there is a config.

This should be covered by these events:

```
"workspaceContains:.devcontainer/devcontainer.json",
"workspaceContains:.devcontainer.json",
```

I frequently see the activation time as taking 200-300ms

**Comment by chrmarti** [comment]
These events only cover the case where the devcontainer.json is in the workspace. There are a few additional devcontainer.jsons built-in for which discoverability was an issue when the notification didn't tell the user that a Dev Container config is available.

**Comment by Tyriar** [comment]
Right, I don't know how many there are but is upstreaming these an option? It seems like a shame to activate for every repo when it's often not needed.

**Comment by chrmarti** [comment]
The user can add configurations in a local folder outside the workspace folder and we want to check these. Closing, thanks.
