### ISSUE TITLE
Add label to created containers that specifies the container is a devcontainer

### ISSUE THREAD

**Issue by josegonzalez** [microsoft/vscode-remote-release#5596]
At the moment, there isn't a great way to check if a container is a devcontainer or not. We get a few labels that don't seem to be devcontainer specific:

```
vsch.local.folder
vsch.quality
vsch.remote.devPort
```

I would like to have a label such as `vsch.devcontainer=true` so that I can show only non-devcontainer containers. This would be useful for deleting all other containers during tests _inside_ of the devcontainer.

My current workaround is to add a custom label to the devcontainer Dockerfile, but I'd need to do this for every project. Having something standard upstream would make it more portable.

**Comment by chrmarti** [comment]
`devcontainer.config_file` appears to be always set now. Closing as otherwise out of scope.
