### ISSUE TITLE
The config's default value only work after it be hard code in the config file.

### ISSUE THREAD

**Issue by amaothree** [microsoft/vscode-remote-release#5599]
Vscode Version: 1.60.1-Windows
Remote - SSH version: 0.65.8
OS: Windows 10

After I upgrade the vscode to 1.60.1, I found I cannot connect to my remote server via "Remote-ssh" extension.

 I checked logs, I found the value of config "remote.SSH.useLocalServer" be change to false during the connection.

However, I always use the default value (true/enable) of this config. I try to check and uncheck the config repeatedly but not fix the issue.

Then I realised that if you change a boolean type setting to a default value. Then VScode would only delete the changed value from the config.json file, not reverse its value. 

Thus, I try to hardcode the '"remote.SSH.useLocalServer": true' in the config.json file. And it work! the config be load, I can connect to my server again.

I believe this is a bug, I'm not sure if this is a plugin problem or a vscode problem, which has never happened before.

**Comment by roblourens** [comment]
This is a known issue, see https://github.com/microsoft/vscode/issues/58038
