### ISSUE TITLE
no ssh remote connection

### ISSUE THREAD

**Issue by Bebbolus** [Microsoft/vscode-remote-release#56]
Issue Type: <b>Bug</b>

The terminal process command 'cmd.exe/c (type "C:\Users\A744153\AppData\Local\Temp\vscode-linux-multi-line-command-localddserver.sh" | ssh -F C:\Users\A744153\.vscode-insiders\remoteconfig.config localddserver) & exit /b 0' failed to launch (exit code: 255)

ssh configuration file content:
Host localddserver
    User roberto
    HostName 192.168.56.104

with putty ssh connection works fine

Extension version: 0.34.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (7.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kieferrm** [comment]
@Bebbolus Putty is not yet supported. Pls try the steps in https://code.visualstudio.com/docs/remote/troubleshooting#_reusing-a-key-generated-in-puttygen.

**Comment by murilogiatti** [comment]
Creating the ssh key using: ssh-keygen -t rsa -b 4096 is not working on Windows 10's powershell. So I used ssh-keygen -o -a 100 -t ed25519 -f C:\Users\user\ .ssh\id_ed25519.

I think this needed to be added in here: https://code.visualstudio.com/docs/remote/troubleshooting#_installing-a-supported-ssh-server

**Comment by Bebbolus** [comment]
Installed Github all work fine!
