### ISSUE TITLE
remote ssh docker volume dev container error

### ISSUE THREAD

**Issue by Diluka** [microsoft/vscode-remote-release#5612]
Issue Type: <b>Bug</b>

1. using remote ssh connect to a server
2. open docker ext
3. expand volumes tab
4. right click on any one
5. click Explore in a dev container

```log
[169794 ms] Remote-Containers 0.194.0 in VS Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d).
[169793 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[169911 ms] 
[169911 ms] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Extension version: 1.16.1
VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 4.15.0-153-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.32GB free)|
|Process Argv|--crash-reporter-id 70d49eaf-740d-4f61-8019-84b755e21cb6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: bf07|
|OS|Linux x64 4.15.0-153-generic|
|CPUs|Intel(R) Xeon(R) Gold 6161 CPU @ 2.20GHz (8 x 2200)|
|Memory (System)|15.66GB (0.91GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187cf:30365362
pydsgsc2:30361791
vscus224cf:30367820
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by chrmarti** [comment]
This is https://github.com/microsoft/vscode/issues/111238. Marking as upstream.

It works from the Remote Explorer viewlet.

**Comment by chrmarti** [comment]
Upstream issue. Closing as wont-fix.
