### ISSUE TITLE
Dev Container node.js application stucks with VS Code 1.60.1

### ISSUE THREAD

**Issue by Iamcerba** [microsoft/vscode-remote-release#5613]
- VSCode Version: 1.60.1
- Local OS Version: Windows 10 Enterprise 19043.1237
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: [javascript-node](https://github.com/microsoft/vscode-dev-containers/tree/v0.194.0/containers/javascript-node)

Steps to Reproduce:

1. Check out the following node.js express application: https://github.com/jatins/express-hello-world.git
2. Open it with the following dev container definition:
```jsonc
{
	"name": "Node.js",
	"build": {
		"dockerfile": "Dockerfile",
		// Update 'VARIANT' to pick a Node version: 12, 14, 16
		"args": { "VARIANT": "14" }
	},

	// Set *default* container specific settings.json values on container create.
	"settings": {},

	// Add the IDs of extensions you want installed when the container is created.
	"extensions": [
		"dbaeumer.vscode-eslint"
	],

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "yarn install",

	// Comment out connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "node"
}
```
3. In terminal install npm dependencies:
```bash
npm install
```
4. Run application:
```bash
npm start
```
5. Application will start but when you try to navigate any route it will stuck with infinite load: 
![image](https://user-images.githubusercontent.com/8203463/133986005-0f5745d3-f25b-41d7-bf26-0757132e8843.png)
6. The same application worked well with previous versions of VS Code, e.g. **1.59.1**. It is only reproducible with a new 1.60.1 version with different node.js applications like express.js, NestJs.

**Comment by Chuxel** [comment]
Moving to right repository.  

@chrmarti @alexr00 - This might be a regression. I'm seeing the same thing if the app is listening to `localhost` instead of `0.0.0.0`.

**Comment by chrmarti** [comment]
Reproduced with the snippet below. Not sure if that plays a role, but starting the server without hostname reports the hostname as the ipv6 localhost `[::]`.
```js
const server3 = http.createServer((req, res) => {
    res.end('Hello!');
});
server3.listen(1236, () => {
    const address = server3.address();
    console.log(`http://${address.address}:${address.port}`);
});
```

**Comment by Iamcerba** [comment]
> the sample above omits `'localhost',` and just specifies the port. So not sure if that somehow has something to do with this or not.
In "listen()" method "hostname" arg isn't obligatory, moreover, this sample was working with the previous version of VS Code (1.59.1).

**Comment by alexr00** [comment]
To verify:
1. Open a container (where you can run javascript) in a folder. https://github.com/microsoft/vscode-remote-try-node is always a good one.
2. Add this snippet to a file in our open folder:
```ts
const server3 = http.createServer((req, res) => {
    res.end('Hello!');
});
server3.listen(1236, () => {
    const address = server3.address();
    console.log(`http://${address.address}:${address.port}`);
});
```
3. Run the snippet from step 2.
4. Port 1236 will get forwarded. Open the Ports view.
5. From the Ports view, use the globe inline action on port 1236 to "Open in Browser".
6. Verify that your browser opens and you can see the `'Hello!'`.

**Comment by hediet** [comment]
Verified in insiders!

**Comment by chrmarti** [comment]
Verified in the latest 1.60.2 candidate build.
