### ISSUE TITLE
Docker Compose V2 profiles do not work with dev containers

### ISSUE THREAD

**Issue by abarani** [microsoft/vscode-remote-release#5617]
I'm not sure this is a bug strictly related to the Containers extension but currently dev containers defined in a Docker Compose config using [custom profiles](https://docs.docker.com/compose/compose-file/compose-file-v3/#profiles) are no longer working with Docker Compose V2 using the latest Docker Desktop release. This is a regression from Docker Compose V1 as they were working as expected previously.

Trying to start a container with such configuration results in the following error:

```
Service '[name]' configured in devcontainer.json not found in Docker Compose configuration.
```

Checking the log I see the extension is calling `docker-compose '-f' '[path]/docker-compose.yml' 'config'` command resulting in any container defined under custom profiles to be left out from the generated configuration.

If this cannot be fixed I suggest adding a `serviceProfile` property to devcontainer.json to let users specify the profile to use when starting up the container defined in `docker-compose.yml`.

#### Details:

- VSCode Version: 1.61.0-insider
- Local OS Version: Windows 10 21H1 (19043.1237)
- Remote OS Version: -
- Remote Extension/Connection Type: Docker
- Logs:

#### Steps to Reproduce:

1. Enable Docker Compose V2 release candidate in Docker Desktop settings:
    ![docker-settings-compose-v2](https://user-images.githubusercontent.com/2650264/134180274-33ab3759-f370-4374-8806-5a472f9a713a.png)

2. Try to start a dev container using Docker Compose and a custom profiles assigned:
    ![vscode-container-error](https://user-images.githubusercontent.com/2650264/134180530-c1a57c53-a845-48e2-af25-a6867317fbe7.png)

#### Sample configuration files:

- docker-compose.yml:
    ```yaml
    version: "3.8"
    services:
      dev:
        image: alpine:3.14
        command: [ "sleep", "infinity" ]
        init: true
        volumes:
          - .:/workspace:cached
        profiles:
          - dev
    ```

- .devcontainer/devcontainer.json:
    ```json
    {
      "name": "test",
      "dockerComposeFile": "../docker-compose.yml",
      "workspaceFolder": "/workspace",
      "service": "dev",
      "runServices": ["dev"]
    }
    ```

Does this issue occur when you try this locally? Yes
Does this issue occur when you try this locally and all extensions are disabled? Yes

**Comment by chrmarti** [comment]
This is a change in how Docker Compose's config command handles profiles. Not sure if that's by intention, I have opened https://github.com/docker/cli/issues/3313 to clarify.

**Comment by chrmarti** [comment]
`--profile '*'` only works with 1.29.0 (released 2021-04-06). (https://docs.docker.com/compose/release-notes/#1290)

**Comment by abarani** [comment]
Verified on latest Insiders version (1.61.0 - a43442f) and it is now working as expected. 👍
Thank you!
