### ISSUE TITLE
There is no way to stop remote from creating docker container

### ISSUE THREAD

**Issue by KasperSkytte** [microsoft/vscode-remote-release#5619]
version 1.60.1
windows+linux+macos

There is no way to stop VSCode from creating a docker container when using the nice remote (in container) feature in the bottom left corner. It's really frustrating when it's failing, hanging, or taking a long time. Closing or killing the terminal or ctrl+c doesn't help, restart vscode doesn't help, as it will just do it all again at start. The terminal seems to be only outputting, otherwise totally non-interactive and VSCode is hanging until the background process is done. Thanks for an otherwise awesome feature!

**Comment by chrmarti** [comment]
There is `F1` > `Remote: Close Remote Connection` while the container is building. Does that address your issue?

**Comment by KasperSkytte** [comment]
It absolutely does! And it doesn't continue building if I reopen the folder afterwards. Thank you
