### ISSUE TITLE
Docker Compose error when opening from vscode directly

### ISSUE THREAD

**Issue by adalfa** [microsoft/vscode-remote-release#5622]
Hello to all
I've encountered an issue with rover caf-terraform container when starting the container from vscode. 
I get the following errors:

> docker-compose --project-name caf-terraform-landingzones-starter_devcontainer -f /home/dalfarra/Documents/caf/caf-terraform-landingzones-starter/.devcontainer/docker-compose.yml -f /tmp/docker-compose.devcontainer.containerFeatures-1632327544896.yml up -d
> ERROR: Version mismatch: file /home/dalfarra/Documents/caf/caf-terraform-landingzones-starter/.devcontainer/docker-compose.yml specifies version 3.7 but extension file /tmp/docker-compose.devcontainer.containerFeatures-1632327544896.yml uses version 

if i fix the version manually in  the docker-compose.devcontainer.containerFeatures-1632327544896.yml , the containert starts successfully

Version: 1.60.1
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:06:57.931Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.16-100.fc33.x86_64

tanks

**Comment by chrmarti** [comment]
Could you append your docker-compose.yml? (The version part matters most, we try to parse that out.)

**Comment by adalfa** [comment]
Hello here you have (is the standard docker-compose from  zone)
`


  version: '3.7'
  services:
    rover:
      image: aztfmod/rover:1.0.1-2106.3012
      user: vscode

      labels:
        - "caf=Azure CAF"

      volumes:
        # This is where VS Code should expect to find your project's source code
        # and the value of "workspaceFolder" in .devcontainer/devcontainer.json
        - ..:/tf/caf
        - volume-caf-vscode:/home/vscode
        - volume-caf-vscode-bashhistory:/commandhistory
        - ~/.ssh:/tmp/.ssh-localhost:ro
        - /var/run/docker.sock:/var/run/docker.sock

      # Overrides default command so things don't shut down after the process ends.
      command: /bin/sh -c "while sleep 1000; do :; done"

  volumes:
    volume-caf-vscode:
      labels:
        - "caf=Azure CAF"
    volume-caf-vscode-bashhistory:
                                   
`

**Comment by chrmarti** [comment]
The file has a two spaces indentation. The fix on our side is to ignore it. You could work around it by removing these two leading spaces in the entire file.

**Comment by TylerLeonhardt** [comment]
@adalfa can you verify this is working for you again in the latest version?

**Comment by adalfa** [comment]
@TylerLeonhardt same error with another version of the S.O, I can confirm that with the corret syntax is working in my office machine, i'll give a try and update the thread. thanks
Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:01:43.795Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 4.16.11-100.fc26.x86_64

**Comment by chrmarti** [comment]
@adalfa Thanks for checking, you currently need VS Code Insiders to get the updated version of the Remote-Containers extension with the fix. The same version will be available with the upcoming VS Code 1.61.

**Comment by adalfa** [comment]
@chrmarti I confirm that with insiders version is working, thanks
