### ISSUE TITLE
Open Remote Settings (JSON) not working as expected

### ISSUE THREAD

**Issue by alexkuc** [microsoft/vscode-remote-release#5623]
When I select "Open Remote Settings (JSON)", instead of opening JSON, it actually opens regular settings pane:

![image](https://user-images.githubusercontent.com/3331946/134396583-4a89b53c-a98d-4fa5-9fb8-81aaa6bc1c3b.png)

![image](https://user-images.githubusercontent.com/3331946/134396615-73a44d03-8466-481b-a03d-b29c8acae38b.png)

- VSCode Version: 1.60.2
- Local OS Version: OSX 10.13.6
- Remote OS Version: Ubuntu 20.04.3 LTS 
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Launch remote session via SSH
2. Command palette
3. "Open Remote Settings (JSON)"

**Comment by bamurtaugh** [comment]
Thanks for reporting @alexkuc - this seems like a bug. Does this happen consistently? Does it happen consistently on this remote / every remote?

**Comment by alexkuc** [comment]
@bamurtaugh it actually happens all the time. I only have 1 remote to test this on.
