### ISSUE TITLE
Custom Inputs for ssh connections 

### ISSUE THREAD

**Issue by sinazadeh** [microsoft/vscode-remote-release#5625]
Here is my problem. I am a windows user who wants to connect to a server with 2-factor authentication. SSH keys not working on this server, so every time I want to login to the server, I should enter my password, and then enter number 1, so some confirmation will be sent to my phone.
Is there any way to use vscode remote with custom inputs? (First, enter my password like sshpass then enter number 1). I know it is not safe but I don't care. I don't want to use Wsl either.

**Comment by bamurtaugh** [comment]
I think this is covered by https://github.com/microsoft/vscode-remote-release/issues/4427 (making all 2fa prompts completable).

This is also related to https://github.com/microsoft/vscode-remote-release/issues/2010. If you set `"remote.SSH.showLoginTerminal": true`, then you should be able to enter your code into the actual terminal, and you can also set `remote.SSH.maxReconnectionAttempts`.
