### ISSUE TITLE
how to start a remote session from cli with port and pam file

### ISSUE THREAD

**Issue by mhamri** [microsoft/vscode-remote-release#5628]
in the documentation, it has only one example it doesn't show any example about identity file and without using config file. 

I tried to see if I can find any example here or stackoverflow but look like it's not a topic that explored a lot 

I've tried to look into the code and then I realized this repo is only for the release and not sure where even I can see the code. 

my question is how to start the connection right away from the command without writing it inside the config

I'm looking for something align this 

`
code --remote="user:root;host:172.19.18.2/folder/to/open;port:1972;IdentityFile:~./ssh/id_rsa"
`

**Comment by bamurtaugh** [comment]
As described in https://github.com/microsoft/vscode-remote-release/issues/585#issuecomment-536580102, you can use the following to launch from the command line:

`code --remote ssh-remote+myubuntubox /home/x/projects/foo`.

@roblourens @aeschli Would setting the port and other files from the command line be a feature request?

**Comment by mhamri** [comment]
thanks @bamurtaugh but it doesn't help as it expects the `myubuntubox` be an existing setting in the `ssh.config`

what I'm looking for is something totally different, I want to start a session without an existing setting, from scratch, through the command line
