### ISSUE TITLE
Fails on remote non-amd64 arch

### ISSUE THREAD

**Issue by zhabba** [microsoft/vscode-remote-release#563]
Issue Type: <b>Bug</b>

Extension fails if remote machine has other than x86_64 architecture with the following error:

Can't connect to arm-sink: unreachable or not Linux x86_64 (Linux aarch64)

Extension version: 0.41.0
VS Code version: Code - Insiders 1.35.0-insider (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T00:08:32.039Z)
OS version: Linux x64 4.18.0-21-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 1454)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|15.55GB (3.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/60
