### ISSUE TITLE
VScode fork bombed my ssh

### ISSUE THREAD

**Issue by EricDiGi** [microsoft/vscode-remote-release#5631]
1. Using the ssh plugin that appears first in app frame when you search "ssh"
2. Login to ssh server of choice, that has a resource limit on users
2a. Our server allows students to fork processes for programming classes, but we limit resources to avoid crossover with other students 
3. Now that you are connected, do some work, save, edit, repeat but when you're done leave the vscode program open.
4. Continue to use your device as usual, BUT WITHOUT closing the vscode program.
5. After a couple days close the program or try to log back in
6. When you try to restart the ssh again it should fork bomb. (This may take 1 or 2 attempts)

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by EricDiGi** [comment]
SSH through cli worked just fine.
Any use of VScode to access ssh resulted in fork bomb.

**Comment by roblourens** [comment]
Sorry that you had this experience. This isn't enough information to repro or act on. 

Can you find the full command line of the actual processes, like using `ps`?

Do you have any remote extensions installed? Does this happen if you disable them?

**Comment by EricDiGi** [comment]
This also occurred to many of my classmates who were using the same
extension for the same purpose.
On the server, user instances cannot run into one-another's services, so it
was NOT the case that one student launched a fork that interrupted other
students.

**Comment by roblourens** [comment]
> There was nothing being run across an SSH session when the problem occurred.

I don't understand, it sounds like this happens when connected with Remote-SSH
