### ISSUE TITLE
WSL Remote: Keyboard shortcut for word wrap (Alt Z) not working; works locally

### ISSUE THREAD

**Issue by Pawper** [microsoft/vscode-remote-release#5632]
- VSCode Version: 1.61.0-insider
- Local OS Version: Windows 10 Home OS build 19042.1237
- Remote OS Version:  Ubuntu 20.04
- Remote Extension/Connection Type: WSL
- Logs: N/A

Steps to Reproduce:

1. I only have the Remote - WSL extension enabled
2. Open file in WSL remote
3. Press Alt Z while editor is in focus

Does this issue occur when you try this locally?: No - it works locally. issue is just while in WSL remote
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
I just tried Alt + Z while in a Remote-WSL session, and it appears to be working for me. Does this fail in every file / project in WSL, or just certain ones? Is there anything unusual in the Remote Server or Remote Extension Host logs?

**Comment by Pawper** [comment]
It's very strange, this seems to be working now. Thanks for your time!
