### ISSUE TITLE
Test that ports 443 and 8443 are https by default

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#5634]
Refs: https://github.com/microsoft/vscode-remote-release/issues/5489

- [x] ssh @lydiayschung
- [x] dev container @hediet
- [x] ssh @digitarald (Optional)

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%235634%0A%0A&assignees=alexr00)

---

1. Connect to your remote.
2. Forward ports 443, 8443, and one more port of your choosing.
3. For each port:
   1. Right click on each port and go to the "Change protocol" menu entry. 
   2. Verify that 443 and 8443 show "https" and that the other port shows "http" as the item with the ✔ in the submenu.

**Comment by digitarald** [comment]
Worked as expected. Only minor surprise I had is that _Copy Local Address_ doesn't include the protocol.
