### ISSUE TITLE
Solution to running PostgreSQL commands on Docker Devcontainer [Python 3 & PostgreSQL]

### ISSUE THREAD

**Issue by StEvUgnIn** [microsoft/vscode-remote-release#5636]
You need to create a shared volume between Python (`app`) and PostgreSQL (`db`).

Template available here for `docker.compose.yml`: https://gitlab-etu.ing.he-arc.ch/-/snippets/160

**Comment by bamurtaugh** [comment]
Do you have a specific question about using the definition at https://github.com/microsoft/vscode-dev-containers/tree/main/containers/python-3-postgres? Are you encountering a bug or issue with it? 

Greater details about what you're experiencing, what you've tried, and what you'd like to achieve would be great. Thanks!

**Comment by StEvUgnIn** [comment]
@bamurtaugh You may have not read the title, but without bound volume, you cannot use `psql` on the container.
