### ISSUE TITLE
SSH Extension: Return/Enter while in disconnected (with dialog up) should NOT add a newline to editor

### ISSUE THREAD

**Issue by adumas** [microsoft/vscode-remote-release#5637]
Using SSH extension, with a window open to a remote folder:
1) Wait for the SSH connection to timeout/die and the "Reload" or "Cancel" dialog is up in the editor
2) Hitting enter on Mac actually adds a newline to the open file under the dialog instead of activating the Reload functionality (expected since the button seems like a default value because it's blue/highlighted and it should be a blocking dialog box element)
3) Once you restore the connection, the edited code has an extra return value in there and Undo does not correct the issue-- you have to revert the file.

CPUs | Apple M1 (8 x 24)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 1, 1, 2
Memory (System) | 16.00GB (0.48GB free)
Process Argv | --crash-reporter-id fa5c042c-3e36-44a1-b857-442111d62bd8
Screen Reader | no
VM | 0%

**Comment by sbatten** [comment]
@adumas is the enter keystroking dismissing the dialog? or just adding characters to the file underneath without dismissing the dialog?

**Comment by sbatten** [comment]
is this still reproducible?

**Comment by roblourens** [comment]
I can't repro
