### ISSUE TITLE
Test: Container features IntelliSense

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#5639]
Refs: #5442

- [x] windows @stevencl
- [x] anyOS @alexdima

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%235639%0A%0A&assignees=chrmarti)

---

- Add `"remote.containers.experimentalContainerFeatures": true` to your user settings (ignore that it is unknown).
- Use `Remote-Containers: Add Development Container Configurations Files...` to add a devcontainer.json to a workspace folder.
  - Verify that at the end you can pick container features and these then show up in the `"features"` property of the devcontainer.json (not in the JSON schema yet).
- Use IntelliSense to edit the `"features"` property. Some features have a version that can either be specified as a string value or as an `{ "version": "..." }` object value. Both should be supported with IntelliSense.

Limitations:
- The experimental setting is "unknown".
- The `"features"` property is not in the JSON schema.

**Comment by alexdima** [comment]
@chrmarti everything works great. I didn't understand however this bullet point:

> Verify the TBD feature also has the additional TBD option and you get IntelliSense for that too.

**Comment by chrmarti** [comment]
@chrmarti We didn't get that into the metadata in time. Updating the test description now, thanks.
