### ISSUE TITLE
files can not be opened from vscode integerated terminal connected to remote Linux PC via remote development extension

### ISSUE THREAD

**Issue by imrahul81** [microsoft/vscode-remote-release#5645]
I can not open any file with the command
`code file_name `

Although I can open the files in Linux PC with `code file_name`

- VSCode Version: 1.60.2
- Local OS Version: Windows 10
- Remote OS Version:  (Ubuntu 20.4)
- Remote Extension/Connection Type: SSH/Docker/WSL
- Logs: 
```
`$ code abc.txt --verbose`
[337572:0928/175202.272153:ERROR:browser_main_loop.cc(1402)] Unable to open X display.
The futex facility returned an unexpected error code.
/dev/fd/3: No such file or directory
Server response:
```

**Comment by imrahul81** [comment]
In my Linux PC I have multiple desktops installed, it this helps
1. XFCE
2. KDE plasma
3. Gnome

**Comment by bamurtaugh** [comment]
Can you open the files with Remote-WSL while already in VS Code, rather than through the command line?

**Comment by imrahul81** [comment]
> Can you open the files with Remote-WSL while already in VS Code, rather than through the command line?

Yes, I can open them from the vscode file explorer.

**Comment by imrahul81** [comment]
this issue only happens in the vscode integrated terminal while on remote ssh connection.

**Comment by imrahul81** [comment]
> Can you open the files with Remote-WSL while already in VS Code, rather than through the command line?

could you please help here
