### ISSUE TITLE
Cannot work with docker compose v2

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-remote-release#5647]
Since v2, which is now stable, docker compose is not a binary named `docker-compose` anymore but instead a plugin to docker, which can be invoked with `docker compose`.

This can be worked around by using [compose-switch](https://github.com/docker/compose-switch):

 ```console
$ version=v1.0.2
$ sudo curl -fsSL --output "/usr/local/bin/docker-compose" "https://github.com/docker/compose-switch/releases/download/${version}/docker-compose-linux-amd64"
$ sudo chmod +x /usr/local/bin/docker-compose
 ```

But ideally the Remote - Containers should handle this situation by itself.

**Comment by Chuxel** [comment]
There is a compose-switch package docker is putting together to address the linux issue as well that I believe will ultimatley be made a dependency. https://github.com/docker/compose-switch

**Comment by felipecrs** [comment]
Very interesting, thanks for letting me know about it.

**Comment by rgeorgiev583** [comment]
> Since v2, which is now stable, docker compose is not a binary named `docker-compose` anymore but instead a plugin to docker, which can be invoked with `docker compose`.
> 
> This can be worked around by having a shim like:
> 
> ```shell
> cat <<'EOF' | sudo tee /usr/local/bin/docker-compose
> #!/bin/sh
> 
> exec docker compose --compatibility "$@"
> EOF
> sudo chmod +x /usr/local/bin/docker-compose
> ```
> 
> But ideally the Remote - Containers should handle this situation by itself.

I tried this workaround but VSCode still replies with "Docker Compose required"; any idea what might be the underlying cause?  I even tried changing the "Docker Compose Path" setting for this extension to `/usr/local/bin/docker-compose` - to no avail.

**Comment by felipecrs** [comment]
On my tests it worked, but I'm not using the workaround anymore and I don't think it's better than using compose-switch. Can you try with compose-switch instead? For example, I install it with:

```
$ version=v1.0.2
$ sudo curl -fsSL --output "/usr/local/bin/docker-compose" "https://github.com/docker/compose-switch/releases/download/${version}/docker-compose-linux-amd64"
$ sudo chmod +x /usr/local/bin/docker-compose
```

**Comment by rgeorgiev583** [comment]
compose-switch did the job for me; thanks a lot! :)

**Comment by TylerLeonhardt** [comment]
@chrmarti @Chuxel  can we have some verification steps?
or
@felipecrs @rgeorgiev583 can you verify that this issue is fixed and you don't need compose-switch?

**Comment by Chuxel** [comment]
Install Docker CE on Linux

**Comment by Chuxel** [comment]
1. Get a fresh Linux VM with VS Code installed or WSL instance
2. Verify docker-compose is not installed
2. Install Docker CE on Linux in the VM/WSL instance:  https://docs.docker.com/engine/install/ 
    (Docker Desktop will NOT verify since it installs the compose-switch)
3. Install Docker Compose v2 https://github.com/docker/compose#where-to-get-docker-compose
4. Use "Add Dev Container Configuration Files" to add one of the docker compose definitions from thist (e.g. Node & MongoDB)
5. Reopen folder in container

**Comment by chrmarti** [comment]
Instead of 1.-4. I have used Docker Desktop and changed the Remote Containers: Docker Compose Path setting to a non-existing name.

Temporarily renaming the docker-compose executable would also work.

(Both are assuming the docker executable has Compose v2 installed, which is the case with recent Docker Desktop.)
