### ISSUE TITLE
devcontainer CLI (public) does not factor in features

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#5648]
Testing https://github.com/microsoft/vscode-remote-release/issues/5442 from the CLI, even when the experimental dev container features are enabled in settings, the CLI does not seem to pick up the feature and build it.  This happens for both the image/Dockerfile scenario and Docker Compose.

Repro:

1. Get the latest insides and Remote - Containers extension and install the dev container CLI locally via the built in command
2. Use "Add Development Container Configuration Files" and select a definition and some features.
3. Go to the command line and execute `devcontainer build --image-tag feature-test .` from the folder with the `.devcontainer` filer in it.  For example, the Azure CLI.
4. Run `docker run -it --rm feature-test bash` and run a command to verify the feature is installed (e.g. just type `az` if you installed the Azure CLI).

Expected: Feature is present in image
Actual: Feature not present

//cc: @chrmart @joshspicer

**Comment by joshspicer** [comment]
I've added an `--experimental` flag to `devcontainer build` - I don't believe it will work with just the vscode settings.  

Now that we're closer to publicizing, probably doesn't make sense anymore to have the flag

**Comment by Chuxel** [comment]
@joshspicer Is this in 0.198.0?  `--experimental` didn't seem to resolve it.

**Comment by Chuxel** [comment]
@joshspicer  One updated observation with bits that will land tomorrow There's still a bug in the CLI because the `--image-name` argument is not applied to the image that contains the features... it's applied to the one before it.  So the repro above still fails.

In addition, Docker Compose variant still doesn't seem to do the features build.

**Comment by rzhao271** [comment]
I tried verifying the issue but got stuck on https://github.com/microsoft/vscode-remote-release/issues/5670. @Chuxel are you able to verify the issue?

**Comment by Chuxel** [comment]
@rzhao271 I was able to get it running on Linux, yes.  However, I was trying on 1.60 and not on Windows.  I replied to your issue with an error I saw when trying the CLI installed via the extension there.

(I did fail in downloading the public CLI from vscode-remote-release, however. I think that's locked down to MS employees only which wasn't the goal. )

**Comment by rzhao271** [comment]
Thanks for the hint. Verified it fine on the Mac.

**Comment by Chuxel** [comment]
Its published here as well https://github.com/microsoft/vscode-remote-release/packages/1019896 - but you seem to need to log in and use a PAT.

**Comment by chrmarti** [comment]
@rzhao271 Does `remote-containers.installUserCLI` not work? (On which OS?)

**Comment by rzhao271** [comment]
@chrmarti the command works fine for me. I was wondering what @Chuxel meant for https://github.com/microsoft/vscode-remote-release/issues/5648#issuecomment-933947784
