### ISSUE TITLE
@wainj do you know by any chance how much space it requires?

### ISSUE THREAD

**Issue by xyzustc** [microsoft/vscode-remote-release#5649]
In fact, it is not about disk space but about the number of file/dirs. You can refer https://unix.stackexchange.com/questions/67890/disk-quota-exceeded-problem .
I had the same problem as a user with low privileges in a server, so I guess I have very limited quota, I clean many small files/dirs in my $HOME, and problem solved. 
Or you can ask your admin to increase your quota.
@wainj do you know by any chance how much space it requires?

_Originally posted by @islaterm in https://github.com/microsoft/vscode-remote-release/issues/1374#issuecomment-531358125_

**Comment by bamurtaugh** [comment]
Hi @xyzustc - is this a new request/issue? If so, please provide additional details. Thank you!
