### ISSUE TITLE
Support multi-architecture builds in the devcontainer CLI

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#5652]
Currently, the `devcontainer build` command will build for your current architecture. While this has worked well historically, the arrival of M1 macs has created a challenge particularly for CI systems (that are nearly always running x86) to generate both x86 and arm64 images.

To resolve this, we could provide an option that will `buildx` to build multiple architectures (or the equivalant command for other docker-esque clis we end up supporting). However, note that the `buildx --load` option that makes the image available for local use does not support multiple `--platform` values today. As a result, if a single platform is specified we can use the load option,  otherwise we would not. We can also expose something analogous to `--push` to automatically push to image registries.

//cc @chrmarti @joshspicer

**Comment by KrisJanssen** [comment]
Is there any update on this? Indeed hitting issues trying to use a Dev container on an M1 system... having the container build with a forced --platform linux/amd64 would solve that.

**Comment by chrmarti** [comment]
Setting the DOCKER_DEFAULT_PLATFORM environment variable (see https://docs.docker.com/engine/reference/commandline/cli) should work.

**Comment by Chuxel** [comment]
@chrmarti I don't believe that supports multiple architectures.  You can't "run" in multi-architecture mode. What we need to be able to do is accept multiple platforms and do a push for CI scenarios.  This is how the vscode-dev-containers repository is set up.

**Comment by chrmarti** [comment]
@Chuxel Forgot to qualify my suggestion: In @KrisJanssen's case DOCKER_DEFAULT_PLATFORM might work since that appears to only require a single platform. The original feature request cannot be solved with that. Thanks for clarifying.
