### ISSUE TITLE
Port forwarding - separate local and remote ports?

### ISSUE THREAD

**Issue by jakevossen5** [microsoft/vscode-remote-release#5654]
As far as I can tell, there is no way to have a separate local and remote ports. If I want to connect to a service that is running on port 80 on the remote host, I have to use port 80 on my localhost. I know when using the SSH command you can set different ports, it would nice to be able to do this in the UI of VSCode.

Sorry if this is a duplicate, I looked around a good bit and didn't find anything but the search terms are kinda generic.

**Comment by roblourens** [comment]
You can right click a forwarded port entry to change the lcoal port.
