### ISSUE TITLE
Provide a way to read remote-host variables when creating devcontainers on a remote docker host

### ISSUE THREAD

**Issue by Clockwork-Muse** [microsoft/vscode-remote-release#5655]
I don't believe this is likely possible at the moment, since the necessary commands for starting the containers are all run locally but...

It may occasionally be useful to read the value of environment variables, or execute scripts, from the _remote host_ when building or starting devcontainers.  

For instance, if your devcontainer includes build scripts for deployment containers (and especially if the container was cloned into a volume, as opposed to a source mount), you will need to run them from inside the devcontainer.  Doing this requires including the docker cli in the container, mounting the docker socket, and this little bit of extra setup:

```docker
    # Add Docker group by reading in group id from file
RUN  groupadd -g ${DOCKER_GID} docker \
    && usermod -a -G docker ${USER} 
```
(this assumes that the user was added to the _hosts_ `docker` group, and that the internal UID matches the in-container UID)

There is, of course, no way currently to read variables from the remote host.

In addition, some tricks that could normally be used to retrieve these variables via `initializeCommand` (say, by separately connecting via SSH and writing the output to a file) fail in cases where the repository is being created from a volume-cloned repository (either because the command is run inside the container, or the output would be written to a container that ends up getting discarded, I'm not sure).

**Comment by chrmarti** [comment]
You are right, this is currently not possible. We use Docker's support for connecting to a remote host. One option might be to mount some file or folder on the remote host that contains the required information.

**Comment by chrmarti** [comment]
This might be covered by the recent work on https://github.com/microsoft/vscode-remote-release/issues/2994. With that the Docker CLI is run on the SSH server.
