### ISSUE TITLE
Damaged remote container setup

### ISSUE THREAD

**Issue by valhuber** [microsoft/vscode-remote-release#5658]
First, I love this feature.  It's become integral to [my project](https://github.com/valhuber/ApiLogicServer/blob/main/README.md).  If my instructions are incorrect or sb-optimal, please let me know.

I am not sure how I did this (possibly recreating a project that was already open), but I am unable to reopen a previously working project.

I open the project, and it detects the .devcontainer:
<img width="1270" alt="open - sees container" src="https://user-images.githubusercontent.com/5579631/135488472-5a6b9df3-6c2c-4c17-a691-45df22459363.png">

As usual, I say yes.  But then I get this:

<img width="1270" alt="Screen Shot 2021-09-30 at 8 33 10 AM" src="https://user-images.githubusercontent.com/5579631/135488712-98bb7b3d-65cf-4a32-b9af-36a8555ec465.png">

And it does not appear to help to "recreate the file":

<img width="1270" alt="Screen Shot 2021-09-30 at 8 33 41 AM" src="https://user-images.githubusercontent.com/5579631/135488780-4efc8fb3-513a-4387-b28d-ad0fc2cba2e0.png">

How can I recover my project?  I am happy to support a remote session to investigate.

**Comment by valhuber** [comment]
I found out how to resolve using **rebuild-container**, [posted here](https://stackoverflow.com/questions/60472084/vscode-unable-to-open-file-unable-to-read-file-message-when-clicking-on-an/69396657#69396657).

**Comment by chrmarti** [comment]
Sounds like it is working again. Closing the issue, thanks.

**Comment by valhuber** [comment]
Fair to close given workaround, but I recommend an update to the "Unable to open" message to suggest trying this.  The [SO article](https://stackoverflow.com/questions/60472084/vscode-unable-to-open-file-unable-to-read-file-message-when-clicking-on-an/69396657#69396657) has been viewed a stunning 27k times, so probably worth it...
