### ISSUE TITLE
Failing to load Python Extension in remote container

### ISSUE THREAD

**Issue by valhuber** [microsoft/vscode-remote-release#5663]
On both the PC and the Mac, [ApiLogicServer](https://github.com/valhuber/ApiLogicServer/blob/main/README.md) creates Database API projects preconfigured for remote containers, including request to pre-load Python.  It fails in a way that does not directly lead to fixing it:

<img width="1358" alt="needs-python-added" src="https://user-images.githubusercontent.com/5579631/135733173-06dfc89f-9aef-4491-84e7-2066a5e90217.png">

In spite of the message, the fix is to load:
 
<img width="1358" alt="reload-required" src="https://user-images.githubusercontent.com/5579631/135733207-5fb8c36c-71bd-4509-8407-bae94e1b1768.png">

This is a bit of a shame, since ApiLogicServer otherwise is a really great container / VSCode demo.  My TL;DR wants to be this, but I have to leave off the last few lines to avoid confusing users:

```
cd ~/dev/servers                   # directory of API Logic Server projects on local host
docker network create dev-network  # only required once (ignore errors if network already exists)

# Start (install if required) the API Logic Server docker container
docker run -it --name api_logic_server --rm --net dev-network -p 5000:5000 -p 8080:8080 -v ${PWD}:/local/servers apilogicserver/api_logic_server

ApiLogicServer create --project_name=/local/servers/docker_project 


# ideally, I would include the following:

exit  # return to local host
code docker_project  # customize, and use the launch configuration to run / debug the server
```

The project is created with the `.devcontainer.json` shown below.  

```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.194.0/containers/docker-existing-dockerfile
{
	"name": "Existing Dockerfile",

	// Sets the run context to one level up instead of the .devcontainer folder.
	"context": "..",

	// Update the 'dockerFile' property if you aren't using the standard 'Dockerfile' filename.
	"dockerFile": "../Dockerfile",

	// Set *default* container specific settings.json values on container create.
	"settings": {},

	// add network
	"runArgs": [
		"--network=dev-network",
	],

	// Add the IDs of extensions you want installed when the container is created.
	"extensions": ["ms-python.python"]

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Uncomment the next line to run commands after the container is created - for example installing curl.
	// "postCreateCommand": "apt-get update && apt-get install -y curl",

	// Uncomment when using a ptrace-based debugger like C++, Go, and Rust
	// "runArgs": [ "--cap-add=SYS_PTRACE", "--security-opt", "seccomp=unconfined" ],

	// Uncomment to use the Docker CLI from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker.
	// "mounts": [ "source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind" ],

	// Uncomment to connect as a non-root user if you've added one. See https://aka.ms/vscode-remote/containers/non-root.
	// "remoteUser": "vscode"
}
```

So, my question is

- is this a bug, or 
- am I creating the project incorrectly?

**Comment by chrmarti** [comment]
I would expect the Python extension to activate without reload. Does it work with a simple `.devcontainer.json`:
```json
{
	"image": "python:3.9-slim-bullseye",
	"extensions": ["ms-python.python"]
}
```

**Comment by valhuber** [comment]
Thanks for the quick reply - much appreciated.

Yes, the simple `.devcontainer.json` you supplied does load Python.

I have commented out most everything in mine, still failing.  I've attached the container-log, but it appears to think Python was loaded.
[container-log.txt](https://github.com/microsoft/vscode-remote-release/files/7280135/container-log.txt)

I am not sure how to diagnose this.  I am happy to participate in screen sharing (or whatever is convenient for you).

I am sure you are busy, but the steps to recreate take about a minute (using PowerShell):

```
cd ~/Desktop                                        # directory of API Logic Server projects on local host
docker network create dev-network  # only required once (ignore errors if network already exists)

# Start (install if required) the API Logic Server docker container
docker run -it --name api_logic_server --rm --net dev-network -p 5000:5000 -p 8080:8080 -v ${PWD}:/local/servers apilogicserver/api_logic_server

ApiLogicServer create --project_name=/local/servers/docker_project --db_url=

exit  # return to local host
code docker_project     # observe Python "requires reload"
```

My container seems to be working fine (both stand-alone and with VSCode), but you can see the Dockerfile used to create it [here](https://github.com/valhuber/ApiLogicServer).

I am really eager to get this to work.  I am writing an article, and want include this if possible.  I think it presents a _very_ compelling case for VSCode and the remote-container support.

**Comment by chrmarti** [comment]
I see some differences to the latest VS Code Insiders, could you retry with that? This installs side-by-side with the stable version: https://code.visualstudio.com/insiders/

**Comment by valhuber** [comment]
Excellent progress!  

After opening the project and installing the remote-container, it seemed to want to install Python (which recall is in my container).  So that's a little misleading...

It did not show the Python on the lower status bar, so I thought it failed to load:
<img width="1136" alt="python-install" src="https://user-images.githubusercontent.com/5579631/136037508-29e37ceb-d9e5-4b81-bcfc-a9d8b7cf236a.png">

But, I ignored that, and tried to run... and it worked brilliantly:

<img width="1092" alt="but-it-worked" src="https://user-images.githubusercontent.com/5579631/136037583-37fd30da-0aa9-4a30-b397-e4020a3f7a81.png">

So it might have been comforting to see Python on the status bar, but that's a nit (the offer to load Python noted above could actually send me down the wrong path).

But this is real progress.  Any idea when this is GA?

Thanks again for your help...

**Comment by sandy081** [comment]
> It seems a recommendation for Python was shown while the Python extension was being installed as part of the server startup.

Are you able to repro it? I thought this is fixed as part of this https://github.com/microsoft/vscode/issues/124119
