### ISSUE TITLE
Required a way to remove for unneeded connected targets(hosts).

### ISSUE THREAD

**Issue by EMWD** [microsoft/vscode-remote-release#5668]
Issue Type: <b>Feature Request</b>

I want to delete the connected host, for example 194. *. *. *, However there is no delete button in the interface. It is inconvenient to delete through files and configs, so you need a convenient way to do this through the interface of the extension itself.  Thanks

Extension version: 0.65.8
VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:01:43.795Z)
OS version: Linux x64 5.11.0-27-generic snap
Restricted Mode: No

**Comment by ADataGMan** [comment]
I'd really like a way to clear my remote explorer recently opened list. It doesn't seem like there's an option to do it today except clicking remove one by one on each folder?
