### ISSUE TITLE
WSL2/Docker | Attach Visual Studio Code does not attach

### ISSUE THREAD

**Issue by trysetnull** [microsoft/vscode-remote-release#5674]
Issue Type: <b>Bug</b>

# Summary
I have opened a GIT repository cloned in WSL2 debian bullseye with Visual Studio Code and have started a docker container using a Docker file which extends debian buster-backports.
The Docker extension shows that the container is running and I can use the "Attach Shell" context menu successfully.
However, when clicking on "Attach Visual Studio Code" on the running container, a notification is displayed: "Activating Extensions..." and that's it (notification is displayed for ~4 seconds)
Visual Studio Code does not open with the remote container, no errors are reported, and none of VS Code logs contain any error messages.

# Host Environment
Windows 10 10.0 version 1909 (OS Build 18363.1734)
Linux 5.4.72-microsoft-standard-WSL2 microsoft/vscode-docker#1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux
Docker version 20.10.8, build 3967b7d (docker-ce from debian-bullseye, see following)
containerd.io (1.4.11-1)
docker-ce-cli (5:20.10.9~3-0~debian-bullseye)
docker-ce-rootless-extras (5:20.10.9~3-0~debian-bullseye)
docker-ce (5:20.10.9~3-0~debian-bullseye)
Docker Compose version v2.0.1

## About | Visual Studio Code
Version: 1.60.2 (user setup)
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:00:31.514Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363

Extension version: 1.17.0
VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (16.56GB free)|
|Process Argv|--crash-reporter-id f712b328-091a-450b-ab64-8698154bea42|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|Memory (System)|24.89GB (21.60GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis400:30374798
vsaa593cf:30376535

```

</details>

**Comment by chrmarti** [comment]
@trysetnull What's in the `F1` > `Remote-Containers: Show Container Log` log?

Could you retry with VS Code Insiders (https://code.visualstudio.com/insiders/) or the upcoming VS Code 1.61? That will get you the latest Remote-Containers version containing additional fixes.

**Comment by trysetnull** [comment]
> @trysetnull What's in the `F1` > `Remote-Containers: Show Container Log` log?

With VS Code 1.60, nothing happens just the notification "Activating Extensions" is displayed, just like with the "Attach Visual Studio Code" problem above. 

> Could you retry with VS Code Insiders (https://code.visualstudio.com/insiders/) or the upcoming VS Code 1.61? That will get you the latest Remote-Containers version containing additional fixes.

After installing VS Code 1.61 plus the remote-containers and remote-development meta extensions, a message is displayed that I should download Docker Desktop for Windows. The Show Container Log has the following:

```text
[217948 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[217957 ms] findLocalWindowsExecutable: Exectuable 'docker' not found on PATH 'C:\Program Files\Google\Chrome\Application;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Users\w100168\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\JetBrains\CLion 2021.1.1\bin;;C:\Users\w100168\.dotnet\tools;C:\Users\w100168\AppData\Local\Programs\Microsoft VS Code\bin'.
[217959 ms] spawn C:\Users\<user-name>\AppData\Local\Programs\Microsoft VS Code Insiders\docker ENOENT
[217960 ms] CLI host's PATH: C:\Program Files\Google\Chrome\Application;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Users\<user-name>\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\JetBrains\CLion 2021.1.1\bin;;C:\Users\<user-name>\.dotnet\tools;C:\Users\<user-name>\AppData\Local\Programs\Microsoft VS Code\bin
```

So it would seem that the windows version of VS Code/Remote Containers extension, expects that if I'm using docker then I must have Docker Desktop for windows installed. However, I have WSL2 active and have docker installed there:
```text
$ docker --version
Docker version 20.10.8, build 3967b7d
```
Any chance that VS Code/Remote Containers extension could support my set-up?
Installing Docker Desktop for windows is not an option for me.

**Comment by trysetnull** [comment]
I activate the setting in VSCode 1.61 insiders and now have the same behaivour as v1.60 ("Activation Extensions" notification and nothing more).

The Remote-Container extension log consists of the following 2 lines:
```text
[2021-10-06T10:16:53.102Z] Start: Run: wsl -d debian
[2021-10-06T10:16:53.102Z] Remote-Containers 0.202.0 in VS Code 1.61.0-insider (71ca6e8e74591ae5c577d52a2aa1bd0c3df5ac32).
```
