### ISSUE TITLE
Need to press "Attach Visual Studio Code" twice

### ISSUE THREAD

**Issue by theUpsider** [microsoft/vscode-remote-release#5678]
Does this occur consistently? Yes
Repro steps:

1. Remote SSH via VS Code on server which has docker container running
2. Under the docker extension in the tab "containers" 
3. right click on a running container
4. select "Attach Visual Studio Code"
5. You get asked for the SSH password but nothing happens
6. You have to do steps 3 and 4 + password again

Version: 1.17.0
OS: linux
OS Release: 5.4.0-86-generic
Product: Visual Studio Code
Product Version: 1.60.2
Language: en

**Comment by chrmarti** [comment]
There is some delay between the password prompt and the list of containers to pick from (that needs to be picked again due to https://github.com/microsoft/vscode/issues/111238).

Does it work if you give it some time? If not, could you attach the log (`F1` > `Remote-Containers: Show Container Log`)?

**Comment by theUpsider** [comment]
It actually does work after a couple of seconds. The log shows the first attempt where I waited until it popped up and the second attempt at 77346 ms where I pressed it again.
The difference is that during the first time the popup menu which informs the user that the containers are being browsed, doesn't show up. This leads to the misconception that it doesn't work (immediately).

[44626 ms] Remote-Containers 0.202.4 in VS Code 1.61.1 (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63).
[44626 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[51827 ms] 1.40
[51839 ms] Start: Run: docker ps -q
[55850 ms] Start: Run: docker inspect --type container 990c6d972f5f 6271b4b3b02b bf471ef843e0 09caa2ef4f89 3244938b2cc1 334d3cc94079
[77346 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[80106 ms] 1.40
[80107 ms] Start: Run: docker ps -q
[84277 ms] Start: Run: docker inspect --type container 990c6d972f5f 6271b4b3b02b bf471ef843e0 09caa2ef4f89 3244938b2cc1 334d3cc94079

**Comment by chrmarti** [comment]
Thanks. I will shorten the delay between the two. Ideally there would be none, but these two inputs are controlled by different parts of the underlying implementation, making it difficult to remove the delay completely.

**Comment by connor4312** [comment]
Reopening per the user's report

**Comment by rzhao271** [comment]
Something else to check is whether you're on Remote - Containers v0.205.0

**Comment by theUpsider** [comment]
Im on v0.202.5

**Comment by chrmarti** [comment]
The fix is only in Remote-Containers 0.203.0 and later. (Thanks @rzhao271!)

@theUpsider Could you use VS Code Insiders (https://code.visualstudio.com/insiders/) to get the latest version of Remote-Containers (currently 0.205.0) for verification.

(Closing again for verification.)

**Comment by alexr00** [comment]
@chrmarti the flow proceeded, but I got asked which container I wanted to connect to even though I had specifically right clicked on a specific container.

**Comment by chrmarti** [comment]
Thanks, the bug that you have to pick the container from the QuickPick list after having it picked from the Docker viewlet is tracked with #4405.

**Comment by theUpsider** [comment]
The delay is noticeably shorter than before in 1.62.2. Thanks!
