### ISSUE TITLE
Running multiple devcontainers with docker-in-docker in parallel fails, need unique volume name

### ISSUE THREAD

**Issue by berndku** [microsoft/vscode-remote-release#5679]
A single devcontainer with docker-in-docker is running fine. If opening a second devcontainer with docker-in-docker on the same host in parallel, docker execution fails in the 2nd container. 

- VSCode Version: 1.60.2
- Local OS Version: Windows 10 Pro 10.0.19042
- Reproduces in: Remote - Containers 
- Name of Dev Container Definition with Issue: Docker-in-Docker

Steps to Reproduce:

1. Open devcontainer with docker-in-docker definition in first instance of VS Code
2. Run "docker ps" --> CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES --> works
3. Open a second VS Code instance and let the first VS Code Window continue to run in parallel.
3. Open a second devcontainer with a Docker-in-docker definition in the second instance of VS Code
4. Run "docker ps" --> Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
5. If closing the first VS Code instance and rebuilding the second, then docker-in-docker works on the second instance.

**Comment by Chuxel** [comment]
@chrmarti Wouldn't replacing those characters with a `-` do the trick?  That's what I've been doing for things like publishing branch specific dev container images.  For example. branch `clantz/feature-1234` becomes `clantz-feature-1234`

For that matter, we could convert the string to base64 if we had to.

**Comment by afterthought** [comment]
I want to point out that the same conflict exists for Minikube.

`      {
        "Type": "volume",
        "Source": "minikube-config",
        "Target": "/home/vscode/.minikube"
      }`

**Comment by Chuxel** [comment]
To close the loop, this is also a problem for the dev container features preview for docker-in-docker in particular as described in microsoft/vscode-dev-containers#1249. We'd want to be able to use this to give the volume a unique name to avoid it.

**Comment by stuartleeks** [comment]
@Chuxel - I've just hit this issue using the `docker-in-docker` container feature to install docker. In an [earlier comment](https://github.com/microsoft/vscode-remote-release/issues/5679#issuecomment-936270789) on this issue you mentioned changing the config. Is that possible with the `docker-in-docker` container feature?

**Comment by Chuxel** [comment]
@stuartleeks No - tho IMHO, this is one of the things we have to have to "GA" features. //cc @edgonmsft @joshspicer @chrmarti @bamurtaugh

**Comment by stuartleeks** [comment]
Is there a decision on what identifier/name should be used for the volume name? I have a couple of features I'd like to create that also need this functionality 😄

**Comment by Chuxel** [comment]
This was raised as https://github.com/devcontainers/spec/issues/62 in the dev container spec to zero in on a specific solution since it would apply to any tool implementing the specification.

**Comment by gdlol** [comment]
For those who can't wait, below is a workaround utilizing the fact that Docker Compose prepends directory name to named volumes:

Assuming an existing `.devcontainer/Dockerfile`, add the below 2 files:

- `.devcontainer/daemon.json`
  ```JSON
  {
      "data-root": "/var/lib/dind"
  }
  ```

- `.devcontainer/docker-compose.devcontainer.yml`
  ```YAML
  services:
    devcontainer:
      build:
        dockerfile: Dockerfile
      init: true
      volumes:
        - ./daemon.json:/etc/docker/daemon.json:ro
        - var-lib-dind:/var/lib/dind
        - ..:/workspace
  volumes:
    var-lib-dind:
  ```

Edit `.devcontainer/devcontainer.json`:
```JSONC
{
	// "name": ...,
	"dockerComposeFile": "docker-compose.devcontainer.yml",
	"service": "devcontainer",
	"workspaceFolder": "/workspace",
	"overrideCommand": true,
	"features": {
		"docker-in-docker": "latest",
		// ...
	},
	// ...
}
```

See
- https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/docker-in-docker.md
- https://code.visualstudio.com/docs/remote/create-dev-container#_use-docker-compose

**Comment by Chuxel** [comment]
This has been resolved in v2 of the docker-in-docker Feature for a bit now.

Update your existing references as follows:

```json
"features": {
    "ghcr.io/devcontainers/features/docker-in-docker:2": {}
}
```

However, note that this will generate a new volume name, so the existing volume will no longer be used. If you need to keep your container contents around in one container, then stick with version 1 until you are ready to switch.
