### ISSUE TITLE
click to open file location with remote wsl build task does not goto line

### ISSUE THREAD

**Issue by pwm1234** [microsoft/vscode-remote-release#568]
Issue Type: <b>Bug</b>

Follow the steps for "Developing in WSL" , https://code.visualstudio.com/docs/remote/wsl, with a build task that simply calls make in a wsl directory. When there is an error, "click-to-open" in the build task output window opens the file correctly, but it goes to the first line. It does not go to the line number indicated by the gcc error message, which is in the format absolute_path:line_number:column

I have been trying out more of the remote development capabilities in 1.35, and I have discovered the exact same behavior when following "Developing inside a Container". So this problem is not specific to WSL.  For what it is worth, I have attached my tasks.json file. 

[tasks.zip](https://github.com/microsoft/vscode-remote-release/files/3259188/tasks.zip)

Extension version: 0.38.0
VS Code version: Code - Insiders 1.35.0-insider (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T00:13:30.572Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (18.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz (8 x 2901)|
|Memory (System)|31.85GB (18.59GB free)|
|VM|0%|
</details>

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/136
