### ISSUE TITLE
Make the -T option configurable

### ISSUE THREAD

**Issue by dronl** [microsoft/vscode-remote-release#5683]
Currently the plugin will run ssh command with -T option by default:
Running script with connection command: ssh -T -o ClearAllForwardings=true -o ConnectTimeout=20

However, it may cause some issue in complicated SSH servers which PTY is not supported. (-T means disable pseudo terminal), Request for an option in settings which user could decide if -T is required

**Comment by roblourens** [comment]
Can you tell us more about servers that don't support that flag? Why not? What happens?
