### ISSUE TITLE
Failed to connect to the remote extension host server (Error: Time limit reached) SSH

### ISSUE THREAD

**Issue by xiongyt-bear** [microsoft/vscode-remote-release#5689]
🚨 The issue tracker is not for questions 🚨

When I used Remote-SSH connect remote server, I met the problem that can not fetch the remote environment and Failed to connect to the remote extension host server(Error: Time limit reached), How can I solve it ?

**Comment by tanhakabir** [comment]
Hey @xiongyt-bear! Would you be able to send us your logs for the Remote -SSH extension when you're trying to connect?
