### ISSUE TITLE
Python virtual environment not loading in WSL

### ISSUE THREAD

**Issue by draggeta** [microsoft/vscode-remote-release#569]
Selecting an interpreter works, but after clicking on it, it's not applied to vscode. It stays in the default environment. Changing to and using the venv via the shell does work without issues.

I haven't tried this outside of a workspace. I'll report back when I do.

- VSCode Version: 1.35.0-insider
- Local OS Version: Windows 10 1903
- Remote OS Version: Debian Stretch
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Configure virtual envs with `python3 -m venv ~/.virtualenvs/provider`
2. Configure remote settings.json with `"python.venvPath": "~/.virtualenvs",`
3. Restart code insiders
4. Select the virtual environment from the dropdown

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by draggeta** [comment]
After testing it seems to only happen when using a workspace of multiple folders. If I open the specific folder, everything starts correctly.

**Comment by karrtikr** [comment]
@draggeta Can you please inform if you're connecting to WSL ubuntu over SSH?

**Comment by karrtikr** [comment]
Dup of #273

**Comment by draggeta** [comment]
Sorry, didn't see the other issue when searching. However, for me it's not via SSH, but via WSL directly.

**Comment by karrtikr** [comment]
If you check the issue content, people have reported problems with both wsl and ssh, so you can close this one.
