### ISSUE TITLE
Statically forwarding ports no longer works on devcontainer

### ISSUE THREAD

**Issue by yoongkang** [microsoft/vscode-remote-release#5696]
- VSCode Version: 1.61.0
- Local OS Version: macOS Big Sur 11.6 (20G165)
- Remote OS Version: Using python:3.9-slim-buster
- Remote Extension/Connection Type: Docker
- Logs:

Steps to Reproduce:

1. Start a devcontainer based on a docker-compose file that exposes port 8000
2. Try to start a server on port 8000, it will be inaccessible. Starting a server on a different port (e.g. 5000) will automatically forward the port (i.e. ask me if I want to open in browser)

Example: https://github.com/yoongkang/portissue

I used to be able to run `python manage.py runserver` and navigate to http://127.0.0.1:8000 and it will work okay. This no longer works, but the following cases will work:

- Using `python manage.py runserver 0.0.0.0:8000` will open up the port (appears green under "Ports")
- Using `python manage.py runserver 5000` would automatically forward a port too

It's weird that only port 8000 doesn't work, when it's the only one I've explicitly exposed. This all worked up until a few days ago.

Does this issue occur when you try this locally?: Not applicable
Does this issue occur when you try this locally and all extensions are disabled?: Not applicable

**Comment by Chuxel** [comment]
//cc: @alexr00 @chrmarti

**Comment by yoongkang** [comment]
> The fact that python manage.py runserver 0.0.0.0:8000 works makes me think that python manage.py runserver 8000 only binds to the container's local interface on 127.0.0.1. So maybe the change was in the manage.py.

That would be correct, it binds to the container's local interface on `127.0.0.1`, and this has always been the behaviour IIRC (so nothing has changed recently). 

The strange thing is using `python manage.py runserver 5000` would also bind to `127.0.0.1` but this forwards the port automatically. I'd expect 8000 to also work, as it's the only one where I've specifically exposed in docker-compose (and devcontainer.json)

**Comment by Chuxel** [comment]
@chrmarti Yeah worth clarifying if the forwarding is not happening or its just on a different port.

@yoongkang If you look at the ports view, it likely specifies a different port was used in auto-forwarding re-reading your steps.  

The `forwardPorts` property in devcontainer.json can be used to forward a port which works if the application binds to localhost - but docker-compose.yaml "publishes" a port which will not work for things bound on localhost.  (This is how Docker works - not something we control.) However, if you do have 8000 declared in docker-compose.yaml and `forwardPorts` in devcontainer.json, VS Code will think port 8000 is already in use locally, and map to a different port.
