### ISSUE TITLE
git autorefresh does not work

### ISSUE THREAD

**Issue by johnbindel** [microsoft/vscode-remote-release#570]
- VSCode Version: 1.35.0-exploration
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Change local file under git repository
2. File does not appear under git tab until the refresh icon is clicked

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

I have tried setting ```"git.autorefresh": true``` locally and remotely and this does not have any impact on fixing the problem.

**Comment by joaomoreno** [comment]
Did you open the root of the repository as a folder in VS Code?

**Comment by LynnScarlett** [comment]
same problem，+1
