### ISSUE TITLE
Smart Card Authentication for SSH (PKCS11)

### ISSUE THREAD

**Issue by jordanenglish** [microsoft/vscode-remote-release#5701]
Would like to see smart card support for SSH sessions within VS Code.
https://code.visualstudio.com/docs/remote/ssh-tutorial

**Comment by roblourens** [comment]
Can you give me more details about what sort of smart card, like is there an auth method that you are already using with SSH for this, and what is it called?

**Comment by jordanenglish** [comment]
The smart card in use:
PIV type A
https://csrc.nist.gov/csrc/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp1414.pdf

Example PowerShell command to invoke SSH connection using smart card
```
& "C:\Program Files (x86)\OpenSSH-Win32\ssh.exe" 'first.last@domain.com@exampleserver' \
-I 'C:\Program Files (x86)\HID Global\ActivClient\acpkcs211.dll'
```

Which then prompts the authenticator:

![image](https://user-images.githubusercontent.com/6087717/136979402-79ea4e7a-7170-4bd9-968b-682441aec008.png)

**Comment by roblourens** [comment]
If you set up your ssh config properly to set the equivalent of the `-I` command line flag, then I'd expect this to work
