### ISSUE TITLE
Disconnects

### ISSUE THREAD

**Issue by samwez** [microsoft/vscode-remote-release#571]
Issue Type: <b>Bug</b>

everytime i open vscode it will connect to the wsl server then it disconnects and just keeps attempting to reconnect

Extension version: 0.38.0
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.4.0-17134-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17134-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|15.92GB (8.90GB free)|
|VM|0%|
</details>

**Comment by roywong10** [comment]
I also experiencing an issue like this. When I open a relatively large JSON file ( approximately 8 megabytes ), then it disconnects and just keeps attempting to reconnect and never ends.

**Comment by drdebmath** [comment]
Same issue here. Even if I open a new window of VS code in WSL, it disconnects after activating the extensions. Then it continuously tries to reconnect with no avail. I redid the same thing with all other extensions uninstalled. The problem persists.

Extension version: 0.39.2
WSL: Ubuntu 16.04
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by SanchezSobrino** [comment]
As a workaround, I just fixed it by removing the extension "Spell Right" in the WSL remote. Perhaps it's because of some problematic extension you have.

**Comment by drdebmath** [comment]
> As a workaround, I just fixed it by removing the extension "Spell Right" in the WSL remote. Perhaps it's because of some problematic extension you have.

Thanks. It worked. Since it was disconnecting really fast, I had to uninstall the extension in WSL remote as soon as it opens. Yes, I also had the Spell Right extension in WSL. Now it works fine.

**Comment by JustasDaugintis1** [comment]
Also receiving this recently. Was working with no issue previously, but now recently after working for about 10 min it disconnects and keeps trying to reconnect ...

**Comment by Smityz** [comment]
When I connect to the local virtual machine with VScode, it often disconnects , causing me to be unable to use it.

**Comment by aeschli** [comment]
I'm not able to reproduce. if you still see this, please file a new issue with details.
