### ISSUE TITLE
Unable to connect after update

### ISSUE THREAD

**Issue by jethas-bennettjones** [microsoft/vscode-remote-release#5713]
Issue Type: <b>Bug</b>

After updating Visual Studio Code, the remote SSH connection no longer works.

Extension version: 0.65.8
VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No
Fetching remote diagnostics for 'SSH' failed: The VS Code Server failed to start

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz (8 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.59GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bdev-cvd-sj01.dev.bjlocal/e%3A/dev/code/ethical-walls/BennettJones.EthicalWalls/ClientApp --crash-reporter-id 140962b7-f554-4645-8e6f-755b436f1dde|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: The VS Code Server failed to start
</details>

**Comment by jethas-bennettjones** [comment]
This seems to happen every time I update VSCode.

**Comment by tanhakabir** [comment]
Thanks for submitting the issue! Would you be able to post your Remote-SSH output channel logs when you try to connect?

**Comment by tanhakabir** [comment]
Oh sorry about the slow reply! Hmm from your logs it looks like a vscode-server issue on your remote machine. Could you try deleting the `.vscode-server` on your remote machine and try connecting again through the extension?
