### ISSUE TITLE
workspace.getWorkspaceFolder not working for URIs with upper-case drive letters

### ISSUE THREAD

**Issue by rbi** [microsoft/vscode-remote-release#5714]
- VSCode Version: 1.61.0
- Local OS Version: Ubuntu 20.04
- Remote OS Version: Windows 10 Enterprise 20H2
- Remote Extension/Connection Type: Windows OpenSSH Daemon started from a Powershell Window (not as Windows Service)
- Logs: - 

Steps to Reproduce:

1. Pass an URI `workspace.getWorkspaceFolder` which has an upper-case Windows drive letter in the `path` field of the URI. You will get `undefined` (or `null`?) even if the URI is a sub-path of a workspace folder.
2. e.g. try to use the [vscode-java-test](https://github.com/microsoft/vscode-java-test) extension to run Java test on a remote Windows machine and you will get "Failed to get workspace folder for the test items" error messages.
    - See also https://github.com/microsoft/vscode-java-test/issues/878#issuecomment-938396359

Additional Information:
* As a workaround it works to normalize the URL to have lower-case drive letters before passing it to `workspace-getWorkspaceFolder`. E.g. with this I get the [vscode-java-test](https://github.com/microsoft/vscode-java-test)  working: https://github.com/microsoft/vscode-java-test/pull/1317
* Plain-local-only Visual Studio Code had the same issue. I found the workaround here https://github.com/microsoft/vscode/issues/36221#issuecomment-337670295. The bug is fixed there and the [vscode-java-test](https://github.com/microsoft/vscode-java-test) extension is working on a local Visual Studio Code on Windows.
* Maybe the same bug got implemented a second time in the "Remote Development" version of `workspace.getWorkspaceFolder` ?

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: This bug describes a problem in the extension API.

**Comment by sandy081** [comment]
Fixed by https://github.com/microsoft/vscode/commit/d7e50f713cc2c8cb1c541c3b04a9cc2b5654432b

**Comment by alexr00** [comment]
I don't get `undefined` when my drive letter is upper-case ✔️
I do get `undefined` when my drive letter is lower-case 🐛

**Comment by sandy081** [comment]
@alexr00 Can you please provide the sample you used to verify this and also the set up you used?

**Comment by alexr00** [comment]
My setup:
- Ubuntu VM is my local machine
- Windows 11 is my remote machine
- Using Remote SSH to connect

My extension:
```ts
import * as vscode from 'vscode';
export function activate(context: vscode.ExtensionContext) {
	const disposable = vscode.commands.registerCommand('extension.helloWorld', () => {
		console.log(vscode.workspace.getWorkspaceFolder(vscode.Uri.file('c:\\Users\\alros\\Documents\\empty1\\Folder')));
	});
	context.subscriptions.push(disposable);
}
```

Steps:
1. Connect to my remote.
2. Open the folder with my extension.
3. Build and F5.
4. In my extension development host window, open the folder `C:\Users\alros\Documents\empty1`
5. In my extension development host window, run the command `extension.helloWorld`

When the drive letter is uppercase, the console log is the expected uri.
When the drive letter is lowercase, the console log is undefined.

**Comment by alexr00** [comment]
Ok, now I get the reverse:
When the drive letter is **lowercase**, the console log is the expected uri.
When the drive letter is **uppercase**, the console log is undefined.

**Comment by jrieken** [comment]
Great issue! Yes, the schemes don't under-go uri transformation because they travel as plain strings. Maybe, we should create fake transport uris so that this is tackled
