### ISSUE TITLE
remote.containers.repositoryConfigurationPaths is not used when using remote docker context for cloning into a volume

### ISSUE THREAD

**Issue by farooqu** [microsoft/vscode-remote-release#5715]
- VSCode Version: 1.61.0
- Local OS Version: Windows 11
- Remote OS Version: N/A
- Remote Extension/Connection Type: Docker and WSL

Steps to Reproduce:

1. Setup a repository configuration directory, and configure VSCode to use it
2. Create a docker context for a remote docker host
3. Clone a repository in a container volume
4. Notice that VSCode prompts to create container definition files

Does this issue occur when you try this locally?: No, when using the default local docker context the repository configuration path is used, and the correct Dockerfile is also used.
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/3708.
