### ISSUE TITLE
Don't show "The process tried to write to a nonexistent pipe"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#5723]
- Use windows
- Fail to connect with Remote-SSH for many reasons. For example, run "Connect to Host", then type "foo" which is not the name of any computer. ssh fails to connect
- See a generic error, "The process tried to write to a nonexistent pipe"
- On mac, I see "Could not resolve hostname." which is more useful

I am not entirely sure why you get this, it has something to do with trying to pipe the install script into a dead ssh process. I don't see it when entering commands in the terminal manually.

**Comment by tanhakabir** [comment]
Related to https://github.com/microsoft/vscode-remote-release/issues/5640
