### ISSUE TITLE
Container name missing first character

### ISSUE THREAD

**Issue by jecassis** [microsoft/vscode-remote-release#5725]
### Background
- VSCode Version: 1.62.0-insider (34eeebdd)
- Local OS Version: Windows 11 (22000.258)
- Remote OS Version: Linux 5.10.60.1-microsoft-standard-WSL2
- Remote Extension/Connection Type: Docker/WSL
- Logs: N/A

### Reproduction

1. Clone `vscode-remote-try-node` into WSL
2. Launch Development Container

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

### Description

In the Remote Explorer's Containers pane, the first character of the container's name is missing. The name should be `agitated_bhabha` (see included image example).

![image](https://user-images.githubusercontent.com/36133/137482845-2e0ea460-5059-4371-a229-5cc6744d7a48.png)

**Comment by chrmarti** [comment]
Fixed since. Thanks.
