### ISSUE TITLE
Provide support/hooks for checking/getting SSH Certificate before connecting to a remote host

### ISSUE THREAD

**Issue by dave-read** [microsoft/vscode-remote-release#5728]
We've starting using SSH Certificates with a 1 hour TTL for our connections to remote hosts using the Visual Studio Code Remote - SSH extension.  We have a very rudimentary custom task that we run that calls external command line tools to get/refresh the SSH Certificate.  That custom task must be run **_before_** trying to connect. 

It would be helpful to have the extension "know" (based on the presence of a ```CertificateFile``` entry in the the ssh config for the target host) that a SSH Certificate is required and ideally:
- Check that the cert is there and if so if it's still valid
- If a cert is needed, provide a hook point for calling out to an external tool to get/refresh the token

There's are several Open Source tools/frameworks for requesting SSH Certificates.  We are currently using [Preview: Login to a Linux virtual machine in Azure with Azure Active Directory using: SSH certificate-based authentication](https://docs.microsoft.com/en-us/azure/active-directory/devices/howto-vm-sign-in-azure-ad-linux) so for us the callout would be to the azure CLI to fetch a SSH Certificate for the public key associated with the target host. e.g. ```az ssh cert -p $targetHost.publicKeyPath```.  A generic set of callouts to external tools/scripts during the connect process might support this.

**Comment by roblourens** [comment]
Will close for the more general request, https://github.com/microsoft/vscode-remote-release/issues/6835
