### ISSUE TITLE
Support command-line pinentry for GPG

### ISSUE THREAD

**Issue by dave-holland** [microsoft/vscode-remote-release#5730]
Currently if the host doesn't have a graphical `pinentry`, signing with `gpg` in the container will lead to an error:

```
gpg: signing failed: No such file or directory
```
and `git commit -S` will give:
```
error: gpg failed to sign the data
fatal: failed to write commit object
```

As mentioned by @chrmarti in https://github.com/microsoft/vscode-remote-release/issues/3168#issuecomment-654637826: 

> Make sure you have a graphical pinentry program setup on Mac/Windows (console pinentry wouldn't work).

The same behavior is also mentioned in https://github.com/microsoft/vscode-remote-release/issues/5527.

---

It can be solved by installing a graphical `pinentry` on the host.

Here are some things I learned along the way, so that people facing the same problems can see before the issue is closed:

- Run `gpgconf` to see all GPG components and their paths
- Run `gpgconf --launch all` on the host to make sure the Remote Containers extension detects it
- Run `echo some_text | gpg --clear-sign` as a convenient way to check if `gpg` is working correctly
- Run `gpg --list-keys` to see if the keys exist
- Run `gpgconf --list-config` to see the configuration file. They are normally `gpgconf.conf` and/or `gpg-agent.conf`.\
    However, they are not automatically created when you install GPG.\
    If you need to change configs, run `gpgconf --list-config`, and create the file shown in the output.

For macOS users:

- [`gnupg`](https://formulae.brew.sh/formula/gnupg) on Homebrew doesn't have a graphical `pinentry`.
- [GPG Tools](https://gpgtools.org/) aka [GPG Suite on Homebrew](https://formulae.brew.sh/cask/gpg-suite-pinentry) does have a graphical `pinentry`. However, it's a real pain using it. 
    - The suite is installed at `/usr/local/MacGPG2`, and it occurred to me once that it's not in `PATH`. When it happens, commands like`gpgconf` and `gpg-agent` don't work. \
      You can add it to `PATH` by putting `export PATH=$PATH:/usr/local/MacGPG2/bin` in your shell profile, which is `~/.zshrc` for macOS 11/12.
    - GPG Tools also doesn't launch `gpg-agent`, etc. on startup, so the Remote Containers extension can't detect GPG on the host machine. \
      You can add `"initializeCommand": "gpgconf --launch all"` in your `devcontainer.json` to make sure it's running every time the container starts.

If Remote Containers supports command-line pinentry, there wouldn't be so much hassle; a good old `gnupg` package would be enough.

**Comment by chrmarti** [comment]
https://www.gnupg.org/documentation/manuals/gnupg-devel/Invoking-GPG_002dAGENT.html mentions setting `GPG_TTY` when starting the gpg-agent. Have you tried that?
