### ISSUE TITLE
Remote SSH CPU spike to 100% and uses a lot of memory with large projects

### ISSUE THREAD

**Issue by variantf** [microsoft/vscode-remote-release#5733]
- VSCode Version:
Version: 1.61.1 (Universal)
Commit: c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
Date: 2021-10-14T01:23:30.274Z (4 days ago)
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.4.0

- Local OS Version: Mac OS 11.3.1
- Remote OS Version: Linux Ubuntu 20.04.2
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

I've no idea about how to exactly reproduce the error. Just open a large project from remote host, after a while, you will see the node takes about 10GB memory and CPU runs over 100%

![image](https://user-images.githubusercontent.com/2265407/137684198-94d419de-fff6-4cec-b35f-0c0d2df2e83a.png)

**Comment by tanhakabir** [comment]
We've seen issues in the past with large workspaces: https://github.com/microsoft/vscode-remote-release/issues/1257. I'm thinking there's some correlation of this issue with that one

**Comment by roblourens** [comment]
Please share the full command line of that project. Do you have any remote extensions installed? Does it help if you disable them?

**Comment by roblourens** [comment]
That is the watcherService process @bpasero

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by variantf** [comment]
@bpasero I've upgrade to 1.61.2 and this issue seems disappeared. Thank you for the help. I'll reopen this ticket if I see the same scenario in the futures.

**Comment by variantf** [comment]
@bpasero Hi the same scenario appears again! This time, I found it has strong relation with golang extension. Both CPU/Memory usage increased quickly when I editing .go files.  

Any suggestions to debug this error or where can I found more detailed logs?


here's version info:
Version: 1.62.2 (Universal)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:59:05.913Z (1 wk ago)
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.4.0

**Comment by variantf** [comment]
Here's some error logs from go extension, but I have no idea why this happened and why this will affect ssh-remote itself.

![image](https://user-images.githubusercontent.com/2265407/143170884-0bd8657c-150a-4572-a0b9-9c33644de867.png)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by variantf** [comment]
thank you @bpasero , I think it's an issue from the go extension. I'll file another tick there!
