### ISSUE TITLE
VS Code Server for WSL closed unexpectedly

### ISSUE THREAD

**Issue by git-zjx** [microsoft/vscode-remote-release#5734]
![image](https://user-images.githubusercontent.com/24617415/137093299-d431d1e3-9f1d-42f0-ba91-375c036693b7.png)

**Comment by git-zjx** [comment]
> @git-zjx I wonder if this problem is specific to using VS Code with a translated language. Does the problem reproduce when switching VS Code to English?

I tried it and the result was the same
![image](https://user-images.githubusercontent.com/24617415/137834319-2f87c2e3-a829-444b-b077-fc6140566ded.png)

**Comment by aeschli** [comment]
Maybe the final double quote was missing?

**Comment by aeschli** [comment]
Strange. Can you tell me what this translates to?
![image](https://user-images.githubusercontent.com/6461412/137915801-0143b560-b517-4881-bc83-711aea7787d2.png)

**Comment by git-zjx** [comment]
> Strange. Can you tell me what this translates to? ![image](https://user-images.githubusercontent.com/6461412/137915801-0143b560-b517-4881-bc83-711aea7787d2.png)

The remote host was forced to close an existing connection

**Comment by aeschli** [comment]
Do you still see this issue?
