### ISSUE TITLE
[Remote-SSH] Uninstall remote server command doesn't delete remote server

### ISSUE THREAD

**Issue by Reanmachine** [microsoft/vscode-remote-release#575]
Issue Type: <b>Bug</b>

I've been trying to debug why I might be experiencing #246 and I wanted to remove the vscode server (possibly tainted from insiders build) from my remote server.

By using the CTRL+SHIFT+P -> Uninstall SSH-Remote on server it prompts me to log into my machine, and then does nothing. It seems like it only does the `uname` command to figure out what to do then stops.

**Log (Extension Host)**

> [2019-06-05 22:23:37.032] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-ssh {"startup":false,"activationEvent":"onCommand:opensshremotes.cleanDevBox"}
[2019-06-05 22:23:37.032] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\aren\.vscode\extensions\ms-vscode-remote.remote-ssh-0.42.0\out\extension

**Remote - SSH Log**

> Picking SSH host
> Selected dev
> Confirming that dev is a valid reachable host
> Running type "C:\Users\aren\AppData\Local\Temp\vscode-linux-multi-line-command-dev.sh" | > ssh  "dev" bash to confirm the host platform
> 
> warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
> 
> aren@toudai's password:
> 
> 
> 
> Linux x86_64
> 
> "uname" terminal command done

Extension version: 0.42.0
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600X Six-Core Processor            (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (17.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
It doesn't log or confirm that it did anything but it should kill the server processes and remove `~/.vscode-server-insiders`.

**Comment by Reanmachine** [comment]
Hrm, it doesn't seem to do anything either. Perhaps it shuts down the server, but all the files remain:

<details>
<summary>Before Uninstall Command Issued:</summary>

```
a@toudai  ~  ls -la .vscode*
.vscode-remote:
total 48
drwxrwxr-x  5 aren aren 4096 May 27 23:32 ./
drwxr-xr-x 38 aren aren 4096 Jun  8 00:48 ../
-rw-rw-r--  1 aren aren 1295 May 31 03:06 .16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9.log
-rw-rw-r--  1 aren aren 3934 May  7 01:30 .473af338e1bd9ad4d9853933da1cd9d5d9e07dc9.log
-rw-rw-r--  1 aren aren  550 May 24 02:09 .4ca38ce5584d7cd67b435b3c32ef1240c6a29628.log
-rw-rw-r--  1 aren aren  476 May 16 03:10 .57b550c559b945eb9d871dbf2b2e4cb9e31e2551.log
-rw-rw-r--  1 aren aren  476 May 27 23:27 .94f7de61ece171f4390ece488a220d22cbb0fddd.log
drwxrwxr-x  9 aren aren 4096 May 27 23:32 bin/
-rw-rw-r--  1 aren aren 1493 May 11 01:58 .daf71423252a707b8e396e8afa8102b717f8213b.log
drwxrwxr-x  5 aren aren 4096 May  3 01:51 data/
-rw-rw-r--  1 aren aren  513 May 17 02:01 .e83e24a0c9225becd7341e56952177a20d5d4629.log
drwxrwxr-x  5 aren aren 4096 May 30 23:33 extensions/

.vscode-server:
total 24
drwxrwxr-x  5 aren aren 4096 Jun  5 21:50 ./
drwxr-xr-x 38 aren aren 4096 Jun  8 00:48 ../
-rw-rw-r--  1 aren aren 1121 Jun 12 07:31 .553cfb2c2205db5f15f3ee8395bbd5cf066d357d.log
drwxrwxr-x  3 aren aren 4096 Jun  5 21:50 bin/
drwxrwxr-x  5 aren aren 4096 Jun  5 22:18 data/
drwxrwxr-x  3 aren aren 4096 Jun  8 02:04 extensions/

.vscode-server-insiders:
total 24
drwxrwxr-x  5 aren aren 4096 Jun  1 12:32 ./
drwxr-xr-x 38 aren aren 4096 Jun  8 00:48 ../
-rw-rw-r--  1 aren aren 1744 Jun  8 02:03 .0284236851a94b116f468345f6e98688a737015d.log
drwxrwxr-x  3 aren aren 4096 Jun  1 12:31 bin/
drwxrwxr-x  5 aren aren 4096 Jun  1 12:31 data/
drwxrwxr-x  4 aren aren 4096 Jun  4 22:55 extensions/

.vscode-server-oss:
total 24
drwxrwxr-x  5 aren aren 4096 Jun  1 12:30 ./
drwxr-xr-x 38 aren aren 4096 Jun  8 00:48 ../
-rw-rw-r--  1 aren aren  385 Jun  8 02:03 .94f7de61ece171f4390ece488a220d22cbb0fddd.log
drwxrwxr-x  3 aren aren 4096 Jun  1 12:30 bin/
drwxrwxr-x  5 aren aren 4096 Jun  1 12:30 data/
drwxrwxr-x  3 aren aren 4096 Jun  1 12:30 extensions/
```

</details>

<details>
<summary>Before Uninstall Command Issued:</summary>

```
 a@toudai  ~  ls -la .vscode*
.vscode-remote:
total 48
drwxrwxr-x  5 aren aren 4096 May 27 23:32 ./
drwxr-xr-x 38 aren aren 4096 Jun  8 00:48 ../
-rw-rw-r--  1 aren aren 1295 May 31 03:06 .16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9.log
-rw-rw-r--  1 aren aren 3934 May  7 01:30 .473af338e1bd9ad4d9853933da1cd9d5d9e07dc9.log
-rw-rw-r--  1 aren aren  550 May 24 02:09 .4ca38ce5584d7cd67b435b3c32ef1240c6a29628.log
-rw-rw-r--  1 aren aren  476 May 16 03:10 .57b550c559b945eb9d871dbf2b2e4cb9e31e2551.log
-rw-rw-r--  1 aren aren  476 May 27 23:27 .94f7de61ece171f4390ece488a220d22cbb0fddd.log
drwxrwxr-x  9 aren aren 4096 May 27 23:32 bin/
-rw-rw-r--  1 aren aren 1493 May 11 01:58 .daf71423252a707b8e396e8afa8102b717f8213b.log
drwxrwxr-x  5 aren aren 4096 May  3 01:51 data/
-rw-rw-r--  1 aren aren  513 May 17 02:01 .e83e24a0c9225becd7341e56952177a20d5d4629.log
drwxrwxr-x  5 aren aren 4096 May 30 23:33 extensions/

.vscode-server:
total 24
drwxrwxr-x  5 aren aren 4096 Jun  5 21:50 ./
drwxr-xr-x 38 aren aren 4096 Jun  8 00:48 ../
-rw-rw-r--  1 aren aren 1121 Jun 12 07:31 .553cfb2c2205db5f15f3ee8395bbd5cf066d357d.log
drwxrwxr-x  3 aren aren 4096 Jun  5 21:50 bin/
drwxrwxr-x  5 aren aren 4096 Jun  5 22:18 data/
drwxrwxr-x  3 aren aren 4096 Jun  8 02:04 extensions/

.vscode-server-insiders:
total 24
drwxrwxr-x  5 aren aren 4096 Jun  1 12:32 ./
drwxr-xr-x 38 aren aren 4096 Jun  8 00:48 ../
-rw-rw-r--  1 aren aren 1744 Jun  8 02:03 .0284236851a94b116f468345f6e98688a737015d.log
drwxrwxr-x  3 aren aren 4096 Jun  1 12:31 bin/
drwxrwxr-x  5 aren aren 4096 Jun  1 12:31 data/
drwxrwxr-x  4 aren aren 4096 Jun  4 22:55 extensions/

.vscode-server-oss:
total 24
drwxrwxr-x  5 aren aren 4096 Jun  1 12:30 ./
drwxr-xr-x 38 aren aren 4096 Jun  8 00:48 ../
-rw-rw-r--  1 aren aren  385 Jun  8 02:03 .94f7de61ece171f4390ece488a220d22cbb0fddd.log
drwxrwxr-x  3 aren aren 4096 Jun  1 12:30 bin/
drwxrwxr-x  5 aren aren 4096 Jun  1 12:30 data/
drwxrwxr-x  3 aren aren 4096 Jun  1 12:30 extensions/
```

</details>

I also know something is up because when I connect back to the server afterwards, the install process is skipped and all my remote extensions and settings are there.

My default shell is `fish`, I was affected by #33 incase this may be related.

**Comment by roblourens** [comment]
That's weird, did it kill the server processes at least? You can try `ps ax | grep server.sh`

**Comment by Reanmachine** [comment]
Unfortunately no:

```
 a@toudai  ~  ps ax | grep server.sh
16000 pts/0    S+     0:00 grep --color=auto server.sh
24056 ?        S      0:00 sh /home/aren/.vscode-server/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/server.sh --port=0
 a@toudai  ~  ps ax | grep server.sh
16083 pts/0    S+     0:00 grep --color=auto server.sh
24056 ?        S      0:00 sh /home/aren/.vscode-server/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/server.sh --port=0
```

**Comment by roblourens** [comment]
I guess I'll add some logging that you can try in tomorrow's nightly extension build

**Comment by roblourens** [comment]
Well I log the command now at least and you can check whether anything else in the nightly build has fixed your issue, there have been many fixes.

**Comment by Reanmachine** [comment]
@roblourens Hrm, latest nightly seems to work... although, I can't tell if it's the same one as the one I tested ~5 hours ago...

```
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
> 
> Enter passphrase for key 'c:\Users\aren\.ssh\id_rsa':
> 
> 
> kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
> 
> kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
> kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
> 
> kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
> 
"Uninstall VS Code Server" terminal command done
```
a@toudai  ~  ps ax | grep server.sh
18072 pts/0    S+     0:00 grep --color=auto server.sh
 a@toudai  ~  ls -la .vscode*
total 12
drwxrwxr-x  3 aren aren 4096 Apr  6 21:34 ./
drwxr-xr-x 34 aren aren 4096 Jun 12 21:36 ../
drwxrwxr-x  5 aren aren 4096 May  1 00:14 extensions/
 a@toudai  ~ 
```

‾\_(ツ)_/‾ Not sure what to say, I guess it's fixed?

**Comment by roblourens** [comment]
Hm, let me know if you have any other issues
