### ISSUE TITLE
Support vscode.dev (Web Extension)

### ISSUE THREAD

**Issue by jimpowelldev** [microsoft/vscode-remote-release#5750]
Honestly not sure if using SSH in the browser is a possibility, but allowing Remote - SSH to run in the browser would be a game changer. If you're already running on a remote development environment, this would allow you have a fully cloud-based dev stack with nothing to install/maintain, etc.

**Comment by hcyang99** [comment]
I am using [cdr/code-server](https://github.com/cdr/code-server) for now, does pretty much the same thing. Just that you need to deploy the code-server onto your remote machine. Not all extensions are available, but there are more than [vscode.dev](vscode.dev).

**Comment by tanhakabir** [comment]
Hey everyone, thanks for your interest and feedback!

We're happy to share that we just released a private preview service called the Visual Studio Code Server. The VS Code Server is a service you can run on a remote development machine, like your desktop PC or a virtual machine. It allows you to securely connect to that remote machine from anywhere through vscode.dev and doesn't need SSH.

You can learn more in the announcement [blog post](https://aka.ms/vscode-server-blog) and [docs](https://aka.ms/vscode-server-doc). There's also a link in that blog to sign up for the private preview with your GitHub alias.

**Comment by varanauskas** [comment]
Great news! There is one thing I seem to be missing from the release, is there any way to forward the ports manually? I want to run `code-server` on my Raspberry Pi, and access it on my iPad without network connection to `vscode.dev`

**Comment by tamird** [comment]
@tanhakabir it looks like it was once possible to run VS Code Server with `--serve-local`, serving the same need as https://github.com/coder/code-server. That option appears to be gone, and now there's no way to use VS Code Web (https://vscode.dev/) for remote development *without* VS Code Remote Tunnels.

This comes up when the local machine is running ChromeOS (can't use the VSCode SSH extension). Are there any plans to bring back something like `--serve-local`? That would allow VS Code Server to displace https://github.com/coder/code-server using SSH port forwarding (which *is* available on ChromeOS).

**Comment by AlsoBearPerson** [comment]
I'm also coming here for ChromeOS, via a slightly different direction: While the recommended method of installing vscode as a native crostini app works, that introduces small but noticeable UI lag, particularly when scrolling, compared to `vscode.dev` running in the main chrome browser. Running `code tunnel` in crostini provides this, but needlessly bounces the connection from the machine to itself through the cloud.

Implementing any of

* SSH remote support in the browser (there is [a pure webasm implementation](https://chromium.googlesource.com/apps/libapps/+/refs/heads/main/wassh/) of an ssh client that ChromeOS uses elsewhere, though this might be relying on subtle chrome APIs at the moment, pending progress on WICG/direct-sockets)
* Direct tunnel connections to localhost without cloud indirection
* Resurrecting `--serve-local`

would allow for an improved experience in ChromeOS: Perfect scrolling in the main browser, development environment in crostini, and local development that still works while offline, potentially depending on the `vscode.dev` PWA being loaded for offline use.

**Comment by lattice0** [comment]
What about dev containers on vscode.dev?

**Comment by sroener** [comment]
This should  be solved with the implementation of https://github.com/microsoft/vscode/pull/191014  ?!
Can the issue be closed?

@roblourens 
@jimpowelldev

**Comment by roblourens** [comment]
I think the original request here implied something slightly different, but I'd say that the use case is satisfied now.
