### ISSUE TITLE
Can't connect to hostx: unreachable or not Linux x86_64 ( * Error: Problem adding; giving up)

### ISSUE THREAD

**Issue by tcuze** [microsoft/vscode-remote-release#577]
- VSCode Version:  1.35.0 (user setup)
- Local OS Version: Windows_NT x64 10.0.17134
- Remote OS Version: Linux
- Remote Extension/Connection Type: SSH

Does this issue occur when you try this locally?: Yes
my ssh config is 
```
Host xx
    HostName uu
    User uu
    IdentitiesOnly no
    PubkeyAuthentication no
    PreferredAuthentications keyboard-interactive
    AddKeysToAgent no
    ServerAliveInterval 10
    LogLevel FATAL
    ForwardAgent yes
```
when i use ssh client to connect the host，i also get the error ( Error: Problem adding; giving up), but connected successfully

**Comment by jberardo** [comment]
I am having the same issue. I can connect normally via terminal, but when I try to use the extension I get this error.

Details:
- VSCode Version: 1.35.0
- Local OS Version: Darwin x64 18.6.0
- Kernel Version 18.6.0
- Remote OS Version: Linux (Ubuntu kernel  4.15.0-51-generic)
- Remote Extension/Connection Type: Remote-SSH

My ssh config:
```
Host xx
  HostName xx
  User xx
  IdentityFile ~/.ssh/xx
  IdentitiesOnly yes
```

**Comment by roblourens** [comment]
Is this still an issue? You will probably have to set the setting `remote.SSH.showLoginTerminal` for keyboard-interactive auth.
