### ISSUE TITLE
WSL+Containers: Allow selection of an alternate distro for docker commands

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#5774]
Remote - Containers now supports a mode where all CLI commands can be set to run directly inside of WSL by updating the **Execute in WSL** setting.

However, it can be useful to select a different WSL named "distro" for containers other than the WSL default. In particular, given running Docker or Podman directly in WSL does not ensure the same security boundary as running in a VM, using a separate WSL instance can provide the same advantages (which is why Docker Desktop also uses a separate distro). 

As a result, it would be useful to have a VS Code setting that allowed you to pick a different default specifically for use in Remote - Containers.

**Comment by chrmarti** [comment]
Makes sense. As a side-note: When using a folder inside a WSL distro we use that distro to run the Docker / Compose CLIs (actually have to because that folder is usually not available in other distros).

**Comment by alkatar21** [comment]
I have my problem right here.
I am using Docker Desktop with WSL2 backend and a WSL distro for everything related to docker and have set it in Docker Desktop settings at `Enable integration with additional distros`.
For reasons my default WSL has to be a WSL1. The option `"remote.containers.executeInWSL"` now tries to use the default WSL 1 distro instead of one configured in Docker Desktop. It would be nice if this could be changed or it would at least be configurable.

**Comment by rzhao271** [comment]
@chrmarti What are some steps to verify this issue? I tried changing `remote.containers.executeInWSLDistro` to `docker-desktop` and `remote.containers.executeInWSL` to `true` while in the vscode repo, but I'm not sure what output to expect.

**Comment by chrmarti** [comment]
`docker-desktop` is a special-purpose distro from Docker Desktop, not sure if that can be used like a normal distro.

Please try the following steps:
- Make sure you are using WSL 2: `wsl --set-default-version 2`
- Install a second (regular) distro, e.g., Debian from the Windows Store.
- Make sure this is not the default distro: `wsl -l -v` (The default is marked with `*`.)
- Enable Docker support for this distro. (See screenshot below.)
- Set `remote.containers.executeInWSLDistro` to this distro and `remote.containers.executeInWSL` to `true`.
- Start a container: `docker run -d alpine sleep inf`
- Run the `Remote-Containers: Attach to Running Container...` command to attach to that container.
- Verify in the log (`Remote-Containers: Show Container Log`) that the new distro was used to run the Docker commands. (Check at the top of the log, the commands should mention the distro like `wsl -d <distro> ...`.)

![image (2)](https://user-images.githubusercontent.com/9205389/151379170-d1472c23-18fc-4a49-a9bd-d4a536354d4a.png)

**Comment by rzhao271** [comment]
I had to use the show all logs command, because the current log seemed to be cut off for me, but I confirmed that it works.
