### ISSUE TITLE
Review IsWindowsFilePathHeuristic fix with WSL

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#5775]
The fix for https://github.com/microsoft/vssaas-planning/issues/5628 suggests that we are using a FileHost for the workspace's filesystem when we want to access the built-in features files. WSL has a similar setup, there might be a more targeted fix for this issue.

**Comment by rchiodo** [comment]
@chrmarti can you provide some verification steps? Thanks.
