### ISSUE TITLE
Include elevation in port restore

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#5776]
Current behavior (only in codespaces since that's the only remote that uses elevation):
1. Forward a port that requires elevation
2. Provide elevation
3. ✔ port is forwarded using the privileged local port
4. Reload
5. ❌ privileged local port is not restored

To fix step 5, we should store and restore whether a port should ask for elevation.

**Comment by alexr00** [comment]
This must be verified with the test resolver as there is another issue with Codespaces. To verify:
1. Use a linux OS. 
2. Run the test resolver (you can build from source, then open the extensions/vscode-test-resolver folder and F5.
3. Forward a port < 1000.
4. Verify that you get a fake elevation prompt and that a port within 1 number of your original was used as the local address
5. Reload. Verify that you get another fake elevation prompt and the same local port number is used.

**Comment by roblourens** [comment]
I get a fake elevation prompt, but a larger port as the local address

![image](https://user-images.githubusercontent.com/323878/144170207-5525acd0-24c4-4ca6-8d37-9557d6e59d3b.png)

**Comment by alexr00** [comment]
It looks like this cannot be verified at this time. Moving to December to try to verify with Codespaces later.

**Comment by alexr00** [comment]
This must be verified with Codespaces desktop with linux. To verify, follow the original steps: https://github.com/microsoft/vscode-remote-release/issues/5776#issue-1036016114
