### ISSUE TITLE
linux dev container on windows incorrect core.filemode

### ISSUE THREAD

**Issue by agowa338** [microsoft/vscode-remote-release#5777]
Does this issue occur when all extensions are disabled?: No, dev containers don't work then...

- VS Code Version: 1.61.2
- OS Version: Windows_NT x64 10.0.22478

Steps to Reproduce:

1. Create a new project with any Linux dev container (e.g. the python3 template) on a Windows host with docker.
2. Run `git config core.filemode` inside the dev container.

The 2nd command should return true as we're now on a file system that supports executable bits. But it appears to be inherited from the window host as `false`, which causes problems with executable bits being written into the git index.

**Comment by chrmarti** [comment]
On the executable bit: There might be some translation going on in the support for mounting a Windows filesystem in a Linux container. The cloned repository resides on the Windows filesystem, using the mentioned 'Clone in Volume' command or using a folder in a WSL distro would allow you to use a Linux filesystem for the repository.

Closing this issue as this is a limitation inherent to the setup you are using and there are other options (volume or WSL) available. Thanks.
