### ISSUE TITLE
TIP: Programmatically ensure Dockerfile is built by VScode

### ISSUE THREAD

**Issue by fyyyyy** [microsoft/vscode-remote-release#5779]
We recently had the issue that a user tried to build the .devcontainer/Dockerfile manually with docker and was expecting this to work. To handle this error i added following:

In your Dockerfile:

```Dockerfile
# Ensure this docker file is built by VScode.
# Manual / user build of this Dockerfile is NOT supported.
ARG vscode
RUN if [[ -z "$vscode" ]] ; then printf "\nERROR: This Dockerfile NEEDS to be built with VScode !" && exit 1; else printf "VScode is detected: $vscode"; fi
```

In devcontainer.json:

```json
    "build": {
      "dockerfile": "Dockerfile",
      "args": {
          // set vscode arg for Dockerfile
          "vscode": "true"
      },
    },
```

**Comment by bamurtaugh** [comment]
Thanks again @fyyyyy! This change has been merged in https://github.com/microsoft/vscode-docs/pull/4920, so going to close this issue.
