### ISSUE TITLE
Not able to close VSCode if the SSH connection drops

### ISSUE THREAD

**Issue by gauravmahto** [microsoft/vscode-remote-release#578]
- VSCode Version: 1.35.0 (user setup)
- Local OS Version: Win10 x64 Pro
- Remote OS Version: WSL Ubuntu 18.10
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to a remote machine using SSH.
2. If the SSH connection drops due to some network issue. VSCode won't let you close the window and always remain in a hung state. The only way to close the VS Code is to kill the 'code.exe' process.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No
![Annotation 2019-06-06 150855](https://user-images.githubusercontent.com/3089767/59023299-21b78980-886d-11e9-9a26-53dc65c5b7b0.png)

**Comment by roblourens** [comment]
Are you still seeing this issue? Can you share the log from the "Remote - SSH" output channel when this happens?

**Comment by gauravmahto** [comment]
I tried to reproduce this scenario by forcefully shutting down the ssh service on the remote host and seems like now I'm not able to reproduce this issue. I'm closing this for now.

Thanks!
