### ISSUE TITLE
Remote SSH stops working if current window is closed 

### ISSUE THREAD

**Issue by arsalansiddique1** [microsoft/vscode-remote-release#5781]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

1) Open SSH in current window 
2) Open folder from host on the remote SSH window
3)Close The VS code SSH window 
4) Open a new VS Code window and try ro conect to host and open same folder

Problem:
Folder is unable to be opened when steps carried out indicating a mess up of the working SSH setup and SSH is no longer able to connect to remote host unless 'Kill vs-code server on host is used'.

Only current solution is to 'Close remote connection' in current window to keep SSH setup intact. Expected solution should allow user to cross vs code window but keep the SSH setup intact. A solution could possibly be to initate a close remote connection if the user crosses the current window. 

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-80-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (5.54GB free)|
|Process Argv|--crash-reporter-id 748dd135-d823-4c12-9bd1-6effb49067bf|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: DICE|
|OS|Linux x64 5.4.0-80-generic|
|CPUs|AMD EPYC 7302 16-Core Processor (64 x 3292)|
|Memory (System)|503.57GB (148.00GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.3
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.2
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593:30376534
vssld246:30386377
vscrecpromptt3:30387013

```

</details>

**Comment by roblourens** [comment]
Ok, it sounds like as long as you leave some ssh connection open, then you can open a new remote window, but once they have all closed you connect but get permission errors from the remote. I'm wondering if your remote has some setup where you connect as a different user, or to a different node, or something else is different if you have not logged in recently. Maybe there is some cleanup process on the remote that breaks us. You might ask your system administrator about it.

**Comment by arsalansiddique1** [comment]
Yeah quite possibly could be due to the weird setup of my uni's remote server. It connects to a jump page and then another ssh command is used to connect to the cluster of servers I want. I'll just use the workarounds I found for now, thanks.
