### ISSUE TITLE
busy ripgrep process when opening wsl on a root folder

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#5784]
- Open a WSL window on the root folder `/` on a WSL1 distro (Ubuntu 18.04)
- open `htop` and see that that there a process running, consuming around 10% of the CPU. It doesn't seem to terminate (or is called repeatetly?)

![recording (1)](https://user-images.githubusercontent.com/6461412/139024990-43084d8e-680e-4281-b415-55d63f9e947a.gif)

`/home/aeschli/.vscode-server-insiders/bin/dc1a6699060423b8c4d2ced736ad70195378fddf/node_modules/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g /.devcontainer/devcont
ainer.json -g /.devcontainer.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/Thumbs.db -g !**/node_modules -g !**/bower_components -g !**/*.code-search --no-ignore-parent --follow --quiet --no-config --no-ignore-global`

**Comment by roblourens** [comment]
Still an issue?

`-g /.devcontainer/devcontainer.json` Seems that it could have been triggered by the remote-containers extension
