### ISSUE TITLE
Substitute environment variables from ssh connected Docker host

### ISSUE THREAD

**Issue by max06** [microsoft/vscode-remote-release#5787]
- VSCode Version: 1.61.2
- Local OS Version: Win11
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

**Attention:** This is a docker remote setup running on different hosts. The remote host (linux) is configured as a docker context in the cli (windows). This is **not** docker desktop.

1. Have a `devcontainer.json` configuration containing something like 

```json
	"mounts": [
	 	"source=${localEnv:HOME}${localEnv:USERPROFILE}/.config/openstack/clouds.yaml,target=/root/.config/openstack/clouds.yaml,type=bind,consistency=cached"
	],
```

2. Launch Container and see error 

```
[22766 ms] Remote-Containers server terminated (code: 137, signal: null).
docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: 'C:/Users/max06/.config/openstack/clouds.yaml' mount path must be absolute.
```

Despite having the file available on the linux docker host, this should be a linux path.

**Comment by chrmarti** [comment]
Connecting to the SSH server with Remote-SSH and then using Dev Containers gives you the requested functionality.
