### ISSUE TITLE
DevContainers: code-command unavailable in PostAttachCommand 

### ISSUE THREAD

**Issue by max06** [microsoft/vscode-remote-release#5788]
- VSCode Version: 1.61.2
- Local OS Version: Win11
- Remote OS Version: Debian 11 (Container)
- Remote Extension/Connection Type: Docker

Since mounts are rather suboptimal in some system configurations I tried to find another solution for having app specific config files. This attempt includes a mounted volume (for persistence across rebuilds) and a `postAttachCommand`-trigger asking the user for the config content (later: if it doesn't exist).

Steps to Reproduce:

1. Have a `devcontainer.json`-configuration containing

```json
	"postAttachCommand": "code --wait /root/.config/openstack/clouds.yaml",
```

2. Rebuild/Relaunch the container. A wild error appears:

```
[51322 ms] 
Running the postAttachCommand from devcontainer.json...

[51324 ms] Start: Run in container: /bin/sh -c code --wait /root/.config/openstack/clouds.yaml
code or code-insiders is not installed
[53316 ms] Error: Command failed: /bin/sh -c code --wait /root/.config/openstack/clouds.yaml
        at Qy (c:\Users\max06\.vscode\extensions\ms-vscode-remote.remote-containers-0.202.5\dist\extension\extension.js:296:15)
        at async c6 (c:\Users\max06\.vscode\extensions\ms-vscode-remote.remote-containers-0.202.5\dist\extension\extension.js:289:3069)
        at async c:\Users\max06\.vscode\extensions\ms-vscode-remote.remote-containers-0.202.5\dist\extension\extension.js:271:8669
```

What's the proper way to do something like this?

**Comment by VikramAIS** [comment]
Is there any possibility to run the code command from postStart/Create command?

I have requirement where open the devcontainer, then immediately open the new folder from devcontainer.

Thanks,
Vikram

**Comment by chrmarti** [comment]
@VikramAIS It is the same for the other commands in the devcontainer.json. (VS Code might not have connected to the container when they run.)
