### ISSUE TITLE
Remote Container (Docker) rebuild needed after VSCode relaunch

### ISSUE THREAD

**Issue by DHOFM** [microsoft/vscode-remote-release#5796]
Hi,
VSCode is 
Version: 1.61.2

OS: Mac OS

I use a remote container, built from Dockerfile with Python. Works Fine until relaunch. After relaunch custom libraries like tensorflow are not found by VSCode. After rebuild everything works again. Logging into the running container via shell and using Python in the container the Libs are found. I also notice that in the output window, the call is different:

This works:
`/usr/bin/env /usr/local/bin/python /home/appuser/.vscode-server/extensions/ms-python.python-2021....`

This does not work:
`/usr/bin/env /usr/bin/python3 /home/appuser/.vscode-server/extensions/ms-python.python-2021....`

Kind regards,

Dirk

**Comment by chrmarti** [comment]
Could you append your devcontainer.json? Are you listing the extensions you need in the devcontainer.json's `"extensions"` property?
