### ISSUE TITLE
file watchers registered by LSP not working in wsl2-ubuntu-20.04.1

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-remote-release#5797]
- VSCode Version: 1.61.2
- Ubuntu 20.04.1 LTS (GNU/Linux 5.10.16.3-microsoft-standard-WSL2 x86_64)
- Remote-WSL: v0.58.4

Steps to Reproduce:

1. Clone Java project https://github.com/microsoft/vscode-remote-try-java to a windows directory
2. Open this project folder in VS Code first, then use "Reopen Folder in WSL"
3. Install “**Extension Pack for Java**” extension in WSL
4. Waiting for Java extension to be ready. (When Java extension is ready, it will display a 👍 icon at the right bottom status bar).
5.  Open pom.xml file and change **source** property to new value such as "1.8". And save pom.xml file.
```
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
```
6. Java extension is supposed to pop up a notification on pom.xml file change. But it didn't display any notification on wsl2.
![image](https://user-images.githubusercontent.com/14052197/138889668-6051c1d0-2440-4355-ae8e-c772e612b8aa.png) 

The same steps work well in a local VS Code environment, but not work in wsl2. 

Java extension uses LSP request "client/registerCapability" to register watch pattern `"globPattern": "**/pom.xml"` for "workspace/didChangeWatchedFiles". It looks like these file watchers are not working in wsl2. I also changed "Developer: Set Log Level..." to trace, didn't observe any error for file watcher in output channel and developer tools console.

**Comment by aeschli** [comment]
Is the folder that is watched a windows mount (`/mnt/c/...`) ?

**Comment by testforstephen** [comment]
yes, i just reopen a windows folder in wsl, it's something like `/mnt/c/...`

**Comment by aeschli** [comment]
It's a known WSL2 issue that file events on `/mnt/`are not reliable: #5000
