### ISSUE TITLE
Connection hangs at "checking for a running server"

### ISSUE THREAD

**Issue by chuckds** [microsoft/vscode-remote-release#5799]
* VSCode version 1.61.2
* local OS: Windows 10
* Remote OS: RHEL 7
* Using: Remote: SSH

When I try to connect to my linux server using remote ssh the connection just hangs ("Setting up SSH Host <hostname>: Installing VS Code Server").

The last entry in the remote output window is:

```
[00:06:55.740] > Checking /<homedir>/.vscode-server/.6cba118ac49a1b88332f312a8f67186f7f3c1643.log and /<homedir>/.vscode-server/.6cba118ac49a1b88332f312a8f67186f7f3c1643.pid for a running server
```

Neither of these files exist.
On the server the only process tree that seems to be vscode related seems broken:

```
58429  0.0  0.0 113420  1796 ?        Ss   16:06   0:00  \_ bash
58535  0.0  0.0 113420   688 ?        S    16:06   0:00      \_ bash
58536  0.0  0.0 113684   988 ?        D    16:06   0:00          \_ bash
58537  0.0  0.0 112816   988 ?        S    16:06   0:00          \_ grep /<homedir>/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/server.sh
58538  0.0  0.0 112816   952 ?        S    16:06   0:00          \_ grep -v grep
58539  0.0  0.0 108064   668 ?        S    16:06   0:00          \_ wc -l
58540  0.0  0.0 108080   356 ?        S    16:06   0:00          \_ tr -d [:space:]
```

It looks like there's a command missing in that tree to provide stdin to grep or the grep is missing an arg.

I've tried removing all files on the server, uninstalling vscode locally, removing user vscode files, removing extensions, restarting my local machine and combinations on these but nothing has helped.

I'm suspecting an issue on the remote side, but I don't know how I can debug this further - I don't see any other logs on the remote side.

**Comment by roblourens** [comment]
Could you share the full log?

There is an echo of `ps` output, which I guess has exited, then the other commands to find a running server if already available.

**Comment by chuckds** [comment]
I included a snippet from `ps aux --forest` . The process tree in the snippet does not exit, it hangs around until killed (still there after 3 days) - hence my comment about it seeming incorrect like grep is being invoked without the right args. There are no other processes related to vscode in the ps output that I can tell (no mention of `node` or `vscode`). Is there anything else I should look for?

I'm happy to provide more logs, just let me know where the logs are located - I haven't been able to find any relevant ones.

**Comment by roblourens** [comment]
You shared one line of the log, I want the rest of the same one :) It's the Remote-SSH output channel

And what I mean is, our script is running a `ps` command piped into the other processes which show in your comment. The command we run is 

`ps ax | grep /<homedir>/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/server.sh | grep -v grep | wc -l | tr -d [:space:]`

I don't know whether that would work differently than expected on your system

**Comment by chuckds** [comment]
Oh that is interesting thanks. Can I ask; does the code do anything to "generate" the above command invocation? e.g. does it try and find the right version of ps to run or anything like that? Or is it just hardcoded?

If I run that command directly from my terminal on the server I get the expected result; stdout of "0" and 0 rc.
From the ps forest output I provided it looks like instead of that command pipe starting with `ps ax` it is instead starting with `bash`, which (since that will start an interactive shell) is not the intent - hence the question above about how that invocation is generated.
With this info I now have a recovery: If I `kill -9` that stray bash process (the 3rd listed in the above forest output - 58536), the blockage is lifted and remote works!


Regarding logs;
In order to reproduce the main issue (hang on connect) I need to empty the .vscode-server directory on the remote host. I've attached the "Remote-SSH output channel" logs that result when I do that and then restart vscode locally.
[vscode-remote.log](https://github.com/microsoft/vscode-remote-release/files/7474847/vscode-remote.log)

If I don't remove the .vscode-server directory and restart vscode then on connection it can't get the flock and so assumes (rightly?) that an installation is in progress, disconnects and retries a bit later getting the same result.

**Comment by roblourens** [comment]
It's actually run in a subshell with backticks, like `RESULT=`ps ax | grep ....`, that is probably where the bash process comes from. I'm not sure why that would be stuck though.

> If I don't remove the .vscode-server directory and restart vscode then on connection it can't get the flock and so assumes (rightly?) that an installation is in progress, disconnects and retries a bit later getting the same result.

I guess that would mean that another bash process still has the lock, maybe it didn't quit correctly after getting stuck.

**Comment by chuckds** [comment]
> I guess that would mean that another bash process still has the lock, maybe it didn't quit correctly after getting stuck.

Yes exactly. The "other bash process" is the subject of our issue :)

> It's actually run in a subshell with backticks, like RESULT=ps ax | grep ....`, that is probably where the bash process comes from

Unlikely. That would be where the parent bash process comes from (PID 58535 in the above ps forest output).
The stray bash process we're trying to track down (PID #58536  in the above forest) is a peer of the other commands (e.g. "grep -v grep" and "wc -l") in that pipe command which means it is part of that pipe. Coupled with the fact that we don't see `ps` in the output something odd is clearly doing on.
To demonstrate this you can replicate the above process tree with the following:
```
> cat ps.sh
#/bin/bash
read  -n 1 -p "Waiting for some input" input
echo "input was ${input}"
> ./ps.sh ax | grep server.sh | grep -v grep | wc -l | tr -d [:space:]
Waiting for input
```

This will hang until you enter a character, and while in this state the process tree in `ps ax --forest` looks exactly what I was seeing the problems.

I see that there is a "ps fallback" in the vscode repo (https://github.com/microsoft/vscode/blob/136adbed5bdcbca1510f8e4dd5eacd1f4ea63c49/src/vs/base/node/ps.sh) is it at all possible that this is being run instead of the "proper" ps? (if so; why?)

If it is possible that this is being run then all that would be needed to explain my symptoms would be if this script somehow hung - perhaps due to some badly behaving process on my remote host?

If this theory turns out to be correct (or at least possible) then;
1. Why was this "fallback" ps.sh being used? The remote hosts ps seems fine.
2. Can some protection be added to ps.sh to prevent indefinite hangs?

Since I identified how to recover from this issue I haven't hit it since so it there was some issue on the host it appears to have passed. Though I haven't gone as far as removing the .vscode-server directory and see if vscode can cope from a clean slate.

Thanks,

**Comment by roblourens** [comment]
No, that other ps script isn't in the remote server and isn't being used. So I still don't know what's going on

**Comment by roblourens** [comment]
If you delete the server files, make sure you kill the server process too (or run the command "Kill VS Code Server on Host" which does all this cleanup) or you might end up in a bad state.

But it sounds like you aren't seeing an issue right now. I'll close this for now, I can reopen it if we need to investigate more later.
