### ISSUE TITLE
Repeated debug session doesnt work

### ISSUE THREAD

**Issue by trondhindenes** [microsoft/vscode-remote-release#58]
Issue Type: <b>Bug</b>

If I start then stop a debugging session, it looks like the app isn't stopped in the container. This causes an error if I try and start a new debug session, which fails because the publishing port is already taken.

Steps to repro:
start debugging (f5)
stop debugging
start debugging (f5)
notice the error in the console and that the debug task fails.

Extension version: 0.48.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.9.125-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: .NET Core Sample|
|OS|Linux x64 4.9.125-linuxkit|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (2 x 2040)|
|Memory (System)|1.93GB (0.12GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment]
@trondhindenes can you please provide more information about the debug session, what language, what extension are you using, can you share your setup?

**Comment by Chuxel** [comment]
@trondhindenes Is this a dupe of https://github.com/Microsoft/vscode-remote-try-dotnetcore/issues/3 or are you seeing it for things other than the try sample?

**Comment by trondhindenes** [comment]
It is. I realized posting here would be more correct than the initial bug I posted in the "try" repo. I'll test based on your comment there, and report back in both issues. Sorry about the duplication.

**Comment by trondhindenes** [comment]
Yup, working after pulling the update in the example repo, thanks! Closing.
