### ISSUE TITLE
Setting up SSH tunnel never resolves

### ISSUE THREAD

**Issue by juliussimonelli** [microsoft/vscode-remote-release#580]
Issue Type: <b>Bug</b>

I had been using the same method to create an SSH connection between my docker container on AWS and VSCode using Remote - SSH (nightly) for a week and it was working and recently it suddenly stopped working. I create a port forwarding ssh to a docker instance inside EC2 with something like this `ssh -L 2201:localhost:2222 user@host -N -i ~/.ssh/id_rsa -v`. user@host is an AWS instance running a docker container and I publish port 2222 when I create it the docker container, but I have to map port 2201 on the host to port 2222 in the container. Then I connect to it using a config file that looks like: 
```
Host *
     User root
     Port 2201
     IdentityFile ~/id_rsa(base)
```

Then in VSCode I go to "Remote-SSH: Connect to Host" and enter `localhost`.

This had been working for the last week but now it never connects. I get a message saying "Setting up SSH Host localhost: (details) Setting up SSH tunnel
Source: Remote - SSH (Nightly) (Extension)"
Then there is a progress bar at the bottom but it keeps cycling over and over. It used to connect within about 5 seconds, but now it won't after 5+ minutes (multiple attempts).

Here's the output from Remote - SSH:

remote-ssh-nightly@2019.6.6855
SSH Resolver called for "ssh-remote+localhost"
SSH Resolver called for host: localhost
Setting up SSH remote "localhost"
Using commit id "7a5bca9fafbbb23de289179be95e9c4832540c02" and quality "insider" for server
Using SSH config file "/Users/juliussimonelli/config"
Install and start server if needed
> Found existing installation at /root/.vscode-server-insiders/bin/7a5bca9fafbbb23de289179be95e9c4832540c02...
> Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> ee29004b-bc2f-4136-a794-e1fe696e4852==46380==
"install" terminal command done
Received install output: ee29004b-bc2f-4136-a794-e1fe696e4852==46380==
Server is listening on port 46380
Using SSH config file "/Users/juliussimonelli/config"
Spawning tunnel with: ssh -t -F /Users/juliussimonelli/config "localhost" -L localhost:60984:localhost:46380 "echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity"
> Connected to SSH Host - Please do not close this terminal

I can test that the tunnel is active by opening a terminal and typing `ssh -F ~/config localhost`. This works as expected.

Extension version: 2019.6.6855
VS Code version: Code - Insiders 1.36.0-insider (7a5bca9fafbbb23de289179be95e9c4832540c02, 2019-06-06T11:36:26.351Z)
OS version: Darwin x64 18.6.0
Fetching remote diagnostics for 'ssh-remote+localhost' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_2904773|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'ssh-remote+localhost' timed out.
</details>

**Comment by roblourens** [comment]
Are you using the showLoginTerminal setting? If so I see the problem.

**Comment by juliussimonelli** [comment]
Yes. And when I changed it from true to false it started working.

**Comment by roblourens** [comment]
Verification:
- Set `remote.SSH.showLoginTerminal`
- Try to connect to any SSH remote
- The install and port tunnel terminals should show up while connection is happening (just for an instant)
- And you should connect successfully
