### ISSUE TITLE
vscode-server with remote-ssh extension eats 100% cpu if "sleep" binary does not exist

### ISSUE THREAD

**Issue by benkillin** [microsoft/vscode-remote-release#5800]
- VSCode Version: 1.61
- Local OS Version: windows 10
- Remote OS Version: rhel 7
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. delete the sleep binary
2. connect to the remote host using the vscode remote-ssh plugin

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes  other than remote-ssh

**Comment by tanhakabir** [comment]
Hm why are you removing the sleep binary from your machine?
