### ISSUE TITLE
Can't save my code

### ISSUE THREAD

**Issue by bennrosh23** [microsoft/vscode-remote-release#5807]
When I try to save my file the in remotte ssh the following error occurs ...
I could be able to save in nano editor in terminal ...
But pressing ctrl + s in VS code won't work and the following error occurs....

Failed to save 'Input_AsmGen.cpp': Unable to write file 'vscode-remote://ssh-remote+ai-aws/export/home/broshnan/sw_dev/device_model_instr/Input_AsmGen.cpp' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/export/home/broshnan/sw_dev/device_model_instr/Input_AsmGen.cpp')

**Comment by bennrosh23** [comment]
No I can save the file in nano editor .... 
So I think permissions are alright ...
I only can't save it in VSCODE by simply pressing ctrl + s
every time to save the code I create a new file in nano, copy paste the code ... save the code in terminal ...

**Comment by roblourens** [comment]
Are you sure you signed in as the right user? 

Do other vscode features work? Can you open terminals or search?
