### ISSUE TITLE
`containerUser` does not work with `Clone Repository in Remote Volume`

### ISSUE THREAD

**Issue by mrmachine** [microsoft/vscode-remote-release#5809]
- VSCode Version: Version: 1.62.0-insider
- Local OS Version: macOS 11.6
- Remote OS Version: Docker Desktop 4.1.1 (macOS)
- Remote Extension/Connection Type: Docker
- Logs:

Steps to Reproduce:

1. Use `Clone Repository in Container Volume` on a repo with a `Dockerfile` that creates an unprivileged user, and a `devcontainer.json` that references that user in `containerUser`.
2. Note that `/workspaces/FOO` and its contents are owned by `root` while the VS Code Server is running as the unprivileged user, and is therefore unable to modify any files.

Does this issue occur when you try this locally?: **No.** Regular devcontainers and Codespaces have bind mounted (regular devcontainer) and workspace (Codespaces) dirs/files owned by the unprivileged user.

**Comment by chrmarti** [comment]
Could you try with a new volume? We update the owner only once after cloning the repository.
