### ISSUE TITLE
Remote-ssh: improve empty workspace experience

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-remote-release#581]
After the user executes the "Connect to Host in New Window" from the SSH Viewlet, we open a new empty VSCode window.
This empty VSCode window does provide any useful functionality and we want to get the user as soon as possible out of this. The only thing that the user can get out of this is that he is happily connected to remote.

I propose that once the connection is made that we automatically show a quick open dialog and offer the user to choose a remote folder to open. 
I understand this is not the pattern that we commonly use, however we already have some multi step quick open actions for remote, the only difference here is that one of the steps is opening a new window.

This opening of a dialog should only be done after the user invoked the "Connect to a Host" action, not every time he is in an empty window on remote.

The alternative would be to make sure the explorer is opened, and we could tune the empty explorer text. To change the wording that it is clear the the user is opening a folder on the remote.

I simply prefer the first approach since I believe it is more straight forward to the user and we skip this state where the user can no do anything useful.

@roblourens @kieferrm let me know what you think

fyi @egamma

**Comment by roblourens** [comment]
Same discussion going on in https://github.com/microsoft/vscode-remote-release/issues/511 and https://github.com/microsoft/vscode-remote-release/issues/501

**Comment by isidorn** [comment]
Ok, I will copy my comment there
