### ISSUE TITLE
Cloning repository in volume with docker-compose configuration always results in root file permissions

### ISSUE THREAD

**Issue by benjaminwood** [microsoft/vscode-remote-release#5810]
When cloning a repository in a container volume (or named container volume) that contains a `.devcontainer` configuration using docker-compose, the workspace directory will *always* be owned by `root:root`, regardless of what user is used in the container via `USER` in the Dockerfile or, `user` in `docker-compose`, or `remoteUser` in `.devcontainer`.

It is important to note that this problem is docker-compose specific. When using a vanilla `.devcontainer` configuration that does not use docker-compose, I see that my workspace directory is automatically `chown`'ed:

```
[15139 ms] Start: Run in container: stat -c %u /workspaces/my-project
[15260 ms] 0
[15261 ms] Start: Run in container: chown vscode:1000 /workspaces
[15263 ms] Start: Run in container: chown -R vscode:1000 /workspaces/my-project
```

Likewise in codespaces, I see similar behavior. Here's a `chown` I found in the logs:

```
Executing raw command: 'docker exec -u root [container-id] chown -R ben /workspaces'
```

My expectation is a `.devcontainer` configuration using docker-compose would behave the same when cloned to a volume as it does in codespaces, or in a non `docker-compose` `.devcontainer`.

I can work around the issue with `postCreateCommand` like this, but I feel I should not have to:

```
"postCreateCommand": "sudo chown -R $(id -u):$(id -g) $(pwd)"
```

- VSCode Version: 1.61.2
- Local OS Version: Ubuntu 20.04
- Remote OS Version: Any/all
- Remote Extension/Connection Type: Docker
- Logs: N/A

Steps to Reproduce:

1. Clone a repository in a container volume (or named container volume) that contains a `.devcontainer` configuration using docker-compose.
2. The cloned repository files will be owned by `root:root`, even if the Dockerfile specifies a different User. I also tried explicitly specifying the `remoteUser` in `.devcontainer`, but it has no effect on this issue.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by benjaminwood** [comment]
Thanks for the fix!

**Comment by aeschli** [comment]
Verified by
- created a new repo on with a `Docker from Docker Compose` devcontainer file
- use `Clone Repository in Container Volume` on that repo
- open the terminal and verify that the user is `vscode` as specified in the devcontainer file
