### ISSUE TITLE
"Open Folder in WSL" shows "\\wsl$\[object Object]\home\chrmarti\devel\smktst"

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#5812]
Not sure this is new. I then can't correct the path for the input validation to accept it.

**Comment by chrmarti** [comment]
@rzhao271 I don't see a new release of Remote-WSL. Your update to the milestone of this issue might be too early.

**Comment by aeschli** [comment]
Th fix is not yet published...

**Comment by chrmarti** [comment]
Verified in 0.58.5. 👍
