### ISSUE TITLE
View files during devcontainer build

### ISSUE THREAD

**Issue by SlothFriend** [microsoft/vscode-remote-release#5815]
Hi, it would be great if we could still view files while vscode is building the devcontainer. I attached a screenshot of the experience waiting for the devcontainer to build and not being able to view the files anymore.

Thanks for considering this request!

<img width="1680" alt="Screen Shot 2021-11-01 at 10 11 59 AM" src="https://user-images.githubusercontent.com/11187206/139703771-e3f53546-4645-474d-b7ee-339f56e752e6.png">

**Comment by chrmarti** [comment]
This might be difficult to achieve as we need to run the VS Code server in the container to get access to the files. Running a temporary container or accessing the files locally (if they are on the local filesystem) might be an option, but that would need support from VS Code / VS Code server.
