### ISSUE TITLE
The "Kill VS Code Server on Host" command does not work for hostnames containing spaces

### ISSUE THREAD

**Issue by ElleshaHackett** [microsoft/vscode-remote-release#5816]
VSCode Version: 1.61.2
Local OS Version: Windows 10 21H1
Remote OS Version: Ubuntu 20.04.3 LTS
Remote Extension/Connection Type: Visual Studio Code Remote - SSH extension (https://code.visualstudio.com/docs/remote/ssh)
Logs: n/a

**Steps to Reproduce** are described in detail in this answer: https://github.com/microsoft/vscode-remote-release/issues/5813#issuecomment-958770528

However manually killing it by running `ps uxa | grep .vscode-server | awk '{print $2}' | xargs kill -9` remotely does work.

**Comment by roblourens** [comment]
Can you try running that command and sharing the log from the Remote-SSH output channel? The command we are running is essentially the same as yours.

**Comment by ElleshaHackett** [comment]
@roblourens I suppose the label "needs more info" can be removed from both issues as I think I supplied all details steps and info needed to reproduce this. Below you find the requested log (anonymized) if I run that action.

````
[11:39:17.133] Picking SSH host
[11:39:21.933] Selected XXXXXX - 192.168.x.x
[11:39:21.939] Running script with connection command: ssh -T -o ClearAllForwardings=true XXXXXX - 192.168.x.x bash
[11:39:21.941] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[11:39:22.180] > ]0;C:\WINDOWS\System32\cmd.exe
[11:39:31.557] > ssh: Could not resolve hostname XXXXXX: unknown host. 
[11:39:32.810] "Uninstall VS Code Server" terminal command done
````

**Comment by roblourens** [comment]
I see the problem - we can connect to hostnames with a space, but do not handle that correctly for the kill command

**Comment by tanhakabir** [comment]
@ElleshaHackett were you able to run `ssh XXXXXX - 192.168.x.x` in your terminal? From my understanding reading the https://www.man7.org/linux/man-pages/man5/ssh_config.5.html, I see that patterns aren't allowed to include spaces and that Host values should be patterns.

**Comment by roblourens** [comment]
Hosts can include whitespace, they just have to be quoted

**Comment by tanhakabir** [comment]
I'm not seeing that to be the case when I try to ssh with terminal:

I have a config like this:
```
Host name with spaces
  HostName 147.182.250.143
  User root
```

And I see in terminal this:
```
(base) tanha@Tanhas-MacBook-Pro ~ % ssh "name with spaces"
ssh: Could not resolve hostname name with spaces: nodename nor servname provided, or not known
```

However with my config:
```
Host namenospaces
  HostName 147.182.250.143
  User root
```

I see no issues:
```
(base) tanha@Tanhas-MacBook-Pro ~ % ssh namenospaces      
root@147.182.250.143's password: 

(base) tanha@Tanhas-MacBook-Pro ~ % ssh "namenospaces"
root@147.182.250.143's password: 
```

**Comment by ElleshaHackett** [comment]
Please reopen, all information is supplied

**Comment by tanhakabir** [comment]
@ElleshaHackett it's fixed in the Nightly version of the extension and will be published in stable next week!

**Comment by ElleshaHackett** [comment]
Thanks. Do you have any idea on the original issue that lead me to create this issue? https://github.com/microsoft/vscode-remote-release/issues/5813

**Comment by tanhakabir** [comment]
Sorry I'm not sure about the original issue
