### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jaweed-khan** [microsoft/vscode-remote-release#5817]
- Issue Type: `Performance`
- Extension Name: `remote-containers`
- Extension Version: `0.202.5`
- OS Version: `Linux x64 5.11.0-38-generic`
- VS Code version: `1.61.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/ms-vscode-remote.remote-containers-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by chrmarti** [comment]
@jaweed-khan Could ypu attach the file mentioned above?
