### ISSUE TITLE
Conexion SSH 

### ISSUE THREAD

**Issue by alu0100990539** [microsoft/vscode-remote-release#5820]
Buenas, 

Estoy intentando conectarme con Visual Studio Code a mi cuenta en IONOS y no entiendo porque no me funciona.

Mediante Filezilla puedo ver que al intentar la conexión, después de que Visual Studio Code me preguntara el tipo de servidor (linux) y el password, en el servior se crea la carpeta .vscode-server

Y esta es la salida/debug que ofrece Visual Studio Code al intentar conectarse:
```
u90331772@home696135976.1and1-data.host's password:
a504f8ad7e3b: running
Acquiring lock on /kunden/homepages/35/d696135976/htdocs/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/vscode-remote-lock.u90331772.c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
Found existing installation at /kunden/homepages/35/d696135976/htdocs/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63...
Checking /kunden/homepages/35/d696135976/htdocs/.vscode-server/.c13f1abb110fc756f9b3a6f16670df9cd9d4cf63.log and /kunden/homepages/35/d696135976/htdocs/.vscode-server/.c13f1abb110fc756f9b3a6f16670df9cd9d4cf63.pid for a running server
Looking for server with pid: 94609
Found running server...

*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
*

Checking server status on port 34756 with wget
a504f8ad7e3b: start
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==34756==
osReleaseId==debian==
arch==x86_64==
tmpDir==/tmp==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==379b67b3-6066-4077-8619-f359ed7661f5==
a504f8ad7e3b: end
channel 3: open failed: administratively prohibited: open failed
channel 3: open failed: administratively prohibited: open failed
```

Con otros servidores linux si que me puedo conectar correctamente...

Gracias y un saludo.

**Comment by tanhakabir** [comment]
Hello! I don't know spanish very well so I don't understand the context but I understand your logs. Looks like `channel 3: open failed: administratively prohibited: open failed` is the issue. I've seen this happen if your remote server doesn't allow TCP forwarding. Are you able to verify your server allows TCP forwarding?

**Comment by alu0100990539** [comment]
Sorry, I update now the issue to full english

**Comment by alu0100990539** [comment]
@tanhakabir sorry, I update the issue to english.

How I can check if the server allows TCP forwarding? With "ss" comand?

**Comment by tanhakabir** [comment]
I'm not sure what kind of access IONOS gives you but either you have permission to edit the sshd_config file and set AllowTcpForwarding to true, more here: https://man.openbsd.org/sshd_config#AllowTcpForwarding

Or if you don't have permissions to edit that file then maybe IONOS has some sort of UI on it's platform to enable this? Sorry I'm not very familiar with IONOS. You could also ask you IT admin for help if you're part of an organization
