### ISSUE TITLE
[Remote-SSH] switch folder/file doesn't switch git branch

### ISSUE THREAD

**Issue by need47** [microsoft/vscode-remote-release#583]
- VSCode Version: 1.35.0
- Local OS Version: Win 10 Enterprise x64
- Remote OS Version: CentOS x86_64 GNU/Linux
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. add two folders (say dirA and dirB) to remote SSH workspace
2. dirA and dirB each have a different git branch (say branchA and branchB)
3. switch from dirA to dirB doesn't switch git branch from branchA to branchB. The bottom left git icon still shows dirA's branchA.

Note this doesn't occur locally. I have these two folder mapped via `Map network drive` and the git branch works normal.

**Comment by roblourens** [comment]
> switch from dirA to dirB

Can you explain by "switch"? Are you clicking the other folder in the SCM viewlet?

**Comment by need47** [comment]
Nope, I'm switching different file tabs that belong to different branches (of different projects).

**Comment by roblourens** [comment]
The status bar is driven by the selected workspace in the git viewlet, not the open file. You can have multiple open files, for example
