### ISSUE TITLE
pass the uid, username and gid, groupname as arguments when building devcontainer if updateRemoteUserUID is enabled.

### ISSUE THREAD

**Issue by scalavision** [microsoft/vscode-remote-release#5831]
Make it possible to extract uid,username and gid, groupname when building the Dockerfile, i.e. these
variables would be available:

```Dockerfile
ARG USERNAME=myuser
ARG GROUPNAME=users
ARG USER_UID=1000
ARG USER_GID=1000
```

If `updateRemoteUserUID`, is enabled.

It simplifies the ownership of internal folders and files to match the same as the user on the host system.

**Comment by chrmarti** [comment]
UID and GID are updated after your Dockerfile is built, so you can assume they are not changed yet while that runs.

Would you want username and group name in the container to be updated to your local account?

**Comment by scalavision** [comment]
I see, thank you for the explanation @chrmarti :-)  It was clarifying the docs.

What I want to achieve is to have a non-privilege user inside the container, and it should be aligned with the host user to avoid permission issues when using bind (as described in the `devcontainer.json` specification for Linux).

I therefor need to give permissions to the folders and tools running inside the container, when the container is building, so the same user also can do work inside this container.

I could extract that info using a script exporting it again via localEnv, if this issue got resolved:

* https://github.com/microsoft/vscode-remote-release/issues/5835

I have read the documentation quite thoroughly, but maybe there is some way to achieve this that I am missing? I find it a bit odd that this isn't a use case many developers would want. Running devcontainer as root is never a good idea. I could guess that often times the userid=1000 and groupid=1000 inside the container and that is the default value on many Linux OS's, but that is not always the case. (NixOS for instance has groupid=100 as default it seems).

I hope this gives a bit more motivation for the use case, but I am not sure it is the best way to achieve it.

**Comment by chrmarti** [comment]
> I have read the documentation quite thoroughly, but maybe there is some way to achieve this that I am missing? I find it a bit odd that this isn't a use case many developers would want. Running devcontainer as root is never a good idea. I could guess that often times the userid=1000 and groupid=1000 inside the container and that is the default value on many Linux OS's, but that is not always the case. (NixOS for instance has groupid=100 as default it seems).

If you run your Dockerfile with a userid=1000 and groupid=1000, the UID/GID updating will then update that user's UID and GID to your local ones.

Marking as feature request.
