### ISSUE TITLE
open remote directory/file from client machine's command line

### ISSUE THREAD

**Issue by yingbo** [microsoft/vscode-remote-release#585]
Same as open a local file "code-insiders bar" can we do the same, from client machine's terminal: "code-insiders ssh://foo.com/home/username/bar"? 

It makes us easily open a code directly connect to the remote server. It's different than https://github.com/microsoft/vscode-remote-release/issues/263 where you need to connect to the remote server first.

**Comment by bmweller** [comment]
@roblourens , can we rename this issue to reflect this is general requirement not limited to remote and/or SSH based access?

As designed VSCode launches a project containing a .devcontainer it starts in local mode prompting to reopen in a container.

"Folder contains a dev container configuration file. Reopen folder to develop in a container (learn more)."

I would like to have an option added to the command line to allow the dev container to be opened by default for example:

```code-insider /uri-path-to-project-folder --dev-container or  
code-insider /uri-path-to-project-folder --mode=dev-container```

when this extension is enabled.

**Comment by slikts** [comment]
The current steps to connect to a remote directory are:

1. *Remote-SSH: Connect to Host…*
1. Select host
1. Wait
1. *Open Folder*
1. Select folder
1. Wait

This is compared to just running `code path` from WSL. Connecting to SSH is relatively very cumbersome and should instead just take an SSH path to replace almost all of these steps.

**Comment by aeschli** [comment]
It's already possible to directly open remote files & folders using `--file-uri`and `--folder-uri`
- `code --file-uri vscode-remote://ssh-remote+myubuntubox/home/x/projects/test.code-workspace`
- `code --folder-uri vscode-remote://ssh-remote+myubuntubox/home/x/projects/foo`

I added a simpler notation:

- `code --remote ssh-remote+myubuntubox /home/x/projects/foo`

There's still more work needed to give good user feedback if the remote or the path can not resolve

**Comment by yingbo** [comment]
Thank you @aeschli . I tried 
`code --file-uri vscode-remote://ssh-remote+myubuntubox/home/x/projects/test.code-workspace`  and `code --folder-uri vscode-remote://ssh-remote+myubuntubox/home/x/projects/foo`. Both are working. The `code --remote ssh-remote+myubuntubox /home/x/projects/foo`, however,  didn't work. My Remote Development version is 0.178.0 and "Remote -SSH" version is 0.46.1

**Comment by aeschli** [comment]
@yingbo I will be in tomorrows insider build...

**Comment by yingbo** [comment]
Got it, thanks! I like the idea of `code --remote ssh-remote+myubuntubox /home/x/projects/foo`.

**Comment by theomessin** [comment]
@aeschli How can you do this with (Docker) Remote Containers? I was thinking a simple `code --remote .` would be nice
