### ISSUE TITLE
Bad configuration option: pubkeyacceptedalgorithms

### ISSUE THREAD

**Issue by catteneo** [microsoft/vscode-remote-release#5851]
- VSCode Version: 1.62.1
- Local OS Version: Windows 10 Build 19043.1320
- Remote OS Version: Ubuntu 18.04.5 LTS - Kernel 4.15.0-151
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Update ~/.ssh/config with added options to host (added becuase of this [issue](https://github.com/git-for-windows/git/issues/3468))
`  HostkeyAlgorithms +ssh-rsa
  PubkeyAcceptedAlgorithms +ssh-rsa`
2. Connect
3. Get error `Bad configuration option: pubkeyacceptedalgorithms`

This is probably related with the version of OpenSSH used (pre 8.5), as the deprecated name of that configuration option works `PubkeyAcceptedKeyTypes`

**Comment by tanhakabir** [comment]
When you connect through PowerShell do you still see the same issue? We use the default ssh binary in your machine so I'm not sure why we'd be using a different one than what is set to default.

**Comment by catteneo** [comment]
Just tried it, got the same error through the PowerShell
Checked the ssh binary, its OpenSSH_8.1p1 for Windows

**Comment by tanhakabir** [comment]
Hm if PowerShell can't connect then the extension won't be able to connect because it uses PowerShell on your machine to ssh connect. Are you able to update OpenSSH on your machine?

**Comment by catteneo** [comment]
According to its Github there's a new version available including OpenSSH_8.6
https://github.com/PowerShell/Win32-OpenSSH/releases/

**Comment by tanhakabir** [comment]
Are you able to try to use that? Once PowerShell can ssh to your remote then the extension in VS Code can. Until PowerShell works there's nothing we can do in the extension to make it work.

**Comment by catteneo** [comment]
Managed to manually update System's ssh.
Can now ssh into the machine using PowerShell.
Remote-SSH extension is now working again.

**Comment by tanhakabir** [comment]
Great thanks! Closing this issue now
