### ISSUE TITLE
Remote SSH doesn't work on windows 10

### ISSUE THREAD

**Issue by kstenerud** [microsoft/vscode-remote-release#5859]
It pops up a small status dialog saying "Setting up SSH host xyz: (details) Initializing VS Code Server" and then hangs forever. Clicking on "details" does nothing, but double-clicking the status popup expands the window to reveal nothing. There is zero feedback from the UI to tell what's going on.

I've tried following https://code.visualstudio.com/docs/remote/troubleshooting#_troubleshooting-hanging-or-failing-connections to no avail. I can SSH from powershell fine.

This is a completely fresh install. I have VS code and the remote extension and nothing else.

- VSCode Version: 1.62.1
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: SSH
- Logs: When I go to Remote-SSH: Show Log, it says "No log files found"

Steps to Reproduce:

1. Install visual studio
2. Install remote extension
3. Connect to SSH host

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: That makes no sense. If I disable this extension I can't connect to a remote system.

**Comment by tanhakabir** [comment]
Hey thank you for being so diligent! And just to verify you don't see anything in the Output Channel for Remote-SSH?

**Comment by kstenerud** [comment]
Actually it's working perfectly now after my machine rebooted. Chalk it up to Windows I guess?

**Comment by tanhakabir** [comment]
Oh great! Let me know if you see this come up again!
