### ISSUE TITLE
Remote - SSH: project path missing after updated to 0.66.0

### ISSUE THREAD

**Issue by fox4u** [microsoft/vscode-remote-release#5861]
In remote explorer, there was the project path just after the name of each project. It became a dot "." after updated to 0.66.0/0.66.1

<img width="358" alt="z0 66 0" src="https://user-images.githubusercontent.com/4506637/141277009-53071fc9-fc3e-41d7-9174-206d5cf419f9.png">

before:
<img width="282" alt="z0 65 8" src="https://user-images.githubusercontent.com/4506637/141277377-8de69a1b-2cbd-4ef6-b4e3-4853115b9d24.png">

**Comment by tanhakabir** [comment]
Hm I'm not reproducing this. Would you be able to verify with disabling Remote-SSH and grabbing [Remote-SSH Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly)?

**Comment by fox4u** [comment]
> Hm I'm not reproducing this. Would you be able to verify with disabling Remote-SSH and grabbing [Remote-SSH Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly)?

with nightly now but the problem persists, any suggestions?

<img width="327" alt="z-nightly" src="https://user-images.githubusercontent.com/4506637/141401940-474335d8-66e5-41b3-afa3-e3ea0727bf30.png">

<img width="321" alt="z-nightly-path" src="https://user-images.githubusercontent.com/4506637/141401990-8801b37a-ce7d-47c2-9646-47e40228252d.png">

**Comment by kleinandreas2002** [comment]
For me the same - missing paths

![image](https://user-images.githubusercontent.com/34026772/141485727-26b73ccc-d8d6-4f8c-bd3f-83690721e08f.png)


Also with nightly build
![image](https://user-images.githubusercontent.com/34026772/141485429-edac82f6-064c-467c-95af-79c8e69cb1b6.png)

**Comment by tanhakabir** [comment]
Last check could you verify this problem exists in vscode version 1.62.2? (the latest one)

**Comment by tanhakabir** [comment]
I can't reproduce this issue. My versions:

VS Code: 1.62.2
Remote-SSH (stable): 0.66.1

**Comment by kleinandreas2002** [comment]
Some new test results from another PC

SSH targets:
![image](https://user-images.githubusercontent.com/34026772/141523565-eac4f491-841d-4068-8d2d-4653fea1bbc4.png)

Current version info:
Version: 1.62.2 (user setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043


BTW:
WSL targets is working:
![image](https://user-images.githubusercontent.com/34026772/141523803-b60e2ae3-1c93-4bc8-8661-f3e329f7a40e.png)

**Comment by tanhakabir** [comment]
@kleinandreas2002 and this is also using Remote-SSH version 0.66.1 stable?

Sorry I'm struggling to reproduce this on my end with both my Windows 10 and MacOS machines.

**Comment by kleinandreas2002** [comment]
Yes, the last input was from Remote-SSH version 0.66.1

Summarize more tests with versions:
0.66.1 -> show no paths
0.66.0 -> show no paths
0.65.8 -> show paths

**Comment by tanhakabir** [comment]
Hm looking through the code since I can't reproduce my guess is that there might be some issue with reading the user data for the extension. 

Would you be able to run this VSIX of the extension that has some console.logs for the data that's saved about folders. https://1drv.ms/u/s!Art4fdsu4NidiWWH70BDZBJ1ymC-

And once you're running the vsix could you first open the SSH Target explorer and then run the command `Developer: Toggle Developer Tools`. You should see some logs from the extension like these: 
![image](https://user-images.githubusercontent.com/12758612/141530501-1971e8fc-4e38-4e1e-b5f4-8c01100fa4fb.png)

Could you send this to me?

**Comment by kleinandreas2002** [comment]
The log is attached

[vscode-app-1636751674194.log](https://github.com/microsoft/vscode-remote-release/files/7530463/vscode-app-1636751674194.log)

If you need more information, please let me know.

**Comment by tanhakabir** [comment]
Thank you! Investigating now

**Comment by tanhakabir** [comment]
This should be fixed an available in the Remote -SSH Nightly extension. And eventually the fix will be published on stable in a couple weeks!
