### ISSUE TITLE
Upgrade to VSC 1.62.1 broke git in remote-ssh

### ISSUE THREAD

**Issue by manuprathab** [microsoft/vscode-remote-release#5863]
Git actions(pull, commit etc) are not asking for user name and pwd after upgrading to this version, it was/is working with the earlier versions.

- VSCode Version: 1.62.1
- Local OS Version: Windows 10 Pro
- Remote OS Version: Red Hat Enterprise Linux Server 7.9 (Maipo)
- Remote Extension/Connection Type: SSH
- Logs:
> git log --oneline --cherry develop...develop@{upstream} --
> git pull --tags origin develop

Steps to Reproduce:

1. Before this version everything was fine
2. After upgrade to this version, git pull does not show the dialog to enter user name and pwd, and it seems to be waiting endlessly.

My colleagues tried to uninstall this version and use the prev version and it seems fine for them. As a workaround we can do that, but still we need a solution for this issue.

**Comment by TTimo** [comment]
Workaround: you can unset GIT_ASKPASS

**Comment by tanhakabir** [comment]
Hmm https://github.com/microsoft/vscode/issues/136791 might be related to your issue. Would you all be able to try to connect on VS Code Insiders?

**Comment by manuprathab** [comment]
Yes, when I tried insider (1.63.0) there is works, it's asking user name and pwd.

**Comment by tanhakabir** [comment]
Okay good! The fix on Insiders will be out later today, you should have an update for stable at the latest tomorrow. Thanks for verifying!

**Comment by tanhakabir** [comment]
Going to close this issue now. If anyone is still seeing this issue in stable 1.62.2 which was released earlier today let me know!
