### ISSUE TITLE
Remote Containers asks to install docker in debian

### ISSUE THREAD

**Issue by asitemade4u** [microsoft/vscode-remote-release#5866]
Issue Type: <b>Bug</b>

Since last version of VS Code (1.62.1) Remote Containers refuses to open a previously functional container

To fix the ssue, I resort to rebuilding the development container whose configuration files are all present)
1. I enter the container's workspace as **Workspace** first
2. I check the **Remote - Container** extension is well installed (I reinstalled it to be sure)
3. I execute: **Rebuild and Reopen in Container**
4. but then it asks me to install docker on my machine:  version 17.12.0 required
5 Back in the debian terminal, I check my docker install with `docker version` and it is 20.10.10 (last docker version)

Extension version: 0.205.2
VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:56:50.217Z)
OS version: Linux x64 4.19.0-18-amd64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3199)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|18.30GB (5.91GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by chrmarti** [comment]
Maybe VS Code's PATH is incomplete. Could you close all VS Code windows and then start VS Code from a terminal that has `docker` available? Does that allow you to reopen the folder in a container?
