### ISSUE TITLE
URI to attach to running container

### ISSUE THREAD

**Issue by simse** [microsoft/vscode-remote-release#5867]
I'm looking for a way to open VS Code and attach to a running container. I assume the command would something like this:
`code --folder-uri=vscode-remote://ms-vscode-remote.remote-containers/simons-container/home/simon`

It's not, and I can't find any documentation on this. Does VS Code support this?

I understand the extension supports the following URI: `vscode-insiders://ms-vscode-remote.remote-containers/cloneInVolume?url=https://github.com/microsoft/vscode-remote-try-python` from #5261. Is there a handler for "Attach to running container"?

**Comment by chrmarti** [comment]
Not officially supported, but you can use `code --folder-uri vscode-remote://attached-container+<container id or name>/workspace/path` to do that.

There is also a CLI that can open a folder in a dev container (but does not yet support attaching to an existing container). You add it to the PATH with `F1` > `Remote-Containers: Install devcontainer CLI`.
