### ISSUE TITLE
Remote SSH: Indistinguishable folder name

### ISSUE THREAD

**Issue by enjaxx** [microsoft/vscode-remote-release#5872]
I have multiple folders which are named the same, but have different path.  If I open such folders in remote SSH, they are only showed with their names with a dot behind the name where the path should stand, so I can't dsitinguish them without moving the mouse over them. I don't know, if it's a setting I miss or a bug, this behavoir ist shown both in the newest vs code and vs code-insiders.

![image](https://user-images.githubusercontent.com/36880987/141451680-9ba58cf6-3172-45c3-aea4-da2501ebc30f.png)

**Comment by tanhakabir** [comment]
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/5861

I wasn't able to reproduce this issue on my end. Are you on the latest version of vscode? (1.62.2)?
