### ISSUE TITLE
Failed to connect server if use wired network

### ISSUE THREAD

**Issue by dengwu08** [microsoft/vscode-remote-release#5873]
it is ok to use remote-ssh if I use wifi.
but if I disabled wifi and use wired network, 
remote-ssh hang up when connect to server.

it is ok if I run "ssh" from windows "cmd.exe" under both network condition.

**Comment by tanhakabir** [comment]
Hey! Thanks for testing this. Would you be able to share your logs from the Remote-SSH output channel?
