### ISSUE TITLE
Automatically reload window after SSH disconnection

### ISSUE THREAD

**Issue by viveksjain** [microsoft/vscode-remote-release#5875]
After sleeping my computer overnight, the vscode remote SSH connection gets disconnected (which is expected). However, after wakeup vscode pops a message asking to reload the entire window. Is there a reason vscode doesn't already 1) create a new SSH connection without reloading the window, or 2) even if that's necessary, automatically reload once it detects that the remote is reachable (waiting might be required e.g. for VPN to get connected). I often have multiple remote workspaces open, and reloading each one takes a bit of time and is annoying.

**Comment by tanhakabir** [comment]
When we connect to your remote, we're using the ssh program from your local machine and so when the computer goes to sleep for awhile that process on your machine also disconnects. We need to reload the window to start that process again with requires authenticating in again. So unfortunately this reload is unavoidable.

But if you set up your SSH with your passphrase in the ssh agent then on reloads you won't need to type in anything to authenticate in.

**Comment by viveksjain** [comment]
Thanks for the response. I don't need to currently type anything to authenticate so that is not an issue, the feature request was specifically that no manual actions (i.e. not even clicking "Reload") are required at all.

**Comment by tanhakabir** [comment]
Ah I see, hmm I don't believe we've automatically reloaded the window before for any other action in VS Code so it might go against common design of the rest of VS Code.

@roblourens thoughts?

**Comment by roblourens** [comment]
I don't think we should reload the window automatically

**Comment by viveksjain** [comment]
In case anyone else stumbles on this and wants similar behavior, turns out this is not too hard to do in an extension (although I do have to use some heuristics, not sure how to detect actual disconnection). It's been working well for me, and now it's published at https://marketplace.visualstudio.com/items?itemName=viveksjain.remreload
