### ISSUE TITLE
Path Expansion Wrong on MacOS Monterey

### ISSUE THREAD

**Issue by jonyoder** [microsoft/vscode-remote-release#5877]
Issue Type: <b>Bug</b>

Use Remote-Containers - Clone Repository in Named Container Volume to open a workspace from Github that uses the following configuration:

```
# .devcontainer/docker-compose-vscode.yml
version: '3'

services:

    vscode:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        ports:
            - "5559"
        tty: true
        privileged: true
        volumes:
            - ~/:/userhome
            - ~/.aws:/root/.aws
            - /var/run/docker.sock:/var/run/docker.sock
```

The Dockerfile can be anything, simply something like `FROM ubuntu:bionic` should suffice.

When expanding the `~` characters to mount the volumes, the tilde is expanded to `/root` instead of the correct user home even if VS Code is running as a non-root user. 

Here's a snipped from the remoteContainers log:

```
[2021-11-12T19:59:10.731Z] services:
  vscode:
    build:
      context: /workspaces/launcher
      dockerfile: .devcontainer/Dockerfile
    labels:
      vsch.local.repository: https://github.com/rstudio/launcher.git
      vsch.local.repository.folder: launcher
      vsch.local.repository.volume: launcher-dev
    ports:
    - target: 5559
    privileged: true
    tty: true
    volumes:
    - /root/.aws:/root/.aws:rw
    - /root:/userhome:rw
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - launcher-dev:/workspaces:rw
version: '3'
volumes:
  launcher-dev:
    external: true
    name: launcher-dev

ERROR: for launcher_devcontainer_vscode_1  Cannot start service vscode: Mounts denied: 
The path /root/.aws is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.

ERROR: for vscode  Cannot start service vscode: Mounts denied: 
The path /root/.aws is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.
```

Extension version: 0.205.2
VS Code version: Code 1.62.2 (Universal) (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.47-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id c4accd76-af89-4258-aca4-4ffd7ceeef6a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Recovery Container|
|OS|Linux x64 5.10.47-linuxkit|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (8 x 2600)|
|Memory (System)|7.77GB (6.64GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by jonyoder** [comment]
To clarify a few things, this issue started occurring immediately after upgrading to Monterey. I've also verified a few things:

* Docker and docker-compose are not broken. I can create a barebones `Dockerfile` and docker-compose YML file and use docker-compose outside of VS Code. Path expansion is correct and the `~` used for mounting a volume expands correctly to my home directory.
* I also completely uninstalled and reinstalled Docker Desktop for Mac, just to be sure there wasn't an issue with it.
* VS Code appears to be running under the correct account. The `Code` process and a number of `Code Helper` processes are all running as my user account (not root).

**Comment by jonyoder** [comment]
Here's an example repo that you can use to reproduce the issue: https://github.com/jonyoder/test-vscode

1. From the VS Code Command Palette, choose "Remote-Containers: Clone Repository in Named Container Volume..."
2. Choose Github, then choose the `jonyoder/test-vscode` repo.
3. Choose the `main` branch.
4. Choose "Create a new Volume", then enter a volume name and a workspace folder name.

This should reproduce the problem, and you should see the following in the container log:

```
[2021-11-12T21:01:40.699Z] services:
  test-compose:
    build:
      context: /workspaces/test-vscode/.devcontainer
      dockerfile: ./Dockerfile
    container_name: test-compose
    labels:
      vsch.local.repository: https://github.com/jonyoder/test-vscode.git/tree/main
      vsch.local.repository.folder: test-vscode
      vsch.local.repository.volume: jon-test-vscode
    privileged: true
    tty: true
    volumes:
    - /root:/userhome:rw
    - jon-test-vscode:/workspaces:rw
version: '3'
volumes:
  jon-test-vscode:
    external: true
    name: jon-test-vscode

[snipped]

ERROR: for test-compose  Cannot start service test-compose: Mounts denied: 
The path /root is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
```

**Comment by volkovichRan** [comment]
Had the same problem i just downgrade the remote extension to 0.203.0 and it working but need to fix this :)

**Comment by chrmarti** [comment]
#5900 mentions `${HOME}${USERPROFILE}` also used to work. It took me some time to realize that this is a regression, this worked due to a fix for WSL that was no longer needed and was removed.

**Comment by tanhakabir** [comment]
Couldn't reproduce original bug
