### ISSUE TITLE
Unable to add SSH Target

### ISSUE THREAD

**Issue by lynchpin-ravi** [microsoft/vscode-remote-release#5879]
**Version of VS Code:**
1.62.2

**What type of remote connection you were using:**
SSH

**Your operating system:** 
MacOS Monterey 12.0.1

**The remote operating system you are connecting to:**
Debian 4.9.168-1 (2019-04-12) x86_64

**List of extensions that you have installed:**
Rainbow CSV v1.10.1
Python v2021.11.1422169775
Pylance v2021.11.1
Jupyter Notebook Renderers v1.0.3
Jupyter Keymap v1.0.0
Jupyter v2021.10.1101450599
Remote Development v0.21.0
Remote - WSL v.058.5
Remote - SSH: Editing Configuration Files v0.66.1
Remote - SSH v0.66.1
Remote - Containers v0.205.2

**Steps to Reproduce:**
1. Navigate to Remote Explorer in side bar
2. Add an SSH Connection Command
3. Choose pre-installed ssh config (usr/bin/ssh)
4. Observe that ssh target does not appear in left panel
5. Select the refresh button in the left panel (adjacent to SSH TARGETS)
6. Observe the error "ERROR: Unexpected line break at ..."
![image](https://user-images.githubusercontent.com/81155848/141612683-0ab840b1-6068-494c-ade6-77df301b062d.png)

**What you expected to see, versus what you actually saw:**
I expect to see the ssh target that was added by steps 1-3. I further expect to see the ssh target after refreshing the list in step 5.

**Errors from the Dev Tools Console (open from the menu: Help > Toggle Developer Tools)**
[error.log](https://github.com/microsoft/vscode-remote-release/files/7531692/error.log)

**Comment by tanhakabir** [comment]
> Add an SSH Connection Command

What was the connection you wanted to add?

I'm not reproducing this on my side
