### ISSUE TITLE
Can't connect to <host> : unreachable or not Linux x86_64

### ISSUE THREAD

**Issue by jhsterling** [microsoft/vscode-remote-release#588]
- VSCode Version:  1.35.0
- Local OS Version: windows 10 1703
- Remote OS Version: centos 7 x86_64
- Remote Extension/Connection Type: SSH

This worked the first 10-12 times I connected.  Was building code.  Compiling and debugging. Was using it on two different Linux boxes.  Then it just quit working.

Steps to Reproduce:

1.  Open vscode and try to connect to remote 
2.  

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

![Capture](https://user-images.githubusercontent.com/8131192/59068196-c38ca580-8870-11e9-8577-d0bbc6f0d7bf.PNG)
![prompt](https://user-images.githubusercontent.com/8131192/59068260-f20a8080-8870-11e9-8a38-1696f24a96c8.PNG)

**Comment by jhsterling** [comment]
Ok now I understand why it worked the first dozen times.   I started vscode from a cygwin terminal.  When I start from cmd there is no ssh in cmd.

**Comment by roblourens** [comment]
Can you tell me whether this works in the nightly ssh extension build? (uninstall the stable version first) https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly then you can set the setting `remote.SSH.path` to the path to cygwin ssh
