### ISSUE TITLE
Devcontainers cannot follow symbolic links created on the host

### ISSUE THREAD

**Issue by dbready** [microsoft/vscode-remote-release#5881]
I operate on a fairly full SSD which contains my code workspace and keep larger datasets on a bigger HDD. Outside of a devenvironment context, I create a symbolic link from the external data drive to within the project directory for ease of use (ie `ln -s /mnt/bighdd/project_data/massive_dir ~/project/data/massive_dir`). This allows transparent reference to datasets that may otherwise live across multiple locations or drives because I can mount everything locally under `data/`.

Unfortunately, the development containers cannot read the host symbolic links. In the above example, the development container is unable to explore `~/project/data/massive_dir`. Neither file nor directory links are maintained. 

- VSCode Version: 1.62.2
- Local OS Version: Ubuntu 20.04.3 LTS
- Remote OS Version: tried Alpine and Ubuntu
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Setup to create the `workspace/` and `external_loc/` mount point which gets linked inside the workspace
```
mkdir -p ~/example/workspace
mkdir -p ~/example/external_loc/sub_dir
echo "workspace native file" > ~/example/workspace/host_local_file.txt
echo "external top level" > ~/example/external_loc/data.txt
echo "external secondary level" > ~/example/external_loc/sub_dir/sub_data.txt

# make symbolic links to file and directory
ln -s ~/example/external_loc/data.txt ~/example/workspace/sym_data.txt
ln -s ~/example/external_loc/sub_dir ~/example/workspace/sym_sub_dir
```

2. Add development container files
Default configuration `~/example/workspace/.devcontainer/.devcontainer.json`
```json
{
"name": "Alpine",
"build": {
	"dockerfile": "Dockerfile",
	"args": { "VARIANT": "3.14" }
},
"settings": {},
"extensions": [],
"remoteUser": "vscode"
}
```

Default Alpine `~/example/workspace/.devcontainer/Dockerfile`
```docker
ARG VARIANT="3.14"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-alpine-${VARIANT}
```

3. Launch environment inside container
4. Attempt to read symbolic link file -> No such file or directory
```bash
cat sym_data.txt
```
5. Attempt to interact with symbolic directory link
```bash
ls sym_sub_dir
```
6. Attempt to read file nested in symbolic directory -> No such file or directory
```bash
cat sym_sub_dir/sub_data.txt
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
The second drive is not mounted into the container automatically. You can mount it at the same relative path as locally and a relative symlink should work. You can use the `"mounts"` property in the devcontainer.json to specify additional mount points.
