### ISSUE TITLE
SSH: "unable to watch for file changes in this large workspace" triggered for no reason?

### ISSUE THREAD

**Issue by MarkKahn** [microsoft/vscode-remote-release#5884]
- VSCode Version: 1.62.2 & Insiders
- Local OS Version: OSX 11.5.2
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: SSH

I'm regularly seeing the popup "Visual Studio Code is unable to watch for file changes in this large workspace", however

    lsof | grep inotify | wc -l

reports a whopping 82 watches.

**Comment by roblourens** [comment]
But it is a large workspace right?

**Comment by MarkKahn** [comment]
No, there's <200 files (not including node_modules)

**Comment by bpasero** [comment]
Can you try:
* configure `files.legacyWatcher: off`
* in `files.watcherExclude` configure the path to `node_modules` as an exclude
* restart
* see if it still reproduces
