### ISSUE TITLE
Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)

### ISSUE THREAD

**Issue by pru007** [microsoft/vscode-remote-release#5888]
Hi, I am trying to connect to a remote server via SSH. Whereas when I try to connect it is saying "WebSocket close with status code 1006". 

I am new to VSCode. Any help is appreciated.

**Comment by tanhakabir** [comment]
Hello! Thanks for submitting an issue!

I just need some more information from you:

- VSCode Version:
- Local OS Version:
- Remote OS Version:

And the full logs of your session. You can learn more about the logs I'm looking for here: https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues
