### ISSUE TITLE
Remote SSH integrated terminal doesn't forward x11

### ISSUE THREAD

**Issue by DangoMelon** [microsoft/vscode-remote-release#589]
- VSCode Version: 1.35.0
- OS Version: Ubuntu 18.04.2 LTS x86_64 

Steps to Reproduce:

1. Set "ForwardX11 yes" inside ~/.ssh/config
```
Host *
    ForwardAgent yes
    ForwardX11 yes
    ForwardX11Trusted yes

Host web
    HostName 10.10.0.8
    User web
````

2. Launch remote host from the Remote - SSH tab

3. Try to open any GUI like `evince`, `eog` or `grads`

Does this issue occur when all extensions are disabled?: Yes

I tried code-insiders and the issue persists.
I usually mount the remote directory to a local folder and then launch `ssh -X web@10.10.0.8` inside VSC integrated terminal. I want to change my workflow now that remote development is integrated into VSC but can't due to this issue.

**Comment by roblourens** [comment]
I think this doesn't work for the same reason ForwardAgent https://github.com/microsoft/vscode-remote-release/issues/16. We have to fix up the remote environment with the DISPLAY variable.

**Comment by ATL-Flaneur** [comment]
I'm running VSC on MacOS and connecting to a Linux VM, where I'm working on Python 3 code that displays the result of various calculations with MatPlotLib. When VSC first connects to the VM, I can look in the VSC terminal and see that `DISPLAY` is set to `localhost:10.0` as expected, but running my application gives `Error: Can't open display: localhost:10.0`. The same happens if I run `xeyes` or similar from the terminal.

Oddly, if I launch a MacOS terminal and ssh to the VM, graphical commands from VSC work as expected. Not sure why this should change things, but it does.

**Comment by madscientist42** [comment]
What's more annoying?  It **_USED_** to do this for the most part on my setup.  Now it's just broken.

**Comment by dpar39** [comment]
I got it to work in Windows client with the following steps:
1. Setting environment variable DISPLAY=localhost:10.0
2. Launching the local XServer as "C:\Program Files (x86)\Xming\Xming.exe" :10 -clipboard -multiwindow
3. Setting your ssh_config with
Host *
    ForwardAgent yes
    ForwardX11 yes
    ForwardX11Trusted yes
4. Adding env to my .vscode/launch.json configuration:
```
    {
            "name": "Launch MyProgram",
            "type": "lldb",
            "program": "${workspaceFolder}/install/myProgram",
            "request": "launch",
            "env": {
                "DISPLAY": "localhost:10.0"
            },
    }
```

**Comment by Ehiole** [comment]
@dpar39 is spot on here. Been struggling with this for a long while and I can confirm this works. 

Remote X11 (SSH) extension should add the env variable configuration to the settings.json automatically and tell the user to input their display number in the settings panel based on whatever they set in Xming.

**Comment by ryolate** [comment]
I used https://marketplace.visualstudio.com/items?itemName=spadin.remote-x11&ssr=false#review-details as a workaround. (I'm using Mac, but it seems it works on Windows too)

**Comment by roblourens** [comment]
Does anyone know, is the only thing needed here to set the DISPLAY variable in the remote environment? The extension seems to do a lot of work, and I'm having trouble following exactly what it's doing, but for the basic case I think I just need to discover the value of the DISPLAY variable in the SSH shell's environment and copy that into VS Code's remote extension host environment.

**Comment by roblourens** [comment]
This should work in the next build of the **Nightly** Remote-SSH extension, about 12 hours from now. Please try it out.

**Comment by plwalsh** [comment]
I'm at a bit of a loss in trying to get this to work. I'm running the latest version 0.65.0, and I have `ForwardX11 yes` in my ssh config, but every time I open a remote-ssh workspace, my `DISPLAY` variable is not set in the terminal, and X-forwarding fails. In the *Remote - SSH* output log I see this:

```
[16:36:34.897] Running script with connection command: ssh -T -D 65053 "<hostname>" bash
```

I would've expected to see a `-X` in that command, along with my `DISPLAY` variable being set in the terminal environment. If I manually set the `DISPLAY` variable and open a background ssh connection using PuTTY, I can then launch Xwindows out of VSCode.

Am I missing something in the setup?

**Comment by roblourens** [comment]
`-X` is the same as what you have in your ssh config. Can you open a new issue and include your log from the Remote-SSH  output channel?
