### ISSUE TITLE
Refused to connect to unsupported server - Oracle Cloud

### ISSUE THREAD

**Issue by lexxnsk** [microsoft/vscode-remote-release#5891]
I can not access Oracle Cloud VM - getting this Refused to connect to unsupported server
VM is based on Oracle Linux Server release 7.9
It is ARM based VM

Same works for ARM VM, based on Oracle Linux Server release 8.4

**Comment by tanhakabir** [comment]
Hey! Does the remote machine fit these requirements? https://code.visualstudio.com/docs/remote/linux
