### ISSUE TITLE
Cannot spawn bash

### ISSUE THREAD

**Issue by 4BRobby** [microsoft/vscode-remote-release#5896]
I am running into an error when connecting through ssh.

The server log says:
```
`*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

Extension host agent listening on 34977

[14:42:03] Extension host agent started.
[14:42:03] getUnixShellEnvironment#errorChildProcess A system error occurred (spawn /usr/local/bin/ssh-bash ENOENT)
[14:42:03] ptyHost was unable to resolve shell environment Error: Unable to resolve your shell environment: A system error occurred (spawn /usr/local/bin/ssh-bash ENOENT)
    at /.vscode-server/bin/b3318bc0524af3d74034b8bb8a64df0ccf35549a/out/vs/server/remoteExtensionHostAgent.js:85:55598
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /.vscode-server/bin/b3318bc0524af3d74034b8bb8a64df0ccf35549a/out/vs/server/remoteExtensionHostAgent.js:77:21932`
```

Why would it like to spawn this path when the real bash is at /bin/bash?

**Comment by tanhakabir** [comment]
Just the clarify what is your:
- VSCode Version:
- Local OS Version:
- Remote OS Version:

**Comment by 4BRobby** [comment]
* VSCode Version: 1.62.2 (also tried 1.62.0)
* Local OS Version: Microsoft Windows [Version 10.0.19043.1348]
* Remote OS Version: Ubuntu 20.04.3 LTS

**Comment by roblourens** [comment]
What's the value of the `$SHELL` environment variable on your remote? Something is telling us that is your shell

**Comment by roblourens** [comment]
Can you run the command "Kill VS Code Server on Host", try connecting again, and share the log from the Remote-SSH output channel? It should log printenv. But somewhere, $SHELL must have that value, we didn't make it up

**Comment by 4BRobby** [comment]
I will send an update on this later today but have been way too busy with other things the last days.

**Comment by 4BRobby** [comment]
The command does not change anything. But I can see more output wenn viewing terminal output while connecting. As far as libstdc concerns I have read this is not mandatory and changing not anything.
I have a different server I am running vscode against and it works perfectly there.

Still I get the log entries on the server and on the client
```
Warning: Can't find libstdc++.so or ldconfig, can't verify libstdc++ version
bash: line 175: ldd: command not found
Missing GLIBC >= 2.17!
Found version
```
```
Checking //.vscode-server/.xxxxx.log and //.vscode-server/.xxxx.pid for a running server
bash: line 528: ps: command not found
```
Successful server setup, but with an error concerning the token file:
```
rm: cannot remove '//.vscode-server/.xxxxx.token': No such file or directory
Spawned remote server: 1734726
Waiting for server log...
Waiting for server log...
```
```
channel 3: open failed: administratively prohibited: open failed
channel 3: open failed: administratively prohibited: open failed
```

**Comment by roblourens** [comment]
I was asking for the full log which should include the value of the SHELL environment var from printenv

But I might have misunderstood the original issue. Are you able to connect at all? I thought you were just having an issue with the terminal, but from those errors, I would expect that you can't connect at all.
