### ISSUE TITLE
'Add development configuration files' support to navigate to the documentation for a feature/configuration

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#5899]

**Comment by chrmarti** [comment]
Adding an optional `documentationURL` string property to the feature type. /cc @joshspicer 

@Chuxel Was the idea to also have this for definitions? Where would I read the URL from?

**Comment by chrmarti** [comment]
Not adding to the test plan since we are not using this yet.

**Comment by Chuxel** [comment]
@chrmarti I didn't realize you were waiting on me for anything here.  Holiday brain.

For the definitions, I'm not sure where we'd do config-as-code here.  We could use definition-manifest.json if we needed a spot. Otherwise, we'd for now we'd just have to assume where it originated.

**Comment by Chuxel** [comment]
@chrmarti Just pushed an update so we can cut a remote-containers repo release at any point.

**Comment by chrmarti** [comment]
@Chuxel Linking to the README's in vscode-dev-containers for now. Let me know if/when you add a doc URI to the metadata.
