### ISSUE TITLE
Clone in volume docker-compose volume mount cannot use host environment variables in volume mounts definition

### ISSUE THREAD

**Issue by ledouxpl** [microsoft/vscode-remote-release#5900]
Prior to VSCode `1.62.0`, the following `docker-compose.yml` volume mounts were valid and working:

```yaml
volumes:
    # host's tool configuration
    - ${HOME}${USERPROFILE}/.config/gcloud:/root/.config/gcloud:cached
    - ${HOME}${USERPROFILE}/.kube:/root/.kube:cached
```

The use of `${HOME}` enabled any our team member to mount their own configuration into the dev container. Furthermore, the use of `${USERPROFILE}` enabled our team members running Windows to also be able to work with the same docker-compose definition.

Since version `1.62.0`, this configuration is no longer valid and the logs shows that `${HOME}` seems to no longer be evaluated in the host's context but within the container's context, resulting in an attempt to mount `/root` instead of `/Users/johndoe`.

A workaround was to drop support of our Windows dev, and to use the  `~` alias instead to refer to the host's home folder.

```yaml
volumes:
    # host's tool configuration
    - ~/.config/gcloud:/root/.config/gcloud:cached
    - ~/.kube:/root/.kube:cached
```

Although far from ideal, this worked until VSCode `1.62.2`. Now `~` also refers to `/root` when volume mounting occurs.

We tried using the `localenv:` prefix, thinking it might work:

```yaml
volumes:
    # host's tool configuration
    - ${localEnv:HOME}${localEnv:USERPROFILE}/.config/gcloud:/root/.config/gcloud:cached
    - ${localEnv:HOME}${localEnv:USERPROFILE}/.kube:/root/.kube:cached
```

This resulted in a different error preventing the dev container from launching:

```
[2021-11-16T16:00:23.313Z] Start: Run in container: gpgconf --list-dir agent-socket
[2021-11-16T16:00:23.625Z] 
[2021-11-16T16:00:23.625Z] /bin/sh: gpgconf: not found
[2021-11-16T16:00:23.625Z] Exit code 127
```

What is the proper way of handling host's home folder volume mounts through docker-compose when cloning the repository in a named volume?

**Comment by chrmarti** [comment]
Tracking with #5877.
