### ISSUE TITLE
Possibility to get/set the local clipboard from remote terminal?

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode-remote-release#5905]
Hi, 

I'm not sure this is possible or worth the effort, but it's worth asking. 
On linux one can pipe the output of  terminal command into the system (X) clipboard:

```
command | xsel -ib
```

The same is possible on mac:

```
command | pbcopy
``` 

And I'm sure this can be done on windows too.
It's incredibly practical and I use it all the time but currently it isn't possible in a remote session as it would set the remote server's clipboard, not the local one. 

1. Is there any chance that this could be added to the remote extension?
2. If not, is it possible to implement it as a plugin or separate extension? I think the remote extension is closed source, so not sure how  I could go about it?

**Comment by tanhakabir** [comment]
Hey! Thank you for the request! This isn't a super trivial feature but the work would need to be done in VS Code core not the remote extension

**Comment by ldorigo** [comment]
Could you elaborate? If it's in the core, then it might be easier to implement the functionality as a separate extension (as the core is open source). But isn't this specifically something the remote extension would need to handle? I guess in a similar way you handle `code <file>` in a remote terminal - not sure how exactly you implemented that but I assume you're automatically adding .vscode_server/bin to the path when a remote terminal is started?

**Comment by tanhakabir** [comment]
The remote extension mainly handles connecting and maintaining the connection. The actual terminal and such is maintained by the main repo. You can install extensions in the remote if you'd like to make an extension. I'm not sure if the terminal in core has awareness of being in a remote environment or not (my assumption is that it doesn't) so there would some structural changes needed to enable this.

**Comment by booyaa** [comment]
Just in case anyone else comes across this ticket, someone made a plugin that uses a 3rd party tool called [piknik](https://github.com/jedisct1/piknik). There's a bit of setup, but it works great and has a vscode [extension](https://marketplace.visualstudio.com/items?itemName=jedisct1.piknik)
