### ISSUE TITLE
Interacting with remote file system "freezes" the entire app

### ISSUE THREAD

**Issue by thistlillo** [microsoft/vscode-remote-release#5909]
With the latest update of this extension, interacting with the remote filesystem has become dangerous: very often (almost always), with a probability proportional to the size of the remote files operating upon, the operation does not end. Visual Studio Code remains reactive, but it is impossible to perform any operation, including saving modified source files, disconnecting from the remote server and exiting from the app. 

For example, few minutes ago I asked to delete permanently a file using the file browser in the left column. The operation kept running, I could not save any file, if I asked to "close remote connection" nothing happened, if I closed visual studio code (cross in upper right corner), VSC would ask me to confirm switching workspaces but then did not close. I had to kill it with Task Manager. 

This dynamic occurs very very often, but I could not detect any pattern, just that about the file size.

Version: 1.62.2 (user setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Remote SSH: v0.66.1

**Comment by tanhakabir** [comment]
This could potentially be a filewatcher issue @bpasero?

**Comment by bpasero** [comment]
Why? File watchers run in separate child processes and should not block the process that is responsible for file operations. But to rule that out, you can configure `files.watcherExclude: '**'` and restart.
