### ISSUE TITLE
Allow filtering available SSH connections

### ISSUE THREAD

**Issue by VishaalK** [microsoft/vscode-remote-release#591]
The Extension is working like a charm, but it was tedious to search through all the different hosts on the `Connections` tab, and I didn't end up finding mine. I instead using `Remote-SSH: Connect To Host..` to find it. It seems the host I was looking for did not show up in the `Connections` tab.

**Comment by roblourens** [comment]
@sandy081 Can custom treeviews opt into the tree's search/filter logic?

**Comment by sandy081** [comment]
Adopting to new tree will provide this out of the box - https://github.com/microsoft/vscode/issues/63566

**Comment by roblourens** [comment]
This is now supported (thanks @sandy081)
