### ISSUE TITLE
Error installing remote-containers vsix 0.206.0 on macOs 

### ISSUE THREAD

**Issue by aturetta** [microsoft/vscode-remote-release#5911]
- VSCode Version: 1.62.2
- Local OS Version: macOS Catalina 10.15.7
- Remote OS Version:
- Remote Extension/Connection Type: Docker
- Logs:
Unable to install extension 'ms-vscode-remote.remote-containers' as it is not compatible with VS Code '1.62.2'

Steps to Reproduce:

1. disconnect mac from network (my machine is not internet connected)
1. Install from vsix, select ms-code-remote.remote-containers-0.206.0.vsix

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

remote-containers 0.205.2 installs fine on the very same machine

**Comment by chrmarti** [comment]
Remote-Containers 0.206.0 currently requires VS Code Insiders (or the future VS Code 1.63.x).
