### ISSUE TITLE
Opening (large) workspace in container fails with "Cannot reconnect, please reload the window"

### ISSUE THREAD

**Issue by MartinSoto** [microsoft/vscode-remote-release#5915]
Trying to open a relatively large workspace (20+ projects, mostly Java, all of them rather small) leads to a failure with the dreaded "Cannot reconnect, please reload the window" message box. Reloading as indicated results in the same failure in about 4 of 5 attempts. The other attempt will mysteriously succeed, with VSCode operating properly from that point on until it is restarted again manually.

![image](https://user-images.githubusercontent.com/609005/142503606-f95a5b3d-91f4-4fd1-8fae-f39d73cc2fcd.png)

The VSCode Version is

        Version: 1.62.3 (user setup)
        Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
        Date: 2021-11-17T08:11:14.551Z
        Electron: 13.5.2
        Chrome: 91.0.4472.164
        Node.js: 14.16.0
        V8: 9.1.269.39-electron.0
        OS: Windows_NT x64 10.0.18363

The container is a customized Ubuntu 20.04 (Focal). 

Docker is Docker for Windows 4.1.1.

The issue was present before, but its frequency was much lower, so that we could still work while having to occasionally retry on restart. It recently became worse to the point of making the environment almost unusable. Unfortunately, I cannot track exactly which update made it worse.

I have tried all sort of things, to no avail. Removing/deactivating all extensions (with the exception of Remote Containers, of course) didn't help. I even manually removed all extensions installed in the container, but the problem persisted.

The only thing that seems to mitigate the issue is to reduce the size of the workspace file to about 5 entries. The start-up process  then becomes significantly faster (or at least not as slow) and works quite reliably. This of course is a possible workaround for us, but no proper solution in the long run as it makes work quite inconvenient

The following is the extension log for one of the failures:

[remoteContainers-2021-11-18T21-03-47.484Z.log](https://github.com/microsoft/vscode-remote-release/files/7566294/remoteContainers-2021-11-18T21-03-47.484Z.log)

I'd appreciate any help and will be glad to provide additional information on request.

**Comment by chrmarti** [comment]
A bit of a guess, could you:
- Run `code --locate-extension ms-vscode-remote.remote-containers` find the extension's install location.
- Remove the following two lines from that folder's `package.json` file:
```json
		"workspaceContains:.devcontainer/devcontainer.json",
		"workspaceContains:.devcontainer.json",
```
- Check if the problem is still the same.
