### ISSUE TITLE
Type Chinese characters messily in Terminal 

### ISSUE THREAD

**Issue by purocean** [microsoft/vscode-remote-release#592]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/7115690/59076135-0bf6a280-8907-11e9-9486-e149168cf62c.png)

Extension version: 0.38.0
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (7.29GB free)|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Mrliduanyang** [comment]
可能是字符集的问题。
我的情况是vscode remote 连接阿里云ubuntu1604主机。在bash中无法输入中文，在vim中可以输入中文但乱码。
解决方案是安装语言包并重新设置系统语言，用到命令如下：

- apt-get -y install language-pack-zh-hans
- dpkg-reconfigure locales

可以试下。

**Comment by purocean** [comment]
@Mrliduanyang 谢谢，我加入这两句就好了
```bash
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
```

**Comment by Tyriar** [comment]
Can you try set `"terminal.integrated.setLocaleVariables": true`

Also what's the result of `echo $LANG`?

**Comment by purocean** [comment]
Thank you @Tyriar 
I turn on the `terminal.integrated.setLocaleVariables` option. Environment variable `$Lang` is `zh_CN.UTF-8`. Not working properly. I turn off that option. `$Lang` is `en_US.UTF-8`. It works fine.

So I set the setting `terminal.integrated.setLocaleVariables`  option off now.

**Comment by Tyriar** [comment]
I'll close this off for now as you have a fix and will keep an eye out for similar reports, thanks.
