### ISSUE TITLE
Client retry mechanism

### ISSUE THREAD

**Issue by Diamondjcx** [microsoft/vscode-remote-release#5922]
When an individual file in the accessed server folder does not have permission, the server memory will be stuck in the server memory, and there is no error or forced exit. It is recommended to add an error or warning prompt

![图1](https://user-images.githubusercontent.com/27531549/142714212-b8e076b6-ab3d-473f-92dc-bb25052a2302.png)
![图2](https://user-images.githubusercontent.com/27531549/142714217-9b06908b-270e-4777-b141-b1216659269a.png)
类似像图一这种 访问，会一直消耗服务器的内存，导致服务器卡到爆，且客户端和服务端并不会收到错误或warning，希望可以优化下这块功能。
类似图二这种访问，就没有影响。

**Comment by eleanorjboyd** [comment]
Hello! My name is Eleanor and I am the new maintainer for the Remote-SSH extension. Are you still experiencing this issue? Thanks
