### ISSUE TITLE
SSH targets only show httpdocs

### ISSUE THREAD

**Issue by thijndehaas** [microsoft/vscode-remote-release#5924]
All websites in our dev Plesk environment show the following in the SSH targets screen:
![afbeelding](https://user-images.githubusercontent.com/18503351/142721136-498d14e0-4d0b-489f-9c67-cb543ec939ac.png)

A few version ago it would show the actual path instead of the dot behind it.
Something really useful would be to have a config with words that get removed from it, and maybe show some symbol before them to make it clear.

![afbeelding](https://user-images.githubusercontent.com/18503351/142721438-8fd82e1c-57b2-4044-8b03-9f5933653f13.png)

A list of words that are used in many environments:
httpdocs
htdocs
public_html
private_html

**Comment by tanhakabir** [comment]
Hey! This was a bug we introduced and recently fixed: https://github.com/microsoft/vscode-remote-release/issues/5861. The fix is currently only in the Remote-SSH Nightly extension and will be merged into stable soon. Let me know if you end up trying it and the fix works for you!
