### ISSUE TITLE
Specify docker context when attaching running containers on different machines

### ISSUE THREAD

**Issue by jingzhaoou** [microsoft/vscode-remote-release#5926]
I searched quite a bit and don't see any similar suggestions yet. I work on multiple remote machines. Each of the machines has running containers that I connect to using VSCode Remote-Containers. Since the containers are on different machines, I need to manually run `docker context use <new_context>` and then use "Remote-Containers: Attaching to Running Container..." to connect to the container on that specific machine. I wonder if I can specify docker context when running "Remote-Containers: Attaching to Running Container..." so that I don't need to do this in two steps. 

Thanks a lot!

**Comment by chrmarti** [comment]
Not sure if that helps, but the Docker extension's viewlet has a `Context` section that allows you to switch contexts.

**Comment by jingzhaoou** [comment]
@chrmarti  thanks for the suggestions. I am aware of the option with Docker extension. Just that it is still a two-step process. If VSCode is able to invoke docker with different contexts, I am curious if VSCode can simply expose this option on the UI.
