### ISSUE TITLE
vscode.commands.executeCommand('workbench.extensions.installExtension', 'ms-vscode.cpptools') doesn't work.

### ISSUE THREAD

**Issue by taronlee** [microsoft/vscode-remote-release#5935]
- VSCode Version: 1.62.3
- Local OS Version: windows NT x_64 10.0.17134
- Remote OS Version: ubuntu 16.04
- Remote Extension/Connection Type: SSH
- Logs: 

Steps to Reproduce:

1. excute vscode.commands.executeCommand('workbench.extensions.installExtension', 'ms-vscode.cpptools');
2. it doesn't work. noting happend and **there isn't any log**.

only happens when remote,
**I tried it on local (windows), ms-vscode.cpptools was successfully installed.**

**Comment by tanhakabir** [comment]
Hm when you try to run `vscode.commands.executeCommand('workbench.extensions.installExtension', 'ms-vscode.cpptools');` after you've connected, could you try to run the command `Developer: Toggler Developer Tools` to see if there are any logs in the console there?

**Comment by taronlee** [comment]
Hello.
There is the result with logs, when trying to run the command.
I can not upload the file because of our security.

>Congratulations, your extension "Hello world" is now active!
/home3/the.lee/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/bootstrap-fork.js:5
Extensions installed on SSH: 168.219.244.65:
dbaeumer.vscode-eslint@2.2.2
esbenp.prettier-vscode@9.0.0
lumos.codesearch@0.0.3
lumos.lumostest@0.0.1
>/home3/the.lee/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/bootstrap-fork.js:5
############ helloWorld command
>/home3/the.lee/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/bootstrap-fork.js:5


**It's my test code.**
```
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import { commands, ExtensionContext } from 'vscode';
import { exec } from 'child_process';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: ExtensionContext) {
  console.log('Congratulations, your extension "Hello world" is now active!');

  exec('code --list-extensions --show-versions', (error, stdout) => {
    console.log(stdout);
  });

  context.subscriptions.push(
    commands.registerCommand('lumostest.helloWorld', () => {
      console.log('############ helloWorld command');
      commands
        .executeCommand(
          'workbench.extensions.installExtension',
          'ms-vscode.cpptools'
        )
        .then(
          data => {
            console.log(`success : ${data}`);
          },
          err => {
            console.log(`error : ${err}`);
          }
        );
    })
  );

  // context.subscriptions.push(disposable);
}

// this method is called when your extension is deactivated
export function deactivate() {}

```

**Comment by taronlee** [comment]
>  ERR Error while installing 'ms-vscode.cpptools' extension in the remote server. connect ETIMEDOUT 13.107.6.175:443

Hmm.. after waiting exactly 12mins, the logs came out. 
It seems to be a security issue for our company, but it took too long..

after proxy exception request, I will test it again.

**Comment by tanhakabir** [comment]
Sounds good! Let me know!
