### ISSUE TITLE
Git Installation not found on Remote-SSH

### ISSUE THREAD

**Issue by Marco-Leal** [microsoft/vscode-remote-release#5936]
I am connecting from Windows to a Linux Server where I have no sudo-privileges. I installed git from an rpm package to my user folder and it's working:

![grafik](https://user-images.githubusercontent.com/23037727/143055548-c3a7ae9c-a193-4086-896a-9739839893a7.png)

I've tried adding the installation folder to $PATH on my ~/.profile, and it's there:

![grafik](https://user-images.githubusercontent.com/23037727/143055636-9a15e436-f7e9-4193-9319-556b4f44fde7.png)

I've added git.path to my Remote settings.json:

![grafik](https://user-images.githubusercontent.com/23037727/143064171-615f085e-268c-4ae6-9ad6-b93d557c7cd0.png)

I've also set the full permissions on /home/j348630/src and all subfolders and files. Finally I've tried to Reload the VS-Code Windows multiple times and even killed the remote .vscode-server in order to reset it.

Despite all this VS-Code still can't find my git installation:

![grafik](https://user-images.githubusercontent.com/23037727/143064253-61ed6056-9752-4e3e-b980-18a254feac7d.png)

![grafik](https://user-images.githubusercontent.com/23037727/143056250-fcc65bd7-1af4-4a91-85ef-444bde44eec0.png)

- VSCode Version: 

Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 6.3.9600

- Local OS Version: Windows Server 2012 R2
- Remote OS Version: SUSE Linux Enterprise Server 12 SP3
- Remote Extension/Connection Type: SSH
- Logs:

Does this issue occur when you try this locally?: No. I have Portable Git installed on Windows and it works fine.

**Comment by lszomoru** [comment]
When you open the workspace in VS Code, did you choose to trust the workspace?
The `git` extension has some limitations when it comes to workspaces that are in "Restricted Mode".

**Comment by Marco-Leal** [comment]
Yes, the workspace is trusted. Just ran Workspaces: Manage Workspace Trust to make sure and the project folder is in the list of trusted folders.

**Comment by lszomoru** [comment]
Thanks @Marco-Leal for the update. Will take a look at the issue and get back to you.

**Comment by Marco-Leal** [comment]
@lszomoru Any ideas?
