### ISSUE TITLE
Attempting to reconnect

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode-remote-release#594]
<img width="791" alt="1" src="https://user-images.githubusercontent.com/11925432/59087518-71fb1e00-8937-11e9-891b-035c1bcdb6d8.png">

I have to reload Window to reconnect.

**Comment by kzhui125** [comment]
another problem:
macbook: wake from from sleep

It shows Attempting to reconnect.

I have to reload VSCode to reconnect.

**Comment by HinPeng** [comment]
My problem very seems. The connection will lost very soon when connecting to wsl. It seems that this problem will happen when trying to open a large text file (more than 10 MB). This problem is gone when closing such big text file in vscode.

**Comment by roblourens** [comment]
This would most likely happen when the connection is lost for 3+ hours. Is that the case? If not can you tell me more about exactly what is happening?
