### ISSUE TITLE
Being able to create settings.json and extensions.json outside of image and named config level for an ATTACHED VSCode Container

### ISSUE THREAD

**Issue by joshsedl** [microsoft/vscode-remote-release#5944]
I'm using WSL 2 for Windows, and I'm currently working on a ddev repo where I am creating a development environment using ddev and VSCode. On initiation of the ddev environment, I am starting up all my containers. With my custom "ddev code" command, I am attaching VSCode to the web container via the hex representation of the web container using 

    'code --folder-uri="vscode-remote://attached-container+646465762d646465762d7673636f64652d646576636f6e7461696e65722d64727570616c392d74656d706c6174652d776562%/var/www/html"'

Now, I would like to automatically enable a bunch of extensions and settings. Currently, I am using workspace settings in my projects folder structure in the form of .vscode/settings.json and extension settings in the form of .vscode/extensions.json. But this is just a workaround, since VSCode will use these settings as "workspace settings" and not "devcontainer settings". I would like to define the settings and install the extensions directly on my attached VSCode container rather than in my workspace settings, since I can only use "recommendations" in the extensions.json, because it is seen as a workspace.

I know I can set the settings and extensions under "AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\imageConfigs" or "nameConfigs" but I would like to have them in Ubuntu or rather in my project's folder directory. I also know that there is the devcontainer.json for standalone VSCode Containers where you can set the Docker files and settings/extensions, but how can I use such a file for my attached container?

Another way would be to install the extensions via command after attaching VSCode using 

`code --install-extension <extension-id>`

But this will only install them locally. And executing this command in the Web-Container via ssh will throw an error.

This would be a really helpful feature addition for our team!

Here is the repository I am working on:
https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template

EDIT: Maybe this issue from our repo can also give more insight:
https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template/issues/28

**Comment by chrmarti** [comment]
I'm not familiar with ddev, but it looks like it is using Docker Compose to start the containers. Maybe you could used a devcontainer.json with `"dockerComposeFile"` pointing at ddev's compose file. Either when the containers are already running or to create the containers (it would be best to try both).

**Comment by joshsedl** [comment]
Hey @chrmarti thanks, for your reply! Yes, ddev is using docker compose for creating the containers, I will give your idea a go in the next couple of weeks and let you know the outcome!

**Comment by joshsedl** [comment]
Ok so I tried both of your suggestions and here is the outcome:

1. Using a devcontainer.json pointing at ddev's compose file and executing "Remote-Containers: Reopen in Container", while the ddev containers are already running, will lead to VSCode running into an error, because it (obviously) can not create the containers:

```
Creating ddev-ddev-vscode-devcontainer-drupal9-template-db ... 
Creating ddev-ddev-vscode-devcontainer-drupal9-template-chromedriver ... 
Creating ddev-ddev-vscode-devcontainer-drupal9-template-chromedriver ... error
ERROR: for ddev-ddev-vscode-devcontainer-drupal9-template-chromedriver  Cannot create container for service chromedriver: Conflict. The container name "/ddev-ddev-vscode-devcontainer-drupal9-template-chromedriver" is already in use by container "48567ae6758dd7e9626e0fe06ac37a38af5477da4daa1d2aea29ec83d7fd2e95". You have to remove (or rename) that container to be able to reuse that name.
Creating ddev-ddev-vscode-devcontainer-drupal9-template-db           ... error
ERROR: for ddev-ddev-vscode-devcontainer-drupal9-template-db  Cannot create container for service db: Conflict. The container name "/ddev-ddev-vscode-devcontainer-drupal9-template-db" is already in use by container "53c11a27fd8fd21e54d8d6dc82bc4fdfdb021cf15fee92e67c43c0af6c6a775a". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for chromedriver  Cannot create container for service chromedriver: Conflict. The container name "/ddev-ddev-vscode-devcontainer-drupal9-template-chromedriver" is already in use by container "48567ae6758dd7e9626e0fe06ac37a38af5477da4daa1d2aea29ec83d7fd2e95". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for db  Cannot create container for service db: Conflict. The container name "/ddev-ddev-vscode-devcontainer-drupal9-template-db" is already in use by container "53c11a27fd8fd21e54d8d6dc82bc4fdfdb021cf15fee92e67c43c0af6c6a775a". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
[7568 ms] Command failed: docker-compose --project-name ddev -f /home/josh/myprojects/ddev-vscode-devcontainer-drupal9-template/.ddev/.ddev-docker-compose-full.yaml -f /tmp/docker-compose.devcontainer.containerFeatures-1639043376050.yml up -d
```

2. Using a devcontainer.json pointing at ddev's compose file and executing "Remote-Containers: Reopen in Container", while the ddev containers are not running will actually work! But it seems that some ddev commands won't work anymore this way, Since VSCode seems to delegate the containers instead of ddev, I will test it further and let you know the outcome!

**Comment by joshsedl** [comment]
Ok @chrmarti, I tested it a bit more, and it strips too much from the ddev environment for my liking. Most custom ddev commands we set up do not work anymore, and some of the core ddev commands don't work either.
To explain, ddev provides commands which can be executed outside the container, which will execute stuff inside a container, so if I would like to run phpunit inside my web-container, I can easily execute "ddev phpunit path/to/tests" outside the container in my working directory. This is a custom command we provided inside the .ddev/commands/web folder. Now that VSCode delegates the containers, these commands won't work anymore, so we have to use "phpunit -c /var/www/html/web/core/phpunit.xml path/to/test" in the VSCode CLI (inside the Container), which is way more complicated. Also, ddev core commands like "ddev delete" which executes some docker scripts to delete the containers and do some other stuff won't work anymore.

The possibility to attach VSCode to a running container is already huge and brings so many benefits! In our repository, we are already using a custom ddev host command "ddev code" in ".ddev\commands\host" which executes:
`code --folder-uri="vscode-remote://attached-container+646465762d646465762d7673636f64652d646576636f6e7461696e65722d64727570616c392d74656d706c6174652d776562%/var/www/html"`
for attaching VSCode to our running web container. 

If there could be an easier readable command to attach to a container, instead of using the hex value of the container, + some additional flags which define the location of a settings/extensions.json, to use would be perfect!
For example:
`code-attach-to-container --extension-path /my/path/to/extensions.json --settings-path /my/path/to/settings.json`

@chrmarti maybe this should be closed and moved to feature request? Or do you have any other suggestions?

**Comment by chrmarti** [comment]
Sounds good, let's track this in https://github.com/microsoft/vscode-remote-release/issues/5944. Thanks!

**Comment by joshsedl** [comment]
Sounds perfect! Thank you!
