### ISSUE TITLE
.ssh/config line 3: Missing target argument.

### ISSUE THREAD

**Issue by rjcdcs** [microsoft/vscode-remote-release#5946]
- VSCode Version: 1.63-insider Commit: c1f2f40bcd81380bf2e286af64becddada57db88 and 1.62.3
- Local OS Version: macOS 11.6.1
- Remote OS Version: any
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Create new connection with the -L option, "ssh -L8888:localhost:9999 localhost"
2. Save to config file
3. Using ssh on the command line, shows error message "/Users/user/.ssh/config line 3: Missing target argument.", due incorrect syntax of the LocalForward option. VSCode saves `LocalForward 8888:localhost:9999` in .ssh/config when it should instead be `LocalForward 8888 localhost:9999`. The same happens for forwarding to a unix socket file.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by tanhakabir** [comment]
What does the entry in your config file look like in total?

**Comment by rjcdcs** [comment]
Thanks for responding, the entry it writes is this:

```
Host localhost
  HostName localhost
  LocalForward 8888:localhost:9999
```

**Comment by tanhakabir** [comment]
Thank you! Will work on this soon
