### ISSUE TITLE
Vscode server process using up all watchers

### ISSUE THREAD

**Issue by kartikeyshetty** [microsoft/vscode-remote-release#5950]
- VSCode Version: 1.62.2
- Local OS Version: MacOS 11.6
- Remote OS Version: Red Hat Linux 8.3
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install Remote-SSH
2. Connect to a remote linux host
3. Open folder on host

While working on vscode with the remote-ssh extension, i noticed having hit the max number of watchers, 8192. 

Upon scrutiny, the below vscode process had "7977" watchers associated to it alone -

/user/kartikey/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/node /user/kartikey/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/bootstrap-fork

Deleting ".vscode-server" and letting remote-ssh recreate the folder reduces the watcher limit. But the issue resurfaces as i continue to use vscode. 

I don't seem to have the issue in other machines that i am connecting to. Any pointers to mitigate or further debug the issue will be helpful.

**Comment by tanhakabir** [comment]
Was vscode version `1.68.2` a typo? If you meant `1.62.2` could you try updating to `1.62.3` to see if you still have the same issue?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by kartikeyshetty** [comment]
Apologies @tanhakabir, i indeed meant 1.62.2. Updated to 1.62.3 now and unfortunately i am seeing it here as well. 

Let me try the insider build @bpasero. Will update what i see.

**Comment by bpasero** [comment]
K

**Comment by kartikeyshetty** [comment]
I haven't gotten around to using the insider build yet. But one other user from my org is reportedly seeing the same issue on a different machine. He is seeing 8020

I don't know if it means anything, but weirdly enough the uuid folder under bin in both our cases have the same "ccbaa2d27e38e5afa3e5c21c1c7bef4657064247" -

/user/aditya/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/node /user/aditya/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/bootstrap-fork

**Comment by bpasero** [comment]
Ok

**Comment by kartikeyshetty** [comment]
Okay. so i haven't encountered it yet in the insider build. Here are the build details

Version: 1.63.0-insider (Universal)
Commit: d09289a2b6dd0e56b2a264a8e9380685498e10d6
Date: 2021-12-04T02:02:08.723Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

So, how do i get this working for regular Code ?

**Comment by bpasero** [comment]
We will ship stable today or tomorrow.
