### ISSUE TITLE
Stuck at aquiring lock

### ISSUE THREAD

**Issue by badkoubeh** [microsoft/vscode-remote-release#5954]
Issue Type: <b>Bug</b>

The remote ssh get stuck at aquiring lock on a particular directory on the remote server does not connet. It connect for the first time but never connects back.

Extension version: 0.66.1
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 4|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|. --crash-reporter-id 2cce6106-cdd5-4a6b-adea-80f8bbfc5da3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593:30376534
vssld246:30401890
vscexrecpromptc:30404946
vscop804:30404766
vs360:30404995

```

</details>

**Comment by tanhakabir** [comment]
Would you be also able to add the logs here for when it becomes stuck? You can find the Remote-SSH logs in the output channel

**Comment by badkoubeh** [comment]
Here is the output,


> 16 updates could not be installed automatically. For more details,
> see /var/log/unattended-upgrades/unattended-upgrades.log
[21:32:24.136] stderr> ln: failed to create symbolic link
'/home/bba37/.android/avd': File exists
[21:32:24.136] stderr> ln: failed to create symbolic link
'/home/bba37/.gradle': File exists
[21:32:24.174] > ready: 6afa97e13b5d
[21:32:24.195] > Linux 4.15.0-163-generic #171-Ubuntu SMP Fri Nov 5
11:55:11 UTC 2021
[21:32:24.196] Platform: linux
[21:32:24.279] > 6afa97e13b5d: running
[21:32:24.363] stderr> /usr/bin/ldd: line 43: printf: write error: Broken
pipe
[21:32:24.364] > Acquiring lock on
/home/bba37/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/vscode-remote-lock.bba37.ccbaa2d27e38e5afa3e5c21c1c7bef4657064247

**Comment by tanhakabir** [comment]
Thanks! Could you also show me the full logs? not just the portion with the error
