### ISSUE TITLE
SSL issue with devcontainer and WSL2

### ISSUE THREAD

**Issue by martgra** [microsoft/vscode-remote-release#5958]
- VSCode Version: 1.62.3
- Local OS Version: Windows NT 10.0.19042
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: mcr.microsoft.com/vscode/devcontainers/python:3-bullseye

Sitting on a corporate computer I use WSL2 + devcontainer for python. From time to time the devcontainer fails to install from poetry claiming unsigned cert in chain. 
```python
  HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/traitlets/5.1.1/json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
```
However running the same installation works just fine in WSL2.  Only solution I have found is a full reset of the host machine. 

Not sure how to reproduce this issue.

**Comment by Chuxel** [comment]
I'm not sure there's much we can do on our side here. Have you seen this at all @chrmarti ?

**Comment by chrmarti** [comment]
@martgra Are you behind a network proxy requiring a custom certificate installed on your machine?
