### ISSUE TITLE
Add quotes to remote bash commands

### ISSUE THREAD

**Issue by lars18th** [microsoft/vscode-remote-release#596]
Hi,

The current implementation uses for the remote command execution something like this:
```
 -c echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity ...
```

This line is passed to the Bash Shell when the OpenSSH server calls to `/bin/bash`.
However, when the shell isn't `/bin/bash` but for example a shell script that does some processing, the remote command execution fails when passing the line to the Bash **because** the content _after_ the `-c` **needs** to be quoted.

So, the correct syntax is:
```
 -c "echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity ... "
```

You can try by yourself executing this in you Linux command shell:
```
$ bash -c "echo -e 'Connected to SSH Host'"
Connected to SSH Host
$ bash -c echo -e 'Connected to SSH Host'

```

You see the difference?
Regards.

**Comment by roblourens** [comment]
I don't think this is an issue now, all commands like this go to bash in ssh as stdin. I changed that in the port tunnel command today.
