### ISSUE TITLE
Test: Support connecting to the remote server through a wsl.exe proxy

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#5960]
Refs: https://github.com/microsoft/vscode-remote-release/issues/5894

- [x] Windows @alexdima 
- [x] Windows @rzhao271

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%235960%0A%0A&assignees=aeschli)

---

The WSL -Remote extension now uses a new connection method for WSL2 when connecting to the remote extension host. It's using a local proxy that runs `wsl.exe` to talk to the distro.

- Make sure you are on the latest Code-Insiers 1.63 and Remote WSL version 0.63.3
- Open the settings and look for settings `remote.WSL1.connectionMethod` and `remote.WSL2.connectionMethod`. Verify that the one for WSL1 is set to localhost, and for WSL2 it is `wslExeProxy`.
- Open a remote window and check that the WSL log (command: `Remote-WSL: Show Log`) tells you at the end which connection method has been used.
- Verify that changing the connection method works (needs a restart of VS Code)
- Verify that opening a remote window with the method `wslExeProxy` works.
- Test that the steps from https://github.com/microsoft/vscode/issues/121799#issuecomment-857881313 no longer cause a reconnect
   - open a new WSL 2 window
   - open the server log (`Log (Remote Server)`) and observethat turning the active network adapter on and off does not case a reconnect in the log
 - Test that sleeping or hibernating the machine does not show a reconnection dialog or require a reload.

**Comment by alexdima** [comment]
👍 Works really nice!
