### ISSUE TITLE
Test: Review/add commands to be surfaced when connected from WSL

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#5963]
Refs: #5765

- [x] windows @rzhao271

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%235963%0A%0A&assignees=chrmarti)

---

- With Remote-Containers, Remote-WSL and Docker Desktop installed:
- Connect to WSL with Remote-WSL.
- Verify the remote menu (click green corner) and the command palette show the same Remote-Containers commands as when not connected with WSL.
- Check with a folder open and the empty window.

**Comment by rzhao271** [comment]
The only remote-containers command that is in the local command palette but not the WSL command palette seems to be `remote-containers.trySample`. This disparity occurs both when there is a folder open, and when it's just an empty window.
The remote menu entries are fine, though.
