### ISSUE TITLE
Test Remote-SSH: Choose set of ports for remote server to use.

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-remote-release#5965]
Refs: https://github.com/microsoft/vscode-remote-release/issues/1386

- [x] macOS @sandy081 
- [x] linux @JacksonKearl 
- [x] windows @karrtikr 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%235965%0A%0A&assignees=tanhakabir)

---

We want to make sure 

Prerequisites: 
1. Use the [Remote-SSH Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly) extension
2. SSH into your own machine: [Windows](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers#windows), [macOS](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers#macos), and [Linux](https://github.com/roblourens/ssh-containers) to get one set up locally.

Steps:

1. Connect to your VM. Observe the log `Remote server is listening on ___` to see random port being chosen.
2. Run the command "Kill VS Code Server on Host...".
3. Set `remote.SSH.serverPickPortsFromRange` setting for your host with a range of ports to connect to.
4. Connect to same host again. Observe that `Remote server is listening on ___` specifies a port within your range.
5. [Stretch] Get creative. (try validating that if no free port is found in range then error is thrown)

**Comment by karrtikr** [comment]
Blocked on https://github.com/microsoft/vscode-remote-release/issues/5966#issuecomment-982632833

**Comment by amunger** [comment]
works for for Windows Server 2019
