### ISSUE TITLE
Test Remote-SSH: Specify installation path on remote

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-remote-release#5966]
Refs: https://github.com/microsoft/vscode-remote-release/issues/472

- [x] macOS @DonJayamanne 
- [x] linux @lramos15 
- [x] windows @karrtikr 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%235966%0A%0A&assignees=tanhakabir)

---

We want to make sure 

Prerequisites: 
1. Use the [Remote-SSH Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly) extension
2. SSH into your own machine: [Windows](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers#windows), [macOS](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers#macos), and [Linux](https://github.com/roblourens/ssh-containers) to get one set up locally.

Steps:

1. Connect to your VM. Observe the file directory of the remote to see `.vscode-server` saved on the home directory.
2. Close you connection
3. Set `remote.SSH.serverInstallPath` setting for your host with an absolute path for the server to be installed instead.
4. Connect to same host again. Observe that `.vscode-server` was saved in your specified location.

**Comment by karrtikr** [comment]
> SSH into your own machine: [Windows](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers#windows)

I'm having trouble doing this, I followed the instructions mentioned in the link, but I'm not quite sure what servername and user name to use [in this step](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse#connect-to-openssh-server): `ssh username@servername`.

I used `northamerica\karraj` as username (which is what `whoami /user` returns). For servername I tried using the IP address for my Wireless LAN adapter Wi-Fi, but this combination does not seem to working. Can you please elaborate here?

**Comment by karrtikr** [comment]
> SSH into your own machine: [Windows](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers#windows)

I'm having trouble doing this, I followed the instructions mentioned in the link, but I'm not quite sure what servername and user name to use [in this step](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse#connect-to-openssh-server): `ssh username@servername`.

I tried using combinations of username: `northamerica\karraj`, `northamerica\karraj@microsoft.com` (which is what `whoami /user` returns), with servername asthe IP address for my Wireless LAN adapter Wi-Fi or `localhost`, but it does not seem to working. Can you please elaborate here?

**Comment by tanhakabir** [comment]
@karrtikr could you try these instructions?

> Connect to localhost on your own Windows machine. You'll need to [set up and start OpenSSH services](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse), such as the OpenSSH SSH Server service and the OpenSSH Authentication Agent service.

**Comment by karrtikr** [comment]
That's what I did, I'm stuck at this step mentioned in the doc: https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse#connect-to-openssh-server

**Comment by tanhakabir** [comment]
Oh try adding to your config an entry like this and then connecting to localhost with `ssh localhost`

```
Host localhost
    Hostname localhost
```

**Comment by karrtikr** [comment]
I am still getting this error: 
![image](https://user-images.githubusercontent.com/13199757/144107334-779f8c8c-5f0b-453b-a683-122598c85978.png)

**Comment by tanhakabir** [comment]
Hmm looking at these 2 sources can you check where your OpenSSH is installed?

https://stackoverflow.com/questions/65921478/connection-reset-by-1-port-22-windows-10-powershell-cmd-openssh
https://github.com/PowerShell/Win32-OpenSSH/issues/1249#issuecomment-419622368

**Comment by DonJayamanne** [comment]
@tanhakabir 
I'm getting the following error in the terminal (following instructions from https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers#macos)
```
> docker run --rm --privileged hypriot/qemu-register
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: : fork/exec /usr/bin/containerd-shim-runc-v2: exec format error: unknown.
```

Basically I cannot proceed with this test. Must be because I"m on Mac M1 (Apple Silicon).

**Comment by DonJayamanne** [comment]
Works for me on Mac M1

**Comment by karrtikr** [comment]
My OpenSSH was installed in `"C:\Windows\System32\OpenSSH"`, I moved it to `"C:\Program Files\OpenSSH"` after which I started getting a different error:

![image](https://user-images.githubusercontent.com/13199757/144225864-39bd3a68-8c60-4721-9142-a22ce0394f75.png)

Looking into if I can solve it...

**Comment by tanhakabir** [comment]
Thanks for trying @karrtikr! Sorry I don't know exactly what the issue is

**Comment by karrtikr** [comment]
I think it's supposed to be a mapping similar to `remote.SSH.remotePlatform`:
```json
"remote.SSH.serverInstallPath": {
    "20.83.238.187": "c:/src"
},
```

**Comment by amunger** [comment]
thanks! that worked, validated successfully for Windows Server 2019
