### ISSUE TITLE
Remote Dev containers - Error response from daemon: Mounts denied for .gitconfig

### ISSUE THREAD

**Issue by bhauminpatel** [microsoft/vscode-remote-release#597]
I am following https://code.visualstudio.com/docs/remote/containers#_getting-started to setup vs code remote container and facing issue in Quickstart: Try a dev container -> step 4. 

I have setup SSH tunnel in client host to communicate with docker on the server.
I have performed all prerequisite steps and executed

_git clone https://github.com/Microsoft/vscode-remote-try-node_

Once I open the folder in the container it is throwing an error as below :

Run: docker run -a STDOUT -a STDERR -p 127.0.0.1:3000:3000 --mount src=vscode-remote-volume,dst=/vscode-remote,type=volume,volume-driver=local -v /home/USER/.gitconfig:/root/.gitconfig -l vsch.quality=stable -l vsch.local.folder=/home/USER/Downloads/Workspace/Github/vscode-remote-try-node -l vsch.remote.devPort=0 vsc-vscode-remote-try-node-045d1a48844eef6429a23eea9b92b32b /bin/sh -c echo Container started ;  while sleep 1; do :; done
docker: Error response from daemon: Mounts denied: 
**The path /home/USER/.gitconfig**
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
 
Can you please help me to figure out why I am getting an error with the .gitconfig file?

P.S.: I do have git installed on my host machine for other project work. 
Below are my machine configuration
Client: Linux machine
Server: Mac OS

**Comment by chrmarti** [comment]
Do you have a `/home/USER/.gitconfig`? This used to work even when there is none. Can you check in the Docker preferences if filesharing for /Users is enabled?
