### ISSUE TITLE
Error dialog does not mention about unavailable ports

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-release#5970]
Testing #5965

- Configured `remote.SSH.serverPickPortsFromRange` to a range that does not exist
- Connecting to Remote SSH has shown following error dialog which does not mention anything about ports

![image](https://user-images.githubusercontent.com/10746682/144069682-171ee15d-0fc1-45cc-a6e5-a312452bcf8f.png)

**Comment by tanhakabir** [comment]
I believe this issue was reintroduced recently with all the changes to the server distro
