### ISSUE TITLE
Cannot attach vscode to a podman container on a remote linux server using remote containers extension

### ISSUE THREAD

**Issue by gilfree** [microsoft/vscode-remote-release#5971]
Issue Type: <b>Bug</b>

Cannot attach vscode to a podman container on a remote linux server using remote containers extension. 
Podman is run rootless mode on the server. all podman commands work from client to server, only attaching
vscode fails.

Use windows 10 client and linux server. 
Versions:
Windows 10 client, vscode insiders 1.63
Ubuntu 18.04 server
podman 3.3.1 on client and server. Installed in rootless mode.

To reproduce:
1. Verify that podman is installed and the socket is running on the server.
2. Create podman connection from client to server (podman system connection create)
    For example, my connection is:
    <connection name> <private key path> ssh://<username>@<servername>:22/run/user/<remote uid>/podman/podman.sock
3. Set vscode to use podman: ```    "remote.containers.dockerPath": "podman" ```
4. Set vscode to use podman in docker extension, e.g. ``` "docker.commands.attach": "podman exec -it ${containerId} ${shellCommand}"```
4. On the server, start a container: ```podman run -d -it ubuntu:21.04 sleep inf```
5. On the client, open vscode. Verify that the docker extension properly shows the container. All docker extension commands work e..g attaching a sheel
6. Right click the container name and select attach visual studio code.
7. vscode window will open, connect to the container, install vscode in it, and then get stuck. Bellow is the log, shortened:

```log
[132 ms] Remote-Containers 0.208.0 in VS Code 1.63.0-insider (d18d093403b12a65350c58a7b0d5771cc1f42aba).
....

[11368 ms] Port forwarding 50688 > 33489 > 33489: Local close
[11369 ms] Port forwarding 50688 > 33489 > 33489 terminated by extension (closed) with code 0 and signal null.
[11380 ms] Port forwarding connection from 60998 > 33489 > 33489 in the container.
[11380 ms] Start: Run in container: /root/.vscode-server-insiders/bin/d18d093403b12a65350c58a7b0d5771cc1f42aba-insider/node -e 
[12395 ms] Port forwarding 60998 > 33489 > 33489 
[13075 ms] Port forwarding 60998 > 33489 > 33489 
[13096 ms] Start: Run in container: /bin/sh -c # Watch installed extensions
[13180 ms] Port forwarding 60998 > 33489 > 33489 
[13192 ms] Port forwarding 60998 > 33489 > 33489: Local close
[13193 ms] Port forwarding 60998 > 33489 > 33489 terminated by extension (closed) with code 0 and signal null.
[13268 ms] Start: Run in container: /bin/sh -c # Watch machine settings
[14823 ms] Start: Run in container: /bin/sh -c # Watch installed extensions
[14908 ms] Start: Run in container: /bin/sh -c # Watch machine settings
```

The last two messages are repeated forever. 

In addition, two popups appear:

```
Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)
```

and 

```
Could not fetch remote environment
```

> An important note:
> I was able to attach vscode to that podman container when I have used a docker context on the client connected to docker in the 
> server, itself using podman socket as it's active context. That has worked for me for some time, but stopped working a 
> couple of weeks ago, with very similar error log. 

System details below:

Extension version: 0.208.0
VS Code version: Code - Insiders 1.63.0-insider (d18d093403b12a65350c58a7b0d5771cc1f42aba, 2021-11-26T08:21:30.810Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-42-generic
Fetching remote diagnostics for 'attached-container+7b22636f6e7461696e65724e616d65223a22636f6e64657363656e64696e675f61757374696e227d' timed out.

<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593cf:30376535
vsc1dst:30396469
pythonvs932:30404738
vscexrecpromptt2:30397559
vscop804cf:30404767
vscop940:30404999
vsclayoutctrc:30405799

```

</details>

**Comment by chrmarti** [comment]
Could you check if it still works with VS Code 1.62?

**Comment by gilfree** [comment]
No, it does not. I checked both with insiders and curent version of vscode. (1.62)

**Comment by tnk4on** [comment]
SSH remote connection problems have been fixed in Podman v3.4.0. Please try again using Podman v3.4.0 or later on the server side.
Please check the comments in the issue. https://github.com/microsoft/vscode-remote-release/issues/4643#issuecomment-916587957

**Comment by gilfree** [comment]
I will try, but it will take some time to get my sysadmin update podman.

**Comment by q40603** [comment]
I have tested on vscode 1.66.2 on windows 10 with podman 3.0.1 installed on wsl2, and it works.

- remote linux server : Fedora 36

- remote podman version:  4.0.3

![image](https://user-images.githubusercontent.com/24668397/163383308-d0ae6d0d-7c80-47d5-8884-7d55cb9f088e.png)

Simply modify the container settings from docker  to podman-remote

**Comment by gilfree** [comment]
Works with podman 4.4.1. Closing
