### ISSUE TITLE
devcontainer CLI cannot find VS code binary installed from snap

### ISSUE THREAD

**Issue by StefanBrand** [microsoft/vscode-remote-release#5978]
- VSCode Version: 1.62.3 / 1.63.0 (insiders)
- Remote Containers: v0.205.2 / v0.208.0 (insiders)
- Local OS Version: Ubuntu 20.04
- Remote OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Run `devcontainer open` or `devcontainer-insiders open`

```bash
>>> devcontainer open
/home/brands/.local/bin/devcontainer: 52: /snap/code/80/usr/share/code/code: not found
>>> ls /snap/code/
81  82	current
```

```
>>> devcontainer-insiders open
/home/brands/.local/bin/devcontainer-insiders: 52: /snap/code-insiders/825/usr/share/code-insiders/code-insiders: not found
>>> ls /snap/code-insiders
875  879  current
```

**Comment by chrmarti** [comment]
Same or similar as https://github.com/microsoft/vscode-remote-release/issues/5865. Keeping this for the CLI.

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/5629.
