### ISSUE TITLE
SSH connection lost if install terminal opened and closed

### ISSUE THREAD

**Issue by omer-musa-battal** [microsoft/vscode-remote-release#5981]
Issue Type: <b>Bug</b>

1. Open a remote host.
2. Click "details" on "Installing vscode server (details)" dialog that shows up after SSH password is entered. A terminal named "install" is created after this.
Edit: The full copied text is as follows: Setting up SSH Host gpu_node_x: ([details](command:opensshremotes.showDetails "Show details")) Initializing VS Code Server.
3. Close this "install" terminal. SSH connection is now lost. Try to open any file, or a terminal, and it fails. After some time, VSCode asks for SSH password again.
4. Repeat from step 2. The bug persists.

If the "details" link is not clicked at step 2, the "install" terminal is not created at all, and the bug vanishes.

Reproducibility may be an issue at step 2, as that dialog does not seem to show up always. I presume it only shows up when the vscode-server at the remote machine has to be updated, or installed from scratch.

Extension version: 0.66.1
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-90-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (22.04GB free)|
|Process Argv|--crash-reporter-id a31b25eb-58a1-4fc2-9111-6a9b9f26bfc4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: gpu_node_x|
|OS|Linux x64 5.4.0-90-generic|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 2199)|
|Memory (System)|31.35GB (26.80GB free)|
|VM|0%|
</details>

**Comment by tanhakabir** [comment]
Hm I can't seem to repro this in Insiders and Remote-SSH version `0.66.1`. Would you mind trying on Insiders?

**Comment by omer-musa-battal** [comment]
Tried with Insiders and Remote-SSH version `0.66.1`, and the issue still persists for me.
By the way, the "details" link mentioned in step 2 can be clicked before entering the password, and the issue still reproduces.

**Comment by tanhakabir** [comment]
This is what I see:
![recording (58)](https://user-images.githubusercontent.com/12758612/144494205-aa1420f6-8f6a-4ca6-88e0-b2cbfcf35322.gif)

Would you able to show me a screen recording of what you see?

/gifPlease
