### ISSUE TITLE
Feature entrypoint does not fire when Docker Compose definition is used

### ISSUE THREAD

**Issue by jrussellsmyth** [microsoft/vscode-remote-release#5983]
- VSCode Version: 1.62.3
- Local OS Version: MacOS 10.14.6 Docker Desktop Version 3.6.0 (3.6.0.5487)
- Reproduces in: Remote - Containers 
- Name of Dev Container Definition with Issue: desktop-light feature

Steps to Reproduce:

1. clone this repo https://github.com/jrussellsmyth/feature-desktop-compose-dosnt-run
2. open in VSCode
3. reopen in container
4. attempt to connect to VNC on http://localhost:6080/
- will fail
5. can also forward port 6080 and try http://localhost:6080/
- will still fail

**Comment by Chuxel** [comment]
I also if it is a bug and not something I'm missing, we should probably look at getting this one in for 1.63 since as feature use starts to grow.

**Comment by joshspicer** [comment]
Is this in the latest remote containers `v0.208.0`?

**Comment by chrmarti** [comment]
Does adding `"overrideCommand": true` to the devcontainer.json make it work?

**Comment by Chuxel** [comment]
@chrmarti Yep! That's does appear to be the issue since its false by default for Docker Compose.

**Comment by joshspicer** [comment]
@chrmarti  - for reference, how is the entrypoint determined if multiple features are used?  If a user is utilizing a feature with a custom `entrypoint` (like dind here: https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/container-features/src/features.json#L22), should we automatically be setting `overrideCommand`?

**Comment by jrussellsmyth** [comment]
verified for me `"overrideCommand": true` does make the feature work

**Comment by Chuxel** [comment]
Yeah, I would not expect to have to set this manually.

**Comment by chrmarti** [comment]
The default does not override because we didn't have that for Docker Compose before and changing it would break existing setups.

**Comment by Chuxel** [comment]
@chrmarti This won't work because there is no way for the user to know that is the case. It just looks broken. In terms of existing setups, they made a change, so when this happens it would be clear what happened.  We should not be overriding existing entrypoints anyway, but rather calling that entrypoint after all of ours.  This is why I've got these entry points setup to enable chaining.

```
ENTRYPOINT: [ "/usr/local/share/docker-init.sh", "/usr/local/share/dekstop-init.sh", "existing-entrypoint-goes-here" ]
```

You need to alter this for the script to even work - so not making that switch really adds little value.  Perhaps though there are two bugs if we are also stepping on the exisitng enterypoint.

**Comment by chrmarti** [comment]
One issue with the chaining is that we would require feature authors to enable that too. I have now come up with an approach that sets the user's entrypoint and command as the new command, so we can use the entrypoint to run the feature entrypoints, then (if overrideCommand is not true) run the user's entrypoint and command and finally go into a sleep loop.

We can always do this (also with no feature entrypoints) with the additional benefit of when the user's entrypoint exits, we keep the dev container running with the sleep loop. This might allow us to remove the requirement for the user to have a sleep loop (or `sleep infinity`) in the docker-compose.yml.

**Comment by chrmarti** [comment]
Doing the same for single containers. The default there is to override the entrypoint and command by default, but the same issue would occur when you add `"overrideCommand": false` to the devcontainer.json.
