### ISSUE TITLE
Docker + linters helper

### ISSUE THREAD

**Issue by AbdelazizSharaf001** [microsoft/vscode-remote-release#5984]
We need help to fix this https://github.com/microsoft/vscode-python/issues/18100

The problem is to work with many containers on the same project files mounted from a volume

Maybe adding an api feature that **allows other extensions to fetch specified docker files from backend** could be helpful
or if there is a way to **combine docker environment and executable in the current workspace** ( first before local environment ) so we could work with many docker environments and executables from the same window

Here is a screen of what I face with linters I need to work with other 2 containers at the same time on the same time with the correct permissions, Getting out the remote dispatch the linter as it can't find executables & getting in destroys permissions for other containers
![Screenshot_2021-12-01_23-48-59](https://user-images.githubusercontent.com/36330265/144326220-e7d78fbd-3805-422d-9788-5597f3b7c0dd.png)

> Why I'm here : https://github.com/microsoft/vscode-python/issues/18100#issuecomment-983888800
Please have a lock at the that issue too so we could generate a solution
I don't know where to ask for help if this is not the right place

**Best regards.**

**Comment by chrmarti** [comment]
Have you tried using the Remote-Containers extension? https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers

**Comment by AbdelazizSharaf001** [comment]
Yes it's perfect for it's purpose, I do use the remote development package
but I'm working for my own projects, many of connected projects...

running with several windows is a pain in local development
However I'm using volumes to mount my projects I still need to log using remote container into every container ( servers )
so I could edit with linter functionalities
also when editing I have a problem with files permisions so I need to fix permissions every time I save :( either manually or using script ( which doesn't know when I did saved ؟ )
when switching to another container I need to restart the container and what I got is getting me out of it

**isn't there a way to attach environments from containers on current window or attache container to the window as a dir so we could Enter the container environment as dir**

> explanation screen with local vscode ( linter is not working properly ) above
and remote container window ( linter is working properly ) below
and you could see the browser permissions
![Screenshot_2021-12-02_18-10-08](https://user-images.githubusercontent.com/36330265/144462747-36117f49-0e3d-4ce8-94fe-0e8b06e8ac95.png)

**Comment by chrmarti** [comment]
Connecting to multiple containers from the same window is currently not possible and tracked in https://github.com/microsoft/vscode-remote-release/issues/1460.

**Comment by AbdelazizSharaf001** [comment]
and how about connecting in background to the container environment

**Comment by chrmarti** [comment]
That could make it faster to switch between containers. It would not show multiple containers in the same window. For that #1460 is needed.
