### ISSUE TITLE
Wrong connection options

### ISSUE THREAD

**Issue by zlygostev** [microsoft/vscode-remote-release#599]
Issue Type: <b>Bug</b>

Have 2 config files to connect 
C:\Users\zlygostev\.ssh\config
# Read more about SSH config files: https://linux.die.net/man/5/ssh_config
Host zlygostev-linux
    HostName zlygostevco7
    User root
C:\ProgramData\ss\ssh_config 
(empty)
Try to connect In remote-ssh tab to zlygostev-linux host.
Expected:
connect as ssh root@zlygostevco7
Output :
Confirming that zlygostev-linux is a valid reachable host
Running type "C:\Users\ZLYGOS~1\AppData\Local\Temp\vscode-linux-multi-line-command-zlygostev-linux.sh" | ssh  "zlygostev-linux" bash to confirm the host platform
> 
> Zlygostev@zlygostev-linux's password:

Zlygostev is my hosted system user. 
Btw, problem starts produce after reboot , possibly after code update.
Code version 1.35.0 
and reproduce in Insiders code too.

Extension version: 0.42.0
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.15063

**Comment by slowjoe007** [comment]
Hi @zlygostev, I tried to set up `Remote SSH` today for the first time and faced the same symptoms also reported by you.
I realized that the extension ignores all settings in files `config` or `ssh_config` except `Host`. So, `HostName`, `User` and `IdentityFile` are not considered when connecting to the remote machine.

A _working_ `config` file looks like this:
```config
# Read more about SSH config files: https://linux.die.net/man/5/ssh_config
Host root@myhost.domain.com
```
although the initial content, when creating the file via VS seems to imply that `Host` takes an alias only and the user can be specified in the extra setting `User`:
```
# Read more about SSH config files: https://linux.die.net/man/5/ssh_config
Host alias
    HostName hostname
    User user
```
Of course, my minimalistic configuration requires a matching certificate at `C:\Users\MyUser\.ssh`.

I hope this helps.

**Comment by roblourens** [comment]
> So, HostName, User and IdentityFile are not considered when connecting to the remote machine.

This is not true @slowjoe007, but please open your own issue and I can try to help.

@zlygostev I don't understand your issue, can you explain some more exactly what the problem is?
