### ISSUE TITLE
Cannot add "Common OS Utilities" via "Configure Features" command

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode-remote-release#5990]
This is currently due to the fact that the "common" feature [does not supply a `version` option](https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/container-features/src/features.json#L1028), and the tooling right now is expecting that as the "default". 

`version` does not make sense for this kind of feature, so the tooling should be able to handle features without this option.  Spoke with @chrmarti and this is the feeling he has as well.

To Reproduce:

1. Remote-Containers v0.209.0 (or codespaces extension).
2. Open project with a devcontainer, with a base image like our vscode ubuntu image
3. Open `Configure Container Features`
![image](https://user-images.githubusercontent.com/23246594/144609708-c23eba7e-3138-486b-84bc-410644977a64.png)
4. Select `common` and some other feature
5. Note that you're given a prompt to select the version for other features, but not `common`.
6. Note the final output does not include common in your devcontainer.json
```
	"features": {
		"docker-in-docker": "20.10"
	}
```

cc/ @Chuxel

**Comment by joshspicer** [comment]
Note that this causes a more noticeable error in codespaces: https://github.com/microsoft/vssaas-planning/issues/6171

**Comment by Chuxel** [comment]
As discussed, common OS utilities should not be appearing at all here. This is partly due to #6069.

**Comment by chrmarti** [comment]
Also making the empty include list always exclude. (No include property will include everywhere unless the exclude property is given - which I see we do not use at the moment.)
