### ISSUE TITLE
Never ending loop when shut down remote instance before closing VS Code 

### ISSUE THREAD

**Issue by suared** [microsoft/vscode-remote-release#5997]
How to recreate:
* Remote workspace a couple of remote terminals.  (I am using AWS EC2, not sure if the specific cloud will matter however)
* Have something running on a remote terminal - local db or whatever
* Shut down the remote instance

What happens:
* VS Code keeps prompting to reconnect and does not respond to exit/ close or provide an option to say that you want to close down

What I would like to happen:
* A way to cleanly close down VS Code when this is intentional without having to click don't retry over and over with no luck

Sometimes the reconnect loop happens forever and only able to close VS Code using the Windows Ctrl-Alt-Delete stop program feature.

**Comment by tanhakabir** [comment]
Sorry about the slow response! I found another issue that's really similar: https://github.com/microsoft/vscode-remote-release/issues/6175

I believe that solving the linked issue would solve this as well? @bpasero thoughts?

**Comment by bpasero** [comment]
@tanhakabir see https://github.com/microsoft/vscode-remote-release/issues/6175#issuecomment-1026527817

**Comment by tanhakabir** [comment]
This should be resolved now from https://github.com/microsoft/vscode/issues/134180#issuecomment-1049629149
