### ISSUE TITLE
Include "Open devcontainer.json" action in problems resulting from devcontainer.json

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-remote-release#6]
When using an "alpine" image in my devcontainers.json I was getting this helpful warning:

![2019-04-25_17-34-20](https://user-images.githubusercontent.com/1898161/56802531-9506be00-6820-11e9-8345-ac29b83c2a76.png)

After dismissing it this not-so-helpful QuickPick showed up:

![2019-04-26_12-39-30](https://user-images.githubusercontent.com/1898161/56802549-9fc15300-6820-11e9-9190-d1ddc942da95.png)

I suggest to add an action to "Open devcontainer.json" in the first alert.

**Comment by chrmarti** [comment]
Ideally we could open the folder locally and the file within it. (Need to check if the 'open folder' command supports that.)

**Comment by chrmarti** [comment]
'Open Folder Locally' now does that.
