### ISSUE TITLE
Do not use GH APIs (due to rate limits) when acquiring public remote "features"

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#6004]
Currently the remote features capability in Remote - Containers uses a GitHub API to aquire the feature.  While this can make sense if a GITHUB_TOKEN environment variable is set, there are low limits for GH APIs if one is not present.  Given this is highly likely to be missing in all local scenarios (and basically everything but GitHub Codespaces), and in CI for everything other than GitHub Actions, we should be using GitHub fetch APIs for public interactions.

e.g. 
1. To get latest you can use this to get latest: `http://github.com/microsoft/vscode-dev-containers/releases/latest` and the effective URL will contain the version number
2. We can require `git` be present when a full version number or latest isn't specified and use `git ls-remote` to do version matching. This is how the [script-library scripts work](https://github.com/microsoft/vscode-dev-containers/blob/9a2d5659aef40ad889b2289dd1e2db41b52305f9/script-library/shared/utils.sh#L176).

**Comment by joshspicer** [comment]
The uris will look something more like this: https://github.com/codspace/myotherfeatures/releases/download/v0.0.5/features.tgz
or
https://github.com/codspace/myotherfeatures/releases/latest/download/features.tgz
