### ISSUE TITLE
Trusted SSH folder still shows as restricted after connecting

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-remote-release#6005]
- VSCode Version: latest Insiders
- Local OS Version: Windows 10
- Remote OS Version: Not sure
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to a previously trusted SSH workspace.
2. Notice it is restricted, and go to manage workspace trust.
3. :bug: There is an entry showing the SSH workspace is trusted, but the workspace still displays as not trusted.

![Example](https://user-images.githubusercontent.com/7199958/144909546-5ec70bda-7074-4acf-858c-642ee0587dad.PNG)

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by rzhao271** [comment]
I wonder if it has to do with there being two entries pointing to the same folder.
I have an entry for the vscode-docs folder so that it should be trusted when I open it.
When I click on the first vscode-docs one, it always opens in restricted mode.
When I click on the second vscode-docs one, it always opens trusted.

![dupentry](https://user-images.githubusercontent.com/7199958/145263597-e27493cc-b0f6-43b9-b818-332c0a1addc0.PNG)

**Comment by tanhakabir** [comment]
@rzhao271 but these are the same directories on the same remote? How did you end up having them both in the SSH Explorer?

**Comment by rzhao271** [comment]
1. Right-click on localhost
2. Click "Connect to host in new window"
3. In that new window, reopen vscode-docs
4. Both vscode-docs show in the remote explorer

**Comment by tanhakabir** [comment]
Huh that seems like a bug on its own

**Comment by tanhakabir** [comment]
@rzhao271 does this mean the issue isn't trust but rather one of your folders were trusted and one wasn't?

**Comment by rzhao271** [comment]
By default, I have `security.workspace.trust.emptyWindow` set to `false`, so at the beginning of step 3 above, the new window is not trusted. I'm not sure whether the issue is that when I open vscode-docs again, trust starts off restricted, but it gets into a mixed up state where at the same time, there is already an entry for that folder in the trusted list.

**Comment by tanhakabir** [comment]
@rzhao271 hm I'm not reproducing this
