### ISSUE TITLE
Add option to locally install extensions on SSH Remote via scp

### ISSUE THREAD

**Issue by jheuel** [microsoft/vscode-remote-release#6009]
It would be nice to have an option that enables installing of extensions over SSH (with scp) similar to the "Local Server Download" option. 

This would simplify the setup of machines not directly connected to the internet.

**Comment by tanhakabir** [comment]
Hey! Does the setting `remote.SSH.defaultExtensions` not help you?

**Comment by jheuel** [comment]
No. As far as I understand the `remote.SSH.defaultExtensions` setting it is just a list of extensions that are installed when connecting to a host. Correct me if I am wrong. And in my scenario that would lead to showing me a never finishing install process of my extensions, as the host is not directly connected to the internet.

To make the idea clear: The client computer connects to a host machine that may sit behind a few ssh proxy jumps. The client computer has access to the internet but the internet access of the host is slow or blocked entirely. Now I propose a setting that enables downloading of extensions on the client machine, before transferring and installing to the host machine.

So it would do
1. download extension files to client computer
2. scp extension files to host machine
3. install on host machine

**Comment by tanhakabir** [comment]
Oh I see!

**Comment by roblourens** [comment]
The setting `remote.downloadExtensionsLocally` now exists
