### ISSUE TITLE
VS Code and WSL lock up hard when build environment changes

### ISSUE THREAD

**Issue by andyp1per** [microsoft/vscode-remote-release#601]
Issue Type: <b>Bug</b>

This is easy to reproduce for me, but I have no idea what step cause the issue:

- Check out and build ardupilot on WSL
- Connect code insiders to the source tree
- Checkout a different branch
- Rebuild ardupilot
- I get a lockup in the build process that also hangs VS code and eventually all of windows. Ultimately I have to reboot to free up.

Happy to provide details when the lockup happens

Extension version: 0.38.0
VS Code version: Code - Insiders 1.36.0-insider (c089daa858f34631f5f827ff8a0313bf1e2ded6d, 2019-06-07T05:19:15.188Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.42GB (5.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3301)|
|Memory (System)|15.42GB (5.24GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3301)|
|Memory (System)|15.42GB (5.24GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment]
Maybe related to the `EACCESS: permission denied error trying to rename a folder in the open workspace` problem that WSL1 has.

Please turn on polling as described in https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace ans see if this fixes the issue.
