### ISSUE TITLE
Cannot activate the 'SQLTools MySQL/MariaDB' extension because it depends on the 'SQLTools' extension

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#6020]
Not sure if this is an issue with this feature specifically, but I have two installed extensions that have a dependency between each other. Every time I connect to the container, I get the following message:

```
Cannot activate the 'SQLTools MySQL/MariaDB' extension because it depends on the 'SQLTools' extension, which is not loaded. Would you like to reload the window to load the extension?
```

The problem goes away if I reload the window.

My `.devcontainer.json`:
```json
{
  "name": "Backend",
  "dockerComposeFile": ["../docker-compose.yml"],
  "service": "backend",
  "shutdownAction": "none",
  "extensions": ["prisma.prisma", "esbenp.prettier-vscode", "mtxr.sqltools", "mtxr.sqltools-driver-mysql"],
  "workspaceFolder": "/code",
  "remoteUser": "dev"
}
```

In this case, `mtxr.sqltools-driver-mysql` is dependent on `mtxr.sqltools`.

LMK if this isnt'related to this feature, I'll be happy to create a separate issue.

_Originally posted by @dreoliv in https://github.com/microsoft/vscode-remote-release/issues/2994#issuecomment-988858315_

**Comment by chrmarti** [comment]
Does it always fail when you rebuild the container? Could you append the log from a rebuild that failed? (`F1` > `Remote-Containers: Show Container Log`)

**Comment by dreoliv** [comment]
I'm sorry but I can't for the life of me replicate this issue anymore. 

Guess it's all good?

I think we can close this issue - I'll report back with the logs if I start seeing it again.
