### ISSUE TITLE
Investigation: RemoteCommand uses/needs

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-remote-release#6025]
Related to https://github.com/microsoft/vscode-remote-release/issues/4474.

The following are requested use cases for RemoteCommand:

1. To change to a different user (ssh'd user doesn't have permissions to desired workspace)
    - https://github.com/microsoft/vscode-remote-release/issues/4474#issuecomment-983095231
    - https://github.com/microsoft/vscode-remote-release/issues/695#issuecomment-507267851
    - https://github.com/microsoft/vscode-remote-release/issues/690
2. Set a default shell 
    - https://github.com/microsoft/vscode-remote-release/issues/481#issue-449402872
3. Automatically open folder on remote 
    - https://github.com/microsoft/vscode-remote-release/issues/5934#issue-1060796988
4. To proxy to another host. (Could be solved by ProxyCommand?)
    - https://github.com/microsoft/vscode-remote-release/issues/4474#issue-808762618
5. To get into a container which has been recently added as a feature in the Remote - Containers extension
    - https://github.com/microsoft/vscode-remote-release/issues/4474#issuecomment-782719598
6. Run VS Code Server in different environment:
    - Slurn
        - https://github.com/microsoft/vscode-remote-release/issues/4474#issuecomment-897278182
        - https://github.com/microsoft/vscode-remote-release/issues/1722
    - Toolbox: https://github.com/microsoft/vscode-remote-release/issues/4474#issuecomment-958690311
7. Load dependencies
   - https://github.com/microsoft/vscode-remote-release/issues/1139

**Comment by roblourens** [comment]
1 also has https://github.com/microsoft/vscode-remote-release/issues/690
