### ISSUE TITLE
Reenable automated 3rd party notices generation

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#6027]
#5898

Had to be turned off because the order in the notices file randomly changed and that made the pipeline push commits with these changes in order. (Owning team confirmed the issue and is tracking it with a work item.)

**Comment by rzhao271** [comment]
What are some verification steps for this issue? I tried checking the pipeline and didn't see the string `3rd-party notices unchanged.` show up, so I wonder if the pipeline still thinks the files are different each time, or if the files are actually different each time.

**Comment by rzhao271** [comment]
No wonder
I only checked the NOTICE File Generator and DownloadPipelineArtifact steps.
