### ISSUE TITLE
Reopen docker-compose project fails with a error "Command failed: docker-compose version --short"

### ISSUE THREAD

**Issue by eitsupi** [microsoft/vscode-remote-release#6032]
I tried to open a project that was working a few days ago, but I noticed that I could not open it with an error. I can't even rebuild it.
Running the command in the terminal confirmed that it was working properly. (both on Windows side and WSL2 side)

```shell
$ docker-compose --version --short
v2.2.1
```

- VSCode Version: 1.63.0
- Local OS Version: WSL2/Windows10
- Remote Extension/Connection Type: Docker
- Logs: [remoteContainers-2021-12-10T15-43-28.898Z.log](https://github.com/microsoft/vscode-remote-release/files/7693872/remoteContainers-2021-12-10T15-43-28.898Z.log)

Steps to Reproduce:

1. Create a project with devcontainer.json and set `dockerComposeFile`.
2. Reopen in container.

And, if I try to start the container from the DockerDesktop GUI, I will see this error.

![image](https://user-images.githubusercontent.com/50911393/145602682-f27d7b1e-d885-4982-b099-080c9c408a8d.png)

**Comment by truong-vonh-ostv** [comment]
@eitsupi I met same your issue. Could you fix it already?
You should downgrade your Vscode version to `1.62.0`. This issue will be fixed
![image](https://user-images.githubusercontent.com/88626098/145750167-60d5fe2e-5e43-433e-bc63-2846f38e9b24.png)

**Comment by chrmarti** [comment]
@eitsupi The environment probe is timing out. What do you get when you run `wsl -e /bin/bash -lic printenv`?

**Comment by chrmarti** [comment]
@truong-vonh-ostv Could you attach the log from an unsuccessful startup? (`F1` > `Remote-Containers: Show Container Log`)

**Comment by truong-vonh-ostv** [comment]
> @truong-vonh-ostv Could you attach the log from an unsuccessful startup? (`F1` > `Remote-Containers: Show Container Log`)

Hi @chrmarti Thanks for your answer about my issue. But after I tried to downgrade my VScode to version `1.62.0`, The issue was fixed, I didn't capture my error info, but It looks same @eitsupi

**Comment by eitsupi** [comment]
@chrmarti 

> The environment probe is timing out. What do you get when you run `wsl -e /bin/bash -lic printenv`?

Logged into fish shell because the last line of `~/.bashrc` is `exec fish`.
Is this the cause? (I haven't checked the behavior without the last line yet)

It used to work fine with this `~/.bashrc`, has something changed?

**Comment by eitsupi** [comment]
I commented out `exec fish`, and it is back to working properly. Thanks.

I would be happy if the original `bashrc` would work as well as the previous version, but if such a fix is difficult, please close this issue.

**Comment by chrmarti** [comment]
@eitsupi Checking if there is a terminal should make it work:
```sh
if [ -t 1 ]; then
    exec fish
fi
```

Let me know if that helps.

What has changed is that we now use an interactive login shell to probe the environment, previously we were using a non-interactive login shell and that does not source `.bashrc`. This change moves the environment we are using for running commands (e.g., the Docker CLI) closer to the environment users are seeing when they run commands from a terminal.

**Comment by eitsupi** [comment]
> Checking if there is a terminal should make it work:
> 
> ```shell
> if [ -t 1 ]; then
>     exec fish
> fi
> ```
> 
> Let me know if that helps.

I works fine, thank you again!
