### ISSUE TITLE
wslview broken ?

### ISSUE THREAD

**Issue by WeiShengv99** [microsoft/vscode-remote-release#6034]
- VSCode Version:
version: 1.63.0 (user setup)
commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
date: 2021-12-07T06:26:56.179Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
- Local OS Version:
 Windows_NT x64 10.0.19043

- Extension Version
 Remote - WSL  0.63.5
- Remote OS Version:
```
➜  rust-hello-world git:(master) ✗ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```
- Remote Extension/Connection Type: WSL
- Logs:

Steps to Reproduce:
[look the context about this problem ](https://github.com/rust-lang/cargo/issues/7557#issuecomment-991485945)

1. open windows sub Linux system,
2. run `code ./`
3. run ` wslview www.google.com ` in vscode shell, it works
4. close windows shell  
5. run   ` wslview www.google.com ` in  vscode shell, it doesn't work

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

when I run `wslview www.google.com` in vscode shell, its return 
```
rust-hello-world git:(master) ✗ wslview www.google.com
<3>init: (3834) ERROR: UtilConnectToInteropServer:307: connect failed 2
<3>init: (3844) ERROR: UtilConnectToInteropServer:307: connect failed 2
<3>init: (3846) ERROR: UtilConnectToInteropServer:307: connect failed 2
<3>init: (3848) ERROR: UtilConnectToInteropServer:307: connect failed 2
```

**Comment by WeiShengv99** [comment]
I don't know what happened, when I reinstall the remote server, it works fine.

**Comment by WeiShengv99** [comment]
but if I close windows shell, the problem is Reproduce

**Comment by aeschli** [comment]
Please file this against https://github.com/wslutilities/wslu. I don't know the mechanism behind the util.
