### ISSUE TITLE
"remoteUser" does not switch to UID/GID when docker host user has GID=100

### ISSUE THREAD

**Issue by hmaerki** [microsoft/vscode-remote-release#6036]
- VSCode Version: 1.63.0
- Local OS Version: Ubuntu 20.04.3 LTS
- Remote OS Version: mcr.microsoft.com/vscode/devcontainers/python/3.9-buster
- Remote Extension/Connection Type: Docker (devcontainer)
- Logs:
```
Step 8/10 : RUN eval $(sed -n "s/${REMOTE_USER}:[^:]*:\([^:]*\):\([^:]*\):[^:]*:\([^:]*\).*/OLD_UID=\1;OLD_GID=\2;HOME_FOLDER=\3/p" /etc/passwd);       eval $(sed -n "s/\([^:]*\):[^:]*:${NEW_UID}:.*/EXISTING_USER=\1/p" /etc/passwd);       eval $(sed -n "s/\([^:]*\):[^:]*:${NEW_GID}:.*/EXISTING_GROUP=\1/p" /etc/group);        if [ -z "$OLD_UID" ]; then            echo "Remote user not found in /etc/passwd ($REMOTE_USER).";     elif [ "$OLD_UID" = "$NEW_UID" -a "$OLD_GID" = "$NEW_GID" ]; then               echo "UIDs and GIDs are the same ($NEW_UID:$NEW_GID).";        elif [ "$OLD_UID" != "$NEW_UID" -a -n "$EXISTING_USER" ]; then          echo "User with UID exists ($EXISTING_USER=$NEW_UID).";         elif [ "$OLD_GID" != "$NEW_GID" -a -n "$EXISTING_GROUP" ]; then                echo "Group with GID exists ($EXISTING_GROUP=$NEW_GID).";       else            echo "Updating UID:GID from $OLD_UID:$OLD_GID to $NEW_UID:$NEW_GID.";          sed -i -e "s/\(${REMOTE_USER}:[^:]*:\)[^:]*:[^:]*/\1${NEW_UID}:${NEW_GID}/" /etc/passwd;                if [ "$OLD_GID" != "$NEW_GID" ]; then         sed -i -e "s/\([^:]*:[^:]*:\)${OLD_GID}:/\1${NEW_GID}:/" /etc/group;             fi;             chown -R $NEW_UID:$NEW_GID $HOME_FOLDER;        fi;
 ---> Running in 73ecc9fcc9b7
Group with GID exists (users=100).
```

### Steps to Reproduce

1. In empty directory: "code ."
2. "Remote Containers: Open Folder in Container ..." -> Python 3.9 -> booster
3. Now the container builds. You see an excerpt of the log above with the message `Group with GID exists (users=100)`
4. In container: `$ id` => `uid=1000(vscode) gid=1000(vscode)`
5. ERROR: I would expect `$ id` => `uid=1000(101438) gid=100(vscode)` (as my user on the docker host)
6. ERROR: As the UID is wrong, I cannot write the files in the workspace.

### Background

In Container `cat /etc/group` => `users:x:100:`
The group `users` seems to be the cause of the error `Group with GID exists (users=100)`.

### Workaround

I add to the `.devcontainers/Dockerfile` this line `RUN groupdel users`.
Now `$ id` return `uid=1000(101438) gid=100(vscode)` and I may access the files in the workspace as expected - great!

**Comment by chrmarti** [comment]
We could remove the conflicting entry from the group file in the container, but that might not always be desirable. What is the local group's name? Also `users`?

**Comment by hmaerki** [comment]
Yes, it is `users`.
``` $ id
uid=101438(hansm) gid=100(users) groups=100(users),999(docker)
```

The solution could also be a more verbose error message like: The group `100-users` is already taken, fix see https://xxx.

**Comment by chrmarti** [comment]
We could check if the existing container group's name is the same as the local one and then just merge the two groups in the container. Unsure which of the two names the resulting group should have (`users` or `vscode` in your example).

**Comment by hmaerki** [comment]
> Unsure which of the two names the resulting group should have (`users` or `vscode` in your example).

I would go for `vscode` as the dev-container is using user:group `vscode:vscode`.

**Comment by didier-booking** [comment]
Wouldn't it work to just update the user anyway and leave the group alone, instead of bailing out completely ?

**Comment by chrmarti** [comment]
@didier-booking We could do that, the result would be files owned by your local user and some random GID. Would that be an improvement?

**Comment by chrmarti** [comment]
I was thinking that to "leave the group alone" also means to let the container user keep its GID, but that would usually not be the same as the host user's GID.

Are you suggesting to update the container user's GID to the host user's GID? That works well when the existing container group with that GID is `users` or similar (and maybe less well when it is `sudo`, `docker` or any other group adding privileges).

**Comment by didier-booking** [comment]
Yeah I meant "if the group with the host user's GID alreay exists in the container then just use that instead of failing". 
But it requires the code to never depend on the fact that the user's group is named "vscode" (not sure why it would, though).

**Comment by chrmarti** [comment]
We could make "users" a special case where we update the user's GID anyway. (Avoiding the update for other groups that could add permissions we don't know about.)

**Comment by chrmarti** [comment]
We now update the UID and leave the GID as-is if the target GID is already in use.
