### ISSUE TITLE
Confused about ports

### ISSUE THREAD

**Issue by valhuber** [microsoft/vscode-remote-release#6037]
Issue Type: <b>Issue</b>

I had been using remote containers for some time - excellent feature.  For reasons I don't understand, my port mapping suddenly was changed.  I was able to repair it on the lower pane.

My questions:

- Any thoughts on why this might occur?  I did not change it.  Is this possibly a response to a port conflict?
- Minor confusion - should ports be visible in left pane?

<img width="1606" alt="managing ports" src="https://user-images.githubusercontent.com/5579631/145695074-4c9c78f8-b018-4f99-a07f-5ada03514096.png">

Extension version: 0.209.5
VS Code version: Code 1.63.0 (Universal) (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (11.32GB free)|
|Process Argv|--crash-reporter-id 3096c2b2-d33c-40f5-9d44-7104519ebb31|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Existing Dockerfile|
|OS|Linux x64 5.10.76-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (2 x 2300)|
|Memory (System)|1.94GB (0.16GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
vsena315cf:30406436
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710:30405998
vscexrecpromp3c:30407761

```

</details>

**Comment by chrmarti** [comment]
The port must have been in use already (maybe temporarily), a different port is then picked automatically.

When you open an URL in VS Code with the container port, that URL is automatically rewritten to one valid on your local machine before it is opened in your browser. (This should be the case in all of VS Code's UI.)
