### ISSUE TITLE
Simple Browser failing with 404

### ISSUE THREAD

**Issue by valhuber** [microsoft/vscode-remote-release#6038]
Issue Type: <b>Bug</b>

Running ApiLogicServer under docker is failing in Simple Browser, works in Firefox (or any other browser).

It is not showing any web console, so it's difficult to diagnose.

The screen shot below shows the 404 failure, but running fine with run by Firefox.

This has run many times before, and runs on other machines.  I am at a loss to understand how to reproduce or diagnose....

<img width="1434" alt="Simple Browser 404 - works Firefox" src="https://user-images.githubusercontent.com/5579631/145697196-b2039728-864f-4d86-92f7-71937c9fb905.png">

Extension version: 0.209.5
VS Code version: Code 1.63.0 (Universal) (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (9.09GB free)|
|Process Argv|--crash-reporter-id 3096c2b2-d33c-40f5-9d44-7104519ebb31|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Existing Dockerfile|
|OS|Linux x64 5.10.76-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (2 x 2300)|
|Memory (System)|1.94GB (0.20GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
vsena315cf:30406436
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710:30405998
vscexrecpromp3c:30407761

```

</details>

**Comment by mjbvz** [comment]
Please provide a set of minimal steps to reproduce the issue

/needsMoreInfo

**Comment by valhuber** [comment]
My problem is resolved, but the main thing here is that I don't have tools to see JavaScript console log, see/clear local storage.  For me, these are the typical things that go wrong.  

Leave it to you to determine if this is out of scope for a "simple" Browser...

**Comment by mjbvz** [comment]
You can use the normal VS Code dev tools to inspect it (`Developer: Toggle developer tools`):
![Screen Shot 2021-12-13 at 8 29 20 PM](https://user-images.githubusercontent.com/12821956/145933200-30c51817-e821-436d-81bb-f47e1aec5307.png)
