### ISSUE TITLE
【loongarch64】 The remote host's architecture is not supported

### ISSUE THREAD

**Issue by yuxingwei** [microsoft/vscode-remote-release#6039]
![image](https://user-images.githubusercontent.com/62556743/145749049-9e0f1c1c-47e2-4007-8d31-7bef7ddd3316.png)
![image](https://user-images.githubusercontent.com/62556743/145748912-e0ea2f29-5e97-4ac2-8fd2-f7f7b9069802.png)

**Comment by tanhakabir** [comment]
Sorry we can't support your remote machine. Please look https://code.visualstudio.com/docs/remote/ssh#_system-requirements and https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites to see what prerequisites we need.
