### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by sampie** [microsoft/vscode-remote-release#6041]
Why "Remote - SSH" extension is not open source? The extension seems not to be available for VSCodium.

**Comment by chrmarti** [comment]
Please see our FAQ on licensing of the VS Code Remote Development extensions: https://code.visualstudio.com/docs/remote/faq#_license-and-privacy

**Comment by sampie** [comment]
Thanks for the link. However, it says that licence is not open source while the extension is in preview phase. How long does the preview phase take? Didn't the extension come out 2019? Surely the preview can't last this long?
