### ISSUE TITLE
After updating remote-wsl, `code .` does't work.

### ISSUE THREAD

**Issue by imdouyu** [microsoft/vscode-remote-release#6043]
- VSCode Version: 1.63.0 (user setup)
- Local OS Version: Win 10(21h1)
- Remote OS Version: Ubuntu 20.04.3 LTS
- Remote Extension/Connection Type: WSL
- Logs:

Steps to Reproduce:

1. Every time after updating remote-wsl, `code .` doesn't work.
![image](https://user-images.githubusercontent.com/59607623/145793103-47bcd763-b92c-486e-825e-b78ec5200d04.png)

2. I found `c:\Users\{username}\.vscode\extensions\ms-vscode-remote.remote-wsl-0.58.5` in `/tmp/remote-wsl-loc.txt`, To work as usually, I manually update `0.58.5` to `0.63.5`, everything is ok. But when next update is coming, I need do the same work.

So how to avoid this case or is there a way to disable a specific extenestion update?

Someone have the same issue in [stackoveflow](https://stackoverflow.com/questions/67802492/visual-studio-code-extension-ms-vscode-remote-remote-wsl-0-54-6-keeps-getting).

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by aeschli** [comment]
Is this still a problem?
