### ISSUE TITLE
@nchandran3 I'll add a setting to turn this off.

### ISSUE THREAD

**Issue by navneetkarnani** [microsoft/vscode-remote-release#6048]
@nchandran3 I'll add a setting to turn this off.

__Originally posted by @chrmarti in https://github.com/microsoft/vscode-remote-release/issues/2470#issuecomment-603322073__

Did a setting get added for this ?

**Comment by chrmarti** [comment]
Two related settings are available:
- You can control if the credential helper should be registered globally, system-wide or not at all.
- You can control if the local `.gitconfig` should be copied to the container.

<img width="716" alt="The two settings." src="https://user-images.githubusercontent.com/9205389/145956959-eb74c227-9358-4ae9-8be9-37076b7a500e.png">
