### ISSUE TITLE
Command request: List PIDs from running container

### ISSUE THREAD

**Issue by aaomidi** [microsoft/vscode-remote-release#6049]
In a lot of remote debugging scenarios, you don't necessarily want to run your entire development stack inside the container, but rather, just the actual binary. In these situations, having an ability to tell the tool "hey, pick a PID from this other context", is super useful.

The way I imagine the flow would work is, inside launch.json of some random workflow. I can replace a field (let's call it PID), with the value of `${command:remote-containers:selectPID}`. This will first give me a dropdown of all the containers running on my system. I select the container I have in mind. And then it will give me a list of PIDs in that container. Selecting that allows me to substitute the PID value with what I selected in the dropdown. 

This feature request isn't directly related to what this extension aims to accomplish, but it probably is the best place for it to live, and is definitely a facilitator for weird development environments.

An example of where this could be useful: https://github.com/golang/vscode-go/issues/1941

**Comment by chrmarti** [comment]
Have you considered filing this as a feature request for the Docker extension? That might be a better place for a generic feature like this.
