### ISSUE TITLE
Open folder with docker-compose hangs after creating container

### ISSUE THREAD

**Issue by talohana** [microsoft/vscode-remote-release#605]
- VSCode Version: 1.35.0
- Local OS Version: Windows 10 Home 64 bit, using docker toolbox version 18.03.0-ce
- Name of Dev Container Definition with Issue: [docker-compose template](https://github.com/microsoft/vscode-dev-containers/tree/master/container-templates/docker-compose)

Steps to Reproduce:

1. Clone this repository
2. Navigate to `container-templates/docker-compose` folder and run `code .`
3. When the window opens, click Reopen in Container
4. docker-compose build runs and hangs after container starting

Hangs with this:
![image](https://user-images.githubusercontent.com/24203431/59130088-24060a80-8977-11e9-9ad2-3179cd180e97.png)

Things I have tried:

1. Setting up workspaceRoot to an empty string in devcontainer.json
2. Re-creating the local docker-machine
3. Following [this issue](https://github.com/microsoft/vscode-dev-containers/tree/master/container-templates/docker-compose)

**Comment by talohana** [comment]
@Chuxel unfortunately I cannot retry with Docker Desktop since I have Windows 10 Home 64bit

**Comment by Chuxel** [comment]
@talohana Ah bummer - ok, watch issue #95 for updates. In concept, it should work, but there may be some subtle thing causing it not to do so.
