### ISSUE TITLE
Cannot clone repository into container volume with remote docker host.

### ISSUE THREAD

**Issue by Clockwork-Muse** [microsoft/vscode-remote-release#6052]
Results in: 
![image](https://user-images.githubusercontent.com/5569508/145892671-9de6ce02-9e13-423f-aa82-c6de4f535277.png)

- VSCode Version: 1.63
- Local OS Version: Windows 11
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Docker
- Logs:

[remoteContainers-2021-12-13T21-34-57.047Z.log](https://github.com/microsoft/vscode-remote-release/files/7707156/remoteContainers-2021-12-13T21-34-57.047Z.log)

Steps to Reproduce:

1. Download the docker cli and place it somewhere the command line can find it.
2. Set up and use a docker context, eg `docker context create somecontext --docker ssh://<remoteuser>@<remoteserver>;` + `docker context use somecontext`
3. Attempt to clone a repository; open the command palette, and select `Remote-Containers: Clone repository in container volume`

... it looks like it might be trying to use docker on WSL, and thus complaining about the missing docker engine, but I specifically **don't** want docker installed, or to use a local container runtime in this instance.  Docker is not installed on WSL, although podman is, and is aliased as docker, but it shouldn't even be touching WSL in this instance - it should be acting against the remote machine.

**Comment by chrmarti** [comment]
I assume you have the Docker CLI installed on Windows (not WSL).

I think you have 'Remote-Containers: Execute in WSL' enabled, try disabling that in the user settings:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/9205389/146356289-c48f81a3-12ff-43a9-8464-f348cfa63c23.png">

**Comment by Clockwork-Muse** [comment]
The mentioned setting was the issue, yes
