### ISSUE TITLE
Using WSL's ssh

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#6053]
Not working for me either, in a slightly different flavor;

I'm on windows 11, connected to a remote Ubuntu machine.  I'm ssh'd into the machine, and can open folders that way, and it picks up the `.devcontainer`, but for some reason it seems to want to run things on WSL:

```shell
[8582 ms] Remote-Containers 0.209.5 in VS Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e).
[8582 ms] Start: Run: wsl -l -v
[8611 ms] Start: Run: wsl -d Ubuntu -e ssh slipstream /bin/sh -c /bin/sh
[8613 ms] Start: Run in host: id -un
# process stuck here for some reason
```
... except the docker cli in Windows has a context pointing it to the remote machine (verified as both the cli and the docker extension properly reflect the remote machine).
WSL doesn't have docker installed, although it does have podman installed and aliased for docker.

_Originally posted by @Clockwork-Muse in https://github.com/microsoft/vscode-remote-release/issues/6021#issuecomment-992926692_

**Comment by chrmarti** [comment]
It is using SSH in WSL (but not Docker or Podman). You probably have this setting enabled:
<img width="707" alt="image" src="https://user-images.githubusercontent.com/9205389/145955176-c83cd298-b73c-4b0f-98fa-d413986cd4eb.png">

Try disabling this setting. Or: Check what happens when you run `wsl -d Ubuntu -e ssh slipstream /bin/sh` in a terminal. Using WSL's SSH should also work.

**Comment by alkatar21** [comment]
I can confirm that this setting is the difference between this behavior and the one in the original issue.

**Comment by Clockwork-Muse** [comment]
I'm pretty sure I had that setting on, yes.
Unfortunately I'm currently away from that machine, and won't be back for a week.

**Comment by Hartorn** [comment]
I think this issue is not linked to wsl, but to id -un, or the following

I run VSCode on Ubuntu 20, but have a similar problem when trying to connect into a container on a remote SSH machine.

```
[2882 ms] Remote-Containers 0.209.6 in VS Code 1.64.0-insider (e8a26d3ebf5095d4324ad4bf794787540ed3b33e).
[2880 ms] Start: Run: ssh xxx.xxx.xxx.xxx /bin/sh -c /bin/sh
[2897 ms] Start: Run in host: id -un

```
It is staying stuck on that.

Just connecting to ssh to the distant machine is fine, same for VsCode ssh, but when trying to attach to a container, it stays like this.

I did try with VSCode, or VScode Insiders, same result

**Comment by alkatar21** [comment]
@Hartorn Have you [set up the ssh-agent](https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent) which is required for this?
The problem is that in the current implementation in the WSL the SSH agent can never run. Especially since probably another ssh-agent should be used. Namely the one that is specified for the other actions via ssh.

**Comment by Hartorn** [comment]
@alkatar21 I can manage to connect in ssh without any issue.
I did just try connecting in ssh, launching agent, then Using vs code ssh + reopen in container : same issue.

**Comment by chrmarti** [comment]
Which OS is the SSH server running on? (Could be https://github.com/microsoft/vscode-remote-release/issues/6055.)

**Comment by Clockwork-Muse** [comment]
@chrmarti - Yes, the setting mentioned was the issue.

**Comment by Hartorn** [comment]
@chrmarti SSH Server was running on Ubuntu 20. Still have the issue at the moment.

**Comment by chrmarti** [comment]
@Hartorn Could you retry with VS Code Insiders and Remote-Containers 0.211.0 with 'trace' logging enabled in the extension's settings and append the log from that?
<img width="344" alt="image" src="https://user-images.githubusercontent.com/9205389/149024219-30e632df-f42a-42d2-b7d7-41221681722e.png">

**Comment by Hartorn** [comment]
So here is it what I've done after settings to trace : 

- Open VSCode Insiders
- Connect with SSH to remote machine
- Type password
- Click on "Reopen in container" popup
- It stays stuck, saying "Setting  up Remote-Containers"

```
[50013 ms] Remote-Containers 0.211.0 in VS Code 1.64.0-insider (753319a08f8e74700b1dba3a29bf0a6af7c2953f).
[50011 ms] Start: Run: ssh xxx.xxx.xxx.xxx (remote IP) /bin/sh -c /bin/sh
[50025 ms] Start: Run in host: id -un
```

Also, when trying to attach to running container, I got the same issue.
Basically, when working locally on the machine, I can attach/open in container just fine, but when using ssh, and then trying to attach, it seems to be blocking.

**Comment by chrmarti** [comment]
What happens when you run `ssh xxx.xxx.xxx.xxx /bin/sh` from a local terminal? Could you append the output?

**Comment by Hartorn** [comment]
@chrmarti So, when doing `ssh xxx.xxx.xxx.xxx /bin/sh`, I got no output.
It stays hanging. I had a look on the receiving computer, and checking the processes, I can see the `/bin/sh` process running.

If I do `ssh xxx.xxx.xxx.xxx id -un`, I got the proper output (user name).

I guess the ssh starts an `sh` session/shell interactive, and this blocks the execution.

**Comment by chrmarti** [comment]
We use the `/bin/sh` session to run commands like `id -un`, not sure why that does not work in your case.

What is the shell you get when you just regularly ssh into the machine?

**Comment by Hartorn** [comment]
Just a bash, classic regular one

**Comment by Hartorn** [comment]
I'm available if you need me to test more stuff, I really would like to fix this problem, as this is quite problematic for me.

**Comment by chrmarti** [comment]
You mention entering the password for Remote-SSH, are you asked for a password after choosing "Reopen in Container"?

**Comment by Hartorn** [comment]
> You mention entering the password for Remote-SSH, are you asked for a password after choosing "Reopen in Container"?

No, I don't have a prompt for password after choosing reopen.

**Comment by chrmarti** [comment]
Adding logging for the next pre-release version.

**Comment by Hartorn** [comment]
Retried today, with Remote-Containers 0.218.0 in Vs Code Insider 1.65.0 (0.283cec6ec...).
No changes (no more logs or prompt for log in)

Am I too early ?

**Comment by chrmarti** [comment]
Could you retry with Remote-Containers 0.219.0 (switch to pre-release version if you haven't) and again post the log with logging for Remote-Containers set to 'trace'?

<img width="359" alt="image" src="https://user-images.githubusercontent.com/9205389/152983109-6d36f90c-f589-41da-8668-a08170c17983.png">

**Comment by lpasselin** [comment]
@Hartorn We had this problem on Mac client, trying to build devcontainer on linux ssh remote host. Same error, stuck on `id -un`.

Fix:
- Setup SSH key on host using ssh-copy-id
- Reconnect to the host as if it was new (SSH Connect to Host -> Add New SSH Host).
- Reopen in devcontainer

Not sure if the second step is required or not but this worked.

**Comment by jacoverster** [comment]
Same issue here, connecting to remote host from WSL using SSH. Tried pre-release with trace logging, also no effect.

**Comment by chrmarti** [comment]
@Hartorn I agree, using public key auth with the private key locally added to the ssh-agent will avoid the password/passphrase prompts and provide a more seamless experience and also work around this problem. It would still be interesting to fix the original problem.

@jacoverster We always use `ssh` on Windows and not the one in WSL. This is to align with Remote-SSH.

**Comment by Hartorn** [comment]
@chrmarti Agreed on this, still happening btw :) Not sure what I can do to help with this

**Comment by chrmarti** [comment]
Now using Remote-SSH to connect.
