### ISSUE TITLE
Kubernetes with Remote-SSH

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#6054]
@chrmarti Haha good point, of course, it is installed. In fact, what you are looking at is not my local vscode at all, it is a remote instance SSH running on a VPS. My local computer is not used for running code or connecting to the cluster at any point.

_Originally posted by @markomitranic in https://github.com/microsoft/vscode-remote-release/issues/12#issuecomment-992599767_

**Comment by chrmarti** [comment]
This needs https://github.com/microsoft/vscode-remote-release/issues/4405 for passing the selection from the Kubernetes extension and changes in Remote-Containers to pass the SSH connection string along.

**Comment by gaocegege** [comment]
Can you please explain more about the feature?

**Comment by markomitranic** [comment]
I can't explain more about the feature, I'm not very proficient in VSCode extension development. However here is a rundown of my setups and the steps I've taken.

### Replication steps:

1. Local runs VSCode
2. Using `Remote-SSH` extension I attach to a VPS
3. The VPS has (or has access to) a k8s cluster
4. In the `Kubernetes Explorer` i right click on a running pod
5. The context menu appears, but there is no `Attach Visual Studio Code` item.

<img width="298" alt="145788212-f728e101-dbd8-4dfd-86cf-5d14cf8f9f66" src="https://user-images.githubusercontent.com/10811624/145976738-1b295a91-33d4-49ef-95a3-dc47575b8cf6.png">


### Expected behaviour:

As seen in the docs, that show it under Pods: https://code.visualstudio.com/docs/remote/attach-container#_attach-to-a-container-in-a-kubernetes-cluster

**Comment by gaocegege** [comment]
Thanks!

**Comment by MurzNN** [comment]
I have the same issue, my original report is here https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1021 but the author says that the problem seems lay in Remote SSH extension.

**Comment by inliquid** [comment]
Same issue.

**Comment by thanhtam98** [comment]
same issue.

**Comment by iceychris** [comment]
Looks like this is an issue with shelling out to `kubectl` without passing the correct kubeconfig or cluster to use. The error message I get is:

```sh
Error running command remote-containers.attachToK8sContainerFromViewlet:
Command failed: kubectl get pod my-pod-dmxnf -o json --namespace default.
This is likely caused by the extension that contributes remote-containers.attachToK8sContainerFromViewlet.
```

I was able to solve this by replacing `∼/.kube/config` (the default config `kubectl` uses when not specifying uses I guess) with the kubeconfig of cluster containing the pod I wanted to attach to.

**Comment by ottoyiu** [comment]
> @iceychris you are able to solve the problem @MurzNN is having?
> 
> On my machine, I have the same issue as both @MurzNN @markomitranic . We can communicate with the cluster (via remote-ssh instance) , this (may) involve setting the config like below, but the option "attach visual studio code" is unavailable.
> 
> if I understand, your solution is to add the path of the kubeconfig file (from your remote server) to the settings.json like below. This just allows VSCode to the access the right configs
> 
> ```
>   "vs-kubernetes.kubeconfig": "/path_to_/.kube/config",
>        "vs-kubernetes.knownKubeconfigs": [
>            "/path_to_/.kube/config"
>        ],
> ```

doesn't seem to fix anything by adding that to the settings.json

**Comment by lupalby** [comment]
I am also affected by this unfortunately. Happy to test anything if a possible solution comes around.

**Comment by felipecrs** [comment]
@chrmarti mind explaining the reason why this was closed?

**Comment by chrmarti** [comment]
This will be available in the next pre-release version of Dev Containers.

The workaround for the missing selection when invoking the action from the context menu in the Kubernetes view is to show the list of pods in a picker at the top of the window.

**Comment by felipecrs** [comment]
This is amazing, thanks a lot.

**Comment by chrmarti** [comment]
Available in Dev Containers 0.386.0-pre-release. The context menu action is also available when connected to a remote host (it will show a picker due to limitations) and there is a new command `F1` > `Dev Containers: Attach to Kubernetes Container...`.

**Comment by lupalby** [comment]
I can confirm that it's working, thank you very much for fixing this! And now I don't even need the kubernetes extension anymore, the dev containers extension is enough. Awesome

**Comment by lupalby** [comment]
@chrmarti perhaps the official instructions should be updated here: https://code.visualstudio.com/docs/devcontainers/attach-container#_attach-to-a-container-in-a-kubernetes-cluster
