### ISSUE TITLE
Remote-Containers: Connect through Windows SSH server

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#6055]
The first line doesn't work, because I'm connecting to a Windows machine, so I'm guessing there's no `/bin/sh`. `ssh localhost` is fine. Also, I'm using the vscode-docs repository to repro this issue (https://github.com/microsoft/vscode-docs/blob/258a90bf0f3e08004d04fc187da968f2f70b2374/.devcontainer). Reopening the local repository in a container works fine, but local -> SSH (Windows) -> Container doesn't seem to be working.

_Originally posted by @rzhao271 in https://github.com/microsoft/vscode-remote-release/issues/6045#issuecomment-992729625_

**Comment by lseongjoo** [comment]
Yes 👍 I have this problem. Mac to windows opening remote container.

**Comment by Steven-Livingstone** [comment]
I'm experiencing the same issue with an identical setup to @lseongjoo.

**Comment by Hartorn** [comment]
Also experimenting this, from an Ubuntu machine towards an ubuntu machine. 
Was working fine in previous build, no longer working.

Not working either on insider build.

**Comment by ServiceAccountOrigin8cares** [comment]
I resolve this by enablgin `remote.SSH.remoteServerListenOnSocket` for it was hanging at different place like hte output of the command was not forwarded correclty.
![image](https://user-images.githubusercontent.com/92868258/180655413-665b9cc4-b458-44c4-b0a1-9ac4dd90be58.png)


Since I did that, start the container take only a few second compare to more than 3 min!

**Comment by taylorkangbeck** [comment]
For anyone looking for a workaround, this is what worked for me.

I was originally trying to connect from my Mac to remote containers on a Windows machine. Instead, I now connect to a WSL distro (Ubuntu) on my Windows machine. You need to run an additional SSH server inside of WSL - more details are in [this post (see "SSH into WSL2 > Full remote WSL2 ssh support")](https://superuser.com/questions/1622581/ssh-into-wsl-from-another-machine-on-the-network/1622603#1622603).

It will also require you to install WSL2 and configure the WSL2 engine in Docker Desktop for Windows.

**Comment by chrmarti** [comment]
The SSH connection part is currently not OSS.

**Comment by adriangh-ai** [comment]
Same issue, MacOS client trying to remotely open containers both through "Remote Explorer" and "Reopen in container" on a Windows 11 host. The logs point out that the extension is trying to run "ssh [address] /bin/sh" on the host, instead of powershell, which throws the corresponding error "The system cannot find the path specified" in both cases. All this while already connected to the vscode server through ssh. "remotePlatform" is set to "windows" on the "SSH - Remote" settings.

Works flawlessly on a Linux host.

Apart from this, great software. Cheers.

**Comment by darkimage** [comment]
getting the same errors the extensions tries to run a sh shell on the windows host connecting using a linux client, is there a workaround?

**Comment by darkimage** [comment]
> any updates on this issue? also connecting to a windows host via mac.

i ended up ssh directly into a ubuntu wsl instance in a windows host where i enabled the docker integration (from the docker desktop running in the windows host), that way the remote containers work. for the direct ssh access into wsl i used [this handy article ](https://medium.com/geekculture/enable-ssh-access-into-wsl-from-a-remote-computer-f2e4a962430#:~:text=The%20only%20way%20a%20remote,e.g.%2C%20Ubuntu%2022.04)%20session.)

**Comment by schiffy91** [comment]
Same issue

**Comment by Paxton0222** [comment]
same issue

**Comment by Paxton0222** [comment]
> Same issue, MacOS client trying to remotely open containers both through "Remote Explorer" and "Reopen in container" on a Windows 11 host. The logs point out that the extension is trying to run "ssh [address] /bin/sh" on the host, instead of powershell, which throws the corresponding error "The system cannot find the path specified" in both cases. All this while already connected to the vscode server through ssh. "remotePlatform" is set to "windows" on the "SSH - Remote" settings.
> 
> Works flawlessly on a Linux host.
> 
> Apart from this, great software. Cheers.

![image](https://github.com/microsoft/vscode-remote-release/assets/62993623/987c720f-fbca-43bb-b286-cbb2f6aca146)
![image](https://github.com/microsoft/vscode-remote-release/assets/62993623/f1d11811-10aa-46f5-b233-4cb50fcf7db9)

I had the same problem as you said, I changed platforms, but it didn't work on my Mac, the bug still there.

My vscode version is:

版本: 1.78.2
提交: b3e4e68a0bc097f0ae7907b217c1119af9e03435
日期: 2023-05-10T15:00:40.428Z
電子: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
作業系統: Darwin arm64 22.4.0
Sandboxed: Yes

**Comment by chrmarti** [comment]
Available with Dev Containers 0.320.0-pre-release and later (requires VS Code 1.84 Insiders or later). https://github.com/microsoft/vscode-remote-release/issues/9095

**Comment by bilby91** [comment]
@chrmarti This should work as well when using Tunnels instead of SSH ?

**Comment by chrmarti** [comment]
@bilby91 Yes, both Remote-Tunnels and Remote-SSH are supported for connecting to Dev Containers.

**Comment by bilby91** [comment]
@chrmarti Thanks for the quick confirmation!

I'm running some issues with both extensions unfortunately :(. 

Reporting the following issue for the Remote-SSH extension (https://github.com/microsoft/vscode-remote-release/issues/9155) and I have a different issue with the Remote-Tunnels one, it just gets stuck. Will try to gather more information and open a different issue.

**Comment by chrmarti** [comment]
@bilby91 Fixed #9155 in Dev Containers 0.322.0-pre-release. When connecting through Remote Tunnels, make sure to use the latest pre-release of Remote Tunnels, that includes some required fixes. (We will release a new stable version of Remote Tunnels soon.)
