### ISSUE TITLE
Delete Partial Lock File on Failed SCP Transfer Attempt

### ISSUE THREAD

**Issue by leifwalsh** [microsoft/vscode-remote-release#6059]
- VSCode Version: Latest Insiders
- Local OS Version: Windows 10
- Remote OS Version: Debian 9
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Connect to a remote SSH session when vscode-server isn't already downloaded on the remote side (for a new host, or after a version update)
2. Do this behind a firewall, where the remote download with `wget` fails, and over a low-bandwidth connection, where the fallback to `scp` often times out.

After the timeout, a lock file is left behind. If you try to connect again, VS Code sees the lock file and thinks another instance is busy downloading the server, and goes into a retry loop. But there's no other instance downloading, connections will fail forever, unless you delete `.vscode-server[-insiders]/bin/<latest commit>`. It seems to me that if the `scp` command fails, it should remove the lock file on its way out. 

I don't think `remote.SSH.useFlock` has any effect on this, on or off.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by eleanorjboyd** [comment]
From my understanding the following fix needs to be executed:

When scp fails due to any reason (but in this case specifically due to timeout) remove all files which are attempted to be installed like lock file before disconnected.

**Comment by roblourens** [comment]
The lock file should be automatically removed when the install script terminates for any reason. Is your remote filesystem NFS? That is where we see the most issues with the lockfile.
