### ISSUE TITLE
Reconnect is broken

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#606]
Issue Type: <b>Bug</b>

With the latest version of insiders, reconnect is broken.

1) Connect to a SSH host
2) turn off your network connection
-> VS Code start trying to reconnect
3) turn on your network connection
-> VS Code enters error state and proposes to reload window

Extension version: 2019.6.9540
VS Code version: Code - Insiders 1.36.0-insider (c089daa858f34631f5f827ff8a0313bf1e2ded6d, 2019-06-07T06:13:41.194Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.18.0-1014-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.54GB free)|
|Process Argv|-psn_0_1544569|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 4.18.0-1014-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.66GB (4.23GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
The resolver does the right thing, then

> `Connection error: Unknown reconnection token.`

**Comment by roblourens** [comment]
We still reference out/vs/server/main.js to kill processes, and I tried to get rid of it, but actually if remote processes clean themselves up then we may not need that kill command anyway.
