### ISSUE TITLE
Please update the changelog for Remote - WSL

### ISSUE THREAD

**Issue by glen-84** [microsoft/vscode-remote-release#6064]
It currently only includes version `0.39.6`.

**Comment by MuriloChianfa** [comment]
mine too =(

![image](https://user-images.githubusercontent.com/60560085/168816933-acae6a62-4011-4095-a725-9b90e76d5344.png)

**Comment by bamurtaugh** [comment]
Thanks for the issue! We include a section for Remote Development updates, including WSL, in the VS Code release notes: https://code.visualstudio.com/updates/v1_96#_remote-development.
