### ISSUE TITLE
docker-compose definitions don't provide additional options in the UX (codespaces desktop)

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode-remote-release#6069]
On codespaces desktop (which implements some shared functionality from remote-containers), selecting a docker-compose definition with customizable `features` or `Dockerfile` options does not initiate the UX prompt to select those additional features.

This doesn't repro in the web, only in the vscode extension on the desktop (v1.4.2)

cc/ @chrmarti @Chuxel

**Comment by aeschli** [comment]
Not sure if I got the steps right, but I still don't see a features selection picker when in a codespace,:

github.codespaces v1.5.0

![Peek 2022-01-28 15-37](https://user-images.githubusercontent.com/6461412/151565682-b641bed6-794a-4cd8-b534-031bd75024a7.gif)

![Peek 2022-01-28 15-39](https://user-images.githubusercontent.com/6461412/151565936-b5cfa624-9829-444f-abb4-d4551143be89.gif)

**Comment by chrmarti** [comment]
Please verify with the `Node.js & Mongo DB` definition. (The `Docker from Docker Compose` definition is using our base image which doesn't work well with our include/exclude logic. I will open a new issue for that.)

**Comment by aeschli** [comment]
Also with the `Node.js & Mongo DB` definition there are no additional quick inputs after selecting the definition.
![Peek 2022-01-31 13-02](https://user-images.githubusercontent.com/6461412/151790601-f1b8d4a3-16e6-419d-8250-e1a91999b860.gif)

On the desktop I get to chose the OS version and features

**Comment by chrmarti** [comment]
Rewritten since, seems to work now.
