### ISSUE TITLE
Open local files in Remote - WSL

### ISSUE THREAD

**Issue by Sumanai** [microsoft/vscode-remote-release#607]
I am opening a VSCode with Remote - WSL to more easily use Linux tools.
But when I open a local file using Windows Explorer or another third-party program, it opens another copy of VSCode without using WSL.
Is there any way to fix this? If you drag a file into the VSCode window, it opens and edits normally.

**Comment by egamma** [comment]
>Is there any way to fix this?

When you open a local file from the internal terminal in a remote WSL window using `code filename`.

**Comment by Chuxel** [comment]
You can also do something like this from Command Prompt that you could probably put in a code.cmd file in your path:

```bat
@wsl code "$(wslpath -a '%1')"
```

**Comment by Sumanai** [comment]
All voiced exit methods will not help when opening files in Windows Explorer or from third-party programs ((
