### ISSUE TITLE
code command errors out when using remote-ssh

### ISSUE THREAD

**Issue by gretzteam** [microsoft/vscode-remote-release#6073]
For some time now the 'code' command to open a file in vscode from the terminal stopped working and gives this error:
```
Unable to connect to VS Code server.
Error in request
```
This is a bit random - sometimes it works fine, and sometimes it doesn't, for exactly the same connection.
Deleting the .vscode-server and reinstalling everything has no effect: behavior is still random.

This is greatly complicating my work as it becomes very cumbersome to open files in the editor from the terminal.

- VSCode Version: 1.63.1
- Local OS Version: Windows 10
- Remote OS Version: CentOS 7
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Initiate a SSH remote connection - this works fine.
2. In the terminal window, type: code filename. For example:
```
code requirements.txt 
Unable to connect to VS Code server.
Error in request
```

3. code -v produces
```
1.63.1
fe719cd3e5825bf14e14182fddeb88ee8daf044f
x64
```

**Comment by tanhakabir** [comment]
Hello! Sorry about the slow response!

Unfortunately on your remote you can't use `code` the same way you'd use on your local machine. There's mutliple `code` executables saved on you machine to handle matching to various versions of VS Code on your local machine and so you'd need to point to the correct executable in the correct folder with a commit id.

You can see more details here and you may need the same request as them too: https://github.com/microsoft/vscode-remote-release/issues/6171
