### ISSUE TITLE
Provide a way to specify remotePlatform mapping outside of settings.json

### ISSUE THREAD

**Issue by ddnomad** [microsoft/vscode-remote-release#6081]
Hi there!

I've being trying to integrate VS Code into my development workflow for working with remote hosts (mostly Windows) and encountered an issue with how platform mappings are saved.

I tend to keep all configuration files for all operating systems I deal with in a single "dotfiles" repository (see [here](https://github.com/ddnomad/dotfiles)). I would like to be able to keep VS Code's `settings.json` in there as well, but this plugins leaks host aliases from my SSH configuration file in the configuration file.

Example:
``` json
{
    "remote.SSH.remotePlatform": {
        "top.secret.fqdn.that.should.not.be.leaked.io": "windows"
    }
}
```

This is not ideal, as I would like to keep my SSH host aliases descriptive and they are usually hostnames or FQDNs of an actual remote server. A lot of them are internal corporate / work hosts and hence their names should never appear in a public Git repository or otherwise.

**Any chance you will add support for a separate configuration file that will contain this information, i.e. `remote-hosts.json` or similar?**

I appreciate that it might not be possible due to various technical limitations, but as it is right now, it's not really usable as I'd have to rename all "private" host aliases into something non-descriptive, which makes it less than ideal to manage.

**Comment by tanhakabir** [comment]
Thanks for the suggestion! I'll label this as a feature request for now and see what complexity there will be to introduce this!
