### ISSUE TITLE
When multiple configurations with different ports but the same host are added, the ssh target list is not complete

### ISSUE THREAD

**Issue by fwgood** [microsoft/vscode-remote-release#6083]
- VSCode Version: 1.63.1
- Local OS Version: Windows 11 21H2 22000.376
- Remote OS Version: WSL 2 Ubuntu 
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Add configurations for the same host with different port numbers. 
2. View the remote plugin configuration list.
3. You will then notice that only one configuration is displayed in the list.

![image](https://user-images.githubusercontent.com/16516811/146731724-1ba14cee-2ec9-4868-9871-d2f78614be61.png)
![image](https://user-images.githubusercontent.com/16516811/146731767-ff02856d-471e-4af7-a0d5-bbcecf10ed3f.png)
![image](https://user-images.githubusercontent.com/16516811/146731799-14fa414b-fff4-4af9-ac55-5f5eb8c833fc.png)
![image](https://user-images.githubusercontent.com/16516811/146731806-8279b0e4-5ed2-4550-ae34-300de5e8888a.png)

My Suggestion:
1. Do not use host as the default name
2. Or display port numbers in the list when host is duplicated.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by eleanorjboyd** [comment]
Hello! My name is Eleanor and I am the new maintainer for the Remote-SSH extension. Are you still experiencing this issue? We have moved to using the Remote-Explorer extension to display targets and I wanted to know if this had made a difference. Thanks!
