### ISSUE TITLE
Working with remote docker container with proxy 407 error

### ISSUE THREAD

**Issue by dishkakrauch** [microsoft/vscode-remote-release#6084]
Hello there!

I've faced huge problem when trying to use vscode remote with proxy inside docker containter.

Here is my Dockerfile:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/34490641/146768566-812ae8a5-3863-4fc9-b6ce-a796e4db642c.png)

Here is an output after I try attach my VS Code to started container:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/34490641/146768644-3e043980-8beb-41e2-86b8-95e8f3d332db.png)

If I attach VS Code shell wget will work insside container.
Can you please help?

**Comment by chrmarti** [comment]
Additionally add the proxy URL including credentials to the `http.proxy` user setting:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/9205389/147071260-cdf3c8a0-8862-4976-8a6a-987bee939717.png">

That will apply locally when downloading the server.
