### ISSUE TITLE
Not all menu options are listed

### ISSUE THREAD

**Issue by amarth1982** [microsoft/vscode-remote-release#609]
Issue Type: <b>Bug</b>

I dont see the commands mentioned as per https://code.visualstudio.com/docs/remote/containers

like 
Remote-Containers: Open Folder in Container
Remote-Containers: Create Container Configuration File

Extension version: 0.60.0
VS Code version: Code - Insiders 1.36.0-insider (c089daa858f34631f5f827ff8a0313bf1e2ded6d, 2019-06-07T05:19:15.188Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.52GB (18.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|31.52GB (18.56GB free)|
|VM|0%|
</details>

**Comment by amarth1982** [comment]
I was able to get the options after I reinstalled the complete ms-vscode-remote.vscode-remote-extensionpack

**Comment by amarth1982** [comment]
reinstall didnt help. I worked for the first time and then again I lost the options

**Comment by roblourens** [comment]
Some commands only appear when in a valid context for them. For example, it looks like you filed this issue from a remote window, and those commands will only show up for a local folder.

**Comment by amarth1982** [comment]
I am not sure what you mean by remote window? I started VS code from WSL. 
I understand command appear based on the context, but as I mentioned earlier, I was able to see it after I reinstalled the pack and lost it after restarting VS Code

**Comment by roblourens** [comment]
If the window is connected to a remote (like WSL) then you will not see those commands. If it's a local window, you should see them.
