### ISSUE TITLE
Every time when i use vscode to connect to a remote host, i need to restart the system before you can connect, or you will get an error "终端进程启动失败: A native exception occurred during launch (Cannot create process, error code: 740)。"

### ISSUE THREAD

**Issue by BA7JCM** [microsoft/vscode-remote-release#6091]
- VSCode Version:
版本: 1.63.2 (system setup)
提交: 899d46d82c4c95423fb7e10e68eba52050e30ba3
日期: 2021-12-15T09:40:02.816Z
(copy from vscode 's "about" )
- Local OS Version:
Windows_NT x64 10.0.22523
- Remote OS Version:
centos8
- Remote Extension/Connection Type: SSH/Docker/WSL
ssh
- Logs:

```
[10:10:59.730] Log Level: 2
[10:10:59.735] remote-ssh@0.70.0
[10:10:59.735] win32 x64
[10:10:59.754] SSH Resolver called for "ssh-remote+<ip>", attempt 1
[10:10:59.754] "remote.SSH.useLocalServer": false
[10:10:59.754] "remote.SSH.showLoginTerminal": true
[10:10:59.755] "remote.SSH.remotePlatform": {"<some my remote host>"}
[10:10:59.755] "remote.SSH.path": undefined
[10:10:59.755] "remote.SSH.configFile": undefined
[10:10:59.755] "remote.SSH.useFlock": true
[10:10:59.755] "remote.SSH.lockfilesInTmp": false
[10:10:59.755] "remote.SSH.localServerDownload": auto
[10:10:59.755] "remote.SSH.remoteServerListenOnSocket": false
[10:10:59.756] "remote.SSH.showLoginTerminal": true
[10:10:59.756] "remote.SSH.defaultExtensions": []
[10:10:59.756] "remote.SSH.loglevel": 2
[10:10:59.756] "remote.SSH.serverPickPortsFromRange": {}
[10:10:59.756] "remote.SSH.enableDynamicForwarding": true
[10:10:59.756] "remote.SSH.serverInstallPath": {}
[10:10:59.758] SSH Resolver called for host: <ip>
[10:10:59.758] Setting up SSH remote "<ip>"
[10:10:59.784] Using commit id "899d46d82c4c95423fb7e10e68eba52050e30ba3" and quality "stable" for server
[10:10:59.788] Install and start server if needed
[10:10:59.791] Checking ssh with "ssh -V"
[10:10:59.825] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.3.3
[10:10:59.831] Running script with connection command: ssh -T -D 19410 "<ip>" bash
[10:10:59.834] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:11:00.133] "install" terminal command done
[10:11:00.134] Install terminal quit with output: 
[10:11:00.135] Resolver error: Error: Got bad result from install script
	at Function.Create (c:\Users\叶子\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:430425)
	at Object.t.tryInstall (c:\Users\叶子\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:523975)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\叶子\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:487216
	at async Object.t.withShowDetailsEvent (c:\Users\叶子\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:490561)
	at async Object.t.resolve (c:\Users\叶子\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:488295)
	at async c:\Users\叶子\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:564197
[10:11:00.140] ------
```

Steps to Reproduce:

every time when i want to use vscode to connect my server to do something,it aslo can't connect and report "终端进程启动失败: A native exception occurred during launch (Cannot create process, error code: 740)。",but when i reboot my conputer and then try to connect to my server with vscode again ,, it can connect to my server normally, but after a period of time, when I want to connect again, the previous problem will appear again, and I need to restart my computer again Can use vscode to connect to the remote device, but I use the ssh command in the "Windows terminal" to connect, everything is normal, only use the vscode connection will have this problem . I have tried uninstalling and reinstalling vscode, but to no avail 

Does this issue occur when you try this locally?: Yes/No
yes,it occur when i try to use the remote connect extensions
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No
no,but when I first started using the remote connection function of vscode, this problem did not occur.

**Comment by tanhakabir** [comment]
Hmm could you try connecting with `remote.SSH.useLocalServer` set to `false`?

**Comment by BA7JCM** [comment]
> Hmm could you try connecting with `remote.SSH.useLocalServer` set to `false`?

It is already "false", but I still cannot connect to my server normally
![image](https://user-images.githubusercontent.com/79561519/148180627-e5a0505e-4c85-413e-8d98-faca29ae33b9.png)
![image](https://user-images.githubusercontent.com/79561519/148180656-2cb82333-f571-4e38-a4af-44e81dba101c.png)

**Comment by tanhakabir** [comment]
Do you have any antivirus software active on your machine? Looking up your error code I see: https://windowsreport.com/createprocess-failed-code-740/#:~:text=Unable%20to%20execute%20file%20createprocess%20failed%20code%20740,have%20the%20necessary%20privileges%20to%20run%20certain%20applications.

Generally what we do in the extension is use your SSH binary on your machine and capturing the output to then prompt for passphrases and to connect.

**Comment by BA7JCM** [comment]
> Do you have any antivirus software active on your machine? Looking up your error code I see: https://windowsreport.com/createprocess-failed-code-740/#:~:text=Unable%20to%20execute%20file%20createprocess%20failed%20code%20740,have%20the%20necessary%20privileges%20to%20run%20certain%20applications.
> 
> Generally what we do in the extension is use your SSH binary on your machine and capturing the output to then prompt for passphrases and to connect.

only windows defender,and i can use "ssh" command to connect my server on command line,but can 't connect on vscode

**Comment by BA7JCM** [comment]
> Do you have any antivirus software active on your machine? Looking up your error code I see: https://windowsreport.com/createprocess-failed-code-740/#:~:text=Unable%20to%20execute%20file%20createprocess%20failed%20code%20740,have%20the%20necessary%20privileges%20to%20run%20certain%20applications.
> 
> Generally what we do in the extension is use your SSH binary on your machine and capturing the output to then prompt for passphrases and to connect.

i tryed to use command to connect my server on cmd,it can work
![image](https://user-images.githubusercontent.com/79561519/148184349-2b59d178-cec9-4aa1-b7ee-0498f98d2439.png)

but vscode can't
![image](https://user-images.githubusercontent.com/79561519/148184444-f6efdea8-6a02-4167-8baa-c9560dfbd905.png)

this is my windows defender 's settings
![image](https://user-images.githubusercontent.com/79561519/148184594-608c40f9-dc88-4344-8273-2d9d24e011e2.png)

everytime when i want to use vscode to connect my server,i can only restart my computer and after it boot finish immediately start  vscode to connect, can' t wait , otherwise i will recive the same error message

**Comment by tanhakabir** [comment]
It's definitely some issue with VS Code being unable to send commands to powershell to execute because of some permissions error. But unfortunately I can't really see what the issue is from your given information.

Were you able to verify everything in the 2 links I had sent you?

**Comment by BA7JCM** [comment]
> From my understanding of the error vscode doesn't seem to have access to spin up the process to actually run `ssh` in.
> 
> You could try looking at [PowerShell/vscode-powershell#2853 (comment)](https://github.com/PowerShell/vscode-powershell/issues/2853#issuecomment-743320342)

![image](https://user-images.githubusercontent.com/79561519/148185257-427cc555-d983-4f83-aca1-5c5b97ea8627.png)

I did not "check the option ‘Run as administrator’" as stated in this issue.

**Comment by BA7JCM** [comment]
> It's definitely some issue with VS Code being unable to send commands to powershell to execute because of some permissions error. But unfortunately I can't really see what the issue is from your given information.
> 
> Were you able to verify everything in the 2 links I had sent you?

and i tryed to run vscode as administrator,it can' t work either

**Comment by BA7JCM** [comment]
> It's definitely some issue with VS Code being unable to send commands to powershell to execute because of some permissions error. But unfortunately I can't really see what the issue is from your given information.
> 
> Were you able to verify everything in the 2 links I had sent you?

But the software started as an administrator seems to have drag and drop disabled in Windows. I can't drag and drop anything from the outside to the inside, nor can I drag and drop anything from the inside to the outside, which is very inconvenient. I tried to search for related keywords on the Internet. But can't find a solution

**Comment by tanhakabir** [comment]
Hmm I just noticed in the above screenshot you opened the permissions for pwsh but not PowerShell. These are separate applications and the remote extension uses PowerShell specifically. Could you check you don't have the admin box checked off on PowerShell as well?

**Comment by BA7JCM** [comment]
> Hmm I just noticed in the above screenshot you opened the permissions for pwsh but not PowerShell. These are separate applications and the remote extension uses PowerShell specifically. Could you check you don't have the admin box checked off on PowerShell as well?

powershell does not have a "compatibility" tab
![image](https://user-images.githubusercontent.com/79561519/148471331-e2a1c547-fff8-4ddd-80dd-41539fb1580e.png)
the cmd didn't have it either
![image](https://user-images.githubusercontent.com/79561519/148471476-4c39882e-2c31-4a87-bf7f-4637e22e0d49.png)
I can’t find anything about setting "Run as administrator" in their properties window

**Comment by BA7JCM** [comment]
> Hmm I just noticed in the above screenshot you opened the permissions for pwsh but not PowerShell. These are separate applications and the remote extension uses PowerShell specifically. Could you check you don't have the admin box checked off on PowerShell as well?

but there is "Run as administrator" for this shortcut in "Shortcut">"Advanced", but that The check box of the option is also unchecked
![image](https://user-images.githubusercontent.com/79561519/148471932-5991c548-ee48-4509-9cd3-c42b1e83223b.png)

**Comment by tanhakabir** [comment]
Hmm I'm not sure now. I can't seem to repro your set up nor can I find any other solutions online. 

If you set up a brand new account on your machine are you able to connect? Maybe something in your PowerShell set up went awry?

**Comment by BA7JCM** [comment]
> Hmm I'm not sure now. I can't seem to repro your set up nor can I find any other solutions online.
> 
> If you set up a brand new account on your machine are you able to connect? Maybe something in your PowerShell set up went awry?

"A new account", do you mean my server or my local computer?i think my server maybe is normal,bacause when i run vsc as admin ,i can connect to it

**Comment by BA7JCM** [comment]
> Hmm I'm not sure now. I can't seem to repro your set up nor can I find any other solutions online.
> 
> If you set up a brand new account on your machine are you able to connect? Maybe something in your PowerShell set up went awry?

In addition, I feel that it may be cmd instead of powershell, because I try to start cmd in the "Windows Terminal" app running as a non-administrator, and the same problem occurs, but it is normal when running as an administrator

**Comment by BA7JCM** [comment]
> Hmm I'm not sure now. I can't seem to repro your set up nor can I find any other solutions online.
> 
> If you set up a brand new account on your machine are you able to connect? Maybe something in your PowerShell set up went awry?

By the way, after I installed the vscode plugin of Microsoft edge and nodejs, when I start vscode, node will pop up a warning box saying "Elevated privileges are required to run"

**Comment by BA7JCM** [comment]
> Hmm I'm not sure now. I can't seem to repro your set up nor can I find any other solutions online.
> 
> If you set up a brand new account on your machine are you able to connect? Maybe something in your PowerShell set up went awry?

i guess maybe they are a same question?

**Comment by tanhakabir** [comment]
Ah I see. You're right in that we seem to default to cmd and try to use cmd but it's blocked by some set of permissions. Unfortunately I really can't advise much more here since I don't know specifically what's happening in the rest of your machine. My only advice is to fix the required admin privileges for cmd since that's probably going to be a problem in many other places too.

**Comment by BA7JCM** [comment]
> Ah I see. You're right in that we seem to default to cmd and try to use cmd but it's blocked by some set of permissions. Unfortunately I really can't advise much more here since I don't know specifically what's happening in the rest of your machine. My only advice is to fix the required admin privileges for cmd since that's probably going to be a problem in many other places too.

i know this,but i try to search on bing and google about this question,but they can.t tell me something about how to fix it,maybe nobody same as me...

**Comment by BA7JCM** [comment]
> Ah I see. You're right in that we seem to default to cmd and try to use cmd but it's blocked by some set of permissions. Unfortunately I really can't advise much more here since I don't know specifically what's happening in the rest of your machine. My only advice is to fix the required admin privileges for cmd since that's probably going to be a problem in many other places too.

But the strange thing is that I directly use the "win+r" key combination, and when I enter cmd in "run", it does not pop up uac (my computer is turned on uac)

**Comment by BA7JCM** [comment]
> Ah I see. You're right in that we seem to default to cmd and try to use cmd but it's blocked by some set of permissions. Unfortunately I really can't advise much more here since I don't know specifically what's happening in the rest of your machine. My only advice is to fix the required admin privileges for cmd since that's probably going to be a problem in many other places too.

or how can i change the setting to use "ssh" this porgram or use other common program?

**Comment by tanhakabir** [comment]
You can try using `remote.SSH.path` to point to a different executable but we will still be using cmd to make the connection

**Comment by BA7JCM** [comment]
> You can try using `remote.SSH.path` to point to a different executable but we will still be using cmd to make the connection

Can it be set to connect directly using ssh.exe, maybe this can bypass this strange problem?

**Comment by BA7JCM** [comment]
> You can try using `remote.SSH.path` to point to a different executable but we will still be using cmd to make the connection

Windows seems to have its own openssh client
