### ISSUE TITLE
ETIMEDOUT connecting from mac to linux box

### ISSUE THREAD

**Issue by xtr0n** [microsoft/vscode-remote-release#610]
- VSCode Version: 1.36.0-insider 
- Local OS Version:Darwin x64 18.6.0
- Remote OS Version:ubuntu 18.04.2
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Click on the green box in the lower left corner "><" 
2. Select Remote-SSH: Connect to Host...
3. Select a host from the hosts file with the following format:
Host <alias>
  User <userid>
  HostName <hostname>
  IdentityFile /Users/<userdirectory>/.ssh/id_ed25519
  AddKeysToAgent yes
  UseKeychain yes
  ForwardAgent yes

This worked perfectly a week ago and I was able to edit code on my linux box from my MacBook.   I'm not sure what changed but one day it would hang when I tried to connect. I can ssh to the machine from the terminal just fine, using the exact same alias config file. 

The only extension I've added to this VS Code insiders install is the remote development pack.  

I have enabled remote.SSH.showLoginTerminal and it looks like there is an ssh connection but then we still time out (see attached screenshot) since the terminal says "Connected to SSH Host - Please do not close this terminal"

If there is particular logging I can enable or gather on either the client or server, let me know. 

I tried to remove the remote server by hand and starting fresh using these instructions https://code.visualstudio.com/docs/remote/troubleshooting#_cleaning-up-the-vs-code-server-on-the-remote, but the error still occurs (although the ~/.vscode-server-insiders directory does come back, so the server install seems to happen) . 

FWIW, I have both insider and non-insider builds of VS code running on the Mac and non-insider VS code running on the linux machine.

![image](https://user-images.githubusercontent.com/18756895/59140676-b990a280-8955-11e9-8dcc-e1d8372d7767.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

This is the output that the "report a bug" feature in VS code gathered:

VS Code version: Code - Insiders 1.36.0-insider (c089daa, 2019-06-07T06:13:41.194Z)
OS version: Darwin x64 18.6.0
Fetching remote diagnostics for 'SSH: dt' failed: connect ETIMEDOUT 10.60.13.143:14378
Item | Value
-- | --
CPUs | Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: enabledoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | 3, 3, 3
Memory (System) | 16.00GB (0.08GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Fetching remote diagnostics for 'SSH: dt' failed: connect ETIMEDOUT 10.60.13.143:14378

Extensions: none

**Comment by asymingt** [comment]
I'm having the issue. I've noticed that the IP referenced by ETIMEDOUT doesn't match my remote server IP, and doesn't respond to a ping. Is there is some caching going on here?

**Comment by xtr0n** [comment]
Is the connection between the VS Code client and server is anything other than vanilla ssh using the creds given when running "Remote-SSH: Connect to Host"?  Are any specific ports used?  I'm wondering if it's possible that a means of communication between the 2 sides is somehow blocked by a firewall on one of the machines?

**Comment by roblourens** [comment]
> Is the connection between the VS Code client and server is anything other than vanilla ssh using the creds given when running "Remote-SSH: Connect to Host"?

No, just running an ssh command with -L to forward a port. 
Could you share the full log from the "Remote - SSH" output channel?

![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Comment by asymingt** [comment]
My problem was due to a corrupted `/etc/hosts` file in OS X that was causing `localhost` to be resolved by DNS. It just so happened that there was a machine called localhost on the domain, but the tunnel obviously could not be established to that host. I solved it by fixing my host file.

**Comment by xtr0n** [comment]
Like @asymingt , my problem was also a corrupted /etc/hosts file in OS X.  I can revert to the crappy hosts file and get the logs just to make sure this is easily diagnosable in the future, if it would help?  I was having trouble finding the full logs when I was trying to diagnose.  Maybe I was just obtuse, but it might be helpful to have a few pointers to the important logs in your docs.    Also, is there absolutely any chance that VS Code may have messed up the hosts file?  I'm not even sure if it would have permissions to do that, but @asymingt and I have been looking @  what we each have installed to both get identical hosts file corruption.

**Comment by roblourens** [comment]
Thanks for following up. I think it's really unlikely that vscode did that. Out of curiosity can you tell me how the hosts file was corrupted?  I wonder whether there is something else in common between the two of you.

Anyway the SSH extension should use `127.0.0.1` instead of `localhost`. I've learned this lesson before...

**Comment by xtr0n** [comment]
Thank *you* for following up!  My hosts file literally contained the following:
`^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@`
I have *no* clue how it got there, but the same thing happened to @asymingt There could be some other application or  maybe a sysadmin script? I'm running in a managed environment but other folks on my team are unaffected, so ¯\_(ツ)_/¯
