### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Rylynnn** [microsoft/vscode-remote-release#6100]
- Issue Type: `Performance`
- Extension Name: `remote-containers`
- Extension Version: `0.209.6`
- OS Version: `Darwin arm64 21.2.0`
- VS Code version: `1.63.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/sz/2vcgy8fd1dv96yjs9p17hsfh0000gp/T/ms-vscode-remote.remote-containers-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by chrmarti** [comment]
Please attach the file mentioned above and provide steps to reproduce.
