### ISSUE TITLE
Task process does not run on folderOpen under Remote - WSL

### ISSUE THREAD

**Issue by kazarmy** [microsoft/vscode-remote-release#6102]
Issue Type: <b>Bug</b>

I have the following in my `tasks.json` (the task is half-done and I'm aware that VSCode doesn't support a project `keybindings.json`, but there is a symbolic link to it and it's under version control):

```json
    {
      "label": "keybindings_mac.json watch",
      "type": "shell",
      "command": "${workspaceFolder}/node_modules/.bin/chokidar",
      "args": ["${workspaceFolder}/.vscode/keybindings.json", "-c",
        "\"echo Watching {path} ..\""],
      "isBackground": true,
      "problemMatcher": {
        "pattern": {
          "regexp": "^.*$"
        },
        "background": {
          "activeOnStart": true,
          "beginsPattern": "^change.*keybindings\\.json.*$",
          "endsPattern": "^Watching.*keybindings\\.json.*$"
        },
      },
      "runOptions": {
        "runOn": "folderOpen"
      }
    }
```

The task process doesn't run on `folderOpen` as per screenshot below:

![onFolderOpen](https://user-images.githubusercontent.com/12002672/147360178-129a58c5-b5c1-4b09-959a-d4e967466058.png)

The task process does run if the task is invoked manually via `Tasks: Run Task`:

![asTask](https://user-images.githubusercontent.com/12002672/147360197-7087e22a-70dd-4d02-968b-d68db6f97fd3.png)

The task process does run on `folderOpen` on Windows and Mac so I don't think this is a POSIX problem.

----

Extension version: 0.63.13
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.01GB free)|
|Process Argv|--crash-reporter-id 0198d331-5e46-4651-b501-67cf2be1e237|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)|
|Memory (System)|12.41GB (11.78GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614
vscexrecpromp3t1:30407762

```

</details>

**Comment by rchiodo** [comment]
This works for me in stable so not sure how to test.

Here's the steps I took:
1. Start WSL
2. Create test folder
3. Create test/.vscode folder
4. Create tasks.json like so:
```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "echo Hello from tasks.json",
            "runOptions": {
                "runOn": "folderOpen"
            },
            "problemMatcher": []
        }
    ]
}
```
5. Open test folder
6. Nothing happens
7. Run task
8. Give permissions to this workspace to run tasks on startup
9. Reopen folder
10. Task runs

I would have expected step 10 to fail on stable?

**Comment by alexr00** [comment]
This is partly a timing issue, so it's not unexpected that some people will not repro the issue in stable. There is not a good way to force the bad timing to occur though.
