### ISSUE TITLE
Remote-Containers: lifecycle commands broken when user home is unconventional

### ISSUE THREAD

**Issue by RLThomaz** [microsoft/vscode-remote-release#6103]
CPUs | Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 2, 2, 2
Memory (System) | 16.00GB (0.54GB free)
Process Argv | --crash-reporter-id e92e772e-962d-4e55-ac01-5d4203cf0f3d
Screen Reader | no
VM | 0%

Remote | Dev Container: Ubuntu
-- | --
OS | Linux x64 5.10.76-linuxkit
CPUs | Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (6 x 2600)
Memory (System) | 1.94GB (0.13GB free)
VM | 0%

Extension	Author (truncated)	Version
remote-containers	ms-	0.209.6
remote-ssh	ms-	0.70.0
remote-wsl	ms-	0.63.13
vscode-remote-extensionpack	ms-	0.21.0

Version: 
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
- VSCode Version: 1.63.2 (Universal) Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
- Local OS Version: Darwin x64 20.6.0
- Remote OS Version: Ubuntu Focal Fossa (20.04)
- Remote Extension/Connection Type: SSH/Docker/WSL (See above)
- Logs: No logs.

Steps to Reproduce:

1. Create a `.devcontainer` folder with a `Dockerfile` and `devcontainer.json`
2. In the `Dockerfile` create a user and assign it an unconvational home directory (e.g., by including a `MY.CORP.DIR` folder).
3. In the `devcontainer.json` add lifecycle commands.
4. Watch the output of the container instance (Remote-Containers); only `postStartCommand` is executed.

Edit: I forgot one very important information, the error is just a "Exit Code 1" and can be seen on the `Dev Containers` terminal as seen below:

```
[3947 ms] Start: Run in container: test ! -f '/home/MY.CORP.DIR/rlthomaz/.vscode-server/data/Machine/.onCreateCommandMarker' && set -o noclobber && mkdir -p '/home/MY.CORP.DIR/rlthomaz/.vscode-server/data/Machine' && { > '/home/MY.CORP.DIR/rlthomaz/.vscode-server/data/Machine/.onCreateCommandMarker' ; } 2> /dev/null
[3950 ms] 
[3950 ms] 
[3950 ms] Exit code 1
[3951 ms] Start: Run in container: test ! -f '/home/MY.CORP.DIR/rlthomaz/.vscode-server/data/Machine/.updateContentCommandMarker' && set -o noclobber && mkdir -p '/home/MY.CORP.DIR/rlthomaz/.vscode-server/data/Machine' && { > '/home/MY.CORP.DIR/rlthomaz/.vscode-server/data/Machine/.updateContentCommandMarker' ; } 2> /dev/null
[3954 ms] 
[3954 ms] 
[3954 ms] Exit code 1
[3954 ms] Start: Run in container: test ! -f '/home/MY.CORP.DIR/rlthomaz/.vscode-server/data/Machine/.postCreateCommandMarker' && set -o noclobber && mkdir -p '/home/MY.CORP.DIR/rlthomaz/.vscode-server/data/Machine' && { > '/home/MY.CORP.DIR/rlthomaz/.vscode-server/data/Machine/.postCreateCommandMarker' ; } 2> /dev/null
[3963 ms] 
[3963 ms] 
[3963 ms] Exit code 1
```

# Dockerfile

```Dockerfile
FROM ubuntu:20.04

# RUN and other Dockerfile commands to prepare the image.

ARG USERNAME=rlthomaz
ARG USER_UID=1000
ARG USER_GID=$USER_UID
# Important bit here: if the home directory is changed to `-d /home/SOME.FOLDER/$USERNAME` it breaks the lifecycle commands
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd -d /home/MY.CORP.DIR/$USERNAME --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
```

# devcontainer.json

```json
// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.209.6/containers/ubuntu
{
	"name": "Ubuntu",
	"build": {
		"dockerfile": "Dockerfile"
	},
	"workspaceMount": "source=${localWorkspaceFolder},target=/home/MY.CORP.DIR/rlthomaz,type=bind,consistency=cached",
	"workspaceFolder": "/home/MY.CORP.DIR/rlthomaz",
	// Set *default* container specific settings.json values on container create.
	"settings": {},
	// Add the IDs of extensions you want installed when the container is created.
	"extensions": [],
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],
	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "uname -a",
	// Comment out connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "rlthomaz",
	"onCreateCommand": "echo OnCreate",
	"updateContentCommand": "echo UpdateContent",
	"postCreateCommand": "echo PostCreate",
	"postStartCommand": "echo PostStart",
	"waitFor": "updateContentCommand"
}
```

Note: If the home directory is unchanged, i.e., `/home/$USERNAME`, then everything works as expected.

Note: If the `remoteUser` is set to root, then everything works as expected; but that shouldn't be a fix (just a clue perhaps).

Does this issue occur when you try this locally?: Not possible to test
Does this issue occur when you try this locally and all extensions are disabled?: No actual extensions installed

**Comment by chrmarti** [comment]
There are marker files in the `/home/MY.CORP.DIR/rlthomaz/.vscode-server/data/Machine` folder, when these exist the corresponding lifecycle command is not run. You seem to be mounting the home folder, I guess these marker files are carried over from the previous container.

**Comment by RLThomaz** [comment]
Thank you for your reploy.

Yes, I am mounting the home folder, and missed that when changing the directory structure. You are correct, the files are there and removing them triggers the lifecycle commands correctly.

Do you think there is a workaround this? My use case is that I need a folder binding my Mac and Ubuntu workspaces, and this should be Ubuntu's home since it has to store some credentials, ssh keys, cookies, and furthemore. And the lifecycle would be fundamental for refreshing some of those files when creating/rebuilding/updating the development container.

**Comment by chrmarti** [comment]
What appears to work:
- Create a folder owned by the user in your Dockerfile: `RUN mkdir /vscode-server-data && chown rlthomaz:rlthomaz /vscode-server-data`
- Create a symlink locally in your workspace folder (delete the existing `.vscode-server` first): `ln -s /vscode-server-data .vscode-server`
- Rebuild container.

This works for me on OSX, not sure if there is a way to place the symlink in a workspace folder on Windows (could try creating it from within the container).

A more convenient way would be to have a way to set the path for the `.vscode-server` folder in the devcontainer.json.

**Comment by RLThomaz** [comment]
Thanks,

I understand my issue better now and how vscode-remote is setup on my system. I really appreciated your help.
