### ISSUE TITLE
CPU usage too high when use the remote-wsl ext

### ISSUE THREAD

**Issue by heng19970427** [microsoft/vscode-remote-release#611]
Issue Type: <b>Performance Issue</b>

wsl: ubuntu 18.04
shell: zsh
vscode version: 1.35.0
windows version: 1809

Extension version: 0.38.0
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (7.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2301)|
|Memory (System)|15.83GB (7.79GB free)|
|VM|50%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    83	  1676	code main
    0	   219	  5952	   window (main.js - ylgk [WSL] - Visual Studio Code)
    0	    51	  6080	     extensionHost
    0	    28	 18352	       electron_node wslDaemon.js 
    0	     5	 10488	         C:\WINDOWS\System32\wsl.exe bash -c "./scripts/wslServer.sh 553cfb2c2205db5f15f3ee8395bbd5cf066d357d stable .vscode-server  "
    0	     6	  9368	           console-window-host (Windows internal process)
    0	     5	 19368	           C:\WINDOWS\System32\lxss\wslhost.exe {e302a621-f0cd-4eab-b4c1-214cab3b79c9} 448 456 460
    0	     8	 10212	             console-window-host (Windows internal process)
    0	    13	 16640	     electron-crash-reporter
    1	   133	  7804	   gpu-process
    1	    68	 12776	   window (问题报告程序)
    0	    69	 13584	   shared-process

Remote: WSL
CPU %	Mem MB	   PID	Process
    0	     0	  1772	remote agent
    0	     0	  1792	   watcherService
    0	     0	  2058	   extensionHost
    0	     0	  2076	     /home/xiaoliu/.vscode-server/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/node /home/xiaoliu/.vscode-server/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-typescript/bed4df17d475b6f73371/tscancellation-760fb273c14e360024f6.tmp* --locale zh-cn --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
    0	     0	  2109	       /home/xiaoliu/.vscode-server/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/node /home/xiaoliu/.vscode-server/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /home/xiaoliu/.cache/typescript/3.5 --enableTelemetry --typesMapLocation /home/xiaoliu/.vscode-server/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation
    0	     0	  2083	     /home/xiaoliu/.vscode-server/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/node /home/xiaoliu/.vscode-server/extensions/dbaeumer.vscode-eslint-1.9.0/server/out/eslintServer.js --node-ipc --clientProcessId=2058
    0	     0	  2126	     /home/xiaoliu/.vscode-server/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/node /home/xiaoliu/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.2.0/dist/server/index.js --node-ipc --clientProcessId=2058
    0	     0	  2174	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  2175	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: WSL|    Folder (ylgk): 91 files|      File types: vue(33) js(24) xml(7) css(3) png(3) less(2) md(2) ttf(2)
|                  ico(2) svg(2)
|      Conf files: package.json(1);
```

</details>

**Comment by egamma** [comment]
Can you provide more information when this exactly happens?
From the Process information doesn't show any high CPU consumption

![image](https://user-images.githubusercontent.com/172399/59584887-82ea2300-90df-11e9-82e0-b0201d971db4.png)


When it happens next time can you run `Help>Open Process Explorer` and try to find the process with high CPU consumption.

**Comment by heng19970427** [comment]
i found it , `zsh`
