### ISSUE TITLE
Debug Config Selector Not updated when launch.json Changed

### ISSUE THREAD

**Issue by fierval** [microsoft/vscode-remote-release#6110]
Issue Type: <b>Bug</b>

1. Attach to a docker container
2. Create or update a launch.json file by adding a debug configuration, save.
3. Click on the Debugger icon in the well.

Observe
The new debugger configuration is not reflected in the "RUN AND DEBUG" selector

Extension version: 0.209.6
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (32.19GB free)|
|Process Argv|. --crash-reporter-id 28592bab-0cbd-42c4-b35d-ec0a4bb99be1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container 33 (suspicious_chandrasekhar)|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 3800)|
|Memory (System)|31.32GB (10.70GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614
py55gd98cf:30411515
vscexrecpromp3c:30407761

```

</details>

**Comment by chrmarti** [comment]
What is the underlying filesystem of the workspace folder containing the launch.json? This sounds like the event for the file update is not propagated. (/cc @bpasero)

**Comment by fierval** [comment]
> What is the underlying filesystem of the workspace folder containing the launch.json? This sounds like the event for the file update is not propagated. (/cc @bpasero)

NTFS

**Comment by chrmarti** [comment]
Confirmed in 1.61. Could be https://github.com/microsoft/WSL/issues/4739.

**Comment by chrmarti** [comment]
Closing as upstream.
