### ISSUE TITLE
Add ability to use buildx and e.g. force --platform linux/amd64

### ISSUE THREAD

**Issue by KrisJanssen** [microsoft/vscode-remote-release#6115]
Issue Type: <b>Feature Request</b>

Running development work on an M1 system with other team members using intel machines. Container on my system will not build due to amd64 specific dependencies. Having the ability to foce the build architecture would solve this.

Extension version: 0.209.6
VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:46.212Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

**Comment by chrmarti** [comment]
You can set the `DOCKER_DEFAULT_PLATFORM` environment variable according to https://docs.docker.com/engine/reference/commandline/cli/ to achieve this.
