### ISSUE TITLE
Openining remote container over SSH fails

### ISSUE THREAD

**Issue by lseongjoo** [microsoft/vscode-remote-release#6116]
Issue Type: <b>Bug</b>

Log is as below (note that broken characters are actual log copied):

remote-containers.reopenInContainer {"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"}
[2021-12-31 17:07:45.441] [exthost] [error] Shell server terminated (code: 1, signal: null)

/bin/sh : '/bin/sh' �� cmdlet, �Լ�, ��ũ��Ʈ ���� �Ǵ� ������ �� �ִ� ���α׷� �̸����� �νĵ��� �ʽ��ϴ�. �̸��� 
��Ȯ���� Ȯ���ϰ� ��ΰ� ���Ե� ��� ��ΰ� �ùٸ��� ������ ���� �ٽ� �õ��Ͻʽÿ�.
��ġ ��:1 ����:1
+ /bin/sh -c /bin/sh
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (/bin/sh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Extension version: 0.209.6
VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No
Remote OS version: Windows_NT x64 10.0.19044

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 2|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 256ef68e-9b28-4651-9e80-aeb13f113979 --crash-reporter-id 256ef68e-9b28-4651-9e80-aeb13f113979|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: big|
|OS|Windows_NT x64 10.0.19044|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3693)|
|Memory (System)|63.94GB (40.92GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710:30416614
py55gd98cf:30411515
vscop841cf:30415854

```

</details>

**Comment by chrmarti** [comment]
Tracked as https://github.com/microsoft/vscode-remote-release/issues/6055.
