### ISSUE TITLE
Clone multiple repositories into container volume

### ISSUE THREAD

**Issue by nnooney** [microsoft/vscode-remote-release#6117]
I have a Hugo website that consists of two git repositories: one for the site content, and one for the theme. I like using the workflow enabled by the "Remote-Containers: Clone Repository in Container Volume..." command. However, I am unable to find a suitable solution for my project setup, which has two git repositories.  What I'd like to happen is that both repositories get cloned into the same volume, at paths like `/workspace/repo-a` and `/workspace/repo-b` and show a multi-root workspace in the explorer pane.

What I've tried so far:
- Manually cloning the repositories and using the "Remote-Containers: Open Workspace in Container..." command. While I am able to open both repositories in a container, it results in a slower and degraded experience (it's recommended to keep the source in the Linux filesystem for WSL, and file notify events aren't implemented for WSL2 yet, see https://github.com/microsoft/WSL/issues/4739 and https://github.com/microsoft/vscode-remote-release/issues/3497).

**Comment by chrmarti** [comment]
https://github.com/microsoft/WSL/issues/4739 should only matter if you use a Windows application to change the files while you have VS Code connected to the dev container. I don't expect that to be the case because you couldn't do that when the repositories are cloned in a Docker volume.

**Comment by nnooney** [comment]
I may be missing something, but I don't believe my repositories are cloned in a Docker volume when I use the workflow "Remote-Containers: Open Workspace in Container..." command. Here's an overview of my directory structure:

```
|   project.code-workspace
\---project-folder
    +---.devcontainer
    +---repo-a
    +---repo-b
```

The `project.code-workspace` file points to the `project-folder`, so that I see both repositories in the container. When opening the workspace, I see this line from the container logs:

```
[7043 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=c:\Users\nicholasnooney\project-folder,target=/workspaces/project-folder,consistency=cached
```

I would like to use a Docker volume instead of a bind mount, but it seems that even if I follow the instructions at https://code.visualstudio.com/remote/advancedcontainers/improve-performance#_use-a-named-volume-for-your-entire-source-tree, it still ends up creating the bind mount above.

I also tried following the instructions in an empty container to build the named volume. I see that it creates the volume, but then I also get the following error message.

![image](https://user-images.githubusercontent.com/3597640/147971654-1dea30c3-51fc-4ac9-9a57-9b24f78ac886.png)

If I select cancel to try and clone the repository as the instructions say, I'm unable to open a terminal, because it instantly closes and the following error message pops up:

![image](https://user-images.githubusercontent.com/3597640/147972059-c07b8808-dd1f-43b1-bf73-5f771597ce52.png)

**Comment by chrmarti** [comment]
You are right. https://github.com/microsoft/WSL/issues/4739 also seems to apply to mounted NTFS folders. (Related: https://github.com/microsoft/vscode-remote-release/issues/6110)
