### ISSUE TITLE
Remote-Container uses incorrect umask 0022 and file permission 644 with vscode(non root) user.

### ISSUE THREAD

**Issue by Uguudei** [microsoft/vscode-remote-release#6118]
VS Code remote-container is using an umask 0022. Is this expected behavour? 

I am using the `vscode` user in the remote container. When I create a file from python code or terminal, file permission is set as 644/umask 0022/. I want files to have permission 664 /umask 0002/. Since I am not using root user, shouldn't the vscode use umask 0002? It seems like a bug.

In my case, files need to have permission 664 in the mounted directory which is shared among multiple users. I have created file in container volume and mounted directory. Both cases have permission 644. 

- VSCode Version: 1.63.2
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Open repo in Remote-SSH
2. Reopen in Folder in Container

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
We could read the umask when we probe the environment variables and set it for launching the VS Code Server. That would require you to set it in `/etc/profile` or the user's `~/.profile` / `~/.bash_profile` scripts. Marking as feature request. (Related for implementation: https://github.com/nodejs/node/issues/32321)
