### ISSUE TITLE
Support for ‘Multilayer connection’

### ISSUE THREAD

**Issue by Arvid-pku** [microsoft/vscode-remote-release#6119]
Sometimes I come into the trouble that the server A I want to connect to requires my computer in the same local network as itself. So I have to connect the other server B (do not need that) first, and ssh connect A from B.

But in that case, I can only see the code on B in the vscode. 
Could you please add the feature that supports the user can see the code on A when he connects B and uses B to connect A?
That will help me a lot! Thanks for your work.

**Comment by chrmarti** [comment]
Try using ProxyJump in your ssh config: https://man7.org/linux/man-pages/man5/ssh_config.5.html

**Comment by Arvid-pku** [comment]
It works! THANK YOU SOOOO MUCH!
Without your advice, I would never know this method.

**Comment by Arvid-pku** [comment]
> Try using ProxyJump in your ssh config: https://man7.org/linux/man-pages/man5/ssh_config.5.html

It works! THANK YOU SOOOO MUCH!
Without your advice, I would never know this method.
