### ISSUE TITLE
plus sign in ssh config Host entry breaks the extension

### ISSUE THREAD

**Issue by makuk66** [microsoft/vscode-remote-release#612]
- VSCode Version: 1.35.0
- Local OS Version:Ubuntu 18.04.2 LTS
- Remote OS Version:Ubuntu 18.04.2 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Add to your `.ssh/config` (from https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Proxies_and_Jump_Hosts):
```
Host *+*
ProxyCommand ssh $(echo %h | sed 's/+[^+]*$//;s/\([^+%%]*\)%%\([^+]*\)$/\2 -l \1/;s/:/ -p /') nc $(echo %h | sed 's/^.*+//;/:/!s/$/ %p/;s/:/ /')
```
2. Reload the Connections list and connect to one of the hosts listed elsewhere in your config
3. Observe the "Checking ... is reachable" notification, but beyond that nothing happens. No error message either.
4. Change the plus sign to "foo". Reload, connect, observe it succeeds

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
Good find

**Comment by makuk66** [comment]
Thanks!
