### ISSUE TITLE
Bound volume is not being created for extensions

### ISSUE THREAD

**Issue by Nefcanto** [microsoft/vscode-remote-release#6122]
- VSCode Version: 1.63.2
- Local OS Version: Ubuntu 20.04 LTS
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: I don't understand this

Steps to Reproduce:

1. According to your [docs](https://code.visualstudio.com/remote/advancedcontainers/avoid-extension-reinstalls), use this `devcontainer.json`
```
{
	"name": "ApiProject",
	"image": "any_image_here",
	"settings": {
		"terminal.integrated.defaultProfile.linux": "bash",
		"terminal.integrated.profiles.linux": {
			"bash": {
				"path": "bash"
			}
		}
	},
	"extensions": [
		"ms-dotnettools.csharp"
	],
	"remoteUser": "vscode",
	"mounts": [
		"source=apiproject,target=/root/.vscode-server/extensions,type=volume"
	]
}
```
2. Then use `docker volume ls`
3. You will not see `apiproject` as a volume.
4. Kill the container
5. Reattach to the container
6. Extension is not shown immediately and takes some time to be shown, which suggests that it gets installed again.

**Comment by Chuxel** [comment]
@Nefcanto You have "remoteUser" set to `vscode`.  In this case the contents would be stored at `/home/vscode/.vscode-server/extensions` rather than root.  Or is this a typo?

**Comment by Nefcanto** [comment]
Thank you @Chuxel. So, if I change it to 'root' it would work? I'll test it and let you know. I guess we need clearer documentation for that `remoteUser`.

**Comment by Chuxel** [comment]
Yeah, docs say:

> Add the following to devcontainer.json, replacing /root with the home directory in the container if not root (for example /home/user-name-goes-here) and unique-vol-name-here with a unique name for the volume:

remoteUser in devcontainer.json reference says:

> Overrides the user that VS Code and other devcontainer.json supporting services tools / runs as in the container (along with sub-processes like terminals, tasks, or debugging). 

We could in concept add a specific mention of remoteUser in the first bit.
