### ISSUE TITLE
Reopen docker-compose project fails with a error "docker-compose -f /Users/my_user_name/my_project_name/docker-compose.yml -f /Users/my_user_name/my_project_name/.devcontainer/docker-compose.yml --profile * config"

### ISSUE THREAD

**Issue by sagarkt** [microsoft/vscode-remote-release#6129]
I restarted my machine and reopened project inside container. Now I am unable to open the project inside container and also not able to rebuild the project.

Starting all services from terminal using below command worked properly. 
```docker-compose up```

Also all services from Docker Desktop mentioned within this docker-compose file can be successfully started.

#### Visual Studio Code

- Version: 1.63.0
- Date: 2021-12-07T05:15:48.091Z (4 wks ago)
- Electron: 13.5.2
- Chromium: 91.0.4472.164
- Node.js: 14.16.0
- V8: 9.1.269.39-electron.0
- OS: Darwin x64 20.4.0

#### Remote Container

- Type: Container
- Version: 0.209.6

#### Local OS

- macOS Big Sur
- Version: 11.3.1
- Chip: Apple M1

Logs: [remoteContainers-2022-01-04T18-48-43.069Z.log](https://github.com/microsoft/vscode-remote-release/files/7809759/remoteContainers-2022-01-04T18-48-43.069Z.log)

### Steps to Reproduce:

1. Create a project with devcontainer.json and set dockerComposeFile.
2. Reopen in container.

#### P.S

- Referred Issue #6032, and Tried to downgrade VS Code Version to 1.62.0. But that didn't resolved the issue.

### EDIT:
I just started project through terminal using ```docker-compose up``` and then tried to attach the running container. I am able to open the folder.

**Comment by chrmarti** [comment]
Could this be https://github.com/microsoft/vscode-remote-release/issues/5992#issuecomment-1000745587?

**Comment by sagarkt** [comment]
@chrmarti looks like mentioning default network in networks in docker-compose.yml file resolved the issue.

Mentioned in details(with filename) for someone who faces this issue. :-)

Safe to close.

**Comment by chrmarti** [comment]
Thanks @sagarkt! Closing.
