### ISSUE TITLE
Investigate using cache volume with Docker Compose

### ISSUE THREAD

**Issue by dfarley1** [microsoft/vscode-remote-release#6132]
- VSCode Version: 1.63.2
- Local OS Version: MacOS Monterey
- Remote OS Version: Gentoo
- Remote Extension/Connection Type: Remote Docker

I'm connecting to a container running on a remote host using the `"docker.host": "ssh://danf@devbox"` setting.
In the container I have a `~/.bashrc` that I'd like to be run when VSCode attaches to the container (right before it installs itself).
However, the Dev Containers logs suggest it's using `/bin/sh`:
```
[15 ms] Remote-Containers 0.209.6 in VS Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3).
[15 ms] Start: Resolving Remote
[16 ms] Setting up container: /home_danf_git_stage
[16 ms] Host: ssh://danf@devbox
[17 ms] Start: Run: ssh danf@devbox /bin/sh -c /bin/sh
[18 ms] Start: Run in host: id -un
...
```

I've tried adding `"terminal.integrated.defaultProfile.linux": "bash"` to my User and Workspace settings.
I've tried adding `export SHELL /bin/bash` to my Docker config (from #350).
If I manually enter the container outside of VSCode I get a `bash` prompt and `echo $SHELL` returns `/bin/bash` as expected.

How do I get VSCode to correctly detect that I want to use `bash` over `sh`?
#38 seems to suggest setting `"terminal.integrated.shell.linux"` but that setting's been deprecated in favor of the terminal profiles so I'd rather not use it?
Is there some other variable that VSCode is looking at when picking `sh` over `bash`?

**Comment by chrmarti** [comment]
We use `/bin/sh` for installing because that is available everywhere. What is in your `~/.bashrc` that needs to run first? (We do extract environment variables from your default shell and pass these along.)

**Comment by dfarley1** [comment]
We want the ability for developers to move the `.vscode-server` location in Containers (I already created #6079). Without some official config flag, I thought I'd add symlink creation to my `.bashrc` to map `$HOME/.vscode-server` somewhere else.

I know we could potentially do this with a Docker volume mount, but because we want it to be developer configurable, we can't just easily modify the project-wide Docker config.

This is primarily to reduce the overhead of reinstalling VSCode when the container restarts, it takes upwards of 90s for installation to finish and our dev containers bounce quite a bit. This is a typical installation log connecting from my laptop at home over VPN to my devobx in the office:
```
...
[1396 ms] Installing VS Code Server for commit 899d46d82c4c95423fb7e10e68eba52050e30ba3
[1396 ms] Start: Downloading VS Code Server
[1396 ms] 899d46d82c4c95423fb7e10e68eba52050e30ba3 linux-x64 stable 
[20494 ms] Start: Installing VS Code Server
[20494 ms] Start: Run in container: mkdir -p /home/danf/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3_1641843856623
[20527 ms] 
[20528 ms] 
[20570 ms] Start: Run in container: (dd iflag=fullblock bs=8192 count=6542 2>/dev/null; dd iflag=fullblock bs=3733 count=1 2>/dev/null) | tar --no-same-owner -xz -C /home/danf/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3_1641843856623
[111486 ms] 
[111488 ms] 
[111489 ms] Start: Run in container: mv -n /home/danf/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3_1641843856623/* /home/danf/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3 && rmdir /home/danf/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3_1641843856623
[111524 ms] 
[111525 ms] 
[111532 ms] Start: Launching Remote-Containers helper.
...
```

**Comment by chrmarti** [comment]
We cache the server download in a temp folder. Moving the cache to a non-volatile location would help. (Related: #2347)

We also cache the server install in a Docker volume `vscode` for single containers (but not Docker Compose). Are you by chance removing this volume sometimes? There is also a user setting to turn the use of this volume off, make sure you have it enabled.
<img width="713" alt="image" src="https://user-images.githubusercontent.com/9205389/149023170-59d9ba4d-a3db-4556-87db-1b844bea78f7.png">

**Comment by dfarley1** [comment]
> We cache the server download in a temp folder. Moving the cache to a non-volatile location would help.

Moving that folder kind of falls under the same issue as this, it needs to be configurable or else I'm gonna have to jump through symlink hoops to move it.

Part of the reason this is such a pain is that my org doesn't really like the idea of IDE or dev-specific config "polluting" the primary config, so editing `docker-compose.yml` with volumes just for VSCode is generally out of the question.

> We also cache the server install in a Docker volume vscode for single containers (but not Docker Compose). Are you by chance removing this volume sometimes?

Not intentionally or often. Maybe once a year I do a `docker system prune`. I do not see any `vscode` volumes listed by `docker volume ls`. The Cache Volume setting is enabled on my laptop as well.

**Comment by chrmarti** [comment]
You would only get that volume when you use a single container. It sounds like you might always be using a docker-compose.yml. We still need to investigate using the cache volume with Docker Compose. We would likely do it by using a docker-compose.yml fragment that Docker Compose then merges in-memory with your docker-compose.yml, so there would be no change on disk for any of your files.

**Comment by chrmarti** [comment]
We are now using the same volume to cache server installs when using Docker Compose.
