### ISSUE TITLE
Unable to access the CLI pipe

### ISSUE THREAD

**Issue by raul-bns** [microsoft/vscode-remote-release#6136]
- VSCode Version: 1.63.2
- Local OS Version: Ubuntu 20.04
- Remote OS Version: CentOS-7
- Remote Extension/Connection Type: SSH
- Logs: The logs of connection are normal, not errors

Steps to Reproduce:
The problem is that in some workspaces when i try to open a file in the terminal with command code i get this error

```
Unable to connect to VS Code server.
Error in request
```
If i delete .vscode-server and I reconnect to recreate the server start to work. After some time start to ocurre again and it's not in all workspace. The rest of the connection works fine

**Comment by aeschli** [comment]
Looks like something wrong with the IPC socket that we use to communicate with VSCode.
There's an environment variable `VSCODE_IPC_HOOK_CLI` that points to a socket file. It is created by the remote terminal process (which is the parent process of all terminals) and also deleted by such. It is only valid for processes running in the remote terminal parent process.
Can you find out if the ENV variable is set and if it points to an existing file?

**Comment by raul-bns** [comment]
Thanks, Il check that.

**Comment by seonglae** [comment]
I have same problem and when I run

```bash
ls $VSCODE_IPC_HOOK_CLI -al
```
Below is output

```
ls: cannot access '/run/user/1000/vscode-ipc-7fda9eca-e873-4070-bd72-338ea1613d5c.sock': No such file or directory
```
![image](https://user-images.githubusercontent.com/27716524/153105887-0f78c04a-5c42-4057-8822-1e99b237b7cb.png)

I can resolve this problem by remove `~/.vscode-server` and reinstall.
However, that tooks long time to reinstall all extensions

**Comment by raul-bns** [comment]
Hi do you have this in your settings
`    "remote.SSH.useLocalServer": true,
`
My college that has this problem didnt put that in his settings. Also he told me that this probleme arrive when he change between workspaces inside of same server, so his solution sometimes is to kill the terminal inside vscode and reopen

**Comment by seonglae** [comment]
Now, upper option doesn't work (ssh v0.74.0)

![image](https://user-images.githubusercontent.com/27716524/155660969-e6f4db1c-cdb8-4a26-a00f-1be91246e867.png)

But I can still open remote server on same instance by VSCode UI
![image](https://user-images.githubusercontent.com/27716524/155661081-ed9da6a7-3a6a-4759-927f-3754a714cec5.png)

**Comment by xyiiinexg3** [comment]
> 

excuse me, do you have a solution? I have the same error. thank you in advance

**Comment by seonglae** [comment]
@xyiiinexg3  I'm not sure when this is happening. I used vscode remote development GUI panel to open saved folder. However, nowadays this error is not happened for me. Did you checked VSC or extention version?

**Comment by roblourens** [comment]
Please let me know whether this is still an issue
