### ISSUE TITLE
How to setup bash-completion post create command?

### ISSUE THREAD

**Issue by LorhanSohaky** [microsoft/vscode-remote-release#6142]
🚨 The issue tracker is not for questions 🚨

After creating the container I want git autocomplete to be working. I trying 
````json
"postStartCommand":"source /usr/share/bash-completion/completions/git",
````

**Comment by LorhanSohaky** [comment]
> The setup run in `postStartCommand` does not carry over to your shell session in the integrated terminal. I would suggest to follow a blog or tutorial on setting up bash completion using `~/.bashrc` and when that works, modify your Dockerfile to automate the config step.

But how can I only append my `.bashrc` into `.bashrc` of container? In the tests I did, I only managed to replace it

**Comment by chrmarti** [comment]
I would only append the completion setup to the `.bashrc` in the container, not the entire `.bashrc` (which might or might not work). The easiest way might be to use `RUN echo "...setup..." >> ~/.bashrc` in the Dockerfile, but this depends on the exact steps to setup completions.
