### ISSUE TITLE
Erroneous documentation

### ISSUE THREAD

**Issue by HM20222022** [microsoft/vscode-remote-release#6143]
Issue Type: <b>Wrong Doc</b>

The name attribute on devcontainer.json isn't used to name a container, as indicated on the online reference : https://code.visualstudio.com/docs/remote/devcontainerjson-reference.

Extension version: 0.209.6
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No
Remote OS version: Linux x64 5.10.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (2 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (2.28GB free)|
|Process Argv|--crash-reporter-id ccb81bbc-cda6-41c0-9329-50498f077fc0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Inspect Volume|
|OS|Linux x64 5.10.76-linuxkit|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (2 x 2593)|
|Memory (System)|1.91GB (0.12GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30414009
pythonvs932:30410667
vscop804cf:30404767
vs360cf:30404996
vsrem710cf:30416617
py55gd98cf:30419166
vscexrecpromp3t1:30407762

```

</details>

**Comment by HM20222022** [comment]
I still find it quite ambiguous. The fact the Docker is currently working on a Dev Environment functionality won't help matters.

Here is what shows up on VS Code when you put your mouse over the name attribute : "A name to show for the workspace folder."

**Comment by bamurtaugh** [comment]
Is there a description you would find clearer @HM20222022? Would mentioning it appears in the lower left remote indicator be helpful?

Do you find the in-product description, `"A name to show for the workspace folder."` to be clear, or do you think that should be updated as well? In which case this issue would involve both the [documentation](https://code.visualstudio.com/docs/remote/devcontainerjson-reference) and the in-product message?

**Comment by HM20222022** [comment]
I think "A name to show for the workspace folder on the lower left remote indicator" on both documentation and in product would be best, since as far as I am aware it is the only effect of the name attribute (though I am not an an expert on Remote-Containers).

The ideal would probably be to extend the use of the name attribute, for example for it to show up on the "recent projects" tab, though that's not an issue about documentation anymore^^.

**Comment by bamurtaugh** [comment]
How about `A name for the workspace folder. It is shown on the lower left remote indicator.`? @chrmarti I could update docs with this, how do you feel about the in-product description?

**Comment by HM20222022** [comment]
Sounds good to me! It would probably be better for the in-product description and the documentation to be the same, so as to leave no room for confusion.

**Comment by chrmarti** [comment]
I wonder if it should be `workspace folder` or `dev container`. The workspace folder already has kind of a name, so maybe `dev container` is better, or does that complicate it?

- `A name for the workspace folder. It is shown on the lower left remote indicator.`
- `A name for the dev container. It is shown on the lower left remote indicator.`

It is also shown in the window title, but calling out the remote indicator makes sense.

Updating it in the schema makes sense, we might want to avoid the VS Code-specific 'lower left remote indicator' and just mention it is shown in the UI.

**Comment by bamurtaugh** [comment]
> we might want to avoid the VS Code-specific 'lower left remote indicator' and just mention it is shown in the UI.

That makes sense to me. Then I'd be in favor of:

`A name for the dev container displayed in the UI.`

> I'm a bit worried that dev container will end up creating a bit of confusion with container names.
Hopefully by specifying "dev container" and adding "displayed in the UI," this could help clarify? I agree with @chrmarti that this property is a bit different than the workspace folder, so I'd prefer to refer to it as the name for the dev container.

**Comment by chrmarti** [comment]
Sounds good, thanks!

**Comment by HM20222022** [comment]
Fine for me too, thanks for your answers!

**Comment by bamurtaugh** [comment]
https://github.com/microsoft/vscode-docs/pull/5108 has been merged, thus updating the property name in docs!

@chrmarti did you want this issue open for updating it in the schema? Should I open a PR to update https://github.com/microsoft/vscode/blob/main/extensions/configuration-editing/schemas/devContainer.schema.src.json#L12?

**Comment by chrmarti** [comment]
Just updated it. Closing this issue, thanks.
