### ISSUE TITLE
Setting remote.SSH.useLocalServer via Settings UI does not update settings.json

### ISSUE THREAD

**Issue by mmahacek** [microsoft/vscode-remote-release#6147]
- VSCode Version:
  - Version: 1.63.2 (system setup)4
  - Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
  - Date: 2021-12-15T09:40:02.816Z
  - Electron: 13.5.2
  - Chromium: 91.0.4472.164
  - Node.js: 14.16.0
  - V8: 9.1.269.39-electron.0
- Local OS Version: Windows_NT x64 10.0.19043
- Remote OS Version:  N/A
- Remote Extension/Connection Type: SSH/Docker/WSL: NA
- Logs: Did not initially identify any related logs.

Steps to Reproduce:

1. Open user Settings
2. Enable the `Remote.SSH: User Local Server` setting
3. The settings.json file is not updated to include the `remote.SSH.useLocalServer` setting
  - If settings.json is manually updated to include `"remote.SSH.useLocalServer": true`, the check box in the Settings UI will update to match.
  - After manually editing the settings.json, if the setting is unchecked in the Settings UI, the setting will be updated to a `false` value in the json.
  - A subsequent re-enable in the UI will remove the `remote.SSH.useLocalServer` line completely from the settings.json file.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by tanhakabir** [comment]
@roblourens have you seen issues in the past where settings UI doesn't reflect the settings.json?

**Comment by roblourens** [comment]
This is by design for the settings editor - when the setting is set to its default value, the entry is removed from settings.json.

Note that it's a little tricky for this particular setting in windows because the actual default just on windows is for it to be disabled. Setting it to true in JSON overrides that default. Ideally we would have platform-specific settings for this setting but we can't express the actual current behavior in an extension.

**Comment by mmahacek** [comment]
@roblourens  Just to clarify, the issue I'm reporting is that the setting does not get set to true in settings.json when clicking it in the Settings UI.

**Comment by roblourens** [comment]
Right, since that is the default value

**Comment by roblourens** [comment]
Actually, I will reopen this, since this setting is here to stay we should look into a better way to deal with it. We could introduce platform-specific settings for this.

**Comment by Zij1n** [comment]
I enabled useLocalServer in setting UI, but when I am trying to connect to a remote host, the log says it is still disabled! I have to write "remote.SSH.useLocalServer" in setting json: true to really enable this. @roblourens

**Comment by mmahacek** [comment]
Closing this issue as I'm not having issues with this in recent versions.
