### ISSUE TITLE
when installing extensions into a container, can it auto-add them to devcontainer json?

### ISSUE THREAD

**Issue by ericblade** [microsoft/vscode-remote-release#615]
... either automatically, or with a "install and add to devcontainer.json" button in the panel?

Finding the package names of extensions is .. difficult? at least, not obvious.. and adding 20 of them is pretty time consuming.

**Comment by Chuxel** [comment]
@ericblade Thanks for the suggestion!  Quick question, is the issue here:

1. That you are having to re-install them on rebuild
2. Or that you are trying to add them to devcontainer.json to share with the team or others?

For the first issue, we've considered using a volume mount to avoid this problem and you can manually set this up now (see #421 or the [docs](https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild) if you are interested). That wouldn't solve the second case, though, so making sure we understand the need.

**Comment by ericblade** [comment]
yes, for my particular use case, i was looking for a way to not have to reinstall everything on a container re-build.  I'd also like to have a large quantity of my extensions available to any containers i decide to use -- and I will make heavy use of them, now that this functionality is in the stable release.  

I did just realize that the extension's package name is in small print next to the large print name of the extension on the page.. so that does make it a bit easier.. still, with some 20 extensions that i want to add, and make sure they get added again on a rebuild.. it'd make it a little easier to have some extra options right from the UI panel.  (add to devcontainer.json, add to "always install this package on remote containers list in settings")

Though granted, that doesn't solve the problem of it taking a long time TO install the extensions -- but i'm more worried about just having them, i don't care if it takes 10 minutes to build the container, as i'm normally not rebuilding frequently.  For people that are, however, the volume solution seems to be a better choice.

I didn't even consider the #2 point.  The project I'm currently working on is all a personal project, so I haven't messed with that.  That does make me consider that maybe there should be some separation of things between "user preferences" and "things this repo needs to have to work" .. where having things like "what ports to forward" are a thing you NEED to have in a devcontainer configuration, but "what extensions are installed" is more a user preference...

**Comment by bamurtaugh** [comment]
I believe feedback along these lines has been helped by: right click -> Add to devcontainer.json.

![image](https://user-images.githubusercontent.com/25310137/96775215-0d115e00-139c-11eb-831a-0f35beae10e7.png)

Closing this issue for now, but please let me know if you have any other questions, feedback, or ideas!
