### ISSUE TITLE
Run and debug not updating after editing the launch.json (using wsl extension)

### ISSUE THREAD

**Issue by Logifire** [microsoft/vscode-remote-release#6154]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.63.2
- Remote - WSL: v0.63.13
- OS Version: Windows 10

Steps to Reproduce:

1. Open your project in WSL (using Microsoft WSL extension).
2. Edit launch.json, add a new configuration option.
3. Try tro run it in the Run and Debug pane (it will not show up in the dropdown).

A) If it is a new configuration it will not show up in the dropdown.
B) If it is an existing configuration, and you edit the name, it will not update the name in the dropdown before running it.

![image](https://user-images.githubusercontent.com/16954276/149015387-e12f9e89-4318-46aa-af52-921fc94ea25e.png)

**Comment by bamurtaugh** [comment]
Thanks for filing. I tried to repro:

- Open project with Remote-WSL
- Run and Debug view -> dropdown -> Add Configuration...
- When I add a config, the dropdown updates. If I remove it, the dropdown removes it.

Are you still experiencing this (or did I miss anything key in my steps above)? Do you experience it locally in VS Code when not connected to WSL with Remote-WSL?

**Comment by Logifire** [comment]
Hi, thank you for trying it out. I do not experience the issue when not connected to WSL 2.

I have tried to disabled all the plugins, and still not working - but on a note, the project I am working on is located in the `/mnt/c` - and i just tried to clone it into the home folder in WSL 2, and this seems to work. So it may have something to do when work with WSL 2 and the C-mount.

**Comment by bamurtaugh** [comment]
Thanks for clarifying - I'm able to repro the issue when using a project on `mnt/c`. cc @aeschli for what might be causing this for mounted projects rather than those in the WSL file system.

**Comment by aeschli** [comment]
See https://github.com/microsoft/vscode-remote-release/issues/5000

This a known issue with WSL2: microsoft/WSL#4739. File events on `/mnt/` drives are not reliable.

**Comment by Cartman0** [comment]
hi! i have same issue too. 
This easy solution is "Restart VSCode" ?

**Comment by aeschli** [comment]
The best is to move your project to the Linux file system. That's much more performant.
