### ISSUE TITLE
Did a request get lost?

### ISSUE THREAD

**Issue by James-Mart** [microsoft/vscode-remote-release#6155]
A feature was marked as a backlog candidate if it could get 10 upvotes:

This feature request is now a candidate for our backlog. The community has 60 days to upvote the issue. If it receives 10 upvotes we will move it to our backlog. If not, we will close it. ...
_Originally posted by @vscode-triage-bot in https://github.com/microsoft/vscode-remote-release/issues/5855#issuecomment-965381744_

The issue was then closed in favor of #3545, which has plenty more than 10 upvotes. But it appears that it's not currently on the backlog?

**Comment by chrmarti** [comment]
Added it to the backlog, thanks.
