### ISSUE TITLE
[feature] Do not edit /etc/environment or at least quote values with spaces

### ISSUE THREAD

**Issue by gabyx** [microsoft/vscode-remote-release#6157]
I think modifying /etc/environment when opening a devcontainer in VS Code, which is obviously the case when `ENV` variables are defined, is not really good. Since it alters the container in a way that can introduce bugs:

An `ENV MYVAR="GAGA GAGA"` will be written to `/etc/environment`:

```
MYVAR=GAGA GAGA
```

Also this is allowed since `/etc/environment` is **not a script file**, it causes problems e.g. for example with `update-info-dir`  (`sudo apt-get install m4`) because it sources the file apparently which crashes because of the spaces (?).

I was wondering why `/etc/environment` is touched and why? Can this be disabled or are quotes actually allowed, if yes, can that be considered?

**Comment by Chuxel** [comment]
Generally this is done to enable things like the PATH to be modified in non-interactive processes that use `sh`.  There are are also scenarios where you get a fresh shell that will not inherit environment variables.  Keep in mind that containers do not have a classic login flow.  

That said, there could be a bug in the specific scenario you're running into.

@chrmarti Is this a bug in the logic we've got around updating /etc/environment?

**Comment by gabyx** [comment]
We experienced this etc/env behavior recently and it did not occur before…

**Comment by chrmarti** [comment]
We are doing this for sshd (https://github.com/microsoft/vscode-remote-release/issues/4781). It seems to work fine using double-quotes for the values, I can add these.

**Comment by rchiodo** [comment]
@chrmarti can you add some verification steps please? Thanks.

**Comment by connor4312** [comment]
Verified vars are now quoted

**Comment by gabyx** [comment]
Sidenote: is it actually allowed to have quotes, because I could not read any spec which says it is for /etc/environment ?
Its just linebased value=….


Von meinem iPhone gesendet

**Comment by chrmarti** [comment]
This file seems to originate from PAM which has documentation on using quotes: http://www.linux-pam.org/Linux-PAM-html/sag-pam_env.html
