### ISSUE TITLE
Dev Container messing up VS Code integrated terminals outside of the Container.

### ISSUE THREAD

**Issue by Nicolascanala** [microsoft/vscode-remote-release#6158]
Hi,

I'm running into an odd issue with the Dev Containers. The containers work great, no problem there! However, after running a container, it messes up my vscode integrated terminal in other windows which are not running a container.

The issue seems to affect my extensions as well. When the terminal is not working, the extensions also disappear. The only way I can get them and the terminal to work again is by quitting every VS Code process and re-launching them. It's even hard to reproduce the issue, as it seems to come and go as it pleases.

- VSCode Version: 1.63.2
- Local OS Version: Mac OS Big Sur, 11.5.2
- Chip: M1 Apple Silicon
- Reproduces in: Cannot seem to reproduce it at will.

**Comment by Chuxel** [comment]
@Nicolascanala Can you explain what you mean by "messes up my vscode integrated terminal"?

**Comment by Nicolascanala** [comment]
> 

Should've been more precise!

By "messes up my vscode integrated terminal" I mean that I cannot type on it. If I open a new terminal, it just opens a blank slate. I don't even see the "bash" or "zsh" options, it's just blank.

This issue is not only happening to me, but to my colleagues as well, unfortunately.

This happens ONLY in the integrated terminal of VS Code, not in my local terminal.

**Comment by Chuxel** [comment]
@Tyriar Is there anything known here already?

/cc @chrmarti as well

**Comment by chrmarti** [comment]
@Nicolascanala Could you try to find steps to reproduce? Also attach a screenshot when this happens again, there might be hints on what is going on.

**Comment by Nicolascanala** [comment]
> @Nicolascanala Could you try to find steps to reproduce? Also attach a screenshot when this happens again, there might be hints on what is going on.

@chrmarti Unfortunately, as I mentioned earlier, I still haven't found a way to reproduce this issue. There seems to be no pattern. The issue pops up either straight away after opening a devcontainer, or it might take half an hour, a full day, half a day, etc. I will attach some screenshots, but I doubt they'll be of much use. As I also mentioned earlier, there's not output of any kind and just blank slates. No changes to VS Code config, nothing that might give us a hint of what's going wrong. I'll make sure to upload those images once the problem pops up again, very frustrating not to be able to reproduce it at will.

**Comment by Nicolascanala** [comment]
@Chuxel @chrmarti The problem showed up again! These images show:

- My terminal before any actions.
- My terminal after opening another integrated terminal.
- My extensions disappearing.

This is a VS Code window that is NOT running a devcontainer, while I run another VS Code window inside a container.

<img width="810" alt="Screenshot 2022-01-14 at 09 33 21" src="https://user-images.githubusercontent.com/75334566/149480858-6671e1e3-c046-43b4-80d4-c82290bfc159.png">

<img width="791" alt="Screenshot 2022-01-14 at 09 33 48" src="https://user-images.githubusercontent.com/75334566/149480946-b60534fd-df7f-4bdb-8dde-30b7a6418e70.png">

<img width="246" alt="Screenshot 2022-01-14 at 09 34 13" src="https://user-images.githubusercontent.com/75334566/149481013-056f48f2-7736-4161-85c4-ba823a752051.png">

**Comment by BrandonOldenhof** [comment]
Just to add a little more context: reloading the window doesn't fix the problem, neither does creating new windows. The only way to get the terminals to work again is to force-quit VSCode and restart it completely.

As you can imagine, this reduces developer efficiency quite a bit.

**Comment by chrmarti** [comment]
@Tyriar That sounds like it might be related to persistent terminal sessions.

**Comment by BrandonOldenhof** [comment]
@chrmarti that sounds like a reasonable hypothesis! I'll try to reproduce this issue over the weekend, both with persistent sessions turned on and with it turned off. I'll add an update here with my conclusions.

**Comment by BrandonOldenhof** [comment]
Hello again! I just ran into the same problem again: I have a DevContainer running and I have a normal VSCode window. I can't create any new terminals in the normal VSCode window, but it works just fine in the DevContainer.

I've added a screenshot of the problem:
- Left: DevContainer
- Right: Normal VSCode window.

If you look carefully you can see there are multiple terminal sessions running on the left, but the "terminal list" on the right is empty, even though I currently have a 2nd terminal session active. The active terminal session item is offset to the bottom because there is another one above it that also doesn't work.

<img width="1918" alt="Screenshot 2022-01-21 at 16 15 35" src="https://user-images.githubusercontent.com/42144260/150551671-11486c43-e1ef-44ba-abc6-4b011f5ab1fb.png">

**Comment by BrandonOldenhof** [comment]
Just to make it a little bit more interesting: my "extensions" panel has also gone blank and the number it shows is incorrect:
<img width="330" alt="Screenshot 2022-01-21 at 16 34 57" src="https://user-images.githubusercontent.com/42144260/150554930-0ac191f0-97eb-479d-a20b-35c3cb11292e.png">

I have 62 extensions installed, as can be seen after I restart VSCode completely:
<img width="293" alt="Screenshot 2022-01-21 at 16 36 20" src="https://user-images.githubusercontent.com/42144260/150555039-2beea6af-9f7d-4d86-96ce-08c92b2c6f35.png">

**Comment by Tyriar** [comment]
The fact that extensions aren't showing up as well is quite puzzling. @deepak1556 any thoughts? Could this be related to M1?

**Comment by BrandonOldenhof** [comment]
@Tyriar that was my thought as well because my colleagues don't have M1s don't have the problem.
