### ISSUE TITLE
SSH_ASKPASS prompt might not work in WSL2?

### ISSUE THREAD

**Issue by jerryc05** [microsoft/vscode-remote-release#6167]
- VSCode Version: 1.64.0-insider
- Local OS Version: Win 11
- Remote OS Version:
```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bookworm/sid
Release:        unstable
Codename:       sid
$ uname -r
5.10.60.1-microsoft-standard-WSL2
```
- Remote Extension/Connection Type: WSL
- Logs:

Steps to Reproduce:

1. Shutdown WSL and fresh restart WSL
2. `git push` a new commit through source control panel in vscode
3. vscode hangs forever (unless I `pkill ssh`)
4. Open terminal, and type `git push`, I saw `Enter passphrase for key '...': `

So clearly `ssh` is assuming we are running inside a terminal, or the SSH_ASKPASS is not causing vscode to prompt for `ssh` passphrase.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
@aeschli @lszomoru any thoughts? It sounds like there's differing behavior in the Source Control view vs using a `git` command in the integrated terminal?
