### ISSUE TITLE
Remote-SSH: Forward Git Credential Helper

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#6168]
I'm in the same situation.
My laptop (Windows machine with Git installed and GCM) and GCM is not forwarded to Remote-SSH Host.

Scenario 1:
My Laptop => Remote-SSH to linux host, trying to clone a repo that have the credentials saved on the windows machine fails.
`$ git config --get credential.helper` empty reply

Scenario 2:
Manually upload the content of the repository to the SSH Host, because there is a .devcontainer that I want to run.
My Laptop => Remote-SSH to linux host => Reopen folder remote container works without issues.
`$ git config --get credential.helper` Returns 
`!f() { /root/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/node /tmp/vscode-remote-containers-673b0b90a3ad4447008f875661559991d7fdb747.js $*; }; f`

Is there any workaround to be able to forward de GCM to the Remote-SSH host?

_Originally posted by @interpeix in https://github.com/microsoft/vscode-remote-release/issues/5977#issuecomment-1012563299_

**Comment by iPoetDev** [comment]
[credential "protocol://hostname/path]
      helper = !<absolute path to command>

Where  !  Everything after is a shell command and is treated as a shell script.

So map your remote command or script to a remote and add the bang character.

Not tested, but is per gitgredentials on git-scm.com.

In theory, a helper can be any external command, script or executable in any language. Git doesn't care so long as the output is accessible.

**Comment by roblourens** [comment]
If this is still an issue, I need an explanation of how to forward GCM (or even what that is exactly)
