### ISSUE TITLE
Password protected ssh-file

### ISSUE THREAD

**Issue by Appelg** [microsoft/vscode-remote-release#617]
I'm using a password protected ssh-key.
First problem was that it took some time to just figure out what was going on.

I expected to be -prompted- for the password, but it just stuck on "verifying connection"... (So I started troubleshooting the connection, firewall rules etc).
You needed to figure out that `"remote.SSH.showLoginTerminal": true` was needed in order to even see the password prompt.

**Possible solution:**
Either just prompt for the password automatically (best solution) or at least document this way better (lets say in the first guide about SSH connecting, a note about pw-protected key files).
Will issue #513 solve this too?

**Next issue:**
It seems that it opens multiple connections? I get prompted for the password several times upon connecting. Really annoying.
Also, it disconnects a lot. Like every 5 minutes. No idea why. "Normal" ssh-usage works fine for the host in question. Guess I might need to troubleshoot that... But this makes me have to enter the password about 2-3 times every 5 min. Maybe it closes connection due to timeout when not actually editing the files?

**Is it possible to "cache" the ssh-key-file-password, or the decrypted keyfile, or .. something(?), so I only need to enter it once every time I start VS-code?
Or is that considered insecure/bad practice?**

This is a really really nice feature, just a bit messy when used with a password protected key file...

**Comment by roblourens** [comment]
Yes, #513 should solve this. If you set up the ssh-agent on your machine and add your key/passphrase to it, then you should be able to connect without typing the passphrase multiple times. 

> Also, it disconnects a lot. Like every 5 minutes. No idea why. "Normal" ssh-usage works fine for the host in question.

Most likely there is some flakiness in your network. It's also possible that you are using an extension that causes the remote extension host to be busy for 10 seconds at a time.

> Is it possible to "cache" the ssh-key-file-password, or the decrypted keyfile, or .. something(?), so I only need to enter it once every time I start VS-code?

No, I think this is not safe. But we are still working on this.
