### ISSUE TITLE
Add remote vscode-server code executable path that persists between versions

### ISSUE THREAD

**Issue by jonathanq9** [microsoft/vscode-remote-release#6171]
I'm using vscode remote-ssh and executed `Shell Command: Install 'code' command in PATH ` to add vscode code executable to the remote server path but it did not work. 

Upon further research I was able to manually add the vscode code executable path `~/.vscode-server/bin/<commit-id>/bin/code` and it now works as expected.
```
code --version   
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
```
My understanding is that the vscode-server path `commit-id` changes with each new version upon connection and versions older than the last 5 versions are deleted. Essentially this would mean that every 6th version of vscode-server would require you to update the remote vscode-server code executable path since only the last 5 versions are kept.

**Feature Request:**

Can you add a way to have the remote vscode-server code executable path persist between versions that does not use the vscode version commit-id in the file path?

**Comment by bamurtaugh** [comment]
@tanhakabir does this feel related/tangential to https://github.com/microsoft/vscode-remote-release/issues/6146?

**Comment by mr-eyes** [comment]
Here's a workaround that worked for me.

```bash
code_latest_version=$(ls -tral -1 ~/.vscode-server/bin | sed -n '2p' | rev | cut -d' ' -f1 | rev)
export PATH=${HOME}/.vscode-server/bin/${code_latest_version}/bin/remote-cli:$PATH
```

**Comment by tanhakabir** [comment]
Oh sorry for the late response! I believe this should already work where the latest path to the code executable is set in your PATH. Are you note seeing it in there?

**Comment by tanhakabir** [comment]
Related issue: https://github.com/microsoft/vscode-remote-release/issues/6289
