### ISSUE TITLE
Remote-WSL: Add 'Kill server' similar to Remote-SSH

### ISSUE THREAD

**Issue by vvavrychuk** [microsoft/vscode-remote-release#6177]
I would like to reload shell configuration in VS Code terminal opened from the Remote-WSL VS Code window. Reopening VS Code terminal or reopening VS Code might not be enough for that when variables setting is removed in new configuration, it will be still present from parent WSL server shell.

**Comment by bamurtaugh** [comment]
Thanks for filing @vvavrychuk! This is quite related to https://github.com/microsoft/vscode-remote-release/issues/5568; would you mind including that ask in that issue, and then we could close out this one?

**Comment by bamurtaugh** [comment]
Closing in favor of https://github.com/microsoft/vscode-remote-release/issues/5568.
