### ISSUE TITLE
Using Fedora 35 with 'which' installed fails to install dotfiles in docker remote

### ISSUE THREAD

**Issue by BenjaminSchubert** [microsoft/vscode-remote-release#6180]
## System information

- VSCode Version: 1.63.2
- Local OS Version: Windows 11, build 22000.434
- Remote OS Version: Fedora 35
- Remote Extension/Connection Type: Docker

## Explanation

When using a devcontainer project based on Fedora, in which `which` is installed, the dotfiles fail to be installed.

This seems to be because Fedora provides an alias for `which` in `/etc/profile.d/which2.sh`, like so:

```sh
# shellcheck shell=sh
# Initialization script for bash, sh, mksh and ksh

which_declare="declare -f"
which_opt="-f"
which_shell="$(cat /proc/$$/comm)"

if [ "$which_shell" = "ksh" ] || [ "$which_shell" = "mksh" ] || [ "$which_shell" = "zsh" ] ; then
  which_declare="typeset -f"
  which_opt=""
fi
 
which ()
{
(alias; eval ${which_declare}) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot "$@"
}

export which_declare
export ${which_opt} which
```

I could not find where the check is made, and the dotfiles installed in the Code.

## Steps to Reproduce:

1. Set a dotfiles repository in your settings. E.g. `"remote.containers.dotfiles.repository": "https://gitlab.com/BenjaminSchubert/configuration"` in your settings.json file.
2. Using the following configuration:
```json
// devcontainer.json
{
	"name": "Fedora",
	"build": {
		"dockerfile": "Dockerfile",
	},
	"remoteUser": "vscode",
}
```
```
// Dockerfile
FROM fedora:latest
RUN dnf install -y git which && \
    useradd -m vscode
```

When opening this remote-container configuration, you will notice that the dotfiles did not get downloaded correctly, and an error will be shown in the logs, looking like:

```
[156912 ms] Start: Run in container: # Clone & install dotfiles
[156914 ms] /bin/sh: line 48: BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot "$@"
}: No such file or directory
```

Adding `RUN rm /etc/profile.d/which2.sh` at the end of the Dockerfile allows installing the dotfiles correctly.

I therefore believe that the dotfiles installation has a bug and invokes `which` incorrectly. However I could not find where this is done to actually be able to test a fix.

I'd be happy to help fixing this if I can get pointers as to where this is done.

**Comment by PavelSosin-320** [comment]
Please, provide the exact type of your Fedora 35 installation Workstation or Server and how your installed Docker [Docker installation](https://docs.docker.com/engine/install/fedora/). Note: 1. Fedora 35 is completely systemd-based system 2.Fedora 35 uses systemd-homed to manage "Home area". It elevates security dramatically but has some side effects. Dotfiles are located in the "Home area" that available only upon successful login. Even processes running under root has restricted access to the user's home area - it is completely private. 
Since Fedora 35 doesn't allow to disable SELINUX & POLKIT VSCode may be in troubles.

**Comment by BenjaminSchubert** [comment]
@PavelSosin-320 

Sorry I realized this is unclear:

- The host system is Win 11 (I can also reproduce that on a linux based system)
- Docker is installed in WSL2 (Ubuntu based)
- The "remote" (the container) runs fedora, and is based on the `fedora:latest` image, so server vs workstation doesn't apply.
- Selinux is also disabled and systemd not used, since we are in a container.

And I believe none of this is relevant, since removing `which` from the image, or removing the `/etc/profile.d/which2.sh` fixes the problem.

However those questions make me doubt: is this really the repo for vscode-remote-containers releases? Or did I post this on the wrong repository?

**Comment by chrmarti** [comment]
I can remove `BASH_FUNC_...%%` variables before installing dotfiles using `/bin/sh`. Not sure if the other shells are using a similar approach to export functions, but these might then need a similar fix.

**Comment by PavelSosin-320** [comment]
@chrmarti Good luck ! RedHat uses its own development stack and Fedora cloud images can be produced  without Docker, from scratch or from UBI image. Fedora repositories, package manager, init (systemd) are radically different from Ubuntu and Debian. Most of system utilities are plain CLI of system services running as Units. Podman team demonstrated the Windows WSL based Podman-on-Fedora as application. It will be certainly more stable runtime for RedHat's images.

**Comment by PavelSosin-320** [comment]
@chrmarti It can be security-related problem. Fedora always assumes that SELinux is active. It can't be disabled in neither distro or Official docker images that are cut by RedHat from Fedora project repository. The Fedora ISO and Fedora/Fedora images are not exclusion as I saw looking under the hood of the image posted to DockerHub. SELinux in Fedora 35 tends to prevent any altering of dot scripts and systemd Unit files to prevent huge breach in security - remote altering of the specific user's login process, services startup, etc.
