### ISSUE TITLE
unable to connect vscode studio to container running on remote machine

### ISSUE THREAD

**Issue by danielgrzenda** [microsoft/vscode-remote-release#6181]
- VSCode Version: 1.63.2
- Local OS Version: WSL2 (Ubuntu 20.04) (Windows 10.0.1.19042)
- Remote OS Version: Linux 18.04
- Remote Extension/Connection Type: SSH and Docker

- Logs: 
Error running command remote-containers.attachToRunningContainerFromViewlet: Shell server terminated (code: 255, signal: null) ssh: Could not resolve hostname `<ssh host string>`: No such host is known. . This is likely caused by the extension that contributes remote-containers.attachToRunningContainerFromViewlet.

- Extension Host Log:
ssh: Could not resolve hostname `<ssh host string>`: No such host is known. 
 remote-containers.attachToRunningContainerFromViewlet {"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"}

Steps to Reproduce:

1. open folder in WSL 
2. `ctrl-shift-p` + remote-ssh connect to host (select `<ssh host string>`)
3. go to docker pannel 
4. launch container
5. right click container and connect vscode studio

I get a similar error if from the ssh machine I try `ctrl-shift-p` + open in container.

I have tried with a folder open in the ssh-remote window and without. I have also tried connecting to the docker container using the remote explorer instead of through the docker extension. 

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
Is the SSH host listed in the `~/.ssh/config` or a plain hostname? (If you list it in a separate SSH config file you use with Remote-SSH, the `Remote.SSH: Config File` setting is supported with the development version of Remote-Containers and will be available with VS Code 1.64.)

**Comment by danielgrzenda** [comment]
Currently I'm using WSL and remote containers is pointed at `C:\\Users\<username>\.ssh\config`. Could that be causing the problem? 

In the config file the host is listed like this: 

```
Host <shortname>
    HostName <static-ip-address>
```

**Comment by chrmarti** [comment]
Correct, try disabling `Execute In WSL` if it is enabled in your user settings:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/9205389/151781329-0642f4e8-5d3a-499d-95f8-59d7a8d4c7a6.png">

More recent versions of Remote-Containers ignore that setting when connecting to an SSH server (since Remote-SSH doesn't use that setting either).

**Comment by danielgrzenda** [comment]
Enabling this setting acutally fixed the problem. I can open the dev container on the remote server. My ssh-agent still isn't forwarding but I think that's a separte issue. Thanks for your help.
