### ISSUE TITLE
Containers' download filesystem function sanitizes filename with env

### ISSUE THREAD

**Issue by dewcked** [microsoft/vscode-remote-release#6183]
- VSCode Version: 1.63.2
- Local OS Version: Windows 10 21H2 19044.1466
- Remote OS Version: Debian GNU/Linux 11
- Remote Extension/Connection Type: WSL2
- Logs: x

Steps to Reproduce:

1. create file or directory with filename that includes environment variables surrounded with % (e.g. `foo%username%bar`)
2. download file with Remote - Containers extension
3. see the part surrounded with % are replaced into environment variable value.

Does this issue occur when you try this locally?: Yes?
Does this issue occur when you try this locally and all extensions are disabled?: Yes?

**Comment by bpasero** [comment]
> download file with Remote - Containers extension

What exactly is that action? Can you show a gif?

**Comment by dewcked** [comment]
@bpasero 
https://gfycat.com/keenzestyladybug

**Comment by bpasero** [comment]
I can confirm this happens and it seems that the Windows explorer dialog replaces file names that contain `%` with the respective environment variables. I see the same behaviour with other apps that show such a dialog.

I suggest you file a bug against Windows.
