### ISSUE TITLE
Remote SSH does not re-execute RemoteCommand on window reload or short-term reconnect

### ISSUE THREAD

**Issue by markusdd** [microsoft/vscode-remote-release#6187]
VSCode Version: 1.63.2
    SSH Remote extension latest preview (v0.71.2021121615 Pre-Release)
    Local OS Version: Fedora 35
    Remote OS Version: CentOS 7.9
    Remote Extension/Connection Type: SSH

Consider the following env setup using RemoteCommand in ssh-config:

```
Host slpcomp1-project1
  HostName slpcomp1
  User mkrause
  ForwardX11 yes
  RemoteCommand bash -c "export PRJHOME=/lscratch/mkrause/project1; export TOOLS=/tools/version1; bash"
```

After connecting we get the expected env:
![image](https://user-images.githubusercontent.com/25175069/149996794-1e4e9624-896c-4a54-82e4-cfa1deb500f1.png)

Now consider our project moved to a version2 toolset, so we update our environment (this could either be directly in the ssh config or a file that is being sourced upon shell entry, I do it in the command here):

```
Host slpcomp1-project1
  HostName slpcomp1
  User mkrause
  ForwardX11 yes
  RemoteCommand bash -c "export PRJHOME=/lscratch/mkrause/project1; export TOOLS=/tools/version2; bash"
```

Now I use 'Windows Reload' or 'Close Remote Connection' followed by 'Connect Host to current Window' to reload my connection, expecting the variable to be `TOOLS=/tools/version2`, but instead we get this:
![image](https://user-images.githubusercontent.com/25175069/149997540-363bf74c-f87d-4ed6-b700-56a6d885cd2c.png)

Like in issue #6186 the connection is being re-used, although when a RemoteCommand is being used that cannot be done. Remote Commands (which is the whole purpose of the feature) can alter the environment code runs in, so assuming it just is the same on reconnect or reload is not correct beahvior.

The only way to circumvent this currently is to use the 'Kill Remote server on machine XYZ' command, but this takes long as it unncessarily even erases the whole code server data and combined with issue #6186 it is even fatal because if you have 2 different workspace connections to the same machine you would currently kill the other editor connection.
Also it is unreliable as we have found if user homes are on NFS drives (which is often the case). Sometimes you need to run it twice to really get rid of everything and restart.

There are even further complications because currently, except for the entries that VS Code itself offers under recent, there is no way to actually setup a connection which right away opens a workspace file. You always get connected to the machine first without any workspace, although the remote command sets up an environment for a specific workspace in many cases.

So maybe you should consider instead of only using the ssh config having a proper config file for workspaces for this extension where everything can be specified. And then upon Window reload do an actual restart of the ssh connection and remote shell env and not re-use what is still there although it might be outdated and provide a wrong environment. I think the current granularity this extension runs on is the remote machine itself, which is kind of ok for container connections but most probably not for SSH, where usually many parallel sessions access powerful central compute nodes.

So in my view:

Quick fix: Provide a proper quick reload option which cleanly re-establishes the connection without deleting the whole server infrastructure.

Proper fix: Treat the remote setup either per node (as is it now) OR optionally per workspace, so that workspaces can coexist with different environments on the same remote machine and can be reloaded independently.

/cc @mhoeher

**Comment by tanhakabir** [comment]
Closed in favor of https://github.com/microsoft/vscode-remote-release/issues/6186 which would solve this issue as well.

**Comment by markusdd** [comment]
I agree this can be incorporated into #6186, with the one addition that a window reload causes a proper env reload on the server side. Because otherwise you still get the lengthy: disconnect, kill server, reconnect procedure which can take multiple minutes because the server gets reinstalled after the kill and not just restarted.
