### ISSUE TITLE
Allow disabling container persistence

### ISSUE THREAD

**Issue by chriskuech** [microsoft/vscode-remote-release#6190]
VS Code development containers seem ideal for destructable management containers that can be used for managing infrastructure without leaking credentials.  The only problem is that VS Code development containers are persistent, so credentials can be leaked.  I would like a flag to allow non-persistent containers--containers that are **not** saved to disk after execution.

**Comment by chrmarti** [comment]
"containers that are saved to disk after execution", do you mean "removed from disk"? That wouldn't make credentials safe I think. 1 They are still stored temporarily. 2 Deletion from disk might be incomplete depending on how it works and is implemented.

**Comment by chriskuech** [comment]
> "containers that are saved to disk after execution", do you mean "removed from disk"?
Yes (updated inline)

> 1 They are still stored temporarily. 2 Deletion from disk might be incomplete depending on how it works and is implemented.
Yes, but at least still free from the normal cred file scanning malwares.  Imperfect, but much better than nothing.

**Comment by chrmarti** [comment]
If you are running a single container (not using Docker Compose) you can add `"runArgs": ["--rm"],` to the devcontainer.json for doing this. The container is automatically stopped 10 seconds after VS Code disconnects and `--rm` will let Docker remove it after it stopped.

Continuing tracking in https://github.com/microsoft/vscode-remote-release/issues/3512.
