### ISSUE TITLE
Code command not installed on remote

### ISSUE THREAD

**Issue by benbuzbee** [microsoft/vscode-remote-release#6191]
Issue Type: <b>Bug</b>

Connected to new remote VM via remote-ssh

vagrant@cloudchamber-devbox:~/salt$ code --help
bash: code: command not found

Docs imply this should work, and I believe it used to on my old VM?

https://code.visualstudio.com/docs/remote/ssh#_opening-a-terminal-on-a-remote-host

Extension version: 0.70.0
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-91-generic
Remote OS version: Linux x64 5.10.0-9-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 x 3504)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (20.11GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bhivemind/home/bbuzbee/repos/cloudchamber/cloudchamber-nomad-driver --crash-reporter-id a76a0714-9707-4cf7-bfff-3faff2f083a3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: hivemind|
|OS|Linux x64 5.4.0-91-generic|
|CPUs|AMD Ryzen Threadripper 1950X 16-Core Processor (32 x 2187)|
|Memory (System)|31.29GB (14.24GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: cc-devbox|
|OS|Linux x64 5.10.0-9-amd64|
|CPUs|AMD Ryzen Threadripper 1950X 16-Core Processor (27 x 3393)|
|Memory (System)|15.63GB (13.34GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30424896
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710:30416614

```

</details>

**Comment by benbuzbee** [comment]
Perhaps this is because something that is supposed to update PATH is not working?

Seems to be available here:
/home/vagrant/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/bin/code

What process is supposed to make this available on PATH? I have done this for now:
export PATH=/home/vagrant/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/bin:$PATH

**Comment by benbuzbee** [comment]
Sorry for the noise, bashrc overwrites path for me.

**Comment by Jason5Lee** [comment]
I got the same problem. `code` bin not exists under `/home/jason5lee/.vscode-server/bin/*` .
