### ISSUE TITLE
Adding new host breaks ssh config file when there are spaces in the host

### ISSUE THREAD

**Issue by seaofbits** [microsoft/vscode-remote-release#6197]
- VSCode Version: 1.63.2 (system setup)
- Local OS Version: Windows_NT x64 10.0.19042
- Remote OS Version: N/A
- Remote Extension/Connection Type: SSH
- Logs: N/A

On my windows computer, I have a configuration like this, and noticed there are spaces in the host:
![before](https://user-images.githubusercontent.com/38586229/150293221-1ccf4efe-995c-460d-8aac-b15eb50ec10a.png)

After adding a new host by clicking the "+" button, the quotes disappear and the configuration file has a different meaning:
![after](https://user-images.githubusercontent.com/38586229/150293235-fd393475-7038-40c4-b570-0a0dbfc1d51e.png)

Steps to Reproduce:
Just above :)

**Comment by eleanorjboyd** [comment]
Hello! My name is Eleanor and I am the new maintainer for the Remote-SSH extension. Are you still experiencing this issue? Thanks

**Comment by eleanorjboyd** [comment]
I have replicated this bug locally and therefore am re-opening it.

**Comment by eleanorjboyd** [comment]
I have tried to replicate this locally and it does not seem to occur, please re-open if you are still seeing it on your machine. Thanks

**Comment by Belutak** [comment]
hi
 i am experiencing this same issue, as soon as i add Host field to /etc/ssh/sshd_config - ssh wont restart, it is broken.
 
 by man pages, my version of ssh supports field Host.
 OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020 on Ubuntu 20.04.5 LTS
 
 this happens on all machines on which i have tried(at least 3)
 
 i can help with any additional info needed

**Comment by Belutak** [comment]
HOST should be in ssh_config and not sshd_config per man page, i think i made a mistake, thank you
