### ISSUE TITLE
Can't open files on remote server

### ISSUE THREAD

**Issue by abhinav-nutanix** [microsoft/vscode-remote-release#6199]
Issue Type: <b>Bug</b>

If I want to open a remote file in my editor. I have to grant 0777 permissions to that file otherwise it do not allow me to edit file in my editor and save it

Extension version: 0.70.0
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.49.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 6, 6|
|Memory (System)|16.00GB (3.22GB free)|
|Process Argv|--crash-reporter-id 79ba6c12-f5bb-4785-bc39-31b50ac1e3d4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: epoch-secops-vm|
|OS|Linux x64 3.10.0-1160.49.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (1 x 2200)|
|Memory (System)|1.65GB (0.28GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30424895
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30416617
vsbas813:30426126

```

</details>

**Comment by tanhakabir** [comment]
>  I have to grant 0777 permissions to that file otherwise it do not allow me to edit file in my editor and save it

How do you know this is the case?

Also are you able to share you Remote-SSH logs with us?
