### ISSUE TITLE
Unable to use GPG Agent 

### ISSUE THREAD

**Issue by johntdyer** [microsoft/vscode-remote-release#62]
- VSCode Version: Version 1.34.0-insider (1.34.0-insider)
- Local OS Version: 10.14
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open VSCode from terminal ( effort to inherit environment ) 
2. Connect to host and get error

![image](https://user-images.githubusercontent.com/58234/57135666-34273a80-6d78-11e9-8154-006d31ff7961.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by johntdyer** [comment]
Appears the problem is actually VSCode not honoring the User override. 

At the top I have

```shell
Host *
    StrictHostKeyChecking no
    User johndye
    ControlMaster auto
    ControlPath ~/.ssh/master@%C:%p
    ControlPersist 15m
    TCPKeepAlive yes
    ServerAliveInterval 120
    IdentityAgent /Users/johndye/.gnupg/S.gpg-agent.ssh
    ServerAliveCountMax 10
    ForwardAgent yes
```

And then I have

```shell

Host ubuntu
	HostName xxxxxxxx
	User jdyer
```

and VSCode appears to always use `johndye` vs `jdyer`

![image](https://user-images.githubusercontent.com/58234/57135666-34273a80-6d78-11e9-8154-006d31ff7961.png)

If I remove the one at the global level in my ssh config it appears to honor the locally scoped User parameter

**Comment by kieferrm** [comment]
@johntdyer does `ssh ubuntu` work in a terminal for you as expected? In the end, we leave the evaluation of the ssh config files to the ssh implementation.
