### ISSUE TITLE
Failure in postCreateCommand is not obvious

### ISSUE THREAD

**Issue by Sean-Driscoll** [microsoft/vscode-remote-release#6206]
If the `postCreateCommand` has a non-zero return value the `postStartCommand` will never be called but the devcontainer will start up. The logs do not provide any any indication that the latter is ever attempted.

Steps to Reproduce:

1. Create any sample dev container
2. Add the following to the devcontainer settings
   ```
      "postCreateCommand": "(exit 1)",
      "postStartCommand": "echo 'some fancy command that must be run'"
   ```
3. Rebuild the container, review the logs and note the message is never displayed

Note: I didn't test the repro steps but seems pretty straightforward of a repro. My actual scenario is not using a sample dev container. I'm using a custom devcontainer definition that uses a Centos:7 base image.

Workarounds:
1. If you have a single command add ` || true` to the end
2. If you have multiple commands chained and one of them will always be successful then move it to be called last (e.g. use `(exit 1); (exit 0)` instead of `(exit 0); (exit 1)`)

Details:
- VSCode Version: 1.63.2
- Local OS Version: Centos7
- Remote OS Version: Centos7
- Remote Extension/Connection Type: Docker

**Comment by chrmarti** [comment]
`"postCreateCommand"` is run before `"postStartCommand"`. Could you try running your repro?

**Comment by Sean-Driscoll** [comment]
@chrmarti - you are correct. I described my issue incorrectly but have corrected it in the description above. Note, the title is accurate and succinctly describes the issue: "postStartCommand not called if postCreateCommand fails"

**Comment by chrmarti** [comment]
You're right. We could offer an option in the devcontainer.json to change this behavior. Not sure if changing the default behavior would have the expected result for all existing dev containers.

**Comment by Sean-Driscoll** [comment]
@chrmarti  - adding an option is fine, but I strongly suggest that the default behavior change. It's more likely that someone is unintentionally running into this issue then actually using it. If you keep the current default it's just hiding problems from the user.

 I can absolutely say it was a problem for me, and one not easily identified because there is no message logged to indicate what happened (or in this case did not happen).

IMO, one of the following should be a logical **default** behavior:
1. If a user command fails, the dev container startup fails and logs a message accordingly
2. If a user command fails, log the failure and continue to process additional user commands 

Lastly, the title change you made is perpetuating the same behavior as this issue - it's hiding the problem. The problem isn't that no option exists to continue running user commands after one fails... _it's that the devcontainer startup process hides the fact that some user commands are never even being attempted_

**Comment by chrmarti** [comment]
Logging can be improved there and actually seems to be broken at the moment. I'll investigate.

On 1: We run these commands in the background while the VS Code window opens and starts accepting input. So it is too late to fail startup.
On 2: That might hide an error more.

**Comment by chrmarti** [comment]
I'm adding an error message including the exit code to the output to improve this:
<img width="706" alt="image" src="https://user-images.githubusercontent.com/9205389/151513786-ee2ce2dd-5973-4e6b-9b72-9c65b8ca89df.png">

**Comment by Sean-Driscoll** [comment]
@chrmarti - this is much more useful thanks! 

Half of the issue described still exists though. I'm curious what it would take to print a message indicating the `postStartCommand` will not be attempted? Maybe that's just a documentation update?

**Comment by connor4312** [comment]
cc @chrmarti for docs update

**Comment by chrmarti** [comment]
How about this:
<img width="783" alt="image" src="https://user-images.githubusercontent.com/9205389/151933922-3ce7b032-0a9b-4c87-8817-6cef99ab69d6.png">

**Comment by Sean-Driscoll** [comment]
As a user it is still lacking to me, explanation below. If there isn't going to be an explicit message that `postStartCommand` is being skipped (and any other 'user-provided command' that I'm unaware of) I'd rather see online documentation updated appropriately.

I hadn't heard them referred to as 'user commands' until you mentioned it, and I'm still not certain all if what that entails. Until this issue I got the distinct impression that they were independent actions. 

The context of that block of messages is the `postCreateCommand`, as indicated by the initial message "Running the ...". There is no indication that `postStartCommand` is a linked action, so when I see a message about skipping further user-provided commands I'm thinking of commands in that specific context.
