### ISSUE TITLE
Node not found - Basic python3 module

### ISSUE THREAD

**Issue by jochman** [microsoft/vscode-remote-release#6211]
Tried to develop in the basic docker of python3. Could not find node installed inside.

- VSCode Version: 1.63.2
- Local OS Version: MacOS Monterey 12.1 (M1 Pro chip)
- Remote OS Version: mcr.microsoft.com/vscode/devcontainers/python:0-3.10-bullseye
- Remote Extension/Connection Type: Docker
- Logs:
[remote.log](https://github.com/microsoft/vscode-remote-release/files/7920146/remote.log)

Steps to Reproduce:

1. Create a devcontainer using the default py3 image (`Remote-Containers: Add Development Container Configuration Files...`
2. Try to reopen the folder in the container.
Fail.

I can see that `node` isn't installed from the logs (`[23907 ms] Container server: /bin/sh: 29: /home/vscode/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/node: not found`)
I guess the vscode server is running on it.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Could you use `docker exec` to get a shell in the container (assuming VS Code doesn't startup, the Docker extension can do this when you use Attach Shell from a container's context menu) and post the output of `ls -l /home/vscode/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3` here?

**Comment by jochman** [comment]
```sh
# ls -l /home/vscode/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3
lrwxrwxrwx 1 vscode vscode 78 Jan 25 07:50 /home/vscode/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3 -> /vscode/vscode-server/bin/linux-arm64/899d46d82c4c95423fb7e10e68eba52050e30ba3
```

**Comment by chrmarti** [comment]
Could you rerun with a `/` appended: `ls -l /home/vscode/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/`

**Comment by jochman** [comment]
> Could you rerun with a `/` appended: `ls -l /home/vscode/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/`

```sh
# ls -l /home/vscode/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/
ls: cannot access '/home/vscode/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/': No such file or directory
```

**Comment by chrmarti** [comment]
It seems the symlink is dangling. Does using `F1` > `Remote-Containers: Rebuild and Reopen in Container` help? (This will remove the existing container.)

**Comment by jochman** [comment]
I have tried rebuilding the image several times.

**Comment by chrmarti** [comment]
Try disabling the cache volume in the user settings and rebuild the container:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/9205389/151243792-e77d8efd-6968-4d40-8734-df839a890ff3.png">

**Comment by jochman** [comment]
Did it. Try to do the same with the node basic image (mcr.microsoft.com/vscode/devcontainers/javascript-node:0-16).
I'm getting the same error for all of the builds.

**Comment by diegodgs** [comment]
I am suffer this error too.

**Comment by jochman** [comment]
Tried the same build on my windows pc - It worked.
Something off with Mac/Ubuntu as it seems.

**Comment by chrmarti** [comment]
Could be a corrupt download in `$TMPDIR/vsch/serverCache`. Try deleting that folder and keep the `Cache Volume` setting turned off, then rebuild the dev container.

@diegodgs What is your hardware architecture for Ubuntu and what is it for the dev container? Which version of VS Code are you using?

**Comment by jochman** [comment]
It worked after I removed all cache and disabled the cache volumes. Is there a way to solve it without disabling all of those?

**Comment by diegodgs** [comment]
VSCode Version: 1.63.2
    Local OS Version: Ubuntu 20.04, Linux x64 5.13.0-27-generic
    Remote OS Version: mcr.microsoft.com/vscode/devcontainers/python:3.7
    Remote Extension/Connection Type: Docker
    
    Electron: 13.5.2
    Chromium: 91.0.4472.164
    Node.js: 14.16.0
    V8: 9.1.269.39-electron.0

**Comment by chrmarti** [comment]
@jochman Does deleting `$TMPDIR/vsch/serverCache` make it work again? I wonder if the download was corrupted or later the file was somehow changed.

**Comment by jochman** [comment]
> @jochman Does deleting `$TMPDIR/vsch/serverCache` make it work again? I wonder if the download was corrupted or later the file was somehow changed.

Tried it several times. Sometimes it works, sometimes it is not. I guess something is changing the file later.

**Comment by diegodgs** [comment]
I update vscode to version 1.64 and the error persist.

**Comment by chrmarti** [comment]
Does deleting `$TMP/vsch/serverCache` and disabling the cache volume in the user settings make it work? (Rebuild the container after this.)

<img width="804" alt="image" src="https://user-images.githubusercontent.com/9205389/151243792-e77d8efd-6968-4d40-8734-df839a890ff3.png">
