### ISSUE TITLE
Test: Remote-Containers pre-release adoption

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#6212]
Refs: https://github.com/microsoft/vscode-remote-release/issues/6169

- [x] anyOS @greazer
- [x] anyOS @dbaeumer

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%236212%0A%0A&assignees=chrmarti)

---

- Start Insiders with an empty user data and extensions dir: `code-insiders --user-data-dir tmp-folder/data --extensions-dir tmp-folder/exts`
- Verify that the Remote-Containers extension is shown with 'Install Pre-Release' button in the Extensions viewlet.
- Exit and install a regular release first (make sure the extension wasn't installed with this user data dir before): `code-insiders --user-data-dir tmp-folder/data --extensions-dir tmp-folder/exts --install-extension ms-vscode-remote.remote-containers@0.213.0`.
- Start Insiders again (same data and exts folders) and verify the extension auto-updates to the latest pre-release (migration path for existing Insiders users).

**Comment by greazer** [comment]
Tested on Windows

**Comment by dbaeumer** [comment]
Also tested on Windows.
