### ISSUE TITLE
Test: devcontainer-features.json schema

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#6214]
Refs: https://github.com/microsoft/vscode-remote-release/issues/5980

- [x] anyOS @lramos15
- [x] anyOS @dbaeumer

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%236214%0A%0A&assignees=chrmarti)

---

- Install the Remote-Containers extension.
- Check that you get completion proposals and hovers when editing https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/container-features/src/devcontainer-features.json

**Comment by dbaeumer** [comment]
Tested under Windows.
