### ISSUE TITLE
Can't open folder in container in remote SSH with RemoteCommand

### ISSUE THREAD

**Issue by aniketbhatnagar** [microsoft/vscode-remote-release#6215]
I am using preview version of Remote - SSH plugin with `"remote.SSH.enableRemoteCommand": true`. SSH is confirmed with `RemoteCommand sudo su <a user with docker access>`. Once I connect to SSH host and then use the `Open folder in container` option, nothing happens and output console emits an error (mentioned as logs below)  

- VSCode Version: 1.63.2
- Local OS Version: Mac OS
- Remote OS Version: 18.04.1-Ubuntu
- Remote Extension/Connection Type: SSH + Docker
- Logs: 
```
[2022-01-24 14:22:17.397] [exthost] [error] Shell server terminated (code: 255, signal: null)

Cannot execute command-line and remote command.
 remote-containers.openFolder {"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"}
```

Steps to Reproduce:

1. Switch to preview version of Remote - SSH plugin and enable `"remote.SSH.enableRemoteCommand": true`
2. Connect to SSH host with `RemoteCommand sudo su <a user with docker access>`
3. Try opening a folder in container

https://user-images.githubusercontent.com/618933/150802329-884aab29-c2a4-424e-9eba-0b0c23da9bfa.mp4

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by tanhakabir** [comment]
I'd suggest using the Remote Containers extension instead to open your folder in a Container and in SSH: https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_63.md#open-folder-in-container-on-ssh-server

**Comment by aniketbhatnagar** [comment]
Hi @tanhakabir ... thanks for looking into this. Unfortunately, same thing happens when I follow the instructions - `First open the folder using Remote-SSH to connect to the SSH server and then click the green remote indicator to use the Reopen in Container command`. Is there a way to get more logs on what actually fails? `Cannot execute command-line and remote command.` doesn't reveal much.

**Comment by chrmarti** [comment]
"Cannot execute command-line and remote command." indicates that we can't pass a command to ssh when it also has a RemoteCommand. Will need to investigate.

**Comment by tanhakabir** [comment]
@aniketbhatnagar could you remove your remote command in your config?

@chrmarti are you adding `bash` or `powershell` at the end of your connection command? That could be causing this error:
https://github.com/microsoft/vscode-remote-ssh/commit/21d0cc043142cf48bde68433baf4300eb79f81cf

and then I completely removed the specified shell:
https://github.com/microsoft/vscode-remote-ssh/commit/533b67be58e677112024bffd4549f761d64df7b7

**Comment by aniketbhatnagar** [comment]
Hi @tanhakabir , if I remove the remote command (`sudo su <a user with docker access>`), it indeed makes more progress but unfortunately in the remote host that I am using, I need to su to another user to run any docker command. So, it eventually fails with permission denied on docker. I can try giving my SSH user access to docker but it would be great it remote command was supported while opening a folder in container over SSH

**Comment by manycoding** [comment]
I might hit a similar issue:

```Cannot execute command-line and remote command.
 remote-containers.attachToRunningContainer {"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"}```

All I do is Remote-Containers: Attach to Running Container...

**Comment by manycoding** [comment]
Update: I am still having this issue. I have no problems attaching through terminal but can't attach VSCode:
* remote explorer - containers is empty, even though Docker is not
* Right click > attach Visual Studio Code or f1 > attach to running containers produces the same error above.

```[exthost] [error] Shell server terminated (code: 255, signal: null)

Cannot execute command-line and remote command.
 remote-containers.attachToRunningContainer {"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"}```

**Comment by ericsampson** [comment]
> "Cannot execute command-line and remote command." indicates that we can't pass a command to ssh when it also has a RemoteCommand. 

@chrmarti I'm definitely running into this. Any thoughts on tweaks (format etc) of the user-specified RemoteCommand that would make this not fail? Or is this something that's going to need a fix on the extension side.

as a side issue, this failure was not easy to debug as a user, so if there's any way to improve that in the interim that could help as well. I tried to view all the VSCode debug logs that I could find, but wasn't able to uncover the underlying issue.

Cheers!

**Comment by ericsampson** [comment]
Also can we perhaps rename this Issue so that it's more accurate like "support ssh RemoteCommand" @aniketbhatnagar

**Comment by chrmarti** [comment]
Dev Containers is now using Remote-SSH's ssh connection.
