### ISSUE TITLE
Need old version for Remote-Container

### ISSUE THREAD

**Issue by ronen77** [microsoft/vscode-remote-release#6217]
Q: where can I find an Old Extension Remote-container to be compatible with vscode 1.57 (from July 2021)?

**Comment by chrmarti** [comment]
Not obvious:
- The remote release notes mention 0.183.x being the corresponding Remote-Containers version: https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_57.md
- The Extensions viewlet in VS Code offers 'Install Other Version...' in the context menu of the installed Remote-Containers extension. That shows 0.183.0 was the only 0.183.x release.
- If you need a direct download you can use https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-containers/0.183.0/vspackage.

@isidorn The version history on the marketplace is very short. Is there an issue tracking to make the full history available?

**Comment by isidorn** [comment]
@chrmarti there is no issue tracking this. Can you please file a new feature request here https://github.com/microsoft/vsmarketplace

**Comment by chrmarti** [comment]
Opened https://github.com/microsoft/vsmarketplace/issues/317. Thanks.

**Comment by ronen77** [comment]
Hi,

You helped me before, hope you can help this time as well.\

I am still using vscode 1,57,1 and needs:
cpp dbg extension
ms-vscode-remote.vscode-remote-extensionpack

obviously, these packages needs to be compatible with vscode 1.57.1

Regards,
Ronen Levy

‫בתאריך יום ג׳, 25 בינו׳ 2022 ב-9:39 מאת ‪Christof Marti‬‏ <‪
***@***.***‬‏>:‬

**Comment by isidorn** [comment]
Please update to latest VS Code.

**Comment by ronen77** [comment]
I prefer not to upgrade the vscode. Please send link to suitable extension
cpp dbg. Appreciate.
