### ISSUE TITLE
I can not open another server when it had open a server.

### ISSUE THREAD

**Issue by JiexingQi** [microsoft/vscode-remote-release#6219]
Issue Type: <b>Bug</b>

For mac vscode, I can not open another different server when I had open a server use remote ssh. Although it can open the window for another server, but the terminal is still the first server you had opend. This is not occured in windows vscode.

Extension version: 0.70.0
VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No
Remote OS version: Linux x64 4.15.0-55-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (17.57GB free)|
|Process Argv|--crash-reporter-id 0f3d1bba-e1cf-4f41-aae0-cc132d15ea36|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: server.acemap.cn:26001|
|OS|Linux x64 4.15.0-55-generic|
|CPUs|AMD EPYC 7352 24-Core Processor (96 x 1797)|
|Memory (System)|251.82GB (88.40GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30424895
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710:30416614
vscop841:30424583
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by tanhakabir** [comment]
Do you mean you were connected, you closed the connection and the window did not reload so you aren't able to connect to a different server?

Do you have any logs from the failed attempt?

**Comment by JiexingQi** [comment]
Hi, @tanhakabir, thank you for your reply. I'm sorry for not describing this problem clearly.

The details for this problem is as follows:

First, I connect a remote server A and it runs normally.
![image](https://user-images.githubusercontent.com/43906450/150907188-8945562d-7e57-4203-bda1-777ecad90350.png)


Then, I didn't close the connection with A and start a new window for connecting server B. 
![image](https://user-images.githubusercontent.com/43906450/150907286-04a9c775-ebff-4f6c-a56d-104bf0e48e76.png)


It displays that I connect to server B in the left button status bar. 

![image](https://user-images.githubusercontent.com/43906450/150907392-24027c7a-91ae-4ee9-b1b1-1738684f5406.png)


However, it still is the terminal for server A when I start the terminal on connection for server B.

All of these steps did not have error.


Thank you for your reply, @tanhakabir , thanks a lot.

**Comment by tanhakabir** [comment]
Hm when you look at the Remote SSH logs and look for "Authenticated to .." do you see the appropriate IP addresses or do you see the same IP address on both connections?

**Comment by JiexingQi** [comment]
Thank you @tanhakabir , I found this problem is caused by the setting
```
"remote.SSH.useLocalServer": true
```
and when I set this to 
```
"remote.SSH.useLocalServer": false
```
thins that work well.

Thank you again @tanhakabir
