### ISSUE TITLE
Test Remote-SSH: Pre-release version

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-remote-release#6222]
Refs: https://github.com/microsoft/vscode-remote-release/issues/6010

- [x] anyOS @chrmarti 
- [x] anyOS @kieferrm 
- [ ] anyOS @digitarald (Optional) 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%236222%0A%0A&assignees=tanhakabir)

---

We want to make sure 

Prerequisites: 
1. Use VS Code Insiders.
2. Get the Remote SSH extension.
3. Switch to Pre-release version.
4. Check that you have the setting `remote.SSH.enableRemoteCommand` available to you.
5. Switch to stable version of the extension. Check that the setting is no longer available.

**Comment by digitarald** [comment]
Tested on macOS.
