### ISSUE TITLE
VSCode SSH Remote did not download correct archeticture when connecting to a Raspeberry Pi host

### ISSUE THREAD

**Issue by shanoaice** [microsoft/vscode-remote-release#6223]
When I tried to connect to my Raspberry Pi using the SSH host, the dev server failed to start. In the logs it says that binary "node" not found in the `bin` directory, but I confirm it is there. It seems like that VSCode downloaded a x86-64 build of the node binary instead of an ARM64/AArch64 one.

**Comment by bamurtaugh** [comment]
Thanks for filing. Seems like this may be a dupe of https://github.com/microsoft/vscode-remote-release/issues/3248?

**Comment by shanoaice** [comment]
Nope, this is not a dupe. After some examination, it was probably due to NixOS (using its unique layout). The node binary links to` /lib/ld-linux-aarch64.so.1`, but that thing did not exist on NixOS. Closing this right now as the solution is described here: [NixOS Wiki](https://nixos.wiki/wiki/Visual_Studio_Code#Remote_SSH)/
