### ISSUE TITLE
Remote-SSH: Kill server ask to login first

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#6228]
Testing #6220

Windows
Remote-WSL v0.71.2021121615 (pre-release)
Version: 1.64.0-insider (user setup)
Commit: f93c69659de1a1466bd15e0f1c9f790e73be9208
Date: 2022-01-25T08:42:41.055Z
OS: Windows_NT x64 10.0.19044

- open a remote SSH window and open a folder
- run the `Kill VS Code Server on Host` command
- I'm prompted to decide to which host to connect. Then I'm prompted to enter the password
- The window reopens. A notification tells me that the server has been killed.

**Comment by aeschli** [comment]
![Recording 2022-01-25 at 17 03 34](https://user-images.githubusercontent.com/6461412/151014363-a4e4fead-48c1-41b6-9f34-b4a84e87c331.gif)

**Comment by aeschli** [comment]
Also see #6227

**Comment by sbatten** [comment]
I'm seeing the same and verified that useLocalServer is true.

**Comment by tanhakabir** [comment]
Sorry just noticed the @aeschli used `Kill VS Code Server on Host`. This expected. I expect `Kill Current VS Code Server` not not prompt for password

**Comment by aeschli** [comment]
The Remote-SSH version is now v0.71.2022012519

I didn't see `Kill Current VS Code Server` before.

In deed `Kill Current VS Code Server` is doing it correctly (no prompt)
