### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by shawnl** [microsoft/vscode-remote-release#623]
- VSCode Version: 1.35
- Local OS Version: Ubuntu DIsco
- Remote OS Version: Debian Sid, powerpc64el
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Where is the code?
2. Where is the friggen code?

Does this issue occur when you try this locally?: Yes/No
I can't find the code!
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No
Yes, because I can't look at the code!

**Comment by VAggrippino** [comment]
I'd also like to see the code of this extension pack and all of the extensions it depends on, but this is Microsoft... There's no code because they don't understand how Open Source Software works.

**Comment by Chuxel** [comment]
@shawnl The Remote Development extensions are not open source. See [the FAQ](https://code.visualstudio.com/docs/remote/faq#_why-arent-the-remote-development-extensions-or-their-components-open-source) for details.
