### ISSUE TITLE
DNS outage for CDN leads to failed container build

### ISSUE THREAD

**Issue by maresb** [microsoft/vscode-remote-release#6236]
- VSCode Version: 1.63.2
- Local OS Version: Ubuntu 20.04.1
- Reproduces in: Remote - Containers

Steps to Reproduce:

Build a new dev container.

The following error occured during the build process:

```
Installing VS Code Server for commit 899d46d82c4c95423fb7e10e68eba52050e30ba3
Start: Downloading VS Code Server
8999d46d82c4c95423fb7e10e68eba52050e30ba3 linux-x64 stable
Error: getaddrinfo ENOTFOUND az764295.vo.msecnd.net at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js: 67:26)
```

The internet was accessible from my container. However, this particular Azure CDN seems to have been down:

![image](https://user-images.githubusercontent.com/15216687/150982554-1e90cd05-28b1-45f9-be24-69c4c0b8f942.png)

The outage lasted at least an hour, and it came back online about 15 minutes ago.

I would expect that a backup CDN should be configured to avoid a fatal error during such outages. Or at least in the event of such an outage, it would be nice to have a readable error message to the effect of: 

> Although the Internet is accessible from the container, the Microsoft CDN servers az764295.vo.msecnd.net and xyz.vo.msecnd.net could not be reached. Please try again later.

**Comment by Chuxel** [comment]
This is Azure CDN, so it is redundant, but even CDNs have regional hiccups.  I don't know the specifics of this one. @chrmarti  @joaomoreno ?

**Comment by joaomoreno** [comment]
> Error: getaddrinfo ENOTFOUND az764295.vo.msecnd.net at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js: 67:26)

This is not a CDN outage. This was a DNS issue. Given that we received no other issues about this specific CDN being down, and that we *heavily* use this CDN for distributing VS Code and its updates... I'd argue this was a DNS issue on the user's machine/network.

**Comment by maresb** [comment]
Thanks @joaomoreno for clarifying that this was a DNS issue, I had not realized that.

I'd argue that it wasn't just my network: I experienced the DNS issue on three seemingly independent networks. First on AWS Frankfurt where I run my dev container. Second on my home network in Geneva. Third on Down for Everyone or Just Me.

**Comment by joaomoreno** [comment]
> Regarding the lack of other issues, I think there's a very strong bystander effect... people believe that if it hasn't already been reported, then it must be on their local network. But somebody must be the first to report it.

I'd be very surprised. Unfortunately that would be very much against the norm when it comes to this specific CDN. Every time something happens with it we do hear about it. A **lot**.

**Comment by maresb** [comment]
Ok, you'd know much better than I. :smile:

I'm not sure why "Down for Everyone" believes it's down, but that takes me down to two independent networks, neither of which can be externally verified, which indeed casts further doubt that this was a true outage.

While it's still a big mystery to me, and I've never had network problems before, it doesn't seem like there's much you can do at this point... Would you like me to close this as not reproducible?

Thanks so much for your time.

**Comment by joaomoreno** [comment]
Yeah let's close it for now. I'll definitely keep an eye open for this.
