### ISSUE TITLE
Killing current VS Code server doesn't close window

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-remote-release#6238]
Testing #6220

On Linux, after running the kill current VS code server command, I am prompted for my password, but after I press enter, the window still stays open. I do get a notification, though, saying the server was killed.
I also have the `useLocalServer` setting explicitly set to `true`.

**Comment by tanhakabir** [comment]
Fixed: https://github.com/microsoft/vscode-remote-ssh/commit/f6d2a0b50ed12f07ec8af01fda37e13c8680e52b

Will be out in todays pre-release
