### ISSUE TITLE
remote vscode server cann't start.

### ISSUE THREAD

**Issue by wonderkun** [microsoft/vscode-remote-release#624]
- VSCode Version:Version 1.35.0
- Local OS Version:macOS 10.14.4
- Remote OS Version: centos7.5
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. connect to remote server centos 7.5 use remote-ssh  
2. remote vscode-server start failed 

```
> Server did not start successfully. Full server log:
> cat: /root/.vscode-server/.553cfb2c2205db5f15f3ee8395bbd5cf066d357d.log: No such file or directory
> cat: /root/.vscode-server/.553cfb2c2205db5f15f3ee8395bbd5cf066d357d.log: No such file or directory
"install" terminal command done
Received install output: cat: /root/.vscode-server/.553cfb2c2205db5f15f3ee8395bbd5cf066d357d.log: No such file or directory
Failed to parse remote port from server output: cat: /root/.vscode-server/.553cfb2c2205db5f15f3ee8395bbd5cf066d357d.log: No such file or directory

```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Is that the full log? Any other errors?

**Comment by wonderkun** [comment]
Yes, that is the full log . I don't know what happended.

**Comment by roblourens** [comment]
Could you try it with the nightly version of the extension and vscode insiders?

**Comment by wonderkun** [comment]
I'm sorry for the delay in replying to you. Vscode insiders is without the problem. It  works .
I will close this  issue.
