### ISSUE TITLE
Prerelease version not auto installed

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-remote-release#6242]
Testing #6212

- follow the steps outlined in #6212 
- after installing 0.213.0 of the extension opening VS Code will install 0.214.0.

No automatic installation of pre-release will happen. You presents:

<img width="918" alt="capture" src="https://user-images.githubusercontent.com/1931590/151144680-23b045dd-ec6e-49f5-b507-92a5d7addf81.png">

**Comment by chrmarti** [comment]
You're right, I think the auto-update and the update to pre-release by the extension don't go well together. It works in two upgrades when I install 0.209.6 (which does not update to pre-release) first. This then upgrades to 0.214.0 which (after a reload) upgrades to 0.215.0 (or later) pre-release. So this might be a problem with the instructions, could you retry starting with 0.209.6?

**Comment by dbaeumer** [comment]
These steps worked for me.

**Comment by chrmarti** [comment]
Over 35% of Insiders users stay behind on the last stable release. Not sure why this is, but I will release a new pre-release 0.218.0 and then a new release 0.217.0 version that once again updates Insiders to pre-release versions. /fyi @sandy081
