### ISSUE TITLE
IPv6 DNS flooding

### ISSUE THREAD

**Issue by spyesx** [microsoft/vscode-remote-release#6246]
Issue Type: <b>Bug</b>

When opening an SSH target, vscode sends thousands and thousands of DNS queries AAAA (IPv6) to our local DNS server. The thing is I'm opening a connexion with a local server that does not have an IPv6 address.

Eventually, after flooding the network for more than 5min, it stops. 

Extension version: 0.70.0
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:38:17.605Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No
Remote OS version: Linux arm64 5.13.0-1015-raspi

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|--crash-reporter-id 97c5a010-219d-4b18-80a4-8cc1cdbc6e60|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: <hostname>|
|OS|Linux arm64 5.13.0-1015-raspi|
|CPUs|unknown (4 x 1000)|
|Memory (System)|3.70GB (1.98GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30428978
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710cf:30416617
vsbas813:30426126

```

</details>

**Comment by spyesx** [comment]
The exact number is 548,512 DNS queries in the last 10min.

**Comment by tanhakabir** [comment]
When you ssh in your shell do you see fewer queries?

**Comment by spyesx** [comment]
Hi, yes everything's clear. Only one DNS query is logged from a regular SSH connexion. Same thing with `ssh`, `dig` or any `http` request. Is there debug log I can share to help?

**Comment by tanhakabir** [comment]
Hm strange. You can send me your Remote SSH logs to see if there's anything there. Instructions to find those: https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues

Generally the extension just uses your SSH binary in your machine to resole the host and connect to it so it'd be odd that the extension behaves any differently since it uses the same SSH executable.
