### ISSUE TITLE
Remote-SSH hangs on "Confirming that ... is reachable"

### ISSUE THREAD

**Issue by manolosolalinde** [microsoft/vscode-remote-release#625]
Hi. I cant get remote ssh to work. It hangs on "Confirming that ... is reachable...".
I tried reinstalling. Remote development is the only installed extension. Please help.

Details:
- VSCode Version: 1.36.0-insider
- Local OS Version: Windows 10
- Remote OS Version: Raspbian GNU/Linux 9 (stretch)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
1. F1 -> Remote-SSH: Connect to Host -> user@hostip

**Comment by manolosolalinde** [comment]
Just realized that a new terminal "uname" is silently enabled asking for password. I just didnt get a prompt or windows focus or anything which is not very user friendly. 

Solved going to view -> terminal -> uname

**Comment by buggymcbugfix** [comment]
I just had the same issue.

**Comment by Akryllax** [comment]
> 
> 
> Just realized that a new terminal "uname" is silently enabled asking for password. I just didnt get a prompt or windows focus or anything which is not very user friendly.
> 
> Solved going to view -> terminal -> uname

We have the same problem, but no password promt is expected for our connetion (we have a tested id_rsa keypair with HostChecking disabled). It just hangs there forever.

All logs say are [Remote - SSH]:
Using SSH config file "C:\Users\Username\.ssh\config"
Confirming that docker is a valid reachable host
`Running type "C:\Users\Username\AppData\Local\Temp\vscode-linux-multi-line-command-docker.sh" | ssh -F C:\Users\Username\.ssh\config "docker" bash to confirm the host platform`

And it just hangs there for initinity.

**Comment by Akryllax** [comment]
Okay, it seems that it all is because of a "File Not Found" exception in the boostrap-v5.js scripts, will post logs in an hour or so. Gonna try tracing the code to find which path it is trying to access.

**Comment by Akryllax** [comment]
Okay, after some fighting with the console tools, we tracked down the problem to the module WinPTY that comes with the Remote Development - SSH extension, that gives a "File Not Found Exception" after trying to start the "uname" process.

Attaching logs and sourcefile responsible:
[-1560250701926.log](https://github.com/microsoft/vscode-remote-release/files/3276166/-1560250701926.log)



[Desktop.zip](https://github.com/microsoft/vscode-remote-release/files/3276170/Desktop.zip)

**Comment by Akryllax** [comment]
**FIX FOUND**:

For some unexplained reason, my coleague's Windows 7 install did **not** have `cmd.exe` set in the SYSTEM PATH. He found that after adding `cmd.exe` to it, the extension started working as expected.

Note: This error also leaves an orphaned vscode installer process in the Docker container, so you have to execute the following commands to destroy it and cleaning BEFORE trying to open again VSRemoteDev:

- `ps aux | grep vscode` to find the process ID of the orphan (a number in the second columnd), for example:
`user    21702  0.2  1.0 1219100 61628 ?` Get the 21702 value.
- `kill -9 21702` to actually kill the process.
- `rm -rf ~/.vscode-server` to clear half installed files.

**OR**
- If you home folder is **not** mounted, you can restart the container, wiping all current changes.

If you don't delete this folder, VSCode might enter in a refresh loop trying to overwrite already existing files.

**Comment by sivum** [comment]
Same here ( was prompting for password away from view). Saw @buggymcbugfix answer Thanks!

**Comment by darkguy2008** [comment]
Same here, why don't we have a dialog like when it asks for the host or the fingerprint to continue, to ask for the password too? this seems counter-intuitive, it's so bad UX that an issue has been opened, hah.

**Comment by roblourens** [comment]
You can set `remote.SSH.showLoginTerminal` to reveal the terminal with prompt, but we are working on improving this.

@Akryllax great analysis, thanks!

> For some unexplained reason, my coleague's Windows 7 install did not have cmd.exe set in the SYSTEM PATH

That's pretty strange. To be honest, I don't think it's worth it to try to detect that case. If your PATH is totally broken, I would think other windows things would be broken too.
