### ISSUE TITLE
Remote SSH : When trying to rename or create a file/folder in the sidebar random deselection occurs

### ISSUE THREAD

**Issue by markusdd** [microsoft/vscode-remote-release#6251]
VSCode Version: 1.63.2
SSH Remote extension latest preview (v0.71.2021121615 Pre-Release)
Local OS Version: Fedora 35
Remote OS Version: CentOS 7.9
Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Try to rename a file or folder or create a new one. While typing, eventually, a random deselect will happen. If you are not quick enough during create, it might deselect without any chars entered yet, so the creation of the file or folder is aborted.

I have also seen once a popup claiming the remote file does not exist. Yes of course...I'm just in the process of creating it :D

This is a very annoying problem. For me it is so bad I have to do any file creation or copy actions through the Terminal.

**Comment by tanhakabir** [comment]
Do you have a gif of this? I'm connected to a remote on my side and when I true to repro I don't see this issue 😕

**Comment by markusdd** [comment]
sure:
![New_Folder_File](https://user-images.githubusercontent.com/25175069/151940499-238cb555-92f1-4310-99f0-430d50b206d9.gif)
