### ISSUE TITLE
Can't see files changes

### ISSUE THREAD

**Issue by puku** [microsoft/vscode-remote-release#6255]
- VSCode Version: Version: 1.63.2 (Universal)
- Local OS Version: macOS Monterey
- Remote OS Version: node:16-alpine
- Remote Extension/Connection Type: Docker
- Logs:

Can't see files changes.
Files legacy watcher set to off. node_modules folder is excluded

**Comment by chrmarti** [comment]
Running `git status` in the integrated terminal shows changes, but the SCM viewlet in VS Code does not?

**Comment by puku** [comment]
Hey @chrmarti, I don't have this issue anymore. As it appeared the problem was related to git not being installed in the container. Sorry for bothering 🙂

**Comment by chrmarti** [comment]
No problem, thanks for letting me know.
