### ISSUE TITLE
【version】When will the official version be provided?

### ISSUE THREAD

**Issue by wsq-7** [microsoft/vscode-remote-release#6256]
1、When I use the extention, I find that the preview version is available. When will the official version be available?

2、Is there a plan to open source code?

**Comment by wsq-7** [comment]
for remote-ssh

**Comment by tanhakabir** [comment]
1. We release every stable release of the extension along with VS Code. The next stable release will be this upcoming week. 
2. No we don't have any plans at the moment to open source the Remote SSH extension

**Comment by tanhakabir** [comment]
You should be able to switch between the stable and the preview version of the extension. Are you not seeing that you're able to?

**Comment by wsq-7** [comment]
Thanks，I can switch。
And I have another question, what does this “preview” mean?
![image](https://user-images.githubusercontent.com/70617427/152741148-76efb510-63e2-4f02-ba3d-86f93a53fd58.png)

**Comment by tanhakabir** [comment]
We are tracking the Preview label [here](https://github.com/microsoft/vscode-remote-release/issues/5520). You can also learn more about it in our [docs](https://code.visualstudio.com/docs/remote/faq#_why-arent-the-remote-development-extensions-or-their-components-open-source).
