### ISSUE TITLE
Opening container configuration file for remote attached container does nothing

### ISSUE THREAD

**Issue by TimUnderhay** [microsoft/vscode-remote-release#6258]
When running Remote -> Open Container Configuration File on a container attached to over a Remote ssh session, nothing happens, and no errors are logged.  Consequently, I cannot work out where to define any devcontainer-y settings for attached containers.

- VSCode Version: 1.63.2
- Local OS Version: MacOS 12.2
- Remote OS Version: Ubuntu 20.04.1 LTS
- Remote Extension/Connection Type: Remote Containers over SSH
- Logs:  I can find no messages associated with this but attaching 
[Remote-Containers 0.209.6 in VS.txt](https://github.com/microsoft/vscode-remote-release/files/7969980/Remote-Containers.0.209.6.in.VS.txt)

Steps to Reproduce:

1.  Remote -> Connect to Host (pick a host)
2. Remote -> Attach to Container
3. File -> Open any folder in the attached container, 
4. Remote -> Open Container Configuration File.
5. Observe that nothing happens.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
I still repro this. I have `v0.223.0`

**Comment by chrmarti** [comment]
Similarly: Doesn't work on Windows with a remote devcontainer.json because the code converts to a `file:` URI.

**Comment by chrmarti** [comment]
This seems to work now.
