### ISSUE TITLE
Can't open files with VSC in tmux

### ISSUE THREAD

**Issue by wuyihao14** [microsoft/vscode-remote-release#626]
- VSCode Version: c089daa858f34631f5f827ff8a0313bf1e2ded6d
- Local OS Version: macOS 10.14 (18A391)
- Remote OS Version: CentOS 7 ( kernel 4.9.147 )
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.  Use tmux as shell program:  `terminal.integrated.shell.linux": "tmux",`
2. Run in the integrated terminal:  `code-insiders --verbose SOMEFILE`
3. Error is: `[919:0610/144516.630460:WARNING:browser_main_loop.cc(343)] Gtk: cannot open display:`.

Does this issue occur when you try this locally?:No
Does this issue occur when you try this locally and all extensions are disabled?:No

**Comment by egamma** [comment]
@wuyihao14 

>Run in the integrated terminal: code-insiders --verbose SOMEFILE

Can you confirm that you run this command in an SSH Remote context?
