### ISSUE TITLE
Colima: Attach to running container in remote host

### ISSUE THREAD

**Issue by catapulta** [microsoft/vscode-remote-release#6261]
Docker Desktop [has become non-free](https://www.docker.com/blog/updating-product-subscriptions/). A particularly easy-to-setup alternative is [Colima](https://github.com/abiosoft/colima). However, Remote Containers on a remote host does not seem to work.

- VSCode Version: Insiders 1.64
- Local OS Version: macOS Big Sur 11.6
- Remote OS Version: Ubuntu
- Remote Extension/Connection Type: Docker
- Logs:

> [2022-01-27T18:06:53.323Z] Remote-Containers 0.214.0 in VS Code 1.64.0-insider (0c6d1e9f7ef648cfa50733abb62388bc0791856a).
> [2022-01-27T18:06:53.323Z] Start: Run: docker version --format {{.Server.APIVersion}}
> [2022-01-27T18:06:53.364Z] Stop (41 ms): Run: docker version --format {{.Server.APIVersion}}
> [2022-01-27T18:06:53.364Z] 1.41
> [2022-01-27T18:06:53.367Z] Start: Run: docker inspect --type container d39bacfd96048fef9cf90cd99da3547e16ca351742a479ac3e251aeffa0c8866
> [2022-01-27T18:06:53.393Z] Stop (26 ms): Run: docker inspect --type container d39bacfd96048fef9cf90cd99da3547e16ca351742a479ac3e251aeffa0c8866

Steps to Reproduce:

Prereq: I assume the machine is [properly configured](https://code.visualstudio.com/docs/remote/attach-container) for Remote Containers.

1. In remote machine (Ubuntu) start the container, `docker run -it debian:buster-slim`
2. In local (MacOS) Docker extension, container appears with green "play" icon. Optionally: Confirm left click and attach terminal works (commands in terminal too).
3. Right click on container in Docker extension, Attach Visual Studio Code:
> Error running command remote-containers.attachToRunningContainerFromViewlet: Command failed: docker inspect --type container 20eb0d065a385db36d18e6690223a6382fca48d73313fddd43b8ea6cbe1b720a. This is likely caused by the extension that contributes remote-containers.attachToRunningContainerFromViewlet.

Optionally: Hit F1: type `Remote-Containers: Attach to Running Containers...`: Gets error message: There are no running containers to attach to.

**Comment by chrmarti** [comment]
Does `docker ps` in the integrated terminal show the container?
