### ISSUE TITLE
k8s: node not found

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#6262]
I have the same problem.  I followed this procedure (https://code.visualstudio.com/docs/remote/attach-container#_attach-to-a-container-in-a-kubernetes-cluster) and I get the following error.  I am cluster admin.
[vs-error.txt](https://github.com/microsoft/vscode-remote-release/files/7971976/vs-error.txt)

_Originally posted by @leociociano in https://github.com/microsoft/vscode-remote-release/issues/12#issuecomment-1025897136_

**Comment by chrmarti** [comment]
@leociociano The log shows it can't find `/root/.vscode-server/bin/b3318bc0524af3d74034b8bb8a64df0ccf35549a/node`. That should have been extracted there before, maybe delete `/root/.vscode-server/bin/b3318bc0524af3d74034b8bb8a64df0ccf35549a` and retry. That should make it extract the VS Code Server again, including the Node.js binary.

**Comment by leociociano** [comment]
I tried deleting ".vscode-server" complete dir, and got the same error.

[37659 ms] Remote-Containers server: /bin/sh: /root/.vscode-server/bin/b3318bc0524af3d74034b8bb8a64df0ccf35549a/node: not found
[37660 ms] Remote-Containers server: command terminated with exit code 127

The weird thing is that, when I manually search for the file in the container, it does exist:

~ # ls -l /root/.vscode-server/bin/b3318bc0524af3d74034b8bb8a64df0ccf35549a/node
-rwxr-xr-x    1 root     root      73873984 Nov  3 15:19 /root/.vscode-server/bin/b3318bc0524af3d74034b8bb8a64df0ccf35549a/node

By the way, this is the component versions I'm working with.
Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-03T15:18:44.904Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 4.18.0-305.19.1.el8_4.x86_64
Kubernetes: 1.21.8

I'm a bit confused here...

**Comment by chrmarti** [comment]
What Linux distro is the container using? I think we have seen a similar error when trying to run the libc-compiled node binary in Alpine Linux.

**Comment by leociociano** [comment]
For what I've read, Alpine Linux is based on Busybox.  Hence, I think it's the same for the purpose of your question.
Now, I tried with another Pod with an image based on CentOS 8 and it worked just fine.  I think you are right, it may be a thing with Alpine Linux.
Thank you very much for your time.

**Comment by chrmarti** [comment]
We detect Alpine Linux and use a different binary, what is in `/etc/os-release` of the container?

**Comment by leociociano** [comment]
I've been using Busybox as testing, and it does not have an /etc/os-release file (or any other file that says something about the distro). Honestly, I don't know other way to check it.  All I know is what I read in Alpine Linux site.
https://www.alpinelinux.org/about/ : "Alpine Linux is built around musl libc and busybox."

**Comment by chrmarti** [comment]
Assuming that is fine for now and closing. Thanks.
