### ISSUE TITLE
"Forwarded ports" is not visible on UI

### ISSUE THREAD

**Issue by ybonda** [microsoft/vscode-remote-release#6267]
- VSCode Version: 1.63.2
- Local OS Version: Ubuntu 20.04.3 LTS (Linux x64 5.10.0-electron.0)
- Remote OS Version:
- Remote Extension/Connection Type: SSH/Docker
- Logs:

Steps to Reproduce:

1. Open Remote Explorer

On Xubuntu tried and checked everything, but there is no such item as "Forwarded Ports" on my Remote Explorer.
The only existing features are "SSH Targets" and "Containers"

Please assist.

**Comment by alexr00** [comment]
It moved about a year ago! https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_54.md#ports-view-table-layout
