### ISSUE TITLE
Go To Definition Not Working For Java project on Remote SSH 

### ISSUE THREAD

**Issue by rest17** [microsoft/vscode-remote-release#6273]
- VSCode Version: 1.63.2
- Local OS Version:MacOS Montrey
- Remote OS Version:Ubuntu 18.04
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1.Connect to remote host using SSH
2.Open the Project directory 
3. Try going to Go To Definition using F12 key but doesn't work.
4. Also getting Maven Executable not found

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by tanhakabir** [comment]
Does the F12 key work on non remote scenarios? 

I believe this error is most likely from the Java extension so I will be moving this issue there.

**Comment by tanhakabir** [comment]
Would you mind filing an issue here? https://github.com/microsoft/vscode-java-pack

The issue creation requires some more information about your system
