### ISSUE TITLE
needs proxy pac url setting on remote

### ISSUE THREAD

**Issue by taronlee** [microsoft/vscode-remote-release#6274]
![image](https://user-images.githubusercontent.com/18044244/152293566-a7cf007b-030a-426c-90b1-32826d28e466.png)

like **Http: proxy** setting,
we need proxy pac setting.

>code --proxy-pac-url **${pac url}**
Ignoring option proxy-pac-url: not supported for code.
Unable to connect to VS Code server.

**Comment by vytautas-petrikas** [comment]
It looks like behavior of the extension has changed... It no longer downloads VS Code Server locally and instead tries to download it on the remote machine.
