### ISSUE TITLE
changing `.vscode/settings.json` in a windows workspace opened from WSL doesn't trigger updates

### ISSUE THREAD

**Issue by tao-cumplido** [microsoft/vscode-remote-release#6276]
Issue Type: <b>Bug</b>

When I connect VS Code to WSL but open a folder on the Windows drives (e.g.  under `/mnt/c/`) and update `.vscode/settings.json` directly, the change is only registered when I reload the window. When the workspace settings are updated through the Settings UI, the change is registered immediately.

I noticed this while developing an extension on WSL but opened a folder on the Windows drive in the Extension Development Host. Some of the extension's configurations can only be edited in `settings.json` directly and I was confused why `vscode.workspace.onDidChangeConfiguration` didn't fire and `vscode.workspace.getConfiguration` would still fetch the old state.

Extension version: 0.63.13
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.57GB free)|
|Process Argv|--crash-reporter-id bfafabb7-ffb7-49ef-b735-31e134ad7365|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|Memory (System)|7.77GB (4.33GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|Memory (System)|7.77GB (4.33GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|Memory (System)|7.77GB (4.33GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|Memory (System)|7.77GB (4.33GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vs360:30404995
vsrem710cf:30416617

```

</details>

**Comment by bamurtaugh** [comment]
Thanks for opening. Could you provide precise repro steps (including the settings.json)? I tried to repro, but wasn't able to. My steps:

- Open Windows folder in VS Code
- Reopen in WSL with Remote-WSL extension, so that it's mounted
- Edit .vscode/settings.json file in project
- Save, changes take effect. No reload necessary
