### ISSUE TITLE
Remote SSH doesn't save the file 

### ISSUE THREAD

**Issue by Soepavlamos** [microsoft/vscode-remote-release#6282]
Hello,

I have a Azure Virtual Machine (Ubuntu 20.04) where I have my code on.
I followed the guidelines to Remote Development using SSH with VCS.
My Client is a Mac OSX (Monterey 12.1 - Apple M1 Max) with VCS Version: 1.64.0 (Universal)

I'm able to have a successful connection and I can see, load, edit and save my python files in VCS.

Unfortunately when I save, -although I get no error - my files are not updated on the remote server.
(the left bottom shows a green SSH connection)

Am I missing something ? Should I do a sync somewhere or scp ? 
If this file is not saved on the remote server, where is it saved?

Kind regards,
Philippe

**Comment by tanhakabir** [comment]
If you open the Dev Tools with `Toggle Dev Tools..` after you try to save the file, do you see any errors?

**Comment by Soepavlamos** [comment]
Hello, 

Thanks, here's what I see.
This is an error I see in the console from the Dev Tools. but not specifically when I save. It looks like it's reconnecting lateron. I saw this sequence a couple of times.

 INFO resolveAuthority(ssh-remote) returned '127.0.0.1:62166' after 958 ms
log.ts:301  INFO [remote-connection][Management   ][f0bd6…][reconnect] connecting to 127.0.0.1:62166...
log.ts:301  INFO [remote-connection][Management   ][f0bd6…][reconnect] reconnected!
log.ts:301  INFO [remote-connection][ExtensionHost][4039d…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
log.ts:313   

ERR CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: "", type: "close", …}bubbles: falsecancelBubble: falsecancelable: falsecode: 1006composed: falsecurrentTarget: WebSocket {url: "ws://127.0.0.1:62054/?reconnectionToken=4039d336-7…b6eb8&reconnection=true&skipWebSocketFrames=false", readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}binaryType: "blob"bufferedAmount: 0extensions: "permessage-deflate"onclose: nullonerror: nullonmessage: nullonopen: nullprotocol: ""readyState: 3url: "ws://127.0.0.1:62054/?reconnectionToken=4039d336-77c8-422a-a90f-7d8d8d5b6eb8&reconnection=true&skipWebSocketFrames=false"__proto__: WebSocketdefaultPrevented: falseeventPhase: 0isTrusted: truepath: []reason: ""returnValue: truesrcElement: WebSocket {url: "ws://127.0.0.1:62054/?reconnectionToken=4039d336-7…b6eb8&reconnection=true&skipWebSocketFrames=false", readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}binaryType: "blob"bufferedAmount: 0extensions: "permessage-deflate"onclose: nullonerror: nullonmessage: nullonopen: nullprotocol: ""readyState: 3url: "ws://127.0.0.1:62054/?reconnectionToken=4039d336-77c8-422a-a90f-7d8d8d5b6eb8&reconnection=true&skipWebSocketFrames=false"__proto__: WebSockettarget: WebSocket {url: "ws://127.0.0.1:62054/?reconnectionToken=4039d336-7…b6eb8&reconnection=true&skipWebSocketFrames=false", readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}binaryType: "blob"bufferedAmount: 0extensions: "permessage-deflate"onclose: nullonerror: nullonmessage: nullonopen: nullprotocol: ""readyState: 3url: "ws://127.0.0.1:62054/?reconnectionToken=4039d336-77c8-422a-a90f-7d8d8d5b6eb8&reconnection=true&skipWebSocketFrames=false"__proto__: WebSocketCLOSED: 3CLOSING: 2CONNECTING: 0OPEN: 1binaryType: (...)bufferedAmount: (...)close: ƒ close()extensions: (...)onclose: (...)onerror: (...)onmessage: (...)onopen: (...)protocol: (...)readyState: (...)send: ƒ send()url: (...)constructor: ƒ WebSocket()Symbol(Symbol.toStringTag): "WebSocket"get binaryType: ƒ binaryType()set binaryType: ƒ binaryType()get bufferedAmount: ƒ bufferedAmount()get extensions: ƒ extensions()get onclose: ƒ onclose()set onclose: ƒ onclose()get onerror: ƒ onerror()set onerror: ƒ onerror()get onmessage: ƒ onmessage()set onmessage: ƒ onmessage()get onopen: ƒ onopen()set onopen: ƒ onopen()get protocol: ƒ protocol()get readyState: ƒ readyState()get url: ƒ url()__proto__: EventTargettimeStamp: 432507.5type: "close"wasClean: false__proto__: CloseEvent
log.ts:301  INFO [remote-connection][ExtensionHost][4039d…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:301  INFO [remote-connection][ExtensionHost][4039d…][reconnect] resolving connection...
log.ts:301  INFO [remote-connection][ExtensionHost][4039d…][reconnect] connecting to 127.0.0.1:62166...
log.ts:301  INFO [remote-connection][ExtensionHost][4039d…][reconnect] reconnected!

**Comment by bpasero** [comment]
Is this reproducible all the time or only sometimes?

**Comment by Soepavlamos** [comment]
Oh my god.... I'm so stupid....
What happened : In my terminal, I moved my files to another directory, but these files where still open in my VCS.
So by saving it in VCS he recreated the old directory and I was compiling (using command line) my package over and over again from the new location...wondering why my changes weren't applied. 
I'm so sorry I've wasted your time.
