### ISSUE TITLE
Add link to settings: Docker version 17.12.0 or later required

### ISSUE THREAD

**Issue by razzeee** [microsoft/vscode-remote-release#6288]
Docker is installed with version
Has been mentioned in https://github.com/microsoft/vscode-remote-release/issues/5866

- VSCode Version: 1.63.2
- Local OS Version: Fedora 35
- Remote OS Version: Fedora 30
- Remote Extension/Connection Type: Docker
- Logs:

Steps to Reproduce:

1. Try to open the devcontainer for https://github.com/flatpak/flatpak.github.io on a fedora install with docker
2. Get greeted by the message

**Comment by chrmarti** [comment]
What do you get for `docker version` and `which docker` in the integrated terminal?

**Comment by razzeee** [comment]
```
❯ docker version
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:03 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:48 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
❯ which docker
/usr/bin/docker
```

**Comment by chrmarti** [comment]
Could you append the log after the dialog was shown? (`F1` > `Remote-Containers: Show Container Log`)

**Comment by razzeee** [comment]
Thank you. That tried to access podman. I thought I wiped the settings, but seems like the sync failed me.

So these both settings, referenced podman before:

![image](https://user-images.githubusercontent.com/5943908/153179675-ddf5a66b-20ad-483b-8ccd-16179caff0fc.png)

Podman isn't installed on this system (anymore?, not sure)
