### ISSUE TITLE
Can't connect reliable when using ssh + password

### ISSUE THREAD

**Issue by aseques** [microsoft/vscode-remote-release#629]
- VSCode Version: 1.35
- OS Version: Windows 10

Steps to Reproduce:

1. Enable ssh authentication via password (remote.SSH.showLoginTerminal)
2. I can connect normally but having to enter the password so many times is a pain
3. Modify the config file to include the master configuration ([instructions](https://code.visualstudio.com/docs/remote/troubleshooting#_enabling-alternate-ssh-authentication-methods))
4. I get this when starting a new connection
>Install and start server if needed
>> 
>> getsockname failed: Not a socket
>> packet_write_poll: Connection to UNKNOWN port -1: Permission denied
>> 
>"install" terminal command done
>Received install output: packet_write_poll: Connection to UNKNOWN port -1: Permission denied
>Failed to parse remote port from server output: packet_write_poll: Connection to UNKNOWN port -1: Permission denied

If I am already connected when I add the ControlMaster  configuration then it works as expected, I can go for all the session working without issues.
Instead, if I open the session on a fresh visual studio core setup, then I can't connect, and I'm getting the above message.

**Comment by roblourens** [comment]
Can you include the full log?

**Comment by aseques** [comment]
I posted what I found in the screen, do you mean the log from the plugin, vscode? I am not at home right now, you mean this https://stackoverflow.com/a/54381900/322049?

**Comment by roblourens** [comment]
I mean the full log from the "Remote - SSH" output channel?

![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Comment by donestefan** [comment]
I have the same problem. Remote-ssh Log is like this:
```
remote-ssh@0.42.2
Confirming that playground8 is a valid reachable host
Running type "C:\Users\edited\AppData\Local\Temp\vscode-linux-multi-line-command-playground8.sh" | ssh  "playground8" bash to confirm the host platform
> 
> getsockname failed: Not a socket
> packet_write_poll: Connection to UNKNOWN port -1: Permission denied
> 
"uname" terminal command done
playground8: unreachable or not Linux x86_64. (packet_write_poll: Connection to UNKNOWN port -1: Permission denied)
```

Problem disappears as soon as I remove the `ControlPath  ~/.ssh/sockets/%r@%h-%p` option from my ssh client config.
It seems like windows integrated ssh has a general problem with multiplexed ssh. At least on my hosts (win10 with current patch level). Currently I can not make ssh work while `ControlPath` option is set. No wonder that vscode-remote throws an error.

My ssh config is
```
Host playground8
    HostName "192.168.1.1"
    User root
    ControlMaster auto
    ControlPath  ~/.ssh/sockets/%r@%h-%p
    ControlPersist  600
```

**Comment by roblourens** [comment]
Yeah, ControlPath is not supported on Windows. I think this was the OP's issue too.

**Comment by aseques** [comment]
After a few days using vscode, now it's working normally, I can isolate if there was a fix the resolved the issue (i got an update for vscode and applied it, but there where no mentions of ssh in the changelog).
Maybe the socket was left in an unclean state (i recall having deleted the subfolder that might have helped too)
Thanks anyway
