### ISSUE TITLE
Unable to use jupyter interactive notebook on remote development ssh connection to a server

### ISSUE THREAD

**Issue by nirzaa** [microsoft/vscode-remote-release#6293]
While trying to launch the jupyter interactive notebook on ssh connection to a server via the remote development extension it does not appear in the list.
I've found similar issue here:
https://github.com/microsoft/vscode-remote-release/issues/4479
But it was closed for some reason

**Comment by tanhakabir** [comment]
@IanMatthewHuff was there any updates to that issue? Was it ever resolved?
