### ISSUE TITLE
Working with docker inside of a remote computer via SSH

### ISSUE THREAD

**Issue by YoniChechik** [microsoft/vscode-remote-release#6295]
Is there an **easy** way to work with docker inside of a remote computer via SSH? (Explanation: The docker is running on a remote computer and we are connecting to it via SSH)

I'm sure that for data scientists it would be a really good feature. The only way I know that works is really complex and requires building a SSH agent inside the docker and then SSH tunnel our way to this docker.

It would be great to have some simple configuration to connect some remote docker vie SSH like you are doing for regular SSH.

Thanks for all of the great work on VScode and VScode-remote.

**EDIT:** The solutions given [in the docs](https://code.visualstudio.com/docs/containers/ssh) are too complex in my opinion... I was hoping for somthing a bit more smooth and user friendly to simply connect via some UI...

**Comment by vytautas-petrikas** [comment]
@YoniChechik there are some things you can try:

Update your ssh configuration `~/.ssh/config` file:
```
Host {your server address here}
    HostName {your server address here}
    IdentityFile ~/.ssh/{name of private ssh key file}
    User {your user here}
    LocalForward {Port to forward here} localhost:{Port to forward here} 
```

*Solution 1*
Setup a remote forwarded docker context by running below commands
```
docker context create my-remote-forwarded --docker="host=tcp://localhost:23750"
docker context use my-remote-forwarded
```

Forward docker sock to your local machine by starting a terminal and running below:
```
ssh -NL localhost:23750:/var/run/docker.sock {your user here}@{your server address here}
```

Reload your VS Code and check remote containers extension

*Solution 2*
Setup a remote docker context by running below commands
```
docker context create my-remote --docker="host=ssh://{your user here}@{your server address here}"
docker context use my-remote 
```

Reload your VS Code and check remote containers extension

Hope this helps :)

P.S. If you want to use docker locally again just run:
```
docker context use default
```

**Comment by YoniChechik** [comment]
Thanks @vytautas-petrikas but I already know those solutions ([from here](https://code.visualstudio.com/docs/containers/ssh)). I was hoping for somthing a bit more smooth and user friendly to simply connect via some UI...

**Comment by eitsupi** [comment]
The ability to start Remote-Containers while connected via Remote-SSH has already been implemented. It is recommended to close this issue.
https://github.com/microsoft/vscode-remote-release/issues/2994#issuecomment-979485248

**Comment by chrmarti** [comment]
@YoniChechik Make sure you have Remote-SSH installed too. You can use that to first connect to an SSH server and from there you can reopen any folder with a dev container config in a container.

**Comment by chrmarti** [comment]
@bamurtaugh Should we replace the tunneling instructions in https://code.visualstudio.com/docs/containers/ssh with a short walkthrough on how to use Remote-Containers with Remote-SSH?

**Comment by YoniChechik** [comment]
Thanks @chrmarti! do I also need Remote-docker extension?

**Comment by chrmarti** [comment]
@YoniChechik Remote-Containers, yes, that will create and connect to the dev container.

**Comment by bamurtaugh** [comment]
Thanks for looping me in, @chrmarti!

@YoniChechik we have this documented in https://code.visualstudio.com/docs/remote/containers#_open-a-folder-on-a-remote-ssh-host-in-a-container, but that is a good point it doesn't mention the info I linked about Remote-SSH + Remote-Containers. I can open a PR to discuss adding it.

**Comment by bamurtaugh** [comment]
I opened https://github.com/microsoft/vscode-docs/pull/5187.
