### ISSUE TITLE
Download update from wsl2 slow

### ISSUE THREAD

**Issue by mattiagiupponi** [microsoft/vscode-remote-release#6297]
Issue Type: <b>Performance Issue</b>

It seems that VScode takes a lot of time to download the upgrade script, my connection is ok.
![image](https://user-images.githubusercontent.com/51856725/152836295-1e8cc856-8e00-4e51-9ebd-e0f3802a1945.png)

From console log:

```
[2022-02-07 16:32:20.973] Resolving wsl+ubuntu, resolveAttempt: 1
[2022-02-07 16:32:21.026] Starting VS Code Server inside WSL (Ubuntu)
[2022-02-07 16:32:21.026] Extension version: 0.58.2, Windows build: 19044. Multi distro support: available. WSL path support: enabled
[2022-02-07 16:32:21.027] No shell environment set or found for current distro.
[2022-02-07 16:32:21.199] Probing if server is already installed: C:\Windows\System32\wsl.exe -d Ubuntu -e sh -c "[ -d ~/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2022-02-07 16:32:21.379] Probing result: x86_64
[2022-02-07 16:32:21.379] No server install found in WSL, needs x64
[2022-02-07 16:32:21.379] Downloading server on client side to C:\Users\user\AppData\Local\Temp\vscode-remote-wsl\5554b12acf27056905806867f251c859323ff7e9\vscode-server-stable-linux-x64.tar.gz.
[2022-02-07 16:32:21.380] https://update.code.visualstudio.com/commit:5554b12acf27056905806867f251c859323ff7e9/server-linux-x64/stable
[2022-02-07 16:32:22.296] Download checksum: 28100da7dcf9a2c28e1a5786e3aee858f4a5d108e4a429ae38fedb884bc012b9
```
Is almost 1 hour that is stuck in this download

I also tried to restart the PC and ping (from wsl2) the `update.code.visualstudio.com` and is not responding:
```
➜  ping update.code.visualstudio.com
PING waws-prod-am2-193.cloudapp.net (51.144.164.215) 56(84) bytes of data.
--- waws-prod-am2-193.cloudapp.net ping statistics ---
30 packets transmitted, 0 received, 100% packet loss, time 30138ms
```

Extension version: 0.64.2
VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Connection to 'wsl+ubuntu' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3400G with Radeon Vega Graphics     (8 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.95GB (2.44GB free)|
|Process Argv|--crash-reporter-id 844cb9dd-5129-49d8-b3b0-e2ac6e011014|
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+ubuntu' could not be established
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   147	  6320	code main
    0	    41	  2352	   utility-network-service
    0	   266	  2420	   extensionHost
   20	   358	  2024	     "C:\Users\user\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\user\.vscode\extensions\ms-python.vscode-pylance-2021.9.1\dist\server.bundle.js --cancellationReceive=file:caf600814134ca5272d2aa8ca3beabae5bae4ca09d --node-ipc --clientProcessId=2420
    0	    72	 15136	     "C:\Users\user\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\user\.vscode\extensions\tht13.python-0.2.3\node_modules\vscode-languageclient\lib\utils\electronForkStart c:\Users\user\.vscode\extensions\tht13.python-0.2.3\out\server\src\server.js
    0	   102	  7052	   shared-process
    0	    75	  9360	     fileWatcher
    0	    33	 16464	     ptyHost
    0	     6	  2224	       console-window-host (Windows internal process)
    0	    81	  6328	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    11	 16764	     fileWatcher
    0	    84	  9632	   issue-reporter
    1	   132	  9972	   gpu-process
    0	    29	 11992	   extensionHost
    0	    16	 16624	     "C:\Users\user\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-wsl-0.58.2\dist\wslDaemon.js
    0	    13	 14284	   crashpad-handler
    0	   110	 14976	   window (Get Started - emsa-tdms [WSL: Ubuntu] - Visual Studio Code)
    0	   325	 15792	   window (ingestion.py - C183-ALMAVIVA-2021-Ingestion - Visual Studio Code)
Connection to 'wsl+ubuntu' could not be established
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ingestion.py - C183-ALMAVIVA-2021-Ingestion - Visual Studio Code)
|    Folder (C183-ALMAVIVA-2021-Ingestion): 33 files
|      File types: py(6) pyc(2) log(2) tif(2) gitignore(1) json(1) txt(1)
|                  yaml(1) md(1) gz(1)
|      Conf files: dockerfile(2)
Connection to 'wsl+ubuntu' could not be established;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vs360cf:30404996
vsrem710cf:30416617
vscscmwlcmt:30433761

```

</details>

**Comment by bamurtaugh** [comment]
> It seems that VScode takes a lot of time to download the upgrade script

Have you connected to Remote-WSL in VS Code before, and now you are trying to download an update (to VS Code, or Remote-WSL)? If you've connected before, how long did it take to connect?

Are you behind any sort of proxy?

**Comment by mattiagiupponi** [comment]
Hi, thanks for the reply:

> Have you connected to Remote-WSL in VS Code before, and now you are trying to download an update (to VS Code, or Remote-WSL)? If you've connected before, how long did it take to connect?

Yes, I worked with the Insiders version (it updates quite often) for almost 1 year before facing this problem. To solve it, I had to install the stable version since it doesn't require to be updated too often.
Before facing this issue, it took seconds to update the WSL.

> Are you behind any sort of proxy?

Nope

**Comment by bamurtaugh** [comment]
Are you still able to connect to Remote-WSL in Insiders? 

Also, you can set your update preferences in VS Code, in case this would help in the future: https://code.visualstudio.com/docs/supporting/FAQ#_how-do-i-opt-out-of-vs-code-autoupdates.

**Comment by littleomie** [comment]
I have a similar issue now. My internet is good. Normally, this only takes around 5-10 minutes.

```
Updating VS Code Server to version b5205cc8eb4fbaa726835538cd82372cc0222d43
Removing previous installation...
Installing VS Code Server for x64 (b5205cc8eb4fbaa726835538cd82372cc0222d43)
Downloading:   1%
```

**Comment by Lucas-C** [comment]
I have the same issue...
In 15min, less than 25MB of `C:\Temp\vscode-remote-wsl\e18005f0f1b33c29e81d732535d8c0e47cafb0b5\vscode-server-stable-linux-x64.tar.gz_1649260128376` were downloaded
