### ISSUE TITLE
devcontainer.json runArgs / upArgs for docker-compose command

### ISSUE THREAD

**Issue by yannissgarra** [microsoft/vscode-remote-release#6298]
It would be nice to support `runArgs` parameter to call some args on docker-compose command.

For example, we could use the `--env-file` option on docker-compose command to specify custom `.env` file name where we set `COMPOSE_PROJECT_NAME` (it's a common use case to have a committed `.env` file but an ignored `.env.local` file that override some values).

(It might also be an `envFile` parameter in `devcontainer.json` to specify the `.env` file to use)

Thanks!

**Comment by sanmai-NL** [comment]
See also #4885.

**Comment by crhan** [comment]
`upArgs` for docker-compose is really useful when several developers use dev container on the same server . Otherwise a project name collision will happen.
