### ISSUE TITLE
Keeps asking for SSH config file

### ISSUE THREAD

**Issue by tralston** [Microsoft/vscode-remote-release#63]
- VSCode Version: 1.34.0-insider
- Local OS Version: Windows 10 v1809 17763.316/MacOS 10.14.4
- Remote OS Version: Linux (Synology, WSL)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Click the Remote SSH plugin icon
2. Notice that Connections list says "No SSH hosts have been configured yet. Configure a SSH host."
3. Click the "Configure a SSH host" link.
4. Select ssh config file.
5. Nothing changes.
6. Open settings and specify path to config file, save.
7. Still nothing changes, no list of potential connections, not even list of active connections.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
@roblourens  I see exactly the same on my machine. When I use the command palette UI, I do see the hosts:

![Screenshot from 2019-05-03 16-37-45](https://user-images.githubusercontent.com/22350/57144680-db7c8f80-6dc1-11e9-85d9-d3981e5530c7.png)

**Comment by kieferrm** [comment]
Interesting. The list comes from the same code in both cases.

**Comment by tralston** [comment]
Turns out my config file had lower case `host` entries as soon as I capitalized them to `Host`, they all showed up, including ones I was currently connected to. As mentioned in #68, it should be able to process case-insensitive keywords.
