### ISSUE TITLE
Access old terminal sessions after reconnecting

### ISSUE THREAD

**Issue by Xazax-hun** [microsoft/vscode-remote-release#630]
After closing a Remote VS Code window and reopening the connection later on it would be great to be able to access the terminal sessions from the previous window. On the host I can still see the processes (that I started in the closed VS Code) running, but I did not find any ways to get back to old terminals rather than starting a new one.

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/44302

**Comment by Tyriar** [comment]
/duplicate

This is possible now although there is currently a bug being tracked for remote: https://github.com/microsoft/vscode/issues/133741
