### ISSUE TITLE
Spring Developer Tools not working in Java Container

### ISSUE THREAD

**Issue by nathanielsuchy** [microsoft/vscode-remote-release#6301]
I'm working on a Java/Spring Boot Application and like many web applications created with Java and Spring Boot it uses Thymeleaf and Static Resources (CSS, JS, etc). These resources are stored in `resources/static/**`. 

In GitHub Codespaces to see a CSS change I restart the Spring server, not a huge deal but it works with only a slight annoyance. However, if I want to use my local computer instead of GitHub Codespaces I launch up a VS Code Dev Container with the VS Code Remote Containers Extension. 

When I update any template or static file the only way to update to take effect is for me to run `mvn clean` and `mvn install` to force the entire `target/**` folder to rebuild. Stopping and starting the server is not enough. The files are not copied to `target/**`. I've cleared Chrome cache, it's not a caching issue, I even tested with curl just in case. This even happened when I updated `application.properties`. Which is bad!

This affects any thymeleaf template and static resource.  I can confirm that by restarting the application and opening the `target/**` directory and seeing the file there has not updated. Does VS Code update the last updated timestamp any time you update a CSS file? GitHub Codespaces uses Docker on presumably Linux whereas I run VS Code with Dev Containers on Windows 11 without issue.

An interesting thing about this bug is GitHub Codespaces and VS Code Remote Containers both use Dev Containers (Docker file and stuff is at https://github.com/irlcatgirl/vscode-java-spring-live-reload-config) so it should work in both locations but does not. GitHub Codespaces is in beta and likely has undocumented quirks.

**Sample Repo**
I created a sample repo to show the bug. Please compare https://github.com/irlcatgirl/spring-boot-bug-29664-demo/blob/master/src/main/resources/templates/index.html and https://github.com/irlcatgirl/spring-boot-bug-29664-demo/blob/master/target/classes/templates/index.html for further verification of the bug. You can run this demo in any computer with VS Code, Remote Containers Extension, and Docker Desktop.

**The gist**
Changing any file in my Java application does not copy it over to the classpath (e.g. `target/**`). This bug is specific to Java inside a Dev Container. VS Code directly is not affected, and for some reason, it works fine in GitHub Codespaces.

**Comment by irlcatgirl** [comment]
> Is your workspace folder on Windows or in WSL? If on Windows: Do you have `Remote > Containers: Execute in WSL` enabled?

My machine runs Windows 11. The WSL question is complicated because Docker uses WSL but remote containers say it does not. They say a picture is worth 1000 words so I included several of different contexts :)

**Execute in WSL is off:**
![image](https://user-images.githubusercontent.com/8227641/153043117-fa9107eb-6503-4e39-90e5-0ee7d5efc868.png)

**Docker settings:**
![image](https://user-images.githubusercontent.com/8227641/153043196-af63ce47-30ea-4c01-81d1-227cc20dc81c.png)


**System details:**
![image](https://user-images.githubusercontent.com/8227641/153042944-8311289d-b014-4af9-9ca9-8886ae0aad96.png)

**Application running in debug mode in container:**
![image](https://user-images.githubusercontent.com/8227641/153043832-16720414-ff21-4a10-bea3-fa5835b3b2d6.png)

**Comment by chrmarti** [comment]
Make sure the files are changed on the Linux side. There is an issue with file events in WSL when the files change on the Windows side: https://github.com/microsoft/WSL/issues/4739

**Comment by chrmarti** [comment]
My guess is that the copying waits for file events from the OS to know which files need to be copied. When these events don't fire due to some bug, then that bug is causing the problem. Am I missing something?

**Comment by irlcatgirl** [comment]
> My guess is that the copying waits for file events from the OS to know which files need to be copied. When these events don't fire due to some bug, then that bug is causing the problem. Am I missing something?

To make sure I understand. Spring does not see the file updated event even though the file was changed on the disk and is visible on application server restart, therefore the live reload plugin does not know to copy assets to `target/**`. Is this something we have to wait on WSL2 to fix?

**Comment by chrmarti** [comment]
This is my guess, but the only setup I know of where this is a problem is when the file is changed by a Windows application and the WSL Linux side then does not get a change event. Could this be the case here? Which application is changing the files?

**Comment by chrmarti** [comment]
Does this work when you use a Docker volume for the repository? You get that when you use `F1` > `Remote-Containers: Clone Repository in Container Volume...`.
