### ISSUE TITLE
Allow user to choose where vscode-server dependencies are downloaded

### ISSUE THREAD

**Issue by vytautas-petrikas** [microsoft/vscode-remote-release#6304]
After update to VS Code version 1.64.0 the extension dependencies are no longer downloaded locally (via the ui) and vs code tries to download dependencies on the remote.

While https://github.com/microsoft/vscode-remote-release/issues/6274 covers proxy configuration settings on the remote it does not allow user to specify that download should occur locally. Therefore people working in air tight environments with no internet connectivity from the remote machine cannot install the server.

Please allow to specify on the user settings where the dependencies should be downloaded:

// settings.json
```
{
     "remote.downloadDependenciesLocally": true // defaults to false
}
```

Also, some improvement could be to allow users specify some mirror for the dependecies (i.e. artifactory users)
// settings.json
```
{
   "remote.downloadDependencyMirror": "https://somehostname.com/somedir/" 
   // expected call https://somehostname.com/somedir/5554b12acf27056905806867f251c859323ff7e9/server-linux-x64/stable
}
```

**Comment by vytautas-petrikas** [comment]
@chrmarti yes it is related to that, but this is a feature request which would allow users to specify where vscode-server should be downloaded. Also, adding a mirror option would be nice.

Please let me know what additional information I should provide 🙂

**Comment by chrmarti** [comment]
Makes sense. This has come up before, but I don't think we have a separate issue yet. Labelling as feature request.

**Comment by kedelux** [comment]
Doesn't #6146 sound similar?
We also have the problem that neither the client nor the remote in the company have internet access with the necessary rights to download. So the vscode-server installation is unfortunately impossible.

**Comment by bamurtaugh** [comment]
> This has come up before, but I don't think we have a separate issue yet.

@chrmarti In case it's useful, there is an SSH-labeled one: https://github.com/microsoft/vscode-remote-release/issues/6146.

**Comment by chrmarti** [comment]
Thanks, closing as duplicate.
