### ISSUE TITLE
Debugging python tests yields error message: Unable to open 'filename.py': File not found

### ISSUE THREAD

**Issue by NuclearFartman** [microsoft/vscode-remote-release#6305]
- VSCode Version: 1.64.0 (user setup)
- Local OS Version: Windows_NT x64 10.0.19042
- Remote OS Version: Ubuntu 20.04.3 LTS
- Remote Extension/Connection Type: WSL2
- Logs:

Steps to Reproduce:

1. Install Remote Containers extension
2. I have the following project setup:
![image](https://user-images.githubusercontent.com/38425837/152963954-81f89753-34f8-4e31-9916-7397dfcf9ac3.png)
3. Dockerfile:

FROM debian:bullseye as base

RUN apt-get update
RUN apt-get install -y git python3 python3-pip make zip
RUN pip3 install cfn-lint mock pylint pylint-quotes pytest pytest-cov awscli virtualenv pipenv

USER root

WORKDIR /app

ARG PYPI_USER_ARG
ARG PYPI_PASS_ARG
ENV PYPI_USER=$PYPI_USER_ARG
ENV PYPI_PASS=$PYPI_PASS_ARG

FROM base as test-service-a

WORKDIR /app
COPY ./service-a/Pipfile /app
COPY ./service-a/Pipfile.lock /app

RUN pipenv lock -r --dev > requirements.txt
RUN pip3 install -r requirements.txt
RUN rm -f Pipfile
RUN rm -f Pipfile.lock

RUN ln -s /usr/bin/python3 /usr/bin/python

FROM base as test-service-b

WORKDIR /app
COPY ./service-b/Pipfile /app
COPY ./service-b/Pipfile.lock /app

RUN pipenv lock -r --dev > requirements.txt
RUN pip3 install -r requirements.txt
RUN rm -f Pipfile
RUN rm -f Pipfile.lock

RUN ln -s /usr/bin/python3 /usr/bin/python`
4. docker-compose.yml:
`version: '3.4'

services:
  test-service-a:
    build:
      context: .
      dockerfile: Dockerfile
      target: test-service-a
      args:
        PYPI_USER_ARG: ${PYPI_USER}
        PYPI_PASS_ARG: ${PYPI_PASS}
    volumes:
      - ./service-a/:/app
    working_dir: /app

  test-service-b:
    build:
      context: .
      dockerfile: Dockerfile
      target: test-service-b
      args:
        PYPI_USER_ARG: ${PYPI_USER}
        PYPI_PASS_ARG: ${PYPI_PASS}
    volumes:
      - ./service-b/:/app
    working_dir: /app`
5. run command: docker-compose build --force-rm
6. run command: docker-compose run --rm -d test-service-a
7. run command: docker-compose run --rm -d test-service-b
8. Attach to one running container and then to the other (two vs-code windows open)
9. After installing the usual python extension (ms-python.python) in the container the tests are correctly discovered. But no breakpoint is respected and when clicking on Debug on the method level there is this error message: Unable to open 'filename.py': File not found
10. Workaround: Renaming a test or writing a new one often fixes the issue for this specific file but not for the others. I suspect some discovery errror.

**Comment by chrmarti** [comment]
Could you attach the log from when this happens? (`F1` > `Remote-Containers: Show Container Log`)

**Comment by chrmarti** [comment]
Not related to https://github.com/microsoft/vscode-python/issues/18436 I guess?
