### ISSUE TITLE
overrideCommand: true is not respected when using docker-compose

### ISSUE THREAD

**Issue by pcorliss-provi** [microsoft/vscode-remote-release#6307]
We run development containers using a docker-compose file and a devcontainer file. We set the `overrideCommand` property to `true` in our `devcontainer.json` file. This worked up until about 2 days ago before users started reporting that they couldn't start their development environments.

On investigating further it appears that `overrideCommand` is being ignored and vs code is not running the command outlined in the documentation.

> Tells VS Code and other devcontainer.json supporting services / tools whether they should run `/bin/sh -c "while sleep 1000; do :; done"` when starting the container instead of the container's default command

I've included a minimal git repository below that I believe demonstrates the issue. Which is the docker-compose command being executed instead of `/bin/sh -c "while sleep 1000; do :; done"` as specified in the documentation.

- VSCode Version: Version: 1.64.0 (Universal)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:20:17.224Z (5 days ago)
- Local OS Version: MacOs BigSur 11.6/Darwin x64 20.6.0
- Remote OS Version: Alpine Latest & Ubuntu 18.04
- Remote Extension/Connection Type: Docker
- Logs: N/A

Steps to Reproduce:

1. git clone https://github.com/pcorliss-provi/vscode-overridecommand.git
2. cd vscode-overridecommand
3. Open repository in container
4. Open vs code terminal
5. Run `ps aux | grep sleep`
6. Notice that the `docker-compose.yml` command is being executed `sleep 12345` instead of the command referenced by 

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
@pcorliss-provi Thanks for the sample repository!

Fixed in Remote-Containers 0.217.2 (and 0.220.0 pre-release).

@edgonmsft @joshspicer FYI: Fix is also in the CLI 0.57.2 for Codespaces. (The default is `"overrideCommand": false`, so maybe not super critical.)
