### ISSUE TITLE
Issue changing file name switching letters from lower to pascal case.

### ISSUE THREAD

**Issue by GoldenGuillaume** [microsoft/vscode-remote-release#6308]
Issue Type: <b>Bug</b>

I'm currently working with a project located on windows filesystem from wsl with the extension, I'm using WSL1.

When i'm trying to rename a file for example app.js to App.js the following error occur:

Impossible de déplacer/copier 'vscode-remote://wsl+debian/mnt/d/example/path/project/src/app/redux/hook.ts' parce que la cible 'vscode-remote://wsl+debian/mnt/d/example/path/project/src/app/redux/hooK.ts' existe déjà dans la destination.

to translate it in english it's saying: 
Impossible to move/copy  'vscode-remote://wsl+debian/mnt/d/example/path/project/src/app/redux/hook.ts' because the target 'vscode-remote://wsl+debian/mnt/d/example/path/project/src/app/redux/hooK.ts' already exist in the destination.

The problem is occuring only when i'm trying to capitalize or downcasing a letter of the filename, if i change the filename hook.ts by hooks.ts for example it works.

Extension version: 0.64.2
VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:16:22.147Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (4.45GB free)|
|Process Argv|--crash-reporter-id 3bd38df6-8ab6-444c-a6ec-89e803b507e6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|Memory (System)|15.90GB (4.45GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30433058
pythonvs932:30410667
wslgetstarted:30433507
vscop341:30404997
vsrem710cf:30416617
vscop841cf:30434590
vscscmwlcmt:30433761
i9688383:30435148

```

</details>

**Comment by BrutalSimplicity** [comment]
yea, I'm getting this issue as well. I _think_ vscode is issuing the move command in a way that assumes case insensitivity.

**Comment by BrutalSimplicity** [comment]
On further looking at this, I now wonder if it's the container causing the issue. 🤔 
Even when I try to issue the command from the terminal it fails.

**Comment by bamurtaugh** [comment]
cc @aeschli does marking as a bug make sense to you?

**Comment by aeschli** [comment]
That WSL, not VS Code specific. See https://github.com/microsoft/WSL/issues/4767
