### ISSUE TITLE
Cannot reconnect. Please reload the window.

### ISSUE THREAD

**Issue by MondoBurrito** [microsoft/vscode-remote-release#6310]
I am CONSTANTLY getting this error:

Cannot reconnect. Please reload the window.

Help! It has been happening for days.

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36
Embedder: codespaces

**Comment by roblourens** [comment]
There are lots of thing that can lead to that error. Please make sure you have updated first, that version is old.

**Comment by MondoBurrito** [comment]
I see it ALL THE TIME. Sometimes I could work for 5 minutes before it showed up... sometimes it happens every 10 seconds.  I am not sure how to update, but I did delete that Codespace and created a new one. The error came back :(

**Comment by roblourens** [comment]
Didn't notice that this is codespaces, please open an issue at https://github.com/github/feedback/discussions/categories/codespaces-feedback
