### ISSUE TITLE
How do I get a plugin with an earlier version?

### ISSUE THREAD

**Issue by wsq-7** [microsoft/vscode-remote-release#6311]
I have an IDE based on the vscode. It seems that the version of the IDE is too old to support the installation of remote-ssh. Can I get the plugin that dominates my base version?
My base version is as follows:
```
VSCode-huawei: 1.60.3
Commit: 86869d3dc996c994b0297c4befdd0d6cce60db4b
Date: 2022-01-20T06:44:44.537Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by tanhakabir** [comment]
I'm not sure about your IDE but on VS Code you can install another version on the extension page from search.
