### ISSUE TITLE
Container Remote Development: `$SSH_AUTH_SOCK` not respected while attaching a session

### ISSUE THREAD

**Issue by juergendrachta** [microsoft/vscode-remote-release#6312]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: Arch Linux with Kernel 5.16.2-arch1-1 and Openbox

Steps to Reproduce:

1. Starting `ssh-agent` and manipulating `~/.bash_profile` (or `~/.bashrc`) according to [the official doc](https://code.visualstudio.com/docs/remote/containers#_using-ssh-keys), i.e.
   1. Starting an ssh-agent via `ssh-agent` and
   1. adding following lines to the bash startup scripts
      ```bash
       if [ -z "$SSH_AUTH_SOCK" ]; then
         # Check for a currently running instance of the agent
         RUNNING_AGENT="`ps -ax | grep 'ssh-agent -s' | grep -v grep | wc -l | tr -d '[:space:]'`"
         if [ "$RUNNING_AGENT" = "0" ]; then
              # Launch a new instance of the agent
              ssh-agent -s &> $HOME/.ssh/ssh-agent
         fi
         eval `cat $HOME/.ssh/ssh-agent`
       fi
1. I checked, that every new spawned terminal (as well as the integrated bash terminal in VS Code) has the variable `$SSH_AUTH_SOCK` set accordingly, which is the case.
1. I ensured that the VS Code Setting `Inherit Env` is set to true in the general settings (as this already caused troubles, c.f. https://github.com/microsoft/vscode-remote-release/issues/2926)
1. Then, when I try to attach to a container (in the Docker extension, right click on a container and `Attach Visual Studio Code`), i see in the log files (F1 -> `Remote Container Developers: Show All Logs`): 
   ```
     ....
    [2022-02-04T10:11:22.656Z] Start: Launching Remote-Containers helper.
    [2022-02-04T10:11:22.657Z] ssh-agent: SSH_AUTH_SOCK not set on host.
    [2022-02-04T10:11:22.657Z] Start: Run: gpgconf --list-dir agent-extra-socket
     ...     
     and thus, the inside the container, I don't have access to the agent, and git etc doesn't work.

![image](https://user-images.githubusercontent.com/24944956/152512433-f46782fd-fae4-43c9-8d66-d5dee1eae2bd.png)

I tried it as well with the `VS Code insiders` -- with no success. 

What I also found out: 

As a workaround, I tried to manually mount the ssh-agent socket into the container, by adding the following portion to my `docker-compose.yml`
```yaml
myapp:
   ...
   volumes:
      - $SSH_AUTH_SOCK:/root/.ssh/ssh_auth_sock
```
When I start this compose file via "Right click on file -> Compose Up" in VS Code's file explorer, then I get the following error indicating that the env var `$SSH_AUTH_SOCK` is not present when I let VS Code start docker-compose by itself:
```bash
> Executing task: docker-compose -f "docker/devel/docker-compose.yml" up -d --build <

source /home/juergen/miniconda3/bin/activate
WARN[0000] The "SSH_AUTH_SOCK" variable is not set. Defaulting to a blank string. 
1 error(s) decoding:

* error decoding 'Volumes[2]': invalid spec: :/root/.ssh/ssh_auth_sock: empty section between colons
The terminal process "/bin/bash '-c', 'docker-compose -f "docker/devel/docker-compose.yml" up -d --build'" failed to launch (exit code: 15).
```

But when I up the containers via VS Code's terminal and 
```bash
docker-compose -f docker/devel/docker-compose.yml up
```
then it works.

Maybe someone who knows, how docker-compose gets executed by VS Code, has a clue, why `$SSH_AUTH_SOCK` is not available when I start docker-compose by VS Code. 

Interestingly, on MacOS, Ubuntu and Windows we managed to get it running without problems. Somehow I suspect that it's some specific problems with Arch linux default settings in ~/.bash_rc etc. But I ensured, that each new bash session inherits `SSH_AUTH_SOCK`, but this isn't translated to the container.

**Comment by juergendrachta** [comment]
Thx for your reply.

In the parent's VSCode window, i find the following entry in the `Log (Main)` after attaching the IDE to a container: 
>[2022-02-23 16:09:20.279] [main] [trace] resolveShellEnv(): skipped (VSCODE_CLI is set)

**Comment by chrmarti** [comment]
VSCODE_CLI is set when you start VS Code from the terminal (not the UI dock). Is `SSH_AUTH_SOCK` set in the terminal you start VS Code from?

**Comment by juergendrachta** [comment]
Thanks for your help -- this indeed was the issue. 

I'm using [dmenu](https://wiki.archlinux.org/title/dmenu) for starting programs -- which doesn't execute bash settings beforehand, what I now found out the hard way thanks to your help! 
When starting VS code from bash, `SSH_AUTH_SOCK` is set within code, and thus the socket is forwarded into the container as expected.
