### ISSUE TITLE
Download of vscode-server on client fails with ECONNRESET

### ISSUE THREAD

**Issue by kczx3** [microsoft/vscode-remote-release#6313]
In the upcoming version we now download the server on the Windows side. That way we avoid problems with missing proxy settings or missing certificates.

_Originally posted by @aeschli in https://github.com/microsoft/vscode-remote-release/issues/79#issuecomment-504368316_

What is the command that's run on the client (Windows 10, in this case)?  I am getting ECONNRESET and can't figure out what the problem is.  I am behind a corporate proxy and downloading the .zip works from the browser.  Trying to use curl from the Windows CMD fails but I think that's because it isn't using my proxy.

**Comment by kczx3** [comment]
Well, even though VS Code on my machine was failing to download and install the latest vscode-server version both locally and via WSL, I was able to get it to function by opening my own WSL terminal instance and running `code .` which downloaded and installed everything just fine.

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/issues/142201 is the issue for this. Fix is on the way.

**Comment by kczx3** [comment]
Thank you!
