### ISSUE TITLE
Clone Repository in Container Volumes does not work with GitLab Extension. How to debug?

### ISSUE THREAD

**Issue by J0F3** [microsoft/vscode-remote-release#6315]
- VSCode Version: 1.64.1
- Local OS Version: Windows 10, H21H2
- Remote OS Version: N/A (Linux Container)
- Remote Extension/Connection Type: Docker
- Logs: ?

Steps to Reproduce:

1. Install extension GitLab Workflow
2. Crtl + Shift + P
3. Remote-Containers: Clone Repository in Container Volume...
3. Clone a repository from GitLab (https://gitlab.com) in a Container Volume
4. Select a repository
5. Select an URL (I have to use the HTTPS URL due Firewall which is blocking SSH).
6. Nothing happens (instead of cloning and building the dev container.)

If I copy & paste the HTTPS URL of the same repository in step 3 (instead of browsing the repo in VS Code) it works as expected. 

How can I troubleshoot this? Which log do I need to look at?

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Works for me when I use the clone https:// URL for a public repository. Could you append the log? (`F1` > `Remote-Containers: Show Container Log`)

**Comment by muhammedbasilsk** [comment]
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0
Logs: Added below


Steps: To reproduce
1. Open visual studio
2. CMD+Shift+P - Remote-Containers: Clone Repository in Container Volume

For repo HTTPS URL:
```
Cannot access the repository 'https://gitlab.com/********/*****************.git'.
```
For SSH:
```
Git clone failed. Cloning into '.'...
git@gitlab.com: Permission denied (publickey,keyboard-interactive).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by J0F3** [comment]
@chrmarti 

There is nothing in the log and nothing happens. 

Note that it work also for my private repo if I paste the https URL but it works not when I select 'Clone a repository form GitLab' and select the same repo. 

That works:
![image](https://user-images.githubusercontent.com/12759579/155278043-c7f63372-1cf8-4d57-9ae7-451a52fbb2f8.png)

But this does not not (after selecting the repo absolutely nothing happens in vs code):
![image](https://user-images.githubusercontent.com/12759579/155278088-fc9f157e-667c-490d-a8c7-c207a2ced2e0.png)
![image](https://user-images.githubusercontent.com/12759579/155278228-a79f04db-8d71-469c-9422-dccbf3e163ef.png)

But I saw now that when searching the repo through vs code end in a clone trough ssh instead of https. This is probably my problem because SSH is blocked by the corporate firewall which I am behind.

So it fails probably already before dev containers are coming into play. But it is a lite strange that I get not even an error message.

**Comment by chrmarti** [comment]
I don't see 'Clone from GitLab' when I have GitLab Workflow installed. Could you check which extension contributes that?

**Comment by J0F3** [comment]
It is definitely the 'GitLb Workflow' extension but I think you see 'Clone form GitLab' only after you have set a personal access token to access gitlab.com. 
After you installed the extension klick on the GitLab icon on the left then you should see that:
<img width="353" alt="Screenshot 2022-02-23 at 10 33 52" src="https://user-images.githubusercontent.com/12759579/155293353-0fa2786a-9713-4b46-b789-16ec7660367e.png">

Or F1 > GitLab: Set GitLab Personal Access Token

**Comment by chrmarti** [comment]
Got it working with a fix in Remote-Containers. Thanks.

**Comment by J0F3** [comment]
Cool! Thank you!

**Comment by muhammedbasilsk** [comment]
I am still facing the same issue.
@chrmarti could you please share the steps you followed to achieve it or some pointers?

**Comment by chrmarti** [comment]
@muhammedbasilsk The fix will be in the next pre-release (0.224.0, maybe today) and later stable release (expected next week) version of the Remote-Containers extension. The fix is not released yet.

**Comment by muhammedbasilsk** [comment]
Okay, Thanks @chrmarti

**Comment by chrmarti** [comment]
Publishing with 0.224.1 pre-release (you can switch Remote-Containers to pre-releases in the Extensions viewlet).

**Comment by J0F3** [comment]
@chrmarti Just tested with the pre-release and it works now as expected. Thx!

**Comment by rzhao271** [comment]
Marking as verified based on https://github.com/microsoft/vscode-remote-release/issues/6315#issuecomment-1054505791

**Comment by muhammedbasilsk** [comment]
It worked with the 0.224.1 pre-release version . Thank you.

**Comment by chemelli74** [comment]
> Steps: To reproduce
> 
> 1. Open visual studio
> 2. CMD+Shift+P - Remote-Containers: Clone Repository in Container Volume
> 
> For repo HTTPS URL:
> 
> ```
> Cannot access the repository 'https://gitlab.com/********/*****************.git'.
> ```

Still same issue here, both using `v0.230.0` pre-release and `v0.224.3` release.

Simone
