### ISSUE TITLE
Install vscode server in an offline environment

### ISSUE THREAD

**Issue by realprocrastinator** [microsoft/vscode-remote-release#6318]
Hi, I knew that vscode can download the `vscode-server.tar.gz` on the clientside and transfer it to the remote side using scp. However, in my situation, my clientside machine is behind the firewall, and can't perform downloading. So I manually installed the `vscode-server.tar.gz` from the website according to the release COMMIT_ID and extracted it under the remote host's `.vscode/bin/{COMMIT_ID}`. However, vscode doesn't seem to notice that the server has already been installed on the remote side and keeps downloading from the internet and failed. My question is how to inform vscode that I've already had a vscode server on the remote side and can skip the package downloading phase?

**Comment by tanhakabir** [comment]
This unfortunately isn't a flow we've implemented yet. We're tracking this request with https://github.com/microsoft/vscode-remote-release/issues/1242
