### ISSUE TITLE
not able to debug with python in virtual environment in remote ssh instance

### ISSUE THREAD

**Issue by raghavk92** [microsoft/vscode-remote-release#632]
Issue Type: <b>Bug</b>

Hi,
I have  a virtual environment in folder /home/ubuntu/venv/enn

my launch.json is:
`{
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Python: session_server",
            "type": "python",
            "request": "launch",
            "program": "/home/ubuntu/path/to/file/session_server.py",
            "console": "integratedTerminal",
            "pythonPath" : "/home/ubuntu/venv/enn/bin/python",
            
            "args": ["--config_file=../domain/path/to/test_config.hocon"]
        }
    ]
}`

i added my python.pythonPath in settings(Remote-ssh) as  /home/ubuntu/venv/enn/bin/python

on the bottom bar i have clicked on the python from the virtual environment in vscode-insiders.

So when i run the python program as is without debugging in the virtual environment it runs perfectly but when i try to debug it says import error for many of the import statements. Even pyllint gives import error. What is the correct procedure for debugging to work correctly in vscode-insiders in remote ssh as it was working a few days back but now it stopped working.

Extension version: 0.42.0
VS Code version: Code - Insiders 1.36.0-insider (c089daa858f34631f5f827ff8a0313bf1e2ded6d, 2019-06-07T05:19:15.188Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-1075-aws

**Comment by roblourens** [comment]
Please file this issue on the Python extension, thanks: https://github.com/microsoft/vscode-python/issues
