### ISSUE TITLE
Visual Studio Server ask for user input on remote connection

### ISSUE THREAD

**Issue by Lorac** [microsoft/vscode-remote-release#6321]
Version: 1.65.0-insider (system setup)
Commit: 82a8bec63666b0883d9bf762ee2aaa87e9be9a3a
Date: 2022-02-10T05:16:36.093Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Windows_NT x64 10.0.22543

- VSCode Version: 1.65.0-insider (system setup)
- Local OS Version: Windows 11
- Remote OS Version: buntu 21.04
- Remote Extension/Connection Type: SSH
- Logs:

```
...
[12:46:54.262] "install" terminal received data: "Waiting for server log..."
[12:46:54.297] "install" terminal received data: "Waiting for server log..."
[12:46:54.334] "install" terminal received data: "Waiting for server log..."
[12:46:54.371] "install" terminal received data: " 
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) [30;80H
*
[1C"
[12:46:54.383] "install" terminal received data: "
Server did not start successfully. Full server log at /home/maxrous/.vscode-serv
[29;80Hver-insiders/.82a8bec63666b0883d9bf762ee2aaa87e9be9a3a.log >>>
server.sh is being replaced by 'bin/code-server-insiders'. Please migrate to the
[29;80He new command and adopt the following new default behaviors:[?25l
* connection token is mandatory unless --without-connection-token is used       [30;74H[?25h
* host defaults to `localhost`
*
* Visual Studio Code Server
*[?25l
* Reminder: You may only use this software with Visual Studio family products,  [30;79H[?25h
* as described in the license https://aka.ms/vscode-server-license
*
Do you accept the terms in the License Agreement? <<< End of server log
e6c9ffaa4f46: start
exitCode==32==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==7686==
e6c9ffaa4f46: end"
```

Looks like it's waiting on user input.

Steps to Reproduce:

1. Connect to remote host
2. Wait till it errors out

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by rdlaner** [comment]
@Lorac I was able to work around this issue by changing to the "pre-release" version of the "Remote-SSH" extension.

**Comment by niderhoff** [comment]
I guess it is tied to a very recent insider's release, the issue started happening today for me.

**Comment by niderhoff** [comment]
> @Lorac I was able to work around this issue by changing to the "pre-release" version of the "Remote-SSH" extension.

https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh This one?

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/6328

Apologies, yes you can switch to "pre-release" to work around this until we get a new stable release out

**Comment by buxiangqimingle233** [comment]
> > > @Lorac I was able to work around this issue by changing to the "pre-release" version of the "Remote-SSH" extension.
> > 
> > 
> > https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh This one?
> 
> Exactly that worked for me, they announced the pre-release version recently: https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_64.md#ssh-version-072x

Thanks a lot, that works for me!

**Comment by clouedoc** [comment]
Manually updating the extension (I disabled auto-updating) was what worked for me. I did not need to select a pre-release.
