### ISSUE TITLE
Reseting or disabling Shell Integration setting causes a configuration error

### ISSUE THREAD

**Issue by lorond** [microsoft/vscode-remote-release#6323]
- VSCode Version: 1.64.2
- Local OS Version: macOS 12.2 (21D49)
- Remote OS Version: Ubuntu 20.04.3 LTS
- Remote Extension/Connection Type: SSH
- Logs: _nothing related_

Steps to Reproduce:

1. Connect to Remote-SSH
2. Open settings
3. Enable "Terminal › Integrated: Enable Shell Integration" setting
![image](https://user-images.githubusercontent.com/1833263/153512017-dbc8fd93-a38e-42bc-9a26-40a7f3326ad1.png)

4. Disable or reset "Terminal › Integrated: Enable Shell Integration"
![image](https://user-images.githubusercontent.com/1833263/153512076-87c423a4-5bb2-4bde-b323-9e5d5b9c8b34.png)

Being invalid setting behaves just like being disabled.

When setting is enabled, settings.json contains line:
```"terminal.integrated.enableShellIntegration": true```

When setting was reset or disabled, that line disappears.

Manually adding ```"terminal.integrated.enableShellIntegration": false``` disables setting correctly.
![image](https://user-images.githubusercontent.com/1833263/153512932-648d48c3-9df2-4cbf-8810-08559be565f2.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by rzhao271** [comment]
I'm unable to reproduce the issue with a Windows setup.
In your case, when you remove the `"terminal.integrated.enableShellIntegration"` line from the Settings JSON file, does the setting not display properly in the Settings editor anymore? Is it possible that that setting key shows up more than once in the JSON file?

**Comment by lorond** [comment]
@rzhao271 no, it does not display properly  when `"terminal.integrated.enableShellIntegration"` line removed.

**Comment by rzhao271** [comment]
I confirmed this occurs with remote-containers as well, but not locally.

**Comment by rzhao271** [comment]
Hm, I'm now unable to reproduce the issue in the latest [Insiders](https://code.visualstudio.com/insiders/). Does the issue still occur for you there?

**Comment by lorond** [comment]
@rzhao271 seems fixed. Cannot reproduce anymore with latest version.
