### ISSUE TITLE
VScode server on insiders version, only working on preview release 

### ISSUE THREAD

**Issue by angelenriquep** [microsoft/vscode-remote-release#6327]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Getting the issue described here after in the last insiders update: https://github.com/microsoft/vscode-remote-release/issues/4307
2. Feel free to close the issue.
3. VScode insiders version: ![image](https://user-images.githubusercontent.com/56274826/153653421-02236d7a-daed-459d-912f-971da707df8b.png)

I have solved using ssh preview release. (just in case someone could find it helpful)

**Comment by lramos15** [comment]
Experienced this as well when connecting insiders to an Ubuntu 20.04 box. Deleting the server folder and killing on host had no real effect. Installing pre-release SSH seemed to work though. Not sure if there's any action to be taken though since pre-release extension seems to work fine.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/6328
