### ISSUE TITLE
VSCode still opens multiple tabs with the same url when using Remote SSH extension

### ISSUE THREAD

**Issue by neodon** [microsoft/vscode-remote-release#6334]
Based on #5930 which was closed without a resolution.

@philolypse provided a good, concise reproduction:

* Open few windows connected to the remote
* Open and run project that will automatically open browser tab with project url (like serve)
* VSCode will open as many tabs as we have windows opened in vscode

Another way to test it:
* open multiple windows of vscode
* connect all of them to the same remote
* run e.g. `xdg-open http://localhost` in remote terminal 
* the same amount of browser tabs will be opened as we have connected instances in vscode

Tested on: 
Client: macOS 12.0.1
Remote: Ubuntu 21.10
VSCode: 1.62.3

_Originally posted by @philolypse in https://github.com/microsoft/vscode-remote-release/issues/5930#issuecomment-978373999_

I'm also experiencing this with VSCode on Windows 10 Pro using the Remote SSH extension with a Ubuntu 20.04 VM.  If I have 7 VSCode windows open with remote projects, and I run a command that opens a URL, it opens 7 browser tabs with the same URL.

**Comment by roblourens** [comment]
It looks like it was linked to https://github.com/microsoft/vscode/issues/121926, that issue is still open

**Comment by misterjoshua** [comment]
I can also reproduce this issue when I have multiple VS Code windows open. The same happens for `xdg-open https://www.google.com` and with the AWS CLI (for `aws sso login`.) The latter with the AWS CLI is more problematic for me, as AWS invalidates the device access codes in the SSO login link after their first use, so only one of the browser tabs opens to a legitimate authorization link.
