### ISSUE TITLE
Connection to a Docker SSH context works directly on remote machine, but not from VS Code

### ISSUE THREAD

**Issue by tfenster** [microsoft/vscode-remote-release#6345]
Issue Type: <b>Bug</b>

My problem is that I use remote-ssh to connect to a Windows VM (on Azure), but am unable to connect from there to another Windows VM with a Docker ssh context. Here is what I do:

1. Setup a my Windows development VM (further referenced as dev-vm) with ssh key login
2. Connect to the dev-vm with VS Code -> works
3. Setup a different Windows VM as Docker host (further referenced as docker-host) and connect to it through a jumpbox with SSH
4. Confirm that I can connect from the dev-vm to the docker-host using ssh:
```
tfenster@sshhost c:\>ssh mgr1
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS [mgr1]:C:\Users\vm-administrator>
```
**--> works as expected**
5. Confirm that I can directly use the SSH connection for Docker from the dev-vm to the docker-host if I log in to the dev-vm using a standard Windows Terminal with PowerShell 7
```
PS C:\Users\tfenster> ssh devtfe-4ps
PowerShell 7.2.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\tfenster> docker --host ssh://mgr1 --debug version
time="2022-02-15T14:53:01Z" level=debug msg="commandconn: starting ssh with [-- mgr1 docker system dial-stdio]"
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:44:07 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Mirantis Container Runtime
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       e1bf5b9c13
  Built:            08/19/2021 18:53:20
  OS/Arch:          windows/amd64
  Experimental:     false
```
**--> works as expected**
6. Connect to the dev-vm using VS Code and try to use the terminal within that to connect to the docker-host
```
PowerShell 7.2.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\tfenster\AzDevOps\docker-automation\core> cd c:\
PS C:\> docker --host ssh://mgr1 version
PS C:\> docker --host ssh://mgr1 --debug version
time="2022-02-15T14:52:49Z" level=debug msg="commandconn: starting ssh with [-- mgr1 docker system dial-stdio]"
```
**--> hangs indefinitely**

I would expect that I should be able to connect from VS Code on the dev-vm to the docker-host in the same way as I am able to connect from am ssh session on the dev-vm to the docker-host. My actual issue is that I can't use that connection for debugging, but I wanted to simplify it by showing that even the direct connection doesn't work

Extension version: 0.70.0
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22543
Restricted Mode: No
Remote OS version: Windows_NT x64 10.0.20348

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (16.35GB free)|
|Process Argv|--crash-reporter-id 605726bb-7d0f-479e-8671-927715f3fb37|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: devtfe-4ps|
|OS|Windows_NT x64 10.0.20348|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (4 x 2793)|
|Memory (System)|16.00GB (13.55GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30438341
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
vsbas813:30436447
vscscmwlcmc:30436992
helixcf:30438276

```

</details>

**Comment by roblourens** [comment]
Sorry, I have no idea what the problem would be and why that docker command would work in a normal ssh terminal but not in VS Code. I don't know enough about docker to know what would be affecting it. Any idea @chrmarti?

**Comment by chrmarti** [comment]
Maybe compare the environment variables between the two (`dir env:`). There might be some `DOCKER` or `SSH` variable set that makes the two cases behave differently.

**Comment by tfenster** [comment]
I put the output from the working direct SSH connection into ssh.txt and the output from the failing vscode environment into vscode.txt. The differences are

```
diff ssh.txt vscode.txt
2a3
> _FIRST_ARG                     --start-server
4a6,7
> BROWSER                        c:\Users\tfenster\.vscode-server\bin\f80445acd5a3dadef24aa209168452a3d97cc326\bin\helpers\browser.cmd
> c28fc6f98a2c44abbbd89d6a3037d… AAAAAAICAgA=
7a11
> COLORTERM                      truecolor
13a18
> GIT_ASKPASS                    c:\Users\tfenster\.vscode-server\bin\f80445acd5a3dadef24aa209168452a3d97cc326\extensions\git\dist\askpass.sh
16a22
> LANG                           en_US.UTF-8
21c27
< Path                           c:\program files\powershell\7;C:\Program Files\PowerShell\7;c:\Users\tfenster\.vscode-s…
---
> Path                           C:\Program Files\PowerShell\7;c:\Users\tfenster\.vscode-server\bin\f80445acd5a3dadef24aa209168452a3d97cc326\bin\remote-cli;c:…
33c39,40
< PSModulePath                   C:\Users\tfenster\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\p…
---
> PSExecutionPolicyPreference    Unrestricted
> PSModulePath                   C:\Users\tfenster\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\7\Modules;C:\U…
34a42,43
> RESTVAR                         --start-server --host 127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port 0 --connection-token-file…
> ROOT_DIR                       C:\Users\tfenster\.vscode-server\bin\f80445acd5a3dadef24aa209168452a3d97cc326\bin\..
36,38c45,46
< SSH_CLIENT                     185.35.208.84 39939 22
< SSH_CONNECTION                 185.35.208.84 39939 10.0.0.4 22
< SSH_TTY                        windows-pty
---
> SSH_CLIENT                     185.35.208.84 40045 22
> SSH_CONNECTION                 185.35.208.84 40045 10.0.0.4 22
42c50,51
< TERM                           xterm-256color
---
> TERM_PROGRAM                   vscode
> TERM_PROGRAM_VERSION           1.64.2
47a57,61
> VSCODE_GIT_ASKPASS_EXTRA_ARGS
> VSCODE_GIT_ASKPASS_MAIN        c:\Users\tfenster\.vscode-server\bin\f80445acd5a3dadef24aa209168452a3d97cc326\extensions\git\dist\askpass-main.js
> VSCODE_GIT_ASKPASS_NODE        C:\Users\tfenster\.vscode-server\bin\f80445acd5a3dadef24aa209168452a3d97cc326\node.exe
> VSCODE_GIT_IPC_HANDLE          \\.\pipe\vscode-git-7f2b40ddfd-sock
> VSCODE_IPC_HOOK_CLI            \\.\pipe\vscode-ipc-fea8bdbc-f74c-401c-b993-dd62f034c93f-sock
```

The only thing that jumped out to me was `SSH_TTY` which was missing in the vscode env variables, but manually setting it unfortunately didn't help. @chrmarti do you see anything else worth trying?

**Comment by chrmarti** [comment]
Are there any `DOCKER` or `SSH` variables that are the same between the two?

**Comment by tfenster** [comment]
Nothing for `DOCKER`. For ssh there are `SSH_CLIENT` and `SSH_CONNECTION` which are identical except for the port

```
36,38c45,46
< SSH_CLIENT                     185.35.208.84 39939 22
< SSH_CONNECTION                 185.35.208.84 39939 10.0.0.4 22
< SSH_TTY                        windows-pty
---
> SSH_CLIENT                     185.35.208.84 40045 22
> SSH_CONNECTION                 185.35.208.84 40045 10.0.0.4 22
```

If you want to take a look for yourself, I have also attached both files:

[ssh.txt](https://github.com/microsoft/vscode-remote-release/files/8115900/ssh.txt)
[vscode.txt](https://github.com/microsoft/vscode-remote-release/files/8115901/vscode.txt)

**Comment by tfenster** [comment]
@chrmarti any other ideas?
@stefanscherer would you maybe have a thought why this could potentially go wrong?

**Comment by StefanScherer** [comment]
I don‘t have a clue.

**Comment by chrmarti** [comment]
@tfenster Not sure you mention this above: Does `ssh mgr1` work from the VS Code terminal when connected to the dev-vm using Remote-SSH? (If not: Try to debug it with `ssh -v mgr1`.)

**Comment by tfenster** [comment]
@chrmarti Yes, `ssh mgr1` works:

```
PS C:\Users\tfenster\AzDevOps\FSA> ssh mgr1
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS [mgr1]:C:\Users\vm-administrator> exit
Connection to mgr1 closed.
PS C:\Users\tfenster\AzDevOps\FSA> docker --host ssh://mgr1 --debug version
time="2022-03-07T18:55:23Z" level=debug msg="commandconn: starting ssh with [-- mgr1 docker system dial-stdio]"
```

After that it hangs indefinitely, so that still doesn't work

I have now also tried to start the ssh daemon in debug mode (ssh -D -ddd) and captured the output, but to me it seems identical, only the one that is called from vscode just gets stuck at the end

[vscode.txt](https://github.com/microsoft/vscode-remote-release/files/8201059/vscode.txt)
[direct.txt](https://github.com/microsoft/vscode-remote-release/files/8201062/direct.txt)

**Comment by tfenster** [comment]
I don't have the scenario anymore, so I can't say

**Comment by chrmarti** [comment]
Closing for now, let us know when this comes up again. Thanks.

**Comment by schickling** [comment]
I'm facing a similar situation where the when I manually `ssh` into my server, the `$SSH_TTY` env var is set properly but it's not available in the VSC terminal:

![image](https://github.com/microsoft/vscode-remote-release/assets/1567498/827d018a-4f98-4eb4-8f2e-b424b0ea2566)

**Comment by chrmarti** [comment]
`SSH_TTY` is only set when there is a tty for the first command run inside the ssh session.

@schickling Could you open a new issue if your problem persists? Thanks.
