### ISSUE TITLE
Allow multiple files under remote.SSH.configFile / Make remote explorer parse Include directive.

### ISSUE THREAD

**Issue by acalvino4** [microsoft/vscode-remote-release#6352]
## Background
The ssh config that VS Code remote uses to list possible options is configurable with the setting `remote.SSH.configFile`.

## Feature
This feature request is to allow that setting to reference multiple files.

Better yet, keep that setting pointing at a single file, but follow any `Include` directives in the file to find any additional remotes that the user's config loads when working with ssh. This is probably the preferable solution, since it makes VS Code's remote explorer simply pick up what the user's ssh config is configured to know about. In fact, if you look at it that way, this may even be considered a bug.

## Use Case
We have a company-wide ssh config file that engineers load through an include directive at the end of their main ssh config. We would like for the list of remotes shown in VS Code Remote tab to include both the company remote machines as listed in the company config, as well as any machines that are listed in an engineer's individual config.

**Comment by acalvino4** [comment]
I am not using any wildcard in the path. My path is of the form
`Include /Users/myname/.hidden_dir/config/ssh_config`

**Comment by tanhakabir** [comment]
Where in your config is the `Include`? We have a known issue where if `Include` is not above all entries, it isn't parsed properly https://github.com/microsoft/vscode-remote-release/issues/4339

**Comment by acalvino4** [comment]
aha, that is exactly the problem. I don't think I saw that issue since initially I was searching for 'allow multiple files remote.ss.configfile'.  Thanks for the very quick help - we can close this as duplicate.

I am definitely invested in seeing that issue fixed though - I had the Include at the end intentionally so that user configs would take precedence.
