### ISSUE TITLE
vscode in Windows does not show WSL TARGETS

### ISSUE THREAD

**Issue by eunchan** [microsoft/vscode-remote-release#6367]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: Windows 11 Pro 21H2 22000.434

Steps to Reproduce:

1. Setup WSL2 (Ubuntu)
2. Setup VSCode and create a workspace inside WSL2 (Ubuntu)
3. Create a recovery point
4. Roll back to the recovery point
5. Open VSCode

After following the steps, vscode in windows does not show WSL targets. I still am able to enter the WSL2 system with `wsl.exe` command. And `wsl.exe -l` shows valid WSL image `Ubuntu (Default)`

**Comment by aeschli** [comment]
`${HOME}/.vscode/extensions/ms-vscode-remote.remote-wsl-0.64.2` does not contain any runtime data or state.
If `wsl -l` shows the distro and `wsl -d Ubuntu` also works, the  I don't see a reason why the Remote-WSL extension cannot connect.

**Comment by eunchan** [comment]
the commands worked. Anyway, that's what happened. Now the workaround exists. I think we can close this?

**Comment by aeschli** [comment]
Ok, let's close it as it's probably a rare scenario. If others hit it too, I''m happy to reopen and I'll look closer into it.
