### ISSUE TITLE
Remote server log file has null bytes

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#637]
I got into a situation where the server's log file had thousands of null characters at the end, preventing it from being processed by grep. @kieferrm this is probably what you saw. 

My log file had the normal output at the end

```
> ==> Received a management connection
> EXTHOST: PROCESS EXITED
> 0
> null
```

followed by many null characters. No clue where they came from. Working around it by using the `-a` flag with grep.

**Comment by roblourens** [comment]
`$VSCH_DIR/node $VSCH_DIR/out/remoteExtensionHostAgent.js --port=0 &> $VSCH_LOGFILE < /dev/null &`

@kieferrm do you know what `< /dev/null` is doing here?

**Comment by kieferrm** [comment]
If I remember correctly, sending the process in the background from within the shell script didn't work without the stdin redirect.

**Comment by roblourens** [comment]
Not seeing this anymore, and the workaround is fine anyway
