### ISSUE TITLE
SSH Terminal with Windows 10

### ISSUE THREAD

**Issue by Hammad22222** [microsoft/vscode-remote-release#6373]
Hi,

Can a user use this on Windows 10 machines to access his linux machines? What are the limitations to it? How many sessions and ssh terminals?

**Comment by tanhakabir** [comment]
Hello! Yes you can use the Remote SSH extension to access linux machines. There's documentation here of which Linux machines are supported: https://code.visualstudio.com/docs/remote/linux. 

As fro limitations, we don’t set any limitations, besides one per user per version of VS Code locally. You can run as many sessions as you want until they run out of memory on the remote machine.
