### ISSUE TITLE
How to run a remote script before code starts?

### ISSUE THREAD

**Issue by juxeii** [microsoft/vscode-remote-release#6375]
We have a fairly complex environment on our remote machine. We need to run a script which sets it before we do anything in our workspace.
My workflow is
1) Start VSC on Windows 10
2) Connect via remote ssh extension to a remote host running linux

The connection is fine, but I need to run the above mentioned script such that all paths are set.
For example, I cannot call clang-format(via 'Format Document') to format a source file:

_/opt/llvm/x86_64/9.0.0.g920a/bin/clang-format: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/llvm/x86_64/9.0.0.g920a/bin/clang-format)_

This clearly shows that the environment is not set.
The command to get the environment is **source /var/set_gnb_env.sh**. I tried the following
1) Add it to ~/.bash_profile
2) Add it to ~/.bashrc
3) Add it to ~/.profile
4) Add it to .vscode-server/server-env-setup

Now the command is in all these locations, but still many programs and extension have the above problem of not seeing the correct GLIBCXX.
Where else can I add the source command?
Is there a possibility that vsc inherits from a shell which sourced the command and starts from there as a child process? And so all other programs would inherit the same env when open a new shell?

**Comment by tanhakabir** [comment]
Have you tried using RemoteCommand?

To use it you need to go into your settings and set `remote.SSH.useLocalServer: true` and `remote.SSH.enableRemoteCommand: true`. And then you can specify in your ssh config the script you want run first to set up the env variables.

**Comment by juxeii** [comment]
@tanhakabir 
Thx, I tried, but whatever command is used I get 
**_local-server-1> ssh child died, shutting down_**

**Comment by tanhakabir** [comment]
You need to use a non-terminating command that is intended to set up the environment of the shells you want to use. You can test if your command will work as expected with VS Code by using terminal/powershell to ssh into the machine and see if you still have an interactive session.

More details here: https://github.com/microsoft/vscode-remote-release/issues/6108#issuecomment-1022544055

**Comment by juxeii** [comment]
Ok, I added a trailing ;bash to RemoteComman. That works, but seems weird.
Thank you very much!
