### ISSUE TITLE
Managing remote extensions

### ISSUE THREAD

**Issue by wwangsa** [microsoft/vscode-remote-release#6376]
Ability to specify the location where the remote extensions are installed.  For local development, we could launch VS Code with `--extensions-dir` option. 

When developing remotely via SSH extensions, we need to install some extensions on the server and by default, the location is in the user home (`~/.vscode-server`) folder. Some system administrators follow the practice to keep the user's home folder size small in order to keep the server image size low as well. Over time, the _.vscode-server_ folder size grows and it could use up all the spaces quickly and it might eventually crash the server if the server wasn't configured properly.

**Comment by tanhakabir** [comment]
Does changing where the `.vscode-server` is downloaded help? There's a setting now called `remote.SSH.serverInstallPath` which allows you to specify a different path to save VS Code server in.

**Comment by wwangsa** [comment]
@tanhakabir What should I enter in the **Item** field? I'm assuming the new path would be entered in the **Value** field?

**Comment by wwangsa** [comment]
It works! I didn't know the feature was there. I've searched the settings, feature request and googled it but couldn't find anything. Thanks a lot @tanhakabir!
