### ISSUE TITLE
Any Solution for "If this is a jump server that requires a pty/interactive session, then this will not work."  now ?

### ISSUE THREAD

**Issue by DachuanZhao** [microsoft/vscode-remote-release#6382]
If this is a jump server that requires a pty/interactive session, then this will not work.

_Originally posted by @roblourens in https://github.com/microsoft/vscode-remote-release/issues/3035#issuecomment-722762242_

**Comment by eleanorjboyd** [comment]
Hello! Is this a feature request or a bug?

**Comment by joshspicer** [comment]
I imagine that this kind of scenario is not supported today.  For us to confirm, please create a new issue with your Remote - SSH logs + SSH config demonstrating a failed connection . Thanks!
