### ISSUE TITLE
Unable to install another version of platform-specific extension on the remote host

### ISSUE THREAD

**Issue by caucbianca** [microsoft/vscode-remote-release#6384]
When installing a platform-specific extension from the VS Code Marketplace on the remote host, it will work fine the first time, as it recognized that a different version of the extension should be installed.
However, it seems that this is not available anymore when using "Install another version...", causing the following error:
_Can't install ... extension because it is not compatible with the current version of Visual Studio Code (version ...)._
even if the requirement of the minimum VS Code version is fulfilled.

![unnamed](https://user-images.githubusercontent.com/17355584/155513230-b4eafc3d-6bf9-4fda-a04a-74195516e2cb.gif)

- **VSCode Version**:
Version: 1.64.0 (Universal)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:20:17.224Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0
- **Local OS Version**: Darwin arm64 20.6.0
- **Remote OS Version**: Ubuntu 18.04.5 LTS
- **Remote Extension/Connection Type**: SSH
- **Logs**:
```[12:25:57] Failed to install extension. ms-vscode.cpptools
[12:25:57] Incompatible: Can't install 'ms-vscode.cpptools' extension because it is not compatible with the current version of Visual Studio Code (version 1.64.0).
    at z.checkAndGetCompatibleVersion (/home/bianca.cauc/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9/out/vs/server/node/server.main.js:108:11880)
    at async z.installFromGallery (/home/bianca.cauc/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9/out/vs/server/node/server.main.js:108:2933) {
  code: 'Incompatible'
}
```
**Steps to Reproduce**:
1. Install Remote SSH extension
2. Run command ‘Remote-SSH: Connect current window to host…’
3. Install the latest version of the C/C++ extension (https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools)
4. Right click on the C/C++ extension in SSH Installed section and try to install a previous version

**Comment by caucbianca** [comment]
@sandy081 can you tell me please what is the other duplicate ticket?
Before I opened this one, I tried to see if there was anything on the subject, but I didn't find anything

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/142890

**Comment by sandy081** [comment]
the original bug was reopened
