### ISSUE TITLE
File opening via Protocol not working on WSL/remote

### ISSUE THREAD

**Issue by jonas-kell** [microsoft/vscode-remote-release#6393]
Issue Type: <b>Bug</b>

When trying to open a file via the protocol handler in wsl it shows `NO FOLDER OPENED`.

Opening files via the Protocol API is very useful for using debug-extensions in the browser for surveilling webapps developed on wsl.

Opening a Folder via command line works:
```cmd
code --remote wsl+Ubuntu-20.04 /var/www/html/
```
Opening a File (inside an open folder) via command line works (and doesn't reopen the window, just switches to the file):
```cmd
code --remote wsl+Ubuntu-20.04 /var/www/html/index.html
```
Opening a Folder via the Protocol API works (only reopens the window when folder is changed): (tested from chrome, explorer and Win+R execution menu)
```
vscode://vscode-remote/wsl+Ubuntu-20.04/var/www/html/
```
Opening a File via the Protocol API *DOESN'T* work (Always reopens the window and loses the folder. File also isn't opened): (tested from chrome, explorer and Win+R execution menu)
```
vscode://vscode-remote/wsl+Ubuntu-20.04/var/www/html/index.html
```

If I misunderstand the protocol api format, I would love to be pointed in the right direction, however I think this is a bug.

Extension version: 0.64.2
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (8.01GB free)|
|Process Argv|--crash-reporter-id 2d1a872f-a267-4f2b-944f-0692ad1ed7fd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4007)|
|Memory (System)|12.44GB (12.13GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30442554
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc008:30440022
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
vscaac:30438847
vsnot107:30443614

```

</details>

**Comment by bamurtaugh** [comment]
cc @aeschli thoughts?

**Comment by aeschli** [comment]
See https://github.com/microsoft/vscode/issues/108257#issuecomment-824323473
