### ISSUE TITLE
Handling for SSH wildcard in ssh config

### ISSUE THREAD

**Issue by Keno** [microsoft/vscode-remote-release#64]
My ssh config looks something like:
```
Host cluster? bob alice
     User me
     HostName %h.hostname.internal
```
which lets me connect to any of `cluster1`, `cluster2`, `bob` or `alice`. However, the Remote-SSH environment seems to pick up the entirety of `cluster? bob alice` as a single hostname and offers it as a hostname to connect to. I'd expect to either see each of the non-wildcard hostnames as a separate entry, or have it ignore the entire line.

**Comment by kieferrm** [comment]
@keno you can still connect to those hosts by using the explicit host name in the connect input box.

**Comment by Keno** [comment]
Yep, I'm aware and that works well. Just a bit confusing at first.

**Comment by caizixian** [comment]
I have a similar setup and I would imagine being able to select those machines from the left hand pane is useful.
It seems that the left hand pane only has hosts found in `.ssh/config`.
It would be nice if it shows `user@host` combinations that I've previously used. @kieferrm

**Comment by roblourens** [comment]
I will close this in favor of https://github.com/microsoft/vscode-remote-release/issues/186 for wildcard matching.
