### ISSUE TITLE
Using 'code some_file.extension' opens file in VSCode instance on the server, not on my machine!

### ISSUE THREAD

**Issue by hofingermarkus** [microsoft/vscode-remote-release#6400]
I am recently facing the problem that opening files from VSCodes built in shell using the comman ´code filename´ does not work any more in remote sessions (used to work fine).
While previously typing ´code filename´ during a SSH remote session would open the remote file in my local PCs VSCode instance, it seems as if now a new VSCode instance is opened on the Server instead!.
I am currently using VSCode to access my Offices workstation for home-office, so both PCs have a graphical front-end, and VSCode instances can sporadically be open on both of them.

- Local OS Version: Ubuntu 20.04
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

VSCode version details:
    Version: 1.64.2
    Commit: f80445acd5a3dadef24aa209168452a3d97cc326
    Date: 2022-02-09T22:02:29.527Z
    Electron: 13.5.2
    Chromium: 91.0.4472.164
    Node.js: 14.16.0
    V8: 9.1.269.39-electron.0
    OS: Linux x64 4.15.0-167-generic

**Comment by tanhakabir** [comment]
I believe a dup of https://github.com/microsoft/vscode-remote-release/issues/6289

I think this will be fixed in the latest release coming out this week
