### ISSUE TITLE
Display basename of local folder somewhere

### ISSUE THREAD

**Issue by davidpcaldwell** [microsoft/vscode-remote-release#6410]
When I use this extension to develop inside containers, I'm working on multiple projects that share essentially a common structure, which I think is a common workflow in Docker.

Unfortunately, this means I can't tell anywhere on the VSCode UI what project I'm working on without introspecting the file and folder structure. All of my containers map the source folder to `/app`, and all of my services are named `devbox`, and so the name `app` occurs as the folder name on the UI, and both in the file listing and in the green extension thing at the lower left the `devbox` name appears, and I can see the `git` *branch* I'm working on in the bottom bar (but when working on multiple projects, often *this* is the same for each project also).

I'm not a UX person but to me it seems intuitive to remove the (redundant) service name in the files listing, and instead display the local folder name there (so both the remote and local folder names are there, which makes sense to me in a files listing).

But I'm sure there are alternatives. I just want to be able to tell at a glance what project I'm working on.

**Comment by chrmarti** [comment]
You can add a `"name"` property to each project's devcontainer.json. The name value will then be shown in the green remote indicator in the lower left.

Does that help?

**Comment by davidpcaldwell** [comment]
> You can add a `"name"` property to each project's devcontainer.json. The name value will then be shown in the green remote indicator in the lower left.
> 
> Does that help?

Yes, I didn't notice that. That takes care of it, thank you!
