### ISSUE TITLE
Set EDITOR automatically for Remote SSH

### ISSUE THREAD

**Issue by davetapley** [microsoft/vscode-remote-release#6426]
I'm surprised this hasn't come up yet...

As mentioned in #643 you can set `export EDITOR='code --wait'` to get a nice interactive `git` flow (or in my case `crontab -e`) when using Remote SSH. Is there a reason this isn't injected automatically?

If someone is going to the trouble of using Remote SSH in VS Code (as opposed to just using `ssh` from a terminal outside VS Code), then I _presume_ they'd be happy that VS Code is the default editor (as opposed to e.g. `nano` in the terminal window)?

**Comment by RAnders00** [comment]
I wanted to share a possible solution for the meanwhile. Add this to your `~/.bashrc`, `~/.zshrc` etc:

```sh
if [ "$VSCODE_INJECTION" = "1" ]; then
    export EDITOR="code --wait"
fi
```

**Comment by joshspicer** [comment]
I believe @RAnders00 's workaround is the best solution, as it's straightforward and unopinionated.  I actually do think some folks like using their remote's default terminal editor alongside VS Code.  Please feel free to share your thoughts with me if you think strongly otherwise

**Comment by joshspicer** [comment]
I documented how to set this up in https://github.com/microsoft/vscode-docs/pull/7865
