### ISSUE TITLE
Provide a way to open the editor from the remote CLI

### ISSUE THREAD

**Issue by configurator** [microsoft/vscode-remote-release#643]
When I'm running VS Code locally, I use the env setting `EDITOR='code --wait'`, so I can edit files, or git interactive elements (e.g. commit message, rebase commands), using the VS editor. This works great!

When using the Remote-SSH extension (or other remotes), I'd like to be able to do the same.

It looks like the extension opens some channel for backward-communication. The ideal design would export a bash function that would send a command through that channel; something like the following environment variable would do the trick nicely:

    BASH_FUNC_code%%=() {
        local args=(--data-urlencode "pwd=$PWD")
        for arg in "$@"; do
            args+=(--data-urlencode "arg=$arg")
        done
        curl '<channel>/cli-hook' "${args[@]}"
    }

where `<channel>` is the port or socket open for communication back to the client. This would be part of the env exported to shells opened by that specific client, meaning the channel would be specific to the client in the case of multiple clients, and there wouldn't be a problem where we open a file for editing from one machine and it opens in a different one.

**Comment by aeschli** [comment]
When you open an integrated terminal in a remote window, you can already use `code -w file.txt`.
It's using a channel similar to what you described, but with a shell script that is located in the remote install and put on the PATH.
Is that what you suggested?
As you write, all this is client specific, and is only available to processes started out of the remote window (integrated terminal, debug sessions, tasks...).

**Comment by configurator** [comment]
What you describe is exactly what I want; however, when I try running `code -w file` or `code`, it fails because the script is not found in my PATH. As you can see in my screenshot below, I tried running both `code -w file` and just `code`, from within the integrated terminal connected to an SSH server.

I originally opened this issue because I had the env setting `EDITOR='code --wait'` by default, and it failed in remote connections, forcing me to change the setting.

```
configurator@dook:~$ code
bash: code: command not found
configurator@dook:~$ cat file
hello
configurator@dook:~$ code -w file
bash: code: command not found
configurator@dook:~$ 
```

![screenshot](https://user-images.githubusercontent.com/671365/59259434-7d558e80-8c42-11e9-8010-b7299d7e4dd3.png)

**Comment by aeschli** [comment]
On insiders use `code-insiders -w file`

**Comment by configurator** [comment]
D'oh. That works perfectly. Sorry, and thanks!

**Comment by garymm** [comment]
Where is the `code` script installed? I don't seem to have it on the remote machine.

**Comment by aeschli** [comment]
It's part of the server build (`.vscodeserver/bin/commitId/bin/code.sh|bat`), but that path is added to the PATH. To work, it requires another env variable (the name of the pipe), so it's only usable when in a process created by the remote window, as explained above.

**Comment by garymm** [comment]
Thanks. What version of the server was this added in?

**Comment by aeschli** [comment]
It's always been there
