### ISSUE TITLE
"Attach Visual Studio Code" command

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode-remote-release#6430]
I have actually two issues about this "Attach Visual Studio Code" command from the Containers view:

![image](https://user-images.githubusercontent.com/38782922/157539006-96585fa6-5dc3-4c79-9ce0-08185f76bf0d.png)

1. I use this menu item frequently and it would be great if it was available via the command bar. Unfortunately, there is no command like "Docker Containers: Attach Visual Studio Code" in the command bar. This also feels slightly inconsistent and thus harder to explore to me.
2. When I press the aforementioned menu item on a selected container, I am asked to enter the container again via a model dialog:

   ![image](https://user-images.githubusercontent.com/38782922/157539287-5911e10e-32aa-44b4-a838-6eb379de9560.png)

   This dialog is redundant and should not appear.

---

Implementational note:

I actually already tried to find these UI elements in the source code, but confusingly, both strings are not available in the source code of this repository (not even [anywhere on GitHub](https://cs.github.com/?scopeName=All+repos&scope=&q=%22Select+the+container+to+attach+VS+Code%22)). Apparently this item is contributed by the VS Code Remote Extension ([pointer](https://github.com/pmarsceill/setup/blob/a6f469054a339ff312807b63458c9ea251f45719/vscode/extensions/ms-vscode-remote.remote-containers-0.209.6/package.json#L329)). I'm still opening this issue under this repository because I am not sure how both extensions communicate and which one would be responsible for implementing the required changes. Thank you for your time!

**Comment by chrmarti** [comment]
You can use `Remote-Containers: Attach to Running Container...` from the command palette.

You need to select the container a second time due to an upstream issue tracked as https://github.com/microsoft/vscode-remote-release/issues/4405.

**Comment by LinqLover** [comment]
Thank you!
