### ISSUE TITLE
Containers: I can't manage to get my git ssh credentials to work in the container

### ISSUE THREAD

**Issue by francisr** [microsoft/vscode-remote-release#6432]
- VSCode Version: 1.64.2
- Local OS Version: Linux 5.4.0-65-generic 18.04.1-Ubuntu
- Remote OS Version: 
- Remote Extension/Connection Type: Docker
- Logs: 

Steps to Reproduce:

1. I have a windows machine on which VSCode is installed, with the `Remote - *` extensions.
2. With the `Remote - SSH` extension, I open a VSCode instance on a cloud VM.
3. In that instance, I have the `Docker` extension installed.
4. In the `Docker` extension, I right-click on my running container, and `Attach Visual Studio Code`.
5. VSCode installs runs the setup, and creates `~/.gitconfig`, which is the same as on my VM, but with this added :  

```
[credential]
        helper = "!f() { /root/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/node /tmp/vscode-remote-containers-27a67f1eb2639de5a0de32110e370b2771b3c475.js $*; }; f"
```
6. I made sure that my ssh-agent is running on my VM using the snippet from https://code.visualstudio.com/docs/remote/containers#_sharing-git-credentials-with-your-container, when I ssh into the VM I'm welcomed with `Agent pid 29059`.
7. My `~/.ssh/config` on the VM has `ForwardAgent yes` as the first line.
8. When I try to push or clone (or other git operations that connect to a remote) from within the container, it still asks for my password.

If works if I manually copy my keys into `/root/.ssh` in the container, but it would be good to avoid that.

**Comment by kinghat** [comment]
im also having this issue with remote dev container in a project im trying to setup so i can sync with the origin repo from within the container. same issue on manjaro from their repo and on kde neon via the snap install.

> git pull --tags origin dev-container
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

> 
> $ cat ~/.gitconfig 
> [user]
>         email = my-email@email.com
>         name = kinghat
> [credential]
>         helper = "!f() { /home/node/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/node /tmp/vscode-remote-containers-c510df8276dea7888fcaa04cdc34d732c8826cc2.js $*; }; f"

i have my agent holding the key and is verified:

> $ eval "$(ssh-agent -s)"
> Agent pid 201094
> $ ssh-add ~/.ssh/id_ed25519
> Identity added: /home/kinghat/.ssh/id_ed25519 (kinghat@kinghat-workstation)
> $ ssh-add -l 
> 256 SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX kinghat@kinghat-workstation (ED25519)

i have also tried to use my `~/.ssh/config` file but that doesnt work either:

> Host github.com
>      HostName github.com
>      User git
>      IdentityFile ~/.ssh/id_ed25519

vscode version:
> Version: 1.65.2
> Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
> Date: 2022-03-10T15:36:26.048Z
> Electron: 13.5.2
> Chromium: 91.0.4472.164
> Node.js: 14.16.0
> V8: 9.1.269.39-electron.0
> OS: Linux x64 5.15.25-1-MANJARO

dev container repo: https://github.com/kinghat/thelounge/tree/dev-container

**Comment by shadycuz** [comment]
I'm having a similar issue. I'm using windows but with the WSL backend. My dev container used to work fine with git, but then I didnt open it for a long time. Now when I open it, I'm unable to run any git commands like fetch, pull or push. 

```
jenkins@15f532f8052c:~/pipeline-library$ git fetch
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I also have a `~/.gitconfig` in my dev container with a credential helper. 

```
[credential]
        helper = "!f() { /var/jenkins_home/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/node /tmp/vscode-remote-containers-5867624ca2fee47b887b601b597c8ccc148993b8.js $*; }; f"
        ```

**Comment by bamurtaugh** [comment]
cc @lszomoru in case you have any ideas on the Git side of things.

**Comment by chrmarti** [comment]
We will connect to the ssh-agent on the SSH server (or in the WSL distro if you are using WSL) if there is one and otherwise use the local ssh-agent.

If you have a ssh-agent running on the SSH server: Is your key listed when you run `ssh-add -l` on the SSH server?

**Comment by francisr** [comment]
> We will connect to the ssh-agent on the SSH server (or in the WSL distro if you are using WSL) if there is one and otherwise use the local ssh-agent.
> 
> If you have a ssh-agent running on the SSH server: Is your key listed when you run `ssh-add -l` on the SSH server?

Yes:
```
❯ ssh-add -l                                                                                                                                       ─╯
4096 SHA256:XXXXX /home/remi/.ssh/id_rsa (RSA)
3072 SHA256:XXXXX (RSA)
```
(The XXX are just to hide the sha).

**Comment by chrmarti** [comment]
Could you append the log from when you open with the container? (`F1` > `Remote-Containers: Show Container Logs`)
