### ISSUE TITLE
Easy way to configure ssh-server temporary files location + method to clean it

### ISSUE THREAD

**Issue by crapitea** [microsoft/vscode-remote-release#6433]
At the present time the vscode-server when it's installed in Linux, it generates a number of temporary files into /tmp.
The problem arises when you are using the server on a machine that is not automatically cleaning the temporary directory (or uses a persistent partition for it). In this scenario, the /tmp directory will be filled in a relatively short time with a huge amount of hash files (ex: e6c600a8-2f54-4b07-b6ea-5bdac0d4c006) and you don't have any easy way to distinguish what are critical files needed for vscode or even have an option to remove files that are not used anymore.
Also, there should be a method to configure where these files should be placed.

**Comment by roblourens** [comment]
We will use `$XDG_RUNTIME_DIR` when that is set. If these files are coming from an extension, they may hardcode `/tmp` or do something else.

**Comment by crapitea** [comment]
> We will use $XDG_RUNTIME_DIR when that is set, is that in your environment or can you try that? If these files are coming from an extension, they may hardcode /tmp or do something else.

XGD is set and points to a different location. I've attached a log that shows what files were created after starting a ssh session (at 'Mar 16 10:39'): https://gist.github.com/crapitea/e92e2b81a79eee4232da4c6a21088e49

**Comment by roblourens** [comment]
Some of those at least are probably from the Pyright extension? You could file an issue on them. The others may also be from that extension, or from a different extension. The ones with ssh in the name are not from this extension, but could be from ssh itself or somewhere else.
