### ISSUE TITLE
Cloned repository running on WSL is not recognised by VSCode

### ISSUE THREAD

**Issue by moseleyi** [microsoft/vscode-remote-release#6434]
- VSCode Version: 1.65.1
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu
- Remote Extension/Connection Type: WSL (WSL version: 5.10.16.3-microsoft-standard-WSL2 Ubuntu)
- Logs:

Steps to Reproduce:

1. Ctrl+Shift+P -> Select New WSL Window
2. Open folder that was cloned from Github
3. Go to Source Control
4. Repository is not found. "Initialize Repository" button is shown

**Comment by bamurtaugh** [comment]
Could you share which repo this happens with? Is it all repos, or one specifically?

**Comment by lszomoru** [comment]
Also, could you please share the contents of the `Git output channel` which can be accessed through the `Git: Show Git Output` command from the command palette? Thank you!

**Comment by moseleyi** [comment]
This is the output
![image](https://user-images.githubusercontent.com/16131590/159496898-92585d11-5433-41be-a210-3a77694f8caa.png)

It actually happens to any repository that I open with WSL via VSCode

**Comment by lszomoru** [comment]
Are you opening a folder that is being stored on the Linux file system or the Windows file system (under `mnt/`)?
In case you are trying to open a folder under `mnt/`, are you able to reproduce the issue when you try to open the same folders in a normal VS Code window. If you open Developer Tools using the `Developer: Toggle Developer Tools` command, do you see any errors? Thanks!
