### ISSUE TITLE
SSH and terminal  do NOT respect user credendials entered in config file

### ISSUE THREAD

**Issue by mxdog** [microsoft/vscode-remote-release#6438]
Issue Type: <b>Bug</b>

I have been trying this for about 2 hours and it seems that VSCode is just doing what it wants : The remote machine has been set to allow root ssh access and works just fine  when ssh into it with other programs clients :

/user/myname/config
Host 192.168.0.1
user root
remotecommand cd /somedir

so what happens is I go to remote explorer select that connection.. window at the top of Code opens and asks for password myname@192.168.0.1 NOT  root@192.168.0.1  enter password and connect . Go down to terminal window and it opens as myname "whoami  returns  myname NOT root

So somewhere VS Code is doing its own thing and NOT what is in the actual config file . I have logged on with myname so i am guessing there is another history/config file that is being used instead of the one I set up.  or some a-hole dev made a decision to not allow root to do anything . in which case that is much worse ..... not a bug but outside dictatorial interference.

Other then being incredibly annoying this is serious security concern if the program does not respect the actual files/credentials  WANTED but defaults to some other hidden or lesser know configuration/history file. 

So in actuality there are 2 bugs here :
1. SSH - not logging on with the /user/myname/config
2. opening a  terminal with different credentials then what is in that file
    should note here that by happenstance both root and myname have the 
    same password or i think i would have gotten an actual login error 

(3). there is no  context or menu item to delete a connection or 
      configuration file

also as a suggestion it would be nice to be able to have that terminal/window/panes  detachable like in Visual Studio and resizable    

TO FIX : 
respect the config file setup and error out otherwise and NOT use history or whatever is going on here LINUX is NOT windows and we are not married to our user name that we log on with  like windows is .  when I want to log on jowblow@whatever i expect that name to be used and not my windows desktop name  

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.19.0-18-amd64

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.14
Angular2|joh|13.0.0
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
debugger-for-chrome|msj|4.13.0
JavaScriptSnippets|xab|1.8.0
vscode-perl|cfg|1.18.0
perl|ric|2.3.0
bash-debug|rog|0.3.9

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by roblourens** [comment]
If you have your ssh config file in a non-standard location (not `~/.ssh/config`) you will have to set the `remote.SSH.configFile` setting to tell vscode where it is.

If that's not what's going on here, you can share the Remote-SSH log in the output channel and it should give some hint.

There is no other hidden config - using the current user name is what ssh does by default when no other user name is specified (ie config file is not being used)

**Comment by zTonyZhao** [comment]
Same issue here.

The config file(C:\Users\<MYUSERNAME>\.ssh\config) looks like this:

```
Host <REMOTEIP>
  HostName <REMOTEIP>
  User root
```

Log Here:
```
[09:31:13.217] Log Level: 2
[09:31:13.218] remote-ssh@0.76.1
[09:31:13.219] win32 x64
[09:31:13.225] SSH Resolver called for "ssh-remote+<REMOTEIP>", attempt 1
[09:31:13.226] "remote.SSH.useLocalServer": false
[09:31:13.226] "remote.SSH.showLoginTerminal": false
[09:31:13.226] "remote.SSH.remotePlatform": {"<REMOTEIP>":"linux"}
[09:31:13.226] "remote.SSH.path": undefined
[09:31:13.226] "remote.SSH.configFile": undefined
[09:31:13.226] "remote.SSH.useFlock": true
[09:31:13.226] "remote.SSH.lockfilesInTmp": false
[09:31:13.227] "remote.SSH.localServerDownload": auto
[09:31:13.227] "remote.SSH.remoteServerListenOnSocket": false
[09:31:13.227] "remote.SSH.showLoginTerminal": false
[09:31:13.227] "remote.SSH.defaultExtensions": []
[09:31:13.227] "remote.SSH.loglevel": 2
[09:31:13.227] "remote.SSH.enableDynamicForwarding": true
[09:31:13.227] "remote.SSH.enableRemoteCommand": false
[09:31:13.227] "remote.SSH.serverPickPortsFromRange": {}
[09:31:13.227] "remote.SSH.serverInstallPath": {}
[09:31:13.240] SSH Resolver called for host: <REMOTEIP>
[09:31:13.240] Setting up SSH remote "<REMOTEIP>"
[09:31:13.258] Using commit id "c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1" and quality "stable" for server
[09:31:13.261] Install and start server if needed
[09:31:13.264] Checking ssh with "ssh -V"
[09:31:13.289] > OpenSSH_for_Windows_8.1p1
[09:31:13.290] > , LibreSSL 3.0.2

[09:31:13.293] Running script with connection command: ssh -T -D 56156 "<REMOTEIP>" bash
[09:31:13.295] Terminal shell path: C:\Windows\System32\cmd.exe
[09:31:13.504] > ]0;C:\Windows\System32\cmd.exe
[09:31:13.505] Got some output, clearing connection timeout
[09:31:14.108] > <WINDOWSUSERNAME>@<REMOTEIP>'s password: 
[09:31:14.111] Showing password prompt
[09:31:14.929] Password dialog canceled
[09:31:14.930] "install" terminal command canceled
[09:31:14.931] Resolver error: Error: Connecting was canceled
	at Function.Canceled (c:\Users\<WINDOWSUSERNAME>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:586237)
	at c:\Users\<WINDOWSUSERNAME>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:681160
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
[09:31:14.938] ------
```

(used <WINDOWSUSERNAME> and <REMOTEIP> to hide certain info)

After I changed the "Host" section in the config file to "root@\<REMOTEIP\>" it connected to the remote server with the correct username. It seems that the app is just ignoring the "User" section.

**Comment by mxdog** [comment]
@zTonyZhao  yeah exactly but I ended up clearing out  VSCodes saved data databases and starting from scratch basically after that the config file worked as intended ..wish i would have thought of changing the user name on the host line like you did .

@roblourens  there is saved data all over the place for instance on my linux box there is now a folder in /home/code directory with all of codes databases in it.

**using the current user name is what ssh does by default**  that is the problem I think, maybe .  but it doesn't explain how it still logged on with user name after selecting the config from the drop down menu . It should error, out not go on to the default. So my security concern again. 

like TonyZhao said it acts like it is just ignoring the user section and defaulting to the previous login since i restarted VSCode a few times during this process IT IS storing previous logins some where or it would not have had the previous **login name and address**  hence this issue ...not to mention that the problem went away when I blew away user data . after that it worked the first time...  so somewhere in the data base or state files the program is restoring previous and not respecting the actual file at least in this case . Again if it was NOT storing previous data it would be impossible for it to log on a non existent user/address with the info in the ssh config file.    

As above this is the file and was still ssh-logging in as mxdog@192.168.0.173  
# Read more about SSH config files: https://linux.die.net/man/5/ssh_config
Host 192.168.0.173
    HostName 192.168.0.173
    User root

I did run across a warning somewhere along the line after i got the login to work that bleah bleah bleah as root is discouraged or some such and had to hit continue  and then the trust popup to accept the folder/contents. maybe that was hidden when changing to root ?  But still used an impossible to know user name/address unless was stored  or like you said defaulted user name but address from config file .

**Comment by mxdog** [comment]
just for repeatability :
on remote box
1, set up a user with password and ssh access
2. set root with exact same password and ssh access ( yeah yeah we know bad practice ) 
3.  ssh into server with user  disconnect/close Code
4.  in Code again change config file from user user  to user root 
5.  connect to remote host see if root is used or previous user ( my case previous user)

**Comment by roblourens** [comment]
I tested but can't repro an issue. Some things to try

If you change `Host` to some name like "myRemote" instead of the IP address, does it work?

If you add

```
Host *
	LogLevel DEBUG3
```

to your ssh config file, do you see verbose logs from ssh in the Remote-SSH log? If not, it is not finding your ssh config file at all. If that is the case, try changing the setting `remote.SSH.configFile` to the path to your config file.
