### ISSUE TITLE
Remote ssh functionality will fail if I have set some launch scripts on Windows 10 cmd

### ISSUE THREAD

**Issue by BIAOXYZ** [microsoft/vscode-remote-release#644]
- VSCode Version: see below
- OS Version: see below

```
Version: 1.35.0 (user setup)
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:17:12.481Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

Steps to Reproduce:

1. Since I always work between different OS, I have set a launch script `lslldir.bat` on Window 10 with some alias setting:
```
doskey ls=dir
doskey ll=dir
```
**and register it to Windows Regedit so that it can be automatically run everytime I open a Windows command line.**

This is the difference before and after I set up this lauch script:

```
before：
----------------------------------------------------------------------------------------------------
Microsoft Windows [版本 10.0.17763.503]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\Users\BIAOXYZ>
----------------------------------------------------------------------------------------------------

after：
----------------------------------------------------------------------------------------------------
Microsoft Windows [版本 10.0.17763.503]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\Users\BIAOXYZ>doskey ls=dir

C:\Users\BIAOXYZ>doskey ll=dir

C:\Users\BIAOXYZ>
----------------------------------------------------------------------------------------------------
```

Then a new connection to a remote host functionality of vs code will never succeed. 

2. Remove this launch script, then the remote ssh functionality becomes normal.

Some additional words --> The reason is clear, but I am not 100% sure if it is suitable to call this phenomenon a "bug" (or I should create this issue in the feature category so that launch script will be supported as a future feature?).  

Does this issue occur when all extensions are disabled?: Yes/No
Not relevant.

**Comment by roblourens** [comment]
> Then a new connection to a remote host functionality of vs code will never succeed.

Can you try connecting with this script enabled, and share the output of the "Remote - SSH" output channel?

**Comment by BIAOXYZ** [comment]
@roblourens 
```
Can't connect to root@cloudsec2: unreachable or not Linux x86_64 (c:\Users\BIAOXYZ>doskey ls=dir)
```

**Comment by roblourens** [comment]
Thanks, but please find the log here:

![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Comment by BIAOXYZ** [comment]
```
remote-ssh@0.42.0
Picking SSH host
Selected root@cloudsec2
Confirming that root@cloudsec2 is a valid reachable host
Running type "C:\Users\BIAOXYZ\AppData\Local\Temp\vscode-linux-multi-line-command-cloudsec2.sh" | ssh  "root@cloudsec2" bash to confirm the host platform
> 
> c:\Users\BIAOXYZ>doskey ls=dir
> 
> 
> 
> 
"uname" terminal command done
root@cloudsec2: unreachable or not Linux x86_64. (c:\Users\BIAOXYZ>doskey ls=dir)
Picking SSH host
```

**Comment by roblourens** [comment]
It might work now with the nightly extension https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly

**Comment by BIAOXYZ** [comment]
OK, if so, this issue can be closed. Thank you~

**Comment by roblourens** [comment]
I think it will, would appreciate if you try it.

**Comment by BIAOXYZ** [comment]
Unfortunately, nightly version still won't work, with the same error message.

**Comment by roblourens** [comment]
You have to uninstall the stable version of the extension first (not disable)

**Comment by BIAOXYZ** [comment]
I have uninstalled all the remote development related extensions, and try again. But it seems that the remote ssh nightly version still cannot work. The symptom is: vs code is stuck at the ssh connection stage, the figure is listed below:
![image](https://user-images.githubusercontent.com/6740021/59578644-c0f54000-90fb-11e9-9515-db71d9e4f167.png)

From the picture above, you can see that there is not any message in the OUTPUT tab. When I change the tab to TERMINAL, there is only a one-line message:
```
c:\Users\BIAOXYZ>doskey ls=dir
```

**Comment by roblourens** [comment]
Sorry for bugging you so much but can you share the log from running it with nightly?

**Comment by BIAOXYZ** [comment]
Sure. Since there is no prompt message or other information in the OUTPUT tab, where are more detailed logs?

**Comment by roblourens** [comment]
Everything is in the output tab, pick "Remote - SSH" from the dropdown

**Comment by BIAOXYZ** [comment]
![image](https://user-images.githubusercontent.com/6740021/59741345-554ad880-929d-11e9-906f-4860613f1f5c.png)

The OUTPUT tab is indeed empty...

**Comment by roblourens** [comment]
That is the "Tasks" output, pick "Remote - SSH" from the dropdown.

**Comment by BIAOXYZ** [comment]
I still do not get you point (mainly about **which drop-down menu** I should pick), let me display my steps:

1.When I open vscode by double click, the main interface is listed here:
![image](https://user-images.githubusercontent.com/6740021/59906030-3d5c8b80-943a-11e9-94e9-22183f67c892.png)
**Note the red rectangle in the bottom left, then I will click this to start a remote ssh.** 

2.Then I will click `Remote-SSH: Connect to Host:......`
![image](https://user-images.githubusercontent.com/6740021/59906172-a217e600-943a-11e9-8d8f-07af64b08668.png)

3.Input `root@cloudsec2` and enter (cloudsec2 is the hostname of my linux vm).
![image](https://user-images.githubusercontent.com/6740021/59906338-13f02f80-943b-11e9-9a67-8ca4a575b8a5.png)

4.This time, it seems that vscode **does** return some error message (before, it is always stuck)
![image](https://user-images.githubusercontent.com/6740021/59906416-4ac64580-943b-11e9-8f9e-cd919439961b.png)

Hope it helps!

**Comment by roblourens** [comment]
In your other screenshot there is a dropdown that says "Tasks". Click that, select "Remote - SSH"

**Comment by BIAOXYZ** [comment]
I still do not see this tab... However, this issue can easily be reproduced (at least on my machine). So I will provide you with the method and the whole process:

1. Create the launch script, like `C:\Users\BIAOXYZ\mydata\lslldir.bat` with content:
```
doskey ls=dir
doskey ll=dir
```
2. Create a `addcmd.reg` file with the content listed below to add the launch script to Windows Registry.
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Command Processor]
"AutoRun"="%USERPROFILE%\\mydata\\lslldir.bat"
```
3. Double click `addcmd.reg` and then when you start your window command line, it will execute `doskey ls=dir` `doskey ll=dir` first. Then you can try to use remote ssh functionality and you will see the bug.

**Comment by roblourens** [comment]
Look at this screenshot: 

https://user-images.githubusercontent.com/6740021/59741345-554ad880-929d-11e9-906f-4860613f1f5c.png

You see the "Tasks" dropdown? Click that and select "Remote - SSH". I don't want to mess with my windows registry just to see the log.
