### ISSUE TITLE
Devcontainer setting `remote.localPortHost=allInterfaces` is not respected

### ISSUE THREAD

**Issue by steersbob** [microsoft/vscode-remote-release#6445]
- VSCode Version: 1.65.2
- Local OS Version: Ubuntu 20.04
- Remote OS Version: `mcr.microsoft.com/vscode/devcontainers/python:0-3-bullseye`
- Remote Extension/Connection Type: Docker
- Logs:

Steps to Reproduce:

1. Open VSCode with the `Remote - Containers` extension installed.
2. Select `Remote-Containers: Try a Development Container Sample` from the command palette.
3. Choose `Python`
4. Wait for VSCode to switch, load, and build
5. Set `Remote: Local Port Host` to the `allInterfaces` option in workspace settings.
6. Press F5 to start the application.
7. Switch to host.
8. Open `localhost:9000` on the host browser, and confirm it shows the example page.
9. Open `192.168.XXX.XXX:9000` (insert LAN IP here) on the host browser, and confirm it is unable to connect
10. Run `sudo netstat -tulpn | grep :9000` on the host, and confirm it shows `127.0.0.1:9000`

Expected behavior would be that by setting `remote.localPortHost=allInterfaces` in either workspace or user settings, the port would be opened as `0.0.0.0:9000`.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by pierreyves-lebrun** [comment]
I was able to replicate that issue

**Comment by abdalazizrashid** [comment]
Same here

**Comment by MartinsSmirnovs** [comment]
When is this going to be fixed? The issue forces us to manually publish specific ports from container, which is not as automatic (and crashes container startup if given port is already in use by another container) as VSCode's built in port forwarder which increments if given port is already in use.

**Comment by MartinsSmirnovs** [comment]
Yes, I still cannot successfully perform all steps provided in initial comment using VSCode Insiders + Dev Containers v0.264.0. I am using Windows as host though.

**Comment by steersbob** [comment]
I can also still reproduce the issue using AMD64 linux.

**Comment by alexr00** [comment]
Ok, thanks for reporting back. I had tested using a Windows host. I'll continue to investigate.

**Comment by steersbob** [comment]
Is this closure intentional, or a mildly overzealous bot?

**Comment by alexr00** [comment]
Just the bot!

**Comment by alexr00** [comment]
@makeable port forwarding is actually handled by VS Code, not by the Remote Containers or Remote WSL extension. I'm not 100% certain where the issue lies, but I can point you to the function I would start by looking at: 

https://github.com/microsoft/vscode/blob/1b4af18aa69083bf3cd545503e251c8bcc72a8c2/src/vs/platform/tunnel/node/tunnelService.ts#L85-L108

**Comment by alexr00** [comment]
> it erroneously reports as "localhost" in the port mapping.

In the Ports view we want to show something you can actually connect to in the Local Address column. `0.0.0.0:port-number` will not work in all browsers. Therefore, we show `localhost:port-number`. I could change it to use the machine's current IP address, but I expect that most users would prefer it stay as `localhost`.

**Comment by steersbob** [comment]
I hate to be the party pooper here, but I can still reproduce this issue on today's insider build.

.vscode/settings.json
```json
{
    "remote.localPortHost": "allInterfaces"
}
```

Netstat output for the Node example:

```
steersbob@blackbox:~/git$ sudo netstat -tulpn | grep :3000
tcp        0      0 127.0.0.1:3000          0.0.0.0:*               LISTEN      38996/code  
```

Version: 1.75.0-insider
Commit: 04b15ff231a2c3cfcdd90d90c16075a9c1e6da15
Date: 2023-01-09T05:29:32.376Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-57-generic
Sandboxed: Yes

**Comment by alexr00** [comment]
Interesting. I tried it out on Ubuntu and it's still looking good for me there:
```
alex@alex-Ubuntu-Lenovo-1:~$ sudo netstat -tulpn | grep :3000
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      7698/Code - Insider 
```

@steersbob can you confirm that you set the setting _before_ you forwarded the port?

**Comment by alexr00** [comment]
Looks like this is related to the setting being set in the workspace settings, not in the user settings.

**Comment by benstechlab** [comment]
I just confirmed this on M1 MacBook Pro, MacOS Monterey 12.6, 

Visual Studio Code Details:
Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:32:21.587Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

I changed the remote.localPortHost=allInterfaces on my user settings instead of workspace settings and it fixed my ability to access the devcontainer hosted app from my phone via local lan.

Now I just need to erase from my memory how many hours I just spent on this before finding this thread. 😅

**Comment by alexr00** [comment]
Fix will be available in the next insiders build. Thank you everyone in this thread for your persistence!
