### ISSUE TITLE
Failed to connect to the remote extension host server

### ISSUE THREAD

**Issue by delcata** [microsoft/vscode-remote-release#645]
Hello,
I have an issue when i try to open remote wsl on vscode and vscode insiders with all my distros (Ubuntu,Pengwin). after reinstalling my them ,vscode, vscode insiders , remote extension pack  and after downgrading version i have always the same problem, any help please?
I'm using windows 10 build 1903
vs insiders 1.36 
vs code 1.35
![issue_part1](https://user-images.githubusercontent.com/28787067/59245439-bffe7300-8c10-11e9-97b2-a445fe069cf8.png)

**Comment by aeschli** [comment]
@delcata  Do you get any additional information in the WSL terminal?

**Comment by delcata** [comment]
Yes the error code!
![issue_part2](https://user-images.githubusercontent.com/28787067/59253956-31e1b700-8c27-11e9-8b0e-912f88d6dc99.png)

**Comment by aeschli** [comment]
On error the WSL terminal should show automatically. If it doesn't, can you click on the 'Details' button that shows in the notification when the remote server is started (see screenshot below)

![image](https://user-images.githubusercontent.com/6461412/59255607-a4a45f80-8c32-11e9-92e5-ed4717398b39.png)

**Comment by delcata** [comment]
sure:
![issue_part2](https://user-images.githubusercontent.com/28787067/59256328-a159a580-8c2b-11e9-8fba-6244c33fa1ae.png)

**Comment by delcata** [comment]
Damn i know how to resolve that , i think it's my antivirus it changes my Adress ip to protect me and that interreput the connexion tunnel between my windows and the wsl
