### ISSUE TITLE
Log output not shown while the image is built

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#6452]
- Remote Containers>Try a Sample 

-> notice that during the image building phase there is no log shown in the terminal after clicking the 'show log' link in the progress notification.

![screencast log](https://user-images.githubusercontent.com/172399/158367338-5f337aef-c7b1-42c9-b905-c62827f709c8.gif)

**Comment by chrmarti** [comment]
Seeing this with shell integration enabled. Tracking as https://github.com/microsoft/vscode/issues/144729.
