### ISSUE TITLE
Remote SSH extension tests messed with my user settings

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-remote-release#646]
Tried using the Remote SSH extension this morning and saw this:

![image](https://user-images.githubusercontent.com/22350/59259069-61012400-8c39-11e9-9495-efb5340092b1.png)

I found this in my user settings: :confused: 

![image](https://user-images.githubusercontent.com/22350/59259127-7bd39880-8c39-11e9-81ea-627e8218970a.png)

I remembered I ran the SSH extension tests on my box last week. They left this setting behind. :bug:

**Comment by roblourens** [comment]
This actually was fixed 6 days ago in c71a254af18f249d5ab414e6f498081593dadf4f, you probably ran them just before that
