### ISSUE TITLE
unable to configure server on macOS 12.3 due to python dependency

### ISSUE THREAD

**Issue by jazaval** [microsoft/vscode-remote-release#6462]
- VSCode Version: Version: 1.66.0-insider
- Local OS Version: macOS 12.3 (21E230)
- Remote OS Version: macOS 12.3 (21E230)
- Remote Extension/Connection Type: SSH
- Logs:
```
*/bin/code-server-insiders: line 10: python: command not found
usage: dirname string [...]
usage: dirname string [...]
*/bin/code-server-insiders: line 13: /node: No such file or directory
```

Steps to Reproduce:

1. Attempt to start remote session with macOS 12.3 as server host. 

Per Apple's [release notes](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes) for macOS 12.3, the bundled version of `python` has been removed:

> Python 2.7 was removed from macOS in this update. Developers should use Python 3 or an alternative language instead. (39795874)

**Comment by jazaval** [comment]
Current workaround is to symlink python3 to `python` somewhere in the PATH.

**Comment by elgandoz** [comment]
Hey @jazaval , I'm having the exact same issue.

I tried add an alias to `python3` in `~/.zsrcr`, `~/.bashrc` and `~/.bash_profile` or add `/usr/local/opt/python/libexec/bin` to the PATH,  but none of those solutions worked (I'm connecting with the same user).

Symlink  worked.

**Comment by chrissnell-okta** [comment]
Installing python definitely does **not** fix it for me.  Same error persists.

**Comment by chrissnell-okta** [comment]
So, I was digging through the log and trying to figure out why the server wouldn't start after I already installed python (and node, just to be sure).  I ran the server command but without the redirection to a log file so that I could quickly see what was happening:

```  /Users/me/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown  --telemetry-level off --socket-path=/tmp/vscode-ssh-remote-server-sock-1647541863
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
[14:41:59] Extension host agent started.
[14:41:59] Error occurred in server
[14:41:59] Error: listen EADDRINUSE: address already in use /tmp/vscode-ssh-remote-server-sock-1647541863
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1463:5)
    at start (/Users/me/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/server-main.js:2:854)
    at Object.<anonymous> (/Users/me/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/server-main.js:12:28)
    at Module._compile (internal/modules/me/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/me/loader.js:1092:10)
    at Module.load (internal/modules/me/loader.js:928:32)
    at Function.Module._load (internal/modules/me/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '/tmp/vscode-ssh-remote-server-sock-1647541863',
  port: -1
}```

It appears that the server did start at some point and hung around and now new attempts were failing because the server couldn't bind to the port.  Just to "kill it with fire", I rebooted the remote machine and now the extension installs properly.

**Comment by kersson** [comment]
https://docs.brew.sh/Homebrew-and-Python#python-3y
>Unversioned symlinks for `python`, `python-config`, `pip` etc. are installed here:
>
>`$(brew --prefix)/opt/python/libexec/bin`

This workaround worked for me using `zsh`:
```sh
# Make sure you have python3 from brew
brew install python

# Add the unversioned symlinks to the PATH
echo export PATH=\"$(brew --prefix)/opt/python/libexec/bin:\$PATH\" >> ~/.zprofile
```

**Comment by andrespipe** [comment]
I've tried all the options posted here and no one is working for me.

I already created an alias, when I execute "python" command in terminal recognize it; however still getting same error message:

`*/bin/code-server-insiders: line 10: python: command not found
usage: dirname string [...]
usage: dirname string [...]
*/bin/code-server-insiders: line 13: /node: No such file or directory`

**Comment by AndyAyersMS** [comment]
> This workaround worked for me using `zsh`:

This worked for me too, but I needed to set it up in `~/.zshenv`

**Comment by bamurtaugh** [comment]
cc @tanhakabir @roblourens

**Comment by jazaval** [comment]
@roblourens 👋

**Comment by tanhakabir** [comment]
cc @deepak1556 @aeschli

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode-remote-release/issues/6442

**Comment by carlitorendon** [comment]
> > This workaround worked for me using `zsh`:
> 
> This worked for me too, but I needed to set it up in `~/.zshenv`
Thank you @AndyAyersMS that's exactly what did it for me. What an unfortunate situation. A few hours went onto a rabbit hole.
