### ISSUE TITLE
Unable to open 'chefignore': Unable to read file 'vscode-remote://ssh-remote+vmchefwstn01/home//chef-repo/cookbooks/test/chefignore' (Unknown (FileSystemError): An unknown error occurred. Please consult the log for more details.).

### ISSUE THREAD

**Issue by freelancer10** [microsoft/vscode-remote-release#6463]
in chef-repo under cookbooks
Just found, any cookbook downloaded from our Chef Infra server will show the error like below figure
Then I cannot open any files under test folder with remote SSH, but the files can be opened with Vim in command line.
![image](https://user-images.githubusercontent.com/8535865/158820207-05de8b62-cbe7-4a2a-9e9f-d96858261a24.png)

**Comment by freelancer10** [comment]
i want delete sensitive information, why the github is keeping the information that even in the changed the title? I don't want to expose my account

**Comment by roblourens** [comment]
@freelancer10 do you want this issue deleted?

**Comment by freelancer10** [comment]
> @freelancer10 do you want this issue deleted?

Can just delete the title change histroy? If cannot, then please delete the issue, thanks.
