### ISSUE TITLE
WSL with multiple guests - only able to connect to one guest

### ISSUE THREAD

**Issue by aorcl** [microsoft/vscode-remote-release#647]
- VSCode Version: 1.35.0
- Local OS Version: Windows 10 pro build 17763
- Remote OS Version: Ubuntu 18.4 LTS
- Remote Extension/Connection Type: WSL

In my WSL, I have two guest OSes (both of them Ubuntu 18.4). In the VScode's WSL extension, I see no option for selection of which of the guests the VSCode is connecting to, and I'm unable to connect to one of them.

Is this case (multiple WSL guests) just not supported yet or am I missing an option somewhere?

Thanks

**Comment by egamma** [comment]
duplicate for #118
