### ISSUE TITLE
Add option to allow running devcontainer inside a WSL2 Docker instance

### ISSUE THREAD

**Issue by AlexanderYW** [microsoft/vscode-remote-release#6470]
Since Docker Desktop changed their way of doing license, people have looking into running the docker instance alternative ways e.g. installing Docker inside an WSL Distro and exposing it to the host. Over all this works. But when wanting to open a .devcontainer in VS Code this will fail because of the Windows path since COMPOSE_CONVERT_WINDOWS_PATHS doesn't work without Docker Desktop.

So my suggestion is to add an option in "Remote - Containers" that translate the Windows Path to WSL mount path using the wslpath binaries.

**Comment by bamurtaugh** [comment]
Hi @AlexanderYW - it is currently possible to use Remote-Containers within Remote-WSL. Is this request different than [what we currently describe](https://code.visualstudio.com/remote/advancedcontainers/docker-options#_windows-windows-subsystem-for-linux-wsl)?

**Comment by chrmarti** [comment]
Note that if you are using a Windows folder, you need to enable "Execute in WSL":
<img width="923" alt="image" src="https://user-images.githubusercontent.com/9205389/159434951-1aa12b98-e53a-46a0-9543-9a64addfa955.png">

That will also do the path translation you mention. If that doesn't work, please append the log. (`F1` > `Remote-Containers: Show Container Log`)

**Comment by jankap** [comment]
> Note that if you are using a Windows folder, you need to enable "Execute in WSL": <img alt="image" width="923" src="https://user-images.githubusercontent.com/9205389/159434951-1aa12b98-e53a-46a0-9543-9a64addfa955.png">
> 
> That will also do the path translation you mention. If that doesn't work, please append the log. (`F1` > `Remote-Containers: Show Container Log`)

That is awesome; I've been fiddling around with TCP forwarding of the Docker daemon running in WSL but it's quite unsafe. This is *much* better, thanks!

**Comment by AlexanderYW** [comment]
I would love it to start the Daemon if it's not running, I experience mine is crashing sometimes
