### ISSUE TITLE
Clone Repository in Container Volume fails with "fatal: Unsupported SSL Backend 'schannel'"

### ISSUE THREAD

**Issue by J0F3** [microsoft/vscode-remote-release#6471]
- VSCode Version: 1.65.2
- Local OS Version: Windows 10 21H2
- Remote OS Version: Docker Desktop 4.6.0
- Remote Extension/Connection Type: Docker
- Logs: 

Steps to Reproduce:

1. Add the following config to local (Windows) .gitconfig (which is often need for Proxy Servers/Firewalls which to TLS Inspection):

```
[http]
  sslBackend = schannel
```

2. Run "Clone Repository in Container Volume"
3. When it comes to the point where the repository is cloned you get the following error:
![image](https://user-images.githubusercontent.com/12759579/159000383-c9c5ffec-06e7-43ae-b639-cc32a247039f.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

I need to set ` sslBackend = schannel` in my local git configuration otherwise git will not work correctly because of the corporate Firewall which does TLS Inspection. So this setting is needed that git respect the custom CA Certificates which are installed in the Windows Cert Store. 
My temporary workaround is to comment out the section in the local git configuration, then do the cloning into the the container volume and finally add it back. 
However I think it would be cool if remote container could somehow ignore such windows specific git settings so the do not make issues with dev containers.

Thanks!

Note: Of course I had initially also the problem that the vsc-volume-bootstrap image could not be built (because of the corporate firewall). But I saw that is already being discussed in https://github.com/microsoft/vscode-remote-release/issues/5052

**Comment by jankap** [comment]
Same problem here. Are all Windows git settings automatically used inside the container's git? Any way to avoid that?

**Comment by TheLonelyGhost** [comment]
Yes, it seems like the user-wide gitconfig (`--global`) is pulled in from the host machine (windows) and copied to the user-wide gitconfig in the container. A way I've found to get around _some_ of those issues is to move certain platform-specific settings to the system (`--system`) scoped gitconfig. Example:

```powershell
$> git config --global --unset http.sslbackend
$> git config --system http.sslbackend schannel
```

Then rebuild the container.

**Comment by chrmarti** [comment]
We now unset `http.sslbackend` in the temporary and the final container.
