### ISSUE TITLE
A simple way to re-open a repository cloned to a (named) container volume.

### ISSUE THREAD

**Issue by J0F3** [microsoft/vscode-remote-release#6473]
When a repository is cloned to a container volume or named container volume there should be a easy way to re-open it again after VS Code is closed. 
Currently, as far as I understand it, the only way to re-open the repository is through "File > Open Recent." 
But as far from that I do not get how one can re-open the repositions cloned to a container volume again. I think there should be a Command or something similar in VS Code where I can see the Repos cloned to the volume(s) and can select which one I like to re-open. 

I cloud also not found any thing about that in the documentation. 

May be I just missing something here or I just did misunderstood the whole idea of cloning to a container volume completely.

So I would appreciate all inputs or clarifications about the actual idea of the "clone to container volume" feature. 😊

Thx!

**Comment by chrmarti** [comment]
There should be an entry in the Remote-Explorer viewlet (select Containers at the top). Does that address your request?

**Comment by chrmarti** [comment]
Fixing the repository name in the Remote Explorer. Please open a new issue for the other problem if that still occurs. Thanks.

**Comment by TylerLeonhardt** [comment]
@J0F3 is this fixed for you in the prerelease version of the Dev Containers extension?

**Comment by chrmarti** [comment]
Verification:
- `F1` > `Dev Containers: Clone Repository in Container Volume`
- Enter a GitLab repo URL with 3 path segments, e.g.: https://gitlab.com/gitlab-org/editor-extensions/gitlab-ide-icons.git
- Verify in the Remote Explorer's tree view that the label makes sense.

Previously (from above):
![image](https://user-images.githubusercontent.com/12759579/160157685-1805db96-3625-437a-b31b-fb4bd2f40c06.png)

**Comment by J0F3** [comment]
@TylerLeonhardt @chrmarti Thanks for coming back to this! 
Yes, I can confirm it is fixed. The label makes much more sense now. Very cool! Thx! 😃
