### ISSUE TITLE
Attach vscode feature is not working and is struck at setting up.

### ISSUE THREAD

**Issue by vijaysamula** [microsoft/vscode-remote-release#6474]
https://user-images.githubusercontent.com/50096409/159038080-c6d5cdc5-9f23-45ad-b4bb-38f96ca9b610.mp4

I have a problem with attaching visual code to a remote container. You can see the video posted above. Whenever I try to attach the visual code, Vscode is struck at setting up the container. Please resolve it.

My system is UBUNTU 18.04
using latest vscode and docker.

**Comment by bamurtaugh** [comment]
Is there any difference if you try this experience in the latest VS Code Insiders?

Has this worked previously and it no longer works? Or has it never worked for you?

**Comment by vijaysamula** [comment]
Hi, @bamurtaugh  I did not try using vs code insiders. It worked pretty well last month.

**Comment by chrmarti** [comment]
@vijaysamula I can't play the video you uploaded, could retry the upload?

**Comment by vijaysamula** [comment]
https://user-images.githubusercontent.com/50096409/159430997-8cf04190-18e6-4f54-9a5e-bfab198c37d5.mp4

I am attaching here again.

**Comment by chrmarti** [comment]
Thanks, my video app didn't work, using a different one now.

What output do you get when you run the ssh command in a terminal? I would expect another password prompt at the time it hangs.
<img width="167" alt="image" src="https://user-images.githubusercontent.com/9205389/159652195-0bf883dd-80d5-4521-8038-ad915a5617e5.png">

Could you also try using a local ssh-agent and add your key to it with ssh-add? That will avoid the password prompts in VS Code.
