### ISSUE TITLE
Remote - WSL: error occurred with "Reveal in Explorer" when the login shell is pwsh

### ISSUE THREAD

**Issue by lewis-yeung** [microsoft/vscode-remote-release#6476]
- VSCode Version: 1.65.2
- Local OS Version: Windows_NT x64 10.0.22000
- Remote OS Version: Ubuntu-20.04 (WSL2)
- Remote Extension/Connection Type: WSL
- Logs:

```
Error: Command failed: C:\WINDOWS\System32\wsl.exe -d Ubuntu-20.04 sh -c wslpath -w "$VSCODE_WSL_PATH"
wslpath: \: No such file or directory
```

Steps to Reproduce:

1. Set the login shell in WSL to pwsh (PowerShell v7.2.1): `chsh -s /usr/bin/pwsh`.
2. Go Remote - WSL.
3. Execute "Reveal in Explorer" on a file, wherever it is located, on the host or the WSL filesystem, the error will occur.

I have tested the same op when the login shell was bash or zsh, it worked normally. From the error info in the logs above, it seems that the extension/server did not properly handle the case when the login shell was pwsh, and `$VSCODE_WSL_PATH` was not correctly evaluated so `wslpath` got an empty path.

**Comment by bamurtaugh** [comment]
@aeschli I'm able to repro this.

**Comment by lewis-yeung** [comment]
Still broken on **VSCode v1.66.0** with **Remote - WSL v0.66.0** & **PowerShell v7.2.2**.

**Comment by lewis-yeung** [comment]
@aeschli The `wslpath` works correctly in a regular pwsh shell. E.g., when I run `wslpath -w /mnt/c/Users/myname/dir1/dir2`, it outputs `C:\Users\myname\dir1\dir2`.

**Comment by aeschli** [comment]
In a Windows console, can you run
`set WSLENV=VSCODE_WSL_PATH/u`
`set VSCODE_WSL_PATH=/mnt/c/Users`
`wsl.exe -d Ubuntu-20.04 sh -c 'wslpath -w "$VSCODE_WSL_PATH"'`

If this doesn't work, run `wsl.exe -d Ubuntu-20.04 sh -c 'env'` to see if VSCODE_WSL_PATH is set.

**Comment by lewis-yeung** [comment]
@aeschli It shows `C:\Users`.

**Comment by aeschli** [comment]
Hm, interesting. That's what the extension internally does. 
You tried that with `pwsh` as default shell, right?

**Comment by lewis-yeung** [comment]
@aeschli Yes, I did.

**Comment by lewis-yeung** [comment]
@aeschli Can you repro this? It seems that `$VSCODE_WSL_PATH` is evaluated to an incorrect value in the extension.

**Comment by aeschli** [comment]
Found the issue.
When running a command in WSL, we need to use `--exec` to avoid that the current shell is invoked and causes escaping on the command line.

**Comment by aeschli** [comment]
@bamurtaugh Maybe you can verify as you already have the setup. It's in Remote-WSL@0.66.2.
Otherwise:
- install powershell in Linux: https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.2. I did it on Debian.

**Comment by lewis-yeung** [comment]
Bravo! It's confirmed fixed. Thanks for your work and patience. @aeschli

**Comment by aeschli** [comment]
Thanks @lewis-yeung for the help! Marking the issue as verified.
