### ISSUE TITLE
Module: command not found in vscode remote terminal

### ISSUE THREAD

**Issue by Betristor** [microsoft/vscode-remote-release#6478]
- VSCode Version: 1.65.2
- Local OS Version: Macos 12.3
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: SSH
- Logs: 

Steps to Reproduce:

1. add ```module load <xxx>```  in ```.bashrc``` file (module works fine in terminal when ssh with iterm2)
2. start a terminal in vscode

It looks like this. I don't know what thing went wrong. Through searching others' questions and answers, I still got stuck in this problem. I checked the env between ssh in terminal and vscode terminal, ```BASH_FUNC_switchml%%``` and ```BASH_FUNC__module_raw``` are missing in vscode terminal.
Does anyone encounter this before? Any suggestion will help.
![image](https://user-images.githubusercontent.com/55777837/159150039-aeebd203-5c4f-4664-b1ec-7548f9a10bf7.png)

Does this issue occur when you try this locally?: No, module is deployed on remote
Does this issue occur when you try this locally and all extensions are disabled?: No, same with above

**Comment by Tyriar** [comment]
Likely related to the remote server's environment being setup in a different way to when sshing into iterm2.

**Comment by Betristor** [comment]
Temporarily I set a testing to distinguish whether to load environment variables by module commands or manually, and it works. But still vscode terminal won't load environment variables like a normal terminal opened in iTerm2 or other ssh agents such as Terminus.

**Comment by aeschli** [comment]
Sorry, @tanhakabir I'm no expert on how terminals set up their environment, nor on how the Remote SSH extension works.

**Comment by Betristor** [comment]
There is a environment variable $TERM_PROGRAM which could help distinguish whether you're using vscode in ssh. With this conditioning ```if [ $TERM_PROGRAM ]```,  the .bashrc could judge the ssh way and choose appropriate environment variables to load. It's a temporary solution but it works. Hoping it will help others who are in the same situation with me.

**Comment by tanhakabir** [comment]
Sorry I haven't had a chance to investigate yet so I want to reopen this issue

**Comment by Betristor** [comment]
Ok, I'm not familiar with environment variables loading sequence, but there must be something wrong which caused the module command not being loaded. And that influenced everything after.

**Comment by phil-blain** [comment]
This still won't read your `~/.bashrc`, it will read `.profile` (or `~/.bash_login` if it exists, read http://manpages.ubuntu.com/manpages/focal/en/man1/bash.1.html#invocation for the gory details), just as when you log in to your system using SSH, but then you could source your `.bashrc` from `.profile` if you like.

**Comment by rabiafidan** [comment]
> This looks like you need your VSCode integrated terminal to launch a login shell instead of a non-login shell (which is the default behaviour).
> 
> The way I do this is using these settings in `~/.vsode-server/data/Machine/settings.json` on the remote machine:
> 
> ```js
> {
> // maybe other settings here...
>     "terminal.integrated.profiles.linux": {
> 
>         "bash (login)": {
>             "path": "bash",
>             "args": ["--login"]
>         },
>     "terminal.integrated.defaultProfile.linux": "bash (login)",
> // maybe other settings here, if not remove the comma on the previous line...
> }
> ```

Why is a non-login shell default? I am wondering if it would cause other problems to make it a login shell. What does a non-login shell read as the source instead of .bashrc?

**Comment by joel99** [comment]
This stackoverflow post suggests that maybe standard ssh calls `/etc/profile.d/modules.sh`, and vscode integrated terminal doesn't; sourcing `modules.sh` registers `module` as a valid command.
