### ISSUE TITLE
Evaluate variables in `workspaceFolder`

### ISSUE THREAD

**Issue by fnkr** [microsoft/vscode-remote-release#6480]
In order to keep the correct workspace name when mounting a subdirectory of the project in the container, I would like to do this:

```json
{
  "workspaceMount": "source=${localWorkspaceFolder}/subdir,target=/${localWorkspaceFolderBasename},type=bind",
  "workspaceFolder": "/${localWorkspaceFolderBasename}"
}
```

Unfortunately `workspaceFolder` is not a templated string right now. I have to specify the name statically, which is not as convenient:

```json
{
  "workspaceMount": "source=${localWorkspaceFolder}/subdir,target=/projectfoo,type=bind",
  "workspaceFolder": "/projectfoo"
}
```

**Comment by chrmarti** [comment]
Seems to work for me, could you append the log from when you try to open the folder in the dev container? (`F1` > `Remote-Containers: Show Container Log`)

**Comment by fnkr** [comment]
Found the problem: I was using the `Rebuild Container` option instead of closing the folder and opening it again. In that case, VSCode seems to apply the new `workspaceMount` but it still uses the old `workspaceFolder`. Not sure if this is intended or not - you can close the issue if you want.

**Comment by chrmarti** [comment]
That is a known limitation. It allows you to change to a different folder and when rebuilding/reloading stay in that folder.

Closing as this hasn't come up much as a problem so far. Thanks.
