### ISSUE TITLE
Can not select venv interpreter - vscode ssh (remote)

### ISSUE THREAD

**Issue by kuntiik** [microsoft/vscode-remote-release#6483]
- VSCode Version:
1.65.0
- Local OS Version:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
- Remote OS Version:
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
connect to a remote host over ssh
pyhon -m venv venv

bug: Virtual environment not visible in select interpreter
what I tried and did not work:
created .vscode/setting.json file with the following content:    "python.defaultInterpreterPath": "/mnt/PathToWorkspaceFolder/venv/bin/python"
tried the same without /mnt/

None of those worked for me. Search thru issues, but specifying the path in settings.json solved the problem for most of them.

**Comment by tanhakabir** [comment]
@karrtikr any ideas?

**Comment by karrtikr** [comment]
Couple of things to try:
- Try using `Python: Clear Internal extension cache` command.
- Is the workspace folder opened? If so try setting a relative path instead: `./venv/bin/python`.

If none of the solutions work please transfer it it `vscode-python` and we can have a look.
