### ISSUE TITLE
There is no function(h){return d} in the remote-ssh extension.js file 

### ISSUE THREAD

**Issue by aChang146** [microsoft/vscode-remote-release#6488]
@[ydcool](https://github.com/ydcool)> > If I change the ssh client from openssh to the git ssh located at `C:\\Progra~1\\Git\\usr\\bin\\ssh.exe` then everything will be fine.
> 
> Can you tell me how to replace it? Thank you

Step 1: Find the remote ssh extension file, in general at  `C:\Users\<YOUR_NAME>\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-<CURRENT_VERSION>\out\extension.js`.

Step 2: Open `extension.js`, search the function named `getSshCommand` , you may got about 3 matches, in front of the first one, you can find the function  `function h(){return d}`.

Step 3: Modify the function h , change the return value to your ssh client path, for example, 
```js
function h(){
  return "C:\\Progra~1\\Git\\usr\\bin\\ssh.exe"
}
```
The last step before this trick works, just save and relaunch vscode or reload window with `ctrl + shift + p`. 👻

@xluos

_Originally posted by @ydcool in https://github.com/microsoft/vscode-remote-release/issues/51#issuecomment-495089308_

Hi，thanks for your reply ,but i can't find the  `function h(){return d}`.Do you know another way to fix the issue? thank you very much !

**Comment by ydcool** [comment]
hi @aChang146  That comment was posted a long time ago, and the vscode has changed a lot, that solution maybe not works any more for recent releases, on the other hand, that bug in the original issue should already fixed since it has been closed. If you still have that issue, you should post your details at a new issue, not for that outdated `temporary` solution.

**Comment by ydcool** [comment]
This comment said the ext has already introduced a new setting for alternative ssh client, I'm not sure if you have tried this or not, or recent version of this extension still has this feature or not.

> https://github.com/microsoft/vscode-remote-release/issues/51#issuecomment-501806925

**Comment by bamurtaugh** [comment]
Thanks for the additional context @ydcool.

@aChang146 could you please clearly state what issue you are experiencing and what you'd like to achieve? Thank you!
