### ISSUE TITLE
Cannot attach to new folder after connecting to container once

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-remote-release#6490]
Testing #6482

1. Launch container like: `docker run -d alpine sh -c 'sleep 3600;'`
2. Attach via Docker view's "individual containers" context menu
3. Once attached, make a folder in the terminal and open it via "Open Folder"
4. Hangs 🐛
5. Launch new container like: `docker run -d alpine sh -c 'sleep 3600;'`
6. Try to attach:
7. 🐛 See that it's trying to open the folder from the other container: 
<img width="1694" alt="image" src="https://user-images.githubusercontent.com/8586769/159778687-ad1e0f6d-77e8-49c7-aeef-1f67945d82fc.png">
8. Pick "Open Workspace", select other folder, hangs 🐛

**Comment by sbatten** [comment]
I see the same on Windows

**Comment by chrmarti** [comment]
First and third hang are https://github.com/microsoft/vscode-remote-release/issues/6481. The second one is a known limitation.

Keeping open to verify it is fixed by https://github.com/microsoft/vscode-remote-release/issues/6481.

**Comment by chrmarti** [comment]
Fixed by https://github.com/microsoft/vscode-remote-release/issues/6481. Thanks.
