### ISSUE TITLE
"Always installed" features

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#6497]
Similar to ["always installed" extensions](https://code.visualstudio.com/docs/remote/containers#_always-installed-extensions), it could be useful to allow certain features to always be installed. This would help in cases where users always want certain tools or config (like a theme, default terminal) without needing to add it to a repo's dev container.

```
"remote.containers.defaultFeatures": [
    "feature1",
    "..."
]
```

cc @stuartleeks @Chuxel

**Comment by sarisia** [comment]
Is this documented somewhere? I found the new VSCode setting `dev.containers.defaultFeatures` but found neither docs or changelogs.

![image](https://user-images.githubusercontent.com/33576079/222621029-6b951ab8-3a6d-4804-a5b8-d0cbfaa2b60a.png)

This setting really helps me, thanks!

**Comment by vilgotf** [comment]
> Is this documented somewhere?

I've not found any documentation either, but the syntax seems to be the exact same as the `features` property of devcontainer.json. The following is valid

```json
  "dev.containers.defaultFeatures": {
    "ghcr.io/devcontainers/features/github-cli:1": {}
  },
```

**Comment by bamurtaugh** [comment]
Thanks! Adding to docs makes sense to me, opened https://github.com/microsoft/vscode-docs/pull/6641.
