### ISSUE TITLE
Notification to avoid mounts in containers

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#6498]
In Remote-WSL, we recommend users to use the Linux file system rather than a mount for improved performance.

Right now, if I:
- Open a project cloned locally
- Reopen in WSL

I'm prompted:

`This workspace is on the Windows file system (/mnt/). For best performance, we recommend moving the workspace to the Linux file system (~/home).` with a link to https://docs.microsoft.com/windows/wsl/setup/environment#file-storage.

If this project has a dev container, I receive a second prompt simultaneously:

`Folder contains a Dev Container configuration file. Reopen folder to develop in a container ([learn more](https://aka.ms/vscode-remote/docker)).`

@stuartleeks mentioned user confusion over mounts in Remote-Containers. Could we:
- Mention in the dev container prompt to clone in a volume and reopen?
- If users reopen in dev container without addressing the WSL mount prompt, prompt them again while using Remote-Containers to:
     - use a container volume, or 
     - use the Linux filesystem

cc @Chuxel

**Comment by stuartleeks** [comment]
While the performance difference between having the source on a Windows volume vs Linux volume is significant, I've seen other issues such as file notifications not firing reliably and problems with file attributes. These have often been a bigger issue than performance with having the source on a Windows volume mounted into the container. I wonder whether it would help to mention issues such as these in the toast (and linked doc page)?

**Comment by Chuxel** [comment]
Also just to clarify, I think we'd want to present this if you did a "open folder in container" on the Windows side (`C:\repos\foo`) as well as long as WSL is installed. The WSL engine is the default for Docker Desktop now and alternatives like Rancher Desktop also use it.

**Comment by chrmarti** [comment]
The two notifications are from different extensions. While a bit verbose, I suggest we include the message from Remote-WSL at the end of the Dev Containers notification:
![Image](https://github.com/microsoft/vscode-remote-release/assets/9205389/2cdb33ef-bbdc-4dde-899d-ec276101573a)

This avoids having to coordinate between the two extensions for now.
