### ISSUE TITLE
Opening Remote hangs w/ W10 server, Linux/Mac client, OpenSSH authorized_keys works

### ISSUE THREAD

**Issue by atalkingegg** [microsoft/vscode-remote-release#6499]
I see another recent VSCode 1.6.2 Opening Remote hangs issue, but this one seems a bit different.
I've got three systems, a 2014 MacBookPro HighSierra i7, a Raspberry Pi 4 8GB 64-bit Linux, and a Dell OptPlex i7 Windows 10 64-bit (the Mac, the Pi, and the PC).
All running VSCode 1.6.2 with the remote-ssh extension, an OpenSSH server, and have working cross-system authorized keys.
ssh-logins between the three login to remote shells immediately, no passwords required.
The Pi can remote-ssh debug C++/Python3 programs on the Mac and vise versa.
The PC can remote the same on Mac and Linux with no problems.
The first time trying to remote to the PC from the Mac, it was missing "minimist", which seemed to be fixed by installing node.JS and running "npm install -g minimist" on the PC. As far as I know, nodejs had never been installed on this PC before. Other people have hit this before, but was easy to fix. I'm guessing 100% of VSCode devs have this installed from the start. Is there a quick check to see if the nodejs environment is still functional?
Finally though, all attempts to remote from Mac or Linux to the PC end up "Failed to connect" "status code 1006", timing out after what looks like a successful login and remote vscode server launch. I'm including the terminal log from Pi->PC. The Mac->PC looks about the same.
Thanks in advance for any help! It would be nice to know if there's others debugging Windows apps from a Linux/Mac console, nearly all of the remote-ssh examples are happening the other way.

[term_log.txt](https://github.com/microsoft/vscode-remote-release/files/8346664/term_log.txt)

**Comment by atalkingegg** [comment]
BTW...
echo "echo hello" | ssh user@othersystem
works every which way. This doesn't look like an ssh issue.
"AllowTcpForwarding yes" is set on all the system's sshd_config files.

**Comment by atalkingegg** [comment]
"OpenSSH-server for Windows" Version
((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
7.7.2.3

Server Operating System Version
((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)
Windows 10 Pro

Python Version
((Get-Item (Get-Command py.exe).Source).VersionInfo.FileVersion)
3.9.12

Until today, I was running on MS-Store download of python 3.9.5, but discovered that for security reasons IT WILL NOT RUN under a service, which means for security reasons you can't run ANY PYTHON APPS OVER SSH! FOR REMOTE DEBUGGING ONLY USE PYTHON VERSIONS DOWNLOADED FROM PYTHON.ORG ON WINDOWS!

That said, while I can now run python programs on Windows 10 over an ssh shell, I still can't get VSCode on Linux/Mac to connect to debug services on Windows 10, even though ssh connects just fine, and now python code runs fine, and the remote debug service bits seem to be launched and waiting. Please let me know what other information I can provide to figure this out. Thanks!

**Comment by tanhakabir** [comment]
Would you be able to share a gif with us of what isn't working now?

**Comment by atalkingegg** [comment]
I'm not sure I understand the more info request; a picture of the error popup?

To summarize the problem: I click on Remote Explorer (on VSCode running on the Linux system), select the Windows 10 PC in SSH Targets that I want to debug a program on, it pops up a new window with the lower left corner stating "Opening Remote", it asks for the platform (Windows), I see the terminal that it has connected and has started up a remote process (will include a terminal dump), after a minute or so it errors out. "Could not fetch remote environment", and "Failed to connect to the remote extension host server (Error WebSocket close with status code 1006)". 
The text in the included term_log all happens in the terminal window within a second or so of the connection attempt.

[term_log.txt](https://github.com/microsoft/vscode-remote-release/files/8365182/term_log.txt)

If this doesn't cover what's needed, please let me know. Thanks for looking at this!

**Comment by atalkingegg** [comment]
One last note: this exact procedure works fine if it's Linux->Mac, Mac->Linux, Windows->Linux, or Windows->Mac. It only and always fails for Linux->Windows and Mac->Windows.

**Comment by tanhakabir** [comment]
Thanks for the clarification! Would you also be able to share your Remote SSH logs here? You can find them with this: https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues

**Comment by atalkingegg** [comment]
### No problem, not much there...
[17:19:36.033] Log Level: 2
[17:19:36.111] remote-ssh@0.76.1
[17:19:36.113] linux arm64
### and that's it!
