### ISSUE TITLE
Cannot download vscode server in China

### ISSUE THREAD

**Issue by sino1641** [microsoft/vscode-remote-release#6502]
- VSCode Version:1.66 insider
- Local OS Version:Win11
- Remote OS Version:Centos7
- Remote Extension/Connection Type: SSH
- Logs:
```shell
> 57f0aef94f38: running
> Acquiring lock on /root/.vscode-server-insiders/bin/616cad0638d0c6d436abcf42fb85a8e333b7d705/vscode-remote-lock.root.616cad0638d0c6d436abcf42fb85a8e333b7d705
> Found old VS Code install db0525ff4ba814780e901a5b9e399aaf596b9b20, attempting to clean up
> Install still has running processes, not deleting: db0525ff4ba814780e901a5b9e399aaf596b9b20
> Installing to /root/.vscode-server-insiders/bin/616cad0638d0c6d436abcf42fb85a8e333b7d705...
> 57f0aef94f38%%1%%
> Downloading with wget
[20:54:32.963] > wget download failed
> https://vscode.cdn.azure.cn/insider/616cad0638d0c6d436abcf42fb85a8e333b7d705/vscode-server-linux-x64.tar.gz?1: 2022-03-25 20:54:33 ERROR 404: The specified blob does not exist..
```
Steps to Reproduce:

1.Open VSCode.
2.Try to connect remote server via ssh in China.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by tanhakabir** [comment]
Hello! Would you be able to share your full logs as well?

**Comment by sino1641** [comment]
> Hello! Would you be able to share your full logs as well?

I can download this package using other VSCode CDNs and connect to remoter servers 
so it is just something wrong with the VSCode China CDN `vscode.cdn.azure.cn`. 
But obviously, I have no way to contact them but to report issue here.

**Comment by tanhakabir** [comment]
Which version of VS Code are you running? Could you try using the latest Insiders of VS Code?
