### ISSUE TITLE
Failed to create hard link

### ISSUE THREAD

**Issue by Mark531** [microsoft/vscode-remote-release#6505]
[logs.txt](https://github.com/microsoft/vscode-remote-release/files/8360858/logs.txt)

Does this issue occur when all extensions are disabled?: No
I need the SSH Remote extension to reproduce this bug.

- VS Code Version: 1.65.2
- OS Version: Windows 10

Steps to Reproduce:

1. Install SSH Remote Extension and try to connect to a SSH target
2. This error occurs:
ln: failed to create hard link '/home/admindev/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/vscode-remote-lock.admindev.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1'

I've tried to remove the mentioned file but it does not exist...
I deactivated the option useFlock, but it didn't solve the same issue.
Many people are complaining about this blocking bug on stackoverflow and it hasn't been corrected so far.

**Comment by tanhakabir** [comment]
Could you please share your Remote SSH logs? Instructions here: https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues

**Comment by Mark531** [comment]
Remote logs attached.

**Comment by tanhakabir** [comment]
Could you try using the setting `remote.SSH.lockfilesInTmp` as set to `true`?

**Comment by Mark531** [comment]
Awesome, it worked! I've been struggling with that issue for weeks... But the root cause should be addressed.

**Comment by Mark531** [comment]
I still didn't understand what the problem was. Every day when I started VS Code, I had this very error. So, I had to manually remove the lock file. But sometimes, the file didn't even exist, so I'm confused...

**Comment by tanhakabir** [comment]
What kind of remote machine are you using? Is your home directory using NFS/any other distributed filesystem?

**Comment by Mark531** [comment]
It is a Linux machine.

**Comment by tanhakabir** [comment]
Do you have more details about your machine? 

> Is your home directory using NFS/any other distributed filesystem?

Do you know if this is true?

**Comment by Mark531** [comment]
I don't know how to check that. It's a VM deployed on Azure.
