### ISSUE TITLE
Cannot remote into AWS Cloud9 from Windows machine

### ISSUE THREAD

**Issue by gideonsergei** [microsoft/vscode-remote-release#6508]
Repro:
1. On Win10 machine follow steps here: https://aws.amazon.com/blogs/architecture/field-notes-use-aws-cloud9-to-power-your-visual-studio-code-ide/

2. Download all the required scripts (AWS CLI, Systems Manger, etc)

3. Open VSC and select Cloud9 from Remote-SSH: Connect current window to host...

Result:
See errors CreateProcessW failed error:2 and The process tried to write to a nonexistent pipe

I've tried all the tips on web/StackOverflow to resolve this issue and none hae worked. Help!

**Comment by tanhakabir** [comment]
Hello! Would you be able to share your Remote SSH logs for when you try to connect? Here are the instructions to do so: https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues

**Comment by gideonsergei** [comment]
Hi of course! Please see attached or let me know where to post. There was no WSL log AFAIK.

Thank you!

**Comment by tanhakabir** [comment]
Seeing this error in your logs `posix_spawnp: No such file or directory`

Found these relevant results: https://newbedev.com/windows-10-ssh-proxycommand-posix-spawn-no-such-file-or-directory and https://github.com/PowerShell/Win32-OpenSSH/issues/1890

Do the steps in the first blog post help?
