### ISSUE TITLE
VSCode gets stuck on "Downloading with wget"

### ISSUE THREAD

**Issue by Moseby** [microsoft/vscode-remote-release#6511]
So I have a Linux VM on Hyper-V and it set up with SSH. I can access the VM via SSH on Powershell from my Windows 10 machine. The VM is on the same machine. 

But when I try to SSH into it via VSCode and ssh exension. It just asks for my password and after that it gets stuck on the first "Downloading with wget" and on the right VSCode says "Downloading vscoe server". I could leave it like that for hours. 

Any ideas how I can troubleshoot this further and fix this?

Edit: Pinging works from the Linux VM and I can also wget files from the terminal without probem. Can also SSH into it and wget files from there.

![forever](https://user-images.githubusercontent.com/29925219/160241475-38279d0b-c12e-451d-bd4e-00ca095c31e9.png)

**Comment by tanhakabir** [comment]
Hello! Could you also share your Remote SSH logs? https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues

**Comment by sliterok** [comment]
I have the same issue and there is no "Remote-SSH: Show Log" command in command palette... 
![image](https://user-images.githubusercontent.com/12751644/168421087-531c7f87-61e4-437c-8a2c-0da381ae3aea.png)

**Comment by tanhakabir** [comment]
Do you have the extension installed? I'm seeing the command just fine: 
<img width="880" alt="image" src="https://user-images.githubusercontent.com/12758612/168442330-84321627-2908-4ff8-8a2a-f276ddd9bd45.png">

> UPD: [this](https://stackoverflow.com/a/65081326/6167132) helped

So is the issue resolved for you?
