### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by HRagaa** [microsoft/vscode-remote-release#6512]
The install button is not working, kindly provide me with a way to download and install "Visual Studio Code Remote Containers Extension"

**Comment by tanhakabir** [comment]
Hello! Could you please share some more details of which installation button you're referring to and what you're seeing:?

**Comment by HRagaa** [comment]
No action/pop up appeared after pressing install button

**Comment by tanhakabir** [comment]
You should be able to see all the functions available by the Remote Containers extension by either clicking the Window Indicator in the bottom left:
![image](https://user-images.githubusercontent.com/12758612/161304458-03397198-f501-428b-a7cc-5885d2ef04f0.png)

Or searching in the command palette (Ctrl/Cmd + shift + P) and searching `Remote-Containers`

**Comment by chrmarti** [comment]
@HRagaa Could you post a screenshot of the entire window when the button is shown? I'm not sure which button this is.
