### ISSUE TITLE
Set label and update devcontainer action doesn't work

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#6514]
The "Set Label and Update devcontainer.json" action in the Ports view doesn't do anything.

This exception occurs when the tunnel, which is set as the context for the action, is serialized to be set to the extension host:

```
Exception has occurred: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Node'
    |     property 'next' -> object with constructor 'Node'
    --- property 'prev' closes the circle
  at JSON.stringify (<anonymous>)
    at stringify (vscode-file://vscode-app/d:/repos/Microsoft/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:65:21)
    at Function.serializeRequestArguments (vscode-file://vscode-app/d:/repos/Microsoft/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:666:23)
```

**Comment by rzhao271** [comment]
What are some verification steps for this issue? I tried using Codespaces, and the action still seems to do nothing other than focus the row in the ports view.

**Comment by alexr00** [comment]
To verify:
1. Connect to a Codespace or container.
2. Forward a port
3. Use the "Set label and update devcontainer.json" action on the port in the ports view
4. Verify that the label is changed in the ports view.
