### ISSUE TITLE
Remote extension disablement is broken

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-remote-release#652]
Disabling the Remote SSH extension, in order to have the Remote SSH Nightly extension running doesn't work 100%:

1. Install both Remote SSH and Remote SSH Nightly
2. Disable Remote SSH, in the extensions viewlet
3. Connect to a Raspberry Pi

This will successfully launch a new remote window and then fail connecting with the following output:

```
remote-ssh@0.42.0
SSH Resolver called for "ssh-remote+pi"
SSH Resolver called for host: pi
Setting up SSH remote "pi"
Using commit id "7bc29bf67c17608b11e23a8497c8f1de5a0922cf" and quality "insider" for server
Install and start server if needed
> Installing to /home/pi/.vscode-server-insiders/bin/7bc29bf67c17608b11e23a8497c8f1de5a0922cf...
> Downloading with wget
> WARNING: /home/pi/.vscode-server-insiders/bin/7bc29bf67c17608b11e23a8497c8f1de5a0922cf/out/remoteExtensionHostAgent.js doesn't exist. Download/untar may have failed.
> Printing the current remote environment...
> LC_ALL=en_US.UTF-8
> SSH_CONNECTION=10.8.0.3 55495 10.8.0.1 22
> LANG=en_GB.UTF-8
> XDG_SESSION_ID=c4
> USER=pi
> PWD=/home/pi
> HOME=/home/pi
> SSH_CLIENT=10.8.0.3 55495 22
> MAIL=/var/mail/pi
> SHELL=/bin/bash
> SHLVL=2
> VSCODE_AGENT_FOLDER=/home/pi/.vscode-server-insiders
> LOGNAME=pi
> XDG_RUNTIME_DIR=/run/user/1000
> PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
> _=/usr/bin/printenv
> OLDPWD=/home/pi/.vscode-server-insiders/bin/7bc29bf67c17608b11e23a8497c8f1de5a0922cf
> Starting server...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Server did not start successfully. Full server log:
> /home/pi/.vscode-server-insiders/bin/7bc29bf67c17608b11e23a8497c8f1de5a0922cf/server.sh: 12: /home/pi/.vscode-server-insiders/bin/7bc29bf67c17608b11e23a8497c8f1de5a0922cf/server.sh: /home/pi/.vscode-server-insiders/bin/7bc29bf67c17608b11e23a8497c8f1de5a0922cf/node: Exec format error
> bd64b7b0-c4ac-463f-bb77-9a3505f6ee7d====
"install" terminal command done
Received install output: bd64b7b0-c4ac-463f-bb77-9a3505f6ee7d====
Failed to parse remote port from server output: bd64b7b0-c4ac-463f-bb77-9a3505f6ee7d====
```

Also:

```
pi@raspberrypi:~/.vscode-server-insiders/bin/7bc29bf67c17608b11e23a8497c8f1de5a0922cf $ file node
node: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=42c88d3401728b722d7ea3e700cb81f90ec1cfb6, not stripped
```

This indicates that the extension downloaded the x64 bits, not the armhf ones.

This means the following:

- The nightly extension was the one running when testing for host compatibility, because that step succeeded. Only nightly should succeed in testing against an ARM host.
- The non-nightly extension was the one running and creating the _download agent_ script on the remote machine, since the nightly one would check for ARM and download the correct agent.

This whole setup works if the user uninstalls the non-nightly version. I can only conclude disablement is not working properly here.

cc @shanselman

**Comment by roblourens** [comment]
Yes, this is https://github.com/microsoft/vscode-remote-release/issues/431. This is why the readme for the nightly extension says to uninstall the stable extension first. The log also has the version of the extension which tells you that the stable version was running.

**Comment by roblourens** [comment]
Sorry for the trouble, it's not a good experience. I could actually work around this in the extension. The stable version can check whether the nightly version is installed, and if so, halt its activation.

**Comment by roblourens** [comment]
Actually I don't think I can work around it perfectly because there will still be conflicts between the duplicated commands, but I am adding an error dialog that will be appear when both extensions are present:

![image](https://user-images.githubusercontent.com/323878/59311583-f1059480-8c5e-11e9-97c0-2e6a486c1722.png)

Someone can dismiss it and continue if they know what they are doing but it will be very obvious at least.

**Comment by zz940522** [comment]
> Disabling the Remote SSH extension, in order to have the Remote SSH Nightly extension running doesn't work 100%:
> 
> 1. Install both Remote SSH and Remote SSH Nightly
> 2. Disable Remote SSH, in the extensions viewlet
> 3. Connect to a Raspberry Pi
> 
> This will successfully launch a new remote window and then fail connecting with the following output:
> 
> ```
> remote-ssh@0.42.0
> SSH Resolver called for "ssh-remote+pi"
> SSH Resolver called for host: pi
> Setting up SSH remote "pi"
> Using commit id "7bc29bf67c17608b11e23a8497c8f1de5a0922cf" and quality "insider" for server
> Install and start server if needed
> > Installing to /home/pi/.vscode-server-insiders/bin/7bc29bf67c17608b11e23a8497c8f1de5a0922cf...
> > Downloading with wget
> > WARNING: /home/pi/.vscode-server-insiders/bin/7bc29bf67c17608b11e23a8497c8f1de5a0922cf/out/remoteExtensionHostAgent.js doesn't exist. Download/untar may have failed.
> > Printing the current remote environment...
> > LC_ALL=en_US.UTF-8
> > SSH_CONNECTION=10.8.0.3 55495 10.8.0.1 22
> > LANG=en_GB.UTF-8
> > XDG_SESSION_ID=c4
> > USER=pi
> > PWD=/home/pi
> > HOME=/home/pi
> > SSH_CLIENT=10.8.0.3 55495 22
> > MAIL=/var/mail/pi
> > SHELL=/bin/bash
> > SHLVL=2
> > VSCODE_AGENT_FOLDER=/home/pi/.vscode-server-insiders
> > LOGNAME=pi
> > XDG_RUNTIME_DIR=/run/user/1000
> > PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
> > _=/usr/bin/printenv
> > OLDPWD=/home/pi/.vscode-server-insiders/bin/7bc29bf67c17608b11e23a8497c8f1de5a0922cf
> > Starting server...
> > Waiting for server log...
> > Waiting for server log...
> > Waiting for server log...
> >  
> > *
> > * Reminder: You may only use this software with Visual Studio family products,
> > * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> > *
> >  
> > Server did not start successfully. Full server log:
> > /home/pi/.vscode-server-insiders/bin/7bc29bf67c17608b11e23a8497c8f1de5a0922cf/server.sh: 12: /home/pi/.vscode-server-insiders/bin/7bc29bf67c17608b11e23a8497c8f1de5a0922cf/server.sh: /home/pi/.vscode-server-insiders/bin/7bc29bf67c17608b11e23a8497c8f1de5a0922cf/node: Exec format error
> > bd64b7b0-c4ac-463f-bb77-9a3505f6ee7d====
> "install" terminal command done
> Received install output: bd64b7b0-c4ac-463f-bb77-9a3505f6ee7d====
> Failed to parse remote port from server output: bd64b7b0-c4ac-463f-bb77-9a3505f6ee7d====
> ```
> 
> Also:
> 
> ```
> pi@raspberrypi:~/.vscode-server-insiders/bin/7bc29bf67c17608b11e23a8497c8f1de5a0922cf $ file node
> node: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=42c88d3401728b722d7ea3e700cb81f90ec1cfb6, not stripped
> ```
> 
> This indicates that the extension downloaded the x64 bits, not the armhf ones.
> 
> This means the following:
> 
> * The nightly extension was the one running when testing for host compatibility, because that step succeeded. Only nightly should succeed in testing against an ARM host.
> * The non-nightly extension was the one running and creating the _download agent_ script on the remote machine, since the nightly one would check for ARM and download the correct agent.
> 
> This whole setup works if the user uninstalls the non-nightly version. I can only conclude disablement is not working properly here.
> 
> cc @shanselman

how to fix the problem
