### ISSUE TITLE
Cannot connect to Docker container running on AWS EC2 VM

### ISSUE THREAD

**Issue by dumbledad** [microsoft/vscode-remote-release#6523]
I cannot connect to a Docker container running on a remote VM (an AWS EC2 VM).

I have followed the steps in the [Connect to remote Docker over SSH](https://code.visualstudio.com/docs/containers/ssh) documentation and the additional [troubleshooting steps](https://github.com/microsoft/vscode-docker/wiki/Troubleshooting#the-extension-does-not-find-docker-on-a-remote-machine-failed-to-connect-is-docker-installed-and-running-error):

- I have a local Docker context
- Using the local Docker context I can run `docker ps` which lists all the containers running on the VM
- I have connected to the VM in VSCode over SSH and made sure that the Docker extension is installed on the VM

But in the container list in the VSCode Docker extension I get the error:
> Failed to connect. Is Docker running?  
> Error: Request timed out.  

I have tried in VSCode Version: 1.65.2 (Universal) and VSCode-insiders Version: 1.66.0-insider with Docker extension v.1.20.0 on an M1 Mac.

The only diagnostic output I can find is the Docker extension's output terminal, which just reports: `The Docker extension will try to connect to 'ssh://ubuntu@ec2-xxx-xxx-xxx-xxx.compute-1.amazonaws.com', via context 'ec2-context'.` I have verified at the local terminal that this SSH connection should succeed.

How might I diagnose what it going wrong?

**Comment by chrmarti** [comment]
@dumbledad Maybe to clarify: If the Docker extension is installed on the VM, it will access the Docker daemon directly on the VM, independently of the Docker context you set locally.

When you are connected to the VM using Remote-SSH, what do you get for `docker ps` in VS Code's integrated terminal (which runs a shell on the VM in this case)?

Could you install the Remote-Containers extension and check what the Remote-Explorer viewlet shows for "Containers" (switch to Containers at the top of the viewlet)?

**Comment by bwateratmsft** [comment]
@chrmarti I think @dumbledad is aiming to do Remote - SSH to connect to the VM, and then use Remote - Containers to connect to the container running on that VM. Is that possible?

**Comment by chrmarti** [comment]
@bwateratmsft Yes: When you are connected to an SSH server using Remote-SSH, Remote-Containers will use Docker on the SSH server and you can use the "Reopen in Container" command on the folder of the Remote-SSH session/window.

**Comment by dumbledad** [comment]
Sorry @chrmarti I cannot see how to do that, I'll do some digging.

**Comment by chrmarti** [comment]
@dumbledad There is documentation on this here: https://code.visualstudio.com/docs/remote/containers#_open-a-folder-on-a-remote-ssh-host-in-a-container
