### ISSUE TITLE
vscode; remote; got bad result from install script

### ISSUE THREAD

**Issue by gudy123** [microsoft/vscode-remote-release#6527]
I met the same issue. I tried the methods suggested in this [issue](https://github.com/microsoft/vscode-remote-release/issues/2805) and reinstalling VS code, but neither of them works for me. Finally, I got the solution mentioned [here](https://issueexplorer.com/issue/microsoft/vscode-remote-release/5693), which works for me. My solution is shared here as a reference:
- I found my cmd.exe crashed (it would just pop up and close immediately), which may be the cause of my issue.
- I change the registry values `Autorun`  in `HKEY_CURRENT_USER\Software\Microsoft\Command Processor` from `if exists` to a blank (as this [link](https://superuser.com/questions/1493887/what-is-the-default-registry-value-for-command-processors-autorun) suggests).
- my cmd.exe works fine and Remote SSH works again.

_Originally posted by @ZhangGe6 in https://github.com/microsoft/vscode-remote-release/issues/5803#issuecomment-967792530_

**Comment by gudy123** [comment]
thank u very much.
After I tried almost every ways I can do, in many days continuously.
Only your methods take effect!!!

**Comment by tanhakabir** [comment]
Thanks for sharing the cmd.exe fix! If it's okay I'll close this issue?
