### ISSUE TITLE
Shell server failed

### ISSUE THREAD

**Issue by Janatbek** [microsoft/vscode-remote-release#6528]
Issue Type: <b>Bug</b>

cannot connect to running docker containers. 

Shell server failed: Error: spawn C:\Users\jsharsheyev\AppData\Local\Programs\Microsoft VS Code\ssh ENOENT
	at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
	at onErrorNT (node:internal/child_process:477:16)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)

Extension version: 0.209.5
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Connection to 'SSH' could not be established  No remote extension installed to resolve ssh-remote.
Remote OS version: Linux x64 4.19.0-20-cloud-amd64
Connection to 'SSH' could not be established  No remote extension installed to resolve ssh-remote.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (18.34GB free)|
|Process Argv|--crash-reporter-id 07a7b0d5-e999-48bd-86e3-d14bb6877215|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH' could not be established  No remote extension installed to resolve ssh-remote.

|Item|Value|
|---|---|
|Remote|SSH: some numbers|
|OS|Linux x64 4.19.0-20-cloud-amd64|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (2 x 2199)|
|Memory (System)|7.30GB (3.44GB free)|
|VM|0%|

Connection to 'SSH' could not be established  No remote extension installed to resolve ssh-remote.
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
testflightcf:30433671
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvid2:30447481
pynewfile477:30463512

```

</details>

**Comment by chrmarti** [comment]
Could you update the Remote-Containers extension to the latest version (currently 0.231.1) and retry?

**Comment by Janatbek** [comment]
found an issue. 
the OpenSSH windows feature has to be installed on machine: 
https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse

now all my containers show up and I can connect to them.
