### ISSUE TITLE
Failed to list disabled extensions on a broken remote window

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-remote-release#653]
Issue https://github.com/microsoft/vscode-remote-release/issues/652 caused a broken SSH window. From there I can't see my disabled extensions any more:

<img width="1440" alt="Screenshot 2019-06-11 at 19 25 43" src="https://user-images.githubusercontent.com/22350/59293086-c3304800-8c7e-11e9-8eac-4bdc3c697acf.png">

**Comment by sandy081** [comment]
Disabled extensions view is a mix of both remote and local extensions. Hence it cannot be shown when remote server is down. 

Local extensions are shown when grouped by server in Installed Extensions view. There all local extensions can be managed.

**Comment by joaomoreno** [comment]
@sandy081 We should probably change the UI then. I won't be the last thinking that the red error sign and the "Error while loading extensions. Error" viewlet message are purposeful design decisions.

**Comment by sandy081** [comment]
I do not see this error in the view but I see never ending progress. I will see if the error appears and show a proper message.

**Comment by sandy081** [comment]
As said I am not seeing this error and instead a long progress and we show the disconnected message in the remote location in the status bar. I do not think there will be any action will be taken. Hence closing this.
