### ISSUE TITLE
ssh domain connection

### ISSUE THREAD

**Issue by merriaux** [microsoft/vscode-remote-release#6535]
Is there a connect on a ssh server identify by domain ?
I use a command like that in a terminal : ssh -t -l username@domain 10.1.4.15
But in the remote ssh vscode, I was not able to find a way to connect it. Is it exist or need development ?

thanks
Pierre

**Comment by tanhakabir** [comment]
You can either add your host to your SSH Configuration file or use the `Add Host` command which will take in your connection command and add your host to your SSH Config file
