### ISSUE TITLE
Not able to attach VSCode to Docker Container

### ISSUE THREAD

**Issue by mrpositron** [microsoft/vscode-remote-release#6542]
My Docker Container works fine. I can connect to it via shell. However, it is always problematic to attach VScode to it. Sometimes I can attach it. However, most of the time it fails. Now I am receiving the following problem:

Docker returned an error.
Make sure the Docker daemon is running.

Console returns the following:
![Screen Shot 2022-04-01 at 2 34 28 PM](https://user-images.githubusercontent.com/42044624/161201566-937c3ff6-a343-498c-be26-a3c47156f11c.png)

- VSCode Version: Version: 1.66.0 (Universal)
- Local OS Version: macOS Monterey. Version 12.2.1
- Remote OS Version: Ubuntu 20.04.2
- Remote Extension/Connection Type: SSH and Docker
- Logs:
![image](https://user-images.githubusercontent.com/42044624/161200398-c615ef47-4d22-4c85-88a1-3f1b9c90a345.png)

Steps to Reproduce:

1. Start a Docker Container on a remote host
2. Attach VSCode to a Docker Container

**Comment by mrpositron** [comment]
Reconnecting to remote server, and restarting docker helped me. Do anyone know why this is happening, and how I can solve it without restarting?

**Comment by chrmarti** [comment]
Could you append the full log? (`F1` > `Remote-Containers: Show Container Log`)

**Comment by chrmarti** [comment]
Also check if it is fixed in Remote-Containers v0.231.2 or v0.232.2-pre-release.
