### ISSUE TITLE
It's impossible to execute a PowerShell script as a initialize command on WSL2

### ISSUE THREAD

**Issue by filipwski** [microsoft/vscode-remote-release#6544]
**Specification:**
- VSCode Version: **1.65.1**
- Local OS Version: **Windows 21H2 (22000.556)** / **Ubuntu 20.04 LTS (WSL2)**
- Remote Extension/Connection Type: **Docker**

Does this issue occur when you try this locally?: **Yes**
Does this issue occur when you try this locally and all extensions are disabled?: **No**

**Steps to Reproduce:**
1. When using WSL2 pass any PowerShell command as _initializeCommand_ in the _devcontainer.json_ file (see description bellow).
2. Run the container building process.

**Description:**

I'm working on a Windows machine with WSL2 enabled and I'm using a complex configuration to build a containerized Linux environment basing on the extension. The project I'm working on requires to use an internal company certificate. To fully automatize the building process, the certificate should be exported from the Windows store using a PowerShell script.

The script is passed as `initializeCommand` in the _devcontainer.json_ file like this:
```json
"initializeCommand": "powershell.exe <pathToTheScript>.ps1"
```

The mechanism had been working correctly until the version from March 30 (`0.231.0`) was released. Now, the building process freezes without any error message when it's executing the _initializeCommand_. It happens also when trying to execute any PowerShell command in this way. When the script (or any PS command) is executed manually in the Ubuntu terminal it works fine.

I managed to workaround the problem by installing the `0.224.3` version. The problem occurs first when using the both newer ones.
![image](https://user-images.githubusercontent.com/25831273/161250170-3b337e0d-6f24-4607-9876-d5a1cbd71ba3.png)

**Comment by chrmarti** [comment]
Could you retry with Remote-Containers 0.231.3? That has a fix for `initializeCommand` to again show in a separate terminal and accept keyboard input (in case that is needed).

**Comment by filipwski** [comment]
It seems this change fixed the problem - the script is executed as expected. Thanks!
