### ISSUE TITLE
Changelog link to release notes

### ISSUE THREAD

**Issue by pmCrawler** [microsoft/vscode-remote-release#6546]
The link to release notes under "Changelog" needs to be updated. It's still pointing to the ".../master/..." branch.

Old link:  https://github.com/microsoft/vscode-docs/tree/master/remote-release-notes

New link:  https://github.com/microsoft/vscode-docs/tree/main/remote-release-notes

**Comment by pmCrawler** [comment]
WSL

**Comment by sandy081** [comment]
It is still pointing to wrong link

<img width="463" alt="image" src="https://user-images.githubusercontent.com/10746682/165509962-89730cb3-3272-4fc5-a4d1-2e9aa3e8bc45.png">

**Comment by tanhakabir** [comment]
cc @aeschli was there anything else I was supposed to do in addition to https://github.com/microsoft/vscode-remote-wsl/commit/84610b9dbea3277811fd2637841a87211b94cc03?

**Comment by aeschli** [comment]
The change didn't make into a RemoteWSL release yet.

**Comment by aeschli** [comment]
I published a new version of Remote-WSL: 0.66.1

**Comment by pmCrawler** [comment]
I'm running 0.66.3 as well - VS Code version 1.67.1, but I see the Change
Log pointing to the correct link.  The market place website is also
pointing to the correct link.

The remote release notes under the corresponding VS Code version contains
change logs for all remote extensions in one .md file,  i.e. Containers,
SSH, and WSL.  Am I missing something?

**Comment by xconverge** [comment]
Yea sorry I edited my post when I realized it's not "exactly" the same issue that was initially reported as fixed, but I can't find any other place outside of reporting a new issue to get the right eyes on it

![image](https://user-images.githubusercontent.com/4219348/168883149-e55e0627-1f2a-48b4-a567-804718bb9cde.png)

**Comment by tanhakabir** [comment]
@xconverge thanks for noticing and filing! Just merged a PR to fix this, it should be fixed in tomorrow's pre-release
