### ISSUE TITLE
Failed remote connection to server with docker container in 1.66 version

### ISSUE THREAD

**Issue by CyberDreamer** [microsoft/vscode-remote-release#6548]
After update VS Code to 1.66 version (Mac OS Monteray 12.3 (21E5227a) beta, MacBook Pro 2018) connection spinning endlessly. Did not help:
- reinstall Docker 
- reinstall VS Code 1.66
- reinstall all VS Code extensions
- Restart Docker container on server
- Reboot laptop

**Comment by chrmarti** [comment]
Could you try with Remote-Containers 0.231.2 and VS Code 1.66 to see if the latest fixes in Remote-Containers resolve the issue?

If that still shows the problem, please post the entire log. (`F1` > `Remote-Containers: Show Container Log` or click on the link in the progress notification in the lower right corner.)
