### ISSUE TITLE
对远程Docker容器开发插件的一点小小的建议

### ISSUE THREAD

**Issue by c4dr01d** [microsoft/vscode-remote-release#655]
我昨天把vscode升级到了最新版并且安装了远程开发插件，我今天在使用远程Docker容器开发的时候，发现在退出含有远程容器开发配置的文件夹时，vscode并没有退出远程容器环境。
能不能实现一下在远程容器开发时，退出含有远程容器开发配置的文件夹或工程时，也退出远程容器呢？:)

**Comment by eaglexiang** [comment]
>  VSCode did not exit the remote container environment when I exited a folder that contained a remote container development configuration. 

you mean the vscode-remote program process didn't quit, or local vscode didn't close the connection to remote folder?

**Comment by c4dr01d** [comment]
@eaglexiang yeah

**Comment by chrmarti** [comment]
Could you append your devcontainer.json?

**Comment by c4dr01d** [comment]
@chrmarti Just normal setting at devcontainer.json, I just modified the Dockerfile to build development environment.

**Comment by chrmarti** [comment]
The container should be stopped by default, but you can change that with the devcontainer.json's "shutdownAction" property.

Is the container not stopped? Are you setting the "shutdownAction"?

**Comment by c4dr01d** [comment]
@chrmarti Nope.

**Comment by chrmarti** [comment]
Which host OS is this? Could you append the Dockerfile?

**Comment by c4dr01d** [comment]
@chrmarti Windows 10, but I'm solved the question, thanks.
