### ISSUE TITLE
copying password not work when language is "fa"

### ISSUE THREAD

**Issue by jmowlaei** [microsoft/vscode-remote-release#6551]
Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1.Open remote ssh project.
2.Put language to non English(LTR) like Farsi(RTL)
3.Copy and paste pasword.

**Comment by tanhakabir** [comment]
Could you show me a GIF of what you're seeing?
