### ISSUE TITLE
Error when reopening project in container with remote-container version 0.231.2

### ISSUE THREAD

**Issue by linhmtran168** [microsoft/vscode-remote-release#6555]
After updating to remote-container version 0.231.2 and reopening my project in remote container I've encountered the following error:
```
Error: Command failed: docker compose -f /home/ubuntu/Dev/github.com/myspace/myproject/docker-compose.yml -f /home/ubuntu/Dev/github.com/myspace/myproject/.devcontainer/docker-compose.vscode.yml --profile * config
```

I thought it's the same problem as https://github.com/microsoft/vscode-remote-release/issues/5992 and tried adding the `default` network to the compose file as specified in https://github.com/microsoft/vscode-remote-release/issues/5992#issuecomment-1000745587 but the problem still happens.
Only downgrading to 0.231.1 solves the issue for me.

- VSCode Version: 1.66.0
- Local OS Version: MacOS 10.15.7
- Remote OS Version: Ubuntu 20.04.4 LTS
- Remote Extension/Connection Type: SSH + Remote Container through Docker in SSH Remote
- Logs:
[remoteContainers-2022-04-04T04-32-49.103Z.log](https://github.com/microsoft/vscode-remote-release/files/8406819/remoteContainers-2022-04-04T04-32-49.103Z.log)

Steps to Reproduce:

1. Open a project with remote container development through SSH remote

**Comment by linhmtran168** [comment]
Additional info: When replacing `*` with `'*'`, running the command in my SSH remote's shell (fish) shows no problem
```
docker compose -f /home/ubuntu/Dev/github.com/myspace/myproject/docker-compose.yml -f /home/ubuntu/Dev/github.com/myspace/myproject/.devcontainer/docker-compose.vscode.yml --profile '*' config
```

**Comment by chrmarti** [comment]
Could you enable trace logging and attach the log from both 0.231.3 (the latest) and 0.231.1 (where it still worked)?
<img width="349" alt="image" src="https://user-images.githubusercontent.com/9205389/161716502-21cb874b-80cd-4097-9553-0935bc3bf360.png">

**Comment by chrmarti** [comment]
Likely https://github.com/microsoft/vscode-remote-release/issues/6562, continuing there.
