### ISSUE TITLE
update to 1.66 doesn't allow user to type input on devcontainer initializeCommand

### ISSUE THREAD

**Issue by ewhitesides** [microsoft/vscode-remote-release#6557]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66
- OS Version: WSL2, also see this issue on Mac

Steps to Reproduce:
i have a devcontainer that runs a shell script on initializeCommand parameter.  the script would prompt the user to enter some credentials, and in 1.65, this worked fine, but in 1.66 it seems the user is not able to type in any input into the terminal during this phase.

**Comment by akutruff** [comment]
> 
@chrmarti I think it is fixed now.  Thanks!
