### ISSUE TITLE
Cannot setup Remote-Containers after updated to Windows 11 version 22H2

### ISSUE THREAD

**Issue by terrycmchan** [microsoft/vscode-remote-release#6559]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.65.2 (user setup)
- OS Version: Windows_NT x64 10.0.22581

Steps to Reproduce:

1. Update to Windows 11 version 22H2
2. Remote-SSH to my host computer
3. Attach VS Code to container in my host computer

The terminal shows log:
[18105 ms] Remote-Containers 0.231.0 in VS Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1).
[18105 ms] Start: Run: ssh 10.6.72.92 /bin/sh
[18111 ms] Start: Run in host: id -un

**Comment by terrycmchan** [comment]
> Does `ssh 10.6.72.92 /bin/sh` work from a terminal?

Yes, it does.
In addition, if I roll back to previous Windows 11 version, this issue will not happen.
This issue only happens in Windows 11 version 22H2.

**Comment by chrmarti** [comment]
@tanhakabir Are you aware of any issues with SSH in Windows 11 version 22H2?

**Comment by tanhakabir** [comment]
This might be related? https://github.com/microsoft/vscode-remote-release/issues/5290

**Comment by chrmarti** [comment]
@terrycmchan What is the output of `ssh -v 10.6.72.92 /bin/sh`?

**Comment by terrycmchan** [comment]
> This might be related? #5290

@tanhakabir This problem only happens on Windows 11 version 22H2 (maybe a Windows Insider Program version). Before this version 22H2, everything is normal on the regular Windows 11 release.

**Comment by terrycmchan** [comment]
> @terrycmchan What is the output of `ssh -v 10.6.72.92 /bin/sh`?

@chrmarti Here is the log from Powershell 7 (After enter the password, it hangs):

> PS C:\Users\terry> ssh -vvvv 10.6.72.92 /bin/sh
OpenSSH_for_Windows_8.6p1, LibreSSL 3.3.3
debug1: Reading configuration data C:\\Users\\terry/.ssh/config
debug1: C:\\Users\\terry/.ssh/config line 1: Applying options for 10.6.72.92
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug2: resolve_canonicalize: hostname 10.6.72.92 is address
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> 'C:\\Users\\terry/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> 'C:\\Users\\terry/.ssh/known_hosts2'
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug3: ssh_connect_direct: entering
debug1: Connecting to 10.6.72.92 [10.6.72.92] port 22.
debug1: Connection established.
debug3: Failed to open file:C:/Users/terry/.ssh/id_rsa error:2
debug3: Failed to open file:C:/Users/terry/.ssh/id_rsa.pub error:2
debug3: failed to open file:C:/Users/terry/.ssh/id_rsa error:2
debug1: identity file C:\\Users\\terry/.ssh/id_rsa type -1
debug3: Failed to open file:C:/Users/terry/.ssh/id_rsa-cert error:2
debug3: Failed to open file:C:/Users/terry/.ssh/id_rsa-cert.pub error:2
debug3: failed to open file:C:/Users/terry/.ssh/id_rsa-cert error:2
debug1: identity file C:\\Users\\terry/.ssh/id_rsa-cert type -1
debug3: Failed to open file:C:/Users/terry/.ssh/id_dsa error:2
debug3: Failed to open file:C:/Users/terry/.ssh/id_dsa.pub error:2
debug3: failed to open file:C:/Users/terry/.ssh/id_dsa error:2
debug1: identity file C:\\Users\\terry/.ssh/id_dsa type -1
debug3: Failed to open file:C:/Users/terry/.ssh/id_dsa-cert error:2
debug3: Failed to open file:C:/Users/terry/.ssh/id_dsa-cert.pub error:2
debug3: failed to open file:C:/Users/terry/.ssh/id_dsa-cert error:2
debug1: identity file C:\\Users\\terry/.ssh/id_dsa-cert type -1
debug3: Failed to open file:C:/Users/terry/.ssh/id_ecdsa error:2
debug3: Failed to open file:C:/Users/terry/.ssh/id_ecdsa.pub error:2
debug3: failed to open file:C:/Users/terry/.ssh/id_ecdsa error:2
debug1: identity file C:\\Users\\terry/.ssh/id_ecdsa type -1
debug3: Failed to open file:C:/Users/terry/.ssh/id_ecdsa-cert error:2
debug3: Failed to open file:C:/Users/terry/.ssh/id_ecdsa-cert.pub error:2
debug3: failed to open file:C:/Users/terry/.ssh/id_ecdsa-cert error:2
debug1: identity file C:\\Users\\terry/.ssh/id_ecdsa-cert type -1
debug3: Failed to open file:C:/Users/terry/.ssh/id_ecdsa_sk error:2
debug3: Failed to open file:C:/Users/terry/.ssh/id_ecdsa_sk.pub error:2
debug3: failed to open file:C:/Users/terry/.ssh/id_ecdsa_sk error:2
debug1: identity file C:\\Users\\terry/.ssh/id_ecdsa_sk type -1
debug3: Failed to open file:C:/Users/terry/.ssh/id_ecdsa_sk-cert error:2
debug3: Failed to open file:C:/Users/terry/.ssh/id_ecdsa_sk-cert.pub error:2
debug3: failed to open file:C:/Users/terry/.ssh/id_ecdsa_sk-cert error:2
debug1: identity file C:\\Users\\terry/.ssh/id_ecdsa_sk-cert type -1
debug3: Failed to open file:C:/Users/terry/.ssh/id_ed25519 error:2
debug3: Failed to open file:C:/Users/terry/.ssh/id_ed25519.pub error:2
debug3: failed to open file:C:/Users/terry/.ssh/id_ed25519 error:2
debug1: identity file C:\\Users\\terry/.ssh/id_ed25519 type -1
debug3: Failed to open file:C:/Users/terry/.ssh/id_ed25519-cert error:2
debug3: Failed to open file:C:/Users/terry/.ssh/id_ed25519-cert.pub error:2
debug3: failed to open file:C:/Users/terry/.ssh/id_ed25519-cert error:2
debug1: identity file C:\\Users\\terry/.ssh/id_ed25519-cert type -1
debug3: Failed to open file:C:/Users/terry/.ssh/id_ed25519_sk error:2
debug3: Failed to open file:C:/Users/terry/.ssh/id_ed25519_sk.pub error:2
debug3: failed to open file:C:/Users/terry/.ssh/id_ed25519_sk error:2
debug1: identity file C:\\Users\\terry/.ssh/id_ed25519_sk type -1
debug3: Failed to open file:C:/Users/terry/.ssh/id_ed25519_sk-cert error:2
debug3: Failed to open file:C:/Users/terry/.ssh/id_ed25519_sk-cert.pub error:2
debug3: failed to open file:C:/Users/terry/.ssh/id_ed25519_sk-cert error:2
debug1: identity file C:\\Users\\terry/.ssh/id_ed25519_sk-cert type -1
debug3: Failed to open file:C:/Users/terry/.ssh/id_xmss error:2
debug3: Failed to open file:C:/Users/terry/.ssh/id_xmss.pub error:2
debug3: failed to open file:C:/Users/terry/.ssh/id_xmss error:2
debug1: identity file C:\\Users\\terry/.ssh/id_xmss type -1
debug3: Failed to open file:C:/Users/terry/.ssh/id_xmss-cert error:2
debug3: Failed to open file:C:/Users/terry/.ssh/id_xmss-cert.pub error:2
debug3: failed to open file:C:/Users/terry/.ssh/id_xmss-cert error:2
debug1: identity file C:\\Users\\terry/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.6
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.2p1 Ubuntu-4ubuntu0.4
debug1: compat_banner: match: OpenSSH_8.2p1 Ubuntu-4ubuntu0.4 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 10.6.72.92:22 as 'terrychan'
debug3: record_hostkey: found key type ECDSA in file C:\\Users\\terry/.ssh/known_hosts:2
debug3: record_hostkey: found key type RSA in file C:\\Users\\terry/.ssh/known_hosts:4
debug3: record_hostkey: found key type ED25519 in file C:\\Users\\terry/.ssh/known_hosts:5
debug3: load_hostkeys_file: loaded 3 keys from 10.6.72.92
debug3: Failed to open file:C:/Users/terry/.ssh/known_hosts2 error:2
debug1: load_hostkeys: fopen C:\\Users\\terry/.ssh/known_hosts2: No such file or directory
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts: No such file or directory
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts2: No such file or directory
debug3: order_hostkeyalgs: have matching best-preference key type ssh-ed25519-cert-v01@openssh.com, using HostkeyAlgorithms verbatim
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
debug2: host key algorithms: ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:xpJcAF7I6+dF9UG3vCRlpO0cEYzcp6sgdwDtMgm8uok
debug3: record_hostkey: found key type ECDSA in file C:\\Users\\terry/.ssh/known_hosts:2
debug3: record_hostkey: found key type RSA in file C:\\Users\\terry/.ssh/known_hosts:4
debug3: record_hostkey: found key type ED25519 in file C:\\Users\\terry/.ssh/known_hosts:5
debug3: load_hostkeys_file: loaded 3 keys from 10.6.72.92
debug3: Failed to open file:C:/Users/terry/.ssh/known_hosts2 error:2
debug1: load_hostkeys: fopen C:\\Users\\terry/.ssh/known_hosts2: No such file or directory
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts: No such file or directory
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts2: No such file or directory
debug1: Host '10.6.72.92' is known and matches the ED25519 host key.
debug1: Found key in C:\\Users\\terry/.ssh/known_hosts:5
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey in after 134217728 blocks
debug3: unable to connect to pipe \\\\.\\pipe\\openssh-ssh-agent, error: 2
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug1: Will attempt key: C:\\Users\\terry/.ssh/id_rsa
debug1: Will attempt key: C:\\Users\\terry/.ssh/id_dsa
debug1: Will attempt key: C:\\Users\\terry/.ssh/id_ecdsa
debug1: Will attempt key: C:\\Users\\terry/.ssh/id_ecdsa_sk
debug1: Will attempt key: C:\\Users\\terry/.ssh/id_ed25519
debug1: Will attempt key: C:\\Users\\terry/.ssh/id_ed25519_sk
debug1: Will attempt key: C:\\Users\\terry/.ssh/id_xmss
debug2: pubkey_prepare: done
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: C:\\Users\\terry/.ssh/id_rsa
debug3: no such identity: C:\\Users\\terry/.ssh/id_rsa: No such file or directory
debug1: Trying private key: C:\\Users\\terry/.ssh/id_dsa
debug3: no such identity: C:\\Users\\terry/.ssh/id_dsa: No such file or directory
debug1: Trying private key: C:\\Users\\terry/.ssh/id_ecdsa
debug3: no such identity: C:\\Users\\terry/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: C:\\Users\\terry/.ssh/id_ecdsa_sk
debug3: no such identity: C:\\Users\\terry/.ssh/id_ecdsa_sk: No such file or directory
debug1: Trying private key: C:\\Users\\terry/.ssh/id_ed25519
debug3: no such identity: C:\\Users\\terry/.ssh/id_ed25519: No such file or directory
debug1: Trying private key: C:\\Users\\terry/.ssh/id_ed25519_sk
debug3: no such identity: C:\\Users\\terry/.ssh/id_ed25519_sk: No such file or directory
debug1: Trying private key: C:\\Users\\terry/.ssh/id_xmss
debug3: no such identity: C:\\Users\\terry/.ssh/id_xmss: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
terrychan@10.6.72.92's password:
debug3: send packet: type 50
debug2: we sent a password packet, wait for reply
debug3: receive packet: type 52
debug1: Authentication succeeded (password).
Authenticated to 10.6.72.92 ([10.6.72.92]:22).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Requesting no-more-sessions@openssh.com
debug3: send packet: type 80
debug1: Entering interactive session.
debug1: pledge: filesystem full
debug3: receive packet: type 80
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug3: client_input_hostkeys: received RSA key SHA256:HjSmyzsaBi3ozD51IdA/9n1jPPPTmyW7eAjNexUmunI
debug3: client_input_hostkeys: received ECDSA key SHA256:ajHOKIi1IXXp+2KZGuf+yoOHfQyGBv+KqaDiH91aGBg
debug3: client_input_hostkeys: received ED25519 key SHA256:xpJcAF7I6+dF9UG3vCRlpO0cEYzcp6sgdwDtMgm8uok
debug1: client_input_hostkeys: searching C:\\Users\\terry/.ssh/known_hosts for 10.6.72.92 / (none)
debug3: hostkeys_foreach: reading file "C:\\Users\\terry/.ssh/known_hosts"
debug3: hostkeys_find: found ecdsa-sha2-nistp256 key at C:\\Users\\terry/.ssh/known_hosts:2
debug3: hostkeys_find: found ssh-rsa key at C:\\Users\\terry/.ssh/known_hosts:4
debug3: hostkeys_find: found ssh-ed25519 key at C:\\Users\\terry/.ssh/known_hosts:5
debug1: client_input_hostkeys: searching C:\\Users\\terry/.ssh/known_hosts2 for 10.6.72.92 / (none)
debug3: Failed to open file:C:/Users/terry/.ssh/known_hosts2 error:2
debug1: client_input_hostkeys: hostkeys file C:\\Users\\terry/.ssh/known_hosts2 does not exist
debug3: client_input_hostkeys: 3 server keys: 0 new, 3 retained, 0 incomplete match. 0 to remove
debug1: client_input_hostkeys: no new or deprecated keys from server
debug3: receive packet: type 91
debug2: channel_input_open_confirmation: channel 0: callback start
debug2: fd 3 setting TCP_NODELAY
debug2: client_session2_setup: id 0
debug1: Sending command: /bin/sh
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0

**Comment by chrmarti** [comment]
@terrycmchan This looks like a problem with the ssh client. Could you file an issue at https://github.com/PowerShell/Win32-OpenSSH/issues including the debug output? Thanks.

**Comment by terrycmchan** [comment]
OK. Thanks
