### ISSUE TITLE
Add CLI for remote dev

### ISSUE THREAD

**Issue by ykafia** [microsoft/vscode-remote-release#656]
Would be useful to just call VsCode remote dev directly through CLI like so :

```powershell
code --remote-ssh Machine1
```

**Comment by roblourens** [comment]
I think we have an issue for this somewhere but I can't find it...

**Comment by payonel** [comment]
just starting using remote ssh, this is the first thing i was looking for. I start all my projects and tools from command line, so this (for me) would be a very valuable feature!

**Comment by robertsk50** [comment]
If you want to open a specific file/folder on a remote machine you can use the uri command line functionality:

`code --folder-uri vscode-remote://ssh-remote%2B<host><path>`
or
`code --file-uri vscode-remote://ssh-remote%2B<host><path>`

**Comment by johnbillion** [comment]
How does this translate to a `vscode://`-style URI that can be opened via the browser? The `vscode-remote://` protocol handler doesn't appear to be registered.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/pull/90367 suggests to introduce support for vscode://-style URIs in the form of: `vscode://vscode-remote/<authority>/<path>`

**Comment by aeschli** [comment]
Also already supported is the following:

`code --remote ssh-remote+<remoteHost> <remotePath>`

It's up to each remote extension to define the format for what's behind the `+`.
Ideally, ssh would spec what is valid in the documentation.

**Comment by bpasero** [comment]
This landed via https://github.com/microsoft/vscode/commit/bdf11560cd000d52d87c7bbb86521c9c9360901d. The URI must be of the form: `<vscode|vscode-insiders>://<vscode-remote>/<authority>/<path>` and will then internally be transformed to be `<vscode-remote>://<authority>/<path>`

**Comment by d2inco** [comment]
I am assuming the `vscode-remote` is the SSH target.... What key is the `authority`?

**Comment by bpasero** [comment]
Here is an example for SSH: `vscode://vscode-remote/ssh-remote+<host>/<path>`. Pretty much everything in `vscode://vscode-remote` is static and only afterwards is remote specific.

**Comment by bpasero** [comment]
Verification:

Craft a `vscode-remote` URI as outlined above and use the "Open Link" command to open it:

![image](https://user-images.githubusercontent.com/900690/74760069-25affe00-527a-11ea-9844-d030e9d3be7e.png)

**Comment by connor4312** [comment]
I wasn't able to get this working. On the latest insiders I tried opening the link:

```
vscode-insiders://vscode-remote/ssh-remote+<ip>/home/connor
```

(as well as the non-`-insiders` version)

However, nothing happened. I didn't see any error logs anywhere. Running Open Link on `https://example.com` works. The remote SSH extension is installed and I'm able to connect to the host manually.

**Comment by bpasero** [comment]
@connor4312 please clarify how you tried this and on what OS you are on.

**Comment by connor4312** [comment]
Okay, I got it working. Realized that the vscode URI, unlike the https link, was not recognized in the plain text language mode.

**Comment by kuboon** [comment]
> code --remote ssh-remote+<remoteHost> <remotePath>

I have tried this on *code-insiders 1.44.0-insider*
I have both WSL and SSH remote extentions, this command opened WSL.
how can I open SSH?

**Comment by svalentin** [comment]
Just to confirm, is there a way to open a remote _file_ by URL? I only seem to get it to work with folders.
vscode://vscode-remote/ssh-remote+<host>/<path/to/folder> works
vscode://vscode-remote/ssh-remote+<host>/<path/to/file> tries to open the "folder" with the name of the file.

**Comment by bersbersbers** [comment]
@svalentin I just confirmed that it does work with workspace files, that is,
`vscode://vscode-remote/ssh-remote+myhost/home/myuser/myproject.code-workspace`
is working fine.

**Comment by svalentin** [comment]
Interesting. To me it behaved as if running vscode with `code --folder-uri <URI-to-file>`  when what I was looking for was something similar with running vscode with `code --file-uri <URI-to-file>`.
I worked around it by registering my own URL handler that runs the above command.
