### ISSUE TITLE
VScode remote: Clone repository in container volume

### ISSUE THREAD

**Issue by daniellaera** [microsoft/vscode-remote-release#6564]
When I clone a private repository over `https` in VSCode remote container using CTRL + P > clone repository in container volume
I have the error saying `cannot access the repository...`
I doesn't even asks for credentials in any popup terminal or windows

- VSCode Version: 1.66
- Local OS Version: Ubuntu 21.10
- Reproduces in: <Codespaces | Remote - Containers | Both>

Steps to Reproduce:

![Screenshot from 2022-04-05 11-35-59](https://user-images.githubusercontent.com/8995710/161725525-4cbdc592-c26a-4ddc-bacf-9fd85bca711d.png)

**Comment by chrmarti** [comment]
We forward Git credentials from your local Git, but we do not support user input yet. This is tracked as https://github.com/microsoft/vscode-remote-release/issues/1941.

If you set up your local Git such that you can clone the repository locally without user input, it should also work for the dev container.
