### ISSUE TITLE
All code was lost when using vscode for remote development in a container

### ISSUE THREAD

**Issue by qingchunlizhi** [microsoft/vscode-remote-release#6565]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:1.62.3 (Universal): ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
- OS Version: macOS montery 12.3

Steps to Reproduce:

1. When I used the  remote development(containers) tools to develop in a remote machine, all code was lost suddenly. I found the project and the .vscode file  were removed, but not deleted artificially. Like this picture:
![image](https://user-images.githubusercontent.com/18531375/161725785-2427d463-5b6e-4e7b-bde6-0e4401d524cf.png)
Has anyone ever had the same problem？It was a very terrible experience, and I also encountered it in vscode-insiders. Please help me！！
Thanks！！

**Comment by chrmarti** [comment]
The error shows that you have worked with a container you attached to. Did you create the container yourself? Were the files mounted from the local filesystem or from a Docker volume?

**Comment by qingchunlizhi** [comment]
> The error shows that you have worked with a container you attached to. Did you create the container yourself? Were the files mounted from the local filesystem or from a Docker volume?

Yes, I create the container based on a basic image. The files were mounted from the local filesystem. The .vscode and .git files were lost too.

**Comment by chrmarti** [comment]
Could you describe what you were doing at the time this happened and does it happen again when you try doing the same with new files?
