### ISSUE TITLE
Cannot connect to Rasperry Pi

### ISSUE THREAD

**Issue by isaac2004** [microsoft/vscode-remote-release#657]
- VSCode Version:
- Local OS Version:
- Remote OS Version:
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Please include more details about what you are trying to do.

Helpful blog post: https://www.hanselman.com/blog/VisualStudioCodeRemoteDevelopmentOverSSHToARaspberryPiIsButter.aspx
