### ISSUE TITLE
How to import my local vscode settings into ssh'ed remote session?

### ISSUE THREAD

**Issue by ksajan** [microsoft/vscode-remote-release#6573]
🚨 The issue tracker is not for questions 🚨

If you have a question about VS Code, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code and about
VS Code Remote on https://stackoverflow.com/questions/tagged/vscode-remote.

I am able to ssh into the remote desktop and work as intended but I would like to know that is it possible to import local vscode settings into my remote directly without going through each individual plugin and settings themes I have configured on my local vscode. I have tried sync but it doesn't work and I am not able to find any solution on the internet. Thanks for the help

**Comment by ksajan** [comment]
No error it just doesn't show anything. It just says sync completed but I don't see any changes in my editor. Such as theme change or plugins such as tabnine, copilot, pylance, etc..

**Comment by tanhakabir** [comment]
Oh hm that seems unexpected, @sandy081 any thoughts?

**Comment by sandy081** [comment]
Are you using settings sync feature out of the box or the feature from the extension?

**Comment by sandy081** [comment]
Ok. But May I know the reason for your ask?

> but I would like to know that is it possible to import local vscode settings into my remote directly
