### ISSUE TITLE
Allow MFA code to be provided when using Remote SSH with AWS SSM

### ISSUE THREAD

**Issue by Fydon** [microsoft/vscode-remote-release#6574]
I used to be able to enter my Multi-Factor Authentication code for AWS SSM when using Remote SSH, but now it only shows on the output window where I can't provide input. I think that it used to appear in the terminal. As a workaround, I can provide the MFA for another command just prior to SSH so that it doesn't prompt.

**Comment by tanhakabir** [comment]
Would you be able to share your Remote SSH logs?

**Comment by Fydon** [comment]
Sorry it seems to be working again. I use vscode-insider so maybe a nightly broke something when I previously tried it.

**Comment by tanhakabir** [comment]
Hm I'm not sure but I haven't pushed any changes in the pre-release of the extension recently. My guess would be that your setting `showLoginTerminal` was set to `false`
