### ISSUE TITLE
Kubernetes: Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused: auth mismatch)

### ISSUE THREAD

**Issue by sfarkya** [microsoft/vscode-remote-release#6578]
I am trying to connect my Kubernetes pod container to VSCode on local and I am following these steps: 

https://code.visualstudio.com/docs/remote/attach-container#_attach-to-a-container-in-a-kubernetes-cluster 

I am able to connect it to the pod but when I try to access the file system inside the pod I am getting this error: 

[![enter image description here][1]][1]

Just more details, the filesystem is mounted inside the pod from an external PVC we have on our data storage. 

Here's the log generated inside the pod while the connection is being set up. [![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/Deg3J.png
  [2]: https://i.stack.imgur.com/cP9Of.png

I think that there's some permission issue someplace in the setup but unable to narrow it down.

**Comment by alejandrogr** [comment]
Hello! we are seeing the same behavior since yesterday. The connection to the pod is done but when we try to access the filesystem we get the same error.

**Comment by chrmarti** [comment]
Looks like https://github.com/microsoft/vscode-remote-release/issues/6563. Could someone seeing this append the dev container log from when this fails? (Click on the link in the initial progress notification in the bottom right or use `F1` > `Remote-Containers: Show Container Log` if that already works.)

**Comment by MeirP-3** [comment]
Here is the container log. Line 111 ends with `-e` without arguments. Maybe this is the problem
[container.log](https://github.com/microsoft/vscode-remote-release/files/8441449/container.log)

**Comment by chrmarti** [comment]
The line ending in `-e` would continue on the next line, but we don't log that to keep the log from filling too quickly.

This doesn't show for me. Could someone go back one version of the Remote-Containers extension at a time and see at which version it broke?

**Comment by chrmarti** [comment]
https://github.com/microsoft/vscode-remote-release/issues/5290#issuecomment-1088083803 mentions 0.231.1 is working and 0.231.2 broke it.

**Comment by chrmarti** [comment]
Fixed in Remote-Containers 0.231.5 and 0.232.5-pre-release.
