### ISSUE TITLE
Dev container with docker compose seems to ignore `docker.context` setting

### ISSUE THREAD

**Issue by artificial-aidan** [microsoft/vscode-remote-release#6581]
- VSCode Version: 1.64.0-insider
- Local OS Version: macOs 10.15.7
- Remote OS Version: linux
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Use a remote docker context and a docker compose dev container
2. Set `docker.context` to `default`
3. Try and start dev container.

When I just use 1 dev container this works fine (the context is observed, and a local container runs), and the `docker.context` setting is observed. However when I try and use docker compose, it errors.

Maybe this is a docker extension issue?

**Comment by chrmarti** [comment]
This seems to work with the latest Remote-Containers extension (currently 0.231.4). Could you retry with that?

**Comment by artificial-aidan** [comment]
I still see this issue on v0.232.6.

I will try going back to stable.

**Comment by artificial-aidan** [comment]
Tried v0.231.6. Same problem.

I think it might be related to using `docker-compose` not `docker compose`. IIRC `docker-compose` does not respect context the same way.

Is there a set of environment variables that could be used to try and set remote context instead?

**Comment by artificial-aidan** [comment]
@chrmarti is there a way to reopen this?

**Comment by chrmarti** [comment]
What version of docker-compose are you using?

**Comment by artificial-aidan** [comment]
Confirmed not an issue with latest docker-compose. Thank you.
