### ISSUE TITLE
Please add support for pyspark remote connections

### ISSUE THREAD

**Issue by krishnayeswanth99** [microsoft/vscode-remote-release#6583]
Hai,
      can u please add the feature where I can run my spark notebooks (ipynb) from code, specifying the spark bin path?

If this feature already exists please point me to the same. I tried searching for this but didn't find any.

**Comment by chrmarti** [comment]
Maybe you are looking for something like this tutorial: https://docs.microsoft.com/en-us/azure/synapse-analytics/spark/vscode-tool-synapse ?

**Comment by krishnayeswanth99** [comment]
@chrmarti this is for setting up the environment provided we have creds right. But in my case I only have access to DB's through certain jump servers which I normally connect through ssh and tunnel notebook through this. But in this case how can I achieve this?

**Comment by chrmarti** [comment]
The Remote Development extensions are all about having your source code somewhere else, e.g., a SSH server with the Remote-SSH extension.

If your source code is on an SSH server, I suggest using Remote-SSH. If there are any SSH jump servers in between, you can configure them in your `~/.ssh/config` file (if you haven't already) to make it work.

Does that help?

**Comment by krishnayeswanth99** [comment]
@chrmarti  I have already setup ssh config, but to use notebook we have to specify kernel right. But incase of spark we don't have any such utility and we have initialise notebook from yarn and tunnel the same to local right?

**Comment by chrmarti** [comment]
I'm not familiar with Spark. I would suggest to open an issue for the Spark extension at https://github.com/microsoft/Spark-Hive-Tools/issues or ask on StackOverflow. Thanks.
