### ISSUE TITLE
Error connecting to Remote VM with Windows vscode. [Could not fetch remote environment]

### ISSUE THREAD

**Issue by themagiccog** [microsoft/vscode-remote-release#6588]
Error connecting to Remote VM with Windows vscode. 
[Could not fetch remote environment]
[Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)]

<img width="498" alt="image" src="https://user-images.githubusercontent.com/13458634/162070207-3788cea1-1836-4f6b-a414-f8420229a9a2.png">

**Comment by tanhakabir** [comment]
Could you share your full Remote SSH logs with us? And do you have TCP port forwarding enabled on your remote machine?

**Comment by themagiccog** [comment]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/13458634/162554203-8e1a3ae3-07c4-4c13-a179-1e8b53ca5054.png">

See image of Log

**Comment by tanhakabir** [comment]
Are you able to connect to this VM through your shell?

**Comment by themagiccog** [comment]
I am unable to connect to the VMs when using Windows.


With My Mac, I am able to connect.

**Comment by umdstu** [comment]
I've recently begun having these reconnect issues again as well, within the last ~2 weeks maybe, not sure exact date when it started but definitely recently. 

Different from OP, i'm on Linux. The behavior is similar but not exact to the above users. The scenario is this:

1. Connect to remote host.
2. Stop using session for some period of time
3. Remote host is terminated at 2100 each evening
4. According to Output tab, the Extension attempts to reconnect immediately following the remote host termination, but ultimately gets a connection refused from it.
5. The next morning this window is still spinning `Reconnecting to SSH: ...` in the bottom left. The tail end of Output tab for `Remote - SSH` just contains messages (at 30s intervals or so).

```
[time] Failed to set up socket for dynamic port forward to remote port 40219: connect ECONNREFUSED 127.0.0.1:44493. Is the remote port correct?
```

This behavior isn't unexpected. What is unexpected is the fact that the extension doesn't appear to give up and accept the connection is lost. The other windows/sessions in the same scenario ultimately accept defeat and display the `"Cannot reconnect. Please reload the window." Cancel / Reload Window` dialog. It's only the one window that never accepts defeat and displays the dialog, it just keeps spinning (and attempting to connect to the remote port)

Around this same time (perhaps a bit before if at all), the Cancel / Reload Window dialog also began being unresponsive for all but one of the VSCode windows that were open. Wherein you have to find the window of the many open ones that allows you to click the button, click 'Reload' then move through the windows again to find the next one that will let you click it, repeating until all windows are reconnected. In the past, the solution for this particular issue was enabling native dialog for VSCode, however that is enabled and it's now still happening. 

I can create separate tickets for these but they all coincided around the same time and seem similar enough to OP that I wanted to drop them here first in case it's all related. 

Related Details:
Version: 1.66.1
OS: Linux x64
Remote - SSH Version: 0.78.0
`"window.dialogStyle": "native"`

**Comment by umdstu** [comment]
And for what it's worth, I compared the Output tab for a window that successfully yielded the reconnect dialog with the one that hasn't been, and they are identical in everywhere except:
- seconds/milliseconds in timestamps
- Pids
- Ports
- Socket filenames

**Comment by eleanorjboyd** [comment]
Hello, I'm Eleanor the new remote-SSH maintainer! I wanted to check about the status of this issue. Are you still experiencing these issues and if so on the most recent version of VS Code?

If it is still occurring, what I am understanding from the thread is that after the connection to the server dies then all the windows show they got disconnected except for one which keeps trying? Then secondly all these windows become unresponsive except one that shows `"Cannot reconnect. Please reload the window." Cancel / Reload Window` and after selecting there you are then able to click only the next window in the 'queue' to cancel or reload. Is this correct? 

Thanks!
