### ISSUE TITLE
A number of problems

### ISSUE THREAD

**Issue by ariansacct** [microsoft/vscode-remote-release#659]
- There's not even a button to disconnect
- When the connection suddenly terminates there is no way to get rid of the window and the whole application has to be restarted
- A new window is opened every time
- Once a folder is opened there is no way to go up or open another folder without opening a new window

**Comment by egamma** [comment]
@ariansacct thanks for your feedback

>There's not even a button to disconnect

This has been added in the latest.

**Comment by ariansacct** [comment]
I hope you haven't been offended by my comment, which was not my intention. I tried to give an honest review. If you're not a Microsoft employee (or you don't get paid to do this), I appreciate the work that you put in.

**Comment by ariansacct** [comment]
What do you mean by the latest? I have the latest version of Code and this plugin. I still cannot see how to disconnect.

**Comment by egamma** [comment]
@ariansacct sorry for not being more clear. The latest fixes require the insider version of vscode, pls see https://code.visualstudio.com/blogs/2016/02/01/introducing_insiders_build for more information about the insiders build.

If you are on insiders then the action is called `Close Remote Connection`.

![image](https://user-images.githubusercontent.com/172399/59584661-e889df80-90de-11e9-8aaf-13f489823c4d.png)

**Comment by roblourens** [comment]
> When the connection suddenly terminates there is no way to get rid of the window and the whole application has to be restarted

If vscode can't reconnect, then you should see a dialog with a "reload window" button. You can also open the command palette and run this command yourself.

> A new window is opened every time

Not clear what you're talking about, please give more details


> Once a folder is opened there is no way to go up or open another folder without opening a new window

You can open any new folder in that window with the "File: Open" command

**Comment by aasgnfd** [comment]
Here are a few suggestions. Feel free to disagree with any of them.

- It is better if when a connection is established remote files can be opened in the same window. For example by having two filesystems open in the sidebar (one local and one remote)
- When a connection is gracefully closed the window doesn't close and the files stay available for local viewing
- Navigation buttons are provided next to each open filesystem

**Comment by ariansacct** [comment]
Here are a few suggestions. Feel free to disagree with any of them.
- It is better if when a connection is established remote files can be opened in the same window. For example by having two filesystems open in the sidebar (one local and one remote)
- When a connection is gracefully closed the window doesn't close and the files stay available for local viewing
- Navigation buttons are provided next to each open filesystem

**Comment by roblourens** [comment]
- Mixed workspaces (local and remote files in one window) is something that we might support at some point but not in the near future
- In the second point I think you are talking about some kind of "offline" mode where you can browse files that were previously downloaded, but that is not likely to happen in the near future
- I don't understand what you are asking for in the third point

I'm going to close this, please open issues that focus on a single feature request that is well-described, not a list of requests.
