### ISSUE TITLE
What is this line all about in startup log?

### ISSUE THREAD

**Issue by juxeii** [microsoft/vscode-remote-release#6595]
This is in my Remote SSH debug log startup
```
[09:00:57.615] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:00:59.410] > ]0;C:\WINDOWS\System32\cmd.exe
[09:00:59.411] Got some output, clearing connection timeout
[09:00:59.831] > c1ede549f155: running
[09:00:59.909] > bash: line 180: ldd: command not found
[09:00:59.927] > Missing GLIBC >= 2.17!
```
In order to debug the missing GLIBC, I wanted to know where `bash: line 180: ldd: command not found` stems from?
Is it in some startup script? I grepped for it in `.vscode-server folder`, but nothing could be found.
So, who wants to call `ldd`?

**Comment by tanhakabir** [comment]
In our installation script upon connection we run `ldd --version | head -n1` to verify your remote machine has the requirements we need.

What happens when you execute `ldd --version | head -n1` on your remote?

Also these are our Linux machine prereqs: https://code.visualstudio.com/docs/remote/linux

**Comment by juxeii** [comment]
I connecting to a Synology NAS. The problem with GLIBC is know and I can handle it.
I just want to know where I can **find the installation script** you mentioned.

**Comment by tanhakabir** [comment]
The installation script is closed source and piped in on successful SSH connection.

These are the various paths we check for rereqs:
1. `/usr/lib64/libstdc++.so.6` or `/sbin/ldconfig` for libstdc
2. If libstdc was found then `cat $libstdc_path | grep -a -o -E 'GLIBCXX_[[:digit:]]+\\.[[:digit:]]+\\.([[:digit:]]+)?' | sed 's/GLIBCXX_'//gi` for glibcxx versions
3. We check if glibcxx is at least 3.4.18 exists from all versions
5. `ldd --version | head -n1` for ldd which we check the version matches the regex of `^ldd.*([[:digit:]]+)\\.([[:digit:]]+)`
6. And then we check that the version number of ldd is higher than 217 to verify glibc is higher than 2.17

**Comment by juxeii** [comment]
Oh, was not aware that we have closed sources in an open source project ;)
Neverming, thank you very much. That is helpful.
