### ISSUE TITLE
Clone this repo in VS Code and allow it to reopen in a dev container: "Cannot open: Permission denied" * 489+

### ISSUE THREAD

**Issue by jsma** [microsoft/vscode-remote-release#6596]
Does this issue occur when all extensions are disabled?: Yes/No

I am not sure what disabling extensions might have to do with this since this project is opened in a dev container which specifies its own extensions and presumably these are the only extensions involved in this scenario:

```
"extensions": [
    "dbaeumer.vscode-eslint",
    "mutantdino.resourcemonitor"
]
```

- VS Code Version: 1.66.0
- OS Version: macOS 12.3.1

Steps to Reproduce:

1. Copy the clone URL for this repo: https://github.com/microsoft/vscode.git
2. Open Visual Studio Code
3. Click "Clone Git Repository..."
4. Paste the clone URL
5. Let VS Code do the cloning, then get prompted to reopen in a dev container
6. Click prompt to allow reopening in a dev container
7. See hundreds of errors in the output

Small sample of the output:

```
102726 ms] [02:40:45] Renamed to /home/node/.vscode-server/extensions/mutantdino.resourcemonitor-1.0.7
[102729 ms] [02:40:45] Extracting completed. mutantdino.resourcemonitor
[102731 ms] [02:40:45] Extension installed successfully: mutantdino.resourcemonitor
[102733 ms] Extension 'mutantdino.resourcemonitor' v1.0.7 was successfully installed.
tar: ./test/smoke/node_modules/fstream/node_modules/.bin/rimraf: Cannot open: Permission denied
tar: ./test/smoke/node_modules/fstream/node_modules/.bin/mkdirp: Cannot open: Permission denied
tar: ./test/smoke/node_modules/@vscode/test-electron/node_modules/.bin/rimraf: Cannot open: Permission denied
tar: ./test/smoke/node_modules/.bin/which: Cannot open: Permission denied
tar: ./test/smoke/node_modules/.bin/run-s: Cannot open: Permission denied
tar: ./test/smoke/node_modules/.bin/rimraf: Cannot open: Permission denied
tar: ./test/smoke/node_modules/.bin/ncp: Cannot open: Permission denied
tar: ./test/smoke/node_modules/.bin/pidtree: Cannot open: Permission denied
tar: ./test/smoke/node_modules/.bin/semver: Cannot open: Permission denied
tar: ./test/smoke/node_modules/.bin/run-p: Cannot open: Permission denied
tar: ./test/smoke/node_modules/.bin/npm-run-all: Cannot open: Permission denied
tar: ./test/smoke/node_modules/.bin/watch: Cannot open: Permission denied
tar: ./test/smoke/node_modules/.bin/mkdirp: Cannot open: Permission denied
tar: ./test/smoke/node_modules/cross-spawn/node_modules/.bin/which: Cannot open: Permission denied
tar: ./test/smoke/node_modules/cross-spawn/node_modules/.bin/semver: Cannot open: Permission denied
tar: ./test/smoke/node_modules/normalize-package-data/node_modules/.bin/semver: Cannot open: Permission denied
```
Full output from the Terminal here:

[vscode-dev-container-errors.txt](https://github.com/microsoft/vscode/files/8403772/vscode-dev-container-errors.txt)

Perhaps this is expected for whatever reason, but I couldn't find anything in the issue tracker related to this. Or perhaps I did a git clone at an inopportune time and the build is currently broken. As a first time cloner of this repo, I expected things to just work given all the hype around devcontainer solving all of the problems of getting a working environment up and running. I did not expect to see nearly 500 "Permission denied errors". As a newcomer that tells me something is very broken.

Also, when I first confirmed that VS Code should reopen in a dev container it popped up an alert:

<img width="263" alt="Screen Shot 2022-04-02 at 7 38 41 PM" src="https://user-images.githubusercontent.com/24574/161410910-172d674e-d7a5-4448-9c53-dc66163f5f1b.png">

This is my unmodified Docker Desktop for Mac configuration:

<img width="501" alt="Screen Shot 2022-04-02 at 9 05 16 PM" src="https://user-images.githubusercontent.com/24574/161410942-04306894-4b62-4f72-bda4-e1fd80a6e3e2.png">

All I see in `.devcontainer/devcontainer.json` is:

```
"hostRequirements": {
    "memory": "8gb"
}
```

Is VS Code trying to tell me that Docker calculates RAM differently than VS Code and so I'm short "0.23gb"? Perhaps VS Code/devcontainer.json should use the same RAM math as Docker? Is "gb" the same unit of measure as "GB" or has Microsoft introduced a brand new unit of measure?

**Comment by chrmarti** [comment]
@jsma What do you get for `docker info --format '{{json .}}'` on the command line?

**Comment by Chuxel** [comment]
I'm not able to reproduce the permissions issue with the same configuration.  Generally, I'd suggest using "Clone Repository in Container Volume" for this repository since you'll see much improved disk performance.  The only thing I can think of is if this repository already existed on your filesystem, its possible that some of the folders already had permissions on them somehow that prevented them from being created/updated.

I did however, see the error message.  For whatever reason, if you set Docker Desktop to 8GB, it reports 7.774GB via `docker info`. It's consistent since setting it to 8.25GB returns 8.008GB.  There must be some overhead in the VM that consumes some amount of RAM that makes the usable amount less than the set amount.

**Comment by jsma** [comment]
Sometime after I posted this issue, there was an update for Docker Desktop for Mac. After the update, preferences showed the slider had moved to just below 8GB so I had to slide it back up to 8GB. I didn't see anything in the release notes related to RAM but it made me wonder if they had changed something related to the UI's representation of allocated RAM. At the moment, the slider says "8.00GB" and the output of `docker info` says: `"MemTotal":8346021888`.

I tried to repeat my steps above, ensuring the previous checkout was renamed and out of the way. I still get the memory error:
<img width="343" alt="Screen Shot 2022-04-11 at 7 55 47 AM" src="https://user-images.githubusercontent.com/24574/162767726-ee1ac245-21a2-4cb0-880b-00cd531cac79.png">

While I agree Docker may have things a little mixed up on their end, it seems there is still an issue with VS Code if `docker info` shows something much higher than the 7.77GB VS Code reports.

I left the modal open and adjusted Docker to 8.50GB (`docker info` now says: `"MemTotal":8861917184`), restarted Docker and the clicked "Continue" in VS Code. I still get permission denied errors. The only extensions installed in the dev container are of course the extensions defined in devcontainer.json.

@Chuxel, I can "Clone Repository in Container Volume" and I don't see any errors in the output. It seems to do far less work vs "clone & reopen in dev container" but at least it seems to work. 

Apologies for the snark in my original post, it's been a frustrating couple of weeks trying to get any IDE working and I was surprised that I couldn't even use VS Code to clone `vscode` without immediately encountering issues.

**Comment by Chuxel** [comment]
@chrmarti I suspect we may need to factor in the ~250mb delta between what is set in the Docker Desktop UX and what docker info returns.  `8861917184` is actually 8.25GB despite it being set to 8.5GB.  I'm seeing the same thing elswhere... that would explain the 7.77GB.

@jsma It also sounds like there's something might be going on with Docker and the file location you have the repository cloned into which is odd.  

There was a 1.66.1 release and Remote - Containers 0.231.5 was released to try to fix some issues and I know one was path related.  That's what I used to try to repro and wasn't able to get it to happen so it's possible this has been fixed already since I noticed in your bug report you mentioned VS Code 1.66.0.  

Can you check the VS Code and extension version?  I'm wondering if postCreateCommand was executing in the wrong spot before that fix got in. That could explain it.

FWIW - "Clone Repository in Container Volume" goes through the exact same steps, but does it in a volume so the disk performance is much better.  Bind mounts translate from the macOS filesystem to Linux, which adds a lot of overhead on small files ... like an npm install. (Docker is working on a new filesystem and experimenting with using Apple's hypervisor to try to fix this - but its not easy as you can imagine.).

**Comment by jsma** [comment]
> It also sounds like there's something might be going on with Docker and the file location you have the repository cloned into which is odd.

The file location is `~/Projects`, where I keep all of my...projects 😉. No special file permissions, no problems checking out any other repo including my day job repo that also has a devcontainer.json. Only `vscode` gives me this trouble.

```
ls -l ~/
...snip...
drwxr-xr-x  31 username  staff    992 Apr 11 07:54 Projects
...snip...
ls -l ~/Projects/
...snip...
drwxr-xr-x  37 username  staff       1184 Apr 11 07:59 vscode
...snip...
```

> FWIW - "Clone Repository in Container Volume" goes through the exact same steps, but does it in a volume so the disk performance is much better. Bind mounts translate from the macOS filesystem to Linux, which adds a lot of overhead on small files ... like an npm install. (Docker is working on a new filesystem and experimenting with using Apple's hypervisor to try to fix this - but its not easy as you can imagine.).

Ah, well maybe this is relevant (maybe not, but I'm a lowly web developer who'd love to get back to web development and wishes these tools were mostly invisible to me 😉):
<img width="778" alt="Screen Shot 2022-04-11 at 3 36 06 PM" src="https://user-images.githubusercontent.com/24574/162844458-84366d05-c9c7-455a-8484-b6439982496f.png">

I was under the impression these "experiments" might actually _improve_ performance rather than introduce obscure bugs that might make performance even worse, but they _are_ labelled "experiments" so caveat emptor lol.

I'll have to do another clean clone using both methods and try to capture the output, but the "clone and open in container" option took way longer IIRC.

> There was a 1.66.1 release and Remote - Containers 0.231.5 was released to try to fix some issues and I know one was path related. 

I'm currently on the versions you mention and am fairly certain that was the case before I tested again this morning. There wasn't any obvious "restart to update" etc. and I actually did a clean install on my laptop late last week and it appears the latest updates happened on or before the reinstall (4/8/2022). 

I really don't want to be a PITA and apologies if I've crossed that line already. I didn't intend to contribute to `vscode` directly so this issue isn't the biggest priority for me. Again, I had just assumed that if _any_ project in the world would work according to the promise/hype of dev containers "it just works!", it would be `vscode`.

I only cloned the `vscode` repo so I could more easily navigate the code as I tried to sort out how other extensions work since so far my experience with VS Code using dev containers for an existing Docker Compose-based Django project have been 🤯 bad. As in eat your homework aka formatting mixed language (aka Django) templates in ways that break the templates so you have to disable all kinds of IDE features and then revert the auto-saved broken changes so you are at least back to your existing working project pre-VS Code, just with an IDE that has almost no useful features enabled. That is, unless you're willing to endure the pain of trying a bunch of barely maintained 3rd party extensions that themselves only have half-baked workarounds squirreled away in their own issue trackers. I did put in the time to [submit a PR](https://github.com/microsoft/vscode-docs/pull/5280) to update the relevant tutorial to be more accurate and manage expectations, so I'm contributing where I can. Just a little surprised at the out of box experience.

All that aside, I'm happy to try whatever steps you suggest for creating a reproducible case. Again, this is a clean install latest version of macOS, Docker Desktop, Visual Studio Code, etc. Thanks!

**Comment by Chuxel** [comment]
Oh do you have that experiment enabled?  That certainly could be doing something odd given its not GA. I did not test with that enabled.

**Comment by Chuxel** [comment]
Ok - now I repro'd it.  There seem to be files getting created with no permissions whatsoever.  I suspect this is a bug in the experiment. If you disable it, that should go away.

e.g.
```
ls -la ./extensions/markdown-math/node_modules/@iktakahiro/markdown-it-katex/node_modules/.bin
directory
total 0
drwxr-xr-x 3 node node 96 Apr 12 01:15 .
drwxr-xr-x 3 node node 96 Aug 13  2021 ..
---------- 1 node node  0 Apr 12 01:15 katex
```

This could wreak all kinds of havoc - so you might want to try disabling the experiment for now and seeing if that improves matters for you. If you were seeing odd rollbacks of files, privs, etc in other scenarios, this same thing could cause it.

**Comment by chrmarti** [comment]
@Chuxel Filed #6610 for the memory size.
