### ISSUE TITLE
Podman Support in Devcontainer

### ISSUE THREAD

**Issue by mattstrayer** [microsoft/vscode-remote-release#6609]
Migrating away from Docker Desktop and I'd like to use `podman` as an alternative. Trying to run remote `devcontainers`with podman continues to throw errors about Docker / Docker Compose not being installed.

**Comment by chrmarti** [comment]
Have you set your user setting to podman:
<img width="489" alt="image" src="https://user-images.githubusercontent.com/9205389/163116671-aa7c4784-548a-4b10-b42f-438ee0729918.png">

There is a second setting for Compose if needed.

**Comment by mattstrayer** [comment]
yeah, I did both of those. docker -> podman docker-compose -> podman-compose. 

Full restart. Fully wiped docker from my system. 

System Info: macos 12.latest
intel chip
iMac 2017

**Comment by chrmarti** [comment]
Could you attach the log from when the error occurs? (`F1` > `Remote-Containers: Show Containers Log`)
