### ISSUE TITLE
stopCompose not working on remote connection (ssh)

### ISSUE THREAD

**Issue by jonathanlaf** [microsoft/vscode-remote-release#6616]
### Tested versions
- VSCode:
  - Version: 1.66.2 (system setup)
  Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
  Date: 2022-04-11T07:46:01.075Z
  Electron: 17.2.0
  Chromium: 98.0.4758.109
  Node.js: 16.13.0
  V8: 9.8.177.11-electron.0
  OS: Windows_NT x64 10.0.19043
  - Version: 1.67.0-insider (user setup)
  Commit: e3f21a18e2727ac37c78159ba81f2c6ee4a982cc
  Date: 2022-04-13T05:15:45.536Z
  Electron: 17.4.0
  Chromium: 98.0.4758.141
  Node.js: 16.13.0
  V8: 9.8.177.13-electron.0
  OS: Windows_NT x64 10.0.19043
- Local OS: Windows 10 Pro | MacOS Monterey Version 12.3
- Remote OS: Ubuntu 20.04
- Remote Extension/Connection Type: SSH / Containers
- Logs: https://gist.github.com/jonathanlaf/f2be00b81605740038fea3324f66c3db

### Steps to Reproduce

1. create a fresh project in a distant machine through ssh
2. add a docker-compose
3. add a devcontainer
4. add "shutdownAction": "stopCompose", to devcontainer
    I've created a demo project "ready to use" [wp-docker-devcontainer](https://github.com/the-kraken-web-company/wp-docker-devcontainer) 
6. Open project in container
7. Close the project

### Local vs Remote
- Does this issue occur when you try this locally? 
  - I tried this localy instead of through a distant machine and it work flawlessly. 
-Does this issue occur when you try this locally and all extensions are disabled?
  - It occurs when using devcontainer through remote connection with or without other extensions installed. Localy it work with all extension as previously stated.

### Expected 
Containers present in docker-compose should be stopped when using File > Close remote connection

### Actual behavior 
Containers still running indefinitly.

**Comment by imcom** [comment]
same issue here

**Comment by chrmarti** [comment]
Tracking with https://github.com/microsoft/vscode-remote-release/issues/6056, thanks.
