### ISSUE TITLE
RemoteSSH uses windows instead of WSL2 backend

### ISSUE THREAD

**Issue by shadycuz** [microsoft/vscode-remote-release#6620]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
```
Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044
```

- OS Version: WSL2 Ubuntu

Steps to Reproduce:

1. Open vscode with the WSL2 as the backend.
2. Configure a remote SSH machine.
3. Use connect in the current window

What should happen is that vscode uses the wsl2 backend to SSH into the remote. What actually happens is that the wsl2 backend closes and the normal "windows" vscode opens and then tries to SSH into the machine, even though SSH on windows was never setup or configured. 

I'm not sure when but around 6 months to a year ago something changes in vscode that broke a lot of WSL2 functionality. 

For example when opening up a devcontainer from wsl2 backend, the wsl2 ssh-agent was proxied into the devcontainer so `git` commands would work. This broke because it started trying to use the "windows" ssh-agent, even if one wasn't started or configured. 

You used to be able to open a devcontainer from the wsl2 backend and then using the command palette "Reopen workspace locally", open the workspace back in the wsl2 backend but this was also broken because now that command opens the "windows" vscode.

And now I noticed the remote SSH functionality that used to use the wsl2 backend for SSHing, is now broken because its attempting to use the windows SSH agent even if the wsl2 backend active.

I believe all these broke from the same change, about 3-9 months ago or so.

**Comment by jabbera** [comment]
> An alternative if you have Windows 11 (and thus WSLg) _might_ be running VS Code from WSL (i.e. not using the "Remote - WSL" extension) (never tried it as I do not have Windows 11).

This isn't supported but I really want it to be. Maybe you could toss the feature request an thumbs up!

https://github.com/microsoft/vscode-remote-release/issues/6591

**Comment by phil-blain** [comment]
> > An alternative if you have Windows 11 (and thus WSLg) _might_ be running VS Code from WSL (i.e. not using the "Remote - WSL" extension) (never tried it as I do not have Windows 11).
> 
> This isn't supported but I really want it to be. Maybe you could toss the feature request an thumbs up!
> 
> #6591

This issue you are linking to seems to be about adding the ability to use the WSLg display server running on a local Windows machine to launch graphical apps on a remote system, using  the "Remote - SSH" extension in a Windows instance of VSCode to connect to said system. 

It is not what I was suggesting. I was suggesting running the _Linux_ version of VSCode instead of the Windows version of VSCode, i.e. launching "code" from a regular WSL terminal window, and then using the "Remote - SSH" extension inside that instance of VSCode to connect to a remote system (which would then use the WSL `ssh` executable, as the OP asked). This _should_ work with Windows 11 and WSLg. I was not able to get it to work in Windows 10 using the ancestral open-source Xming (haven't tried VcXsrv, it's a work machine so I can't install stuff at will).

**Comment by chrmarti** [comment]
> For example when opening up a devcontainer from wsl2 backend, the wsl2 ssh-agent was proxied into the devcontainer so `git` commands would work. This broke because it started trying to use the "windows" ssh-agent, even if one wasn't started or configured.

If the dev container runs locally (not on an SSH server), it first checks for SSH_AUTH_SOCK in WSL and then falls back to the Windows one.

If the dev container runs on an SSH server, it first checks for SSH_AUTH_SOCK on the SSH server and then falls back to the Windows one.

> You used to be able to open a devcontainer from the wsl2 backend and then using the command palette "Reopen workspace locally", open the workspace back in the wsl2 backend but this was also broken because now that command opens the "windows" vscode.

There is a "Reopen Folder in WSL" command. Is your dev container running on an SSH server?

> And now I noticed the remote SSH functionality that used to use the wsl2 backend for SSHing, is now broken because its attempting to use the windows SSH agent even if the wsl2 backend active.

This indeed changed to align with Remote-SSH. The "new" flow to work with a dev container on an SSH server is to first open a folder with Remote-SSH and then "Reopen in Container". To make this work seamlessly, Remote-Containers is using the Windows SSH client like Remote-SSH does.

**Comment by shadycuz** [comment]
@chrmarti

> If the dev container runs locally (not on an SSH server), it first checks for SSH_AUTH_SOCK in WSL and then falls back to the Windows one.

I finally fixed this, but I still feel like new behavior was introduced that broke things on my machine. I ended up going back to the devcontainer docs and it was talking about adding a program called socat and putting that in my bash profile, which did work. 

> There is a "Reopen Folder in WSL" command. Is your dev container running on an SSH server?

 My dev container is running locally using the windows docker desktop thingy. If I open visual studio code from windows, it will always open the last workspace, which is always in the WSL backend. So this is the desired behavior. But while in the WSL backend, if I open a devcontainer and then use the "Remote-WSL: Reopen Folder in WSL" command I get a notification pop up in the bottom right hand corner that says "A local or a WSL window is required for this command."

**Comment by chrmarti** [comment]
If the workspace folder is in WSL there should be a `Remote-Containers: Reopen Folder in WSL` command (note: not `Remote-WSL: ...`) while it is open in a container.

**Comment by chrmarti** [comment]
socat is no longer needed. Will update the documentation.

**Comment by shadycuz** [comment]
@chrmarti socat was the only reason it worked 🤔 , let me remove and see what happens. I will also try the very similar `Remote-Containers: Reopen Folder in WSL` command.

**Comment by shadycuz** [comment]
@chrmarti That command did work. So at least now I can go from devcontainer back to WSL <3. 

but... I uninstalled socat and now my devcontainers dont have the ability to push or pull from git. 

I think I understand why though. The docs say to use this snippet:

```
if [ -z "$SSH_AUTH_SOCK" ]; then
   # Check for a currently running instance of the agent
   RUNNING_AGENT="`ps -ax | grep 'ssh-agent -s' | grep -v grep | wc -l | tr -d '[:space:]'`"
   if [ "$RUNNING_AGENT" = "0" ]; then
        # Launch a new instance of the agent
        ssh-agent -s &> $HOME/.ssh/ssh-agent
   fi
   eval `cat $HOME/.ssh/ssh-agent`
fi
```

But this doesnt work? When I open vscode, I do not have an ssh agent running in the terminal. 

```
shadycuz-> ssh-add -l
Error connecting to agent: Connection refused
```

but if I open a new terminal directly from WSL, it works.

```
shadycuz-> ssh-add -l
The agent has no identities.
```

So why does a terminal in vscode and one opened manually in WSL work differently? 

Because vscode it setting the `SSH_AUTH_SOCK` environment variable for some reason? Probably to the windows ssh agent?

```
shadycuz-> printenv | grep SSH_
SSH_AUTH_SOCK=/tmp/ssh-RDpuEZZMGCSi/agent.315
SSH_AGENT_PID=316
```

I actually checked and the windows SSH agent is not running. So I'm not sure where these values are coming from.

**Comment by shadycuz** [comment]
Another weird this, is their is no file at `/tmp/ssh-RDpuEZZMGCSi/agent.315` but I do see the running process

**Comment by chrmarti** [comment]
Is the VS Code terminal running the shell in WSL or in the dev container? For the dev container, please append the log. (`F1` > `Remote-Containers: Show Container Log`)

**Comment by shadycuz** [comment]
The issues I am having with `ssh-agent` are in WSL. The only way I could fix was to add this to my `.bash_profile`. 

```
# these lines were required to make vscode terminal in WSL backend start with a valid ssh-agent
eval `ssh-agent -s`
ssh-add ~/.ssh/id_rsa

## share SSH creds with the vscode dev container
if [ -z "$SSH_AUTH_SOCK" ]; then
   # Check for a currently running instance of the agent
   RUNNING_AGENT="`ps -ax | grep 'ssh-agent -s' | grep -v grep | wc -l | tr -d '[:space:]'`"
   if [ "$RUNNING_AGENT" = "0" ]; then
        # Launch a new instance of the agent
        ssh-agent -s &> $HOME/.ssh/ssh-agent
   fi
   eval `cat $HOME/.ssh/ssh-agent`
fi
```

**Comment by chrmarti** [comment]
Does that indicate that the `.bash_profile` was run with an incorrect `SSH_AUTH_SOCK`? That would skip the `if` you added from the documentation.

**Comment by shadycuz** [comment]
This was a highly complex issue; it seemed like several settings were fighting each other for control. I don't remember what worked or didn't work. VScode is much more "hostile" to WSL users compared to 12-18 months ago. I have since gave up on installing Docker and VScode in windows. I now run VScode and docker in WSL and do all my work in WSL. I recommend 64GB of RAM for this setup but 32GB might work, 16GB did not work well.
