### ISSUE TITLE
[cli] desktop code is opened when running 'code' in remote terminal

### ISSUE THREAD

**Issue by callwyat** [microsoft/vscode-remote-release#6625]
- VSCode Version:   1.66.0
- Local OS Version:    macOS 11.6.4
- Remote OS Version:   macOS 12.2.1
- Remote Extension/Connection Type: SSH
- Logs: 

Steps to Reproduce:

1. Install VSCode normally on the remote machine
2. Set "code --wait" as the default editor for git on remote machine 
    a. git config --global core.editor "code --wait"
3. Connect to the remote machine via "Remote - SSH" into a folder with git SCM
4. Use a git command that will invoke the default editor
    a. git rebase -i
    b. git config --global -e
5. Notice that VSCode opened on the remote machine and not the local machine and be sad

If VSCode has not been installed on the remote machine, then the "code --wait" works as expected.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
> Notice that VSCode opened on the remote machine and not the local machine and be sad

Did you run the commands from 4 on the local or remote machine? I'd anticipate that if running on your remote machine, it would make sense to open VS Code on your remote (i.e. as when running other commands, they run against the remote, whether it's checking the version of a toolset or running code).

**Comment by callwyat** [comment]
Step 4 should be executed from the VSCode terminal on the local machine, which is connected to the remote machine by “Remote - SSH” 

On my other remote machine (Ubuntu Server 20.04), where I have not installed VSCode but instead connect with “Remote - SSH” exclusively, the editor opens in the local VSCode as expected.

**Comment by bamurtaugh** [comment]
cc @tanhakabir this sounds reasonable to me, but perhaps there are other considerations here that you could think of.

**Comment by tanhakabir** [comment]
I agree with @callwyat that the behavior he expects is what should be happening. I'm wondering if @aeschli knows what else needs to be done to ensure that the PATHs work for this scenario too?

**Comment by callwyat** [comment]
What information is needed? I thought I answered so the questions? Was the “need more info tag just not removed?

**Comment by bamurtaugh** [comment]
Reopening as it looks like the info was provided - cc @tanhakabir

**Comment by tanhakabir** [comment]
pinging @aeschli again for ideas

**Comment by aeschli** [comment]
I'll look at this for the May release.

The problem us that the login shell adds the path of the desktop vscode to the PATH environment variable first. So the remote one is shadowed by the desktop one.

The idea is to improve the desktop cli to detect that we are in a remote terminal.

**Comment by callwyat** [comment]
Thanks everyone for fixing this for me!

**Comment by joyceerhl** [comment]
Marking `verified` since this was also `on-testplan`.
