### ISSUE TITLE
Support cloning repositories using git-lfs

### ISSUE THREAD

**Issue by KenxinKun** [microsoft/vscode-remote-release#6628]
**ISSUE:** I have just tried the "Clone Repository in Container Volume..." with a repository that uses git-lfs, and although it succeeds on cloning, it fails to checkout, since the container image used to clone into the volume does not have git-lfs installed.

**ERROR DETAILS:**
```
Start: Run in container: git clone --depth 1 https://gitlab.com/redacted/redacted.git .
Cloning into '.'...
remote: Enumerating objects: 8776, done.
remote: Counting objects: 100% (8776/8776), done.
remote: Compressing objects: 100% (7421/7421), done.
remote: Total 8776 (delta 1631), reused 5689 (delta 839), pack-reused 0
Receiving objects: 100% (8776/8776), 65.24 MiB | 23.51 MiB/s, done.
Resolving deltas: 100% (1631/1631), done.
git-lfs filter-process: line 1: git-lfs: not found
fatal: the remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**PROPOSED SOLUTION:** Update the container image used by the extension to clone the repository in the volume to have git-lfs installed.

**Comment by bamurtaugh** [comment]
Thanks for filing @KenxinKun. 

> Update the container image used by the extension to clone the repository in the volume to have git-lfs installed.

Apologies if I'm misunderstanding, but the Remote-Containers extension uses the image defined in your project. It sounds like the repo you're cloning may need to include git-lfs in its dev container, rather than a change to Remote-Containers?

**Comment by KenxinKun** [comment]
For clarity, after the extension uses its OWN image ti clone the repo to the volume, it then builds/pulls MY image to set up the dev container and attaches the previous volume that has the repo cloned in it. Unfortunately since the first image from the extension does not have git-lfs, then the cloning operation fails as per the original error message posted.

**Comment by bamurtaugh** [comment]
Thanks for clarifying! I better understand the scenario now.

**Comment by monfortm** [comment]
:+1:

**Comment by chrmarti** [comment]
@monfortm Maybe check where it is installed (`which git-lfs`) and then see where that is added to the `PATH`. If this turns out to be an issue with the Dev Containers extension, could you open an new issue for it? Thanks.

**Comment by monfortm** [comment]
OK, so a bit more background. I am working on a remote machine that relies on environment modules for most software, incl. `git-lfs`. `git-lfs` is not expected to be available in the `PATH` until the module is loaded (`module load git-lfs`). I tried to load the module as part of my `.bashrc`, or directly modify & `export` a `PATH` allowing to access the needed binaries (in my case loading the module is prefered over `PATH` manipulation, though).

So this worked for the integrated terminal. i.e. the path there contains `git-lfs`. I don't really know how I can check what `PATH` the built-in git extension relies on, but I would not have expected to be different from the one in the integrated terminal.

Do you reckon I should open a dedicated issue, seems to me pretty similar to this one

Cheers,
M

**Comment by chrmarti** [comment]
Adding `git-lfs` to the temporary container running `git clone` for February.

**Comment by cguentherTUChemnitz** [comment]
> Adding `git-lfs` to the temporary container running `git clone` for February.

Why the ticket is closed, when cloning a repository in a docker volume with git-lfs hooks present is still not possible with latest vscode?
