### ISSUE TITLE
Not able to launch go code in debug mode

### ISSUE THREAD

**Issue by ycao56** [microsoft/vscode-remote-release#6631]
I am trying to debug go code on a remote host (MacOS). However, I am getting following errors when trying to launch the code in debug mode.
<img width="260" alt="image" src="https://user-images.githubusercontent.com/16092291/164084985-f7ee087e-83b2-455e-9fea-056d7d2244d0.png">
 `Run without debugging` mode works fine.
 
Below is the launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch main",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${workspaceFolder}/cmd/main.go"
        }
    ]
}
```

**Comment by tanhakabir** [comment]
Which Go extension are you using? These seems like an appropriate issue for the extension not Remote-SSH

**Comment by ycao56** [comment]
I am using delve. If I launch the same configuration directly on the host through VS code, it runs perfectly.

**Comment by ycao56** [comment]
I am wondering if additional ports need to be mapped in order to allow debugging for remote. How can I find logs for it?

**Comment by tanhakabir** [comment]
Hm there shouldn't be any additional ports you need to configure to get it to work on the remote. The same VS Code process runs on the remote. How do you know if it's a port issue?

Also have you created an issue for the extension as well? The extension author might have an idea of what's happening

**Comment by ycao56** [comment]
> Hm there shouldn't be any additional ports you need to configure to get it to work on the remote. The same VS Code process runs on the remote. How do you know if it's a port issue?
> 
> Also have you created an issue for the extension as well? The extension author might have an idea of what's happening

I do not know. Just a guess. Will also open an issue for the extension.

**Comment by ycao56** [comment]
Just found this issue https://github.com/golang/vscode-go/issues/2192
and seems to be exactly same issue but on windows

**Comment by tanhakabir** [comment]
You found the right place to ask/create issues. I'm curious what their thoughts are on this issue first since it most likely seems extension/environment related

**Comment by chriscasola** [comment]
I ran into this issue, only in remote containers as well. The solution for us was to add `"output": "/tmp/godbgbin"` to each debug launch configuration.

**Comment by tanhakabir** [comment]
Seems like an issue with the Go extension. Closing this issue for now with the workaround @chriscasola suggested
