### ISSUE TITLE
Reconnecting to remote host with ssh passphrase when "Show Login Terminal" is selected prevents entering the password

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode-remote-release#6635]
Issue Type: <b>Bug</b>
See screenshot below: terminal shows prompt for entering the ssh passphrase, but since there is a modal window, it's impossible to focus the terminal to enter it.

![Screenshot_20220420_182030](https://user-images.githubusercontent.com/8631181/164278339-0475b1fc-a499-4520-b908-767cad0de539.png)

Extension version: 0.76.1
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.16.16-zen1-1-zen
Restricted Mode: No
Remote OS version: Linux x64 5.15.32-1-lts

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics (16 x 1400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|30.84GB (2.00GB free)|
|Process Argv|--crash-reporter-id 9614dc43-c276-4d0e-94fc-c84de505d77f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma-i3|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE-i3|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: puf|
|OS|Linux x64 5.15.32-1-lts|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 3600)|
|Memory (System)|31.36GB (4.58GB free)|
|VM|0%|
</details>

**Comment by ldorigo** [comment]
Every time the connection drops (e.g. because I close my laptop) and I *re*connect, yes.

**Comment by roblourens** [comment]
We should have put up an input for your passphrase. If this is still an issue, you can try `"remote.SSH.useLocalServer": true`, or share the log from your Remote-SSH output channel. But you can also just dismiss that modal to get to the terminal.
