### ISSUE TITLE
Test: DnD of local files into remote and vice versa

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-remote-release#664]
- [x] win @mjbvz
- [x] macOS @octref
- [x] linux @bpasero

Refs: https://github.com/microsoft/vscode-remote-release/issues/627
Complexity: 2

We now support more drag and drop scenarios in the explorer. Open a remote folder (either container, wsl or ssh) and verify:
* You can drag a single file from vscode to your machine (we can not drag multiple or a folder due to a chrome limitation)
* You can drag any number of files / folders from your machine to the remote vscode explorer

Now open a local folder in vscode. And verify:
* Drop a folder inside the explorer that you get prompted if you want to copy the folder or to add it to the workspace

**Comment by bpasero** [comment]
Does not seem to work on Linux, at least the part about downloading via DND. Upload works fine.
