### ISSUE TITLE
devcontainer CLI "open" command runs two different containers and windows for the same directory but with or without trailing slash like "example" and "example/"

### ISSUE THREAD

**Issue by iamxeph** [microsoft/vscode-remote-release#6642]
devcontainer CLI "open" command runs two different container for "example" and "example/" and opens two diffrent windows. Since "devcontainer open" thinks "example" and "example/" are two different targets, containers created for "example" and "example/" use different volumes. This ends up with inconsistency of container environment, for example, even if I installed some extensions inside "example" container, those extensions doesn't exist when I open the folder with "devcontainer open example/"

"code" CLI knows "code example" and "code example/" are the same.

- VSCode Version: 1.66.2
- Local OS Version: Linux x64 5.17.3-arch1-1
- Remote OS Version: 6.0-bullseye-slim
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open "example" directory with "devcontainer open example" command
2. Open the same directory with "devcontainer open example/" command
3. Two different VSCode windows are being opened with two different docker containers for each of them

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by TylerLeonhardt** [comment]
@chrmarti did this command get renamed? I'm not seeing an `open`.

**Comment by chrmarti** [comment]
There is a built-in variant of the CLI that has that command:
- First: `F1` > `Dev Containers: Install devcontainer CLI`
- This adds the built-in `devcontainer` CLI (or `devcontainer-insiders` when you are using VS Code Insiders) to the PATH.
- Then verify that `devcontainer-insiders open <path>` no longer gives you two containers depending whether or not you use a trailing slash in the path.
