### ISSUE TITLE
Remote ssh does not set SSH_AUTH_SOCK correctly on remote machine when it reloads the window

### ISSUE THREAD

**Issue by arungrover** [microsoft/vscode-remote-release#6646]
- VSCode Version:1.66.2
- Local OS Version: OS X11.5.2
- Remote OS Version: Ubuntu 18.04.6 LTS
- Remote Extension/Connection Type: SSH
- Logs: 
Remote SSH logs - 
```
[15:58:46.760] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-MxdhscIgoC/agent.63363" "/run/user/1556817823/vscode-ssh-auth-sock-766465296"
[15:58:46.760] Using cwd: vscode-remote://ssh-remote%2Bmy-user/
[15:58:46.760] Remote extension host environment: {"SSH_AUTH_SOCK":"/run/user/1556817823/vscode-ssh-auth-sock-766465296"}
[15:58:46.762] [Forwarding server 50775] Got connection 0
```
env on machine shows - `SSH_AUTH_SOCK=/run/user/1557717823/vscode-ssh-auth-sock-343994002`

Steps to Reproduce:

1. Connect to a remote machine
2. Wait until ssh disconnects due to inactivity
3. Then vscode prompts to reload window
4. now run env on remote machine, it shows wrong SSH_AUTH_SOCK

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by arungrover** [comment]
Issue steps - 
```
my-user@dev-my-user:/remote/workspace/$ ssh-add -L
Error connecting to agent: No such file or directory
my-user@dev-my-user:echo $SSH_AUTH_SOCK 
/run/user/1556817823/vscode-ssh-auth-sock-766465296
my-user@dev-my-user: file /run/user/1556817823/vscode-ssh-auth-sock-766465296
/run/user/1557717823/vscode-ssh-auth-sock-766465296: broken symbolic link to /tmp/ssh-MxdhscIgoC/agent.63363
my-user@dev-my-user:export SSH_AUTH_SOCK=/run/user/1556817823/vscode-ssh-auth-sock-527762187
my-user@dev-my-user:ssh-add -L
< Shows the right data >
```

**Comment by qwertzguy** [comment]
I think one way to fix this would be to add something like below to https://github.com/microsoft/vscode/blob/3b63023489329145b42bc4ffc944f2ab0c04117e/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh#L119 (as well as the integrations script for other shell types):
```
# Before every command, check if there is a new active ssh-agent
# from vscode (this is needed to handle reloading the vscode window)
vscode_fix_ssh_auth_sock() {
    [ -e "$SSH_AUTH_SOCK" ] && return
    VSCODE_AUTH_SOCK=$(ls -t /run/user/1001/vscode-ssh-auth-sock* 2> /dev/null | head -n1)
    [ -e "$VSCODE_AUTH_SOCK" ] && export SSH_AUTH_SOCK=$VSCODE_AUTH_SOCK
}
```

My current workaround is to declare the above function in my ~/.bashrc and use the following to enable it:
```
if [ "$TERM_PROGRAM" == "vscode" ]; then
    trap vscode_fix_ssh_auth_sock DEBUG
fi
```

**Comment by roblourens** [comment]
See https://github.com/microsoft/vscode/issues/168202#issuecomment-1339812609
