### ISSUE TITLE
Test: Refactoring for reference implementation

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#6653]
Refs: https://github.com/microsoft/dev-container-spec/issues/9

- [x] anyOS @paulacamargo25
- [x] anyOS @weinand

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%236653%0A%0A&assignees=chrmarti)

---

Remote-Containers 0.233.0 contains a larger cleanup for https://github.com/microsoft/dev-container-spec/issues/9. Please do some random testing across the extension. Some ideas:
- Single container vs. Docker Compose vs. attach to existing container.
- Local, clone in volume, in WSL or with SSH server.
- Vary devcontainer.json options.
- Change Remote-Containers settings.

**Comment by weinand** [comment]
Could not find any issues - but I'm not the most demanding container user...

**Comment by paulacamargo25** [comment]
I couldn't find any errors either. I think the same as @weinand , I tested with ssh and docker on macOS.

**Comment by chrmarti** [comment]
No worries, there are more setups than we could possibly test, some randomized testing was all I was looking for. Thanks!
