### ISSUE TITLE
Feature request/question for an option that overrides the mounts key-pair given in the devcontainer.json

### ISSUE THREAD

**Issue by HenrikBach1** [microsoft/vscode-remote-release#6655]
Hi Code'rs

I would like to know, whether there is an option that overrides the mounts key-pair given in the devcontainer.json? 

If not, which steps should/could it take to implement this in Code?

Thank you.

/Henrik

**Comment by HenrikBach1** [comment]
I put my question in a wrong way. I'll try to reformulate it.

What I meant was, is there a command line option that overrides the mounts key-pair given in the devcontainer.json, like, i.e.:

code . --overrideMounts <new-key-pair>

Resulting in that code is using the <new-key-pair> in the running container instead of the given key-pair from the devcontainer.json.

**Comment by chrmarti** [comment]
We don't have such an option at the moment. Why do you need to override the mounts from the command line?

**Comment by HenrikBach1** [comment]
Because, I want to use DevContainer in Code to create an IDE project space independent on the devcontainer.json file, other than to build the image for a DevContainer.

**Comment by HenrikBach1** [comment]
Propably `--workdir=/projects` will suffice? I'll try it.

**Comment by HenrikBach1** [comment]
I found, that the mount key-pair in .devcontainer.json suffices for my use case.
