### ISSUE TITLE
How to reconnect SSH after network change?

### ISSUE THREAD

**Issue by duane-etagen** [microsoft/vscode-remote-release#667]
I was connected remotely over SSH via a VPN. The computer went to sleep and disconnected the VPN. VSCode prompted to "reconnect" but I dismissed that prompt, in order to reconnect at a later time.

How do I reconnect? 

I tried opening a file. VSCode seems to be waiting ... for the file to open.

I suppose closing and reopening the window would work. Seems like there should be a better solution.

**Comment by roblourens** [comment]
If you dismiss the popup, it will continue connecting in the background and show a progress notification in the lower right corner. So either it is stuck trying to reconnect, or you waited too long (8 hours) and it timed out and gave up reconnecting, (or something went wrong and reconnecting failed). After 8 hours you need to reload the window but at that point it should show you a prompt to reload.

**Comment by tschundler** [comment]
I similarly have a problem where it claims it "cannot reconnect" on network change (specifically waking up my laptop after maybe ~30min of it asleep) and prompts me to reload the window. On CLI, I have a script to auto reconnect my tmux sessions, and that works after retying and failing a couple time as the network re-establishes. So I feel it's not true that it simply retries for 8 hours.

I do get a prompt to reload the window, and doing that, it reconnects with no problem, but I'd rather avoid that every time.

Curiously, I just tried turning wifi off and back on and it did reconnect OK. So I guess it's not just on network change. Maybe the timing of "8 hours" is broken? (this is on OSX for me, connecting to Linux with key-based auth.)

**Comment by roblourens** [comment]
Actually 3 hours I think. But definitely more than 30 minutes. It would help if you can share the log from a time when it fails to reconnect. 

![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

Also the nightly version of the ssh extension might work better (uninstall the stable version first)

**Comment by tschundler** [comment]
Here's the exact error I get:
![Screen Shot 2019-06-19 at 12 28 33 PM](https://user-images.githubusercontent.com/1110025/59794565-1b260a80-928e-11e9-9b5d-b0fc0dcb54aa.png)

If I click "Cancel" to try to view the logs, I can't:
<img width="206" alt="Screen Shot 2019-06-19 at 11 10 44 AM" src="https://user-images.githubusercontent.com/1110025/59794586-2711cc80-928e-11e9-9e5d-45ee75d34ff8.png">

Incidentally after returning from lunch today, when I got the error, one window reconnected, but another (connected to a different host) failed. While this morning (after definitely > 8h), both failed.

**Comment by roblourens** [comment]
I expect that after 8h, but after a shorter period there should be a log that tells us why we think we couldn't reconnect. There also might be useful errors in developer tools (Help > Toggle Developer Tools)

**Comment by tschundler** [comment]
After being away <1h:

```
13:09:56.340 /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1552 An error occured while trying to reconnect:
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1552
13:09:56.343 /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1552 s
    at e.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3305:139)
    at Generator.next (<anonymous>)
    at r (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:34:454)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1552
13:09:56.363 /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1552 An error occured while trying to reconnect:
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1552
13:09:56.365 /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1552 s
    at e.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3305:139)
    at Generator.next (<anonymous>)
    at r (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:34:454)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1552
13:09:56.370 /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3183 Extension host terminated unexpectedly. Code:  0  Signal:  null
_onExtensionHostCrashed @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3183
```
well, obviously, s at e.<anonymous>

The error is logged from code somewhat like (pretty-printed)
```
               console.error("An error occured while trying to reconnect:"),
                                console.error(e),
                                this._permanentFailure = !0,
                                this._onDidStateChange.fire(new y),
                                this.protocol.acceptDisconnect();
```
Unfortunately clicking anywhere else in the stacktrace for `console.error(e)` won't take me to the pretty-printed parts of that code.

:| probably not so useful due to minification.

**Comment by roblourens** [comment]
That shows that the ssh tunnel is probably closing with some error that we don't recognize as recoverable.

It would help if you can share the ssh extension log from a time when it fails to reconnect. 

![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

Also the nightly version of the ssh extension might work better (uninstall the stable version first)

**Comment by tschundler** [comment]
As I pointed out above, the plugin crashes, so there's no way to get to "Remote - SSH" output as it isn't available anymore. And I linked what's in the debugging console. Are there instructions somewhere on how to install the nightly version of the extension? Or do I just get it by switching to the "insiders" version of VS Code?

**Comment by roblourens** [comment]
Sorry, right. There is another issue to not get rid of the output channels in that case.

You need vscode Insiders, then install https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly

We can still find that log on disk if needed but lets try the nightly first...
