### ISSUE TITLE
Debugging with "chrome attach" configuration does not work through remote SSH

### ISSUE THREAD

**Issue by alexpmay** [microsoft/vscode-remote-release#6671]
- VSCode Version: Version: 1.67.0-insider (Universal) and Version: 1.66.2 (Universal)
- Local OS Version: Mac OS Big Sur 11.6.5
- Remote OS Version: Ubuntu 20.04 via WSL on Windows 10 Pro Build 19043.1645
- Remote Extension/Connection Type: SSH
- Logs: [vscode-debugadapter-eaa4874c.json.gz](https://github.com/microsoft/vscode-remote-release/files/8595266/vscode-debugadapter-eaa4874c.json.gz)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Steps to Reproduce:

1. Remote: create default next app: `npx create-next-app@latest`
2. Remote: start next app: `cd my-app; npm run dev'
3. Local: Start Google Chrome with remote debugging enabled `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222`. Make sure you don't have any other instances of Google Chrome running before doing this.
4. VSCode: Create launch.json as follows:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Chrome",
            "port": 9222,
            "request": "attach",
            "url": "http://localhost:3000",
            "type": "chrome",
            "webRoot": "${workspaceFolder}",
            "trace": true
        },
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```

6. VSCode: Put a breakpoint on ./my-app/pages/index.js, ine 5
```
  4  export default function Home() {
* 5    return (
  6      <div className={styles.container}>
```

7. VSCode: Start "Attach to Chrome" debug configuration
8. Local: In Chrome goto `http://localhost:3000/`. *Debugging does not work*. Breakpoint will not be hit. Output doesn't go to debug console.

Notes:
1. "chrome launch" configuration works. VSCode: Stop debug session, start "Launch Chrome against localhost", goto `http://localhost:3000/`. Debugging works fine.
2. I uninstalled VSCode, deleted all user data, and re-installed. Only extension is Remote - SSH
3. I tried through both OpenSSH server installed on ubuntu, and using the built in window SSH server
4. This worked a few months ago. I had pinned my version of VS Code and it broke when I upgraded VS Code to the latest. Unfortunately I don't know exactly with which version of VS Code things stopped working
5. I noticed that with "chrome launch" chrome is starting with `--remote-debugging-pipe` and not `--remote-debugging-port`. I tried to start chrome manually that way, but it appears to be a setting that requires some coordination between chrome and the starting process.

**Comment by alexpmay** [comment]
I tried this on an Ubuntu box on AWS just now (so no Windows/WSL intermediary host). Same symptoms. Debugging with "attach" does not work, debugging with "launch" does work.

**Comment by connor4312** [comment]
Thanks for the issue, duplicates https://github.com/microsoft/vscode-js-debug/issues/1249
