### ISSUE TITLE
ssh_config include parsing handles "Include" but not lowercase "include"

### ISSUE THREAD

**Issue by cdleonard** [microsoft/vscode-remote-release#6673]
- VSCode Version: 1.66.2
- Local OS Version: Both Mac and Windows
- Remote OS Version: Linux
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Add an "Include" statement to your ~/.ssh/config and refresh "remote explorer"
2. Check hosts inside the included config file show up
3. Replace the header with "include" and refresh "remote explorer"
4. Check hosts no longer show up

Optional: Check that "ssh" towards the included hosts still works.

According to `man ssh_config` keywords are case insensitive but vscode seems to use case-sensitive parsing for Include directives.

**Comment by z-a-f** [comment]
Oh woops, might be a dup: #7427

But in my case neither upper nor lower cases work
