### ISSUE TITLE
VSCode attempts to reinstall remote SSH server when folder is opened from opened remote

### ISSUE THREAD

**Issue by richiksc** [microsoft/vscode-remote-release#6676]
Related to issue #6414 , which, by the way, still persists, but was auto-closed by the bot.

- VSCode Version: 1.66.2, Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
- Local OS Version: macOS Monterey 12.3.1
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: SSH
- Logs: https://gist.github.com/richiksc/f30c1b07b77b329124b1d33bf9402385

Steps to Reproduce:

1. Open a remote from the Remote Explorer sidebar by pressing the Connect To Host button
<img width="296" alt="image" src="https://user-images.githubusercontent.com/8939680/166314408-3b67fb0b-c411-487b-bef0-da0879c23d2f.png">

2. Wait for VSCode to connect and server to install
3. Click "Open" from the Get Started page and navigate to a specified directory on the remote
<img width="440" alt="image" src="https://user-images.githubusercontent.com/8939680/166314535-3f47c54e-21f0-4114-b736-abb2ea56dc00.png">
4. Observe as terminal command keeps crashing and retrying repeatedly to install the VSCode remote SSH server on a remote which already has an established open connection and installed and running server.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by bamurtaugh** [comment]
@tanhakabir should we close in favor of https://github.com/microsoft/vscode-remote-release/issues/6414, which is now open again?

**Comment by tanhakabir** [comment]
Hm this looks different than the other issue. Thanks for tagging me!

@richiksc do you have a gif or any logs in the Dev Tools with the crash? You can see Dev Tools with the command `Developer: Toggler Developer Tools`
