### ISSUE TITLE
Environment variables cannot start with vscode

### ISSUE THREAD

**Issue by DatGuyJonathan** [microsoft/vscode-remote-release#668]
- VSCode Version: 1.35.0
- Local OS Version: MacOS High Sierra
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: Docker

I have a Dockerfile like this:

```
FROM ubuntu:18.04
ENV VSCODE_REMOTE1 true
ENV VSCODEREMOTE2 true
ENV VSCODEE_REMOTE3 true
ENV TEST_ANOTHER_ENV4 true
```

After starting my project in the container, the environment variable `VSCODE_REMOTE1` is not present. The others are.

If I start the Docker container through other means (e.g. `docker run`), all environment variables exist.

Is there a rule that we can't set environment variables starting with `VSCODE_`?

**Comment by chrmarti** [comment]
We remove these before launching the terminal: https://github.com/microsoft/vscode/blob/5f70390f0d77ae95604434daaff16afa231e4f29/src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts#L233

This is by design. What would you use the variable for? /cc @Tyriar

**Comment by DatGuyJonathan** [comment]
We're just adding some environment variables for our VS Code extensions. They don't need to start with `VSCODE_`; I was just curious of the behaviour. Thanks for clarifying!
