### ISSUE TITLE
`root` owns refs in `.git/refs/remotes/origin` after first build

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode-remote-release#6684]
- VSCode Version: 1.66.2
- Local OS Version: Windows 11 21H2
- Remote OS Version: Ubuntu 22.04
- Remote Extension/Connection Type: Docker

Using Remote - Containers v0.231.6.

Steps to Reproduce:

1. Clone repository in container volume
2. `ls -la .git/refs/remotes/origin/`

Expected: Remote refs that existed during clone are owned by container user.
Actual: Remote refs that existed during clone are owned by `root`.

![image](https://user-images.githubusercontent.com/1505561/166728234-41a82e62-93a6-474a-a270-a990c8576ab9.png)

This creates a special problem when using branch names like `aaronadamsCA/foo`. If that branch was present on the remote when I cloned the repository, I can no longer publish local branch `aaronadamsCA/bar` to the remote, because I get the following error message:

```
error: update_ref failed for ref 'refs/remotes/origin/aaronadamsCA/bar': cannot lock ref 'refs/remotes/origin/aaronadamsCA/bar': Unable to create '/workspaces/***/.git/refs/remotes/origin/aaronadamsCA/bar.lock': Permission denied
```

Tag refs in `.git/refs/tags/` have the same problem too.

![image](https://user-images.githubusercontent.com/1505561/166729391-ac985453-ad52-4a86-aafa-62f3d49245f0.png)

<details><summary><code>Dockerfile</code></summary>

```
FROM mcr.microsoft.com/vscode/devcontainers/base:0.203.0-ubuntu-22.04

# Set environment variables required by Node.js install script
ENV NVM_DIR="/usr/local/share/nvm"
ENV NVM_SYMLINK_CURRENT=true \
    PATH=${NVM_DIR}/current/bin:${PATH}

# Run all commands in a single layer to minimize image size
RUN export DEBIAN_FRONTEND=noninteractive \
    # Safely add ngrok package server
    && curl -sS https://ngrok-agent.s3.amazonaws.com/ngrok.asc | gpg --dearmor > /usr/share/keyrings/ngrok-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ngrok-archive-keyring.gpg] https://ngrok-agent.s3.amazonaws.com/ bullseye main" > /etc/apt/sources.list.d/ngrok.list \
    # Install OS packages
    && apt-get update \
    && apt-get -y install --no-install-recommends dnsutils ngrok \
    # Install Node.js support (nvm, Yarn, and node-gyp dependencies)
    && bash -c "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/node-debian.sh")" -- "${NVM_DIR}" "none" \
    # Clean up to reduce image size
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*
```

</details>

<details><summary><code>devcontainer.json</code></summary>

```
{
  "name": "Nishe Web Apps",
  "image": "(redacted)", // Using image built directly from our Dockerfile
  "remoteUser": "vscode",
  "updateContentCommand": ".devcontainer/update-content.sh", // Just runs `nvm install` and `yarn install`
  "settings": {
    "remote.containers.copyGitConfig": false
  },
  "extensions": (redacted),
  "forwardPorts": (redacted),
  "portsAttributes": (redacted)
}
```

</details>

**Comment by alexanderniebuhr** [comment]
We have the same issue with the ubuntu base images.

**Comment by aaronadamsCA** [comment]
Thankfully Codespaces is unaffected, as everything in there seems to be world-writable.

**Comment by chrmarti** [comment]
We clone as root and once we know the user based on the config, we chown the cloned workspace to be owned by this user. We do this only once, but not, e.g., when you change the `"remoteUser"` in your config at a later time.

Could you check if this is still a problem and provided detailed steps to reproduce?

**Comment by aaronadamsCA** [comment]
I can no longer reproduce this using v0.327.0 of the extension.
