### ISSUE TITLE
Localize Remote SSH extension

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-remote-release#6702]
Localize all the commands and ideally logs

**Comment by TylerLeonhardt** [comment]
For your reference: https://github.com/microsoft/vscode-engineering/wiki/Extensions-Localization

**Comment by tanhakabir** [comment]
Thanks @joyceerhl! Fixing the Targets text and the `commands.showLog.title` bug. The SSH_ASKPASS setting I believe just hasn't been translated yet since it looks correct in the package.json and package.nls.json
