### ISSUE TITLE
WSL Ubuntu 22.04 LTS "$ code ." error tar is unable to read 

### ISSUE THREAD

**Issue by flyingkaktus** [microsoft/vscode-remote-release#6704]
Hello, I just installed Ubuntu 22.04 as WSL and wanted to load the VS Code Server according to instructions but I get a strange error message. How can I fix this in a beginner friendly way? The workaround [#1856](https://github.com/microsoft/vscode-remote-release/issues/1856.) does not work for me because https://packages.ubuntu.com/disco/amd64/gzip/download does not seem to exist in the year 2022.

- VSCode Version: 1.67.1
- Local OS Version: win10
- Remote OS Version: ubuntu 22.04
- Remote Extension/Connection Type: WSL
- Logs:

Updating VS Code Server to version da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Removing previous installation...
Installing VS Code Server for x64 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d)
Downloading: 100%
/usr/bin/gzip: 1: ELF: not found
/usr/bin/gzip: 3: : not found
/usr/bin/gzip: 4: Syntax error: "(" unexpected
tar: Child returned status 2
tar: Error is not recoverable: exiting now

tar is unable to read /home/deradmin/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d-1652216065.tar.gz. Either the file is corrupt or tar has an issue.
There's a known WSL issue with tar on Ubuntu 19.10.
See workaround in https://github.com/microsoft/vscode-remote-release/issues/1856.
Reload the window to initiate a new server download.

Steps to Reproduce:

1. $ code .
2.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by Louchii** [comment]
I have the same problem :(

**Comment by flyingkaktus** [comment]
for me the error was that my running wsl was version 1, by switching to wsl2 everything works fine.

wsl2 update if missing https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

**you can check your running version in the cmd:**

wsl -l -v
wsl --set-default-version 2
wsl --set-version Ubuntu-20.04 2 #will set your Ubuntu 20.04 distribution to use WSL 2

**Comment by elieyi** [comment]
https://code.visualstudio.com/docs/remote/wsl

FROM VS CODE
Alternatively, you can open a Remote WSL window directly from VS Code:

Start VS Code.
Press F1, select Remote-WSL: New Window for the default distro or Remote-WSL: New Window using Distro for a specific distro.
Use the File menu to open your folder.
If you already have a folder open, you can also use the Remote-WSL: Reopen in WSL command. You will be prompted which distro to use.

If you are in a WSL window and want to open the current input in a local window, use Remote-WSL: Reopen in Windows.

**Comment by flyingkaktus** [comment]
@elieyi when the error was not fixed, it did not work via this way either, because on Linux side the server did not operate.

**Comment by elieyi** [comment]
There was the same issue with Ubuntu 22.04 in a similar environment as @flyingkaktus.
After following the above steps on the windows part after that Ubuntu 22.04 activated automatically on VS Code. After that I wrote that "code ."  on the ubuntu side, the problem was fixed.

**Comment by jisujit** [comment]
Thank you thermalogic, 
Running the command 
echo -en '\x10' | sudo dd of=/usr/bin/gzip count=1 bs=1 conv=notrunc seek=$((0x189))

That fixed my issue
