### ISSUE TITLE
SSH problems

### ISSUE THREAD

**Issue by Manthan-Verma** [microsoft/vscode-remote-release#6707]
Vs code is unable to connect to SSH properly to systems that requires a keyboard input of characters before entering ssh  login password.

That is when we do ssh -X user@hostname  , after this step in normal shell there will be a random number display for checking if ssh connecting is human or not , after that you enter the password . 
In these systems that check for human validation , vscode is not able to connect.

**Comment by roblourens** [comment]
Does it work if you set `"remote.SSH.showLoginTerminal": true` and `"remote.SSH.useLocalServer": false`? It should pop up the terminal for you to interact with manually

**Comment by Manthan-Verma** [comment]
How to do that ?. i tried to do it in .jason file but was not able to get it properly.

**Comment by Manthan-Verma** [comment]
Yes it worked thanks!!.
One little problem , in some of the connections as soon as i login it shows " bash powershell"  and says command not found and exits .
is there any way to resolve it ??

**Comment by Manthan-Verma** [comment]
Thanks , It worked !!!.
