### ISSUE TITLE
Losing SSH connection orphans task terminals

### ISSUE THREAD

**Issue by anp** [microsoft/vscode-remote-release#6709]
Issue Type: <b>Bug</b>

1. connect to a remote host over SSH
2. Cmd+Shift+P -> "Tasks: Run task"
3. run a long-lived task
4. open a regular terminal
5. Cmd+Shift+P -> "Reload window" (or another way to force a reconnection to the server daemon, like losing SSH connectivity temporarily)
6. Observe terminal from (4) is still open but task terminals from (3) do not re-open
7. Observe (using `ps aux` or similar) that processes from (3)'s long-lived tasks are still running but have not reattached to the editor UI

I assume that the server daemon is still aware of the task processes it was running on behalf of the client, and that UI work is needed to recreate the task terminals when connecting to the remote host, but I haven't tried to debug any further than that.

Extension version: 0.80.0
VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:14:47.100Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No
Remote OS version: Linux x64 5.15.15-1rodete2-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 5|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: cloudtop|
|OS|Linux x64 5.15.15-1rodete2-amd64|
|CPUs|Intel(R) Xeon(R) CPU @ 2.00GHz (96 x 2000)|
|Memory (System)|177.07GB (13.35GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vsclangdc:30486549

```

</details>

**Comment by tanhakabir** [comment]
@Tyriar how do we rediscover spawned terminal processes from the running VS Code Server?

**Comment by anp** [comment]
Hi! I'm not sure whether anything changed here but it seems that after updating VSCode I can now reconnect to a remote session and my previous task terminals are still available. Feel free to close unless you think this is a fluke that should still be investigated?

**Comment by Tyriar** [comment]
We now support task reconnection so this should work: https://code.visualstudio.com/updates/v1_71#_reconnection-on-window-reload
