### ISSUE TITLE
no source control providers registered error on latest VS Code Insiders build

### ISSUE THREAD

**Issue by basiljoseph** [microsoft/vscode-remote-release#671]
- VSCode Version:
Version: 1.36.0-insider (user setup)
Commit: d04b5d2eb16c156e24dbf44010c315d968694bd6
Date: 2019-06-13T05:19:34.516Z
Electron: 4.2.3
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

- Remote OS Version:
CentOS Linux release 7.6.1810 (Core)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
Open any git work space with the latest insiders build and this error shows in the Source Control Tab of VS Code. 
The issue can be reproduced with previous build also (33ba72fef9099c4b58ad812585babc3fbacb9427)

This seems to occur only with remote folders.
In local folders source control is able to find Git.

**Comment by egamma** [comment]
I can also reproduce this in remote containers:
- clone and open a vscode-remote-try-* example
- switch to the SCM Viewlet

**Comment by joaomoreno** [comment]
Caused by https://github.com/microsoft/vscode/commit/13d0dad699bfc4e4529ece16dd577be98945fce1

Workaround: install a newer git (at least v2.13) on the remote machine

We will publish another release which works around this and doesn't force you to update git.

**Comment by basiljoseph** [comment]
Happy to report that the issue got fixed in the latest release 

Version: 1.36.0-insider (user setup)
Commit: 15b7c86d86319b187a5ef255c170184a8519c5af
Date: 2019-06-14T10:37:04.235Z
Electron: 4.2.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763
