### ISSUE TITLE
What is the reason for that DevContainers cannot use or end in interactive shells?

### ISSUE THREAD

**Issue by HenrikBach1** [microsoft/vscode-remote-release#6713]
Hi

What is the reason for that DevContainers (with overrideCommand set to false in the .devcontainer.json) cannot use or end in interactive shells, especially issued by `bash -i` in chained files from the `cmd` or `entrypoint` in the Dockerfile, but Docker does?

I've attached a sample project to this message that demonstrates the/my issue/problem [hello-from-entrypoint.zip](https://github.com/microsoft/vscode-remote-release/files/8684555/hello-from-entrypoint.zip) where `user-entry.sh` calls an interactive shell:
```bash
#!/usr/bin/env bash

echo "Hello from user-entry.sh: $@"

bash -i
```
Which is invoked from the Dockerfile:
```
...
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD [ "/user-entry.sh" ]
```

Thank you.

Regards
Henrik

**Comment by chrmarti** [comment]
We don't attach to stdin with `docker run`. Would you want to have the integrated terminal send key strokes to the container's process? Couldn't you use the integrated terminal with a new shell (which you get automatically when you open a new integrated terminal)?

**Comment by HenrikBach1** [comment]
Do you mean putting this in the .devcontainer.json file:
```
	,"settings": {
		"terminal.integrated.shell.linux": "/bin/bash"
	}
```
or just clicking on the + sign when popping up the problem/terminal window?

Neither work in the real use case.

**Comment by HenrikBach1** [comment]
In the real use case, I'll get a terminal windows, but without the effect of having ran through the chain of entrypoint, somehow...

**Comment by chrmarti** [comment]
`+` in the terminal tab should open a new terminal with the default shell (no need for a setting). What does that do when you try?

Why do you need to interact with what `docker run` runs?
