### ISSUE TITLE
[SSH] Improve server setup progress reporting

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-remote-release#672]
When connecting to an agent which doesn't yet have the server installed, the progress reporting is very underwhelming:

> Installing to /home/joao/.vscode-server-insiders/bin/f291714906cdcb02830b8cfe2485a3c23415b5fe...
> Downloading with wget

There's no more output until the bits are downloaded, extracted, verified, removed and (possibly) extensions are installed.

This hits especially hard on slow network connections or slower machines (raspberry pi).

It would be great to add more echos in there. Also more details (which URL is being downloaded by wget?).

cc @shanselman

**Comment by roblourens** [comment]
I have https://github.com/microsoft/vscode-remote-release/issues/530 to expose the progress bar while downloading, that should address this, I will look into that now.
