### ISSUE TITLE
"code" command is running from local /bin/code not .vscode-server/

### ISSUE THREAD

**Issue by DVCoder** [microsoft/vscode-remote-release#6733]
The Linux remote machine I'm using has VSCode installed locally and I'm using a Windows machine with VSCode and remote-ssh installed. Whenever I use the command "code <filename>" in the terminal, it opens VSCode on the Linux machine. How do I get to open it on the Windows VSCode.

**Comment by bamurtaugh** [comment]
> Whenever I use the command "code " in the terminal

Is the terminal you're using on the local Windows machine, or remote Linux machine?
