### ISSUE TITLE
Workspace name is incorrect when cloning repository in container volume

### ISSUE THREAD

**Issue by ijaouani** [microsoft/vscode-remote-release#6740]
- VSCode Version: 1.67.2
- Local OS Version: 22000.675
- Remote OS Version: v0.234.0
- Remote Extension/Connection Type: Docker

Context :
We have moved our GitLab repository which contains a devcontainer definition in a subgroup and the workspace name has changed unexpectedly. The workspace name has shift to the subgroup name instead of the repo name. After digging I find out that we can reproduce this issue with any subgroups.

I put here the steps for minimal reproduction with a public GitLab repo I have found:

Steps to Reproduce:

1. Open vscode and run the cmd remote-containers.openRepositoryInUniqueVolume

<img width="327" alt="image" src="https://user-images.githubusercontent.com/27200712/169528340-f264a009-6e15-444e-bf74-597498613cdc.png">

2. Put https://gitlab.com/xxllnc/cga-public/xxllnc-common-ground-apps

<img width="334" alt="image" src="https://user-images.githubusercontent.com/27200712/169528462-62293809-4a72-493e-a8fd-49de37009a7f.png">

3. The workspace name is the subgroup name CGA-PUBLIC instead of the git repo name xxllnc-common-ground-apps

![image](https://user-images.githubusercontent.com/27200712/169533918-661e9a76-a833-4ad9-841a-351ffce23ad1.png)

- Logs:

[78 ms] Remote-Containers 0.234.0 in VS Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5).
[77 ms] Start: Resolving Remote
[96 ms] Start: Check Docker is running
[96 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[468 ms] Server API version: 1.41
[469 ms] Start: Run: docker volume ls -q
[812 ms] Start: Run: docker volume create --label vsch.local.repository=https://gitlab.com/xxllnc/cga-public/xxllnc-common-ground-apps --label vsch.local.repository.unique=true cga-public-0836902e24ba95b0991f7a70884d6a1c

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
cc @chrmarti @lszomoru I'm able to repro that this occurs when cloning https://gitlab.com/xxllnc/cga-public/xxllnc-common-ground-apps into a container volume. The repo name appears as expected when just cloning in local VS Code.

**Comment by ijaouani** [comment]
@chrmarti, thanks for the fix but I don't see any commit link to the issue and I am curious about it.

Also I am wondering when the fix will be deployed.

**Comment by TylerLeonhardt** [comment]
@ijaouani can you try installing the latest pre-release of Remote - Containers and see if that works for you?

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/171938967-d327664a-61cf-4f99-aa4c-80b2972ed7da.png)

looks good to me
