### ISSUE TITLE
Allow installing pre-release extensions when using VSCode remotely

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode-remote-release#6743]
I have noticed that installing pre-release extensions in my VSCode Remote-SSH environment doesn't work. When I try to do it, I get an error message akin to "Cannot install extension. Requires VSCode 1.67.2." But I have that version of VSCode.

This situation isn't ideal because I want to make use of a lot of Microsoft extensions including the new `isort` and `black` extensions from the `ms-python` team.

Is there anything that could be done to fix this situation?

**Comment by tristan957** [comment]
Of note, if I go to the extension marketplace, download the extensions I want, scp them over to the remote server, and install them as VSIX, the extensions work fine.

**Comment by tanhakabir** [comment]
What version of VS Code are you running locally?

**Comment by tristan957** [comment]
@tanhakabir I am running VSCode 1.67.2 on a Windows machine. My remote server I am SSHed into is a Fedora 35 machine.

**Comment by tanhakabir** [comment]
Hm we always match the local version of VS Code to the remote one. It's odd that you're getting an error about needing a certain version.

@sandy081 any ideas?

**Comment by tristan957** [comment]
Happy to provide any logs. I know I am not the first person with this issue. I initially discussed it on Reddit when 1.67 released.

**Comment by tristan957** [comment]
After manually installing the isort and Black Formatter extensions, I now have to manually update them. Painful process.

**Comment by sandy081** [comment]
Could be a duplicate of https://github.com/microsoft/vscode/issues/146749

Can you please try our [insiders](https://code.visualstudio.com/insiders/) and see if it fixed your issue?

**Comment by tristan957** [comment]
This definitely sounds like a duplicate. Unfortunately this is a locked-down work machine, so installing VSCode Insiders is not really doable for me without jumping through hoops. I'll close the issue since it sounds like it got solved in the VSCode repo from reading that issue. Can't wait for the May release.
