### ISSUE TITLE
[BUG] Selecting Python 3.9 creates a Python 3.10-bullseye docker file

### ISSUE THREAD

**Issue by tonybaloney** [microsoft/vscode-remote-release#6749]
- VSCode Version: 1.67.2
- Local OS Version: macOS 12.4
- Remote OS Version:
- Remote Extension/Connection Type: Docker

Creating a dev container using the wizard and specifying Python 3 and then Python 3.9 will create a spec for 3.9 but a dockerfile for 3.10-bullseye

https://user-images.githubusercontent.com/1532417/169723700-b3b18e81-d667-42cc-9cd1-a0c1a31450b7.mp4

**Comment by bamurtaugh** [comment]
Thanks for opening @tonybaloney!

Although the Dockerfile displays 3.10, the devcontainer.json correctly uses 3.9 through these steps. If you run “python3 --version” in the dev container’s integrated terminal, you’ll see the container prefers the version in the devcontainer.json as the output is “Python 3.9.2”:
 
![image](https://user-images.githubusercontent.com/25310137/170116224-211da84d-b01b-458d-b6f0-13d4ccef5942.png)

I am a bit unclear why the Dockerfile added to the project is different from what we have in https://github.com/microsoft/vscode-dev-containers/blob/main/containers/python-3/.devcontainer/Dockerfile (which uses `ARG VARIANT=3-bullseye` in the Dockerfile). @chrmarti what is your thinking?

**Comment by chrmarti** [comment]
The Dockerfile is probably updated at build time of vscode-dev-containers (looking at its definition-manifest.json). When you pick version 3.9, Remote-Containers adds that as `"VARIANT": "3.9"` to the devcontainer.json, but leaves the Dockerfile unchanged (the value there is overridden by the one in the devcontainer.json).

**Comment by chrmarti** [comment]
@tonybaloney Does that clarify what you are looking at?
