### ISSUE TITLE
Consider `compose.yaml` and `compose.yml` as compose file

### ISSUE THREAD

**Issue by eitsupi** [microsoft/vscode-remote-release#6751]
The `Remote-Containers: Add Development Container Configuration Files...` command detects `docker-compose.yaml` or `docker-compose.yml` file in the workspace and generates a `devcontainer.json` file.
Similarly, `compose.yaml` and `compose.yml` must also be considered as compose file.

In the compose spec adopted by docker compose V2, the recommended file name is `compose.yaml`.
https://docs.docker.com/compose/compose-file/#compose-file

**Comment by warrenseine** [comment]
Hello @chrmarti,

Can we consider this feature request? I'm expecting it to be straightforward, and that seems to be correct path for [specification](https://github.com/compose-spec/compose-spec/blob/master/spec.md#compose-file) compliance.
