### ISSUE TITLE
 connecting with ssh timed out at first after restart vscode, after a while retry works

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode-remote-release#6756]
Version: 1.67.2 (user setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000
- Remote OS Version: CentOS 7 / Ubuntu 22.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. open a dozen remote rolder/workspaces.
2. exit vscode for updating or resume from suspend/reboot of computer.
3. open vscode to restore all the windows

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

I remember in previous versions ( maybe before 1 or 2 months ago) it used to succeed connecting at first start of vscode (takes several seconds within 1 min). But now it would show the " connecting with ssh timed out" on all windows after trying for about 10/20 seconds. But when I click retry in each window it would succeed in connecting eventually, sometimes even fail for a second time, usually on the third retry all succeed.

![image](https://user-images.githubusercontent.com/1189869/170286770-9729e392-b580-47b3-b48e-ceafc13b9dc1.png)

Or if there' s an configurable option of retry times or wait time before showing the error dialog that needs manual action it would be fine for me.

**Comment by xgdgsc** [comment]
Oh I just found the option of timeout. I will see.

**Comment by tanhakabir** [comment]
Would you be able to share your Remote SSH logs as well?

**Comment by xgdgsc** [comment]
Seems timeout config works, I will close for now. I will share logs if occurs in current much longer timeout config.
