### ISSUE TITLE
Type password only once when connecting SSH and opening folder

### ISSUE THREAD

**Issue by chadluo** [microsoft/vscode-remote-release#6757]
Currently when connecting to an SSH host you will need to type the password twice. First when connecting to the host, second when you choose to open a folder in the Explorer sidebar.

This feels unnecessary, and during the process if the password dialog lost focus by accident, your password could be exposed as you type.

Is it possible that either

1. when you are connected to the SSH host, vscode opens `~` by default and you can open a different folder later, or
2. vscode saves the password for a short period of time and reuse it when selecting the folder, although it could be vulnerable

Thanks

Version: 1.67.2
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:57.384Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.5.0

**Comment by chadluo** [comment]
Yep:

```json
{
  "remoteListeningOn": {
    "port": 39392
  },
  "osReleaseId": "centos",
  "arch": "x86_64",
  "webUiAccessToken": "",
  "sshAuthSock": "",
  "display": "",
  "tmpDir": "/run/user/500",
  "platform": "linux",
  "connectionToken": "44b6525c-0721-44e1-ac42-1638069228d2",
  "pid": 3613,
  "ipcHandlePath": "/var/folders/21/l38y56253kg8vbssrpwnnxwm0000gq/T/vscode-ssh-askpass-17c83472107cb2abb24116be59ef6f650051f78d.sock",
  "socksPort": 59751,
  "startupTime": 1653539417948
}
```

and after opening the folder (typing password 2nd time) it changes to:

```json
{
  "remoteListeningOn": {
    "port": 39392
  },
  "osReleaseId": "centos",
  "arch": "x86_64",
  "webUiAccessToken": "",
  "sshAuthSock": "",
  "display": "",
  "tmpDir": "/run/user/500",
  "platform": "linux",
  "connectionToken": "44b6525c-0721-44e1-ac42-1638069228d2",
  "pid": 3657,
  "ipcHandlePath": "/var/folders/21/l38y56253kg8vbssrpwnnxwm0000gq/T/vscode-ssh-askpass-4ab6d772c89fe1faf831ce70535d4cb7c196f6b3.sock",
  "socksPort": 59776,
  "startupTime": 1653539456048
}
```

**Comment by yinshizhang** [comment]
It seems we encountered the same problem with latest vscode remote. The difference is that OTP is requested every time I open or switch folders as I use 2FA to login. However, the ssh works well in vscode version 1.63.2 with remote-ssh version 0.70. If you are interested you can down grad to vscode 1.63.2 to see if the problem persists. @chadluo
