### ISSUE TITLE
Location of scp binary should be configurable

### ISSUE THREAD

**Issue by bachorp** [microsoft/vscode-remote-release#6758]
It is possible to use a custom executable for `ssh` (via setting `"remote.SSH.path"`) but not for `scp`. The `scp`-executable to be used must be placed in the same folder as the `ssh`-executable and named `scp`.
If one wants to set a specific `ssh`-executable to be used, one likely wants to specify the `scp`-executable as well. In my case, I needed to resort to creating a symlink at the location expected by the extension. Such a hack should not be necessary.

**Comment by roblourens** [comment]
I think it's reasonable to expect that ssh and scp are a package deal, and if not, you can fix it with a symlink.

**Comment by bachorp** [comment]
That would make sense if one would specify the folder containing the executables. Imo the current way to configure the paths is lacking / inconsistent.
I understand that this only problematic in case the executables are not named `ssh` and `scp`, respectively - arguably a low-priority edge case.
