### ISSUE TITLE
NestedOpen in {SSH | container}

### ISSUE THREAD

**Issue by hikaruna** [microsoft/vscode-remote-release#6762]
## Expected example

When
localMachin -(SSH)-> remoteMachinA -(Docker)-> remoteMachinADevContainer -(SSH) -> remoteMachinB

```
[localMachin] open vscode
[localMachin vscode] >Connect to Host remoteMahinA
[remoteMachinA vscode] >Open in Container
[remoteMachinADevContainer] > Connect to Host remoteMachinB
[remoteMachinB] >
```

Being able to achieve this kind of usability.

### Detail
I want you to be able to reopen in the {remoteSSH | devContaier}vscode.

**Comment by tanhakabir** [comment]
And what is the behavior you're seeing now? I believe this should work as you expect
