### ISSUE TITLE
Build folders unable to be removed

### ISSUE THREAD

**Issue by matthojo** [microsoft/vscode-remote-release#677]
- VSCode Version: 1.36.0 (Insider)
- Local OS Version: Windows_NT x64 10.0.18362
- Remote OS Version: Ubuntu 18.04.2 LTS
- Remote Extension/Connection: WSL

Steps to Reproduce:

1. Open folder in WSL environment
2. Try and delete a folder (locally / via shell / via VSCode) which has been 'built'
3. See error mentioned below

Does this issue occur when you try this locally (if extension is connected)?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

This only appears to affect folders which have been built - I'm personally using Next.js but haven't tried any other tools.

## Error
```
blog-frontend_1     | (node:49) UnhandledPromiseRejectionWarning: Error: ENOTEMPTY: directory not empty, rmdir '/app/.next/static/chunks'
blog-frontend_1     | (node:49) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
blog-frontend_1     | (node:49) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by egamma** [comment]
This is a known limitation of WSL 1 that has been addressed in WSL 2, pls see the known issues in the VS Code Remote WSL doc.

**Comment by matthojo** [comment]
Thank you @egamma. Sorry for the dud issue. That was the one place I didn’t look for known issues 😅

**Comment by egamma** [comment]
No problem, we are also investigating into work arounds pls see the WSL section of the remote plan https://github.com/microsoft/vscode-remote-release/issues/608
