### ISSUE TITLE
Test: Don't open desktop code when running 'code' in remote terminal

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#6774]
Refs: https://github.com/microsoft/vscode-remote-release/issues/6625

- [x] macOS @tanhakabir 
- [x] linux @aeschli 

Complexity: 3

---

- Open a Remote-SSH connection to a machine that has desktop code-insiders (on the latest insiders version, important!) installed as well
- In the remote window open the terminal
  - verify that `which code-insiders` points to the desktop code (if not, it seems your shell startup script did not prepend paths )
  - verify that running `code-insiders` does not open the desktop code, but a remote window

**Comment by tanhakabir** [comment]
Trying this in localhost everything seemed to work except the new window didn't say "localhost" in the Remote Indicator:
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/12758612/171228046-da872a02-3dea-4e3f-a312-c9272f919959.png">


I tested this by exporting a variable in the first remote window and then calling `code-insiders .` to open another hopefully remote window. I expected the second window to be remote as well.
