### ISSUE TITLE
Bash errors when openning an integrated terminal (WSL)

### ISSUE THREAD

**Issue by mhn1384** [microsoft/vscode-remote-release#6784]
- VSCode Version: 1.67.2
- Local OS Version: Windows 10
- Remote OS Version: AlmaLinux 8.6
- Remote Extension/Connection Type: WSL
- Logs: https://pastebin.com/vssU053W

Steps to Reproduce:

1. Open a wsl terminal
2. Run `code .`
3. Open an integrated terminal
4. Receive the following errors:
```
bash: which: line 1: syntax error: unexpected end of file
bash: error importing function definition for `which'
/bin/sh: which: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `which'
/bin/sh: which: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `which'
/bin/sh: which: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `which'
```

Note: This error can also happen if you where to create a wsl window using `Remote-WSL: New WSL Window` but there is an inconsistency in reproducing the error

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
Thanks for opening @mhn1384. Would you be able to test this on another WSL distro, so that we can see if it's an issue with the AlmaLinux 8.6 distro, or Remote-WSL overall on your machine?

**Comment by SebastianJ91** [comment]
I see the same error message using Oracle Linux Server release 8.5, but not on Ubuntu 20.04.4 LTS

So this could be a problem on RedHat based OS.

**Comment by bamurtaugh** [comment]
Based on https://code.visualstudio.com/docs/remote/linux, RedHat Enterprise Linux 7 is expected to work, but RedHat Enterprise Linux 6 may not. cc @aeschli
