### ISSUE TITLE
can't ssh to an IPv6 address start with fe80:

### ISSUE THREAD

**Issue by jiang1997** [microsoft/vscode-remote-release#6788]
- VSCode Version: 1.67.2
- Local OS Version: Manjaro 21.2.3 Qonos
- Remote OS Version: Linux 5.4.0-42-generic Ubuntu
- Remote Extension/Connection Type: SSH

https://superuser.com/a/237001

> quote from above link
because EVERY fully operational network interface will have an fe80: address. So, the system does not know which interface to send the traffic 

so the proper way to ssh an IPv6 address is to specify the interface as follow.
``` ssh -6 fe80::21b:21ff:fe22:e865%eth1 ```

There is no option related to the interface in ssh_config as far as I know.
I have tried `BindAddress`, but the problem remains.
```
Host fe80::e458:3ac8:dfb1:43fb
  HostName fe80::e458:3ac8:dfb1:43fb
  AddressFamily inet6
  User XXX
  BindAddress ip6-localhost
```

**Comment by tanhakabir** [comment]
Hm are you able to get the eth1 IP address by inspect the ListenAddress on your remote machine's sshd_config?
