### ISSUE TITLE
Python unittest discovery issue as non-root user

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-remote-release#6789]
_Originally from @tuncozanaydin in https://github.com/microsoft/vscode-docker/issues/3542._

VSCode correctly discovers the test cases inside the following directory structure with the auto-generated unittest config **only when I run my container as root** :
```
vsct2
├── hello
│   ├── hello.py
│   └── __init__.py
└── tests
    ├── __init__.py
    └── test_hello.py
```
.vscode/settings.json
```
{
    "python.testing.unittestArgs": [
        "-v",
        "-s",
        "./tests",
        "-p",
        "test_*.py"
    ],
    "python.testing.pytestEnabled": false,
    "python.testing.unittestEnabled": true
}
```

When I instead run the container **as a non-root user**, VSCode's testing pane lists 
remote-cli, sbin and UID.py and does not discover the unittests I wrote in `test_hello.py`

Here is my setup:
_Local:_
VScode 1.67.2 
Mac OS 11.6.6
_Remote:_
Ubuntu 16.04 container running on Arch linux

**Comment by bwateratmsft** [comment]
@chrmarti I seem to have lost my ability to transfer issues to this repo.

**Comment by chrmarti** [comment]
@joaomoreno Is there a team we can add @bwateratmsft to, so he can continue to transfer issues to this repository? (I guess we recently tightened access?)

**Comment by chrmarti** [comment]
@tuncozanaydin Could you append the container log after recreating the issue? (`F1` > `Remote-Containers: Show Container Log`)

**Comment by joaomoreno** [comment]
@bwateratmsft Can you try now?

**Comment by bwateratmsft** [comment]
@joaomoreno it doesn't look like it, `vscode-remote-release` isn't in this list:
![image](https://user-images.githubusercontent.com/36966225/173065097-e46498b9-8e59-45cd-99b9-8619da6d503c.png)

**Comment by bwateratmsft** [comment]
Yes, now it shows. Thanks @joaomoreno!
![image](https://user-images.githubusercontent.com/36966225/173068326-13457814-9ff5-46f7-b471-b01b8728dd3e.png)

**Comment by organicghemp** [comment]
> _Originally from @tuncozanaydin in [microsoft/vscode-docker#3542](https://github.com/microsoft/vscode-docker/issues/3542)._
> 
> VSCode correctly discovers the test cases inside the following directory structure with the auto-generated unittest config **only when I run my container as root** :
> 
> ```
> vsct2
> ├── hello
> │   ├── hello.py
> │   └── __init__.py
> └── tests
>     ├── __init__.py
>     └── test_hello.py
> ```
> 
> .vscode/settings.json
> 
> ```
> {
>     "python.testing.unittestArgs": [
>         "-v",
>         "-s",
>         "./tests",
>         "-p",
>         "test_*.py"
>     ],
>     "python.testing.pytestEnabled": false,
>     "python.testing.unittestEnabled": true
> }
> ```
> 
> When I instead run the container **as a non-root user**, VSCode's testing pane lists remote-cli, sbin and UID.py and does not discover the unittests I wrote in `test_hello.py`
> 
> Here is my setup: _Local:_ VScode 1.67.2 Mac OS 11.6.6 _Remote:_ Ubuntu 16.04 container running on Arch linux
