### ISSUE TITLE
Rebuild Container issue

### ISSUE THREAD

**Issue by suryaharshi** [microsoft/vscode-remote-release#6793]
ADD ISSUE DESCRIPTION HERE

Version: 1.67.2
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
Embedder: codespaces

**Comment by suryaharshi** [comment]
![1](https://user-images.githubusercontent.com/95463492/172761479-d0bab764-37d1-467e-a821-0472f816e73b.jpeg)
![2](https://user-images.githubusercontent.com/95463492/172761506-2d431a81-a952-49b8-b294-5e05be10f3b4.jpeg)

**Comment by suryaharshi** [comment]
these are the errorsi am getting

**Comment by chrmarti** [comment]
Thanks @suryaharshi. These seem to be specific to GitHub Codespaces. Could you post your issue at https://github.com/github-community/community/discussions/categories/codespaces? Thanks.
