### ISSUE TITLE
password of vscode ssh

### ISSUE THREAD

**Issue by ardeal** [microsoft/vscode-remote-release#6794]
Hi,

I am using ssh of vscode to connect to the remote computer.
I have to input password every time when the network is broken.
Is there any way to save the password so that I don't need to input it every time?

**Comment by ardeal** [comment]
@roblourens 
Thank you!

I just now checked the option `remote.SSH.useLocalServer` which is default set to True.
however, I was still experiencing the same issue (re-input passwd once the network connection is broken).

One more question:
how to share the Remote-SSH log from the output panel?

**Comment by bamurtaugh** [comment]
@ardeal Here is info on reporting issue and how you can access your logs: https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues.
