### ISSUE TITLE
SSH connection servers never close

### ISSUE THREAD

**Issue by tpfau** [microsoft/vscode-remote-release#6798]
Issue Type: <b>Bug</b>

Hi,

When connecting to a ssh server visual code opens a vscode-instance on that  server. This server is normally closed if vscode exits. However, when the connection fails, vscode will reconnect to the server but not check, whether the vscode instance it used still works. If the connection is not very stable this can lead to a large amount of vscode processes running on the remote server, which can at some point bog down that server. 
This seems to be a bug in either the vscode instances on the remote host not checking whether they are still in use, and/or the local vscode instance not checking, whether it already has an open instance on the target machine. 
It would be great, if this could be handled properly by vscode, most likely by a: remembering the instance used on a server, and b: trying to reconnect to that instance if a reconnect is neccessary, and only start a new one if the reconnection fails. 

To reproduce, you can create a connection to a remote ssh server, and unplug/plug in your network cable a few times :) 
You will notice several vscode instances on that remote server.

Extension version: 0.80.0
VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:23:40.286Z)
OS version: Linux x64 5.11.0-41-generic
Restricted Mode: No

**Comment by tanhakabir** [comment]
> but not check, whether the vscode instance it used still works.

How do you know this is the case?

> to a large amount of vscode processes running on the remote server, which can at some point bog down that server

Do you have more data about these? Like the list of processes left running?

**Comment by tpfau** [comment]
Sorry that it took so long to reply.  
Here are some jobs that are currently running. As you can see, some of them are > 50 days old, and according to the user are not in use:
```
12818 53-22:59:48 sh /home/XXXX/.vscode-server/bin/57fd6d0195bb9b9d1b49f6da5db789060795de47/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all --connection-token-file /home/XXXX/.vscode-server/.57fd6d0195bb9b9d1b49f6da5db789060795de47.token
12830 53-22:59:48 /home/XXXX/.vscode-server/bin/57fd6d0195bb9b9d1b49f6da5db789060795de47/node /home/XXXX/.vscode-server/bin/57fd6d0195bb9b9d1b49f6da5db789060795de47/out/server-main.js --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all --connection-token-file /home/XXXX/.vscode-server/.57fd6d0195bb9b9d1b49f6da5db789060795de47.token
12867 53-22:59:48 /home/XXXX/.vscode-server/bin/57fd6d0195bb9b9d1b49f6da5db789060795de47/node /home/XXXX/.vscode-server/bin/57fd6d0195bb9b9d1b49f6da5db789060795de47/out/bootstrap-fork --type=ptyHost
13034 53-22:59:47 /home/XXXX/.vscode-server/bin/57fd6d0195bb9b9d1b49f6da5db789060795de47/node /home/XXXX/.vscode-server/bin/57fd6d0195bb9b9d1b49f6da5db789060795de47/out/bootstrap-fork --type=extensionHost --transformURIs --useHostProxy=false
13190 21-02:09:52 sh /home/XXXX/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all --connection-token-file /home/XXXX/.vscode-server/.c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5.token
13202 21-02:09:52 /home/XXXX/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node /home/XXXX/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/server-main.js --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all --connection-token-file /home/XXXX/.vscode-server/.c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5.token
13293 21-02:09:52 /home/XXXX/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node /home/XXXX/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/bootstrap-fork --type=ptyHost
15438 21-02:09:50 /home/XXXX/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node /home/XXXX/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/bootstrap-fork --type=extensionHost --transformURIs --useHostProxy=false
25821 14-14:33:20 sh /home/XXXX/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all --connection-token-file /home/XXXX/.vscode-server/.4af164ea3a06f701fe3e89a2bcbb421d2026b68f.token
25833 14-14:33:20 /home/XXXX/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/node /home/XXXX/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/server-main.js --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all --connection-token-file /home/XXXX/.vscode-server/.4af164ea3a06f701fe3e89a2bcbb421d2026b68f.token
25890 14-14:33:19 /home/XXXX/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/node /home/XXXX/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/bootstrap-fork --type=ptyHost
25970 14-14:33:19 /home/XXXX/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/node /home/XXXX/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/bootstrap-fork --type=fileWatcher
26399 14-14:33:18 /home/XXXX/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/node /home/XXXX/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/bootstrap-fork --type=extensionHost --transformURIs --useHostProxy=false
```
So, these jobs are not connected, and don't die even though they are disconnected for a very long time.

**Comment by tanhakabir** [comment]
@aeschli I believe `--enable-remote-auto-shutdown` means that the server would close after 8 hours. Do you think a lingering process/execution can keep the server alive?

**Comment by aeschli** [comment]
I think 5 minutes after the last connection to an extension host has been closed.
The server logs should tell you more.
