### ISSUE TITLE
keywords in .ssh/config should be expected being case-insensitive

### ISSUE THREAD

**Issue by jose-d** [Microsoft/vscode-remote-release#68]
- VSCode Version: 1.34.0-insider
- Local OS Version: Linux 4.18.0-16-generic / ubuntu cosmic
- Remote OS Version: not relevant
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. create `.ssh/config` with multiple hosts

```
Host host
  HostName host.name.tld
  User XXX

Host host1
  Hostname host1.name.tld
  User XXX

Host host2
  Hostname host2.name.tld
  User XXX

Host host1-host
  Hostname host1.name.tld
  User XXX
  ProxyJump host

Host host2-host
  Hostname host2.name.tld
  User XXX
  ProxyJump host
```
2. click on 'remote extension' in side menu
3. just first host ("host") in my case will be shown in "connections"
4. click on 'refresh' icon
5. just one host will be shown in connections

## workaround

credits: [TomFrost](https://github.com/Microsoft/vscode-remote-release/issues/68#issuecomment-489136696)

keyword  `HostName` ignored when written as `Hostname`. 
According [manpage](https://linux.die.net/man/5/ssh_config), keywords are case-insensitive there in `ssh_config`.

## expected behavior:

all hosts from `.ssh/known_hosts` will be shown in 'connections'.

## screenshot

![Screenshot_20190503_145602](https://user-images.githubusercontent.com/7630424/57139142-b59cbe00-6db4-11e9-8362-c4a1ca00ce8a.png)

**Comment by jose-d** [comment]
edit: it seems that in the bottom left remote button all hosts are included, so perhaps it would be enough to clarify what's the role of the menu "CONNECTIONS" and what one should expect to see there.

**Comment by ikhurramraza** [comment]
Experiencing the same issue/confusion.

**Comment by TomFrost** [comment]
@jose-d I'm not on the VSCode team, but this looks like a syntax error in your file. The first entry has `HostName` with a capital N, the rest do not. I just tested this-- `Hostname` with a lowercase N does not appear in the list, but uppercase it and it does.

**Comment by jose-d** [comment]
> The first entry has `HostName` with a capital N, the rest do not.

@TomFrost, nice, you found the trigger!

in [`man ssh_config`](https://linux.die.net/man/5/ssh_config) they say:

> The possible keywords and their meanings are as follows (note that keywords are case-insensitive and arguments are case-sensitive)

So both variants are acceptable.

**Comment by TomFrost** [comment]
TIL-- I thought they were case sensitive! Great catch.
