### ISSUE TITLE
After connection to Remote Destination cannot download vscode-server-linux-x64.tar.gz with wget

### ISSUE THREAD

**Issue by mpd18** [microsoft/vscode-remote-release#680]
after connection to the remote host with remote desktop extension It is stuck on the step of downloading vscode-server-linux-x64.tar.gz with wget,

Here is the output of the extension

> 
> Installing to /home/user/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f...
> Downloading with wget
> 

and it is stuck like that until I cancel it.

When I run the command it is running myself in the terminal it downloads correctly right away

`wget -nv -O vscode-server-linux-x64.tar.gz https://update.code.visualstudio.com/commit:c7d83e57cd18f18026a8162d042843bda1bcf21f/server-linux-x64/stable`

I tried copying the tar into the directory it is trying to install it itself but when I reconnect to the remote host it deletes the tar and tries to re-download it again.

I don't think my proxy settings are incorrect since I can download it myself and the extension is trying to execute the wget as my user account so it should be the same as running in the terminal but it is stuck

**Comment by lRawd** [comment]
I ran into this same issue. I was able to grab the file when I manually entered the wget command, but not when connecting via vscode.

It turns out the vscode documentation for setting up the proxy in the .bashrc file incorrectly has HTTPS_PROXY instead of https_proxy. There was something else that was correctly setting it lowercase for me when I manually connected and ran wget.

**Comment by mpd18** [comment]
That did not work. I checked my environment variables and they were lower case. I remember doing this now because I initially had them at upper case and when I did a wget from my terminal it complained that the variables were not set correctly. So this issue is still not resolved for me.

**Comment by roblourens** [comment]
The download script is not run in an interactive shell so try setting the proxy vars near the top of the script. Some .bashrc files will bail out if they are not in an interactive session. I should mention that in the docs if that is the case here...

**Comment by doom119** [comment]
> I ran into this same issue. I was able to grab the file when I manually entered the wget command, but not when connecting via vscode.
> 
> It turns out the vscode documentation for setting up the proxy in the .bashrc file incorrectly has HTTPS_PROXY instead of https_proxy. There was something else that was correctly setting it lowercase for me when I manually connected and ran wget.

This is helpful, thank you
