### ISSUE TITLE
Remote SSH doesn't work at all!

### ISSUE THREAD

**Issue by 71walceli** [microsoft/vscode-remote-release#6801]
Just installed the extension, but nothing works. No command seems to do anything at all, except for its sidebar icon.

#### VSCode details from About Dialog
- Version: 1.66.2 (system setup)
- Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
- Date: 2022-04-11T07:46:01.075Z
- Electron: 17.2.0
- Chromium: 98.0.4758.109
- Node.js: 16.13.0
- V8: 9.8.177.11-electron.0
- OS: Windows_NT x64 10.0.19044

#### Logs:
I tried https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues to get the logs, as well as extensions, main, window and shared ones, but I really can´t get them as the commands won't even log anything out. 

When I try running any command, I get this, but only when done from F1 menu, otherwise nothing:

![image](https://user-images.githubusercontent.com/26799081/172737557-1579b1ed-8d7c-4dcf-807e-06a9f7fd3a3b.png)

#### Steps to Reproduce:

I really can't seem to understand what's going on, thus I really don't know what to describe here, except that I tried following the steps from https://code.visualstudio.com/docs/remote/ssh to no avail, having of course tried reinstalling the extension or restarting VS Code.

Does this issue occur when you try this locally?: Yes, I'm unable to even connect.
Does this issue occur when you try this locally and all extensions are disabled?: No

I know this doesn't even have logs, no steps

**Comment by tanhakabir** [comment]
What version of the extension do you have installed?

**Comment by 71walceli** [comment]
Version 11.679.326, the released one as of today.

**Comment by 71walceli** [comment]
Yes, I do. It's v0.80.0 actually.

![image](https://user-images.githubusercontent.com/26799081/173052469-5206c218-8a51-4c3b-aa32-4bf7fd261829.png)

**Comment by tanhakabir** [comment]
> Version 11.679.326, the released one as of today.

Which extension is this then?

**Comment by 71walceli** [comment]
> Yes, I do. It's v0.80.0 actually.
> 
> ![image](https://user-images.githubusercontent.com/26799081/173052469-5206c218-8a51-4c3b-aa32-4bf7fd261829.png)

It's the v0.80.0 release version, not the prerelease one of Remote - SSH.

**Comment by 71walceli** [comment]
I wonder if I broke my vscode installation of configs. Could you please tell me if there is any way I can, just like in chrome of Edge, create a new profile in order to test?

**Comment by 71walceli** [comment]
My bad! it's just as I feared

![image](https://user-images.githubusercontent.com/26799081/173481698-7df1bb81-88ec-4806-be31-e02c85c9443d.png)

After restarting VSCode (alter a reboot), everything started working fine. Sorry for reporting this in the way I did. I think you may close it now. Your help has been welcome!
