### ISSUE TITLE
"Sharing Git credentials between Windows and WSL" on Tips needs to be updated

### ISSUE THREAD

**Issue by azusa** [microsoft/vscode-remote-release#6802]
- VSCode Version: 1.67.2
- Local OS Version: Windows 10 Pro 21H2
- Remote OS Version:
- Remote Extension/Connection Type: WSL
- Logs:

Steps to Reproduce:

On [Sharing Git credentials between Windows and WSL](https://code.visualstudio.com/docs/remote/troubleshooting#_sharing-git-credentials-between-windows-and-wsl), It says to sharing Git credentials between Windows and WSL,

```
 git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-wincred.exe"
```

Git Credential Manager for Windows moves to [https://github.com/GitCredentialManager/git-credential-manager](https://github.com/GitCredentialManager/git-credential-manager), and path to execute changes.

I think it seems and it works fine:

```
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe"
```

It is related with https://github.com/GitCredentialManager/git-credential-manager/issues/692 .

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by curbengh** [comment]
or link the guide to https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-credential-manager-setup

**Comment by andreamah** [comment]
I see that the change was made in the docs, but not on the website. Is this intended? @aeschli

**Comment by sbatten** [comment]
change still needs to be deployed to the website, vnext will be merged by next week
