### ISSUE TITLE
vscode cant attach docker on a remote server

### ISSUE THREAD

**Issue by Kurt-Shiwz** [microsoft/vscode-remote-release#6803]
- VSCode Version: 1.67.2
- Local OS Version: 12.4
- Remote OS Version: CentOS Linux release 7.9.2009 (Core), 3.10.0-1127.13.1.el7.x86_64
- Remote Extension/Connection Type: SSH  and Containers（want attach container）

I want use vscode remote ssh login remote linux over jumpserver, then use docker extension to attach with vscode.

Steps to Reproduce:
1. use remote ssh login remote server over jumpserver
2. select docker extension on the left pane
`error: cant connect access /var/run/docker.sock.`
![image](https://user-images.githubusercontent.com/7554917/172897821-05d56464-e97d-48c3-a950-613b0b537f97.png)

Because jumpserver, remote ssh just can login with one user `ops`, so i try fix it with add `docker` group to `ops`
But when exce `newgrp docker` and relogin, `ops` groups dont has `docker`. then i try `newgrp ops`, it works, i can use `docker ps` without `sudo` after relogin.
![image](https://user-images.githubusercontent.com/7554917/172900101-860418e9-6b68-4f98-bd1f-08066175ac80.png)

But when i use vscode remote-ssh to login remote server, on buildin terminal cant use `docker ps`. even `groups ops` is right.
 So docker extension cant access container ?
![image](https://user-images.githubusercontent.com/7554917/172899036-3ea0dced-492b-41a6-9049-d0627923ce07.png)

**Comment by Kurt-Shiwz** [comment]
Update !!!
I quit vscode and next day i try again, it work, i can see the containers and buildin terminal can use `docker ps ` without `sodo`
![image](https://user-images.githubusercontent.com/7554917/173009624-7f08f4ea-0b33-4bb9-90c5-257e7b1ac095.png)
![image](https://user-images.githubusercontent.com/7554917/173009750-fc1518b2-534f-4179-9b36-0395ca948694.png)

when i try to `attach vscode`
![image](https://user-images.githubusercontent.com/7554917/173009869-1c3d33bb-5e48-4059-a52a-188f68c40ccb.png)
it doesnt work
![image](https://user-images.githubusercontent.com/7554917/173010791-e3353f71-f49c-4885-845d-d7d2c5719692.png)

**Comment by chrmarti** [comment]
Does the `ssh` connection require you enter a password or passphrase? (Could be https://github.com/microsoft/vscode-remote-release/issues/6670.)

How are you configuring the jumpserver? Could you share your ~/.ssh/config?

**Comment by Kurt-Shiwz** [comment]
> Does the `ssh` connection require you enter a password or passphrase? (Could be #6670.)
no password,  just `MFA auth`

> How are you configuring the jumpserver? Could you share your ~/.ssh/config?
```
Host host1
    HostName jumpserver.a.com
    User jumpserverUsername@linuxUsername@ip1
    Port 2222
```

----
i can see the files in container, and i can use `docker exec -it nme bash` into the container with buildin terminal
![image](https://user-images.githubusercontent.com/7554917/173023005-5b42c43b-71e0-4de9-849a-4f8dedfb52e1.png)

**Comment by chrmarti** [comment]
> > Does the `ssh` connection require you enter a password or passphrase? (Could be #6670.)
> > no password,  just `MFA auth`

Does MFA require you to interact with `ssh` by keyboard?

> > How are you configuring the jumpserver? Could you share your ~/.ssh/config?
> 
> ```
> Host host1
>     HostName jumpserver.a.com
>     User jumpserverUsername@linuxUsername@ip1
>     Port 2222
> ```

How are you connecting from the jumpserver to the server that has the `docker` CLI? (Or is that the same machine?)

**Comment by Kurt-Shiwz** [comment]
> Does MFA require you to interact with ssh by keyboard?

yes, after first time, new connection doesnt need.

> How are you connecting from the jumpserver to the server that has the docker CLI? (Or is that the same machine?)

i dont know how to connect from jumpserver to remote server, i think it doesnt same machine.

---
attach shell works
![image](https://user-images.githubusercontent.com/7554917/173033175-b860a870-5a9a-4464-b5a2-526d89b2e572.png)

![image](https://user-images.githubusercontent.com/7554917/173033125-9d5aecd4-c025-4dbf-8ea1-d02574be492d.png)

**Comment by chrmarti** [comment]
I guess the jumpserver just opens a shell with linuxUsername@ip1. I think `ENABLE_VSCODE_SUPPORT=true` avoids using a remote PTY (from looking at the jumpserver/koko project), could you try with `ENABLE_VSCODE_SUPPORT=false`?

**Comment by Kurt-Shiwz** [comment]
> I guess the jumpserver just opens a shell with linuxUsername@ip1. I think `ENABLE_VSCODE_SUPPORT=true` avoids using a remote PTY (from looking at the jumpserver/koko project), could you try with `ENABLE_VSCODE_SUPPORT=false`?

if i set `ENABLE_VSCODE_SUPPORT`to `false` vscode could not connect remote linux(i think), so the docker extension cant find the container maybe.
