### ISSUE TITLE
No Menu, Commands Or SSH Icon After Installing with VSIX File in Closed Network

### ISSUE THREAD

**Issue by advra** [microsoft/vscode-remote-release#6805]
Installing Remote Development Extension Pack does not show any SSH, WSL or Container menu icons on the left hand side of VSCode. Extensions show the Remote Development Extension as installed. No remote menu or icon can be found. F1 in command menu shows Install Remote Development Pack but not specific menus such as ">Remote-SSH Add New Remote Host" as it typically would.

- VSCode Version: 1.65.2
- Local OS Version: RHEL 7.9
- Remote OS Version: RHEL 7.9
- Remote Extension/Connection Type: SSH/Containers/WSL: Remote Development Pack v0.21.0
- Logs: Cannot confirm but installing extension showed no errors in the IDE a typical fail would show 

Steps to Reproduce:

1. _In machine without internet_
2. Download VSCode 1.65.2 and install
3. Download VSIX extension file for Remote Development Pack
4. Transfer files to Machine
5. Install VSCode
6. Within VSCode install the Remote Development Pack via "Install from VSIX" file option 
7. Confirm extension menu shows Remote Development pack appears under the "Installed" categories

Does this issue occur when you try this locally?: Running locally on machine (no option to connect to host)
Does this issue occur when you try this locally and all extensions are disabled?: Yes all other extensions are disabled

**Comment by chrmarti** [comment]
You also need to download and install the Remote-WSL, Remote-SSH and Remote-Containers extensions as separate VSIX files. (The extension pack only references these but does not include them in its VSIX file. You can omit the extension pack's VSIX, it does not add anything beyond pulling in the other extensions.)

**Comment by advra** [comment]
I am now able to ssh into my server but the server is offline and has no internet access either. I see the following before it failed:

> Downloading VS Code server locally...
> Terminating local server

I assume because it has no internet it cannot install the server on the host I am trying to connect to. How would I resolve this?

**Comment by advra** [comment]
I also tried to sshed into the host and removed the `~/.vscode-server` folder. When sshing again it attempted to download vs code server locally but errored with `Resolved Error: XHR Failed`

**Comment by advra** [comment]
Added a feature request #6828 which expands on this issue.
