### ISSUE TITLE
findFreePort is failing on Windows 10

### ISSUE THREAD

**Issue by lRawd** [microsoft/vscode-remote-release#681]
Issue Type: <b>Bug</b>

connect via SSH to a remote host on windows 10

Spawning tunnel with: ssh app-dev-user-N -L localhost:0:localhost:34231
Spawned SSH tunnel between local port 0 and remote port 34231
Waiting for ssh tunnel to be ready
Tunneling remote port 34231 to local port 0
Resolving "ssh-remote+app-dev-user" to "localhost:0", attempt: 1
Illegal argument: port
Tunnel(34231) stderr: Bad local forwarding specification 'localhost:0:localhost:34231'

Extension version: 0.42.2
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.16299
Fetching remote diagnostics for 'SSH: app-dev-user' failed: Illegal argument: port

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (23.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH: app-dev-user' failed: Illegal argument: port
</details>

**Comment by roblourens** [comment]
Sorry, I missed this issue. It is probably fixed by now.
