### ISSUE TITLE
Always use default context

### ISSUE THREAD

**Issue by bhack** [microsoft/vscode-remote-release#6821]
Issue Type: <b>Bug</b>

Vscode-insider now always try to open a container with the default context. 
It is going to ingore the Docker extension, command line `docker use contex <contex_name>`, DOCKER_HOST and DOCKER_CONTEXT variable in preferences (when installed the Docker extension).

Extension version: 0.239.0
VS Code version: Code - Insiders 1.69.0-insider (53130238b422606ffcd616126fb8c6c81c6e4436, 2022-06-13T11:24:41.004Z)
OS version: Linux x64 5.18.0
Restricted Mode: No

**Comment by bhack** [comment]
> Also check if your user settings have 'default' as the value for the Docker context (instead of no value).

where can I find it?

**Comment by chrmarti** [comment]
The regular user settings: Gear Icon (lower left) > Settings. Or `F1` > `Preferences: Open User Settings`.

There you can search for "docker context" and should get the setting from the Docker extension (assuming you have installed that).

**Comment by bhack** [comment]
Docker extension DOCKER_HOST and DOCKER_CONTEXT  with no value in preferences.
No DOCKER_HOST env variable set.

With the docker extension I've change the context (to a local one) and I've launched `Try Python` container and It fails:
```
2851 ms] Command failed: docker volume ls -q
[2852 ms] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2852 ms] Exit code 1
[2910 ms] Container server terminated (code: 137, signal: null).
```
As you can see ` unix:///var/run/docker.sock` is the default context not the current one I see in the extension and with `docker context ls`

**Comment by bhack** [comment]
I still see the need more info label. Do you need more info?

**Comment by bhack** [comment]
Any news on this?

**Comment by chrmarti** [comment]
E.g., on macOS I get the following and the Try Sample command works:
```
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                                  KUBERNETES ENDPOINT                ORCHESTRATOR
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                      https://127.0.0.1:6443 (default)   swarm
desktop-linux       moby                                                          unix:///Users/chrmarti/.docker/run/docker.sock                                      
dev-server2 *       moby                                                          ssh://dev-server2                                                                   swarm
```

**Comment by bhack** [comment]
On that machine is similar to your one. I have only an extra `rootless` entry for docker rootless.

Are we going to memorize or not the context for the containers memorized in the remote explorer?

**Comment by chrmarti** [comment]
The context is remembered for the entries in the Remote Explorer.

**Comment by bhack** [comment]
Have you tried to create one `dev-server2` then switch to your `desktop-linux` and try to reopen the same entry in the remote explorer?

**Comment by antdking** [comment]
attempting to open a devcontainer:
```
[4543 ms] Dev Containers 0.266.0 in VS Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b).
[4542 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[4573 ms] 
[4573 ms] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

```sh
$ docker context ls
NAME        DESCRIPTION                               DOCKER ENDPOINT                     KUBERNETES ENDPOINT               ORCHESTRATOR
default *   Current DOCKER_HOST based configuration   unix:///run/user/1000/docker.sock   https://<redacted> (default)   swarm
local                                                 unix:///run/user/1000/docker.sock   https://<redacted> (default)   swarm
Warning: DOCKER_HOST environment variable overrides the active context. To use a context, either set the global --context flag, or unset DOCKER_HOST environment variable.
$ echo $DOCKER_HOST
unix:///run/user/1000/docker.sock
$ echo $DOCKER_CONTEXT

```



> The regular user settings: Gear Icon (lower left) > Settings. Or `F1` > `Preferences: Open User Settings`.
> 
> There you can search for "docker context" and should get the setting from the Docker extension (assuming you have installed that).

This setting is non-existent.


I've managed to get devcontainers working locally (with rootless) by doing this:

- ensure the docker extension is installed
- enter `Docker contexts: use` into the command pallet (ctrl shift p)
- select the context you want
- restart vscode
Devcontainers now working.

I have no idea why vscode is not respecting the host selected context or `DOCKER_HOST`.

**Comment by chrmarti** [comment]
Probably fixed with https://github.com/microsoft/vscode-remote-release/issues/7569 where we didn't update an internal state after the context changed.
