### ISSUE TITLE
how to debug code on cluster compute node?

### ISSUE THREAD

**Issue by challow0** [microsoft/vscode-remote-release#6826]
Hi~
I encounter a problem. Before debugging how to ssh to another node? Could you please help me with it?
- I want to debug code on the cluster's compute node. So I need `ssh gpu1` before the debug command runs. I've created `launch.json` and `tasks.json`. But when I begin to debug (press `F5`), the procedure did not run as I wanted. It just stuck here. I hope you can give me some advice on the problem. Thank you very much !!!

![image](https://user-images.githubusercontent.com/46772513/173586068-eaf85719-51ff-4a79-b198-93e7109dbec5.png)

- the `launch.json` file
```JSON
{
    "version": "0.2.0",
    "configurations": [
        {
            "preLaunchTask": "sshgpu",
            "name": "Python: Current File",
            "type": "python",
            "python": "/public/home/xxxx/anaconda3/envs/de1/bin/python",
            "request": "launch",
            "program": "/public/home/xxxx/train_4.py",
            "console": "integratedTerminal",
            "justMyCode": true,
            "args": ["--gpus", "0,3,1,4,5,6"],
        }
    ]
}
```
- the `tasks.json` file
```JSON
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "sshgpu",
            "type": "shell",
            "command": "ssh gpu1",
        }
    ]
}
```

**Comment by chrmarti** [comment]
The launch config still runs locally (it does not pick up the ssh connection from the task).

You could try using the Remote-SSH extension to first connect VS Code to your SSH server and create a launch.json on the SSH server.

Also see https://code.visualstudio.com/docs/remote/ssh-tutorial for more details on that.

**Comment by challow0** [comment]
@chrmarti Thank for you your reply~ Sorry, I didn't express my problem completely. I first ssh the login node already, but I need to ssh compute node through the `ssh gpu1` command to run my code on GPUs. When I going to debug, I am just stuck on the login node and didn't ssh to compute node.
- This picture is when I ssh to the compute node named gpu1 from the login node named admin1.
![image](https://user-images.githubusercontent.com/46772513/174258609-ee07b0d7-080a-426c-8a0f-e4e681a5a59f.png)

- When I debug, still in the login node. **But I need to ssh to compute node named gpu1.**
![image](https://user-images.githubusercontent.com/46772513/174261001-77fa9b16-1ece-4671-83bf-b79cdfbc0b6c.png)

**Can you give me some advice?**

**Comment by chrmarti** [comment]
I think https://stackoverflow.com/a/66986029/7857763 is pointing in the right direction. I'll comment there.

**Comment by challow0** [comment]
@chrmarti Thanks for your help~ Wish you a good day.
