### ISSUE TITLE
How to load vscode extensions and settings after attached to kubernetes pod?

### ISSUE THREAD

**Issue by bigquant** [microsoft/vscode-remote-release#6827]
After attach to a pod in a Kubernetes cluster (Attach Visual Studio Code), how to make VSCode to load a list of extensions and settings (like defined in .devcontainer.json in working dir)?

<img width="475" alt="image" src="https://user-images.githubusercontent.com/19626072/173672925-939a4240-0bfa-4c5f-9c53-bb0b12079e0f.png">

**Comment by chrmarti** [comment]
Tracking this as a feature request in https://github.com/microsoft/vscode-remote-release/issues/5165.
