### ISSUE TITLE
Remote WSL should stop using legacy Walkthrough

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-remote-release#6833]
Looks like WSL is the last user of the legacy walkthrough format according to this comment https://github.com/microsoft/vscode/blob/24d4557352e5ea802e13c403e016b128ddf2b20f/src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStartedService.ts#L385. Is there something blocking the adoption of the new format so that we may sunset this code?

**Comment by aeschli** [comment]
@bamurtaugh Let me know if I should look into this

**Comment by bamurtaugh** [comment]
Thanks for flagging folks.

@digitarald Would you be able to help with this? I'm not sure which part of our walkthrough should be changed. Is it just the use of `.md` files?

**Comment by lramos15** [comment]
Actually investigating it appears that WSL's walkthrough looks up to date with the current schema. I'll remove the legacy fallback and check for breakages.
