### ISSUE TITLE
[Feature request] Choose different remote installation directory for container

### ISSUE THREAD

**Issue by pexcn** [microsoft/vscode-remote-release#6837]
Like https://github.com/microsoft/vscode-remote-release/issues/472 issue, I wish vscode would support custom container server paths.

This option can be named as `remote.containers.serverInstallPath`:
```json
    "remote.containers.serverInstallPath": {
        "192.168.1.10": "/opt",
        "192.168.1.20": "/opt",
        // ...
    },
```

**Comment by chrmarti** [comment]
Tracking as https://github.com/microsoft/vscode-remote-release/issues/6079.
