### ISSUE TITLE
The manage of sensitive case characters with WSL is wrong

### ISSUE THREAD

**Issue by pfebolo** [microsoft/vscode-remote-release#684]
- VSCode Version: 1.35.1
- Local OS Version: Windows 10 Pro -Build 1709 - compliation 16299.547)
- Remote OS Version: Ubuntu 16.04
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. In Ubuntu
```(bash)
p@T:~$ mkdir myFolder
p@T:~$ cd myFolder/
p@T:~/myFolder$ echo "lower case" > aaa.txt
p@T:~/myFolder$ echo "UPPER CASE" > AAA.TXT
p@T:~/myFolder$ ll
total 0
drwxrwxrwx 0 p p 4096 Jun 13 18:04 ./
drwxr-xr-x 0 p p 4096 Jun 13 18:03 ../
-rw-rw-rw- 1 p p   11 Jun 13 18:04 aaa.txt
-rw-rw-rw- 1 p p   11 Jun 13 18:04 AAA.TXT
p@T:~/myFolder$ cat aaa.txt
lower case
p@T:~/myFolder$ cat AAA.TXT
UPPER CASE
```
2. In Visual code
Conect WSL 
Open WSL folder 'myFolder' 
**>>>>Only the aaa.txt file is found<<<<**

![image](https://user-images.githubusercontent.com/5252679/59467565-619ae580-8e06-11e9-8d0a-47e494e28ec5.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/12448
