### ISSUE TITLE
`code <path> --reuse-window` changes all open WSL VSCode instances

### ISSUE THREAD

**Issue by wongjn** [microsoft/vscode-remote-release#6847]
WSL2, Linux 18.04 in Windows 10

Using `code <path> --reuse-window` in the integrated terminal will open the same `<path>` for all open VSCode windows that are connected to WSL, whereas I would expect only the current VSCode window to open the `<path>`.

**Comment by bamurtaugh** [comment]
@aeschli thoughts? I might also only expect the current VS Code window to open the path.

**Comment by aeschli** [comment]
This is https://github.com/microsoft/vscode/issues/121926
