### ISSUE TITLE
List LocalForward ports from ssh config file in Remote-SSH UI

### ISSUE THREAD

**Issue by Nadock** [microsoft/vscode-remote-release#685]
If you configure a `LocalForward` rule in your `.ssh/config` file the port is forwarded from the host to your local machine correctly, however the UI does not reflect this.

Example `.ssh/config`:
```
Host my.remote.host
    User nadock
    Hostname my.remote.host
    LocalForward {remote_port} localhost:{local_port}
```

Desired behaviour:
In Remote-SSH panel, under "FORWARDED PORTS" it should display:
```my.remote.host:{remote_port} forwarded to localhost:{local_port}```

Potentially related is the suggestion in #480 to "save forwarded ports and auto restore them after opening the project".

**Comment by pd93** [comment]
Came here to open this exact issue. This would be a really helpful feature.

I like the idea to persist the forwarded ports too as long as the persistence is via the ssh config file and not obscured by VS Code somewhere.

**Comment by Pytal** [comment]
Was this implemented?

**Comment by roblourens** [comment]
Yes, you can see it if you use VS Code Insiders + the latest version of the nightly extension.

**Comment by pd93** [comment]
@roblourens Looks good! I can see all my forwarded ports:

![image](https://user-images.githubusercontent.com/9294862/72261146-3383bb00-360c-11ea-818c-94c92779bb85.png)

However, I've noticed that clicking on the `+` icon no longer brings up the dialogue to type in a new port to forward? I have to push `F1` and select "Forward a port".

**Comment by roblourens** [comment]
It should show a text input inline like this: 
![image](https://user-images.githubusercontent.com/323878/72268963-a32b8300-35d7-11ea-997e-f59394be4189.png)

**Comment by pd93** [comment]
That's not happening for me sadly. I get the following message pop up in my developer tools console instead: 

```
  ERR TreeError [RemoteTunnels] Data tree node not found: [object Object]: Error: TreeError [RemoteTunnels] Data tree node not found: [object Object]
    at Y.getDataNode (file:///C:/Users/<user>/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1081:14)
    at Y.reveal (file:///C:/Users/<user>/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1080:577)
    at file:///C:/Users/<user>/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5000:720
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by roblourens** [comment]
Oh, could you open a new issue in https://github.com/microsoft/vscode?

**Comment by pd93** [comment]
@roblourens Sorry for the delay. New issue: https://github.com/microsoft/vscode-remote-release/issues/2159

**Comment by roblourens** [comment]
Nah that's ok, thanks

**Comment by Nadock** [comment]
Just saw this feature in the [January 2020 release notes!](https://github.com/microsoft/vscode-docs/blob/master/remote-release-notes/v1_42.md#unified-port-forwarding-experience) Thanks to everyone in `code` team that worked on this feature 👏
