### ISSUE TITLE
Remote container cannot open local folder

### ISSUE THREAD

**Issue by sara96** [microsoft/vscode-remote-release#6855]
- VSCode Version: 1.68.1
- Local OS Version: Windows 10
- Remote OS Version: 
- Remote Extension/Connection Type: WSL2
- Logs:
Command failed: C:\Program Files\Microsoft VS Code\Code.exe c: \Users\ss6821\. vscode\extensions
Ims-vscode-remote.remote-containers-@.238.2\dist\spec-node\devContainersSpecCLI.jsup--user-data-folderc
:\users\ss6821\AppData\Roaming\Code\User\globalstorage\ms-vscode-remote.remote-containers\data--workspace
-folder c: \Users\ss6821\Desktop\order-data-highjump-persister --workspace-mount-consistency cached --id-la
bel devcontainer.local_folder=c: \Users\ss6821\Desktop\order-data-highjump-persister --log-level debug --lo
-format json --config c:)Users\ss6821 \Desktop\order-data-highjump-persister\. devcontainer\devcontainer.js
on -default-user-env-probe loginInteractiveshell--mount type=volume, source=vscode, target=/vscode, externa
1=true --skip-post-create--update-remote-user-uid-defaulton--mount-workspace-git-roottrue

This happens when I try to open the local project folder in the remote container. I have stopped all the conflicting docker containers locally and it still didn't work.

**Comment by chrmarti** [comment]
Could you append the full log (`F1` > `Remote-Containers: Show Container Log`)?
