### ISSUE TITLE
Sometimes extensions are not being installed

### ISSUE THREAD

**Issue by Nefcanto** [microsoft/vscode-remote-release#6862]
- VSCode Version: 1.68.1
- Local OS Version: Ubuntu 22.04 LTS
- Local chip architecture: x86_64
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: I have no idea what this means.

I have a .NET Core container and this is my `.devcontainer/devcontainer.json` file:

```
{
	"name": "ProjectAdminApi",
	"image": "holism/dotnet-dev:latest",
	"settings": {
		"terminal.integrated.defaultProfile.linux": "bash",
		"terminal.integrated.profiles.linux": {
			"bash": {
				"path": "bash"
			}
		}
	},
	"customizations": {
		"vscode": {
			"extensions": [
				"ms-dotnettools.csharp"
			]
		}
	},
	"extensions": [
		"ms-dotnettools.csharp"
	],
	"remoteUser": "root",
	"mounts": [
		"source=projectadminapi,target=/root/.vscode-server/extensions,type=volume"
	]
}
```

And the extension specified does not get installed.

In your docs, there are two ways of specifying extensions:

1- [Inside the customization property](https://code.visualstudio.com/docs/remote/containers#_create-a-devcontainerjson-file)
2- [Top-level property](https://code.visualstudio.com/docs/remote/containers#_create-a-devcontainerjson-file)

Though I should only add it to the second place, because I'm attaching it to an existing container, I added them to make sure the problem persists.

No matter how many times I destroy my container and recreate it and then use VS Code Remove Containers to attach to it, the extension is not being installed.

What should I do?

**Comment by bamurtaugh** [comment]
Transferring as it sounds like this is an issue with the Remote-Containers extension specifically, rather than a specific dev container definition (@Nefcanto please feel free to let me know if this isn't the case).

**Comment by Nefcanto** [comment]
@bamurtaugh  in fact I checked this repo first but got confused if it's the right place or not. Thank you.

**Comment by chrmarti** [comment]
Could you append the full log after rebuilding the container? (`F1` > `Remote-Containers: Show Container Log`)
