### ISSUE TITLE
The new features for #1386 do not appear to be active in 1.68.1

### ISSUE THREAD

**Issue by PipeItToDevNull** [microsoft/vscode-remote-release#6870]
I need to specify a listen address for vscode-server to implement a functional firewall configuration.

According to #1386 and [stackoverflow](https://stackoverflow.com/questions/61693137/how-to-specify-port-for-vscode-server-when-using-remote-ssh) this should be implemented but I cannot realize the result in VSCode 1.68.1

In my client I have the following in my settings.json:

```
{
    "workbench.startupEditor": "none",
    "remote.SSH.serverPickPortsFromRange": {
        "hostname": "5000-5000"
      },
}
```

I have also tried the following which matches #1386:

```
{
    "workbench.startupEditor": "none",
    "remote.SSH.serverPickPortsFromRange": {"5000-5000"},
}
```

**Comment by tanhakabir** [comment]
Hm that does seem like the correct version. What errors do you see using the setting? It's also available through the Settings GUI

**Comment by PipeItToDevNull** [comment]
The "error" is the server not starting on the specified port.

In the settings pane I see the same settings reflected properly. I noticed "hostname" appears to be a variable which is not conveyed in the StackOverflow answer. I changed it to `*` but it did not alter the behaviour.
