### ISSUE TITLE
Schroot does no longer works when connecting from ~/.ssh/authorized_keys 

### ISSUE THREAD

**Issue by abpostelnicu** [microsoft/vscode-remote-release#6876]
- VSCode Version: 1.68.1
- Local OS Version: 21.5.0
- Remote OS Version: Debian 11 4.19.235-1
- Remote Extension/Connection Type: SSH
- Logs: https://paste.mozilla.org/Q3fVdZNX

Steps to Reproduce:

1. Connect to a SSH server where a user has a custom rule in ~/.ssh/authorized_keys similar to:
`command="/usr/bin/schroot -c my_chroot -d / -- $SSH_ORIGINAL_COMMAND", ssh-rsa prv_key`
2. The new SSH connection will be established to the original shell and not into the new chroot my_chroot

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: /No

**Comment by tanhakabir** [comment]
Just to verify when you try to connect to the same remote outside of VS Code with that rule, you do successfully connect to the new chroot?
