### ISSUE TITLE
Remote SSH not working from within VS Code terminal

### ISSUE THREAD

**Issue by zjeng** [microsoft/vscode-remote-release#688]
Issue Type: <b>Bug</b>

VSCode Version: Version 1.35.1
Local OS Version: Win 7 Enterprise
Remote OS Version: Azure Linux (ubuntu 18.04)
Remote Extension/Connection Type: SSH

I try to connect from a Win7 VS Code session to an Azure Ubuntu server via Remote SSH extension. I set up Git for Windows incl. optional Unix tools as indicated in SSH tips. "remote.SSH.showLoginTerminal" is enabled. Then I try to connect to the server and get a password login in the VS code cmd terminal. However, result is "Permission denied, please try again." If I try the same SSH connection from a standard cmd terminal it works.

Extension version: 0.42.2
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.1.7601

**Comment by roblourens** [comment]
Could you share the full log from the "Remote - SSH" output channel?

![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Comment by zjeng** [comment]
**"Remote - SSH" output:**
remote-ssh@0.42.2
Picking SSH host
Selected zjeng@137.116.221.113
Confirming that zjeng@137.116.221.113 is a valid reachable host
Running type "C:\Temp\vscode-linux-multi-line-command-137.116.221.113.sh" | ssh  "zjeng@137.116.221.113" bash to confirm the host platform
> 
> zjeng@137.116.221.113's password:
> 
> 
> Permission denied, please try again.
> zjeng@137.116.221.113's password:
> 
> 
> Permission denied, please try again.
> zjeng@137.116.221.113's password:
> 
> 
> zjeng@137.116.221.113: Permission denied (publickey,password).
> 
"uname" terminal command done
zjeng@137.116.221.113: unreachable or not Linux x86_64. (zjeng@137.116.221.113: Permission denied (publickey,password).)

**Doing "ssh zjeng@137.116.221.113" on Win cmd (not VS Code cmd) directly login me to the server.**

**Comment by roblourens** [comment]
That's interesting, I have no idea what the difference would be. We are just running the same ssh command in basically the same way. Is there some special setup in your windows cmd that is required?

**Comment by zjeng** [comment]
Got it!
My password is containing a special character "^" which is accepted by Win cmd but not VSC cmd directly. I have to type it twice and delete one afterwards. Now I'm in.

Not sure if this is a bug or just a "you need to know" issue.

**Comment by roblourens** [comment]
Huh, is that some special escape character? Are you using a non-us keyboard? @Tyriar any idea?

**Comment by zjeng** [comment]
It's ASCII code 94 = ^ ( Circumflex accent or Caret ). German keyboard.
So, yes: 
_"The command-line interpreter, cmd.exe, of Windows family of operating systems uses the caret (^) to escape reserved characters."_

Win cmd dosn't show it when it's typed ones but if another char follows. So you can type a phrase containing a Caret char as usual (but not as last character) in a passphrase.
In VSC cmd only typing Caret twice (and delete one afterwards) or Caret followed by Space works.

**Comment by Tyriar** [comment]
@roblourens would the bg terminal fix this issue as you're sending `^` directly?

**Comment by roblourens** [comment]
I don't see how that would fix it, I think I just have to replace `^` with `^ ` in passwords, or something
