### ISSUE TITLE
Potentially missing environment variables when opening an SSH remote

### ISSUE THREAD

**Issue by Poshi** [microsoft/vscode-remote-release#6881]
- VSCode Version: 1.68.1 (system setup) (30d9c6cd9483b2cc586687151bcbcd635f373630)
- Local OS Version: Windows_NT x64 10.0.19044
- Remote OS Version: CentOS Linux release 7.9.2009 (Core)
- Remote Extension/Connection Type: SSH

Hello,

I'm having an issue related to using a specific Python binary due to dynamic libraries not found.
My setup is a Windows 10 connecting to a CentOS 7 thru SSH. The remote machine (CentOS) have a quite minimal installation and the users build their own software stacks (using EasyBuild, BTW). Then, we configure our environment thru a module system (Lmod in particular) so we can access the different software easily. For reference, the system versions of some tools are: python3->3.6.8, git->1.8.3.1. The versions I installed are python3->3.10.5, git->2.36.1.
My `.bash_profile` loads my `.bashrc`, which, in turn, loads the modules for python and git (bash 4.2.46(2)-release is my login shell). As soon as I login into the machine, I can run `git` and `python3` and get the latest versions I installed.

The issue is that I cannot use my Python 3.10.5 binary because some libraries are not set in LD_LIBRARY_PATH. The Python extension tries to load them, but it returns the following message:
```
[ERROR 2022-6-1 16:4:26.597]: [Error: Command failed: /home/groups/group/user/scratch/devel/cleanup/.venv/bin/python3 /home/groups/group/user/.vscode-server/extensions/ms-python.python-2022.8.1/pythonFiles/get_output_via_markers.py /home/groups/group/user/.vscode-server/extensions/ms-python.python-2022.8.1/pythonFiles/interpreterInfo.py
/home/groups/group/user/scratch/devel/cleanup/.venv/bin/python3: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
```

I would say that the issue is related to the initialization of the environment, but surprisingly, the git command seems to be working with the latest version:
```
[2022-07-01T14:04:25.359Z] [info] Usando GIT 2.36.1 desde git
```
Also, if I open a terminal in VSCode and try to run the apparently failing Python interpreter, it works flawlessly.

So I'm not really sure of what's happening here.

I tried removing the `.bash_profile` and `.bashrc` files, ans the VSCode also complained about an old git, so it seems it is loading the initialization files. I also tried setting the LD_LIBRARY_PATH variable either thru `module load` and thru the classic `export LD_LIBRARY_PATH=...`. But for some reason, the Python interpreter is failing to load due to unable to find libraries.

Any idea of what can be happening? I tried to find logs regarding the initialization process, but I've been unable to find anything :-(

**Comment by eleanorjboyd** [comment]
Hello! I am glad to hear you solved your issue. So one good way to troubleshoot issues like this is the remote-ssh logs should print all the environment variables on connection. I would check here when debugging to see what the values are set to on startup. Secondly we have a complex install script that uses bash profiles and RCs at different times in the process. You could try switching around where you put an environment variable to see if the location it is read from has an impact. Thanks
