### ISSUE TITLE
problem connecting to ssh. While ssh works properly on terminal

### ISSUE THREAD

**Issue by abhilashreddyy** [microsoft/vscode-remote-release#6885]
Issue Type: <b>Bug</b>

I am getting this error while trying to connec to my remor\te GCP VM.
ERROR : Failed to connect to the remote extension host server (Error: Cannot read properties of undefined (reading 'replace'))

This don't happend immediately after creating a ssh in ~/.ssh/config. But after sometime like a day or something. I guess it is some kind of cache related issue

VS Code version: Code 1.68.0 (Universal) (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:00.250Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 6, 4|
|Memory (System)|16.00GB (2.41GB free)|
|Process Argv|--crash-reporter-id f45b2c45-659a-4d8b-be71-1c25b14475a9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.82.1
remote-ssh-edit|ms-|0.80.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
841h4636:30513271

```

</details>

**Comment by dbaileycamus** [comment]
FWIW - am seeing same problem myself, also on a GCP VM, same intermittency too, and same error on "reading 'replace'".

**Comment by eleanorjboyd** [comment]
Hello @dbaileycamus and @abhilashreddyy, my name is Eleanor and I'm the new Remote-SSH maintainer! Are you still experiencing this issue on the most recent version on VS Code and the extension? Additionally do you have any firewalls on your server? Sometimes these can interrupt the script transfer.
