### ISSUE TITLE
Setting `"terminal.integrated.inheritEnv": false` clobbers `$PATH` in remote SSH shell

### ISSUE THREAD

**Issue by Tyrubias** [microsoft/vscode-remote-release#6886]
Issue Type: <b>Bug</b>

My shell on both macOS and Linux are set to `zsh`. When I set `"terminal.integrated.inheritEnv": false` on my macOS system, opening the integrated terminal using the Remote SSH extension mangles the `$PATH` of the remote terminal (e.g. `/bin` and `/usr/bin` are not in `$PATH` when they should be). The behavior I observed (and relied on) in the past was that the integrated terminal should have the same `$PATH` and generally behave the same as if I manually SSH'd into the remote system. This old behavior returns if I set `"terminal.integrated.inheritEnv": true`. I can reproduce this behavior with all other extensions disabled and with the default settings (with the exception of the `inheritEnv` setting, of course).

Extension version: 0.82.1
VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:37.209Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.17.15-76051715-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.08GB free)|
|Process Argv|--crash-reporter-id c633d3d3-db12-4f51-a090-62ae82384d25|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: victors-pop-os|
|OS|Linux x64 5.17.15-76051715-generic|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|Memory (System)|62.73GB (51.94GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
pylanb8912:30520716
vsclangdc:30486549

```

</details>

**Comment by meganrogge** [comment]
I think this is expected and is probably one of the reasons we have the `terminal.integrated.inheritEnv` setting. Thoughts @Tyriar ?

**Comment by Tyriar** [comment]
I'm guessing this is the same root cause as https://github.com/microsoft/vscode-jupyter/issues/10707

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/microsoft/vscode-remote-release/issues/1671
