### ISSUE TITLE
Not parsing the port forwarded from a different container when opening in browser

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-remote-release#6895]
VS Code allows me to forward a port running in another container (docker-compose), which is an extremely useful feature, especially when running under Remote - SSH since docker-compose's `publish` won't help in such situations for containers other than the one connected in the VS Code window.

So, VS Code forwards the port correctly, and I can browse it just fine when navigating from the "PORTS" tab.

But, when I try to open a link from within VS Code, except from the "PORTS" tab, it does not match the forwarded port (to be able to auto translate to a `localhost` counterpart), and therefore, it opens the browser with the original port I asked it to open (like: `http://hass:8123` instead of `http://localhost:8123`).

I tried opening from the Terminal (`sensible-browser http://hass:8123`), but when using the `serverReadyAction` and `openExternally` in `launch.json`, the same problem triggers.

The problem stops here, but out of curiosity, if I try to `sensible-browser http://localhost:8123` from VS Code, it auto-forwards the port `dev:8123` to `localhost:8124` and open the latter in my browser. Which of course does not work, since there is nothing listening on `dev:8123`.

I see nothing wrong in the paragraph above, but the problem is that I didn't find a way to make VS Code stop auto-forwarding and translating `http://localhost:8123` to  `http://localhost:8124` (`remote.autoForwardPorts: false` is uneffective, as in its own description), because if I did, this would allow me browser with `sensible-browser http://localhost:8123` as well.

But I don't think it should be changed, as long as the bug that I reported initially gets solved.

- Refs https://github.com/blakeblackshear/frigate-hass-integration/pull/300#discussion_r914356328

- VSCode Version: 1.68.1
- Local OS Version: Windows 11 22H2
- Remote OS Version: Ubuntu 20.04 in WSL2, Debian 11 in the devcontainer.
- Remote Extension/Connection Type: Containers
- Logs: I did not find any relevant logs.

Steps to Reproduce:

`docker-compose.yml`:

```yaml
version: '3'
services:
  dev:
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-16
    user: node
    volumes:
      - .:/workspace
  hass:
    image: homeassistant/home-assistant:2022.6
```

`.devcontainer/devcontainer.json`:

```jsonc
{
  "dockerComposeFile": "../docker-compose.yml",
  "service": "dev",
  "workspaceFolder": "/workspace",
  "shutdownAction": "stopCompose",
  "forwardPorts": ["hass:8123"],
  "portsAttributes": {
    "hass:8123": {
      "label": "Home Assistant",
      "onAutoForward": "silent"
    }
  }
}
```

Video demonstrating the issue:

https://user-images.githubusercontent.com/29582865/177465562-30f6604c-e112-4563-a6fa-adc49c384d3b.mp4

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by chrmarti** [comment]
@aeschli I believe `sensible-browser http://hass:8123` should actually work?

@alexr00 Should `serverReadyAction` and `openExternally` in the launch.json map the URL according to the port forwardings?

**Comment by alexr00** [comment]
For `openExternally` (and maybe `serverReadyAction` too, I haven't looked at the implementation), I've created https://github.com/microsoft/vscode-remote-release/issues/6897.

**Comment by chrmarti** [comment]
`sensible-browser` would benefit from #6897 too (it forwards to `code` via BROWSER). Closing in favor of #6897.
