### ISSUE TITLE
Pass custom --env-file run args to docker-compose

### ISSUE THREAD

**Issue by frediy** [microsoft/vscode-remote-release#6896]
It would be nice to support runArgs parameter to call some args on docker-compose command.

For example, we could use the --env-file option on docker-compose command to specify custom .env file name where we set COMPOSE_PROJECT_NAME (it's a common use case to have a committed .env file but an ignored .env.local file that override some values).

(It might also be an envFile parameter in devcontainer.json to specify the .env file to use)

Thanks!

**Comment by chrmarti** [comment]
Tracking as https://github.com/microsoft/vscode-remote-release/issues/4885.
