### ISSUE TITLE
`code` executable is missing in PATH environment inside a Container connection, but present inside an SSH connection

### ISSUE THREAD

**Issue by MurzNN** [microsoft/vscode-remote-release#6899]
- VSCode Version: 1.68.1
- Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
- Date: 2022-06-15T02:58:26.441Z
- Electron: 17.4.7
- Chromium: 98.0.4758.141
- Node.js: 16.13.0
- V8: 9.8.177.13-electron.0
- OS: Linux x64 5.15.0-25-generic snap
- Extension Version: v0.238.3
- Remote OS Version: Debian GNU/Linux 11
- Remote Extension/Connection Type: Containers

Steps to Reproduce:

1. Connect to any container.
2. Open the Terminal.
3. Type `code` and see that it doesn't found:
```
$ code -v
bash: code: command not found
```
4. Check the `PATH` variable:
```
$ echo $PATH
~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/html/vendor/bin:/var/www/html/bin- 
```
The path like `/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/bin/remote-cli` is missing!

5. Connect to some host via SSH and check the same - the `code` binary is available:
```
$ code -v
1.68.1
30d9c6cd9483b2cc586687151bcbcd635f373630
x64
$ echo $PATH
/home/murz/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
$ which code
/home/murz/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/bin/remote-cli/code
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
This is set by the VS Code Server. Is anything in your shell startup scripts overwriting it? (E.g., `~/.profile`, `~/.bash_profile`, `~/.bashrc`.)

**Comment by MurzNN** [comment]
I've checked the startup scripts - they are pretty default, and don't overwriting the `$PATH`, only add items to it:
```
alexey_korepov@tvh-web:/var/www/html$ cat ~/.profile | grep PATH
# set PATH so it includes user's private bin if it exists
    PATH="$HOME/bin:$PATH"
alexey_korepov@tvh-web:/var/www/html$ cat ~/.bashrc  | grep PATH
alexey_korepov@tvh-web:/var/www/html$ cat ~/.bash_profile  | grep PATH
cat: /home/alexey_korepov/.bash_profile: No such file or directory
```
@chrmarti So in your environment the VS Code Server fills the $PATH right after you connect to a container?

**Comment by MurzNN** [comment]
I've found the similar issue https://github.com/microsoft/vscode-remote-release/issues/6358 and already have the version where it should be fixed, but issue is still here :(
