### ISSUE TITLE
Please add support for Linux on ARM64

### ISSUE THREAD

**Issue by telemething** [microsoft/vscode-remote-release#69]
I see another request for ARM support for PI, but I'm looking for support on other platforms. Specifically the Nvidia Jetson line-up.

**Comment by xiujunma** [comment]
I'm looking forward the support on freebsd.

**Comment by ericblade** [comment]
Hoping to eventually be able to use it for webOS here :-)

**Comment by atyshka** [comment]
Is there any reason why this restriction exists? Other remote extensions like the popular SSHFS work regardless of architecture.

**Comment by egamma** [comment]
Related #13

**Comment by egamma** [comment]
@atyshka pls see https://github.com/Microsoft/vscode-remote-release/issues/13#issuecomment-488807445.

**Comment by bsatrom** [comment]
I'll add a +100 to this. I'm doing some work on a Google Coral Dev Kit and I would love to use VSCode remote. To your question @atyshka, I am using SSH FS now and it works as a bare bones solution, but I'd love to be able to trigger debug sessions on the device via Code, handle remote dependencies/extensions, etc.

**Comment by wxdao** [comment]
Is this issue being worked on? Does the project have a roadmap or something?

**Comment by egamma** [comment]
@wxdao we just released the preview and are now observing the feedback we receive, based on the feedback we plan the future work.

**Comment by dopuskh3** [comment]
@egamma how can we try and provide feedback?

**Comment by egamma** [comment]
>@egamma how can we try and provide feedback?

Please file issues.

**Comment by benelgiac** [comment]
+100 please :)

**Comment by axiomaster** [comment]
Remote - SSH (Nightly, 2019.6.39966) add experimental support for ARM32 Raspbian.
Now docker desktop for windows support ARM64 container, could release a Remote package Night version to support ARM64 container?

**Comment by skalldri** [comment]
It really would be fantastic to be able to do development work on my NVidia Jetson Nano using this extension, but it doesn't support aarch64. Can you investigate adding is as a supported arch?

**Comment by gasparka** [comment]
Just tried the extension provided by @roblourens, first i had to uninstall all remote extensions and reload the vscode before it started working. My target is Jetson Nano and host is Arch Linux (installed visual-studio-code-insiders from AUR). 

Currently i have installed the Python extension and tested the debugging, all is working good so far :)

This is extremely useful, thanks!

**Comment by constant5** [comment]
Just installed and seems to be working well for python development on a Jetson TX2.

**Comment by roblourens** [comment]
This will be

**Comment by Wunkolo** [comment]
> I have a version of the ssh extension modified to support arm64. Would appreciate if anyone with the right hardware could install this build (remove .zip from the name and "Install Vsix") and try it out!

Just some more insight for @roblourens. Works just fine on my Raspberry Pi 3 B+ running Arch Linux.!I can get in and open my CMake projects and edit files and build them all fine.

Only issue now is that the C/C++ extension is giving me an `Architecture arm64 not supported.` error.
![image](https://user-images.githubusercontent.com/644247/63989688-1eabee00-ca96-11e9-96b8-ed186329e2c5.png)

As far as this extension goes though, it gets me in and works just fine. Thank you! 🙏

**Comment by magic-k** [comment]
Would this work with arm64 containers too? Is there a insider remote docker extension?

**Comment by roblourens** [comment]
@chrmarti?

> Would this work with arm64 containers too?

**Comment by mosilver** [comment]
It doesn't work for me, I still get error with the new nightly ssh extension:

unsupported architecture i686

**Comment by Wunkolo** [comment]
> unsupported architecture i686

This is not ARM64. i686 is the equivalent of the 32-bit Intel Pentium II which is deserving of its own issue thread(adding support for the entire 32-bit x86 platform-family).

**Comment by chrmarti** [comment]
@magic-k Remote-Containers does not support ARM64 yet. Could you open a feature request for it? Please mention how you are using it (if you can).

**Comment by TWhidden** [comment]
@roblourens  Hey Rob, tried your **0.45.6** attachment above. 

Just testing this out myself.  Ubuntu 18.04 on aarch64  (**Odroid N2**)

> [01:14:41.820] remote-ssh@0.45.6
[01:14:41.820] win32 x64
[01:14:41.820] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a224f64726f69644e......", attempt 1
[01:14:41.820] SSH Resolver called for host: OdroidN2
[01:14:41.820] Setting up SSH remote "OdroidN2"
[01:14:41.834] Using commit id "f06011ac164ae4dc8e753a3fe7f9549844d15e35" and quality "stable" for server
[01:14:41.835] Testing ssh with ssh -V
[01:14:41.873] ssh exited with code: 0
[01:14:41.873] Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[01:14:41.874] Running script with connection command: ssh -o ClearAllForwardings=true OdroidN2 bash
[01:14:41.875] Install and start server if needed
[01:14:42.067] > 
[01:14:42.067] Got some output, clearing connection timeout
[01:14:42.290] > warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
[01:14:42.554] > 
[01:14:42.758] > Running remote connection script
[01:14:42.793] > Unsupported architecture: aarch64
> 9f3132f8-6bcb-4e4d-8778-36143243e816##27##
[01:14:42.793] Received install output: 9f3132f8-6bcb-4e4d-8778-36143243e816##27##
[01:14:42.793] Unsupported architecture
[01:14:42.793] The remote server architecture is not supported
[01:14:42.794] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"ExitCode"},"measures":{"resolveAttempts":1,"exitCode":27,"retries":1}}
[01:14:42.794] ------

I'll be doing work on the Nvidia Jetson also (which looks like most people above are trying to do) but trying a bunch of hardware for this one project to see how well they compare. 

If you want access to this odroid N2 , I can forward some ports for you to poke around with.

**Comment by ditek** [comment]
Sorry if this is obvious. I tried the provided zip file on a Raspberry pi 2 (compute module) and still got "arch not supported". Same with getting the extension from VS Code Insider. Isn't that what "getting the nightly ssh extension" that Rob mentioned means?

**Comment by skalldri** [comment]
@ditek isn't the Raspberry Pi 2 an ARM32 processor, not an ARM64 (aka Aarch64) processor?

What's the output from `uname -m`?

**Comment by roblourens** [comment]
@ditek Please open an issue with the log from the Remote-SSH output channel.

**Comment by ditek** [comment]
The output of `uname -m` is `armv61`. It's not in the supported hosts list, so it's not relevant to this thread.
