### ISSUE TITLE
Cache server binary on a client machine

### ISSUE THREAD

**Issue by Yanpas** [microsoft/vscode-remote-release#6910]
- VSCode Version: 1.69
- Local OS Version: win 10
- Remote OS Version: rhel 7
- Remote Extension/Connection Type: 0.82.1
- SSH
- Logs:

Each time vs code updates it copies new server binary to each remote machine. Moreover it downloads it from internet each time! I have slow internet connection so it's tedious to wait 10 minute each time I connect to ssh.

Why not to keep server binary on client machine?

**Comment by tanhakabir** [comment]
We do keep the server binary on the machine but we delete after we saved 5. Are multiple users logging into the same remote account? And are you changing VS Code versions often?

**Comment by Yanpas** [comment]
No, I'm the only user of my local machine and one of many users of remote one. No one uses my account.

The update process is fragile, often goes into loops if some file transfer fails so I have to clear /run/user/, $HOME/.vscode-server/bin folders

**Comment by tanhakabir** [comment]
As @d84833 suggested you can try deleting the `.vscode-server` folder and killing all processes and try connecting again

**Comment by tanhakabir** [comment]
Yeah sorry I wasn't able to repro
