### ISSUE TITLE
Unauthorized tunnel creation access when starting code-server

### ISSUE THREAD

**Issue by benjaminwood** [microsoft/vscode-remote-release#6912]
- VSCode Version: `VS Code Server 20220708.1`
- Local OS Version: Ubuntu 20.04
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Server
- Logs:
```
root@d734ed1a93d9:/# wget -O- https://aka.ms/install-vscode-server/setup.sh | sh
.....
2022-07-08 16:04:10 (20.7 MB/s) - '/usr/local/bin/code-server' saved [9928760/9928760]

root@d734ed1a93d9:/# code-server

VS Code Server

*
* By using the software, you agree to the
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*

✔ Do you accept the terms in the License Agreement · yes
[2022-07-08 16:04:17] warn Error using system keyring storage: error reading keyring: Platform secure storage failure: zbus error: I/O error: No such file or directory (os error 2)
[2022-07-08 16:04:17] warn You can set up keyring storage for more secure of credentials: https://aka.ms/vscode-server-keyring
To grant access to the server, please log into ****-**** and use code https://github.com/login/device
✔ What would you like to call this machine? · modest-trogon
[2022-07-08 16:05:11] info Creating tunnel with the name: modest-trogon
[2022-07-08 16:05:12] error Could not create tunnel with name: modest-trogon
Reason: ResponseError(ResponseError { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("global.rel.tunnels.api.visualstudio.com")), port: None, path: "/api/v1/tunnels", query: Some(""), fragment: None }, status_code: 403, data: Some("{\"title\":\"Request not permitted.\",\"status\":403,\"detail\":\"Unauthorized tunnel creation access: Authenticated user does not have 'create' access scope for the default tunnel domain.\"}"), request_id: Some("****") })
```

Steps to Reproduce:

1. Run a docker image (`docker run --rm -it ubuntu:20.04 bash`)
2. Install `wget`, then install vscode-server per the docs: `wget -O- https://aka.ms/install-vscode-server/setup.sh | sh` 
3. Run code-server & accept the terms
4. Authorize with the GitHub for VS Code app & accept the default machine name
5. Boom, get the error: "Unauthorized tunnel creation access: Authenticated user does not have 'create' access scope for the default tunnel domain."

I've double checked that "GitHub for VS Code" has all the requested permissions on GitHub. Not sure where else to look.

Thanks! I'm super excited to try this out!

Does this issue occur when you try this locally?: y
Does this issue occur when you try this locally and all extensions are disabled?: y

**Comment by bamurtaugh** [comment]
Hi @benjaminwood, thanks for reporting! 

The tunneling service you'll use to securely connect to the VS Code Server is in private preview, so you'll need to request access through a [signup form](https://aka.ms/vscode-server-signup). You'll receive an email, hopefully only within a few weeks, once you can start using the service.

Based on your error here, it looks like you still need to be added to the private preview. If I'm missing anything, please let me know!

**Comment by morebrackets** [comment]
Run on your local machine: ssh -L 8000:127.0.0.1:8000 youruser@yourremoteserver.com
Then, run on remote server: code-server serve-local

The remote server will then print a URL for you to copy/paste into your local web-browser like:
Web UI available at http://localhost:8000/?tkn=secret-code-here

You're welcome!

**Comment by morebrackets** [comment]
In addition, here's a one-liner to run on your local machine:

ssh -L 8000:127.0.0.1:8000 youruser@yourremoteserver.com "code-server serve-local"
