### ISSUE TITLE
Remote Containers system error uv_os_get_passwd

### ISSUE THREAD

**Issue by mcw8d** [microsoft/vscode-remote-release#6913]
Attempting to use the 'Remote-Containers: Clone Repository' commands results in an error dialog with the following text:

> Command 'Remote-Containers: Clone Repository in Named Container Volume...' resulted in an error (A system error occurred (A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)))

This is happening with Remote-Containers version 0.241.3 and the pre-release 0.242.0. When I roll back to version 0.238.3 everything works as expected. This is affecting a number of folks on my team with similar local OS versions.

- VSCode Version: 1.69.0
- Local OS Version: Ubuntu 20.04
- Remote OS Version: CentOS-7
- Remote Extension/Connection Type: Containers
- Logs: Does not appear to get to a point where a log is generated. If I use `Remote-Containers: Show Previous Log` I get the log for when I rolled back to Remote-Containers 0.238.3 and the container started as expected.

Steps to Reproduce:

1. Press `F1` to open the command palette.
2. Select 'Remote-Containers: Clone Repository in Named Container Volume' or 'Remote-Containers: Clone Repository in Container Volume'
3. An error dialog immediately pops up

Does this issue occur when you try this locally?: Yes I removed my `docker.host` setting and it still happens

**Comment by chrmarti** [comment]
Looks like https://github.com/nodejs/node/issues/25714. We need to handle that.

**Comment by thebestnom** [comment]
Revert to 0.238.3 fixed for you too?

**Comment by thebestnom** [comment]
@chrmarti it doesn't seem to be for the same reason as it\s happens on the local vscode and not on the container (which does have $HOME and passwd (also tried to add them anyway)
I can repreduce the issue on the local vscode (not the container) in the developer tool by running `require("os").userInfo()`

**Comment by chrmarti** [comment]
https://github.com/nodejs/node/issues/25714 mentions "Docker container", but I think the same is true on the local machine depending on its configuration. (E.g., you mention LDAP, maybe your user does not have an `/etc/passwd` entry?)

**Comment by thebestnom** [comment]
@chrmarti I do have /etc/passwd (even though Im on ldap), and running `userInfo` on normal node (from different terminal) does works, somehow just vscode can't use it (tried strace but couldn't find the root cause)

**Comment by thebestnom** [comment]
![image](https://user-images.githubusercontent.com/21955247/178267993-10b2e58d-e270-43ea-b7fb-1c500dc4e48d.png)
![image](https://user-images.githubusercontent.com/21955247/178268084-3476c4a9-f2ff-4a25-b470-c00fd7d000d7.png)
@chrmarti

**Comment by thebestnom** [comment]
![image](https://user-images.githubusercontent.com/21955247/178268177-529833e6-7eb7-4cb3-a325-1f0b7c20ae56.png)
![image](https://user-images.githubusercontent.com/21955247/178268548-ea761ffc-dda1-4029-8238-8f011894e338.png)
@chrmarti

**Comment by chrmarti** [comment]
What is the Node.js version you are using? (VS Code is currently using Electron based on Node.js 16.13.2.)

**Comment by thebestnom** [comment]
@chrmarti tried them all just to be sure already 😅 but this one specifically is `v10.19.0`

**Comment by thebestnom** [comment]
![image](https://user-images.githubusercontent.com/21955247/178269156-03db7f09-5293-4e74-821c-a61002423da3.png)

**Comment by chrmarti** [comment]
@deepak1556 Do you know if Electron's `os.userInfo()` is somehow different from the one in the same Node version?

**Comment by mcw8d** [comment]
As a test, I downloaded the latest `.tar.gz` version of VSCode and that seems to work just fine. I am able to use the 0.241.3 version of Remote Containers as expected and I am also able to successfully call `require("os").userInfo();` from the developer tools in VSCode local.
When I ran into this issue I was using VSCode installed through the snap store. Could this be a sandboxing issue with the snap distribution?

**Comment by deepak1556** [comment]
@chrmarti Electron does not carry any custom patches for the `userInfo` implementation. The underlying implementation in libuv relies on `getpwuid_r` https://github.com/libuv/libuv/blob/c4d73c306b87e32acba3a77f933da72ac5604659/src/unix/core.c#L1257-L1259 which seems to be a problem for snaps. Very likely related to https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1606212

**Comment by chrmarti** [comment]
Works for me with Ubuntu 20.04 (tested running `os.userInfo()` with the Electron binary from the snap).

**Comment by thebestnom** [comment]
@chrmarti Ill remind you that both @mcw8d and I are ldap users and don't have entry in /etc/passwd

**Comment by thebestnom** [comment]
Also tested again on 1.69.1 and didn't fix

**Comment by charlesroelli** [comment]
Oops, I totally forgot to mention I use an LDAP account (not present in `/etc/passwd`) on my machine too. When I use another non-LDAP account on the same machine to launch the remote container in VS Code, then the error in https://github.com/microsoft/vscode-remote-release/issues/6913#issuecomment-1181742652 doesn't occur and everything works fine with `Remote-Containers 0.241.3`.

**Comment by thebestnom** [comment]
@chrmarti is it released?

**Comment by chrmarti** [comment]
@thebestnom It is now available with Remote-Containers 0.243.0-pre-release (switch Remote-Containers to pre-releases from the Extensions viewlet). Let me know if that fixes it, thanks!

**Comment by thebestnom** [comment]
@chrmarti Working as expected, thanks!

**Comment by mcw8d** [comment]
I got a chance to test today and it is working as expected for me as well. Thank you @chrmarti !
