### ISSUE TITLE
Not saving a new file with GitHub Codespaces causes you to lose that file

### ISSUE THREAD

**Issue by fulldecent** [microsoft/vscode-remote-release#6915]
Issue Type: <b>Bug</b>

1. Buy GitHub Codespaces
2. Open a Codespace
3. Open a new file in a new tab
4. Type important stuff in that tab
5. Go take an important phone call for 31 minutes
6. Return to desk

---

Expected:

You do not lose the important stuff in that file

---

Actual:

1. Popup dialog that you codespace is stopped and do you want to restart it 
  - only option is to START
2. Popup asking if you want to save the file
  - can't save because the workspace is stopped
  - don't save is unacceptable
  - only option is to CANCEL

These two dialogs are in a mutual infinite loop.

---

Workaround:

1. Drink caffiene
2. Use FAST twitch muscles and keyboard shortcuts to execute in quick succession:
    1. cancel popup
    2. click inside window
    3. select all text
    4. copy
3. Open some other program to save that text
4. DON"T SAVE the file

Extension version: 0.241.3
VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:46.408Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1074-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (2.29GB free)|
|Process Argv|. --crash-reporter-id 887f8733-a96a-44f8-b91e-d4df21ec6bd3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1074-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (4 x 2593)|
|Memory (System)|7.77GB (0.15GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
@fulldecent Thanks for reporting this. This is the issue tracker for the Remote-Containers extension for VS Code. Could you post your report over at the [Codespaces discussions](https://github.com/github-community/community/discussions/categories/codespaces)? Thanks!

**Comment by fulldecent** [comment]
Posted per your advice to https://github.com/github-community/community/discussions/20342.

However, I do believe this issue is specifically with the Remote-Containers extension for VS Code.

I expect this same issue is reproducible using SSH, Docker or other supported Remote-Containers setups. Just repeat the steps, but replace "take important 31 minute phone call" with "disconnect your network" or "yank the cable on your external drive".
