### ISSUE TITLE
Fail to add new SSH targets

### ISSUE THREAD

**Issue by JamyDon** [microsoft/vscode-remote-release#6916]
Issue Type: <b>Bug</b>

1. Open the remote explorer
2. Choose 'SSH Targets'
3. Click on the '+' to add a new SSH target
4. Enter the SSH connection command and press ENTER

Then it asked me to 'Edit custom SSH configuration file', with a config file 'C:\Users\username\\.ssh\config' below for me to choose. When I clicked on that file, or just pressed ENTER, the prompt window vanished and nothing happened.

As viewed on the Internet, the normal consequence should be that the config file is opened for me to edit. What's more, after entering information about the remote host, as is also said on the Internet, there should be a remote host icon in the 'SSH targets' list of the remote explorer. But after editing the config file 'C:\Users\username\\.ssh\config' artificially and saving it, again nothing happened.

I don't know how to solve the problem. This pushes me to enter the 'username@hostname' and the password each time I want to connect to a remote host via SSH, which is quite troublesome. I hope you can help me with this problem. Thank you very much!

Extension version: 0.82.1
VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (10.11GB free)|
|Process Argv|--crash-reporter-id c9861d0c-0b94-4cde-95f8-3fe1c16f0d1b|
|Screen Reader|no|
|VM|40%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30520716
vsclangdf:30486550

```

</details>

**Comment by tanhakabir** [comment]
Would you be able to share your Remote SSH logs when you try to do this? https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues

Also if you have any gif or video recording of what you see

**Comment by JamyDon** [comment]
[13:55:52.251] Log Level
[13:55:52.252] remote-ssh@0.82.1
[13:55:52.252] win32 x64

The above is all the logs after doing the four steps I listed. It seems like nothing happened when I do these steps.

![gif](https://user-images.githubusercontent.com/83012616/178419925-b822dcae-4584-4aad-a2ca-d9f2807c7fd4.gif)

As you can see from the gif, nothing happened, and no new logs were printed.

**Comment by tanhakabir** [comment]
Hm that's odd. Would you be able to run the command "Toggle Dev Tools" to see if there are any relevant logs?

**Comment by JamyDon** [comment]
Oh, I'm not good at analyzing HTML elements, and I found nothing like logs. I feel sorry for that.

I've only located the HTML of the SSH Connection Command input box:
![N0AU4{@NJRT)3B}RVN(N)TH](https://user-images.githubusercontent.com/83012616/178434415-48ce1102-a48e-40f9-807d-d7baefe1701b.png)
![@SH{FFUYSKJ3O64VE6~V{MF](https://user-images.githubusercontent.com/83012616/178434401-3bcf6e60-19dc-4965-a219-039dfdb3d8b3.png)

Maybe something helpful can be found if I could locate the HTML element <form> or JavaScript related to this input box. But I'm not good at this and don't know what to do next.

**Comment by tanhakabir** [comment]
Could you check the console tab in the devtools for logs?

**Comment by JamyDon** [comment]
Did you mean this one?
![TJ6M 15R)JNBQPR4I6)0~CS](https://user-images.githubusercontent.com/83012616/178441615-0b87bfc5-be43-4fe7-9ed1-83da072f2628.png)

There's nothing, too.

**Comment by proxseas** [comment]
I just faced this issue on Windows and this is how I resolved it: I opened my VSCode's "settings.json" and removed these 2 entries:

- "remote.SSH.configFile"
- "remote.SSH.remotePlatform"

(I think you can probably just remove the first of these 2 entries)

Then, for good measure, I restarted VSCode. After that, saving the ssh config to a new file worked correctly.

**Comment by JamyDon** [comment]
> I just faced this issue on Windows and this is how I resolved it: I opened my VSCode's "settings.json" and removed these 2 entries:
> 
> * "remote.SSH.configFile"
> * "remote.SSH.remotePlatform"
> 
> (I think you can probably just remove the first of these 2 entries)
> 
> Then, for good measure, I restarted VSCode. After that, saving the ssh config to a new file worked correctly.

Oh it works! Thank you so much!!!

**Comment by JamyDon** [comment]
> I just faced this issue on Windows and this is how I resolved it: I opened my VSCode's "settings.json" and removed these 2 entries:
> 
> * "remote.SSH.configFile"
> * "remote.SSH.remotePlatform"
> 
> (I think you can probably just remove the first of these 2 entries)
> 
> Then, for good measure, I restarted VSCode. After that, saving the ssh config to a new file worked correctly.

And yes, only the first entry must be removed. The second is not necessary.
