### ISSUE TITLE
vs code-server failed to authenticate on github when running on google cloud shell

### ISSUE THREAD

**Issue by ghalibansari** [microsoft/vscode-remote-release#6917]
warn Error using system keyring storage: error reading keyring: Platform secure storage failure: zbus error: I/O error: No such file or directory (os error 2)
warn You can set up keyring storage for more secure of credentials: https://aka.ms/vscode-server-keyring

- VSCode Version: 1.69
- Local OS Version: Linux cs-1072277301103-default 5.10.109+ #1 SMP Sat Jun 18 09:25:23 UTC 2022 x86_64 GNU/Linux
- Remote OS Version: Linux cs-1072277301103-default 5.10.109+ #1 SMP Sat Jun 18 09:25:23 UTC 2022 x86_64 GNU/Linux
- Remote Extension/Connection Type: SSH/Containers/WSL/Server: Conatiner
- Logs: warn Error using system keyring storage: error reading keyring: Platform secure storage failure: zbus error: I/O error: No such file or directory (os error 2)
warn You can set up keyring storage for more secure of credentials: https://aka.ms/vscode-server-keyring

Steps to Reproduce:

1. go to google cloud shell.
2. wget -O- https://aka.ms/install-vscode-server/setup.sh | sh
3.  code-server
4. try to authenticate on github
5. https://github.com/login/device/failure?reason=not_found

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

![image](https://user-images.githubusercontent.com/20482230/178109628-64d782b5-47f3-4936-afb5-081abc12e0fe.png)
![image](https://user-images.githubusercontent.com/20482230/178109730-97759bd6-11d6-46e4-8107-43bec05ab7e7.png)

**Comment by connor4312** [comment]
This looks like a potential Github issue. Do you get the "not found" error consistently?

**Comment by ghalibansari** [comment]
yeah, I tried several times still happening, this "not found" page comes after I fill the verification code

**Comment by ghalibansari** [comment]
VSCode Version: 1.70 is likely to fix it.
