### ISSUE TITLE
VSCode Server running in serve-local mode, a lot CORS warning from unpkg and settings sync

### ISSUE THREAD

**Issue by karuboniru** [microsoft/vscode-remote-release#6924]
- VSCode Version:
- Local OS Version: N/A
- Remote OS Version: 1.69.0
- Remote Extension/Connection Type: Server
- Logs: 

Steps to Reproduce:

1.  start code-server `code-server serve-local --without-connection-token --port 3000`
2.  use nginx to publish the code-server instance (not needed, a exposed directly to LAN server also suffer from this)
3.  use Browser to open, e.g. Firefox/Chrome, press <F12>, see console 

Get errors like 
```
Access to fetch at 'https://www.vscode-unpkg.net/_lp/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/1.69.0/zh-CN/vscode/vs/workbench/workbench.web.main/' from origin 'https://<server.hostname.ltd>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

maybe set no-cors on code side or set CORS policy at https://www.vscode-unpkg.net/ is needed? 

And also, I am getting `Error loading webview: Error: Could not register service workers: SecurityError: The operation is insecure..` from vscode, is this related to CORS problem?

**Comment by ZauberNerd** [comment]
I'm also seeing CORS issues, but mine are related to settings sync:
For `/v1/manifest`
```
Access to XMLHttpRequest at 'https://vscode-sync.trafficmanager.net/v1/manifest' from origin 'http://localhost:30170' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
ERR RequestService#request (browser) - error https://vscode-sync.trafficmanager.net/v1/manifest Error: XHR failed
    at m.onerror (request.ts:30:29)
```
For `/v1/resource/machines/latest`
```
Access to XMLHttpRequest at 'https://vscode-sync.trafficmanager.net/v1/resource/machines/latest' from origin 'http://localhost:30170' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
ERR RequestService#request (browser) - error https://vscode-sync.trafficmanager.net/v1/resource/machines/latest Error: XHR failed
    at m.onerror (request.ts:30:29)
```

**Comment by connor4312** [comment]
This is something that settings sync/unpkg would need to support, reassigning.

**Comment by Tyriar** [comment]
I think requests to settings sync should also be happening on the server @sandy081?

**Comment by sandy081** [comment]
Settings Sync requests go through `RequstService`. It makes requests directly from the browser first and if it fails it falls back to the server. Same is happening in this case. For VS Code Server, we can redirect all requests to go through the server and for other known VS Code Web products like vscode.dev/github.dev we can use the fallback request handling mechanism. But I do not know if we can make this decision for all callers of request service in VS Code Server.

**Comment by Tyriar** [comment]
@sandy081 so sync should still work due to the fallback? If these CORS errors are showing in the devtools console could we suppress them as they're expected?

**Comment by ZauberNerd** [comment]
@Tyriar yes, sorry, I should have clarified that earlier. The settings sync feature does work, it's just spitting out a lot of warnings into the devtools console.

**Comment by sandy081** [comment]
> If these CORS errors are showing in the devtools console could we suppress them as they're expected?

These are logged by the browser I suppose and I do not know if there is a way to suppress them.

**Comment by Tyriar** [comment]
Oh ok, probably not if try/catch doesn't suppress

**Comment by joaomoreno** [comment]
This should now be fixed: 

```
❯ https -h https://www.vscode-unpkg.net/_lp/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/1.69.0/zh-CN/vscode/vs/workbench/workbench.web.main/ Origin:https://foobar
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Accept,Accept-Encoding,X-Client-Name,X-Client-Version,X-Machine-Id,X-Client-Commit
Access-Control-Allow-Origin: *
Cache-Control: public, max-age=31536000
Content-Encoding: gzip
Content-Type: application/json
Cross-Origin-Resource-Policy: cross-origin
Date: Wed, 27 Jul 2022 13:52:33 GMT
Transfer-Encoding: chunked
Vary: Origin
X-Azure-Ref: 0IkPhYgAAAAAJmJCV9WLMR6YRGuaqV07ITElTMDFFREdFMDUwOQA4ZGNmMmY1OC03MDUyLTQwYjAtODhjOC0xMTljNGMyM2EzM2I=
X-Azure-Ref-OriginShield: 0ikLhYgAAAADXgCWHWiR0Q6iNcRBr4oR5UEFSMjAxMDMxMDEyMDA5ADhkY2YyZjU4LTcwNTItNDBiMC04OGM4LTExOWM0YzIzYTMzYg==
X-Cache: TCP_HIT
request-context: appId=cid-v1:d6866f6c-d894-40e4-bb0c-0a7fb563edfd
```
