### ISSUE TITLE
Cant use F5 after vscode updated this morning.

### ISSUE THREAD

**Issue by KbyteTutu** [microsoft/vscode-remote-release#6927]
I'm using VSCODE and remote-WSL to debug my python script.  I cant use debug and run in WSL to run my code.

i can run it via python command, but i cant use debug feature any more. 

I dont know why, but seems i didn't do anything than updated my vscode this morning. But even if i revert the vscode to 1.68, the problem still exist. It might be some wrong settings, but idk how to fix it.

**Comment by aeschli** [comment]
If you still see this issue, please file it against the ms-python extension.
