### ISSUE TITLE
Centos 7 ARM Find in Files and Command Palette search only work for files open in editor.

### ISSUE THREAD

**Issue by jnchaba** [microsoft/vscode-remote-release#6930]
- VSCode Version: 1.69.0
- Local OS Version: macOS Monterey 12.3.1
- Remote OS Version: CentOS Linux release 7.9.2009 (AltArch)
- Remote Extension/Connection Type: SSH
- Logs:
```[2022-07-11 13:08:15.296] [renderer7] [trace] SearchService#search {"_reason":"searchView","folderQueries":[{"folder":{"$mid":1,"fsPath":"/home/vagrant/SNaaP","external":"vscode-remote://ssh-remote%2Bsnaap2it/home/vagrant/SNaaP","path":"/home/vagrant/SNaaP","scheme":"vscode-remote","authority":"ssh-remote+snaap2it"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/Thumbs.db":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"disregardParentIgnoreFiles":true,"ignoreSymlinks":false}],"usingSearchPaths":false,"onlyOpenEditors":false,"maxResults":20000,"type":2,"contentPattern":{"pattern":"help","isRegExp":false,"isCaseSensitive":false,"isWordMatch":false,"wordSeparators":"`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"},"previewOptions":{"matchLines":1,"charsPerLine":1000},"usePCRE2":false}```

Steps to Reproduce:

1. Connect to Host using Remote-SSH, where the host is an Centos 7 ARM image
2. Open folder of your codebase
3. Cmd+Shift+F for anything that exists in your codebase.
4. "No results found. Review your settings for configured exclusions and check your gitignore files".
5. Try to open a file using command palette, no files are listed.
6. Open any from your codebase to your editor.
7. Try searching again using Cmd+Shift+F.
8. Results only appear for the file in your editor.
9. Try to open a file using command palette, only the files you have previously opened appear as options.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

I have two environments set up. My windows environment remote ssh's into a Centos 7 x86 image, with the same codebase,  and this issue does not present. My M1 environment remote ssh's into a Centos 7 AltArch image, also with the same codebase, and this issue does present. I'm aware there was recently a release with issue 2998 that added support for Centos 7, and it works perfectly except for the Find-in-Files and Find-in-Folder searches.

I am using the exact same exclusion settings and .gitignore files across the two environments.

**Comment by jnchaba** [comment]
Images of comparison of search across windows and mac, also showing permissions for ripgrep, which I believe is what drives the search (might be wrong, though?)
Windows, working normally:
![image](https://user-images.githubusercontent.com/35639052/178329340-12f633f6-2e1e-463b-a3c1-fd714ff821e1.png)
Mac, not showing any results:
<img width="871" alt="CleanShot 2022-07-11 at 14 07 53@2x" src="https://user-images.githubusercontent.com/35639052/178329770-2329ecd7-4c9f-4b4d-b95e-6c7137c13b3b.png">
Mac, showing results if the file is open in an editor:
<img width="880" alt="CleanShot 2022-07-11 at 14 09 08@2x" src="https://user-images.githubusercontent.com/35639052/178329820-9c9be836-e663-4481-932d-8cdb9948cdcc.png">

**Comment by sfc-gh-pbennes** [comment]
Filed https://github.com/microsoft/vscode-ripgrep/issues/34 in what I think is the upstream. Addressing that should fix this.

**Comment by pclausen** [comment]
> Workaround:
> 
>     * Install rustlang on the remote ssh host per: https://www.rust-lang.org/tools/install
> 
>     * Download and build ripgrep on the remote ssh host per https://github.com/BurntSushi/ripgrep#building
> 
>     * Replace the broken `rg` binaries on the remote host in `~/.vscode-server/ with the one just built:
> 
> 
> ```
> [pbennes@localhost ripgrep]$ ./target/release/rg --version
> ripgrep 13.0.0 (rev a9d97a1dda)
> -SIMD -AVX (compiled)
> [pbennes@localhost ripgrep]$ find /home/pbennes/.vscode-server/ -type f -name rg -exec cp -vf target/release/rg {} \;
> ‘target/release/rg’ -> ‘/home/pbennes/.vscode-server/bin/da76f93349a72022ca4670c1b84860304616aaa2/node_modules/@vscode/ripgrep/bin/rg’
> ‘target/release/rg’ -> ‘/home/pbennes/.vscode-server/bin/6d9b74a70ca9c7733b29f0456fd8195364076dda/node_modules/@vscode/ripgrep/bin/rg’
> ```

+1 - works for me on  CentOS Linux release 7.7.1908 (AltArch)
Next problem is getting debugging with gdb to work...

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/145541
