### ISSUE TITLE
Unable to use code-server due to a port forwarding issue

### ISSUE THREAD

**Issue by Torreip** [microsoft/vscode-remote-release#6932]
- VSCode Version: Latest Server Build available --> VScode on the web
- Local OS Version: Windows 11 Pro build 21H2 22000.778
- Remote OS Version: Windows 11 Pro build 21H2 22000.778
- Remote Extension/Connection Type: Server
- Logs: 
- [2022-07-12 12:27:58] info Downloading port forwarding utility
thread 'tokio-runtime-worker' panicked at 'failed to spawn command: Os { code: 32, kind: Uncategorized, message: "Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus." }', src\basis.rs:697:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2022-07-12 12:28:32] error could not open tunnel: tunnel creation cancelled

Screenshot for better formatting
![Capture d’écran 2022-07-12 124903](https://user-images.githubusercontent.com/80983183/178473646-d73d4fa8-fb39-431b-9ad2-b9eae38259e2.png)

Steps to Reproduce:

1. Follow official install step
2. Run code-server
3. Accept EULA
4. Connect to authorized Github account
5. Select a snazzy name
6. Have this error

-- More Info --

I have a residential internet connection, with dynamic IP, Server has a static IP on the LAN.
I have uninstalled completely and reinstalled twice following each and every step. Have the same error every time.
After serving the server (post error) it does display a VS Code loading screen for a few seconds before crashing and telling me to check devs tools this is the message.
The problem is a 404.
Is there a way to manually port forward the app ?

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by tanhakabir** [comment]
I translated `Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.` to `The process cannot access the file because this file is used by another process.`

It looks like some part of the server panicked because it couldn't have access to the file it needed. @connor4312 what are your thoughts on what files are being used for tunnel creation that could be causing this error?

**Comment by Torreip** [comment]
Sorry I should have translated the part in french. I forgot / didn’t saw it. I sometime mix the two language when I read ^^’

**Comment by connor4312** [comment]
Should be resolved with https://github.com/microsoft/vscode-cli/issues/434

**Comment by Torreip** [comment]
Ok I'll try that first thing in the morning. Thank's

**Comment by Torreip** [comment]
Hello, I came around retesting to see if the solution was indeed implemented and it now works on my main machine.

I will do some VM & WSL test to see if it was not a fluque Thanks for the provided help !

**Comment by connor4312** [comment]
This has now been released, and you can run the setup script again to grab the newest bits
