### ISSUE TITLE
Remote-Containers: Clone Repository in Container Volume not working from WSL 

### ISSUE THREAD

**Issue by VikramAIS** [microsoft/vscode-remote-release#6934]
- VSCode Version:  1.68.1
- Local OS Version: Windows 10
- Local chip architecture: arm64
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: N/A

Steps to Reproduce:

1. Install Docker Engine in WSL Ubuntu distribution and start the docker
2.  Open the vscode from Ubuntu wsl
3.  Open the command palette and select Remote-Containers: Clone Repository in Container Volume

**Actual Behavior:**
Error throws **"this error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified."**

**Expected:**
No error as docker daemon is running on WSL distro

**Comment by bamurtaugh** [comment]
Transferring as this seems to be an extension issue, rather than an issue with a specific dev container definition.

**Comment by chrmarti** [comment]
Try enabling 'Execute in WSL' in the user settings:
<img width="916" alt="image" src="https://user-images.githubusercontent.com/9205389/178703993-4c60213a-52b3-4aa8-b024-21f4fd438ec2.png">

**Comment by chrmarti** [comment]
Related: https://github.com/microsoft/vscode-remote-release/issues/6817
