### ISSUE TITLE
Remote Container is not working

### ISSUE THREAD

**Issue by SudonNoh** [microsoft/vscode-remote-release#6937]
After update version, It is not working like this.

It is still installing server..

How can I solve this problem ?

![image](https://user-images.githubusercontent.com/69226800/178667208-6896dd60-0b59-41f2-ad40-424b2af86682.png)

**Comment by jinrudals** [comment]
same for `b06ae3b2` commit (1.69.1).

**Comment by SudonNoh** [comment]
> same for `b06ae3b2` commit (1.69.1).

Sorry, It's my first issue. I don't understand your reply.
What does that mean ?

**Comment by ho-tae** [comment]
@SudonNoh 혹시 윈도우 11이신가요?

**Comment by ho-tae** [comment]
> > @SudonNoh 혹시 윈도우 11이신가요? 저도 오늘 오전에 로컬에서 서버 컨테이너 접속하려고 하는데 오류가 나서 확인하다가 결국은 해결을 못하고 ssh remote까지 지우고 다시 설치하는데 vscode-server를 다운 받지 못해서 ssh도 연결이 안되고 있습니다. 이번 update와 윈11이 뭔가 문제가 있는거 같네요..
> 
> 네 , 저도 윈도우 11입니다... 최근까지 잘 되다가 업데이트 하니 안돌아가네요. 위에 코멘트 따라해보고 안되면 다음 업데이트 기다려보려구요..

저도 저 코멘트처럼 해봤는데 잘 안돼서 혹시 결과 좀 공유해주시면 감사하겠습니다!

**Comment by jinrudals** [comment]
@ho-tae @SudonNoh I guess it was a temporal netowork error in Korea. I've just tried again, and the download process is working (still slow though).

**Comment by ho-tae** [comment]
@jinrudals I also found out through trial and error. It seems to face the same problem. It's very slow

**Comment by ho-tae** [comment]
My co-worker uses Mac, but there is no such problem.

**Comment by SudonNoh** [comment]
> My co-worker uses Mac, but there is no such problem.

@ho-tae 저 아침에 해보니 됐네요..?? 뭐가 문제인지는 모르겠네요 ㅋㅋㅋ 아침에 해보니까 동작하는데, 연결 끊었다가 다시 해보기 무서워서 그냥 작업부터 하려구요

**Comment by ho-tae** [comment]
> > My co-worker uses Mac, but there is no such problem.
> 
> @ho-tae 저 아침에 해보니 됐네요..?? 뭐가 문제인지는 모르겠네요 ㅋㅋㅋ 아침에 해보니까 동작하는데, 연결 끊었다가 다시 해보기 무서워서 그냥 작업부터 하려구요

저도 출근중인데 가서 해봐야겠네요 위에 말처럼 일시적인 한국 서버 오류일 확률이 높네요 ㅠㅠ

**Comment by SudonNoh** [comment]
> > > My co-worker uses Mac, but there is no such problem.
> > 
> > 
> > @ho-tae 저 아침에 해보니 됐네요..?? 뭐가 문제인지는 모르겠네요 ㅋㅋㅋ 아침에 해보니까 동작하는데, 연결 끊었다가 다시 해보기 무서워서 그냥 작업부터 하려구요
> 
> 저도 출근중인데 가서 해봐야겠네요 위에 말처럼 일시적인 한국 서버 오류일 확률이 높네요 ㅠㅠ

네, 그런거 같아요 !

지금 연결 끊었다가 다시 했는데 잘되네요 ㅎㅎ

**Comment by SudonNoh** [comment]
Thanks to everyone who commented. It works now!
I think it was a temporal netowork error in Korea just like @jinrudals said.

**Comment by ho-tae** [comment]
@SudonNoh 
후... 잘됩니다.. 고생하셨어요 저는 어제 날린거 생각하면 ㅠㅠㅠ

**Comment by SudonNoh** [comment]
@ho-tae 
저도 거의 4시간 날렸습니다. 다시 깔고 조건 바꿔보고 별의별 짓을 다했었는데ㅎㅎㅎ 고생하셨어요

**Comment by SudonNoh** [comment]
@chrmarti

I just deleted and downloaded "Remote Container".
I think yes It is an intermittent problem. 

When I ran it in this morning, It worked. 
After a while I disconnected and reconnected and it didn't work anymore.
