### ISSUE TITLE
New files doesn't recognize in devcontainer

### ISSUE THREAD

**Issue by InsonusK** [microsoft/vscode-remote-release#6938]
When You open project in devcontainer.
Then create new file
This files doesn't recognized by code assistant

Example on python
We have project 
```
- src
  - __init__.py
```
 
1. Open project in devcontainer.
2. add file src/some_code.py
3. add function to file some_code.py  `def some_method():`
4. try add `from .some_code import some_method` to __init__.py
5. we get error `Import ".some_code" could not be resolved`
6. reopen container: "Reopen folder Localy" + "Reopen in Container"
7. now import work correct.

I have got same problem in python, TS, C#.

**Comment by chrmarti** [comment]
Which versions of VS Code and Remote-Containers are you using?

**Comment by InsonusK** [comment]
> Which versions of VS Code and Remote-Containers are you using?
@chrmarti 

VS Code Version: 1.69.1
Remote-Containers (ms-vscode-remote.remote-containers): v0.241.3

**Comment by InsonusK** [comment]
I have change version of Remote - Containers to pre-release v0.243.0
I look like it start work better.

Now, after adding file, there is some delay, around 10-20 seconds before VSCode recognize new file.

Is there is any delay between adding file till VSCode recognize that new file exist?

**Comment by jaen003** [comment]
I have had the same error, but it only happens on windows, I have tried it on linux and it works perfectly.

**Comment by jaen003** [comment]
It seems that the error is in Pylance, I have changed the language of the server language to Jedi and this has solved the problem.
