### ISSUE TITLE
code-server launcher should forward --socket-path to the underlying server

### ISSUE THREAD

**Issue by leifwalsh** [microsoft/vscode-remote-release#6940]
There are two things called `code-server`, I'm not sure how you refer to them internally, but I'll call https://aka.ms/vscode-server-launcher/x86_64-unknown-linux-gnu the launcher and https://update.code.visualstudio.com/commit:b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/server-linux-x64-web/stable, which that downloads, the server.

The server supports `--socket-path`, which makes it listen on a unix domain socket, which is great for security. We can use that, and send it traffic through a reverse proxy that terminates authentication in the way we like to do authentication internally. Having the server listen on a localhost TCP port is less secure on shared hosts.

But, the launcher only supports `--host` and `--port`, it doesn't know about `--socket-path`. Could we make the launcher forward the `--socket-path` argument along for `code-server serve-local --socket-path`?

**Comment by connor4312** [comment]
Thanks for the issue.

Currently, we listen on a port since the underlying infrastructure and client we use from another team is designed as a port forwarding service. However, we hope to soon build native integration to their service in our CLI and their SDK, which would let us avoid having to listen anywhere, since we can connect incoming connections directly to the control server.

**Comment by connor4312** [comment]
Ah, right, missed that...

**Comment by andreamah** [comment]
What are some verif steps for this?

**Comment by connor4312** [comment]
1. Install/update to the latest version of the CLI (steps https://github.com/microsoft/vscode-cli#installation)
2. Run `code-server serve-local --help` and verify `--socket-path` is there
3. Run `code-server serve-local --socket-path /path/to/some/socket` and verify that the output says it's listening on that path

**Comment by connor4312** [comment]
actually, I didn't work on this, so I did that and just verified it 😛
