### ISSUE TITLE
There should be a way to unrgister a different machine from the code-server port forwarding service

### ISSUE THREAD

**Issue by eladts** [microsoft/vscode-remote-release#6942]
It seems the only way to unregister a machine from the code-server port forwarding service is from the machine itself using the command `code-server unregister`. However, if you cannot access the machine (for example, you deleted that VM), there is no way to remove it from the service. You cannot reuse the name for a different machine. There should be a way to purge such a machine from the forwarding service.

**Comment by eladts** [comment]
This issue is not with Remote SSH but rather with the new experimental [Code Server](https://code.visualstudio.com/blogs/2022/07/07/vscode-server).

**Comment by suasuasuasuasua** [comment]
Agreed. I'm running into the same issue, so now I have machines that I can't access nor delete.

**Comment by connor4312** [comment]
In tomorrow's extension build, there will be a context menu action for this:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/2230985/190263884-a2e0b548-7764-43c9-86a5-48295a3993e2.png">
