### ISSUE TITLE
VSCode Server and Extension is all good? (slow and lags)

### ISSUE THREAD

**Issue by YooSungHyun** [microsoft/vscode-remote-release#6948]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.69.1 (latest)
- OS Version: win 10

Steps to Reproduce:

1.vscode download is so slow in korea
2.vscode server download is so slow in korea
  2-1. so, can not connect server to remote-ssh. because, when vscode-server install on my remote server, raise time-out and infinity loop
3. extension install is too slow

maybe microsoft server issue?

**Comment by tanhakabir** [comment]
> 3. extension install is too slow

This is referring to installing extensions on the remote machine while you're connected?

> 2-1. so, can not connect server to remote-ssh. because, when vscode-server install on my remote server, raise time-out and infinity loop

Is this referring to being unsuccessful to connect to a remote machine using the Remote SSH extension?

**Comment by YooSungHyun** [comment]
@tanhakabir 
thx for reply!

- This is referring to installing extensions on the remote machine while you're connected?
all-same slow
connected server and my local vscode
it is little faster than yesterday, but still so slow.
and, my coworker's vscodes same feeling slow.
isn't it korea or asia server issue?

- Is this referring to being unsuccessful to connect to a remote machine using the Remote SSH extension?
yes, but i find way that is .vscode-server folder delete and reinstall. then success
but, in korea, vscode-server download speed is too much slow. and we have to re setting program....😢

**Comment by YooSungHyun** [comment]
now, that problem is solved.
maybe, vscode download server was haved some issue....

**Comment by deagwon97** [comment]
I often encounter the same problem as you in Korea.

This is a temporary solution. But if this happens again and you are in a really urgent situation, try it.

1. This method requires you to have the .vscode-server/ dir in advance. (If there is a server that connects to the remote-ssh extension, you can find the .vscode-server/ dir.)
2. copy the .vscode-server dir into your project directory.

```command
sudo cp -r /home/user/.vscode-server/bin /home/user/srv/project/.vscode-server/bin
```
3. modify your Dockerfile
```Docker
FROM base-image
...
COPY ./.vscode-server/bin /root/.vscode-server/bin
...
```
4. Do `Remote-Containers: Open Folder in Container.. `
