### ISSUE TITLE
Support ProxyCommand/RemoteCommand AND password prompt

### ISSUE THREAD

**Issue by three0s** [microsoft/vscode-remote-release#695]
This is with `remote.SSH.showLoginTerminal` turned on to input the password manually (which I can't get around with the setup I am under). 
The typical `ssh` behaviour would be to prompt for password first and then forward the `ProxyCommand`/`RemoteCommand`, however the extension seems to be forwarding the stdin right away when the password is prompted causing the connection to fail.

**Comment by roblourens** [comment]
We block RemoteCommand, because it won't work the way you expect anyway, ie it won't apply to terminals that are opened inside of vscode. You will have to find another way to get the same result. If you tell me what you are using it for I can try to give advice.

**Comment by three0s** [comment]
After doing a bit of searching, my workflow is exactly same as the one mentioned in this issue
https://github.com/microsoft/vscode-remote-release/issues/82

Any suggestions would be great, thanks!

**Comment by yedane** [comment]
Hello, 

In my case, we need to connect with a specific user (userA) and then switch to another (user) in order to have access to the source folder.  userB cannot be reached using SSH. 

Host some_name
  User  userA
  HostName  xxx.xxx.xxx.xxx
  RemoteCommand su - userB
  RequestTTY yes

**Comment by tanhakabir** [comment]
Just added a new setting to enable RemoteCommand, `remote.ssh.enableRemoteCommand` in the newest release of the extension version `0.70.0`. 

`enableRemoteCommand` will only work with `remote.ssh.useLocalServer` set to `true`. Let me know any issues or bugs you see with the experimental setting!
