### ISSUE TITLE
Add the source code of the extension

### ISSUE THREAD

**Issue by fortierq** [microsoft/vscode-remote-release#6958]
Apparently, the source code of this extension ms-vscode-remote.remote-containers is not available on GitHub. Is it possible to upload it?

**Comment by chrmarti** [comment]
The Dev Container CLI on which Remote-Containers is based is published under the MIT license here: https://github.com/devcontainers/cli

The Remote-Containers extension itself is not open source, please see the FAQ for more information: https://code.visualstudio.com/docs/remote/faq#_license-and-privacy.

**Comment by fortierq** [comment]
Thanks.
