### ISSUE TITLE
Add support for code server installation on machine without internet access

### ISSUE THREAD

**Issue by ahmednrana** [microsoft/vscode-remote-release#6959]
Sometimes, a machine is not allowed access to internet. In that scenario, please add support to install and use code-server locally on machine without any internet access.

**Comment by tanhakabir** [comment]
@ahmednrana are you able to connect to the port forwarding service though? Since that requires internet access

**Comment by OneCyrus** [comment]
there should be a way to connect directly to a local instance without going through the tunnel. the remote server extension should allow to connect to an internal hostname by allowing custom hostnames in the selector.

**Comment by tanhakabir** [comment]
No that isn't possible since there is no tunneling service for the extension to connect to through. It's technically not feasible for the extension in the browser to connect to the remote without having some in between tunneling service.

**Comment by ahmednrana** [comment]
@tanhakabir No I was unable to install vscode-server as the machine does not have internet access.

**Comment by tanhakabir** [comment]
@ahmednrana yes you can't currently install the vscode-server on the remote without internet access. This is expected.

**Comment by connor4312** [comment]
In the current CLI, we do not have a "connect directly to a local instance" mode. This might come back in the future, but for now this issue is out of scope.

**Comment by mihailik** [comment]
Given that it's mentioned and got  ✅ checkbox as done [on November 2022 plan:](https://github.com/microsoft/vscode-remote-release/issues/7479)

![image](https://user-images.githubusercontent.com/4041967/215162412-121d85d7-e757-45f9-a90d-6bcb4a5ff71a.png)

Should this *out-of-scope label be removed now?

Can't be both 'done'  and  'out of scope'  can it?

**Comment by connor4312** [comment]
That should have pointed to https://github.com/microsoft/vscode-remote-tunnels/issues/308, which actually _was_ done. "local download" is the name of the same feature/setting in SSH.
