### ISSUE TITLE
Yarn watch doesn't seem to react to save events

### ISSUE THREAD

**Issue by lediur** [microsoft/vscode-remote-release#696]
Issue Type: <b>Bug</b>

Environment: remote development via SSH to Ubuntu 18.04 server (via SSH bastion host as ProxyCommand "-W" flag)

0. Start a remote development session
1. Create an application with create-react-app
2. Run `yarn start` to start the watch session
3. Change a file in the project, which should've triggered a recompile
4. Notice that recompilation doesn't occur

Extension version: 0.42.2
VS Code version: Code - Insiders 1.36.0-insider (15b7c86d86319b187a5ef255c170184a8519c5af, 2019-06-14T10:37:04.235Z)
OS version: Windows_NT x64 10.0.18917
Remote OS version: Linux x64 4.15.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (0.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: b-farli|
|OS|Linux x64 4.15.0-48-generic|
|CPUs|Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz (1 x 2261)|
|Memory (System)|4.86GB (1.68GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment]
@lediur what happens when you change a file in the Git view, does the change appear and the change count is updated?

**Comment by lediur** [comment]
Sorry for the delay. If I change a file, it does show up as a new file in the unstaged changes list of the Git source control provider, but the React development server running through `yarn start` doesn't seem to pick up a file change. If I run `git diff` in a separate terminal, the change shows up. I'm not sure what you mean by "change count" though.

**Comment by egamma** [comment]
@lediur can you confirm that this works locally?

**Comment by lediur** [comment]
Yep, just confirmed it works locally in the VSCode terminal. I had switched to local development to work around the issue for now, but was using an external terminal program with no issues.

**Comment by ayazhussein** [comment]
I'm having the same issue with angular cli, changing files and saving them does not trigger any recompilation but it does show in git tab that the files are changed. weirdly when also editing the file through vim in vscode terminal, it doesn't trigger anything.

**Comment by roblourens** [comment]
This sounds like an issue with the react/angular, not vscode.
