### ISSUE TITLE
extension makes my server mems usage high and lose connect 

### ISSUE THREAD

**Issue by Ross249** [microsoft/vscode-remote-release#6965]
- VSCode Version:1.69.1
- Local OS Version:MacOS 12.3
- Remote OS Version:ubuntu 20.04 LTS
- Remote Extension/Connection Type: SSH/Containers/WSL/Server
- Logs:

Steps to Reproduce:

1. use remote ssh to connect my server
2. make some code and then ssh connect was closed
3. my server send me wrong message because of server's mems usage was up to more then 75%

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by tanhakabir** [comment]
> my server send me wrong message

What message is this?

What are the specs of your remote server? Do you have any Remote SSH logs of what you're seeing?

**Comment by Ross249** [comment]
The warning content is probably saying that my server memory utilization is greater than 75%.

my server got 2 core and 2 G mems

sorry,this is the first time i have met and i didn't have the history usage of my server memory.

**Comment by tanhakabir** [comment]
Hm well the excessive memory usage could be a result of opening too many files or large files, or many active extensions.

You could try killing the VS Code Server with the command `Kill VS Code Server on Host...`

**Comment by Ross249** [comment]
OK,i will try.thank you so much
