### ISSUE TITLE
VS Code server (gateway) does not allow to open directories that include space in them.

### ISSUE THREAD

**Issue by kartikfire** [microsoft/vscode-remote-release#6969]
- VSCode Version: 1.69.2 
- Local OS Version: Windows 11 Home - 10.0.22000 Build 22000 (but using WSL to host)
- Remote OS Version: Brave browser - 1.41.96 Chromium: 103.0.5060.114 (Official Build) (64-bit) 
- Remote Connection Type: **Server**
- code-server Version: **VS Code Server 20220708.2**

Steps to Reproduce:

1. Download code server from https://code.visualstudio.com/blogs/2022/07/07/vscode-server
2. Run code-server on any unix machine / terminal
3. Follow the steps and go to the link shown in terminal (it would be something like https://insiders.vscode.dev/+ms-vscode.remote-server/name:8000/mnt/path/to/dir)
4. Open a directory that includes a space in it (eg: "/My App") (to be done in the link shown in terminal)
5. It fails to find the directory because url converts " " to "%20"

Does this issue occur when you try this locally?: Yes

**Comment by tanhakabir** [comment]
Fixed in insiders.vscode.dev!
