### ISSUE TITLE
File content viewing

### ISSUE THREAD

**Issue by chasset** [microsoft/vscode-remote-release#697]
Issue Type: <b>Bug</b>

After an hour of good behavior, it is not possible to see the content of a file after selecting it. The SSH connection seems to be OK since I can send command over the vscode Terminal.

Extension version: 0.42.2
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.15.0-50-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (2.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: zebulon|
|OS|Linux x64 4.15.0-50-generic|
|CPUs|Intel(R) Xeon(R) CPU E7- 8837  @ 2.67GHz (64 x 2800)|
|Memory (System)|1007.87GB (296.08GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment]
>it is not possible to see the content of a file after selecting it

What exactly do you mean by this? Was the explorer still active when this happend? Did you see any error message?
