### ISSUE TITLE
Attach Visual Studio Code Error -> uv_os_get_passwd returned ENOENT

### ISSUE THREAD

**Issue by corn-dog** [microsoft/vscode-remote-release#6971]
Does this occur consistently? Yes
Repro steps:

1. Start up (any) container via docker compose up
2. Navigate to Activity Bar > Docker > CONTAINERS
3. Right click on (any) container and "Attach Visual Studio Code"
4. Receive the following error:

"Error running command remote-containers.attachToRunningContainerFromViewlet: A system error occurred (A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)). This is likely caused by the extension that contributes remote-containers.attachToRunningContainerFromViewlet."

Version: 1.22.1
OS: linux
OS Release: 5.15.0-41-generic
Product: Visual Studio Code
Product Version: 1.69.2
Language: en

**Comment by corn-dog** [comment]
fyi this error occurred in the latest VSCode Snap. I have since removed this snap, and downgraded to Version 1.68.1 via .deb , this has resolved the issue

**Comment by chrmarti** [comment]
There is a fix for this in Remote-Containers 0.243.0-pre-release (switch Remote-Containers to pre-releases from the Extensions viewlet). Tracked as https://github.com/microsoft/vscode-remote-release/issues/6913. Thanks.
