### ISSUE TITLE
VS code remote connection: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by zhenglilei** [microsoft/vscode-remote-release#6973]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.1
- OS Version: Darwin arm64 21.5.0

Steps to Reproduce:
1. Keep the remote connection in VScode
2. AFK (away from keyboard)
3. When the connection naturally breaks, then retry to connect
4. The error message will occur.

``` bash
[18:33:55.749] Resolver error: TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.a [as sanitizeConnectionToken] (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:691806)
    at Object.C [as findRunningServer] (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:626542)
    at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622510
    at async T (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:619351)
    at async Object.t.resolveWithLocalServer (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622460)
    at async Object.t.resolve (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644834)
    at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[18:33:55.751] ------
```
I found that one solution is to remove VScode cache at `/Users/username/Library/Application\ Support/Code`

But this is definitely not the right way, any one knows the root cause and how to solve it?

**Comment by tanhakabir** [comment]
@zhenglilei could you let me know if the pre-release version of the extension fixes your error?

**Comment by janus-zheng** [comment]
> me

Yes, I switched to the pre-release version in the past two days. No error any more.

**Comment by zhenglilei** [comment]
OK, given the discussion above, I will close this issue. Thanks to all!

**Comment by alexkutsan** [comment]
How can I install the pre-release version on my Mac? 
Is that it? 
![изображение](https://user-images.githubusercontent.com/860357/182197495-2e8dfd59-4684-4d1d-9eea-899345ca9e90.png)

**Comment by zhenglilei** [comment]
> How can I install the pre-release version on my Mac?
> Is that it?
> ![изображение](https://user-images.githubusercontent.com/860357/182197495-2e8dfd59-4684-4d1d-9eea-899345ca9e90.png)

@alexkutsan   it's here, `switch to pre-release version`
![image](https://user-images.githubusercontent.com/8134656/182377666-28179046-457b-4947-85b5-ec13938d3a78.png)

**Comment by ns-jzhan** [comment]
I enabled "Remote Server Listen On Socket" option and it worked good so far. 

I tried to switch between **pre-release** version and **stable release** version. It worked only for a little while and got broken again.

**Comment by srinivasa-rao-k** [comment]
> I enabled "Remote Server Listen On Socket" option and it worked good so far.
> 
> I tried to switch between **pre-release** version and **stable release** version. It worked only for a little while and got broken again.

The same happened to me. Thanks for the help! Enabled <Remote Server Listen On Socket> in the Remote SSH extension settings and it worked again.
