### ISSUE TITLE
curl fails for some public websites but not others

### ISSUE THREAD

**Issue by mkarikom** [microsoft/vscode-remote-release#6976]
- VSCode Version:
- Local OS Version: macos 12.4
- Remote OS Version: ubuntu 20.04
- Remote Extension/Connection Type: remote dev container
- Logs: see `wed_morning.txt` attached (there is nothing in there about curl)

Steps to Reproduce:

1. build container using `devcontainer.json` and `Dockerfile` (attached in Archive.zip)
2. run successful download from `wikipedia.org`:
```
vscode ➜ /workspaces/scACVI_devcon/rawdata_wu2021 (main ✗) $ curl https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/DNA_Structure%2BKey%2BLabelled.pn_NoBB.png/680px-DNA_Structure%2BKey%2BLabelled.pn_NoBB.png --output check.png
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  392k  100  392k    0     0  3598k      0 --:--:-- --:--:-- --:--:-- 3598k
```
3. run unsuccessful download from `broadinstitute.org`
```
vscode ➜ /workspaces/scACVI_devcon/rawdata_wu2021 (main ✗) $ curl "http://singlecell.broadinstitute.org/single_cell/api/v1/bulk_download/generate_curl_config?accessions=SCP1039&auth_code=QYGxPBlI&directory=all&context=study"  -o cfg.txt; curl -K cfg.txt && rm cfg.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server
Warning: error trying read config from the 'cfg.txt' file
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes
[wed_morning.txt](https://github.com/microsoft/vscode-remote-release/files/9152126/wed_morning.txt)
[Archive.zip](https://github.com/microsoft/vscode-remote-release/files/9152142/Archive.zip)

**Comment by chrmarti** [comment]
This is unrelated to VS Code or Remote-Containers. I suggest you open a question on StackOverflow or similar. Thanks.
