### ISSUE TITLE
git config gpg.program should not be copied into devcontainer.

### ISSUE THREAD

**Issue by cor** [microsoft/vscode-remote-release#6978]
When you create a decontainer, your `~/.gitconfig` is copied into the container. This is great, except for the fact that it introduces an issue with signing commits. Because a `.gitconfig` could include the following:

```
[gpg]
	program = /opt/homebrew/bin/gpg
```

When this is the case, the host location of `gpg` gets copied into the remote. Then, when you want to sign a commit within the container, it will complain that `/opt/homebrew/bin/gpg` is not found. A workaround is to type 
```
git config --global gpg.program `which gpg`
```
in the container's terminal, but you should not have to do this. Instead, when copying over the `.gitconfig`, `gpg.program` should be ignored.

When you want to sign commits using `gpg` inside of your devcontainer,

- VSCode Version: Version: 1.69.2 (Universal)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
- Local OS Version: macOS 12.4 (21F79)
- Remote OS Version: any
- Remote Extension/Connection Type:Containers

Steps to Reproduce:

1. Have `gpg.program` set in the host's `~/.gitconfig`
2. Create any devcontainer
3. try to sign a commit from within that devcontainer
4. this should error (see details above)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
The copying of `.gitconfig` can be turned off in the user settings. Alternatively you could set a dotfiles repository in the user settings and use that to create a better `.gitconfig`. (Note that we don't copy the `.gitconfig` if your dotfiles places one.)

**Comment by joaomoreno** [comment]
I just hit this issue. I think copying the gitconfig is a great idea, but it should probably be massaged in a way that it removes host specific options.

**Comment by chrmarti** [comment]
Since this can be specific to a user's `.gitconfig` and the list of available keys appears to be open-ended we could consider adding a user setting that lists the keys that should be omitted.

**Comment by lavahot** [comment]
I'm having an identical issue on Windows 10 with containers through WSL2. I can confirm that the workaround with `which gpg` works perfectly. I hope that a solution is implemented soon.

**Comment by gremo** [comment]
Any update? There are also other settings that should NOT be copied, like `editor`.

**Comment by gremo** [comment]
@chrmarti thank you a lot! When we can expect a new release with these fixes?
