### ISSUE TITLE
Cannot Turn on the Setting Sync with Microsoft Account

### ISSUE THREAD

**Issue by mat-wang** [microsoft/vscode-remote-release#6979]
- VSCode Version: VS Code Server 20220708.2
- Local OS Version: Windows 10/11
- Remote OS Version: Linux version 5.10.0-16-amd64 ([debian-kernel@lists.debian.org](mailto:debian-kernel@lists.debian.org)) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.127-1 (2022-06-30)
- Remote Extension/Connection Type: Server

Steps to Reproduce:
1. screen -S vscode-server
2. dbus-run-session -- sh -c "(echo 'somecredstorepass' | gnome-keyring-daemon --unlock) && code-server serve-local --host 0.0.0.0"
3. Ctrl+A D
4. visit the vscode on web
5. Turn on the Setting Sync, select Microsoft Account option, and login to my Microsoft Account in directed page
6. The page below shown
![image](https://user-images.githubusercontent.com/33516065/180242023-c1030c0d-ff39-45f5-9ec4-b3e774fca63e.png)
7. Go back to vscode on web
8. Error info and log for Microsoft Authentication shown below:
![image](https://user-images.githubusercontent.com/33516065/180243292-b42b5f09-7281-4212-9efc-bbd6bb2faa77.png)
```log
[Info  - 14:27:45.756] Reading sessions from secret storage...
[Info  - 14:27:46.591] Got 0 stored sessions
[Info  - 14:27:46.903] Getting sessions for the following scopes: email offline_access openid profile
[Trace  - 14:27:46.903] No session found with idtoken scopes... Using fallback scope list of: email offline_access openid profile
[Info  - 14:27:46.903] Got 0 sessions for scopes: email offline_access openid profile
[Info  - 14:40:14.793] Getting sessions for all scopes...
[Info  - 14:40:14.793] Got 0 sessions for all scopes...
[Info  - 14:40:18.438] Getting sessions for the following scopes: email offline_access openid profile
[Trace  - 14:40:18.438] No session found with idtoken scopes... Using fallback scope list of: email offline_access openid profile
[Info  - 14:40:18.438] Got 0 sessions for scopes: email offline_access openid profile
[Info  - 14:40:20.223] Logging in for the following scopes: email offline_access openid profile
```
9. Restart the vscode-server
10. Refresh browser
11. Microsoft Account did NOT login
12. Login Github Account in similar way
13. Login success
14. Restart the  vscode-server
15. Refresh browser
16. Github Account logged in

**Comment by szmcdull** [comment]
https://github.com/microsoft/vscode/issues/151867

**Comment by mat-wang** [comment]
> [microsoft/vscode#151867](https://github.com/microsoft/vscode/issues/151867)

Thanks for your reference. Seems the same. My issues happens on the vscode-server, but my desktop version working well. Logs looks the same, but when I click my profile, there is no Microsoft Account shown in the list, and only the Github Account showed.

**Comment by TylerLeonhardt** [comment]
@mat-wang are there any errors in Browser Dev Tools of the "You can close this page now"?

**Comment by mat-wang** [comment]
> @mat-wang are there any errors in Browser Dev Tools of the "You can close this page now"?

There are no error showed in the Dev Tools of my browser, and BTW, after updating to 20220727.1, the issue solved!
