### ISSUE TITLE
serve-local should default to 0.0.0.0 to work across NICs 

### ISSUE THREAD

**Issue by ahmadnassri** [microsoft/vscode-remote-release#6980]
when using `serve-local`, it currently defaults to listen on `127.0.0.1`, it should probably listen on `0.0.0.0` by default as in most linux systems, this address works across multiple network interfaces (network cards)

**Comment by aeschli** [comment]
No, that's on purpose. 0.0.0.0 will make the port accessible to all machines on your network.
You should only set 0.0.0.0 if you trust all machines on the same network.
