### ISSUE TITLE
Dev Container PHP & Maria DB (community)  PHP 8.0/8.1

### ISSUE THREAD

**Issue by ArmandArthur** [microsoft/vscode-remote-release#6986]
Hello,

I had installed this container, the build works but the terminal on vscode no working properly.

So, i can't run the server.

Do you have an idea?

Thx

**Comment by ArmandArthur** [comment]
Precision, it's works but i need to wait about 5 minutes between every command.

**Comment by bamurtaugh** [comment]
Hi @ArmandArthur - what version of VS Cod and Remote-Containers are you using?

And it sounds like the dev container does ultimately work, there's just some lag between commands? Do you experience this lag with all commands? With different kinds of images / dev container configurations?

**Comment by ArmandArthur** [comment]
Hello, sorry for delay. I don't know the versions about the remote-containers but i add updated my vscode with last version.

Else, i have no probleme with the extension for Python, only PHP MariaDB is very slow for the console.

**Comment by ArmandArthur** [comment]
All commands.

**Comment by bamurtaugh** [comment]
This may be machine- or language-specific like you mention, but we can see if other folks also mention they're having issues in this scenario.

**Comment by bamurtaugh** [comment]
I was referring to any other users who may try this out!

**Comment by ArmandArthur** [comment]
Only me?

**Comment by bamurtaugh** [comment]
We're not certain if this issue may be affecting other users beyond you, so I'm suggesting we leave this issue open for a bit to see if other Remote-Containers users mention they're also experiencing this. If other users aren't experiencing this, and we can't discern a specific bug you're encountering, we may ultimately close this issue. Thanks!

**Comment by ArmandArthur** [comment]
Thank you. I will try with a other computer when i could buy a new.
And i will tell you the results, ok. Good evening.

**Comment by tinydogio-joshua** [comment]
My team is noticing a lot of delays between commands in the terminal the last few weeks. We're using the Node+TypeScript devcontainer though.

**Comment by Chuxel** [comment]
Try disabling the git status portion of the prompt.  Sometimes this can happen with large repos. Run:

```
git config codespaces-theme.hide-status 1
```

**Comment by ArmandArthur** [comment]
Works for me. But git is disable?, i don't see the branch now.

**Comment by tinydogio-joshua** [comment]
Disabling the new shellIntegration setting really sped things up for our team.

https://code.visualstudio.com/updates/v1_70#_terminal

```
"terminal.integrated.shellIntegration.enabled": false
```

**Comment by Chuxel** [comment]
//cc @Tyriar re: performance and the new shell integration

**Comment by Tyriar** [comment]
@tinydogio-joshua can you be more specific what you mean by "a lot of delays"? Also what shell were you using?

**Comment by Tyriar** [comment]
cc @meganrogge

**Comment by tinydogio-joshua** [comment]
> @tinydogio-joshua can you be more specific what you mean by "a lot of delays"? Also what shell were you using?

We were seeing 3 to 10 second delays typing in pretty much any command. We're all on M1 MacBook Pro's. zsh shell. I know at least one person has oh-my-zsh installed. I have rocketship but as far as I know the rest of the team hasn't customized their shells. Setting the above setting to false brought the performance back up.

It is in a decent sized monorepo. Doing a stock Node+TypeScript devcontainer does not show the same behavior.

**Comment by Tyriar** [comment]
Let's track the performance problem in https://github.com/microsoft/vscode/issues/157432
