### ISSUE TITLE
Remote - Server Connect to a Serve-Local Code-Server Instance

### ISSUE THREAD

**Issue by TheMiskic** [microsoft/vscode-remote-release#6987]
Hello!

I've noticed that currently there is only a possibility of connecting to the Github hosted **code-server** instances.

Are there any plans for a feature that would allow you to connect to **code-server** instances hosted by the **serve-local** function?

Best regards and thanks in advance!

**Comment by tanhakabir** [comment]
Thanks for the excitement! `serve-local` is supposed to be an advanced method of using the CLI where you made your machine accessible through a web browser. 

To connect to a remote machine from just vscode.dev we need a tunneling service to reach the remote machine and thus need our tunneling service involved.

**Comment by alexzielenski** [comment]
I'm also interested in this sort of functionality.

> we need a tunneling service to reach the remote machine and thus need our tunneling service involved.

@tanhakabir I dont understand your explanation for why this is not possible. Surely if I am able to use a web browser as a client to access a remote server, I should be able to use my native `VS Code` client application to do the same. At least from a feasibility standpoint. 

A "tunneling" service does not seem necessary if a web socket can be established with a remotely hosted `code-server` instance?

**Comment by tanhakabir** [comment]
@alexzielenski yes in desktop it's completely the same as web and possible today. The original post was asking to enable `serve-local` an advanced option the same as what we have currently with `serve` which is not possible

**Comment by alexzielenski** [comment]
@tanhakabir I'm not sure I understand correctly. Is there today a feature which enables me to provide my desktop vscode remote with the URL of my `code-server serve-local` instance to establish a connection? 

i.e. `http://<CODE_SERVER_IP>:<CODE_SERVER_PORT>/?token=<TOKEN>`

I would not like to use the `vscode.dev` tunneling service, so I am starting `code-server` with `serve-local`. I have not found a way to connect to my `serve-local` instance using the native client.

**Comment by tanhakabir** [comment]
It's only possible through using our tunneling service today. `serve-local` is only intended to be used if you plan on hosting the UI of vscode yourself
