### ISSUE TITLE
Vscode server stops after running for a while without use. 

### ISSUE THREAD

**Issue by mwaaas** [microsoft/vscode-remote-release#6988]
Leaving my vscode server running overnight when I wake up in the morning I can't connect to the server as it has already stopped. 

And I see this on the server terminal 

Last EH closed

**Comment by tanhakabir** [comment]
Do you have any logs from the server?

**Comment by mwaaas** [comment]
Hey @tanhakabir 

Here is the log that I keep on seeing each time the server fails, I always fail when the vscode server is idle, ie leaving the server running at night and waking up in the morning would have stopped. 

command running is 
code-server serve-local --without-connection-token --host=0.0.0.0 --port=80

below are the logs 

[03:29:04] Extension installed successfully: ms-vsliveshare.vsliveshare
[06:44:38] [192.168.0.106][5a6a05dc][ExtensionHostConnection] <11844> Extension Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[06:44:38] Last EH closed, waiting before shutting down
Last EH closed, shutting down
[06:49:38] Last EH closed, shutting down
OpenTelemetry trace error occurred. Exporter application-insights encountered the following error(s): upload failed with 400: No retry possible

**Comment by tanhakabir** [comment]
@aeschli Is this due to the --autoshutdown flag?

**Comment by mwaaas** [comment]
How can I disable that flag

**Comment by connor4312** [comment]
Since this issue was created, we revamped how the CLI connects to the tunneling service. It should be much more stable and predicable now. Please try updating to the latest version of the CLI, and let us know if you still hit any issues.
