### ISSUE TITLE
Intellisense not working on dev containers.

### ISSUE THREAD

**Issue by abhishekdharu** [microsoft/vscode-remote-release#6990]
Issue Type: <b>Bug</b>

When creating a dev container from docker-compose file, code-completion does not work even though the extensions have been installed

Extension version: 0.241.3
VS Code version: Code 1.69.0 (Universal) (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:41.511Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.104-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id bb7899df-294f-453e-ac4c-55a14f8f1f8e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Existing Docker Compose (Extend)|
|OS|Linux x64 5.10.104-linuxkit|
|CPUs|unknown (5 x 0)|
|Memory (System)|7.67GB (1.10GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
pylanb8912:30529769
vsclangdc:30486549
c4g48928:30534093

```

</details>

<img width="1728" alt="Screenshot 2022-07-26 at 5 20 32 PM" src="https://user-images.githubusercontent.com/25360018/180999250-8f25c9a3-6a69-4a1f-a6bf-ae469915e528.png">

Do we need to make any changes in the python extension settings to make autocomplete work in the dev container?

**Comment by bamurtaugh** [comment]
Is the Python extension installed in the dev container? Including a screenshot of how the extension appears in the Extension view could be helpful.
