### ISSUE TITLE
Allow setting environment variables for docker-compose

### ISSUE THREAD

**Issue by PanCakeConnaisseur** [microsoft/vscode-remote-release#6991]
Currently it is not possible to set environment variables in *devcontainter.json*  for docker-compose such as `COMPOSE_HTTP_TIMEOUT`.

This is a duplicate (or rather ressurection) of https://github.com/microsoft/vscode-remote-release/issues/6298 and thus the tenth upvote, which will hopefully make this issue go into the backlog. There is already a duplicate in the linked thread, so we should be at 11 now.

**Comment by chrmarti** [comment]
Does adding `COMPOSE_HTTP_TIMEOUT` to an `.env` file next to the docker-compose.yml work? (This is docker-compose functionality.)
