### ISSUE TITLE
Remote containers: Add flag to disable prompt on start up

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-remote-release#7]
I would like to add docker configuration files to my team's extensions so that running and testing these extensions remotely would be easier and more consistent (everyone testing has one spec). 

A workspace config setting to disable the `Reopen in container` message on startup would make the extension less intrusive - I can always 'Open Folder in Container' if I want to. :-)

**Comment by chrmarti** [comment]
Implemented a while ago.
