### ISSUE TITLE
cannot select python interpreter from my venv on WSL

### ISSUE THREAD

**Issue by uishon** [microsoft/vscode-remote-release#70]
- VSCode Version:
- Local OS Version: Windows 10. 1809.
- Remote OS Version: WSL (Ubuntu 18.10)
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. set python.venvPath in python extension setting to ~/.virtualenvs (on remote, not user)
2. try select interpreter from the command palette (or simply click on the interpreter listed on the status bar) - VS code shows a list of interpreters to choose from but not the ones under ~/.virtualenvs. 

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by ricjuanflores** [comment]
Add to wsl settings: 

`"python.pythonPath": "~/.virtualenvs/venv_test/bin/python", `

**Comment by uishon** [comment]
It works. Thanks.

**Comment by uishon** [comment]
Hmm... Just tried the same with remote-ssh but here it didn't work :-(
I was able to select one of my virtualenvs by changing this
"python.pythonPath" to that specific virtualenv and that worked but it
still doesn't list the other virtualenvs to select from.

**Comment by uishon** [comment]
Just a quick update.
When I opened a new remote-ssh window - all virtualenvs are listed properly.
That original remote-ssh window which remained open, however, is still not
showing them all.

**Comment by egamma** [comment]
FYI @qubitron

**Comment by qubitron** [comment]
@DonJayamanne @BrettCannon can you comment on whether the venvPath setting is expected to work here?

**Comment by DonJayamanne** [comment]
@uishon 
* When adding `"python.venvPath": "~/.virtualenvs"` do you not see the environments in WSL or SSH or both?
* Are there any errors logged in the `Console Window` accessible from `Help-> Toggle Developer Tools` menu.

> That original remote-ssh window which remained open, however, is still not
showing them all.

Is this still the case?

**Comment by uishon** [comment]
Sorry it took me some time to respond...

Anyway, now I see the virtual environments in both WSL and SSH.
That already opened ssh-window is closed by now so I can't really reply to
your question but at least as long as I kept it open, it never showed up
the virtualenvs list correctly. Only new windows did.

Uri.

**Comment by DonJayamanne** [comment]
@uishon Thanks for getting back to us. 
Its most likely the discovery of interpreters was taking a little longer than usual. The way it works is we discover interpreters in the background.

@kieferrm I believe we can consider this issue resolved.

**Comment by phtn** [comment]
install `Remote - WSL` extension.

**Comment by sleighsoft** [comment]
Not for WSL but I cannot change my environment on a linux server I am connected to. It properly lists all available conda environments but when selecting one (either from bottom menu / or by "select interpreter") nothing changes.

**Comment by brettcannon** [comment]
@sleighsoft are you saying that your Linux server isn't running under WSL?

**Comment by sleighsoft** [comment]
Yes, it is an ubuntu server. Not WSL.
And when I login with vscode remote I always defaults to the same conda environment and I cannot choose another one.

**Comment by fangaofeng** [comment]
i open folder with wsl，then File->Preferences-> settings->Remote [WSL:Ubuntu] change my setting, not effect.  it effect by local settings.
When i change .vscode/settings.json is same as Remote[WSL:Ubuntu].json, python can run. But it change local file .This Remote settings:
```
{
    "python.venvPath": "/home/fgf",
    "python.venvFolders": [
        "whlenv"
    ],
    "python.pythonPath": "/home/fgf/whlenv/bin/python",
    //"python.pipenvPath": "E:\\pythonvenv\\trainserver-PFVxFgBL\\Scripts\\pipenv.exe",
    //"python.pipenvPath": "C:\\Python\\Python37\\Scripts\\pipenv.exe",
    "python.terminal.activateEnvironment": true,
    "python.autoComplete.addBrackets": false,
    // "python.linting.flake8Enabled": true,
    "python.linting.pycodestyleEnabled": true,
    "python.formatting.provider": "autopep8",
    "python.formatting.autopep8Args": [
        "--max-line-length",
        "120",
        "--experimental"
    ],
    // "python.sortImports.args": ["-rc", "--atomic"],
    // "python.formatting.yapfArgs": ["--style", "{based_on_style:pep8}"],
    "editor.formatOnSave": true,
    "editor.tabCompletion": "on",
    "python.analysis.logLevel": "Trace",
    "python.analysis.diagnosticPublishDelay": 1000,
    "python.analysis.openFilesOnly": false,
    "python.analysis.symbolsHierarchyDepthLimit": 20,
    //"svn.path": "c:\\Program Files\\TortoiseSVN\\bin",
    "git.ignoreLimitWarning": true,
    "python.autoComplete.extraPaths": [
        "/home/fgf/whlenv/Lib/site-packages"
    ],
    "python.linting.pylintEnabled": false,
    "python.linting.maxNumberOfProblems": 120,
    "files.associations": {
        "**/templates/*.html": "django-html",
        "**/templates/*": "django-txt",
        "**/requirements{/**,*}.{txt,in}": "pip-requirements"
    },
    "emmet.includeLanguages": {
        "django-html": "html"
    }
}
```

**Comment by raeperd** [comment]
1. Ctrl + Shift + p
2. >python: Select Interpreter
3. Choose virtual environment 

This was my solution

**Comment by bamurtaugh** [comment]
Reviewing this thread - it looks like we can consider the original issue resolved? If folks aren't still experiencing it, I'll go ahead and close it.

**Comment by bamurtaugh** [comment]
Closing based on above comment - thanks all!
