### ISSUE TITLE
[Remote SSH] Source control view doesn't sync up with the editor when making changes in a git repository

### ISSUE THREAD

**Issue by JReinhold** [microsoft/vscode-remote-release#700]
- VSCode Version: `1.36.0-insider (1.36.0-insider)` and `Version 1.35.1 (1.35.1)`
- Local OS Version: `macOS Mojave 10.14.5`
- Remote OS Version: `Ubuntu 19.04`
- Remote Extension/Connection Type: SSH

This is actually two issues, but I thought they were so related that I decided to merge them in to one. Let me know if you want me to file them separately.

When changing files on the remote using the Remote SSH extension, the changes aren't shown in the Source Control view, until you manually press refresh. You have to press refresh every time you make changes.

And when discarding changes from the Source Control view, that discard isn't reflected in the editor until you reopen the file. Sometimes it works just to switch tabs.

Basically changes aren't synced up between the Source Control view and the editor view, but the two views works fine separately (eg. the editor immediately shows red/green/blue colors in the gutter when changing a line).

Steps to Reproduce:

1. Use the SSH extension to connect to a remote host
2. Open a folder that is under git version control.
3. Make changes to any file and save it.
4. Go to the source control view
5. **See that the changes aren't reflected under the "Changes" list**
6. Press the "Refresh" button in the top left corner
7. See that the changes are now correctly reflected.
8. While having a changed file opened in the editor, discard the changes in the Source Control view.
9. **See that the changes aren't reverted in the editor**
10. Close and open the file in the editor.
11. See that the changes are now correctly reverted in the file.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Let me know if you need any more information.

**Comment by joaomoreno** [comment]
> https://github.com/microsoft/vscode/issues/5970

Are you opening the root of the repository, or a subfolder?

Are you using symlinks at all?

Make sure you test the latest insiders. Today's version is: 6520c22b83c0b6f168ba7de3309ffab42281e905
