### ISSUE TITLE
VS Code Server

### ISSUE THREAD

**Issue by weixuehao** [microsoft/vscode-remote-release#7000]
error Could not create tunnel with name

![%W7@23)J1OZ3{(2`4%XH%2T](https://user-images.githubusercontent.com/94975686/181726229-1fe83918-8052-43fe-bf7c-2faf455ae02b.png)

**Comment by connor4312** [comment]
@derekbekoe is there any extra info you can provide based on the request ID in the user's screenshot? (2nd to last line)

**Comment by derekbekoe** [comment]
@weixuehao Thanks for signing up for the preview. Looks like you do not have access yet. You should receive an email from the team when your account is given access to the private preview.
See https://code.visualstudio.com/docs/remote/vscode-server#_how-can-i-get-access-to-the-vs-code-server
