### ISSUE TITLE
Remote Server extension - Allow user to connect to custom "code-server serve-local" URL

### ISSUE THREAD

**Issue by paulquack** [microsoft/vscode-remote-release#7002]
I am running `code-server` in `server-local` mode with my own custom SSL reverse proxy with cookie based authentication mechanism. I can currently access the code-server in a browser via a custom https url (i.e. not vscode.dev). I would like to use the VSCode app (on Mac) Remote Server extension to connect to the code-server instance. I think this is currently only possible via the built-in tunnelling mechanism/github authentication.

**Comment by tanhakabir** [comment]
This should be available to you now if you install the `ms-vscode.remote-server` extension on Desktop

**Comment by OneCyrus** [comment]
@tanhakabir I couldn't find this option. it still only allows me to connect to tunneled connections and not serve-local instances. where can I find this option?

**Comment by tanhakabir** [comment]
Oh I'm sorry I misread. No sorry we can't provide options to connect to serve-local instances. But serve local hosts the UI of VS Code on a port of your remote machine so if you can access that port externally then you can access that remote machine through serve-local. More details here: https://code.visualstudio.com/docs/remote/vscode-server#_can-i-host-vs-code-the-vs-code-server-myself

**Comment by OneCyrus** [comment]
you should reopen the issue then and look at it as a feature request. technically it shouldn't be much of a problem to solve this.

**Comment by tanhakabir** [comment]
This request isn't in the scope of serve-local since it was an advanced option for users who want to support their own remoting scenarios entirely.

**Comment by 3alpha** [comment]
Could this gently be nudged into the scope? 🙏 
I would just like to have consistent experience across devices on my home network. On devices that support VS Code app, I would use that, and on devices that don't I would use web browser. No authentication, no unnecessary overhead, just server IP and that is it. Currently, I need to use SSH remote to connect to the server and that's bit suboptimal

**Comment by gottwald** [comment]
I would have the exact same use-case.
There are environments where you aren't allowed to use a foreign tunneling service and you have to make a direct connection to your remote instance.
Just to be clear, I would love to start vscode-server on a wireguard interface on the remote VM (which is already possible, even behind a TLS reverse proxy) and then access it through a local vscode instance on my laptop instead of having to go through a browser.
Is there any chance that this would be added to the scope to make self-hosting possible?
