### ISSUE TITLE
crashes on name createment

### ISSUE THREAD

**Issue by MagneLindholm** [microsoft/vscode-remote-release#7003]
✔ What would you like to call this machine? · coding-hazard
[2022-07-30 10:51:09] info Creating tunnel with the name: coding-hazard
[2022-07-30 10:51:09] error Could not create tunnel with name: coding-hazard
Reason: ResponseError(ResponseError { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("global.rel.tunnels.api.visualstudio.com")), port: None, path: "/api/v1/tunnels", query: Some(""), fragment: None }, status_code: 403, data: Some("{\"title\":\"Request not permitted.\",\"status\":403,\"detail\":\"Unauthorized tunnel creation access: Authenticated user does not have 'create' access scope for the default tunnel domain.\"}"), request_id: Some("c70c9e89-6d59-487f-820a-7781405fd2c3") })

**Comment by giantsystems** [comment]
you missed the first step,

As the service that you use to securely connect to the VS Code Server is in private preview, you'll need to request access through a [signup form](https://aka.ms/vscode-server-signup). You'll receive an email, hopefully only within a few weeks, once you can start using the service.

**Comment by bamurtaugh** [comment]
Thanks for jumping in @giantsystems!

I believe that should address the issue, but @MagneLindholm please let me know if there's anything else, and I'm happy to reopen.
