### ISSUE TITLE
Devcontainers with features only launch if local workspace directory is on C drive

### ISSUE THREAD

**Issue by AlexHunterCodes** [microsoft/vscode-remote-release#7004]
- VSCode Version: 1.69.2
- Local OS Version: Windows 11 Pro H1H2 22000.795
- Remote OS Version: N/A
- Remote Extension/Connection Type: Containers
- Logs: https://gist.github.com/AlexHunterCodes/75be64f42182b07eb46a27940a796fa1

Steps to Reproduce:

1. On a Windows machine, clone repository https://github.com/microsoft/vscode-dev-containers.git (or any repo with a devcontainer that uses features) to a drive other than C. I used D in my example.
2. Wait for the workspace to relaunch and container to start building
3. After image layers are pulled, vscode will try to symlink `.devcontainer/Dockerfile` from D to `%TEMP%\vsch\containerfeatures\` on C, which will fail.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Tracking as https://github.com/devcontainers/cli/issues/240. Thanks.
