### ISSUE TITLE
Remote-containers ignore my .dockerignore

### ISSUE THREAD

**Issue by bonaccipp** [microsoft/vscode-remote-release#7007]
- VSCode Version: 1.69.2 (system setup)
- Local OS Version: Windows 11 Pro. version 21H2
- Remote OS Version: Debian GNU/Linux 11 (bullseye)
- Remote Extension/Connection Type: SSH/Containers/WSL/Server
- Extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers
- Logs:

For some strange reason my .dockerignore is being ignored. Why???

example repo: https://github.com/bonaccipp/Remote-Containers-ignore-my-.dockerignore.git

![image](https://user-images.githubusercontent.com/43193460/182484375-81d5cd0a-3b96-477b-88d2-ffed423bc63d.png)

Mr. [chrmarti](https://github.com/chrmarti) or someone else can help me???

thxs...

**Comment by bonaccipp** [comment]
... can someone help???

**Comment by chrmarti** [comment]
`/home/example` is mounted to your local folder. `.dockerignore` only applies to Docker's build context, but that doesn't affect the mounted folder.
