### ISSUE TITLE
Localize Issue - Remote-SSH Menu

### ISSUE THREAD

**Issue by ayatokura** [microsoft/vscode-remote-release#701]
Issue Type: <b>Bug</b>

1. Run Command Palette
2. Enter "Remote-SSH"
3. "View: Show Remote-SSH" menu doesn't seem displaying correctly that it shows "View: Show {0}"

![Remote_SSH_Menu](https://user-images.githubusercontent.com/12283147/59563741-e55c0880-9078-11e9-8558-9f9f6d537f93.png)

Extension version: 0.42.2
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.81GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by tanhakabir** [comment]
Hey @ayatokura are you still having a similar issue? The UI for Remote-SSH has changed a lot so I'm not sure this is as much of an issue anymore
