### ISSUE TITLE
WSL Localization bug

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-remote-release#7011]
![image](https://user-images.githubusercontent.com/12758612/182468909-f068a0d6-60cb-472a-a343-9a662e41a1c0.png)

**Comment by aeschli** [comment]
I verified that `remoteView.name` is in `package.nls.json`

**Comment by aeschli** [comment]
I don't see this:
![image](https://user-images.githubusercontent.com/6461412/185889753-a5d4d2c6-3b69-482c-9355-b930caff43dc.png)

@tanhakabir Can you give more details how to reproduce this?

**Comment by tanhakabir** [comment]
Hm I don't see this anymore. Not sure what happened in the past for me to see what I had screenshotted. Closing issue
