### ISSUE TITLE
vscode-server serve-local does not persist configuration / settings across browser sessions

### ISSUE THREAD

**Issue by ahmadnassri** [microsoft/vscode-remote-release#7014]
- VSCode Version: 1.69.2
- Local OS Version: Windows / Chrome
- Remote OS Version: Docker
- Remote Extension/Connection Type: Server

I'm running the new `vscode-server` preview on my local machine / [docker](https://github.com/ahmadnassri/docker-vscode-server):

```
dbus-run-session -- sh -c "(echo $VSCODE_KEYRING_PASS | gnome-keyring-daemon --unlock) && code-server serve-local --disable-telemetry --without-connection-token --host 0.0.0.0"
```

I've noticed that each browser instance _(e.g. different profiles on chrome)_ is generating a new configuration ... 

I'm persisting my `.vscode-server` folder, which keeps all the extensions installed, but seemingly the settings are not the same when switching browser instances, or restarting the docker container... all the relevant settings are seemingly stored in browser storage.

is there a way to persist (server-side) user configuration and (logged in state to Settings Sync) across restarts and different browsers?

**Comment by bamurtaugh** [comment]
@connor4312 @tanhakabir I've seen a few folks mention this.

**Comment by aeschli** [comment]
Your observation is correct, each browser/browser profile behaves like a separate machine and you need to connect to settings sync to share settings.
