### ISSUE TITLE
address already in use 127.0.0.1

### ISSUE THREAD

**Issue by yb3616** [microsoft/vscode-remote-release#7015]
- VSCode Version: 1.69.2
- Local OS Version: Windows 10
- Remote OS Version: CentOS Linux release 7.9.2009 (Core)
- Remote Extension/Connection Type: SSH
- Logs:
```
> [11:40:47] Extension host agent started.
> [11:40:47] Error occurred in server
> [11:40:47] Error: listen EADDRINUSE: address already in use 127.0.0.1
>     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
>     at listenInCluster (node:net:1382:12)
>     at doListen (node:net:1520:7)
>     at processTicksAndRejections (node:internal/process/task_queues:84:21) {    
>   code: 'EADDRINUSE',
>   errno: -98,
>   syscall: 'listen',
>   address: '127.0.0.1'
> }
```
![8X5HE5RG8CW@RIVA)~@7%)G](https://user-images.githubusercontent.com/8839021/182521550-14a3205e-5e88-4ce4-afb5-72bd535ad200.png)

Steps to Reproduce:

1. open vscode
2. open remote ssh

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

`rm -rf ~/.vscode-server` is useless.
another vps is success

**Comment by megaDannyIng** [comment]
same problem. can't connect even after reload pc

**Comment by yb3616** [comment]
> same problem. can't connect even after reload pc

reload remote linux server

**Comment by megaDannyIng** [comment]
> > same problem. can't connect even after reload pc
> 
> reload remote linux server

it helped, thanks.

**Comment by tanhakabir** [comment]
We need to connect to 127.0.0.1 and it looks like you've resolved your issue. Closing for now but let me know if you see other issues
