### ISSUE TITLE
Terminal does not start after opening a folder in Remote SSH

### ISSUE THREAD

**Issue by iansmathew** [microsoft/vscode-remote-release#702]
- VSCode Version:1.35.1 (user setup)
- OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Connect to Remote SSH via `Remote-SSH: Connect to host
2. Open Terminal. `Note: Works fine!`
3. Open a folder. Eg: `usr/src`
4. Open terminal again after remote is connected.
5. Terminal exits with process 1 and log `chdir(2): No such file or directory is found`

Does this issue occur when all extensions are disabled?: Yes (Remote Development - enabled)

### Description:
A terminal cannot be opened after opening a folder in the editor when connected via SSH. The bash location is not valid after opening a folder.

**Comment by Tyriar** [comment]
Could you try this with the VS Code Insiders build and the SSH nightly extension?

**Comment by iansmathew** [comment]
@Tyriar The issue is resolved using the latest VS Code insiders build (as of 16-6-2019).

I have tried both the SSH Nightly as well as the stable SSH extensions and the issue does not pop up in either one, so I'm guessing its a bug in Code.
