### ISSUE TITLE
Password prompts for SSH ignoring Private key permissions

### ISSUE THREAD

**Issue by manivmtc** [microsoft/vscode-remote-release#7024]
Type: <b>Bug</b>

Prompts for password to remote SSH host in spite of having correct permissions (Tried both 600 and 400) for private key file.  I dont use RSA encryption but rather ed25519. 

```
[11:17:17.331] > @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> Permissions for 'C:/Users/me/.ssh/mykey_ed25519' are too open.
> It is required that your private key files are NOT accessible by others.  
> This private key will be ignored.
> Load key "C:/Users/me/.ssh/mykey_ed25519": bad permissions    
> me@11.44.55.22's password:
[11:17:17.332] Showing password prompt
[11:17:21.008] Got password response 
```

Extension version: 0.84.0
VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Remote OS version: Linux x64 5.15.0-41-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 5650U with Radeon Graphics      (12 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.83GB (5.61GB free)|
|Process Argv|--crash-reporter-id d3493d5e-2bfd-45da-a2d4-a567b1b78f51|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.46.52.28|
|OS|Linux x64 5.15.0-41-generic|
|CPUs|Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz (8 x 3400)|
|Memory (System)|23.40GB (7.45GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30525689
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30535728
hb751961:30541207
dsvsc012:30540252

```

</details>

**Comment by tanhakabir** [comment]
When you try to connect outside of VS Code in a separate shell like Terminal or PowerShell what do you see?

**Comment by manivmtc** [comment]
Outside of VS code, I am able to ssh into the remote machine without a password . Another details is I dont use rsa but ed25519
