### ISSUE TITLE
Machine name prompt fails when pressing some non-character keys

### ISSUE THREAD

**Issue by patridge** [microsoft/vscode-remote-release#7025]
- VSCode Version: VS Code Server 20220727.1
- Local OS Version: Windows 11 Pro 21H2 (22000.831)
- Remote OS Version: n/a
- Remote Extension/Connection Type: n/a
- Logs:

Steps to Reproduce:

1. Install code-server, following along with [Windows (x64) instructions](https://code.visualstudio.com/docs/remote/vscode-server#_quick-start)
2. Run `code-server`
3. Accept terms
4. When asked "What would you like to call this machine?", press Ctrl or Caps Lock keys.

At this point, the `code-server` launch process will fail with an error and a timestamp.

> [2022-08-05 08:03:15] error Failed to read confirm input: Not a terminal

I triggered this because my server machine had a small wireless keyboard that I picked up, accidentally pressing Ctrl as I did so, causing the prompt to log the error and quit. But I could see someone wanting to Ctrl+V paste in a name or press Caps Lock to enable/disable that setting before entering a server name.

Does this issue occur when you try this locally?: Yes (happens during installation)
Does this issue occur when you try this locally and all extensions are disabled?: Yes (happens during installation)

**Comment by bamurtaugh** [comment]
@connor4312 with the recent updates to the VS Code Server runs with the [release](https://code.visualstudio.com/blogs/2022/12/07/remote-even-better) of the unified `code` CLI, can we close this one as we're not prompting for machine name?
