### ISSUE TITLE
Remote-SSH uses a wrong SSH configuration when it connects to the same host not the first time

### ISSUE THREAD

**Issue by intractabilis** [microsoft/vscode-remote-release#7027]
- VSCode Version: 1.69.2
- Electron: 18.3.5
- Chromium: 100.0.4896.160
- Node.js: 16.13.2
- V8: 10.0.139.17-electron.0
- Local OS Version: Linux x64 5.18.14-1-MANJARO
- Remote OS Version: Linux x64 5.18.14-1-MANJARO
- Remote Extension/Connection Type: SSH

Remote machine's SSH server is configured to accept `VS_CODE_CONFIG` environment variable, i.e. there is a line in `/etc/ssh/sshd_config`:
```
AcceptEnv VS_CODE_CONFIG
```
On the local desktop, I set up two SSH configurations (inside `~/.ssh/config`):
```
Host remote-config-1
  HostName remote
  User user
  IdentityFile ~/.ssh/id_something
  SetEnv VS_CODE_CONFIG=1

Host remote-config-2
  HostName remote
  User user
  IdentityFile ~/.ssh/id_something
  SetEnv VS_CODE_CONFIG=2
```
I expect that when I use `remote-config-1` for remote connection, `VS_CODE_CONFIG` will be equal to 1, and when I use `remote-config-2`, it will be equal to 2. I can verify it:
```
$ ssh remote-config-1
$ echo $VS_CODE_CONFIG
1
Connection to remote closed.
$ ssh remote-config-2
$ echo $VS_CODE_CONFIG
2
```
VS Code does everything correctly when it connects the first time. For example, open VS Code, choose "Remote-SSH: Connect to Host...", select `remote-config-1`, then in the VS Code terminal verify the value of `VS_CODE_CONFIG`, it will be 1. Now close VS Code, open again, choose "Remote-SSH: Connect to Host...", `remote-config-2`. Verify in the VS Code terminal the value of `VS_CODE_CONFIG`. It is still 1, instead of 2.

Log for the first connection:
```
[17:26:51.977] Log Level: 1
[17:26:51.978] remote-ssh@0.84.0
[17:26:51.978] linux x64
[17:26:51.994] Picking SSH host
[17:26:54.734] Selected remote-config-1
```
Log for the second connection:
```
[17:28:18.162] Log Level: 1
[17:28:18.163] remote-ssh@0.84.0
[17:28:18.163] linux x64
[17:28:18.181] Picking SSH host
[17:28:19.849] Selected remote-config-2
```

**Comment by shekhovt** [comment]
I guess this is related to that vscode-server is still running on host when you close VS Code on your desktop.
Try switching off 
"remote.SSH.useLocalServer"
(enables a mode of connecting using a single connection shared between windows and across window reloads....).
As you are using the same host, this sounds like it.

**Comment by eleanorjboyd** [comment]
Hello! If you use the command "kill vs code on remote server" then try to reconnect does it work?
