### ISSUE TITLE
"Using localhost in Docker Compose" doc can have some improvement

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode-remote-release#7031]
I think [this doc](https://code.visualstudio.com/docs/remote/create-dev-container#_using-localhost-in-docker-compose) can be improved for `forwardPorts` description.

Here is the issue I found.

1. I have a ASP.NET Core 6 app with a MS SQL Server database.

2. Add `.devcontainer` files to the project.

    I choose `C# (.NET) and MS SQL`.

3. The `.devcontainer/docker-compose.yml` file have the following comment.

   ```sh
   db:
     image: mcr.microsoft.com/mssql/server:2019-latest
     restart: unless-stopped
     environment:
       SA_PASSWORD: P@ssw0rd
       ACCEPT_EULA: Y
     # Add "forwardPorts": ["1433"] to **devcontainer.json** to forward MSSQL locally.
     # (Adding the "ports" property to this file will not forward from a Codespace.)
   ```

The `Add "forwardPorts": ["1433"] to **devcontainer.json** to forward MSSQL locally.` is misleading and [this doc](https://code.visualstudio.com/docs/remote/create-dev-container#_using-localhost-in-docker-compose) doesn't provide any details. The correct description should be `Add "forwardPorts": ["db:1433"] to **devcontainer.json**`.

I do find more details [here](https://code.visualstudio.com/docs/remote/devcontainerjson-reference#_general-devcontainerjson-properties). The [devcontainer.json reference](https://code.visualstudio.com/docs/remote/devcontainerjson-reference#_general-devcontainerjson-properties) is really helpful. If the doc can provide a link, that will be awesome. 👍

> I don't know where is the right place to create this issue. If I am creating the wrong place, please let me know. Thanks.

**Comment by chrmarti** [comment]
Continuing in https://github.com/devcontainers/templates/issues/221.
