### ISSUE TITLE
`No view` error when using server

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#7038]
- Run `code-server` on WSL
- Click on insiders.vscode.dev link
- insiders.vscode.dev opens successfully, but I get the following toast each time I open the link:

![image](https://user-images.githubusercontent.com/25310137/183521380-7ebedbb0-c54d-44a8-a5e2-404ffc03c464.png)

**Comment by tanhakabir** [comment]
should be fixed now too
