### ISSUE TITLE
Add default option: Open project in remote development mode?

### ISSUE THREAD

**Issue by redblue9771** [microsoft/vscode-remote-release#704]
First of all, I am very happy that vscode has increased remote development, and the experience is really very good!

For the time being, I basically developed based on **WSL**, but I have to click on the development project: new window->file->open folder->select **complex** path.

Are you planning to add an option that defaults to open in remote development mode? Includes a right-click registry menu. I know this is a challenging feature.

I am a Chinese developer, I have limited English expression skills, I hope you can understand! Thank you!

**Comment by egamma** [comment]
@redblue9771 the simplest way to open a folder in remote is to run `code .` or `code folderName` from the bash shell.

**Comment by redblue9771** [comment]
@egamma I understand what you mean, but this also requires opening the VSCode under Windows and entering the `code .` in the terminal to be valid.
My idea is whether it is possible to add ‘Open with the Visual Studio Code Remote Development’ to the windows context menu. Or provide an option in VSCode that opens the project  with the Visual Studio Code Remote Development by default.

**Comment by PalokhaO** [comment]
I absolutely second this request. My workflow requires multiple workspaces that I have bound to keyboard shortcuts (like ctrl-alt-f to open the frontend workspace). With remote-wsl now I need to open the local vscode first, then click two buttons, and then navigate through the explorer to the needed folder.

I would greately appreciate one of the following:
1) A way to save the remote connection as part of the workspace file.
2) A way to open Code connected to a remote server via CLI (like `code --remote-mode wsl`) 
3) Some other way to simplify the launch-connect-open sequence

**Comment by egamma** [comment]
@PalokhaO are using File>Open Recent this enables you to easily switch back to a preview workspace in remote context.

**Comment by egamma** [comment]
>@egamma I understand what you mean, but this also requires opening the VSCode under Windows and entering the code . in the terminal to be valid.

Actually this also works from a WSL terminal outside of VS Code. This means you do not need to open VS Code first.

**Comment by redblue9771** [comment]
> > @egamma I understand what you mean, but this also requires opening the VSCode under Windows and entering the code . in the terminal to be valid.
> 
> Actually this also works from a WSL terminal outside of VS Code. This means you do not need to open VS Code first.

Did I encounter a bug? I tried to open the command in an external terminal without any action, but it is normal inside VSCode. I make sure my PATH and environment settings are correct.

**Comment by egamma** [comment]
>Did I encounter a bug? I tried to use the command in an external terminal without any action, but it is normal inside VSCode. I make sure my PATH and environment settings are correct.

You have to do it in a WSL/Bash terminal not a Windows terminal.

**Comment by redblue9771** [comment]
> > Did I encounter a bug? I tried to use the command in an external terminal without any action, but it is normal inside VSCode. I make sure my PATH and environment settings are correct.
> 
> You have to do it in a WSL/Bash terminal not a Windows terminal.

I am pretty sure that I did this, I think I should reinstall it.

**Comment by redblue9771** [comment]
> I absolutely second this request. My workflow requires multiple workspaces that I have bound to keyboard shortcuts (like ctrl-alt-f to open the frontend workspace). With remote-wsl now I need to open the local vscode first, then click two buttons, and then navigate through the explorer to the needed folder.
> 
> I would greately appreciate one of the following:
> 
> 1. A way to save the remote connection as part of the workspace file.
> 2. A way to open Code connected to a remote server via CLI (like `code --remote-mode wsl`)
> 3. Some other way to simplify the launch-connect-open sequence

I think your thoughts are very good.

**Comment by redblue9771** [comment]
@egamma Although using the `code` command is a good choice, it comes at the cost of opening a terminal.  I don't think this is the best way. Compared to creating a new window from vscode, this really simplifies the path, but it still needs to close the old window.  I prefer to get a simple and friendly experience.

**Comment by redblue9771** [comment]
It is also possible to add an option to reload a window using remote development from the current path in addition to the option to create a new window in vscode.  For the case of using commands, I can customize an alias with an exit command in the terminal.

But no matter what, I still need to activate the remote development mode.  For situations where the mode is heavily dependent (generally WSL, because the environment of SSH and Docker always changes), it is best to use this mode when opening any file with vscode.

**Comment by egamma** [comment]
//fyi @aeschli

**Comment by aeschli** [comment]
The remote wsl extension can not contribute actions to the Windows explorer.
But I added a new command `Open in WSL` that opens the folder/workspace that is currently open in VSCode in WSL.

It will be in the next release. Please try it out and let me know if this helps or needs more improvement.

**Comment by redblue9771** [comment]
@aeschli I have updated to get this feature, currently it works very well and is a lot easier, thank you!
