### ISSUE TITLE
Failed to connect to the remote extension host server (Error: Failed to write install script to path

### ISSUE THREAD

**Issue by Kevan-y0** [microsoft/vscode-remote-release#7040]
Since I uninstalled the BaiduNetdisk, accidentally I deleted the ssh remote connection temp, and such an error occurred. 
I re-created the temp folder under the E:\BaiduNetdisk, and the error was resolved.
But I was stranged how can the temp folder be under the E:\BaiduNetdisk?I have never configured it like this.

![image](https://user-images.githubusercontent.com/81600855/183589576-16ba83c4-8f7b-4c74-9b41-6f284d4b48a6.png)

**Comment by eleanorjboyd** [comment]
Hello! My name is Eleanor and I am the new maintainer for the Remote-SSH extension. Are you still experiencing this issue?

**Comment by eleanorjboyd** [comment]
looks to be the same issue here: https://github.com/microsoft/vscode-remote-release/issues/2920. I will investigate if there is an easier solution.
