### ISSUE TITLE
Lot of crashes recently

### ISSUE THREAD

**Issue by krzikalla** [microsoft/vscode-remote-release#7041]
I experience crashes since some weeks. During the last days it is happening so frequently, that I can't consider it a productive environment anymore. 
Often it happens after I change to the VS Code main window, but sometimes also, if the window is already in the foreground. 
Maybe related: sometimes, if I change to the VS Code main window, it stalls for quite while before it gets back to work.

The crash starts with a Windows message box: `The window has crashed (reason: 'oom', code: '-536870904').`
If I click 'Reopen', VS Code restarts. However a VS Code message box appears: `Failed to connect to the remote extension host server (Error: Cannot resolve authority).`
All editor windows are blank with a message in the center: `The editor could not be opened due to an unexpected error: No file system provider found for resource 'vscode-remote://ssh-remote...'.`
After closing and reopening by hand, VS Code works again (for a while).

- VSCode Version: 1.70.0
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: SSH (I guess, how do I know?)

**Comment by tanhakabir** [comment]
Sorry about this! Would you be able to attach your crash logs when you see the crash happen? https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
