### ISSUE TITLE
Unauthorized tunnel creation access: Authenticated user does not have 'create' access scope for the default tunnel domain

### ISSUE THREAD

**Issue by pirafrank** [microsoft/vscode-remote-release#7043]
- VSCode Version: VS Code Server 20220727.1
- Local OS Version: iOS 15.6 via Blink Shell over ssh connection
- Remote OS Version: Debian GNU/Linux 11 (bullseye), kernel Linux 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux
- Remote Extension/Connection Type: SSH
- Logs:

❯ code-server serve
✔ What would you like to call this machine? · adoring-cuckoo
[2022-08-10 01:14:39] info Creating tunnel with the name: adoring-cuckoo
[2022-08-10 01:14:40] error Could not create tunnel with name: adoring-cuckoo
Reason: ResponseError(ResponseError { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("global.rel.tunnels.api.visualstudio.com")), port: None, path: "/api/v1/tunnels", query: Some(""), fragment: None }, status_code: 403, data: Some("{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.3\",\"title\":\"Request not permitted.\",\"status\":403,\"detail\":\"Unauthorized tunnel creation access: Authenticated user does not have 'create' access scope for the default tunnel domain.\",\"traceId\":\"00-36654ac7245228a33873ce0fc2d3520c-f502168ace8aa86c-00\"}"), request_id: Some("6df80205-127a-40b9-9575-d8874f8e01d1") })

Steps to Reproduce:

1. connect to the machine over SSH
2. Run `code-server` (first run) or `code-server server (other tests)

No extensions have been installed, this has actually never started.

As per troubleshooting and other issues, it looks like I have not been added to the VS Code Server Preview, yet I have received an email about that a couple of days ago.
I have also tried deleting the ~/.vscode-cli folder and running `code-server` again to go through the setup process once more. I have logged in using this GitHub account (pirafrank), the same I've filled in the Preview sign up form.

Attached below two images about the error and the mentioned email.

Thank you.

![5C87CF3A-515D-40A0-8128-BB135F5972BC](https://user-images.githubusercontent.com/3326151/183855946-55869780-2f36-4045-9435-60f14235ecc1.png)
![B3D1E7CB-AD5F-4318-9EDA-93FFAD62E011](https://user-images.githubusercontent.com/3326151/183855951-1e096c3b-0528-49a2-9a3a-8477031bbb46.jpeg)

**Comment by bamurtaugh** [comment]
@curib could you take a look?

**Comment by jfullerton44** [comment]
@pirafrank can you try again now?

**Comment by pirafrank** [comment]
@jfullerton44 Bingo! It works, now it's play time. Thank you all for your support.

**Comment by criox4** [comment]
@pirafrank can you please let me know how much time did it take for you to be approved for VS Code Server Preview. I had applied for it like 2-3 months earlier and I am yet to get notified anything regarding the acceptance.

**Comment by pirafrank** [comment]
Hi, it was about one month iirc
