### ISSUE TITLE
Unable to access ssh keys on host when in dev container

### ISSUE THREAD

**Issue by JaimieWi** [microsoft/vscode-remote-release#7044]
- VSCode Version: Remote-Containers 0.241.3 in VS Code 1.70.0
- Local OS Version: macOS Monterey version 12.5
- Remote OS Version: 
- Remote Extension/Connection Type: Remote-Containers
- Logs:

Steps to Reproduce:

1. Open folder in container
2. `git pull` (to a remote repo within Azure DevOps)
3. Asked for git@ssh.dev.azure.com password. Permission denied

Checks done:
1. SSH_AUTH_SOCK is set inside the container.
2. `ssh -v ssh.dev.azure.com` is not showing any keys from the host, indicating that something is not working in the forwarding.
<img width="630" alt="Screenshot 2022-08-10 at 15 52 36" src="https://user-images.githubusercontent.com/92854957/183935136-fbb9f2b3-f6ea-4e7f-b605-b464f8f697ef.png">
<img width="803" alt="Screenshot 2022-08-10 at 15 53 15" src="https://user-images.githubusercontent.com/92854957/183935425-7625a7aa-9638-4387-a514-34c1462fea79.png">

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No
Only happens when in a dev container

**Comment by chrmarti** [comment]
Does `ssh-add -l` in the container show any keys? Try adding them on the host with `ssh-add` if they are not listed.

**Comment by JaimieWi** [comment]
That worked! Thank you very much for your help

`ssh-add -l` returned 'The agent has no identities.'
Adding the private key to host solved the issue
