### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#7045]
We've heard a good amount of user feedback that port forwarding would be a valuable addition to the VS Code Server. I didn't see an issue here tracking it, but please let me know if we already have one.

cc @Chuxel @burkeholland as we've discussed this.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-cli/issues/373

**Comment by bamurtaugh** [comment]
Moving the context from the other issue here:

- Automatically forward the port where the server is run
- Automatically forward ports after that, i.e. if a user is running a web app

**Comment by connor4312** [comment]
I've implemented port forwarding in the linked commit, which I think closes the issue. For automatic forwarding, [according to Alex](https://github.com/microsoft/vscode-internalbacklog/issues/2652#issuecomment-1025590249), we need a change in core: https://github.com/microsoft/vscode/issues/141737
