### ISSUE TITLE
Session can't be established because of missing `tar` insufficiently communicated

### ISSUE THREAD

**Issue by happylynx** [microsoft/vscode-remote-release#7048]
Type: <b>Bug</b>

1. Get a linux machine with sshd, without `tar` installed
2. Try to open remote ssh session there

Expected result: Establishing session fails. The issue is communicated to user in way that it is obvious what the root cause is - `tar` is missing.

Actual result: Establishing session fails. No explanation provided.

Extension version: 0.84.0
VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Connection to 'SSH' could not be established  Failed to install the VS Code Server
Remote OS version: Linux x64 4.18.0-372.19.1.el8_6.x86_64

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30529769
vsclangdf:30486550
c4g48928:30535728
hb751961:30543456
dsvsc012:30540252

```

</details>

**Comment by eleanorjboyd** [comment]
Hello! My name is Eleanor and I am in the new Remote-SSH maintainer! Quick clarifying question, when you say "Actual result: Establishing session fails. No explanation provided." Is there no explanation in terms of a pop up message or does it say nothing in the logs? What error message is mentioned in the logs? Is there any generic error message or no notice of the error is produced?
