### ISSUE TITLE
Server commands in vscode.dev aren't working

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#7053]
- Open insiders.vscode.dev or vscode.dev
- Click remote indicator
- Try any of the server commands:
![image](https://user-images.githubusercontent.com/25310137/184222974-c3d84ece-aeb4-4be1-a722-0c80535f4440.png)

- I see `Activating Extensions` in the status bar, but then nothing happens

**Comment by loligans** [comment]
I'm also having this issue. When I go to the log window tab, all I see is:

`[window] [info] Request to 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-server/0.1.2022081218/extension/package.nls.json' failed with status code 404`

**Comment by tanhakabir** [comment]
This should be fixed now. Let me know if you're still seeing an issue
