### ISSUE TITLE
Mac M1 - Dev Container UI isn't consistent with Win 11

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-remote-release#7054]
Please see [StackOverflow item](https://stackoverflow.com/questions/73323433/vscode-remote-containers-m1-ver-win11).

**Comment by burkeholland** [comment]
I see it on my M1...

![image](https://user-images.githubusercontent.com/686963/184265430-abe7efd5-8622-458f-a644-231842df1856.png)

**Comment by chrmarti** [comment]
@diberry Make sure Remote-Containers is installed and enabled. It can be enabled/disabled from the context menu in the Extensions viewlet.
