### ISSUE TITLE
Allow opening the server link in the desktop app

### ISSUE THREAD

**Issue by frejonb** [microsoft/vscode-remote-release#7055]
It would be useful if the insiders.vscode.dev link could be open in the VSCode app as well. This allows to use the server from any location and with the best experience for the device. For example I might be content with the quirks of the browser experience in a tablet, but in a desktop I rather have the full experience.

**Comment by tanhakabir** [comment]
If you install the Remote Server extension in your Desktop app, you should be able to connect there as well through the Remote Indicator at the bottom. Let me know if this doesn't work for you!

**Comment by frejonb** [comment]
Thanks. I wasn’t aware of it. This is the link for anyone wondering: https://marketplace.visualstudio.com/items?itemName=ms-vscode.remote-server
