### ISSUE TITLE
code-server hangs without showing authentication url

### ISSUE THREAD

**Issue by bilby91** [microsoft/vscode-remote-release#7056]
Today I got my invite approved to start working with code-server. When running `code-server`, the login URL for GitHub never shows up. I tried running with verbose mode and couldn't find any extra clues.

- VSCode Version: 20220810.1
- Local OS Version: None (Yet)
- Remote OS Version: Linux linux-server 5.4.0-7634-generic #38~1596560323~20.04~7719dbd-Ubuntu SMP Tue Aug 4 19:12:34 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- Remote Extension/Connection Type: SSH/Containers/WSL/Server
- Logs: None

Steps to Reproduce:

1. code-server

**Comment by tanhakabir** [comment]
Could you share your verbose logs?

**Comment by connor4312** [comment]
Verbose logs in the most recent release will contain verbose details about HTTP connections. If you're able to get these logs, that would be helpful, but we haven't heard back so I will close this for now.
