### ISSUE TITLE
Mix "Remote" & "Local" folders in workspace.

### ISSUE THREAD

**Issue by jimbomorrison** [microsoft/vscode-remote-release#706]
Under "Remote Development using SSH" would it be possible to mix local & remote folders in a single Workspace configuration please?

**Comment by egamma** [comment]
Having a mixed workspace would require that a workspace extension can be active both locally and remotely. Currently an extension can only be active once, either locally or remotely. So this is currently not possible and we have no plans to support this.
The recommendation is to have separate windows open for the local and remote workspace.

**Comment by jimbomorrison** [comment]
Okay, makes sense. Thanks Erich.
