### ISSUE TITLE
403 while setting code-server

### ISSUE THREAD

**Issue by swastika-ui** [microsoft/vscode-remote-release#7064]
- VSCode Version: 1.71 (Insider)
- Local OS Version: MacOS Ventura Beta 5
- Remote OS Version: -
- Remote Extension/Connection Type: -
- Logs:

```
[2022-08-13 08:59:55] error Could not create tunnel with name: great-goshawk
Reason: ResponseError(ResponseError { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("global.rel.tunnels.api.visualstudio.com")), port: None, path: "/api/v1/tunnels", query: Some(""), fragment: None }, status_code: 403, data: Some("{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.3\",\"title\":\"Request not permitted.\",\"status\":403,\"detail\":\"Unauthorized tunnel creation access: Authenticated user does not have 'create' access scope for the default tunnel domain.\",\"traceId\":\"00-5358308cf58091de765d71048551b91b-2b8a6a4a1c0eccd2-00\"}"), request_id: Some("951740de-e0e8-4935-8720-cc54e2089474") })
```

Recently, I got access to VS code-server. After following the steps mentioned in the blog/documentation I'm getting the above error in my Mac while setting it up. I authenticated GitHub with the access code provided, however I'm getting 403.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by jcouball** [comment]
I am seeing the same issue when setting up code-server on a new host.

```
~ » code-server
✔ What would you like to call this machine? · vigilant-magpie
[2022-08-13 23:46:16] info Creating tunnel with the name: vigilant-magpie
[2022-08-13 23:46:17] error Could not create tunnel with name: vigilant-magpie
Reason: ResponseError(ResponseError { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("global.rel.tunnels.api.visualstudio.com")), port: None, path: "/api/v1/tunnels", query: Some(""), fragment: None }, status_code: 403, data: Some("{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.3\",\"title\":\"Request not permitted.\",\"status\":403,\"detail\":\"Unauthorized tunnel creation access: Authenticated user does not have 'create' access scope for the default tunnel domain.\",\"traceId\":\"00-d61b6894a4885d90dc5c70d31e18fa8d-f031075dcc0b89f8-00\"}"), request_id: Some("1ee9a502-4111-48ec-beca-32d1af192651") })
~ »
```

**Comment by shyamsantoki** [comment]
Same is happening while setting up code-server on new machine

**Comment by connor4312** [comment]
Please check out https://github.com/microsoft/vscode-remote-release/issues/6912#issuecomment-1179184173

**Comment by jcouball** [comment]
@connor4312, I believe I have already signed up and been accepted into the program and received a confirmation email.  I had already set this up once, but because of a security issue with the VM I used, I had to destroy that VM and use a new one.

**Comment by swastika-ui** [comment]
@connor4312 I got this email. After following the steps mentioned in the blog post/documentation, I am getting the 403.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/91778902/184986646-356208d3-3e9e-488e-8661-569ce725bd4b.png">

**Comment by connor4312** [comment]
@bamurtaugh @curib can you help out?

**Comment by jcouball** [comment]
@connor4312 thank you for reopening.

**Comment by curib** [comment]
Thanks for tagging me, @connor4312! 

@jcouball, @shyamsantoki, and @swastika-ui could ya'll try again and let us know if it works? Thank you!

**Comment by sakujiro-inagaki** [comment]
I am probably experiencing the same problem.

- Remote OS Version: Ubuntu 22.04 LTS
- VS Code Server Version: VS Code Server 20220903.2

@curib, can you help me?

```
[2022-09-03 16:56:05] info Creating tunnel with the name: infallible-greenbul
[2022-09-03 16:56:07] error Could not create tunnel with name: infallible-greenbul
Reason: ResponseError(ResponseError { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("global.rel.tunnels.api.visualstudio.com")), port: None, path: "/api/v1/tunnels", query: Some(""), fragment: None }, status_code: 403, data: Some("{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.3\",\"title\":\"Request not permitted.\",\"status\":403,\"detail\":\"Unauthorized tunnel creation access: Authenticated user does not have 'create' access scope for the default tunnel domain.\",\"traceId\":\"00-eb67963fcc41112cb5caf752b2161ee5-cb56422740546221-00\"}"), request_id: Some("b0a60bb1-e35e-48f1-82fa-ab26280881dd") })
```
![スクリーンショット 2022-09-04 2 08 00](https://user-images.githubusercontent.com/81898143/188281243-24c2046e-6b76-44d4-b3ce-6f3fd8c9f47b.png)
