### ISSUE TITLE
can't connect to the remote CentOS host!

### ISSUE THREAD

**Issue by FantasyJXF** [microsoft/vscode-remote-release#707]
I use the terminal on MAC with ssh `root@address -p port` to connect the remote CentOS server, after I enter the passwd, I can login into the server.

BUT, with vscode stable or insider, I use the Remote-SSH extension and configure the ~/.ssh/config with hostname, User, Port, IP. I could't connected to the server, I have successfully enter the passed, and another window jumped out and I entered the passwd again, and the ERROR MESSAGE is 

```
Tunnel(35495) stderr: Permission denied, please try again.

Tunnel(35495) stderr: Permission denied, please try again.

Tunnel(35495) stderr: root@xxx.xxx.xxx.xx: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
```

Looking forward to your replay

**Comment by suryasr007** [comment]
Are you facing the similiar error for  passwordless authentication ?

**Comment by FantasyJXF** [comment]
> Does your password consist of special characters?
> If so refer: [issue 688](https://github.com/microsoft/vscode-remote-release/issues/688#issuecomment-502241774)
> 
> Are you facing a similar error for passwordless authentication?

Thanks for your reply,  not sure the answer works or not.  Since now I use Jump Sever, don't have the chance to try.  

Pity

**Comment by roblourens** [comment]
Is this still an issue? Sorry for the slow response.
