### ISSUE TITLE
Password not working

### ISSUE THREAD

**Issue by amelieEmily** [microsoft/vscode-remote-release#7070]
Hello,

recently I realized I cannot connect to the server I have been connecting for that past month with the same password.

I checked on the other consoles and the password seems to work fine on those, but when I try to connect through vscode, it seems to give me a hard time.

I also realized that there is a $mark attached at the front of my username when I try to connect and I was guessing that might have something to do with the issue?

so the prompt shows like:

_Enter password for **$**\<my username\>@\<my server name\>_

can you look into this?

**Comment by tanhakabir** [comment]
Hello! Could you share the logs of what you see?
