### ISSUE TITLE
VSCode terminal not refreshing when new pwsh commands are installed (dotnet)

### ISSUE THREAD

**Issue by OMikkel** [microsoft/vscode-remote-release#7076]
Type: <b>Bug</b>

I am having trouble with the integrated VSCode terminal when ssh connected to a remote host. In this instance i am connected via SSH to a windows vm.

I just installed all the .net packages necessary to start developing, obviously you have to restart the pwsh terminal for the commands to become available and so i did. 
The command (dotnet) works fine in the pwsh terminal via remote desktop, however i cant figure out how to update the commands in the VSCode terminal on my machine via SSH. The command (dotnet) just wont work, it keeps telling me it is an unkown cmd.
Spent an hour and havent managed to figure it out, cant even find any similar issues online.

Heres what i have tried
- Restarting my pc two times just to be greeted by the same awful errors
- Restarted vscode 20 or so times
- Reinstalled the extension and cleared the known hosts
- Checked that the command is available via remote desktop
- Updated my machines pwsh to version 7

What i havent tried
- Restarting the VM - it is such a pain to start every running program again

Extension version: 0.84.0
VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Windows_NT x64 10.0.20348

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (24.20GB free)|
|Process Argv|--crash-reporter-id 1e96fddb-eb32-4c94-a3d9-3571a5acb539|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 23.88.120.42|
|OS|Windows_NT x64 10.0.20348|
|CPUs|Intel Xeon Processor (Skylake, IBRS) (4 x 2095)|
|Memory (System)|15.62GB (10.41GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30543456
dsvsc012:30540252
azure-dev_surveyone:30548225

```

</details>

**Comment by tanhakabir** [comment]
Hm I'm sorry you're seeing these issues. I'll try to repro on my end. Would you also be able to share your Remote SSH logs?

**Comment by OMikkel** [comment]
> Hm I'm sorry you're seeing these issues. I'll try to repro on my end. Would you also be able to share your Remote SSH logs?

Where do i find the logs - Under output?

**Comment by tanhakabir** [comment]
https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues

**Comment by OMikkel** [comment]
Will do it when i get home

**Comment by OMikkel** [comment]
Here are the logs, I just removed the ip
[Remote - SSH Logs.txt](https://github.com/microsoft/vscode-remote-release/files/9376964/Remote.-.SSH.Logs.txt)

FYI: The command is still not working after a few days and restarts :)
My computer: https://i.imgur.com/0bOKtgk.png
Remote machine: https://i.imgur.com/bko4y5e.png

**Comment by roblourens** [comment]
This just means the command is not on your PATH- you will have to configure the PATH on your remote, and this depends on your own setup
