### ISSUE TITLE
Continue on Remote SSH session locally

### ISSUE THREAD

**Issue by allendred** [microsoft/vscode-remote-release#7078]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/4343664/185023525-da5c5f3f-2c00-4e89-9d1e-e1df8ca36035.png">

When the ssh remote connection is disconnected, I can't open the local code, is this normal, and if this is normal, can I add a function to meet my needs
Intuitively, a local backup should always exist, like pycharm

**Comment by ThiefMaster** [comment]
I think that's a bug in the latest insiders (how did a breaking bug like this make it in there, and more important WHY IS THERE STILL NO OPTION TO ROLLBACK TO THE PREVIOUS VERSION?!).... not really related to loval vs remote files.

**Comment by tanhakabir** [comment]
>  I can't open the local code

Do you mean another workspace or the same code locally?

**Comment by allendred** [comment]
> > I can't open the local code
> 
> Do you mean another workspace or the same code locally?
The same code locally
This might be an extra feature

**Comment by tanhakabir** [comment]
Yes sorry we haven't supported this before

**Comment by tanhakabir** [comment]
Are you remotely connected to your localhost machine and then wanting to edit that code after locally?

**Comment by roblourens** [comment]
VS Code Remote isn't designed to work offline. If you are disconnected, don't expect to have files locally. It's not clear that there's anything broken here that was working previously
