### ISSUE TITLE
Cannot use Remote-Containers when %userprofile% has German umlauts in it's path

### ISSUE THREAD

**Issue by lhaussknecht** [microsoft/vscode-remote-release#7079]
Type: <b>Bug</b>

On a Windows 11 system with a user that has umlauts in his/her name and thus with a %userprofile%  with umlauts Remote-Containers cannot start.

Extension version: 0.245.0
VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Logs: [gist](https://gist.github.com/lhaussknecht/c42ae6f5dfacbc2fae07a72d08c6660e)
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253
azure-dev_surveyone:30548225

```

</details>

**Comment by chrmarti** [comment]
It can't find tar, not sure if that is related to the username. What do you get for running `(gcm tar).Path` in PowerShell?

**Comment by lhaussknecht** [comment]
Hi, thanks for taking your time.

```
❯ (gcm tar).Path
C:\Windows\system32\tar.exe
```

**Comment by chrmarti** [comment]
If you have Node.js installed, what do you get for running `node -p "process.env.PATH.split(';')"` in a terminal?
