### ISSUE TITLE
link remote-ssh with centos 6.5 give a suggestion:Failed to parse remote port from server output: 87f2eb5e-2df6-47dd-801d-d4350c24fe97====

### ISSUE THREAD

**Issue by zz940522** [microsoft/vscode-remote-release#708]
🚨 The issue tracker is not for questions 🚨

remote-ssh@0.42.2
SSH Resolver called for "ssh-remote+alias"
SSH Resolver called for host: alias
Setting up SSH remote "alias"
Using commit id "553cfb2c2205db5f15f3ee8395bbd5cf066d357d" and quality "insider" for server
Install and start server if needed
> 
> Found existing installation at /root/.vscode-server-insiders/bin/553cfb2c2205db5
> f15f3ee8395bbd5cf066d357d...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Server did not start successfully. Full server log:
> 87f2eb5e-2df6-47dd-801d-d4350c24fe97====
> 
"install" terminal command done
Received install output: 87f2eb5e-2df6-47dd-801d-d4350c24fe97====
Failed to parse remote port from server output: 87f2eb5e-2df6-47dd-801d-d4350c24fe97====

**Comment by kjhughes097** [comment]
I have a similar issue with Raspbian (Stretch).

`> Server did not start successfully. Full server log >>>
> /home/pi/.vscode-server-insiders/bin/7f53e50cbf316dff94fbbe5406d8f352dac99a6b/server.sh: 12: /home/pi/.vscode-server-insiders/bin/7f53e50cbf316dff94fbbe5406d8f352dac99a6b/server.sh: /home/pi/.vscode-server-insiders/bin/7f53e50cbf316dff94fbbe5406d8f352dac99a6b/node: Exec format error
> <<< End of server log
> ad408f97-01a6-4cd3-96fa-67eaf58f3ad8====
"install" terminal command done
Received install output: ad408f97-01a6-4cd3-96fa-67eaf58f3ad8====
Failed to parse remote port from server output: ad408f97-01a6-4cd3-96fa-67eaf58f3ad8====`
When I connect to the pi manually and run the `server.sh` it tells me :+1: 
`pi@wallboard:~/.vscode-server-insiders/bin/7f53e50cbf316dff94fbbe5406d8f352dac99a6b $ ./server.sh 
./server.sh: 12: ./server.sh: ./node: Exec format error`
Running `./node` I get:
`pi@wallboard:~/.vscode-server-insiders/bin/7f53e50cbf316dff94fbbe5406d8f352dac99a6b $ ./node
-bash: ./node: cannot execute binary file: Exec format error`
I'm guessing it's something to do with the Linux dependencies, but there's none listed for Raspberry currently...

**Comment by roblourens** [comment]
@zz940522 for centos 6.5 I think you are seeing https://github.com/microsoft/vscode-remote-release/issues/103

@kjhughes097 Make sure that you are using the nightly version of the extension. If you connected with the stable version before, run the command "Uninstall VS Code Server" first
