### ISSUE TITLE
Pre-release Version of Remote SSH Failing to Connect

### ISSUE THREAD

**Issue by IcySlurpee** [microsoft/vscode-remote-release#7084]
- VSCode Version: 1.71.0-insider (user setup), commit `dd0ed9381`
- Local OS Version: Windows 10 Pro 21H2 19044.1889
- Remote OS Version: macOS Monterey 12.5, Manjaro Linux 21.3.7 - kernel 5.19.1.
- Remote Extension/Connection Type: SSH
- Logs: [vscode-app-1660759130145.log](https://github.com/microsoft/vscode-remote-release/files/9365119/vscode-app-1660759130145.log)

Steps to Reproduce:
1. Install pre-release version of "Remote - SSH" (version v0.85.2022081715).  Preview release (version v0.84.0) does not have this bug.
2. Attempt to connect to a host via SSH.
3. Receive an error that reads "Cannot activate the 'Remote - SSH' extension because it depends on the 'Remote Explorer' extension which is disabled."
4. Viewing the console logs, it appears vscode can't resolve the `remote-ssh` extension, however it is installed.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes, I removed all extensions and only installed "Remote - SSH" to see if there was a different extension causing this issue.

**Comment by tanhakabir** [comment]
This should be fixed with the latest release of the Remote Explorer extension. Please let me know if you're still seeing this after updating

**Comment by YXL76** [comment]
`Remote - SSH (v0.85.2022081715)` with `Remote Explorer (v0.1.2022081809)` still not working.

**Comment by andreyan-andreev** [comment]
not working. totaly broken. shame! :)

**Comment by tanhakabir** [comment]
Could you all try SSH extension version `0.85.2022081816` for me? Sorry about the troubles!

**Comment by IcySlurpee** [comment]
Remote SSH `0.85.2022081816` is working for me, thanks!
