### ISSUE TITLE
Can't perform search on workspace in WSL

### ISSUE THREAD

**Issue by ckoryom** [microsoft/vscode-remote-release#709]
I am not able to perform a search on my WSL workspace. Opening a file allows me to search in that particular file, but if I want to find something inside other files in the workspace it just doesn't work.

![image](https://user-images.githubusercontent.com/3449097/59597037-2bf14780-90f9-11e9-991d-a1b1a2eb08ca.png)

**Comment by ckoryom** [comment]
When opening a new remote window, I go ahead and open a folder on my WSL distro.

Pressing ctrl+shift+f leads me to the Search panel. Trying to search anything there doesn't give me any result back.

The expected behavior should return the list of files which contain the searched keyword.

**Comment by aeschli** [comment]
Yes, search should look into all file inside the workspace.
I jst tried that in my WSL remote window, at it worked.
Please check:
- that the explorer shows one or more files
- your `search.exclude` settings (e.g. by default we exclude everything inside `node_modules`
- if there's anything interesting in the logs (View > Output, Log (Remote Server / Remote Extension Host)

**Comment by ckoryom** [comment]
Ok so I just rechecked and I am still having the same issue:

- [x ] the explorer shows a file
- [x ] search.exclude looks ok (only the node_modules and brew are excluded)
- [x ]  the logs are not showing any issues or anything interesting

On the screenshot you can see the problem:

File search works when a file is opened in the editor, it finds the text on the opened file naturally:

![file_explorer](https://user-images.githubusercontent.com/3449097/59669800-2b20ea00-91bb-11e9-9d1f-806463838a7d.PNG)

Here is the search working with the opened file in the editor.

![search_with_file_opened_in_editor](https://user-images.githubusercontent.com/3449097/59669816-307e3480-91bb-11e9-84fb-11d03d1497d0.PNG)

Now with the file closed in the editor (but still showing in the explorer) I cant find anything:

![search_with_file_not_opened_in_editor](https://user-images.githubusercontent.com/3449097/59669871-45f35e80-91bb-11e9-8513-fb44dbbcd639.PNG)

**Comment by roblourens** [comment]
Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" and the "Log (Remote Extension Host)" output channels

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by ckoryom** [comment]
Thanks for the support!

This is what I'm getting from "Log (Remote Extension Host)"

![image](https://user-images.githubusercontent.com/3449097/59718232-01e37680-921a-11e9-809e-ddb680834ad0.png)

**Comment by roblourens** [comment]
Hm, is it possible that your remote is very low on memory?

**Comment by ckoryom** [comment]
hmm, I don't think so, here is the result for ulimit on my WSL:

ulimit:

output: unlimited

cat /proc/meminfo

MemTotal:       33361176 kB
MemFree:        22214124 kB
Buffers:           34032 kB
Cached:           188576 kB
SwapCached:            0 kB
Active:           167556 kB
Inactive:         157876 kB
Active(anon):     103104 kB
Inactive(anon):    17440 kB
Active(file):      64452 kB
Inactive(file):   140436 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:      62392956 kB
SwapFree:       62367264 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:        102824 kB
Mapped:            71404 kB
Shmem:             17720 kB
Slab:              13868 kB
SReclaimable:       6744 kB
SUnreclaim:         7124 kB
KernelStack:        2848 kB
PageTables:         2524 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      515524 kB
Committed_AS:    3450064 kB
VmallocTotal:     122880 kB
VmallocUsed:       21296 kB
VmallocChunk:      66044 kB
HardwareCorrupted:     0 kB
AnonHugePages:      2048 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       12280 kB
DirectMap4M:      897024 kB

**Comment by bilogic** [comment]
I can't switch/go to an existing file via ```ctrl-p``` when using remote development, is this under WSL? or?

**Comment by roblourens** [comment]
@bilogic please open your own issue with more details and the same logs. 

@ckoryom I don't know why ripgrep is trying to access an invalid memory address. FYI @burntsushi

**Comment by BurntSushi** [comment]
Dunno. I'd need a much more targeted reproduction for this. A full command and the input that triggers it. If a reproduction isn't possible, then the OP probably needs to build ripgrep from source, re-run the errant command under a debugger and get a stack trace. Although, I'm not sure that this just isn't a I/O error happening somewhere. "bad address" doesn't necessarily mean ripgrep is looking at an invalid memory address, as far as I can tell.

**Comment by ckoryom** [comment]
Thanks for the support, I will also keep researching to figure out the issue. Not sure if other users are getting this as well.

I'm going to try and use a different WSL distro and see if I get the same issue.

**Comment by marcusedu** [comment]
same issue with me. 😞
