### ISSUE TITLE
No list of remote machines in RemoteSSH insiders

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode-remote-release#7090]
Type: <b>Bug</b>

Version `v0.85.2022081816` of RemoteSSH does not display a list of remote machines, and an error `No view is registered with id: remoteTargets` is displayed.

Extension version: 0.85.2022081816
VS Code version: Code - Insiders 1.71.0-insider (dced70bbf36d3c53c08e791da1791ac7fc42519b, 2022-08-10T05:17:53.560Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.0-46-generic
Connection to 'SSH: UbuntuVM' could not be established  Canceled

<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252

```

</details>

**Comment by tanhakabir** [comment]
Do you see a "Remote" dropdown in the Remote Explorer?

**Comment by anatolyburakov** [comment]
@tanhakabir no i do not

**Comment by tanhakabir** [comment]
And could you verify that you have the Remote Explorer extension installed?

**Comment by anatolyburakov** [comment]
@tanhakabir yes I do, see below

![2022-08-22_15-58-11](https://user-images.githubusercontent.com/37181601/185953070-44c13a86-23db-45e8-a2ff-52258921d9c7.png)

**Comment by anatolyburakov** [comment]
One of the new revisions seems to have fixed the issue
