### ISSUE TITLE
ssh showLoginTerminal Problem

### ISSUE THREAD

**Issue by zhangzscn** [microsoft/vscode-remote-release#7091]
I have set the "remote.SSH.showLoginTerminal": true。but there is  no Terminal show in vscode。but in windows it works。

版本: 1.70.1

提交: 6d9b74a70ca9c7733b29f0456fd8195364076dda

日期: 2022-08-10T06:09:15.055Z

Electron: 18.3.5

Chromium: 100.0.4896.160

Node.js: 16.13.2

V8: 10.0.139.17-electron.0

OS: Linux x64 5.15.0-46-generic

**Comment by tanhakabir** [comment]
> but in windows it works

Could you clarify but what you mean here?

Do you have a screenshot of what you're seeing?
