### ISSUE TITLE
AWS EC2 Instance running Debian  -- Telemetry issues and node crashing AWS instance

### ISSUE THREAD

**Issue by baitnfatty** [microsoft/vscode-remote-release#7094]
- VSCode Version:1.70.2
- Node.js Version: 16.13.2
- Local OS Version: Windows 11- 21H2 - 22000.856 
- Remote OS Version: AWS Instance  EC2 - Debian GNU/Linux 11 (bullseye)
- Remote Global Npm and Node versions: Npm 8.11.0    &&   Node.js 16.16.0
- Remote Extension/Connection Type: SSH
- Logs:

````
[20:38:37]` [127.0.0.1][e1b8ac07][ExtensionHostConnection] <1246> Launched Extension Host Process.
[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for executable "/bin/sh" and args [
  '-c',
  'wget --version > /dev/null\n' +
    'if [ $? -eq 0 ]\n' +
    'then\n' +
    "\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q --header='Metadata:true' -O - http://169.254.169.254/metadata/instance?api-version=2019-03-11\n" +
    'else\n' +
    '\tcurl --version > /dev/null\n' +
    '\tif [ $? -eq 0 ]\n' +
    '\tthen\n' +
    "\t\tcurl --connect-timeout 7 -s --header='Metadata:true' http://169.254.169.254/metadata/instance?api-version=2019-03-11\n" +
    '\tfi\n' +
    'fi\n' +
    'exit 0'
]
[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for executable "/bin/sh" and args [
  '-c',
  'wget --version > /dev/null\n' +
    'if [ $? -eq 0 ]\n' +
    'then\n' +
    '\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q  -O - http://169.254.169.254/latest/meta-data/instance-id\n' +

    'else\n' +
    '\tcurl --version > /dev/null\n' +
    '\tif [ $? -eq 0 ]\n' +
    '\tthen\n' +
    '\t\tcurl --connect-timeout 7 -s  http://169.254.169.254/latest/meta-data/instance-id\n' +
    '\tfi\n' +
    'fi\n' +
    'exit 0']




[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for executable "/bin/sh" and args [
  '-c',
  'wget --version > /dev/null\n' +
    'if [ $? -eq 0 ]\n' +
    'then\n' +
    "\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q --header='Metadata-Flavor:Google' -O - http://metadata.google.internal/computeMetadata/v1/instance/id\n" +
    'else\n' +
    '\tcurl --version > /dev/null\n' +
    '\tif [ $? -eq 0 ]\n' +
    '\tthen\n' +
    "\t\tcurl --connect-timeout 7 -s --header='Metadata-Flavor:Google' http://metadata.google.internal/computeMetadata/v1/instance/id\n" +
    '\tfi\n' +
    'fi\n' +
    'exit 0'
]
[20:39:35] No ptyHost heartbeat after 6 seconds
[20:40:36] No ptyHost heartbeat after 6 seconds
[20:43:01] No ptyHost heartbeat after 6 seconds
[20:43:03] [127.0.0.1][c875e4f9][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[20:43:05] Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/lccwww/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/server/node/server.main.js:145:7922)
    at process.emit (node:events:390:28)
rejected promise not handled within 1 second: ErrorNoTelemetry: Could not find pty on pty host
stack trace: ErrorNoTelemetry: Could not find pty on pty host,    at d._throwIfNoPty (/home/lccwww/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/pty>[20:43:07] [ErrorNoTelemetry: Could not find pty on pty host,    at d._throwIfNoPty (/home/lccwww/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyH>rejected promise not handled within 1 second: ErrorNoTelemetry: Could not find pty on pty host
````

Steps to Reproduce:
1. run a node server via powershell ssh at anytime while using Vscode and remote ssh extension. 
2. connect vscode to server and begin editing
3. change files 

Usually it will hang pretty quickly. If npm has a dev server up, VSCode gets mad... 

One thing that is interesting is that I have to reset my instance after this happens. it literally hangs the entire AWS instance when it occurs and it is super annoying. 

I am running this as a non root user of lccwww and cleaning out the .vscode-server folder on user solves problem until you launch a dev server with node, it then instantly crashes.

**Comment by tanhakabir** [comment]
Could you share your Remote SSH logs as well?

**Comment by baitnfatty** [comment]
Sure, Here it is, As well as the Daemon.log. 


'______AUTH.LOG__________

Aug 19 23:48:30 ip-172-31-25-157 systemd-logind[512]: Watching system buttons on /dev/input/event1 (Power Button)
Aug 19 23:48:30 ip-172-31-25-157 systemd-logind[512]: Watching system buttons on /dev/input/event2 (Sleep Button)
Aug 19 23:48:30 ip-172-31-25-157 systemd-logind[512]: Watching system buttons on /dev/input/event0 (AT Translated Set 2 keyboard)
Aug 19 23:48:30 ip-172-31-25-157 systemd-logind[512]: New seat seat0.
Aug 19 23:48:34 ip-172-31-25-157 sshd[699]: Accepted publickey for lccwww from xMY.IPx.xxx.xxx port 49317 ssh2: ED25519 SHA256:{Hidden FingerPrint}
Aug 19 23:48:34 ip-172-31-25-157 sshd[699]: pam_unix(sshd:session): session opened for user lccwww(uid=1001) by (uid=0)
Aug 19 23:48:34 ip-172-31-25-157 systemd-logind[512]: New session 1 of user lccwww.
Aug 19 23:48:34 ip-172-31-25-157 systemd: pam_unix(systemd-user:session): session opened for user lccwww(uid=1001) by (uid=0)
Aug 19 23:56:39 ip-172-31-25-157 sshd[722]: Received disconnect from xMY.IPx.xxx.xxx port 49317:11: disconnected by user
Aug 19 23:56:39 ip-172-31-25-157 sshd[722]: Disconnected from user lccwww xMY.IPx.xxx.xxx port 49317
Aug 19 23:56:39 ip-172-31-25-157 sshd[699]: pam_unix(sshd:session): session closed for user lccwww
Aug 19 23:56:39 ip-172-31-25-157 systemd-logind[512]: Session 1 logged out. Waiting for processes to exit.
Aug 19 23:56:39 ip-172-31-25-157 systemd-logind[512]: Removed session 1.
Aug 19 23:56:49 ip-172-31-25-157 systemd: pam_unix(systemd-user:session): session closed for user lccwww
Aug 19 23:56:54 ip-172-31-25-157 sshd[742]: Accepted publickey for lccwww from xMY.IPx.xxx.xxx port 49719 ssh2: ED25519 SHA256:{Hidden FingerPrint}
Aug 19 23:56:54 ip-172-31-25-157 sshd[742]: pam_unix(sshd:session): session opened for user lccwww(uid=1001) by (uid=0)
Aug 19 23:56:54 ip-172-31-25-157 systemd-logind[512]: New session 3 of user lccwww.
Aug 19 23:56:54 ip-172-31-25-157 systemd: pam_unix(systemd-user:session): session opened for user lccwww(uid=1001) by (uid=0)
Aug 20 00:09:01 ip-172-31-25-157 CRON[1262]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)
Aug 20 00:09:01 ip-172-31-25-157 CRON[1262]: pam_unix(cron:session): session closed for user root
Aug 20 00:17:01 ip-172-31-25-157 CRON[1346]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)
Aug 20 00:17:01 ip-172-31-25-157 CRON[1346]: pam_unix(cron:session): session closed for user root
Aug 20 00:39:01 ip-172-31-25-157 CRON[1479]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)
Aug 20 00:39:01 ip-172-31-25-157 CRON[1479]: pam_unix(cron:session): session closed for user root
Aug 20 00:58:48 ip-172-31-25-157 sshd[765]: Received disconnect from xMY.IPx.xxx.xxx port 49719:11: disconnected by user
Aug 20 01:01:01 ip-172-31-25-157 sshd[765]: Disconnected from user lccwww xMY.IPx.xxx.xxx port 49719
Aug 20 01:04:12 ip-172-31-25-157 systemd-logind[512]: Failed to abandon session scope, ignoring: Connection timed out
Aug 20 01:05:55 ip-172-31-25-157 sshd[742]: pam_unix(sshd:session): session closed for user lccwww
Aug 20 01:07:41 ip-172-31-25-157 systemd-logind[512]: Session 3 logged out. Waiting for processes to exit.
Aug 20 01:08:58 ip-172-31-25-157 sshd[742]: pam_systemd(sshd:session): Failed to release session: Transport endpoint is not connected






Daemon.LOG_______________________________________________

Aug 19 23:48:34 ip-172-31-25-157 systemd[702]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Aug 19 23:48:34 ip-172-31-25-157 systemd[702]: Listening on GnuPG cryptographic agent and passphrase cache.
Aug 19 23:48:34 ip-172-31-25-157 systemd[702]: Listening on D-Bus User Message Bus Socket.
Aug 19 23:48:34 ip-172-31-25-157 systemd[702]: Reached target Sockets.
Aug 19 23:48:34 ip-172-31-25-157 systemd[702]: Reached target Basic System.
Aug 19 23:48:34 ip-172-31-25-157 systemd[1]: Started User Manager for UID 1001.
Aug 19 23:48:34 ip-172-31-25-157 systemd[1]: Started Session 1 of user lccwww.
Aug 19 23:48:34 ip-172-31-25-157 systemd[702]: Reached target Main User Target.
Aug 19 23:48:34 ip-172-31-25-157 systemd[702]: Startup finished in 101ms.
Aug 19 23:48:36 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 8280ms.
Aug 19 23:48:44 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 16500ms.
Aug 19 23:49:01 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 31760ms.
Aug 19 23:49:33 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 61800ms.
Aug 19 23:50:34 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 118160ms.
Aug 19 23:52:32 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 128510ms.
Aug 19 23:54:41 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 115670ms.
Aug 19 23:56:37 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 109550ms.
Aug 19 23:56:39 ip-172-31-25-157 systemd[1]: session-1.scope: Succeeded.
Aug 19 23:56:49 ip-172-31-25-157 systemd[1]: Stopping User Manager for UID 1001...
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: Stopped target Main User Target.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: Stopped target Basic System.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: Stopped target Paths.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: Stopped target Sockets.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: Stopped target Timers.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: dbus.socket: Succeeded.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: Closed D-Bus User Message Bus Socket.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: dirmngr.socket: Succeeded.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: Closed GnuPG network certificate management daemon.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: gpg-agent-browser.socket: Succeeded.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: Closed GnuPG cryptographic agent and passphrase cache (access for web browsers).
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: gpg-agent-extra.socket: Succeeded.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: gpg-agent-ssh.socket: Succeeded.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: gpg-agent.socket: Succeeded.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: Closed GnuPG cryptographic agent and passphrase cache.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: Removed slice User Application Slice.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: Reached target Shutdown.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: systemd-exit.service: Succeeded.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: Finished Exit the Session.
Aug 19 23:56:49 ip-172-31-25-157 systemd[702]: Reached target Exit the Session.
Aug 19 23:56:49 ip-172-31-25-157 systemd[1]: user@1001.service: Succeeded.
Aug 19 23:56:49 ip-172-31-25-157 systemd[1]: Stopped User Manager for UID 1001.
Aug 19 23:56:49 ip-172-31-25-157 systemd[1]: Stopping User Runtime Directory /run/user/1001...
Aug 19 23:56:49 ip-172-31-25-157 systemd[1]: run-user-1001.mount: Succeeded.
Aug 19 23:56:49 ip-172-31-25-157 systemd[1]: user-runtime-dir@1001.service: Succeeded.
Aug 19 23:56:49 ip-172-31-25-157 systemd[1]: Stopped User Runtime Directory /run/user/1001.
Aug 19 23:56:49 ip-172-31-25-157 systemd[1]: Removed slice User Slice of UID 1001.
Aug 19 23:56:54 ip-172-31-25-157 systemd[1]: Created slice User Slice of UID 1001.
Aug 19 23:56:54 ip-172-31-25-157 systemd[1]: Starting User Runtime Directory /run/user/1001...
Aug 19 23:56:54 ip-172-31-25-157 systemd[1]: Finished User Runtime Directory /run/user/1001.
Aug 19 23:56:54 ip-172-31-25-157 systemd[1]: Starting User Manager for UID 1001...
Aug 19 23:56:54 ip-172-31-25-157 systemd[745]: Queued start job for default target Main User Target.
Aug 19 23:56:54 ip-172-31-25-157 systemd[745]: Created slice User Application Slice.
Aug 19 23:56:54 ip-172-31-25-157 systemd[745]: Reached target Paths.
Aug 19 23:56:54 ip-172-31-25-157 systemd[745]: Reached target Timers.
Aug 19 23:56:54 ip-172-31-25-157 systemd[745]: Starting D-Bus User Message Bus Socket.
Aug 19 23:56:54 ip-172-31-25-157 systemd[745]: Listening on GnuPG network certificate management daemon.
Aug 19 23:56:54 ip-172-31-25-157 systemd[745]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Aug 19 23:56:54 ip-172-31-25-157 systemd[745]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Aug 19 23:56:54 ip-172-31-25-157 systemd[745]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Aug 19 23:56:54 ip-172-31-25-157 systemd[745]: Listening on GnuPG cryptographic agent and passphrase cache.
Aug 19 23:56:54 ip-172-31-25-157 systemd[745]: Listening on D-Bus User Message Bus Socket.
Aug 19 23:56:54 ip-172-31-25-157 systemd[745]: Reached target Sockets.
Aug 19 23:56:54 ip-172-31-25-157 systemd[745]: Reached target Basic System.
Aug 19 23:56:54 ip-172-31-25-157 systemd[1]: Started User Manager for UID 1001.
Aug 19 23:56:54 ip-172-31-25-157 systemd[1]: Started Session 3 of user lccwww.
Aug 19 23:56:54 ip-172-31-25-157 systemd[745]: Reached target Main User Target.
Aug 19 23:56:54 ip-172-31-25-157 systemd[745]: Startup finished in 52ms.
Aug 19 23:58:26 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 109500ms.
Aug 20 00:00:16 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 124320ms.
Aug 20 00:00:30 ip-172-31-25-157 systemd[1]: Starting Rotate log files...
Aug 20 00:00:30 ip-172-31-25-157 systemd[1]: Starting Daily man-db regeneration...
Aug 20 00:00:30 ip-172-31-25-157 systemd[1]: Reloading The Apache HTTP Server.
Aug 20 00:00:30 ip-172-31-25-157 systemd[1]: Reloaded The Apache HTTP Server.
Aug 20 00:00:30 ip-172-31-25-157 systemd[1]: logrotate.service: Succeeded.
Aug 20 00:00:30 ip-172-31-25-157 systemd[1]: Finished Rotate log files.
Aug 20 00:00:31 ip-172-31-25-157 systemd[1]: man-db.service: Succeeded.
Aug 20 00:00:31 ip-172-31-25-157 systemd[1]: Finished Daily man-db regeneration.
Aug 20 00:02:20 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 126710ms.
Aug 20 00:03:30 ip-172-31-25-157 systemd[1]: Starting Cleanup of Temporary Directories...
Aug 20 00:03:30 ip-172-31-25-157 systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
Aug 20 00:03:30 ip-172-31-25-157 systemd[1]: Finished Cleanup of Temporary Directories.
Aug 20 00:04:27 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 113920ms.
Aug 20 00:06:21 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 121380ms.
Aug 20 00:08:22 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 124020ms.
Aug 20 00:09:10 ip-172-31-25-157 systemd[1]: Starting Clean php session files...
Aug 20 00:09:10 ip-172-31-25-157 systemd[1]: phpsessionclean.service: Succeeded.
Aug 20 00:09:10 ip-172-31-25-157 systemd[1]: Finished Clean php session files.
Aug 20 00:10:26 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 113020ms.
Aug 20 00:12:19 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 125610ms.
Aug 20 00:14:25 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 130390ms.
Aug 20 00:16:00 ip-172-31-25-157 dhclient[355]: DHCPREQUEST for 172.31.25.157 on eth0 to 172.31.16.1 port 67
Aug 20 00:16:00 ip-172-31-25-157 dhclient[355]: DHCPACK of 172.31.25.157 from 172.31.16.1
Aug 20 00:16:00 ip-172-31-25-157 dhclient[355]: bound to 172.31.25.157 -- renewal in 1622 seconds.
Aug 20 00:16:35 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 117880ms.
Aug 20 00:18:33 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 121920ms.
Aug 20 00:20:35 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 127980ms.
Aug 20 00:22:43 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 130920ms.
Aug 20 00:24:54 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 126270ms.
Aug 20 00:27:00 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 116640ms.
Aug 20 00:28:57 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 114390ms.
Aug 20 00:30:51 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 115540ms.
Aug 20 00:32:47 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 125600ms.
Aug 20 00:34:52 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 111100ms.
Aug 20 00:36:43 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 131030ms.
Aug 20 00:38:54 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 110320ms.
Aug 20 00:39:10 ip-172-31-25-157 systemd[1]: Starting Clean php session files...
Aug 20 00:39:10 ip-172-31-25-157 systemd[1]: phpsessionclean.service: Succeeded.
Aug 20 00:39:10 ip-172-31-25-157 systemd[1]: Finished Clean php session files.
Aug 20 00:40:45 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 124560ms.
Aug 20 00:42:49 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 128210ms.
Aug 20 00:43:02 ip-172-31-25-157 dhclient[355]: DHCPREQUEST for 172.31.25.157 on eth0 to 172.31.16.1 port 67
Aug 20 00:43:02 ip-172-31-25-157 dhclient[355]: DHCPACK of 172.31.25.157 from 172.31.16.1
Aug 20 00:43:02 ip-172-31-25-157 dhclient[355]: bound to 172.31.25.157 -- renewal in 1685 seconds.
Aug 20 00:44:57 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 130190ms.
Aug 20 00:47:08 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 127300ms.
Aug 20 00:49:15 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 120330ms.
Aug 20 00:51:15 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 127900ms.
Aug 20 00:53:23 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 123970ms.
Aug 20 00:56:38 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 112740ms.
Aug 20 01:02:34 ip-172-31-25-157 dhclient[411]: XMT: Solicit on eth0, interval 113370ms.
Aug 20 01:10:20 ip-172-31-25-157 dbus-daemon[498]: [system] Connection has not authenticated soon enough, closing it (auth_timeout=30000ms, elapsed: 83618ms)`

**Comment by tanhakabir** [comment]
No sorry these logs: https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues

**Comment by SomervilleTom** [comment]
I'm seeing exactly the same issue in late January 2023. 

@tanhakabir: As the thread-starter says, ALL ssh connectivity to the remote instance is lost when this happens. Existing SSH connects are dropped and the server does not respond to new connection attempts. If you can share specific logs that are helpful (on either the remote or local system), then I'll look for them.

Like the thread-starter, I'm running VSCode from a local Windows 10 Pro system. I'm doing remote development using `Remote SSH` and the `Javascript debugger`. This happens when I launch the Javascript development servers on the remote host that are used while debugging a React app using the VSCode stack.

I'm running VSCode `Version: 1.74.3 (system setup)`.

Perhaps this issue can be re-opened or merged with a counterpart that is receiving developer attention. This issue is SERIOUS -- it locks out ALL connections to the affected AWS EC2 server.

**Comment by SomervilleTom** [comment]
This hang just occurred again.  Connectivity to the server was restored without intervention after about 8 minutes. All times are in server time.

Connectivity lost: Jan 31 15:44
Connectivity recovered: Jan 31 15:52

Here are excerpts from some perhaps relevant logs. I've excluded entries outside the time window of this interruption.

`/var/log/messages`:

`
Jan 31 15:40:01 byron systemd[1]: Starting system activity accounting tool...
Jan 31 15:40:01 byron systemd[1]: sysstat-collect.service: Succeeded.
Jan 31 15:40:01 byron systemd[1]: Started system activity accounting tool.
Jan 31 15:46:25 byron systemd[1]: session-12.scope: Succeeded.
Jan 31 15:46:25 byron systemd-logind[905]: Session 12 logged out. Waiting for processes to exit.
Jan 31 15:46:25 byron systemd-logind[905]: Removed session 12.
Jan 31 15:46:25 byron systemd[1]: session-10.scope: Succeeded.
Jan 31 15:46:25 byron systemd-logind[905]: Session 10 logged out. Waiting for processes to exit.
Jan 31 15:46:25 byron systemd-logind[905]: Removed session 10.
Jan 31 15:46:26 byron systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Jan 31 15:46:26 byron systemd[1]: Started Process Core Dump (PID 8285/UID 0).
Jan 31 15:46:26 byron systemd[1]: Started Session 13 of user tms.
Jan 31 15:46:26 byron systemd-logind[905]: New session 13 of user tms.
Jan 31 15:46:26 byron systemd-coredump[8286]: Resource limits disable core dumping for process 7385 (node).
Jan 31 15:46:26 byron systemd-coredump[8286]: Process 7385 (node) of user 1001 dumped core.
Jan 31 15:46:26 byron systemd[1]: systemd-coredump@0-8285-0.service: Succeeded.
Jan 31 15:50:00 byron systemd[1]: Starting system activity accounting tool...
Jan 31 15:50:00 byron systemd[1]: sysstat-collect.service: Succeeded.
Jan 31 15:50:00 byron systemd[1]: Started system activity accounting tool.
Jan 31 15:51:44 byron systemd-logind[905]: New session 14 of user root.
Jan 31 15:51:44 byron systemd[1]: Started Session 14 of user root.
Jan 31 15:52:33 byron systemd[1]: Started Session 15 of user tms.
Jan 31 15:52:33 byron systemd-logind[905]: New session 15 of user tms.
`

`/~/.vscode-server/data/logs/20230131T145254/exthost1/exthost.log`:
`
2023-01-31 15:46:25.498 [info] Extension host terminating: received terminate message from renderer
2023-01-31 15:46:25.901 [info] Lock '/home/tms/.vscode-server/data/User/workspaceStorage/e71344bf6e8903ea68569ac4346d49d2/vscode.lock': Marking the lockfile as scheduled to be released in 6000 ms.
2023-01-31 15:46:25.922 [info] Extension host with pid 6641 exiting with code 0
`

`/~/.vscode-server/data/logs/20230131T145254/remoteagent.log`:
`
2023-01-31 15:44:07.693 [warning] No ptyHost heartbeat after 6 seconds
2023-01-31 15:44:15.896 [warning] No ptyHost heartbeat after 6 seconds
2023-01-31 15:44:32.747 [warning] No ptyHost heartbeat after 6 seconds
2023-01-31 15:44:42.237 [warning] No ptyHost heartbeat after 6 seconds
2023-01-31 15:45:07.605 [error] CodeExpectedError: Could not find pty on pty host
    at h.J (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:27:6395)
    at h.updateIcon (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:27:2715)
    at Object.call (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:17:5110)
    at r.q (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:15:5390)
    at r.p (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:15:4881)
    at /home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:15:4286
    at n.invoke (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at C.deliver (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:11:2038)
    at v.fire (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:11:1676)
    at process.O (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:9:20886)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2023-01-31 15:45:08.109 [error] CodeExpectedError: Could not find pty on pty host
    at h.J (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:27:6395)
    at h.updateTitle (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:27:2665)
    at Object.call (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:17:5110)
    at r.q (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:15:5390)
    at r.p (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:15:4881)
    at /home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:15:4286
    at n.invoke (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at C.deliver (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:11:2038)
    at v.fire (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:11:1676)
    at process.O (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:9:20886)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2023-01-31 15:45:08.490 [error] CodeExpectedError: Could not find pty on pty host
    at h.J (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:27:6395)
    at h.updateTitle (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:27:2665)
    at Object.call (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:17:5110)
    at r.q (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:15:5390)
    at r.p (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:15:4881)
    at /home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:15:4286
    at n.invoke (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at C.deliver (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:11:2038)
    at v.fire (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:11:1676)
    at process.O (/home/tms/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/platform/terminal/node/ptyHostMain.js:9:20886)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2023-01-31 15:46:25.410 [info] [127.0.0.1][a62010f2][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
2023-01-31 15:46:26.102 [info] [127.0.0.1][fe08b89a][ExtensionHostConnection] <6641> Extension Host Process exited with code: 0, signal: null.
2023-01-31 15:46:26.103 [info] Last EH closed, waiting before shutting down
2023-01-31 15:46:26.535 [info] Got delay-shutdown request while in shutdown timeout, delaying
2023-01-31 15:46:26.535 [info] Cancelling previous shutdown timeout
2023-01-31 15:51:26.535 [info] Last EH closed, shutting down
`

I was unable to find any other relevant log entries.

Perhaps this log information is helpful if anybody looks at this again.
