### ISSUE TITLE
Prevent SSH logout after opening folder

### ISSUE THREAD

**Issue by MartinLoeper** [microsoft/vscode-remote-release#7096]
I am currently looking for a way to open a Gradescope Debug SSH session in vscode via remote ssh extension.
My issue is that when I click the "Open Folder" button in the explorer, vscode closes the previously initiated ssh session and reopens the window using a new ssh connection.

However, the gradescope ssh server instance is terminated after any connection was closed.
Is there a way to open a folder without triggering an ssh reconnect?
Possibly opening a default folder right on first connection attempt?

somehow related issue: https://github.com/microsoft/vscode-remote-release/issues/511

**Comment by eleanorjboyd** [comment]
Hello! My name is Eleanor the new maintainer for Remote-SSH. What is your setting for `useLocalServer`? Could you set that to `true` and see if that helps maintain the connection instead of reloading it?
