### ISSUE TITLE
Install Local Extensions in `...` should install too themes and icons

### ISSUE THREAD

**Issue by Hitusss** [microsoft/vscode-remote-release#7097]
Type: <b>Feature Request</b>

I try to create the extension that select random color theme, but I have big issue with Remote WSL, because themes are only installed local and I can't get list of installed themes from this code ```vscode.extensions.all```.

Extension version: 0.66.3
VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

**Comment by bamurtaugh** [comment]
Does this command meet your needs? 
![image](https://user-images.githubusercontent.com/25310137/185984054-59c0af41-0f54-4349-8714-63953784510b.png)

**Comment by Hitusss** [comment]
I know about it, but extensions like themes, are enable in Local Extension Host and when I try to firstly use [Random Theme Switcher](https://marketplace.visualstudio.com/items?itemName=zanza00.random-theme-switcher) it's run in WSL and have error because can't access the themes list. Right now I try to make my own extension and I find other solution for it, by enabling extension by Local Extension Host.
