### ISSUE TITLE
Connecting to Windows Server over SSH

### ISSUE THREAD

**Issue by pbering** [Microsoft/vscode-remote-release#71]
I get this error when trying to connect to a Windows Server 2019 running SSH server:

`Can't connect to XXX: unreachable or not Linux x86_64 (PS C:\Users\Administrator> )`

Is it not supported?

**Comment by kieferrm** [comment]
Windows servers are currently no supported.

**Comment by Tyriar** [comment]
/duplicate https://github.com/Microsoft/vscode-remote-release/issues/25
