### ISSUE TITLE
Hangs on "Confirming that XYZ is reachable" on Raspbian?

### ISSUE THREAD

**Issue by jamescrowley** [microsoft/vscode-remote-release#710]
Issue Type: <b>Bug</b>

Is Raspbian supported? It's based off Debian so was hoping yes, but I have a rasberry pi running the full raspbian (9 stretch), and VS code running on macOS.

I ran:

     ssh-copy-id pi@192.168.1.116
 
and can now connect via the terminal using

     ssh 192.168.1.116 -l pi

entering no further credentials aside from my SSH key passphrase. However, when I try and connect from VS code (command palette -> Remote SSH - connect to host) and select "192.168.1.116" the UI just hangs "Confirming that 192.168.1.116 is reachable".

Extension version: 0.42.2
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|-psn_0_3584875|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
First make sure that you are using the nightly version of the ssh extension, and also VS Code Insiders. Raspberry pi support hasn't made it to the stable version yet.

**Comment by jamescrowley** [comment]
Ah ok, that'll be it. Thanks @roblourens.
