### ISSUE TITLE
Test: Allow for default value in `${localEnv:...}` and `${containerEnv:...}`

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#7100]
Refs: https://github.com/devcontainers/spec/issues/63

- [x] anyOS @lszomoru
- [x] anyOS @aeschli 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%237100%0A%0A&assignees=chrmarti)

---

Use the latest Remote-Containers pre-release (currently 0.248.0) or Dev Containers CLI (currently 0.12.1) for testing.

A devcontainer.json's property values can reference environment variables locally and inside the container. Test that the updated syntax supports having a default value that is used when the environment variable is not set: `${localEnv:ENV_VAR:default_value}` and `${containerEnv:ENV_VAR:default_value}`

**Comment by lszomoru** [comment]
Works as advertised 🎉
