### ISSUE TITLE
Test: Use container features from OCI registry

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#7102]
Refs: https://github.com/devcontainers/cli/issues/88

- [x] anyOS @alexr00 
- [x] anyOS @dbaeumer

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%237102%0A%0A&assignees=chrmarti)

---

Use the latest Remote-Containers pre-release (currently 0.248.0) or Dev Containers CLI (currently 0.12.1) for testing.

Note that the new feature id syntax shows an error decoration in the editor because it is not yet officially supported.

- Test that container features can be referenced by their OCI-based id. See https://github.com/orgs/devcontainers/packages?repo_name=features for the complete list. E.g.:
```json
{
	"image": "mcr.microsoft.com/vscode/devcontainers/base:0-bullseye",
	"features": {
		"ghcr.io/devcontainers/features/node": "latest"
	}
}
```
- Check that semver versioning on the feature id works, e.g., `"ghcr.io/devcontainers/features/node:1.0.2"`, `"ghcr.io/devcontainers/features/node:1.0"`, `"ghcr.io/devcontainers/features/node:1"`.
- Check that the old feature ids still work (these is mapped to the new sytnax), e.g.: `"node"`. The complete list is in https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/container-features/src/devcontainer-features.json.

**Comment by alexdima** [comment]
Notes from the standup discussion:
1. `"ghcr.io/devcontainers/features/go:1": "latest"` is very confusing
2. `version` might be better called `goVersion`, `nodeVersion`, etc:
```
"ghcr.io/devcontainers/features/go:1": {
    "version": "latest" // maybe better called "goVersion"?
}
```
compare with actions:
```
- uses: actions/setup-node@v3
  with:
    node-version: 16
```
3. Consider using `@` for feature version instead of `:`

**Comment by alexr00** [comment]
I tried adding 
```
    "features": {
        "go": "latest"
    }
```
to my devcontainer.json, but when I rebuilt I got this error:

```
[2022-08-25T14:30:50.275Z] * Fetching feature: go_1_local-cache
[2022-08-25T14:30:50.309Z] Feature go is not a 'v2' feature. Attempting fallback to 'v1' implementation.
[2022-08-25T14:30:50.315Z] Failed to find feature 'go' in provided v1 metadata file
[2022-08-25T14:30:50.315Z] (!) ERR: Failed to fetch feature: Failed to parse feature 'go_1_local-cache'. Please check your devcontainer.json 'features' attribute.
[2022-08-25T14:30:50.316Z] Error: Failed to parse feature 'go_1_local-cache'. Please check your devcontainer.json 'features' attribute.
[2022-08-25T14:30:50.317Z]
```
