### ISSUE TITLE
Attach Visual Studio Code via Kubernetes fails to connect remoteContainers [resolved]

### ISSUE THREAD

**Issue by Jackbennett** [microsoft/vscode-remote-release#7108]
- VSCode Version: 1.70.0
- Local OS Version: windows 10 x64 19043.1889
- Remote OS Version: n/a
- Remote Extension/Connection Type: Kubernetes v1.3.10 attach remote container to Containers hyper-V Talos cluster.
- Logs: lost log - but the remoteContainers error isn't valid for the actual problem.

Steps to Reproduce:

* Note: opening PowerShell normally, kubectl finds the working kubeconf and works fine.

1. Set kubeconfig via command to configure kubernetes plugin
1. Have System Env of `KUBECONFIG                     %userprofile%\.kube\config`
2. Use "attach to container" and an error from remoteContainers about kubectl config current-context will be thrown

Results in `KUBECONFIG                     C:\WINDOWS\system32\config\systemprofile\.kube\config`

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: n/a

checking `ls Env:` finds expected ENV variables with my username. Only KUBECONFIG has the system32 path.

# Fix
Remove `KUBECONFIG` key from System Env. User env is untested, just revert to letting kubectl search default paths itself.

I don't know how vscode launches its terminal to end up with `%userprofile%` in system32 but I think having the system env kubeconfig a user err on my part lingering from long ago. This issue is reported in case someone else has the same odd error where you can browse the cluster but can't attach code to connect to pods, getting a terminal works.

## Secondary, invisible config
It seems `vs-kubernetes.kubeconfig` isn't used by "attach visual studio code" to container OR it's overwritten by an ENV when ran, which isn't used when browsing the cluster in the sidebar UI.

Command palette: "Configure kuberenetes" sets these keys which aren't visible in the Settings UI viewing `@ext:ms-kubernetes-tools.vscode-kubernetes-tools`
```
  "vs-kubernetes": {
    "vs-kubernetes.knownKubeconfigs": ["c:\\Users\\Jack\\.kube\\config"],
    "vs-kubernetes.kubeconfig": "c:\\Users\\Jack\\.kube\\config"
  }
```
Searching "kubeconfig" has no settings found at all. Maybe this key is ignored as that's a default path anyway and that's a red herring.

**Comment by MurzNN** [comment]
Thanks for the description of the fix! But it doesn't work for me on Linux. I've made suggested changes, using invisible config:
```json
  "vs-kubernetes": {
    "vs-kubernetes.knownKubeconfigs": ["/srv/korepov/.kube/config"],
    "vs-kubernetes.kubeconfig": "/srv/korepov/.kube/config"
  },
```
When I'm setting incorrect path - the cluster is disappearing from the Kubernetes tab, so those settings are working well.
But I still don't see the "Attach Visual Studio Code" menu item:
![image](https://user-images.githubusercontent.com/336662/186585422-29674ead-d1e7-4f43-b1de-0779ad955d47.png)

Maybe you have any other ideas what else can I try?

**Comment by chrmarti** [comment]
@Jackbennett Maybe `%userprofile%` in a system environment variable resolves to that system path? (Haven't tried.)

@MurzNN You need the Remote-Containers extension to get that context menu entry. It won't work though when the Kubernetes extension is running remotely as part of Remote-SSH due to https://github.com/microsoft/vscode-remote-release/issues/6054.

**Comment by Jackbennett** [comment]
Yeh I guess it's closable, I don't think there's an action to resolve. Maybe warning if the resolved profile config is a known system path anyway?

I don't think code was running as admin so wouldn't expect userprofile to actually be something in system32. I'm not sure how to detect vscode and kubectl getting different configs, probably a good amount of time it's intentional.
