### ISSUE TITLE
There are no running containers to attach to.

### ISSUE THREAD

**Issue by dacianpeng** [microsoft/vscode-remote-release#7109]
Hi, I'm experiencing the same problem as
[There are no running containers to attach to. microsoft/vscode-docker#2579](https://github.com/microsoft/vscode-docker/issues/2579)

computer A ( vscode 1.70.2, windows Version 10.0.22621 Build 22621 )
server B ( Ubuntu 22.04.1 LTS 5.15.0-46-generic, Docker Engine - Community 20.10.17, Docker Desktop 4.11.1 (84025))

Computer A vscode ssh connect to serverB
`computerA------------> ssh------------> serverB` 

then, use `remote explorer plugin` to attach vscode to serverB

inside the `remote explorer attached vscode`, use `docker plugin` , right click the running container and attach vscode to it

`computerA------------> ssh------------> serverB------------> attach vscode to a running container`

There are no running containers to attach to.

![image](https://user-images.githubusercontent.com/43288063/186053767-759ddaaa-71d4-44c6-ad87-40705aca4fe5.png)

**Comment by dacianpeng** [comment]
Thanks. I will provide information and logs at your need.

Versions attached.
`Remote - Containers v0.247.0`
`Docker v1.22.1`

**Comment by chrmarti** [comment]
@dacianpeng Do you see the container listed when you run `docker ps` yourself? Make sure it is running (not stopped).

**Comment by dacianpeng** [comment]
Yes, in `serverB`, `docker ps`, I can see it's running.

**Comment by dacianpeng** [comment]
well, I find the page [docker-extension-limitations](https://code.visualstudio.com/docs/remote/ssh#_docker-extension-limitations)

**Comment by dacianpeng** [comment]
ok, now I've dodged out a way. [code-server](https://github.com/coder/code-server)
