### ISSUE TITLE
I can't link server(centos 6.5) with root,but link with common user successed. why ?

### ISSUE THREAD

**Issue by zz940522** [microsoft/vscode-remote-release#711]
I can't link server(centos 6.5) with root,but link with common user successed. why ?

**Comment by suryasr007** [comment]
Does root have login permissions in your server?

**Comment by zz940522** [comment]
> Does root have login permissions in your server?

today,i update the vscode insider,then root can login yet,thank you!
but i still don't know why

**Comment by chrmarti** [comment]
Which host OS are you on and which of the Remote extensions are you using?
