### ISSUE TITLE
Missing error message when referencing un-existing feature.

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-remote-release#7116]
Testing #7102

Using a feature doesn't show an error when rebuilding the container:

```
{
	"name": "test",
	"image": "mcr.microsoft.com/vscode/devcontainers/base:0-bullseye",
	"features": {
		"ghcr.io/devcontainers/features/node": "1.0.3"
	}
}
```

Rebuild / build a container with this `devcontainer.json`. You end up with a container with no node (or better with a very old one in `/usr/local/share/nvm/versions/io.js/v1.0.3/bin/node`). I would have expected an error message that the feature can't be found.

**Comment by dbaeumer** [comment]
I think I misunderstand the syntax of this. Is `1.0.3` referring to the node version or to the version of the node feature here: https://github.com/devcontainers/features/pkgs/container/features%2Fnode which list `latest`, `1.0.2`, `1.0`, ...

**Comment by chrmarti** [comment]
Correct, the value is the NodeJS version. To specify a feature version, you append it to the key with a `:` as separator. Assuming that resolves the issue, I close it, thanks.
