### ISSUE TITLE
Unable to open any folder in containers. Explorer is empty, "Operation not permitted" in terminal running "ls"

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode-remote-release#7118]
- VSCode Version: 1.70.2
- Local OS Version: macOS Monterey 12.4
- Remote OS Version: Ubuntu 22.04
- Remote Extension/Connection Type: Containers
- Docker version: 4.6.1 (76265)
- Logs: [log.txt](https://github.com/microsoft/vscode-remote-release/files/9425724/log.txt)

Steps to Reproduce:

1. Create an empty folder
2. Add a file "foo.txt"
3. Purge all containers from the Docker Desktop interface to ensure there's nothing that can be re-used
4. Run the **Remote-Containers: Open Folder in Container** command
5. Select the folder created above that contains "foo.txt"
6. Select the Ubuntu definition, 22.04, accepting default of no additional components to be installed
7. Wait for container to be opened
8. Note that nothing is shown in explorer
9. Run `ls` in the terminal, and note error "ls: reading directory '.': Operation not permitted"
    <img width="1069" alt="Screenshot 2022-08-25 at 15 39 57" src="https://user-images.githubusercontent.com/1078012/186695213-6fe8943e-36ab-4794-b70d-8586341a0250.png">
10. Run Remote-Containers: Reopen Folder Locally
11. Note "foo.txt" is once again visible in the explorer
12. Run Remote-Containers: Rebuild and Reopen in Container
13. Still same, folders not showing

I've also tried explicitly setting `workspaceMount` and `workspaceFolder`:

```
"workspaceMount": "source=${localWorkspaceFolder},target=/workspace,type=bind",
"workspaceFolder": "/workspace"
```

But that also makes no difference.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by DanTup** [comment]
I tried the same using Ubuntu 20 and got some different errors, but essentially broken in a similar way:

<img width="502" alt="Screenshot 2022-08-25 at 15 46 37" src="https://user-images.githubusercontent.com/1078012/186696840-42b6c5e3-7c07-4173-a200-6d61b93da7fa.png">

**Comment by chrmarti** [comment]
Please check in the System Preferences if Docker has access to the Desktop folder (of which your workspace folder is a subfolder):
<img width="666" alt="image" src="https://user-images.githubusercontent.com/9205389/188601830-e2a9b5a2-2fca-4e98-bb78-438cb9ab1d9c.png">

**Comment by DanTup** [comment]
Sorry for the delay. It looks like you were spot on. I should've thought to check in there. Thanks! :-)

<img width="632" alt="Screenshot 2022-09-21 at 17 38 49" src="https://user-images.githubusercontent.com/1078012/191562109-92518d92-4658-4dd8-a2bf-26a329c65dbb.png">
