### ISSUE TITLE
`${containerEnv:ENV_VAR:default_value}` not working

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#7121]
Testing #7100

- open a new folder, create a new devcontainer file (e.g. Ubuntu)
- add `"postCreateCommand": "echo XXX ${localEnv:PATH:NO_PATH} ${localEnv:PATH1:NO_PATH1}",`
- run the container. Works
```
[5207 ms] Start: Run in container: /bin/sh -c echo XXX /home/aeschli/.local/bin:/home/aeschli/.... NO_PATH1
XXX /home/aeschli/.local/bin:/home/aeschli/... NO_PATH1
```
change `localEnv` to `containerEnv`: 
`"postCreateCommand": "echo XXX ${containerEnv:PATH:NO_PATH} ${containerEnv:PATH1:NO_PATH1}",`
- rebuild container
```
[5199 ms] Start: Run in container: /bin/sh -c echo XXX ${containerEnv:PATH:NO_PATH} ${containerEnv:PATH1:NO_PATH1}
/bin/sh: 1: Bad substitution
```

**Comment by tvenhaus** [comment]
I just tested version v0.250.0 using the VSCode Insiders build and observed that container environment variables (i.e. ${containerEnv:ENV_VAR:default_value) are still not working when used within the "mounts" property.

```
"mounts": [
	"source=${containerEnv:SOME_VAR},target=/some/folder,type=bind,consistency=cached"
],
```

**Comment by aeschli** [comment]
Verified with v0.252.0
