### ISSUE TITLE
Coder/code-server conflicts with the startup command of visual studio code server

### ISSUE THREAD

**Issue by 2659170494** [microsoft/vscode-remote-release#7122]
- VSCode Version:1.70.2
- Local OS Version:Windows
- Remote OS Version:Ubuntu
- Remote Extension/Connection Type: SSH/Containers/WSL/Server
- Logs:1.70.2

Steps to Reproduce:

1To install the coder/code-server (or visual studio code server)
2.run "code-server" then you will see the estimated results
3.instal the visual studio code server (or coder/code-server)
4. run "code-server" then you will find that the results are different from the original ones

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by tanhakabir** [comment]
Sorry coder/code-server isn't officially supported by us so we can't help solve any issues it might have
