### ISSUE TITLE
Debugging with Visual Studio Code to WSL2 remotely then using a virtual Conda environment

### ISSUE THREAD

**Issue by mrmarten** [microsoft/vscode-remote-release#7123]
Type: <b>Bug</b>

I stumbled upon an issue while i try to use the VS Code to remote debug WSL2 that is using an Conda virtual environment. When i use the 'base' version of Conda the debugger starts properly. But for the virtual environment it just kinda "blinks" with the debug bar and then stops.

GIF Sequence of the issue here i start with the virtual environment then switch to the base:
https://i.stack.imgur.com/YUC9d.gif

This is my launch.json file.

// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
"version": "0.2.0",
"configurations": [
    {
        "name": "Python: Module",
        "type": "python",
        "request": "launch",
        "module": "run",
        "justMyCode":true,
        "env": { "PYTHONPATH": "${PYTHONPATH}:/home/marten/rl/go-explore/robustified"}
    }
]

}

Extension version: 0.66.3
VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.22622
Modes:
Remote OS version: Linux x64 5.15.57.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz (16 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.77GB (17.84GB free)|
|Process Argv|--crash-reporter-id 5ab38405-45ae-451a-95de-dbeaf08ed2a1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.15.57.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz (16 x 3096)|
|Memory (System)|15.50GB (13.25GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30542925
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by aeschli** [comment]
Do you still see this? This needs to be filed against the extension that contributes the debugger (Python)
