### ISSUE TITLE
Server always says "An update for the VS Code CLI on your remote server is availible"

### ISSUE THREAD

**Issue by techflashYT** [microsoft/vscode-remote-release#7124]
- VSCode Version: From within the remote environment:
```
$ code --version
1.70.2
e4503b30fc78200f846c62cf8091b76ff5547662
x64
```
- Local OS Version: According to `winver`:
```
Microsoft Windows
Version 1909 (OS Build 18363.2274)
```
It also occurs on a Windows 11 Insider Dev Build machine.
- Remote OS Version:
```
$ uname -r
5.19.3-arch1-1
```
- Remote Extension/Connection Type: SSH/Containers/WSL/Server: Server
- Logs: N/A

Steps to Reproduce:

1. Download server version: `VS Code Server 20220810.1` (version I have installed, ~~may~~ (it is!) be reproducible on latest version, will find out once there is a new version)
2. Start the server
3. Click either of the "update" buttons on the notification
4. Server does not appear to update

Does this issue occur when you try this locally?: Yes/No: Notification is about the server
Does this issue occur when you try this locally and all extensions are disabled?: N/A, see above

Additional Info:
I was clicking the button from within the vscode.dev link that the server generated.
It would show an "updating" progress bar for about 1.5 seconds before nothing else happenend.

**Comment by connor4312** [comment]
Thank you for the issue! However, in the next couple iterations, we are working on moving the "code-server" utility into the VS Code CLI, as referenced in our issues. That is happening as we speak, and it will use a different upgrade mechanism, so I don't have any plans to fix this in the code-server.
