### ISSUE TITLE
Prevent system from sleeping while the server is running

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-remote-release#7127]
Suggested via user feedback, I think this makes good sense. If a user expects their machine to be remotely available, it should not automatically go to sleep.

**Comment by bamurtaugh** [comment]
I think @chrisdias and I are observing something related. 

We both had remote machines where we enabled remote access, and we shut those machines down in some way (I just enabled tunnel access on another laptop and then shut the lid). Remote Tunnels still lists the machine as online, but when I try to connect, it is stuck trying to connect and eventually times out after a few minutes:

![image](https://user-images.githubusercontent.com/25310137/211871540-27beead4-dd4c-4204-a70f-477d62d36e9b.png)

**Comment by connor4312** [comment]
This is now done:

- When enabling remote tunnel access from the UI, you can set `remote.tunnels.access.preventSleep` to stop the computer from sleeping
- When running from the CLI, you can pass the flag `--no-sleep`
