### ISSUE TITLE
ssh using cmd.exe instead of git bash

### ISSUE THREAD

**Issue by universalmind303** [microsoft/vscode-remote-release#713]
Issue Type: <b>Bug</b>

VSCode Version: latest
Local OS Version: win10
Remote OS Version: amazon linux
Remote Extension/Connection Type: SSH

log: Can't connect to aliyun: unreachable or not Linux x86_64
The terminal process command 'cmd.exe/c (type "C:\Users\xxx\AppData\Local\Temp\vscode-linux-multi-line-command-xxx.sh" | ssh xxx) & exit /b 0' failed to launch (exit code: 255)

I am using git bash for my development and am using a locked down version of windows. So cmd.exe and poweshell DO NOT have ssh installed. 

I have vscode configured to use git bash, but i am unable to configure the ssh connection to use the git bash equivalent when starting up. 

I am able to connect to the instance from ssh 
seems related to #359 
Extension version: 0.42.2
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.15063

Steps to Reproduce: 
- install git bash 
- configure git bash as default terminal in vscode
- make sure ssh and openssh are not installed in cmd.exe or powershell 
- try to connect to remote host

**Comment by MBetters** [comment]
I'm not using Git Bash. I'm using Cmder. I ran into a similar problem. I fixed it by adding the folder containing Cmder's ssh.exe to the integrated terminal path. My settings. json has these keys...

```json
...
"terminal.integrated.shell.windows": "C:\\Windows\\system32\\cmd.exe",
    "terminal.integrated.env.windows": {
        "CMDER_ROOT": "C:\\cmder",
        "PATH": "C:\\cmder\\vendor\\git-for-windows\\usr\\bin;C:\\Program Files\\Oracle\\VirtualBox;C:\\HashiCorp\\Packer;C:\\HashiCorp\\Vagrant\\bin;C:\\Program Files\\jq;C:\\Program Files (x86)\\GnuWin32\\bin;C:\\Program Files\\PuTTY;${env:PATH}"
    },
    "terminal.integrated.shellArgs.windows": [
      "/k C:\\cmder\\vendor\\init.bat"
    ],
...
```

**Comment by universalmind303** [comment]
I tried changing all the settings within "terminal.*". I still get the same error message

**Comment by universalmind303** [comment]
that did the trick!

**Comment by roblourens** [comment]
In the nightly version of the extension, if it can't find your ssh, there is also a dedicated setting to give it the path to the ssh binary.
