### ISSUE TITLE
Fail to run code-server at Debian 9

### ISSUE THREAD

**Issue by Vanbob-Lee** [microsoft/vscode-remote-release#7130]
➜  ~ code-server 
code-server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by code-server)
➜  ~ sudo apt-get install libc6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libc6 is already the newest version (2.24-11+deb9u4).
0 upgraded, 0 newly installed, 0 to remove and 210 not upgraded.
➜  ~ uname -a
Linux xxx 4.14.81.bm.15-amd64 #1 SMP Debian 4.14.81.bm.15 Sun Sep 8 05:02:31 UTC 2019 x86_64 GNU/Linux

It seems there is no way to update glibc>=2.25 at Debian9
Is updating OS version the only solution?

**Comment by connor4312** [comment]
Yes, though as in https://github.com/microsoft/vscode-remote-release/issues/6923 we may remove the dependency on glibc
