### ISSUE TITLE
SSH Agent Forwarding does not work 

### ISSUE THREAD

**Issue by julienflack** [microsoft/vscode-remote-release#7133]
- VSCode Version: 1.70.2
- Local OS Version: Mac OSX Monterey 12.1 (21C52) 
- Remote OS Version: Amazon linux 4.14.290-217.505.amzn2.x86_64
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. On local machine (Mac) add a host with agent forwarding in ~/.ssh/config i.e.:
```
Host test
        HostName xxx.xxx.xxxx.xxx
        User ec2-user
        IdentityFile ~/.ssh/XXX.pem
        ForwardAgent yes
```
2. Connect via osx command line ssh i.e. `ssh test`
3. Test whether agent forwarding works with `ssh-add -l` -> outcome success list keys from local machine in remote terminal
4. Use visual studio code 1.70.2 to connect to the same host (test) using Remote SSH v0.84.0 release version with the Enable Agent Forwarding setting and terminal.integrated.inheritEnv enabled
5. type `ssh-add -l` -> outcome `The agent has no identities.`

Also tested on Visual Studio Code Insiders - same result.

The issue seems to be related to `SSH_AUTH_SOCK` as discussed here:
https://github.com/microsoft/vscode-remote-release/issues/6235

However, the work arounds for setting the socket file do not work in my case. The socket file created do not seem to enable access to the agent. However, if I create a ssh connection outside of vs code using the command line and then redirect `SSH_AUTH_SOCK` at the socket file generated by that process then the integrated terminal is able to access the agent correctly. But it does require to have an external ssh connection to be active. 

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
> However, the work arounds for setting the socket file do not work in my case. The socket file created do not seem to enable access to the agent. However, if I create a ssh connection outside of vs code using the command line and then redirect SSH_AUTH_SOCK at the socket file generated by that process then the integrated terminal is able to access the agent correctly. But it does require to have an external ssh connection to be active.

I don't really follow what your workaround is. But I think it's likely that just as in #6235, you just need to open a new terminal. We can continue in that issue.
