### ISSUE TITLE
Remote Explorer doesn't refresh when editing ssh config or adding new hosts

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#7144]
- Open the remote explorer
- Add New SSH Host
- The remote explorer should refresh to show the host that I just added

And I think it used to refresh automatically when editing the ssh config file in the text editor as well

cc @tanhakabir

**Comment by eleanorjboyd** [comment]
@roblourens Just to clarify, this means that the remote explorer will reload on a "save" event or more frequently like on some sort of text edit event?

**Comment by roblourens** [comment]
On save, I think

**Comment by joshspicer** [comment]
This fix will be released the next build of the pre-release extension (on Monday)
