### ISSUE TITLE
vscode-server Mac needs to explain that the system keychain must be unlocked running vscode-server

### ISSUE THREAD

**Issue by jum** [microsoft/vscode-remote-release#7148]
If installing vscode-server on a Mac server, the following errors may occur if doing the install via an ssh/tmux session:

[2022-09-01 19:17:06] warn Failed to update keyring with new credentials: error updating keyring: Platform secure storage failure: User interaction is not allowed.

The registration process proceeds, no further error is shown but the server is not reachable. Repeating the registration after running the command:

`security unlock-keychain`

makes vscode-server work and complete the registration successfully.

Maybe this should be stated in the installation docs.

**Comment by connor4312** [comment]
We now gracefully fall back if requesting the keychain fails
