### ISSUE TITLE
Terminal not working after connecting to remote server

### ISSUE THREAD

**Issue by jzequn** [microsoft/vscode-remote-release#7151]
- VSCode Version:1.70.2
- Local OS Version: macOS Monterrey. version 12.3.1
- Remote OS Version:Arch Linux
- Remote Extension/Connection Type: SSH/Containers/WSL/Server
- Logs:

Steps to Reproduce:

1. Connect to remote server via remote development extension. 
2. input password to remote server.
3. press ` and ctrl in vscode to open the embeded terminal of vscode
4. terminal open without showing text. 

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No ( haven't try it yet)

![Screen Shot 2022-08-31 at 4 17 45 PM](https://user-images.githubusercontent.com/18434451/188132006-bf956d19-9ac9-4d69-820a-ed1c4305b6d2.png)

**Comment by tanhakabir** [comment]
Is this using any Remote extension?

**Comment by jzequn** [comment]
What's the other info needed for you to debug? Please let me know : )

**Comment by jzequn** [comment]
> Is this using any Remote extension?

I'm positive. 
I have run the embeded terminal of vscode without remote development extension (connecting to remote server) and it works properly. When I connect to a remote server using remote development extension, it open a new window and ask for password to the server. After entering the password, im able to see the files and folder of remote server. Then I press ` and ctrl to open embeded terminal. The embeded terminal is opened without any text on it. I can't input any command on it.

**Comment by jzequn** [comment]
I have uninstalled c/c++ extension under ssh: remote server in EXTENSIONS. 
Restart vscode and connect to remote server again. Terminal works again!
