### ISSUE TITLE
Fix "Failed to load message bundle" error in remote-ssh development

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#7154]
In the development build, we should not include the nls webpack loader. To check the mode flag, we need to change the config to export a function instead of an object

Example:

https://github.com/microsoft/vscode-remotehub/blob/main/extensions/remotehub/webpack.config.js#L83-L94

https://webpack.js.org/configuration/mode/#mode-none

**Comment by eleanorjboyd** [comment]
This issue was fixed in the most recent remote-SSH release
