### ISSUE TITLE
pubring.kbx not getting copied

### ISSUE THREAD

**Issue by Goldfels** [microsoft/vscode-remote-release#7156]
- VSCode Version: 1.70.1
- Local OS Version: Fedora Workstation 36
- Local chip architecture: x86
- Reproduces in: Remote - Containers

I'm currently developing a custom Docker container based on a custom Yocto image, that we'd like to use for development.
I'd like to run VSCode inside this container, so that the application being developed has a mostly consistent execution environment, that's very close to the real OS.

However, VSCode for some reason fails to copy this file (~/.gnupg/pubring.kbx), and only this file.

By manually copying this file into the container, and restarting the IDE twice, the container starts successfully.

**Comment by bamurtaugh** [comment]
Transferring as this sounds more Remote-Containers specific than focused on a specific dev container template.

@Goldfels is the flow that you see the .kbx file when you open the project locally in VS Code, and then reopening with Remote-Containers results in the file being missed?

**Comment by chrmarti** [comment]
Please append the log (`F1` > `Remote-Containers: Show Container Log`). Also make sure the container does not already have a pubring.kbx as we do not overwrite existing files.

**Comment by Goldfels** [comment]
It seems like after one of the updates, this problem has disappeared, and a new one emerged.

Now, the tar.gz file containing the remote server runs into a `gzip: unexpected end of file` error when the container tries to extract it. It works fine if I copy the file over and do it manually, but every time VSCode gets an update, it tries updating the server, and fails, which is rather annoying.

The `Show Container Log` option only showed me an empty window, but I uploaded the "remoteContainers" log file.
[remoteContainers-2022-09-19T13-46-39.762Z.log](https://github.com/microsoft/vscode-remote-release/files/9599463/remoteContainers-2022-09-19T13-46-39.762Z.log)
