### ISSUE TITLE
open jupyter notebook inside vscode server

### ISSUE THREAD

**Issue by khatbahusain** [microsoft/vscode-remote-release#7159]
How to properly open jupyter notebook inside vscode server ?

**Comment by eleanorjboyd** [comment]
Hello! Can you please provide further information so we can troubleshoot this issue. Please provide at least where you VS Code server is located, you ssh config settings, and the log files related to ssh and the vscode server on the host. This will help us determine if this is an SSH issue or direct you to the right group who can help- Thanks!

**Comment by khatbahusain** [comment]
I have a VS code server in running in my work station and i'm using it it from anywhere (in a web browser), now how can I run a jupyter notebook server in my work station using the web browser ?

`https://insiders.vscode.dev/+ms-vscode.remote-server/myworkstation `

Thanks !

**Comment by eleanorjboyd** [comment]
Hi! Could you share your ssh config file? You can access it by going to the command palette and looking up `open ssh configuration file` Also is your server up and running? If your server is running and vscode successfully installed on your server than you would just need to get the jupyter notebook on your server machine and run it like you would do so locally in the connected vscode window.

**Comment by eleanorjboyd** [comment]
Hello! Were you able to solve your issue? If so, we would love to hear your solution as it can help future users that come across similar errors. Let us know otherwise we will close this issue shortly due to lack of activity. Thanks!
