### ISSUE TITLE
Persist extensions installed after a dev container is built

### ISSUE THREAD

**Issue by szszoke** [microsoft/vscode-remote-release#7161]
It would be nice if there would be a way to persist extensions that were installed after a dev container is built.

An example: the project needs ESLint, so that is always installed via `devcontainer.json`.

I might also use a bracket pair colorizer extension, GitLens, a JSON sorter extension, etc.

I more or less always want to install these extensions but I do not necessarily want to force others to use them (or be forced to use someone else's extensions)

My only option is to manually install the extensions but they seem to be lost after the container is rebuilt.

An alternative to somehow persisting the extensions there could be a user setting for "default" extensions that are always installed, even if they do not appear in `devcontainer.json`

**Comment by chrmarti** [comment]
There are 'default extensions' in the user settings:
<img width="498" alt="image" src="https://user-images.githubusercontent.com/9205389/188560869-f20fcc22-4f8f-43ca-a4fd-ef9a1400e6d3.png">

These apply to all containers.

**Comment by szszoke** [comment]
This solves my problem. Thanks!
