### ISSUE TITLE
Coredump after installing code-server on fedora 36

### ISSUE THREAD

**Issue by marmolak** [microsoft/vscode-remote-release#7166]
- VSCode Version: code-1.71.0-1662018467.el7.x86_64
- Local OS Version: fedora 36
- Remote OS Version: fedora 36
- Remote Extension/Connection Type: nothing for now
- Logs:

Steps to Reproduce:

1. install from https://code.visualstudio.com/docs/remote/vscode-server
via `wget -O- https://aka.ms/install-vscode-server/setup.sh | sh`
on fedora 36 box
2. run `code-server`

Result:
Segmentation fault (core dumped)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Not relevant

More details:
$ strace code-server
execve("/usr/local/bin/code-server", ["code-server"], 0x7ffd735fa840 /* 50 vars */) = 0
mmap(NULL, 1136, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd13ffd1000
arch_prctl(ARCH_SET_FS, 0x7fd13ffd1390) = 0
set_tid_address(0x7fd13ff3829c)         = 138920
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xc2166} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

**Comment by connor4312** [comment]
This should now be fixed! Let me know if you continue to hit it

**Comment by marmolak** [comment]
Hi. It works :). Thanks!
