### ISSUE TITLE
issue with long hostname containing several special chars

### ISSUE THREAD

**Issue by colas31** [microsoft/vscode-remote-release#7170]
- VSCode Version: 1.71.0
- Local OS Version: Windows 11
- Remote OS Version: Linux 
- Remote Extension: remote-ssh v0.84.0
- Logs:

Issue: 
1.
We automate the "Open folder on a remote server" created on the fly. 
We are using this code to create the connection: 
```
const containerName = "xxx-develop-golang-xxx-ncel111111";
const uri = vscode.Uri.from(
                    { scheme: "vscode-remote",
                    authority: `ssh-remote+${containerName}`,
                    path: "/home/myproject"}
                )
await vscode.commands.executeCommand("vscode.openFolder", uri, {forceNewWindow: true});

```
This code is working fine, VSCode properly opens the folder on the specific remote host.

2. Close all VSCode windows
3. Open recent project from the welcome view: **myproject [SSH: xxx-develop-golang-xxx-ncel111111]** 
4. VSCode is not able to initialize the connection and we get the error:

> [13:12:48.119] Running script with connection command: ssh -T -D 55751 "xxx-develop-golang-xxx-ncel111111" bash
[13:12:48.124] Terminal shell path: C:\windows\System32\cmd.exe
[13:12:48.412] > ]0;C:\windows\System32\cmd.exe
[13:12:48.413] Got some output, clearing connection timeout
[13:12:49.460] > ssh: Could not resolve hostname xxx-develop-golang-xxx-ncel111111: No such host 
> is known.

After some investigation this issue appears only if the hostname is very long and contains lot of "-".
The hostname seems to be encoded.

I don't face the issue if the hostname is short. 
**with this hostname xxx-develop-golang-xxx opening a recent project is working correctly.**

Thanks
Best regards

**Comment by joshspicer** [comment]
> [13:12:49.460] > ssh: Could not resolve hostname xxx-develop-golang-xxx-ncel111111: No such host
is known.

Thanks for opening an issue.  This kind of error is coming directly from the `ssh` program on your machine and we have no way to influence that from this extension.
