### ISSUE TITLE
version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by cheungxi** [microsoft/vscode-remote-release#7173]
- VSCode Version: 20220903.2 (UTC 1662182760)
- Local OS Version:
- Remote OS Version: linux kernel 4.19.0 (Loongnix-20.2 base debian 10)
- Remote Extension/Connection Type: SSH/Containers/WSL/Server
- Logs:

```
/usr/local/bin/code-server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/code-server)

```

Steps to Reproduce:

1. I used `code-server` 2022-09-01 everythins is ok , but after i `sudo code-server update` to  20220903.2 (UTC 1662182760) . Run `code-server` is broken.

Does this issue occur when you try this locally?: NO
Does this issue occur when you try this locally and all extensions are disabled?: No

How I downgrade to previous version or compatible lastest version ?

**Comment by bamurtaugh** [comment]
@connor4312 would it make sense to open a feature request for managing versions, based on:

> How I downgrade to previous version or compatible lastest version ?

**Comment by everdrone** [comment]
Having the same problem, on Linux ARM64 (Ubuntu 18.04.6 LTS)
