### ISSUE TITLE
Unable to connect remote host

### ISSUE THREAD

**Issue by hakumard** [microsoft/vscode-remote-release#7177]
I tried to connect sjc-ads-3593 observing error 
[18:39:05.510] > mkdir: cannot create directory '/users/hakumard/.vscode-server': File exists
> Creating the server install dir failed...

**Comment by eleanorjboyd** [comment]
Hello! Could you please provide more detail on what you are trying to do and attach the full logs that you got as a result? Thanks!

**Comment by eleanorjboyd** [comment]
Hello! Were you able to solve your issue? If so, we would love to hear your solution as it can help future users that come across similar errors. Let us know otherwise we will close this issue shortly due to lack of activity. Thanks!
