### ISSUE TITLE
Custom devcontainer library repositories

### ISSUE THREAD

**Issue by michidk** [microsoft/vscode-remote-release#7181]
The default devcontainers are great, but I would like to create my own devcontainer templates containing my own dockerfiles and zsh configuration.

Basically, I want to create a repository like https://github.com/microsoft/vscode-dev-containers/ and then be able to browse it using the "Remote-Containers: Add Development Container Configuration Files" command.

**Comment by chrmarti** [comment]
Tracking as https://github.com/devcontainers/spec/issues/71. Thanks.
