### ISSUE TITLE
SSH targets icon disappear in pre-release version

### ISSUE THREAD

**Issue by lierik** [microsoft/vscode-remote-release#7186]
- VSCode Version: 1.71.1
- Local OS Version: MacOS Monterey 12.5.1
- Remote OS Version: v0.87.2022090715
- Remote Extension/Connection Type: SSH
- Logs: No logs

Besides, if i install the release version V0.84, everything works fine. But vscode will automatically "help" me update Remote-SSH into this pre-release version and then, ssh targets disappears.

How can i fix the release version V0.84? Or is this situation as expected?

**Comment by lierik** [comment]
I have already set "extensions.autoCheckUpdates": false  and "extensions.autoUpdate": false, but remote-ssh extension is still updated automatically, how can i change the setting so that i can use v0.84?

For pre-release, either no ssh targets in remote resource monitor, or no remote resource monitor in left sidebar.

**Comment by eleanorjboyd** [comment]
Hello! Could you please provide a screenshot of the missing SSH target icon? Additionally can you provide the logs from the `dev tools` console as this could explain an error which was causing the lack of display.

**Comment by jvillemure** [comment]
I think I have the same problem. After updating from Remote SSH v0.85 to v0.87, the Remote SSH host list in the explorer view disappeared. I would usually see a list of SSH hosts taken from my ssh config file, but now this list is not visible from anywhere in the Remote Explorer view (also, the SSH tab from the drop down list disappeared).

![Annotation 2022-09-22 120714](https://user-images.githubusercontent.com/35437328/191815230-4677fcc0-44ec-4444-86c7-86711ded2f90.png)

**Comment by lierik** [comment]
> 

Yes, we are almost same. But for me, it's worse. Sometimes there is even no "remote resources monitor" icon in the leftbar. When I reinstall this plugin and I cannot pull down the box "Remote explorer"， only one choice "Remote".

**Comment by eleanorjboyd** [comment]
Hello! Could one of your provide the ssh logs? They can be found by going to `terminal` then `output` then selecting `Remote-SSH` from the dropdown menu on the right. Additionally could you provide a screenshot of your ssh config file? Thanks

**Comment by jvillemure** [comment]
Hi, unfortunately I can't share this information as this might break corporate policies of my workplace. In any case, the issue doesn't seem to be related to a connection problem of any kind, as I can always connect to any of my configured SSH hosts defined in my ssh config file, or from my recently opened (ssh) workspaces, and the resulting behavior is the same as it used to be.

The only thing I noticed that have changed is the missing SSH hosts in the explorer view, so this is probably related to UI.

**Comment by lierik** [comment]
> Hello! Could one of your provide the ssh logs? They can be found by going to `terminal` then `output` then selecting `Remote-SSH` from the dropdown menu on the right. Additionally could you provide a screenshot of your ssh config file? Thanks

Sorry, exactly the same reason with @jvillemure, I cannot share the ssh config or log. But we are at the same situation. I can ssh my remote resources in terminal, and I can also get connection by "Connect to Host" through SHIFT + Command + P in vscode.

Just the icon and SSH hosts disappear, but the function is still available.

And one more thing, i realize there might be some errors in terminal initialization in vscode. Some of my $PATH env in remote machine cannot be initialized in the terminal of vscode, but can be initialized in vscode-insiders under the same version of Remote-SSH or MacOS terminal or iTerm.

**Comment by eleanorjboyd** [comment]
No worries, we understand corporate polices makes sharing information hard. Could you go to the command prompt and open `developer tools` and see if there are any error messages in there? In the meantime you can right click on the extension in the marketplace and click the switch to stable option instead of setting autoupdates to false to get around this issue. Thanks

**Comment by jvillemure** [comment]
@eleanorjboyd Hello,
the issue seems resolved after upgrading `Remote - SSH` to version 0.90.1. To verify this, I have disabled all extensions except for `Remote Development` pack v0.21.0 (`Remote SSH` v0.90.1, `Remote - SSH: Editing Configuration Files` v0.84.0, `WSL` v0.72.0, `Dev Containers` v0.259.0) , and I can see the same *SSH Targets* view I'm used to:
![image](https://user-images.githubusercontent.com/35437328/195369361-7ebfaa39-ba1e-42fb-b131-02815c1e231c.png)

**Comment by eleanorjboyd** [comment]
> the issue seems resolved after upgrading Remote - SSH to version 0.90.1. @jvillemure 

great! We pushed a fix so I am glad you can verify this, thanks!
