### ISSUE TITLE
SSH: do not close panel if user manually opened it

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-remote-release#719]
1. Connect to an SSH remote
2. While it is setting up quickly press Cmd + J to open the panel (which was closed before)
3. Once the SSH finishes setting up it will close the panel 🐛 

The SSH extension should only close the panel if it automatically opened it. Not if the user manualy opened it.
Apart from that we try not to do this smart changing of the UX for the user.

**Comment by roblourens** [comment]
Did you open it up to the terminal? I think when the terminal command is done and there are no other terminals, the panel is closed, maybe something else should happen?

**Comment by isidorn** [comment]
Yeah, I had the terminal open.
As a user if I explicitly opened the terminal that means I want a new terminal window. So once your terminal was finished I would expect the terminal to remain open and that I have a new clean terminal tab.

**Comment by Tyriar** [comment]
@isidorn are you on the nightly where the backgrounded terminal is being used? If so, you would have to press the details button to open the ssh connection terminal and I see this as designed since the terminal exits and it would be the last one.

**Comment by isidorn** [comment]
I explicitly opened the terminal pressing cmd + J.
I am using vscode insiders. I am not sure if it is using the backgrounded terminal.

**Comment by Tyriar** [comment]
I think you're using the stable ssh extension though, in the nightly extension the panel would not go away, you would open it and get a "Starting..." terminal. Just tested it and it works as expected, so the backgrounded terminal fixed this issue already.

**Comment by isidorn** [comment]
Yeah I am using the stable ssh extension. Sorry I misunderstood the question.
