### ISSUE TITLE
Remote SSH: stuck after authentication

### ISSUE THREAD

**Issue by azencodev** [microsoft/vscode-remote-release#7196]
Hi guys !

I am currently stuck after SSH authentication on remote OS (Windows server 2012 R2).
Remote-SSH output only characters W and C, and vs code server initialization doesn't progress...

- VSCode Version: 1.71.1
- Local OS Version: Windows 10 21H2 (x64) 
- Remote OS Version: Windows Server 2012 R2 (SSH version: OpenSSH_For_Windows_8.9p1, LibreSSL 3.0.2)
- Remote Extension/Connection Type: SSH (version: OpenSSH_For_Windows_8.1p1, LibreSSL 3.0.2)

![image](https://user-images.githubusercontent.com/39826070/190405341-9bed3046-b744-4600-ac29-6cdbfbcaa9e9.png)

Thanks

**Comment by eleanorjboyd** [comment]
Hello! Can you try running the same ssh connection command in a local terminal window outside of vscode and see if the issue occurs there as well?

**Comment by azencodev** [comment]
Hello !

Outside vs code, SSH connection works (tested with DOS)

On local :
***@***.***

On remote
***@***.***

Thanks
Christian

De : Eleanor Boyd ***@***.***>
Envoyé : mardi 20 septembre 2022 19:46
À : microsoft/vscode-remote-release ***@***.***>
Cc : Christian NGUYEN ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/vscode-remote-release] Remote SSH: stuck after authentication (Issue #7196)


Hello! Can you try running the same ssh connection command in a local terminal window outside of vscode and see if the issue occurs there as well?

**Comment by eleanorjboyd** [comment]
Hello again- could you try running it with this setting: `remote.SSH.useLocalServer` set to true in your `settings.json`? Appreciate it!

**Comment by azencodev** [comment]
Hello again

I have tried (updating remote.SSH.useLocalServer = true) and give me same result => infinite loop with WC on output, and indefinitely prompt me for password…

Thanks

De : Eleanor Boyd ***@***.***>
Envoyé : vendredi 23 septembre 2022 00:48
À : microsoft/vscode-remote-release ***@***.***>
Cc : Christian NGUYEN ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/vscode-remote-release] Remote SSH: stuck after authentication (Issue #7196)


Hello again- could you try running it with this setting: remote.SSH.useLocalServer set to true in your settings.json? Appreciate it!

**Comment by eleanorjboyd** [comment]
Hi @azencodev, it is interesting that the `useLocalServer` mode got stuck with an indefinite password prompt- could you include the logs from this try as well? And just to confirm do you have the right user set for this ssh connection in vscode? A indefinite password prompt might suggest an issue authenticating access via ssh but the logs should give more insight as well.

**Comment by eleanorjboyd** [comment]
Hello! Were you able to solve your issue? If so, we would love to hear your solution as it can help future users that come across similar errors. Let us know otherwise we will close this issue shortly due to lack of activity. Thanks!
