### ISSUE TITLE
Saving Python files in remote causes excessive CPU consumption and longer waiting time

### ISSUE THREAD

**Issue by guidocioni** [microsoft/vscode-remote-release#7198]
When working with Python files on a remote server (especially notebooks) saving them causes a spike in CPU usage (see screenshot) that basically makes the system unresponsive.

<img width="2044" alt="Screen Shot 2022-09-15 at 16 11 21" src="https://user-images.githubusercontent.com/12760310/190426610-d6977d38-1a5e-46a7-988d-ee4c5fb87850.png">

I cannot work on the code during this time as linting and suggestions are all halted. Usually it takes about 20-30 seconds to save a file which I think it's completely anomalous even for bad connections.

I made a video where you can clearly see the issue, unfortunately I cannot update it here on github: https://www.dropbox.com/s/p5pxitzptu9hmir/Screen%20Recording%202022-09-15%20at%2016.00.05.mov?dl=0 

I'm pretty sure this is related to PyLance or some weird code checking that is triggered on save but I don't have anything similar activated, plus I cannot reproduce the same issue locally. 

- VSCode Version: 1.71.1 
- Local OS Version: MacOs 12.5 
- Remote OS Version: CentOS Linux release 7.1.1503 (but it also happens on newer systems)
- Remote Extension/Connection Type: SSH

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
Could you file this issue on the python extension repo? Thanks!
