### ISSUE TITLE
Unable to GPG Sign Commit when running in Dev Container

### ISSUE THREAD

**Issue by swiffer** [microsoft/vscode-remote-release#72]
- VSCode Version: 1.34.0-insider
- Local OS Version: Win 10 1903 64bit
- Remote OS Version: 4.9.125-linuxkit [python:3.6 base image]
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Configure git to gpg sign commits [global .gitconfig locally]
```
[commit]
	gpgsign = true
```

2. Start project in dev container, try to commit
```
root@953bed01abcd:/workspaces/my-project# git commit -m dockerize
error: gpg failed to sign the data
fatal: failed to write commit object
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by jrobsonchase** [comment]
I've managed to get this to work by using `-v` to map my local gpg agent socket into the container, likewise with the ssh agent:

```json
"-v", "${env:HOME}/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx",
"-v", "${env:HOME}/.gnupg/trustdb.gpg:/root/.gnupg/trustdb.gpg",
// You'll probably have to change this to point to your gpg-agent socket.
// Not sure where Mac/Windows put it.
"-v", "${env:XDG_RUNTIME_DIR}/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent",
"-v", "${env:SSH_AUTH_SOCK}:${env:SSH_AUTH_SOCK}",
"-e", "SSH_AUTH_SOCK=${env:SSH_AUTH_SOCK}"
```

Not ideal, but it's a decent workaround and allows for signing commits in the container and fetching dependencies in private git repositories via ssh.

**Comment by smiller171** [comment]
@jrobsonchase unfortunately there are numerous problems with this if you're running on a Mac or Linux host.

I think it makes sense to allow git operations to run locally when using remote containers to avoid this issue, possibly hidden behind a flag.

**Comment by heberleh** [comment]
I have similar or same problem. I am using git on code-insiders bash with WSL as remote. What is strange is that sometimes it is working, and it stops working, or it is not working and then after some minutes it works.

I noticed that restarting code-insiders seems to make it work, but not always. I have no idea how to solve, I have tried the normal solutions for the messages "error: gpg failed to sign the data
fatal: failed to write commit object" that I found on the web. Nothing seems to work permanently.

**Comment by silenceisgolden** [comment]
Same issue if using Ubuntu WSL. I found a workaround using this repository but there is not a published, peer-reviewed package since the issue is fairly new.

https://github.com/diablodale/pinentry-wsl-ps1

**Comment by johnletey** [comment]
I'm not quite sure if this is the right place to ask this, but what's the best way to use your GPG key from your computer on your Raspberry Pi to sign commits. Do you transfer the key? Do you create a new one?

**Comment by vovimayhem** [comment]
I'm really interested on any updates on this.

Does anyone has been successful in signing Git commits within the dev container?

**Comment by chrmarti** [comment]
Got it implemented by copying pubring.kbx and trustdb.gpg into the container and then forwarding the agent socket in the container to the extra ('remote') socket on the local machine. This will need some testing in the wild to confirm it works as expected.

**Comment by ItalyPaleAle** [comment]
@chrmarti Do you mind sharing a code sample? Also, rather than copying the keyring (which is a manual operation), could we mount the GPG folder in the container instead?

**Comment by qqq689** [comment]
Is it possible to explain my explanation did not understand a lot please
clarify a few

في الاثنين، ١٨ أيار، ٢٠٢٠ ١١:١١ م Christof Marti <notifications@github.com>
كتب:

**Comment by qqq689** [comment]
Ok🌹😍

في الاثنين، ١٨ أيار، ٢٠٢٠ ١١:١٤ م Alessandro (Ale) Segala <
notifications@github.com> كتب:

**Comment by airtonix** [comment]
> Got it implemented by copying pubring.kbx and trustdb.gpg into the container and then forwarding the agent socket in the container to the extra ('remote') socket on the local machine. This will need some testing in the wild to confirm it works as expected.

Prove it.

show us a gif of it working on windows using docker-desktop for windows and vscode-remote connecting to a linux container.

until then this isn't solved.

**Comment by chrmarti** [comment]
@ItalyPaleAle You can still mount the GPG folder (or the individual files) if you prefer. The implementation checks if the files exist before writing them.

@airtonix This will be in the next version of the Remote-Containers extension. I have closed this issue for my own book-keeping.

**Comment by ItalyPaleAle** [comment]
@chrmarti Apologies, but I'm a bit confused... Did you fix this already? Does it work on the current version, or do we need to wait for the next version? Will there be some docs explaining how to do this?

**Comment by chrmarti** [comment]
@ItalyPaleAle It will be available with the next version. It should work out-of-the-box and we will add documentation as needed.

**Comment by LaysDragon** [comment]
It really tricky to setup to forward agent connection especially between windows and container myself,I almost forget how I done this before...Even though it can work but it still not that convenience ,and I give up to use container develop at the end years ago.
But I'm still excited to know that this feature is going to become build-in feature :D

**Comment by chrmarti** [comment]
This is available in the latest version of Remote-Containers (0.118.0). You will need VS Code Insiders to get that version at the moment. Make sure to have `gpg` installed locally and in the container (update the Dockerfile if needed).

Let me know if it works and open bug reports if it does not! 👍

**Comment by jtokoph** [comment]
Was super excited to try this out today @chrmarti! Currently seeing an issue with older versions of gpg2. Opened an issue here: #3048. In the meantime I'm working on getting my dev container setup with the latest gpg2.

**Comment by airtonix** [comment]
@chrmarti I think you've implmented something that assumes we want this feature turned on all the time...

so now this explodes our local docker environments.

**Comment by chrmarti** [comment]
@airtonix Let's try to make it work first. Could you open a new issue with details on what is not working?
