### ISSUE TITLE
Explain "Configuration file(s) changed" message

### ISSUE THREAD

**Issue by OldStarchy** [microsoft/vscode-remote-release#7200]
Sometimes I see this message.

<img width="428" alt="image" src="https://user-images.githubusercontent.com/15243523/190554783-c8d2e075-db76-48ad-8c43-e6fc0a645ca7.png">

I would like to know what changes it has detected.

I haven't changed anything in the config, the only thing I can think of is that I did a `docker image prune` yesterday, could that trigger this message?

**Comment by chrmarti** [comment]
The checksum on the devcontainer.json didn't match the previously recorded one. Is this a dev container opened on a local folder? Which OS is the host machine running?

**Comment by OldStarchy** [comment]
~~The project is in WSL2/Ubuntu-20.04 on Windows 11.~~

I found a change to the devcontainer.json that was pulled in from a rebase that added an extension, my bad for missing it the other day.
