### ISSUE TITLE
.NET docker debug breaks on remote WSL2 when configureSsl is enabled

### ISSUE THREAD

**Issue by marc-weber1** [microsoft/vscode-remote-release#7205]
- VSCode Version: 1.71.2
- Local OS Version: Windows 10 Pro 21H2
- Remote OS Version: WSL 2 Ubuntu 20.04 LTS
- Remote Extension/Connection Type: Remote SSH
- Logs:
```
The Docker extension will try to connect to 'unix:///var/run/docker.sock', via context 'default'.
Error: Process 'dotnet user-secrets --project "/mnt/c/...' exited with code 1
Error: Command failed : Access to the path '/home/[user]/.microsoft/usersecrets/758a6639-07ef-41d7-aa0d-54086b53b96f' is denied.
```

Steps to Reproduce:

1. For a dotnet project, use command palette to generate docker files and initialize for docker debugging
2. Add "configureSsl": true to docker-build: debug
3. Run & Debug Docker .NET Core Launch from the launch menu

This should be a non-issue, but "sudo" is not an allowed property anywhere, .microsoft/usersecrets can't be chmod'ed because I'm assuming it's a WSL2 folder, and I can't mount a file with my certificates in it like I can with docker-compose. Is there any other options?

**Comment by chrmarti** [comment]
Is this related to the C# extension? Could you open an issue at https://github.com/OmniSharp/omnisharp-vscode/issues?

**Comment by gregg-miskelly** [comment]
Sorry to give you the runaround, but I think you actually want to open this issue in https://github.com/microsoft/vscode-docker

**Comment by bamurtaugh** [comment]
Sounds like we can close in favor of https://github.com/microsoft/vscode-docker/issues/3623. If there's anything we'd like to still track here, please let me know. Thanks!
