### ISSUE TITLE
Pre Release doesn't Recognize SSH Targets

### ISSUE THREAD

**Issue by casonk** [microsoft/vscode-remote-release#7208]
Update to pre-release version of Remote - SSH and the SSH Target tab disappears in the remote explorer. 

Issue solved by downgrading from pre-release to v0.84.0

**Comment by eleanorjboyd** [comment]
Hello! Could you please provide a screenshot of the missing SSH target icon? Additionally can you provide the logs from the `dev tools` console as this could explain an error which was causing the lack of display.

**Comment by changshivek** [comment]
I have the same problem, my set up is vscode version 1.71.2 on ubuntu 22.04.1, I tried to install remote-ssh plugin version 0.87 and 0.85, both of these versions suffers from the same problem, that ssh target tab disappears from remote target tab. Unfortunately I cannot provide any screenshot or log file because I work in stand-alone LAN environment. Hope this bug get fixed soon.

**Comment by eleanorjboyd** [comment]
Hi @changshivek, totally understand. Could you see if `dev tools` produces any errors if this is something you are able to share?

**Comment by casonk** [comment]
Hello Together, 
Please see below the differences between stable and pre-release versions. 
![version stable](https://user-images.githubusercontent.com/72440835/193450378-7488b653-8d00-4e24-bde2-12d077359cf6.png)
![remote stable](https://user-images.githubusercontent.com/72440835/193450381-ce38419d-f047-403f-a236-a297a6cb06a9.png)
![version issue](https://user-images.githubusercontent.com/72440835/193450385-dab5a478-6033-4e43-9ef7-fbd155ddce2e.png)
![remote issue](https://user-images.githubusercontent.com/72440835/193450388-b6d8962e-5a10-4d27-a454-d2467777e630.png)

**Comment by eleanorjboyd** [comment]
Hello! This should be fixed on our newest release of stable, could someone confirm? Thanks!!

**Comment by casonk** [comment]
for v0.93.2022111515 confirmed ! thank you 👍
