### ISSUE TITLE
Remote-SSH: Provide an option that disables vscode server auto-downloading.

### ISSUE THREAD

**Issue by zeodtr** [microsoft/vscode-remote-release#7211]
Nowadays, https://update.code.visualstudio.com is often very slow and error-prone.

And Remote-SSH automatically downloads a new version of vscode server when startup and is unusable until the new version is downloaded.

With the above two combined, VSCode is literally unusable.

So, please provide an option that disables vscode server auto-downloading, so I can at least work with the old version that's already working.

**Comment by eleanorjboyd** [comment]
Hello! Your vscode server updates to match your client vscode version so to stop vscode from downloading a new version on the server you can disable the updates for the client vscode by toggling the `update.mode` setting. If you could provide the logs for the remote-ssh console that could also provide information about these repeat errors which by resolving could improve your experience.

**Comment by zeodtr** [comment]
@eleanorjboyd I think remote-ssh console log is not necessary. It's just a downloading problem. Vscode server update stuck on downloading the update file. I tried downloading the update file manually when the updating vscode server took a long time, and the situation was the same - manual downloading also took a long time (and failed). Eventually, I succeeded in downloading the update file using wget and manually updated the vscode server.

**Comment by eleanorjboyd** [comment]
Yes this makes sense, it might be worth setting `"remote.SSH.localServerDownload"` to `true` to see if your host connection speed is faster and could speed up the process. Otherwise toggling the `update.mode` setting could also help in the future.
