### ISSUE TITLE
Delete remote server tunnel

### ISSUE THREAD

**Issue by JustDanMan** [microsoft/vscode-remote-release#7212]
When I connect a code-server instance to vscode.dev via GitHub account I can't delete the connection if I don't use it anymore. It would be nice to have a option to delete old entries in the machine list. Otherwise the name cannot be reused.
<img width="457" alt="vscode-remote-list" src="https://user-images.githubusercontent.com/7783735/190972104-bab32b36-a1fe-440e-a252-6fe6b6bf350d.png">

**Comment by mat-wang** [comment]
> When I connect a code-server instance to vscode.dev via GitHub account I can't delete the connection if I don't use it anymore. It would be nice to have a option to delete old entries in the machine list. Otherwise the name cannot be reused. <img alt="vscode-remote-list" width="457" src="https://user-images.githubusercontent.com/7783735/190972104-bab32b36-a1fe-440e-a252-6fe6b6bf350d.png">

Meet the same issue when my physical server lost all data suddenly, and there is always an unused tunnel showed in the list. And because the old instance has been deleted, there is no way to run `code-server unregister` command anymore...

Hope delete unused feature will be available in the future!

**Comment by bamurtaugh** [comment]
Hi there - are you able to unregister machines with the steps shown [here](https://github.com/microsoft/vscode-remote-release/issues/6942#issuecomment-1247310436)? I think that'd address this issue.

**Comment by JustDanMan** [comment]
Great, in the insiders build the function is available. Thank you!
