### ISSUE TITLE
postCreateCommand do not use git credential helper from vscode

### ISSUE THREAD

**Issue by RobertGalatNordic** [microsoft/vscode-remote-release#7215]
I want to download private rpository during setup of devcontainer but I'm asked for username and passwrod

I have credential helper set in .gitconfig. When I use 
`"postCreateCommand":["bash", "-c", "git config -l"],`
I got following output:
```
Run in container: bash -c git config -l
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
credential.helper=!f() { /home/.vscode-server/bin/74b1f979648cc44d385a2286793c22
6e611f59e7/node /tmp/vscode-remote-containers-659223eac41462e2a2b20518b548d52d47
8a3955.js $*; }; f
safe.directory=*
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
```

When I try to download private repo, I get ask about username, but when I delete postCreateCommand form devcontainer.json, and execute the same git pull command inside the container, it works right away, and do not ask me for password

Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:12:14.256Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-46-generic snap
Sandboxed: No

Steps to Reproduce:

1. add postCreateCommand step to devcontainer that will pull private repository form github via https
`"postCreateCommand":["bash", "-c", "git clone https://url_to_private_repo"],`
2. rebuild container
3. the container asks for username

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
Could you append the log from when this fails? (`F1` > `Remote-Containers: Show Container Log`)
