### ISSUE TITLE
Server no longer applies --port argument

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#7216]
Tests started failing without changes except that we always test with the latest VS Code Insiders build: https://github.com/microsoft/vscode-remote-containers/actions/runs/3089922157/jobs/4998082564

The log shows `--port 1234` being passed and port 8000 being used:
<img width="1482" alt="image" src="https://user-images.githubusercontent.com/9205389/191342776-91a56877-ca76-450f-adf7-d503202cc805.png">

The above build is using 1.72 insiders a829fbb91cbae44afb6a389341a0763fb3a6ac6f.

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode/pull/161254
