### ISSUE TITLE
Unable to attach to container on remote host over Remote-SSH

### ISSUE THREAD

**Issue by tgrosinger** [microsoft/vscode-remote-release#7218]
- VSCode Version: 1.71.2
- Local OS Version: Windows 11 - 10.0.22000
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH and Container

I am trying to open a workspace on remote machine in a container on the remote machine. I am attempting to follow [these instructions](https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host#_connect-using-the-remote-ssh-extension-recommended) which claim that Docker Desktop is not required on the local machine. However, when running "Remote-Containers: Reopen in Container" or "Attach Visual Studio Code" in the Docker extension I receive an error that Docker must be installed.

![DockerVersion](https://user-images.githubusercontent.com/597386/191584403-9276b2b5-52b9-4829-9c57-7b8eb59eca1f.png)

Steps to Reproduce:

1. Open VS Code locally on Windows without Docker Desktop installed.
2. Connect to remote workspace using Remote SSH extension. Key-based auth is being used.
3. Run "Remote-Containers: Reopen in Container"

Please let me know if I can provide additional details. If I understand correctly the instruction in that doc linked above is exactly what I am looking for, it just does not seem to behave as described. Thank you.

**Comment by chrmarti** [comment]
You still need Docker on the SSH server. Which version of Docker do you have installed there?

**Comment by tgrosinger** [comment]
That command to show the container log was very helpful, thank you!

This error was caused because I have configured my VS Code to use podman when using containers in WSL2. I'll have to see if there's a place I can put that configuration so it uses Docker when connecting over ssh to this machine, but podman when running locally.

**Comment by tgrosinger** [comment]
It seems that having `"remote.containers.dockerPath": "podman"` in my user settings, and `"remote.containers.dockerPath": "docker"` in my settings on the ssh host doesn't seem to work. The only solution I've found so far is to temporarily remove the setting for podman from my user settings.
