### ISSUE TITLE
local terminal

### ISSUE THREAD

**Issue by angtysj** [microsoft/vscode-remote-release#7221]
how to open new local terminal when opened reemote terminal in same window

**Comment by eleanorjboyd** [comment]
Hello! Could you elaborate a bit further? You are attempting to have both a local and a remote terminal in the same vscode window? Is the vscode window running on a server via ssh?

**Comment by Tyriar** [comment]
See docs here: https://code.visualstudio.com/docs/terminal/advanced#_local-terminals-in-remote-windows
