### ISSUE TITLE
SSH remote editing + Markdown preview + PlantUML: plantuml code section won' t show up

### ISSUE THREAD

**Issue by MeatBoy106** [microsoft/vscode-remote-release#7224]
Type: <b>Bug</b>

Preliminary note: I'm note using Markdown Preview Enhanced (which has its own issues with plantuml). I'm using the native Markdown previewer.

The issue arises while previewing a Markdown file that contains a plantuml code block in an SSH remote editing session with the PlantUML extension installed. I have configured PlantUML to use a local rendering server.

Minimum markdown file that triggers the issue:
``` markdown
```plantuml
@startuml
Bob -> Alice: Hello
@enduml
```plantuml
``` 

Expected result: the plantuml block is rendered by the server to be displayed in the markdown preview.
Observed result: a tiny default placeholder icon (![image](https://user-images.githubusercontent.com/15690897/191749840-5f851580-9c41-47ee-8b0b-21d8093a1664.png)) is displayed in place of the diagram.

Related observations:
- Preview works fine in local editing sessions using the same PlantUML rendering server as with the SSH remote edition session.
- Markdown preview security settings are not at play. If I set it to strict, I get the expected error message saying some untrusted content was blocked. If I set it to any other value, I don't get any error but I get that icon in place of the diagram when using SSH remote editing.

Extension version: 0.84.0
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-46-generic
Remote OS version: Linux x64 5.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (14.87GB free)|
|Process Argv|--crash-reporter-id f254e8dd-15b4-4f7e-904b-54d84726c6e9|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ar001vm|
|OS|Linux x64 5.15.0-46-generic|
|CPUs|Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz (6 x 2394)|
|Memory (System)|31.35GB (20.90GB free)|
|VM|40%|

|Item|Value|
|---|---|
|Remote|SSH: ar001vm|
|OS|Linux x64 5.15.0-46-generic|
|CPUs|Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz (6 x 2394)|
|Memory (System)|31.35GB (20.90GB free)|
|VM|40%|
</details>

**Comment by mjbvz** [comment]
Please start by filing this issue against the PlantUML extension . The should be able to investigate and let us know what is causing the problem if VS Code has a bug
