### ISSUE TITLE
No sign of forwarding port

### ISSUE THREAD

**Issue by jerrylin96** [microsoft/vscode-remote-release#7227]
[docum](https://code.visualstudio.com/docs/remote/ssh#_remember-hosts-and-advanced-settings)

shows a forwarded port section, but I do not see that in the IDE

**Comment by chrmarti** [comment]
There is a Ports panel at the bottom. I think the docs need to be updated there.

**Comment by bamurtaugh** [comment]
Opened https://github.com/microsoft/vscode-docs/pull/5667.
