### ISSUE TITLE
vscode can't connect wsl 

### ISSUE THREAD

**Issue by theta25** [microsoft/vscode-remote-release#7231]
- VSCode Version:1.71.2 (system setup)
-- commit: 74b1f979648cc44d385a2286793c226e611f59e7
- Local OS Version:Windows _NT x64 10.0.22621
- Remote OS Version:Ubuntu-20.04
- Remote Extension/Connection Type: WSL
- Logs:

Steps to Reproduce:

1. open terminal enter ubuntu-20.04 system
2. cd project/xx
3. code .
4. vscode started but can't connect ubuntu
![image](https://user-images.githubusercontent.com/62426262/191922452-61db82ad-06a0-4779-aaa7-f71b8a8a63c2.png)

**Comment by bamurtaugh** [comment]
What is the output if you run `wsl --status` in a terminal?
