### ISSUE TITLE
Remotes only Reload when Window is Active

### ISSUE THREAD

**Issue by bphunter1972** [microsoft/vscode-remote-release#7234]
Type: <b>Bug</b>

* Open a number of remote projects and merge them all into one window.
* Wait for computer to go to sleep.
* Wake computer and see that you receive a connection authorization request for each project.
* Without switching between projects, only the project that is front and center will reload properly.
* The others will attempt to re-load in 30 seconds and will again request authorization access.
* This will continue until you have brought all windows to the front and have re-loaded each one individually.

Extension version: 0.87.2022090715
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:05:37.721Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 3.10.0-1062.1.2.el7.x86_64
Remote OS version: Linux x64 3.10.0-1062.1.2.el7.x86_64
Remote OS version: Linux x64 3.10.0-1062.1.2.el7.x86_64
Remote OS version: Linux x64 3.10.0-1062.1.2.el7.x86_64
Remote OS version: Linux x64 3.10.0-1062.1.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|10, 10, 8|
|Memory (System)|16.00GB (1.53GB free)|
|Process Argv|--crash-reporter-id ed8eb4ec-682d-46cd-9f6c-960816ecada1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: msc-bphunter01.csg.apple.com|
|OS|Linux x64 3.10.0-1062.1.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz (2 x 2992)|
|Memory (System)|7.64GB (5.34GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: msc-bphunter01.csg.apple.com|
|OS|Linux x64 3.10.0-1062.1.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz (2 x 2992)|
|Memory (System)|7.64GB (5.34GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: msc-bphunter01.csg.apple.com|
|OS|Linux x64 3.10.0-1062.1.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz (2 x 2992)|
|Memory (System)|7.64GB (5.34GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: msc-bphunter01.csg.apple.com|
|OS|Linux x64 3.10.0-1062.1.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz (2 x 2992)|
|Memory (System)|7.64GB (5.34GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: scv-bphunter01.csg.apple.com|
|OS|Linux x64 3.10.0-1062.1.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6246 CPU @ 3.30GHz (2 x 3292)|
|Memory (System)|7.64GB (5.81GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
fc301958:30573243

```

</details>

**Comment by bamurtaugh** [comment]
Are you using the Remote-SSH extension? Or a combination of SSH, dev containers, WSL?

**Comment by bphunter1972** [comment]
Remote-SSH

**Comment by eleanorjboyd** [comment]
Hello! Do you have LocalServerMode set to true? This allows all the windows to have a shared SSH connection. Secondly when you wake your computer is it totally disconnected or trying to reconnect (does an error pop up saying it disconnected or does it look like it is already attempting a retry)?

**Comment by bphunter1972** [comment]
If you mean remote.SSH.useLocalServer, then no it is not set.
If you mean remote.SSH.localServerDownload, that is set to always.

When the computer wakes back up, it will try to reconnect automatically. Memento will pop up and I'll approve it. If the window is not front and center, it will fail. If it showing on the screen, it will pass.
If it's in a tab that is not shown (when all tabs are merged), it will fail.

Then, it will try reloading, with this process repeating.

**Comment by eleanorjboyd** [comment]
Could you try enabling useLocalServer? This setting enables a mode for connecting using a single connection shared between windows and across window reloads. This makes it faster to open new windows and should reduce the number of times a password needs to be entered.

**Comment by bphunter1972** [comment]
The issue remains.

After changing the settings yesterday and re-running, I left 3 tabs open all in the same merged window. 
After waking the computer, all 3 tabs say that they cannot reconnect and all three need to be re-loaded, separately, and re-authenticated.

**Comment by eleanorjboyd** [comment]
Hello! Sorry for all the questions but is your computer sleeping for more than 8 hrs? If not then it is likely connected to this issue we plan to address soon regarding attempting reconnection following short sleep: https://github.com/microsoft/vscode-remote-release/issues/5755.

**Comment by eleanorjboyd** [comment]
Ok sounds good- since this is less than 8 hours I am closing this as a dup of #5755 so please subscribe to notifications there to stay up to date on when a fix is released. Thanks!
