### ISSUE TITLE
VSCode fully hangs when connecting to an SSH target. No logs.

### ISSUE THREAD

**Issue by munael** [microsoft/vscode-remote-release#7235]
- VSCode Version: `1.72.0-insider (user setup)` at `2022-09-23T15:06:00.185Z`
- Local OS Version: `Windows_NT x64 10.0.19044`
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Connect to a remote.
2. The whole VSCode window is unresponsive. No logs are printing even with the Output pane opened up and switched to `Remote - SSH`.
3. The only thing animated is a spinning `Activating Extensions` in the status bar. This did not happen before. No extensions were updated while updating VSCode and the SSH extension.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by eleanorjboyd** [comment]
Hello! Could you outline more specifically what happens before it comes unresponsive? Is the remote window unresponsive? How did you connect to the remote? From the UI, within the current window etc. Finally are there any errors in the `developer tools` sidebar you can access via the command palette?

**Comment by eleanorjboyd** [comment]
Hello! Were you able to solve your issue? If so, we would love to hear your solution as it can help future users that come across similar errors. Let us know otherwise we will close this issue shortly due to lack of activity. Thanks!
