### ISSUE TITLE
Source Control panel does not respond to git command running in integrated terminal

### ISSUE THREAD

**Issue by krave1986** [microsoft/vscode-remote-release#7236]
- VSCode Version: 1.71.2
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 22.04.1 LTS
- Remote Extension/Connection Type: Containers
- Logs:

Steps to Reproduce:

1.Edit files which are bind mounted in container
2.Run `git add .` to stage the changes.

![image](https://user-images.githubusercontent.com/16416541/192066420-ee248192-e356-4db3-a2fe-6a97702bc57b.png)

Source Control panel does not reflect the fact that the changes have already been staged by git.

3. Hit refresh button in Source Control panel can bring these changes into **Staged Changes**.
![image](https://user-images.githubusercontent.com/16416541/192066564-035b0f24-2dd7-4fce-b4d5-a12902bc7b66.png)

But there is no need to do this step 3 on Windows locally.

**Comment by krave1986** [comment]
It turns out it is another issue introduced by bind mount. If I clone the source into a named volume, the issue will gone. Maybe we should use this method as a default one and advocate in docs.

**Comment by chrmarti** [comment]
Another option is to use a WSL folder for the project and open the dev container from that.

Closing as this is an upstream issue. Thanks.
