### ISSUE TITLE
Extension in container but its not installed anywhere (anymore)

### ISSUE THREAD

**Issue by andreujuanc** [microsoft/vscode-remote-release#7239]
I have this issue where I used to have Copilot installed on my local (windows) settings. And it, of course, appeared in all my devcontainers after creations. But shortly after, I decided not to continue using it, but it stayed in my existing and newly build containers.

I have tried to rebuild the containers, and also rebuild without cache option. But the extension (which is nowhere to be found locally) still appears. I have also make sure it's not on my wsl settings, nor in the devcontainer.json file.

I had initially open a ticket on copilot repo, but after some debate we think it's a bugerino (or just a feature?) on the extensions management. https://github.com/orgs/community/discussions/33479#discussioncomment-3719156

- VSCode Version: 1.71.2
- Local OS Version:  Win 11 (10.0.22000.978)
- Remote OS Version: Ubuntu 20.04.5 LTS
- Remote Extension/Connection Type: SSH/Containers/WSL/Server: Containers (not using docker desktop, but docker installed in WSL2)

Steps to Reproduce:

1.  Install extension on main host OS
2.  Create new devcontainer, build and open
3.  Use extension within the devcontainer
4.  Close devcontainer
5.  Uninstall such extension from #1
6.  Re-open the devcontainer, extension still there.
7.  Re-build without cache, extension still there.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

Local list
![image](https://user-images.githubusercontent.com/360052/192089405-c17c22ef-eb9b-4163-8aa9-812d2887e835.png)

WSL2 list:
![image](https://user-images.githubusercontent.com/360052/192089424-5ae14454-7ecb-4c88-8ac0-1fa8637e84fe.png)

A repo that I created yesterday:
![image](https://user-images.githubusercontent.com/360052/192089470-eff04526-04d7-476d-bebd-b6fc5deafcfb.png)

My assumption is that the extension got installed in a docker layer that it was not supposed to, and now it will be added to any new project I create :/

**Comment by andreujuanc** [comment]
I just did a system prune, made sure everything was clean, no images, nothing. And Copilot is not installed either in my local host nor in WSL2, then I went and open a repo in a devcontainer:
![image](https://user-images.githubusercontent.com/360052/192158400-b43d222a-10ca-4315-93e1-bac4a901e140.png)

This is VERY strange.

**Comment by andreujuanc** [comment]
Found the culprit:
![image](https://user-images.githubusercontent.com/360052/192158498-925701a2-e116-49ad-8650-c090e4b26522.png)

**Comment by chrmarti** [comment]
Thanks for following up. Closing as expected behavior.
