### ISSUE TITLE
[Code Server] Better connectivity for users in other regions

### ISSUE THREAD

**Issue by ofseed** [microsoft/vscode-remote-release#7242]
I've been trying to use the vscode server for some days, but I found except for using the serve-local mode, the connection between my browser and vscode is unstable while the latency is very high.

Both I and my vscode server instance are in Beijing, China, obliviously the above situation is caused by this,
Will this problem be improved in the future?

**Comment by bamurtaugh** [comment]
Thanks for opening. I'm curious if visiting vscode.dev without using the server also has highly latency? Or is it just when using vscode.dev + the server?

**Comment by ofseed** [comment]
No, it seems that vscode.dev without the server downloads data needed and runs locally, while there may be less Internet connection in this situation.

**Comment by ofseed** [comment]
By the way, I tried the serve-local mode a few days ago, which works pretty well.

**Comment by bamurtaugh** [comment]
cc @connor4312 @joaomoreno not sure if there are other things to investigate, I've seen a handful of users mention this.

**Comment by connor4312** [comment]
This is entirely on the Dev Tunnels side -- not sure if the have a cluster in China yet, cc @derekbekoe

**Comment by derekbekoe** [comment]
We **do not** have an instance in China but **do** have an instance in Southeast Asia (Singapore). I'd expect latency from China to be performant enough against Southeast Asia.

To confirm that you are being routed to the best region for you, run `code-server --verbose` and comment here with the log line that starts with `Connected to tunnel endpoint:`. We can use that info to check.

Additionally, network conditions outside of our control can also impact latency such as: use behind a VPN, poor Internet connectivity, etc.

**Comment by ofseed** [comment]
> Connected to tunnel endpoint: TunnelRelayTunnelEndpoint { base: TunnelEndpoint { connection_mode: TunnelRelay, host_id: "2cd458a7-da14-4dd1-8e5f-f4cd81be539c", host_public_keys: [], port_uri_format: Some("https://flpj6d5v-{port}.asse.rel.tunnels.api.visualstudio.com/"), port_ssh_command_format: Some("ssh flpj6d5v-{port}@asse.rel.tunnels.api.visualstudio.com") }, host_relay_uri: Some("wss://asse-data.rel.tunnels.api.visualstudio.com/api/v1/Host/Connect/flpj6d5v"), client_relay_uri: Some("wss://asse-data.rel.tunnels.api.visualstudio.com/api/v1/Client/Connect/flpj6d5v") }

Before this test, I disabled all VPNs and kept excellent internet connectivity.

**Comment by derekbekoe** [comment]
That's the correct region. Over time, we plan to expand to additional regions.

**Comment by baitian752** [comment]
@derekbekoe  Hi, I have the same problem. I am in Shanghai, China, my server is in Nanjing, China.

> Connected to tunnel endpoint: TunnelRelayTunnelEndpoint { base: TunnelEndpoint { connection_mode: TunnelRelay, host_id: "a24398d0-0178-4c99-a2c2-35ddda9950df", host_public_keys: [], port_uri_format: Some("https://mtn71frb-{port}.asse.devtunnels.ms/"), port_ssh_command_format: Some("ssh mtn71frb-{port}@asse.devtunnels.ms") }, host_relay_uri: Some("wss://asse-data.rel.tunnels.api.visualstudio.com/api/v1/Host/Connect/mtn71frb"), client_relay_uri: Some("wss://asse-data.rel.tunnels.api.visualstudio.com/api/v1/Client/Connect/mtn71frb") }

**Comment by derekbekoe** [comment]
Thanks for the feedback. To help us prioritize expansion to future regions, can you share the top 2 or 3 regions and latencies that show up with the lowest latency?
https://azurespeedtest.azurewebsites.net/ (external site)

Also, where specifically is this impacting your `code-server` experience (e.g. slow typing)?

**Comment by baitian752** [comment]
![屏幕截图 2022-11-15 125306](https://user-images.githubusercontent.com/28034106/201829557-c24eadee-2b10-4f12-aa6d-8da7bd395856.png)

Besides slow typing, listing file is also slow when opening folder or file, and occasionally get disconnected.

**Comment by derekbekoe** [comment]
Thanks for the additional information. Those latencies would not significantly impact your experience.
I think there's something else going on here.

Were you, or had you just tried to, download a large file around the time you saw the slow behavior?

**Comment by MiguelRodo** [comment]
Exactly the same issues as @baitian752, with similar latency:
![image](https://user-images.githubusercontent.com/23501332/206382022-78db453a-162b-4bf8-b5d7-ea8b20f9c520.png)

The slow behaviour (typing, file updates etc.) has been consistent ever since `code-server` came out. It's slow enough that I'd rather just use the shell and vim on our HPC.

**Comment by derekbekoe** [comment]
We recently expanded to additional regions and will continue to expand to more over time.

For future reports of this, please include as much of the following as possible:
- The tunnel endpoint information (can be retrieved by running `code tunnel --verbose`)
  - For example: ```Connected to tunnel endpoint: TunnelRelayTunnelEndpoint { base: TunnelEndpoint { connection_mode: TunnelRelay, host_id: "...", host_public_keys: [], port_uri_format: Some("[https://dcbm35xg-{port}.brs.devtunnels.ms/](https://dcbm35xg-%7Bport%7D.brs.devtunnels.ms/)"), port_ssh_command_format: Some("ssh dcbm35xg-{port}@brs.devtunnels.ms") }, host_relay_uri: Some("wss://brs-data.rel.tunnels.api.visualstudio.com/api/v1/Host/Connect/dcbm35xg"), client_relay_uri: Some("wss://brs-data.rel.tunnels.api.visualstudio.com/api/v1/Client/Connect/dcbm35xg") }```
- Country/location of the client (i.e. where you're connecting from)
- Country/location of the remote machine
- Was the perceived slow-down when interacting with VS Code directly or a web-forwarded port?
- Were you interacting with large files? (e.g. downloading/uploading files in the VS Code session). This is tracked by https://github.com/microsoft/vscode-remote-release/issues/7726.

**Comment by derekbekoe** [comment]
Since my last comment, we've expanded to further regions.
Closing this issue since there have not been recent comments.

If you are continuing to see high latency please [install the devtunnel CLI](https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started?tabs=macos#install) and send the output of `devtunnel clusters --ping`.
