### ISSUE TITLE
Allow starting VSCode SSH directly from the CLI

### ISSUE THREAD

**Issue by loligans** [microsoft/vscode-remote-release#7243]
I am running in a Windows environment. I have WSL2 running and a Docker container running within WSL2. I have set up a proxy to enable the Docker Container to forward `xdg-open` calls to the WSL2 host. The result of this is that I can execute `xdg-open vscode://new-window` and VSCode opens on the Windows host.

The docker containers I spin up are ephemeral so it doesn't make sense for them to have their own SSH Config entry.

The feature I would like to propose is to enable a command to connect directly to the remote machine via the VSCode CLI. `vscode://ms-vscode-remote.remote-ssh/opensshremotes.connectRemote?args{"host":"etc...","options":{"StrictHostKeyChecking": "no"}}` In this way no SSH configurations need to be saved.

The result is I could call this command from the Docker host and VSCode would startup on the Windows host and connect via SSH to the Docker host.

**Comment by chrmarti** [comment]
Have you tried using the Dev Containers extension? That allows you to connect to an existing container or can create a container from a devcontainer.json configuration file.
