### ISSUE TITLE
Windows shouldn't copy ~/.gitconfig to /home/vscode/.gitconfig in the container

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode-remote-release#7247]
- VSCode Version: `1.71.0`
- Local OS Version: `Windows_NT x64 10.0.19043`
- Remote OS Version: `Debian GNU/Linux 11 (bullseye)` (Container)
- Remote Extension/Connection Type: `Containers`
- Logs: N/A

Steps to Reproduce:

1. `Remote-Containers: Open Folder in Container`
2. Choose a folder
3. Choose `Java 8`
4. Choose `bullseye`
5. Choose `lts/* (default)`
6. Choose `Install Maven` and `Install Gradle`
7. Choose nothing for additional features
8. After vscode-container been boot up. Open terminal.
9. Run `git config --global core.autocrlf` to check `core.autocrlf` config

    In my Windows, the default is `true`. BUT in Linux, this MUST be `false`.

11. Run `git config --global core.editor` to check `core.editor` config

    In my Windows, the default is `notepad`. BUT in Linux, this SHOULD be `vi` by default.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
This can be turned off in the user settings:
<img width="936" alt="image" src="https://user-images.githubusercontent.com/9205389/192496026-8c7621a7-b870-40f3-be34-0eec4c799955.png">

Does this help?

**Comment by doggy8088** [comment]
That is helpful. Thanks.

But I still want to suggest add some tuning for the default behavior. Copy Git Config to the container by default will be okay for Linux/macOS users and not for Windows users. It just cause some negative issues especially for new Remote Container users.

**Comment by chrmarti** [comment]
We now unset core.editor if it can't be found in the container. Having `core.autocrlf` the same inside the container as outside might still make sense, because you can edit the same files locally or in the container.
