### ISSUE TITLE
Container warns about memory, even though its set to exact value in Docker

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-remote-release#7250]
Type: <b>Bug</b>

Dev Container doesn't let me open my project even though I am really close in spec (actually 100% in spec in my config)

Extension version: 0.253.0
VS Code version: Code - Insiders 1.72.0-insider (831678f718c8e998adc40d4854d9d35d9586a09f, 2022-09-26T09:36:38.583Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

**Comment by chrmarti** [comment]
What do you get for `docker info --format '{{json .}}'` and what are the host requirements in your devcontainer.json?
