### ISSUE TITLE
Git username and email isn't set in container

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-remote-release#7251]
Type: <b>Bug</b>

While commiting works on my laptop, commit in my dev container fails with "Make sure you configure your 'user.name' and 'user.email' in git.". Or from the logs: `fatal: no email was given and auto-detection is disabled`.

I would assume that the dev container does inherit from my local machine.

<img width="922" alt="image" src="https://user-images.githubusercontent.com/8599/192426538-c3be6579-9eb4-4c48-aee3-947fa240b366.png">

Extension version: 0.253.0
VS Code version: Code - Insiders 1.72.0-insider (831678f718c8e998adc40d4854d9d35d9586a09f, 2022-09-26T09:36:38.583Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.124-linuxkit

**Comment by chrmarti** [comment]
It copies the local `~/.gitconfig` to the container if the container does not have one already. If that doesn't explain it, please attach the full log from after rebuilding the container (`F1` > `Dev Containers: Show Container Log`).
