### ISSUE TITLE
Attaching to running container does not install extensions

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-remote-release#7252]
Testing #7248

Not sure if this is as designed or not.

* basically all the CLI steps in #7248
* open a new window
* run the action `Dev Container: Attach to Running Container...`
* pick the container with `-workspace-` in its name
* the extensions `chrmarti.regex` or `ms-vscode.hexeditor` don't get installed
* I've also tried the action `Dev Container: Open Folder in Container` and picked the `workspace` folder. Also in this case, the two vscode extensions were not installed:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/5047891/192544345-adb914d9-d871-4044-8c6c-fed1868d3c33.png">

**Edit**: The extensions I was expecting only got installed when executing `Rebuild Container`:

<img width="524" alt="image" src="https://user-images.githubusercontent.com/5047891/192544677-c36d8c6b-8576-49ff-b8e0-e2ec4d39fa09.png">

**Comment by chrmarti** [comment]
Currently expected. We need a `devcontainer attach` command.

Related: https://github.com/devcontainers/spec/issues/20

**Comment by chrmarti** [comment]
This was fixed with https://github.com/microsoft/vscode-remote-release/issues/7872.
