### ISSUE TITLE
devcontainer.json settings should take precedence over image metadata

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-remote-release#7254]
Testing #7248

* basically all the CLI steps in #7248
* modify `workspace/.devcontainer.json` to be:
```
{
	"image": "test-base-image",
	"postAttachCommand": "echo 'Hello from the postAttachCommand in the workspace image!'",
	"customizations": {
		"vscode": {
			"extensions": ["ms-vscode.hexeditor"],
			"settings": {
				"terraform.languageServer.enable": false
			}
		}
	}
}
```
* (notice the above configures `"terraform.languageServer.enable": false`)
* Rebuild Container and open the machine settings
* observe the setting is `"terraform.languageServer.enable": true` instead of `false`.

**Comment by rzhao271** [comment]
The Terraform extension doesn't seem to install for me

**Comment by rzhao271** [comment]
@alexdima are you able to verify this issue?

**Comment by rzhao271** [comment]
I also tried rebuilding and reopening the workspace container, selecting the Alpine Linux definition. Then, I installed the Hashicorp Terraform extension, which doesn't come with the `terraform.languageServer.enable` setting.

**Comment by chrmarti** [comment]
Attaching to an existing container does not yet apply the metadata (like install extensions). This is tracked as https://github.com/microsoft/vscode-remote-release/issues/7252.

To verify:
- Reopen a folder with the following devcontainer.json in a container:
```json
{
	"image": "mcr.microsoft.com/devcontainers/rust:1",
	"customizations": {
		"vscode": {
			"settings": {
				"rust-analyzer.checkOnSave.command": "check"
			}
		}
	}
}
```
- Verify in the machine settings look like:
```json
{
	"lldb.executable": "/usr/bin/lldb",
	"files.watcherExclude": {
		"**/target/**": true
	},
	"rust-analyzer.checkOnSave.command": "check"
}
```
- Specifically the rust analyzer setting should be "check".
