### ISSUE TITLE
User field does not work

### ISSUE THREAD

**Issue by Hui-Se** [microsoft/vscode-remote-release#7255]
While writing ssh config file like this:
![屏幕截图 2022-09-27 214512](https://user-images.githubusercontent.com/42287812/192544195-69be8e9f-8f40-4a8e-b22e-b80359213f61.png)
![屏幕截图 2022-09-27 214716](https://user-images.githubusercontent.com/42287812/192544225-ae9e860d-b8ce-406c-af0a-fc2c9a46470b.png)
And then connecting with it, it uses my desktop's username:
![屏幕截图 2022-09-27 214835](https://user-images.githubusercontent.com/42287812/192544689-ca63f834-d32a-4d2b-aa27-0ed18096aaef.png)
I have to modify Host to change the login user:
![屏幕截图 2022-09-27 215214](https://user-images.githubusercontent.com/42287812/192545349-8c697ca1-5c6e-4eb7-a871-4a6c75209ec5.png)
It seems like the keyword User has failed.

- Remote SSH Extension version: 0.84.0
- VSCode Version: 1.71.2 (user setup)
- Local OS Version: Windows_NT x64 10.0.22000
- Remote OS Version: Linux version 3.10.0-957.el7.x86_64
- Remote Extension/Connection Type: SSH

**Comment by eleanorjboyd** [comment]
Hello! If you try and doing the `ssh 14.212....` from your terminal does it use the correct user or does it also still use your desktop name? Additionally is this the only entry in your log file? Referencing the same host but different usernames can also cause issues.

**Comment by Hui-Se** [comment]
Sorry to reply late. I use option -p to specify needed port and it works, and I think that is my ssh tool's issue as it cannot resolve hostname with symbol ":port".

**Comment by eleanorjboyd** [comment]
No worries- thanks for getting back to me! We actually have a fix coming soon to allow the ":port" syntax so I'll reach out once it is release to see if it is working for you. Thanks!
