### ISSUE TITLE
Terminal text is stuck blue on Windows terminal/pwsh after build

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-remote-release#7260]
Testing #7248

After the build completes, the terminal prompt text after the command is run is still blue.
![Screenshot showing an example](https://user-images.githubusercontent.com/7199958/192638399-59d8cea3-41b7-4519-86a0-3c848c421bda.png)

**Comment by chrmarti** [comment]
Cannot reproduce with the latest Docker Desktop in the Windows Terminal. This might have been fixed upstream. Let me know if you still see it. Thanks.
