### ISSUE TITLE
Name is just [object Object]

### ISSUE THREAD

**Issue by ssesfahani** [microsoft/vscode-remote-release#7262]
Steps to Reproduce:

1. Go to https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-edit&ssr=false#overview
2. ![image](https://user-images.githubusercontent.com/1325757/192660742-f1c10b0b-5cdc-4969-9b1e-aa8431f6ee1a.png)

Does this issue occur when you try this locally?: Sure
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by azusachino** [comment]
![image](https://user-images.githubusercontent.com/18746830/192677200-77f9c2cd-cbfd-4bf8-b58f-7f3aea5ad2e5.png)

**Comment by u-u-z** [comment]
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/11187239/192677728-bd82a0a5-0b5a-4240-afa8-e646f9287153.png">

**Comment by kands-code** [comment]
![image](https://user-images.githubusercontent.com/59006329/192681508-917ba07f-157a-43a4-866a-0d6dd320c25d.png)

exactly

**Comment by Bitllion** [comment]
hahahahaahhahaha
![7a2aab1878ea8155e465d9dd37af201](https://user-images.githubusercontent.com/39736583/192697589-769b151c-331c-4208-85ae-12b4f135d40d.png)

**Comment by FatsharkGo** [comment]
[锟斤拷 烫烫烫] would be better.  😃

**Comment by spookyuser** [comment]
Honestly this name is a vibe

**Comment by yyt6801** [comment]
I forgot what it was called .  😃 😃 😃

**Comment by Lordxan** [comment]
I was here

**Comment by sihaixianyu** [comment]
That's so hilarious 👎

**Comment by EastMonster** [comment]
I love this name, don't fix it pls

**Comment by roblourens** [comment]
A new release with a fix is on the way :)
