### ISSUE TITLE
Wrong title in marketplace? XD

### ISSUE THREAD

**Issue by JasonBenfrin** [microsoft/vscode-remote-release#7264]
- VSCode Version: 1.71.2
- Local OS Version: Ubuntu 22.04.1

Steps to Reproduce:

1. Search for [object Object] in marketplace

![[object Object]](https://i.imgur.com/FtcH6Tq.png)

![object Object in Web](https://i.imgur.com/PzzNKep.png)

**Comment by joshsleeper** [comment]
dupe of #7262 btw~

**Comment by chrmarti** [comment]
Closing as duplicate. Thanks.
