### ISSUE TITLE
Using $BROWSER to open an html file causes a MS Store pop up to open

### ISSUE THREAD

**Issue by nicber** [microsoft/vscode-remote-release#7270]
I've installed VS Code on Windows 11.
I'm connecting to a Linux VM running CentOS 7.

I open a terminal from VS Code and run:
```
$BROWSER some-file.html
```

I get this pop-up:

![image](https://user-images.githubusercontent.com/3106794/193285193-6be1ab94-8899-4978-9a9b-7dffe087ebf8.png)

**Comment by eleanorjboyd** [comment]
Hello! Can you try using this command, `Simple Browser: Preview` from the command palette and see if this works?

**Comment by nicber** [comment]
Hi!

That command does not exist (VS Code 1.71.2).
I tried `Simple Browser: Show`, but it does not really work.
It always shows a blank page.

**Comment by eleanorjboyd** [comment]
Hello @nicber, could you try using the `live preview` extension? This might give you the functionality you are looking for.

**Comment by nicber** [comment]
Hi, that seems to be working fine.
Thanks!
