### ISSUE TITLE
Open in DevContainer starts background download without any indicator

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-remote-release#7273]
Type: <b>Bug</b>

I had an ipynb open that I wanted to use conda with.

- Ran the command "Reopen in Container"
- Picked the Anaconda container
- Nothing changes in the UI

I know it is downloading as I see the network traffic in the Activity Monitor. Where VS Code shows me progress I can not find, not even logs that I should look at. No notification or status bar update.

After 4min, it did have things ready and re-opened VS Code in the container without warning.

Extension version: 0.254.0
VS Code version: Code - Insiders 1.72.0-insider (2c801254ebf547baaee771b99aa76d202f999622, 2022-09-29T08:07:33.897Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

**Comment by chrmarti** [comment]
That is before the window reloads?

**Comment by chrmarti** [comment]
We pull the image to check its dev container metadata for host requirements. (The metadata is new, so this is a regression.)

I will add a progress notification for when this happens. Once the image is in the local image cache, this will be quick as before.

There are ways to inspect the image in the registory without pulling it, we could look into these in the future:
- regclient tool: https://github.com/regclient/regclient/
- HTTP requests (not sure about authentication): https://medium.com/hackernoon/inspecting-docker-images-without-pulling-them-4de53d34a604

**Comment by chrmarti** [comment]
Also got the direct lookup in the registry working in the CLI. That is much faster and should often times avoid the progress notification. Available in Dev Containers 0.255.1.

**Comment by chrmarti** [comment]
Verification:
- Have a workspace folder with `.devcontainer.json`:
```json
{
	"image": "mcr.microsoft.com/devcontainers/rust:1"
}
```
- Remove all containers and images from Docker (CAREFUL: Make sure you don't need them anymore):
  - Remove all containers: `docker ps -a -q | xargs docker rm -f`
  - Remove all images: `docker system prune --all`
- `Reopen Folder in Container` and verify that the UI either shows a progress notification or reloads and then shows a progress notification.
