### ISSUE TITLE
SLOW when connect to WSL2

### ISSUE THREAD

**Issue by YiHui-Liu** [microsoft/vscode-remote-release#7275]
- VSCode Version: 1.71.2
- Local OS Version: Windows10 21H2 19044.2006
- Remote OS Version: v0.66.3(beta)
- Remote Extension/Connection Type: WSL

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

-------------------
Use `VSCODE_WSL_DEBUG_INFO=true code --verbose .` open vscode in wsl terminal:
<details>
<pre>
+ COMMIT=74b1f979648cc44d385a2286793c226e611f59e7
+ APP_NAME=code
+ QUALITY=stable
+ NAME=Code
+ SERVERDATAFOLDER=.vscode-server
+ realpath /mnt/d/Microsoft/VS Code/bin/code
+ dirname /mnt/d/Microsoft/VS Code/bin/code
+ dirname /mnt/d/Microsoft/VS Code/bin
+ VSCODE_PATH=/mnt/d/Microsoft/VS Code
+ ELECTRON=/mnt/d/Microsoft/VS Code/Code.exe
+ IN_WSL=false
+ [ -n Ubuntu ]
+ IN_WSL=true
+ [ true = true ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID
+ wslpath -m /mnt/d/Microsoft/VS Code/resources/app/out/cli.js
+ CLI=D:/Microsoft/VS Code/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/d/Microsoft/VS Code/Code.exe D:/Microsoft/VS Code/resources/app/out/cli.js --ms-enable-electron-run-as-node --locate-extension ms-vscode-remote.remote-wsl
+ cat /tmp/remote-wsl-loc.txt
+ WSL_EXT_WLOC=c:\Users\fox\.vscode\extensions\ms-vscode-remote.remote-wsl-0.66.3
+ [ -n c:\Users\fox\.vscode\extensions\ms-vscode-remote.remote-wsl-0.66.3 ]
+ wslpath -u c:\Users\fox\.vscode\extensions\ms-vscode-remote.remote-wsl-0.66.3
+ WSL_CODE=/mnt/c/Users/fox/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.3/scripts/wslCode.sh
+ /mnt/c/Users/fox/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.3/scripts/wslCode.sh 74b1f979648cc44d385a2286793c226e611f59e7 stable /mnt/d/Microsoft/VS Code/Code.exe code .vscode-server --verbose .
+ [ -z .vscode-server ]
+ [ .vscode-server = .vscode-insiders ]
+ [ ! -t 0 ]
+ VSCODE_REMOTE_BIN=/home/fox/.vscode-server/bin
+ AUTHORITY=wsl+default
+ [ Ubuntu ]
+ AUTHORITY=wsl+Ubuntu
+ dirname /mnt/c/Users/fox/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.3/scripts/wslCode.sh
+ /mnt/c/Users/fox/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.3/scripts/wslDownload.sh 74b1f979648cc44d385a2286793c226e611f59e7 stable /home/fox/.vscode-server/bin
+ [ ! -d /home/fox/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7 ]
+ RC=0
+ [ 0 -ne 0 ]
+ mktemp /tmp/vscode-distro-env.XXXXXX
+ STORED_ENV=/tmp/vscode-distro-env.6eGx4Y
+ env
+ dirname /mnt/c/Users/fox/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.3/scripts/wslCode.sh
+ VSCODE_CLIENT_COMMAND=/mnt/d/Microsoft/VS Code/Code.exe VSCODE_CLIENT_COMMAND_CWD=/mnt/c/Users/fox/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.3/scripts VSCODE_CLI_AUTHORITY=wsl+Ubuntu VSCODE_CLI_REMOTE_ENV=/tmp/vscode-distro-env.6eGx4Y VSCODE_STDIN_FILE_PATH= WSLENV=VSCODE_CLI_REMOTE_ENV/w:ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID /home/fox/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/bin/remote-cli/code --verbose .
Invoking: cd "/mnt/d/Microsoft/VS Code" && ELECTRON_RUN_AS_NODE=1 "/mnt/d/Microsoft/VS Code/Code.exe" "resources/app/out/cli.js" "--ms-enable-electron-run-as-node" "--verbose" "--folder-uri=vscode-remote://wsl+Ubuntu/home/fox/ComSim" "--remote=wsl+Ubuntu"
</pre>
</details>

Stuck at last output for more than 10min with:

![image](https://user-images.githubusercontent.com/30190271/193410953-bf7a572c-2d65-43bc-ba96-7074012d8d55.png)

Open folder with remote-wsl in vscode, it will take ~1min to save a file or expand a directory in explorer.

-------------------

I have read https://github.com/microsoft/vscode-remote-release/issues/3851, https://github.com/microsoft/vscode-cpptools/issues/5558, https://github.com/microsoft/vscode-remote-release/issues/4461, https://github.com/microsoft/vscode-remote-release/issues/4888.
I'm sure that:
* close VPN (clash for windows)
* close system proxy
* no proxy in Windows environment variables settings
* set connection method to `localhost` ( can not find `remote.WSL.server.connectThroughLocalhost`)
![image](https://user-images.githubusercontent.com/30190271/193411079-042864a1-08f5-4456-9156-094ed2a463a8.png)
* no http proxy in vscode
![image](https://user-images.githubusercontent.com/30190271/193411100-05dcde21-9493-403a-9d4c-28a3d74fc945.png)
* no proxy settings in wsl (.zshrc)

**Comment by bamurtaugh** [comment]
Thanks for reporting. Do you still experience this in the latest VS Code Insiders with the WSL extension?

Are you using a standard Ubuntu distro from the Microsoft store?
