### ISSUE TITLE
Hangs at install script when LocalForward is in use

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#728]
Found by @sbatten 

Repros on any platform...

- Run `ssh myHost` 
- Open VNC Viewer on `localhost:5901`. The host must have a VNC server installed
  - This would probably work with anything that keeps a connection over the forwarded port
- Kill the ssh session so VNC Viewer begins trying to reconnect
- Connect vscode with ssh to myHost
- It hangs at the install script and never continues

We need to prevent the install script from forwarding a port.

**Comment by chrmarti** [comment]
I see that I end up with the LocalForward tunnel established. Maybe this is not about the final state, but about one of the intermediate connections? Please add steps to verify.

**Comment by roblourens** [comment]
Follow the original steps for an ssh config with LocalForward. You should be able to connect successfully without getting stuck while the install script is running, and at the end, the port in LocalForward should be forwarded. It sounds like this is what you saw.
