### ISSUE TITLE
Fetch Features dynamically from `containers.dev` crawled index

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode-remote-release#7280]
Fetch Features in the `Configure Container Features...` UX from index file (visualized at https://containers.dev/features.)

**Comment by bamurtaugh** [comment]
I believe this is in now: 

![image](https://user-images.githubusercontent.com/25310137/198153266-0ef83b19-465e-4c41-b559-5e61745a55f3.png)

Closing, but please reopen if this is asking for something else!
