### ISSUE TITLE
Containers: Fish shell integration path wrong

### ISSUE THREAD

**Issue by max06** [microsoft/vscode-remote-release#7286]
Hello Party-People!

- VSCode Version: 1.71.2
- Local OS Version: Win11 22H2 22621.521
- Remote OS Version:  Debian 11 Bullseye
- Remote Extension/Connection Type: Container

Steps to Reproduce:

1. Open integrated terminal
2. Run `code --locate-shell-integration-path fish`
3. Find wrong filename in output: It should be `shellIntegration.fish` instead of `shellIntegration-fish.fish`

Does this issue occur when you try this locally?: No (works without remote env)

Doesn't hurt as I'm using the fixed path hardcoded in my profile for now, a fix would be great at some point.

**Comment by meganrogge** [comment]
works for me in insider's
![Screen Shot 2022-10-06 at 5 52 07 AM](https://user-images.githubusercontent.com/29464607/194317364-f96036e3-34a8-48f4-8a2b-65669f22936e.png)

**Comment by Tyriar** [comment]
@max06 I think the fix for this is coming in 1.72 which will be released today or tomorrow

**Comment by max06** [comment]
@Tyriar Thank you - I'll test it once it's available and report back 🙇🏼

**Comment by max06** [comment]
This is much better! Thank you very much for this really quick fix 🥳
