### ISSUE TITLE
Where do I find the source code?

### ISSUE THREAD

**Issue by jbrunink** [microsoft/vscode-remote-release#7287]
Hope you're doing well. :-)

Where do I exactly find the source code of this extension? I'd like to make some local changes but I can't find it anywhere. :-(

Thanks in advance!

**Comment by chrmarti** [comment]
We recently published the Dev Container CLI under the MIT license (https://github.com/devcontainers/cli). This CLI is used by the Dev Containers (Remote-Containers is being renamed) extension.

We are tracking issues for the Remote Development extensions for VS Code here. The source code for these is currently not available. Please see https://code.visualstudio.com/docs/remote/faq#_license-and-privacy for more information.
