### ISSUE TITLE
ERROR resolve image config for docker.io/docker/dockerfile:1.4  (since 0.255?)

### ISSUE THREAD

**Issue by KUGA2** [microsoft/vscode-remote-release#7291]
- VSCode Version: 1.7.2
- Local OS Version: 
Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎17.‎03.‎2021
OS build	19044.2006
Experience	Windows Feature Experience Pack 120.2212.4180.0

+ WSL2, Ubuntu 20.04
- Remote OS Version: custom debian container
- Remote Extension/Connection Type: SSH/**Containers**/WSL/Server 0.255
- Logs:

Steps to Reproduce:

0. Be behind a proxy
1. Rebuild and Open in Container

Description:

When opening in devcontainer, VSCode tries to build the Dockerfile. This results in:

`ERROR resolve image config for docker.io/docker/dockerfile:1.4     `

This syntax is not referenced in my Dockerfile.

Reason:
VSCode creates a **temporary Dockerfile** and builds it with buildx (this is new in this version, i guess). Command:
`docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-<user>/container-features/0.19.0-1664968926540/Dockerfile-with-features ...`
If you look into Dockerfile-with-features, you can see it references `# syntax=docker/dockerfile:1.4` in the top line. This file cannot be accessed because of proxy rules.

Workaround:
Install release version (0.251)
Then it does:
`docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /home/<user>/git/<repo>/.devcontainer/Dockerfile`

Potential fix:
Check if user Dockerfile contains the syntax line, then do not add a syntax line to temporary Dockerfile. Users behind proxy need add a reference to a syntax file they can access.

**Comment by chrmarti** [comment]
Tracking as https://github.com/microsoft/vscode-remote-release/issues/6920. Thanks.
