### ISSUE TITLE
SSH Agent Forwarding not working with Remote SSH on Windows 11

### ISSUE THREAD

**Issue by nermin99** [microsoft/vscode-remote-release#7293]
- VSCode Version: 1.71.2
- Local OS Version: Windows 11 Pro 22H2
- Remote OS Version: Fedora 36
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Check that you have `ForwardAgent yes` in `~/.ssh/config`, and that your ssh-agent is running with ``eval `ssh-agent -s` `` and `ssh-add`
2. Check that you can ssh to your server and use your forwarded key, e.g. by pulling a repo - using your local terminal, like cmd and PowerShell (and Git Bash).
3. Now try and ssh to your server using VSCode Remote SSH (which works) and perform the same command which requires your forwarded key.

I then get `git@github.com: Permission denied (publickey)` meaning that my key wasn't forwarded properly.

Does this issue occur when all extensions are disabled?: Yes

---

I'm not entirely sure but it seems like sometimes it works if I first open a terminal in vscode before connecting through Remote SSH, but I can't reproduce it consistently. Also, I'm still not entirely sure if your Default Shell Profile in VSCode makes a difference. Especially having Git Bash as Default Shell Profile might be a problem. But yet again I can't reproduce any results consistently.

The reason why I mention Git Bash is because it's notorious for not automatically running the `ssh-agent` when starting your computer and a new session. However, one can counter this by creating a script in `~/.profile` or `~/.bashrc` which runs `ssh-agent` automatically.
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases  
https://stackoverflow.com/questions/18404272/running-ssh-agent-when-starting-git-bash-on-windows

**Comment by eleanorjboyd** [comment]
Hi! Can you check to see if `echo "$SSH_AUTH_SOCK"` returns anything when you are connected to your remote via the remote-ssh VS Code extension?
