### ISSUE TITLE
Can't open devcontainer when using podman and enabling sandboxing

### ISSUE THREAD

**Issue by maweil** [microsoft/vscode-remote-release#7294]
- VSCode Version: 1.71.2
- Local OS Version: Fedora 36
- Remote OS Version: n/a
- Remote Extension/Connection Type: Containers
- Logs:
  ```txt
  [699318 ms] Remote-Containers 0.251.0 in VS Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7).
  [699316 ms] Start: Run: podman version --format {{.Server.APIVersion}}
  [699375 ms] Stop (59 ms): Run: podman version --format {{.Server.APIVersion}}
  [699376 ms] time="2022-10-05T21:48:16+02:00" level=error msg="running `/usr/bin/newuidmap 30916 0 1000 1 1 100000 65536`: newuidmap: write to uid_map failed: Operation not permitted\n"
  Error: cannot set up namespace using "/usr/bin/newuidmap": exit status 1
  ```

Steps to reproduce:

1. Define the following settings:
```json
{
    "remote.containers.dockerPath": "podman",
    "window.experimental.useSandbox": true
}
```

2. Open any project with a development container configuration (or initialize a new one) in the container

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

#### Description:
When using `podman` instead of docker and while having the `window.experimental.useSandbox` setting enabled, connecting to any devcontainer fails with an error (see screenshot) initially. When trying this after executing any `podman` command in a terminal, the error does no longer occur during the session.

![Screenshot of the error message](https://user-images.githubusercontent.com/16721506/194151197-2e433a73-1c22-4e76-a76b-2665bc05422d.png)

As you can see in the log, the setup of the subnamespace fails internally for podman. As the same command (`podman version --format {{.Server.APIVersion}}`) works fine when executing it in another terminal, it seems be be related to the sandboxing feature of VSCode. 

(I guess that the sandboxing blocks some system calls using `seccomp` that podman needs for setting up the subnamespace. As it works flawlessly after running any podman command outside of VSCode, I assume the creation of the subnamespace is only needed once per user session)

**Comment by chrmarti** [comment]
@deepak1556 Do you know if sandboxing affects permissions on processes spawned from the extension host?

**Comment by deepak1556** [comment]
Extension host will not be affected by sandbox setting, I feel like you are running into the root issue from https://github.com/microsoft/vscode/issues/160380. I don't have podman setup to verify this currently, can you check if the issue persists with our insiders https://code.visualstudio.com/insiders. Thanks!

**Comment by maweil** [comment]
Hi @deepak1556, thanks for clarifying.
I have tried again with the code-insiders package (from <https://packages.microsoft.com/yumrepos/vscode>).
I can confirm that starting the container inside that one works as expected on first try. Sorry for not trying this earlier.

This issue can be closed. I'm looking forward to the next stable release :+1: 

Logs:
```txt
[73 ms] Dev Containers 0.256.0 in VS Code 1.72.0-insider (64bbfbf67ada9953918d72e1df2f4d8e537d340e).
[72 ms] Start: Resolving Remote
[102 ms] Setting up container for folder or workspace: /home/max/git_repo/npm-scope-download-analysis
[106 ms] Start: Check Docker is running
[106 ms] Start: Run: podman version --format {{.Server.APIVersion}}
[660 ms] Server API version: 4.2.1
```
