### ISSUE TITLE
Cannot load container list of remote server

### ISSUE THREAD

**Issue by waylight3** [microsoft/vscode-remote-release#7295]
- VSCode Version: 1.71,2
- Local OS Version: Windows 11
- Remote OS Version: Ubuntu
- Remote Extension/Connection Type: Containers
- Logs:
```
[9963 ms] Remote-Containers 0.251.0 in VS Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7).
[9962 ms] Start: Run: ssh (server-ip) /bin/sh
[9970 ms] Start: Run in host: id -un
[309259 ms] Start: Run: ssh (server-ip) /bin/sh
[309265 ms] Start: Run in host: id -un
```

Steps to Reproduce:
1. Connect remote ssh to the remote server. (it works)
2. On the sidebar, change target from "ssh" to "conatiners", to search docker container list.
3. At this time, it seems blocked after "Run in host: id -un".
I waited at least few hours, but it still not working.
I already updated my local OS and VSCode and tried many reboots.
I also tried remove .ssh file and re-register it.

This is my .ssh config file.
```
Host (server-ip)
  HostName (server-ip)
  User root
```
This is the log after I run "id -un" in my remote server.
```
root
```

**Comment by chrmarti** [comment]
Does running `ssh (server-ip) /bin/sh` in a terminal connect without additional keyboard input? (Like password or passphrase.)

**Comment by sgemaraju** [comment]
> Does running `ssh (server-ip) /bin/sh` in a terminal connect without additional keyboard input? (Like password or passphrase.)

Mine (Windows WSL local & host) asks for password for ssh user@ip. I'm unsuccessful in getting the password prompt to stop.

My `ssh -V` is as follows
----
Host: OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020
Guest: OpenSSH_8.2p1 Ubuntu-4ubuntu0.4, OpenSSL 1.1.1f  31 Mar 2020

My VsCode log
----
```
[63327 ms] Dev Containers 0.255.2 in VS Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e).
[63326 ms] Start: Run: ssh -F C:\Users\sgemaraju\.ssh\config 10.171.147.35 /bin/sh
[63353 ms] Start: Run in host: id -un
```

**Comment by waylight3** [comment]
``ssh -V`` in my vscode terminal (and also in powershell)
```
OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3
```

**Comment by chrmarti** [comment]
@sgemaraju Could you also run `ssh -V` on Windows and post it here? The extension uses the `ssh` binary on Windows.

@waylight3 I think I'm on the latest regular Windows 11 update and have `OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2`. Do you know how you got the more recent version?

**Comment by sgemaraju** [comment]
> @sgemaraju Could you also run `ssh -V` on Windows and post it here? The extension uses the `ssh` binary on Windows.
> 
> @waylight3 I think I'm on the latest regular Windows 11 update and have `OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2`. Do you know how you got the more recent version?

On Guest CMD.exe
```
> ssh -V
OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3
```

On Host CMD.exe
```
> ssh -V
OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3
```

**Comment by martinerk0** [comment]
Had the same problem, ssh extension worked, but couldn't open folder in already running container in remote.
I tried to use ssh keys on remote and it started working, so it probably asks for password and therefore hangs?
My setup was: 
- local Ubutnu 18.04 
- remote Ubuntu 20.04
I think it worked month ago without needing to set up ssh keys, and I think it just asked for password on remote when attaching to container?

**Comment by nursinghoming** [comment]
> Had the same problem, ssh extension worked, but couldn't open folder (attach to container) in already running container in remote. I tried to use ssh keys on remote and it started working, so it probably asks for password and therefore hangs? My setup was:
> 
> * local: Ubutnu 18.04
> * remote :Ubuntu ~20.04~  18.04  (container is 20.04)
>   I think it worked month ago without needing to set up ssh keys, and I think it just asked for password on remote when attaching to container?

have you deal with this problem successfully? how to deal ?
