### ISSUE TITLE
Enable copying files to/from remote workspace

### ISSUE THREAD

**Issue by WSLUser** [microsoft/vscode-remote-release#73]
Though I technically consider this a bug, since this is in preview, I am calling a "feature request". In the blog it says 

> You cannot drag files out of the File Explorer to your local filesystem to copy them.

You can do this with the SSHFS extension, though it does have some limitations in other areas. Please enable this feature so I can test my code to better test and debug for cross-platform compatibility when needed.

**Comment by Chuxel** [comment]
Updating title to be a bit more reflective of the ask since this is equally applicable to remote containers where you wouldn't use SCP/SFTP .

**Comment by bhack** [comment]
@Chuxel Are we considering here also this use case/pipeline https://github.com/microsoft/vscode-remote-release/issues/12#issuecomment-489608015?

**Comment by bhack** [comment]
Also is https://github.com/microsoft/vscode-remote-release/issues/196 a duplicate?

**Comment by Chuxel** [comment]
This is about dragging and dropping in and out of the  VS Code.  #196 is about syncing.  #12 is about Kubernetes.  So, each has separate considerations.

**Comment by bhack** [comment]
I supposed that it could be some common internal design about file transfer for all theese other than dnd UX. But it is closed source so I don't know internals.

**Comment by egamma** [comment]
This is now supported https://github.com/microsoft/vscode-docs/blob/master/remote-release-notes/v1_36.md#drag-and-drop-to-and-from-the-explorer
