### ISSUE TITLE
Support local terminals

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-remote-release#730]
New terminal (local) command was added in https://github.com/microsoft/vscode/commit/6520c22b83c0b6f168ba7de3309ffab42281e905

This issue was forked off from https://github.com/microsoft/vscode-remote-release/issues/168

**Comment by psolyca** [comment]
Did not find it the first time, need to use the Command palette as it is not exposed in the Terminal menu.

Thanks a lot.
