### ISSUE TITLE
Running "Remote-SSH" extension in "Code - OSS" fails to install remote-server

### ISSUE THREAD

**Issue by jackpunt** [microsoft/vscode-remote-release#7302]
Type: <b>Bug</b>

Steps to Reproduce:

1. clone and build vscode, producing Code-OSS
2. Running vscode-oss, install extension "Remote-SSH"
3. try connect to remote host; provoking extension to install remote-server
4. connect to remote works, scp works, but
5. installing remote-server fails
```
[12:17:58.282] > vscode-scp-done.flag                          100%    9     1.9KB/s   00:00    
[12:17:58.543] "Copy server to host" terminal command done
[12:18:00.635] > Found flag and server on host
[12:18:00.642] > 4d1f898c4a21%%2%%
> tar --version:
[12:18:00.645] > bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6
[12:18:02.860] stderr> mv: rename vscode-server-darwin/bin to ./bin: Directory not empty
[12:18:02.860] stderr> mv: rename vscode-server-darwin/extensions to ./extensions: Directory not empty
[12:18:02.860] stderr> mv: rename vscode-server-darwin/node_modules to ./node_modules: Directory not empty
[12:18:02.861] > ERROR: /Users/user/.vscode-server-oss/bin/6a25ae3a24929f35aabf8a051531c0716032e0a0/node or /Users/user/.vscode-server-oss/bin/6a25ae3a24929f35aabf8a051531c0716032e0a0/bin/code-server-insiders don't exist
[12:18:02.861] stderr> mv: rename vscode-server-darwin/out to ./out: Directory not empty
[12:18:02.864] > Already attempted local download, failing
Connecting/installing from 'stock' vscode works.
```

---

My goal is to test/debug to see how my fork interacts with Remote-SSH.
I notice that the extension creates a new window... is that a new instance of vscode?
Is there a way to run the stock vscode but have it create the new/ssh instance running vscode-oss ?

Or: is there a document that explains the how the SSH extension works? What the remote-server does?
[something easier that reverse-engineering from the source code...]

Or: For my current question: what is the URI that is used in the TextEditorModel ?
Is it a simple file://path/file.ext that is interpreted by the remote-server?
or is it like: ssh://host/path/file.ext.ssh ?

---

Extension version: 0.84.0
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:05:37.721Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No
Remote OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 316f3c1c-a36c-4a53-8287-27893e2d0466|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: mac-mini-wifi|
|OS|Darwin x64 19.6.0|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|Memory (System)|8.00GB (4.42GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
vsccc:30566497
pyindex848:30577860
40g7c324:30573242

```

</details>

**Comment by eleanorjboyd** [comment]
Hello! I will try my best to answer the different aspects of your questions but please follow up with anything I missed or additional questions! For the screenshot you send it seems you are attempting to download where a remote server may already exist. I would try the "kill vscode on remote" to see if that might reset your workspace.

> I notice that the extension creates a new window... is that a new instance of vscode?
yes, the extension creates a new window which is no longer the window you are running with your local code. Please use the command "connect current window to host" to be able to test your own code.

> is there a document that explains the how the SSH extension works? What the remote-server does?
This is likely our most in depth doc: https://code.visualstudio.com/docs/remote/ssh, is that the type of information you are looking for? Our troubleshooting doc could also be useful: https://code.visualstudio.com/docs/remote/troubleshooting

> Or: For my current question: what is the URI that is used in the TextEditorModel ?
For issues related to non-remote questions it would likely work best for you to file an issue in our main repo and someone with expertise in that area can respond.

Thanks!!

**Comment by jackpunt** [comment]
Thanks for the info.

>> For my current question: what is the URI that is used in the TextEditorModel ?
>
>For issues related to non-remote questions it would likely work best for you to file an issue in our main repo and someone >with expertise in that area can respond.

To be clear, this the specific question I'm trying to answer about SSH-Remote.
When editing a file using ssh-remote, the TextEditorModel is given a URI to find the file.
I see two possibilities:
1) ssh-remote runs the Editor on the proximal/local machine, using a 'remote' URI (like **ssh:/host/path/to/file**)
2) ssh-remote runs the Editor on the remote machine (sending 'display' info to local machine), so the URI is simple **file:/path/to/file**

If you can confirm that ssh-remote uses (2), then I'll know that nothing special is needed to recognize the file path.
([this question](https://github.com/microsoft/vscode/issues/4873#issuecomment-1262561302) came up in regards the fix for [marking an editor as readonly](https://github.com/microsoft/vscode/pull/161716))

**Comment by eleanorjboyd** [comment]
Hello! So sorry for the delay- yes #2 is correct. Thanks!

**Comment by jackpunt** [comment]
Thanks. 
We can close this out; 
If you know anyone who can help get [PR 161716](https://github.com/microsoft/vscode/pull/161716) moving forward, please ping them.
