### ISSUE TITLE
Please explain which file is the license and which file has transitive closure of dependencies

### ISSUE THREAD

**Issue by dariomx** [microsoft/vscode-remote-release#7304]
Greetings,

My questions below apply to remote - ssh extension:

1. Could you explain which file contains the license, among the ones on this folder?

https://github.com/Microsoft/vscode-remote-release

Not sure if it is LICENSE-extensions, LICENSE-repository or something else.

2. Could you share whether file NOTICE-remote-ssh.txt contains all recursive dependencies, aka, whether is the transitive closure of all dependencies? 

Thank you.

**Comment by dariomx** [comment]
Hi Brigit,

As a reference for this request, I would like to share a similar one I raised for vscode itself (now closed):

https://github.com/microsoft/vscode/issues/161660

Thank you.

**Comment by bamurtaugh** [comment]
Hi @dariomx! The Remote-SSH license is here: https://marketplace.visualstudio.com/items/ms-vscode-remote.remote-ssh/license.

You can see a link to it in the [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) and our [docs](https://code.visualstudio.com/docs/remote/faq#_license-and-privacy).

NOTICE-remote-ssh.txt contains all dependencies Remote-SSH uses.

Closing as I believe this addresses the issue, but let me know if you have other questions. Thanks!

**Comment by dariomx** [comment]
Thank you, Brigit.
