### ISSUE TITLE
Remote Containers downloads docker/dockerfile:1.4

### ISSUE THREAD

**Issue by kingsler** [microsoft/vscode-remote-release#7309]
- VSCode Version: 1.72.0 also tested with insiders
- Local OS Version: Windows
- Remote OS Version: RHEL 7.9
- Remote Extension/Connection Type: SSH/Containers
- Logs: 

When using VSCode Remote Container extension 0.255.2+ on a network that cannot reach out to dockerhub I am unable to create my dev image because the unable to build moby/buildkit image. This was possible on 0.251.0. Buildkit is installed on the ssh machine the build seems to require the container to build. I have not seen any options to modify the build command. The plugin does not seem to use the setting for docker command. This can be an issue in a corporate environment.

Steps to Reproduce:

1. Create devcontainer.json files
2. Remove moby/buildkit and disconnect from the internet
3. Use local image as your image
4. Reopen folder in devcontainer
5. During the image build moby/buildkit is unable to be found

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
Could you append your devcontainer.json and the log from when this fails? (`F1` > `Dev Containers: Show Container Log`)

**Comment by kingsler** [comment]
[remoteContainers-2022-10-11T12-33-23.422Z.log](https://github.com/microsoft/vscode-remote-release/files/9769456/remoteContainers-2022-10-11T12-33-23.422Z.log)

[devcontainer.txt](https://github.com/microsoft/vscode-remote-release/files/9769513/devcontainer.txt)


The devcontainer.json does not matter but I attached an example.

**Comment by chrmarti** [comment]
Can you pull that image while you are connected (with `docker pull docker/dockerfile:1.4`)?

**Comment by kingsler** [comment]
I am in a corporate environment that blocks our connection to dockerhub. So downloading on that network is not possible.
