### ISSUE TITLE
Unable to return to local

### ISSUE THREAD

**Issue by Fourstepper** [microsoft/vscode-remote-release#731]
Issue Type: <b>Bug</b>

1) Install remote extension
2) Start Remote in New Window
3) Create files in WSL directory, work on them in VS Code 
4) Close VS Code
5) Open VS Code, VS Code starts in WSL mode with no (apparent) way to get back to local

Extension version: 0.38.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.84GB (17.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|23.84GB (17.59GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment]
The latest insiders now has a `Close Remote Connection` command in the file menu as well as in the remote menu.

**Comment by Fourstepper** [comment]
> The latest insiders now has a `Close Remote Connection` command in the file menu as well as in the remote menu.

Thank you for the insight!

**Comment by aeschli** [comment]
duplicate of #501
