### ISSUE TITLE
Cannot establish remote connection with `ssh` command but config file works (aws ec2 instance)

### ISSUE THREAD

**Issue by rleyvasal** [microsoft/vscode-remote-release#7310]
Remote connection cannot be made with `ssh` command but config file works - same information is used for both `ssh` and config file command (see screenshots)

- VSCode Version: 1.72
- Local OS Version: Windows 11 22h2
- Remote OS Version: Ubuntu 22.04
- Remote Extension/Connection Type: SSH
- Logs:  
[12:28:16.432] S[12:35:41.635] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2231332e35372e35382e313730222c2275736572223a22737368202d6920433a2f55736572732f452f2e7373682f6177735f6563325f6b6579732e70656d207562756e7475227d", attempt 3, (Reconnection)
[12:35:41.636] SSH Resolver called for host: ssh -i C:/Users/E/.ssh/aws_ec2_keys.pem ubuntu@13.57.58.170
[12:35:41.636] Setting up SSH remote "13.57.58.170"
[12:35:41.638] Using commit id "64bbfbf67ada9953918d72e1df2f4d8e537d340e" and quality "stable" for server
[12:35:41.640] Install and start server if needed

Steps to Reproduce:

1. ctrl+shift+p
2. type remote 
3. select Remote-SSH Connect to Host
4. Enter ssh command 

# SSH command

![ssh command](https://user-images.githubusercontent.com/61335136/194640879-e9b9bc15-12e8-4534-b5ad-2a0529dc8a7b.png)

![asking for remote os](https://user-images.githubusercontent.com/61335136/194640890-5357ac91-f3a1-4986-b94f-2468dd0a7e07.png)

![error message](https://user-images.githubusercontent.com/61335136/194641542-7370020f-10fd-48cc-b20b-3f1569ec4ba5.png)

# Config file creates the connection without issue

![ssh connected with config file](https://user-images.githubusercontent.com/61335136/194641665-e5925349-3838-41fe-b203-e54d9cd9d2cc.png)

Does this issue occur when you try this locally?:  Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by s2071087** [comment]
この問題は、これをローカルで試したときに発生しますか?: はい
これをローカルで試し、すべての拡張機能を無効にすると、この問題が発生しますか?: はい

**Comment by eleanorjboyd** [comment]
Hello! To clarify your config file is set up with the `host: ssh -i C:/Users/E/.ssh/aws_ec2_keys.pem ubuntu@13.57.58.170` right? If it is in your config file you then just have to call the name of the host in the `select Remote-SSH Connect to Host` instead of typing in the whole ssh command again. I am not seeing the host names displayed in the dropdown for `select Remote-SSH Connect to Host` so could you send over a picture your config file as well?

**Comment by rleyvasal** [comment]
![config_file](https://user-images.githubusercontent.com/61335136/195713893-ebf36a92-87c5-4ee8-96dc-912d6f85173d.png)

**Comment by eleanorjboyd** [comment]
Hello! When you call from the command palette `remote ssh: connect to host` is `aws-e2` listed on your dropdown? You can click on this or call `ssh aws-e2` from `remote ssh: connect to host`. Let me know if that works, thanks!

**Comment by rleyvasal** [comment]
Yes, from command palette `remote ssh: connect to host`  and choosing `aws-e2`  in the drop down menu works. However, typing command `ssh -i C:/Users/E/.ssh/aws_ec2_keys.pem ubuntu@13.57.58.170`  on command palette does not work.

**Comment by eleanorjboyd** [comment]
what error do you get from the command palette? Are you typing that ssh string into the input box after you choose `remote ssh: connect to host` or somewhere else? If you could provide a screenshot of where you are attempting this connection string that would be helpful too.

**Comment by rleyvasal** [comment]
# ssh config file
![config ssh](https://user-images.githubusercontent.com/61335136/213928006-30a89f0a-a8cd-401f-9782-9ad80b90c11d.png)

# ssh comand on vscode
![comand ssh](https://user-images.githubusercontent.com/61335136/213928067-1beb7cde-46a8-4827-a418-dabcac0ad03e.png)

# Error message
![ssh error message](https://user-images.githubusercontent.com/61335136/213928047-ce73c224-1dbd-4a7b-91ff-46f33a74905f.png)

**Comment by eleanorjboyd** [comment]
I notice the command you type directly has a different file path, C:/Users/E/.ssh/aws_ec2_keys.pem, if it is the same as the one in your config does it work then?

**Comment by rleyvasal** [comment]
The screenshots show my latest setup. 

  I have changed my client device to linux, and  I have created is a new key  id_ed25519.

SSH connection works well when using the config file as shown in the screenshot **ssh config file**.  above; however when typing the **.ssh comand on vscode** connection cannot be established as shown on the last screenshot **Error message**

**Comment by eleanorjboyd** [comment]
Hello! Upon further investigation this is by design that the extension does not take an SSH command into the input box for connect to host. Would you like me to turn this issue into a feature request to allow that functionality?
