### ISSUE TITLE
devcontainer.json stop functioning properly with docker containers after last VSCode update

### ISSUE THREAD

**Issue by aborealis** [microsoft/vscode-remote-release#7312]
Some directives from devcontainer.json ceased to execute on the docker build. They worked fine before the last VSCode update.

What exactly doesn't work:

1. Extensions are not installed (though they are listed)
```json
"customizations": {
	"vscode": {
		"extensions": [
			"burkeholland.simple-react-snippets",
			"esbenp.prettier-vscode",
			"dbaeumer.vscode-eslint",
			"NuclleaR.vscode-extension-auto-import"
		]
	}
}
```
2. Shutdown actions and post create commands are also ignored:
```json
"shutdownAction": "none",
"postCreateCommand": "python -m pip install -U pytest pytest-django autopep8"
```

VSCode Vesrion - 1.72.0
OS where the issue happens
- Kali Linux
- MacOs
(Both OS are updated)
- Remote connection - docker container

- VSCode Version:
- Local OS Version:
- Remote OS Version:
- Remote Extension/Connection Type: SSH/Containers/WSL/Server
- Logs:

**Comment by mitaroThanken** [comment]
I have the same issue in my environment.
This issue occurs when reopen in a container that is already running.

- VSCode Version: 1.72.0
- Local OS Version: Windows 11 22H2
- Remote OS Version: Ubuntu 20.04.5 LTS (WSL2)
- Remote Extension/Connection: Containers
- Logs: (attached)
[Dev Containers 0.255.2_NG.log](https://github.com/microsoft/vscode-remote-release/files/9739257/Dev.Containers.0.255.2_NG.log)
[Remote-Containers 0.251.0_OK.log](https://github.com/microsoft/vscode-remote-release/files/9739258/Remote-Containers.0.251.0_OK.log)

**Comment by chrmarti** [comment]
Could you append the log from after you rebuild the container, the full devcontainer.json, Dockerfile and docker-compose.yml (if you have these)? If you can't share these, please try to remove all sensitive information and make sure the problem still exists and append this simplified configuration.

(@mitaroThanken The 0.255.2 log seems to be from an existing dev container. Could you rebuild it and append the log from the rebuild?)

**Comment by bakaleks** [comment]
Had same issue here, but solved by "Rebuilding the container"

**Comment by jgadling** [comment]
I'm having the same issue, however when I manually install *any* extension in the container, suddenly the remote extensions see my list of *expected* extensions and installs them all.

**Comment by aborealis** [comment]
> 

Sure, please find the files attached [Archive.zip](https://drive.google.com/file/d/1cQ-ZzxN1zkJdlS3HZlM-Km9l1jsOlzBx/view?usp=sharing)

**Comment by mitaroThanken** [comment]
@chrmarti 
> (@mitaroThanken The 0.255.2 log seems to be from an existing dev container. Could you rebuild it and append the log from the rebuild?)

"Dev Container: Rebuild and Reopen in Container": FAILED
see: #7313 
logs: https://github.com/microsoft/vscode-remote-release/issues/7313#issuecomment-1274038698

all image removed, `docker compose build`, then "Dev Container: Reopen in Container": FAILED
[remoteContainers-2022-10-11T03-51-33.763Z.log](https://github.com/microsoft/vscode-remote-release/files/9750954/remoteContainers-2022-10-11T03-51-33.763Z.log)

**Comment by chrmarti** [comment]
Merging into https://github.com/microsoft/vscode-remote-release/issues/7307. Continuing there. Thanks!

**Comment by chrmarti** [comment]
Added a fix in Dev Containers 0.259.0-pre-release. Could you give that a try and let me know if that fixes it? Thanks.

**Comment by aborealis** [comment]
Yes, it works!

Thanks for fixing it!

**Comment by bakaleks** [comment]
@chrmarti Strange, extensions declared in devcontainer.json are automatically installed in the dev container on RHEL7 host, but not on RHEL8 host. Here is the error message I get from dev-container log on RHEL8 host:
```
[1849 ms] Host server: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[1866 ms] Host server: (node:347634) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(Use `node --trace-warnings ...` to show where the warning was created)
```
When I click on 'Install in Dev Container:..' manually they get installed though, but not automatically when I build the container.

I'm on 0.259.0 pre-release using Remote - SSH + Dev Containers combo
