### ISSUE TITLE
Four extensions that I did not install appear on a remote server when connected with vscode.dev

### ISSUE THREAD

**Issue by eladts** [microsoft/vscode-remote-release#7314]
- VSCode Version: 1.72.0
- Local OS Version: ChromeOS x86_64 15054.86.
- Remote OS Version: Debian GNU/Linux 11.5
- Remote Extension/Connection Type: Server
- Logs:

Steps to Reproduce:

1. Connect to the remote server using vscode.dev.
2. Look at the installed extensions on the server in the primary sidebar.
3. Four extensions show as "Reload Required", even though I never installed them.
![Screenshot 2022-10-08 11 37 58](https://user-images.githubusercontent.com/6475871/194715778-33d042ce-eaff-4908-9dcc-f372f3a91b04.png)
4. Click "Reload Required"
5. Back to step 3.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by eladts** [comment]
This issue does not refer to SSH but rather to VS Code Server (Remote Tunnels).

**Comment by eladts** [comment]
The issue seems to be resolved with VS Code 1.72.1.

**Comment by eleanorjboyd** [comment]
Yes it was fixed in 1.72.1- thanks!
