### ISSUE TITLE
Unable to install the ms-mssql.mssql extension when requested in the devcontainer.json

### ISSUE THREAD

**Issue by MarkKharitonov** [microsoft/vscode-remote-release#7316]
Type: <b>Bug</b>

Unable to install the `ms-mssql.mssql` extension using the `customizations.vscode.extensions` array.

My `devcontainer.json` file is:
```
{
	"name": "Ubuntu",
	"build": {
		"dockerfile": "Dockerfile",
		"args": {
			"VARIANT": "ubuntu-22.04"
		}
	},
	"customizations": {
		"vscode": {
			"extensions": [
				"ms-mssql.mssql"
			]
		}
	},
	"remoteUser": "vscode",
	"features": {},
	"mounts": [
		"source=vscode-ext-mydbproject,target=/home/vscode/.vscode-server/extensions,type=volume"
	]
}
```
My Dockerfile is:
```
ARG VARIANT="jammy"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}

ARG USERNAME=vscode
RUN mkdir -p /home/$USERNAME/.vscode-server/extensions && chown -R $USERNAME.$USERNAME /home/$USERNAME/.vscode-server

COPY dayforce.crt /usr/local/share/ca-certificates
RUN update-ca-certificates
```
The container is created fine, here are the last messages of the Dev Containers log:
```
[9596 ms] Installing extensions...
[9598 ms] [20:33:22] Extension host agent started.
[9719 ms] [20:33:22] ComputeTargetPlatform: linux-x64
[9730 ms] Port forwarding 62779 > 34493 > 34493 stderr: Connection established
[9750 ms] Port forwarding connection from 62783 > 34493 > 34493 in the container.
[9750 ms] Start: Run in Host: docker exec -i -u vscode -e VSCODE_REMOTE_CONTAINERS_SESSION=6bf19fe0-f386-4585-9934-232ba5de35a21665261191786 6bba32084f62b8926308eab54f5b6720cfc417888680b9448321bc217358af75 /home/vscode/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/node -e 
[9755 ms] [20:33:22] [127.0.0.1][5b3b1e6c][ManagementConnection] New connection established.
[10030 ms] Port forwarding 62783 > 34493 > 34493 stderr: Connection established
[10226 ms] [20:33:22] [127.0.0.1][c87979da][ExtensionHostConnection] New connection established.
[10232 ms] [20:33:22] [127.0.0.1][c87979da][ExtensionHostConnection] <267> Launched Extension Host Process.
[259742 ms] Start: Run in container: cat /proc/926/environ
[266557 ms] Start: Run: wsl -d Ubuntu-20.04 -e wslpath -u \\wsl.localhost\Ubuntu-20.04\home\mark\mydbproject
```
And then nothing happens. Browsing through all the logs I stumbled upon this Remote Server log:
```
[2022-10-08 20:33:22.180] [remoteagent] [info] Extension host agent started.
[2022-10-08 20:33:22.298] [remoteagent] [debug] ComputeTargetPlatform: linux-x64
[2022-10-08 20:33:22.334] [remoteagent] [info] [127.0.0.1][5b3b1e6c][ManagementConnection] New connection established.
[2022-10-08 20:33:22.805] [remoteagent] [info] [127.0.0.1][c87979da][ExtensionHostConnection] New connection established.
[2022-10-08 20:33:22.810] [remoteagent] [info] [127.0.0.1][c87979da][ExtensionHostConnection] <267> Launched Extension Host Process.
[2022-10-08 20:33:23.330] [remoteagent] [error] Error: Failed Installing Extensions: ms-mssql.mssql
    at w.installExtensions (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/server/node/server.main.js:88:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
I checked all the other logs and saw no errors. I will happily provide more information - just let me know how to collect it.

When I empty the `customizations.vscode.extensions` array and just install it manually while running in the container then everything works fine. And since I save vscode extensions on a persisted volume I do not need to reinstall it every time. So, there is a workaround, but I am interested very much in understanding what is wrong and how it can be fixed (I assume it is my problem),

Extension version: 0.255.2
VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:39.912Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.76GB (15.38GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu-20.04/home/mark/mydbproject --crash-reporter-id d7143f0e-0d93-4e58-9ab2-8ee6c205c051|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.50GB (13.06GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1:30583747
40g7c324:30573242

```

</details>

**Comment by chrmarti** [comment]
Are you behind a network proxy?

**Comment by MarkKharitonov** [comment]
No, but our corporate network uses ZScaler and so its CA certificates must be configured.
So here is what I know:

**On my WSL console**:
```
mark@L-R910LPKW:~$ devcontainer features info "ghcr.io/devcontainers/features/dotnet:1"
[8172 ms] Failed to get registry auth token with error: Error: unable to get local issuer certificate
[8172 ms] (!) ERR: Failed to publish feature: ghcr.io/devcontainers/features/dotnet
No published versions found for feature 'ghcr.io/devcontainers/features/dotnet:1'
mark@L-R910LPKW:~$
```
Now if I tell node.js to use the CA certificates from openssl (where I have already configured the missing ZScaler CA certificates):
```
mark@L-R910LPKW:~$ export NODE_OPTIONS=--use-openssl-ca
mark@L-R910LPKW:~$ devcontainer features info "ghcr.io/devcontainers/features/dotnet:1"
Published Versions:
   latest
   1
   1.0
   1.0.0
   1.0.1
   1.0.2
   1.0.3
   1.0.4
   1.0.5
   1.0.6
mark@L-R910LPKW:~$
```
Now back to the dev container. The new version is:
```
ARG VARIANT="jammy"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}

ARG USERNAME=vscode
RUN mkdir -p /home/$USERNAME/.vscode-server/extensions && chown -R $USERNAME.$USERNAME /home/$USERNAME/.vscode-server

COPY *.crt /usr/local/share/ca-certificates
RUN update-ca-certificates
ENV NODE_OPTIONS=--use-openssl-ca
```
I also added this to the `devcontainer.json`:
```
"remoteEnv": {
  "NODE_OPTIONS": "--use-openssl-ca"
},
```
But it has no effect. When I rerun I am still getting the **Failed to get registry auth token with error: Error: unable to get local issuer certificate** message.

So that is the current state of affairs.

**Comment by MarkKharitonov** [comment]
I am starting VS Code from the WSL console:
![image](https://user-images.githubusercontent.com/489792/194931771-5cef5887-613e-4008-9724-9900f5315be5.png)

On the console I have the `NODE_OPTIONS` environment variable set to `--use-openssl-ca`, but when I inspect the `code` process environment with the Process Monitor `NODE_OPTIONS` is not there. I tried with notepad++.exe and cmd.exe and they do not show this environment variable either. But opening a new `bash` instance does show it. I do not know what to make out of it yet,

**Comment by MarkKharitonov** [comment]
Found this post - https://stackoverflow.com/questions/60422936/how-do-you-pass-an-environment-variable-from-wsl-into-windows-executable

Now I am able to see the `NODE_OPTIONS`, but the value is empty. Continue to investigate ...

**Comment by chrmarti** [comment]
If you open a WSL folder in a dev container, we run the dev container CLI in WSL and we probe the shell environment variables in WSL. Could you try setting `NODE_OPTIONS` in your `.bashrc` (or `.bash_profile`/`.profile`) and retry? If that doesn't work, please append the full log with Dev Containers log level set to "trace" in VS Code's user settings.

**Comment by MarkKharitonov** [comment]
NODE_OPTIONS does not propagate within VS Code - https://github.com/microsoft/vscode/issues/164090
