### ISSUE TITLE
dotfile clone from azure devops repo: "fatal: Cannot determine the organization name..."

### ISSUE THREAD

**Issue by zvilius** [microsoft/vscode-remote-release#7317]
- VSCode Version: 1.72.0
- Local OS Version: Ubuntu 22.04
- Remote OS Version: Ubuntu 22.04
- Remote Extension/Connection Type: Docker container running locally
- Logs:
[container_log.txt](https://github.com/microsoft/vscode-remote-release/files/9741828/container_log.txt)

I am trying to use the feature of VSCode Remote-Containers that automatically **clones a dotfile repo** into the container when the container is created. My dotfile repo is hosted on Azure Devops (dev.azure.com).

I receive the following error message in the Dev Containers log:
> fatal: Cannot determine the organization name for this 'dev.azure.com' remote URL. Ensure the credential.useHttpPath configuration value is set, or set the organization name as the user in the remote URL '{org}@dev.azure.com'.

My VSCode user-level settings.json has:
`"dotfiles.repository": "https://zest-computing@dev.azure.com/zest-computing/Common/_git/dotfiles"
`

When the container is running, I can manually clone the repo in the container using the VSCode bash terminal:

> vscode ➜ ~/xfer $ git clone https://zest-computing@dev.azure.com/zest-computing/Common/_git/dotfiles
> Cloning into 'dotfiles'...
> remote: Azure Repos
> remote: Found 19 objects to send. (175 ms)
> Unpacking objects: 100% (19/19), 5.65 KiB | 304.00 KiB/s, done.

The container is based on a stock C++ dev container from Microsoft: 
https://github.com/microsoft/vscode-dev-containers/tree/v0.187.0/containers/cpp/.devcontainer/base.Dockerfile
... with minimal modifications.

Otherwise the containerized development environment works, including using Azure Devops-based repos for source control.

Does this issue occur when you try this locally?: No

**Comment by zvilius** [comment]
I still have this problem. Has there been any diagnosis? Workaround?

**Comment by chrmarti** [comment]
Does adding the following to the Dockerfile make it work?
```Dockerfile
RUN git config --system credential.https://dev.azure.com.useHttpPath true
```

**Comment by zvilius** [comment]
I added the line to my Dockerfile, but the problem is unchanged.
Here are snippets from the Dev Containers log for the build: (the first line shows the added line)

> ...
>  => [dev_container_auto_added_stage_label 5/7] RUN git config --system cr  0.3s
> ...
> [253576 ms] fatal: Cannot determine the organization name for this 'dev.azure.com' remote URL. Ensure the `credential.useHttpPath` configuration value is set, or set the organization name as the user in the remote URL '{org}@dev.azure.com'.
> fatal: could not read Password for 'https://zest-computing@dev.azure.com': terminal prompts disabled
> [253579 ms] fatal: could not read Password for 'https://zest-computing@dev.azure.com': No such device or address
>

**Comment by zvilius** [comment]
As a workaround, I tried copying my dotfiles repo to GitHub.
I changed the line in my VSCode user-level settings.json to:
`"dotfiles.repository": "zvilius/dotfiles",`

With this approach it successfully clones the repo into ~/dotfiles in the container, but then I get the following in the log:
```
[362520 ms] Setting current directory to ~/dotfiles
Could not locate ~/dotfiles/install.sh...

```
But when I look at ~/dotfiles in a bash shell (running in the container) I see install.sh is there. For example:
```
vscode ➜ ~/dotfiles (main) $ ll
total 32
drwxr-xr-x 3 vscode vscode 4096 Aug 14 20:27 ./
drwxr-x--- 1 vscode vscode 4096 Aug 14 20:27 ../
-rw-r--r-- 1 vscode vscode 5443 Aug 14 20:27 .bashrc
-rw-r--r-- 1 vscode vscode 3329 Aug 14 20:27 .clang-format
drwxr-xr-x 8 vscode vscode 4096 Aug 14 20:27 .git/
-rw-r--r-- 1 vscode vscode   23 Aug 14 20:27 .gitignore
-rwxr-xr-x 1 vscode vscode  131 Aug 14 20:27 install.sh*
```
If this should be reported as a separate bug, I'll be happy to.

**Comment by chrmarti** [comment]
> If this should be reported as a separate bug, I'll be happy to.

Yes please, thanks!

**Comment by chrmarti** [comment]
This works for me with `https://monacotools@dev.azure.com/monacotools/Monaco/_git/chrmarti-test`. It seems to use the username before the @ as the project name and looks up the password in the local Git's credential store.

**Comment by chrmarti** [comment]
You're right, the username before the @ is the organization name. We pass the entire URL to `git`, the same way you pass it when you run the `git clone` from a terminal, so wouldn't expect the hyphen to be an issue. Can you confirm that it works from a local terminal and a terminal in the container with that full URL? Does your local `~/.gitconfig` contain the `useHttpPath` config?

**Comment by zvilius** [comment]
I confirm that the URL works both directly from the local machine and from a terminal (bash shell) on the dev container:

From local machine:

```
mark ➜ ~/xfer $ git clone https://zest-computing@dev.azure.com/zest-computing/Common/_git/dotfiles
Cloning into 'dotfiles'...
remote: Azure Repos
remote: Found 19 objects to send. (82 ms)
Unpacking objects: 100% (19/19), 5.65 KiB | 1.88 MiB/s, done.
```
From container (bash terminal in VSCode):

```
vscode ➜ ~/xfer $ git clone https://zest-computing@dev.azure.com/zest-computing/Common/_git/dotfiles
Cloning into 'dotfiles'...
remote: Azure Repos
remote: Found 19 objects to send. (77 ms)
Unpacking objects: 100% (19/19), 5.65 KiB | 1.13 MiB/s, done.
```

My local `~/.gitconfig` is:
```
mark ➜ ~ $ cat .gitconfig
[user]
	name = Mark Zvilius
	email = mark.zvilius@zest-computing.com
[init]
	defaultBranch = main

[credential]
	helper = /usr/local/share/gcm-core/git-credential-manager-core
	credentialStore = gpg
[credential "https://dev.azure.com"]
	useHttpPath = true
```
