### ISSUE TITLE
Dockerfile frontend declaration removed in docker-compose setup

### ISSUE THREAD

**Issue by oinopion** [microsoft/vscode-remote-release#7318]
VS Code Dev Containers version v0.255.2 introduced an issue with dev containers setup using docker compose: the generation of `Dockerfile-with-features` removes [Docker frontend declaration](https://docs.docker.com/develop/develop-images/build_enhancements/#overriding-default-frontends) (eg. `# syntax=docker/dockerfile:1.2`). 

Note that this only happens with docker compose; switching to simple Dockerfile setup works correctly.

I've created a minimal example repo that reproduces the issue: [oinopion/devcontainer-frontend-issue](https://github.com/oinopion/devcontainer-frontend-issue). It includes the [Dockerfile-with-features](https://github.com/oinopion/devcontainer-frontend-issue/blob/main/logs/Dockerfile-with-features) that has been generated and [logs from a failed container creation run](https://github.com/oinopion/devcontainer-frontend-issue/blob/main/logs/remoteContainers-2022-10-10T10-27-50.611Z.log).

VS Code info:
```
Version: 1.72.0
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:19:55.212Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
```

- VSCode Version: 1.72.0
- Local OS Version: macOS Monterey 12.6
- Local chip architecture: Apple M1
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: any with docker-compose
- Dev Containers versions affected: v0.256.0 & v0.255.2 (works in v0.251.0)

Steps to Reproduce:
1. Clone the repository
2. Open the repository in container
3. The build fails as the Dockerfile syntax is unsupported by the default Docker frontend (`dockerfile.v0`)

**Comment by chrmarti** [comment]
Tracking as https://github.com/microsoft/vscode-remote-release/issues/6848. Please see https://github.com/microsoft/vscode-remote-release/issues/6848#issuecomment-1273459194 and give 0.258.0-pre-release a try. Thanks.

**Comment by oinopion** [comment]
The pre-release version seems to have fixed it for me, thanks!

**Comment by sylver** [comment]
@chrmarti still having the issue on `0.262.3` and `0.263.0`, please see #7463
