### ISSUE TITLE
Docker UI extension not activated when defined as an extension in devcontainer.json

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#732]
- clone the following project https://gitlab.com/billgrant/dev_container_example
- open it in a dev container

Notice that the docker extension is added as an extension to be installed in the devcontainer.json. However, by default the docker extension is a UI extension.

In this setup what happens is that the docker extension is not activated. See the screenshot from the extensions viewlet.

![image](https://user-images.githubusercontent.com/172399/59762605-e3bc5b80-9297-11e9-842f-a55fb9e63899.png)

I would have expected that the Docker extension gets activated since it is defined to be a UI extension.

**Comment by sandy081** [comment]
This is because the extension host is started before configuration is completely loaded.

**Comment by sandy081** [comment]
I think this is no longer valid as docker extension is now multi kind. I would probably get back to this if there is a valid scenario.
