### ISSUE TITLE
containers.attachToRunningContainerFromViewlet 错误: Shell server terminated (code: 255, signal: null)

### ISSUE THREAD

**Issue by xihongshi153** [microsoft/vscode-remote-release#7322]
- VSCode Version: 1.70
- Local OS Version:Windows 10
- Remote OS Version: Centos 7
- Remote Extension/Connection Type: SSH/Containers/WSL/Server
- Logs:containers.attachToRunningContainerFromViewlet 错误: Shell server terminated (code: 255, signal: null)

Steps to Reproduce:

When  i want to attach VScode ,this occur.I want to attach the docker. 
运行命令 remote-containers.attachToRunningContainerFromViewlet 错误: Shell server terminated (code: 255, signal: null) CreateProcessW failed error:2 ssh_askpass: posix_spawnp: No such file or directory Permission denied, please try again. CreateProcessW failed error:2 ssh_askpass: posix_spawnp: No such file or directory Permission denied, please try again. CreateProcessW failed error:2 ssh_askpass: posix_spawnp: No such file or directory root@120.46.208.103: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password). 。这可能是由提交 remote-containers.attachToRunningContainerFromViewlet 的扩展引起的。

**Comment by chrmarti** [comment]
Could you also attach the dev container log after this occurs? (`F1` > `Dev Containers: Show Container Log`)

**Comment by nursinghoming** [comment]
> * VSCode Version: 1.70
> * Local OS Version:Windows 10
> * Remote OS Version: Centos 7
> * Remote Extension/Connection Type: SSH/Containers/WSL/Server
> * Logs:containers.attachToRunningContainerFromViewlet 错误: Shell server terminated (code: 255, signal: null)
> 
> Steps to Reproduce:
> 
> When i want to attach VScode ,this occur.I want to attach the docker. 运行命令 remote-containers.attachToRunningContainerFromViewlet 错误: Shell server terminated (code: 255, signal: null) CreateProcessW failed error:2 ssh_askpass: posix_spawnp: No such file or directory Permission denied, please try again. CreateProcessW failed error:2 ssh_askpass: posix_spawnp: No such file or directory Permission denied, please try again. CreateProcessW failed error:2 ssh_askpass: posix_spawnp: No such file or directory root@120.46.208.103: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password). 。这可能是由提交 remote-containers.attachToRunningContainerFromViewlet 的扩展引起的。

do you deal with this problem successfully? I met the same issue and dont know how to deal with, please help

**Comment by nursinghoming** [comment]
[26130 ms] Dev Containers 0.259.0 in VS Code 1.72.1 (129500ee4c8ab7263461ffe327268ba56b9f210d).
[26129 ms] Start: Run: ssh zk /bin/sh
[26150 ms] Start: Run in host: id -un

**Comment by nursinghoming** [comment]
> Could you also attach the dev container log after this occurs? (`F1` > `Dev Containers: Show Container Log`)

[26130 ms] Dev Containers 0.259.0 in VS Code 1.72.1 (129500ee4c8ab7263461ffe327268ba56b9f210d).
[26129 ms] Start: Run: ssh zk /bin/sh
[26150 ms] Start: Run in host: id -un

**Comment by chrmarti** [comment]
Could you run `ssh -V` and post the output here?

**Comment by nursinghoming** [comment]
> Could you run `ssh -V` and post the output here?

远程centos7上ssh -V 
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
