### ISSUE TITLE
Could not fetch remote environment Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)

### ISSUE THREAD

**Issue by shfguan** [microsoft/vscode-remote-release#7325]
Could not fetch remote environment
Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)

I tried versions 1.69.2 and 1.72.0, and the remote connection to the server prompts the above error. It is useless to delete .vscode-server. I have tried various methods, but it does not work. It took a lot of time and troubled me for a long time. ,it used to be works fine , but suddenly it doesn't work. Is it caused by an automatic update of a certain version? Please help, thank you very much

vscode  infomation: 
Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: [10.0.139.17-electron.0]
OS: Windows_NT x64 10.0.18363

![image](https://user-images.githubusercontent.com/25581121/195099703-d6e3c2d9-9eb9-4071-8496-7a99b9a9a79f.png)

**Comment by eleanorjboyd** [comment]
Hello! Could you please provide the entire remote-ssh logs? The whole logs includes some settings which are helpful to the debugging process. Feel free to remove any confidential information as you see fit but the logs are most helpful when they are verbose so include as much as possible. Thanks!
