### ISSUE TITLE
Ability to switch user and open expore files in his directory

### ISSUE THREAD

**Issue by Varun-garg** [microsoft/vscode-remote-release#733]
Issue Type: <b>Feature Request</b>

It would be great if there was an ability to switch user and open expore files in his directory. Example there is another user, that I have to go to by using `sudo su - <user>` and access the files in his home directory that cannot be accessed through mine.

Extension version: 0.42.2
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 3.10.34-39.137.amzn1.x86_64

**Comment by bamurtaugh** [comment]
Hey there, thanks for opening this feature request! From what I can tell, this is https://github.com/microsoft/vscode-remote-release/issues/690, so closing in favor of that one. If I'm mistaken, please just let me know, and happy to discuss further.
