### ISSUE TITLE
Can't install release version of 'ms-vscode.remote-explorer' extension because it has no release version

### ISSUE THREAD

**Issue by acohenOT** [microsoft/vscode-remote-release#7330]
- VSCode Version: 1.72.1
- Local OS Version: Windows 11 Pro 22H2
- Remote OS Version: N/A
- Remote Extension/Connection Type: N/A
- Logs: 
[14:20:43.216] Log Level: 2
[14:20:43.218] remote-ssh@0.84.0
[14:20:43.218] win32 x64

Steps to Reproduce:

I'm not sure exactly, but I noticed it started after updating from VS Code 1.72 to 1.72.1
1. Open Extensions tab
2. Click Update on Remote - SSH extension

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/34688558/195170247-b32c962b-dbf8-4a2c-808e-ac89db53eceb.png)

**Comment by philipdowner** [comment]
I can confirm that this also fails on MacOS when installing the extension for the first time.

**Comment by daniannr** [comment]
Tried installing it on VSCode 1.72.0 on MacOS, also had same issue

**Comment by keenranger** [comment]
Windows 1.72.1, same problem

**Comment by DebankurS** [comment]
Any other extensions dependent on this are also failing including Remote - SSH

**Comment by roblourens** [comment]
Apologies - fix incoming

**Comment by alexr00** [comment]
I still get this when I tree to install the release version with VS Code insiders:

![image](https://user-images.githubusercontent.com/38270282/198093276-ee1d1f4b-a2db-498b-a14a-934fbe4cdc67.png)

**Comment by roblourens** [comment]
The remote-explorer stable version is still not published (working on it) but it's not expected that anybody installs that extension on its own. The only fix was was unblocking installing the ssh extension.
