### ISSUE TITLE
using ssh with proxychains

### ISSUE THREAD

**Issue by 0x00-pl** [microsoft/vscode-remote-release#7333]
i set `remote.ssh: Path` to `proxychains -q ssh`
but got this error:
```
 Checking ssh with "proxychains -q ssh -V"
 Got error from ssh: spawn proxychains -q ssh ENOENT
```
how can i use proxychains with ssh in vscode?

**Comment by eleanorjboyd** [comment]
the `remote.ssh: Path` is supposed to point to a binary that we can spawn. We can point at a script that runs the ssh command you are trying to execute but the `remote.ssh: Path` needs to be runnable.
