### ISSUE TITLE
Open a folder on a remote Windows SSH host in a container

### ISSUE THREAD

**Issue by ULudo** [microsoft/vscode-remote-release#7343]
I'm using VSCode on MacOS and want to develop in a docker container running on a remote Windows OS. I can connect to the workspace on the Windows machine via SSH from my MacBook.

When I'm connected to the remote Windows machine via SSH in VSCode and execute "Remote-Containers: Add Development Container Configuration Files..." I get following error: 

_Command 'Remote-Containers: Add Development Container Configuration Files...' resulted in an error ([UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character)_

When I try to reopen a folder in a container, using the command "Remote-Containers: Reopen Folder in Container ", with a existing devcontainer configuration, I get following error:

_Command 'Remote-Containers: Reopen in Container' resulted in an error (Shell server terminated (code: 1, signal: null)
The system cannot find the path specified.)_

.devcontainer/devcontainer.json:
```
{
	"name": "Ubuntu",
	"build": {
		"dockerfile": "Dockerfile",
		"args": { "VARIANT": "ubuntu-20.04" }
	},
	"remoteUser": "vscode",
	"features": {
		"git": "latest",
		"git-lfs": "latest",
		"python": "3.10"
	}
}
```

.devcontainer/Dockerfile:
```
ARG VARIANT="jammy"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}
```

- VSCode Version: 1.71.2
- Local OS Version: macOS Monterey Version 12.6
- Local chip architecture: Apple Silicon M1

Executing "Remote-Containers: Reopen Folder in Container " in VSCode on the Windows-Host works fine.

**Comment by chrmarti** [comment]
Tracking as https://github.com/microsoft/vscode-remote-release/issues/6055. Thanks.
