### ISSUE TITLE
"An error occurred setting up the container" when docker context is non-default

### ISSUE THREAD

**Issue by pamelafox** [microsoft/vscode-remote-release#7348]
- VSCode Version: 1.72.1 (Universal)
- Local OS Version: Mac OS X 12.6
- Remote OS Version: Python 3.10 Dockerfile (whatever OS that has)
- Remote Extension/Connection Type: Containers

Steps to Reproduce:

1. Create a docker context for Azure Container Instances (https://docs.docker.com/cloud/aci-integration/)
2. Open a project in VS Code that requires a devcontainer
3. See "An error occurred setting up the container"
4. Set docker context based to default local moby context
5. Restart VS Code and open project
6. See devcontainer open successfully.

Unfortunately, I didn't grab the logs when #3 happened, but I know that once I figured out #4, it stopped error'ing. I haven't managed to replicate it by switching back to the ACI docker context, so I don't know why it's inconsistently a problem to have the non-default context, but I thought I'd make the report anyways in case it's useful.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: I didn't try disabling extensions

**Comment by chrmarti** [comment]
Tracking as https://github.com/microsoft/vscode-remote-release/issues/88. Thanks.

**Comment by pamelafox** [comment]
I think this is slightly different, as I had no intention of using a different docker context- I forgot that I'd been experimenting with docker contexts and didn't even realize that would affect devcontainer. It'd be great if it had just said "Try switching contexts". But maybe formally supporting contexts as described in #88 would help users who accidentally were in a non-default context like me. Thanks!
