### ISSUE TITLE
I couldn't open dev container in remote ssh

### ISSUE THREAD

**Issue by hugosim97** [microsoft/vscode-remote-release#7350]
- VSCode Version: 1.72.1 129500ee4c8ab7263461ffe327268ba56b9f210d x64
- Local OS Version: Windows 10.0.19042 N/A Builds 19042
- Remote OS Version: Ubuntu 22.04.1 LTS
- Remote Extension/Connection Type: SSH: v0.90.1/Containers: v0.259.0
- Logs:
```
[42 ms] Dev Containers 0.259.0 in VS Code 1.72.1 (129500ee4c8ab7263461ffe327268ba56b9f210d).
[41 ms] Start: Resolving Remote
[55 ms] Start: Check Docker is running
[55 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[180 ms] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

[183 ms] Docker returned an error code 1, message: Command failed: docker version --format {{.Server.APIVersion}}
```
Steps to Reproduce:

1. Connect remote ssh
2. Create dev continaer with  `Clone Repository in Container Volume` command in remote ssh. (ps. I selected docker from docker option)
3. New dev container vscode window is opend automatically, It's working well yet.
4. And Close the dev container vscode window
5. I can't open this dev container using dev container extension in remote
6. But, There were one of wey to open dev cotainer. It was just to use recent open menu...

So I compared recent opened path with dev container path of extension
![image](https://user-images.githubusercontent.com/109582083/195495821-1fd16d81-024d-447d-b3a0-e13f6a232166.png)
![image](https://user-images.githubusercontent.com/109582083/195496024-c06c75ad-892c-4a6b-8a01-73041ee994ae.png)

It was different like that..
```
vscode-remote://dev-container+7b227265706f7369746f727950617468223a2268747470733a2f2f6769746875622e636f6d2f7a696762616e672f6269676c61622d6d6f6e69746f722e6769742f747265652f6d6173746572222c22766f6c756d654e616d65223a225f5f554e49515545~~~~d/workspaces/repo
```
```
vscode-remote://dev-container+7b227265706f7369746f727950617468223a2268747470733a2f2f6769746875622e636f6d2f7a696762616e672f6269676c61622d6d6f6e69746f722e6769742f747265652f6d6173746572222c22766f6c756d654e616d65223a226269676c61622d6~~~~d/workspaces/repo
```

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
Is it still shown in the Remote-Explorer viewlet?

The URIs you post seem to have a truncated authority. Did you remove sensitive information there or are these the actual URIs?

**Comment by hugosim97** [comment]
@chrmarti I removed some text.
It is still shown dev container in remote explorer

There are full text urls
- It's working url
TITLE: repo [Dev Container: Node.js @ ssh://sshurl]
URL:
```
vscode-remote://dev-container+7b227265706f7369746f727950617468223a2268747470733a2f2f6769746875622e636f6d2f7a696762616e672f6269676c61622d6d6f6e69746f722e6769742f747265652f6d6173746572222c22766f6c756d654e616d65223a225f5f554e495155455f5f222c22666f6c646572223a226269676c61622d6d6f6e69746f72222c2273657474696e6773223a7b22686f7374223a227373683a2f2f5a422d4875676f2d454332227d2c22636c6f6e65496e666f223a7b2275726c546f436c6f6e65223a2268747470733a2f2f6769746875622e636f6d2f7a696762616e672f6269676c61622d6d6f6e69746f722e676974222c22726566223a226d6173746572227d2c22696e7370656374566f6c756d65223a66616c73657d/workspaces/repo
```
- It's not working url
TITLE: repo [Dev Container]
URL:
```
vscode-remote://dev-container+7b227265706f7369746f727950617468223a2268747470733a2f2f6769746875622e636f6d2f7a696762616e672f6269676c61622d6d6f6e69746f722e6769742f747265652f6d6173746572222c22766f6c756d654e616d65223a226269676c61622d6d6f6e69746f722d6d61737465722d6531666234623263316266373832633534363631333363373961343434646233222c22666f6c646572223a226269676c61622d6d6f6e69746f72222c22696e7370656374566f6c756d65223a66616c73657d/workspaces/biglab-monitor
```
