### ISSUE TITLE
Why don't you add 'install locally' option in the installer shell script

### ISSUE THREAD

**Issue by physmlee** [microsoft/vscode-remote-release#7351]
I am a physics researcher, and I am sharing a computing server (linux) with many collegues.

As the server is not mine, I could not install the code-server via the 'quick install' guide because I don't have sudo permission.

Actually, it was not that hard to install locally.
Changing the installation path and deleting sudo-related parts from the shell script solved the problem.

So, for those who like me, why don't you ask where to install? (like local or global)

**Comment by eleanorjboyd** [comment]
Hello! To clarify are you trying to ssh to a computer server and use VS Code on that server? Also can you link the quick install guide you are using?

**Comment by physmlee** [comment]
Usually, I open the VS Code on my own computer and use Remote-SSH to connect to that server.

This time, I installed the VS Code Server preview on that server, ran the `code-server`, and connected through an internet browser on any device.

The quick install guide was...
https://code.visualstudio.com/docs/remote/vscode-server#_quick-start

**Comment by eleanorjboyd** [comment]
Understood- so at what point in the process are you stuck? Were you able to connect to the VS Code on your server?

**Comment by physmlee** [comment]
I'm not stucked!
I'm just suggesting to add 'install locally' option in the vs code-server installer.
I believe it would help many people who are using a server with many collegues.

**Comment by eleanorjboyd** [comment]
Have you looked into the setting `Remote.SSH: Local Server Download`? This allows you to set whether the extension should download the VS Code Server on the client and transfer it to the host with scp, instead of downloading it on the host.

**Comment by physmlee** [comment]
Well, there's no problem with `Remote-SSH`. There were no permission issues with it. (`Remote.SSH: Local Server Download` was set as `auto`)

But this time, I wanted to use the `code-server` preview version because it looked so convenient on a tablet.

And while installing the `code-server` preview, the [installer](https://aka.ms/install-vscode-server/setup.sh) (for linux) tried to achieve the `sudo` permission.

As the server is not my own device, I had to edit the installer script so that it installs in my local directory, without any `sudo` permission.

So, my suggestion is to add a line in the installer script to ask "install locally (without sudo) or globally".

I think it can be helpful for people like me (sharing a server with many people). If you don't agree with my suggestion, you can skip this issue as well :)

**Comment by eleanorjboyd** [comment]
Hello @physmlee we believe that this issue is currently out of scope. If you do find any issues in the VS Code repo regarding this request feel free to upvote them to demonstrate interest but otherwise we unable to commit to putting this feature request on our timeline right now.
