### ISSUE TITLE
Create terminal only when requested

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-remote-release#736]
https://github.com/microsoft/vscode/pull/75290

There's a new terminal option that can completely hide the terminal from the user, for ssh that means all the setup/connection stuff can happen only in output and notifications unless the user clicks for more detail. For containers the same could be true where the terminal that sets up the container is only shown when requested

**Comment by chrmarti** [comment]
@Tyriar Are there any plans to bring this to TerminalRenderer?

**Comment by Tyriar** [comment]
@chrmarti if you're using a terminal renderer you don't need it do you, you can just cache the data you've received and delay the creation of the terminal renderer?

We could add it to https://github.com/microsoft/vscode/issues/70978 if it made sense to but the above solution is probably better as it would involve less work and memory.

**Comment by chrmarti** [comment]
Makes sense, I'll look into doing that. Thanks.
