### ISSUE TITLE
Fork(pty3) error when starting a terminal in Remote-SSH

### ISSUE THREAD

**Issue by PipeItToDevNull** [microsoft/vscode-remote-release#7367]
- VSCode Version: 1.67.2
- Local OS Version: Windows 10 1607 LTS
- Remote OS Version: RHEL7
- Remote Extension/Connection Type: SSH
- Logs: "The terminal process failed to launch: A native exception occurred during launch (fork(pty3) failed.)."

Steps to Reproduce:

1. Connect to a host via SSH
2. Launch a terminal in VSC

I cannot reproduce this issue on a similar RHEL8 box where all configurations (SSHD etc) and `/dev/pt*` permissions are the same

**Comment by PipeItToDevNull** [comment]
The fixes here do not resolve the issue https://github.com/microsoft/vscode-remote-release/issues/4233

1. Renaming `~/.vscode-server` does not resolve it
2. Changing permissions of various `/dev/` files: They match the working box already

**Comment by eleanorjboyd** [comment]
Hello! Could you please provide the remote-ssh logs? You can find them through going to the `terminal` on your server side vscode window then selecting the tab `output` then select `remote-ssh` from the dropdown. Feel free to remove any confidential information as you see fit but the logs are most helpful when they are verbose so include as much as possible. Thanks!

**Comment by PipeItToDevNull** [comment]
Hello,

There is no vscode installed on the server side, only the vscode-server directory required for this connection. On the client the "Remote Server" logs only contain "Connection Established" 

The "Remote-SSH" log only contains "[Forwarding server 50205] [Got Connection 2]"

**Comment by eleanorjboyd** [comment]
So to clarify the remote-ssh logs on the remote vscode window which is connected only has the logs "[Forwarding server 50205] [Got Connection 2]" but you connection is established? There are no other error messages or other completion messages sent?

**Comment by PipeItToDevNull** [comment]
I have SSH logs for the connection being established, but no matter how many times I open a terminal to its failure message, no additional logs are generated

**Comment by PipeItToDevNull** [comment]
It is an issue larger than Remote-SSH is what I have found 

https://github.com/microsoft/vscode/issues/165712

**Comment by PipeItToDevNull** [comment]
I was able to finally resolve this by changing the mount permissions of `/dev/pts`

https://www.linuxquestions.org/questions/linux-newbie-8/need-solution-to-failed-to-fork-pty-and-error-creating-the-child-process-problems-777130/

I copied from a working box and used 

```
devpts /dev/pts devpts rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptxmode=000
```

Originally `mount | grep pts` showed no `gid` and `mode=600` which I think was my issue. I have no clue how that configuration could have been put in place, as PTS was never in the `fstab`
