### ISSUE TITLE
Cannot Install vscode-server on ubuntu server

### ISSUE THREAD

**Issue by behnam-io** [microsoft/vscode-remote-release#7370]
- Remote OS Version: Ubuntu 22 LTS

Steps to Reproduce:

1. ssh into ubuntu server
2. run vscode-server installation command `wget -O- https://aka.ms/install-vscode-server/setup.sh | sh`

Error: 

```
ERROR: no certificate subject alternative name matches
	requested host name ‘vscodeserverlauncher.blob.core.windows.net’.
To connect to vscodeserverlauncher.blob.core.windows.net insecurely, use `--no-check-certificate'.
```

**Comment by Winston-Gu** [comment]
same problem

**Comment by bamurtaugh** [comment]
Hi there, thanks for reporting!

We've made recent updates to how the VS Code Server runs with the [release](https://code.visualstudio.com/blogs/2022/12/07/remote-even-better) of the unified `code` CLI. Does that seem to install / work properly for you?
