### ISSUE TITLE
Dev Container PHP & Maria DB (community) PHP 8.1

### ISSUE THREAD

**Issue by Omrize** [microsoft/vscode-remote-release#7372]
Hello,

I'm using this configuration to run a laravel application, and I get the following error:
![image](https://user-images.githubusercontent.com/19373072/196003146-2c027384-92cb-485b-8032-1f4786ca882b.png)

this is how my db container config looks:
![image](https://user-images.githubusercontent.com/19373072/196003011-bf72081e-1a64-4729-b4a0-c8e372bea5c5.png)

and on laravel .env
![image](https://user-images.githubusercontent.com/19373072/196003030-dd13c6a5-a464-462d-b875-f7bd172c0736.png)

nothing else was changed.

what am I missing here?

**Comment by chrmarti** [comment]
Did you recreate all containers to make sure they pick up all changes? Please ask generic questions like this on StackOverflow or the Laravel community as this does not seem to be specific to dev containers. Thanks.
