### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Talaku123** [microsoft/vscode-remote-release#7375]
- Issue Type: `Performance`
- Extension Name: `remote-wsl-recommender`
- Extension Version: `0.0.17`
- OS Version: `Windows_NT x64 10.0.22621`
- VS Code version: `1.72.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/mtala/AppData/Local/Temp/ms-vscode-remote.remote-wsl-recommender-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bamurtaugh** [comment]
Hi @Talaku123, it looks like we don't actually have the text file in this issue - could you please attach it, and/or expand on what you're experiencing? Thanks!
