### ISSUE TITLE
Some releases/tags are missing on vscode-dev-containers github

### ISSUE THREAD

**Issue by marcindulak** [microsoft/vscode-remote-release#7376]
It looks like not all tags available as vscode extensions are available on the project github https://github.com/microsoft/vscode-dev-containers. For example installable extensions 0.251.0 to 0.255.4 are missing on github, or https://github.com/microsoft/vscode-dev-containers/releases/tag/v0.244.0 is not available as an installable extension in vscode.
What is the policy for github tags/releases publishing of extensions?

![Screenshot from 2022-10-17 18-51-52_part](https://user-images.githubusercontent.com/3178318/196240661-bac1b750-3dff-401a-b746-894543f47ac0.png)

![Screenshot from 2022-10-17 18-50-46](https://user-images.githubusercontent.com/3178318/196240748-5ab79633-5f91-4c06-b6b9-5807de8c41fc.png)

**Comment by chrmarti** [comment]
We are leaving `microsoft/vscode-dev-containers` behind and are replacing it with separately released templates and features. See https://github.com/devcontainers/templates and https://github.com/devcontainers/features.
