### ISSUE TITLE
Types of dependencies within NOTICE-remote-ssh.txt

### ISSUE THREAD

**Issue by dariomx** [microsoft/vscode-remote-release#7379]
Hello,

I recently asked on [#7304](https://github.com/microsoft/vscode-remote-release/issues/7304) whether NOTICE-remote-ssh.txt included all dependencies required by this extension. I have now a related question:

Are all the dependencies listed in NOTICE-remote-ssh.txt required at runtime? Or some are required due other usages like build tools, sample code, test code, and so on? If they are mixed inside, could be possible to tag them to distinguish which are truly runtime dependencies?

Thank you.

**Comment by dariomx** [comment]
Dear all, 

Could you comment on this issue please?

Thank you.

**Comment by chrmarti** [comment]
Why is this of interest? My understanding is that the notices file lists components that are distributed with the extension.

**Comment by dariomx** [comment]
Hello Christof,

This is required in my org in order to know if we can use this extension at all. The license of each component will be reviewed, hence we want to minimize the work and consider only those really needed. Some times these dependencies are not really required at runtime by the extension but rather come from a difference need: libraries used by tests or example code, or components needed to build the software, additional software used to produced documentation, etc. 

Actually, I suspect the scope of my question is perhaps wider and applies to any ThirdPartyNotices.txt generated and placed on Microsoft repositories (NOTICE-REMOTE-ssh.txt looks like one of those).

Hope you can give me a hand with that information, your help is appreciated it. 

Thank you and regards.

**Comment by dariomx** [comment]
Hello, Christof et all

Any update on this request? Your help is highly appreciated.

Thank you and saludos.

**Comment by dariomx** [comment]
Hello Christof,

Any news about this?

Thanks.

**Comment by eleanorjboyd** [comment]
Hello! Sorry for the delay, yes all the dependencies listed in NOTICE-remote-ssh.txt are required at runtime.

**Comment by dariomx** [comment]
Thank you for your reply, Eleanor. 

Can I assume the same about ay other third-party generated file in other Microsoft products? I have a similar question asked on vscode: 

https://github.com/microsoft/vscode/issues/165559

and since I suspect same tool is used to generate dependencies in both cases, I wonder if I could extend your answer to vscode and any other extension (eg C/C++ extension).

Thanks again!

**Comment by eleanorjboyd** [comment]
Hello! I am unable to answer for all the other third-party generate files in other Microsoft products but hopefully the person who responds to you in core could also answer that question. Thanks!

**Comment by dariomx** [comment]
Fair enough, Eleanor. Have a great holidays season.
