### ISSUE TITLE
Constant "Cannot reconnect. Please reload the window." issue

### ISSUE THREAD

**Issue by david-engelmann** [microsoft/vscode-remote-release#7381]
- VSCode Version: 1.72.2
- Local OS Version: Windows 11 Home
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Docker Containers with Ubuntu 20.04 as the WSL Distro
 - Logs: Pulled the logs for a container after the issue occurred and they had nothing relevant in them. If there are other logs or alternative files that could assist please let me know.

Steps to Reproduce:
I'm struggling to find patterns in the issue. Basically, it's occurring consistently but at variable lengths of time. 
1. Build a container through the remote development extension in the bottom left hand corner
2. Wait anywhere from 1 min to 3/4 hours for the container to suddenly drop the connection

Does this issue occur when you try this locally?: Yes/No - It's a remote connection specific issue, however, docker daemon is locally running through Docker Desktop
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No - Issue occurs if the extensions are disabled and the container is built through docker-compose

The most consistent way to cause the issue is to run something with a decent computational lift. Any time I attempt a nice bit of matrix multiplication at some point the error will occur. 

There are plenty of resources for docker, so it shouldn't be a memory issue. I'm unsure the root cause but it appears that when working on a hard process or bunch of processes, eventually the vscode server process freezes up or at least appears to. Please let me know what else I can provide to add clarity to the issue.
 
I'll include a screenshot of the popup message, which has no further error details.
![image](https://user-images.githubusercontent.com/81196676/196483086-a58e3cf9-94c0-413f-b81f-df07795936ec.png)

I'll also include a screenshot of the remote development extension corner.
![image](https://user-images.githubusercontent.com/81196676/196483775-33bac7ff-1dc6-45d3-978a-34adb1c55c58.png)

**Comment by chrmarti** [comment]
I guess the VS Code Server might run out of resources. Maybe use some extension (e.g., https://marketplace.visualstudio.com/items?itemName=mutantdino.resourcemonitor) to monitor resources?

**Comment by david-engelmann** [comment]
@chrmarti I'll monitor the resources but even not difficult processes are causing the VS Code Server to disconnect. Just pulling up vscode in wsl is causing a ton of resources to be consumed. [Others have confirmed this as well](https://github.com/docker/for-win/issues/13022#issuecomment-1287686090)

**Comment by david-engelmann** [comment]
This issue is still occurring and its makes docker in VS Code unusable, can someone please investigate?

**Comment by rebelliousconformist** [comment]
Hi I dont think it is a resource monitor problem ![image](https://user-images.githubusercontent.com/10911640/211776461-4af15dad-eade-4f35-845c-3686b281218f.png)
