### ISSUE TITLE
vscode-server took so high CPU usage that the remote server was zombied

### ISSUE THREAD

**Issue by Dynmi** [microsoft/vscode-remote-release#7388]
- VSCode Version: 1.70.2
- Local OS Version:  MacOS 12.6
- Remote OS Version:  Debian GNU/Linux 10 (buster)
- Remote Extension/Connection Type: SSH/Containers/WSL/Server
- Logs:

Steps to Reproduce:

1....
2...

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: have not tried yet

![image](https://user-images.githubusercontent.com/43609816/196926763-41d825ce-fc4f-48d5-aa41-6ab80e01730f.png)

**Comment by Dynmi** [comment]
![image](https://user-images.githubusercontent.com/43609816/196926139-4c63477c-c39f-4530-b940-d4889f0f0683.png)

**Comment by alexdima** [comment]
@Dynmi I see that not all server processes take 100% CPU. It would be good to find out if these processes were fiel watcher processes, pty hosts, or extension hosts. What were the complete CLI arguments for these processes?
