### ISSUE TITLE
Caching ssh remote connexion

### ISSUE THREAD

**Issue by F-PMOR** [microsoft/vscode-remote-release#7392]
- VSCode Version: 1.72.2
- Local OS Version: Windows 10 Entreprise 20H2 - build 19042.2006
- Remote OS Version: Ubuntu 20.04.5 LTS (focal)
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

my ssh config file on my windows host (C:\Users\USERNAME\.ssh)
```
Host SERVER
    HostName 192.168.1.2
	User user
	SetEnv LC_TOTO=toto
```
1.Connect to remote linux server via VSCode
2.start a terminal
3. start bash command : env |grep LC
```
user@SERVER:~$ env |grep LC
LC_TOTO=toto
LC_ALL=en_US.UTF-8
```
4. exit from vscode
5.change ssh config file : 
```
Host SERVER
    HostName 192.168.1.2
	User user
	SetEnv LC_TOTO=titi
```
reconnect to the server and look for env variable : 
6. you should have : 
```
user@SERVER:~$ env |grep LC
LC_TOTO=titi
LC_ALL=en_US.UTF-8
```
7. You have
```
user@SERVER:~$ env |grep LC
LC_TOTO=toto
LC_ALL=en_US.UTF-8
``` 
The Env variable is not change, the remote server keep the old information (in a cache ? ).
The workaround I found is to delete on the remote server the files .vscode-server/.xxxxxxxxxxx.(log/pid/token) 
Is there's a way to do that automatically on exit or any other solution to erase what seams a caching information ?

This does not occur when I connect with local ssh client from windows using my ssh config file :
ex: from my windows client on cmd window  : ssh server

Does this issue occur when you try this locally?: No

**Comment by eleanorjboyd** [comment]
Hello! During reconnection, do you kill the remote server first or just reconnect? Killing the remote server would mean the connection would have to be re-established and the SSH command would be run, otherwise you might just be connecting to an already existing connection. Thanks!

**Comment by F-PMOR** [comment]
Hello, what do you mean by killing the remote server ? I just connect and disconnect from the remote server. I use files/exit from vscode to disconnect from the remote host. Then I reconnect to it directly via vscode with remote explorer.
Thanks,
PM

**Comment by eleanorjboyd** [comment]
The command palette (cmd+P) should have an option on your local vscode instance that is `Kill VS Code Server on Host`. Thanks!

**Comment by F-PMOR** [comment]
Yes, it's working, thanks.
But is there a way to ``` kill vscode on host ```  each time you leave one server (not necessary for all ) ?

**Comment by eleanorjboyd** [comment]
In terms of changing environment variables from the SSH connection command these require the `kill vscode on host` every time. It might be worth looking into a way to more specifically target the environment variable you want to change that would not require a restart, such as launch.json for some related cases. Thanks!
