### ISSUE TITLE
Node user used locally even when `remoteUser` not set

### ISSUE THREAD

**Issue by dmattia** [microsoft/vscode-remote-release#7395]
- VSCode Version: 1.72.2
- Local OS Version: MacOS 12.4 (M1 mac if it makes a difference)
- Remote OS Version: mcr.microsoft.com/vscode/devcontainers/javascript-node:14-buster
- Remote Extension/Connection Type: Containers
- Logs:  [logs.txt](https://github.com/microsoft/vscode-remote-release/files/9844782/logs.txt)

Steps to Reproduce:

1. Add devcontainer files for Node using the VsCode command "Add Dev Container Configuration Files"
2. Select the Node option
3. Comment out the line `"remoteUser": "node"` in `devcontainer.json`, which has the comment `Comment out to connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.`
4. Open inside the devcontainer locally
5. Run `whoami` and see the value `node`

This can be seen in this example git repo: https://github.com/dmattia/devcontainer-root-test

<img width="1078" alt="Screen Shot 2022-10-22 at 9 11 36 AM" src="https://user-images.githubusercontent.com/8922077/197349678-9da2dd27-0391-4dd9-98e2-815350f62a73.png">

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Of note, this issue does not appear in Codespaces, where I do see the `root` user used: 
<img width="1024" alt="Screen Shot 2022-10-22 at 9 10 28 AM" src="https://user-images.githubusercontent.com/8922077/197349656-8d943d7f-57a1-4e46-abe4-513117284d3a.png">

**Comment by chrmarti** [comment]
This is a recent change: The base image can now include parts of the configuration and, e.g., set the `"remoteUser"` without you setting it yourself. We have updated the documentation, but the existing comment in your devcontainer.json is no longer correct. If you want `root` to be used, you can set it with `"remoteUser": "root"`.

**Comment by rvanlaar** [comment]
I've seem to hit two bugs.
One, my local docker version was from december 2021. 
Two, remoteUser was commented out.

Please make it a note regarding this change on https://aka.ms/vscode-remote/containers/non-root

**Comment by rvanlaar** [comment]
I got it to work. 
Reinstalled docker locally, did clean git checkouts and stopped using the CodeWorkspace by opening the folder as a new project in vscode. Somewhere it started working again.
