### ISSUE TITLE
Attach Visual Studio Code to a container fails 

### ISSUE THREAD

**Issue by aliahmadvand** [microsoft/vscode-remote-release#740]
- VSCode Version: Version 1.35.1
- Local OS Version: macOS high Sierra Version 10.13.6
- Remote OS Version: fedora:28 (https://yum.postgresql.org/10/fedora/fedora-28-x86_64/pgdg-fedora10-10-4.noarch.rpm)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Run my container 
2.Attach Visual Studio Code to the container
3. Receive this error:

`Setting up container with f6edfccaf67c386b462fb5179897062d46b3ce1f1cdc3d56a9eefd68d92b233c
Run: docker exec f6edfccaf67c386b462fb5179897062d46b3ce1f1cdc3d56a9eefd68d92b233c test -d /home/cdpuser/.vscode-server
Run: docker exec f6edfccaf67c386b462fb5179897062d46b3ce1f1cdc3d56a9eefd68d92b233c /bin/sh -c (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
NAME=Fedora
VERSION="28 (Twenty Eight)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Twenty Eight)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
Run: docker exec f6edfccaf67c386b462fb5179897062d46b3ce1f1cdc3d56a9eefd68d92b233c test -d /home/cdpuser/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f
Run: docker exec f6edfccaf67c386b462fb5179897062d46b3ce1f1cdc3d56a9eefd68d92b233c test -d /home/cdpuser/.vscode-server/extensions
Run: docker exec -w /home/cdpuser/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f -u 0 f6edfccaf67c386b462fb5179897062d46b3ce1f1cdc3d56a9eefd68d92b233c /bin/sh -c command -v git >/dev/null 2>&1 && git config --system credential.helper '!f() { command -v code >/dev/null 2>&1 && code --gitCredential $*; }; f' || true
OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "chdir to cwd (\"/home/cdpuser/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f\") set in config.json failed: permission denied": unknown
Command failed: docker exec -w /home/cdpuser/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f -u 0 f6edfccaf67c386b462fb5179897062d46b3ce1f1cdc3d56a9eefd68d92b233c /bin/sh -c command -v git >/dev/null 2>&1 && git config --system credential.helper '!f() { command -v code >/dev/null 2>&1 && code --gitCredential $*; }; f' || true`

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/551
