### ISSUE TITLE
Allow `vscode-remote://` to parse your `.ssh/config` and display alias in bottom left

### ISSUE THREAD

**Issue by Hacksore** [microsoft/vscode-remote-release#7400]
This is a great feature to be able to connect to a remote machine with ease.
[Connect to a remote host from the terminal](https://code.visualstudio.com/docs/remote/troubleshooting#_connect-to-a-remote-host-from-the-terminal)

ex: `code --folder-uri vscode-remote://ssh-remote+<FQDN><RemoteDirectory>`

Is there any possibility to support reading your .ssh config as well?

What I'd like to have is something like this:

```
code --folder-uri vscode-remote://ssh-remote+<AliasFromSSHConfig><RemoteDirectory>
```

This would make it easier to configure/execute since you might not know your FQDN off the top of your head 😬. The second part of the feature would be to see the `Host` alias in the bottom left instead of the FQDN.

Mock:
![image](https://user-images.githubusercontent.com/996134/197556574-1d51acc1-5391-42bc-a9c0-ffad140d41ab.png)

**Comment by Hacksore** [comment]
@eleanorjboyd I swear this wasn't working last week but maybe it was a case of PEBCAK 😅.

In any case, looks to be working now so I'll gladly close out the issue.

![image](https://user-images.githubusercontent.com/996134/198738701-77a4c7e6-3c95-4171-86b9-77692aa5d6da.png)

**Comment by eleanorjboyd** [comment]
Glad it is working now! Happy coding 🎉
