### ISSUE TITLE
Test: Create Dev Container

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#7403]
Refs: #7363

- [ ] anyOS @daviddossett
- [x] anyOS @joaomoreno

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%237403%0A%0A&assignees=chrmarti)

---

- Requires Dev Containers extension 0.261.0.
- Use `Dev Containers: Create Dev Container...` to create a dev container in a volume (without the need for a local folder or a repository).
- Verify the dev container starts successfully.
- Make some changes.
- Use `Remote: Close Remote Connection` to leave the dev container.
- Verify that you can use the Remote Explorer to open the folder (including any changes you made) again.

**Comment by joaomoreno** [comment]
✅ Tested on Windows with Docker on WSL2.

**Comment by daviddossett** [comment]
Worked great 👍
