### ISSUE TITLE
Test: User env variables for dev container features

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#7404]
Refs: https://github.com/devcontainers/spec/issues/91

- [x] anyOS @eleanorjboyd
- [x] anyOS @weinand

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%237404%0A%0A&assignees=chrmarti)

---

- Requires Dev Containers extension 0.261.0.
- Have a workspace folder with the following 3 files:
- `.devcontainer/devcontainer.json`:
```json
{
	"image": "mcr.microsoft.com/devcontainers/base:0-focal",
	"features": {
		"./test-feature": "latest"
	}
}
```
- `.devcontainer/test-feature/devcontainer-feature.json`:
```json
{
	"id": "test-feature"
}
```
- `.devcontainer/test-feature/install.sh`:
```sh
#!/bin/sh

printenv >/printenv.env
```
- Reopen this folder in a dev container and verify that `/printenv.env` has `_REMOTE_USER`, `_CONTAINER_USER`, `_REMOTE_USER_HOME` and `_CONTAINER_USER_HOME`.
- Add the following to the devcontainer.json:
```json
	"containerUser": "vscode",
	"remoteUser": "root",
```
- Rebuild the container and verify that `/printenv.env` has the updated values.

**Comment by weinand** [comment]
work fine for me on macOS and a Docker container.

**Comment by eleanorjboyd** [comment]
works as well for me, macOS and Docker container
