### ISSUE TITLE
Test: `${devcontainerId}` variable

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#7405]
Refs: https://github.com/devcontainers/spec/issues/62

- [ ] anyOS @mjbvz
- [x] anyOS @sandy081

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%237405%0A%0A&assignees=chrmarti)

---

- Requires Dev Containers extension 0.261.0.
- Have a workspace folder with the following 3 files:
- `.devcontainer/devcontainer.json`:
```json
{
	"image": "mcr.microsoft.com/devcontainers/base:0-focal",
	"features": {
		"./test-feature": "latest"
	}
}
```
- `.devcontainer/test-feature/devcontainer-feature.json`:
```json
{
	"id": "test-feature"
}
```
- `.devcontainer/test-feature/install.sh`:
```sh
#!/bin/sh

echo Hi!
```
- Use the new `${devcontainerId}` variable in the supported devcontainer.json properties: `name`, `runArgs`, `initializeCommand`, `onCreateCommand`, `updateContentCommand`, `postCreateCommand`, `postStartCommand`, `postAttachCommand`, `workspaceFolder`, `workspaceMount`, `mounts`, `containerEnv`, `remoteEnv`, `containerUser`, `remoteUser`, `customizations` and properties in the devcontainer-feature.json: `entrypoint`, `mounts`, `customizations`.
- Verify the `${devcontainerId}` is replaced with an id that is stable across container rebuilds, but changes for different dev containers (e.g., from a different local folder or repository when cloning into a volume).

**Comment by chrmarti** [comment]
Adding a few examples here:

Change the above devcontainer.json to:
```json
{
	"image": "mcr.microsoft.com/devcontainers/base:0-focal",
	"features": {
		"./test-feature": "latest"
	},
	"postCreateCommand": "echo ${devcontainerId} >~/devcontainerId.txt",
	"containerEnv": {
		"CONTAINER_ENV_DEVCONTAINER_ID": "${devcontainerId}"
	},
	"remoteEnv": {
		"REMOTE_ENV_DEVCONTAINER_ID": "${devcontainerId}"
	}
}
```

Change the above devcontainer-feature.json to:
```json
{
	"id": "test-feature",
	"entrypoint": "echo ${devcontainerId} >/devcontainerId.entrypoint.txt",
	"mounts": [
		{
			"source": "test-volume",
			"target": "/test-volume-${devcontainerId}",
			"type": "volume"
		}
	],
	"customizations": {
		"vscode": {
			"settings": {
				"test-setting": "${devcontainerId}"
			}
		}
	}
}
```

Verify the variable is correctly replaced.

**Comment by mjbvz** [comment]
Worked great for me in everything except for `postCreateCommand` (#7412)
