### ISSUE TITLE
Test: Config file parsing

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode-remote-release#7406]
Refs: https://github.com/microsoft/vscode-remote-release/issues/7321

- [ ] macOS @daviddossett 
- [x] linux @dbaeumer
- [x] windows @hediet

Complexity: 1

Author: @eleanorjboyd 

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%237406%0A%0A&assignees=eleanorjboyd)

---

Prerequisites: 
1. Use the [pre-release of the Remote-SSH extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh)

Steps:
1. open up your SSH config file
2. create a new entry that uses a "Match" statement
3. from command palette select "connect to host" 
4. Verification: make sure the host name you provided for the config entry with the "Match" statement appears as a selectable item in the dropdown.
6. Make sure to clear any settings out of your config once you are done

**Comment by dbaeumer** [comment]
@eleanorjboyd for someone that is not a ssh expert there is quite some searching involved to find out what match statements are and what they do. An example would have been helpful here.

**Comment by hediet** [comment]
This is what I used:

```
Match User jhon
  host "myserver.net"
  parameter2
```

**Comment by daviddossett** [comment]
Worked great 👍
