### ISSUE TITLE
Test: Dynamic template and feature index

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#7407]
Refs: 

- [x] macOS @meganrogge
- [x] linux @rzhao271
- [x] windows @dbaeumer 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%237407%0A%0A&assignees=chrmarti)

---

- Requires Dev Containers extension 0.261.0.
- Start with an empty folder.
- Use `Dev Containers: Add Container Configuration Files...` to add a configuration template and features.
- Ensure the UI works as expected.
- Reopen the folder in a dev container and make sure that works. (Use only a few features at a time as these will add to the build time.)

**Comment by meganrogge** [comment]
I like how this simplifies the dev container experience 👏🏼
