### ISSUE TITLE
Terminal: Can't generate VS Code extensions

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#741]
Issue Type: <b>Bug</b>

1) Connect to a SSH box
2) Open terminal
3) Run `npm install -g yo generator-code` if needed
4) Run `yo code`
5) Select extensions type
-> You're now supposed to enter the name of the extension. No keyboard input. No <kbd>Ctrl+C</kbd>.

Extension version: 2019.6.10042
VS Code version: Code - Insiders 1.36.0-insider (6520c22b83c0b6f168ba7de3309ffab42281e905, 2019-06-19T05:18:56.881Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.18.0-1018-azure
Remote OS version: Linux x64 4.18.0-1018-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.27GB free)|
|Process Argv|-psn_0_3916732|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 4.18.0-1018-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (5.47GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 4.18.0-1018-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (5.47GB free)|
|VM|0%|
</details>

**Comment by kieferrm** [comment]
Red herring. Same happens locally in a native macOS terminal.

**Comment by kieferrm** [comment]
@aeschli  figured out that it's an issue with https://www.npmjs.com/package/inquirer. When rolling back to version 6.3.1 the issue is fixed.

**Comment by aeschli** [comment]
- `npm install -g yo generator-code`
- `yo code`
- select `New Extension (TypeScript)`
- try to enter a name. Prompt does not accept any characters, even Ctrl+c is broken

Observe that yo contains `inquirer@6.4.0`.
Modify the installation to use `inquirer@6.3.1`: Steps above work again.

I tried to file this against https://github.com/SBoudrias/Inquirer.js/issues, but github seems to have an issue. FYI @SBoudrias

**Comment by aeschli** [comment]
Dup of https://github.com/SBoudrias/Inquirer.js/issues/811
