### ISSUE TITLE
Test: Invalid Port Range

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode-remote-release#7410]
Refs: https://github.com/microsoft/vscode-remote-release/issues/5970 

- [ ] macOS @isidorn 
- [ ] linux @dbaeumer 
- [ ] windows @rzhao271

Complexity: 1 

Author: @eleanorjboyd 

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%237410%0A%0A&assignees=eleanorjboyd)

---

Prerequisites: 
1. Use the [pre-release of the Remote-SSH extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) 

Steps: 
Part 1: 
1. set the variable `remote.SSH.serverPickPortsFromRange` to an invalid range. 
2. Verification: try to connect to the host for the invalid range and ensure an error message comes up that mentions the port range being incorrect

**Comment by dbaeumer** [comment]
@eleanorjboyd 

I was not able to get this working. I used the following settings

```json
	"remote.SSH.serverPickPortsFromRange": {
		"Localhost": "abc-def"
	}
```

Tried both `Localhost` and `localhost`. 

I also noticed that there is no `pre-release` version of the extension in the marketplace. At least it is not marked as such. I tested this using version `0.90.1`

**Comment by isidorn** [comment]
Same as @dbaeumer I do not see a pre-release version of the extension.
Might it be that while you uploaded 0.89.2022... version you forgot the pre-release flag? Since it looks like a pre-release version but it is not

![Screenshot 2022-10-25 at 15 37 43](https://user-images.githubusercontent.com/1926584/197788453-e57c5795-fa78-4d05-9737-103e6d4748e8.png)

fyi @roblourens

**Comment by karrtikr** [comment]
I think the intended version is: 
![image](https://user-images.githubusercontent.com/13199757/197883802-19e4d2e0-a459-47f5-98cf-8accd66e6b43.png)

It's marked as pre-release for me but I don't see the `Switch to pre-release button` here when on stable:

![image](https://user-images.githubusercontent.com/13199757/197883965-4bc24121-6d6d-4e93-921a-8ac68aaffbb8.png)

**Comment by eleanorjboyd** [comment]
Hi! Sorry about this- we are currently having some issues pushing out a release version due to some dependencies with the new remote-explorer extension and the work we did this iteration to move that to its own repo. I am will fix this issue and get back to you! Thanks

**Comment by eleanorjboyd** [comment]
Closing this as it is no longer planned to be released in this iteration, we are deferring this commit to the next due to the timing issues with push changes and getting out the build

**Comment by isidorn** [comment]
@eleanorjboyd @karrtikr can you just double check if there is some bug with showing the pre-release version in VS Code. If yes, can you file a new issue so @sandy081 looks into it.

**Comment by eleanorjboyd** [comment]
@roblourens can verify but this is not a bug but just an issue with our release version of remote-ssh due to some dependencies on remote-explorer which we are finalizing the build pipeline for. Thanks!
