### ISSUE TITLE
What is the `dev_container_feature_content_temp` image?

### ISSUE THREAD

**Issue by niccolomineo** [microsoft/vscode-remote-release#7414]
This suddenly appeared some time ago. What is that?

**Comment by chrmarti** [comment]
We use it to add install scripts for the `"features"` you might have configured in your devcontainer.json. (When you have BuildKit 0.8+ installed we use an additional build context instead.)

**Comment by niccolomineo** [comment]
Ok. Is it possible to disable this or is it mandatory?

**Comment by chrmarti** [comment]
If you are using features we need a way to bring the install script into the image build. Does this cause any problems?

**Comment by niccolomineo** [comment]
> If you are using features we need a way to bring the install script into the image build. Does this cause any problems?

As a user, it's adding noise to my image repo and it feels like I have less control on it. I can live with it but it's kind of a step backwards in the UX.

**Comment by niccolomineo** [comment]
> Are you able to install BuildKit? (as @chrmarti mentioned, the `dev_container_feature_content_temp` image is only used if you don't have a recent version of BuildKit installed)

According to Docker Desktop (v 4.13.1, which uses Engine v20.10), I am using BuildKit - not sure which version though:

```
{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "experimental": false,
  "features": {
    "buildkit": true
  }
}
```

**Comment by stuartleeks** [comment]
Oh, interesting. What do you see if you run `docker buildx version`?

**Comment by niccolomineo** [comment]
`github.com/docker/buildx v0.9.1 ed00243a0ce2a0aee75311b06e32d33b44729689`

**Comment by niccolomineo** [comment]
> Oh, interesting. What do you see if you run `docker buildx version`?

`github.com/docker/buildx v0.9.1 ed00243a0ce2a0aee75311b06e32d33b44729689`

**Comment by chrmarti** [comment]
We have changed this to only require the image when using features. With the BuildKit version you have, you should only see this image when using features with Docker Compose. This is tracked in https://github.com/microsoft/vscode-remote-release/issues/7305. Continuing there.
