### ISSUE TITLE
On Alpine container, `apt-get` is not found

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-remote-release#7417]
Testing #7407

On Linux
1. Set up an Alpine container with Conda and Ruby features.
2. Reopen in a dev container
3. :bug: Conda fails to install. 

The issue is `apt-get` is not found.

**Comment by chrmarti** [comment]
Requires https://github.com/devcontainers/spec/issues/58.

**Comment by chrmarti** [comment]
Continuing there.
