### ISSUE TITLE
Dev Containers: "Refresh" link in welcome view does not reload the window

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-remote-release#7418]
Testing #7403

<img width="330" alt="CleanShot 2022-10-25 at 10 22 29@2x" src="https://user-images.githubusercontent.com/25163139/197840889-53c37912-cb45-4ab8-8c96-56224edbf415.png">

**Comment by chrmarti** [comment]
That reruns a query for the current containers. If Docker is still not installed this welcome view should stay. (It will not reload the window.)

**Comment by daviddossett** [comment]
I installed it after seeing this message and still didn't see any changes. However this was on an Apple M1 computer which gave me a compatibility warning. No issues on Windows 11.

**Comment by chrmarti** [comment]
We check if `docker` is found on the `PATH`. I see Docker Desktop symlinks the CLI as `/usr/local/bin/docker`. That folder should be on the `PATH`, so it's not clear why it would not be found. Did this start working after a reload/restart?
