### ISSUE TITLE
Debian container with Ruby feature doesn't build

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-remote-release#7419]
Testing #7407

On Linux
1. Set up a Debian bullseye container with the Ruby feature
2. Run the "Rebuild and reopen in container" command
3. :bug: There's an error while building the container.

I am unable to copypaste directly from the VM so I took a screenshot for now.
![Screenshot showing the docker buildx command failed with the steps above](https://user-images.githubusercontent.com/7199958/197843041-3d015daa-1d86-488f-8690-9c4a8b62989a.png)

**Comment by chrmarti** [comment]
Could you extract and append the full log?

**Comment by rzhao271** [comment]
I'm unable to repro this issue now. Closing
