### ISSUE TITLE
VSCode can't quit or reopen the older folder in ssh

### ISSUE THREAD

**Issue by PrinceP** [microsoft/vscode-remote-release#7421]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.72.1
- OS Version: macOS monterey 12.6

Steps to Reproduce:

1. SSH connection is not working from the host, Restore windows setting is preserve.

**Comment by eleanorjboyd** [comment]
Hello, please include more information in order for us to assist. Thanks
