### ISSUE TITLE
ssh_config "Include" key

### ISSUE THREAD

**Issue by z-a-f** [microsoft/vscode-remote-release#7427]
## Info

- VS Code Version: 1.72.2
- Local OS: Mac OS 12.6

## Description

The [`ssh_config`](https://man7.org/linux/man-pages/man5/ssh_config.5.html) allows an `Include` keyword, which allows a user to split the config file. However, it looks like the current version of the remote does not recognize it when "Connect to Host" is used.

## Reproduction

1. Create a ssh config file to be included
    ```bash
    cat << EOF > ${HOME}/.ssh/test_include_config
    HOST dummy_test_host
        Hostname  github.com
        User      git
    EOF
    ```
1. Add the include into the main config file
    ```bash
    echo "\nInclude test_include_config\n" >> ${HOME}/.ssh/config
    ```
1. Confirm it works in the `ssh`
    ```bash
    ssh dummy_test_host
    # Should result in `git@github.com: Permission denied (publickey).`
    ```
    Note that if this step shows "`ssh: Could not resolve hostname dummy_test_host: nodename nor servname provided, or not known`", then something went wrong :)
1. Check if VS Code is able to see the `dummy_test_host`
    ![image](https://user-images.githubusercontent.com/4216323/198151562-64e3eb4f-7daf-4491-94ac-ad2f138dae40.png)
    ![image](https://user-images.githubusercontent.com/4216323/198151593-752207ab-d73c-469f-ab92-f2ea358df14c.png)
    Notice that the newly added host is not there :'(
1. Confirm that the host is recognizable if added directly
    ![image](https://user-images.githubusercontent.com/4216323/198151995-3c87b39a-a332-4620-84c4-4b38d9cf0973.png)

**Comment by eleanorjboyd** [comment]
Hi! This looks like a bug where the "include" keyword is not parsed correctly. Could you send over your full config file? We can mark this as something we need to fix but wanted to confirm exactly what your file looks like so I can replicate the issue myself. Thanks!

**Comment by z-a-f** [comment]
> Hi! This looks like a bug where the "include" keyword is not parsed correctly. Could you send over your full config file? We can mark this as something we need to fix but wanted to confirm exactly what your file looks like so I can replicate the issue myself. Thanks!

Here is the structure of my configuration. **Note:** The entry inside the `.ssh/config` as well as the contents of the `./.ssh/ai_ssh` folder is not maintained by myself -- those are changed automatically, if the configuration of the remote server changes. That means an option to just flatten the configuration into one file doesn't really apply here.

```console
$ find ./.ssh
./.ssh
./.ssh/config
./.ssh/ai_ssh
./.ssh/ai_ssh/includes
./.ssh/ai_ssh/zaf
./.ssh/ai_ssh/zaf/config
./.ssh/ai_ssh/zaf/current.pem
./.ssh/known_hosts
$ cat ./.ssh/config

Include ai_ssh/includes

$ cat ./.ssh/ai_ssh/includes
Include ai_ssh/zaf/config
$ cat ./.ssh/ai_ssh/zaf/config
HOST partition_cluster_ai
	User ai
	IdentityFile /Users/zaf/.ssh/ai_ssh/zaf/current.pem
	Hostname <HOSTNAME>
HOST partition_cluster_zaf
	User zaf
	IdentityFile /Users/zaf/.ssh/ai_ssh/zaf/current.pem
	Hostname <HOSTNAME>
        ServerAliveInterval 60
	ServerAliveCountMax 4
	StrictHostKeyChecking no
	UserKnownHostsFile /dev/null
$ ssh partition_cluster_zaf
======================================================================
Hi zaf! HAPPY COMPUTING
<SOME INFO>
======================================================================
$ hostname
<HOSTNAME>
$ logout
Connection to <HOSTNAME> closed
```

**Comment by z-a-f** [comment]
> Hi! This looks like a bug where the "include" keyword is not parsed correctly. Could you send over your full config file? We can mark this as something we need to fix but wanted to confirm exactly what your file looks like so I can replicate the issue myself. Thanks!

Also, you can reproduce it if you follow the steps I added: Basically create another config and include it in your `config` file.

**Comment by eleanorjboyd** [comment]
Thank you for the additional information! I am going to put this in the backlog as  a bug we need to fix. Thanks!

**Comment by allir** [comment]
Resolving this would be really great, is there any new information?
Having this issue as well, as my main .ssh/config file pretty much just looks like this:

```
Host *
    ... some default config...

Include config.d/*
```

This allows to separate various hosts into files per project for example.

**Comment by eleanorjboyd** [comment]
@allir, could you try putting you include statement at the top of your config file? Thanks

**Comment by allir** [comment]
@eleanorjboyd that does indeed work. It also seems to handle multiple Includes but only of they are all at the top of the file. If there is a host between them only the top one will work for example.

It's a workaround for sure but still feels like it should be fixed properly as the includes are supposed to be allowed anywhere in the file and works with ssh in general?

**Comment by eleanorjboyd** [comment]
yes we are working on a fix to have it work everywhere! It is a bit confusing when it is lower on the file if the include is based on a conditional part of the config file. This means it is a bit more complicated of a fix but should be a part of this ticket to handle that workflow.

**Comment by jamus-cambium** [comment]
FYI @eleanorjboyd I had an Include as the only line in my ssh_config, but it wasn't being parsed correctly because of the comment:

`Include config.d/* # comment`

**Comment by eleanorjboyd** [comment]
closing this in favor of [this longstanding issue](https://github.com/microsoft/vscode-remote-release/issues/4339) but I will copy over your comment for reference so we check that as an edge case when we make the changes. Thanks!
