### ISSUE TITLE
Support multiple developer roles via multiple files in `.devcontainer` folder

### ISSUE THREAD

**Issue by zfields** [microsoft/vscode-remote-release#7434]
Depending on the developer role, you may have a different experience interacting with a code base through a container (e.g. different credentials, user, context, Dockerfile, etc...). All these things are prescribed by `.devcontainer/devcontainer.json`.

I would like to be able to specify multiple configuration files (as opposed to only devcontainer.json) in the `.devcontainer` folder, then be prompted to select one when I choose to "Open Folder in Container...", unless there is only one, in which case I want it to be smart enough to select it for me.

Relates to: Remote - Containers

**Comment by Chuxel** [comment]
This has not been implemented in the UI of the Dev Containers extension yet.  Let's use this issue to track that since I'm not seeing another one.

**Comment by chrmarti** [comment]
Tracked as https://github.com/microsoft/vscode-remote-release/issues/7548.
