### ISSUE TITLE
Open local files when using vs code server

### ISSUE THREAD

**Issue by matifali** [microsoft/vscode-remote-release#7435]
I tried vscode server on my remote machine and can successfully login to browser-based vscode.
But I can not open any local files. 
While github.dev supports opening local files using the FileHandlings APIs, why vscode-server can not do the same.

**Comment by eleanorjboyd** [comment]
Hello, please include more information in order for us to assist. Thanks

**Comment by matifali** [comment]
I tried vscode server on my remote machine and can successfully login to browser-based vscode.
But I can not open any local files. 
While github.dev supports opening local files using the FileHandlings APIs, why vscode-server can not do the same.

**Comment by eleanorjboyd** [comment]
Hi, this is still not enough information- please clarify if this is a feature request or a bug. Additionally if you are using github.dev or a local version of VS Code.
