### ISSUE TITLE
open failed: administratively prohibited: open failed

### ISSUE THREAD

**Issue by eaglexiang** [microsoft/vscode-remote-release#744]
- VSCode Version:1.35.1
- Local OS Version:Linux Mint 19.1 Tessa
- Remote OS Version:CentOS Linux release 7.6.1810 (Core)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.open a remote folder in vscode
2.close the vscode
3.open a remote folder in vscode again

it alerts:

```shell
Tunnel(37364) stderr: channel 2: open failed: administratively prohibited: open failed
```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by eaglexiang** [comment]
If I run shell command below to kill all vscode-remote processes, It works again.

```shell
ps -ef | grep vscode | awk '{print $2}' | xargs kill -9
```

**Comment by roblourens** [comment]
I'm not sure why that would happen. I associate "administratively prohibited" with TCP forwarding being disabled.

**Comment by eaglexiang** [comment]
It does happened times everyday. And I found the more files or extensions vscode loaded, the more it happened.

**Comment by eaglexiang** [comment]
By the way, I've set `TCP forwarding` `true`, and I've set `MaxSessions` as `50`.

**Comment by eaglexiang** [comment]
@roblourens Could you reopen this issue?

**Comment by roblourens** [comment]
Could you share the full log from the "Remote - SSH" output channel?

![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Comment by eaglexiang** [comment]
```shell
remote-ssh@0.42.2
SSH Resolver called for "ssh-remote+dev"
SSH Resolver called for host: dev
Setting up SSH remote "dev"
Using commit id "c7d83e57cd18f18026a8162d042843bda1bcf21f" and quality "stable" for server
Install and start server if needed
> Found existing installation at /home/dp/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f...
> Printing the current remote environment...
> XDG_SESSION_ID=3
> SHELL=/bin/zsh
> SSH_CLIENT=192.168.99.163 59642 22
> USER=dp
> VSCODE_AGENT_FOLDER=/home/dp/.vscode-server
> MAIL=/var/mail/dp
> PATH=/usr/local/bin:/usr/bin
> PWD=/home/dp
> LANG=zh_CN.UTF-8
> SHLVL=1
> HOME=/home/dp
> LOGNAME=dp
> SSH_CONNECTION=192.168.99.163 59642 192.168.99.201 22
> XDG_RUNTIME_DIR=/run/user/1000
> _=/usr/bin/printenv
> Starting server...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> 9e36c7a2-6a6c-4888-914a-bb1d4aa5b0da==36339==
"install" terminal command done
Received install output: 9e36c7a2-6a6c-4888-914a-bb1d4aa5b0da==36339==
Server is listening on port 36339
Spawning tunnel with: ssh dev -N -L localhost:52243:localhost:36339
Spawned SSH tunnel between local port 52243 and remote port 36339
Waiting for ssh tunnel to be ready
Tunneling remote port 36339 to local port 52243
Resolving "ssh-remote+dev" to "localhost:52243", attempt: 1
Tunnel(36339) stderr: channel 2: open failed: administratively prohibited: open failed

Tunnel(36339) stderr: channel 2: open failed: administratively prohibited: open failed
channel 3: open failed: administratively prohibited: open failed
```

@roblourens

**Comment by roblourens** [comment]
And killing the server like you tried before doesn't fix it?

Is it possible that you are connecting to a system that assigns you to different machines each time you ssh in?

**Comment by eaglexiang** [comment]
> And killing the server like you tried before doesn't fix it?

Sometimes killing action works, sometimes not. It's easier to fix with less file tabs opened or less extensions loaded.

> Is it possible that you are connecting to a system that assigns you to different machines each time you ssh in?

I'm sure not that reason, because local ssh request always alert when I killed remote server process.

**Comment by eaglexiang** [comment]
Directly, it's not "killing remote vs process" but "killing remote ssh process" causes local request alert,.

**Comment by eaglexiang** [comment]
code was updated to `v1.36.0` and this issue seems been fixed already.

**Comment by josemera** [comment]
I am using vscode 1.36 and experiencing the same problem when trying to connect from a Mac

**Comment by eaglexiang** [comment]
@josemera OK I've reopen this issue for you.

**Comment by roblourens** [comment]
@josemera I would prefer that you open your own issue with as many details as possible including the log from the Remote-SSH output channel. The main reason that this error has shown up has been that tcp port forwarding is disabled on the server, so check that.
