### ISSUE TITLE
Building Dev Container: unable to prepare context: unable to get relative Dockerfile path

### ISSUE THREAD

**Issue by rik1599** [microsoft/vscode-remote-release#7440]
- VSCode Version: 1.72.2
- Local OS Version: Windows 11 22H2
- Remote Extension/Connection Type: Containers
- Logs: [remoteContainers-2022-10-31T11-33-46.510Z.log](https://github.com/microsoft/vscode-remote-release/files/9900678/remoteContainers-2022-10-31T11-33-46.510Z.log)
- devcontainer folder: [devcontainer.zip](https://github.com/microsoft/vscode-remote-release/files/9900683/devcontainer.zip)
- Extension version: v0.262.0-pre-release

Steps to Reproduce:

1. Try to build the devcontainer inside the zip file

**Comment by chrmarti** [comment]
Tracking as https://github.com/devcontainers/cli/issues/240. Thanks.
