### ISSUE TITLE
Fatal Error Please check Developer Tools 

### ISSUE THREAD

**Issue by AlmatYeraly** [microsoft/vscode-remote-release#7443]
- VSCode Version: 1.72.2
- Local OS Version: MacOS Ventura 13.0
- Remote OS Version: iPadOS 16.1
- Remote Extension/Connection Type: SSH/Containers/WSL/Server

Does this issue occur when you try this locally?: Yes

I am getting this error (in the title as well). Not quite sure how to go about it. The terminal shows the server is running.

![image](https://user-images.githubusercontent.com/46356542/199257232-8274bd69-67e7-46d9-8be6-70ca94eb56ac.png)

**Comment by Anzanda** [comment]
Me too... 404 error occured

**Comment by chrmarti** [comment]
Did you install the server on an iPad and are seeing this error in the browser?

**Comment by dejanceltra** [comment]
I had the same issue earlier, but it works now.

vscode.dev page was returning 404 for a few assets, so I'm pretty sure this was not server related, but I'm using it on Linux aarch64.

**Comment by Anzanda** [comment]
> Did you install the server on an iPad and are seeing this error in the browser?

I saw this error in both of them. Just server 404 error. It works now with no problems

**Comment by bamurtaugh** [comment]
Looks like things are working now, so I'm going to close this issue. Thanks for reporting!
