### ISSUE TITLE
[Doc]  use ${localWorkspaceFolderBasename} in named volume example

### ISSUE THREAD

**Issue by czzonet** [microsoft/vscode-remote-release#7444]
In example: [Improve container performance](https://code.visualstudio.com/remote/advancedcontainers/improve-performance#_use-a-targeted-named-volume)

```
"mounts": [
    "source=try-node-node_modules,target=${containerWorkspaceFolder}/node_modules,type=volume"
]
```

Better to use ${localWorkspaceFolderBasename} for readers to reuse instead of the static name.

```
"mounts": [
  "source=${localWorkspaceFolderBasename}-node_modules,target=${containerWorkspaceFolder}/node_modules,type=volume"
]
```

**Comment by chrmarti** [comment]
There is now also `${devcontainerId}`.
