### ISSUE TITLE
have the option to keep the terminal session running when vscode is closed

### ISSUE THREAD

**Issue by otaolafranc** [microsoft/vscode-remote-release#7445]
I would like the option that if we run an application, it stills keeps running when the VScode is closed. I found that there might be some workarounds but nevertheless it would be great to have this option as default in VS.

**Comment by Tyriar** [comment]
We don't have plans to do this as it would be unexpected for a lot of people and lead to confusion. You should keep the window open if you want to keep the processes running. Note there is an advanced feature to detach a session which should keep it around until you close the last vscode window if that's useful to you:

![image](https://user-images.githubusercontent.com/2193314/205132569-640ab4e8-d355-4478-a80f-429642b5d02d.png)
