### ISSUE TITLE
Infinite loop attaching remote docker container to vscode

### ISSUE THREAD

**Issue by Yusepp** [microsoft/vscode-remote-release#7446]
Few weeks ago I suddenly got this loop where I can connect to my server but i can't attach to the docker inside on both my `Windows 11 and 10` machines. I can attach them on my `Linux (Pop.OS 22.04)` machine but all windows based system don't work. As soon as I press ` Attach Visual Studio Code` on the desired container it starts the loop. I tried to reinstall vscode, install a lower  version, reinstall docker and remote-container extensions and downgrade them but nothing seems to work.

- VSCode Version:  `1.72.2`
- Local OS Version:` Windows 11 22H2`
- Remote OS Version: `Ubuntu 22.04`
- Remote Extension/Connection Type: SSH/Containers/WSL/Server:  `Remote-Containers 0.251.0`
- Logs:
```
[2948 ms] Remote-Containers 0.251.0 in VS Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075).
[2947 ms] Start: Run: ssh UOC /bin/sh
[2970 ms] Start: Run in host: id -un
```

<img width="1756" alt="ec4c3e0f026cb4147071e2ccc118e58b" src="https://user-images.githubusercontent.com/36641566/199586628-8ddb9e43-5ce4-4dc4-8d3e-5c043c7f2d87.png">

Here's the logs and the message in loop : `Setting up Remote-Containers`

**Comment by chrmarti** [comment]
Please try the latest Dev Containers versions (0.262.3 or 0.263.0-pre-release) which should fix this. (https://github.com/microsoft/vscode-remote-release/issues/7355)
