### ISSUE TITLE
Open folder in container fails after upgrade to MacOS Ventura

### ISSUE THREAD

**Issue by romado77** [microsoft/vscode-remote-release#7450]
- VSCode Version: 1.73.0
- Local OS Version: Darwin arm64 22.1.0 (Ventura)
- Remote OS Version: Debian GNU/Linux 10
- Remote Extension/Connection Type: Docker Container

Can't open folder in container after upgrade to MacOS Ventura. Getting following error in log:

Extension log:
> 2022-11-03 11:13:28.839 [error] {"message":"Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/rdolgush/.vscode/extensions/ms-vscode-remote.remote-containers-0.263.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/rdolgush/Dev/temp/csa_remote_dev_env/csa_backend --log-level debug --log-format json --config /Users/rdolgush/Dev/temp/csa_remote_dev_env/csa_backend/.devcontainer.json --include-merged-configuration --mount-workspace-git-root true","code":1} remote-containers.openFolder {"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"}

Window log:
>2022-11-03 11:13:28.841 [error] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/rdolgush/.vscode/extensions/ms-vscode-remote.remote-containers-0.263.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/rdolgush/Dev/temp/csa_remote_dev_env/csa_backend --log-level debug --log-format json --config /Users/rdolgush/Dev/temp/csa_remote_dev_env/csa_backend/.devcontainer.json --include-merged-configuration --mount-workspace-git-root true: Error: Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/rdolgush/.vscode/extensions/ms-vscode-remote.remote-containers-0.263.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/rdolgush/Dev/temp/csa_remote_dev_env/csa_backend --log-level debug --log-format json --config /Users/rdolgush/Dev/temp/csa_remote_dev_env/csa_backend/.devcontainer.json --include-merged-configuration --mount-workspace-git-root true
	at s._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:111561)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

It was working on Monterey.

**Comment by chrmarti** [comment]
Could you append the container log from when this fails? (`F1` > `Dev Containers > Show Container Log`)

**Comment by romado77** [comment]
@chrmarti, Thank you for hint! I found from log that image version wasn't passed to Dockerfile, thus no attaching to container. After adding args to docker compose yaml file all works fine.
