### ISSUE TITLE
Cannot access the terminal inside from the web server on IPAD

### ISSUE THREAD

**Issue by EvanGit09** [microsoft/vscode-remote-release#7451]
I have created servers hosted on both Windows 10 and WSL systems; in both cases, the terminal cannot be accessed on the web servers created. The terminal opens, but then I cannot write anything inside the terminal. Also, nothing appears (there is no output in the terminal, it just stays blank) when I run files.
![vs-code-server-error](https://user-images.githubusercontent.com/41394979/199745024-c14fb9ae-8c4b-41e5-90a5-e57c3831b616.jpg)

**Comment by sky80830** [comment]
same behavior observed.

**Comment by isaacl16** [comment]
having the same issue as well.

**Comment by wheredidhugo** [comment]
Same issue happening on my end.

**Comment by miroc99** [comment]
Same issue happening when I am trying to open a powershell terminal on ipad pro, but works fine on windows 10 chrome browser(Same project)

**Comment by icouldonlygetthisname** [comment]
Open the url in Blink seems to fix this issue

**Comment by kasraTM** [comment]
> Same issue happening when I am trying to open a powershell terminal on ipad pro, but works fine on windows 10 chrome browser(Same project)

Same thing,  my windows open it perfectly, but my ipad and my mac don’t

**Comment by bamurtaugh** [comment]
cc @Tyriar @meganrogge

**Comment by paul-wang** [comment]
any update on this ?

**Comment by wheredidhugo** [comment]
> any update on this ?

worked for me today weirdly

**Comment by meganrogge** [comment]
@EvanGit09 can you still reproduce? if so, try disabling `terminal.integrated.gpuAcceleration`
