### ISSUE TITLE
git credentials in devcontainer

### ISSUE THREAD

**Issue by illia-karpenkov** [microsoft/vscode-remote-release#7454]
Type: <b>Bug</b>

Any git command that creates .gitconfig from postCreateCommand in devcontainer.json will prevent vscode from propagating git credentials from host into a devcontainer.

Steps to Reproduce:

1. add postCreateCommand to devcontainer.json with the content:
   git config --global push.autoSetupRemote true
2. rebuild devcontainer and check git email from vscode terminal:
  > git config user.email

Extension version: 0.262.3
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.74GB (10.07GB free)|
|Process Argv|--crash-reporter-id 060bcdb5-c641-49fa-9bd3-12dedddd7079|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|11.70GB (6.93GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Python 3|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|11.70GB (6.93GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
fc301958:30595537
282f8724:30602487
3d0df643:30602300

```

</details>

**Comment by illia-karpenkov** [comment]
Small update: it seems that problem disappears if I remove --global flag from the command:
> git config push.autoSetupRemote true

**Comment by chrmarti** [comment]
`--global` makes it create the `~/.gitconfig`. We will not overwrite that with your local `.gitconfig` if it already exists.
