### ISSUE TITLE
Port forwarding Flask app not working on vscode-server

### ISSUE THREAD

**Issue by berceanu** [microsoft/vscode-remote-release#7455]
I am using vscode server (tried both insiders as well as stable versions). After connecting to vscode.dev, I run a Python Flask app which starts a webserver on localhost:8888. I expect vscode-server to be able to detect that and start port forwarding to a private custom domain. However, nothing happens. Manual forwarding the port also fails.

<img width="1552" alt="Screenshot 2022-11-03 at 21 47 33" src="https://user-images.githubusercontent.com/4405658/199819770-ab56c378-5026-460b-aadb-9813e63d5f3c.png">
<img width="1552" alt="Screenshot 2022-11-03 at 21 47 46" src="https://user-images.githubusercontent.com/4405658/199819806-ac4e844d-cf9e-46b7-ac5e-1598fa82c935.png">
<img width="1552" alt="Screenshot 2022-11-03 at 21 48 07" src="https://user-images.githubusercontent.com/4405658/199819852-47b99c9e-a577-4697-baaa-ae314ad1b9ca.png">

**Comment by VeryFunnyMonkey** [comment]
Same issue happening to me, only started happening around 2 days ago

**Comment by bamurtaugh** [comment]
Thanks for reporting! We've made recent updates to how the VS Code Server runs with the [release](https://code.visualstudio.com/blogs/2022/12/07/remote-even-better) of the unified `code` CLI. Are you still experiencing this in the latest version?
