### ISSUE TITLE
Unable to install VSCode Server on Raspberry Pi

### ISSUE THREAD

**Issue by coder0107git** [microsoft/vscode-remote-release#7456]
- VSCode Version: Latest VSCode Server Insiders Preview
- Local OS Version: Raspberry Pi OS GNU/Linux 11 armv7l 32-bit
- Remote OS Version: N/A (VSCode Web)
- Remote Extension/Connection Type: Server
<details><summary>Logs</summary>

```bash
pi@raspberrypi:~ $ wget -O- https://aka.ms/install-vscode-server/setup.sh | sh
--2022-11-03 17:28:32--  https://aka.ms/install-vscode-server/setup.sh
Resolving aka.ms (aka.ms)... 23.79.213.73
Connecting to aka.ms (aka.ms)|23.79.213.73|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://vscodeserverlauncher.blob.core.windows.net/builds/setup-scripts/setup.sh [following]
--2022-11-03 17:28:32--  https://vscodeserverlauncher.blob.core.windows.net/builds/setup-scripts/setup.sh
Resolving vscodeserverlauncher.blob.core.windows.net (vscodeserverlauncher.blob.core.windows.net)... 20.150.78.68
Connecting to vscodeserverlauncher.blob.core.windows.net (vscodeserverlauncher.blob.core.windows.net)|20.150.78.68|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1758 (1.7K) [text/x-sh]
Saving to: ‘STDOUT’

-                                                    100%[====================================================================================================================>]   1.72K  --.-KB/s    in 0s

2022-11-03 17:28:33 (29.4 MB/s) - written to stdout [1758/1758]

glibc version is 2.31
is min? 1
Installing from https://aka.ms/vscode-server-launcher/x86_64-unknown-linux-gnu
pi@raspberrypi:~ $ code-server
-bash: /usr/local/bin/code-server: cannot execute binary file: Exec format error
```

</details>

Steps to Reproduce:

1. Run `wget -O- https://aka.ms/install-vscode-server/setup.sh | sh`
2. Run `code-server`

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

I think the issue occurs because the x86_64 version gets installed instead of the armv7l version. I can install the `Aarch64` version (`https://aka.ms/vscode-server-launcher/aarch64-unknown-linux-gnu`) manually but I get the same `cannot execute binary file: Exec format error` error message.

**Comment by coder0107git** [comment]
Related: #7311 #7274

**Comment by charathram** [comment]
I can verify that the install fails with the same error on Raspberry Pi 4 running the same OS as the reporter above.

**Comment by Arjun99ab** [comment]
I can also verify this.

**Comment by connor4312** [comment]
I will close this, since we are soon making an Insiders quality of the [VS Code CLI](https://github.com/microsoft/vscode/tree/main/cli) available; no further releases of the `code-server` are planned. Please follow https://github.com/microsoft/vscode/issues/159791 for updates.

**Comment by nathanblair** [comment]
@connor4312 is there a way to either not close this or open a mirrored issue on the vs-code main github repository page for this support?

The repository you linked must be internal or private and as such the public can't "follow" any updates there :/
