### ISSUE TITLE
webview not work in the last update in remote-ssh。

### ISSUE THREAD

**Issue by TianQinS2** [microsoft/vscode-remote-release#7457]
- VSCode Version: 1.73
- Local OS Version: win11
- Remote OS Version: linux  remote-ssh: v0.91.2022103115
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by TianQinS2** [comment]
image
https://file+.vscode-resource.vscode-cdn.net/home/user/.vscode-server/extensions/app/src/view/element/vue.js

in remote-ssh mode this is not work。

**Comment by TianQinS2** [comment]
![image](https://user-images.githubusercontent.com/58967563/199887885-0a20f81b-4899-47b5-98be-9359c3a28b4e.png)

**Comment by TianQinS2** [comment]
panel = vscode.window.createWebviewPanel(
'View', // viewType
'name', // title
vscode.ViewColumn.Beside,
{
enableScripts: true,
retainContextWhenHidden: true,
localResourceRoots: [vscode.Uri.file(context.extensionPath)]
}
);

**Comment by TianQinS2** [comment]
It's right in local mode

**Comment by eleanorjboyd** [comment]
Hello! Can you send over your remote-ssh logs? And can you also include what extensions you have enabled?

**Comment by TianQingS** [comment]
asWebviewUri in old version return:

https://vscode-remote+ssh-002dremote-002balias.vscode-resource.vscode-webview.net/home/user/.vscode-server/extensions/app/src/view/element/vue.js

in 1.73 it's return:
https://file+.vscode-resource.vscode-cdn.net/home/user/.vscode-server/extensions/app/src/view/element/vue.js

**Comment by TianQingS** [comment]
html = html.replace(/(<link.+?href="|<script.+?src="|<img.+?src=")(.+?)"/g, (m, $1, $2) => {
        return $1 +  panel.webview.asWebviewUri(vscode.Uri.file(path.resolve(dirPath, $2))).toString() + '"';
    });

**Comment by TianQingS** [comment]
this problem is resolved, 
localResourceRoots: [vscode.Uri.file(context.extensionPath)] 
->
localResourceRoots: [context.extensionUri]

can solve this problem

**Comment by eleanorjboyd** [comment]
Hello! Just to clarify, is this problem fixed or are you suggesting a fix to this problem in your most recent comment? If it is fixed you can close it, if not if you clarify a bit more what you mean that would be helpful. Thank you for all your work to diagnose and investigate this issue!
