### ISSUE TITLE
Interactive commands are not started over Remote SSH

### ISSUE THREAD

**Issue by KaiWalter** [microsoft/vscode-remote-release#7458]
When starting interactive shell commands from extensions ![RemoteSshShell](https://user-images.githubusercontent.com/7418323/199893199-d4640e70-f98b-45f7-9cf3-22f0d853ca5d.gif) the command is sent to shell, not actually started and then shell expects input.

I experienced this issue first when using [Azure Functions extension](https://github.com/microsoft/vscode-azurefunctions/issues/3383) but can also reproduce it with other extensions like **Docker**

- VSCode Version:
  - Version: 1.73.0 (user setup)
  - Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
  - Date: 2022-11-01T15:34:06.111Z
  - Electron: 19.0.17
  - Chromium: 102.0.5005.167
  - Node.js: 16.14.2
  - V8: 10.2.154.15-electron.0
  - Sandboxed: No
- Local OS Version: Windows_NT x64 10.0.19044
- Remote OS Version: (my current configuration, but issues also experienced on Ubuntu 20.04 + 22.04) NAME="Common Base Linux Mariner" / VERSION="2.0.20221010"
- Remote Extension/Connection Type: SSH+WSL
- Logs: [RemoteSshOutputlog.txt](https://github.com/microsoft/vscode-remote-release/files/9935297/RemoteSshOutputlog.txt)

Steps to Reproduce:

1. install remote VM with *Ubuntu 20.04 or 22.04* 
2. remote SSH on VM and install **Docker** extensions
3. pull container like `busybox`
4. use Docker extension to _Run Interactive_ on this image

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
@eleanorjboyd @roblourens This stems from the issue I previously shared with you https://github.com/microsoft/vscode-azurefunctions/issues/3383. Any thoughts?

**Comment by eleanorjboyd** [comment]
@bamurtaugh, looking through the logs it seems like SSH successfully connects and there were no errors in the startup process. I do not think it is related to SHH based on the log information. @roblourens, would you agree?

**Comment by bamurtaugh** [comment]
Hey @roblourens, did you have a chance to look at this one?

**Comment by roblourens** [comment]
It looks like this is a terminal task failing to run the command in a remote window

**Comment by meganrogge** [comment]
not sure exactly what `Run Interactive` does - kind of cryptic in the docker extension code base. Looks like the task starts executing then neither exits or finishes. 

https://github.com/microsoft/vscode-docker/blob/15ce82e4503f22674ecbf4c2ab961d41cc0a97e7/src/commands/images/runImage.ts#L17

What happens if you run the command that the task runs in a terminal directly?

**Comment by KaiWalter** [comment]
> not sure exactly what `Run Interactive` does - kind of cryptic in the docker extension code base. Looks like the task starts executing then neither exits nor finishes in your gif.
> 
> https://github.com/microsoft/vscode-docker/blob/15ce82e4503f22674ecbf4c2ab961d41cc0a97e7/src/commands/images/runImage.ts#L17
> 
> What happens if you run the command that the task runs in a terminal directly?

When I run it in the terminal directly, those commands succeed.
