### ISSUE TITLE
No search results when workspace folder has a trailing slash since vscode 1.7.2

### ISSUE THREAD

**Issue by owebia** [microsoft/vscode-remote-release#7459]
- VSCode Version: 1.7.2+
- Local OS Version: Windows 11 build 22621.755
- Remote OS Version: Ubuntu 20.04.5
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Create a workspace with a folder ending with a trailing slash
   ```json
   {
      "folders": [
         {
            "uri": "vscode-remote://ssh-remote+example.com/home/"
         }
      ],
      "remoteAuthority": "ssh-remote+example.com"
   }
   ```
2. Search for a text that exists in any file
3. You get "No results found"

The same search when the folder has no trailing slash works.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by owebia** [comment]
Probably related post: https://community.home-assistant.io/t/vscode-search-results/471447/3

**Comment by eleanorjboyd** [comment]
What version of remote-ssh are you on?

**Comment by owebia** [comment]
v0.92.0

**Comment by andreamah** [comment]
Apologies for the very very late reply, I just saw this. Does this happen on the latest vscode version?

**Comment by owebia** [comment]
I checked on version `v0.107.1` (vscode `1.84.2`) and I was not able to reproduce the issue.

Thanks
