### ISSUE TITLE
Remote SSH connection issue with MAC OS 13

### ISSUE THREAD

**Issue by noip-lames** [microsoft/vscode-remote-release#7468]
I recently updated to Mac OS 13 and now the Remote - SSHv0.90.1 extension will no longer stay connected and continues to try and connect over and over again. Has this been reported by any other users? Our server logs show my session starts and then disconnects.

**Comment by eleanorjboyd** [comment]
Hello! Can you include your remote ssh logs? If you go back to version SSHv0.88 does this problem disappear?
