### ISSUE TITLE
The name ... is already in use

### ISSUE THREAD

**Issue by jordanbtucker** [microsoft/vscode-remote-release#7469]
- VSCode Version: VS Code Server 20220909.27
- Local OS Version: Windows 10
- Remote OS Version: Windows 10
- Remote Extension/Connection Type: Server
- Logs:
  - Tried to enable verbose logging via the [instructions](https://code.visualstudio.com/docs/remote/vscode-server#_where-can-i-provide-feedback-or-report-an-issue), but got the error: `The term 'server-launcher' is not recognized as a name of a cmdlet, function, script file, or executable program.`
  - Tried `code-server -v`, but got the error: `Found argument '-v' which wasn't expected, or isn't valid in this context`

Steps to Reproduce:

1. Run `code-server`
2. It asks for a name.
3. Choose a name.
4. Connect to remote code server.
5. Stop code server.
6. Run `code-server` again.
7. It asks for a name again.
8. Choose the same name.
9. Get the error `The name ... is already in use`

Does this issue occur when you try this locally?: No (N/A)
Does this issue occur when you try this locally and all extensions are disabled?: N/A, cannot get to that point.

**Comment by jordanbtucker** [comment]
I was able to delete the failed tunnel with these steps:

1. Install the Remote Tunnels extension.
2. Open Remote Explorer.
3. Select Remote from the drop down.
4. Right-click the failed tunnel.
5. Select Unregister Tunnel.

After that, I was able to setup a new tunnel with the old name.

**Comment by bamurtaugh** [comment]
Thanks for reporting!

We've made recent updates to how the VS Code Server runs with the [release](https://code.visualstudio.com/blogs/2022/12/07/remote-even-better) of the unified `code` CLI. Are you still experiencing trouble when you use the latest version?

**Comment by jordanbtucker** [comment]
Thanks for checking in. I was able to resolve the issue with the steps in my last comment. So I would consider this issue closed.
