### ISSUE TITLE
List of requirements at the remote environment

### ISSUE THREAD

**Issue by jan-di** [microsoft/vscode-remote-release#747]
As the source code is not public, it would be nice if there is a detailed list with all binaries and other requirements which the ssh extension needs to be installed on a remote environment

Background:
I'm currently using a webspace with ssh access on a shared hoster, and vscode cannot install the remote server because "flock" is not available. Therefore I would like to send them a list of the requirements so that they can see if they could support it.

```
Install and start server if needed
> 
> bash: line 25: flock: command not found
```
Or is the installscript itself publicly available?

**Comment by roblourens** [comment]
This is a list of things that we require on Linux and other tips that may be helpful: https://code.visualstudio.com/docs/remote/linux
