### ISSUE TITLE
VS Code Server Linux service

### ISSUE THREAD

**Issue by berceanu** [microsoft/vscode-remote-release#7477]
It would be nice to have a `systemd` service for the server, as this would allow it to be restarted automatically after a reboot, for instance.

**Comment by mcx808** [comment]
I managed to get the service up and running with the following systemd unit:

```
[Unit]
Description=VSCode Remote Server

[Service]
User={Your Username}
Group={Your Group}

ExecStart=/usr/local/bin/code-server --telemetry-level off

[Install]
WantedBy=multi-user.target
```

**Comment by bamurtaugh** [comment]
Thanks for filing! I believe this is addressed by https://github.com/microsoft/vscode-remote-release/issues/7125, but if this request is different or you're still experiencing issues, please let us know.
