### ISSUE TITLE
Can't install release version of 'ms-vscode.remote-server' extension because it has no release version.

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [microsoft/vscode-remote-release#7489]
- VSCode Version: 1.73.0
- Local OS Version: Windows 11 22H2
- Remote OS Version: Any
- Remote Extension/Connection Type: Server
- Logs:

Steps to Reproduce:

1. Click Install Button
2. An Error
![image](https://user-images.githubusercontent.com/50797982/200839233-07d2a389-6f2f-4fa2-b243-f475804b03d4.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by Dragon1573** [comment]
I also meet the same problem ...

## Environment Information

- Windows 11 Professional 22H2
- Visual Studio Code v1.73.0 (system setup)

## Screenshots

Except "WSL", other 3 plugins are using the latest pre-release version.

![image](https://user-images.githubusercontent.com/49941141/200840414-636ca13e-44bd-435f-bb85-daf9c0fa93c2.png)

Click "Update to version v0.22.0", an error occured.

![image](https://user-images.githubusercontent.com/49941141/200840974-6900840f-16b6-4a49-be9c-81bc221c83c0.png)

![image](https://user-images.githubusercontent.com/49941141/200841015-7f2920e2-72ac-471b-843c-0bc6f5230f0a.png)

**Comment by Dragon1573** [comment]
@Natural-Harmonia-Gropius 

`ms-vscode.remote-server` is actually the "Remote Tunnels" extension. It looks like something below on my device.

![image](https://user-images.githubusercontent.com/49941141/200842056-82a82595-be03-46b6-b35e-0971870df3a0.png)

When I click "Switch to Release Version", the same error occured and pops up a notification at the bottom-right corner.

![image](https://user-images.githubusercontent.com/49941141/200842470-3ee59981-0957-4c44-b64e-863c0856fa76.png)

*****

Maybe there's some "installation logic" error on VSCode Extensions? The "Remote Tunnel" only have pre-releases but no stable releases so it can't perform the update action?

**Comment by Natural-Harmonia-Gropius** [comment]
> actually the "Remote Tunnels"

I know, the extension pack try to update and get fails every startup, that's annoy.
After uninstalled it, I can't reinstall the pack now.

> only have pre-releases but no stable releases so it can't perform the update action

This is what should be addressed.

**Comment by vxltersmxth** [comment]
same issue

**Comment by Natural-Harmonia-Gropius** [comment]
Fixed by 0.23.0

**Comment by darkred** [comment]
@Natural-Harmonia-Gropius I confirm that it's fixed in 0.23.0 👍
But I notice that the 4th extension of the pack, 'ms-vscode.remote-server' (Remote Tunnels), has been removed the new version . Will it be re-added in the next version? Could you please elaborate?

**Comment by Natural-Harmonia-Gropius** [comment]
Until the day Remote Tunnels releases are available, I think.
