### ISSUE TITLE
server-env-setup is not working

### ISSUE THREAD

**Issue by BhavyaVM1** [microsoft/vscode-remote-release#7490]
- VSCode Version: 1.73.0 (Universal)
- Local OS Version:
- Remote OS Version: RHEL8
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. I have a linux host that i am connecting with the Remote Development Extension. On the server installation process it setup the umask from the current shell. I have changed umask value from **~/.vscode-server/server-env-setup** file. whatever inside server-env-setup file is not triggering on the server start process.
2.Please provide the setup for **server-env-setup** in the documentation.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by eleanorjboyd** [comment]
Hello! Could you provide additional details on this question and what file setup you are looking for? Can you provide the full path name of the file you are referencing so we can understand if it is one that we are installing. Thanks!

**Comment by BhavyaVM1** [comment]
I have to setup a umask value 022 from the .bashrc file in the remote host.

> bgl-ads-test:~ > umask
> 0022
> bgl-ads-test:~ > touch foo_touch
> bgl-ads-test:~ > code foo_code
> bgl-ads-test:~ > ls -la foo*
> -rw-------. 1 bvmohan eng 0 Nov 14 18:32 foo_code
> -rw-r--r--. 1 bvmohan eng 0 Nov 14 18:32 foo_touch_

The files that i am creating is having different permissions, while doing it through terminal and through code command/vscode ui. I tried creating a **server-env-setup** file in the .vscode-server folder and tried to set the umask value 077 from there( I tried 077 to check which umask will get affected - one from .bashrc or from .server-env-setup). After that i noticed my permission changed to 077. And then i tried to change the permission back to 022 in the server-env-setup file and i am not able to revert it back. 

If i switch my bash to a different shell, permissions are perfect there. Something with the **server-env-setup** file changed the behaviour. I tried uninstalling the server and cleared all data from the local machine. Somewhere this permissions got cached. 

What is the preferred way to change umask when we connect with vscode remote SSH. From where exactly the vscode reading the umask value when a new file is created using code command or UI.

**Comment by eleanorjboyd** [comment]
Hello! A few suggestions, we do not actually use the server-env-setup file, this is only for WSL. Instead, if your goal is running the script on login, you can put it in the bash rc or use a remote command which may work as well. We have an ongoing issue about umask that you can track as well for updates on that feature request: https://github.com/microsoft/vscode-remote-release/issues/4442

**Comment by BhavyaVM1** [comment]
Hai, I have already set the umask from .bashrc. Since i did a mistake of setting server-env-setup in the Remote-SSH, Is there some way to reset everything back to the initial state. I did tried uninstalling the server, killing the server etc, Please suggest a solution to revert it back. Thanks.

**Comment by eleanorjboyd** [comment]
Hello @BhavyaVM1, I am so sorry I must have missed this. Are you still experiencing this issue or were you able to reset everything? In terms of resetting, you can reset all the ssh settings like all VS Code settings and the command "kill vs code on remote" will help reset it on the remote side. Let me know your status and I'll try my best to help if the error is still occurring.
