### ISSUE TITLE
Armv7l 32 bit support

### ISSUE THREAD

**Issue by thorgrimjansrud** [microsoft/vscode-remote-release#7495]
- VSCode Version: 1.71.0
- Local OS Version: W11 Pro 21H2
- Remote OS Version: Debian based Armv7l 32-bit (Wago 752-8203 Edge Controller)
- Remote Extension/Connection Type: Remote-Server CLI 

I ran into problems similar to: https://github.com/microsoft/vscode-remote-release/issues/7456.
As I understand something is going on with the release of yet another code-server.

But from the quickstart its a link to the system requirements that says "code-server" is supported on armv7l:

https://code.visualstudio.com/docs/remote/vscode-server#_quick-start
![image](https://user-images.githubusercontent.com/48207719/201025821-0753c641-b38f-4097-8652-34090bc4fad2.png)
![image](https://user-images.githubusercontent.com/48207719/201026977-056ba840-280b-4ae4-a7da-a07cc40f119d.png)

Is it so that the link to the system requirements is not updated to match the requirements for code-server CLI?
And this version of code-server is deprecated (?).

Could you please describe more clearly what is the future of armv7l 32 bit support and what is possible today.
I use the VS Code Remote Development extensions and remote SSH that works fine with a minor tweak on my system but would like
to have the remote tunneling/WEB client feature.

**Comment by connor4312** [comment]
Added in https://github.com/microsoft/vscode/pull/163971. The next VS Code stable release should have info on how to use it 🙂

**Comment by thorgrimjansrud** [comment]
@connor4312: Could you confirm the version you are referring to? I have both 1.74.0-insider and 1.73.1 installed that have the "tunneling" pre-release. The beneath information is not helpful because I can not install the server on armv7l 32 bit target.. (but I can make it work on 64-bit WSL). 

![image](https://user-images.githubusercontent.com/48207719/201487861-41e0fd6a-3757-4467-ad70-0a843d22bd54.png)

**Comment by connor4312** [comment]
check here: https://github.com/microsoft/vscode-remote-release/issues/7129#issuecomment-1312521130

**Comment by thorgrimjansrud** [comment]
@connor4312: I now found the "arm32" CLI file but install fails.

![image](https://user-images.githubusercontent.com/48207719/201543282-55ce920c-df67-44c0-b64c-3414408eced9.png)

![image](https://user-images.githubusercontent.com/48207719/201541877-6a99b7fc-c61a-411a-b23c-d3d8aa137826.png)

A missing/faulty initial check ? 

![image](https://user-images.githubusercontent.com/48207719/201541953-aec52d4b-76d1-434d-ab4f-5b8078e6d4db.png)

![image](https://user-images.githubusercontent.com/48207719/201542012-7d6904f7-102a-4012-a8d3-83c28bf97afd.png)

![image](https://user-images.githubusercontent.com/48207719/201542045-77f44f25-6163-48bc-ac87-5d0716bec49f.png)

![image](https://user-images.githubusercontent.com/48207719/201542258-af002942-df7d-4614-93ac-1d3db51c9122.png)

Please see what you can do, We/Wago sell a lot of these controller units world wide. Would love to empower them.

**Comment by connor4312** [comment]
This logic is based on https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites, which is checked via [`ldd --version`](https://github.com/microsoft/vscode-cli/blob/947706875ad657925ffda6e7f686e24d3751cbfa/launcher/src/util/prereqs.rs#L114-L133).

**Comment by thorgrimjansrud** [comment]
Thanks @connor4312 for trying to help out. I've read this before when trying the "old" code-server that had the same prerequisites. That worked, and my glibc etc. is ok. Don't know why you are checking musl, thats should not be necesarry in my system with glibc should it (?) so that was the reason I believed there was something up with your checking. If the library requirements for the code-server is equal to the CLI then this will run if its not stopped by these initial checks that must be different from the code-server ..?

**Comment by connor4312** [comment]
Hmm. Are you able to manually download the latest server bits directly (https://az764295.vo.msecnd.net/insider/07edd19d50e77c4cce91f8fb897923c1ac4b6ac0/vscode-server-linux-armhf.tar.gz) and run `./server.sh` successfully inside of that? 

If so maybe our documentation + checking just needs to be adjusted; I don't own the requirements page, so that might be the case...

**Comment by thorgrimjansrud** [comment]
Yes.

![image](https://user-images.githubusercontent.com/48207719/202103417-ee061e7e-1fbe-47b7-8e92-62a72c6c1160.png)

Then I tried ./code-server-insiders. This fails becuase of my busybox I think but I know the solution from before with the old code-server [here](https://github.com/thorgrimjansrud/vs-code-on-wago-device-armv7l/issues/1#issue-1350411256).

![image](https://user-images.githubusercontent.com/48207719/202106165-e85450d9-0b3b-43eb-9e4b-ee7cf6a1ea36.png)

**Comment by connor4312** [comment]
Interesting, thanks. @deepak1556 what's your recommendation here?

**Comment by deepak1556** [comment]
@thorgrimjansrud , the cli checks for glibc version based on `ldd --version` output and `2.7` is definitely old. Given that you are able to run the server, the system does have the required glibc version ? Can you provide the output of `/usr/lib/libc.so.6 --version` to validate this.

**Comment by thorgrimjansrud** [comment]
@deepak1556: Yes its 2.30.

![image](https://user-images.githubusercontent.com/48207719/202516086-9f916e2a-191b-4310-a775-6512ed7fe6c7.png)

 Just let me know if there are things to test !

**Comment by connor4312** [comment]
> @thorgrimjansrud , the cli checks for glibc version based on ldd --version output and 2.7 is definitely old. Given that you are able to run the server, the system does have the required glibc version ? Can you provide the output of /usr/lib/libc.so.6 --version to validate this.

Excellent idea! The current logic was ported from the remote ssh shell that didn't have access to that, but it's conveniently exposed in the [libc crate](https://docs.rs/libc/0.2.137/libc/fn.gnu_get_libc_version.html).

**Comment by thorgrimjansrud** [comment]
@connor4312  would this fix be in the next release..?

**Comment by connor4312** [comment]
It'll be in the next Insiders available by the PST morning / sometime today in Europe. I'll send a new link once it's ready.

**Comment by thorgrimjansrud** [comment]
Thanks @connor4312 I tried it. There is still some checks that inhibits me running the server:
![image](https://user-images.githubusercontent.com/48207719/202767374-0c673a60-354a-4759-b9e7-b2ab9b8ed4db.png)
My libstdc++ seems ok:
![image](https://user-images.githubusercontent.com/48207719/202767416-89deeab7-c633-4acc-aeb6-030b158c3b8a.png)
Found you source-code [here](https://github.com/microsoft/vscode/blob/main/cli/src/util/prereqs.rs), seems like you are checking ‘/lib64’ but we are on 32-bit ‘/lib’ so guess you can combine e.g. the ‘target_arch’ further up to get it correct path. Also skip the ‘ld-musl-x86_64.so.1’ ..?

**Comment by connor4312** [comment]
Got it, I'll patch that up as well. For my own ability to test, what distribution are you running? I initially have been testing via `docker run -it arm32v7/ubuntu`, but that seems to be a bit different than your environment (e.g. libstdc++ is installed in `/lib/arm-linux-gnueabihf/libstdc++.so.6` and discoverable in `ldconfig -p`)

Thanks for your patience.!

**Comment by thorgrimjansrud** [comment]
This is a debian distro we build for our edge controller hardware. This hardware also supports docker.
![image](https://user-images.githubusercontent.com/48207719/202781375-6419c101-b1ae-4519-a692-4928dfd96388.png)
hmm.. 'ldconfig' does not work in my distro (command not found). But if its possible to search in '/usr/lib' or maybe downstream from here or check ldconfig.. Maybe I also can check some32 bit docker images later and compare ..

**Comment by connor4312** [comment]
We run `ldconfig -p` with no further arguments

**Comment by thorgrimjansrud** [comment]
@connor4312 Finally it runs through the startup procedure! Awesome. I can start the tunneling "./code tunnel -mytunnel" and find this tunnel both in the browser and VS Code IDE. As in previous code-server I must fix "readlink -> realpath" but ok. Still there is error when connecting "./node: cannot execute binary file: Exec format error". Are we sure about the 32 bit compatibility and Node.JS here ..?
