### ISSUE TITLE
ssh_config Include wildcard files are missing

### ISSUE THREAD

**Issue by hi120ki** [microsoft/vscode-remote-release#7499]
- VSCode Version: 1.73.1 (Universal)
- Local OS Version: macOS ventuna 13.0.1

Hi, I'm using remote ssh to edit server's files on VSCode.
Then, I try to use `Include` keyword to manage ssh configs like this

```
$ ls ~/.ssh
config
config-h
config-n
config-r
id_ed25519
id_ed25519.pub
known_hosts

$ cat ~/.ssh/config
...
Include config-*
...

$ cat ~/.ssh/config-h
Host h-xxx
  HostName 10.0.0.1
  ProxyJump h
  User xxx
  Port 22
  IdentityFile ~/.ssh/id_ed25519
```

Using `Include` keyword with wildcard `*` to read other ssh's config files works well in ssh command.
But in VSCode remote ssh, it does not work and it reads only `~/.ssh/config` hosts.

It will be nice to VSCode remote ssh can handle `Include` keyword with wildcard `*`.

Cloud you give me some comments about this?
Thank you.

**Comment by eleanorjboyd** [comment]
Hello! We have tried to implement a fix for this but it has some additional specifications about how to arrange your config file. Please reference this issue for more information: https://github.com/microsoft/vscode-remote-release/issues/4339

**Comment by hi120ki** [comment]
Thank you for comment!
I checked referenced issue and enabled notification.

Cloud you determine to close this issue or keep open?
Thank you.

**Comment by eleanorjboyd** [comment]
We will close this issue and keep track of work on the other issue to centralize all work on this problem. Thanks
