### ISSUE TITLE
Failed to set remote SSH tunnel

### ISSUE THREAD

**Issue by uishon** [Microsoft/vscode-remote-release#75]
- VSCode Version: 1.34.0-insiders
- Local OS Version: Windows 10. 1809.
- Remote OS Version: Ubuntu 18.04 (running on on hyper-v)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. remote-ssh: connect <vm-uishon-ubuntu>
2. terminal prompts for password
3. connection works but, eventually, I get an error message and this log
```
SSH Resolver called for "ssh-remote+vm-uishon-ubuntu"
SSH Resolver called for host: vm-uishon-ubuntu
Setting up SSH remote "vm-uishon-ubuntu"
Using commit id "473af338e1bd9ad4d9853933da1cd9d5d9e07dc9" and quality "insider" for server
Install and start server if needed
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> uishon@172.17.104.39's password:
> 
> 
> Welcome to Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-48-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>  * Ubuntu's Kubernetes 1.14 distributions can bypass Docker and use containerd
>    directly, see https://bit.ly/ubuntu-containerd or try it now with
> 
>      snap install microk8s --classic
> 
>  * Canonical Livepatch is enabled.
>    - All available patches applied.
> 
> 44 packages can be updated.
> 0 updates are security updates.
> 
> 
> bash: cannot set terminal process group (119817): Inappropriate ioctl for device
> bash: no job control in this shell
> 
> Found existing installation...
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
> 6079d990-24c2-46f4-a8e6-6e5201303f32==45905==
> 
"install" terminal command done
Received install output: 6079d990-24c2-46f4-a8e6-6e5201303f32==45905==
Server is listening on port 45905
Spawning tunnel with: ssh  vm-uishon-ubuntu -N -L localhost:20479:localhost:45905
Spawned SSH tunnel between local port 20479 and remote port 45905
Waiting for ssh tunnel to be ready
Tunnel(45905) stderr: Permission denied, please try again.

Tunnel(45905) stderr: Permission denied, please try again.

Tunnel(45905) stderr: uishon@172.17.104.39: Permission denied (publickey,password).

Could not establish tunnel to "vm-uishon-ubuntu" (Max wait time exhausted).
Could not establish tunnel to "vm-uishon-ubuntu" (Max wait time exhausted).
```

**Comment by TheStoof** [comment]
Is your /tmp noexec by any chance?

**Comment by kieferrm** [comment]
@uishon you might have another password prompt waiting for you in a terminal. The terminal should have popped up by itself. But if it didn't check the terminals in the drop down of the Terminal panel.

**Comment by TheStoof** [comment]
We are using PKI, which works direct but through the jump box, it does not. I also tried jumping through a jump box to a box that would require a password and was prompted. The error that appears is that the server isn’t x86_64 or something like that.

**Comment by roblourens** [comment]
If you have to use a password to log in, then you will have to set `remote.SSH.showLoginTerminal`.

See https://code.visualstudio.com/docs/remote/troubleshooting#_enabling-alternate-ssh-authentication-methods for details

Let me know whether that helps

**Comment by uishon** [comment]
That helped. Thanks. I'm now connected and able to work remotely.

**Comment by jovinbm** [comment]
@uishon How are you dealing with the constantly changing IP address of Hyper-V? Everything works on my end except every time I wake the PC from sleep/restart, they ip address of the VM in Hyper-V is different and I have to change the host in ssh config.

**Comment by uishon** [comment]
I'm using a dns name. In my case it's the hyper-v Linux name with a ".
mshome.net" suffix. Works wakeup or reboot.

**Comment by jovinbm** [comment]
Okay thanks. I have a a linux vm called `dev` but ssh-ing to `username@dev.mshome.net` but cannot resolve hostname. Am I doing something wrong?

**Comment by jovinbm** [comment]
I figured it out. I was using the hyper-v name given to the machine instead of the hostname of the linux machine. Works now. Thanks.
