### ISSUE TITLE
Test improved handling of password auth with SSH

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#750]
Test https://github.com/microsoft/vscode-remote-release/issues/513

- [x] Windows @RMacfarlane
- [x] Linux @jrieken
- [x] Mac @rebornix

Complexity: 3

Use the Nightly SSH extension for testing (uninstall stable)

- Disable the `remote.ssh.showLoginTerminal` setting if you have that set already
- Configure and connect to to the ssh remote `52.247.215.15` with username `roblou`
- You should get a password prompt in a quick input, the password is `myubuntuVM1!`
- While connecting and once connected, the terminals named "install" and "SSH Tunnel" should not show up in the terminal dropdown picker
- But while connecting, there should always be a progress notification with a "details" link. If you click that, it should reveal the terminal.

**Comment by rebornix** [comment]
Works as expected after typing in passwords a couple of times, the only catch is once VS Code loses focus, an error throws.
