### ISSUE TITLE
Hang when TCP Forwarding is disabled

### ISSUE THREAD

**Issue by girlpunk** [microsoft/vscode-remote-release#7506]
Type: <b>Bug</b>

When a connection to the remote host was successful, but port forwarding could not be established because `AllowTcpForwarding` was set to `no` in the SSHD configuration, no errors are reported and the `Opening Remote...` message appears forever.

The situation is only discovered when clicking the `show details` option in the notification during a password prompt, which shows the SSH log in the terminal, revealing the error `channel 3: open failed: administratively prohibited: open failed`

Extension version: 0.92.0
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (11.58GB free)|
|Process Argv|--crash-reporter-id 14e144c1-dc8e-43ea-ba73-fe5d4fa0f758|
|Screen Reader|no|
|VM|17%|

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce2:30605431
iaj6b796:30608729
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by eleanorjboyd** [comment]
Hello! Thank you for submitting this- this is a bug we will look to fix to surface the error more visibly.

**Comment by joshspicer** [comment]
This is documented in our "tips and tricks" section https://code.visualstudio.com/docs/remote/troubleshooting#_troubleshooting-hanging-or-failing-connections

**Comment by joshspicer** [comment]
This is also already handled in the extension, checking for `administratively prohibited: open failed` and providing the following tip.

```
ERROR: TCP port forwarding appears to be disabled on the remote host. Ensure that the sshd_config has `AllowTcpForwarding yes`. Contact your system administrator if needed.
```

I am also improving this by tying it into a new error handling mode [as shown in the change log this month](https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_96.md#enhanced-session-logging)
