### ISSUE TITLE
Missing changelog for Remote SSH

### ISSUE THREAD

**Issue by pcjmfranken** [microsoft/vscode-remote-release#7510]
🚨 The issue tracker is not for questions 🚨  🤧 

My Current channel VSCode shows an available update to `v0.92.0` of the [Remote - SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) extension, but I cannot for my life find any mention of this version or its changes in any of the release notes.

It looks like several obfuscated files were added, increasing the total extension size by nearly a third. It seems odd for this to remain undocumented (publicly, anyway). Am I missing something, or is this indeed intentional?

There's a related matter that I'd best communicate in private to an insider. What email address should I send this to?

**Comment by eleanorjboyd** [comment]
Hello! Thank you for reaching out - we are currently looking into the extension size increase to get an answer on that. In the meantime my email is eleanorboyd@microsoft.com and you can contact me directly. Thanks!

**Comment by eleanorjboyd** [comment]
Hello! Just to follow up, this is just an artifact of the telemetry module we use and how it is then packaged by webpack which is why there was no change log. We appologize for the size increase!
