### ISSUE TITLE
VS code server, request is blocked

### ISSUE THREAD

**Issue by a-pipi** [microsoft/vscode-remote-release#7515]
- VSCode Version: 1.73.1
- Local OS Version: Ubuntu 20.04.5 LTS
- Remote OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. I am going to the link provided when setting up the VS code server;
2. I am asked to login to Github;
3. I am asked to login to my personal account;
4. Getting the warning: "The request is blocked."

I am trying to acces the server through the browser at work, however the request is blocked. Why does this warning show up? I have the feeling that it is caused by my company blocking my personal e-mail account.

**Comment by eleanorjboyd** [comment]
Hello! Which link are you following when setting up the VS Code server and are you connecting to this server via SSH ? Also are you connecting from your local vs code or via github.dev? Finally does it say the request is blocked regarding your github account?
