### ISSUE TITLE
Test clean up of old agent processes in SSH

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#752]
Test https://github.com/microsoft/vscode-remote-release/issues/203

Please cover at least a debian-type distro host (like Ubuntu) and a red hat-type distro.

- [x] Windows @alexr00
- [x] Mac @sandy081
- [x] Linux @Tyriar

Complexity: 5

Use the Nightly SSH extension for testing (uninstall stable)

- If you have connected to this host before from the stable version of the ssh extension, run the "Kill VS Code Server on Host" command
- Using an external terminal (or vscode, but an external terminal might be easier the way these steps are written) connect to the host and check the number of folders in `~/.vscode-server-insiders/bin`.
  - If there are 5 or fewer, run `cp -r somecommit anything` a few times until there are more than 5 folders present
  - Then you can manipulate the new folder's modified date with `touch -t` because the ssh extension will try to delete all but the 5 newest folders.  Example, `touch -t 1903050709.12 <folder>` https://www.thegeekstuff.com/2012/11/linux-touch-command/
- Connect to the host using the nightly version of the ssh extension
- Check the log in the "Remote - SSH" output channel
- You should see lines like `Deleting old install from ...` for the oldest commits in `~/.vscode-server-insiders/bin`, and it should leave the 5 newest commits

Part 2
- Check the commit of vscode you are using, call it $C
- Quit vscode
- In an external terminal, check the processes still running from that commit like  `ps ax | grep $C`. The extension host should be gone. There should be 2 processes, server.sh and the node process (and grep)
- Wait 10 minutes
- The server process should have shut down automatically and it should no longer show up in `ps`

For any bugs you file, include the ssh log (Remote - SSH output channel) and the server log (at `~/.vscode-server-insiders/.commitid.log`

**Comment by alexr00** [comment]
I tested only on Ubuntu, not on red hat due to #794

**Comment by Tyriar** [comment]
I missed testing on red hat, will do today

**Comment by roblourens** [comment]
I just meant that among the 3 testers I wanted red hat covered by at least one. But it's broken so don't worry about that, Ubuntu is fine.
