### ISSUE TITLE
Test improved SSH binary discovery

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#753]
Test https://github.com/microsoft/vscode-remote-release/issues/448

Complexity: 3

- [x] Windows @deepak1556
- [x] Windows

Ensure that ssh can be found

- With the new ssh path setting
- On the path
- In the default windows 10 install location, if not on the path
- In the default git ssh install location, if not on the path

See the list of locations in https://github.com/microsoft/vscode-remote-release/issues/448

**Comment by jrieken** [comment]
This is a little hard to test because I don't wanna ruin my windows setup with all different ssh installs. Anyways, it does work with ssh on path and I did review the code for the paths mentioned in #448

**Comment by deepak1556** [comment]
Have tested all path combinations except for WSL
