### ISSUE TITLE
Extensions not loading

### ISSUE THREAD

**Issue by sungvzer** [microsoft/vscode-remote-release#7530]
- VSCode Version: 1.73.1
- Local OS Version: Windows 10 22H2
- Remote OS Version: Ubuntu 22.04.1 LTS
- Remote Extension/Connection Type: WSL
- Logs: 
    - [Log(Window)](https://pastebin.com/9vka7uYK)
    - [Log(Remote Extension Host)](https://pastebin.com/z29BK7tP)
    - [Log(emote Server)](https://pastebin.com/56k6PJif)

Steps to Reproduce:

1. Open a WSL Window
2. Open the extensions tab
3. The tab gets stuck in eternal loading of extensions. "Install in WSL:Ubuntu-22.04" doesn't work either. ![immagine](https://user-images.githubusercontent.com/52582911/201960157-94542127-85a4-4124-9d25-9e8e8efd1caf.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by sungvzer** [comment]
Unfortunately I fixed this by having to reinstall vscode and wsl, so I am not able to provide logs anymore.

**Comment by sandy081** [comment]
Glad that it is fixed for you. Please reopen it if you see it again and provide us the logs.

**Comment by Raibows** [comment]
I have the same issue as you, in https://github.com/microsoft/vscode/issues/168725. Is the only way left to fix it is to reinstall wsl2? 😭

**Comment by sungvzer** [comment]
I managed to fix it by reinstalling WSL yes.
Not even uninstalling the VSCode remote server worked, but I'm not sure if a full nuking of the distro is the only way to go or if there are other less destructive ways.
