### ISSUE TITLE
Remote explorer aggressively causes sign in

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-remote-release#7535]
@bamurtaugh noticed that if you:

1. Open vscode.dev when not signed in
2. Install a theme extension
3. Remote Tunnels will prompt for sign in ⁉️ 

This behavior goes away when disabling the remote explorer. I think that it's probably ending up trying to do some query for basis tunnels.

In general we should not trigger sign in automatically from the remote explorer, and instead show a "sign in to view tunnels" option in the tree view instead.

cc @eleanorjboyd

**Comment by connor4312** [comment]
ah, here's the issue.

I tried to repro this last week but was unable to. I think this got fixed in some of my auth refactoring work earlier. @bamurtaugh please let me know if you still encounter it.

**Comment by bamurtaugh** [comment]
Just tested the same flow mentioned above and I no longer saw the aggressive sign in prompt! Will let you know if I see it again in the future.
