### ISSUE TITLE
"Installation of vs code server fails. Please install wget or curl on the remote computer"

### ISSUE THREAD

**Issue by oconnor127** [microsoft/vscode-remote-release#7538]
I have an ARM64 Board without any outbound internet connection, where I want to develop remotely. 

Problem: The installation of a vs-code server (and therefore the remote-connection) keeps failing because of a missing outbound internet connection.

Is there any option to circumvent this?

**Comment by eleanorjboyd** [comment]
Hi! Please check out the setting `Remote.SSH: Local Server Download`. This setting sets whether the extension can download the VS Code Server on the client and transfer it to the host with scp, instead of downloading it on the host.
