### ISSUE TITLE
Test debugging web app in remote window

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#754]
Test https://github.com/microsoft/vscode-chrome-debug/issues/832

- [x] Windows @sbatten
- [x] Mac @chrmarti
- [x] Linux @aeschli

Complexity: 3

- On any type of remote, create a webapp with a launch config for Chrome. Starters: https://github.com/Microsoft/vscode-recipes#technology-scaffolding-tools
- Install the Chrome debug extension as a UI extension
- If needed, start the webserver and forward the port. Make sure the url in the launch config is correct for how the local machine needs to access the webapp
- Run the launch config
- Chrome should launch on the local machine and open your page
- You can set and hit breakpoints and do other debugger things

⚠️ There are a couple caveats that may keep breakpoints from binding for some project setups, see https://github.com/microsoft/vscode-chrome-debug#usage-with-remote-vs-code-extensions

If you see an issue it would help to try the same project in a local window. If you file an issue it would help to include the repo or setup steps.

**Comment by chrmarti** [comment]
Ping @roblourens on the TODO above. :)

**Comment by sbatten** [comment]
Double ping @roblourens

**Comment by roblourens** [comment]
Nooo I missed one. Wrote some steps
