### ISSUE TITLE
unregister vscode tunnels 

### ISSUE THREAD

**Issue by Goldn7799** [microsoft/vscode-remote-release#7541]
In tomorrow's extension build, there will be a context menu action for this:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/2230985/190263884-a2e0b548-7764-43c9-86a5-48295a3993e2.png">

_Originally posted by @connor4312 in https://github.com/microsoft/vscode-remote-release/issues/6942#issuecomment-1247310436_

How to i acces this menu

**Comment by connor4312** [comment]
By right clicking in the Remote Explorer view

**Comment by Goldn7799** [comment]
> By right clicking in the Remote Explorer view

i dont know, but Remote Explorer view is empty

**Comment by bamurtaugh** [comment]
> i dont know, but Remote Explorer view is empty

If the Remote Explorer view is empty, that means you don't have access to any remote machines. Have you run the VS Code Server on a remote machine before? Are you logged into the VS Code client where you're looking at the Remote Explorer?

**Comment by bamurtaugh** [comment]
Thanks for reporting this @7molP. Are you still experiencing an empty tunnel list in VS Code Stable after the latest release (which was last Wednesday)?

**Comment by 7molP** [comment]
> Thanks for reporting this @7molP. Are you still experiencing an empty tunnel list in VS Code Stable after the latest release (which was last Wednesday)?

No, I can see my remote machines now.
