### ISSUE TITLE
SSH Powershell: Cannot invoke method. Method invocation is supported only on core types in this language mode

### ISSUE THREAD

**Issue by dcharkes** [microsoft/vscode-remote-release#7546]
Type: <b>Bug</b>

When trying to connnect to a Windows machine through SSH, it fails with the following error.

```
[11:47:22.860] > U4NDhlNGE0OiByZXN1bWVMb2ciCm1haW4K')))); powershell -ExecutionPolicy Unrestricted -NoLogo -NoPr
[11:47:22.860] > ofile -NonInteractive -EncodedCommand `$remoteSSHConfiguration
[11:47:22.862] > Script"
[11:47:23.838] stderr> Cannot invoke method. Method invocation is supported only on core types in this language mode.
[11:47:23.838] stderr> At line:1 char:1
[11:47:23.839] stderr> + $remoteSSHConfigurationScript=[Convert]::ToBase64String([Text.Encodin ...
[11:47:23.839] stderr> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[11:47:23.839] stderr>     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
[11:47:23.839] stderr>     + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage
[11:47:23.839] stderr>  
[11:47:24.248] stderr> Cannot process the command because of a missing parameter. A command must follow -Command.
[11:47:24.287] > 
[11:47:24.288] > PowerShell[.exe] [-PSConsoleFile <file> | -Version <version>]
>     [-NoLogo] [-NoExit] [-Sta] [-Mta] [-NoProfile] [-NonInteractive]
>     [-InputFormat {Text | XML}] [-OutputFormat {Text | XML}]
>     [-WindowStyle <style>] [-EncodedCommand <Base64EncodedCommand>]
>     [-ConfigurationName <string>]
>     [-File <filePath> <args>] [-ExecutionPolicy <ExecutionPolicy>]
>     [-Command { - | <script-block> [-args <arg-array>]
>                   | <string> [<CommandParameters>] } ]
> 
```

The workaround mentioned in https://github.com/PowerShell/PowerShell/issues/17900 doesn't seem to work for the remote extension.

Extension version: 0.92.0
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:22:48.959Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (9.93GB free)|
|Process Argv|--crash-reporter-id 173adbb2-d181-42f1-90b2-c8210a4149b8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by dcharkes** [comment]
Possibly related:

* https://github.com/microsoft/vscode/issues/158548

**Comment by dcharkes** [comment]
Also happens in v0.93.2022111815.
Also in 0.88, 0.78, 0.68.

Also with VSCode 1.69.2 + this plugin 0.84.

It used to work before, I'm failing to reproduce that. I will try to see if any configuration on the Windows machine changed.

**Comment by dcharkes** [comment]
It's likely that my machine used to run in full language mode rather than constrained language mode.

```
>powershell.exe     
Windows PowerShell                                          
Copyright (C) Microsoft Corporation. All rights reserved.   
                                                            
Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\> $ExecutionContext.SessionState.LanguageMode
ConstrainedLanguage
```

**Comment by dcharkes** [comment]
@eleanorjboyd @Tyriar is it likely that the Remote-SSH into Windows machines will work in PowerShell constrained language mode (or without changing from the normal shell into PowerShell) in a future version?

**Comment by Tyriar** [comment]
Looks like this is an issue with the ssh resolver needing higher privileges

**Comment by roblourens** [comment]
Sorry, I'm not familiar with "constrained language mode", do you know why your machine is now running in this constrained mode?

**Comment by dcharkes** [comment]
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes?view=powershell-7.2

Why my machine is running it, corp policy.

**Comment by roblourens** [comment]
I'm not sure we can do anything about this, sorry, I think we just have to say that our script has to run in full language mode

**Comment by kcking** [comment]
I think the remote setup could work over SSH if the module is signed. As explained in https://devblogs.microsoft.com/powershell/powershell-constrained-language-mode/#then-what-is-it-for "all Powershell modules shipped with Windows are signed"

I imagine Microsoft would also likely run into this with their own employees using remote windows machines for development.

**Comment by roblourens** [comment]
I don't think we have the capability to deploy a signed powershell module over ssh with the way the install process currently works. However, sometime we will migrate from this powershell setup script to the new vscode CLI, and that should avoid this issue entirely.

**Comment by dcharkes** [comment]
> However, sometime we will migrate from this powershell setup script to the new vscode CLI, and that should avoid this issue entirely.

Is there a tracking issue for this?

**Comment by roblourens** [comment]
I opened this if you want something to subscribe to, https://github.com/microsoft/vscode-remote-release/issues/7870 but no ETA or other details currently, sorry
