### ISSUE TITLE
Trying to install VSCode Server on M1 Mac Mini, (Running monterey) fails.

### ISSUE THREAD

**Issue by tuksnesis** [microsoft/vscode-remote-release#7555]
Hello, running the wget -O- https://aka.ms/install-vscode-server/setup.sh | sh script responds with 

minituksnesis@reDevices-Mini ~ % wget -O- https://aka.ms/install-vscode-server/setup.sh | sh
--2022-11-21 14:06:58--  https://aka.ms/install-vscode-server/setup.sh
Resolving aka.ms (aka.ms)... 2.22.197.32
Connecting to aka.ms (aka.ms)|2.22.197.32|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://vscodeserverlauncher.blob.core.windows.net/builds/setup-scripts/setup.sh [following]
--2022-11-21 14:06:58--  https://vscodeserverlauncher.blob.core.windows.net/builds/setup-scripts/setup.sh
Resolving vscodeserverlauncher.blob.core.windows.net (vscodeserverlauncher.blob.core.windows.net)... 20.150.78.68
Connecting to vscodeserverlauncher.blob.core.windows.net (vscodeserverlauncher.blob.core.windows.net)|20.150.78.68|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1758 (1.7K) [text/x-sh]
Saving to: ‘STDOUT’

-                                            100%[===========================================================================================>]   1.72K  --.-KB/s    in 0s      

2022-11-21 14:06:59 (335 MB/s) - written to stdout [1758/1758]

Installing from https://aka.ms/vscode-server-launcher/aarch64-apple-darwin-signed
curl: (23) Failure writing output to destination
chown: /usr/local/bin/code-server: No such file or directory
chmod: /usr/local/bin/code-server: No such file or directory

Any ideas on what could be the issue here?

**Comment by alexrqs** [comment]
does it makes any difference if you manually create the folder?

**Comment by bamurtaugh** [comment]
Thanks for reporting!

We've made recent updates to how the VS Code Server runs with the [release](https://code.visualstudio.com/blogs/2022/12/07/remote-even-better) of the unified `code` CLI. I'll close this issue for now, but if you're still experiencing issues, please just let us know.
