### ISSUE TITLE
No scroll for Apple Magic Keyboard trackpad

### ISSUE THREAD

**Issue by tsingh-twist** [microsoft/vscode-remote-release#7563]
- VSCode Version:20220909.27
- Local OS Version:Windows 11
- Remote OS Version:iPad OS
- Remote Extension/Connection Type: SSH/Containers/WSL/Server
- Logs:

Steps to Reproduce:

1. Run code-server on Windows
2. Launch url on iPad in either chrome or safari.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by icouldonlygetthisname** [comment]
I've noticed the scroll bars don't render correctly, and it's best to use the arrow keys. Also, there's no scroll in the terminal, which is annoying.

**Comment by tsingh-twist** [comment]
More infuriatingly there is no issue in using GitHub codespaces on iPad with Magic Keyboard. The editor scroll works flawlessly with the trackpad on codespaces. Do clearly there is an issue for code-server unable to handle trackpad input for scroll and what is means is we as users are being punished to go that extra mile, install and configure code server and try to code on iPad os, where as we could have simply gone to codespaces for free, and just start using it without going through the headache of self hosting

**Comment by tsingh-twist** [comment]
Hey code-server Eva, can we as early adopters be not punished as much as much as we are. You good really pushed out on your videos with iPad as the central computing device, not only you fail there the most, as a team you incoherently refuse to fix the issues

**Comment by pedromzadeh** [comment]
I also have this issue and my setup is the same as that in the original issue. A fix would be very much appreciated. 

I do want to point out that the current fix is to toggle on `shortcuts` in the keyboard section of iOS settings. With this attribute toggled on, you can click on a text window and use the trackpad to scroll. This is super annoying however, for two reasons 
1. I don’t want the keyboard shortcuts to appear when I have a physical keyboard attached. 
2. I shouldn’t need to tap on a window to _activate_ it for the scrolling to work. 

I imagine this is an issue with the WebKit interface but I know nothing about that. Hoping the symptoms here lead to the issue and a speedy fix. This really affects workflow.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/164220
