### ISSUE TITLE
Unknown network traffic from vscode-remote server to AWS IPs

### ISSUE THREAD

**Issue by liamgib** [microsoft/vscode-remote-release#7568]
- VSCode Version: 1.73.1
- Local OS Version: Windows_NT x64 (10.0.22621)
- Remote OS Version:  Ubuntu 22.04.1 LTS
- Remote Extension/Connection Type: SSH
- Logs: 

Steps to Reproduce:
1. Upgrade to latest VS Code
2. Connect to Remote Server via SSH
3. Record network traffic outgoing on destination port 4318:
watch lsof -nPi tcp:4318 > records.txt

Due to the use of watch, the records file will be unformatted but once it detects the connection you will see the record on a new line. 
As an example, the line will look like so:
node    4097  /user/ 35u  IPv4 1312875383[47G0t0  TCP /internal-ip/:38708->34.225.141.207:4318 (SYN_SENT)

When we look up the destination IPs, we can see they're AWS IPs which has raised the concern as it would be assumed that if these are for telemetry they'd be hosted on Microsoft. It's known that port 4318 is used for Open Telemetry, but we wouldn't expect the network of Vscode telemetry to be initiated from the remote server itself.

Because of this change, it has been getting blocked by our corporate firewall.

A few of the destination IPs include,
34.225.141.207
54.243.205.170
54.175.105.210
 
 It's important to note, this has only started since the last release on the 18th~
 
 
 I would assume that this would be some sort of A record with multiple values. 
 
 **If this is not a bug, could you please confirm this is VSCode Telemetry along with the domain used?**
 

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by lramos15** [comment]
Is there any traffic going to these IPs? Like is there a telemetry payload being sent or just a handshake?

I'm trying to find out where these IPs are coming from as we only configure the SDKs to send to `https://mobile.events.data.microsoft.com/OneCollector/1.0`

**Comment by liamgib** [comment]
Hi @lramos15,

This traffic is currently being blocked by our firewall, but I would assume it would've intended to send a payload after TCP handshake. 

To provide some additional information, we identified the PID that was initiating the connection.

```user       4097  0.7  1.7 1126664 280528 ?      Sl   10:49   1:12 /home/user/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/node /home/user/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/bootstrap-fork --type=extensionHost --transformURIs --useHostProxy=false```


I am assuming that the "6261075646f055b99068d3688932416f2346dd3b" folder is version of the vscode-server. It wasn't happening on users using the previous version of Vscode, and the folder was only added once upgrading. 

Happy to provide any diagnostics information you might require. 

It's unclear right now, but it looks like turning off telemetry stops the traffic.

**Comment by lramos15** [comment]
This is the remote extension host which hosts all your extensions. What extensions do you have installed besides remote SSH? Can you try disabling them all besides remote SSH and see if the IPs still appear?

**Comment by liamgib** [comment]
Hi @lramos15,

It took some time, but we've identified the extension.
https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

Ever since the following change, even though telemetry data is turned off for the extension it still sends telemetry data.
https://github.com/redhat-developer/vscode-yaml/pull/845

If we turn off telemetry for all of vscode, it will stop the traffic.
It really shouldn't be sending telemetry when it's not enabled at the extension level, so will raise an issue on that repo.

**Comment by lramos15** [comment]
Glad you figured it out @liamgib, feel free to file an issue on their repo of course as we cannot control what other extensions do.

As for if telemetry data started getting sent from the remote the answer is that it has always been sent from the remote in core VS Code. It's based on where the extension is running from. There haven't been any major changes to the telemetry architecture last release. We try our best to be transparent about everything happening via the telemetry output logs. Here's the code for the remote telemetry service if you're interested. https://github.com/microsoft/vscode/blob/959c8b024c73af436700e17cb43753be4be80aa3/src/vs/platform/telemetry/common/serverTelemetryService.ts
