### ISSUE TITLE
devcontainer.json not loading custom localEnv values correctly using WSL2 

### ISSUE THREAD

**Issue by KUGA2** [microsoft/vscode-remote-release#7570]
- VSCode Version: 1.73.1
- Local OS Version: Windows + wsl2 (debian bullseye)
- Remote OS Version: debian bullseye
- Remote Extension/Connection Type: SSH/**Containers**/WSL/Server
- Logs:

Steps to Reproduce:

1. open wsl shell
2. start code form wsl
3. Open in devcontainer   (devcontainer.json has:   `"initializeCommand": "echo localEnv:HTTP_PROXY=${localEnv:HTTP_PROXY}"`)
4. The variable is Empty. Logged: `localEnv:HTTP_PROXY=`

I know this is a duplicate to #3456, but it does not work and it is closed. I set the environment varible in `/etc/environment`, in `/etc/profile.d/`, in `~/.profile` and in `~/.bashrc`, nothing help. Even in `~/.vscode-server/server-env-setup` (as seen in `ms-vscode-remote.remote-wsl-0.72.0\scripts\wslServer.sh`) nothing seems to help.

@chrmarti: you closed the linked issue, could you have a look here?

Special problem that derives from this (for google searchers): Extensions in devcontainer.json cannot be installed.

**Comment by chrmarti** [comment]
Could you append the full log from opening the dev container? Does `${localEnv:PATH}` work?

**Comment by KUGA2** [comment]
In wsl2 shell:
```
CENSORED@PC18989:~$ echo $PATH
/opt/git-subrepo/lib:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/WindowsApps/Microsoft.WindowsTerminal_1.15.2874.0_x64__8wekyb3d8bbwe:/mnt/c/Program Files/Microsoft MPI/Bin/:/mnt/c/Perl/bin/:/mnt/c/Python37/Scripts/:/mnt/c/Python37/:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS/:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS/:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files (x86)/WebEx/Productivity Tools:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Microsoft SQL Server/110/Tools/Binn/:/mnt/c/Program Files (x86)/Microsoft SDKs/TypeScript/1.0/:/mnt/c/Program Files/Microsoft SQL Server/120/Tools/Binn/:/mnt/c/Users/ramold/.dnx/bin:/mnt/c/Program Files/Microsoft DNX/Dnvm/:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Program Files/Java/jdk1.8.0_201/bin:/mnt/c/Program Files/Intel/WiFi/bin/:/mnt/c/Program Files/Common Files/Intel/WirelessCommon/:/mnt/c/Program Files/gnuplot/bin:/mnt/c/Program Files/OpenJDK/jdk-12.0.2/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/LLVM/bin:/mnt/c/Program Files/OpenJDK/openjdk-11.0.7_10/bin:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Program Files/dotnet/:/mnt/c/tools/BCURRAN3:/mnt/c/Program Files/Git/cmd:/mnt/c/Ruby27-x64/bin:/mnt/c/Users/ramold/scoop/shims:/mnt/c/Users/ramold/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/kdiff3:/mnt/c/Users/ramold/AppData/Local/Pandoc/:/mnt/d/vagrant/VirtualBox:/mnt/c/Program Files (x86)/Nmap:/mnt/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin:/mnt/d/git/platform_rts/Scripts/build_resources:/mnt/c/Users/ramold/.dotnet/tools:/mnt/c/Users/ramold/.dotnet/tools:/mnt/c/Users/ramold/AppData/Roaming/Code/User/globalStorage/ms-vscode-remote.remote-containers/cli-bin:/mnt/c/Users/ramold/.dotnet/tools
CENSORED@PC18989:~$ echo $HTTPS_PROXY
http://proxy1.CENSORED.int.CENSORED.com:80
CENSORED@PC18989:~$ cat /etc/environment | grep HTTPS_PROXY
HTTPS_PROXY="http://proxy1.CENSORED.int.CENSORED.com:80"
CENSORED@PC18989:~$ cat /etc/profile.d/02-proxy.sh | grep HTTPS_PROXY
HTTPS_PROXY="http://proxy1.CENSORED.int.CENSORED.com:80"
CENSORED@PC18989:~$ cat ~/.profile | grep HTTPS_PROXY
HTTPS_PROXY="http://proxy1.CENSORED.int.CENSORED.com:80"
CENSORED@PC18989:~$ cat ~/.bashrc | grep -n proxy
5:. /etc/profile.d/02-proxy.sh
CENSORED@PC18989:~$ code git/CENSORED_os_hardware_description/
```

Edit devcontainer.json add:

```
  "initializeCommand": "echo localEnv:HTTP_PROXY=${localEnv:HTTP_PROXY}",
  "onCreateCommand": "echo localEnv:HTTP_PROXY=${localEnv:HTTP_PROXY}",
  "postCreateCommand": "echo localEnv:HTTP_PROXY=${localEnv:HTTP_PROXY}",
  "postStartCommand": "echo localEnv:HTTP_PROXY=${localEnv:HTTP_PROXY}",
  "postAttachCommand": "echo localEnv:HTTP_PROXY=${localEnv:HTTP_PROXY}",
```
  

F1 -> Rebuild and Reopen in Container
Logs "Dev Container" and "Configuring...".
[HTTPS_PROXY_Devcontainers.txt](https://github.com/microsoft/vscode-remote-release/files/10167920/HTTPS_PROXY_Devcontainers.txt)
[HTTPS_PROXY_configuring.txt](https://github.com/microsoft/vscode-remote-release/files/10167921/HTTPS_PROXY_configuring.txt)
Note: The HTTPS_PROXY at [8572 ms] Start: Run: is hard coded since referencing the local env did not work.

Then the same for PATH (but in quotes cause there are spaces).
[PATH_configuring.txt](https://github.com/microsoft/vscode-remote-release/files/10167927/PATH_configuring.txt)
[PATH_Devcontainers.txt](https://github.com/microsoft/vscode-remote-release/files/10167928/PATH_Devcontainers.txt)

**Comment by chrmarti** [comment]
It seems to work with PATH. Could you retry with trace logging enabled in the user settings and post the log again?
<img width="355" alt="image" src="https://user-images.githubusercontent.com/9205389/207540470-056a0b33-2138-4a3d-b240-331e3838d3f5.png">

**Comment by KUGA2** [comment]
Closing this after just 1 week? Right around Christmas? I was not in the office for a few days and I cannot reproduce this from homeoffice.

However, now here are the logs with TRACE enabled. I hope you can find the problem in there.
[TRACE_PATH_configuring.txt](https://github.com/microsoft/vscode-remote-release/files/10288222/TRACE_PATH_configuring.txt)
[TRACE_PATH_Devcontainers.txt](https://github.com/microsoft/vscode-remote-release/files/10288223/TRACE_PATH_Devcontainers.txt)
[TRACE_HTTPS_PROXY_configuring.txt](https://github.com/microsoft/vscode-remote-release/files/10288224/TRACE_HTTPS_PROXY_configuring.txt)
[TRACE_HTTPS_PROXY_Devcontainers.txt](https://github.com/microsoft/vscode-remote-release/files/10288226/TRACE_HTTPS_PROXY_Devcontainers.txt)

PS: I think the logs are not complete now. The terminal buffer run over. Please tell me if I need to repeat this (and with witch setting)
