### ISSUE TITLE
Can't install the remote ssh server on a Debian 64bit machine

### ISSUE THREAD

**Issue by Suniron** [microsoft/vscode-remote-release#7574]
- VSCode Version: **1.73.1**
- Local OS Version: **Windows 11** (and Ubuntu 22.04 in WSL but i'm using Windows to make the remote server connection)
- Remote OS Version: **5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64**
- Remote Extension/Connection Type: **SSH**
- Logs:
```
[13:39:08.146] > 
> main: line 221: millis: command not found
> 1f7319867716%%2%%
> tar --version:
> tar (GNU tar) 1.34
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>. 
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
> tar: This does not look like a tar archive
> 
> gzip: stdin: unexpected end of file
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> main: line 228: elapsed: command not found
> ERROR: tar exited with non-0 exit code: 0
[13:39:08.171] > 
> main: line 160: fail_with_exitcode: command not found
[13:39:09.465] "install" terminal command done
[13:39:09.466] Install terminal quit with output: main: line 160: fail_with_exitcode: command not found
[13:39:09.466] Received install output: main: line 160: fail_with_exitcode: command not found
[13:39:09.467] Failed to parse remote port from server output
[13:39:09.469] Resolver error: Error: 
	at g.Create (c:\Users\etien\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:583821)
	at t.handleInstallOutput (c:\Users\etien\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:582473)
	at t.tryInstall (c:\Users\etien\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:679811)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\etien\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:642614
	at async t.withShowDetailsEvent (c:\Users\etien\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:645932)
	at async t.resolve (c:\Users\etien\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:643664)
	at async c:\Users\etien\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:722342
[13:39:09.479] ------
```

I tried to reinstall the app or remove the `.vscode-server` and `vscode-server.tar.gz` on remote but it's not resolved.. :(

**Comment by eleanorjboyd** [comment]
Hello! Could you please provide the entire remote-ssh logs? The whole logs includes some settings and output which are helpful to the debugging process. Thanks!

**Comment by Suniron** [comment]
>  Hello! Could you please provide the entire remote-ssh logs? The whole logs includes some settings and output which are helpful to the debugging process. Thanks!

Sûre, but the log is more than 2 500 000 chars 😅.

How can I share you this big log ?

Also, the problem is the same from another host computer (windows 10) 😏

**Comment by eleanorjboyd** [comment]
Are these the logs from the remote-ssh tab for output? They do not look familiar in their format to how we print out our logs. Additionally are you running a stable and authorized build of VS Code from off of our site here: https://code.visualstudio.com/download?

**Comment by Suniron** [comment]
Yes, I'm using the offical and stable Release only..

For the logs, it's from the remote ssh tab.

Le lun. 28 nov. 2022, 17:45, Eleanor Boyd ***@***.***> a
écrit :

**Comment by eleanorjboyd** [comment]
Hello! Do you have bash installed? Secondly do you have bash aliased to zsh? It seems part but not all of our script was run using zsh instead of bash. Additionally do you have any firewalls installed on your remote server? These firewalls can also truncate our install script.

**Comment by Suniron** [comment]
I uploaded antoher log file from my other host computer: https://raw.githubusercontent.com/Suniron/vscode-remote-ssh-error/main/logsFromAnotherHost

1) I have bash which call zs: if i send "bash" in terminal, i'll see only zsh.
2) I'm using [yunohost](https://yunohost.org/) on my server, so there is a firewall. I tried to install vscode server manually (and create a `0` file in the `bin/:commit` folder) to avoid a network error.

**Comment by eleanorjboyd** [comment]
Hi! So the remote-ssh extension needs bash to run so if you could change your setup so bash does not call zsh then that might fix the problem. Thanks!

**Comment by Suniron** [comment]
Ooooh thank's for the tips !

I called `zsh` from my `.bashrc`, it was the problem!

Big thank's for your reactivity 😊

**Comment by eleanorjboyd** [comment]
Happy to help! Glad we caught the issue
