### ISSUE TITLE
VS Code Web can't open as a PWA app when running at serve-local mode.

### ISSUE THREAD

**Issue by Arrow-Li** [microsoft/vscode-remote-release#7576]
- VSCode Version: VS Code Server 20220909.27
- Local OS Version: iOS 14.2.1
- Remote OS Version: CentOS 7
- Remote Extension/Connection Type: Server
- Logs: None

Problem:
I running vs code server on my server and use link `http://10.0.1.xx/?tkn=****` to visit with safari, but if add this page to home screen(PWA), this not work, show a white screen with **Forbidden** message.

https://user-images.githubusercontent.com/17962902/204205605-95d47904-0f18-4a32-9fad-1b6b36583021.MP4

Steps to Reproduce:

1. Add to Home Screen in Safari
2. Open it

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by aeschli** [comment]
code-server as been superceeded by VS Code tunnels. This is not a scenario we support yet.
