### ISSUE TITLE
Tunnel not opening from ipad os/android code-server when converted to WPA

### ISSUE THREAD

**Issue by kristsm** [microsoft/vscode-remote-release#7577]
- VSCode Version:  VS Code Server 20220909.27
- Local OS Version: Fedora 37
- Remote OS Version: Ipad OS 15 / Android
- Remote Extension/Connection Type: SSH/Containers/WSL/Server
- Logs:

Steps to Reproduce:

1. Tunnel is opening fine in the Ipad OS 15 Safari/Android MS Edge/Chrome browser windows (but not when converted to PWA);
2. Convert code-server instance to PWA from Ipad OS 15 Safari browser (install app) or Android Microsoft Edge / Chrome browser (install app);
3. PWA is installed, it opens connection to code-server, but when requesting to open Tunnel to code-server instance, the instance shows in the list, but nothing happens after selecting the respective tunnel. Although, PWA does not open default code-server tunnel even if the tunnel was running before fine in the browser.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by connor4312** [comment]
We recently updated lots of things and released [VS Code Tunnels](https://code.visualstudio.com/docs/remote/tunnels). Please let us know if you reproduce it on there.
