### ISSUE TITLE
Prompt to rebuild on reload if devcontainer.json or associated Dockerfile/compose files have been updated

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#758]
A few people I have talked to have mentioned that they find themselves forgetting to rebuild their container(s) after modifying `devcontainer.json` or the related `Dockerfile` or `docker-compose.yml`.  This is particularly easy to forget if you are making small edits.  I admit I have done this myself.

While it could be annoying to prompt to rebuild on every edit or save, it might make sense to ask if the container should be rebuilt when container is reopened since this is a less frequent operation.

//cc: @chrimarti - Does this make sense to you as well?

**Comment by dilin-MS** [comment]
Our [Azure IoT Device Workbench](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-iot-workbench) is integrating containerization mechanism leveraging the vscode remote extension. 
In our scenario, we will scaffold project files which include a `.devcontainer` directory containing `Dockerfile` and `devcontainer.json` file. 
>.devcontainer
├── Dockerfile
└── devcontainer.json

The user can develop their application in the container built from the Dockerfile. We also want to allow user to modify the Dockerfile adding their customized configurations. So  we are in need of this **prompt on reload** feature to rebuild docker image when Dockerfile is modified. It's okay to prompt rebuild when reload project.

Looking forward to the feature.
