### ISSUE TITLE
Test: Consume bundled devcontainer CLI

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#7580]
Refs: https://github.com/microsoft/vscode-remote-release/issues/7508

- [x] anyOS @daviddossett
- [x] anyOS @dbaeumer
- [x] anyOS @brettcannon (Optional)

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%237580%0A%0A&assignees=chrmarti)

---

- Install the Dev Containers extension (0.265.0-pre-release or later).
- Check `~/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-*/dist/spec-node` contains a single minified JavaScript file.

**Comment by daviddossett** [comment]
Looks good 👍
