### ISSUE TITLE
Test: Support for cygwin/mingw unix socket files

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#7587]
Refs: https://github.com/devcontainers/cli/issues/62

- [x] windows @aeschli (didn't work for me: see https://github.com/microsoft/vscode-remote-release/issues/7601)
- [x] windows @joyceerhl (also didn't work for me due to the same issue ^)

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%237587%0A%0A&assignees=chrmarti)

---

With the Dev Containers extension (0.265.0-pre-release or later):

Use the mingw (e.g. installed with Git for Windows) ssh-agent or Cygwin's ssh-agent and verify that it is successfully forwarded into a dev container with ssh installed.
- Make sure `SSH_AUTH_SOCK` is set when starting VS Code. (See instructions below.)
- Check `ssh-add -l` in a terminal of a local VS Code window shows some keys (otherwise add some).
- Check that in a dev container with ssh installed `ssh-add -l` shows the same keys. (See devcontainer.json below.)
- If you have a key registered with GitHub try `git clone` with an ssh connection string (can be copied from the GitHub Clone UI).
- If you have a key registered with an ssh server, try to `ssh` to it.

Note that when `SSH_AUTH_SOCK` is not set the extension will try to use the built-in ssh-agent's default socket, so maybe turn off the ssh-agent service in Windows to make sure you're not inadvertently using that instead of the mingw/cygwin one. (You can check in Windows Services. The default for it is to not automatically start.)

---

#### Minimal `.devcontainer/devcontainer.json` for testing

```json
{
	"image": "mcr.microsoft.com/devcontainers/base:jammy"
}
```

---

#### `SSH_AUTH_SOCK` setup

Open Git Bash (Mingw's Bash) or Cygwin's Bash (depending on which you use for testing) and add the following to `~/.bash_profile` (create with this content if it does not exist yet):
```sh
SSH_ENV="$HOME/.ssh/agent-environment"

function start_agent {
    echo "Initialising new SSH agent..."
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add;
}

# Source SSH settings, if applicable

if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    #ps ${SSH_AGENT_PID} doesn't work under cywgin
    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
        start_agent;
    }
else
    start_agent;
fi
```

Reopen Bash (this might ask for a passphrase now) and check `ssh-add -l` shows some key.

Start VS Code from this Bash session for testing.

**Comment by aeschli** [comment]
I remove myself from the item as testing came to a stop due to #7601. Please add me back if this can be fully tested.
