### ISSUE TITLE
can't find Add Container Configuration File option 

### ISSUE THREAD

**Issue by dreamrororo20** [microsoft/vscode-remote-release#759]
- VSCode Version:1.35
- Local OS Version: 10.14  
- Remote OS Version:  CentOS Linux release 7.6.1810 (Core)
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:
I read docs https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host,but i can not find "Remote-Containers: Add Container Configuration File..." option
![image](https://user-images.githubusercontent.com/49423837/59893295-150b6780-940f-11e9-9e0f-38d5c8e65fa1.png)

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by Chuxel** [comment]
@dreamrororo20 You might have missed step 2

> Create and open a local empty folder in VS Code.

If you do not have a folder open, you will not be able to add any files.
