### ISSUE TITLE
Docker installed for Windows machines errors without WSL

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-remote-release#7590]
Installing Docker Desktop through the remote extension notification doesn't go smoothly, when on a Windows machine without WSL.

VS Code / the extension didn’t warn me about this, and I only found out when I kept getting the “Docker Desktop stopped…” error from the Docker Desktop app after installation.

Seems like the docs also need to be updated to include WSL installation as a prereq for Windows machines: https://code.visualstudio.com/docs/devcontainers/tutorial

**Comment by chrmarti** [comment]
https://docs.docker.com/desktop/windows/wsl/ suggests that Docker Desktop would prompt you, but I guess that did not happen?
