### ISSUE TITLE
Add "Configure Container Features" command to the list of drop down for remote indicator

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-remote-release#7591]
I tried clicking on the remote indicator on the bottom left, and expected to see “Configure Container Features…” command as one of the list in the drop down so that I can add features to my container (seems like an intuitive place for me).

**Comment by chrmarti** [comment]
Superseded by the work to streamline the remote indicator menu: https://github.com/microsoft/vscode-remote-release/issues/8018
