### ISSUE TITLE
Alt + click is not working

### ISSUE THREAD

**Issue by RainboWu** [microsoft/vscode-remote-release#7596]
Type: <b>Bug</b>

can't open remote dirs since vs code 1.73

Extension version: 0.1.2022112409
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T03:54:53.913Z)
OS version: Linux x64 5.17.0-1021-oem
Modes:
Sandboxed: No
Remote OS version: Linux x64 3.10.0-693.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900T (24 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 1|
|Memory (System)|62.50GB (56.85GB free)|
|Process Argv|--unity-launch --crash-reporter-id adc64e8b-a615-4401-8b28-597a7c62f9e0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.10.234|
|OS|Linux x64 3.10.0-693.el7.x86_64|
|CPUs|AMD EPYC 7551 32-Core Processor (128 x 2000)|
|Memory (System)|251.70GB (158.12GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Where do you Alt + Click? Would a screenshot help?
