### ISSUE TITLE
VS Code Web Terminal not showing in Safari

### ISSUE THREAD

**Issue by Arrow-Li** [microsoft/vscode-remote-release#7598]
- VSCode Version: VS Code Server 20220909.27
- Local OS Version: Safari 15.2 (17612.3.6.1.6)
- Remote OS Version: CentOS 7
- Remote Extension/Connection Type: Server
- Logs: None

--------

+ Safari not showing terminal
![123213](https://user-images.githubusercontent.com/17962902/204426507-55898250-b947-46b3-9aa5-9bb192e8f27f.jpg)

+ Firefox is ok
![1232121](https://user-images.githubusercontent.com/17962902/204426639-7e1b7f3a-6e35-407a-93e4-acf1d98effb1.jpg)

Steps to Reproduce:

1. Open Terminal

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
@Arrow-Li looks like the server version is from September, can you update it and try again?

**Comment by Arrow-Li** [comment]
> 

No update.
<img width="244" alt="Screen Shot 2022-12-01 at 17 46 07" src="https://user-images.githubusercontent.com/17962902/205020414-3f4d31ed-f43e-4a93-8efc-d55306d77255.png">

**Comment by Tyriar** [comment]
@connor4312 please provide instructions to update when you can

**Comment by icouldonlygetthisname** [comment]
I am in the same position. The workaround I have is to use Blink shell, but being able to update would be great 🙂

**Comment by connor4312** [comment]
This works for me in Safari on Ventura, version 16.1. Can you try updating your browser version and letting us know if the problem persists?

**Comment by Arrow-Li** [comment]
> 

@connor4312 I can't update Safari because I don't want to update my macOS or iOS version either.

**Comment by icouldonlygetthisname** [comment]
@connor4312 those work for me, the other question is I am on VS Code Server 20220909.27 is that the latest? update does nothing, I want the server to run as a service :)

**Comment by connor4312** [comment]
It sounds like updating the browser solves this problem, so I will close this issue.

> I am on VS Code Server 20220909.27 is that the latest? update does nothing, I want the server to run as a service :)

Today we are (re) releasing this feature as Remote Tunnels in VS Code stable. Check out the "Remote Tunnels" section of https://code.visualstudio.com/updates/v1_74. This should be released in about 2 hours.

**Comment by Arrow-Li** [comment]
> It sounds like updating the browser solves this problem, so I will close this issue.
> 
> > I am on VS Code Server 20220909.27 is that the latest? update does nothing, I want the server to run as a service :)
> 
> Today we are (re) releasing this feature as Remote Tunnels in VS Code stable. Check out the "Remote Tunnels" section of https://code.visualstudio.com/updates/v1_74. This should be released in about 2 hours.

For anyone who can not update browser, don't want to fix this problem?
