### ISSUE TITLE
Failed to connect to Ubuntu 16.04 SSH server

### ISSUE THREAD

**Issue by superm1** [Microsoft/vscode-remote-release#76]
- VSCode Version: 1.34.0-insider (user setup)
- Local OS Version: Windows 10, 1803
- Remote OS Version: Ubuntu 16.04.3
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Configure `C:\users\<user>\.ssh\config`
2. Click the button to launch new window with remote.
3. Receive error prompt.  Below is in debugging log:

```
SSH Resolver called for "ssh-remote+serverman"
SSH Resolver called for host: serverman
Setting up SSH remote "serverman"
Using commit id "473af338e1bd9ad4d9853933da1cd9d5d9e07dc9" and quality "insider" for server
Install and start server if needed
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-112-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
> 830 packages can be updated.
> 0 updates are security updates.
> 
> 
> *** /dev/sda1 will be checked for errors at next reboot ***
> *** /dev/sda1 will be checked for errors at next reboot ***
> 
> No mail.
> bash: cannot set terminal process group (3717): Inappropriate ioctl for device
> bash: no job control in this shell
> 
> Installing...
> 
> Downloading with wget
> 
> Unable to establish SSL connection.
> 
> ef32d250-bb04-4890-8f88-ccd4d68f4895##25##
> 
"install" terminal command done
Received install output: ef32d250-bb04-4890-8f88-ccd4d68f4895##25##
Server download failed
Downloading VS Code Server failed. Please try again later.

```

Does this issue occur when you try this locally?: Can't check, it's SSH...
Does this issue occur when you try this locally and all extensions are disabled?: I only installed settings sync and this extension in insiders.

**Comment by superm1** [comment]
I found that if I set up my bashrc to configure a proxy in advance I could connect..

**Comment by TheStoof** [comment]
> I found that if I set up my bashrc to configure a proxy in advance I could connect..

Can you share the deets?

**Comment by superm1** [comment]
1. I set up CNTLM with my necessary credentials, and configured it to listen on localhost:8123.
2. Add this to my bashrc:
```
function proxy_on() {
        export https_proxy='http://127.0.0.1:8123'
        export http_proxy='http://127.0.0.1:8123'
}

function proxy_off() {
        unset https_proxy
        unset http_proxy
}
proxy_on
```

Specifically done that way so I can turn on/off proxy when needed with a simple command.
