### ISSUE TITLE
Remote wakatime fail

### ISSUE THREAD

**Issue by Wheeeeeeeeels** [microsoft/vscode-remote-release#7600]
- VSCode Version:
- Local OS Version:
- Remote OS Version:
- Remote Extension/Connection Type: SSH/Containers/WSL/Server
- Logs:

Steps to Reproduce:

1.  install waka time plugins on the visual studio code
2. then the wakatime can not figure the time. (only on some server can done)

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
This sounds like an issue with the extension. Could you file an issue for them? Thanks.
