### ISSUE TITLE
Call windows executable from remote SSH session

### ISSUE THREAD

**Issue by juxeii** [microsoft/vscode-remote-release#7602]
I am connected to a linux server via a remote SSH session under Windows. Is it somehow possible to call an executable from Windows?
For example: I am currently working on an extension and would like to start Notepad++ with two files from the remote linux machine. Is it possible to have the Windows system also available while working remotely?

How would a call to an .exe look like?

**Comment by eleanorjboyd** [comment]
Hello! Currently this is not possible, and would only work with an extension that could communicate between a server and a client. I think this document might help provide additional information about the area you are investigating. Thanks! https://code.visualstudio.com/api/advanced-topics/remote-extensions

**Comment by juxeii** [comment]
Thx for the information.
