### ISSUE TITLE
Remote over https / reverse SSH tunnel?

### ISSUE THREAD

**Issue by dobos** [microsoft/vscode-remote-release#7604]
I would like to use vscode for remote development on a server that has no internet facing SSH connection. This is a scientific platform that can be used to access jupyterlap in a browser but otherwise just provides a containerized linux environment. When I open a terminal from jupyter I can make SSH connections to the outside world and I can also establish an SSH tunnel to my desktop machine. Is there a way to manually start a vscode server on the remote machine and trick the local client into using the SSH tunnel I set up manually? I also know that vscode can connect to Azure Machine Learning without an SSH connection. Does that connection use SSL/https? Is establishing a connection like that possible (without the Azure API)?

**Comment by eleanorjboyd** [comment]
Hello! Apologies, I thought I responded to this but must have forgot to submit the comment. Did you explore the setting: `"remote.SSH.localServerDownload"`? This might be what you need for a server with no internet. Let me know if this doesn't work or I misunderstood your problem so I know to look into it further. Thanks!
