### ISSUE TITLE
WSL extension should not sync to macOS

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#7606]
For testing I had to enable settings sync from my testing Windows machine to my main macOS machine. When I checked what my macOS machine got, I noticed that WSL was now installed. Imho that should be a platform specific extension (Windows only) that should not sync to my macOS machine.

**Comment by aeschli** [comment]
The WSL extension does not add any functionality when on the Mac or Linux. No real harm when synchronizing.

**Comment by aeschli** [comment]
No plans to work on this
