### ISSUE TITLE
Wording: trust feature from ...

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-remote-release#7609]
Testing #7581

<img width="615" alt="image" src="https://user-images.githubusercontent.com/876920/204673815-41de3821-9fa1-4d1e-a56e-d2bf954633d1.png">

It took me a while to realize that `owner/organization` is referring to `GitHub`. I wonder if the wording can be simply as "Trust {} from GitHub"

**Comment by chrmarti** [comment]
Maybe with an @:
```
Trust dev-containers-contrib from GitHub

Trust dev-containers-contrib GitHub owner/organization(s)

Trust @dev-containers-contrib from GitHub
```

@bamurtaugh Do you have any advise on the wording here?

**Comment by bamurtaugh** [comment]
I like the third option you mention @chrmarti - `Trust @dev-containers-contrib from GitHub`.

The text prefilled in the quick pick (`Some features are from...`) already mentions that GitHub is the owner/organization, so I think it's okay not to mention owner/organization again. 

One other idea is `Trust @dev-containers-contrib` `Owner/organization: GitHub`. That to me makes it clearer that GitHub is the owner.

**Comment by chrmarti** [comment]
I like the brevity:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/9205389/205017871-747d0d5d-9c04-46f2-99b8-74e466e489a0.png">
