### ISSUE TITLE
VS Code removes double quotes in `.ssh/config` when using the "Add new SSH Host" dialog

### ISSUE THREAD

**Issue by hakontonne** [microsoft/vscode-remote-release#7611]
This bug was discovered when fixing [this bug](https://github.com/gravitational/teleport/issues/18424) in Teleport. 
If the `.ssh/config` file contains any double quotes in its `ProxyCommand`, it is removed when VS Code adds a new host to the config file. 

- VSCode Version: 1.73.1
- Local OS Version: MacOS 12.6.1
- Remote OS Version: Amazon Linux 2
- Remote Extension/Connection Type: SSH
- Logs: Not relevant

Steps to Reproduce:

1. Ensure you have a working config with double quotes in the `ProxyCommand` of a host your gonna connect to. Check out [this bug](https://github.com/gravitational/teleport/issues/18424) if you need an example. 
2. Add the host to VS Code using the "Add new SSH Host" dialog, save to the same `.ssh/config` as the double quoted `ProxyCommand`. 
3. Attempt to connect, it should fail if the double quotes are required. 

Opening the `.ssh/config` and adding back the double quotes will fix the connection to the host. 

While I think this an obscure bug that affects few people, its a bit concerning that VS Code deletes quotes in an unrelated line in the `.ssh/config` file. 

I'll be happy to provide screenshots and more to demonstrate the bug.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No, this is a bug in the SSH extension

**Comment by eleanorjboyd** [comment]
Hello @hakontonne, thank you for filing this bug. To confirm the behavior, when you have double quotes in "Add new SSH Host", and after entering you check your config and these double quotes no longer exist correct? Then if you modify directly in the ssh config file to add double quotes it adds as expected?

How our "Add new SSH Host" works is it parses the entered string using the same rules as the command line. This allows us to parse host names and display these in the UI etc. Given this fact, you should be able to use an escape character to perserve these double quotes ex ` \"hello world\"`
