### ISSUE TITLE
Remote Tunnel does not work anymore

### ISSUE THREAD

**Issue by SimeonEhrig** [microsoft/vscode-remote-release#7613]
The remote tunnel extension does not work anymore after the update today:

![image](https://user-images.githubusercontent.com/10682583/204809151-3d59578f-498b-4d94-8fff-0dfe1d108160.png)

- VSCode Version: 1.73.1
- Local OS Version: Linux Mint 20.3
- Remote OS Version: Ubuntu 20.04.5
- Remote Extension/Connection Type: Remote Tunnels

**Comment by datanetai** [comment]
Yes i'm facing the same problem in VS code but it does work in vscode insider.

**Comment by SimeonEhrig** [comment]
Hopefully it is solved soon. I don't want to change to the insider because of extensions. At the moment, I reactivated my old workflow with remote-ssh.

**Comment by SimeonEhrig** [comment]
@connor4312 The problem still exists. I have vsc 1.73.1 and the remote tunnel extension has version 1.0.0. Do I need to wait for an new vsc release or do I have to do some kind of fresh install (I already reinstalled the extension)?

**Comment by SimeonEhrig** [comment]
The vsc release `1.74.0` solves the problem.
