### ISSUE TITLE
Recovery container shows `Dev Container configuration '.devcontainer/devcontainer.json' already exists`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#7614]
v0.265.0

- Try a Dev Container Sample
- In the sample add a syntax error to the Docker file
- Reload the container. The container fails. Open a Recovery container.
- Recovery container with the error dialog appears 

![image](https://user-images.githubusercontent.com/6461412/204832786-9d420fa7-7681-404b-b2e6-1a6cb127ea80.png)

**Comment by connor4312** [comment]
How does one open the recovery container? I'm on dev containers 0.266. I see options to rebuild the container, edit the devcontainer.json locally, and so on, but nothing that mentions a recovery container.

**Comment by joyceerhl** [comment]
I did

1. Try devcontainer sample
2. Added syntax error to Dockerfile
3. Got this error dialog

<img width="791" alt="image" src="https://user-images.githubusercontent.com/30305945/205185829-7a0698dd-9804-4883-9fdf-09daa72c83cd.png">

4. Picked reload in recovery container
5. No error
