### ISSUE TITLE
Port range is not considered

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-remote-release#7615]
Testing #7594

I have this local user setting:
```json
"remote.SSH.serverPickPortsFromRange": {
    "localhost": "59708-59708"
},
```
Then I start VS Code and connect to localhost.

However, it looks like it chose a port outside of that range (60025):

![image](https://user-images.githubusercontent.com/2931520/204838191-a7bcd6ce-25b3-4554-89d8-fdb5b61322e2.png)

(Also I have an http server running on the port 59708 to block it)

**Comment by eleanorjboyd** [comment]
Hi! Thank you for looking into this. Could you provide the full logs from the remote-ssh extension? The port number `60025` is actually the socks port since the server hasn't started yet so for example `Starting forwarding server. localPort 53287 -> socksPort 60025 -> remotePort 59708`.
