### ISSUE TITLE
Add continue working in command for container

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#7617]
Verified from the remote repositories options. Looks like 1 and 2 (local folder and local container) still need to add entries to be consistent. 
<img width="355" alt="image" src="https://user-images.githubusercontent.com/6561887/204895340-eb6fa2e1-4dcd-4d5e-a34c-4c689274984a.png">

_Originally posted by @sbatten in https://github.com/microsoft/vscode/issues/167615#issuecomment-1332667793_

**Comment by joyceerhl** [comment]
This is already implemented and just requires a new release of the Containers extension.
