### ISSUE TITLE
"Attach to a running container" should support writing files owned by local user, rather than root

### ISSUE THREAD

**Issue by arifb** [microsoft/vscode-remote-release#7618]
Hello,

My workflow is to `docker compose up` from the terminal, then in vscode, "Attach to Running Container".

When I create files/directories in vscode it would be great if the UID/GID matched my local environment user, rather than the root user in docker.

I see issues supporting this with a devcontainer.json but as I understand it "Attach to Running Container" uses its own config file, rather than devcontainer.json? And it only supports a subset of devcontainer.json, or at least setting `containerUser` or `remoteUser` to my local username is not doing the trick.

Could the config files that are used for "Attach to Running Container" support using `containerUser`? 

Or is there a better way?

**Comment by chrmarti** [comment]
This should work: When connected to the container you can use `F1` > `Dev Containers: Open Container Configuration File` and add, e.g., `"remoteUser": "node"` to the opened JSON file. Then use `F1` > `Developer: Reload Window` to reconnect as that user.

Does that help?
