### ISSUE TITLE
Unable to download vscode server - wget vbersion too low on host

### ISSUE THREAD

**Issue by yangsos123** [microsoft/vscode-remote-release#762]
- VSCode Version: 1.35.1
- Local OS Version: Ubuntu 18.04.2 LTS
- Remote OS Version: SUSE 12.3
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install vscode remote ssh;
2. Fail to download vs code server on host.

Error code:
`
Install and start server if needed
> Installing to *********************************
> Downloading with wget
> wget: unrecognized option '--show-progress'
> Usage: wget [OPTION]... [URL]...
> 
> Try `wget --help' for more options.

...

> f212f9cd-1e1b-4aaf-b821-bb68304b218d##25##
"install" terminal command done
Received install output: f212f9cd-1e1b-4aaf-b821-bb68304b218d##25##
Server download failed
Downloading VS Code Server failed. Please try again later.`

It seems that --show-progress option is available only since wget 1.16, while on the host its version is 1.14. I have no access to update wget.

**Comment by KapitanOczywisty** [comment]
You can compile wget yourself, just don't install
```
wget http://ftp.gnu.org/gnu/wget/wget-1.20.3.tar.gz
tar -xzvf wget-1.20.3.tar.gz
cd wget-1.20.3
./configure --with-ssl=openssl --with-libssl-prefix=/usr/lib64/openssl --prefix=/usr
make 
mkdir ~/bin
cp src/wget ~/bin/wget
```
And now only change one line in `.bash_profile` (move `$HOME/bin` to the beginning)
```
PATH=$HOME/bin:$PATH:$HOME/.local/bin
```

It's not the best solution, but works for me

**Comment by yangsos123** [comment]
> You can compile wget yourself, just don't install
> 
> ```
> wget http://ftp.gnu.org/gnu/wget/wget-1.20.3.tar.gz
> tar -xzvf wget-1.20.3.tar.gz
> cd wget-1.20.3
> ./configure --with-ssl=openssl --with-libssl-prefix=/usr/lib64/openssl --prefix=/usr
> make 
> mkdir ~/bin
> cp src/wget ~/bin/wget
> ```
> 
> And now only change one line in `.bash_profile` (move `$HOME/bin` to the beginning)
> 
> ```
> PATH=$HOME/bin:$PATH:$HOME/.local/bin
> ```
> 
> After all reconnect and check version
> 
> ```
> wget -V
> ```
> 
> It's not the best solution, but works for me

Thanks and it works for me. 

But now here comes another problem as in #332 :
`"install" terminal command done
Received install output: 
Failed to parse remote port from server output: 
`
Killing and reconnecting did not work for me. By running server.sh directly on host, I got
`
*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


IP Address: 
Extension host agent listening on 8000
`

**Comment by KapitanOczywisty** [comment]
Nightly build? I had to downgrade from today's update, because of that. Server returns one port, but extension expect two. If stable I have no idea.

For Nightly If you can locate extension folder (`%appdata%\..\..\.vscode\extensions`) just copy files from older folder to newer and just update version in `package.json`

**Comment by roblourens** [comment]
Fixed in https://github.com/microsoft/vscode-remote-release/issues/794
