### ISSUE TITLE
File explorer contains extra `.docker` folder

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-release#7626]
Testing #7587

1. Create debian container
2. Add SSH feature
3. Explorer shows this:

<img width="618" alt="image" src="https://user-images.githubusercontent.com/30305945/205176992-1e0086eb-42d4-4808-9076-b087c993755d.png">

Additionally the path seems to contain mixed file path separators.

**Comment by chrmarti** [comment]
I can't find anything like this in the sshd feature. Could this be a mount point from a previous configuration? (Does it disappear when you rebuild the container?)

**Comment by joyceerhl** [comment]
Hm, seems to not repro anymore. Closing for now.
