### ISSUE TITLE
git index constantly refreshes with multiple containers

### ISSUE THREAD

**Issue by Lucianod28** [microsoft/vscode-remote-release#7627]
- VSCode Version: 1.73.1
- Local OS Version: Windows 11
- Remote OS Version: Debian 11
- Remote Extension/Connection Type: Containers

Steps to Reproduce:

1. Use Windows on host and Linux in container
2. Set up multi-container project as described in [the docs](https://code.visualstudio.com/remote/advancedcontainers/connect-multiple-containers)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

My project is a monorepo, so I use multiple dev containers as described in the multiple dev container [docs](https://code.visualstudio.com/remote/advancedcontainers/connect-multiple-containers). When I run `Dev Containers: Open Folder in Container...` for either one of my service folders, the project opens successfully. However, the git index constantly refreshes, I think because the `.git` folder is in the shared volume and there are differences between the Windows and Linux `.git`. This makes the terminal unusable both inside and outside the container - as long as I'm within the git repository the index refreshes after every single command (e.g. `ls`) blocking further terminal commands for 5-10 seconds.

The docs recommend having `.git` in the volume, and I need it there to use `git` inside the repository, but the result with cross-platform (Windows host, Linux remote) containers is unusable. This doesn't happen if the host and remote are both Linux.

**Comment by chrmarti** [comment]
Moving the workspace folder to WSL also helps with performance (similarly to using a Docker volume).

Given how long `ls` takes, your shell might run `git status` or something to show Git information. Try removing that and see if performance in the terminal improves.

**Comment by Lucianod28** [comment]
Ah you're right, my shell prompt uses `git status` to display the current branch and number of files modified. Removing that fixes the issue for non-git commands. Still, any `git` command takes 5-10 seconds, and I preferred having that information in my prompt. So you're suggesting I put the host folder on Linux using WSL? I was hoping dev containers would provide a more cross-platform solution - is there any alternative that could allow members of my team that use Windows to run it without going into WSL? And will this be an issue with macOS too? Thanks.

**Comment by chrmarti** [comment]
You can use `F1` > `Dev Containers: Clone Repository in Volume` on Windows and Mac.

The problem on both platforms is that mounting a Windows/Mac folder in a Linux container has to bridge between the Linux and the Windows/Mac OS and that appears to be much slower than mounting a Linux filesystem folder (like a Docker volume or WSL folder). The mount implementation comes with Docker Desktop and is not part of the Dev Containers extension, so I can't tell for sure what makes it slower.
