### ISSUE TITLE
can't use ssh to connect my sever when click terminal

### ISSUE THREAD

**Issue by Ross249** [microsoft/vscode-remote-release#7639]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.0
- OS Version: MacOS 12.3(Intel i9 chip)
- Extension: Remote - SSH (v0.84.0)

Steps to Reproduce:

1. connect server by remote ssh extension
2. use :w to save files which i modifed
3. click terminal to run my script
4. ssh disconnect when i click terminal button
5. can't reconnect my server any more

**Comment by eleanorjboyd** [comment]
Hello! My name is Eleanor and I am the new maintainer for the Remote-SSH extension. Are you still experiencing this issue? Thanks

**Comment by Ross249** [comment]
Yes, this issue still exists. When I used this extension to connect my server, it made it out of memory after a while. I use other ssh clients such as Termius and MobaXterm, the out-of-memory didn't happen again.
