### ISSUE TITLE
WSL: bash opens wrong directory

### ISSUE THREAD

**Issue by Zerotask** [microsoft/vscode-remote-release#7640]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68
- OS Version: Windows 10 (Windows_NT x64 10.0.19042)

Steps to Reproduce:

1. open WSL Ubuntu
2. cd /var/projects/test
3. type `code .`
4. open terminal in VS Code
5. bash shows directory /var/projects

This worked a month ago but then stopped working. Tried it with several other directories inside /var/projects. VS Code always shows this directory. I always have to cd to the proper directory to get started.

**Comment by aeschli** [comment]
Are you still seeing this?

Reasons could be:
- a `cd` command in the shell startup script (e.g. `.bashrc`)
- the setting `terminal.integrated.cwd`

@Tyriar Any other possibilities?

**Comment by Zerotask** [comment]
> a cd command in the shell startup script (e.g. .bashrc)

This was my problem. Thank you.
