### ISSUE TITLE
Allow to specify custom kubeconfig file for attaching to the remote k8s container

### ISSUE THREAD

**Issue by dzhulgakov** [microsoft/vscode-remote-release#7647]
Currently, the connection to k8s remote encodes several arguments (deducing it from the URI visible in the saved workspace): `vscode-remote://k8s-container+context=<context>+podname=<pod>+namespace=<namespace>+name=<container_name>+image=<image>`. It assumes that the context is installed in the main `kubeconfig`.

In my setup, I manage several kubeconfig files passed to `kubectl` via env var or by `kubectl --kubeconfig=...`. Since VSCode just calls `kubectl` it should be easy to pass `--kubeconfig` there.

Proposal: add `"kubeconfig"` option to the `remoteAuthority` options and the `vscode-remote://` URI. It should be a trivial change, but unfortunately the extension is closed sourced.

Related issue https://github.com/microsoft/vscode-remote-release/issues/4998 might also be addressed by this

**Comment by chrmarti** [comment]
I agree, let's continue tracking this n #4998. Thanks.
