### ISSUE TITLE
Allow local server option to `code tunnel` command

### ISSUE THREAD

**Issue by MiguelRodo** [microsoft/vscode-remote-release#7655]
I've been using `code-server serve-local` instead of accessing as accessing the remote machine via `vscode.dev` is slow for me (reported here: https://github.com/microsoft/vscode-remote-release/issues/7242). I see that we are to switch over from `code-server` to `code tunnel`, as announced in the [latest blog post](https://code.visualstudio.com/blogs/2022/12/07/remote-even-better). But, from examining `code tunnel`'s help file, I can't see any option to use a local server instead of `vscode.dev`.

So, I'd like to continue being able to use the local server. If it's already easily doable as before, then I'd like to know how. Otherwise, I'd like it to be added to `code tunnel`'s functionality. Thanks!

**Comment by Brainor** [comment]
I think [this issue](https://github.com/microsoft/vscode/issues/168492) needs some upvotes.
