### ISSUE TITLE
Open file on remote host through integrated terminal

### ISSUE THREAD

**Issue by lisanhu** [microsoft/vscode-remote-release#766]
* Version of VS Code: __1.36.0-insider__
* What type of remote connection: __SSH__
* operating system: __macOS 10.14.5__
* remote operating system: __Linux__

If in local, I know we can open a file in the integrated terminal through `code -r filename` to open a file in existing window.

I wish to have similar function on remote server through integrated terminal, so in a certain folder, I can type `code -r filename` or some other commands to open the file directly in the current window.

What I'm doing now to do this: `readlink -f filename`, then Cmd + left click on the full file path. It's working, but it's still not very convenient.

Really appreciate your work that makes my workflow more smoothly. Thank you very much!

**Comment by tomocafe** [comment]
`code -r filename` is working for me on Linux remote machine from the integrated terminal. Is `code` in your PATH? If not, there's a command to install it from within VS Code. 

BTW, I opened #768 along the same lines, but for opening to a certain line.

**Comment by egamma** [comment]
This is supported. You can run `code filename` from the integrated terminal that runs in the remote context. If it doesn't work please file an issue with detailed steps for how to reproduce.

**Comment by lisanhu** [comment]
Thank you! Just realized what happened, `code` doesn't work because I should use `code-insiders`! It worked perfectly using `code-insiders` command on the remote server! Thank you!
