### ISSUE TITLE
VsCode over ssh can leave zombie processes on remote host

### ISSUE THREAD

**Issue by sadgsagsag** [microsoft/vscode-remote-release#7660]
Type: <b>Bug</b>

shutdown the laptop or otherwise ungracefully terminate the VsCode ssh session.

Ultimately the remote server can become heavily loaded with zombie VsCode processes.  This will result in the server and editor both becoming non-responsive (text highlight/selection and cursor position are erratic and jumpy).

I think that VsCode must proactively clean up all zombies each time the editor is restarted and connection with the remote host is started. 

The current behavior is too expensive to manage... non-responsive editor... server loaded... even outlook on the laptop starts to misbehave because cursor/highlighting is problematic.

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 3.10.0-1160.76.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|29.88GB (22.23GB free)|
|Process Argv|--crash-reporter-id 5ee1fb62-c4e9-4e19-a77c-26937a1511ac|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: atletx7-reg148|
|OS|Linux x64 3.10.0-1160.76.1.el7.x86_64|
|CPUs|AMD EPYC 7742 64-Core Processor (128 x 2250)|
|Memory (System)|2015.82GB (1766.63GB free)|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.16.3
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.0.3
tcl|ras|0.1.0
vscode-ruby|win|0.28.0
vscode-perforce|bam|1.1.3
doxdocgen|csc|1.4.0
systemverilog|eir|0.13.3
better-cpp-syntax|jef|1.16.3
cmake-language-support-vscode|jos|0.0.7
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2022.20.0
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.6
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.6.0
ruby|reb|0.28.1
cmake|twx|0.0.17
vscode-ruby|win|0.28.0
change-case|wma|1.0.0

(2 theme extensions excluded)

</details>

**Comment by eleanorjboyd** [comment]
Hello! What value is your "useLocalServer" setting set to? Does this ongoing issue seem like it might be related?https://github.com/microsoft/vscode-remote-release/issues/7642

**Comment by sadgsagsag** [comment]
[AMD Official Use Only - General]

Thanks Eleanor, I am not familiar with 'useLocalServer' let me look it up...

The remote server is a linux machine..

Remote.SSH.Use Local Server is enabled, I can disable it.

**Comment by eleanorjboyd** [comment]
Sounds great! The setting useLocalServer mode is advised since it does create a more seamless experience in my opinion therefore I would suggest switching it back once the fix I tagged is release which will be very soon. Im closing this issue so please reference https://github.com/microsoft/vscode-remote-release/issues/7642 for updates and post there will follow up questions. Thanks!

**Comment by sadgsagsag** [comment]
To be clear, I am not certain of how the zombie processes were left on the linux server.  It could have been laptop shutdown or an ungraceful termination of the connection to the host or other reasons.  I suspect the solution will need to be something like a consistent clean up of zombies when VsCode reconnects to the host... some reliable return to a good state during regular use.  Thank you for your attention, VsCode over ssh has been an excellent productivity tool.
