### ISSUE TITLE
Remote - Tunnels: Details tab in Extensions view shows broken image

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-remote-release#7662]
![image](https://user-images.githubusercontent.com/6726799/206695020-ad47e2ab-7fa3-409a-9b75-0fb9fcd286ef.png)

**Comment by bamurtaugh** [comment]
Thanks for reporting @gjsjohnmurray!

@aeschli I see you updated the extension's readme last week, and although it isn't updated in the marketplace, I think it's just waiting a new extension release. Thus, I think this issue will be fixed upon the next release of the extension, but just wanted to double-check with you before closing.

**Comment by bamurtaugh** [comment]
The images appear correctly now, please let me know if folks see otherwise though!
