### ISSUE TITLE
Unable to connect to remote host: "Failed to parse remote port from server output"

### ISSUE THREAD

**Issue by carlfischerjba** [microsoft/vscode-remote-release#767]
- VSCode Version: 1.35.1
- Local OS Version: Windows 10
- Remote OS Version: CentOS 7
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to remote host from VSCode.
2. See error message popup 'Could not establish connection to "my-remote-host"'.

Output 
```
remote-ssh-nightly@2019.6.29700
win32 x64
SSH Resolver called for "ssh-remote+my-remote-host", attempt 1
SSH Resolver called for host: my-remote-host
Setting up SSH remote "my-remote-host"
Using commit id "c7d83e57cd18f18026a8162d042843bda1bcf21f" and quality "stable" for server
Testing ssh with c:\Program Files\Git\usr\bin\ssh.exe -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_7.9p1, OpenSSL 1.0.2p  14 Aug 2018
Install and start server if needed
> 
> Found existing installation at /home/my-user/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> 
> 85fc924b-ffe8-4f1a-9f48-fb04185ea9e3==40300====
> 
"install" terminal command done
Received install output: 85fc924b-ffe8-4f1a-9f48-fb04185ea9e3==40300====
Failed to parse remote port from server output: 85fc924b-ffe8-4f1a-9f48-fb04185ea9e3==40300====
```

I've seen three other similar bug reports but they have a different string for the "install output", either empty or an error message.

I'm using the nightly build of the Remote SSH extension and I've provided the path to `c:\Program Files\Git\usr\bin\ssh.exe` to avoid failures earlier in the connection process.

My ssh config file is:
```
Host my-remote-host
    HostName my-remote-host
    User my-user
    IdentityFile ~/.ssh/id_rsa-remote-ssh
```

**Comment by carlfischerjba** [comment]
Killing the remote server process and trying again is very similar except for the additional lines in the output:
```
> Starting server...
> Waiting for server log...
```

**Comment by carlfischerjba** [comment]
Followed suggestion from issue #762 and downgraded to yesterday's nightly build. Now I'm able to connect.

**Comment by dimitar-nikovski** [comment]
I downgraded to 2019.6.23944 and then I reattempted, then it failed with the same message, then I retried, VS Code gave me a warning "extensions have been modified on disk, please reload" I reloaded, then the extension showed the downgraded version, I was prompted to connect and it worked.

The difference in output is:

`Received install output: 85fc924b-ffe8-4f1a-9f48-fb04185ea9e3==40300====
Failed to parse remote port from server output: 85fc924b-ffe8-4f1a-9f48-fb04185ea9e3==40300====`

vs

`Received install output: efc526ac-9f12-4db4-977b-9d080e83e870==34409==
Server is listening on port 34409
Spawning tunnel with: "ssh" -t   "username@myhost" -L localhost:58154:localhost:34409 "echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity"`
