### ISSUE TITLE
Remote Tunnels - Not standalone and difficult to install

### ISSUE THREAD

**Issue by y2k4life** [microsoft/vscode-remote-release#7670]
RE: [Remote Development Even Better](https://code.visualstudio.com/blogs/2022/12/07/remote-even-better)

It is a challenge to install on Linux that does not have a desktop (no GUI/browser). Even after figuring out how to download the tar.gz file it does not work as advertised "standalone".

First issue was downloading.

The experience to get a URL and download the CLI for Linux install without a desktop is not as direct and easy. Due to the redirects and auto download on the webpage [Alt Downloads](https://code.visualstudio.com/#alt-downloads) I had to use F12 tools in my browser to figure out the URL before I could copy/past for use with cURL or Wget. This is the correct file? [Direct Link](https://az764295.vo.msecnd.net/stable/5235c6bb189b60b01b1f49062f4ffa42384f8c91/vscode_cli_alpine_x64_cli.tar.gz). This issue is not just with VS Code. I experience similar issues with .NET.  These redirect auto downloads make installing software on Linux a pain. Would be nice to have URL you can copy and paste. I digress.

> ... we've also made it available for standalone install, in case you're working on a VM or locked down machine where you can't install VS Code Desktop.

Second issue with running the app

After extracting the tar.gz file I get a single file "code". Run that file and I get this:

>No installation of Visual Studio Code Stable was found.
Install it from your system's package manager or https://code.visualstudio.com, restart your shell, and try again.

>If you already installed Visual Studio Code and we didn't detect it, run `code version use stable --install-dir /path/to/installation`

If I install Visual Studio Code then I would not need the standalone.

**Comment by jonghwanhyeon** [comment]
For the second issue, `./code tunnel` works even if Visual Studio Code  is not installed.

**Comment by tmeckel** [comment]
@y2k4life the "correct" download URL for this redirect mess via the "Alt Downloads" page should be:

https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64

Aside this I fully agree that the current experience for downloading the tunnel cli is a pain.

**Comment by y2k4life** [comment]
That is a 304 redirect URL. Which either I don't know how to have wget or cURL handle redirects. Either one will lock up. That is why I used F12/Network to see the redirected URL. I tried cURL with an -L a -V, and many other parameters. From what I've Googled (with Bing) wget follows redirects. Not in this case.

Regardless, it should not be this difficult.

**Comment by y2k4life** [comment]
@tmeckel thank you that works and helps with simplifying the download and would be considered a documentation bug not specifying the how to download with cURL or wget. IMHO.

Issue #2 is not resolved regardless of the way you download the app is the same.

I'm downloading the same app regardless of how I download it and I still get the dependent on the full VSCode.

**Comment by y2k4life** [comment]
@jonghwanhyeon thank you. Can't just run ./code need to run with the switch. I had a typo. Dohh!

The only issue then is to clean up the documenting on downloading and to comment the error I've seen and what to do with it.

**Comment by bamurtaugh** [comment]
I opened a docs PR to add this info: https://github.com/microsoft/vscode-docs/pull/6047.

**Comment by zyzhang1992** [comment]
@bamurtaugh I am having trouble running code tunnel on one of the clusters I have access to. That worked just fine on one cluster and didn't work on another. What happened is that when I run it and authenticate it on the git page, it will never start the server and the tunnel will not connect. Please see below for the error. Any ideas how to resolve this?

```
[zyzhang@sh02-01n39 ~/vscode-test] (job 14040661) $ /home/users/zyzhang/code tunnel --verbose
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
[2023-03-27 21:29:54] debug No code server tunnel found, creating new one
[2023-03-27 21:29:54] trace Found token in keyring
[2023-03-27 21:29:54] debug [reqwest::connect] starting new connection: https://api.github.com/
[2023-03-27 21:29:54] debug [reqwest::connect] starting new connection: https://global.rel.tunnels.api.visualstudio.com/
[2023-03-27 21:32:02] error error listing current tunnels: connection error: error sending request for url (https://global.rel.tunnels.api.visualstudio.com/api/v1/tunnels?global=true&tags=vscode-server-launcher&allTags=true): error trying to connect: tcp connect error: Operation timed out (os error 110)
```

**Comment by bamurtaugh** [comment]
@zyzhang1992 thanks for sharing. This seems it may be a different issue than what's described in this issue? I'd recommend opening a new issue in this repo. But please let me know if it is related and I'm just missing something.

**Comment by zyzhang1992** [comment]
Thanks @bamurtaugh for the quick response. You are right that this may not be related to the current issue. I'll open another ticket.
