### ISSUE TITLE
 Code tunnel service issues 

### ISSUE THREAD

**Issue by icouldonlygetthisname** [microsoft/vscode-remote-release#7678]
- VSCode Version: 1.74
- Local OS Version: OSX 13.0.1 iPadOS 16.1.1
- Remote OS Version: Ubuntu 22.04.1 
- Remote Extension/Connection Type: Server
- Logs: 
Code Tunnel Service Log is blank after a reboot. 

I've got two issues, the service doesn't run as a service. On first install it starts and runs as expected if I reboot then it doesn't start, systemctl doesn't recognise it either so I can't manually encourage it to start. I know I can tweak the unit file or make a new one.  

The 2nd issue is if I run it as a service then I can't connect with remote tunnel extension in 1.74 it sees the remote host as online but doesn't tunnel. If I uninstall the service and do code tunnel then it works fine. Oddly using insider in a browser from my iPad allows me to connect when running as a service and without running as a service.

**Comment by icouldonlygetthisname** [comment]
So after some minor tweaks to the until file, it is working as expected for my iPad.
For anyone else experiencing the same issues here's what I did to fix it. 

sudo loginctl enable-linger $USER

in the unit file, I replaced the line to :
[Install]
WantedBy=default.target

 in ~/.config/systemd/user/ mkdir default.target.wants (just in case) 
check the permissions with ls -l 
systemctl --user daemon-reload
systemctl --user enable code-tunnel.service
systemctl --user status

rebooted and it's fine 😄 

Although I can't connect from the Mac still 🤷‍♂️

**Comment by serkodev** [comment]
@icouldonlygetthisname For the Mac (desktop VSCode) problem, maybe https://github.com/microsoft/vscode-remote-release/issues/7661 can help you

**Comment by serkodev** [comment]
@icouldonlygetthisname After install `1.74.1 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a` update, I can connect from macOS now.

**Comment by serkodev** [comment]
#### Reference for contributor

If i understand correctly, `multi-user.target` is for system-bus.

VS Code does not recommend start `tunnel` as a super user so running `code tunnel service enable` by user should generate config `[Install] WantedBy: default.target` for user-bus instead of `multi-user.target`.

Reference: https://unix.stackexchange.com/a/666515

**Comment by icouldonlygetthisname** [comment]
1.74.1 fixed the Mac issue, I think that was the character issue @connor4312 

The service not starting with multi-user.target has stumped me; technically, it shouldn't make any difference, but when I check with systemctl get-default = graphical.target so switching to default.target fixed it. 
Updating doesn't modify the unit file either I update the Ubuntu box to 1.74.1 without issue. 

If you need any verbose logs let me know.

**Comment by rjwonder** [comment]
> in ~/.config/systemd/user/ mkdir default.target.wants (just in case)

For me on Debian Buster this was the key to get it working.

I left this as-is
[Install]
WantedBy=multi-user.target

**Comment by connor4312** [comment]
Merging into https://github.com/microsoft/vscode/issues/170014 (since there is a PR open for that)
