### ISSUE TITLE
Unregister a tunnel other than current machine via CLI

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#7683]
From discussion with @chrisdias: We can right-click a tunnel to unregister it in the VS Code UI, but via the CLI, I believe there’s only an “unregister” command for the current machine where I’m running the CLI. 

In the CLI, could we list all tunnels associated with the current logged in user and allow them to unregister any tunnel they'd like?

**Comment by connor4312** [comment]
We now are good about recycling tunnels, and they also expire after 30 days of inactivity, so I don't think there's a big need to do this.
