### ISSUE TITLE
WSL: Blue screen of death tied to dependency discovery through symbolic links

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-remote-release#769]
VSCode Version: 1.36.0-insider (user setup)
Commit: c3fe2d8acde04e579880413ae4622a1f551efdcc
Date: 2019-06-20T05:20:10.276Z
Electron: 4.2.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
Local OS OS: Windows_NT x64 10.0.18362

Remote OS Version: Debian GNU/Linux 9
Remote Extension/Connection Type: WSL 1

Steps to Reproduce:

1. In the WSL, install NodeJS 10.16 (I used `nvm`).
2. Install rush: https://rushjs.io
3. Clone https://github.com/Azure/azure-sdk-for-js/ inside the WSL.
4. Open VSCode with the WSL extension and add the folder of the azure-sdk-for-js repository to a workspace.
5. cd into the cloned repository.
6. Run `rush install`.
7. In VSCode, open some of the files of one of the packages in the `sdk` folder of the `azure-sdk-for-js`.
8. Add a new dependency to the package you picked, let's say `bluebird`, as follows:
    a. In the file you opened, add a line somewhere with something like `console.log(require('bluebird'))`, this probably doesn't matter, but just in case.
    b. Inside the folder of the package you selected, run `rush add bluebird`

At some point you should get the following error:

```
ERROR: Error: Error: EACCES: permission denied, rename '/home/sadasant/code/github.com/Azure/azure-sdk-for-js/common/temp/node_modules' -> '/home/sadasant/code/github.com/Azure/azure-sdk-for-js/common/temp/rush-recycler/node_modules_1561142494527'  Often this is caused by a file lock from a process like the virus scanner. 
```

At this point, we have two scenarios:
1. **Blue screen of death:** If now I run `rush reset-workspace`, I get the blue screen of death. See the picture below.
2. **Temporary fix:** If I close VSCode and re-run the command, the error goes away. However, sometimes this doesn't seem to be enough, I've had to restart my machine at least once in the last couple of weeks.

Photo of the blue screen of death:

![photo4929196896489154663](https://user-images.githubusercontent.com/417016/59944660-53b31900-9433-11e9-85d9-136354803400.jpg)

**What might be causing this:**
I believe this is caused due to the way VSCode's remote extensions discover and access the remote dependencies and perhaps also the fact that `rush` uses symbolic links. VSCode must be using some locking mechanism to make sure the underlying files are not deleted and this is probably not enough to hold back `rush reset-workspace` from removing the symlinks.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by gulshan** [comment]
I have experienced BSOD several times while wsl remote was running also. Filed my issue at #988

**Comment by aeschli** [comment]
Please file WSL crash issues directly against https://github.com/microsoft/WSL/issues (of course check for duplicates first)
