### ISSUE TITLE
Can not attach to remote container

### ISSUE THREAD

**Issue by donproc** [microsoft/vscode-remote-release#7692]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:
1. just attach one remote container

I  tried the way from several related solved issues, but still don't work  

Error Message
![image](https://user-images.githubusercontent.com/16092281/177898530-0e8fc256-48ef-4127-ab71-dfdfe5b8a4c1.png)

https://stackoverflow.com/questions/72812351/can-not-attach-visual-studio-code-to-remote-container

**Comment by chrmarti** [comment]
Sorry for the delay, is this still a problem? Could you append the log from when this happens? (`F1` > `Dev Containers: Show Container Log`)

**Comment by donproc** [comment]
> Sorry for the delay, is this still a problem? Could you append the log from when this happens? (`F1` > `Dev Containers: Show Container Log`)
@chrmarti 
Thanks for you reply. Yes it is. I still can not attach.



```
[14272579 ms] Start: Run: C:\Users\name\.ssh\config remote_host /bin/sh
[14272584 ms] Start: Run in host: id -un
```

**Comment by donproc** [comment]
The problem resolved by setting ssh  full path explicitly. Thanks @chrmarti, inspired by the answer with similar issue https://github.com/microsoft/vscode-remote-release/issues/6943
