### ISSUE TITLE
Confiscated my stolen data and all my valuable cryptos back and plus 10% interest on every fraudulent user.

### ISSUE THREAD

**Issue by Masterkenshin** [microsoft/vscode-remote-release#7698]
- VSCode Version:
- Local OS Version:
- Remote OS Version:
- Remote Extension/Connection Type: SSH/Containers/WSL/Server
- Logs:

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by bamurtaugh** [comment]
If you have a specific issue with a VS Code Remote extension, please feel free to let us know, thanks!
