### ISSUE TITLE
Add AppData SSH location

### ISSUE THREAD

**Issue by Sti2nd** [microsoft/vscode-remote-release#7699]
This is really a duplicate of https://github.com/microsoft/vscode-remote-release/issues/6682 so that can be opened instead if you like, but now I am more certain what the problem is. This extension do not check all the install locations for SSH. When one isn't admin on the computer Git for Windows and GitHub Desktop will install SSH in `C:\Users\USERNAME\AppData\Local\Programs\Git\usr\bin\ssh.exe`. The places it looks for SSH is listed here: https://github.com/microsoft/vscode-remote-release/issues/6682#issuecomment-1124007793

A colleague got the same error I got in https://github.com/microsoft/vscode-remote-release/issues/6682 a few days ago that is why I decided to open a new issue.

- VSCode Version: any
- Local OS Version: Windows_NT x64 10.0.19042
- Remote OS Version: any
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. On a new Windows computer without admin rights; install GitHub Desktop which will install Git and SSH
2. In VSCode with the SSH - extension, try to connect to any remote address with VS Code. Will fail

Does this issue occur when you try this locally?: Don't understand what you are asking
Does this issue occur when you try this locally and all extensions are disabled?: Don't understand what you are asking

**Comment by eleanorjboyd** [comment]
Hi! If you update the setting `Remote.SSH: Path` in VS Code to your ssh setup path does this work?
