### ISSUE TITLE
devcontainer "build": {"dockerfile": ...} corrupts environment variables

### ISSUE THREAD

**Issue by diricxbart** [microsoft/vscode-remote-release#7700]
- VSCode Version: 1.74.0
- Local OS Version: Windows 10
- Remote OS Version: Debian 9
- Remote Extension/Connection Type: SSH + Containers

Steps to Reproduce:

Folder structure:
```
└── [  57]  my_project
    ├── [  39]  .devcontainer
    │   └── [ 472]  devcontainer.json
    └── [  47]  Dockerfile
```
The Dockerfile is only used in the _failing setup_.

**Working setup:**

Contents of `devcontainer.json`:
```
{
    "image": "nvcr.io/nvidia/tensorflow:22.10.1-tf2-py3",
    "workspaceFolder": "/git/my_project",
    "workspaceMount": "src=/home/my_user_name/git/my_project,dst=/git/my_project,type=bind",
    "runArgs": [
        "--gpus",
        "all",
    ],
    "postCreateCommand": "env | grep CUDA"
}
```
Output of `postCreateCommand`:
```
Running the postCreateCommand from devcontainer.json...

[46203 ms] Start: Run in container: /bin/sh -c env | grep CUDA
NVIDIA_REQUIRE_CUDA=cuda>=9.0
CUDA_CACHE_DISABLE=1
CUDA_VERSION=11.8.0.065
CUDA_DRIVER_VERSION=520.61.05
_CUDA_COMPAT_PATH=/usr/local/cuda/compat
Done. Press any key to close the terminal.
```

**Failing setup:**
Contents of `Dockerfile`, basically only defining the exact same base image...:
```
FROM nvcr.io/nvidia/tensorflow:22.10.1-tf2-py3
```

Contents of `devcontainer.json`:
```
{
    "build": {
        "dockerfile": "${localWorkspaceFolderBasename}/../../Dockerfile"
    },
    "workspaceFolder": "/git/my_project",
    "workspaceMount": "src=/home/my_user_name/git/my_project,dst=/git/my_project,type=bind",
    "runArgs": [
        "--gpus",
        "all",
    ],
    "postCreateCommand": "env | grep CUDA"
}
```
Output of `postCreateCommand`:
```
Running the postCreateCommand from devcontainer.json...

[53922 ms] Start: Run in container: /bin/sh -c env | grep CUDA
_CUDA_COMPAT_PATH=/usr/local/cuda/compat
Done. Press any key to close the terminal.
```

This shows that the environment variables are not properly preserved when making using of `"build": {"dockerfile": ...}`.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by diricxbart** [comment]
Any plans on fixing this bug?

**Comment by chrmarti** [comment]
`${localWorkspaceFolderBasename}` in `"${localWorkspaceFolderBasename}/../../Dockerfile"` might not be what you intend to. Maybe you meant to use `${localWorkspaceFolder}`?

**Comment by diricxbart** [comment]
It correctly finds the dockerfile the way it is currently referred to, this is not the issue..

The issue is that after starting the referenced docker via build, it behaves differently (as in it no longer works in our case) compared to starting it directly (via image). If I remember correctly this caused issues with running a Python script using CuPy (GPU), further investigation then showed that at least the environment variables were different... This difference in behavior is unexpected.

When defining the docker via build, it should behave identical compared to via image. Now via build the image is corrupted / broken in my case...

**Comment by diricxbart** [comment]
I reproduced the issue today. I managed to reproduce it both using:
```
"build": {
    "dockerfile": "${localWorkspaceFolder}/Dockerfile"
},
```
and 
```
"build": {
    "dockerfile": "${localWorkspaceFolderBasename}/../../Dockerfile"
},
```
Note that in both cases you should NOT specify `image` (as we are using `build`).

The result of the `env | grep CUDA` command in the failing case is now slightly different:
```
Running the postCreateCommand from devcontainer.json...

[94874 ms] Start: Run in container: /bin/sh -c env | grep CUDA
_CUDA_COMPAT_STATUS=System has unsupported display driver / cuda driver combination (CUDA_ERROR_SYSTEM_DRIVER_MISMATCH) cuInit()=803
_CUDA_COMPAT_PATH=/usr/local/cuda/compat
Done. Press any key to close the terminal.
```
But the conclusion is the same: within the resulting docker container, GPU access will fail...

If you first tried the successful method (using `image`), then you'll need to first `rm` that container on the remote server, otherwise you'll be connecting to the previously defined container.

I'm testing this while connecting to a server which has 4 GPU's and the following drivers (based on `nvidia-smi`):
```
NVIDIA-SMI 520.56.06    Driver Version: 520.56.06    CUDA Version: 11.8 
```

My local PC is Windows 10 based, the remote server is Debian 9 (Stretch).
