### ISSUE TITLE
Remote-ssh: time-out error message but it is connected

### ISSUE THREAD

**Issue by thistlillo** [microsoft/vscode-remote-release#7717]
With the latest version of VSC and remote-ssh, every time I connect to a remote machine I get:
- VSC takes some time to connect, but it does eventually. It was much faster with earlier versions;
- as soon as it connects, I get a dialog telling me that it could not connect due to a time-out. However, VSC is connected and I can work on the remote machine.

Is there any simple check I can make to make VSC reasonable again?

```
Version: 1.74.0 (user setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
```

Remote-SSH: `v0.94.0`

Client runs Windows 11 Pro (it is full of bugs, may be this is another one); remote runs linux. As I said, I started seeing this weirdness only with the latest VSC.

**Comment by eleanorjboyd** [comment]
Hello! Could please file a new issue using this [form](https://github.com/microsoft/vscode-remote-release/issues/new?assignees=eleanorjboyd&labels=ssh&template=a_remote_ssh_bug_form.yml&title=%5BRemote-SSH+Bug%5D%3A+). This will help us gather important information that will help troubleshoot your current issue. Thanks!
