### ISSUE TITLE
Is there any way to use socks5 instead of port forward

### ISSUE THREAD

**Issue by oneengineer** [microsoft/vscode-remote-release#772]
In my environment, I can use `ssh -D $portA  remote_server` , but `ssh -L $portX:localhost:$portY remote_server` would fail.
Is there any to use make vscode remote use dynamic tunneling (I guess it is same as socks5) instead of TCP forward?

**Comment by caffeineaddiction** [comment]
see also: https://github.com/microsoft/vscode-remote-release/issues/161

**Comment by caffeineaddiction** [comment]
as a work around I have done the following:

Desktop `~/.ssh/config`
```
...

Host *
  RemoteForward 54321

...
```

Remote: `~/bin/wget` in which `~/bin` is added to `PATH` via .bashrc
```
#!/bin/bash
export LD_LIBRARY_PATH=$HOME/opt/lib/tsocks/
export TSOCKS_CONF_FILE=$HOME/opt/tsocks/tsocks.conf
$HOME/bin/tsocks /usr/bin/wget $@
```
Remote: `~/opt/tsocks/tsocks.conf`
```
server = 127.0.0.1
server_port = 54321
server_type = 5
```
note `tsocks` binary has been scp-ed to `~/bin/tsocks` and `~/opt/tsocks/` has been created with `libtsocks.so` which is normally stored in `/usr/lib64/libtsocks.so`

This is a work around that allows me to have wget functionality with out messing with anything outside my profile to get it to work (eg: no root required ... even though I have it).

**Comment by cameronbraid** [comment]
Just edit your ssh config file and add 

```DynamicForward 54321```

And this will setup a SOCKS5 proxy on port 54321

**Comment by caffeineaddiction** [comment]
> Just edit your ssh config file and add
> 
> `DynamicForward 54321`
> 
> And this will setup a SOCKS5 proxy on port 54321

wget does not support socks5 by default

**Comment by cameronbraid** [comment]
Sure, but my answer was in regards to the question :

>Is there any way to use socks5 instead of port forward?
>
> In my environment, I can use ssh -D $portA remote_server , but ssh -L $portX:localhost:$portY remote_server would fail.
> Is there any to use make vscode remote use dynamic tunneling (I guess it is same as socks5) instead of TCP forward?

Since you can do the same thing as `-D` using `DynamicForward` in ssh config


This allows you to setup socks5 instead of port forwarding.

**Comment by caffeineaddiction** [comment]
https://www.openssh.com/txt/release-7.6
> ssh(1): add support for reverse dynamic forwarding. In this mode,
> ssh will act as a SOCKS4/5 proxy and forward connections
> to destinations requested by the remote SOCKS client. This mode
> is requested using extended syntax for the -R and RemoteForward
> options and, because it is implemented solely at the client,
> does not require the server be updated to be supported.

`-R` allows for doing a reverse `-D` ... thus `-R` is using socks5

**Comment by cameronbraid** [comment]
Aah, so you can do it in reverse too.. sweet

**Comment by roblourens** [comment]
Dynamic forwarding is now used
