### ISSUE TITLE
Investigate: Improve management of Dev Containers

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-remote-release#7720]
When creating many dev containers using the "Create Dev Container..." command, it becomes difficult after a while to tell them apart. It would be nice to allow renaming them and to better support the user in cleaning them correctly (removing both a container and its volume).

<img width="941" alt="DevContainers" src="https://user-images.githubusercontent.com/5047891/208068380-d2a1d403-e06d-48b0-935f-9fde1b0da34b.png">

cc @kieferrm

**Comment by chrmarti** [comment]
Adding a clean up command. Renaming is difficult because a container's metadata is readonly.
