### ISSUE TITLE
Forwarded ports are sometimes held open on the host after the process in the container is closed

### ISSUE THREAD

**Issue by davidwallacejackson** [microsoft/vscode-remote-release#7731]
Intermittently, when developing in Dev Containers, I've seen ports associated with closed processes still show up in the "Ports" tab. When I try to access these ports within the container, they're closed, but if I hit them from outside, the request never finishes (as if it's waiting for a response from the server).

I'm happy to post logs for this the next time I hit it, but creating the issue for now as requested by @chrmarti, who also asked me to tag @alexr00

**Comment by chrmarti** [comment]
@alexr00 Would it make sense to stop forwarding an automatically forwarded port when the remote process stops listening on the port? We already detect when a process starts listening on a port, so maybe that can be extended to also automatically tear down a port forwarding.

**Comment by chrmarti** [comment]
Thought I could reproduce, but now it works as expected:

- Using a dev container with `.devcontainer/devcontainer.json`: `{ "image": "mcr.microsoft.com/devcontainers/typescript-node:0-18" }`
- Settings: `remote.autoForwardPorts: true`, `remote.autoForwardPortsSource: process` , `remote.localPortHost: localhost`, `remote.portsAttributes: empty`, and `remote.otherPortsAttributes: empty`.
- Ports panel starts empty.
- Run `node server.js` in terminal.
- Ports panel shows port 1234 forwarded.
- Running `curl http://localhost:1234` in a local terminal shows the server response.
- Ctrl+C in terminal to terminate server.js.
- Ports panel is again empty.
- Running `curl http://localhost:1234` in a local terminal reports the connection gets refused.

server.js:
```js
const http = require('http');

const server = http.createServer((req, res) => {
    res.end('Hello World!');
});
server.listen(1234, '127.0.0.1', () => {
    const address = server.address();
    console.log(`http://${address.address}:${address.port}`);
});
```

@davidwallacejackson Could you check if this works for you?
