### ISSUE TITLE
Forwarded ports are sometimes not automatically detected and exposed

### ISSUE THREAD

**Issue by davidwallacejackson** [microsoft/vscode-remote-release#7732]
Sometimes I can open a port from a process in a Dev Container without VS Code detecting the port or forwarding it to the host. I haven't seen any pattern to when this occurs, but closing and reopening VS Code usually fixes it.

I'm happy to post logs for this the next time I hit it, but creating the issue for now as requested by @chrmarti, who also asked me to tag @alexr00

**Comment by alexr00** [comment]
This is automatic detecting and forwarding for ports? Next time you see the issue can you please set the log level to trace (command: Developer: Set Log Level), wait a minute, then share the following:
- Remote Extension Host output
- Window output
- Shared output
- The values of `remote.autoForwardPorts`, `remote.autoForwardPortsSource`, `remote.localPortHost`, and `remote.portsAttributes`.

**Comment by chrmarti** [comment]
Thought I could reproduce, but now it works as expected:

- Using a dev container with `.devcontainer/devcontainer.json`: `{ "image": "mcr.microsoft.com/devcontainers/typescript-node:0-18" }`
- Settings: `remote.autoForwardPorts: true`, `remote.autoForwardPortsSource: process` , `remote.localPortHost: localhost`, `remote.portsAttributes: empty`, and `remote.otherPortsAttributes: empty`.
- Ports panel starts empty.
- Run `node server.js` in terminal.
- Ports panel shows port 1234 forwarded.
- Running `curl http://localhost:1234` in a local terminal shows the server response.
- Ctrl+C in terminal to terminate server.js.
- Ports panel is again empty.
- Running `curl http://localhost:1234` in a local terminal reports the connection gets refused.

server.js:
```js
const http = require('http');

const server = http.createServer((req, res) => {
    res.end('Hello World!');
});
server.listen(1234, '127.0.0.1', () => {
    const address = server.address();
    console.log(`http://${address.address}:${address.port}`);
});
```

@davidwallacejackson Could you check if this works for you?
