### ISSUE TITLE
Add "Open In Terminal" option when right-clicking a folder

### ISSUE THREAD

**Issue by benlindsay** [microsoft/vscode-remote-release#774]
In a local VSCode instance, I can right-click on a folder in the file explorer window, click "Open in Terminal". That option doesn't seem like it's available when I'm in a remote SSH environment. If that could be added it would be great. Is that feasible?

![image](https://user-images.githubusercontent.com/9361152/59965873-641dcf00-94d9-11e9-91de-b5c99bbf83e7.png)

**Comment by Tyriar** [comment]
This feature is disabled for remote but it should be enabled and force `"terminal.explorerKind": "integrated"`

**Comment by Tyriar** [comment]
To verifier:

Make sure open in terminal explorer context menu works in remote and local and also the "Open New Terminal" command works in remote (should open external terminal) and local (should open integrated terminal).

**Comment by lramos15** [comment]
@Tyriar I believe you flipped what the Open New Terminal command does in the remote context and local context in your verification steps.
