### ISSUE TITLE
Finding actions from other resolvers is hard when in a remote window

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-remote-release#7741]
* Connect to a Remote (e.g. a dev container)
* Click the Remote Indicator status bar
* Only actions from dev containers are shown
* It might be useful to have a way to get to the other actions from the other remotes

> ![image](https://user-images.githubusercontent.com/5047891/208129694-97109068-9bc9-4687-b5fb-65909287d330.png)

* Example how it looks in a non-remote window:
> ![image](https://user-images.githubusercontent.com/5047891/208129733-b077d472-4586-427b-af2b-33ea2f0f7327.png)

cc @kieferrm @bamurtaugh @egamma for thoughts

**Comment by aeschli** [comment]
Here's are the command we currently show in the remote indicator in a local window:

![image](https://user-images.githubusercontent.com/6461412/213486738-1ad70bf5-1fb9-44d7-8422-b50335e7d8e7.png)
![image](https://user-images.githubusercontent.com/6461412/213486914-c5c5c43d-8462-4239-8da2-7e6557ab7262.png)

**Comment by aeschli** [comment]
|  Command | Category | Use | Explanation | 
| --------------------  | ------- |  --- | -------------------- | 
| Connect to Tunnel... | Tunnels| | 
| Get Started with VS Code Tunnels |  
| New WSL Window | WSL | 
| New WSL Window using Distro... | 
| Open Folder in WSL... | 
| Reopen Folder in WSL | 
| Getting Started with WSL | 
| Connect to Host...  | SSH | 
| Connect Current Window to Host...| 
| Open SSH Configuration File...| 
| Getting Started with SSH| 
| Continue Working in a Container Volume | Dev Containers | 
| Reopen in Container| 
| Open Folder in Container...| 
| Create Dev Container...| 
| Clone Repository in Container Volume...| 
|  Attach to Running Container...| | |
| Add Dev Container Configuration Files...| | |
| Try a Dev Container Sample...| | |
| Getting Started with Dev Containers| | |
| Connect to Codespace| Codespaces |
| Create New Codespace| | |
| Delete Codespace.| | |
| Continue Working in a New Codespace.| | |
| Open Remote Repository...| Remote Repos| |

**Comment by chrmarti** [comment]
The Dev Containers commands also make sense when in a WSL window. Same for "Clone Repository in Container Volume" and "Try a Dev Container Sample" as they then use Docker installed in SSH / WSL.

**Comment by aeschli** [comment]
@chrmarti Thanks I updated the descriptions

**Comment by aeschli** [comment]
Adoption:

- [ ] WSL @aeschli https://github.com/microsoft/vscode-remote-wsl/pull/92
- [ ] SSH @eleanorjboyd https://github.com/microsoft/vscode-remote-ssh/pull/288
- [x] Container @chrmarti 
    - Already shows commands in WSL and SSH
    - Could remove `Getting Started with Dev Containers`
- [x] Tunnels @aeschli @connor4312
    - Already shows commands
    - Could remove `Getting Started with Dev Containers`
 - [x] Remote Repositories @joyceerhl 
    - Already shows in remote
 - Dev Containers

**Comment by joyceerhl** [comment]
We also have
- Continue Working in New Local Clone (contributed by git extension and available in remote windows like Codespaces)
- Continue Working in VS Code for the Web (contributed by Remote Repositories in virtual workspaces and the GitHub extension in desktop git repos)

@aeschli would you suggest to show these commands in the remote indicator as well, and if so do we have a remote group that they intuitively belong to?

**Comment by aeschli** [comment]
@joyceerhl These command, they are like a `Reopen in...`, right? We already have such command for Dev containers and WSL (`Reopen Folder in WSL`), so yes, they fit well in the remote menu
I'd put the first one in the Codespaces category, the second one in Remote Repositories.
The third one is tricky. We could add a vscode.dev category, but then maybe the second one should also go in there.

Note that this issue is more about which remote commands to show in **every** remote window. The command you list only work in certain windows, if I understand correctly. Please ping me if I misunderstood.
