### ISSUE TITLE
[Remote Tunnels] "The workbench failed to connect to the server" "error connecting to vscode server socket ... No such file or directory (os error 2)"

### ISSUE THREAD

**Issue by ggondim** [microsoft/vscode-remote-release#7742]
I was using Remote Tunnels and the browser client simply disconnected from host.

I tried to reconnect and to restart server with `code-insiders tunnel unregister` then `code-insiders tunnel` and it gives me this error:

![image](https://user-images.githubusercontent.com/2074685/208490010-79944c03-0494-46c0-9370-f6d27ebd1dcb.png)

Console output in Developer Tools:

<img width="681" alt="image" src="https://user-images.githubusercontent.com/2074685/208491134-14757610-69f9-4b94-b075-8f841415e337.png">

**Comment by connor4312** [comment]
What's the status of the tunnel on the remote machine, are you able to see if there are any logs there?

**Comment by pedestriantactics** [comment]
I'm also having a similar issue

An unexpected error occurred that requires a reload of this page.
The workbench failed to connect to the server (Error: WrappedError(WrappedError { message: "error spawning server", original: "No such file or directory (os error 2)" }))

The latest two logs from the console on the remote machine are below

2023-07-21 09:46:30.785 [info] [2023-07-21 09:46:30] info [rpc.1] Starting server...

2023-07-21 09:46:34.895 [info] [2023-07-21 09:46:34] info [rpc.1] Disposed of connection to running server.

**Comment by connor4312** [comment]
I would need more logs than that...

Closing this issue as we haven't hear back from the reporter.
