### ISSUE TITLE
Could not establish connection to "localhost".

### ISSUE THREAD

**Issue by juliussimonelli** [microsoft/vscode-remote-release#775]
Issue Type: <b>Bug</b>

I had been using the same method to create an SSH connection between my docker container on AWS and VSCode using Remote - SSH (nightly) and it was working and recently it stopped working. I create a port forwarding ssh to a docker instance inside EC2 with something like this `ssh -L 2201:localhost:2222 user@host -N -i ~/.ssh/id_rsa -v`. user@host is an AWS instance running a docker container and I publish port 2222 when I create it the docker container, but I have to map port 2201 on the host to port 2222 in the container. Then I connect to it using a config file that looks like:

```
Host *
     User root
     Port 2201
     IdentityFile ~/id_rsa(base)
```

Then in VSCode I go to "Remote-SSH: Connect to Host" and enter `localhost`.

This had been working but now it doesn't. I get a message saying "Could not establish connection to "localhost"."

Here's the output from Remote - SSH:

```
remote-ssh-nightly@2019.6.29700
darwin x64
SSH Resolver called for "ssh-remote+localhost", attempt 1
SSH Resolver called for host: localhost
Setting up SSH remote "localhost"
Using commit id "9ff8ae037e8e6109d65e4b5e3eb3dc60cc187e21" and quality "insider" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_7.9p1, LibreSSL 2.7.3
Using SSH config file "/Users/juliussimonelli/config"
Install and start server if needed
> Installing to /root/.vscode-server-insiders/bin/9ff8ae037e8e6109d65e4b5e3eb3dc60cc187e21...
> Downloading with wget
> SHELL=/bin/bash
> SSH_CLIENT=172.17.0.1 59258 22
> USER=root
> VSCODE_AGENT_FOLDER=/root/.vscode-server-insiders
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
> MAIL=/var/mail/root
> PWD=/root/.vscode-server-insiders/bin/9ff8ae037e8e6109d65e4b5e3eb3dc60cc187e21
> LANG=en_US.UTF-8
> __GLX_VENDOR_LIBRARY_NAME=nvidia
> HOME=/root
> SHLVL=2
> LOGNAME=root
> SSH_CONNECTION=172.17.0.1 59258 172.17.0.2 22
> LESSOPEN=||/usr/bin/lesspipe.sh %s
> _=/usr/bin/printenv
> OLDPWD=/root
> 
> 401b4cf8-f98f-4928-bb35-f06bab602b35##25##
> wget: unrecognized option '--show-progress'
> Usage: wget [OPTION]... [URL]...
> 
> Try `wget --help' for more options.
"install" terminal command done
Received install output: Try `wget --help' for more options.
Failed to parse remote port from server output: Try `wget --help' for more options.

ConfigFileWatcher: start watching file:///Users/juliussimonelli/config
ConfigFileWatcher: adding save listener
ConfigFileWatcher: adding close listener
ConfigFileWatcher: closing walkThrough:/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fcontrib%2Fwelcome%2Fpage%2Fbrowser%2Fvs_code_welcome_page%22%7D
------
```

VS Code version: Code - Insiders 1.36.0-insider (9ff8ae037e8e6109d65e4b5e3eb3dc60cc187e21, 2019-06-21T05:18:36.348Z)
OS version: Darwin x64 18.6.0
Fetching remote diagnostics for 'SSH' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_5031116|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed.
</details>Extensions: none

**Comment by roblourens** [comment]
This should be fixed now, I don't use that wget option anymore

**Comment by juliussimonelli** [comment]
Works again. Thank you!
