### ISSUE TITLE
Cannot "Attach Visual Studio Code" on a container in a remote machine connected using SSH

### ISSUE THREAD

**Issue by hsm207** [microsoft/vscode-remote-release#7759]
- VSCode Version:  1.74.1 (Universal)
- Local OS Version: macOS Ventura Version 13.0 (22A380)
- Remote OS Version: Ubuntu 20.04.5 LTS (Focal Fossa)
- Remote Extension/Connection Type: SSH and Containers

- Logs:

```
[18395701 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[18395702 ms] stream is closed
[18481889 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[18481891 ms] stream is closed
```

Steps to Reproduce:

1. SSH to a remote machine e.g. an EC2 instance on AWS
2. Bring up the docker-compose deployment in this [repo](https://github.com/hsm207/haystack-weaviate-docker-compose) 
3. Try to "Attach to Visual Studio Code" on any of the containers

You will see the following message:

![image](https://user-images.githubusercontent.com/2398765/209111761-1cce201e-7423-4d97-87ed-3a405b7a3449.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
What is the log in `Show Log`? Does the Docker extension show the containers?

**Comment by hsm207** [comment]
@chrmarti thanks for looking into this. I'm unable to reproduce the issue anymore. I upgraded to VS Code 1.74.2. It could be that I installed an older version of docker-compose in the VM earlier.

At the moment, this works:

```
Docker version 20.10.22, build 3a2c30b
docker-compose version 1.29.2, build unknown
```
