### ISSUE TITLE
dev containers: git commit.gpgsign + user.signingkey should be carried into the container

### ISSUE THREAD

**Issue by lflfm** [microsoft/vscode-remote-release#7763]
By default the git username and email are carried into the dev container and that's great; but the commits are not signed because `commit.gpgsign` and `user.signingkey` are not.
Since the GPG keys are also available in the dev containers, these settings could be carried over as well.

edit: the GPG private keys are not available in the container, they should be also...

**Comment by lflfm** [comment]
Actually, just realized that the private key is actually not working in the container, just the public ones... so I'm editing the issue to ask that the private key is also accessible in there

**Comment by chrmarti** [comment]
We copy the `~/.gitconfig` file into the container, is that where the two settings are?

Do you have the gpg-agent running locally? We forward that into the container. Could you append the log from when you open a dev container? (`F1` > `Dev Containers: Show Container Log`)
