### ISSUE TITLE
Object `initializeCommand` is not working

### ISSUE THREAD

**Issue by sarisia** [microsoft/vscode-remote-release#7765]
- VSCode Version:
- Local OS Version:

```
Version: 1.75.0-insider (user setup)
Commit: 6ed4d436a9b6ae131732f4e2a723868231f4473a
Date: 2022-12-23T05:21:57.802Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
```

Also tested in VSCode v1.74.2, Dev Containers v0.266.1

- Remote OS Version:
- Remote Extension/Connection Type: Containers

Setting the object as `initializeCommand` in devcontainer.json does not work (the command is not executed).

- Logs: [initializeCommand-object.log](https://github.com/microsoft/vscode-remote-release/files/10296990/initializeCommand-object.log)

Steps to Reproduce:

1. Use the following `.devcontainer/devcontainer.json`

```jsonc
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/ubuntu
{
	"name": "Ubuntu",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/base:jammy",

	// "initializeCommand": "touch ${localWorkspaceFolder}/test"

	"initializeCommand": {
		"touch-test1": "touch ${localWorkspaceFolder}/test1",
		"touch-test2": "touch ${localWorkspaceFolder}/test2"
	}
}
```

2. Command palette -> Dev Containers: Reopen in Container
3. Devcontainer starts without executing `initializeCommand` (No log lines regarding initializeCommand)

Remarks:

- setting the string as `initializeCommand` works as expected (log: [initializeCommand-string.log](https://github.com/microsoft/vscode-remote-release/files/10297001/initializeCommand-string.log))
- devcontainer.json docs says `initializeCommand` supports object notation, but is not allowed in schema.json
(see https://github.com/devcontainers/spec/issues/168)

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by justin-mccann** [comment]
We ran into this issue today with extension `v0.292.0`, and the same behavior as documented here. 

As we're adding more commands into the startup sequence, having a way to separate them out instead of creating one large command chain would be useful.

**Comment by joshspicer** [comment]
From what I can can see in the [reference implementation](https://github.com/devcontainers/cli/blob/3b8e16506456b4d50d05a6056eb65cf8a28ee834/src/spec-node/utils.ts#L411) it was never implemented this way and was likely a documentation error. That said, I agree that it seems very useful. I'll investigate what it would take to implement this.  

There also might be reason that this wasn't implemented, cc/ @chrmarti any thoughts? I don't see any reason we shouldn't support this.

**Comment by joshspicer** [comment]
I've put up a change here pending review: https://github.com/devcontainers/cli/pull/514

**Comment by sarisia** [comment]
It's released and seems this can be closed now
