### ISSUE TITLE
_REMOTE_USER_HOME not set for features in all cases.

### ISSUE THREAD

**Issue by Clockwork-Muse** [microsoft/vscode-remote-release#7767]
When a devcontainer installs both the `common-utils` feature and some other  (possibly only local?) feature, `_REMOTE_USER_HOME` is present but not set when `"remoteUser"` is specified to the user created by the `common-utils` feature.

- VSCode Version: 1.74.2
- Local OS Version: Ubuntu 22.04
- Remote OS Version: Ubuntu 22.04
- Remote Extension/Connection Type: Containers
- Logs: [devcontainer.log](https://github.com/microsoft/vscode-remote-release/files/10297391/devcontainer.log)

[repro.zip](https://github.com/microsoft/vscode-remote-release/files/10297315/repro.zip)

Steps to Reproduce:

1. Unzip `repro.zip`, and open the `feature_install` folder in VS Code.
2. Follow the prompt to reopen in a dev container
3. After it opens, run `cat /printenv.env`, and observe that although `_REMOTE_USER_HOME` is present, it isn't set.

This occurs even though at the time the second feature runs the remote user exists and has a home directory.

(The original [test case for these variables](https://github.com/microsoft/vscode-remote-release/issues/7404)).
I haven't been able to run the repro on insiders - I can't install the devcontainers extension due to an "unknown error".

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
We determine `_REMOTE_USER_HOME` before any features run.

**Comment by chrmarti** [comment]
Continuing in https://github.com/devcontainers/cli/issues/331. Thanks.
