### ISSUE TITLE
Add a widget showing info (monitoring) about remote computer

### ISSUE THREAD

**Issue by alainesp** [microsoft/vscode-remote-release#7770]
Adding a widget that shows info on the remote computer:

Usage of CPU, RAM, Disk space, Network, and GPUs. A very basic remote task manager. Support in settings to show or hide this UI.

When developing on a remote PC this may be useful.

**Comment by chrmarti** [comment]
Covered by extensions like https://marketplace.visualstudio.com/items?itemName=mutantdino.resourcemonitor I think.
