### ISSUE TITLE
this tool works well but it clear the jupiter session whenever reconnect

### ISSUE THREAD

**Issue by huynhducloi00** [microsoft/vscode-remote-release#7771]
If i use SSH with this tool and also use vscode Jupyter extension, i manage to get jupyter notebook run on the remote computer, however, the session (all output cell results) are cleared whenever reconnect.
this is a bad user experience. The idea of running on the remote machine is to partially make data persistent.

**Comment by eleanorjboyd** [comment]
Hi! Can you include screenshots/ videos? Additionally can you send over the logs from remote-ssh? You can find it via `view` then `output` then select `remote-ssh` from the dropdown. Thanks!
