### ISSUE TITLE
Attach Visual Studio Code from other extension

### ISSUE THREAD

**Issue by cat-deploy-unsafe** [microsoft/vscode-remote-release#7775]
It is able to attach to a ssh container and open a new vscode window for that container **at other extensions**? Is there any API to do this? like Kubernetes command `Attach Visual Studio Code`? I think it might be much helpful if providing this API.

ref:
https://github.com/microsoft/vscode-remote-release/issues/12

🚨 The issue tracker is not for questions 🚨

If you have a question about VS Code, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code and about
VS Code Remote on https://stackoverflow.com/questions/tagged/vscode-remote.

**Comment by chrmarti** [comment]
I think the `remote-containers.attachToRunningContainer` command would do that when you are connected with Remote-SSH. You can pass the container id as the first argument. (This also works locally with local containers.)
