### ISSUE TITLE
ability to change user in the remote ssh workspace session

### ISSUE THREAD

**Issue by maliknajjar** [microsoft/vscode-remote-release#7777]
Can you implement a way to change the user in a remote ssh session like we do in the terminal using the `su - user`
for security reasons I can't access root directly.

Thanks.

**Comment by eleanorjboyd** [comment]
Hello! Are you asking to be able to change the user during a session or when creating a new connection to a remote machine?

**Comment by maliknajjar** [comment]
during a session
so basically in my job we have ssh access to only a normal user in the server that has not privileges. and then we run `su -` to switch to the root user and edit some files.
the problem is that in ssh-remote extension when I ssh to the normal user I cant edit files so I need a way to switch the root user in vs code to be able to edit those files.

**Comment by eleanorjboyd** [comment]
Hello! Would it be possible to do the switch in a remote command that is passed in to the ssh connection command? This would make the switch before we began spinning up the server.

**Comment by maliknajjar** [comment]
Sorry for not responding fast. 
yes that would solve the problem. actually I tried to pass the command in the ssh connection command like this: 
```ssh user@ipAdress "su -"``` 
but its not supported currently in the vscode ssh extension

**Comment by eleanorjboyd** [comment]
Hello! I realized this is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/690. Please look here for solutions or to stay up to date on changes. Thanks!
