### ISSUE TITLE
specifying --platform in .devcontainer.json

### ISSUE THREAD

**Issue by AbdulAbCellera** [microsoft/vscode-remote-release#7779]
This is more of a question than an issue:

Host: `macOS arm64`
Image: `mcr.microsoft.com/devcontainers/base:jammy`

```
>> docker manifest inspect mcr.microsoft.com/devcontainers/base:jammy
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1786,
         "digest": "sha256:54d1fd0219908ba82b67230aabf350cf72dcab012d48111dccaf18209a56d1e4",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1786,
         "digest": "sha256:aec79b5e88157fa7e4b3ec9af83a48bce0f1435ee982ecd65680c27a3ab877af",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```
when I choose the vscode command `Rebuild and Reopen in Container`, I get a container with an `arm64` arch (matching host). Setting `export DOCKER_DEFAULT_PLATFORM=linux/amd64` in `~/.zshrc` did not help.

The Question:
- how to specify `--platfrom=linux/amd64` in .devcontainer.json

**Comment by AbdulAbCellera** [comment]
This worked for me     
"image": "mcr.microsoft.com/devcontainers/base:jammy@sha256:54d1fd0219908ba82b67230aabf350cf72dcab012d48111dccaf18209a56d1e4",

However, if I want the latest image this would not do it.

**Comment by chrmarti** [comment]
You could use a Dockerfile with `--platform` in `FROM`: https://docs.docker.com/engine/reference/builder/#from
