### ISSUE TITLE
Nightly build: Failed to parse remote port from server output

### ISSUE THREAD

**Issue by abpprkonsalting** [microsoft/vscode-remote-release#778]
- VSCode Version: June 2019 (version 1.36) Nightly
- Local OS Version: MacOS High Sierra
- Remote OS Version:  Raspbian GNU/Linux 9 (stretch)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Just trying to connect to the raspberry pi does not work anymore. Before today everything worked just fine.

Output:

> Found existing installation at /home/pi/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01...
> Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Checking server status with wget
> bec1e031-feeb-4a62-9e0f-494278b499ed==41343====
"install" terminal command done
Received install output: bec1e031-feeb-4a62-9e0f-494278b499ed==41343====
Failed to parse remote port from server output: bec1e031-feeb-4a62-9e0f-494278b499ed==41343====

Up until today everything was fine. I've tried a lot of things (removing extension in host and guest, deleting folders, etc.), but nothing helps. I've research similar issues in other recent reports but none of the proposed solutions helps.

**Comment by KapitanOczywisty** [comment]
Last version which worked for me was `2019.6.28281` and `2019.6.29213` was already broken. Extension after that update expects 2 ports in response, but server gives only one. Even wiping out vscode from server didn't solve that. I've disabled updates and I'm working on `2019.6.28281` which seems to be stable.
Other similar report #767

**Comment by abpprkonsalting** [comment]
> Last version which worked for me was `2019.6.28281` and `2019.6.29213` was already broken. Extension after that update expects 2 ports in response, but server gives only one. Even wiping out vscode from server didn't solve that. I've disabled updates and I'm working on `2019.6.28281` which seems to be stable.
> Other similar report #767

Uff, The last one that worked for me before I posted yesterday was 2019.6.23944. I did rollback to it during my steps to fix the problem, but really don't remember if tried 2019.6.28281, I think no. Anyway I rolled back to 2019.6.28281 and it's up and well again. :-D

Maybe my issues were related too that yesterday when I rolled back I did it with all three extensions to versions 2019.6.23... [ "Remote - SSH Editing Configuration Files (Nightly)" & "Remote - SSH Explorer (Nightly)" ]. Now I just rolled back "Remote - SSH (Nightly)", and the other two remained in their current state.

For reference, now my configuration is:

Remote - SSH (Nightly) 2019.6.28281
Remote - SSH Editing Configuration Files (Nightly) 2019.6.29213
Remote - SSH Explorer (Nightly)" ]. Now I just rolled back 2019.6.29213

**Comment by KapitanOczywisty** [comment]
I think this should stay open, issue still need to be fixed for future versions.

**Comment by abpprkonsalting** [comment]
Yes, sorry, I mistake the button.

**Comment by luboslav** [comment]
I got same error connecting to apline.

<details>
  <summary>My configuration</summary>
<pre>
VSCode - latest insiders (1.36.0)
Remote - SSH (Nightly) 2019.6.38785
Remote - SSH: Editing Configuration Files (Nightly) 2019.6.38785
Remote - SSH: Explorer (Nightly)  2019.6.38785
</pre>
</details>

<details>
  <summary>Error log</summary>
<pre>
remote-ssh-nightly@2019.6.38785
win32 x64
SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a226c6f63616c686f7374222c2275736572223a22726f6f74227d", attempt 1
SSH Resolver called for host: root@localhost
Setting up SSH remote "localhost"
Using commit id "e73ef9a00c8bdbd84b21557737cc2c430aaeac51" and quality "insider" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
Install and start server if needed
> 
> root@localhost's password:
> 
> 
> ls: unrecognized option: sort=time
> 
> BusyBox v1.27.2 (2018-06-06 09:08:44 UTC) multi-call binary.
> 
> Usage: ls [-1AaCxdLHRFplinshrSXvctu] [-w WIDTH] [FILE]...
> 
> List directory contents
> 
>         -1      One column output
>         -a      Include entries which start with .
>         -A      Like -a, but exclude . and ..
>         -x      List by lines
>         -d      List directory entries instead of contents
>         -L      Follow symlinks
>         -H      Follow symlinks on command line
>         -R      Recurse
>         -p      Append / to dir entries
>         -F      Append indicator (one of */=@|) to entries
>         -l      Long listing format
>         -i      List inode numbers
>         -n      List numeric UIDs and GIDs instead of names
>         -s      List allocated blocks
>         -lc     List ctime
>         -lu     List atime
>         --full-time     List full date and time
>         -h      Human readable sizes (1K 243M 2G)
>         --group-directories-first
>         -S      Sort by size
>         -X      Sort by extension
>         -v      Sort by version
>         -t      Sort by mtime
>         -tc     Sort by ctime
>         -tu     Sort by atime
>         -r      Reverse sort order
>         -w N    Format N columns wide
>         --color[={always,never,auto}]   Control coloring
> Installing to /root/.vscode-server-insiders/bin/e73ef9a00c8bdbd84b21557737cc2c430aaeac51...
> Downloading with wget
> --2019-06-28 10:42:18--  https://update.code.visualstudio.com/commit:e73ef9a00c8bdbd84b21557737cc2c430aaeac51/server-linux-x64/inside
> r
> Resolving update.code.visualstudio.com...
> Resolving update.code.visualstudio.com... 51.144.164.215
> Connecting to update.code.visualstudio.com|51.144.164.215|:443...Connecting to update.code.visualstudio.com|51.144.164.215|:443... connected.
> 
> HTTP request sent, awaiting response...
> HTTP request sent, awaiting response... 302 Found
> Location: https://az764295.vo.msecnd.net/insider/e73ef9a00c8bdbd84b21557737cc2c430aaeac51/vscode-server-linux-x64.tar.gz [following]
> --2019-06-28 10:42:18--  https://az764295.vo.msecnd.net/insider/e73ef9a00c8bdbd84b21557737cc2c430aaeac51/vscode-server-linux-x64.tar.
> gz
> Resolving az764295.vo.msecnd.net... 152.199.19.160
> Connecting to az764295.vo.msecnd.net|152.199.19.160|:443...
> Connecting to az764295.vo.msecnd.net|152.199.19.160|:443... connected.
> 
> HTTP request sent, awaiting response...
> HTTP request sent, awaiting response... 200 OK
> Length: 26780179 (26M) [application/gzip]
> Saving to: 'vscode-server-linux-x64.tar.gz'
> 
>           vscode-se   0%[                    ]       0  --.-KB/s
>          vscode-ser   5%[>                   ]   1.32M  4.60MB/s
>         vscode-serv  15%[==>                 ]   4.05M  8.33MB/s
> 
>        vscode-serve  26%[====>               ]   6.73M  9.74MB/s
>       vscode-server  36%[======>             ]   9.28M  10.4MB/s
>      vscode-server-  46%[========>           ]  11.90M  10.9MB/s
>     vscode-server-l  56%[==========>         ]  14.54M  11.2MB/s
>    vscode-server-li  67%[============>       ]  17.30M  11.6MB/s
>   vscode-server-lin  78%[==============>     ]  19.96M  11.7MB/s
>  vscode-server-linu  85%[================>   ]  21.88M  11.2MB/s
> vscode-server-linux  93%[=================>  ]  23.88M  11.1MB/s
> scode-server-linux-  99%[==================> ]  25.35M  10.8MB/s
> Download completex-  99%[==================> ]  25.35M  10.8MB/s
> vscode-server-linux 100%[===================>]  25.54M  10.7MB/s    in 2.4s
> 
> 2019-06-28 10:42:21 (10.7 MB/s) - 'vscode-server-linux-x64.tar.gz' saved [26780179/26780179]
> 
> 
> SSH_CONNECTION=10.0.2.2 60641 10.0.2.15 22
> USER=root
> PWD=/root
> HOME=/root
> SSH_CLIENT=10.0.2.2 60641 22
> MAIL=/var/mail/root
> SHELL=/bin/ash
> SHLVL=2
> VSCODE_AGENT_FOLDER=/root/.vscode-server-insiders
> LOGNAME=root
> PATH=/bin:/usr/bin:/sbin:/usr/sbin
> _=/bin/printenv
> OLDPWD=/root/.vscode-server-insiders/bin/e73ef9a00c8bdbd84b21557737cc2c430aaeac51
> Starting server...
> 
> Waiting for server log...
> 
> Waiting for server log...
> 
> Waiting for server log...
> 
> Waiting for server log...
> 
> Waiting for server log...
> 
> Waiting for server log...
> 
> Waiting for server log...
> 
> 
> *
> 
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Server did not start successfully. Full server log >>>
> /root/.vscode-server-insiders/bin/e73ef9a00c8bdbd84b21557737cc2c430aaeac51/node: /usr/lib/libstdc++.so.6: no version information avai
> lable (required by /root/.vscode-server-insiders/bin/e73ef9a00c8bdbd84b21557737cc2c430aaeac51/node)
> /root/.vscode-server-insiders/bin/e73ef9a00c8bdbd84b21557737cc2c430aaeac51/node: /usr/lib/libstdc++.so.6: no version information avai
> lable (required by /root/.vscode-server-insiders/bin/e73ef9a00c8bdbd84b21557737cc2c430aaeac51/node)
> /root/.vscode-server-insiders/bin/e73ef9a00c8bdbd84b21557737cc2c430aaeac51/node: /usr/lib/libstdc++.so.6: no version information avai
> lable (required by /root/.vscode-server-insiders/bin/e73ef9a00c8bdbd84b21557737cc2c430aaeac51/node)
> /root/.vscode-server-insiders/bin/e73ef9a00c8bdbd84b21557737cc2c430aaeac51/node: /usr/lib/libstdc++.so.6: no version information avai
> lable (required by /root/.vscode-server-insiders/bin/e73ef9a00c8bdbd84b21557737cc2c430aaeac51/node)
> /root/.vscode-server-insiders/bin/e73ef9a00c8bdbd84b21557737cc2c430aaeac51/node: /usr/lib/libstdc++.so.6: no version information avai
> lable (required by /root/.vscode-server-insiders/bin/e73ef9a00c8bdbd84b21557737cc2c430aaeac51/node)
> /root/.vscode-server-insiders/bin/e73ef9a00c8bdbd84b21557737cc2c430aaeac51/node: /usr/lib/libstdc++.so.6: no version information avai
> lable (required by /root/.vscode-server-insiders/bin/e73ef9a00c8bdbd84b21557737cc2c430aaeac51/node)
> 
> 
> #
> # Fatal error in , line 0
> # Check failed: SetPermissions(protect_start, protect_size, PageAllocator::kReadExecute).
> #
> #
> #
> #FailureMessage Object: 0x783a076bd7c0Illegal instruction
> <<< End of server log
> 
"install" terminal command done
Received install output: <<< End of server log
Failed to parse remote port from server output: <<< End of server log
</pre>

</pre>
</details>

**Comment by KapitanOczywisty** [comment]
> I got same error connecting to apline.

In your case there are missing libraries [Linux Prerequisites](https://code.visualstudio.com/docs/remote/linux)

**Comment by roblourens** [comment]
It looks like you might have been trying this with a slightly out of date VS Code Insiders version. Can you check that vscode and the extension are both fully updated and try again?

**Comment by kylrth** [comment]
I get this any time I open a specific folder on the remote:

```
Failed to parse remote port from server output: =40153==
```

I'm able to successfully connect if I just do `Remote-SSH: Connect to Host...`, but as soon as I try to open a folder I get the same error.

**Comment by roblourens** [comment]
@kylrth please open your own issue with the full log
