### ISSUE TITLE
Slurm-managed HPC remote debug

### ISSUE THREAD

**Issue by soumickmj** [microsoft/vscode-remote-release#7780]
Hello,
I'm trying to debug remotely on a slurm-managed HPC.

Here we can log jobs using salloc and have interactive jobs using srun.
But, this HPC's setup does not allow us to use SSH to go to the allocated compute node. 
The SSH can only be used to enter the login node, then have to use the job system.
Now, as we cannot SSH to the allocated compute node even from the login node, I cannot use ProxyJump host to reach the compute node.

If I have my VSCode connected to the HPC, it is connected to the login node. 
If I use srun from the terminal, I do get the terminal for the compute node - but that is not valid when I start a debug. The debug starts always from the login node.

Is there any feature currently available or any workaround to be able to connect to the allocated compute node?

Thank you so much for your help :)

**Comment by eleanorjboyd** [comment]
closing this in favor of the discussion we have on this issue, https://github.com/microsoft/vscode-remote-release/issues/1722. Please add your input there as part of that longer discussion on this issue and feature request. Thanks!
