### ISSUE TITLE
How to apply the language pack that comes with the [Vscode-WSL] plugin package -- set to Chinese

### ISSUE THREAD

**Issue by Luichuns** [microsoft/vscode-remote-release#7785]
Encountered some difficulties,
Install WSL plugin in Vscode, this plugin has other language packs, how to set up the use of this language pack, I want the language Chinese.
Trouble :)

如何应用 [Vscode-WSL] 插件包附带的语言包 -- 设置为中文

遇到了些难题，
在Vscode中安装WSL插件，这个插件是有其他语言包的，怎么设置使用这个语言包，我想要的语言时中文。
麻烦了:)

**Comment by bamurtaugh** [comment]
Could you please let us know what trouble you encountered, and any steps we could take to reproduce this? Thank you!
