### ISSUE TITLE
PROPOSAL: allow opening of SSH / FISH urls

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/vscode-remote-release#779]
As Fish and SSH support landed via Plugins we will need a way to directly open urls via click in vscode 

## Features
Open Single File via clicking on a url(link)
Open Folder via url(link)

To make that clear i am talking about urls for example on a webpage. Not inside vscode while that would be sure additional possible then as side effect

**Comment by roblourens** [comment]
Can you explain what sort of urls you are talking about? What's a fish url?

**Comment by frank-dspeed** [comment]
@roblourens 

# for example 
```
<a href="vscode://ssh://29.29,28,28">Open Master</a>
```
Placed in a .html file should open vscode with the ssh://* url


```
<a href="vscode://file:///home/frank/projects/master">Open local</a>
```
Placed in a .html file should open vscode with the /home/frank/projects/master folder opened

**Comment by frank-dspeed** [comment]
i think this issue belongs to both repos vscode main and the ssh extension should extend the function of the main repo

**Comment by frank-dspeed** [comment]
# Documentation what to do
https://support.shotgunsoftware.com/hc/en-us/articles/219031308-Launching-applications-using-custom-browser-protocols

**Comment by frank-dspeed** [comment]
https://github.com/liximomo/vscode-remote-fs

this extension does add the expected behavior we should change it so that this works now nativ with the ssh extension

**Comment by frank-dspeed** [comment]
Is already in mainline now.
