### ISSUE TITLE
remote-ssh + github-remote

### ISSUE THREAD

**Issue by tymoor** [microsoft/vscode-remote-release#7794]
I use remote-ssh for development on offline hardware - and want to maintain my repo in Github.  I'd like to be able to push/pull my project from my local (internet connected) dev machine to/from github, even while that code 'lives' on the remote-ssh machine.

**Comment by joshspicer** [comment]
You should be able to use git to clone your repo on any number of devices, pushing and pulling code from your remote GitHub repo however you like.
