### ISSUE TITLE
Hard crash on Windows when parsing  `IdentityFile %USERPROFILE%\.ssh\id_rsa` in ssh config

### ISSUE THREAD

**Issue by stoooops** [microsoft/vscode-remote-release#7797]
Type: <b>Bug</b>

When I set the C:\path\to\config\ssh.config file with the following configuration:
```
Host remote
   HostName remote
   User bar
   IdentityFile  %USERPROFILE%\path\to\id_rsa
```
The user "bar" is not being respected, and in the console I see it attempting to connect with the local host user name, "foo@remote", which does not exist. This is causing an error and preventing a successful connection.

Steps to reproduce:

Set the ssh.config file with the specified configuration.
Attempt to establish a connection using the "remote" host.
Expected result:
The user "bar" should be respected and the connection should be established using "bar@remote".

Actual result:
The user "foo" is used and the connection fails due to the non-existent user "foo@remote".

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-56-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.36GB free)|
|Process Argv|--crash-reporter-id 919c2dfd-2513-4d26-bae1-00a1d2600cd9|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.1.100|
|OS|Linux x64 5.15.0-56-generic|
|CPUs|Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 x 3800)|
|Memory (System)|31.29GB (23.39GB free)|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.13.5
better-cpp-syntax|jef|1.17.2
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.0.3
open-in-browser|tec|2.0.0
doxdocgen|csc|1.4.0
vscode-svgviewer|css|2.0.0
copilot|Git|1.65.7705
go|gol|0.37.0
better-cpp-syntax|jef|1.17.2
solidity|Jua|0.0.141
rainbow-csv|mec|3.5.0
vscode-docker|ms-|1.23.3
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2023.1.10
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.9
cpptools-extension-pack|ms-|1.3.0
vetur|oct|0.36.1
LiveServer|rit|5.7.9
cmake|twx|0.0.17
volar|Vue|1.0.22

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723
vscsbc:30628655

```

</details>

**Comment by roblourens** [comment]
Please see https://github.com/microsoft/vscode-remote-release/wiki/Debugging-for-Remote-SSH and share logs from the Remote-SSH output channel.

That isn't the default ssh config location, so make sure you set the `remote.SSH.configFile` setting or use the default location

**Comment by stoooops** [comment]
Ok I want to describe what I'm seeing.

While repeating the steps to write a reply, I encounter TWO more bugs. 

## Bug 1 (found while reproducing, UI related):
Remove Explorer > Select "Remote" dropdown > Right Click > Remove From List.

The UI appears to not be removing them (except the first one). You click right click > remove from list and nothing happens. But if you restart the application, they are gone. So I suspect a bug in the UI code that is managing those UI elements, not in the backend part managing the config for that list.

**Comment by stoooops** [comment]
Now, here are the steps I filed the issue for. Before filing the issue, I repeated it back and forth over and over reliably.

But surprisingly, I seem to have hit a different, * worse * issue at the very end. I can't ssh at all to the remote host I'm blocked now!

Anyway, here's what I did:

## Medium Bug That I Filed Issue For (Can't setup passwordless, but not blocked)
Adding the setting:
![image](https://user-images.githubusercontent.com/3518037/211077361-4d079f4f-0a60-48b5-9e24-018b51369160.png)

file contents (I know it's linking to this correctly because when I had filepath typos I got I/O errors):
![image](https://user-images.githubusercontent.com/3518037/211077972-98b577ad-66ab-4cb7-99dd-ce1f96744685.png)

Restarting VS Code, it tries to use `coryg` NOT `dev`
![image](https://user-images.githubusercontent.com/3518037/211077628-bdbc31a1-90d2-4784-a113-197f0b62e9ce.png)

CTRL+C to cancel and see logs in terminal
![image](https://user-images.githubusercontent.com/3518037/211078295-1f04fe44-e209-4b3b-be59-9c573773464e.png)

Remove the setting again:
![image](https://user-images.githubusercontent.com/3518037/211078407-cc7b4bc2-c5a9-4676-858c-3b4ee89a8d90.png)

Restart the host:
Now, at this point, I THOUGHT I would just connect back to my programming session. I've been programming for about 12 hours in a row (haha).

BUT!

In reproducing these steps, I seem to have corrupted something and now I can't connect to the remote host AT ALL.

## SEVERE Issue Found While Reproducing Just Now (100% Blocked will get some sleep and revisit I guess)
Here is the NEW, SEVERE issue I'm seeing.

Basically, it's pretty simple. I login and it fails immediately, never prompting me for a password and seemingly never getting to the part where it would parse (and then log) the "User" (which was the original bug I was trying to file issue for.

## Questions
Please let me know if you need clarifications.

**Comment by stoooops** [comment]
I can leave this machine in this state for ~12-24 hours before I'll need to re-install to fix the SEVERE issue described blocking me.

Let me know if you want any debug info or something.

**Comment by stoooops** [comment]
To give a bit more context on your question (1), I was working with a list that looked like this:
```
foo
bar
baz
qux
```

I started by right-clicking on `foo` and selecting the option to Remove From List. This worked as expected, and the list was updated to:
```
bar
baz
qux
```

Next, I tried to remove `bar` in the same way, but nothing happened visually. The list remained unchanged:
```
bar
baz
qux
```

I also tried removing `baz`, but again, there was no visual change to the list:
```
bar
baz
qux
```

At this point, I restarted VS Code to see if that would resolve the issue. Upon reopening the tab, I saw that the list had been updated to:
```
qux
```

This suggests to me that the configuration was likely changed successfully on the backend, but something went wrong with the logic that manages the display of list items. I hope this additional information helps! Let me know if there's anything else I can provide.

**Comment by stoooops** [comment]
When I try to run the following command in WSL:
```
ssh -T -D 51909 "192.168.1.100" bash
```
I am unable to establish a connection. However, when I use the same public/private key pair in PuTTY, I am able to connect without being prompted for a password. I'm not sure if this is related, but I thought it was worth mentioning.

**Comment by stoooops** [comment]
I am trying to connect to `dev@remote` but it is doing `coryg@remote`.

Windows user is `coryg`
Linux user (remote) is `dev`. User `coryg` does not exist on this remote host.

**Comment by stoooops** [comment]
The way it crashes will not let me copy-paste the logs because my cursor cannot select the window, so here are pictures:
![image](https://user-images.githubusercontent.com/3518037/211104498-bef9c1f7-49ce-4fd8-9531-1e0f43ec1ca7.png)
![image](https://user-images.githubusercontent.com/3518037/211104665-6f020f83-236c-45c8-be98-0a820d7a2532.png)
![image](https://user-images.githubusercontent.com/3518037/211104798-6c4ca2c6-e1fd-4cab-8611-6c2f057d3669.png)
![image](https://user-images.githubusercontent.com/3518037/211104836-322688e5-eea8-4a8b-8d27-04a99d94efc3.png)
![image](https://user-images.githubusercontent.com/3518037/211104900-dec3644c-cfc7-43f9-9f28-079dad6e745d.png)

This is a pretty bad crash I would say. I cannot use my development machine remotely (although I can just walk over to the computer in the other room and use it no big deal).

If there is a log file somewhere on disk (windows) you can point me to, I would be happy to include it.

**Comment by stoooops** [comment]
Ok, I think have narrowed it down to the logic which processes `IdentityFile`.

Here are the cases:
```
#
# This works, but asks for password
# 
Host 192.168.1.100
  HostName 192.168.1.100
  User dev
```
```
#
# This fails with Load key "C:\\Users\\coryg\\dev\\id_rsa": invalid format
#
# This should work.
# 
Host 192.168.1.100
  HostName 192.168.1.100
  User dev
  IdentityFile C:\Users\coryg\dev\id_rsa
```
```
#
# This fails with Load key "C:/Users/coryg/dev/id_rsa": invalid format
#
# I think this should fail because the / should be \ on Windows
#
Host 192.168.1.100
  HostName 192.168.1.100
  User dev
  IdentityFile C:/Users/coryg/dev/id_rsa
```
```
#
# This crashes VS Code with "percent_expand: unknown key %U"
#
# I think this should fail because the / should be \ on Windows
#
Host 192.168.1.100
  HostName 192.168.1.100
  User dev
  IdentityFile %USERPROFILE%/dev/id_rsa
```
This is the one that has a bug and needs a patch:
```
#
# This crashes VS Code with "percent_expand: unknown key %U"
#
# This should work and not request password.
#
Host 192.168.1.100
  HostName 192.168.1.100
  User dev
  IdentityFile %USERPROFILE%\dev\id_rsa
```

**Comment by eleanorjboyd** [comment]
What happens when you run `ssh -G "192.168.1.100" | grep "^user "`? Additionally when you run `ssh -v "192.168.1.100"` does it print the correct identity file? In verbose logs that should be printed with text like `identity file` labeling it.

The remote-explorer question makes sense, I will try to replicate. Thanks!

**Comment by stoooops** [comment]
Man, I am not sure what's going on here, but your suggestion got me to run it from Command Prompt instead of WSL. 

I was able to reproduce the error directly from the command-line. This indicates to me the issue might not be VS Code related, although the behavior to crash is undesireable.

Here are the requested commands:
```cmd
# users on remote host: dev
C:\Users\coryg\.ssh>ssh -G "192.168.1.100" | findstr "^user "
user dev
userknownhostsfile ~/.ssh/known_hosts ~/.ssh/known_hosts2

# config file on local host. Notice cwd is .ssh/
C:\Users\coryg\.ssh>type config
Host 192.168.1.100
  HostName 192.168.1.100
  User dev
  IdentityFile %USERPROFILE%\.ssh\id_rsa

# requested command fails from command-line
C:\Users\coryg\.ssh>ssh -v 192.168.1.100
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
debug1: Reading configuration data C:\\Users\\coryg/.ssh/config
debug1: C:\\Users\\coryg/.ssh/config line 1: Applying options for 192.168.1.100
debug1: Connecting to 192.168.1.100 [192.168.1.100] port 22.
debug1: Connection established.
percent_expand: unknown key %U
```
Here is what ChatGPT says. I have tried all of these suggestions.
![image](https://user-images.githubusercontent.com/3518037/211123973-2d009000-90a7-412c-b1ec-59bad3ce843e.png)

Quite puzzling!

**Comment by stoooops** [comment]
Also this statement I made earlier:
```
# I think this should fail because the / should be \ on Windows
```
is false. I verified it reads it either way.

**Comment by eleanorjboyd** [comment]
>I was able to reproduce the error directly from the command-line
If the SSH command does not work from the command line then yes it is likely not a VS Code issue. I would suggest running the SSH command we output in the logs but removing different parameters (such as the -T parameter) to see if some part of the command is causing the break. I am going to close this issue since it is likely not VS Code but if you find a parameter that breaks your ssh command let me know as we do have some other people reporting the `-T` parameter does not work for them. Thanks!

**Comment by stoooops** [comment]
Can you please provide the syntax of a valid file on WIndows?

**Comment by stoooops** [comment]
I believe this is a bug. Here is the same issue filed against Win32-SSH. https://github.com/PowerShell/Win32-OpenSSH/issues/702

This is a full Microsoft software stack. I need help please.

**Comment by stoooops** [comment]
Re-opened as https://github.com/microsoft/vscode-remote-release/issues/7819 .

I need Microsoft developers to fix their SSH software stack please.

**Comment by stoooops** [comment]
If anyone finds this issue, my primary issue was taking online instructions too literally and using the string `IdentityFile %USERPROFILE%\.ssh\id_rsa` instead of `IdentityFile C:/Users/myname/.ssh/id_rsa`.

This causes OpenSSH to fail with an opaque error string:
```
percent_expand: unknown key %U
```
There are 7-8 places in `libopenssh` where this error string is used: https://github.com/openssh/libopenssh/search?q=percent_expand

I'm pretty sure this line in `auth.c` is the one that causes the authentication error when parsing (in my case), the IdentityFile vale: `libopenssh/ssh/auth.c`: https://github.com/openssh/libopenssh/blob/05dfdd5f54d9a1bae5544141a7ee65baa3313ecd/ssh/auth.c#L257
```c
// libopenssh/ssh/auth.c
// commit: 05dfdd5f54d9a1bae5544141a7ee65baa3313ecd
/*
 * Given a template and a passwd structure, build a filename
 * by substituting % tokenised options. Currently, %% becomes '%',
 * %h becomes the home directory and %u the username.
 *
 * This returns a buffer allocated by xmalloc.
 */
char *
expand_authorized_keys(const char *filename, struct passwd *pw)
{
	char *file, ret[MAXPATHLEN];
	int i;

	file = percent_expand(filename, "h", pw->pw_dir,
	    "u", pw->pw_name, (char *)NULL);

	/*
	 * Ensure that filename starts anchored. If not, be backward
	 * compatible and prepend the '%h/'
	 */
	if (*file == '/')
		return (file);

	i = snprintf(ret, sizeof(ret), "%s/%s", pw->pw_dir, file);
	if (i < 0 || (size_t)i >= sizeof(ret))
		fatal("expand_authorized_keys: path too long");
	xfree(file);
	return (xstrdup(ret));
}
```

To fix this on Windows 10 (and to fix Remote-SSH errors in VS Code), I replaced:
```ssh-config
Host example
    HostName example.com
    User user
    IdentityFile %USERPROFILE%\.ssh\id_rsa
```
with
```ssh-config
Host example
    HostName example.com
    User user
    IdentityFile C:\Users\myname\.ssh\id_rsa
```
in my `.ssh/config`, and then subsequently facepalmed when it worked.

You can use the following Batch script to help debug. Your specific issue may need a bit of tweaking, but this helped me solve an issue I had been facing for longer than I'm willing to admit publicly.
```bat
@echo off
REM Author: Cory Gabrielsen
REM Date: 2023-01-10
REM Description: This script will help you debug ssh issues by displaying the ssh config file
REM and the contents of the IdentityFile.  It will also run ssh -G test and display the results.
REM This script is intended to be run on a Windows machine.
REM

REM display the contents of the ssh config file located in the .ssh directory under
REM the user's profile.

REM Must pass the hostname as the first argument to this script
if "%1"=="" goto :usage

echo ^>        USERPROFILE: %USERPROFILE%
echo ^>        Running ssh -G %1...
ssh -G "%1" 2>&1 > ssh_G.txt
echo ^>        Result written to ssh_G.txt
echo ^>        ssh_G.txt contents:
set /p first_line=<ssh_G.txt
echo %first_line%
echo ....


echo ^>       Finding IdentityFile from ssh_G.txt...
set found=
rem search through the ssh_G.txt file for the IdentityFile line
for /f "tokens=2 delims= " %%i in ('findstr /i "identityfile" ssh_G.txt') do set found=%%i
for /f "tokens=2 delims= " %%i in ('findstr /i "identityfile" ssh_G.txt') do echo identityfile %%i
echo ^>       identityfile %found%

echo Connecting to host: %1...
ssh "%1"

rem usage instructions
:usage
echo.
echo Usage: debug_ssh.bat hostname
echo Example: debug_ssh.bat test.example.com
echo.
echo This script will help you debug ssh issues by displaying the ssh config file
echo and the contents of the IdentityFile.  It will also run ssh -G test and display the results.
echo This script is intended to be run on a Windows machine.
echo.
```

I think many people probably spent 10 seconds on this and used the correct string, but sometimes you just get the wrong idea of how to do something in your head and get stuck. I hope this can help anyone who deals with the `percent_expand` error coming from OpenSSH on Windows.

This also causes a hard crash in VS Code when using the Remote-SSH extension.
