### ISSUE TITLE
Code-insiders started from WSL doesn't return to console/ doesn't connect

### ISSUE THREAD

**Issue by Sieboldianus** [microsoft/vscode-remote-release#780]
Intro:

* I've searched and found 2 similar problems, but no solution reported there works for me and, even when following the guidance, my issue remains. See [46462](https://github.com/Microsoft/vscode/issues/46462) and [44540](https://github.com/Microsoft/vscode/issues/44540)
* I've installed the latest code-insiders release
* VSCode Version: 1.36.0-insider (user setup)
* OS Version: Windows 10 with latest patches

Steps to Reproduce:

1. Install Code-Insiders
2. Open WSL
3. type `code-insiders .`
4. a: Code insiders opens up in Windows, does not connect to WSL
4. b: WSL shows log output from code-insiders, e.g.:

```output
[main 2019-06-23T15:41:16.497Z] update#setState idle
[main 2019-06-23T15:41:46.501Z] update#setState checking for updates
[main 2019-06-23T15:42:02.481Z] update#setState idle
```

* same result when launching with `code-insiders . --disable-extensions`, launching with `code .` opens up regular vs code (doesn't leak, but also has no native WSL support). So, does this issue occur when all extensions are disabled? Yes!

My Path environment variables for `code` and `code-insiders`:

```
which code-insiders
/c/Users/[me]/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders
```

```
which code
/c/Program Files/Microsoft VS Code/bin/code
```

My WSL is based on the official Ubuntu 18.04, setup with [LxRunOffline](https://github.com/DDoSolitary/LxRunOffline)

* starting code-insiders with `code-insiders .` from WSL worked until the last week. So this issue didn't occur before the latest version of code-insiders.

**Comment by williamclot** [comment]
The error has been fixed with the latest update. Thank you!

**Comment by Sieboldianus** [comment]
Just tested, it works! Many thanks!

**Comment by Sieboldianus** [comment]
This issue needs to be reopened.

As of the newest version `112fa76c775ecb79ac2c9e9e5dba0d711d523543`, VS Code Insiders can't connect to WSL, again, and it doesn't return to shell after starting. Here's the output from WSL bash:

```bash
Updating VS Code Server to version 112fa76c775ecb79ac2c9e9e5dba0d711d523543
Removing previous installation...
Downloading: 100%
Unpacking: 100%

[main 2019-07-24T07:55:56.905Z] update#setState idle
[main 2019-07-24T07:56:03.294Z] Received resolved authority wsl+default
[main 2019-07-24T07:56:24.177Z] Resolving authority wsl+default
[main 2019-07-24T07:56:26.908Z] update#setState checking for updates
[main 2019-07-24T07:56:26.932Z] update#setState downloading
[main 2019-07-24T07:56:32.543Z] update#setState updating
```
