### ISSUE TITLE
Properly support Match statement in ssh config

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode-remote-release#7801]
With the[ recent update to our upstream config parsing library](https://github.com/cyjake/ssh-config/issues/58), we need to update our extension to this new release and then make sure it is compatible. All code related to "match" which can be done by the config parsing should be done there and not in the extension.

**Comment by eleanorjboyd** [comment]
make sure this use case works:

However, the standard way to separate the Match items documented in the manpage (ssh_config.5) is the comma ','. That causes misbehavior in the parsing library.
Therefore `host LabServer1,LabServer2 match xyz` would then work.

**Comment by joshspicer** [comment]
The library is already on a much newer version
