### ISSUE TITLE
fedora silverblue + dev containers (docker/podman)

### ISSUE THREAD

**Issue by PiotrJustyna** [microsoft/vscode-remote-release#7802]
I'm not sure this is an issue for vscode dev containers or for fedora, but probably worth asking anyway. I am having a difficult time getting vscode + dev containers extensions working on fedora silverblue 37.1.7 (immutable linux distro). On paper, the idea behind the os is very appealing, I just can't figure out how to properly configure vs code and this extension. Here is what I tried so far and every time I am getting the same problem: vscode does not work correctly with docker/podman.

* docker installed directly on the host machine (through `rpm-ostree`)
* my user can execute docker commands
* vs code installed through flatpak (and I can confirm I can invoke docker commands from the vs code terminal)
* vs code installed directly on the host machine (through `rpm-ostree` and I can confirm I can invoke docker commands from the vs code terminal)
* vs code configured to use podman (podman comes preinstalled in that os) instead of docker

In that last scenario (preinstalled podman + vs code configured to use podman instead of docker for dev containers), I am getting a silent failure when opening a repository in a dev container. When I check the output terminal which starts when the dev container is opening, I get the following message:

```
2023-01-06 19:40:13.076 [error] {"message":"Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /var/home/piotrjustyna/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /var/home/piotrjustyna/Documents/code/haskell-anywhere --log-level debug --log-format json --config /var/home/piotrjustyna/Documents/code/haskell-anywhere/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true","code":1} remote-containers.reopenInContainer {"value":"ms-vscode-remote.remote-containers","c":"ms-vscode-remote.remote-containers"}
```

When I use vs code with docker (instead of podman), vs code complains with a dialog upon opening a directory in a dev container which states:

`Current user does not have permission to run 'docker'. Try adding the user to the 'docker' group (Cancel/Documentation)`

even though I can execute docker commands from the vs code terminal (`whoami` ran in vs code terminal indicates that I'm running the command as myself). The `Documentation` button leads to the following resource: https://docs.docker.com/engine/install/linux-postinstall/ but that is unfortunately not 100% applicable in an immutable os.

So what I'm really reporting is a number of potential problems and maybe also a general question: is there a best practices document which handholds users trying to simply:

* set up an immutable os
* set up vs code
* install the dev cotnainers externsion
* get coding

a wiki like that would be very useful.

- VSCode Version: 1.74.2
- Local OS Version: fedora silverblue 37.1.7
- Local chip architecture: x64
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: irrelevant, problems using containers in general (docker + podman)

Steps to Reproduce:

1. open a directory in a remote container

**Comment by chrmarti** [comment]
Can you add a `docker-test.sh` to the PATH? E.g.:
```
#!/bin/sh

date >>~/devcontainer-test.log
whoami >>~/devcontainer-test.log
echo docker "$@" >>~/devcontainer-test.log
echo >>~/devcontainer-test.log

docker "$@"
```

And then let Dev Containers use that to see what is going on:
<img width="472" alt="image" src="https://user-images.githubusercontent.com/9205389/211327334-46b1596d-943b-4751-b9fe-39c042924777.png">

**Comment by PiotrJustyna** [comment]
Thank you @chrmarti. I switched back to docker (from podman) and what I'm getting in that file is:

```bash
[piotrjustyna@fedora ~]$ cat ~/devcontainer-test.log 
Tue Jan 10 02:09:46 PM GMT 2023
piotrjustyna
docker context ls --format {{json .}}

Tue Jan 10 02:09:46 PM GMT 2023
piotrjustyna
docker version --format {{.Server.APIVersion}}
```

**Comment by chrmarti** [comment]
Maybe the VS Code processes do not have the same permissions as you have in a terminal window? Unfortunately I'm not familiar with the details of Fedora Silverblue.

**Comment by PiotrJustyna** [comment]
Thanks @chrmarti. Probably best to ask the fedora community. The OS feels like a perfect for for developers, having dev containers working there would be amazing. I’ll try to update this issue once I have more information.

**Comment by PiotrJustyna** [comment]
Started a discussion here: https://discussion.fedoraproject.org/t/vscode-devcontainers/45874

**Comment by PiotrJustyna** [comment]
My question got answered on the fedora forum, now I can enjoy flatpak vs code with devcontainers and podman on silverblue. This is great! It's a dream set up for developers short on time like me.
