### ISSUE TITLE
Specifying build target in devcontainer.json when using docker-compose

### ISSUE THREAD

**Issue by arousta** [microsoft/vscode-remote-release#7810]
I can see in the [documentaion](https://containers.dev/implementors/json_reference/) there's a `build.target` option to set the build target for image/docker case. So this is only for dockerfile and no way to set this when using docker-compose?

**Comment by chrmarti** [comment]
You can add an additional `docker-compose.yml` (`"dockerComposeFile"` can have an array of strings value) and set the target in that. Does this help?

**Comment by arousta** [comment]
Yes, I tried and is working thanks :+1:
