### ISSUE TITLE
remote-SSH , Permission denied (publickey,gssapi-keyex,gssapi-with-mic)

### ISSUE THREAD

**Issue by alchemistlee** [microsoft/vscode-remote-release#7811]
Does this issue occur when all extensions are disabled?: no

- VS Code Version:  1.74.2 
- OS Version: macOS Ventura 13.1

Steps to Reproduce:

1. try to remote-ssh server in vscode, after enter ps and verify-code, 
2.had already added local pub-rsa to server ./ssh/authority-keys
3.then  ERROR occur , 
![image](https://user-images.githubusercontent.com/3377447/209548577-f495bbcc-e39e-4ea4-a589-4a66c72f18a4.png)

![image](https://user-images.githubusercontent.com/3377447/209546978-f8ca339f-0348-416c-a291-a93ba2af2f23.png)

my config
<img width="518" alt="image" src="https://user-images.githubusercontent.com/3377447/209568698-f4169786-720d-4655-a2a3-364365c4eea1.png">

**Comment by roblourens** [comment]
Please see https://github.com/microsoft/vscode-remote-release/wiki/Debugging-for-Remote-SSH
