### ISSUE TITLE
Test: Read user home folder and default shell from /etc/passwd

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#782]
#22 & #521

- [x] anyOS @deepak1556
- [x] anyOS @weinand

Complexity: 4

Verify for 1) a single container, 2) the Compose case and 3) when attaching to an existing container, that:
- When the Dockerfile does not set HOME / SHELL:
  - The VS Code server (`.vscode-sever-insiders`) is installed in the users home folder as given by /etc/passwd.
  - The default shell (when not overridden by settings) is also read form /etc/passwd.
- HOME and SHELL environment variables set in the Dockerfile override /etc/passwd.

See https://github.com/microsoft/vscode-remote-release/wiki/Remote-Containers-Smoke-Test for how to set up 1) and 2). 3) is probably easiest to test from a separate window against a container created with 1) or 2).

**Comment by weinand** [comment]
Useful Docker commands:
- create user with default shell in image: `RUN useradd -ms /bin/zsh newuser`
- switch to user: `USER newuser`
- set env var for image: `ENV HOME=/home/newuser`
