### ISSUE TITLE
Dev Container Error

### ISSUE THREAD

**Issue by ryhhtn** [microsoft/vscode-remote-release#7829]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.3
- OS Version: Windows 10

Steps to Reproduce:

1. Install VSCode
2. Install Dev Container (pre-release 0.269.0)
3. Select Remote Explorer pulldown `Containers`
4. Click `Refresh`

```
Error running command remote-containers.explorerTargetsRefresh: command 'remote-containers.explorerTargetsRefresh' not found. This is likely caused by the extension that contributes remote-containers.explorerTargetsRefresh.
```

**Comment by liligwu** [comment]
I encounter this error in 

> Version: 1.75.1 (user setup)
> Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
> Date: 2023-02-08T21:32:34.589Z
> Electron: 19.1.9
> Chromium: 102.0.5005.194
> Node.js: 16.14.2
> V8: 10.2.154.23-electron.0
> OS: Windows_NT x64 10.0.22621
> Sandboxed: Yes

Remote Development
v0.23.0

Remote Explorer
v0.2.0
