### ISSUE TITLE
Save remote password

### ISSUE THREAD

**Issue by githubUser982** [microsoft/vscode-remote-release#7832]
Yes I know this has been discussed before but the problem is as relevant as ever.

This is a basic feature that is required to stay relevant today. Users expect to be logged in when they open an app, or at least have their password saved. Asking them for it every time the app is relaunched, twice (and then again later when it has timed out) is not user friendly.

There is nothing dangerous or unusual about this standard feature that is found in all browsers.

Ignoring this problem will make new users use "cloud IDEs" like replit, heroku and other such web-based platforms and will make them think running local apps like VScode is painful and inefficient.

Yes I know about SSH keys. If you find it concerning saving the password, then consider that saving a key without a passphrase isn't any safer. But if you really find it preferable, then add an option to create one and add it to the configuration automatically.

**Comment by eleanorjboyd** [comment]
Hello, just to clarify are you asking for the remote-ssh extension to remember the password to the remote machine? Or saving the password to the ssh key?
