### ISSUE TITLE
VSCode ignores the feature's `installsAfter` when the version is omitted

### ISSUE THREAD

**Issue by sarisia** [microsoft/vscode-remote-release#7838]
- VSCode Version:
- Local OS Version:
- Remote OS Version:

```
Version: 1.74.3 (system setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

- Remote Extension/Connection Type: Containers v0.266.1
also tested and reproduced with pre-release v0.269.0

VSCode ignores the feature's `installsAfter` when the version is omitted.
[Devcontainer Feature Spec](https://github.com/devcontainers/spec/blob/7791da141b7996865d88ddd977ef2ca9b8ad932c/docs/specs/devcontainer-features.md?plain=1#L47) requires feature IDs in `installsAfter` to be a version tag omitted string, but doing so results build error in VSCode, because of improper resolution of installation order of features (`installsAfter` is not respected).

- Logs: [vscode-log-stable.txt](https://github.com/microsoft/vscode-remote-release/files/10394876/vscode-log-stable.txt)

Steps to Reproduce:

Assuming the following usecase:

- I'm working on Python project (Python devcontainer) and want to install the tools with nodejs & npm.
- In order to include these tools to the pre-built devcontainer image, I'm installing these tools with "local devcontainer feature".

1. clone the sample repository: https://github.com/kirchen-bell/simple-internal-feature
2. open with VSCode and run `Dev Containers: Rebuild Container Without Cache` command
3. build fails because of `npm` command is missing. See the log file attached above
4. adding the version to the feature id in `installsAfter` and re-run step 3 successfully launches devcontainer (but it violates the spec...).

    `.devcontainer/local-feature/devcontainer-feature.json`:

    ```json
        "installsAfter": [
            "ghcr.io/devcontainers/features/node:1"
        ]
    ```

Related informations:

- `@devcontainers/cli` fails to build the image when the version tag is added to the feature id (step 4)
    - seems this is intended: https://github.com/devcontainers/cli/issues/269
- the spec documentation in [containers.dev](https://containers.dev/implementors/features/) does not say that `installsAfter` requires version tag omitted strings, but [docs in repo](https://github.com/devcontainers/spec/blob/7791da141b7996865d88ddd977ef2ca9b8ad932c/docs/specs/devcontainer-features.md?plain=1#L47) says.
    - this seems an another issue: https://github.com/devcontainers/spec/issues/174

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
Checking on https://github.com/microsoft/vscode-remote-release/issues/7838.

**Comment by joshspicer** [comment]
Confirmed that this no longer repros
