### ISSUE TITLE
The problem in log and detecting reach.

### ISSUE THREAD

**Issue by smart2pet** [microsoft/vscode-remote-release#7847]
## Problem Description:
Actually, this won't affect me at all. But I think we should to make more details in log. Also, There's another problem, It just 'got some output', we should detect the output made by the client. Or maybe that just the problem in the log. Please look at this issue.
## Log details:
`[17:39:40.019] Got some output, clearing connection timeout`.

**Comment by chrmarti** [comment]
Which product and extensions does this refer to?

**Comment by smart2pet** [comment]
That's just in vscode. And it is from Remote - SSH extension.

**Comment by smart2pet** [comment]
That's just in vscode. And it is from Remote - SSH extension.



At 2023-01-13 17:23:22, "Christof Marti" ***@***.***> wrote:

Which product and extensions does this refer to?

**Comment by smart2pet** [comment]
Is somebody here?

**Comment by eleanorjboyd** [comment]
We should persist all logs from remote-ssh to the user but I will confirm.

**Comment by smart2pet** [comment]
Yeah. So is there any solution?

**Comment by eleanorjboyd** [comment]
Hello! I am sorry these logs are confusing, feel free to create a feature request issue with what changes you would like to see. The output line you are commenting on is one we use to understand that the install script ran and returned output so it more signals a step in the resolver process. Any error messages that occur in this process should be printed in the remote-ssh logs. Hope this helps, thanks

**Comment by smart2pet** [comment]
thanks
