### ISSUE TITLE
[Remote-SSH Bug]: GIT signing error: "Permission denied (publickey)"

### ISSUE THREAD

**Issue by ffMathy** [microsoft/vscode-remote-release#7852]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Debugging Steps

- [X] I have followed these debugging steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting
- [X] My SSH command works from a local terminal
- [X] I can connect using the Remote-SSH extension on VS Code when all other VS Code extensions are disabled

### ->

When I try to run `git push` from my terminal window in the devcontainer, I get the following error:

```
git@xxx: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Running `git push` in my host terminal works just fine.

Running `gpg --list-secret-keys --keyid-format=long` in the devcontainer reveals my public key, so that seems to be available in the container just fine.

Here's my devcontainer config:

```json
{
	"name": "Debug",
	"dockerComposeFile": "docker-compose.yml",
	"overrideCommand": true,
	"postStartCommand": "git config --global gpg.program \"$(which gpg)\"",

	// The 'service' property is the name of the service for the container that VS Code should
	// use. Update this value and .devcontainer/docker-compose.yml to the real service name.
	"service": "app",

	// The 'workspaceFolder' property is the path VS Code should open by default when
	// connected. Corresponds to a volume mount in .devcontainer/docker-compose.yml
	"workspaceFolder": "/workspace",

	// Set *default* container specific settings.json values on container create.
	"settings": {},

	// Add the IDs of extensions you want installed when the container is created.
	"extensions": []
}
```

Here's my `docker-compose.yml`:

```yml
version: '3'

services:
  app:
    build: 
      context: ../
      dockerfile: ./Dockerfile
      target: dev-container

    volumes:
      - ..:/workspace:cached
```

And here's my `Dockerfile`:

```dockerfile
FROM python:3.11 AS base
WORKDIR /app

RUN apt-get update
RUN apt-get install -y python-dev libldap2-dev libsasl2-dev libssl-dev libzbar-dev

COPY ./requirements.txt ./
RUN pip install -r requirements.txt


FROM base AS app
WORKDIR /app
COPY . .


FROM base AS dev-container
WORKDIR /app

CMD [ "sleep", "infinity" ]
```

I've looked at #72 and its linked issues but it doesn't seem related.

### Versions

- VS Code Version: 1.74.3
- devcontainers Version: v0.266.1

### Remote-SSH Log

I couldn't find the `Remote-SSH` in the drop-down. Do I need to submit this issue in another repo?

**Comment by ffMathy** [comment]
It should be added that perhaps documenting #72 would help. Because I can't find where the fix for 72 was made (which commit), nor find out how to use the fix in the documentation.

**Comment by chrmarti** [comment]
This might be an issue with the ssh-agent forwarding (and not GPG). Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)
