### ISSUE TITLE
When opening js files in nvim vs code auto open this file

### ISSUE THREAD

**Issue by geril2207** [microsoft/vscode-remote-release#7855]
I try to use wsl with vscode and install it on my desktop(not from video, now dont have access to it wsl with vs code works correctly).
Now I wanted to put wsl with vs code on a laptop(this video) i open wsl, type `code .`, force stopped installing vs code server(ctrl + c), i get this behavior from video below,  after i go to wsl and reinstall vs code server but its not fix this.

https://user-images.githubusercontent.com/62308020/212495955-6ac7b2ec-a2a7-47c0-b9f2-472a329d4427.mp4

**Comment by aeschli** [comment]
Sorry, from the video I can tell what's happening.

What if you first open VS Code and open a WSL window from there?
If you run into a problem, please look for the WSL log (Command: WSL: Show Log) and paste it here.

**Comment by geril2207** [comment]
Hi, it's been a while, since I faced it, and as I remember, reinstalling was the fix, maybe I did something wrong during the installation. If there are no other reports on it, I think we can close this one.
