### ISSUE TITLE
[Remote-SSH Bug]: code cli is unable to open file on remote in the same window

### ISSUE THREAD

**Issue by pWoLiAn** [microsoft/vscode-remote-release#7861]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Debugging Steps

- [X] I have followed these debugging steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting
- [X] My SSH command works from a local terminal
- [X] I can connect using the Remote-SSH extension on VS Code when all other VS Code extensions are disabled

### Versions

- VS Code Version: 
1.74.3
97dec172d3256f8ca4bfb2143f3f76b503ca0534
x64
- Remote OS Version:
1.74.3
97dec172d3256f8ca4bfb2143f3f76b503ca0534
x64

### Expected Behavior

code cli should be able open a file in the current window

### Steps To Reproduce

1. open folder on remote machine using the remote-ssh extension
2. try to open a file on the server using code cli from the terminal, in the same window with -r option
3. the cmd errors out

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
Unable to connect to VS Code server: Error in request.
Error: connect ENOENT /run/user/0/vscode-ipc-9a611ff4-a089-4e3c-9a9d-ad2099a72c03.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/run/user/0/vscode-ipc-9a611ff4-a089-4e3c-9a9d-ad2099a72c03.sock'
}
```

</p>
</details>

**Comment by eleanorjboyd** [comment]
Hello! Could you please provide the entire remote-ssh logs? The whole logs includes some settings and output which are helpful to the debugging process. Thanks!
