### ISSUE TITLE
hanging on Install and Start server if needed

### ISSUE THREAD

**Issue by crsayen** [microsoft/vscode-remote-release#787]
Issue Type: <b>Bug</b>

I dont even make it to the point that it asks for the password. I have connected to this host before on my Mac so I know it works. I have enabled showLoginTerminal and I have allowed tcp forwarding on the remote machine. I can ssh into the machine with WSL no problem

remote-ssh-nightly@2019.6.34020
win32 x64
SSH Resolver called for "ssh-remote+192.168.7.2", attempt 1
SSH Resolver called for host: 192.168.7.2
Setting up SSH remote "192.168.7.2"
Using commit id "6a7020dd4a11e0f33b157b3df4baeec90d85701b" and quality "insider" for server
Testing ssh with ssh -V
Got error from ssh: spawn ssh ENOENT
Testing ssh with C:\Windows\System32\OpenSSH\ssh.exe -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
Install and start server if needed

Extension version: 2019.6.34020
VS Code version: Code - Insiders 1.36.0-insider (6a7020dd4a11e0f33b157b3df4baeec90d85701b, 2019-06-24T06:46:00.488Z)
OS version: Windows_NT x64 10.0.17763
Fetching remote diagnostics for 'ssh-remote+192.168.7.2' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.70GB (0.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'ssh-remote+192.168.7.2' timed out.
</details>

**Comment by roblourens** [comment]
I have seen this too, so I am adding a timeout. Currently 15 seconds.

**Comment by Tyriar** [comment]
@roblourens steps? If you have seen it in the past maybe you can mark verified?
