### ISSUE TITLE
[Remote-SSH Bug]: Does not handle cases of insufficient RAM on remote system well - death spiral

### ISSUE THREAD

**Issue by cinderblock** [microsoft/vscode-remote-release#7875]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Debugging Steps

- [X] I have followed these debugging steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting
- [X] My SSH command works from a local terminal
- [X] I can connect using the Remote-SSH extension on VS Code when all other VS Code extensions are disabled

### Versions

- VS Code Version: v1.74.3
- Remote OS Version: Raspberry Pi OS Lite x64 on Raspberry Pi 4 2GB

### Steps To Reproduce

1. Connect to a device with limited RAM (<= 2GB) and no/slow swap
2. Start working
3. Add Extensions
4. Do more than the remote system can handle. Exhaust RAM.

### Actual Behavior

The whole remote system becomes unresponsive.

VS Code asks if it should retry/reload. No button to say no. Without clicking anything, it retries anyway.

**Unsaved work cannot be saved** until successful reconnect. You can't even copy the contents of the tab because they go blank.

It seems to me what is happening is that the connection *starts* to work, and then it launches the many helper subprograms, which use more ram, and then something crashes, so it tries again, leaving the old processes hanging around to slowly die/get cleaned up. When the system gets overloaded, this can easily take 30 minutes to recover.

### Expected Behavior

- **Not blanking out local editor windows**
- Automatic retry for intermittent issues
- A button to stop the retry / not retrying automatically if it is asking if it should
- Automatic backoff on frequency of retries
- Cleaning up lingering processes from a previous connection before using more resources

**Comment by eleanorjboyd** [comment]
Hello! Does this issue seem to be what you are struggling with? Can you try some of the possible solutions outlined in this issue?

https://github.com/microsoft/vscode-remote-release/issues/7825

**Comment by cinderblock** [comment]
I don't think so. The connection is generally stable. It's when I start loading things up that problems start happening.

When idle, the system sits comfortably at ~134MB of RAM usage, according to `sudo htop`. Once I start VS Code remote SSH, RAM usage goes up to ~700MB. Starting to do stuff, compiling TypeScript, running extensions/code formatters, usage can easily peak to above 2GB.

I was able to switch to a Raspberry Pi with 4GB of RAM which seems to have entirely prevented this from happening for me for now. However, I still think this could be considered a bug because the death spiral that starts that is hard to recover from.

On top of the death spiral, that, after reloading the VS Code window (before it successfully reconnects), the unsaved editor windows are blank preventing me from manually saving unsaved file contents (by copying to some editor on my development computer, for instance). This feels like an oversight since the changes do come back once the SSH remote connects correctly.

**Comment by eleanorjboyd** [comment]
@sandy081 or @bpasero, seems to be struggling with ram following the SSH connection. It seems like both running extensions and opening/saving files are leading to an increase. Any ideas of a fix?

**Comment by cinderblock** [comment]
To be clear, I don't think the ram increase is entirely undue. I get that I need to run some things on the Pi for the full features of the remote editor to work, and those things need ram. And if we're out of ram, that's a hardware problem, and at some point, there isn't anything VS Code can do. I mean, I don't entirely understand why so much is running on the remote lightweight system, but that's a different discussion.

This issue, as far as I see it, is about VS Code's behavior when hitting the ram limit. VS Code's current behavior actively makes things worse in two ways:
1. Uncontrollable frequent automatic retries that use even more ram making the problem worse
2. Preventing access to the unsaved code in open editor windows

The most reliable "fix" I currently have is keeping a second terminal connection open and, when running out of ram, running `killall node` to kill all VS Code remote processes. Even that can take minutes to run but at least it relatively reliably gives a clean slate with reduced memory usages so that VS Code has enough memory available to make a normal connection. This is what lead to one of my suggested options of VS Code's remote explorer trying to cleanup old hanging processes before starting all the new ones it needs.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by cinderblock** [comment]
This is no longer trivial for me to reproduce. Do you expect there to be a difference in the nightly insider version? I will try if you think there is.
