### ISSUE TITLE
Test: Support multiple devcontainer.json files

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#7881]
Refs: https://github.com/microsoft/vscode-remote-release/issues/7548

- [x] macOS @eleanorjboyd
- [x] linux @connor4312
- [x] windows @deepak1556

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%237881%0A%0A&assignees=chrmarti)

---

Supported locations: `.devcontainer.json`, `.devcontainer/devcontainer.json` and `.devcontainer/*/devcontainer.json` (note: only one level deep).

Test actions operating on a single devcontainer.json when there are multiple devcontainer.json in a workspace folder (Docker volumes are not supported yet):
- `Reopen in Container`
- `Add to devcontainer.json` (context menu on extensions in Extensions viewlet)
- `Configure Container Features`
- `Open Folder in Container`
- `Open Workspace in Container` (config files are located relative to the `.code-workspace` file)
- `Open Container Configuration File`

Some actions are also available while connected to a dev container, also test these while connected to a dev container. They should operate on the config of the current dev container.

On Windows also test with a workspace folder in WSL.

**Comment by connor4312** [comment]
Couldn't quite test fully due to https://github.com/microsoft/vscode-remote-release/issues/7908, but I verified that it _tried_ to use the right devcontainer.json in each case

**Comment by brianbucketlist** [comment]
I am having trouble with this, I keep getting a "select a container configuration template..." dialogue when trying any of the commands listed in this thread.

I have the following folder structure.
.devcontainer
|_node
  |_devcontainer.json
|_django
 |_devcontainer.json

**Comment by jacobwoffenden** [comment]
@brianbucketlist I think this feature is in 0.272.0 onwards, I had to install Code Insiders and use the CLI to install the newer version. Current release of Code was incompatible.
