### ISSUE TITLE
Test `remote.forwardOnOpen`

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#7885]
Refs: https://github.com/microsoft/vscode-remote-release/issues/6972

- [x] ssh @sbatten
- [x] dev container @lszomoru

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%237885%0A%0A&assignees=alexr00)

---

1. Connect to your remote (ssh tester, you could also use Codespaces if you'd prefer).
2. Turn off auto port forwarding (`"remote.autoForwardPorts": false`)
3. Run something in the integrated terminal that will cause a process to listen on a port and that prints something like `https://localhost:3000` to the terminal. The try node sample is always good for this: https://github.com/microsoft/vscode-remote-try-node
4. Go to the ports view and confirm that your port hasn't been forwarded.
5. Ctrl+click on the `localhost` link in the terminal.
6. Verify that the port is forwarded.
7. From the Ports view, stop forwarding the port.
8. Set `"remote.forwardOnOpen": false`
9. Ctrl+click on the `localhost` link in the terminal again.
10. Go to the ports view and verify that your port was not forwarded.

**Comment by lszomoru** [comment]
The settings work as advertised 👏🏻
