### ISSUE TITLE
Test: Clone in Volume with private image

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#7886]
Refs: https://github.com/microsoft/vscode-remote-release/issues/7184

- [x] macOS @paulacamargo25
- [x] linux @connor4312
- [x] macOS @jrieken (windows)

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%237886%0A%0A&assignees=chrmarti)

---

- Push a Docker image to a registry (e.g., Docker hub, ACR or GHCR) and keep it private.
- Create a Git repository with devcontainer.json using the private image.
- Make sure the image is not in the local cache: `docker rmi <image name>`.
- Use `Clone Repository in Container Volume` to test it uses your local Docker credentials (you need to be logged in with `docker login`).
- Check this doesn't work when not logged in (`docker logout`).

**Comment by connor4312** [comment]
Instructions for setting up with an ACR https://learn.microsoft.com/en-us/azure/container-registry/container-registry-get-started-docker-cli?tabs=azure-cli

**Comment by connor4312** [comment]
I'm not able to verify due to the following error when running **Clone Repository in Container Volume**:

```
[611 ms] Dev Containers 0.272.0 in VS Code 1.75.0-insider (0a6c277e4faa44a6b6eb82ddca8bfeccf7fecef6).
[610 ms] Start: Resolving Remote
[629 ms] Start: Check Docker is running
[630 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[775 ms] Server API version: 
[781 ms] Start: Run: docker volume ls -q
[966 ms] Start: Run: docker volume create --label vsch.local.repository=https://github.com/connor4312/verification-7886.git --label vsch.local.repository.unique=true verification-7886-17d94f3747ea408a792775cd6bf8e967
[1115 ms] Start: Run: docker build -f /tmp/vsch-connor/bootstrap-image/0.272.0/bootstrap.Dockerfile -t vsc-volume-bootstrap /tmp/vsch-connor/bootstrap-image/0.272.0
unable to prepare context: path "/tmp/vsch-connor/bootstrap-image/0.272.0" not found
[1955 ms] Command failed: docker build -f /tmp/vsch-connor/bootstrap-image/0.272.0/bootstrap.Dockerfile -t vsc-volume-bootstrap /tmp/vsch-connor/bootstrap-image/0.272.0
[1955 ms] Exit code 
```

The repository in question is: https://github.com/connor4312/verification-7886

**Comment by chrmarti** [comment]
Tracking the above in https://github.com/microsoft/vscode-remote-release/issues/7908 which looks like a known limitation with Docker installed as snap.

Working on getting a fix for https://github.com/microsoft/vscode-remote-release/issues/7854 published that is currently blocking testing for @jrieken.

**Comment by chrmarti** [comment]
Fix is available in Dev Containers 0.273.0-pre-release. Thanks.

**Comment by jrieken** [comment]
I successfully tested this - on macos tho

**Comment by roblourens** [comment]
@chrmarti does this need a windows tester? We can try to find one today

**Comment by jrieken** [comment]
That would be nice, I couldn't do windows because of VMs inside VMs inside VMs...

**Comment by paulacamargo25** [comment]
I use ACR, I see that it is getting the image correctly.
<img width="1379" alt="Screenshot 2023-01-25 at 2 18 51 PM" src="https://user-images.githubusercontent.com/17892325/214665360-635f9cc7-3c56-4194-b8e1-e405d6d18416.png">

But then I get an error.
<img width="1372" alt="Screenshot 2023-01-25 at 2 19 01 PM" src="https://user-images.githubusercontent.com/17892325/214665349-d0d7a82b-4174-42cd-9c4d-079ddfcfa559.png">

I'm not sure if it's a bug or if it's normal.

**Comment by chrmarti** [comment]
> @chrmarti does this need a windows tester? We can try to find one today

@roblourens I quickly checked it works on Windows, that should cover platform specific issues. Thanks!
