### ISSUE TITLE
Test: Apply dev container metadata when attaching

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#7887]
Refs: https://github.com/microsoft/vscode-remote-release/issues/7872

- [x] anyOS @kieferrm
- [x] anyOS @dbaeumer

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%237887%0A%0A&assignees=chrmarti)

---

- Manually start a container including metadata, e.g.: `docker run -d mcr.microsoft.com/devcontainers/rust:latest sleep inf`.
- Run the `Dev Containers: Attach to Existing Container` command and pick the new container.
- Check the user in the Integrated Terminal, the machine settings and the remote extensions match those in the metadata, e.g. from: https://github.com/devcontainers/images/blob/main/src/rust/.devcontainer/devcontainer.json (note that features can add their own metadata).

You can also inspect the container's `devcontainer.metadata` label to see the metadata: `docker inspect -f '{{ index .Config.Labels "devcontainer.metadata" }}' <container id>`.

**Comment by kieferrm** [comment]
Question for @chrmarti : When I inspect the containers meta data and format it, I see the customization section twice.  One seems to be local to the rust feature and the other global. Why is that?

```
[
    {
        "id": "ghcr.io/devcontainers/features/common-utils:2"
    },
    {
        "id": "ghcr.io/devcontainers/features/git:1"
    },
    {
        "id": "ghcr.io/devcontainers/features/rust:1",
        "capAdd": [
            "SYS_PTRACE"
        ],
        "securityOpt": [
            "seccomp=unconfined"
        ],
        "customizations": {
            "vscode": {
                "extensions": [
                    "vadimcn.vscode-lldb",
                    "mutantdino.resourcemonitor",
                    "rust-lang.rust-analyzer",
                    "tamasfe.even-better-toml",
                    "serayuzgur.crates"
                ],
                "settings": {
                    "lldb.executable": "/usr/bin/lldb",
                    "files.watcherExclude": {
                        "**/target/**": true
                    },
                    "rust-analyzer.checkOnSave.command": "clippy"
                }
            }
        }
    },
    {
        "customizations": {
            "vscode": {
                "settings": {
                    "lldb.executable": "/usr/bin/lldb",
                    "files.watcherExclude": {
                        "**/target/**": true
                    },
                    "rust-analyzer.checkOnSave.command": "clippy"
                },
                "extensions": [
                    "vadimcn.vscode-lldb",
                    "mutantdino.resourcemonitor",
                    "rust-lang.rust-analyzer",
                    "tamasfe.even-better-toml",
                    "serayuzgur.crates"
                ]
            }
        },
        "remoteUser": "vscode"
    }
]
```

**Comment by chrmarti** [comment]
> Question for @chrmarti : When I inspect the containers meta data and format it, I see the customization section twice. One seems to be local to the rust feature and the other global. Why is that?

One is from the Rust feature and one is from the [devcontainer.json](https://github.com/devcontainers/images/blob/main/src/rust/.devcontainer/devcontainer.json). We could omit those in the devcontainer.json that are equal to those in the feature. Following up in https://github.com/devcontainers/images/issues/372.
