### ISSUE TITLE
Test: include in ssh config, both casing

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode-remote-release#7888]
Refs: https://github.com/microsoft/vscode-remote-release/issues/6673

- [x] anyOS @lszomoru
- [x] anyOS @bhavyaus

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%237888%0A%0A&assignees=eleanorjboyd)

---

1. Add an "include" (make sure to use lowercase include) statement to your ~/.ssh/config and refresh "remote explorer" (example below)
2. Check hosts inside the included config file show up 

```
Include config.d/home

Host github.com
    HostName github.com
    User git
```

**Comment by lszomoru** [comment]
I can't seem to get this to work, and I feel that I am missing something obvious:

Here are the contents of my `~/.ssh/config` file
```
Host *
  IdentityFile ~/.ssh/id_ed25519

Include ~/.ssh/config.d/home

include ~/.ssh/config.d/home2
```

**~/.ssh/config/d/home**
```
Host github.com
    HostName github.com
    User git
```

**~/.ssh/config/d/home**
```
Host github99.com
    HostName github99.com
    User git
```

None of these hosts appear in the "Remote Explorer". Am I missing something obvious? Thanks!

**Comment by eleanorjboyd** [comment]
Hello! Does it work if you have the include as the first line in your config? Currently, we only support the include in the first line of a config file- sorry I didn't specify!
<img width="408" alt="Screenshot 2023-01-24 at 10 16 18 AM" src="https://user-images.githubusercontent.com/26030610/214374897-cedb4051-1f00-4808-a6f2-9079944abac7.png">

**Comment by bhavyaus** [comment]
Tested this with `Includes` on the first line and it works. 

Based on the below usage statement, the `Include` at the end of the file is probably getting grouped under the last `Host` 

>> 
>              Include the specified configuration file(s).  Multiple
>              pathnames may be specified and each pathname may contain
>              glob(7) wildcards and, for user configurations, shell-like
>              ‘~’ references to user home directories.  Wildcards will be
>              expanded and processed in lexical order.  Files without
>              absolute paths are assumed to be in ~/.ssh if included in a
>              user configuration file or /etc/ssh if included from the
>              system configuration file.  Include directive may appear
>              inside a Match or Host block to perform conditional
>              inclusion.nclude
>              Include the specified configuration file(s).  Multiple
>              pathnames may be specified and each pathname may contain
>              glob(7) wildcards and, for user configurations, shell-like
>              ‘~’ references to user home directories.  Wildcards will be
>              expanded and processed in lexical order.  Files without
>              absolute paths are assumed to be in ~/.ssh if included in a
>              user configuration file or /etc/ssh if included from the
>              system configuration file.  **Include directive may appear
>              inside a Match or Host block to perform conditional
>              inclusion.**

**Comment by eleanorjboyd** [comment]
Yes @bhavyaus that is correct. We have a current issue open regarding how include should be considered in terms of the way that the config file is parsed. We haven't come to a final decision but do frequently get comments from people one way or the other about how remote-explorer should handle includes. We are thinking of adding support for includes under `Host *` since that is generally applicable but this has not been implemented yet.

**Comment by lszomoru** [comment]
Rather than the first line, it seems to me that the limitation is that the `include` statements come **before** the host list.

**Comment by eleanorjboyd** [comment]
ah yes, thank you for that clarification on the wording you are correct.
