### ISSUE TITLE
Test: WSL - Support multiple Linux distros

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#789]
Tests https://github.com/microsoft/vscode-remote-release/issues/118

- [x] Windows @alexr00 
- [x] Windows @sbatten

Complexity: 4

- You need the Windows 10 May 2019 Update: https://www.microsoft.com/en-us/software-download/windows10
- Install WSL and install some distros (Note: Alpine is not supported): https://docs.microsoft.com/en-gb/windows/wsl/install-win10
- Install the latest Remote WSL extension (0.38.1 or newer, to be published Tuesday morning)

- open the WSL shell of each distro, make sure they are initialized. Verify that when running `code-insiders .` in the shell, VSCode opens a remote window for the given shell.
  - Test that the remote indicator shows `WSL: Name of the distro`
  - Test that the explorer and the integrated terminal are showing the files in the given distro
- Use the remote indicator (in the status bar).
  - Verify that you see `Remote WSL: New Window` and `Remote WSL: New Window (Select Distro)`
  - Verify that the first one opens a window with the default distro. The default distro can be specified with `wslconfig.exe` in the Windows command prompt
  - Verify that the second one lets you pick a distro and opens a window of the selected distro
- After trying a few distros, check the recently opened menu and check that all entries have properly formatted labels (with `[WSL: Name of the distro]` suffix).

If you still have an older Windows install with WSL:

- verify that `Remote WSL: New Window (Select Distro)` only show up until the WSL-Remote extension is activated. It then is hidden. When run, an information dialog will explain that a new version of WSL is required.

**Comment by alexr00** [comment]
I don't have an old version of Windows to test the last one with so I couldn't test it.
