### ISSUE TITLE
Test: sleep inhibition

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-remote-release#7892]
Refs: https://github.com/microsoft/vscode-remote-release/issues/7127

- [x] macOS @deepak1556 
- [ ] linux @bpasero @rzhao271 
- [x] windows @karrtikr

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%237892%0A%0A&assignees=connor4312)

---

This iteration, we added a CLI and UI option to prevent your computer from going to sleep while the tunnel is running. Note this should not prevent the screen from turning off/screensaver, except on Linux, where there is no other option 😢  

Linux notes: you will need to be running systemd-based distro with a UI, such as Ubuntu or Fedora. If you run Linux in a VM where it can't trigger sleep, it _should_ be sufficient to check that the screensaver does not appear, as we disable all power management functions.

1. Set your computer to fall asleep after a short period of inactivity
1. Update the setting `remote.tunnels.access.preventSleep` to `true` in VS Code
1. Turn on remote tunnel access, if it was not already on, via the account menu. Run **Remote Tunnels: Show Log** and check that it didn't warn about not being able to inhibit sleep, for any reason
1. Do one of the following (suggested):
    - Make tea
    - Take a walk
    - Pet a cat
1. Verify your computer did not fall asleep.

**Comment by karrtikr** [comment]
> Set your computer to fall asleep after a short period of inactivity

I cannot get my computer to automatically fall asleep on my Windows machine, I configured it as:

![image](https://user-images.githubusercontent.com/13199757/214253173-3bf2ae5b-5ded-47b6-ae97-20cc11c6401d.png)

And had a video clip being played on youtube, the screen turns off after a minute, however clip keeps playing. If I manually put my computer to sleep, clip stops playing.

**Comment by connor4312** [comment]
Browsers will (also) prevent the computer from sleeping when playing media. You can see anything blocking sleep via `powercfg -requests` from an administrative command prompt. You should be able to have your computer sleep if you avoid playing media.

**Comment by karrtikr** [comment]
I see, how can I differentiate between my screen turning off or whether my computer went to sleep? I played a clip as an attempt to distinguish between the two.

**Comment by connor4312** [comment]
If you have a physical machine, you should be able to tell when it goes to sleep since fans etc. will stop spinning and the power light generally goes from on to blinking/pulsing, or off entirely.

**Comment by karrtikr** [comment]
Ok so there's no power light on my Surface book 2, but listening very closely I could verify the fan does not go off when remote tunnel access is on. `powercfg -requests` also indicates the tunnel blocking sleep. Wish there was a better way to verify though.

**Comment by rzhao271** [comment]
Closing out the TPI and creating an issue instead for step 3 on Linux.
