### ISSUE TITLE
Open commands from some remote extensions are missing in remote window

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-remote-release#7893]
Testing #7890

Following the steps in above issue, installed Remote Tunnels, Remote SSH, Dev Containers, Remote Repositories and Codespaces extensions.

* Verified that commands show up in local window indicator
* Open tunnel window
* Remote indicator only shows the following commands., ssh, containers commands are missing.

<img width="948" alt="Screenshot 2023-01-24 at 4 35 55 PM" src="https://user-images.githubusercontent.com/964386/214238069-2dc349d7-8634-4947-ae8e-7b31fdd61597.png">

**Comment by DonJayamanne** [comment]
I too see the issue

**Comment by deepak1556** [comment]
I tested the above scenario where tunnel was setup inside WSL.

**Comment by aeschli** [comment]
@deepak1556 The commands show up when in a local window, right?

**Comment by deepak1556** [comment]
Yup they show up in the local window.

**Comment by aeschli** [comment]
Do you have the pre-release version of SSH?

Dev containers only show up when in a WSL or SSH (and local) window, as designed

**Comment by deepak1556** [comment]
Yes I had pre-release version of all the remote extensions, I just tried the flow again and I couldn't repro the issue anymore. Closing for now.
