### ISSUE TITLE
Prompt after turning on remote tunnel access does not display link properly

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode-remote-release#7894]
Testing #7892

<img src="https://user-images.githubusercontent.com/13199757/214242404-56f6384e-b9e9-4c0d-afc3-8f472b93a479.png" width=450/>

**Comment by karrtikr** [comment]
Seems to be working when I disabled and re-enabled it:
![image](https://user-images.githubusercontent.com/13199757/214243515-4dacb2a3-af60-48e3-96d6-594bd7eb0b42.png)

**Comment by connor4312** [comment]
@aeschli it looks like we are not URI-encoding all of the path segments, I'm guessing the `OneDrive - Microsoft` segment of the URL prevents it from being seen as valid.
