### ISSUE TITLE
Rebuild dialog is only shown once per session

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-remote-release#7899]
Testing #7882

- change the devcontainer.json file and save
- You get the rebuild dialog
- press ignore
- change the file again
- no dialog is shown

The fact that ignore ignores it for the whole session should be made more clear. Or even better offer a check-box to ignore if `always`, `session`, `once`

**Comment by chrmarti** [comment]
I'll change it, so the notification will trigger again after pressing 'Ignore'. Leaving it otherwise as-is to avoid making the UI more complex. Thanks!
