### ISSUE TITLE
Test: `Open Folder in WSL` and `Open Folder in Windows`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#790]
Tests https://github.com/microsoft/vscode-remote-release/issues/562

- [x] Windows @roblourens
- [x] Windows @weinand

Complexity: 3

- Have Windows with WSL enabled: https://code.visualstudio.com/docs/remote/wsl#_getting-started
- Install the latest Remote WSL extension (0.38.1 or newer, to be published Tuesday morning)
- open a local window on a folder
- From the remote indicator menu in the status bar, use `Remote WSL: Reopen in WSL`
  - Verify that this opens the folder in a WSL window
  - if you have more than one Distro installed and are on Win10, May 2019 Update, you will also be prompted to select the distro
- Once in the WSL Window, use `Remote WSL: Reopen in Windows` to open the folder again in Windows
- Test what happens when using `Remote WSL: Reopen in Windows` is folders that are not in `/mnt/c/...`. This should work with Win10, May 2019 Update and open on a `//wsl$/distro...` path. On older windows versions there will be an error dialog
- Test what happens when using `Remote WSL: Reopen in WSL` in folders that are not in the C drive (I never tried that...)

**Comment by weinand** [comment]
Using `Remote WSL: Reopen in WSL` in a folder that is not in the C drive, results in this notification:
![2019-06-25_12-09-49](https://user-images.githubusercontent.com/1898161/60090222-6c2c7780-9742-11e9-9311-9aaf9e3f7dfc.png)
