### ISSUE TITLE
Unknown configuration settings for Rust container

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-remote-release#7901]
Testing #7887

Followed the steps in the test plan item. When inspecting the machine settings I noticed that some of the settings are now unknown. may be we need to update the devcontainer.json

<img width="412" alt="image" src="https://user-images.githubusercontent.com/1931590/214284193-497f3b6e-0448-42d3-9b26-c86162548de6.png">

**Comment by kieferrm** [comment]
Same here.

**Comment by chrmarti** [comment]
Copied to https://github.com/devcontainers/features/issues/420, continuing there.
