### ISSUE TITLE
[Remote-SSH Bug]: Incorrect umask values while creating files

### ISSUE THREAD

**Issue by BhavyaVM1** [microsoft/vscode-remote-release#7902]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Debugging Steps

- [X] I have followed these debugging steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting
- [X] My SSH command works from a local terminal
- [X] I can connect using the Remote-SSH extension on VS Code when all other VS Code extensions are disabled

### ->

The umask values are not getting affected even after doing the "uninstall vscode server from the host". For the files created using the touch command from bash shell having  022 permissions and one created using vscode GUI is having 077 permissions.

### Versions

- VS Code Version: 1.74.0 (Universal)
- Remote OS Version: Linux

### Expected Behavior

When we set the umask value 022 in the .bashrc file and  _`Remote SSH : unistall vscode server from the host`_ , the permissions for the files create using GUI and touch command should have
rw-r-r 
permission

### Steps To Reproduce

<img width="535" alt="Screenshot 2023-01-24 at 9 27 55 PM" src="https://user-images.githubusercontent.com/112678660/214343234-04f08509-87c6-42c9-a9bb-6208280bc952.png">

1  set umask value to 022 in .bashrc
2  unistall vscode server from host
3  create file using touch command `touch file_created_from_terminal`
4 create file from GUI `file_created_from_vscode`
5  check `ls la file_*`

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>
<img width="535" alt="Screenshot 2023-01-24 at 9 27 55 PM" src="https://user-images.githubusercontent.com/112678660/214344035-f4046f12-6196-4e7a-af02-29f67b20c535.png">

**Comment by eleanorjboyd** [comment]
Hello! Apologies for the delay. The best next steps is for you to confirm your bash.rc script is running during the connection. If you can identify that part is working then we can look more closely into the ordering of commands. What is likely happening is the bash.rc script could be running either before or after our install script and that could change the outcome. Thanks

**Comment by BhavyaVM1** [comment]
Hai, All the other settings i change in the _bashrc_ is reflecting in an expected way when connecting with the vscode-server again. How do i interrupt in between install script, to closely check the umask behaviour.

**Comment by eleanorjboyd** [comment]
Could you include your bashrc file or a similar example to what you have set so I can try and repro? Thanks

**Comment by BhavyaVM1** [comment]
Similar to the umask issue, the repo cloned using the git extension through VSCode is not having the correct permissions. The process itself running in **bin/sh** shell, which is the default shell in the machine|linux , but through VSCode we have set the default shell as **bin/bash** and set the umask to 022. My Assumption is for some internal process of VSCode similar to clone or create file is still running in the default shell **bin/sh**.

<img width="1044" alt="Screenshot 2023-02-03 at 10 40 44 AM" src="https://user-images.githubusercontent.com/112678660/216517829-ddbac477-ad36-499b-9f32-cbfb95a6ced6.png">

<img width="1567" alt="Screenshot 2023-02-03 at 10 41 06 AM" src="https://user-images.githubusercontent.com/112678660/216517834-78ef4572-7b48-44b9-8425-159f7be12fa1.png">

### Current .bashrc file in the user directory

<img width="1049" alt="Screenshot 2023-02-03 at 10 44 57 AM" src="https://user-images.githubusercontent.com/112678660/216518212-64cbf3b5-ceef-4001-8c58-1e79d086a26f.png">

I tried changing the default shell umask to 022 by creating a .profile in the user directory. But it is not working. Can you provide a solution to this kind of issues. 


<img width="264" alt="Screenshot 2023-02-03 at 10 45 11 AM" src="https://user-images.githubusercontent.com/112678660/216518560-e2f97b14-f316-491e-8e3a-56c4d2c2544e.png">

**Comment by BhavyaVM1** [comment]
This is a common issue that we are facing with many extensions. While running a command inside the extension
const { spawn } = require('node:child_process');
const ls = spawn('ls', ['-lh', '/usr']);

we closely observed that it is no running on the default shell set inside the user settings.json file. It go for the default shell which the machine provides. 

<img width="485" alt="Screenshot 2023-02-03 at 4 29 04 PM" src="https://user-images.githubusercontent.com/112678660/216587004-c3d1bc56-f91b-4806-b8ff-ba802aa662fe.png">

**Comment by eleanorjboyd** [comment]
Hi! To follow up what I think is happening is that you are changing the default shell within vscode but this does not effect what shell gets used for the resolver which handles the vscode remote install. The default shell set in vscode is not an accessible value when we are installing the vscode server on the remote and therefore we use the default from the remote machine. Please change your default for your machine in order to get the desired effect. This can be done using `chsh`. Thanks!

**Comment by BhavyaVM1** [comment]
Hi,
I understand that VSCode server installation is happening on the default shell only. But after installing the server from an extension i tried running a node js process which is also running on the default shell of the machine. We cannot change the default shell in the machine, we have restrictions in that. Different users may be using their own default shell , is there some other way from VSCode to select the shell for its internal process.

> Hello what setting did you change when you say " through VSCode we have set the default shell as bin/bash"? Thanks

From the command pallet -> Select default profile
