### ISSUE TITLE
Reopen Folder in WSL fails with `VS Code Server for WSL closed unexpectedly`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-release#7906]
- Remote Extension/Connection Type: WSL
- Logs:

> ```
> [2023-01-24 17:45:12.933] WSL daemon log file: 
> [2023-01-24 17:45:12.936] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Ubuntu-20.04 -e sh -c "[ -d ~/.vscode-server-insiders/bin/0a6c277e4faa44a6b6eb82ddca8bfeccf7fecef6 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
> [2023-01-24 17:45:13.045] Unable to detect if server is already installed: Error: Command failed: C:\WINDOWS\System32\wsl.exe -d Ubuntu-20.04 -e sh -c "[ -d ~/.vscode-server-insiders/bin/0a6c277e4faa44a6b6eb82ddca8bfeccf7fecef6 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
> [2023-01-24 17:45:13.046] An existing connection was forcibly closed by the remote host.
> [2023-01-24 17:45:13.046] 
> [2023-01-24 17:45:13.046] Launching C:\WINDOWS\System32\wsl.exe -d Ubuntu-20.04 sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 0a6c277e4faa44a6b6eb82ddca8bfeccf7fecef6 insider code-server-insiders .vscode-server-insiders --host=127.0.0.1 --port=0 --connection-token=2832599753-3147556522-4136304272-306543327 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --telemetry-level=all'
> [2023-01-24 17:45:13.137] An existing connection was forcibly closed by the remote host.
> [2023-01-24 17:45:13.137] 
> [2023-01-24 17:45:13.138] VS Code Server for WSL closed unexpectedly.
> [2023-01-24 17:45:13.138] For help with startup problems, go to https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips
> [2023-01-24 17:45:13.149] WSL Daemon exited with code 0
> ```

Steps to Reproduce:

1. Have `microsoft/vscode` repo cloned locally
2. Select `Reopen Folder in WSL`
3. :bug: WSL remote immediately disconnects:

<img width="1620" alt="image" src="https://user-images.githubusercontent.com/30305945/214368990-cac67227-1ffc-44c0-bd6d-ea88a15e6b8e.png">

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Looks like an issue with WSL.
- Does `C:\WINDOWS\System32\wsl.exe -d Ubuntu-20.04 -e sh -c "echo hello"` work (from the windows command prompt)
- Try `wsl --shutdown` to restart WSL
