### ISSUE TITLE
SSH agent forwarding not working on first connect

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#7912]
I'm not sure if my issue is related, but the first time I build and connect to a dev container, I'm not able to clone a repo using SSH from my host machine. I get the same error as others trying to clone a private repo.

If I run `env` I can see

```
SSH_AUTH_SOCK=/tmp/ssh-XXXXXXVqcT3M/agent.636
```

when it connects the first time right after building. If I disconnect from the container and reconnect (and all future reconnects), I get a variable like

```
SSH_AUTH_SOCK=/tmp/vscode-ssh-auth-1d31887b20b2c25bedf0e097a3e0c1ea8f215d88.sock
```

and I can clone the repo and do everything as needed with SSH successfully. This is from an Ubuntu dev container with minimal config.

_Originally posted by @dslatkin in https://github.com/microsoft/vscode-remote-release/issues/4024#issuecomment-1402866412_

**Comment by chrmarti** [comment]
`SSH_AUTH_SOCK=/tmp/ssh-XXXXXXVqcT3M/agent.636` looks like you are running an ssh-agent inside the container. Could you make sure this is not the case?

**Comment by dslatkin** [comment]
Hi, wonderful! You're absolutely right @chrmarti, thank you. I took my dev container definition I was using for a Codespace which set up an ssh-agent, keys, etc. and migrated it to a dev container, but missed the one spot that was actually starting the agent in a `.bashrc` file. I appreciate the help.

**Comment by chrmarti** [comment]
Closing as resolved then. Thanks!
