### ISSUE TITLE
"Search: Find in Files" not working in MacOS Docker container

### ISSUE THREAD

**Issue by kmbgit** [microsoft/vscode-remote-release#7928]
Type: <b>Bug</b>

I'm running Docker 4.16.2 (95914) on a 14" M1 MacBook Pro with Dev Containers v0.266.1, using the "Attach to Running Container..." option to attach to a container I spun up from the command line using "docker run".  The Dockerfile begins `FROM centos:7` - yes, I'm using CentOS-7 inside the container.

The problem I see is that "Search: Find in Files" (Shift-Cmd-F) only shows results in open editors - and, not, I don't have that option set.

Also "Search files by name" (Cmd-P) can't find any filenames even though they're visible in the explorer view.

One thing I've noticed is that the Docker extension reports "Failed to Connect. Is Docker installed?" in its Containers, Images, Networks, Volumes and Contexts views even though Docker is most definitely installed, and if I run "New Window" (Shict-Cmd-N) then Docker in that new window reports the existence of the container I'm attached to.  So perhaps VScode is trying to attach to Docker INSIDE the container I'm attached to?

Bash shell inside the container says this:-
```
bash-4.2$ uname -a
Linux a870d3b0f9fc 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
bash-4.2$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (AltArch)
```
Extension version: 0.266.1
VS Code version: Code 1.74.3 (Universal) (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:07:18.579Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No
Remote OS version: Linux arm64 5.15.49-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 4|
|Memory (System)|32.00GB (4.68GB free)|
|Process Argv|--crash-reporter-id f086e80b-baa6-4f0e-a5e0-547c1ed7aaf1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container sentinel-cpp-sentinel (gallant_ishizaka)|
|OS|Linux arm64 5.15.49-linuxkit|
|CPUs|unknown (10 x 0)|
|Memory (System)|31.31GB (29.60GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
pyind779cf:30647092
89544117:30613380
pythonsymbol12cf:30652349
a9j8j154:30646983
vscup:30628656

```

</details>

**Comment by kmbgit** [comment]
The problem appears to be related to the remote operating system being the AltArch build of CentOS7 running on an M1 MacBook Pro.  I came to this conclusion as follows:

First I installed CentOS-7-aarch64-Minimal-2009.iso under QEMU/UTM on my MacBook (installed using homebrew `brew install emu utm`) along with ARM64 builds of Rocky 9 and Ubunutu 22.04.  I then connected to each system in turn using Remote-SSH.  The Centos 7 VM exhibited the same problem with file content and file name searching as did the docker image.  The Rocky 9 and Ubuntu 22.04 VMs both behaved correctly.

From this I conclude that there's a problem in the vscode-server that gets downloaded to an ARM64 CentOS7 host.

I ought to repeat this for Rocky 9 and Ubuntu 22.04 running in a Docker container, but it's 6pm on a Friday and I'm ready for home so I'll do it later if that's okay :-). Oh, and trying a non-MacBook ARM64 host running CentOS 7 natively would be a sensible idea too.

**Comment by kmbgit** [comment]
The problem is definitely related to the host OS.  Here's a short recipe to reproduce the fault:-
```
docker pull centos:7
docker run -it --name centos7 -d centos:7
docker exec -it --user root centos7 /bin/bash
```
In the shell run `cd ; ls -l` to see what's in the home directory.

Now open Remotes in VSCode, select Containers from the remote type dropdown, select the centos7 container and attach to it.  Now Open Folder and select /root/ - the Explorer view shows all the files in root's home directory.  Now type Cmd-P to search files by name and type a "." - no filenames are offered even though they exist.  Open .bashrc from the Explorer view and do Cmd-P again.  When you type a "." only .bashrc is offered.

Now repeat all the above with centos:8.  The container works correctly and Search files by name shows all files in the opened directory.

**Comment by chrmarti** [comment]
We are tracking this issue as https://github.com/microsoft/vscode-ripgrep/issues/34. Thanks!

**Comment by krishi-saripalli** [comment]
Running on M2 Pro and having exact same issue!
