### ISSUE TITLE
Integrated terminal significantly slows down and lags after long term using of WSL2

### ISSUE THREAD

**Issue by Eplankton** [microsoft/vscode-remote-release#7929]
I feel sorry that I can't replay this bug in my environment ( Ubuntu 22.04 WSL2 ) again, and i don't know why.....

To be simple, after long terms using ( 24 hours for example ), the integrated terminal (bash shell) in WSL remote seems to be very slow, as  well as  
other operations like save files, delete files...etc, however, by  `wsl --shutdown` , everything turns to normal again. 

But on the other hand, the external terminal opened with `Windows Terminal` has nothing wrong at all, I can smoothly type something and get response at once, compare to the abnormal phenomenon in the integrated terminal.

**Comment by meganrogge** [comment]
Closing as it's probably improved over the last 2 years
