### ISSUE TITLE
user groups out of sync

### ISSUE THREAD

**Issue by stevezkw1998** [microsoft/vscode-remote-release#7931]
Type: <b>Bug</b>

root add userA to groupA
from remote ssh, userA run command `id`, doesn't show groupA, but powershell works well
re-connect, re-start machine, delete host and add, all don't resolve,
I try to clear ssh session, but ssh session is not even obvious for user to clear.

**Comment by eleanorjboyd** [comment]
Hello! I apologies but I am a bit confused about what exactly is happening. Could you explain the desired behavior and the actual behavior? What is the userA and groupA? Which aspects do not resolve? And finally where are you trying to clear the ssh session?

**Comment by stevezkw1998** [comment]
> Hello! I apologize but I am a bit confused about what exactly is happening. Could you explain the desired behavior and the actual behavior? What is the userA and groupA? Which aspects do not resolve? And finally, where are you trying to clear the ssh session?

Hi Thank you for your help, sorry for late reply, the situation is:
In remote host machine, userA has been added to groupA
But when I use vscode ssh -> host, in my terminal, userA still not added in groupA
but when I use powershell ssh -> host, it works well

Just wondering the reason that cause this issue

**Comment by eleanorjboyd** [comment]
By groups are these groups of users that have certain settings permissions? How are you adding and removing them from permission groups?

**Comment by stevezkw1998** [comment]
> By groups are these groups of users that have certain settings permissions? How are you adding and removing them from permission groups?

Yes, these groups have certain permissions, 
Admin user add my user to the group on his side, then I test my group by command `id` on windows powershell->ssh, it can show I was added to that group
But when I use vscode SSH remote host, I try 'id' in my terminal, it shows I have not been added to the group

logout->login, restart, delete connection, all don't work

finally I Kill local Connection Server For Host
Then SSH terminal seems work, but vscode still can not open /etc/* sudo permission files, even though my account has sudo permission

**Comment by KomaGR** [comment]
I think this is related to https://github.com/microsoft/vscode-remote-release/issues/5813 which, for me, is not fixed and I also cannot comment there because the bot has locked the conversation.

**Comment by roblourens** [comment]
When you make changes like this, you will have to force-restart the remote VS Code server. You can run the "Kill VS Code Server on Host" to do this
