### ISSUE TITLE
Can't install any extensions in WSL

### ISSUE THREAD

**Issue by wulei20** [microsoft/vscode-remote-release#7932]
Type: <b>Bug</b>

I can use everything except for installing an extension.
My VSC version is 1.74.3 and my WSL version is Ubuntu 22.04.
Month ago I remember I could still install extensions, but now I can't.
When I click the "Install in Ubuntu-22.04" button of any extension, the progress bar of the extension page keep loading and nothing happened. I waited for long time but the extension was still not been installed. I tried to reload and re-download my vscode and remote extensions, and restart Ubuntu, but nothing helped.

Extension version: 0.72.0
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.81GB (21.60GB free)|
|Process Argv|\\\\wsl$\\Ubuntu-22.04\\home\\wulei\\.vscode-server\\data\\logs --crash-reporter-id fbff8b62-5388-42bd-a62f-2ee4b93221a7|
|Screen Reader|no|
|VM|40%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|Memory (System)|24.91GB (24.25GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
89544117:30613380
2i9eh265:30646982

```

</details>

**Comment by wulei20** [comment]
Also, when I install an extension by vsix, I can't find its status change to "Installed in Ubuntu 22.04" in the Extension store, but it actually installed in the .vscode-server/extension directory and can work.

**Comment by wulei20** [comment]
I think it maybe related to the extension path. For example I installed "Todo Tree" by vsix, actually it was installed in .vscode-server/extensions, and it really worked as the sidebar has the element registered, but I can't find it in the extensions installed list, and if I search it in the extensions market, its status is "Reload Required". If I tap that, the page flashed and vscode reload, but the extension remained its status.

**Comment by wulei20** [comment]
By the way, I can't find anything in extensions->…->show running extensions, only huge area of blank, I think maybe it's loading, but I can't find any results.

**Comment by sandy081** [comment]
@wulei20 Can you please let us know if you are still seeing this issue on the latest version of VS Code?

**Comment by wulei20** [comment]
No, thanks. I think there's something wrong or incompatible of vscode extensions on WSL2 with the router in my home.
I only faced this problem when using vscode for wsl in my home, but everything is fine when I went back to school and use the campus network.
