### ISSUE TITLE
Remove vscode-server from remote host (no documentation found)?

### ISSUE THREAD

**Issue by iobFan** [microsoft/vscode-remote-release#7933]
Hi everyone,

I've installed the "Remote - SSH" extension on my VS Code and connected to my remote raspberry pi. 

I'm not using it anymore. I didn't find any documentation about how to uninstall the "vscode-server" from my remote host.

Can someone explain to me how this works or send me a documentation?

**Comment by eleanorjboyd** [comment]
You should see the command `remote-ssh: uninstall vscode server on remote` in the command palette. Let me know if that is not actually what you are looking for, thanks.
