### ISSUE TITLE
containers.attachToRunningContainerFromViewlet: Shell server terminated (code: 255, signal: null) [Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by Huertas97** [microsoft/vscode-remote-release#7934]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Debugging Steps

- [X] I have followed these debugging steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting
- [ ] My SSH command works from a local terminal
- [ ] I can connect using the Remote-SSH extension on VS Code when all other VS Code extensions are disabled

### Versions

- VS Code Version: 1.74.3
- Remote OS Version: Ubuntu 20.04.5 LTS (Focal Fossa)
- Local OS Version:Windows 11
- Remote-SSH Extension Version:  v0.94.0
- Dev Container Extension Version: Tried with v269.0, v266.1
Logs:containers.attachToRunningContainerFromViewlet 错误: Shell server terminated (code: 255, signal: null)
Steps to Reproduce:

When i want to attach VScode to a running Docker container:

Error running command remote-containers.attachToRunningContainerFromViewlet: Shell server terminated (code: 255, signal: null) Load key "C:\\Users\\AlvaroHuertasGarc\303\255a\\.ssh": Operation not supported on socket CreateProcessW failed error:2 ssh_askpass: posix_spawnp: No such file or directory Permission denied, please try again. CreateProcessW failed error:2 ssh_askpass: posix_spawnp: No such file or directory Permission denied, please try again. CreateProcessW failed error:2 ssh_askpass: posix_spawnp: No such file or directory alvaro@g2.etsisi.upm.es: Permission denied (publickey,password). . This is likely caused by the extension that contributes remote-

### Remote-SSH Log

Error running command remote-containers.attachToRunningContainerFromViewlet: Shell server terminated (code: 255, signal: null) Load key "C:\\Users\\AlvaroHuertasGarc\303\255a\\.ssh": Operation not supported on socket CreateProcessW failed error:2 ssh_askpass: posix_spawnp: No such file or directory Permission denied, please try again. CreateProcessW failed error:2 ssh_askpass: posix_spawnp: No such file or directory Permission denied, please try again. CreateProcessW failed error:2 ssh_askpass: posix_spawnp: No such file or directory alvaro@g2.etsisi.upm.es: Permission denied (publickey,password). . This is likely caused by the extension that contributes remote-

**Comment by chrmarti** [comment]
Could you also append the log from `F1` > `Dev Containers: Show Container Log` when you see this?

**Comment by chrmarti** [comment]
Does `ssh g2.etsisi.upm.es` work from the command line? Does it require keyboard input? Do you have any entries in your local `~/.ssh/config` for this host?

**Comment by Huertas97** [comment]
- `ssh g2.etsisi.upm.es` works from the command line. It requires introducing the user's password. 
- Yes I have entries in my local `~/.ssh/config` for this host

```Host g2.etsisi.upm.es
  HostName g2.etsisi.upm.es
  IdentityFile C:\Users\nameuser\.ssh
  User myuser
```

- But I cannot access to `C:\ProgramData\ssh\ssh_config` in my local machine:

<img width="296" alt="image" src="https://user-images.githubusercontent.com/56938752/217497125-e662a67d-aa59-47a2-b09a-5be4ba9f053b.png">

**Comment by Huertas97** [comment]
It still does not work. I have tried to check my ssh user profile and credentials. But even creating a new user does not allow to connect to Docker containers through VSCode.

**Comment by chrmarti** [comment]
@eleanorjboyd The errors appear to be Remote-SSH related.

**Comment by eleanorjboyd** [comment]
added @roblourens

**Comment by roblourens** [comment]
That error just tells us that file doesn't exist or you don't have permission to access it. Not actually related to the Remote-SSH extension
