### ISSUE TITLE
Can't install extension only in dev container

### ISSUE THREAD

**Issue by kenf1** [microsoft/vscode-remote-release#7935]
Certain extensions don't have option to be installed only in Dev Container. Only option is `install locally`.

Example: [extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag)

- VSCode Version: 1.74.3
- Remote OS Version: node.js 19.5 slim docker image
- Remote Extension/Connection Type: Containers
- Dev container version: v0.266.1

**Comment by chrmarti** [comment]
The extension linked to above indicates that it should be able run locally or remotely. Try adding it to your devcontainer.json and rebuild the dev container, that will install it in the dev container:
```
	"customizations": {
		"vscode": {
			"extensions": [
				"formulahendry.auto-close-tag"
			]
		}
	}
```

/fyi @sandy081

**Comment by kenf1** [comment]
Doing it via this method worked. Thanks!
