### ISSUE TITLE
proxy: unknown scheme: http with DOCKER_HOST

### ISSUE THREAD

**Issue by iLem0n** [microsoft/vscode-remote-release#7939]
- VSCode Version: 1.74.3 (Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534)
- Local OS Version: macOS Ventura 13.2
- Remote OS Version: DevContainer Extension (v0.266.1) / Image: mcr.microsoft.com/devcontainers/base:jammy
- Remote Extension/Connection Type: Containers

```
 ~/docker-setup (master)> docker --host ssh://vagrant@127.0.0.1:2222 version
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:41 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          23.0.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       d7573ab
  Built:            Wed Feb  1 17:43:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Logs: 
```
[1178 ms] Dev Containers 0.266.1 in VS Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534).
[1177 ms] Start: Run: git rev-parse --abbrev-ref --symbolic-full-name @{u}
[1198 ms] Stop (21 ms): Run: git rev-parse --abbrev-ref --symbolic-full-name @{u}
[223805 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[223922 ms] Stop (117 ms): Run: docker version --format {{.Server.APIVersion}}
[223923 ms] proxy: unknown scheme: http
```

Steps to Reproduce:

1. Do not have Docker-Desktop installed
2. Setup a docker host. Using [Docker VM Setup with Virtualbox + Vagrant + Ansible](https://github.com/iLem0n/docker-vm-setup)
3. Configure "DOCKER_HOST" in VSCode
![Screenshot 2023-01-31 at 08 15 22](https://user-images.githubusercontent.com/5202672/215691876-d2e80d34-7a02-4d71-b931-0e169d5f9c43.png)

4. create a bare minimum dev container project only containing the following file: 
```
# .devcontainer/devcontainer.json
{
    "name": "Example DevContainer",
    "image": "mcr.microsoft.com/devcontainers/base:jammy",
    "customizations": {    
        "vscode": {         
            "settings": {               
                "docker.environment": {
                    "DOCKER_HOST": "ssh://vagrant@127.0.0.1:2222"
                }
            }
        }
    }   
}
```
5. run `Dev Containers: Open Folder in Container...` (or any other DevContainers command) in VSCode

Expected Behaviour: 
VSCode should build and run the dev container using "external" docker host 

Actual Behaviour: 
VSCode directly stops with the error shown in logs and don't even start to build anything. 

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Does `docker --host ssh://vagrant@127.0.0.1:2222 version` work when you run it from the command line?

**Comment by iLem0n** [comment]
I have set `DOCKER_HOST=ssh://vagrant@127.0.0.1:2222` environment variable set and all docker commands from the command line working just fine and are executed at the VM docker-daemon.

**Comment by chrmarti** [comment]
What do you get when running `docker version`? (Could be an older issue: https://github.com/moby/moby/issues/25740)

**Comment by chrmarti** [comment]
Does `docker version --format {{.Server.APIVersion}}` work? This is just a guess, I see the server has a recent version.

**Comment by iLem0n** [comment]
Yes, works fine:
```bash
docker version --format {{.Server.APIVersion}}
1.42
```

**Comment by chrmarti** [comment]
I have it running with the same builds (same client and server commit ids) as you (only difference is that I'm testing with an ARM Mac).

Instead of using `DOCKER_HOST`, you could use the Remote-SSH extension to first open a folder in the VM and then reopen that folder in a dev container from there. That uses Dev Containers' integration with Remote-SSH. Can you give that a try?
