### ISSUE TITLE
code . is not working from wsl2 ubuntu after root access

### ISSUE THREAD

**Issue by francescorota93** [microsoft/vscode-remote-release#7940]
I cannot access vsc code from wsl2 ubuntu terminal, after that i accessed as root, if i enter "code ."
I was trying to fix following here https://github.com/microsoft/WSL/issues/4276, but still not working if I enter as user, while from root "code ." is working

This is the error I get when trying to access vsc code from my user:
 
code .
xdg-open: unexpected option '-n'

Anyone can help? Thanks in advance

**Comment by bamurtaugh** [comment]
Are you able to connect starting from the WSL extension in VS Code (so install WSL extension, run command `Connect to WSL`)?
