### ISSUE TITLE
Debt: Display forwarding when opening Windows folder in container

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#7941]

**Comment by joyceerhl** [comment]
What are the verification steps for this issue?

**Comment by chrmarti** [comment]
Step to verify:
- Precondition: Check that DISPLAY and WAYLAND_DISPLAY env variables are set in WSL.
- Reopen a Windows folder in a dev container.
- Check that DISPLAY and WAYLAND_DISPLAY are set inside the dev container.
- Extra check: Install gedit (or some other simple GUI app) in the dev container and verify that running it opens a local window.
