### ISSUE TITLE
Dev-Containers error with Remote Host

### ISSUE THREAD

**Issue by DevelopersWork** [microsoft/vscode-remote-release#7949]
- VSCode Version: 1.74.3 (user setup)
- Local OS Version: Windows_NT x64 10.0.22621
- Remote OS Version: Windows_NT x64 10.0.22621
- Remote Extension/Connection Type: Containers/Server

I had connected my host machine via ssh VS-Code but when I try anything like "Reopen in Container" or "Open Folder in Container" throws the following error.  This issue isn't caused if I use VS-Code on the host machine directly.
![image](https://user-images.githubusercontent.com/17892671/216126265-676dd010-6216-4be3-b411-421d55a5649e.png)

Steps to Reproduce:

1. Install docker on a host machine(another computer connected to same network as the client)
2. Connect from client to host via ssh(key-based authentication) from vs-code 
3. Try ">Dev Containers: Open Folder in Container..."

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Could you append the log from when this happens? (`F1` > `Dev Containers: Show Container Log`)

**Comment by DevelopersWork** [comment]
> [4492 ms] Dev Containers 0.266.1 in VS Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534).
[4492 ms] Start: Run: ssh DW-LAPTOP /bin/sh
[4510 ms] Start: Run in host: id -un
[11623 ms] Start: Run: ssh DW-LAPTOP /bin/sh
[11641 ms] Start: Run in host: id -un
[42949 ms] Start: Run: ssh DW-LAPTOP /bin/sh
[42967 ms] Start: Run in host: id -un

I assume this is due to the host system. /bin/sh doesn't exist on Windows Host Machine. Is there anything I can do to fix it, or is it needed to be taken as a feature request?

**Comment by chrmarti** [comment]
We are tracking this as https://github.com/microsoft/vscode-remote-release/issues/6055. Thanks.
