### ISSUE TITLE
Always being asked for password 3 times

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-remote-release#795]
https://github.com/microsoft/vscode-remote-release/issues/750

Followed the steps in the test plan item, initially assumed I have copied&pasted invalid characters but I actually seems that I always need to provide (paste/type) the password three times

**Comment by roblourens** [comment]
With the nightly extension it should be 2 (I should have said that explicitly) but are you using the stable version? There it will still be 3...

**Comment by jrieken** [comment]
No, nightly and 3 times

**Comment by roblourens** [comment]
Oh I see, @kieferrm do we have to set up the extra webview server tunnel even when the enableWebAccess setting is not set?

**Comment by roblourens** [comment]
We are back to two password prompts, I published the ssh nightly extension with this.
