### ISSUE TITLE
Dev Container Error

### ISSUE THREAD

**Issue by ryhhtn** [microsoft/vscode-remote-release#7956]
- VSCode Version: 1.75.0
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Containers

- Logs:

Steps to Reproduce:

1. Install Dev Container (0.275.0)
2. Select Remote Explorer pulldown Containers
3. Click Refresh

`Error running command remote-containers.explorerTargetsRefresh: command 'remote-containers.explorerTargetsRefresh' not found. This is likely caused by the extension that contributes remote-containers.explorerTargetsRefresh.`

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Could you check the Extension Host's Output channel and the Dev Containers log for errors? (`F1` > `Output: Show Output Channels...` and `F1` > `Dev Containers: Show Container Log`)
