### ISSUE TITLE
Dev containers install extension failed(Apple silicon macOS)

### ISSUE THREAD

**Issue by Chindada** [microsoft/vscode-remote-release#7957]
- VSCode Version: v.0.275.0
- Local OS Version: macOS 13.2
- Remote OS Version: linux/amd64 container(python:3.10.8)
- Remote Extension/Connection Type: Containers

- Logs: -

Steps to Reproduce:

1. Start docker container
2. Attach it
3. Go to extension tab, choose extension to install
4. then, sutck like below image, it took long time, but still failed.
![image](https://user-images.githubusercontent.com/46039903/216547429-3a316a24-67b7-4569-b85f-2af8be01eb1f.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Can you please share following logs while you reproduce this

- F1 > Open View... > Log (Window)
- F1 > Open View... > Log (Remote Server)
