### ISSUE TITLE
Bad use of quick pick title

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-remote-release#796]
#750
<img width="842" alt="Screenshot 2019-06-25 at 12 14 44" src="https://user-images.githubusercontent.com/1794099/60090720-5e2b2680-9743-11e9-8234-8d0b82269e91.png">
<img width="840" alt="Screenshot 2019-06-25 at 12 18 00" src="https://user-images.githubusercontent.com/1794099/60090721-5ec3bd00-9743-11e9-871a-8245c0cf84eb.png">

The affordance should be the placeholder text (compare command palette), the title should summarise the current step, e.g. title: "Connecting to foo@bar.server", placeholder: "Type password"

**Comment by kieferrm** [comment]
The command palette doesn't use any titles. We only have/use titles in custom quick picks and we use them consistently through all interactions for Remote-SSH. This came out of initial user feedback that people felt lost without providing them more context/having typed the first letters and having lost the guidance.

**Comment by jrieken** [comment]
> The command palette doesn't use any titles. We only have/use titles in custom quick picks and we use them consistently through all interactions for Remote-SSH.

Yes, I see that remote ssh is doing its own thing. If we think placeholders in quick input/pick are not good we should tackle that for all it usages and not do one-off workaround. IMO till now the recommendation (also for 3rd party developers) is use the title as a step-summary and not as placeholder.

/cc @misolori @stevencl

**Comment by stevencl** [comment]
Some of the early user feedback from studies back in April was about the fact that participants weren't aware that they had multiple options for how to connect to an SSH host. In those studies, the issue wasn't so much that they lost the guidance as soon as they started typing a few characters, it was more that they didn't know they could just type user@host.

Having heard a few people tell us in recent interviews that getting started with SSH was slightly challenging, I am not yet convinced that this change solves the original problem.

**Comment by misolori** [comment]
From a consistency perspective, I agree that if we have problems with our quick pick input fields (like [placeholders being hard to use](https://medium.com/simple-human/10-reasons-why-placeholders-are-problematic-f8079412b960)) we should fix those across the board as a new pattern instead of breaking current patterns.

**Comment by roblourens** [comment]
I hate losing the prompt when typing sensitive info. I want to be totally confident in where this is going when I press enter. This is inconsistent but I think it's not that bad.
