### ISSUE TITLE
Extensions from devcontainer.json not available in dev container

### ISSUE THREAD

**Issue by janhurst** [microsoft/vscode-remote-release#7965]
After updating to 1.75, opening a devcontainer config that has been working for some time, the extensions defined in devcontainer.json are not installed.

Reverting back to 0.266.1 and extensions install as expected.

- VSCode Version: 1.75
- Local OS Version: Windows 11
- Remote OS Version: Debian in dev containers
- Remote Extension/Connection Type: Containers

- Logs:

Steps to Reproduce:

1. Rebuild/reopen dev container
2. Extensions defined in devcontainer.json do not get installed

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
Could you append your log after a rebuild with the current version of the extension? (`F1` > `Dev Containers: Show Container Log`)
