### ISSUE TITLE
env-loginInteractiveShell.json appearing in project

### ISSUE THREAD

**Issue by niccolomineo** [microsoft/vscode-remote-release#7969]
- VSCode Version: 1.75
- Local OS Version: MacOS Ventura 13.2
- Local chip architecture: Apple Silicon
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: what? :D

Steps to Reproduce:

1. Just run a container
2. Establish that an `env-loginInteractiveShell.json`file in a nested directory structure appears:

![Screenshot 2023-02-03 alle 11 53 09](https://user-images.githubusercontent.com/5409469/216586417-d7e5a946-c4a0-4f14-b90e-52aee654a6f2.png)

**Comment by nicknystrom** [comment]
Experiencing the same issue, also on an M1 Ventura mac.

Additionally:
* Cannot open terminal in containers: `native exception cannot chdir()` errors
* Cannot install plugins into the remote container (no errors, just stuck on "installing...")

Vscode seems to be working fine when working on a local folder.

I was forced to revert to vscode 1.74.3 to continue working.

**Comment by alexjose** [comment]
Multiple files are getting created in /tmp directory within the application directory.

Ex: `tmp/devcontainers-4496cb69-ac47-491b-8d12-2215349eaf3b1675659225490/env-loginInteractiveShell.json`

**Comment by chrmarti** [comment]
Tracking as https://github.com/microsoft/vscode-remote-release/issues/7962. Thanks.
