### ISSUE TITLE
WSL: New Window (select distro) tweaks

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#797]
![image](https://user-images.githubusercontent.com/172399/60091068-0d67fd80-9744-11e9-9cd7-2513073e40cc.png)

- The command should have '...' since it shows a picker.
- Suggest to simplify the label to 'New Window using Distro...'

This item only makes sense when there is >1 distro.

**Comment by aeschli** [comment]
fixed by https://github.com/microsoft/vscode-remote-wsl/commit/de75fe1e23aa5a04ed6a60f60ac469292e7f2e6a
