### ISSUE TITLE
Dev Container can not run CMD in building

### ISSUE THREAD

**Issue by morning-start** [microsoft/vscode-remote-release#7971]
My dockerfile like this

```dockerfile
FROM golang

ENV GO111MODULE=on

CMD go install -v github.com/cweill/gotests/gotests@latest && bash
```

**when I use `docker run` , the gotests will be installed, but it doesn't work with Dev Container(reopen in container)**

**Comment by chrmarti** [comment]
Try adding `"overrideCommand": false` to your `devcontainer.json`. Does that make it work?

**Comment by morning-start** [comment]
> Try adding `"overrideCommand": false` to your `devcontainer.json`. Does that make it work?

it works! thanks
