### ISSUE TITLE
[Remote-SSH Bug]: Cannot access git-lfs from built-in git extension

### ISSUE THREAD

**Issue by monfortm** [microsoft/vscode-remote-release#7981]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Expected Behavior

I got a similar issue with remote where a hook complains that it did not find `git-lfs`, when trying to use git commands from the built-in git extension. 

I am working on a remote machine that relies on environment modules for most software, incl. `git-lfs`. 
`git-lfs` is not expected to be available in the `PATH` until the module is loaded (`module load git-lfs`). I tried to load the module as part of my `.bashrc`, or directly export a modified `PATH` allowing to access the needed binaries (in my case loading the module is prefered over `PATH` manipulation, though).

So this worked for the integrated terminal. i.e. the path there contains `git-lfs`. I don't really know how I can check what `PATH` the built-in git extension relies on, but I would not have expected to be different from the one in the integrated terminal.

### Remote-SSH Log

> [info] \nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/post-commit'.\n

This used to open a pop-up, but not anymore. 

### Anything else?

Follow-up of my messages in https://github.com/microsoft/vscode-remote-release/issues/6628

- https://github.com/microsoft/vscode-remote-release/issues/6628#issuecomment-1405234533
- https://github.com/microsoft/vscode-remote-release/issues/6628#issuecomment-1406736878

edit: add title...

**Comment by eleanorjboyd** [comment]
Hello! So to clarify you path is correct once the loading is finalized and the connection is acheived? So in the integrated terminal of your remote if you look at the path it has `git-lfs`? The problem you are running into is that you try and load the module in your `bashrc` and it doesn't work soon enough or at all? Just trying to figure out if it does work by connection finish or if it erroring if you include the import in the `bashrc` at all.
