### ISSUE TITLE
Failed to connect to `alpine` image

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-remote-release#799]
Testing https://github.com/microsoft/vscode-remote-release/issues/783 on Linux

1. Run `docker run -it alpine`
2. In VS Code, using the Docker explorer, context click that container and run `Attach Visual Studio Code`.

![image](https://user-images.githubusercontent.com/22350/60091922-fde9b400-9745-11e9-9343-d6a9f474a415.png)

**Comment by joaomoreno** [comment]
Seems to work for the `node:alpine` image.

**Comment by chrmarti** [comment]
Which Linux and architecture is this? What do you get for `docker version`?

**Comment by joaomoreno** [comment]
```
➜  ~ cat /etc/os-release NAME="Ubuntu"
VERSION="18.10 (Cosmic Cuttlefish)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.10"
VERSION_ID="18.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
➜  ~ docker version
Client:
 Version:           19.03.0-beta3
 API version:       1.40
 Go version:        go1.12.4
 Git commit:        c55e026
 Built:             Thu Apr 25 02:58:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.0-beta3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.4
  Git commit:       c55e026
  Built:            Thu Apr 25 02:57:32 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.5
  GitCommit:        bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        2b18fe1d885ee5083ef9f0838fee39b62d653e30
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by joaomoreno** [comment]
This works fine on Windows actually.

**Comment by chrmarti** [comment]
You are on a beta version of Docker. Is that intended? (If not: Would you mind retrying with the latest stable release?)

**Comment by joaomoreno** [comment]
It's the default on Ubuntu 18.10. :man_shrugging:

**Comment by chrmarti** [comment]
@joaomoreno Can you check your APT sources? Follwing https://docs.docker.com/install/linux/docker-ce/ubuntu/ I got with Docker 18.09.6 on Ubuntu 18.10. There I don't see the segfault.

**Comment by joaomoreno** [comment]
I do have the `universe` source enabled... I wonder if that is related?

**Comment by chrmarti** [comment]
Universe appears to be using 18.06.1. I got 18.09.6 from docker.com's .deb repository.

**Comment by joaomoreno** [comment]
This fails when using the `alpine` image, but succeeds when locking the version to `alpine:3.8`.

**Comment by aeschli** [comment]
I created #1026 for the Alpine 3.10 issue on Linux.
