### ISSUE TITLE
[Remote-SSH Bug]: "Not yet activated"

### ISSUE THREAD

**Issue by gra-mir** [microsoft/vscode-remote-release#7991]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

I installed the Extension Remote-SSH in VS Code. This should make available the Remote-SSH command palette, which it doesn't. While inspecting the "Runtime Status" of the extension I found that it says "Not yet activated".

### Steps To Reproduce

1. VS Code:
Version: 1.75.0 (user setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:23:45.584Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
2. Install Extension "Remote - SSH: Editing Configuration Files" v0.84.0

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by gra-mir** [comment]
Hi @eleanorjboyd, the status should be activated automatically upon installation of the Extension, right?

**Comment by roblourens** [comment]
No, extensions are only activated when you use their features, not when they are installed. Can you give some more information about what you're actually trying to do?

For example, a good starting point is to click the button in the bottom left corner of the window status bar that looks like `> <` and you will see commands from all Remote extensions.
