### ISSUE TITLE
[Remote-SSH Bug]: Error running command remote-containers.attachToRunningContainerFromViewlet: Command in host failed: cat /etc/passwd. This is likely caused by the extension that contributes remote-containers.attachToRunningContainerFromViewlet.

### ISSUE THREAD

**Issue by 519174419** [microsoft/vscode-remote-release#7992]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[22589 ms] Start: Run in host: cat /etc/passwd
[104438 ms] Start: Run: ssh 10.10.112.107 /bin/sh
[104450 ms] Start: Run in host: id -un
[105172 ms] nemo.liu```

</p>
</details>


### Anything else?

_No response_

**Comment by eleanorjboyd** [comment]
Hello! Could you please explain a bit more your issue and include logs? Thanks

**Comment by 519174419** [comment]
its successful when i attach docker container. But I try to attach it in vscode, ref the pic.  I met the mistake.
 ![image](https://user-images.githubusercontent.com/24762951/221087357-00cf7054-bb67-4ead-aa06-f51c38d9adf1.png)
![image](https://user-images.githubusercontent.com/24762951/221087734-8fca00e3-bea3-489c-b4db-c9c3943927d6.png)
