### ISSUE TITLE
WSL2 vsCode infinite loading

### ISSUE THREAD

**Issue by paulcoffee85** [microsoft/vscode-remote-release#7996]
I am running into WSL 2 Opening Remote infinitely even after closing VSCode and ending ubuntu and vsc in task manager. A total reboot is not a good answer for me. What's another option ?       

       Thanks for reporting and for the detailed writeup @gwillen. Since it sounds like restarting VS Code has resolved the issue, I'm going to close this as you mentioned, but if you are able to repro or if more folks start running into this, please let us know, and I'd be happy to reopen/discuss further.

_Originally posted by @bamurtaugh in https://github.com/microsoft/vscode-remote-release/issues/4450#issuecomment-784614369_

**Comment by bamurtaugh** [comment]
Hi, please follow the guidance I mentioned in this issue: https://github.com/microsoft/vscode-remote-release/issues/7990#issuecomment-1420277350. Thanks!
