### ISSUE TITLE
Opening workspace inside devcontainer fails in v0.275.x release

### ISSUE THREAD

**Issue by trxcllnt** [microsoft/vscode-remote-release#7998]
Opening a workspace inside a devcontainer fails in the latest `ms-vscode-remote.remote-containers` `v0.275.x` release. This worked in `v0.266.1`.

When the VSCode remote containers extension fails (as in the below image), `docker ps` reports the container is in the exited state.

It appears the VSCode remote containers extension stops the container when VSCode reloads, then attempts to run [this command](https://github.com/microsoft/vscode-remote-release/issues/7962#issuecomment-1416531769) to initialize the new workspace session without first restarting it.

![Screenshot_2023-02-07_14-47-05](https://user-images.githubusercontent.com/178183/217385774-7b8de8f4-194b-4d5b-bb12-dde37493c560.png)

- VSCode Version: 1.75.0
- Local OS Version: Ubuntu 20.04
- Remote OS Version: Ubuntu22.04
- Remote Extension/Connection Type: Containers

- Logs: https://gist.github.com/trxcllnt/1f24840d67f886c10976bc1201b2eaa3

Steps to Reproduce:

1. Open a devcontainer that contains a VSCode `.code-workspace` file
2. Click "Open Workspace" on the `.code-workspace` file

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by chrmarti** [comment]
This appears to be a timing issue. Does adding `"shutdownAction": "none"` to the devcontainer.json work around it?

**Comment by trxcllnt** [comment]
Adding `"shutdownAction": "none"` does work around this issue, but that's not an ideal fix in the long term.
