### ISSUE TITLE
v0.278.0 fail to attach a container

### ISSUE THREAD

**Issue by taoqf** [microsoft/vscode-remote-release#8002]
- VSCode Version: 1.75.0
- Local OS Version: Fedora 35
- Remote OS Version: 
- Remote Extension/Connection Type: Containers

- Logs: No logs, just show message at statusbar, says 'activateing extension', then, nothing happens at all, and won't attach to the  container.

Steps to Reproduce:

1. start a container
2. attach to running container

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

And, I tried the preview version, that will do. but, even do that,  I can not open a terminal, when I do that , an error shows up `The connection to the terminal's pty host process is unresponsive, the terminals may stop working.` with a button `Restart pty host`, after I clicked that button, a terminal opened. But if I open a new terminal, the message shows again.

**Comment by Oblynx** [comment]
I have the same symptom. The "Remote Server" logs show this hint:
```
2023-02-08 10:56:28.433 [trace] getUnixShellEnvironment#stderr bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```

@taoqf can you also check and paste the logs of the Remote Server from the "Output" panel?

**Comment by Oblynx** [comment]
https://github.com/microsoft/vscode-remote-release/issues/7999 seems related

**Comment by taoqf** [comment]
https://github.com/microsoft/vscode-remote-release/issues/7964#issuecomment-1430122538 waiting for 1.76

**Comment by taoqf** [comment]
1.76 works
