### ISSUE TITLE
Remote Targets for SSH not shown

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/vscode-remote-release#8003]
Type: <b>Bug</b>

It works all fine on insiders, but on release I do not see the "Remotes" option in the remote explorer - I only see "Containers" and "WSL Targets" there.

The remote ssh extension is properly installed though, when I run the "Remote-SSH: Connect to host" command it works as expected.

Extension version: 0.96.0
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|39.34GB (19.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by eleanorjboyd** [comment]
Hello! Can you include some screenshots to demonstrate? Thanks!
