### ISSUE TITLE
Gpg and ssh-auth forwarding not working in devcontainer on mac

### ISSUE THREAD

**Issue by yosefresina** [microsoft/vscode-remote-release#8004]
- VSCode Version: 1.75
- Local OS Version: OSX Ventura 13.2 (22D49)
- Remote OS Version: golang:1.20.0-bullseye
- Remote Extension/Connection Type: Dev container

- Logs:

Steps to Reproduce:

1. Start from scratch
2. open a simple go project folder
3. F1 > Dev Containers: Open in dev container
4. In container: gpg --list-secret-keys --keyid-format=long

This is shown:
gpg: directory '/home/vscode/.gnupg' created
gpg: keybox '/home/vscode/.gnupg/pubring.kbx' created
gpg: /home/vscode/.gnupg/trustdb.gpg: trustdb created

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
Could you rebuild the container and append the resulting log? (`F1` > `Dev Containers: Show Container Log`)
