### ISSUE TITLE
Can we please rename the `Remote` category in the Remote Explorer

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-release#8006]
1. It is weird to me that the Remote Explorer should contain a category called 'Remote', because all views in the Remote Explorer are by definition Remote
2. It's hard to find Tunnels/SSH from the Remote Explorer dropdown if you don't know that they are hidden under 'Remote'

I'd propose to rename this category to Tunnels/SSH instead since I know we had reasons for unifying the Tunnels/SSH management story here.

<img width="593" alt="image" src="https://user-images.githubusercontent.com/30305945/217618429-f9ef0fdb-0aeb-4344-abf2-c2ea653a6caf.png">

**Comment by bamurtaugh** [comment]
Makes sense to me. I know what's in the `Remote` category, but it still throws me off a bit.

**Comment by aeschli** [comment]
+1 for renaming to SSH/Tunnels, +2 for having them separate again, which would simplify the implementation a lot. 
Related: https://github.com/microsoft/vscode/issues/167065

From what I understand, the motivation to merge them in one node was that we don't like the UI with the drop down. I think we should look again into switching to a tree representation instead, at least for all the non-active remotes. There the main use case is opening a new remote.

@alexr00 is/was the owner of the remote explorer

**Comment by eleanorjboyd** [comment]
Yep also agree with both renaming and having them separate. Not sure how much work this will be- @roblourens do you have a sense? If this does move forward we would just have to prioritize it against the other remote repo changes.

**Comment by roblourens** [comment]
I think the commonality that they have is that these are all of my "Remotes" (we removed the Remote name from WSL and Containers at the same time) and there are just two different mechanisms for connecting to them, via ssh or a tunnel. This makes a lot of sense to me, I think the mental model for these is similar and very different conceptually from WSL or Containers. However I don't really have a strong opinion about whether it's one or two entries in the dropdown. I'm just wouldn't look forward to undoing all the refactoring that led to the separate extension https://github.com/microsoft/vscode-remote-explorer.

**Comment by joyceerhl** [comment]
> these are all of my "Remotes" (we removed the Remote name from WSL and Containers at the same time) and there are just two different mechanisms for connecting to them, via ssh or a tunnel

I think this makes conceptual sense and I'm not advocating for undoing the refactoring--I just ask that the `Remote` dropdown item be given a more descriptive name. Something like `Remote Machines`, `Tunnels/SSH` or, space permitting, `Remote Machines (Tunnels/SSH)` would make it easier for me to find tunnels to connect to from the explorer.
