### ISSUE TITLE
[Remote-WSL Bug]:  `code .` prompts to Reopen Folder in WSL

### ISSUE THREAD

**Issue by jcrben** [microsoft/vscode-remote-release#8009]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] ~~I have tried both values of the `remote.SSH.useLocalServer` setting~~ N/A

### Connect Locally

It connects successfully

### ->

N/A

### Expected Behavior

Expected: When I type `code .` in a WSL terminal, I get dropped immediately into a WSL window of that WSL instance.

Actual: I get this message:
```
When working on folders in \\wsl, we recommend to use a WSL window. 
In a WSL window, all commands, extensions and the terminal run in the Linux subsystem. 
To switch to a WSL window, use [Reopen Folder in WSL](command:remote-wsl.reopenFromRecommendation).
```

### Steps To Reproduce

* Boot the computer, a managed corporate Dell laptop running Windows 21H2 19044.2486
* VSCode version is 1.75.0
* In the Windows Terminal (1.16.10261.0), I first open bash for windows (bash 4.4.23(1)-release). 
    * I execute `code .`  in Windows
    * I do this because I noticed that I needed to open VSCode on Windows first for it to recognize my extensions, which are in an unusual location using the VSCODE_EXTENSIONS variable to point there: $USERPROFILE/dev/.vscode/extensions
    * I also tried this with the extensions in the default location and it hit the same bug, but my daily driver looks like this
* open Ubuntu 20.04 via dropdown in the Windows Terminal configured via "source": "Windows.Terminal.Wsl"
* receive the prompt noted above
* noticed that I didn't get a prompt in the cli about "downloading remote server..." - I did get a somewhat similar message in WSL after clicking the prompted button

I messed around with this by deleting the ~/.vscode-server file in my Ubuntu 20.04 instance and deleting the WSL extension, and I hit this message when trying to reinstall WSL:
```
wsl install 2023-02-08 17:48:26.531 [error] SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at Object.factory (vscode-file://vscode-app/c:/Users/bncrsy/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:93520)
```

This message seemed to persist around restarts IIRC. I deleted all caches from %APPDATA% Roaming and got the same message. Eventually uninstalled a random extension (Python I believe), reinstalled it, and tried again and it seemed to address that message.

I feel like I had this working briefly but then it broke.

I feel that https://github.com/microsoft/vscode-remote-release/issues/5568 could help me here as it sounds like it cleanly uninstalls WSL remote server - reluctant to delete ~/.vscode-server given the unexpected end of JSON input error I got earlier.

### Remote-SSH Log
I executed with the suggested flag:
```
ben@~/devex$ (master) VSCODE_WSL_DEBUG_INFO=true code .
+ COMMIT=e2816fe719a4026ffa1ee0189dc89bdfdbafb164
+ APP_NAME=code
+ QUALITY=stable
+ NAME=Code
+ SERVERDATAFOLDER=.vscode-server
+ realpath /mnt/c/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/bin
+ VSCODE_PATH=/mnt/c/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code
+ ELECTRON=/mnt/c/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/Code.exe
+ IN_WSL=false
+ [ -n Ubuntu-20.04 ]
+ IN_WSL=true
+ [ true = true ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID
+ wslpath -m /mnt/c/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ CLI=C:/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --ms-enable-electron-run-as-node --locate-extension ms-vscode-remote.remote-wsl
+ cat /tmp/remote-wsl-loc.txt
+ WSL_EXT_WLOC=
+ [ -n  ]
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --ms-enable-electron-run-as-node .
+ exit 0
```

Thereafter, 
Show WSL log shows nothing initially, but if I "Reopen in WSL", I see this when I open up WSL Logs from the Command Pallete:
```
[2023-02-09 02:33:42.120] Resolving wsl+Ubuntu-20.04, resolveAttempt: 1
[2023-02-09 02:33:42.232] Starting VS Code Server inside WSL (wsl2)
[2023-02-09 02:33:42.232] Extension version: 0.75.1
[2023-02-09 02:33:42.232] Windows build: 19044. Multi distro support: available. WSL path support: enabled
[2023-02-09 02:33:42.232] No shell environment set or found for current distro.
[2023-02-09 02:33:42.443] WSL daemon log file: 
[2023-02-09 02:33:42.445] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Ubuntu-20.04 -e sh -c "[ -d ~/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2023-02-09 02:33:42.799] Probing result: found
[2023-02-09 02:33:42.799] Server install found in WSL
[2023-02-09 02:33:42.801] Launching C:\WINDOWS\System32\wsl.exe -d Ubuntu-20.04 sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" e2816fe719a4026ffa1ee0189dc89bdfdbafb164 stable code-server .vscode-server --host=127.0.0.1 --port=0 --connection-token=3738274153-3007821659-2290250652-107648709 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --telemetry-level=all'
[2023-02-09 02:33:43.128] Setting up server environment: Looking for /home/ben/.vscode-server/server-env-setup. Not found.
[2023-02-09 02:33:43.128] WSL version: 5.10.102.1-microsoft-standard-WSL2 Ubuntu-20.04
[2023-02-09 02:33:43.128] WSL-shell-PID: 28523
[2023-02-09 02:33:43.128] Node executable: /home/ben/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/node
[2023-02-09 02:33:43.128] Starting server: /home/ben/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/bin/code-server --host=127.0.0.1 --port=0 --connection-token=3738274153-3007821659-2290250652-107648709 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --telemetry-level=all
[2023-02-09 02:33:43.128] *
[2023-02-09 02:33:43.128] * Visual Studio Code Server
[2023-02-09 02:33:43.128] *
[2023-02-09 02:33:43.128] * By using the software, you agree to
[2023-02-09 02:33:43.128] * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
[2023-02-09 02:33:43.128] * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
[2023-02-09 02:33:43.128] *
[2023-02-09 02:33:43.128] Server bound to 127.0.0.1:34405 (IPv4)
[2023-02-09 02:33:43.128] Extension host agent listening on 34405
[2023-02-09 02:33:43.128] 
[2023-02-09 02:33:43.141] Started local proxy server on 49270.
[2023-02-09 02:33:43.141] WSL resolver response: 127.0.0.1:49270
[2023-02-09 02:33:43.141] To debug connection issues, open a local browser on http://127.0.0.1:49270/version
[2023-02-09 02:33:43.142] Using 'wslExeProxy' to connect to the VS Code server as configured by setting 'remote.WSL2.connectionMethod'
[2023-02-09 02:33:43.142] 'wslExeProxy' should fix reconnection issues after sleep and network adapter changes.
[2023-02-09 02:33:43.142] Please report issues related with the new setting to https://github.com/microsoft/vscode-remote-release/issues/5894
[2023-02-09 02:33:43.142] To revert back to the old way of connecting, change setting 'remote.WSL2.connectionMethod' to 'wsl2VMAddress'.
```

### Anything else?

Related issues: 
* found one report over at https://superuser.com/questions/1713661/starting-vscode-with-wsl-distro-from-command-line
* searched issues in this repository, did not find any reports; the message [When working on folders in \\wsl, we recommend to use a WSL window](https://github.com/microsoft/vscode-remote-release/issues?q=is%3Aissue+is%3Aopen+%22When+working+on+folders+in+%5C%5Cwsl%2C+we+recommend+to+use+a+WSL+window%22) has no matches

**Comment by bamurtaugh** [comment]
Hi, thanks for reporting!

Out of curiosity, does the following flow work for you?
- Open VS Code
- Connect to WSL from VS Code using the WSL extension
- Open integrated terminal in VS Code
- Type `code .` in integrated terminal, and another WSL-connected VS Code instance should open

> open Ubuntu 20.04 via dropdown in the Windows Terminal configured via "source": "Windows.Terminal.Wsl"

Does this mean you're typing `code .` in an external Windows terminal, like the following, and it's not working for you?

![image](https://user-images.githubusercontent.com/25310137/220754209-9549f140-fadc-4945-87d8-3e1955cf2f9b.png)

![image](https://user-images.githubusercontent.com/25310137/220754280-02d0792b-384c-4e04-9ffd-22f88b5ba5c9.png)

**Comment by aeschli** [comment]
Thanks for the logs!
So yes, `code .` from a WSL terminal should open a WSL window. The logs show that the cli command running on WSL could not locate the WSL extension, which is on the Windows side.
The command that tries to find the wsl extension is:
```
ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --ms-enable-electron-run-as-node --locate-extension ms-vscode-remote.remote-wsl
```
You see it calls a Window command

You mentioned that you are using the `VSCODE_EXTENSIONS` variable. Is that variable set globally on the Windows side?
Maybe it needs to be added to WSLENV.

**Comment by jcrben** [comment]
@bamurtaugh that worked - after connecting (using the Remote Explorer from the sidebar) and opening an integrated terminal, it popped right into WSL

@aeschli I was not setting it globally via the Windows Environment Variables GUI or anything. The VSCODE_EXTENSIONS file is set in a .bashrc - I have a copy of that file in both Windows (where I'm using msys bash) and in WSL and I keep them in sync via git and have conditions checking for WSL / Linux to handle cross-platform compatibility.

The top of the file has `export VSCODE_EXTENSIONS="/c/Users/bncrsy/dev/.vscode/extensions"` and then later inside a WSL condition (`if [[ $(cat /proc/version) == *WSL2* ]]; then`) I was redefining it to `"/mnt/c/Users/bncrsy/dev/.vscode/extensions"`. I commented out the redefinition and it seems to work without it.

I tried adding VSCODE_EXTENSIONS to WSLENV and still not working. I tried it with both `/mnt/...` and without.

Incidentally, I find that VSCode only picks up my extensions if I start it up in Windows first. If I just start it straight from a WSL shell it can't find any extensions.

```
ben@~$ export VSCODE_EXTENSIONS="/mnt/c/Users/bncrsy/dev/.vscode/extensions"
ben@~$ VSCODE_WSL_DEBUG_INFO=true code .
+ COMMIT=441438abd1ac652551dbe4d408dfcec8a499b8bf
+ APP_NAME=code
+ QUALITY=stable
+ NAME=Code
+ SERVERDATAFOLDER=.vscode-server
+ realpath /mnt/c/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/bin
+ VSCODE_PATH=/mnt/c/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code
+ ELECTRON=/mnt/c/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/Code.exe
+ IN_WSL=false
+ [ -n Ubuntu-20.04 ]
+ IN_WSL=true
+ [ true = true ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:VSCODE_EXTENSIONS:WT_SESSION::WT_PROFILE_ID
+ wslpath -m /mnt/c/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ CLI=C:/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --ms-enable-electron-run-as-node --locate-extension ms-vscode-remote.remote-wsl
+ cat /tmp/remote-wsl-loc.txt
+ WSL_EXT_WLOC=
+ [ -n  ]
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/bncrsy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --ms-enable-electron-run-as-node .
+ exit 0
```

**Comment by jcrben** [comment]
Another thing @aeschli @bamurtaugh - I tried this inside of my WSL Ubuntu 20.04 instance:
```
ben@~$ ~/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/bin/remote-cli/code
Command is only available in WSL or inside a Visual Studio Code terminal.
ben@~$
```

I'm not sure how we are supposed to call `code` in WSL - my assumption was that we call the one in `/mnt/...` which is why I load that into my path in my WSL .bashrc

**Comment by aeschli** [comment]
@jcrben Using a vanilla setup will certainly help. 

When running a WSL window, VS Code actually starts on the Windows side, using extensions located on the Windows file system, typically in `C:\Users\USER\.vscode\extensions`. These extensions can contain Window binaries.
The WSL window, once open, will additionally use extensions stored on the Linux file system, typically on `~/.vscode-server/extensions`. These must be separate from the Windows extensions as they can contain Linux binaries.
So you don't want to use a VSCODE_EXTENSION variable on both sides.

I suggest to try to run everything with the default folders.

**Comment by aeschli** [comment]
`~/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/bin/remote-cli/code` is the shell script that we put on PATH when you are in an internal terminal in a WSL window. It can not be used in external/normal terminals.
In external terminals, `which code` should give you the `code` shell script located on the Windows file system, e.g. `/mnt/c/Users/USER/AppData/Local/Programs/Microsoft VS Code/bin/code`. It comes in through the PATH that WSL inherits from Windows. That shell script that knows how to start VS Code on the Windows side and open a WSL window given the current (WSL) working directory.

**Comment by jcrben** [comment]
@aeschli fyi this automatically started working properly today - I didn't change much

The one thing that I changed yesterday is that I had an old folder named `/.vscode-server2` which I deleted yesterday. I don't see why that would have an impact - and I could try to `mv ~/.vscode-server ~/.vscode-server2` to see if that replicates the issue - but not in a hurry to break it right now.

**Comment by jcrben** [comment]
fyi, even tho mine has now started working properly, I set a coworker up on WSL and they are getting the same prompt - and they're using a fairly vanilla setup. I'll update this ticket if I figure out more as to why
