### ISSUE TITLE
Dev Containers (version 0.275.x) corrupts existing X forwarding in docker container

### ISSUE THREAD

**Issue by johan-laneau** [microsoft/vscode-remote-release#8011]
- VSCode Version: January 2023
- Local OS Version: Windows 10 22H2
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Containers

Steps to Reproduce:

1. Create a docker container with a socket mounted to forward X communication from e.g. WSL to the docker container. I do this via docker-compose.yml file with following lines
'''volumes:
      - source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        type: bind
'''
2. Then create devcontainer.json for the docker-compose.yml and launch VS Code January 2023 edition.
3. The X forwarding in the docker container does not work anymore.

The issue started occurring since Dev Containers (version 0.275.x) that was installed together with VS Code January 2023 version. I assume it is caused by the X11 & Wayland Forwarding that was introduced in this version.
I think the extension should detect that the docker container already has X forwarding and then not try to insert its own forwarding.

My current work-around is the locally remove the X forwarding from the docker-compose.yml file. Then, the docker container will use the docker forwarding inserted by the dev container extension. However, this workaround is not good because I can't use the same docker-compose.yml file for other usecases where VS Code is not used and X forwarding is still required.

**Comment by ahayzen** [comment]
Note i've started a feature request to prevent all automatic forwarding of sockets #8031 so that this doesn't silently fail again and allow for opting out of forwarding.

I also think that if forwarding is enabled it should not set the env var if it is already set in a container that is being attached to (or at least warn that it is overwriting).

**Comment by chrmarti** [comment]
Tracking as https://github.com/microsoft/vscode-remote-release/issues/7983.
