### ISSUE TITLE
Do not hardcode the path to gzip

### ISSUE THREAD

**Issue by SuperSandro2000** [microsoft/vscode-remote-release#8015]
gzip on NixOS is not at the hardcoded location ``/usr/bin/gzip``. Instead of relying on hardcoded, paths the code server should just take any gzip from PATH which then works on any Distro, including NixOS.

---

- VSCode Version: 1.75.0
- Local OS Version: Windows 11
- Remote OS Version: NixOS 23.05 (Stoat)
- Remote Extension/Connection Type: WSL

- Logs:
```
$ code
Updating VS Code Server to version e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Removing previous installation...
Installing VS Code Server for x64 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164)
Downloading: 100%
/nix/store/qqa28hmysc23yy081d178jfd9a1yk8aw-bash-5.2-p15/bin/bash: /usr/bin/gzip: No such file or directory
tar: Child returned status 1
tar: Error is not recoverable: exiting now

tar is unable to read /home/sandro/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164-1675960984.tar.gz. Either the file is corrupt or tar has an issue.
There's a known WSL issue with tar on Ubuntu 19.10.
See workaround in https://github.com/microsoft/vscode-remote-release/issues/1856.
Reload the window to initiate a new server download.
```

Steps to Reproduce:

1. Install NixOS-WSL
2. run code

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by aeschli** [comment]
The WSL extension does not hardcode `gzip` but uses `tar -xf`.
So maybe a configuration issue with NixOS ?
https://github.com/NixOS/nixpkgs/issues/153774 seems similar
