### ISSUE TITLE
Streamline extension contributions to the remote indicator

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-release#8016]
Guidelines for extensions contributing entries to the remote indicator:
- Reduce the total number of actions contributed per remote, in order to ensure that as many remotes' actions are visible at a glance as possible
	- When in a local window there should be at most 3 actions per remote
	- When in a remote window, the relevant remote category should remain sorted to the top, and there should be at most 5 actions per remote
- Remote names should be consistent where possible
	- Where it makes sense, remotes should use consistent verbs ('Connect', 'Create' etc)
	- Remote indicator actions should be suffixed with `...` when they will trigger a multistep flow
- Getting Started and Configure actions for each remote shall be surfaced as quickpick buttons instead of being listed as quickpick items to save space in the list, we will introduce API for this
- Getting Started actions should ideally open each remote's walkthrough in-product instead of redirecting to docs
- Remotes which have separate commands like 'Connect to _' and 'Connect to _ in New Window' should consolidate these actions and respect `"window.openFoldersInNewWindow"`, or we can add support for alt modifiers to open in a new window

| Window | Current remote indicator contents | Proposed remote indicator contents |
| -- | -- | -- |
| Local empty window | ![image](https://user-images.githubusercontent.com/30305945/217453175-27612d80-a4f3-4b87-9292-c4cbf54b6b8d.png) | <img width="725" alt="image" src="https://user-images.githubusercontent.com/30305945/217899050-11d62162-d600-436d-8aec-6b191094a9eb.png"> |
| Local folder | ![image](https://user-images.githubusercontent.com/30305945/217452935-69c82c1e-99a6-4606-891e-fa52db7f7461.png) | <img width="719" alt="image" src="https://user-images.githubusercontent.com/30305945/217899420-e2a67b58-12c8-4d33-82ff-e94a1a5db787.png"> |
| Dev container | ![image](https://user-images.githubusercontent.com/30305945/217454800-5af0c6f6-d6e9-4f70-9f87-05dcf1e0c5f1.png) | <img width="721" alt="image" src="https://user-images.githubusercontent.com/30305945/217899510-c0d7aaee-f03f-441a-a017-71628d29d8db.png"> (Additional offscreen items: Install Additional Remote Extensions, Close Remote Workspace) |
| Codespaces | ![image](https://user-images.githubusercontent.com/30305945/217453459-ed2d6db0-765e-4081-9dad-bd97f77d486e.png) | <img width="728" alt="image" src="https://user-images.githubusercontent.com/30305945/217899590-ddd28e31-4cf1-498b-bb2c-2d9163f7886b.png"> |
| Remote Repositories | ![image](https://user-images.githubusercontent.com/30305945/217457302-84e8fb01-0b45-4c18-968e-4020a29a3812.png) | <img width="727" alt="image" src="https://user-images.githubusercontent.com/30305945/217899686-74026296-f6a7-4630-b9cd-86e3f7498d94.png"> (Additional offscreen items: Connect to Host..., Open SSH Configuration File... Connect to Tunnel, Install Additional Remote Extensions, Close Remote Workspace) |
| WSL | ![image](https://user-images.githubusercontent.com/30305945/217454691-98ae5877-35c3-445b-a633-9db282588838.png) | <img width="723" alt="image" src="https://user-images.githubusercontent.com/30305945/217910623-a97b6243-c73d-4bad-bcb2-a94e68273607.png"> (Additional offscreen items: Install Additional Remote Extensions, Close Remote Workspace) |
| Tunnels | <img width="648" alt="image" src="https://user-images.githubusercontent.com/30305945/217619103-aa90ff59-0eec-487a-a21d-2bf54c8c83cf.png"> | <img width="723" alt="image" src="https://user-images.githubusercontent.com/30305945/217899828-6c0deb2f-eac6-46ba-8dc1-11bbbe95144b.png"> (Additional offscreen items: Close Remote Workspace) |
| SSH | ![image](https://user-images.githubusercontent.com/30305945/217628445-64b2bbb8-9e84-46e1-a997-23532e3eb1f3.png) | <img width="727" alt="image" src="https://user-images.githubusercontent.com/30305945/217900004-3a0fb866-6ca1-44ad-b19e-1fe5a5efbe91.png"> |

**Comment by rjra100** [comment]
Suggestion: rather than deciding what 3 actions are deemed worthy of inclusion in the remote indicator, allow it to be configured. Different situations have different workflows: for example, I almost never use any of the three "worthy" actions from Dev Container, but I regularly want Open Folder in Container and Rebuild Container.

**Comment by roblourens** [comment]
Can this be closed @joyceerhl?

**Comment by joyceerhl** [comment]
Yes, thanks
