### ISSUE TITLE
Streamline Dev Containers contributions to the remote indicator

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-release#8018]
Ref https://github.com/microsoft/vscode-remote-release/issues/8016

## Remote indicator cleanup

Local empty window
- [ ] Show only `Create Dev Container...`, `Attach to Running Container...`, `Clone Repository in Container Volume`

Local folder
- [ ] Show only `Create Dev Container...`, `Attach to Running Container...`, `Add Dev Container Configuration Files...`, `Reopen Folder in Container`

Dev container
- [ ] Show only `Create Dev Container...`, `Attach to Running Container...`, `Configure Container Features...`, `Reopen Folder Locally`

Codespaces
- [ ] Show only `Create Dev Container...`, `Attach to Running Container...`, `Clone Repository in Container Volume`

Remote Repositories
- [ ] Show only `Create Dev Container...`, `Attach to Running Container...`, `Continue Working in Dev Container...` (via `contribEditSession` extension point)

WSL without folder
- [ ] Show only `Create Dev Container...`, `Attach to Running Container...`, `Clone Repository in Container Volume`

WSL with folder
- [ ] Show only `Create Dev Container...`, `Attach to Running Container...`, `Add Dev Container Configuration Files...`, `Reopen Folder in Container`

Tunnels
- [ ] Show only `Create Dev Container...`, `Attach to Running Container...`, `Clone Repository in Container Volume`

SSH without folder
- [ ] Show only `Create Dev Container...`, `Attach to Running Container...`, `Clone Repository in Container Volume`

SSH with folder
- [ ] Show only `Create Dev Container...`, `Attach to Running Container...`, `Add Dev Container Configuration Files...`, `Reopen Folder in Container`

## Additional cleanup
These are commands which we propose to remove from the remote indicator for now and surface in the command palette as well as potentially as quickpick buttons on the remote indicator itself.
- Rename `Getting Started...` command to `Get Started`
- Rename settings command to Dev Containers: Settings to be consistent and more concise
- Rename command to Dev Containers: Help to be consistent and more concise
- Rename command to Dev Containers: Report Issue... to be consistent and more concise
- Contextually hide Dev Containers: Show Container Log unless a user is in a dev container; it just points to Terminal otherwise
- Rename command Dev Containers Developer: Show All Logs... to Dev Containers: Show All Logs...

**Comment by joyceerhl** [comment]
@drnielsen You should still be able to access `Rebuild Container Without Cache` from the command palette: 
<img width="558" alt="image" src="https://user-images.githubusercontent.com/30305945/223267745-6a440755-b92a-4bce-9daf-45d8ceb9ae55.png">

**Comment by drnielsen** [comment]
But why isn't this also in the menu by default? It seems like a highly relevant command while within a container.
