### ISSUE TITLE
Streamline SSH contributions to the remote indicator

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-release#8019]
Ref https://github.com/microsoft/vscode-remote-release/issues/8016

## Remote indicator cleanup

All windows

- [ ] ~`Connect to Host...` and `Connect Current Window to Host...` should be consolidated into a single `Connect to Host` action. Whether the window is opened in the current window or a new window should be determined by checking the value of the `"window.openFoldersInNewWindow"` core setting~ (this setting relates to opening folders, and SSH always opens empty windows--we don't have a setting for that)
- [ ] Remove `Getting Started with SSH` and `Open SSH Configuration File` from remote indicator
- [ ] ~Rename remote indicator category from Remote-SSH to SSH~ (we keep the Remote-* distinction to communicate that SSH and Tunnels relate to remote machines)

When in an SSH window
- [ ] Remove `Settings`, `Show Log`, `Report Issue...`, `Help`, `Provide Feedback` from the remote indicator, surface them instead as command palette actions

## Additional cleanup
- [ ] Rename `Getting Started with SSH` to `Get Started with SSH` per guidance from @bhavyaus

**Comment by eleanorjboyd** [comment]
Is this finalized or are any of the changes still up for discussion in https://github.com/microsoft/vscode-internalbacklog/issues/3440? Also what is the desired timeline here?

**Comment by joyceerhl** [comment]
@eleanorjboyd This guidance incorporates input from Martin, Christof and Brigit--if you have any additional feedback/suggestions on this guidance I would love to hear it. The item to simplify the remote indicator is on the February 2023 iteration plan: https://github.com/microsoft/vscode-remote-release/issues/7972. Please let me know if you would like help with changes on the SSH side.

**Comment by eleanorjboyd** [comment]
Hi! Yes, I will need help any with changes on the SSH side if we want to get these in for Feb- my iteration plan is already pretty full for the tasks I have to accomplish. Happy to review PRs etc but otherwise I don't really have the time to commit to making those changes myself unless we want to incorporate them into my plan for next month. Thanks!
