### ISSUE TITLE
Port Forwarding 5432 from Remote Server Not Working Properly

### ISSUE THREAD

**Issue by drew-two** [microsoft/vscode-remote-release#8021]
- VSCode Version: 1.75.0
- Local OS Version: Windows 10 Pro 19044.2486
- Remote OS Version: Ubuntu 20.04.5 LTS
- Remote Extension/Connection Type: SSH

- Logs (WSL):
```
$ pgcli -h localhost -d ny_taxi -U root
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
```
- Logs (Docker container):
```
2023-02-09 23:01:17.360 UTC [106] LOG:  invalid length of startup packet
2023-02-09 23:01:18.495 UTC [107] LOG:  invalid length of startup packet
2023-02-09 23:01:18.920 UTC [108] LOG:  invalid length of startup packet
```
 - This occurs when trying to connect through the local browser (which shouldn't work), but confirms some connection

Steps to Reproduce:

1. Load Postgres:13 container in Docker with port 5432 open
2. Forward the port 5432 within VS Code
3. Attempt to connect to database with pgcli or otherwise

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

I am able to forward other ports fine, and VS Code does not give any error forwarding the port, but I can't seem to access the DB at all. 
- Postgres:13 seems to be running fine as I am able to connect to it with pgcli or pgadmin while on the remote host.
- Forwarding the port manually with an SSH command also works fine

**Comment by roblourens** [comment]
If this is still an issue, can you explain a little more? Did you connect via Remote-SSH, then open a container? Or is it a different scenario? How is wsl involved?
