### ISSUE TITLE
CPU usage always 100% with remote-ssh

### ISSUE THREAD

**Issue by alvin08s** [microsoft/vscode-remote-release#8022]
Type: <b>Bug</b>

I always use remote-ssh to connect my server to develop, bug always found than cpu usage reached up to 100%, this leads to SEARCH runs very slow and always disconnect from server

Extension version: 0.96.0
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.15.0-175-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz (12 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.72GB (5.91GB free)|
|Process Argv|--crash-reporter-id 7049e48d-54f9-4b7d-ba20-8f2c9b1cc462|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.108.9.33-jus|
|OS|Linux x64 4.15.0-175-generic|
|CPUs|Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (64 x 3466)|
|Memory (System)|251.38GB (144.22GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyonecf:30548226
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
pyind779cf:30657577
f6dab269:30613381
pythonsymbol12cf:30657549
vscodeenable:30659961

```

</details>

**Comment by eleanorjboyd** [comment]
Hello! Does this happen with all extensions disabled on remote?
