### ISSUE TITLE
"Git" and/or "Jira and Bitbucket (Official)" extension(s) may not be loading properly

### ISSUE THREAD

**Issue by NWinocur** [microsoft/vscode-remote-release#803]
Issue Type: <b>Bug</b>

Shortly after connecting to Raspberry Pi, shows error in lower right saying: "Cannot activate the 'Jira and Bitbucket (Official)' extension because it depends on the 'Git' extension, which is not loaded. Would you like to reload the window to load the extension?"

Pressing the "Reload Window" button does reload the window, but the same error appears again.

Extension version: 2019.6.34020
VS Code version: Code - Insiders 1.36.0-insider (e80dd4f217db6e230d311a87fdf4276f740f6445, 2019-06-25T05:20:16.601Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux arm 4.19.42-v7+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (2.41GB free)|
|Process Argv|-psn_0_1560957|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 172.16.32.92|
|OS|Linux arm 4.19.42-v7+|
|CPUs|ARMv7 Processor rev 4 (v7l) (4 x 600)|
|Memory (System)|0.90GB (0.13GB free)|
|VM|0%|
</details>

**Comment by joaomoreno** [comment]
Do Git features work? Can you view diffs, commit, etc?

**Comment by NWinocur** [comment]
Looked into the git output; seems at the very least I've forgotten to set up the public/private ssh key pairing between the Raspberry Pi & the bitbucket server they way I've already done between my normal development computer & the bitbucket server:

`Looking for git in: git
Using git 2.11.0 from git
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git config --get commit.template
Open repository: /home/pi/ourproject
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse feature/JenkinsResultsReadability
> git rev-parse --symbolic-full-name feature/JenkinsResultsReadability@{u}
> git rev-list --left-right feature/JenkinsResultsReadability...refs/remotes/origin/feature/JenkinsResultsReadability
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
Missing or invalid credentials.
Skip fetch commands
remote: Invalid username or password
fatal: Authentication failed for 'https://nwinocur-myemployer@bitbucket.org/myemployer/ourproject.git/'
> git show :.vscode/arduino.json
> git ls-tree -l HEAD -- /home/pi/ourproject/.vscode/settings.json
> git show 0baa29100ff13ff1ad614ff448e39cfdee462644
> git show HEAD:.vscode/settings.json
> git show :.vscode/arduino.json
`

I'll try setting that up & seeing how things behave after that.

**Comment by NWinocur** [comment]
Tried setting up the public/private SSH key, installed keychain on the raspberry pi & added 
> `eval `keychain --agents ssh --eval my_id_rsa`
to its .bashrc, changed the repo details to point to an ssh-based address instead of https-based address, and tried doing some git commands.
Looks like the version of git available from the default package manager settings is on the older side and supports fewer features or uses different commands; tried doing a git stash via VSCode gui and it threw an error because the "push" part of "git stash push -u" doesn't seem to be a thing on git 2.11.0.
Meanwhile am still getting permission denied errors not so different from before:
`Using git 2.11.0 from git
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git config --get commit.template
Open repository: /home/pi/ourproject
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse feature/somefeaturename
> git rev-parse --symbolic-full-name feature/somefeaturename@{u}
> git rev-list --left-right feature/somefeaturename...refs/remotes/origin/feature/somefeaturename
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :.vscode/tasks.json
> git check-ignore -v -z --stdin
> git show :.vscode/tasks.json
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`
