### ISSUE TITLE
[Remote-SSH Bug]: use the wsl ssh for ssh to a remote host for the remote server  

### ISSUE THREAD

**Issue by zyzhang1992** [microsoft/vscode-remote-release#8033]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

remote ssh connect to host will successfully connect to the remote host

### Steps To Reproduce

The objective is to use the ssh of the wsl and its associated ,ssh/config in /home/username of wsl for the connection to the remote host to start the code server with remote-ssh. 

settings.json: 

"remote.ssh.PATH": c:\Users\username\ssh.bat

I have also set "remote.SSH.showLoginTerminal": true,

The c:\Users\username\ssh.bat contains the following: 
@echo off
C:\Windows\system32\wsl.exe ssh -vvv %*

I have verified in a cmd terminal that running the following will connect to the remote host successfully and also verified that it is making use of the .ssh/config of the /home/username/.ssh/config of the wsl. 
c:\Users\username\ssh.bat 

For the remote-ssh connection, choose the remote host and then the log on prompt appears in the terminal view. When I enter the passoword and then hit return, nothing will happen. There will be no response to multiple returns or input of any characters at the log in prompt. 

I have attached two log files, ssh.diff and ssh.diff.worked, one (ssh.dff) from the remote-ssh log of the OUTPUT of the terminal view from the failed log in when invoking remote ssh connection from the vscode server. the other one (ssh.diff) from running ssh,bat remotehostname from a Windows cmd terminal.  
[ssh.diff.worked.txt](https://github.com/microsoft/vscode-remote-release/files/10718758/ssh.diff.worked.txt)
[ssh.diff.txt](https://github.com/microsoft/vscode-remote-release/files/10718810/ssh.diff.txt)

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>
[remote-ssh-log.txt](https://github.com/microsoft/vscode-remote-release/files/10718858/remote-ssh-log.txt)

**Comment by zyzhang1992** [comment]
@eleanorjboyd Any chance that somebody can take a look at this anytime soon? I'd be happy to work with the developers to figure this out. This could be an interesting issue that opens some opportunities for making vscode much easier to use on a cluster.

**Comment by eleanorjboyd** [comment]
hi @zyzhang1992, looking into this now just finding the right person. Thanks

**Comment by zyzhang1992** [comment]
Thank you! Very much appreciate it.

Sent via the Samsung Galaxy Note8, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by eleanorjboyd** [comment]
Hello! We do not officially support this setup of using an ssh binary inside WSL. Please reference [this issue](https://github.com/microsoft/vscode-remote-release/issues/937) for the discussion and tips regarding this setup. Thanks
