### ISSUE TITLE
remote extension removed after vscode update 

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode-remote-release#8040]
- VSCode Version: 
 - 版本: 1.75.1
提交: 441438abd1ac652551dbe4d408dfcec8a499b8bf
日期: 2023-02-08T21:35:30.018Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 5.15.0-57-generic
沙盒化: No
- Local OS Version: Ubuntu 22.04
- Remote OS Version: CentOS 7
- Remote Extension/Connection Type: Server
 
Steps to Reproduce:
 
1. install some extensions in remote
2. update vscode
  
I' ve seen this in at least 2 servers of mine. All remote extensions (like Python, Julia, C++ extensions) are removed and I have to reinstall them.

**Comment by firejq** [comment]
I meet the same problem

**Comment by connor4312** [comment]
Can you provide reproduction steps?

**Comment by xgdgsc** [comment]
It' s hard to provide. I did was just normal using and updating vscode. And it suddenly occurs.
