### ISSUE TITLE
Remote tunnel with microsoft  account requires github.com account login

### ISSUE THREAD

**Issue by stdll00** [microsoft/vscode-remote-release#8041]
`code tunnel user login --provider microsoft && code tunnel` need github.com login, it will never used.
With github.com login, it works well.  With vscode Desktop App, I don't know how to login with Microsoft Account.

- VSCode Version: code-cli 1.75.1 (commit 441438abd1ac652551dbe4d408dfcec8a499b8bf) 
- Local OS Version: Apple M1 Pro Macbook  OS: 13.1 browser: GoogleChrome 110.0.5481.77
- Remote OS Version: Tested on docker-desktop on local machine. Also happens on linux server.
- Remote Extension/Connection Type:  Tunnel

- Logs:
```
./code tunnel
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*

Open this link in your browser https://vscode.dev/tunnel/********

[2023-02-14 08:52:00] info [tunnels::connections::relay_tunnel_host] Opened new client on channel 2
```

Steps to Reproduce:

1. Logout from github  
2. `code tunnel user login --provider microsoft ` and login with Microsoft Account
3. `code tunnel`
4. access to https://vscode.dev/tunnel/xxxxx . Redirected github.com. Expected redirect to microsoft.com.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by glxplz** [comment]
Bump, I have the same issue.

**Comment by bamurtaugh** [comment]
@connor4312 I think this would be a feature request, but let me know if otherwise.

**Comment by connor4312** [comment]
We do not officially support Microsoft login yet, which is why the `--provider` option is hidden. Still quite a few things we need to do there.
