### ISSUE TITLE
Command 'Remote-Tunnels: Connect to Tunnel...' resulted in an error (command 'remote-tunnels.connectCurrentWindowToTunnel' not found)

### ISSUE THREAD

**Issue by multimeric** [microsoft/vscode-remote-release#8047]
- VSCode Version:  1.73.0, 8fa188b2b301d36553cbc9ce1b0a146ccb93351f, arm64
- Local OS Version: MacOS Monterey 12.6 (21G115)
- Remote OS Version: n/a
- Remote Extension/Connection Type: Tunnels

- Logs:
   ```
    Command 'Remote-Tunnels: Connect to Tunnel...' resulted in an error (command 'remote-tunnels.connectCurrentWindowToTunnel' not found)
    ```

Steps to Reproduce:

1. Run `Remote-Tunnels: Connect to Tunnel`

    ![image](https://user-images.githubusercontent.com/5019367/218904770-cdfcfbd2-ab71-4f5b-a66a-c743f752e883.png)

2. The below error appears:
    ![image](https://user-images.githubusercontent.com/5019367/218904830-d768d547-1876-4635-84f3-eed99a426d18.png)

Note: I am using `Remote - Tunnels v1.0.0`, but this also happens with the pre-release version.

**Comment by connor4312** [comment]
I cannot reproduce this. Do you see any errors logs when running Toggle Developer Tools?

**Comment by playbahn** [comment]
Had the same issue. On a modded Windows 10, I don't have Powerpoint, using cmd.

**Comment by playbahn** [comment]
> Had the same issue. On a modded Windows 10, I don't have Powerpoint, using cmd.

Also, the `code tunnel` command does not work in cmd, so I think there's some connection?

**Comment by playbahn** [comment]
> > Had the same issue. On a modded Windows 10, I don't have Powerpoint, using cmd.
> 
> Also, the `code tunnel` command does not work in cmd, so I think there's some connection?

Additional info: On my machine that shows no issues, the "source" column shows the extension name "Remote - Tunnels" while on the machine that shows issues, the "source" column shows "Default". Maybe the extension isn't working correctly?
