### ISSUE TITLE
The connection to the terminal's pty host process is unresponsive, the terminals may stop working

### ISSUE THREAD

**Issue by suharnikov** [microsoft/vscode-remote-release#8050]
Type: <b>Bug</b>

After update terminal tab doesn't work in a devcontainer.

Extension version: 0.275.1
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:35:30.018Z)
OS version: Linux x64 6.1.11-zen1-1-zen
Modes:
Sandboxed: No
Remote OS version: Linux x64 6.1.11-zen1-1-zen

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 4700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled_force<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 1|
|Memory (System)|15.56GB (6.71GB free)|
|Process Argv|--unity-launch --ignore-gpu-blocklist --disable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --enable-gpu-rasterization --enable-zero-copy --crash-reporter-id fa5ac6dc-4130-4c55-9d38-5c97b1724932|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: Python 3 & PostgreSQL|
|OS|Linux x64 6.1.11-zen1-1-zen|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 4700)|
|Memory (System)|15.56GB (6.71GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779cf:30662993
f6dab269:30613381
pythonsymbol12cf:30657549
2i9eh265:30646982
vsccsb:30662443

```

</details>

**Comment by hypo-thesis** [comment]
Yea this is happening to me too.

**Comment by JorgeO3** [comment]
Me too.

**Comment by jgillich** [comment]
I don't remember the issue number but this has been reported and fixed in VS Code. The latest insiders release works fine.

**Comment by suharnikov** [comment]
@jgillich thanks. I updated to the insiders version and it works now.
