### ISSUE TITLE
Attached terminal not launching UI

### ISSUE THREAD

**Issue by jacksgrin** [microsoft/vscode-remote-release#8055]
Type: <b>Bug</b>

When trying to run a QT ui application from CLI, the terminal in vscode attached to a container hangs.
Opening a new window not attached to the container, starting a terminal in that window, attaching the new terminal to a running container manually launches the ui application as expected.

Rolling back to version 0.266.1, a could not connect to display error occurs and the command aborts properly.
echo $DISPLAY shows :1 in the terminal that works, and :4 in the one that vscode attached to the docker through dev containers and does not work.

Extension version: 0.275.1
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:35:30.018Z)
OS version: Linux x64 5.15.0-60-generic snap
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.0-60-generic

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30660300
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779cf:30662993
f6dab269:30613381
pythonsymbol12cf:30657549
vsctsb:30662444
vscodeenable:30660116

```

</details>

**Comment by chrmarti** [comment]
The latest version forwards the DISPLAY to the local host's DISPLAY. Are GTK apps like gedit working? Could you attach the log from when this fails? (`F1` > `Dev Containers: Show Container Log`)

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/7983. Thanks.
