### ISSUE TITLE
Clarification on `serverInstallPath` setting for vscode remote

### ISSUE THREAD

**Issue by kzhang2** [microsoft/vscode-remote-release#8065]
The documentation indicating that the `serverInstallPath` setting is "a map of remote host to absolute path" could use some clarification on a few points:
1. I'm not familiar with other vscode settings whose values are expected to be a map, it'd be nice to have an example of how this is supposed to look.
2. I'd like to know exactly how the map lookup works:
   - Can make the setting conditional upon whether the remote host name contains a substring matching a pattern or something like that, or do you need to specify the full remote name?
   - I'd like clarification on what counts as the remote's "name" that is looked up in the map: do I have to specify the remote's the FQDN or if it's based on the alias I have in my ~/.ssh/config that I'm using to SSH to the remote, or if the vscode remote just checks the value of $HOST or $HOSTNAME after reaching the remote? 
 
It's not ideal to need to figure this out by trial and error, when SSH-ing to a shared remote server that the user may have little control over, where failures result in accidentally installing the vscode remote server in unwanted places that need to be manually cleaned up.

>I'd expect $HOSTNAME and others to work as well.

That variable substitution doesn't address the problem I share with LiveFreeAndRoam for two reasons:
- I desire is to use the remote host name not as part of the server install path but as part of some condition, so that I can apply a particular `serverInstallPath` setting only when SSH-ing to a particular remote.
- I'm not sure if variables are substituted based on values on the client side, or if it's based on environment variables found after connecting to the remote.

_Originally posted by @VictorYing in https://github.com/microsoft/vscode-remote-release/issues/472#issuecomment-974661105_

---

In particular, I am interested in the first bullet of point 2: is it possible to make the setting conditional on whether the remote hostname contains a substring or some pattern? My specific use case is that I would like to be able to attach my vscode editor to remote SLURM allocations, which do not necessarily give me the same compute node each time (different hostnames) but I would still like to reference the same `.vscode-server` directory for all of them.

**Comment by eleanorjboyd** [comment]
Hello! Not sure if you were using the settings UI but it might make more sense there. Here is a screenshot of where you would include it. The host name is the item and the absolute path is the value. The host name is whatever is configured in your ssh config file, so in the example below the host name here would be `ejb-remote`

 Host ejb-remote
	 HostName xxxx
	 IdentityFile ~/.ssh/xxx
	 User xxx

I will have to investigate further on the second part of your question regarding conditional statements. Have you checked out "match" statements in ssh config files? This might be what you are looking for and would be the standard way to include conditionals in your ssh configurations.

<img width="882" alt="Screenshot 2023-03-13 at 11 02 17 AM" src="https://user-images.githubusercontent.com/26030610/224789895-e1c0a68c-0fc2-4636-af2f-60b5387597f6.png">

**Comment by eleanorjboyd** [comment]
To follow up the serverInstallPath setting should only contain a path so it is best to look for a solution to your issue in the ssh config or by other means. Thanks!

**Comment by kzhang2** [comment]
I don't think I can solve this directly in the ssh config either. The fundamental issue is that VSCode assumes that each remote host maps to only one `serverInstallPath`, but I would like for it to be possible to map multiple hosts to the same `serverInstallPath`. Even if I use `match`, it seems that each entry in the ssh config maps possibly multiple names to just one machine/ip, rather than mapping multiple machines/ips to one name, which would fix this problem. To overcome this, I have simply written a script that updates my ssh config and vscode user settings json file in tandem.

**Comment by eleanorjboyd** [comment]
Understood- well I am glad you found a script that works!
