### ISSUE TITLE
Test: Setting NODE_OPTIONS in remoteEnv irretrievably breaks devcontainer

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#8071]
Refs: https://github.com/devcontainers/cli/issues/351

- [x] anyOS @DonJayamanne
- [x] anyOS @alexr00

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%238071%0A%0A&assignees=chrmarti)

---

- Create a devcontainer with the devcontainer.json setting `NODE_OPTIONS` in `"remoteEnv"`.
- Verify this breaks the previous stable release 0.275.1 of Dev Containers.
- Verify it does not break the current pre-release version of Dev Containers.

**Comment by DonJayamanne** [comment]
@chrmarti Here is my devcontainer.json file
```jsonc
{
{
	"name": "Alpine1",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "ubuntu",
	"remoteEnv": {
		"NODE_OPTIONS":"--max_old_space_size=4096"
	}

```

This works fine for me.

> Verify this breaks the previous stable release 0.275.1 of Dev Containers.

What am i supposed to see here, i.e. how is this supposed to fail?

**Comment by chrmarti** [comment]
I should have said: Using an invalid value for `NODE_OPTIONS`. So instead of the valid `"--max_old_space_size=4096"`, try, e.g., `"--foobar"`.

**Comment by DonJayamanne** [comment]
Works as expected
