### ISSUE TITLE
Test: Streamline Dev Containers contributions to the remote indicator

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#8075]
Refs: https://github.com/microsoft/vscode-remote-release/issues/8018

- [x] anyOS @paulacamargo25
- [x] WSL @rzhao271 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%238075%0A%0A&assignees=chrmarti)

---

(Requires Dev Containers 0.280.0-pre-release.)

Verify the Dev Containers contributions to the remote indicator as specified in https://github.com/microsoft/vscode-remote-release/issues/8018.

**Comment by paulacamargo25** [comment]
I tested all the scenarios that I could, since I work on Mac I can't check the behavior with WSL
