### ISSUE TITLE
"Download in background is enabled" never showed up on version 0.75.3 of the WSL extension 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-remote-release#8077]
Testing #8045

I followed the steps in the TPI with version 0.75.3 but not only the setting `"remote.WSL.downloadInBackground"` wasn't recognized, the message never showed up. But it worked as describe/expected when I tried it with the 0.76 version.

**Comment by aeschli** [comment]
Oh sorry, I got this wrong in the test item:, Requires WSL extension > 0.76, available to users on VS Code 1.76.
