### ISSUE TITLE
Error in Streamline Dev Containers contributions: codespace

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode-remote-release#8078]
Testing #8075

According to #8018:  Show only `Create Dev Container..., Attach to Running Container..., Clone Repository in Container Volume`

But is showing:

<img width="624" alt="Screenshot 2023-02-21 at 5 46 37 PM" src="https://user-images.githubusercontent.com/17892325/220481003-125ac3dd-3acb-4cd0-a45c-49b62285da46.png">

**Comment by chrmarti** [comment]
@joyceerhl I believe #8018 should refer to "Continue Working in Container Volume" instead of "Clone Repository in Container Volume" for Dev Containers while connected to a Codespace?

**Comment by joyceerhl** [comment]
@chrmarti yes you are absolutely right, this issue can be closed.
