### ISSUE TITLE
Error in Streamline Dev Containers contributions: SSH

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode-remote-release#8079]
Testing #8075

According to #8018:

- **SSH without folder**

Should show only `Create Dev Container..., Attach to Running Container..., Clone Repository in Container Volume`

But is showing:
<img width="616" alt="Screenshot 2023-02-21 at 6 16 49 PM" src="https://user-images.githubusercontent.com/17892325/220481346-cce465ba-4b7f-4bf4-8db7-2a0f8dcf611c.png">

- **SSH with folder** 

Should show only: `Create Dev Container..., Attach to Running Container..., Add Dev Container Configuration Files..., Reopen Folder in Container`

But is showing:
<img width="1445" alt="Screenshot 2023-02-21 at 6 18 04 PM" src="https://user-images.githubusercontent.com/17892325/220481402-9580788c-8ede-4b44-9834-5485340f70bf.png">

**Comment by chrmarti** [comment]
Fixing together with https://github.com/microsoft/vscode-remote-release/issues/8080.
