### ISSUE TITLE
Older recent menu entries are not updated with distro tag

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#808]
Testing #789 

I believe this is because this menu entry was created before multi distro support.

![image](https://user-images.githubusercontent.com/6561887/60119460-5a8fa380-9733-11e9-9b00-c68a9bca0120.png)

**Comment by aeschli** [comment]
It's the way it's currently implemented. We store the label at the time the recent menu entry is created. So on startup, we don't have to activate any extension to get the proper format (also, the extension might not know the name anymore)

**Comment by aeschli** [comment]
No changes planed. Eventually the old entries will be replaced by more recent ones.
