### ISSUE TITLE
In WSL window without open folder, Clone Repository in Container Volume option is missing

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-remote-release#8080]
Testing #8075

Dev Containers extension version v0.280.0

1. Open a WSL window. Optionally, open a WSL folder in that window.
2. Click on the remote indicator.
3. :bug: The only options that show up that are contributed by Dev Containers, no matter whether a folder is open or not, are "Create Dev Container..." and "Attach to Running Container...". By https://github.com/microsoft/vscode-remote-release/issues/8018#issue-1578430096, I expected there to be more options.

**Comment by chrmarti** [comment]
Available with Dev Containers 0.281.0-pre-release.
