### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by mpotane** [microsoft/vscode-remote-release#8082]
Issues on newer releases of debian and ubuntu.

**Comment by bamurtaugh** [comment]
Hi! In order for us to help diagnose your issue, please include the information in the issue reporter template (i.e. which extension you're using, version of VS Code and the extension, steps to reproduce). Thanks!

**Comment by mpotane** [comment]
---
name: Bug report
about: Create a report to help us improve
---

- VSCode Version: [Version 1.75](https://code.visualstudio.com/updates)
- Local OS Version: Windows 22H2
- Remote OS Version: Ubuntu Lunar Lobster and Debian Testing
- Remote Extension/Connection Type: WSL v0.75.3 _preview_

**Comment by bamurtaugh** [comment]
Hi, thanks for the info so far! Whenever you get a chance, if you can let us know steps you took where you found this issue, steps we can take to reproduce it, and what exactly the issue is (i.e. a screenshot, exact copy of the logs), that'd be great.

**Comment by mpotane** [comment]
> Hi, thanks for the info so far! Whenever you get a chance, if you can let us know steps you took where you found this issue, steps we can take to reproduce it, and what exactly the issue is (i.e. a screenshot, exact copy of the logs), that'd be great.

🤔It seems to be working fine now that I tested it again. 🚫Closing the issue, sorry for the inconvenience. 🙏

**Comment by Dennis-Zhang-SH** [comment]
> > Hi, thanks for the info so far! Whenever you get a chance, if you can let us know steps you took where you found this issue, steps we can take to reproduce it, and what exactly the issue is (i.e. a screenshot, exact copy of the logs), that'd be great.
> 
> 🤔It seems to be working fine now that I tested it again. 🚫Closing the issue, sorry for the inconvenience. 🙏

How did you fix this?
