### ISSUE TITLE
vscode can't access to WSL on extension version 0.75.3

### ISSUE THREAD

**Issue by gusxo** [microsoft/vscode-remote-release#8084]
- VSCode Version: 1.75.1
- Local OS Version: Windows 10 Pro, 21H2, 64bit, OS Build number = 19044.2604
- Remote OS Version: WSL2, Ubuntu-22.04
- Remote Extension/Connection Type: Containers/WSL/Server

- Logs:

Steps to Reproduce:

1. vscode extension installed by 'Remote Developement' package (Remote - SSH, Remote - Tunnels, Remote Explorer, WSL)
2. extension versions : 
```
Remote - SSH = v0.96.0
Remote - Tunnels = v1.0.0
Remote Explorer = v0.2.0
WSL = v0.75.3
```
3. don't response or get error msg in all features about WSL extension
4. using WSL : New WSL Windows
![image](https://user-images.githubusercontent.com/36655104/220543162-f1b8b938-4d82-4064-9354-cea929535f94.png)
5. using WSL : New WSL Window using Distro
![image](https://user-images.githubusercontent.com/36655104/220543317-6ad859ab-0f43-4467-abb0-e450ddc5c8ed.png)
6. using WSL : Show Logs
![image](https://user-images.githubusercontent.com/36655104/220543366-e30da1e1-6094-4081-8f42-e2b725eda50d.png)

7. type ```code``` in WSL shells
8. open new vscode windows, but can't access terminal or directories, and remote status bar say disconnected.(below image)
![image](https://user-images.githubusercontent.com/36655104/220543753-56429606-0173-4795-ae1d-80f2f7666e7d.png)

9. type ```wsl -l -v``` in windows cmd
![image](https://user-images.githubusercontent.com/36655104/220544375-83bfaec0-37bc-469f-b48b-5f7140dacab8.png)

10. remove and reinstall Ubuntu-22.04, but not solved.
11. remove and reinstall VSCode, but not solved.
12. remove and reinstall VSCode's extension, but not solved.
13. when WSL extension's version downgrade(0.75.3 to 0.75.2), error solved.(can access to WSL in vscode)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: all extensions(without remote extensions) disabled, occured.

**Comment by aeschli** [comment]
I tried the same combination (VS Code 1.75.1, WSL 0.75.3) and it works.

The only difference was the fix of the telemetry key that is in 0.75.3.

Do you see anything interesting in the dev tools console?
