### ISSUE TITLE
SSH title prompt host name malformed

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-remote-release#809]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode-remote-release/issues/750

Using Remote - SSH Nightly version 2019.6.35460

Added
```
Host kiwi
    HostName 52.247.215.15
    User roblou
```
to my ssh config file and then ran "Connect to Host..." on that. The title prompt mangles the host name:
![Screen Shot 2019-06-25 at 10 40 33 AM](https://user-images.githubusercontent.com/3672607/60120658-384b5500-9736-11e9-91a2-9baefa0dff5c.png)

VS Code version: Code - Insiders 1.36.0-insider (e80dd4f217db6e230d311a87fdf4276f740f6445, 2019-06-25T05:19:01.461Z)
OS version: Windows_NT x64 10.0.18362

**Comment by roblourens** [comment]
I think these are all fixed now
