### ISSUE TITLE
Unable to create dev container with a message of 'This is likely caused by the extension that contributes remote-containers.newContainer.'

### ISSUE THREAD

**Issue by jakemraz** [microsoft/vscode-remote-release#8091]
- VSCode Version: 1.75.1
- Local OS Version: Mac Ventura 13.1
- Remote OS Version: v0.275.1
- Remote Extension/Connection Type: Containers/WSL/Server

- Logs:
Error running command remote-containers.newContainer: Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/t1100433/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js templates apply --workspace-folder /var/folders/hk/cz1jx6257zdg8p860csy7ph029lw67/T/tmp-output-dir-1677115589097 --template-id ghcr.io/devcontainers/templates/alpine:latest --template-args {"imageVariant":"3.16"} --features [{"id":"ghcr.io/devcontainers/features/anaconda:1","options":{"version":"latest"}}] --tmp-dir /var/folders/hk/cz1jx6257zdg8p860csy7ph029lw67/T/tmp-dir-1677115589097. This is likely caused by the extension that contributes remote-containers.newContainer.

Steps to Reproduce:

1. Create any dev containers
2. Error occured

When I tried to create the dev container, it failed with alert box (above log)
I tried to do with every dev container VSCode supports and every time I failed.
Please check this

Does this issue occur when you try this locally?: Yes

**Comment by chrmarti** [comment]
Could you append the container log from when this fails? (`F1` > `Dev Containers: Show Container Log`)

**Comment by jakemraz** [comment]
interesting... It wasn't working while I'm in the office, but it's working now at my home.
I should be going to investigate it..
