### ISSUE TITLE
[Remote-SSH Bug]: Doesn't connect to the remote machine with the "Connect" button when the new host is added

### ISSUE THREAD

**Issue by kishankarun** [microsoft/vscode-remote-release#8092]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

As soon as a new remote machine is added to VS Code a popup like below appears

![image](https://user-images.githubusercontent.com/323202/220827880-4ba3332b-c2f1-41ce-95d0-deff7553a739.png)

But clicking on the "Connect" button, nothing happens.

### Expected Behavior

New connection should be open to the newly added server

### Steps To Reproduce

1. Create a new connection
2. A popup appears saying "Host added!" with 2 buttons - "Open Config" and "Connect"
![image](https://user-images.githubusercontent.com/323202/220828655-652310d6-54c5-4728-9c82-691bb8d8fd0d.png)

3. When I click on the "Open Config" the config file opens, but when I click on the "Connect" button, nothing happens

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
No logs available
```

</p>
</details>

![image](https://user-images.githubusercontent.com/323202/220829035-88ea0454-0557-4239-bc17-8296d7320480.png)

**Comment by eleanorjboyd** [comment]
I am able to repro this issue- I will investigate if it is a regression and fix it regardless. Thank you for pointing this out!

**Comment by kishankarun** [comment]
> I am able to repro this issue- I will investigate if it is a regression and fix it regardless. Thank you for pointing this out!

My pleasure @eleanorjboyd , to be a part of improving the very useful VS Code 😊 👍
