### ISSUE TITLE
[Remote-SSH Bug]: "Remove from Recent" in the Remote explorer removes only 1st item

### ISSUE THREAD

**Issue by kishankarun** [microsoft/vscode-remote-release#8093]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

When clicking the "Remove from Recent" button, in the Remote Explorer, it removes the item the first time

![image](https://user-images.githubusercontent.com/323202/220829428-96809d67-b52f-4392-b064-45798a5902f8.png)

Whenever I try it next time, the item selected for removal is note removed.

Even after clicking the refresh list button, it doesn't reflect it on the list.

The updated list is only shown after reloading the instance

### Expected Behavior

The selected item should be removed every time an item is selected and Remove button is clicked

### Steps To Reproduce

When clicking the "Remove from Recent" button, in the Remote Explorer, it removes the item the first time

![image](https://user-images.githubusercontent.com/323202/220829428-96809d67-b52f-4392-b064-45798a5902f8.png)

Whenever I try it next time, the item selected for removal is note removed.

Even after clicking the refresh list button, it doesn't reflect it on the list.

The updated list is only shown after reloading the instance

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
No logs applicable/seen
```

</p>
</details>

### Anything else?

The refresh list button tries to connect to GitHub Tunnels also, which is also annoying

**Comment by kishankarun** [comment]
Hi @eleanorjboyd ,

Could you please let me know how can I contribute in fixing the issue in the extension?

**Comment by eleanorjboyd** [comment]
Hello! Once we get the code merged I will reach out to ask for your help to verify the fix. Otherwise, the remote-ssh extension, where the issue lies, is private. Your issue helped us uncover some more bugs so that is why it is taking a bit. Thanks

**Comment by kishankarun** [comment]
Glad to know that it helped uncover (and fix) more bugs.
I shall be glad to help verify the fix.

Is there any chance the extension would be made public for contribution?

**Comment by eleanorjboyd** [comment]
Thanks again! Currently, no plan to make this extension public as all of our remote extensions are closed source. Thanks

**Comment by kishankarun** [comment]
Thanks for the update. 😃 👍

**Comment by kishankarun** [comment]
Hi @eleanorjboyd ,

Any updates if the fix has been published?

**Comment by eleanorjboyd** [comment]
should be out in the newest version of insiders and will be out on stable next week when VS Code has their monthly release!

**Comment by eleanorjboyd** [comment]
verification steps:
1. connect to a remote host in a new window
2. now in that remote host open two seperate folders - example your desktop and your documents on your remote host
3. go to the old window you started in
4. go to the remote-explorer tab, now click the refresh button here (or reload window)
5. you should see the remote host you connected two with the two folders you opened on it listed under
6. now right click to delete the folder
7. check to make sure you can delete BOTH folders back to back (without the refresh button) and that both will be removed.

**Comment by kishankarun** [comment]
Hi @eleanorjboyd , I haven't got the insider's version, if possible please let me know how to try it out 😃 

Else I shall wait for the next update and will let you know 👍

**Comment by kishankarun** [comment]
I got the latest version and I have verified it to be working fine. The items are getting removed without refreshing/reloading.

Thanks for your support 😃 👍
