### ISSUE TITLE
Error on `az acr login` when no credential helper available

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#8096]
The latest prerelease version doesn't work for me either. In my setup, I'm using devcontainers over SSH. `az acr login` now gives me
```
Error saving credentials: error storing credentials - err: exit status 1, out: `Docker credential helper 'docker-credential-osxkeychain' not found: write EPIPE.`
```
It looks like it is looking for the credential helper on my local mac, not the Linux host I'm SSHing into, where the devcontainer is actually running, which has no credential helper.

_Originally posted by @johnstairs in https://github.com/microsoft/vscode-remote-release/issues/7982#issuecomment-1441816443_

**Comment by johnstairs** [comment]
In the devcontainer:
```json
{
        "credsStore": "dev-containers-bdd50788-db59-4d42-8192-8e3166281308"
}
```

On the SSH host (Linux):
``` json
{
        "auths": {
                "ijk.azurecr.io": {
                        "auth": "MDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwOg==",
                        "identitytoken": "something.something.something"
                },
                "xyz.azurecr.io": {
                        "auth": "MDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwOg==",
                        "identitytoken": "something.something.something"
                }
        }
}
```

Local machine (macos): no file at ~/.docker/config.json (docker is not installed).

I'm using v0.280.0 of the Dev Containers extension.

**Comment by finite8** [comment]
I added some comments on this issue here for the same problem: https://github.com/microsoft/vscode-remote-release/issues/7982

I am worried that this "automatic" behaviour will conflict with various setups, as this current feature has forced me to downgrade the extension. If possible, could this auto-adding of the cred store be feature toggled in devcontainer.json? My team have the container set up so that the container itself negotiates required authentication to services so even if there IS a credential helper on the host we do not want the container using it.

**Comment by chrmarti** [comment]
Adding support for `"identitytoken"` here. Tracking the option to turn the entire feature off in https://github.com/microsoft/vscode-remote-release/issues/8201. Thanks.

**Comment by chrmarti** [comment]
@johnstairs Since this is quite involved could you verify the fix in the latest Dev Containers pre-release version? (Currently 0.287.0-pre-release.)

What I did:
- Create an Azure Container Registry.
- Sign-in to the Azure Container Registry using the Docker CLI inside a container without a credential helper in `~/.docker/config.json`. (That makes it write the tokens to the config file.)
- Copy the tokens from the config file in the container to the config file on your local machine.
- Create a dev container with the docker-in-docker feature and verify that you can pull or push images to the registry.
