### ISSUE TITLE
[Remote-SSH Bug]: git pull hangs when remote host is Windows system

### ISSUE THREAD

**Issue by davidkhess** [microsoft/vscode-remote-release#8101]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

I expect git pulls (over ssh) attempted via a remote ssh connection to a Windows host to work. Instead, they hang and never complete.

### Steps To Reproduce

1. Setup a VS Code client environment (in my case, macOS).
2. Setup a Windows host to act as a remote ssh host (install / enable openssh for logins).
3. Connect to the remote Windows host and open a workspace with a git repository.
4. Attempt a git pull operation.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
not relevant
```

</p>
</details>

### Anything else?

See this issue:

https://github.com/PowerShell/Win32-OpenSSH/issues/2037

There is a bug in the Windows OpenSSH code that causes this environment variable to be set when VS Code Remote-SSH connects to a Windows host:

```
c28fc6f98a2c44abbbd89d6a3037d0d9_POSIX_FD_STATE
```

The existence of that environment variable then interferes with the operation of ssh client - especially when used as a transport for git operations. In my case, git pulls (in the VS Code hosted terminal or via VSCode UI) hang and never complete.

If I unset the environment variable in a cmd.exe as follows:

```
set c28fc6f98a2c44abbbd89d6a3037d0d9_POSIX_FD_STATE=
```

the git operations complete successfully in that cmd.exe.

Additionally, git pulls in terminals not via an ssh connection (i.e. via remote desktop) are fine.

I've also proven that if I add a `HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun` script that clears this environment variable, VS Code initiated git pulls no longer hang.

So, technically, this isn't a bug in the Remote SSH extension. But, a workaround that the Remote SSH extension could implement is to clear that environment variable before launching the remote server.

**Comment by SGS-Oliver** [comment]
Thanks.
Unfortunately my git push command hangs even if I replace the variable.

**Comment by davidkhess** [comment]
@SGS-Oliver can you provide more details about the steps you are following? For instance, clearing that variable will only fix git operations in that cmd.exe after that point. Is that what you did? It’s a test to see if that is the problem, not a fix. 

Also, note that sshd.exe does not support agent forwarding on incoming ssh connections (there are open issues about it documenting the situation) - so don’t expect that to work. However, Windows ssh client does support ssh agent - meaning, you can start the Windows host ssh agent and ssh-add your key there to enable passwordless git operations after that point.

**Comment by eleanorjboyd** [comment]
hi @davidkhess, thank you for the in-depth report and for opening an issue on open-ssh. I will look into this now. One quick question- this issue is not connected to the one you have been reporting on issues https://github.com/microsoft/vscode-remote-release/issues/8073 and https://github.com/microsoft/vscode/issues/168202 right?

**Comment by davidkhess** [comment]
@eleanorjboyd that's correct. The ssh-agent forwarding issue that I run into in those issues is with my Linux hosts. This issue is particular to Windows hosts.

**Comment by eleanorjboyd** [comment]
Thank you for clarifying! And is this a regression? We have seen a regression in another part of the recent open-ssh release which we have worked to patch and didn't know if this one was also a issue related to new open-ssh version releases.

**Comment by davidkhess** [comment]
I don't know - I started using VS Code with a Windows host for the first time about 6 months or more ago and git operations have never worked there. I just finally got tired of the situation and debugged the root cause.

Because of the nature of the bug and when it was introduced in OpenSSH (5 years ago I think?), I don't think it is a regression of any sort.

**Comment by eleanorjboyd** [comment]
Hello! Thank you for your quick responses and for filing the issue upstream. I am going to mark this as closed due to the problem being upstream but feel free to come back if the problem turns out to not be upstream. Thanks
