### ISSUE TITLE
VS Code Server service setup fails on Windows with AD user

### ISSUE THREAD

**Issue by aelij** [microsoft/vscode-remote-release#8107]
- VSCode Version: 1.75.1 441438abd1ac652551dbe4d408dfcec8a499b8bf x64
- Local OS Version: Windows 11 22H2
- Remote OS Version: Windows 11 21H2
- Remote Extension/Connection Type: Server

Steps to Reproduce:

1. Open PowerShell 7 as admin
2. Run `&'code-tunnel.exe' 'tunnel' 'service' 'install'`
3. Enter username and password (tried with `user`, `domain\user` and `user@domain`)

Output:

```
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Running a Windows service under your user requires your username and password.
These are sent to the Windows Service Manager and are not stored by VS Code.
✔ Windows username: · user@domain
✔ Windows password: · ********
[2023-02-27 01:01:39] error Invalid username or password, please try again...
Running a Windows service under your user requires your username and password.
These are sent to the Windows Service Manager and are not stored by VS Code.
```

Workaround:
1. Create a local user
2. Install the service using its credentials
3. Change the VS Code Server logon credentials in the Services control panel
4. Kill the process and start the service (stop doesn't work)

**Comment by connor4312** [comment]
Was fixed in https://github.com/microsoft/vscode/pull/172679

**Comment by aelij** [comment]
@connor4312 The approach in #172679 requires the user to log on to the machine. This is less desirable if you want the tunnel to always be available and avoid RDP. Would it possible to keep both options? Perhaps just provide PowerShell commands to install it as service (`New-Service`)?

**Comment by connor4312** [comment]
Taking the initial approach was flawed for many reasons. Users are free to install the tunnel as a service in other ways, such as by using `New-Service`, but the `service install` is mostly for convenience

**Comment by aelij** [comment]
Then perhaps provide a PowerShell example in the `service install` command help? It's hard to discover the exe path and parameters.
