### ISSUE TITLE
Problem when opening a devcontainer on macOS

### ISSUE THREAD

**Issue by tomato-ga** [microsoft/vscode-remote-release#8108]
VSCode Version: 1.75.1 (Universal)
Local OS Version: MBP14 macOS Ventura 13.2.1
Remote OS Version: Mac mini macOS Ventura 13.2.1
Remote Extension/Connection Type: Containers
Remote - Containers: 0.275.1
Docker Desktop: 4.16.2 
Docker Engine: 20.10.22

Logs:

> [1707 ms] Start: Resolving Remote
> [1708 ms] Start: Run: git rev-parse --show-cdup
> [1716 ms] Start: Run: /Users/don/.docker/bin/docker ps -q -a --filter label=devcontainer.local_folder=/Users/don/docker/go121 --filter label=devcontainer.config_file=/Users/don/docker/go121/.devcontainer/devcontainer.json
> [1758 ms] Start: Run: /Users/don/.docker/bin/docker inspect --type image golang:1.20.1-bullseye
> [4099 ms] local container features stored at: /Users/don/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/node_modules/vscode-dev-containers/container-features
> [4102 ms] Start: Run: tar --no-same-owner -x -f -
> [4133 ms] Start: Run: /Users/don/.docker/bin/docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/g3/byht53l10pq3_7l4xq0tjlp80000gn/T/devcontainercli/container-features/0.29.0-1677509305340/Dockerfile-with-features -t vsc-go121-c768769c07ef330c3c1d70cbc4642455 --target dev_containers_target_stage --build-arg VARIANT=bullseye --build-arg BUILDKIT_INLINE_CACHE=0 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/don/docker/go121
> ERROR: open /Users/don/.docker/buildx/current: permission denied
> [4198 ms] Error: Command failed: /Users/don/.docker/bin/docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/g3/byht53l10pq3_7l4xq0tjlp80000gn/T/devcontainercli/container-features/0.29.0-1677509305340/Dockerfile-with-features -t vsc-go121-c768769c07ef330c3c1d70cbc4642455 --target dev_containers_target_stage --build-arg VARIANT=bullseye --build-arg BUILDKIT_INLINE_CACHE=0 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/don/docker/go121
> [4198 ms]     at pie (/Users/don/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:1916:1698)
> [4199 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> [4199 ms]     at async vF (/Users/don/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:1915:1972)
> [4199 ms]     at async P7 (/Users/don/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:1915:901)
> [4199 ms]     at async Fie (/Users/don/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:1921:2093)
> [4200 ms]     at async Vf (/Users/don/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:1921:3241)
> [4200 ms]     at async eoe (/Users/don/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:2045:17324)
> [4200 ms]     at async Qse (/Users/don/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:2045:17065)
> [4201 ms] Exit code 1
> [4203 ms] Command failed: /Users/don/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/node /Users/don/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js up --docker-path /Users/don/.docker/bin/docker --container-session-data-folder /tmp/devcontainers-36ab92a3-03e5-477a-94aa-00af5f7362091677509300896 --workspace-folder /Users/don/docker/go121 --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/don/docker/go121 --id-label devcontainer.config_file=/Users/don/docker/go121/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/don/docker/go121/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true

I found a similar report, so I took the following steps as described there, but to no avail.
https://github.com/microsoft/vscode-remote-release/issues/6814

In devcontainer.json, I added "BUILDKIT_INLINE_CACHE": "0".

**Comment by chrmarti** [comment]
`ERROR: open /Users/don/.docker/buildx/current: permission denied` indicates this is a problem with the buildx install. What do you get when running `docker buildx version` in a terminal?

**Comment by tomato-ga** [comment]
@chrmarti Thanks, I ran the docker buildx version and got the following response
`github.com/docker/buildx v0.10.0 876462897612d36679153c3414f7689626251501`

**Comment by bachirelkhoury** [comment]
@tomato-ga run `sudo chown -R $(whoami) ~/.docker ` and see if that works.
