### ISSUE TITLE
Very slow to connect to remote server

### ISSUE THREAD

**Issue by yorkshirelandscape** [microsoft/vscode-remote-release#8112]
I can't really tell you what is causing this problem, but whenever I try to develop on a remote machine, it takes VSCode FOREVER to connect and load extensions. It seems to need to install the VSCode server on the remote machine each time, gets disconnected and retries frequently, and the PTY host keeps failing. I'm happy to provide whatever output or diagnostics you need.  I'm preliminarily attaching the output of a relatively successful attempt (after quitting and restarting twice) that only took three minutes.
[vscode_output.txt](https://github.com/microsoft/vscode-remote-release/files/10849687/vscode_output.txt)

I'm running MacOS 13.0.1 and VSCode... well, here:

Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z (2 wks ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No

Thank you for any help you can offer.

**Comment by eleanorjboyd** [comment]
Hello! After attempting to connect with remote-ssh and it fails can you check the CPU on your remote machine? I am curious if it is struggling / overloaded. Also what extensions do you have installing on your remote?

**Comment by yorkshirelandscape** [comment]
You are spot on. My CPU pegs instantly when I log in. It's a VM and I guess I'm not allocating it enough processing power. Extensions are: Edit csv, Pylance, Python, ESLint, JSON Grid Viewer, Jupyter, Rainbow CSV, and SandDance. For what I'm doing on this particular machine, I don't really need half of those, but I installed them locally and I guess they automatically transfer?

**Comment by yorkshirelandscape** [comment]
Wow. I gave it a couple more cores and sockets and it's working instantly. Thank you so much. This has been driving me crazy.

**Comment by eleanorjboyd** [comment]
so glad it worked! Happy coding!
