### ISSUE TITLE
Investigate discoverability of dev containers when installed

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#8114]
Dev containers can be difficult to discover when already installed:
- Command list opened through remote indicator is hard to discover.
- Remote-Explorer doesn't indicate it might be about dev containers and its combo box shows a generic "Containers" label.
- Docker viewlet has a good icon, but the only dev container command currently is "Attach Visual Studio Code" in containers' context menu.

Ideas:
- In Remote-Explorer update contribution label to "Dev Containers".
- In Docker viewlet also contribute the "Create Dev Container" menu (with a plus icon) in the container's view toolbar.

/cc @hediet who provided feedback

**Comment by chrmarti** [comment]
Contribution of `+` to Docker viewlet (mouse cursor missing from screenshot):
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/9205389/221864218-02617a5f-68d0-4198-a921-a45efb2c7c07.png">

Updated label in Remote-Explorer:
<img width="516" alt="image" src="https://user-images.githubusercontent.com/9205389/221864614-10c31825-2832-4112-9605-26a3800d30d9.png">

/cc @bamurtaugh

**Comment by bamurtaugh** [comment]
Both of the changes you show above make a lot of sense to me!

> Command list opened through remote indicator is hard to discover.

I'd be curious to know if any of the remote indicator work @joyceerhl drove this past iteration impacts this. Is this feedback more about the discoverability of the remote indicator overall, or specifically the dev container commands once you're in the remote indicator?

**Comment by chrmarti** [comment]
The feedback was that it was not obvious that the remote indicator could be clicked to get a list of applicable commands. I think the remote indicator is missing a visual indication that it can be clicked (it lights up when the mouse hovers over it, but not many users might move their mouse point there). One approach might be to make it a UI element that users already expect to be clickable like an entry on the menubar with the commands listed as menu entries when you click it.

**Comment by bamurtaugh** [comment]
Makes sense, thanks for explaining!

> there are discussions to wiggle the remote indicator when the Open Remote entry is hovered

Yes! Though I think it's worth starting off with @bhavyaus's welcome page entry and then see if we want/need to experiment more with the remote indicator itself.

**Comment by bhavyaus** [comment]
> Makes sense, thanks for explaining!
> 
> > there are discussions to wiggle the remote indicator when the Open Remote entry is hovered
> 
> Yes! Though I think it's worth starting off with @bhavyaus's welcome page entry and then see if we want/need to experiment more with the remote indicator itself.

I'm not enabling `dev containers`  for the initial roll-out of the `Connect to...` start list entry because `dev containers` needs docker installed and additional setup to enable a golden path getting started scenario. 

I would like to enable it provided all setup dependencies are met. Is there a context I could use to check this? 
If not, let me know so that we can explore creating this and setting up `dev containers` in the start list entry.

**Comment by chrmarti** [comment]
> I would like to enable it provided all setup dependencies are met. Is there a context I could use to check this? If not, let me know so that we can explore creating this and setting up `dev containers` in the start list entry.

Is this a context the Dev Containers extension would set? (We need to check if `docker` is on the PATH.)

**Comment by joyceerhl** [comment]
@aeschli and I had previously discussed potentially generalizing the WSL recommender extension to contextually recommend additional remote extensions besides just WSL. Maybe checking whether docker is on PATH is a good fit for the recommender extension?

**Comment by bhavyaus** [comment]
> 
> Is this a context the Dev Containers extension would set? (We need to check if `docker` is on the PATH.)  

Ideally, this context would be available outside of `dev containers` extension so that we could also recommend it to be installed from the start list entry if `docker` is already on the PATH.

> Maybe checking whether docker is on PATH is a good fit for the recommender extension?
We also need to check if the docker daemon is running?

**Comment by chrmarti** [comment]
> We also need to check if the docker daemon is running?

You could leave that to the Dev Containers extension. (E.g., we might offer the user to start the deamon for them in the future.) Having the `docker` executable on the PATH is a strong indicator.

**Comment by chrmarti** [comment]
I have published the changes mentioned in https://github.com/microsoft/vscode-remote-release/issues/8114#issuecomment-1448161290. Are there any other changes we would like to be part of this issue?

Is there consensus on adding Dev Containers to the recommender extension?

**Comment by bamurtaugh** [comment]
I think adding Dev Containers to the recommender extension is interesting, but I'm a bit hesitant about using the Docker exe as a continued signal. We've seen frustration with the current Docker and dev container recommendations ([discussion](https://github.com/microsoft/vscode-internalbacklog/issues/3219)), so I think we'd want to further refine that path before adding more Docker-related recommendations. Though let me know if you think it'd avoid the issues we've discussed in the linked issue.

**Comment by chrmarti** [comment]
Sounds good. I'll close this issue here and suggest we continue the discussion in https://github.com/microsoft/vscode-internalbacklog/issues/3219. Thanks!
