### ISSUE TITLE
[Remote-SSH Bug]: Failed to install VS Code Server locally

### ISSUE THREAD

**Issue by wanderess7sgn** [microsoft/vscode-remote-release#8117]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (different error message)

### ->

> Downloading with wget
[09:28:09.358] > Download complete
[09:28:09.374] > 94a5dbfe899d%%2%%
> tar --version:
> tar (GNU tar) 1.34
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[09:28:10.917] > mv: cannot move 'vscode-server-linux-x64/bin' to './bin': Directory not empty   
> mv: cannot move 'vscode-server-linux-x64/extensions' to './extensions': Director
> y not empty
[09:28:10.985] > mv: cannot move 'vscode-server-linux-x64/node_modules' to './node_modules': Dire
> ctory not empty
> mv: cannot move 'vscode-server-linux-x64/out' to './out': Directory not empty   
> ERROR: /home/<user>/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b50
> 3ca0534/node or /home/<user>/.vscode-server/bin/97dec172d3256f8ca4bfb214
> 3f3f76b503ca0534/bin/code-server don't exist
> Trigger local server download
> 94a5dbfe899d:trigger_server_download
> platform==linux==
[09:28:10.992] > 
> vscodeArch==x64==
> destFolder==/home/<user>/.vscode-server/bin/==
> destFolder2==97dec172d3256f8ca4bfb2143f3f76b503ca0534==
> 94a5dbfe899d:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/<user>/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f
> 76b503ca0534/vscode-scp-done.flag and vscode-server.tar.gz to exist

### Steps To Reproduce

__

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
> Downloading with wget
[09:28:09.358] > Download complete
[09:28:09.374] > 94a5dbfe899d%%2%%
> tar --version:
> tar (GNU tar) 1.34
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[09:28:10.917] > mv: cannot move 'vscode-server-linux-x64/bin' to './bin': Directory not empty   
> mv: cannot move 'vscode-server-linux-x64/extensions' to './extensions': Director
> y not empty
[09:28:10.985] > mv: cannot move 'vscode-server-linux-x64/node_modules' to './node_modules': Dire
> ctory not empty
> mv: cannot move 'vscode-server-linux-x64/out' to './out': Directory not empty   
> ERROR: /home/<user>/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b50
> 3ca0534/node or /home/<user>/.vscode-server/bin/97dec172d3256f8ca4bfb214
> 3f3f76b503ca0534/bin/code-server don't exist
> Trigger local server download
> 94a5dbfe899d:trigger_server_download
> platform==linux==
[09:28:10.992] > 
> vscodeArch==x64==
> destFolder==/home/<user>/.vscode-server/bin/==
> destFolder2==97dec172d3256f8ca4bfb2143f3f76b503ca0534==
> 94a5dbfe899d:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/<user>/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f
> 76b503ca0534/vscode-scp-done.flag and vscode-server.tar.gz to exist
```

</p>
</details>

**Comment by eleanorjboyd** [comment]
Can you try running the command "kill server on remote"? Seems like some files saving the setup of the server are not being deleted correctly so a new server cannot be installed.
