### ISSUE TITLE
"Open Folder in Container" has gone missing in pre-release versions

### ISSUE THREAD

**Issue by rjra100** [microsoft/vscode-remote-release#8119]
- VSCode Version: 1.75.1
- Local OS Version: Windows 10 21H1
- Remote OS Version: RHEL7 (but we're not getting that far!)
- Remote Extension/Connection Type: Containers

In pre-release Dev Containers extension 0.280 and 0.281, the "Open Folder in Container" option has gone missing from the green connections ("><") button in the bottom left of the VSCode window. It's still present and working from the Command Palette.
Please can we have it back before this reaches full release? It'll definitely confuse all the colleagues we've trained to open containers from the green button.

**Comment by chrmarti** [comment]
We have reduced the number of commands to keep the options from overflowing when there are multiple remote dev extension installed. See https://github.com/microsoft/vscode-remote-release/issues/8018.

**Comment by rjra100** [comment]
I must say, it may just be resistance to change but I rather disagree with the choices of which options remain. When not connected to anything, that button is labelled "Open a remote window", yet what is - at least for the workflows we use - the most common "opening" operation is no longer there. Instead we have options for building containers from standard images which I suspect our compliance people would object to us using even if we wanted to, and connecting to a running container: all very well _if_ it's running.
It seems that you're wanting everyone to move to a two step "create a container; now open the folder" process, which to me seems a bit klunky compared to just "open that folder using the associated configuration"?

> As has "rebuild container".

This I don't mind so much; the button remains about opening various connection modes, so it is at least consistent. But of course it helps that I've never been in the habit of doing rebuild container from there (I always used the command palette, mostly because I saw the green button as being about connection modes rather than container management).

**Comment by rjra100** [comment]
Maybe it'd be worth making which options show up there configurable..?

**Comment by KevinYobeth** [comment]
This introduce multiple clicks to open a folder in WSL...... and it's annoying

Previously I only need to:
1. Click bottom left corner remote window button, 
2. and click "WSL: Open Folder in WSL...". 

Now I have to: 
1. Click remote window button, 
2. connect to the WSL, 
3. and then click open, 
4. then select the folder.

maybe add a config for this kind of behavior?

**Comment by chrmarti** [comment]
The commands are still available from the command pallette. (Press `F1` and then type to filter down.)

**Comment by dreamwayjgs** [comment]
The commands are also available in shortcuts. But I'm not sure it is good solution...

**Comment by amarrella** [comment]
It's really a degratation in UX having to look for the rebuild command in the command palette instead of having them available in the "container" button in the bottom left :( please reconsider this decision

**Comment by chrmarti** [comment]
Adding back `Open in Container...` to the empty window and `Rebuild Container` when already connected to a dev container. HTH!
