### ISSUE TITLE
Launch docker when it isn't running

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-remote-release#8121]
When using Dev Containers on macOS and Windows, it is possible that Docker Desktop is not running. In such a case, it would be helpful to have a "Launch Docker Desktop" button in this dialog:

<img width="361" alt="image" src="https://user-images.githubusercontent.com/5047891/222151455-933d38d1-aaa1-4d18-8095-80932763ec6e.png">

cc @kieferrm

**Comment by chrmarti** [comment]
Tracked as https://github.com/microsoft/vscode-remote-release/issues/8089.
