### ISSUE TITLE
Command 'Remote-Tunnels: Connect to Tunnel...' resulted in an error

### ISSUE THREAD

**Issue by playbahn** [microsoft/vscode-remote-release#8125]
![image](https://user-images.githubusercontent.com/111122492/222471235-a2c0ab9b-27ac-45c5-9ea3-b933f2ed22b9.png)

The same issue as [this](https://github.com/microsoft/vscode-remote-release/issues/here), with additional information.

Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Local OS: Windows_NT x64 10.0.18363 (a modded Windows 10 Pro from Oprekin)

Remote OS: Windows 11 Home

Extension: Name: Remote - Tunnels v1.0.0

Here's what I've found that seems to be useful info.

The remote system seems to be working just fine.

For the local system:
The `code tunnel` command doesn't work in cmd (I don't have Powershell). So I can't create a tunnel. Maybe for even distantly related reasons, I can't connect to one?

![image](https://user-images.githubusercontent.com/111122492/222486969-91a32375-6831-41ef-ba66-9707f62da847.png)

On the remote machine, the "source" column shows the extension name "Remote - Tunnels", while on local machine the "source" column shows "Default". Maybe the extension isn't working correctly? I've tried uninstalling the extension from extensions menu, and also deleting it from the _%PROFILE%/.vscode/extensions_ directory. Nothing seems to work.

![image](https://user-images.githubusercontent.com/111122492/222471684-be72d63a-e408-4e65-bf6f-308015c8f265.png)

I can connect just fine only when I'm using vscode.dev, but the issue persists when I use the desktop client

**Comment by connor4312** [comment]
You're on a fairly old version of VS Code, the latest is 1.77. Please upgrade and let us know if you still are hitting issues.

**Comment by playbahn** [comment]
Updated to 1.76.2. Issues resolved.
