### ISSUE TITLE
Connecting hangs when incorrectly entering password on second or third prompt

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-remote-release#813]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode-remote-release/issues/750

Using Remote - SSH Nightly version 2019.6.35460

1. Try to connect to the host
2. Enter the password correctly on the first prompt
3. Enter a wrong password three times after that

(Entering the password correctly twice and then incorrectly three times has the same behavior)

The notification still shows "Setting up SSH tunnel". Clicking on details, nothing is displayed in the terminal. No further prompts are shown.

VS Code version: Code - Insiders 1.36.0-insider (e80dd4f217db6e230d311a87fdf4276f740f6445, 2019-06-25T05:19:01.461Z)
OS version: Windows_NT x64 10.0.18362

**Comment by sbatten** [comment]
@roblourens I still see this issue

**Comment by roblourens** [comment]
Now N/A
