### ISSUE TITLE
Unable to install extension 'ms-vscode-remote.remote-wsl' as it is not compatible with VSCodium '1.75.1'.

### ISSUE THREAD

**Issue by sre-data-engineer** [microsoft/vscode-remote-release#8130]
- VSCode Version:
Version: 1.75.1 (system setup)
Release: 23040
Commit: c6a9727b801542499d2b59cb7db4224e060fc578
Date: 2023-02-09T22:46:15.410Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

- Local OS Version:
Майкрософт Windows 10 Pro 10.0.19045 build 19045
- Remote OS Version:
Oracle Linux Server 8.7 (Ootpa) ol8
- Remote Extension/Connection Type: 
WSL

- Logs:
Unable to install extension 'ms-vscode-remote.remote-wsl' as it is not compatible with VS Code '1.75.1'.

Steps to Reproduce:

1. Download ms-vscode-remote.remote-wsl-0.76.1.vsix
2. Try to install from VSCodium extensions "Install from VSIX" menu

**Comment by aeschli** [comment]
0.76 requires VS Code 1.76

**Comment by pantaoran** [comment]
My company currently only lets me install VS Code 1.74.3 through their software center.
How can I download the vsix file for that version? @aeschli 
I tried through the following URL, and that seems to work until back to version 1.77.0, but older version numbers give me an error:
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-wsl/0.77.0/vspackage
