### ISSUE TITLE
Cannot ssh connect on the recent VSCode 1.76 (WebSocket close with status code 1006)

### ISSUE THREAD

**Issue by supernovaZhangJiaXing** [microsoft/vscode-remote-release#8131]
- VSCode Version: 1.76.0
- Local OS Version: Windows 10
- Remote OS Version: Rocky 9 & CentOS Stream 9
- Remote Extension/Connection Type: Server

Steps to Reproduce:

1. Update the VSCode to 1.76
2. Just connect remote ssh with Remote - SSH extension

**Comment by lawson-ng** [comment]
Same problem.

**Comment by ieraora** [comment]
me too

**Comment by ieraora** [comment]
Here the solution https://github.com/microsoft/vscode/issues/175878

**Comment by rzhao271** [comment]
Closing as a duplicate
