### ISSUE TITLE
Cant edit&save Dockerfile while being inside the container

### ISSUE THREAD

**Issue by Mahosaurus** [microsoft/vscode-remote-release#8134]
Since today, I cant save the modified Dockerfile anymore while being inside the container. It makes debugging a lot harder. Other files can be edited as usual.
Error looks like below.

Docker engine: v20.10.23 / WSL 2 backend
Docker Desktop 4.17.0 (99724)
Dev Containers v0.282.0
VS Code: 1.75.1

- Logs:
![grafik](https://user-images.githubusercontent.com/13378914/222713005-5ae03455-84cf-452c-b2b8-5bf4a398cf0e.png)
Steps to Reproduce:

1. Open folder in Container
2. Try to save the edited Dockerfile

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
What are the permissions on the Dockerfile?

**Comment by Mahosaurus** [comment]
They are -rw-r--r--
I don't know what changed, but it actually works again.
