### ISSUE TITLE
"Open folder in WSL" is missing 

### ISSUE THREAD

**Issue by tundragon** [microsoft/vscode-remote-release#8135]
Type: <b>Bug</b>

Hello
I have updated VS Code to the latest version and i have noticed in the "WSL" extenstion that the "Open Folder in WSL"  is missing, when i want to connect to WSL.

Extension version: 0.76.1
VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by enekux** [comment]
+1

**Comment by j30393** [comment]
+1

**Comment by MrBrodinha** [comment]
+1

**Comment by kkmbsky** [comment]
+1

**Comment by Basti82b** [comment]
+1

**Comment by maxzerker** [comment]
workaround: install the previous working version (0.75.3) the menu has been gone since 0.76 onwards

**Comment by asanchez-kore** [comment]
+1

Bring it back. Convenient "Open in Dev Container" is still there..

**Comment by loquilloll** [comment]
+1

Bring it back. Convenient "Open in Dev Containers" is still there.

**Comment by andyye1999** [comment]
he option "Reopen Folder in WSL..." is missing

**Comment by DevilSakuya** [comment]
++

**Comment by andy-kogsys** [comment]
++

**Comment by tundragon** [comment]
It is fixed in 
Version: 1.76.1 (system setup)

**Comment by carlosrmendes** [comment]
v1.76.2 (user steup) and still not works

**Comment by ArnauMontagud** [comment]
+1
not working in v1.76.2

**Comment by 78wesley** [comment]
+1 Not working in v1.77.0

**Comment by ADCWilson** [comment]
+1
Not working in v1.76.2
