### ISSUE TITLE
Cannot open Devcontainer in VSCode 1.76.0

### ISSUE THREAD

**Issue by sairaghavak** [microsoft/vscode-remote-release#8138]
- VSCode Version: 1.76.0
- Local OS Version:  Linux Mint 20.2
- Remote OS Version: debian:bullseye-slim
- Remote Extension/Connection Type: Containers

Container log is stuck here
![image](https://user-images.githubusercontent.com/16429828/222807939-6f73993f-b101-4ec4-92fb-6fb8b890f02c.png)

And when I tried to see the output specific to extension host it keeps waiting
![image](https://user-images.githubusercontent.com/16429828/222808048-0543eee2-7e2e-4a7d-9554-6298bcadfa0a.png)

Tried deleting the whole docker data locally, but the issue exists

**Comment by chrmarti** [comment]
Could you append the full log? (The server should announce when it is ready to receive connections, maybe that is missing.)
