### ISSUE TITLE
Remote-SSH uname -sm runs forever 

### ISSUE THREAD

**Issue by bangyogesh** [microsoft/vscode-remote-release#814]
Remote-SSH in VSCode to a Ubuntu 18.04 VM from Windows 8.1 machine. The window goes into infinite loop with below message. Please find the attached ScreenShot for details.

I am using vscode-insiders, the details of which are as below.
Version: 1.35.0-insider
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T00:13:30.572Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.3.9600

![image](https://user-images.githubusercontent.com/2494368/60123246-a3cc0b80-97a4-11e9-944b-3c86c320d280.png)

**Comment by roblourens** [comment]
This is an old version of vscode insiders, can you try updating? And is this the nightly version of the ssh extension?
