### ISSUE TITLE
`Dev Containers: Clone Repository in Container Volume...` fails when `"updateRemoteUserUID": true`

### ISSUE THREAD

**Issue by darkdragon-001** [microsoft/vscode-remote-release#8145]
- VSCode Version: 1.74.3
- Local OS Version: Debian 12
- Remote OS Version: Debian 12
- Remote Extension/Connection Type: Containers

- Logs: _see below_

Steps to Reproduce:

1. Create repository with the following files:
    `.devcontainer/devcontainer.json`:
    ```json
    {
    	"build": {
    		"dockerfile": "Dockerfile"
    	},
    	"remoteUser": "builder",
    	"updateRemoteUserUID": true
    }
    ```
    `.devcontainer/Dockerfile`:
    ```Dockerfile
    FROM debian
    RUN adduser builder
    ```
2. Run `Dev Containers: Clone Repository in Container Volume...` and select your repository

Starting fails with error:
```
Command failed: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /workspaces/REPO --workspace-mount-consistency cached --id-label vsch.local.repository=git@github.com:ORG/REPO.git --id-label vsch.local.repository.volume=vsc-remote-containers --id-label vsch.local.repository.folder=REPO --log-level debug --log-format json --config /workspaces/REPO/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-26c12896-8ab3-419c-a6c5-8ab61df8eaf9.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vsc-remote-containers,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root true
```

Is this releated to `--update-remote-user-uid-default off` being part of the options in the failed command?

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
The default would be off when cloning in a volume, why are you setting the property to true? It defaults to on when using a local folder on Linux.

**Comment by darkdragon-001** [comment]
I need to (read-only) mount a local cloud credential folder into the container. Without this option set, the unprivileged user doesn't have permission to read it...

**Comment by chrmarti** [comment]
I can fix the error. The remaining issue is that the devcontainer CLI doesn't get at your local UID/GID because it runs as root in the temporary container. Will open a separate issue for that.
