### ISSUE TITLE
Can not connect to remote host on the latest vs code (1.76.0)

### ISSUE THREAD

**Issue by Kicey** [microsoft/vscode-remote-release#8146]
- VSCode Version:1.76.0
- Local OS Version: Ubuntu 22.04 (Linux version 5.19.0-35-generic) and Windows 10
- Remote OS Version: Ubuntu 22.04, Ubuntu 20.04
- Remote Extension/Connection Type: Server

The vscode on ubuntu recently get upgraded, and then I found that I can't use remote extension to connect my server, then I try it on my windows laptop (as the ssh client), there is no problem. Then I upgrade my vscode on my windows laptop. The same problem appear again.

- Logs:

[23:03:15.980] Failed to parse remote port from server output
[23:03:15.981] Resolver error: Error: 
	at m.Create (/home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:584388)
	at t.handleInstallOutput (/home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:582948)
	at Object.e [as tryInstallWithLocalServer] (/home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:623670)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:643639
	at async t.withShowDetailsEvent (/home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:647359)
	at async /home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:622142
	at async C (/home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:618648)
	at async t.resolveWithLocalServer (/home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:621757)
	at async t.resolve (/home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:644967)
	at async /home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:720839

Steps to Reproduce:

1. Upgrade vs code to 1.76.0.
2. Try to connect a remote host.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by Kicey** [comment]
> Same on macOS. Downgraded to VSCode to January's version and everything working again.

The problem fixed. The remote extension works correctly now.

**Comment by Saicharan2001** [comment]
> Same on macOS. Downgraded to VSCode to January's version and everything working again.

I tried but didn't work

**Comment by Saicharan2001** [comment]
> * VSCode Version:1.76.0
> * Local OS Version: Ubuntu 22.04 (Linux version 5.19.0-35-generic) and Windows 10
> * Remote OS Version: Ubuntu 22.04, Ubuntu 20.04
> * Remote Extension/Connection Type: Server
> 
> The vscode on ubuntu recently get upgraded, and then I found that I can't use remote extension to connect my server, then I try it on my windows laptop (as the ssh client), there is no problem. Then I upgrade my vscode on my windows laptop. The same problem appear again.
> 
> * Logs:
> 
> [23:03:15.980] Failed to parse remote port from server output [23:03:15.981] Resolver error: Error: at m.Create (/home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:584388) at t.handleInstallOutput (/home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:582948) at Object.e [as tryInstallWithLocalServer] (/home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:623670) at process.processTicksAndRejections (node:internal/process/task_queues:96:5) at async /home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:643639 at async t.withShowDetailsEvent (/home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:647359) at async /home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:622142 at async C (/home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:618648) at async t.resolveWithLocalServer (/home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:621757) at async t.resolve (/home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:644967) at async /home/kicey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:720839
> 
> Steps to Reproduce:
> 
> 1. Upgrade vs code to 1.76.0.
> 2. Try to connect a remote host.
> 
> Does this issue occur when you try this locally?: Yes/No Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

Would some one help tried all the methods like upgrading and downgrading versions .. unable to connect
