### ISSUE TITLE
[Remote-SSH Bug]: unexpected mac address format

### ISSUE THREAD

**Issue by markieboy223** [microsoft/vscode-remote-release#8149]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### ->

When remote server listen on socket is turned off
![image](https://user-images.githubusercontent.com/40497236/223177818-a80c0cc2-2aca-4a47-abd9-9c7b09834d41.png)
I cannot connect to my linux server when trying to connect using remote ssh. Does anyone have a solution, this came out of nowhere btw on saturday it was still working properly.

When remote server listen on socket is turned off this happens 
![image](https://user-images.githubusercontent.com/40497236/223178459-c6a776c2-5d55-4b6f-bbf5-6fcfdfa521ab.png)
or this happens
![image](https://user-images.githubusercontent.com/40497236/223179675-6f165601-9a5d-4ba9-9814-31377fa6d684.png)
![image](https://user-images.githubusercontent.com/40497236/223179742-a292738a-63cb-4fd5-88a3-0b61baaa9b89.png)
![image](https://user-images.githubusercontent.com/40497236/223179992-59a1231f-a37b-48cd-b8ba-72754bee6f9d.png)

Does anyone know what's going wrong and the solution.

### Expected Behavior

Just 2 days ago it was connecting fine as expected.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
Spawned remote server: 54389
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...
 
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*

7df6b01e0e3d: start
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==43220==
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==365==
connectionToken==3d5935c3-e1d3-4069-96e6-531d6164fc5d==
7df6b01e0e3d: end
 channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused


```

</p>
</details>

### Anything else?

So far ive tried to change extension settings and the kill vscode server on remote command.
Also i tried connecting with one other device which is my laptop and first time it connected but the second time the same errors occured.

Other devices still work properly just my laptop and dekstop get these errors now.

**Comment by markieboy223** [comment]
> Same here...
> 
> In de log file on the remote host these entries are the last before the code server stops ..
> 
> Visual Studio Code Server .. v 1.76
> 
> Error: Unable to retrieve mac address (unexpected format)
> 
> Error: Unable to retrieve mac address (unexpected format) at S (/home/...../.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:63:3251) at v (/home/...../.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:74:8276) at async /home/..../.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:74:8133 at Timeout._onTimeout (/home/bvveen/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:8:12) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
> 
> I understand on 1 March the server code change and is now using the MAC address as a security.... On my remote server ( Strato VM ) there is no MAC address when I use IP LINK of IP ADDR.
> 
> Seems that the change introduced a new problem.

Using strato as well so that seems to be the problem,
are there any solutions to this yet?

**Comment by RussianProtein** [comment]
Same problem. I can't find a solution yet

**Comment by bmakan** [comment]
My vscode couldn't download the vscode-server remotely. It was just hanging. So, I logged into the remote machine and downloaded the vs-server manually:

```bash
wget  https://update.code.visualstudio.com/commit:92da9481c0904c6adfe372c12da3b7748d74bdcb/server-linux-x64/stable
mv stable vscode-server.tar.gz
tar -zxf vscode-server.tar.gz
mv vscode-server-linux-x64/* ./
```

> Commit hash depends on your current version. You can check it in `Help` -> `About`.

**Comment by cggit** [comment]
> Same problem. I can't find a solution yet

Downgrade VSCode should fix it

**Comment by eleanorjboyd** [comment]
Could someone include their full remote-ssh logs?

**Comment by eleanorjboyd** [comment]
> I understand on 1 March the server code change and is now using the MAC address as a security....

@bvv400 could you elaborate a bit more on what you mean by this?

**Comment by bvv400** [comment]
@eleanorjboyd 

This is de log file on de server when Remote SSH connection is started.   Also the ifconfig. 

[92da9481c0904c6adfe372c12da3b7748d74bdcb.log](https://github.com/microsoft/vscode-remote-release/files/10961685/92da9481c0904c6adfe372c12da3b7748d74bdcb.log)

[ifconfig.txt](https://github.com/microsoft/vscode-remote-release/files/10961761/ifconfig.txt)

**Comment by bvv400** [comment]
@eleanorjboyd 

Found the error txt in  vscode-1.76.1\src\vs\base\node\macAddress.ts.

If no MAC address is registered then an error is thrown.

**Comment by sbatten** [comment]
I think this is fixed now with https://github.com/microsoft/vscode/pull/176512

**Comment by eleanorjboyd** [comment]
This change should therefore be out on insiders. I will close this in favor of the other discussion so please post in that issue if you are still seeing problems on insiders or have further questions.
