### ISSUE TITLE
Remote Containers fails to communicate with docker after system upgrade

### ISSUE THREAD

**Issue by exhuma** [microsoft/vscode-remote-release#8153]
Since I did a system upgrade, the remote-container extension no longer works. It fails with the following error-dialog:

![image](https://user-images.githubusercontent.com/65717/223349386-8889a404-5499-4489-a835-3638b80f5916.png)

Looking at the logs, it looks like the output of the `docker ps` command is not parsed correctly. It sees the string `IMAGE STATUS NAMES PORTS` as container-id/-name. This then makes subsequent commands fail. Here is the relevant part of the logs:

```
[2023-03-06T06:10:13.679Z] Stop (39 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/exhuma/work/flog --filter label=devcontainer.config_file=/home/exhuma/work/flog/.devcontainer/devcontainer.json
[2023-03-06T06:10:13.679Z] Start: Run: docker inspect --type container IMAGE     STATUS    NAMES     PORTS
[2023-03-06T06:10:13.716Z] Stop (37 ms): Run: docker inspect --type container IMAGE     STATUS    NAMES     PORTS
[2023-03-06T06:10:13.716Z] Command failed: docker inspect --type container IMAGE     STATUS    NAMES     PORTS
```

- VSCode Version: 1.76.0
- Local OS Version: Arch Linux
- Remote OS Version: /
- Docker Version: 23.0.1, build a5ee5b1dfc
- Remote Extension/Connection Type: Containers

**Comment by chrmarti** [comment]
`-q` should skip that header in the output. What do you get when you run `docker ps -q -a` in a terminal?

**Comment by exhuma** [comment]
Seems like `-q` is not having any effect.

Command without `-q`:
```
› docker ps -a
IMAGE     STATUS                    NAMES          PORTS
node:18   Exited (0) 26 hours ago   hopeful_bell
```

... and with `-q`:

```   
› docker ps -q -a
IMAGE     STATUS                    NAMES          PORTS
node:18   Exited (0) 26 hours ago   hopeful_bell   
```

Here's the docker version:

```
› docker --version
Docker version 23.0.1, build a5ee5b1dfc
```

I've come across a web-post stating that installing docker via snap would help and there is indeed a difference. I've installed it in parallel and the snap version works. That version is an *older* version though:

```
› /snap/docker/current/bin/docker --version
Docker version 20.10.17, build 100c70180f
```

Could it be that the newer docker versions cause problems?

**Comment by exhuma** [comment]
That's interesting... exactly the same build number and different behaviour... I noticed that the `-q` flag has no effect at all for me. It not only keeps the header intact, it also shows the full container details. That is, it does not show the ID at all.

I wonder if it has something to do with the Arch package. In which case I'll open an issue over there.

What's your MD5-sum of the `docker` executable? Here's mine:

```
› md5sum /usr/bin/docker 
ee5c16a1221c2d2cfc49f292b046f144  /usr/bin/docker
```

**Comment by chrmarti** [comment]
I don't expect the executables to be identical since they were built separately against separately built libraries and distros. Opening a issue with Arch sounds like a good next step. I'll close this issue here since it does not appear to be an issue with Dev Containers, thanks!

**Comment by yakisamin** [comment]
@chrmarti -q didn't work for me on ubuntu 20.04, I had to reinstall docker using snap (which gave me version 20.x) to fix the same issue OP was having.

**Comment by exhuma** [comment]
If anyone else comes across this: In my particular case it is cause by a customised `psFormat` in my `~/.docker/config.json`

This was not a problem in an older version of docker. I don't see the connection with `snap` yet though. Might just be a slightly different version.

In any case, I opened a corresponding bug report here: https://github.com/docker/cli/issues/4093

As a workaround it is possible to simply remove the customised `psFormat` from the config.

**Comment by exhuma** [comment]
@chrmarti In my research I came across a JSON format for `docker ps`:

```
docker ps -a --format '{{ json . }}'
```

It is a hell of a lot slower though. Which may or may not be an issue. If speed is *not* an issue here, would this not be a good alternative to simple stdout parsing from a "raw" `docker ps`?

Concerning the speed: If this is only used once on container startup, this slowdown may be negligible. If, on the other hand, the command needs to be executed often, parsing raw stdout might still be preferrable.
