### ISSUE TITLE
Maintain a local volume mount + remote volume

### ISSUE THREAD

**Issue by bhack** [microsoft/vscode-remote-release#8160]
How we could maintain a local folder mount and at the same a remote volume mount in the same devcontainer configuration?

E.g.
https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host#_converting-an-existing-or-predefined-devcontainerjson

There are some suggestion on how to sync the local folder remotely at:
https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host#_optional-making-the-remote-source-code-available-locally

But the main point is how to maintain a compatible configuration when we want to use the same devcontainer locally and remotely on the same repo.

**Comment by chrmarti** [comment]
We recommend checking out the repository remotely while connected with the Remote-SSH extension. You can then reopen the remote folder in a remote container the same way you do locally. See https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host#_connect-using-the-remote-ssh-extension-recommended.

**Comment by bhack** [comment]
The point is different.
Suppose that you have a Docker remote and local  instance for the same repository. Local and remote is controlled by the docker context.
In the remote you are going to work with a remote folder or a with a docker volume. But at the same time in the local context you work with a local fonder mount.

It is very annoying to comment and uncomment in the devcontainer configuration between remote volume and local folder mount every docker context switch.

**Comment by chrmarti** [comment]
You can use `Clone Repository in Volume` while you are connected to the SSH server using Remote-SSH. That will change the workspace mount to the volume mount.

The documentation recommends the use of Remote-SSH to connect to the SSH server. The other documented ways of connecting to a remote Docker daemon also work, but might be less convenient. Maybe we could call this out better in the documentation.

**Comment by bhack** [comment]
Generally the pipeline is to clone a repo locally and use a local docker container to make some development activities.
Then when you need more resources on the same project it easy to switch the docker context to the remote one.
But then the `worspaceFolder` specification it will be incompatible between the local mount and the remote volume `workspaceMount`.

**Comment by bhack** [comment]
I was guessing: 
Do you think that we could solve this just with https://github.com/devcontainers/spec/issues/6?
Or have some entries in `.devcontainer` (like the workspace mount) that are host specific?

**Comment by chrmarti** [comment]
I recommend using Remote-SSH to connect to the remote host and then reopen the folder there (or using the mention "clone in container" command). That should match the pipeline you describe. https://github.com/devcontainers/spec/issues/6 would also be an option.
