### ISSUE TITLE
Cannot open a remote folder using the Tunnels extension

### ISSUE THREAD

**Issue by SotoiGhost** [microsoft/vscode-remote-release#8166]
Suddenly, I cannot longer open a remote folder using the Remote Tunnels extension by manually connecting to the Remote Tunnels extension.

Steps to reproduce the issue:

1. Open vscode.dev
2. Click on the “Remote Tunnels” button (Left-down corner button)
3. Click on “Connect to Tunnel” and pick the desired tunnel
4. Wait for VSCode to connect to the tunnel and a warning message will appear

![F2C41000-1CDB-4947-AE85-11E885A613EF](https://user-images.githubusercontent.com/5924210/223873138-58512248-977e-499d-afad-eb55fb9d24b6.jpeg)

Here’s a video of the issue:

https://user-images.githubusercontent.com/5924210/223873394-69d35e05-5e36-45f5-b4ed-c8b8213a3176.mp4

I can connect to a Tunnel using the URL generated by the extension.

I’ve already deleted the `.vscode-cli`, `.vscode-server` and reinstalled the extension on the main machine, but it’s still failing.

Here are the logs:  [20230308T144058.zip](https://github.com/microsoft/vscode-remote-release/files/10926443/20230308T144058.zip)

I tried to open the folder named: **FacebookComponents**

Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
Embedder: vscode.dev

**Comment by ryoi084** [comment]
I can also connect remote tunnels by `menu bar`.
Can you do that?

(I can't access my workspace from "connect to tunnel" button, too)

**Comment by Ghvinerias** [comment]
Im getting same problem

**Comment by SotoiGhost** [comment]
@ryoi084 How do you do it from `menu bar`? I'm not finding the option.

Btw, I tried installing vscode.dev as PWA and use the `Open URL` with the Tunnel URL, but that does not do anything.

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode-remote-release/issues/8212
