### ISSUE TITLE
Default WSL distro started for no apparent reason

### ISSUE THREAD

**Issue by voltamund** [microsoft/vscode-remote-release#8171]
Version: 1.76.0 (system setup)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:22:44.506Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

For some reason opening a devcontainer on a remote ssh host in VS Code starts my default WSL distro on Windows.

1. Open new VS Code Window on Windows Host -> WSL not started
2. Connect to Linux VM via ssh (not wsl distro) -> WSL not started
3. On Linux VM open folder or workspace in devcontainer -> The container starts on the Linux VM, **but the default WSL distro on Windows host is also started**

It is really not clear which part of VS Code starts the WSL distro and why this is done at all.
The devcontainer runs in docker or podman on the Linux VM. VS Code connects to it through ssh. WSL should not be involved at all.
For now at least I set a WSL1 distro as my default to make it cheaper.

I could reproduce this on two different machines with similar setup. It also happens when opening the most recent folder / workspace (devcontainer on ssh host) directly.

**Comment by bamurtaugh** [comment]
Thanks for opening @voltamund. Do you have the WSL2 backend set up for Docker Desktop: https://code.visualstudio.com/docs/devcontainers/containers#_system-requirements? If so, I could imagine that might be the cause.

**Comment by voltamund** [comment]
I do not have Docker Desktop installed on Windows. No Docker is installed on the Windows host. Docker is only installed inside the Linux VM using the distro's package.
I had a closer look at the container log. It could be related to userEnvProbe. I also tried `"userEnvProbe": "none"` in devcontainer.json. But even after rebuilding the container, I can see some userEnvProbe without none: The log contains multiple userEnvProbe, some are `none`, some are `loginInteractiveShell`. It looks like vscode tries to be too smart. I start a container in a Linux VM. It may look at the environment of my Windows host and the VM where docker runs. But it should definitely not snoop into a completely unrelated WSL distro. I can even see that it creates a  `.vscode-remote-containers` folder in the wsl home directory. 

```
[900 ms] Start: Run in host: test -f '/home/xxx/.vscode-remote-containers/dist/vscode-remote-containers-server-0.282.0.js'
[901 ms] 
[901 ms] 
[904 ms] userEnvProbe: loginInteractiveShell (default)
[904 ms] userEnvProbe: not found in cache
[904 ms] userEnvProbe shell: /bin/bash
[1136 ms] userEnvProbe PATHs:
Probe:     '***'
Container: None
[1138 ms] Setting up container for folder or workspace: ***.code-workspace
[1138 ms] Host: ssh://linux-vm
[1139 ms] Start: Run: wsl -l -v
[1422 ms] Start: Run: wsl -d Debian -e /bin/sh -c echo ~
[2183 ms] Start: Run: wsl -d Debian -e /bin/sh -c cd '/home/xxx' && /bin/sh
[2218 ms] Start: Run in host: id -un
[2538 ms] xxx
[2538 ms] 
[2538 ms] Start: Run in host: cat /etc/passwd
[2569 ms] Start: Run in host: echo ~

```

**Comment by bamurtaugh** [comment]
@chrmarti @aeschli thoughts?

**Comment by chrmarti** [comment]
@voltamund We connect to services inside WSL. Try setting the WSL Distro for Dev Containers to one that does not exist in your user settings:
<img width="471" alt="image" src="https://user-images.githubusercontent.com/9205389/229048159-4b718b98-115f-461f-a5e9-c8a261fa0b5b.png">

That seems to work around this.
