### ISSUE TITLE
(Re)building dev container adds invalid mount to generated docker compose

### ISSUE THREAD

**Issue by ahl-trifork** [microsoft/vscode-remote-release#8172]
Type: <b>Bug</b>

Since last i rebuilt my dev container the rebuild process adds a new volume which seems to be invalid, producing the following error: 
```
docker: Error response from daemon: invalid mount config for type "bind": bind s
ource path does not exist: \\wsl.localhost\Ubuntu\mnt\wslg\runtime-dir\wayland-0
```

I'm running Windows using Rancher desktop instead of Docker desktop, but havn't had any issues because of that before, so I'm not sure if that's the cause. 

As minimal reproduciton i created an empty workspace with only a `.devcontainer/devcontainer.json`  file containing:
```
{
	"name": "Ubuntu",
	"image": "ubuntu:20.04"
}
```

For my actual workspace I'm using docker compose getting a slightly different error, but  they seem to be caused by the same volume mount: 
```
Error response from daemon: create \\wsl.localhost\Ubuntu\mnt\wslg\runtime-dir\w
ayland-0: "\\\\wsl.localhost\\Ubuntu\\mnt\\wslg\\runtime-dir\\wayland-0" include
s invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" a
re allowed. If you intended to pass a host directory, use absolute path
```

I took a look at generated docker compose files in `C:\Users\ahl\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data\docker-compose`

I found that there was a difference between files generated today and files generated a few weeks ago. The following volume is added, without the actual docker compose file in my workspace having changed:
`- \\wsl.localhost\Ubuntu\mnt\wslg\runtime-dir\wayland-0:/tmp/vscode-wayland-3d4914df-ebfb-40f2-bbca-efb3a59da01d.sock`

Is there a way I can make it not generate that mount? Earlier today everything was running fine, but i had to change my configuration for another container in my compose setup, and now my dev container won't build. 

Extension version: 0.282.0
VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (7.65GB free)|
|Process Argv|--crash-reporter-id c8ad24ca-22fd-46d8-8d93-5f0b3f27a8f6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30677849
vscodeenable:30660116
funwalk2:30682974
pythonms35:30680984

```

</details>

**Comment by eposgmbh** [comment]
I have the same issue, albeit with Docker Desktop for Windows (non-WSL version).

**Comment by ahl-trifork** [comment]
FYI - Downgrading the `Dev Containers` plugin to `v0.266.1` solved it for me, but i look forward to a fix 😊

You downgrade by selecting `Install another version` under the uninstall dropdown:
![image](https://user-images.githubusercontent.com/108787421/225368670-af2172ab-dacd-42e1-b545-67da83840280.png)

**Comment by sonikro** [comment]
> FYI - Downgrading the `Dev Containers` plugin to `v0.266.1` solved it for me, but i look forward to a fix 😊
> 
> You downgrade by selecting `Install another version` under the uninstall dropdown: ![image](https://user-images.githubusercontent.com/108787421/225368670-af2172ab-dacd-42e1-b545-67da83840280.png)

That worked for me.

I`m having the same problem, and this is my environment:

> WSL version: 1.1.3.0
Kernel version: 5.15.90.1
WSLg version: 1.0.49
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19043.2364

Rolling back to 0.266.1 fixed the issue

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/8157.
