### ISSUE TITLE
Running "code -r ." from Remote SSH terminal results in an error.

### ISSUE THREAD

**Issue by ksaito1125** [microsoft/vscode-remote-release#8175]
Type: <b>Bug</b>

When I run "code -r ." from Remote SSH terminal, I get the following error.
This has happened since I updated VSCode today.

```
ubuntu@ip-10-15-83-125:~/tmp/ec2$ code -r .
Unable to connect to VS Code server: Error in request.
Error: connect ENOENT /run/user/1000/vscode-ipc-41cec0ea-2b92-48b0-b712-531a1fa0801b.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/run/user/1000/vscode-ipc-41cec0ea-2b92-48b0-b712-531a1fa0801b.sock'
}
ubuntu@ip-10-15-83-125:~/tmp/ec2$
```

Even after rebooting the server and deleting $HOME/.vscode-server, I got an error.
It looks like a phenomenon with low reproducibility.

Extension version: 0.98.0
VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.0-1031-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.73GB (1.22GB free)|
|Process Argv|--crash-reporter-id 131ce736-6fa7-46d5-80be-2c46842e3916|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev|
|OS|Linux x64 5.15.0-1031-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz (2 x 2500)|
|Memory (System)|3.77GB (3.01GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyonecf:30548226
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsctsb:30677850
pythonb192cf:30669361
funwalk2cf:30682975

```

</details>

**Comment by eleanorjboyd** [comment]
Can you successfully connect if you use the UI from VS Code or for your setup do you have to SSH into the remote and then spin up VS Code with `code -r .`?

@alexdima looping you in since I am not sure if this is the resolver or the ssh connection.

**Comment by ksaito1125** [comment]
In my environment, I use VSCode as follows.

* Launch VSCode for Windows
* Connect to EC2 with Docker set up using Remote SSH
* Open the project with ``code -r .``
* Start development container with Reopen in Container

I have been using this procedure for over half a year.
I plan to prepare a new EC2 instance and see if the phenomenon improves.
Is there anything else I should do to resolve the issue?
