### ISSUE TITLE
Initial automatic port detection can be very slow

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#8177]
Remote that have just been set up at connection time (such as when a Codespace is created) can run into the following problem:
1. Machine is very busy initializing.
2. Remote connection causes more commands to be run, such as starting VS Code processes and running `npm install` + other post install actions.
3. Auto port forwarding starts
4. Because the machine is so busy, the first couple port scans are very slow, causing the [moving average](https://github.com/microsoft/vscode/blob/1b6f8ebd88da711d02d0df3987db32e43e54089b/src/vs/workbench/api/node/extHostTunnelService.ts#L269-L270) used for calculating the delay between port scans to be very large.

This makes it look like automatic port forwarding is very slow for the first couple minutes.

To solve this, we should try not to inflate the moving average for the first 2-3 scans. 

This could result in the post install actions slowing down slightly as more cycles will be devoted to port scanning, but should result in automatic port forwarding not looking broken.

**Comment by andreamah** [comment]
Are there some verif steps for this?
