### ISSUE TITLE
Copying last command output fails over Remote Explorer SSH but works locally

### ISSUE THREAD

**Issue by 0x303** [microsoft/vscode-remote-release#8187]
The setting for this VSCode action is `workbench.action.terminal.copyLastCommandOutput`. I bound it to a unique keyboard shortcut in the Keyboard Shortcut settings. 

This action enables a user to run a command, then trigger the action using a keyboard shortcut to copy the output of the command to the clipboard. It works wonderfully locally, but does not work over through the Remote Explorer SSH tunnel for some reason. 

Version Info: 
OS Version: Mac OS 12.6 
VS Code Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:06.752Z (1 wk ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

If I need to file this issue using a formal bug report template let me know, I just thought it would be easier to follow using a blank template.

**Comment by 0x303** [comment]
More research into this:

I actually discovered that you CAN perform copy command output through the remote explorer, but there is a catch.
The current shell you are in MUST be either`$SHLVL` equal to `1` or `2`. Any greater (`$SHLVL` of `3` for example) and you will be unable to utilize the copy command output feature. 

You can tell whether or not the copy last command feature will work (even before running `echo $SHLVL`) based on whether or not you have the small BLUE CIRCLE that will appear on before each command, in the left edge border of your terminal, after a command is executed.

I am not sure if this is a bug or intended behavior. If this is a bug then it may be more of a VScode problem, than a VScode-Remote problem.

**Comment by 0x303** [comment]
I closed this issue by accident, but then I reopened it. Sorry about that.

**Comment by Tyriar** [comment]
It sounds like this is working as designed. The feature is powered by shell integration which may or may not work automatically for sub-shells (`$SHLVL > 1`). If you want it to work reliably for sub-shells you will want to install shell integration manually, see https://code.visualstudio.com/docs/terminal/shell-integration#_installation
