### ISSUE TITLE
remote ssh stuck after wifi dissconnected and can not reconnect

### ISSUE THREAD

**Issue by myrfy001** [microsoft/vscode-remote-release#819]
- VSCode Version: 1.35.1
- Local OS Version: OSX 
- Remote OS Version:  Centos 7
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.Disconnect wifi for a whole night and connect wifi next morning
2.

![image](https://user-images.githubusercontent.com/11474381/60146761-5fb92500-97fd-11e9-9383-6d7011912987.png)

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Reconnection only works for 3 hours. After that you should see a dialog prompting you to reload the window. Did you see that?
