### ISSUE TITLE
CTRL + Clicking on relative paths open with backlashed paths instead of forward slash

### ISSUE THREAD

**Issue by paul-vd** [microsoft/vscode-remote-release#8192]
### Reproduction
1. Create a folder in you wsl system for example `/home/{YOUR USER}/reproduction`
2. add the following two files, `./tsconfig.b.json`
	```json
	{
	  "foo": "bar"
	}
	```
	and  `./tsconfig.a.json`
	```json
	{
	  "extends": "./tsconfig.b.json"
	}
	```
3. When you <kbd>CTRL</kbd> + <kbd>click</kbd> on the extends from `tsconfig.a.json` it should open up the relative path, so for example if you have opened the project with the remote WSL, it should open the path as `/home/{USERNAME}/reproduction/tsconfig.b.json` but instead it opens the path as `\home\{USERNAME}\reproduction\tsconfig.b.json` which is on your local system and not in the WSL, ofcourse this results in the file not existing
![image](https://user-images.githubusercontent.com/39598117/224979297-1241ff8d-2da5-42f9-9e3d-966215b0b33f.png)

> **NOTE:** I disabled all my extensions and only enabled the WSL/Remote extensions and the issue still persists.

**Comment by aeschli** [comment]
This works for me.
![image](https://user-images.githubusercontent.com/6461412/227493187-223d40cf-d7b0-4cc2-b5d6-afb061609bd0.png)

Please make sure you are in a Remote WSL window (as seen in the remote indicator)
![image](https://user-images.githubusercontent.com/6461412/227493658-24586190-8bbd-474a-a454-8563ed8fdbbf.png)
