### ISSUE TITLE
Remote-SSH through gateway doesn't work

### ISSUE THREAD

**Issue by SuperV1234** [microsoft/vscode-remote-release#82]
VSCode version: 1.34-0 (user setup)
OS: Windows 10 x64

---

At my company, we need to access SSH machines through a gateway like this:

```bash
ssh -l my_username -t -X -p22 -t companygateway.com inline my_hostname
```

I created this `config` for VSCode:

```
Host companygateway
        Hostname companygateway.com
        RequestTTY force
        Port 22
        User my_username

Host my_hostname
        Hostname companygateway.com
        RemoteCommand inline %n
        Port 22
        RequestTTY force
        ForwardX11 yes
```

I then selected *"Remote-SSH: Connect to Host"*, and passed `my_username@my_hostname`. The connection began and a popup with *"Confirming that `my_username@my_hostname` is reachable..."* appeared.

Nothing happens at all. If I open the *"Terminal"* tab, I can see a `uname` process, where I am being asked for my SSH password:

>      Password: 

After I insert my password, I can see `uname -sm` being immediately printed out, then I connect to my remote host, and some company-specific initialisation starts (loading some host-shared configs and my bash/zsh plugins).

Then nothing happens. The final terminal looks like this:

> ```
> ...some initialisation output...
> ...some initialisation output...
> o> uname -sm
> ```

where `o>` is my PS1. However the `uname -sm` command never seems to be executed, and *"Confirming that `my_username@my_hostname` is reachable..."* never disappears. 

I cannot write anything in the remote host terminal nor use any of the extension features.

**Comment by roblourens** [comment]
If you have to enter a password to connect, you will have to enable `remote.SSH.showLoginTerminal`. See https://code.visualstudio.com/docs/remote/troubleshooting#_enabling-alternate-ssh-authentication-methods for more details.

**Comment by ntextreme3** [comment]
even with `remote.SSH.showLoginTerminal`, after putting in a password I get the uname error.  (Removed some info from below)

```
Picking SSH host
Selected <host>
Confirming that <host> is a valid reachable host
Running type "C:\...\vscode-linux-multi-line-command-<host>.sh" | ssh  <host> to confirm the host platform
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> Password:
> 
> 
> Host:ERROR: Access to uname -sm not allowed
> Host:
> Bye
> 
"uname" terminal command done
<host>: unreachable or not Linux x86_64. (Bye)
```

**Comment by ntextreme3** [comment]
fyi, I tried changing the extension to bypass that check, and then it fails with a bunch of access errors:

```
Using commit id "daf71423252a707b8e396e8afa8102b717f8213b" and quality "insider" for server
Install and start server if needed
...
> Host:Host:ERROR: Access to INSTALL_SCRIPT=`mktemp -d`/vscode-remote-install.daf71423252a707b8e396e8afa8102b717f8213b.sh not allowed
> Host:ERROR: Access to cat << 'EOF' > $INSTALL_SCRIPT not allowed
...
# and another couple pages of access errors
```

**Comment by roblourens** [comment]
`Host:ERROR: Access to uname -sm not allowed` Not sure what this means. Which OS is the remote running? Which shell does it use?

**Comment by ntextreme3** [comment]
I also tried change the command to just 'echo' the version it was expecting 😂 but looks like not even that will run. Not sure which OS the gateway is running (or really much how that works at all) Could probably find out tomorrow.

**Comment by SuperV1234** [comment]
Even with `remote.SSH.showLoginTerminal = true`, after inserting the password it gets stuck. This is what I see:

> ```
> Password:
> Your password expires in XX days.  Please change it as soon as possible.
> 
> Press Enter to Continue.
> GetConsoleMode on STD_INPUT_HANDLE failed with 6
> 
> Last login: XXXX
> Kickstarted on XXXX-XX-XX
> uname -sm?[?1034hHost:uname -sm
> ```

**Comment by MyPasswordIsHello** [comment]
I'm also seeing this... Exact same situation as OP and have remote.SSH.showLoginTerminal = true

`GetConsoleMode on STD_INPUT_HANDLE failed with 6

Last login: Tue May 28 13:12:12 2019 from XXX-MYLOCALHOSTNAME-XXX
uname -sm?]0;sshusername@sshhost:~?[?1034h[sshusername@sshhost~]$ uname -sm`

**Comment by roblourens** [comment]
Lots has changed here. Please open a new issue if there are still problems.
