### ISSUE TITLE
Where is the documentation for #72?

### ISSUE THREAD

**Issue by ffMathy** [microsoft/vscode-remote-release#8205]
The fix that was applied here in this issue: https://github.com/microsoft/vscode-remote-release/issues/72

Where is the documentation for that? It would be nice to link it in the future, so we can figure out how to make it work. I am currently having the exact same problem on the latest version.

**Comment by chrmarti** [comment]
Please see https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials#_sharing-gpg-keys.
