### ISSUE TITLE
Certificate expired error when using Remote-Containers

### ISSUE THREAD

**Issue by dmaasland** [microsoft/vscode-remote-release#8207]
Type: <b>Bug</b>

The exact issue as described here: https://github.com/microsoft/vscode/issues/136787

The same workaround applies as well (disable system certificates)

Extension version: 0.24.0
VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:09.831Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 2|
|Memory (System)|64.00GB (31.16GB free)|
|Process Argv|--crash-reporter-id b5d4c7d9-c5c3-4d0f-a8cd-fbb2079da76a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30672705
vsccsb:30677849
pythonb192:30669360
funwalk2:30682974
pythonms35:30686772

```

</details>

**Comment by dmaasland** [comment]
Hmm, not that I can find. I've checked both the user and system keychains. Also updated all homebrew apps just to be sure but still gives me the same warning. Wish I knew what certificate it's on about :)

**Comment by chrmarti** [comment]
Could you install the Network Proxy Test extension (https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test) and check the output of `F1` > `Network Proxy Test: Show OS Certificates` in VS Code? That lists the certificates VS Code loads as "System Certificates".

(If you cannot install the extension through the Extensions viewlet in VS Code, you can use the `Download Extension` link on the above linked page and then install the downloaded VSIX with `F1` > `Extensions: Install VSIX...`.)

**Comment by dmaasland** [comment]
Here you go:

```
Note: Make sure to replace all sensitive information with dummy values before sharing this output.

VS Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710)
Network Proxy Test 0.0.5
darwin 22.3.0 x64

Certificates loaded from the OS (Keychain Access > Certificates):
- Subject: C=US O=Apple Inc. OU=Apple Worldwide Developer Relations CN=Apple Worldwide Developer Relations Certification Authority
  Validity: Feb  7 21:48:47 2013 GMT - Feb  7 21:48:47 2023 GMT
  Fingerprint: FF:67:97:79:3A:3C:D7:98:DC:5B:2A:BE:F5:6F:73:ED:C9:F8:3A:64
  Issuer: C=US O=Apple Inc. OU=Apple Certification Authority CN=Apple Root CA
- Subject: C=US O=Apple Inc. OU=Apple Certification Authority CN=Apple Root CA
  Validity: Apr 25 21:40:36 2006 GMT - Feb  9 21:40:36 2035 GMT
  Fingerprint: 61:1E:5B:66:2C:59:3A:08:FF:58:D1:4A:E2:24:52:D1:98:DF:6C:60
  Issuer: C=US O=Apple Inc. OU=Apple Certification Authority CN=Apple Root CA
- Subject: CN=Mac OS X Provisioning Profile Signing O=Apple Inc. C=US
  Validity: Jan 28 00:14:43 2016 GMT - Feb  7 21:48:47 2023 GMT
  Fingerprint: 04:49:FC:17:90:3E:06:51:45:D4:61:0E:CC:87:0D:D8:E3:EB:C0:B1
  Issuer: C=US O=Apple Inc. OU=Apple Worldwide Developer Relations CN=Apple Worldwide Developer Relations Certification Authority
  Not a CA
- Subject: C=US O=Let's Encrypt CN=R3
  Validity: Oct  7 19:21:40 2020 GMT - Sep 29 19:21:40 2021 GMT
  Fingerprint: 48:50:4E:97:4C:0D:AC:5B:5C:D4:76:C8:20:22:74:B2:4C:8C:71:72
  Issuer: O=Digital Signature Trust Co. CN=DST Root CA X3
  Key usage: 1.3.6.1.5.5.7.3.1, 1.3.6.1.5.5.7.3.2
- Subject: CN=com.apple.systemdefault O=System Identity
  Subject alt: DNS:com.apple.systemdefault
  Validity: Aug 15 02:28:20 2020 GMT - Aug 10 02:28:20 2040 GMT
  Fingerprint: 1E:6E:0E:5F:9F:5A:AC:B5:42:6F:D3:9A:05:E0:FD:A9:5D:63:39:52
  Issuer: CN=com.apple.systemdefault O=System Identity
  Key usage: 1.2.840.113635.100.4.4
  Not a CA
- Subject: CN=com.apple.kerberos.kdc O=System Identity
  Subject alt: DNS:com.apple.kerberos.kdc
  Validity: Aug 15 02:28:20 2020 GMT - Aug 10 02:28:20 2040 GMT
  Fingerprint: 4A:BC:E3:88:E8:7D:DB:8D:A3:F3:91:2F:04:CD:AD:29:67:20:C6:31
  Issuer: CN=com.apple.kerberos.kdc O=System Identity
  Key usage: 1.3.6.1.5.5.7.3.1, 1.3.6.1.5.2.3.5
  Not a CA

```

**Comment by chrmarti** [comment]
The Let's Encrypt certificate is expired. The issue you link to above mentions Let's Encrypt. Could that be the issue? What are you doing / which server are you connecting to when the error occurs?

You can use `F1` > `Network Proxy Test: Test Connection` to test the connection to the server the error occurs with. This will also show the certificates the server sends.

**Comment by dmaasland** [comment]
That does appear to be the case doesn't it. However, there is no mention of this certificate in my Keychain, even with "Show expired" enabled:

![image](https://user-images.githubusercontent.com/5823830/232722656-efb6d8cb-e4ef-4c5e-b5f4-f0db6e221c0e.png)

Here is the output of the network test:

```
Note: Make sure to replace all sensitive information with dummy values before sharing this output.

VS Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710)
Network Proxy Test 0.0.5
darwin 22.3.0 x64

Settings:
- http.proxy: 
- http.proxyAuthorization: null
- http.proxyStrictSSL: true
- http.proxySupport: override
- http.systemCertificates: false
  - globalValue: false

Environment variables:

Sending GET request to https://containers.dev...
vscode-proxy-agent: DIRECT
Received response:
- Status: 200 OK
Certificate chain:
- Subject: containers.dev
  Subject alt: DNS:containers.dev, DNS:www.containers.dev
  Validity: Mar 22 19:22:30 2023 GMT - Jun 20 19:22:29 2023 GMT
  Fingerprint: 0E:5A:A1:2D:65:17:D1:3E:CB:61:8C:59:8D:C1:46:E7:51:04:18:58
- Subject: R3 (Let's Encrypt)
  Validity: Sep  4 00:00:00 2020 GMT - Sep 15 16:00:00 2025 GMT
  Fingerprint: A0:53:37:5B:FE:84:E8:B7:48:78:2C:7C:EE:15:82:7A:6A:F5:A4:05
- Subject: ISRG Root X1 (Internet Security Research Group)
  Validity: Jan 20 19:14:03 2021 GMT - Sep 30 18:14:03 2024 GMT
  Fingerprint: 93:3C:6D:DE:E9:5C:9C:41:A4:0F:9F:50:49:3D:82:BE:03:AD:87:BF
- Subject: DST Root CA X3 (Digital Signature Trust Co.)
  Validity: Sep 30 21:12:19 2000 GMT - Sep 30 14:01:15 2021 GMT
  Fingerprint: DA:C9:02:4F:54:D8:F6:DF:94:93:5F:B1:73:26:38:CA:6A:D7:7C:13
  Self-signed
```

Where else would this certificate be on my system?

**Comment by dmaasland** [comment]
Nevermind, it was in the "Login" keychain for some reason. Deleted it there and now eveything works. Thanks for the help!
