### ISSUE TITLE
Terminal locked after microsoft/vscode#176512

### ISSUE THREAD

**Issue by bvv400** [microsoft/vscode-remote-release#8208]
Type: <b>Bug</b>

After deleting vscode-server in user home directory and starting VSC a fresh vscode-server is installed.  Issue microsoft/vscode#176512 is solved but new issue is introduced.  Install Terminal is not completing the task and log several warnings.  ( see log file. ) 

Extension version: 0.98.0
VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Remote OS version: Linux x64 3.10.0-1160.21.1.vz7.174.13

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.92GB (0.92GB free)|
|Process Argv|--crash-reporter-id f283230e-45b2-4f02-ab75-379a9c328c4f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: motivmatch.com|
|OS|Linux x64 3.10.0-1160.21.1.vz7.174.13|
|CPUs|AMD EPYC 7453 28-Core Processor (2 x 1999)|
|Memory (System)|4.00GB (3.38GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30672705
vsccsb:30677849
pythonb192:30669360
funwalk2:30682974
pythonms35:30686772

```

</details>

[5e805b79fcb6ba4c2d23712967df89a089da575b.log](https://github.com/microsoft/vscode-remote-release/files/10982181/5e805b79fcb6ba4c2d23712967df89a089da575b.log)

**Comment by eleanorjboyd** [comment]
I think this is fixed now with https://github.com/microsoft/vscode/pull/176512. Closing in favor of [this issue](https://github.com/microsoft/vscode-remote-release/issues/8149) so please post any ongoing errors there. Thanks!

**Comment by eleanorjboyd** [comment]
oops sorry! Reopened the issue and assigned to @sbatten who knows this area better. Thanks

**Comment by sbatten** [comment]
@bvv400 the issue you link is not shipped yet in the stable release afaict. can you try with the latest insiders?

**Comment by bvv400** [comment]
Tried with the latest insiders.  Same result, shell with install will not end.   Logging on the server and output on the terminal.

[b9226e1ccc11625bcb42b55efb795e07ee533bb0.log](https://github.com/microsoft/vscode-remote-release/files/11081023/b9226e1ccc11625bcb42b55efb795e07ee533bb0.log)

[terminal output.txt](https://github.com/microsoft/vscode-remote-release/files/11081058/terminal.output.txt)

**Comment by bvv400** [comment]
@sbatten 
Additional information.  The install/start code-server job bin/sh will produce additional logging after connections are made.

[output.txt](https://github.com/microsoft/vscode-remote-release/files/11122277/output.txt)
