### ISSUE TITLE
Can't load VSIX

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#821]
While testing https://github.com/microsoft/vscode/issues/76028.

I created an extension and packaged the vsix. After installing the vsix, I get notified that the extension was installed and the extension viewlet presents it self as:

![image](https://user-images.githubusercontent.com/4674940/60158204-f3d0bf80-97f0-11e9-8213-3d8331ae4252.png)

After reloading the same picture. The extension never gets activated. The same vsix works without issues in the local case.

Complete code available in https://github.com/kieferrm/vscode-remote-release-issues-821.

**Comment by sandy081** [comment]
I cannot reproduce it. May I know if you have configured this extension as UI extension in settings? If so in which settings did you configure?

**Comment by Akryllax** [comment]
Had some similar troubles while developing my extension. VSCode RD doesn't throw really useful logs at the moment if an extension installation fails.

In my case, I was developing an extension for Language and UI, but for some reason VSCode was trying to install it as a server-side extension. Forcing it to install as a local extension in the `package.json` fixed my issue.

**Comment by kieferrm** [comment]
No setting was specified.

**Comment by kieferrm** [comment]
@sandy081, I retried the same vsix file with the latest insider and now can't reproduce the issue any more.

> 1.36.0-insider
> b7265738444f1eee05762341b4361ee6452a4154
> x64
