### ISSUE TITLE
Git Credential Helper not copying into the remote dev container gitconfig 

### ISSUE THREAD

**Issue by YingyHuang** [microsoft/vscode-remote-release#8215]
When first connecting to a remote dev container, I notice the git credential helper is not being copied from my one of my devices to remote dev container's gitconfig file. But it is showing correctly if I connect to a remote dev container from another device. Could you help to see if there is anything missing on my device?

**I'm seeing**:

In the `Dev containers` output, no output message related to setting up git credential. helper.

In the `~/.gitconfig` file in remote container, there is no content for credential helper
```
[credential]
	helper = 
```

-------------------------

**I should see**:

The `credential.helper` correctly configured in the `Dev containers` output, 
```
[19623 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --system --replace-all credential.helper '!f() { /root/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/node /tmp/vscode-remote-containers-932f5356-744f-429b-9807-421ac6634fad.js git-credential-helper $*; }; f' || true
```
In the `~/.gitconfig` file in remote container, helper content correctly setup:
```
[credential]
	helper = "!f() { /root/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/node /tmp/vscode-remote-containers-f66fcb93-ba9c-4096-9f28-9a6bb70aefb6.js git-credential-helper $*; }; f"
```

--------

Issue is that the `/root/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/node /tmp/vscode-remote-containers-f66fcb93-ba9c-4096-9f28-9a6bb70aefb6.js git-credential-helper` setting is missing.

**Comment by chrmarti** [comment]
Could you append the full log from when this doesn't work? (`F1` > `Dev Containers: Show Container Log`)

**Comment by YingyHuang** [comment]
Hi chrmarti,
yes, here's the full log
[Dev Containers.log](https://github.com/microsoft/vscode-remote-release/files/11031887/Dev.Containers.log)

**Comment by YingyHuang** [comment]
Thank you @chrmarti, this is the setting I'm missing. Setting this value as `global` fix the issue.
