### ISSUE TITLE
[Remote-SSH Bug]: Connecting to Raspberry Pi 4 with 32 bit OS installed

### ISSUE THREAD

**Issue by jsolderitsch** [microsoft/vscode-remote-release#8216]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

I expect that the remote server will start and connect to the local Visual Studio program running

### Steps To Reproduce

Using VSC on a Mac. Latest release version 1.76.2. Using 0.98 version of remote-ssh. Installed normally.

The ssh destination is a Pi 4 running Raspberry Pi OS 32 bit. Latest version with apt update and apt upgrade applied.

Connection fails with a resolver error and if I look closely at the log there is a message that the server has not started successfully because the file ```node``` can't be found. But If i look on the Pi, there is a file by that name present.

[https://qubitsandbytes.co.uk/fixing-vs-code-remote-node-not-found-error/](https://qubitsandbytes.co.uk/fixing-vs-code-remote-node-not-found-error/)

says something about VSC expecting I was running a 32 bit program on a 64 bit OS. But the remedy at the link did not seem applicable to me.

BUT, the url suggested to me that maybe VSC server is NOW expecting that a Pi 4 is running the 64 bit Raspberry Pi OS. So I prepared a new install of Raspberry Pi OS 64 bit on the Pi 4 I was using.

I again did an apt update and upgrade and then tried remote-ssh again. 

Now it works.

Nothing I read in advance suggested this expected install behavior failure. At the very least documentation needs to be updated about OS expectations for the Pi ecosystem. At the very least documentation needs to be tweaked to warn of Pi architecture and Pi OS level expectations.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
Log no longer available after Pi OS change

</p>
</details>


### Anything else?

_No response_

**Comment by eleanorjboyd** [comment]
Hello! Thank you for all your investigation into this! To clarify are you able to connect correctly and that issue is resolved? Secondly, what are you describing as your fix and how it differs from the docs? Did you update your raspberry pi to the 64 bit and this makes it work but the docs do not mention this? Thanks!

**Comment by jsolderitsch** [comment]
If I change the Raspberry Pi OS to be 64 bit (new SD card prepared) then remote-ssh works.

I could not use remote-ssh with the 32-bit OS installed. It doesn't work.

I did not see any docs that prescribe that you need to worry about the OS (32-bit vs. 64 bit). I did NOT try to connect to a Pi 3 with the 32 bit OS installed there. Maybe that works. Don't know.

**Comment by eleanorjboyd** [comment]
Understood- could you give your exact raspberry pi version that it didn't work on and I can look into changing our docs? Thanks

**Comment by eleanorjboyd** [comment]
Hi! Closing in favorite of https://github.com/microsoft/vscode-remote-release/issues/8264, we will continue the conversation there. Thanks!
