### ISSUE TITLE
[VSCode Server] Create a systemd service on Linux installs

### ISSUE THREAD

**Issue by calebevans** [microsoft/vscode-remote-release#8218]
Please create a systemd service for VSCode Server installs on Linux. It would be nice for users to be able to enable/start/stop/restart the service easily.

I was able to create one easily because I wanted the server to come up after a system reboot without me running an additional command. If it is decided that one shouldn't be created by the install script, it may be worth adding that option to the documentation for others who might desire the functionality.

**Comment by cglong** [comment]
I'd be interested in seeing a similar feature for Windows services as well! (And maybe launchd for macOS for completeness?)
