### ISSUE TITLE
[Remote-SSH Bug]: file://path/to/file Links Do Not Work with Remote - SSH

### ISSUE THREAD

**Issue by seamusm02** [microsoft/vscode-remote-release#8219]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Open remote file when using ssh @file:///path/to/file

### Steps To Reproduce

![file-link-not-working](https://user-images.githubusercontent.com/59479271/226260146-b7e6da40-fa23-469d-a6b4-d4a9dc2824f0.gif)

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by hediet** [comment]
This is not a link detection issue. The `@` is skipped. I think the file being opened is just not the file in the workspace.

**Comment by bpasero** [comment]
🤷, then maybe close as designed if the code editor does no link validation.

**Comment by seamusm02** [comment]
I did some testing on Windows (local / remote - ssh) and Linux (local / remote - ssh) 

1.  The "@" prefix was simply an extension feature that colorized the text, so this is not relevant.  However, file://path/to/file only works locally on Linux and Mac.  It doesn't not work with remote - ssh on Linux , Windows, (and probably Mac).  It also doesn't not work on Windows locally.

2. Linux local file links WORK

![linux-local-works](https://user-images.githubusercontent.com/59479271/226791888-ea0effa6-0568-44ce-8bc6-39a76e34f67e.gif)

3. Linux remote -ssh file links do NOT work

![linux-remote-ssh-does-not-work](https://user-images.githubusercontent.com/59479271/226792106-c46f6652-b531-4c2b-a864-2e85e9d8799e.gif)

4. Windows local and remote file links do NOT work (showing local only below)

![windows-does-not-work](https://user-images.githubusercontent.com/59479271/226792266-588daae4-f5e0-4a85-ba0d-375e2b7d98ec.gif)

**Comment by hediet** [comment]
This works for me:
> file:///C:/dev/temp/empty/file1.txt

I think the other issues are not bugs, but it works as designed.

**Comment by seamusm02** [comment]
I made a mistake with respect to Windows local: `file:///C:/path/to/file` does work as you pointed out above.  I was missing the 3rd `/` before the drive letter and not converting `\` to `/`.  However, `file:///C:/path/to/file` does NOT work in the Remote - SSH extension on Windows.  `file://path/to/file` also does NOT work in the Remote - SSH extension on Linux either.  That's what this issue is about.
