### ISSUE TITLE
Test: Remove dependance on built-in repository configs

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#8224]
Refs: https://github.com/microsoft/vscode-remote-release/issues/7532

- [x] anyOS @DonJayamanne
- [x] anyOS @hediet

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%238224%0A%0A&assignees=chrmarti)

---

Use Dev Containers 0.286.0-pre-release or later.

Randomly checkout one or two of the below repositories that previously had a dev container config built-in and check that when you reopen its folder in a container you are asked for the dev container template to use and that the dev container opened is indeed built from that template:
- https://github.com/aymericdamien/TensorFlow-Examples
- https://github.com/barryclark/jekyll-now
- https://github.com/django/django
- https://github.com/microsoft/vscode-azure-account
- https://github.com/python/cpython
- https://github.com/spmallick/learnopencv
- https://github.com/tensorflow/addons
- https://github.com/tensorflow/tensorflow
- https://github.com/terraform-providers/terraform-provider-azurerm

**Comment by DonJayamanne** [comment]
@chrmarti @hediet I'm sorry, but I'm not sure what I'm supposed to do here
The instructions aren't very clear to me

Do i need to clone one of the above repors and then attempt to open in a dev container and then verify that I am presented with the option to select a template?
Right now thats what happens, but the list is just a generic `Add Dev Container Configuration Files` list

**Comment by DonJayamanne** [comment]
Works as expected, thanks for the clarification @bamurtaugh
