### ISSUE TITLE
Test: Improve management of Dev Containers

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#8225]
Refs: https://github.com/microsoft/vscode-remote-release/issues/7720

- [x] anyOS @paulacamargo25
- [x] anyOS @rzhao271

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%238225%0A%0A&assignees=chrmarti)

---

Use Dev Containers 0.286.0-pre-release or later.

- Create a few dev containers with the commands:
  - `Dev Containers: Reopen in Container`
  - `Dev Containers: Clone Repository in Container Volume`
  - `Dev Containers: New Dev Container...`
- Use `Dev Containers: Clean Up Dev Containers` to clean up the dev containers.
  - Verify that all stopped dev containers are offered for removal (that does not include non-dev containers).
  - Verify that any volumes that are no longer used are offered for removal.
- Use `Dev Containers: Clean Up Dev Volumes` to clean up the dev volumes.
  - Verify that all unused dev volumes are offered for removal (that does not include non-dev volumes).

**Comment by paulacamargo25** [comment]
I tested on Mac, the Clean Up Dev Containers command works perfect, but I couldn't test the other one because I get a not found error.
