### ISSUE TITLE
Test: Remote tunnels: Open desktop from vscode.dev 

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#8226]
Refs: https://github.com/microsoft/vscode-remote-release/issues/8199

- [x] macOS @sbatten 
- [x] linux @andreamah 
- [x] windows @bamurtaugh  

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%238226%0A%0A&assignees=aeschli)

---

- start a remote tunnel on a machine: 
   - Open VS Code Desktop (insiders), run `Turn on Remote Tunnel Access..` from the Account menu
   -  In the popup that appears, copy the insiders.vscode.dev link and open that link in the browser
   - If you missed the popup, you can get the link by  running the command `Remote Tunnels: Copy Browser URI to Clipboard`
- in a browser, open a tunnel
   - use the link from before
   - alternatively open https://insiders.vscode.dev/, install the Remote Tunnels extension, run `Connect to Tunnel...` 
- test that this opens a remote folder
   - if you get the error `Workspace does not exists` this is probably [issue 8212](https://github.com/microsoft/vscode-remote-release/issues/8212). Make sure the path ends with a `/`
   - test that the remote indicator shows the name of the tunnel 
   - test that the file explorer showing the remote content
- in the remote menu you should find the command `Continue With Tunnel on VS Code Desktop`
  - test that the command works
  - test that command is also in the command palette

**Comment by sbatten** [comment]
I know https://github.com/microsoft/vscode-remote-release/issues/8212 is already filed, but when I click the "Open workspace..." button in the dialog, it seems I can only open a workspace file, but shouldn't I be able to select a folder in that flow too?

**Comment by sbatten** [comment]
Is there already a tracking issue for not being able to browse tunnels in the remote explorer on browser?

**Comment by bamurtaugh** [comment]
> Is there already a tracking issue for not being able to browse tunnels in the remote explorer on browser?

I filed an issue in case there isn't: https://github.com/microsoft/vscode-remote-release/issues/8233.
