### ISSUE TITLE
Can't create container without internet access

### ISSUE THREAD

**Issue by myrfy001** [microsoft/vscode-remote-release#8229]
Type: <b>Performance Issue</b>

I'm working on an private remote machine where the internet access is very poor. When creating new dev containers, it has to fetch data from https://dl-cdn.alpinelinux.org/, which blocks the whole process.

Extension version: 0.282.0
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes
Connection to 'dev-container+7b22766f6c756d654e616d65223a22646174656e6c6f7264222c22666f6c646572223a22646174656e6c6f7264222c2273657474696e6773223a7b22686f7374223a227373683a2f2f616c6979756e2d646576227d7d' could not be established

**Comment by chrmarti** [comment]
What needs to be fetched mainly depends on your devcontainer.json. For Alpine we additionally install `libstdc++` if it is not installed already.

Does using a simple devcontainer.json make it faster? E.g.:
```json
{
	"image": "mcr.microsoft.com/devcontainers/base:alpine-3.17"
}
```
