### ISSUE TITLE
terminal.integrated.inheritEnv not working on remote

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#823]
While testing https://github.com/microsoft/vscode/issues/76053. 

1) open remote ssh workspace
2) set `terminal.integrated.inheritEnv` to `true`
3) destroy all existing terminals and create a new one
4) `env > inherit.txt`
5) set `terminal.integrated.inheritEnv` to `false`
6) destroy all existing terminals and create a new one
7) `env > clean.txt`
8) compare `clean.txt` and `inherit.txt`
-> no differences
In my case `SHLVL=4` in both and shouldn't.

**Comment by Tyriar** [comment]
The setting doesn't actually do anything on remote just yet as I didn't think through it fully. I'll have a look to see if doing the same thing will work across each of the extensions.

**Comment by Tyriar** [comment]
Ok, this should work on remote now, SLLVL=3 for me which I think is fine since ssh is a shell. The main thing to look out for in remote is that your bashrc only runs once (and doesn't duplicate in the PATH environment).
