### ISSUE TITLE
Testing tunneling: No tunnels in Remote Explorer

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#8233]
Testing #8226

When I'm brought to insiders.vscode.dev, I expected to see my current tunnel and any others in the Remote Explorer:

![image](https://user-images.githubusercontent.com/25310137/226682143-5b44d2c3-1642-406c-89a7-f1343ed9f157.png)

**Comment by aeschli** [comment]
I can reproduce when opening a URL with a tunnel: e.g. `https://insiders.vscode.dev/tunnel/martin-pc`
(It works when opening https://insiders.vscode.dev)
