### ISSUE TITLE
Testing tunneling: Wording in connection toast

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#8235]
Testing #8226

I understand the content in the toast we show when tunneling access is enabled, but I wonder about users less familiar with tunneling and remote terminology:

![image](https://user-images.githubusercontent.com/25310137/226683806-2a3439d2-4718-431d-b695-67c8c1e67526.png)

What about something like:

`You can now access this machine (_host name here_) anywhere via a secure tunnel. To connect via a different machine, use the generated insiders.vscode.dev link, or use the _Remote - Tunnels_ (link to https://code.visualstudio.com/docs/remote/tunnels) extension in the desktop or web. You can _configure_ or _turn off_ this access via the VS Code Account menu.`

**Comment by aeschli** [comment]
After iterating on it with @connor4312, I ended up on:

![image](https://user-images.githubusercontent.com/6461412/227055394-78e9cf39-e7ba-4bd9-8898-bac1a4b1f57b.png)
