### ISSUE TITLE
Command 'Dev Containers: Clean Up Dev Volumes...' not found

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode-remote-release#8239]
Testing #8225

When i tried to  run the command 'Dev Containers: Clean Up Dev Volumes...'  i get an error.

<img width="1029" alt="Screenshot 2023-03-21 at 11 02 39 AM" src="https://user-images.githubusercontent.com/17892325/226701853-42607cb7-d9ee-4490-975f-87259d4374ca.png">

I am using version v0.286.0 Prerelease.

**Comment by eleanorjboyd** [comment]
What steps are needed to repro this? Saw the same error but I think the fix just might not be on insiders yet due to the merge timestamp.

**Comment by chrmarti** [comment]
I saw it when the Remote-Explorer wasn't shown and I triggered the command from the command palette. The fix is in Dev Containers 0.287.0-pre-release.
