### ISSUE TITLE
[Feature] Allow to suppress message about using different port because port has been used

### ISSUE THREAD

**Issue by rrmistry** [microsoft/vscode-remote-release#8245]
My workflow involves running a continuous `dotnet watch` run which restarts my web server from time to time.

During development, I keep persistently getting this popup message:
![image](https://user-images.githubusercontent.com/25514145/227038992-ba82e21d-8e45-44cd-95a0-cfbe95370116.png)

And there seems to be no way to suppress this.

Whenever `dotnet` decides to restart the server, this popup shows up as it detects the web server, and this breaks the focused flow.

I am using a multi-container docker-compose setup with `NGINX` as the ingress into the docker network and route traffic to my web server running inside the dev container.

The NGINX HTTP proxy will route traffic internally from a different source port, however, I would still like to reserve the option to open the web app directly from the web browser, hence I need to set up port forwarding with `5043:5043`.

I have tried changing the local port to another port temporarily and rebuilding the dev container, but this issue reoccurs for the new port number.

It would be great to suppress this message with a VS Code setting.

**Comment by alexr00** [comment]
@rrmistry If you have a devconatiner.json file you can set up 5043 to be forwarded to 5043 when you connect to the container.

**Comment by rrmistry** [comment]
Finally figured out the issue.

The problem was with this statement, which sometimes is unreliable at checking the local host port
(even if the port is blocked by the same docker process)

```jsonc
// .devcontainer/devcontainer.json
{
    // ...
        // Use 'forwardPorts' to make a list of ports inside the container available locally.
    "forwardPorts": [
        "5043:5043"
    ],
    "portsAttributes": {
        "5043": {
            "protocol": "http",
            "requireLocalPort": false // 👈👈👈
        }
    },
    // ...
}
```

Closing now.
