### ISSUE TITLE
Can't Open a new Workspace When Attach a Running Container

### ISSUE THREAD

**Issue by AuSjukwa** [microsoft/vscode-remote-release#8246]
Steps:
1. Start a devcontainer
2. Attach to Running Container(named container1), it can open a new Workspace
3. Attach to Running Container(named container1) again, it switch to the workspace from second step. Cant't open a new workspace in the same Running Container!!

**Comment by chrmarti** [comment]
As a workaround you could remove the `"workspaceFolder"` from the config we use before attaching for the second time. (`F1` > `Dev Containers: Open Attached Container Configuration File...`)

**Comment by AuSjukwa** [comment]
> As a workaround you could remove the `"workspaceFolder"` from the config we use before attaching for the second time. (`F1` > `Dev Containers: Open Attached Container Configuration File...`)

It works, thanks.
