### ISSUE TITLE
Unexpected Umask Behaviour [Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by bhavyavm** [microsoft/vscode-remote-release#8247]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Both the connections ,ie through **VSCode ssh extension** and **SSH thorough the terminal** should give the same umask value for a shell in the remote host.

### Steps To Reproduce

1. From the terminal create SSH connection to a host. (ssh hostname)
2. Open the bin/sh shell
3. check the umask value.
4. Do the same using remote ssh connection through VSCode and open the same shell.
5. Check the umask value in the vscode bin/sh terminal.
![Screenshot 2023-03-23 at 3 17 35 PM](https://user-images.githubusercontent.com/57523254/227168813-e8c274b3-7737-4df2-8a67-38817aaf4de1.png)

<img width="498" alt="Screenshot 2023-03-23 at 3 12 27 PM" src="https://user-images.githubusercontent.com/57523254/227168904-1b1047a1-9af8-4532-801e-26723e750178.png">

![Screenshot 2023-03-23 at 3 19 17 PM](https://user-images.githubusercontent.com/57523254/227169842-57af79b8-33ae-4838-8720-68984e9c5a32.png)
The Umask values are different in same shell open through vscode SSH and normal SSH  connection. 

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```


```

</p>
</details>

**Comment by bhavyavm** [comment]
> can you confirm on both connections that the user it is logged in as are the same?

Yes I am using same ADS connection

**Comment by roblourens** [comment]
We have https://github.com/microsoft/vscode-remote-release/issues/4442 to investigate this, although you can help by providing some more details- we are not manipulating the umask value, if it is not the default then it has been set by something in your system configuration, for example, a bashrc file.

Can you tell us what you expect it to be and how it gets set on your system?

**Comment by bhavyavm** [comment]
We are not using any profile or bashrc to change the default umask behaviour. By default i am getting the umask values as mentioned in the images above. The issue that we are facing is only with the "bin/sh" shell, it behaves differently for normal-ssh connection and vscode terminal.
