### ISSUE TITLE
Dev container: Reopen in Container result in an error on Windows

### ISSUE THREAD

**Issue by Giangblackk** [microsoft/vscode-remote-release#8248]
![image](https://user-images.githubusercontent.com/10430725/227160812-524f736a-d4b5-44d4-ba3a-4755a442abc3.png)

Does this occur consistently? 
Repro steps:

1. Open a folder in VScode
2. Run command "Dev Container: Reopen in Container".

Version: 1.24.0
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

**Comment by chrmarti** [comment]
Please append the full Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)

**Comment by Giangblackk** [comment]
Here is all Dev Containers log from when it happens.
```log
[4116 ms] Dev Containers 0.282.0 in VS Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884).
[4116 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[4419 ms] 1.41
[4769 ms] No dev container config found. No repository connection string found.
```

**Comment by chrmarti** [comment]
Could you install this extension I recently published to diagnose problems like this: https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test. Then use `F1` > `Network Proxy Test: Test Network Connection` with `https://containers.dev/static/devcontainer-index.json` as the URL to check if that works. If it shows the certificate error retry with `F1` > `Network Proxy Test: Test Network Connection (Allow Unauthorized)` to get more information about the problem.

Make sure replace any sensitive information before posting it here. Thanks.
