### ISSUE TITLE
Surface WSL in the Remote picker

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode-remote-release#8251]
Related: https://github.com/microsoft/vscode/issues/173396
WSL extension requires additional contexts before enable this for the remote picker. 
The current experience for creating new connection for WSL without the necessary dependencies is a mix of user interactions inside and out of vscode which can break a new user's flow (WSL needs a distro install and redirects users via notifications to the distro downloads page.). There is an opportunity here to clean up the WSL getting started experience.

**Comment by bamurtaugh** [comment]
I agree- adding it and then continuing to refine it over time makes sense to me too. It's a great way to continuing broadening the awareness of WSL.

**Comment by bhavyaus** [comment]
Sounds good. I'll have this our next week to enable in insiders after end-game.

**Comment by aeschli** [comment]
The `Add Distro` command now can install a distro

**Comment by aeschli** [comment]
`Connect to WSL` is now in the `Connect to...` quick pick
