### ISSUE TITLE
VSCode dev container didn't include local files

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-remote-release#8262]
- VSCode Version: 1.76.2 (user setup) commit ee2b180d...
- Local OS Version: Windows_NT_ x64 10.0.22621 - really Windows 11 for internal FTEs 
- Remote OS Version: 
- Remote Extension/Connection Type: Containers

- Logs:

Steps to Reproduce:

1. Install Docker desktop for windows - docker engine v20.10.23 - I only mention this b/c it had been removed from the computer and was surprised so I re-installed
2. In new project created from VS Code functions, run "Open in Dev Container"
3. Picked typescript/node container from list
4. VScode reopens with only devcontainer showing. 
5. Thought I must have done something wrong so did it again, same thing. 
6. Next, I just added dec container file from command palette, tweaked it, which looks like

  ```
  // For format details, see https://aka.ms/devcontainer.json. For config options, see the
  // README at: https://github.com/devcontainers/templates/tree/main/src/typescript-node
  {
	  "name": "Node.js & TypeScript",
	  // Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	  "image": "mcr.microsoft.com/devcontainers/typescript-node:0-16",
	  "features": {
		  "ghcr.io/devcontainers/features/node:1": {
			  "version": "16"
		  },
		  "ghcr.io/devcontainers-contrib/features/typescript:2": {
			  "version": "latest"
		  }
	  },
  
	  // Features to add to the dev container. More info: https://containers.dev/features.
	  // "features": {},
  
	  // Use 'forwardPorts' to make a list of ports inside the container available locally.
	  "forwardPorts": [7071],
  
	  // Use 'postCreateCommand' to run commands after the container is created.
	  // "postCreateCommand": "yarn install",
  
	  // Configure tool-specific properties.
	  // "customizations": {},
  
	  // Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	  // "remoteUser": "root"
  }
  
  ```

7. Then reopen in dev container. This time it works. 

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by diberry** [comment]
Reopen in container wasn't a choice. So I thought it had been renamed to the other thing.

**Comment by chrmarti** [comment]
We renamed `Dev Containers: Create Dev Container` to `Dev Containers: New Dev Container`, but that doesn't capture that it has nothing to do with the currently open workspace folder. Maybe something like `Dev Containers: New Empty Dev Container` would clarify this. /cc @bamurtaugh

@diberry It sounds like the command was missing? Did you have a workspace folder open at that time?

**Comment by diberry** [comment]
@chrmarti No, I didn't have a workspace folder open at the time. And now the issue appears to be gone. Bug self-resolved.... I'll close this.
