### ISSUE TITLE
docker remote

### ISSUE THREAD

**Issue by bhack** [microsoft/vscode-remote-release#8266]
I've see in the last months that the docker remote experience started to be a little bit slower. 
An already available remote container now requires on a quite fast connection an avg > `90K ms`

Just the `Start: Run in container: test -e /tmp/.X11-unix/[<n]` sequences of commands occupy 7K. 

Are we really caring about the point that the docker container/context could be remote? (E.g. also to batch commands?).

**Comment by chrmarti** [comment]
Could you append your log from connecting to a remote context? Have you tried connecting with Remote-SSH and then reopening a folder from there, does that have the same performance?

**Comment by chrmarti** [comment]
I would be interested in which commands take a long time. Maybe compare it with the log from earlier versions. Maybe something stands out.

**Comment by bhack** [comment]
I think that is mainly the accumulated over time amount of single `docker cli` command (without batching) we are sending to the remote docker as https://github.com/microsoft/vscode-remote-release/issues/3938 seems to help a bit.

I don't have test visibility here but do you have performance test on a simulated slower connection then just the local one in your CI for this project?

**Comment by chrmarti** [comment]
This might be a bit specific to using a Docker Context with SSH since that reinitiates an SSH connection each time. (This is why #3938 helps.)

When you use Remote-SSH and then open the dev container, we use a single SSH connection. This is the recommended way of connecting to an SSH server.

**Comment by bhack** [comment]
Probably the best solution is  duplicate the `devcontainer.json` to handle a remote and local version. 
This is going to create too much duplication and misalignment (just for few rows) until  we support overlay at https://github.com/microsoft/vscode-remote-release/issues/3279

**Comment by bhack** [comment]
> When you use Remote-SSH and then open the dev container, we use a single SSH connection. This is the recommended way of connecting to an SSH server.

It is not the same as this require to install vscode stuffs in the docker host and not directly in the container. So I think that we could add some perf test in the CI for this specific scenario.
