### ISSUE TITLE
removing balances in all my wallets

### ISSUE THREAD

**Issue by wellhungwguy** [microsoft/vscode-remote-release#8267]
- VSCode Version:
- Local OS Version:
- Remote OS Version:
- Remote Extension/Connection Type: Containers/WSL/Server

- Logs:

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by wellhungwguy** [comment]
how can l rectify this

**Comment by hoang-himself** [comment]
You really are a well hung guy.
