### ISSUE TITLE
Permission Denied While Editing Files on a Romote Device

### ISSUE THREAD

**Issue by mfatih7** [microsoft/vscode-remote-release#8269]
Hello

I am trying to use VS Code and Remote Explorer extension to connect to Virtual Machine on the Google Cloud Platform.
After I connect to the Virtual Machine I try to edit files on the Virtual Machine with VSCode File Explorer.
While saving the file I get the error below.

![image](https://user-images.githubusercontent.com/58260582/227739369-83a5b005-d100-4b71-81e1-e62b328a500a.png)

How can I do all of my operations on the remote device as sudo user?

**Comment by eleanorjboyd** [comment]
If you connect via the terminal to this remote on the same user and then try and edit this file does that work successfully?

**Comment by mfatih7** [comment]
@eleanorjboyd
Thank you for the answer.

If I connect to Virtual Machine via terminal and use Vim to edit files as sudo user I can edit files without any problem.

**Comment by eleanorjboyd** [comment]
Do you think it is the same as this issue here? https://github.com/microsoft/vscode-remote-release/issues/8060

@bpasero any thoughts on the permissions here? Same for issue 8060 we were struggling for a next direction regarding the file permissions not working.

**Comment by bpasero** [comment]
Does the node.js server process run under the same user as the terminal? Because in the end the file will be written to on behalf of the server node.js process. We use `fs.writeFile` and variants for writing in node.js.

**Comment by roblourens** [comment]
@mfatih7 do you use a workflow where you change users when connecting manually to this remote (connect as user1, edit files as user2)? That scenario may not work properly here.

You can check this by opening a terminal in the Remote-SSH window and checking whether you are the same user as when connecting manually. Please also check whether you can edit the file with vim in the Remote-SSH vscode terminal as well.

**Comment by roblourens** [comment]
Thanks for the clear explanation. We don't support this scenario currently. This is tracked in either https://github.com/microsoft/vscode/issues/48659 or https://github.com/microsoft/vscode-remote-release/issues/690
