### ISSUE TITLE
[Remote-SSH Bug]: Connection fails when using tab-separated LocalForward arguments

### ISSUE THREAD

**Issue by lpaolini** [microsoft/vscode-remote-release#8271]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

It should connect.

### Steps To Reproduce

In MacOS Ventura (I suspect it's common to other platform too), use tabs (vs spaces) for separating LocalForward arguments in `.ssh/config`.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
Resolver error: TypeError: Cannot read properties of undefined (reading 'split')
	at j (/Users/<user>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:666772)
	at /Users/<user>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:667401
	at Array.map (<anonymous>)
	at t.localForwardsForHost (/Users/<user>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:667358)
	at async t.resolve (/Users/<user>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:645642)
	at async /Users/<user>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:721750
```

</p>
</details>

**Comment by eleanorjboyd** [comment]
yes that makes sense, marking as bug

**Comment by eleanorjboyd** [comment]
@lpaolini the fix is now on vscode insiders on the pre-release version of the remote-ssh extension. If you want to give it a try and verify please let me know if it works. Thanks!

**Comment by lpaolini** [comment]
@eleanorjboyd I confirm it now handles tabs correctly on pre-release. 
Many thanks for prompt action!

**Comment by eleanorjboyd** [comment]
Great! Thanks!
