### ISSUE TITLE
[Remote-SSH Bug]: Restoring terminal when forwarding sometimes breaks SSH_AUTH_SOCK

### ISSUE THREAD

**Issue by florisvdg** [microsoft/vscode-remote-release#8278]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

VS Code Remote-SSH usually works great with agent forwarding, but I'm noticing that if I reconnect to a timed out workspace or reload the workspace while a terminal is still open, the SSH auth socket sometimes isn't working in the terminal VS Code tries to restore.

If I `exit` and open a new terminal, everything is fine again. That's an easy workaround, so it's not a huge issue. But it does happen pretty often and it's not a great experience.

Ideally, after a reconnect or reload, all restored terminal windows should keep on working as they did before I stepped away.

### Steps To Reproduce

1. Connect to a remote workspace with `ForwardAgent yes`
2. Open a terminal
3. Verify that `SSH_AUTH_SOCK` is set and run `ssh-add -l` and see keys from the local agent presented
4. Wait for a while, but leave the window open
5. Return and reconnect/reload
6. Run `ssh-add -l` again from the restored terminal --> fails with socket error

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

TODO, will add it the next time it happens.

</p>
</details>

**Comment by florisvdg** [comment]
Did some debugging and found another workaround:
```
SSH_AUTH_SOCK=$(ls -td /run/user/1000/* | head -n1) ssh-add -l
```
Which implies that VS Code seems to create a new socket upon reload, but then doesn't update the forwarded `SSH_AUTH_SOCK` when restoring the terminal session.

**Comment by eleanorjboyd** [comment]
Hi! Yeah we are seeing ongoing issues with ssh_auth_sock and forwarding. This is the issue I have been directing people too where we will keep the discussion going. Please reopen if you do not think your issue is related to this one: [https://github.com/microsoft/vscode/issues/177368](https://github.com/microsoft/vscode/issues/177368)

**Comment by florisvdg** [comment]
@eleanorjboyd One thing to consider for this issue is that agent forwarding itself actually works great.

It's the terminal window restoration part that needs to make sure that `SSH_AUTH_SOCK` gets updated with the new socket path.
