### ISSUE TITLE
Support to type port

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-remote-release#828]
* connect to ssh
* you can enter `user@host`

I run my ssh server on a different port than 22 and it would be nice if I can type `user@host:port`

**Comment by roblourens** [comment]
Try `ssh://user@host:port`, see https://github.com/microsoft/vscode-remote-release/issues/515

**Comment by roblourens** [comment]
And if you have any ideas to make it more discoverable since `:` is a valid character in a hostname

**Comment by jrieken** [comment]
> more discoverable since : is a valid character in a hostname

haha - how about using a proper placeholder instead of crapped title, see https://github.com/microsoft/vscode-remote-release/issues/796#issuecomment-506234967
