### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by work-direxfranko** [microsoft/vscode-remote-release#8285]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### ->

remote.SSH.useLocalServer

### Expected Behavior

huboshellx
[route.print.txt](https://github.com/microsoft/vscode-remote-release/files/11083716/route.print.txt)

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

### Anything else?

direxwire
[respose code.txt](https://github.com/microsoft/vscode-remote-release/files/11083723/respose.code.txt)

**Comment by eleanorjboyd** [comment]
Hello! Could you please send your remote-ssh logs? You can find the logs by going to `view` in the menu bar, then selecting `output`, and finally once the bottom window pops up select  `remote-ssh` from the dropdown on the right. Additionally please describe the expected and actual behavior. Thanks
