### ISSUE TITLE
code tunnel on vscode.dev: unable to open workspace

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#8287]
- create a multi root workspace and save it as `test.code-workspace`
- try to open the workspace from vscode.dev via tunnels: 
- `https://insiders.vscode.dev/tunnel/my-office-pc-dev/home/martin/workspaces/testing/test.code-workspace`
Does not load

Nothing interesting in the log

**Comment by connor4312** [comment]
This works for me. Can you take a screenshot of the page in the "does not load" state?

**Comment by aeschli** [comment]
Yes, now it works for me too.
