### ISSUE TITLE
wrong path separators in editor tab for source attachment editor

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#830]
Testing https://github.com/microsoft/vscode-remote-release/issues/754

- in a WSL window
- install `Debugger for Chrome`
- git clone `https://github.com/ahfarmer/calculator.git`
- open folder (in WSL), `yarn`
- create a chrome launch config, set URL and webRoot
```
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:3000",
            "webRoot": "/"
        }
```
- run and set breakpoint in `calculate.js`
- editor opens with breakpoint reached. It uses `\` but should use '/' as we are in WSL

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/60180561-9ce2de80-9820-11e9-91c5-ba02f60ab640.png)

**Comment by aeschli** [comment]
@roblourens Not sure of a better way to get the source mapping working. 
The react sources have urls like 
![image](https://user-images.githubusercontent.com/6461412/60180700-e7fcf180-9820-11e9-9cf5-ee4aea96e0bc.png)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/76117
