### ISSUE TITLE
'Invalid mount config' error when starting Dev Container using Rancher Desktop

### ISSUE THREAD

**Issue by MikeEvansLarah** [microsoft/vscode-remote-release#8306]
- VSCode Version: 1.76.2
- Local OS Version: Windows 11 10.0.22621
- Remote Extension/Connection Type: Containers

- Logs:

```
Start: Starting container
Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=c:\temp\endjin\devcontainetest,target=/workspaces/devcontainetest,consistency=cached --mount type=volume,src=vscode,dst=/vscode --mount type=bind,src=\\wsl.localhost\Ubuntu-20.04\mnt\wslg\runtime-dir\wayland-0,dst=/tmp/vscode-wayland-ba7ede98-a9e5-4dfc-a023-d66e1a09712f.sock -l devcontainer.local_folder=c:\temp\endjin\devcontainetest -l devcontainer.config_file=c:\temp\endjin\devcontainetest\.devcontainer\devcontainer.json --entrypoint /bin/sh -l devcontainer.metadata=[{"id":"./local-features/git"},{"id":"ghcr.io/devcontainers/features/common-utils:2"},{"remoteUser":"vscode"}] mcr.microsoft.com/devcontainers/base:alpine-3.17 -c echo Container started
docker: Error response from daemon: invalid mount config for type "bind": bind s
ource path does not exist: \\wsl.localhost\Ubuntu-20.04\mnt\wslg\runtime-dir\way
land-0.
```

Steps to Reproduce:

1. Start Rancher Desktop
2. Open a folder in Dev Container

Issue only occurs when using VS Code Dev Containers extension > v0.266.1

**Comment by rik1599** [comment]
Same problem: Revolved dowgrading devcontainer extension to 0.266.1.
I think it is a problem of the extensione because the same problem seems appear also in Docker Desktop.

**Comment by MikeEvansLarah** [comment]
I did not get the error when using Docker Desktop with latest version of extension

**Comment by jsburckhardt** [comment]
Have a look into this issue https://github.com/microsoft/vscode-remote-release/issues/8172

**Comment by bamurtaugh** [comment]
It sounds like this may be covered by https://github.com/microsoft/vscode-remote-release/issues/8172#issuecomment-1481296173, and then https://github.com/microsoft/vscode-remote-release/issues/8157.

Are folks still experiencing this?

**Comment by CaringDev** [comment]
Using v0.288.1 and `dev.containers.mountWaylandSocket: false` works for me using Rancher Desktop 👍🙏

**Comment by OneCyrus** [comment]
I had it working with mountWaylandSocket once but now the error is back also with v0.288.1.


looks like it doesn't respect the setting in the devcontainer file:
```
"customizations": {
   "vscode": {
     "settings": {
       "dev.containers.mountWaylandSocket": false
     }
   }
 }

```

**Comment by KeesCBakker** [comment]
Had the same problem on my Windows 10. But I moved the `wayland-0` and `wayland-0.lock` file to an `backup` dir. After rebuilding the dev container everything was fine. Got the idea from: https://dev.to/crumdev/vscode-dev-container-failing-to-build-ap4

**Comment by bamurtaugh** [comment]
Thanks all for the continued feedback. It sounds like there are several possible solutions shared above. Please let us know if folks still encounter this.
