### ISSUE TITLE
Can't load container log or Attach to Running Container

### ISSUE THREAD

**Issue by codigoisaac** [microsoft/vscode-remote-release#8307]
Type: <b>Bug</b>

If I right-click in the container and select "Show container log", the container log does not appear. This started to happen today and other friends of mine also noticed.

I installed the previous version of Microsoft's "Dev Containers" extension and the problem persists.

Also, if I click the container in the status bar and select "Attach to Running Container...", or if I click "Attach to Container" in the list of Dev Containers, it doesn't show the available containers so I can attach. 

Extension version: 0.288.0
VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.09GB free)|
|Process Argv|--crash-reporter-id eab56b6e-06b1-4f4f-b09a-673d4dc2180c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container work_plataforma (plataforma_beta)|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|Memory (System)|3.76GB (1.00GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container work_terra (terra_beta)|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|Memory (System)|3.76GB (1.00GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30672706
vsctsb:30677850
defaultazurewalk:30687958
pythonms35:30701012

```

</details>

**Comment by MarkusMattinen** [comment]
If your containers are based on Alpine 3.15 or older, it might be this issue: https://github.com/microsoft/vscode/issues/178748

I ran into this issue and the main symptom was that most of the Dev Containers extension commands would do nothing (like Show Container Log, Rebuild Container, Attach to Running Container etc.). Only the status bar shows "Activating extensions..." for a few seconds, and nothing else happens. What you're describing here sounds very similar.

Upgrading the containers to Alpine 3.16 or newer fixed it for me.

**Comment by bamurtaugh** [comment]
Thanks for filing @codigoisaac, and thanks for sharing that extra info @MarkusMattinen.

@codigoisaac does what @MarkusMattinen mention above sound like your scenario?

**Comment by codigoisaac** [comment]
Thank you @MarkusMattinen . Your note helped us resolve the problem!

@bamurtaugh yes, and the problem is fixed, thanks :)
