### ISSUE TITLE
Chrome debugger remote: Partially working source maps

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#831]
Testing #754

Setting the breakpoint in HelloWorld.vue did not register, but when I set the breakpoint in the 'loaded script', it mapped back to HelloWorld.vue:

![image](https://user-images.githubusercontent.com/9205389/60180664-d61b4e80-9820-11e9-9490-b4191c93c43e.png)

Doing this locally works correctly.

I set this up using the Vue.js CLI recipe: https://github.com/Microsoft/vscode-recipes/blob/master/vuejs-cli/README.md

**Comment by roblourens** [comment]
Should be the same as https://github.com/microsoft/vscode-chrome-debug/issues/867
