### ISSUE TITLE
Dev container gets stuck at "Start: Run in host: id -un"

### ISSUE THREAD

**Issue by osirisFdragon** [microsoft/vscode-remote-release#8319]
Hello, I have a problem when run `Dev Containers: Open Folder in Container...` in a remote ssh server. It keeps stucking at `Start: Run in host: id -un` as in image below.

![Screenshot from 2023-04-04 09-42-10](https://user-images.githubusercontent.com/119914421/229673065-6e0799b0-b960-463a-a0d0-58ca8e3e0614.png)

Some environment information:
- VSCode Version: 1.74.3
- Local OS Version: Ubuntu 18.04.6 LTS 
- Remote OS Version: Ubuntu 22.04.1 LTS
- Remote Extension/Connection Type: Dev Containers version 0.269.0
- Remote - SSH Extension version: 0.98.0

P/s:
- I have a simple Dockerfile (only contains `FROM python:3.8`) and I run devcontainer from this configuration Dockerfile.
- It works fine when run devcontainer in my local device. But meet above problem when run through SSH in server.

Thanks for helping.

**Comment by ricber** [comment]
@osirisFdragon I reported the same problem in #8259

**Comment by osirisFdragon** [comment]
@ricber Do you have solution for this annoying problem? It extremely doesnt have a log to know where the error comes from.

**Comment by ricber** [comment]
@osirisFdragon in my case downgrading Dev container to version 0.266.1 solved the problem.

**Comment by ASiCo1116** [comment]
I ran into the same problem, any updates?
Thanks!

**Comment by bamurtaugh** [comment]
Thanks all for reporting. Are you still experiencing this in the latest VS Code Insiders?

If so, are you able to [grab logs](https://github.com/microsoft/vscode-remote-release/issues/8259#issuecomment-1486334481), or do you experience what @ricber [mentioned](https://github.com/microsoft/vscode-remote-release/issues/8259#issuecomment-1496289406) about that not working either?

**Comment by ricber** [comment]
@bamurtaugh with version 0.288.1 I do not experience the issue anymore

**Comment by stellarpower** [comment]
I have tried `0.292.0` and `0.294.0 preview` on Jammy AMD64 and this still occurs for me. Downgrading to `0.266.1` also has not resolved the problem. I have set the log level to trace as advised in #8259  but this isn't giving me any extra information.

**Comment by stellarpower** [comment]
Upon further inspection, it seems the SSH connections that Code started were left busy-waiting and using up a lot of my CPU power.
