### ISSUE TITLE
Chrom debugger source mapping on react-app works on Windows but not in WSL

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#832]
Testing #754

Windows with WSL, installed Debugger for Chrome extension

- following https://medium.com/@auchenberg/live-edit-and-debug-your-react-apps-directly-from-vs-code-without-leaving-the-editor-3da489ed905f

- In the Windows File System, git clone `https://github.com/ahfarmer/calculator.git`
- open folder, `yarn`, `yarn start`
- create a chrome launch config, set URL and webRoot
```
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}/src"
        }
```
- set breakpoint in `calculate.js`, run launch config and use web app
- all works, breakpoint is reached

Now try in WSL

- `Remote WSL: Reopen Folder in WSL`
- `yarn start`
- set breakpoint in `calculate.js`, run launch config and use web app
- breakpoint not verified and not reached

**Comment by roblourens** [comment]
I think it's the same as https://github.com/microsoft/vscode-chrome-debug/issues/867, should be fixed
