### ISSUE TITLE
[Remote-SSH Bug]: Adding new host breaks ssh config file when there are spaces in the host, with more detail

### ISSUE THREAD

**Issue by dandelion-sea** [microsoft/vscode-remote-release#8320]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Hi there!
This is infact an old issue #6197. I'am sorry that I did't get any notice about the reply until today, and the thread is closed now, and unfotrunatly the bug still exist. So I have to open a new issue.
It's just a simple bug, but I recognize that I didn't explain it clearly in the old issue. So I improved the details and paste again here. (If it's better to continue in the old thread, I can repose the detail again there.)

### Steps To Reproduce

All in GIF:
![1](https://user-images.githubusercontent.com/38586229/229699638-212671f7-b43e-4556-af09-434df0a4c23f.gif)

Detailed Steps below:
1. Prepare an example config file, which has quoted string with space.
``` ssh-config
Host "vm-ubuntu-2004"
  HostName 192.168.211.128
  User example
  Port 22

Host "CentOS 7.9 no GPU"
  HostName zone1.example.com
  User example
  Port 2224
```

2. click left-buttom `green-area`, click `Connect to Host...`, click `Add new host...`, type any valid ssh string, such as `ssh hello@microsoft.com -A`.
![3](https://user-images.githubusercontent.com/38586229/229699682-81f12133-a69a-47a6-b8e0-5e160c7d02f4.png)

3. You can see the broken ssh config how.
![4](https://user-images.githubusercontent.com/38586229/229699862-d2aa6a8d-a49e-4c5d-a548-a4e5c16bfa01.png)

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[13:27:31.809] Log Level: 2
[13:27:31.824] VS Code version: 1.73.1
[13:27:31.825] Remote-SSH version: remote-ssh@0.96.0
[13:27:31.825] win32 x64
[13:31:17.492] Picking SSH host
```

</p>
</details>

**Comment by roblourens** [comment]
Possibly an issue with the ssh-config library- not sure where the quoting is supposed to happen

**Comment by seaofbits** [comment]
I've checked the [manual](https://man.openbsd.org/ssh_config.5#DESCRIPTION) of the ssh_config:

> The file contains **keyword-argument pairs**, one per line. Lines starting with ‘#’ and empty lines are interpreted as comments. **Arguments may optionally be enclosed in double quotes (") in order to represent arguments containing spaces.** Configuration options may be separated by whitespace or optional whitespace and exactly one ‘=’; the latter format is useful to avoid the need to quote whitespace when specifying configuration options using the ssh, scp, and sftp -o option.
> 
> The possible **keywords** and their meanings are as follows (note that keywords are case-insensitive and arguments are case-sensitive):
> 
> **Host** ...

So spaces in the argument of `Host` is valid in grammar. And it's useful too, I usually configure as below:
```
Host "CentOS 7.9 no GPU" ai
  HostName zone1.example.com
  User example
  Port 2224
```
This allows me to see a readable name in the green-block in the left of status bar, and I can use `ssh ai` to connect to my server conveniently.

**Comment by seaofbits** [comment]
I don't know what's the implementaion of the `Add new host...` function. It seems (just seems in my opinion) easy to fix because we can just simply add some line on the top of the configuration file, and keep rest of the file original.

In fact, the bug just affect me when it occurs for the first time, it slightly breaks my ssh_config file. After that, I'am always editting ~/.ssh/ssh_config mahually.

**Comment by seaofbits** [comment]
> Hi! To follow up the fix for me seems to be when using "add new ssh host" and typing in `ssh "host name"` for example, this is valid and should be saved in the ssh config as `Host "host name"`. Currently, it is saved as `Host host name` which breaks it. Fix is just to the "add new ssh host" command to keep quotes when copying over.

Yes, this is one aspect. Another aspect is, if you type `ssh "host2 name"`, it will break ALL existing lines like `Host "host name"`  in the ssh_config file.

In other words, we can have a test case:

1. In "add new ssh host", type `ssh "host name"`, it should be saved as `Host "host name"` in ssh_config.
2. In "add new ssh host", type `ssh "host name 2"`, it should be saved correctly too, and the previous `Host "host name"` is not broken.

**Comment by roblourens** [comment]
As of the latest ssh version, spaces are no longer allowed in hostnames. See https://github.com/microsoft/vscode-remote-release/issues/9370
