### ISSUE TITLE
Dev Containers: "Open folder in Container..." only opens default devcontainer config when starting remote

### ISSUE THREAD

**Issue by dmckernanacv** [microsoft/vscode-remote-release#8322]
- VSCode Version: 1.77.0
- Local OS Version: MacOS Ventura 13.3
- Remote OS Version: Irrelevant (Bug is prior to creating container)
- Remote Extension/Connection Type: Containers

- Logs:
[VSCode-Logs.zip](https://github.com/microsoft/vscode-remote-release/files/11148725/VSCode-Logs.zip)

Steps to Reproduce:

Prerequisite: Have a local folder ready with two devcontainer definitions like so

```mermaid
---
title: Folder
---
flowchart LR
  root["/"] --> .devcontainer[".devcontainer/"]
  .devcontainer --> dc1[devcontainer.json]
  .devcontainer --> secondaryContainer["secondaryContainer/"]
  secondaryContainer --> dc2[devcontainer.json]
```

1. Open VSCode locally
2. Open command pallete (F1)
3. Pull up "Dev Containers: Open Folder in Container" command
4. Select the command and choose your folder with two devcontainer configurations

At this point, I would expect the modal which asks which devcontainer I want to use to popup, however it simply picks the default one (that is `folderRoot/.devcontainer/devcontainer.json`)

Once the default devcontainer starts I can run the command again (now that I am in remote mode), and it gives me the option to pick the `secondaryContainer`, however it should give me this option before entering remote mode, as this is a waste of time / resources if I intend to use the secondary container from the start.

Does this issue occur when you try this locally?: Irrelevant
Does this issue occur when you try this locally and all extensions are disabled?: Irrelevant

**Comment by chrmarti** [comment]
Can reproduce when starting with an empty window (no folder open).

**Comment by chrmarti** [comment]
@andreamah The following code does not return any files when in an empty window, it returns 20 files when I have a workspace folder. This seems unexpected.
```ts
	const rootUri = vscode.Uri.parse('file:///Users/chrmarti/Development/repos/smktst');
	const configFilePattern = '{.devcontainer.json,.devcontainer/devcontainer.json,.devcontainer/*/devcontainer.json}';
	const pattern = new vscode.RelativePattern(rootUri, configFilePattern);
	const files = await vscode.workspace.findFiles(pattern, null);
```

**Comment by andreamah** [comment]
Hmm... in the docs website, it says that `vscode.workspace.findFiles` looks in all workspace folders. 
<img width="397" alt="image" src="https://user-images.githubusercontent.com/31675041/236070872-41a2a554-ce0e-4179-9b43-6acae002474a.png">

Based on the fact that it's in `vscode.workspace`, I think it makes sense that it searches workspaces and doesn't return any results if no workspaces are open. What do you think?

**Comment by chrmarti** [comment]
I'm using a URI for `base` for `vscode.RelativePattern` which says it works outside of the workspace:
```ts
 * @param base A base to which this pattern will be matched against relatively. It is recommended
 * to pass in a {@link WorkspaceFolder workspace folder} if the pattern should match inside the workspace.
 * Otherwise, a uri or string should only be used if the pattern is for a file path outside the workspace.
```

It works when I have some other unrelated workspace folder open, so I guess there must be very little missing to make it work with the empty window.

**Comment by andreamah** [comment]
@chrmarti I fixed the `findFiles` issue in https://github.com/microsoft/vscode/pull/181951. Please let me know if anything else is needed here.

**Comment by chrmarti** [comment]
Works in latest 1.80-insiders for me. Thanks!
