### ISSUE TITLE
Fails to connect to WSL with wsl extension 0.78.0

### ISSUE THREAD

**Issue by pantsmann** [microsoft/vscode-remote-release#8324]
Type: <b>Bug</b>

Update WSL extension to version 0.78.0. Then try to open workspace where the code resides in WSL. Opening WSL message appears and spins indefinitely. Have let it spin in the background for hours.

Same result if I try to start VSCode from a WSL terminal using code-insiders. 

While trying to connect almost no other functionality is available.

I rolled back the extension to 0.77.0 and everything works again.

Extension version: 0.77.0
VS Code version: Code - Insiders 1.78.0-insider (cbf35328c8357175b9cd747823f39ade987c3d3c, 2023-04-04T18:41:32.861Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Connection to 'wsl+Ubuntu' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (0.33GB free)|
|Process Argv|--crash-reporter-id 88ec6cdc-0ca1-447a-aded-701683f3fcf1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (4 x 2807)|
|Memory (System)|7.76GB (5.41GB free)|
|VM|0%|

Connection to 'wsl+Ubuntu' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
6233i204:30659907
pythonb192cf:30661257
defaultazurewalk:30687958
pythonms35:30671666
j16hj152:30680472
57b77579:30687741
pythonclientmv:30700173

```

</details>

**Comment by cl1933404370** [comment]
I have the same problem. Version 0.78 of the wsl extension does not work properly in Version 1.78.0 of vs code insider.
![屏幕截图 2023-04-06 214212](https://user-images.githubusercontent.com/39961012/230397159-0ab7cdde-b544-4163-8afb-1ada58316e59.png)

**Comment by bamurtaugh** [comment]
Thanks for reporting, and apologies for the difficulty here. Do you still experience this with the latest WSL extension in the latest VS Code Insiders?

**Comment by mage1k99** [comment]
Yes, I too got this same error, so I downloaded previous version, installed it and it has no issues. something is wrong with the new update I guess

**Comment by aeschli** [comment]
Do you still see this with the latest version 0.78.4? If yes, can you paste the WSL Log (command: `WSL: Show Log...`) or see if you find something the Dev tools console (`Developer: Toggle Developer Tools`)

**Comment by mage1k99** [comment]
No, I don't get the issue with latest version `v0.78.4`

**Comment by aeschli** [comment]
Thanks, closing the issue then
