### ISSUE TITLE
On m1 mac, when remote ssh is an x86ubuntu, the installation of extended CPU takes up very high

### ISSUE THREAD

**Issue by JunJie-zhang-o** [microsoft/vscode-remote-release#8326]
I used orbstack software to create an x86 linux on m1 mac. When I remote ssh linux and install the extension, the CPU occupies a very high.

Vscode: arm version
linux：x86 version

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/78187633/229992230-93ab7c21-8033-4c03-b03b-c98375a5598b.png">

I wonder if it is caused by the incompatibility between vscode's arm and linux's x86?

**Comment by JunJie-zhang-o** [comment]
I don't know what the vsce-sign process works, but I installed several extensions to Linux at the same time.

**Comment by darionesi** [comment]
hi @JunJie-zhang-o, sounds similar to https://github.com/microsoft/vscode-remote-release/issues/8169, if that's the case, could you please post there? thanks

**Comment by bamurtaugh** [comment]
Thanks for opening @JunJie-zhang-o! Sounds like this may be related to the linked issue, so I'll close this one. If it's separate, please just let me know. Thanks!
