### ISSUE TITLE
Set max number of caches VS Code server installations

### ISSUE THREAD

**Issue by GammaGames** [microsoft/vscode-remote-release#8329]
Related to #1041 

> when you mentioned you see old versions of vscode in the .vscode-server/bin folder, how many do you see? If it's 5 or less that's expected.

[by tanhakabir](https://github.com/microsoft/vscode-remote-release/issues/5955#issuecomment-990136815)

Why would I possibly need 5? We keep our programs up to date so limiting it to the last 2 would be sufficient. Any more is just a waste of space on the server. Since it's installed into my home directory, I should be able to set the max in my `settings.json`.

**Comment by joshspicer** [comment]
Thank you for the feedback, will continue to track in https://github.com/microsoft/vscode-remote-release/issues/7963
