### ISSUE TITLE
Activity bar icons contributed by extensions running remotely are shown hidden until remote window is loaded

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-release#833]
1. Have some extensions that contribute activity bar icons, like GitLens, installed
2. Open remote window (SSH or WSL or Dev Container)

Not all activity bar icons load:
![missing_gitlens_icon](https://user-images.githubusercontent.com/3672607/60118949-38495600-9732-11e9-9ecd-d7e130594d41.png)

Activity bar icons are loaded only after remote server is started

**Comment by gregvanl** [comment]
I still see the delay in showing the Activity Bar items until the server is installed on WSL

**Comment by sandy081** [comment]
@gregvanl Delay is expected and infact it is the fix. We do not cache the icons anymore and they appear only after remote connection is established. 

Previously, remote activity bar items are rendered as empty placeholders until connection is established which looks buggy. Now we do not show these placeholders and show the items after.
