### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by PatrickSchiefer** [microsoft/vscode-remote-release#8333]
Pleas add an API documentation, to use this extension as a dependency for others

I want to open a new window from a VSCode Extension via Typescript, but didn't find any API documentation.

As a workaround I now open the window via terminal but it's not really a clean way

```
		var terminal = vscode.window.createTerminal(terminalOptions);

		terminal.show();
		terminal.sendText(`code --folder-uri vscode-remote://ssh-remote+${ip.ipAddress}/`, true);

```

Is there a other way to do it?

**Comment by roblourens** [comment]
I think this work-in-process doc is what you are looking for: https://github.com/microsoft/vscode-remote-release/pull/7725/files. Your approach is ok too, tbh

But could you tell me more about what you are building and what your usecase is?

**Comment by PatrickSchiefer** [comment]
We develop a solution which provides self service developer environments. These Environments could be created via one click in VSCode. The developers should be able to open VSCode via ssh inside of this environments. I will try it with this doc of the PR.
