### ISSUE TITLE
VSCode scans remote machine file systems without even connecting to them

### ISSUE THREAD

**Issue by molohov** [microsoft/vscode-remote-release#8334]
Type: <b>Bug</b>

1. Establish remote connection to server and save keys/passwords
2. Close VSCode
3. Open new VSCode window, without specifying any target folder
4. Remote file system gets scanned. 

I know this is happening because the drives on my remote file system are set to spin down after inactivity, and opening VSCode on my client machine, without connecting to the remote session, always spins them back up.

Extension version: 0.98.0
VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.75GB (12.01GB free)|
|Process Argv|--crash-reporter-id da6c98e1-840c-4ba3-8c8d-751e25bb27ac|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.0.0.3|
|OS|Linux x64 5.10.0-21-amd64|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 800)|
|Memory (System)|31.25GB (4.80GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30705553
vscodeenable:30660116
azdwalk:30687957
pythonms35:30701012
pythonclientmvcf:30705674

```

</details>

**Comment by roblourens** [comment]
Sorry, I don't understand the scenario. Are you using the Remote-SSH extension? Are you sure you don't have a remote window open in the background when reopening vscode?

If not, we are not trying to connect to your system.

**Comment by molohov** [comment]
Yes, I am using the Remote-SSH extension. 

I just tried this with the following scenario.
VSCode window open on a local workspace
Opened a new VSCode window (using File, New Window)
Again my remote file system was scanned

**Comment by roblourens** [comment]
> Again my remote file system was scanned

Can you be more specific? What exactly is happening?

**Comment by molohov** [comment]
As per the description in the first post, my remote system's hard drives spin up as soon as VSCode is opened, indicating that there is activity on those drives.

**Comment by molohov** [comment]
And to add more information to that, the folder opened on the remote system is NOT on those hard drives, meaning that VSCode is scanning far more than the remote folder.

**Comment by roblourens** [comment]
You are saying that this happens when you are connected to that remote, or when you previously had connected but are not currently connected? The second is what it sounds like you are claiming to me

> VSCode window open on a local workspace
> Opened a new VSCode window (using File, New Window)

And I can't imagine how that would happen. As it is I am not sure there is enough for us to do anything about whatever you're seeing.

**Comment by molohov** [comment]
> You are saying that this happens when you are connected to that remote, or when you previously had connected but are not currently connected? The second is what it sounds like you are claiming to me
> 
> > VSCode window open on a local workspace
> > Opened a new VSCode window (using File, New Window)
> 
> And I can't imagine how that would happen. As it is I am not sure there is enough for us to do anything about whatever you're seeing.

Correct, it is the second case. 
Is there any logging mechanism I can enable to see what is causing the scan? Since it is very reproducible on my end, I should be able glean something for you.

**Comment by roblourens** [comment]
I still don't know what you mean by "scan" so I don't know what sort of log you expect.

**Comment by molohov** [comment]
The files on my remote machine are accessed, but not explicitly opened into any editor. I was hoping a log could show me what files are being accessed upon VSCode startup

**Comment by roblourens** [comment]
I guarantee that we are not accessing files on any other machines when you have not opened a window with a workspace on that machine.

Sorry, but without more detail this is not an actionable issue

**Comment by molohov** [comment]
I was able to determine the root cause as SMBClient, being triggered by VSCode. It seems it was looking at recently accessed directories/files that were accessed on the server HDD share, whenever a new window was being opened. In any case, unrelated to the remote extension. Thanks for the support anyways.
