### ISSUE TITLE
Ability to cancel downloads

### ISSUE THREAD

**Issue by homelyseven250** [microsoft/vscode-remote-release#8338]
Type: <b>Feature Request</b>

It would be great if when downloading a file via the context menu you can cancel it, particularly for large files such as videos. Currently I believe the only way is to reload the window.

Extension version: 0.24.0
VS Code version: Code 1.77.1 (Universal) (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:23:33.779Z)
OS version: Darwin x64 22.4.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 6.2.9-arch1-1

**Comment by wang-c-h** [comment]
I also hope to see this feature soon

**Comment by bamurtaugh** [comment]
Thanks for opening! I believe this is related to https://github.com/microsoft/vscode/issues/169433 and would be covered by https://github.com/microsoft/vscode/issues/57585 (cc @bpasero). I'll close this issue, but if this is a separate topic, please just let me know. Thanks!
