### ISSUE TITLE
Failed to establish a socket connection to proxies: ["HTTPS <proxy_name>:<port_number>"]

### ISSUE THREAD

**Issue by xu19971109** [microsoft/vscode-remote-release#8347]
![image](https://user-images.githubusercontent.com/50237122/231107809-7d171519-33b8-43bb-b8e6-c7dd51913bf6.png)
I couldn't clear the values of http_proxy and https_proxy, so I set “usnet http_proxy” and "unset https_proxy" in ~ /.bashrc, but why would I get my local environment variable values in the output? This is the value before I unset env. The python and jupyter plug-ins cannot be downloaded from the server.

**Comment by chrmarti** [comment]
I don't understand. Are these environment variables literally set to `<proxy_name>:<port_number>` or are these redacted value? How did the output change after you unset them in bashrc?

**Comment by xu19971109** [comment]
> I don't understand. Are these environment variables literally set to `<proxy_name>:<port_number>` or are these redacted value? How did the output change after you unset them in bashrc?

These environment variables literally set to `<proxy_name>:<port_number>`, I changed a lot of configuration files but didn't work. Therefore,  in the bashrc under my user path, I write 'unset https_proxy' and 'unset http_proxy' in ~/.bashrc and source it, but the output of vscode's ssh is shown  in the screenshot above.

1. The tar file of vscode-server couldn't download by vscode, it only can donwload by wget.
2. docker container can't install. It seems to pause somewhere.
The settings of `<proxy_name>:<port_number>` have not changed, older versions of vscode and its extensions are available and undisturbed.  Did the new  version of the vscode or remote-SSH changes the location of reading agent? Can I read my ~ /.bashrc when downloading some thing by the extension store?
Thank you!
![image](https://user-images.githubusercontent.com/50237122/232413108-9b1558a1-5dfe-44bb-bcfe-f2d8205b0d67.png)

**Comment by xu19971109** [comment]
> 

Version: 1.77.3 (Universal)
Date: 2023-04-12T09:19:37.325Z (4 days ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No

**Comment by xu19971109** [comment]
I solved the problem by restarting the mac (it may help a lot) and update the Dev Containers to 0.282.0, but I still have another linux that can only download vscode-server via wget because of http_proxy and https_proxy. Although I write 'unset http_proxy' and 'unset https_proxy' in ~/.bashrc.
I found this error is  like  [7997](https://github.com/microsoft/vscode-remote-release/issues/7997), we all have 
`[info] [LocalProcess0][resolveAuthority(attached-container,1)][1214ms] waiting...`
Then I solved the problem by tapping into #7974 
Thank you!

**Comment by chrmarti** [comment]
@xu19971109 What was the solution?

**Comment by xu19971109** [comment]
> @xu19971109 What was the solution?

Rebooted the local computer and changed the version of Dev Containers.
