### ISSUE TITLE
VSCode inside Docker not checking for code errors inline

### ISSUE THREAD

**Issue by atsepa** [microsoft/vscode-remote-release#8348]
Version: 1.77.1 (Universal)
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:23:33.779Z (6 days ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: Yes

- Issues:
- VSCode inside Docker is no longer detecting issues inline. Error is only shown in the console but not in the IDE or inline
>> text thisShouldBeAnError should be marked inline as an error as it does not exist <<
![Screenshot 2023-04-10 at 12 31 13 PM](https://user-images.githubusercontent.com/59751704/231193185-a5a61e14-61f9-4c4f-b54d-e5e27b20bc63.png)

- VSCode inside Docker is no longer taking you to the declaration of the function when you right-click on it.
- VSCode inside Docker is no longer able to find anything when trying to do a search in the project. It gets stuck. It will only work if the file is open. 
>> Here you can see that it did find handleSearch because the file was open but handleSearch is present in many other files and it does not show in the search results. The search is hung on a loop it seems 
![Screenshot 2023-04-11 at 10 32 27 AM](https://user-images.githubusercontent.com/59751704/231197717-e5d46c5e-f46e-4431-ae28-19b4846248f3.png)

- VSCode inside Docker is no longer able to give you suggestions for imports.
>> Not only some() should be marked as an error as it has not been imported, but it should also let me know there are import options. when i right-click on it <<<
![Screenshot 2023-04-11 at 10 38 25 AM](https://user-images.githubusercontent.com/59751704/231198250-5399a244-c368-4ff1-aac4-a5f756f87a23.png)

- VSCode inside Docker is no longer applying to the code format 

Steps to Reproduce:

1. Open VSCode
2. Run Docker
3. Use "Dev Containers: Open Folder in Container" This will open VSCode inside the container
4. Error 1 -> Create an error, this will not be marked as an error inline
5. Error 2 -> Right-click on a function been used, it should take you to the declaration of function
6. Error 3 -> Try to search for something in a not-open file. results are never displayed
7. Error 4 -> Add a function from any external library to a function. It should be marked as an error as it has not been imported and when right-clicked it should give you the possible import options
8. Error 5 -> Add code without indentation. When save code should be formatted

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by atsepa** [comment]
It was working perfectly last week, I can see there was an update April 10, so I wonder if this has something to do with this

**Comment by bamurtaugh** [comment]
Thanks for filing, and I'm sorry to hear things aren't working quite right at the moment. Since you mention behavior changing with an update, does the latest VS Code Insiders and pre-release version of the Dev Containers extension work for you?
