### ISSUE TITLE
Adopt opening in-product Get Started walkthrough from remote help

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-release#8349]
With https://github.com/microsoft/vscode/commit/ad2e57deb371dcd833e7594eece283038c9228fd in `v1.78-insider` we now support remote extensions specifying a Get Started walkthrough ID in the remote help contribution. This allows for a more integrated Get Started experience since it removes the need to open an external site to learn how to use the product. Remote Repositories has adopted this if you'd like a reference.

**Ask**: for all remote extension owners, please consider adopting the `id` property in `gettingStarted` in your remote extension's remote help section if it is valuable for your remote extension to register a Get Started walkthrough (you'll likely want to bump the VS Code engine you target if you do so):

- [x] Remote Repositories @joyceerhl
- [x] Remote-SSH @eleanorjboyd @roblourens 
- [ ] Remote-Tunnels @connor4312 @aeschli 
- [x] WSL @aeschli
- [ ] Dev Containers @chrmarti 

cc @bamurtaugh @bhavyaus

**Comment by roblourens** [comment]
Is the plan to add walkthroughs for remote extensions that don't have them? 

Also, were we supposed to adopt the `remoteHelp` contribution at some point? I don't see that for ssh/tunnels

**Comment by joyceerhl** [comment]
Huh, you're right, I guess SSH and Tunnels never adopted `remoteHelp` or walkthroughs. I'd suggest to adopt them to be consistent with other remotes if it makes sense for your remote's scenarios.

**Comment by roblourens** [comment]
Oh, that contrib is old, guess we just missed it. I'll add it for SSH now

**Comment by roblourens** [comment]
Btw what I'm seeing now is that the "Get Started" opens a quickpick showing URLs, but when I click Dev Containers, it opens the welcome page, and doesn't show a walkthrough.

**Comment by roblourens** [comment]
But I think we don't plan to add a walkthrough for SSH right now

**Comment by joyceerhl** [comment]
> Btw what I'm seeing now is that the "Get Started" opens a quickpick showing URLs, but when I click Dev Containers, it opens the welcome page, and doesn't show a walkthrough.

That is a bug, thank you!

**Comment by joyceerhl** [comment]
Moving this out to May for further adoption in Tunnels and Containers. @aeschli @chrmarti if you don't plan to add a walkthrough for your remote extensions please feel free to just check the box above and unassign yourself--thanks!

**Comment by bamurtaugh** [comment]
@aeschli I'm not aware of any plans at the moment. If folks generally think it'd be useful (which I think it would), I can add an item in an upcoming iteration to work on them.

**Comment by joyceerhl** [comment]
Closing this out for now since I think there aren't yet plans to add walkthroughs for Tunnels and Dev Containers and all other remotes have adopted--please feel free to create new issues to track those.
