### ISSUE TITLE
Configured forwardPorts prevents application from running

### ISSUE THREAD

**Issue by Somebody25** [microsoft/vscode-remote-release#8354]
Configured forwardPorts seem to block applications from using this specific port. I am using dev containers to develop an elixir application and I was always able to easily forward, for example port 4000 to the host.

Now the problem occured, when I set a port forwarding from container 4000 to local address localhost:4000, the application that I am developing cannot be started because it cannot obtain the port. It dies with a :eaddrinuse (address already in use) error.

This was not the case a few days ago where the application was running on port 4000 fine while also being forwarded to localhost:4000 and accessible with the hosts browser.

Prior to launching vs code, port 4000 is not in use neither by the host windows, nor in wsl2 and also when running the container and the application stopped, there is no listening application on 4000 in the container. This issue arises when the project is located locally and in wsl2 file system.

I found a workaround for this issue and while working on that also noticed something strange while looking at the resource monitor: After I start vs code all ports configured as forwardPorts in the devcontainer.json are claimed by Code.exe . Then I change the local address port in the port forwarding to something different, for example 4000 to localhost:4002. The application now can be started. There is a process "wslrelay.exe" that spawns and claims port 4000 on the host windows. While this process is running, I cannot change the forwarded port back to 4000. It does die after a few seconds and then I can change the port back to 4000 allowing the application to be forwarded on port 4000 like before.

A other workaround is to statically specify the port in the docker-compose.yml and not as forwardPorts.

- VSCode Version: 1.77.3
- Local OS Version: Windows 11 Pro 22H2 Build 22621.1555
- Remote OS Version: Debian GNU/Linux 11 (bullseye)
- Remote Extension/Connection Type: Containers

- Logs:

Steps to Reproduce:

1. Open folder in vscode
2. Add devcontainer configuration files, the ones I used where "Elixir, Phoenix, Node.js & PostgresSQL (Community)"
3. Open folder in container and wait for the build
4. Create a new phoenix project with `mix phx.new name`
5. Follow the instructions to start a server
6. Server cannot be started because address is already in use

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by adriano-nbfr** [comment]
I'm facing the same issue since I've applied an update two days ago. Before the update, my application was always able to start at port 8080 with "forwardPorts" : [8080] in devcontainer.json file. Now, this configuration makes the application always fail on start listen on port 8080 (if I leave the auto forward option enabled and not specify the port, VSCode uses the port 8081 and start normally). After a whole day trying to understand the cause, I solved my problem using the older "appPort" : [8080] option (statically) instead of forwardPorts.

**Comment by or2e** [comment]
fixed in WSL [1.2.1](https://github.com/microsoft/WSL/releases/tag/1.2.1)

**Comment by bamurtaugh** [comment]
Thanks for filing and providing really helpful context. It sounds like this was fixed - if so, are we okay to close it?

cc @alexr00 for awareness too

**Comment by adriano-nbfr** [comment]
Ok. Fix verified by updating WSL to 1.2.1 or higher.

**Comment by Somebody25** [comment]
I also verified it is fixed after updating WSL, thanks!
