### ISSUE TITLE
Doesn't show option to open in new window for containers

### ISSUE THREAD

**Issue by kishankarun** [microsoft/vscode-remote-release#8356]
- VSCode Version:
- Local OS Version: Windows 10
- Remote OS Version: Linux (Rocky Linux 8.6)
- Remote Extension/Connection Type: Containers

- Logs:

Steps to Reproduce:

1. Connect to remote host (SSH)
2. Open the list of containers (From the Dev Containers dropdown)
3. From the tree view, move the mouse over the required container to open
4. We see only 2 options: Open Folder in Container and Remove Recent Folder
5. There should be an option for "Open in New Window", but it shows as "Open Folder in container" as mentioned in screenshot

![image](https://user-images.githubusercontent.com/323202/231806941-1ea6b88b-009f-4218-897c-b221d662946b.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by bamurtaugh** [comment]
Thanks for opening! I think this would be covered by https://github.com/microsoft/vscode-remote-release/issues/8397. If I'm missing anything, please just let me know, and I'm happy to reopen. Thanks!

**Comment by kishankarun** [comment]
@bamurtaugh , Thanks for the related covered issue.
This looks to be pretty much covering all missing features.

Hope the features are being worked upon?
When could we expect them to be available?

**Comment by bamurtaugh** [comment]
Great, no problem! 

That issue is currently on the May milestone, so the plan is for us to continue discussing and potentially implement in May.
