### ISSUE TITLE
Files are marked as changed even though nothing changed

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-remote-release#8359]
Type: <b>Bug</b>

For bug reports please include the complete log output. (In the VS Code window: `F1` > `Dev Containers: Show Container Log`.)

Extension version: 0.290.0
VS Code version: Code - Insiders 1.78.0-insider (c9df8ee8e8c316f38dcc75a894ba150024ce3718, 2023-04-13T05:25:44.823Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (10.99GB free)|
|Process Argv|--crash-reporter-id 11494669-52ca-4f2c-aa0e-29172189cc8e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Python 3|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (5 x 2995)|
|Memory (System)|5.79GB (3.11GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30659908
pythonb192cf:30661257
defaultazurewalk:30687958
pythonms35:30671666
0bg3d529:30680467
7ij38806:30687742
pythonfmttextcf:30710680
pythonclientmv:30700173

```

</details>

**Comment by bamurtaugh** [comment]
Hey @luabud, do you have some repro steps we could try out?

**Comment by luabud** [comment]
Oh, I didn't realize I had created this issue. I tried to reproduce it again to get the repro steps but then I couldn't. I guess I clicked on submit by mistake, apologies :)
