### ISSUE TITLE
Remote SSH does not use remote environment vars

### ISSUE THREAD

**Issue by dannyalan** [microsoft/vscode-remote-release#836]
- VSCode Version: 1.35.1
- Local OS Version: OSx 10.14.3
- Remote OS Version: Dockerised Ubuntu 18:04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to the remote outside of VSCode SSH and set/edit an environment variable
2. Connect to the remote
3. Using the VSCode terminal, call echo $variable_name to print the value. 
4. Identify that the variable is not as expected. 

Screenshot of env variable from a terminal outside of VsCode.
<img width="338" alt="Screenshot 2019-06-26 at 19 37 11" src="https://user-images.githubusercontent.com/3920354/60205643-a16fbd00-9849-11e9-9d25-29d35e7fff8e.png">

Screenshot of the same env variable from within VsCode.
<img width="388" alt="Screenshot 2019-06-26 at 19 37 22" src="https://user-images.githubusercontent.com/3920354/60205705-cd8b3e00-9849-11e9-962e-808b40ae28b5.png">

This of course also applies to any debugging sessions that you instigate from VsCode. I am using the C++ plugin by Microsoft and noticed immediately that the debugged application can no longer access those expected variables.

**Comment by dotnetdanny** [comment]
I have also just tried using the SendEnv functionality in the ssh config, but, with no avail. No env variables are passed to the remote

**Comment by dotnetdanny** [comment]
Ok, further developments:

The host is actually a docker container (I neglected to mention that in the original issue) and the variables are set within the dockerfile. 

If I add those environment vars to the .bashrc file then the issue goes away! 

I can't help but feel however, that this is a workaround. Should VsCode not be able to handle env vars set in docker containers using dockerfiles?

**Comment by roblourens** [comment]
Could you try this with vscode insiders and the nightly version of the ssh extension, and let me know whether it works there? This might have been fixed
