### ISSUE TITLE
Failed to write install script to path when connecting ssh

### ISSUE THREAD

**Issue by CocoLee2** [microsoft/vscode-remote-release#8363]
I downloaded vscode in my disk D before, but I deleted my disk D afterwards. Since D doesn't exit anymore, I cannot download the script. How can I fix this probelm?
![image](https://user-images.githubusercontent.com/111034055/231944775-7ba67b88-73bd-4bf0-b0cf-f9cc2a434055.png)

**Comment by roblourens** [comment]
> I downloaded vscode in my disk D before, but I deleted my disk D afterwards.

This is based off your TEMP environment variable. You should fix that on your system to make sure that it points to a path that exists, or you will probably have issues with lots of programs
