### ISSUE TITLE
The Golang project cannot shut down the process after stopping debugging

### ISSUE THREAD

**Issue by 6yy66yy** [microsoft/vscode-remote-release#8365]
- VSCode Version:1.77.3
- Local OS Version:Microsoft Windows [version 10.0.22621.1413]
- Remote OS Version:AlmaLinux release 8.7 Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023
- Remote Extension/Connection Type: WSL

- Logs:

Steps to Reproduce:

1. Open a Golang project
2. Add breakpoints in the program and debug the project (The debugging window may get stuck or run slowly)
3. wait
4. Stop debugging
5. Query the debug process, the process is still running

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
Please file this on the Go extension, thankss
