### ISSUE TITLE
Closing Remote Tunnel does not unregister previous tunnel

### ISSUE THREAD

**Issue by jnoelvictorino** [microsoft/vscode-remote-release#8370]
Type: <b>Bug</b>

1. Using code-tunnel-insiders.exe tunnel --accept-server-license-terms --name <NameOfTunnel>
2. Then, code-tunnel-insiders.exe tunnel kill
3. Then start a new tunnel. There's an error that the tunnel name already in use.

In previous version, this did not happen.

Extension version: 1.0.0
VS Code version: Code - Insiders 1.78.0-insider (3ad5774eb8123d4224eb55629df9e5f82fe13b99, 2023-04-14T05:25:56.476Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.89GB (9.77GB free)|
|Process Argv|--crash-reporter-id cd7d16a5-df10-4965-834e-bcdfacc8e07f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: abc2023|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|9.72GB (7.03GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30659908
defaultazurewalk:30687958
pythonms35:30671666
0bg3d529:30680467
ecj1e332:30687743
pythonfmttextcf:30710680
pythonclientmv:30700173

```

</details>

**Comment by bamurtaugh** [comment]
Thanks for filing @jnoelvictorino, this sounds like a bug, but looping in @connor4312 who could help confirm.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/180693

**Comment by jnoelvictorino** [comment]
Thanks @bamurtaugh & @connor4312
