### ISSUE TITLE
No response after click connect to host

### ISSUE THREAD

**Issue by liujiaorr** [microsoft/vscode-remote-release#8372]
Steps to Reproduce:

https://user-images.githubusercontent.com/128006184/232144420-caed7a75-56e8-42d9-b499-a195be3308f0.mov

**Comment by roblourens** [comment]
Can you check for errors in the devtools log? (Help > Toggle Developer Tools)

**Comment by liujiaorr** [comment]
Can you give me the link of Help > Toggle Developer Tools, I didn't see Toggle Developer Tools in help. Thanks

**Comment by liujiaorr** [comment]
The devtools log:  
 ERR A system error occurred (EISDIR: illegal operation on a directory, read): Error: A system error occurred (EISDIR: illegal operation on a directory, read)
	at m.h (/private/var/folders/lj/npq5ygcj72n0dm5b494vv0bc0000gr/T/AppTranslocation/A5B79C41-D3A6-4FB1-8A8D-82A8DC029A8F/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:126151)

**Comment by roblourens** [comment]
How did you install vscode? Seems like it's installed into a temp dir, maybe a browser download folder? I wonder whether the extension host is not working at all like this, can you run other extensions?

**Comment by liujiaorr** [comment]
I installed it on the dir of download, just by clicking the unzip package. The other extension like?

**Comment by roblourens** [comment]
I'd recommend moving it out of the temp folder to wherever you want it installed permanently

**Comment by liujiaorr** [comment]
Hi Rob, thanks for your suggestion. Removed ~/.vscode and code package, installed in home dir, no luck so far, it's so weird only happened on my computer, is there any way disable this function? Otherwise can't think what could cause this.

**Comment by roblourens** [comment]
> installed in home dir, no luck so far

So what exactly happens now?
