### ISSUE TITLE
[Feature Request] Give an option if extension should be kept or removed locally after installation.

### ISSUE THREAD

**Issue by Hypnoes** [microsoft/vscode-remote-release#8374]
Stop installing extensions locally if the extension is declared they are prefered running on remote.

Or mark this extension should be removed after the installation is done.
(I'm not sure the installation is download the extension file directly from remote or first download it locally then transfer it. Because remote-server might be at a private network and has no connection with the out-side world.)

**Comment by roblourens** [comment]
Sorry, I don't follow, please describe exactly what the problem is step-by-step

**Comment by Hypnoes** [comment]
![image](https://user-images.githubusercontent.com/13956546/232655078-7516f0f5-c4c2-4dde-ba42-0fa0711d3563.png)

Sorry for my poor english... I mean as above picture, when I install `python extension`

![image](https://user-images.githubusercontent.com/13956546/232655613-364065e9-e74c-4f42-a812-b5feb4590df7.png)

Both local and remote (Dev Container in this case) will install that extension. 
Could I have a option that make vscode only install in Dev Container?

![image](https://user-images.githubusercontent.com/13956546/232656406-2b483bd3-cb49-49d8-9cfc-a0514732e158.png)

It says this extension prefers to run remote.

**Comment by chrmarti** [comment]
You can uninstall the Python extension locally by using a local VS Code window. (I think you had the Python extension installed locally before.)

**Comment by Hypnoes** [comment]
> You can uninstall the Python extension locally by using a local VS Code window. (I think you had the Python extension installed locally before.)

No, the extension isn't installed locally before. And i know i can uninstall it by opening a new local window. I'm just asking if there can be an option for a little convenience.

**Comment by sandy081** [comment]
Do you have settings sync enabled?

**Comment by Hypnoes** [comment]
> Do you have settings sync enabled?

Yes.

**Comment by sandy081** [comment]
When Settings Sync is enabled, we automatically install the extension everywhere. If you want the extension installed only in the remote you can choose **Install (Do not sync)** action as below

![image](https://github.com/microsoft/vscode-remote-release/assets/10746682/921562a7-8d1b-44e2-87e0-480da024ba05)
