### ISSUE TITLE
remote ssh problem with Developer: reload window

### ISSUE THREAD

**Issue by thanhle7** [microsoft/vscode-remote-release#8380]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.77.3
- OS Version:  Windows 10

Steps to Reproduce:

1. remote ssh extension required
2. remote.ssh: Remote Server Listen On Socket = Yes
3. Open a project folder on remote server, then select: Developer.Reload Window
4. vscode unable to reload project but showing the message: please install either wget or curl on remote server
5. While both wget and curl installed, the only solution is killing vscode on remote server then redo "reload window"

Anyway to do "Developer.Reload Window" without a need of killing vscode on remote server?

**Comment by roblourens** [comment]
Please include the log from the Remote-SSH output channel

**Comment by thanhle7** [comment]
> Please include the log from the Remote-SSH output channel
Hi @roblourens,

Attached please find remote sshd log and local terminal log.

[remote_Debian11_sshd_log.txt](https://github.com/microsoft/vscode-remote-release/files/11255366/remote_Debian11_sshd_log.txt)
[local_Windows10_terminal_log.txt](https://github.com/microsoft/vscode-remote-release/files/11255367/local_Windows10_terminal_log.txt)
Thanks,

**Comment by roblourens** [comment]
Are you sure that curl and wget are on the PATH on the remote? We tried to run both commands and this failed.

**Comment by thanhle7** [comment]
> Are you sure that curl and wget are on the PATH on the remote? We tried to run both commands and this failed.

Yes. On the remote server, I have PATH set using /etc/profile. Here below is the output for PATH when checked using printenv
`PATH=/opt/nginx:/opt/curl/bin:/opt/git/bin:/opt/php/bin:/opt/mysql/bin....`

**Comment by thanhle7** [comment]
> > Are you sure that curl and wget are on the PATH on the remote? We tried to run both commands and this failed.
> 
> Yes. On the remote server, I have PATH set using /etc/profile. Here below is the output for PATH when checked using printenv `PATH=/opt/nginx:/opt/curl/bin:/opt/git/bin:/opt/php/bin:/opt/mysql/bin....`

In addition, the sshd service on my remote server configured with both AllowTcpForwarding and AllowStreamLocalForwarding enabled.

At the moment, I set "remote.ssh: Remote Server Listen On Socket = off" and every thing works just fine. I can also see vscode-node server listening to a random tcp port.

However, when switching back using unix socket then problem again. Beside of killing vscode, restarting sshd on remote server, or just wait for a couple of ten minutes, also helps. I think the problem is because of somethings relevant to unix socket reuse or  time out.

**Comment by roblourens** [comment]
> At the moment, I set "remote.ssh: Remote Server Listen On Socket = off" and every thing works just fine. I can also see vscode-node server listening to a random tcp port.

I realized the error message is not quite right, and maybe this isn't documented well, but the socket forwarding only works when curl is present because wget can't make a request to a socket, only a port. So if it works with that setting, then that implies that we found curl but not wget.

**Comment by thanhle7** [comment]
@roblourens Thank you for your prompt response!

> I realized the error message is not quite right, and maybe this isn't documented well, but the socket forwarding only works when curl is present because wget can't make a request to a socket, only a port. So if it works with that setting, then that implies that we found curl but not wget.
> 
I have wget system-wide installed using apt-get. That's why I said I have both wget and curl installed.
> Seems like using this with that setting is a good workaround for you?

No unfortunately. I am not allowed to have any app using tcp port, even locally on my remote server.

**Comment by roblourens** [comment]
Sorry I might have said it the other way around... it implies that we found wget but not curl. Either way, I would guess that it is not actually on your PATH in the environment we get when running our script over ssh. Sorry, I think that's all I can say to help.

If it helps at all, the command we run is `curl --version` and we just check the exit code with `if (( $? == 0 )) [...]`

**Comment by thanhle7** [comment]
Hi @roblourens,
I set the PATH to curl at top priority in every possible setting on my remote linux server. I also did that in vscode settings as below.
```
"remote.SSH.remoteServerListenOnSocket": true,
"terminal.integrated.env.linux": {
  "PATH": "/opt/curl/bin:${env:PATH}"
},
```
I am sure the problem is because of **node** that vscode runs on the remote server. I just tried and learned that: after a "reload window" fail; waiting for 30 minutes and redo; It then works. I guess that "reload window" forces vscode to kill **node**, making it handling improperly the opening unix socket, then unable to restart. Plus, I don't have this problem on my other another linux using ubuntu 20. I think switching Debian 11 back to Ubuntu 20 is the best solution for me now.

Thank you once again for spending your time on this issue.

**Comment by roblourens** [comment]
FWIW, that setting doesn't have an impact here. This is the script we run to install the vscode server on your host- that setting is only about terminals that are opened inside a vscode window.

**Comment by thanhle7** [comment]
> FWIW, that setting doesn't have an impact here. This is the script we run to install the vscode server on your host- that setting is only about terminals that are opened inside a vscode window.

You are correct! I had checked vscode and learned that. I then made a system-wide soft link to my custom curl installation then the problem resolved.

Thank you so much for your help and have a good day.
