### ISSUE TITLE
Issue with Passing Secrets to Docker Using Devcontainer

### ISSUE THREAD

**Issue by DVRM** [microsoft/vscode-remote-release#8386]
I am experiencing a problem while attempting to pass a Personal Access Token (PAT) as a secret to Docker, utilizing the --secret flag in a devcontainer setup. I have configured the following lines in my devcontainer:

`"initializeCommand": "DOCKER_BUILDKIT=1 SECRET_TOKEN=$AZURE_ARTIFACT_TOKEN docker build --secret id=SECRET_TOKEN ."`
I have ensured that the $AZURE_ARTIFACT_TOKEN is present in my .bashrc file. Additionally, I have incorporated the secret in the Dockerfile as follows:
```
RUN --mount=type=secret,id=SECRET_TOKEN \
 SECRET_TOKEN=$(cat /run/secrets/SECRET_TOKEN) &&\
 echo $SECRET_TOKEN | az devops login --organization https://dev.azure.com/***** &&\
 az artifacts universal download --organization "https://dev.azure.com/*****/" --feed "thirdparty" --name "****" --version "0.2.1" --path ~/perception
```
Occasionally, the image is created successfully, and the Visual Studio Code configuring step is completed. However, there are instances where the dev containers step fails with the following error message:

> cat: /run/secrets/SECRET_TOKEN: No such file or directory

I attempted to resolve this issue by reinstalling Visual Studio Code, which temporarily fixed the problem. Unfortunately, the issue has resurfaced several times without any changes to the code.

Could you please provide guidance on the correct way to pass secrets to Docker using devcontainer? Additionally, any insight into potential errors in my current implementation would be greatly appreciated.

Thank you very much for your time and assistance.

**Comment by DVRM** [comment]
I want to emphasis the issue is only on devcontainer. when trying to run the initial command on terminal- the container is running properly

**Comment by DVRM** [comment]
I found the cause to my issue:
 when I tried in terminal : docker buildx ls, I saw the buildx in use is docker-container driver. when **I changed it to use the default buildx** - the issue was fixed.

**Comment by bamurtaugh** [comment]
Thanks for all the details! It sounds like this is now resolved, so I'll close this out. If there's anything further, please just let us know.
