### ISSUE TITLE
[Remote - Tunnels] Server stops working after several hours

### ISSUE THREAD

**Issue by johnw42** [microsoft/vscode-remote-release#8388]
- VSCode Version: 1.77.3 (local and remote)
- Local OS Version: Windows 11 Enterprise 22H2
- Remote OS Version: Windows 11 Enterprise 22H2
- Remote Extension/Connection Type: tunnel server

- Server log: [remote-tunnel-service-log.txt](https://github.com/microsoft/vscode-remote-release/files/11275601/remote-tunnel-service-log.txt)
- Local error message:
![image](https://user-images.githubusercontent.com/201923/233146075-64aa12fa-4e70-4e07-8b47-6534882ed345.png)

Steps to Reproduce:

1. Start the server. I'm doing it by opening a VS Code instance over an RDP connection with remote tunnel access enabled, but I get similar results when I run `code-server.exe`.
2. Connect to the remote server. I'm know if this step is necessary for the server to start misbehaving, but it's what I always do since connecting a client is the point.
3. Leave clients connected for several hours. Eventually the client will disconnect, and it will be impossible to reconnect or connect another client.

Does this issue occur when you try this locally? no
Does this issue occur when you try this locally and all extensions are disabled? It happens when I disable everything but the Tunnel extension on the local side.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/178316
