### ISSUE TITLE
Using system windows variables when configuring the path to the ssh key (IdentityFile)

### ISSUE THREAD

**Issue by avraam-inside** [microsoft/vscode-remote-release#8389]
I have an ssh-key and i maked a windows environment variable (`PATH_DEVELOPMENT_DIR = c:\path\to\some\dir`). 

For example, this command in the **cmd** and **Windows Terminal** is correct: 
```
ssh -i %PATH_DEVELOPMENT_DIR%\store_ssh_keys\private.ppk -t <user>@<host> "cd /opt && exec bash -l"
```

But i cant use this variable in config-file for **VsCode remote-ssh** extension (in `IdentityFile`) - only a full handle-written path. Its a problem. 
Please add support of using system variables in config file for ssh connections.

**Comment by roblourens** [comment]
So you are adding this config to your ssh config file, and setting that with `IdentityFile`? First, I don't know whether environment variables are supported there in an ssh config. Does it work when you connect manually using that ssh config?

vscode doesn't interpret your ssh config file- we only run ssh, and ssh does. If it works in your own terminal but not vscode that implies that the variable is not set in the environment in which you started vscode.

**Comment by avraam-inside** [comment]
So you are adding this config to your ssh config file, and setting that with IdentityFile?

No, not like that.

I add the IdentityFile configuration to the config file (with which the Vs Code -> Remote SSH extension works) - the path to the SSH file.

![image](https://user-images.githubusercontent.com/52919010/233573958-b3231422-b155-4e7b-a343-bced593dff96.png)

The REMOTE-SSH extension for some reason does not use the system variable "%PATH_DEVELOPMENT_DIR%", although it exists in the system and works on other scripts.

It is needed a revision on your side so that the extension works with system variables.

**Comment by roblourens** [comment]
It sounds like you are doing what I described, I don't understand how that's different. But I understand now.

vscode doesn't interpret the config or read environment variables- all we do is run an `ssh` command and ssh does the rest. Does this work when you run `ssh servername` in a terminal?

**Comment by avraam-inside** [comment]
Yes, the command to connect to `server.com` over ssh, specifying the path through the system variable in the terminal works.

My request is simple - the file is being searched in the system, the path to the file could also be run in the system, system will sort itself out.

It would be great if this was ever implemented.

**Comment by roblourens** [comment]
Like I said, vscode doesn't interpret the ssh config, only ssh does. Without more details, the most likely problem is that your vscode environment doesn't have that environment variable set
