### ISSUE TITLE
VSCode SSH Issue, continually asking for password

### ISSUE THREAD

**Issue by mharrill** [microsoft/vscode-remote-release#8390]
```
> Acquiring lock on /run/user/83630/vscode-remote-lock.xxxxxx.704ed70d4fd1c6bd63
> 42c436f1ede30d1cff4710
> Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFloc
> k setting
```

You can delete that file manually on the remote or try changing the setting

_Originally posted by @roblourens in https://github.com/microsoft/vscode-remote-release/issues/8383#issuecomment-1513600440_

I have tried to manually delete the file, update vscode, toggle the setting, delete the full file path and try to connect to the remote host again, but to no success.

**Comment by roblourens** [comment]
No need to open a new issue, we can continue in the previous issue
