### ISSUE TITLE
opensshremotes.openEmptyWindow not found

### ISSUE THREAD

**Issue by osmancoskun** [microsoft/vscode-remote-release#8394]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### ->

![image](https://user-images.githubusercontent.com/44034936/233377467-caeeb8c1-28ca-403e-93a1-30bb7084e327.png)

I got this message whenever i try to troubleshoot.

### Expected Behavior

Working remote connection.

### Remote-SSH Log

this is all i got.
[16:10:31.623] Log Level: 2

### Anything else?

I cant even open configuration file. So i dont have any idea how can i post some logs or other kind of information with you. 
Here is steps that i followed.
Downloaded extension from website.
Installed manually from vsix file. 
Tried to connect to host.

My development system.
OS: Arch Linux x86_64 
Kernel: 6.2.11-arch1-1 
Shell: zsh 5.9 
Resolution: 1920x1080, 2560x1440 
DE: GNOME 43.4 
Terminal: gnome-terminal 
CPU: Intel i9-9900 (16) @ 5.000GHz 
GPU: NVIDIA GeForce GTX 1060 6GB 
Memory: 4200MiB / 15928MiB 
gcc (GCC) 12.2.1 20230201

**Comment by roblourens** [comment]
Are you using an official release build of vscode? I have had this reported in the past and it has been due to people using vscodium or another unsupported configuration

**Comment by osmancoskun** [comment]
using open source build of vscode. currently its from AUR. not vscodium
here is link for AUR repo
https://archlinux.org/packages/community/x86_64/code/
currently arch linux is not officially supported. there are bunch of tutorials but i didnt test them so far.

**Comment by roblourens** [comment]
Ah yes I see that in your screenshot, didn't notice it before.

Code - OSS is not supported in that scenario.
