### ISSUE TITLE
Frozen dev container with node process CPU usage at 100% 

### ISSUE THREAD

**Issue by ddahan** [microsoft/vscode-remote-release#8395]
My dev container quickly becomes unusable after starting it.
At the beginning (after the container has been built/open), everything seems to be fine.
But at some point in time after using it (not doing a specific action, just file editing and saving), the whole interface becomes of frozen with every action hanging.

Running a `htop` command on this container, I notice one of my 4 CPU cores is stuck at 100% usage, because of a node process:

<img width="1997" alt="image" src="https://user-images.githubusercontent.com/1933516/233384715-5d1d5fb1-f3c7-4378-8284-250e4407e9fd.png">

When this happens, I can do nothing except closing the connexion and reopening it, or rebuild the container. Then a few seconds or minutes later, the problem happens again.

Any idea how to debug this?

### Additional notes
- I'm using VS Code 1.77.3 on mac OS 13.3.1
- Bug tested with node 16, 17, 18, 19.
- The problem on this container is pretty new, so I suspect an extension or local package upgrade to cause it
- I found a [similar issue](https://github.com/microsoft/vscode/issues/101080) but related to WSL
- I run the `show running extensions` and don't notice something wrong

Thanks.

**Comment by ddahan** [comment]
Seems to be related to Prettier-vscode extension.
This issue can be closed.

**Comment by bamurtaugh** [comment]
Thanks for the update!

**Comment by ddahan** [comment]
To be more accurate, it was because of this plugin: https://github.com/tailwindlabs/prettier-plugin-tailwindcss
Uninstalled and everything is fine by now.
