### ISSUE TITLE
Standardize windowing behavior from Remote Explorer view

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-release#8397]
Part of https://github.com/microsoft/vscode/issues/178854

All remotes which contribute views to the remote explorer currently offer different ways to open a remote in a current or new window. Ideally we would offer the same options across all our remotes to reduce hesitation when choosing to open a remote.

| Remote view | Open in current window | Open in new window |
| -- | -- | -- |
| <img width="400" alt="image" src="https://user-images.githubusercontent.com/30305945/233434447-b2eab14c-8a73-4c5a-82c9-a387d9d90f92.png"> | ❌ | ✅ |
| <img width="391" alt="image" src="https://user-images.githubusercontent.com/30305945/233434613-fcb175bc-8084-4cbf-ad43-0ce205516295.png"> | ✅ (uses right arrow instead of window codicon) | ✅ |
| <img width="396" alt="image" src="https://user-images.githubusercontent.com/30305945/233434898-765277b1-74a3-45ce-8c92-4fe8ae5c0175.png"> | ✅  | ✅ (available with alt modifier in inline actions) |
| <img width="389" alt="image" src="https://user-images.githubusercontent.com/30305945/233435082-18c4cf6a-b6ad-408a-a976-c0ce29e29d30.png"> | ✅ (uses folder codicon instead of window codicon) | ❌ |
| <img width="388" alt="image" src="https://user-images.githubusercontent.com/30305945/233435543-cf667ff2-946c-4b7f-8fd8-fb97b642cb36.png"> | ✅ | ✅ (not available in inline actions) |

Proposal:
- Always give the user the option to choose between using the current window and the new window
    - Suggestion 1: Offer one inline action and use alt modifiers, this is done by setting a command ID in the `alt` property for a command contributed to `view/item/context` (only Remote Repos does this today):
      ![image](https://user-images.githubusercontent.com/30305945/233437377-6e0adf93-2bf2-465d-8434-b5e046e11812.png)

    - Suggestion 2: Offer two inline actions (one for opening in current and another for opening new window)
    - Suggestion 3: Only offer one option (open in current or open in new window)
- Use common codicons so that user doesn't need to hover to know what the action will do
    - `$(window)` for current window, `$(empty-window)` for new window
- State location in the command name so that it's unambiguous what location will be used
    - E.g. Remote Repos and Containers should have 'Open in Current Window' and 'Open in New Window'

**Comment by joyceerhl** [comment]
cc for feedback: @aeschli @chrmarti @connor4312 @eleanorjboyd @roblourens

**Comment by bamurtaugh** [comment]
Thanks so much for putting this together @joyceerhl! 

> Suggestion 2: Offer two inline actions (one for opening in current and another for opening new window)

I like this option to help avoid limiting users to just one path.

**Comment by joyceerhl** [comment]
I just noticed that in the Ctrl+R recent list, the ctrl modifier means new window while the alt modifier means to use the same window:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/30305945/233459484-a9358091-0550-4de1-89ef-ed2a7459106c.png">

Remote Repositories currently uses the alt modifier to denote a new window, and I wouldn't want to change the default action for Remote Repositories just to align with the recent list...so +1 for standardizing on two inline actions.

**Comment by roblourens** [comment]
We also have the setting `window.openFoldersInNewWindow` which sets a default for whether the window is reused when opening a folder. I can't tell you exactly why we went the totally explicit route instead of trying to match folder opening behavior... I think that we were thinking of opening remotes as just being a sort of different thing than opening a folder?

Also I don't think it's an issue if alt in the open recent picker works differently than an alt-action on a menu button, to me they are different things.

I'm fine with 1 or with 2. If it's 1, then both options should show up in the context menu too

**Comment by aeschli** [comment]
Same with WSL. The `Connect to WSL` command is following the setting `window.openFoldersInNewWindow`. Should I remove that behavior in favor of having two commands?

**Comment by joyceerhl** [comment]
@aeschli when I have `"window.openFoldersInNewWindow": "off"`, the action from the WSL remote explorer view still opens the distro in a new window: 
![Uploading image.png…]()

**Comment by joyceerhl** [comment]
I think for SSH it makes sense that you do not currently observe `"window.openFoldersInNewWindow"` because in my experience when you first connect to the SSH remote there isn't an initial folder open, instead it's an empty remote window. WSL appears to be the same.

**Comment by joyceerhl** [comment]
Moving this out to May so I can get input from all remote owners on this issue.

**Comment by bamurtaugh** [comment]
Here's a related issue on this topic: https://github.com/microsoft/vscode-remote-release/issues/8356

**Comment by aeschli** [comment]
> when I have `"window.openFoldersInNewWindow": "off"`, the action from the WSL remote explorer view still opens the distro in a new window

Ok you are right, I didn't realize that. On the distro item, it's currently a `force new window`. On recent folders, it's the setting.

I'm not a big fan of the setting (`window.openFoldersInNewWindow`) as few users know about it. But on the other hand, it's (consistently) followed by the workspace commands like open folder, open recent and I'm a huge fan of consistency :-)

**Comment by joyceerhl** [comment]
I'd suggest that we offer both options (open in current window, open in new window) for the remote explorer (inline as well as context menu), as I wouldn't want to take away functionality for the remotes which already offer the ability to do both. What do you think @aeschli?

**Comment by chrmarti** [comment]
That's what Remote-SSH currently does which I like for being very clear. It does take some space, but I think it's still a good trade-off as a user setting can't cover that you don't always want the same behavior and the modifier keys tend to be too subtle for new users. (Consistency with modifier keys where we support them would still make sense though.)

**Comment by aeschli** [comment]
Sounds good. So to summarise, for the remote explorer context menu we add two commands that are explicit, and we do not use the `window.openFoldersInNewWindow` setting .

**Comment by eleanorjboyd** [comment]
agreed that I think we should maintain both options (open in current window, open in new window) so this sounds good to me. Thanks!

**Comment by joyceerhl** [comment]
Closing this issue as it looks like Containers, WSL and Remote Repos have updated windowing behavior in the remote explorer and SSH/Tunnels has no changes required. Thank you everyone!
