### ISSUE TITLE
Allow selection of devcontainer config for local dev as well

### ISSUE THREAD

**Issue by tfenster** [microsoft/vscode-remote-release#8399]
In repos with multiple devcontainer configurations, I can select the configuration that I want to use when creating a codespace

![image](https://user-images.githubusercontent.com/15346084/233502818-25f456ca-ecfb-45bd-a6cc-880404b33edd.png)

But for development in a local devcontainer, that isn't possible. It would be great to have that option as well

@bamurtaugh As discussed today :)

**Comment by bamurtaugh** [comment]
Thanks so much for filing @tfenster! @chrmarti confirmed you should be able to pick the config when using a local folder in the Dev Containers extension, but “Clone in volume” is still missing that behavior. With this in mind, could you share a bit more about what steps you're trying and what you're seeing?

**Comment by tfenster** [comment]
Exactly, I do a "clone in volume" and then used to end up with a generic devcontainer, if I remember correctly. Now I tried again and it looks like the extension now picks the first config that it can find and copies it into a new devcontainer.json? But I also tried the experience with a local folder and that would indeed solve my problem. Could it be possible to integrate that into the "clone in volume" experience?

Somewhat related: In the same repo, I also have two workspace files, similar to the two devcontainer configs. Can I somehow pick the workspace file and the devcontainer.json to open that workspace in a devcontainer with that config? Currently, I always have to open the devcontainer and then pick the workspace and reopen. It would be nice if I could do that in one step

**Comment by bamurtaugh** [comment]
Thanks so much for the clarification!

I think this can be a new feature request to track this selection support for Clone in Volume - @chrmarti let me know if there's another spot we're already tracking this I may be forgetting.

And thanks for sharing the related request. I think that could be covered by https://github.com/microsoft/vscode-remote-release/issues/3665 - let me know if you have other thoughts.

**Comment by bamurtaugh** [comment]
Actually, I realize the first request is covered by https://github.com/microsoft/vscode-remote-release/issues/7879 - @tfenster it'd be great if you could share your feedback in there!

@tfenster if you agree both of the linked issues address your requests, I think we can close this issue.

**Comment by tfenster** [comment]
@bamurtaugh Those two indeed look good although #7879 is a bit light on explanation :) But I agree, both scenarios should be covered, so I'll close this one
