### ISSUE TITLE
Cannot debug Vue recipe webapp remotely on Windows

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#840]
Testing #754 

See attached debug log.

Remote: Azure Linux VM
Client: Windows 10

Followed these instructions: https://github.com/Microsoft/vscode-recipes/blob/master/vuejs-cli/README.md

Breakpoints will not verify.

[vscode-chrome-debug.txt](https://github.com/microsoft/vscode-remote-release/files/3332253/vscode-chrome-debug.txt)

**Comment by sbatten** [comment]
Fails locally as well but with some different information: 
[vscode-chrome-debug.txt](https://github.com/microsoft/vscode-remote-release/files/3332267/vscode-chrome-debug.txt)

**Comment by roblourens** [comment]
One remote-specific issue is that workspaceRoot is resolved correctly by the extension but workspaceFolder is not.

**Comment by roblourens** [comment]
Fix pushed but I will publish the extension tomorrow morning.
