### ISSUE TITLE
[Remote-SSH Bug]: SSH connections left open after close until VSCode itself has terminated

### ISSUE THREAD

**Issue by tomqwpl** [microsoft/vscode-remote-release#8402]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

I expect that having "closed" the SSH connection, the ssh.exe process is terminated. Perhaps my expectation is incorrect.

### Steps To Reproduce

The vscode version I'm using is 1.77.3, on Windows 11. 
The same behaviour occurs on the latest Insiders version.

To reproduce:
1. Start VSCode
2. Connect to a remote server using SSH
3. Do this multiple times, so you have multiple VSCode windows open each of which is connected to the same SSH server (doesn't matter that it's the same one, you just need multiple windows each connected to an SSH server). You should also still have the original starting VSCode window.
4. Using Windows task manager or preferably process explorer (https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer) to find the executables that are running.
5. Close down all of the "SSH" VSCode windows, leaving the original "local" VSCode window
6. Note that all of the SSH executables are still running in Process Explorer/Task Manager:
![Screenshot 2023-04-21 141139](https://user-images.githubusercontent.com/42344626/233646292-704925cc-0f61-4270-a23a-8f69a4b8dc71.png)

The above shot is taken when the only VSCode window open is an empty "local" VSCode window. I had opened, and then closed two "remote ssh" VSCode windows.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[14:21:19.930] Log Level: 2
[14:21:19.948] Picking SSH host
[14:21:19.951] VS Code version: 1.77.3
[14:21:19.951] Remote-SSH version: remote-ssh@0.100.0
[14:21:19.952] win32 x64
[14:21:21.432] Selected linux-el8-dev
[14:21:37.828] Picking SSH host
[14:21:38.928] Selected linux-el8-dev

```

</p>
</details>

**Comment by roblourens** [comment]
This is https://github.com/microsoft/vscode-remote-release/issues/7642. But you should be able to work around it by setting the `useLocalServer` setting to false
