### ISSUE TITLE
Test: Experimental Dev Container Lockfile

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#8403]
Refs: https://github.com/microsoft/vscode-remote-release/issues/8330

- [ ] anyOS @DonJayamanne 
- [x] anyOS @rzhao271
- [x] anyOS @alexr00 
- [x] anyOS @hediet

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%238403%0A%0A&assignees=chrmarti)

---

- Install the latest Dev Containers extension (>=0.291.0-pre-release).
- Enable "dev.containers.experimentalLockfile" in the user settings.
- Create a dev container with a few container features.
- Verify a `devcontainer-lock.json` is created next to the `devcontainer.json`.
- Verify that the lockfile locks the feature version by manually modifying the lockfile:
  - First change the feature reference in the devcontainer.json to install an earlier version of a feature (the lockfile will tell you what the latest version is).
  - Change the feature version in the devcontainer.json to be less specific (drop patch or patch and minor version).
  - Change the version in the key for this feature in the lockfile to the same less specific version.
  - Rebuild the dev container and verify that the older version registered in the lockfile is used.
  - Cross check: Remove the lockfile and rebuild the dev container to check that again the later version of the feature is used.
- Change one of the integrity digests in the lockfile to simulate a tampered feature and verify a rebuild of the dev container fails with an error message.

**Comment by DonJayamanne** [comment]
@chrmarti I'm sorry, but I'm not sure how i should test this.
I'm not sure how i can test installing an older version of the feature to verify the TPI
E.g. I've got an node container and I have the gulp, mocha and typescript features, however I'm not sure I can verify that changing the versions will in fact install some older version of the same feature (as in both cases the version of mocha, gulp and ts are the same)
 
Can you provide more instructions or a dev container and set of features I can use to test this. thanks

**Comment by sandy081** [comment]
Closing this as it is well covered. Hence I am closing this.

@chrmarti Please respond to @DonJayamanne after back as he is interested to test and learn this functionality.

**Comment by sandy081** [comment]
@alexr00 / @hediet Since you could successfully test this item, can you please help @DonJayamanne to unblock and test this?

**Comment by rzhao271** [comment]
I took the item for now

**Comment by sandy081** [comment]
Reopening this, since @rzhao271 volunteered for now.

Also added @DonJayamanne back, he expressed interest to test this feature and know this functionality.

@rzhao271 If you can successfully test this, can you please unblock him?

**Comment by DonJayamanne** [comment]
> verify that the older version registered in the lockfile is used.

This is what is confusing.
Is the step simple as chekc if the lock file got updated, if thats the case then fine
But then I guess it should instead read `verify the lock file is updated with the older version` 

I.e. how can i verify the old version is used in the container? E.g. if i install an old version of the gulp feature then how do i know the old version of that feature is used.

@alexr00 @hediet perhaps you can shed some light on how you verified this.

**Comment by alexr00** [comment]
I just checked that the lock file was updated properly.

**Comment by chrmarti** [comment]
> > verify that the older version registered in the lockfile is used.
> 
> This is what is confusing. Is the step simple as chekc if the lock file got updated, if thats the case then fine But then I guess it should instead read `verify the lock file is updated with the older version`

Sorry for being imprecise, ensuring that the lockfile doesn't change is the best check at the moment. I'll open an issue to improve the log output.

Thanks everyone!
