### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by ChenJunzhi-buaa** [microsoft/vscode-remote-release#8406]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

VScode remote terminal commands cannot be logged to the history of the remote server, while commands runs in ssh of cmd can be logged to the history of the remote server.

This issue happened on all my servers. 

### Expected Behavior

VScode remote terminal commands should be logged to the history of the remote server.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by roblourens** [comment]
Sorry, I don't understand the issue, please describe in detail

**Comment by ChenJunzhi-buaa** [comment]
![image](https://user-images.githubusercontent.com/77711950/234768776-1df1e4af-fc61-42b2-bf18-615c733d3b44.png)

The command I run in shell of VScode can not be saved to history command.
If I killed the shell, all the latest command I run in the shell would be lost.

This doesn't appear if I connect to the remote by the command prompt or powershell of Windows. That's to say, If I killed the powershell, all the latest command I run in the powershell would be saved to the history of the remote. Therefore, I am sure it's the problem of VScode remote extension. 

What's more, there is no the issue several months ago.

**Comment by roblourens** [comment]
I see, sorry, but this would be some issue with your configuration. Shell history works differently on different types of shells.

**Comment by ChenJunzhi-buaa** [comment]
> I see, sorry, but this would be some issue with your configuration. Shell history works differently on different types of shells.

Can you help me about how to set configuration？
I really don‘t know what’s the problem.
I have tried to reinstall a clean VScode, but it dosen't work.
