### ISSUE TITLE
The python plug-in failure problem of the same account on different machines

### ISSUE THREAD

**Issue by 1193700079** [microsoft/vscode-remote-release#8407]
Type: <b>Bug</b>

I remotely connect to the server C on the A machine and install the python plug-in
Then connect to the server C remotely on the B machine and install the python plug-in, it will fail

Extension version: 2023.6.1
VS Code version: Code 1.76.2 (Universal) (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:54:09.061Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No
Connection to 'ssh-remote+10.1.16.214' could not be established
Connection to 'ssh-remote+10.1.16.73' could not be established
Connection to 'ssh-remote+10.1.16.73' could not be established
Remote OS version: Linux x64 4.15.0-142-generic
Connection to 'ssh-remote+10.1.16.73' could not be established
Connection to 'ssh-remote+www.heitong.site' could not be established
Remote OS version: Linux x64 5.19.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 3c32c582-32a7-4166-96f3-7e0f7b7b75c1|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+10.1.16.214' could not be established

Connection to 'ssh-remote+10.1.16.73' could not be established

Connection to 'ssh-remote+10.1.16.73' could not be established

|Item|Value|
|---|---|
|Remote|SSH: 10.1.16.73|
|OS|Linux x64 4.15.0-142-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (48 x 1200)|
|Memory (System)|251.78GB (240.03GB free)|
|VM|0%|

Connection to 'ssh-remote+10.1.16.73' could not be established

Connection to 'ssh-remote+www.heitong.site' could not be established

|Item|Value|
|---|---|
|Remote|SSH: 10.1.16.214|
|OS|Linux x64 5.19.0-38-generic|
|CPUs|AMD EPYC 7642 48-Core Processor (96 x 1500)|
|Memory (System)|125.64GB (112.40GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
vscrpc:30673769
pythonsymbol12:30671437
2i9eh265:30646982
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743

```

</details>

**Comment by bamurtaugh** [comment]
@sandy081 any thoughts on this one?

**Comment by sandy081** [comment]
Not sure.

@1193700079 What do you mean by

> Then connect to the server C remotely on the B machine and install the python plug-in, it will fail

What is failing? Is it extension installation or python functionality is not working?
