### ISSUE TITLE
[Remote-SSH Bug]: git is not recognized as an internal or external command (Windows 10)

### ISSUE THREAD

**Issue by hfmamh** [microsoft/vscode-remote-release#8415]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

I'm trying to run git on vscode terminal
![image](https://user-images.githubusercontent.com/51278148/234771266-b24f378a-b479-4690-b167-10837be221b0.png)

### Expected Behavior

Should initialize git repo (I've already installed it on both client and server)

### Steps To Reproduce

1. Connect to remote folder on server.
2. Open terminal
3. run "git init"

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

### Anything else?

Looks like it doesnt recognize any environment variables. Documentation didn't help to solve the problem: https://code.visualstudio.com/docs/remote/ssh#_ssh-hostspecific-settings

**Comment by roblourens** [comment]
git is not on your path here. That means that it is not installed, or there is an issue with your terminal configuration
