### ISSUE TITLE
The version 1.77.3 of VS Code does not load folder

### ISSUE THREAD

**Issue by derkmal** [microsoft/vscode-remote-release#8416]
The version 1.77.3 of VSCode does not load folder. How can I resolve this?

**Comment by eleanorjboyd** [comment]
Hello! Can you please elaborate on what extension you are using and describe this functionality more?

**Comment by derkmal** [comment]
Hi! Thank you for your attention. I installed the 1.57.0 version and disabled auto update to solve the issue. All the best!

**Comment by eleanorjboyd** [comment]
Great, happy coding! 🎉

**Comment by derkmal** [comment]
Thanks! You too!
