### ISSUE TITLE
Turn on remote tunnel in vscode from Windows UI with WSL

### ISSUE THREAD

**Issue by hcmlopes** [microsoft/vscode-remote-release#8418]
Type: <b>Feature Request</b>

When I use the UI option to turn on remote tunnel it initiates code-server from the windows host machine. However with WSL2 installed and all my code living there it would be nice if this feature would actually initiate the code-server instanted installed within WSL instead of requiring me to have to start that via cli.
This can probably cause some confusion with less experienced users.

Extension version: 1.1.0
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

**Comment by aeschli** [comment]
The next release has a feature that allowss to connect to a WSL distro through a tunnel to the Windows machine. In the beginning this is only for the web (vscode.dev)

**Comment by vkissoyan** [comment]
Is this somewhere that can be tested?

**Comment by chrmarti** [comment]
@vkissoyan There is a release note on this here: https://github.com/microsoft/vscode-docs/blob/vnext/remote-release-notes/v1_79.md#tunnels. HTH

**Comment by MujiSayed** [comment]
Gave this a shot but every wsl distro(both wsl v1/v2) i attempted to connect to resulted in the following error: 
```
The workbench failed to connect to the server (Error: Cannot resolve remote machine name!)
```

**Comment by chrmarti** [comment]
@MujiSayed Could you open an issue with the details on that? Thanks.

**Comment by bamurtaugh** [comment]
Thanks all for the feedback! Since this has been implemented, let's use follow up issues for subsequent requests or bugs as Christof suggested above. If there is still anything outstanding for this issue specifically though, please lmk, and I'm happy to reopen. Thanks so much!
