### ISSUE TITLE
Cannot SSH remote to raspberry pi anymore with [VSC] latest insiders version (with nightly extension)

### ISSUE THREAD

**Issue by n3rd4i** [microsoft/vscode-remote-release#842]
Issue Type: <b>Bug</b>

Trying to connect with Remote SSH Nightly extension on Raspberry PI fails with:
`product.json: Unexpected end of JSON input`

Extension version: 2019.6.35460
VS Code version: Code - Insiders 1.36.0-insider (b7265738444f1eee05762341b4361ee6452a4154, 2019-06-27T05:22:06.378Z)
OS version: Windows_NT x64 10.0.18362
Fetching remote diagnostics for 'SSH' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.43GB (2.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed.
</details>

**Comment by egamma** [comment]
// @joaomoreno I suspect this is a consequence of only building Pi for insiders?

**Comment by joaomoreno** [comment]
Not sure. @n3rd4i Can you share the full log where the error occurs?

**Comment by n3rd4i** [comment]
Link to the full [log](https://gist.githubusercontent.com/n3rd4i/351f5e77c34a2af13749cf6b4cae724d/raw/3702918cdb8cf5ae94643015971813c3039d21e6/vsci_ssh_e_nightly.log).

**Comment by n3rd4i** [comment]
this was fixed some time ago, will close
