### ISSUE TITLE
Adding ssh host with identify file at path with backslashes adds host without backslashes in identity file path

### ISSUE THREAD

**Issue by ironyman** [microsoft/vscode-remote-release#8421]
that is, using the add new SSH host command, it fails with this host
```
ssh -i C:\Users\ironyman\key.pem hostname
```
the config file is updated with this 
```
  IdentityFile C:Usersironymankey.pem 
```

**Comment by eleanorjboyd** [comment]
Hi! We parse the input to add host like bash so just put quotes around the identity file: `ssh -i "C:\Users\ironyman\key.pem "hostname`, thanks
