### ISSUE TITLE
remoteUser uses wrong UID/GID

### ISSUE THREAD

**Issue by zljubisic** [microsoft/vscode-remote-release#8424]
Type: <b>Bug</b>

I will explain

Extension version: 0.288.1
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux arm64 5.15.84-v8+
Connection to 'SSH: rpi4' could not be established  Canceled
Connection to 'SSH: rpi4' could not be established  Canceled
Connection to 'ssh-remote+rpi4' could not be established
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux arm64 5.15.84-v8+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.70GB (2.06GB free)|
|Process Argv|--crash-reporter-id 20867a71-86e7-4099-b6a3-86f70c6c2d10|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|7.61GB (5.19GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Existing Dockerfile @ ssh://rpi4|
|OS|Linux arm64 5.15.84-v8+|
|CPUs|Cortex-A72 (4 x 1800)|
|Memory (System)|7.63GB (5.88GB free)|
|VM|0%|

Connection to 'SSH: rpi4' could not be established  Canceled

Connection to 'SSH: rpi4' could not be established  Canceled

Connection to 'ssh-remote+rpi4' could not be established

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|7.61GB (5.19GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|7.61GB (5.19GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|7.61GB (5.19GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: rpi4|
|OS|Linux arm64 5.15.84-v8+|
|CPUs|Cortex-A72 (4 x 1800)|
|Memory (System)|7.63GB (5.88GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
vscrpc:30673769
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30672706
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30716742

```

</details>

**Comment by roblourens** [comment]
Please do

**Comment by zljubisic** [comment]
@roblourens  It is a duplicate, please delete this issue.
