### ISSUE TITLE
remoteUser uses wrong UID/GID

### ISSUE THREAD

**Issue by zljubisic** [microsoft/vscode-remote-release#8425]
Type: <b>Bug</b>

I have a Dockerfile in which docker_user is created with UID/GID=818:

```
ARG APP_NAME=docker_perm
ARG USER=docker_user
ARG UID=818
ARG GID=818

ARG PYTHON_VERSION=3.7.16

FROM python:$PYTHON_VERSION-slim

ARG APP_NAME
ARG USER
ARG UID
ARG GID

RUN set -eux; \
    groupadd -r $USER --gid=$GID; \
    useradd -r -g $USER --uid=$UID --shell=/bin/bash $USER; \
    mkdir -p /home/$USER; \
    chown -R $USER:$USER  /home/$USER

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONFAULTHANDLER=1 \
    PYTHONHASHSEED=random

WORKDIR /$APP_NAME
RUN chown -R $USER:$USER /$APP_NAME



USER $USER

RUN whoami

COPY --chown=$USER:$USER . ./
RUN export


ENTRYPOINT ["python"]
CMD ["main.py"]

```

and a main.py in the same directory:

```
import datetime as dt

file = 'data/test_file.txt'

print('original file:')
with open(file, 'r') as f:
    print(f.read())

print('adding dt.datetime.now()')
with open(file, 'w') as f:
    f.write(str(dt.datetime.now()))

print('re-reading the file')
with open(file, 'r') as f:
    print(f.read())

```

I also created a devcontainer.json file:

```
	{
		"name": "Existing Dockerfile",
		"build": {
			"context": "..",
			"dockerfile": "../Dockerfile",

		},
		"workspaceMount": "source=${localWorkspaceFolder},target=/docker_perm,type=bind",
		"workspaceFolder": "/docker_perm",
		"mounts": [
			"source=/home/pi/tmp/docker_perm/data,target=/docker_perm/data,type=bind,consistency=cached"
		  ],
		"customizations": {
			"vscode": {
				"extensions": [
					"ms-python.python"
				]
			}
		},
		"remoteUser": "docker_user"
	}

```

On my host machine there is a docker_user with UID/GID=818:

```
pi@rpi4:~/tmp/docker_perm $ id docker_user
uid=818(docker_user) gid=818(docker_user) groups=818(docker_user)
```

data folder uses that `docker_user` for owner/group:

```
pi@rpi4:~/tmp/docker_perm $ ls -l
total 12
drwxr-xr-x 2 docker_user docker_user 4096 Apr 30 12:06 data
-rw-r--r-- 1 pi          pi           626 Apr 30 12:21 Dockerfile
-rw-r--r-- 1 pi          pi           300 Apr 30 12:05 main.py

pi@rpi4:~/tmp/docker_perm $ ls -l data
total 4
-rw-r--r-- 1 docker_user docker_user 16 Apr 30 12:06 test_file.txt
```

We could say that on the host, data folder is owned by docker_user whose UID/GID=818.
This data folder is mounted in devcontainer.json.
In devcontainer.json remoteUser="docker_user".

I would have expected that in the devcontainer there is a docker_user (created in Dockerfile) with UID/GID=818, but from dev container UID/GID=1000 not 818:

```
docker_user@a2ff58e56c2d:/docker_perm$ whoami
docker_user
docker_user@a2ff58e56c2d:/docker_perm$ id docker_user
uid=1000(docker_user) gid=1000(docker_user) groups=1000(docker_user)
docker_user@a2ff58e56c2d:/docker_perm$ 
```

Because of that, if I run main, I get:

```
docker_user@a2ff58e56c2d:/docker_perm$ /usr/local/bin/python /docker_perm/main.py
original file:
initial content

adding dt.datetime.now()
Traceback (most recent call last):
  File "/docker_perm/main.py", line 10, in <module>
    with open(file, 'w') as f:
PermissionError: [Errno 13] Permission denied: 'data/test_file.txt'
docker_user@a2ff58e56c2d:/docker_perm$ 
```

What I need to do in order to have `docker_user` inside of dev container with UID/GID=818?

Extension version: 0.288.1
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux arm64 5.15.84-v8+
Connection to 'SSH: rpi4' could not be established  Canceled
Connection to 'SSH: rpi4' could not be established  Canceled
Connection to 'ssh-remote+rpi4' could not be established
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux arm64 5.15.84-v8+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.70GB (1.91GB free)|
|Process Argv|--crash-reporter-id 20867a71-86e7-4099-b6a3-86f70c6c2d10|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|7.61GB (5.19GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Existing Dockerfile @ ssh://rpi4|
|OS|Linux arm64 5.15.84-v8+|
|CPUs|Cortex-A72 (4 x 1800)|
|Memory (System)|7.63GB (5.97GB free)|
|VM|0%|

Connection to 'SSH: rpi4' could not be established  Canceled

Connection to 'SSH: rpi4' could not be established  Canceled

Connection to 'ssh-remote+rpi4' could not be established

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|7.61GB (5.19GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|7.61GB (5.19GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|7.61GB (5.19GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: rpi4|
|OS|Linux arm64 5.15.84-v8+|
|CPUs|Cortex-A72 (4 x 1800)|
|Memory (System)|7.63GB (5.97GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Try adding `"updateRemoteUserUID": false` to your devcontainer.json. Does that help?

**Comment by zljubisic** [comment]
@chrmarti It works, thanks. 
Still, I am investigating the case a bit.
Please keep this issue open for some time.

**Comment by zljubisic** [comment]
Everything is OK now. Thanks.
