### ISSUE TITLE
DnD file from remote file explorer to desktop

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#843]
I don't have a reproducible case yet but I observed the following repeatedly:

1) connect to a SSH box and open a non-empty workspace there
2) open file explorer
3) select `.txt` file and drag it into the macOS finder

-> file is copied
4) repeat 1-3 a few times
-> the file is created on macOS but no content is copied. I.e. file size == 0k

I have not seen this happening with any other app.

**Comment by isidorn** [comment]
I can try to reproduce, and you can let me know if you find reproducable steps. Thanks

**Comment by isidorn** [comment]
I can not reproduce. Here I am connecting from my mac to my linux VM via ssh
Please let me know if you are doing something differently or if you have better steps

![sshcopy](https://user-images.githubusercontent.com/1926584/60266867-3d043a80-98e9-11e9-9e5f-47e189f3728d.gif)

**Comment by isidorn** [comment]
Closing for now. Will reopen if Kai provides more info.
