### ISSUE TITLE
Ability to extend devcontainer.json

### ISSUE THREAD

**Issue by willwill96** [microsoft/vscode-remote-release#8430]
I have a lot of individual repos that use devcontainers at this point. I would like to have some partial `.devcontainer.json`  that can be used in my projects to define shared configuration across several of my applications. Things that I would like to see as extensible:
- `customizations` - I want to be able to set a default set of extensions that developers would get out of the box.
- `mounts` - I would like to define a docker volume for a shared npm cache across devcontainer files.

**Comment by chrmarti** [comment]
Tracking in https://github.com/devcontainers/spec/issues/22.
