### ISSUE TITLE
vs code-server fails to start with --port 0

### ISSUE THREAD

**Issue by Th3G4mbl3r** [microsoft/vscode-remote-release#8431]
I have located the problem, it was because I was using docker via tcp port on the remote host. This does not work with port 0 apparently. Removing that and doing the ssh tunnel with the docker socket fixed the issue.

It should probably be documented that the ssh step shown to do a forward of the docker socket is necessary, and using a remote docker via docker TCP does not work.

_Originally posted by @bbangert in https://github.com/microsoft/vscode-remote-release/issues/739#issuecomment-504239093_

@bbangert - can you share the steps or link to documentation on how you bypassed this issue? for me the step to get vscode-server started with switch --port=0 fails with complaint port not found. And i'm banging my head to understand what is going on...

**Comment by connor4312** [comment]
It works with the new `code serve-web`
