### ISSUE TITLE
"Connecting to" Toast message never disappears when connecting to a Tunnel

### ISSUE THREAD

**Issue by Ponjimon** [microsoft/vscode-remote-release#8432]
- VSCode Version: Version: 1.77.3 (Universal)
- Local OS Version: Darwin arm64 22.4.0

- Logs: (Not sure which logs are required here, please do tell me)

Steps to Reproduce:

1. Connect to a Tunnel
2. See that the notification toast never disappears

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

<img width="468" alt="Screenshot 2023-05-01 at 12 26 34" src="https://user-images.githubusercontent.com/770632/235441019-a9c3fbf3-9a7a-4103-bac8-5766577e90b1.png">

It connect successfully but the toast message never disappears

**Comment by gotham8x** [comment]
It keeps connecting on my machine and also on vscode.dev.
It seems there is an issue with 'wss://use-data.rel.tunnels.api.visualstudio.com'.

**Comment by mdonato-fn** [comment]
same here but I cannot see anything in the logs, they all seem right (both on the server and the extension)

**Comment by mdonato-fn** [comment]
it is a bit better now. It only shows in the status bar a the bottom so it is not a permanent pop up on the bottom right
The server window says 

`[2023-06-07 19:27:34] warn [rpc.2] error handling call: NoAttachedServerError(NoAttachedServerError)`

although the server seems to be working properly

**Comment by LittleDan9** [comment]
I’ve been plagued by this as well. Experienced this on the release and insiders endpoints. Tunnel does reconnect, but toast never disappears; I’ve had as many as three toasts at once.
Running on iPad and experiencing this across at least two different machines running `code tunnel` on Debian Linux. Running code versions 1.79.0 on one server and 1.79.2 on the other.
The only thing I see that stands out as an error in the servers outputs after reconnect is:
`error [tunnels::connections::relay_tunnel_host] error handshaking session: EOF`. I haven’t had time to dive in an see if this is related or not.

**Comment by SaneBow** [comment]
Same here. It is quite annoying. Anyone working on fixing this?

**Comment by aamarin** [comment]
Is this being looked at or considered? It gets in the way.

**Comment by Gowiem** [comment]
Anyone have a workaround while this bug is still taking up space? Using the terminal is partially broken due to this.

**Comment by mdonato-fn** [comment]
Apparently it is fixed now. I can confirm that after an update to the vscode cli I use in the tunnel I don't see the toast anymore after connection

**Comment by Gowiem** [comment]
Yeah, I'm seeing this fixed as well 👍

**Comment by mdonato-fn** [comment]
FYI it was closed here:
https://github.com/microsoft/vscode/issues/186345#event-9969679662

**Comment by mdonato-fn** [comment]
aaand it's back for me :D

**Comment by a-gn** [comment]
Not solved for me in VSCode 1.81. with Remote - Tunnels 1.3.0 on macOS.

**Comment by rile-musfin** [comment]
> Not solved for me in VSCode 1.81. with Remote - Tunnels 1.3.0 on macOS.

Me too on window, vscode 1.81 as well.

**Comment by connor4312** [comment]
Should be fixed nowadays
