### ISSUE TITLE
Remote file picker keeps picking files

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-remote-release#844]
verifying https://github.com/microsoft/vscode-remote-release/issues/4

* open picker
* navigate into a few folders
* press backspace and don't release
* you navigate to the root folder, release backspace
* :bug: look at the picker and notice how it updates a few times before it settles 

![Jun-27-2019 11-58-33](https://user-images.githubusercontent.com/1794099/60257220-54382d80-98d3-11e9-9294-32baa00013d8.gif)

**Comment by alexr00** [comment]
You should only see one extra folder pick now, which will get you into the final folder that you landed in.
