### ISSUE TITLE
"No WSL distros found" with WSL1 after upgrade to v0.78.4

### ISSUE THREAD

**Issue by Winniebear2** [microsoft/vscode-remote-release#8446]
Type: Bug

Update WSL extension to version 0.78.4. Then try to open my workspace in WSL1. The message prompt "No WSL distros found. New distros can be installed from the Microsoft Store."

But in fact my WSL1 works fine.

After I rolled back the vscode to 1.77.0 and the extension to 0.77.0. Everything works fine.

VSCode Version: 1.78.0
Local OS Version: Windows 10 Pro, 1909, 64bit, OS Build number = 18363.592
Remote OS Version: WSL1, Ubuntu-20.04

Version: 1.78.0 (user setup)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:09:00.748Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.18363
Sandboxed: No

**Comment by gotohx** [comment]
I had the same problem.
VSCode Version: 1.78.0
Remote OS Version: WSL1, Ubuntu-20.04

**Comment by iblincoeTAG** [comment]
I had the same issue, version 1.78.1. Reverting to 1.77.3 and uninstalling and reinstalling the WSL extension fixed it.

**Comment by resetsa** [comment]
+1
VSCode Version: 1.78.5
Remote OS Version: WSL1, Ubuntu-20.04

**Comment by aeschli** [comment]
Fixed in 0.78.9

**Comment by resetsa** [comment]
@TylerLeonhardt 
Yes, problem solved after update to 0.78.9
Thanks sir!
