### ISSUE TITLE
VS Code does not use configured settings for connecting to host machine

### ISSUE THREAD

**Issue by KyleDev008** [microsoft/vscode-remote-release#8453]
Everything has been working 100% reliably when connecting to remotes hosts for about 2 years straight, but suddenly a few weeks ago, I started noticing issues where VS Code would either not use my configured username when connecting to a host, or it would ignore my custom port for a host and use the default port 22, which is disabled on the live server that I manage.

My config file is structured exactly as outlined in the docs, which is why it was working previously, and nothing has been changed.

I've tried checking my host machines, and I can connect to them just fine using every other method like windows cmd, etc. It just doesn't work in VS Code and I can for the life of me not understand why.

Any clarification would be greatly appreciated, and please do let me know what details I need to supply in order for this issue to be addressed.

Thanks in advance!

**Comment by roblourens** [comment]
Please give some more specific details (what _exactly_ are you seeing) and include the log from the Remote-SSH output channel, thanks
