### ISSUE TITLE
不要什么都翻译成汉语

### ISSUE THREAD

**Issue by YSHIDM** [microsoft/vscode-remote-release#8456]
Type: <b>Feature Request</b>

希望有些专业词汇不要翻译成汉语，会看不懂的

Extension version: 0.292.0
VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.49-linuxkit

**Comment by wywzxxz** [comment]
such as ?
