### ISSUE TITLE
Stuck when trying to connect to VScode remote server

### ISSUE THREAD

**Issue by aks03dev** [microsoft/vscode-remote-release#8457]
I have been trying to connect to remote server using SSH and I have been stuck in this process.
I tried deleting the .vscode-server in the remote server(using terminal) but after that I am again stuck when trying to connect to the host
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/108564935/236829512-f862d749-8cc8-4dec-8586-44afafc50a3e.png">

**Comment by roblourens** [comment]
Please share the full log
