### ISSUE TITLE
cannot close remote connection to devcontainer, devcontainer workspace keeps re-loading in a loop

### ISSUE THREAD

**Issue by altsang** [microsoft/vscode-remote-release#8459]
- VSCode Version: 1.78.0 (Universal)
- Local OS Version: 13.3.1 (a) 
- Remote OS Version: Debian GNU/Linux 11 (bullseye)
- Remote Extension/Connection Type: Containers

- Logs: (see attached remoteContainers log)
[remoteContainers-2023-05-08T20-03-36.290Z.log](https://github.com/microsoft/vscode-remote-release/files/11425084/remoteContainers-2023-05-08T20-03-36.290Z.log)

- GIF Video
![2023-05-08_13-03-41 (1)](https://user-images.githubusercontent.com/2261105/236933355-d4fa6cec-e64b-4059-afcb-b16c8801ffd0.gif)

Steps to Reproduce:

1. run devcontainer through docker
2. attach to devcontainer in remote extension
3. try to close remote connection OR open another workspace

Expected behavior - unless the remote connection is re-established to the running devcontainer - it should not try to keep bringing up the remote workspace

**Comment by chrmarti** [comment]
@altsang Does this also happen when you disable all extensions except Dev Containers? (It looks like the `Close Remote Connection` command works, but then the empty window immediately reloads as a remote window again and I'm not aware of anything on our side that might trigger this.)

**Comment by altsang** [comment]
correct - the remote connection closes, but then the window immediately launches again - OR I pick another workspace to load and it does that - but then it immediately goes BACK to the devcontainer workspace, really interesting

so I have all my extensions disabled except for

1. Dev Containers
2. Docker
3. Remote - Tunnels
4. Remove Development

you were onto something - if I load up our Web3 container and its remote workspace and then close it - it closes just fine without any kind of window override.

When I went about disabling the extensions i did curiously notice one extension called Web3 devcontainer, I believe it was the extension that our team built for ConsenSys that did a bunch of automated actions on the advice that @isidorn and team gave us. What's weird is - I can no longer find that extension.

I'm going to re-enable the extensions one by one and see if I can find the culprit.  All my other extensions look very unrrelated and I've been using for years...

**Comment by altsang** [comment]
found the smoking gun - it was the web3 extension that the team built that automates those actions as referenced above for scaffolding. Thanks for your all your help!! 🙏

**Comment by isidorn** [comment]
@altsang thanks for letting us know 🙏  
So I will go ahead and close this issue.
