### ISSUE TITLE
Jupyter notebook not displaying python code

### ISSUE THREAD

**Issue by DominicPalaczky** [microsoft/vscode-remote-release#8462]
- VSCode Version: 

When opening an existing notebook, or creating a new one, code within within cells will run and be editable, but the code itself is not visible. The code block will remain blank, even if code is in it. This only occurs when running in container, not otherwise, but might be a compatibility issue with the jupyter extension.

Steps to Reproduce:

1. Create a container, using python 3.11, python extensions
2.  Install jupyter notebook extension for kernel 
3. Create a .ipynb
4. Try to enter code, see that what is entered is not displayed

![Screenshot 2023-05-10 093228](https://github.com/microsoft/vscode-remote-release/assets/102159801/fca9a5ae-ae32-46b0-b56f-48aa17f650b5)

**Comment by chrmarti** [comment]
This works for me using the following devcontainer.json:
```json
{
	"image": "mcr.microsoft.com/devcontainers/base:bullseye",
	"features": {
		"ghcr.io/devcontainers/features/python": {
			"installJupyterlab": true
		}
	}
}
```

I then used `F1` > `Create: New Jupyter Notebook`.

Have you checked with a different color theme?
