### ISSUE TITLE
Disable download of remote files through a global server flag.

### ISSUE THREAD

**Issue by SuperFoxtrot** [microsoft/vscode-remote-release#8466]
It would be really great, if we can add a feature to disable download of files from remote server, through the use of some server flag. 

This essentially means, that users are able to connect to a remote server, and view / edit the files on the remote server, but are not able to download the files locally. Currently, a user can download the whole codebase without any restrictions.

**Comment by roblourens** [comment]
Why would it be helpful to let users read every file but not "download" them? To me there is not really a difference

**Comment by SuperFoxtrot** [comment]
For individual files, sure it is very easy to just copy the whole content
manually. But this would create a barrier for the user, to just download
the whole codebase in just 1 click. Currently downloading the whole
codebase is just a few clicks affair.

**Comment by SuperFoxtrot** [comment]
Also, currently due to this ability, VS code is blocked in my org, but if the admin had the ability to prevent downloads for the users that are connecting the remote server then we could use VS Code with Remote SSH without any issues for our development

**Comment by roblourens** [comment]
That doesn't sound like a good security measure, making it slightly more inconvenient to do something that they can do anyway.

This doesn't fit into how vscode works- it requires ssh and shell access, so the user can mass-copy whatever files they want regardless of whether a button is disabled. We also don't have any way to actually read and enforce some kind of organization policy.
