### ISSUE TITLE
Remote SSH + Devcontainer hangs at build after Ubuntu upgrade

### ISSUE THREAD

**Issue by cbast** [microsoft/vscode-remote-release#8467]
Type: <b>Bug</b>

Setup: 
- Local host: Ubuntu 20.04
- Remote host (SSH): Ubuntu 22.04
- From VSCode running locally, connect to the Remote-SSH (Status: Good)
- From the Remote-SSH, select `Open in devcontainer` (This command never completes)

Result:
Logs from `Dev Containers` terminal (full):
```
[8548 ms] Dev Containers 0.292.0 in VS Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9).
[8547 ms] Start: Run: ssh tower2 /bin/sh
[8562 ms] Start: Run in host: id -un
```

This setup used to work, then I upgraded the Remote host from Ubuntu 20.04 to 22.04, and it does not work anymore.
The IP address also changed, I only had to change the IP in ~/.ssh/config (I don't think it is important).

What I tried:
- deleted all docker containers/images on the remote host (`docker system prune -a`)
- uninstalled the local's VSCode and reinstall it (through APT)
- uninstalled the remote's VSCode server from the remote host (through APT)
- removed the ~/.vscode* folders in the remote Host
- connected through the Tunnel  instead of SSH(which strangely, the tunnel still existed after I deleted VSCode server, maybe I am missing something).  In this case, the `Reopen in container` command is not available at all, and asks me to install docker, even though docker does works properly (I can pull images).

I would like to restore this functionality to the "factory default".  I don't mind loosing VSCode-related data (e.g. extensions & containers & settings).

What is the proper way to uninstall both vscode server & client sides, to start from fresh?
What are the next steps to isolate the issue?

Thanks :)

Extension version: 0.292.0
VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:46:23.602Z)
OS version: Linux x64 5.4.0-148-generic snap
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.0-71-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 2094)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 2, 1|
|Memory (System)|7.71GB (5.55GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id ef46f5ff-af95-4499-9b67-6e6d4c619fb5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: tower2|
|OS|Linux x64 5.15.0-71-generic|
|CPUs|Intel(R) Pentium(R) CPU G3258 @ 3.20GHz (2 x 800)|
|Memory (System)|7.64GB (6.38GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyonecf:30548226
vscccc:30610679
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
24365598:30736109
pythonfmttext:30731395
pythoncmv:30731968
fixshowwlkth:30730052

```

</details>

**Comment by chrmarti** [comment]
Does running `ssh tower2` in a terminal ask for a password or passphrase?
