### ISSUE TITLE
Stuck on "Öpening Remote..."

### ISSUE THREAD

**Issue by bangyogesh** [microsoft/vscode-remote-release#847]
- VSCode Version: 
Version: 1.35.0-insider
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T00:13:30.572Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.3.9600

- Local OS Version: Windows 8.1
- Remote OS Version: - Ubuntu 18.04 
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
1. Click on the Remote-SSH extension  
2. Click on the Host name (picked up from ~/.ssh/config)
3. It opens another window of VS-Code and shows the below output and shows the "Opening Remote..."message at the bottom of the left corner of the vs-code indefinitely. Please check the attached screenshot. 

![image](https://user-images.githubusercontent.com/2494368/60267812-b4959200-9908-11e9-88f3-c5abaee28ae3.png)

**Comment by roblourens** [comment]
It looks like you are using an old version of vscode insiders, please try updating

**Comment by bangyogesh** [comment]
@roblourens 
I have upgraded it with version 1.36, however I still get the same result ... vs-code stucks on "Opening Remote..."

Upgraded version -
Version: 1.36.0-insider
Commit: e73ef9a00c8bdbd84b21557737cc2c430aaeac51
Date: 2019-06-28T00:41:40.409Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.3.9600

**Comment by roblourens** [comment]
Can you share your ssh config? Has this worked in the past?

**Comment by gonz01d** [comment]
@bangyogesh I had this same issue and it was because I was missing seeing the prompt for entering my passphrase at the top middle of the VS code main window - instead, I was seeing the prompt in the text of the terminal window and trying to enter it there which it would appear does not work - once I entered my passphrase in the top prompt the server libs were installed and I was able to connect as expected.

**Comment by bangyogesh** [comment]
@roblourens
ssh config is as below
---------------------------------
Host Ubuntu
     HostName 172.10.10.3
     Port 22
     User yogesh
     IdentityFile /c/MySW/VSCode-insider/yogesh.key
-----------------------------------
I have Git-Bash installed. 
If I ssh from CMD promt with  command as  "ssh Ubuntu",  I am able to login to the VM without entering any password, passphrase. However VSCode Remote Stucks with "Opening Remote..." and never comes out.

**Comment by bangyogesh** [comment]
@gonz01d 
Thanks for the hint. However I do not see the prompt anywhere in the VSCode window. I am connecting using ssh config and it has mention of  ssh-key (private key) which do not need any passphrase. 

I have also tried to connect using 'username@vm-ip' way, I still dont see the password prompt.
BTW, my seetings.json is as below
{
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "remote.SSH.showLoginTerminal": true   
}

Screen-Shot where VS-Code Stucks on "Opening Remote ... " as below ---

![image](https://user-images.githubusercontent.com/2494368/60379586-3a255900-9a53-11e9-90af-aaa1c6e04673.png)

**Comment by roblourens** [comment]
I'm not sure what the problem would be. Seems that the install script just fails to start. Can you try using a windows-style path for IdentityFile to see if that makes a difference? Like `C:/MySW/...`

Also what do you get if you try running a command through ssh from the command prompt, like `ssh Ubuntu "echo hello"`?

**Comment by bangyogesh** [comment]
@roblourens ,
1) I tried putting the path like Windows Path( e.g. c:\Mysw \...) . However VSCode still shows the same result and Stucks on "Opening Remote...

2) Here is the o/p of running ssh Ubuntu "echo hello"

![image](https://user-images.githubusercontent.com/2494368/60729981-a88d7e00-9f61-11e9-8648-8b2ad657abb3.png)

**Comment by roblourens** [comment]
Do you see anything in the terminal if you click the "details" link in that notification?

**Comment by bangyogesh** [comment]
@roblourens , 
It loads the Output screen and its empty and Stuck on "Opening Remote...
Attaching a screen-shot (This time I used the IP address of the Ubuntu VM to connect instead of the name)".

![image](https://user-images.githubusercontent.com/2494368/60985947-0ce28000-a35c-11e9-9979-fac46c7d81e8.png)

**Comment by bangyogesh** [comment]
@roblourens
Appreciate if you can help further.

**Comment by roblourens** [comment]
Sorry, I don't even know what to ask. Still an issue with the latest Insiders and latest nightly extension?
