### ISSUE TITLE
Terminal Comes Up on Every Remote SSH Session on Specific Host

### ISSUE THREAD

**Issue by umamibeef** [microsoft/vscode-remote-release#8475]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.78.0 (user setup)
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Connect to my remote SSH VS Code session
2. Session connects without problems, but terminal window pops up with a little exclamation, but no error in the log. The log contains the following:

```
.
*

Checking server status on port 45807 with wget      
4b8f157aa4c5: start
SSH_AUTH_SOCK====
webUiAccessToken====
listeningOn==45807==
osReleaseId==linuxmint==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==0c6e788b-10c4-4661-9033-74939b492ccd==
4b8f157aa4c5: end
```

**Comment by roblourens** [comment]
Do you have the setting `"remote.SSH.showLoginTerminal": true` set?

**Comment by umamibeef** [comment]
> Do you have the setting `"remote.SSH.showLoginTerminal": true` set?

This was it! Thank you. Hopefully this helps someone in the future.
