### ISSUE TITLE
Cache remote server installation

### ISSUE THREAD

**Issue by fangzhangmnm** [microsoft/vscode-remote-release#8476]
The plugin download and install the code server every time I connect to the machine. which results in long connecting process. How can I avoid it?

**Comment by roblourens** [comment]
We only download/install the server when there are updates, unless someone/something deletes it from your remote host. When there is a vscode update, we need to download it again.

**Comment by fangzhangmnm** [comment]
> We only download/install the server when there are updates, unless someone/something deletes it from your remote host. When there is a vscode update, we need to download it again.

Thank you for your response! Can I see or specific the place of installation to see if it is being deleted automatically every time?

**Comment by roblourens** [comment]
It's at `~/.vscode-server/...` by default
