### ISSUE TITLE
Page up/down don't work in integrated terminal

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode-remote-release#848]
Page up/down work in local terminals, but when you connect to a remote host using the *Remote - SSH* extension and use the terminal there, it does nothing.

Using VSCode Insiders 1.36 (15b7c86d86319b187a5ef255c170184a8519c5af), on MacOS 10.14.4. The remote host is Ubuntu 18.04.

**Comment by Tyriar** [comment]
Works for me, what do you expect page up and down to do? Are you running tmux or screen or something?

**Comment by Timmmm** [comment]
I expect it to scroll up and down! Seems to be working for me now though so I'm not sure what happened.
