### ISSUE TITLE
notification 'Connecting to [tunnel name]' keep loading although connected

### ISSUE THREAD

**Issue by ngtankhoa** [microsoft/vscode-remote-release#8481]
Type: <b>Bug</b>

just connect to the tunnels and the notification keep showing although the tunnels connected

Extension version: 1.1.0
VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin x64 19.6.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-71-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|-psn_0_4469827 --crash-reporter-id 297a6eb4-ad0d-42de-b5a3-d3aa9a47c0a2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|khoa-latitude-e6520|
|OS|Linux x64 5.15.0-71-generic|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 3200)|
|Memory (System)|7.65GB (5.38GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30731970
fixshowwlkth:30730052

```

</details>

**Comment by fredlarochelle** [comment]
Can confirm, I am seeing the same bug

**Comment by emdfonseca** [comment]
Appears to be the same as #8432
