### ISSUE TITLE
Cannot connect to a remote dev container

### ISSUE THREAD

**Issue by darnox** [microsoft/vscode-remote-release#8490]
Type: <b>Bug</b>

When trying to connect to a dev container on a remote server the following error message appears:
`Failed to connect to the remote extension host server (Error: this.c.makeConnection is not a function)`

There must have been an update of VSC and/or some extension since just yesterday the same procedure worked as charm. 
The problem does not occur in the stable version of VSC.

Extension version: 0.293.0
VS Code version: Code - Insiders 1.79.0-insider (7a7d45793b76351a2783d266a381ae5ef450c08a, 2023-05-16T05:23:57.470Z)
OS version: Linux x64 5.15.0-71-generic snap
Modes:
Connection to 'Container ghcr.io/xxx-amd64 (xxx) @ ssh://trainstation5' could not be established  this.c.makeConnection is not a function
Remote OS version: Linux x64 5.15.0-69-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|11.52GB (7.93GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id bf13a6b5-d083-4ec1-9608-5e2224f2e5a0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

Connection to 'Container ghcr.io/xxx (xxx) @ ssh://trainstation5' could not be established  this.c.makeConnection is not a function

|Item|Value|
|---|---|
|Remote|SSH: trainstation5|
|OS|Linux x64 5.15.0-69-generic|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900KF (24 x 3200)|
|Memory (System)|62.62GB (44.59GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30737417
azdwalk:30721579
pythonms35:30671666
0bg3d529:30680467
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showsbindicator:30724477
pythongtdpath:30726887

```

</details>

**Comment by bamurtaugh** [comment]
Thanks for reporting. Are you still experiencing this in the latest VS Code Insiders? If so, can you share your remote setup (i.e. what kind of remote machine, how are you connecting to it)?

**Comment by darnox** [comment]
The issue has been resolved by now, thanks!
