### ISSUE TITLE
I'm taking segmentation fault when I try open WSL

### ISSUE THREAD

**Issue by LucasSAPacheco** [microsoft/vscode-remote-release#8492]
COMMIT=b3e4e68a0bc097f0ae7907b217c1119af9e03435
+ APP_NAME=code
+ QUALITY=stable
+ NAME=Code
+ SERVERDATAFOLDER=.vscode-server
+ realpath /mnt/c/Users/luks_/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/luks_/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/luks_/AppData/Local/Programs/Microsoft VS Code/bin
+ VSCODE_PATH=/mnt/c/Users/luks_/AppData/Local/Programs/Microsoft VS Code
+ ELECTRON=/mnt/c/Users/luks_/AppData/Local/Programs/Microsoft VS Code/Code.exe
+ IN_WSL=false
+ [ -n Ubuntu ]
+ IN_WSL=true
+ [ true = true ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:
+ wslpath -m /mnt/c/Users/luks_/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ CLI=C:/Users/luks_/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/luks_/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/luks_/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --ms-enable-electron-run-as-node --locate-extension ms-vscode-remote.remote-wsl
+ cat /tmp/remote-wsl-loc.txt
+ WSL_EXT_WLOC=c:\Users\luks_\.vscode\extensions\ms-vscode-remote.remote-wsl-0.78.5
+ [ -n c:\Users\luks_\.vscode\extensions\ms-vscode-remote.remote-wsl-0.78.5 ]
+ wslpath -u c:\Users\luks_\.vscode\extensions\ms-vscode-remote.remote-wsl-0.78.5
+ WSL_CODE=/mnt/c/Users/luks_/.vscode/extensions/ms-vscode-remote.remote-wsl-0.78.5/scripts/wslCode.sh
+ /mnt/c/Users/luks_/.vscode/extensions/ms-vscode-remote.remote-wsl-0.78.5/scripts/wslCode.sh b3e4e68a0bc097f0ae7907b217c1119af9e03435 stable /mnt/c/Users/luks_/AppData/Local/Programs/Microsoft VS Code/Code.exe code .vscode-server .
+ [ -z .vscode-server ]
+ [ .vscode-server = .vscode-insiders ]
+ [ ! -t 0 ]
+ VSCODE_REMOTE_BIN=/home/lousin/.vscode-server/bin
+ AUTHORITY=wsl+default
+ [ Ubuntu ]
+ AUTHORITY=wsl+Ubuntu
+ dirname /mnt/c/Users/luks_/.vscode/extensions/ms-vscode-remote.remote-wsl-0.78.5/scripts/wslCode.sh
+ /mnt/c/Users/luks_/.vscode/extensions/ms-vscode-remote.remote-wsl-0.78.5/scripts/wslDownload.sh b3e4e68a0bc097f0ae7907b217c1119af9e03435 stable /home/lousin/.vscode-server/bin
+ [ ! -d /home/lousin/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435 ]
+ RC=0
+ [ 0 -ne 0 ]
+ mktemp /tmp/vscode-distro-env.XXXXXX
+ STORED_ENV=/tmp/vscode-distro-env.2fT1jO
+ env
+ dirname /mnt/c/Users/luks_/.vscode/extensions/ms-vscode-remote.remote-wsl-0.78.5/scripts/wslCode.sh
+ VSCODE_CLIENT_COMMAND=/mnt/c/Users/luks_/AppData/Local/Programs/Microsoft VS Code/Code.exe VSCODE_CLIENT_COMMAND_CWD=/mnt/c/Users/luks_/.vscode/extensions/ms-vscode-remote.remote-wsl-0.78.5/scripts VSCODE_CLI_AUTHORITY=wsl+Ubuntu VSCODE_CLI_REMOTE_ENV=/tmp/vscode-distro-env.2fT1jO VSCODE_STDIN_FILE_PATH= WSLENV=VSCODE_CLI_REMOTE_ENV/w:ELECTRON_RUN_AS_NODE/w: /home/lousin/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/bin/remote-cli/code .
Segmentation fault
+ exit 139

It appear when I try to run "code ."

**Comment by bamurtaugh** [comment]
Thanks for opening this issue @LucasSAPacheco, and for the help @albertchen97. 

@LucasSAPacheco did @albertchen97's info solve your issue?

**Comment by LucasSAPacheco** [comment]
It's work, thanksss!!!

**Comment by LucasSAPacheco** [comment]
I used a solution, but I forgot to say here. Thanks!
