### ISSUE TITLE
Dev Container: Docker installed on M2 Mac is incompatible

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode-remote-release#8493]
Steps to Reproduce:
Ensure that no docker container is installed on an M2 Mac
1. Use the `Connect To` entry on the welcome page to get started with dev containers
2. Accept pop up which asks to install docker.
3. Try to open the Docker application post install.

Docker fails to open with the below compat error.
`“Fatal Error
Incompatible CPU detected.
Docker requires a processor with virtualization capabilities.`

Docker downloaded from https://www.docker.com/products/docker-desktop/ works

**Comment by chrmarti** [comment]
Is this in the M2's main OS or inside a VM? (Nested virtualization is not supported with the M1 and M2 Macs.)

**Comment by bhavyaus** [comment]
> Is this in the M2's main OS or inside a VM? (Nested virtualization is not supported with the M1 and M2 Macs.)

This is on the M2's main OS.

**Comment by chrmarti** [comment]
What is the output of running `docker version` in a terminal?

**Comment by Tyriar** [comment]
This still happens, the extension offers to download and install docker. When it does you see this:

<img width="330" alt="Screenshot 2024-02-05 at 12 10 17" src="https://github.com/microsoft/vscode-remote-release/assets/2193314/7d67e966-8900-455a-a417-e77868799696">

We must be downloading the intel binary, not the apple silicon one. https://docs.docker.com/desktop/install/mac-install/

**Comment by Tyriar** [comment]
It's one the main OS, not a VM. And I can't run `docker version` because it doesn't start (or didn't install a CLI at this point).

**Comment by bhavyaus** [comment]
Tried `docker version` now as well and I see the same issues as mentioned above.

**Comment by chrmarti** [comment]
Missed that we are using a single download link, adding one for ARM now, thanks!
