### ISSUE TITLE
Suddenly the extension is not working anymore

### ISSUE THREAD

**Issue by doussa2504** [microsoft/vscode-remote-release#8498]
I have been using the extension to connect to a remote slurm, and it works flawlessly. 
Today I got kicked out of the session and could not connect to the server using vscode anymore, although I can connect to it through ssh command line.
I tried some suggested solutions while going through issues:

- uninstall and reinstall the extension
- downgrade the extension
- remove .vscode-server directory from the server and ssh from windows, and start the installation over.
Nothing from the above suggestions has solved the issue.
I am stuck in the initialization stage and the last message I get after entering my password  is the following
Got password response
"install" wrote data to terminal: "*************"

What could be the issue?

**Comment by roblourens** [comment]
Could you share the full log from the "Remote - SSH" output channel?

![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Comment by doussa2504** [comment]
> Could you share the full log from the "Remote - SSH" output channel?
> 
> ![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

the log is a bit long, so I divided it on 2 screenshots:
![vscode-1](https://github.com/microsoft/vscode-remote-release/assets/77145707/f6ef84ec-9d6d-4d97-9def-89384d51d038)
`

![vscode-2](https://github.com/microsoft/vscode-remote-release/assets/77145707/7fd6f320-8741-4c8c-bddd-e9b54a5a8280)

**Comment by doussa2504** [comment]
update: after some time( more than an hour), it stops  and here is the output:
![vscode-3](https://github.com/microsoft/vscode-remote-release/assets/77145707/8766a5bd-dd61-4faa-b1a5-1710cd7a585f)

**Comment by roblourens** [comment]
We sent the password and never got a response from your server.

Does a command like this work for you (in powershell) `echo "echo hello" | ssh -T yourhost`

**Comment by doussa2504** [comment]
I tried it now and it kept running since several minutes without getting any response :(

**Comment by roblourens** [comment]
Does it work without the `-T`?

**Comment by doussa2504** [comment]
No, it kept pending. What does that mean?

**Comment by roblourens** [comment]
You will have to check with your system admin for the remote or experiment with your own ssh configuration. If that doesn't work, there is no way for us to connect and run a script.
