### ISSUE TITLE
For me, this issue only happens to https://labs.play-with-docker.com/ instances, but not others vps.

### ISSUE THREAD

**Issue by leandro-costa** [microsoft/vscode-remote-release#8499]
For me, this issue only happens to https://labs.play-with-docker.com/ instances, but not others vps.
I can `ssh hostname_of_play_with_docker_instance` successfully and control it, but it doesn't work with this extension.

_Originally posted by @maple3142 in https://github.com/microsoft/vscode-remote-release/issues/1704#issuecomment-546947206_

**Comment by bamurtaugh** [comment]
Thanks for opening. Is this issue the same as what was discussed in https://github.com/microsoft/vscode-remote-release/issues/1704? Could you provide some more info on the steps you're trying, what you're seeing vs what you'd expect, etc?
