### ISSUE TITLE
extension stop work  when use remote ssh

### ISSUE THREAD

**Issue by evildiamond** [microsoft/vscode-remote-release#850]
Issue Type: <b>Bug</b>

extension stop work  when use remote ssh

Extension version: 0.42.2
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 Centos7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: clouddev|
|OS|Linux x64 Centos7.0|
|CPUs|Intel(R) Xeon(R) Gold 61xx CPU (8 x 2494)|
|Memory (System)|15.42GB (4.44GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Please give more details. Which extension, what exactly is happening?
