### ISSUE TITLE
[Remote-SSH Bug]: vs code explorer does not open files

### ISSUE THREAD

**Issue by Vlod-github** [microsoft/vscode-remote-release#8501]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

I expect that if I log on to a remote server through a user who has root privileges, then being under it I can read or write system files through vscode explorer

### Steps To Reproduce

1. Log in to a remote server through a user who has root privileges.
2. Open the folder with system files.
3. Click on the file with the mouse.

### Remote-SSH Log

The Remote-SSH Log contains information only about a successful connection.

### Anything else?

After logging on to the server, it is possible to switch to root using `sudo su` in the terminal, but explorer shows `(FileSystemError): An unknown error occurred. Please consult the log for more details.`

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/48659
