### ISSUE TITLE
I cannot remote to server

### ISSUE THREAD

**Issue by chutinutcha99** [microsoft/vscode-remote-release#8509]
Type: <b>Bug</b>

I got this issue on yesterday.  I clicked remote ssh button 
1. Select hosting for remote
2. Enter password
after that it's not connect and don't have an error

Extension version: 0.102.0
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:47:05.613Z)
OS version: Linux x64 5.19.0-41-generic
Modes:
Sandboxed: Yes

**Comment by bamurtaugh** [comment]
Thanks for filing. 

> after that it's not connect and don't have an error

Could you please expand on this? i.e. what isn't correct, what do you see in the UI?
