### ISSUE TITLE
ssh-remote: document the `--remote` command line syntax

### ISSUE THREAD

**Issue by the-moog** [microsoft/vscode-remote-release#8517]
The documentation for wsl-remote gives the url format.

From the cli:
```powershell
`code --remote wsl+default /home/user/work/projects/name`
\#or
`code --folder-uri vscode-remote://wsl+default/home/user/work/projects/name`
```
Extensions use the same but without the `code --switch` part.

ref: [https://code.visualstudio.com/docs/remote/wsl](https://code.visualstudio.com/docs/remote/wsl])

Where `user` is the userid on the WSL instance.
_Note: I think the instructions on the link are swapped for folder and file references._

I can't find the same documentation for ssh-remote?
In WSL, being the logical owner of the instance and not a cluster, the full path to the user login is always known.

My question is how does the url format handle the case where the person connecting does not know the absolute path for their login before they login. e.g. when logging into a cluster. Often in that case the login shell determines the users logical homedir path.

How I think this works, is that vscode does a shell login `ssh user@system .... bash` then installs the vscode remote handlers in ~/.vscode and then does a chdir to the project via that link.

Is there a two step process or does the ${HOME} environment variable work?

I tried all the following with wsl and only the first one works.
This makes a request for the clarrification of the correct syntax. as it is the parsing done in vscode-remote and not wsl-remote or ssh-remote that needs better documetation.

```powershell
code --remote wsl+default /home/user/work/project1
code --remote wsl+default work/project1
code --remote wsl+default ~/work/project1
code --remote wsl+default ${HOME}/work/project1
code --remote wsl+default "${HOME}/work/project1"
```

**Comment by aeschli** [comment]
> I think the instructions on the link are swapped for folder and file references.
I don't see that:
![image](https://github.com/microsoft/vscode-remote-release/assets/6461412/2c374590-857f-4106-a4c2-0a0bb6a6f5c7)


Yes, we need to know the full path. At the time we construct the input URI we don't have a connection to WSL yet and can not resolve $HOME or ~.
