### ISSUE TITLE
Remote Tunnel requires SSH connection

### ISSUE THREAD

**Issue by fredlarochelle** [microsoft/vscode-remote-release#8529]
In VSCode (rpm in Fedora)  on my laptop, when I try to connect to a remote session on an Ubuntu server through a tunnel, it is never able to connect up until I open a SSH connection in an external terminal. It does the same thing when the laptop is on a local and external network (using Tailscale). As soon as I close the terminal with the SSH connection, VSCode is loosing the connection with the remote. The tunnel connection is dependent on having a SSH connection opened, but this problem doesn't exist if I connect through `vscode.dev/tunnel/...` in a browser, everything works just fine.

This issue is noncritical for me, since I already have a workaround (the SSH connection), but it's a bug and not ideal.

- VSCode Version:  1.78.2
- Local OS Version: Fedora 38 with kernel 6.2.15-300
- Remote OS Version: Ubuntu 22.04 with kernel 5.19.0-41-generic

**Comment by connor4312** [comment]
I'm guessing you have the tunnel installed as a service. You'll want to run `loginctl enable-linger $USER` to have user services stay running even if the user is not logged in.
