### ISSUE TITLE
[Remote-SSH Bug]: Laggy terminal and file creation/saving

### ISSUE THREAD

**Issue by zmunro** [microsoft/vscode-remote-release#8530]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

The terminal and the entire application is extremely sluggish when running in WSL2 Ubuntu. Saving any file takes 5+ seconds, typing a few words on the command line takes 5+ seconds for the words to show up, creating a file takes 10+ seconds. I expect things to be quick and snappy like they are when running locally.

### Steps To Reproduce

1. Have Ubuntu 20.04 installed:

> Distributor ID: Ubuntu
> Description:    Ubuntu 20.04 LTS
> Release:        20.04
> Codename:       focal

2. Connect to WSL2 from VScode using the WSL extension.

3. Do literally anything and it takes several seconds before your actions affect the application.

### Remote-SSH Log

Output window is empty, the things that are sluggish are: typing in the terminal, saving files, creating files and directories. None of these log anything to output.

### Anything else?

Here is a video of the behavior:
[https://streamable.com/kv4b6z](https://streamable.com/kv4b6z)

**Comment by roblourens** [comment]
It looks like this is about WSL, not remote-ssh

**Comment by aeschli** [comment]
Is this the same when using an external terminal?
