### ISSUE TITLE
Tasks aren't sourcing .bashrc in when using Remote SSH

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/vscode-remote-release#854]
- VSCode Version: 1.35.1
- Local OS Version: Windows 10 1803
- Remote OS Version: Centos 7.6
- Remote Extension/Connection Type: SSH

I have a simple build task:

    {
        "version": "2.0.0",
        "tasks": [
            {
                "label": "make",
                "type": "shell",
                "command": "which g++ && source ~/.bashrc && which g++",
                "problemMatcher": []
            }
        ]
    }

My remote .bashrc contains:

    source scl_source enable devtoolset-7

which sets the default g++ compiler to:

    /opt/rh/devtoolset-7/root/usr/bin/g++

when I run the task I see:

    > Executing task: which g++ && source ~/.bashrc && which g++ <
    /usr/bin/g++
    /opt/rh/devtoolset-7/root/usr/bin/g++

This indicates that the task's shell is not running .bashrc - I have to source it in the task.  

I assume that the shell should source .bashrc. Is this a bug related to Remote SSH?

**Comment by Tyriar** [comment]
@DavidA2014 to clarify, `.bashrc` is run in a *non-login* shell, `.bash_profile` is run in a login shell.

@alexr00 anything tasks is doing that would prevent it from running `.bashrc`?

**Comment by alexr00** [comment]
Possibly related? https://github.com/microsoft/vscode/issues/47235
Tasks should just be running the specified command in the terminal. It isn't doing anything that would prevent it from running `.bashrc`.

**Comment by DavidA2014** [comment]
Sorry for my inaccuracies - thanks for correcting those.

Would you expect the remote session to run .bash_profile and .bashrc?

**Comment by Tyriar** [comment]
@DavidA2014 can you share your settings.json and what your $SHELL environment variable is set to? (`echo $SHELL` in a terminal)

**Comment by DavidA2014** [comment]
@Tyriar Here they are:

    $ echo $SHELL
    /bin/bash

and

    {
    "files.exclude": {
        "**/_gnu*": true,
        "**/.vs": true,
        "**/*.doc": true,
        "**/*.docx": true,
        "**/*.filters": true,
        "**/*.jpg": true,
        "**/*.pdf": true,
        "**/*.png": true,
        "**/*.ppt": true,
        "**/*.pptx": true,
        "**/*.user": true,
        "**/*.vcproj": true,
        "**/*.vcxproj": true,
        "**/*.xls": true,
        "**/*.xlsx": true,
        "**/Debug": true,
        "**/ipch": true,
        "**/Release": true,
        "Demo": true,
        "MSVC": true
    },
    "files.associations": {
        "complex": "cpp",
        "vector": "cpp",
        "algorithm": "cpp",
        "cctype": "cpp",
        "cmath": "cpp",
        "cstddef": "cpp",
        "cstdint": "cpp",
        "cstdio": "cpp",
        "cstdlib": "cpp",
        "cstring": "cpp",
        "ctime": "cpp",
        "cwchar": "cpp",
        "deque": "cpp",
        "exception": "cpp",
        "fstream": "cpp",
        "initializer_list": "cpp",
        "iomanip": "cpp",
        "ios": "cpp",
        "iosfwd": "cpp",
        "iostream": "cpp",
        "istream": "cpp",
        "limits": "cpp",
        "map": "cpp",
        "memory": "cpp",
        "new": "cpp",
        "ostream": "cpp",
        "queue": "cpp",
        "sstream": "cpp",
        "stdexcept": "cpp",
        "streambuf": "cpp",
        "string": "cpp",
        "system_error": "cpp",
        "tuple": "cpp",
        "type_traits": "cpp",
        "typeinfo": "cpp",
        "utility": "cpp",
        "xfacet": "cpp",
        "xiosbase": "cpp",
        "xlocale": "cpp",
        "xlocinfo": "cpp",
        "xlocmon": "cpp",
        "xlocnum": "cpp",
        "xloctime": "cpp",
        "xmemory": "cpp",
        "xmemory0": "cpp",
        "xstddef": "cpp",
        "xstring": "cpp",
        "xtr1common": "cpp",
        "xtree": "cpp",
        "xutility": "cpp"
    }
    }

**Comment by DavidA2014** [comment]
Please will someone clarify whether it is expected that .bashrc or .bash_profile would be sourced in a remote session created by this extension?

**Comment by alexr00** [comment]
@Tyriar I'm seeing some strange things happening here. I'm testing using WSL.
In my .bashrc:
`export TEST_VAR='a value'`
If I start a terminal then `echo $TEST_VAR` then I get `a value`.

If I add to my settings.json **and don't reload**:
```
	"terminal.integrated.shell.linux": "bash",
	"terminal.integrated.shellArgs.linux": ["-c", "echo", "$TEST_VAR"],
```
then open a terminal, I see  `a value` echoed.

After I reload, then try to open a terminal the terminal immediately closes. No error in the console.

**Comment by alexr00** [comment]
@Tyriar  to confirm, but the .bashrc should be sourced in every terminal.

Also @Tyriar I'm testing with WSL, and I'm seeing something weird. In my .bashrc:
```
alias l='ls -CF'
export TEST_VAR='a value'
```
Only the var ends up accessible to my task:
```
> Executing task: echo $TEST_VAR <

a value

Terminal will be reused by tasks, press any key to close it.

> Executing task: l <

bash: l: command not found
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.
```

**Comment by alexr00** [comment]
And it gets stranger. I also tested on Ubuntu, not using remote. Same tasks, but this time the var and the alias are missing:

```
> Executing task: echo $TEST_VAR <



Terminal will be reused by tasks, press any key to close it.

> Executing task: l <

/bin/bash: l: command not found
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.

**Comment by alexr00** [comment]
Some more learning indicates that .bashrc is not sourced with bash is run with -c. All tasks run with -c unless explicitly overridden by the task. It is very strange that some parts of the .bashrc appear to be coming through though.

**Comment by alexr00** [comment]
@Tyriar I'm convinced now that none of the .bashrc should be sourced in tasks. Can you explain the inconsistent behavior here: https://github.com/microsoft/vscode-remote-release/issues/854#issuecomment-521153475 ?

**Comment by Tyriar** [comment]
.bashrc should not be sourced for non-interactive shells ([there are exceptions though](https://unix.stackexchange.com/a/257613/115410)):

```
❯ sh
$ c
sh: 1: c: not found
$ bash -c c
bash: c: command not found
$ bash -ci c  
code-insiders 1.38.0-insider

Usage: code-insiders [options][paths...]

Options
  -d --diff <file> <file>           Compare two files with each other.
  -g --goto <file:line[:character]> Open a file at the path on the specified line and character position.
  -n --new-window                   Force to open a new window.
  -r --reuse-window                 Force to open a file or folder in an already opened window.
  -w --wait                         Wait for the files to be closed before returning.
  -v --version                      Print version.
  -h --help                         Print usage.
  --folder-uri <uri>                Opens a window with given folder uri(s)
  --file-uri <uri>                  Opens a window with given file uri(s)

Troubleshooting
  -s --status Print process usage and diagnostics information.

```

For echo it might be getting confused where the env var is being evaluated? Hard to say without being on your computer:

```
$ bash -c "echo $TEST_VAR"        

$ bash -c "echo \$TEST_VAR"

$ bash -ci "echo $TEST_VAR"      

$ bash -ci "echo \$TEST_VAR"            
a value
```

Or maybe the outer environment has `$TEST_VAR` set already?

**Comment by alexr00** [comment]
For people who want to source .bashrc, include `-ci` in your tasks shell arguments:
```
{
			"label": "Run tests",
			"type": "shell",
			"command": "./scripts/test.sh",
			"linux": {
				"options": {
					"shell": {
						"args": ["-ci"]
					}
				}
			},
		}
```

**Comment by alexr00** [comment]
Closing since .bashrc and .bash_profile shouldn't be sourced in tasks unless you add special arguments to make it interactive. @bobmagicii if you're not seeing your.bash_profile sourced then you're seeing another problem.
