### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by gabo515** [microsoft/vscode-remote-release#8543]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### ->

ec87c785d4a8: running
Acquiring lock on /home/gabe/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/vscode-remote-lock.gabe.b3e4e68a0bc097f0ae7907b217c1119af9e03435
Installing to /home/gabe/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435...
ec87c785d4a8%%1%%
Downloading with wget
Download complete
ec87c785d4a8%%2%%
tar --version:
tar (GNU tar) 1.34
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
Checking /home/gabe/.vscode-server/.b3e4e68a0bc097f0ae7907b217c1119af9e03435.log and /home/gabe/.vscode-server/.b3e4e68a0bc097f0ae7907b217c1119af9e03435.pid for a running server
Running ssh connection command... /home/gabe/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all   &> "/home/gabe/.vscode-server/.b3e4e68a0bc097f0ae7907b217c1119af9e03435.log" < /dev/null
printenv:
    SHELL=/bin/bash
    PWD=/home/gabe
    LOGNAME=gabe
    XDG_SESSION_TYPE=tty
    MOTD_SHOWN=pam
    HOME=/home/gabe
    LANG=en_US.UTF-8
    VSCODE_AGENT_FOLDER=/home/gabe/.vscode-server
    SSH_CONNECTION=192.168.2.7 62388 192.168.1.72 22
    XDG_SESSION_CLASS=user
    USER=gabe
    SHLVL=0
    XDG_SESSION_ID=15
    XDG_RUNTIME_DIR=/run/user/1003
    SSH_CLIENT=192.168.2.7 62388 22
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1003/bus
    OLDPWD=/home/gabe/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435
    _=/usr/bin/printenv
rm: cannot remove '/home/gabe/.vscode-server/.b3e4e68a0bc097f0ae7907b217c1119af9e03435.token': No such file or directory 
Spawned remote server: 3553
Waiting for server log...
 
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*

ec87c785d4a8: start
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==39181==
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1003==
platform==linux==
unpackResult==success==
didLocalDownload==0==
downloadTime==721==
installTime==686==
extInstallTime====
serverStartTime==37==
connectionToken==567fa221-6b37-4e6e-ae6d-f78f78f380f3==
ec87c785d4a8: end

### Expected Behavior

I would expect it to connect and stop saying Opening Remote... / Setting up SSH Host

### Steps To Reproduce

VSCode Version: 1,78
Local OS Version: Microsoft Windows 11 Pro 10.0.22621 Build 22621
Remote OS Version: Ubuntu 22.04.2 LTS
Remote Extension/Connection Type: SSH

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
  GNU nano 6.2                             .b3e4e68a0bc097f0ae7907b217c1119af9e03435.log                                 M     *
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Server bound to 127.0.0.1:39181 (IPv4)
Extension host agent listening on 39181

[18:42:49]




[18:42:49] Extension host agent started.
[18:42:49] Started initializing default profile extensions in extensions installation folder. file:///home/gabe/.vscode-server>
[18:42:49] Completed initializing default profile extensions in extensions installation folder. file:///home/gabe/.vscode-serv>
Last EH closed, shutting down
[18:47:49] Last EH closed, shutting down
```

</p>
</details>

**Comment by roblourens** [comment]
Please share the log from the Remote-SSH output channel
