### ISSUE TITLE
'Could not create tunnel' ... 'tunnel name already in use'

### ISSUE THREAD

**Issue by robertandrews** [microsoft/vscode-remote-release#8544]
Type: <b>Bug</b>

Running VS Code on Mac. For a few weeks, I've been running a tunnel allowing me to access the install on my iPad via web.

I just also installed VS Code Insiders Nightly, span that up and also attempted to run the tunnel, without success.

Now I just want to go back to my usual setup, but Turn On Remote Tunnel Access results in the following log...

```
2023-05-27 20:27:03.516 [info] [2023-05-27 20:27:03] error Could not create tunnel with name: roberts-imaclocal
Reason: tunnel name already in use

2023-05-27 20:27:03.517 [info] tunnel exit(930): + 1 
2023-05-27 20:27:03.517 [info] tunnel process terminated
```

NB. I stopped the Insiders Nightly running, I trashed it, I rebooted the machine. But still the old stable build won't let me create the tunnel. I even restored the Insider build just to go in and ensure I used the Off function for tunnels.

I've even just removed the Remote Tunnels extension and reinstated it. No change.

On iPad Safari, vscode.dev can't "Connecting to roberts-imaclocal". Nothing happens.

It is possible to make a new tunnel with a new name, and that can be loaded up correctly.

But how can I free-up my core hostname for the tunnel?

Help.

There are only two results I can find on the web for this.

Wish I hadn't tried Insiders. It was a requirement of using Copilot Chat.

Extension version: 1.1.0
VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin x64 21.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|112, 36, 14|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 3558bb4d-b6c2-4f86-8162-8b2c278c78c0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
fixhidewlkth:30730051
hidesbindicator:30730055
pythongtdpath:30739704

```

</details>

**Comment by bamurtaugh** [comment]
Thanks for filing @robertandrews, and sorry to hear about the trouble.

@connor4312 @aeschli whenever you get a chance, it'd be great if you could check this one out. I think I may have experienced something similar last week.

**Comment by connor4312** [comment]
To remove the tunnel, in the Remote Explorer view, you can right click and unregister a tunnel

<img width="441" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/2230985/8e2378fe-ad9a-4217-975e-acc46994fe51">

We should offer (or default to) overwrite the existing tunnel if one already exists

**Comment by robertandrews** [comment]
So, I should delete the offline one matching my computer hostname? And then it will be available/recreated when I turn Remote Tunnels (_Off_ and then) back _On_ ... ?

<img width="401" alt="Screenshot 2023-05-31 at 20 08 21" src="https://github.com/microsoft/vscode-remote-release/assets/3158787/b8790a7d-ecfa-455a-a62d-8fae4bbc1131">

**Comment by connor4312** [comment]
Correct. Unregistering tunnels is generally non-destructive since they'll get recreated the next time that machine is started.

**Comment by robertandrews** [comment]
> Correct. Unregistering tunnels is generally non-destructive since they'll get recreated the next time that machine is started.

Okay - if I unregister both (and remove "blah" from the Host Name Override), then "Turn on Remote Tunnel Access", VS Code will successfully create a tunnel whose name defaults to the host computer again.

Thanks, both.

Very clever technology, by the way.

**Comment by connor4312** [comment]
This should be fixed in last month's release; the CLI will now take ownership of an existing tunnel name instead of failing
