### ISSUE TITLE
Clone repository in named container volume fails silently

### ISSUE THREAD

**Issue by hakito** [microsoft/vscode-remote-release#8548]
I try to clone into a named container using a ssh URL. But after entering the URL and clicking enter the Dialog closes and nothing happens.

- VSCode Version: 1.78.2
- Local OS Version:  22H2
- Remote OS Version:  -
- Remote Extension/Connection Type: Containers/WSL/Server -

- Logs: 

```
[99407 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[99573 ms] 1.42
[101593 ms] Start: Run: git ls-remote ssh://subatom/mnt/path/to/repo/obfuscated.git
```

Steps to Reproduce:

1. Execute command `Clone Repository in Named Container Volume`
2. Enter a ssh URL
3. Hit enter

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: -

**Comment by chrmarti** [comment]
Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)

**Comment by hakito** [comment]
I added the logs to the issue. When I execute the command from terminal, I have to enter the SSH-Password. So I added ssh keys and now it's working. But anyway I think some feedback for the user would be helpful.

**Comment by chrmarti** [comment]
Is that path part of your local `~/.gitconfig`?

**Comment by hakito** [comment]
Yes it is. In the meantime I already figured out, that the local gitconfig is copied into the _intermediate_ container. I already removed those lines in my `.gitconfig` and got it working.

This is actually out of scope for the current issue. But I didn't expect something like this to happen. I also couldn't find any documentation on this. I'd expect at least that I get asked if I want to copy my local config or if I want to start from scratch. (Espescially on windows)

**Comment by chrmarti** [comment]
There is a user setting to turn this off:
<img width="939" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/9205389/e780bf10-c870-413e-b4a6-e8bb3203c7f3">

**Comment by chrmarti** [comment]
We could clear the `core.sshCommand` setting to avoid this case.

**Comment by hakito** [comment]
> There is a user setting to turn this off: <img alt="image" width="939" src="https://user-images.githubusercontent.com/9205389/243670567-e780bf10-c870-413e-b4a6-e8bb3203c7f3.png">

Thanks - didn't think about the settings.
