### ISSUE TITLE
Check defaultExtensions on every connection

### ISSUE THREAD

**Issue by Morgy93** [microsoft/vscode-remote-release#855]
Probably somehow related to #463 or maybe my feature request is their problem :b 
ANYWAY

I'd like have `remote.SSH.defaultExtensions` checked on every connection, not once during server install on the remote host.

That would make it possible for me to use my default extensions and my co-workers to have their own default extensions installed if they connect to the same remote host.

**Comment by roblourens** [comment]
Dupe of https://github.com/microsoft/vscode-remote-release/issues/463
