### ISSUE TITLE
Remote - Tunnels: Failed to connect to the remote extension host server (Error: Connection error: Client refused: version mismatch)

### ISSUE THREAD

**Issue by jfether** [microsoft/vscode-remote-release#8555]
In the preview version of VS Code's Remote Tunnels extension (v1.2.2023053010), I see this error when connecting to my remote:

> 2023-05-30 17:23:28.442 [info] Creating new tunnel proxy server
> 2023-05-30 17:23:29.239 [info] [proxy] Found tunnel (ID=(redacted), Cluster=usw3)
> 2023-05-30 17:23:29.241 [info] Remote resolution completed
> 2023-05-30 17:23:30.398 [info] [proxy] [connection.0] tunnel connection established
> 2023-05-30 17:23:30.442 [info] [proxy] Tunnel connection successful
> 2023-05-30 17:23:30.610 [info] Resolving tunnel+(hostname redacted)...
> 2023-05-30 17:23:30.612 [info] Found running server in \\.\pipe\vscode-tunneling-(redacted)-sock
> 2023-05-30 17:23:30.640 [info] Error greeting the server, starting a new instance (Error: Connection closed)

And I get this error:
![image](https://github.com/microsoft/vscode-remote-release/assets/4120020/a4ae029f-5011-41d1-a291-8336d61f64e1)

Switching back to the release version (v1.1.0) resolves the issue.

Client OS: Windows 10 19044.2965
Remote (Server) OS: Linux 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux (Raspberry Pi with Raspberry Pi OS)

Client Version: Visual Studio Code 1.78.2
Remote (Server) version: code 1.78.2

**Comment by connor4312** [comment]
Thanks for the issue! This should be fixed on today's Insiders already (note: you'll want to update VS Code / the CLI on the host machine). Please let me know if you continue to experience problems.
