### ISSUE TITLE
remote-containers.attachToRunningContainerFromViewlet 错误: Shell server terminated (code: 255, signal: null)

### ISSUE THREAD

**Issue by zhyxue0** [microsoft/vscode-remote-release#8558]
When I deploy docker on remote linux server:
```
docker run -it  -u root --restart=always  --shm-size="1024g" --name=fenics quay.io/fenicsproject/leasted:current /bin/bash
```

Then I try to click the docker container in vscode ![图片](https://github.com/microsoft/vscode-remote-release/assets/102371822/a708701a-e34d-4160-b03f-a15b45ff3aaa) 
I meet the error:
```
运行命令 remote-containers.attachToRunningContainerFromViewlet 错误: Shell server terminated (code: 255, signal: null)

Permission denied, please try again.
Permission denied, please try again.
xxxx@xxx.xx.xx.xx: Permission denied (publickey,password).
。这可能是由提交 remote-containers.attachToRunningContainerFromViewlet 的扩展引起的
```

linux server `ssh -V` is:
```
OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
```

How to fix it?

- VSCode Version: 1.76
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 20.04.1 LTS
- Remote Extension/Connection Type: Containers

- Logs:  运行命令 remote-containers.attachToRunningContainerFromViewlet 错误: Shell server terminated (code: 255, signal: null)

Permission denied, please try again.
Permission denied, please try again.
xxxx@xxx.xx.xx.xx: Permission denied (publickey,password).
。这可能是由提交 remote-containers.attachToRunningContainerFromViewlet 的扩展引起的

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
`xxxx@xxx.xx.xx.xx: Permission denied (publickey,password).` suggests that there was an auth issue. The connection code had a large overhaul since, could you retry?
