### ISSUE TITLE
Vmmem process using 100% cpu and freezes when vscode with WSL2 is idling for some few hours

### ISSUE THREAD

**Issue by patchie** [microsoft/vscode-remote-release#8560]
- VSCode Version:
> Version: 1.79.0-insider (user setup)
> Commit: c3867859cf3e1a73f3ddce5ad36b3791b7883d88
> Date: 2023-06-01T05:24:05.541Z
> Electron: 22.5.4
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Windows_NT x64 10.0.19044

- Local OS Version:
> Edition	Windows 10 Enterprise
> Version	21H2
> Installed on	‎06.‎12.‎2022
> OS build	19044.2846
> Experience	Windows Feature Experience Pack 120.2212.4190.0

- Remote OS Version: Ubuntu(WSL2)
- Remote Extension/Connection Type: WSL2

- Logs: N/A? (vscode has freezed, can i find these logs in a .txt file somewhere maybe?)

Steps to Reproduce:

1. start vscode with remote:WSL.
2. wait for 5-7 hours, ish. Just leave it idle...
3. suddenly, the CPU will spike to 100% on both windows task manager(wmmem process), and in WSL2 ubuntu installation.
4. The vscode window suddenly shows following:
![image](https://github.com/microsoft/vscode-remote-release/assets/1792727/046d21ba-4ce4-4be2-ad92-f4df4450b296)
![image](https://github.com/microsoft/vscode-remote-release/assets/1792727/ccf091d4-839b-4f3b-8d42-4783a086dbd8)

5. Since i had "htop" open, i could see the freezed frame of what cpu processes is using cpu
![image](https://github.com/microsoft/vscode-remote-release/assets/1792727/d1c26034-8b6f-42c2-bf8e-487b671b4322)

It seems that vmmem process is using very little processor power for hours, but suddenly it goes up to around 20%, and then after some seconds/half a minute/a minute or something, it goes to 100%cpu and WSL2 + vscode freezes.
I now need to restart the computer, as i cannot find any way to force restart the process or WSL2

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by seflue** [comment]
I have exactly the same problem.

**Comment by aeschli** [comment]
Is this still an issue?
