### ISSUE TITLE
VS Code Remote server.sh script fails -- unable to execute node.

### ISSUE THREAD

**Issue by stringfold** [microsoft/vscode-remote-release#857]
- VSCode Version: 1.35.1
- Local OS Version: Windows 10 v1903
- Remote OS Version: Debian 9.9 on Linode VPS 64-bit
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install Remote extension
2. Issue Remote-SSH: Connect Current Window to Host... command

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

Apologies if I'm overlooking something obvious (which I probably am) but I cannot get the Remote extension to run at all via SSH. I have double-checked all the prerequisites are in place, and SSH is working fine. The Connect command installs the server correctly, but when it tries to execute ./server.sh, all I get is a "node: not found" error.

When I try running the command manually on my server, I get the same error -- the script simply isn't recognizing node as an executable as far as I can tell. All file permissions are as installed and are all correct as far as I can see.

Here's the remote install directory:

```
drwxr-xr-x   2 stringfold users     4096 Jun 12 09:34 bin
drwxr-xr-x  27 stringfold users     4096 Jun 12 09:35 extensions
-rw-r--r--   1 stringfold users    13380 Jun 12 09:14 LICENSE
-rwxr-xr-x   1 stringfold users 37154432 Jun 12 09:34 node
drwxr-xr-x 154 stringfold users     4096 Jun 12 09:35 node_modules
drwxr-xr-x   3 stringfold users     4096 Jun 12 09:34 out
-rw-r--r--   1 stringfold users      880 Jun 12 09:21 package.json
-rw-r--r--   1 stringfold users    16392 Jun 12 09:14 product.json
-rwxr-xr-x   1 stringfold users      242 Jun 27 15:21 server.sh

```Here's the log:

remote-ssh@0.42.2

SSH Resolver called for "ssh-remote+xxx"
SSH Resolver called for host: xxx
Setting up SSH remote "xxx"
Using commit id "c7d83e57cd18f18026a8162d042843bda1bcf21f" and quality "stable" for server
Install and start server if needed
> 
> ]0;C:\WINDOWS\SYSTEM32\cmd.exe
>  
> Enter passphrase for key 'C:\Users\xxx/.ssh/id_rsa': 
> 
> 
> Installing to /home/stringfold/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bc
> f21f...
> 
> Downloading with wget
> 
> Printing the current remote environment...
> 
> SSH_CONNECTION= xxx
> LANG=en_US
> XDG_SESSION_ID=5263
> USER=stringfold
> PWD=/home/stringfold
> HOME=/home/stringfold
> SSH_CLIENT= xxx
> MAIL=/var/mail/stringfold
> SHELL=/bin/bash
> SHLVL=2
> LANGUAGE=en_US:en
> VSCODE_AGENT_FOLDER=/home/stringfold/.vscode-server
> LOGNAME=stringfold
> XDG_RUNTIME_DIR=/run/user/1002
> PATH=/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/local/rvm/bin:/home/stringfold/.rvm/
> bin
> _=/usr/bin/printenv
> OLDPWD=/home/stringfold/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f   
> Starting server...
> 
> Waiting for server log...
> 
> 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
> Server did not start successfully. Full server log:
> /home/stringfold/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f/server.sh
> : 12: /home/stringfold/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f/ser
> ver.sh: /home/stringfold/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f/n
> ode: not found
> 2e26f913-c2fe-4acf-b96d-8bc5584739fd====
> 
"install" terminal command done
Received install output: 2e26f913-c2fe-4acf-b96d-8bc5584739fd====
Failed to parse remote port from server output: 2e26f913-c2fe-4acf-b96d-8bc5584739fd====

```
```

**Comment by wmertens** [comment]
Try editing `/home/stringfold/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f/server.sh` and replacing the `$node` on the last line (or is it `${node}`? Anyway the first word) with just `node` or the full path to a local installation of Node 10.

**Comment by stringfold** [comment]
Thanks for the suggestion. After struggling to install node 10, I discovered that my venerable VPS was upgraded from 32-bit to 64-bit a number of years ago, but many of the packages are still running i386 versions. This is likely the root source of the problem (and why I can't get node v10 installed!), but it'll take me a day or two to resolve the issues -- probably by porting my VPS to a clean 64-bit build.

I'll report back when I'm done.

**Comment by stringfold** [comment]
Okay, after porting my server over to a pure 64-bit Debian 9 VPS, and finally getting back to the point where I can run the VS Code Remote installation again, I am now getting past the error I was previously receiving. I'm still getting an error, but it's almost certainly to do with client configuration problems already documented in other issues. Closing this issue.
