### ISSUE TITLE
SSH path setting is not respected

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-remote-release#858]
- VSCode Version: 1.36.0-insider ( b7265738444f1eee05762341b4361ee6452a4154)
- Local OS Version: Windows_NT x64 10.0.18362
- Remote OS Version: Ubuntu 18.04 x64
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

When testing https://github.com/microsoft/vscode-remote-release/issues/753

1. Make sure ssh is not specified in system PATH , uninstall windows installation of ssh, uninstall git for windows
2. Install git for windows to some custom location, just for the sake of specifying it explicitly under settings 
3. Set `Remote.SSH: Path`
4. Connect window to ssh host
5.  Error prompt with `An SSH installation couldn't be found`

**Comment by roblourens** [comment]
Hey @deepak1556, when you create an issue from a testplan item, you can just assign it to the owner right away to make sure we see it. Can you share the log from the Remote-SSH output channel for this?
