### ISSUE TITLE
Error if SSL-versions of Host and Guest are not the compatible

### ISSUE THREAD

**Issue by mineichen** [microsoft/vscode-remote-release#8581]
It would be nice, if there were a error, if the dev-container and host ssl-versions are not compatible. It was very inconvenient to find the issue, which caused git not to work with ssh-repositories when using a new container-image. At first I was wondering, if I had to install a missing dependency in the devcontainer for it to work. Later I learnt, that this is caused by incompatible ssl versions (the new Container used OpenSsl3, the old OpenSsl1).  This was specially confusing, as `ssh-add -l` still correctly listed the keys within the devcontainer. Eventually, the following command gave me the hint:
```
GIT_SSH_COMMAND="ssh -v" git clone git@github.com:mineichen/minfac.git
```
Output:
```
...
debug1: get_agent_identities: ssh_fetch_identitylist: communication with agent failed
...
```

With this error I found the following issue: https://superuser.com/questions/1726204/get-agent-identities-ssh-agent-bind-hostkey-communication-with-agent-failed, which explains, that the HOST-OpenSsl has to be updated.

I don't know, if it would make sense to solve this at the ssh-level or git-level. Failing, the command if there is an incompatible agent on the system.

It would be nice to mention the issue at: https://code.visualstudio.com/docs/containers/ssh.

It would be nice if the dev-container doesn't startup with incompatible versions, because the issue is hard to spot. There might however be a flag in `devcontainer.json` like `checkSslCompatibility`, which defaults to true. This could be mentioned in the error message, when the incompatibility is spoted alongside the alternative to update the host's OpenSsl.

**Comment by chrmarti** [comment]
This is https://github.com/microsoft/vscode-remote-release/issues/7525. My Windows 11 installation still has OpenSSH 8.6, so this might continue to come up until Windows ships a new version of OpenSSH.

@bamurtaugh Maybe https://code.visualstudio.com/docs/devcontainers/containers#_known-limitations would be a good place to mention that there is an incompatibility between OpenSSH versions when the ssh-agent runs on Windows with version <= 8.8 and the ssh client (on any platform) runs version >= 8.9. The workaround is to upgrade OpenSSH on Windows to 8.9 or later, either using `winget` or an installer from https://github.com/PowerShell/Win32-OpenSSH/releases.

**Comment by bamurtaugh** [comment]
@mineichen thanks for opening!

@chrmarti thanks for tagging me, that makes sense. I self-assigned this issue as a docs issue (considering https://github.com/microsoft/vscode-remote-release/issues/7525 is the same) and opened https://github.com/microsoft/vscode-docs/pull/6398.
