### ISSUE TITLE
Remote-Tunnels : client refused, version mismatch, from one day to the other

### ISSUE THREAD

**Issue by crankedguy** [microsoft/vscode-remote-release#8582]
I have severe problems with the tunnels extension, the connections are very unstable at times etc. But now I cannot even connect anymore at all. I get the error client refused, version mismatch, although there is no version mismatch

I connect from Win to RHEL(Alma 9), I restarted Code on Win, restarted the code-tunnel service on the host, nothing helps, I am getting always the same error, yesterday everything was working, no new vscode version installed, but seemingly a new release of the tunnels extension...

Windows 
```
Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```
RHEL
```
Last metadata expiration check: 3:09:35 ago on Wed 07 Jun 2023 05:07:14 PM CEST.
Installed Packages
code.x86_64                                                                                     1.78.2-1683731087.el7                                                                                    @code
```
AlmaLinux release 9.2 (Turquoise Kodkod), complete up to date

```
     Loaded: loaded (/home/user/.config/systemd/user/code-tunnel.service; enabled; preset: disabled)
     Active: active (running) since Wed 2023-06-07 20:20:24 CEST; 7s ago
   Main PID: 803082 (code-tunnel)
      Tasks: 8 (limit: 98068)
     Memory: 5.3M
        CPU: 127ms
     CGroup: /user.slice/user-1005.slice/user@1005.service/app.slice/code-tunnel.service
             └─803082 /usr/share/code/bin/code-tunnel --verbose --disable-telemetry --cli-data-dir /home/user/.vscode-cli tunnel service internal-run

```

Tunnels extension
v1.2.0

Please advise for further investigation, thanks

**Comment by mdonato-fn** [comment]
Same here. I tried to:
1. remove `code-cli`, re-download, re-start
2. remove `.vscode-cli` and `.vscode-server` and `.vscode-server-insider` from my home, go back to 1. and restart
3. use the pre-release version of remote tunnels
Nothing works.

I checked the log.txt at `/home/me/.vscode-cli/servers/Insiders-545d981034e010e2e31396faf224996c31eceab1/log.txt` (I don't know why I get insiders, I have no idea how to get it to use stable) and this is the content:

```
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Server bound to /tmp/code-28ba3dac-366e-4794-8428-19b8b1483f3f
Extension host agent listening on /tmp/code-28ba3dac-366e-4794-8428-19b8b1483f3f

[18:39:04] 




[18:39:04] Extension host agent started.
[18:39:05] Started initializing default profile extensions in extensions installation folder. file:///home/me/.vscode-server-insiders/extensions
[18:39:05] Completed initializing default profile extensions in extensions installation folder. file:///home/me/.vscode-server-insiders/extensions
[18:39:05] [<unknown>][e1d8145b] Client refused: version mismatch.
[18:39:05] [<unknown>][67ec0344] Client refused: version mismatch.
[18:39:05] [<unknown>][45e59ac3] Client refused: version mismatch.
[18:39:06] [<unknown>][f70ceada] Client refused: version mismatch.
[18:39:06] [<unknown>][c6254168] Client refused: version mismatch.
[18:39:06] [<unknown>][46835796] Client refused: version mismatch.
[18:39:06] [<unknown>][64d818fa] Client refused: version mismatch.
[18:39:07] [<unknown>][9bd79ba7] Client refused: version mismatch.
[18:39:07] [<unknown>][f2e6c2ca] Client refused: version mismatch.
[18:39:07] [<unknown>][fcda7d69] Client refused: version mismatch.
```

**Comment by crankedguy** [comment]
You are right, there is something very wrong as I also have an Insider directory all of a sudden and not Stable, my last Stable-xxx logs are from 5th June and everything is fine there, my actual log from Insiders version looks exactly like yours...
So you already reinstalled and it automatically pulls the insider version? Then I do not have to try this anyways.
The time this is consuming with Code goes through the roof slowly, last time init file was hardcoded with bad code through update on Windows...

Can someone please investigate this?
Many thanks!

```
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Server bound to /tmp/code-xxx
Extension host agent listening on /tmp/code-xxx

[20:21:07]




[20:21:07] Extension host agent started.
[20:21:07] [<unknown>][3c4f516e] Client refused: version mismatch.
[20:21:10] [<unknown>][a601f3df] Client refused: version mismatch.
[20:21:12] [<unknown>][05df2e9c] Client refused: version mismatch.
[20:21:14] [<unknown>][7f503b75] Client refused: version mismatch.
[20:21:16] [<unknown>][4082f841] Client refused: version mismatch.
[20:21:18] [<unknown>][54fa2beb] Client refused: version mismatch.
[20:21:18] [<unknown>][cc3aba5b] Client refused: version mismatch.
[20:21:18] [<unknown>][6b30b785] Client refused: version mismatch.
[20:21:18] [<unknown>][8021785e] Client refused: version mismatch.
Last EH closed, shutting down

```

**Comment by mdonato-fn** [comment]
That's a good point, I did not notice but mine too switched to insider yesterday without me doing anything.

**Comment by crankedguy** [comment]
Yes so it seems to have to do with the Tunnels extension which was updated (in the local install). It somehow messes with the remote, becasue on my remote host nothing happened at all, no update etc., all the code binaries have past date, code versions are equal, nothing specifically logged on the system...

**Comment by mdonato-fn** [comment]
Also good point there: I installed Remote Tunnels 1.1.0 and now I can connect to the tunnel.

**Comment by crankedguy** [comment]
Exactly, switching back to 1.1.0 and deleting all Insiders related stuff on the remote just to be sure fixed the connection again.
But this should not be considered fixed here, as it seems to be an inconsistent mess between stable and insider versions, as in the linked issue the user installed insider locally and then it worked

**Comment by connor4312** [comment]
Thanks for the issue report, extension version 1.2.1 will be out shortly which'll fix the error. A bunch of changes happened over the last month and I fumbled part of the release lockstep. As you've found, you can also downgrade to the extension to 1.1.0 to work around this.

**Comment by crankedguy** [comment]
@connor4312 Thanks for getting onto this quick!

**Comment by Naruu** [comment]
I downgraded tunnel extensio nto 1.10 and it solved. Thank you so much!

**Comment by vhphan** [comment]
How do I downgrade to 1.10?

**Comment by axman6** [comment]
Any idea when the fix will be available? I'm going to have to resort to X-forwarding to get work done today 🤮

**Comment by crankedguy** [comment]
> Any idea when the fix will be available? I'm going to have to resort to X-forwarding to get work done today 🤮 

why not downgrade? a matter of seconds

**Comment by axman6** [comment]
> > Any idea when the fix will be available? I'm going to have to resort to X-forwarding to get work done today 🤮
> 
> why not downgrade? a matter of seconds

I haven't been able to figure out how to, I tried installing the previous version locally and on the remote machine and I get the same error. Like @vhphan I would love to know what the correct command is (and which machine to run it on)

**Comment by crankedguy** [comment]
you don't need a command to downgrade, and as mentioned in the thread already you just need to downgrade the local version. just open the extension and click install other version and use 1.1.0

**Comment by axman6** [comment]
> ... just open the extension and click install other version and use 1.1.0

Thank you, that's all you needed to say, no need to be snarky when clearly at least two people didn't understand. I've never needed to install a specific version of a VS Code extension, and I'm sure I'm not alone (which says a lot about the quality of extensions in the community).

Looks like it's working now.

**Comment by vhphan** [comment]
I only can access the remote machine via SSH. 
I am starting the tunnel on the remote machine using "code cli" tunnel command like this ">>code tunnel" as described here:

https://code.visualstudio.com/docs/remote/tunnels

So how do I downgrade on the remote server when the only way to access the remote machine is SSH (i.e. no VS code GUI available)??

**Comment by axman6** [comment]
> I only can access the remote machine via SSH. I am starting the tunnel on the remote machine using "code cli" tunnel command like this ">>code tunnel" as described here:
> 
> https://code.visualstudio.com/docs/remote/tunnels
> 
> So how do I downgrade on the remote server when the only way to access the remote machine is SSH (i.e. no VS code GUI available)??

I didn't need to do anything on the remote machine, only as @crankedguy said, downgrade on the client machine. I'm using the Remote SSH extension, so I'm not sure if this is relevant to you, but you might want to try running `code tunnel kill; code tunnel` on the server and then try reconnecting from the client once you've downgraded the extension.

**Comment by vhphan** [comment]
> > I only can access the remote machine via SSH. I am starting the tunnel on the remote machine using "code cli" tunnel command like this ">>code tunnel" as described here:
> > https://code.visualstudio.com/docs/remote/tunnels
> > So how do I downgrade on the remote server when the only way to access the remote machine is SSH (i.e. no VS code GUI available)??
> 
> I didn't need to do anything on the remote machine, only as @crankedguy said, downgrade on the client machine. I'm using the Remote SSH extension, so I'm not sure if this is relevant to you, but you might want to try running `code tunnel kill; code tunnel` on the server and then try reconnecting from the client once you've downgraded the extension.

@axman6 , Thanks a lot for your hep!! It is working now. I was just a little confused. 

I also didn't need to `code tunnel kill`

**Comment by trallnag** [comment]
works fine with pre-release version of extension.

**Comment by grisaitis** [comment]
I think this should have the `tunnels` label instead of `ssh`. looks like the github actions bot added the `ssh` label https://github.com/microsoft/vscode-remote-release/issues/8582#event-9463695875

**Comment by reverendrenegade** [comment]
Have there been any updates here? I reverted to the older version but that is now giving me trouble and it appears there is a new release.

**Comment by connor4312** [comment]
Yes, extension version 1.2.1 is out, so you should upgrade to that

**Comment by GingerIndustries** [comment]
My copy of Code doesn't show 1.2.1, only 1.2.0.

**Comment by mdonato-fn** [comment]
Installed 1.2.1 and it works for me, thanks for the quick turnaround!

**Comment by vavtnen** [comment]
How do you downgrade or upgrade to pre release version using vscode.dev?

**Comment by GingerIndustries** [comment]
Still doesn't work with 1.2.1 on a Raspberry Pi.
