### ISSUE TITLE
DevContainer: run commands in remote host directly

### ISSUE THREAD

**Issue by 7c00** [microsoft/vscode-remote-release#8587]
I am using `DevContainer` in a remote host (via `Remote SSH`). But due to some network control policies, it always hangs during initializing. I checked the log, which shows that:

```
[2023-06-09T01:43:29.559Z] Dev Containers 0.292.0 in VS Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302).
[2023-06-09T01:43:29.559Z] Start: Run: ssh remote-host /bin/sh
[2023-06-09T01:43:29.564Z] Start: Run in host: id -un
```

It seems that although I am running vscode in a **remote** host, the `DevContainer` extension still invokes commands **via ssh from my local host**.

Could we make `Dev Container` work complete remotely when running in a remote host?

**Comment by chrmarti** [comment]
It currently needs to establish an initial connection using `ssh remote-host`. This is the same Remote SSH does, could you append your `~/.ssh/config` (or just the relevant parts of it)?

**Comment by 7c00** [comment]
@chrmarti Thanks for your reply. There is nothing special in ~/.ssh/config. Bug my remote host is behind a relay server, and accessible via an open source software https://github.com/jumpserver/jumpserver. It has some restriction on ssh client by default, but after [some configuration](https://kb.fit2cloud.com/?p=48),  Remote SSH extension works, but Dev Container does not.
