### ISSUE TITLE
[Dev Containers] version 0.292 create new set of docker images and containers for every 'Reopen in Container'

### ISSUE THREAD

**Issue by tjin4** [microsoft/vscode-remote-release#8588]
- VSCode Version: 1.79.0
- Local OS Version: Windows 10, WSL Ubuntu 20
- Remote OS Version: Ubuntu 20
- Remote Extension/Connection Type: Containers/WSL/Server

VSCode 1.79.0 with 'Dev Containers' Extension version 0.292, when I run 'Reopen in Container', the newly created Docker images and containers are all prefixed with a unique project name (with GUID). After I close the VS Code and reopen the project with 'Reopen in Container', the Dev Container will use a new GUI and create whole new set of Docker images and containers.  This new behavior causes huge leak in docker images and containers, and worse, if one of the container expose a port, then it will complain the port is already in use and fail to start. 

I reverted 'Dev Containers' extension to version 0.282, the created Docker images and containers are all prefixed with a static 'project name', when I close and reopen the project, it will connect to the existing docker container instances, everything is good.

**Comment by gcarvajal1222** [comment]
@tjin4 I started seeing the same thing in docker desktop: 

![image](https://github.com/microsoft/vscode-remote-release/assets/36053537/e7764943-92a2-495a-aa51-f8a72298b3cb)

**Comment by tjin4** [comment]
//--vv-- first time open project in vscode, run 'reopen in container'

tjin4@DESKTOP-2P2K49E:~$ docker ps
CONTAINER ID   IMAGE                                                                                     COMMAND                  CREATED          STATUS          PORTS     NAMES
bd3cb7481511   vsc-async-activity-535317bdd90e51c5f9dd3925037dd4d63b6fbe3386bebad70f07849ca683729e-uid   "/bin/sh -c 'echo Co…"   28 seconds ago   Up 21 seconds             devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-activity-devcontainer-1
0331219ebfe2   devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-temporalite                      "temporalite start -…"   39 seconds ago   Up 22 seconds             devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-temporalite-1

tjin4@DESKTOP-2P2K49E:~$ docker images
REPOSITORY                                                                                TAG       IMAGE ID       CREATED              SIZE
vsc-async-activity-535317bdd90e51c5f9dd3925037dd4d63b6fbe3386bebad70f07849ca683729e-uid   latest    f513ca639026   About a minute ago   1.14GB
devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-activity-devcontainer            latest    91f612bc0c8c   About a minute ago   1.14GB
devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-temporalite                      latest    03e7b0a18a0b   3 minutes ago        484MB
bitnami/kafka                                                                             latest    2d24aee8412e   2 days ago           558MB


//--vv-- close vscode, reopen the project, and run 'reopen in container'

tjin4@DESKTOP-2P2K49E:~$ docker ps
CONTAINER ID   IMAGE                                                                                     COMMAND                  CREATED          STATUS          PORTS     NAMES
44eeb1dec9cb   vsc-async-activity-535317bdd90e51c5f9dd3925037dd4d63b6fbe3386bebad70f07849ca683729e-uid   "/bin/sh -c 'echo Co…"   20 seconds ago   Up 13 seconds             devcontainer-config-923a58ce-d00e-4caf-8ac8-ada5c3539e81-activity-devcontainer-1
544f3b79a134   devcontainer-config-923a58ce-d00e-4caf-8ac8-ada5c3539e81-temporalite                      "temporalite start -…"   22 seconds ago   Up 14 seconds             devcontainer-config-923a58ce-d00e-4caf-8ac8-ada5c3539e81-temporalite-1
bd3cb7481511   f513ca639026                                                                              "/bin/sh -c 'echo Co…"   2 minutes ago    Up 2 minutes              devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-activity-devcontainer-1
0331219ebfe2   devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-temporalite                      "temporalite start -…"   2 minutes ago    Up 2 minutes              devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-temporalite-1

tjin4@DESKTOP-2P2K49E:~$ docker images
REPOSITORY                                                                                TAG       IMAGE ID       CREATED          SIZE
vsc-async-activity-535317bdd90e51c5f9dd3925037dd4d63b6fbe3386bebad70f07849ca683729e-uid   latest    0a173bc924e0   31 seconds ago   1.14GB
<none>                                                                                    <none>    f513ca639026   3 minutes ago    1.14GB
devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-activity-devcontainer            latest    91f612bc0c8c   3 minutes ago    1.14GB
devcontainer-config-923a58ce-d00e-4caf-8ac8-ada5c3539e81-activity-devcontainer            latest    ae55fd3c4db5   3 minutes ago    1.14GB
devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-temporalite                      latest    03e7b0a18a0b   5 minutes ago    484MB
devcontainer-config-923a58ce-d00e-4caf-8ac8-ada5c3539e81-temporalite                      latest    bb6b46a4e700   5 minutes ago    484MB
bitnami/kafka                                                                             latest    2d24aee8412e   2 days ago       558MB


//--vv-- close code, reopen the project, and run reopen in container

tjin4@DESKTOP-2P2K49E:~$ docker ps
CONTAINER ID   IMAGE                                                                                     COMMAND                  CREATED          STATUS          PORTS     NAMES
20bdb77ee89a   vsc-async-activity-535317bdd90e51c5f9dd3925037dd4d63b6fbe3386bebad70f07849ca683729e-uid   "/bin/sh -c 'echo Co…"   25 seconds ago   Up 15 seconds             devcontainer-config-a2b3d2a7-6cf4-4a1a-a546-2b335b00fd04-activity-devcontainer-1
d4f8b1a04452   devcontainer-config-a2b3d2a7-6cf4-4a1a-a546-2b335b00fd04-temporalite                      "temporalite start -…"   28 seconds ago   Up 16 seconds             devcontainer-config-a2b3d2a7-6cf4-4a1a-a546-2b335b00fd04-temporalite-1
44eeb1dec9cb   0a173bc924e0                                                                              "/bin/sh -c 'echo Co…"   4 minutes ago    Up 4 minutes              devcontainer-config-923a58ce-d00e-4caf-8ac8-ada5c3539e81-activity-devcontainer-1
544f3b79a134   devcontainer-config-923a58ce-d00e-4caf-8ac8-ada5c3539e81-temporalite                      "temporalite start -…"   4 minutes ago    Up 4 minutes              devcontainer-config-923a58ce-d00e-4caf-8ac8-ada5c3539e81-temporalite-1
bd3cb7481511   f513ca639026                                                                              "/bin/sh -c 'echo Co…"   6 minutes ago    Up 6 minutes              devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-activity-devcontainer-1
0331219ebfe2   devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-temporalite                      "temporalite start -…"   6 minutes ago    Up 6 minutes              devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-temporalite-1

tjin4@DESKTOP-2P2K49E:~$ docker images
REPOSITORY                                                                                TAG       IMAGE ID       CREATED          SIZE
vsc-async-activity-535317bdd90e51c5f9dd3925037dd4d63b6fbe3386bebad70f07849ca683729e-uid   latest    b80450b96fe3   34 seconds ago   1.14GB
<none>                                                                                    <none>    0a173bc924e0   4 minutes ago    1.14GB
<none>                                                                                    <none>    f513ca639026   7 minutes ago    1.14GB
devcontainer-config-a2b3d2a7-6cf4-4a1a-a546-2b335b00fd04-activity-devcontainer            latest    5b71291b57c0   7 minutes ago    1.14GB
devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-activity-devcontainer            latest    91f612bc0c8c   7 minutes ago    1.14GB
devcontainer-config-923a58ce-d00e-4caf-8ac8-ada5c3539e81-activity-devcontainer            latest    ae55fd3c4db5   7 minutes ago    1.14GB
devcontainer-config-a2b3d2a7-6cf4-4a1a-a546-2b335b00fd04-temporalite                      latest    d67b5c28b44c   9 minutes ago    484MB
devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-temporalite                      latest    03e7b0a18a0b   9 minutes ago    484MB
devcontainer-config-923a58ce-d00e-4caf-8ac8-ada5c3539e81-temporalite                      latest    bb6b46a4e700   9 minutes ago    484MB
bitnami/kafka                                                                             latest    2d24aee8412e   2 days ago       558MB

**Comment by tjin4** [comment]
tjin4@DESKTOP-2P2K49E:~$ docker inspect devcontainer-config-c7c0a02f-69c3-4903-abf0-204d000f9522-activity-devcontainer-1
[
    {
        "Id": "7a8d22f6f7423314fe094186ed210e060fc82beb333f908826286a9377214eca",
        "Created": "2023-06-13T02:50:39.9680567Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "echo Container started\n trap \"exit 0\" 15\n \n exec \"$@\"\n while sleep 1 & wait $!; do :; done",
            "-",
            "docker-entrypoint.sh",
            "/bin/sh",
            "-c",
            "while sleep 1000; do :; done"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 554,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-06-13T02:51:07.0166143Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:775fe855b8571afc6334336d7af0e6184d90fee68be0fb244f99064cb3a5eada",
        "ResolvConfPath": "/var/lib/docker/containers/6c156f037b56284598f7d4ac27d80f28a49ccc95359ba41b56ba8ec4d1d10ff8/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/6c156f037b56284598f7d4ac27d80f28a49ccc95359ba41b56ba8ec4d1d10ff8/hostname",
        "HostsPath": "/var/lib/docker/containers/6c156f037b56284598f7d4ac27d80f28a49ccc95359ba41b56ba8ec4d1d10ff8/hosts",
        "LogPath": "/var/lib/docker/containers/7a8d22f6f7423314fe094186ed210e060fc82beb333f908826286a9377214eca/7a8d22f6f7423314fe094186ed210e060fc82beb333f908826286a9377214eca-json.log",
        "Name": "/devcontainer-config-c7c0a02f-69c3-4903-abf0-204d000f9522-activity-devcontainer-1",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": [
            "61a1fa17abb35a17c919b69879bd1d9ceefe81108e7917dad49c95590518075d",
            "1c69aa13deaa7a3ef260629c26c7a9f9897408b8b25f270afaffb899ade232aa",
            "d50543e09c0b019a35518d0a902ca07aaad2e0946f0de967eb58f98abe8b0ef9",
            "13714d2095970b758484c9e85bb2b0b303bae731911f76cfcb868b98bab7747f",
            "d0cec87c2a0d9dd228717d636bfc7ef0b1904eb4d880c64d559264c7f2b0da4f",
            "480beb84eefa1b68e1b0183648953961a08b1a176b48ac01bb7d1110b228c86a"
        ],
        "HostConfig": {
            "Binds": [
                "/tmp/devcontainer-config-c7c0a02f-69c3-4903-abf0-204d000f9522:/usr/activity:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "container:6c156f037b56284598f7d4ac27d80f28a49ccc95359ba41b56ba8ec4d1d10ff8",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "volume",
                    "Target": "/usr/activity/activity-provider/node_modules",
                    "VolumeOptions": {}
                },
                {
                    "Type": "volume",
                    "Source": "vscode",
                    "Target": "/vscode",
                    "VolumeOptions": {}
                }
            ],
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/a66907439e5bf8c40fd40e9a4f9abe24c08a1570a70dc5e01a141d4192a7f281-init/diff:/var/lib/docker/overlay2/w033v48cf128n1vjnf7yiid4c/diff:/var/lib/docker/overlay2/xgx9k84we0dupsii3shff1sbd/diff:/var/lib/docker/overlay2/kvjfy5doyxwepaf14k5eiafr4/diff:/var/lib/docker/overlay2/zcqmpvg6tkznf08a6kdyogavl/diff:/var/lib/docker/overlay2/099b8eaa74968ed3c4335b59587dbb07635416f67ed14980158aeebabad52804/diff:/var/lib/docker/overlay2/82319c574bdeff778ee70adb5528b94c0981cccfd606ba65675322341f5b550e/diff:/var/lib/docker/overlay2/63a65d12a4d3ca348b0cc624d5c0bf47496204e036029bb1ada5f3608b2fba09/diff:/var/lib/docker/overlay2/58270712c28f1b99b001a37bf4bc147cd5f630c51d9f99ac8ea361c79c5e5941/diff:/var/lib/docker/overlay2/e63e3649ec6d317af8a8570bad7b0b7583f493166b3de237fe449f07f1abc5e6/diff:/var/lib/docker/overlay2/0e3d87a7c015fd5157a1526f0288ed1f27eff4f3801c1abe980ce7cd4e702b56/diff:/var/lib/docker/overlay2/60a3968a9699c157d873ccb78f32fcc45825fccabf11ea75cf153ae6e4e16cf6/diff:/var/lib/docker/overlay2/98947f634243f8cc4eeefe194cb7a00f5f1a707f5db7ca88b2f8e70703553e44/diff",
                "MergedDir": "/var/lib/docker/overlay2/a66907439e5bf8c40fd40e9a4f9abe24c08a1570a70dc5e01a141d4192a7f281/merged",
                "UpperDir": "/var/lib/docker/overlay2/a66907439e5bf8c40fd40e9a4f9abe24c08a1570a70dc5e01a141d4192a7f281/diff",
                "WorkDir": "/var/lib/docker/overlay2/a66907439e5bf8c40fd40e9a4f9abe24c08a1570a70dc5e01a141d4192a7f281/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "vscode",
                "Source": "/var/lib/docker/volumes/vscode/_data",
                "Destination": "/vscode",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/tmp/devcontainer-config-c7c0a02f-69c3-4903-abf0-204d000f9522",
                "Destination": "/usr/activity",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "ab752d2b9cf302cdcd75afd21f2d0b0a9a784e219449972414c80796f0b2b1df",
                "Source": "/var/lib/docker/volumes/ab752d2b9cf302cdcd75afd21f2d0b0a9a784e219449972414c80796f0b2b1df/_data",
                "Destination": "/usr/activity/activity-provider/node_modules",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "6c156f037b56",
            "Domainname": "",
            "User": "op",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=20.3.0",
                "YARN_VERSION=1.22.19"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "while sleep 1000; do :; done"
            ],
            "Image": "vsc-async-activity-535317bdd90e51c5f9dd3925037dd4d63b6fbe3386bebad70f07849ca683729e-uid",
            "Volumes": null,
            "WorkingDir": "/usr/activity/activity-provider",
            "Entrypoint": [
                "/bin/sh",
                "-c",
                "echo Container started\n trap \"exit 0\" 15\n \n exec \"$@\"\n while sleep 1 & wait $!; do :; done",
                "-",
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "c288d214a936bfb2f1eef6fa44821828506f15ddc64e7d15ff21149eeb33f813",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "temporalite:service_started,kafka:service_started",
                "com.docker.compose.image": "sha256:775fe855b8571afc6334336d7af0e6184d90fee68be0fb244f99064cb3a5eada",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "devcontainer-config-c7c0a02f-69c3-4903-abf0-204d000f9522",
                "com.docker.compose.project.config_files": "/tmp/devcontainer-config-c7c0a02f-69c3-4903-abf0-204d000f9522/docker-compose-env.yml,/tmp/devcontainer-config-c7c0a02f-69c3-4903-abf0-204d000f9522/.devcontainer/docker-compose.yml,/tmp/devcontainercli-tjin4/docker-compose/docker-compose.devcontainer.build-1686624580630.yml,/tmp/devcontainercli-tjin4/docker-compose/docker-compose.devcontainer.containerFeatures-1686624632361.yml",
                "com.docker.compose.project.working_dir": "/tmp/devcontainer-config-c7c0a02f-69c3-4903-abf0-204d000f9522",
                "com.docker.compose.service": "activity-devcontainer",
                "com.docker.compose.version": "2.15.1",
                "devcontainer.config_file": "file:///c%3A/github/tjin4/async-activity/.devcontainer/devcontainer.json",
                "devcontainer.local_folder": "c:\\github\\tjin4\\async-activity",
                "devcontainer.metadata": "{\"customizations\":{\"vscode\":{\"extensions\":[\"esbenp.prettier-vscode\",\"Orta.vscode-jest\",\"mquandalle.graphql\"]}},\"forwardPorts\":[10799]}"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {}
        }
    }
]

**Comment by chrmarti** [comment]
Could you append a `devcontainer.json` and `docker-compose.yml` that show the problem?

**Comment by tjin4** [comment]
[async-activity.zip](https://github.com/microsoft/vscode-remote-release/files/11740759/async-activity.zip)

**Comment by chrmarti** [comment]
I don't get these UUIDs you have in the image and container names. Are you using the latest Docker Desktop? What do you get for `docker version`?

**Comment by tjin4** [comment]
> I don't get these UUIDs you have in the image and container names. Are you using the latest Docker Desktop? What do you get for `docker version`?

The images was provided by [gcarvajal1222](https://github.com/gcarvajal1222), I think they are docker volumes, not the same thing I reported here originally.

I'm running docker in WSL directly, not using Docker desktop. For me, the problem is that the docker compose launched by devcontainer extension now use a prefix like 'devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-xxx' when it build the image and containers, and the GUID after 'devcontainer-config-' is a new one every time I run 'reopen in container'.  
When I close VSCode, the previous docker compose is still running, and later I open the same project in VSCode, and do 'reopen in container', it will rebuild a whole set images and containers.  

For example in my previous attached output, after I 'reopen in container' 3 times, it ended up with 3 different devcontainer and temporalite images (and containers) like the following:

devcontainer-config-a2b3d2a7-6cf4-4a1a-a546-2b335b00fd04-activity-devcontainer latest 5b71291b57c0
devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-activity-devcontainer latest 91f612bc0c8c
devcontainer-config-923a58ce-d00e-4caf-8ac8-ada5c3539e81-activity-devcontainer latest ae55fd3c4db5
devcontainer-config-a2b3d2a7-6cf4-4a1a-a546-2b335b00fd04-temporalite latest d67b5c28b44c
devcontainer-config-7930cbc2-46f8-4479-b40b-3ca96b44a236-temporalite latest 03e7b0a18a0b
devcontainer-config-923a58ce-d00e-4caf-8ac8-ada5c3539e81-temporalite latest bb6b46a4e700

In devcontainer extension version 0.282, it just uses the root directory name as the prefix (same as docker compose behavior), i.e. my project root is 'myproj', then the images will be look like this: 
myproj-activity-devcontainer
myproj-temporalite

And no matter how many times I close VSCode and reopen the project, they all use the same set of images and containers.

This change in devcontainer extension 0.292 seems intentional and by design, maybe I missed something and not doing it in the right way?
