### ISSUE TITLE
The connection to the terminal's pty host process is unresponsive, the terminals may stop working.

### ISSUE THREAD

**Issue by ZedRover** [microsoft/vscode-remote-release#8589]
- VSCode Version: 1.78.2 Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
- Local OS Version: Apple M1 Pro, 13.4 (22F66)
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: Containers

- Logs:

<img width="486" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/29392414/66c245da-e9fe-4785-938a-9526b281e29b">

<img width="1527" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/29392414/d39cf267-cd13-47c3-886d-e4a077ac3586">

Steps to Reproduce:
After connecting to the docker container with ssh for python development, I only need to execute python scripts like "python train.py" on the command line. I often encounter problems with the pty host disconnecting, or the built-in command line is very laggy, I am now used to local I'm now used to running python scripts in the local terminal, but I hope the vscode team will fix this bug.
I run into this problem both in my corporate intranet environment and at home when developing remotely via tailscale intranet penetration, and I'm sure it's not due to network issues. Also, my remote server has 4Tb RAM, which I don't normally think is related to the remote server configuration.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by ZedRover** [comment]
[https://github.com/microsoft/vscode/issues/150058](url)
[https://github.com/microsoft/vscode-remote-release/issues/8050](url)
According to the developer this issue has been fixed, but I'm still experiencing this problem a lot lately. Thank you for your help.

**Comment by thmyztm1895** [comment]
I have the problem too. And the version of VS Code is 1.79

**Comment by alanmangalindan** [comment]
Also encountering this issue. Just updated to VS Code 1.79, on Windows 11.

**Comment by s3bc40** [comment]
Same here for VS Code 1.79

**Comment by thmyztm1895** [comment]
> I have the problem too. And the version of VS Code is 1.79

update: The error dialog isn't appear today. But i do nothing.

**Comment by toasteur** [comment]
same problem here on windows 10 as soon as i updated to 1.79

**Comment by lucasgustavodiaz** [comment]
Same problem here, clean install

Versión: 1.79.1 (user setup)
Electrón: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by draganpetkov** [comment]
I reverted to an older version until the bug is fixed
