### ISSUE TITLE
`Commands: Execute in WSL` allways active | Container creation fails with default settings

### ISSUE THREAD

**Issue by S-p-Ace** [microsoft/vscode-remote-release#8590]
Type: <b>Bug</b>

Trying to create dev containers fails on command 'up' similar to [issue #800] from rancher-desktop.  

[issue #800]:(https://github.com/rancher-sandbox/rancher-desktop/issues/800)
[Dev Containers.log](https://github.com/microsoft/vscode-remote-release/files/11705746/Dev.Containers.log)

## reproduction steps

1. use Rancher Desktop for docker
     * set `dockerd(moby)` as docker engine
2. set a default WSL distro different from  `rancher-desktop` (for example Ubuntu)
3. create a dev container either via
     * (Re-)Open Folder in Container...
     * Try a Dev Container Sample...

It makes no difference if Rancher Desktop is configured to expose the the docker socket to Ubuntu or not.

## Workaround

* Set `rancher-desktop` as default WSL distribution in WSL or
* set `dev.containers.executeInWSLDistro` to `rancher-desktop`

---
It stands to reason that the setting `dev.containers.executeInWSL` is ignored and always active as the other setting comes into effect even though this setting is unchecked and I'm not operating within a WSL folder.

Rancher Desktop: v1.8.1

Extension version: 0.295.0
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.16GB free)|
|Process Argv|--crash-reporter-id 9723fad1-8bbb-4480-8fdd-f354f4674d72|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
hidesbindicator:30760978
pythongtdpath:30739704
dh2dc718:30763024

```

</details>

**Comment by chrmarti** [comment]
Is the `docker` command available in the default WSL distro (e.g., Ubuntu)?

Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)

**Comment by S-p-Ace** [comment]
yes, the docker command is available inside the Ubuntu WSL distro

```
kevin@LAPTOP-S13TG3MA:~$ docker --version
Docker version 23.0.1-rd, build 393499b
kevin@LAPTOP-S13TG3MA:~$ docker ps -a
CONTAINER ID   IMAGE                                                                                                  COMMAND                  CREATED      STATUS                  PORTS     NAMES
be6123a93075   mcr.microsoft.com/devcontainers/base:alpine-3.17                                                       "/bin/sh -c 'echo Co…"   2 days ago   Exited (0) 2 days ago             distracted_lehmann
9769ea4232ee   vsc-ms-identity-node-main-544c3985d72f1fe84288d72ac90cd52d0af87b84123a104be5dff7217c57200f-features    "/bin/sh -c 'echo Co…"   2 days ago   Exited (0) 2 days ago             intelligent_ptolemy
86bf12663787   mcr.microsoft.com/devcontainers/python:0-3.11                                                          "/bin/sh -c 'echo Co…"   3 days ago   Exited (0) 3 days ago             trusting_swirles
39dad13be032   vsc-vscode-remote-try-java-562126e00b6ad54b40a10300c
10263ba753fd9071ee6491400470b7e7813ad9b-features   "/bin/sh -c 'echo Co…"   3 days ago   Exited (0) 3 days ago             affectionate_zhukovsky

```

[remoteContainers-2023-06-12T07-33-51.604Z.log](https://github.com/microsoft/vscode-remote-release/files/11719602/remoteContainers-2023-06-12T07-33-51.604Z.log)
