### ISSUE TITLE
[ vscode.dev/tunnel ] Cannot signin to github in an Android Webview

### ISSUE THREAD

**Issue by KermanX** [microsoft/vscode-remote-release#8592]
- VSCode Version: any
- Local OS Version: any
- Remote OS Version: Android Webview version unknown
- Remote Extension/Connection Type: Server, tunnel

Steps to Reproduce:

1. **in an Android Webview**
2. open `https://vscode.dev/tunnel/<TUNNEL-NAME>`
3. it requires you to signin to Github
4. automatically you are redirected to the GitHub signin page
5. input your username and password, login, and authorize vscode
6. automatically you are redirected to a page which reads "You can close this page now"
7. **However, since you are in an Android Webview, the only way to close the page is to exit the webview**, so there is.no other choice but to press the button "←" button and return to vscode.dev
8. However, vscode.dev requires to signin again. This is an infinite loop.

**In a common browser, the signin to GitHub page will be opened in a new window.**
**But in an Android Webview, there is no "new window", so vscode.dev actually redirected the whole page to the Github signin page.**

**I am sure it wasn't like this one week ago**
One week ago, once you open `vscode.dev/tunnel/***`, it wouldn't load vscode, but immediately jumps to Github signin page. And once you've signined and authorized vscode, it automatically jumps back to `vscode.dev/tunnel/***`.

> Why I use Android Webview? I have no other choice... I am at school, and common browsers are disabled.

**So is there any workaround, and can someone fix this? Thanks a lot!**

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by KermanX** [comment]
the key is:
1. Why this problem didn't happen one week ago? What has been changed.
2. Maybe we need another choice to signin to GitHub, like there are multiple choices to signin to GiHub in a vscode in electron (with/without local server, device code...)

**Comment by TylerLeonhardt** [comment]
Do you get the same behavior by opening like: https://vscode.dev/github/microsoft/vscode

Here's the _fairly normal_ browser code we use to open a pop up:
https://github.com/microsoft/vscode/blob/4ddef94beb34a88aacc3079849a2c0a669f70b25/src/vs/base/browser/dom.ts#L1154-L1174

The idea is that this code would be able to open the auth page over vscode.dev, and then at the end of the flow, it would close itself.

This is going to be hard to debug without seeing what the dev tools say... I might need you to follow something like:
https://developer.chrome.com/docs/devtools/remote-debugging/webviews/
or 
https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/remote-debugging/webviews

in order to see  what's going on.

**Comment by KermanX** [comment]
> Do you get the same behavior by opening like: https://vscode.dev/github/microsoft/vscode

Yes. "the extension GitHub Repository requires login to GitHub"

I am so sorry that I have no way to connect that Android Webview to a devtool. Because the webview is embed and all functions are locked (the pad is designed to be used in school).
I think the webview just ignores the parameter `target: "_blank"`, and opens the auth page directly in current window.

Is there any possibility to offer a redirection in the page which reads "You can close the page now", or use `iframe` instead of a popup window, or just rollback to the previous way of login?

Thanks:smile:

**Comment by TylerLeonhardt** [comment]
The thing is, this hasn't changed in ... like years. So my guess is that Android WebViews have either a new security feature or bug that's preventing this flow from finishing. 

I would suspect that the dev tools of the Android webview would be telling.

Perhaps to start, can you hit the back button to get back to vscode.dev for me and open the output panel (ctrl+shift+u I think) and share with me the contents of these output channels (hit the drop-down to switch):
* GitHub Authentication
* Main
* Window
* anything tunnel related

**Comment by KermanX** [comment]
I'm sorry for my late reply, and thank you so much.

However, I've graduated from high school, so I no longer can use the Pad to repro this issue...

Students in the next grade will (definitely) still meet the issue, so maybe @7086cmd will reopen this issue after this September?

Again, really appreciate your patience and help!
