### ISSUE TITLE
Port forwarding not working

### ISSUE THREAD

**Issue by thonkinator** [microsoft/vscode-remote-release#8595]
Type: <b>Bug</b>

Whenever a process starts that uses a port, the port is not automatically forwarded, and when I try to manually forward it, it gives me an error as if the port is not in use.

Extension version: 1.2.1
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:29:00.206Z)
OS version: Darwin x64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
showsbindicator:30760979
pythongtdpath:30739704
dh2dc718:30763024
pythonnosmt12:30757131

```

</details>

**Comment by TPreece101** [comment]
I have this same problem with VS Code version 1.79.1

**Comment by garibarba** [comment]
Same issue when using `code tunnel`. It works sometimes through Linux vscode, but it doesn't work through vscode.dev.

**Comment by TPreece101** [comment]
Same for me @garibarba - when I use vscode on my mac then it works fine but doesn't work on vscode.dev

I also have some icons that look like they're not loading properly on vscode.dev
For example here is the icon for SQLTools - however the icons work fine when I'm using vscode on my mac - I don't know if they're connected but both issues started occurring at the same time

![Screenshot 2023-06-17 at 14 20 49](https://github.com/microsoft/vscode-remote-release/assets/12260327/b7642fd9-d403-474c-93c6-65f85fe6e408)

**Comment by Sandros94** [comment]
Automatically or manually forwarding ports when connected via vscode.dev doesn't work. But if I open the tunnel from another vscode instance everything works (host is `vscode 1.79.2` on `win 11 22621.1848`).

Same here, a number of icons are missing in vscode.dev:
![image](https://github.com/microsoft/vscode-remote-release/assets/13056429/c7fa3057-06c5-4c5f-83e3-bab6e6bed4ee)

**Comment by TPreece101** [comment]
Hi @roblourens - sorry for tagging you directly, I noticed that you're quite active on this repo so I'm hoping you can help answer this question. What do we need to do to get this looked at? Is there more information required? I'm happy to provide as much as needed as the lack of port forwarding is becoming a real blocker for me - it looks like it's just affecting the version of VSCode on https://vscode.dev/ rather than local version.

**Comment by mfriedy** [comment]
Same issue as everyone else - issue solely when connecting through vscode.dev.

Happy to assist with any debug information as required

**Comment by bamurtaugh** [comment]
Thanks all for filing and the details! It seems this is for Remote - Tunnels, rather than SSH (as the issue was initially tagged by the bot), so updating the label and tagging @connor4312 and @alexr00.

**Comment by thonkinator** [comment]
similarly, some icons are missing for me (as mentioned by others above). should i stay in this issue or open a new one?

**Comment by thonkinator** [comment]
oops, sorry. i didn't realize that the fix was in the july 2023 milestone. i'll try insiders for now
