### ISSUE TITLE
Is there a way to attach a running container without opening any workspace?

### ISSUE THREAD

**Issue by Kidsunbo** [microsoft/vscode-remote-release#8598]
- VSCode Version: 1.79.0
- Local OS Version: MacOS 12.3
- Remote OS Version: Ubuntu 22.04
- Remote Extension/Connection Type: Containers

Actually I am not sure if it's a bug or a new feature. I notice that starting from v0.295.0, the right click menu has changed, `Attach to Container` has changed to `Attach in Current Window`. But that's not the problem.

If I attach a container using `Attach in New Window`, in the previous version, it will open a new window without opening to a workspace but `NO FOLDER OPENED`. But starting from v0.295.0, it always tries to open a workspace. For some scenarios, it's OK. But if I removed the workspace before or removed the container and started a new one with same image and then attach to it, it still tries to open the non-existing workspace and then reports an error. 

Is this a bug or intentional feature? And is there a way to attach the container without opening any workspace like before?

**Comment by bamurtaugh** [comment]
cc @chrmarti @joyceerhl as perhaps this stemmed from making the remote open commands more consistent
