### ISSUE TITLE
non-bash startup scripts are not executed when installing agent via ssh

### ISSUE THREAD

**Issue by MarkDHarris** [microsoft/vscode-remote-release#86]
- VSCode Version: 1.34.0-insider
- OS Version: macOS 10.13.6
- Remote-SSH version: 0.34.0

Steps to Reproduce:

1.  Install vscode insiders and install vscode remote development extension pack
2. Configure multi-factor authentication and generated public ssh key.
3A. Use extension and attempt to connect to remote host.  
...
...
> Starting agent...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Server did not start successfully. Full server log:
> /home/<user>/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/server.sh: line 10: realpath: command not found
> /home/<user>/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/server.sh: line 12: ./node: No such file or directory
> 13a4e8e9-6167-4804-b1f0-1242ef47c39b====
"install" terminal command done
Received install output: 13a4e8e9-6167-4804-b1f0-1242ef47c39b====
Failed to parse remote port from server output: 13a4e8e9-6167-4804-b1f0-1242ef47c39b====
...
...

3B.  Also tried ssh'ing and running .vscode-remote/bin/<...>/server.sh manually.  Server reports listening on 8000.  Then using local vscode and attempting to connect :
...
...
> Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Server did not start successfully. Full server log:
> /home/<user>/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/server.sh: line 10: realpath: command not found
> /home/<user>/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/server.sh: line 12: ./node: No such file or directory
> 26fba612-0cb6-4f35-8899-d4ae43730b9f====
"install" terminal command done
Received install output: 26fba612-0cb6-4f35-8899-d4ae43730b9f====
Failed to parse remote port from server output: 26fba612-0cb6-4f35-8899-d4ae43730b9f====
...
...

4.  I cannot find any additional troubleshooting logs.  Files at ~/.vscode-remote/data/logs/20190503T163450/remoteagent.log are empty.

5. I can confirm that the resources that appear to be reported as not being found do exist:
(on remote host)

% pwd
/home/<user>/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9

% realpath
/local/home/<user>/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9

 % ls
0  bin  extensions  LICENSE  node  node_modules  out  package.json  product.json  server.sh

(the script seems to be looking for "/local/home/<user>/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/node" which clearly does exist)

Is there anything else I can investigate to learn why this fails to connect?  

Does this issue occur when all extensions are disabled?: Yes/No
  N/A - This issue is about the remote-ssh extension

**Comment by Tyriar** [comment]
See https://code.visualstudio.com/docs/remote/troubleshooting#_enabling-alternate-ssh-authentication-methods for 2fa

**Comment by MarkDHarris** [comment]
I can also confirm vscode-insiders setting:
"remote.SSH.showLoginTerminal": true

and ControlMaster configured (had to use s instead of sockets due to the path being 104 chars)
Host *
        ControlMaster auto
        ControlPath  ~/.ssh/s/%r@%h-%p
        ControlPersist  600

were already enabled in my step #2 above.

**Comment by MarkDHarris** [comment]
I can ssh into my host from the vscode terminal or from my main terminal just fine.  (That was how I ssh'd and started the vscode server script manually.)  However, the extension is unable to connect.

**Comment by wqfan** [comment]
I had this problem too. It looks like VS Code overrides `PATH` when it's installing the extension. And for some reason that `realpath` is not in the `PATH` overridden. To fix this I put my `realpath` into one of the path it overrides.

**Comment by MarkDHarris** [comment]
Thanks wqfan!  I ran "sudo cp /<was on my path set by .zshrc>/realpath /usr/local/bin/" and that led to one more line of output in the error that looks like my required environmental setup is failing or not completing.   I don't have any influence over some of what is in my .zshrc because my organization has custom tools that are required.

@Tyriar - Is there a way to enforce that the .zshrc script gets properly initialized or a way to get additional diagnostic output?  I think wqfan is correct, it seems to overwrite some or part of the environment but that's based on my unconfirmed hunch gained from one extra line of output I can now see.   I need to get more insight and possibly control over how it starts because if my organization's tooling and environment is not properly initialized I won't be able to use this awesome extension anyway.

**Comment by Tyriar** [comment]
@MarkDHarris I don't think the path is an issue as it should be inherited, the problem sounds like it's because vscode is launched inside a bash login shell whereas you have your setup happening in zsh?

**Comment by MarkDHarris** [comment]
Yes.  To be specific, bash on macOS to launch the "local" instance of vscode and ssh'ing to a remote linux vm running in the cloud where my environment is zsh.  Is that a supported scenario?  (that's why I am so excited about this extension :))

**Comment by Sundayistomorrow** [comment]
I also encountered this problem.
As far as I'm concerned, when the linux server system is centos7, it's  running normally,
but when its system is centos6 , the problem occur. The reason is that the script server.sh required the "realpath" command but it not installed  on centos6 (need to install manually）
centos7 has this command .

**Comment by ahnm** [comment]
I encountered the same problem. Installing realpath with sudo apt-get install realpath helped fix it.

**Comment by Chuxel** [comment]
@Sundayistomorrow See #103 on CentOS 6.

**Comment by LeuisKen** [comment]
> I also encountered this problem.
> As far as I'm concerned, when the linux server system is centos7, it's running normally,
> but when its system is centos6 , the problem occur. The reason is that the script server.sh required the "realpath" command but it not installed on centos6 (need to install manually）
> centos7 has this command .

I also fix this problem by install `coreutils` manually, maybe we should document the `realpath` requirement like `tar` `curl` `wget`. See: https://code.visualstudio.com/docs/remote/faq#_what-linux-packages-or-libraries-need-to-be-installed-on-a-host-to-use-remote-development

**Comment by roblourens** [comment]
If there is still an issue here, please open a new issue. We won't execute non-bash startup scripts manually but you can from your `.profile`
