### ISSUE TITLE
Containers: Files created in container are created with root in local file system

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#860]
- open a remote container from `vsocde-dev-container` 
- when in remote, add some files to the shared folder
- reopen the folder locally
- try to remove the added file, e.g. using git
 -> permission denied

![image](https://user-images.githubusercontent.com/6461412/60334833-b741c700-999c-11e9-9ddc-7cfbb7879c3c.png)

The problem is that docker runs as root .

https://denibertovic.com/posts/handling-permissions-with-docker-volumes/
has a some ideas

**Comment by aeschli** [comment]
http://www.inanzzz.com/index.php/post/q1rj/running-docker-container-with-a-non-root-user-and-fixing-shared-volume-permissions-with-dockerfile

**Comment by chrmarti** [comment]
/duplicate #49 

Forgot we already have that, thanks.
