### ISSUE TITLE
Copilot Chat in Sidebar causes SSH to fail to connect

### ISSUE THREAD

**Issue by Nosrac** [microsoft/vscode-remote-release#8604]
Type: <b>Bug</b>

1. Connect to server via Remote SSH.
2. Make sure Github Copilot Chat is enabled.
3. Put Chat interface in the secondary sidebar

4. Reload Window

VSCode will now timeout when trying to connect via SSH.  Timeout duration doesn't matter.  

5. Wait until sufficiently frustrated, close the secondary sidebar.

6. Reload Window

VSCode will now successfully connect via SSH.

7. Add Copilot Chat to sidebar

VSCode now works as you'd expect.  

[Reloading at this point would cause SSH to timeout again because it's in the sidebar]

Extension version: 0.102.0
VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:17:16.971Z)
OS version: Darwin arm64 22.5.0
Modes:
Remote OS version: Linux x64 5.4.0-149-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|8, 12, 8|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id c8716dbe-f64d-4ce0-8d57-53aa0c8743b2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev|
|OS|Linux x64 5.4.0-149-generic|
|CPUs|AMD EPYC 7713 64-Core Processor (4 x 1999)|
|Memory (System)|7.77GB (6.57GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
pythongtdpathcf:30739705
bgfeh915:30763804
dh2dc718:30763024
pythonnosmt12:30765603

```

</details>

**Comment by Nosrac** [comment]
https://github.com/microsoft/vscode-remote-release/assets/196331/13905de5-a1e9-4778-abb7-c982360dc10c

**Comment by MitchTalmadge** [comment]
Seems like a regression of #7324. I don't think it's related to copilot. Even an empty secondary side bar will prevent SSH from connecting. If I close the secondary (right-side) side bar, SSH will connect.

**Comment by GameTaco** [comment]
Well, I was having problems connecting right after installing the new Copilot Chat extension (I have used the insiders/nightly version without issue) and also found myself unable to connect via ssh under certain conditions. Connecting directly to the machine worked fine, but I couldn't reconnect to some projects after I had already connected to them. It was _only_ projects that I had already connected to, but not all of them... I tried full re-installs of local VSCode, the install on the server, and the server files, re-configuring ssh, deleting caches, increasing time, most of the things recommended on stackoverflow, reinstalling from backup etc.. and could find no similarity between the broken projects, but as soon as I uninstalled the Copilot Chat extension, I was able to reconnect to all of them. Unfortunately I wasn't able to replicate the issue after reinstalling. I should note that before uninstalling, I did try to remove the extension from the sidebar, and switch to the right, but that didn't have any effect on whether or not I could connect. I'm mostly just trying to add info in case it does turn out to be an compatibility issue with the extensions, or if someone stumbles here from Google. 
```
System Info:
Host OS: Win 10 Pro
Virtualization software: Hyper-V
SSH software: OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
Guest OS: Ubuntu 20.04
VSCode version: 1.79.2
Copilot Chat version: 0.2.1
The error was just a generic timeout message I'll see if I can dig it out of a log somewhere.
 ```

**Comment by fadialzammar** [comment]
> I did try to remove the extension from the sidebar, and switch to the right, but that didn't have any effect on whether or not I could connect. 

Did you try closing the secondary sidebar completely, or just removing the extension from it? My issue #8586 is tracking a problem with having the secondary sidebar open at all, regardless of what's in it, like @MitchTalmadge mentioned.

**Comment by roblourens** [comment]
Can you verify whether this is fixed in the latest vscode insiders?

**Comment by cyril-nmpro** [comment]
I am having the same issue... sidebar with codeium chat fails the ssh connection. Workaround is to close sidebar and try again.
