### ISSUE TITLE
Use `docker compose` instead of `docker-compose`

### ISSUE THREAD

**Issue by superlevure** [microsoft/vscode-remote-release#8606]
The extension seems to be using Compose V1 (`docker-compose`) instead of Compose V2 (`docker compose`), which makes it not possible to use new keywords from the [Compose specification](https://github.com/compose-spec/compose-spec) in `docker-compose.yml` like the top level `name` keyword. 

Is there any plan to allow the use of Compose V2?

**Comment by superlevure** [comment]
Found https://github.com/microsoft/vscode-remote-release/issues/8059 in the meantime but it is still unclear to me how to make the extension use Compose V2

**Comment by tbnguyen1407** [comment]
I would also like to switch to new `docker compose` as this now runs as `docker` plugin and not required to be in the `$PATH`

**Comment by HichemAK** [comment]
You can change the default path of docker compose in the DevContainer extension settings

Search for **Docker Compose Path** and replace the current **docker-compose** with **docker compose** (remove the hyphen).

![image](https://github.com/microsoft/vscode-remote-release/assets/45534644/874703e9-0680-4e80-9587-d01ce6bd8249)

**Comment by chrmarti** [comment]
`docker compose` is now the default with `docker-compose` as the fallback.
