### ISSUE TITLE
Fatal Error Please check Developer Tools

### ISSUE THREAD

**Issue by yzy1996** [microsoft/vscode-remote-release#8609]
- VSCode Version: Latest
- Local OS Version: Latest windows/macos/ipados
- Remote OS Version: Latest windows/macos/ipados
- Remote Extension/Connection Type: Tunnels

Steps to Reproduce:

1. Open `vscode.dev` in any web browser.

![image](https://github.com/microsoft/vscode-remote-release/assets/20658350/dc53109f-f5f2-4439-9bf0-931b47dec7ff)

The same with #7443.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by bamurtaugh** [comment]
Thanks for opening! Do you still experience this with the latest version of vscode.dev?
