### ISSUE TITLE
Why vscode-remote ignore .dockerignore file on root of Docker context?

### ISSUE THREAD

**Issue by jeudesprits** [microsoft/vscode-remote-release#861]
Why vscode-remote ignore .dockerignore file on root of Docker context?

**Comment by chrmarti** [comment]
We use `docker build` and don't do anything to ignore `.dockerignore`. Does it work when you build from the command line?

**Comment by jeudesprits** [comment]
> We use `docker build` and don't do anything to ignore `.dockerignore`. Does it work when you build from the command line?

Yes, .dockerignore works, when I build from commandline, but vscode-remote ignoring .dockerignore

**Comment by chrmarti** [comment]
We by default set the context to the `Dockerfile`'s folder. You can override that with the `"context"` property in the devcontainer.json. Can you describe your folder layout? (Where is the devcontainer.json, Dockerfile, .dockerignore?)

**Comment by jeudesprits** [comment]
> We by default set the context to the `Dockerfile`'s folder. You can override that with the `"context"` property in the devcontainer.json. Can you describe your folder layout? (Where is the devcontainer.json, Dockerfile, .dockerignore?)

Current folder layout: 
<img width="375" alt="Screen Shot 2019-07-01 at 15 38 34" src="https://user-images.githubusercontent.com/36597778/60430651-3f330580-9c17-11e9-8c1b-bbb30b25ed1f.png">

But I try set context for both dockerfile.

**Comment by chrmarti** [comment]
I guess devcontainer.json has `"dockerFile": "Dockerfile"` then? That would make the context be the `.devcontainer` folder by default. Could you append the devcontainer.json?

**Comment by jeudesprits** [comment]
> I guess devcontainer.json has `"dockerFile": "Dockerfile"` then? That would make the context be the `.devcontainer` folder by default. Could you append the devcontainer.json?

`{
	"name": "ig-web",
	"dockerFile": "../Dockerfile",
	"context": "..",
	"postCreateCommand": "npm install",
	"extensions": [
		"ms-vscode.vscode-typescript-tslint-plugin",
		"ms-azuretools.vscode-cosmosdb",
		"visualstudioexptteam.vscodeintellicode",
		"mutantdino.resourcemonitor",
	]
}`

`# ls -la
total 216
drwxr-xr-x  22 root root    704 Jul  1 10:28 .
drwxr-xr-x   3 root root   4096 Jul  1 14:01 ..
-rw-r--r--   1 root root  10244 Jun 28 21:37 .DS_Store
drwxr-xr-x   4 root root    128 Jun 29 20:58 .devcontainer
-rw-r--r--   1 root root    155 Jul  1 10:29 .dockerignore
-rw-r--r--   1 root root     93 Jun 30 15:18 .env
-rw-r--r--   1 root root     31 Jun 30 15:27 .env.example
drwxr-xr-x  13 root root    416 Jul  1 11:19 .git
-rw-r--r--   1 root root     18 Jun 27 16:34 .gitattributes
-rw-r--r--   1 root root    287 Jul  1 10:30 .gitignore
drwxr-xr-x   3 root root     96 Jun 28 12:45 .vscode
-rw-r--r--   1 root root    600 Jun 28 16:57 Dockerfile
-rw-r--r--   1 root root      9 Jun 13 10:10 README.md
drwx------  17 root root    544 Jul  1 11:14 chromium
drwxr-xr-x  10 root root    320 Jun 30 15:09 dist
drwxr-xr-x 382 root root  12224 Jun 30 19:46 node_modules
-rw-r--r--   1 root root 163222 Jun 30 19:46 package-lock.json
-rw-r--r--   1 root root   2098 Jun 30 19:46 package.json
drwxr-xr-x   9 root root    288 Jun 30 09:42 src
drwxr-xr-x   3 root root     96 Jul  1 10:28 tmp
-rw-r--r--   1 root root    859 Jun 30 09:50 tsconfig.json
-rw-r--r--   1 root root     81 Jun 28 15:33 tslint.json`

**Comment by chrmarti** [comment]
This works for me. Maybe you are looking at the files in the container at `/workspaces/your-folder`? These are the original files mounted into the container.

If not: What do you get for `docker version` and which files do you see being part of the context and are in the `.dockerignore` file? How do you determine they are in the context and could you attach a minimal example that shows the problem?

**Comment by jeudesprits** [comment]
> This works for me. Maybe you are looking at the files in the container at `/workspaces/your-folder`? These are the original files mounted into the container.
> 
> If not: What do you get for `docker version` and which files do you see being part of the context and are in the `.dockerignore` file? How do you determine they are in the context and could you attach a minimal example that shows the problem?

Yes, in `/workspaces/your-folder `

**Comment by chrmarti** [comment]
That's the mounted folder with the original files. Any changes there are applied to the files on your host machine. That is independent of the build context.

If you want to disable that mount, you could set `"workspaceMount": null` and use `"workspaceFolder": "/root"` in the `devcontainer.json` to let VS Code open some other folder.
