### ISSUE TITLE
Request times out on host when accesing VM, but terminal shows password prompt.

### ISSUE THREAD

**Issue by Arlen22** [microsoft/vscode-remote-release#8616]
Type: <b>Bug</b>

**_Renaming the workspace file solves the problem!_**
- I think this is still an issue because there should at least be a remote-ssh command that does the equivalent of that on the local vscode instance, since I'm assuming that this has something to do with a cache directory or something. 

### Original Report

I'm trying to open a workspace on a guest VM. After waiting 10-15 seconds I get a message `Could not establish connection to "...": Connecting with SSH timed out.` But as soon as the message pops up I see the password prompt in the output window behind it.  I have no idea what the issue is.

I'm using VirtualBox with "bridged adapter" on the ethernet adaptor. The IP address on the host and guest are different and appear correctly assigned. Pings work correctly and copying the command from the output window in the cmd also gives me a password prompt within one second. So it isn't a networking issue between the host and guest. 

I set it to always show the login terminal, and when I type the password into the terminal I get what appears to be the expected output of the server initializing the session, but of course by this time it's too late because vscode has already given up. The other folders I open do not have this problem, as they just ask me to type in the password in the terminal (two terminals) and open up properly. 

Clearing everything except the folder paths from the code-workspace file does not change anything, but that seems irrelevant because it can't even access the file since it can't log in.

- My other computer has no problem opening this workspace file. 
- Trying a different host without setting a public key immedately gives me a rejected login.
- Accessing the guest from the host without a workspace works correctly.
- Accessing a different workspace in the guest from the host also works correctly.
- Accessing the desired folder without opening the workspace works correctly.
- So somehow it seems to be just this specific workspace that gives me problems on this specific computer.

**_Renaming the workspace file solves the problem!_**

Extension version: 0.102.0
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3100 4-Core Processor               (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (35.76GB free)|
|Process Argv|--file-uri vscode-remote://ssh-remote%2Bhost/home/project/main-folder/main-folder.code-workspace --crash-reporter-id 105cc59d-1391-4043-b733-c31e515f32c7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixhidewlkth:30730051
hideindicator:30766889
pythongtdpath:30769146
i26e3531:30769768
dh2dc718:30770000
pythondjangotscf:30768920

```

</details>

**Comment by Arlen22** [comment]
- Trying a different host without setting a public key immedately gives me a rejected login. 
- Accessing the guest from the host without a workspace works correctly.
- Accessing a different workspace in the guest from the host also works correctly.
- Accessing the desired folder without opening the workspace works correctly.

So somehow it seems to be just this specific workspace that gives me problems.

**Comment by roblourens** [comment]
Sounds like https://github.com/microsoft/vscode-remote-release/issues/8586. Can you check whether this repros in the latest Insiders build?

**Comment by Arlen22** [comment]
I didn't check the latest version, but closing and opening the secondary sidebar solved it, as mentioned here: https://github.com/microsoft/vscode-remote-release/issues/7324#issuecomment-1307954310
