### ISSUE TITLE
Access to the shell hosted by VS Code Server

### ISSUE THREAD

**Issue by ruben-fuerst** [microsoft/vscode-remote-release#8619]
Type: <b>Feature Request</b>

Hello,
we are developing C/C++ code where our codebase is stored on a high performance computing cluster (Linux). We use Remote-SSH to connect to it. 
At some points, we have to change our zsh-initialization script, but VS Code does not recognize it, since it seems that the shell initialized by the VS Code server is still running after closing VS Code and the only way we are currently able to restart that shell is by killing the VS Code Server and reinitialize everything (we even had to delete the .vscode-server folder on the remote for that).
For me, this is no problem, but we have students which are not inside that VS Code remote thing (or even into Linux) and its a major inconvenience for them, since they have to ask us for that purpose.
My suggestion is a feature where we can access the actual VS Code Server shell so we can type "source ~/.zshrc" to reload the desired modules.
I would really appreciate such a feature.

Thanks in advance :)
Ruben Fuerst

Extension version: 0.102.0
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 4.18.0-425.19.2.el8_7.x86_64

**Comment by roblourens** [comment]
There isn't such a shell- it's just a running program that has a certain environment that was initialized by your zsh init script. So to get it to pick up the new environment, you have to restart it. You can use the command "Kill VS Code Server on host" to do this cleanly. Sorry for the inconvenience
