### ISSUE TITLE
Unable to start dev-containers: "Cannot read properties of undefined (reading 'files')"

### ISSUE THREAD

**Issue by exhuma** [microsoft/vscode-remote-release#8623]
I'm trying to run dev-containers on a host which is subject to fairly strong restrictions. I'm tasked with identifying issues of exactly this type: identify issues and try find solution to make development with docker work on those machines.

Unfortunately, the issue I have is not detailed enough. The only thing I see in the VS-Code logs is this:

```
2023-06-21 08:47:07.756 [error] TypeError: Cannot read properties of undefined (reading 'files')
	at HH (c:\Users\ti11298\.vscode\extensions\ms-vscode-remote.remote-containers-0.295.0\dist\extension\extension.js:293:49914)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5) remote-containers.reopenInContainer {"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"}
```

It does not tell me the root-cause of the issue. It might point to one of the restrictions in place on my machine which may need to be lifted/modified. But from the error-message I cannot gleam which it might be.

- Remote OS Version: /
- Remote Extension/Connection Type: Containers (v0.295.0)

VS-Code "About" info:

Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by exhuma** [comment]
Attaching to running containers seems to work fine. I can open a WSL shell and run a container with (f.ex.):

```
docker run --rm nginx
```

... and then use the command-palette with "Dev Containers: Attach to running container" to attach to that container. This works without issue. But opening an empty folder, an then executing `Reopen in Container` to get the interactive prompts to generate a dev-container.json file fails with the message above.

When opening a folder with an *existing* `.devcontainer` definition also works without issue. So it seems to be limited to the use-case where a new `.devcontainer` folder needs to be generated.

**Comment by bamurtaugh** [comment]
Thanks for filing. 

> So it seems to be limited to the use-case where a new .devcontainer folder needs to be generated.

Could you share some more info on the restrictions of this machine? This being the only scenario where it fails makes it sound like it could be insufficient permissions for file creation?

**Comment by chrmarti** [comment]
Please also append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)

It looks like running the `templates apply` on the built-in dev container CLI did not return a result.

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/8623.
