### ISSUE TITLE
Remote Explorer and Remote SSH only support 1 user per host

### ISSUE THREAD

**Issue by matthiasgeihs** [microsoft/vscode-remote-release#8629]
I have an ssh config where I have two different users for one host. The config looks something like this:
```
Host 1.2.3.4
  IdentityFile ~/.ssh/user1
  User user1

Host 1.2.3.4
  IdentityFile ~/.ssh/user2
  User user2
```
This works fine with `ssh` on the command line. It will choose the correct identity file depending on the given user (e.g., `ssh user1@1.2.3.4` will use identity file `~/.ssh/user1`).

However, **Remote Explorer and Remote-SSH don't work with this setup and will only recognize the first entry.** That is, Remote Explorer only shows the first user under the host and Remote-SSH will just default to the first user when connecting to the host, without any option to choose a different user.

VSCode Version: 1.79.2
Local OS Version: macOS 13.4.1

(PS: Actually I think that at some point in the past Remote Explorer was indeed capable of showing multiple users per host, but no matter how many times I try refreshing and restarting VSCode I get the same faulty behavior as described above on the current version.)

**Comment by roblourens** [comment]
I'm not convinced that actually works from the command line. I'm trying this test on mac

```
Host 1.2.3.4
	User user1
	LogLevel DEBUG3

Host 1.2.3.4
	User user2
	LogLevel DEBUG1
```

When I run `ssh user2@1.2.3.4`, it runs with LogLevel=DEBUG3. What you describe doesn't match my understanding of how ssh config files are interpreted. Are you sure there isn't something else going on?

**Comment by matthiasgeihs** [comment]
I tested it again to be sure: Executing `ssh user1@1.2.3.4` will pick `~/.ssh/user1` and `ssh user2@1.2.3.4` picks `~/.ssh/user2`. (obviously user1, user2, and 1.2.3.4 are just replacements for real user names and IP)

Have you been able to test with different identity files for the same host? (instead of LogLevel)
(Maybe also try to place `User` as last argument?)

In any case: I am not saying that this is the intended behavior of ssh across different systems. In fact, when I searched for alternative ways to configure what I need, I found that one can also use a `Match` statement in the config file. However, that didn't work with VSCode either.

Any suggestions how I can make VSCode let me login to the same host with different users?

**Comment by roblourens** [comment]
Trying this

```
Host 168.62.29.176
	IdentityFile ~/.ssh/keyfile1
	User user1

Host 168.62.29.176
	IdentityFile ~/.ssh/keyfile2
	User user2
```

Interesting, it actually tries both for me

```
debug1: Trying private key: /Users/roblou/.ssh/keyfile1
no such identity: /Users/roblou/.ssh/keyfile1: No such file or directory
debug1: Trying private key: /Users/roblou/.ssh/keyfile2
no such identity: /Users/roblou/.ssh/keyfile2: No such file or directory
```

I wonder if it's doing the same thing in your case and just ending up with the one that worked for that user.

In any case, in the semantics of ssh config files as I understand it, these shouldn't really be considered two separate "entries" for the same remote. You can make this work in vscode by setting up two different names for the host with all different parameters, and that would be less typing for the command line too.

**Comment by matthiasgeihs** [comment]
@roblourens I was wondering, how I did arrive at this "unusual" SSH config file. I think actually VSCode created this for me. Try setting up two different SSH users with the same host through VSCode Remote Explorer and you'll probably end up with a similar SSH config. Maybe worth considering revising the "Add New SSH Host" command flow?
