### ISSUE TITLE
/root/.gitconfig is directory in  remote container 

### ISSUE THREAD

**Issue by dreamrororo20** [microsoft/vscode-remote-release#863]
- VSCode Version:1.35
- Local OS Version:10.14
- Remote OS Version:CentOS Linux release 7.6.1810 (Core)
- Remote Extension/Connection Type: Docker

When I am developing inside a container on a remote Docker host, I found /root/.gitconfig is a directory rather than a file in container.

My terminate shows (/Users/dragon/.gitconfig is a local file):

Run: docker run -a STDOUT -a STDERR --mount src=/home/yinlh/workspace,dst=/workspace,type=bind -v /Users/dragon/.gitconfig:/root/.gitconfig -l vsch.quality=stable -l vsch.local.folder=/Users/dragon/remote-container-projects -l vsch.remote.devPort=0 --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v /mnt:/mnt vsc-remote-container-projects-a58d60ff0de94a3051e873a762b0b3db /bin/sh -c echo Container started ;  while sleep 1; do :; done

when I use git clone  , there are some error message as follows,
warning: unable to access '/root/.gitconfig': Is a directory
fatal: unknown error occurred while reading the configuration files

**Comment by dreamrororo20** [comment]
I must set workspaceFolder and workspaceMount because I need install extensions.

**Comment by chrmarti** [comment]
/duplicate #509

We now copy `.gitconfig` to the container if it is a file.
