### ISSUE TITLE
[Remote-SSH Bug]: "Enter SSH Connection Command" Input Dialog backslash bug

### ISSUE THREAD

**Issue by mbrotos** [microsoft/vscode-remote-release#8631]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Backslashes in the ssh connection input dialog should be properly escaped. 

This bug makes enterpise-level window server ssh workflow more unpleasant than it already is(:

### Steps To Reproduce

1. Create ssh config from vscode UI
2. Test connection: `ssh domain\username@SERVERNAME -A`
3. Open ssh config file and see bug

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

### Anything else?

Test input with backslash domain in the user:
![image](https://github.com/microsoft/vscode-remote-release/assets/44556562/d886badc-45a1-4ec6-9e0c-6aee70e9686a)

Bug: The backslash was not escaped properly 
![image](https://github.com/microsoft/vscode-remote-release/assets/44556562/14235ba1-5a04-4ae4-a4a1-842fc445f760)

**Comment by roblourens** [comment]
You will need to double-up the backslash, this field is interpreted like bash (maybe this is unexpected on windows)
