### ISSUE TITLE
Dev Container ripgrep high CPU usage

### ISSUE THREAD

**Issue by heing** [microsoft/vscode-remote-release#8635]
- VSCode Version: 1.79.2
- Local OS Version: Debian 11.7
- Remote OS Version: N/A
- Remote Extension/Connection Type: Containers

- Logs:
`2023-06-23 10:10:15.987 [debug] ExtHostSearch /usr/share/code/resources/app/node_modules.asar.unpacked/@vscode/ripgrep/bin/rg --files --hidden --case-sensitive -g '/{.devcontainer.json,.devcontainer/devcontainer.json,.devcontainer/*/devcontainer.json}' -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/Thumbs.db' --no-ignore --follow --no-config --no-ignore-global`

Steps to Reproduce:

1. Install Dev Containers extension
2. Open a project with a very large folder locally
3. Observe CPU usage of the rg process

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

The problem is that when searching for a devcontainer.json file, the ripgrep process does not respect the .gitignore file or the VS Code search settings. When the project contains a very large folder, like a Yocto build folder, the search will use a lot of CPU for a very long time. This happens locally when the Dev Container extension is installed, but only on projects which does not have a .devcontainer.json file.

**Comment by andreamah** [comment]
Some questions:
Is your gitignore at the root of the directory? 
Did you set `search.useIgnoreFiles` to true? 
Is your folder initialized as a git repo?

**Comment by heing** [comment]
> Some questions: Is your gitignore at the root of the directory? Did you set `search.useIgnoreFiles` to true? Is your folder initialized as a git repo?

Yes, I did.

**Comment by andreamah** [comment]
Yes to all of them? Are you referring to ignores that are in a global file? is github respecting the ignores?

**Comment by heing** [comment]
Yes, I have a .gitignore in the root of the project and search.useIgnoreFiles is the default setting. Local git is respecting the .gitignore. If you look at the command line below, it seems like it explicitly ignores local and global .gitignore (the --no-ignore and --no-ignore-global flags):
`/usr/share/code/resources/app/node_modules.asar.unpacked/@vscode/ripgrep/bin/rg --files --hidden --case-sensitive -g '/{.devcontainer.json,.devcontainer/devcontainer.json,.devcontainer/*/devcontainer.json}' -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/Thumbs.db' --no-ignore --follow --no-config --no-ignore-global`

**Comment by chrmarti** [comment]
Fixing this in https://github.com/microsoft/vscode-remote-release/issues/9738
