### ISSUE TITLE
Version lenses are quite slow

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-remote-release#8649]
Testing #8646

* Follow the steps in the linked TPI
* 🐌 the code lenses take quite some time to update

https://github.com/microsoft/vscode-remote-release/assets/1794099/09def38a-c9f6-4ea1-884c-828080a7989b

**Comment by chrmarti** [comment]
Fixed in Dev Containers 0.298.0-pre-release.

**Comment by rzhao271** [comment]
Verified, but it takes a while for them to show up in the first place.
