### ISSUE TITLE
WSL extension can't find WSL

### ISSUE THREAD

**Issue by Victor-Botelho** [microsoft/vscode-remote-release#8650]
Type: <b>Bug</b>

VS Code Insiders:
- 1.80.0-insider
- 45b31e9a872da8cc3cc8fff41c1eeb2063be04b7
- x64

VS Code WSL extension:
- versions 0.80.0 and 0.80.1

WSL version 2
Windows 10

When opening VS Code Insiders with specified versions above, WSL extension can't seem to find the WSL resource.

Fixed the issue simply by rolling back the extension version back to 0.79.0

Extension version: 0.79.5
VS Code version: Code - Insiders 1.80.0-insider (45b31e9a872da8cc3cc8fff41c1eeb2063be04b7, 2023-06-27T05:33:23.513Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (16.77GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/victor --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1689)|
|Memory (System)|15.49GB (13.82GB free)|
|VM|0%|
</details>

**Comment by cquick01** [comment]
#8643

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/8643.
