### ISSUE TITLE
WSL not detected in Windows 10 (with fix)

### ISSUE THREAD

**Issue by phildaniels** [microsoft/vscode-remote-release#8651]
I get the error message "Windows Subsystem for Linux not detected. The WSL extension requires Windows 10 with the Windows Subsystem for Linux feature installed." 

Digging into the extension (which is obfuscated) looks like the error is here, maybe someone forgot a return statement?

![image](https://github.com/microsoft/vscode-remote-release/assets/11820265/d917da3b-b8f2-46e9-b341-57f30d9e3cbc)

Adding the code directly in the extension.js file seems to fix it for me. Just FYI for this team

- VSCode Version:
Version: 1.80.0-insider (system setup)
Commit: b4952d14a465572e33f0635ef58de089227b8876
- Local OS Version:
Date: 2023-06-26T05:32:56.741Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

- Remote OS Version:
WSL2
Distributor ID: Ubuntu
Description: Ubuntu 22.04.2 LTS
Release: 22.04
Codename: jammy
- Remote Extension/Connection Type: WSL

- Logs:

Steps to Reproduce:

1. Open WSL in windows 10 using wsl extension version 0.80.1. Maybe more versions

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by maxshlain** [comment]
happens on insiders build:
wsl ubuntu is running on background
vscode insider fails to connect to it (official version works fine for me)
![image](https://github.com/microsoft/vscode-remote-release/assets/212429/275d80d2-2336-441c-a978-b165fdf8f283)

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/8643. Thanks.
