### ISSUE TITLE
Access host chrome from vscode devcontainer

### ISSUE THREAD

**Issue by RaviTejaVattem** [microsoft/vscode-remote-release#8652]
I am wondering if there is a way to access the chrome installed on host machine(Mac) from vscode devcontainer?

I have a devcontainer.json file as follows

```json
{
    "name": "Node.js",
    "build": {
        "dockerfile": "Dockerfile"
    },
    "remoteEnv": {
        "TEST": "${localEnv:TEST}",
        "CHROME_BIN": "${containerEnv:PATH}:/Applications/'Google Chrome.app'/Contents/MacOS/'Google Chrome'"
    }
}
```
I want to run jasmine tests from the container which is expecting "CHROME_BIN" env variable which should be a chrome binary.

When I spin-up the container with the above configuration, karma launcher is unable to find chrome(In other words the docker container is unable to locate host machine's chrome with CHROME_BIN variable I set).

BTW I do not want to run chrome in headless mode inside my docker container.

I already asked the same question in [stackoverflow](https://stackoverflow.com/questions/76536083/access-host-chrome-from-vscode-devcontainer) and [devcontainers-spec](https://github.com/devcontainers/spec/issues/266) but couldn't get any help.

- VSCode Version: 1.79.2 (Universal)
- Local OS Version: 13.4 (22F66)
- Remote OS Version: any alpine
- Remote Extension/Connection Type: Containers/WSL/Server: Containers

Steps to Reproduce:

1. Spin up a vscode dev container with jasmine tests.
2. Run the tests and notice "Unable to locate chrome_bin error".

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
If you install an xserver locally, the Dev Containers extension will forward the display into the container and you could run Chrome inside the container using your local machine's display.

There is no way to launch a binary on the local machine from within the container currently.

**Comment by RaviTejaVattem** [comment]
Thank you for the details @chrmarti.

I can't install xserver to do this job.

Please let me know if it is something that is achievable so that I can make a feature request.

Dev containers are helping me to skip local installation by taking everything to container, but this issue is limiting its full scale experience as I cannot run and debug stuff with chrome UI.

I understand that tests are usually run in headless mode inside the containers till date but it would be great if I can get full developer experience by being able to access or run any required host programs(chrome in my current scenario) from the dev containers.

**Comment by RaviTejaVattem** [comment]
I am able to access chrome ui from the dev-container forwarded port.

Hence closing this issue.
