### ISSUE TITLE
"Delete Codespace..." option seems out of place

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-remote-release#8653]
Testing microsoft/vscode#186222

Considering that this menu is for connecting to a remote source, this doesn't feel like the right place to have a `Delete Codespace...` option.
![image](https://github.com/microsoft/vscode/assets/10833267/e587849e-5c0e-428a-bce3-eb582a7858c9)

**Comment by bhavyaus** [comment]
This is a question for the Codespaces team since they're contributing to the `statusBar/remoteIndicator` menu which is being shown here. @joyceerhl who is a good person to reach out to/transfer this issue to? Thanks!

**Comment by joyceerhl** [comment]
@jkeech can we please consider removing Delete Codespace from the remote indicator?

**Comment by jkeech** [comment]
Yes, I think it's fair to remove the `Delete Codespace...` command from the remote indicator. We can do that in an upcoming extension release.

**Comment by joyceerhl** [comment]
Confirmed that `Delete Codespace` is no longer in the remote indicator, thank you!
