### ISSUE TITLE
remote-ssh

### ISSUE THREAD

**Issue by xuzhou2016** [microsoft/vscode-remote-release#8658]
Type: <b>Bug</b>

Hello:
    My host is windows 11 home edition, and vscode version is Version: 1.79.2.
When I install virtualbox7 for windows,  and start a virtual machine of ubuntu23.  By port forward, ( host port 22 -> virtual machin  port 22)  I can visit ubuntu23 using ssh.   But I cannot access ubuntu23 by vscode extension
-- Remote SSH,  please help me. 
Thanks

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Connection to 'SSH' could not be established  Connecting was canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (18.48GB free)|
|Process Argv|--crash-reporter-id 8199e5a5-8d71-47d3-9d37-6000e41bcc5e|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH' could not be established  Connecting was canceled
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30773603
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
bgfeh915:30769767
e440d664:30770001
pythonidxpt:30772539
pythondjangotscf:30772537
pythonnocebcf:30773527

```

</details>

**Comment by roblourens** [comment]
@xuzhou2016 see the wiki at https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting, see whether any tips there help, and if not please share the output channel log
