### ISSUE TITLE
Can not initialize remote vs code server[error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol Unable to establish]

### ISSUE THREAD

**Issue by Hollyen** [microsoft/vscode-remote-release#866]
Issue Type: <b>Bug</b>

I connect to Ubuntu 16 machine, which using http proxy to access web;

I got below exception when i click connections to the machine:
```bash
remote-ssh@0.42.2
SSH Resolver called for "ssh-remote+100.94.8.139"
SSH Resolver called for host: 100.94.8.139
Setting up SSH remote "100.94.8.139"
Using commit id "c7d83e57cd18f18026a8162d042843bda1bcf21f" and quality "stable" for server
Install and start server if needed
> 
> Installing to /root/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f...
> 
> Downloading with wget
> 
> OpenSSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol Unable to establish SSL connection.
> dfca0078-4dee-40eb-bcbe-351956f80166##25##
> 
"install" terminal command done
Received install output: dfca0078-4dee-40eb-bcbe-351956f80166##25##
Server download failed
Downloading VS Code Server failed. Please try again later.

```

Extension version: 0.42.2
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.1.7601
Fetching remote diagnostics for 'SSH' failed: Downloading VS Code Server failed. Please try again later.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.99GB (10.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: Downloading VS Code Server failed. Please try again later.
</details>

**Comment by roblourens** [comment]
It looks like your proxy does not like https or does not understand SSL2.3, is that possible?
