### ISSUE TITLE
vscode-server: Unauthorized client refused.

### ISSUE THREAD

**Issue by GMHDBJD** [microsoft/vscode-remote-release#8660]
- VSCode Version: VS Code Server 20220909.27
- Local OS Version: chrome
- Remote OS Version: ubuntu 22.04
- Remote Extension/Connection Type: Server

- Logs:
```
[2023-06-29 11:09:12] info Starting server...
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Server bound to 0.0.0.0:9527 (IPv4)
Extension host agent listening on 9527

[11:09:12] 




Web UI available at http://localhost:9527/?tkn=e01aa24a-3c34-4486-968c-7a07bd8b0249
[11:09:12] Extension host agent started.
[11:09:50] [10.2.4.254][f779ce18] Unauthorized client refused.
[11:09:50] [10.2.4.254][a3eadd08] Unauthorized client refused.
```
Steps to Reproduce:

1. run vscode-server serve-local
2. connect via web browser

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by wangzhe258369** [comment]
Perhaps VS Code 1.78.2 is the last version that supports code server? VS Code 1.79 and newer versions do not work.

```
code-server serve-local --accept-server-license-terms --commit-id b3e4e68a0bc097f0ae7907b217c1119af9e03435
```

**Comment by bamurtaugh** [comment]
Thanks for your issue! If you're using the `code-server` CLI, please go ahead and switch over to the `code` CLI instead - we made the switch in our November 2022 release: https://code.visualstudio.com/updates/v1_74#_remote-development.

I'll close this issue for now, but if you have other questions, please don't hesitate to share them. Thanks!

**Comment by fvannee** [comment]
I have an additional question on this. It looks like with `code` cli it is not possible to access the server from a webbrowser directly (without going through vscode.dev). Does this mean it is not possible anymore to use the `serve-local` functionality anymore, but everything has to go through vscode.dev?

**Comment by bamurtaugh** [comment]
I believe what you're looking for is tracked in this feature request: https://github.com/microsoft/vscode/issues/168492.
