### ISSUE TITLE
rg.exe in big repo installed uses 8% CPU and 600MB Ram just watching for devcontainer.json etc. Sometimes even vscode crashes with OOM (Devcontainer Ext)

### ISSUE THREAD

**Issue by RobIsHere** [microsoft/vscode-remote-release#8661]
(The other rg.exe of the two is caused by a php extension)

At Home it just tries to empty the power plant, but on the go it successfully empties my laptop battery - that's the main problem!

I have also Java Extensions and others installed that somehow manage to not use up the whole battery. It's only you and php by devsense. So there is probably another way to do this searching like the other extensions do it without having an own power plant at home.

![image](https://github.com/DEVSENSE/phptools-docs/assets/13229377/448a6a9f-97df-4719-93a0-8be2a24b87d7)
![image](https://github.com/DEVSENSE/phptools-docs/assets/13229377/a6e75277-23b5-4a14-9971-b1c2857843a2)

See also https://github.com/DEVSENSE/phptools-docs/issues/358 having this issue too. So I have this problem twice.

**Comment by andreamah** [comment]
Does this still happen with all extensions disabled? If not, then this should only be filed with devsense's repo.

**Comment by RobIsHere** [comment]
Hi! Yesterday there was just the one devcontainer rg.exe in the process manager anymore because I had uninstalled the devsense extension before. 

The folders I'm working with have a lot of build files and such stuff in it that cannot be excluded. But anyhow a search for a devcontainer file should not get out of control like this.

Also my devcontainer is not opened as it should. I have to manually start it with docker and docker exec bash into it. 

I can't disable the extensions because I don't know exactly how to reproduce the problem. It just appears during work. But it has some relation to the workspace/folders opened because once there the problem restarts when I restart vscode. So it is somehow dependent on state that is remembered by vscode across restarts.

That's all I know.

**Comment by RobIsHere** [comment]
At the ripgrep manpage there is a command line option "--max-depth".
Restricting the search depth to a sane but high enough value could help?

10 maybe by default as it would be very unusual to have a config file like devcontainer.json file in a deeper nested folder?

**Comment by andreamah** [comment]
If you do the following, what do you get?

1. run `Developer: Set Log Level`  in the command palette and set `Trace`
2. do a search
3. In the bottom panel, check logs in the `Extension Host (Remote)` channel in the `Outputs` tab.

Is there a line that starts sort of like this?
```
RipgrepSearchEH#search c:\Users\andreamah\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\@vscode\ripgrep\bin\rg.exe 
```

Then, if you invoke rg.exe directly from the command line, what type of performance do you get? I just want to double-check that it's ripgrep lacking in performance here and not something else.

**Comment by RobIsHere** [comment]
As I said above: I don't know exactly how to reproduce the issue. That's equally true for the command line as for using vscode.

The task manager screenshots point rather clearly to rg.exe twice so I have no doubt on this. The rg.exe are also consuming a huge amount of memory, So it's running long and building up memory.

If you want to go for the root cause: my experience tells me that there is some rare condition that causes a cycle in ripgrep. I even looked into rg source code and checked if there is some protection against cyclic links - there is. First I would look for rare conditions that are not properly handled there. The fact that the memory usage is quite high points to sections in the program where memory can build up quickly. The cycle-prevention is one of these places. That's if you love a challenge ;) 

Anyhow this bugfixing without an exact reproduction is rather advanced and requires years of experience with low level languages to get a quick result. The second best and a rather quick fix is to break otherwise - that's why I think max-depth is going to work. 

And by the way: running a search or something like that with absolutely no restriction while knowing nothing about neither the folder nor the speed of the file system is not best practice at all. So you get two things by max-depth: just a better program if I'm wrong and protection from cycles by an additional break criteria if I'm right :)

**Comment by RobIsHere** [comment]
Additional information: the process sometimes also crashes with an OOM (out of memory error). But it takes a very long time, about an hour after it get's out of control eating processor and memory.
I have 16GB of RAM installed minus 5GB dedicated to hyper-v.

**Comment by andreamah** [comment]
I can consider this as a feature request for a setting for `max-depth`, but re-setting the default for everyone might interfere with flow for some users.

**Comment by RobIsHere** [comment]
Thank you! 

I want to add another perspective: the extension developers are using this functionality for searching for extension specific files in the project directory.

An extension developer often knows where he expects the files belonging to his extension to be placed. So if the extension developer could optionally pass max-depth as a parameter to the search, he can most effectively restrict the search. 

Therefore you do not need re-setting the default for everyone to get a lot of issues with extensions resolved. The extension developer can do that for you.

Maybe that's easier than communicating to every impacted user that he needs to set max-depth?

**Comment by andreamah** [comment]
Oh ok, was your `rg.exe` instance that ran for a long time from the remote extension? Or were you explicitly making a search?

**Comment by RobIsHere** [comment]
Uninstalling all other extensions did _not_ help!

**Comment by RobIsHere** [comment]
The extensions are calling the createFileSystemWatcher() API described at https://code.visualstudio.com/api/references/vscode-api  which causes rg.exe to run (see the linked other extension in issue description, where the developer points there)

**Comment by chrmarti** [comment]
FYI: I'm improving the search for devcontainer.json files in https://github.com/microsoft/vscode-remote-release/issues/9738.
