### ISSUE TITLE
Unable to connect to my ec2 instance via vscode

### ISSUE THREAD

**Issue by tseladev** [microsoft/vscode-remote-release#8664]
Type: <b>Performance Issue</b>

 but I have double checked and there is nop issue with my server, I am able to connect using my mobaxterm 

Extension version: 0.102.0
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 6.2.9200
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i3-1215U (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (0.42GB free)|
|Process Argv|--crash-reporter-id 22f45412-e7dc-4f76-9fef-edf32fd59b9f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   113	 41784	code main
    0	   134	  8212	window [1] (Welcome - Visual Studio Code)
    0	   179	  9092	   gpu-process
    0	    95	 14656	extensionHost [1]
    0	    80	 21328	fileWatcher [1]
    0	    45	 41584	   utility-network-service
    0	    30	 42152	   crashpad-handler
    0	    99	 43428	shared-process
    0	    93	 45896	window [2] (Issue Reporter)
    0	    58	 47872	ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
pythonnosm12tcf:30779713
pythonidxptcf:30772540
pythonnocebcf:30776496

```

</details>

**Comment by bamurtaugh** [comment]
Can you please share more info so that we can further assess and potentially try to repro? i.e. which extension and VS Code version you're using, steps, your full output logs. Thanks!
