### ISSUE TITLE
Use locally installed formatter

### ISSUE THREAD

**Issue by Morgy93** [microsoft/vscode-remote-release#867]
I cannot find related issues, nor am I able to get it to work, so I think a feature request fits best. 🤷‍♀ 

I'd like to use my locally installed formatters on remote files, so I don't have to install every formatter on each host.
I tried `bmewburn.vscode-intelephense-client` for php files, `esbenp.prettier-vscode` for css and even `dotjoshjohnson.xml` for xml files, but none of them work if the `remote.extensionKind` is set to `ui`.
I just get the message that there is no formatter installed for that filetype.

So am I doing something wrong, does the extension need some support for that or does it simply not work?

**Comment by egamma** [comment]
When an extension is ran as UI extension, then the extension needs to explicitly support it. When run as a UI extension then the extension cannot access workspace files. We have an API proposal that enables an extension to access files through a file system provider. 

Bottom line, this needs to be supported by an extension, therefore please file feature requests against the corresponding extensions.

**Comment by Chuxel** [comment]
@Morgy93 You may also be interested in up-voting #157. You can also use "remote.SSH.defaultExtensions" in settings.json to specify a list of IDs that should always be installed on a new host.

**Comment by Morgy93** [comment]
Yes and that works fine, except: #855
