### ISSUE TITLE
Connect to remote server without tunnel

### ISSUE THREAD

**Issue by guw** [microsoft/vscode-remote-release#8672]
It should be possible to connect to a remote running VS Code server directly, i.e. without setting up a tunnel. We cannot use tunneling or SSH in our network.

Please provide documentation how to connect directly assuming the domain name or IP address of the running VS Code server is known. Also document which ports need to be accessible for websocket/https connectivity.

Goal: user is able to connect locally running VS Code instance to a remote server endpoint via https directly without a tunnel.

**Comment by Igorgro** [comment]
You can setup self-hosted (http) vscode server instance https://github.com/microsoft/vscode/issues/135856#issuecomment-1170091265

**Comment by guw** [comment]
@Igorgro I am thinking about running a local VS Code client (Electron app) and connecting to a remote. Similar to IntelliJ Gateway. I know about VS Code server and using it in a browser.

**Comment by bamurtaugh** [comment]
Thanks for opening! I believe this is covered by https://github.com/microsoft/vscode/issues/168492, so closing this as a dupe. If this is a different request, please just let me know.

**Comment by guw** [comment]
@bamurtaugh I think it's a different request. Reading though https://github.com/microsoft/vscode/issues/168492 it looks like this is a VS Code server people can connect to via web browser. That's actually what we are using today.

What we would like is to *avoid* the browser and use VS Code directly as client. Similar to what JetBrains offers with IJ Gateway.

**Comment by guw** [comment]
It can be setup on premise with server process running on individual vms/containers. With SSH the benefit is that the server process will be managed from the client. However, the server itself supports arbitrary socket connection (websockets). 

We [published a plugin](https://github.com/salesforce/secure-pomerium-tunneler) to access it via an IAP. We would love to implement similar thing for VS Code if there is any API and such a possibility for VS Code to be a client UI.

**Comment by bamurtaugh** [comment]
cc @connor4312 would be great to get your thoughts here

**Comment by guw** [comment]
@connor4312 To clarify we are not asking for any kind of authentication. Our ask would be for a direct web socket connection.

As far as "esoteric" is a concern: firewall and compliance rules, https is ok 🤷

**Comment by nxphi47** [comment]
+1 My organization setup is like this:
* coder-server is served from the server via `0.0.0.0:1234`
* This `0.0.0.0:1234` can only be accessible through some abstractive cloud domains like "mycloud.vscode.xyz/my_instance"
* I can also go to that link the access the server's terminal and run anything I like.
* There is no way to ssh to the server from my laptop
* Cannot tunneling via a public relay (github tunnel) as that will violate security policy
* I can access vscode web version with chrome by going to `mycloud.vscode.xyz/my_instance`, which has terrible performance and limited

I want the local vscode app to connect to my server using the link above the same way Remote SSH works

Please help, even if you have a workaround also good.

**Comment by connor4312** [comment]
You may want to watch https://github.com/microsoft/vscode/issues/168492, might have news on that front soon

**Comment by OneCyrus** [comment]
@connor4312 now that your mentioned issue is closed does that really address this issue here? it looks like it still only supports access through a browser.
