### ISSUE TITLE
[Remote-SSH Bug]: "Connect to Host..." drop down does not show hosts in config include

### ISSUE THREAD

**Issue by J-Siu** [microsoft/vscode-remote-release#8674]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Host defined in include should show in drop down:

![Screenshot 2023-07-01 at 11 27 17 PM](https://github.com/microsoft/vscode-remote-release/assets/3171920/088e1238-c86e-4265-a68c-c978638d3ef9)

### Steps To Reproduce

1. Create a file ~/.ssh/host.conf
2. Put following in the file
```
host test
```
3. Add following line in ~/.ssh/config
```
Include host.conf
```
4. In vscode, click the lower left connect icon
5. Click 'Connect to Host...'
6. The host `test` is not shown in the drop down

### Remote-SSH Log

Does not apply for this issue.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/4339
