### ISSUE TITLE
Easy switching with multiple devcontainer.json configurations.

### ISSUE THREAD

**Issue by jtkiley** [microsoft/vscode-remote-release#8678]
Currently, if you have multiple `devcontainer.json` specifications, and you want to switch between them, you need to do the following:

1. Click the Dev Containers control (bottom right).
2. Reopen Folder Locally (at the top)
3. Reopen in Container (from the popup or going back to the control)
4. Choose the container configuration.

It would be really nice if there were a faster option. Perhaps:

1. (Better) Click the Dev Containers control, and have options for the other container configurations (i.e. "Switch to `[name]`"). You could imagine a limit on how many of those options are presented, with a "Switch to another..." option for overflow. (This collapses 2-4 into a single click.)
2. (Good) Click the Dev Containers control, have an option for "Switch to another container", and have that pop up the chooser. (This collapses 2-3 into a single click.)

Aside/root cause: part of the issue here is that moving from the bottom left to the top center is a long way on a big monitor, so the friction here feels a lot more significant in that case (compared to, e.g., a laptop).

**Comment by chrmarti** [comment]
I will add a "Switch Container" command to the Command Palette. We are trying to keep the number of entries in the remote indicator menu (triggered on the green lower left corner) minimal because that is shared with other remote extensions and can become long already now.

**Comment by DonJayamanne** [comment]
Works well, great feature, will use this for testing Jupyter extension in multiple containers, a number of steps reduced to 2 clicks.
Love it.
