### ISSUE TITLE
Open more than one WSL window

### ISSUE THREAD

**Issue by ridhwaans** [microsoft/vscode-remote-release#8679]
With VSCode you are able to connect to a running docker instance
After that you can open a WSL window based on a workspace folder in the remote container 
However, you cant open multiple WSL windows if you need to choose to open another folder in the same docker container
You have to close and re-open the remote VSCode window
![image](https://github.com/microsoft/vscode-remote-release/assets/1103336/83755e63-de01-494c-85a8-ace8747a99d5)
Allow having more than one WSL window open

**Comment by bamurtaugh** [comment]
Thanks for opening. To ensure I fully understand your request, could you share the exact sequence of commands you tried, and the actual vs desired output of them?

Also the screenshot appears to be from an older version of VS Code - please be sure to update you VS Code too!

**Comment by bamurtaugh** [comment]
No worries! Thanks for letting us know!
