### ISSUE TITLE
Orphan vscode-server in WSL 2

### ISSUE THREAD

**Issue by KyivJunta** [microsoft/vscode-remote-release#868]
- VSCode Version: 1.35.1
- Local OS Version: Microsoft Windows 10 Pro Insider Preview 10.0.18922 Build 18922
- Remote OS Version: Linux alpha 4.19.43-microsoft-standard #1 SMP Mon May 20 19:35:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Remote Extension/Connection Type: WSL

Steps to Reproduce:
1. Open folder from WSL 2 environment
2. Close workspace/editor
3. Use [h]top to investigate running processes, obviously

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

![Annotation 2019-06-30 151811](https://user-images.githubusercontent.com/1730837/60396499-12b1b780-9b4b-11e9-9e63-555521ae0789.png)

**Comment by aeschli** [comment]
duplicate of #699
