### ISSUE TITLE
Error "no secret key error" when sharing GPG Keys from Windows to Docker container

### ISSUE THREAD

**Issue by gremo** [microsoft/vscode-remote-release#8680]
- VSCode Version: 1.79.2 
- Local OS Version: Windows 11
- Remote OS Version: Debian 12 (bookworm)
- Remote Extension/Connection Type: Containers

Steps to Reproduce:

1. Follow the [official documentation](https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials#_sharing-gpg-keys) and add a GPG key in Windows using [Gpg4win](https://www.gpg4win.org/) (using Kleopatra GUI)
2. Ensure container has `gpg` and `gnupg2`
2. Run `echo test | gpg2 --clearsign` inside the container

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

I get the following error running `echo test | gpg2 --clearsign` (it works on the host) inside the container:

```bash
root@4a09cf30bfae:/var/www/html# echo test | gpg2 --clearsign
gpg: no default secret key: No secret key
gpg: [stdin]: clear-sign failed: No secret key
```

Version check inside the container:

```bash
root@741303da2f51:/var/www/html# apt list gpg   
Listing... Done
gpg/stable,now 2.2.40-1.1 amd64 [installed,automatic]

root@741303da2f51:/var/www/html# apt list gnupg2
Listing... Done
gnupg2/stable,now 2.2.40-1.1 all [installed]
```

Excerpt from Visual Studio Code container log:

```log
[10776 ms] Start: Run in container: gpgconf --list-dir agent-socket
[10778 ms] /root/.gnupg/S.gpg-agent
[10778 ms] 
[10778 ms] Start: Run in container: gpgconf --list-dir homedir
[10780 ms] /root/.gnupg
[10780 ms] 
[10780 ms] Start: Run in container: ls '/root/.gnupg/private-keys-v1.d' 2>/dev/null
[10783 ms] 
[10783 ms] 
[10783 ms] Exit code 2
[10783 ms] Start: Run: gpgconf --list-dir agent-extra-socket
[10792 ms] gpg-agent: No agent-extra-socket found on local host.
```

**Comment by chrmarti** [comment]
The locally run `gpgconf --list-dir agent-extra-socket` does not return a socket path. Please check your local GPG configuration (e.g., `~/.gnupg/gpg-agent.conf`).
