### ISSUE TITLE
WSL can't connect to VS Code after it updated

### ISSUE THREAD

**Issue by nuked44** [microsoft/vscode-remote-release#8684]
- VSCode Version: 1.79.2
- Local OS Version: WindowsNT x64 10.0.19045
- Remote OS Version: Ubuntu 22.04.1 LTS
- Remote Extension/Connection Type: WSL

- Logs: 
[03:00:03.821] Log Level: 2
[03:00:03.893] VS Code version: 1.79.2
[03:00:03.893] Remote-SSH version: remote-ssh@0.102.0
[03:00:03.894] win32 x64

Steps to Reproduce:

1. typed "code ." in wsl terminal
vs code updated, refused to connect 
after restarting my pc and typing "code ." in wsl terminal it responds with:

`Updating VS Code Server to version 660393deaaa6d1996740ff4880f1bad43768c814
Removing previous installation...
rm: cannot remove '/home/nuked/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node_modules/debug': Read-only file system
rm: cannot remove '/home/nuked/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node_modules/es6-promise/package.json': Read-only file system
rm: cannot remove '/home/nuked/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node_modules/es6-promise/auto.js': Read-only file system

...

rm: cannot remove '/home/nuked/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/bootstrap-amd.js': Read-only file system`

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by nuked44** [comment]
after following https://github.com/microsoft/WSL/issues/6220
i now get the error: 
`/home/nuked/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/bin/remote-cli/code: 12: /home/nuked/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node: Exec format error`

when trying to run code .

**Comment by chrmarti** [comment]
The folder `695af...` is for VS Code 1.79.2. I guess that folder might be incomplete or corrupt, try removing the `695af...` folder completely, it will be reinstalled when you use 1.79.2 the next time.

**Comment by AhmadMayo** [comment]
I think I have the same issue. Here's what happens:
- VS code detects newer version -> update to v1.80.0
- After a while VS code detects another new version -> downgrades to v1.79.2 !!
- After the restart wsl extension is not working, and the error message is that it's not compatible with this version of VS code
- Restarting the app from Ubuntu or windows has the same result
- Deleted VS code, and re-installed from the store
- After a while VS code detects a new version, and then downgrades to 1.79.2 again, and the same cycle happens again

For now I can ignore the "install new version" notification, but I don't know what's going on. If there are some logs that I can capture please let me know

**Comment by nuked44** [comment]
I tried to open code from wsl again today and it updated and worked without a problem.
No clue if someone fixed it overnight or if my pc had some wierd problem
