### ISSUE TITLE
WSL - update installation message

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-remote-release#869]
on first run of `code` once i have the WSL extension installed i get this message ("Installing VS Code Server 1234...")

![image](https://user-images.githubusercontent.com/1487073/60396902-6ae6ba80-9b47-11e9-9050-d69ca8527a6e.png)

We should use the full product name, and perhaps we don't need to say that it is a "server".  Suggestion:

"Installing Visual Studio Code WSL support"

We should only show the commit if its helpful for diagnostics, and if so I suggest:

"Installing Visual Studio Code WSL Support (commit 12345....)"

**Comment by aeschli** [comment]
"Installing Visual Studio Code WSL Support" is not a bad suggestion but I thought we agreed on the term `VS Code Server` to be user-facing so I tried to use it consistently in progress messages & error messages in WSL:
https://github.com/microsoft/vscode-remote-wsl/search?q="vs+code+server"&unscoped_q="vs+code+server"

Containers and SSH:
https://github.com/microsoft/vscode-remote-containers/search?q=q="vs+code+server"&unscoped_q="vs+code+server"
https://github.com/microsoft/vscode-remote-ssh/search?q=q="vs+code+server"&unscoped_q="vs+code+server"

**Comment by aeschli** [comment]
No changes planed..
