### ISSUE TITLE
node vscode-server process using excessive CPU

### ISSUE THREAD

**Issue by dkarnows** [microsoft/vscode-remote-release#8691]
In our work environment we have users developing with VS Code configured to do remote development on Linux servers. Often we have the server side "node vscode-server" processes using excessive CPU, a few hundred % of constant activity on the box and racks up thousands of hours of CPU time. When asked what the user is doing the answer is nearly always "VS Code is launched but at the moment I'm not doing anything with it". Them restarting the VS Code app kills the server side "node" process and then everything is fine for a while until it happens again.

Is there a way for us to see what these "node vscode-server" processes are doing when they're in this state of constant heavy CPU usage when the user is not even engaged with VS Code?

**Comment by roblourens** [comment]
Can you check the exact command line arguments of these processes? I'm guessing it's some extension process, could be something else.
