### ISSUE TITLE
Password for remote ssh

### ISSUE THREAD

**Issue by RuiPan2021** [microsoft/vscode-remote-release#8696]
Type: <b>Feature Request</b>

Why we can't write the password in the ssh config like mobaXterm?
We need to write the password so many times when log in.
Some guys share how to log in remote ssh without typing password every time by using the public key. But that's not suitable for me. Because I have more than 1 OS share the same IP.

Extension version: 0.90.1
VS Code version: Code 1.71.1 (e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb, 2022-09-08T19:56:36.424Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.19.0-gnr.po.bkc.6.7.17.x86_64

**Comment by roblourens** [comment]
Remote-SSH shouldn't manage your password. Try setting `"remote.SSH.useLocalServer": true` in settings.json to avoid password prompts when connecting
