### ISSUE TITLE
Copy-paste in WSL often rotates

### ISSUE THREAD

**Issue by mozhuanzuojing** [microsoft/vscode-remote-release#8699]
- VSCode Version:1.80
- Local OS Version:Windows10 22H2
- Remote OS Version:Ubuntu22.04
- Remote Extension/Connection Type: WSL

- Logs:

Steps to Reproduce:

1.Open a Java project in WSL, copy and paste a piece of text into a certain file, and there will often be rotation

![ef5371e7b0aeb686fee74ee10884787](https://github.com/microsoft/vscode-remote-release/assets/63572041/7a718cfb-ea97-4090-8110-dec8b98b8867)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

##### attach

All plugins are up to date, this phenomenon has only occurred in the last two weeks

**Comment by chrmarti** [comment]
Maybe related: https://github.com/microsoft/vscode/issues/187331

**Comment by mozhuanzuojing** [comment]
After our investigation, we found that this is the `vscode-java` plugin backend returns the pasted content too slowly, and may not be a remote plugin problem. Excuse me.
![image](https://github.com/microsoft/vscode-remote-release/assets/63572041/ec2b65b9-5f2d-4b56-b093-0340fb74c1df)
