### ISSUE TITLE
Add options to enable buildkit 

### ISSUE THREAD

**Issue by proelbtn** [microsoft/vscode-remote-release#87]
I used VS Code Remote Containers and I was impressed to this awesome extensions. but I find that VS Code build as a normal way.

Docker provides a build enhancement feature for more flexible build.

https://docs.docker.com/develop/develop-images/build_enhancements/

I want to use this feature to cache files regarding to apt, but It seems not to provide ways to enable this feature. buildkit is used to start up vscode with DOCKER_BUILDKIT=1, but I want you to add options for buildkit.

**Comment by nphmuller** [comment]
Not part of the team, but it seems that in the upcoming Docker 19.03 release you can make buildkit the default builder by running the `docker buildx install` command. The environment variable should then no longer be necessary.

The buildx plugin should be part of Docker 19.03 by default. Although I'm not sure if it's part of the current Docker Edge preview release currently.

See: https://github.com/docker/buildx#setting-buildx-as-default-builder-in-docker-1903

**Comment by proelbtn** [comment]
oh, thanks
