### ISSUE TITLE
Broken file watch in WSL 2

### ISSUE THREAD

**Issue by KyivJunta** [microsoft/vscode-remote-release#870]
- VSCode Version: 1.3.5.1
- Local OS Version: Microsoft Windows 10 Pro Insider Preview 10.0.18922 Build 18922
- Remote OS Version: Linux alpha 4.19.43-microsoft-standard #1 SMP Mon May 20 19:35:22 UTC 2019 
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Use create-react-app/storybook to create new project
2. Eventually file watchers stop working

Note:

- Files placed on WSL 2 file system (as WSL 2 docs say)
- Sometimes simply relaunching (`wsl --terminate/shutdown`) helps, but other times only system reboot fixes this behavior - there is not any pattern on foreseeable point when this happens
- There is not any error/warning neither on vscode side, nor on WSL 2 side

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by aeschli** [comment]
Can you check whether increasing `max_user_watches` in the WSL2 VM helps?
https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc

We had a bug that we don't report that error (or other file watcher errors) in the UI or in the log file. 
That's fixed in insiders (and the upcoming stable build). 
In insiders you should see error log entries in the `Output > Log (Remote Server)` log.
You can also set the log level (`Set Log Level`) to `Trace` to see whether the file watcher is still reporting file changes.

**Comment by KyivJunta** [comment]
I'he already done this. Without that tweak, node modules such as create-react-app (CRA) would not work in dev mode at all.
As I've already said, this bug happens randomly and for whole day I was using CRA without any problems. On other hand, when using CRA with storybook package, storybook randomly stops watching without any errors.
I'll try going back to insiders tomorrow.

**Comment by mdgozza** [comment]
In insiders I am also seeing this error when adding more than one folder to a workspace. 

```[2019-07-16 14:47:34.422] [remoteagent] [error] [File Watcher (nswf)] Inotify limit reached (ENOSPC)
[2019-07-16 14:47:43.986] [remoteagent] [error] [File Watcher (node.js)] Failed to watch /home/mdgozza/projects/work/city/ms-invoice/.vscode for changes using fs.watch() (Error: ENOSPC: no space left on device, watch '/home/mdgozza/projects/work/city/ms-invoice/.vscode')
[2019-07-16 14:47:43.987] [remoteagent] [error] [File Watcher (node.js)] Failed to watch /home/mdgozza/projects/work/city/web-main/.vscode for changes using fs.watch() (Error: ENOSPC: no space left on device, watch '/home/mdgozza/projects/work/city/web-main/.vscode')```

**Comment by BaoBaoJiu** [comment]
My problem is sometimes
`cat /proc/sys/fs/inotify/max_user_watches`
524288 came back to 8192 
after files.watcherExclude changed

**Comment by aeschli** [comment]
It's a WSL2 issue: microsoft/WSL#4232
