### ISSUE TITLE
How to share Server dir between several User ?

### ISSUE THREAD

**Issue by cherryamme** [microsoft/vscode-remote-release#8701]
Hello,

I have several accounts on a remote server and I need to work on these accounts. However, each account requires its own configuration and extensions. I'm wondering if there is a method to share the .vscode-server directory among multiple accounts, so that the extensions used by these accounts can be synchronized.

Additionally, this remote server is not connected to the internet, so I'm particularly interested in sharing local extensions.
I try to set Remote.SSH: Server Install Path same, but it didn't work because of directory Permission。

Is there any way to accomplish this?

Thank you.

**Comment by bamurtaugh** [comment]
Thanks for opening. Since you mention sharing extensions and config, would Dev Containers (https://code.visualstudio.com/docs/devcontainers/containers), Profiles (https://code.visualstudio.com/docs/editor/profiles), or Settings Sync (https://code.visualstudio.com/docs/editor/settings-sync) help?
