### ISSUE TITLE
can't open directory link in terminal

### ISSUE THREAD

**Issue by Anderson-777** [microsoft/vscode-remote-release#8702]
Type: <b>Bug</b>

1. open the terminal
2. type "ls" to show the list
3. find a directory then "ctrl+left click"
4. most of the time it can't open this link but "open editors" enabled

Extension version: 0.80.2
VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

**Comment by bamurtaugh** [comment]
Thanks for opening. Just to clarify, this happens in the latest version of the WSL extension? I see you mention WSL but wasn't 100% sure since I saw the bot labeled SSH.

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "info-needed" terminal
