### ISSUE TITLE
[Remote-SSH Bug]: can't connect to host (not an authority that can be resolved)

### ISSUE THREAD

**Issue by Juarrow** [microsoft/vscode-remote-release#8703]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### Expected Behavior

Established connection

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[19:09:46.087] Log Level: 2
[19:09:46.095] VS Code version: 1.80.0
[19:09:46.096] Remote-SSH version: remote-ssh@0.102.0
[19:09:46.096] win32 x64
```

</p>
</details>

### Anything else?

![image](https://github.com/microsoft/vscode-remote-release/assets/5290648/51564e73-b58d-4e77-8b44-cec45b2b55ed)

Dev tools log output:

![image](https://github.com/microsoft/vscode-remote-release/assets/5290648/730e9d06-d58b-4c89-bbe6-fa6d43c5fc68)

Additional Info:

- This started happening only after my recent VS Code upgrade.
- Also tried uninstalling and re-installing all Remote Development extensions & removing related settings from settings.json

**Comment by roblourens** [comment]
What steps did you do to open the remote? Something went very wrong here but I haven't had any other reports

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/187202 should be fixed in Insiders at least, but I'd like to hear about your scenario

**Comment by Juarrow** [comment]
@roblourens sorry, i totally missed searching in already-closed issues 🙈 

My usual flow of opening the remote is:
1. open "Remote explorer"
2. select one of the entries there coming from my `%USER%/.ssh/config`-file in the form of
````
Host user@host.com
  HostName host.com
  User abc
````

I also tried `code --remote ssh-remote+user@host.com /home/abc`
