### ISSUE TITLE
Support bourne shell in Remote SSH

### ISSUE THREAD

**Issue by junwuzhang** [microsoft/vscode-remote-release#8715]
Currently, if a user tries to remote SSH into a Linux machine where the only available shell is bourne shell (i.e. `sh`), the user would encounter a "`bash not found`" error message, something like
```
[00:41:52.129] > sh: bash: not found
[00:41:52.397] "install" terminal command done
[00:41:52.397] Install terminal quit with output: sh: bash: not found
[00:41:52.397] Received install output: sh: bash: not found
[00:41:52.399] Resolver error: Error: bash not found
```

Therefore, could we add support to Linux or Unix-like systems where only bourne shell is installed? Thanks!

**Comment by junwuzhang** [comment]
Hi! Original issue opener here - any updates on this? :)

I noticed there are some tags changing :), still wanna check on my side that this ticket will be worked on, since it would be super super helpful. Thanks a lot!! :)

**Comment by AlTaiRius** [comment]
My systems use the Korn Shell.  Surely we can configure our default shell?

**Comment by junwuzhang** [comment]
Hi OP here - any updates on this issue? Thank you so much! 🙏 😀

**Comment by joshspicer** [comment]
When the setting `useExecServer` is enabled (the default), `sh` will be used to execute the installation script (no more dependency on bash!)
