### ISSUE TITLE
Rebuilding Devcontainer fails to load .env values when run from running devcontainer window in vscode

### ISSUE THREAD

**Issue by KevinDMack** [microsoft/vscode-remote-release#8716]
- VSCode Version:  1.80.0
- Local OS Version:  Windows 11 Enterprise 22621.1992
- Remote OS Version: Ubuntu 20.04.5 LTS (remote box)
- Remote Extension/Connection Type: Containers/WSL/Server

- Logs:

Steps to Reproduce:

1.  Opening a vscode window for a directory that has a devcontainer (NOTE: Devcontainer has a initialize and postStart command tha rely on values in an env file.  All files in the .devcontainer directory).  
2.  Hit F1 to rebuild devcontainer without cache
3.  After devcontainer finishes loading successfully, in the same window, hit F1 and select "Rebuild DevContainer without Cache."
4.  Will get errors from devcontainer post start command that shows null values in the environment variables.

That above fails, but the following will succeed:
1.  Opening a vscode window for a directory that has a devcontainer (NOTE: Devcontainer has a initialize and postStart command tha rely on values in an env file.  All files in the .devcontainer directory).  
2.  Hit F1 to rebuild devcontainer without cache
3.  After devcontainer finishes loading successfully, close the vscode window.
4.  Open a new vscode instance window, for the same directory and hit F1 and select "Rebuild DevContainer without Cache."

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
Thanks for opening! Apologies if I'm missing something - why are you running "Rebuild without cache" twice in a row?
