### ISSUE TITLE
[Remote-SSH Bug]: ssh connection to remote fails to mkdir when user name contains a space

### ISSUE THREAD

**Issue by eliberma** [microsoft/vscode-remote-release#8717]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

upon connecting successfully to remote host the error seen in VSCode's ssh extension console is:

> mkdir: cannot create directory ‘/home/First’: Permission denied

where user name is First Last (i.e., First <space> Last).

Appears that mkdir is possibly not quoting user name in the target dir command?

### Expected Behavior

expecting:

mkdir "/home/First Last" or a variant thereof

### Steps To Reproduce

1. using VSCode version 1.80.0
2. using Remote - SSH extension version 0.102.2
3. using a target Linux (Ubuntu 22.04) machine
4. using an account where user name on the target machine contains a space
5. attempt to ssh to the target machine (success)
6. attempt to use VSCode's Remote - SSH extension to connect to target machine with user = First Last
7. failure to mkdir as described above.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by anewadventure** [comment]
This is likely not an extension problem. You're trying to create a directory inside `/home`, and the normal user permission doesn't permit this. This is because `/home` is supposed to be used as the user directory of each user. Each folder in `/home` represents a normal user, while root is an exception (`/root`).

**Comment by eliberma** [comment]
anewadventure - I must humbly and respectfully disagree here. 

Since I am attempting to run VSCode on the remote target server for the first time, upon a successful ssh connection from VSCode to the target server, ssh extension is attempting to initialize it's (hidden) .vscode directory like this:

`mkdir /home/First Last/.vscode`

this initialization fails because `First Last` has a space and is missing the required quotes. Instead, this command runs:

`mkdir /home/First`

which fails since indeed there is no user on the system called `First`

@roblourens - Please let me know what it would take to quote the `First Last` user name in the mkdir command above.

Many thanks.

**Comment by eliberma** [comment]
@roblourens - could you please opine on this bug? Many thanks!

**Comment by eliberma** [comment]
@roblourens - ping. Any chance this could get a slice of your time pretty please?

**Comment by roblourens** [comment]
I added the 'bug' label, I agree it's a bug, and I will fix it when I have the time
