### ISSUE TITLE
Blank terminal appears when connecting via ProxyJump

### ISSUE THREAD

**Issue by pd93** [microsoft/vscode-remote-release#872]
- VSCode Version: 1.35.1
- Local OS Version: Windows 10 - 1809
- Remote OS Version: Ubuntu 16.04
- Remote Extension/Connection Type: SSH/~~Docker/WSL~~

Steps to Reproduce:

1. Create a new config that uses the `ProxyJump` setting in your `~/.ssh/config` file (example below).
1. Ensure that you have followed [the steps to get `ProxyJump` working with Remote SSH](https://github.com/microsoft/vscode-remote-release/issues/18#issuecomment-507258777).
1. Open a new Remote SSH session using the config you created earlier.

A blank terminal window will open containing no text and the title: `C:\WINDOWS\System32\OpenSSH\ssh.exe`. If the window is closed then the Remote SSH session is ended and VS Code attempts to reconnect. If successful, the blank terminal will re-appear.

**Example ~/.ssh/config**
```
Host jumpbox
    HostName    x.x.x.x
    Port        22
    User        myuser

Host test-server
    HostName    172.16.0.1
    Port        22
    User        myuser
    ProxyJump   jumpbox
```

**Screenshot**
![image](https://user-images.githubusercontent.com/9294862/60438963-c7121300-9c09-11e9-9d92-71277ca4fd48.png)

**Comment by roblourens** [comment]
This looks the same as https://github.com/microsoft/vscode-remote-release/issues/230, not sure I can do anything.

**Comment by pd93** [comment]
Oops, missed that one.. Looks like a duplicate to me.
Thanks anyway.
