### ISSUE TITLE
ctrl+click on file addr takes to local file instead of remote

### ISSUE THREAD

**Issue by aquirdTurtle** [microsoft/vscode-remote-release#8723]
I'm working on a repo which I have cloned both locally and in a VM. I am using the remote+ssh extension to work with the repo in a jupyter notebook on the VM. The code threw an error with a stack trace. 

If I ctrl+click on a file address in the stack trace output, I am taken to the local version of the file instead of the remote version. The local version shows up under a file address `/home/user/code/...`. If I use f12 on the function I called, I am taken correctly to the remote version of the file, which shows up as `~/code/...`. Took me a while to figure out since the files have the same path on both machines.

**Comment by roblourens** [comment]
Is that in the terminal or the debug console?
