### ISSUE TITLE
Typescript Language Server Mac<>Mac not working

### ISSUE THREAD

**Issue by martinwepner** [microsoft/vscode-remote-release#8725]
Type: <b>Bug</b>

Hello, I have problem when using the remote SSH extension. I can't reproduce it, but sometimes after updating Extensions/VS code, all Typescript functions stop working when I connect from my MacBook to a Mac Studio. I don't know how to fix the problem, it seems that after a while it just starts working again and then "randomly" stops again. 

As a workaround I have to start a "Live Session" on the remote Studio and connect via link on my MacBook.

Edit1: Screenshots
<img width="923" alt="Bildschirmfoto 2023-07-18 um 13 08 13" src="https://github.com/microsoft/vscode-remote-release/assets/12143284/cf8d868a-9a30-4a91-b289-288de66b6c3c">
<img width="106" alt="Bildschirmfoto 2023-07-18 um 13 08 36" src="https://github.com/microsoft/vscode-remote-release/assets/12143284/58fe8d8b-4ec4-43b0-bba9-724f76085795">
<img width="721" alt="Bildschirmfoto 2023-07-18 um 13 09 07" src="https://github.com/microsoft/vscode-remote-release/assets/12143284/8ad68891-3097-4b24-a94e-ddf286f83eb3">

No TypeScript in the selectable languages:
<img width="721" alt="Bildschirmfoto 2023-07-18 um 13 09 32" src="https://github.com/microsoft/vscode-remote-release/assets/12143284/0984ec74-a10f-4bd1-ad25-1e98beec06fd">

Extension version: 0.102.0
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:20:23.298Z)
OS version: Darwin x64 21.6.0
Modes:
Remote OS version: Darwin arm64 22.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (3.64GB free)|
|Process Argv|--crash-reporter-id 7f550680-4aaf-4ea2-8c36-9213ae0e03a2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: studio|
|OS|Darwin arm64 22.5.0|
|CPUs|Apple M1 Ultra (20 x 24)|
|Memory (System)|128.00GB (36.45GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnoceb:30776495
h7j2d465:30786200
dsvsc013cf:30789518
cmakesidepanelv2:30779593

```

</details>

**Comment by mjbvz** [comment]
Are you still seeing this? When this issue happens do any other extensions / languages work, or is everything broken?

**Comment by martinwepner** [comment]
Thank you for looking into this, @mjbvz. Other extensions such as Github Copilot are working as expected. I just checked it with a Python file and everything seems to be normal (syntax highlighting, IntelliSense, etc.). Only all kinds of JS files (.js, .ts, .jsx, .tsx, ...) are not working.

If I can give you any more information, I would be happy to help you with this issue.
