### ISSUE TITLE
always spinning tunnel connecting notification

### ISSUE THREAD

**Issue by elantrean** [microsoft/vscode-remote-release#8727]
Type: <b>Bug</b>

The notification "Connecting to [servername]" is always spinning although i successfully connected to the tunnel

Extension version: 1.3.0
VS Code version: Code 1.80.1 (Universal) (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:20:23.298Z)
OS version: Darwin arm64 23.0.0
Modes:
Remote OS version: Linux x64 5.4.0-125-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id bb215363-d55e-4af2-9319-2e3da39a6b0c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|yulab3|
|OS|Linux x64 5.4.0-125-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz (80 x 1198)|
|Memory (System)|251.67GB (217.09GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnoceb:30776495
h7j2d465:30786200
dsvsc013:30789517

```

</details>

**Comment by a-gn** [comment]
Server is Windows 11 with
```
> code --version
1.80.1
74f6148eb9ea00507ec113ec51c489d6ffb4b771
x64
```

Client is macOS Ventura with
```
Version: 1.80.1 (Universal)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:20:23.298Z (2 wks ago)
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

I have the Remote - Tunnels extension version 1.3.0.

**Comment by bamurtaugh** [comment]
Thanks all for filing.

@connor4312 perhaps this and https://github.com/microsoft/vscode-remote-release/issues/8721 are related?

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/186345
