### ISSUE TITLE
Option to have all extensions installed on remote editor by default

### ISSUE THREAD

**Issue by iconmaster5326** [microsoft/vscode-remote-release#873]
The biggest problem with using this feature is the fact that I have to re-install workspace-class extensions every time I connect to a new remote, which happens fairly often for me. I know there is an extension whitelist (`remote.extensionKind` in general, `remote.containers.defaultExtensions` for Docker, `remote.SSH.defaultExtensions` for SSH, etc), but what if we had an option to install every extension on a new remote, and use an extension blacklist instead? Having to manually add every extension to a configuration setting is tedious to say the least, and is fragile in the case when I install or remove extensions. Just having all of them by default would make my life a lot easier.

**Comment by Chuxel** [comment]
Lets consolidate this in #157. Closing as dupe.
