### ISSUE TITLE
Invalid Pull Request error

### ISSUE THREAD

**Issue by rubengr** [microsoft/vscode-remote-release#8732]
- VSCode Version: 1.80.1
- Local OS Version: Windows 11

- Logs: Don't have logs

Steps to Reproduce:

1. Go to Clone Github Pull Request in Container Volume
2. Paste the Github clone URL.

It gives the error. The URL is correct, because i tested make clone directly. It happens in two different computers, with windows 10 too.

![image](https://github.com/microsoft/vscode-remote-release/assets/6231423/0976db04-d413-4fd8-b04a-fe05afabd747)

**Comment by bamurtaugh** [comment]
Thanks for filing. Based on the URL you shared, I'm not sure that's a PR specifically - it looks more like a link to an overall repo?
