### ISSUE TITLE
SSH is not working

### ISSUE THREAD

**Issue by Yu-Yuqing** [microsoft/vscode-remote-release#8733]
Type: <b>Bug</b>

[Error  - 18:14:35.856] Error resolving authority
Error: Couldn't install vscode server on remote server, install script returned non-zero exit status
	at t.installCodeServer (c:\Users\22493\AppData\Local\Programs\cursor\resources\app\extensions\jeanp413.open-remote-ssh\out\extension.js:1:423265)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\22493\AppData\Local\Programs\cursor\resources\app\extensions\jeanp413.open-remote-ssh\out\extension.js:1:387528

Extension version: 0.102.0
VS Code version: Cursor 0.2.51 (c3f87c47d631216e7a0f5124e2d2e47dd58cf9bd, 2023-07-19T23:32:44.076Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.63GB (22.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bamurtaugh** [comment]
Thanks for filing. Can you please share the full SSH output logs, in addition to the steps you're taking?
