### ISSUE TITLE
Test: Record feature dependencies in the lockfile

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#8749]
Refs: https://github.com/devcontainers/cli/issues/564

- [ ] anyOS @eleanorjboyd
- [x] anyOS @aiday-mar

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%238749%0A%0A&assignees=chrmarti)

---

- Install `@devcontainers/cli`: `npm i -g @devcontainers/cli`
- Create a `.devcontainer/devcontainer.json` in a workspace folder with features that have dependencies (using test features here):
```
{
	"image": "mcr.microsoft.com/devcontainers/base:ubuntu",
	"features": {
		"ghcr.io/codspace/dependson/C": {},
		"ghcr.io/codspace/dependson/E:1": {}
	}
}
```
- Verify feature dependencies are recorded in the `devcontainer-lock.json`: `devcontainer build --workspace-folder . --experimental-lockfile`

**Comment by eleanorjboyd** [comment]
Hi! Not able to get mine working, am I missing a step of did the setup wrong? Thanks

package.json
```
{
  "name": "my-node-project",
  "version": "1.0.0",
  "description": "A basic Node.js project",
  "main": "index.js",
  "dependencies": {
    "express": "^4.17.1",
    "lodash": "^4.17.21",
    "axios": "^0.24.0"
  }
}
```
ran `npm i`
ran `devcontainer build --workspace-folder . --experimental-lockfile`

devcontainer-lock.json
```
{
  "features": {
    "ghcr.io/codspace/dependson/A": {
      "version": "2.0.1",
      "resolved": "ghcr.io/codspace/dependson/a@sha256:932027ef71da186210e6ceb3294c3459caaf6b548d2b547d5d26be3fc4b2264a",
      "integrity": "sha256:932027ef71da186210e6ceb3294c3459caaf6b548d2b547d5d26be3fc4b2264a",
      "dependsOn": [
        "ghcr.io/codspace/dependson/E"
      ]
    },
    "ghcr.io/codspace/dependson/C": {
      "version": "2.0.0",
      "resolved": "ghcr.io/codspace/dependson/c@sha256:db651708398b6d7af48f184c358728eaaf959606637133413cb4107b8454a868",
      "integrity": "sha256:db651708398b6d7af48f184c358728eaaf959606637133413cb4107b8454a868",
      "dependsOn": [
        "ghcr.io/codspace/dependson/A",
        "ghcr.io/codspace/dependson/E"
      ]
    },
    "ghcr.io/codspace/dependson/E": {
      "version": "2.0.0",
      "resolved": "ghcr.io/codspace/dependson/e@sha256:9f36f159c70f8bebff57f341904b030733adb17ef12a5d58d4b3d89b2a6c7d5a",
      "integrity": "sha256:9f36f159c70f8bebff57f341904b030733adb17ef12a5d58d4b3d89b2a6c7d5a"
    },
    "ghcr.io/codspace/dependson/E:1": {
      "version": "1.0.0",
      "resolved": "ghcr.io/codspace/dependson/e@sha256:90b84127edab28ecb169cd6c6f2101ce0ea1d77589cee01951fec7f879f3a11c",
      "integrity": "sha256:90b84127edab28ecb169cd6c6f2101ce0ea1d77589cee01951fec7f879f3a11c"
    }
  }
}
```

**Comment by eleanorjboyd** [comment]
Ok spoke with @roblourens and think my output was actually correct- I misunderstood the dependencies and I think those are already in the devcontainer.json file you included. Closing for now but if my output for my devcontainer-lock.json above doesn't look correct let me know. Thanks!

**Comment by roblourens** [comment]
@chrmarti this could really use more detail for a general TPI. Even reading the two upstream issues, it's hard to understand what this is actually about for someone who isn't a devcontainer CLI expert.

**Comment by chrmarti** [comment]
> Ok spoke with @roblourens and think my output was actually correct- I misunderstood the dependencies and I think those are already in the devcontainer.json file you included. Closing for now but if my output for my devcontainer-lock.json above doesn't look correct let me know. Thanks!

The output looks good, thanks!
