### ISSUE TITLE
Many Touch ID prompts when using SeKey and an SSH server

### ISSUE THREAD

**Issue by rgov** [microsoft/vscode-remote-release#875]
- VSCode Version: 1.35.1
- Local OS Version: macOS 10.15.6
- Remote OS Version: Linux 3.10.0-693.2.2.el7.x86_64
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install [SeKey](https://github.com/sekey/sekey), a tool that stores SSH keys on the Secure Enclave on Touch ID-equipped Macs. Configure public key authentication to a remote SSH server using a key stored on the Secure Enclave.

2. Use Visual Studio Code to connect to the Remote SSH server.

3. During "Confirming <server> is reachable" phase, authenticate via Touch ID. (Awesome that it works with no change on the VS Code side!)

4. Authenticate via Touch ID again, during "Initializing VS Code Server" phase.

5. Authenticate via Touch ID *again*, during "Waiting for port forwarding" phase.

6. Click "Open Folder" in the file navigator and enter a path to open.

7. Authenticate via Touch ID two more times...

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
I would expect 3 auth steps (with nightly ssh, it will be 2). Then reloading the window there will be 2 more. Still working on this...

**Comment by Chuxel** [comment]
@roblourens #96 (and thus the next release) should largely eliminate this problem correct?

**Comment by roblourens** [comment]
Yes but I should test SeKey to make sure it still works when taking ssh out of the terminal.

**Comment by rgov** [comment]
This has gotten pretty good.

**Comment by roblourens** [comment]
#96 should essentially fix this if you enable that option.
