### ISSUE TITLE
Test: remote SSH using exec server

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-remote-release#8750]
Refs https://github.com/microsoft/vscode-remote-release/issues/8747

- [x] macOS @rebornix
- [x] linux @andreamah 
- [x] windows @amunger 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%238750%0A%0A&assignees=connor4312)

---

The user scenario didn't quite get finished due to a blocker, but please still test the exec server in remote SSH and make sure it's functional. Please _connect to_ the OS assigned in this issue; it doesn't matter what host OS you're using.

1. Install the latest **prerelease** version of Remote-SSH
2. Connect to your given platform with the standard `Remote-SSH: Connect to Current Window in Host`. Verify the connection gets made.
3. Disconnect and run `Remote-SSH: Kill VS Code Server on Host`, and then remove the `~./.vscode-server-insiders` folder on the remote
4. Set `remote.SSH.localServerDownload: "always"` in your user settings, and repeat step 2.
5. Run `Remote-SSH: Kill VS Code Server on Host`
6. Set `remote.SSH.experimental.useExecServer: true` in your user settings (it will show as not found, but we still look for it)
7. Repeat step 2.
8. Verify that the connection works and that you see "Exec server connection established" as one of the last lines in the "Remote - SSH" Output. This is important, and we'll fall back to the "old" way if the exec server connection fails.
9. Remove the `remote.SSH.localServerDownload: "always"` setting, and then remove the `~./.vscode-server-insiders` folder on your remote.
10. Repeat step 2 and 8

**Comment by rebornix** [comment]
Works as expected, well documented steps.

**Comment by amunger** [comment]
initial connection failed for a fresh Azure VM: failed to install vscode server. Retrying succeeded quickly, implying that installation was actually successful.

**Comment by amunger** [comment]
currently blocked on steps 6,7,8. Connor has access to the machine to investigate

**Comment by amunger** [comment]
new version is out, back to testing
