### ISSUE TITLE
Test: local port forwarding using tunnels

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-remote-release#8751]
Refs https://github.com/microsoft/vscode-internalbacklog/issues/4382

- [x] macOS @daviddossett
- [x] windows @roblourens

Complexity: 3

Authors: @connor4312, @alexr00 

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%238751%0A%0A&assignees=connor4312,alexr00)

---

This iteration we built the first version of "local forwarding", which allows users to forward their local ports and make them accessible to the internet using Dev Tunnels.

1. Install the latest prerelease of the Remote Tunnels extension (note: this is [still in PR](https://github.com/microsoft/vscode-remote-tunnels/pull/661) at time of writing, so may not be published by Zurich's Tuesday morning)
2. Set `"remote.tunnels.experimental.forwarding": true` in your user settings, and reload the window
3. The "Ports" view should now appear, even though you are not connected to a remote.
4. You should be able to forward a port and go to the resulting URL to view anything you have running on that port locally.
5. Test out forwarding multiple ports from multiple VS Code windows.
6. Capture the Output from the "Remote Tunnels" extension if you have any issues

**Comment by daviddossett** [comment]
Followed up offline but posting here too:

> Capture the Output from the "Remote Tunnels" extension if you have any issues

<img width="1202" alt="CleanShot 2023-07-25 at 11 41 19@2x" src="https://github.com/microsoft/vscode-remote-release/assets/25163139/7483f6b5-1817-48ee-95f2-7cc867d8e1b3">

**Comment by connor4312** [comment]
Extension version `v1.4.2023072518` has the fix

**Comment by Yoyokrazy** [comment]
Running into issues forwarding the port. ran `serve -p 3000` and tried to forward that port, consistently got the following error message. @eleanorjboyd was able to forward, though ran into another error further into testing. Reassigning item to her

<img width="342" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/12552271/8dc404c0-8f55-4ff6-b77d-2cbc85cd58ea">
<img width="331" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/12552271/0969cd39-cc4f-4e48-8f54-a8f5581222ba">

**Comment by eleanorjboyd** [comment]
able to forward a port but when I try and open it I get this. Is this the desired behavior? There wasn't anything on the port I forwarded but wanted to check

<img width="1426" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/26030610/91ce008e-feb8-45d3-b2bb-3dc31063e273">

**Comment by roblourens** [comment]
Connor pushed a fix for https://github.com/microsoft/vscode-remote-release/issues/8751#issuecomment-1650377427 and now it works great 👍
