### ISSUE TITLE
[Remote-SSH Bug]: not work in combined ProxyJump and StrictHostKeyChecking 

### ISSUE THREAD

**Issue by cadem** [microsoft/vscode-remote-release#8753]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (different error message)

### ->

I have 2 ssh config:
Host virtual_host1
  HostName 172.17.0.3
  StrictHostKeyChecking no
  Port 22
  ProxyJump root@192.168.1.52
  User root

Host virtual_host1
  HostName 172.17.0.3
  StrictHostKeyChecking no
  Port 22
  ProxyJump root@192.168.0.217
  User root

I have 2 virtual machines in 2 different hosts, but they have same internal ip address.
vscode cant connect successfully, it is connecting endlessly.

If I remove StrictHostKeyChecking, vscode will prompt "remote host key has changed". In order to connect one, I need to delete the other one host key. But I add  StrictHostKeyChecking, it doesn't work  and didn't give out any error popup.

### Remote-SSH Log

In the remote-ssh output, there is "Failed to set up socket for dynamic port forward to remote port 43719: connect ECONNREFUSED 127.0.0.1:51450. Is the remote port correct?"

**Comment by roblourens** [comment]
This would only be because SSH reported that issue. If you think it's a vscode-specific issue, please include the full log
