### ISSUE TITLE
remote.SSH.localServerDownload always requires password twice

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-remote-release#8754]
Testing #8750

Not sure if this is any technical limitation, but when setting `localServerDownload: "always"`, it prompts for password twice, while when setting it to auto it only requires once.

**Comment by rebornix** [comment]
I might be wrong, `auto` requires password twice too.

**Comment by roblourens** [comment]
Yeah, one for ssh and one for scp unfortunately
