### ISSUE TITLE
Port forwarding seems to need a progress indicator

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-remote-release#8755]
Testing #8751

At first I thought this didn't work since I hit enter and it hung on the welcome view. A progress state or indicator could help with this:

https://github.com/microsoft/vscode-remote-release/assets/25163139/9bcdbbb8-4309-49d5-a859-3e898ee9fa87

**Comment by alexr00** [comment]
I can add this for August. \

**Comment by alexr00** [comment]
It would be nice to just automatically show progress in the Ports view when we wait for the "forward" promise to resolve. If you want to do it in the extension too and provide additional info then that's good, but I think Codespaces would also benefit from a default progress in the view.
