### ISSUE TITLE
Clicking link to forwarded port doesn't open the link

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-remote-release#8756]
Testing #8751

Understood that this may be a table widget issue. But I found it strange that the underline styling implies a regular hyperlink but then it requires a cmd/ctrl click or clicking on an actual link in the hover.

https://github.com/microsoft/vscode-remote-release/assets/25163139/ebcf4897-219a-489f-a8fd-7c881bc19c23

**Comment by alexr00** [comment]
This was done to match how links are opened in the terminal: https://github.com/microsoft/vscode-remote-release/issues/4826
