### ISSUE TITLE
Test ssh exec server: asked for password after killing server

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode-remote-release#8759]
Testing #8750

1. Perform steps 4 and 5 from the TPI.
2. It should say that it was successful in killing the server, but it prompts me for the password again and is in this state. Is this expected?
<img width="1193" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/31675041/9139be80-0dcd-44e1-b80b-770400efd887">

**Comment by connor4312** [comment]
It looks like you're connecting to the VS Code server in that state. Prompting for a password is expected depending on how your auth is set up.

If you didn't disconnect in step (3) before killing the server, then it might try to ask for your password again to reconnect

**Comment by andreamah** [comment]
Oh ok, I didn't disconnect before killing it. That's probably fine then.
