### ISSUE TITLE
How to debug `Electron App` when dev with devcontainer in vscode.

### ISSUE THREAD

**Issue by qtisan** [microsoft/vscode-remote-release#8760]
When develop a electron app, it has a client and a dev server.
Mostly the os in dev container is linux, without GUI.
How to debug the app:
1. Run the client app in the host. (for example MacOS)
2. Run the dev server in the container.

**Comment by bamurtaugh** [comment]
This type of question would be a great fit for our dev container community Slack channel! https://aka.ms/dev-container-community

**Comment by bamurtaugh** [comment]
Also, have you tried running your server in the container, and using the forwarded port URL with the client app?

**Comment by qtisan** [comment]
> Also, have you tried running your server in the container, and using the forwarded port URL with the client app?

It is a solution but not perfect.
I thought about it carefully, maybe this issue should be in `Electron` repo, to find some way to debug in dev container.
Even I have not figured it out yet, it is unavoidable, that make the project codes in a mounted volume, then running native ui app on the host,  and serving the server code in the container.
In this case, it will install all the environment dependencies either in the host and container, it is not pure "containered dev" mode.

Thanks for attention, and applogize for unclear trouble.
