### ISSUE TITLE
Document `vscode-remote` URI scheme

### ISSUE THREAD

**Issue by jpillor-macquarie** [microsoft/vscode-remote-release#8764]
Feature request to document `vscode-remote` URI scheme

I know of these two:
* `vscode://vscode-remote/ssh-remote+${host}${path}`
* `vscode://vscode-remote/attached-container+${hex(container-id)}${path}`

I'd like to be able to set the SSH `user`, and also do a nested attach after connecting to a remote `host`

Is this documented somewhere? Happy to read source code too if that's available?

**Comment by bamurtaugh** [comment]
Thanks for opening! We have some documentation here: https://code.visualstudio.com/docs/remote/troubleshooting#_connect-to-a-remote-host-from-the-terminal.

We'd absolutely welcome your feedback in a PR if you have ideas on how this could be better or clearer: https://github.com/microsoft/vscode-docs. Thanks so much!

**Comment by jpillor-macquarie** [comment]
Hi Brigit, thanks for the link I've read the page and it doesn't answer my question unfortunately. Are you able to see the source code and get a list of the available parameters?

**Comment by bamurtaugh** [comment]
Thanks for your response! I'll reopen this issue and cc @roblourens here.

**Comment by roblourens** [comment]
If you want to customize ssh connection parameters, I recommend setting them in your ssh config. Not sure about the container case. @chrmarti

**Comment by chrmarti** [comment]
You can use: `vscode-remote://attached-container+${hex(json({ containerName: 'container-name-or-id', settings: { host: 'ssh:://ssh-server' } }))}${path}`. (JSON-encode the JavaScript object and then hex-encode that to embed it in the URI.)

**Comment by jpillor-macquarie** [comment]
Thanks Christof! Will test tomorrow

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jpillor-macquarie** [comment]
Thanks @chrmarti  For future readers, this worked for me:

```javascript
const json = JSON.stringify({
    settings: { host: 'ssh://myuser@myhost:2200' },
    containerName: `container-on-myhost`
})
const hex = (str) => new Array(str.length).fill(0).map((_, i) => str.charCodeAt(i).toString(16)).map(x => x.length === 1 ? `0${x}` : x).join("")
const folder = `/path/to/workspace`
return `vscode://vscode-remote/attached-container+${hex(json)}${folder}`
// set this string to an `a.href` and click it and VS Code should open
```

**Comment by jpillor-macquarie** [comment]
hey @chrmarti, one minor issue - opening this URI replaces the current VS Code window. Is there an extra flag to open the remote machine in new VS Code window?
