### ISSUE TITLE
Command 'WSL: Connect to WSL in New Window' resulted in an error

### ISSUE THREAD

**Issue by MetaCrawler** [microsoft/vscode-remote-release#8766]
Hello, 

Me and my colleague are facing following issue, since a vscode + extensions update approx. 3 weeks ago.

![grafik](https://github.com/microsoft/vscode-remote-release/assets/7521898/b7ae42bc-bde0-4cf1-a796-0d15c4bdaae8)

- **VSCode Version:** 
Version: 1.80.1 (user setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
- **WSL Extension Version:** 
WSL v0.80.2

- **Logs:**
```
> 2023-07-27 07:55:02.744 [error] TypeError: Cannot read properties of undefined (reading 'env')
>     at Object.getEnv (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-wsl-0.80.2\dist\node\extension.js:2:635142)
>     at c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-wsl-0.80.2\dist\node\extension.js:2:642392
>     at t.getWSLExecServer (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-wsl-0.80.2\dist\node\extension.js:2:642371)
>     at t.AuthorityResourceStore.get (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-wsl-0.80.2\dist\node\extension.js:2:586692)
>     at v (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-wsl-0.80.2\dist\node\extension.js:2:595548)
>     at e.$vL.h (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:64077) remote-wsl.connectInNewWindow {"value":"ms-vscode-remote.remote-wsl","_lower":"ms-vscode-remote.remote-wsl"}
```

**Steps to Reproduce:**

1. Open Command Palette.
2. Select "WSL: Connect to WSL in New Window"
3. Error Appears.

Current workarout is: 
1. Open Command Palette. 
2. "New Window".
3. Inside new Window open command palette again
4. "WSL: Connect to WSL".

That works without any issues.

**Comment by bamurtaugh** [comment]
Thanks for opening!

cc @lramos15 @devinvalenciano if you have any ideas on the error message.

**Comment by lramos15** [comment]
> cc @lramos15 @devinvalenciano if you have any ideas on the error message.

This is a bug in `0.8.0` of @vscode/extension-telemetry. Updating to 0.8.2 and publishing a new version of remote WSL should fix this. We should probably deprecate 0.8.0 because of this bug

**Comment by blelem** [comment]
> Current workarout is:
> 
>     Open Command Palette.
>     "New Window".
>     Inside new Window open command palette again
>     "WSL: Connect to WSL".

I also stumbled on that. Thanks for the workaround, @MetaCrawler  !

**Comment by aeschli** [comment]
This got fixed in the meantime.
