### ISSUE TITLE
Installing code-server downloads a HTML file

### ISSUE THREAD

**Issue by jf908** [microsoft/vscode-remote-release#8768]
Following the [these instructions](https://code.visualstudio.com/blogs/2022/07/07/vscode-server) to download `code-server` installs a HTML file as `/usr/local/bin/code-server`. Are the instructions no longer valid?

- Local OS Version: Windows 11 22H2
- Remote Extension/Connection Type: Server

- Logs:
```
$ wget -O- https://aka.ms/install-vscode-server/setup.sh | sh
--2023-07-27 12:45:58--  https://aka.ms/install-vscode-server/setup.sh
Resolving aka.ms (aka.ms)... 104.127.22.146
Connecting to aka.ms (aka.ms)|104.127.22.146|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://vscodeserverlauncher.blob.core.windows.net/builds/setup-scripts/setup.sh [following]
--2023-07-27 12:45:58--  https://vscodeserverlauncher.blob.core.windows.net/builds/setup-scripts/setup.sh
Resolving vscodeserverlauncher.blob.core.windows.net (vscodeserverlauncher.blob.core.windows.net)... 20.150.78.68
Connecting to vscodeserverlauncher.blob.core.windows.net (vscodeserverlauncher.blob.core.windows.net)|20.150.78.68|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1758 (1.7K) [text/x-sh]
Saving to: ‘STDOUT’

-                             100%[=================================================>]   1.72K  --.-KB/s    in 0s

2023-07-27 12:45:59 (191 MB/s) - written to stdout [1758/1758]

glibc version is 2.31
is min? 1
Installing from https://aka.ms/vscode-server-launcher/x86_64-unknown-linux-gnu
$ code-server
/usr/local/bin/code-server: line 1: syntax error near unexpected token `newline'
/usr/local/bin/code-server: line 1: `<!DOCTYPE html>'
```

Steps to Reproduce:

1. Run `wget -O- https://aka.ms/install-vscode-server/setup.sh | sh` in wsl
2. Running `code-server` doesn't work

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by jf908** [comment]
I missed the part of the documentation that states this a private preview.

**Comment by yokowasis** [comment]
The private preview part is for vscode.dev, you don't need access to private preview for code-server server-local. This happened to me too today. The installed file should be binary, but get html instead.

**Comment by jf908** [comment]
> The private preview part is for vscode.dev, you don't need access to private preview for code-server server-local. This happened to me too today. The installed file should be binary, but get html instead.

Ah, I will reopen.

**Comment by jonatas-88** [comment]
I am facing the same problem when I tried to install code-server on Ubuntu Server 20.04

**Comment by Phil-Barker** [comment]
Same error on my vscode server running in Docker under Unraid 😞

**Comment by piotrlewalski** [comment]
Same here. 
Looks that https://aka.ms/vscode-server-launcher/aarch64-unknown-linux-gnu (download location used by https://aka.ms/install-vscode-server/setup.sh script) redirects to https://code.visualstudio.com/docs/remote/tunnels html page instead of a binary.

**Comment by yokowasis** [comment]
They link is dead. You can download the new link using this command (for ARM64 / termux  / android)

```
wget https://az764295.vo.msecnd.net/stable/$(curl https://update.code.visualstudio.com/api/commits/stable/server-linux-arm64-web | cut -d '"' -f 2)/vscode-server-linux-arm64-web.tar.gz
```

**Comment by Ali-Flt** [comment]
Any updates on this?

**Comment by Ali-Flt** [comment]
any updates on this?

**Comment by Ali-Flt** [comment]
I think this is answered here:
[https://github.com/microsoft/vscode/issues/188197#issuecomment-1642587140](https://github.com/microsoft/vscode/issues/188197#issuecomment-1642587140)

**Comment by bamurtaugh** [comment]
Thanks all! This should now be addressed via https://github.com/microsoft/vscode/issues/168492.
