### ISSUE TITLE
WSL distro name not shown

### ISSUE THREAD

**Issue by p-kager** [microsoft/vscode-remote-release#8770]
- VSCode Version: 1.80.2
- WSL Plugin Version: 0.80.2
- Local OS Version: W10 - 19045.3208
- Remote OS Version: Alpine 3.15
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Import new WSL distro (must be new, never been connected to with VS Code)
2. Connect to WSL using distro...

![image](https://github.com/microsoft/vscode-remote-release/assets/116003244/e62d99d6-e754-4d68-90cd-be2820569fb2)

Expected:

![image](https://github.com/microsoft/vscode-remote-release/assets/116003244/a273859b-b53e-438b-814e-256890e82c57)

Seems to be a regression, works fine with 0.79.5. So a workaround would be rollback WSL plugin to 0.79.5 then connect to distro and then update back to latest plugin version.

**Comment by zgjja** [comment]
same as me, i have two computers, one is good, the other does not show, and thanks for your workaround!

**Comment by connor4312** [comment]
Fixed in the latest release
