### ISSUE TITLE
Port forwarding is not working propertly, from a Tunnel in vscode.dev

### ISSUE THREAD

**Issue by aleleba** [microsoft/vscode-remote-release#8771]
Versión: 1.80.2
Confirmación: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Fecha: 2023-07-27T20:48:17.303Z (hace 16 horas)
Explorador: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

- Logs:
- Cannot forward localhost:2615. The host may not be available or the remote port may have already been forwarded

Steps to Reproduce:

1. Connect to a tunnel in vscode.dev
2. Run a app that runs on any port
3. Try to port forwarding that port

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

It only happens on vscode.dev

This is happening on vscode.dev when connecting to a tunnel.
Port forwarding is not working propertly, from a Tunnel.

<img width="1440" alt="Captura de pantalla 2023-07-28 a la(s) 6 58 26 a  m" src="https://github.com/microsoft/vscode-remote-release/assets/28767814/b6330f2d-ec9f-4426-b8dc-d6023e8bfa28">

From my dev environment normally y use codercom/codeserver, but this seems to be a better option, this is the only fix, if it is fixed, I can migrate to use this.

<img width="1438" alt="Captura de pantalla 2023-07-28 a la(s) 9 02 06 a  m" src="https://github.com/microsoft/vscode-remote-release/assets/28767814/6094a118-a385-4a59-8325-d53f6f249821">

With insiders.vscode.dev it works.

**Comment by aleleba** [comment]
Also should be great to have Cors Configuration on Port forwarding.

**Comment by aleleba** [comment]
Hi @bamurtaugh, I have seen the youtube videos, and this is a awesome iniciative, congrats to all team, can I have a response to this issue, this is the right place to raise the issue?, thank you in advance 👍🏼

**Comment by bamurtaugh** [comment]
Thanks for opening! I'll try to repro your issue.

> Also should be great to have Cors Configuration on Port forwarding

Could you please open a separate feature request for this? Thanks!

**Comment by bamurtaugh** [comment]
I was able to forward a port using a simple Node server.js app that forwards port 3000. Are you able to forward any ports when you're tunneling? Are you just unable to forward ports in certain scenarios?

**Comment by aleleba** [comment]
This only happened to me on vscode.dev, it is working on insiders.vscode.dev, I assumed that this issue is happening on Versión: 1.80.2, of vscode, maybe is a missconfiguration on infrastructure of vscode.dev site, what do you think?

**Comment by bamurtaugh** [comment]
Interesting, my port also isn't automatically forwarded in vscode.dev.

@alexr00 @connor4312 any idea why my port would be forwarded automatically in insiders.vscode.dev when connected to a tunnel, but it's not forwarded in vscode.dev?

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-remote-release/issues/8595, should be fixed on insiders.vscode.dev already.
