### ISSUE TITLE
Refresh dev container list result in error "UNC host 'wsl.localhost' access is not allowed"

### ISSUE THREAD

**Issue by pootow** [microsoft/vscode-remote-release#8773]
Type: <b>Bug</b>

Click `refresh` icon at the top of Remote Explorer to refresh dev container list, an error message will appare in the right bottom saying `UNC host 'wsl.localhost' access is not allowed`. But,
1. In explorer, I can access `\\wsl.localhost`.
2. Change user setting `security.allowedUNCHosts` and add `wsl.localhost` in it does not help.

Extension version: 0.4.1
VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (19.13GB free)|
|Process Argv|-n --crash-reporter-id 5423b8f6-4776-4d1d-a5c8-e5353dd4b4c6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
gsofb:30797622
pythonnosmt12:30797651
e537b577:30795824
dsvsc013:30795093
dsvsc014cf:30797590

```

</details>

**Comment by pootow** [comment]
This issue may be related to some project that has inaccessible path in it. After I delete the dev container manually, this refresh icon works again.

**Comment by bamurtaugh** [comment]
Thanks for filing. Have you experienced this issue after deleting the dev container you mention?
