### ISSUE TITLE
Extensions are not installed in dev-containers

### ISSUE THREAD

**Issue by exhuma** [microsoft/vscode-remote-release#8777]
I have run into the issue explained in #8097. In the thread, it says the following:

              It will be available in next release of VS Code or if you are using VS Code insiders, it is available already.

_Originally posted by @sandy081 in https://github.com/microsoft/vscode-remote-release/issues/8097#issuecomment-1471705861_
            
I see on the releases page that the latest version is 1.80 and has been release in June 2023 (well after the comment above was made): https://code.visualstudio.com/updates/v1_80

Is it possible that the fix somehow didn't make it into 1.80?

**Comment by johannes-isaksson** [comment]
Don't know if related, but the problems from #178748 seem to have resurfaced as well.

**Comment by sandy081** [comment]
Can you please provide steps to reproduce?

**Comment by exhuma** [comment]
Sorry for the late reply. And it does indeed work again. The thing I noticed recently is that clicking on the "add to devcontainer.json" option in the extension drop-down menu does not actually add it to the json file. This was the origin of my error. I clicked that button and rebuilt the image without noticing that the file on disk never changed.
