### ISSUE TITLE
Can't launch/run/debug program hosted in remote-docker

### ISSUE THREAD

**Issue by XUWeijiang** [microsoft/vscode-remote-release#878]
- VSCode Version: Version: 
    1.35.1 (user setup)
    Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
    Date: 2019-06-12T14:30:02.622Z
   Electron: 3.1.8
   Chrome: 66.0.3359.181
   Node.js: 10.2.0
   V8: 6.6.346.32
   OS: Windows_NT x64 10.0.18362
- Local OS Version: Windows 10 1903
- Remote OS Version: Redhat Enterprise 7.5
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. According to https://code.visualstudio.com/docs/remote/containers-advanced, use SSH tunnel to map remote docker sock to local, and then set docker.host property accordingly.
2. Start a docker container in remote machine
3. Attach the container started in step 1 
4. git clone source code in that container.
5. Open that source code folder in the same vscode instance.
6. Add a configuration for debug ( I am using python, and using the default 'Python: Current File" configuration)
7. Run (with or without debug)

Results:
vscode pops an error message " Failed to start the socket server. (Error: Listen EADDRNOTAVAIL ::1)

Expected: 

Run normally just like in local container

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

![image](https://user-images.githubusercontent.com/10752685/60486422-5fbf9600-9cd1-11e9-90a7-2919825f6412.png)

**Comment by roblourens** [comment]
This sounds like an issue with the vscode-python extension. Please file an issue on their repo.
