### ISSUE TITLE
vscode<--node process still running even if closed

### ISSUE THREAD

**Issue by StoryDevOffical** [microsoft/vscode-remote-release#8780]
🚨 The issue tracker is not for questions 🚨

- VS Code Version: 1.80.2
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. remote ssh from a client to a ubuntu vscode-server 
2. close vscode 
3. see 10 process still running for ~5 minutes

` .vscode-server/bin/[..]/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level off--connection-token-file .vscode-server/.2ccd690cbff1569e4a83d7c43d45101f817401dc.token`

` vscode-server/bin/[..]/out/server-main.js --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level off--connection-token-file .vscode-server/.2ccd690cbff1569e4a83d7c43d45101f817401dc.token`

Why still running from bin ?

it can be related to this [issue](https://github.com/microsoft/vscode-remote-release/issues/6798)
I tried with bissect and all extensions disabled.

**Comment by roblourens** [comment]
The server will stay running for some period of time after the last connection is closed, then shut down.
