### ISSUE TITLE
Dev Containers: Reopen in Container 

### ISSUE THREAD

**Issue by aboschke** [microsoft/vscode-remote-release#8783]
Type: <b>Bug</b>

For bug reports please include the complete log output. (In the VS Code window: `F1` > `Dev Containers: Show Container Log`.)
Hit <command><shift>P, searched for 'Dev Containers: Reopen in Container ', selected it and ended up here

Extension version: 0.299.0
VS Code version: Code 1.80.2 (Universal) (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T21:05:41.366Z)
OS version: Darwin x64 20.6.0
Modes:
Remote OS version: Linux x64 4.18.0-477.13.1.el8_8.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|40.00GB (3.73GB free)|
|Process Argv|--crash-reporter-id e1d73bb5-2485-4bc2-b893-965ba60dbdaa|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: alta|
|OS|Linux x64 4.18.0-477.13.1.el8_8.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8268 CPU @ 2.90GHz (24 x 2893)|
|Memory (System)|188.39GB (184.38GB free)|
|VM|40%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
gsofb:30797622
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076
cmakesidepanelv2:30779593

```

</details>

**Comment by bamurtaugh** [comment]
Hi @aboschke, thanks for opening. Did you have a specific issue with the Reopen in Container command? If so, please provide some more info and repro steps. Thanks!
