### ISSUE TITLE
Add feature to have Cors Configuration on Port forwarding, or be able to use base url port forwarding

### ISSUE THREAD

**Issue by aleleba** [microsoft/vscode-remote-release#8788]
Also should be great to have Cors Configuration on Port forwarding, or be able to use base url port forwarding, something like: https://{randomKey}.use.devtunnels.ms/proxy/{portNumber}, for avoid cors issues, right now I am trying to develop an application that have a front-end app server, and a back-end server, both running on different ports, so I am having Cors issues when trying to fetch back-end project. Thank you in advance @bamurtaugh.

_Originally posted by @aleleba in https://github.com/microsoft/vscode-remote-release/issues/8771#issuecomment-1662971596_

**Comment by aleleba** [comment]
It should be great to have Cors Configuration on Port forwarding, or be able to use base url port forwarding, something like: https://{randomKey}.use.devtunnels.ms/proxy/{portNumber}, for avoid cors issues, right now I am trying to develop an application that have a front-end app server, and a back-end server, both running on different ports, so I am having Cors issues when trying to fetch back-end project. Thank you in advance @bamurtaugh.

**Comment by aleleba** [comment]
Hi, maybe @alexr00 I can help on free time, if you give me some guidance, thank you so much 😁

**Comment by aleleba** [comment]
I am not sure, but I think the logic should be here, https://github.com/microsoft/vscode/blob/83fc3ad9bd553869e8fea3d370d1d2bd438f9e54/src/vs/workbench/electron-sandbox/window.ts#L894

**Comment by aleleba** [comment]
I am getting the cors error and the message of provisional headers.

<img width="646" alt="Captura de pantalla 2023-08-07 a la(s) 7 34 25 a  m" src="https://github.com/microsoft/vscode-remote-release/assets/28767814/4b45dcd0-25f4-4035-b886-6b5ee29c8207">

**Comment by aleleba** [comment]
Adding some another tests I have made, when using as back-end origin dev-back-end.p-lao.com and front-end origin as url of tunnel it worked, so my asumption of the cors I think that is true, I am trying to give you as much information I can.

**Comment by connor4312** [comment]
Ah, actually. I think dev tunnels stores their authentication for private tunnels a cookie with the `SameSite=lax` attribute set. They would need to set `SameSite=none` in order for programmatic cross-site requests to be made, otherwise it redirects to get authentication for private tunnels.

**Comment by aleleba** [comment]
Thank you @connor4312 for found the issue, I am really exited to get the fix, to be able to migrate totally to this environment 😁

**Comment by aleleba** [comment]
Hi @derekbekoe, hope you are doing well, I think the change should be on file: vscode/src/vs/server/node/webClientServer.ts on this lines: https://github.com/microsoft/vscode/blob/fffde1001afa6207a084a9ea63c78702626802a1/src/vs/server/node/webClientServer.ts#L254 and https://github.com/microsoft/vscode/blob/fffde1001afa6207a084a9ea63c78702626802a1/src/vs/server/node/webClientServer.ts#L391 , hope this help.

**Comment by aleleba** [comment]
Also I think this should fix https://github.com/microsoft/vscode-remote-release/issues/8800 this too, not sure but I think this will fix the simple browser too. Maybe is the cookie the one that is missing to be able to enter to the page on simple browser.

**Comment by aleleba** [comment]
Maybe if @derekbekoe have a lot of work I can make the Pull Request, can I help with something?

**Comment by derekbekoe** [comment]
As @connor4312 mentioned above, the behavior you're seeing is due to the Dev tunnels service, not VS Code client. Also, it's likely due to the fact that the port has access set to private (requiring authentication); currently all ports hosted from vscode.dev Remote Tunnels get set to private.

With that said, here are some options that I believe should work:

**1 - Set the "backend" port in your example to public**
While vscode only supports private today, it's still possible to change this using the [devtunnel CLI](https://aka.ms/devtunnels/docs). Here are the steps:
```
# download the CLI for your OS - https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started#install
# log in via GitHub
devtunnel login -g
# verify the tunnel id shows in the list of tunnels (this is the id in the *.devtunnels.ms url)
devtunnel list
# make the port public
devtunnel access create TUNNELID --port-number 4000 --anonymous
```
Now that the port is public, re-test your scenario.

Note that this makes the port accessible to anyone with the url without authentication. Other ports will remain private. Also, it may take 30s to 60s for the change to take effect.

**2 - Use an access token to access the port**

It is possible to also keep the tunnel private and get a token you provide in the header of the request to your backend.
- With the devtunnel cli, you can run `devtunnel token TUNNELID --scope connect` which will output a token.
- When your frontend is making the API call, add the header to authenticate the request: `X-Tunnel-Authorization: tunnel TOKEN`
Learn more at https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/security#tunnel-access

**Comment by aleleba** [comment]
Thank you! I will try that and let you know 😁

**Comment by aleleba** [comment]
@derekbekoe, @connor4312, I have tested and it worked, but I think that for the final user it should be useful that vscode handles this for them and create a fetch interceptor where attaches the `X-Tunnel-Authorization: tunnel TOKEN` behind the scenes on every request. What do you think?

**Comment by derekbekoe** [comment]
Glad it worked.

It may be unexpected if VS Code started adding this header automatically to user requests. In addition, it is not always needed and it may not translate well to other languages or frameworks.

I see a couple possible ways to improve the experience here:
- Support is added for switching individual ports to Public, without the need for the devtunnel CLI
- Support is added for getting a tunnel access token directly e.g. via a UI element (this would be similar to [Visual Studio](https://learn.microsoft.com/en-us/aspnet/core/test/dev-tunnels?view=aspnetcore-7.0#dev-tunnels-tool-window))

**Comment by aleleba** [comment]
@derekbekoe , thank you!, agreed with you, can this features be on planning of developimg? 😁

**Comment by connor4312** [comment]
Those two ideas are doable, and I think setting ports to public is something we'd want to do anyway. I am concerned though that it is very unclear to users who hit this issue that setting the port to public or using an access token is the right thing to do.

Maybe if Dev Tunnels see an different `Origin` header in the request, it can respond with some descriptive error in the response body rather than redirecting for authentication?

**Comment by burkeholland** [comment]
While this can be done manually, the ideal model (I think) would be similar to Codespaces where localhost is perfectly emulated. As is, I would prefer to use Remote Tunnels, but I default to Codespaces because of the ease of working with ports.

**Comment by aleleba** [comment]
Hi @connor4312, hope you are doing great, I want to make a following up of this feature, if the team is thinking to add support to this?, thank you! 👍🏼

**Comment by aleleba** [comment]
Hi does there are some following up of this work?, thank you in advance 😄

**Comment by achertovsky** [comment]
same here. FE application together with backend application. as its in fact 2 different hosts i have cors issue and no clue how to sort it out

**Comment by aleleba** [comment]
@connor4312 any update for this?

**Comment by aleleba** [comment]
Sorry to be so impatient, but I did not have any response since a month ago, @connor4312, do we have any update for this, thank you in advance.

**Comment by ntaraujo** [comment]
I'm also interested. Please, any updates?

**Comment by aleleba** [comment]
Hi @connor4312 , I have some avaiability to help. With some docs I think I can help to move this feature to a reality, may I help?

**Comment by aleleba** [comment]
@connor4312 do you know if there is a plan to integrate this?

**Comment by aleleba** [comment]
@derekbekoe @connor4312 , any plans for this, thank you in advance 👍🏼

**Comment by derekbekoe** [comment]
@aleleba For security reasons authentication is per tunnel-port so the options are as previously outlined in 
[this previous comment](https://github.com/microsoft/vscode-remote-release/issues/8788#issuecomment-1670218545).

You could either make the backend port public or make an authenticated request but passing in the tunnel access token. Making the port public is now straightforward in VS Code as it allows you to set the port to Public.

**Comment by aleleba** [comment]
> Glad it worked.
> 
> It may be unexpected if VS Code started adding this header automatically to user requests. In addition, it is not always needed and it may not translate well to other languages or frameworks.
> 
> I see a couple possible ways to improve the experience here:
> - Support is added for switching individual ports to Public, without the need for the devtunnel CLI
> - Support is added for getting a tunnel access token directly e.g. via a UI element (this would be similar to [Visual Studio](https://learn.microsoft.com/en-us/aspnet/core/test/dev-tunnels?view=aspnetcore-7.0#dev-tunnels-tool-window))
> 
> It may be best to have separate issues for those.

As we discuss here, we talked about be able to open public ports automaticly for dev-tunnels, just as local vscode do, in local vscode you can change to use a public or private tunnel.

**Comment by derekbekoe** [comment]
Ah okay so Port Visibility is available on local VS code but not when using Remote - Tunnels to connect to a remote machine.

**Comment by aleleba** [comment]
@derekbekoe That is right, thank you for your response.

**Comment by achertovsky** [comment]
any updates on cors in tunnel?
is it possible to configure headers via application now?

**Comment by aleleba** [comment]
Any update on this? thank you for adding this to the Backlog 👍🏼

**Comment by connor4312** [comment]
Ports forwarded over Remote Tunnels can be set as "Public" using the latest VS Code Insiders and REmote - Tunnels extension.

**Comment by aleleba** [comment]
Hi, on the insiders.vscode.dev is not possible yet, right?
![Screenshot_20240419_113609_Chrome.jpg](https://github.com/microsoft/vscode-remote-release/assets/28767814/3ca446a7-0424-44c9-806d-91919bc2090c)

**Comment by ajmeese7** [comment]
I'm not seeing it on that site either @aleleba, running into the same issue:

![Missing visibility option](https://github.com/microsoft/vscode-remote-release/assets/17814535/838ae9b7-7049-4038-bb37-ada2a4b0a2af)

I've found that I can't access my API on port 1337 using a URL like `https://bw1vqn78.use.devtunnels.ms:1337/` whatsoever, and that I can access `https://bw1vqn78-1337.use.devtunnels.ms/` in the browser as expected, but run into CORS issues whenever trying to access the second URL method from the app I'm running on port 3000. Any kind of fix/workaround for this would be greatly appreciated, I've tried dozens of variations of `fetch` but the issue still stems from the lack of a permissive `Access-Control-Allow-Origin` header that allows requests from the same domain.

Code I'm using for reference, although I'm pretty sure the issue is independent of the code:

```js
const getApiServerEndpoint = () => {
  let hostname = window.location.hostname;
  if (process.env.NODE_ENV === "development" && hostname.endsWith("use.devtunnels.ms")) {
    // Support for VS Code tunnels during development
    hostname = hostname.replace(/-\d{4}/, "");
    return window.location.protocol + "//" + hostname + ":1337";
  } else {
    return process.env.REACT_APP_API_SERVER;
  }
};

const healthCheckInterval = 2500;
const checkHealth = async () => {
  await fetch(getApiServerEndpoint() + "/parse/health", {
    signal: AbortSignal.timeout(5000),
    redirect: "follow"
  })
    .then(async (res) => await res.json())
    .then(
      (result) => { setIsBackendReady(true); },
      (error) => {
        console.warn("Error parsing health check data:", error);
        setIsBackendReady(false);
      }
    )
    .catch((error) => {
      console.warn("Failed health check:", error);
      setIsBackendReady(false);
    });

  // This way instead of setInterval to avoid multiple concurrent requests,
  // because the server occasionally hangs when under heavy load
  setTimeout(checkHealth, healthCheckInterval);
};
```

**Comment by aleleba** [comment]
> I'm not seeing it on that site either @aleleba, running into the same issue:
> 
> ![Missing visibility option](https://github.com/microsoft/vscode-remote-release/assets/17814535/838ae9b7-7049-4038-bb37-ada2a4b0a2af)
> 
> I've found that I can't access my API on port 1337 using a URL like `https://bw1vqn78.use.devtunnels.ms:1337/` whatsoever, and that I can access `https://bw1vqn78-1337.use.devtunnels.ms/` in the browser as expected, but run into CORS issues whenever trying to access the second URL method from the app I'm running on port 3000. Any kind of fix/workaround for this would be greatly appreciated, I've tried dozens of variations of `fetch` but the issue still stems from the lack of a permissive `Access-Control-Allow-Origin` header that allows requests from the same domain.
> 
> Code I'm using for reference, although I'm pretty sure the issue is independent of the code:
> 
> ```js
> const getApiServerEndpoint = () => {
>   let hostname = window.location.hostname;
>   if (process.env.NODE_ENV === "development" && hostname.endsWith("use.devtunnels.ms")) {
>     // Support for VS Code tunnels during development
>     hostname = hostname.replace(/-\d{4}/, "-1337");
>     return window.location.protocol + "//" + hostname;
>   } else {
>     return process.env.REACT_APP_API_SERVER;
>   }
> };
> 
> const healthCheckInterval = 2500;
> const checkHealth = async () => {
>   await fetch(getApiServerEndpoint() + "/parse/health", {
>     signal: AbortSignal.timeout(5000),
>     redirect: "follow"
>   })
>     .then(async (res) => await res.json())
>     .then(
>       (result) => { setIsBackendReady(true); },
>       (error) => {
>         console.warn("Error parsing health check data:", error);
>         setIsBackendReady(false);
>       }
>     )
>     .catch((error) => {
>       console.warn("Failed health check:", error);
>       setIsBackendReady(false);
>     });
> 
>   // This way instead of setInterval to avoid multiple concurrent requests,
>   // because the server occasionally hangs when under heavy load
>   setTimeout(checkHealth, healthCheckInterval);
> };
> ```

Hi, the only way right now is to set in the headers of the app this X-Tunnel-Authorization: tunnel TOKEN, in the conversation behind you can see a reference to the docs on how you can achive connect a front-end and a back-end running on different ports, but as far as I know right now they are working on a way to connect it without this token. Hopefully this come soon.

**Comment by aleleba** [comment]
I want to update, on insiders.vscode.dev is working now 👍🏼

**Comment by aleleba** [comment]
@connor4312 It seems to not work yet, when I set public the visibility it ask for credentials, so it not changed to public.
![Captura de pantalla 2024-04-24 a la(s) 7 23 47 a  m](https://github.com/microsoft/vscode-remote-release/assets/28767814/8440bb2e-8c0f-4de3-88a8-884e5ae5999f)

**Comment by aleleba** [comment]
I found that is not working right, can anyone let me know if you are working on the fix?

**Comment by aleleba** [comment]
Hi @connor4312 , sorry for bother you, I only want to confirm that the team knows about the last issue?

**Comment by connor4312** [comment]
> It seems to not work yet, when I set public the visibility it ask for credentials, so it not changed to public.

Make sure the tunnel process you're running is also VS Code Insiders / the VS Code Insiders CLI, as that is required for the port to actually be marked as public.

**Comment by aleleba** [comment]
You are right @connor4312 , I have downloaded vscode insiders, created a tunnel with the insiders version, and it worked, thank you for your help, very appreciated all the effort of all team members. Very exited to test it on stable release 👍🏼

**Comment by aleleba** [comment]
Hi @connor4312 , it seems that vscode have been updatedd but the stable release for remote-tunnels extension is not yet deployed, right? The plan was to deploy together?

**Comment by aleleba** [comment]
Hi @connor4312, sorry for bother you, but I do not know if there is a plan to update the Remote - Tunnels extension to new stable version, vscode have alredy updated but the extension no, and this feature is not working now without that stable version release, thank you in advance 👍🏼
