### ISSUE TITLE
SSH with VirtualBox is not working

### ISSUE THREAD

**Issue by loosec9n** [microsoft/vscode-remote-release#8789]
Type: <b>Bug</b>

Using Remote-SSH / Remote Explorer to connect with Ubuntu in VirtualBox is not happening in VS Code, showing an error. But when i try from CMD the ssh connects and i can access the Ubuntu. 
error message is Could not establish connection to " ip address ".

Extension version: 0.102.0
VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by roblourens** [comment]
Is this still an issue? If so please share the log from the Remote-SSH output channel
