### ISSUE TITLE
VS Code Exec format error in `Terminal` but can open remote window from within VS Code integrated terminal

### ISSUE THREAD

**Issue by clmnin** [microsoft/vscode-remote-release#8790]
- VSCode Version: 1.80.2 - 2ccd690cbff1569e4a83d7c43d45101f817401dc - x64
- Local OS Version: Windows 11
- Remote OS Version:  Ubuntu 22.04.2 LTS
- Remote Extension/Connection Type: WSL

When I try running code from the [Terminal](https://github.com/microsoft/terminal) I get an error
```sh
code --version
/mnt/c/Users/username/AppData/Local/Programs/Microsoft VS Code/bin/code: 61: /mnt/c/Users/username/AppData/Local/Programs/Microsoft VS Code/Code.exe: Exec format error
```

But if I open a remote connection from within VS Code, following the below steps
1. Open new window <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>N</kbd>
2. Open a WSL / Ubuntu / remote folder <kbd>Ctrl</kbd> + <kbd>K</kbd> <kbd>Ctrl</kbd> + <kbd>O</kbd>
3. Open the integrated terminal  <kbd>Ctrl</kbd> + <kbd>`</kbd>
4. Get version of `code`
    ```
    code --version
    1.80.2
    2ccd690cbff1569e4a83d7c43d45101f817401dc
    x64
    ```

The location of `code` in the terminal and in the VS Code integrated terminal are different
1. This is from the terminal
```
which code
/mnt/c/Users/username/AppData/Local/Programs/Microsoft VS Code/bin/code
```
2. This is from the VS Code integrated terminal
```
which code
/home/username/.vscode-server/bin/2ccd690cbff1569e4a83d7c43d45101f817401dc/bin/remote-cli/code
```

**Comment by rcdeo** [comment]
I have the same problem in VSCode Version: 1.81.0 - 6445d93c81ebe42c4cbd7a60712e0b17d9463e97 - x64

1. This is from the terminal
`/mnt/c/Program Files/Microsoft VS Code/bin/code: 61: /mnt/c/Program Files/Microsoft VS Code/Code.exe: Exec format error`
2. This is from the VS Code integrated terminal
`/home/USERNAME/.vscode-server/bin/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/bin/remote-cli/code`
`/mnt/c/Program Files/Microsoft VS Code/bin/code`

**Comment by chinsoon12** [comment]
Following this
https://github.com/microsoft/WSL/issues/8952#issuecomment-1568212651

resolved the below for me
/mnt/c/Program Files/Microsoft VS Code/bin/code: 61: /mnt/c/Program Files/Microsoft VS Code/Code.exe: Exec format error

**Comment by clmnin** [comment]
@chinsoon12 solution worked for me. Will be closing this issue
