### ISSUE TITLE
Connecting VS Code and WSL extension to Ubuntu will cause the /mnt/c directory in WSL2 to report input/output error.

### ISSUE THREAD

**Issue by chestarss** [microsoft/vscode-remote-release#8791]
- VSCode Version: 1.80.2
- Local OS Version: windows 11
- Remote OS Version: ubuntu 22.04.2
- Remote Extension/Connection Type: WSL

- Logs:

Steps to Reproduce:

1. open vscode project which type is remote wsl
2. in terminal will show input/output error.
![image](https://github.com/microsoft/vscode-remote-release/assets/11288347/2e5cdae0-10d4-41ab-8ae9-2a82a660478c)
3.  `ps -ef|grep vscode|awk '{print $2}'|xargs -i kill {}`

4. terminal will ok when aflter i close vscode
![image](https://github.com/microsoft/vscode-remote-release/assets/11288347/67097cf4-7636-4815-9000-ecbe047fb094)

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
The input/output errors are coming from WSL. E.g. https://github.com/microsoft/WSL/issues/5552 is a similar issue.
From what I know, the workaround is to run `wsl --shutdown`
