### ISSUE TITLE
vscode更新至1.81.0后，remote ssh连接卡顿无法正常使用

### ISSUE THREAD

**Issue by DddHBbb** [microsoft/vscode-remote-release#8796]
Type: <b>Performance Issue</b>

在windows机器上使用vscode插件remote ssh连接任意linux机器，均可复现

Extension version: 0.102.0
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 4.4.0-116-generic

**Comment by MYWProgram** [comment]
MacOS also has this problem.

**Comment by pluveto** [comment]
same issue

**Comment by DddHBbb** [comment]
我重新安装openssh就好了
