### ISSUE TITLE
integrated terminal unexpected result running command `w`

### ISSUE THREAD

**Issue by itzsimpl** [microsoft/vscode-remote-release#8799]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.78.2, b3e4e68a0bc097f0ae7907b217c1119af9e03435
- OS Version Remote: ubuntu 20.04
- OS Version Host: Ventura 13.4

Steps to Reproduce:

1. Establish a remote session to ubuntu 20.04
2. open integrated terminal
3. execute command `w`
4. nothing shows up

Expected Behaviour:
1. logged in user listed

Alternatives:
1. Any other way to determine if a user is currently logged in / actively using the remote system via vscode?

**Comment by itzsimpl** [comment]
I news on this?

A little background on what is the use case; we have a multi-user system, where multiple users use the vscode Remote SSH feature to access it. For mainatance of the system it would be very valuable to know when, and which, users are actively using the system (e.g. via the `w` command), so as to prevent any dataloss caused by upgrading and rebooting the system while in use.

Another related thing is that when Remote SSH creates the ssh session the output is logged in the OUTPUT pane (View > Output). One common approach for providing important messages to SSH users is via the `Banner` feature in `sshd_config`. However, since the SSH session that vscode Remote SSH creates is logged in solely in the OUTPUT pane, most users who access the system via vscode Remote SSH and focus on the `Terminal` window, will miss it, which defies the banner's notification function altogether. 

Any chance of passing this information to every `Terminal` session that the use opens? Or any other way of pushing a server side notification to the users? I would like to have some means to discover active users, and the ability to notify the active users that the system is about to be rebooted/shutdown to avoid data loss.

**Comment by roblourens** [comment]
I think we need to revisit the `-T` parameter, although it was required for some configurations, I have an issue to investigate that here: https://github.com/microsoft/vscode-remote-release/issues/7558
