### ISSUE TITLE
Simple Browser not working with tunnel port forwarding on vscode.dev

### ISSUE THREAD

**Issue by aleleba** [microsoft/vscode-remote-release#8800]
Versión: 1.81.0
Confirmación: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Fecha: 2023-08-02T12:38:25.436Z (hace 2 días)
Explorador: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

Connected with tunnel on vscode.dev

- Logs:

Steps to Reproduce:

1. Run a service on port
2. Trying to use simple browser to view the link of the port forwarded.
3. Page not load.

On vscode.dev connected to tunnel.
![image](https://github.com/microsoft/vscode-remote-release/assets/28767814/f04be441-a945-475c-9f13-2895b28c571b)

On local vscode connected to tunnel
![Captura de pantalla 2023-08-04 a la(s) 12 40 29 p  m](https://github.com/microsoft/vscode-remote-release/assets/28767814/f96bfa42-5433-4bc9-9f12-61123390c198)

Does this issue occur when you try this locally connected to tunnel?: Yes
Does this issue occur when you try this locally and all extensions are disabled yes connected to tunnel?: Yes

**Comment by connor4312** [comment]
This is because the Github login page sets `X-Frame-Options: deny`, preventing it from showing or doing the auth flow when embedded in an iframe. This is not under vscode control unfortunately.

**Comment by aleleba** [comment]
@connor4312 , thank you for your response, do you think that can contact guthub team to search a fix that work to both teams? 😁
