### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by waylight3** [microsoft/vscode-remote-release#8804]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### Expected Behavior

I have set up my Synology NAS server to allow SSH access, and I use VS Code Remote to access my files.
I work in a Docker container environment, so after connecting to the server via SSH, I go through another step to access the container.

### Steps To Reproduce

There is no problem with connecting via remote SSH, but as soon as I try to access the docker container, an error occurs.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[42 ms] Dev Containers 0.304.0 in VS Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97).
[41 ms] Start: Resolving Remote
[42 ms] Setting up container: /[my_container_name]
[42 ms] Host: ssh://[my_host_name]
[57 ms] Start: Run: ssh [my_host_name] /bin/sh
[81 ms] Start: Run in host: id -un
[9143 ms] [my_username]
[9143 ms] 
[9144 ms] Start: Run in host: getent passwd [my_username]
[9157 ms] Command in host failed: getent passwd [my_username]
[9158 ms] /bin/sh: line 2: getent: command not found
[9158 ms] Exit code 127
```

</p>
</details>

### Anything else?

Until updating remote docker ssh, I used to come across a warning message stating that the server does not support the appropriate glibc and libc-bin.
However, I couldn't install these two packages on the Synology NAS server, so I left it as is since vscode was working.
After the version update, I am consistently encountering this error, and I can no longer access the server, wondering if it is now mandatory to use getent.

**Comment by aleleba** [comment]
I have a synology NAS too, and I run a vscode instance to create a tunnel on it, this is my image and I use a custome image for that: https://hub.docker.com/repository/docker/aleleba/vscode-server/general this is my cutome image with common extensions and many engines languagues support like .net, node.js, java, python. Invite you to use it, I did not have any issues with that image, only the ones I raised before.

**Comment by waylight3** [comment]
I don't think the issue lies with the Docker image in my opinion.
Though I'm not certain about the exact process, it seems to be related to the usage of 'getent' by remote SSH, probably to look up Docker user information.
Even when using the suggested image, the same problem occurs.

**Comment by hoshikawa** [comment]
I was facing this problem too.
In my case, downgrading [`ms-vscode-remote.remote-containers`](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) on my client machine  to `v0.299.0` did the trick, so I suspect that the change related to [this issue](https://github.com/microsoft/vscode-remote-release/issues/2957) caused the problem which occurs when `getent` command is not installed.

**Comment by diedgarsa** [comment]
The same error (`getent: command not found`) also occurs when the remote machine is running macOS, which does not have `getent`, nor it can be installed.

Downgrading [`ms-vscode-remote.remote-containers`](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) to v0.299.0 worked as a workaround, thank you @hoshikawa!
