### ISSUE TITLE
opening remote workspace failing after latest update

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode-remote-release#881]
Issue Type: <b>Bug</b>

opening remote workspace failing after latest update

VS Code version: Code - Insiders 1.36.0-insider (b7ca272b6e041e42f9edfe48f4d559c2044cdaae, 2019-07-02T12:12:51.404Z)
OS version: Windows_NT x64 10.0.17134
Fetching remote diagnostics for 'SSH' failed: Downloading VS Code Server failed. Please try again later.

```
remote-ssh@0.42.2
SSH Resolver called for "ssh-remote+angular_serve"
SSH Resolver called for host: angular_serve
Setting up SSH remote "angular_serve"
Using commit id "b7ca272b6e041e42f9edfe48f4d55" and quality "insider" for server
Install and start server if needed
> 
> Installing to /root/.vscode-server-insiders/bin/
> 
> Downloading with wget
> 
> Unable to establish SSL connection.
> 
> 
"install" terminal command done
Received install output: 
Server download failed
Downloading VS Code Server failed. Please try again later.
```

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (3.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: Downloading VS Code Server failed. Please try again later.
</details>Extensions: none

**Comment by roblourens** [comment]
Does your remote have internet access?

Are you behind a proxy? Do you expect the https_proxy env var to be set?

**Comment by sanket-bhalerao** [comment]
Yes remote has internet access.
I am able to ssh the remote properly using cmder.
The remote connection was working properly before i installed the latest Insiders update.

**Comment by roblourens** [comment]
Something very strange going on,

`> Installing to /root/.vscode-server-insiders/bin/`

that should have the commit.

Does it still work with vscode stable?

**Comment by sanket-bhalerao** [comment]
![image](https://user-images.githubusercontent.com/9264813/60565343-d071bb80-9d80-11e9-8e65-4c5ecce2a735.png)
>issue snapshot

**Comment by sanket-bhalerao** [comment]
![image](https://user-images.githubusercontent.com/9264813/60565490-76252a80-9d81-11e9-8d00-8614ea8c9155.png)
>snapshot for stable build
build details Version: 1.35.1 (user setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

>extension list snapshot
![image](https://user-images.githubusercontent.com/9264813/60565550-acfb4080-9d81-11e9-865e-9acbedd12dda.png)

**Comment by sanket-bhalerao** [comment]
@roblourens can you please mention what more information i can provide to help on this?

**Comment by sanket-bhalerao** [comment]
as of now the issue is resolved. 
>screenshot
![image](https://user-images.githubusercontent.com/9264813/60593743-020a7700-9dc1-11e9-8179-8e250bb7f285.png)

**Comment by roblourens** [comment]
Did it just start working randomly? If it breaks again you could try the nightly version of the ssh extension + vscode insiders.

Also you can try just `wget https://update.code.visualstudio.com` on your remote to see if that works. And whether any of these tips help: https://stackoverflow.com/questions/28757232/unable-to-establish-ssl-connection-upon-wget-on-ubuntu-14-04-lts

**Comment by sanket-bhalerao** [comment]
@roblourens no changes are done from my side apart from the daily insider and extension updates.
I have checked the internet connectivity and it appears fine on the remote.
The issue can be closed, however, I am not sure what caused it or resolved it.

**Comment by sanket-bhalerao** [comment]
Closing this issue, as it has not re-occurred.
