### ISSUE TITLE
Command in host failed: getent passwd

### ISSUE THREAD

**Issue by Wei-Xiong123** [microsoft/vscode-remote-release#8811]
When i want to attach vs code to my docker container, it will appear this problem

"Error running command remote-containers.attachToRunningContainerFromViewlet: Command in host failed: getent passwd"

**Comment by muthyas** [comment]
v0.299.0 fixes getent issue, but has another problem that is:
mkdir: cannot create directory ‘/.vscode-server’: Permission denied

**Comment by romankarlstetter** [comment]
We have a similar problem with version 0.304. I reported the reason (and a potential fix) here: https://github.com/microsoft/vscode-remote-release/issues/2957#issuecomment-1671002829

**Comment by victorcpascua** [comment]
> I believe this error is caused by the changes introduced in [this PR](https://github.com/devcontainers/cli/pull/577). It's likely caused by using a machine that doesn't have `getent` installed. Until a fix is introduced, you should downgrade your copy of the `ms-vscode-remote.remote-containers` extension to `v0.299.0`. @chrmarti

Same problem, same fix, downgraded to v0.299.0 and working like a charm.

**Comment by chrmarti** [comment]
Looking into a fix here. What container images are you using that do not have `getent`, but the VS Code Server can run on? (I found Docker Hub's `busybox` does not have `getent`, but the VS Code Server does not run on that.)

**Comment by chrmarti** [comment]
Fixed in Dev Containers 0.306.0-pre-release. Please give that a try.

@romankarlstetter I have also fixed the handling of backslashes in the username, could you check if that works now?

**Comment by COWI-MI** [comment]
@chrmarti just tested that image **heartexlabs/label-studio:latest** fails with both v0.304.0 and v0.306.0.

The error for v0.306.0

```
[2023-08-23T07:19:17.859Z] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd '1001' || grep -E '^1001|^[^:]*:[^:]*:1001:' /etc/passwd)
[2023-08-23T07:19:17.861Z] Stop (2 ms): Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd '1001' || grep -E '^1001|^[^:]*:[^:]*:1001:' /etc/passwd)
[2023-08-23T07:19:17.861Z] Error: Command in container failed:  (command -v getent >/dev/null 2>&1 && getent passwd '1001' || grep -E '^1001|^[^:]*:[^:]*:1001:' /etc/passwd)
```

**Comment by romankarlstetter** [comment]
Unfortunately it does not really work for me either. If I use the `"remoteUser": "DOMAIN\foo",` setting in the `devcontainer.json` file, it is invalid json ("Invalid escape character in string"). 
Then I tried `"remoteUser": "DOMAIN\\foo",`, but now I'm _always_ getting an error when even trying to rebuild the container, even when completely removing the `remoteUser` option from `devcontainer.json`.

Going back to 0.299.0 works without the domain user.

**Comment by COWI-MI** [comment]
@chrmarti 
I figured out it happens when the Dockerfile sets the user to 1001. https://github.com/HumanSignal/label-studio/blob/develop/Dockerfile


### To reproduce:
Dockerfile
```Dockerfile
FROM alpine

USER 1001
```

.devcontainer/devcontainer.json
```json
{
	"name": "Existing Dockerfile",
	"build": {
		"context": "..",
		"dockerfile": "../Dockerfile"
	}
}
```
Run "Open in Dev container" and it fails.
Remove `USER 1001` and Dev container works.

**Comment by chrmarti** [comment]
Thanks for the feedback!

@romankarlstetter Continuing in https://github.com/microsoft/vscode-remote-release/issues/8873.
@COWI-MI Continuing in https://github.com/microsoft/vscode-remote-release/issues/8875.

**Comment by dss010101** [comment]
I was getting this error on latest, then switched to pre-release and getting this error now:
```

[2023-09-01T22:36:49.523Z] Stop (4 ms): Run in container: mkdir -p '/root/.vscode-server/bin' && ln -snf '/vscode/vscode-server/bin/linux-x64/6c3e3dba23e8fadc360aed75ce363ba185c49794' '/root/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794'
[2023-09-01T22:36:49.527Z] Command in container failed: mkdir -p '/root/.vscode-server/bin' && ln -snf '/vscode/vscode-server/bin/linux-x64/6c3e3dba23e8fadc360aed75ce363ba185c49794' '/root/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794'
[2023-09-01T22:36:49.527Z] mkdir: cannot create directory ‘/root’: Permission denied
```

**Comment by dss010101** [comment]
> I was getting this error on latest, then switched to pre-release and getting this error now:
> 
> ```
> 
> [2023-09-01T22:36:49.523Z] Stop (4 ms): Run in container: mkdir -p '/root/.vscode-server/bin' && ln -snf '/vscode/vscode-server/bin/linux-x64/6c3e3dba23e8fadc360aed75ce363ba185c49794' '/root/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794'
> [2023-09-01T22:36:49.527Z] Command in container failed: mkdir -p '/root/.vscode-server/bin' && ln -snf '/vscode/vscode-server/bin/linux-x64/6c3e3dba23e8fadc360aed75ce363ba185c49794' '/root/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794'
> [2023-09-01T22:36:49.527Z] mkdir: cannot create directory ‘/root’: Permission denied
> ```
> 
> I started having all these issues after switching to image: python:latest (which is debian12-bookworm based image)

If i add my host (windows 11) user id and name to the .env file used by docker compose, then pass that as an arg to the docker file, then in the docker file i create that user with group 1000.   it works.   so im guessing in the latest version its trying to run as the host user?  
Note: if i try to run the container as myself by adding 'USER myusername' it doesnt work

**Comment by COWI-MI** [comment]
@dss010101 this might be relevant: https://github.com/devcontainers/cli/pull/622#issuecomment-1698815270

**Comment by msingh0101** [comment]
> @dss010101 this might be relevant: [devcontainers/cli#622 (comment)](https://github.com/devcontainers/cli/pull/622#issuecomment-1698815270)

Ah, so it's running as root if no user specified.  That's the same behavior as before i believe.
 Interesting...this was all working fine before I upgraded the OS image..I didn't have to add or run as a new user.
