### ISSUE TITLE
fatal: Unable to persist credentials with the 'wincredman' credential store

### ISSUE THREAD

**Issue by davetapley** [microsoft/vscode-remote-release#8812]
When connecting to a Windows machine from MacOS over SSH,
I see this ⬇️  twice when I `git pull` or `git push`,
but the command does succeed 🤔 

```
fatal: Unable to persist credentials with the 'wincredman' credential store.
```

Looks like it's come up in a few other repos:

- https://github.com/microsoft/vscode/issues/138199
- https://github.com/git-ecosystem/git-credential-manager/issues/633

---

Low priority as it doesn't actually impact work, but 👍🏻 if you see it too.

**Comment by mhowlader** [comment]
https://github.com/git-ecosystem/git-credential-manager/blob/release/docs/credstores.md

By default, git credential manager will use windows credential manager as its store, but windows credential manager cannot be used over SSH. Recommend using `dpapi`
