### ISSUE TITLE
too many consoles in use, max consoles is 32

### ISSUE THREAD

**Issue by leet0rz** [microsoft/vscode-remote-release#8814]
Error:
```
      0 [main] bash 15358 C:\Program Files\Git\bin\..\usr\bin\bash.exe: *** fatal error - console device allocation failure - too many consoles in use, max consoles is 32
    255 [main] bash 15358 cygwin_exception::open_stackdumpfile: Dumping stack trace to bash.exe.stackdump

[process exited with code 256 (0x00000100)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

- VSCode Version: 1.18.0
- Local OS Version: 19044.3086

- Logs: attached.

Steps to Reproduce:

1. Using git-bash in the terminal.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

[logfile.txt](https://github.com/microsoft/vscode-remote-release/files/12291576/logfile.txt)

**Comment by bamurtaugh** [comment]
Can you please share some more information, i.e. which remote extension(s) you're using, the version of VS Code and the remote extension you're using, what you specifically did with git bash in the terminal?

**Comment by leet0rz** [comment]
> Can you please share some more information, i.e. which remote extension(s) you're using, the version of VS Code and the remote extension you're using, what you specifically did with git bash in the terminal?

I think the issue lays with git bash or new windows terminal. My bad. It seems git bash does not close properly and overflows at 32 instances.
