### ISSUE TITLE
SSH keys not forwarded to Codespaces

### ISSUE THREAD

**Issue by 3f6a** [microsoft/vscode-remote-release#8816]
Connecting to a Github Codespaces instance from vscode does not forward my local SSh keys. I have SSH keys added to my agent, and indeed connecting to other kinds of vscode remotes (via Remote-SSH) does forward my SSH keys correctly.

- VSCode Version: 1.81.0 (Universal)
- Local OS Version: macOS
- Remote OS Version: Linux (Codespaces)
- Remote Extension/Connection Type: Containers (Codespaces)

**Comment by bamurtaugh** [comment]
Thanks for filing. As this sounds like an issue with Codespaces, we'd recommend to please file in Codespaces Discussions: https://github.com/orgs/community/discussions/categories/codespaces. Thanks!

**Comment by bamurtaugh** [comment]
Thank you for clarifying! To ensure I understand: you're using the Codespaces extension https://marketplace.visualstudio.com/items?itemName=GitHub.codespaces? That Discussions area is the right spot for Codespaces extension issues as well. I'll check out the Discussion you opened and tag some folks too.

**Comment by bamurtaugh** [comment]
Got it! To help clarify, we consider each remote extension individually with its own feature requests and bugs: https://code.visualstudio.com/docs/remote/remote-overview.
