### ISSUE TITLE
[Remote-SSH Bug]: Failed to write `remote.SSH.remotePlatform`: CodeExpectedError: Unable to write to User Settings because remote.SSH.remotePlatform is not a registered configuration.

### ISSUE THREAD

**Issue by acse-pms122** [microsoft/vscode-remote-release#8819]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [x] I have followed these troubleshooting steps
- [x] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Connect to a remote machine.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
...
[15:40:14.948] [Forwarding server 56180] Got connection 1
[15:40:14.948] > 
[15:40:15.021] [Forwarding server 56180] Got connection 2
[15:40:18.942] Failed to write `remote.SSH.remotePlatform`: CodeExpectedError: Unable to write to User Settings because remote.SSH.remotePlatform is not a registered configuration.
```

</p>
</details>

### Anything else?

Yesterday it worked without any problems... I don't think I udated VSCode.

**Comment by acse-pms122** [comment]
It somehow worked after restarting a few times:)

**Comment by acse-pms122** [comment]
Issue happened again today.... I did not change anything

**Comment by acse-pms122** [comment]
It now says:

[09:31:03.203] Forwarding server listening on 52019
[09:31:03.203] Waiting for ssh tunnel to be ready
[09:31:03.204] [Forwarding server 52019] Got connection 0
[09:31:03.205] Tunneled 37583 to local port 52019
[09:31:03.205] Resolved "ssh-remote+ese-hivemind.ese.ic.ac.uk" to "127.0.0.1:52019"
[09:31:03.208] ------




[09:31:03.217] [Forwarding server 52019] Got connection 1
[09:31:03.230] > 


______________________________________
Then it looks like it is connected but I cannot open a terminal or a folder and then it asks me for my password again and the whole thing starts over again.

**Comment by roblourens** [comment]
That error message is not necessarily a real message.  Please share the full log and just tell me exactly what actually happens

**Comment by stargolike** [comment]
The bug also has happened in my computer，i cant connect my remote machine.

**Comment by TimFelixBeyer** [comment]
> That error message is not necessarily a real error. Please share the full log and just tell me exactly what actually happens

I have the same issue. 
Since the last update, VSCode asks me for the ssh password twice before connecting. The ssh setup then takes extremely long (3-5mins) on each connection, much longer than before.
Sometimes it looks like the connection is established, and the remote file browser shows up but then the connection drops again and VSCode asks for a password.
I am only getting this particular error message when using useLocalServer = false, but I only changed this setting to try and fix the connection issues.
