### ISSUE TITLE
Remotely installed extensions disappear after reconnect

### ISSUE THREAD

**Issue by amirhosseindavoody** [microsoft/vscode-remote-release#8820]
- VSCode Version: July 2023 (version 1.81)
- Local OS Version: Windows 11
- Remote OS Version: SLES 12 (Open Suse)
- Remote Extension/Connection Type: Server

- Logs:

Steps to Reproduce:

1. Use VScode remote extension to connect remotely to the Linux server from a Windows Machine 
2. Install python and pylance extensions on the remote server.
3. Close the connection by closing vscode.
4. Open vscode and connect to the linux server again.
5. The extension that are installed in the linux server have disappeared and need to be installed again.

Note that this is a flaky issue, but happens about 50% of the times for me.

Also, I am able to see the installed extensions in the `.vscode-server/extensions` folder but some how it is not discovered by vscode when a new connection is established.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by schlunma** [comment]
I have the exact same issue with the Python and Pylance extensions. After installing them, they appear in `.vscode_server/extensions/extensions.json` and corresponding subdirectories exist in `.vscode_server/extensions/`. After exiting and re-opening VSCode, the extensions still appear in `.vscode_server/extensions/extensions.json`, but the two subdirectories of the Pylance and Python extensions in `.vscode_server/extensions/` are gone.

- VSCode Version: 1.81.0
- Local OS Version: Windows 10
- Remote OS Version: OpenSUSE Tumbleweed
- Remote connection type: WSL

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by sandy081** [comment]
Can you please update to 1.81.1 and see if you can still reproduce the issue?

**Comment by schlunma** [comment]
It seems to work fine again for me with 1.81.1. All extensions work as expected 👍
