### ISSUE TITLE
Let Simple Browser working with tunnel port forwarding on vscode.dev

### ISSUE THREAD

**Issue by aleleba** [microsoft/vscode-remote-release#8821]
Hi @connor4312 I know that we start to talk about this feature in https://github.com/microsoft/vscode-remote-release/issues/8800 but I am wondering if is possible to talk to the team that manage the Github login, or if you know a channel to communicate to them and ask for a possible support, I think this should be a great improvement, I personally use this to no left my dev environment. Thank you a lot for your patience and thank you for your work.

**Comment by connor4312** [comment]
This is a security feature and is not something they're willing to change
