### ISSUE TITLE
Port Visibility menu showing duplicate entries

### ISSUE THREAD

**Issue by derekbekoe** [microsoft/vscode-remote-release#8822]
I got into a state where port visibility is showing up twice.

![Image](https://github.com/microsoft/vscode-remote-release/assets/16448634/9ff83627-4a00-47b9-a9d0-ae557580f0d7)

Version: 1.82.0-insider
Commit: bf9c8105647b1e9d244f0f00155c21298e7554cf
Date: 2023-08-09T05:35:11.584Z (15 hrs ago)
Electron: 25.4.0
ElectronBuildId: 22901934
Chromium: 114.0.5735.248
Node.js: 18.15.0
V8: 11.4.183.27-electron.0
OS: Darwin x64 22.6.0
- Remote Extension/Connection Type: Tunnels

Steps to Reproduce:

_Haven't been able to reproduce yet since the screenshot was taken. Will update if there's a clear repro_

Does this issue occur when you try this locally?: n/a
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

cc: @connor4312

**Comment by connor4312** [comment]
Can you verify that you're on the latest prerelease version of the Remote Tunnels extension? That version has its tunnel factory removed (in favor of the now built-in version), thinking you might get these if there were two factories registered...

**Comment by derekbekoe** [comment]
I've been testing with the pre-release version.
Currently, it says "Remote - Tunnels v1.5.2023080809 Pre-Release".
However, it's possible it auto-updated after I took the screenshot as I didn't check the version at that time.

Feel free to close. I can re-comment if I see it happen again.

**Comment by connor4312** [comment]
That version is correct. Please re-open if you see it again.
