### ISSUE TITLE
"EACCES: permission denied" issue in Remote Explorer extension

### ISSUE THREAD

**Issue by zgjja** [microsoft/vscode-remote-release#8824]
"EACCES: permission denied" issue in Remote Explorer trying to open container from there.

- VSCode Version: 1.81.0
- Local OS Version: Ubuntu-22.04
- Remote OS Version: Ubuntu-20.04
- Remote Extension/Connection Type: Containers

- Logs:
Error running command remote-containers.openFolderInContainerInNewWindow: A system error occurred (EACCES: permission denied, scandir '/root/disk/`<MyFolder>`'). This is likely caused by the extension that contributes remote-containers.openFolderInContainerInNewWindow.

Steps to Reproduce:

I have a mobile hard disk and it's mounted on my OS with docker env and my repo, and used on 2 computers with same uid and gid, the folder permission is ok (775, root) but this error prevents me from open multiple folders in a container.

1. both repo and docker on the mobile disk, mount setting is 'defaults', umask is 002;
2. container's repo can still access from the shortcut in welcome and open manually after attach vscode into it, which i guess it's not the permission issue of my repo's folder;
3. the repo folder is a bind mount of container;
4. when opening a repo or folder inside container, another error appears: `Error running command remote-containers.openFolderInContainerInNewWindow: spawn /usr/share/code/resources/app/node_modules.asar.unpacked/@vscode/ripgrep/bin/rg EACCES. This is likely caused by the extension that contributes remote-containers.openFolderInContainerInNewWindow.`
5. what i tried to fix:
  * delete .vscode-server folder in container and reinstall;
  * rebuild container with docker compose;
  * sudo chmod my repo folder;
  * check the mounted disk's permission;
  * add `privileged: true` when building the container with docker compose;
  * reinstall vscode;
None of above works, how to fix this?

Does this issue occur when you try (open repo in vscode) this locally?: No

**Comment by zgjja** [comment]
With some trying, finally find one workaround, just down grade the `dev container` version to at least `v0.299.0`, the newest version has a bug.

**Comment by dss010101** [comment]
This seems to happen ALOT running in a remote devcontainer.  Im unable to delete some files/folders due to this.  Afte a day or two, the issue is resolved.
Something is holding on to these files/folders it feels like

**Comment by chrmarti** [comment]
Is this still an issue?
