### ISSUE TITLE
Creates some extensions that can run emulators of android and ios for mobile develop on the browser.

### ISSUE THREAD

**Issue by aleleba** [microsoft/vscode-remote-release#8829]
Creates some extensions that can run emulators of android and ios for mobile develop on the browser.

This should be a good feature to develop mobile apps from browser, this could become vscode the full tooling for any developer.

**Comment by bamurtaugh** [comment]
Thanks for filing. You're definitely welcome to create and publish new extensions! We have guidance here: https://code.visualstudio.com/api.

If you're experiencing a specific issue with one of the remote development extensions, please feel free to file a new issue.
