### ISSUE TITLE
Schema versioning in devcontainer.json...

### ISSUE THREAD

**Issue by code-n-go** [microsoft/vscode-remote-release#8831]
Could we please get support for schema versioning in the devcontainer.json (like docker-compose.yml)?  For the most part, those configs don't get changed much once created, and it's pretty frustrating to see 'deprecated' messages all over the place during rebuilds, and in some rare (but still viable) instances... things just flat out not installing/working that used to, w/o any issues.

**Comment by bamurtaugh** [comment]
Thanks so much for filing. We have an issue in the dev containers org to discuss versioning - we'd appreciate your feedback there: https://github.com/devcontainers/spec/issues/248.

I'm also curious to learn more about any specific config or tools you have in your dev container that are deprecated and causing frustration - this kind of feedback is really helpful to the team.

**Comment by code-n-go** [comment]
Thank you for linking the specification.  I'll absolutely take a look and contribute feedback.  Much appreciated @bamurtaugh!
