### ISSUE TITLE
Devcontainer.json doesn't update when open and adding extension

### ISSUE THREAD

**Issue by olguzzar** [microsoft/vscode-remote-release#8834]
- VSCode Version: Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
- Remote Extension/Connection Type: Containers

Steps to Reproduce:

1. Connect to dev container
2. Open the devcontainer.json file
3. Right click on an extension and click "Add to devcontainer.json"
4. Expected result: The extension id gets added to the devcontainer.json
5. Actual result: There is no visible change to the devcontainer.json, and you must reopen the file to see the change reflected

Recording: 

https://github.com/microsoft/vscode-remote-release/assets/95261576/555fa655-6ad6-42e4-9d91-0d071a2df032

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

@bamurtaugh the issue we discussed :) 
@chrmarti

**Comment by chrmarti** [comment]
Sounds like a missing file event. Need to check if the extension changes the file in the container or locally.

**Comment by chrmarti** [comment]
Fixing as part of https://github.com/microsoft/vscode-remote-release/issues/2243.
