### ISSUE TITLE
Server cannot get a connection after waking up from suspend

### ISSUE THREAD

**Issue by Anatoly03** [microsoft/vscode-remote-release#8839]
This issue is bump of [this issue](https://github.com/microsoft/vscode-remote-release/issues/2627), which got closed.

- VSCode Version: Version: 1.81.1, Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
- Local OS Version: Mac OS Ventura 13.2.1 (22D68)
- Remote OS Version: Ubuntu 22.04.3 LTS
- Remote Extension/Connection Type: Containers/WSL/Server

- Logs: Not sure how to get them.

Steps to Reproduce:

1. Connect to server
2. Put server device to sleep/ suspend
3. Awake device
4. Connecting is no longer possible

Does this issue occur when you try this locally?: - (Problem depends on remote connection)
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Image Client:

<img width="1440" alt="Screenshot 2023-08-13 at 18 56 59" src="https://github.com/microsoft/vscode-remote-release/assets/44678124/a819349e-fe5b-4bcf-a899-b0dc46988b91">

**Comment by roblourens** [comment]
I believe that issue was about the client sleeping. In this case where the server sleeps and the client is probably trying to unsuccessfully connect to it for some time, I would expect it to time out at some point.
