### ISSUE TITLE
non-interactive execution is NOT allowed

### ISSUE THREAD

**Issue by frostnotfall** [microsoft/vscode-remote-release#884]
In my few Special case，opensssh must use keyboard-interactive to login.
when I use OpenSSH Direct login on powershell，it works.
but when I login on vscode，it does not works

- VSCode Version: 1.36.0(Inside)
- Local OS Version: Windows 10 1903
- Remote OS Version: CentOS 6.3
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. config file: PreferredAuthentications keyboard-interactive
2. Enable the remote.SSH.showLoginTerminal setting in VS Code
2. login in vscode with remote-ssh

![image](https://user-images.githubusercontent.com/38377709/60561356-d61dd000-9d85-11e9-8e22-6eab2edcd1ea.png)

**Comment by roblourens** [comment]
Can you tell me more about how you authenticate to your ssh host? Are you sure this is related to `keyboard-interactive` and not another requirement by the host?

Do you have a special PAM installed? 

What do you enter when logging in?

What is the output of running `ssh host 'echo hello'` in a normal terminal?

**Comment by frostnotfall** [comment]
Yes, a special PAM，but it doesn't need extra software。
I need keyboard-interactive and I will get a QR Code ，or  2-Step  password。
Custom ssh-client, powershell or Xshell , use keyboard-interactive mode and It works, so I guess vscode doesn't support  keyboard-interactive?

**Comment by roblourens** [comment]
Can you tell me how you installed or configured this PAM so that I can try it?

**Comment by ysrcyx** [comment]
I have the same problem.
it works in terminal,but doesn't work in Remote - SSH
![111](https://user-images.githubusercontent.com/14849010/63849698-2f406380-c9c5-11e9-8935-a855ffdecae4.jpg)

![222](https://user-images.githubusercontent.com/14849010/63849708-36677180-c9c5-11e9-88ac-e02fa7a12445.jpg)
