### ISSUE TITLE
When launched from the terminal, executables open unfocused, behind the VSCode window.

### ISSUE THREAD

**Issue by rainlizard** [microsoft/vscode-remote-release#8840]
- VSCode Version: 1.81.1
- Local OS Version: Windows 10
- Remote OS Version: 22.04.2 LTS
- Remote Extension/Connection Type: WSL

- Logs: none

Steps to Reproduce:

1. Put VSCode in WSL mode
2. Open a project
3. Type `notepad.exe` into the terminal
4. Observe that it opens behind VSCode (very very annoying)

- VSCode in normal-mode, no project opened and type `notepad.exe` into the terminal: it launches in front
- VSCode in normal-mode, project opened and type `notepad.exe` into the terminal: it launches in front
- VSCode in WSL-mode, no project opened and type `notepad.exe` into the terminal: it launches in front
- VSCode in WSL-mode, project opened and type `notepad.exe` into the terminal: **it launches in background**

But also in WSL-mode if you close the project you've opened, then the bug will persist.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by aeschli** [comment]
I'm not able to reproduce this issue.
It's th window manager of the OS that decides which window gets in front. The newly opened window get the focus and therefore are put in front.
Can it be that VS Code grabs the focus?
