### ISSUE TITLE
code command in WSL removes previous VS code server and it doesn't work in offline environment

### ISSUE THREAD

**Issue by Tagussan** [microsoft/vscode-remote-release#8849]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.0
- OS Version: WSL 2

Steps to Reproduce:

1. Type `code` command in WSL in the offline environment
2. If there's a newer version of VSCode, it starts removing the previous installation. After removal, it tries to fetch the newest version, which fails in offline environment. 
3. I can't launch VSCode in WSL using `code` command anymore in offline environment. I need an internet connection to start VSCode again
![dont_update_please](https://github.com/microsoft/vscode/assets/3764516/bad265ab-e89b-42be-aa38-9ebbd61e55b2)

**Comment by bamurtaugh** [comment]
Thanks for filing. I believe this would be covered by some combination of https://github.com/microsoft/vscode-remote-release/issues/1242, https://github.com/microsoft/vscode-remote-release/issues/1802, and https://github.com/microsoft/vscode-remote-release/issues/1399. If you believe this is a separate issue, please just let me know!
