### ISSUE TITLE
[Remote-SSH Bug]: SSH authenticates then exits

### ISSUE THREAD

**Issue by shushansh** [microsoft/vscode-remote-release#8850]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

ssh command to complete successfully.

### Remote-SSH Log

![image](https://github.com/microsoft/vscode-remote-release/assets/46396200/84793dd4-5525-4ece-9093-195fe28e6de7)

### Anything else?

Unable to pin-point the command which is causing this error, ssh connection is successful when I do it directly from the terminal.
Even the SSH authentication is successful, but then the process exits throwing the permission error.

**Comment by roblourens** [comment]
I think that error about not being authorized is the issue. Maybe there is something wrong with your config, or you may have to troubleshoot it on your end or ask your system administrator.
