### ISSUE TITLE
Remote - Tunnels on vscode.dev is not working propertly because a misconfiguration of the default version.

### ISSUE THREAD

**Issue by aleleba** [microsoft/vscode-remote-release#8859]
Remote - Tunnels on vscode.dev is not working propertly because a misconfiguration of the default version.

![Captura de pantalla 2023-08-18 a la(s) 5 15 28 p  m](https://github.com/microsoft/vscode-remote-release/assets/28767814/bff122c7-fee3-4516-b1f8-ebf9b96a00dc)

**Comment by aleleba** [comment]
@connor4312 sorry for bother you, but I think this hotfix is important because is a break of thr tunnel feature on vscode.dev

**Comment by connor4312** [comment]
Thanks, new release is on the way
