### ISSUE TITLE
In my vs code html file is not working can't code...please give a solution for me ...

### ISSUE THREAD

**Issue by anasmuhammmad** [microsoft/vscode-remote-release#8862]
- VSCode Version:
- Local OS Version:
- Remote OS Version:
- Remote Extension/Connection Type: Containers/WSL/Server

- Logs:

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by bamurtaugh** [comment]
Can you please provide more info? i.e. is this an issue with a Remote Development extension, or with VS Code in general? Can you provide a screenshot and paste any logs?
