### ISSUE TITLE
Remote Tunnels v1.4.2 hangs on connecting to remote

### ISSUE THREAD

**Issue by spitis** [microsoft/vscode-remote-release#8864]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

v1.40 works. v1.42 broke something and does not. 

### Remote-SSH Log

I don't know. Not my problem, sorry. I don't even know if "Remote - Tunnels" is "Remote-SSH"

**Comment by spitis** [comment]
And yes, I've tried this on multiple machines / clients, with both normal and insiders vscode clients. It connects in the browser, but the v1.42 extension broke the desktop clients (via WSL)

**Comment by littlegiqnt** [comment]
also happening on tunnel

**Comment by owen-hope11** [comment]
Downgraded back to `v1.4.0` to get it working again.

**Comment by crankedguy** [comment]
same here, nothing in the logs to see, just does not work, 1.4.0 as said works, Windows latest version, Remote installes on RHEL 9

**Comment by itay-sho** [comment]
had a similar issue. switching to pre-release version resolved my problem too.

**Comment by legendof-selda** [comment]
same issue here
Latest version of Remote - Tunnels v1.4.2 doesn't connect to my linux VM where code tunnel is running.
Downgraded the extension to v.1.4.0 in desktop and it works.
In console I see the warning "extensionDescriptionRegistry.ts:358 The customer named _initialize has been holding on to the lock for 30s. This might be a problem." when trying to connect to remote tunnel in v1.4.2

Same as #8867

**Comment by mdonato-fn** [comment]
Same here, using verbose on the server shows that the connection never even gets there from the client

**Comment by connor4312** [comment]
Please confirm what version of the CLI or VS Code you're using to _host_ the tunnel

**Comment by neil176** [comment]
I'm seeing this with
```
code --version
1.81.1
6c3e3dba23e8fadc360aed75ce363ba185c49794
arm64
```

Using the same install of vscode for both server and client on same machine (my team's only current use of the tunnel feature is to run the typescript server outside of electron in order to be able to give it more heap memory in a large monorepo). Hosting the tunnel appears completely fine, as access from `vscode.dev` still works.

As someone mentioned above, changing to prerelease `v1.5.2023080709` version of the remote tunnel extension solves the issue from client side.

**Comment by connor4312** [comment]
Thanks, 1.4.3 with the fix will be out in a few minutes

**Comment by neil176** [comment]
Huge thanks for the quick fix on this @connor4312 , I was planning on rolling out tunnel usage to a lot of engineers next week and seeing the fast turnaround here is very confidence-inspiring!
