### ISSUE TITLE
No WSL distros found. New distros can be installed from the Microsoft Store

### ISSUE THREAD

**Issue by ctsyeh** [microsoft/vscode-remote-release#8865]
Hi,

I have been a long time user of VSCode and WSL 2.0 with Ubuntu.  Everything works great until recently.  I searched couldn't find any ticket or posting can help me to resolve my issue.

I have two computers that this is happening on. 
### Computer #1 - Work Computer
Group policy prevents me from installing from Windows App Store.
12:49:09.54 => wsl --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19044.3324

Tried VSCode with System installation and User's Installation
WSL Ubuntu 22.04 installed using wsl --install -d Ubuntu-22.04

13:58:06.12 => wsl --list
Windows Subsystem for Linux Distributions:
Ubuntu-22.04 (Default)
OracleLinux_9_1

13:58:11.97 => wslconfig /list
Windows Subsystem for Linux Distributions:
Ubuntu-22.04 (Default)
OracleLinux_9_1

![image](https://github.com/microsoft/vscode-remote-release/assets/10673028/5a7d2896-2a8a-49e8-883a-b83e845fba8d)

From within VSCode terminal
![image](https://github.com/microsoft/vscode-remote-release/assets/10673028/fce7a868-bad9-48da-aaac-eb29f8215761)

- VSCode Version:  1.80.1 and  1.79.02
- Local OS Version: Windows 10.0.19044.3324
- Remote OS Version:  Ubuntu-22.04 (Default) and OracleLinux_9_1
- Remote Extension/Connection Type: WSL (v0.79.5)

WSL: Show Long
[2023-08-20 20:59:13.369] Download in background is enabled
[2023-08-20 20:59:13.484] WSL feature installed: true
[2023-08-20 20:59:41.483] Run: C:\WINDOWS\System32\wsl.exe --list --verbose
[2023-08-20 21:11:13.532] Update check by another window detected, skipping.

[2023-08-20 21:13:05.411] WSL feature installed: true
[2023-08-20 21:13:05.422] Resolving wsl+Ubuntu-22.04, resolveAttempt: 1
[2023-08-20 21:13:05.422] Run: C:\WINDOWS\System32\wsl.exe --list --verbose
[2023-08-20 21:13:47.622] Download in background is enabled
[2023-08-20 21:14:17.625] Update check by another window detected, skipping.

### Computer #2 - Home Computer
This was working until I disconnected from Remote and now I can't get it to reconnect
**I also installed Ubuntu-20.04 from the App Store and VSCode still reports No WSL distros found **

13:57:48.11 => wsl --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2134
```
14:09:25.10 => wsl --list --verbose
  NAME            STATE           VERSION
* Ubuntu-22.04    Running         2
  Ubuntu-20.04    Running         2
```
```
14:09:30.46 => wslconfig /list
Windows Subsystem for Linux Distributions:
Ubuntu-22.04 (Default)
Ubuntu-20.04
```
- VSCode Version:  1.80.1
- Local OS Version: Windows 10.0.22621.2134
- Remote OS Version:  Ubuntu-22.04 (Default) and Ubuntu-20.04
- Remote Extension/Connection Type: WSL (v0.72.0)

- VSCode Version:
- Local OS Version:
- Remote OS Version:
- Remote Extension/Connection Type: Containers/WSL/Server

WSL: Show Long

Steps to Reproduce:

1. From within a WSL distro, execute "code ."  VSCode starts but is unable to connect, it's stuck on "Opening Remote..."
2. I also removed the .vscode-server folder in the Distro

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: N/A.  I tried uninstalling and re-installing the extension and it still didn't resolve the issue.

I reviewed and tried all the following and couldn't get it to work:

1. https://github.com/microsoft/vscode-remote-release/issues/8446
3. https://github.com/microsoft/vscode-remote-release/issues/3910 - Tried with and without being an administrator
4. https://github.com/microsoft/WSL/issues/3244

**Comment by ctsyeh** [comment]
I performed a fresh install of WSL and attempted personal and system install of VSCode.  The issue still remain.

Please help.

**Comment by aeschli** [comment]
On your home mahcine you are on a quite old version of the WSL extension.
- Can you try with the latest WSL extension? That's currently 0.81.0. It requires VS Code 1.81 which is the latest stable version.
- You can install a specific version of the WSL extension in the extensions viewlet. Search for WSL and open the context meny: `Install Another Version...`
- After installing a new WSL version, please always close and restart VS Code. You can also do a `wsl --shutdown` in the command prompt to get WSL restarted.
- If `0.81.0` doesn't find any distro, please try version 0.78.3 of the WSL extension. There were some refactings in-between, maybe that caused the problem.

**Comment by ctsyeh** [comment]
Hi @aeschli .  Thank for your help.

On my home computer, I did a complete uninstall.
I unregistered the distro.  From the Add/Remove app, I uninstalled Ubuntu-22.04 and Windows Subsystem for Linux.  I also disabled Virtual Machine Platform feature.  For some reason, Windows subsystem for Linux feature is not enabled.  

Reboot

Then re-install Ubuntu-22.04 using wsl --install -d Ubuntu-22.04.
Then I installed VScode and upgraded to the latest 1.81 and upgraded the WSL plugin to 0.81.0
I shutdown and restarted WSL.
* At this point, WSL work but VSCode will can't find a distro.  I even enabled the Windows SubSystem for Linux and reboot; still doesn't recognized the WSL distro.

Downgrade the WSL plugin to 0.78.3; shutdown and restart WSL, still it doesn't work, outputs below.

** Keep in mind, that it was working on this computer until I disconnected from WSL.  Now, I can't reconnect.  Almost like the system has leftover cache or registry setting.

nis c:\Projects
22:56:47.07 => wsl --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2134

nis c:\Projects
22:56:49.38 => code --version
1.81.1
6c3e3dba23e8fadc360aed75ce363ba185c49794
x64

nis c:\Projects
22:56:56.55 => wsl
yeh@MOREFINE:/mnt/c/Projects$ code --version
1.81.1
6c3e3dba23e8fadc360aed75ce363ba185c49794
x64

nis c:\Projects
22:59:56.91 => code --list-extensions --show-versions
ms-vscode-remote.remote-containers@0.304.0
ms-vscode-remote.remote-ssh@0.102.0
ms-vscode-remote.remote-ssh-edit@0.86.0
ms-vscode-remote.remote-wsl@0.78.3
ms-vscode.remote-explorer@0.4.1
ms-vscode.remote-server@1.4.3

**Comment by ctsyeh** [comment]
I found the solution, thanks to theSpark user on StackOverFlow (https://stackoverflow.com/questions/how-to-answer?questionid=74895728&reason=thankyou&s=dbe54dfa-2ec1-46ac-a0a0-801b7620b08f)

The solution was to unset WSL_UTF8 variable.  I recently set this to 1 because I wanted to be able to grep the output of the WSL command.

It seems that VSCode should be able to handle if the WSL is set to UTF8 or not.

**Comment by aeschli** [comment]
Thanks for finding that. I will push a fix.

**Comment by zero00072** [comment]
> I found the solution, thanks to theSpark user on StackOverFlow (https://stackoverflow.com/questions/74895728/wsl-distros-not-visible-to-vscode-or-intellij-ides/76980745#76980745)
> 
> [Edit] - Fixed the StackOverFlow URL.
> 
> The solution was to unset WSL_UTF8 variable. I recently set this to 1 because I wanted to be able to grep the output of the WSL command.
> 
> It seems that VSCode should be able to handle if the WSL is set to UTF8 or not.

Useless to me. The problem still occurred very often on Code Insiders `1.82.0-insider`.

Another way to solve this very wonderful. Downgrade the WSL ext to `v0.78.9`, it connected successfully every time.

**Comment by aeschli** [comment]
Please try version v0.81.2. It has a fix for the `WSL_UTF8 ` variable.

@zero00072 If that doesn't work for you, can you open a new issue?
I'd like to know what the WSL log says and what you get when you run `wsl --list --verbose` on the command line.

**Comment by bdlake** [comment]
> Another way to solve this very wonderful. Downgrade the WSL ext to `v0.78.9`, it connected successfully every time.

@zero00072 Thank you, rolling back to WSL extension to v0.78.9 fixed this issue for me. 
VSCode was working fine, then suddenly when I tried to launch it, I would get `No WSL distros found. New distros can be installed from the Microsoft Store`. Tried reinstalling the WSL extension, reinstalling VSCode, and installing the previous version of both VSCode and WSL ext but none of that worked. Installing v0.78.9 finally allowed VSCode to find WSL. Now I guess I'm stuck at this version for a while. 
@aeschli this is the output to `wsl --list --verbose`:
```
  NAME                   STATE           VERSION
* Ubuntu                 Running         2
  docker-desktop-data    Stopped         2
  docker-desktop         Stopped         2
```
I believe this issue should be reopened as it's still happening as of latest VSCode v1.82.2 and WSL ext v0.81.3.

**Comment by zero00072** [comment]
> > Another way to solve this very wonderful. Downgrade the WSL ext to `v0.78.9`, it connected successfully every time.
> 
> @zero00072 Thank you, rolling back to WSL extension to v0.78.9 fixed this issue for me. VSCode was working fine, then suddenly when I tried to launch it, I would get `No WSL distros found. New distros can be installed from the Microsoft Store`. Tried reinstalling the WSL extension, reinstalling VSCode, and installing the previous version of both VSCode and WSL ext but none of that worked. Installing v0.78.9 finally allowed VSCode to find WSL. Now I guess I'm stuck at this version for a while. @aeschli this is the output to `wsl --list --verbose`:
> 
> ```
>   NAME                   STATE           VERSION
> * Ubuntu                 Running         2
>   docker-desktop-data    Stopped         2
>   docker-desktop         Stopped         2
> ```
> 
> I believe this issue should be reopened as it's still happening as of latest VSCode v1.82.2 and WSL ext v0.81.3.

Yes, thanks to your reply.

I have opened here #8924 .
