### ISSUE TITLE
Can't open .ssh/config via vscode 

### ISSUE THREAD

**Issue by rbavery** [microsoft/vscode-remote-release#887]
Issue Type: <b>Bug</b>

when clicking the CONNECTIONS settings button and then my config file nothing happens. I'm on the latest stable version of vscode and the remote ssh extension and Ubuntu 16.04 LTS.

![Selection_530](https://user-images.githubusercontent.com/22258697/60623795-5fd69900-9d98-11e9-8b68-f43da49c0e38.png)

Extension version: 0.44.0
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 4.15.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.08GB (0.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Does that file exist?
