### ISSUE TITLE
Can not open vscod.dev in web browser

### ISSUE THREAD

**Issue by jcheynet** [microsoft/vscode-remote-release#8871]
VSCode Version: Latest
Local OS Version: Latest windows/macos/ipados
Remote OS Version: Latest windows/macos/ipados
Remote Extension/Connection Type: Tunnels
Steps to Reproduce:

Open vscode.dev in any web browser.
![image](https://github.com/microsoft/vscode-remote-release/assets/30298903/9b39ef03-c94a-46c4-82fa-44bddb37b7a9)

The same with https://github.com/microsoft/vscode-remote-release/issues/7443 & 151368 & 8609

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by bamurtaugh** [comment]
Thanks for filing. Do you still experience this?

**Comment by jcheynet** [comment]
Hi Brigit,

Yes, I still do.

Best Regards / Sincerely
Joseph CHEYNET
PLM Project Manager

***@***.***
PRECISION SEALING SYSTEM
Le Joint Français SNC
1 rue Gutenberg, ZI ouest de Bazouges
53200 - Château Gontier sur MAyenne
FRANCE
www.hutchinson.com<http://www.hutchinson.com/>
***@***.*** +33.2.43.09.23.68
***@***.*** ***@***.******@***.***>
***@***.*** <https://www.linkedin.com/company/hutchinson>   ***@***.***  <https://www.facebook.com/hutchinson.co?utm_source=signature&utm_medium=email&utm_campaign=Facebook>   ***@***.***  <https://www.instagram.com/hutchinson_company/?utm_source=signature&utm_medium=email&utm_campaign=Instagram>   ***@***.***  <https://www.hutchinson.com/fr/wechat-qr-code>
***@***.***

Be kind to our planet and print this email only when necessary.

CONFIDENTIALITY. :
This email (including any attachments) may contain information which could be confidential.
It may not be used other than for the purpose for which it has been sent.
If you are not the intended recipient, please delete it and notify immediately the sender.




De : Brigit Murtaugh ***@***.***>
Envoyé : mardi 29 août 2023 23:46
À : microsoft/vscode-remote-release ***@***.***>
Cc : CHEYNET Joseph ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/vscode-remote-release] Can not open vscod.dev in web browser (Issue #8871)

EXTERNAL


Thanks for filing. Do you still experience this?

-

**Comment by jcheynet** [comment]
No I have the same error:
***@***.***
***@***.***

De : Brigit Murtaugh ***@***.***>
Envoyé : mercredi 30 août 2023 17:26
À : microsoft/vscode-remote-release ***@***.***>
Cc : CHEYNET Joseph ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/vscode-remote-release] Can not open vscod.dev in web browser (Issue #8871)

EXTERNAL


Are you able to navigate to https://vscode.dev/ on its own (independent of tunneling) successfully?

When you experience this error, what are the steps that led to it? Do you start a tunnel via the code CLI and click the vscode.dev link it generates?

-

**Comment by bamurtaugh** [comment]
Interesting - it sounds like there's something specific with your browser or machine setup, since https://vscode.dev/ should load no problem (it just loaded for me). 

- Are you behind any sort of proxy or firewall? 
- Related ^, do you have trouble/limitations accessing any other sorts of websites?
- Does clearing cookies and trying https://vscode.dev/ again help?

**Comment by jcheynet** [comment]
Yes, we have a firewall in our company. Clearing the cash does not help.
I do not have any trouble accessing other sites

De : Brigit Murtaugh ***@***.***>
Envoyé : mercredi 30 août 2023 17:40
À : microsoft/vscode-remote-release ***@***.***>
Cc : CHEYNET Joseph ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/vscode-remote-release] Can not open vscod.dev in web browser (Issue #8871)

EXTERNAL


Interesting - it sounds like there's something specific with your browser or machine setup, since https://vscode.dev/ should load no problem (it just loaded for me).

  *   Are you behind any sort of proxy or firewall?
  *   Related ^, do you have trouble/limitations accessing any other sorts of websites?
  *   Does clearing cookies and trying https://vscode.dev/ again help?

-

**Comment by bamurtaugh** [comment]
Are there any errors in the Dev Tools (as that's what the original error recommends reviewing)?

**Comment by jcheynet** [comment]
vscode.dev/:1  Refused to load the stylesheet 'https://gateway.zscalertwo.net/auD?origurl=https%3A%2F%2Fmain%2evscode%2dcdn%2enet%2fstable%2f6c3e3dba23e8fadc360aed75ce363ba185c49794%2fout%2fvs%2fworkbench%2fworkbench%2eweb%2emain%2ecss&wexps=1&_ordtok=HKW3WVLhZ7436PZmTRS6T5qRJh' because it violates the following Content Security Policy directive: "style-src 'self' https://*.vscode-cdn.net http://localhost:* 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

So there is something that is blocked by the policies of our zscaler


De : Brigit Murtaugh ***@***.***>
Envoyé : mercredi 30 août 2023 18:14
À : microsoft/vscode-remote-release ***@***.***>
Cc : CHEYNET Joseph ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/vscode-remote-release] Can not open vscod.dev in web browser (Issue #8871)

EXTERNAL


Are there any errors in the Dev Tools (as that's what the original error recommends reviewing)?

-

**Comment by bamurtaugh** [comment]
No, we haven't changed anything on the vscode.dev side of things. Glad to hear it is working now!

**Comment by jcheynet** [comment]
Yes that is strange


De : Brigit Murtaugh ***@***.***>
Envoyé : mercredi 30 août 2023 18:32
À : microsoft/vscode-remote-release ***@***.***>
Cc : CHEYNET Joseph ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/vscode-remote-release] Can not open vscod.dev in web browser (Issue #8871)

EXTERNAL


No, we haven't changed anything on the vscode.dev side of things. Glad to hear it is working now!

-
