### ISSUE TITLE
How can i prepare the offline server on ssh server

### ISSUE THREAD

**Issue by gabrielpondc** [microsoft/vscode-remote-release#8872]
My company network can not connect to public network but we have a lot of different environment. I only know that the link for download linux 86/64  is ttps://update.code.visualstudio.com/commit:$COMMIT_ID$/server-linux-x64/stable what if the environment is linux arm64 or windows  or Mac arm how can i replace the server-linux-x64 for these environment

**Comment by bamurtaugh** [comment]
Thank you for filing. I believe this would be covered by some combination of https://github.com/microsoft/vscode-remote-release/issues/1242, https://github.com/microsoft/vscode-remote-release/issues/1802, and https://github.com/microsoft/vscode-remote-release/issues/1399. If you believe this is a separate request, please just let me know, thanks!
