### ISSUE TITLE
Connection to container on remote host stucks

### ISSUE THREAD

**Issue by zzasdf** [microsoft/vscode-remote-release#8874]
I'm trying to connect to a running container on a remote host. The host is in a private network, I use a VPN to connect to it. My vscode can connect to the host, but when I trying to attach to the container, it stucks, and the output is like this
![1692861090625](https://github.com/microsoft/vscode-remote-release/assets/68544676/6242a0a0-bb64-4f56-899b-f18ed0532f83)

I can run the these commands without any problem in powershell.
My ssh config looks like these:
```yaml
Host debug001
  HostName ip_for_jump_server
  Port 2222
  User id_for_jump_server@id_for_host@ip_for_host
```
What could be the reason of the stucking?

**Comment by chrmarti** [comment]
Does `ssh debug001 /bin/sh` work in a terminal? Does it ask for credentials or anything?

**Comment by zzasdf** [comment]
it turns out to be a problem related to the jump server software used by my company, [jumpserver](https://github.com/jumpserver/jumpserver/issues/8363), there is no more problem after switching to normal ssh
