### ISSUE TITLE
remote: support diff with reading from stdin

### ISSUE THREAD

**Issue by NightWing1998** [microsoft/vscode-remote-release#8876]
When running VS Code in dev container, there is an irregularity in how server code cli is detecting files to read from stdin. From the logs attached, you can see that for the first command that code cli did not detect a file has to read from stdin but it worked in the second case. I also tried `code -d file.go -` but that also has the same outcome. I want the cli to read the dry run output from my formatter and display the diff to me but it fails to read the output from stdin

- VSCode Version: 1.81.1
- Local OS Version: Ubuntu 22.04 arm64
- Remote OS Version: MacOS  13
- Remote Extension/Connection Type: Containers

- Logs:

```
➜ ~/root/project $ golines -m 100 --chain-split-dots --shorten-comments file.go | code --verbose -d - file.go
{
  "type": "open",
  "fileURIs": [
    "file:///root/project/file.go"
  ],
  "folderURIs": [],
  "diffMode": true,
  "mergeMode": false,
  "addMode": false,
  "gotoLineMode": false,
  "forceReuseWindow": false,
  "forceNewWindow": false
}
➜ ~/root/project $ golines -m 100 --chain-split-dots --shorten-comments file.go | code --verbose -d -
Running "locale charmap" to detect terminal encoding...
Detected raw terminal encoding: UTF-8

Reading from stdin via: /tmp/code-stdin-vda
Marker file for --wait created: /tmp/dxQQ9wmR
{
  "type": "open",
  "fileURIs": [
    "file:///tmp/code-stdin-vda"
  ],
  "folderURIs": [],
  "diffMode": true,
  "mergeMode": false,
  "addMode": false,
  "gotoLineMode": false,
  "forceReuseWindow": false,
  "forceNewWindow": false,
  "waitMarkerFilePath": "/tmp/dxQQ9wmR"
}
^C
root ➜ ~/root/project (ftr) $ code --version
1.81.1
6c3e3dba23e8fadc360aed75ce363ba185c49794
arm64
```

Steps to Reproduce:

1. Open a file with vscode server CLI where one has to be read from a file vs one has to be read from stdin
2. `code` does not detect/process the arg to read from stdin

Does this issue occur when you try this locally?: No. In local version of VS Code, the cli is reading both files (stdin and local)
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by aeschli** [comment]
Reading from stdin is only activated when there are no input files or folder
