### ISSUE TITLE
Command 'Remote-SSH: Connect to Host...' resulted in an error.

### ISSUE THREAD

**Issue by rbavery** [microsoft/vscode-remote-release#888]
Issue Type: <b>Bug</b>

I open VSCODE, open the command pallette, and attempt the above command and get the above error message with no other details. Not sure where to find a more descriptive traceback.

![Selection_531](https://user-images.githubusercontent.com/22258697/60623917-ceb3f200-9d98-11e9-947b-5b7cd4c48ddd.png)

Extension version: 0.44.0
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 4.15.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.08GB (0.21GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Can you open the developer tools (under Help menu) to see whether there is a full error message?

**Comment by rbavery** [comment]
This seems to have fixed itself and I can now attempt to connect. I'm making another issue for a new error

**Comment by dsyer** [comment]
I'm getting the same error. No idea what is going on and the developer tools console has no new information (except the line number of the log statement that alerted the error). I could open another issue? Or can someone re-open this one?
