### ISSUE TITLE
Unclear flow for GH auth vs tunnels listed in Remote Explorer

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-remote-release#8887]
Type: <b>Bug</b>

I could not find a way to connect to the tunnel from my client machine. The docs say that tunnels appear in Remote Explorer view, but Tunnels wasn't even listed (https://code.visualstudio.com/docs/remote/tunnels#_remote-tunnels-extension).

Eventually I picked `Remote-Tunnels: Connect to Tunnel...` and triggered the GH auth for Tunnels. This got my remote machine to show up.

It should be more straightforward to auth tunnels with the right account on the client, so the existing tunnels show up. At least Tunnels should always be listed in Remote Explorer.

Extension version: 1.5.2023082209
VS Code version: Code - Insiders 1.82.0-insider (083fca132543aa91a7e1de2dc23857d70ea56dd3, 2023-08-25T05:34:47.246Z)
OS version: Darwin x64 22.6.0
Modes:
Connection to 'tunnel+z' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (26.24GB free)|
|Process Argv|--log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|

Connection to 'tunnel+z' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
7ij38806:30687742
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
welcomedialogc:30812479
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingc:30808720
asynctok:30821568
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonmhint1:30815193
dsvsc015:30821418

```

</details>

**Comment by connor4312** [comment]
I'm not able to reproduce this, this is what I see with a fresh user-data-dir and extensions-dir

<img width="320" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/2230985/c6aea7f5-68c9-4437-8ca4-45a29ab0f89d">
