### ISSUE TITLE
Turn off Remote Tunnel Access is a noop

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-remote-release#8888]
Type: <b>Bug</b>

1. Click `"Turn off Remote Tunnel Access"` in remote tunnel menu
2. Confirmation dialog `"Do you want to turn off ...? This will also stop the service ..."` - Yes
3. Nothing happens, Remote Runnel is still turned on.

Extension version: 1.5.2023082209
VS Code version: Code - Insiders 1.82.0-insider (083fca132543aa91a7e1de2dc23857d70ea56dd3, 2023-08-25T05:33:34.878Z)
OS version: Windows_NT x64 10.0.23531
Modes:
Remote OS version: Linux x64 5.15.90.4-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.90.4-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700KF (20 x 3610)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (13.37GB free)|
|Process Argv|--log trace --crash-reporter-id a92d7478-ec86-40ff-a269-5f3ad9856be9|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.4-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700KF (20 x 3609)|
|Memory (System)|15.54GB (13.48GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.4-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700KF (20 x 3609)|
|Memory (System)|15.54GB (13.48GB free)|
|VM|0%|
</details>

**Comment by connor4312** [comment]
I don't reproduce this. What's the log of the Remote Tunnel Service output? How was the tunnel initially started?

**Comment by digitarald** [comment]
@connor4312 I checked but not seen any logs for the tunnel service.

**Comment by connor4312** [comment]
Hm, there should always be output there, even if you never interact with it, because it'll check to see if there's another running tunnel on boot that it should use to reflect the status

<img width="559" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/2230985/173e6688-7a95-41e6-a4f6-74ea42c08ff9">
