### ISSUE TITLE
Test: Help to install Docker inside WSL

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#8891]
Refs: https://github.com/microsoft/vscode-remote-release/issues/8641

- [x] windows @connor4312
- [x] windows @hediet
- [x] windows @joyceerhl

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%238891%0A%0A&assignees=chrmarti)

---

- Uninstall WSL if you have it already installed or create a VM without WSL (e.g., with an `osonly` image on http://devbox.microsoft.com).
- Uninstall Docker if you have it already installed.
- Install the Dev Containers extension 0.307.0-pre-release or later.
- Run a Dev Containers command that requires Docker (e.g., reopen folder in container, new dev container).
- Verify you are offered to install Docker in WSL.
- Installing Docker in WSL works without user interaction.
- When done retry the command that requires Docker and verify it now works.

**Comment by joyceerhl** [comment]
I can't get the last step to work with either a Dev Box or my local machine
