### ISSUE TITLE
Test restoring of auto-forwarded ports

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#8892]
Refs: https://github.com/microsoft/vscode-remote-release/issues/8638

- [x] ssh @gregvanl
- [x] dev container @hediet
- [x] anyOS @ulugbekna (Codespaces)

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%238892%0A%0A&assignees=alexr00)

---

Setup:
1. Make sure you have `"remote.autoForwardPorts": true`
2. Connect to your remote and open a folder
3. Set `"remote.autoForwardPortsSource": "process"`
4. Reload

Verify process discovered ports:
- On your remote, start a process that listens on a port. For example, you can run `npx http-server -p 5006`.
- Reload
- Verify that the port gets restored and that it's "Origin" is still "Auto forwarded" (for Codespaces, no need to verify the "Origin" as this is a known issue).

Verify output discovered ports:
- Unforward all ports and kill your process that listens on a port.
- Set `"remote.autoForwardPortsSource": "output"`
- Repeat the verification steps for process discovered ports.

**Comment by hediet** [comment]
Ulugbek and me are both stuck on this.

> Don't kill your process from step 3 of the setup

Which process? Are we supposed to start an http server or sth?

> Verify that the port gets restored and that it's "Origin" is still "Auto forwarded" (for Codespaces, no need to verify the "Origin" as this is a known issue).

Which origin?
