### ISSUE TITLE
tunnels and pty host broken in last vscode insiders version ?

### ISSUE THREAD

**Issue by nh-37rtm** [microsoft/vscode-remote-release#8895]
Type: <b>Bug</b>

Hi!

with the last vscode insiders update (look at the report for the versions details):

i connect to my manually installed (and at a lower insider version) vscode service on the remote host
the remote server is online in the global remote dev list.
it suggest me to update the server, 
the update seems to work
vscode is "attached" but when i open a terminal i have a "pty host" tag (to the right from the remote server name)
telling : "The connection to the terminal's pty host is unresponsive, terminals may stop working..."
the terminal never open

Extension version: 1.4.3
VS Code version: Code - Insiders 1.82.0-insider (f7973f357e7c316a88e8817886f41a843021fe74, 2023-08-28T05:35:52.131Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.108-1-pve
Remote OS version: Linux x64 5.15.108-1-pve

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|47.71GB (36.55GB free)|
|Process Argv|--crash-reporter-id 867eb1a4-1682-416d-a6a1-638c367dec11|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|haproxy02|
|OS|Linux x64 5.15.108-1-pve|
|CPUs|Intel(R) Xeon(R) CPU D-1520 @ 2.20GHz (2 x 2499)|
|Memory (System)|0.50GB (0.18GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|haproxy01|
|OS|Linux x64 5.15.108-1-pve|
|CPUs|Intel(R) Xeon(R) CPU D-1520 @ 2.20GHz (2 x 2499)|
|Memory (System)|0.50GB (0.33GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
showlangstatbar:30737417
962ge761:30823813
57b77579:30687741
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonlinttype:30823781
pythonmpsinfo:30815194
dsvsc015:30821418

```

</details>

**Comment by roblourens** [comment]
Is this still an issue?
