### ISSUE TITLE
Unable to launch ssh on window 7

### ISSUE THREAD

**Issue by fenggc** [microsoft/vscode-remote-release#890]
Issue Type: <b>Bug</b>

I'm using windows 7, and have installed git as well, but, it seems that VSC alway try to find ssh on dedicated location, where ssh cannot be found.
So, is it possible to self-define the location to help VSC find the ssh client?

Extension version: 0.44.0
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:11:51.716Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310M CPU @ 2.70GHz (4 x 2693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by roblourens** [comment]
It looks for ssh on your path and in some common locations, but if it can't find it, there is a setting, `remote.SSH.path`, try setting that.

**Comment by fenggc** [comment]
I can execute SSH on window cmd.exe, and I can't find the settings `remote.SSH.path` you mentioned. 

The error is as followed:

The terminal process command 'cmd.exe /c (type "C:\Users\fenggc\AppData\Local\Temp\vscode-linux-multi-line-command-158.sh" | C:\windows\Sysnative\OpenSSH\ssh.exe  "158" bash) & exit /b 0' failed to launch (exit code: 255)

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/60682089-c87c4f00-9e46-11e9-87ac-bc1d3c61d5af.png)
