### ISSUE TITLE
[Remote-SSH Bug]: VSCode does not record logins/logouts to utmp

### ISSUE THREAD

**Issue by prolificpandas** [microsoft/vscode-remote-release#8901]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

An entry should exist in the host's wtmp database, that looks something like 

` username    pts/1        VSCodeSSH     Tue Aug 29 15:28 - 15:40  (00:11)`

when a user enters and exits a VSCode Remote-SSH session.

### Steps To Reproduce

1. Access a host with VSCode remote-SSH
2. run `last -f /var/log/wtmp` to verify no record exists

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

### Anything else?

[utempter](https://www.unix.com/man-page/suse/8/utempter) is a helpful library for updating utmp/wtmp as an unprivileged user.

**Comment by roblourens** [comment]
I would say that this is the job of ssh or some configuration of the ssh server. We don't really have a concept of "entering and exiting" a session beyond opening and closing an ssh connection
