### ISSUE TITLE
kubernates plugin bug: vscode 1.81.0 Failed to connect to the remote extension host server (Error: No remote extension installed to resolve kubernetes)

### ISSUE THREAD

**Issue by graphenn** [microsoft/vscode-remote-release#8909]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.81.0
- OS Version: Win11

Steps to Reproduce:

1. In ~/.kube/config, config a context with @ inside: admin@kubernetes
2. Attach to k8s dev container

This issue seems duplicated with closed issue microsoft/vscode#187351 but still happen at recent release.

**Comment by qihao-plus** [comment]
same still as above

**Comment by peterbom** [comment]
Hi @chrmarti: Have there been any developments or updates on this? We believe that this might be the cause of [an issue](
https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1199)
we've encountered in our Kubernetes extension.

**Comment by graphenn** [comment]
still not fixed at 1.86.2

**Comment by graphenn** [comment]
because there is another [issue](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1199) track it, close this one

**Comment by chrmarti** [comment]
Sorry for the delay, https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1199#issuecomment-1793919624 makes sense. `@` has become a special character in the remote URI's authority. I'll encode the information to avoid the issue.

**Comment by chrmarti** [comment]
Fix is available in Dev Containers 0.351.0-pre-release.

@graphenn Could you give that a try and let me know if it works?

**Comment by graphenn** [comment]
yes, it is fixed now

**Comment by TylerLeonhardt** [comment]
marking as verified thanks to @graphenn 👍
