### ISSUE TITLE
Detail error when trying to open folder in container

### ISSUE THREAD

**Issue by gustavodeon** [microsoft/vscode-remote-release#8913]
## Suggestion

When trying to open the active folder inside a container, if something goes wrong, display a descriptive message, instead of the current alert: 
![Captura de tela de 2023-09-04 14-44-42](https://github.com/microsoft/vscode-remote-release/assets/21964050/cecd1339-29d1-4566-92b7-73a9b8dbb961)

## How it happened

While trying to configure a dev container config, i accidentally saved the dockerfile all in lowercase, and vscode wasn't able to initiate the remote container because it was looking for a 'Dockerfile'.
The only way i was able to find the issue was going to the log files and find the issue under the remote containers log file

**Comment by bamurtaugh** [comment]
Thanks for filing!

@chrmarti do we have more detailed info that we'd be able to surface in a dialogue? Or is this dialogue surfaced for a variety of potential reasons, which makes it a bit more challenging?

**Comment by chrmarti** [comment]
It should open the log terminal.

Summarizing errors in the dialog is difficult, we are doing this only for the most often occurring ones that we can somewhat reliably detect. (E.g., when the Docker daemon is not running.)

**Comment by gustavodeon** [comment]
Thanks for the reply!

For me at least it is not opening the log terminal, all it does after displaying the message is display the option to open the web documentation for debugging dev containers.

[Error happening](https://github.com/microsoft/vscode-remote-release/assets/21964050/3e9a03c3-9430-4b6e-a216-373f42b7062f)

Actually, another weird behavior is, after the first error, it doesn't display anything else for any further attempts.
