### ISSUE TITLE
Can't launch devcontainer in a remote SSH server

### ISSUE THREAD

**Issue by delucca** [microsoft/vscode-remote-release#8914]
- VSCode Version: 1.81.1
- Local OS Version: macOS Ventura 13.5
- Remote OS Version: Windows 11 Pro
- Remote Extension/Connection Type: SSH

- Logs:
```
[2515 ms] Dev Containers 0.304.0 in VS Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794).
[2514 ms] Start: Run: ssh 10.147.18.141 /bin/sh
[2521 ms] Start: Run in host: id -un
```

Steps to Reproduce:

1. Setup VSCode on the macOS (local)
2. Setup the Docker installaion on the Windows remote server
3. Setup the SSH connection (I don't have anything on any of the SSH configs, only `authorized_keys` on Windows)
4. Launch the remote connection (works) to open a folder that contains a devcontainer
5. Installs the devcontainer extension (I've tried both installing the extension locally, as well as remotely)
6. Try running `Open in container` commands

For some reason it seems it hangs on the last command (`id -un`). I've already tried removing the `.vscode-server` folder from the remote host, and I've already tried connecting on SSH both with password, as well as a passkey (neither work)

The same devcontainer works as expected if I run it locally

**Comment by chrmarti** [comment]
Please check if this is still an issue with the latest versions.
