### ISSUE TITLE
PHP executable not valid

### ISSUE THREAD

**Issue by florianPopulaer** [microsoft/vscode-remote-release#892]
Issue Type: <b>Bug</b>

While in remote-ssh the local php executable file to validate php seems not to be valid. So validation is not working. In local development, there is no problem with the exact same settings.

Extension version: 0.44.0
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.15.0-36-generic

**Comment by roblourens** [comment]
Do you have `php.validate.executablePath` set in remote settings? You will need it set in remote settings, not just user settings.

**Comment by florianPopulaer** [comment]
I cannot find such a setting. Where do I have to look for it?

**Comment by egamma** [comment]
@florianPopulaer the proper way to do this is:
- open the user settings
- switch to remote tab (see screenshot)
- define the path where it is on the SSH box.

![image](https://user-images.githubusercontent.com/172399/60757230-299f5080-a008-11e9-9b6d-1ae7d3052575.png)

There was an issue in that the scope of the `php.validate.executablePath` was not scoped properly. This is fixed now and will be available in the Monday insider build.
