### ISSUE TITLE
vscode remote ssh extension

### ISSUE THREAD

**Issue by zxy-coder** [microsoft/vscode-remote-release#8921]
Because the pc in my company couldn't connect Internet, I need to install remote ssh offline.Outside my vscode edition is 1.65.2.But I can't get history edition of remote ssh fitting my vscode.Can anyone help me?

**Comment by osksa** [comment]
I had a similar issue, the download link only gives the 1.106* version vsix, which is a pre-release, and that does not work to install with the latest vs code version as of now, which is 1.81.1. In my case, I could install 1.81.1 on an internet connected machine, install the remote ssh extension using vscode, and then find the version of the latest stable release, which was 0.102. Then I used the link provided in the version history, like 
 https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-ssh/0.106.2023090115/vspackage
 And changed the URL to be 0.102, like so:
 https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-ssh/0.102.0/vspackage
And this way I could get the release version of the vsix for the extension which works with my version of visual studio code. 

If any devs are reading this: I think that clicking the download link on the extension homepage should give latest STABLE/release version NOT pre-release version as is the case now.

**Comment by zxy-coder** [comment]
> I had a similar issue, the download link only gives the 1.106* version vsix, which is a pre-release, and that does not work to install with the latest vs code version as of now, which is 1.81.1. In my case, I could install 1.81.1 on an internet connected machine, install the remote ssh extension using vscode, and then find the version of the latest stable release, which was 0.102. Then I used the link provided in the version history, like https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-ssh/0.106.2023090115/vspackage And changed the URL to be 0.102, like so: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-ssh/0.102.0/vspackage And this way I could get the release version of the vsix for the extension which works with my version of visual studio code.
> 
> If any devs are reading this: I think that clicking the download link on the extension homepage should give latest STABLE/release version NOT pre-release version as is the case now.

Thank you!But how can I get  the info of history edition.I just find I can download 102, how can I get other edition?

**Comment by osksa** [comment]
You need to find out which version of remote ssh fits your vscode version. One way would be to install the same version you have offline in an online computer, install the extension from within vscode and look at the version. Then, if you edit the link I published above, if you are lucky they still host the version you need.

**Comment by bamurtaugh** [comment]
Sounds like this issue is now resolved, so closing.
