### ISSUE TITLE
[Remote-SSH Bug]: Download links on web site points to pre-release version

### ISSUE THREAD

**Issue by osksa** [microsoft/vscode-remote-release#8927]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

I expect to be able to download the Release version from the extension website. When clicking "Download extension" now, I get the pre-release version which will not install on my vscode 1.81.1, which is latest stable version of vscode as of writing. If I install the extension in an online environment, I get 0.102.0, which works fine. The download link on the extension website gives me 0.106.2023081615 which seems to be a pre-release version. 

I need to get latest release version to be able to install the extension in an offline environment. 

### Steps To Reproduce

1. Go to https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh
2. Click "Download Extension"

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by joshspicer** [comment]
That seems to be a quirk of how the marketplace website works and it not something controlled by this extension.  To get a specific version, you could perhaps install it with VS Code and then navigate on disk to where it has downloaded?
