### ISSUE TITLE
Remote ssh can now work when update to vscode 1.82.0 and Remode-SSH v0.106.1

### ISSUE THREAD

**Issue by cxk99** [microsoft/vscode-remote-release#8928]
![image](https://github.com/microsoft/vscode-remote-release/assets/32592877/4edd8f98-9e54-4550-94f6-19db48a80b90)
 
Downloading VS Code Server...    is never successful.
In the server (Cent OS 7.9), the directory "~/.vscode-server/cli/servers/Stable-8b617bd08fd9e3fc94d14adb8d358b56e3f72314.staging"  is always empty.

**Comment by hlwang1124** [comment]
same issue

**Comment by ladyrick** [comment]
same issue. I think you can put a "[P0 FATAL]" label in front of this issue title.

**Comment by yyh230501** [comment]
same issue

**Comment by Jangzi** [comment]
same issue

**Comment by jianse** [comment]
same issue. but a temporary solution here

```console
$ commit_id="8b617bd08fd9e3fc94d14adb8d358b56e3f72314"
$ wget https://vscode.cdn.azure.cn/stable/${commit_id}/vscode-server-linux-x64.tar.gz
$ mkdir -p "~/.vscode-server/cli/servers/Stable-${commit_id}/server"
$ tar xf vscode-server-linux-x64.tar.gz --strip 1 -C "~/.vscode-server/cli/servers/Stable-${commit_id}/server"
```

The `commit_id` is vscode's commit id you can get it form vscode's menu bar -> help -> about.

If you are connecting to an isolated (no Internet connection) system. You need to execute the `wget` command on an Internet-connected system. Then upload `vscode-server-linux-x64.tar.gz` to the system and execte rest command on the remote host.

**Comment by cailloumajor** [comment]
Same issue, @jianse workaround works for me, thanks a lot!

**Comment by liyufan** [comment]
#8926

**Comment by SSK015** [comment]
same issue! It is strange that only one of my remote servers do not work, while the other work normally.

**Comment by SSK015** [comment]
> ```
> mkdir -p "~/.vscode-server/cli/servers/Stable-${commit_id}/server"
> ```

Thanks! It works for me!

**Comment by luguanyu1234** [comment]
same issue ,    not  connection fail  after upgrade to release v0.106.2. 
I try to delete all  ~/.vscod-server files, but not work

**Comment by sayajin101** [comment]
Same issue :(

**Comment by yanhui09** [comment]
Same issue :(
@sayajin101 solution works for me. ;)

**Comment by bamurtaugh** [comment]
I think we can close as resolved from https://github.com/microsoft/vscode-remote-release/issues/8926, but please let me know if folks are still experiencing this. Thanks!
