### ISSUE TITLE
Why i can't sign in host?

### ISSUE THREAD

**Issue by luyahan** [microsoft/vscode-remote-release#893]
remote-ssh@0.44.0
win32 x64
SSH Resolver called for "ssh-remote+153", attempt 1
SSH Resolver called for host: 153
Setting up SSH remote "153"
Using commit id "0f3794b38477eea13fb47fbe15a42798e6129338" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
Install and start server if needed
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 1
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 2
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 3
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 4
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 5
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 6
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 7
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 8
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 9
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 10
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 11
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 12
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
> 
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 13
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 14
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 15
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 16
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 17
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 18
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 19
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 20
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 21
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 22
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 23
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 24
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 25
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 26
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 27
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 28
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 29
> 
> Installation already in progress...
> 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
> 
"install" terminal command done
Received install output: 6ada49db-3aa7-43a3-bc38-1a8a85eab87e##24##
Server installation process already in progress - waiting and retrying 30

------

**Comment by luyahan** [comment]
After rm /home/user/.vscode in Host 
Vscide :
Installing to /home/luyahan/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338...
Downloading with wget
![image](https://user-images.githubusercontent.com/22358871/60648354-5de10880-9e72-11e9-9597-0015f104084f.png)

**Comment by luyahan** [comment]
I find reason: thr remote host can't weget vscode-server-linux-x64
https://stackoverflow.com/questions/56718453/ssh-with-vscode-without-internet

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/15
