### ISSUE TITLE
Cannot change local address port in SSH

### ISSUE THREAD

**Issue by mrgleba** [microsoft/vscode-remote-release#8933]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

After upgrading to VSCode 1.82 it is no longer possible
to edit forwarded addres in the forwaderd ports pane

Each forwarded port is redirected to localhost with the same port number.

The option to change forwarded address is gone from the edit menu

### Expected Behavior

Previously there was a menu option to change forwarded address.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by roblourens** [comment]
Can you share a screenshot to make sure we know what you are looking for?

**Comment by mrgleba** [comment]
The option in the image below is missing in 1.82
![image](https://github.com/microsoft/vscode-remote-release/assets/6221849/df02df8b-5732-4b55-99c6-bfd79eacf2c5)
The screen is from 1.81.1

**Comment by alexr00** [comment]
Also https://github.com/microsoft/vscode/issues/192681

**Comment by alexr00** [comment]
I still can't reproduce this somehow. But I think I see how to fix it.

**Comment by alexr00** [comment]
I've been able to reproduce the issue in Insiders and test my fix. The fix will be available in the next VS Code Insiders.

**Comment by alexr00** [comment]
Downgrading from a candidate because this now requires `"remote.SSH.useExecServer": true` to repro.
