### ISSUE TITLE
2fa duo prompt doesn't appear

### ISSUE THREAD

**Issue by kc9qey** [microsoft/vscode-remote-release#8934]
Type: <b>Bug</b>

1. Open ssh remote to a host using 2fa duo (Windows11 client)
2. vscode prompts for password
3. The second prompt never appears and one has to press "details" , then it appears at the top but doesn't say anything about duo ( the mac and linux vscode apps handle this correctly ).  Enter passcode from DUO ( duo push doesn't work, but passcode works...also a difference from the mac/linux vscode).

Extension version: 0.106.1
VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 4.18.0-477.15.1.el8_8.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (20.43GB free)|
|Process Argv|--crash-reporter-id 5610a707-54e8-45ae-a51c-9029aaf56009|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dt-login.delta.ncsa.illinois.edu|
|OS|Linux x64 4.18.0-477.15.1.el8_8.x86_64|
|CPUs|AMD EPYC 7763 64-Core Processor (128 x 2445)|
|Memory (System)|251.60GB (132.79GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015cf:30829746

```

</details>

**Comment by kc9qey** [comment]
This may also be relevant:
The system is not "bare metal" and is managed by an organization, system settings shows "hypervisor detected" along with "Virtualization-based security" enabled for a few things.

**Comment by roblourens** [comment]
Merging to https://github.com/microsoft/vscode-remote-release/issues/9316
