### ISSUE TITLE
ssh connection issue

### ISSUE THREAD

**Issue by mdsaud03** [microsoft/vscode-remote-release#8939]
Type: <b>Bug</b>

i have a issue  in connect with remote ssh when ever i tried to connect with my ssh that will not properly connected also it return the request 

Extension version: 0.102.0
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.42GB (2.03GB free)|
|Process Argv|--crash-reporter-id 3bc6d6bf-63ca-4cfa-b6a0-d2a7461944ac|
|Screen Reader|no|
|VM|40%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
89544117:30613380
vscrp:30673768
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746
pythonfb280951:30830810

```

</details>

**Comment by danielfaust** [comment]
Same here. All my connections to the servers are stuck at "Opening Remote" with "Downloading VS Code Server..."

Version: 1.82.0 (user setup)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by khue3012** [comment]
Same here. Could not connect to my remote server.

**Comment by marco910** [comment]
Same issue here

```
Version: 1.82.0
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Datum: 2023-09-06T22:08:29.670Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
Betriebssystem: Darwin arm64 21.6.0
```

**Comment by sayajin101** [comment]
What worked for me was on the `Remote - SSH` extension clicking on the 'Switch to Pre-Release Version`

**Comment by danielfaust** [comment]
Related: https://github.com/microsoft/vscode-remote-release/issues/8926

That issue mentions the workaround, which is to set the setting `remote.SSH.useExecServer` to `false`, which works in most cases.

**Comment by roblourens** [comment]
This should be addressed now in the latest stable releases, let us know if not
