### ISSUE TITLE
Remote SSH list took so long to refresh.

### ISSUE THREAD

**Issue by KilinW** [microsoft/vscode-remote-release#8940]
Type: <b>Bug</b>

I'm not really sure how to reproduce this issue. Because I don't have another computer.
But the thing is loading Remote SSH explorer is taking so long (1min) just to show what were the remote that I can connect. Does anyone know some possibly reason or anything that I should provide for this kind of problem?
Everything else seems to be fine.

Extension version: 0.105.1
VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:18.759Z)
OS version: Linux x64 6.2.0-32-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 4418)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 0, 0|
|Memory (System)|31.00GB (28.52GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id fc1d702f-f776-4145-bee9-f8c48b4f2899|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30831757
03d35959:30757346
pythonfmttext:30731395
f8hc8238:30694864
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746
pythonfb280951cf:30830811

```

</details>

**Comment by SunBK201** [comment]
same issue

**Comment by liuliping0315** [comment]
same issue. I have to connect server by "welcome page -- Start -- 'Connect to...' -- 'Connect to Host ...' -- <machine names>".

**Comment by bamurtaugh** [comment]
Thanks all for filing. To double check: what versions of VS Code and the Remote-SSH extension are you using? Does using the latest VS Code Insiders help?

**Comment by SunBK201** [comment]
I found that the reason why it took time was because of "Remote - Tunnels" extension. When I disabled the "Remote - Tunnels" extension, the issue disappeared.

**Comment by bamurtaugh** [comment]
Thanks for taking a closer look!

cc @connor4312 for the Remote-Tunnels aspect

**Comment by connor4312** [comment]
We should refresh (and load) tunnels and ssh asynchronously.

**Comment by KilinW** [comment]
> Thanks all for filing. To double check: what versions of VS Code and the Remote-SSH extension are you using? Does using the latest VS Code Insiders help?
Using VSCode insider doesn't help. But like SunBK201 said. Disabling remote tunnel does make the remote explorer really fast.
