### ISSUE TITLE
WrappedError shown

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#8944]
Got this when connecting while tethered to my phone. Not sure what triggered it, I don't see it in the log

![Image](https://github.com/microsoft/vscode-remote-release/assets/323878/28ca9ece-7034-4bd2-8c1f-7a7818d3c410)

[ssh-log.txt](https://github.com/microsoft/vscode-remote-release/files/12570027/ssh-log.txt)

**Comment by thanthan9794** [comment]
Hi, was it resolved? I have the same error.
