### ISSUE TITLE
Multiple "Downloading vscode server" shown

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#8945]
Not sure what triggered this, the reconnection right after connecting? Same log as https://github.com/microsoft/vscode-remote-release/issues/8944

![Image](https://github.com/microsoft/vscode-remote-release/assets/323878/79f7d2e2-13c4-4246-bebc-ad3ea33b5bd3)

**Comment by connor4312** [comment]
This can happen if the server didn't set up successfully on the first attempt, you get N more notifications.
