### ISSUE TITLE
[Remote-SSH Bug]: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found

### ISSUE THREAD

**Issue by jbrepogmailcom** [microsoft/vscode-remote-release#8952]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### ->

/root/.vscodium-server/bin/13ae69686c4390a9aee7b71b44337eb488319f26/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /root/.vscodium-server/bin/13ae69686c4390a9aee7b71b44337eb488319f26/node)

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

### Anything else?

Suddenly stopped working

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/192685
