### ISSUE TITLE
[Remote-SSH Bug]: no easy way to read the release changelog

### ISSUE THREAD

**Issue by FlorinAndrei** [microsoft/vscode-remote-release#8956]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

A new version of the Remote SSH extension has been released. Where is the changelog? How do I know what new features have been implemented, or what bugs have been fixed?

I've searched the GitHub repository, and the extension tab in VSCode. No luck.

Please add some kind of changelog, somewhere. A good start would be a Releases page on the repo, each release having some notes added to it.

### Expected Behavior

The user should be able to easily find the extension changelog.

### Steps To Reproduce

see above

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
nonexistent, just like the changelog :)
```

</p>
</details>

**Comment by bamurtaugh** [comment]
Thanks for filing. The remote release notes are linked from the VS Code release notes: https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_82.md.
