### ISSUE TITLE
Excessive Abnormal Processes on Remote Host with VSCode Version After 1.81"

### ISSUE THREAD

**Issue by luxixing** [microsoft/vscode-remote-release#8957]
- VSCode Version: 1.82
- Local OS Version: MACOS 13.4 (22F66) M2
- Remote OS Version: Ubuntu 22.04
- Remote Extension/Connection Type:  SSH Server, Remote ssh v0.106.3

- Logs:

Steps to Reproduce:

1. use command  `ps aux| grep "vscode-server" | grep $username`
2. command outputs:
```
/home/$username/.vscode-server/code-8b617bd08fd9e3fc94d14adb8d358b56e3f72314 command-shell --cli-data-dir /home/$username/.vscode-server/cli --on-port --require-token $token
```
I've found that there are a lot of these kinds of outputs on my remote host, around 100 similar outputs, which I believe is very abnormal.

The previous version of VSCode 1.81 didn't have this output.

**Comment by roblourens** [comment]
Sorry for teh slow response. Is this still an issue?
