### ISSUE TITLE
Git not working in remote WSL

### ISSUE THREAD

**Issue by scrossan-crown** [microsoft/vscode-remote-release#896]
- VSCode Version: 1.36.0
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Open VS Code, open remote wsl in new window
2. Add folders to work space

Even though they are git repos and have a .git folder the source control view shows `No source control providers registered`

![image](https://user-images.githubusercontent.com/30405149/60655605-f319d800-9e45-11e9-9185-07db67f30380.png)

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by scrossan-crown** [comment]
Git output
```
Looking for git in: git
Using git 2.22.0 from git
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
```

**Comment by lukechen526** [comment]
I experienced similar issue today: 
* VSCode Version: 1.37.0
* Local OS Version: Windows 10
* Remote OS Version: Ubuntu (only installed distro)
* Remote Extension/Connection Type: WSL 1 

Changes made to files did not get reflected in Git version control in the UI. However, every time I restarted VScode the changes would be reflected (i.e., you can't see any saved changes made since the latest restart).

**Comment by joaomoreno** [comment]
@scrossan-crown 

Can you still reproduce this issue?

**Comment by darkmattercoder** [comment]
Same here. Since the introduction of remote wsl, I never saw any git interaction. I still need to reopen the directory in Windows to make use of it.

**Comment by joaomoreno** [comment]
I'm using remote WSL full time and git works fine.

@darkmattercoder In Remote WSL you must use git inside WSL, not the Windows one.
