### ISSUE TITLE
Root (/) route not shown

### ISSUE THREAD

**Issue by tarutin** [microsoft/vscode-remote-release#8964]
Type: <b>Bug</b>

Root (/) path not shown. Just empty string

<img width="298" alt="Screenshot 2023-09-13 at 03 16 17" src="https://github.com/microsoft/vscode-remote-release/assets/2318079/b51aa446-278c-4f17-91f6-799d335975ba">

 

Extension version: 0.4.1
VS Code version: Code 1.82.1 (Universal) (6509174151d557a81c9d0b5f8a5a1e9274db5585, 2023-09-08T08:49:32.930Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|24.00GB (3.21GB free)|
|Process Argv|--crash-reporter-id 9bd776f9-9745-4d71-b9e0-42dc90828135|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
<img width="298" alt="Screenshot 2023-09-13 at 03 16 17" src="https://github.com/microsoft/vscode-remote-release/assets/2318079/64ebf78d-c23c-4d7e-a8f9-41689173b9a4">

vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
0bi6i642:30835152
a2ce3375:30757347
24365598:30736109
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by roblourens** [comment]
Not sure what you mean

**Comment by tarutin** [comment]
@roblourens When I added the root directory to Remotes. This root is displayed as an empty string (on the screenshot)

**Comment by joshspicer** [comment]
I don't think this will repro any, but if so please feel free to re-open
