### ISSUE TITLE
Unsaved files on a disconnected connection cannot be saved and prevent successful reconnection

### ISSUE THREAD

**Issue by howellzhu** [microsoft/vscode-remote-release#8969]
- VSCode Version: 1.82.1 6509174151d557a81c9d0b5f8a5a1e9274db5585 x64
- Local OS Version: Windows 10 22H2 x64
- Remote OS Version:  Linux mysrv 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 x86_64 x86_64 GNU/Linux
- Remote Extension/Connection Type: Containers

- Logs:

When I have a remote connection disconnection when my project contains an unsaved file on a remote ssh host, then I no longer have the opportunity to save that file to the remote host.

Note that in my vscode settings, autoSave and hotExit are both set to off.

Steps to Reproduce:
1. open vscode on windows and connect to the remote ssh-remote host;
2. open a file for editing, do not save;
3. put windows to sleep;
4. wake up windows;
5. vscode will detect the disconnection and prompt whether to reload windows;
6. click the `reload` button and it will prompt for unsaved files and whether to save them or not;
7. click save, but find that the save fails. The notification dialog box in the bottom right corner prompts

> Failed to save 'main.txt': Unable to write file 'vscode-remote://ssh-remote+mysrv/home/user/study/VscReload/main.txt' (Canceled: Canceled)

and the prompt in the lower left corner is `disconnected from SSH:mysrv`. 
9. Clicking `retry` repeats the previous error;
10. clicking `save as` only saves to local windows;
11. you can only select `discard` or you will never be able to reconnect to the remote ssh host.

I think the reason for this problem is that the relationship since each other is confused.

If you save to the server, you need to reconnect; but before reconnecting, vscode again prompts that it didn't save.

Wouldn't the correct approach be to save in memory before reconnecting, and then after reconnecting, prompt for the file to be forced to be saved (I can see how this would involve the possibility of the remote file being rewritten during the time of disconnection, but at least give the user the option to decide for themselves)

Does this issue occur when you try this locally?: Not Applicable
Does this issue occur when you try this locally and all extensions are disabled?: Not Applicable

**Comment by bpasero** [comment]
I am not sure what the ask is here? If you are disconnected you cannot save to the remote, but we still need to tell you so that you can save your unsaved data to some other place, e.g. locally.

**Comment by Raymvp** [comment]
> * VSCode Version: 1.82.1 6509174151d557a81c9d0b5f8a5a1e9274db5585 x64
> * Local OS Version: Windows 10 22H2 x64
> * Remote OS Version:  Linux mysrv 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 x86_64 x86_64 GNU/Linux
> * Remote Extension/Connection Type: Containers
> 
> * Logs:
> 
> When I have a remote connection disconnection when my project contains an unsaved file on a remote ssh host, then I no longer have the opportunity to save that file to the remote host.
> 
> Note that in my vscode settings, autoSave and hotExit are both set to off.
> 
> Steps to Reproduce:
> 
> 1. open vscode on windows and connect to the remote ssh-remote host;
> 2. open a file for editing, do not save;
> 3. put windows to sleep;
> 4. wake up windows;
> 5. vscode will detect the disconnection and prompt whether to reload windows;
> 6. click the `reload` button and it will prompt for unsaved files and whether to save them or not;
> 7. click save, but find that the save fails. The notification dialog box in the bottom right corner prompts
> 
> > Failed to save 'main.txt': Unable to write file 'vscode-remote://ssh-remote+mysrv/home/user/study/VscReload/main.txt' (Canceled: Canceled)
> 
> and the prompt in the lower left corner is `disconnected from SSH:mysrv`. 9. Clicking `retry` repeats the previous error; 10. clicking `save as` only saves to local windows; 11. you can only select `discard` or you will never be able to reconnect to the remote ssh host.
> 
> I think the reason for this problem is that the relationship since each other is confused.
> 
> If you save to the server, you need to reconnect; but before reconnecting, vscode again prompts that it didn't save.
> 
> Wouldn't the correct approach be to save in memory before reconnecting, and then after reconnecting, prompt for the file to be forced to be saved (I can see how this would involve the possibility of the remote file being rewritten during the time of disconnection, but at least give the user the option to decide for themselves)
> 
> Does this issue occur when you try this locally?: Not Applicable Does this issue occur when you try this locally and all extensions are disabled?: Not Applicable

did you solve this problem? I encounter this problem!
