### ISSUE TITLE
WSL1 `code .` broken with 1.82.1

### ISSUE THREAD

**Issue by NuclearPowerNerd** [microsoft/vscode-remote-release#8976]
Hello,

VScode recently updated to 1.82.1 on my laptop and now `code .` no longer works in WSL1. It does not thrown an error it just doesn't do anything. Before the update it worked no issue. Here is my setup.

* VScode 1.82.1
* WSL Extension Version 0.81.3
* Windows Terminal 1.17.11461.0
* WSL1 running Ubuntu 20.04.3 LTS
* OS is Windows 10 Enterprise Version 22H2

To fix this - I tried opening VSCode in windows, updated the WSL Extension, and then did the reload it suggested. This appeared to do some kinda re-installation but the outcome is still the same. `code .` does not open VSCode. It does nothing. Note that I have another PC with the same WSL1 setup, still on 1.81.1 (and same version of WSL extension), and it works fine.

On my laptop if I do `code . --verbose` I get the following. Then nothing happens.

```
Invoking: cd "/mnt/c/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code" && ELECTRON_RUN_AS_NODE=1 "/mnt/c/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/Code.exe" "resources/app/out/cli.js" "--ms-enable-electron-run-as-node" "--verbose" "--folder-uri=vscode-remote://wsl+Ubuntu/home/USERNAME" "--remote=wsl+Ubuntu"
```
Any help getting this resolved would be appreciated.

**Comment by StoneCut** [comment]
I have the same issues (as does a friend).

```
user@workstation:~$ code .
Installing VS Code Server for x64 (6509174151d557a81c9d0b5f8a5a1e9274db5585)
Downloading: 100%
Unpacking: 100%
Unpacked 1794 files and folders to /home/user/.vscode-server/bin/6509174151d557a81c9d0b5f8a5a1e9274db5585.
user@workstation:~$ code .
user@workstation:~$ echo $?
0
user@workstation:~$ code . --no-sandbox --verbose
Invoking: cd "/mnt/c/Users/stonecut/AppData/Local/Programs/Microsoft VS Code" && ELECTRON_RUN_AS_NODE=1 "/mnt/c/Users/stonecut/AppData/Local/Programs/Microsoft VS Code/Code.exe" "resources/app/out/cli.js" "--ms-enable-electron-run-as-node" "--verbose" "--folder-uri=vscode-remote://wsl+Ubuntu-22.04/home/user" "--remote=wsl+Ubuntu-22.04"
user@workstation:~$ echo $?
0
user@workstation:~$ code . --verbose
Invoking: cd "/mnt/c/Users/stonecut/AppData/Local/Programs/Microsoft VS Code" && ELECTRON_RUN_AS_NODE=1 "/mnt/c/Users/stonecut/AppData/Local/Programs/Microsoft VS Code/Code.exe" "resources/app/out/cli.js" "--ms-enable-electron-run-as-node" "--verbose" "--folder-uri=vscode-remote://wsl+Ubuntu-22.04/home/user" "--remote=wsl+Ubuntu-22.04"
user@workstation:~$ echo $?
0
```

Result: VScode does not start. I can manually launch it from within Windows and remote connect to WSL1, though.

**Comment by aeschli** [comment]
There was a fix for WSL1 in 1.82.2. 
@StoneCut are you saying it works on 1.81.1 but not on 1.81.2? We are talking about WSL1, right?

**Comment by StoneCut** [comment]
@aeschli Works in 1.81.1 but not in 1.82.1 - haven't tested 1.82.2.

And yes. WSL1.

**Comment by aeschli** [comment]
Ah, I meant 1.82.2. Yes, please try 1.82.2, it should have the fix.
