### ISSUE TITLE
Incorrect PATH when accessing remote containers from within remote SSH

### ISSUE THREAD

**Issue by Colonial-Dev** [microsoft/vscode-remote-release#8977]
When accessing a remote container from *within* an existing remote SSH session, the `PATH` environment variable doesn't make the jump, which breaks most of my tooling. I *am* using `podman` instead of  `docker` (more specifically, `podman` managed by Fedora `toolbox`) - but connecting to these containers without the extra SSH step functions as expected.

- VSCode Version: 1.82.0
- Local OS Version: Fedora Silverblue 38.20230912.0 (2023-09-12T01:59:54Z)
- Remote OS Version: Fedora Silverblue 38.20230910.0 (2023-09-10T00:44:30Z)
- Remote Extension/Connection Type: SSH + Containers

- Logs:
[Container Log pastebin](https://pastebin.com/afeWUN0q), highlights below.

It seems to get the `PATH` right at first:
```
[1158 ms] userEnvProbe PATHs:
Probe:     '/var/home/colonial/.cargo/bin:/var/home/colonial/.local/bin:/var/home/colonial/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin'
Container: None
```
But then completely loses all the homedir stuff later:
```
[5835 ms] userEnvProbe PATHs:
Probe:     '/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
Container: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
Merged:    '/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
```

... Which causes all my Rust tooling to completely break. 

The final `PATH` is:

```
⬢[colonial@toolbox FTL]$ echo $PATH
/root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/bin/remote-cli:/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

Steps to Reproduce:

1. Create a `toolbox`/`podman` container on an SSH host. Install something like Rust that requires altering your `PATH`. Accessing this container from the same host using Remote Containers (once you've specified `podman`) should work fine.
2. Access this host from another machine using Remote SSH. 
3. Go to Remote Explorer, switch to the container view and attach to the container you created.
4. Check the value of `PATH` - it'll be missing the extra stuff. Commands like `cargo` (in my case) are considered not found.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by Colonial-Dev** [comment]
Hmm, the plot thickens. Exporting the correct `PATH` isn't a fix since extensions don't pick up on it, but I tried it anyways and got:
```
⬢[colonial@toolbox FTL]$ export PATH=/var/home/colonial/.cargo/bin:/var/home/colonial/.local/bin:/var/home/colonial/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
⬢[colonial@toolbox FTL]$ cargo check
error: rustup could not choose a version of cargo to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
```
Which is... odd.

Doing a little more digging, and it seems my homedir is set to `/root` (inside the container!)
```
⬢[colonial@toolbox FTL]$ cd ~
⬢[colonial@toolbox ~]$ ls
anaconda-ks.cfg  anaconda-post-nochroot.log  anaconda-post.log  buildinfo  original-ks.cfg
⬢[colonial@toolbox ~]$ pwd
/root
⬢[colonial@toolbox ~]$ 
```
Pretty devious, considering the `$` instead of `#` and the fact that it defaults to the correct project directory. It's frankly a mystery to me why this is all happening *only* when SSH is thrown into the middle of things.

**Comment by chrmarti** [comment]
The first `userEnvProbe` is for the SSH server, the second is for the container. Podman sets `HOME=/root` on all containers, you might need to unset that.
