### ISSUE TITLE
can't download vscode server 

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-remote-release#898]
Currently I can't download vscode server on vscode 1.36. But I can use command to download vscode server like this and the error as attached.
`curl -kL https://update.code.visualstudio.com/commit:0f3794b38477eea13fb47fbe15a42798e6129338/server-linux-x64/stable --output vscode-server-linux-x64.tar.gz -w %{http_code}`
![23456](https://user-images.githubusercontent.com/39362073/60660337-24b49280-9e8a-11e9-9da0-cee1b8adc08a.PNG)

![12345](https://user-images.githubusercontent.com/39362073/60660286-03ec3d00-9e8a-11e9-86c1-ef84a6c16267.PNG)

**Comment by roblourens** [comment]
Are you behind a proxy? Do you need the http[s]_proxy env vars? They may not be set in the installer environment

**Comment by Lennon925** [comment]
> Are you behind a proxy? Do you need the http[s]_proxy env vars? They may not be set in the installer environment

I have set this on my linux machine following this tips:
https://code.visualstudio.com/docs/remote/troubleshooting#_troubleshooting-hanging-or-failing-connections

**Comment by roblourens** [comment]
So you are behind a proxy? How are you setting those variables? Do they show up in the printenv output in the log?

**Comment by pandyamitesh** [comment]
Try to Add a .wgetrc file to your users home directory 
put this content in .wgetrc

use_proxy=yes
http_proxy=<Your proxy server ip and port>
https_proxy=<Your proxy server ip and port>

**Comment by pandyamitesh** [comment]
Try to Add a .wgetrc file to your users home directory 
put this content in .wgetrc
use_proxy=yes
http_proxy=Your proxy server ip and port
https_proxy=Your proxy server ip and port


If this is going in Infinteloop of crash then try to kill node process

**Comment by roblourens** [comment]
I can't reproduce that @pandyamitesh, are you using the latest version of the ssh extension? If so then please open a new issue with more details

**Comment by pandyamitesh** [comment]
Thanks @roblourens  I took the update the on July 12 and that fixed issue for me.

**Comment by Lennon925** [comment]
> Try to Add a .wgetrc file to your users home directory
> put this content in .wgetrc
> use_proxy=yes
> http_proxy=Your proxy server ip and port
> https_proxy=Your proxy server ip and port
> 
> If this is going in Infinteloop of crash then try to kill node process

it works for my and thanks very much
