### ISSUE TITLE
Can't connect to local devcontainer from Remote Explorer panel

### ISSUE THREAD

**Issue by iemejia** [microsoft/vscode-remote-release#8982]
I tried to connect to an existing local devcontainer from the Remote Explorer panel and the option was not there. I was expecting to find an option or an arrow button like the one that exists for SSH connections but the only way to connect to the container that I found was through the project and then open in container. This is a bit more cumbersome and less intuitive, in particular compared with the SSH experience.

![devcontainers-not-evident-way-to-connect-to-a-devcontainer](https://github.com/microsoft/vscode-remote-release/assets/79476/ce0d0318-b4d4-4876-a814-31e29bb3d546)

VSCode Version: 1.12.1
Local OS Version: Ubuntu 22.04
Remote OS Version: Devcontainers Universal Image
Remote Extension/Connection Type: Containers

- Logs:

Steps to Reproduce:

1. Create a local devcontainer
2. Go to the Remote Explorer left panel and try to connect to the devcontainer

Curiously this works as I would expect when I access the devcontainer throush a SSH connection, in that case just clicking in the arrow gets me into the devcontainer.
![devcontainers-local-vs-remote-experience](https://github.com/microsoft/vscode-remote-release/assets/79476/7ec39e99-200d-42f4-99f7-97dbd68f2e3a)

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by bamurtaugh** [comment]
Thanks for filing. You should be able to connect via the Remote Explorer. I see one dev container in your Remote Explorer in the videos - did the other dev container that's missing have any notable differences (i.e. it was created or connected to in a different way to begin with)?
