### ISSUE TITLE
[Remote-SSH Bug]: SSH agent not forwarded

### ISSUE THREAD

**Issue by albireox** [microsoft/vscode-remote-release#8984]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [x] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

Since version `v0.102.0` the local SSH agent is not forwarded correctly to the remote system. It is difficult to pinpoint the exact behaviour, but it seems that when you install a new version of the remote extension, and it downloads and starts a new server, the SSH agent is properly forwarded (you can do `ssh-add -l` in the remote Linux machine and the local keys are there) but once you close VSCode or the window with the SSH connection and open it again, the agent is not forwarded.

Everything else seems to work fine, including the port forwarding, but the SSH agent is not there, which means that working with remote GitHub repositories is very painful if you don't have local SSH keys on that machine.

I think I've tried most versions, stable and insiders, since `v0.102.0` and with none of them I can get a stable behaviour, although in some (random?) cases the SSH agent is forwarded for a few times before it stops working.

### Remote-SSH Log

I can provide a log if there's a specific test that would be useful.

**Comment by albireox** [comment]
Any updates on this? This seems to keep happening with newer versions of the extension.

**Comment by albireox** [comment]
Another gentle ping on this, as it's still a recurring issue.

**Comment by ehoogeveen-medweb** [comment]
Could you try closing the terminal (with the trash can icon) and reopening it? We recently started using agent forwarding, and closing and reopening the terminal fixes it for us (even when closing and reopening VSCode or running `Developer: Reload Window` doesn't).

I'm experimenting with disabling persistent terminal sessions (`"terminal.integrated.enablePersistentSessions": false`) to see if that fixes it.

**Comment by albireox** [comment]
Unfortunately that doesn't seem to work for me. Once I start getting

```
>>> ssh-add -l
Error connecting to agent: No such file or directory
```

closing the terminal and opening a new one doesn't change that.

I have noticed though that every time the remote server gets update, it works in that session. And one can force it to redownload. For example if in the  `remote-ssh` output I see

```
[16:47:22.296] [server] Checking /home/gallegoj/.vscode-server-insiders/cli/servers/Insiders-8762127fc97b8aaae5f3a0dd6a6d853d9a1b7574/log.txt and /home/gallegoj/.vscode-server-insiders/cli/servers/Insiders-8762127fc97b8aaae5f3a0dd6a6d853d9a1b7574/pid.txt for a running server...
```

and I remove `/home/gallegoj/.vscode-server-insiders/cli/servers/Insiders-8762127fc97b8aaae5f3a0dd6a6d853d9a1b7574` and reload the window, it will redownload the server and it the agent will be properly forwarded during that session, but fail again once I close and reopen the remote session. Of course, that's not a great solution anyway.

I'll test the `"terminal.integrated.enablePersistentSessions": false` option, but having the terminal only work is not good enough. If, for example, the integrated git extension cannot use the agent while on remote a lot of functionality becomes unavailable.

**Comment by albireox** [comment]
This seems to be a duplicate to microsoft/vscode#168202 so closing.

For reverence it seems that disabling `remote.SSH.useExecServer` and deleting `~/.vscode-server-insiders` fixes this for now.
