### ISSUE TITLE
Optimize terminal in web extension.

### ISSUE THREAD

**Issue by LoreBadTime** [microsoft/vscode-remote-release#8986]
Basically it's like web interface its sending every single terminal typed key to the server, this result in delay when typing commands.

The solution could be to check locally specific combinations (like CTRC+C or ENTER) before sending anything to the server, it doesn't fully fix the issue, but it will at least should mitigate better 999 ping when writing commands and should reduce connection usage.

- VSCode Version: live insiders web,live web
- Local OS Version: multiple OS tested
- Remote OS Version: Ubuntu 22.04
- Remote Extension/Connection Type: Tunnel

- Logs:

Steps to Reproduce:

1.Start vscode web and try to connect to a tunnel
2. Use terminal

Does this issue occur when you try this locally?: Not tested 
Does this issue occur when you try this locally and all extensions are disabled?: Not tested

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/135644, also see https://code.visualstudio.com/docs/terminal/advanced#_reducing-remote-input-latency
