### ISSUE TITLE
Window reason: "Crash" -1073741819

### ISSUE THREAD

**Issue by thisiswhereitype** [microsoft/vscode-remote-release#8988]
Type: <b>Bug</b>

At first I thought it was caused by many files in the workspace since updating but it appears when WSL is active.
NB: I have neabled WSL via the dialog but and opened a directory with a single file it is not clear causes the crash.

Extension version: 0.81.3
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.49GB free)|
|Process Argv|--disable-extensions --folder-uri=vscode-remote://wsl+Ubuntu/home/jscott/conda-envs --remote=wsl+Ubuntu --crash-reporter-id a3899707-306e-4780-be26-eb47b1ee921e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (10 x 3599)|
|Memory (System)|13.65GB (12.81GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30835152
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30829745

```

</details>

**Comment by joshspicer** [comment]
I see that folks engaged on this issue on https://github.com/microsoft/vscode/issues/183456 and it sounds like the issue was no longer reproing.  Please definitely create a new issue (and please include your entire log) if you do see it again

**Comment by thisiswhereitype** [comment]
I think they were unrelated but as you suggest I will try a new issue.
