### ISSUE TITLE
switch vscode source control when using dev containers

### ISSUE THREAD

**Issue by aaronzjc** [microsoft/vscode-remote-release#899]
Currently when i open project inside dev containers, vscode source control seems to use Git inside the containers, not my local system. So i think maybe an option to switch vscode source control using local Git ?

I can configure Git  inside containers to work things right, but  in my opinion, containers are temporary, they can be destroyed at anytime. Also, I don't want to add keys in dev container Dockerfile, especially when i need to share my dev environment to others.

Or maybe an option to open terminal outside containers. currently when using dev containers, terminals are opened inside containers too. At the end, I have to open a local terminal to do Git things.

**Comment by Chuxel** [comment]
@aaronzjc A couple of thoughts here:

1. We added a [section on getting your Git credentials into the container](https://code.visualstudio.com/docs/remote/containers#_sharing-git-credentials-with-your-container) without copying them. You can use a volume mount for SSH keys and if you use HTTPS with a credential helper it's actually transparent.
2. If you are manually installing git in your container, note that the postCreateCommand property in devcontainer.json can be used to automate this without modifying your Dockerfile/Compose file.  e.g.`"postCreateCommand": "apt-get update && apt-get install -y git"`

Does that help address your concerns?

**Comment by aaronzjc** [comment]
Yes, thank you very much. it does solve my problems with Git !

Just for consideration, i think there should be someway to open a terminal in my local system when using dev containers . look a situation i met before https://github.com/microsoft/vscode-remote-release/issues/233 , i have to handle it other way. in my opinion, dev containers are really great tools to help developing, but sometimes i may want to use my local system tool chains.

**Comment by egamma** [comment]
@aaronzjc there now is a command to open a local terminal: `Terminal: Create New Integrated Terminal (local)`.

**Comment by aaronzjc** [comment]
@egamma  Yes, that's what i want. Thanks a lot.
