### ISSUE TITLE
[Remote-SSH Bug]: I still hope to solve the compatibility issue with OpenSSH for Windows versions

### ISSUE THREAD

**Issue by etanman** [microsoft/vscode-remote-release#8990]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->
I would appreciate it if you could test this issue. In Win32 OpenSSH, the development engineer has confirmed that this is a compatibility issue.

![1694834256249](https://github.com/microsoft/vscode-remote-release/assets/45775943/1f7c96c1-bfa7-4ed4-b2d2-3325bfdd8b3e)

https://githubfast.com/PowerShell/Win32-OpenSSH/issues/2116

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by roblourens** [comment]
Same response from https://github.com/microsoft/vscode-remote-release/issues/8929#issuecomment-1722117885
