### ISSUE TITLE
[Remote-SSH Bug]: Remote-ssh: Open SSH Configuration FIle... not works

### ISSUE THREAD

**Issue by yzjcloud** [microsoft/vscode-remote-release#8993]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### ->

OS: WIndows 11 Enterprise
Visual Studio Code Version: 1.81.1
Remote-SSH extension: v0.107.2023091215

Issue:
press F1, click "Remote-SSH: Open SSH Configuration File...", received error message: 
Command 'Remote-SSH: Open SSH Configuration FIle...' resulted in an error
command 'opensshremotes.openConfigFile' not found

Tried: 
uninstall the extension/ reinstall the extension, reboot laptop, still same result.

### Expected Behavior

expect can open the window to edit Remote-SSh Configuration File.

### Steps To Reproduce

press F1
select 'Remote-SSH: Open SSH Configuration FIles...'
received same error

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by roblourens** [comment]
Please try updating VS Code to the latest version
