### ISSUE TITLE
Audio in Repo unable to Play in Dev Container

### ISSUE THREAD

**Issue by sinemakinci1** [microsoft/vscode-remote-release#8996]
- VSCode Version: 1.68
- Local OS Version: Windows 11
- Remote OS Version: debian 11
- Remote Extension/Connection Type: Containers/WSL/Server: Container Volume

- Logs:
(SDL message: "That operation is not supported")
(SDL message: "Negative swap interval unsupported in this GL")
(SDL message: "That operation is not supported")
Unable to change VSync state
(SDL message: "That operation is not supported")
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory

Steps to Reproduce:

1. Clone repo in Container Volume from VS Code: https://github.com/sinemakinci1/endless-sky/tree/devcontainer , specifically the devcontainer branch
2. Press Run
3. You should see that log now.

Does this issue occur when you try this locally?: No, occurs only in remote dev container and Codespaces

**Comment by chrmarti** [comment]
This requires some additional setup for the container: https://stackoverflow.com/questions/28985714/run-apps-using-audio-in-a-docker-container

Closing as this is separate from dev containers.
