### ISSUE TITLE
Why not open source vscode-remote-release?

### ISSUE THREAD

**Issue by ByteFlyCoding** [microsoft/vscode-remote-release#8997]
Why not open source vscode-remote-release? The remote system of your create is powerful. I think that is magical. As a primer developer, it is attractive for me that how does it work.

**Comment by bamurtaugh** [comment]
Thank you for filing and for your positive words about remote! There's more information here: https://code.visualstudio.com/docs/remote/faq#_why-arent-the-remote-development-extensions-or-their-components-open-source.
