### ISSUE TITLE
High CPU usage  with Remote WSL while coding in PHP

### ISSUE THREAD

**Issue by stefanoginella** [microsoft/vscode-remote-release#90]
Issue Type: <b>Performance Issue</b>

I have a LAMP development environment in WSL, and sometimes when using the Remote WSL feature with VS Code Insiders and editing a PHP file I have the PHP7.3 and NODE process using almost all of my CPU.

It was not happening before.

Extension version: 0.32.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.89GB (12.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|      Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2401)|
|Memory (System)|23.89GB (12.79GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   114	 25192	code-insiders main
    0	   169	  9324	   gpu-process
    1	    66	 13144	   window (Issue Reporter)
    0	   219	 24124	   window (● setup.php - woptimize.io [WSL] - Visual Studio Code - Insiders)
    0	    69	 12868	     extensionHost
    0	    28	 14196	       electron_node wslDaemon.js 
    0	     5	 25516	         C:\WINDOWS\System32\wsl.exe bash -i -c "./scripts/wslServer.sh 473af338e1bd9ad4d9853933da1cd9d5d9e07dc9 insider .vscode-remote  "
    0	    11	  6604	           console-window-host (Windows internal process)
    0	     5	 15668	           C:\WINDOWS\System32\lxss\wslhost.exe {77081860-9acc-4e28-b8eb-43e4fdcc136f} 456 464 468
    0	    13	 24652	             console-window-host (Windows internal process)
    0	    79	 24708	   shared-process

Remote: WSL
CPU %	Mem MB	   PID	Process
    4	     0	  4935	remote agent
    0	     0	  4948	   extensionHost
    0	     0	  5001	     /home/stefano/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/node /home/stefano/.vscode-remote/extensions/ikappas.phpcs-1.0.5/node_modules/vscode-languageclient/lib/utils/electronForkStart /home/stefano/.vscode-remote/extensions/ikappas.phpcs-1.0.5/server/src/server.js --node-ipc --clientProcessId=4948
    0	     0	  5009	     /home/stefano/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/node /home/stefano/.vscode-remote/extensions/bmewburn.vscode-intelephense-client-1.0.14/node_modules/intelephense/lib/intelephense.js --node-ipc --clientProcessId=4948
    0	     0	  5015	     /home/stefano/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/node /home/stefano/.vscode-remote/extensions/kisstkondoros.vscode-gutter-preview-0.19.0/out/src/server/server.js --node-ipc --clientProcessId=4948
    0	     0	  5041	     PHP Language Server
    0	     0	  4958	   watcherService
    0	     0	  5315	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  5316	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: WSL|    Folder (woptimize.io): 4981 files|      File types: php(2896) js(603) css(320) png(173) mo(154) xml(146)
|                  scss(104) txt(96) gif(90) json(87)
|      Conf files: package.json(3) webpack.config.js(1);
```

</details>

**Comment by Tyriar** [comment]
Normally these sorts of issues are due to the language extension itself. It looks like only the remote agent process is using 4% when you reported this, could you run `code-insiders --status` when the CPU problem happens again to get the process tree then paste it in here to help identify the problem process?

**Comment by tabennett** [comment]
This is happening to me as well. Doesn't seem to be related to any specific PHP language extension I have installed (I removed them all and it still happens). Any PHP workspace I open causes the CPU to ramp up to 60% under the node process that VS code is running under. Switching to a JS (Vue CLI) project and the CPU usage goes back down.

Version:          Code - Insiders 1.36.0-insider (fe0c3e785c22c3ed2d5caa7178488c92d62bdb08, 2019-06-28T12:34:35.956Z)
OS Version:       Windows_NT x64 10.0.18362
CPUs:             Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)
Memory (System):  15.90GB (8.36GB free)
VM:               0%
Screen Reader:    no
Process Argv:     
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  native_gpu_memory_buffers:     disabled_software
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_deferred_display_list:    disabled_off
                  skia_renderer:                 disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    0      103   14604  code-insiders main
    1      131    3356     window (discovery (Workspace) [WSL] - Visual Studio Code - Insiders)
    0       58    7804       extensionHost
    0       32    7192         electron_node wslDaemon.js 
    0        6   11744           C:\WINDOWS\System32\wsl.exe bash -c "'./scripts/wslServer.sh' 'fe0c3e785c22c3ed2d5caa7178488c92d62bdb08' 'insider' '.vscode-server-insiders' 'C:/Users/TABENN~1/AppData/Local/Temp/vscode-remote-wsl/fe0c3e785c22c3ed2d5caa7178488c92d62bdb08/vscode-server-linux-x64.tar.gz'  "
    0        6   13508             C:\WINDOWS\System32\lxss\wslhost.exe {75764515-3231-443d-82ab-b3e97afd6529} 484 492 496
    0       13   12420               console-window-host (Windows internal process)
    0       11   18780             console-window-host (Windows internal process)
    0       81   14992     shared-process
    0       15   18640     electron-crash-reporter
    0      539   20448     gpu-process



Remote:           WSL
OS Version:       Linux x64 4.4.0-18362-Microsoft
CPUs:             Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)
Memory (System):  15.90GB (8.36GB free)
VM:               0%

**Comment by neofelisho** [comment]
Hi,

This is also happening to me. I use Elixir, and install ElixirLS (elixir language server) in the WSL by vscode remote development.

neofelis@NEO-XPS13  /mnt/c/Users/neofe/workspace/personal  code-insiders --status

Version:          Code - Insiders 1.36.0-insider (fe0c3e785c22c3ed2d5caa7178488c92d62bdb08, 2019-06-28T12:34:35.956Z)
OS Version:       Windows_NT x64 10.0.18362
CPUs:             Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)
Memory (System):  15.75GB (4.95GB free)
VM:               0%
Screen Reader:    no
Process Argv:     --folder-uri=vscode-remote://wsl+Ubuntu-18.04/mnt/c/Users/neofe/workspace/xxxpay/xxx-services --remote=wsl+Ubuntu-18.04
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  native_gpu_memory_buffers:     disabled_software
                  oop_rasterization:             disabled_off
                  protected_video_decode:        enabled
                  rasterization:                 enabled
                  skia_deferred_display_list:    disabled_off
                  skia_renderer:                 disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    0       77   10592  code-insiders main
    0      502     804     gpu-process
    0      172    1916     window (slack.ex - xxx-services [WSL: Ubuntu-18.04] - Visual Studio Code - Insiders)
    0       45    2872       extensionHost
    0       25    9272         electron_node wslDaemon.js
    0        5   13812           C:\Windows\System32\wsl.exe -d Ubuntu-18.04 bash -c "'./scripts/wslServer.sh' 'fe0c3e785c22c3ed2d5caa7178488c92d62bdb08' 'insider' '.vscode-server-insiders'
 'C:/Users/neofe/AppData/Local/Temp/vscode-remote-wsl/fe0c3e785c22c3ed2d5caa7178488c92d62bdb08/vscode-server-linux-x64.tar.gz' 4000  "
    0        5    4428             console-window-host (Windows internal process)
    0        5    8604             C:\Windows\System32\lxss\wslhost.exe {07088caa-0544-4eff-a158-300c77da2f1c} 460 468 472
    0        7   14436               console-window-host (Windows internal process)
    0       12    7328     electron-crash-reporter
    0      156   10684     window (changes.ex - xxxpay [WSL: Ubuntu-18.04] - Visual Studio Code - Insiders)
    0       51   17380       extensionHost
    0       29   12276         electron_node wslDaemon.js
    0       59   12492     shared-process



Remote:           WSL: Ubuntu-18.04
OS Version:       Linux x64 4.4.0-18362-Microsoft
CPUs:             Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)
Memory (System):  15.75GB (4.94GB free)
VM:               0%
CPU %   Mem MB     PID  Process
   16        0    2459  remote agent
    0        0    2511     extensionHost
    0        0    2573       /usr/bin/zsh
    0        0    2575       sh /home/neofelis/.vscode-server-insiders/extensions/jakebecker.elixir-ls-0.2.25/elixir-ls-release/language_server.sh
    0        0    2583         /usr/lib/erlang/erts-10.4.2/bin/beam.smp -- -root /usr/lib/erlang -progname erl -- -home /home/neofelis -- -pa /usr/lib/elixir/bin/../lib/eex/ebin /usr/lib/el
ixir/bin/../lib/elixir/ebin /usr/lib/elixir/bin/../lib/ex_unit/ebin /usr/lib/elixir/bin/../lib/iex/ebin /usr/lib/elixir/bin/../lib/logger/ebin /usr/lib/elixir/bin/../lib/mix/ebin -noshell -
s elixir start_cli -extra -e ElixirLS.LanguageServer.CLI.main()
    0        0    2611           erl_child_setup 65536
    0        0    2845     extensionHost
    0        0    2918       sh /home/neofelis/.vscode-server-insiders/extensions/jakebecker.elixir-ls-0.2.25/elixir-ls-release/language_server.sh
    0        0    2925         /usr/lib/erlang/erts-10.4.2/bin/beam.smp -- -root /usr/lib/erlang -progname erl -- -home /home/neofelis -- -pa /usr/lib/elixir/bin/../lib/eex/ebin /usr/lib/el
ixir/bin/../lib/elixir/ebin /usr/lib/elixir/bin/../lib/ex_unit/ebin /usr/lib/elixir/bin/../lib/iex/ebin /usr/lib/elixir/bin/../lib/logger/ebin /usr/lib/elixir/bin/../lib/mix/ebin -noshell -
s elixir start_cli -extra -e ElixirLS.LanguageServer.CLI.main()
    0        0    2946           erl_child_setup 65536
   10        0    2856     watcherService
    0        0    3657     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0        0    3658       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0        0    3659     /home/neofelis/.vscode-server-insiders/bin/fe0c3e785c22c3ed2d5caa7178488c92d62bdb08/node /home/neofelis/.vscode-server-insiders/bin/fe0c3e785c22c3ed2d5caa7178488c
92d62bdb08/out/vs/server/main.js  --port=0 --fileWatcherPolling=4000
Folder (xxx-services): 6469 files
|      File types: beam(3705) ex(841) exs(322) erl(223) fetch(158) app(119)
|                  js(102) config(92) md(86) sh(83)
|      Conf files: package.json(8) makefile(5) webpack.config.js(1)



Remote:           WSL: Ubuntu-18.04
OS Version:       Linux x64 4.4.0-18362-Microsoft
CPUs:             Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)
Memory (System):  15.75GB (4.94GB free)
VM:               0%
CPU %   Mem MB     PID  Process
   15        0    2459  remote agent
    0        0    2511     extensionHost
    0        0    2573       /usr/bin/zsh
    0        0    2575       sh /home/neofelis/.vscode-server-insiders/extensions/jakebecker.elixir-ls-0.2.25/elixir-ls-release/language_server.sh
    0        0    2583         /usr/lib/erlang/erts-10.4.2/bin/beam.smp -- -root /usr/lib/erlang -progname erl -- -home /home/neofelis -- -pa /usr/lib/elixir/bin/../lib/eex/ebin /usr/lib/el
ixir/bin/../lib/elixir/ebin /usr/lib/elixir/bin/../lib/ex_unit/ebin /usr/lib/elixir/bin/../lib/iex/ebin /usr/lib/elixir/bin/../lib/logger/ebin /usr/lib/elixir/bin/../lib/mix/ebin -noshell -
s elixir start_cli -extra -e ElixirLS.LanguageServer.CLI.main()
    0        0    2611           erl_child_setup 65536
    0        0    2845     extensionHost
    0        0    2918       sh /home/neofelis/.vscode-server-insiders/extensions/jakebecker.elixir-ls-0.2.25/elixir-ls-release/language_server.sh
    0        0    2925         /usr/lib/erlang/erts-10.4.2/bin/beam.smp -- -root /usr/lib/erlang -progname erl -- -home /home/neofelis -- -pa /usr/lib/elixir/bin/../lib/eex/ebin /usr/lib/el
ixir/bin/../lib/elixir/ebin /usr/lib/elixir/bin/../lib/ex_unit/ebin /usr/lib/elixir/bin/../lib/iex/ebin /usr/lib/elixir/bin/../lib/logger/ebin /usr/lib/elixir/bin/../lib/mix/ebin -noshell -
s elixir start_cli -extra -e ElixirLS.LanguageServer.CLI.main()
    0        0    2946           erl_child_setup 65536
   11        0    2856     watcherService
    0        0    3659     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0        0    3660       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0        0    3661     /home/neofelis/.vscode-server-insiders/bin/fe0c3e785c22c3ed2d5caa7178488c92d62bdb08/node /home/neofelis/.vscode-server-insiders/bin/fe0c3e785c22c3ed2d5caa7178488c
92d62bdb08/out/vs/server/main.js  --port=0 --fileWatcherPolling=4000
Folder (xxxpay): 3175 files
|      File types: beam(1860) ex(517) erl(167) exs(94) fetch(66) md(55)
|                  config(43) app(40) eex(33) hex(33)
|      Conf files: makefile(4) package.json(2) webpack.config.js(1)

**Comment by powerpbx** [comment]
I also see this.  I am running debian 9 in WSL.  I don't need to have any files open.  I just need to be using WSL remote to connect to my WSL debian files.

**Comment by holt83** [comment]
Also happening to me. The node process constantly using 30-40% CPU and I'm not editing any files.

I recently was experiencing [this issue](https://github.com/microsoft/vscode-remote-release/issues/877) and per recommendation enabled the `remote.WSL.fileWatcher.polling` setting, which appeared to fix the locking issue.

Performance appears to be somewhat better when i disable that setting again. But CPU is still too high IMO sitting at a constant 15% on my CPU. But it is a lot better, so this setting clearly does have an effect on performance. It just that disabling this, will give issues with locked files again that can't be deleted/renamed by my application.

As a last experiment I tried to enable the `remote.WSL.fileWatcher.polling` setting again, but this time with an increased polling interval (from 5000ms to 10000ms), which appears to get the CPU usage down to around 10-15% when idle and 20% when editing files. A lot better than before with this setting enabled.

I would think that a constant CPU usage of 10-15% when idle is still too high?

```
code --status

Version:          Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)
Memory (System):  15.93GB (3.55GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  native_gpu_memory_buffers:     disabled_software
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_deferred_display_list:    disabled_off
                  skia_renderer:                 disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    0       81   25500  code main
    0      136    1544     window (Settings - phpdev [WSL] - Visual Studio Code)
    0       64   32264       extensionHost
    0       30    8928         electron_node wslDaemon.js
    0        5   22640           C:\WINDOWS\System32\wsl.exe sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 3db7e09f3b61f915d03bbfa58e258d6eee843f35 stable .vscode-server 5000  '
    0        5   20280             C:\WINDOWS\System32\lxss\wslhost.exe {12345678-1234-5678-0123-456789abcdef} 396 400 404
    0       11   13648               console-window-host (Windows internal process)
    0        9   22456             console-window-host (Windows internal process)
    0       66    9092     shared-process
    0       60   13248     gpu-process
    0       13   15508     electron-crash-reporter



Remote:           WSL
OS Version:       Linux x64 4.4.0-17134-Microsoft
CPUs:             Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)
Memory (System):  15.93GB (3.59GB free)
VM:               0%
CPU %   Mem MB     PID  Process
   36        0    4184  remote agent
    0        0    4234     extensionHost
    0        0    4261     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0        0    4262       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
Folder (phpdev): more than 33835 files
|      File types: php(5244) yml(1807) js(1407) inc(902) css(674) module(515)
|                  md(502) info(421) png(376) twig(338)
|      Conf files: package.json(27) makefile(19) gulp.js(9) grunt.js(7)
|                  webpack.config.js(2) launch.json(1)
|      Launch Configs: php(2)
```
