### ISSUE TITLE
Cannot connect to remote host since updating to Remote SSH 0.44.0

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/vscode-remote-release#900]
- VSCode Version: 1.36.0
- Local OS Version: Windows 10
- Remote OS Version: Centos 7.6
- Remote Extension/Connection Type: SSH

Since upgrading (this morning) to VS Code 1.36.0 / Remote SSH 0.44.0 VS Code no longer connects to the remote host I had previously used. After starting VS Code it immediately tries to connect to the remote host, fails and retries. It happens so fast, and the console is written to and quickly cleared, that it is hard to capture any error message, but I managed to capture this:

![image](https://user-images.githubusercontent.com/7724321/60670620-1144ff80-9e69-11e9-8429-f02c6febad00.png)

I also see in Log (Window):

    [2019-07-04 14:28:25.725] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
    [2019-07-04 14:35:11.406] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
    [2019-07-04 14:36:38.900] [renderer1] [error] Could not fetch environment: Error: Could not fetch environment
        at d.getEnvironment.then.e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3852:937)

The SSH extension window shows:

![image](https://user-images.githubusercontent.com/7724321/60670767-608b3000-9e69-11e9-8142-5317784670c9.png)

I rolled back to Remote SSH 0.42.2 and then achieved a working remote connection. I then updated again to 0.44.0 and the failure to connect returned. So it definitely looks to be a problem in 0.44.0.

**Comment by jemerald** [comment]
Same as #895

You'll find if you kill all vscode-server processes (`pgrep -f "vscode" | xargs kill`), you will be able to connect, but only from one VC Code window.

**Comment by roblourens** [comment]
Very strange. Same as https://github.com/microsoft/vscode-remote-release/issues/895.

When you are successfully connected, can you try these on your remote: `wget 127.0.0.1:<port>/delay-shutdown` and also just `wget 127.0.0.1:<port>` (should be 404).

Also when you see this error, please share `cat ~/.vscode-server/.<hash>.log` to see if the server was stuck in the middle of shutting down or something like that.

**Comment by derekslenk** [comment]
I can also confirm this is an issue for me. It will connect in the first Window, but as soon as I try to open a folder and it opens another window - that new window can never connect

**Comment by roblourens** [comment]
This appears to be https://github.com/microsoft/vscode-remote-release/issues/895, will close as dupe
