### ISSUE TITLE
[FEATURE] Automatically Setting Proxy for VSCode in WSL

### ISSUE THREAD

**Issue by futuretech6** [microsoft/vscode-remote-release#9000]
I have a clash client on my windows servering at localhost:7890. To set the proxy in my wsl, I can use the following command: `export http_proxy=http://$(cat /etc/resolv.conf | grep nameserver | awk '{ print $2 }'):7890`. However, the host specified in "/etc/wsl.conf" varies across different machines. Consequently, when I attempt to set the "http.proxy" to the host on one machine, it doesn't match the host on another machine. (this setting cannot be set in remote or workspace scale)

I wonder if there's a way to automatically configure the proxy for wsl, regardless of the specific host given by "/etc/wsl.conf" on each machine.

**Comment by aeschli** [comment]
I don't think this is an issue for the WSL extension, maybe mor e a general WSL question?
