### ISSUE TITLE
Cannot install any extensions on a remote container

### ISSUE THREAD

**Issue by Snapbarre** [microsoft/vscode-remote-release#9003]
- VSCode Version: 1.80.0
- Local OS Version: ubuntu 20.04
- Remote OS Version: ubuntu 20.04
- Remote Extension/Connection Type: Containers
- Container :  pytorch/pytorch:2.0.0-cuda11.7-cudnn8-devel

- Issue : 
I cannot install any extension when attached to a docker container on a remote computer, and the UI gets stuck on `installing ...`
Proxy is set for container, networking works ok and i am able to install packages via terminal.
Extensions installation works ok for local and remote vscode

- Logs: 
[container_logs.txt](https://github.com/microsoft/vscode-remote-release/files/12664351/container_logs.txt)
[Extension_Log_(Remote).txt](https://github.com/microsoft/vscode-remote-release/files/12664350/Extension_Log_.Remote.txt)

Developper tool console does return a single error message when I click on install : 
[developer_tool_console.txt](https://github.com/microsoft/vscode-remote-release/files/12664421/developer_tool_console.txt)

proxy is set for docker such as:
```
{
 "proxies": {
   "default": {
     "httpProxy": "http://proxyip:3128",
     "httpsProxy": "http://proxyip:3128"
   }
 }
}
```
in "~/.docker/config.json" on remote host

`Extension: install from vsix` does not display anything and get stuck too.

Steps to Reproduce:

1. connect via ssh and vscode remote development extension to remote computer
2. Set proxy via docker config
3. start container on remote:
`docker run --ipc=host --gpus all -it --rm -d --privileged=true -p 8829:8829 --name torch_dev pytorch/pytorch:2.0.0-cuda11.7-cudnn8-devel`
5. attach to container via vscode container development extension

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
Could you retry with the latest version of VS Code Insiders to make sure you have all the latest fixes? https://code.visualstudio.com/insiders/
