### ISSUE TITLE
postCreateCommand opens in the first folder of a code-workspace

### ISSUE THREAD

**Issue by moltar** [microsoft/vscode-remote-release#9006]
Version: 1.82.2
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T06:00:27.244Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

- Logs:

Steps to Reproduce:

1. Create a multi-root workspace with 2 folders
2. Create a dev container config with `postCreateCommand`
3. Open dev container
4. Observe that the terminal that runs the `postCreateCommand` commands opens in the first workspace's folder.

I think it should be configurable and allow users to specify the `cwd` somehow.

**Comment by chrmarti** [comment]
It should currently run in the folder of the workspace file. Where is that file located?

**Comment by moltar** [comment]
> It should currently run in the folder of the workspace file. Where is that file located?

It's in the root of the repo `./@project.code-workspace`

**Comment by chrmarti** [comment]
So you open the workspace locally and then run `Dev Containers: Reopen Folder in Container` with the config at `./.devcontainer/devcontainer.json`? If so, could you post your workspace file? (If not: Could you give that setup a try?)

**Comment by moltar** [comment]
Just tested it locally as well, and I think this only happens in GitHub Codespaces.

And this happens even on re-opening of the container after it has been built.

I am guessing this is then outside the scope of this repo?

**Comment by moltar** [comment]
Opened a follow-up discussion in Codespaces: https://github.com/orgs/community/discussions/68313

Will close this issue here, as it's not reproducible with local devcontainers.

@chrmarti Thanks for pointing in the right direction! :)
