### ISSUE TITLE
Is it possible to open a file on a remote host via terminal?

### ISSUE THREAD

**Issue by AntonMamedov** [microsoft/vscode-remote-release#9015]
How can I open a file on a remote host via a terminal, similar to how this can be done locally with `code filename`? Maybe there is an API that will allow me to independently implement this functionality? If there is no such feature, is it expected? I would like to open files something like this: `code username@remote_host:22:/home/...`

**Comment by bamurtaugh** [comment]
Thanks for filing. I believe this addresses what you're looking for: https://code.visualstudio.com/docs/remote/troubleshooting#_connect-to-a-remote-host-from-the-terminal.
