### ISSUE TITLE
Test: Connect to dev containers over tunnels

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#9019]
Refs: #7705

- [x] macOS @TylerLeonhardt
- [x] linux @roblourens
- [x] windows @ulugbekna 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%239019%0A%0A&assignees=chrmarti)

---

The tunnel needs to run on a Linux machine at the moment. Use the assigned OS as the one running the VS Code desktop app.

- Make sure you are using Dev Containers 0.313.0-pre-release or later.
- Install the latest VS Code CLI Insiders on a Linux machine and start a tunnel with `code-insiders tunnel`.
- Connect to the tunnel from VS Code desktop using the Remote-Tunnels extension (tunnel will be listed in the Remote-Explorer).
- Reopen folder in container:
  - Open empty folder in tunnel.
  - Run `Dev Containers: Reopen Folder in Container`.
  - Pick a dev container config template.
  - Verify that the window reopens on that folder.
- Open an Integrated Terminal in the dev container and `git clone ...` a private repository.
  - Verify that the Git credentials are forwarded from your local host.
  - If you are using ssh to clone: The ssh-agent is also forwarded into the dev container, check with `ssh-add -l` in the container that your key is available.

**Comment by TylerLeonhardt** [comment]
I can't seem to figure out how to get this TPI to work. I hit the same issues @ulugbekna reported which is preventing me from actually testing the behavior.

**Comment by roblourens** [comment]
I also tried it just in case and got the same errors

**Comment by chrmarti** [comment]
If `Reopen in Container` does not work when there is no devcontainer.json yet (#9030), you can work around it by first using `Add Dev Container Configuration Files...`.

**Comment by roblourens** [comment]
Did that, but then we get https://github.com/microsoft/vscode-remote-release/issues/9031

**Comment by chrmarti** [comment]
The workaround for #9031 is to use Remote-Tunnels v1.5.2023091209 or earlier. (Thanks @TylerLeonhardt for confirming!)

**Comment by roblourens** [comment]
I assume everyone tested this, unassign yourself and close it out if so
