### ISSUE TITLE
Test: Connect to dev containers over SSH

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#9021]
Refs: #7705

- [x] anyOS @paulacamargo25
- [x] anyOS @alexr00

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%239021%0A%0A&assignees=chrmarti)

---

This feature was updated to use Remote-SSH's ExecServer to connect to the SSH server.

The SSH server needs to run on a Linux machine at the moment. All 3 OSes work for the VS Code desktop app.

- Make sure you are using Dev Containers 0.313.0-pre-release or later.
- Connect to the SSH server from VS Code desktop using the Remote-SSH extension.
- Reopen folder in container:
  - Open empty folder on SSH server.
  - Run `Dev Containers: Reopen in Container`.
  - Pick a dev container config template.
  - Verify that the window reopens on that folder.
- Open an Integrated Terminal in the dev container and `git clone ...` a private repository.
  - Verify that the Git credentials are forwarded from your local host.
  - If you are using ssh to clone: The ssh-agent is also forwarded into the dev container, check with `ssh-add -l` in the container that your key is available.

**Comment by alexr00** [comment]
I don't see a `Reopen Folder in Container` command, but the `Open Folder in Container` + selecting the current folder works.

**Comment by alexr00** [comment]
👏

**Comment by chrmarti** [comment]
It's `Reopen in Container`, fix the description. It should be available when you have a workspace folder open.
