### ISSUE TITLE
EOL feature problems don't update when the file is moved

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#9023]
Testing #9020

1. Open an empty folder
2. Add a .devcontainer.json file:
```
{
	"image":"mcr.microsoft.com/devcontainers/typescript-node:0-20",
	"features": {
		"fish": "latest",
		"homebrew": "latest",
		"git": "latest"
	}
}
```
3. Note the 2 errors in the problems panel.
4. Make a folder `.devcontainer` in the explorer and drag `.devcontainer.json` into it
5. Now you have 4 errors, 2 of which are for a file that no longer exists
<img width="762" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/38270282/c3344806-098e-4d61-87f5-1ea634acd7b4">

**Comment by rzhao271** [comment]
Still repros on v0.314.0

**Comment by chrmarti** [comment]
Duplicate warnings are currently expected and tracked as https://github.com/microsoft/vscode-remote-release/issues/9024. Thanks.
