### ISSUE TITLE
Error when running Dev Containers: Reopen in Container on MacOS

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode-remote-release#9032]
Testing #9021

I follow all the steps, when i run `Dev Containers: Reopen in Container`, i got this error and nothing else happened.

![Screenshot 2023-09-26 at 1 12 10 PM](https://github.com/microsoft/vscode-remote-release/assets/17892325/695d16e3-da67-4ecf-9fe0-aa2edfd7316e)

**Comment by chrmarti** [comment]
Please make sure the SSH server runs on a Linux machine (this is currently a limitation we will look into in a coming milestone).
