### ISSUE TITLE
ssh auth credentials not forwarded

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#9033]
Testing #9019

Locally I can clone a repo with ssh credentials, but in this scenario, I get Permission Denied. `SSH_AUTH_SOCK` is set to something like `/tmp/vscode-ssh-auth-...` does the Dev Container extension do that, the same way Remote-SSH does? Not sure what else to look at to debug it.

**Comment by chrmarti** [comment]
We forward the ssh-agent's socket into the container (not using SSH's forwarding). Could you append the log from after you try this? (`Dev Containers: Show Container Log`)
