### ISSUE TITLE
Devcontainer using Docker Compose loses outbound connectivity behind VPN

### ISSUE THREAD

**Issue by matthew-burr** [microsoft/vscode-remote-release#9035]
### Problem Summary
Although I can initially access both external and corporate networks from my devcontainer, after some time, I lose connectivity, and can only regain it either by rebuilding the container or by stopping/restarting the Docker service.

### Scenario
I have a pre-existing Docker Compose file. I've created a devcontainer referencing this file. I run this devcontainer on my local machine. I have a corporate VPN running, as well. I need to be able to access external resources (e.g. GitHub) from the Docker container, as well as some corporate resources (e.g. a database server) via the VPN.

When I first build the container and run it, I am able to access both external and corporate resources from within the container. Examples: I can run code that queries our database and I can access GitHub to push/pull.

After some time, and I've yet to determine a concrete trigger for this, I lose this connectivity. A call to `ssh -T git@github.com`, for example, just hangs. Attempts to use various Git extensions eventually time out. Similarly, attempts to access our DB server, also hang. Even a call to `curl` to access a common site, e.g. `google.com` hangs.

I can resolve the issue by rebuilding the container.
I can also resolve it by shutting down the container, restarting Docker services, and then reconnecting.

Neither of these are desirable approaches.

### Ask
While I've used Docker, Docker Compose, etc. I'm not an expert in any of them. And Dev Containers in VS Code are new to me. 

So, I'm looking for any direction and pointers on how to go about troubleshooting this. My sense is that I just haven't got something configured quite right.

**Comment by chrmarti** [comment]
This seems to be independent of Dev Containers, but would apply to all Docker containers. Please check documentation and forums on that.
