### ISSUE TITLE
[wsl] download fills disk

### ISSUE THREAD

**Issue by mathieulongtin** [microsoft/vscode-remote-release#9036]
Type: <b>Bug</b>

My laptop's disk filled with 350GB of temporary files named like this:
vscode-server-insider-linux-x64.tar.gz_TIMESTAMP

There were 50MB each, that's 7000 copies, averaging 70 files per day since I started using VS Code Insiders. 

Extension version: 0.81.5
VS Code version: Code - Insiders 1.83.0-insider (c72447e8d8aaa7497c9a4bd68bc4301584b92beb, 2023-09-22T09:29:47.641Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.0-78-generic
Remote OS version: Linux x64 5.15.0-78-generic
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.39GB (0.58GB free)|
|Process Argv|--crash-reporter-id 31ccd15c-60c6-43d2-bd51-2b6b81189fe3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1804)|
|Memory (System)|7.46GB (5.13GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
ecj1e332:30687743
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingc:30808720
synctok:30821570
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonlinttypecf:30823782
pythonmpsinfo:30842935
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809
pythonregdiag:30842812
pythonmypyd1:30841190

```

</details>

**Comment by mathieulongtin** [comment]
More details:
* The files are erased if you quit vscode
* But when you restart, they download rapidly, I had 700 files within a 10 hours, while the compute was locked

**Comment by roblourens** [comment]
Sorry for the late response. Is this still an issue? Which remote extension are you using?

**Comment by aeschli** [comment]
Did you find these files on the Windows or on the WSL Linux file system?

**Comment by mathieulongtin** [comment]
It was in Windows. I stopped using the insider version not long after I filed this bug.
