### ISSUE TITLE
devcontainer: extensions are not installed

### ISSUE THREAD

**Issue by borjamunozf** [microsoft/vscode-remote-release#9040]
- VSCode Version: 1.82.2
- Local OS Version:  Ubuntu 20.04 WSL
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Containers/WSL

- Logs:

I have been working with VSCODE since last year and I have tried devcontainer to install the extensions for a while, but no release has fixed this yet for me.

1. Tested with Default profile.
2. Create devcontainer.json with any extension (manually added in my case)
```json
{
        "name": "native toolchain",
        "build": {
                "dockerfile": "Dockerfile",
                "args": {
                        "USERNAME": "${localEnv:USER}",
                        "USER_UID": "1000"
                }
        },
        "privileged": true,
        "runArgs": [
                "--ipc=host"
        ],
        "mounts": [
                "source=${localWorkspaceFolder}/vtune-results,target=/vtune-results,type=bind,consistency=cached"
        ],
        "customizations": {
                "vscode": {
                        "extensions": [
                                "ms-vscode.cpptools-extension-pack"
                        ]
                }
        }
}
```
3. Run
![imagen](https://github.com/microsoft/vscode/assets/25910927/dfbccaaa-9e56-4030-a48c-f1ba171daeca)

This has been reported previously on #8777

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
I think this issue and #8777 are not same

**Comment by chrmarti** [comment]
Could you append the entire log?

**Comment by borjamunozf** [comment]
I have been away, sorry. Uploading the devcontainer log:

devcontainer.json content
```json
{
    "name": "test-extensions",
    "build": {
        "dockerfile": "Dockerfile",
        "args": {
                "USERNAME": "${localEnv:USER}",
                "USER_UID": "1000"
        }
},
    "customizations": {
        "vscode": {
                "extensions": [
                        "ms-vscode.cpptools-extension-pack",
                        "ms-vscode.cpptools"
                ]
        }
    }
}

```
[devcontainer extensions not installed.txt](https://github.com/microsoft/vscode-remote-release/files/12884860/devcontainer.extensions.not.installed.txt)

Snapshot:

![imagen](https://github.com/microsoft/vscode-remote-release/assets/25910927/1f90f4d1-7ebb-4a4d-9496-caeb076c1876)
