### ISSUE TITLE
std-in files (/tmp/code-stdin-*) are not removed on remote and should have user only access rights

### ISSUE THREAD

**Issue by smerschjohann** [microsoft/vscode-remote-release#9048]
Type: <b>Bug</b>

1. run `echo test | code -` from an integrated terminal (on a remote)
2. VSCode reads from stdin `Reading from stdin via: /tmp/code-stdin-Nsj`
3. VSCode opens up the /tmp/code-stdin-* file
4. the shell from 1. still waits for return
5. close the editor window in VSCode
6. the shell from 1. returns
7. the file persists.

If I do the same on a local machine without the Remote Extension, the file gets successfully deleted.

In addition to this, the files are world readable and can potentially contain sensitive information.

So I would like to see:
1. the temp files are removed after use (like without extension)
2. the temp file has only required r/w rights (600)

Extension version: 0.106.4
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:51:20.981Z)
OS version: Linux x64 6.5.5-300.fc39.x86_64
Modes:
Remote OS version: Linux x64 5.4.0-163-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 400)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|38.84GB (35.01GB free)|
|Process Argv|--unity-launch --crash-reporter-id 9bae5dee-b705-48dc-a1c7-04705bde99bf|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|

|Item|Value|
|---|---|
|Remote|SSH: server1|
|OS|Linux x64 5.4.0-163-generic|
|CPUs|Intel(R) Pentium(R) CPU  N3710  @ 1.60GHz (4 x 1520)|
|Memory (System)|15.47GB (13.41GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by joshspicer** [comment]
Adding Ben who from [git blame](https://github.com/microsoft/vscode/blame/cdec0c6a14aeeae336c3467a7fa156f2cde6945f/src/vs/platform/environment/node/stdin.ts#L38) might how some knowledge of this feature

**Comment by aeschli** [comment]
The file is in the `tmp` folder and will eventually be removed by the OS.

I agree that removing it right away is nicer, but not a 'must-have'

**Comment by smerschjohann** [comment]
As /tmp files are not user bound, and the passed data might contain sensitive data, I would prefer if they are cleaned up sooner than later. Also /tmp files on servers can be kept for quite some time before removal.

But yes, not a "must".

**Comment by aeschli** [comment]
We can only remove the file if the cli was started with `--wait`. Thats also the behavior on a local CLI.
Otherwise, it's just a file open in an editor and we don't know how long the user wants to use it.

The PR now also removes the file when started with `--wait` so the remote cli behaves like the local CLI.

Also, it changes the access rights to 600
