### ISSUE TITLE
Can not attach to Dev Containers, Running Container on remote Host through SSH

### ISSUE THREAD

**Issue by mickeyboo0112** [microsoft/vscode-remote-release#9049]
Type: <b>Bug</b>

Error running command remote-containers.explorerTargetsRefresh: Shell server terminated (code: 1, signal: null)

The system cannot find the path specified.
. This is likely caused by the extension that contributes remote-containers.explorerTargetsRefresh.

Extension version: 0.106.4
VS Code version: Code 1.82.2 (Universal) (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:59:47.790Z)
OS version: Darwin x64 19.6.0
Modes:
Remote OS version: Windows_NT x64 10.0.19045

**Comment by chrmarti** [comment]
Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)
