### ISSUE TITLE
Documentation title is misleading

### ISSUE THREAD

**Issue by rivaros** [microsoft/vscode-remote-release#9050]
Having read twice the article below titled `Configure separate containers`
https://code.visualstudio.com/remote/advancedcontainers/configure-separate-containers

I'd like to state that there is nothing in it about `separate containers`. What article tells is that you can start
ONE container on root folder and then open different folders INSIDE that container.

Please remove the misleading title. Also this issue https://github.com/microsoft/vscode-remote-release/issues/2413
was closed based on that article (and seems there was no thorough check that it has nothing to do with the issue reported). Pls reopen issue - devcontainer in subdirectories is not supported by VSCode atm!

**Comment by bamurtaugh** [comment]
Thanks for the feedback. If you have a moment, would you be willing to contribute a PR to the documentation that would make it clearer for you? Please feel free to tag me in the PR, and I'd be happy to review it!
