### ISSUE TITLE
Reveal in Explorer is not supported in the browser 

### ISSUE THREAD

**Issue by caiobarilli** [microsoft/vscode-remote-release#9053]
the fix made in version 0.79.5 stopped working in the current version 0.81.7

history of this issue:
https://github.com/microsoft/vscode-remote-release/issues/8568

**Comment by palpa** [comment]
Issue started on 0.81.5, rolling back to 0.81.4 Reveal in Explorer is working fine.

**Comment by aeschli** [comment]
duplicate of #9037
