### ISSUE TITLE
Tunnel List Empty

### ISSUE THREAD

**Issue by sohampnow** [microsoft/vscode-remote-release#9055]
Type: <b>Bug</b>

I am fairly new to using Remote Tunnels. I started a tunnel each on two remote machines using `code tunnel`. I was able to access them from my local vscode instance for the last 3 days. 
However, my local machine suddenly got disconnected from the remote tunnels today and I can no longer see any tunnels listed in my options. 

I verified the following:
1. Tunnels are still running on both machines. Restarted them as well
2. Links to the browser mode for remote tunnels still work. Tunnel list is empty on these links as well
3. The extension is using the same GitHub account on all vscode instances

I saw this particular error on one of the tunnels. Unfortunately I don't have the detailed logs from the error.

`Exceeded rate limit ApiQueryRatePerIPAddress of 40/s`

Does this mean I have been rate-limited? If so, when will the limit be taken off? If not, are there suggestions to fix this?

Thanks in advance! 

Extension version: 1.4.3
VS Code version: Code 1.82.3 (Universal) (fdb98833154679dbaa7af67a5a29fe19e55c2b73, 2023-10-02T11:06:17.496Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|32.00GB (2.43GB free)|
|Process Argv|--crash-reporter-id 814390fd-62dc-4b37-8e94-422326bacf9e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
vscrp:30673768
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by aleleba** [comment]
It happened to me too:

![Screenshot_20231002_193819_Chrome.jpg](https://github.com/microsoft/vscode-remote-release/assets/28767814/d04b9825-d130-47f8-8955-1ef1e356a092)

**Comment by ajs1998** [comment]
Exact same problem here. It was working yesterday and now it's not. Clicking the link works, but connecting directly through VSCode on my machine shows no tunnels to connect to.

**Comment by tuancuong92** [comment]
I just faced this problem few hours ago. Never see this bug before.

**Comment by digismack** [comment]
Same issue [here](https://github.com/microsoft/vscode-remote-release/issues/9054).

**Comment by Drogmor** [comment]
I have been facing the same issue today.
I can access my remote tunnel via the vscode.dev/tunnel url using my browser but the tunnels do not appear on the list in my vs code for windows.
I have tried the following:
Running both code tunnel and code-insiders tunnel.
Killed and used prune on my host.
Unregistered the machine and stared again after removing all related files and folders.
Removed the extension and reinstalled (both stable and pre-release).
Sign out from github account on my vs code.

**Comment by Yharon** [comment]
Same issue here.

![image](https://github.com/microsoft/vscode-remote-release/assets/25456250/18a2dd44-89e2-440f-bc5c-ae50bad77105)

**Comment by devdouglasferreira** [comment]
I am facing the same problem. I was running tunnels just fine some time ago I was running it on as Raspberry Pi 4 was able to access anywhere from my iPad. Now I had to reinstall the Ubuntu Server distro and reinstalled eveything including code-cli and I'm not being able to list the tunnels on my vs code web in ipad neither in my desktop installed vs code...

**Comment by devdouglasferreira** [comment]
> Exact same problem here. It was working yesterday and now it's not. Clicking the link works, but connecting directly through VSCode on my machine shows no tunnels to connect to.

I was being able to connect clicking in the link only as well. But now not even clicking it works. It pop ups the error: 
"(Error: Timeout connecting to relay)"

**Comment by Yukun-Guo** [comment]
Same issue here. I tried the previous versions of Remote-tunnel, but all of them don't work. 
![image](https://github.com/microsoft/vscode-remote-release/assets/23413230/1478b407-a548-4e23-b3b3-e3bf16000af6)

**Comment by yusufkhan07** [comment]
Same problem.

**Comment by connor4312** [comment]
Duplicating into https://github.com/microsoft/vscode-remote-release/issues/9054
