### ISSUE TITLE
[Remote-Tunnel] Cannot find the opening tunnel server 

### ISSUE THREAD

**Issue by chocolatetoast-chiu** [microsoft/vscode-remote-release#9057]
Type: <b>Bug</b>

I previously used `code tunnel` to run the code server and remotely access my code in my server PC, but now I cannot see any tunnel running after click the "connecting to tunnel..." even if I can use the browser in server PC to connect to the tunnel. I wonder why that happened. Thanks!

My server terminal:
![image](https://github.com/microsoft/vscode-remote-release/assets/56018137/6b602b81-1354-4790-9e37-774fb4297535)

My VSCode UI: Remote-Tunnel extension command palette:
![image](https://github.com/microsoft/vscode-remote-release/assets/56018137/c8fc582b-7bff-4b13-bd28-cc648af37304)

Extension version: 1.4.3
VS Code version: Code 1.82.3 (fdb98833154679dbaa7af67a5a29fe19e55c2b73, 2023-10-02T10:49:50.455Z)
OS version: Linux x64 5.15.0-83-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz (40 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|31.04GB (9.63GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 196f6ff3-0935-4585-bb3d-d07bcd2e3152|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by samxu29** [comment]
Might be a server outage...
Same issues here:
https://github.com/microsoft/vscode-remote-release/issues/9055
https://github.com/microsoft/vscode-remote-release/issues/9054

**Comment by connor4312** [comment]
Duplicating into https://github.com/microsoft/vscode-remote-release/issues/9054
