### ISSUE TITLE
Search for files & symbols not working with remote SSH & dev containers

### ISSUE THREAD

**Issue by savvn001** [microsoft/vscode-remote-release#9062]
Type: <b>Bug</b>

Hi,

I'm using the dev-containers extension whilst connected to a remote-SSH server, through the remote-SSH functionality in VSCode.

I'm experiencing an issue where searching for files or symbols, either though the command pallete or the search pane, that are present in my workspace aren't found, until I manually go and open those files at least for the first time. Then after that they are always found as usual.

I find this always happens each time I re-open VSCode.

Extension version: 0.309.0
VS Code version: Code 1.82.3 (Universal) (fdb98833154679dbaa7af67a5a29fe19e55c2b73, 2023-10-02T11:06:17.496Z)
OS version: Darwin arm64 22.6.0
Modes:
Remote OS version: Linux arm64 6.1.51-0-lts

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 84bade16-60cd-4cd6-b7e7-3642a378ebee|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Existing Dockerfile @ ssh://10.211.55.3|
|OS|Linux arm64 6.1.51-0-lts|
|CPUs|unknown (4 x 0)|
|Memory (System)|3.82GB (2.06GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
0bi6i642:30841073
a2ce3375:30757347
24365598:30736109
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by rnicholus** [comment]
having the same issue here - search by file name is simply broken when using remote development

**Comment by andreamah** [comment]
1. Run `Developer: Set Log Level`  in the command palette and set `Trace`.
2. Do a search.
3. In the bottom panel, check logs in the `Extension Host (Remote)` channel in the `Outputs` tab.

Do you get any error messages regarding Ripgrep or search?
