### ISSUE TITLE
File system provider not available in latest version (v0.315.0)

### ISSUE THREAD

**Issue by Sapentia-Theo-Cole** [microsoft/vscode-remote-release#9065]
- VSCode Version: 1.83, 1.82.3
- Local OS Version: Windows 11 Home 10.0.22621 Build 22621
- Remote OS Version: Ubuntu 22.04.2 LTS (WSL)
- Remote Extension/Connection Type: Devcontainer to Docker Desktop using WSL engine

- Logs:

Steps to Reproduce:

1. From WSL, open in container
![image](https://github.com/microsoft/vscode-remote-release/assets/111371576/15cd95dd-78fb-4736-a32b-ec25491870c1)

Downgrading to v0.309.0 fixes the issue.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by ToRe-12357** [comment]
Same behaviour here with VSCode 1.83.0

**Comment by ToRe-12357** [comment]
Could be related to #9060

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/9060. Thanks.
