### ISSUE TITLE
Error attach to a container in last release

### ISSUE THREAD

**Issue by ste-script** [microsoft/vscode-remote-release#9066]
Type: <b>Bug</b>

On last version doesn't attach and report Logs: Error running command remote-containers.attachToRunningContainerFromViewlet. 
Rolling back to the last update is back to work

Extension version: 0.309.0
VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Remote OS version: Linux x64 5.15.0-86-generic
Remote OS version: Linux x64 5.15.0-86-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1280P (20 x 1997)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (7.36GB free)|
|Process Argv|--crash-reporter-id bf6619df-3c9e-4e82-8089-31583c72578f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container webservices-php-fpm (webservices-php-fpm-1) @ ssh://192.168.10.151|
|OS|Linux x64 5.15.0-86-generic|
|CPUs|Intel(R) Xeon(R) Silver 4310 CPU @ 2.10GHz (4 x 2095)|
|Memory (System)|7.75GB (6.04GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.10.151|
|OS|Linux x64 5.15.0-86-generic|
|CPUs|Intel(R) Xeon(R) Silver 4310 CPU @ 2.10GHz (4 x 2095)|
|Memory (System)|7.75GB (6.04GB free)|
|VM|7%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30845448

```

</details>

**Comment by AbhinavDutta** [comment]
Faced the same issue . Switched back to v0.309.0 and everything works as usual

**Comment by tonynajjar** [comment]
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/9064

**Comment by connor4312** [comment]
To confirm, are you trying to attach to a container running on a remote machine? If so, this is a duplicate.

**Comment by ste-script** [comment]
Just rolled back to previous version
