### ISSUE TITLE
Hosts hidden with multiple IPs per line in config file

### ISSUE THREAD

**Issue by omartin2010** [microsoft/vscode-remote-release#907]
Issue Type: <b>Bug</b>

When the ssh config file has a line like this :

Host 192.168.x.50 192.168.x.51 192.168.xx.52
	User abc
	ForwardX11		no
	ForwardAgent		no
	ForwardX11Trusted	no

Then this/these entry/entries won't show in the list of IPs to connect to.

Extension version: 0.44.0
VS Code version: Code - Insiders 1.37.0-insider (8627d1e311d1cc1c8fcd1df5688c145a8bf3a6c9, 2019-07-04T17:03:22.019Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
This works for me now with the latest nightly version of the extension
