### ISSUE TITLE
Issue with Remote-SSH Extension in VSCode when Switching Users

### ISSUE THREAD

**Issue by SammonBabu** [microsoft/vscode-remote-release#9072]
Hello everyone,

I've been using VSCode with the Remote-SSH extension, and I'm encountering a problem when trying to access certain files on a remote host. I connect to the host using a username and IdentityFile with a passphrase. However, to access specific files, I need to switch users using the `'su <user>'` command, and provide that user's password.

The issue I'm facing is that once I switch users, I can only access the file in the terminal, and I'm unable to see or edit it in the VSCode file explorer. Consequently, I'm unable to use the graphical editor of VSCode to modify these files.

Has anyone else encountered this problem, and if so, do you have any suggestions on how to resolve it? Your help would be greatly appreciated!

Thank you.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/690
