### ISSUE TITLE
[Remote-SSH Bug]: Can't Attatch Visual Studio

### ISSUE THREAD

**Issue by alexxony** [microsoft/vscode-remote-release#9073]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

I connected to server. 

As you see below 
![image](https://github.com/microsoft/vscode-remote-release/assets/63861370/7e49e5bf-c5e8-4a4f-b643-be0b77e1e43e)

But When I tried to Attatch Visual Studio,

![image](https://github.com/microsoft/vscode-remote-release/assets/63861370/c24e4d09-a4dc-46c6-a148-822fa1cba066)

This Error occured.

**Error running command remote-containers.attachToRunningContainerFromViewlet: The operation was aborted. This is likely caused by the extension that contributes remote-containers.attachToRunningContainerFromViewlet.**

It occured in yesterday morning,  How could I fix it?

### Expected Behavior

Can't Attach Visual Studio code

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
==========
== CUDA ==
==========

CUDA Version 11.8.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.```

</p>
</details>


### Anything else?

_No response_

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-remote-release/issues/9064, should be fixed with the latest version of Remote - Containers and Remote - SSH.
