### ISSUE TITLE
[Remote-SSH Bug]: Failure to acquire local install lock

### ISSUE THREAD

**Issue by laurentdelosieresfact** [microsoft/vscode-remote-release#9074]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

When setting the "remote.SSH.useLocalServer" to true, and an update of VSCode or Google Chrome is occurring via Jamf, the extension is trying to acquire a lock file in an obsolete folder e.g. "/Library/Application Support/JamfAppInstallers/com.google.Chrome/tmp/vscode-remote-ssh-7390705a-install.lock" and since the folder does not exist anymore the process gets hung.

### Expected Behavior

The extension should check if the folder still exists before trying to acquire the lock.

### Steps To Reproduce

1. Enrolll Mac with Jamf
2. Add VSCode and Google Chrome in the Jamf Catalog and force the installation via Jamf (as well as the updates)
3. Set remote.SSH.useLocalServer to true
4. The extension is getting blocked at acquiring the lock

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[15:29:52.483] Setting up SSH remote "coder-vscode--xxxx"
[15:29:52.485] Acquiring local install lock: /Library/Application Support/JamfAppInstallers/com.google.Chrome/tmp/vscode-remote-ssh-7390705a-install.lock
[15:29:53.984] Starting to look for password prompt from another window
```

</p>
</details>

**Comment by roblourens** [comment]
This is a little confusing... how can they delete my temp dir while an app is still using it? Why is vscode's temp dir under `/com.google.Chrome/`? What other location am I supposed to use?

**Comment by laurentdelosieresfact** [comment]
Hi @roblourens ,

"""
Why is vscode's temp dir under /com.google.Chrome/
"""
-> this is a very good question and we do not know the answer to this one. We have seen this issue with 
```
[15:29:52.485] Acquiring local install lock: /Library/Application Support/JamfAppInstallers/com.google.Chrome/tmp/vscode-remote-ssh-7390705a-install.lock
```

and 

```
[08:07:07.810] Acquiring local install lock: /Library/Application Support/JamfAppInstallers/com.microsoft.VSCode/tmp/vscode-remote-ssh-910937f8-install.lock
```

Best,
L.

**Comment by roblourens** [comment]
I don't know how Jamf works under the hood, but I am not convinced that vscode is doing anything wrong. We have a temp dir, we are using it in a normal way, Jamf decided to delete it while the app is still running.

**Comment by laurentdelosieresfact** [comment]
@roblourens before acquiring the lock, can we add a condition that checks whether the lock still exists ?

**Comment by roblourens** [comment]
I would like to improve the locking code, there is an issue for that, although I'm not sure it would totally solve this issue because some window could acquire the lock, jamf could delete that folder, thus breaking the lock? It all just seems wrong to me. Closing this.
