### ISSUE TITLE
able to use gui program remotely like ssh -X when using remote tunnel

### ISSUE THREAD

**Issue by yongjer** [microsoft/vscode-remote-release#9080]
add config in remote tunnel whether activating gui 
```[tasklist]
### Tasks
```

**Comment by bamurtaugh** [comment]
Hi, can you please provide some more info on what you're interested in here? Thanks!

**Comment by yongjer** [comment]
forward X over tunnel to run graphics applications remotely
such as using gimp
there is only cli now
