### ISSUE TITLE
Fix: Use interactive login shell on remote host for env probing

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#9081]
Rollbacking to `v0.309.0` from `0.315.1` also fixed an error for me where the `localEnv` was always empty. I was using SSH.

_Originally posted by @Telcrome in https://github.com/microsoft/vscode-remote-release/issues/9060#issuecomment-1752623030_

**Comment by juancarlossanctions** [comment]
Hello,

I was following [previous thread](https://github.com/microsoft/vscode-remote-release/issues/9060) and trying differents solutions but I am still getting error:

`Error opening dev container configurations: CodeExpectedError: ENOPRO: No file system provider found for resource 
 'vscode-remote://dev-container%2B7b22686f737450617468223a22643a5c5c4a75616e6b795c5c776f726b73706163655c5c53616e6374696f6e732e696f5c5c73616e6374696f6e732e696f2d617069222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a22643a5c5c4a75616e6b795c5c776f726b73706163655c5c53616e6374696f6e732e696f5c5c73616e6374696f6e732e696f2d6170695c5c2e646576636f6e7461696e65725c5c646576636f6e7461696e65722e6a736f6e222c225f736570223a312c2265787465726e616c223a2266696c653a2f2f2f642533412f4a75616e6b792f776f726b73706163652f53616e6374696f6e732e696f2f73616e6374696f6e732e696f2d6170692f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f643a2f4a75616e6b792f776f726b73706163652f53616e6374696f6e732e696f2f73616e6374696f6e732e696f2d6170692f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/Users/myuser/workspace/myproject'`

I am using **Windows 10** with:

- **VSCode** 1.83
- **Docker Desktop** 4.24.1 (Docker engine 24.0.6)

and then I checked several versions of VSCode plugin **Dev Containers**:

- 0.309.0
- 0.315.0
- 0.315.1
- 0.317.0

But I am still getting the same error :(

Thanks!

**Comment by prz999** [comment]
I got this problem too. When I rollbacking to 'v0.309.0', it's solved.

**Comment by chrmarti** [comment]
@juancarlossanctions Thanks, continuing for the ENOPRO in #9089. Will track the localEnv issue @Telcrome reported here.

**Comment by chrmarti** [comment]
Fixed in Dev Containers 0.318.0-pre-release.

**Comment by chrmarti** [comment]
Verification:
- Start a tunnel (`code-insiders tunnel`) on a Linux or Mac machine.
- Add an env variable to its default shell's RC file, e.g.: add `export FOO=TESTING456` to `~/.bashrc` (`~/.zshrc` if zsh is the default shell).
- Connect to that tunnel, open a folder and add the following `.devcontainer/devcontainer.json`:
```json
{
	"image":"mcr.microsoft.com/devcontainers/typescript-node:0-20",
	"remoteEnv": {
		"BAR": "${localEnv:FOO}"
	}
}
```
- Reopen folder in container and verify in the terminal that the env variable is there: `echo $BAR`

**Comment by connor4312** [comment]
Unfortunately this doesn't seem to work for me on v0.320.0. Neither FOO nor BAR are set in the container.

**Comment by chrmarti** [comment]
I see this working. Make sure you open a new integrated terminal as existing shells (that may be preserved across window reloads) would not pick up additional env variables. If that doesn't explain it, please enable trace logging for Dev Containers in the user settings, reload the container window and attach the log from that (`F1` > `Dev Containers: Show Container Log`).


![Image](https://github.com/microsoft/vscode-remote-release/assets/9205389/84fc3ae6-e180-40cf-a7a4-111a321d05c7)

**Comment by connor4312** [comment]
It worked for me this time! Maybe I had something outdated at some point.
