### ISSUE TITLE
Identify vscode remote connection is active through terminal or env

### ISSUE THREAD

**Issue by BhavyaVM1** [microsoft/vscode-remote-release#9083]
Inquiry about Programmatic Differentiation of Remote SSH Connections in VS Code Extension

I am currently developing an extension for Visual Studio Code that requires different behavior depending on whether the VS Code instance is connected via Remote SSH or running locally in VNC sessions.

I have noticed the presence of the "SSH:<host-name>" label in the VS Code status bar when connected via Remote SSH, and I'm interested in obtaining this information programmatically or any other reliable indicator that can help me distinguish between remote SSH connections and local instances.

Could you please provide guidance or insights on how I can programmatically determine whether a Visual Studio Code instance is connected through the Remote SSH Extension or running locally? Your assistance in this matter would be greatly appreciated.

**Comment by roblourens** [comment]
See `vscode.env.remoteName`
