### ISSUE TITLE
Podman error when reopen in remote devcontainer: could not find a working conmon binary

### ISSUE THREAD

**Issue by NerdToMars** [microsoft/vscode-remote-release#9088]
- VSCode Version: 
Version: 1.83.0 (user setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

- Local OS Version: OS: Windows_NT x64 10.0.22621
- Remote OS Version: Linux 5.15.0-78-generic 20.04.1-Ubuntu SMP Mon Jul 17 09:42:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Remote Extension/Connection Type: Remote Containers

- Logs:
```
[4696 ms] Start: Run in Host: /home/xxxx/miniconda3/bin/podman version --format {{.Server.APIVersion}}
[4801 ms] Error: could not find a working conmon binary (configured options: [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon]: invalid argument)
```
I can run `podman version --format {{.Server.APIVersion}}` on my remote host, the output is 
```
4.3.1
```

the conmon is installed 
```
# which conmon
/home/xxxx/miniconda3/bin/conmon
```

Steps to Reproduce:
1. install remote-ssh on local vscode
2. connect to remote host use remote-ssh in vscode
3. Install devcontainer extension on remote vscode:

> the devcontainer:
> 
> Name: Dev Containers
> Id: ms-vscode-remote.remote-containers
> Description: Open any folder or repository inside a Docker container and take advantage of Visual Studio Code's full feature set.
> Version: 0.317.0
> Publisher: Microsoft
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers
> 

4. Reopen in container on remote vscode

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

There is no issue if I roll back ms-vscode-remote.remote-containers to version v0.299.0; I did not test other older version.

**Comment by chrmarti** [comment]
This could be https://github.com/microsoft/vscode-remote-release/issues/9081 which should be fixed in Dev Containers 0.320.0-pre-release. Could you give that a try?
