### ISSUE TITLE
not showing first entry of config file

### ISSUE THREAD

**Issue by omartin2010** [microsoft/vscode-remote-release#909]
Issue Type: <b>Bug</b>

When opening a config file that looks like this for example : 

```
Host host1
	HostName 192.168.x.y
	User test123

Host host2
	HostName 192.168.x.y+1
	User test123

Host host3
	HostName 192.168.x.y+2
	User test123

```
Only the last two entries will show in the list of hosts 
![image](https://user-images.githubusercontent.com/11371870/60686101-fa0c0f00-9e74-11e9-98bb-e173421f7afe.png)

I'm observing the same behavior on MacOs too.

Extension version: 0.44.0
VS Code version: Code - Insiders 1.37.0-insider (8627d1e311d1cc1c8fcd1df5688c145a8bf3a6c9, 2019-07-04T17:03:22.019Z)
OS version: Windows_NT x64 10.0.18362
Fetching remote diagnostics for 'SSH: notebookVM1' failed: Connection error: Unauthorized client refused.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH: notebookVM1' failed: Connection error: Unauthorized client refused.
</details>

**Comment by roblourens** [comment]
Is this exactly what your ssh config looks like or could there be some other difference between host1 and host2 that causes the issue? Some ssh config syntax is not supported well.

**Comment by omartin2010** [comment]
In fact, here's the complete file : 

```
Host *
	KexAlgorithms +diffie-hellman-group1-sha1
	ForwardX11		yes
	ForwardAgent		yes
	ForwardX11Trusted	yes

Host host1
	HostName 192.168.x.y
	User test123

Host host2
	HostName 192.168.x.y+1
	User test123

Host host3
	HostName 192.168.x.y+2
	User test123
```
When I have this, host1 doesn't show. If I remove the Host * or if I put it last, then it works. I guess it's a parsing issue.

**Comment by roblourens** [comment]
Yeah it has something to do with the tab characters, strangely enough.

**Comment by roblourens** [comment]
Upstream: https://github.com/cyjake/ssh-config/issues/20
