### ISSUE TITLE
Remote-WSL: Why does the extension activate on startup?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-remote-release#9093]
I just noticed an excessive number of user data changes happening and one of the culprits appears to be the WSL extension: https://github.com/microsoft/vscode-remote-release/issues/9092

It begs the question why is it even activating in a window not connected to WSL?

**Comment by aeschli** [comment]
Two reasons:
- we have a recommender that is active when not in a remote window. If we are editing in `\\wsl$\...` we tell you to reopen in a WSL window
- we track the update service and if there's a new build ready, we also download the matching server build to be ready in case the user updates while offline

We don't do much in activate, so this shouldn't be a problem

**Comment by Tyriar** [comment]
> we have a recommender that is active when not in a remote window. If we are editing in \\wsl$\... we tell you to reopen in a WSL window

This is the built-in WSL: Recommender though right?

> we track the update service and if there's a new build ready, we also download the matching server build to be ready in case the user updates while offline

Can't we just do that when in a window with WSL? I would expect that to capture most cases and then we don't need to activate at all. Even if it's a little, it all adds up. This extension is one of the few things that was doing something on idle for example (https://github.com/microsoft/vscode-remote-release/issues/9092).

**Comment by aeschli** [comment]
> This is the built-in WSL: Recommender though right?
No that's in WSL. The reopen command it recommends is provided by the extension.
The WSL Recommender is about recommending installing the WSL extension.

> Can't we just do that when in a window with WSL? I would expect that to capture most cases and then we don't need to activate at all. Even if it's a little, it all adds up. This extension is one of the few things that was doing something on idle for example (https://github.com/microsoft/vscode-remote-release/issues/9092).

Yes I guess we can do that.

**Comment by aeschli** [comment]
As explained, we need the eager activation for the `\\wsl$\...` recommendation.

It's also needed to set context variables that are used for command enablement.
That's e.g. needed that when we discover that we run in a tunned or ssh windows that supports WSL.

Closing the issue, I don't see any alternatives here...
