### ISSUE TITLE
Support connecting to docker containers over tunnels on Windows

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#9095]
Continuing from https://github.com/microsoft/vscode-remote-release/issues/7705

**Comment by schiffy91** [comment]
I don't know if this is useful, but if it is – here's the output I get after 1) using my mac (client) to connect to a windows 11 desktop (server) with remote tunnel 2) opening a remote workspace 3) trying to open that workspace in the container

[10325 ms] Dev Containers 0.318.0 in VS Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc).
[10324 ms] Start: Run: powershell -NoProfile -Command -
[10416 ms] Start: Run in host: id -un
[10691 ms] 
[10692 ms] id : The term 'id' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:28
+ [Console]::Write('
[10695 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd '' || grep -E '^|^[^:]*:[^:]*::' /etc/passwd || true

It just hangs

**Comment by NicoNicoNico123** [comment]
> I don't know if this is useful, but if it is – here's the output I get after 1) using my mac (client) to connect to a windows 11 desktop (server) with remote tunnel 2) opening a remote workspace 3) trying to open that workspace in the container
> 
> [10325 ms] Dev Containers 0.318.0 in VS Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc). [10324 ms] Start: Run: powershell -NoProfile -Command - [10416 ms] Start: Run in host: id -un [10691 ms] [10692 ms] id : The term 'id' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:28
> 
> * [10695 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd '' || grep -E '^|^[^:]_:[^:]_::' /etc/passwd || true
> 
> It just hangs

Have you fix this issue? It's same issue on me? It's that need to connect via SSH?

**Comment by chrmarti** [comment]
This is available with Dev Containers 0.319.0-pre-release. Could you give that a try?

You first connect to a Windows machine either using tunnel or SSH and there you have the usual Dev Container commands available.

We are currently testing this, feedback appreciated, thanks!

**Comment by chrmarti** [comment]
I forgot: Currently you need the latest VS Code Insiders version: https://code.visualstudio.com/insiders/ to get Dev Containers 0.319.0-pre-release. This will also work with VS Code 1.84 which is expected to become available some time next week.
