### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by paamonim** [microsoft/vscode-remote-release#9097]
Type: <b>Bug</b>

I have wsl extension installed. Everything worked fine. Today it stopped working! But it'w weird. Only for my rails app it is stuck, but it does connect to other folders that I work with like React Native.
It tries to connect all the time with no success!
I tried to reinstall the extension - not working, tried to reinstall visual studio - not working. Tried to install previous version of wsl extension - not working.

Extension version: 0.81.8
VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (8.39GB free)|
|Process Argv|--crash-reporter-id 6ad9ef7f-2045-45a5-bc81-9985cfec6d4f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
0bi6i642:30841073
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingt:30839829
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30845448

```

</details>

**Comment by 54younger** [comment]
I have the same issue with you, but the difference is that I have two versions' VScode, one is Vscode, and another is Vscode insider. 
The most werid things is that, same folder, same setting, only one version can successfully worked.
So the bug can't be in the extension's setting, and can't be in the .ssh folder neither, but it just happened ,I am so confused.

**Comment by bamurtaugh** [comment]
Thanks for letting us know. Do you still experience this in the latest VS Code Insiders with the latest WSL extension?

**Comment by paamonim** [comment]
I figured that the problem was with the* NEW ruby lsp* plugin. So I
uninstalled it, and then installed the *previous Ruby* plugin that is
deprecated, and the problem was solved.

**Comment by bamurtaugh** [comment]
Thanks for letting us know! I'll close this issue then.
