### ISSUE TITLE
Can't convert jupyter notebook on remote, python extension crashes

### ISSUE THREAD

**Issue by rbavery** [microsoft/vscode-remote-release#910]
Issue Type: <b>Bug</b>

I've opened a connection to vscode on an azure vm where I have rsynced some notebooks. I'm trying to open a notebook and import it but it looks like the extension crashes, see traceback from the Developer Tools.

To reproduce, start the Azure Data Science VM, open a connection using the latest stable versions of vscode and the pyhon extension, right click on a .ipynb file and try to import it. Nothing happens but the traceback shows the extension has crashed.

/usr/share/code/resources/app/out/bootstrap-window.js:5 [uncaught exception]: Error: Cannot read property 'reprocess' of undefined

TypeError: Cannot read property 'reprocess' of undefined
    at w.onDefaultConfigurationChanged (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4252:688)
    at _register.p.Registry.as.onDidUpdateConfiguration.e (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4245:211)
    at d.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:79:760)
    at h.registerConfigurations (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:1456:242)
    at h.registerConfiguration (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:1455:936)
    at u.getDefaultTerminalLinuxReady.then.e (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4083:43)
onUnexpectedError @ /usr/share/code/resources/app/out/bootstrap-window.js:5
/usr/share/code/resources/app/out/bootstrap-window.js:5 Error: Cannot read property 'reprocess' of undefined

TypeError: Cannot read property 'reprocess' of undefined
    at w.onDefaultConfigurationChanged (/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4252)
    at _register.p.Registry.as.onDidUpdateConfiguration.e (/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4245)
    at d.fire (/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:79)
    at h.registerConfigurations (/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:1456)
    at h.registerConfiguration (/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:1455)
    at u.getDefaultTerminalLinuxReady.then.e (/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4083)
    at setTimeout (/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:33)
onUnexpectedError @ /usr/share/code/resources/app/out/bootstrap-window.js:5
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3343 [Extension Host] debugger listening on port 56332
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4377 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: vscode-remote://ssh-remote%2Bcropmask-gpu/home/ryan/.vscode-server/extensions/redhat.vscode-yaml-0.4.1/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///usr/share/code/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json
register @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4377
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4377 Overwriting grammar scope name to file mapping for scope source.json.
Old grammar file: vscode-remote://ssh-remote%2Bcropmask-gpu/data/home/ryan/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/extensions/json/syntaxes/JSON.tmLanguage.json.
New grammar file: file:///home/rave/.vscode/extensions/ct6502.idl-1.4.0/syntaxes/json-task/JSON.tmLanguage
register @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4377
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:1413   ERR Error: [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/home/ryan/work/CropMask_RCNN/.vscode'
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3341 Extension Host
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3341 Debugger attached.
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:1560 An error occured while trying to reconnect:
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:1560
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:1560 Error: handshake timeout
    at setTimeout (/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:1555)
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:1560
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3206 Extension host terminated unexpectedly. Code:  0  Signal:  null
_onExtensionHostCrashed @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3206

Extension version: 0.44.0
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 4.15.0-54-generic
Remote OS version: Linux x64 4.15.0-1050-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 4161)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.61GB (2.30GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: cropmask-gpu|
|OS|Linux x64 4.15.0-1050-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (2 x 2294)|
|Memory (System)|7.77GB (6.87GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment]
@qubitron can you help to narrow this issue down please.

**Comment by qubitron** [comment]
@microsoft/pvsc-team to help

**Comment by rchiodo** [comment]
I don't think this is a python extension problem. We have no 'reprocess' call in our code. Unless that's just a symptom of the python extension crashing.

@rbavery if you go to Help | Toggle Developer Tools, and look at the console tab is there any other information?
