### ISSUE TITLE
devcontainer - extensions are not installed 

### ISSUE THREAD

**Issue by borjamunozf** [microsoft/vscode-remote-release#9100]
- VSCode Version: 1.82.2
- Local OS Version:  Ubuntu 20.04 WSL
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Containers/WSL

Reopen this issue #9040 because it was closed after _non-activity_. I went on holidays.

- Logs: uploaded Show Container log. [devcontainer extensions not installed.txt](https://github.com/microsoft/vscode-remote-release/files/12885004/devcontainer.extensions.not.installed.txt)
I have been working with VSCODE since last year and I have tried devcontainer to install the extensions for a while, but no release has fixed this yet for me.

![imagen](https://github.com/microsoft/vscode-remote-release/assets/25910927/1f86d6d9-264b-49ca-9f27-41ec9fddebda)
Steps to Reproduce:

1. Tested with Default profile & different extensions.
2. Create devcontainer.json with any extension (manually added in my case)
```json
{
    "name": "test-extensions",
    "build": {
        "dockerfile": "Dockerfile",
        "args": {
                "USERNAME": "${localEnv:USER}",
                "USER_UID": "1000"
        }
},
    "customizations": {
        "vscode": {
                "extensions": [
                        "ms-vscode.cpptools-extension-pack",
                        "ms-vscode.cpptools"
                ]
        }
    }
}

```
3. Open folder with Container.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
@borjamunozf Could you rebuild the container and append the log from that? (Extensions are only installed for new dev containers. The log you uploaded shows the log from an existing container, so it doesn't help determining what went wrong.)

**Comment by borjamunozf** [comment]
I thought I did that before. Seems that is fixed :) thanks, sorry for the stupid issue.


> @borjamunozf Could you rebuild the container and append the log from that? (Extensions are only installed for new dev containers. The log you uploaded shows the log from an existing container, so it doesn't help determining what went wrong.)
