### ISSUE TITLE
after last updating remote SSH connection lost a few times per hour

### ISSUE THREAD

**Issue by tonic12** [microsoft/vscode-remote-release#911]
I'm use vscode for remote developing on my dev server, but after last updating remote connection losting a few times per hour. I'm thinked it's my wi-fi connection, but when i change it to ethernet problem repeated. Dev server in LAN with me, it's not connection problem.

**Comment by mykter** [comment]
You might have run into #246, which hasn't been diagnosed.

**Comment by tonic12** [comment]
Yes, you right! It looks like [#246 ](https://github.com/microsoft/vscode-remote-release/issues/246).
