### ISSUE TITLE
Ripgrep process causing CPU slow downs if host cannot access files crated by dev container

### ISSUE THREAD

**Issue by aminya** [microsoft/vscode-remote-release#9110]
Type: <b>Bug</b>

I have a repository with `.devcontainer.json` at the root. When I open the repository (without the dev container running). The Ripgrep process uses 100% of the CPU consistently. 

It seems it is searching for the devcontainer files. I found the issue by doing an extension bisect. 

![image](https://github.com/microsoft/vscode-remote-release/assets/16418197/a06df996-63f6-486b-bb73-eada3e5cec7d)

Here is `.devcontainer.json` in case it helps (although I didn't actually open the dev container!)
```json
{
    "name": "Dev Container",
    "dockerComposeFile": "${localWorkspaceFolder}/docker-compose.yaml",
    "service": "app",
    "workspaceFolder": "/home/aminya/",
    "remoteUser": "aminya",
    "features": {
        "ghcr.io/devcontainers/features/common-utils:2": {
            "configureZshAsDefaultShell": true
        }
    },
    "customizations": {
        "vscode": {
            "extensions": [
				"BazelBuild.vscode-bazel",
				"janisdd.vscode-edit-csv",
				"llvm-vs-code-extensions.vscode-clangd",
				"ms-vscode-remote.remote-containers",
				"ms-vscode.cmake-tools",
				"ms-vscode.cpptools",
				"pustelto.bracketeer",
				"smilerobotics.urdf",
				"stackbuild.bazel-stack-vscode",
				"twxs.cmake",
				"vadimcn.vscode-lldb",
				"josetr.cmake-language-support-vscode",
				"cheshirekow.cmake-format",
				"GitHub.copilot",
				"GitHub.copilot-chat",
				"GitHub.copilot-labs"
			]
        }
    }
}

```

Extension version: 0.318.0
VS Code version: Code - Insiders 1.84.0-insider (4678919d52909efc7c4ab958a2e5c8f45d50ffc3, 2023-10-13T05:33:39.403Z)
OS version: Linux x64 6.2.0-34-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 3599)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 8, 10|
|Memory (System)|30.97GB (25.74GB free)|
|Process Argv|/home/aminya/Gitlab/robodrake|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

I verified that the issue happens on stable VsCode as well.

**Comment by aminya** [comment]
I also get this error in the output logs in case it is related:
```js
2023-10-19 10:17:06.553 [error] d.actions is not iterable: TypeError: d.actions is not iterable
    at i.f (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:783:9209)
    at i.c (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:783:8990)
    at c.a (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:783:8833)
    at c.d (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1538:1900)
    at c.setHandler (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1538:1773)
    at new i (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:783:8784)
    at g.j (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:640:1241)
    at g.createInstance (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:640:733)
    at new o (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1579:67787)
    at g.j (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:640:1241)
    at g.createInstance (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:640:733)
    at y.k (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1579:62978)
    at d (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1579:62760)
```

**Comment by aminya** [comment]
I have fixed the issue by adding this to my `.vscode/settings.json`. So, I am pretty sure ripgrep is stuck in a symlink loop created by Bazel.

```json
  "files.exclude": {
    "**/.git": true,
    "**/.cache": true,
    ".idea/": true,
    "external/": true,
    "bazel-*/": true,
    "install/": true,
    "**/build": true,
  }
```

**Comment by BurntSushi** [comment]
ripgrep does check for loops created by symlinks and should avoid an infinite loop. With that said, symlinks can dramatically increase the size of the directory tree and result in very long traversal times.

**Comment by aminya** [comment]
Is there a way that I can make ripgrep more verbose to realize what is it stuck on? If not possible, is there a tool to monitor the Linux disk system calls while ripgrep is searching

**Comment by BurntSushi** [comment]
You can try `--trace`, but that may generate too much output. Other tactics available:

* Search smaller parts of your directory tree to see if you can isolate a particularly problematic sub-tree. (This assumes such a tree exists. It's possible that it's just death by a thousand cuts, but in my experience, there's usually one particularly deep cut.)
* Old fashioned printf debugging. ripgrep isn't hard to build. You just need `cargo`.

**Comment by aminya** [comment]
OK, It is the `external` folder added by Bazel-compiler-command-extractor. Inside that folder, there are huge number of files that do not exist (invalid symlink files).

I ran the rg command that VsCode uses
```bash
 /usr/share/code-insiders/resources/app/node_modules.asar.unpacked/@vscode/ripgrep/bin/rg --hidden -case-sensitive --no-require-git -g "{.devcontainer.json,.devcontainer/devcontainer.json/.devcontainer/*/devcontainer.json}" --no-ignore --follow --no-config --no-ignore-global
```
```
./external/test/bazel-test/external/boost/bazel-bin/test.runfiles/test.txt: No such file or directory (os error 2)
# the error is repeated many times
```


That's why adding `external` and `bazel-*` fixes the issue.

```json
  "files.exclude": {
    "**/.git": true,
    "**/.cache": true,
    ".idea/": true,
    "external/": true,
    "bazel-*/": true,
    "install/": true,
    "**/build": true,
  }
```

**Comment by BurntSushi** [comment]
Can you try passing `--no-messages`? I wonder if the extreme number of errors is causing pathologically slow behavior by printing so much to stderr.

More generally though, if your tooling is creating trees with large numbers of broken symlinks then perhaps that tooling ought to be fixed.

**Comment by iamGavinJ** [comment]
This is also happening on a non-containerised host; Just a raw SSH remote connection to a folder:
![Monosnap - 2023-11-11 10-26-59](https://github.com/microsoft/vscode-remote-release/assets/15910740/fa2013d0-1225-455e-9084-9b602d7f151c)

I haven't tried altering `files.exclude` yet.

**Comment by aminya** [comment]
The main issue is that VsCode forces ripgrep to search in gitignored folders! I don't know which extension sets these flags for ripgrep.

**Comment by SoonIter** [comment]
😢Many of our developers have encountered this issue in the repository of https://github.com/web-infra-dev/rspack. 
<img width="597" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/79413249/58539e08-2b68-4bfd-a07e-d4fd5aeafb8f">

**Comment by chrmarti** [comment]
`rg` doesn't prune its tree traversal based on inclusion rules like `/{.devcontainer.json,.devcontainer/devcontainer.json,.devcontainer/*/devcontainer.json}`.

I'm improving the search for devcontainer.json files now in https://github.com/microsoft/vscode-remote-release/issues/9738.
