### ISSUE TITLE
remote-wsl.explorer.addDistro 错误

### ISSUE THREAD

**Issue by jingxizhu** [microsoft/vscode-remote-release#9111]
Type: <b>Bug</b>

运行命令 remote-wsl.explorer.addDistro 错误: command 'remote-wsl.explorer.addDistro' not found。这可能是由提交 remote-wsl.explorer.addDistro 的扩展引起的。

Extension version: 0.81.8
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (20.31GB free)|
|Process Argv|--crash-reporter-id 5c0cb483-431b-4301-81af-229369fd6c6b|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30841074
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pythonregdiag:30859691

```

</details>

**Comment by Abrillant-Lee** [comment]
运行命令 _cl.eide.project.historyRecord 错误: command '_cl.eide.project.historyRecord' not found。这可能是由提交 _cl.eide.project.historyRecord 的扩展引起的。
![image](https://github.com/microsoft/vscode-remote-release/assets/129536239/1de92c57-0593-485a-a01a-8b47d65a4184)
如何解决

**Comment by echo567** [comment]
更新下vscode为最新版 或者 重装下vscode

**Comment by lhyscau** [comment]
> 更新下vscode为最新版 或者 重装下vscode

亲测有效，重装vscode

**Comment by 2mulin** [comment]
我也遇到了相同问题, 一种临时解决方法是使用Windows Terminal连接上wsl, 然后使用code指令打开指定工作区, 例如我这里打开blog工作区:
```shell
cd blog
code ./
```

**Comment by DogeFlow** [comment]
same issue

**Comment by tonychen0924** [comment]
> 更新下vscode为最新版 或者 重装下vscode

我怎么重装了以后还是一样。。。。。

**Comment by aeschli** [comment]
Can you give more detail how you get this?
- is the window a remote window? Connected to tunnels, SSH, WSL
- you open the remote explorer, select WSL, and click on 'Add Distro' ?
