### ISSUE TITLE
WSL: run server with a startup script

### ISSUE THREAD

**Issue by quantokratos** [microsoft/vscode-remote-release#912]
- VSCode Version: 1.36.0
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu
- Remote - WSL Extension Version: 0.38.1 - 0.38.7
- Remote Extension/Connection Type: WSL

To access the remote repository via public key authentication I load the key into my authentication agent in Windows (Pageant) and make sure it is accessible from WSL using weasel-pageant. The relevant key is then accessible from any WSL terminal as can be checked with `ssh-add -l`. It also works perfectly fine when calling e.g. `git pull` in a terminal from within VSCode.

Up to (and including) version 0.38.0 of the extension all the git commands also worked perfectly fine when calling them from VSCode directly. However, now the following fails:

Steps to Reproduce:
1. Load key in Pageant 
2. Open VS Code, open remote wsl
3. Open folder under source control (git)
4. Open source control from side bar (recognizes git)
5. Choose e.g. Pull from menu

Result:
```
> git pull --tags origin some-branch
git@gitlab.***.***: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

All local git operators work perfectly fine.

**Comment by aeschli** [comment]
The problem is that you rely on `weasel-pageant` being run when the server starts.
We used to start the server in an interactive login shell, but no longer do.

**Comment by easeev** [comment]
Have similar issue https://github.com/microsoft/vscode-remote-release/issues/985

**Comment by aeschli** [comment]
In 0.39.7 (requires latest insiders), we now have allow users to specify a script that is run on server startup: ~.vscode-server-insiders/server-env-setup

Note that this must be a `sh` script.
