### ISSUE TITLE
Not compatible with VS Code '1.79.2'

### ISSUE THREAD

**Issue by KevinChngJY** [microsoft/vscode-remote-release#9122]
How can i find the version which compatible with VS Code 1.79.2. I have no clue for it.

**Comment by sungho-cho** [comment]
Same here, except it's incompatible with VS Code 1.83.1

**Comment by bamurtaugh** [comment]
What extension are you looking to install? And is there a reason you can't updated to the latest VS Code? We recommend using the latest VS Code and versions of the remote extensions for the best experience - things may not work properly in older versions.

**Comment by KevinChngJY** [comment]
I'm working on a confidential project which the environment don't have internet connection... I have to transferred the VS code installer and plugin to the environment...Last time the VS code i transferred is 1.79.2. Does it mean if I transfer the latest VS code and latest plugin should be workable?

**Comment by bamurtaugh** [comment]
Thanks for the info. Yes, using the latest version of VS Code and the extension(s) you have in mind should work.

Are you still experiencing any issues?
