### ISSUE TITLE
Problem with DEV Containers and new release of VSCode

### ISSUE THREAD

**Issue by JNaranjo-Alcazar** [microsoft/vscode-remote-release#9130]
- Extension version:  0.315.0
- VSCode Version: 1.83.0
- OS: Ubuntu

Steps to Reproduce:

Dear community, in previous versions of VSCode I connected to a Host with the plug in. Then, inside the new VSCode window connected to the host I connected to a docker with the same plug in by clicking: "Attach to running container". Now, with the new version, when I press Attach (to a docker), the launched containers don't appear and it's like the window restarts.

Has this been fixed in any version of Dev Containers?

**Comment by chrmarti** [comment]
Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)
