### ISSUE TITLE
Allow to open a tunnel with an API token

### ISSUE THREAD

**Issue by jjcasmar** [microsoft/vscode-remote-release#9132]
When creating a tunnel in VSCode, it requires to log into github and insert a numeric code. It would be nice if it was possible to use an API token to be able to automate the creation of tunnels. 

That way, it would be possible to create a docker image which open a tunnel without user intervention

**Comment by connor4312** [comment]
Please check out the `code tunnel user login` command. You can pass an access token there. Note that the access token would need to be a valid token created by VS Code or the CLI before, or at least under the VS Code app ID.

**Comment by jjcasmar** [comment]
Ill test this, thanks!

**Comment by jjcasmar** [comment]
@connor4312  Could you explain how to create the access token?

**Comment by connor4312** [comment]
Actually it looks like the dev tunnel CLI is now public. So the way to go is to create a tunnel using the [dev tunnels CLI](https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/cli-commands), after signing in with your preferred GH/MSA account, and create a token with the `connect`, `manage`, and `host` permissions on the tunnel. Then it can be hosted with the command `code tunnel --tunnel-id=<tunnel.id> --host-token=<token> --name=<preferred-tunnel-name>`.
