### ISSUE TITLE
Wrong keyboard layout

### ISSUE THREAD

**Issue by adalseno** [microsoft/vscode-remote-release#9136]
- VSCode Version: 1.83.1
- Local OS Version: Mac Os X 10.15
- Remote OS Version: Chrome Os 118.0
- Remote Extension/Connection Type: Server
-
I am using Vscode server running on a Mac and accessed via Browser (Chrome) on a Chromebook. It works fine, but the keyboard layout is detected as "es" instead of Italian ("it"). 
![Screenshot 2023-10-26 00 46 44](https://github.com/microsoft/vscode-remote-release/assets/2405291/16df2115-964b-48c3-beb9-7525e402da54)

The UI language is correctly set to Italian. I tried to change the layout in the settings but without any luck.
![Screenshot 2023-10-26 00 36 24](https://github.com/microsoft/vscode-remote-release/assets/2405291/2999a4b8-60ff-445b-8a9b-9a93395f234e)
Switching from "autodetect" to "it" has no effect even after reloading.

On the Chromebook, as well as on the Mac, the Keyboard is set to Italian:
![Screenshot 2023-10-26 00 43 26](https://github.com/microsoft/vscode-remote-release/assets/2405291/77a11442-437b-46f9-82ca-c8c1e96eedf5)

So far, the different layout hasn't given me any problems, but I would like to fix it. In the menu, the "it" layout is not available.
![Screenshot 2023-10-26 00 49 23](https://github.com/microsoft/vscode-remote-release/assets/2405291/c6a8509f-2d99-4bda-b528-0faaee660075)

If I try with Firefox or Vivaldi (linux-based on the Chromebook) the layout is set to us.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by ulugbekna** [comment]
Do you mean that you open vscode.dev and see the layout detected as `es`? 

Also, what do you mean by vscode server? Do you mean a vscode tunnel?
