### ISSUE TITLE
Asked for password twice when not using ExecServer

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#9142]
When Remote-SSH is not using the ExecServer and Dev Containers (which is always using the ExecServer) is installed, I'm asked twice for the SSH password. Enabling the ExecServer for Remote-SSH or uninstalling Dev Containers reduces this to one.

Is there a good way to fix this? Or can we enable the ExecServer for Remote-SSH in stable by default (my understanding is it is only enabled in Insiders)?

**Comment by chrmarti** [comment]
Related: https://github.com/microsoft/vscode-remote-release/issues/9077

**Comment by connor4312** [comment]
Exec server is now enabled for stable
