### ISSUE TITLE
@Chuxel How does one create a `/workspaces` folder in order to add it to the shared folders list? Docker Desktop preferences won't let me add the path that doesn't exist, and `sudo mkdir /workspaces` says `mkdir: /workspaces: Read-only file system`.

### ISSUE THREAD

**Issue by Dzivo** [microsoft/vscode-remote-release#9148]
@Chuxel How does one create a `/workspaces` folder in order to add it to the shared folders list? Docker Desktop preferences won't let me add the path that doesn't exist, and `sudo mkdir /workspaces` says `mkdir: /workspaces: Read-only file system`.

_Originally posted by @mrmachine in https://github.com/microsoft/vscode-remote-release/issues/5808#issuecomment-965959627_
 
Currently i have the same problem as mentioned here i am unable to create /workspaces folder on mac. 

I get this error when trying to Clone Repository into named container
```
The path /workspaces/MyProject is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
```

**Comment by chrmarti** [comment]
Please see https://github.com/microsoft/vscode-remote-release/issues/5388#issuecomment-1259437096 for a workaround.
