### ISSUE TITLE
Shell integration failed to activate (zsh)

### ISSUE THREAD

**Issue by tekumara** [microsoft/vscode-remote-release#9150]
Type: <b>Bug</b>

Shell integration failed to activate

Extension version: 0.106.5
VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 23.0.0
Modes:
Remote OS version: Linux x64 5.15.0-1047-aws
Remote OS version: Linux x64 5.15.0-1036-aws
![CleanShot 2023-10-30 at 18 34 24@2x](https://github.com/microsoft/vscode-remote-release/assets/125105/17f7c70e-e97b-498b-89ac-9418f1c4fa8a)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 7, 10|
|Memory (System)|32.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id 1420092c-d4ca-4cab-85bb-af47402199b1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev-oliver-compute|
|OS|Linux x64 5.15.0-1047-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (4 x 2499)|
|Memory (System)|15.43GB (14.09GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev-oliver-delme-compute|
|OS|Linux x64 5.15.0-1036-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (4 x 2499)|
|Memory (System)|15.44GB (14.62GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythoncet00cf:30874137
2e7ec940:30870395
pythontbext0:30864172

```

</details>

**Comment by tekumara** [comment]
I can't find any relevant logs in the Output panes (they produce nothing went I open the terminal). Is there somewhere else I can look?

**Comment by meganrogge** [comment]
In order for shell integration to work, you'll need to use a `zsh` login shell. Have you set the `zsh` profile to explicitly just use `-i` for the args? Changing that to `-l` should fix it.

**Comment by tekumara** [comment]
Thanks for your response. `zsh -i` doesn't appear to be set anywhere. I have:

```
❯ env | grep -i SHELL
SHELL=/usr/bin/zsh
```

And am using the unset default for `terminal.integrated.defaultProfile.linux`, eg:

![CleanShot 2023-11-01 at 11 27 35@2x](https://github.com/microsoft/vscode-remote-release/assets/125105/f710129a-84e0-4bbf-994f-663b306a0aa2)

If I choose `zsh` rather than `null` (ie: automatically detect the default) the issue remains. 

FYI - I don't have this problem locally, just remotely.

**Comment by meganrogge** [comment]
I've seen issues like this happen when there's a permissions issue - do you know if that path is protected?

**Comment by tekumara** [comment]
It's owned by root, but I can read and execute it as non-root:
```
❯ ll /usr/bin/zsh
-rwxr-xr-x 1 root root 858K Mar 11  2022 /usr/bin/zsh
```

**Comment by tekumara** [comment]
FYI if I run the shell integration manually in the terminal after starting it, it runs and activates without failure:
```
[[ "$TERM_PROGRAM" == "vscode" ]] && . "$(code --locate-shell-integration-path zsh)"
```

**Comment by Tyriar** [comment]
Our logging here isn't the greatest as we try to do the minimum possible and revert to an untouched terminal if it's not possible. Unless you want to look into the [shell integration script](https://github.com/microsoft/vscode/blob/8db902c64c2d6ce1dd19340336df0da35e3b802a/src/vs/workbench/contrib/terminal/common/scripts/shellIntegration-rc.zsh) and debug to figure out where it failed, I'd say just run with the manual install method if that's working for you.

Something someone on the team hit recently was they had powerlevel10k which is incompatible with our shell integration and they explicitly turn it off. So you could be seeing that.

**Comment by tekumara** [comment]
I too am using powerlevel10k ... I wonder if there's an interaction there.

**Comment by Tyriar** [comment]
@tekumara yes, they turn out shell integration off in favor of theirs which misses some of the features we need (like command line reporting)
