### ISSUE TITLE
Group Remote Hosts in Remote Explorer

### ISSUE THREAD

**Issue by davidnnaji** [microsoft/vscode-remote-release#9157]
I'd like to request the ability to group remotes using a directory structure. This feature is useful when you begin to accumulate remote hosts (i.e. 60+ hosts and counting). For example, suppose I have a list of hosts in remote explorer:

```
Host_1
Host_2
Host_3
...
Host_n
```

I'm looking to have this:

```
myLocation1
  Host_1
myLocation2
  Host_2
  Host_3
...
```

I'd like to edit my .ssh\config file as follows (or something similar):
```
Location1
    Host Host_1
        HostName 192.168.100.1
        User gatt
Location2
    Host Host_2
        HostName 192.212.77.1
        User gatt
    Host Host_3
        HostName 192.212.77.2
        User gatt
```

Related feature request(s) I found:
[#3617](https://github.com/microsoft/vscode-remote-release/issues/3617)

**Comment by roblourens** [comment]
I don't think that a vscode extension should be trying to extend the ssh config. You might look at the `remote-explorer.foldersSortOrder` setting and try some naming scheme, and sort remotes alphabetically, that might help
