### ISSUE TITLE
When connect to host, allow user to connect with ssh args, without having to save it to ssh/config 

### ISSUE THREAD

**Issue by BossaMelon** [microsoft/vscode-remote-release#9158]
![27111680-1e39-45b6-82bf-a7dde11b7351](https://github.com/microsoft/vscode-remote-release/assets/38517713/44a1bd5c-f988-4e95-ade4-6fd30794a1cd)

Hello, 
Firstly thanks a low for all the work developing such a great tools for remote developing. 
I faced with a problem that, my workflow need to login worker nodes with difference port, because the node is assignde by slurm server with a random port. If every time I have to save the ssh config to file, my ssh config file will contains too many entries which will only be used once. I would like to ask for a feature that can directly ssh to remote with different port without saving it to ssh/config then connect.

Much appreciate!
Best
Yuehao

**Comment by roblourens** [comment]
You don't have to safe it to a file. You can connect directly to what you entered by selecting that entry in the picker. Does that not work for you?
