### ISSUE TITLE
allow devcontainers to work with Finch

### ISSUE THREAD

**Issue by kidbrax** [microsoft/vscode-remote-release#9162]
Allow devcontainers to replace Docker with [Finch](https://github.com/runfinch/finch).

Or more specifically, for now the issue seems to be the way vscode gets the docker version. It currently uses 'version --format {{.Server.APIVersion}}'. That command format is not available in Finch. If we could alter the specific command it uses to get the version, Finch "might" work

**Comment by weikequ** [comment]
I did some investigation [here](https://github.com/runfinch/finch/issues/387) by altering & recompiling finch to output a APIVersion, but in the end, it seems like we might be blocked by the docker socket requirement. See issue linked above.

**Comment by benbridts** [comment]
this is now supported on the finch side: https://runfinch.com/docs/integrations/mac/devcontainers/

**Comment by chrmarti** [comment]
@benbridts Great, thanks!

I guess this issue can be closed then?
