### ISSUE TITLE
Remote connection doesn't respect .bashrc at startup

### ISSUE THREAD

**Issue by krzikalla** [microsoft/vscode-remote-release#9165]
Default git version on the remote side is 1.8. In my .bashrc there is a `module load git` line to activate a more recent version. This works for remote terminals inside VS Code. However, the VS Code git itself still uses git version 1.8. There seems to be no way to properly configure the remote startup of VS Code.

**Comment by chrmarti** [comment]
Is this with Remote-SSH?

**Comment by krzikalla** [comment]
Yes. Client is windows, remote is linux.

**Comment by paroj** [comment]
seems the same as #7834

**Comment by chrmarti** [comment]
@paroj If you see this with Dev Containers, could you open a new issue? This issue here is for Remote-SSH. Thanks!

**Comment by joshspicer** [comment]
IF anyone is interested in support for this scenario, please create a new issue and be sure to share both your Remote - SSH connection log, as well as a clear repro for the bug you are reporting. That will make it possible for us to provide suggestions - thanks!
