### ISSUE TITLE
node not found error so container could not started

### ISSUE THREAD

**Issue by karatashakan** [microsoft/vscode-remote-release#9168]
I am trying to setup devcontainer [typescript-node template](https://github.com/devcontainers/templates/tree/main/src/typescript-node) . I receiving the following error. If I don't use dockerComposeFile property and use image property in devcontainer.json, there is no problem. I have cleared all caches and tried again, result has failed. I attached the entire log file to this issue. When I tried [devcontainers php template](https://github.com/devcontainers/templates/tree/main/src/php) with dockerComposeFile property, there is no problem and everything is OK. Someone had opened almost same issue #6850 

- VSCode Version: 1.84.0
- Local OS Version: Windows 10 Pro 22H2
- Remote OS Version: mcr.microsoft.com/devcontainers/typescript-node:1-18-bullseye
- Remote Extension/Connection Type: Containers

Steps to Reproduce:

1. Create devcontainer.json, docker-compose.yml and Dockerfile.
2. Set dockerComposeFile property to ["../docker-compose.yml"] in devcontainer.json.
3. Set service and workspaceFolder in devcontainer.json.
4. Set docker-compose.yml file with required configuration.
5. Write this, "FROM mcr.microsoft.com/devcontainers/typescript-node:1-18-bullseye" to Dockerfile.
6. Rebuild Without Cache and Reopen in Container

- Logs:
`Host server: /bin/sh: /root/.vscode-remote-containers/bin/d037ac076cee195194f93ce6fe2bdfe2969cc82d/node: not found`

[remoteContainers-2023-11-04T00-20-43.852Z.log](https://github.com/microsoft/vscode-remote-release/files/13255480/remoteContainers-2023-11-04T00-20-43.852Z.log)

**Comment by chrmarti** [comment]
Make sure your container doesn't stop by either adding `command: sleep infinity` to your docker-compose.yml or setting `"overrideCommand": true` in the devcontainer.json.
