### ISSUE TITLE
VS Code's tsserver was deleted by another application...

### ISSUE THREAD

**Issue by OmriSama** [microsoft/vscode-remote-release#917]
Issue Type: <b>Bug</b>

On the latest Insider version, I get the `VS Code's tsserver was deleted by another application such as a misbehaving virus detection tool. Please reinstall VS Code` issue. This just started happening today on the latest Insider version.

I can confirm this doesn't happen with the latest version when not using Remote SSH.

Extension version: 0.44.0
VS Code version: Code - Insiders 1.37.0-insider (bbfd565b1be08703831d261859955c4fd188b555, 2019-07-05T15:42:24.267Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 5.0.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1603 v4 @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|

|Item|Value|
|---|---|
|Remote|SSH: ubuntu|
|OS|Linux x64 5.0.0-20-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-1603 v4 @ 2.80GHz (4 x 2793)|
|Memory (System)|13.60GB (9.48GB free)|
|VM|100%|
</details>

**Comment by bterlson** [comment]
+1, getting same error starting today.

**Comment by roblourens** [comment]
This will be fixed in the next Insiders update
