### ISSUE TITLE
(Error: Cannot read properties of undefined (reading 'closeRemote')) - when cloning a Github repository in a container volume within a Remote - SSH session

### ISSUE THREAD

**Issue by ioExpander** [microsoft/vscode-remote-release#9171]
Type: <b>Bug</b>

I cannot clone any new repository in a dev container when connected with SSH to a remote Debian server. The error message displayed is : 

`Failed to connect to the remote extension host server (Error: Cannot read properties of undefined (reading 'closeRemote'))`

Openinig existing repositories in their containers on that same server work fine. Those were cloned using that same method in vscode a few weeks ago with no issues.

Cloning the same repositories in a dev container on my local docker (Rancher Desktop VM) works fine. The issue occurs only when connected in ssh which is why I've opened it on the Remote - ssh plugin.

Some investigations I did : 
- using pre release versions of the remote - ssh and remote - dev containers plugins. Same error
- I have tried remoting on a servers Debian 11/12 and Ubuntu 23.10 with no luck.
- The issue is also present on the vscode insiders.

Error logs : 

<img width="813" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/1975648/da869fc6-a946-4022-83ab-e66995c281d9">

<img width="813" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/1975648/27c0480d-93b8-4ec2-8576-3804e7631314">

Extension version: 0.107.0
VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:29:51.160Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id b407decd-5d39-423c-a7b5-53763d696dea|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
vscrp:30673768
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss2:30879913
pythonmypyd1:30879173
pythoncet00cf:30874137
pythontbext0:30879054
dsvsc016cf:30880770
dsvsc018cf:30880895

```

</details>

**Comment by ioExpander** [comment]
As a workaround one can use docker contexts pointing to the remote server's docker daemon and clone the repository from there : 
```shell
docker context create my-remote-server --docker "host=ssh://username@remote-server:port"
docker context switch my-remote-server
```

From there clone the repo in a dev container volume in vscode.
Once create,  it is possible to reopen it using the regular remote ssh -> dev container method.

**Comment by wanmyj** [comment]
@ioExpander Just want to let you know that I had the exact same issue with you showing error of `(reading 'closeRemote')`.
My environment is VSCode remoting to Ubuntu 22.04.
It turned out that the problem was due to `the latest VSCode version 1.84`. 
I am not sure on which version this issue starts, but the version of `1.66` works fine with me. You can try to downgrade VSCode to workaround this issue.

**Comment by canghai118** [comment]
I'm experiencing the exact same issue here. I use devcontainer every day, and it bothers me a lot.

**Comment by canghai118** [comment]
> I'm experiencing the exact same issue here. I use devcontainer every day, and it bothers me a lot.

After downgrading to version 1.83.1, it works again.   

However, after reinstalling version 1.83.1, all related plugins must also be reinstalled due to compatibility issues. 
  
The most important step is to kill the VS Code Server on the Remote Host.   

Doing this ensures that the next time you connect to the remote, it will automatically download and install the correct version on the remote server."
![image](https://github.com/microsoft/vscode-remote-release/assets/3394863/51221297-bf0a-44dc-acbd-c052a0d22aec)

**Comment by chrmarti** [comment]
Fixing with https://github.com/microsoft/vscode-remote-release/issues/9249.
