### ISSUE TITLE
Host key verification - better UX please

### ISSUE THREAD

**Issue by inspector71** [microsoft/vscode-remote-release#9172]
When a remote domain or server changes, subsequent connection attempts from VS Code will be refused due to a mismatch between the hosts identification key and the domain stored along with it in the `.ssh/known_hosts` file. One error received could be:

`Remote host key has changed, port forwarding is disabled`

The error is misleading in that it's not always the actual key data that has changed, but the pairing of that key data with a domain in the `.ssh/known_hosts` file. The combination of which 'has changed'.

I found this SO page helpful

https://stackoverflow.com/questions/64758096/how-to-confirm-a-new-remote-host-key-in-visual-studio-code-remote-ssh-extensio

Using PuTTY this is a simple enough issue to resolve. Usually the corresponding line in the `.ssh/known_hosts` file is deleted and the next connection attempt prompts for acceptance of the key, which unless the user fears a MITM attack, they just accept and along you go with your day.

In VS Code there seems to be an absence of helpfulness for solving this. The terminal pops open with chunks of text feedback from OpenSSH (presumably) but there's no dialog or helpful suggestions at the end of the OpenSSH feedback for how to solve the issue.

I cannot find any reference to this problem in the troubleshooting or other SSH documentation either.

In the May 2023 release notes, there is a dialog screenshot that would be great UX to see in this situation, but only seems to apply to local UNC connections:

https://code.visualstudio.com/updates/v1_79#_windows-unc-host-allowlist-improvements

Something like this would be great for working with remote servers, files.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/4683
