### ISSUE TITLE
Cannot attach to running container if .ssh is read only

### ISSUE THREAD

**Issue by hsandmeyer** [microsoft/vscode-remote-release#9178]
When attaching to a running, remote container via context menu, the `~/.ssh/know_hosts` is copied to the container. However, in my case, `~/.ssh`  is mounted read only from the host system. Thus, `known_hosts` can't be copied and attaching to the container fails.
Note that I connect to the remote machine via the ssh-extension first. Then, I try to connect via the context menu in the docker pane. The same issue happens when using a [docker context](https://code.visualstudio.com/docs/containers/ssh) to directly connection from my local machine.
This happens with the insiders version as well. As a workaround, I tried to remove my local `~/.ssh/known_hosts` before attaching to the container. This way, there is nothing to copy. This works indeed and I can attach VSCode to the running container

- VSCode Version: 1.83.0
- Local OS Version: Ubuntu 22.04
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Docker

Here are the relevant logs:
```
Start: Run in container: # Copy /home/hsandmeyer/.ssh/known_hosts to /home/gpu/.ssh/known_hosts
[3812 ms] 
[3813 ms] /bin/sh: 26: cannot create /home/gpu/.ssh/known_hosts: Read-only file system
[3813 ms] Exit code 2
[3814 ms] /home/gpu
[3814 ms] 
[3819 ms] Command in container failed: # Copy /home/hsandmeyer/.ssh/known_hosts to /home/gpu/.ssh/known_hosts
(dd iflag=fullblock bs=8192 count=10 2>/dev/null; dd iflag=fullblock bs=4616 count=1 2>/dev/null) >/home/gpu/.ssh/known_hosts
[3820 ms] /bin/sh: 26: cannot create /home/gpu/.ssh/known_hosts: Read-only file system
[3820 ms] Exit code 2
```

Steps to Reproduce:

1. Create a container where  `~/.ssh` is mounted with read only rights
2. Try to attach to the running container via context menu in the Docker pane

I searched for an option not to copy the known_hosts file but did not find any. If there is one, please close

**Comment by chrmarti** [comment]
Another workaround would be to place a `known_hosts` file (can be empty) in the mounted `.ssh` folder. We first check if one exists.

I will also add a check for whether the folder is writable.

**Comment by chrmarti** [comment]
To verify (Dev Containers 0.326.0-pre-release or later):
- Verify your local `~/.ssh/known_hosts` file is still copied to the container, e.g., with the following devcontainer.json:
```json
{
	"image": "mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye"
}
```
- Verify it is not copied to the container and you can still connect to the container with an empty local folder mounted in the container:
```json
{
	"image": "mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye",
	"runArgs": ["-v", "<path to empty local folder>:/home/node/.ssh:ro"]
}
```
Make sure you rebuild the container to make the `"runArgs"` apply.
