### ISSUE TITLE
Dev Container fails to build when Docker is installed using an Ubuntu snap

### ISSUE THREAD

**Issue by nuxy** [microsoft/vscode-remote-release#9181]
While this is not a bug per se, it's something I'm pretty confident other users are experiencing when running [Remote Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) on an Ubuntu system with Docker installed via the [Snap Store](https://snapcraft.io/store).  I'm hoping by documenting this here it helps others avoid having to debug obscure errors unrelated to the action issue.

### Build failure

When launching the following `devcontainer.json` the build process fails with the following error:
```
Start: Run: docker build -f /tmp/devcontainercli-<user-name>/updateUID.Dockerfile-0.52.1 -t vsc-test-c8e23e125076b243b35b8d3ef519add529491cf07d5c6a285a9216a3d04c7877-uid --build-arg BASE_IMAGE=mcr.microsoft.com/devcontainers/typescript-node:0-18 --build-arg REMOTE_USER=node --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=root /home/<user-name>/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/devcontainercli-<user-name>: no such file or directory
```

Looking into this error further I found the **following note** in the [Docker documentation](https://docs.docker.com/engine/reference/commandline/build/#file):

> docker `build` returns a `no such file or directory` error if the file or directory does not exist in the uploaded context. This may happen if there is no context, or if you specify a file that is elsewhere on the Host system. The context is limited to the current directory (and its children) for security reasons, and to ensure repeatable builds on remote Docker hosts. This is also the reason why `ADD ../file` does not work.

With that known I attempted to run shortened version of the `docker build` command within the `/tmp/devcontainercli-<user-name>` directory and received the following error:
```
docker build -f updateUID.Dockerfile-0.52.1 -t vsc-test --build-arg BASE_IMAGE=mcr.microsoft.com/devcontainers/typescript-node:0-18 --build-arg REMOTE_USER=node --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=root
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /var/lib/snapd/void/updateUID.Dockerfile-0.52.1: no such file or directory
```

It seems that when Docker is executed it runs under a sandboxed environment thereby resulting in a failed build process.

### Solution

Uninstall the [Docker snap](https://snapcraft.io/docker) and reinstall using the following command:
```
$ apt install docker.io
```

Hope this helps.

**Comment by bamurtaugh** [comment]
Thank you for taking the time to file this! If you have a moment, would you be willing to open a PR to our dev container docs, so that others can see this solution?

**Comment by nuxy** [comment]
@chrmarti 
It would be nice if errors like this were documented in a _Troubleshooting issues_ section since an advanced user would never have read this document.  For example, there are many cases where a developer works on an existing project that has a preconfigured `devcontainer.json` so the only requirements to get up and running are installing Docker and VS Code (open in container).

That said, being able to search the issue based on the error message would have saved a lot of time.

**Comment by bamurtaugh** [comment]
> It would be nice if errors like this were documented in a Troubleshooting issues section

@nuxy If you're interested in opening a PR, perhaps an addition to https://code.visualstudio.com/docs/devcontainers/tips-and-tricks or https://code.visualstudio.com/docs/devcontainers/faq would make sense as one of these kinds of sections?

If you're able to open a PR, please feel free to tag me, and I can provide a review!

**Comment by nuxy** [comment]
Will do.  Thanks!

**Comment by nuxy** [comment]
The following message found [here](https://github.com/microsoft/vscode-docs/blob/513424f40cb523f4fac0ab4a430684377c36891c/docs/devcontainers/containers.md#L48) should be sufficient.  That said, closing this issue.
> The unofficial Ubuntu Docker snap package for Linux is not supported. Follow the [official Docker install instructions for your distribution](https://docs.docker.com/install/#supported-platforms).
