### ISSUE TITLE
Support remote containers for AzureML

### ISSUE THREAD

**Issue by Chris-hughes10** [microsoft/vscode-remote-release#9189]
When connecting to AzureML compute instances using a ssh connection, dev containers work as expected. However, when connecting to a compute instance through the AzureML portal, which is the preferred way to access the compute, dev containers don't seem to work at all. It would be great to support this connection approach.

**Comment by bamurtaugh** [comment]
Thank you for filing!

@sevillal @tbombach I think this might be a request moreso on the AML side / for an AML repo rather than here, but please lmk what you think.

**Comment by sevillal** [comment]
@bamurtaugh yes this is something it's been in our radar for some time, we have an issue open in our repo to track this: https://github.com/microsoft/vscode-tools-for-ai/issues/2062

**Comment by bamurtaugh** [comment]
Thanks!

@Chris-hughes10 let's track in the issue that @sevillal linked.
