### ISSUE TITLE
Issues with WSL distribution name

### ISSUE THREAD

**Issue by ronaldseoh** [microsoft/vscode-remote-release#919]
- VSCode Version: 1.36
- Local OS Version: Windows 10 Pro 1903 (Build 18362.207)
- Remote OS Version: Debian Linux
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Install 'Remote - WSL' extension.
2. Attempt to open a new Remote - WSL window.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes. I've tried reinstalling VSCode with just this 'Remote - WSL' extension installed.

I've been trying to make use of this WSL remote functionality on my Win 10 machine so far without any success. When I try to open a new remote window after installing the extension, it simply gives me an error after failing to launch 'VS Code Server for WSL'.
![captu](https://user-images.githubusercontent.com/4341404/60751606-1930ab00-9ff3-11e9-99a3-861ce161df68.PNG)

I suspect there's an issue with how the extension specifies the name of the WSL distribution it wants to run. I only have Debian installed on my machine and the distro is shown as `Debian(기본값)` on `wslconfig /l` (기본값 == default). However, it seems that WSL does not allowing starting up the distro with the name `Debian(기본값)` - Instead, I have to specify it as just `Debian`.
![cap2](https://user-images.githubusercontent.com/4341404/60751609-20f04f80-9ff3-11e9-9e8f-c4a0436f0367.PNG)

**Comment by suhdonghwi** [comment]
I am a Korean user and this also happens to me. Is this CJK character related problem?

**Comment by ronaldseoh** [comment]
can't say for sure as I don't know much about VSCode/WSL internals but I have feeling that this does not have much to do with CJK. (although the error msg inside VSCode terminal is garbled up - I heard Windows still uses euc-kr internally) I think Remote-WSL should not put `(기본값)` suffix in the first place. Hopefully it won't be much of a hassle to correct this behavior.

**Comment by suhdonghwi** [comment]
Here's a workaround: install another dummy distro, set it default, and launch VSCode WSL remote with the distro you used before.
