### ISSUE TITLE
Regex support for `remote.SSH.remotePlatform`

### ISSUE THREAD

**Issue by JamyDev** [microsoft/vscode-remote-release#9191]
Currently you have to add an entry to `remote.SSH.remotePlatform` for every host you connect to. For areas where you know all hosts run the same platform (EG your AWS hosts, or internal server network that all have the same suffix), it would be nice to default the platform for all of them. eg:

```
"remote.SSH.remotePlatform": {
    "*.jamy-net.pro": "linux",
}
```

versus having to do:
```
"remote.SSH.remotePlatform": {
    "host1.ams.jamy-net.pro": "linux",
    "host2.bra.jamy-net.pro": "linux",
    ...
    "host4.sea.jamy-net.pro": "linux",
}
```

There's some benefits for use to have `useLocalServer` disabled, which is why this is applicable.

**Comment by connor4312** [comment]
This'll be available in tomorrow's prerelease version of Remote - SSH
