### ISSUE TITLE
On Windows only: No OTP prompt pop-up before password on SSH connection

### ISSUE THREAD

**Issue by Daraan** [microsoft/vscode-remote-release#9197]
This issue is the same as reported in #5824 but it still persists.
When connecting from Windows to a server via SSH that requires an OTP prompt before the password prompt no pop-up shows up to enter the OTP and I have to switch to the terminal to enter it.
 I face this problem only on Windows when on a Linux machine (also same settings) the OTP prompt shows normally.

The recommended alternative in #5824 is to enable `remote.SSH.showLoginTerminal`.  
While this works it, however, has the downside that it creates a non-interactive terminal and I have to manually create a new one. 

---

- VSCode Version: 1.84.2
- Local OS Version: Windows 10 Pro, 22H2

Steps to Reproduce:

* On Windows: Connect to server via SSH that requires an OTP before password

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Most likely enabling `remote.SSH.useLocalServer` would do it for you

**Comment by roblourens** [comment]
If not, please share the log from the Remote-SSH output channel
