### ISSUE TITLE
Remote WSL: There is no data provider registered that can provide view data

### ISSUE THREAD

**Issue by nicola-lunghi** [microsoft/vscode-remote-release#9205]
On remote wsl extension whe  I try to see my wsl targets I get this error:

There is no data provider registered that can provide view data.

![image](https://github.com/microsoft/vscode-remote-release/assets/25422924/d3d843da-2119-4812-81a3-ab7754bdee57)

And I get this error in a window:

Error running command remote-wsl.explorer.refresh: command 'remote-wsl.explorer.refresh' not found.
This is likely caused by the extension that contributes remote-wsl.explorer.refresh.

- VSCode Version: 1.84.2
- Remote extension version: v0.81.8
- Local OS Version: Windows 10
- Remote Extension/Connection Type: WSL

**Comment by bamurtaugh** [comment]
Thanks for filing. The WSL view currently loads for me on Windows 11 and the latest VS Code Insiders:

![image](https://github.com/microsoft/vscode-remote-release/assets/25310137/560549f2-d9eb-496d-84e0-52f743c52fad)

Out of curiosity, do you see anything different if you try the latest VS Code Insiders? And/or did refreshing in the viewlet help?

**Comment by msdn65** [comment]
Fehler beim Ausführen des Befehls remote-wsl.explorer.refresh: command 'remote-wsl.explorer.refresh' not found. Dies wird vermutlich durch die Erweiterung verursacht, die remote-wsl.explorer.refresh beiträgt.

**Comment by bojiangpro** [comment]
@nicola-lunghi You can try open code in WSL. (root@NV-9FVKCL3:~# code)

**Comment by IbrahimTanyalcin** [comment]
This is marked as info needed. Exactly what else does he need to provide? I have the same issue described

**Comment by thanhleha** [comment]
I fixed by reinstalling the WSL extension and restarting vscode

**Comment by bamurtaugh** [comment]
Thanks all for the continued feedback. Please let us know if folks still encounter this, otherwise sounds like reinstall / updates may have fixed this.
