### ISSUE TITLE
Attach to Visual Studio Code opens unnecessary quick pick

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-remote-release#9206]
1. Have a bunch of stopped containers
2. Select them all, right click and hit start 
3. 🎉 No quick pick it knows what to start based on what I selected (although it does sometimes show an unnecessary notification about the action not being permitted on certain parts of the selection such as the header)
4. Right click one of the containers that is started
5. Click attach to visual studio code
6. 🐛 A quick pick opens making me select the container again. It should just attach to the one my selection is one

**Comment by lramos15** [comment]
I'm not sure I follow. I'm right clicking again after the icon shows running and clicking attach

**Comment by lramos15** [comment]
I'm not sure I follow. I'm right clicking again after the icon shows running and clicking attach

**Comment by bwateratmsft** [comment]
If another container transitioned from stopped to running, the same thing would occur. There are also periodic refreshes and a few other conditions that would trigger a refresh. If any one of them happens, the tree item in the selection becomes out of date and VSCode passes undefined to commands executed from that context menu.

**Comment by lramos15** [comment]
Interesting my flow is always to wait until all my containers are reporting that they started then right clicking one to connect and I have never not gotten the quick pick

**Comment by bwateratmsft** [comment]
You might have gotten unlucky with the timing of refreshes (e.g., the one-minute refresh could have occurred between you right-clicking and then choosing the Attach command in the context menu)--does it happen every time you try? I tried a couple times with just two containers and was not able to repro.

**Comment by lramos15** [comment]
> does it happen every time you try?

Yes, but my setup is also Remote SSH -> Dev box running containers -> Attach to a container. Not sure if that's add a complexity layer

**Comment by bwateratmsft** [comment]
Can you try the following to see if it's for sure the tree item refreshes that is causing the issue?

1. Minimize every subwindow except containers, to keep the logs more brief.
2. Turn Docker's log level up to Trace
3. Execute your scenario, and check Docker's output window to see if a `docker container ls` command happens as you right click

**Comment by lramos15** [comment]
> Can you try the following to see if it's for sure the tree item refreshes that is causing the issue?
> 
> 1. Minimize every subwindow except containers, to keep the logs more brief.
> 2. Turn Docker's log level up to Trace
> 3. Execute your scenario, and check Docker's output window to see if a `docker container ls` command happens as you right click

I see nothing occurring in the logs when I right click which makes me assume a refresh is not occurring
