### ISSUE TITLE
/.devcontainer/postCreateCommand.sh: Permission denied

### ISSUE THREAD

**Issue by EnlightonOcean** [microsoft/vscode-remote-release#9207]
`postCreateCommand` runs in the workspace folder, you could, e.g., place a script in the `.devcontainer` folder and invoke it as `./.devcontainer/postCreateCommand.sh`.

_Originally posted by @chrmarti in https://github.com/microsoft/vscode-remote-release/issues/3527#issuecomment-674739457_

Running the postCreateCommand from devcontainer.json...

[23700 ms] Start: Run in container: /bin/sh -c ./.devcontainer/postCreateCommand.sh
/bin/sh: 1: ./.devcontainer/postCreateCommand.sh: Permission denied
[23861 ms] postCreateCommand failed with exit code 126. Skipping any further user-provided commands.
Done. Press any key to close the terminal.

**Comment by chrmarti** [comment]
Which OS are you running on? Could you check the file permissions with `ls -la .devcontainer` from an Integrated Terminal when connected to the container?
