### ISSUE TITLE
vscode-server processes hangs remote server

### ISSUE THREAD

**Issue by mironovdm** [microsoft/vscode-remote-release#921]
- VSCode Version: 1.36.0
- Local OS Version: Windows 10 build 1903
- Remote OS Version: Ubuntu 18.04.2 LTS
- Remote Extension/Connection Type: SSH

I have EC2 instance in AWS cloud for developer purposes(1Gb, 1vCPU). Recently I began to use Remote-SSH extension for development and noticed a strange thing: after some time of working connected to my dev server I get message in VS Code that connection to the server is lost. Usually I have two SSH sessions to the server with Putty and sometimes WinSCP connection. At the moment when VS Code alerts about disconnection WinSCP also show that connection is lost, one of the Putty terminals also shows that connection is lost, but one of them remains connected and when I try to type something in terminal after several seconds characters appear in console. Feeling like it is a very slow connection or server is under high load.

First time I was shure that something wrong with AWS service. After several minitues I tried to reboot server using AWS console and it helped - I was able to connect to the server normally . After next two times of loosing a connection and rebooting a server by AWS console I began to suspect that this happens when I working in VS Code with Remote-SSH.  Next time right after starting Remote-SSH session I looked at the server with ps command what are the processes bound to the VSCode. There was several node processes started from .vscode-server directory.

After some time of working the connection again was lost. One of the putty terminal remain connected. I typed command "killall node" and after 10-15 seconds it was appear in terminal. The command was executed for several seconds and after execution normal operation of the server has been restored.

So now it is clear that vscode-server is the reason of the problems with remote server. If necessary, I can provide logs from the server.

**Comment by roblourens** [comment]
1 GB of RAM? We don't have minimum required specs but that might just be too low. We also tend to perform poorly on machines with just one processor core.
