### ISSUE TITLE
[Remote-SSH Bug]: .vscode-server Download error

### ISSUE THREAD

**Issue by CNGoSeI** [microsoft/vscode-remote-release#9214]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### ->

版本: 1.83.1 (user setup)
提交: a6606b6ca720bca780c2d3c9d4cc3966ff2eca12
日期: 2023-10-27T12:03:04.063Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT ia32 10.0.19045

this version ssh server download server return 404 NOT FOUND 
https://update.code.visualstudio.com/commit:a6606b6ca720bca780c2d3c9d4cc3966ff2eca12/server-linux-x64/stable
the version 

Is this version of ssh no longer supported?

### Expected Behavior

If it's just that the link is gone and the file still exists, are there any other download channels?

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by YorickColeu** [comment]
I had this issue too. I ended up uninstalling VSCode completely and then reinstalling it; this fixed the issue. My previous VSCode installation was a 32-bit version instead of 64-bit, and I had a warning for a while regarding this mismatch. It may be related...

**Comment by CNGoSeI** [comment]
> I had this issue too. I ended up uninstalling VSCode completely and then reinstalling it; this fixed the issue. My previous VSCode installation was a 32-bit version instead of 64-bit, and I had a warning for a while regarding this mismatch. It may be related...
Microsoft has stopped supporting 32-bit, and my old computer only supported 32-bit, so I switched to coder-server

**Comment by roblourens** [comment]
`a6606b6ca720bca780c2d3c9d4cc3966ff2eca12` is not the official release build- seems like you might have ended up on a private build somehow? You are also on an out of date version, so updating or uninstall/reinstall should fix it
