### ISSUE TITLE
Wrong directory

### ISSUE THREAD

**Issue by FuriouZz** [microsoft/vscode-remote-release#922]
Issue Type: <b>Bug</b>

* Create a directory "dir1" with some file via Windows Explorer
* Create a directory "dir2" with some file via Windows Explorer
* Open "dir1" with Remote - WSL
* Close VSCode
* Remove "dir1"
* Rename "dir2" to "dir1"
* Open the new "dir1" with Remote - WSL : Continue to display old "dir1" files

Extension version: 0.38.7
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.97GB (10.00GB free)|
|Process Argv|D:\Users\FuriouZz\Documents\Projects\@tools\lol.js|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3001)|
|Memory (System)|15.97GB (10.00GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment]
What do you mean by `Continue to display old "dir1" files`. Can you add a screenshot?
In the explorer? The explore fetches the file structure on every restart.
