### ISSUE TITLE
add possibility to extend dev container configuration to complement user or platform specific configurations

### ISSUE THREAD

**Issue by pascal456** [microsoft/vscode-remote-release#9220]
I am looking for a possibility to extend or overload a `devcontainer.json` file that has been added to the repository / version control.

# current

Example project structure (can be replicated with the *"Try a Dev Container -> Python3" command in vscode*):
```
.
├── .devcontainer
│   └── devcontainer.json
├── .git
│   ├── FETCH_HEAD
...
├── app.py
├── requirements.txt
...
```

Now the actual `devcontainer.json` from that example looks different but to simplify, let's assume it looks like this:
```json
{
	"name": "Python 3",
	"image": "mcr.microsoft.com/devcontainers/python:0-3.11",
	"postCreateCommand": "pip3 install -r requirements.txt"
}
```

This is fine so far.

# Attempt

I would like to keep that configuration file. But for some dev PCs that we use, we also have GPUs available. Now when I add 
```json
"runArgs": ["--gpus", "all"],
```
for a PC that actually has a GPU installed, everything is fine.

But for PCs that have not, an error occurs (do not remember correctly, something about nvidia containers).

# Goal / Idea

I am looking for something like a configuration that I can keep in the repository, say the above `devcontainer.json` file. And something like an extending file, that is additionally considered, say `devcontainer.extend.json`.

In the end, I would add the `devcontainer.extend.json` to the `.gitignore` so that personal, machine-dependent configurations like the `"runArgs": ["--gpus", "all"]` would be placed in that file.

So the `devcontainer.extend.json` file would contain nothing else than
```
"runArgs": ["--gpus", "all"],
```
which would be laod after the original configuration, so that it overloads the original config (in this case not exactly overloading but extending the configuration by adding another setting)

And to be complete, the full devcontainer configuration, when both files are combined, would look similar to this:
```json
{
    "name": "Python 3",
    "image": "mcr.microsoft.com/devcontainers/python:0-3.11",
    "postCreateCommand": "pip3 install -r requirements.txt",
    "runArgs": ["--gpus", "all"]
}
```
and the new folder structure containing the extending file could be something like this:
```
.
├── .devcontainer
│   ├── devcontainer.json
│   └── devcontainer.extend.json
├── .git
│   ├── FETCH_HEAD
...
├── app.py
├── requirements.txt
...
```

**Comment by pascal456** [comment]
wow, easy solution. No did not try that before. Works fine for me.
So my original problem is solved! Thank you very much.

Nevertheless: is the idea I described above still interesting enough for implementation?

**Comment by sarphiv** [comment]
@chrmarti 's suggestion works perfectly on Fedora Linux when used on a PyTorch CUDA enabled image. 
However, some of my teammates on Windows 11 using Docker Desktop are having issues with "hostRequirements" not doing anything. They have to use "runArgs" for the devcontainer to detect their CUDA-enabled GPU. However, as stated in the issue - adding this option causes an error for people without a GPU.

**Comment by pascal456** [comment]
@sarphiv Is using WSL an Option?

I use Windows 10 + WSL. I create the devcontainer from there with Docker Desktop (Ubuntu Docker integration turned on in Docker Desktop settings), what works fine in my case.

**Comment by sarphiv** [comment]
@pascal456 Yes, this is on WSL 2 on Windows 11.

This does not work using the default WSL docker-desktop environment, nor does it work using a newly created Ubuntu environment created via WSL. We have also tried to use the Dev Environments tab in Docker Desktop, and this too does not work. 

To make sure we all understand each other. "hostRequirements": { "gpu": "optional" } works perfectly on Linux Fedora, so PyTorch can be CUDA-accelerated. On our Windows machines with CUDA-enabled GPUs, the above does not work. We have to add "runArgs": [ "--gpus", "all" ] for PyTorch on our Windows machines to detect the GPU. However, adding "runArgs": [ "--gpus", "all" ] breaks the dev container for machines without GPUs.

**Comment by pascal456** [comment]
You are right!

# my setup
I my case
- docker desktop
- windows 10
- set up dev environment in WSL (Ubuntu 20.04) with Docker Desktop integration

`devcontainer.json`:
```
...
"hostRequirements": { "gpu": "optional" },
...
```

## Result

This was working for me, so that this resulted in the starting command "`docker run ... --gpus all...`".

This was a few weeks ago. Now I have not used the container for a while... turns out it is not working anymore, but I am quite sure it was working. So I can confirm it: `"hostRequirements": { "gpu": "optional" }` has no effect for me **on my windows machine**, on a Ubuntu client it is working.

## more info
- `nvidia-smi` runs fine in windows
- `nvidia-smi` runs fine WSL
- `nvidia-smi` does **not** work in a devcontainer that is started from within the WSL

# Suggestion
I don't really need this solved very urgently right now, because I'm currently mostly working from the Ubuntu client. When you need it now, @sarphiv, you probably should better open a new issue. This here was done at that time. You can surely also tag me on the new issue and I will see if I can provide input as well, tests etc.

**Comment by chrmarti** [comment]
A new issue would be appreciated, thanks. Note that the detection for a GPU is rather simplistic at the moment, maybe Docker's output changed in a way that broke it on Windows: https://github.com/devcontainers/cli/blob/f7d4c853bf8c284d784173f3e915a34d961b0b55/src/spec-node/utils.ts#L201
