### ISSUE TITLE
[Remote-SSH Bug]: Windows Visual Studio Code - can't connect SSH with whitespaces in the path for the ssh config

### ISSUE THREAD

**Issue by heku-ard** [microsoft/vscode-remote-release#9225]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### Expected Behavior

Issue of #994 is back. 
I also tried the pre-release-version.
I want to store my config-file in onedrive, which is configured with whitespaces in the path (corporate setting)

### Steps To Reproduce

1.) configure a specific path with whitespaces in one of the folders in the path
2.) configuration will be loaded corrected
3.) on connect you get the error-message:

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>
[11:01:54.324] Using SSH config file "C:\Users\USER\Path with spaces\VS-Code-Config\config"
[11:01:54.325] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 59563 -F "C:\Users\USER\Path with spaces\VS-Code-Config\config" mon bash
[11:01:54.335] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[11:01:54.680] > Can't open user config file C:\\Users\\USER\\Path: No such file or directory

<-- it breaks at the first whitespace
</p>
</details>

**Comment by heku-ard** [comment]
it breaks at the first whitespace

**Comment by LeChatP** [comment]
Similar problem here when I use docker-compose DevContainers, there is no double quote on docker-compose command args that lead to blocking error when there is spaces on paths.

**Comment by joshspicer** [comment]
I tested moving my config to a path with spaces and was able to connect. I believe is now works as expected, but please re-open if you think otherwise.
