### ISSUE TITLE
[Remote-SSH Bug]: File links file://path/to/file Links Do Not Work with Remote Linux - SSH

### ISSUE THREAD

**Issue by JacquesSyn** [microsoft/vscode-remote-release#9227]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Open a file on a remote using VSCode Links like `file:///path/to/file` do NOT work on Linux remotes. 

- Correctly answers "Not found" when wrong path
- ERRORS when right path : "Unable to read file ... (Unkown FileSystemError : Error : UNKOWN: unkown error, stat <file>

- If you do the same without remote : it works

### Steps To Reproduce

- Create a file on a remote
- Create a Readme.md file and make a link to the file like `file:///path/to/file`
- Click the link on VSCode

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
Unable to read file ... (Unkown FileSystemError : Error : UNKOWN: unkown error, stat <file>
```

</p>
</details>

### Anything else?

Is not working as intended and is a feature that is working on base VSCode.

**Comment by joshspicer** [comment]
In the case of creating a link in a markdown file, I suggest omitting the `file://`.  Perhaps try `./path/to/file`.  There is a different filesystem scheme used for remote
