### ISSUE TITLE
The node processes and sockets keep alive on server.

### ISSUE THREAD

**Issue by seokbeomKim** [microsoft/vscode-remote-release#9228]
- VSCode Version: 1.84.2
- Local OS Version: Windows_NT x64 10.0.22631
- Remote OS Version: Linux S101 3.19.8-100.fc20.x86_64 #1 SMP Tue May 12 17:08:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- Remote Extension/Connection Type: Server

```
Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
```

- Logs:

```
[20:10:22.757] [server] Checking /home/B190253/.vscode-server/cli/servers/Stable-1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/log.txt and /home/B190253/.vscode-server/cli/servers/Stable-1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/pid.txt for a running server...
[20:10:22.797] [server] Found running server (pid=1592)
[20:10:24.133] > Removing old logfile at /home/B190253/.vscode-server/.cli.1a5daa3a0231a0fbba4f14db7ec463cf99d7768e.log
> Spawned remote CLI: 1831
> Waiting for server log...
> Waiting for server log...
> e1ad370e75c6: start
> SSH_AUTH_SOCK====
> DISPLAY====
> listeningOn==127.0.0.1:46979==
> osReleaseId==fedora==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1000006450==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> serverStartTime==74==
> execServerToken==26e356ea1f84==
> e1ad370e75c6: end
> 
> 
[20:10:25.582] Opening exec server for ssh-remote+dev
[20:10:25.594] Verified and reusing cached exec server for ssh-remote+dev
[20:13:22.933] > Removing old logfile at /home/B190253/.vscode-server/.cli.1a5daa3a0231a0fbba4f14db7ec463cf99d7768e.log   
> Spawned remote CLI: 1831
> Waiting for server log...
> Waiting for server log...
> e1ad370e75c6: start
> SSH_AUTH_SOCK====
> DISPLAY====
> listeningOn==127.0.0.1:46979==
> osReleaseId==fedora==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1000006450==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> serverStartTime==74==
> execServerToken==26e356ea1f84==
> e1ad370e75c6: end
```

Steps to Reproduce:

I checked with the pre-release version, and the 'node' process remains alive even when I do  'close remote connection'. I am not sure this is intended behavior. Also, the number of node processes increases whenever I connect to the remote server and change the working directory. Is this issue affected by the remote server environment? like the OS version?

1. Connect to the server. 
2. Check the number of node processes.
3. Change the working directory.
4. Check the number of node processes again. 
5. Close the remote connection.
6. Check the node processes and they keep remaining. (also, in /run/user/{userid}/vscode*.sock files have remained without any removal. Is this normal behavior?)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
Which node processes, can you check their command arguments? Do they time out and shut down after a few hours?
