### ISSUE TITLE
Can't connect remote vscode?

### ISSUE THREAD

**Issue by luyahan** [microsoft/vscode-remote-release#923]
remote-ssh@0.44.0
win32 x64
SSH Resolver called for "ssh-remote+153", attempt 1
SSH Resolver called for host: 153
Setting up SSH remote "153"
Using commit id "0f3794b38477eea13fb47fbe15a42798e6129338" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
Install and start server if needed
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 1
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 2
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 3
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 4
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 5
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> 
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 6
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> 
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 7
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 8
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 9
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 10
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 11
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 12
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 13
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 14
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 15
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 16
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 17
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 18
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 19
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 20
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 21
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 22
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 23
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 24
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> 
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 25
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 26
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
> 
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 27
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 28
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 29
> 
> Found existing installation at /home/luyahan/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> failed: Connection refused.
> 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
> 
"install" terminal command done
Received install output: 010fae5f-7ba8-4596-a3cc-9c408bbb0d2f##28##
Server status check failed - waiting and retrying 30

------

**Comment by felwolff** [comment]
The same thing is happening to me! It can be "fixed" for me by restarting the remote VSCode server. When I then reload the window (that is successfully connected), I get this status-check-failed loop. The same thing happens when I open a new folder in a connected window. 
The issue is still persistent in 1.37.0-insider.

**Comment by felwolff** [comment]
I may have just found the reason: I have a proxy configured in my `.wgetrc`, which is necessary to download the vscode server in our company network. When I remove the wget proxy, the reloading works.
Any ideas what the best way here is? I'm pretty sure it worked like this before.

**Comment by roblourens** [comment]
Please try again with the latest version of the extension, I believe this is fixed.
