### ISSUE TITLE
I installed remote tunnel extension on a windows VM later the VM is deleted.

### ISSUE THREAD

**Issue by kalvapradyumnareddy** [microsoft/vscode-remote-release#9232]
🚨 The issue tracker is not for questions 🚨

If you have a question about VS Code, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code and about
VS Code Remote on https://stackoverflow.com/questions/tagged/vscode-remote.

**Comment by bamurtaugh** [comment]
If you have a specific issue, please provide more info (local and remote OS, extensions you're using, detailed repro steps, logs/error messages, etc). Thanks!

**Comment by bamurtaugh** [comment]
Actually now that I see https://github.com/microsoft/vscode-remote-release/issues/9233, closing this one as a dupe.
