### ISSUE TITLE
Test: CAs in remote extension host

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#9237]
Refs: https://github.com/microsoft/vscode-remote-release/issues/9176

- [x] anyOS @anthonykim1
- [x] anyOS @benibenj

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%239237%0A%0A&assignees=chrmarti)

---

- Create a workspace folder with a `.devcontainer/devcontainer.json`:
```jsonc
{
	"image": "mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye",
	"postCreateCommand": "[ -f server_localhost.key ] || openssl req -x509 -newkey rsa:4096 -keyout server_localhost.key -out server_localhost.crt -days 365 -nodes -subj /CN=localhost",
	"customizations": {
		"vscode": {
			"extensions": [
				"chrmarti.network-proxy-test"
			]
		}
	}
}
```
- And a `https-server.js`:
```js
const https = require('https');
const fs = require('fs');

const options = {
  key: fs.readFileSync('./server_localhost.key'),
  cert: fs.readFileSync('./server_localhost.crt')
};

const server = https.createServer(options, (_req, res) => {
  res.writeHead(418);
  res.end();
}).listen(3000);
```
- Run `Dev Containers: Reopen in Container`. (This will also create a certificate in your workspace.)
- Run `node https-server.js` in the integrated terminal.
- Run `Network Proxy Test: Test Network Connection` and enter `https://localhost:3000` when asked.
- Verify that you see a `DEPTH_ZERO_SELF_SIGNED_CERT` in the log shown in the editor.
- Add `server_localhost.crt` from the workspace to your OS' CA store. (See below for instructions.)
- Restart VS Code (close all VS Code windows and reopen, reloading the window is not sufficient).
- Re-Run `Network Proxy Test: Test Network Connection` and enter `https://localhost:3000` when asked.
- Verify that you no longer see a `DEPTH_ZERO_SELF_SIGNED_CERT` in the log shown in the editor.

### Add Certificate to OS Store

Remember to remove the certificate when you are done with testing.

#### Windows

- Open `Manage Computer Certificates`.
- Right-Click `Trusted Root Certification Authorities` > `All Tasks` > `Import`.
- Import the `server_localhost.crt` from the workspace folder.

#### macOS

- Open `Keychain Access`.
- Click the `Certificates` tab and select the `login` key chain.
- `File` > `Import Items...`.
- Import the `server_localhost.crt` from the workspace folder.
- Right-Click on the new `localhost` entry in the list and `Get Info`.
- In the dialog: Expand `Trust` tree node and change the default trust to `Always Trust`.

#### Linux

For Ubuntu/Debian (make sure to run this on your host Linux, not the dev container):
```sh
sudo apt-get install -y ca-certificates
sudo cp server_localhost.crt /usr/local/share/ca-certificates
sudo update-ca-certificates
```

**Comment by anthonykim1** [comment]
@chrmarti are you supposed add Certificate to OS Store before all the steps? Before running reopen in dev container?

**Comment by anthonykim1** [comment]
@chrmarti When you say log, is it referring to logs accessible via "Dev Containers Developer: Show All Logs..."? 
<img width="395" alt="Screenshot 2023-11-27 at 9 01 54 PM" src="https://github.com/microsoft/vscode-remote-release/assets/62267334/603f6957-8a45-404d-9e72-b1c7ad094fa3">

**Comment by chrmarti** [comment]
@anthonykim1 The `Network Proxy Test: Test Network Connection` command should open a text editor with log output from a request sent to the https-server.js script listening on https://localhost:3000 inside the container.
