### ISSUE TITLE
node https-server.js fails to run 

### ISSUE THREAD

**Issue by anthonykim1** [microsoft/vscode-remote-release#9241]
Testing #9237

Steps to repro:
1. Create a workspace folder with a .devcontainer/devcontainer.json:
```
{
	"image": "mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye",
	"postCreateCommand": "[ -f server_localhost.key ] || openssl req -x509 -newkey rsa:4096 -keyout server_localhost.key -out server_localhost.crt -days 365 -nodes -subj /CN=localhost",
	"customizations": {
		"vscode": {
			"extensions": [
				"chrmarti.network-proxy-test"
			]
		}
	}
}
```
and https-server.js:
```
const https = require('https');
const fs = require('fs');

const options = {
  key: fs.readFileSync('./server_localhost.key'),
  cert: fs.readFileSync('./server_localhost.crt')
};

const server = https.createServer(options, (_req, res) => {
  res.writeHead(418);
  res.end();
}).listen(3000);
```
3. Run Dev Containers: Reopen in Container
4. Have Docker running
5. Run node https-server.js 
<img width="713" alt="Screenshot 2023-11-27 at 9 09 45 PM" src="https://github.com/microsoft/vscode-remote-release/assets/62267334/c27b1b5f-1c07-4083-8955-2dc8f35ab299">

<img width="668" alt="Screenshot 2023-11-27 at 9 09 50 PM" src="https://github.com/microsoft/vscode-remote-release/assets/62267334/703da584-218e-4aae-978b-993ce142a9e0">

**Comment by chrmarti** [comment]
This is expected. The example is only good for testing with something like the test command mentioned in the test instructions.
