### ISSUE TITLE
remote ssh does not respect the user in .ssh/config

### ISSUE THREAD

**Issue by vdejager** [microsoft/vscode-remote-release#9248]
Type: <b>Bug</b>

if the confic contains a different name than the user on the local machine, remote explored tries to connect with the local username instead of the specified user

Extension version: 0.107.1
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:57.054Z)
OS version: Darwin arm64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
This would imply that it's not actually using the ssh config entry. If you think that things are configured correctly on your end, please share the log from the Remote-SSH output channel
