### ISSUE TITLE
remote development in docker doesn't support well in python language server

### ISSUE THREAD

**Issue by messi-yang** [microsoft/vscode-remote-release#925]
- VSCode Version:
1.36.0
- OS Version:
mac os 10.14.5
Steps to Reproduce:
1. Choose running container in the docker extension, right click then choose "Attach Visual Studio Code"
2. So in the new window of the container, I activate the virtual python environment using "source .../activate", and choose the target interpreter. 
3. I hover in some function or module, the code always shows "Code analysis is in progress..." and never finished. and the code automation and code suggestion all both unavailable.

I use Visual Studio Code for my main daily development in docker. So I wish anybody can fix the problem, or the remote development is not useful like PyCharm. 

Does this issue occur when all extensions are disabled?: Yes/No
Yes, just keep python still occurs.

**Comment by Chuxel** [comment]
//cc: @microsoft/pyvsc

**Comment by brettcannon** [comment]
Are you selecting the Python interpreter in the extension, or only doing an activation by hand in the terminal? If you selected a virtual environment in the extension then it would automatically activate in the terminal upon terminal creation, hence the question based on you saying " I activate the virtual python environment using "source .../activate", and choose the target interpreter".

If you didn't select the appropriate interpreter then things may not resolve appropriately. And just to double-check, you specifically have turned on the language server over Jedi?

**Comment by messi-yang** [comment]
@brettcannon I also choose the appropriate interpreter in the status bar, and in the settings.json file, I have this below:
{
    "python.pythonPath": "venvs/edxapp/bin/python"
}

**Comment by brettcannon** [comment]
So if you open a terminal after the Python extension initially loads ("Code analysis is in progress..." is not part of this) then does the terminal get sent the activation command for your virtual environment?

And I still need to know whether you're using the language server or Jedi (is the "Jedi Enabled" setting on or off?).

**Comment by messi-yang** [comment]
@brettcannon yes, if i open a new terminal by click "New Terminal" in the integrated terminal, it sent the activation command for my virtual environment, like this:
root@28255645cfbc:/edx/app/edxapp# source /edx/app/edxapp/venvs/edxapp/bin/activate
(edxapp) root@28255645cfbc:/edx/app/edxapp#

I don't use Jedi, i checked it in my settings, "Jedi enabled" is unnchecked.

But another situation is that i see the Python Output in my intergrated terminal, the last several lines are:
[Info  - 1:55:52 AM] User search paths:
[Info  - 1:55:52 AM]     /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages
[Info  - 1:56:42 AM] Microsoft Python Language Server version 0.3.20.0
[Info  - 1:56:42 AM] Initializing for /edx/app/edxapp/venvs/edxapp/bin/python 
So i guess it never finishs initializing?

**Comment by brettcannon** [comment]
OK, I think we're at the point that we need to open an issue at https://github.com/microsoft/vscode-python.

@messi-yang would you mind opening an issue over there? I can copy this issue over by hand if you don't want to, but our issue template asks some questions that would be useful to capture to help diagnose this, so if you you're willing to open a fresh issue over there that would be really helpful.

**Comment by messi-yang** [comment]
@brettcannon Ok, I can open a new issue over there. And really thanks for your reply.

**Comment by egamma** [comment]
Closing the issue, since it is tracked in vscode-python.
