### ISSUE TITLE
Deadlock in VSCode SSH Client During Concurrent Torch Training Runs

### ISSUE THREAD

**Issue by Henri-Leon** [microsoft/vscode-remote-release#9260]
I've experienced a recurring issue where both the VSCode SSH client and concurrent PyTorch training runs enter a deadlock state. This has happened three times under the following conditions:

- Running PyTorch training scripts on a remote server.
- Simultaneously connected to the server via VSCode's Remote SSH extension.
result: 
- The process .vscode-server/bin/[commit_hash]/out/bootstrap-fork --type=fileWatcher enters a 'D' state along with the training process.

This situation arises when the training data is located in the same directory that the VSCode extension is accessing. While relocating the training data might be a workaround, the occurrence of a deadlock is unexpected.

My assumption:
I suspect this deadlock might be related to VSCode's file watcher interacting with the same files as torch accesses during training.

VSCode version local:
Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:50:47.800Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-89-generic snap

remote OS: 5.15.0-89-generic #99~20.04.1-Ubuntu SMP

my OS: 5.15.0-89-generic #99~20.04.1-Ubuntu SMP

torch version:  2.0.1

**Comment by bpasero** [comment]
I suggest to configure the `files.watcherExclude` setting to exclude the folder of the training data.

I am not actually sure what you are seeing here, nor do I think there is a fix that applies to VS Code. We rely on https://github.com/parcel-bundler/watcher external library.
