### ISSUE TITLE
Open all 130 ports by default? 

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-remote-release#9261]
- host platform: macbook pro m1 pro Sonoma 14.1.2
- VSCode Version: 1.84.2(Universal) commit 1a5daa3a- Local OS Version:
- Remote OS Version: mcr.microsoft.com/devcontainers/typescript-node:1-18-bullseye
- Remote Extension/Connection Type: Containers

- Logs:

Steps to Reproduce:

1. Open repo in local host dev container in vscode and see 130 ports
2. There are no ports or services running at the time. 
3. Check settings and this is turned on by default but I didn't turn it on by default and I haven't seen this before.
4. Had to turn off, all settings about port forwarding to get back to what was my development environment on Friday meaning only 1/few ports open. 

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by diberry** [comment]
Maybe all ports are open because the azd or az auth redirect was failing without it?

**Comment by bamurtaugh** [comment]
cc @alexr00 for any thoughts

**Comment by alexr00** [comment]
@chrmarti is correct. A screenshot of the ports view would help confirm whether this is what happened.

**Comment by bamurtaugh** [comment]
Hey there @diberry, thanks again for filing. If you're able to share the screenshot mentioned above, or you have other updates here, please let us know. Thank you!
