### ISSUE TITLE
Icon does not load when reopening folder in Windows

### ISSUE THREAD

**Issue by redblue9771** [microsoft/vscode-remote-release#928]
**Icon does not load when reopening folder in Windows.**

- VSCode Version: 1.37.0-insider
- Local OS Version: Windows10 1903 OS Build 18362.175
- Remote OS Version: Ubuntu 18.04.2 LTS
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Reopen folder in Windows
![D%%AS8)@5S6LBSU`~_Y7 X0](https://user-images.githubusercontent.com/32461741/60816912-43d65b80-a1cd-11e9-9380-d4a7ccaba4dc.png)

2. Close Remote Connection

3. File->Open Recent->Just the folder
![QTPJ3KWDXT%V~QJCM_C%Z21](https://user-images.githubusercontent.com/32461741/60816901-4042d480-a1cd-11e9-8d14-28588d369a13.png)

CPUs | Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz (8 x 3096)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.92GB (8.32GB free)
Process Argv |  
Screen Reader | no
VM | 0%

**Comment by aeschli** [comment]
dup of #966
