### ISSUE TITLE
Changing .vscode_server directory on remote host

### ISSUE THREAD

**Issue by dennykhoerniawan** [microsoft/vscode-remote-release#929]
🚨 The issue tracker is not for questions 🚨

I noticed that the .vscode-server and .vscode-cpptools I installed are automatically installed in my home directory on my remote host. I have very little space there and would like to change it. How do I do that?

**Comment by tomocafe** [comment]
https://github.com/microsoft/vscode-remote-release/issues/940#issuecomment-510232416
