### ISSUE TITLE
[Dev Containers on Remote SSH] Extra home directory created with extra characters

### ISSUE THREAD

**Issue by taesungh** [microsoft/vscode-remote-release#9292]
When attempting to set up a dev container over Remote SSH, my user folder is not properly recognized, and a second user folder is created but with some extra characters at the end. In Finder, it appears as `Taesung?n`, and when doing tab completion in terminal, it appears as `Taesung$'\n'-n`.

The container itself appears to run fine afterwards, but I would prefer not to have this extra user folder just to store `.vscode-remote-containers`.

Perhaps this is because the home path (`/Volumes/Storage SSD/Taesung`) contains a space character?

## Logs
```
[158 ms] Dev Containers 0.327.0 over Remote - SSH 0.107.1 in VS Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c).
[157 ms] Start: Resolving Remote
[181 ms] Start: Run: /bin/sh 
[219 ms] Start: Run in host: echo ~
[232 ms] 
/Volumes/Storage SSD/Taesung
-n 
[232 ms] -n 
[233 ms] Start: Run in host: id -un
[312 ms] 
Taesung
-n 
[312 ms] -n 
[313 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'Taesung
[331 ms] userEnvProbe: loginInteractiveShell (default)
[331 ms] userEnvProbe: not found in cache
[331 ms] userEnvProbe shell: /bin/sh
[370 ms] userEnvProbe: falling back to printenv
[370 ms] userEnvProbe shell: /bin/sh
[482 ms] userEnvProbe PATHs:
Probe:     '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
Container: None
[589 ms] Start: Run: uname -m
[1473 ms] Start: Extracting tarball
[1474 ms] Start: Run: mkdir -p /Volumes/Storage SSD/Taesung
[1665 ms] Start: Run: tar --no-same-owner -x --strip-components 1 -C /Volumes/Storage SSD/Taesung
[98815 ms] Start: Run: mv -n /Volumes/Storage SSD/Taesung
[98886 ms] Setting up container for folder or workspace: ...
```

## Platform
- VS Code 1.85.0 on macOS 12.6.9
- Dev Containers extension v0.327.0
- Remote SSH extension v0.107.1
- The remote server is also running macOS 12.6.9

**Comment by taesungh** [comment]
I updated the home path to `/Users/Taesung` and now encounter a similar issue
```
[error] {"message":"Command failed: mkdir -p /Users/Taesung\n-n/.vscode-remote-containers/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c_1702159433845","stdout":{"type":"Buffer","data":[]},"stderr":{"type":"Buffer","data":[109,107,100,105,114,58,32,47,85,115,101,114,115,47,84,97,101,115,117,110,103,10,45,110,58,32,80,101,114,109,105,115,115,105,111,110,32,100,101,110,105,101,100,10]},"code":1} remote-containers.openFolder {"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"}
```

**Comment by nyannyacha** [comment]
I'm also experiencing the same problem and that might be related to the built-in `/bin/sh` in MacOS. IIRC the native `/bin/sh` does not support using the `-n` switch. In effect, looking at my output in the dev container, it tries getting outputs from the stdout using the `echo -n` command on the `/bin/sh`.

```
[8815 ms] Dev Containers 0.327.0 over Remote - SSH 0.107.0 in VS Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c).
[8814 ms] Start: Run: /bin/sh 
[8834 ms] Start: Run in host: echo ~
[8845 ms] 
/Users/nyan
-n 
[8846 ms] -n 
[8846 ms] Start: Run in host: id -un
[8864 ms] 
nyan
-n 
[8864 ms] -n 
```

I think this is what happened cause the remote extension threw the wrong shell into the dev container, which collects the outputs from the remote host.

**Comment by taesungh** [comment]
Ahh you are correct, according to `man echo` on macOS:
> Some shells may provide a builtin `echo` command which is similar or identical to this utility. Most notably, the builtin `echo` in sh(1) does not accept the `-n` option. Consult the builtin(1) manual page.

It appears `/bin/bash` does not have this issue, so perhaps a shell override is needed for `platform === "darwin"`?

**Comment by Cubox** [comment]
I am also getting this error since yesterday.

**Comment by karl-otto** [comment]
I am getting this odd behaviour too. Went back to _Dev Container v0.321.0_ to work around this issue.

**Comment by nag92** [comment]
I am having a similar issue too with WSL and devcontainers

**Comment by pmunin** [comment]
Same issue connecting on latest vscode, while trying to open remote devcontainer from Windows on MacOs.

Windows Vscode:
```
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

MacOs Vscode:
```
Version: 1.85.1 (Universal)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0
```

Devcontainers extension version: `Dev Containers v0.327.0`

**Comment by chrmarti** [comment]
This should be fixed in recent versions.
