### ISSUE TITLE
Can't use `code` inside VSCode WSL terminal: `Unable to connect to VS Code server: Error in request`

### ISSUE THREAD

**Issue by McSneaky** [microsoft/vscode-remote-release#9294]
- VSCode Version: 1.84.2
- Local OS Version: Windows 11 Pro 23H2
- Remote OS Version: Ubuntu 22.04.3 LTS
- Remote Extension/Connection Type: WSL2

- Logs: no idea how to get

Steps to Reproduce:

1. Open VSCode connected to WSL
2. Open terminal in VSCode
3. Type `code` in terminal
4. Get error:
    ```sh
    Unable to connect to VS Code server: Error in request.
    Error: connect ENOENT /run/user/1000/vscode-ipc-ffd819f4-90ac-45c2-8701-ce64c4a15f80.sock
        at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
      errno: -2,
      code: 'ENOENT',
      syscall: 'connect',
      address: '/run/user/1000/vscode-ipc-ffd819f4-90ac-45c2-8701-ce64c4a15f80.sock'
    }
    ```

Video, in upper left I have VSCode terminal in local, upper left is Windows terminal inside WSL and bottom is broken VSCode terminal in WSL

https://github.com/microsoft/vscode-remote-release/assets/6796697/6fdc761c-7d83-42a5-a94d-b8ac81b9b7c1

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by Dawn-K** [comment]
I also encountered the same problem, also with WSL2.
The solution I initially used was to set the /run/$USER directory to be owned by USER, that is, `chown $USER /run/user/$USER`. This worked at first, but today I found that it didn't work again.
I continued to browse the issue and found a few that may be useful, but they are not a radical solution: #6997 . This indicates that there is actually an available link, but I don’t know why. The `VSCODE_IPC_HOOK_CLI` in the environment variable seems to point to a link that does not exist, but through `VSCODE_IPC_HOOK_CLI=$( lsof | grep $UID/vscode-ipc | awk ' {print $(NF-1)}' | head -n 1 )
`I was able to find a working link, I tried it and it did solve the problem. I hope the authorities can resolve this issue as soon as possible. Unfortunately I have never been able to reproduce this problem, it always appears suddenly and cannot be restored on its own.


My PC information:
`CPUs | Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: enabled_on direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: enabled
Load (avg) |  
Memory (System) | 23.87GB (11.93GB free)
Process Argv | --crash-reporter-id b93aeb5f-3964-4439-97fe-5de6e9a03b47
Screen Reader | no
VM | 0%`

`Extension | Author (truncated) | Version
-- | -- | --
language-x86-64-assembly | 13x | 3.1.4
better-cpp-syntax | jef | 1.17.2
jupyter-keymap | ms- | 1.1.2
remote-ssh | ms- | 0.107.1
remote-ssh-edit | ms- | 0.86.0
remote-wsl | ms- | 0.81.8
vscode-icons | vsc | 12.6.0
vim | vsc | 1.27.1
python | ms- | 2023.22.0
vscode-pylance | ms- | 2023.11.10
cpptools | ms- | 1.18.5`

`vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30917259`

**Comment by McSneaky** [comment]
I was able to reproduce it 100% of the time. Got it solved by:
- Uninstall WSL2 distro
- Uninstall VSCode
- Manually find and delete everything that seems like leftover from VSCode (settings, plugins, everything)
- Reinstall WSL2
- Reinstall VSCode
- Take 2 days to set up WSL2 distro again 

I wouldn't consider: "Format and reinstall OS" a fix tho 😅

**Comment by McSneaky** [comment]
Aaand it's back :) 
Any log or info I can provide? Don't really want to reinstall whole OS and tooling just to have it working for ~4 hours

**Comment by McSneaky** [comment]
Found some workarounds in here: https://github.com/microsoft/vscode/issues/157275

Might come handy for someone. None of those workarounds work for me tho

**Comment by Dawn-K** [comment]
@McSneaky I found a way that may alleviate your troubles, which is to delete all vscode-*.sock under /run/user/$USER, then close vscode, and then reopen vscode. Although I don't think this is a radical solution, it may be able to temporarily help you...

**Comment by McSneaky** [comment]
That works for just about a minute or so. Then VSCode breaks down again :|

**Comment by McSneaky** [comment]
Solved by https://github.com/microsoft/vscode/issues/157275#issuecomment-1890408573

> loginctl enable-linger $(whoami) 

And then restart WSL with `wsl --shutdown` in Powershell

**Comment by janelznic** [comment]
I fixed it with following solution:

1. End the session in VS Code's command line:
    `exit`
3. Close VS Code in Windows.
4. Run PowerShell console.
   * Try to stop running WSL distro with VS Code stored data (usually stored in location `~/.vscode-server`):
      `wsl -t Ubuntu-22.04`
   * You can list all distros with:
     `wsl -l -v`
5. Run VS Code again.
6. In VS Codes's command line try to start server again in project root folder with:
    `code .`
