### ISSUE TITLE
deveco

### ISSUE THREAD

**Issue by Mead0527** [microsoft/vscode-remote-release#9299]
![image](https://github.com/microsoft/vscode-remote-release/assets/129639038/c843e416-3084-4b94-9181-50d0e29545b7)

**Comment by bamurtaugh** [comment]
Thanks for opening. It looks like this is an issue with an extension named Deveco. I'd recommend filing an issue with the Deveco extension's authors, as this repository is for the Remote Development extensions. If this issue does relate to remote though, please let us know.
