### ISSUE TITLE
RVM dotfiles (.ruby-version/.ruby-gemset) are not read

### ISSUE THREAD

**Issue by hoffmanilya** [microsoft/vscode-remote-release#930]
When using RVM (Ruby version manager) the current Ruby version and gemset name to use are indicated using dotfiles. The shell correctly sets the current version/gemset while VS code remote does not.

- VSCode Version: 1.36.0
- Local OS Version: Windows_NT x64 10.0.18362
- Remote OS Version: Ubuntu 18.04 
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Install RVM and add `.ruby-version` and `.ruby-gemset` files indicating the current projects respective version and gemset name.
2. Launch VS Code remote using `code .` from within WSL.
3. Neither VS Code nor the terminal sets the correct Ruby version/gemset. This prevents extensions that rely on Gems from working.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Once the terminal is launched, if I `cd ..` and then `cd my_project` it will correctly set the Ruby version/gemset. However this still doesn't help with extensions.

The only thing I've found to work right now is explicitly adding `rvm use ruby-2.5.1@my_project` to `.bashrc` which obviously prevents me from working on multiple projects.

Any ideas on how to fix this so VS Code remote picks up the correct gemset/name?

**Comment by roblourens** [comment]
> The shell correctly sets the current version/gemset while VS code remote does not.

What does it do exactly? Not clear what is supposed to happen.

**Comment by hoffmanilya** [comment]
@roblourens Apologies if the original issue was unclear.

With RVM I can use different Ruby versions and "gemsets" for different projects. For example, I would create the following:

`echo ruby-2.5.1 > /my_project/.ruby-version`
`echo my_project > /my_project/.ruby-gemset`

Now when I `cd /my_project/` RVM will automatically set the correct Ruby version and gemset to use. If I change directories to another project RVM will set that project's respective Ruby version and gemset. 

However, when I open up WSL and execute `code .` within my project's directory VSCode does not pick up the correct Ruby version/gemset. Any extensions that rely on Gems fail with a "Gem not found" error and the Terminal (within VSCode) produces the same result.

As a temporary workaround I've added the following to my `.bashrc` script: `rvm use ruby-2.5.1@my_project`. This explicitly tells RVM which Ruby version/gemset to use. This works but prevents me from being able to work on multiple projects at once (since VSCode is always going to be loading a shell with the explicit version/gemset.) 

Please let me know if you need any more info here. Thanks a lot!

**Comment by roblourens** [comment]
VS Code doesn't know anything about Ruby or RVM so I don't see how this is an issue with vscode. Isn't it Ruby's job to detect the `.ruby-version` file? 

Is there some environment variable set or program that needs to be called? I don't know what actually is supposed to happen to make this work.

**Comment by hoffmanilya** [comment]
From what I understand, RVM is loaded by sourcing it from the `.bashrc` script (e.g. `source /etc/profile.d/rvm.sh`).

It turns out that RVM isn't triggered unless your change directories so opening up VSCode in the current directory wasn't triggering the hook to read the gemset/version files. I managed to fix this by adding `cd .` to my `.bashrc` script. This fixed the issue in the VSCode terminal and now that correctly loads the Ruby version/gemset.

However, any extensions that rely on Gems still fail with a "gem not found" error. Any ideas on what I could try to troubleshoot that? 

Thanks for your help.

**Comment by roblourens** [comment]
Ok, maybe the environment is still not correct somehow. I don't know enough about Ruby or RVM to help any more, sorry.
