### ISSUE TITLE
[Remote-SSH Bug]: Socket Connection Compatibility

### ISSUE THREAD

**Issue by huangyxi** [microsoft/vscode-remote-release#9300]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

command `code` is available when `remote.SSH.remoteServerListenOnSocket` enabled

### Steps To Reproduce

1. set `remote.SSH.remoteServerListenOnSocket` as enabled
2. connect to any SSH remote server
3. run command `code` in the remote terminal
4. error raised

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
Unable to connect to VS Code server: Error in request.
Error: connect ENOENT /run/user/1001/vscode-ipc-1a7a14a7-06b0-4665-80e2-03eca136e70b.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/run/user/1001/vscode-ipc-1a7a14a7-06b0-4665-80e2-03eca136e70b.sock'
}
```

</p>
</details>

**Comment by joshspicer** [comment]
I can no longer repro this issue.  

I tests with `useLocalServer` disabled  and enabled `AllowStreamLocalForwarding` on my remote's SSH server (like `remote.SSH.remoteServerListenOnSocket` says to do).

Please feel free to re-open if you can repro. If you do re-open, please include your entire Remote - SSH logs so I can compare my settings and environment with yours. Thanks.
