### ISSUE TITLE
Remote SSH to Alpine Linux downloads incorrect binary, works otherwise

### ISSUE THREAD

**Issue by robbertkl** [microsoft/vscode-remote-release#9315]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: macOS 14.1.1

Steps to Reproduce:

1. Use Remote SSH to connect to a Alpine Linux host

I know Alpine Linux is unsupported for Remote SSH, but got it working fine with a simple change.

On my host, I created this simple wget wrapper (which I saved to `/usr/local/bin/wget`) to replace the package that is automatically downloaded by the installer.

```shell
#!/bin/bash

args=("${@}")

for ((i=0; i < $#; i++))
do
  args[$i]=$(echo "${args[$i]}" | sed 's/server-linux-x64/server-linux-alpine/g')
done

exec /usr/bin/wget "${args[@]}"
```

After this, it works great. The only "issues" I have:
- I see a few glibc/musl related errors in the Remote SSH output after connecting, but it still continues with the install and succeeds
- I get the `The remote host may not meet VS Code Server's prerequisites for glibc and libstdc++` warning in my client after connecting

Seems like it would be pretty easy to support Alpine Linux for Remote SSH, just by downloading a different package.

**Comment by roblourens** [comment]
Does this work if you set `"remote.SSH.useExecServer": true`?

**Comment by robbertkl** [comment]
Yes, also seems to work with `"remote.SSH.useExecServer": true` (which was default off for me).

In fact, using this already works out of the box with Alpine? I don't need the wget wrapper to rewrite the URL and it also does not give me any errors in the output or warning notification!

So Alpine Linux is already working with `remote.SSH.useExecServer` turned on? Are there any downsides to enabling it?

**Comment by roblourens** [comment]
Yes, I think we never properly enabled this before, but we are moving towards useExecServer as the default in the future, so I will close this.

**Comment by robbertkl** [comment]
Great, thanks for the quick response and glad to find out it's working without any workarounds!
