### ISSUE TITLE
remote ssh tunnels does restart on reboot

### ISSUE THREAD

**Issue by pascal456** [microsoft/vscode-remote-release#9320]
I have gone through many of the other issues about remote tunnels not starting on reboot. I think this is a little different. There seems to be something wrong in my configuration or something else ...

also, when I start the tunnel `--random-name` does not work. it starts with the name of the machine

- VSCode Version: 1.85.1
- Local OS Version: Windows 10 22H2 19045.3803
- Remote OS Version: Ubuntu 22.04.3 LTS
- Remote Extension/Connection Type: Server

- Logs: which do you need?

# Steps to Reproduce:

## check status

```
➜  ~ code tunnel status
{"tunnel":null,"service_installed":false}
```
## start the tunnel
```
code tunnel --random-name
```
```
➜  ~ code tunnel --random-name
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
[2023-12-16 23:38:05] info Using Github for authentication, run `code tunnel user login --provider <provider>` option to change this.
To grant access to the server, please log into https://github.com/login/device and use code ...
```
## follow link, enter code
```
[2023-12-16 23:39:00] info Creating tunnel with the name: zm2ws1

Open this link in your browser https://vscode.dev/tunnel/zm2ws1
```
## then starting the service
```
➜  ~ code tunnel service install
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
[2023-12-16 23:43:34] info Successfully registered service...
[2023-12-16 23:43:34] info Successfully enabled unit files...
[2023-12-16 23:43:34] info Tunnel service successfully started
[2023-12-16 23:43:34] info Tip: run `sudo loginctl enable-linger $USER` to ensure the service stays running after you disconnect.
Service successfully installed! You can use `code tunnel service log` to monitor it, and `code tunnel service uninstall` to remove it.
```

## Now I can connect, and also the tunnel is shown online on my client that I want to connect from
![grafik](https://github.com/microsoft/vscode-remote-release/assets/21061035/d1cd92b5-36ba-4fe8-9455-6edbe0162047)

## after a reboot:
`code tunnel status`
```json
{"tunnel":{"name":null,"started_at":"2023-12-16T22:51:30.924805170Z","tunnel":"Disconnected","last_connected_at":null,"last_disconnected_at":null,"last_fail_reason":null},"service_installed":true}
```
mind the `Disconnected` status. The service is running though.

## logs say that the authorization cannot succeed (`code tunnel service log`):
<details>
<summary> see service logs </summary>

```
➜  ~ code tunnel service log
● code-tunnel.service - Visual Studio Code Tunnel
     Loaded: loaded (/home/pascal/.config/systemd/user/code-tunnel.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-12-16 23:50:45 CET; 2min 22s ago
   Main PID: 1971 (code-tunnel)
      Tasks: 9 (limit: 19019)
     Memory: 5.8M
        CPU: 94ms
     CGroup: /user.slice/user-1001.slice/user@1001.service/app.slice/code-tunnel.service
             └─1971 /snap/code/148/usr/share/code/bin/code-tunnel --verbose --cli-data-dir /home/pascal/.vscode/cli tunnel service internal-run
Dez 16 23:52:18 zm2ws1 code-tunnel[1971]: [2023-12-16 23:52:18] trace refresh poll failed, retrying: Error getting authorization: authorization_pending The authorization request is still pending.
Dez 16 23:52:24 zm2ws1 code-tunnel[1971]: [2023-12-16 23:52:24] trace refresh poll failed, retrying: Error getting authorization: authorization_pending The authorization request is still pending.
Dez 16 23:52:29 zm2ws1 code-tunnel[1971]: [2023-12-16 23:52:29] trace refresh poll failed, retrying: Error getting authorization: authorization_pending The authorization request is still pending.
Dez 16 23:52:34 zm2ws1 code-tunnel[1971]: [2023-12-16 23:52:34] trace refresh poll failed, retrying: Error getting authorization: authorization_pending The authorization request is still pending.
Dez 16 23:52:39 zm2ws1 code-tunnel[1971]: [2023-12-16 23:52:39] trace refresh poll failed, retrying: Error getting authorization: authorization_pending The authorization request is still pending.
Dez 16 23:52:44 zm2ws1 code-tunnel[1971]: [2023-12-16 23:52:44] trace refresh poll failed, retrying: Error getting authorization: authorization_pending The authorization request is still pending.
Dez 16 23:52:49 zm2ws1 code-tunnel[1971]: [2023-12-16 23:52:49] trace refresh poll failed, retrying: Error getting authorization: authorization_pending The authorization request is still pending.
Dez 16 23:52:54 zm2ws1 code-tunnel[1971]: [2023-12-16 23:52:54] trace refresh poll failed, retrying: Error getting authorization: authorization_pending The authorization request is still pending.
Dez 16 23:53:00 zm2ws1 code-tunnel[1971]: [2023-12-16 23:53:00] trace refresh poll failed, retrying: Error getting authorization: authorization_pending The authorization request is still pending.
Dez 16 23:53:05 zm2ws1 code-tunnel[1971]: [2023-12-16 23:53:05] trace refresh poll failed, retrying: Error getting authorization: authorization_pending The authorization request is still pending.
Dez 16 23:53:10 zm2ws1 code-tunnel[1971]: [2023-12-16 23:53:10] trace refresh poll failed, retrying: Error getting authorization: authorization_pending The authorization request is still pending.
```
</details>

Cannot connect to remote machine.
![grafik](https://github.com/microsoft/vscode-remote-release/assets/21061035/1c9d6c75-a70f-4a5a-9758-708a4a88b0dc)

## run `code tunnel` again after reboot
I have to run the command again (via ssh) to start the tunnel
```
➜  ~ code tunnel
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Connected to an existing tunnel process running on this machine.
```
But I cannot connect to this. And when I run `code unregister` I can still see the tunnel
```
➜  ~ code tunnel kill
➜  ~ code tunnel status
{"tunnel":{"name":null,"started_at":"2023-12-16T23:04:31.492750178Z","tunnel":"Disconnected","last_connected_at":null,"last_disconnected_at":null,"last_fail_reason":null},"service_installed":true}
➜  ~ code tunnel unregister
➜  ~ code tunnel status
{"tunnel":{"name":null,"started_at":"2023-12-16T23:04:41.534290139Z","tunnel":"Disconnected","last_connected_at":null,"last_disconnected_at":null,"last_fail_reason":null},"service_installed":true}
```

But I can run 
```
➜  ~ code tunnel service uninstall
[2023-12-17 00:05:54] info Successfully stopped service...
[2023-12-17 00:05:54] info Tunnel service uninstalled
➜  ~ code tunnel unregister
➜  ~ code tunnel kill
[2023-12-17 00:06:06] error no tunnel process is currently running
➜  ~ code tunnel status
{"tunnel":null,"service_installed":false}
```

# Question

To get it running again, I have to start the setup procedure from the very first steps. This does not really make sense right? I have to be physically at the machine to make a reboot. Is that the intended use case?

# Additional info about host and setup

- A colleague and I are using this workstation.
- We had to restart due to driver install; we have done this remotely, wondering why the machine did not come back online.
- My colleague and I use each an own user account on this machine.
- one thing that I was wandering about is the machine name, whichs is the hosts / workstation DNS name, which is fine and helpful for SSH, but does this harm here?

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by pascal456** [comment]
# further attempts

In the meantime I try to collect some more scenarios and information.

In my next attempt I again deleted the folders `.vscode`, `.vscode-server` on the remote machine.

again I checked if everything is reset, nothing is running. so commands were like in the following:
```sh
code tunnel status
code tunnel prune
code tunnel kill
>> cannot because no tunnel is running (or similar)
code tunnel restart
>> cannot because no tunnel is running (or similar)
rm -r .vscode-server
```
service was marked being uninstalled at this point:
```
{"tunnel":null,"service_installed":false}
```

Then I started a new tunnel
```
code tunnel
```
stopped it and renamed it
```
code tunnel rename zm2ws1-pascal
```
started again to check its name
```
code tunnel
```
then on the connecting / local machine I checked the connection with the running tunnel from right above. this was fine, like I would expect.

Then stopped it again.

Status was shown as disconnected. OK, would expect that. And then install the service again.

```
code tunnel service install
```
Then connection was possible again. OK, would expect that. Now I rebooted (without actions on the remote machine, i.e. no login of the corresponding user at the machine) and this was working fine now. (like I would expect).
# before 
but before this was not possible unless the user logged in and started the tunnel again.
```
code tunnel
```
`>>> reusing existing tunnel` (or similar)

sometimes even this was not working, and I had to go through the authentication again.


# result

for whatever reason. It is working now. I did everything in the same way except renaming the tunnel on the remote system (after creation, from `zm2ws1` to `zm2ws1-pascal`) with the same user as before.

In all the steps, when starting the tunnel, authentication was necessary (by visiting the given webaddress and typing in shown code).

Is it possible that the problem was not on the remote's site but on the connecting machine's site? Something like an old cache that was holding information about the tunnel `zm2ws1`? because after renaming the problem seemed to disappear.

**Comment by vorburger** [comment]
> logs say that the authorization cannot succeed (code tunnel service log):
> Dez 16 23:52:34 zm2ws1 code-tunnel[1971]: [2023-12-16 23:52:34] trace refresh poll failed, retrying: Error getting authorization: authorization_pending The authorization request is still pending.

https://github.com/vorburger/vorburger.ch-Notes/blob/develop/security/vsc-token.md blog post from me may interest you?

I still couldn't get it to work though - this just seems to be broken (at least for me). 😢

**Comment by pascal456** [comment]
In my case the `code tunnel user login` is not changing the situation that the authorization request is unsuccessful / pending.

Additionally, using the `code tunnel user` command also throws an error:
```
➜  ~ code tunnel user show
Warning: 'sandbox' is not in the list of known options for subcommand 'user'
not logged in
```

I found a solution that works since a while now. But it does not feel like the intended usage:
1. restart server / workstation / the service
2. check `code tunnel service log`. When it works, fine. When not the messages about pending authentication will show up. Also in the logs, there should be the instuctions on how to proceed with the authentication (visit url... put in code AAAA-AAAA).
3. from there on the service is running and working, also after machine / service restart

**Comment by connor4312** [comment]
Github only keeps the 10 most recently used access tokens active. New versions of the CLI attempt to keep the token in-used by "pinging" a github endpoint every hour, but if the token expires or is revoked for whatever reason we must ask for login again.

You may also try logging in with Microsoft auth which does a proper refresh flow and should not have this issue -- though it does have a shorter expiration window and if the device is off for longer than that period of time we have to ask for authentication again.
