### ISSUE TITLE
Additional features config passed to dev container CLI

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#9325]
> I'm also experiencing this issue at the moment. Digging into the container log files, I see this:
> 
> ```
> 
> [6388 ms] Dev Containers 0.327.0 over Remote - SSH 0.107.1 in VS Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c).
> 
> [6388 ms] Start: Run: /bin/sh 
> 
> [6400 ms] Start: Run in host: echo ~
> 
> [6451 ms] /home/adener
> 
> [6451 ms] 
> 
> [6452 ms] Start: Run in host: id -un
> 
> [6505 ms] adener
> 
> [6505 ms] 
> 
> [6506 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'adener' || grep -E '^adener|^[^:]*:[^:]*:adener:' /etc/passwd || true)
> 
> [6558 ms] userEnvProbe: loginInteractiveShell (default)
> 
> [6558 ms] userEnvProbe: not found in cache
> 
> [6558 ms] userEnvProbe shell: /bin/bash
> 
> [6866 ms] userEnvProbe PATHs:
> 
> Probe:     '/home/adener/Developer/scripts/git-custom-commands:/home/adener/Developer/dotfiles/.pyenv/plugins/pyenv-virtualenv/shims:/home/adener/Developer/dotfiles/.pyenv/shims:/home/adener/Developer/dotfiles/.pyenv/bin:/usr/local/cuda/bin:/home/adener/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/p4v/bin/:/opt/pycharm-community-2020.3.3/bin'
> 
> Container: None
> 
> [6965 ms] Start: Run: docker version --format {{.Server.APIVersion}}
> 
> [7021 ms] 1.43
> 
> [7493 ms] Start: Run: tar --no-same-owner -x -f -
> 
> [7568 ms] Start: Run: /home/adener/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/node /home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/adener/Developer/code/te-jax-dev --log-level debug --log-format json --config /home/adener/Developer/code/te-jax-dev/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root --additional-features {"extensions.verifySignature":false}
> 
> [7758 ms] @devcontainers/cli 0.54.1. Node.js v18.15.0. linux 6.2.0-36-generic x64.
> 
> [7758 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/adener/Developer/code/te-jax-dev --filter label=devcontainer.config_file=/home/adener/Developer/code/te-jax-dev/.devcontainer/devcontainer.json
> 
> [7779 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/adener/Developer/code/te-jax-dev
> 
> [7794 ms] Resolving Feature dependencies for 'extensions.verifySignature'...
> 
> [7795 ms] * Processing feature: extensions.verifySignature
> 
> [7795 ms] Legacy feature 'extensions.verifySignature' not supported. Please check https://containers.dev/features for replacements.
> 
> [7797 ms] Error: Legacy feature 'extensions.verifySignature' not supported. Please check https://containers.dev/features for replacements.
> 
>     at yJ (/home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:390:4619)
> 
>     at tC (/home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:390:6575)
> 
>     at Q (/home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:390:1751)
> 
>     at q7 (/home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:285:24126)
> 
>     at AC (/home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:285:26717)
> 
>     at Su (/home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:285:26943)
> 
>     at vu (/home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:390:1824)
> 
>     at async _eA (/home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:35175)
> 
> [7779 ms] Exit code 1
> 
> ```
> 
> 
> 
> It looks like Dev Containers extension attempts to launch with a  `--additional-features {"extensions.verifySignature":false}` feature, which is no longer supported and errors out.
> 
> 
> 
> My `devcontainer.json` is very barebones because it uses a compose file:
> 
> ```
> 
> {
> 
>     "name": "TE-JAX Development",
> 
>     "dockerComposeFile": [ "/home/adener/Developer/containers/docker-compose.yaml" ],
> 
>     "service": "te-jax-dev",
> 
>     "overrideCommand": false,
> 
>     "workspaceFolder": "/home/adener/Developer/code/te-jax-dev"
> 
> }
> 
> ```
> 
> 
> 
> There's nothing in here that has anything to do with the `{"extensions.VerifySignature": false}` option. I also don't have that in my `settings.json` either. It appears to be hard-coded into Dev Containers, with no way to control/disable/override in the settings.
> 
> 
> 
> I'm wondering if Dev Containers could be mistaking this as an error from the `devcontainers.json` file, refusing to use what it sees as a faulty configuration, and instead asking the user to select a different container from its preconfigured options.
> 
>  

 _Originally posted by @denera in [#9302](https://github.com/microsoft/vscode-remote-release/issues/9302#issuecomment-1854163119)_

**Comment by chrmarti** [comment]
Could you check your user settings JSON for an entry for `dev.containers.defaultFeatures` (`F1` > `Preferences: Open User Settings (JSON)`)? That is where the value for `--additional-features` is read from. Where is `extensions.VerifySignature` in that JSON?

Note from #9302: It seems setting `initializeCommand` to some arbitrary command in the devcontainer.json works around the issue.

**Comment by Chamuelm** [comment]
Happens on M3 Macbook Pro with the "initializeCommand" workaround working, newly installed mac with no `dev.containers.defaultFeatures` configured in user, workspace and remote settings.
