### ISSUE TITLE
Remote SSH extension ignores localServerDownload setting

### ISSUE THREAD

**Issue by jjunac** [microsoft/vscode-remote-release#9330]
Type: <b>Bug</b>

Hello,

While updating from 1.84 to 1.85.1, it's now impossible for me to remote SSH to a VM disconnected for the internet.
I still have "remote.SSH.localServerDownload" set "always", however in the extension logs I can see that the wrong value is passed:
`[11:24:50.239] "remote.SSH.localServerDownload": off`
I've tried disabling/re-enabling the setting. Same issue with remote SSH pre-release and with Insider commit 9621add46007f7a1ab37d1fce9bcdcecca62aeb0 . I've tried as well downgrading the remote SSH extension, same issue, so I guess the problem is caused by VSCode and not the extension.

Please advise, thanks !

Extension version: 0.107.1
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 15, 14|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jjunac** [comment]
Ok solved !
For some reason an older deprecated settings `remote.SSH.allowLocalServerDownload` started to conflit with localServerDownload. Removing it solved the issue.

**Comment by haorzhan** [comment]
> Ok solved ! For some reason an older deprecated settings `remote.SSH.allowLocalServerDownload` started to conflit with localServerDownload. Removing it solved the issue.

Hi @jjunac how did you remove it? I am having the same issue

**Comment by jjunac** [comment]
@haorzhan You have to open the settings.json file, and search for all `remote.SSH` settings.
The greyed out ones are not used anymore, the ones with the yellow squiggle are deprecated.
`remote.SSH.allowLocalServerDownload` was listed as deprecated and I removed it.
Hope it helps :)
