### ISSUE TITLE
[Remote-SSH Bug]: VSCode remote server related files are re-downloaded on remote machine if multiple users try to access it

### ISSUE THREAD

**Issue by saransappa** [microsoft/vscode-remote-release#9340]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

User1 connects to the remote machine using the Remote-SSH extension. Then, VSCode remote server-related files are downloaded on the remote machine and everything works fine. But when User2 tries to do the same, the VSCode remote server-related files are re-downloaded. 

In my case, the remote machine is an ARM machine with limited memory. So, User2 is unable to use the Remote-SSH as there is no space left to download the VSCode remote server related files again.

### Expected Behavior

As the VSCode remote server-related files are already present, I would like the VSCode to figure it out and skip re-downloading those files.

### Steps To Reproduce

1. User1 connects to a remote machine -> VSCode remote server setup is done by downloading some files
2. User2 connects to the same remote machine -> VSCode remote server setup is done again by downloading some files that are already available

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/6429
