### ISSUE TITLE
Dev Containers - Mounted directory not available inside Dockerfile

### ISSUE THREAD

**Issue by nayaran** [microsoft/vscode-remote-release#9342]
Issue Type: <b>Bug</b>

I am exploring dev containers but have hit an issue. My company uses SSL forward proxy (Palo Alto firewall) so by default all HTTPS connections initiated from the container fail since the default ca-bundle available inside the container doesn't have the certificates used by the SSL forward proxy. This essentially means that I am not able to install any packages due to SSL errors.

So I need to manually install these certificates in the container before installing any packages. Based on https://code.visualstudio.com/remote/advancedcontainers/add-local-file-mount, I tried mounting the directory containing the certificate and installing it manually using the following configuration - 

`.devcontainer/devcontainer.json`
```
{
	"name": "Python 3",
	"build": {
		"dockerfile": "Dockerfile",
		"context": "..",
		"args": { 
			"VARIANT": "3.11"
		}
	},
    "mounts": ["source=/etc/pki/ca-trust/extracted/pem/,target=/home/root/host-certs,type=bind,consistency=cached"]
}
```

`.devcontainer/Dockerfile`
```
ARG VARIANT="3.11"
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}

RUN cp /home/root/host-certs/tls-ca-bundle.pem /usr/local/share/ca-certificates/ca-bundle.crt
RUN echo "/usr/local/share/ca-certificates/ca-bundle.crt" | sudo tee -a /etc/ca-certificates.conf
RUN update-ca-certificates
```

But the container build fails with following error (Full logs are attached)
```
 > [2/4] RUN cp /home/root/host-certs/tls-ca-bundle.pem /usr/local/share/ca-certificates/ca-bundle.crt:
0.556 cp: cannot stat '/home/root/host-certs/tls-ca-bundle.pem': No such file or directory
------
```
However, if I comment out all the RUN commands from the Dockerfile, the container builds successfully and once I am inside the container, I am able to install the certificate.

Looks like the mounted directory is not available until the container is built. I am new to Docker so not sure if this is the expected behavior. But I'd really appreciate some help in solving this issue.

Note - One workaround that I found was to specify the commands to install the certificates in a bash script and then run that script as part of `postCreate` command. But then the main purpose of Dockerfile gets defeated since I'll have to put everything in that script since installation of certificate is a prerequisite for basically all the steps that I need to do to setup the dev environment.

Extension version: 0.245.2
VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Connection to 'SSH: narayan-dev-apse1.w
[docker_logs.txt](https://github.com/microsoft/vscode-remote-release/files/13759780/docker_logs.txt)
orkspaces.corp.win.ia55.net' could not be established  Canceled
Remote OS version: Linux x64 5.15.139-93.147.amzn2.x86_64
Remote OS version: Linux x64 5.15.139-93.147.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.44GB (14.36GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bnarayan-dev-apse1.workspaces.corp.win.ia55.net/home/narayan/code/slack-status-sync --crash-reporter-id 45b888ba-a57c-4e11-998d-182f619416a4|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: narayan-dev-apse1.workspaces.corp.win.ia55.net' could not be established  Canceled

|Item|Value|
|---|---|
|Remote|SSH: narayan-dev-apse1.workspaces.corp.win.ia55.net|
|OS|Linux x64 5.15.139-93.147.amzn2.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz (4 x 2500)|
|Memory (System)|15.43GB (1.48GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: narayan-dev-apse1.workspaces.corp.win.ia55.net|
|OS|Linux x64 5.15.139-93.147.amzn2.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz (4 x 2500)|
|Memory (System)|15.43GB (1.48GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
89544117:30613380
showlangstatbar:30737416
0bi6i642:30917235
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184c:30925681

```

</details>

**Comment by chrmarti** [comment]
Mount points are only available once the container runs. The Dockerfile is run before that to build the image.

Try adding an additional context in the devcontainer.json:
```jsonc
{
	// ...
	"build": {
		// ...
		"options": [
			"--build-context", "host-certs=/etc/pki/ca-trust/extracted/pem/"
		]
	}
}
```

And then use that in the Dockerfile:
```Dockerfile
# ...
COPY host-certs/tls-ca-bundle.pem /tmp/host-ca-certificates.crt
RUN csplit -f /usr/local/share/ca-certificates/host-ca-certificate- -b '%02d.pem' -z -s /tmp/host-ca-certificates.crt '/-----BEGIN CERTIFICATE-----/' '{*}'
RUN update-ca-certificates
# ...
```

This might adjusting to your specific case. The `csplit` might be needed because only single certificates per file are supported. Please check and let me know if that works.
