### ISSUE TITLE
Not obvious enough when connection fails due to port forwarding being disabled

### ISSUE THREAD

**Issue by FreudGit** [microsoft/vscode-remote-release#9343]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

**- remote.SSH.useLocalServer = true:**

VS code freeze with 'opening remote'

Log: > * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
>  
[14:50:43.577] > Checking server status on port 36915 with wget
[14:50:43.583] > 7bf3709180b4: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==36915==
> osReleaseId==Linux==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1017==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken==a1a11111-11a1-1111-1a11-111a1aa1a1a1==
> 7bf3709180b4: end
[14:50:43.584] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==36915==
osReleaseId==Linux==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1017==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==a1a11111-11a1-1111-1a11-111a1aa1a1a1==

[14:50:43.584] Remote server is listening on port 36915
[14:50:43.584] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":36915},"osReleaseId":"Linux","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1017","platform":"linux","connectionToken":"a1a11111-11a1-1111-1a11-111a1aa1a1a1"},"installUnpackCode":""}
[14:50:43.585] Persisting server connection details to /Users/francoisviglob/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-7b2fb61d-0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2-0.108.2023112915-tr/data.json
[14:50:43.587] Starting forwarding server. local port 54104 -> socksPort 54058 -> remotePort 36915
[14:50:43.588] Forwarding server listening on port 54104
[14:50:43.588] Waiting for ssh tunnel to be ready
[14:50:43.589] Tunneled port 36915 to local port 54104
[14:50:43.589] Resolved "ssh-remote+184.107.95.214" to "port 54104"
[14:50:43.590] [Forwarding server port 54104] Got connection 0
[14:50:43.593] ------

[14:50:43.599] [Forwarding server port 54104] Got connection 1
[14:50:43.681] Failed to set up socket for dynamic port forward to remote port 36915: Socket closed. Is the remote port correct?
[14:50:43.693] Failed to set up socket for dynamic port forward to remote port 36915: Socket closed. Is the remote port correct?
[14:50:47.775] > local-server-1> Timed out
[14:50:47.784] Local server exit: 0

**- remote.SSH.useLocalServer = false:**, result: VS code freeze with 'opening remote'

log:
Acquiring lock on /home/francoisdevviglo/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/vscode-remote-lock.francoisdevviglo.0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Found existing installation at /home/francoisdevviglo/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2...
Checking /home/francoisdevviglo/.vscode-server/.0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.log and /home/francoisdevviglo/.vscode-server/.0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.pid for a running server
Looking for server with pid: 3730510
Found running server...
 
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
 
Checking server status on port 36915 with wget
9f987f195e9c: start
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==36915==
osReleaseId==Linux==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1017==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==f4d13564-46c8-4210-9d39-766f5bb0b4e8==
9f987f195e9c: end
channel 3: open failed: administratively prohibited: open failed
channel 4: open failed: administratively prohibited: open failed

### Expected Behavior

I expect to see a successfull connection, like the ssh in the terminal. :)

### Steps To Reproduce

vscode: 1.85.1
macos 11.7

### Remote-SSH Log

Acquiring lock on /home/francoisdevviglo/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/vscode-remote-lock.francoisdevviglo.0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Found existing installation at /home/francoisdevviglo/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2...
Checking /home/francoisdevviglo/.vscode-server/.0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.log and /home/francoisdevviglo/.vscode-server/.0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.pid for a running server
Looking for server with pid: 3730510
Found running server...
 
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
 
Checking server status on port 36915 with wget
9f987f195e9c: start
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==36915==
osReleaseId==Linux==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1017==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==f4d13564-46c8-4210-9d39-766f5bb0b4e8==
9f987f195e9c: end
channel 3: open failed: administratively prohibited: open failed
channel 4: open failed: administratively prohibited: open failed

**Comment by lvguanjun** [comment]
I have this problem too. vscode: 1.85.1

**Comment by a1k0z** [comment]
I have this problem too. vscode: 1.86.0-insider

**Comment by roblourens** [comment]
> `open failed: administratively prohibited: open failed`

This typically means that tcp port forwarding is disabled on your host, or failed for some reason, please check that. Did it work in the past?

**Comment by bremme** [comment]
Just came here to say thanks @roblourens. After changing `AllowTcpForwarding no` to `AllowTcpForwarding yes` in my `/etc/ssh/sshd_config` file and restarting my sshd service al seems to work fine. I probably overlooked something in the documentation.

It would have helped me if the error message pointed me in the right direction. Like instead of "Is the remote port correct?" "Have you enabled tcp forwarding in your ssh configuration?" or something similar.

**Comment by roblourens** [comment]
Thanks for the suggestion, I'm adding an error notification and some more helpful messages at the bottom of the log, when we detect this case.

**Comment by bremme** [comment]
Cool!
