### ISSUE TITLE
Unable to run [Dev Containers] on remote Linux host

### ISSUE THREAD

**Issue by tzengshinfu** [microsoft/vscode-remote-release#9345]
- VSCode Version: 1.85.1 (user setup) Windows 10
- Local OS Version: Windows 10 professional 22H2 (19045.3031) ZH_TW
Dev Containers: v0.327.0
Remote - SSH: v0.107.1
- Local account: y1938
- Remote OS Version: Ubuntu 20.04.6
- Remote account: y1938
- Remote working directory: /workspace/dev-container
- Remote container configuration: Alpine 3.18

I successfully connect remote Linux host using [Remote - SSH],
but cannot run any container command.
PS: I have deleted the folder `.vscode-*` and reconnected.

Steps to Reproduce:
1. [New Dev Container...]
Logs:
> [50002 ms] Dev Containers 0.327.0 over Remote - SSH 0.107.1 in VS Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2).
> [50001 ms] Start: Run: /bin/sh 
> [50005 ms] Start: Run in host: echo ~
> [50043 ms] /home/y1938
> [50043 ms] 
> [50044 ms] Start: Run in host: id -un
> [50090 ms] y1938
> [50090 ms] 
> [50091 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'y1938' || grep -E '^y1938|^[^:]*:[^:]*:y1938:' /etc/passwd || true)
> [50127 ms] userEnvProbe: loginInteractiveShell (default)
> [50128 ms] userEnvProbe: not found in cache
> [50128 ms] userEnvProbe shell: /bin/bash
> [52132 ms] Start: Run: /bin/sh 
> [52136 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd || echo ; readlink /proc/$pid/ns/mnt || echo ; cat /proc/$pid/stat | tr "
> [53793 ms] userEnvProbe PATHs:
> Probe:     '/home/y1938/.nvm/versions/node/v19.3.0/bin:/home/y1938/.sdkman/candidates/maven/current/bin:/home/y1938/.sdkman/candidates/jbang/current/bin:/home/y1938/.sdkman/candidates/java/current/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/snap/bin:/home/y1938/.dotnet/tools:/opt/oracle/instantclient_12_1'
> Container: None
> [53864 ms] Start: Run: docker version --format {{.Server.APIVersion}}
> [53954 ms] 1.43
> [53954 ms] Start: Run: docker pull alpine:3.16.3
> [54503 ms] Start: Run: docker volume ls -q

Select a container configuration template: Alpine
Logs:
> [78184 ms] userEnvProbe is taking longer than 2 seconds. Process not found.
> [106287 ms] Start: Run: docker volume create --label dev.container.volume=true alpine
> [106372 ms] Start: Run: docker run -d --mount type=volume,src=alpine,dst=/workspaces alpine:3.16.3 sleep infinity
> [107230 ms] Start: Run: D:\Users\y1938\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node d:\Users\y1938\.vscode\extensions\ms-vscode-remote.remote-containers-0.327.0\dist\spec-node\devContainersSpecCLI.js templates apply --workspace-folder C:\Users\y1938\AppData\Local\Temp\tmp-output-dir-1703551300771 --template-id ghcr.io/devcontainers/templates/alpine:latest --template-args {} --features [] --tmp-dir C:\Users\y1938\AppData\Local\Temp\tmp-dir-1703551300771
> [107473 ms] [2023-12-26T00:41:41.010Z] @devcontainers/cli 0.54.1. Node.js v18.15.0. win32 10.0.19045 x64.

After window refresh
Logs:
> [32 ms] Dev Containers 0.327.0 over Remote - SSH 0.107.1 in VS Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2).
> [31 ms] Start: Resolving Remote
> [43 ms] Start: Run: wsl -l -v
> [169 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c echo ~
> [363 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/y1938' && /bin/sh
> [375 ms] Start: Run in host: id -un
> [487 ms] y1938
> [487 ms] 
> [487 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'y1938' || grep -E '^y1938|^[^:]*:[^:]*:y1938:' /etc/passwd || true)
> [489 ms] Start: Run in host: echo ~
> [490 ms] /home/y1938
> [490 ms] 
> [490 ms] Start: Run in host: test -x '/home/y1938/.vscode-remote-containers/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node'
> [491 ms] 
> [491 ms] 
> [491 ms] Exit code 1
> [491 ms] Start: Run in host: test -x '/home/y1938/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node'
> [492 ms] 
> [492 ms] 
> [492 ms] Start: Run in host: test -f '/home/y1938/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node_modules/node-pty/package.json'
> [493 ms] 
> [493 ms] 
> [493 ms] Start: Run in host: test -f '/home/y1938/.vscode-remote-containers/dist/vscode-remote-containers-server-0.327.0.js'
> [494 ms] 
> [494 ms] 
> [496 ms] userEnvProbe: loginInteractiveShell (default)
> [496 ms] userEnvProbe: not found in cache
> [496 ms] userEnvProbe shell: /bin/bash
> [628 ms] userEnvProbe PATHs:
> Probe:     '/home/y1938/.sdkman/candidates/maven/current/bin:/home/y1938/.sdkman/candidates/jbang/current/bin:/home/y1938/.sdkman/candidates/java/current/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files/Common Files/SYSTEM/MSMAPI/1028:/mnt/c/Program Files (x86)/Microsoft SQL Server/160/DTS/Binn/:/mnt/d/Users/y1938/AppData/Roaming/nvm:/mnt/c/Program Files/nodejs:/mnt/d/Users/y1938/AppData/Local/Microsoft/WindowsApps:/mnt/d/Users/y1938/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/d/Users/y1938/.dotnet/tools:/mnt/d/Users/y1938/.jvms:/mnt/c/Program Files/jdk/bin:/mnt/c/Program Files/TortoiseGit/bin:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Program Files/Git/cmd:/Docker/host/bin:/mnt/d/Users/y1938/AppData/Local/Microsoft/WindowsApps:/mnt/d/Users/y1938/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/d/Users/y1938/AppData/Local/Microsoft/WinGet/Links:/mnt/c/Program Files (x86)/Rico Suter/NSwagStudio/:/mnt/c/Program Files/Azure Data Studio/bin:/snap/bin'
> Container: None
> [630 ms] Start: Check Docker is running
> [630 ms] Start: Run: docker version --format {{.Server.APIVersion}}
> [901 ms] Server API version: 1.43
> [902 ms] Start: Run: docker build -f C:\Users\y1938\AppData\Local\Temp\vsch\bootstrap-image\0.327.0\bootstrap.Dockerfile -t vsc-volume-bootstrap C:\Users\y1938\AppData\Local\Temp\vsch\bootstrap-image\0.327.0
> 
> [+] Building 0.5s (10/10) FINISHED                               docker:default
>  => [internal] load build definition from bootstrap.Dockerfile             0.0s
>  => => transferring dockerfile: 570B                                       0.0s
>  => [internal] load .dockerignore                                          0.0s
>  => => transferring context: 2B                                            0.0s
>  => [internal] load metadata for mcr.microsoft.com/devcontainers/base:0-a  0.3s
>  => [internal] load build context                                          0.0s
>  => => transferring context: 747B                                          0.0s
>  => [1/5] FROM mcr.microsoft.com/devcontainers/base:0-alpine-3.16@sha256:  0.0s
>  => CACHED [2/5] RUN echo "@old https://dl-cdn.alpinelinux.org/alpine/v3.  0.0s
>  => CACHED [3/5] RUN apk add --no-cache  git-lfs  nodejs  python3  npm  m  0.0s
>  => CACHED [4/5] RUN cd && npm i node-pty                                  0.0s
>  => CACHED [5/5] COPY .vscode-remote-containers /root/.vscode-remote-cont  0.0s
>  => exporting to image                                                     0.0s
>  => => exporting layers                                                    0.0s
>  => => writing image sha256:780bd51a11ff2171140bfbc4e95fcaf16a6c234f807c3  0.0s
>  => => naming to docker.io/library/vsc-volume-bootstrap                    0.0s
> 
> View build details: docker-desktop://dashboard/build/default/default/e80q3vxfcsu
> 04f6jiy09u0d1i
> 
> What's Next?
>   View a summary of image vulnerabilities and recommendations → docker scout qu
> ickview
> [2386 ms] Start: Run: docker run -d --mount type=volume,src=alpine,dst=/workspaces -v /var/run/docker.sock:/var/run/docker.sock vsc-volume-bootstrap sleep infinity
> [3015 ms] Start: Run in container: /bin/sh
> [3440 ms] Start: Run in container: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /workspaces/alpine --id-label vsc.devcontainer.volume.name=alpine --id-label vsc.devcontainer.volume.folder=alpine --log-level debug --log-format json --mount-workspace-git-root
> [3941 ms] @devcontainers/cli 0.54.1. Node.js v16.20.2. linux 5.15.133.1-microsoft-standard-WSL2 x64.
> [3941 ms] Error: Dev container config (/workspaces/alpine/.devcontainer/devcontainer.json) not found.
>     at _eA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:34628)
> [3966 ms] Exit code 1
> [3968 ms] Command failed: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /workspaces/alpine --id-label vsc.devcontainer.volume.name=alpine --id-label vsc.devcontainer.volume.folder=alpine --log-level debug --log-format json --mount-workspace-git-root
> [3968 ms] Exit code 1
![New_Dev_Container](https://github.com/microsoft/vscode-remote-release/assets/2170033/05b11897-37e9-45f0-b363-43449b2b7c5d)

2. [Attach to Running Container...]
Logs:
> [9 ms] Dev Containers 0.327.0 over Remote - SSH 0.107.1 in VS Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2).
> [8 ms] Start: Resolving Remote
> [10 ms] Setting up container: /greenlight-v3
> [10 ms] Host authority: ssh-remote+root@api-test.usuntek.com
> [21 ms] Start: Run: docker inspect --type container /greenlight-v3
![Attach_to_Running_Container](https://github.com/microsoft/vscode-remote-release/assets/2170033/4044db3b-b19f-4c50-9c01-d918b946db66)

3. [Add Dev Container Configuration Files...]
Logs:
> [13 ms] Dev Containers 0.327.0 over Remote - SSH 0.107.1 in VS Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2).
> [12 ms] Start: Resolving Remote
> [36 ms] Setting up container for folder or workspace: /workspace/dev-container
> [36 ms] Host authority: ssh-remote+y1938@api-test.usuntek.com
> [37 ms] Start: Run: wsl -l -v
> [159 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c echo ~
> [346 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/y1938' && /bin/sh
> [358 ms] Start: Run in host: id -un
> [462 ms] y1938
> [463 ms] 
> [463 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'y1938' || grep -E '^y1938|^[^:]*:[^:]*:y1938:' /etc/passwd || true)
> [465 ms] Start: Run in host: echo ~
> [465 ms] /home/y1938
> [465 ms] 
> [466 ms] Start: Run in host: test -x '/home/y1938/.vscode-remote-containers/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node'
> [466 ms] 
> [466 ms] 
> [467 ms] Exit code 1
> [467 ms] Start: Run in host: test -x '/home/y1938/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node'
> [467 ms] 
> [467 ms] 
> [467 ms] Start: Run in host: test -f '/home/y1938/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node_modules/node-pty/package.json'
> [468 ms] 
> [468 ms] 
> [468 ms] Start: Run in host: test -f '/home/y1938/.vscode-remote-containers/dist/vscode-remote-containers-server-0.327.0.js'
> [469 ms] 
> [469 ms] 
> [471 ms] userEnvProbe: loginInteractiveShell (default)
> [471 ms] userEnvProbe: not found in cache
> [471 ms] userEnvProbe shell: /bin/bash
> [606 ms] userEnvProbe PATHs:
> Probe:     '/home/y1938/.sdkman/candidates/maven/current/bin:/home/y1938/.sdkman/candidates/jbang/current/bin:/home/y1938/.sdkman/candidates/java/current/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files/Common Files/SYSTEM/MSMAPI/1028:/mnt/c/Program Files (x86)/Microsoft SQL Server/160/DTS/Binn/:/mnt/d/Users/y1938/AppData/Roaming/nvm:/mnt/c/Program Files/nodejs:/mnt/d/Users/y1938/AppData/Local/Microsoft/WindowsApps:/mnt/d/Users/y1938/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/d/Users/y1938/.dotnet/tools:/mnt/d/Users/y1938/.jvms:/mnt/c/Program Files/jdk/bin:/mnt/c/Program Files/TortoiseGit/bin:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Program Files/Git/cmd:/Docker/host/bin:/mnt/d/Users/y1938/AppData/Local/Microsoft/WindowsApps:/mnt/d/Users/y1938/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/d/Users/y1938/AppData/Local/Microsoft/WinGet/Links:/mnt/c/Program Files (x86)/Rico Suter/NSwagStudio/:/mnt/c/Program Files/Azure Data Studio/bin:/snap/bin'
> Container: None
> [608 ms] Start: Check Docker is running
> [608 ms] Start: Run: docker version --format {{.Server.APIVersion}}
> [636 ms] spawn C:\Program Files\Docker\Docker\resources\bin\docker.exe ENOENT
> [637 ms] Docker returned an error code ENOENT, message: spawn C:\Program Files\Docker\Docker\resources\bin\docker.exe ENOENT
![Add Dev Container Configuration Files](https://github.com/microsoft/vscode-remote-release/assets/2170033/929d53cf-21a5-4325-8e62-663a103de30c)

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/9324. Thanks.
