### ISSUE TITLE
[Remote-SSH Bug]:   Include directive stopped working.

### ISSUE THREAD

**Issue by cocoonkid** [microsoft/vscode-remote-release#9349]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

Have at the top
```
Include config.d/*
```
in ~.ssh/config  

I do only see ~.ssh/config  host in the explorer but not ~.ssh/config.d/something hosts anymore.

This worked until very recently.

### Expected Behavior

I can see an select all hosts mentioned in ~.ssh/config.d/something 

references #6352 #4339

### Remote-SSH Log

---

### Anything else?

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.6.8-zen1-1-zen

**Comment by cocoonkid** [comment]
Found the problem :

![image](https://github.com/microsoft/vscode-remote-release/assets/43231640/97300446-013f-4305-9f7c-69106c7615a6)
when something is set it does not work.



when empty it works.

Is that expected behaviour?

**Comment by roblourens** [comment]
I can't repro the issue, it works fine with or without that setting configured. Not sure why that would affect it. What is the value of that setting? And are you sure it's what you describe? Note that you will have to click the refresh button on the explorer to see the effect of changing the setting or config file.
