### ISSUE TITLE
[Remote-SSH Bug]: User Directives from .ssh/config are being shown as remotes.

### ISSUE THREAD

**Issue by cocoonkid** [microsoft/vscode-remote-release#9350]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

User Directives from .ssh/config are being shown as remotes.

### Expected Behavior

User Directives from .ssh/config are being shown should be ignored.

references #6352 #4339

### Steps To Reproduce

Add match directives to config.

![image](https://github.com/microsoft/vscode-remote-release/assets/43231640/9cebbb7b-ed6e-4357-b928-6bdd9b82e644)

![image](https://github.com/microsoft/vscode-remote-release/assets/43231640/db927620-6439-4ea2-86e6-13cb6a27f3eb)

### Anything else?

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.6.8-zen1-1-zen

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/7801
