### ISSUE TITLE
Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)

### ISSUE THREAD

**Issue by cctv130** [microsoft/vscode-remote-release#9354]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Steps To Reproduce
ubuntu server 22.04

install xen-hypervisor-4.18.0-ubuntu-jammy-amd64
echo "GRUB_CMDLINE_XEN_DEFAULT=\"dom0_mem=4096M,max:4096M dom0_max_vcpus=4 dom0_vcpus_pin=1 force-ept=1 ept=ad=0 hap_1gb=0 hap_2mb=0 altp2m=1 hpet=legacy-replacement smt=0\"" >> /etc/default/grub
echo "/usr/local/lib" > /etc/ld.so.conf.d/xen.conf
ldconfig
echo "none /proc/xen xenfs defaults,nofail 0 0" >> /etc/fstab
echo "xen-evtchn" >> /etc/modules
echo "xen-privcmd" >> /etc/modules
echo "xen-gntdev" >> /etc/modules
systemctl enable xencommons.service
systemctl enable xen-qemu-dom0-disk-backend.service
systemctl enable xen-init-dom0.service
systemctl enable xenconsoled.service

reboot

vscode remote ssh  tip:
Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)

### Remote-SSH Log

  GNU nano 6.2                                     /home/botao/.vscode-server/.0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.log                                              
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Server bound to 127.0.0.1:34335 (IPv4)
Extension host agent listening on 34335

[07:31:06]

[07:31:06] Extension host agent started.
Illegal instruction (core dumped)

**Comment by roblourens** [comment]
Please share the log from the Remote-SSH output channel

**Comment by roblourens** [comment]
> `Illegal instruction (core dumped)`

This would be the problem, the remote server or extension host node process crashed. What is the architecture of your remote? Something is wrong, maybe it's not actually compatible with the server

**Comment by roblourens** [comment]
Did it work with previous vscode versions and stop when you upgraded?

You can download past releases from the release notes if you want to test it. https://code.visualstudio.com/updates

**Comment by deepak1556** [comment]
avx instructions are required by the server and we cannot disable them optionally, closing as out of scope.
