### ISSUE TITLE
Remote file picker crashes remote vscode when too many files in unrelated directory

### ISSUE THREAD

**Issue by Cocalus** [microsoft/vscode-remote-release#936]
- VSCode Version: 1.36.0
- Local OS Version: OSX 10.14.5
- Remote OS Version: Ubuntu 14.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. mkdir a temporary folder in the users home.
2. put about 250K files into that directory.
3. SSH remote to that user. Try to open any other folder against that user. 

This happens on insiders as well. It looks like the file picker is trying to look at every file even those in directories that are not related to the path I want to open. Not that I get a chance to enter the path. It does seem to handle a subdir with ~125k files, just takes a while to open.

The picker shouldn't descend into sub directories that aren't related to the path I care about (it just wastes IO). Even if I do enter such a folder it should error gracefully instead of breaking the remote server (logs imply that JS ran out of memory). There should be a way to open a folder by typing the name fully bypassing the file picker if it has issues. 

The only work around I've found is to remote to connect to a account without tons of files, open a folder there. Close VSCode and edit the recent file history to point that entry to the user/folder I wanted to open to begin with.

Note that vscode does handle a folders with 100 of thousands of files in it's workspace, the file watcher (I think for git), just errors saying it can't handle that many files.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by Cocalus** [comment]
It looks like the file picker only descends one level. So I moved all the directories that had tones of files into a sub directory.

**Comment by roblourens** [comment]
> Even if I do enter such a folder it should error gracefully instead of breaking the remote server (logs imply that JS ran out of memory)

Can you share the logs?

How much memory/cpu does your remote have?

**Comment by Cocalus** [comment]
Which log files?

256GB / 48 Cores

**Comment by roblourens** [comment]
You said 

> logs imply that JS ran out of memory

I would like to see whatever you are looking at
