### ISSUE TITLE
Add Dev Container Configuration Files behind corporate proxy -> unable to get local issuer certificate

### ISSUE THREAD

**Issue by Roemer** [microsoft/vscode-remote-release#9361]
We have the an issue that just creating the dev-container configuration files locally (or when connected to the remote WSL2) does not work, It always immediately aborts with the error:
```
[error] Error: unable to get local issuer certificate
	at TLSSocket.onConnectSecure (node:_tls_wrap:1543:34)
	at TLSSocket.emit (node:events:513:28)
	at TLSSocket._finishInit (node:_tls_wrap:962:8)
	at ssl.onhandshakedone (node:_tls_wrap:746:12) remote-containers.createDevContainerFile {"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"}
```
I do have the `NODE_EXTRA_CA_CERTS` set to our certificates on Windows but that seems not to help. The last version of the Dev Containers extension that this still works is 0.255.4 but everything newer (up to the pre-release  0.329.0) fails with the error mentioned above. I went thru all open issues related to similar issues but most of them are regarding issues with installing extensions on the remote / container which we don't have if we just add the `NODE_EXTRA_CA_CERTS` and the certificates into the container as well. The only really matching issue is https://github.com/microsoft/vscode-remote-release/issues/8230 which is closed but it still does not work for us.

- VSCode Version: 1.85.1
- Local OS Version: Windows 10 22H2
- Remote OS Version: WSL2 with Debian
- Remote Extension/Connection Type: Container in WSL

Steps to Reproduce:
1. Be on corporate proxy
2. Try to create new dev container configuration files locally

**Comment by Roemer** [comment]
I now tried with setting the environment variable `NODE_TLS_REJECT_UNAUTHORIZED` to `0` in Windows and that actually made it work. This is a workaround but I don't see any reason why it should not work when `NODE_EXTRA_CA_CERTS` is set to a .pem file with all corporate certificates.

**Comment by chrmarti** [comment]
Recent versions automatically set `NODE_EXTRA_CA_CERTS` to a file with the system certificates.
