### ISSUE TITLE
JS/TS server crash

### ISSUE THREAD

**Issue by princess-emma** [microsoft/vscode-remote-release#9364]
Type: <b>Bug</b>

Using the extension while editing node.js projects crashes the server every 2 or 3 minutes because of the JS/TS evaluation.

Extension version: 0.107.1
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.0-91-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12650H (16 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.63GB (6.35GB free)|
|Process Argv|--crash-reporter-id 4e30e4ff-aec6-4497-8839-dc10412dd85b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: hanna|
|OS|Linux x64 5.15.0-91-generic|
|CPUs|Intel Core Processor (Haswell, no TSX) (1 x 2394)|
|Memory (System)|1.87GB (0.47GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
vsjup518:30340749
vshan820:30294714
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
89544117:30613380
vscrp:30673768
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pythonregdiag2:30926735
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30917259
cp7184t3:30927821

```

</details>

**Comment by bamurtaugh** [comment]
Thanks for opening. Can you please share more details, including which remote extension(s) you're using when this happens, and some minimal repro steps + sample code or project?

**Comment by emslay** [comment]
I don't use any extension besides the remote desktop extension and the ones that ship by default with vs code.

About the project, it always happens when editing JS or TS files, the CPU usage skyrockets, and the server becomes unresponsive for about 45 seconds to 2 minutes. In some extreme cases, I can do nothing but force a restart of the whole server.

If you allow me some time to experiment I will try to register the processes that eat all my CPU and also elaborate on the details of what I am doing when it happens. For now, what I can say is that it happens especially when the project grows a little and it has to evaluate JS on different files when I add new code.

**Comment by paperlanternz** [comment]
I am experiencing this issue as well, the remote host starts dumping core as soon as you connect with a typescript file open, eventually you get the error in vscode "Remote Extension host terminated unexpectedly 3 times within the last 5 minutes." 

I am going to try downgrading vs code to november's update to see, but i think the repro is:

Install remote-ssh plugin
open remote folder with typescript project
open *.ts file
JS/TS remote module seems to initialize nominally

reboot vscode
reconnect to remote folder (ts file already open in editor)
core dumps -> error

**Comment by paperlanternz** [comment]
oh btw this is on an arm64 linux remote server, btw. not sure if that's interesting or not

**Comment by Nala60** [comment]
> > If you allow me some time to experiment I will try to register the processes that eat all my CPU and also elaborate on the details of what I am doing when it happens. For now, what I can say is that it happens especially when the project grows a little and it has to evaluate JS on different files when I add new code.
> 
> for me the core dump is pinning 1 cpu so it's probably that?

Yeah I guess my server has low resources to support that :( 1 cpu and 2gb ram

**Comment by bamurtaugh** [comment]
It sounds like updates to the latest VS Code should help with this - but if anyone is still encountering this, please do let us know!
