### ISSUE TITLE
devcontainer open/reopen in container seems to start as a blank/new setup

### ISSUE THREAD

**Issue by voigtan** [microsoft/vscode-remote-release#9378]
When I run my project in insider it seems like when I try to run it in a devcontainer it warns me that I already have a configuration and then tries to setup a new configuration file. This only happens when I run vscode Insider with the stable release of Dev Containers. When I test this in vscode (Version: 1.85.1 Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2) it works fine.

- VSCode Version: Version: 1.86.0-insider
Commit: c973ec767338f7846710cc2ee46e38b4504a044c
Date: 2024-01-10T05:37:20.920Z (1 hr ago)
- Local OS Version: macOS 14.1.2 (23B92)
- Remote OS Version: 
- Remote Extension/Connection Type: Containers

- Logs: [86296 ms] Start: Run: /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin) --ms-enable-electron-run-as-node /Users/voigtan/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js templates apply --workspace-folder /var/folders/cp/trp2yj2s26j5dr3kr7fz4jgm0000gn/T/tmp-output-dir-1704872310027 --template-id ghcr.io/devcontainers/templates/javascript-node:latest --template-args {"imageVariant":"20-bullseye"} --features [] --tmp-dir /var/folders/cp/trp2yj2s26j5dr3kr7fz4jgm0000gn/T/tmp-dir-1704872310027
[86390 ms] /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin): bad option: --ms-enable-electron-run-as-node
[86393 ms] Exit code 9

Steps to Reproduce:

1. Open a project that has a devcontainer setup
2. Try to run either build or Reopen in devcontainer
3. Popup displaying `Dev Container configuration '.devcontainer/devcontainer.json' file already exists.` 
4. "Add Dev Container Configuration Files"-setup starts

I also cant start a new project and setup a new devcontainer setup:

1. Create a folder
2. Start a devcontainer setup
3. I picked node.js and javascript
4. No other options
5. It fails with the log message above.

The outcome I was suppose to get is just step 1 and 2 and then the devcontainer should be up and running.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by TCFox** [comment]
Can confirm the same issue. Works as expected in `0.321.0`, has stopped working somewhere between then and `0.327.0`. Still not working in `0.330.0`. 

Observed on macOS 14.1.2, VS Code 1.85.1, Docker Engine 24.0.7 (w/ Docker Desktop 4.26.0).

**Comment by cptcanuck** [comment]
I resolved this locally when I realized that I didn't have the ecr-credential helper setup properly.  I didn't have the container locally, and it couldn't pull it down properly.  Getting the logs from the "Dev Containers - Show Previous Log" helped a lot in troubleshooting.   Basically, check the devcontainer Dockerfile to see if you have the container locally that you'r trying to use, then troubleshoot why that container isn't there (if it isn't).

The workflow around "open in devcontainer" doesn't seem to be handling the error well - I think that's the "vscode" problem here, but there's likely an error underneath to look into that isn't being surfaced properly in the UI.

$0.02!

**Comment by dbarvitsky** [comment]
@cptcanuck +100 for the "Dev Containers - Show Previous Log" pointer. In my case it was caused by this:

```
[12416 ms] Start: Run: /Users/dbarvitsky/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin) --ms-enable-electron-run-as-node <REDACTED>/.state/extensions-data/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder <REDACTED> --log-level debug --log-format json --config <REDACTED>/.devcontainer.json --mount-workspace-git-root
[12530 ms] /Users/dbarvitsky/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin): bad option: --ms-enable-electron-run-as-node
[12531 ms] Exit code 9
```

This ended up being `ms-vscode-remote.remote-containers` extension not matching the `code-insiders` version.

It would be awesome if vscode displayed the diagnostic log whenever the devcontainer spec failed to result in operational dev container. Like it used to do before 1.86.0. 

There could be a billion and one reason this happens, from failed Dockerfile and docker-compose builds to syntax errors in the .devcontainer.json itself. If someone went through the trouble of checking in a devcontainer spec for their project, it is a very likely that standard ones didn't work for them. Offering the choice of pre-canned dev containers instead of troubleshooting the error is not an appropriate UX choice here.

**Comment by chrmarti** [comment]
You currently need the Dev Containers pre-release version when running VS Code Insiders. (Dev Containers stable adds `--ms-enable-electron-run-as-node` which is no longer needed and not supported.) Thanks. (https://github.com/microsoft/vscode/pull/202053)
