### ISSUE TITLE
how to build vscode-server-linux-x64.tar.gz

### ISSUE THREAD

**Issue by lcjllrwtt** [microsoft/vscode-remote-release#9384]
I modified the tool name based on the vscode source code, and when using the Remote SSH plugin to connect to a remote server, I couldn't connect. Do I need to compile vscode-server-linux-x64.tar.gz myself? How do I compile it?

**Comment by connor4312** [comment]
Remote SSH may only be used to connect to official distributions of VS Code. There is not a method to use Remote SSH to connect to modified versions of the server.
