### ISSUE TITLE
Support WSLg in DevContainer

### ISSUE THREAD

**Issue by alexandre-fabra** [microsoft/vscode-remote-release#9387]
According to the [WSLg documentation](https://github.com/microsoft/wslg/blob/main/samples/container/Containers.md) it is possible to use WSLg within a container. In general passing these arguments to `docker run` may get the WSLg working with the container:

```bash
-v /tmp/.X11-unix:/tmp/.X11-unix
-v /mnt/wslg:/mnt/wslg \
-e DISPLAY
-e WAYLAND_DISPLAY
-e XDG_RUNTIME_DIR
-e PULSE_SERVER
```

Therefore my request would be to add an option for the the DevContainer to run with WSLg support.

**Comment by OhMyMndy** [comment]
Maybe you can create a Devcontainer feature to add the mounts and environment variables?

https://containers.dev/features

**Comment by alexandre-fabra** [comment]
> Maybe you can create a Devcontainer feature to add the mounts and environment variables?
> 
> https://containers.dev/features

I am not sure if that is possible as the mounts and environment variables should only be set for recent WSL2 environments, but not with WSL1, old WSL2 versions or other supported Linux environments. In my opinion this is something which should be supported by the extension.

**Comment by chrmarti** [comment]
Recent versions mount the Wayland socket automatically. Does this not work?

**Comment by alexandre-fabra** [comment]
I tested this on the latest version, and it works perfectly out of the box. As a result, this feature request is not needed.

**Comment by Gerharddc** [comment]
It seems I still have to add the following to my devcontainer.json to get GPU access (at least according to glxinfo):

```
  "runArgs": [
    "--device=/dev/dxg"
  ],
  "mounts": [
    "source=/usr/lib/wsl,target=/usr/lib/wsl,type=bind,readonly"
  ],
  "containerEnv": {
    "LD_LIBRARY_PATH": "/usr/lib/wsl/lib",
    "XDG_RUNTIME_DIR": "${localEnv:XDG_RUNTIME_DIR}"
  }
```

Not sure if that is just because I am using a custom image though.
