### ISSUE TITLE
Remote SSH Windows 8 - The terminal process command failed to launch

### ISSUE THREAD

**Issue by squibsy** [microsoft/vscode-remote-release#939]
- VSCode Version: 1.36.0
- Local OS Version: Windows 8.1 Pro
- Remote OS Version: Centos 7
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. f1 -> Remote-SSH: Connect To host
2. The terminal process command 'cmd.exe /c (type "C:\Users\xxx\AppData\Local\Temp\vscode-linux-multi-line-command-DHR.sh" | ssh  "DHR" bash) & exit /b 0' failed to launch (exit code: 255)

I've setup openssh and configured keys. Using puttygen to convert the public key, I can use putty to connect with the public key I generated. If I run the command "type "C:\Users\xxx\AppData\Local\Temp\vscode-linux-multi-line-command-DHR.sh" | ssh  "DHR" bash" from the command line, it completes just fine. "ssh DHR" from cmd opens an ssh session to the remote server, so at a loss to understand what's up.

**Comment by roblourens** [comment]
What if you run the full command `cmd.exe /c (type "C:\Users\xxx\AppData\Local\Temp\vscode-linux-multi-line-command-DHR.sh" | ssh "DHR" bash) & exit /b 0` in an external terminal?

**Comment by roblourens** [comment]
Can you share the log from the Remote - SSH output channel?

**Comment by squibsy** [comment]
The full command completes also. Remote log (redacted) looks like this:
Jul 15 12:50:48 x sshd[30646]: pam_unix(sshd:session): session opened for user root by (uid=0)
Jul 15 12:50:49 x sshd[30646]: Received disconnect from xxx.xx.xxx.xxx port 52145:11: disconnected by user
Jul 15 12:50:49 x sshd[30646]: Disconnected from xx.x.xx.xx port 52145
Jul 15 12:50:49 x sshd[30646]: pam_unix(sshd:session): session closed for user root

**Comment by roblourens** [comment]
That server log is from when vscode tried to connect or when you ran that command?

**Comment by squibsy** [comment]
From when vscode tried. The manual command produced much the same output.

**Comment by squibsy** [comment]
Turns out a restart of vscode fixed whatever was wrong. Thanks for the help.
