### ISSUE TITLE
Rebuild Container Without Cache does not pull the image.

### ISSUE THREAD

**Issue by huxuan** [microsoft/vscode-remote-release#9391]
- VSCode Version: 1.85.1
- Local OS Version: Windows 11
- Remote OS Version: Ubuntu 22.04
- Remote Extension/Connection Type: Containers

- Logs: 

```

```

Steps to Reproduce:

1. Tag a different image on local to the image used for devcontainers.
2. Trigger the command `Rebuild Container Without Cache`. 

According to a previous issue: https://github.com/microsoft/vscode-remote-release/issues/3128, it should pull the image to the latest version, but it will use the randomly picked image instead. And currently, I have to specify the `docker pull` command as the `initializeCommand` to make the process smooth.

Does this issue occur when you try this locally?: For DevContainers, Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/7104
