### ISSUE TITLE
Allow remote vscode-server to be installed in custom path instead of $HOME directory

### ISSUE THREAD

**Issue by rajashekar007** [microsoft/vscode-remote-release#940]
Allow remote vscode-server to be installed in custom path instead of $HOME directory. 

I have a limitation on size of $HOME directory because of which I had to frequently clear everything and restart everything, which is quite painful.

**Comment by traffisco** [comment]
Why no just download the binary and move it wherever suits you?

**Comment by rajashekar007** [comment]
> Why no just download the binary and move it wherever suits you?

Oh I didn't knew that, but when I tried starting vscode-server manually from a different directory, I still see installing server at /users/<user_name> and it is starting the server in that path. 

Please guide me If you want me to try something else.

**Comment by traffisco** [comment]
What you mean start manually?
I downloaded the binary, moved it to /usr/bin and run it. Nothing new in the HOME folder.

**Comment by tomocafe** [comment]
You could maybe try moving `~/.vscode-*` to another path (i.e. a disk with more space) and then create symbolic links to your home directory, e.g.

```shell
mv ~/.vscode-server /my/big/disk/
ln -s /my/big/disk/.vscode-server ~/.vscode-server
```

**Comment by rajashekar007** [comment]
Thanks @tomocafe , That's a great hack and can we have a proper solution.

**Comment by roblourens** [comment]
Got https://github.com/microsoft/vscode-remote-release/issues/472 for this request
