### ISSUE TITLE
Unable to add local workspace with Remote

### ISSUE THREAD

**Issue by jeegar123** [microsoft/vscode-remote-release#9400]
Type: <b>Bug</b>

first connect with Remote then Go to file Menu ,Add Folder to work space. it won't give option of local.

If its possible we can open local & remote in same vscode.

**Comment by joshspicer** [comment]
Once you connect to a remote machine with Remote - SSH, you can only open directories on the remote.  For this experience, I'd suggest opening another VS Code window side-by-side that is not connected to your remote, allowing you to see your local directories.  To sync projects between your local and remote machine, i'd suggest using git.
