### ISSUE TITLE
[Remote-SSH Bug]: Unable to connect to a remote machine with a fresh installation of Debian

### ISSUE THREAD

**Issue by jinliming2** [microsoft/vscode-remote-release#9404]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Remote-SSH Log

When connecting to a remote machine with a fresh installation of Debian, VS Code is stuck at the "Downloading VS Code Server" stage for a long time. Looking at the logs, I noticed multiple download attempts. After each successful download, I get a "local-server Timed out" error message and then it exits. After 5 repeated download attempts, an error message pops up.

<img width="1023" src="https://github.com/microsoft/vscode-remote-release/assets/10294977/873809ef-3d6f-41b9-8f93-114b50d9b651">

The error message indicates that the issue lies in line 35 of the `check-requirements.sh` script, where the `ldconfig` command does not exist. 

<img width="526" src="https://github.com/microsoft/vscode-remote-release/assets/10294977/c54e97ea-f425-48a4-9d31-9b0285cf451c">

Upon inspecting the `check-requirements.sh` script, I noticed that the existence of `/sbin/ldconfig` is checked at line 33, but `ldconfig` is directly executed at line 35. In a fresh installation of Debian, the `/sbin` directory is not in the `$PATH` of a regular user by default, hence the execution fails.

### Anything else?

Although this can be temporarily resolved by adding `/sbin` to `$PATH`, I believe it would be more reasonable to modify the `check-requirements.sh` script to execute `ldconfig` with an absolute path.

**Comment by roblourens** [comment]
You can set `"remote.SSH.useExecServer": false` to work around it.

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/9405
