### ISSUE TITLE
Constant restart of server

### ISSUE THREAD

**Issue by fueler** [microsoft/vscode-remote-release#941]
Issue Type: <b>Bug</b>

If I put my laptop to sleep while Visual Studio Code is connected to my remote and then wake it up in recent versions it can get stuck trying to restart/install the server piece after SSH connection is established. If shutdown Visual Studio Code and bring it back up afterwards it will not connect.

This only started happening recently.

Extension version: 0.44.0
VS Code version: Code - Insiders 1.37.0-insider (9296aaa2201b638e2b1dc71a9b9fe38c5ab2e904, 2019-07-09T05:24:16.868Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.4.0-154-generic

**Comment by fueler** [comment]
I've gotten in to situations where I need to restart my Linux box. Any tips of restarting the server side would help as a workaround until this regression is fixed.

**Comment by kitos9112** [comment]
Hello,

I face exactly the same issue here.

**Comment by pandyamitesh** [comment]
Try to kill node process on remote server - pkill node

**Comment by roblourens** [comment]
Do you have multiple remote vscode windows open at a time?

If you run the command "Reload Window" does it reconnect successfully?

**Comment by roblourens** [comment]
Also it would help if you can share the log from the Remote-SSH output channel

**Comment by pavank** [comment]
> Do you have multiple remote vscode windows open at a time?
> 
> If you run the command "Reload Window" does it reconnect successfully?

Yes, I have two windows open at the same time - One for app and another for devops code.

I can’t type anything when this happens because an pop up comes up notifying “ Trying to Reconnect..”

**Comment by roblourens** [comment]
Does the other window reconnect?

You can dismiss the popup to run commands

**Comment by pavank** [comment]
no, both windows end up trying to reconnect.

I usually dismiss pop up , close down and reopen VS code instances. I will try running commands and report back (On mobile now).

**Comment by fueler** [comment]
@roblourens I only have one window opened at a time. If I hit reload window I get server install already happening in a loop in the VSCode install terminal. At this point I have to restart my linux box. After that everything works perfectly again.

When it happens again I'll capture the exact output.

**Comment by pavank** [comment]
> no, both windows end up trying to reconnect.
> 
> I usually dismiss pop up , close down and reopen VS code instances. I will try running commands and report back (On mobile now).

Ok. This happened again just now after having both windows open for a couple of hours. Both windows got disconnected (A Parallel SSH connection on the terminal is just fine).

Cancelled pop-ups/notifications and tried reloading windows, one after the other, both still cannot connect successfully. The logs are as follows

```
remote-ssh@0.44.2
win32 x64
SSH Resolver called for "ssh-remote+lab8-dev", attempt 1
SSH Resolver called for host: lab8-dev
Setting up SSH remote "lab8-dev"
Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
Running script with connection command: "ssh"  -o ClearAllForwardings=true    "lab8-dev" bash
Install and start server if needed
> 
> ]0;C:\WINDOWS\SYSTEM32\cmd.exe
```

**Comment by roblourens** [comment]
Lots has changed - please open a new issue if this is still a problem
