### ISSUE TITLE
Connecting via SSH to both live host and GitHub insanely convoluted

### ISSUE THREAD

**Issue by DrunkenTyromancer** [microsoft/vscode-remote-release#9411]
Type: <b>Bug</b>

I used to work mainly with Eclipse IDE, and I had on several occasions gotten Eclipse to connect via SSH to various things, and I never had an issue with it, DESPITE not being a coder ... yes I studied computer science, but I didnt finish the course, and I never worked in the industry as a coder, but I know something like Eclipse should be more complex than something like VSCode, AND YET you somehow managed to make this thing damn near impossible to make it work in every direction I want it to work .. and I am not asking for anything magical or supernatural, but simply to have a local development environment with eventually WAMP running a local server (possibly also a LAMP stack on another machine locally), then use GitHub as "origin" for any repo (off site backup, and eventually start to learn about collaboration through it), and the live hosting site as "upstream" ... now, from my understanding, that shouldnt be anything but a pretty basic standard kind of scenario, yet every single help file and tutorial I see, whether from VSCode or someone else writing about you, or from GitHub, or from Microsoft, or even from my hosting provider and countless youtubers and bloggers ... NOBODY explains anything properly, you all begin with the assumption that I am going to be starting at the point of having no repository already in existence, and I have to create one ... but WHAT IF I had started locally, uploaded it via SFTP/FTPS to the live site, and now I wanted to connect VSCode to be able to push to the live site and publish to GitHub (or whichever way that is supposed to go) ... NOT TO MENTION that when it comes to articles about how to use SSH keys, nobody explains which configuration files to check, they dont explain how the same config file differs in specific purpose when viewed from the perspective of a different host, and so, when you go to adapt those so-called "help" files, there's no way you can, because you cannot adapt something that was never explained ... try writing ACTUAL EXPLANATIONS ... dont just tell me what to do, explain WHY it is being done, explain in what circumstances it might be different, explain how to check the settings in the config files are correct EVEN IF they were set automatically by some process (AND PLEASE get the guys at GitHub to do the same, their documentation is equally useless) ... I have tried this so many ways, and all I want is to have VSCode work with git repos on both the live site AND GitHub AND any other place I put them, while using SSH key connections that dont constantly ask for my password yet again ... and in order to achieve that, I need you to explain the WHOLE picture ... explain how I should check the files on the live server, explain how that will differ from GitHub or differ from a localhost WAMP server ... explain ALL OF IT ... because as it stands, I am contemplating going back to Eclipse, because as nice as some of this functionality may be here, if it cannot also work EASILY under all conditions with SSH logins plus Git in a shared hosting environment where it knows the difference between the root account versus the addon domain I am hosting a website for, and where you explained how to be sure I am logging in to the right part in the right way for VSCode to do its job easily ... if it cant do all that, then it is useless to me, because it was quite frankly EASIER setting all this up with EclipseIDE (and that was years ago when it was less developed than today)

Extension version: 0.107.1
VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 3.10.0-962.3.2.lve1.5.80.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900H (20 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (3.47GB free)|
|Process Argv|--crash-reporter-id 9ec0c9e7-0909-4f38-9509-73b6a2b167b0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: DigitalPacific|
|OS|Linux x64 3.10.0-962.3.2.lve1.5.80.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz (8 x 2299)|
|Memory (System)|23.39GB (7.33GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
a9j8j154:30646983
0bi6i642:30933247
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

**Comment by joshspicer** [comment]
I'm sorry to hear that you have not enjoyed your experience using VS Code Remote and thank you for the candid feedback.

I've read through a few times and am have difficulty pulling out actionable feedback that our team can spin into issues and consider as feature requests or bug reports.  If you're up for it, we'd certainly appreciate you opening new issues with the problems you're facing and steps on how we can reproduce it.  Often times folks on this platform are able to provide workarounds or solutions to get you unblocks.  Of course, if you've already moved on from VS Code we understand.
