### ISSUE TITLE
Test: Additional build flags when building a container image

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#9415]
Refs: https://github.com/microsoft/vscode-remote-release/issues/3545

- [x] anyOS @TylerLeonhardt
- [x] anyOS @alexr00

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%239415%0A%0A&assignees=chrmarti)

---

Dev Containers now supports building the container image with additional Docker CLI options.

Please test:
- Use the latest version of the Dev Containers extension (currently 0.333.0-pre-release).
- Use a Dev Container config with a Dockerfile, e.g.:
  - `.devcontainer/devcontainer.json`:
```jsonc
{
	"build": {
		"dockerfile": "Dockerfile",
		"options": [
			// add options here
		]
	}
}
```
  - `.devcontainer/Dockerfile`:
```Dockerfile
FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
```
- Add some build options (see https://docs.docker.com/engine/reference/commandline/image_build/). E.g., adding a label: `"--label", "testbuildoption=success"`.
- Reopen the folder in the dev container.
- Verify the the build options are applied. E.g., by inspecting the log (`F1` > `Dev Containers: Show Container Log`) or to verify the label was added you can inspect the image or container (which inherits the label) using the Docker CLI (`docker inspect <image / container id>`) or Docker extension (Inspect in container's context menu).

**Comment by alexr00** [comment]
@chrmarti I'm blocked on https://github.com/microsoft/vscode-remote-release/issues/9424

**Comment by TylerLeonhardt** [comment]
Seems to be working! I added `tag` and it was reflected in Docker Desktop
