### ISSUE TITLE
Test: devcontainer.json in user data folder

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#9416]
Refs: https://github.com/microsoft/vscode-remote-release/issues/9175

- [x] macOS @bhavyaus 
- [x] linux @justschen
- [x] windows @bpasero

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%239416%0A%0A&assignees=chrmarti)

---

When adding a devcontainer.json you are now asked if you want to place it in the user data folder instead of the workspace folder.

Please test:
- Use the latest version of the Dev Containers extension (currently 0.333.0-pre-release).
- Use the command `Dev Containers: Add Dev Container Configuration Files`.
- Verify that you can choose between adding to the user data folder and the workspace.
- Verify that you can use the command repeatedly.
- Verify that when adding to the workspace while there already is a config in the user data folder, you are offered to copy that over.
- Verify that when there are configs in both folders you are asked which one to use when using other commands, like:
  - `Dev Containers: Reopen in Container`.
  - `Dev Containers: Open Container Configuration File`.

**Comment by bpasero** [comment]
Using that command shows an error dialog for me:

<img width="464" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/900690/38c5eee5-c294-4d11-8d04-0ac5a64ff665">
