### ISSUE TITLE
remote ssh does not connect anymore (from a month +/-)

### ISSUE THREAD

**Issue by iPadawan** [microsoft/vscode-remote-release#9418]
Type: <b>Bug</b>

Hi,
I'm using same configuration on vs code stable release. With stable release I can connect via remote ssh. Starting a month less or more ago, I cannot connect in vs code insider edition anymore (before I could).

Help!

Riccardo

VS Code version: Code - Insiders 1.86.0-insider (e244acbb172c428cb219717a07bf55d2737492ca, 2024-01-22T05:35:59.383Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Connection to 'SSH: sviluppo-union-172.31.33.123' could not be established 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13980HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.64GB (14.55GB free)|
|Process Argv|--crash-reporter-id 5157cad5-49a3-4c5a-af7b-cf0997ea8726|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: sviluppo-union-172.31.33.123' could not be established 
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
fegfb526:30945144

```

</details>

**Comment by roblourens** [comment]
Please share the log from the Remote-SSH output channel

**Comment by iPadawan** [comment]
Hi, thank you. Here is log.
[[134629.938] Log Level 2.txt](https://github.com/microsoft/vscode-remote-release/files/14024201/134629.938.Log.Level.2.txt)

**Comment by roblourens** [comment]
Does it work to set `"remote.SSH.useExecServer": false`?

**Comment by connor4312** [comment]
Can you also share the contents of the log file found at

`/home/union/.vscode-server-insiders/.cli.e244acbb172c428cb219717a07bf55d2737492ca.log`

**Comment by iPadawan** [comment]
> Can you also share the contents of the log file found at
> 
> `/home/union/.vscode-server-insiders/.cli.e244acbb172c428cb219717a07bf55d2737492ca.log`
Thank you. Here is the .log
[
[.cli.e244acbb172c428cb219717a07bf55d2737492ca.log](https://github.com/microsoft/vscode-remote-release/files/14039509/default.cli.e244acbb172c428cb219717a07bf55d2737492ca.log)
](url)

**Comment by iPadawan** [comment]
> Does it work to set `"remote.SSH.useExecServer": false`?
I cannot check or change flag cause of the "unknown reason" the editor of settings doesn't start.

**Comment by connor4312** [comment]
The requirements for the VS Code server have been increased, see https://github.com/microsoft/vscode/issues/201129

Apparently we need to make a tweak to support showing errors correctly...
