### ISSUE TITLE
[Remote-SSH Bug]:  personal currencies applications policies accounts

### ISSUE THREAD

**Issue by artificial123344** [microsoft/vscode-remote-release#9419]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

billions customers // 

carts accounts //

  budget transaction// 

### Expected Behavior

 usd bass// counts datdbass//
  
100,000,000,000,00,
100,000,000,000,000,00,

### Steps To Reproduce

collaborate apps//
google'purchase' transactions////
Microsoft  billing Authentications ///
sony' price' Proccess'  ////
amazon' premiums ' Legal authority////
apple'subscriptions'///

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by artificial123344** [comment]
> ### Is there an existing issue for this bug?
> * [x]  I have searched the existing issues
> 
> ### Required Troubleshooting Steps
> * [x]  I have followed these troubleshooting steps
> * [x]  I have tried both values of the `remote.SSH.useLocalServer` setting
> 
> ### Connect Locally
> It connects successfully
> 
> ### ->
> billions customers //
> 
> carts accounts //
> 
> budget transaction//
> 
> ### Expected Behavior
> usd bass// counts datdbass//
> 
> 08.5,000,000,000,00, 100,000,000,000,000,00, 01,000,000,000,000,00,
> 
> ### Steps To Reproduce
> collaborate apps// google'purchase' transactions//// Microsoft billing Authentications /// sony' price' Proccess' //// amazon' premiums ' Legal authority//// apple'subscriptions'///
> 
> ### Remote-SSH Log
> Remote-SSH Log
> ### Anything else?
> _No response_

**Comment by roblourens** [comment]
I don't understand
