### ISSUE TITLE
Using that command shows an error dialog for me:

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#9421]
Using that command shows an error dialog for me:

<img width="464" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/900690/38c5eee5-c294-4d11-8d04-0ac5a64ff665">

_Originally posted by @bpasero in https://github.com/microsoft/vscode-remote-release/issues/9416#issuecomment-1905760480_

**Comment by chrmarti** [comment]
Fixed in 0.335.0-pre-release.

Verification: Use the `Dev Containers: Add Dev Container Configuration Files...` command and verify that QuickPick opens without the above error.
