### ISSUE TITLE
Relative path shown when running action again to create into user data dir

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#9422]
Testing #9416

<img width="358" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/900690/6ed0fff3-9c05-48a0-8aac-36f4b9a4729f">

I think here I would show the absolute path.

**Comment by chrmarti** [comment]
The full path is very long, I could add `<user-data-dir>` to abbreviate it:
![Image](https://github.com/microsoft/vscode-remote-release/assets/9205389/bc73cbae-01c1-4735-85a8-c3e5ba613a54)

I also use that when picking from multiple configurations:
![Image](https://github.com/microsoft/vscode-remote-release/assets/9205389/ea6b853f-a655-4ef5-8b25-6fd691c3ac2b)

**Comment by chrmarti** [comment]
Going with that for now. Will be in Dev Containers 0.336.0-pre-release

**Comment by bhavyaus** [comment]
Why can't we show the full dir path? Using `<user-data-dir>` feels weird for reporting path to me. 

![Image](https://github.com/microsoft/vscode-remote-release/assets/25044782/7fc13360-ba1a-4a2e-a944-31f60efac017)

**Comment by chrmarti** [comment]
The full path is quite long and I'm not sure it adds much information at that point:
![Image](https://github.com/microsoft/vscode-remote-release/assets/9205389/f80d032e-2ee7-4bd0-931c-3b28b426d95e)

**Comment by bhavyaus** [comment]
I've only ever seen file paths be reported in relative path or full path format. Using a place holder seems weird to me. User could also not be aware of what `<user-data-dir>` is set to after having launched vscode.

The full path shown above (despite being long) seems ok to me.

**Comment by chrmarti** [comment]
Ok, going with that then. I'll also replace the home folder with `~` on Linux and macOS. Thanks!

**Comment by rzhao271** [comment]
Verified!

Nit: on Windows, if the config is always saved into AppData/Roaming, then a shorthand you could use is %APPDATA%
