### ISSUE TITLE
Python extension not loading when opening Dev Container

### ISSUE THREAD

**Issue by PelicanQ** [microsoft/vscode-remote-release#9426]
Type: <b>Bug</b>

Python extension does not load when opening Dev Container, causing dependent extension Black Formatter to open error dialog:

> Cannot activate the 'Black Formatter' extension because it depends on the 'Python' extension, which is not loaded. Would you like to reload the window to load the extension?

I made a repo for reproducing.

1. Open a new VSCode window.
1. In Command Palette: Dev Containers: Clone Repository in Container Volume.
1. Enter https://github.com/PelicanQ/devcontainer-issue.git
1. Open `main.py` and the error dialog should pop up after a while.
1. If VSCode has not selected the `defaultInterpreter` as given in `devcontainer.json`, select that Python interpreter and rebuild container. The "... Python, which is not loaded" error remains.

I tried this in normal VSCode version 1.85.2 and Dev Containers version v0.327.0
I also tried it with VSCode Insiders. I get the error in both cases.

Docker Desktop 4.26.1 (131620)
Extension version: 0.335.0
VS Code version: Code - Insiders 1.86.0-insider (800e60abdfb1675a59520bac6a9473bc380d49ea, 2024-01-23T06:12:41.150Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HX with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (13.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5900HX with Radeon Graphics (16 x 3293)|
|Memory (System)|15.55GB (13.20GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
b1063948:30943794
fegfb526:30945144

```

</details>

**Comment by luabud** [comment]
I believe this is due to a race condition, where the Black formatter extension is being activated before the Python one. Because this is in the installation and activation flow, there's not much we can do at the extension side to fix this. 

@bamurtaugh -- there's an issue tracking this in the VS Code repo, so I think this can be closed as a dupe? https://github.com/microsoft/vscode/issues/196794

**Comment by bamurtaugh** [comment]
Thanks so much for the insights @luabud! Yes, let's close this as a dupe and track in https://github.com/microsoft/vscode/issues/196794.
