### ISSUE TITLE
Tippfehler: Remoteverbindung scließen

### ISSUE THREAD

**Issue by gitoni** [microsoft/vscode-remote-release#943]
Issue Type: <b>Bug</b>

### [German Language]
Wenn ich eine SSH Verbindung geöffnet habe und diese schließen möchte, gibt es neuerdings den Eintrag 
Datei->Remoteverbindung scließen

super, das fehlte noch in der letzen Version. In der Deutschen Version hat es noch einen Tippfehler: "scließen" statt "schließen"

Extension version: 0.44.0
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)

**Comment by roblourens** [comment]
Our localized strings are not in this repo, you can find info about our localization process here: https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project
