### ISSUE TITLE
JS/TS language crashed on ssh remote

### ISSUE THREAD

**Issue by githubmmbuxan** [microsoft/vscode-remote-release#9430]
Type: <b>Bug</b>

Connect to a server with sshRemote (Microsoft).
The code is an laravel app with react in frontend.
'yarn dev' crash, too many processes.
If sshRemote is closed  and connect to a simple ssh terminal yarn dev works perfect.

Extension version: 0.107.1
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:47:11.635Z)
OS version: Linux x64 5.4.0-150-generic
Modes:
Remote OS version: Linux x64 4.15.0
Remote OS version: Linux x64 4.9.0
Remote OS version: Linux x64 5.2.0

**Comment by joshspicer** [comment]
This sounds like an issue with either yarn or remote machine.  Could you please share what led you to think it was a bug in Remote - SSH, so I can better assist.
