### ISSUE TITLE
devcontainer in wsl avoids windows portproxy intended to expose port for devcontainer

### ISSUE THREAD

**Issue by robot-ranger** [microsoft/vscode-remote-release#9439]
- VSCode Version:
```
Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```
- Local OS Version:
```
Edition	Windows 10 Pro
Version	22H2
Installed on	‎6/‎4/‎2023
OS build	19045.3930
Experience	Windows Feature Experience Pack 1000.19053.1000.0
```
- Remote OS Version:
```
wsl --version
WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3930
```
- Remote Extension/Connection Type: Containers/WSL/Server
Dev Containers v0.327.0

- Logs:

Steps to Reproduce:

When constructing a devcontainer, I need a bunch of ports exposed. I specify my ports in `devcontainer.json`:
```
"forwardPorts": [
        6080,
        5900,
        29999,
        30001,
        30002,
        30003,
        30004,
        30011,
        30012,
        30013,
        30020
    ],
```

But in order to make these ports accessible to other device on my LAN, i have to also add portproxies in windows with `netsh interface portproxy add v4tov4...`:

![image](https://github.com/microsoft/vscode-remote-release/assets/93950632/1856dad1-1fa8-40c1-bd82-755f1e2ec201)

...However... if these portproxies are present when the container is constructed, vscode seems to try to avoid these ports:

![image](https://github.com/microsoft/vscode-remote-release/assets/93950632/1325e4e7-1b41-48eb-bef6-e4ce0a932e01)

...why?...how? if the root of the classic "access WSL from remote LAN device" problem is that WSL isnt aware of the networking setup in windows and vise-versa, then how does it 'know' that these ports are 'occupied' in the first place?

My hack of a solution is:
construct the devcontainer THEN apply the portproxies. when i do it in this order - the services running in WSL are accessible from other devices on my LAN.

How can i force vscode and devcontainer to honor the port number on both 'external' and 'internal' regardless of windows port proxies? 

Does this issue occur when you try this locally?: NA - docker runs in WSL
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Have you tried letting the port proxy listen on the external interface only? It is shown as listening on 0.0.0.0 which is "all" interfaces. I think that makes VS Code consider that port being already in use.
