### ISSUE TITLE
remote install extension pack installs all except one

### ISSUE THREAD

**Issue by jbrandli** [microsoft/vscode-remote-release#944]
Issue Type: <b>Bug</b>

Run vscode remote ssh behind ssl breaking proxy. 

Install java extension pack on remote. 

All extensions will be installed except the redhat language support for java extension and the error "cannot get local issuer certificate will popup. " This is weird because all the others get installed. 

Extension version: 0.44.0
VS Code version: Code - Insiders 1.37.0-insider (7e03eb1a1fce3beb6ccea5f3b8f828e01940be61, 2019-07-05T18:31:56.611Z)
OS version: Windows_NT x64 10.0.16299
Remote OS version: Linux x64 3.10.0-957.10.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (1.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 172.20.48.5|
|OS|Linux x64 3.10.0-957.10.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4116 CPU @ 2.10GHz (4 x 2100)|
|Memory (System)|15.51GB (5.74GB free)|
|VM|18%|
</details>

**Comment by jbrandli** [comment]
This happens even with proxy strict ssl set to false in the remote settings.

**Comment by roblourens** [comment]
Sorry for the slow response. Is this still an issue?

**Comment by jbrandli** [comment]
its fixed in the new versions
