### ISSUE TITLE
Docker fails to start

### ISSUE THREAD

**Issue by nssidhu** [microsoft/vscode-remote-release#9443]
I am trying to setup docket Environment on my VMware (not connected to any domain, its on my personal Laptop).
I tried installing/reinstalling at least 3 times but to no avail.

I am getting the following error.
![Screenshot 2024-01-26 082252](https://github.com/microsoft/vscode-remote-release/assets/3267605/3d354213-b3e5-43a7-86e9-f84800033cc5)

- VSCode Version: N/A. I am having difficulties install Docker Desktop, not there yet to VSCode part.
- Local OS Version: Windows 11 Enterprise 22H2
- Remote OS Version: ?? Not sure what this means ( I am new to docker and trying this for the first time)
- Remote Extension/Connection Type: Containers/WSL/Server ?? Not sure what this means ( I am new to docker and trying this for the first time)

- Logs:

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No (Not sure how to disable extensions)

**Comment by bamurtaugh** [comment]
Hey there, sorry to hear about the trouble. Were you able to get this working and move forward to the VS Code focused pieces?

If you're still having trouble with the Docker installation, we'd recommend reviewing Docker docs. We're happy to help with any VS Code specific parts! Thanks!
