### ISSUE TITLE
Remote connetion fails 

### ISSUE THREAD

**Issue by manilight** [microsoft/vscode-remote-release#9451]
Type: <b>Bug</b>

When opening remote connection to new ssh host, it works fine. But when selecting folder to open, and when VSCode starts to reload, this always fails. 

There is always this same:

[17:05:25.866] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[17:05:25.869] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[17:05:25.870] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[17:05:25.871] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[17:05:25.871] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[17:05:25.873] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[17:05:25.873] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[17:05:25.874] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[17:05:25.874] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"

When I close VSCode and start it again from taskbar shortcut, which leads straight to correct folder, it works. 

Extension version: 0.4.1
VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.26020
Modes:
Connection to 'wsl+ubuntu-22.04' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.66GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2B7b22686f73744e616d65223a224a482d44726f706c65742d3031227d/home/jani/code/nk-client --crash-reporter-id c6138fcd-cf38-490d-bdc1-9c6f6e8d611e|
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+ubuntu-22.04' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30933247
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019a:30933241
3ef8e399:30949928

```

</details>

**Comment by joshspicer** [comment]
Thanks for opening this issue.  The log snippet you chose to share does not indicate an error and is expected

If you're still hitting issues, please feel free to open a new issue with a current copy of your complete logs (`> Remote-SSH: Show Log` in the command palette).
