### ISSUE TITLE
Node.js v.18.15.0 in vscode-server has "critical" vulnerability, needs upgrade

### ISSUE THREAD

**Issue by ae2015** [microsoft/vscode-remote-release#9453]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

The `Node.js` that comes embedded in `vscode-server` on my virtual machine has version 18.15.0, and that is flagged as a critical vulnerability: Node.js 16.x < 16.20.2 / 18.x < 18.17.1 / 20.x < 20.5.1 Multiple Vulnerabilities (Wednesday August 09 2023 Security Releases). The recommended solution is to upgrade to `Node.js` version 18.18.2 or later. I tried replacing the `node` file in `/home/.../.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/` (the current update for vscode-server) with the newer `/usr/bin/node` (both itself and a link to it), but this resulted in VSCode remote connection issues: terminal window not showing shell prompt and `pty host` errors.
```
Visual Studio Code
Version: 1.85.2 (Universal)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:32.531Z
Node.js: 18.15.0
OS: Darwin arm64 22.6.0
```

### Expected Behavior

`Node.js` that comes embedded in `vscode-server` upgraded to at least 18.17.1 or, better, to 18.18.2 or later, or removed altogether and replaced with `/usr/bin/node` or the `node` installed with `nvm`.

### Steps To Reproduce

N/A

### Remote-SSH Log

N/A

**Comment by deepak1556** [comment]
Upcoming release `1.86` will have server Node.js version updated to `18.17.1`.
