### ISSUE TITLE
[Suggestion] Background fetching of VS Code Server updates 

### ISSUE THREAD

**Issue by segln** [microsoft/vscode-remote-release#9458]
Requesting #7067 again.

Please consider adding a feature to update code-server in the background after connecting to the current version.

> I'd really like VS Code to eagerly fetch updates for the VS Code Server for WSL in the background. Right now whenever I restart VS Code I'm prevented from working for a significant amount of time while this extension finishes Downloading server... (takes 5-10 minutes on my connection)\
\
> It basically means I have to pre-empt when I want to restart my computer or VS Code to a time when I am not needing to access my work. Feels very unnecessary? These updates could be fetched in the background and stored locally, then transferred to WSL when needed?

> Others are experiencing the same frustrations: https://stackoverflow.com/questions/71464269/vscode-remote-wsl-downloading-server-every-time

**Comment by aeschli** [comment]
We have that feature in the meantime. When the WSL extension detects that there's a VS Code update, it also downloads the corresponding server.
You should see signs of that in the WSL log (Command : WSL: Show log)

**Comment by segln** [comment]
Actually I'm having this problem with SSH connections. Are they using different methods?
