### ISSUE TITLE
Not able to start Dev Containers

### ISSUE THREAD

**Issue by p-renner** [microsoft/vscode-remote-release#9459]
Type: <b>Bug</b>

Since installing the latest vscode update, trying to start a devcontainer results in the error popup:
"Dev Container configuration '.devcontainer/devcontainer.json' file already exists."

Extension version: 0.327.0
VS Code version: Code 1.86.0 (Universal) (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:29:15.765Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id c1e95375-38ba-436c-b324-c1166cef344b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30951796
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
7j2b6412:30949929

```

</details>

**Comment by langestefan** [comment]
It just happened after the update. None of my dev containers are running anymore. I can't even download the previous version anymore, because the [update website is down](https://code.visualstudio.com/updates) (guess why?)

**Comment by renan-abm** [comment]
The workaround here might help https://github.com/microsoft/vscode/issues/203964

**Comment by langestefan** [comment]
> The workaround here might help [microsoft/vscode#203964](https://github.com/microsoft/vscode/issues/203964)

This works. Thanks!
