### ISSUE TITLE
Unclear Error message about dev container build failure, triggered by seemingly irrelevant VSCode setting

### ISSUE THREAD

**Issue by lnay** [microsoft/vscode-remote-release#9461]
It's unclear where this needs to be reported so I'm posting here for now.

## Problem

The "files.exclude" setting in `.vscode/settings.json` will cause a failure in dev container builds with a pop-up saying **"Dev Container configuration '.devcontainer/devcontainer.json' file already exists"**, if used to exclude the `.devcontainer` directory.

## Why it's a problem

Seeing the the numerous other issues with other causes posted here with the same pop-up message, it was incredibly non-obvious what the cause was.

I came across this issue in a project where the author added that VSCode setting with the intention of de-clutering the file viewer, not expecting any side-effects. Indeed the description for that setting says:

*"Configure [glob patterns](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) for excluding files and folders. For example, the File Explorer decides which files and folders to show or hide based on this setting. [...]"*

which gives no hint about potential effect on dev container builds. To avoid user frustration, the pop-up message should either recognise this scenario, or the dev container extension should not be affected by this VSCode setting.

## Reproduction

- VSCode Version: 1.85.2
- Local OS Version: Fedora 39 (also ubuntu)
- Remote Extension/Connection Type: Containers

Steps to Reproduce:
[Minimal reproduction](https://github.com/lnay/devcontainer-minimal-repro-issue1) adding a few lines to the standard dev container template.

1. Add `.devcontainer` to the "files.exclude" setting in VSCode (last commit in minimal repro above)
2. Choose from command palette: "Dev containers: rebuild and reopen in container"

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this in Codespaces?: No
Does this issue occur with the [devcontainer-cli](https://github.com/devcontainers/cli)?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes (other than the dev container extension)

**Comment by DanTup** [comment]
What makes you think it's related to the `files.exclude` setting?

I'm seeing the same error:

```
[Window Title]
Visual Studio Code

[Content]
Dev Container configuration '.devcontainer\devcontainer.json' file already exists.

[Continue] [Cancel]
```

And I did have `files.exclude` in my `.vscode/settings.json`. However, deleting that file does not solve the issue. I still get this prompt. Clicking "Continue" forces me to pick a container template (I don't know why), but doing that fails anyway with:

```
[Window Title]
Visual Studio Code

[Content]
Application of the template failed.

[Show Log] [Cancel]
```

So far I've not found a way to open my workspace in a container.

**Comment by DanTup** [comment]
I switched to the Pre-release version of the extension (noted in https://github.com/microsoft/vscode/issues/203964#issuecomment-1921283689) and the issue has gone.

**Comment by lnay** [comment]
> What makes you think it's related to the `files.exclude` setting?
> 
> [...]
>
> And I did have `files.exclude` in my `.vscode/settings.json`. However, deleting that file does not solve the issue. I still get this prompt. Clicking "Continue" forces me to pick a container template (I don't know why), but doing that fails anyway with:
> [...]

@DanTup , Is this in your own project or the minimal repro I gave?

I think that this is a trigger because adding it to the standard template for devcontainers (which definitely works), breaks it (as illustrated in the repro). Removing it fixes it.

I'm not saying that this is the only possible cause for that pop-up, hence furthering my point about this being, at the very least, a documentation/error message improvement..

I tried the pre-release version of the dev container extension and that did not change anything (again for this particular problem).

**Comment by DanTup** [comment]
> @DanTup , Is this in your own project or the minimal repro I gave?

Sorry, I wasn't very clear. It was my own project. Unfortunately removing that setting didn't seem to work for me (although it's possible there was something else at play). Updating to the Pre-release (and Reloading to let it load) definitely has solved the issue for me though - even with that setting, I can open the folder in the container.

**Comment by lnay** [comment]
One thing that I realise I didn't clarify at the top of the post was that this is caused by using "files.exclude" on ".devcontainer". That is:

```json
// .vscode/settings.json
{
    "files.exclude": {
        ".devcontainer": true
    }
}
```

**Comment by DanTup** [comment]
Ah, I don't have that in mine at all. I was seeing the same error as you but my settings are:

```
{
	"files.exclude": {
		"**/.git": true,
		"**/.svn": true,
		"**/.hg": true,
		"**/CVS": true,
		"**/.DS_Store": true,
		"**/_site": true
	}
}
```

But removing the whole settings file didn't fix the issue. Restoring it and then updating the extension did. It's possible our issues were different and just happened to produce the same error,

**Comment by lnay** [comment]
Just realised this is a duplicate of (still open) issue #9436
