### ISSUE TITLE
Code server does not work with 18.04

### ISSUE THREAD

**Issue by sebastian-burlacu** [microsoft/vscode-remote-release#9464]
It appears this is intended - however, is there a way to ask for an older version of the software? All instances of code-server pull updates automatically. We cannot update our compute nodes instantly, thus this service is broken for all users. How can I request version 1.85 instead of 1.86?

- VSCode Version: 220909.27
- Local OS Version: Ubuntu 22.04
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: code server

- Logs: 

```
sebastian@nodename:~$ code-server serve-local --host $(hostname) --port 8123 --accept-server-license-terms --disable-telemetry
[2024-02-01 12:18:56] info Downloading VS Code server https://vscode.download.prss.microsoft.com/dbazure/download/stable/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/vscode-server-linux-x64-web.tar.gz -> /home/sebastian/.vscode-cli/server-stable-web/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937
[2024-02-01 12:18:56] info Setting up server...
[2024-02-01 12:18:58] info Starting server...
Warning: Missing GLIBC >= 2.28! from /lib/x86_64-linux-gnu/libc-2.27.so
Error: Missing required dependencies. Please refer to our FAQ https://aka.ms/vscode-remote/faq/old-linux for additional information.
```

Steps to Reproduce:

1. run above command on 18.04 ubuntu

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by russellyq** [comment]
Hi, I meet the same error. Did you solve it ?

**Comment by virtuald** [comment]
Is there a good reason for the glibc upgrade? It worked fine before, I can't imagine a newer glibc provides much more than the old one.

**Comment by virtuald** [comment]
Looks like workarounds are being discussed? https://github.com/microsoft/vscode/issues/203375

**Comment by lucaspompeun** [comment]
I've tried this solution and works well: https://code.visualstudio.com/docs/remote/faq#_can-i-run-vs-code-server-on-older-linux-distributions

**Comment by virtuald** [comment]
I've downgraded to 1.85 for now, but I hope a better long term solution is found.

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode/issues/203375.
