### ISSUE TITLE
the remote host may not meet VS code Server's prerequisites for glibc and libstdc++

### ISSUE THREAD

**Issue by Chiu-Ping** [microsoft/vscode-remote-release#9471]
- VSCode Version: 
  Version: 1.86.0 (Universal)
  Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
  Date: 2024-01-31T10:29:15.765Z
  Electron: 27.2.3
  ElectronBuildId: 26495564
  Chromium: 118.0.5993.159
  Node.js: 18.17.1
  V8: 11.8.172.18-electron.0
- Local OS Version: Darwin arm64 23.2.0
- Remote OS Version: 
  LSB Version:	:core-4.1-amd64:core-4.1-noarch
  Distributor ID:	CentOS
  Description:	CentOS Linux release 7.8.2003 (Core)
  Release:	7.8.2003
  Codename:	Core
- Remote Extension/Connection Type: Containers/WSL/Server

- Logs: 
The remote host may not meet VS Code Server's prerequisites for glibc and libstdc++

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

The problem looks like it is from the remote-ssh because I just updated the version of the vs code version and then I failed to log in to my remote server. could any experts give me more advice?

**Comment by haoqing0110** [comment]
Meet similar issues. Refer to https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites, seems CentOS/RHEL 7 is no longer supported due to no available glibc and libstdc++. 

Want to know any workaround?

**Comment by Chiu-Ping** [comment]
The silly way is to return to the 1.85 version, and it works well.

**Comment by Chiu-Ping** [comment]
> Meet similar issues. Refer to https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites, seems CentOS/RHEL 7 is no longer supported due to no available glibc and libstdc++.
> 
> Want to know any workaround?

The silly way is to return to the 1.85 version, and it works well.

**Comment by Topiya** [comment]
I am also facing same problem.

**Comment by stillhart** [comment]
If you are one of the RHEL7 (remote) users out there: Time to downgrade vscode and stick to vscode 1.85

Here are the release notes of 1.86:
_[Linux minimum requirements update](https://code.visualstudio.com/updates/v1_86#_linux-minimum-requirements-update)
In this milestone, we have updated the toolchains to build our desktop client. From this release onwards, VS Code desktop is only compatible with Linux distributions based on glibc 2.28 or later, and glibcxx 3.4.25 or later, such as **Debian 10, **RHEL 8**, or Ubuntu 20.04.**
If you are unable to upgrade your Linux distribution, the recommended alternative is to use our [web client](https://code.visualstudio.com/docs/editor/vscode-web). If you would like to use the desktop version, then you can [download the VS Code release 1.85](https://code.visualstudio.com/updates/v1_85). Depending on your platform, make sure to disable updates to stay on that version. A good recommendation is to set up the installation with [Portable Mode](https://code.visualstudio.com/docs/editor/portable)._

I got the following error during connection the setup, which brought me to this issue.
_ ⚠️ The remote host may not meet VS Code Server's prerequisites for glibc and libstdc++_

**Comment by chuymtz** [comment]
Is the Remote -SSh extension not compatible with version 1.85.2? I downgrading but now it seems I cant use the extension anymore. Am I the only one seeing this? Thanks

**Comment by Topiya** [comment]
> Is the Remote -SSh extension not compatible with version 1.85.2? I downgrading but now it seems I cant use the extension anymore. Am I the only one seeing this? Thanks

You can solve it by installing this extension again.

**Comment by chuymtz** [comment]
@Topiya you're absolutely right thanks!

**Comment by chuymtz** [comment]
> retracting the changes to the extension or will i be forced to run my machine with ubuntu 2

@Tsajan What version of the extension do you have? Mine worked on `v0.107.1`.

**Comment by Tsajan** [comment]
I tried with v0.107.1 too, that didn't work for me!
