### ISSUE TITLE
Failed remote connection to Amzon Linux 2(EC2) on v0.108.0

### ISSUE THREAD

**Issue by amit-sah7** [microsoft/vscode-remote-release#9473]
In the current version v0.108.0, remote SSH is failing for instances with Amzn Linux 2 AMI, while there is no issue for instances using Amzn Linux 2023.

![image](https://github.com/microsoft/vscode-remote-release/assets/122343593/ff1cadb1-5f73-4f2e-b0b3-bda6d09167ad)
![image](https://github.com/microsoft/vscode-remote-release/assets/122343593/459429d2-93af-464a-997c-1a29c9ea12db)

**Comment by mattras82** [comment]
I also ran into this issue today. Very frustrating. It ate up hours of my day trying to solve/work around it.

**Comment by amit-sah7** [comment]
Immediate resolution:
Revert VS code: 1.85 and Remote-SSH: v0.107.1

**Comment by connor4312** [comment]
This is fixed in VS Code 1.86.1
