### ISSUE TITLE
Add Snap package snippet to FAQ

### ISSUE THREAD

**Issue by aaronprisk** [microsoft/vscode-remote-release#9476]
Hello! There seems to be some confusion from our Ubuntu 18.04 users around the glibc requirement change. While the deb package doesn't work, the Snap version is built on base: core20 and still works as expected. Could there be a small snippet added to the FAQ to let those users know that it's an option for them?

**Comment by bamurtaugh** [comment]
Thanks for opening! If you have a moment, would you be willing to open a PR to the doc section(s) you have in mind? Please feel free to tag me in it, and I'd love to provide a review. https://github.com/microsoft/vscode-docs

**Comment by aaronprisk** [comment]
Sure! I'll sync with my team and see if they can help provide some proper context.

**Comment by bamurtaugh** [comment]
Hey there! Going to close out this issue for now, but please do let us know if you have additional feedback/issues or if you're able to contribute that PR. Thanks so much!
