### ISSUE TITLE
 Git for windows, Could not open a connection to your authentication agent.

### ISSUE THREAD

**Issue by gxtaillon** [microsoft/vscode-remote-release#948]
- VSCode Version: 
```
Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299
```
- Local OS Version: Microsoft Windows [Version 10.0.16299.1217] 
- Remote OS Version: CentOS Linux release 7.6.1810 (Core)
- Remote Extension/Connection Type: SSH

### Description
Hi,

I'm trying to play around with Remote - SSH from by org computer, however I'm running into an issue where I am unable to install the Windows OpenSSH Client as instructed here (https://code.visualstudio.com/docs/remote/troubleshooting#_installing-a-supported-ssh-client). I currently am using git for windows (version 2.22.0 - 2019-06-08) and am running into an issue when trying to connect to an SSH remote, see output below. It might be a bug, or I might be using Remote - SSH wrong, not sure. Can I get some guidance to not run into this issue? Thank you

### Steps to Reproduce:

* Computer is managed by organisation, not authorized to manage optional features
* Manually trying to install the openssh client fails (https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse). Get-WindowsCapability fails with Error code = 0x8024401c
* Using Git for Windows as only option

1. Try to connect with Remote - SSH

### Output:

```
remote-ssh@0.44.0
win32 x64
SSH Resolver called for "ssh-remote+fqdn", attempt 1
SSH Resolver called for host: fqdn
Setting up SSH remote "fqdn"
Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019
Install and start server if needed
> 
> Enter passphrase for key '/c/Users/gtaillon/.ssh/id_rsa':
"install" wrote data to terminal: "***"
> 
> 
> Found existing installation at /home/gtaillon/.vscode-server/bin/>>> UUID <<<
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> 
> 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> >>> UUID <<<
> 
"install" terminal command done
User entered passphrase
Passphrase was entered and ssh config entry was found - adding SSH key to agent
Executing add-ssh-key:
powershell -ExecutionPolicy Bypass C:\Users\gtaillon\AppData\Local\Temp\vscode_add_ssh_key_to_agent.ps1
"add-ssh-key" wrote data to terminal: "powershell -ExecutionPolicy Bypass C:\Users\gtaillon\AppData\Local\Temp\vscode_add_ssh_key_to_agent.ps1"
> Microsoft Windows [Version 10.0.16299.1217]
> (c) 2017 Microsoft Corporation. All rights reserved.
> 
> c:\Users\gtaillon>
> ]0;  - powershell  -ExecutionPolicy Bypass C:\Users\gtaillon\AppData\Local\Temp\vscode_add_ssh_key_to_agent.ps1(powershell -ExecutionPolicy Bypass C:\Users\gtaillon\AppData\
> Local\Temp\vscode_add_ssh_key_to_agent.ps1) & exit /b 0
> 
> PS: adding key to ssh-agent
> ssh-add
> C:\Users\gtaillon\.ssh\id_rsa
> 
> Could not open a connection to your authentication agent.
> >>> UUID <<<
> 
add-ssh-key failed
> ]0; 
add-ssh-key failed
"add-ssh-key" terminal command done
Key with passphrase must be in ssh-agent
------

```

### Workaround
The extension seems to launch a powershell script to run `ssh-add` which aborts the connection procedure when returning a non zero exit code. The workaround replaces `ssh-add` by a bash-batch proxy script which executes the real `ssh-add` executable when launched as a bash script, and does nothing but exit with return code 0 when launched as a batch script.

From the Git for Windows shell
```
mv /usr/bin/ssh-add /usr/bin/ssh-add.real
echo -e ':; /usr/bin/ssh-add.real "$@"\nexit /b 0' > /usr/bin/ssh-add.cmd
```

#### Upside
vscode can now connect to the remote server successfully
#### Downsides
* ssh-agent does not work
* passphrase must be input twice whenever switching the remote folder

**Comment by roblourens** [comment]
Yes it used to be that we couldn't continue connecting without the passphrase cached, but this restriction isn't needed anymore.

I suppose you don't have permissions to install the ssh agent either...

For now you will have to enter your passphrase twice but I am working on improving that too.

**Comment by gxtaillon** [comment]
No I'm not allowed to do that either.

Could there be an option to disable checking/using ssh-agent so that no workarounds are required, at the cost of having to type in passwords twice?

**Comment by roblourens** [comment]
@gxtaillon That should be what you get now in the nightly ssh extension
