### ISSUE TITLE
[Remote-SSH Bug]: After updating VSCode to the latest version, can not connect to remote server by ssh

### ISSUE THREAD

**Issue by EricLabile** [microsoft/vscode-remote-release#9480]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### Expected Behavior

After updating VSCode to the latest version, can not connect to remote server by ssh.
I tried various methods(delete the "known_hosts", clear the ".vscode-server" etc.) and it still doesn't work, showing "The remote host may not meet VS Code Server's prerequisites for glibc and libstdc++"

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by isaacNingLee** [comment]
Hi,
I have the same problem as well, it seems the new update require some specific glibc and libstdc++ which is not compatible to my remote ends. I login to my remote end and delete the .vscode server to trigger wget again but it still fails. I am new to Github issue and I apology if my comment is not adhering to the required format

Cheers

**Comment by EricLabile** [comment]
The log is "Warning: Missing GLIBCXX >= 3.4.25! from /usr/lib64/libstdc++.so.6.0.19
Warning: Missing GLIBC >= 2.28! from /usr/lib64/libc-2.17.so
Error: Missing required dependencies. Please refer to our FAQ https://aka.ms/vscode-remote/faq/old-linux for additional information."
Hope this will be useful.

**Comment by Manaspaul623** [comment]
Hi,
I've the same issue. I was connecting to ec2 till tomorrow before updating to latest VS Code.
But it is not connecting after updating.
Showing the below message - 
"**The remote host may not meet VS Code Server's prerequisites for glibc and libstdc++. "**

**Comment by DavidC-75** [comment]
> So I've downgraded to VS code version 1.85 and it is connecting.

Maybe downgrading isn't necessary after all (with some linux distributions at least). See https://github.com/microsoft/vscode-remote-release/issues/9467#issuecomment-1925498025

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/203375
