### ISSUE TITLE
Unable to start vscode server on Alpine Linux

### ISSUE THREAD

**Issue by fxzxmic** [microsoft/vscode-remote-release#9484]
- VSCode Version: 1.86.0
- Local OS Version: Windows 11
- Remote OS Version: Alpine Linux 3.19
- Remote Extension/Connection Type: WSL

- Logs:
![image](https://github.com/microsoft/vscode-remote-release/assets/54622331/62c47a69-b98f-42f3-a27d-8249694225c2)

Does this issue occur when you try this locally?: No need.
Does this issue occur when you try this locally and all extensions are disabled?: No need.

**Comment by deepak1556** [comment]
/fixedWith https://github.com/microsoft/vscode/commit/fdbf304519ed209b0fabbcae67ac90c02117d356
