### ISSUE TITLE
Unable to install extensions in devcontainer

### ISSUE THREAD

**Issue by NZTimKeegan** [microsoft/vscode-remote-release#9494]
Type: <b>Bug</b>

* create a fresh project
* add devcontainer configuration
* reopen in devcontainer
* try to install any extension

Expected: the extension is installed

Observed: installation hangs at "installing" (left for several hours, installation never completes)

Additional system details:

I've been able to reproduce this with the following combinations:
  * VScode 1.86.0 with DevContainers v0.338.0
  * VScode 1.86.0 with DevContainers v0.338.1
  * VScode 1.86.0 with DevContainers v0.339.0
  * VScode 1.87.0 with DevContainers v0.338.1
  * VScode 1.87.0 with DevContainers v0.339.0

Devcontainer is using the Docker Engine (25.0.2) that ships with Docker Desktop (4.27.1 (136059)).

I have also tried removing the `vscode` volume and the container to start completely from scratch with the same result.

Extension version: 0.339.0
VS Code version: Code 1.86.0 (Universal) (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:29:15.765Z)
OS version: Darwin arm64 23.3.0
Modes:
Remote OS version: Linux x64 6.6.12-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 5, 7|
|Memory (System)|32.00GB (0.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Python 3 @ desktop-linux|
|OS|Linux x64 6.6.12-linuxkit|
|CPUs|unknown (9 x 0)|
|Memory (System)|15.60GB (11.66GB free)|
|VM|0%|
</details>

**Comment by machikoyasuda** [comment]
Experiencing the same issue on Apple M1 Pro and VScode 1.86.0.

**Comment by NZTimKeegan** [comment]
I think this might have been fixed by the latest VSCode release (1.86.1).

I am using this combination today and I can install extensions again:

* VSCode 1.86.1 with DevContainers v0.338.1

**Comment by tuck1s** [comment]
> I think this might have been fixed by the latest VSCode release (1.86.1).
> 
> I am using this combination today and I can install extensions again:
> 
> * VSCode 1.86.1 with DevContainers v0.338.1

Thank you, this fixed it for me also. For me, that specific version of DevContainers works. So does the latest DevContainers `v0.341.0 (pre-release)`

**Comment by bamurtaugh** [comment]
Thank you all for the updates! I'm going to close this issue as it sounds like it's now resolved in the latest version, but please let me know if you're still experiencing any trouble.

**Comment by m8dotpie** [comment]
Met this issue on the 0.354.0 version of devcontainers extension. Rolled back to 0.338.1 and everything is working fine again. I am on apple silicon mac with amd64 container through docker rosetta support.

**Comment by tuck1s** [comment]
I regularly run into issues where some extensions I'm using stick at "installing .." and never complete. The workaround is to add the following to `devcontainer.json`, attribute `customizations.vscode.settings` as follows:

```
      "settings": {
				"extensions.verifySignature": false
			}
```

This allows the install to complete. I realise it's not ideal, but it works. Also using an amd64 container on Apple silicon.

**Comment by italocjs** [comment]
I was having the same issue, just updated code (help -> restart to update) and it fixed, now extensions are loading in container.

**Comment by bastiansg** [comment]
> I regularly run into issues where some extensions I'm using stick at "installing .." and never complete. The workaround is to add the following to `devcontainer.json`, attribute `customizations.vscode.settings` as follows:
> 
> ```
>       "settings": {
> 				"extensions.verifySignature": false
> 			}
> ```
> 
> This allows the install to complete. I realise it's not ideal, but it works. Also using an amd64 container on Apple silicon.

Thanks this works for me!
