### ISSUE TITLE
code serve-web leave node.exe process after exit

### ISSUE THREAD

**Issue by kaala** [microsoft/vscode-remote-release#9495]
- VSCode Version: code 1.86.0 (commit 05047486b6df5eb8d44b2ecd70ea3bdf775fd937)
- Local OS Version: Windows10
- Remote OS Version: Windows10
- Remote Extension/Connection Type: Containers/WSL/Server

- Logs:

Steps to Reproduce:

1. start code serve-web.
2. open browser and open a project to work.
3. close browser.
4. press ctrl+c to shutdown code server.
5. open process explorer to check node.exe is still alive.
![image](https://github.com/microsoft/vscode-remote-release/assets/246542/ad823071-4a6b-49bc-84c0-8aacf5a03f17)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by connor4312** [comment]
It's intentional that the VS Code server can outlive a particular CLI. It will shut down after a few minutes of no connections.
