### ISSUE TITLE
Support connecting to remote server that is totally not publicly exposed

### ISSUE THREAD

**Issue by Ir1d** [microsoft/vscode-remote-release#950]
I read about https://code.visualstudio.com/docs/remote/ssh#_forwarding-a-port-creating-ssh-tunnel but it seems that this requires the server to expose ssh.

In my case I have a machine with no public IP, so I use SSH tunnels to connect it. I wonder if it's possible to implement this feature with this plugin. Thx in advance.

My commands:

```
# remote
ssh -qTfNn -R 20066:localhost:22 AUserForTunnel@ip.of.forwarding.server -p 22 -o ServerAliveInterval=180
# local
ssh -J AUserForTunnel@ip.of.forwarding.server:22 -p 20066 localhost -l myusername
```

**Comment by roblourens** [comment]
This should be possible to configure, but you have to set it up in an ssh config file using ProxyCommand, ProxyJump, etc so that vscode can connect without setting extra command line parameters.

**Comment by roblourens** [comment]
See the proxy section here: https://code.visualstudio.com/docs/remote/troubleshooting#_troubleshooting-hanging-or-failing-connections

**Comment by Ir1d** [comment]
Thanks @roblourens for the guidance.

I'm posting my config here for future reference:

```
Host Jumpwww
  User jumpuser
  HostName jumpserver
  Port 22

Host myserver
  User localuser
  HostName localhost
  Port myport
  ProxyJump  Jumpwww
```

the corresponding ssh command is like this:

```
ssh -J jumpuser@jumpserver:22 -p myport localhost -l localuser
```
