### ISSUE TITLE
The remote host may not meet VS Code Server's prerequisites for glibc and libstdc++

### ISSUE THREAD

**Issue by zulaliskender** [microsoft/vscode-remote-release#9501]
There was no problem with remote SSH until 3 days ago. Now I'm getting the following error and I can't connect to the server

The remote host may not meet VS Code Server's prerequisites for glibc and libstdc++

**Comment by perrog** [comment]
CentOS 7 reached EOL June 30, 2024 so I suspect November release was the last official compatible version.
I wonder if it is possible to set LD_LIBRARY_PATH only for code-server during launch, pointing to newer glibc/libstdc++ , without affecting system-wide?

**Comment by traek** [comment]
This is ridiculous. We have grown to rely on the ability to connect to whatever systems we need to maintain. RHEL 7 isn't EOL nor is it about to be. RHEL 7 is about to be EOM which is very different. Still, EOM doesn't come until July of this year and we are all going to have to work on moving to the later version,..

What I can't imagine is how Microsoft KNOWS there's a market downturn especially affecting tech and this is the time they take one of our essential tools (keeping us using Microsoft tools like VSCode) and nerf it six months before a major OS with an install base in the tens of thousands in the US alone!? Sure, I can use this for newer projects but this needs a solution. They claimed in another issue that this would be allowed for another year. I moved to the prerelease of that extension and still I cannot attach to RHEL 7 nodes remotely inside of VSCode. Then they locked the issue so I couldn't even ask _how_ we are supposed to access this.

Serves me right for allowing an update with zero warning as to what would happen.

**Comment by connor4312** [comment]
This is fixed in VS Code 1.86.1
