### ISSUE TITLE
The remote host may not meet VS Code Server's prerequisites for glibc and libstdc++

### ISSUE THREAD

**Issue by SANTHIGONELA** [microsoft/vscode-remote-release#9508]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

### Anything else?

![image](https://github.com/microsoft/vscode-remote-release/assets/64600488/98115b63-32aa-4e9b-833f-57f563eb0467)

**Comment by connor4312** [comment]
This is fixed in VS Code 1.86.1
