### ISSUE TITLE
Allow specifying subdirectory to open when port forwarding detected

### ISSUE THREAD

**Issue by heaths** [microsoft/vscode-remote-release#9518]
We have [port forwarding set up](https://github.com/Azure/azure-sdk/blob/48e935a3b3f1ff9d52166c34a132dd67c82cdf59/.devcontainer/devcontainer.json#L30-L38) to be able to browse our static site once generated; however, because we have a [baseurl](https://github.com/Azure/azure-sdk/blob/48e935a3b3f1ff9d52166c34a132dd67c82cdf59/_config.yml#L24) set in our Jekyll `_config.yml` the browser reports 404. We would like to be able to customize this to open a subdirectory of the site e.g., `https://127.0.0.1:4000/azure-sdk`.

One idea would be to add this to [`portAttributes`](https://containers.dev/implementors/json_reference/#general-properties) or even `otherPortAttributes`, which shares the same schema e.g.,

```json
{
  "forwardPorts": [4000],
  "portAttributes": {
    "path": "/azure-sdk"
  }
}
```

This `path` could be relative or absolute since it resolves to the site root either way.

**Comment by heaths** [comment]
I'd be happy to work on this myself, but I don't see any source or mention of it. Is this developed internally?

**Comment by bamurtaugh** [comment]
Thanks for also opening in https://github.com/devcontainers/spec/issues/413! I think the spec is a perfect spot to track this, so I'll close this issue in favor of that one.
