### ISSUE TITLE
UI bug -- Remote explorer dropdown no longer allowing connecting to SSH host for system rollback

### ISSUE THREAD

**Issue by ZackingIt** [microsoft/vscode-remote-release#9521]
Does this issue occur when all extensions are disabled?: n/a -- No.

- VS Code Version:  1.85.2
- OS Version: 16.04 Linux

Background: Needed to roll back VSCode to 1.85.2 due to glibc / compatability between 1.86.0 and my remote machine running 16.04 Linux.

Steps to Reproduce:

1. Roll back an updated VSCode that was at 1.86.0 to 1.85.2

2. For Remote-SSH extension, "Install Another Version" to 0.106.4 (dropdown menu which is not shown doesn't allow me to choose Connect to SSH Host, only Dev Container and WSL Targets)

<img width="284" alt="image" src="https://github.com/microsoft/vscode/assets/24970138/93bc8f66-48ea-423f-93fc-412dc3623731">

3. Reload VSCode

4.  Remote Explorer no longer shows SSH Host connection options.  These can still be accessed by hitting F1 and going to a "Connect to a Host", but the sidebar is disabled -- clearly a bug given that functionality is preserved by UI is not reflecting it.

**Comment by roblourens** [comment]
This is driven by the "Remote Explorer" extension, is it possible you lost this one while changing versions? Or ended with with incompatible versions.

In any case, I think this works with the latest of everything installed.
