### ISSUE TITLE
Dev Containers won't install VSCode extensions for linux/amd64 containers on Apple M2 

### ISSUE THREAD

**Issue by ragheb-deriv** [microsoft/vscode-remote-release#9525]
Version: 1.86.0 (Universal)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:29:15.765Z (1 wk ago)
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0

Chip : Apple M2 Pro
macOS Sonoma Version 14.3

Docker desktop version 4.27.1
Engine: 25.0.2
Compose: v2.24.3-desktop.1
Credential Helper: v0.8.1
Kubernetes: v1.29.1

_Use Rosetta for x86/amd64 emulation on Apple Silicon_

Steps to Reproduce:

1. Use any devcontainer configuration with a linux/amd64-only image
2. Try to install any extension using VSCode UI, CLI in devcontainer or devcontainer.json
3. The extension stays in the installing state

![image](https://github.com/microsoft/vscode-remote-release/assets/91007977/cfb24cd4-8bbc-42aa-87a2-c7b83a8e9544)

If you check the services running in the container => vsce-sign is taking too much CPU. if you kill that service, everything works fine and the extensions install normally. 

I thought that bug was fixed here but I guess it surfaced back somehow => https://github.com/microsoft/vscode-remote-release/issues/8169

**Comment by ragheb-deriv** [comment]
This issue is fixed on version 1.86.1

**Comment by vaclcer** [comment]
No, its not. At least not in 1.87.1. Experiencing the very same issue as in https://github.com/microsoft/vscode-remote-release/issues/8169

vsce-sign process in dev container stuck, utilizing all resources, when killed manually, extensions are installed with error:

`[warning] Extension signature verification failed with error 'UnknownError': ms-python.python`

With or without rosetta enabled.
