### ISSUE TITLE
[Remote-SSH Bug]: check-requirements.sh handles systems with multiple libc incorrectly [patch included]

### ISSUE THREAD

**Issue by jotasi** [microsoft/vscode-remote-release#9526]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

The issue is not within the connection but with server startup on the remote. I traced the issue to `helpers/check-requirements.sh` returning an exit code 1.

### Expected Behavior

When connecting to a remote via ssh the server should start even if there are multiple paths for `libc.so.6` and the desired architecture (if these fulfill the version requirement). (As a bonus, if the startup fails because of the requirement checking script crashing, some error message in the server log would be helpful.)

### Steps To Reproduce

Connect a window to a server via ssh that has multiple paths for `libc.so.6` matching the desired architecture.

Alternatively, just try to start the server directly via `bin/code-server` in the servers installation directory when being logged in on such a machine, which fails with empty output and exit code 1.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
N/A (the server log is actually empty and startup of the server command was verified to be the problem by start the server via bin/code-server directly, which prints nothing to stdout or stderr and exits with error code 1.
```

</p>
</details>

### Anything else?

The issue is closely related to #9510 but instead of multiple versions of libstdc++, the server has multiple versions / copies of libc.

The issue could be fixed rather simply (similarly to the other issue) by just using the first result when searching for `libc.so.6` within the `bin/helpers/check-requirements.sh` script.

```text
--- a/check-requirements.sh       XXX
+++ b/check-requirements.sh       YYY
@@ -90,7 +90,7 @@
         libc_paths=$(/sbin/ldconfig -p | grep 'libc.so.6')

         if [ "$(echo "$libc_paths" | wc -l)" -gt 1 ]; then
-            libc_path=$(echo "$libc_paths" | grep "$LDCONFIG_ARCH" | awk '{print $NF}')
+            libc_path=$(echo "$libc_paths" | grep "$LDCONFIG_ARCH" | awk '(NR==1){print $NF}')
         else
             libc_path=$(echo "$libc_paths" | awk '{print $NF}')
         fi
```

**Comment by deepak1556** [comment]
/fixedWith https://github.com/microsoft/vscode/commit/f6a5654dbf9811b94dd8848571a84b73a7a34813

Please test with latest [insiders](https://code.visualstudio.com/insiders)
