### ISSUE TITLE
Fails to Prompt for key when using gpg for ssh

### ISSUE THREAD

**Issue by skewballfox** [microsoft/vscode-remote-release#9527]
Type: <b>Bug</b>

Sorry if this is considered a duplicate, though the other issues are for WSL which is it's own beast. I'm trying to remote between two linux systems runnign fedora39, and I'm using gpg for ssh authentication. The setup for gpg is from [drduh's yubikey gpg guide](https://github.com/drduh/YubiKey-Guide). The current (truncated) contents of the desktop file is this:
```
[Desktop Entry]
Name=Visual Studio Code
...
Exec=sh -c "env SSH_ASKPASS\=\"\$(gpgconf --list-dirs agent-ssh-socket)\"  /usr/share/code/code --enable-features=UseOzonePlatform,Vulkan --ozone-platform=wayland --unity-launch %F"
...
```
1. launch vscode
2. connect to any remote server in a new window

## Actual Result 
permission denied

## Expected results
I'm prompted for my pin if my yubikey is plugged in

## Notes

Opening a terminal SSH_ASKPASS is set correctly, and that variable is not set in the config for that terminals shell, so it is being set from the desktop file. 

ssh works from a terminal both in and outside of vscode

Launching vscode from a terminal makes it so that remote ssh works, though I would rather avoid relying on that as a solution.
my remote ssh relevant settings:

```
  "remote.SSH.showLoginTerminal": true,
  "remote.SSH.useLocalServer": true,
  "remote.SSH.externalSSH_ASKPASS": true,
  "remote.SSH.enableX11Forwarding": false,
  "remote.SSH.enableRemoteCommand": true,
  "remote.SSH.logLevel": "trace",
  "remote.SSH.remoteServerListenOnSocket": false,
  "remote.SSH.enableAgentForwarding": false
```

Extension version: 0.109.2024020215
VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:27:46.147Z)
OS version: Linux x64 6.6.14-200.fc39.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 5650U with Radeon Graphics (12 x 3334)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: enabled_on<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|14.46GB (5.25GB free)|
|Process Argv|--enable-features=UseOzonePlatform,Vulkan --ozone-platform=wayland --unity-launch --crash-reporter-id c7d8e011-0824-4f76-bb2c-8406dd279b8d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
dsvsc019b:30953937
b1063948:30958189
7j2b6412:30949929
bg6jg535:30958357
ccp2r6:30958158

```

</details>

**Comment by joshspicer** [comment]
Is this still an issue for you? Could you please share your logs (`> Remote-SSH: Show Log` in the command palette) after reproducing the issue so I can see how our terminal handling code processed your yubikey touch?
