### ISSUE TITLE
Dev Container stopped working - Fails to detect .devcontainer in current folder

### ISSUE THREAD

**Issue by ramki88** [microsoft/vscode-remote-release#9530]
Type: <b>Bug</b>

1. Open a folder containing .devcontainer
2. In command pallete choose Reopen in contianer

VS Code version: Code - Insiders 1.87.0-insider (Universal) (8fa84589eef3538dbc763ff98dc7d5a8a0c56374, 2024-02-09T05:49:05.817Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 7, 10|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
remotehub|Git|0.63.2024010901
vscode-docker|ms-|1.28.0
vscode-dotnet-runtime|ms-|2.0.1
vscode-kubernetes-tools|ms-|1.3.15
black-formatter|ms-|2024.1.10371008
debugpy|ms-|2024.1.10371006
isort|ms-|2023.10.1
pylint|ms-|2023.11.13481007
python|ms-|2024.1.10391007
vscode-pylance|ms-|2024.2.1
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.338.1
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
makefile-tools|ms-|0.9.4
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.41.2023121801
remote-server|ms-|1.5.0
autodocstring|njp|0.6.1
material-icon-theme|PKi|4.33.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.14.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22
markdown-pdf|yza|1.5.0
material-theme|zhu|3.16.2

</details>

**Comment by ramki88** [comment]
> The folder `$TMPDIR/vsch` might not exist yet, could you check? I will add a fix that makes sure it is created before writing that file.

Yup. It is not there.

**Comment by ramki88** [comment]
> > The folder `$TMPDIR/vsch` might not exist yet, could you check? I will add a fix that makes sure it is created before writing that file.
> 
> Yup. It is not there.

Manually creating the folder `vsch` brings up the dev container when opened from Recent. But starting devcontainer using `Reopen in Container` still fails. Sometimes it's prompting to create the configuration, or failes with the below error:
[113522 ms] Error: connect ETIMEDOUT 185.199.110.153:443
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)

**Comment by noam-codefresh** [comment]
i am getting the same issue, running the 0.341.0 pre-release version.
i downgraded to release (0.338.1), and it sees to be working. that `vsch` directory is still not there, though.

**Comment by chrmarti** [comment]
> Manually creating the folder `vsch` brings up the dev container when opened from Recent. But starting devcontainer using `Reopen in Container` still fails. Sometimes it's prompting to create the configuration, or fails with the below error: [113522 ms] Error: connect ETIMEDOUT 185.199.110.153:443 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)

@ramki88 Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)

@noam-codefresh You can manually create the `vsch` folder for now. I'm getting the fix published later today.

**Comment by ramki88** [comment]
> > Manually creating the folder `vsch` brings up the dev container when opened from Recent. But starting devcontainer using `Reopen in Container` still fails. Sometimes it's prompting to create the configuration, or fails with the below error: [113522 ms] Error: connect ETIMEDOUT 185.199.110.153:443 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
> 
> @ramki88 Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)
> 
> @noam-codefresh You can manually create the `vsch` folder for now. I'm getting the fix published later today.

[13172 ms] Dev Containers 0.341.0 in VS Code 1.87.0-insider (8fa84589eef3538dbc763ff98dc7d5a8a0c56374).
[13172 ms] Start: Run: docker version --format {{json .}}
[13249 ms] {"Client":{"CloudIntegration":"v1.0.35+desktop.10","Version":"25.0.3","ApiVersion":"1.44","DefaultAPIVersion":"1.44","GitCommit":"4debf41","GoVersion":"go1.21.6","Os":"darwin","Arch":"arm64","BuildTime":"Tue Feb  6 21:13:26 2024","Context":"desktop-linux"},"Server":{"Platform":{"Name":"Docker Desktop 4.27.2 (137060)"},"Components":[{"Name":"Engine","Version":"25.0.3","Details":{"ApiVersion":"1.44","Arch":"arm64","BuildTime":"Tue Feb  6 21:14:22 2024","Experimental":"false","GitCommit":"f417435","GoVersion":"go1.21.6","KernelVersion":"6.6.12-linuxkit","MinAPIVersion":"1.24","Os":"linux"}},{"Name":"containerd","Version":"1.6.28","Details":{"GitCommit":"ae07eda36dd25f8a1b98dfbf587313b99c0190bb"}},{"Name":"runc","Version":"1.1.12","Details":{"GitCommit":"v1.1.12-0-g51d5e94"}},{"Name":"docker-init","Version":"0.19.0","Details":{"GitCommit":"de40ad0"}}],"Version":"25.0.3","ApiVersion":"1.44","MinAPIVersion":"1.24","GitCommit":"f417435","GoVersion":"go1.21.6","Os":"linux","Arch":"arm64","KernelVersion":"6.6.12-linuxkit","BuildTime":"2024-02-06T21:14:22.000000000+00:00"}}

**Comment by chrmarti** [comment]
@ramki88 Could you check if there is more in the log? The one you posted lacks an error message.

**Comment by ramki88** [comment]
> @ramki88 Could you check if there is more in the log? The one you posted lacks an error message.

Unfortunately there are no further logs. But I was able to reproduce the issue, If `.devcontainer` is part of `.gitignore` it seems to not detect that a configuration exists. Is this how it's supposed to be?

**Comment by chrmarti** [comment]
@andreamah `vscode.workspace.findFiles` appears always apply the `.gitignore` file's exclusions, also when passing `null` as the second argument and turning it off in the user settings:
![Image](https://github.com/microsoft/vscode-remote-release/assets/9205389/7a07bb2c-7eb3-4aa5-871f-94cc4fda319a)

Should passing `null` as the exclude argument also turn off the use of `.gitignore`?

**Comment by andreamah** [comment]
Good catch, fixing in https://github.com/microsoft/vscode/pull/204845

**Comment by rzhao271** [comment]
@chrmarti what are some verification steps for this issue?

**Comment by andreamah** [comment]
I believe that problem was that `.devcontainer` was being ignored in the workspace's gitignore and that was mistakenly being ignored by the devcontainer extension. The steps for this would look like:

1. Create a `.gitignore` in your repo that ignores `.devcontainer`.
2. Follow the steps in the original issue.
