### ISSUE TITLE
Align presentation of empty workbench on startup with SSH

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#954]
show explorer if not visible, show terminal

**Comment by aeschli** [comment]
@kieferrm I moved your code as is.
Wondering why explorer and terminal are not opened if `startupEditor !== 'welcomePage' && startupEditor !== 'welcomePageInEmptyWorkbench'`
(startupEditor === welcomePage is the default setting)

**Comment by kieferrm** [comment]
@aeschli We wanted to avoid duplication. The Welcome page already has a **Start** section with `Open Folder` which in the remote case opens the remote folder picker.
