### ISSUE TITLE
[Remote-SSH Bug]: "Unauthorized client refused" when using VS Code OSS

### ISSUE THREAD

**Issue by orgads** [microsoft/vscode-remote-release#9556]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Steps To Reproduce

1. Run VS Code OSS version
2. Install both Remote Development and Remote-SSH extensions from VSIX
3. Try to connect to a remote server

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Server bound to 127.0.0.1:42179 (IPv4)
Extension host agent listening on 42179

[11:19:19]




[11:19:19] Extension host agent started.
[11:19:19] [127.0.0.1][3aa92209] Unauthorized client refused.
[11:19:19] [127.0.0.1][1d7b00c3] Unauthorized client refused.
Got delay-shutdown request while in shutdown timeout, delaying
[11:19:20] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[11:19:20] Cancelling previous shutdown timeout
[11:19:20] [127.0.0.1][ad08b69d] Unauthorized client refused.
[11:19:20] [127.0.0.1][2a4ac072] Unauthorized client refused.
Got delay-shutdown request while in shutdown timeout, delaying
[11:19:22] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[11:19:22] Cancelling previous shutdown timeout
```

</p>
</details>

### Anything else?

VS Code official release works fine for the same server.

I tried deleting .vscode-server-oss completely and killing all the vscode processes on the remote, but it didn't help.

**Comment by roblourens** [comment]
Sorry, we don't support using Remote-SSH with the OSS build, only official product builds, because the remote connection depends on a non-OSS component.

**Comment by orgads** [comment]
I wanted to test my change: https://github.com/microsoft/vscode/pull/204807

Is there another way to test it?

**Comment by roblourens** [comment]
I think you can open a remote test connection from OSS by running the command "New TestResolver Window".

If that doesn't work for your scenario, you'll just have to either have a maintainer test it, or have one of us do a private insiders build that contains your change. So

**Comment by orgads** [comment]
Thank you. It didn't work out of the box, but I found a workaround (see https://github.com/microsoft/vscode/pull/204807#issuecomment-1951041668) :)
