### ISSUE TITLE
Permission denied when switch between multiple devcontainers.

### ISSUE THREAD

**Issue by theokoeldavidson** [microsoft/vscode-remote-release#9558]
- VSCode Version: 1.86.1
- ms-vscode-remote.remote-containers Version: 0.338.1
- Local OS Version: Ubuntu 22.04.3 LTS

# Description
I'm actually trying to setup a microservices projet through Devcontainers. I'm based my project structure like the [advenced documentation](https://code.visualstudio.com/remote/advancedcontainers/connect-multiple-containers), to make some test on the performance of this kind of project.
I have exactly the same project structure has above, with two images of `mcr.microsoft.com/devcontainers/javascript-node:1-20-bookworm`. And my goal was to `F1> Dev Containers: Switch Container` between my differents servicies has describe in the [docs](https://code.visualstudio.com/remote/advancedcontainers/connect-multiple-containers#_connect-to-multiple-containers-in-a-single-vs-code-window).
But, when I try tu update and save a file from a different devcontainer as launch. I got a `Permission denied` on the file.

![image](https://github.com/microsoft/vscode-remote-release/assets/158167388/862736a6-9890-454d-a8dc-6e01825047e5)

# Steps to Reproduce:
1. Clone the [project](https://stackblitz.com/edit/typescript-1spgte)
2. `F1> Dev Containers: Reopen in Container > Gateway`
3. `F1> Dev Containers: Switch Container > Auth`
4. Try to edit and save `index.ts`

# Some questions/points to studies.
After some research, I saw some surprising points:

1. Building of devcontainers:
When we run thoses devconatiners, they are not run has the same way.
![image](https://github.com/microsoft/vscode-remote-release/assets/158167388/f2a29b5c-6735-4fd6-bd84-904f4404ae46)
One is run correcly with the devcontainer config
![image](https://github.com/microsoft/vscode-remote-release/assets/158167388/d4aaea3e-458f-4977-942b-0b9963f49131)
But the second is like a normal container.
![image](https://github.com/microsoft/vscode-remote-release/assets/158167388/e3e45050-ca91-48d0-9a7c-29663e8a858d)
Is supose that is normal. However, I was expecting thoses devconatiners will be update when I switch between us, but is not the case ?

2. Temporary solution:
A temporary solution that I found is to `F1> Dev Containers: Rebuild container` each time I switch of devcontainer.
This cannot be a solution, because I know that in the final version of my project there will be `postCreateCommands` which will take several minutes, and therefore which cannot be re-executed for each switch.

**Comment by bamurtaugh** [comment]
Thanks for opening.

@chrmarti I'd love to get your insights on this issue. I tried the exact setup in https://code.visualstudio.com/remote/advancedcontainers/connect-multiple-containers as well, but opening in a dev container fails with:

> Error: Command failed: docker-compose version --short
>     at va (c:\Users\brmurtau\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.352.0\dist\spec-node\devContainersSpecCLI.js:462:889)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async fH (c:\Users\brmurtau\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.352.0\dist\spec-node\devContainersSpecCLI.js:390:23600)
>     at async MrA (c:\Users\brmurtau\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.352.0\dist\spec-node\devContainersSpecCLI.js:661:37707)

**Comment by chrmarti** [comment]
@theokoeldavidson That's a limitation on Linux in that only the container corresponding to the devcontainer.json for which `docker-compose up` runs gets its UID/GID updated to those of the local user.

@bamurtaugh Could you check the log above that? Maybe this is an old `docker-compose` version without  the `--short` option?

**Comment by bamurtaugh** [comment]
@chrmarti here's the full log:

> [1311 ms] Dev Containers 0.352.0 in VS Code 1.88.0-insider (3e41bfbe49c8ba3165dfcd3ab54db75430950774).
> [1310 ms] Initializing configuration support...
> [1312 ms] Internal initialization of dev container support package...
> [1458 ms] Start: Run: git rev-parse --abbrev-ref --symbolic-full-name @{u}
> [26881 ms] Start: Run: docker version --format {{json .}}
> [27172 ms] {"Client":{"CloudIntegration":"v1.0.35+desktop.11","Version":"25.0.3","ApiVersion":"1.44","DefaultAPIVersion":"1.44","GitCommit":"4debf41","GoVersion":"go1.21.6","Os":"windows","Arch":"amd64","BuildTime":"Tue Feb  6 21:13:02 2024","Context":"default"},"Server":{"Platform":{"Name":"Docker Desktop 4.28.0 (139021)"},"Components":[{"Name":"Engine","Version":"25.0.3","Details":{"ApiVersion":"1.44","Arch":"amd64","BuildTime":"Tue Feb  6 21:14:25 2024","Experimental":"false","GitCommit":"f417435","GoVersion":"go1.21.6","KernelVersion":"5.15.133.1-microsoft-standard-WSL2","MinAPIVersion":"1.24","Os":"linux"}},{"Name":"containerd","Version":"1.6.28","Details":{"GitCommit":"ae07eda36dd25f8a1b98dfbf587313b99c0190bb"}},{"Name":"runc","Version":"1.1.12","Details":{"GitCommit":"v1.1.12-0-g51d5e94"}},{"Name":"docker-init","Version":"0.19.0","Details":{"GitCommit":"de40ad0"}}],"Version":"25.0.3","ApiVersion":"1.44","MinAPIVersion":"1.24","GitCommit":"f417435","GoVersion":"go1.21.6","Os":"linux","Arch":"amd64","KernelVersion":"5.15.133.1-microsoft-standard-WSL2","BuildTime":"2024-02-06T21:14:25.000000000+00:00"}}
> [28324 ms] Running Dev Containers CLI:   read-configuration --workspace-folder c:\Users\brmurtau\OneDrive - Microsoft\Documents\GitHub\SwitchContainersTest --log-level debug --log-format json --config c:\Users\brmurtau\OneDrive - Microsoft\Documents\GitHub\SwitchContainersTest\.devcontainer\node-container\devcontainer.json --include-merged-configuration --mount-workspace-git-root
> [28338 ms] ProxyResolver#loadSystemCertificates count
> [28343 ms] ProxyResolver#loadSystemCertificates count filtered
> [28344 ms] Start: Run: C:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe c:\Users\brmurtau\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.352.0\dist\spec-node\devContainersSpecCLI.js read-configuration --workspace-folder c:\Users\brmurtau\OneDrive - Microsoft\Documents\GitHub\SwitchContainersTest --log-level debug --log-format json --config c:\Users\brmurtau\OneDrive - Microsoft\Documents\GitHub\SwitchContainersTest\.devcontainer\node-container\devcontainer.json --include-merged-configuration --mount-workspace-git-root
> [28685 ms] @devcontainers/cli 0.58.0. Node.js v18.18.2. win32 10.0.25987 x64.
> [28685 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\brmurtau\OneDrive - Microsoft\Documents\GitHub\SwitchContainersTest --filter label=devcontainer.config_file=c:\Users\brmurtau\OneDrive - Microsoft\Documents\GitHub\SwitchContainersTest\.devcontainer\node-container\devcontainer.json
> [28970 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\brmurtau\OneDrive - Microsoft\Documents\GitHub\SwitchContainersTest
> [29282 ms] Start: Run: docker-compose version --short
> [29459 ms] Error: Command failed: docker-compose version --short
>     at va (c:\Users\brmurtau\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.352.0\dist\spec-node\devContainersSpecCLI.js:462:889)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async fH (c:\Users\brmurtau\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.352.0\dist\spec-node\devContainersSpecCLI.js:390:23600)
>     at async MrA (c:\Users\brmurtau\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.352.0\dist\spec-node\devContainersSpecCLI.js:661:37707)
> [29479 ms] Exit code 1
> [29480 ms] Running Dev Containers CLI:   read-configuration --workspace-folder c:\Users\brmurtau\OneDrive - Microsoft\Documents\GitHub\SwitchContainersTest --log-level debug --log-format json --config c:\Users\brmurtau\OneDrive - Microsoft\Documents\GitHub\SwitchContainersTest\.devcontainer\node-container\devcontainer.json --mount-workspace-git-root
> [29481 ms] Start: Run: C:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe c:\Users\brmurtau\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.352.0\dist\spec-node\devContainersSpecCLI.js read-configuration --workspace-folder c:\Users\brmurtau\OneDrive - Microsoft\Documents\GitHub\SwitchContainersTest --log-level debug --log-format json --config c:\Users\brmurtau\OneDrive - Microsoft\Documents\GitHub\SwitchContainersTest\.devcontainer\node-container\devcontainer.json --mount-workspace-git-root
> [29871 ms] @devcontainers/cli 0.58.0. Node.js v18.18.2. win32 10.0.25987 x64.
> [29871 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\brmurtau\OneDrive - Microsoft\Documents\GitHub\SwitchContainersTest --filter label=devcontainer.config_file=c:\Users\brmurtau\OneDrive - Microsoft\Documents\GitHub\SwitchContainersTest\.devcontainer\node-container\devcontainer.json
> [30139 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\brmurtau\OneDrive - Microsoft\Documents\GitHub\SwitchContainersTest
> [30455 ms] Start: Run: docker-compose version --short

**Comment by chrmarti** [comment]
@bamurtaugh I don't see any hints on what is failing. Does `docker-compose version --short` work in a terminal?

**Comment by bamurtaugh** [comment]
> Does docker-compose version --short work in a terminal?

Good catch - it does not! Very weird, because I thought Docker Compose was installed automatically as part of Docker Desktop for Windows? 🤔 I'll spend time debugging that. 

Based on this update on my end and your feedback for @theokoeldavidson's issue, I think we can close this one. @theokoeldavidson @chrmarti if you think we should leave this open though, please just let me know!

**Comment by chrmarti** [comment]
I would also expect `docker-compose` to update with Docker Desktop. Maybe an older version is on the `PATH` before Docker Desktop's `PATH` entry.
