### ISSUE TITLE
Remote-SSH hangs forever while Setting Up SSH Tunnel

### ISSUE THREAD

**Issue by pliantenergy** [microsoft/vscode-remote-release#956]
Issue Type: <b>Bug</b>

I'm trying to edit files on an Ubuntu 16.04 machine on my local network using VS Code on Windows 10, and I can't seem to get it to work.

Seems similar to [Issue #580](https://github.com/microsoft/vscode-remote-release/issues/580) but the setting of `remote.SSH.showLoginTerminal` does not affect the results.

## Expected behavior: 
 * Install Remote-SSH extension (via extension pack)
 * Set up SSH keys and SSH config file on Windows 10 machine
 * Add public key to `/home/<REMOTE-USERNAME>/.ssh/authorized_keys` on remote Linux machine
 * Enable `ssh-agent` on local machine
 * use `ssh-add` to add password-protected private key identity to `ssh-agent`
 * Connect to remote machine from inside VS Code
 * Successfully edit files over SSH connection to Ubuntu 16.04 machine on local network (remote machine has internet connection as well)

## Actual behavior: 
 * Remote-SSH successfully gets past `Initializing VS Code Remote...`
 * Remote-SSH hangs indefinitely (5-10 minutes or more) at `Setting up SSH tunnel`
 * VS Code says `Opening remote...` in lower left hand corner forever.
 * `systemctl status sshd` on remote machine says that public key was accepted and session was opened

## Contents of `VSCode_SSH_config` file:

    # Read more about SSH config files: https://linux.die.net/man/5/ssh_config
    Host laptop-six
        Hostname 192.168.1.xxx
        User <REMOTE-USERNAME>
        Port <CUSTOMPORT>
        IdentityFile C:\Users\<REDACTED-USER>\.ssh\<REDACTED-PRIVATEKEY-FILENAME>

## Things I've Tried:
 * Configured `sshd` to use the default port 22 on the remote machine instead of `<CUSTOMPORT>`. Same result.
 * Added `AllowTcpForwarding yes` to `sshd_config` on the remote machine (& restarted `sshd` for all such changes)
 * Set `remote.SSH.showLoginTerminal` to `true` to always reveal the login terminal (flashes briefly and disappears, connection appears successful, `false` gives same result)
 * Tested general SSH connectivity - ordinary SSH logins from the command line in the Windows command prompt and powershell work fine. With private key added to `ssh-agent` no password is needed.
 * Removed and reinstalled VS Code
 * Removed and reinstalled the remote development extensions
 * Manually killed vscode processes on remote server

## Remote-SSH output in VSCode:

    remote-ssh@0.44.0
    win32 x64
    SSH Resolver called for "ssh-remote+laptop-six", attempt 1
    SSH Resolver called for host: laptop-six
    Setting up SSH remote "laptop-six"
    Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for             server
    Testing ssh with ssh -V
    ssh exited with code: 0
    Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
    Using SSH config file "C:\Users\<REDACTED-USER>\.ssh\VSCode_SSH_config"
    Install and start server if needed
    > 
    > The system cannot find the path specified.
    > 
    > 
    > *
    > * Reminder: You may only use this software with Visual Studio family products,
    > * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
    > *
    > 
    > Checking server status with wget
    > fe9aff15-4c3f-4713-87de-d41eb84d5c4f==44352==42294==
    > 
    "install" terminal command done
    Received install output: fe9aff15-4c3f-4713-87de-d41eb84d5c4f==44352==42294==
    Server is listening on port 44352
    Using SSH config file "C:\Users\<REDACTED-USER>\.ssh\VSCode_SSH_config"
    Spawning tunnel with: type "C:\Users\<REDACTED-USER>\AppData\Local\Temp\vscode-linux-multi-line-command-laptop-six-534336966.sh" | "ssh" -L 127.0.0.1:44352:127.0.0.1:44352  -F C:\Users\<REDACTED-USER>\.ssh\VSCode_SSH_config "laptop-six" bash
    > 
    > The system cannot find the path specified.

Extension version: 0.44.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-154-generic x86_64)
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1660 v4 @ 3.20GHz (16 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.92GB (119.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Mini-Web** [comment]
I'm not sure exactly why.
However, the terminal works normally after I delete some relatively large plugin that are not commonly used.

**Comment by pandyamitesh** [comment]
Please fix this. This is frustrating . For me it is working if I kill node process on remote server pkill node

**Comment by pliantenergy** [comment]
I am getting the same behavior trying to connect to a fresh installation of Ubuntu 18.04 as well

**Comment by pliantenergy** [comment]
It looks like Remote-SSH 0.4.1 adds a -ConnectTimeout=15 flag to the SSH tunnel setup command. 

After 1 minute and counting: 

![image](https://user-images.githubusercontent.com/48336556/61133882-503c0c00-a48c-11e9-89a8-bcd5b6b418ae.png)

**Comment by roblourens** [comment]
Is that the full log that you posted above? It almost looks like it's missing lines somehow. Also can you try again with 0.44.2? That ConnectTimeout flag did actually cause an issue due to an issue with windows SSH

**Comment by pliantenergy** [comment]
> Is that the full log that you posted above? It almost looks like it's missing lines somehow.

I clipped a lot of otherwise blank > lines. 

I'm still having the same problem with 0.44.2. Indefinite hang at the SSH tunnel step. No problem with ordinary SSH into the remote machine from the Windows Command Prompt or Powershell. 

Let me know if there's anything else I should check. 

Here's the whole log from the Remote-SSH "Output" pane, no editing:

    remote-ssh@0.44.2
    win32 x64
    SSH Resolver called for "ssh-remote+laptop-six", attempt 1
    SSH Resolver called for host: laptop-six
    Setting up SSH remote "laptop-six"
    Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
    Testing ssh with ssh -V
    ssh exited with code: 0
    Got stderr from ssh: OpenSSH_for_Windows_8.0p1, LibreSSL 2.6.5
    Using SSH config file "C:\Users\<USERNAME>\.ssh\VSCode_SSH_config"
    Running script with connection command: "ssh"  -o ClearAllForwardings=true   -F C:\Users\<USERNAME>\.ssh\VSCode_SSH_config "laptop-six" bash
    Install and start server if needed
    > 
    > The system cannot find the path specified.
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > *
    > * Reminder: You may only use this software with Visual Studio family products,
    > * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
    > *
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > Checking server status with wget
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > e3fc2ff2-a52b-4507-9add-894ac7fb41b3==46227==36663==
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    "install" terminal command done
    Received install output: e3fc2ff2-a52b-4507-9add-894ac7fb41b3==46227==36663==
    Server is listening on port 46227
    Using SSH config file "C:\Users\<USERNAME>\.ssh\VSCode_SSH_config"
    Running script with connection command: "ssh" -L 127.0.0.1:46227:127.0.0.1:46227    -F C:\Users\<USERNAME>\.ssh\VSCode_SSH_config "laptop-six" bash
    Spawning tunnel with: type "C:\Users\<USERNAME>\AppData\Local\Temp\vscode-linux-multi-line-command-laptop-six-516320611.sh" | "ssh" -L 127.0.0.1:46227:127.0.0.1:46227    -F C:\Users\<USERNAME>\.ssh\VSCode_SSH_config "laptop-six" bash
    > 
    > The system cannot find the path specified.
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    >

**Comment by pliantenergy** [comment]
I have resolved this on my machine.

I tried the connection on another machine, same version of Windows 10, VS Code, and Remote-SSH extensions, and it worked fine.

The only perceptible difference was that a fresh command prompt on the problematic machine prints `The system cannot find the path specified` right after the Windows version and copyright notice. This is clear in the logs I posted earlier.

Long story why I looked for it, but I found a broken `AutoRun` registry entry added by [Anaconda](https://www.anaconda.com/distribution/) in `HKEY_CURRENT_USER\Software\Microsoft\Command Processor`

Modifying it to point correctly to the working Anaconda installation cleared the `cannot find the path specified` error and fixed Remote-SSH. Subsequently deleting the registry entry left everything in working order.

I never tried to seriously track down this constant `system cannot find the path` issue because it was just an annoyance. But somehow it seems that invoking this missing Anaconda batch file at the tunnel step was clogging up the works. 

I reproduced the problem starting with a custom batch file that prints this: 

![image](https://user-images.githubusercontent.com/48336556/61413817-79103700-a8ba-11e9-80e8-7fe477ce7789.png)

The batch file is at `C:\Users\<USERNAME>\testfolder\custom.bat`. To get the failed behavior below, I mangled the name of `testfolder`. Mangling only the .bat file name but having it in a valid directory gives a much more helpful error message with a full path.

Don't know why this would affect the SSH tunnel step and not the other earlier steps, but it seems to.

Logs below.

### Resulting log when the `AutoRun` key's value is a fully valid path to my custom .bat file:

    remote-ssh@0.44.2
    win32 x64
    SSH Resolver called for "ssh-remote+laptop-six", attempt 1
    SSH Resolver called for host: laptop-six
    Setting up SSH remote "laptop-six"
    Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
    Testing ssh with ssh -V
    ssh exited with code: 0
    Got stderr from ssh: OpenSSH_for_Windows_8.0p1, LibreSSL 2.6.5
    Using SSH config file "C:\Users\<USERNAME>\.ssh\VSCode_SSH_config"
    Running script with connection command: "ssh"  -o ClearAllForwardings=true   -F C:\Users\<USERNAME>\.ssh\VSCode_SSH_config "laptop-six" bash
    Install and start server if needed
    > 
    > ................................................................................
    > ..
    > This is a custom batch file to test my Remote-SSH hanging issue.
    > Every new command terminal will show this, since it's an AutoRun REG_SZ
    > entry under HKEY_CURRENT_USER\Software\Microsoft\Command Processor
    > ................................................................................
    > ..
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > Running remote connection script
    > Found existing installation at /home/<USER>/.vscode-server/bin/2213894ea0415ee8c
    > 85c5eea0d0ff81ecc191529...
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > Found running server...
    > 
    > *
    > * Reminder: You may only use this software with Visual Studio family products,
    > * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
    > *
    > 
    > Checking server status with wget
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 2f307acc-023a-4cf9-9a38-02c7e9419b3c==43589==33259==
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    "install" terminal command done
    Received install output: 2f307acc-023a-4cf9-9a38-02c7e9419b3c==43589==33259==
    Server is listening on port 43589
    Using SSH config file "C:\Users\<USERNAME>\.ssh\VSCode_SSH_config"
    Running script with connection command: "ssh" -L 127.0.0.1:43589:127.0.0.1:43589    -F C:\Users\<USERNAME>\.ssh\VSCode_SSH_config "laptop-six" bash
    Spawning tunnel with: type "C:\Users\<DOSUSERNAME>\AppData\Local\Temp\vscode-linux-multi-line-command-laptop-six-861942406.sh" | "ssh" -L 127.0.0.1:43589:127.0.0.1:43589    -F C:\Users\<USERNAME>\.ssh\VSCode_SSH_config "laptop-six" bash
    > 
    > ................................................................................
    > ..
    > This is a custom batch file to test my Remote-SSH hanging issue.
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > ..
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > Connected to SSH Host - Please do not close this terminal
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    Spawned SSH tunnel between local port 43589 and remote port 43589
    Waiting for ssh tunnel to be ready
    Tunneling remote port 43589 to local port 43589
    Resolved "ssh-remote+laptop-six" to "127.0.0.1:43589"
    ------

### Resulting log with invalid folder, Remote-SSH hangs

    remote-ssh@0.44.2
    win32 x64
    SSH Resolver called for "ssh-remote+laptop-six", attempt 1
    SSH Resolver called for host: laptop-six
    Setting up SSH remote "laptop-six"
    Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
    Testing ssh with ssh -V
    ssh exited with code: 0
    Got stderr from ssh: OpenSSH_for_Windows_8.0p1, LibreSSL 2.6.5
    Using SSH config file "C:\Users\<USERNAME>\.ssh\VSCode_SSH_config"
    Running script with connection command: "ssh"  -o ClearAllForwardings=true   -F C:\Users\<USERNAME>\.ssh\VSCode_SSH_config "laptop-six" bash
    Install and start server if needed
    > 
    > The system cannot find the path specified.
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > *
    > * Reminder: You may only use this software with Visual Studio family products,
    > * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
    > *
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > Checking server status with wget
    > 5195c6cf-4c9f-4c11-8e77-f93bbb6fb9fb==43589==33259==
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    "install" terminal command done
    Received install output: 5195c6cf-4c9f-4c11-8e77-f93bbb6fb9fb==43589==33259==
    Server is listening on port 43589
    Using SSH config file "C:\Users\<USERNAME>\.ssh\VSCode_SSH_config"
    Running script with connection command: "ssh" -L 127.0.0.1:43589:127.0.0.1:43589    -F C:\Users\<USERNAME>\.ssh\VSCode_SSH_config "laptop-six" bash
    Spawning tunnel with: type "C:\Users\<DOSUSERNAME>\AppData\Local\Temp\vscode-linux-multi-line-command-laptop-six-408072080.sh" | "ssh" -L 127.0.0.1:43589:127.0.0.1:43589    -F C:\Users\<USERNAME>\.ssh\VSCode_SSH_config "laptop-six" bash
    > 
    > The system cannot find the path specified.
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
![image](https://user-images.githubusercontent.com/48336556/61414405-d1940400-a8bb-11e9-9ec2-3aaccf4674f8.png)

**Comment by roblourens** [comment]
Huh, that's interesting. Good catch! I have no idea why it's making the process hang but clearly it's not executing ssh and I don't think there's anything I can do to improve that.
