### ISSUE TITLE
Remote-SSH extention is unusable. "missing value for match criteria ###"

### ISSUE THREAD

**Issue by ba-T-ch** [microsoft/vscode-remote-release#9561]
Type: <b>Bug</b>

The saved list of SSH connections does not show any of the previous connections anymore.

Attempting to add a host in the extension results in an error message.
(first prompt ask for command, then for save location)

```
Command 'Remote-SSH: Add New SSH Host...' resulted in an error
missing value for match criteria ###
```

Same for other commands, but these do not even show any prompt before failing.
- Command 'Remote-SSH: Kill Local Connection Server For Host...' resulted in an error
- Command 'Remote-SSH: Kill VS Code Server on Host...' resulted in an error

No logs or message are stored in Developer Tools' console.

Reverting extension to 0.107.0 resolves the issue. Remote explorer shows old connections, and all commands work.

Extension version: 0.108.0
VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:42:12.210Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 8, 8|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by harnamc** [comment]
Reverting the `Remote - SSH` extension to `v0.107.1` did resolved the issue. VS Code will bring up the prompt `You are about to connect to an OS version that is unsupported by Visual Studio Code.` Click `Allow` and it will connect and show a banner saying `You are connected to an OD version that is unsupported by Visual Studio Code.`

To installs an older version of `Remote - SSH`

* Open the `Extensions` page in VS Code.
* Search for `@installed Remote - SSH` and click on `Remote - SSH` extension.
* Click the down arrow next to the `Uninstall` button and select `Install Another Version`.
![image](https://github.com/microsoft/vscode-remote-release/assets/13107749/70c9f63b-a99f-40c3-8246-b4e80a9fcbee)
* Select `v0.107.1` from the dropdown.

**Comment by Ramneek-kalra** [comment]
Did work for me! Thanks @harnamc !

**Comment by bamurtaugh** [comment]
@isidorn sounds like this is related to the new minimum supported OS, but wanted to cc in case you thought otherwise.

**Comment by isidorn** [comment]
This should just work with latest VS Code and SSH extension. Thus closing.
If someone can reproduce with latest VS Code and SSH extension do let us know and we can reopen. Thank you 🙏

**Comment by JustusAdam** [comment]
I still get the exact same error with the new version (of vscode and this extension). I am connecting to an OS that is technically unsupported by the newer vscode, however I am not in a position to update that OS. The newer editor version also seems to work fine so long as I use the older remove-ssh extension

**Comment by andrross** [comment]
I got the same error here using the latest version of both vscode and this extension. I'm also connecting to an OS with an unsupported version of glibc. I had to revert back to VS Code 1.87.2 and Remote SSH 0.107.1 to get things working again.

**Comment by nshahquinn** [comment]
I had the exact same issue with VS Code 1.88.1 (on macOS 14.4.1) and the latest version of the Remote - SSH extension. Downgrading to v0.107.1 of the extension fixed it (I didn't have to downgrade VS Code).
