### ISSUE TITLE
When VScode is closed while connecting, an empty wget.log file is create in /

### ISSUE THREAD

**Issue by casperklein** [microsoft/vscode-remote-release#9565]
Type: <b>Bug</b>

I've different folders/projects on a remote machine that I access via the Remote-SSH extension. I noticed, that if I close VScode or abort the connection while connecting, sometimes (depends on the timing) an empty wget log file is create at `/wget.log`. If that is repeated, additional files are created:

```
# ls -l /wget-log*
-rw-r--r-- 1 root root 0 Feb 18 13:02 /wget-log
-rw-r--r-- 1 root root 0 Feb 18 13:02 /wget-log.1
-rw-r--r-- 1 root root 0 Feb 18 13:02 /wget-log.2
````

For clarification: I abort the connection, when I've accidentally chosen the wrong remote folder/project.

Extension version: 0.108.0
VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 6.1.0-18-amd64

**Comment by joshspicer** [comment]
Thanks for taking the time to open an issue.  I don't think this should reproduce anymore - if you see it again, please feel free to re-open (and please attach your logs!)

**Comment by casperklein** [comment]
This is still an issue with the current version:

Version: 1.96.0 (user setup)
Commit: 138f619c86f1199955d53b4166bef66ef252935c
Date: 2024-12-11T02:29:09.626Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045

If I can provide additional information/logs, please let me know. I can reliable reproduce that issue.

**Comment by joshspicer** [comment]
`> Remote-SSH: Show Log` in the command palette after reproducing the issue would be helpful to see.  Also please share with me the output of `wget --version` on your remote machine.  What is the contents of wget log?
