### ISSUE TITLE
VS Code Settings not taken over from metadata in image label

### ISSUE THREAD

**Issue by rjaegers** [microsoft/vscode-remote-release#9571]
According to the [Dev Container specification](https://containers.dev/implementors/reference/#labels) it is possible to attach metadata to image labels. This seems to work for most, if not all, options except for [`customizations.vscode.settings`](https://containers.dev/supporting#visual-studio-code). None of the settings specified are taken over in the actual running container instance.

- VSCode Version: 1.86.2
- Dev Containers Version: 0.338.1
- Local OS Version: Windows 10 22H2 (19045.3930)
- Remote OS Version: Docker Desktop using WSL2 with a Ubuntu 22.04 base container
- Remote Extension/Connection Type: Containers
- Logs: Please see reproduction scenario as it is 100% reproducible

Steps to Reproduce:

1. Start a Dev Container with `ghcr.io/philips-software/amp-devcontainer-vscode` as `image`.
2. Observe that none of the settings specified in https://github.com/philips-software/amp-devcontainer/blob/main/.devcontainer/devcontainer-metadata-vscode.json are taken over.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: I have removed all but the Dev Containers extension and cleaned my user `settings.json`. I also tried the pre-release version of the extension but the problem persists.

There is some mention on [StackOverflow](https://stackoverflow.com/questions/76269100/force-vs-code-devcontainer-settings-to-override-user-settings) of similar behavior (see issue comment).

**Comment by chrmarti** [comment]
https://github.com/philips-software/amp-devcontainer/blob/main/.devcontainer/devcontainer-metadata-vscode.json shows the settings property under customizations. It needs to go under the vscode property like the extensions.

**Comment by rjaegers** [comment]
🤦🏻‍♂️ Ooof... that was not my brightest moment. Typically, I am at the other side of these kind of issues, very humbling.

Anyway, this indeed fixes the issue! My sincerest apologies for taking up your time.
