### ISSUE TITLE
Connecting to shared home directory mapped to multiple machines doesn't work

### ISSUE THREAD

**Issue by m-manohar** [microsoft/vscode-remote-release#958]
- VSCode Version: Latest Insiders
- Local OS Version:MacOS
- Remote OS Version:Debian Linux
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
Two remote servers: server1 and server2 with a shared home directory 
1. remote connect to server1. Things are working now
2. remote connect to server2. The connection to server1 is gone now

Looks the remote connection to server2 clobbers some information that was cached for server1 in the home directory. Now even if the connection to server2 is disconnected, a connection to server1 cannot be made

**Comment by roblourens** [comment]
What error messages do you see?

Can you share the Remote-SSH output channel log from each vscode instance?

**Comment by m-manohar** [comment]
Connecting to the first host that shares a common home directory

```
"tetra-01" bash << 'EOSSH'
echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity
EOSSH
> Connected to SSH Host - Please do not close this terminal
Spawned SSH tunnel between local port 40267 and remote port 40267
Waiting for ssh tunnel to be ready
Tunneling remote port 40267 to local port 40267
Resolved "ssh-remote+tetra-01" to "127.0.0.1:40267"
------
```

Now connecting to a second server that shares the same home directory... This message keeps cycling and everytime closes the log and reopens and tries many times before timing out
```
Running remote connection script
Found existing installation at /home/mmanohar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529...
Found running server...
 
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
*
 
Checking server status with wget

5302fbc6-e6d2-43f5-904d-d3c6acb85c04##28##
```

**Comment by roblourens** [comment]
Ok, I see the problem. This will not work, because the server processes on different machines will overwrite each others' log files. I have to call this a feature request.

**Comment by roblourens** [comment]
You might be able to get it to work by replacing the log file with a symlink to another location which is not shared. e.g. linking `~/.vscode-server/.2213894ea0415ee8c85c5eea0d0ff81ecc191529.log` to something in `/tmp` or something. But I have not tested that.

**Comment by roblourens** [comment]
Maybe we should include the machine's name in the log file path, like just from `hostname`

**Comment by m-manohar** [comment]
> You might be able to get it to work by replacing the log file with a symlink to another location which is not shared. e.g. linking `~/.vscode-server/.2213894ea0415ee8c85c5eea0d0ff81ecc191529.log` to something in `/tmp` or something. But I have not tested that.

I just tried that and yes that works wonderfully!
