### ISSUE TITLE
Do we have a deterministic solution to #6080?

### ISSUE THREAD

**Issue by arghhjayy** [microsoft/vscode-remote-release#9585]
I am currently having the same issue with my dev container. Last comment on that issue is from @chrmarti saying it's only a guess.

**Comment by arghhjayy** [comment]
Just an fyi: a reboot does fix it

**Comment by chrmarti** [comment]
What OS and Docker version are you using? This seems out-of-scope for Dev Containers as we depend on Docker for the mount points.

**Comment by arghhjayy** [comment]
Windows 11, Docker Desktop 4.27.2 (137060)

**Comment by chrmarti** [comment]
Reopening the original issue in favor of this one, thanks.

**Comment by arghhjayy** [comment]
@chrmarti: I've opened an issue regarding this with the Docker for Windows issue page here: https://github.com/docker/for-win/issues/13936
