### ISSUE TITLE
Dev Containers (RG) crawls all local files as soon as enabled - excessive CPU load

### ISSUE THREAD

**Issue by spacerunner5** [microsoft/vscode-remote-release#9586]
As soon as enabled, the Dev Containers extension starts to crawl all subfolders of the current opened folder. This results in an excessive CPU usage.

No other extensions enabled.

Example on MacOS: Opening the root folder (MacHD) causes Dev Containers to crawl absolutely everything, even including mounted network shares. Identified on the Mac by looking at the **rg processes** launched after enabling Dev Container. Looking at the open files of the process, the crawling can be seen.

There are some reports around here and in other places stating that the Remote Development extension pack causes high CPU usage when enabled. This might be the cause. Disabling Dev Containers fixes the issue immediately after reload.

--

what did **not** help:

- Dev Containers has the option of adding a "List of additional paths to search for repository configurations". Adding an entry there did however not change the behaviour. 
- Adding excludes to search didn't help.
- Adding excludes to the watcher didn't help.

Any ideas?

I'm happy to provide more information.

--

- VSCode Version: 1.86.2
- Local OS Version: MacOS 13.6.4
- Remote OS Version: not relevant
- Remote Extension/Connection Type: Dev Container

**Comment by adlzanchetta** [comment]
I am facing the exact same issue in Linux (Ubuntu 22.04), same VSCode version (1.86.2).

Every time I start a Dev Container session my CPU usage goes to maximum. I have to open the terminal with an user with sudo powers, run the command ```top```, get the PID of the **two** ```rg``` processes and ```kill``` them.

Killing these processes does not affect VSCode at all.

**Comment by chrmarti** [comment]
Fixing this in https://github.com/microsoft/vscode-remote-release/issues/9738
