### ISSUE TITLE
Option to work/attach multiple folders in one Container. Like version 0.292 and older

### ISSUE THREAD

**Issue by tanquetela** [microsoft/vscode-remote-release#9588]
In previous versions, you could open multiple folders/paths in one container with a right click and "attach in new windows," then select the two sheets icon in the vertical left menu and choose the "Open folder" and a new folder. Then, multiple folders will be available to open in one container. In the latest versions, this version doesn't work anymore. You can only choose one folder from a container, and it will always open that folder. 
We use one dev container for multiple Ruby projects, and we love this option because we can work with all the apps by choosing them from the list (screenshot). But now it is like we need one container per project/folder to open the container.
Please fix this; in previous versions like 0.292, this worked perfectly, but now it is not working, and older versions have started having issues working with newer versions of VS code.

<img width="631" alt="Screenshot 2024-02-25 at 03 28 21" src="https://github.com/microsoft/vscode-remote-release/assets/103223870/561c8cd8-7cd3-4aae-85d9-ad9d4583f68c">

**Comment by chrmarti** [comment]
You can again open specific folders from the Remote Explorer.
