### ISSUE TITLE
remote-ssh broke ssh connections?

### ISSUE THREAD

**Issue by light8lee** [microsoft/vscode-remote-release#959]
- VSCode Version: 1.36.1
- Local OS Version: Ubuntu 18.04.2 LTS / Windows 10
- Remote OS Version: Ubuntu 16.04.5 LTS 
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. open vscode 
2. Remote-SSH: Connect to Host
3. Setting up to SSH Host
4. getting errors:
```
remote-ssh@0.44.0
linux x64
SSH Resolver called for "ssh-remote+s112", attempt 1
SSH Resolver called for host: s112
Setting up SSH remote "s112"
Using commit id "zzzzzzzzzzzzzzzz" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
Install and start server if needed
> ssh: connect to host xxx.xxx.xxx.xxx port 60000: Connection timed out
"install" terminal command done
Received install output: ssh: connect to host xxx.xxx.xxx.xxx port 60000: Connection timed out
The connection timed out
```

And after the remote ssh connection failed, the ssh to the host is also failed. The same issue occurred with my colleague in the same host. Both him and I can not establish the ssh in this host, but the others can access normally, my local os is ubuntu, his Windows 10.

I also tried kill the vscode process in remote host, but it's not worked.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
> `Connection timed out`

Are you sure that your remote is reachable?

**Comment by light8lee** [comment]
yes, I'm sure

**Comment by roblourens** [comment]
This failed at the very first step so I'm not sure what the problem would be. What do you get if you run `ssh s112 uname` in a local terminal?

**Comment by light8lee** [comment]
it just makes me waiting

**Comment by roblourens** [comment]
Ok, it sounds like there is just some issue with that host and you can't connect to it.

**Comment by light8lee** [comment]
I argree with you.
