### ISSUE TITLE
"runArgs": ["--env-file",".devcontainer/devcontainer.env"] not updating Environment Variables  on container start

### ISSUE THREAD

**Issue by thoughtfuldata** [microsoft/vscode-remote-release#9591]
If I update the environment variables in the .env file, they aren't updated the next time I restart the container. I have to rebuild the container for the environment variables to be updated.

Version: 1.86.2 (user setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

- REMOTE OS
Distributor ID: Ubuntu
Description:    Ubuntu 23.10
Release:        23.10

- Remote Extension/Connection Type: Dev Containers/WSL

CONTAINER OS: DEBIAN

Does this issue occur when you try this locally?: Yes

**Comment by chrmarti** [comment]
This behavior is given by Docker and not under the control of Dev Containers.
