### ISSUE TITLE
Allow vscode-server not to be installed

### ISSUE THREAD

**Issue by 117503445** [microsoft/vscode-remote-release#9595]
When many systems cannot meet the installation requirements of vscode-remote, such as Alpine and older versions of CentOS, I hope that even when the remote system does not support the installation of `vscode-remote`, I can still connect to the remote system, browse and edit files, albeit without the ability to use plugins.

**Comment by isidorn** [comment]
What is the actual feature request here? Can you please clarify.

**Comment by 117503445** [comment]
Using VSCode Remote now requires `vscode-server` to be installed on the server. I'd like VSCode Remote to work without `vscode-server`, even if it's just ssh to get basic functionality.

I have this requirement because `vscode-server` cannot be installed on older systems, causing VSCode Remote to fail. In this case, I want VSCode to support the fallback scheme, which is to provide remote file viewing and editing via SSH only.

Translated with DeepL.com (free version)

**Comment by isidorn** [comment]
This is a fair request, but not something we have on the plan.
I can keep this issue open to gather more user feedback. Thanks
