### ISSUE TITLE
ControlMaster is not supported on Windows - find a workaround or document it

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#96]
https://code.visualstudio.com/docs/remote/troubleshooting#_enabling-alternate-ssh-authentication-methods

This feature is not supported on Windows. I don't think there's really a way around it, so we should indicate this in the docs.

**Comment by lars18th** [comment]
Hi,

And any other option for sharing SSH connections?

**Comment by roblourens** [comment]
Not that I'm aware of.

**Comment by davidwin** [comment]
While I think that ssh for Windows _should_ be able to support `ControlMaster` with UNIX domain sockets being available for Windows 10 and all, it would be great if the extension could "trampoline" through ssh for WSL (which does support connection sharing). I do that a lot for e.g. Tasks and launching gdb. It could be as simple as a setting that allowed you to customize the ssh command, so one could specify `wsl.exe ssh` instead.

**Comment by lars18th** [comment]
Hi @davidwin ,

I don't like to idea of leave the support of `ControlMaster` in WSL because:
- This is restricted to last versions of Windows 10.
- This doesn't work if you don't have WSL installed.

Please don't get me wrong. I love WSL, but I use other Windows versions without WSL.

**Comment by davidwin** [comment]
Well, it's a workaround. I think the possibility of specifying the ssh path (including any extra arguments) is generally useful though, whether it's used to get `ControlMaster` support before anyone implements it natively for all Windows versions or not.

**Comment by lars18th** [comment]
> Well, it's a workaround. 

I agree, yes it is! 😉

**Comment by oxo42** [comment]
How can I tell vscode to use my `ssh.cmd` file that actually calls WSL in the background?

My organisation uses 2fac for SSH login so I can't use this extension on my Windows laptop

**Comment by roblourens** [comment]
> My organisation uses 2fac for SSH login so I can't use this extension on my Windows laptop

It should work with 2fa as long as you set `remote.SSH.showLoginTerminal`

**Comment by MattWThomas** [comment]
Is there any other way to solve the issue of [connecting to systems that dynamically assign machines per connection](//code.visualstudio.com/docs/remote/troubleshooting#_troubleshooting-hanging-or-failing-connections)? I cannot use `ControlMaster` as suggested because of this issue. The help file at that link seems to imply that there are other solutions to the problem.

I'm connecting to a compute cluster which dynamically assigns logins to different nodes.

**Comment by roblourens** [comment]
You can hardcode an IP address of a specific machine that you want, that's the only other workaround I can think of unfortunately.

**Comment by josh-gray** [comment]
Was remoting into a high-performance research cluster experiencing the same problem as @MattWThomas. Hardcoding one of the login node IPs worked for me!

**Comment by AceFire2014** [comment]
OK, thanks a lot!

Sincerely,
Andy

**Comment by roblourens** [comment]
Investigated this during July. We could run a server on the client to manage a connection to the host which will be shared by all windows. That way, opening a new window on the same host will not require any password entry.

**Comment by wmertens** [comment]
the limitation is purely software, right? How about using the ssh2 npm package as a secondary connection option? I know you switched to the real client because of some missing authentication features, but apparently the missing features go both ways…

**Comment by roblourens** [comment]
ssh2 doesn't solve this problem, we would still require a password entry per window. Reopening this because I'm still actively working on it, and it's on the iteration plan.

**Comment by roblourens** [comment]
I am calling this "experimental" but now you can try it by setting `"remote.SSH.useLocalServer": true`.
