### ISSUE TITLE
Trying wrong user

### ISSUE THREAD

**Issue by oliverolmos** [microsoft/vscode-remote-release#960]
Issue Type: <b>Bug</b>

I created a SSH config file as follows:
Host 10.220.0.184
HostName nodejs
User root

But then it prompts for the password for this user:
←[0m←[OKroot@nodejs

Then it asks for the password again. Then it won't authenticate. 

It throws the error: "Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.)"

Extension version: 0.44.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
You can ignore the user name issue, it's just failing to remove some terminal escape codes. The real issue is https://github.com/microsoft/vscode-remote-release/issues/103

Please see https://code.visualstudio.com/docs/remote/linux and check that your remote meets the minimum requirements for linux.

**Comment by roblourens** [comment]
I have fixed the escape codes on the user name though, thanks
