### ISSUE TITLE
The system cannot find the path specified after reboot

### ISSUE THREAD

**Issue by futscdav** [microsoft/vscode-remote-release#961]
- VSCode Version: 1.36. 1
- Local OS Version: Windows 10 Pro 1803
- Remote OS Version: Ubuntu 18.10
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
Unknown

Does this issue occur when you try this locally?: Seems to be a local issue
Does this issue occur when you try this locally and all extensions are disabled?: Yes

After successfully using Remote-SSH (/nightly) for the first time and rebooting the local system (ungracefully), there seems to be an issue with paths. I'm unable to track down specifically what this issue is and reinstalling the extension does not resolve the issue. ssh and ssh-agent is on the path and working.

The output is:
```
remote-ssh-nightly@2019.7.12420
win32 x64
SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a223134372e33322e38312e313533222c2275736572223a226675747363646176227d", attempt 1
SSH Resolver called for host: *****
Setting up SSH remote "me@remote ip"
Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4
Install and start server if needed
> 
> The system cannot find the path specified.
> The process tried to write to a nonexistent pipe.
> 
"install" terminal command done
Received install output: The process tried to write to a nonexistent pipe.
The process tried to write to a nonexistent pipe
------
```

I'm not sure how to start fixing this issue without knowing which executable the extension is looking for.

**Comment by futscdav** [comment]
Turns out there was google depot_tools/ssh.bat on the path before OpenSSH/ssh.exe and the extension picked the bat version over looking for exe. This absolutely broke the functionality. Perhaps something to look into or at least give some diagnostic info when it goes wrong. You can close this if you don't see this as an issue.

**Comment by ostanislaw** [comment]
I see the same today on stable remote-ssh 0.44.1, and after downgrading to 0.44.0 it connects properly
remote-ssh@0.44.1
win32 x64
SSH Resolver called for "ssh-remote+ltp_ssh_container", attempt 1
SSH Resolver called for host: ltp_ssh_container
Setting up SSH remote "ltp_ssh_container"
Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
Install and start server if needed
> 
> write: Connection refused
> The process tried to write to a nonexistent pipe.
> 
"install" terminal command done
Received install output: The process tried to write to a nonexistent pipe.
The process tried to write to a nonexistent pipe

**Comment by AndrewMSHowe** [comment]
> I see the same today on stable remote-ssh 0.44.1, and after downgrading to 0.44.0 it connects properly

Oh you absolute BEAUTY, this has been fully DOING MY HEAD IN for the last hour or so. The bloody thing worked yesterday, and something broke it... I tried everything I could think of but nothing worked. 0.44.0 works, nice one. Hey Microsoft, you broke something in 0.44.1!

**Comment by hermeton** [comment]
Also cant access remote host anymore.
- Connecting from: Windows 10 Home
- VS Code: 1.36.1
- Remote host: Ubuntu 18.04.2 @ VirtualBox

Regular SSH connection from cmd works as expected.

```
remote-ssh@0.44.1
win32 x64
SSH Resolver called for "ssh-remote+ubuntu", attempt 1
SSH Resolver called for host: ubuntu
Setting up SSH remote "ubuntu"
Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
Install and start server if needed
> 
> ]0;C:\Windows\SYSTEM32\cmd.exe
>
> write: Connection refused
> 
> The process tried to write to a nonexistent pipe.
> 
"install" terminal command done
Received install output: The process tried to write to a nonexistent pipe.
The process tried to write to a nonexistent pipe
------
```

**Comment by roblourens** [comment]
> Turns out there was google depot_tools/ssh.bat on the path before OpenSSH/ssh.exe and the extension picked the bat version over looking for exe. This absolutely broke the functionality. Perhaps something to look into or at least give some diagnostic info when it goes wrong. You can close this if you don't see this as an issue.

What does ssh.bat do? Since `ssh -V` prints out the real ssh version message I assume it is invoking ssh correctly.

**Comment by ostanislaw** [comment]
remote-ssh 0.44.2 issue fixed for me
