### ISSUE TITLE
Problem building dockerfile-with-features 

### ISSUE THREAD

**Issue by jmls** [microsoft/vscode-remote-release#9610]
type: bug

```
[2024-02-28T16:38:36.460Z] Dockerfile.extended:1
--------------------
   1 | >>> # syntax=docker/dockerfile:1.4
   2 |     ARG _DEV_CONTAINERS_BASE_IMAGE=placeholder
   3 |     
--------------------
ERROR: failed to solve: unlazy requires an applier

```
the error seems to be whenever I try and add a feature to the devcontainer.json  file (doesn't matter which feature)

This is similar to #8202

this is the devcontainer.json file

```
{
	"name": "my-test",
	"image": "mcr.microsoft.com/devcontainers/base:dev-ubuntu-22.04",
	"features": {
		"ghcr.io/devcontainers/features/node:1": {}
	}
}

```
I am running 

docker version
Client: Docker Engine - Community
 Cloud integration: v1.0.24
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:09 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:13:09 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  
  vscode 1.82
  
  ms-vscode-remote.remote-containers: 
  Last released 2024-02-28, 09:16:45
  Last updated 2024-02-28, 16:21:49

**Comment by chrmarti** [comment]
Does using `1.4.0` as the version number help? (https://github.com/microsoft/vscode-remote-release/issues/8202#issuecomment-1503264778)

**Comment by jmls** [comment]
I removed all images, all containers, all volumes. I also removed docker. 

then rebooted, re-installed, and things are now working  - so I actually don't know what the problem was, sorry.

**Comment by chrmarti** [comment]
Thanks, closing for now.
