### ISSUE TITLE
Remote Tunnels do not detect when multiple Microsoft Accounts are Present

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-remote-release#9612]
- VSCode Version: 1.87.0 (tested on insiders too)
- Local OS Version: Win11
- Remote OS Version: Win Server 2019 (Irrelevant)
- Remote Extension/Connection Type: Dev Tunnel

- Logs: None observed in `Remote - Tunnels` output window

Steps to Reproduce:

1. Sign into a MS account
2. Sign into another MS account
![image](https://github.com/microsoft/vscode-remote-release/assets/15258962/eb87c2f3-ce89-48d6-a803-f360aa8a550f)
4. Attempt to connect to tunnel
5. Choose "Microsoft"
6. Tunnel is not present
![image](https://github.com/microsoft/vscode-remote-release/assets/15258962/c99767d4-4146-4093-9548-a1a72dc8c13c)
7. "Sign into tunnel with a different account" does nothing
![image](https://github.com/microsoft/vscode-remote-release/assets/15258962/83979575-f805-4a78-9974-17c6a9dfa7a3)

**Comment by connor4312** [comment]
There is now a new option

![image](https://github.com/microsoft/vscode-remote-release/assets/2230985/d9e6b4f4-316d-467e-a2e2-9d1532a8e35f)

**Comment by JustinGrote** [comment]
I'll give it a go on insiders tomorrow, thanks!

**Comment by goldwater668** [comment]
Connected to an existing tunnel process running on this machine. You can press:

- "x" + Enter to stop the tunnel and exit
- "r" + Enter to restart the tunnel
- Ctrl+C to detach
There is already a remote tunnel established by others. How should I operate it? The official meaning is that a remote tunnel can only be used by one github account.
