### ISSUE TITLE
[Remote-SSH Bug]: check-requirements.sh: line 53: /sbin/ldconfig: Permission denied

### ISSUE THREAD

**Issue by silverasu** [microsoft/vscode-remote-release#9617]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### ->

check-requirements.sh: line 53: /sbin/ldconfig: Permission denied

### Steps To Reproduce

Our remote server has /sbin/ldconfig chmod 700 with root:root

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
.../bin/helpers/check-requirements.sh: line 53: /sbin/ldconfig: Permission denied
```

</p>
</details>

### Anything else?

It worked before last update.

**Comment by connor4312** [comment]
I think the recommendation here is just to tweak the permissions on ldconfig.
