### ISSUE TITLE
how to bump ssh-config ? Failed to connect to the remote extension host server (Error: Missing value for match criteria host=*.toto.net)`

### ISSUE THREAD

**Issue by teto** [microsoft/vscode-remote-release#9618]
I am running `v0.109.2024022215 (pre-release)` on nixos
with a ssh config that looks like
```
Match host=azure1-runner.toto.net,azure1
  Port 12666
  IdentitiesOnly yes
  HostName zaz.net
  IdentityFile /home/teto/.ssh/nova_key
  userKnownHostsFile /nix/store/58ah3glg4zdina7if8darhp1vyiqh2yd-source/configs/prod/ssh_known_hosts
```
and I get
`Failed to connect to the remote extension host server (Error: Missing value for match criteria host=*.toto.net)`
Seems like a fix exists in https://github.com/cyjake/ssh-config/issues/74 and was released in 
https://github.com/cyjake/ssh-config/commit/162eaa36ad7a0ffce0a463322e50a1633f9bd478

Is it possible to  bump the ssh-config dependency ? How one can do it ?

**Comment by roblourens** [comment]
Will do this in https://github.com/microsoft/vscode-remote-release/issues/9683, thanks for the reminder
