### ISSUE TITLE
Allow for default configurations of remote VSCode environments

### ISSUE THREAD

**Issue by nbgibson** [microsoft/vscode-remote-release#9624]
Simply put, it would be a nice QOL addition to be able to specify a given configuration of VSCode (a Profile if you wish) to be used by default when the remote env is being installed/configured on the target machine. This is likely achievable via Ansible and the like, but as VSC has to "install" to the target machine it would make a good bit of sense to have that be part of that process.

### Use case: 
Something as minimal as having a different theme for remote VSC windows than your own would allow for better at a glance awareness of what ENV you are currently working in. Specifying a profile or allotment of extensions would reduce overhead in bringing dev envs in ephemeral infrastructure up to par.

**Comment by bamurtaugh** [comment]
Thanks for filing! A couple thoughts:

- What is the current gap with using a Profile when connecting to a remote? (cc @isidorn for awareness)
- This could also be an opportunity to use a dev container - dev containers are compatible with other remote connection types (SSH, WSL, tunnels)
