### ISSUE TITLE
-bash: ./node: cannot execute: required file not found 

### ISSUE THREAD

**Issue by ericblade** [microsoft/vscode-remote-release#9636]
- VSCode Version: 
![image](https://github.com/microsoft/vscode-remote-release/assets/1451847/56b31f41-0735-40f3-90bb-e8666ed5de5b)

- Local OS Version:
![image](https://github.com/microsoft/vscode-remote-release/assets/1451847/1dc79365-e229-4fdf-93f2-6bf2dbe07d52)

- Remote OS Version: ```Linux MacPro 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 GNU/Linux```
- Remote Extension/Connection Type: WSL

- Logs:

Steps to Reproduce:

1. Attempt to load VSCode into the WSL instance

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

Attempting to run on a custom Linux WSL2 distribution, I get:

![image](https://github.com/microsoft/vscode-remote-release/assets/1451847/c4a76487-735f-4914-9dc4-68c4ee903086)

Opening a shell on said distribution, and running strace on the executeable in question gives me:

```bash
root@MacPro:~/.vscode-server/bin/019f4d1419fbc8219a181fab7892ebccf7ee29a2# strace /home/root/.vscode-server/bin/019f4d1419fbc8219a181fab7892ebccf7ee29a2/node
execve("/home/root/.vscode-server/bin/019f4d1419fbc8219a181fab7892ebccf7ee29a2/node", ["/home/root/.vscode-server/bin/01"...], 0x7ffe98658970 /* 29 vars */) = -1 ENOENT (No such file or directory)
strace: exec: No such file or directory
```

I don't know how to proceed further in diagnosis.

**Comment by aeschli** [comment]
So `/home/root/.vscode-server/bin/019f4d1419fbc8219a181fab7892ebccf7ee29a2/node` does not exist? Maybe the install got corrupted.
Close all VS Code WSL windows, delete `~/.vscode-server/bin` in a shell and restart VS Code.

**Comment by ericblade** [comment]
> So /home/root/.vscode-server/bin/019f4d1419fbc8219a181fab7892ebccf7ee29a2/node does not exist

Node is there, but it's complaining that something it needs is missing.  I've added ldd to the image, and it doesn't find anything incorrect there

```
root@MacPro:~/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6# ldd node
        linux-vdso.so.1 (0x00007fff8ab3e000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f0cc5782000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f0cc5528000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f0cc544a000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f0cc5425000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f0cc5420000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f0cc523f000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib/ld-linux-x86-64.so.2 (0x00007f0cc5793000)
```

IF that error message is correct "required file not found", then i'm guessing i'm missing some dependency that most distributions have .. but bash isn't even starting the binary, so i'm at a loss on how to diagnose what might be missing.  Usually ldd and strace are my tools for that.  

I think I may have just discovered potential source of problem -- i checked the binary in another distribution with the 'file' command, and got

```
node: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=de281e7ff9325415d50c87c4daccff1576e2fb18, with debug_info, not stripped
```
and the binary runs in the other distribution.  I do not have /lib64 in this distro, ld-linux-x86-64.so.2 is over in /usr/lib ...

ok, yeah, making a /lib64 dir and symlinking that file into it gets the vs code server running.  

I guess I'll just close this now, since it looks like having a /lib64 directory should be standard, and i'll get that added to the distro

**Comment by aeschli** [comment]
duplicated of https://github.com/microsoft/vscode-remote-release/issues/9838
