### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by jpnserame** [microsoft/vscode-remote-release#9638]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

Issue Summary
It seems like we're encountering an issue with our VS Code remote-ssh connections, leading to connectivity problems and SSH blocks on our server. Despite uninstalling extensions and ensuring no residual processes, there's a persistent number of connections when users connect, eventually causing disruptions.

Our dev server has 4GB RAM and 20GB NVME storage

Observations:
Even after uninstalling extensions and verifying no leftover processes, there's a problem that causes the server to be locked for SSH connections and requires us to reboot it.

The server isn't crashing outright but rather experiencing connectivity issues or blocks, as indicated by the lack of notifications from our 24X7 tool that can still run and communicate upon the SSH connection block.

Resource usage on the server appears within normal bounds during these spikes, suggesting a more nuanced issue.

screenshots of some dev server metrics from a "crash" a few days ago:

![cpu metrics](https://github.com/microsoft/vscode-remote-release/assets/10959399/471a52d9-e45b-4cc0-ae2a-6f0f94091fd5)

![memory metrics](https://github.com/microsoft/vscode-remote-release/assets/10959399/0cb0c3b7-b831-4b49-a1fb-b75abaf8ec39)

![network metrics](https://github.com/microsoft/vscode-remote-release/assets/10959399/2ece728f-f13f-40e9-ae4d-b2988c602b01)

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by guillemram97** [comment]
I have a similar issue on 1.85.2 and MacOS. My error code is:
```
Error running command remote-explorer.configureSsh: command 'opensshremotes.openConfigFile' not found. This is likely caused by the extension that contributes remote-explorer.configureSsh.
```
I also have 1.86 installed, and this does not seem to be an issue.

**Comment by david-torox** [comment]
i have similar problem, linux server(Ubuntu) and pc(win11)

**Comment by joshspicer** [comment]
Could you elaborate on what you mean by:

> there's a problem that causes the server to be locked for SSH connections and requires us to reboot it.

What does it mean for the server to be locked for SSH connections?

How did you determine these graphs are related to VS Code?
