### ISSUE TITLE
[Remote-SSH Bug]: Temporary files related to vscode-server are continuously generated until the disk space is exhausted

### ISSUE THREAD

**Issue by huhubun** [microsoft/vscode-remote-release#9648]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Don't fill up disk space

### Remote-SSH Log

Sorry, after the remote host disk space was exhausted, I closed the local vscode immediately, so I cannot provide Remote-SSH Log.

But I retained the logs in the remote host `C:\Users\{username}\.vscode-server` and `C:\Users\{username}\.vscode-server\data\logs`, and a copy of `xxxx(random name)\vscode-server-win32-x64` folder in `C:\Users\{username}\AppData\Local\Temp` folder, I can provide it at any time if needed.

### Anything else?

In the `C:\Users\{username}\AppData\Local\Temp` folder of the remote host, temporary files related to vscode-server are continuously generated until the disk space is exhausted:

![vscode-server](https://github.com/microsoft/vscode-remote-release/assets/5095184/5d2fe70d-2f5e-4563-a2d7-286c9e66b30d)

This is the third time I have encountered this situation in half a year. I don't know the steps to reproduce it, because after deleting these temporary files, everything is normal in the vscode remote connection.

If the cause cannot be analyzed now, please tell me what content needs to be retained for analysis next time I encounter this problem.

- VSCode Version: 1.87.1
- Local OS Version: 10.0.19045.4046
- Remote OS Version: 10.0.22631.3007

Thanks,

**Comment by joshspicer** [comment]
Thank you for taking the time to open an issue.  Could you please share your logs (`> Remote-SSH: Show Log` in the command palette) after reproducing the issue?

Not sure if this is a bug, feature gap, or something else.  The logs may help here

Assuming this is a duplicate, but could reopen if we get logs saying otherwise.

/duplicate https://github.com/microsoft/vscode-remote-release/issues/7963
