### ISSUE TITLE
Problem with local/remote extensions

### ISSUE THREAD

**Issue by muammar** [microsoft/vscode-remote-release#965]
First, let me thank you for this great extension to work using a remote server with vscode. It is very useful idea. 

- VSCode Version:
 1.36.1
- OS Version:
Local: macOS 10.15 Beta. 
Remote: Debian Unstable
Steps to Reproduce:

1. Connect through Remote-SSH: Connect to Host...
2. Open a python file. 

Does this issue occur when all extensions are disabled?: Yes.

As shown in the picture, some extensions are disabled when I connect to my SSH server:

<img width="298" alt="Screen Shot 2019-07-09 at 20 13 04" src="https://user-images.githubusercontent.com/954209/60937666-0eda0f80-a286-11e9-8e8f-4ab51199bedc.png">

If I install them in the remote SSH server then all my local extensions stop working. Is this the expected behavior?  The other problem is that extensions like `VIM` are not able to be installed remotely and therefore it becomes impossible to use them when installing something in the remote server.

**Comment by sandy081** [comment]
> some extensions are disabled when I connect to my SSH server:

This is because you are now in Remote Window (connected to SSH) and these disabled extensions and workspace extensions which are meant to run only on remote server in this context. Please go through this for more info - https://code.visualstudio.com/docs/remote/ssh#_managing-extensions

> If I install them in the remote SSH server then all my local extensions stop working. Is this the expected behavior? 

Ofcourse not. Can you be more specific on it. In which window are they not working and which extension and possible steps to repro.

> The other problem is that extensions like VIM are not able to be installed remotely and therefore it becomes impossible to use them when installing something in the remote server.

VIM is an UI extension and always runs locally. What is the usecase to install in it remotely?

**Comment by muammar** [comment]
> > some extensions are disabled when I connect to my SSH server:
> 
> This is because you are now in Remote Window (connected to SSH) and these disabled extensions and workspace extensions which are meant to run only on remote server in this context. Please go through this for more info - https://code.visualstudio.com/docs/remote/ssh#_managing-extensions
> 

Yes, I understand that. The link you sent over is helpful. However, at the moment I install the extensions in the remote the local ones start failing. 

> > If I install them in the remote SSH server then all my local extensions stop working. Is this the expected behavior?
> 
> Ofcourse not. Can you be more specific on it. In which window are they not working and which extension and possible steps to repro.
> 

Take as an example the picture above. If I install any of those extensions with the "install on SSH" in the remote, then, for instance, the VIM extension starts showing these errors:

<img width="736" alt="Screen Shot 2019-07-12 at 08 50 56" src="https://user-images.githubusercontent.com/954209/61141566-b02db500-a482-11e9-9eeb-6f58877ac1c6.png">

The extensions I have locally on my macOS are:

- autoDocstring
- GitLens
- Latex Workshop
- Python
- Vim
- Remote

If you would like to reproduce then install the Python and vim extensions. Connect to a remote and "install on SSH" Python. That should break your vim locally, or at least it does for me. 
> > The other problem is that extensions like VIM are not able to be installed remotely and therefore it becomes impossible to use them when installing something in the remote server.
> 
> VIM is an UI extension and always runs locally. What is the usecase to install in it remotely?

No use case here. I thought that installing vim remotely would fix the errors shown in the picture above.

**Comment by muammar** [comment]
I forgot to mention that I also had installed the [vscode-spellright](https://github.com/bartosz-antosik/vscode-spellright), and that is the extension breaking the SSH stuff on my vscode. I found it by installing on remote my extensions one by one and that is the only one that generates this problem. I, therefore, think that this is not vscode related and will proceed to report this to the upstream developer of vscode-spellright.

**Comment by sandy081** [comment]
Regarding VIM issue, please file an issue against VIM and they can look into it.

Re: vscode-spellright, yes there is an open issue against this extension already.
