### ISSUE TITLE
[Remote-SSH Bug]: WSL Target is not shown in the remote connection

### ISSUE THREAD

**Issue by Jia-py** [microsoft/vscode-remote-release#9653]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

There should be the WSL Targets

### Steps To Reproduce

I have one windows pc, the pc has installed wsl. I want to use another laptop to connect to the wsl on my PC through tunnel.
1. Install the wsl and activate the tunnel on PC. The PC can connect to the wsl successfully.
2. use vscode.dev to connect the tunnel and install the wsl extension. But there is no WSL Targets shown in the remote explorer.

### Remote-SSH Log

None

### Anything else?

Maybe something I missed between step 1 and step 2? Really appreciate it if you can help me with this issue.

**Comment by aeschli** [comment]
Do you get the WSL commands when clicking on the remote indicator (lower left corner)?

Do you have the latest version of WSL installed? (0.86.0) ?

**Comment by Jia-py** [comment]
Thanks for your reply. I found the reason is that the mismatched version of wsl on my pc. After updating my vscode and wsl extension, it works.
