### ISSUE TITLE
Remote tunnel machines from the same IP are overriding each others

### ISSUE THREAD

**Issue by vicary** [microsoft/vscode-remote-release#9655]
- VSCode Version: 1.87.2
- Local OS Version: macOS 14.4
- Remote OS Version: macOS 14.4
- Remote Extension/Connection Type: Server

- Logs: N/A

Steps to Reproduce:

1. Using the "Install as a service" option, enable tunnel server from host A.
2. Check the remote tunnels tab to confirm host A is online.
3. Using the "Install as a service" option, enable tunnel server in host B with a different tunnel name but under the same external IP.
4. Check the remote tunnels tab to confirm that only host B is online, but machine A is disappeared from the list.

Machine A is expected to be online aloneside Machine B.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No. This is an issue about the "Remote Tunnel" extension.

**Comment by connor4312** [comment]
Could you please share the "Remote Tunnel Service" output from both machines?

**Comment by vicary** [comment]
With personal information redacted, these servers seem to kick each others out every few seconds.

The warnings no longer generates if I stop one of the servers.

| Machine A | Machine B|
| - | - |
| ![Screenshot 2024-03-14 at 01 50 02](https://github.com/microsoft/vscode-remote-release/assets/85772/a3dc7d21-e57e-4f2d-850e-3398d52209c0) | ![Screenshot 2024-03-14 at 01 51 56](https://github.com/microsoft/vscode-remote-release/assets/85772/0abcaf5a-bbdc-4b0e-8f4a-10e3066c96c6) |

**Comment by connor4312** [comment]
It looks like you have something that's killing the network connection every 13-14 seconds. I recommend checking your network configuration and any proxies you may have set up.

**Comment by vicary** [comment]
I am not using proxies and the network is only a router connecting the two machines.

It does not happen when there is only one active server behind the router (i.e. in my office), when there is more than one active servers, their "reconnection" will kill the connections of other active servers.

**Comment by connor4312** [comment]
Huh, that's weird, @derekbekoe do you know if there's anything that could be happening here?

**Comment by derekbekoe** [comment]
Unlikely but do the machines happen to share any file directories (e.g. shared drive etc.)?

@vicary, verbose logs from both machines may be helpful. `code tunnel --verbose` should get you the verbose output.

In addition, the tunnel-id and tunnel-region would allow us to check service-side events. The tunnel id and region, is the the value of `client_relay_uri` from the logs. e.g. `"wss://usw2-data.rel.tunnels.api.visualstudio.com/api/v1/Client/Connect/sneaky-fog-n631r4l"`.

After sending this, you can use `code tunnel unregister` so that next time, you get a new tunnel and the old one(s) are deleted.

**Comment by vicary** [comment]
| | Host A | Host B |
| - | - | - |
| tunnel-region | asse | asse |
| tunnel-id | lvrprkrz | lvrprkrz |
| Logs | [host-a.log](https://github.com/microsoft/vscode-remote-release/files/14611971/host-a.log) | [host-b.log](https://github.com/microsoft/vscode-remote-release/files/14611972/host-b.log) |

The tunnel-id for both mathine is identical, I guess this is the culprit.

Running `code tunnel unregister` on one of the macines seems to renew the tunnel-id of both servers on the next run, they are running fine afterwards.

Hopefully the information above would help prevent future occurrance where multiple machines would share the same tunnel-id. 😄

**Comment by connor4312** [comment]
Okay, that would make sense then. We do allow a tunnel to have the same name as an existing tunnel to "adopt" it. Previously we didn't which would require the user to go to their other machine or in the VS Code UI and register the conflicting tunnel. The downside is things like this can happen.

**Comment by vicary** [comment]
It would be nice if a tunnel contains an "active" state and something similar to a "machine id", it would allow other machines a more graceful way to backoff from their "adoptions".

Another workaround would be renewing the tunnel-id when disabling the server via VS Code's command palette, because I have tried multiple times but the GUI doesn't seems to do so. Only the command `code tunnel unregister` you recommended actually does it.

**Comment by connor4312** [comment]
I'll make a change to prevent 'adopting' tunnels that have an active host connection to help avoid this.

**Comment by vicary** [comment]
@connor4312 Thanks a lot!
