### ISSUE TITLE
Remote SSH requires entering password multiple times

### ISSUE THREAD

**Issue by ct-martin** [microsoft/vscode-remote-release#9659]
Type: <b>Bug</b>

Connect to remote server over SSH in VS Code. On Windows 11, VS Code will require you to enter the password for the remote user or SSH key multiple times (usually once when opening the connection and then again after the window appears to have connected). This does not occur on Linux with GNOME, which will only prompt you once.

Extension version: 0.109.0
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.0-97-generic

**Comment by roblourens** [comment]
Setting `"remote.SSH.useLocalServer": true,` can help, this is not the default on Windows.

**Comment by FM-96** [comment]
> Setting `"remote.SSH.useLocalServer": true,` can help, this is not the default on Windows.

This setting makes no difference to me. It still asks me to enter my password four (!) separate times when I connect to a SSH remote and open a folder.
