### ISSUE TITLE
Remote always cannot find path

### ISSUE THREAD

**Issue by Mon-ius** [microsoft/vscode-remote-release#9666]
When connect to the remote machine, open folder, it just auto popup suggestions without stop, it automatic list possible ones, then I click, then it shows the path not existed.

Do u guys just write a death loop for it?

Do u have open source code for this buggy plugin?

Everytime I use this remote connection is just like play music game, copy and paste path that poped, but without end `/`, then it will correctly know that path indeed existed and let me pass, wtf?

**Comment by roblourens** [comment]
I don't know what you're referring to, maybe you can share a screenshot or more details

**Comment by Mon-ius** [comment]
<img width="1920" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/25671258/a0040e7c-7d8b-4bb0-a32f-0118a68848bd">

<img width="1920" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/25671258/1d4a11bc-c113-4538-baff-6e1cd192f7e2">

<img width="833" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/25671258/aa364615-cb40-438e-8d06-125a6a9a49de">

**Comment by Mon-ius** [comment]
think disable the auto search or add delay between each calls can sovle

**Comment by Mon-ius** [comment]
not sure what u modify, now the `remote` cannot set conda based python environment now. 

<img width="997" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/25671258/408019bb-b3c5-4c18-bf66-3276606bea9e">

**Comment by roblourens** [comment]
I still don't really understand what's happening in these screenshots. Need specific step-by-step instructions to repro the issue

**Comment by Mon-ius** [comment]
Normal step,

- Host Selection, config in ~/.ssh/config
- Open Folder, which mentioned previously
- Install official Python support from left side
- Set conda env from right corner
- Then env installed pop-up, but cannot be selected

Best test on the fresh machine, max possibility be triggered

**Comment by roblourens** [comment]
> Then env installed pop-up, but cannot be selected

Can you explain more? Why not?

**Comment by Mon-ius** [comment]
seems not leave a valid log, just normal process, normal operation, and happens on the new machine. And we use, for example, the commands for env creation,

```bash
curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o $DEV_ROOT/conda.sh
mkdir -p $DEV_PREFIX && chmod +x $DEV_ROOT/conda.sh
bash $DEV_ROOT/conda.sh -b -p $CONDA_ROOT_PREFIX && rm $DEV_ROOT/conda.sh

. "$CONDA_ROOT_PREFIX/etc/profile.d/conda.sh"

conda create -n xl python=3.11 numpy -c conda-forge -y
conda activate xl
conda env config vars set LD_LIBRARY_PATH="$CONDA_PREFIX/lib"
conda env config vars set HF_HOME="/dev/shm"
conda env config vars set HF_DATASETS_CACHE="/dev/shm"
conda env config vars set PJRT_DEVICE=TPU
# conda env config vars set XLA_USE_BF16=1
# conda env config vars set XLA_USE_SPMD=1
conda deactivate && conda activate xl

pip install 'torch~=2.2.0' --index-url https://download.pytorch.org/whl/cpu
pip install 'torch_xla[tpu]~=2.2.0' -f https://storage.googleapis.com/libtpu-releases/index.html
pip install git+https://github.com/huggingface/accelerate

```

**Comment by roblourens** [comment]
Sorry but there just isn't enough information here to understand the problem
