### ISSUE TITLE
"Remote - Tunnels" blocks Remotes panel refresh when GitHub/Microsoft account logged in

### ISSUE THREAD

**Issue by mcanouil** [microsoft/vscode-remote-release#9673]
Since recently, if a GitHub or Microsoft grants access to "Remotes - Tunnels", then when refreshing the panel, the following error is displayed.
Of course and consequently, the panel is not refreshed.

On startup (or window reload):
![image](https://github.com/microsoft/vscode-remote-release/assets/8896044/66771d8c-5a19-405d-8cae-68e69566dc8e)

Then when refreshing the panel:

![image](https://github.com/microsoft/vscode-remote-release/assets/8896044/3965ff29-8d85-4b42-9d24-c292e48ba183)

![image](https://github.com/microsoft/vscode-remote-release/assets/8896044/5be3a4f6-63b1-4981-a97b-6450d4f6a482)

```txt
Error running command remote-explorer.refresh: Tunnel service returned status code: 403 Forbidden. This is likely caused by the extension that contributes remote-explorer.refresh.
```

Versions:

```txt
Version: 1.87.2 (user setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22621

Remote Development: v0.25.0
Remote - Tunnels: v1.5.1
```

**Comment by plwalsh** [comment]
I have also been seeing this every day now for the last few weeks.

**Comment by plwalsh** [comment]
This error is now blocking access to my list of SSH targets. Previously it was just an annoying popup, but now it actually fails. And the status code for me is `401 Unauthorized`. Started happening within the last 1-2 weeks or so.

```
Version: 1.96.0-insider (user setup)
Commit: 4a98be2738be4ad8647feb52d1e6845e06515dea
Date: 2024-11-08T09:56:49.748Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by Alex4210987** [comment]
i'd like to know how to solve this?

**Comment by Alex4210987** [comment]
alright, i fix this by reinstalling the extensions
