### ISSUE TITLE
Extension consumes high CPU

### ISSUE THREAD

**Issue by HwAtWork** [microsoft/vscode-remote-release#9676]
Type: <b>Bug</b>

With extension enabled, CPU usage jumps on electron processes and will occasionally cause app and computer freezing.

Extension version: 0.348.0
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (11.51GB free)|
|Process Argv|--crash-reporter-id 23043b49-ac57-4f43-ae9a-816a2de0ec7e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
7ghi1836:30988842

```

</details>

**Comment by bamurtaugh** [comment]
Thanks for filing. Which remote extension are you using? Is this a new behavior you've noticed, and/or is there a specific set of actions you take where you notice this the most?

**Comment by HwAtWork** [comment]
Hi,

After some more testing it seem like the culprit was the ".NET Install Tool":
[cid:89ec1233-3a8c-45c5-a961-afff174488e6]
[cid:0eb38aee-7010-4ffd-80e2-c32ac3c49063]
________________________________

**Comment by bamurtaugh** [comment]
Thank you for the update! I'll close this issue then, but please let us know if there does seem to be a remote-related issue.

**Comment by HwAtWork** [comment]
[like]  Hwan Hong reacted to your message:
________________________________
