### ISSUE TITLE
Remote Tunnels auto-authentication 

### ISSUE THREAD

**Issue by rishabh-dream11** [microsoft/vscode-remote-release#9681]
I followed [this](https://code.visualstudio.com/docs/remote/tunnels) doc to establish tunnels on the remote cluster for developing code with an instance of Local Vs code.

This requires constant authentication for any new cluster, my company's cluster management system gives a new instance of a remote cluster everyday which makes the authentication process repetitive and frustrating at times.

Is there a a way to automate the authentication via a script, say inject the ssh key in the startup scripts of the cluster?

**Comment by connor4312** [comment]
By default the credential for the tunnel is stored in the system keychain. To work around this, you can set the environment variable `VSCODE_CLI_USE_FILE_KEYCHAIN=1` (e.g. by running `echo "export VSCODE_CLI_USE_FILE_KEYCHAIN=1" >> ~/.bashrc` and reconnecting).
