### ISSUE TITLE
initializeCommand does not run before dockerComposeFile check and throws a modal warning of missing files

### ISSUE THREAD

**Issue by four43** [microsoft/vscode-remote-release#9685]
- VSCode Version:  1.87.2 863d2581ecda6849923a2118d93a088b0745d9d6 x64
- Local OS Version: Debian 12
- Remote OS Version: N/A
- Remote Extension/Connection Type: Containers via Docker Compose

- Logs: (None yet)

Steps to Reproduce:

1. Create a devcontainer.json file containing a few docker-compose files and init script:
```
...
	"dockerComposeFile": [
		"docker-compose.yml",
		"docker-compose.override.local-map.yml",
		"docker-compose.override.yml",
	],
	"initializeCommand": "./.devcontainer/config/init.sh",
...
```
2. Ensure only `docker-compose.yml` exists
3.  Create the other files with the init script, something simple like just touching them
4. You are greeted with a popup: `The following referenced docker compose files do not exist` from VS Code. 

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Expectation:

This guard rail should only be run after `initializeCommand` is run. The documentation is for that command states that it should run "before anything else" on the local machine.

Use case:

I need to dynamically set some variables for Docker Compose to use. Since these commands are run in a sub shell I can't seem to get them out to template the Docker Compose files properly. My solution was to write out templated docker compose files, which does work with the init script, but VS Code is throwing up a hand holding guard rail too quickly. I would say remove the guard rail and just let the log show the issue.

**Comment by four43** [comment]
Oh nice, this is already fixed for a march release? Great! Thanks.

**Comment by TylerLeonhardt** [comment]
Fix is available in the latest Dev Containers pre-release. Can you verify this is fixed for you @four43?

**Comment by chrmarti** [comment]
Steps for verification:
- Open empty folder.
- `F1` > `Dev Containers: Reopen in Container` (for verification it is important that the container already exists).
- Pick Docker Compose template, e.g., `Node.js & Mongo DB`.
- `F1` > `Dev Containers: Reopen Folder Locally`.
- Rename `docker-compose.yml` to `docker-compose-orig.yml`.
- Add `"initializeCommand": "cp .devcontainer/docker-compose-orig.yml .devcontainer/docker-compose.yml"` to the `devcontainer.json`.
- `F1` > `Dev Containers: Reopen in Container`
- Ensure there is no error this second time.

**Comment by four43** [comment]
Verification steps:
:heavy_check_mark: - Works great! Removed the old stopped container as well, double checked full rebuild.

My specific issue:
:heavy_check_mark: - Also works great!

Thank you all so much for knocking this out. This is a huge step forward in extensibility of devcontainers.
