### ISSUE TITLE
Test: legacy server for devcontainers

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-remote-release#9686]
Refs: https://github.com/microsoft/vscode/issues/206790

- [x] macOS @paulacamargo25
- [x] windows @ntrogh

Complexity: 3
Authors: @chrmarti, @deepak1556 

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%239686%0A%0A&assignees=deepak1556,chrmarti)

---

This milestone we have changed which server the extension downloads depending on the OS support, the following test plan is to ensure successful connection over the different scenarios

**Prerequisite:**

* Ensure docker is installed https://www.docker.com/get-started/ 
* Clone `https://github.com/chrmarti/legacy-server-test/` and open the folder with VS Code insiders
* Install pre-release version of [dev containers extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers)

**Steps:**

- Run the command `Dev Containers: Reopen in container`
- Choose `Debian 10 (supported)` from the list
- Ensure connection is successful and you are able to open a new terminal.
- In the terminal run `ls /root/.vscode-server-insiders/bin/` and confirm there is no folder that has `-legacy` suffix
- In the terminal run `cat /root/.vscode-server-insiders/bin/<commit-hash>-insider/node | grep -a 'GLIBC_2.28'` and ensure it prints a non-empty output containing `GLIBC_2.28`
- Close the connection
- Run the command `Dev Containers: Reopen in container`
- Choose `Debian 9 (Legacy Server)` from the list
- Ensure a dialog pops-up about potential connection to unsupported OS
- Allow the connection
- In the terminal run `ls /root/.vscode-server-insiders/bin/` and confirm there is a folder that has `-legacy` suffix
- In the terminal run `cat /root/.vscode-server-insiders/bin/<commit-hash>-insider-legacy/node | grep -a 'GLIBC_2.28'` and ensure it prints an empty output
- Close the connection

**Comment by ntrogh** [comment]
LGTM on Windows!

**Comment by paulacamargo25** [comment]
I got this warning, but all steps work fine on MacOS.
<img width="478" alt="Screenshot 2024-03-25 at 10 17 49 AM" src="https://github.com/microsoft/vscode-remote-release/assets/17892325/ce9e3ba1-4dca-4a18-8dd6-1511635ac069">
