### ISSUE TITLE
Change the way VS Code Server installs on remote host (too many dirs)

### ISSUE THREAD

**Issue by WSLUser** [microsoft/vscode-remote-release#969]
- VSCode Version: 1.37
- Local OS Version: Win7 SP1
- Remote OS Version: Fedora 29
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install extension.
2. Setup ssh config to connect to server
3. VSCode Server installs.
4. Go to /home/username/.vs.../bin
5. ls and observe multiple commit id directories exist.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: N/A

I use SSH Nightly. Leaving behind directories filled with the old VS Code server data is not very friendly for users of this extensions. Instead of generating a new directory with an updated commit id, use a dedicated path that simply updates the necessary files. Also make it so if for some reason it fails, you can still connect and work remotely instead of denying from the client side simply because the commits are mismatched. Until this is fixed, I think I need to stop using this extension unfortunately. This last part is especially an issue in my situation since we don't have an [offline install available](https://github.com/microsoft/vscode-remote-release/issues/15).

**Comment by roblourens** [comment]
When connecting we clean up old installations, if they are not in use, leaving just the 5 most recent installs. Is that still too many for you? What issue exactly is this causing?

**Comment by WSLUser** [comment]
I have two machines I used to connect to the same server depending on if I'm in the office or remote. Because the commit ids are different, attempting to force the connection with the same server fails. I should be able to use the same server for multiple machines. Otherwise it's not a server at all. Merely an endpoint and not a great one at that since it wants to reach out to the Internet. The server is not normally open to the Internet so I was hoping once the server was installed, it wouldn't matter if I connected using a different machine. Apparently it does. The issue I've raised proposes a solution to this issue. Because the error I received specifically stated version mismatch since the extension was newer on one machine than the other.

**Comment by roblourens** [comment]
I think there is some misunderstanding. You can absolutely connect with different versions of vscode (this is what matters, not the extension version) but there will be two copies of the server running. If you connect from different machines with the same version of vscode then there would just be one server.

> Because the error I received specifically stated version mismatch since the extension was newer on one machine than the other.

This sounds like a different sort of issue and if you share the log from the Remote-SSH output channel of the window that couldn't connect I can probably tell you what's going on.
