### ISSUE TITLE
Test: legacy server in WSL

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#9690]
Refs: https://github.com/microsoft/vscode/issues/206790

 - [ ] Windows @joyceerhl

Complexity: 4

Authors: @aeschli, @deepak1556

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%239690%0A%0A&assignees=aeschli,deepak1556)

---

This milestone we have changed which server the extension downloads depending on the OS support, the following test plan is to ensure successful connection over the different scenarios

**Prerequisite:**
   - Windows machine with WSL installed: https://learn.microsoft.com/en-us/windows/wsl/install
   - Latest VS Code Insiders & WSL extension installed (0.88.0)
   - A set of distros: At least Ubuntu 18.04, Ubuntu 22.04

To install a new distro:
- open the remote explorer, go to the `WSL Targets` tab
- click on the `+` icon in the toolbar to install a new distro

If you already have these distros and want to create a second instance of a distro:
```
wsl --export Ubuntu-18.04 ubuntu18.tar
wsl --import Second-Ubuntu-18.04 .\SecondUbuntu18 ubuntu18.tar
```

**Testing**

For various distros try that these steps work

a. Starting a remote WSL window from the command line prompt:

- Open a windows command prompt and type `wsl -d Ubuntu-18.04`
- remove existing server installations: `rm -r ~/.vscode-server-insiders/bin`
- start VS Code `code-insiders .`

This should install the server and start VS Code with a remote WSL window
If the OS is a legacy platform (Ubuntu 18.04), you will see two server downloads. First the normal server, then a compatibility check and then the legacy server. 

- close VS Code and try `code-insiders .` again

This should start VS Code with a remote WSL window, no download necessary

b. Starting a remote WSL window from the inside VS Code

- Open a windows command prompt and type `wsl -d Ubuntu-18.04`
- remove existing server installations: `rm -r ~/.vscode-server-insiders/bin`
- open VS Code and invoke the `Connect to WSL using Distro...` command
- This should should a progress dialog. It will install the server and start VS Code with a remote WSL window
- If the OS is a legacy platform (Ubuntu 18.04), you will see two server downloads. First the normal server, then a compatibility check and then the legacy server. 

- close VS Code and try `code-insiders .` again

**Comment by joyceerhl** [comment]
Tested 18.04, 22,04, openSUSE-Leap-15.5, and Kali Linux.
