### ISSUE TITLE
VS Code ignores RemoteCommand

### ISSUE THREAD

**Issue by Roy-Kid** [microsoft/vscode-remote-release#9697]
Hi everyone!

RemoteCommand is always none when I ssh to remote, even I turn on `enableRemoteCommand` and `Use Local Server`. I found this issue [VS Code ignores RemoteCommand](https://github.com/microsoft/vscode-remote-release/issues/6598), and I think the problem is `remote.SSH.remotePlatform`. When I comment it out and ssh to remote, there is always a prompt to ask me to select a system, if I select it, `remote.SSH.remotePlatform` will back to my settings again. I can not remove it. How should I fix this?

Thanks!

**Comment by ZbigniewRA** [comment]
This is my problem as well.
Description for `Remote.SSH: Enable Remote Command` says it is only enabled when remote is not listed in `Remote.SSH: Remote Platform`
Description for `Remote.SSH: Remote Platform` says it is autopopulated for successful connections...
It's a catch-22.

**Comment by roblourens** [comment]
Make sure you've enabled `useLocalServer` in your settings.json, even if it's checked in the UI it needs to be there on windows due to a quirk of our config system, sorry for the confusion
