### ISSUE TITLE
Can't install Ubuntu 18.04 from remote explorer in WSL window

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-release#9698]
Testing #9690

1. Be in a WSL Kali Linux VS Code window
2. From the Remote Explorer, install Ubuntu 18.04
3. :bug: 
    ```
    '[object Promise]' --install -d Ubuntu-18.04
    Could not find command-not-found database. Run 'sudo apt update' to populate it.
    [object Promise]: command not found
    ```

Doing this from a local VS Code window works as expected

**Comment by joyceerhl** [comment]
Also true for installing Ubuntu 18.04 

![Image](https://github.com/microsoft/vscode-remote-release/assets/30305945/3e25a152-d508-41d6-aa69-c6b727e26e62)

**Comment by deepak1556** [comment]
Unrelated to legacy server, removing myself.
