### ISSUE TITLE
[Remote SSH] 0.44.1 very slow to open remote folder via SSH.

### ISSUE THREAD

**Issue by bcronje** [microsoft/vscode-remote-release#970]
- VSCode Version: 1.36.1
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH (Extension version 0.44.1)

Steps to Reproduce:

1. Open remote folder via Remote SSH extension
2. Wait 35 - 40 second for folder to open.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

With extension version 0.44.1 all of a sudden opening remote folders via SSH takes much longer that what it used to. It used to take at most 5 seconds, and all of a sudden it takes 35 - 40 seconds to open the folder. If I downgrade to v 0.44.0 the problem goes away.

I've tested with Insiders 1.37.0-insider and experiencing the exact same issue.

I dont see any errors in the logs apart from:

```
Got stderr from ssh: OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4
```

Using Wireshark to take a packet trace I noticed a 15 second delay between the TCP connection establishment and SSH key exchange and this happens twice (seems to establish two ssh sessions one after the other). So that brings us to 30 seconds worth of waiting just on that. Presumably the 15 seconds is some timeout happening locally as it is always exactly 15 seconds? 

Note once the folder is open then I am not experiencing any other issues.

Connection with 0.44.1 packet trace with issue:

![image](https://user-images.githubusercontent.com/462097/61160111-a2b61080-a4fe-11e9-8596-3069d10d6491.png)

Connection with 0.44.0 packet trace with no issues:

![image](https://user-images.githubusercontent.com/462097/61160182-d002be80-a4fe-11e9-9dc3-96cc20ea6548.png)

**Comment by OmriSama** [comment]
Thank goodness. I thought it was just me, but the latest VSCode-remote over SSH is *so* slow...

**Comment by roblourens** [comment]
Wow, the ConnectTimeout flag is broken in windows openssh: https://github.com/PowerShell/Win32-OpenSSH/issues/1352

I added it back for windows in the last release but I think it was omitted on purpose...

**Comment by bcronje** [comment]
@roblourens I couldn't find the Remote SSH source code repo, is it closed for public review?

Just a small thank you, the whole remote development feature is such a great tool for us that does development across multiple hosts and operating systems. So my thanks and appreciation to you and everyone else involved in releasing this amazing extension.

**Comment by roblourens** [comment]
Right it is currently not open source. I am releasing this to stable right now and it's currently in the nightly release.

Thanks! ❤️

**Comment by roblourens** [comment]
Ok this is in 0.44.2 😓

**Comment by bcronje** [comment]
I can confirm 0.44.2 does fix the issue. Thank you, much appreciated!
