### ISSUE TITLE
UI doesn't open connection

### ISSUE THREAD

**Issue by adamwawrzynski** [microsoft/vscode-remote-release#9707]
Type: <b>Bug</b>

1. Go to `Remote Explorer` tab
2. Click `New remote`
3. Type ssh command and press Enter
4. Select configuration file to update
5. VSCode will open `Extension marketplace` with prompted message `@id:ms-vscode-remote.remote-ssh` even though it is already installed

vscode version: 1.87.2
Tested Remote SSH extensions: 0.109.0, 0.108.0

Extension version: 0.108.0
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:14:59.643Z)
OS version: Linux x64 6.5.0-26-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (32 x 3003)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|62.71GB (50.56GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 5d90dc2c-ecd3-4e27-bd16-ec01062556c9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:30996668
dsvsc021:30996838
g1icg217:30999571

```

</details>

**Comment by xetxezarreta** [comment]
Here's how you can I fixed the problem. Assuming you're using Windows 10/11:

1. Open the following file in a text editor:
```powershell
C:\Users\<username>\.ssh\config
```
Replace `<username>` with your current logged-in windows user.

2. Register your host in the config file using this format:
```config
Host <name>
    HostName <ip address>
    User <username of the remote machine>
    Port <ssh port, default is 22>
```

Replace `<name>`, `<ip address>`, `<username of the remote machine>`, and `<ssh port>` with your specific details.

3. Save the changes and close the file.

4. Try connecting with VSCode again; it should work now.

This solution resolved the issue for me, and hopefully, it works for you too!

**Comment by roblourens** [comment]
I'm not sure how this is happening. 

- Does it still happen with the latest of everything? 
- Can you check for errors in the "Window" output channel?
- Does the "Remote-SSH" output channel appear?


If that doesn't help, it would help if you can get a screen recording of what you're doing to make sure I understand the steps.

**Comment by xetxezarreta** [comment]
> Does it still happen with the latest of everything?

This happened with everything up to the latest version.
Since I fixed the bug following the steps above, I'm not able to reproduce the bug again.

> Can you check for errors in the "Window" output channel?
> Does the "Remote-SSH" output channel appear?

A gif was posted in #9714 showing how the bug occurs. I hope this is helpful. Here is the reposted gif:

![317630231-96c6b668-7452-4c7d-8c73-4ed0a53821bc](https://github.com/microsoft/vscode-remote-release/assets/35383579/cfe68ff1-032b-4bcf-8409-ffc0e1e4b862)

**Comment by whywhy19i** [comment]
I also have such a problem and want to know how to solve it
