### ISSUE TITLE
Cannot determine which container VS Code created when "image" property used in devcontainer.json

### ISSUE THREAD

**Issue by mgsergio** [microsoft/vscode-remote-release#971]
## The problem
When you use an "image" key in .devcontainer.json the container you choose sticks and you can't change it later.

## OS and VSCode versions

Version: 1.37.0-insider
Commit: 8fa811108f0f0524c473020ef57b6620f6c201e1
Date: 2019-07-12T09:17:10.495Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

## Similar issue

[This](https://github.com/microsoft/vscode-remote-release/issues/342) is about the same problem I think. But removing .devcontainer or .devcontainer.json just to reset the container image is not a good option I believe.

## WTR:
  
    mkdir vscode-container-bug
    cd vscode-container-bug
    cat <<END > .devcontainer.json
    {
       "image": "ubuntu",
       "name": "vscode-bug"
    }
    END
    code-insiders .

Then reopen folder in container and make sure that you're in ubuntu
    
    cat /etc/debian_version

Then reopen folder locally and do 

    cat <<END > .devcontainer.json
    {
       "image": "fedora",
       "name": "vscode-bug"
    }
    END

And reopen folder in container again. We can still see docker_version that should not exists in fedora.

    cat /etc/debian_version

## Expected behaviour

VSCode creates container from ubuntu image the first time and from fedora the second time

## Actual behaviour 

VSCode uses ubuntu image both times and ignores "image" key in .devcontainer.json

**Comment by Chuxel** [comment]
Did you run `Rebuild Container` or `Reload`?  Reload will not rebuild since that is a destructive operation.  If you modify devcontainer.json, you use the rebuild command to get it to change.

**Comment by mgsergio** [comment]
Thanks for the quick replay! No I didn't try Reload Container. It did the trick, thanks.

Is there a way to manually clean up the cache of dev containers? I couldn't find anything like that in extensions folder.

**Comment by mgsergio** [comment]
UP

**Comment by Chuxel** [comment]
@mgsergio These are all Docker containers, so you use Docker to clear out images. https://code.visualstudio.com/docs/remote/troubleshooting#_cleaning-out-unused-containers-and-images

**Comment by mgsergio** [comment]
@Chuxel I meed how does VSCode know what container to use for each project? There is no hint in container names.

If I launch a dev container for the first time VSCode ensures that an appropriate image exists and makes a container ,say gifted_ganguly, from it. If I then change "image" in .devcontainer.json VDCode will still use the container gifted_ganguly. So this information should be stored somewhere. I wonder where is it.

**Comment by Chuxel** [comment]
@mgsergio Ah, got it - great question.  In the Dockerfile case, the image name contains the local folder name in the form of `vsch-localfoldernamehere-hash`, however, you can also use `docker ps` to get a list of containers, the local folder, and which version of VS Code created the container (stable/insiders)

```
ps -a --filter label=vsch.local.folder --format "table {{.ID}}: {{.Image}} {{.Label \"vsch.local.folder\"}} ({{.Label \"vsch.quality\"}})"
```

Technically `--filter` is optional.  We should add this to docs.

**Comment by mgsergio** [comment]
@Chuxel Oh! That's cool! Thanks for the answer. Is there a way to have this info in documentation? I could contribute I guess.

**Comment by Chuxel** [comment]
@mgsergio Yep! In fact, I just added it in this docs PR: https://github.com/microsoft/vscode-docs/pull/2901 ☺️ , so closing this as resolved.

**Comment by mgsergio** [comment]
@Chuxel You rock, Thanks!
