### ISSUE TITLE
[Remote-SSH Bug]: Fail to add new Host

### ISSUE THREAD

**Issue by WSUFish** [microsoft/vscode-remote-release#9714]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

After enter the SSH connection command and press ENTER, the config file is displayed and available for me to edit.  A remote host icon should be displayed in the 'SSH targets' list of the remote explorer. However it automatically jumps to the EXTENSIONS page and populates “@id:ms-vscode-remote.remote-ssh” to the search field and nothing in the ssh targets list.

### Steps To Reproduce

1. Open the remote explorer
2. Choose 'SSH Targets'
3. Click on the '+' to add a new SSH target
4. Enter the SSH connection command and press ENTER

Version: 1.87.2 (user setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

Name: Remote - SSH
Id: ms-vscode-remote.remote-ssh
Description: Open any folder on a remote machine using SSH and take advantage of VS Code's full feature set.
Version: 0.109.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh

### Remote-SSH Log

nothing

### Anything else?

![remote-ssh-fail](https://github.com/microsoft/vscode-remote-release/assets/37091198/96c6b668-7452-4c7d-8c73-4ed0a53821bc)

**Comment by xetxezarreta** [comment]
Here's how you can I solved the problem. Assuming you're using Windows 10/11:

1. Open the following file in a text editor:
```powershell
C:\Users\<username>\.ssh\config
```
Replace `<username>` with your current logged-in windows user.

2. Register your host in the config file using this format:
```config
Host <name>
    HostName <ip address>
    User <username of the remote machine>
    Port <ssh port, default is 22>
```

Replace `<name>`, `<ip address>`, `<username of the remote machine>`, and `<ssh port>` with your specific details.

3. Save the changes and close the file.

4. Try connecting with VSCode again; it should work now.

This solution resolved the issue for me, and hopefully, it works for you too!

**Comment by WSUFish** [comment]
@xetxezarreta 
Thank you so much for sharing your solution! I tried it, and I'm glad to report that it resolved the issue for me as well.
