### ISSUE TITLE
Fail to load the list of containers 

### ISSUE THREAD

**Issue by Liuz233** [microsoft/vscode-remote-release#9716]
Does this occur consistently?  Yes
Repro steps:

1. Select options for remote connections
2. Select the "attach to running containers" option
3. keeping loading

Version: 1.29.0
OS: linux
OS Release: 5.15.0-48-generic
Product: Visual Studio Code
Product Version: 1.87.2
Language: zh-cn
------------------------------
When I try to attach containers in vscode, the vscode keep loading the list of running containers and show nothing
I haven't meet this problem before
<img width="461" alt="image" src="https://github.com/microsoft/vscode-docker/assets/92071158/a6c9637c-964a-4d5d-b17a-ccf7f1729a35">

**Comment by chrmarti** [comment]
Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)

**Comment by Liuz233** [comment]
> Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)
here is the log when I try to attach to running containers
![image](https://github.com/microsoft/vscode-remote-release/assets/92071158/471d324e-d509-450c-b573-9804d7c1ff2b)

**Comment by chrmarti** [comment]
Could you append the entire log? There must be many more lines above the ones you posted.

**Comment by Liuz233** [comment]
Here is the entire log
![image](https://github.com/microsoft/vscode-remote-release/assets/92071158/b49107ef-de02-41c8-a486-3ce6c795ef5c)
Also, I may have found the problem. The logs are stuck after running the "docker inspect" command, which I tried to run in the terminal. I found that all other container IDs work fine, except for "docker inspect --type container 13632bbfe551" which gets stuck. I think it's a problem with this container.

**Comment by Liuz233** [comment]
> Could you append the entire log? There must be many more lines above the ones you posted.

Here is the entire log
![image](https://github.com/microsoft/vscode-remote-release/assets/92071158/b49107ef-de02-41c8-a486-3ce6c795ef5c)
Also, I may have found the problem. The logs are stuck after running the "docker inspect" command, which I tried to run in the terminal. I found that all other container IDs work fine, except for "docker inspect --type container 13632bbfe551" which gets stuck. I think it's a problem with this container.

**Comment by chrmarti** [comment]
This appears to be a problem with Docker then. Can you stop the container? That would remove it from the list of containers the extension inspects.

**Comment by Liuz233** [comment]
> This appears to be a problem with Docker then. Can you stop the container? That would remove it from the list of containers the extension inspects.

I closed that container and it finally solved the problem

**Comment by chrmarti** [comment]
Closing as upstream issue. Please file an issue with Docker if you want to track it down. Thanks.
