### ISSUE TITLE
can't parse port connection error

### ISSUE THREAD

**Issue by rbavery** [microsoft/vscode-remote-release#972]
Issue Type: <b>Bug</b>

start vscode and attempt to connect given a config file that looks like this
```
Host *
ServerAliveInterval 240
ServerAliveCountMax 3

Host name
    User username
    HostName ip address
```
I can connect to the following vm on a different machine running the same version of vscode and Ubuntu 18.04, so this issue seems to be configuration specific or OS specific?

```
remote-ssh@0.44.2
linux x64
SSH Resolver called for "ssh-remote+cropmask-gpu", attempt 1
SSH Resolver called for host: cropmask-gpu
Setting up SSH remote "cropmask-gpu"
Using commit id "0f3794b38477eea13fb47fbe15a42798e6129338" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_7.2p2 Ubuntu-4ubuntu2.8, OpenSSL 1.0.2g  1 Mar 2016
Running script with connection command: "ssh"  -o ClearAllForwardings=true -o ConnectTimeout=15   "cropmask-gpu" bash
Install and start server if needed
> Running remote connection script
> Found existing installation at /home/ryan/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338...
> XDG_SESSION_ID=3
> SHELL=/bin/bash
> SSH_CLIENT=128.111.64.33 48052 22
> USER=ryan
> VSCODE_AGENT_FOLDER=/home/ryan/.vscode-server
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
> MAIL=/var/mail/ryan
> PWD=/data/home/ryan
> LANG=en_US.UTF-8
> HOME=/home/ryan
> SHLVL=2
> LOGNAME=ryan
> SSH_CONNECTION=128.111.64.33 48052 10.0.2.4 22
> XDG_RUNTIME_DIR=/run/user/1003
> _=/usr/bin/printenv
> Starting server...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Server did not start successfully. Full server log >>>
> <<< End of server log
"install" terminal command done
Received install output: <<< End of server log
Failed to parse remote port from server output: <<< End of server log

------
```

Extension version: 0.44.2
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2699)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.08GB (0.13GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
You can connect to the same VM from a different machine? That's interesting because it looks like the remote server didn't start properly. Are you connecting as the same user?

Can you check whether `~/.vscode-server/.0f3794b38477eea13fb47fbe15a42798e6129338.log` does actually exist on the remote and whether it is actually empty?

**Comment by rbavery** [comment]
Hey @roblourens thanks for the quick reply. That vscode server file does exist and has stuff in it:

```
ryan@cropmask-gpu:~$ cat ~/.vscode-server/.0f3794b38477eea13fb47fbe15a42798e6129338.log 


*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


IP Address: <privateip>
webview server listening on 46201
Extension host agent listening on 37497

```
should my ssh config hav ethe public or private ip address?

**Comment by roblourens** [comment]
Strange, and if you just try again it does not work?

Your ssh config should have whatever ip address you would normally use to connect to it from that local machine.

**Comment by rbavery** [comment]
Yeah, I've tried again a few times and it's the same thing each time! Happy to provide more info if it will help.

**Comment by rbavery** [comment]
Part of this could be that I'm using a VPN, but without the VPN I can't use ssh due to my current wifi restrictions.

**Comment by roblourens** [comment]
I'm not even sure what to ask. You could try the `Uninstall VS Code Server` command to start over from scratch.
