### ISSUE TITLE
Connect to remote server without tunnel (part 2)

### ISSUE THREAD

**Issue by Bluscream** [microsoft/vscode-remote-release#9721]
Continuation of https://github.com/microsoft/vscode-remote-release/issues/8672 which was closed without being resolved.

I would like to be able to use this feature to offload heavy extensions (like language servers, etc.) to my local machine and away from the server. Same request but different usecase. In my case the server is just not strong enough to run vscode with all my extensions alongside all the other server apps/running the code itself. vscode server manages to take 97% of the CPU of my Pi 3 at times with all the extensions i need when working on different languages, and being able to offload that to the electron client is a nice way to keep the serverside cpu usage at around ~30-40% which is fine while working on stuff.

The alternative of letting the client spawn it's own code-server instance through the ssh tunnel results in the afformentioned cpu usage spikes that make the whole machine inoperable at times and also the code-server instances never close on disconnect which make the resource hogging exponentially worse. I opted to host the server with heavy systemd restrictions to keep resources in bay, but that requires regular service restarts because the server runs OOM after a while
```ini
[Unit]
Description=code-server
After=network.target

[Service]
Type=exec
ExecStart=/usr/bin/code-server --bind-addr 0.0.0.0:4321
Restart=always
RuntimeMaxSec=6h
# User=%i

LimitNOFILE=8000
LimitNPROC=8000
LimitCORE=1500M
LimitRSS=1500M
LimitAS=1500M
LimitFSIZE=1500M
LimitCPU=75%
LimitSTACK=16M
LimitMEMLOCK=128M
LimitLOCKS=64
LimitSIGPENDING=60384
LimitMSGQUEUE=1609600
LimitNICE=0
LimitRTPRIO=16
LimitRTTIME=2000000

[Install]
WantedBy=default.target


```

**Comment by chrmarti** [comment]
For larger repositories it makes sense to run the language services on the same machine where the files are. Maybe in your case you could checkout the repository locally, run VS Code locally and mount the repository (or just the compiled output) from the Pi (or the other way around while still running all of VS Code locally).

**Comment by connor4312** [comment]
code-server is not something we publish, you can try `code serve-web` as an alternative.
