### ISSUE TITLE
[Remote-SSH] Case sensitivity issues in remote file view

### ISSUE THREAD

**Issue by Keno** [microsoft/vscode-remote-release#973]
- VSCode Version: 1.37.0-insider
- Local OS Version: macOS 10.14.5
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to a remote folder that has two folders differing only by case (e.g. `foo` and `FOO`)
2. Only one of the folders shows up in the file view on the LHS

Does this issue occur when you try this locally?: N/A - Local FS is case insensitive
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by roblourens** [comment]
This is a part of https://github.com/microsoft/vscode/issues/12448
