### ISSUE TITLE
Git Commit Signing: Unable to open allowed keys file

### ISSUE THREAD

**Issue by MartinLoeper** [microsoft/vscode-remote-release#9732]
- VSCode Version: 1.87.2
- Local OS Version: NixOS Unstable
- Remote OS Version: NixOS Unstable
- Remote Extension/Connection Type: Containers

- Logs:
```
Good "git" signature with ECDSA-SK key SHA256:<redacted>
Unable to open allowed keys file "/home/node/.ssh/allowed_signers": No such file or directory
sig_find_principals: sshsig_get_principal: No such file or directory
No principal matched.
```

Steps to Reproduce:

1. create a signed commit in a git repo and configure allowed signers:   
```
[gpg "ssh"]
  allowedsignersfile = "~/.ssh/allowed_signers"
```
2. open the repo using devcontainers extension

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

It looks like the allowed_signers file is simply not copied over into the container. Can we make provide a devcontainer.json attribute or so to copy files which are required for git commit signing to work properly.

Possibly related to:

- https://github.com/microsoft/vscode-remote-release/issues/7796 @chrmarti

What is interesting though: Signing works as expected. It is only validation which looks like it's not supported yet.

**Comment by Gakai** [comment]
I get the same error when the `allowed_signers` file is inside a symlinked directory.

**Comment by chrmarti** [comment]
@Gakai This must be Git's behavior independent of Dev Containers.

Looking into copying the file into the dev container when `ssh` is available.

**Comment by chrmarti** [comment]
@MartinLoeper If you get a chance, could you try this with the latest pre-release version of Dev Containers (currently 0.387.0)?

For others to verify:
- Configure an allowed signers file locally: `git config --global gpg.ssh.allowedSignersFile <file path>`.
- If you don't have such a file: It's sufficient for the file to just have a comment line starting with `#`, so you can verify it is properly copied.
- Open a dev container, e.g.: `F1` > `Dev Containers: Try a Dev Container Sample...` > `Node`.
- In the container verify that `git config --global --get gpg.ssh.allowedSignersFile` shows a filepath and the file is a copy of your local file.

**Comment by connor4312** [comment]
This does not seem to work for me on devcontainers 0.387.0 on Windows.

Windows side:

```
PS C:\Users\conno> cat C:\Users\conno\.gitconfig
[core]
        editor = \"C:\\Users\\conno\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\bin\\code-insiders\" --wait
        excludesfile = "C:\\Users\\conno\\.gitignore_global"
        pager = delta
[user]
        email = connor@peet.io
        name = Connor Peet
        signingkey = CF8FD2EA0DBC61BD
[pull]
        rebase = true
[rebase]
        autoStash = true
[commit]
        gpgsign = true
[gpg]
        program = C:\\Program Files (x86)\\GnuPG\\bin\\gpg.exe
[push]
        default = current
[url "git@github.com:"]
        insteadOf = https://github.com/
[merge]
    conflictstyle = diff3
[diff]
    colorMoved = default
[interactive]
    diffFilter = delta --color-only
[gpg "ssh"]
        allowedSignersFile = C:\\Users\\conno\\Downloads\\signer.txt
```

Container side:

```
node ➜ /workspaces/vscode-remote-try-node (main) $ cat ~/.gitconfig 
[core]
        excludesfile = "C:\\Users\\conno\\.gitignore_global"
[user]
        email = connor@peet.io
        name = Connor Peet
        signingkey = CF8FD2EA0DBC61BD
[pull]
        rebase = true
[rebase]
        autoStash = true
[commit]
        gpgsign = true
[push]
        default = current
[url "git@github.com:"]
        insteadOf = https://github.com/
[credential]
        helper = "!f() { /home/node/.vscode-server-insiders/bin/be2747e47e127ec674148b78dd9556c6317d18bd-insider/node /tmp/vscode-remote-containers-f5db7c48-0568-49ce-9f40-e7074d44349d.js git-credential-helper $*; }; f"
```

**Comment by chrmarti** [comment]
@connor4312 Do you have a dotfiles repo configured that brings in a `.gitconfig`? Could you try without?

**Comment by connor4312** [comment]
I don't think so...

![Image](https://github.com/user-attachments/assets/4f022118-724e-4d79-a12d-c6e4f0b8bd48)

**Comment by chrmarti** [comment]
Please append the Dev Containers log from when you rebuild the container.
