### ISSUE TITLE
Dev contains hangs when loading local containers

### ISSUE THREAD

**Issue by shouldnotfail** [microsoft/vscode-remote-release#9741]
- VSCode Version: 1.85.2 (user setup)
- Local OS Version: Windows_NT x64 10.0.19045
- Remote OS Version: Ubuntu 22.04.4 LTS
- Remote Extension/Connection Type: Containers 
- Dev Containers Version: v0.327.0

This issue occurred twice when a local container could not be executed or removed. It seems that the dev container also tried to interact with the bad containers, eventually leading to a hang.
After reboot pc, bad container could be removed and, dev container works again.

command docker exec -it xxx /bin/bash still works when approching other containers in terminal all time

![image](https://github.com/microsoft/vscode-remote-release/assets/15360487/e6e0aa3d-ef98-4cff-b094-23404968fd4b)

**Comment by shouldnotfail** [comment]
command docker exec -it xxx /bin/bash still works when approching other containers

**Comment by chrmarti** [comment]
Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)

The extension uses the Docker CLI to list and inspect the existing containers. This sounds like the Docker CLI might be stuck too.

**Comment by shouldnotfail** [comment]
I've rebooted the computer and will upload the log when it happens again
