### ISSUE TITLE
Remote Host Tasks/Multi Host Workspaces

### ISSUE THREAD

**Issue by GMGilson** [microsoft/vscode-remote-release#9746]
Workflow:
I have a cross platform code base, macos/linux/windows. I will usually declare one of these remotes the main dev system and transfer diffs between remotes to queue builds, debug, and triage. 

Feature: 
Define Hosts in workspace file that can be connected to via ssh.
Essentially multi-root workspaces but where the roots are on remote/container.
Enable tasks that can be specified to run on these hosts.  

Workaround:
Define tasks which invoke ssh for one time commands. 
sshfs mounts in the workspace directories. 

Potential Use Cases:
Being able to configure something like a Remote Host Task could be useful for specifying jobs to be queued on these systems. ie building or starting a remote debug server.

Being able to open multiple remotes in the same workspace could also leverage the excellent copy paste/file drag functionality you already have between host/remote systems. It would be killer to be able to drag files between multiple remotes in the same window. As a common use case of mine is moving diffs via scp. 

I can also see use cases for things like microservices where a user might have source code for multiple services that they are editing. You could define tasks which depend (pre/post) tasks on certain parts of the services running for your local deployment.  
ie. I want to start a remote gdb session.  `gdb-server` depends `build` depends `sync diff`

Another use case is using the remote extension as a log viewer. With multiple workspace hosts defined, you could have a bunch of microservices/build tree log directories essentially symlinked right next to your source code. Then when you pull up a log file and follow a filepath reference jumping to the file in the worktree, not the build tree. 

Issue #1460, has similar requests but I felt the cases I have provided may be significantly different enough to warrant a new request. 
Let me know if this sounds reasonable or not. I would be very excited with just having multi-root remote workspaces just in the fact that I could hand off a new hire my workspace file and have a consistent remote workspace between us.

**Comment by roblourens** [comment]
Thanks for the suggestion. This has come up before and would be cool but unfortunately the way our architecture works, this isn't really feasible currently. https://github.com/microsoft/vscode-remote-release/issues/1460 would probably have the same basic architecture pre-reqs, but I'm going to close this
