### ISSUE TITLE
Support ARMv6

### ISSUE THREAD

**Issue by jpitz31** [microsoft/vscode-remote-release#9754]
Type: <b>Feature Request</b>

Many raspberry pi SOC's are based on older chip technology.  For example the Raspberry Pi Zero support the ARMv6.  

It would be nice to port the Remote SSH extension to the ARMv6 chip architecture.

If you do not have the resources to port the extension, please consider releasing the extension to open source so we can port the extension ourselves.

I think there are still many earlier models of raspberry pi's out there that people would be able to take advantage of this nice extension.

Thanks for the consideration.

Joe Pitz

Extension version: 0.110.1
VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:26:18.741Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/669
