### ISSUE TITLE
tunnel can not connect to even though the tunnel status is running 

### ISSUE THREAD

**Issue by habaohaba** [microsoft/vscode-remote-release#9757]
- VSCode Version: 1.88.0 (Universal)
- Local OS Version: mac os 14.0 (23A344)
- Remote OS Version: windows 11
- Remote Extension/Connection Type: tunnel

- Logs:
<img width="875" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/34515931/0c9eeecb-9679-4618-9843-a11819458389">

Steps to Reproduce:

1. open tunnel access on remote machine, connect to tunnel in local machine successfully
2. next day, when i reopen visual code in local machine, it just can not connect to remote machine, even though the tunnel status is running

**Comment by connor4312** [comment]
Can you share the `--verbose` logs from the tunnel's host side as well?

**Comment by habaohaba** [comment]
![image](https://github.com/microsoft/vscode-remote-release/assets/34515931/2c908c8c-95fc-4fdd-b936-37f6c3882ab2)
How can i get a more verbose log in host side, it seems like there is no cli command to show log.
This is the output in my host side tunnel service panel in visual code.

**Comment by connor4312** [comment]
The CLI argument is `--verbose`, so `code tunnel --verbose`

**Comment by habaohaba** [comment]
![image](https://github.com/microsoft/vscode-remote-release/assets/34515931/6d1828f0-6f7f-47c3-9d3d-35e76d736ad5)

**Comment by connor4312** [comment]
It looks like your credential expired or was invalidated, you may need to run `code tunnel user login` again

**Comment by habaohaba** [comment]
<img width="192" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/34515931/afe272c5-f2de-4f70-a2a4-b3cfd062a5d7">
Today, I restart the tunnel and it can only get started in visual code gui mode but not in cli way. I connect to this reopen tunnel and work a while, but suddenly it crash and the status panel in remote explorer say it is offline which I have no idea why. 
To be honest, visual code tunnel feature is such a unstable functionality for me, I basically need to restart it everyday and it still accidentally crash sometime.

**Comment by connor4312** [comment]
> can only get started in visual code gui mode but not in cli way

Please share the output if you hit this, I'm not sure what the issue is without the output of `code tunnel --verbose`
