### ISSUE TITLE
issue when trying to connect on remote host with docker 25 locally 

### ISSUE THREAD

**Issue by palibert66** [microsoft/vscode-remote-release#9760]
Type: <b>Bug</b>

Erreur pendant l'exécution de la commande remote-containers.attachToRunningContainerFromViewlet : Command failed: docker inspect --type container c40118331d1fe0fc98b5bb59ff02b192068502b83bb48441838f12aa71fbc41b. Probablement due à l'extension qui contribue à remote-containers.attachToRunningContainerFromViewlet.

When I try to run the command manually (docker log ...) it runs as expected

Extension version: 0.354.0
VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:28:09.495Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|9, 6, 5|
|Memory (System)|64.00GB (20.35GB free)|
|Process Argv|--crash-reporter-id d118bbc0-5375-4cf1-a618-f7603585a015|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
9b8hh234:30694863
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d6fi2104:30959263
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30993540
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
g1icg217:30999571
vstestc:31012532

```

</details>

**Comment by chrmarti** [comment]
Merging with https://github.com/microsoft/vscode-remote-release/issues/9759
