### ISSUE TITLE
[Remote-SSH Bug]: remote.SSH.useExecServer settings description is broken

### ISSUE THREAD

**Issue by danielhass** [microsoft/vscode-remote-release#9766]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

In the VSCode preferences/settings UI the description of the setting `remote.SSH.useExecServer` should be displayed correctly. 

### Steps To Reproduce

1. Go to Preferences > Settings
2. Search for `remote.SSH.useExecServer`

You will now see a malformed string as the settings description:

![image](https://github.com/microsoft/vscode-remote-release/assets/456036/623af092-5ce1-4dcf-8079-e753d801fb38)

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[Not Relevant]
```

</p>
</details>

### Anything else?

This might be caused by a typo in the settings template string?

%setting.us**s**eExecServer.description%

**Comment by bamurtaugh** [comment]
@connor4312 I'm able to repro this one.

**Comment by connor4312** [comment]
Whoops. Maybe vsce should validate those strings 🤔

**Comment by joaomoreno** [comment]
I still see this on the Shared process logs: 
<img width="1476" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/22350/b4bfc1bf-b148-4e27-9bc8-7f5bb87eccc1">

Are we missing a release @connor4312 ?

**Comment by mihailim** [comment]
For what it's worth, this is _still_ happening as of now...

**Comment by enzedonline** [comment]
I see this in the renderer log also:
```
2024-06-10 11:37:32.609 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
```
