### ISSUE TITLE
Ability to disable automatic start of Docker

### ISSUE THREAD

**Issue by npalmius** [microsoft/vscode-remote-release#9773]
The following was added in the March 2024 (version 1.88) VS Code release:

> ### Automatic start of Docker
> When the Dev Containers extension detects that Docker is not running on Windows or Mac, it now checks for and automatically starts Docker Desktop. This should avoid a common manual step after rebooting your machine.

I often use multiple VS Code instances - some using dev containers, some not.

Docker can be very resource intensive (especially because I have some large docker compose projects that start automatically when Docker starts), so sometimes I just want to open VS Code without Docker running so that I can use the VS Code instances that aren't using dev containers. The ones that need dev containers fail to load, but that's ok for me as I just need to start Docker then reload the window if I want to use them (this way I can also let the docker compose projects start before starting the dev container(s) that I want).  It also means that I can load just the specific dev container(s) that I need for whatever I'm doing - I may have had other dev containers open when I last exited VS Code that I don't want to load.

However, after this update Docker automatically starts when starting VS Code. This starts some large docker compose projects, and then loads _all_ the dev containers that I happened to have open when I last exited VS Code. If I'm not plugged in, this is particularly undesirable.

So it would be great to have an option to disable the automatic start of Docker. I have looked through the Dev Containers settings and couldn't find anything - apologies if I missed it.

**Comment by devdiogenes** [comment]
It often happen to me, when I open vscode after closing in a docker project. The vscode tries to open inside container, and start it even if I don't want to use

**Comment by joshspicer** [comment]
Looking into adding a setting for the work that was done here: https://github.com/microsoft/vscode-remote-release/issues/9687

**Comment by joshspicer** [comment]
This shipped in `v0.382.0 (pre-release)` with a new setting.  Please let us know if the change helps!



![Image](https://github.com/user-attachments/assets/99f5d2a4-a32c-41e8-af55-1c16473ca937)
