### ISSUE TITLE
`vscode-server` remote SSH memory leak

### ISSUE THREAD

**Issue by binaryfire** [microsoft/vscode-remote-release#9778]
Hi guys

I've got several different remote SSH folders pinned to VS Code in my task bar. They're all on the same host. I'm experiencing the following issues:

- When I open each folder a separate `vscode-server` instance seems to be launched on the host, which results in very high memory usage. 
- When I close the IDE windows, the host memory usage doesn't decrease
- When I open the same folders again, memory usage increases

So after opening and closing the same remote folders a few times, the remote host runs out of memory and needs a reboot. This screenshot is from the remote host. No VS Code IDE windows are open but `vscode-server` is using 8GB RAM.

This screenshot was after opening and closing the same 5 remote SSH folders 3-4 times:

![image](https://github.com/microsoft/vscode-remote-release/assets/5361908/41363dfa-2635-495e-bea9-6208c11a4efb)

**Comment by binaryfire** [comment]
Just rebooted and tested with opening and closing a single folder multiple times. The same problem is occurring - additionally memory is used each time and is not released when the ide is closed.

**Comment by arfianadam** [comment]
I encounter this as well. Closing an editor (connected to `code-server`) does not stop spawned processes. Immediately re-opening after closing the editor will spawn yet another set of processes, repeat and this doesn't end until your system runs out of memory. I had to manually kill all those process manually for the time being.

**Comment by openscript** [comment]
I've had similar issues. From another issue, which I can not recall right now, I learned that the Follow Symlinks settings caused the issue.

![image](https://github.com/microsoft/vscode-remote-release/assets/1105080/7220bc75-3fa9-42ad-a692-95e57fa1e815)

**Comment by AndyMGar** [comment]
Yes, same issue for me. An ever increasing number of vscode-server processes consuming an ever increasing amount of memory until the inevitable happens.

**Comment by AndyMGar** [comment]
> I've had similar issues. From another issue, which I can not recall right now, I learned that the Follow Symlinks settings caused the issue.
> 
> ![image](https://private-user-images.githubusercontent.com/1105080/324372354-7220bc75-3fa9-42ad-a692-95e57fa1e815.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNDYxMjEsIm5iZiI6MTcxNDA0NTgyMSwicGF0aCI6Ii8xMTA1MDgwLzMyNDM3MjM1NC03MjIwYmM3NS0zZmE5LTQyYWQtYTY5Mi05NWU1N2ZhMWU4MTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjVUMTE1MDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjAyNTU3YjFhODVjNThjMmM3NzJlYjNmZGRjMDhiZDBiOWI2MmVjNGJiY2JkNjJjMTAzN2EwYTg1Y2RiY2U4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oI2TC15kvTSPnUYx0U8ZYPqyfgDHMMgyJdz2ioUtHHw)

I think this may be related to high CPU usage rather than processes that never get killed.

**Comment by roblourens** [comment]
Can you share the full command line arguments of the processes that appear to be leaked? If the vscode window exits cleanly, its associated processes should be shut down on the remote (except for the server process which is lives a little longer and is shared with other connected windows)

**Comment by AndyMGar** [comment]
Sure. I have taken some time to look at this more carefully as it is hard to see the wood for the threes, and as you say some processes live a little longer than others. 

In summary what seems to be happening is that every time I close a vscode window, after making sure I close the remote-ssh session first (I am assuming this is the cleanest way to exit) I am left with a set of node processes. When I open a new remote-ssh session some of these processes get replaced with new ones and when I close down again some remain. 

But what seems odd is that one node process never gets removed or replaced, just recreated every time. This is the "fileWatcher" process. This process, and its 11 threads, gets created for each new VSCode remote-ssh session and after existing cleanly remains. On starting a new VSCode remote-ssh a new "fileWatcher" process and a further 11 threads get created. And so on and so on each time I close and start anew.

I have full details in the attached file in case that helps.

[VSCodeRemoteSSHIssuepdf.pdf](https://github.com/microsoft/vscode-remote-release/files/15138069/VSCodeRemoteSSHIssuepdf.pdf)

**Comment by Ccccx159** [comment]
I encountered the same issue using VS Code version 1.88.1 and Remote SSH version 0.110.1. When I close the remote connection in VS Code and then close the VS Code window, the fileWatcher process on the remote server does not stop. Upon reopening VS Code and establishing a remote SSH connection again, a new fileWatcher process is created on the server, resulting in two fileWatcher processes. After repeating this process multiple times, file handles are depleted, and VS Code displays the message 'Visual Studio Code is unable to watch for file changes in this large workspace' (error ENOSPC).

![2024-04-30_134825](https://github.com/microsoft/vscode-remote-release/assets/35327600/04812a15-db05-463b-8203-4cdf9a239582)

**Comment by roblourens** [comment]
@bpasero ?

**Comment by bpasero** [comment]
Sounds a lot like https://github.com/microsoft/vscode/issues/211462, needs investigation.

**Comment by roblourens** [comment]
I'm going to merge it into https://github.com/microsoft/vscode/issues/211462, there's some more detail there
