### ISSUE TITLE
"Opening Remote..." forever.

### ISSUE THREAD

**Issue by vini2003** [microsoft/vscode-remote-release#978]
### Information:

- WSL system: Ubuntu 18.04.02 LTS
- VSCode Version: 1.37.0 (Insider)
- Local OS Version: Windows 10 May Update (1903)
- Remote OS Version:: Windows 10 May Update (1903)
- Remote Extension/Connection Type: SSH

### Path to issue:

1. Install Visual Studio Code Insiders (1.37.0) and Remote-SSH (0.44.2)
2. Install OpenSSH on both machines
    1. On the host machine, OpenSSH Server was installed through PowerShell `Get-WindowsCapability`, which says it is installed, alongside OpenSSH Client:

        ```
        PS C:\WINDOWS\system32> Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'

        Name  : OpenSSH.Client~~~~0.0.1.0
        State : Installed

        Name  : OpenSSH.Server~~~~0.0.1.0
        State : Installed
        ```

    2. On the client machine, OpenSSH Server was installed manually using [this process](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH) due to issues with installing via PowerShell, which were solved after updating Windows. Since the issue persisted, I then reinstalled OpenSSH through PowerShell `Get-WindowsCapability`, removing the previous OpenSSH folder from PATH. PowerShell also says it is installed:

        ```
        PS C:\Users\vini2003\Desktop> Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'

        Name  : OpenSSH.Client~~~~0.0.1.0
        State : Installed

        Name  : OpenSSH.Server~~~~0.0.1.0
        State : Installed
        ```

    Both machines had their keys generated with `ssh-keygen -t rsa -b 4096`, and both public keys were moved to `authorized_keys` in their respective machines. They are in the same local network, albeit one of them is directly connected to a modem, and the other one is in a WiFi network from a router connected to said modem.

    Normal SSH between the machines works without any issues.

3. On the client machine's Visual Studio Code Insiders install, I press `F1`, then write `Remote-SSH: Connect to Host...`, type the host's name, `vini2003@192.168.1.7`, am asked for its password, which is entered. I am then asked for the password again, which is entered, leading to the issue: the status indicator in the bottom left stays at *"Opening Remote..."* forever.

    While this happens, the console output is [this](https://is.gd/67pQ9s).

Unsure how to proceed. After looking through most other issues here, I either missed one similar to mine, or there wasn't one.

**Comment by roblourens** [comment]
It looks like the setup process finished with no issues, but vscode but be having trouble actually connecting to the server that we installed. Can you check for errors in the developer tools on the window? (Help > Toggle developer tools)

**Comment by vini2003** [comment]
Sorry for the delay, real life happened.

My network is running exceptionally slowly randomly as of late, so I get two `[Intervention] Slow network is detected.` warnings in the console, then `[Extension Host] debugger listening on port 25826`. After that, there are no more events logged on the console - this, of course, being developer tools on the "Opening Remote" VSCode instance.

**Comment by roblourens** [comment]
It sounds like you are saying that you were able to connect but then it stops working later? Is that right?

**Comment by vini2003** [comment]
Excuse the wording, I meant to say that in Console at Developer Tools, only those warnings/errors are logged. VSCode itself continues to state "Opening Remote...".

**Comment by roblourens** [comment]
Can you try this with the nightly SSH extension? (uninstall the stable version first)
