### ISSUE TITLE
Input in Terminal not working while in Dev container

### ISSUE THREAD

**Issue by alexandr-osprey** [microsoft/vscode-remote-release#9784]
Type: <b>Bug</b>

I use podman instead of Docker.
Steps to reproduce:
1. Create python dev container
2. Try to select the image in terminal

Expected result: image in terminal selected, input in terminal works
Actual result: terminal looks active, but doesn't respond to input from keyboard. Selection and scrolling works fine.

![Recording2024-04-12at14 10 19-ezgif com-cut](https://github.com/microsoft/vscode/assets/12857502/80ad9a0c-cc13-482e-8129-909e6018381f)

Adding or removing the setting "terminal.integrated.shell.linux" doesn't change the outcome. Outside of dev container terminal works fine.

settings.json
```
{
    "window.titleBarStyle": "custom",
    "security.workspace.trust.untrustedFiles": "open",
    "dev.containers.dockerPath": "podman",
    "docker.dockerPath": "podman",
    "git.autofetch": true,
    "git.confirmSync": false,
    "terminal.integrated.shell.linux": "/bin/bash"
}
```

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:34:12.840Z)
OS version: Linux x64 6.8.4-200.fc39.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12500H (16 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 1, 0|
|Memory (System)|15.35GB (10.52GB free)|
|Process Argv|--unity-launch --crash-reporter-id c726daa5-8812-48d4-88bd-38184708297f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
python-environment-manager|don|1.2.4
gitlens|eam|14.9.0
csdevkit|ms-|1.4.29
csharp|ms-|2.23.15
vscode-dotnet-runtime|ms-|2.0.3
vscodeintellicode-csharp|ms-|2.0.25
python|ms-|2024.4.1
vscode-pylance|ms-|2024.4.1
remote-containers|ms-|0.354.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
chatgpt|tim|1.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572
9c06g630:31013171

```

</details>

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/9748.

(We don't connect the keyboard events to the build command.)
