### ISSUE TITLE
COMPOSE_PROJECT_NAME in .env or ENV is ignored

### ISSUE THREAD

**Issue by volvofixthis** [microsoft/vscode-remote-release#979]
- VSCode Version: 1.36.0
- Local OS Version: Arch
- Remote OS Version: Docker image python:3.5
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Set COMPOSE_PROJECT_NAME to your needs.
2. Open folder in container.
3. Check that --project-name {folder_name} is passed to docker-compose executable.

Expected beahaviour:
VSCode do not pass --project-name by itself. Also it will be nice to have parameter like project_name in .devcontainer.json.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by AGeekInside** [comment]
Has anyone found a work around to this? I am seeing the same issue.

It looks like there is some code in the actually passing in a '--project-name' flag to the docker-compose command when it is executing the 'up' command. Whatever logic is doing that is definitely not respecting the convention of the COMPOSE_PROJECT_NAME setting.
