### ISSUE TITLE
Receiving Interactive authentication is needed when running az login on Remote Tunnel

### ISSUE THREAD

**Issue by MaurGi** [microsoft/vscode-remote-release#9794]
- VSCode Version: 1.88.1
- Local OS Version: Windows 11 or Mac (Darwin arm64 23.4.0), both reproes
- Remote OS Version: Ubuntu 22.04.3 LTS
- Remote Extension/Connection Type: Containers/WSL/Server Remote Tunnel to WSL

- Logs:

Steps to Reproduce:

1. Have an Azure DevBox on the Microsoft.com domain (that requires dual factor auth)
2. Install WSL (Ubuntu)
3. Inside WSL run vscode tunnel
4. Connect with Tunnel from a remote VSCode
5. run 'az login --tenant microsoft.com'
6. Browser will pop out but the flow will not finish as redirecting to localhost will fail (the port is not being redirected)
7. run 'az login --tenant microsoft.com -o none --use-device-code' auth with the browser on your machine
8. run 'az ad app list -o json', see error:
```
AADSTS530003: Your device is required to be managed to access this resource. Trace ID: 4b1f12ef-b632-41d7-bb44-9e5fb1b73800 Correlation ID: 81d77274-e871-406e-a2b8-edb787c2456a Timestamp: 2024-04-17 19:55:56Z
Interactive authentication is needed. Please run:
az login --scope https://graph.microsoft.com//.default
```

Does this issue occur when you try this locally?: Yes/No No - if I remote into the DevBox it works
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No Yes

**Comment by connor4312** [comment]
Seems like the bug may be automatic port fowarding not working in step 6

**Comment by alexr00** [comment]
@MaurGi can you go through your first 4 steps, then share the value of these two settings: `remote.autoForwardPortsSource` and `remote.autoForwardPorts`?

**Comment by MaurGi** [comment]
@alexr00 :
- When running this, the local browser tries to go to http://localhost:43219/
- "remote.autoForwardPortsSource": "hybrid"
- "remote.autoForwardPorts": true

**Comment by alexr00** [comment]
In this case, the issue is that the local address is not actually `localhost`. In this case, the port is still forwarded, but we do not update the original URL to include the forwarded address. I think Azure does a check to make sure the original URL has not been tampered with, which is why we cannot update it.

**Comment by MaurGi** [comment]
so you are saying there is no solution to this @alexr00 ? I have to remote into the target machine to perform this type of authentication? thx
