### ISSUE TITLE
Error: Unable to install extension 'ms-vscode-remote.remote-ssh' as it is not compatible with VS Code '1.84.2'

### ISSUE THREAD

**Issue by shaocongliang** [microsoft/vscode-remote-release#9795]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects unsuccessfully

### Expected Behavior

Extension install successfully.

### Steps To Reproduce

1. Install VSCode 1.84.1
2. run `code --install-extension ms-vscode-remote.remote-ssh-0.112.2024040915.vsix`

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
Error: Unable to install extension 'ms-vscode-remote.remote-ssh' as it is not compatible with VS Code '1.84.2'.
    at X.install (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:50:4615)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async y.g (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:28:299)
    at async /usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:27:16416
    at async Promise.all (index 0)
    at async y.installExtensions (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:27:16345)
    at async /usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:50:25118
    at async Object.ge [as main] (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:50:28802)
    at async A (/usr/share/code/resources/app/out/vs/code/node/cli.js:31:22743)
Failed Installing Extensions: file:///home/${username}/Downloads/ms-vscode-remote.remote-ssh-0.112.2024040915.vsix
```

</p>
</details>

### Anything else?

Alternative solutions: Upgrade my OS version or Upgrade to lastest vscode are less realistic. Because it's a work machine assigned by the company.
My CentOS Version: 
```bash
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
```
Latest vscode(1.88.1) can't installed in this OS becasue glibc version.

## What I hope
Providing a way to download older version Remote-SSH extension.

**Comment by bamurtaugh** [comment]
Thanks for filing!

> Providing a way to download older version Remote-SSH extension.

You can right-click on any extension in the Extensions view and install an older version:

![Image](https://github.com/microsoft/vscode-remote-release/assets/25310137/be59b2b2-c811-4d17-9e09-afc4858e3a31)

As a related note: the version of the VS Code Server used by the remote extensions needs to be kept in sync with the version of VS Code. More info: https://code.visualstudio.com/docs/remote/faq#_can-vs-code-server-be-installed-or-used-on-its-own.

If this doesn't address your issue, please let me know!

**Comment by shaocongliang** [comment]
Thanks, it helps a lot.
