### ISSUE TITLE
feature request - allow me to open local file

### ISSUE THREAD

**Issue by ArrrNeo** [microsoft/vscode-remote-release#980]
Hi VSCode team,

My work involves working on code base on remote server but I have local txt files with tips and tricks. I want to be able to open both in single VSCode window. When I open a local file on window that is working on remote server, it simply opens new VSCode window rather than opening in same window.

This is undesirable behavior, I dont see the practicality of behavior and I am sure lots of developer who work on remote servers have local txt files with their own tips and tricks or commands saved.

I hope this will be fixed. By the way great work on this extenstion I was really looking for something like this for long time.

Thanks and Regards
Naveen Rawat

**Comment by roblourens** [comment]
Can you explain how you are trying to open the file? You should be able to click "show local" in the open file prompt to get a local file picker, or if you drag the file onto the remote window, it should open in that window.

**Comment by ArrrNeo** [comment]
Thanks for responding @roblourens 

I have tried "show local" and as well as open from File->Open or File->Open Recent menu options, in all three cases local file is opened in new VSCode window.

Only in drag and drop way I can open local file in same VSCode window. However this is not the ideal way for me to open a file, for I would have to open the file location in MacFinder every time. I think you would also agree that this is not a very practical solution.

**Comment by roblourens** [comment]
What is your local OS and VS Code version?

**Comment by ArrrNeo** [comment]
MacOS Mojave, 10.14.5
VSCode - 1.36.1
2213894ea0415ee8c85c5eea0d0ff81ecc191529
2019-07-08T22:48:28.193Z

**Comment by ArrrNeo** [comment]
CPUs | Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: enabledoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | 1, 1, 1
Memory (System) | 16.00GB (8.09GB free)
Process Argv |  
Screen Reader | no
VM | 0%

**Comment by ArrrNeo** [comment]
Extension | Author (truncated) | Version
-- | -- | --
autoconf | mae | 0.1.0
yang | mar | 0.1.3
remote-ssh | ms- | 0.44.2
remote-ssh-edit | ms- | 0.44.2
remote-ssh-explorer | ms- | 0.44.2
code-gnu-global | aus | 0.2.2
githistory | don | 0.4.6
gitlens | eam | 9.9.1
cpptools | ms- | 0.24.1
vscode-hexdump | sle | 1.7.2
cmake-tools | vec | 1.1.3

**Comment by roblourens** [comment]
Hey @alexr00 is it by design that if I open a file through "Show Local", it opens the file in a different window instead of opening it in that remote window?

**Comment by alexr00** [comment]
It is by design. @aeschli how would you feel about having it open in the same window?

**Comment by aeschli** [comment]
Yes by design we avoid mixing local and remote files in the same folder.
The problem the file will get limited language support. E.g. no rich typescript support.

IMO we can allow it for single files, but we need to test it.

**Comment by rlevitin** [comment]
I have a related idea, not sure if it's worth a separate ticket/issue. I discuss it at the bottom here: https://github.com/microsoft/vscode-python/issues/6851

My use case is using VSCode with Remote-SSH for interactive data science work with Python and Markdown on a remote machine. There are times I am trying to display an image with markdown that is located in the working directory on the remote filesystem, but it cannot be rendered locally.


![image](https://user-images.githubusercontent.com/1235172/63289514-51cbd180-c28d-11e9-9b66-b97c814d8a8b.png)

**Comment by aeschli** [comment]
@rlevitin Yes, that's not the same as the current request, please file a new issue.

**Comment by rlevitin** [comment]
Sorry, I'm having a lot of trouble figuring out which project/team this issue belongs to. I realized when opening the new issue that I actually have the same problem if running locally, so I'm going to take it back to the VS-Code python extension for further evaluation.

Thanks!

**Comment by Chuxel** [comment]
@rlevitin Np! Commented over in the Python issue as well since on the surface the behavior described should work --- the fact that you see it locally seems to confirm it's not remote related, but we'll see where it goes.

**Comment by alexr00** [comment]
The file dialog service is actually already passing through `forceNewWindow` as false. It looks like the window service has the new window decision.

**Comment by alexr00** [comment]
It seems to work without issue. After I merge the change, if you want to go back to the old behavior you can set `"window.openFilesInNewWindow": "on"` in your workspace settings.

**Comment by ArrrNeo** [comment]
Hi Team,

how can i get this update, seems like my VScode is latest, yet changing this setting is not helping at all.

details:

Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by alexr00** [comment]
This change is in the September 2019 milestone (see milestone off to the right). We have not released yet. You can get the change before we release by installing insiders.

**Comment by ArrrNeo** [comment]
thanks. got it

**Comment by alexr00** [comment]
Local files always used to open in a new window. Things to verify:
- Setting `"window.openFilesInNewWindow": "on"` keeps the old behavior of always opening local files in a new window
- Verify that only files open in the same window, not folders
- Verify that if you have the simple file dialog enabled 	`"files.simpleDialog.enable": true,` and you open a file it follows the regular old window sharing behavior.

**Comment by misolori** [comment]
- I am connected via SSH and have set `window.openFilesInNewWindow` to `on` and opening local files and folders still open in the same window, so I would say this setting is being ignored.
- ✅ Files open in the same window
- This also doesn't work because of the first point above

Also, I'm assuming that `new window` means not re-using the existing window.

**Comment by alexr00** [comment]
It looks like there is a bad interaction between settings. If you have the simple file dialog enabled as your regular file picker then openFilesInNewWindow  is ignored.
