### ISSUE TITLE
Remote-SSH is stuck in an infinte nslookup loop

### ISSUE THREAD

**Issue by grawity** [microsoft/vscode-remote-release#9801]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.87.1 
- OS Version: Windows 11

I'm aware of "Issues caused by an extension need to be reported directly to the extension publisher", but... Microsoft is the extension publisher in this case.

Steps to Reproduce:

1. Have an `~\.ssh\config` with these contents:

    ```
    Host foohostname
        # At least one host section needed; can remain empty.
    
    Host *
        # Canonicalization needs to be enabled.
        CanonicalizeHostname yes
        # More than one domain needs to be specified to trigger the issue.
        CanonicalDomains example.net example.com
    ```

2. Invoke "Remote-SSH: Connect to host..." or "Remote-SSH: Connect current window to host..."

4. The extension never activates. Tools such as ProcMon or ProcExp show that it keeps spawning `nslookup *.example.net` in a loop, the exact same command line repeating infinitely until I close VSCode.

(Upon inspecting extension.js, it seems like the extension looks for output `/server can't find/`, but nslookup doesn't output that exact text here – it outputs `HomeGW.home.arpa can't find` instead. Not sure whether that's related to the infinite loop.)

This is a new issue; it happens with Remote-SSH `v0.109.0` and with `v0.110.2024030815 (pre-release)`, but it used to work 2-3 months ago.

**Comment by joshspicer** [comment]
This should be fixed in the upstream package that is used here and was never closed out. Please re-open if still able to reproduce
