### ISSUE TITLE
Duplicate `CHANGED` events on file save

### ISSUE THREAD

**Issue by klswn** [microsoft/vscode-remote-release#9805]
Apologies if this is the wrong place to raise this. I suspect this is a VSCode issue but I can't reproduce without enabling the dev container extension. It looks like VSCode's file watcher is firing duplicate `CHANGED` events on save when running in a Debian (bullseye) dev container. We're also using Parcel's watcher to build our front end application so this results in two re-builds any time a file is changed. Adding and deleting files results in a single event as expected.

I may be missing something with how the volumes in our Dockerfile affect the underlying `inotify` events. Any help would be appreciated.

- VSCode Version: 1.88.1
- Local OS Version: MacOS 12.6.6
- Remote OS Version: Debian GNU/Linux 11 (bullseye)
- Remote Extension/Connection Type: Containers

- Logs: (single save event)

```
2024-04-22 15:38:22.506 [trace] [File Watcher (parcel)] [CHANGED] /workspace/src/index.js
2024-04-22 15:38:22.563 [trace] [File Watcher (parcel)] [CHANGED] /workspace/src/index.js
2024-04-22 15:38:22.581 [trace] [File Watcher (parcel)]  >> normalized [CHANGED] /workspace/src/index.js
```

Steps to Reproduce:

I set up a minimum reproducible example with instructions in the README [here](https://github.com/klswn/watcher-example)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bpasero** [comment]
That is expected and thus we fold events together into 1 over 50ms time span.
