### ISSUE TITLE
Remote tunnel -  "warn error access singleton, retrying: the process holding the singleton lock file"

### ISSUE THREAD

**Issue by j-silv-ti** [microsoft/vscode-remote-release#9806]
I ran into the same issue that was referenced here. 

```
warn error access singleton, retrying: the process holding the singleton lock file (pid=PID_NUM) exited
```

_Originally posted by @kissdan1 in https://github.com/microsoft/vscode-remote-release/issues/8973#issuecomment-1743712610_

My fix was to delete the .vscode and .vscode-server folders. 

```
rm -rf ~/.vscode ~/.vscode-server
```

Sorry if I shouldn't of created a new issue. Since the previous one was locked I couldn't comment on it.

**Comment by j-silv-ti** [comment]
> Does the tunnel start after you see that log message, or is it stuck in that state / in a loop?

Stuck in that state, in a loop. That message keeps repeating over and over again.

**Comment by jmorim** [comment]
> I ran into the same issue that was referenced here.
> 
> ```
> warn error access singleton, retrying: the process holding the singleton lock file (pid=PID_NUM) exited
> ```
> 
> _Originally posted by @kissdan1 in [#8973 (comment)](https://github.com/microsoft/vscode-remote-release/issues/8973#issuecomment-1743712610)_
> 
> My fix was to delete the .vscode and .vscode-server folders.
> 
> ```
> rm -rf ~/.vscode ~/.vscode-server
> ```
> 
> Sorry if I shouldn't of created a new issue. Since the previous one was locked I couldn't comment on it.

note that you should back up your machine settings if deleting .vscode-server.

Not that I would forget to do that. No way.

**Comment by j-silv-ti** [comment]
Actually, a much simpler solution is to delete the lock file that is located in the `.vscode` folder. This was mentionned in #2507.

```
rm ~/.vscode/cli/tunnel-stable.lock
```
