### ISSUE TITLE
Remote tunnel - "code" command on remote server doesn't open file in local VS code

### ISSUE THREAD

**Issue by j-silv-ti** [microsoft/vscode-remote-release#9807]
- VSCode Version: 1.88.1 (also tested with VS code insiders)
- Local OS Version: Windows 10
- Remote OS Version: RHEL 7
- Remote Extension/Connection Type: Remote tunnel

- Logs: N/A

Steps to Reproduce:

1. Download the code CLI on the remote machine (unpack method as [described here](https://code.visualstudio.com/docs/remote/tunnels))
2. Create a tunnel on the remote machine (`./code tunnel`)
3. On local machine, connect to the tunnel
4. In remote window, open integrated terminal and try opening up a file (`./code filename`)

Resulting output:

```
No installation of Visual Studio Code stable was found.
Install it from your system's package manager or https://code.visualstudio.com, restart your shell, and try again.                                                                                                                              If you already installed Visual Studio Code and we didn't detect it, run `code version use stable --install-dir /path/to/installation`  
```

This is in reference to my [Stackoverflow post](https://stackoverflow.com/q/78356507/24509529) @starball5

As per this [user's comment](https://github.com/microsoft/vscode-remote-release/issues/9251#issuecomment-1834624215), it seems that trying to run the `code` command in an integrated terminal while connected via a remote tunnel should open up the file in the local VS code UI. However, when I try doing this, it just pops up with the above error. 

I just installed the code CLI as explained in the remote tunnel documentation. Is this expected behavior?

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-remote-release/issues/4451
