### ISSUE TITLE
VS Code Python + WSL: Remote extension host terminated unexpectedly 3 times within the last 5 minutes

### ISSUE THREAD

**Issue by appaie** [microsoft/vscode-remote-release#9808]
Type: <b>Bug</b>

Hey everyone,

I was just about to continue working on my project when I encountered the following error:
"Remote Extension host terminated unexpectedly 3 times within the last 5 minutes"

Now, I've lost access to the repository. Has anyone else experienced this issue before?

I think this might have something to do with sudden bugs appearing in the extensions.

That's the problem; I haven't changed any login credentials at all.

Everything was running smoothly until I returned after the program had been running for 1 hour, and this error occurred.

It would be a shame if this issue hindered me for the last 2 weeks... quite frustrating 😅

Any help or advice would be greatly appreciated!

I've already tried disabling extensions one by one, but unfortunately, it didn't solve the problem. I gave it another shot, but still no luck.

I tried cloning the entire repository again, uninstalling all extensions, and deleting the code folder in AppData. Then, I only downloaded the WSL extension to open the code from WSL. Everything seemed to work fine until I opened a .py file from the project in the VS Code editor, after which it completely lost connection.

Extension version: 2024.4.1
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Connection to 'wsl+Ubuntu' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.45GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/tim/Test --remote=wsl+Ubuntu --crash-reporter-id 88ac5fd2-3d52-4849-8218-a03f5f5efdff|
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+Ubuntu' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
chatpanelc:31018788
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31022790

```

</details>

**Comment by chrmarti** [comment]
@appaie Is this still an issue?
