### ISSUE TITLE
[Remote-SSH Bug]: Failed to run `uname -rsv` command in remote windows server

### ISSUE THREAD

**Issue by main-voice** [microsoft/vscode-remote-release#9812]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Connect over SSH to a Windows machine.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

### Anything else?

The error is quiet strange for me. I update the powershell config in windows server, and the client extension failed to connect the server. Leaving a long time waiting, and finally a window saying: "can not establish connection"

I resloved the issue from https://github.com/microsoft/vscode-remote-release/issues/8617, but I can't find any useful debug information from the extension log. 

So is it possible to check the return code when trying to run `uname -rsu` command in a windows server?

**Comment by joshspicer** [comment]
Thank you for taking the time to open an issue.  Could you please share your logs (`> Remote-SSH: Show Log` in the command palette) after reproducing the issue?
