### ISSUE TITLE
Option to not overwrite git credential helper when attaching to a running container

### ISSUE THREAD

**Issue by sam-mfb** [microsoft/vscode-remote-release#9815]
When attaching to a running container, it appears that this extension will always clobber the helper contained in the container's .gitconfig file by calling something like:

```
git config --system --replace-all credential.helper '!f() { /home/vscode/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39/node /tmp/vscode-remote-containers-426405cb-e571-47c7-910e-e852e07fec6f.js git-credential-helper $*; }; f'
```
It would be nice if there was an option to disable that so that one could use VS Code to work in a Docker container, but still use the credential helpers already set up in that Docker container (i.e., NOT use the extension's credential forwarding capabilities).

**Comment by chrmarti** [comment]
There is a user setting to turn this off:
<img width="464" alt="Image" src="https://github.com/user-attachments/assets/949e11c1-3886-43cb-ac63-87b921937a72" />
