### ISSUE TITLE
[Remote-SSH Bug]: failed to acquire lock for install. ln permission denied

### ISSUE THREAD

**Issue by Edenzzzz** [microsoft/vscode-remote-release#9817]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Of course it should connect

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
<img width="940" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/87317405/94585042-8de1-429e-8e81-72ca33008e54">```
<img width="698" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/87317405/6a461ed6-685e-47f5-86a5-6c9bcf4154c9">

</p>
</details>
```

### Anything else?

Removing ~/.vscode-server doesn't help. It reoccurs in a bit.

**Comment by Edenzzzz** [comment]
killing remote host seem to work

**Comment by joshspicer** [comment]
#Thank you for taking the time to open an issue.  Could you please share your logs (`> Remote-SSH: Show Log` in the command palette) after reproducing the issue?
