### ISSUE TITLE
Remote SSH Server doesn't get the $PATH of the host

### ISSUE THREAD

**Issue by zzecool** [microsoft/vscode-remote-release#9818]
Type: <b>Bug</b>

Remote SSH vscode server fails to get the proper path.

My proper path is :

echo $PATH
/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin

But vscode is getting the following :

echo $PATH
/volume1/homes/zzecool/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/bin/remote-cli:/usr/bin:/bin:/usr/sbin:/sbin

This use to work fine but started happening out of nowhere.
Killing the remote server and relog didnt solve the problem.

Extension version: 0.110.1
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (0.98GB free)|
|Process Argv|--crash-reporter-id 2c283143-7671-4204-b811-c418f7c5b9e6|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
jchc7451:30973076
gee8j676:31009558
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31022790

```

</details>

**Comment by zzecool** [comment]
I found that this was happenig in the past 

https://github.com/microsoft/vscode-remote-release/issues/6975#issue-1311358634

Killing and removing vscode Server didnt help on my situation, the new one still picks the wrong $PATH

**Comment by zzecool** [comment]
I wanna add thet if i sudo -i 

For the root user the $PATH is the proper one and everything works as expected.

Please guide me to provide you with any information as SSH is unusable as it is through vscode.

**Comment by zzecool** [comment]
Manual exporting the proper PATH  works as expected until you disconnect and reconnect.

What mechanism os vscode is setting the wrong $PATH ?

![image](https://github.com/microsoft/vscode-remote-release/assets/2816897/1362ec4b-9e33-4688-9fe7-6adcb2f1b4b3)

**Comment by zzecool** [comment]
I think i found the culprit.

I think vscode in contrast to putty for example it parses .profile and search for PATH there. 

if i add :

```
# Get the default PATH
default_path=$(getconf PATH)

# Export the default PATH
export PATH="$default_path"
```

to .profile and delete .vscode-server  and the next login it works fine.

I may not be right 100% to the conclusion. Lets hope a clever guy will jump in.

**Comment by zzecool** [comment]
I was wrong this stopped working again.

I dont tink i will be able to solve this by guessing.

**Comment by zzecool** [comment]
The culprit is that If you edit - create  the .profile file then vscode fails to get the PATH right.

If you delete .profile vscode gets the proper PATH

**Comment by joshspicer** [comment]
> If you delete .profile vscode gets the proper PATH

Is that because your `.profile` file was editing the PATH variable?  Note that it is expected that your path is prepended with `<....>/vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/bin/remote-cli` so that the `code` terminal command works as expected
