### ISSUE TITLE
Port Forwarding does not work

### ISSUE THREAD

**Issue by i-sanyam** [microsoft/vscode-remote-release#9820]
Type: <b>Bug</b>

I use remote explorer to work on a remote machine. The port forwarding works fine when a cold boot of VS Code is done. It breaks as soon as the process/server (using from .vscode/launch.json) is reloaded or the PC goes to sleep and the remote connection is established again. The process is still accessible via the remote machine's terminal but not from my local machine.

Extension version: 0.110.1
VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin arm64 22.5.0
Modes:
Connection to 'ssh-remote+test' could not be established
Remote OS version: Linux x64 5.4.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 4b6f0c5c-d8ac-41a4-aab8-ef045455d3b2|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+test' could not be established

|Item|Value|
|---|---|
|Remote|SSH: test|
|OS|Linux x64 5.4.0-29-generic|
|CPUs|AMD EPYC 7542 32-Core Processor (24 x 2894)|
|Memory (System)|172.75GB (89.33GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
8082a590:30971561
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
gee8j676:31009558
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31022790

```

</details>

**Comment by pdpark** [comment]
I have the same issue.
MacOS version: 23.4.0
Remote machine is Amazon Linux 2023
vscode version: 1.88.1

**Comment by alexr00** [comment]
Next time it happens, can you share logs from "Window", "ExtensionHost", and "SharedProcess"?

**Comment by pdpark** [comment]
ExtensionHost is not an option in my vscode Windows menu
