### ISSUE TITLE
Add a `Open to Remote Container` option from the CLI.

### ISSUE THREAD

**Issue by craigloewen-msft** [microsoft/vscode-remote-release#9824]
In the command line I want to open VS Code and have it open directly into my dev container.

Right now I do this by running code . and then clicking the "Reopen in container" button but I'd love to just open straight to the project.

Something like: devcontainer open . would address my feedback and help me out a lot.

Thanks!

Originally filed here: https://github.com/devcontainers/cli/issues/695 but moved to this repo as suggested.

**Comment by StefanBrand** [comment]
Works for me exactly as you describe:

```sh
>> devcontainer open .
[246 ms] @devcontainers/cli 0.58.0. Node.js v18.18.2. linux 6.5.0-28-generic x64.
```
