### ISSUE TITLE
How to disable the copy/paste functionality from remote (EC2 Instance - Ubuntu) to local desktop where connecting to the instance from local using VS Code Remote Server with SSH

### ISSUE THREAD

**Issue by lohithasree** [microsoft/vscode-remote-release#9826]
Using VS CODE at local desktop.

We are connecting to EC2 Instance - Ubuntu VM (Remote) from local desktop using remote-ssh extension in VS Code.

But with this my files/content of files are able to copy from remote to local.

Is there anyway to disable the copy/paste functionality with VS Code Remote server with SSH

That would be great, If anyone help us or assist to disable copy/paste functionality from remote to local

I have tried enable x11forwarding in /etc/ssh/sshd_config file and modified few of the changes. It haven't worked.

And also tried adding few settings/configuration in settings.json file for remote user.

**Expectation:**

Have to disable the copy/paste functionality from remote to local desktop from VS Coder remote server

**Comment by roblourens** [comment]
No- your remote is accessible over ssh and so content can be transferred to the local desktop. There is no way for vscode to prevent this even if the "copy" command was gone.
