### ISSUE TITLE
Problem when using wsl docker cli with dev containers 

### ISSUE THREAD

**Issue by blackberry-pieces** [microsoft/vscode-remote-release#9839]
Type: <b>Bug</b>

I have installed docker cli on windows and docker cli on wsl with same 26.0.0 version.

1) install WSL2, ubuntu 22, docker cli (https://lippertmarkus.com/2021/09/04/containers-without-docker-desktop/)

2) install wsl, Remote Development extensions

3) build or use one of linux containers into WSL

4) try to attach to one. It will use docker that installed on windows, and will not find linux container

Extension version: 0.354.0
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 5850U with Radeon Graphics      (16 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|30.83GB (7.49GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-22.04/mnt/c/Work/experimental_musl --remote=wsl+Ubuntu-22.04 --crash-reporter-id ec0f23b5-eb61-4fb9-b333-57dec71f1de7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 PRO 5850U with Radeon Graphics (16 x 1896)|
|Memory (System)|15.04GB (13.69GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
jchc7451:30973076
showvideoc:31016891
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by chrmarti** [comment]
You need to set `Dev Containers: Execute in WSL` in the user setting for the extension to always use the Docker CLI in WSL:
![Image](https://github.com/microsoft/vscode-remote-release/assets/9205389/ba11c43b-c14e-492e-aab8-5d6a9939d97f)
Additionally use `Dev Containers: Execute in WSLDistro` if the Docker CLI is in a non-default distro.
