### ISSUE TITLE
Incorrect URL percent decoding (%3 is stripped) when browser is opened remotely

### ISSUE THREAD

**Issue by mstange** [microsoft/vscode-remote-release#9841]
- VSCode Version: 1.88.1 
- Local OS Version: macOS 14.4.1
- Remote OS Version: Windows 10
- Remote Extension/Connection Type: Server (?)

### Steps to Reproduce:

1. Run a command in the remote terminal that wants to load a URL in a browser on the server. I'm using `samply load profile.json` .

### Expected results:

A browser should open on my client with that URL.

In this case the URL should have been `https://profiler.firefox.com/from-url/http%3A%2F%2F127.0.0.1%3A3001%2F3swmpxx3xvzrh762ym3gf2vyb3l8cq98cd18k0kFprofile.json/?symbolServer=http%3A%2F%2F127.0.0.1%3A3001%2F3swmpxx3xvzrh762ym3gf2vyb3l8cq98cd18k0k`

### Actual results:

A browser opens on my client with a different URL.

In this case the URL that opened instead is `https://profiler.firefox.com/from-url/httpAFF127.0.0.1A3001F3swmpxx3xvzrh762ym3gf2vyb3l8cq98cd18k0kFprofile.json/?symbolServer=httpAFF127.0.0.1A3001F3swmpxx3xvzrh762ym3gf2vyb3l8cq98cd18k0k`

The incorrect URL has all instances of `%2` and `%3` stripped from it. This breaks any URL-encoded characters.

Specifically, `http%3A%2F%2F127.0.0.1%3A3001%2F` has become `httpAFF127.0.0.1A3001F`.

---

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Didn't try

This issue does not occur if the remote server is a macOS or Linux machine. I've only seen it with the host being Windows.

**Comment by mstange** [comment]
Thanks for the quick fix!

**Comment by eleanorjboyd** [comment]
@mstange- to confirm, were you able to verify if this fix worked? Thanks!

**Comment by mstange** [comment]
I'm not sure how - is there a prerelease version that I can try?

**Comment by andreamah** [comment]
It looks like the fix was in the core product. Can you try the latest version of VS Code Insiders to see whether this is fixed?
