### ISSUE TITLE
Requests through forwarded ports only provide partial data

### ISSUE THREAD

**Issue by albertpatterson** [microsoft/vscode-remote-release#9853]
Type: <b>Bug</b>

When I connect to my remote maching and run a flask app in VSCode on for example, VSCode automatically opens the necessary ports. This is incredibly convenient in the most simple case. However, when sending files, if they are larger than ~500kb only part of the data is sent and request handling stalls trying to access request.files as all of the data is not available. It is not at all clear what is going wrong and very difficult to debug. If I close the port opened by vscode and then ssh into the remote machine as usual, there is no issue. 

This can easily be reproduced by cloning a repo like https://github.com/romeokienzler/flask-file-upload.git running it on a remote machine through vs code and attempting to upload a 1 Mb image. 

Extension version: 0.109.0
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:21:31.043Z)
OS version: Darwin x64 21.6.0
Modes:
Remote OS version: Linux x64 6.5.0-28-generic

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31022790
fchga941:31038042
dwnewjupytercf:31035177

```

</details>

**Comment by joshspicer** [comment]
@connor4312 Any thoughts on how someone could debug an issue like this? @albertpatterson, is this still something you think is relevant?

**Comment by connor4312** [comment]
Fixed in modern VS Code versions
