### ISSUE TITLE
Not Connecting Host

### ISSUE THREAD

**Issue by jaogle04** [microsoft/vscode-remote-release#9854]
Type: <b>Bug</b>

I input the linux drive that I am trying to connect to and it redirects me to the SSH-remote install in extensions instead of starting the connection to host process. VS code does show that SSH-remote is installed.

Extension version: 0.110.1
VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7940HS w/ Radeon 780M Graphics      (16 x 3992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.21GB (19.86GB free)|
|Process Argv|--crash-reporter-id 5e0df391-9b9c-4ff6-aea8-a62489ed7307|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by smx-smx** [comment]
It works again after downgrading to 1.88.1, which uses vscode-server e170252f762678dec6ca2cc69aba1570769a5d39

**Comment by joshspicer** [comment]
@smx-smx How is that remote log getting generated if you aren't able to install the SSH extension, and therefore couldn't connect?

@jaogle04 Please see the [troubleshooting guide](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting) and share with your logs please if you'd like us to dig into this

**Comment by smx-smx** [comment]
> [@smx-smx](https://github.com/smx-smx) How is that remote log getting generated if you aren't able to install the SSH extension, and therefore couldn't connect?
> 
> [@jaogle04](https://github.com/jaogle04) Please see the [troubleshooting guide](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting) and share with your logs please if you'd like us to dig into this

Sorry for the late reply
Upon re-reading the issue, I should have probably opened a new one since it's not the exact same dynamics.
The only reasoning for posting it here was that I was on the exact same commit.

The effect seen from vscode was "cannot connect", but upon looking at the logs on the server side it would appear that the connection was attempted and the agent crashed.
Time has passed, and I can tell that it doesn't happen anymore on the same environment where I experienced it.
Either it was fixed or the environment was updated.
