### ISSUE TITLE
[Remote-SSH Bug]: too many processes

### ISSUE THREAD

**Issue by jacksoggetto** [microsoft/vscode-remote-release#9862]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

This was not happening with previuos versions, I started noticing this behaviuos in the last 2-3 months.
This doesn't happen only to my, but also to some other people.

I connect normally using SSH, but it seems like vscode leave a lot of processes open, this saturates nproc limit (cpanel with cloudlinux, limits are different on different accounts, from 100 to 250) and the website goes offline since the limit has been reached.

Anyone else noticed this same behaviour? Is this a bug? I didn't find other conversationa about this. Ideas?

### Remote-SSH Log

not sure how to get this data

**Comment by joshspicer** [comment]
Thanks for the feedback, we also heard similar feedback in https://github.com/microsoft/vscode-remote-release/issues/10408.  I posted some suggestions there that you may be interested in (let us know on that issue if it helps)

With the information you've given I don't believe this is a bug.  Could you share more info?  What processes are you seeing? If you're able to capture some more details (output of a process monitoring program, etc..) that may help us understand exactly what you're seeing.


> not sure how to get this data

FYI, there are links on the template that explain how to grab this. The easiest way is running `> Remote-SSH: Show Log` in the command palette.
