### ISSUE TITLE
Does remote depend on local files?

### ISSUE THREAD

**Issue by adriangb** [microsoft/vscode-remote-release#9871]
I often try to use vscode remote when on a bad connection, e.g. wifi. My usual workflow is to spin up a pod in a k8s cluster with ample resources and then do a "Connect to VSCode" from VSCode desktop. But I've noticed this is a lot slower (sometimes won't work) on certain connections. Does VSCode remote rely on copying over local files / the server in any way, or any ideas what would cause this? Thanks!

**Comment by bamurtaugh** [comment]
Thanks for filing!

> Does VSCode remote rely on copying over local files / the server in any way

This is a good question, but no, remote files will stay in the remote environment (no source code needs to be copied to your local machine). Docs: https://code.visualstudio.com/docs/remote/remote-overview.

> when on a bad connection, e.g. wifi

My guess is the bad connection is interfering with and slowing other connectivity activities the remote extensions perform: https://code.visualstudio.com/docs/remote/faq#_what-are-the-connectivity-requirements-for-vs-code-server. 

cc @chrmarti for any other thoughts

**Comment by chrmarti** [comment]
The files you open in the editor are copied over. We try to optimize the amount of data sent, but a bad connection can still affect the experience. Is there anything specific not working (well)?

**Comment by adriangb** [comment]
What is not working well is if I am say on a plane with bad internet it will get stuck or be very slow on a step like:

> [16530 ms] Start: Run in container: (dd iflag=fullblock bs=8192 count=7010; dd iflag=fullblock bs=7858 count=1) | tar --no-same-owner -xz -C /root/.vscode-server/bin/dc96b837cf6bb4af9cd736aa3af08cf8279f7685_1717418505494

I figured it might be copying over the vscode server from the local system instead of e.g. relying on curl to be available on the remote system. When I'm on a good connection this is instant.

The unfortunate thing is that this defeats one of my main use cases for remote: getting access to a beefy machine with a good internet connection when I'm on the go with slow internet.
