### ISSUE TITLE
Support ssh connect distinguish by ip + port + user

### ISSUE THREAD

**Issue by InnovatorSteve** [microsoft/vscode-remote-release#9872]
The same IP address may have different usernames logged in, and there might also be virtual machines using different ports for login. However, in SSH session management, only the last connection method can be used.

**Comment by alexisshaw** [comment]
Not a solution, but a work arround, you can setup multiple entries in you ssh .config file for different usernames and ports, and as these have different names, they will show up separately in vscode.

**Comment by roblourens** [comment]
Thanks @alexisshaw, that's what I recommend
