### ISSUE TITLE
Connect to WSL fails when trying from SSH REMOTE on MACOS

### ISSUE THREAD

**Issue by junior1q94** [microsoft/vscode-remote-release#9874]
Type: <b>Bug</b>

- Connect to a windows PC using SSH Remote
- Try to connect to WSL using normal entry points

Based on the release notes,  it should works on vscode 1.89

The WSL logs look like this:
[2024-05-11 04:40:53.722] Extension version: 0.88.2
[2024-05-11 04:40:53.722] L10N bundle: undefined
[2024-05-11 04:40:53.724] authorityHierarchy: ssh-remote+192.168.1.102
[2024-05-11 04:40:53.724] WSL extension is activating remotely for ssh-remote+192.168.1.102
[2024-05-11 04:40:53.765] Workspace platform is Windows
[2024-05-11 04:40:53.794] Run: C:\WINDOWS\System32\wsl.exe --status
[2024-05-11 04:40:53.841] WSL feature installed: false (wsl --status)
[2024-05-11 04:40:53.841] WSL feature installed: false
[2024-05-11 04:45:30.668] Run: C:\WINDOWS\System32\wsl.exe --list --verbose
[2024-05-11 04:45:30.763] Error: Failed to run wsl.exe --list --verbose: error code 1, error: The file cannot be accessed by the system.
[2024-05-11 04:46:41.267] Run: C:\WINDOWS\System32\wsl.exe --list --online

Extension version: 0.88.2
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin x64 23.4.0
Modes:
Remote OS version: Windows_NT x64 10.0.22631

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.1.102|
|OS|Windows_NT x64 10.0.22631|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|Memory (System)|31.91GB (20.58GB free)|
|VM|0%|
</details>

**Comment by lukas-lang** [comment]
I am experiencing a similar issue (i.e. same behavior & error message). Only difference is that I am using a Windows Client to SSH into the remote computer

**Comment by junior1q94** [comment]
I was able to work around the issue by upgrading the WSL to the pre release version using the next command:
`wsl --update --pre-release`

Before that, I recommend to backup your installed distributions, for example to backup Ubuntu:
`wsl --export Ubuntu "C:\WSL_backups\ubuntubackup.tar"`

To see your installed distributions names:
`wsl --list`

To restore backup:
`wsl --import Ubuntu "C:\WSLDistros" "C:\WSL_backups\ubuntubackup.tar"`

Note: It seems the WSL from the store is source of the issue.

**Comment by bamurtaugh** [comment]
Thanks folks for the discussion. It sounds like this was an issue upstream with WSL potentially rather than VS Code Remote, so I'll close this out. If you are still experiencing issues with VS Code though, please let us know, and happy to reopen.
