### ISSUE TITLE
[Remote-SSH Bug]: Jailed Shell cPanel user unable to open integrated terminal: The terminal process failed to launch: A native exception occurred during launch (forkpty(3) failed.).

### ISSUE THREAD

**Issue by legendarylion** [microsoft/vscode-remote-release#9876]
### Is there an existing issue for this bug?

- [x] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Issue

It connects successfully, files can be edited and saved, but the integrated terminal does not work as expected with "Jailed Access" set to the cPanel account.

### Expected Behavior

The expected behavior is for the terminal to open. 

If the cPanel is set to "Normal Access" the terminal launches correctly.

### Steps To Reproduce

*Connect via Remote SSH to cPanel set as "Jailed Shell" SSH Terminal access*
*Open terminal*
ERROR: The terminal process failed to launch: A native exception occurred during launch (forkpty(3) failed.).
*Terminal automatically closes*

### Remote-SSH Log

N/A
No log available, exception error thrown, terminal closes.

**Comment by bamurtaugh** [comment]
cc @Tyriar @meganrogge for any thoughts

**Comment by legendarylion** [comment]
Hey there,

No, that does not solve the problem.

settings.json
{
    "terminal.integrated.shellIntegration.enabled": false,
...
}

Still predictably throws: The terminal process failed to launch: A native
exception occurred during launch (forkpty(3) failed.). when connected to
the account and initiating a terminal in the editor.

Changing the cPanel status to "Normal" shell resolves this, but of course
carries more security risks.

**Comment by meganrogge** [comment]
has this always been the case or has the issue appeared recently?

**Comment by legendarylion** [comment]
I was just working on this issue. :)

I believe it wasn't an issue in an earlier version of VSC, but I can't
remember what version the issue started.

I was able to find another thread about this that another user was
experiencing the same issue:
https://stackoverflow.com/questions/70052130/how-to-fix-vs-code-error-with-remote-ssh-the-terminal-process-failed-to-launch

**Comment by legendarylion** [comment]
Team,

The issue still persists. It seems to be a permissions issue with command
line and jailed vs normal permissions. Normal works, jailed always fails.

**Comment by Tyriar** [comment]
@legendarylion this is the first time I've heard of cpanel and a "jailed shell". Given this error is unique to this cpanel service I recommend reporting it over there as they're doing something that is not compatible with how we create ptys. It looks like it's throwing somewhere in https://github.com/microsoft/node-pty/blob/8bdbd712f40acb939dbab1def8a1c3a815254f74/src/unix/pty.cc#L258, maybe someone from that company can help figure it out and upstream support if it looks reasonable.

**Comment by legendarylion** [comment]
Copy that. I'll relay it to the cPanel support teams.
