### ISSUE TITLE
Please Allow Remote WSL with non-root user

### ISSUE THREAD

**Issue by oo-wooal** [microsoft/vscode-remote-release#9879]
Currently, WSL Remote only allow root login by default. This is not safe to do development with root account.
Please allow user to configure non root user to login WSL.

**Comment by aeschli** [comment]
There's no requirement to use the root user. The WSL Remote just uses the current default user. It only writes to the user's home folder.
You can change the WSL default user with `ubuntu config --default-user <username>` (`ubuntu` being the distro name here)

**Comment by oo-wooal** [comment]
> There's no requirement to use the root user. The WSL Remote just uses the current default user. It only writes to the user's home folder. You can change the WSL default user with `ubuntu config --default-user <username>` (`ubuntu` being the distro name here)

Great, i changed the default user => restart WSL => now the vscode wsl remote switch to another user.
Thank you!
