### ISSUE TITLE
[WSL]: Clicking on http://localhost:3000 in the terminal translates into loopback, 127.0.0.1 in Windows.

### ISSUE THREAD

**Issue by aidan-rypens** [microsoft/vscode-remote-release#9881]
Type: <b>Bug</b>

Cannot seem to find any configuration that would result in this. Suddenly started occuring.
Only occurs using VSCode. Clicking a link in the terminal (using WSL) results in the correct link.

Only specifically applies to localhost.

Extension version: 0.88.2
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900K (24 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.78GB (47.27GB free)|
|Process Argv|--crash-reporter-id 5042389b-46f0-421e-b14e-d2a5f0e8fa45|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900K (24 x 3187)|
|Memory (System)|31.23GB (29.22GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31018788
dsvsc021:30996838
g316j359:31013175
pythoncenvptcf:31043158
fchga941:31046352
pythonprc:31039816
dwnewjupytercf:31039676

```

</details>

**Comment by aeschli** [comment]
Can you explain more? 
- you have `http://localhost:3000` as a string in the integrated terminal and click on it
- the browser opens but opens `127.0.0.1` ?

**Comment by aidan-rypens** [comment]
> Can you explain more?
> 
> * you have `http://localhost:3000` as a string in the integrated terminal and click on it
> * the browser opens but opens `127.0.0.1` ?

Exactly that behavior. Correct.

**Comment by viell-dev** [comment]
I've had the same problem for a long time. The app I'm working on talks with an ID server that doesn't have loopback IP's in it's CORS settings but does have `localhost`. So signing in only works through `localhost`.

Ended up just putting this in my `main.ts` file:
```ts
if (location.hostname.startsWith("127.")) {
  location.hostname = "localhost";
} else {
  // Actual main code goes here.
}
```

**Here's a step-by-step visual guide to what is happening:**

Terminal shows https:\/\/localhost:8000
![Terminal shows https:\/\/localhost:8000](https://github.com/microsoft/vscode-remote-release/assets/83065072/2c3c9d2b-b341-4406-95dd-54f24f1fe5c6)

Hovering on the "Follow link" text shows https:\/\/localhost:8000
![Hovering on the "Follow link" text shows https:\/\/localhost:8000](https://github.com/microsoft/vscode-remote-release/assets/83065072/e34274c2-2f27-4022-befe-f4c2b75f3a56)

Ports panel shows 127.0.0.1:8000
![Ports panel shows 127.0.0.1:8000](https://github.com/microsoft/vscode-remote-release/assets/83065072/d67504e3-a934-4430-b500-24c0b5cd7257)

Browser opens at https:\/\/127.0.0.1:8000
![Browser opens at https:\/\/127.0.0.1:8000](https://github.com/microsoft/vscode-remote-release/assets/83065072/b973542a-a02d-454c-8b4b-b201c09c5dbd)
