### ISSUE TITLE
Hang at reconnect ( logout->sshdisconnetc->reconnect )

### ISSUE THREAD

**Issue by effolkronium** [microsoft/vscode-remote-release#989]
- VSCode Version: 
![image](https://user-images.githubusercontent.com/15274763/61409551-2602a800-a8eb-11e9-95db-10c7bb5f3eb8.png)

- Local OS Version: 
![image](https://user-images.githubusercontent.com/15274763/61409490-07041600-a8eb-11e9-9528-42c8eb6410e4.png)

- Remote OS Version: ubuntu 18.04 server
- Remote Extension c++; cmake; svn; cmake-tools;
- Connection Type: SSH

Steps to Reproduce:

1. Disconnect of rdp connection to host vscode pc with open connection to linux by ssh
2. Relogin by rdp -> vscode is hanging forever

![image](https://user-images.githubusercontent.com/15274763/61409287-965cf980-a8ea-11e9-967b-c51624bc8bbc.png)

**Comment by roblourens** [comment]
Please describe step by step exactly what you are doing
