### ISSUE TITLE
[Windows+WSL2+Docker] Impossible to reach forwarded port from DevContainer 

### ISSUE THREAD

**Issue by andreujuanc** [microsoft/vscode-remote-release#9893]
- VSCode Version: latest 3 tested
- Local OS Version: 10.0.22631 Build 22631
- Remote OS Version: 5.15.146.1-microsoft-standard-WSL2
- Remote Extension/Connection Type: Containers/WSL/Server: WSL+Docker  DevContainer

Steps to Reproduce:

1. Open repo with a DevContainer, Open in Container,
2. Start webserver
3. Port is forwarded automatically (8080 in my case)
4. Cant connect from any browser, curl, etc

In the DevContainer
![image](https://github.com/microsoft/vscode-remote-release/assets/360052/cbd3d834-bf7c-48c9-9380-bd714b7cac3d)

Host:
![image](https://github.com/microsoft/vscode-remote-release/assets/360052/0128fc04-7661-4b9a-bf54-dfdf56ab49ea)

I have tried:

 - Restarting my machine
 - Restarting WSL
 - Stopping and deleting all containers
 - Installing previous versions of VSCode and Remote Extensions
 - Manually forward the port
 - Change the port number
 - Using "appPort" from devcontainer.json. (tried different port numbers) Does not work.

This started two days ago, and I haven't installed or updated anything on my system.
I know this might be a problem with my box, but since this team is very knowledgeable about networking+extensions+wsl+docker I guessed that maybe it's something that can happen to more people and leaving trace of a way to fix it would be the best thing to do. 

Would appreciate any help regarding this matter.

**Comment by andreujuanc** [comment]
UPDATE:
Weirdly, a local curl within the DevContainer would work. but not outside of the container.
One obvious thing I didn't try was to run a different server. So I did a quick npx serve with an simple html file.
This worked. 
My main server is question is a vite one on dev mode. I removed the certificate part and still does not work. I suspect it might be related to the way vite binds.

**Comment by mswawola** [comment]
I am currently developing a web application using Vite and DevContainer. A few days ago, I encountered an issue where I could not access the application from the browser anymore despite having port forwarding set up for port 3000 as usual. This had been functioning as intended for several months until, possibly, the most recent automatic update of VSCode.

As pointed out by @andreujuanc,  the --host option when running Vite allows me to access the application. However, this should be considered a workaround, and the underlying issue still needs to be resolved.

The following is an error displayed in the Serve output when attempting to access localhost:3000 from the web browser:
![image](https://github.com/microsoft/vscode-remote-release/assets/8048065/eb45ba6a-2c29-4126-9343-457839fb186b)

**Comment by yamdan** [comment]
The same issue happened to me, and it was worked around by setting the `--host` option as @andreujuanc mentioned above. The root cause of this problem might be related to the discussion at https://github.com/vitejs/vite/issues/16522.

**Comment by andreujuanc** [comment]
> The same issue happened to me, and it was worked around by setting the `--host` option as @andreujuanc mentioned above. The root cause of this problem might be related to the discussion at [vitejs/vite#16522](https://github.com/vitejs/vite/issues/16522). It might be better to use `--host 127.0.0.1` as it only exposes locally, as mentioned in [vitejs/vite#16522 (comment)](https://github.com/vitejs/vite/issues/16522#issuecomment-2075856315)

Brilliant!! Thanks for letting me know.

I'll keep this issue open since it's not a vite problem but it looks like a DNS issue when the latest version of docker resolves with ipv6 instead o v4. Maybe the remote extensions can do something about it not to add the host param or disabling ipv6 on all docker projects.

**Comment by yamdan** [comment]
Yes, indeed, the comment at https://github.com/vitejs/vite/issues/16522#issuecomment-2084322973 is quite insightful :)

**Comment by chrmarti** [comment]
@alexr00 This works for me with a simple HTTP server listening on `[::]:3000` in the container.

Could someone seeing this run `netstat -l` inside the container and post the output here?

**Comment by andreujuanc** [comment]
Hi @chrmarti , sure here it is. First with the host:true set, and then the default.
![image](https://github.com/microsoft/vscode-remote-release/assets/360052/b5c095c0-ce37-4c84-b0d9-a807a7f5e48d)

Both look exactly the same, both are forwarded, but only the first one works.

BTW, I just got a friend to do this without devcontainers natively on linux, and when he updated to the latest docker >= 23.1.0 it reproduced the issue.

So this is most likely an network incompatibility issue between docker and vite, and the remote extensions just got tangled in. But I can still be wrong.

**Comment by andreujuanc** [comment]
Server NOT RUNNING:
![image](https://github.com/microsoft/vscode-remote-release/assets/360052/aac3d347-51e1-4b46-9954-93654787cb9f)

Server without the `host:true`
![image](https://github.com/microsoft/vscode-remote-release/assets/360052/c62097b1-42b8-471d-b967-47b86879c3e5)


So there is a difference, and something is being forwarded. It's outside of my networking knowledge.

**Comment by chrmarti** [comment]
I can reproduce with vite and the latest Docker Desktop for Mac.

It seems `[::]` works, but `localhost` doesn't. Continuing in https://github.com/microsoft/vscode-remote-release/issues/7029.
