### ISSUE TITLE
[Remote-SSH Bug]: remote.SSH.connectTimeout not respected using exec server

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode-remote-release#9894]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

`remote.SSH.connectTimeout` is not respected in the ssh command used by exec server, I see it uses  `-o ConnectTimeout=15` always

### Expected Behavior

`remote.SSH.connectTimeout` is respected in the ssh command used by exec server

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by connor4312** [comment]
I'm not able to repro this, and looking at the code we put the setting value directly into the command the only place we create a `ConnectTimeout` argument. Can you please share additional logs/repro steps?

**Comment by jeanp413** [comment]
@connor4312 I tested again and seems it only doesn't work for `"remote.SSH.connectTimeout": 0`, I'm trying to disable it as setting a value greater than 0 causes ssh to resolve the host which takes a considerable time in my case.

>  Also, please verify that you do not have a ConnectTimeout option configured in the SSH host config, as that will be preferred.

That's not what I see, `ConnectTimeout` from ssh config file is always ignored, I created an issue a long time ago for that https://github.com/microsoft/vscode-remote-release/issues/8519
