### ISSUE TITLE
when can use in docker installing with docker toolbox

### ISSUE THREAD

**Issue by jianboy** [microsoft/vscode-remote-release#990]
windows can not install Hyper-V and vmware together. So I just can install docker using docker tools.

**but. VSCode still can not support docker with docker toolbox.** 

![BaiduHi_2019-7-18_5-16-12](https://user-images.githubusercontent.com/11532015/61412335-3894d580-a91b-11e9-8a8f-6fc4348c856a.png)

windows can not use it! 
![2019-07-18_051805](https://user-images.githubusercontent.com/11532015/61412487-95908b80-a91b-11e9-82cb-c450dc155b11.jpg)

**Comment by bamurtaugh** [comment]
As I believe this is a request for support for Docker Toolbox, that's being tracked here https://github.com/microsoft/vscode-remote-release/issues/95, so closing this issue. 

If you have any other questions, or this was a different question or request, please let me know!
