### ISSUE TITLE
Leftover file watchers after window reload

### ISSUE THREAD

**Issue by gavriil-deshaw** [microsoft/vscode-remote-release#9904]
Type: <b>Bug</b>

### Actual:
- Open a workspace using the Remote - SSH extension
  - You see that a file watcher is spawned
- Reload the VSCode window
  - You see a new file watcher is spawned, but the previous one(s) is still there 
### Expected:
- Open a workspace using the Remote - SSH extension
  - You see that a file watcher is spawned
- Reload the VSCode window
  - You see a new file watcher is spawned, but the previous one(s) is killed

### Setup info
- Version: 1.89.1 (system setup) (happened with v1.88 as well)
- Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
- Date: 2024-05-07T05:13:33.891Z
- Electron: 28.2.8
- ElectronBuildId: 27744544
- Chromium: 120.0.6099.291
- Node.js: 18.18.2
- V8: 12.0.267.19-electron.0
- OS: Windows_NT x64 10.0.19045

- Remote - SSH extension: v0.110.1
- Remote OS version: Linux x64

### Other info
- This issue isn't observed with the Remote - WSL extension

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/211462
