### ISSUE TITLE
hope to support  aarch64

### ISSUE THREAD

**Issue by JonesZeng** [microsoft/vscode-remote-release#991]
Issue Type: <b>Feature Request</b> remote-ssh@0.44.2
linux x64
SSH Resolver called for "ssh-remote+tx2", attempt 1
SSH Resolver called for host: tx2
Setting up SSH remote "tx2"
Using commit id "8fa811108f0f0524c473020ef57b6620f6c201e1" and quality "insider" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_8.0p1, OpenSSL 1.1.1c 28 5月2019日
Running script with connection command: "ssh" -o ClearAllForwardings=true -o ConnectTimeout=15 "tx2" bash
Install and start server if needed
> Running remote connection script
> Unsupported architecture: aarch64
> 08c60bc3-f706-4e2e-840e-5ea745153fe9##27##
"install" terminal command done
Received install output: 08c60bc3-f706-4e2e-840e-5ea745153fe9##27##
Unsupported architecture
The remote server architecture is not supported
------ Extension version: 0.44.2
VS Code version: Code - Insiders 1.37.0-insider (8fa811108f0f0524c473020ef57b6620f6c201e1, 2019-07-12T09:18:33.949Z)
OS version: Linux x64 4.19.56-1-MANJARO
Remote OS version: Linux x64 4.4.0-145-generic
Fetching remote diagnostics for 'SSH' failed: The remote server architecture is not supported

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/60
