### ISSUE TITLE
Not showing SSH entries on config file

### ISSUE THREAD

**Issue by DanielDP24** [microsoft/vscode-remote-release#9913]
Type: <b>Bug</b>

after adding remotes, they dont show up on the ssh list, regarding of the extension version

Extension version: 0.108.0
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 6.5.0-35-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3691)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.53GB (8.52GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 110642aa-ff70-4369-b306-686b920a41e6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31049070
fchga941:31046352
pythonprc:31047982
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by jamesps-ebi** [comment]
Same issue for me on Ubuntu.
VS Code version: 1.89.1
Extension version: v0.4.3

**Comment by jamesps-ebi** [comment]
@DanielDP24 are you also using Ubuntu with TPM-backed encryption? I have now tested 2 machines using this encryption and found the same problem.

On an unencrypted machine, I wasn't having the same issue.

**Comment by jamesps-ebi** [comment]
I just tested the pre-release version of Remote-SSH plugin `v0.112.2024051615 (pre-release)` and now the list of SSH hosts is showing.
I can connect without issue on this version.

**Comment by bamurtaugh** [comment]
Thanks for the discussion so far!

Based on @jamesps-ebi's latest update, I'm going to close out this issue. But if folks are still experiencing issues, please let us know, and I'm happy to reopen.
