### ISSUE TITLE
Add Ability To Use Chrome Debugger While Connected To Remote Using Tunnels

### ISSUE THREAD

**Issue by MinamiHasaki** [microsoft/vscode-remote-release#9915]
It would be nice to have the ability to use the Chrome Debugger option while connected to a remote VS Code Server instance using Tunnels.

**Comment by connor4312** [comment]
This should work if you're connecting from desktop VS Code, but cannot work in web. We need to launch a browser with a debugger attached and a random webpage does not have permission to do this.
