### ISSUE TITLE
Option to always replace file when uploading

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode-remote-release#992]
In development you might want to use vscode as a sftp browser to upload files. I would like an option to always replace file on remote server like what filezilla provides:

![image](https://user-images.githubusercontent.com/1189869/61422971-8cfe7c00-a940-11e9-9e0e-e48238284741.png)

**Comment by roblourens** [comment]
Can you explain what is not working and what you want to happen instead?

**Comment by xgdgsc** [comment]
Currently everytime I drag to upload a file with same name on server, it would show a dialog making sure I want to replace it. Since I would replaces it frequently during my development, I want an option to disable this reminder dialog and automatically do the replace according to the rules likely provided by Filezilla.

**Comment by xgdgsc** [comment]
Where is the correct scope to report this?
