### ISSUE TITLE
[Remote-SSH Bug]: Remote connection process resource leakage

### ISSUE THREAD

**Issue by Clownsw** [microsoft/vscode-remote-release#9924]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

I connected to my server remotely via ssh for development. When I closed the connection, the process created by ssh on the remote server did not exit, which resulted in resource leakage.

### Steps To Reproduce

Remote connection (plugin with create process behavior) and then disconnect repeatedly like this

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by roblourens** [comment]
This is likely https://github.com/microsoft/vscode/issues/211462, you can try in the next VS Code Insiders on Monday to see if your issue goes away.
