### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by SystemWar** [microsoft/vscode-remote-release#9925]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

#code #luděk

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by bamurtaugh** [comment]
Thanks for filing. It doesn't look like there's an issue/bug/feature request described here, so closing the issue. If you do have a specific issue in mind, please just let us know, and happy to reopen.
