### ISSUE TITLE
[Remote-SSH Bug]: Failed to install code when specifying a server install path

### ISSUE THREAD

**Issue by MariusDrulea** [microsoft/vscode-remote-release#9930]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [ ] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

The vscode server shall install in remote when specifying the serverInstallPath. I use this setting cause I have to use an apptainer on the remote.
If I don't use the apptainer related settings (e.g. no serverInstallPath specified, and connect to myhost.com instead of myimage1~myhost.com), the installation of vscode server works.

### Steps To Reproduce

**in settings.json**
"remote.SSH.serverInstallPath": {
		"myimage1\~myhost.com": "~/.vscode-container/myimage1",
	},
	
**in ssh config file**
Host myimage1~*
	RemoteCommand apptainer shell /path/myimage1.sif
	RequestTTY yes

Host myhost.com myimage1~myhost.com
	HostName myhost.com
	User user
	ForwardAgent yes
	ForwardX11 yes
	ForwardX11Trusted yes

### Remote-SSH Log

[12:05:36.493] > 6983fdd17fe0: running
[12:05:36.527] > Installing to ~/.vscode-container/myimage1/.vscode-server...
[12:05:36.542] > 6983fdd17fe0%%1%%    
> Downloading with wget
[12:05:36.967] > Download complete
[12:05:36.982] > 6983fdd17fe0%%2%%
> tar --version:
> tar (GNU tar) 1.26
> Copyright (C) 2011 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[12:05:37.531] > mv: cannot move ‘code’ to ‘~/.vscode-container/myimage1/.vscode-server/code-d
> c96b837cf6bb4af9cd736aa3af08cf8279f7685’: No such file or directory
> bash: line 272: /home/user/.vscode-container/myimage1/.vscode-server/code-
> dc96b837cf6bb4af9cd736aa3af08cf8279f7685: No such file or directory
> ERROR: ~/.vscode-container/myimage1/.vscode-server/code-dc96b837cf6bb4af9cd73
> 6aa3af08cf8279f7685 don't exist

**Comment by MariusDrulea** [comment]
I am able to connect using the same command used by the vscode:
`"C:\Program Files\Git\usr\bin\ssh.exe" -T -D 54396 -o RemoteCommand=none "myimage1~myhost.com" bash`
Inside the remote command I am able to create and delete folders.

**Comment by MariusDrulea** [comment]
Indeed, the folder `~/.vscode-container/myimage1` is not created during the server installation process.

**Comment by xiongqr** [comment]
I can confirm the existence of the bug.  The bug is fairly new.  It was working in March, 2024.

**Comment by joshspicer** [comment]
Thanks for taking the time to open an issue.

I believe 'apptainer' is a rebrand of 'Singular', which I know already has a feature request https://github.com/microsoft/vscode-remote-release/issues/3066

As you've shared removing the 'apptainer' the installation works, that points to our lack of Singular/apptainer support.
