### ISSUE TITLE
Remote-SSH unable to connect when config path has a space in it

### ISSUE THREAD

**Issue by jannik11b** [microsoft/vscode-remote-release#994]
- VSCode Version: 1.37.0-Insiders
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. In the settings specify custom ssh configuration file **with space in the path** 
2. Connect to a host from that file

Issue #525 just tells me not to use a space and #360 is also closed

**Comment by roblourens** [comment]
Can you try this with the latest nightly version of the ssh extension? I think I just fixed this.

**Comment by jannik11b** [comment]
I am using the current latest v0.44.2. If this is not what you mean how can i get the latest nightly version?

**Comment by roblourens** [comment]
https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly Make sure you uninstall the stable version first

**Comment by jannik11b** [comment]
Ok thanks, it works with the nightly version.

**Comment by roblourens** [comment]
Thanks!
