### ISSUE TITLE
Must kill node processes on the remote after a few connections

### ISSUE THREAD

**Issue by Joshuah143** [microsoft/vscode-remote-release#9944]
Type: <b>Bug</b>

Open about 10 vs code remote windows into the same server. 

At some point, git will stop functioning and you will be unable to create new terminals.

If you now run `pkill -u USER node` and re-open the windows it will work fine again. Note that after closing a window it leaves the associated node process running on the remote.

Note, all of these steps were performed with a remote that uses `RemoteCommand` to enter an apptainer container.

Extension version: 0.112.2024053015
VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin arm64 23.5.0
Modes:
Remote OS version: Linux x64 5.15.0-107-generic
Remote OS version: Linux x64 5.15.0-107-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|11, 10, 13|
|Memory (System)|32.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id c418b412-f653-46ab-8853-2e0293bd9a9d|
|Screen Reader|yes|
|VM|0%|

Connection to 'SSH: m2' could not be established  Canceled

|Item|Value|
|---|---|
|Remote|SSH: m2-dev|
|OS|Linux x64 5.15.0-107-generic|
|CPUs|Intel(R) Xeon(R) Gold 6336Y CPU @ 2.40GHz (96 x 800)|
|Memory (System)|1007.48GB (986.28GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ML2-dev-tf|
|OS|Linux x64 5.15.0-107-generic|
|CPUs|Intel(R) Xeon(R) Gold 6336Y CPU @ 2.40GHz (96 x 2400)|
|Memory (System)|1007.48GB (986.28GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31064719
chatpanelt:31048053
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31061160
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by Joshuah143** [comment]
Note that this often manifests as: 
<img width="458" alt="Screenshot 2024-05-31 at 10 54 48 AM" src="https://github.com/microsoft/vscode-remote-release/assets/83801098/34d86d35-06b1-4f9f-958a-431ca2258912">
Despite `/bin/bash` definitely existing.

**Comment by roblourens** [comment]
Can you list out the processes that appear to be leaked, with the full command line arguments, so I can see which ones they are?

**Comment by Joshuah143** [comment]
What do you mean by appear to be leaked? I am happy to send over the results of htop the next time I see the issue (at least once a day), but is that what you want? The code that I actually run through VSCode remotely is entirely python.

**Comment by roblourens** [comment]
Actually, this is likely https://github.com/microsoft/vscode/issues/211462. You can try in the next Insiders build on Monday to see whether your issues goes away.
