### ISSUE TITLE
SVN extension doesn't work with Remote-SSH-2

### ISSUE THREAD

**Issue by effolkronium** [microsoft/vscode-remote-release#995]
- VSCode Version:
- Local OS Version:
![image](https://user-images.githubusercontent.com/15274763/61463159-87268c00-a97c-11e9-8dd1-13127133579e.png)

- Remote OS Version:
Ubuntu 1804 server

- Remote Extension/Connection Type: SSH/Docker/WSL
![image](https://user-images.githubusercontent.com/15274763/61463311-cd7beb00-a97c-11e9-9a71-ff69961d61d8.png)

Steps to Reproduce:

1. Install svn extension
2. Open folder with svn repo

**Comment by effolkronium** [comment]
![image](https://user-images.githubusercontent.com/15274763/61463647-84786680-a97d-11e9-8a48-aefbc5e66663.png)

**Comment by roblourens** [comment]
Please file an issue on the SVN extension and ensure that your server has proper certificates installed

**Comment by effolkronium** [comment]
i don't know how, but it was fixed by itself :)
