### ISSUE TITLE
[Remote-SSH Bug]: GNU-userland tools such as `ps` assumed

### ISSUE THREAD

**Issue by sanmai-NL** [microsoft/vscode-remote-release#9954]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Don't invoke CLI utils for which CLI compat isn't guaranteed. 
Use custom source code or use e.g., the proc filesystem to get the required information.

### Steps To Reproduce

Connect to an Alpine Linux based node.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
> ps: unrecognized option: p
[09:31:21.299] > BusyBox v1.36.1 (2024-05-21 13:38:37 UTC) multi-call binary.
> 
> Usage: ps [-o COL1,COL2=HEADER] [-T]
> 
> Show list of processes
> 
> 	-o COL1,COL2=HEADER	Select columns for display
> 	-T			Show threads
```

</p>
</details>

**Comment by sanmai-NL** [comment]
Work-around for Alpine Linux: install the `procps-ng` package.

**Comment by roblourens** [comment]
BusyBox: https://github.com/microsoft/vscode-remote-release/issues/1747 and https://github.com/microsoft/vscode-remote-release/issues/6347 for Alpine

**Comment by joshspicer** [comment]
I've explicitly addressed this as a part of the work tracked in https://github.com/microsoft/vscode-remote-release/issues/1747
