### ISSUE TITLE
DevContainer: environment variables in runArgs are not refreshed after restart

### ISSUE THREAD

**Issue by VaRusLAN** [microsoft/vscode-remote-release#9955]
- VSCode Version: 1.90
- OS: EndeavourOS
- Remote Extension/Connection Type: Container

Issue:

 I wanted to run GUI app from devcontainer, so I modified devcontainer.json like this
```json
{
    "name": "Workspace",
    "build": {
        "dockerfile": "dockerfile",
        "context": ".."
    },
    "workspaceMount": "source=${localWorkspaceFolder},target=/home/user/workspace,type=bind",
    "workspaceFolder": "/home/user/workspace",
    "runArgs": [
        "--network=host",
        "--mount=source=/tmp/.X11-unix,target=/tmp/.X11-unix,type=bind",
        "--mount=source=${localEnv:XAUTHORITY},target=/home/user/.Xauthority,type=bind"
    ],
    "containerEnv": {
        "DISPLAY": "${localEnv:DISPLAY}"
    }
}
```

I'm running Plasma with Wayland and I don't have /home/user/.Xauthority on my machine. Instead, I have a file `/run/user/1000/xauth_RIGXDd` which changes every time I restart my computer (or logout). The only way to retrieve this file is with environment varialbe `$XAUTHORITY`.

After I rebuild the container everything works fine, I can start my GUI application from devcontainer. But after I restart my computer and try to open devcontainer I receive an error 

```
[2024-06-06T07:41:23.911Z] Start: Starting container
[2024-06-06T07:41:23.911Z] Start: Run: docker start 88bf7383d900a6bc3f3e88fefeb1a5ba0cc1fe26a7226c169a1292668b564536
[2024-06-06T07:41:23.921Z] Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /run/user/1000/xauth_yDrFht
Error: failed to start containers: 88bf7383d900a6bc3f3e88fefeb1a5ba0cc1fe26a7226c169a1292668b564536

[2024-06-06T07:41:23.922Z] Stop (11 ms): Run: docker start 88bf7383d900a6bc3f3e88fefeb1a5ba0cc1fe26a7226c169a1292668b564536
[2024-06-06T07:41:23.922Z] Exit code 1
[2024-06-06T07:41:23.924Z] Error: Command failed: docker start 88bf7383d900a6bc3f3e88fefeb1a5ba0cc1fe26a7226c169a1292668b564536
```

I can fix it by running `Rebuild an Reopen in Container`.

The problem is that everytime I restart my computer `$XAUTHORITY` variable changes to a random value and devcontainer extension uses cached previous value instead of reevaluating to a new argument with a new environment variable.

I expected that environment variables would be reapplied after restart at least for `runArgs`, because it makes sense.

**Comment by chrmarti** [comment]
The behavior you observe is given by Docker and not under control by Dev Containers. The mount points are fixed when the container is created and cannot be changed later.

What you can try is to remove the two mount points and remove the `DISPLAY` variable and see if the Dev Containers extension's X11 forwarding works. The extension will set `DISPLAY` in the container when it sees a local `DISPLAY` and forward connections to the local socket.

**Comment by VaRusLAN** [comment]
> What you can try is to remove the two mount points and remove the `DISPLAY` variable and see if the Dev Containers extension's X11 forwarding works. The extension will set `DISPLAY` in the container when it sees a local `DISPLAY` and forward connections to the local socket.

I tried that and although `DISPLAY` is forwarded, it still needs Xauthority
```
Authorization required, but no authorization protocol specified
Unable to access the X Display, is $DISPLAY set properly?
```

**Comment by VaRusLAN** [comment]
Ok, I found a workaround
```json
{
    "name": "Workspace",
    "build": {
        "dockerfile": "dockerfile",
        "context": ".."
    },
    "workspaceMount": "source=${localWorkspaceFolder},target=/home/user/workspace,type=bind",
    "workspaceFolder": "/home/user/workspace",
    "runArgs": [
        "--network=host"
    ],
    "initializeCommand": "xhost +local:docker"
}
```
