### ISSUE TITLE
VSCode remote SSH disconnecting regularly after performing 

### ISSUE THREAD

**Issue by frewsxcv** [microsoft/vscode-remote-release#9956]
- VSCode Version: 1.90.0
- Local OS Version: macOS 13.6
- Remote OS Version: CentOS Linux release 7.5.1804
- Remote Extension/Connection Type: Server

- Logs: https://gist.github.com/frewsxcv/40cfa0f229de47b8584571988e4a7687

The past week or so my remote SSH session in VSCode has been disconnecting regularly, usually after a large CPU operation like TypeScript needing to reindex the project. This hasn't been an issue in the past and I'm wondering if something change din the May 30th extension release last week. Is it possible to release a changelog of the changes that went out with the update last week?

**Comment by roblourens** [comment]
There are probably no changes in the extension that would have impacted this- if anything, it would be a change in Typescript, in another extension, or vscode itself.

Is it possible that you're getting these issues like

> a large CPU operation like TypeScript needing to reindex the project

more frequently? I still wouldn't expect that to break the connection necessarily but maybe it's bad enough to keep the server from communicating with the client for a bit. Is the remote machine low on CPU/memory?

**Comment by frewsxcv** [comment]
https://github.com/microsoft/vscode/issues/211462 is likely the culprit
