### ISSUE TITLE
Stuck on "Configuring Dev Container"

### ISSUE THREAD

**Issue by pamelafox** [microsoft/vscode-remote-release#9959]
- VSCode Version:

Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:32.757Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.5.0

- Local OS Version:
- Remote OS Version: mcr.microsoft.com/devcontainers/python:3.11-bullseye
- Remote Extension/Connection Type: Containers

- Logs:

Steps to Reproduce:

1. Open https://github.com/pamelafox/django-quiz-app in VS Code on Mac OS M1 with Dev Containers extension
2. See that it eternally is stuck on the "Configuring Dev Container" stage

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Not sure, can't load extensions tab curretnly

**Comment by pamelafox** [comment]
Attaching logs:

[remoteContainers-2024-06-07T23-16-28.206Z.log](https://github.com/user-attachments/files/15745812/remoteContainers-2024-06-07T23-16-28.206Z.log)

**Comment by chrmarti** [comment]
Could you attach a screenshot of the VS Code window? How is the above screenshot related to this issue?

**Comment by pamelafox** [comment]
Sorry, wrong screenshot! I'll close, as I don't think I'm experiencing this particular issue anymore with the current version of VS Code. I still get the git issue from the other thread.
