### ISSUE TITLE
option to have remote server kill itself when no one is connected.

### ISSUE THREAD

**Issue by caffeineaddiction** [microsoft/vscode-remote-release#996]
Currently if you make a connection to `remote` for the first time, this extension will wget itself and spin up a server before connecting.   The second time you connect, you will connect to the already running server.

In my opinion this leads to 2x problems:
 1) if someone deletes the `~/.vscode-server` folder or the user profile is deleted and recreated on next login ... vscode-remote will fail due to server already being up but folders from which it was launched not existing anymore.
 2) resources are being consumed on my remote box while no active connection exists ... this is a waste of CPU / Memory.

I think it would be better have either:
 1) remote `server` instead becomes remote `client` connecting back to your desktop via reverse port forwarding.  This is currently how `rmate` works ... and while vscode-remote has quite a bit more functionality ... I believe you wouldn't loose any functionality.  In fact, I believe it might help with some of the stability issues that are currently a problem.
 2) remote `server` spins up when you connect per initial connection, but after all sessions have ended ... it dies off.  Again, I think this is a less wasteful approach, would solve many of the other open issues with server stability between sessions and or deleting `.vscode-server` folder.

While I am sure some of the users wouldnt care about some small amount of cycles being used on the `remote-server` when they are not connected, I believe many people would use this functionality if it was available.

I am currently planning on creating a bash script to live in my .bashrc to spin up in the background and kill everything off once I disconnect ... but imo there should be a more elegant solution.

**Comment by caffeineaddiction** [comment]
Work around for now:

vsCleanUp.sh
```
#!/bin/bash

toFork(){
  while true; do
    if [ -z "$(who)" ]; then
      pkill -9 -f vscode
      exit
    fi
    sleep 60
  done
}

numproc="$(ps hf -opid,cmd -C "$(basename $0)" | awk '$2 !~ /^[|\\]/ { ++n } END { print n }')"
if (( numproc > 1 )); then
  exit
fi
```

call `vsCleanUp.sh` from `~/.bashrc` ... only one instance of the fork will remain, and once ever 60s it will check for open sessions ... if non are found it will kill all instances of vscode on the box and then kill itself.

**Comment by roblourens** [comment]
The server does shut itself down about 10 minutes after the last extension host disconnects. The point you make about the bad result when the server is running but its files have been deleted is true and we have an issue to do a better job at recovering from that state.

**Comment by caffeineaddiction** [comment]
@roblourens is this 10m shut down a configurable option? can I make it shorter?

**Comment by roblourens** [comment]
Not currently
