### ISSUE TITLE
Remote Tunnels Extension Stable Release Date

### ISSUE THREAD

**Issue by aleleba** [microsoft/vscode-remote-release#9964]
@bamurtaugh hi, hope you are doing great, sure, is the one related to this issue: https://github.com/microsoft/vscode-remote-release/issues/8788

_Originally posted by @aleleba in https://github.com/microsoft/vscode-remote-release/issues/9865#issuecomment-2158654198_

@bamurtaugh, hi, created a new one for give some following up to the release process 👍🏼 , thank you for all

**Comment by bamurtaugh** [comment]
Hi there - thanks for following up! I think I'm still unclear on the original ask from https://github.com/microsoft/vscode-remote-release/issues/9865#issuecomment-2142642925 - 

This sounds like you observed different behavior using the pre-release version of the Remote-Tunnels extension vs the release version - is that correct? Could you please share what feature was missing?

**Comment by aleleba** [comment]
Sure with pleasure I give more context, since two months ago the stable release 1.5.1 was not upgraded to any version.
![Captura de pantalla 2024-06-10 a la(s) 10 33 33 a  m](https://github.com/microsoft/vscode-remote-release/assets/28767814/8273faf9-6d38-46b8-a40a-3db3b4ed9802)
Right now only are some updates on prerelease versions.
![Captura de pantalla 2024-06-10 a la(s) 10 34 51 a  m](https://github.com/microsoft/vscode-remote-release/assets/28767814/bcfad569-ef41-4a2a-b99f-0184fc027623)
On stable release 
![Captura de pantalla 2024-06-10 a la(s) 10 35 52 a  m](https://github.com/microsoft/vscode-remote-release/assets/28767814/1e4b7239-bdb5-4f27-9b38-b08399e3fbab)
The port fordwarding is not let me to make public my port fordwarding to connect two apps, one front-end and one back-end.
The prerelease version let me to make public my port fordwarding to connect my back-end and front-end app
![Captura de pantalla 2024-06-10 a la(s) 10 38 08 a  m](https://github.com/microsoft/vscode-remote-release/assets/28767814/c36e4fc8-6807-4ccc-8779-f7bfb2f79d20)

**Comment by aleleba** [comment]
Hi @connor4312 @alexr00 do you know when this will be available?

**Comment by connor4312** [comment]
Sorry for the delay, new stable version has been published

**Comment by aleleba** [comment]
thank you @connor4312 for all your help and assistance 👍🏼
