### ISSUE TITLE
Git repository detected with dubious ownership

### ISSUE THREAD

**Issue by pamelafox** [microsoft/vscode-remote-release#9965]
- VSCode Version:
- 
Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:34:48.028Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
- Local OS Version: Darwin arm64 23.5.0
- Remote OS Version: mcr.microsoft.com/devcontainers/python:3.11
- Remote Extension/Connection Type: Containers

Steps to Reproduce:

I don't know if this will replicate reliably, it is variable for me:

1. Open https://github.com/Azure-Samples/rag-postgres-openai-python/ on Mac OS M1
2. See error when running git commands:

```
vscode ➜ /workspace $ git pull
fatal: detected dubious ownership in repository at '/workspace'
To add an exception for this directory, call:
git config --global --add safe.directory /workspace
```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Not sure

Here is the most recent dev container log:

[remoteContainers-2024-06-10T17-42-16.621Z.log](https://github.com/user-attachments/files/15777210/remoteContainers-2024-06-10T17-42-16.621Z.log)

**Comment by pamelafox** [comment]
Maybe it was a timing issue? After filing this issue, git commands are now working.

**Comment by nataziel** [comment]
I encountered this error today. Not sure if my problem is 100% related to OP but might be relevant.

I was mucking around with automatically installing pre-commit hooks via `"postCreateCommand": "pre-commit install"`, resulting in this error:
```
[22498 ms] Start: Run in container: /bin/sh -c pre-commit install
An error has occurred: FatalError: git failed. Is it installed, and are you in a
 Git repository directory?
Check the log at /home/vscode/.cache/pre-commit/pre-commit.log
[23805 ms] postCreateCommand failed with exit code 1. Skipping any further user-provided commands.
Done. Press any key to close the terminal.
```

This then results in VSCode detecting that the git repository is unsafe, and the same being displayed at the integrated terminal when running git commands.

Changing the `postCreateCommand` to `sudo pre-commit install` fixes this problem, but I'm not really sure why 🤷

**Comment by chrmarti** [comment]
With single containers we check if we need (and can do so safely) add the workspace folder as `safe.directory` after `postCreateCommand` ran. This might explain @nataziel 's case.

When cloning a repo in a volume we update the file ownership to the container user after cloning. This might explain the delay @pamelafox and @mjswensen are seeing.

**Comment by chrmarti** [comment]
> When cloning a repo in a volume we update the file ownership to the container user after cloning. This might explain the delay [@pamelafox](https://github.com/pamelafox) and [@mjswensen](https://github.com/mjswensen) are seeing.

The extension actually waits for the `chown` to finish before continuing, you shouldn't see it change ownerships.

**Comment by chrmarti** [comment]
The config is using Docker Compose. Fixing this with https://github.com/microsoft/vscode-remote-release/issues/7923.

**Comment by chrmarti** [comment]
Could you give Dev Containers 0.373.0-pre-release a try and let me know if that works? That fixes the Docker Compose case and also covers cases where the Git root folder is between the workspace folder and the mount point.

**Comment by pamelafox** [comment]
Unfortunately my extensions sidebar won't load. (My VS Code seems to be in rough shape these days). If I get that to load, or if there's a way to programmatically install that extension from the terminal, then I can try it.

**Comment by chrmarti** [comment]
> Unfortunately my extensions sidebar won't load. (My VS Code seems to be in rough shape these days). If I get that to load, or if there's a way to programmatically install that extension from the terminal, then I can try it.

Please open an issue for the sidebar not loading if you haven't already, so we can look into that.

You can install the latest prerelease version from the command line with:
```
code --install-extension ms-vscode-remote.remote-containers@prerelease --force
```
