### ISSUE TITLE
Can't forward a port

### ISSUE THREAD

**Issue by pamelafox** [microsoft/vscode-remote-release#9966]
- VSCode Version:
Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:34:48.028Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

- Local OS Version: Darwin arm64 23.5.0
- Remote OS Version: mcr.microsoft.com/devcontainers/python:3.11
- Remote Extension/Connection Type: Containers

Steps to Reproduce:

1. Open https://github.com/Azure-Samples/rag-postgres-openai-python/ in Dev Container on Mac M1
2. Go to Ports Tab, click "Add Port", enter 5174, press enter, see nothing happen.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Not sure

**Comment by chrmarti** [comment]
I get the entry in the table:
![Image](https://github.com/user-attachments/assets/2c71bd54-0d87-412d-b27e-51a6b7237047)

Is the port not added to the table in your case?

**Comment by pamelafox** [comment]
I just updated to latest VS Code and re-opened in dev container. It is now working for me. I'll re-open if the problem appears again.
