### ISSUE TITLE
Permanently forwarded ports

### ISSUE THREAD

**Issue by emilsall** [microsoft/vscode-remote-release#997]
Issue Type: <b>Feature Request</b>

I added a "LocalForward" directive to my SSH config and initially thought it didn't work because the sidebar still says "No ports are being forwarded". However, it actually is working!

So I think that permanently forwarded ports should be listed in the sidebar as well? Or at least the sidebar should be titled "Temporarily forwarded ports" or something. 

Sidenote: Would be nice to be able to "convert" a temporary port into a setting automatically from the sidebar.

Extension version: 0.44.2
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 5.0.0-15-generic
Remote OS version: Linux x64 4.9.0-9-amd64

**Comment by milsto** [comment]
I also came here to report this issue. I was expecting the same behavior as @emilsall noted.

I would additionally argue that not showing forwarded ports from config in "Forwarded ports" panel should be considered a bug.

Other suggestion is very welcome as feature requests for me also.

**Comment by ajit555db** [comment]
I too wish to set a few "forwarded ports" permanently. 

I use VScode for kubernetes apps hosted in linux server and manage it from VSCode in Windows 10. For K8s dashboard and k8s desktop clients as well as few apps, I need to set these ports manually every time. Wish it these port's name and value can be persisted at least so that every time I don't have to type it out.

**Comment by emilsall** [comment]
> I too wish to set a few "forwarded ports" permanently.
> Wish it these port's name and value can be persisted at least so that every time I don't have to type it out.

Adding a LocalForward directive to the SSH config _does work_ and persists between sessions/reboots. It's just not indicated in the interface.

**Comment by bamurtaugh** [comment]
Hi all, does setting "Remote: Restore Forwarded Ports" help with this issue at all? 

![image](https://user-images.githubusercontent.com/25310137/96788967-2a98f480-13a9-11eb-92b1-b9ea5e09b7f4.png)

**Comment by samwho** [comment]
I don't know exactly why, but I've found that occasionally that setting doesn't work and I'm back to 0 forwarded ports.

I use a multi-root workspace, and am using Remote SSH'd into a VM on the same machine.

**Comment by roblourens** [comment]
Lots of changes here - you can forward ports via ssh, or via vscode
