### ISSUE TITLE
Devcontainer not working anymore with docker compose V2. 

### ISSUE THREAD

**Issue by cristiangabor** [microsoft/vscode-remote-release#9978]
- VSCode Version:
- Local OS Version:
- Remote OS Version:
- Remote Extension/Connection Type: Containers/WSL/Server

- Logs:

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
Please provide more details.

**Comment by dlencer** [comment]
It is broken for me too. From the output I get, it seems the extension is trying to call old-style `docker-compose` rather than the current `docker compose`.

**Comment by chrmarti** [comment]
It first tries `docker-compose` and if that doesn't exist uses `docker compose`. (There is a change being prepared to reverse the order.)

**Comment by dlencer** [comment]
Thank you for your quick reply. I am using WSL2/Docker Desktop and it seems I cannot easily get rid of `docker-compose` on my PATH, but judging form the printed out version (`Docker Compose version: 2.27.1-desktop.1`), it seems to be using the current version nonetheless. Nevertheless, I am unable to get my devcontainer up and running, it takes forever doing `docker-compose config`; during that, VS Code disconnects, then somehow manages to reconnect to a redrawn window, showing at least the name of the right folder, but that is it. In the "Window" section of Output, I see a constant stream of messages like `2024-06-21 11:44:33.185 [info] [LocalProcess0][resolveAuthority(dev-container,1)][586009ms] waiting...`. Might be I rather suffer from the issue in https://github.com/microsoft/vscode-remote-release/issues/9506.

**Comment by chrmarti** [comment]
Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)

**Comment by dlencer** [comment]
It is embarassing to say, but I found a typo in one of my compose files (representing layers; base, dev, staging, production, ...). It caused `docker compose config` to go wild, unfortunately without printing any error messages. After fixing the compose file, everything is working again.

Many thanks again for your support. I really enjoy dev containers with VS Code, it is a great tool.
