### ISSUE TITLE
Devcontainer initializeCommand does not get pushed to interactive terminal

### ISSUE THREAD

**Issue by aniongithub** [microsoft/vscode-remote-release#9987]
- VSCode Version: 1.90.1
- Devcontainer extension version: v0.369.0 and v0.373.0 (pre-release)
- Local OS Version: Ubuntu 22.04
- Remote OS Version: Ubuntu 22.04
- Remote Extension/Connection Type: DevContainer

Steps to Reproduce:

1. Write an interactive command in initializeCommand, one that waits for input, for ex: `read -p "Continue? (Y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1`
2. Rebuild and reopen in container

It should behave the same as postAttachCommand, pushing it to an interactive terminal. Instead, it stays in the devcontainer logs terminal and hangs the devcontainer start because the user cannot enter any input here.

Does this issue occur when you try this locally?: Yes (this runs on the host machine)
Does this issue occur when you try this locally and all extensions are disabled?: n/a, this is related to the devcontainer extension.

This seems to be re-re-regression of these issues
1. https://github.com/microsoft/vscode-remote-release/issues/2434#issuecomment-949437987
2. https://github.com/microsoft/vscode-remote-release/issues/6557

**Comment by rubensa** [comment]
I have same problem on **GitHub Codespaces**?

I was trying to start a new **codespace** with a **devcontainer** that contains an **intitializeCommand** with a `read` command to prompt the user but, despite I can access the terminal with the prompt, It seems I can't type there (and the container can't be fully initialized).

**Comment by chrmarti** [comment]
This should be fixed in Dev Containers with https://github.com/microsoft/vscode-remote-release/issues/10032.

@rubensa This might be specific to Codespaces, could you ask here: https://github.com/orgs/community/discussions/categories/codespaces. Thanks.

**Comment by rubensa** [comment]
https://github.com/orgs/community/discussions/132199

**Comment by aniongithub** [comment]
> This should be fixed in Dev Containers with #10032.
> 
> @rubensa This might be specific to Codespaces, could you ask here: https://github.com/orgs/community/discussions/categories/codespaces. Thanks.

Why was this closed as completed? This is not fixed in both local and codespaces.
