### ISSUE TITLE
`az login` broken when using remote tunnel

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode-remote-release#9989]
- VSCode Version: 1.90.2
- Local OS Version: Windows 11
- Remote OS Version: Ubuntu 22.04
- Remote Extension/Connection Type: remote tunnel (server)

Steps to Reproduce:

1. Log into machine to start tunnel
2. Run `code tunnel`
3. Connect via VS Code to tunnel
4. Run `az login` in VS Code terminal
5. Observe that web browser gets opened
6. Observe that redirect happens to `http://localhost:35099/?code=0.ARoAv4j5c...` (random port) failing to load page

Manual hack:
- Go to VS Code -> Ports
- Copy the Local address of the forwarded port, e.g. `https://6fv645v1-....uks1.devtunnels.ms/`
- Replace the domain and port of the redirect address with the devtunnels address: `https://6fv645v1-....uks1.devtunnels.ms/?code=0.ARoAv4j5c...`
- Go to that page
- Observe that login finishes successfully

Note that this issue is the same as https://github.com/microsoft/vscode-remote-release/issues/9794.

This is a bug and needs to be addressed as it prevents using Azure when working inside remote tunnels.

**Comment by connor4312** [comment]
Merging into https://github.com/microsoft/vscode-remote-release/issues/9195
