### ISSUE TITLE
Not able to open VScode Tunnel with Azure Authentication (microsoft business account)

### ISSUE THREAD

**Issue by james7x1** [microsoft/vscode-remote-release#9990]
I have the latest public release of code-insiders, but I am still unable to use my work domain @yourBusiness.com to open a VScode tunnel. This is important to maintain encryption in the tunnel process and IT compliance. Any suggestions or help you can provide is much appreciated!

Related to:
https://github.com/microsoft/vscode-remote-release/issues/8908

- VSCode Version: 1.91.0-insider
- Local OS Version: Windows 11
- Remote OS Version: Ubuntu 22.04.2
- Remote Extension/Connection Type: Remotes Tunnels Extension

- Logs:

Steps to Reproduce:

1. `code-insiders tunnel user login --provider microsoft`
2. Click provided link and copy auth code
3. Enter enterprise (Azure/O365+Sharepoint) domain-linked SSO email (xxx@mybusiness.com)

**Comment by connor4312** [comment]
Currently the tunnel service does not support authentication in other tenants. If/when Azure resources for devtunnels are made public this can change, but currently this is not something we can support. I suggest other remote strategies such as a Remote - SSH or the local `code serve-web` command in the meantime.
