### ISSUE TITLE
Extensions not installed in devcontainer when using VPN

### ISSUE THREAD

**Issue by tomj-99** [microsoft/vscode-remote-release#9997]
- VSCode Version: 1.90.1
- Local OS Version: Happens on Rocky Linux 9 and Windows 10 22H2
- Remote OS Version: docker centos:stream9 image
- Remote Extension/Connection Type: DevContainer

I am trying to set up my devcontainer but some extensions (~half  of them) that are listed are not installed. Here is a list of all extensions that I want to install:

```
"customizations": {
        // Configure properties specific to VS Code.
        "vscode": {
            // Add the IDs of extensions you want installed when the container is created.
            "extensions": [
                "donjayamanne.githistory",
                "jeff-hykin.better-cpp-syntax",
                "mhutchie.git-graph",
                "ms-vscode.cmake-tools",
                "ms-vscode.cpptools",
                "ms-vscode.cpptools-extension-pack",
                "ms-vscode.cpptools-themes",
                "ms-vsliveshare.vsliveshare",
                "njpwerner.autodocstring",
                "shardulm94.trailing-spaces",
                "SonarSource.sonarlint-vscode",
                "TabNine.tabnine-vscode",
                "twxs.cmake",
                "VisualStudioExptTeam.intellicode-api-usage-examples",
                "VisualStudioExptTeam.vscodeintellicode"
            ]
        }
    }
```

Some are installed successfully, some are not. I get this log:

```
2024-06-22 18:07:17.294 [error] Error: Failed Installing Extensions: jeff-hykin.better-cpp-syntax, donjayamanne.githistory, mhutchie.git-graph, njpwerner.autodocstring, ms-vsliveshare.vsliveshare, sonarsource.sonarlint-vscode, shardulm94.trailing-spaces, twxs.cmake, tabnine.tabnine-vscode, visualstudioexptteam.vscodeintellicode, visualstudioexptteam.intellicode-api-usage-examples
    at a.installExtensions (/vscode/vscode-server/bin/linux-x64/611f9bfce64f25108829dd295f54a6894e87339d/out/vs/server/node/server.main.js:145:9966)
```

For the extensions that are not installed, I also get something like:
```
2024-06-22 18:07:12.162 [info] Getting Manifest... twxs.cmake
2024-06-22 18:07:12.350 [info] Skipping the packed extension as it cannot be installed twxs.cmake self-signed certificate in certificate chain
```

After opening my project in the container and navigating to the extensions tab, I can manually install (by clicking `Install in Dev Container`) all the extensions successfully that failed previously while creating the devcontainer which is very strange. Also on my host machine, I can install all of them without any issues. It only fails while creating the container.

I am using the VPN of my company without the VPN everything works fine and all extensions are installed successfully but deactivating the VPN is not an option.

There clearly seems to be an issue in installing the extensions from `devcontainer.json` as they can be installed manually or am I missing any config?

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/9994. Thanks.
