### ISSUE TITLE
ssh faild

### ISSUE THREAD

**Issue by EngMichaelMART** [microsoft/vscode-remote-release#9999]
Type: <b>Bug</b>

[17:19:24.571] Opening exec server for ssh-remote+ip
[17:19:24.594] Initizing new exec server for ssh-remote+ip
[17:19:24.597] Using commit id "5437499feb04f7a586f677b155b039bc2b3669eb" and quality "stable" for server
[17:19:24.599] Install and start server if needed
[17:19:28.435] getPlatformForHost was canceled
[17:19:28.435] Exec server for ssh-remote+ip failed: Error: Connecting was canceled
[17:19:28.436] Error opening exec server for ssh-remote+ip: Error: Connecting was canceled

Extension version: 0.112.0
VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Connection to 'SSH' could not be established 
Connection to 'SSH' could not be established 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|39.72GB (16.75GB free)|
|Process Argv|--crash-reporter-id b48f1d27-f86e-4216-85b1-99a7f7bea327|
|Screen Reader|no|
|VM|50%|

Connection to 'SSH' could not be established 

Connection to 'SSH' could not be established 
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
showvideot:31016892
chatpanelc:31048052
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
legacy_priority:31077528

```

</details>

**Comment by roblourens** [comment]
`getPlatformForHost was canceled`

Looks like you dismissed or ignored the dialog to select the remote platform
